In [1]:
# Essential imports
import re

from io import StringIO

import pandas as pd
import numpy as np

from Bio import SeqIO
from bioservices import UniProt

import tqdm

# Connect to UniProt service
u = UniProt(verbose=False)

In [4]:
my_file = open("Accession.txt", "r") 
  
# reading the file 
data = my_file.read() 
  
# replacing end splitting the text  
# when newline ('\n') is seen. 
data_into_list = data.split("\n") 
print(data_into_list) 
my_file.close()

['A0A011VQM7', 'A0A063ZJU6', 'A0A081EVR3', 'A0A099I9L1', 'A0A0D8IWY3', 'A0A0E2HBL2', 'A0A0F0CIE1', 'A0A0F9HQB3', 'A0A0G3WG46', 'A0A0G9LEF6', 'A0A0H5SG89', 'A0A0J6WZA7', 'A0A0J6ZRU4', 'A0A0J9EMW5', 'A0A0M2NHW4', 'A0A0M6WC26', 'A0A0M6WCZ2', 'A0A0M9AS13', 'A0A0R2HL96', 'A0A0S2W112', 'A0A0U5JBG5', 'A0A0W7TMH6', 'A0A0X8VAS2', 'A0A136Q6K1', 'A0A136WGT4', 'A0A140DTE7', 'A0A143Y517', 'A0A143Y9S4', 'A0A143YNF2', 'A0A143YTA3', 'A0A143YWY4', 'A0A143YZV1', 'A0A143Z212', 'A0A143ZCA8', 'A0A151AI36', 'A0A169X118', 'A0A173R3X4', 'A0A173R662', 'A0A173SMJ4', 'A0A173TUR6', 'A0A173V441', 'A0A173W538', 'A0A173X4T2', 'A0A173XV88', 'A0A173XVK8', 'A0A173Z4K3', 'A0A173ZTK6', 'A0A174C5U1', 'A0A174D1D6', 'A0A174GH26', 'A0A174H6C4', 'A0A174JG28', 'A0A174RYE8', 'A0A174T4F8', 'A0A174TIU3', 'A0A174VZ55', 'A0A174XKK3', 'A0A174YTX7', 'A0A174Z5H4', 'A0A175A4T9', 'A0A175ABC8', 'A0A176U687', 'A0A1B1YE78', 'A0A1B1YLE9', 'A0A1C0BVB4', 'A0A1C5KIM4', 'A0A1C5M0W8', 'A0A1C5MDL8', 'A0A1C5MK12', 'A0A1C5N7S1', 'A0A1C5PFK7', 'A0A1C5PIG4', 'A0A1C5PQC5', 'A0A1C5PTP6', 'A0A1C5PX47', 'A0A1C5QAX9', 'A0A1C5QDA2', 'A0A1C5QHK8', 'A0A1C5QX74', 'A0A1C5R1D9', 'A0A1C5R365', 'A0A1C5R381', 'A0A1C5RAN1', 'A0A1C5S8B5', 'A0A1C5SQE8', 'A0A1C5SVL0', 'A0A1C5T8Y6', 'A0A1C5TF49', 'A0A1C5U2K1', 'A0A1C5UAP1', 'A0A1C5UEH7', 'A0A1C5UU75', 'A0A1C5VCM0', 'A0A1C5VT92', 'A0A1C5WY82', 'A0A1C5XWN4', 'A0A1C5Y526', 'A0A1C5YFR7', 'A0A1C5YH18', 'A0A1C5Z331', 'A0A1C5Z9P9', 'A0A1C5ZTV2', 'A0A1C6B393', 'A0A1C6B4K0', 'A0A1C6BQA1', 'A0A1C6BXH2', 'A0A1C6CHG3', 'A0A1C6CSF9', 'A0A1C6CXT8', 'A0A1C6D1W9', 'A0A1C6DAP7', 'A0A1C6DLP9', 'A0A1C6DWH2', 'A0A1C6E048', 'A0A1C6E379', 'A0A1C6F4A8', 'A0A1C6FKD5', 'A0A1C6G7R3', 'A0A1C6G8E0', 'A0A1C6G8R0', 'A0A1C6GHV1', 'A0A1C6GPW7', 'A0A1C6H3W0', 'A0A1C6HLR1', 'A0A1C6HNA9', 'A0A1C6HP51', 'A0A1C6JHM1', 'A0A1C6K3R3', 'A0A1C6KIH8', 'A0A1C7GTZ0', 'A0A1C7HSA7', 'A0A1C7IDV8', 'A0A1D3TYQ0', 'A0A1D9NY31', 'A0A1F8V8B8', 'A0A1F9FQX1', 'A0A1F9ZPG7', 'A0A1G4QLQ0', 'A0A1G4SPK4', 'A0A1G4VHU5', 'A0A1G5B658', 'A0A1G5BLA9', 'A0A1G5DDJ5', 'A0A1G5DER5', 'A0A1G5EK45', 'A0A1G5FBQ7', 'A0A1G5RVB0', 'A0A1G5WAS9', 'A0A1G5WH50', 'A0A1G6AA59', 'A0A1G6AEH9', 'A0A1G6BHE0', 'A0A1G6C6K5', 'A0A1G6KUG1', 'A0A1G7RHP6', 'A0A1G8BB52', 'A0A1G8V2D8', 'A0A1G8VFZ5', 'A0A1G9BC39', 'A0A1G9IKK4', 'A0A1G9THY2', 'A0A1G9XUV1', 'A0A1H0YSA0', 'A0A1H1HR70', 'A0A1H2TZK5', 'A0A1H2V0V3', 'A0A1H3DIU9', 'A0A1H3HZ52', 'A0A1H3LXY5', 'A0A1H3Z0R0', 'A0A1H3ZKY2', 'A0A1H4EZX0', 'A0A1H5WFC4', 'A0A1H5YYF4', 'A0A1H6FT59', 'A0A1H6INP9', 'A0A1H6J2A5', 'A0A1H6R9C6', 'A0A1H6W8Z9', 'A0A1H7IQT2', 'A0A1H7M3E0', 'A0A1H7NPU9', 'A0A1H8S6J8', 'A0A1H9A9D8', 'A0A1H9AGY6', 'A0A1H9GAG5', 'A0A1H9J573', 'A0A1H9JDC6', 'A0A1H9P153', 'A0A1H9P3M9', 'A0A1H9Z210', 'A0A1I0G858', 'A0A1I0H5B4', 'A0A1I0HDV9', 'A0A1I0IK57', 'A0A1I0PYA2', 'A0A1I0QEC7', 'A0A1I0ZNG3', 'A0A1I1D0R6', 'A0A1I1HT54', 'A0A1I1MY45', 'A0A1I2AKI3', 'A0A1I2NIB4', 'A0A1I2TGT7', 'A0A1I3B7Y0', 'A0A1I3FXW0', 'A0A1I3I9Y5', 'A0A1I3M286', 'A0A1I4EUS9', 'A0A1I4ZMN5', 'A0A1I5FF58', 'A0A1I5RRK2', 'A0A1I5SDH6', 'A0A1I5Y4A3', 'A0A1I6FK65', 'A0A1I6JQR0', 'A0A1I6KGS1', 'A0A1I6PBV6', 'A0A1I6YNS1', 'A0A1I7GLL6', 'A0A1I7IQQ2', 'A0A1I7ITC5', 'A0A1J4LTC1', 'A0A1K1NCM8', 'A0A1K1PQ76', 'A0A1L5KYB6', 'A0A1L8N3F6', 'A0A1L8PEC7', 'A0A1L8STM4', 'A0A1M2Z9L9', 'A0A1M4ZJQ1', 'A0A1M5QDY1', 'A0A1M6AMI5', 'A0A1M6CHL9', 'A0A1M6FDK6', 'A0A1M7LS20', 'A0A1M7N5X0', 'A0A1M7SHA9', 'A0A1N6HUP0', 'A0A1N7BYW4', 'A0A1N7EMQ2', 'A0A1N7ESV5', 'A0A1P8RI15', 'A0A1Q6NJY1', 'A0A1Q6PWR8', 'A0A1Q6Q4S8', 'A0A1Q6QFY3', 'A0A1Q6R4W6', 'A0A1Q9JE84', 'A0A1Q9YFT7', 'A0A1Q9YMG2', 'A0A1S8AZU6', 'A0A1S9BS50', 'A0A1S9C9P7', 'A0A1S9CM79', 'A0A1S9CTJ6', 'A0A1T4JI33', 'A0A1T4JSS3', 'A0A1T4M6N6', 'A0A1T4MPV2', 'A0A1T4V9X3', 'A0A1T4XH92', 'A0A1T4XJ61', 'A0A1T5FXA3', 'A0A1U7EUA9', 'A0A1U7NFL4', 'A0A1U7NFM1', 'A0A1V2M684', 'A0A1V2M6R2', 'A0A1V2MD01', 'A0A1V2YEL3', 'A0A1V4SQP7', 'A0A1V5Q5C8', 'A0A1V5TUL5', 'A0A1V6AN14', 'A0A1V6FSD6', 'A0A1W1IDJ2', 'A0A1W1IEF4', 'A0A1W1IG68', 'A0A1W1ZEY0', 'A0A1W2AX19', 'A0A1W2C1Z4', 'A0A1W2CRU9', 'A0A1X4HAD1', 'A0A1Y3A9W7', 'A0A1Y3AEB2', 'A0A1Y3AJI8', 'A0A1Y3RFC7', 'A0A1Y3RRY4', 'A0A1Y3S9H5', 'A0A1Y3SMX9', 'A0A1Y3TM33', 'A0A1Y3TZQ9', 'A0A1Y3WRK2', 'A0A1Y3X5L2', 'A0A1Y3ZW06', 'A0A1Y4BSP8', 'A0A1Y4F2V1', 'A0A1Y4HI56', 'A0A1Y4IQK8', 'A0A1Y4J8M1', 'A0A1Y4L5P0', 'A0A1Y4LM49', 'A0A1Y4LNQ6', 'A0A1Y4NDW8', 'A0A1Y4NS57', 'A0A1Y4NXY3', 'A0A1Y4T9I4', 'A0A1Y4TK26', 'A0A1Y4URH8', 'A0A1Z2XSS6', 'A0A202E691', 'A0A238WFM2', 'A0A238X318', 'A0A239QIB5', 'A0A239R8Y4', 'A0A252F2L0', 'A0A256HFN6', 'A0A256HIH6', 'A0A256HU74', 'A0A256HVI6', 'A0A256HXJ0', 'A0A256IAU5', 'A0A256J2E6', 'A0A256KBC6', 'A0A261EQJ5', 'A0A285PCX6', 'A0A285PVN6', 'A0A285RSQ4', 'A0A2A2FDF5', 'A0A2A5QZ19', 'A0A2A6ZC76', 'A0A2A7A1L3', 'A0A2A7AAI1', 'A0A2A7ART1', 'A0A2A7AY63', 'A0A2A7B470', 'A0A2A7BC95', 'A0A2B7GTQ4', 'A0A2G1WEG4', 'A0A2G1WTK5', 'A0A2G3DSU6', 'A0A2G3E3V2', 'A0A2G3E8V2', 'A0A2G3PYR5', 'A0A2J4JM91', 'A0A2K4ZNQ6', 'A0A2K9P203', 'A0A2N0UWP7', 'A0A2N1RFZ0', 'A0A2N1ZZK7', 'A0A2N2A3X2', 'A0A2N2BXD1', 'A0A2N2CN54', 'A0A2R6CGI2', 'A0A2R6DG65', 'A0A2R6EHW0', 'A0A2R6ETP9', 'A0A2R6EZG2', 'A0A2R6FM49', 'A0A2R6FX01', 'A0A2R6FYC5', 'A0A2R6GLV1', 'A0A2R6H2H7', 'A0A2R6HFY0', 'A0A2R6HGN0', 'A0A2R6I3E5', 'A0A2R6IP35', 'A0A2R6JNJ8', 'A0A2R6K016', 'A0A2R6KFC5', 'A0A2R6L1E7', 'A0A2R6LIY7', 'A0A2R6LZL3', 'A0A2R6M9Y9', 'A0A2R6N841', 'A0A2R6N9Z3', 'A0A2S0M5G2', 'A0A2S0M903', 'A0A2T0B6K8', 'A0A2T3FE90', 'A0A2T5IEE6', 'A0A2T5IJN6', 'A0A2T5IP85', 'A0A2U2EER7', 'A0A2V1JRW0', 'A0A2V2CWD0', 'A0A2V2DIY8', 'A0A2V2DR78', 'A0A2V2DSP1', 'A0A2V2E7V3', 'A0A2V2EWK3', 'A0A2V2EXD4', 'A0A2V2F5A3', 'A0A2V2GRB1', 'A0A2Y9CAP5', 'A0A2Z2HRJ4', 'A0A315Y7U6', 'A0A316C0R3', 'A0A316L7Q2', 'A0A316LYI4', 'A0A316M754', 'A0A316PAM5', 'A0A316Q5V2', 'A0A316QTT7', 'A0A316RBP1', 'A0A317G0I6', 'A0A317ULB1', 'A0A318XMF9', 'A0A328UCK6', 'A0A329T9W9', 'A0A329TIZ6', 'A0A329U1X5', 'A0A329U912', 'A0A329U9C4', 'A0A329UNK8', 'A0A343TP47', 'A0A345E078', 'A0A345E9S5', 'A0A346PKS2', 'A0A348N845', 'A0A348SZ39', 'A0A349IJT1', 'A0A350J6B8', 'A0A350VVQ9', 'A0A350WYP9', 'A0A350X0B6', 'A0A351PIU1', 'A0A351PVI3', 'A0A351Q9K7', 'A0A351R4U7', 'A0A351THN6', 'A0A351XAB7', 'A0A351XND4', 'A0A352B953', 'A0A352CNH9', 'A0A352CV27', 'A0A352DPV9', 'A0A352SI43', 'A0A352T829', 'A0A352TBQ4', 'A0A352WLA9', 'A0A353S6E3', 'A0A354CV11', 'A0A354D398', 'A0A354M8Q0', 'A0A354MTA6', 'A0A354UC59', 'A0A354UXJ2', 'A0A354WS17', 'A0A355L532', 'A0A355U0T8', 'A0A355YJX2', 'A0A356JZA1', 'A0A357AR78', 'A0A357TLZ9', 'A0A358M7Q9', 'A0A358WFN9', 'A0A359JIV1', 'A0A365TD36', 'A0A367G5A8', 'A0A367G6Z8', 'A0A367GD87', 'A0A368NBY6', 'A0A372MIA9', 'A0A373HQJ5', 'A0A373IZ41', 'A0A373LKK3', 'A0A373LV07', 'A0A373NBW8', 'A0A373NHW0', 'A0A373TDA5', 'A0A373VPI8', 'A0A373W3B8', 'A0A373WB21', 'A0A373WB62', 'A0A373WNC9', 'A0A374AZ37', 'A0A374BTC5', 'A0A374BV99', 'A0A374E8I7', 'A0A374ESQ7', 'A0A374HYA9', 'A0A374JZE1', 'A0A374NIG5', 'A0A374UM72', 'A0A374VUC3', 'A0A380RE50', 'A0A383TB64', 'A0A383TDA1', 'A0A383TEW4', 'A0A391P2Q7', 'A0A395V2H0', 'A0A395WC27', 'A0A395XAX9', 'A0A395ZJI4', 'A0A396KF07', 'A0A396KTS7', 'A0A396LLV1', 'A0A396QBZ7', 'A0A397S8C4', 'A0A3A5JCB5', 'A0A3A6CZX2', 'A0A3A6DCQ4', 'A0A3A6DXE2', 'A0A3A6F2C6', 'A0A3A6JGR4', 'A0A3A6JNP8', 'A0A3A6Q4N4', 'A0A3A6QA08', 'A0A3A8U1R4', 'A0A3A8WBS0', 'A0A3A8YRM8', 'A0A3A8ZR18', 'A0A3A9A686', 'A0A3A9AHU2', 'A0A3A9EQQ1', 'A0A3A9EZ61', 'A0A3A9FED2', 'A0A3A9GFS9', 'A0A3A9SKZ0', 'A0A3A9SXB6', 'A0A3A9T3Z5', 'A0A3B8UVC8', 'A0A3B8WX04', 'A0A3B9DWD0', 'A0A3B9RR30', 'A0A3B9SH16', 'A0A3B9T2C8', 'A0A3B9WUZ1', 'A0A3C0BHT2', 'A0A3C0J8P0', 'A0A3C0NNI1', 'A0A3C0TH36', 'A0A3C0U1E6', 'A0A3C0VS63', 'A0A3C0WZ02', 'A0A3C0ZR78', 'A0A3C1A6S1', 'A0A3C1C0C6', 'A0A3C1H5S6', 'A0A3C1K4P1', 'A0A3C1SJG2', 'A0A3C1YM26', 'A0A3D0DNQ2', 'A0A3D0L7S0', 'A0A3D0LDA8', 'A0A3D1HCR6', 'A0A3D1HWC2', 'A0A3D1M6Q9', 'A0A3D1PR94', 'A0A3D1VIG2', 'A0A3D1YAC0', 'A0A3D2A8Z7', 'A0A3D2DN89', 'A0A3D2H4D1', 'A0A3D2HRD6', 'A0A3D2I2I4', 'A0A3D2IMX9', 'A0A3D2KFJ0', 'A0A3D2N5B5', 'A0A3D2TS24', 'A0A3D2YDM4', 'A0A3D3FD73', 'A0A3D3W946', 'A0A3D4CDJ0', 'A0A3D4JMG0', 'A0A3D4KWZ7', 'A0A3D4LRI2', 'A0A3D4QBE3', 'A0A3D4S6E4', 'A0A3D4W5K9', 'A0A3D4XAC3', 'A0A3D5IDU5', 'A0A3D5PCJ0', 'A0A3D5PVN4', 'A0A3D5T795', 'A0A3D5WGV8', 'A0A3E2N433', 'A0A3E2T713', 'A0A3E2TW06', 'A0A3E2UCG9', 'A0A3E2UHE6', 'A0A3E2VY88', 'A0A3E2W4X7', 'A0A3E3E2L2', 'A0A3E3HW34', 'A0A3E4EG44', 'A0A3E4LX30', 'A0A3E4LZF5', 'A0A3E4X059', 'A0A3E4Y6Y1', 'A0A3E5AD41', 'A0A3E5ANY3', 'A0A3E5GL33', 'A0A3G5FID2', 'A0A3G9JI35', 'A0A3M0CVW1', 'A0A3N0I4G0', 'A0A3N1XQV6', 'A0A3N6LYC9', 'A0A3N6MIK2', 'A0A3P3RFN3', 'A0A3Q9EFA7', 'A0A3R6HVQ8', 'A0A3R6LP12', 'A0A3R6NVB4', 'A0A3R6S1G0', 'A0A3R6S323', 'A0A3R6T2E2', 'A0A3R6TUH4', 'A0A3R6VD02', 'A0A3R6W9Z0', 'A0A3R6XWA9', 'A0A3R7JYP2', 'A0A410TQW1', 'A0A412ESC4', 'A0A412I1L5', 'A0A412JAI5', 'A0A412L3Z0', 'A0A412Q5D9', 'A0A412Z6T2', 'A0A413CZM9', 'A0A413G885', 'A0A413I5V5', 'A0A413Q4A5', 'A0A413QIA9', 'A0A413RD45', 'A0A413SL34', 'A0A413U0U1', 'A0A413UEQ5', 'A0A413YZC1', 'A0A414A8A1', 'A0A414ARU4', 'A0A414B8U4', 'A0A414I9E5', 'A0A414JCA5', 'A0A414KBZ4', 'A0A414M657', 'A0A414P7H7', 'A0A414S439', 'A0A414SVC0', 'A0A415D8Z0', 'A0A415H6Z4', 'A0A415HNX0', 'A0A415JYM8', 'A0A415LJU4', 'A0A415MGB1', 'A0A415MX32', 'A0A415TWJ3', 'A0A415WAR6', 'A0A415Y7N4', 'A0A415ZEU8', 'A0A416CAR5', 'A0A416CS21', 'A0A416DJJ8', 'A0A416E8F9', 'A0A416ME66', 'A0A416NNC5', 'A0A416RXX8', 'A0A416T417', 'A0A416VY62', 'A0A417CYC0', 'A0A417FAY0', 'A0A417IKP3', 'A0A417JY11', 'A0A417LI53', 'A0A417PNF3', 'A0A417R8P8', 'A0A417U2N8', 'A0A417UET6', 'A0A417URP4', 'A0A417VTC3', 'A0A419T7T2', 'A0A419WE02', 'A0A425W499', 'A0A425WHC3', 'A0A426DRR9', 'A0A430AFK9', 'A0A448W1N8', 'A0A482Y865', 'A0A482YEN8', 'A0A498EUJ2', 'A0A498FNH3', 'A0A498FNJ6', 'A0A4D6HLC9', 'A0A4P5P5X0', 'A0A4P8WNY4', 'A0A4P8XWV5', 'A0A4P9E8H5', 'A0A4P9TIR6', 'A0A4Q0I9H8', 'A0A4Q1RIE4', 'A0A4Q2K8E9', 'A0A4Q5CCE1', 'A0A4Q7PNC0', 'A0A4R1R5V0', 'A0A4R3K8Z8', 'A0A4S2F9F9', 'A0A4S2HI78', 'A0A4U5JHX5', 'A0A4U7C4Z3', 'A0A4U7CDN6', 'A0A4U7CEX7', 'A0A4U7CTH9', 'A0A4U7CX07', 'A0A4U7D6B8', 'A0A4U7DHS4', 'A0A4U7DV69', 'A0A4U7DZC2', 'A0A4U7ELJ5', 'A0A4U7EV64', 'A0A4U7FCH1', 'A0A4V0Z790', 'A0A4V1YJW1', 'A0A4V2QAD3', 'A0A4V2W5N5', 'A0A4V3G973', 'A0A4V6E5W0', 'A0A4V6E8U1', 'A0A4V6RUF2', 'A0A518SEK0', 'A0A521CIM3', 'A0A544QNG1', 'A0A554NB52', 'A0A562IDY7', 'A0A562IZR5', 'A0A564SQM3', 'A0A564TH32', 'A0A564UFL7', 'A0A564W4H7', 'A0A564WKL7', 'A0A5B9YAF3', 'A0A5C5E511', 'A0A5C5EBG6', 'A0A5C5EC53', 'A0A5D5AW34', 'A0A5N5UD98', 'A0A5N5UDE9', 'A0A5P6VUB9', 'A0A5P9P1L2', 'A0A5S4VQ68', 'A0A644VC25', 'A0A644WX04', 'A0A644XB04', 'A0A644XV74', 'A0A644Z9R4', 'A0A644ZIW7', 'A0A644ZNG6', 'A0A644ZPI2', 'A0A645A974', 'A0A645ACN2', 'A0A645BQS4', 'A0A645CER2', 'A0A645CQT5', 'A0A645DRW9', 'A0A645E3L8', 'A0A645EF30', 'A0A650EQ74', 'A0A6A8KQL6', 'A0A6A9SSQ6', 'A0A6A9TAA9', 'A0A6B0GS07', 'A0A6B0HI83', 'A0A6B0SYS2', 'A0A6B0T2D3', 'A0A6B0VN73', 'A0A6B1IRM6', 'A0A6B9F5H2', 'A0A6B9Y9J0', 'A0A6G2HCU3', 'A0A6G3ZFE0', 'A0A6G4R7Y5', 'A0A6I2U995', 'A0A6I2UKJ2', 'A0A6I3QNZ0', 'A0A6L5GU43', 'A0A6L5T631', 'A0A6L5X9N9', 'A0A6L5YGT4', 'A0A6L5YIP4', 'A0A6L5YR53', 'A0A6L6LSN8', 'A0A6L8S191', 'A0A6L8T527', 'A0A6L8TE47', 'A0A6L8XWF0', 'A0A6M0LJV3', 'A0A6N2TIA4', 'A0A6N2TQM8', 'A0A6N2U4M3', 'A0A6N2U7D4', 'A0A6N2W069', 'A0A6N3AA00', 'A0A6N3FNG1', 'A0A6N3UYL6', 'A0A6N4AJ78', 'A0A6N7IXA3', 'A0A6N7TQV4', 'A0A6N7V013', 'A0A6N7VWI5', 'A0A6N7YD48', 'A0A6N8H849', 'A0A6N9NSM1', 'A0A6N9PAD9', 'A0A6N9PPK6', 'A0A6P1TKI8', 'A0A6S6R667', 'A0A6S6Y9W4', 'A0A7C1PK71', 'A0A7C4F263', 'A0A7C6H9Z6', 'A0A7C6NVQ5', 'A0A7C6R6E7', 'A0A7C7EJX6', 'A0A7C7ENP5', 'A0A7C8HFW2', 'A0A7C8LE71', 'A0A7C9KXI6', 'A0A7D4BPZ6', 'A0A7D4Y6E4', 'A0A7D5E5D8', 'A0A7D5GLZ7', 'A0A7D5HVG8', 'A0A7D5KDW5', 'A0A7D5QD99', 'A0A7D6H3L9', 'A0A7G9FKU0', 'A0A7G9FW70', 'A0A7G9G952', 'A0A7S7EV90', 'A0A7T3RCF2', 'A0A7U9QXY8', 'A0A7U9R1V9', 'A0A7U9R3D7', 'A0A7U9R5J5', 'A0A7U9SYL3', 'A0A7U9T6R9', 'A0A7U9X625', 'A0A7W8CXJ6', 'A0A7W8D0F3', 'A0A7W8G7U4', 'A0A7X2N3T3', 'A0A7X2P6X1', 'A0A7X2PCT8', 'A0A7X2TAH0', 'A0A7X2TKZ1', 'A0A7X3ASZ8', 'A0A7X3BVN0', 'A0A7X3MJ87', 'A0A7X4IAQ1', 'A0A7X4Z7P0', 'A0A7X5ITR0', 'A0A7X5L0V8', 'A0A7X6Z9C6', 'A0A7X7EBR4', 'A0A7X7L7D2', 'A0A7X7MUH8', 'A0A7X7SX82', 'A0A7X8LYU7', 'A0A7X8PRI9', 'A0A7X8ZM44', 'A0A828T2Z2', 'A0A829VSR2', 'A0A830EVM0', 'A0A830EVZ3', 'A0A830EZG5', 'A0A830G1F5', 'A0A830G1M4', 'A0A830G6D7', 'A0A830G7F1', 'A0A830GGW9', 'A0A840SDZ1', 'A0A840UFH7', 'A0A844DI00', 'A0A844DSN8', 'A0A844E1F8', 'A0A844EBW4', 'A0A844GK08', 'A0A844KH10', 'A0A844KJ37', 'A0A845KTN8', 'A0A847CH26', 'A0A847D572', 'A0A847D5D1', 'A0A847N1P0', 'A0A848B3Q7', 'A0A848CN11', 'A0A848EP92', 'A0A855A551', 'A0A897MVN0', 'A0A8A2UE16', 'A0A8A2VRW2', 'A0A8E0R6M4', 'A0A8E8EWD3', 'A0A8F2F0Z1', 'A0A8G1HA07', 'A0A8G1TG76', 'A0A8H9WS41', 'A0A8I0AFC7', 'A0A8I0AML0', 'A0A8J6MF22', 'A0A8J6PFH8', 'A0A8J7H066', 'A0A8J7RSZ7', 'A0A8J7W099', 'A0A8J7ZL15', 'A0A8J8GL03', 'A0A8J8JLU4', 'A0A8J8Q713', 'A0A8J8TCR8', 'A0A8T4GKS8', 'A0A8T4JNY7', 'A0A8T8E5C4', 'A0A8T8LM48', 'A0A8T8WGV8', 'A0A8U0A4W0', 'A0A8U0HXP0', 'A0A8U0IMA8', 'A0A921CQD5', 'A0A921IJH5', 'A0A923L9M9', 'A0A923LJB6', 'A0A923LT31', 'A0A923MJ15', 'A0A926D072', 'A0A926D5K8', 'A0A926DHB2', 'A0A926DNP9', 'A0A926DY84', 'A0A926ESD9', 'A0A926HPS3', 'A0A926I1D1', 'A0A926IBE3', 'A0A926ITG4', 'A0A927TB29', 'A0A927TT45', 'A0A927U2I5', 'A0A927UCK5', 'A0A927UFI4', 'A0A927VG47', 'A0A927Y2C9', 'A0A927Z8W5', 'A0A928MLI3', 'A0A928PDI2', 'A0A928PL84', 'A0A929PZG7', 'A0A931YR25', 'A0A934U4C2', 'A0A934WTK7', 'A0A939R7F4', 'A0A939UAT0', 'A0A939UJD4', 'A0A939UJK2', 'A0A939UZL6', 'A0A939W207', 'A0A939W7Z3', 'A0A939WC21', 'A0A939WLQ2', 'A0A939YG34', 'A0A939YK48', 'A0A939ZC13', 'A0A939ZGI3', 'A0A940AES9', 'A0A940AK69', 'A0A940B3T7', 'A0A940C6R1', 'A0A940HNM9', 'A0A940QD87', 'A0A942AJH2', 'A0A942ZYB7', 'A0A943BNF2', 'A0A943C7N0', 'A0A943ED55', 'A0A943GCU7', 'A0A943GRX7', 'A0A943HIE2', 'A0A943J076', 'A0A943NYK0', 'A0A943QFJ1', 'A0A943RHW1', 'A0A943SBH9', 'A0A943SBR8', 'A0A943TBR5', 'A0A943WTH4', 'A0A943WXB1', 'A0A944A298', 'A0A944FZF3', 'A0A944GNI5', 'A0A945Z3Y5', 'A0A965WS94', 'A0A965XL35', 'A0A965Y123', 'A0A966DAA4', 'A0A970C9J4', 'A0A970EGU6', 'A0A970EUV8', 'A0A970FKS3', 'A0A970GXT2', 'A0A970MCH7', 'A0A970N9Z6', 'A0A970QFG0', 'A0A970R0N6', 'A0A970UKX5', 'A0A970WAS2', 'A0A970XEB3', 'A0A970YC48', 'A0A970ZDE8', 'A0A971AMS4', 'A0A971EW76', 'A0A971G133', 'A0A971NXA9', 'A0A971PA06', 'A0A971UX20', 'A0A971V5Y6', 'A0A971YEX5', 'A0A975CXD7', 'A0A9C7QEY2', 'A0A9C8KA51', 'A0A9D0XUZ3', 'A0A9D0Z6J7', 'A0A9D1AF25', 'A0A9D1AN72', 'A0A9D1DY38', 'A0A9D1E5J4', 'A0A9D1EJI6', 'A0A9D1EP53', 'A0A9D1FSP6', 'A0A9D1GTR9', 'A0A9D1H983', 'A0A9D1HIU9', 'A0A9D1IAD9', 'A0A9D1IAR5', 'A0A9D1IFL3', 'A0A9D1K626', 'A0A9D1LT03', 'A0A9D1MK71', 'A0A9D1NRD6', 'A0A9D1NUM8', 'A0A9D1P0E7', 'A0A9D1PAS3', 'A0A9D1PI59', 'A0A9D1Q0C9', 'A0A9D1QM78', 'A0A9D1R782', 'A0A9D1RDL4', 'A0A9D1RTV9', 'A0A9D1TW90', 'A0A9D1U734', 'A0A9D1V8E3', 'A0A9D1VYY3', 'A0A9D1WJ49', 'A0A9D1XX72', 'A0A9D1XZ54', 'A0A9D1Y891', 'A0A9D1YLV6', 'A0A9D1Z3V4', 'A0A9D1Z6E6', 'A0A9D1ZTG1', 'A0A9D2A8K9', 'A0A9D2AJ74', 'A0A9D2B956', 'A0A9D2C039', 'A0A9D2D658', 'A0A9D2DQS4', 'A0A9D2ET86', 'A0A9D2FHB1', 'A0A9D2FRZ0', 'A0A9D2I7W5', 'A0A9D2IQW6', 'A0A9D2ISQ7', 'A0A9D2L3A6', 'A0A9D2LXL7', 'A0A9D2MKL6', 'A0A9D2MY18', 'A0A9D2MZN5', 'A0A9D2NFE9', 'A0A9D2PL68', 'A0A9D2QIP9', 'A0A9D2RCJ7', 'A0A9D2S172', 'A0A9D2SC64', 'A0A9D2TL68', 'A0A9D5LWH3', 'A0A9D5MBH6', 'A0A9D5MJC7', 'A0A9D5RG35', 'A0A9D8S2E7', 'A0A9D8TW55', 'A0A9D8WSW2', 'A0A9D8X2Q0', 'A0A9D9DY70', 'A0A9D9EKF2', 'A0A9D9HPQ6', 'A0A9D9LYX6', 'A0A9D9PVL6', 'A0A9E0BIP8', 'A0A9E0CWJ9', 'A0A9E0E141', 'A0A9E0ZT81', 'A0A9E1AU37', 'A0A9E1B092', 'A0A9E1BBE4', 'A0A9E1GPE1', 'A0A9E1HWM8', 'A0A9E1LZN9', 'A0A9E1M5L6', 'A0A9E2KLD9', 'A0A9E5G1P0', 'A0A9E5G8Q6', 'A0A9E5SGS8', 'A0A9E5SQC1', 'A0A9E5SYZ5', 'A0A9E6F5C5', 'A0A9E7NER7', 'A0A9N6YWI2', 'A0A9P1BFQ1', 'A0A9Q4L4W6', 'A0A9R1CQJ0', 'A0A9X5BDZ9', 'A0A9X5CBN7', 'A0A9X8CWY5', 'A0A9Y2E7Z6', 'A0AA35G8C0', 'A0AA37EJA7', 'A0AA37N4P2', 'A0AA41K7Q2', 'A0AA42DKQ7', 'A0AA43LQL2', 'A0AA51DY56', 'A0AA96PW81', 'A0AA97D792', 'A0AA97DUI0', 'A0AAE0W0T3', 'A0AAE3ASD5', 'A0AAE3D748', 'A0AAE3D9Q6', 'A0AAE3DG60', 'A0AAE3DN91', 'A0AAE3E6Z3', 'A0AAE3E9V9', 'A0AAE3FHJ3', 'A0AAE3FVH7', 'A0AAE3IFS2', 'A0AAE3IFX0', 'A0AAE3IK34', 'A0AAE3J6N2', 'A0AAE3K2Z4', 'A0AAE3TNI8', 'A0AAE5HBT0', 'A0AAF0PE89', 'A0AAI9K111', 'A0AAJ1D443', 'A0AAJ2WED0', 'A0AAJ4RA85', 'A0AAP2ULS0', 'A0AAP2ZA37', 'A0AAP3E1B7', 'A0AAP4EYC2', 'A0AAP5KD54', 'A0AAP9MGG7', 'A0AAQ1R4F2', 'A0AAU8A953', 'A0AAV3S8B5', 'A0AAV3S8M2', 'A0AAV3SSM3', 'A0AAV3T0D2', 'A0AAV3T9N5', 'A0AAV3UFU8', 'A0AAW3JSL2', 'A0AAW4MRY2', 'A0AAW4VYU4', 'A0AAW4W1P6', 'A0AAW5BVA4', 'A0AAW5CEX0', 'A0AAW5JS35', 'A0AAW5KIA1', 'A0AAW5KKH1', 'A0AAW6CZW8', 'A0AAW6E135', 'A0AAW6E1G4', 'A0AAW6E1L3', 'A0AAW6E6L2', 'A0AAW6E800', 'A0AAW6EBC8', 'A0AAW6EF18', 'A0AAW6EG62', 'A0AAW8SM42', 'A0AAW8STE1', 'A0AAW9L200', 'A0AAW9L5U5', 'A0AAX0BFH2', 'A0AAX1QGG3', 'A0AB35Y226', 'A0AB35Y783', 'A0AB36TJM7', 'A0AB37KHR9', 'A0AB37KPE9', 'A0AB37ZZ00', 'A0AB38A275', 'A0AB38A2S9', 'A0AB38BEM7', 'A0AB38BIZ4', 'A3DFJ8', 'A5KIW3', 'A5Z8F1', 'A5ZXR8', 'A6BJ79', 'A7VBU6', 'A7VSI5', 'A8RR22', 'A8S9D1', 'A8U5C8', 'B0MJN0', 'B1C9R7', 'B5CSB8', 'B7ATM0', 'B7CC80', 'B9LU00', 'C0EAH3', 'C0EZB6', 'C4Z544', 'C4ZEH3', 'C6LBD3', 'C7H8L8', 'D1PQI1', 'D2RU19', 'D3ASW2', 'D4JR11', 'D4LA49', 'D4LUB7', 'D4M2L1', 'D4MIA0', 'D4S279', 'D8J4C6', 'E0RUI1', 'E2ZFN4', 'E5VHJ9', 'E6LDE7', 'E6UL18', 'E8LEM6', 'E9SE87', 'F0RVD2', 'F1TCK5', 'F2JQ39', 'F2NWX7', 'F3AS48', 'F4BMF2', 'F4LNJ2', 'F7JQQ0', 'F7V881', 'F8D7H6', 'G0VRF5', 'G0VS25', 'G1VN54', 'G5HMB9', 'G8QQ37', 'H1B9D4', 'H1D386', 'H2JF35', 'H7EIN0', 'I0X9X8', 'I5ASC3', 'I7CDY2', 'K1UX93', 'L0AHQ0', 'L0JT30', 'L0K3T3', 'L1QIL7', 'L7VT78', 'L9VG40', 'L9WB90', 'L9WHY3', 'L9X2V2', 'L9XEU2', 'L9XS69', 'L9XTL3', 'L9YY28', 'L9YZJ4', 'L9ZG19', 'L9ZNI9', 'L9ZWF4', 'M0AHA9', 'M0B6S6', 'M0B7J9', 'M0BW44', 'M0C732', 'M0CJN2', 'M0D7V4', 'M0DV62', 'M0E1M5', 'M0EBA7', 'M0EBX9', 'M0EL38', 'M0EWN7', 'M0F7H2', 'M0LRJ9', 'M0LYF4', 'M0M6R9', 'M0MDP9', 'M0NET8', 'M0NRE6', 'M0NRJ2', 'M0P8Z5', 'M0PEA5', 'M0PKL9', 'M1XLN4', 'N2A3D2', 'N9WDC4', 'R0AQW9', 'R0BZC3', 'R0C600', 'R2RPW4', 'R2SYZ8', 'R4W0C0', 'R5A6V9', 'R5CN13', 'R5E2R0', 'R5EA84', 'R5EIE5', 'R5GVC5', 'R5KIH9', 'R5L5K4', 'R5LBW8', 'R5P5I7', 'R5QL68', 'R5R1D4', 'R5TYE5', 'R5VL39', 'R5W754', 'R5XFQ9', 'R5Z6B8', 'R5ZQQ6', 'R6A4Z9', 'R6BW10', 'R6CGI3', 'R6CMY6', 'R6DHE6', 'R6IBW5', 'R6J108', 'R6JST5', 'R6KDR5', 'R6LN08', 'R6NDC8', 'R6NWJ0', 'R6PKN7', 'R6QC20', 'R6QDH8', 'R6R7N2', 'R6RQ59', 'R6TNB6', 'R6UG41', 'R6UK02', 'R6US11', 'R6VAV9', 'R6X9G0', 'R6Y261', 'R6Z2W0', 'R6ZEH0', 'R7A2M9', 'R7AMH0', 'R7BCN1', 'R7BFP2', 'R7BJQ0', 'R7C973', 'R7H891', 'R7HV25', 'R7IPF6', 'R7K8S3', 'R7N4H3', 'R7QYH5', 'R8VWI7', 'R9CFP3', 'R9IZI9', 'R9J5N9', 'R9JEE9', 'R9K4R4', 'R9K7H3', 'R9L422', 'R9LN60', 'R9LWT3', 'R9MRV6', 'S0J415', 'S7IXM6', 'U1NGR2', 'U1NXA4', 'U1QPB0', 'U2EDZ6', 'U2JMK8', 'U2PGQ8', 'U2YQL0', 'U3A921', 'U5SA84', 'V4HNV6', 'V4X658', 'V4XLV7', 'V4YAZ8', 'V7I8B0', 'V8CC03', 'W0FHC4', 'W0FNN1', 'W0JIB3', 'W3ANU5', 'W4V1Q8', 'W4V8S6', 'W7UD62', '']

TH: First I search with one ID and take the result and put it into a dataframe. I'm not sure how to get the column of the data frame out so that I can search with extract seq later on but I guess I need to just save it as a string?

LP: The format here looks a little like EMBL format, which in adapted form is the GenBank flat file format we still use (.gbff). It's not quite the same, but the "trick" is - as ever - to work out what information is there that you need, and then decide how much effort you want to spend parsing it. We could, if we wanted, create a new data type or data class, and parse the data into that (worth it if you're doing this a lot and need reusability), or we could simply parse into a collection of (start, end) tuples if we're writing one-shot or throwaway code. Either way, you've gone a long way towards the parsing in your code below.

LP: I'll go through the approach I would take in parsing out the start/end co-ordinates for each helix, below.

In [5]:
# Putting this all into a function:
def parse_ft_transmembrane(result):
    """Returns start, end positions from ft_transmembrane result as generator"""
    transmems = result.split("\n")[1]
    positions = re.findall("(?<=TRANSMEM )(?P<tmemstart>[0-9]*)..(?P<tmemend>[0-9]*)", transmems)
    return ((int(start), int(end)) for start, end in positions)

LP: So much for parsing out the start and end points. That's only part of what you want to do, though. You also want the corresponding protein sequence. We can get this direct from UniProt for the same query in FASTA format.

LP: We need to parse this, and Biopython is convenient. But Biopython needs input as a file-like object, so we use `StringIO` to convert our FASTA string, and make a Biopython `SeqRecord` object.

LP: Bringing it all together, we can extract helix sequences as below. We need to be careful with off-by-one numbering, as Biopython sequence are 0-indexed, but UniProt sequences are 1-indexed.

```text
Biopython: 012345678
Sequence:  MCMFCLEPP
Uniprot:   123456789
```

LP: Let's be neat and wrap this all in a function, where we just pass the query ID.

In [6]:
# Function to return TM helix sequences from UniProt, given a query AA ID
def get_tm_helices(query):
    """Return generator of TM helix sequences for the passed UniProt query"""
    tms = u.search(query, frmt="tsv", columns='ft_transmem')
    record = SeqIO.read(StringIO(u.search(query, frmt="fasta")), "fasta")
    # for returns in record:
    #     if returns != 1:
    #        continue
    return (record.seq[start-1:end] for start, end in parse_ft_transmembrane(tms))

LP: Let's try this on the original list of queries

In [7]:
# returning IDs and TM sequences of proteins with 11 or 12 predicted helices which
# matches ammonium transporters Amt/Mep/Rh

lest = []

spoen = []

matches = []

for quas in data_into_list:
    print(f"\nQuery ID: {quas}")
    helixe = list(get_tm_helices(quas))
    if len(helixe) == 12:
        print(f'query {quas} has {len(helixe)}, using last 11 helices')
        helixe = helixe[-11:]
    if len(helixe) < 11:
        print(f'query {quas} has {len(helixe)} which is too few, skipping')
        helixe = ''
    if len(helixe) > 12:
        print(f'query {quas} has {len(helixe)} which is too many, skipping')
        helixe = ''
    for idx, helix in enumerate(helixe):     
        print(f"Helix {idx + 1}: {helix}")
        reshault = f">{quas}_Helix_{idx + 1} {helix}"
        staup = quas
        lest.append(reshault)
        spoen.append(staup)
        spoon = f"{quas}_Helix_{idx + 1}"
        matches.append(spoon)

Query ID: A0A011VQM7
Helix 1: GVWFMIAVALVFFMQAGFAMV
Helix 2: FCIGTVAFIAIGFGLLLG
Helix 3: SFAWDQFVFNLVFCATTATIVS
Helix 4: YCIYSGIISALIYPIEAHWIWG
Helix 5: LSGSCAIHMVGGICALIGAKIVG
Helix 6: GHNLIIGALGVFILWFGWYG
Helix 7: IFLTTTVAPAIATVTVMVFTWL
Helix 8: VSMCLNASLAGLVGITAGC
Helix 9: FGAIMVGIVSGFLVCFGVWFL
Helix 10: AVAVHMMNGIWGTIAVGLFA
Helix 11: LGLQLLGFVSVAAWAAVAITITFLII

Query ID: A0A063ZJU6
Helix 1: MWVLIATFLIFFMHAGFAML
Helix 2: WSVGVIAFFFVGFGVNALTGSVT
Helix 3: WVSWLFSAVFAMTAATIVSGAVAG
Helix 4: LLLAAIIYPVVTGFTWGGGLLAI
Helix 5: FAGGMIVHGMGGIAGLTAAWII
Helix 6: LTFAALGTLILAFGWYGF
Helix 7: VALNTTLGMAAGAIGAGAVALY
Helix 8: TLYVANGLLAGLVGVTASA
Helix 9: YGGLLSGLIAGAQLPIVFSLV
Helix 10: VFPVHGSAGVIGALLLPFFHI
Helix 11: IVGVTVIGVWTVATTAIVFGAF

Query ID: A0A081EVR3
Helix 1: LMWVAVVCFLIFFMHAGF
Helix 2: LLTWGVGVLVYFLVGFGIEGVA
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YVAYTIAISAVIYPVVAGITWGGG
Helix 5: FAGGMIVHGVGGIAGLTAAYML
Helix 6: MTFAVLGTLVLAFGWYGF
Helix 7: GGYSAVGRVSLTTTLGMGAGAIGAAL
Helix 8: LYVANGVLAGLVAVTGT
Helix 9: WWGAIAVALICGLQLPLVF
Helix 10: VCAVFPVHGSAGVIGVLALPFIHV
Helix 11: VIGVVVITAWTVVATAVVFGVF

Query ID: A0A099I9L1
Helix 1: VNTIWVLVGAALVFFMQAGFSLC
Helix 2: FCIGTPAFWLVGFGIMFGAGNGI
Helix 3: VPLWAFAIFQTVFCATSATIVS
Helix 4: YCIYSAATSLLIYPVSGHWIWG
Helix 5: FAGSTAVHMLGGVCAMIGAAIL
Helix 6: ITFAALGVFILWFCWFGF
Helix 7: VFFNTNIAAAVACCTTMIFTWV
Helix 8: VSMTYNAALAGLVGVTAG
Helix 9: SVGAAGIGIVCGILVVLSIEFF
Helix 10: AVSVHCVCGAVGTVLTGLFATGV
Helix 11: LGVISVTAYVAIVITIVFLVI

Query ID: A0A0D8IWY3
Helix 1: VDTIWVLLGAALVFFMQAGFAMV
Helix 2: FALGTVAFWLAGFGIMFAG
Helix 3: FPSWAFVIFQTVFCATAATIVS
Helix 4: YCIYSVAISLIVYPVGGHWVWG
Helix 5: FAGSTAVHMVGGLCALIGAKMV
Helix 6: LTLAALGCFILWFCWFGF
Helix 7: IFVNTNLAAAVATCVVMIITWS
Helix 8: VSMTLNGSLAGLVAITAG
Helix 9: PFGAAIIGLIAGFAVVFGVEFI
Helix 10: AIGVHFVNGALGTVLTGLFA
Helix 11: FYGGGFGFLGVQMLGVLAVCAWVGVAITLVFFLL

Query ID: A0A0E2HBL2
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FAIGTPLFWLTGFGIMFGGAGAFIG
Helix 3: LPAYLIFQTVFCATAATIVSGA
Helix 4: FISYCIYSAIISAVVYPVSGHWIWG
Helix 5: FAGSTAVHMCGGVAALIGAKVL
Helix 6: LTLGALGVFILWFCWFGF
Helix 7: IFVTTNLAAATATAATMIITWL
Helix 8: ISMTLNGSLAGLVAITAGC
Helix 9: AGAFFIGLIAAFVVVFGIEFI
Helix 10: AIGVHGMCGAAGTLLTGVFAV
Helix 11: FLGIQLLGVVCVILWVSVTMIITFNVL

Query ID: A0A0F0CIE1
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FAIGTPLFWLTGFGIMFGGTGALVG
Helix 3: LPAFLIFQTVFCATAATIVSGA
Helix 4: FISYCIYSAVISAVVYPVSGHWIWG
Helix 5: FAGSTAVHMCGGVAALIGAKIL
Helix 6: LTLGALGVFILWFCWFGF
Helix 7: IFVTTNLAAATATVATMVITWI
Helix 8: ISMTLNGSLAGLVAITAGC
Helix 9: VGAFFIGLIAAFVVVFGIEFI
Helix 10: AIGVHGMCGAAGTLLTGVFAA
Helix 11: FLMIQFIGVIAVIAWVTVTMFVTFNVL

Query ID: A0A0F9HQB3
query A0A0F9HQB3 has 10 which is too few, skipping

Query ID: A0A0G3WG46
Helix 1: LWVLFGAALVFFMQPGFAML
Helix 2: FAFGSLCYWAIGFGIMFGAGTAFVGVL
Helix 3: FPTPAFLIFQTVFCATAATIVS
Helix 4: YVIYSIVISAIVYPISGHWIWG
Helix 5: FAGSTTVHMVGGVAAFIGAALL
Helix 6: ITLAALGVFILWFGWFGF
Helix 7: SIVSAASIFVTTNLAAAAAAAATLLL
Helix 8: MTLNGVLAGLVAITAGCDAVS
Helix 9: LIGLIAGVVVVFAVEFI
Helix 10: AVAVHGVCGALGTVLTGIFAL
Helix 11: MLSVQAFGVIVVAAWISVTMFITFFLL

Query ID: A0A0G9LEF6
Helix 1: IIDTVWVFLAAILVFFMNLGF
Helix 2: FIVFAVSSLGFMLLGWGIMFGG
Helix 3: FFFQLVFCGTAATIVSGAV
Helix 4: LSFIIFSFVLTLIIYPIVGHWIWG
Helix 5: FAGDTVVHSVGGWAALAGALIL
Helix 6: MSLAVIGLFILWLGWFGF
Helix 7: TTNTAAIAAILTSTATAWIII
Helix 8: MTINGCLAGLVGITGSCAYVS
Helix 9: LIGAIAGILVVYAVMFF
Helix 10: TAVHLACGVFGTICVGLFA
Helix 11: QLLWAQIIGIVAVGAFVFASSLLVWYLI

Query ID: A0A0H5SG89
Helix 1: IVDTIWVVLAAVLVFFMNLGF
Helix 2: FIVFAVSSLGFMLLGWGLM
Helix 3: FFFQLVFCGTAATIVSGAV
Helix 4: ISFIVFSFILTLVIYPIVGHWIW
Helix 5: HSVGGWAALSGAIILGPRY
Helix 6: IPGHSMALAVIGLFVLWLGW
Helix 7: ILVTTNTAAIAAVLTATATSWLFI
Helix 8: MTINGCLAGLVGITGSCAYVS
Helix 9: IIGAIAGVIVVFAVLFF
Helix 10: TSVHLVCGVFGTICVGLFA
Helix 11: LLGIIAVGVFVFVSSSVVWLLI

Query ID: A0A0J6WZA7
query A0A0J6WZA7 has 9 which is too few, skipping

Query ID: A0A0J6ZRU4
Helix 1: IVAAFLAFIIQPGVAMVESGLS
Helix 2: VYTNFGIIIILFWFLGFSVLF
Helix 3: VLFQTMLCAAAIASFFGALA
Helix 4: VFCLCSVCMSLVIYPIVGHWVW
Helix 5: AGGAVLHVLSGTAAFIGCKMV
Helix 6: LAVSIQGLFLLWLGWLGVACGSFVL
Helix 7: QNLQLAVAASIVTTLLVTWG
Helix 8: VSMIINGGIAGIAAVSSG
Helix 9: PAGAVCIGVLTGIVIVFSIEFV
Helix 10: AISTHGICGALGCVLTGVFSL
Helix 11: IMTQIMGIVSIVVCVAVLCAVMFYGI

Query ID: A0A0J9EMW5
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FAIGTPLFWLTGFGIMFGGTGALVG
Helix 3: LPAFLIFQTVFCATAATIVSGA
Helix 4: FISYCIYSAVISAVVYPVSGHWIWG
Helix 5: FAGSTAVHMCGGVAALIGAKIL
Helix 6: LTLGALGVFILWFCWFGF
Helix 7: IFVTTNLAAATATVATMVITWI
Helix 8: ISMTLNGSLAGLVAITAGC
Helix 9: VGAFFIGLIAAFVVVFGIEFI
Helix 10: AIGVHGMCGAAGTLLTGVFAA
Helix 11: FLMIQFIGVIAVIAWVTVTMFVTFNVL

Query ID: A0A0M2NHW4
Helix 1: DTVWVLLGAALVFFMQAGFAMV
Helix 2: FSLGSIVFWVIGFGLMFGVSASGF
Helix 3: YAFFIFQTMFCATAATIVS
Helix 4: YCIYSIIISAVIYPISGHWIW
Helix 5: HMVGGVAALVGAKILGARI
Helix 6: ILGHSITLAALGVFILWFAWFG
Helix 7: IFTTTSIAAAAASTGAMLITWI
Helix 8: VSMTLNGALAGLVAITAG
Helix 9: PWAAAVIGLIASFVVVFGVEFV
Helix 10: AIAVHGFCGAAGTILVGIFAL
Helix 11: FLGVQALGVVCVAAWVAVTMTVVFQIL

Query ID: A0A0M6WC26
query A0A0M6WC26 has 10 which is too few, skipping

Query ID: A0A0M6WCZ2
Helix 1: SGVIFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTVVFILIGFSLLL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCVYSGVISALIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGISALVGAAIL
Helix 6: IPGHNITIGALGVFILWLGWYGF
Helix 7: GSIFVTTTIAPALATVVCMIFTWL
Helix 8: VSMCLNASLAGLVAITAG
Helix 9: ALGAIIIGSVAGLLVCFGVWFL
Helix 10: IWGTIAVGLFATNSAPGYSIA
Helix 11: GLQLTGFVSVAAWTVVTITIVFLVI

Query ID: A0A0M9AS13
Helix 1: GTWILVVTFLIFFMHAGFAML
Helix 2: WSVGVTVFFLIGTAFTSLVNGSAGIMSAAGA
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPMVIAFTW
Helix 5: AGGMIVHGMGGIAGLTAAAVL
Helix 6: LTFAVLGTLVLAFGWYGF
Helix 7: LVAMGTTIAMASGGIGAALVVWL
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAVVVGGLAGAQLPIVF
Helix 10: VCAVFPVHGSAGVLGTLLFPFVAA
Helix 11: FVAQLVGVVIIGGWTITATAAVWYVL

Query ID: A0A0R2HL96
query A0A0R2HL96 has 9 which is too few, skipping

Query ID: A0A0S2W112
Helix 1: NTIWVLLGAAMVFFMQAGFAMC
Helix 2: FCIGTPAFWLVGFGIMFGGTGALIG
Helix 3: IWAFFIFQTVFCATAATIVSGA
Helix 4: FISYCIYSAVISLVIYPISGHWIWG
Helix 5: FAGSTAVHMVGGVAACVGAKIL
Helix 6: LSIAALGVFILWFCWFGF
Helix 7: LLAGSIFCTTNMAAAVACVTTMVFTWL
Helix 8: VSMTFNAALGGLVAITAG
Helix 9: ISGAAAIGICVGIVMPLAIGFF
Helix 10: AISVHGVCGAMGTILTGFFAL
Helix 11: FLMTQCLGVFFVIAWVVVTMTIVF

Query ID: A0A0U5JBG5
Helix 1: IDSFWVALAAFLVFWMNLGF
Helix 2: FIVFAVSSLGFMFLGFGLMF
Helix 3: FFWQLVFCGTAATIVSGAV
Helix 4: ISFIIFSFVLTLFIYPIVGHWIWG
Helix 5: FAGGSVVHGLGGIAALAGAMAL
Helix 6: MSLAVIGVFVLWLGWFGF
Helix 7: AHVLLTTNTAAIIAILTSTATSWI
Helix 8: LGMTINGCLAGLVIITPGAA
Helix 9: VSMLLGAIGGVIVVFAVMMF
Helix 10: TSVHLVNGFLGTIAVGLFAK
Helix 11: LLGVQVLGVVAVAAFGFLTSALVW

Query ID: A0A0W7TMH6
Helix 1: VDTIWVLLGAALVFFMQAGFAMV
Helix 2: FALGTVAFWLAGFGIMFAG
Helix 3: FPSWAFVIFQTVFCATAATIVS
Helix 4: YCIYSVAISLIVYPVGGHWVWG
Helix 5: FAGSTAVHMVGGLCALIGAKMV
Helix 6: LTLAALGCFILWFCWFGF
Helix 7: IFVNTNLAAAVATCVVMIITWS
Helix 8: VSMTLNGSLAGLVAITAG
Helix 9: PFGAVIIGLIAGFAVVFGVEFI
Helix 10: AIGVHFVNGALGTVLTGLFA
Helix 11: FYGGGFGFLGVQMLGVLAVCAWVGVAITLVFFLL

Query ID: A0A0X8VAS2
query A0A0X8VAS2 has 0 which is too few, skipping

Query ID: A0A136Q6K1
Helix 1: DTVWVLLGAALVFFMQAGFAMV
Helix 2: FSLGSVVYWAVGFGLMFGVSAGGF
Helix 3: YVFFIFQTMFCATAATIVSGAMA
Helix 4: AYCIYSVIISLVIYPISGHWIWG
Helix 5: FAGSTAVHMVGGVAALVGAKIL
Helix 6: IPLAALGVFILWFAWFGF
Helix 7: FTTTSLSASAGAIGAMFITWI
Helix 8: VSMTLNGALAGLVAITAGC
Helix 9: WAAFVIGLAAAFVVVFGVELL
Helix 10: AVPVHGFCGAVGTLLVGVFAV
Helix 11: FLGIQALGVVSVVAWVAATMTIVFQVL

Query ID: A0A136WGT4
Helix 1: FGIWFLMGAVLVFFMQAGFAMV
Helix 2: FCIGTVVFLILGFNLMMAEDTLFGFIGI
Helix 3: FPWSSFIFNLVFCATAATIVSGA
Helix 4: FNAYLIYSAVISCLIYPI
Helix 5: FAGSAAIHMVGGVSALIGAKLLG
Helix 6: GHSLTLGALGVFILWFGWYGF
Helix 7: AQIFSTTTIAAGFATVTTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAP
Helix 9: ALGAIIIGIVAGFLVVLAVEFL
Helix 10: AVAVHGVNGIWGTLAVGLFNI
Helix 11: ITQLIGVVSIAAWTAVTMYIVF

Query ID: A0A140DTE7
Helix 1: IWYLIGAALVFFMQAGFAMV
Helix 2: FCLGTVAFLILGFSLLCGAQGNA
Helix 3: FTFNLVFCATAATIVSGA
Helix 4: FISYCVYSFVISLLIYPV
Helix 5: FAGSAVIHFAGGLCALIGASML
Helix 6: IVIGALGVFILWFGWYGF
Helix 7: ATIFATTTVAPALAACTVMGFTWI
Helix 8: VSMTLNGALAGLVAITAG
Helix 9: VWGACIIGIVSGFICCFLVWLL
Helix 10: AVAVHFGNGLWGTLAVGLFAC
Helix 11: LGIQALGLLCIGVWTGVTIWLTFFCI

Query ID: A0A143Y517
Helix 1: MFLATVMVLLMTPALSLFYGG
Helix 2: MHSYAAIVVVVIQWILIGYSL
Helix 3: LFMMFQLAFAIITPAIISGSVA
Helix 4: AFLAFVLLWTTLVYDPIAHWVW
Helix 5: LDFAGGTVIHVSAGISALVAAIFVG
Helix 6: NIPMTMIGAGLLLFGWFGF
Helix 7: AMNAFITTMVSGAAAGFSWI
Helix 8: ALGLVSGIIAGLGSITQSA
Helix 9: FSAMIIGFIGGLLCFFAVTAL
Helix 10: AFGCHGVGGIWGGISAGIFA
Helix 11: LIAEIISIVAVIAYSAIISFAIL

Query ID: A0A143Y9S4
Helix 1: VFLATILVLLMTPALSLFYGGMV
Helix 2: SYVAIAVVSIQWILFGYSFV
Helix 3: IPHQLFLMFQLAFAVITPALI
Helix 4: AFLAFILLWTTFVYDPIAHWIW
Helix 5: LDFAGGSVIHISSGVSALVAAIYIG
Helix 6: NIPMTMIGAGLLLFGWYGF
Helix 7: ALNAFIATNTSAAAAGLSWM
Helix 8: ALGFVSGIVAGLVSITPGA
Helix 9: FASLMIGLIGGIVCFYGVTVL
Helix 10: AFGCHGIGGIWGGIATGIFA
Helix 11: LVAEVISILAVVTYAGIVSYLLL

Query ID: A0A143YNF2
Helix 1: VFFATALVMLMTPALSLFYGGMV
Helix 2: SYAAIAVVSVQWLLFGYSFV
Helix 3: LFMMFQLAFAIITPALISGSVA
Helix 4: AFLAFILLWTTFIYDPIAHWVW
Helix 5: LDFAGGSVIHISSGVSALVAAIFIG
Helix 6: SIPMTMVGAGVLLFGWFGF
Helix 7: LAINAIAVNAFITTAMAAATAGLSWL
Helix 8: ALGFVSGIVAGLVSITPGAGFV
Helix 9: LAIGFIGGIACFFGVTVL
Helix 10: AFGCHGIGGIWGGIATGIFA
Helix 11: LIAELISMAAIIAYAAAGSYILL

Query ID: A0A143YTA3
Helix 1: DTLWTLVGTVLVFFMQAGFAMV
Helix 2: FVLGSLGFFLIGYSIMFGDDIAGII
Helix 3: FMFQNVFAATAATIVSGAVAE
Helix 4: YLVYSFLISLLIYPISGHWIWG
Helix 5: FAGSTAVHMVGGVAALVGAALV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IFLNTNLSAVTATLVTLLFTW
Helix 8: LNGSLAGLVAITAGCAVVS
Helix 9: AIGFIAGFAIVLAVEFI
Helix 10: AFSVHGVNGALGTILVGIFAT
Helix 11: LLGVQTLGVASVAAYTAGSMYVVF

Query ID: A0A143YWY4
query A0A143YWY4 has 10 which is too few, skipping

Query ID: A0A143YZV1
Helix 1: DTLWTLLGTVLVFFMQAGFAMV
Helix 2: FVLGSLGFFLIGYSIMFGDDIAGII
Helix 3: FMFQNVFAATAATIVSGAVAE
Helix 4: YLVYSFIISLLIYPISGHWIWG
Helix 5: FAGSTAVHMVGGVAALVGAAVV
Helix 6: LTIGALGVFILWFAWFGF
Helix 7: IFLNTNLSAVTATLVTLLFTW
Helix 8: LNGSLAGLVAITAGCAVVS
Helix 9: AIGFIAGFAIVLAVEFV
Helix 10: AFSVHGVNGALGTILVGVFAT
Helix 11: MLGIQTLGVASVAAYTAGSMYVVF

Query ID: A0A143Z212
Helix 1: VFLATILVMLMTPALSLFYAGMV
Helix 2: SYAAIAVVSIQWLLFGYSFVF
Helix 3: IPHQLFMMFQLAFAIITPALI
Helix 4: AFLAFILLWTTFVYDPIAHWIW
Helix 5: LDFAGGSVIHISSGVSALVAAIYLG
Helix 6: NIPMTMIGAGLLLFGWFGF
Helix 7: ALDAFITTNTAAAAAGISWMV
Helix 8: LGFVSGIVAGLVSITPGA
Helix 9: LSALVIGFVGGIVCFYGVSVL
Helix 10: AFGCHGIGGIWGGIATGIFA
Helix 11: LLAEVISILAVLAYAGIGSFLLL

Query ID: A0A143ZCA8
Helix 1: FLATVMVLLMTPALSLFYGGMV
Helix 2: SYAAIVVVVIQWILLGYSL
Helix 3: IPHQLFMMFQLAFAIITPAII
Helix 4: AYLAFVLLWLTLVYDPIAHWVW
Helix 5: LDFAGGTVIHVSAGISALVAAIFVG
Helix 6: NIPMTMIGAGLLLFGWFGF
Helix 7: AINAFITTTVSGAAAGFSWL
Helix 8: ALGLVSGIIAGLGSITQSA
Helix 9: FSALLIGFIGGLLCFFAV
Helix 10: ALDAFGCHGVGGIWGGISAGIFA
Helix 11: LIAEIISILAVTAYSAVISFVIL

Query ID: A0A151AI36
Helix 1: MMWVLVVTFLIFFMHAGFAML
Helix 2: WAVGVVMFFFVGAAISTVVGAITGGGSY
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YVGYTVLLAAVIYPVVTGLTWA
Helix 5: FAGGMIVHAVGGIAGLTAAWIL
Helix 6: MTFAVLGTLVLAFGWYGF
Helix 7: VALATTLGMALGALGASVVSLAL
Helix 8: LYVANGLLAGLVGVTGI
Helix 9: WWGAVLVAFIAGAQLPLVF
Helix 10: VCAVFPVHGSAGVIGALAIPFVAIP
Helix 11: VFAQVAGVAVIAAWTIGATAVVWGAF

Query ID: A0A169X118
Helix 1: VIAQGINLLWVLIATFLIFFMHAGF
Helix 2: LLTWSVGVMTFFLLGAALSSIV
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YVGYTILLAGVFYPVVVGFTWA
Helix 5: FAGGMIVHGMGGLAGLTAAWII
Helix 6: VTFAALGTLILAFGWYGF
Helix 7: VALVTTLGMGAGTLGAGAVSLI
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WPGAIIVGLLAGAQLPFVF
Helix 10: VCAVFPVHGSAGILGTLVYPFVAVGTW
Helix 11: LAVQATGIAVIGLWIVGATVVVF

Query ID: A0A173R3X4
Helix 1: QIFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTCVFILIGFSLLL
Helix 3: WSSFVFNLVFCATTATIVSGA
Helix 4: FLSYCIYSAVISALIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGLSALIGAKFL
Helix 6: FPGHNIPLGALGVFILWLGWYGF
Helix 7: GSIFVTTTISPAVATVVCMVFTWV
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: AFGAIVIGAVSGLLVCFGVWLL
Helix 10: AVAVHFMNGLWGTLATGLFAT
Helix 11: LKIQIIGIVCVCAWTAVTISLTFTII

Query ID: A0A173R662
Helix 1: NIFGVWFLMGAALVFWMQAGF
Helix 2: LMDFCIGTVMFILIGFSFLLG
Helix 3: NFSFSSFVFNLVFCATTATIVS
Helix 4: YCIYSGVISALIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGVSALIGAWLL
Helix 6: IPGHNLALGCLGCFILWFGWYGF
Helix 7: GSIFLTTTISPAVATVVCMIFTWL
Helix 8: VSMCLNASLAGLVAITAP
Helix 9: AAGSIVIGAVAGLLVVFGVWLL
Helix 10: IWGTFAVGLFATNTAPGYAI
Helix 11: LGLQCLGIITVLAWAAVTITITFLVI

Query ID: A0A173SMJ4
query A0A173SMJ4 has 10 which is too few, skipping

Query ID: A0A173TUR6
query A0A173TUR6 has 0 which is too few, skipping

Query ID: A0A173V441
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDVYVVIVMFIIF

Query ID: A0A173W538
query A0A173W538 has 10 which is too few, skipping

Query ID: A0A173X4T2
Helix 1: SGVIFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTVVFILIGFSLLL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCVYSGVISALIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGISALVGATIL
Helix 6: IPGHNITIGALGVFILWLGWYGF
Helix 7: GSIFVTTTIAPALATVVCMIFTWL
Helix 8: VSMCLNASLAGLVAITAG
Helix 9: ALGAIIIGSVAGLLVCFGVWFL
Helix 10: IWGTIAVGLFATNSAPGYSIA
Helix 11: GLQLTGFVSVAAWTVVTITIVFLVI

Query ID: A0A173XV88
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FCIGTPTFWIVGFGIMFGAGNGFFG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCIYSFLISLIVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAAFIGAIIL
Helix 6: LTIGALGVFILWFCWFGF
Helix 7: FVTTNLAAAVATVTVLIITWV
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIISGFVVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFIGMIITIAWVAVTMTIIF

Query ID: A0A173XVK8
Helix 1: DTIWTLLGAALVFFMQAGFAMV
Helix 2: FCIGTVVFWLIGFGLMFGG
Helix 3: IPTFAFVIFQTVFCATAATIVS
Helix 4: YCIYSLIISAIIYPISGHWIWG
Helix 5: FAGSTAVHMVGGVAALIGATIL
Helix 6: LTVGALGVFILWFAWFGF
Helix 7: IFMTTNIAAAVSTCVVLIITWI
Helix 8: VSMTLNGSLACLVAITAG
Helix 9: PVGACFIGIFAGFAVVFAVEFI
Helix 10: AVSVHGVCGALGTILTGLFAT
Helix 11: FLGTQILGVICVIAWVAITMTIVFIVI

Query ID: A0A173Z4K3
Helix 1: VNTIWVLVGAALVFFMQAGFAMV
Helix 2: FCIGTPVFWLVGFGLMFGAGNGFIG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCIYSLMISLVVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAALIGAIIL
Helix 6: LTVGALGVFILWFCWFGF
Helix 7: FVTTNLAAAVATVTVMIITWV
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIASGFIVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFTGMIITIAWVVVTMTIIF

Query ID: A0A173ZTK6
Helix 1: NTIWVLFGTALVFFMQAGFSLCEAGFI
Helix 2: NLMDFCIGTPAFWLVGFRLMF
Helix 3: LWAFAIFQTVFCATSATIVS
Helix 4: YCIYSAAISLLIYPVSGHWIWG
Helix 5: FAGSTAVHMVGGICAMIGAKIL
Helix 6: LTFAALGVFILWFCWFGF
Helix 7: VFFNTNLAAAVACCAALIFTWI
Helix 8: VSMTYNAALAGLVGITAG
Helix 9: AVGAAVIGVVCGILIVLAIEFF
Helix 10: AVSVHCVCGAAGTVLTGLFA
Helix 11: IQVLGVLAVAAYVAVVITIVFLAI

Query ID: A0A174C5U1
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FAIGTPLFWLTGFGIMFGGAGAFIG
Helix 3: LPAYLIFQTVFCATAATIVSGA
Helix 4: FISYCIYSAVISAVVYPVSGHWIWG
Helix 5: FAGSTAVHMCGGVAALIGAKVL
Helix 6: LTLGALGVFILWFCWFGF
Helix 7: IFVTTNLAAATATAATMVITWL
Helix 8: ISMTLNGSLAGLVAITAGC
Helix 9: AGAFFIGLIAAFVVVFGIEFI
Helix 10: AIGVHGMCGAAGTLLTGVFAV
Helix 11: FLGIQLLGVVCVILWVSVTMIITFNVL

Query ID: A0A174D1D6
Helix 1: VNTIWVLVGAALVFFMQAGFAMV
Helix 2: FCIGTPVFWLVGFGLMFGAGNGFIG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCVYSLMISLVVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAALIGAIIL
Helix 6: LTVGALGVFILWFCWFGF
Helix 7: FVTTNLAAAVATVTVMIITWV
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIASGFIVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFTGMIITIAWVVVTMTIIF

Query ID: A0A174GH26
query A0A174GH26 has 8 which is too few, skipping

Query ID: A0A174H6C4
Helix 1: DTIWTLFGAVLVFFMQAGFAMV
Helix 2: FAIGTVVFWFIGFGLMFAG
Helix 3: LPTFTFVIFQTVFCATAATIVS
Helix 4: YCIYSLIISALIYPISGHWIWG
Helix 5: FAGSTAVHMVGGIAALVGAKIL
Helix 6: LTLGALGVFILWFCWFGF
Helix 7: IFMTTNIAAASSTIVVMIVTWI
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: SGAFFIGVIAGLVLTFAVEFI
Helix 10: AISVHGVCGALGTVLTGLFAL
Helix 11: FLGTQILGVLCVILWVLVTMTIVFLVI

Query ID: A0A174JG28
Helix 1: VNTIWVLVGAALVFFMQAGFAMV
Helix 2: FCIGTPVFWLVGFGLMFGAGNGFIG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCVYSLMISLVVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAALIGAIIL
Helix 6: LTVGALGVFILWFCWFGF
Helix 7: FVTTNLAAAVATVTVMIITWV
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIASGFIVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFTGMIITIAWVVVTMTIIF

Query ID: A0A174RYE8
Helix 1: VNTIWVLLGAALVFFMQAGFAMV
Helix 2: FCIGTPTFWIVGFGIMFGAGNGFFG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCIYSFLISLIVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAAFIGAIIL
Helix 6: LTIGALGVFILWFCWFGF
Helix 7: FVTTNLAAAVATVTVLIITWI
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIISGFVVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFIGMIITIAWVAVTMTIIF

Query ID: A0A174T4F8
query A0A174T4F8 has 10 which is too few, skipping

Query ID: A0A174TIU3
Helix 1: QIFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTCVFILIGFSLLL
Helix 3: WSSFVFNLVFCATTATIVSGA
Helix 4: FLSYCIYSAVISALIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGLSALIGAKFL
Helix 6: FPGHNIPLGALGVFILWLGWYGF
Helix 7: GSIFVTTTISPAVATVVCMVFTWV
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: AFGAIVIGAVSGLLVCFGVWLL
Helix 10: AVAVHFMNGLWGTLATGLFAT
Helix 11: LKIQIIGIVCVCAWTAVTISLTFTII

Query ID: A0A174VZ55
Helix 1: VNTIWVLVGAALVFFMQAGFAMV
Helix 2: FCIGTPVFWLVGFGLMFGAGNGFIG
Helix 3: VPFWAFLIFQTVFCATSATIVS
Helix 4: YCVYSLMISLVVYPVSGHWIWG
Helix 5: FAGSCAVHMVGGVAALIGAIIL
Helix 6: LTVGALGVFILWFCWFGF
Helix 7: FVTTNLSAAVATVTVMIITWV
Helix 8: VSMSLNGSLAGLVAITAG
Helix 9: PTSAAIIGIASGFIVVFGIEFI
Helix 10: AVGVHGLNGAFGTLAVGLF
Helix 11: FGVQFTGMIITIAWVVVTMTIIF

Query ID: A0A174XKK3
Helix 1: TIWVLFGAALVFFMQAGFAMV
Helix 2: FCIGTPIFWFVGFGIMFGSWGSV
Helix 3: ISKWTFVIFQSVFCATAATIVS
Helix 4: YCVYSAVISMVIYPVSGHWIWG
Helix 5: FAGSAAVHMVGGTAAAVGAYLL
Helix 6: ITLGALGVFILWFCWFGF
Helix 7: FMNTNLAAALAGCATMFYTWF
Helix 8: VSMTLNGVLAGLVAITAG
Helix 9: PFGAAAIGICAGILVVVAI
Helix 10: PVGAIGVHGVCGAFGAAAVGLFA
Helix 11: FYGGGFSCLGIQLLGVLSVAAWVFLTMNVVF

Query ID: A0A174YTX7
Helix 1: LFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFVLIGFSFLLGE
Helix 3: FNFSSFVFNLVFCATTATIVSGA
Helix 4: FLSYCVYSAVISALIYPIEAHWIWG
Helix 5: FAGSCCIHMVGGISALIGAKIL
Helix 6: FPGHNIPLGALGVFILWFGWYGF
Helix 7: GSIFLTTTVAPAVATVTCMIFTWI
Helix 8: VSMCLNASLAGLVGITAP
Helix 9: AFGATMIGIVSGLLVVFGVWLL
Helix 10: IWGTIAVGLFATSSAPGYAIA
Helix 11: LGLQLLGFVSVAAWAAVCMVIVFTVI

Query ID: A0A174Z5H4
Helix 1: LFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFVLIGFSFLLGE
Helix 3: FNFSSFVFNLVFCATTATIVSGA
Helix 4: FLSYCVYSAVISALIYPIEAHWIWG
Helix 5: FAGSCCIHMVGGISALIGAKIL
Helix 6: FPGHNIPLGALGVFILWFGWYGF
Helix 7: GSIFLTTTVAPAVATVTCMIFTWI
Helix 8: VSMCLNASLAGLVGITAP
Helix 9: AFGATMIGIVSGLLVVFGVWLL
Helix 10: IWGTIAVGLFATSSAPGYAIA
Helix 11: LGLQLLGFVSVAAWAVVCMVIVFTVI

Query ID: A0A175A4T9
Helix 1: GIWYLIGAALVFFMQCGFAMV
Helix 2: FCLGTIAFVLLGFGLMLGEDTFFGLI
Helix 3: FVFNLVFCATAATIVSGA
Helix 4: FISYCIYSFVISLVVYPIEAHWI
Helix 5: IHMVGGLTALIGAAMVGPRI
Helix 6: ILGHSIPLGALGVFILWFGWY
Helix 7: YLADIFLTTTIAPAVATVVTMIFTWL
Helix 8: VSMCLNASLAGLVAITAP
Helix 9: ALGAAIIGIVSGLLVCFGVWLL
Helix 10: AVAVHFFNGVWGSIAVGLFA
Helix 11: LGIQLLGVVSVCAFTAVTMFLTFYIL

Query ID: A0A175ABC8
query A0A175ABC8 has 10 which is too few, skipping

Query ID: A0A176U687
query A0A176U687 has 10 which is too few, skipping

Query ID: A0A1B1YE78
Helix 1: VVFAGILVFFMNLGFAAVESGFA
Helix 2: NFIVFAVSSLGFMLLGWGLM
Helix 3: FFFQLVFCGTAATIVSGAVA
Helix 4: SFILFSFILTLVIYPIVGHWIWG
Helix 5: FAGDTVVHSVGGWAALAGAIIL
Helix 6: MSLAVIGLFILWLGWFGF
Helix 7: TTNTSAIAAVLTATATSWIFI
Helix 8: MTINGCLAGLVGITGSCAYVS
Helix 9: LIGAIAGVLVVFSVLFF
Helix 10: TSVHLVCGVFGTLCVGLFAQ
Helix 11: LFGIELLGIIAVGAFVFVSTSLVWLIL

Query ID: A0A1B1YLE9
Helix 1: VVFAGILVFFMNLGFAAVESGFA
Helix 2: NFIVFAVSSLGFMLLGWGLM
Helix 3: FFFQLVFCGTAATIVSGAVA
Helix 4: SFILFSFILTLVIYPIVGHWIWG
Helix 5: FAGDTVVHSVGGWAALAGAIIL
Helix 6: MSLAVIGLFILWLGWFGF
Helix 7: TTNTSAIAAVLTATATSWIFI
Helix 8: MTINGCLAGLVGITGSCAYVS
Helix 9: LIGAIAGVLVVFSVLFF
Helix 10: TSVHLVCGVFGTLCVGLFAQ
Helix 11: LFGIELLGIIAVGAFVFVSTSLVWLIL

Query ID: A0A1C0BVB4
Helix 1: VLLGATLVFFMQAGFAMV
Helix 2: FALGTIVFWFIGFGLMQG

ValueError: No records found in handle

query A0A511NGC7 has 12, using last 11 helices
Helix 1: VAWILAAAGLVLLMTPGLSFFYG
Helix 2: MLQSFIALGVISILWVVVGFSLSF
Helix 3: IPFVLFALFQMKFAVITPALVT
Helix 4: YLLFMILFSLIIYTPLCHMVW
Helix 5: VVHMSAGFAALAGALVIG
Helix 6: IPFVMLGTGMLWFGWFGF
Helix 7: AALAFGTTTIASASGMMTWILF
Helix 8: SVSAMGACIGAVVGLVAI
Helix 9: SIFFGFITAIISNMAMYW
Helix 10: VFACHGVGGIMGMILTAIFA
Helix 11: FIHHIIALFFVSVFTFFGAITLFYL

Query ID: A0A142BI19
Helix 1: FYFLMSGALVMWMAAGFAMLEAGLV
Helix 2: NIALFAIACTMYLLCGYAIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWSFLLFAVFMTGFIYPV
Helix 5: AGSGVVHMAGAAAALAGVLLL
Helix 6: LPLATLGTFILWLGWFGF
Helix 7: IFVNTNAGAAGGVIAALIVA
Helix 8: ADLTMALNGALAGLVAITA
Helix 9: SALAATLIGAVGGSLVVFAIVAL
Helix 10: ISVHGVVGIWGLLAVPLT
Helix 11: LSAQLLGIVSIFAWVFGASLVVWGVV

Query ID: A0A081N2G5
Helix 1: FYFLMSGALVMWMAAGFAMLEAGLV
Helix 2: NIALFAIACTMYLLCGYAIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWSFLLFAVFMTGFIYPV
Helix 5: AGSGVVHMAGAAAALAGVLLL
Helix 6: LPLATLGTFILWLGWFGF
Helix 7: IFVNTNAGAAGGVIAALIVA
Helix 8: ADLTMALNGALAGLVAITA
Helix 9: SALAATLIGAVGGSLVVFAIVAL
Helix 10: ISVHGVVGIWGLLAVPLT
Helix 11: LSAQLLGIVSIFAWVFGASLVVWGVV

Query ID: A0A1T4SFK4
Helix 1: DTAWLLVATALVLMMNIPGLSLFYAG
Helix 2: VLATAVQAFAVAALVTVLWFAV
Helix 3: FLMYQATFAIITPAIIAGAFA
Helix 4: AMMWFMGLWLLFVYVPVTHWVWG
Helix 5: FAGGLVVHLNAGIAGLVCALVL
Helix 6: APHNLVLTLIGTSLLWVGWFGF
Helix 7: HVSAAVAALVWMAIEWGA
Helix 8: LGVLSGAVAGLGTITPAA
Helix 9: WAAMVIGLVAGAVCYWASVVV
Helix 10: VFGVHGVSGIVGSVLVGVFATRA
Helix 11: VLAQLYGVVVIAAFSAIVTWAIL

Query ID: A0A1T4SF40
Helix 1: LTSTALVLMMTVPGLALFYGG
Helix 2: VLATVMQSFAITCLVTVLWMVL
Helix 3: VFMTFQMTFAIITPALIAGAFA
Helix 4: ALMWFMTLWAIFVYAPIAHWVWG
Helix 5: YAGGTVVHINAGVAGLVCALVL
Helix 6: APHNLVLSVIGASLLWVGWFGF
Helix 7: AGMAMAVTQIATAAAALAWM
Helix 8: VLGIISGAVAGLVAITPAS
Helix 9: VGGLVIGIVAGVICFWSATSL
Helix 10: AFGVHGVGGFVGAILTGVFAVEAV
Helix 11: LWGSLVTIAWCAVATFIIL

Query ID: A0A1Y3U5V2
Helix 1: STAFMFVCTMLVLLMTPGLAFFYG
Helix 2: MFMSFMVIGIAGLTWVFVGWSLA
Helix 3: IVFQMAFALITAGIVTGSVA
Helix 4: AIALFIGIWSVVVYAPLAHMVWG
Helix 5: VVHISSGLTGLVLCLFLG
Helix 6: AHNVPFVALGAGLLWFGWFG
Helix 7: IAVLAVLNTVVSSAAGMASWM
Helix 8: LVGACTGLVAGLVVVTPAA
Helix 9: WAAVVMGAVVSPVCFFAISHL
Helix 10: AFGCHGIGGILGGVLTGIFCVPELS
Helix 11: VLGILVTVAAVLVLDVAIALVV

Query ID: A0A0L8BVU4
Helix 1: AFMFFSTLLVFFMLIPGLALFY
Helix 2: VLMQCTVIGAAMMIVWVVYGY
Helix 3: YIFMLFQMTFAALTPALIIGAFA
Helix 4: AAVLFSILWATFVYFPIAHMVW
Helix 5: LFGMGALDFAGGTVVHINAGVAGLIGAIMV
Helix 6: APHSMTLTLVGAAMLWFGWFGF
Helix 7: AMLATVNTFLATAAAILSWSV
Helix 8: LGAASGMIAGLVAITPAAGI
Helix 9: AIVMGLIVSPLCYFFVSVV
Helix 10: VFGVHGVGGFFGALATGIF
Helix 11: FMTQVTAVAITIVWCGVVSAILY

Query ID: W8I6E4
Helix 1: LLVFFMLIPGLALFYGGL
Helix 2: LSVLMQCTVIGATMMIVWVVY
Helix 3: YIFMLFQMTFAALTPALIIGAFA
Helix 4: AAVLFSVLWATFVYFPIAHMVW
Helix 5: LFGMGALDFAGGTVVHINAGVAGLIGAIMV
Helix 6: APHSMTLTLVGAAMLWFGWFGF
Helix 7: AMLATVNTFLATAAAILSWSV
Helix 8: LGAASGMIAGLVAITPAAGI
Helix 9: AIVMGLIVSPLCYFFVSVV
Helix 10: VFGVHGVGGFFGALATGIF
Helix 11: FMTQLTAVAITIIWCGVVSAILY

Query ID: A0A6S5XW90
Helix 1: NAFMMISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTFSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A6S5K4J1
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A6S5KAW5
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGEGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGGLLIGLAAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A2T4XZC1
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A330EZR0
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A4Q2EAG7
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A0M3F8F9
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPVAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALIIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAATSLGGV
Helix 11: VLVQLESIAITVVWSGVVAFIGY

Query ID: A0A330GB00
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A443Y093
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A144NLT9
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIALTVVWSAVVAFIGY

Query ID: A0A7H9JPM9
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVTVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSGVVAFIGY

Query ID: A0A7H8UK07
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGIFAA
Helix 11: VQLESIAITVVWSGVVAFIGY

Query ID: A0A411GDE8
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A427KNL6
Helix 1: NAFMMISTALVLFMSIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFVGY

Query ID: A0A4Q4A8K6

Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCVMTGIFAA
Helix 11: VQLESIAITVVWSGVVAFIGY

Query ID: A0A801DSC9
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSGVVAFIGY

Query ID: A0A2W0GQV0
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A8H9CE40
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSGVVAFIGY

Query ID: A0A1Z3MS36
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A2S4SRB5
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A421IL65
Helix 1: NAFMMISTALVLFMSIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A855M376
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFAA
Helix 11: VQLESIAITVVWSAVVAFIGY

Query ID: A0A0M2ADU2
Helix 1: IFVCFCFMWLMIFGVILYYV
Helix 2: LILGLVTIISGTLCWLFVGYSL
Helix 3: IVSILIQLLFCLYSVIMIIGSVL
Helix 4: YIVLFVPLWIVFVYAPVCFSLW
Helix 5: VHTTAGIGSLVLAITSPIRL
Helix 6: IAFVGMLFITLGWFGFNMA
Helix 7: IWLNTLISILGGSISWPFTQWILI
Helix 8: SIMNGIIGGLVGSTCSVGYIY
Helix 9: LISVIVCTLCPIVIHIMHL
Helix 10: FGMNAVGGIAGSILTGVMA
Helix 11: FLQLFGTFLISIWSLSLSLLIHYLL

Query ID: R3H4W8
Helix 1: IFVCFCFMWLMIFGVILYYV
Helix 2: LILGLVTIISGTLCWLFVGYSL
Helix 3: IVSILIQLLFCLYSVIMIIGSVL
Helix 4: YIVLFVPLWIVFVYAPVCFSLW
Helix 5: VHTTAGIGSLVLAITSPIRL
Helix 6: IAFVGMLFITLGWFGFNMA
Helix 7: IWLNTLISILGGSISWPFTQWILI
Helix 8: SIMNGIIGGLVGSTCSVGYV
Helix 9: LLISVIVCTLCPIIIHIMHL
Helix 10: FGMNAVGGIAGSILTGVMA
Helix 11: FLQLFGTFLISIWSLSLSLLIHYLL

Query ID: V7ZMI3
Helix 1: IFVCFCFMWLMIFGVILYYV
Helix 2: LILGLVTIISGTLCWLFVGYSL
Helix 3: IVSILIQLLFCLYSVIMIIGSVL
Helix 4: YIVLFVPLWIVFVYAPICFSLW
Helix 5: VHTTAGIGSLVLAITSPIRL
Helix 6: IAFVGMLFITLGWFGFNMA
Helix 7: IWLNTLISILGGSISWTFTQWILI
Helix 8: SIMNGIIGGLVGSTCSVGYV
Helix 9: LLISVIVCTLCPIVIHIMHL
Helix 10: FGMNAVGGIAGSILTGVMA
Helix 11: FLQLFGTFLISIWSLSLSLLIHYLL

Query ID: A0A2N7LCD7
Helix 1: YALDTFFFLMSGALVMWMAAGF
Helix 2: VCLYAISCTTFLLVGYNIMYV
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWAFLVFSVVLTAVIYPV
Helix 5: AGSGIVHMAGASAALAGVLLL
Helix 6: MPLATLGTFILWFGWFGF
Helix 7: IFLNTNAAAASGAIVALLVC
Helix 8: ADLTMVLNGALAGLVAITA
Helix 9: SPIAALVVGGLSGALVVISIIAL
Helix 10: ISVHGTCGLFGLLAVPFS
Helix 11: FGAQLLGAAVIFAWVFGASLLVWGVL

Query ID: A0A2N7L7C8
Helix 1: LFILMGAIMVLAMHAGFAFLEV
Helix 2: LVKIMSDFGFSALAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIIS
Helix 4: MLIAAAVIVAFVYPFFEGLIWN
Helix 5: FAGSVVVHAVGGWIALAAVLIL
Helix 6: LIAFAPSNIPFLALGAWILTIGWFG
Helix 7: ISGLVAVNTLMAMVGGIVASLVV
Helix 8: FLHNGPLAGLVAVCAGSDL
Helix 9: ALFTGGVAGALFVWLFTLT
Helix 10: VWPLHGVCGMWGGLAAGIFGL
Helix 11: MSQLIGTIAGVVIAFVGGWIVYTAV

Query ID: A0A1E5BXA4
Helix 1: YALDTFFFLISGALVMWMAAGF
Helix 2: VCLYAIACTTYLLVGYNIMYV
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWAFLVFSVILTAFIYPM
Helix 5: AGSGIVHMAGASAALAGVLLL
Helix 6: LPLATLGTFILWFGWFGF
Helix 7: IFLNTNAAAATGALVALGVC
Helix 8: ADLTMVLNGALAGLVAITA
Helix 9: SPVAALVIGGLAGALVVISIVGL
Helix 10: ISVHGTCGLFGLMVVPFS
Helix 11: FGAQLFGAAVIFAWVFGASLVVWAVL

Query ID: A0A1E5C7W4
Helix 1: LFILMGAIMVLAMHAGFAFLEV
Helix 2: LVKIMSDFGFSALAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIIS
Helix 4: MLIAAAAIVAFVYPFFEGLIWN
Helix 5: FAGSVVVHAVGGWIALAAVMIL
Helix 6: LIAFAPSNIPFLALGAWILTIGWFG
Helix 7: ISGLVAVNTLMAMVGGIVASLIV
Helix 8: FLHNGPLAGLVAVCAGSDL
Helix 9: ALVTGGVAGALFVWLFTLT
Helix 10: VWPLHGVCGVWGGLAAGIFGL
Helix 11: MSQLIGTMTGVVVAFVGGWIVYTAV

Query ID: A0A1I5W440
Helix 1: YALDTFFFLMSGALVMWMAAGF
Helix 2: VCLYAISCTTFLLVGYNIMYV
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWAFLVFSVVLTAVIYPV
Helix 5: AGSGIVHMAGASAALAGVLLL
Helix 6: MPLATLGTFILWFGWFGF
Helix 7: IFLNTNAAAASGAIVALLVC
Helix 8: ADLTMVLNGALAGLVAITA
Helix 9: SPIAALVVGGLSGALVVISIIAL
Helix 10: ISVHGTCGLFGLLAVPFS
Helix 11: FGAQLLGAAVIFAWVFGASLLVWGVL

Query ID: A0A1I5SNU9
Helix 1: LFILMGAIMVLAMHAGFAFLEV
Helix 2: LVKIMSDFGFSALAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIIS
Helix 4: MLIAAAAIVAFVYPFFEGLIWN
Helix 5: FAGSVVVHAVGGWIALAAVLIL
Helix 6: LIAFAPSNIPFLALGAWILTIGWFG
Helix 7: ISGLVAVNTLMAMVGGIVASLVV
Helix 8: FLHNGPLAGLVAVCAGSDL
Helix 9: ALFTGGVAGALFVWLFTLT
Helix 10: VWPLHGVCGMWGGLAAGIFGL
Helix 11: MSQLIGTIAGVVIAFVGGWIVYTAV

Query ID: G8JTW0
Helix 1: AAVGFIFMGSVLVFFMVPGLGFLY
Helix 2: LIWAVLMAGIVGIIQWYIW
Helix 3: LVFAIFQGLFMCVTLAIIAGA
Helix 4: VFLFCFATLVYCPVTYWIW
Helix 5: VEILSAVGGFVYSYFLG
Helix 6: PHNVSMVTLGTSILWVGWLGF
Helix 7: AVYALMNTNISAAMGGMAWCLV
Helix 8: KLSTVGLCSGVICGLVAAT
Helix 9: ITLYGSLIQGIVAGIVCNF
Helix 10: GIAGIVGLIFNALFSADWVL
Helix 11: MYKQLAYVAAVSAYSIVVTSLICMLI

Query ID: G8JUJ2
Helix 1: LVWVGMAAVLVWLVVPGVGLLY
Helix 2: LLWASVMAVAVVSFQWFIW
Helix 3: VLFAFYQGMFAMVTGILMVG
Helix 4: MVFLFLWVTTVYCPIACWTWNG
Helix 5: YAGGGPVHISSGHGALIYALV
Helix 6: ITSVVLGTVFLWFGWFGF
Helix 7: AWYSCVSTNLAASCGGLAWMFI
Helix 8: WTTIGLCSGAISGLVGITPA
Helix 9: IWASVIIGVVTASACNVAV
Helix 10: LDVYALHGVGGAVGSVLTGLFAA
Helix 11: YQLAAICSTVAWTCCVTTILLLIL

Query ID: D4HY35
query D4HY35 has 12, using last 11 helices
Helix 1: AFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAMTFALVCVLWMVY
Helix 3: YIHIAFQASFACITVGLIVGAVA
Helix 4: AVLIFVVIWLTFAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFLNTVIATAGAMLSW
Helix 8: SLLGVSSGAIAGLVAITPA
Helix 9: VGGALIIGVIGGLAGLWGVTIL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: WVQLFSVGLTIVWTAVVAFVGF

Query ID: A0A830ZZN8
Helix 1: DNAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAMTFALVCVLWMVY
Helix 3: YIHIAFQASFACITVGLIVGAVA
Helix 4: AVLIFVVIWLTFAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFLNTVIATAGAMLSW
Helix 8: SLLGVSSGAIAGLVAITPA
Helix 9: VGGALIIGVIGGLAGLWGVTIL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: WVQLFSVGLTIVWTAVVAFVGF

Query ID: E5B358
query E5B358 has 12, using last 11 helices
Helix 1: AFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAMTFALVCVLWMVY
Helix 3: YIHIAFQASFACITVGLIVGAVA
Helix 4: AVLIFVVIWLTFAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFLNTVIATAGAMLSW
Helix 8: SLLGVSSGAIAGLVAITPA
Helix 9: VGGALIIGVIGGLAGLWGVTIL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: WVQLFSVGLTIVWTAVVAFVGF

Query ID: A0A074ME37
Helix 1: TATLLVLLMILPGLALFYGGL
Helix 2: QIGATASLAMIIWVMWGYSLA
Helix 3: YVFISFQMTFAAITAALIL
Helix 4: VMMFVPIWLTIVYFPIAHMVWAG
Helix 5: FAGGTVVHINAGVSGLVLAYLLG
Helix 6: PHSLTLTMVGTGLLWVGWFGF
Helix 7: AGLAMINTFVATAAGALAWM
Helix 8: ALGFCSGVIAGLVAVTPAA
Helix 9: FGAILLGIVSSGVCYVFVASV
Helix 10: AFGIHGVGGIVGAIGTAIVY
Helix 11: VQVFSVLVTIAWAGIGTVIAGFAV

Query ID: Q2N625

Helix 1: AWMMTATVLVLLMILPGLALFY
Helix 2: TMTQIGATAALAMLVWVMW
Helix 3: YVFISFQMTFAAITAALIL
Helix 4: VMAFVPIWLTIVYFPIAHMVWAG
Helix 5: FAGGTVVHINAGVSGLVLAYLLG
Helix 6: PHSLTLTMVGTGLLWVGWFGF
Helix 7: AGLAMINTFVATAAAALTWM
Helix 8: ALGFCSGVIAGLVAVTPAA
Helix 9: FGAILLGILSSAVCYYFVA
Helix 10: LDAFGIHGIGGIVGAIGTGIVYQPF
Helix 11: FGVLVTIAWAGIGTLVAAYIV

Query ID: A0A7V8RCZ2
Helix 1: TWMLVSAVLVLMMSIPGLALFY
Helix 2: VLMQVLTIVSVAALVWVSWGY
Helix 3: LAFVVFQMTFACITPALIVGAFA
Helix 4: PLIIFTVLWLTLAYFPVAHMVWYWA
Helix 5: ALDFAGGTVVHINAGIAGLVGCLVIG
Helix 6: PHSLVMTMIGASLLWVGWFGF
Helix 7: TAVAFINTFVATAAATVAWAV
Helix 8: LGAATGAVAGLVAITPASGLA
Helix 9: ILLGFAASIVCFFFVTTV
Helix 10: VFGVHCVGGIIGAIGTGIVA
Helix 11: AVGITILWSGLVSAVLFYAL

Query ID: A0A7V8RAY5
Helix 1: AFMLICGALLMLFAVPGVLLM
Helix 2: GVFLHGTAIAALVSLLWVVV
Helix 3: AFVLFQIAGAMLAALLVAGAWA
Helix 4: WALAFGGMWSLIVYAPVAHWIWG
Helix 5: YAGGIALHFCAGISALVAALVI
Helix 6: ATHNPVMVLAGGALLFIGNFAL
Helix 7: ASSAIINAHVAACTSALVWLLI
Helix 8: TVSAMGAVNGLLAGLAAIAPAS
Helix 9: GAAILIGVIAAPACYFGLRFV
Helix 10: AFALHGIGGLVGALLVAIFI
Helix 11: VAQLVGLAGVAMWSILATLIISYGVA

Query ID: P69681
Helix 1: AFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVTVTFALVCILWVVYGYSLAF
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: FSAVLIFVVVWLTLSYIPIAHMVWG
Helix 5: GTVVHINAAIAGLVGA
Helix 6: MVFTGTAILYIGWFGFNAGS
Helix 7: AALAFVNTVVATAAAILGWIFGEWA
Helix 8: LLGACSGAIAGLVGVTPACGY
Helix 9: VGGALIIGVVAGLAGLWGV
Helix 10: CDVFGVHGVCGIVGCIMTGIFA
Helix 11: GHQLLVQLESIAITIVWSGVVAFIGYKLA

Query ID: P25527
query P25527 has 12, using last 11 helices
Helix 1: EAGPAVLLAYLFAGLLVVMIM
Helix 2: LYWWFWVLVIPLEANIAAMIL
Helix 3: SWVPGIPIWLFSLVITLALTG
Helix 4: WLALCKVIAILAFIFLGAVAI
Helix 5: FGAVLSAMLITMFSFMGAEIV
Helix 6: IFYLCSIFVVVALIPWNMPGL
Helix 7: LIMDCVILLSVTSCLNSALYT
Helix 8: YVAVLLSTGAAFLTVVVNYYA
Helix 9: VFKFLIDSSGAIALLVYLVIA
Helix 10: YPWLTWLVIGFITFVLVVMLF
Helix 11: LEVISTGLLAIGIICTVPIMA

Query ID: P39386
query P39386 has 12, using last 11 helices
Helix 1: LAPAAVSLYLAGGMALQWLLG
Helix 2: PVLITGALIFTLACAATMFTT
Helix 3: FLIARAIQGTSICFIATVGYV
Helix 4: IITSIVLIAPIIGPLSGAALM
Helix 5: VLFAIIAVMGFISFVGLLLAM
Helix 6: FLFGAATISLSYIPMMSWVAV
Helix 7: QFAWTQVPVFGAVIVANAIVA
Helix 8: FIWRAVPIQLVGLSLLIVGNL
Helix 9: VWLWSVLGTSLYAFGIGLIFP
Helix 10: LNMVILMVMSVSVEIGRWLWF
Helix 11: LPFHLLAVVAGVIVVFTLAGL

Query ID: P69680
Helix 1: AFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVTVTFALVCILWVVYGYSLAF
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: FSAVLIFVVVWLTLSYIPIAHMVWG
Helix 5: GTVVHINAAIAGLVGA
Helix 6: MVFTGTAILYIGWFGFNAGS
Helix 7: AALAFVNTVVATAAAILGWIFGEWA
Helix 8: LLGACSGAIAGLVGVTPACGY
Helix 9: VGGALIIGVVAGLAGLWGV
Helix 10: CDVFGVHGVCGIVGCIMTGIFA
Helix 11: GHQLLVQLESIAITIVWSGVVAFIGYKLA

Query ID: A0A942VQZ7
Helix 1: LADIVWVFLAACLVMFMQPGFAMV
Helix 2: FMVGSVLFLCVGFAVMFGGDGAFIGTS
Helix 3: LFIFFQTVFCATAATIVSGAVA
Helix 4: AYCICSAFVSLIIYPVSGHWIWG
Helix 5: FAGSTAVHSVGGWVALMGAVMV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IGHIAMTTNLAACAGGLTVMFFTWL
Helix 8: VSMTLNGVLAGLVGITAG
Helix 9: LWGALLVGLICGITVSLLVPFI
Helix 10: AISVHGGCGVMGTLLVGLLANY
Helix 11: LGVQLLGIIAVAAWALVTSGVMFFII

Query ID: A0A1H0VGF5
Helix 1: DTGFILVCAAMVCLMTPALAVFY
Helix 2: IMFQCFIAMGIVTVLWFIGGFSLIF
Helix 3: IWAPTIPFIAFFIFQLMFALVTPALIC
Helix 4: YMVFLTLWSLLVYIPVAHWVWG
Helix 5: FAGGTVVHMSAGFSALAAVLVVG
Helix 6: MVYVAIGAGLLWFGWFAF
Helix 7: AAMTITNSQISAGFGLMTWVIASWI
Helix 8: VLGAMMGALAGLVCITPGS
Helix 9: WAAAIIGVVGTLCCYGMI
Helix 10: LDVFGLHGVGGTVGIIMTGIF
Helix 11: LTQLAGAAIVMIYSFVLTVIML

Query ID: A0A317RN92
Helix 1: LADIVWVFLAACLVMFMQPGFAMV
Helix 2: FMVGSVLFLCVGFAVMFGGDSAFIGTS
Helix 3: LFIFFQTVFCATAATIVSGAVA
Helix 4: AYCICSAFVSLIIYPVSGHWIWG
Helix 5: FAGSTAVHSVGGWVALMGAVMV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IGHIAMTTNLAACAGGLTVMFFTWL
Helix 8: VSMTLNGVLAGLVGITAG
Helix 9: LWGALLVGLICGITVSLLVPFI
Helix 10: AISVHGGCGVMGTLLVGLLANY
Helix 11: LGVQLLGIIAVAAWALVTSGVMFFII

Query ID: A0A317RMH8
Helix 1: TGFILVCAAMVCLMTPALAVFY
Helix 2: IMFQCFIAMGIVTVLWFMGGFSLIF
Helix 3: FIAFFVFQLMFALVTPALICGAVA
Helix 4: SYMVFLTLWSFLVYIPVAHWVWG
Helix 5: FAGGTVVHMSAGFSALAAVLVIG
Helix 6: MVYVAIGAGLLWFGWFAF
Helix 7: AAMTITNSQISAGFGLMTWVIASWI
Helix 8: VLGAMMGALAGLVCITPGS
Helix 9: WAAAIIGVVGTLCCYGMI
Helix 10: LDVFGLHGVGGTVGIIMTGLF
Helix 11: LTQLAGAVIVMLYSFVLTIVML

Query ID: A0A942ZQQ0
Helix 1: TGFILVCAAMVCLMTPALAVFY
Helix 2: IMFQCFIAMGIVTVLWFMGGFSLIF
Helix 3: FIAFFVFQLMFALVTPALICGAVA
Helix 4: SYMVFLTLWSLLVYIPVAHWVWG
Helix 5: FAGGTVVHMSAGFSALAAVLVIG
Helix 6: MVYVAIGAGLLWFGWFAF
Helix 7: AAMTITNSQISAGFGLMTWVIASWI
Helix 8: VLSAMMGALAGLVCITPGS
Helix 9: WAAAIIGVAGTLCCYGMI
Helix 10: LDVFGLHGVGGTVGIIMTGIF
Helix 11: LTQLAGAVIVMLYSFVLTIVML

Query ID: A0A317RML7
Helix 1: DIAFVLICTILVFFMTPGLSLFYA
Helix 2: IMSTVFCCGLAIVMWFVCGYSL
Helix 3: IPGALFAFFQLMFCVITPAIIV
Helix 4: TFVFVGVWLLLVYYPLAHMVW
Helix 5: IHISSGVSGLVACIILGA
Helix 6: HNIPMFFTGAAVLWAGWFAF
Helix 7: AIQAVVNTGISSAAAMLSWMFI
Helix 8: KVTLMGSVTGAIVGLVAIT
Helix 9: VPFWSAIIIGALVSPICYFAM
Helix 10: SLDAFGCHGVGGIWGGIATGIFA
Helix 11: LFLAQLGAILISVAYSAVVTAIIMLVL

Query ID: A0A6N2Z556
Helix 1: LADIVWVFLAACLVMFMQPGFAMV
Helix 2: FMVGSVLFLCVGFAVMFGGDGAFIGTS
Helix 3: LFIFFQTVFCATAATIVSGAVA
Helix 4: AYCICSAFVSLIIYPVSGHWIWG
Helix 5: FAGSTAVHSVGGWVALMGAVMV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IGHIAMTTNLAACAGGLTVMFFTWL
Helix 8: VSMTLNGVLAGLVGITAG
Helix 9: LWGALLVGLICGITVSLLVPFI
Helix 10: AISVHGGCGVMGTLLVGLLANY
Helix 11: LGVQLLGIIAVAAWALVTSGVMFFII

Query ID: A0A6N2YNZ0
Helix 1: TGFILVCAAMVCLMTPALAVFY
Helix 2: IMFQCFIAMGIVTVLWFMGGFSLIF
Helix 3: FIAFFVFQLMFALVTPALICGAVA
Helix 4: SYMVFLTLWSLLVYIPVAHWVWG
Helix 5: FAGGTVVHMSAGFSALAAVLVIG
Helix 6: MVYVAIGAGLLWFGWFAF
Helix 7: AAMTITNSQISAGFGLMTWVIASWI
Helix 8: VLSAMMGALAGLVCITPGS
Helix 9: WAAAIIGVAGTLCCYGMI
Helix 10: LDVFGLHGVGGTVGIIMTGIF
Helix 11: LTQLAGAVIVMLYSFVLTIVML

Query ID: A0A0U2VGX2
Helix 1: LADIVWVFLAACLVMFMQPGFAMV
Helix 2: FMVGSVLFLCVGFAVMFGGDGAFIGTA
Helix 3: LFIFFQTVFCATAATIVSGAVA
Helix 4: AYCICSAFVSLIIYPVSGHWIWG
Helix 5: FAGSTAVHSVGGWVALMGAIMV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IGHIAMTTNLAACVGGLTVMFFTWL
Helix 8: VSMTLNGVLAGLVGITAG
Helix 9: LWGALLVGLICGITVSLLVPFI
Helix 10: AISVHGGCGVMGTLLVGLLANY
Helix 11: LGVQLLGIISVAAWALLTSGAMFFII

Query ID: E3GQ97
Helix 1: LADIVWVFLAACLVMFMQPGFAMV
Helix 2: FMVGSVLFLCVGFAVMFGGDGAFIGTS
Helix 3: LFIFFQTVFCATAATIVSGAVA
Helix 4: AYCICSAFVSLIIYPVSGHWIWG
Helix 5: FAGSTAVHSVGGWVALMGAVMV
Helix 6: LTLGALGVFILWFAWFGF
Helix 7: IGHIAMTTNLAACAGGLTVMFFTWL
Helix 8: VSMTLNGVLAGLVGITAG
Helix 9: LWGALLVGLICGITVSLLVPFI
Helix 10: AISVHGGCGVMGTLLVGLLANY
Helix 11: LGVQLLGIIAVAAWALVTSGVMFFII

Query ID: E3GI40
Helix 1: TGFILVCAAMVCLMTPALAVFY
Helix 2: IMFQCFIAMGIVTVLWFMGGFSLIF
Helix 3: FIAFFVFQLMFALVTPALICGAVA
Helix 4: SYMVFLTLWSLLVYIPVAHWVWG
Helix 5: FAGGTVVHMSAGFSALAAVLVIG
Helix 6: MVYVAIGAGLLWFGWFAF
Helix 7: AAMTITNSQISAGFGLMTWIIASWI
Helix 8: VLSAMMGALAGLVCITPGS
Helix 9: WAAAIIGVAGTLCCYGMI
Helix 10: LDVFGLHGVGGTVGIIMTGIF
Helix 11: LTQLAGAVIVMLYSFVLTIVML

Query ID: A0A2N0MZ27
Helix 1: DNAFMMICTALVLFMTVPGVALFY
Helix 2: MLTQVIVTFALVCVLWMLY
Helix 3: LIHVAFQCSFACITVALVVGGLA
Helix 4: AVLIFTVIWLTFSYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYMVG
Helix 6: PHNLPMVFTGASILYVGWFGF
Helix 7: SAASSIAALAFLNTVMATAGAILSW
Helix 8: SLLGASSGAIAGLVAITPA
Helix 9: VGGALIIGLVGGVAGLWGVVTL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWIQLLSVGVTLIWSGVVAFIAY

Query ID: A0A502GPV4
Helix 1: DNAFMMICTALVLFMTVPGVALFY
Helix 2: MLTQVIVTFALVCVLWMLY
Helix 3: LIHVAFQCSFACITVALVVGGLA
Helix 4: AVLIFTVIWLTFSYLPIAHMVWA
Helix 5: FAGGTVVHINAAIAGLVGAYLVG
Helix 6: PHNLPMVFTGASILYVGWFGF
Helix 7: SAASSIAALAFLNTVMATAGAILSW
Helix 8: SLLGASSGAIAGLVAITPA
Helix 9: VGGALVIGLIGGVAGLWGVVTL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VLIQLLSVGVTLVWSGVVAFIAY

Query ID: A0A085G774
Helix 1: DNAFMMICTALVLFMTVPGVALFY
Helix 2: MLTQVIVTFALVCVLWMLY
Helix 3: LIHVAFQCSFACITVALVVGGLA
Helix 4: AVLIFTVIWLTFSYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYMVG
Helix 6: PHNLPMVFTGASILYVGWFGF
Helix 7: SAASSIAALAFLNTVMATAGAILSW
Helix 8: SLLGASSGAIAGLVAITPA
Helix 9: VGGALIIGLVGGVAGLWGVVTL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWIQLLSVGVTLIWSGVVAFIAY

Query ID: A0A3E2TW06
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGFLVVLSVEFF
Helix 10: AVSVHFANGVWGTIAAGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A3R6HLW9

Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGFLVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A6A8KQL6
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A844DSN8
Helix 1: NTCWVLVAAFLVYFMQAGFALC
Helix 2: FCIGTPCYWVIGFGLMFGGTSALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAAML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: VCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFIIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLITVDVYVVVVMFIIF

Query ID: A0A844DI00
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGFLVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A413D0R3
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A3E2UCG9
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAVISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIAMLGAALL
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: LTGLVCFNTNLAAAVSTCVTMLF
Helix 8: MTLNGSLAGLVAITAGC
Helix 9: FGAFIIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGIQLLGLIVVDAYVLAVMFVIF

Query ID: A0A3E2UHE6
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDAYVVIVMFIIF

Query ID: A0A3E2VY88
Helix 1: VGAFLVYFMQAGFALCEAGFT
Helix 2: PCYWLIGFGLMFGGTGALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAWML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: ATMTLTGLVCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFFIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLVCVDVYVVIVMFIIF

Query ID: A0A3E2T713
Helix 1: NTCWVLVAAFLVYFMQAGFALC
Helix 2: FCIGTPCYWVIGFGLMFGGTSALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAAML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: VCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFIIGFVAGILVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LSTQLLGLITVDVYVVVVMFIIF

Query ID: A0A3E2XB32
Helix 1: NTCWVLVAAFLVYFMQAGFALC
Helix 2: FCIGTPCYWVIGFGLMFGGTSALI
Helix 3: LWVYIVFQTVFCATAATIVS
Helix 4: YCVYSAAISLVVYPICGHWMWG
Helix 5: FAGSAAVHNVGGVIALLGAAML
Helix 6: LTAGALGVFILWFCWFGF
Helix 7: VCFNTNLAAAVATCVTMIFTWL
Helix 8: VSMTLNGSLAGLVAITAGC
Helix 9: FGAFIIGFVAGVLVVLSVEFF
Helix 10: AVSVHFANGVWGTIAVGLF
Helix 11: LGTQLLGLITVDVYVVVVMFIIF

Query ID: E1SLM7
Helix 1: TFYFLISGALVMWMAAGFAML
Helix 2: LYAIACAMYLLVGYHIMYV
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFAVVLTGFIYPV
Helix 5: FAGSGIVHMAGAAAAIAGVLLL
Helix 6: LPLATLGTFILWLGWFGF
Helix 7: IFVNTNSAAAFGAIAALLVC
Helix 8: ADLTMILNGALAGLVAITA
Helix 9: SLVLAAAIGAVSGGLVVFSIV
Helix 10: GAISVHGVCGLFGLLVVPVS
Helix 11: LMGQLAGAAVIFAWVFGASLVTWGVL

Query ID: D3S2L0
Helix 1: WILTSAALVMLMVPGLALFYA
Helix 2: IMLSLVSYVIVSLQWVLFGYSL
Helix 3: FAFYQLTFAAITLAIITSAAA
Helix 4: SFVLFGLLWTTFVYDPFAKWLWG
Helix 5: FAGGAVVHISSGFGALALALALG
Helix 6: AHNVPMTLLGAGLLWFGWFGF
Helix 7: AVRAVIVTNTAAATGALVWLLI
Helix 8: VGSLAFVTGAIAGLASITPA
Helix 9: IWQSIVIGVVAGVLCYYAM
Helix 10: LDAWAIHGVGGAIGMLMLGI
Helix 11: IPQLVAVTVTIIYAFAVTYIIA

Query ID: S0APH6
Helix 1: WMLTASTLVGLMSIPGLAIYYAGL
Helix 2: MALYAFAAVLIIWILAGYNF
Helix 3: MFFQFVFAAITPILLLGGIL
Helix 4: AWMIFVPIWSLIVYSPVAYWLFA
Helix 5: FSGGYVIHLDAGIGALAAAFVI
Helix 6: ANNLGLVMLGLGLIWLGW
Helix 7: TIDAGIAIINTNVATAVSMMTW
Helix 8: SLIGASVGAIAGLVGITPA
Helix 9: IYGAMVIGIATGIIPWIFLY
Helix 10: LGVFSSHAVAGVVGGLLTGVLA
Helix 11: FYELGIQAFAAVIVILYVFALTYGLL

Query ID: S0AM98
query S0AM98 has 12, using last 11 helices
Helix 1: AMFVMAIIGFNTAFAPTLYGII
Helix 2: YFFFETACAAVTLALVGVIVL
Helix 3: AFFAFSIVYFIFIWNLPAAW
Helix 4: IVVHGAAAIAGLAIVYEIW
Helix 5: YQWLAVGILILWIGWFGF
Helix 6: VLVVVIATFVASGAGMVSTMLFS
Helix 7: TPIIIVAVNGILMGLIIVTPLA
Helix 8: ASALILGLIGGPLFVGAEKLF
Helix 9: LFPAHGVGGIFGVLMIGLF
Helix 10: AAASGNAILPNGLLFGGGFAAL
Helix 11: AFGVFVVVITVFAISFLAIFII

Query ID: I0KDC6
Helix 1: AWMLMATALVLLMTPGLAYFYG
Helix 2: MLQSFVAMGVISIIWVVCGFSLAF
Helix 3: WSLAATIPLAVFAFFQLKFAVITPALI
Helix 4: SYVLFMILFSLFVYAPLAHWTW
Helix 5: LDFAGGTVVHMSAGWAALAGAIYL
Helix 6: LPPANIPYVLLGTGLLWFGWFGF
Helix 7: AATAFATTNTAAAAAGLGWVL
Helix 8: LGFCIGAVVGLVAITPAAGF
Helix 9: AIFVGTIASMVSNYVAHL
Helix 10: VFPCHGVGGMVGMIMTGIFAS
Helix 11: FMNHMIALVVVSAFAFGMSFLLL

Query ID: I2GD40
Helix 1: AWMLVATALVLLMTPGLAYFYG
Helix 2: MLQSFIAMGVISILWVVVGFSLAF
Helix 3: WSLAATIPLVVFAFFQLKFAVITPALV
Helix 4: SYVLFMILFSLFVYAPLAHWTW
Helix 5: LDFAGGTVVHMSAGWAALAGALYL
Helix 6: FPPANIPFVLLGTGLLWFGWFGF
Helix 7: AASAFATTNTAAAAAGLAWVLF
Helix 8: KVSALGFCIGAVVGLVAI
Helix 9: FVTVPTSIFIGTIAAITSNYIA
Helix 10: LDVFPCHGVGGMVGMVMTGIFA
Helix 11: LFTTHMLALVIVSAFAFGMSLLLL

Query ID: A0A068NPW2
Helix 1: TLWVIIAAALVLLMTPALALFYG
Helix 2: FLHSFIMLGIVSILWLVIGYSIA
Helix 3: IPAGAFMLFQMMFAIITPALI
Helix 4: GYVMFTTLWSLLIYGPIACWVWNP
Helix 5: FAGGTVVHLASGVSALAACMVL
Helix 6: ILPNNLTTTLLGAGLLWFGWIG
Helix 7: LALSAFTGTHVAAAAGMLGWL
Helix 8: ALGAASGLVAGLVAITPGA
Helix 9: MSAILVGFVVGAICCMAVGL
Helix 10: VVGVHGVGGLLGAICTGIFASV
Helix 11: ILTQLIAVAVVGAFAFVGTLLLM

Query ID: A0A931PT48
Helix 1: TAWVLVASVLVLLMTPALSLFYGGLV
Helix 2: SIWLMGLGTLIWFLVGFTLAF
Helix 3: IPLAVFMLFQMKFAIITPALI
Helix 4: GYVLFTALWSALIYAPIACWVWNP
Helix 5: FAGGSVVHLASGVAALAACLALG
Helix 6: VPFVLLGAGLLWVGWIGF
Helix 7: LSTGSVAVGAFVATQLAGAAGMIAW
Helix 8: SAVGAATGLVAGLATITPAAGF
Helix 9: AIMIGLAGSIVCYMAVSL
Helix 10: VVGVHGAGGFLGMLLTGAFASVFANAAV
Helix 11: VLMQLLAGVTVLAFSFVGSLVLM

Query ID: A0A068NV61
Helix 1: WTLLGAFLVFGMQAGFVMLEAGFA
Helix 2: CIFDTCLCGFLFWAFGYAFMFA
Helix 3: YLTTGIPILAHWIFQFAFA
Helix 4: ILYSIAVTGFIYPILGHWCWGPG
Helix 5: FLDFAGSTVVHTIGGVISLAGAIAL
Helix 6: PHNLTVAAVGGFLLWFGW
Helix 7: VAANTTLAACAGGMAAMLVALWF
Helix 8: FDLGFTVNGFLGGLVAITCPCYW
Helix 9: SILLGLVAGVVVFFGVNYI
Helix 10: VTVHGFCGIWGTISLGLFACGKYGV
Helix 11: GPTVLIAQIIGSAVITILTFLIAIVI

Query ID: A0A2N6K4Y5
Helix 1: AFMLISAALVLLMTPGLAFFYG
Helix 2: LMMSFVLMGVVGVTWILWGY
Helix 3: IPHLAFMIYQAMFAIITPALI
Helix 4: AYSLFVLLWSTFVYSPLAHMVW
Helix 5: GTVVHISSGVSALVAAIVLGP
Helix 6: HNVPFILLGAGLLWFGWFGF
Helix 7: LASGSLATIAFVNTNTSAAAAALTWL
Helix 8: AVGAATGAVAGLVGITPAA
Helix 9: LAAILIGSITTFVCFYAVSF
Helix 10: TYPVHGVGGTVGAILTAVFATTAV
Helix 11: LAAIAIAYVVAGVGTFVILKLI

Query ID: A0A2N6JV02
query A0A2N6JV02 has 12, using last 11 helices
Helix 1: LWVAIAAFLVFFMNAGFCMLETGLC
Helix 2: NLIVFALATVAFWAIGFGLMF
Helix 3: FLFQLVFAGTAATIVSGAVAE
Helix 4: FLIFSLLLVGISYAITGHWIWG
Helix 5: FAGSTVVHSVGGWAALMGAALLG
Helix 6: VAIPAHNMSIATLGCLILWLGWFGF
Helix 7: AITHIALTTNMAGAVGGIAATVTAWLYL
Helix 8: MIINGILAGLVAVTAPCAYIT
Helix 9: IIGLIAGVIVVFAVTFF
Helix 10: ISVHLVCGIWGTLAVGLFAV
Helix 11: FFTQLIGVLSVGGMTVLLSTIFFLVL

Query ID: A0A243SC06
Helix 1: WIIVATALVLIMTPGLGFFYGGMVG
Helix 2: FMAMIIVTVLWVIIAFGLSFGPTIGGVI
Helix 3: LAPTIPFMLFALFQAKFAIITPA
Helix 4: FWAYLLFMVLFILFIYTPL
Helix 5: AGGTVVHMSAGWAALAGAIFLG
Helix 6: ITYVLLGTGLLWFGWFGF
Helix 7: AVQALGTTTVAAAAAGMAWVFL
Helix 8: GACIGVVVGLVAITPAAGF
Helix 9: AMFIGAIASIISNLVVRAF
Helix 10: FACHGVGGMVGMLLTGVFA
Helix 11: ALVVVSIFAFTASYVLFFIV

Query ID: F8E6R1

Helix 1: FYFLICGALVMWMAAGFAMLEAGLV
Helix 2: NVVLFAIACVMYLLIGYYIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFVIFCVILTGFIYPV
Helix 5: AGSGIVHLAGASAALSGAIFL
Helix 6: LPLATLGTFILWMGWFGF
Helix 7: VFVNTNAAAAGGLVAALIVATILF
Helix 8: MILNGALAGLVAITAGPSA
Helix 9: ATLIGVVGGIIVVFSIIFI
Helix 10: AISVHGVVGTWGLIAVPIT
Helix 11: LGVQVLGALSIFAWVFAVSSIVWLIL

Query ID: A0A1I4ZIZ6
Helix 1: AWMLISTALVLFMTIPGLALFYG
Helix 2: LMQSFAITALMTVLWVVIGYSLA
Helix 3: VFVMFQMTFAIITPALICGAFA
Helix 4: AMLAFMTVWFLAVYVPVAHMVW
Helix 5: MAAAGVLDFAGGTVVHINAGVAGLVCALVM
Helix 6: MPHNLVLSLVGAAMLWVGWFGF
Helix 7: AGMAMLVTHVACAAAALSWM
Helix 8: VLGIISGAVAGLVAITPAAGF
Helix 9: ALIIGLLSGAVCFWTAVHL
Helix 10: AFGVHGIGGILGAILTGFFAV
Helix 11: LQLKGVLFTVVYSGVLTFVIL

Query ID: T2KJ59
Helix 1: LWMLIAGILVFFMQAGFFLV
Helix 2: IAVGSLAFWFIGYSLMYGADV
Helix 3: LFFQTVFAATTATIVSGAIAG
Helix 4: YAIFSIILTALIYPIAGGW
Helix 5: AGSSIVHSVGGWAALVAAWMV
Helix 6: MYATLGVFILWLGWFGF
Helix 7: VLVTNLAASAGALSALLFTWF
Helix 8: LSMTLNGALAGLVSITAGCG
Helix 9: GAVLAGLIGGILVVLSIGFI
Helix 10: AISVHGVAGVWGTLVIGLWGI
Helix 11: QAIGVVAYAFWAIVLSYVFLTII

Query ID: T2KGT3
Helix 1: INNVWMMVCTALVFFMHLGFAFLEI
Helix 2: LFKNIFIICIGLLLYCLVGFNLMY
Helix 3: FLFQGMFAATAATIVSGAVA
Helix 4: IVPFMIFAIVYVGFVYPIA
Helix 5: GSTLVHSVGGWAAVIAVCLL
Helix 6: IPLATAGVLILWLGWFGF
Helix 7: LTSLTLVTTCLAAATGGVVCMLV
Helix 8: MFLNGILGGLVGITAGADQ
Helix 9: AIIIGAVAGALIVFAVSFI
Helix 10: IAVHLICGIWGTLAVGIFGNL
Helix 11: FISQLIGVASYAVFCIVTSFIIIFTL

Query ID: Q0RPB4
Helix 1: AWVLASAALVLLMTPGLAFFYG
Helix 2: IMQNFFCMGIVSVLWVLVTYSLA
Helix 3: IPPVVFVCFQLMFAVITPALI
Helix 4: AFALFIALWSVLVYGPVAHWVF
Helix 5: VHANAGAAALAVAIVLGP
Helix 6: HNVPFVLLGAGLLWFGWFGF
Helix 7: AGSAFVNTNTAAACAMLGWILV
Helix 8: MASTLGAASGAVAGLVAITPAA
Helix 9: VGSIVIGLLAGGVCALATAI
Helix 10: VGAVHLVGGALGALLIGLLGSS
Helix 11: QIVAVAAVVAYSFVVSLIIAGAV

Query ID: H8L2Q4
Helix 1: MLTSSMLVLLMTIPGLALFY
Helix 2: VLMQCFSIVALVSVLWVLYGY
Helix 3: VFVMFQMTFAIITPALIIGAFA
Helix 4: ALLWFTALWVTVVYLPMAHMVW
Helix 5: VIDFAGGTVVHINAGIAGLVACLMIG
Helix 6: PHNLGYTVIGASMLWLGWFGF
Helix 7: AGMAMLVTQVATAAAAIGWT
Helix 8: VLGIVSGAVAGLVAVTPAAG
Helix 9: GALVLGLVTGVICYFTATRL
Helix 10: VFGVHAVAGIVGALLTGPLAAPAL
Helix 11: VGFTVLWSGVLTWLILLLL

Query ID: A0A3F3HWV6
Helix 1: IAFILISSLLVWLMTPGLAFFYAGV
Helix 2: LGLIIIGLVSILWFAFGYSFA
Helix 3: ALFAFFQGTFAMITVLIIVGSVL
Helix 4: ALLLFLSFWLLVVYAPLAHMVW
Helix 5: DFAGGTVVHISSGVTGLVLALLLG
Helix 6: SSYTFIGGLLLWLGWFGF
Helix 7: GILAMFNSAIASAAGLLGFSYCA
Helix 8: LFNGALAGLVAITPAAGFV
Helix 9: LLFGMVAAPVIYWSLATL
Helix 10: AFGIHGVGGILGALLTAIFA
Helix 11: ALAVLLTVAFTAALSYLLA

Query ID: A0A0P0Z9P6
Helix 1: WMMTATLLVLFMTMPGLALFY
Helix 2: VLMQCTMICGIMIIAWVVYGYSFA
Helix 3: YLFIAFQMTFAVITPALIVGGFA
Helix 4: AVIAFVLIWTTFSYYPVAHMVW
Helix 5: FAGGTVVHINAGIAALVGAFVV
Helix 6: APHSMTLTMVGAAILWVGWFGF
Helix 7: AVLAMINTFTATAGALVAWAAI
Helix 8: KASMLGGASGIVAGLVAVT
Helix 9: IGPVGAIVLGAIASAGCYFFVAVV
Helix 10: VFGIHGIGGIIGAVGTGVFTSSALGGI
Helix 11: VWAQIVGVLITIVWSGVVSVIAF

Query ID: Q0G0A4
Helix 1: WMMTATLLVLFMTMPGLALFY
Helix 2: VLMQCTMICGIMIIAWVVYGYSFA
Helix 3: YLFIAFQMTFAVITPALIVGGFA
Helix 4: AVIAFVLIWTTFSYYPVAHMVW
Helix 5: FAGGTVVHINAGIAALVGAFVV
Helix 6: APHSMTLTMVGAAILWVGWFGF
Helix 7: AVLAMINTFTATAGALVAWAAI
Helix 8: KASMLGGASGIVAGLVAVT
Helix 9: IGPVGAIVLGAIASAGCYFFVAVV
Helix 10: VFGIHGIGGIIGAVGTGVFTSSALGGI
Helix 11: VWAQIVGVLITIVWSGVVSVIAF

Query ID: A0A0N7KZ12
Helix 1: YIFNTLLFLMGGFLVMWMAAGF
Helix 2: IGLYSTAGIMYWACGYSLM
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: SFMVFVIILTGFIYPIAGSWQWG
Helix 5: FAGSTLVHSVGGWAALAGVLLL
Helix 6: IPLATLGTFILWLGWFGF
Helix 7: IFANTNLAAAGGVVVTMILL
Helix 8: VDVTMVLNGALAGLVSITA
Helix 9: TAWQAILIGGVGGVIVVFTVPLL
Helix 10: IPVHLFAGIWGTIVVPAT
Helix 11: YVTQLIGVVAYGIFTFVASLVVFGIV

Query ID: Q0G0A3
Helix 1: YIFNTLLFLMGGFLVMWMAAGF
Helix 2: IGLYSTAGIMYWACGYSLM
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: SFMVFVIILTGFIYPIAGSWQWG
Helix 5: FAGSTLVHSVGGWAALAGVLLL
Helix 6: IPLATLGTFILWLGWFGF
Helix 7: IFANTNLAAAGGVVVTMILL
Helix 8: VDVTMVLNGALAGLVSITA
Helix 9: TAWQAILIGGVGGVIVVFTVPLL
Helix 10: IPVHLFAGIWGTIVVPAT
Helix 11: YVTQLIGVVAYGIFTFVASLVVFGIV

Query ID: Q0G2V0
Helix 1: IFYWWCTALMITIHAGFL
Helix 2: LLAFAFVVPTFFFFGWWIY
Helix 3: GVFWAAFALFAATTASIMSGAVI
Helix 4: AFLILAIILGSVVWILGGAWGW
Helix 5: VGAAGVVHLIAGAFTLGVLLNL
Helix 6: VPLTVIGLMLIIVGFFGFLGGCIIYMG
Helix 7: ATLSAFAFNTLMSFSGGIIGGW
Helix 8: FWMMSCGLVGIISAASGL
Helix 9: PLAFTIGFVGGYTAPLVA
Helix 10: VGAVAVHGFGGAWGVLAMGLFAAG
Helix 11: LYGQIISLVVLGVLGFAPGYLIS

Query ID: Q0G2U1
Helix 1: LIYASGTVGAIMVVIGLLLI
Helix 2: FFIGFATYFFCGFAFWASQYYI
Helix 3: FQIFVFFLACFAGIVNVLF
Helix 4: AYYVMAFVAAIMSSILSWLTWGS
Helix 5: FFGVGFVYLFPAGMALALSWKL
Helix 6: VGLAASGLMTIFAGLPMVILSCLFFF
Helix 7: FNNYGIAWAAGALSGALLAY
Helix 8: YLLLGPLAGYVSGAPAF
Helix 9: WQMFLVALGAPFIAYAVY
Helix 10: KLLPLFLGAGTYGLIMVGIL
Helix 11: IVMQLAGIVTCVAFGVVTALVLALIL

Query ID: Q0G2T1
Helix 1: FYYWVTVVFMFLIHVGFCLY
Helix 2: CIPLVTITFFFFGWWIYFAF
Helix 3: GVFWAAFLLFSWTAASIVSGSVI
Helix 4: AFWILAVTIGSLAWIIDAAWGW
Helix 5: VIHAIAGGFALGILIVLG
Helix 6: WLATLGLFLIYTGFWGFYAACNIPII
Helix 7: YLAPTTLSAITFNFLMSLSGGLLMGYV
Helix 8: FWTYSAGLAGIIAASAGN
Helix 9: IQAMFIGAIGAFAAYRLH
Helix 10: AVGAVAVHGYAGFIGVVIAGFML
Helix 11: FIGAIIMFGLLGFLPGFVVA

Query ID: L8JUH3
Helix 1: VWMMLATVLVFIMHLGFAGVEA
Helix 2: LFKNTLTPVIGILTYYIIGFNLMY
Helix 3: FLFQAMFAATAATIVSGAVA
Helix 4: SYLTFTLLFVGIVYPIIGSWKWG
Helix 5: FAGSTLVHSVGGWGALAGIILL
Helix 6: VPLATIGIFLLWLGWFGF
Helix 7: AVSYVLVTTSLAACTGALGGLFAGYFVF
Helix 8: MVLNGVLAGLVGITAGA
Helix 9: GWALVVGLVAGILVVFSAVTL
Helix 10: VSVHLTCGVWGTLAVGIFGV
Helix 11: QLFGVAVCGITAFTSAFLIFFLL

Query ID: K2IMJ7
Helix 1: FYLLVSGAFVMWMAAGFAMLEAGLV
Helix 2: NAVLFAIACVMYMLCGYNIM
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWVFLAFAVVLTGFIYPI
Helix 5: AGSGIVHLTGASAALAGVLLL
Helix 6: LPLATLGMFILWMGWFGF
Helix 7: VFVNTNMAAAGGLIAALVTAKLLF
Helix 8: MAINGALAGLVAITAEPL
Helix 9: LATAIGVVGGILVVFSVIGL
Helix 10: VGAISVHGTVGIWGVLAVPL
Helix 11: IFTVQLIGVASIFAWVFITSFVVWFVL

Query ID: A0A837CWL2
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVTGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQLESVVITLIYSSVMSVIILWV

Query ID: A0A0A3A148
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFTVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: A0A0A2ZRL7
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: F4H924
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: A0A0A2Y4H8
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: TFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: U1H1F7
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: A0A0A3AIB6
Helix 1: WVMLAAILVLFMTIPGLALFYA
Helix 2: MVQSFAVCCLVAVIWLVCGYSLA
Helix 3: VFMVFQMAFAIIAGAIITGAFA
Helix 4: AVLVFVGIWTLLVYVPTAHWVWSI
Helix 5: YAGGTVIHINAGVAGLCAALFIG
Helix 6: PYNLTLTLIGCAMLWIGWFGF
Helix 7: AGMALATTQIAAAVAALTWML
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: AVLIGLITSVFCFVAVTKI
Helix 10: AFGIHGIGGIVGAVLTGVFV
Helix 11: LAQVESVVITLIYSSVMSVIILWV

Query ID: D9SI59

Helix 1: WMLVATLLVIMMSIPGLALFY
Helix 2: ILMQVFSIFALITVLWAIY
Helix 3: FVFVAFQATFAAITVALIVGAFA
Helix 4: AVMLFSGLWFTFAYLPIAHMVWFW
Helix 5: FAGGTVVHINAAVAGLVGAFMV
Helix 6: APHNLVMTMIGAALLWVGWFGF
Helix 7: ATLAFANTLIATAAAVLTWL
Helix 8: LLGAASGAVAGLVAITPA
Helix 9: IGGGLVIGALSGVVCFWGV
Helix 10: ALDVFGIHGIGGILGALLTGVF
Helix 11: VWIQAQAVLTTVIWSGVVAFVCY

Query ID: D9SI36
Helix 1: FILLGAIMVLAMHAGFAFLELGTV
Helix 2: ILTDFSVSTLAYFFIGYLIAYGA
Helix 3: FFFLLTFAAAIPAIVSGGIA
Helix 4: TFMLVGFVYPFFEGIAWN
Helix 5: FAGSVVVHAVGGWIGLAAVLLLGA
Helix 6: FLALGAWILTVGWFGFNVMSA
Helix 7: ISGLVAVNSLMAMVGGTLAALWA
Helix 8: FVHNGPLAGLVAVCAGSDL
Helix 9: ALVVGAVAGGLFVVMFTLT
Helix 10: VWPLHGLCGAWGGIAAGIFG
Helix 11: FMSQLIGTLMGVGIAFAGGYLVY

Query ID: C1A872
Helix 1: AWVLVSTALVAFMVPGLAFFYG
Helix 2: MLMSLAALGVVTVQWVLFGYSLA
Helix 3: LLFTAFQGMFAGITVALFSGAVI
Helix 4: SYLVFGVIWTTFIYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVTAVVLAVVL
Helix 6: VPHNVPFALLGAGMLWFGWFG
Helix 7: IAANALMSTHAAAAAALVTWV
Helix 8: AVGGATGAVVGLVAITPAA
Helix 9: LAGLAIGALAAPCSFFALHY
Helix 10: VFACHGVAGIMGAVLTGVFA
Helix 11: VGIQLLAVVATIVFVGVASVVIL

Query ID: A0A3D4V557
Helix 1: AWVLVSTALVAFMVPGLAFFYG
Helix 2: MLMSLAALGVVTVQWVLFGYSLA
Helix 3: LLFTAFQGMFAGITVALFSGAVI
Helix 4: SYLVFGVIWTTFIYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVTAVVLAVVL
Helix 6: VPHNVPFALLGAGMLWFGWFG
Helix 7: IAANALMSTHAAAAAALVTWV
Helix 8: AVGGATGAVVGLVAITPAA
Helix 9: LAGLAIGALAAPCSFFALHY
Helix 10: VFACHGVAGIMGAVLTGVFA
Helix 11: VGIQLLAVVATIVFVGVASVVIL

Query ID: A0A1G9P6Q0
Helix 1: FILNSFSFLISGVLVMWMAAGFAML
Helix 2: LYSLAGILYYLIGYNLMYSGV
Helix 3: WFFQMVFVATAASVVSGTV
Helix 4: WPFLLFVVVLTGIIYPIQGAW
Helix 5: IVHSVGGWAALTGAIILGA
Helix 6: LATLGTFILWLGWFGFNGGSVLAL
Helix 7: VYLNTNLAAAGGIIAAMIALQVIY
Helix 8: MALNGALAGLVSITAGP
Helix 9: GGAVLIGAVGGVLVVLAVPLFD
Helix 10: VVGALSVHLVCGIWGTLAVPIT
Helix 11: FFVQLLGVVAVGAFVSLLSAGVWLA

Query ID: A0A0C2HHF2
Helix 1: FILNSFSFLISGVLVMWMAAGFAML
Helix 2: LYSLAGILYYLIGYNLMYSGV
Helix 3: WFFQMVFVATAASVVSGTV
Helix 4: WPFLLFVVVLTGIIYPIQGAW
Helix 5: IVHSVGGWAALTGAIILGA
Helix 6: LATLGTFILWLGWFGFNGGSVLAL
Helix 7: VYLNTNLAAAGGIIAAMIALQVIY
Helix 8: MALNGALAGLVSITAGP
Helix 9: GGAVLIGAVGGVLVVLAVPLFD
Helix 10: VVGALSVHLVCGIWGTLAVPIT
Helix 11: FFVQLLGVVAVGAFVSLLSAGVWLA

Query ID: A0A0B5FNH4
Helix 1: FILNTFSFLISGVLVMWMAAGFAML
Helix 2: LYSIAGILYYLIGYNLMYAGV
Helix 3: WFFQMVFVATAASVVSGTV
Helix 4: WPFLIFVVVLTGLIYPIQGAW
Helix 5: IVHSVGGWAALTGALILGA
Helix 6: LATLGTFILWLGWFGFNGGSVLAL
Helix 7: VYLNTNLAAAAGLVAAMIALQMIY
Helix 8: MALNGALAGLVSITAGPA
Helix 9: AAVLIGAVGGVLVVLAVPIFD
Helix 10: VVGALSVHLVCGIWGTLAVPFT
Helix 11: FVAQIVGVAAVGVFVSLTSSLVWLAL

Query ID: A0A0D8BQX6
Helix 1: DALWMMLSAVLVIGMQAGFALL
Helix 2: FSIASLAFWAFGFAITFGAGNSFI
Helix 3: FLFQLGFAGVSLAIAWGGFA
Helix 4: VYFLFGTIFTIAIYPVIGHWVWG
Helix 5: FAGSTVVHLQGAIAALVATILLG
Helix 6: VYTVIGGLILWIGWFGF
Helix 7: FFGYVALTTNLAAAAGAIAAIVT
Helix 8: AMVNGVLAALVAITAACAF
Helix 9: AVVIGAVAGSFTFWTSIYL
Helix 10: FSVHGIAGIIGTISTGFFASPRL
Helix 11: LIVQTVGVLGAAVYVAAVSFIILYA

Query ID: U2WTW8
Helix 1: ALWVMLSAVLVIGMQAGFALL
Helix 2: FAIASLAFWAFGFAITFGAGNSFI
Helix 3: FLFQLGFAGVSLAIAWGGFA
Helix 4: VYFLFGTIFTIAIYPVIGHWVWG
Helix 5: FAGSTVVHLQGAIAALVATILLG
Helix 6: VYTVIGGLILWIGWFGF
Helix 7: FFGYVALTTNLAAAAGAIAAIVT
Helix 8: AMVNGVLAALVAITAACAF
Helix 9: AVVIGAVAGSFTFWTSIYF
Helix 10: FSVHGVAGIIGTISTGFFASPRL
Helix 11: LIVQTVGVLGAAVYVAAVSFVILYAL

Query ID: Q5KZZ9
Helix 1: ALWVMLSAVLVIGMQAGFALL
Helix 2: FAIASLAFWAFGFAITFGAGNSFI
Helix 3: FLFQLGFAGVSLAIAWGGFA
Helix 4: VYFLFGTIFTIAIYPVIGHWVWG
Helix 5: FAGSTVVHLQGAIAALVATILLG
Helix 6: VYTVIGGLILWIGWFGF
Helix 7: FFGYVALTTNLAAAAGAIAAIVT
Helix 8: AMVNGVLAALVAITAACAF
Helix 9: AVVIGAVAGSFTFWTSIYF
Helix 10: FSVHGVAGIIGTISTGFFASPRL
Helix 11: LIVQTVGVLGAAVYVAAVSFVILYAL

Query ID: A0A4D7Q9P4
Helix 1: ALWVMLSAVLVIGMQAGFALL
Helix 2: FAIASLAFWAFGFAITFGAGNSFI
Helix 3: FLFQLGFAGVSLAIAWGGFA
Helix 4: VYFLFGTIFTIAIYPVIGHWVWG
Helix 5: FAGSTVVHLQGAIAALVATILLG
Helix 6: VYTVIGGLILWIGWFGF
Helix 7: FFGYVALTTNLAAAAGAIAAIVT
Helix 8: AMVNGVLAALVAITAACAF
Helix 9: AVVIGAVAGSFTFWTSIYF
Helix 10: FSVHGVAGIIGTISTGFFASPRL
Helix 11: LIVQTVGVLGAAVYVAAVSFVILYAL

Query ID: A0A1I5GN22
Helix 1: TAWVLISAALVLFMTPGLALFY
Helix 2: MMMMSFGALALISVLWVLY
Helix 3: LVFTVPSLAFVAFQGVFAVLTVALIS
Helix 4: WMVFAGVWATLVYFPVAHWVFAF
Helix 5: FAGGTAVHINAGAAGLALALVLG
Helix 6: PHNLPLVMIGAGILWFGWIGF
Helix 7: AAEVFVTTLAATGAATLGWLL
Helix 8: LGAASGVVAGLVAITPAC
Helix 9: LGALAVGLVAGVVCALAVGL
Helix 10: VVGVHLVGGLWGTVAVGLFASAAT
Helix 11: ALGALAVLVYSFVLTLVIGGVIA

Query ID: A0A1M7UEG2
Helix 1: TAWVLASAALVLFMTPGLALFY
Helix 2: MMMMSFGALALISVLWVLY
Helix 3: LVFTVPSMAFVAFQAMFAVLTVALIS
Helix 4: WMVFAGVWATLVYFPVAHWVFAF
Helix 5: FAGGTAVHINAGAAGLALALVLG
Helix 6: PHNLPLVMIGAGILWFGWFGF
Helix 7: AAEVFVTTLVATGAATLGWLLI
Helix 8: HATSLGAASGVVAGLVAITPA
Helix 9: PVGAVLVGFVAGIVCALAVGL
Helix 10: VVGVHLVGGIWGTLAVGLLA
Helix 11: LWRQAVGAGVVLGYSFVLTLGIGFVI

Query ID: D2SE15
Helix 1: TAWVLASAALVLFMTPGLALFY
Helix 2: MMMMSFGALALISVLWVLY
Helix 3: LVFTVPSMAFVAFQAMFAILTVALIS
Helix 4: WMVFAGVWATLVYFPVAHWVFAF
Helix 5: FAGGTAVHINAGAAGLALALVLG
Helix 6: PHNLPLVMIGAGILWFGWFGF
Helix 7: AAEVFVTTLVATGAATLGWLLI
Helix 8: HATSLGAASGVVAGLVAITPA
Helix 9: PVGAILVGLVAGIVCALAVGL
Helix 10: VVGVHLVGGIWGTLAVGLFA
Helix 11: LWRQAVGAGAVLAYSFVLTLVIGVVIA

Query ID: A0A410JZR4
Helix 1: TAWVLVSAALVLFMLPGLAMFYG
Helix 2: MMFSFIAMAVIGVQWVLIGFSVAF
Helix 3: VFAMFQGMFAIITCALISGAIV
Helix 4: AFIVFIVVWATIVYAPIAHWVW
Helix 5: LDFAGGTVVHFSSGTAALALAIVL
Helix 6: IPHNVGYTLIGAGILWFGWFGF
Helix 7: AGVAFVNTLVAPGAAGLGWL
Helix 8: IGLASGIVAGLVAITPAA
Helix 9: WAALIIGFVAGIICFYGC
Helix 10: LDVFGIHGIGGFWGAIATGIFATV
Helix 11: VMAAGVYSFVLSFIIALVI

Query ID: A0A410K1J5
Helix 1: LWTLIAAFMVFFMQLGFAMV
Helix 2: FSMGAIGYWAVGFALMFGATTTGFF
Helix 3: FWIFQTVFCATAATIVSGAIA
Helix 4: AYLLFSLAMTTIIYPIFGSWAW
Helix 5: GFGFIDFAGSTVVHSVGGWAALAGAIVV
Helix 6: IPLATIGVFILWFGWYGF
Helix 7: LPLIAVNTTLAPATAVLVALFTTVILF
Helix 8: MSLNGALAGLVGITAGCA
Helix 9: YAVLIGAVAGLLVVFSVIFF
Helix 10: ISVHGVCGVWGTLAAGLF
Helix 11: VILPQIIGIVAAFVWAFGISFIVF

Query ID: A0A1H9M798
Helix 1: WILVSTALVLLMTLPGIALFYA
Helix 2: MASVLGITCLVSLLWFAVGYSWA
Helix 3: VYAMFQLAFAIITAALVVGALV
Helix 4: ALLLFMSLWTLLVYAPVAHWVW
Helix 5: LDFAGGAVVHINAGVAGLVCAWFLG
Helix 6: PYNLGLTMVGASLLWVGWFGF
Helix 7: AGLALAVTHIAAAAGAAAWM
Helix 8: LLGLCSGLVAGLVAITPAA
Helix 9: AAALLIGGVAGLACYWGATGL
Helix 10: VFGVHGIGGIVGALLTGVLA
Helix 11: LTQMLSVLAVMAYSLVATALLLWL

Query ID: A0A1H9RTW8
Helix 1: AWMLTSTLLVILMIIPGLALFY
Helix 2: VLAQVFVIFALISVLWPLY
Helix 3: YVFVAFQGTFAAITVALIVGAFA
Helix 4: AVLIFAVLWFTFSYVPVAHMVWG
Helix 5: FAGGTVVHINAGIAGLIGAYMVG
Helix 6: PHSLTLTMVGASLLWVGWFGF
Helix 7: AGLAFINTVLATGAATLAWLA
Helix 8: LGAASGAVAGLVCITPAAGFV
Helix 9: IVMGLIIGPVCVWGVGGL
Helix 10: VFGVHGLGGIVGALLTAVFAS
Helix 11: LWVQTEGVLVTIVWSGVVSFISY

Query ID: A0A1B9JHS5
Helix 1: FMMICTALVLFMSIPGIALFY
Helix 2: MLSQVLVTFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLIGAYLLK
Helix 6: PFNLPYVYLGAAILYIGWFGF
Helix 7: AGLAFINTVAATAAAVLSWSF
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGIFA
Helix 11: GIQLMSVITCVIWTAVIAFVAY

Query ID: A0A1B9JZS5
Helix 1: ICTALVLFMSVPGIALFYGGLL
Helix 2: VLVSFSLIAVLWIVYGYSLA
Helix 3: LIWIAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVIWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLMGAYLLK
Helix 6: PFNLPLVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLSWSL
Helix 8: LGAASGVIAGLVGVTPAAGF
Helix 9: ALLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGVF
Helix 11: VGIQAMSVVTCIIWTSVVAFIAY

Query ID: A0A1B9LFW3
Helix 1: DNGFMMICTALVLFMSVPGIALFY
Helix 2: MLSQVLVTFSLIAVLWITYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMALWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAIAGIVGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTIAATSAAVLAWTL
Helix 8: LGSASGVIAGLVGVTPAAGF
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIFA
Helix 11: GIQLMSIITCVIWTAVISFVAY

Query ID: A0A1B9NQ91
Helix 1: FMMICTALVLFMSVPGIALFY
Helix 2: MLTQVLVTFSLIAVLWIIYGY
Helix 3: LIWIAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAIAGIVGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTF
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIF
Helix 11: VGIQLMSVITCVVWTTVVAYIAY

Query ID: A0A1B9K8L2
Helix 1: ICTALVLFMSVPGIALFYGGLL
Helix 2: VLVSFSLIAVLWIVYGYSLA
Helix 3: LIWIAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVIWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLMGAYLLK
Helix 6: PFNLPLVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLSWSL
Helix 8: LGAASGVIAGLVGVTPAAGF
Helix 9: ALLIGIICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCLLTGVF
Helix 11: VGIQAMSVVTCVIWTSVVAFIAY

Query ID: A0A2V4EA49

Helix 1: DNGFMMICTALVLFMSVPGIAFFY
Helix 2: MLSQVLVTFSLIAVLWIVYGY
Helix 3: IWIAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLLGAYLLK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLSWTI
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGVFA
Helix 11: GIQLMSVITCVVWTAIIAYIAY

Query ID: A0A1B9M5B8
Helix 1: DNGFMMICTALVLFMSVPGIALFY
Helix 2: MLSQVLVIFSLIAVLWITYGY
Helix 3: FIWVAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAIAGIIGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTL
Helix 8: LGSVSGVIAGLVGVTPAAGL
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIFA
Helix 11: GIQVMSVITCVIWTAVVAFIAY

Query ID: A0A1B9MYL7
Helix 1: ISTVLVLFMSFPGIALFYGGL
Helix 2: LSILSQVLVTFSLIAVLWIIY
Helix 3: FIWIAFQGSFACITCCLILGACA
Helix 4: AVIIFMVLWFTFSYIPIAHMIWG
Helix 5: FAGGTVVHINAAIAGLVGAYLL
Helix 6: RPFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTIAATAAAVLAWLL
Helix 8: LGAVSGVIAGLVGITPAAGF
Helix 9: ALLIGIISGFSGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGVF
Helix 11: VGIQLISVITCVVWTTVVSFFAY

Query ID: A0A1B9N3H7
Helix 1: GFMMICTALVLFMSVPGIALFY
Helix 2: MLTQVLVTFSLIAVLWIVYGY
Helix 3: LIWIAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPIAHMVWG
Helix 5: FAGGTVVHINAAIAGIVGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVVATAAAVLAWTF
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIFI
Helix 11: GIQLMSVITCVAWTTVVAYIAY

Query ID: A0A1C0A1D9
Helix 1: DNGFMMICTALVLFMSVPGIAFFY
Helix 2: MLSQVLVTFSLIAVLWITYGY
Helix 3: LIWIAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLLGAYMLK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTI
Helix 8: LGAASGVIAGLVGVTPAAGF
Helix 9: AMLIGLACGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VGIQLMSVITCVIWTAIIAFIAY

Query ID: A0A1B9JPL5
Helix 1: DNGFMMICTALVLFMSVPGIALFY
Helix 2: MLSQVLVTFSLITVLWIMYGY
Helix 3: LIWIAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVIWFTFAYIPMAHMVWG
Helix 5: FAGGTVVHINASVAGLIGAYLLK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IASLAFINTVAATAAAVLAWTI
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGIFTA
Helix 11: IQLLSVITCVVWTAIIALIAY

Query ID: A0A1B9KID3
Helix 1: GFMMICTALVLFMSVPGIALFY
Helix 2: MLSQILVTFSLIAVLWIIYGY
Helix 3: LIWVAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLMGAYLLK
Helix 6: PFNLPYVYIGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWSI
Helix 8: LGAASGIIAGLVGITPAAGF
Helix 9: ALLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGIF
Helix 11: IGIQLMSIITCIIWTAVVAFISY

Query ID: A0A1B9M1A9
Helix 1: FMMICTALVLFMSVPGIALFY
Helix 2: MLTQVLVTFSLIAVLWIIYGY
Helix 3: LIWIAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAIAGIVGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTF
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIF
Helix 11: VGIQLMSVITCVVWTTVVAYIAY

Query ID: A0A1B9MBX6
Helix 1: DNGFMMICTALVLFMSIPGIALFY
Helix 2: MLTQVLVVFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGIIGAYFIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTL
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGFICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: GIQLMSIITCVIWTTVISFISY

Query ID: A0A1B9MZ78
Helix 1: DNGFMMICTTLVLFMSIPGIALFY
Helix 2: MLTQVLVVFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGIIGAYFIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTL
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGFICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: GIQLMSIITCVIWTTVISFISY

Query ID: A0A242NIL1
Helix 1: ADNGFMMICTALVLFMSIPGIALFY
Helix 2: MLSQVLVTFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLIGAYLLK
Helix 6: PFNLPYVYLGAAILYIGWFGF
Helix 7: AGLAFINTVAATAAAVLSWSL
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGIFA
Helix 11: GIQLMSVITCVIWTAVIAFISY

Query ID: A0A657K391
Helix 1: FMMICTALVLFMSVPGIALFY
Helix 2: MLTQVLVTFSLIAVLWIVYGY
Helix 3: LIWIAFQGSFACITCCLIPGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAIAGLVGAYLIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTF
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGLICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGIF
Helix 11: VGIQLMSVITCVVWTTVVAYIAY

Query ID: A0A556RTU3
Helix 1: DNGFMMICTALVLFMSVPGIALFY
Helix 2: MLSQVLVTFSLIAVLWIAYGY
Helix 3: IWIAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLIGAYMLK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLSWSF
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGVAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGVFA
Helix 11: GIQLMSVITCVIWTAIIAYIAY

Query ID: A0A556SRH6
Helix 1: FMMICTALVLFMSIPGIALFY
Helix 2: MLSQVLVTFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLMGAYLLK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLSWSF
Helix 8: LGAASGVIAGLVGITPAAGF
Helix 9: AMLIGLICGFAGVWGVSSL
Helix 10: VFGVHGVCGIVGCLLTGIFA
Helix 11: GIQLMSVITCVIWTSVIAFVAY

Query ID: A0A1B9NRG7
Helix 1: DNGFMMICTALVLFMSIPGIALFY
Helix 2: MLTQVLVVFSLISVLWIVYGY
Helix 3: LIWVAFQGSFACITCCLILGAFA
Helix 4: AVLIFMVLWFTFSYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGIIGAYFIK
Helix 6: PFNLPYVYLGAAILYIGWFG
Helix 7: IAGLAFINTVAATAAAVLAWTL
Helix 8: LGSASGVIAGLVGVTPAAGL
Helix 9: AMLIGFICGFAGVWGVSTL
Helix 10: VFGVHGVCGIVGCILTGVFA
Helix 11: AIQLMSIITCVIWTTVISFISY

Query ID: G4QHD2
Helix 1: LLLSSMLVFLMQAGFLCL
Helix 2: FIIAAIIFWLFGFALMFGDSF
Helix 3: ISFFIFQMMFCGTAATILSGAVA
Helix 4: AYLYATILLTSIIYPISGHWAW
Helix 5: FAGSTVVHSVGGWVALAAIIIIG
Helix 6: FPIGSNIPLSVLGTLLIWLGWFGF
Helix 7: ILLNTTLAAAWGGISAAAFHYYVY
Helix 8: FIMNGVIAGLVAITASCHAVS
Helix 9: IIGGIAGVILVSGTLWIN
Helix 10: ALGVVPAHLFAGIWGTIAVAIFA
Helix 11: LFAQLVGIAAIGAYAFVIGFVGL

Query ID: Q7NCB8
Helix 1: DTAWVLVSAALVLLMTPGLAFFYG
Helix 2: LMMSFVALGVIALVWTLVGYSIA
Helix 3: LAFMIFQMMFAVITPALISGAIV
Helix 4: TYVVFIMIWSVVVYSPVAHWVW
Helix 5: AIGALDFAGGTVVHLTAGISALVAAIIL
Helix 6: TPHNVPFVLLGAGLLWFGWFGF
Helix 7: LAANGLASLAFVTTNVATAAALSTWL
Helix 8: AVGAATGAVVGLVAITPAA
Helix 9: LSSIAIGGIAAIISFAAIQL
Helix 10: VFACHGMGGLTGAILTGVFA
Helix 11: LIEQLIGVGAVAVYAAVCTTVILLAL

Query ID: Q8GQS1
Helix 1: MLVSTALVLMMTVPGLALFYG
Helix 2: LMQSFAICCIVTIVWMVAGYSLA
Helix 3: VFMMFQMTFAIITPALITGAFA
Helix 4: ALCVFTILWSLLVYAPVAHWVW
Helix 5: VAGFGAIDFAGGTVVHINAGVAGLVTALVVG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIASAAAGVAWML
Helix 8: LGIISGAVGGLVAITPAAGF
Helix 9: ALIIGLLAGAVCHWTATTM
Helix 10: AFGVHGIGGILGALLTGVLAYGPL
Helix 11: QAKAVGVTIVWCAVVTFVLLKIV

Query ID: A0A7W4NFW5
Helix 1: WMLTSTALVLMMTVPGLALFYGG
Helix 2: VLATLMQSFAICCIITVLWMVA
Helix 3: VFMMFQMTFAIITPALIAGSFA
Helix 4: ALCVFTILWSLLVYAPIAHWVW
Helix 5: VAGFGAVDFAGGTVVHINAGIAGLVTALVLG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIATAAAGLSWM
Helix 8: VLGIISGAVAGLVAITPAAGF
Helix 9: ALVIGLITGAVCYFAATSL
Helix 10: AFGVHGIGGILGALLTGVLAY
Helix 11: FVTQAKAVGVTIVWCGVVTFILL

Query ID: A0A7W4FEM1
Helix 1: MLVSTALVLMMTVPGLALFYG
Helix 2: LMQSFAICCIVTIVWMVAGYSLA
Helix 3: VFMMFQMTFAIITPALITGAFA
Helix 4: ALCVFTILWSLLVYAPVAHWVW
Helix 5: VAGFGAIDFAGGTVVHINAGVAGLVTALVVG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIASAAAGVAWML
Helix 8: LGIISGAVGGLVAITPAAGF
Helix 9: ALIIGLLAGAVCYWTATTM
Helix 10: AFGVHGIGGILGALLTGVLAYGPL
Helix 11: QAKAVGVTIVWCAVVTFVLLKIV

Query ID: B5ZDQ6
Helix 1: MLVSTALVLMMTVPGLALFYG
Helix 2: LMQSFAICCIVTIVWMVAGYSLA
Helix 3: VFMMFQMTFAIITPALITGAFA
Helix 4: ALCVFTILWSLLVYAPVAHWVW
Helix 5: VAGFGAIDFAGGTVVHINAGVAGLVTALVVG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIASAAAGVAWML
Helix 8: LGIISGAVGGLVAITPAAGF
Helix 9: ALIIGLLAGAVCYWTATTM
Helix 10: AFGVHGIGGILGALLTGVLAYGPL
Helix 11: QAKAVGVTIVWCGVVTFILLKIV

Query ID: A9HMD6
Helix 1: MLVSTRWVLMMTVPGLALFYG
Helix 2: LMQSFAICCIVTIVWMVAGYSLA
Helix 3: VFMMFQMTFAIITPALITGAFA
Helix 4: ALCVFTILWSLLVYAPVAHWVW
Helix 5: VAGFGAIDFAGGTVVHINAGVAGLVTALVVG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIASAAAGVAWML
Helix 8: LGIISGAVGGLVAITPAAGF
Helix 9: ALIIGLLAGAVCYWTATTM
Helix 10: AFGVHGIGGILGALLTGVLAYGPL
Helix 11: QAKAVGVTIVWCAVVTFVLLKIV

Query ID: A9H9C4
Helix 1: WMLTSTALVLMMTVPGLALFYGG
Helix 2: VLATLMQSFAICCIITVLWMVA
Helix 3: VFMMFQMTFAIITPALIAGSFA
Helix 4: ALCVFTILWSLLVYAPIAHWVW
Helix 5: VAGFGAVDFAGGTVVHINAGIAGLVTALVLG
Helix 6: PFNLTYAVIGASLLWVGWFGF
Helix 7: AGMAMATTQIATAAAGLSWM
Helix 8: VLGIISGAVAGLVAITPAAGF
Helix 9: ALVIGLITGAVCYFAATSL
Helix 10: AFGVHGIGGILGALLTGVLAY
Helix 11: FVTQAKAVGVTIVWCGVVTFILL

Query ID: A0A149RYW7

Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A149UA34
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A4R4A245
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: Q5FSX6
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A829X098
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFIMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A067Z3S3
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A149SNB1
Helix 1: LISTALVLMMTVPGLALFYGG
Helix 2: VLATLIQSFAICCIASLVWMVA
Helix 3: VYMMFQMTFAVITPALITGAYA
Helix 4: SMCVFTILWLLVVYAPIAHWVW
Helix 5: VDFAGGTVVHINSGVAGLVCAYVLG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQLAAAAGGVAWMI
Helix 8: LGIISGVVAGLVAITPAAGF
Helix 9: AVVIGLIAGAVCFWSATWL
Helix 10: AFGVHGTGGIIGALLTGVLAY
Helix 11: LLAQAEAVCVTIVWCVIMTFVIL

Query ID: A0A149QSR6
Helix 1: LVSTAFVLMMTIPGLALFYGG
Helix 2: VLATLIQSFMICCIGSLVWMVA
Helix 3: VFMMFQMTFAVITPALITGAYA
Helix 4: SMCLFTVAWLLLVYAPVAHWVW
Helix 5: VHINSGVAGLVCAIILGR
Helix 6: FNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQVAAAAGGVAWMV
Helix 8: LGIISGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAGCFWSATWL
Helix 10: AFGVHGTGGIIGAILTGAFAY
Helix 11: VVAQAEAVGVTVVWCVIMTTLIL

Query ID: A0A149S1Z1
Helix 1: LVSTALVLMMTVPGLALFYGG
Helix 2: VLATLIQSFAICCIASLVWMVA
Helix 3: VYMMFQMTFAVITPALITGAYA
Helix 4: SMCVFTILWLLVVYAPVAHWVW
Helix 5: VDFAGGTVVHINSGVAGLVCAYVLG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQLAAAAGGVAWMV
Helix 8: LGIISGVVAGLVAITPAAGF
Helix 9: AVVIGLIAGAVCFWSATWL
Helix 10: AFGVHGTGGIIGALLTGLLAY
Helix 11: LLAQAEAVCVTIVWCVIMTFVIL

Query ID: A0A149QAW7
Helix 1: LVSTAFVLMMTIPGLALFYAG
Helix 2: VLATLMQSFALCCIMSIVWMVA
Helix 3: LFMMFQMTFAIITPALISGAYA
Helix 4: AMCIFSVLWSLLVYAPIAHWVW
Helix 5: VHINAGIAGLVCALVLG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AAMAMATTQIAAAGAGVAWMLV
Helix 8: TVLGVISGAVGGLVAITPAAGF
Helix 9: ALIIGLITGVICYWSATSL
Helix 10: AFGVHGVGGIVGAMLTGLFAY
Helix 11: FMVQGEAVIVTILWCGIISFVLL

Query ID: A0A149U2G9
Helix 1: LVSTALVLMMTIPGLALFYAG
Helix 2: VLATLMQSFALCCIMSIVWMVA
Helix 3: IFMMFQMTFAIITPALISGAYA
Helix 4: AMCVFSIIWSLVVYAPIAHWVW
Helix 5: VHINAGIAGLVCALVLG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMATTQIAAAGAGVAWML
Helix 8: LGVISGAVGGLVAITPAAGF
Helix 9: ALIIGLITGVVCFWSATSL
Helix 10: AFGVHGVGGIVGALLTGVFAY
Helix 11: LVVQSEAVIVTILWCGAISFILL

Query ID: A0A149TSA9
Helix 1: AWMLISTALVLMMTIPGLALFYA
Helix 2: LMQSFALCCIMSIVWMVAGYSLA
Helix 3: IFMMFQMTFAIITPALISGAYA
Helix 4: AMCVFSIIWSLVVYAPIAHWVW
Helix 5: VHINAGIAGLVCALMLG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMATTQIAAAGAGVAWML
Helix 8: LGVISGAVGGLVAITPAAGF
Helix 9: ALIIGLITGVVCFWSATSL
Helix 10: AFGVHGVGGIVGALLTGVFAY
Helix 11: LVVQSEAVIVTILWCGAISFILL

Query ID: I1KKI2
Helix 1: AWQLTAATLVGLQSMPGLVILYA
Helix 2: AFMALYAFAAVLICWVLVCYRMA
Helix 3: LVYFQFTFAAITLILLAGSVL
Helix 4: VPLWLIFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGFTAAYWVG
Helix 6: PNNVLLMLAGAGLLWMGWSGF
Helix 7: YAANIASSIAVLNTNICAATSLLVW
Helix 8: SVIGAVQGMMTGLVCITPGA
Helix 9: WAAIVMGILSGSIPWVTMMIL
Helix 10: AVAGLLGGLLTGLLAEPALCRLLLPV
Helix 11: LVAAMFVIGWNLVSTTIILLVIKLFI

Query ID: K7K8C3
Helix 1: WQLTSATLVGLQSVPGLVILYG
Helix 2: WALNSAFMALYAFAAVLVCWVGW
Helix 3: VYFQLVFAAITLILIAGALL
Helix 4: AWMLFVPLWVTFSYTICAFSIWST
Helix 5: YSGGFVIHLSSGVAGFVAACWV
Helix 6: PPNNILLMLAGAGLLWMGW
Helix 7: LNTHVCTAMSLLTWLFLDILFF
Helix 8: MITGLVCITPAAGTICPRVV
Helix 9: IIMGMMSGSIPWYTMMVLH
Helix 10: TLAVFHTHAVAGSLGGILAGFFA
Helix 11: MVQLLGIVFVILLNVTTTSIVCLLVRIIV

Query ID: K7K3F5
Helix 1: AWQLTAATLVGLQSMPGLVILYA
Helix 2: AFMALYAFAAVLICWVLVCHRMA
Helix 3: VYFQFTFAAITLILLAGSVL
Helix 4: VPLWLIFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGFTAAYWVG
Helix 6: PNNVLLMLAGAGLLWMGWSGF
Helix 7: SSIAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMMTGLVCITPGA
Helix 9: WAAIVMGILSGSIPWVTMMILH
Helix 10: TLGVFHTHAVAGLLGGLLTGLLA
Helix 11: LVAACFIAGWNLVSTTLILLTIQLFI

Query ID: I1L774
Helix 1: AWQLIAATLVGLQSVPGLIILYG
Helix 2: AFMSLYAFACVFFCWVVWGY
Helix 3: VYFQCVFAAITLILIAGAVL
Helix 4: AWMLFVPLWLTFSYTFTAFSIW
Helix 5: IHLSSGVAGFTAAYWVGPRL
Helix 6: ILLMLAGAGLLWMGWTGF
Helix 7: ASLAVLNTHACTATSLLTWVILDVL
Helix 8: VIGAVQGMITGLVCITPAA
Helix 9: WAALIMGVLSGSIPWFTMMVVH
Helix 10: TMAVFHTHAIAGTLGGLLTGLFA
Helix 11: ILGIIFVIFVNVISTSLICLFIRIFV

Query ID: I1N306
Helix 1: AWQLTAATLVGLQSMPGLVILYA
Helix 2: AFMALYAFAAVLICWVLVCYRMA
Helix 3: LVYFQFTFAAITLILLAGSVL
Helix 4: VPLWLIFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTAAYWVG
Helix 6: PNNVLLMLAGAGLLWMGWSGF
Helix 7: YAANIASSIAVLNTNICAATSLLVW
Helix 8: SVIGAVQGMMTGLVCITPGA
Helix 9: WAAILMGILSGSIPWVTMMIL
Helix 10: AVAGLLGGLLTGLLAEPALCRLLLPV
Helix 11: LVAAMFVIGWNLVSTTIILLVIKLFI

Query ID: I1K536
Helix 1: AWQMVSATLVGIQSMPGLVILYG
Helix 2: AFMALYAFAAVIICWVAWAY
Helix 3: VWFQCVFAAIAVVILAGSVLA
Helix 4: PLWLTFSYTIGAFSLWGGGFLFHW
Helix 5: SGGYVIHLSSGIAGFTAAYWVG
Helix 6: PNNVLLTLAGAGLLWMGWAGF
Helix 7: SSMAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIVMGVLSGSVPWFSMMVLG
Helix 10: TLAVFHTHAVAGLLGGILTGLFA
Helix 11: IVGALFIIGWNLVVTSIICVVISFIV

Query ID: A0A7X5BZ76
Helix 1: WVLVAAVLVILMQGGFILLE
Helix 2: IAGKTIFTLGLCTLVYWAVGYAFA
Helix 3: VFFIFQLAFAAVSLSIAWGG
Helix 4: LSAYLVFTVLFTALIYPVI
Helix 5: AGSTVVHLTGAIAAFAATVLL
Helix 6: QVFGALSVLILWVGWFGF
Helix 7: FFGYVAFNTQLGAAGGAVAALLISWL
Helix 8: ITTTLNGALAGLVAITAT
Helix 9: PWAAVVIGLVAGVLVFFSA
Helix 10: IFALSVHGAAGVWGTVANGIFATDVL
Helix 11: LWIQVESVLVCGGYTLVASFILL

Query ID: A0A7X4YNT4
Helix 1: TIWVVLTAAMILLMEGGFALLEAGFV
Helix 2: VFVDITFGALVFYFLGFGLMY
Helix 3: YWLFQCAFVIAVISIVSGAVA
Helix 4: AYILYAIAMTGLIYPVAGHWVW
Helix 5: IDFAGSAVIHALGGFAALAAAIFI
Helix 6: LPLASVGAFILWFGWFGF
Helix 7: SIGHIAVTTMLSAAAGGAGCILF
Helix 8: MVINGSLAGLVGITAGCSFVP
Helix 9: LIGAVCGIVMVLVTELL
Helix 10: FAVHGASGSLGTLAVGLFA
Helix 11: GLKLLGVQALGLAIVSVWGFALTWLVLMLI

Query ID: A0A8H6MPB9
Helix 1: SYILVSAAMVLLMIPGIAFLYS
Helix 2: LWVVMMSFSVIVFQWYFW
Helix 3: ALLYSFYQMMFCAVTAALTA
Helix 4: CMVFIFFWATLVYCPLACWAWNA
Helix 5: YAGGGPVEIGSGMSALAYSWVLG
Helix 6: PHNISLITLGTILLWFGWLGF
Helix 7: AALACWNSCLTAMFAAMTWCLL
Helix 8: KWSLVGWCSGTISGLVAAT
Helix 9: ITPWASIILGVVAGVACNFG
Helix 10: IGGIVGLIFNAFFATGSIIGL
Helix 11: YIQIAYIVACSAYSFAMSALIA

Query ID: A0A8H6NAG3
Helix 1: SYILVSAAMVLLMIPGIAFLYS
Helix 2: LWVVMMSFSVIVFQWYFW
Helix 3: ALLYSFYQMMFCAVTAALTA
Helix 4: CMVFIFFWATLVYCPLACWAWNA
Helix 5: YAGGGPVEIGSGMSALAYSWVLG
Helix 6: PHNISLITLGTILLWFGWLGF
Helix 7: AALACWNSCLTAMFAAMTWCLL
Helix 8: KWSLVGWCSGTISGLVAAT
Helix 9: ITPWASIILGVVAGVACNFG
Helix 10: IGGIVGLIFNAFFATGSIIGL
Helix 11: YIQIAYIVACSAYSFAMSALIA

Query ID: A0A8H6K7L7
Helix 1: SYILVSAAMVLLMIPGIAFLYS
Helix 2: LWVVMMSFSVIVFQWYFW
Helix 3: ALLYSFYQMMFCAVTAALTA
Helix 4: CMVFIFFWATLVYCPLACWAWNA
Helix 5: YAGGGPVEIGSGMSALAYSWVLG
Helix 6: PHNISLITLGTILLWFGWLGF
Helix 7: AALACWNSCLTAMFAAMTWCLL
Helix 8: KWSLVGWCSGTISGLVAAT
Helix 9: ITPWASIILGVVAGVACNFG
Helix 10: IGGIVGLIFNAFFATGSIIGL
Helix 11: YIQIAYIVACSAYSFAMSALIA

Query ID: D0L8H3

Helix 1: AWMLAAFVFVLLMFPGLALYY
Helix 2: MMTMVMSTLGITAIIYVLFGYGL
Helix 3: TLYYLAWFILFAAITIAIAA
Helix 4: WMVFAPIWLIVVYLPVAHWVFS
Helix 5: YAGGTAVHMNSGVAALALALVLG
Helix 6: VPMALLGGGILWFGWFGF
Helix 7: LGASFLTQVVILNTLLAGCAGMIGFLI
Helix 8: LGLITGAVAGLVGITPSA
Helix 9: IGALAVGLLAAGVVAFVLSF
Helix 10: AFAVHGLGGIVGTLCIVLFAA
Helix 11: WRELGGIAVTCTFSFLMTYLIA

Query ID: D0LAL7
Helix 1: WMLASASMVLLMTPALAFFYGGL
Helix 2: LNMMMMSFGALATVSVVYVLW
Helix 3: LPAIVFLGFQLTFAVITVALIS
Helix 4: WLVFSVVWATIVYFPLSHMVW
Helix 5: FAGGTVVHINAGMAGLILAIIVG
Helix 6: PHNIPFVMLGAALLWFGWFGF
Helix 7: AGLVWVNTTAATAAAMIGWLAV
Helix 8: HATSVGAASGIVAGLVAI
Helix 9: ALTPVGSLILGVIAGALAALAIGL
Helix 10: VVGVHLVAGLWGTIGIGLLA
Helix 11: VVQVVIALFALAFTGILTAVIALAL

Query ID: A0A369M386
Helix 1: STGFMLVCAMLVLLMTPGLAFFYG
Helix 2: MLMSFAVLGIVGVTWTVCGWSFA
Helix 3: VVFQLAFCMITTAIITGAVA
Helix 4: AVCAFVAVWTVVVYPPLAHMVWG
Helix 5: VVHISSGLTGLILCVIAGR
Helix 6: HNVPFVALGATLLWFGWFGF
Helix 7: AALALVNTVVASGAALVSWLVV
Helix 8: TLVGAATGLVAGLVVITPAA
Helix 9: WAAAAMGVVVSPVCYAAVSLL
Helix 10: AFGIHAVGGITGGLLTGLFCV
Helix 11: LGAQALGILVTVVFVGVLDVVLGFIV

Query ID: D6E7B3
Helix 1: STGFMLVCAMLVLLMTPGLAFFYG
Helix 2: MLMSFAVLGIVGVTWTVCGWSFA
Helix 3: VVFQLAFCMITTAIITGAVA
Helix 4: AVCAFVAVWTVVVYPPLAHMVWG
Helix 5: VVHISSGLTGLILCVIAGR
Helix 6: HNVPFVALGATLLWFGWFGF
Helix 7: AALALVNTVVASGAALVSWLVV
Helix 8: TLVGAATGLVAGLVVITPAA
Helix 9: WAAAAMGVVVSPVCYAAVSLL
Helix 10: AFGIHAVGGITGGLLTGLFCV
Helix 11: LGAQALGILVTVVFVGVLDVVLGFIV

Query ID: A0A1L3RLF1
query A0A1L3RLF1 has 12, using last 11 helices
Helix 1: WMLISSVIVLMMTVPGLGLFYAGMV
Helix 2: AFSAAAVLSIVWMVAGYSLAF
Helix 3: LFMFFQMTFAIITPALIAGAFA
Helix 4: AYLVFIVLWSLIVYSPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRY
Helix 6: LSYALIGASLLWVGWFGF
Helix 7: AAMAAVATQLGAAGAAIGWIVVEWI
Helix 8: VLGALSGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAICFWGATSL
Helix 10: AWGVHGIGGITGALLTGVFAY
Helix 11: LIIQAKAVGITLVWSGVMTFILL

Query ID: A0A1L3REC0
query A0A1L3REC0 has 12, using last 11 helices
Helix 1: WMLISSVIVLMMTVPGLGLFYAGMV
Helix 2: AFSAAAVLSIVWMVAGYSIAF
Helix 3: LFMFFQMTFAIITPALIAGAFA
Helix 4: AYLVFIVLWSLIVYSPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRY
Helix 6: LSYALIGASLLWVGWFGF
Helix 7: AAMAAVATQLGAAGAAIGWIVVEWI
Helix 8: VLGALSGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAICFWGATSL
Helix 10: AWGVHGIGGITGALLTGIFAY
Helix 11: LIIQAKAVGITLVWSGVMTFILL

Query ID: W6I7E0
query W6I7E0 has 12, using last 11 helices
Helix 1: WMLISSVIVLMMTVPGLGLFYAGMV
Helix 2: AFSAAAVLSIVWMVAGYSLAF
Helix 3: LFMFFQMTFAIITPALIAGAFA
Helix 4: AYLVFIVLWSLIVYSPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRY
Helix 6: LSYALIGASLLWVGWFGF
Helix 7: AAMAAVATQLGAAGAAIGWIVVEWI
Helix 8: VLGALSGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAICFWGATSL
Helix 10: AWGVHGIGGITGALLTGIFAY
Helix 11: LIIQAKAVGITLVWSGVMTFILL

Query ID: Q0BQ69
query Q0BQ69 has 12, using last 11 helices
Helix 1: WMLISSVIVLMMTVPGLGLFYAGMV
Helix 2: AFSAAAVLSIVWMVAGYSLAF
Helix 3: LFMFFQMTFAIITPALIAGAFA
Helix 4: AYLVFIVLWSLIVYSPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRY
Helix 6: LSYALIGASLLWVGWFGF
Helix 7: AAMAAVATQLGAAGAAIGWIV
Helix 8: LGALSGAVAGLVAITPAAGF
Helix 9: AVLIGLIAGAICFWGATSL
Helix 10: AWGVHGIGGITGALLTGIFAY
Helix 11: LIIQAKAVGITLVWSGVMTFILL

Query ID: L1IYP4
Helix 1: WILTSSALVFMMTIPGLAMFYGGLV
Helix 2: SFSIACLITILWVLFGYSLA
Helix 3: FVVYSLTFAIITPALISGAFA
Helix 4: PMLVFIGLWHLLVYCPIAHSTW
Helix 5: VHVAAGCAGLMSSIVVGKRA
Helix 6: ILISVLGASLLWVGWCGFNG
Helix 7: AATSVLNTNLAAATASLTWM
Helix 8: VLGIISGMFSGLVTITAGA
Helix 9: TGAFCMGFLAGPVCYFAA
Helix 10: LDAFGIHAPGGALGGILTGFFAT
Helix 11: QIYLQMYGVAFSAIWSLIVSYILL

Query ID: L1IYW7
query L1IYW7 has 12, using last 11 helices
Helix 1: AWVLTSSALVLMMTIPGLALFYG
Helix 2: VMQSFSIVCLITVLWMCFGYSL
Helix 3: FMVYELMFAIITPALICGAFA
Helix 4: PMLLFMALWHLLVYCPIAHAH
Helix 5: VVHVAAGCSGLMASLVIGS
Helix 6: HNILVSVLGASLLWVGWFGF
Helix 7: TAMAMAVTQISTAVSALAWM
Helix 8: VLGIISGAVAGLVAITPGA
Helix 9: TGAFFFGLLAGPVCYFVC
Helix 10: LDAFGIHGPGGVVGGIMTGLFAT
Helix 11: QLYLQLYGILFAIGWSCIGSLVLL

Query ID: A0A7S4NPK3
Helix 1: WILTSSALVFMMTIPGLAMFYGGLV
Helix 2: SFSIACLITILWVLFGYSLA
Helix 3: FVVYSLTFAIITPALISGAFA
Helix 4: PMLVFIGLWHLLVYCPIAHSTW
Helix 5: VHVAAGCAGLMSSIVVGKRA
Helix 6: ILISVLGASLLWVGWCGFNG
Helix 7: AATSVLNTNLAAATASLTWM
Helix 8: VLGIISGMFSGLVTITAGA
Helix 9: TGAFCMGFLAGPVCYFAA
Helix 10: LDAFGIHAPGGALGGILTGFFAT
Helix 11: QIYLQMYGVAFSAIWSLIVSYILL

Query ID: L1IHZ8
Helix 1: TAWMLTSSAIVLMMTIPGLALFYG
Helix 2: VIQSFAITCLVTFWWLALGYSL
Helix 3: VYIFFQLTFAIITAAIITGSFA
Helix 4: PMLIFISIWHILVYCPIAHW
Helix 5: DVVHISSGVSGLAASLIVG
Helix 6: PPHNVIFVFLGASLLWVGWFGF
Helix 7: AGMAALVTQIAAAMAGLSWMF
Helix 8: VGLVSGAVAGLVVITPASGY
Helix 9: AFVMGVIGGPICFGGIQL
Helix 10: AFGVHAIGGMVGGVLTGCFADA
Helix 11: IAGILITVSYSFVMTLIIL

Query ID: L1J6I4
Helix 1: AWILASTALVVMMTIPGLALFYGGL
Helix 2: SFLWFSFGYSLCFTAGDVFYGNS
Helix 3: LFMVYQMTFAVISAAIICGSFA
Helix 4: AMLIFIAIWHILVYCPVAHWS
Helix 5: VVHVSAGFSGLVASMLVG
Helix 6: SPHNALLVFLGASLLWVGWFGF
Helix 7: AINAMATTQMSGACGGLAWM
Helix 8: VVGIVSGSICGLVCITPG
Helix 9: LAGAVAIGLIGGITGFFSI
Helix 10: LDAFGVHGICGVVGCLATGLFA
Helix 11: QLYIQLYGVVVVVAYCSVISFLIL

Query ID: L1JEX0
Helix 1: HAGASIFCMNIGLVLIEASSL
Helix 2: TITSISLAALSCWILGFGFGFGI
Helix 3: WFLFFSVSSICGNISTLGL
Helix 4: YMTVLVSVVYPIIVHWCWGTGWLSAWGAY
Helix 5: LLDVGGAGVVYLVGGCACMVATIFL
Helix 6: SIAHLLGVLTFWFGSFSF
Helix 7: GMVTTAIAGGAGCLTSIATCSLL
Helix 8: YRGLNGTMVALVAISSCAIIV
Helix 9: LIVGTSSSLLALVTHLLI
Helix 10: IATFAVGGGWGLLCAGIFCTDADV
Helix 11: VQLVGLLVILTWTSALSWGCCFLV

Query ID: L1INN6
Helix 1: AWIVLCGALVFFMQAGFAMLEAGIV
Helix 2: NMIDASIAAIAFWLLGYGFA
Helix 3: FFQWAFAGAAATIVAGAVC
Helix 4: AYFIYSVFLSTFMYPVIVHWVW
Helix 5: FAGSGVVHMVGGFCGLVGAIIA
Helix 6: NTLQALGVFILWFGWYGF
Helix 7: AVNMTISAASAAITATFLA
Helix 8: GLNGVLAGLVGITANCAVV
Helix 9: FLIGFGAAIILLAGHSLLLYL
Helix 10: DASVVHGFCGMWGIWATGIF
Helix 11: VGSLVIAAWTIGMSVMLFLFI

Query ID: L1IUV5
Helix 1: IAFMLISTALVLMMTIPGLALFYG
Helix 2: VMQSFAITCLVSVLWIIAGYSL
Helix 3: VLFVMYQATFAIITCAIITGSF
Helix 4: APTLIFVGIWHLIVYCPIAHW
Helix 5: VVHISSGASGLAASIIVG
Helix 6: PPHNILLVFLGASLLWVGWFGF
Helix 7: ASIAMLVTHVSAAAGGFSWM
Helix 8: VLGAVSGAIAGLVVITPGSGY
Helix 9: AFVMGLIAGPFCYFSIQL
Helix 10: AFGVHGVGGMLGGILTGCFADAAIGG
Helix 11: LGIQLAGIAVTLVYSIIMTFIIL

Query ID: A0A212AV03
Helix 1: VAWMLVSTILVLFMILPGLALFY
Helix 2: VLMQCTLITAMVIVIWVVYGY
Helix 3: YVFICFQMTFACITPALIV
Helix 4: LMLFILLWVTVVYFPIAHMVW
Helix 5: VHINAGIAALVGALVIGPRI
Helix 6: MTLTMVGASILWVGWFGF
Helix 7: AALAMINTFTATAGAILAWCI
Helix 8: LGAASGLVAGLVAVTPAA
Helix 9: IGAIVLGAIASVVCYFFVAVI
Helix 10: VFGIHGVGGIVGAIGTGIFA
Helix 11: WVQIKAVLVTIVWCGVASFILL

Query ID: A0A1C6Z081
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGAGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTLSYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGIAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGILTA
Helix 11: VQALSVVVCIVWSGVAALIAF

Query ID: A0A377PBY1
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWIVYGYSLAFGSGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTISYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGILTA
Helix 11: VQALSVVVCIVWSGVAALIAF

Query ID: A0A377PLP5
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGAGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTISYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGIL
Helix 11: FGVQALSVVVCIVWSGVAALIAF

Query ID: A0A4Q9EZY8
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGAGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTISYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGIL
Helix 11: FGVQALSVVVCIVWSGVAALIAF

Query ID: A0A097R891
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGAGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTISYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGILTA
Helix 11: VQALSVVVCIVWSGVAALIAF

Query ID: G9Y5B0

Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGSGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTFSYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAVLYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLVAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGIL
Helix 11: FGVQALSVAICIVWSGVAALIAF

Query ID: A0A2A2M8K7
Helix 1: ICTALVLFMTIPGIGLFYGGLL
Helix 2: VMVTFAAICVLWVVYGYSLAFGSGNAIF
Helix 3: FYKMIHVAFQGSFACITVGLIV
Helix 4: IRFSAVLIFAVLWFTFSYI
Helix 5: FAGGTVVHINAAIAGLVGAYLLG
Helix 6: PHNLPMVFMGTAVLYIGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGCIAGLVAVTPAAG
Helix 9: GALLLGLIAGVAGLWGVVML
Helix 10: VFGVHGVCGIVGCLATGIL
Helix 11: FGVQALSVAICIVWSGAAALIAF

Query ID: A0A2A2MCP3
Helix 1: AFMLLCTSLVMLMTPGLAFFYGGL
Helix 2: AILWFVVGYSLCFGPTINGII
Helix 3: LIVHIGYQMMFAIITPALITGAFA
Helix 4: AYLIFLTLWLLFVYCPFVHMVW
Helix 5: LDFAGGIVVHATAGFAALAAALYV
Helix 6: SVPFIALGAGLLWFGWYGF
Helix 7: TVSAFFATDIAAATAAVTWLI
Helix 8: VGFLTGSIAGLATITPAAG
Helix 9: AAALIGIIASLVCYFMVGL
Helix 10: FGVHGMGGVVGSILLGVFATQLW
Helix 11: VVVVVFASVWSFIVTYGILWSI

Query ID: Q2S8H9
Helix 1: FYFLVMGALVMWMAAGFAML
Helix 2: LYAIACIMYLICGYEIMYGSGGYFL
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFAVVMTAFIYPM
Helix 5: FAGSGIVHLAGAAAALAGVLLLG
Helix 6: VNAIPGANLPLATLGTFILWMGW
Helix 7: VAIVFLNTNAAAATGAIAALITARLLF
Helix 8: MLLNGALAGLVAITANP
Helix 9: VASSLIGIVAGVLVVFSIVTL
Helix 10: VGAISVHGACGLLGLLVVPF
Helix 11: FLAQLAGAFTIFGWVFTTSLVVWGLI

Query ID: Q2SIR0
Helix 1: LFILLGAIMVLAMHAGFAFL
Helix 2: FGASTLAYFFVGYHIAYGV
Helix 3: FFFLLTFAAAIPAIISGGVA
Helix 4: FYPMLVAASICVGVVYPLF
Helix 5: FAGSVVVHAVGGWIAFAAVYLL
Helix 6: LVAFAPSNIPFLALGAWILTVGWFG
Helix 7: VSGLVALNSLMAMVGGIVTSMLV
Helix 8: FIHNGPLAGLVAVCAGSDI
Helix 9: ALITGAVAGALFVFLFEY
Helix 10: LGVWPLHGVCGLWGGVAAGMFG
Helix 11: FLSQLVGSITGAALALIGGFVVYGVA

Query ID: E7QV43
Helix 1: NSVWVLTVSFLIFFMQPGFAML
Helix 2: WCLGVLIYFLVGSGIAFIAGGLT
Helix 3: WVNWLFGAVFAMTAATIVSGAVA
Helix 4: AYLFYSIALTAVIYPVVQGFAW
Helix 5: FAGATVVHMLGGIAGLVGAYMV
Helix 6: LTLVMLGTFILAFGWYGF
Helix 7: VALNTTLGMGAGAVAAALTTTYL
Helix 8: LFTANGLLAGLVAVTGAV
Helix 9: FGGIALGLIAGVQVPLVY
Helix 10: VCGVFCVHGSAGAIGTWLIPVFA
Helix 11: LAQFTMQTLGIAVITVWTLVTTYLIF

Query ID: D8J4C6
Helix 1: MMWVLVVTFLIFFMHAGFAML
Helix 2: WAVGVVMFFFVGAAISTIVGAITGGGSY
Helix 3: WLFGAVFAMTAATIVSGAVA
Helix 4: AYVGFTVLLAAVIYPVVTGLTWA
Helix 5: FAGGMIVHAVGGIAGLTAAWIL
Helix 6: MTFAVLGTLVLAFGWYGF
Helix 7: VALATTLGMALGALGASVVSLAL
Helix 8: LYVANGLLAGLVGVTGI
Helix 9: WWGAVLVAFIAGAQLPLVF
Helix 10: VCAVFPVHGSAGVIGALAIPFVAIP
Helix 11: VVAQVVGVAVIAAWTIGATALVWGAF

Query ID: D0LTW3
Helix 1: VLLSGFLVFFMNAGFALVESGLC
Helix 2: NFIVFGLAVIGYWSVGYAWM
Helix 3: LYAMFFFQLCFAVTAATIVSGAVA
Helix 4: SFMLFSLVLTAVIYPVVGHWAW
Helix 5: ADFAGSTVVHSVGGWAALVGAILL
Helix 6: LAMVTLGGLILWLGWFGF
Helix 7: VPGIITATALAASFGTVVATMWSWL
Helix 8: LTLIVNGMLGGLVGITAG
Helix 9: LWAAAIIGSLCGVLVIESVMFI
Helix 10: ISVHLVCGVAGTLLTGVF
Helix 11: IGVLAVGAFVVLVSFVGWKIV

Query ID: A0A3C1KS02
Helix 1: FYFLVCGALVMWMAAGFAMLEAGLV
Helix 2: NVALYAIACTMYLICGYQFM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFAVVMTGFIYPI
Helix 5: YAGSGIVHLAGAAAALAGVLLL
Helix 6: MPLATLGTFILWMGWFGF
Helix 7: VFLNTNAAAAGGLIAALLLS
Helix 8: ADLTMALNGALAGLVAITA
Helix 9: TPLLAMIIGAIGGVIVVFSIVA
Helix 10: AISVHGVVGIWGIFAVLLS
Helix 11: FMGQLVGTLVIFVWVFGASLITWAIL

Query ID: F4KY49
Helix 1: NVAWMLVASSMVLLMTPGLSFFYG
Helix 2: MLQSFIALGIISVIWYVVGFSLAF
Helix 3: IPFVLFAAFQLKFAIITPALIT
Helix 4: YIIFIVLWSILIYAPLAHWAW
Helix 5: LDFAGGTVVHISAGIAALIGARVLG
Helix 6: AVLYTPYVILGTGLLWFGWFGF
Helix 7: AVTAFVNTNLASAAAAIAWILV
Helix 8: SALGACIGAVVGLVAITPA
Helix 9: FGPSLLIGAVAATVSNYAVV
Helix 10: GIVGMLMTAIFATEAFGGVIA
Helix 11: LLISHLIALAIVVAYTGVGSWLVY

Query ID: I0JI83
Helix 1: LMNNLWIVVCTVLVLLMQGGFILLE
Helix 2: IAGKTVFTIGIVSLVFWAVGYGLI
Helix 3: FMFQLAFAAIAMTIAFGGF
Helix 4: VAYVIFAILFSIVIYPVIAHWIWG
Helix 5: FAGSTVVHLTGAAAALAATMIL
Helix 6: QVFTALGVLILWVGWFGF
Helix 7: FFGYVALNTQLAAAAGAIGAMLMVWA
Helix 8: VPTTLNGALAGLVAITAS
Helix 9: PWAAVIIGLVGGAFVFFSM
Helix 10: IFALSVHGTVGIWGTLSNGLFAT
Helix 11: LGVQILGVVSSGLYAFVVSYIIL

Query ID: L0K9M1
Helix 1: WTLLAAFLVFFMQAGFAMV
Helix 2: FSLGSLIYWICGFAFMFGAGNTFI
Helix 3: LSAYWIFQAVFAATAATIVS
Helix 4: YLIYSAVITGIIYPVVGHWIW
Helix 5: AGSTVVHSVGGWAALAGALVL
Helix 6: LLMAALGVFILWFGWFGF
Helix 7: SIASIAVTTNLSAAAGATLAMIT
Helix 8: MTLNGALAGLVGITAGCAA
Helix 9: AVAIGALSGVLIVFAVEFI
Helix 10: VAVHGVCGSFGTMLVGFFA
Helix 11: ALLMTQIKGVVVVAIWTFVTAYILF

Query ID: M0MDP9
Helix 1: LVWVLTVTFLIFFMHAGFAML
Helix 2: WSIGVVAFFLVGAGVSSVVGGL
Helix 3: AAWVSWLFGAVFAMTAATIVSGAVAG
Helix 4: YVGYTILLAAIIYPVVTGFTWAGGF
Helix 5: FAGGMIVHGMGGIAGLTAAWVL
Helix 6: MSFAVLGTLILCFGWYGF
Helix 7: SFSYVGRVALTTTLGMAAGAIGAA
Helix 8: TLYVANGMLAGLVSITSI
Helix 9: WPGALVVGLLAGIQLPLVF
Helix 10: VCAVFPVHGSAGILGALAFPFVAV
Helix 11: VIGVAVIAGWTIVATAAVFGAL

Query ID: I3R0S7
Helix 1: YVWILVVSFLIFFMQPGFALL
Helix 2: ALGVLVYFVVGAGVATIVGGL
Helix 3: IDWLFGAVFAMTAATIVSGAV
Helix 4: YVVFAATITGFIYPVVQGLTW
Helix 5: LDFAGATVVHMCGGVAGLVGA
Helix 6: MLLAVLGTLILAFGWYGFNVG
Helix 7: VALVTTLGMGAGAVAAMVVST
Helix 8: PLWMANGLLAGLVAVTGAVPH
Helix 9: VTWWGGLVLGALGGAIVLPAY
Helix 10: VFAVHGVAGAVGTALIPVFAV
Helix 11: VAGVGIIALWTIVASAVVFAA

Query ID: I3R635
query I3R635 has 12, using last 11 helices
Helix 1: IAAEFGLSLTDLGILASAAIW
Helix 2: TVFGIVLAYVGIFSMASAFAT
Helix 3: VVVASAGITFVVGIQHVSQWF
Helix 4: AEGIYAGIGNAGAAGGALILP
Helix 5: AAFFYTGVVAILMAIVYVVFG
Helix 6: VVALALGYVMSFGLEISMNGW
Helix 7: FGSNLVIASTFAATFSLAAGL
Helix 8: QWTVLCMTFIVVSMTGLTFAG
Helix 9: LTVAAGFLVGMSCAFTEGAIF
Helix 10: GAAAGIVGGIGTFGGIGFPLV
Helix 11: TGYVIVAALMIPILALNAFIS

Query ID: M0J579
Helix 1: YVWILVVSFLIFFMQPGFALL
Helix 2: WALGVLVYFVVGAGVATIVGGLT
Helix 3: WIDWLFGAVFAMTAATIVSGAVA
Helix 4: AYVVFAATITGFIYPVVQGLTWSG
Helix 5: FAGATVVHMCGGVAGLVGAKMV
Helix 6: MLLAVLGTLILAFGWYGF
Helix 7: MGAALGRVALVTTLGMGAGAVAAMV
Helix 8: LWMANGLLAGLVAVTGAV
Helix 9: WGGLVLGALGGAIVLPAY
Helix 10: VCGVFAVHGVAGAVGTALIPVFAV
Helix 11: VAGVGIIALWTIVASAVVFAAAGTVFGL

Query ID: A0A482TED1
Helix 1: WILVVTFLIFFMQPGFALL
Helix 2: WILGTLIYFVVGAAIATIVGGLT
Helix 3: WIGWLFGAVFAMTAATIVSGAVA
Helix 4: AYVLFTVLMTAIIYPVVVGFTWGG
Helix 5: FAGATVVHMCGGVAGLVAAKMV
Helix 6: MLLAVLGTFILAFGWYGF
Helix 7: MGAALGRVALVTTLGMGAGGAMAML
Helix 8: LWTANGLLAGLVAVTGAV
Helix 9: WGGALLGGLGGFLVLPAF
Helix 10: VCGVFAVHGVAGAVGTALIPVFAVGG
Helix 11: FALQILGVLIIAAWTVTASGIVLYVL

Query ID: E4NS62
Helix 1: WILVVTFLIFFMQPGFALL
Helix 2: WILGTLIYFVVGAAIATIVGGLT
Helix 3: WIGWLFGAVFAMTAATIVSGAVA
Helix 4: AYVLFTVLMTAIIYPVVVGFTWGG
Helix 5: FAGATVVHMCGGVAGLVAAKMV
Helix 6: MLLAVLGTFILAFGWYGF
Helix 7: MGAALGRVALVTTLGMGAGGAMAML
Helix 8: LWTANGLLAGLVAVTGAV
Helix 9: WGGALLGGLGGFLVLPAF
Helix 10: VCGVFAVHGVAGAVGTALIPVFAVGG
Helix 11: FALQILGVLIIAAWTVTASGIVLYVL

Query ID: J2ZGN6
Helix 1: NLVWVLTVTFLIFFMHAGF
Helix 2: LLTWSVGVIVFFLVGAAVSTIV
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YISYTILLAAVIYPVVVGFTWA
Helix 5: FAGGMIVHGMGGLAGLTAAWII
Helix 6: LSFAVLGTLILAFGWYGFNV
Helix 7: FAYVGRVALVTTLGMAAGAIGAAAV
Helix 8: YVANGLLAGLVGITSIADAI
Helix 9: IVVGLLAGAQLPIVFGFI
Helix 10: VFPVHGSAGILGALMFPFFATSFW
Helix 11: FVSLAIPQVVGVAVIALWTFGATYVVF

Query ID: J3EXK0
Helix 1: YVWILVVSFLIFFMQPGFALL
Helix 2: WALGVLVYFVVGAGVATIVGGLT
Helix 3: WIDWLFGAVFAMTAATIVSGAVA
Helix 4: AYVLFAAVITGFIYPVVQGLTWSG
Helix 5: FAGATVVHMVGGIAGLVGAKMV
Helix 6: MLLAVLGTLILAFGWYGF
Helix 7: MGAALGRVALVTTLGMGAGAVAAML
Helix 8: LWMANGLLAGLVAVTGAV
Helix 9: WGGLILGALGGAIVLPAY
Helix 10: VCGVFAVHGAAGALGTALIPVFGVGGF
Helix 11: LIMQVLGVAIIALWTIVASGIVFAIA

Query ID: A0A1H6R9C6
Helix 1: FAAAMNGTWILVVTFLIFFMHAGF
Helix 2: LLTWSLGVTVFFLIGTAVSSLL
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPVVIAFTW
Helix 5: AGGMIVHGMGGIAGLTAAAVL
Helix 6: LTFAVLGTLVLAFGWYGF
Helix 7: LVAMSTTIAMASGGLGAGLVAWA
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGLAGAQLPIVF
Helix 10: VCAVFPVHGSAGVLGTLMFPFVAA
Helix 11: FIAQATGVVIIGGWTLTATAIVWYVL

Query ID: A0A847UCB6
Helix 1: LWVLVVTFLIFFMHAGFAML
Helix 2: WSVGVALFFLVGATVEGLVGGAG
Helix 3: WVTWLFGAVFAMTAATIVSGAVAG
Helix 4: YITYTVLIAAVIYPVVSGMSWY
Helix 5: AGLGFADFAGGMVVHGMGGIAGLTAAYVL
Helix 6: MTFAVLGTLILAFGWYGF
Helix 7: VAMTTTIAMASGAIGAGLISWV
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGLAGAQLPIVF
Helix 10: VCAVFPVHGSAGVLGTLLYSFVAV
Helix 11: LIGVAIITVWTVAATGLIWGAL

Query ID: A0A4D6KHD1
Helix 1: LWVLVVTFLIFFMHAGFAML
Helix 2: WSVGVALFFLVGATVEGLVGGAG
Helix 3: WVTWLFGAVFAMTAATIVSGAVAG
Helix 4: YITYTVLIAAVIYPVVSGMSWY
Helix 5: AGLGFADFAGGMVVHGMGGIAGLTAAYVL
Helix 6: MTFAVLGTLILAFGWYGF
Helix 7: VAMTTTIAMASGAIGAGLISWV
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGLAGAQLPIVFNFV
Helix 10: VFPVHGSAGVLGTLLYSFVAV
Helix 11: LIGVAIITVWTVAATGLIWGAL

Query ID: C7P0S0

Helix 1: LWVLVVTFLIFFMHAGFAML
Helix 2: WSVGVALFFLVGATVEGLVGGAG
Helix 3: WVTWLFGAVFAMTAATIVSGAVAG
Helix 4: YITYTVLIAAVIYPVVSGMSWY
Helix 5: AGLGFADFAGGMVVHGMGGIAGLTAAYVL
Helix 6: MTFAVLGTLILAFGWYGF
Helix 7: VAMTTTIAMASGAIGAGLISWV
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGLAGAQLPIVFNFV
Helix 10: VFPVHGSAGVLGTLLYSFVAV
Helix 11: LIGVAIITVWTVAATGLIWGAL

Query ID: A0A329Q0D7
Helix 1: YFLVCGALVMWMAAGFSMLEAGLV
Helix 2: NIALFAIACTMYLLVGYYLM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WAFLIFSVILTGFIYPVSGYW
Helix 5: IVHMAGASAALAGVLVLG
Helix 6: IYAIPGANMPLATLGTFILWLGWFGF
Helix 7: VLVNTNAAAAGGVIAALILA
Helix 8: ADLTMALNGAIAGLVSITA
Helix 9: SALGATLIGGFGGLLVVVSIVCL
Helix 10: ISAHGVVGIWGVLAVPLS
Helix 11: FGAQIIGIFGIFVWVFVASLIVWLIL

Query ID: E1V4T3
Helix 1: YFLVCGALVMWMAAGFSMLEAGLV
Helix 2: NIALFAIACTMYLLVGYYLM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WAFLIFSVILTGFIYPVSGYW
Helix 5: IVHMAGASAALAGVLVLG
Helix 6: IYAIPGANMPLATLGTFILWLGWFGF
Helix 7: VLVNTNAAAAGGVIAALILA
Helix 8: ADLTMALNGAIAGLVSITA
Helix 9: SALGATLIGGFGGLLVVVSIVCL
Helix 10: ISAHGVVGIWGVLAVPLS
Helix 11: FGAQIIGIFGIFVWVFVASLIVWLIL

Query ID: F8D7H6
Helix 1: AINYTWILVATFLIFFMHAGF
Helix 2: LLTWSVGVTVFFLIGATVEGI
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPVVTGLTWAGS
Helix 5: FAGGMIVHGMGGIAGLTAAWVL
Helix 6: LTFAALGTLILAFGWYGF
Helix 7: RVALTTTVAMACGAMGAGLVAWL
Helix 8: TLYVANGLLAGLAAITAI
Helix 9: WWGAFVVGGLAGIQLPLVFGFV
Helix 10: VFPVHGSAGVLGTLLFPFVA
Helix 11: FIAQAIGVGVITVWTVFATGLIWFVF

Query ID: Q18ES8
Helix 1: VWILVVCFLIFFMQPGFALL
Helix 2: WTLGVLVFFIVGAGVSSIIGMLTA
Helix 3: YIGWFFGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMTSVIYPVVTGLTWAG
Helix 5: FAGATVVHMVGGLAGLVGAKMV
Helix 6: MLLAVLGTLFLAFGWYGF
Helix 7: VVLNTTLGMGGGAVAAMIVSASW
Helix 8: LWAANGLLAGLVAVTGAV
Helix 9: WGGLILGLIAGALVLPTFRWVV
Helix 10: FVVHGSAGAIGTILIPVFGVTATGGYAF
Helix 11: LIMQVVGVLVIGTWTVFATIAVFGIANALF

Query ID: G0LFE3
Helix 1: VWILVVCFLIFFMQPGFALL
Helix 2: WTLGVLVFFIVGAGVSSIIGMLTA
Helix 3: YIGWFFGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMTSVIYPVVTGLTWAG
Helix 5: FAGATVVHMVGGLAGLVGAKMV
Helix 6: MLLAVLGTLFLAFGWYGF
Helix 7: VVLNTTLGMGGGAVAAMIVSASW
Helix 8: LWAANGLLAGLVAVTGAV
Helix 9: WGGLILGLIAGALVLPTFRWVV
Helix 10: FVVHGSAGAIGTILIPVFGVTATGGYAF
Helix 11: LIMQVVGVLVIGTWTVFATIAVFGIANALF

Query ID: U1PPI7
Helix 1: VWILVVCFLIFFMQPGFALL
Helix 2: WTLGVLVFFIIGAGVSSIVGMLTA
Helix 3: YIGWFFGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMTSVIYPVVTGLTWAG
Helix 5: FAGATVVHMVGGLAGLVGAKMV
Helix 6: MLLAVLGTLFLAFGWYGF
Helix 7: VVLNTTLGMGGGAVAAMIVSASW
Helix 8: LWAANGLLAGLVAVTGAV
Helix 9: WGGLLLGLIAGALVLPTFRWVV
Helix 10: FVVHGSAGAIGTILIPVFGVTAAGGYTF
Helix 11: LIMQVVGVLVIGTWTVLATMVVFGIA

Query ID: U1PIR6
Helix 1: VWILVVCFLIFFMQPGFALL
Helix 2: WTLGVLVFFIIGAGVSSLVGMLTA
Helix 3: YIGWFFGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMTSVIYPVVTGLTWAG
Helix 5: FAGATVVHMVGGLAGLVGAKMV
Helix 6: MLLAVLGTLFLAFGWYGF
Helix 7: VVLNTTLGMGGGAVAAMIVSASW
Helix 8: LWAANGLLAGLVAVTGAV
Helix 9: WGGLILGLIAGALVLPTFRWVV
Helix 10: FVVHGSAGAIGTILIPVFGVTTAGGYTF
Helix 11: LIMQVVGVIVIGTWTVFATIAVFGIA

Query ID: C7NND6
Helix 1: NTVWALVVAFLIFFMQPGFALL
Helix 2: WTLGILSYFIIGFGFSVLIATLTS
Helix 3: WVGWLVGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMTAVIYPVATGITW
Helix 5: FAGATVVHMLGGLAGLVGAYMV
Helix 6: MLLAVLGTLFLAFGWYGF
Helix 7: GRVALNTTLGMAGGALAAML
Helix 8: LWTANGLLAGLVAVTGAV
Helix 9: WGGLILGSLAGALVLPTF
Helix 10: VCGVFAVHGMAGAVGTALIPLFAY
Helix 11: LGMQIVGVIVIGIWAVVGSAIAFGI

Query ID: C7NND3
Helix 1: NVWVLTVTFLIFFMHAGF
Helix 2: LLTWSVGVTVFFVIGAGISGLI
Helix 3: LYGAVFAMTAATIVSGAVAG
Helix 4: FLLAAVIYPVVTGITWVGEYIAV
Helix 5: MIVHGLGGIAGLTAAYILG
Helix 6: TFAVLGTLMLAFGWYGFNVGTAAVF
Helix 7: VAMGTTIAMAAGAMGAGLVAWL
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFIVGGLAGAQLPIVFGFV
Helix 10: VFPVHGSAGVLGTLAFPFVAV
Helix 11: VLGVVIIAAWTILATGVVWGAL

Query ID: A0A0X8X7Y7
Helix 1: FYLLLSGALVMWMAAGFTML
Helix 2: LYSIAVIMYMLIGWNIMY
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WSFFIFAVVLTGFIYPIQGMW
Helix 5: IVHMAGAAAALAGVIVLGAR
Helix 6: AIPGANMPLAALGTLILWLGWFGF
Helix 7: VFMNTNLAAAGGVVAALILARALF
Helix 8: MALNGAIAGLVSITAGP
Helix 9: LLAATIGGVGGVLVVFSIVAL
Helix 10: VGAISAHGTAGIWGILAVLL
Helix 11: AGIAAIFGFVFLSSLLVWTIL

Query ID: W8KM07
Helix 1: FYFLVSGALVMWMAAGFTMLEAGLV
Helix 2: NIALYSIACIMYMIIGYNIM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WAFLAFCVILTGFIYPIQGFW
Helix 5: IVHMTGAVAALAGVLLLGA
Helix 6: NALPGANMPLATLGIFILWMGWFGF
Helix 7: VFTNTNLSAAGGVVAALITSRLLF
Helix 8: MGLNGALAGLVAITAEPL
Helix 9: LAVMIGFIGGVLVVFSIILL
Helix 10: ISAHGTAGIWGVFAVLLS
Helix 11: FVAQLVGVLSIFAFVFTASLLVWLIL

Query ID: B9LU00
Helix 1: LMWVAMVCFLIFFMHAGF
Helix 2: LLTWGVGVLVYFLIGFGIEGVA
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YVAYTIAISAVIYPVVAGVTWGGG
Helix 5: FAGGMIVHGVGGIAGLTAAYML
Helix 6: MTFAVLGTLILAFGWYGF
Helix 7: GGYAAVGRVALTTTLGMGAGAVGAAL
Helix 8: LYVANGVLAGLVAVTGI
Helix 9: WWGAILVALVCGLQLPLVF
Helix 10: VCAVFPVHGSAGVIGVLALPFVSV
Helix 11: VIGVVVITAWTIVATAVVFGAF

Query ID: M0D3Q9
Helix 1: TTWVLVVTFLIFFMHAGF
Helix 2: LLTWSVGVSVFFLIGAGIDSLV
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVAYTFLLAAVIYPVVSGMAWYDA
Helix 5: FAGGTVVHAMGGIAGLTAAWVL
Helix 6: MTFAVLGTLMLAFGWYGF
Helix 7: GRVAMTTTLAMASGAMAAGGVAWA
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGVAGAQLPIVFSIV
Helix 10: VFPVHGSAGVIGTLMLPIVVAP
Helix 11: FLAQLTGVVVIVAWTVVTTGLIWGAL

Query ID: M0D580
Helix 1: VWVLVVCFLIFFMQPGFALL
Helix 2: WVLGVLVFFAIGSAFSALVGQLTT
Helix 3: YIGWFFGAVFAMTAATIVSGAVA
Helix 4: AYVFVAAAMVAVIYPAMPGIAW
Helix 5: YLDFAGATIVHMCGGMAGLVGA
Helix 6: GHSMLLAVLGTLFLAFGWYGF
Helix 7: GGALGQVVMNTTLGMGAGGVAAML
Helix 8: LWAANGLLAGLVAVTGAV
Helix 9: WGGVILGGLAGALVLPTFRWVV
Helix 10: FAVHGMAGAVGTILIPLFGVTA
Helix 11: LIMQVAGVAVVGTWTVLASIVAF

Query ID: W0JIB3
Helix 1: GINLVWVLMATFLIFFMHAGF
Helix 2: LLTWSVGVTVFFLIGAGVESMA
Helix 3: WLFGAVFAMTAATIVSGAVAG
Helix 4: YVAYTFLLAAVIYPVVSGISWFD
Helix 5: FAGGTVVHAMGGIAGLTAAWIL
Helix 6: MTFAVLGTLVLAFGWYGF
Helix 7: VAMATTIAMGSGAIGAALVAWA
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFLVGGLAGAQLPIVFSFV
Helix 10: VFPVHGSAGVLGTLMLPVVA
Helix 11: LAGVVVIAVWTVLTTAIIWGAI

Query ID: A0A172YCA7
Helix 1: LVSTVLVLMMTIPGLALYY
Helix 2: VLMNCFAITALVSIIWVIYGY
Helix 3: IWITFQMTFAIITPALIVGAFA
Helix 4: AMLWFTGLWVTFVYFPIAHMVW
Helix 5: TVVHINSGIAGLVACIVIG
Helix 6: PHNLGYSMIGASLLWLGWFGF
Helix 7: AGMAMLVTQIATAAAALGWM
Helix 8: LLGIITGAIAGLVAVTPAA
Helix 9: MGAIILGAVAGVISFFASTSL
Helix 10: VFGVHGVAGIVGSLLTGAFAAPALG
Helix 11: LWIQLKGVLFTIVYTGIISYILL

Query ID: A0A172YBR4
Helix 1: TFYFLICGVLVMWMAGGFAMLEAGLV
Helix 2: NIILFAVSCVMYLLFSYHLM
Helix 3: FFFQVVFVATAMSIISGAVA
Helix 4: LWSFVIFAVFMTGIIYPTSGYW
Helix 5: IVHMAGASAALAGVLVLGA
Helix 6: NAIPGANLPLATLGAIILWMGWFGF
Helix 7: VLVNTNTAAAGGVIAALVLS
Helix 8: ADLTMALNGALGGLVSITA
Helix 9: AAFTATVIGAIGGIIVVFSII
Helix 10: GAISVHGVAGFWGVMVVPFT
Helix 11: FGAQLIGGVSIFLWVFLASLVVWLAI

Query ID: D2RU19
Helix 1: NYTWILVATFLIFFMHAGFAML
Helix 2: WSVGVTVFFLIGSTVEGLVAGNGFAF
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPVVTGMTWA
Helix 5: FAGGMIVHGMGGIAGLTAAWIL
Helix 6: LTFAVLGTLILAFGWYGF
Helix 7: RVALTTTLSMACGAMGAGLVALL
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAILVGTLAGAQLPIVFGL
Helix 10: VFPVHGSAGVLGTLLFPVVA
Helix 11: VTGVVAITVWTVGMTALIWFLF

Query ID: D0KXQ0
Helix 1: VLFVLSGAIMVLAMHAGFAFL
Helix 2: FAVSAIAYFFIGYFVAYHI
Helix 3: FFFLLTFAAAIPAIISGGIA
Helix 4: LAATFLLVSLVYPFYEGLIWN
Helix 5: YAGSMVVHGMGGWIAIAAVLLL
Helix 6: IPFLALGSWILAVGWFGFNV
Helix 7: IAGISGLVAVNSLMAMVGGILSALVV
Helix 8: FLHNGPLAGLVAVCAGSDV
Helix 9: ALVTGLIAGGLFVWLFTFV
Helix 10: VWSLHGVCGLWGALAAGIFGL
Helix 11: ISQFIGSAVAIAVALGAGFVIYGML

Query ID: Q45HK8
Helix 1: AWMLVCTAFVILMTLPGLGLFY
Helix 2: VLMQCFMIFSLIYILWFVY
Helix 3: LVFVAFQGAFAAITVALIIGAFA
Helix 4: AVILFSILWFTFSYLPMAHMVWFW
Helix 5: YAGGTVVHINAAIAGLVGSYVIG
Helix 6: PHSLTLTMVGASLLWFGWFGF
Helix 7: AALAFVNTILATAAAVLSWSF
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: IGAVVMGLIAGLLCLWGVSGL
Helix 10: VFGVHGVGGILGAILTGVFAA
Helix 11: VWIQFQGVLTTVVLSGVVSFIAY

Query ID: D8ITX4
Helix 1: AWMLVCTAFVILMTLPGLGLFY
Helix 2: VLMQCFMIFSLIYILWFVY
Helix 3: LVFVAFQGAFAAITVALIIGAFA
Helix 4: AVILFSILWFTFSYLPMAHMVWFW
Helix 5: YAGGTVVHINAAIAGLVGSYVIG
Helix 6: PHSLTLTMVGASLLWFGWFGF
Helix 7: AALAFVNTILATAAAVLSWSF
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: IGAVVMGLIAGLLCLWGVSGL
Helix 10: VFGVHGVGGILGAILTGVFAA
Helix 11: VWIQFQGVLTTVVLSGVVSFIAY

Query ID: A0A6M3ZJI1
Helix 1: AWMLISTAFVILMTLPGLGLFY
Helix 2: VLMQCFVIFSLIYILWFVY
Helix 3: LAFVGFQGAFAAITVALIIGSFA
Helix 4: AVILFSILWFTFSYLPMAHMVWFW
Helix 5: FAGGTVVHINAAIAGLVGSYVIG
Helix 6: PHSLTLTMVGASLLWFGWFGF
Helix 7: AALAFINTILATAAAVLSWSF
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: IGAVVMGLIAGLLCLWGVSGL
Helix 10: VFGVHGVGGILGALLTGVFAA
Helix 11: VWIQFQGVLTTVILSGVVSFIAY

Query ID: A0A5B8DZA7

Helix 1: FILLGAIMILAMHAGFAFLEL
Helix 2: LVKILADFAVSTIVYFFIGYYVA
Helix 3: LVKFFFLLTFAAAIPAIISG
Helix 4: LVATAVLVGLVYPFFEGIAWN
Helix 5: FAGSIVVHAVGGWIALPAVLLL
Helix 6: IPFLALGAWILTVGWFGFNVM
Helix 7: VAMNSLMAMAGGTLVALLM
Helix 8: FAYNGPLAGLVAVCAGSDL
Helix 9: ALVTGGMAGAIFVWMFT
Helix 10: LGVWPLHGLCGLWGGLAAGIFGLQAL
Helix 11: LIGSVMGIVIAALGGWIVYGLL

Query ID: A0A6M3ZKU5
Helix 1: FILLGAIMILAMHAGFAFLEL
Helix 2: LVKILADFAVSTIVYFFIGYYVA
Helix 3: LVKFFFLLTFAAAIPAIISG
Helix 4: LVATAVLVGLVYPFFEGIAWN
Helix 5: FAGSIVVHAVGGWIALPAVLLL
Helix 6: IPFLALGAWILTVGWFGFNVM
Helix 7: VAMNSLMAMAGGTLVALLM
Helix 8: FAYNGPLAGLVAVCAGSDL
Helix 9: ALLTGGIAGAIFVWMFT
Helix 10: LGVWPLHGLCGLWGGLAAGIFGLQAL
Helix 11: LIGSLMGIAIAALGGWIVYGLL

Query ID: A4G1J2
Helix 1: AWMLTSTMLVILMTIPGLALFY
Helix 2: VLMQVFVLFALITVLWAIYGY
Helix 3: YVFVAFQSTFAAITCALIVGAFA
Helix 4: AVIAFSVLWFTFSYIPIAHMVWAT
Helix 5: FAGGTVVHINAGVAGLVGAYMVG
Helix 6: PHSLTLTMVGASLLWVGWFGF
Helix 7: LGANGVAGLAFINTILATGAATLSWI
Helix 8: MLGAASGAVAGLVAVTPAAGFV
Helix 9: IVLGLLAGMICLWGVSGL
Helix 10: VFGVHGVGGIFGAIMTGVLAAPSL
Helix 11: GVLITIVWSGIVAFVAYKLV

Query ID: A9B874
Helix 1: DIIWLLIAAVLVFFMQAGFALV
Helix 2: FCVGTVLFFAIGFGLMYGASAGGFI
Helix 3: WVGFFFQLVFAATAATIVSGAV
Helix 4: ISYLIYSAVICGIVYPISGHW
Helix 5: WLFQLGFIDFAGSTIVHSVGGWAAVAGTILL
Helix 6: LTLGVLGVFILWVGWFGF
Helix 7: SIGYIAVTTNMAAAVGALSALITNWLI
Helix 8: AVASNGALAGLVAITAGCA
Helix 9: GALFIGLLGGIIFVYGSIFL
Helix 10: AIPVHCFNGIFGTLAVGLFASPAV
Helix 11: LLGTQAIGVLAVGAWAFTTMFIVFYVL

Query ID: A9AUR8
Helix 1: VLLSAALVMLMTPALGLFYG
Helix 2: LMHSFFMLALISVQWVLFGYSLA
Helix 3: FMIYQMMFAVITPALISGAFA
Helix 4: SFVIFSLAWSTLIYAPVAHWVW
Helix 5: LDFAGGTVVHITSGVSALVCALVLG
Helix 6: PHDTTMTVIGTALLWFGWFGF
Helix 7: LGAGGLAVSAFVNTNSAAAMAMLAWM
Helix 8: VLGASAGAVAGLVAITPAA
Helix 9: MASLIIGFLAGGICYFVV
Helix 10: LDVFGVHGVGGVLGAILVGVFA
Helix 11: LGVQALTVGIVAIYAAGMTWGIL

Query ID: C6XKC2
Helix 1: YLFLLGGLVVMFMAAGFCMLEAGLV
Helix 2: NIALYSIAGLMFWLVGYNLL
Helix 3: HFFQMVFVAATASIVSGTVA
Helix 4: LWPFLIFTAVLTGIIYPI
Helix 5: AGSTLVHSTGGWAALVGAIIL
Helix 6: IPLAALGTFILWFGWFGF
Helix 7: IFLNTNLAAAAGTMAAMILTTILY
Helix 8: MAFNGALAGLVSITAGPL
Helix 9: VAILIGAVGGVLVVLTIPLLD
Helix 10: VVGAIPVHLVCGIWGTMIVPLS
Helix 11: FGVQALGVVSVGAFVAITSAIVWMIL

Query ID: B0UT87
Helix 1: AWVMISAILVLFMTIPGLALFYG
Helix 2: MAQSFAVSGLIAVIWLCFGYSL
Helix 3: VFMIFQMTFAIIAGAIITGATV
Helix 4: ALLLFVGLWSLLIYVPTAHWVW
Helix 5: IHINAGVAGLVAAIVIGKRV
Helix 6: LVLTLIGTAMLQIGWFGF
Helix 7: AGMALATTQISASVGALTWIL
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: ALFIGMITSAVCFVGVMKL
Helix 10: AFGIHGLGGIVGAVLTGIFV
Helix 11: WTQIESVLITIIFSASGSFVLL

Query ID: Q0I445
Helix 1: AWVMISAILVLFMTIPGLALFYG
Helix 2: MAQSFAVSGLIAVIWLCFGYSL
Helix 3: VFMIFQMTFAIIAGAIITGATV
Helix 4: ALLLFVGLWSLLIYVPTAHWVW
Helix 5: IHINAGVAGLVAAIVIGKRV
Helix 6: LVLTLIGTAMLQIGWFGF
Helix 7: AGMALATTQISASVGALTWIL
Helix 8: LGLASGAVAGLVGITPAAGF
Helix 9: ALFIGMITSAVCFVGVMKL
Helix 10: AFGIHGLGGIVGAVLTGIFV
Helix 11: WTQIESVLITIIFSASGSFVLL

Query ID: Q9H310
query Q9H310 has 12, using last 11 helices
Helix 1: PSFQDVHAMVFVGFGFLMVFL
Helix 2: FSSVGFTFLLAAFALQWSTLV
Helix 3: SMINADFCAGAVLISFGAVLG
Helix 4: TQLLLMALLEVVLFGINEFVL
Helix 5: AGGSMTIHTFGAYFGLVLSRVLY
Helix 6: LFAMIGTIFLWIFWPSFNAAL
Helix 7: LNTYYSLAASTLGTFALSALV
Helix 8: IQNAALAGGVVVGTSSEMMLT
Helix 9: FGALAAGFLAGTVSTLGYKFF
Helix 10: MPGVLGALLGVLVAGLATHEA
Helix 11: LFGLFVTLMFASVGGGLGGLL

Query ID: Q9UBD6
query Q9UBD6 has 12, using last 11 helices
Helix 1: PSFQDVHVMVFVGFGFLMTFL
Helix 2: FSAVGFNFLLAAFGIQWALLM
Helix 3: NLINADFCVASVCVAFGAVLG
Helix 4: IQLLIMTFFQVTLFAVNEFIL
Helix 5: AGGSMTIHTFGAYFGLTVTRILY
Helix 6: LFAMIGTLFLWMYWPSFNSAI
Helix 7: INTYCSLAACVLTSVAISSAL
Helix 8: IQNATLAGGVAVGTAAEMMLM
Helix 9: YGALIIGFVCGIISTLGFVYL
Helix 10: IPGIIGGIVGAVTAASASLEV
Helix 11: IYGLLVTLAMALMGGIIVGLI

Query ID: Q02094
query Q02094 has 12, using last 11 helices
Helix 1: PLFQDVHVMIFVGFGFLMTFL
Helix 2: VGINLLVAALGLQWGTIVQGI
Helix 3: NMINADFSAATVLISFGAVLG
Helix 4: IMTILEIVFFAHNEYLVSEIF
Helix 5: IGASMTIHAFGAYFGLAVAGI
Helix 6: LFAMIGTLFLWMFWPSFNSAI
Helix 7: IVNTYFSLAACVLTAFAFSSL
Helix 8: MVHIQNATLAGGVAVGTCADMAI
Helix 9: SMIIGSIAGMVSVLGYKFLTPLF
Helix 10: LHGLPGVVGGLAGIVAVAMGA
Helix 11: AALGSSIGTAVVGGLMTGLIL

Query ID: Q02161
Helix 1: CLPLWALTLEAALILLFYFFT
Helix 2: LVASYQVGQDLTVMAAIGLGF
Helix 3: VAFNLFMLALGVQWAILLDGF
Helix 4: VITLFSIRLATMSALSVLISV
Helix 5: VLGKVNLAQLVVMVLVEVTAL
Helix 6: MNMMHIYVFAAYFGLSVAWCL
Helix 7: TIPSLSAMLGALFLWMFWPSF
Helix 8: VFNTYYAVAVSVVTAISGSSL
Helix 9: LIPSPWLAMVLGLVAGLISVG
Helix 10: LLGLLGEIIYIVLLVLDTVGA
Helix 11: MIGFQVLLSIGELSLAIVIAL

Query ID: P18577
Helix 1: CLPLWALTLEAALILLFYFFT
Helix 2: LVASYQVGQDLTVMAALGLGF
Helix 3: VAFNLFMLALGVQWAILLDGF
Helix 4: ISAGAVLGKVNLAQLVVMVLV
Helix 5: FYVFAAYFGLTVAWCLPKPLP
Helix 6: TIPSLSAMLGALFLWMFWPSV
Helix 7: MFNTYYALAVSVVTAISGSSL
Helix 8: ISMTYVHSAVLAGGVAVGTSC
Helix 9: LIPSPWLAMVLGLVAGLISIG
Helix 10: IFSLLGLLGEITYIVLLVLHT
Helix 11: MIGFQVLLSIGELSLAIVIAL

Query ID: Q15849
query Q15849 has 17, using last 11 helices
Helix 1: WSYNCVLSCIAIGGMFYALTW
Helix 2: LLALICALFCAYMEAAISNIM
Helix 3: VVGVPPGTWAFCLATIIFLLL
Helix 4: GILIILGLFIQNPWWAISGCL
Helix 5: AIAAGFHGYNGVLVGLLMAVF
Helix 6: WWLLLPVIIMSMSCPILSSAL
Helix 7: LPVFTLPFNITVTLYLAATGH
Helix 8: GGIFLIALFISSPLICLHAAI
Helix 9: IYFGLCGFNSTLACIAIGGMF
Helix 10: LLAIACALFAAYLGAALANML
Helix 11: VFGLPPCTWPFCLSALTFLLL

Query ID: Q9Y666
query Q9Y666 has 12, using last 11 helices
Helix 1: LTWIVGVAGVLESFLIVAMCC
Helix 2: MYILGTIEIFLTYISPGAAIF
Helix 3: VYGTCTLVLMALVVFVGVKYV
Helix 4: LALVFLACVVLSILAIYAGVI
Helix 5: IAASFTLLVGIYFPSVTGIMA
Helix 6: LAIVTTSFIYLSCIVLFGACI
Helix 7: LVIGMLAWPSPWVIVIGSFFS
Helix 8: PTWALLLTVLICETGILIASL
Helix 9: APILSMFFLMCYLFVNLACAV
Helix 10: LCLALMFICSWYYALSAMLIA
Helix 11: HIDVWWIVHDGGMLMLLPFLL

Query ID: P55011
query P55011 has 12, using last 11 helices
Helix 1: LVIMMATVVTTITGLSTSAIAT
Helix 2: PEFGGAIGLIFAFANAVAVAMYVVGFAETVVELLKE
Helix 3: NDIRIIGAITVVILLGIS
Helix 4: WEAKAQIVLLVILLLAIGDFVIGTF
Helix 5: FFSVFAIFFPAATGILAGANI
Helix 6: QSAIPKGTLLAILITTLVYVGIAVSVGS
Helix 7: TPLISAGIFSATLSSALASLVSAPKIFQALCKD
Helix 8: GYILTFLIALGFILI
Helix 9: LNVIAPIISNFFLASYALINFSVFHAS
Helix 10: NMWISLLGAILCCIVMFVI
Helix 11: WWAALLTYVIVLGLYIYVTY

Query ID: Q9UP95
query Q9UP95 has 12, using last 11 helices
Helix 1: VLQALLIVLICCCCTLLTAISMS
Helix 2: FGGAVGLCFYLGTTFAAAMYILGAIEILL
Helix 3: NNMRVYGTIFLTFMTLVVFVGVK
Helix 4: YVNKFASLFLACVIISILSIYAGGIK
Helix 5: FTVLVGIFFPSVTGIMAGSNR
Helix 6: IPVGTILAIITTSLVYFSSVVLF
Helix 7: WVIVIGSFFSTCGAGLQSLTGAPRLLQ
Helix 8: TWALLLTALIAELGILIASLD
Helix 9: MVAPILSMFFLMCYLFVNLACAV
Helix 10: YYHWALSFLGMSLCLALMFVSSW
Helix 11: YYALVAMLIAGMIYKY

Query ID: Q9H015
query Q9H015 has 12, using last 11 helices
Helix 1: VPLTTSLFFVGVLLGSFVSGQ
Helix 2: VLFATMAVQTGFSFLQIFSIS
Helix 3: VLFVIVGMGQISNYVVAFILG
Helix 4: LGVCTFFAVGYMLLPLFAYFI
Helix 5: MLLLALTVPGVLCVPLWWFIP
Helix 6: IAIMTIMSLLLWMLTSVGYFA
Helix 7: LNCFLSALIEIPAYITAWLLL
Helix 8: IIAAVLFWGGGVLLFIQLVPV
Helix 9: IGLVMLGKFGITSAFSMLYVF
Helix 10: VGVTSTASRVGSIIAPYFVYL
Helix 11: MLPYIVMGSLTVLIGILTLFF

Query ID: Q7LBE3
query Q7LBE3 has 14, using last 11 helices
Helix 1: VSATLACLTAIIQMGLGFM
Helix 2: FIRGFMTAAGLQILISVLKYIF
Helix 3: SLIFALISGAFLVLVKELN
Helix 4: FPIPTEMIVVVVATAI
Helix 5: SQWKDMIGTAFSLAIVSYVIN
Helix 6: QEMIALGCSNFFGSFF
Helix 7: LSVTLAVDGA
Helix 8: QVASLCVSLVVMITMLVLG
Helix 9: LPKSVLGALIAVNLKNSLKQLT
Helix 10: IWVVSFLSSFFL
Helix 11: LPYGVAVGVAFS

Query ID: Q9UHW9
query Q9UHW9 has 12, using last 11 helices
Helix 1: VLQAFAIVLICCCCTMLTAISMS
Helix 2: FGGAVGLCFYLGTTFAAAMYILGAIEIFL
Helix 3: NNMRVYGTAFLVLMVLVVFIGVR
Helix 4: YVNKFASLFLACVIVSILAIYAGAIK
Helix 5: FTLLVGIFFPSVTGIMAGSNR
Helix 6: IPIGTILAILTTSFVYLSNVVLF
Helix 7: WVIVIGSFFSTCGAGLQSLTGAPRLLQ
Helix 8: TWALLLTAAIAELGILIASLD
Helix 9: LVAPILSMFFLMCYLFVNLACAL
Helix 10: YYHWALSFMGMSICLALMFISSW
Helix 11: YYAIVAMVIAGMIYKY

Query ID: Q9H2X9
query Q9H2X9 has 12, using last 11 helices
Helix 1: IMESFCMVFICCSCTMLTAISMSAI
Helix 2: EFGGAVGLCFYLGTTFAGAMYILGTIEILL
Helix 3: NMRVYGTCVLTCMATVVFVGVK
Helix 4: YVNKFALVFLGCVILSILAIYAGVIK
Helix 5: FTLLVGIYFPSVTGIMAGSNR
Helix 6: SIPTGTILAIATTSAVYISSVVLF
Helix 7: VIVIGSFFSTCGAGLQSLTGAPRLLQAIS
Helix 8: TWALLLTACICEIGILI
Helix 9: LDEVAPILSMFFLMCYMFVNLACAV
Helix 10: WTLSFLGMSLCLALMFIC
Helix 11: WYYALVAMLIAGLIYKYI

Query ID: I8TC71
Helix 1: AWMLTATAIVLLMTIPGLALFY
Helix 2: VMMQCFAICSVITVLWTVYGY
Helix 3: AVFFTFQCTFAIITPALIVGAFA
Helix 4: AMLVFMVLWFTFCYAPMAHMVW
Helix 5: VVHINAGIAGLVAALVLG
Helix 6: PHNVGYALVGASLLWVGWFGF
Helix 7: AGMAMAVTQIATATAAVGWMLVEWI
Helix 8: VLGIISGAVAGLVAITPAAG
Helix 9: GALVIGLAAGVICFFAATSL
Helix 10: VFGVHGVGGIIGAILTGVFAAP
Helix 11: VLIQIKGVLLTVVWTGIGSFILL

Query ID: I7ZHW3

Helix 1: IAWMLTSTAFVLLMSLPGLALFY
Helix 2: TMTQTFAIFCLIGVLWVVY
Helix 3: LLFAVFQMTFACITVALIAGAYA
Helix 4: AVLIFSVIWFTFSYLPMAHMVWWW
Helix 5: FAGGTVVHINAGVAGLVAAIIL
Helix 6: APHSLVMSMIGASLLWFGWF
Helix 7: GYAVLAFANTAFATAAAGVSWF
Helix 8: LLGIISGAIAGLVGITPA
Helix 9: VNGALVIGLLCGAVCFFAVAYI
Helix 10: AFGVHAVGGIIGAVLTGVYV
Helix 11: ILIQIKAVLVAIVLSAVVTAVTLLLL

Query ID: D3DJN2
Helix 1: LISTALVMLMTLPGLALFYG
Helix 2: IAMSFVAYCLVSVIWVLYGY
Helix 3: LIFVVFQLTFAAITVALVS
Helix 4: WVLFSILWVSLVYVPIAHWVWG
Helix 5: FAGGTVVHINAGIAGLVGAILL
Helix 6: NLPMVVLGAGLLWFGWFGF
Helix 7: AAAAFLNTNTATAMAALSWM
Helix 8: LLGLASGAVAGLVAITPAA
Helix 9: VGAIVIGILAGTIPYFMVAVV
Helix 10: VFGIHGAAGILGALLTGIFA
Helix 11: IVQLVAIGTTIVYDAIATFVILVVL

Query ID: A0A066ZTE4
Helix 1: FYFLVTGALVMWMAAGFAMLEAGLV
Helix 2: NVGLFAIACIMYMLVGYNIM
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: SFFVFAIVFTAFIYPMQGYW
Helix 5: IVHMAGGAAALAGVLLLGAR
Helix 6: AIPGANLPLATLGTFILWLGW
Helix 7: VAMVFVNTLMAAAGGVIGSLIA
Helix 8: MMLNGALAGLVAITAEPLT
Helix 9: ATLIGLVGGIIVVFAIIIM
Helix 10: AISVHGIVGIFGLIAVTFT
Helix 11: IVAQLTGIAVIFAWVFITSLIVWSII

Query ID: A0A066ZRQ5
Helix 1: VDILWVLFSAVLVAIMQPGFTAL
Helix 2: FLIAFMIFAIVGASIMLGKSH
Helix 3: TLMLFHAMFASTAVTIISGAIA
Helix 4: SYLVIAVIVSLFIYPIQAHWAW
Helix 5: VHSVGGWAALAAILIIGPRIG
Helix 6: SNLAFSALGVFLIWLGWIGF
Helix 7: LALNAVTGLVILNTLIAGCSGGLVGLVLG
Helix 8: IMNGVLSGLVAITACAHLA
Helix 9: MIIGALGSIAYLIGKSVL
Helix 10: VPVHLFAGITGTLAVAFLV
Helix 11: QLTGIITIGALSFGVTYVLL

Query ID: A0A4P6UIK6
Helix 1: AWMTVATALVIFMTIPGLALFY
Helix 2: VLMQVFVVTCLIYVLWVIY
Helix 3: LTFVAFQATFAAITCALIVGSFA
Helix 4: AVLLFCVLWFTFSYLPVAHMVWYWA
Helix 5: FAGGTVVHINAGVAGLVGAYVL
Helix 6: APHSLTLTMVGAAMLWVGWFGF
Helix 7: TALAFINTLIATAAATLSWI
Helix 8: MLGAASGAVAGLVAITPA
Helix 9: VMGALIIGLLAGLVCLWGVTGL
Helix 10: VFGVHGVGGVLGALLTGVFAA
Helix 11: VWIQFQGVITTVILSAVVSYIAY

Query ID: F3KUN4
Helix 1: AWMTISTALVIFMTIPGLALFY
Helix 2: VLMQVFVVTCLIYVLWVIY
Helix 3: LTFVAFQATFAAITCALIVGSFA
Helix 4: AVLLFCVLWFTFSYLPVAHMVWYWA
Helix 5: FAGGTVVHINAGVAGLVGAYVL
Helix 6: APHSLTLTMVGAAMLWVGWFGF
Helix 7: TALAFINTLIATAAATLSWI
Helix 8: MLGAASGAVAGLVAITPA
Helix 9: VMGALIIGLLAGLVCLWGVTGL
Helix 10: VFGVHGVGGILGALLTGVFAA
Helix 11: VWIQFQGVITTVILSAVVSYIAY

Query ID: A0A016XCG9
Helix 1: AWMTVATALVIFMTIPGLALFY
Helix 2: VLMQVFVVTSMIYVLWVIY
Helix 3: LTFIGFQATFAAITCALIVGAFA
Helix 4: AVLLFCALWFTFCYLPMAHMVWYWA
Helix 5: FAGGTVVHINAGVAGLVGAYVL
Helix 6: APHSLTLTMVGAAMLWVGWFGF
Helix 7: TALAFVNTLVATAAATLSWI
Helix 8: MLGAASGAVAGLVAITPA
Helix 9: VMGALVIGLLSGVICLWGVTGL
Helix 10: VFGVHGVGGIVGALLTGVFAAPSLG
Helix 11: AQVWIQFQGVIITVILSAVVSYIAY

Query ID: A0A4P6UIJ8
Helix 1: AWLLLCAALVIFMTPGLAFFYGGL
Helix 2: LSFGSIIVVAILYVLIGAGIA
Helix 3: FAGHAFLVAFCIITVALASGA
Helix 4: FWPWILFAALFAAFVVFPTFRWLW
Helix 5: WAGGTVIHQSAGAAAMALALVL
Helix 6: TSHNVPLVLIGTAILWFGWFGF
Helix 7: SGLIFLNTLIAPAAAALGWIIV
Helix 8: TAVGAASGIVAGLVAITPA
Helix 9: PIWAILLGLAAGAICALAVEL
Helix 10: VVGIHLVAGFIGCIWIGLFGS
Helix 11: VLSSVTVIVYSFVVTYILAFLV

Query ID: A0A016XDZ5
Helix 1: AWLLLCAALVIFMTPGLAFFYGGL
Helix 2: LSFGSIIVVAILYVLIGAGIA
Helix 3: FAGHAFLVAFCIITVALASGA
Helix 4: FWPWILFAALFAAFVVFPTFRWLW
Helix 5: WAGGTVIHQSAGAAAMALALVL
Helix 6: TSHNVPLVLIGTAVLWFGWFGF
Helix 7: TGLIFLNTLIAPAAAALGWIIV
Helix 8: TAVGAASGIVAGLVAITPA
Helix 9: PIWAILLGLVAGAVCALAVEL
Helix 10: VVGIHLVAGFIGCIWIGLFASVGGA
Helix 11: LIAQVLSSLTVIVYSFVVTYILAFLV

Query ID: A0A0D2NYP3
Helix 1: ISFVVLSMALVWIMIPGVGLFY
Helix 2: MIYTSLASIAVVTFQWFFW
Helix 3: IPAILFCVYQLMFAAITAALAV
Helix 4: LLVFIFVWTTLVYDPLACWTWN
Helix 5: FVLGGLDFAGGTPVHISSGTAALAI
Helix 6: NTTYVIIGTVFLWFGWFGF
Helix 7: AIQACIVTTLAASVGGLTWMLW
Helix 8: KWSAVGFCSGAISGLVAI
Helix 9: FVGSPAAVLFGVVGGTACNFA
Helix 10: ALDIFASHAVGGIVGNLLTGIFA
Helix 11: GVSYSFVVTTLILWVMHYI

Query ID: A0A0D2LEF5
Helix 1: LAFITVAGAMVFFMVPGLAFLY
Helix 2: LIWAVAASNAIVIFQWYFW
Helix 3: ILYSFFQMEFACVTAGILMGGL
Helix 4: LPAMIFTFCWVTVVYCPLVCWIWST
Helix 5: FAGGGPVEIGSGVAGLAYSWVLG
Helix 6: PHNVSLVGLGTFMLWFGWIGF
Helix 7: AFFAIWNTMIAAAFGGSVWCLL
Helix 8: GFCSGTIAGLVAATPSSGFL
Helix 9: VIVGILAGGICNFATKVKFLL
Helix 10: HAVGGIIGLMLNAFFASPSII
Helix 11: LYIQFAYVVATCAYTFVMTAFVAKVI

Query ID: A0A0D2KGN8
Helix 1: IAWVLASTALVWIMVPGVGFFY
Helix 2: MIYLSMMTIAVVSFQWFFWGFSLAF
Helix 3: AIVYCVYQLMFAAITPMLAI
Helix 4: MLVFVFVWSTLVYDPIACWTWNT
Helix 5: FAGGTPVHISSGTAALAISVYL
Helix 6: YVILGTIFLWFGWFGFNGGSAL
Helix 7: AAQACIVTNLAASVGGLTWMLW
Helix 8: KWSAVGFCSGAIAGLVAI
Helix 9: YVGSPAAVLFGFMAGTLCNFAT
Helix 10: LDIFASHAVGGVIGNILTALFAQA
Helix 11: YIQLAIHLADSASGLGYSFVMTTIILWI

Query ID: V5SAJ5
Helix 1: TAWMLTSTVIVLMMAIPGLALFYA
Helix 2: VAMVFAAVCVLSVTWFVIGYSIA
Helix 3: LFIVFQMTFFAITPALIVGSIV
Helix 4: SLLIFLVLWSLIVYAPICHWVWG
Helix 5: FAGGTVVHINSGVAGLVAALVL
Helix 6: APHNLVLTLIGASLLWVGWFGF
Helix 7: ASMAALVTQIAAAAGGLTWM
Helix 8: VLGVTSGAIAGLVGITPAAGFV
Helix 9: LFIGIGAGFAAFFFSTVV
Helix 10: VFGVHGIGGIVGAILTGVFA
Helix 11: IQIYGILATIIWCALATFVILIVL

Query ID: Q0BWD0
Helix 1: YLFLIGGLIVMFMAAGFCMLEAGLV
Helix 2: NVTLFSVAGLMFWITGYNLA
Helix 3: WFFQMVFVATAASIVSGTVA
Helix 4: IWPFLIFTAVLTAFIYPVV
Helix 5: AGSTLVHSTGGWAALTGAIII
Helix 6: IPLAALGTFILWFGWFGF
Helix 7: IFANTNMAAVGGVLAAMVTTAVLY
Helix 8: TLIFNGAIGGLVSITAEPLA
Helix 9: SVLIGAVGGVLVVVSVPLLD
Helix 10: VVGAIPAHLICGIWGTMIVPLT
Helix 11: YAGQAVGVALTGVFVVIISSIIWFAL

Query ID: Q5QVH2
Helix 1: LYLLISGALVMWMAAGFSMLE
Helix 2: ILTKNIVLYAIACIVYLVI
Helix 3: FFFQMVFVATAMSIVSGAVA
Helix 4: SFLLFCVVLSAVIYPVQGLWTWG
Helix 5: FAGSSIVHLTGASAALAAVLLL
Helix 6: MPLAALGTFILWFGWFGF
Helix 7: AMVNTNTSAAAGTIATLLF
Helix 8: MILNGALAGLVAITAQPV
Helix 9: LAGVIGFIAGLIVVLSIIGL
Helix 10: ISVHGVVGIFGTLVVPLS
Helix 11: FVIQLAGVGTIFCWVFFSSLIVWAIL

Query ID: E3H8C9
Helix 1: TWTLIAAAMVFFMQAGFAMV
Helix 2: FSMGILAFWAVGFAFMFG
Helix 3: WTFFIFQGVFAATAATIVSGA
Helix 4: FGSYLVSSFLITAFVYPIFGHWA
Helix 5: FAGSTVVHSVGGWAALAAAIVL
Helix 6: IPLASLGVFILWFGWFGF
Helix 7: IGLIATNTSLAAAAGSISALVI
Helix 8: MTLNGSLAGLVGITAGCA
Helix 9: ASVIIGLVAGVLVVLSVLFI
Helix 10: VSVHGVNGAWGTLAAGIFNA
Helix 11: QAIGIAAAFVVAFVGGLIIFNVV

Query ID: E3H8A6
Helix 1: IVWLGIAGAMVMFMQVGFIAL
Helix 2: FAVGAILYFSIGYAFMFGEGGF
Helix 3: IMVWFFQVMFAGAAATIVSGA
Helix 4: LSGYVVACALIAGFIYPIF
Helix 5: AGSTVIHSLGGWLALAGAIVV
Helix 6: IPLATLGTFILWFGWYGF
Helix 7: IAIVLLNTTLGGAAGALSAMIYS
Helix 8: LVDLGMTLNGALAGLVSVTAGA
Helix 9: GFSILIGLVAGILVSVSVPFF
Helix 10: VSVHGVNGAWGTIAVGLFTA
Helix 11: TQLIGSVTVFVYAFGIGMIMF

Query ID: I0WJ97
Helix 1: LVFFMHLGFSFLEIGLTR
Helix 2: LFIICIGLLLYSLVGFNLMY
Helix 3: FLFQGMFAATAATIVSGAVA
Helix 4: SFMIFTIIYVGLIYPITGSWKWG
Helix 5: FAGSTLVHSVGGWAALVAISLL
Helix 6: LPTATAGVLILWLGWFGF
Helix 7: ATSLVLVTTSIAAASGGIGAFIFSCILY
Helix 8: MFLNGILGGLVAITAGANL
Helix 9: AVLIGIVAGLLVVIGIAFV
Helix 10: AVAVHLICGIFGTLSVGIFG
Helix 11: LAGLLIIGAFCCSTAYIILYLL

Query ID: A0A211ZGL5
Helix 1: QTSTALVLMMTIPGLALFY
Helix 2: ILMQCFAITCLVSIIWMVLGYSLA
Helix 3: VFMMFQMTFAIITPALIVGAFA
Helix 4: SLLVFTTLWSIVVYSPIAHWVW
Helix 5: LFGAGVLDFAGGTVVHINAGIAGLVACIVIG
Helix 6: AFAPHNLVLSVIGASLLWVGWFGF
Helix 7: LAAGGLSGMAFAVTHIATAAAALAWM
Helix 8: VLGIISGAVAGLVAITPAS
Helix 9: MGALAIGIAAGIICYFSATSL
Helix 10: VFGVHCVGGIVGAILTGVFA
Helix 11: WIQVEGVLATLIWSGVVTAVLLFLI

Query ID: A0A952FNL7
Helix 1: WMLTSSALVLMMTIPGLALFYGG
Helix 2: VLAMLMQCFAITALVSIIWMVL
Helix 3: VFMMFQMTFAIITPALIVGAFA
Helix 4: SLLVFTALWSIIVYSPIAHWVW
Helix 5: LFSAGVLDFAGGTVVHINAGIAGLVACIVIG
Helix 6: AFAPHNLVLSVIGASLLWVGWFGF
Helix 7: AGMAFAATHIATAAAALAWM
Helix 8: VLGVISGAVAGLVAITPAS
Helix 9: MGALAIGVAAGIICYFAATSL
Helix 10: VFGVHCVGGVVGAILTGVFA
Helix 11: WIQVEGVLATLIWSGGVTLVLLFLI

Query ID: A0A0A0D6K5
Helix 1: AWMQTSTALVLMMTIPGLALFY
Helix 2: ILMQCFAITCLVSIIWMVLGYSLA
Helix 3: VFMMFQMTFAIITPALIVGAFA
Helix 4: SLLVFTTLWSIVVYSPIAHWVW
Helix 5: LFGAGVLDFAGGTVVHINAGIAGLVACIVIG
Helix 6: AFAPHNLVLSVIGASLLWVGWFGF
Helix 7: LAAGGLSGMAFAVTHIATAAAALAWM
Helix 8: VLGIISGAVAGLVAITPAS
Helix 9: MGALAIGIAAGIICYFSATSL
Helix 10: VFGVHCVGGIVGAILTGVFA
Helix 11: WIQVEGVLATLVWSGVVTAVLLFLI

Query ID: E6SF19
Helix 1: TAFMLIASAMVLLMTPGLALFY
Helix 2: MMMMSFGALGVVGVIYILW
Helix 3: AIVAGFQLTFAVITVALISGAIA
Helix 4: TWLVFAGIWATIVYFPIAHMVW
Helix 5: VVHINAGIAGLVLALIVGQRL
Helix 6: VPLVMIGAGLLWFGWFGF
Helix 7: ASVVWLNTTAATAAAIIGWLVV
Helix 8: HATSIGAASGVVAGLVAI
Helix 9: ALSPVGSLVLGVLAGAFAALAVGL
Helix 10: VVGVHLTAGLWGTIGAGLLSTSTGLFYG
Helix 11: TALQVIIALVSLLVSGVLTAIIGLAL

Query ID: F6FRU9
Helix 1: GVTAWMLTSASLVLLMTPGLALFY
Helix 2: MMMMSFGAMAVVGVIYVLW
Helix 3: VGFQATFAIITVALISGAIA
Helix 4: TWLVFAGLWATLSYFPLSHMVWG
Helix 5: FAGGTVVHINAGVAALVLALIVG
Helix 6: PHNLPLVMLGAALLWFGWFGF
Helix 7: AGLAWVNTTTATAAAILGWLV
Helix 8: LGAASGVVAGLVAITPAA
Helix 9: VGAIVIGLVAGALSALAVGL
Helix 10: VVGVHLVAGLWGTVSLGFLA
Helix 11: AQLAVQVIIAVIAIAISAVVTLVIALAL

Query ID: B7QKQ6

Helix 1: ATWVLTAAIVIFTMQTGFGLL
Helix 2: VILGGLTYWLFGFGLQY
Helix 3: FIFQLSFSTTATTIVSGAMA
Helix 4: AYCVFSLLNTIVYCIPAGWVW
Helix 5: LDFAGSGCVHLLGGASALVAAMLL
Helix 6: VLLGMFTLWWGWLVFNCGSSFG
Helix 7: AAVTTINASLGGGVVGVFYSY
Helix 8: LVGDIVNAILTALVAVTAGSGFY
Helix 9: IVVGAMGALLACWVPSAMDY
Helix 10: VGAVAVHGVGGIWGLLAVGVFI
Helix 11: GVYLLGVQALTALCITAWSVVVSYVLL

Query ID: B7Q7U2
Helix 1: MLVSTLLVLMMAAPGLALFY
Helix 2: MLSQTLLVFSLGVVLWFIYGY
Helix 3: LLFASFQATFAGLTCALVVGSLA
Helix 4: AILVFTVIWFTLAYLPICHMVWFA
Helix 5: TVVHINAGIAGLVGAWMIGPRL
Helix 6: LPLTFIGAALLWVGWFGF
Helix 7: ATLAFFNTMLAAAIGVVAWT
Helix 8: LLGACSGAIAGLVGITPAAGF
Helix 9: ALAIGLITSLACLWGVNVL
Helix 10: VFGIHGLGGIVGALLTGLF
Helix 11: LWIQLEGVLLTLVWSGVAAWIAF

Query ID: C7R314
Helix 1: MTAWMLISASLVLLMTPGLAFFY
Helix 2: MLMMSFGAMGVIGILYVLY
Helix 3: VGFQVTFAMITTALISGAIA
Helix 4: SWLVFSGLWVTLSYFPLAHMVW
Helix 5: FAGGTVVHINAGIAALILVLIIG
Helix 6: PHNLPFVMLGAALLWFGWFG
Helix 7: IAGLAWVNTTTATAAAMIGWLL
Helix 8: LGAASGVVAGLVAITPAA
Helix 9: FGAIILGLIAGVLSALAVGL
Helix 10: VVGVHLVSGLWGTVGIGFLAL
Helix 11: LLAVQVIIAVVAMAFSAAVTAVLALGI

Query ID: I3C0V3
Helix 1: IMWIMIAGILVFFMQAGFTLV
Helix 2: LAVGSLAFWFIGYTLMYGESI
Helix 3: LFFQTVFCATAATIVSGAVA
Helix 4: TYVIFSLIMTTLIYPISGHWVW
Helix 5: IDFAGSTVVHSVGGWAALVGAILV
Helix 6: MFGALGVFILWLGWFGFNA
Helix 7: FNAAGIIITTNLAAAAGAVTALAL
Helix 8: MTLNGALAGLVGITAGCAAVS
Helix 9: IIGILSGLTVVFSIEFI
Helix 10: AISVHGVCGALGTLLVGVFA
Helix 11: GIQAIGVVGIGVWALVTSFIVLFIL

Query ID: A0A7W4TJ72
Helix 1: TAWVLTSAALVLLMTPGLALFY
Helix 2: MMMMSFGAMALIGVLWVLY
Helix 3: LPAMAFVAFQSVFAIIAVALI
Helix 4: AWMVFAGVWATVVYFPVAHWVF
Helix 5: WIAGAGAIDFAGGTAIHINAGAAGLALALVLG
Helix 6: PHNLPLVMLGAGLLWFGWFGF
Helix 7: AAVAWVNTLAATCAAVLGWLL
Helix 8: LGGASGAVAGLVAITPAC
Helix 9: VTSIVVGVIAGVLCALAVGL
Helix 10: VVGVHLVGGLWGTLAVGLFA
Helix 11: LWIQFYAAVVVMVFSFVVTWVIG

Query ID: A6W7U2
Helix 1: TAWVLTSAALVLLMTPGLALFY
Helix 2: MMMMSFGAMALIGVLWVLY
Helix 3: LPAMAFVAFQSVFAIIAVALI
Helix 4: AWMVFAGVWATVVYFPVAHWVF
Helix 5: WIAGAGAIDFAGGTAIHINAGAAGLALALVLG
Helix 6: PHNLPLVMLGAGLLWFGWFGF
Helix 7: AAVAWVNTLAATCAAVLGWLL
Helix 8: LGGASGAVAGLVAITPAC
Helix 9: VTSIVVGVIAGVLCALAVGL
Helix 10: VVGVHLVGGLWGTLAVGLFA
Helix 11: LWIQFYAAVVVMVFSFVVTWVIG

Query ID: K6W5X0
Helix 1: LTSAALVMFMTPGVAFFYG
Helix 2: AVLNMMMMCFGAMATIGVLWVLY
Helix 3: IPSLAFVAFQAMFAIIATALIA
Helix 4: WLVFTAIWGTVVYFPIAHWVF
Helix 5: ALDFAGGTAIHINAGAAALALVLVIG
Helix 6: PHNLTLVMLGAAMLWFGWFGF
Helix 7: AAVAFINTLAATAAAILGWLL
Helix 8: LGAASGIVAGLVGITPAA
Helix 9: LGAIVIGAIAGACCALAVSL
Helix 10: VVGVHLVGGLVGTLLIGFLA
Helix 11: LWRQAVGAFSVLIVSFVLSYAIGWVL

Query ID: E4NAC1
Helix 1: AWLLACTALVLLMTPGLALFY
Helix 2: MIMMSFVSIAVVTVVWLLAGYSLA
Helix 3: LLFATFQLTFAIITAALISGAIA
Helix 4: SWVAFTAVWTLLVYVPVAHWVF
Helix 5: VVEVNCGASGLALALLLGPRL
Helix 6: LPLVLLGAGLLWFGWFGF
Helix 7: AAAAVLNTQAAGCAGLLGWLLV
Helix 8: HATTLGAASGAVAGLVAITPS
Helix 9: LFGALVIGLAAGLVCCYAVSW
Helix 10: VVGVHFVAGVLGTALIGLFATSVM
Helix 11: LVAVLAVACYAFGATYGIG

Query ID: E4NHH7
Helix 1: FVFICAALVMLMTPGLAFFY
Helix 2: MLVMSFISLAIVTVLWVLY
Helix 3: ALTGTIPVTGFAAFQLMFAIITPALI
Helix 4: AWSLFVALWVTIVYFPVAHWVF
Helix 5: AGGTAVHINAGAAGLALALVLG
Helix 6: PHSLPLVMLGSGLLWFGWFGF
Helix 7: LAANGVAGMAFVNTQVATAAAVLGWLAY
Helix 8: AFTTLGAASGAVAGLVAITPA
Helix 9: PLGSIAIGLIAGALCAAAISL
Helix 10: VVGVHLVGGVVGSLLIGLFATGHV
Helix 11: ALGVVVVLVYSFVLSWLLG

Query ID: E4N1T5
Helix 1: WLLASTAMVLLMTPGLAFFY
Helix 2: MIKMSFAALALGSLVWWAL
Helix 3: IPTYIFATFQMGFAVVTVALI
Helix 4: GWLVFVPLWLLLVYAPTAHWVF
Helix 5: PVELSSGAAGLAVALALRGP
Helix 6: NIPLVVIGVGLLWFGWFGF
Helix 7: AAAAFLNTQLGGAAAMVSWPLV
Helix 8: RVSTTGVVSAGVAGMVAITPA
Helix 9: PLGAVVTGLVAGAVCGWAVTL
Helix 10: VVGVHGVGGLTGLLMVGLFATA
Helix 11: QALAALAVAAFSCTLTWLLA

Query ID: A0A318FY98
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VIVTFALVCVLWVVYGYTLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYMMG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAAAILAWT
Helix 8: LLGACSGAIAGLVGVTPACGYIG
Helix 9: IVGIAAGLAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: VLVQLESIAITIVWSGIVAFIGY

Query ID: A0A6B8N021
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VIVTFGLVCVLWVVYGYTLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYMMG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAAAILAW
Helix 8: SLLGACSGAIAGLVGITPA
Helix 9: VGGSLIVGIAAGLAGLWGVTIL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: VLVQLESIAITIVWSGIVAFIGY

Query ID: A0A168EVK8
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VIVTFALVCVLWVVYGYTLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYMMG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAAAILAW
Helix 8: SLLGACSGAIAGLVGITPA
Helix 9: VGGSLIVGIAAGLAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: VLVQLESIGITIVWSGVVAFIGY

Query ID: A0A0H3H4I7
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VIVTFALVCVLWVVYGYTLAFGAGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYMMG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAAAILAW
Helix 8: SLLGACSGAIAGLVGITPA
Helix 9: VGGSLIVGIAAGLAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: VLVQLESIGITIVWSGVVAFIGY

Query ID: A0A0J2IA68
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VIVTFALVCVLWVVYGYTLAFGAGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYMMG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAAAILAW
Helix 8: SLLGACSGAIAGLVGITPA
Helix 9: VGGSLIVGIAAGLAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: VLVQLESIGITIVWSGVVAFIGY

Query ID: A0A378GLU3
Helix 1: NAFMMLCTALVLFMTIPGIALFYGGLI
Helix 2: VAVTFAVVCVLWVVYGYSLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVIWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFIGTAILYFGWFG
Helix 7: IAGLAFVNTVVATAAAILGWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALILGIVVGLAGLWGVTSL
Helix 10: VFGVHGVCGIIGCILTGIFASTALGGV
Helix 11: VLVQLESIAITIVWSGVVAFIGY

Query ID: A0A3N2SFS2
Helix 1: NAFMMLCTALVLFMTIPGIALFYGGLI
Helix 2: VAVTFAVVCVLWVVYGYSLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVIWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFIGTAILYFGWFG
Helix 7: IAGLAFVNTVVATAAAILGWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALILGIVVGLAGLWGVTSL
Helix 10: VFGVHGVCGIIGCILTGIFASTALGGV
Helix 11: VLVQLESIAITIVWSGVVAFIGY

Query ID: A0A2T2Y0D5
Helix 1: NAFMMICTALVLFMTIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLAFGTGGSFF
Helix 3: FYQYIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVIWLTLSYIPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFIGTAILYFGWFG
Helix 7: IAGLAFVNTVVATAAAILGWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALILGIIAGLAGLWGVTSL
Helix 10: VFGVHGVCGIVGCILTGIFASTALGGV
Helix 11: VLVQLESIAITIVWSGIVAYVGY

Query ID: A0A5P2U5F4
Helix 1: MAWIMVAGSFVWLMVPGIGLLY
Helix 2: LLWASIMTIAVVTFQWYWW
Helix 3: LFAWFQGMFAMVTGILMVG
Helix 4: MVFLFLFITIVYCPIACWTWNP
Helix 5: YAGGGPVHICSGHGALIYALI
Helix 6: VTSVVLGTVFTWIGWIGGF
Helix 7: AWYSAYSTNLAAACGALTWMFI
Helix 8: WTTVGLCSGAISGLVGITPA
Helix 9: LWASVIIGIVTAAGCNLAV
Helix 10: LDVYALHGVGGCIGSVLTGIFAA
Helix 11: YQLAAVCATIAWTCVVTACLLLIL

Query ID: A0A5P2U5E9
Helix 1: MVWIFIAGSFVWLMVPGIGLLY
Helix 2: LLWASIMTIAVVTFQWYWW
Helix 3: VFAWFQGMFAIATGILMVG
Helix 4: MVFLFLFITIVYCPIACWTWNP
Helix 5: YAGGGPVHICSGHGALMYALI
Helix 6: VTSVVLGTVFTWLGWIGAF
Helix 7: AWYSAYSTNLAGSCGALTWMFI
Helix 8: WTTVGLCSGAIAGLVGITPA
Helix 9: LWASVIVGIVTAAACNFAV
Helix 10: LDVYALHGVGGCIGSVLTGIFAA
Helix 11: LAAMCASVAWTSVVTACLLLIL

Query ID: Q6CRN1
Helix 1: MAWIMVAGSFVWLMVPGIGLLY
Helix 2: LLWASIMTISVVTFQWYWW
Helix 3: LFAWFQGMFAMVTGILMVG
Helix 4: MVFLFLFITIVYCPIACWTWNP
Helix 5: YAGGGPVHICSGHGALIYALI
Helix 6: VTSVVLGTVFTWIGWIGGF
Helix 7: AWYSAYSTNLAAACGALTWMFI
Helix 8: WTTVGLCSGAISGLVGITPA
Helix 9: LWASVIIGIVTAAGCNLAV
Helix 10: LDVYALHGVGGCIGSVLTGIFAA
Helix 11: YQLAAVCATIAWTCVVTACLLLIL

Query ID: Q6CRN0
Helix 1: MVWIFIAGSFVWLMVPGIGLLY
Helix 2: LLWASIMTIAVVTFQWYWW
Helix 3: VFAWFQGMFAIATGILMVG
Helix 4: MVFLFLFITIVYCPIACWTWNP
Helix 5: YAGGGPVHICSGHGALMYALI
Helix 6: VTSVVLGTVFTWLGWIGAF
Helix 7: AWYSAYSTNLAGSCGALTWMFI
Helix 8: WTTVGLCSGAIAGLVGITPA
Helix 9: LWASVIVGIVTAAGCNFAV
Helix 10: LDVYALHGVGGCIGSVLTGIFAA
Helix 11: LAAMCASVAWTCVVTACLLLIL

Query ID: A0A5P2U8K3

Helix 1: STIAFIFMGCALVFIMIPGLGFLY
Helix 2: LIWAVIMATLVGMVQWYFW
Helix 3: LAWAAFQGMFLCVTLSIIAGA
Helix 4: VFLFCFATIVYCPVTFWVW
Helix 5: VEILSAVGGFVYSAFLG
Helix 6: PHNVSMVTLGTSLLWFGWLGF
Helix 7: SVFALLNTNLSAAFGGMTWCLL
Helix 8: KWSTVGLCSGIICGLVAAT
Helix 9: ITLYASVIQGITAGVVCNF
Helix 10: GIAGVVGLIFNAFFAADWII
Helix 11: MYMQIAYIAAVTGYAAVVTAIICFVL

Query ID: Q6CVL9
Helix 1: STIAFIFMGCALVFIMVPGLGFLY
Helix 2: LIWAVIMATLVGMVQWYFW
Helix 3: LAWAAFQGMFLCVTLSIIAGA
Helix 4: VFLFCFATIVYCPVTFWVW
Helix 5: VEILSAVGGFVYSAFLG
Helix 6: PHNVSMVTLGTSLLWFGWLGF
Helix 7: SVFALLNTNLSAAFGGMTWCLL
Helix 8: KWSTVGLCSGIICGLVAAT
Helix 9: ITLYASVIQGITAGVVCNF
Helix 10: GIAGVVGLIFNAFFAADWII
Helix 11: MYMQIAYIAAVTGYAAVVTAIICFVL

Query ID: A0A5P2UBW0
query A0A5P2UBW0 has 13, using last 11 helices
Helix 1: AFQGIGPAFTLPNAIAIIA
Helix 2: IFSLFGACAPSGFVVGAVF
Helix 3: WAYWIMGITCFLLGVAGYLVI
Helix 4: VAGSVTGVVGLILFNFAW
Helix 5: YTYALLIVGTAFLAAFGFI
Helix 6: FVMGCIAAGWSSFGIWVYY
Helix 7: FVPVAISGLCAAMSTEFLL
Helix 8: TVMIIAMVAFTVGSILVATV
Helix 9: YWAQTFVSIIVMPWGMDMSFPAATII
Helix 10: LAASLVNTIINYSISIGLGFAG
Helix 11: AYYMGIGLAGLGVGVAISYAIF

Query ID: Q6CWZ4
query Q6CWZ4 has 13, using last 11 helices
Helix 1: AFQGIGPAFTLPNAIAIIA
Helix 2: IFSLFGACAPSGFVVGAVF
Helix 3: WAYWIMGITCFLLGVAGYLVI
Helix 4: VAGSVTGVVGLILFNFAW
Helix 5: YTYALLIVGSAFLAAFGFI
Helix 6: FVMGCIAAGWSSFGIWVYY
Helix 7: FVPVAISGLCAAMSTEFLL
Helix 8: TVMIIAMIAFTVGSILVATV
Helix 9: YWAQTFVSIIVMPWGMDMSFPAATII
Helix 10: LAASLVNTIINYSISIGLGFAG
Helix 11: AYYMGIGLAGLGLGVAISYAIF

Query ID: A0A0B4EV76
Helix 1: GHVWMVVAAGLVFFMTPGLALFY
Helix 2: MMMMSFAALGVVGVVWVLW
Helix 3: LLASDFSVTFAIITVALISGAIA
Helix 4: TWVVFTLVWVTLVYFPLAYMVWG
Helix 5: FAGGLAVHINAGIAALVLILLIGA
Helix 6: PHNLPLVMLGSAILWFGWFGF
Helix 7: ALIWTNTLVAPAAAMLSWLL
Helix 8: LGAASGVVAGLVAITPACA
Helix 9: GAIGLSAVAGVLSALAVGF
Helix 10: VCGVHLVSGIVGTVALGFLAV
Helix 11: QLAATGFVALYTGVLTLLIGLVL

Query ID: A0A101Y6H3
Helix 1: WMVVAAGLVFFMTPGLALFY
Helix 2: MMMMSFAALGVVGVVWVLW
Helix 3: LLASDFSVTFAIITVALISGAIA
Helix 4: TWVVFTLVWVTLVYFPLAYMVWG
Helix 5: FAGGLAVHINAGVAALVLILLIGA
Helix 6: PHNLPLVMLGSAILWFGWFGF
Helix 7: ALIWTNTLVAPAAAMLSWLL
Helix 8: LGAASGVVAGLVAITPACA
Helix 9: GAVALSAVAGVLSALAVGF
Helix 10: VCGVHLVSGIVGTVALGFLAI
Helix 11: QLAATAFVALYTGVLTLLIGLAL

Query ID: A0A2I1P2U4
Helix 1: WMVVAAGLVFFMTPGLALFY
Helix 2: MMMMSFAALGVVGVVWVLW
Helix 3: LLASDFSVTFAIITVALISGAIA
Helix 4: TWVVFTLVWVTLVYFPLAYMVWG
Helix 5: FAGGLAVHINAGVAALVLILLIGA
Helix 6: PHNLPLVMLGSAILWFGWFGF
Helix 7: ALVWTNTLVAPAAAMLSWLL
Helix 8: LGAASGVVAGLVAITPACA
Helix 9: GAIGLSAVAGVLSALAVGF
Helix 10: VCGVHLVSGIVGTVALGFLAV
Helix 11: QLAATVFVALYTGVLTLLIGLVL

Query ID: B2GFN1
Helix 1: WMVVAAGLVFFMTPGLALFY
Helix 2: MMMMSFAALGVVSIVWVLW
Helix 3: LGSNFSVTFAIITVALISGAIA
Helix 4: TWVVFTLVWVTLVYFPLAYMVWG
Helix 5: FAGGLAVHINAGVAALVLILLIGA
Helix 6: PHNLPLVMLGSAILWFGWFGF
Helix 7: ALIWANTLVAPAAAMLAWLL
Helix 8: LGAASGVVAGLVAITPACA
Helix 9: GAIALSAVAGVCSALAVGL
Helix 10: VCGVHLVSGIVGTVALGFLAI
Helix 11: QLAATAFVALYTGLLTLVIALAL

Query ID: A0A9E1C4G3
Helix 1: WTVVAAGLVFFMTPGLALFY
Helix 2: MMMMSFAALGVVGVVWVLW
Helix 3: FSVTFAIITVALISGAIA
Helix 4: TWVVFTLVWVTLVYFPLAYMVWG
Helix 5: FAGGLAVHINAGIAALVLILLIGA
Helix 6: PHNLPLVMLGSAILWFGWFGF
Helix 7: ALIWTNTLVAPAAAMLAWLL
Helix 8: LGAASGVVAGLVAITPACA
Helix 9: GAILLSAVAGACSAIAVGL
Helix 10: VCGVHLVSGIVGTVALGFLAI
Helix 11: QLAATLFVTLYTGVLTLVIGLVL

Query ID: A9DQM8
Helix 1: MLWMLLSGILVFFMQAGFTLV
Helix 2: ICVGSLTYWLVGYSLMYG
Helix 3: LFFQTMFAATAATIVSGAIA
Helix 4: YSTYIIFSLVMTAVIYPI
Helix 5: FAGSSIVHSVGGWAALVAAILV
Helix 6: IMATLGVFILWLGWFGF
Helix 7: VLITNISAAAGGLGALITTWIWY
Helix 8: QTLNGALAGLVSITAGCG
Helix 9: GAFLAGLIGGVLVVFSIEFI
Helix 10: AVSVHGVVGAWGTIVIGLWGI
Helix 11: QAIGVLAYAVWAIVLSFIVLFTL

Query ID: A0A165BP25
Helix 1: ISTALVLFMSIPGIALFYGGLI
Helix 2: VAVTFALVCVLWVVYGYSLA
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAGLAFVNTVVATAGAILAWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALIVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCILTGIFAATSLGGV
Helix 11: LLVQLESIALTIVWSGVVAFIGY

Query ID: C5CIT6
Helix 1: MLVATSLVMLMTPGLAFFYGGL
Helix 2: TILWVTVGFTMCFGGDIGGIIG
Helix 3: MGIPMLVFVAYQMMFAIITPALI
Helix 4: AYMIFLTVWLLFVYFPLVHMVWG
Helix 5: FAGGIVVHASAGFAALASVFFV
Helix 6: SIPLVALGTALLWFGWYGF
Helix 7: TVSAFLNTDVAASFAAITWLILAVI
Helix 8: VLGMLTGAVAGLATITPAAGYV
Helix 9: MLIGIIASLIGYAAIAY
Helix 10: VWGVHGMGGYVGILLLGLFASTNI
Helix 11: FVAVTVTAVYAFVFTYVALWLI

Query ID: A0A1D8UWJ6
Helix 1: TAWMLTSTALVLMMTIPGLALFYA
Helix 2: LIQSFAICCIASIVWMVAGYSLA
Helix 3: VYMMFQMTFAIITPALIAGSFA
Helix 4: ALCVFTILWSLLVYAPVAHWVW
Helix 5: VDFAGGTVVHINSGIAGLITALVIG
Helix 6: PFNLTYAIIGASLLWVGWFGF
Helix 7: AGMAMLTTQIAAAVGGMAWM
Helix 8: ALGIISGAVAGLVAITPAAGF
Helix 9: ALIIGLIAGIVCFWASAIL
Helix 10: AFGVHGTGGIIGALLTGVFAY
Helix 11: FLRQAEAVCVTIVWCVIITFLIL

Query ID: D2Q0J8
Helix 1: AWVLVSAALVFLMTPGLAFFY
Helix 2: MMMMSAITIAVVTVLWVVVGYSL
Helix 3: LAFVAFQLMFAIITPALISGAIA
Helix 4: GWIVFVALWTSLVYFPVAHAVW
Helix 5: FAGGTAVHVNAGAAALALAIVLG
Helix 6: PHSLPLVVLGAGLLWFGWFGF
Helix 7: AAVTFVNTQVATAAAVIGWLI
Helix 8: LGMASGAVAGLVAITPAC
Helix 9: VGALILGVVAGGICAFAVSL
Helix 10: VVGVHLVGGLVGSLAIGFLGSAAA
Helix 11: ALANLIVGVYSFVVAFVLAKLI

Query ID: D6TFE1
query D6TFE1 has 12, using last 11 helices
Helix 1: VWVLVAAFLVFGMQVGFVMLEAGFA
Helix 2: GIADTCICGILFWAWGFAFMF
Helix 3: TYLSTGVPLLAFWVFQFAFA
Helix 4: ILYSIGVTGFIYPIIGHWAW
Helix 5: VHSIGGAISLAGAIALGPRLG
Helix 6: APHDLIIGAVGGLILWFGW
Helix 7: VAFNTTLAACSGGLVALFYSYA
Helix 8: LGLTVNGFLGGLVAITCPCYW
Helix 9: AFFIGAIAALVVAWSIDAL
Helix 10: VPVHLAAGIWGTLSLGLFASGAYGL
Helix 11: AIGSGAVVAATMVVSLALMFAL

Query ID: D6TCH6
Helix 1: AWVLLSAALVMLMTPAVGFFYGGMVT
Helix 2: LLILGLVSIQWVLIGYSLV
Helix 3: LAFMVFQAMFAIITPALIIGSFV
Helix 4: TLVLFVVLWSTLVYDPIAHWVWGI
Helix 5: FAGGTVVHISAGFAGLAAAIVI
Helix 6: LAANNVPFVLLGAALLWFGWFGF
Helix 7: AVNAFVVTNTAAAACALTWMVLSWA
Helix 8: AMATATGAVCGLVAITPAS
Helix 9: MASLAIGVITGVVTYLMLML
Helix 10: DVWAAHGMGGVTGAILTGIFA
Helix 11: LLTQILATVVTVVYSFGLTFLLL

Query ID: W5WIX6
Helix 1: TAWVLVSAALVMLMTPGLAFFYG
Helix 2: LMMNFIALGVVTVLWLLYGYSIA
Helix 3: VLAFAMFQLMFAVITPALISGA
Helix 4: FWGWVTFLVVWVSIVYFPVAHWVF
Helix 5: ALDFAGGTAVHINAGAAGLALALVLG
Helix 6: PHNVPFVLLGASLLWFGWYGF
Helix 7: AAVAFTTTTVATAAAVLGWLV
Helix 8: LGAASGAVAGLVAITPACAFVS
Helix 9: AIGLIAGVLCALAVGLKF
Helix 10: GVHLVGGIVGTLLIGLFGTTSV
Helix 11: QAIGAFSVLAYSFVVSFVLGWII

Query ID: B0DY50
Helix 1: IAWVLASTALVWIMMPGVGFFY
Helix 2: MIYLSMMTSAVVSFQWVFW
Helix 3: IPSIVFCVYQLMFAAFTPMIAV
Helix 4: LMVFVFVWATIVYDPIACWTWN
Helix 5: HISSGTAALAISIYLGQRHGY
Helix 6: TTYVVLGTVFLWFGWFGF
Helix 7: AAQACLSTNVAASVGGLTWMLW
Helix 8: KWSVVGFCSGAIAGLVAI
Helix 9: FVGSPAAILFGVTAGTVCNFA
Helix 10: ALDIFASHAVGGLVGNILTALFAQA
Helix 11: YAQLAIHLADSAAGMSYSFVMTTLILWV

Query ID: B0DU91
Helix 1: LSFIIISGAMVSFMIPGLAFLY
Helix 2: LIWAVSASNAVVVFQWFLW
Helix 3: ILYSFFQMEFACVTAGILV
Helix 4: AMVFIFIWMTLVYCPLVCWVWSA
Helix 5: FAGGGPVEIGSGMGGLAYSWVLG
Helix 6: PHNVSLVGLGTSLLWFGWIGF
Helix 7: AIFAVWNSMIAAAFGGIVWCLL
Helix 8: RWSMVGLCSGTIAGLVAAT
Helix 9: LHPWASVIVGVVSGVLCNFA
Helix 10: AIGGIIGLLFNSFFASSTIMA
Helix 11: FAYICATSAYTFVFTALIA

Query ID: B0DXT9
Helix 1: LSFIIISGAMVSFMIPGLAFLY
Helix 2: LIWAVSASNAVVVFQWFLW
Helix 3: ILYSFFQMEFACVTAGILV
Helix 4: AMVFIFIWMTLVYCPLVCWVWSA
Helix 5: FAGGGPVEIGSGMGGLAYSWVLG
Helix 6: PHNVSLVGLGTSLLWFGWIGF
Helix 7: AIFAVWNSMIAAAFGGIVWCLL
Helix 8: RWSMVGLCSGTIAGLVAAT
Helix 9: LHPWASVIVGVVSGVLCNFA
Helix 10: AIGGIIGLLFNSFFASSTIMA
Helix 11: FAYICATSAYTFVFTALIA

Query ID: B0CQX4
Helix 1: LSFIIIAGAMVSFMIPGLAFLY
Helix 2: LIWAVSASNAVVIFQWYFW
Helix 3: ILYAFFQMEFACVTASILMGGL
Helix 4: FPAMVFTFIWMTLVYCPLVCWIWST
Helix 5: FAGGGPVEIGSGIGGLAYSWVLG
Helix 6: PHNVSLVGLGTSMLWFGWIGF
Helix 7: AIFAIWNTMIAAAFGAMVWCLL
Helix 8: RWSMVGLCSGTIAGLVAAT
Helix 9: LRPWSSVIVGILSGAFCNFA
Helix 10: ALDLFAEHAVGGMIGLILNAFF
Helix 11: FAYVCATSAYTFTLTAMIAKAI

Query ID: B0DU93
Helix 1: IIISGAMVSFMIPGLAFLY
Helix 2: LIWAVSASNAVVVFQWFLW
Helix 3: ILYSFFQMEFACVTAGILV
Helix 4: AMVFIFIWMTLVYCPLVCWVWSA
Helix 5: FAGGGPVEIGSGMGGLAYSWVLG
Helix 6: PHNVSLVGLGTSLLWFGWIGF
Helix 7: AIFAVWNSMIAAAFGGIVWCLL
Helix 8: RWSMVGLCSGTIAGLVAAT
Helix 9: LHPWASVIVGVVSGVLCNFA
Helix 10: AIGGIIGLLFNSFFASSTIMA
Helix 11: FAYICATSAYTFVFTALIA

Query ID: B0CXH8
Helix 1: IAWVLASTALVWIMIPGVGYFYA
Helix 2: IYLSMVTLAVVSFQWFFWGF
Helix 3: IPSIVFCVYQLMFAAITPMIAV
Helix 4: GALGPIMVFVFIWSTIVY
Helix 5: GWVFVLGGLDFAGGTPVHISSGTAALAI
Helix 6: NTSYVVIGTIFLWFGWFGF
Helix 7: AAQACIVTNLAASVGGLTWMLW
Helix 8: KWSAVGFCSGAIAGLVAI
Helix 9: FVGSPAAVLFGVAAGTVCNFAT
Helix 10: LDVFASHAIGGVVGNILTALFA
Helix 11: GIAYSFVVTTIILWVMHYI

Query ID: B0DFJ4

Helix 1: IGFVIAATALVWIMIPGVGFFY
Helix 2: MIWTSLVSIGIVSFQWFFW
Helix 3: IPSILFCIYQLMFAAITAALAV
Helix 4: IMVFIFIWTTIVYDPIACWTWN
Helix 5: FVLGGLDFAGGTPVHISSGMAGLAI
Helix 6: NVTYVVIGTILLWFGWFGF
Helix 7: AIQACIVTNLAASVGGMTWMFW
Helix 8: KWSAVGFCSGAIAGLVAI
Helix 9: FVGSPAAVVFGVLGGTACNFAT
Helix 10: LDIFASHAVGGIVGNILTAFFA
Helix 11: GASYSFVVTTIILWVLHFI

Query ID: A0A1H3HZ52
Helix 1: FAVWFLCGAALVFWMQAGFAMV
Helix 2: FCIGTVVFIIIGFSLLLG
Helix 3: TFSFSNFVFNLVFCATTATIVS
Helix 4: YCIYSALISAIVYPIEAHWIWG
Helix 5: FAGSCAIHMVGGISALIGAAMLGA
Helix 6: GHNLPLGALGVFILWFGWYGF
Helix 7: GSIFLTTTVAPAVATVVCMLFTWF
Helix 8: VSMSLNASLAGLVAITAGC
Helix 9: LGAIVIGAVAGVLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFA
Helix 11: LLGVLSVGTWTAITITGVYVLI

Query ID: A0A1H5WFC4
Helix 1: VFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFIVIGFGLFLGEDAL
Helix 3: WSGFVFNLVFCATTATIVSGA
Helix 4: FISYCAYSAVISGIIYPI
Helix 5: AGSNCIHMVGGIGALIGAWILGARI
Helix 6: NIPLGALGVFILWFGWYGF
Helix 7: GHIFVTTTIAPAVATVTTMIFTWI
Helix 8: VSMCLNASLAGLVAITAG
Helix 9: ALGAIIIGAVAGLLVVFAVWLL
Helix 10: AVAVHMCNGIWGTIAVGLF
Helix 11: LGIQFIGMFATIAWATVSLFIAF

Query ID: Q5FLR6
Helix 1: NTLFVFVASVLVFFMTPGLAFFY
Helix 2: TMISVFMITGVAIVLFIAFGY
Helix 3: ILTYLMFQMMFSIITPALFVGAIV
Helix 4: FLVAFVVIWSILIYYPMVHMVW
Helix 5: VHINAGITALLLSIFVGPRLG
Helix 6: LPWVLMGTSILWIGWYGF
Helix 7: ATQAFLTTTVATGTSFVVWMF
Helix 8: IGLCTGALCGLVGITPAAGY
Helix 9: AFAIGFICTLASYGFIHVV
Helix 10: AFGCHGISGIAGSILTGAFAT
Helix 11: ISAQVLGTVFTIVFVGVMTTAIVLPL

Query ID: A0A809KDP7
Helix 1: NTLFVFVASVLVFFMTPGLAFFY
Helix 2: TMISVFMITGVAIVLFIAFGY
Helix 3: ILTYLMFQMMFSIITPALFVGAIV
Helix 4: FLVAFVVIWSILIYYPMVHMVW
Helix 5: VHINAGITALLLSIFVGPRLG
Helix 6: LPWVLMGTSILWIGWYGF
Helix 7: ATQAFLTTTVATGTSFVVWMF
Helix 8: IGLCTGALCGLVGITPAAGY
Helix 9: AFAIGFICTLASYGFIHVV
Helix 10: AFGCHGISGIAGSILTGAFAT
Helix 11: ISAQVLGTVFTIVFVGVMTTAIVLPL

Query ID: A0A0U2KG74
Helix 1: TVFLIIAAVLVLMMTPGLAFFY
Helix 2: TMISVFIICALAIVLFVAFGY
Helix 3: AASYLLFEMMFAIITPALFVGA
Helix 4: FNFLLVFVFFWSVLVYYPL
Helix 5: AGGTVVHINAGITALVLSIFL
Helix 6: SLPWVLLGTAILWLGWYGF
Helix 7: ALTACLTSTVAAAASMMTWLLL
Helix 8: GICTGTLCGLVGITPGAGY
Helix 9: ALFTGILCSLASYFFISQV
Helix 10: AFGCHGISGIVGSLTVGLFA
Helix 11: AAGTLFTIVFTLLMVSLITAVL

Query ID: C1D4X0
Helix 1: AWMLVSTALVLLMTIPGLALFY
Helix 2: TLMQSFAICSVVTVLWFMF
Helix 3: VFVVFQMTFAIITPALIAGAFA
Helix 4: AMLVFMVLWMFAVYVPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRV
Helix 6: LVLTMVGASMLWVGWFGF
Helix 7: AGMAMLVTQIAAGTAAVSWML
Helix 8: LGIVSGAVAGLVAITPAAGF
Helix 9: ALLLGAVAGIVCYWGATGL
Helix 10: AFGVHGVGGIIGAILTGPLAVVAIG
Helix 11: IVTQSVAVAATVGYTLVVTFVLL

Query ID: A0A248LMH8
Helix 1: AWMLVSTALVLLMTIPGLALFY
Helix 2: TLMQSFAICSVVTVLWFMF
Helix 3: VFVVFQMTFAIITPALIAGAFA
Helix 4: AMLVFMVLWMFAVYVPVAHWVW
Helix 5: VHINAGVAGLVCALVLGKRV
Helix 6: LVLTMVGASMLWVGWFGF
Helix 7: AGMAMLVTQIAAGTAAVSWML
Helix 8: LGIVSGAVAGLVAITPAAGF
Helix 9: ALLLGAVAGMVCYWGATGL
Helix 10: AFGVHGVGGIVGAILTGPLAVVAIG
Helix 11: IVTQSVAVAATVGYTLVVTFVLL

Query ID: A0A248LNK5
Helix 1: TAFIILCTALVALMTPGLALFY
Helix 2: IMMQNFISMGIVTLVWVLGGFSLA
Helix 3: FIMVFAYQMMFAIITPALITGAFAG
Helix 4: YLWFIALWTLVVYIPVAHWIWG
Helix 5: FAGGIVVHTTAGFAALATAIFLG
Helix 6: PANIPLVAVGTGLLWFGWFGF
Helix 7: AAYAFVNTAIAGGIAMVVWLFWSAI
Helix 8: FSGVMVGGVAGLATITPTA
Helix 9: WAAIIVGALGATICYFAKGI
Helix 10: VFRAHGIGGITGSLLVGFFA
Helix 11: FIQLLGVAVVAVYSFVVTWILMMVL

Query ID: A0A248LNW8
Helix 1: VLFLLLGAIMILAMHAGFAFL
Helix 2: FAVSAVAYFTVGYTLAYGVSFWAP
Helix 3: LVRFFFLLTFAAAIPAIISGGI
Helix 4: ATFLLVGLVYPLIEGLAWN
Helix 5: FAGSVVVHASGGWMALAAVLLL
Helix 6: IPFLALGAWILIVGWFGFNVMS
Helix 7: AISGLVAMNSLMAMVGGTLAAQWL
Helix 8: FIHNGPLAGLVAVCAGSDV
Helix 9: ALVVGAVAGALFVQLFTLT
Helix 10: VWPLHGLCGVWGGLACGIFGQTAL
Helix 11: LAGTLGLVTLAFAGGLAVYGLL

Query ID: C1D6X6
Helix 1: TAFIILCTALVALMTPGLALFY
Helix 2: IMMQNFISMGIVTLVWVLGGFSLA
Helix 3: FIMVFAYQMMFAIITPALITGAFAG
Helix 4: YLWFIALWTLVVYIPVAHWIWG
Helix 5: FAGGIVVHTTAGFAALATAIFLG
Helix 6: PANIPLVAVGTGLLWFGWFGF
Helix 7: AAYAFVNTAIAGGIAMVVWLFWSAI
Helix 8: FSGVMVGGVAGLATITPTA
Helix 9: WAAIIVGALGATICYFAKGI
Helix 10: VFRAHGIGGITGSLLVGFFA
Helix 11: FIQLLGVAVVAVYSFVVTWILMMVL

Query ID: E4RTK5
query E4RTK5 has 12, using last 11 helices
Helix 1: WVLISAALVLIMTPGLAYFYG
Helix 2: MLQSFIAMGVISVVWVVLGFSIAF
Helix 3: AWGTIPFLLFAFFQLKFAVITPALV
Helix 4: AYVVFMVLFSLLIYAPLAHMTW
Helix 5: LDFAGGTVVHMSAGWAALAGAIYL
Helix 6: LPPANVPYVLLGTGLLWFGWFGF
Helix 7: AVVAFATTNTAAGAAGVAWVF
Helix 8: LGFCIGVVVGLVAITPAAGF
Helix 9: ALVIGVVSSIISNLVAHW
Helix 10: VFPCHGVGGMVGMILTGVFAT
Helix 11: FLKHLLALVLTSAFAFGMSFVVL

Query ID: A0A855EH99
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVTVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPVAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWI
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALIIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGFFA
Helix 11: LVQLESIAITVVWSGVVAFIGY

Query ID: A0A514VEB8
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVTVTFALVCVLWVVY
Helix 3: YIHVAFQGSFACITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPVAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWI
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALIIGIVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIIGCIMTGFFA
Helix 11: LVQLESIAITVVWSGVVAFIGY

Query ID: A3XNG6
Helix 1: ILWIIIAAILVFFMQAGFTLV
Helix 2: LAVGSVMFWVVGYSIMYGGETILG
Helix 3: LFFQTVFCATAATIVSGAVAG
Helix 4: YLIISAILTTFIYPVSGSWLW
Helix 5: GFIDFAGSTIVHAVGGFAALVAAKLV
Helix 6: LLLGALGVFILWLGWFGF
Helix 7: IINTNLAAALGAITALFFTWG
Helix 8: ISMTLNGALAGLVGITAG
Helix 9: AFGAAAIGLISGFVVVLSIEFI
Helix 10: AISVHGVCGFLGTVLVGVFA
Helix 11: GSLSMIAWALVATFIVLFIV

Query ID: A0A1E2SKM1
Helix 1: LLLLVFGALTLLAVPSLGFLS
Helix 2: AVLFGLTGTAVVVLLGVAGGFGMVTGRAL
Helix 3: VYGLARAGSALALCAVATSLLGVAVA
Helix 4: AWLLFAVLWSALVLAPVGYGAL
Helix 5: WAVAGLGAINFGGALLVLAAGASAAGVLLAC
Helix 6: HLRLVAIGGALLLAGWFGL
Helix 7: TALIVVNSFLAAAGGCLMWLL
Helix 8: ASAFCGALSGLVAVTAGSGVL
Helix 9: LLLGALAALACATMVDLAA
Helix 10: AMTVIVIATVASLVGLLFPGLF
Helix 11: VAGLSVLIGVFLVSAGLALVL

Query ID: Q6AFC6
Helix 1: LLLLVFGALTLLAVPSLGFLS
Helix 2: AVLFGLTGTAVVVLLGVAGGFGMVTGRAL
Helix 3: VYGLARAGSALALCAVATSLLGVAVA
Helix 4: AWLLFAVLWSALVLAPVGYGAL
Helix 5: WAVAGLGAINFGGALLVLAAGASAAGVLLAC
Helix 6: HLRLVAIGGALLLAGWFGL
Helix 7: TALIVVNSFLAAAGGCLMWLL
Helix 8: ASAFCGALSGLVAVTAGSGVL
Helix 9: LLLGALAALACATMVDLAA
Helix 10: AMTVIVIATVASLVGLLFPGLF
Helix 11: VAGLSVLIGVFLVSAGLALVL

Query ID: U3P8G1
Helix 1: LWLLVAAALVLLMTPGVAFFY
Helix 2: MMMMSVGAMAIVGVLWVVY
Helix 3: LSGLAFAGFQATFAIITVALI
Helix 4: AWMVFAAIWVTVVYFPVAFWVF
Helix 5: TAVHINAGAAGLALALVLG
Helix 6: PHNVPLTLLGAALLWFGWFGF
Helix 7: AALAWINTLAAPAAATIGWLV
Helix 8: IGAASGAVAGLVAITPAC
Helix 9: FWAILLGLVAGAVCAIAVDL
Helix 10: VVGIHLIGGLIGTLWIGFFGFTHV
Helix 11: LGAQAIGAFAVLIYSFVLAFAIGAVI

Query ID: U3PCH5
Helix 1: LLVVFGTLTLLAVPGLGFLS
Helix 2: AVLFALAGTAVVVLLGVAGGSGTLTGQAL
Helix 3: VYGLARAGSALALCAVAISVLGVAVA
Helix 4: AWLLFAVLWSALVLGPVGYGVM
Helix 5: WAVAGLGAIDFGGALLVLAAGASASGVLLAC
Helix 6: NLRLVAIGGALLLAGWLGL
Helix 7: TALIVVNSFLASAGGCLMWLL
Helix 8: ASAFCGAFSGLAAITAGSGVL
Helix 9: LLLGALSALACATMVDVAA
Helix 10: AMTVIVIATVASLVGLLFPGLF
Helix 11: VAGLSVLIGAFLVSAALALAL

Query ID: A0A1A9F8V6
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFAAITVGLIVGALA
Helix 4: AVLIFVVVWMTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFMGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWI
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALLVGLVSGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFA
Helix 11: LVQLESIGITLVWSGVVAFIAY

Query ID: A0A3S5XY87
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: MLTQVAVTFALVCVLWVVY
Helix 3: YIHVAFQGSFAAITVGLIVGALA
Helix 4: AVLIFVVVWLTLSYVPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLIG
Helix 6: PHNLPMVFTGTAILYFGWFG
Helix 7: IAALAFVNTVVATAGAILSWV
Helix 8: LLGACSGAIAGLVGITPA
Helix 9: VGGALIVGLVAGLAGLWGVTAL
Helix 10: VFGVHGVCGIVGCIMTGIFA
Helix 11: LVQLESIGVTIVWSGVVAFIAY

Query ID: A0A085HMI3
Helix 1: AFMMISTAMVLFMSIPGIALFY
Helix 2: LLTQVIATFSLVSVLWVVY
Helix 3: LIHVAFQGSFACITVGLIVGGFA
Helix 4: AVLLFVLIWFTLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAIAALVGAYMLG
Helix 6: PHSLPMVFVGTAILYIGWFG
Helix 7: IAALAFINTVIATAGAVLGWL
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALVLGVVAGIAGLWGVVVL
Helix 10: VFGVHGVCGIVGCIGTGIL
Helix 11: VGVQAASVVVCLLWSGIVALVAY

Query ID: A6DN47
Helix 1: VFMMMAAVLVFIMHLGFCCLEV
Helix 2: IFKNFTIVAIATLVYGLMGFNIMY
Helix 3: FLFQAMFAAATASIVSGAVC
Helix 4: SFLIFCTVFAGIIYPIIGSWGWG
Helix 5: LAGSGLVHATGGAGALAGAIVLG
Helix 6: FAIMGHNMPVAAIGAFLLWFGWFGF
Helix 7: AASGIMVMTLLASTAGVVGAMILSWI
Helix 8: LSMVLNGALAGLVGITAGAA
Helix 9: SAVIIGAIAGVLVVLAVLLL
Helix 10: IPVHLVCGAWGVIATGIFS
Helix 11: MVQIKSILCIVAFAFVCAFILFTII

Query ID: A6DUG4

Helix 1: VFMMMAAVLVFIMHLGFCCLEV
Helix 2: IFKNFTIVAIATLVYGLMGFNIMY
Helix 3: FLFQAMFAAATASIVSGAVC
Helix 4: SFLIFCTVFAGIIYPIIGSWGWG
Helix 5: LAGSGLVHATGGAGALAGAIVLG
Helix 6: FAIMGHNMPIAAIGAFLLWFGWFGF
Helix 7: AASGIMVMTLLASTAGVVSAMILSWI
Helix 8: LSMVLNGALAGLVGITAGAA
Helix 9: SAVIIGAIAGILVVLAVLLL
Helix 10: IPVHLVCGAWGVIATGIFS
Helix 11: MVQIKSIICIVAFAFVCAFILFTII

Query ID: A0A833LX85
Helix 1: VWVLIAGILVFWMNAGFALVE
Helix 2: ILAKNFVVFGIATLSFWIIGWGLM
Helix 3: FFFQLVFAGTAATIVSGAVA
Helix 4: SFLIFSFILVAVIYPISGHWIWG
Helix 5: FAGSTVVHSVGGWAALAGILFL
Helix 6: MTSASLGAIILWMGWFGFN
Helix 7: AIAYVMVITNIAAMTGAIAAMITAWILV
Helix 8: MLINGLLAGLVAITAPCAFVT
Helix 9: IIGAIGGVLVVFLTLLL
Helix 10: IPVHLGNGIWGTLALGLFYN
Helix 11: TLVQLKGIAVVAVYVFAASAIVWAIL

Query ID: A0A833H2R7
Helix 1: WLWTMIASFLVFFMQAGFALV
Helix 2: ACLGLFGFYLIGFTLMFGLPML
Helix 3: AGAFTFFFFQSVFCATAATIVS
Helix 4: YLVYSFLVSALIYPVFGSLAW
Helix 5: FAGSTVVHSIGGWIALAGTIVL
Helix 6: LTVSTLGVFILWIGWFGF
Helix 7: NFAIIAMTTQFAAAAGAIGAMLTSWLIF
Helix 8: MILNGVLAGLVAITAGCANLN
Helix 9: LLGFVAGVVVVIAVVFFDAI
Helix 10: GAVSVHGVCGALGTLSVGLLA
Helix 11: LGVQALGVGLAFLWAFGTGLLLFFLL

Query ID: A0A833GZR2
Helix 1: ADILWILISAGLVLLMQAGFLAI
Helix 2: FGVAAIFFWVAGFALMFGTSVAGVF
Helix 3: FVFQLAFAGTSATIVSGAVA
Helix 4: AYIITTALISCVIYPLAGHWAW
Helix 5: FAGSTIVHSVGGWVSLAALLV
Helix 6: NLPMAMLGGIILWVGWVGF
Helix 7: IAGIIANTVLALGAGLVTSLLL
Helix 8: APLNGSLAGLVAVTAGAHAL
Helix 9: LFVGAVAGLLVMPTISLL
Helix 10: VPVHLISGIWGTLAVGLFGDAA
Helix 11: IGVQLTGIVAIGIWAFGFSYLLL

Query ID: H2CLF7
Helix 1: VWVLIAGILVFWMNAGFALVE
Helix 2: ILAKNFVVFGIATLSFWIIGWGLM
Helix 3: FFFQLVFAGTAATIVSGAVA
Helix 4: SFLIFSFILVAVIYPISGHWIWG
Helix 5: FAGSTVVHSVGGWAALAGILFL
Helix 6: MTSASLGAIILWMGWFGFN
Helix 7: AIAYVMVITNIAAMTGAITAMITAWILV
Helix 8: MLINGLLAGLVAITAPCAFVT
Helix 9: IIGAIGGVLVVFLTLLL
Helix 10: IPVHLGNGIWGTLALGLFYN
Helix 11: TLVQLKGIAVVAVYVFAASAIVWAIL

Query ID: H2CJI0
Helix 1: ADILWILISAGLVLLMQAGFLAI
Helix 2: FGVAAIFFWVAGFALMFGTSVAGLF
Helix 3: FVFQLAFAGTSATIVSGAVA
Helix 4: AYIITTALISCVIYPLAGHWAW
Helix 5: FAGSTIVHSVGGWVSLAALLV
Helix 6: NLPMAMLGGIILWVGWVGF
Helix 7: IAGIIANTVLALGAGLVTSLLL
Helix 8: APLNGSLAGLVAVTAGAHAL
Helix 9: LFVGAVAGLLVMPTISLL
Helix 10: VPVHLISGIWGTLAVGLFGDAA
Helix 11: IAVQLTGIVAIGVWAFGFSYLLL

Query ID: H2CDR5
Helix 1: WLWTMIASFLVFFMQAGFALV
Helix 2: ACLGLFGFYLIGFTLMFGLPML
Helix 3: AGAFTFFFFQSVFCATAATIVS
Helix 4: YLVYSFLVSALIYPVFGSLAW
Helix 5: FAGSTVVHSIGGWIALAGTIVL
Helix 6: LTVSTLGVFILWIGWFGF
Helix 7: NFAIIAMTTQFAAAAGAIGAMLTSWLIF
Helix 8: MILNGVLAGLVAITAGCANLN
Helix 9: LLGFVAGVVVVIAVVFFDAI
Helix 10: GAVSVHGVCGALGTFAVGLLA
Helix 11: LGVQALGVGLAFLWAFGTGLLLFFLL

Query ID: B0SLB7
Helix 1: TWMLVSSALVFFMIPGLSLFYGGIV
Helix 2: SFVAMIVMTLQWTIFGYSFA
Helix 3: YVHFLFQGMFALITPALISGAIA
Helix 4: AYILFILVWSTLVYDPVAHWVW
Helix 5: LDFAGGTVVHLISGIAGLSAAIVIG
Helix 6: PNNMTYTLLGSGLLWFGWFGF
Helix 7: AARAFLVTLIAPAAAGASWLL
Helix 8: LGAASGIVAGLVVITPASGF
Helix 9: ALIMGVLVSPVCYLAILL
Helix 10: AFGIHGAGGALGAILTGIFAL
Helix 11: MIAQLISVIATGFYSFVVSYILALII

Query ID: B0SL05
Helix 1: LWVLVAGMLVFFMNAGFALVE
Helix 2: ILAKNFIVFAAATFSYWAI
Helix 3: FFFQLVFAATAATIVSGAVA
Helix 4: SFLIFSFILVAVMYPFTGHWVWG
Helix 5: FAGSTVVHSVGGWAALAGAIVL
Helix 6: MTSAALGTLILWLGWFGF
Helix 7: SVMAHVIVTTNISAALGALASTVTAWIIL
Helix 8: MILNGTLAGLVGITAPCAI
Helix 9: AAIIGAVSGVLVVLSVLFF
Helix 10: TSVHLVCGIWGTLAVAIFGY
Helix 11: FLTQLYGILAIGGFTFVVSFILWFVL

Query ID: B0SRS8
Helix 1: WVWTCIAAFLVFFMQAGFAYV
Helix 2: LTVGALAYWLIGFSIMFGPQVL
Helix 3: YTFFIFQIVFAATAATIVSGAMA
Helix 4: AYLIFSVIITAVIYPVFGSFAWGSLLGVS
Helix 5: FAGSTVVHSIGAWAGLAGAIVVG
Helix 6: VYPILGHNMSMAALGVFILWFG
Helix 7: IAVVTHMAACAGALSAMALTWYLF
Helix 8: IGLTLNGGLAGLVAITAP
Helix 9: ILGSVIIGLVAGILVIVSVLFL
Helix 10: VSVHGVCGAWGTMAYGLF
Helix 11: FAQFAAQAIGVVTAFLWAFPASLLMFYLI

Query ID: A0A094W9G3
Helix 1: WVVVAAVLVLFMQAGFAFLETGLS
Helix 2: NLVILGVSSLVFWAIGFGISF
Helix 3: ILFQTAFCAVSLAIVWGGMA
Helix 4: VYIIFGTVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLLL
Helix 6: IPFVILGTMILWLGWFGF
Helix 7: YFAYVAMTTNLAAAAGVLAATFMSWALL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: VIGAIAGVIAVIGVLWV
Helix 10: VSVHGMAGIWGTLSTGLFAA
Helix 11: WHQLGVQFLGIMAVSVYVFSVSLLVFYLI

Query ID: A0A1V3SSW1
query A0A1V3SSW1 has 12, using last 11 helices
Helix 1: LWVVVAAILVLFMQAGFAFLETGLS
Helix 2: NLVILGVSSLVFWAIGFGISF
Helix 3: ILFQTAFCAVSLAIVWGGMA
Helix 4: VYIIFGTVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLLL
Helix 6: IPFVILGTMILWLGWFGF
Helix 7: YFAYVAMTTNLAAAAGVLAATFMSWALL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: VIGAIAGVIAVIGVLWV
Helix 10: VSVHGMAGIWGTLSTGLFAA
Helix 11: WHQLGVQFLGIMAVSVYVFSVSLLVFYLI

Query ID: A0A2I2MEF2
Helix 1: WVVVAAVLVLFMQAGFAFLETGLS
Helix 2: NLVILGVSSLVFWAIGFGISF
Helix 3: ILFQTAFCAVSLAIVWGGMA
Helix 4: VYIIFGTVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLLL
Helix 6: IPFVILGTMILWLGWFGF
Helix 7: YFAYVAMTTNLAAAAGVLAATFMSWALL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: VIGAIAGVIAVIGVLWV
Helix 10: VSVHGMAGIWGTLSTGLFAA
Helix 11: WHQLGVQFLGIMAVSVYVFSVSLLVFYLI

Query ID: A0A7C3QR70
Helix 1: AWQLTAATIVGIQSVPGLVVLYG
Helix 2: AFMALYAFAAVLVAWVLWGY
Helix 3: VFFQFVFAAITLIILAGSVL
Helix 4: AWMLFVPLWLTGSYVVGAFSLWG
Helix 5: YSGGYVIHLAAGFGGLVAAWVV
Helix 6: LPNNILLTLVGAGLLWLGW
Helix 7: LNTNIATAVSLIVWTLLDVF
Helix 8: VIGAIQGMITGLVAITPAA
Helix 9: MGAIIIGIASGIVPWISMNIV
Helix 10: GVAGLLGGVMTGIFATPAL
Helix 11: VVLQLIGAGFIIVLNVVVTYVIL

Query ID: A0A059XYD5
query A0A059XYD5 has 12, using last 11 helices
Helix 1: LWVVVAAILVLFMQAGFAFLETGLS
Helix 2: NLVILGVSSLVFWAIGFGISF
Helix 3: ILFQTAFCAVSLAIVWGGMA
Helix 4: VYIIFGTVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLLL
Helix 6: IPFVILGTMILWLGWFGF
Helix 7: YFAYVAMTTNLAAAAGVLAATFMSWALL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: VIGAIAGVIAVIGVLWV
Helix 10: VSVHGMAGIWGTLSTGLFAA
Helix 11: WHQLGVQFLGIMAVSVYVFSVSLLVFYLI

Query ID: J9ZB82
query J9ZB82 has 12, using last 11 helices
Helix 1: LWVVVAAILVLFMQAGFAFLETGLS
Helix 2: NLVILGVSSLVFWAIGFGISF
Helix 3: ILFQTAFCAVSLAIVWGGMA
Helix 4: VYIIFGTVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLLL
Helix 6: IPFVILGTMILWLGWFGF
Helix 7: YFAYVAMTTNLAAAAGVLAATFMSWALL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: VIGAIAGVIAVIGVLWV
Helix 10: VSVHGMAGIWGTLSTGLFAA
Helix 11: WHQLGVQFLGIMAVSVYVFSVSLLVFYLI

Query ID: J9Z839
Helix 1: AWQLTAATIVGIQSVPGLVVLYG
Helix 2: AFMALYAFAAVLVAWVLWGY
Helix 3: VFFQFVFAAITLIILAGSVL
Helix 4: AWMLFVPLWLTGSYVVGAFSLWG
Helix 5: YSGGYVIHLSAGFAGLVAAWVV
Helix 6: LPNNILLTLVGAGLLWLGW
Helix 7: LNTNVATAVSLIVWTLLDVM
Helix 8: VIGAIQGMITGLVAITPAA
Helix 9: LGAIIIGVASGIIPWISMNIV
Helix 10: GVAGLLGGVMTGILATPAL
Helix 11: VVLQLIGAGFIIALNIVVTYVIL

Query ID: A0A7C3LUF9
Helix 1: LWVVVAAILVLFMQAGFAFLETGLS
Helix 2: NLVILGVSVLVFWAMGFGISF
Helix 3: VLFETAFCAVSLAIVWGGMA
Helix 4: VYILFGIVFSGLIYPVVGHWIWG
Helix 5: FAGSTVVHLQGALSALAGTLFL
Helix 6: IPFVVLGTLILWLGWFGF
Helix 7: YFAYVAMTTNLAAASGVLAATFVSWLLL
Helix 8: MMANGALAALVAITASCAFVT
Helix 9: LIGAVAGAIAVVGVLWI
Helix 10: VSVHGMAGVWGTLSTGFFAS
Helix 11: WHQLAVQSLGILAVSVYVFTASCLVFYLI

Query ID: A0A059XXR1
Helix 1: AWQLTAATIVGIQSVPGLVVLYG
Helix 2: AFMALYAFAAVLVAWVLWGY
Helix 3: VFFQFVFAAITLIILAGSVL
Helix 4: AWMLFVPLWLTGSYVVGAFSLWG
Helix 5: YSGGYVIHLSAGFAGLVAAWVV
Helix 6: LPNNILLTLVGAGLLWLGW
Helix 7: LNTNVATAVSLIVWTLLDVM
Helix 8: VIGAIQGMITGLVAITPAA
Helix 9: LGAIIIGVASGIIPWISMNIV
Helix 10: GVAGLLGGVMTGILATPAL
Helix 11: VVLQLIGAGFIIALNIVVTYVIL

Query ID: A0A094YPF5
Helix 1: AWQLTAATIVGIQSVPGLVVLYG
Helix 2: AFMALYAFAAVLVAWVLWGY
Helix 3: VFFQFVFAAITLIILAGSVL
Helix 4: AWMLFVPLWLTGSYVVGAFSLWG
Helix 5: YSGGYVIHLSAGFAGLVAAWVV
Helix 6: LPNNILLTLVGAGLLWLGW
Helix 7: LNTNVATAVSLIVWTLLDVM
Helix 8: VIGAIQGMITGLVAITPAA
Helix 9: LGAIIIGVASGIIPWISMNIV
Helix 10: GVAGLLGGVMTGILATPAL
Helix 11: VVLQLIGAGFIIALNIVVTYVIL

Query ID: B1Y8C9
Helix 1: AWMMVSTLLVILMTVPGLALFY
Helix 2: VLMQVMVTFSMIVVLWAVY
Helix 3: IVFAAFQATFAGITCCLIVGAFA
Helix 4: AVLMFMVIWFTFSYAPIAHMVWFWM
Helix 5: LLWQWGALDFAGGTVVHINAAVAGIVGAFM
Helix 6: FTPHSLTLTMVGASLLWVGWFG
Helix 7: FAALGFINTLFATAAAVLAWC
Helix 8: MLGAASGAVAGLVAITPA
Helix 9: ILGGIMIGFLAGFACLWGVNGL
Helix 10: VFGVHGVGGILGALLTGVF
Helix 11: VWIQAKAVMLTVVWSAVVSVIAF

Query ID: B1Y6V4
Helix 1: AFIFACCIAVWLMTIPGLALFY
Helix 2: ILMQVFTVSSLITVLWALY
Helix 3: LLYFFFMLLFAAITPTIIVGAFA
Helix 4: AVLVFMAIWFTINYVPMAHM
Helix 5: VVHVNVGIAALVGAWMVGA
Helix 6: GSMLWVGWLAFCGGCALAA
Helix 7: LVVVNTMLAAAAGAMSWVLVEWL
Helix 8: MLGAVSGAIAGLVAITPA
Helix 9: PMGALAIGVIVSPICIWAV
Helix 10: SFDVFGVHGVGGIVGGILTTIFAM
Helix 11: VQLMVIGFSVVYSAISSWIAF

Query ID: B1Y0E5

Helix 1: AWMMAATALVLLMSIPGLALFYA
Helix 2: MAQVLAVCALVSLLWFALGYSLA
Helix 3: FVMYQMSFAIITPALIVGAFA
Helix 4: ALLWFMALWSLAVYAPIAHWVW
Helix 5: VHLNAGMAGLVAAWMLGRRI
Helix 6: LGYTMVGAALLWVGWMGF
Helix 7: AGMAMLATQLAAAAATLSWM
Helix 8: LLGLCSGAVAGLVAVTPAS
Helix 9: ASAVLIGAAAGVGCYWGATGL
Helix 10: VFGVHAVGGLIGALLTGVLA
Helix 11: ATLLYSGVVTAAILWAVDAVI

Query ID: B1XZU2
Helix 1: NLAWVGICTALVFFMQAGFALVEGGLA
Helix 2: IYLGTCFIGVGFWLVGYGVA
Helix 3: LLYQMMFATTAVTIVSGAVA
Helix 4: AYLFFAVLMSLLIYPVYAHW
Helix 5: GAVHSIGAWCALAGVMVLG
Helix 6: LPMVALGGFVLWLGWFGF
Helix 7: NLGTVLLNTYLGACAGGIGALAFM
Helix 8: VLMSASVNGSLCGLVAITGGA
Helix 9: LTATLVGMIGGALCTWGA
Helix 10: VDAIAVHGIGGVWGLIATGLFY
Helix 11: VQALGAFIAFAWAFPMAYACF

Query ID: B1Y842
Helix 1: FILLGAIMVLAMHAGFAFLELGTV
Helix 2: ILVDFAVSTIAYFFVGYSVAYGV
Helix 3: FFFLLTFAAAIPAIVSGGIA
Helix 4: LIATAVIVGLIYPLSEGAVWN
Helix 5: FAGSVVVHAVGGWIGLAAVLLLGA
Helix 6: SSIPFLALGAWVLAVGWFG
Helix 7: ISGLVAVNSLMAMVGGTLVAVLM
Helix 8: FAYNGPLAGLVAVCAGSDL
Helix 9: ALVVGGVAGAIFVSLFTLT
Helix 10: VWPLHGLCGAWGGIACGIFGQQAL
Helix 11: SIGTLLAVIWAFAGGLAVYGAI

Query ID: A0A1H1BPD6
Helix 1: TSAALVLIMTPGLALFYGGL
Helix 2: VNMMLFSVSAMGVVGVLWILF
Helix 3: ASYISVGFGAVFAMITTALIS
Helix 4: WVLFSGVWATLVYFPVAAWVW
Helix 5: LAGGTVIHINAGAAALALALVAG
Helix 6: PHSIPLVTIGAALLWFGWIGF
Helix 7: GLILVNTLAAPAAGIVGWILV
Helix 8: GVIGAASGAVGGLVAITPAA
Helix 9: VWALLLGLIAGMACAVAIEW
Helix 10: VVGLHLVAGVIGSLYLGFFAF
Helix 11: LLLVQAISVVSVMVYSFVVSLVIALGV

Query ID: A0A147EQL9
Helix 1: TSAALVLIMTPGLALFYGGL
Helix 2: VNMMLFSVSAMGVVGVLWILF
Helix 3: ASYIGVGFGAVFAMITTALIS
Helix 4: WVLFSGVWATLVYFPVAAWVW
Helix 5: LAGGTVIHINAGAAALALALVAG
Helix 6: PHSIPLVTIGAALLWFGWIGF
Helix 7: GLILVNTLAAPAAGIVGWILV
Helix 8: GVIGAASGAVGGLVAITPAA
Helix 9: VWALLLGLIAGMACAVAIEW
Helix 10: VVGLHLVAGVIGSLYLGFFAF
Helix 11: LLLVQAISVVSVMVYSFVVSLVIALGV

Query ID: D5T4N9
Helix 1: LAWVLISSALVWLMTPGLALFYG
Helix 2: MFIPVLIIGIASLTWFLVGYSLA
Helix 3: AFALFQGMFPIITAAIITGSVI
Helix 4: AMIVFIILWLITVYSPLAHMVWG
Helix 5: FAGGTVVHISSGVTGLVLALLIG
Helix 6: PSYVLIGGALLWVGWFGF
Helix 7: LAANGTAVLALVNTWLASAVSVLT
Helix 8: VTLAGITSGGVAGLVVITPAA
Helix 9: WSAVIMGLLAGIIGFAGITFV
Helix 10: AFGIHGIGGAVGAILTGVF
Helix 11: WKQLVAVLFTVAFAAIGTLILA

Query ID: A0A7V2SZE0
Helix 1: AWMLVATVLVLFMTIPGLSMFYA
Helix 2: FVQIFAITALATIVWVVIGYSIA
Helix 3: VFMVFQMTFAIITPALIVGAFA
Helix 4: AMLIFTVIWLIVVYAPITHWVW
Helix 5: VHINAGVAGLVAAIVIGKR
Helix 6: NLTYTIIGAAMLWVGWFGF
Helix 7: AGMAMAVTQIATAAAALTWM
Helix 8: ALGIASGAVAGLVAITPAA
Helix 9: MGALALGAISGVACYISVAKL
Helix 10: AFGLHGVGGIVGALLTGVFAA
Helix 11: VMVQATGIGATILYTGVMTFIILIIL

Query ID: A0A7V2T108
Helix 1: NTLWVVFAASLVFFMQAGFAML
Helix 2: MAFCSLAFWAVGYGLMFGA
Helix 3: SYTLLLFQIMFAATAATIVSGAL
Helix 4: WPYIICAILISSFIYPIFGSWAW
Helix 5: FAGSSVVHAIGGWCALAGVIVL
Helix 6: LPLVALGGFILWFGWFGF
Helix 7: IGKIILNTHLSGAAGVFSAMLTL
Helix 8: LLLTSAVNGGLGGLVAICAGCA
Helix 9: FALLTGSIAGIITIFGSRLL
Helix 10: VSVHAFAGTWGTLAVGLFH
Helix 11: IQALGAGIACLWAFSTAWVMFTLLNFIV

Query ID: A0AIW5
Helix 1: MYFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: VLFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMTAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LIIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAVATALIVVIIKLFL

Query ID: A0A7X0WHY1
Helix 1: MFFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: ILFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMTAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LVIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAVVTALIVVVIKLFL

Query ID: A0A842BMP4
Helix 1: MFFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: ILFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMTAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LIIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAVVTALIVVVIKLFL

Query ID: A0A660JU19
Helix 1: MFFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: ILFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMIAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LIIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAIATAIIVVIIKLFL

Query ID: H1GDT6
Helix 1: MFFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: ILFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMTAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LIIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAVVTALIVVVIKLFL

Query ID: Q92BJ7
Helix 1: MFFCTLLVWLMTPGIALFYG
Helix 2: AMYSFSSMAIISILWVIVGYSLA
Helix 3: ILFMMFQMTFAILTVAIISGAFA
Helix 4: AYLIFIILWSLLVYSPVAHWV
Helix 5: VVHISSGVTGLVLAIMIG
Helix 6: NLPLALIGGILVWFGWYGF
Helix 7: AMTAFVNTNTAAAAGIIGWGL
Helix 8: LGTISGAIAGLVSITPAAGFV
Helix 9: LIIGFLGGALCFWAVFWL
Helix 10: AFGLHGIGGIWGGIATGLFATTKV
Helix 11: LIAIGSTVAYVAVVTALIVVVIKLFL

Query ID: A5DYQ2
Helix 1: YVLLFTIASAMIWIMVPGLAFLY
Helix 2: MIWIVIMSSFIGIFQWYFW
Helix 3: LAFAIFQLQFLLVTLAILAGGCI
Helix 4: LPAMVFLFCWATIVYCPVVYWIW
Helix 5: PVEILSGVSAFVYSAFLG
Helix 6: PHNISTVFLGTALLYVGWLFF
Helix 7: VAYSMMNTHLCGAFGAISWCLL
Helix 8: KWSMVAVCSGCISGLVAAT
Helix 9: IPLWASVILGVVAGIVCNL
Helix 10: GVAGVIGLLFNALFGSATVI
Helix 11: LYIQIAYILATFAYAGVVTAILCFVI

Query ID: A5E3X2
Helix 1: MVWIGTASVLVWIMIPGVGLLY
Helix 2: LMWAALMAACVTAFQWFFWGYSLV
Helix 3: VLGAPSVVLTVPDILFCFYQGMFAAVTAILMV
Helix 4: MMVFLFIWLTVVYAPVAYWTW
Helix 5: LVSLGALDFAGGGPVHENSGFAALAYSLW
Helix 6: VSSIVLGTVFLWFGWFGF
Helix 7: SWYACVNTNIAAACGGLTWMFV
Helix 8: VGLCTGAIAGLVGITPAA
Helix 9: YTSIVFGIVPGIVCNFAVDL
Helix 10: VWALHGIGGLCGNIMTALFAADYV
Helix 11: LGYQLAGSVSIAAWSFVVTSILLLV

Query ID: A5E1S5
query A5E1S5 has 13, using last 11 helices
Helix 1: GLQGIGPAIMMPNSQALI
Helix 2: VCFALFGAVAPNGFIVGALF
Helix 3: WTFWVCGIVSIVIAGIAFFVI
Helix 4: FDYWGSILGVSGLVLINFAF
Helix 5: YVYVLLIAGFLCMGAFYFI
Helix 6: FILACISAGWSCFGVWLYY
Helix 7: NIPAGPVGIIAAIAAAYLL
Helix 8: LVMFFAMIAFLAGIIIMGT
Helix 9: FVSLLVQPIGMDMSFPSAVILMSAA
Helix 10: LVSTFVNYSISIGLGFAGTVEYY
Helix 11: YRMGMGLAGFGVVVSTIYLYL

Query ID: A0A1H3WA00
Helix 1: ADNAFMMICTALVLFMTIPGIALFY
Helix 2: VLSQVVVAFALVCLLWVIYGY
Helix 3: FYQYIHVAFQGSFACITVGLVI
Helix 4: IRFSAALIFVVLWLTLSYL
Helix 5: FAGGTVVHINAAVAGLVGATLLG
Helix 6: PHNLPMVCIGTAILYIGWFG
Helix 7: IAGLAFLTTVIATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GAMIIGFAGGFAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCIIWSGVAAFIAF

Query ID: A0A1X3RP39
Helix 1: FMMICTALVLFMTIPGIALFYGGLI
Helix 2: VVVAFALVCLLWVIYGYSVAFSSGNAFF
Helix 3: FYQYIHVAFQGSFACITVGLVI
Helix 4: IRFSAALIFVVLWLTLSYL
Helix 5: FAGGTVVHINAAVAGLVGATLLG
Helix 6: PHNLPMVCIGTAILYIGWFG
Helix 7: IAGLAFLTTVIATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GAMVIGFAGGFAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCIVWSGVAAFIAF

Query ID: A0A1X3RR37
Helix 1: FMMICTALVLFMTIPGIALFYGGLI
Helix 2: VVVAFALVCLLWVIYGYSVAFSSGNAFF
Helix 3: FYQFIHVAFQGSFACITVGLVI
Helix 4: IRFSAALIFVVLWFTLSYL
Helix 5: FAGGTVVHINAAVAGLVGATLLG
Helix 6: PHNLPMVCIGTAILYIGWFG
Helix 7: IAGLAFLTTVIATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GAMVIGFAGGFAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCIVWSGVAAFIAF

Query ID: V4CRP5
Helix 1: WILTSSFIIFTMQSGFGLLEAGSV
Helix 2: NVVDVVFGGVTYWAFGYGF
Helix 3: LVYSTFVFQLSFATTATTVVSGA
Helix 4: LMAYMIFSVFNTVVYCFPAHWVW
Helix 5: VDFAGAGVVHLVGGASSLVAAAFL
Helix 6: GAIVGMFMLWWGWLAFNCGSTFGI
Helix 7: AVTTLISSFSGGIVGIGLSFVV
Helix 8: VAYMINSVLGALVSITACCALV
Helix 9: LVIGMVGGFCTIFVIKIT
Helix 10: IGVHGGGGLWGLIAVGIFAA
Helix 11: FYLLGVQTLCIVCEVFWSGLVTFIILFAI

Query ID: V3ZVE4
Helix 1: ATWILTSAFIIFTMQSGFGLLE
Helix 2: IMVKNAVDVICGGLTYWMF
Helix 3: FFFQASFATTATTIVSGAMA
Helix 4: SYIVFSMLNTFVYCFPAHWIW
Helix 5: IDIAGAGPVHMVGGLSGLVATMVL
Helix 6: ALLGMFMLWWGWLGFNCGSTFGI
Helix 7: AVSTISASTAGGVVGLLSSYIV
Helix 8: VAYLINGVLGSLVGITATCAMVH
Helix 9: VIGLIGGSVTITGVALL
Helix 10: VGTHALGGAWSMLAAGLFA
Helix 11: LGVQTLAVVTLTVWTLFTSFFFL

Query ID: V4AP67
Helix 1: FFLLTNGMIVLLMQCGFAFL
Helix 2: QFFAGISYWLVGYAFAFGK
Helix 3: FALFFFQYVFAATAATIVSGA
Helix 4: FIAYIIYSVLITGFIYPVV
Helix 5: AGSGVVHVLGGIAAFVAAFFLG
Helix 6: VPLAALGGFILLFGFLAFNGGS
Helix 7: AISLAVVNTVISGSTSALFTLVI
Helix 8: WSLLTTLNGALAGMVAI
Helix 9: VYYPWASCIVGFFAAISYRLI
Helix 10: PLDAVAVHFGGGSWGVIAVAFL
Helix 11: YQLAGLLSIGVWTAVTCTIMFGGL

Query ID: V4A9D7

Helix 1: CVVVALSTLFILGLQIGYSLL
Helix 2: LLFEVCILYWVTGHALAFSSG
Helix 3: YSQWLFGFCMCLTSTNIIATSLV
Helix 4: IFFLITFMSVGFVQPVVLHWMW
Helix 5: YVYQDFSGVSCVNIYSGVVGIIGCILL
Helix 6: LIFMGGYLILSGLLALRILA
Helix 7: TLIATSACVLTSIAILTMLNYCG
Helix 8: WFLLLTAINSALSGVVSSGA
Helix 9: YPWAAGVTGFISGCVYIIWCFLL
Helix 10: GSVHLGSGIWSLISAPLFSTSGFIY
Helix 11: WNLAGIGAIMLWTGLPFIVLFISL

Query ID: A0A562BXM4
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVLVVFSVVILVWVSYGY
Helix 3: LLFVVFQSTFAGITTALIV
Helix 4: VLLFSVIWVTFXXLPMVHMVWS
Helix 5: FAGGTVVHINAGIAGLVGAYFLG
Helix 6: PHNVPFTFIGASLLWVGWFG
Helix 7: IASLAMINTMVATAAGVVAWSL
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGAIVIGLAAGAICVWGVNGL
Helix 10: VFGVHAIGGIVGAVLTGVFSA
Helix 11: TFSVLFTIVWCAVVTSIAILVAKAVF

Query ID: A0A839WU60
Helix 1: AWMLTSTLLVLLMVVPGLALFY
Helix 2: VLVQVLVVFSVVILLWIAY
Helix 3: LLFVVFQSTFAGITAALVIGAFA
Helix 4: AVLLFSVLWVTFAYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGIAGLVGAYFVG
Helix 6: PHSVPFTFIGASLLWVGWFGF
Helix 7: AALAMINTMVATAAGVVAWSL
Helix 8: LGAASGAVAGLVGVTPAA
Helix 9: IGALVIGAAAGAVCVWGVNGL
Helix 10: VFGVHAVGGIVGAILTGVF
Helix 11: AQTFSVLFTILWCAVVTTLAILV

Query ID: A0A853JAB6
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVLVVYSVVMLVWVAY
Helix 3: FLFVAFQATFAGITTALIV
Helix 4: IKFAAVLLFSVLWVTFAYLPM
Helix 5: FAGGTVVHINAGVAGLVGAYFLG
Helix 6: PHSVPFTFIGASLLWVGWFGF
Helix 7: AALAMINTMVATAAAVVAWSL
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: LGAIVIGLAAGAICVWAVNGL
Helix 10: VFGVHGVGGIVGALLTGVFSA
Helix 11: AISVVFTIVWCAVVTALAILA

Query ID: A0A5C5TYS5
Helix 1: VAWMLTSTFLVLLMVVPGLALFY
Helix 2: VIMQVLVVFSVVILIWVSY
Helix 3: FLFIVFQSTFAGITTALIVGAFA
Helix 4: AVLLFSVIWVTFSYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGIAGLVGAYFLG
Helix 6: PHNVPFTFIGAALLWVGWFGF
Helix 7: ASLAMINTMVATSAGVVAWSL
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGAIVIGLAAGAICVWAVNGL
Helix 10: VFGVHAVGGIVGALLTGVFSA
Helix 11: LVSVLFTILWCAVVTAIAILIA

Query ID: A0A290XBB5
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VIMQVLVVFSVVIILWVAY
Helix 3: FLFIAFQSTFAGITTALVVGSFA
Helix 4: AVLLFSILWVTFAYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGVAGLVGAYFLG
Helix 6: PHSVPFTFIGASLLWVGWFGF
Helix 7: ASLAMLNTMVATAAGVIAWSI
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGAVVIGLAAGALCVWGVTGL
Helix 10: VFGVHGIGGIVGALLTGVFSA
Helix 11: LVSVAFTVLWCAVVTAVVMLIVRLVV

Query ID: A0A653N397
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VIMQVLVVFSVVIILWVAY
Helix 3: FLFIVFQSTFAGITTALVVGSFA
Helix 4: AVLLFSILWVTFAYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGVAGLVGAYFLG
Helix 6: PHSVPFTFIGASLLWVGWFGF
Helix 7: ASLAMLNTMVATSAGVVAWSI
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGALVIGLAAGALCVWGVTGL
Helix 10: VFGVHGIGGIVGALLTGVFSA
Helix 11: FISVAFTVLWCAVVTAVVMLIVKLVV

Query ID: A0A4R5U5V1
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VIMQVLVVFSVVIILWVAY
Helix 3: FLFIVFQSTFAGITTALVVGSFA
Helix 4: AVLLFSILWVTLAYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGVAGLVGAYFLG
Helix 6: PHSVPFTFIGASLLWVGWFGF
Helix 7: ASLAMLNTMVATAAGVVAWSI
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGALVIGLAAGALCVWGVTGL
Helix 10: VFGVHGIGGIVGALLTGVFSAQALG
Helix 11: VWVQFVSVAFTVLWCAVVTAVVMLLV

Query ID: A0A7Z0QPG3
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVLVVYSLVIVLWVAY
Helix 3: FLFVIFQATFAGITTALIV
Helix 4: IKFAAVLLFSILWVTFAYLPM
Helix 5: FAGGTVVHINAGVAGLVGAYFIG
Helix 6: PHNVPFTFVGASLLWVGWFGF
Helix 7: ASLAMINTMVATAGGVLAWS
Helix 8: ALGAASGAIAGLVGITPAA
Helix 9: IGALAIGLIAGALCVWGVTGL
Helix 10: VFGVHGIGGIVGALLTGVFSA
Helix 11: IGAQVLVQLVSVVFTIVWCAVVTAIAI

Query ID: A0A5C5TUT2
Helix 1: VAWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVLVVFSVVILVWVSYGY
Helix 3: LLFVVFQSTFAGITTALIV
Helix 4: VLLFSVIWVTFAYLPMVHMVWS
Helix 5: FAGGTVVHINAGIAGLVGAYFLG
Helix 6: PHNVPFTFIGASLLWVGWFG
Helix 7: IASLAMINTMVATAAGVVAWSL
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGAIVIGLAAGAICVWGVNGL
Helix 10: VFGVHAIGGIVGAVLTGVFSA
Helix 11: TFSVLFTIVWCAVVTSIAILVAKAVF

Query ID: A0A4V3ALP8
Helix 1: VAWMLTSTFLVLLMVVPGLALFY
Helix 2: VLMQVLVVFSVVILLWVSY
Helix 3: FLFIVFQSTFAGITTALVVGAFA
Helix 4: AVLLFAVLWATFSYLPMVHMVW
Helix 5: VIDFAGGTVVHINAGIAGLVAAYFVG
Helix 6: PHNVPFTFIGAALLWVGWFGF
Helix 7: ASLAMINTMVATSAGVVAWSL
Helix 8: LGAASGAIAGLVGITPAA
Helix 9: MGAIVIGLAAGAICVWAVNGL
Helix 10: VFGVHAVGGIVGAVLTGVFSA
Helix 11: TLSVLVTIGWVAVVTALVMVVVKLVV

Query ID: V4REY8
Helix 1: AFVFNTILFLMGGFLVMFMAAGF
Helix 2: IALYSIAGLMFWLVGYNILY
Helix 3: WFFQMVFCAATASIVSGTVA
Helix 4: LWPFLIFTAILTGIMYPI
Helix 5: AGSTIVHSVGGWAALAGAILL
Helix 6: MPLATLGTFILWLGWFGF
Helix 7: IFVNTNAAAASGVIVAMILS
Helix 8: VDLTFALNGALAGLVSITA
Helix 9: SILWAVIVGGVGGAIVVFAVPLL
Helix 10: IPVHLMAGIWGTLVVPFS
Helix 11: FGTQIVGILAYGVFTFVAALVVWGVL

Query ID: V4RK08
Helix 1: IFYWWCTALMITIHAGFL
Helix 2: LLAFAFVVPTFFFFGWWIY
Helix 3: GIFWAAFALFAATTASIASGAVI
Helix 4: AFLVLAIVLGSAVWILGAAWGW
Helix 5: VGAAGCVHLIAGAFTLGILLNL
Helix 6: VPLTVVGLMLIIVGFFGFLGGCIIYNG
Helix 7: ATLSAFAFNTLMGFTGGIIGGW
Helix 8: FWMMSCGLVGIISAASGL
Helix 9: PLAFAIGMAGGVMAPMVALFL
Helix 10: VAVHGFGGAWGVLAMGLFASGY
Helix 11: VVGLVVLGALGFIPGYAISAVM

Query ID: V4RHR4
Helix 1: FYYWVTVVFMFLIHVGFCLY
Helix 2: CIPLVTITFFFFGWWIYFAF
Helix 3: GVFWAAFLLFSWTAASIVSGSVI
Helix 4: AFWILAVVIGSCTWIIDAAWGWHYG
Helix 5: AYASGVIHAIAGGFALGVLVVLG
Helix 6: WLATLGLFLIYTGFWGFYAACNIPII
Helix 7: YLAPTTLSAITFNFLMSLSGGLLMGYV
Helix 8: FWTYSAGLAGIIAASAGN
Helix 9: IQAMFIGAIGAFAAYKLH
Helix 10: AVGAVAVHGYAGFLGVVIAGFML
Helix 11: FLGAVIMFGVLGFLPAWIISTVL

Query ID: F4XTK4
query F4XTK4 has 12, using last 11 helices
Helix 1: AIWILVAAILVIFMNAGF
Helix 2: LIVFALATIAFWAIGFSFMF
Helix 3: ISVFFLFQAAFAGTAATIVSGA
Helix 4: FLDFLIFSILIVGFSYSI
Helix 5: FAGSTVVHSVGGWAALMGAAFL
Helix 6: MSIATLGCLILWIGWFGF
Helix 7: VPYIAVTTNLAAAAGGITATLTAWL
Helix 8: LSMIINGILAGLVAITAP
Helix 9: YLSAVIIGAIGGIIVVFSVSFF
Helix 10: ISVHLVNGIWGTLAVGLFA
Helix 11: GILAIGGFTVLFSGIVWFVL

Query ID: F4Y3C5
Helix 1: NLSTIWLLVSSFLVFFMNAGF
Helix 2: LIVFCISALAFWLVGFGLMF
Helix 3: FAALFLFQLVFAGTAATIVSGA
Helix 4: FWAFLLFSFFLVGFIYPVT
Helix 5: FAGSTVVHSVGGMAGLVGAWLL
Helix 6: LGLATLGCLILWLGWFGF
Helix 7: MAAAAGGISSVFFSPIILG
Helix 8: IINGILGGLVGITASAAFV
Helix 9: FIIGSISGIFVLLGEYFL
Helix 10: IPVHLFCGFWGTIALGIFSSNSS
Helix 11: FLGWLIIIIVTALLSLLGWLLVSLILYYA

Query ID: A0A2S5CTX8
Helix 1: LSVNLVWIMLGTILVFFMHAGF
Helix 2: FLTISLGGIVYFLCGYAIMFG
Helix 3: LSFFIFQTMFAATGATILSGA
Helix 4: IFAYIGVIILMTILVYPVVGHWVW
Helix 5: IDFAGSTVVHLTGAVAAFIAAIMV
Helix 6: VNVITGHSIPIGALGVFLLWFGWFGF
Helix 7: LVPTVIANTFFSAAAGVVATAFY
Helix 8: LTLNGALAGLVGITAGAANV
Helix 9: LIIGLIAAPLLVEGVRFI
Helix 10: AIAVHGICGIWGTLAVGLF
Helix 11: AIGVIATIAWVSVTVTAGLYII

Query ID: A0A2S0JW39
Helix 1: LSVNLVWIMLGTILVFFMHAGF
Helix 2: FLTISLGGIVYFLCGYAIMFG
Helix 3: LSFFIFQTMFAATGATILSGA
Helix 4: IFAYIGVIILMTILVYPVVGHWVW
Helix 5: IDFAGSTVVHLTGAVAAFIAAIMV
Helix 6: VNVITGHSIPIGALGVFLLWFG
Helix 7: VIANTFFAAAAGVVATAFY
Helix 8: LTLNGALAGLVGITAGAANV
Helix 9: LIIGLIAAPLLVEGVRFI
Helix 10: AIAVHGICGIWGTLAVGLF
Helix 11: AIGVIATIAWVSVTVTAGLYII

Query ID: A0A0S2FHD7
Helix 1: LLVLLMTVPGLALFYGGL
Helix 2: LSVLMQVLAVFSLIVLLWVTY
Helix 3: YVFIAFQSTFAGITGALIVGAFA
Helix 4: AVLLFSAIWFTFAYLPIAHMVW
Helix 5: AIDFAGGTVVHINAGIAGLVGAYFVG
Helix 6: PHNVTFTMIGASLLWVGWFGF
Helix 7: AALAFLNTLLATAAAALAW
Helix 8: SMLGGASGVVAGLVAITPA
Helix 9: PFGAIAIGAIAGAVCVWGVHGL
Helix 10: VFGVHGLGGIIGALLTGVFSSPAL
Helix 11: ALSVGITVVWSGVVSVIAFAIVKLLV

Query ID: A0A0S2DQB6
Helix 1: VAWMLTSTLLVLLMTVPGLALFY
Helix 2: VLMQVLAVFSLIVLLWVSY
Helix 3: YVFVAFQSTFAGITGALIVGA
Helix 4: FAAVLLFAAIWFTFAYLPI
Helix 5: FAGGTVVHINAGIAGLVGAYFVG
Helix 6: PHNVTFTMIGASLLWVGWFGF
Helix 7: AALAFLNTLLATAAAALAW
Helix 8: SMLGGASGVVAGLVAITPA
Helix 9: PFGAIAIGAIAGAACVWGVHGL
Helix 10: VFGVHGLGGIIGALLTGVFSAPAL
Helix 11: ALGVAITVAWSGLVSVVAFVIVKAVV

Query ID: Q2WBF7
Helix 1: TAWMLTSTALVLMMTIPGLALFYAGMV
Helix 2: SFAITCVVTLLWVIIGYSLAF
Helix 3: VFMMFQMTFAIITPALITGAFA
Helix 4: SMLVFMSLWLLVVYAPICHWVW
Helix 5: FAGGTVVHINAGVAGLVACLIL
Helix 6: APHNLSLSIIGAALLWVGWFGF
Helix 7: AGMAMAVTQVGAAAAAVSWMF
Helix 8: LGIISGAVAGLVAITPASGF
Helix 9: ALVIGLVAGVVCYWGATGL
Helix 10: AFGVHGIGGIVGAILTGVFAV
Helix 11: QVYGVLTTLVYTAVVSFILL

Query ID: Q2W5V2
Helix 1: VLFILLGAVMVLAMHSGFAFL
Helix 2: FAVSTIVYFFVGYSVAYGTTFLV
Helix 3: LVKFFFLATFAAAIPAIVSG
Helix 4: LMATAVLVGLVYPLFEGMVWG
Helix 5: FAGSVVVHAVGGWIGLAAVLMLGV
Helix 6: FLALGAWVLSVGWFGFNVMSA
Helix 7: ISGLVAINSLMAMVGGIVTSLLV
Helix 8: FIHNGALAGLVAVCAGSDV
Helix 9: ALVTGGIAGAMFVWLFNLC
Helix 10: VWALHGMCGFLGGIACGVFG
Helix 11: LGAQVTGTVMGAAFGLAGGLAVY

Query ID: F3ZYD6
Helix 1: IWTLLAGFLVFFMQAGFAMV
Helix 2: FAIGTPIYWLVGFGIMFGADAAGLF
Helix 3: LPAFLVFQTMFAATAATIVS
Helix 4: YCIYSAVISLIIYPVVGHWIWG
Helix 5: FAGSTVVHSVGGWTALIGSAMV
Helix 6: ITLAALGTFILWFGWFGF
Helix 7: AIGHIALTTNLAGAMGAVVTMIYTWL
Helix 8: VSMTLNGALAGLVGITAGTLA
Helix 9: AAIIGSLCGLLVVSSVEFF
Helix 10: AISVHGVCGTFGTIMVGLFAT
Helix 11: LLSVQLLGVGSVFLWTTVMAFILFTVL

Query ID: F3ZVV4

query F3ZVV4 has 12, using last 11 helices
Helix 1: AFVLISAALVMLMTPGLAFFYGG
Helix 2: VLNMIMQSFIIIAIISIQWVL
Helix 3: FMIYQLMFAIITPALITGAFA
Helix 4: AFIGFTVLWSFLVYDPLAHWVW
Helix 5: LDFAGGNVVHISSGVSGLVLALI
Helix 6: LLPHSMPMIILGAGILWFGWFG
Helix 7: IAVNAFVTTNTSAAAAVLSWV
Helix 8: ILGAVSGAVAGLVSITPGAGF
Helix 9: AIIIGLVGGVVCYFAISVV
Helix 10: AFGIHGIGGMWGAVATGLFA
Helix 11: LGIQLISVAATVMLAIAMTFIIV

Query ID: A8PXT8
Helix 1: IAWVLTCTCLVFLMIPGVAFFYSGL
Helix 2: LMVLALSMMVMAVASLEWFFW
Helix 3: SLVYCMYQLMFAALTPVIACGAFA
Helix 4: PILLFTFCWCTIVYNPLA
Helix 5: GGTPVHISSGTAALAISLYL
Helix 6: VVLGTVLIWVGWFGFNGGSGI
Helix 7: AVQAMMASHISSCVGGVTWMLL
Helix 8: AFCSGAISGFVAITPASGFV
Helix 9: LAFGVIGATVCNFATGL
Helix 10: IFAAHGIGGIAGNLLTALFA
Helix 11: LGYQLADSCAGFGWSFVLTMILLFL

Query ID: A0A495DND0
Helix 1: AWILTSTALVLLMTLPGLALFYG
Helix 2: LMQSLGAAAVVTVLWALIAYSLA
Helix 3: LFLMFQLTFAIITVAIIAGAAV
Helix 4: AFMVFGAAWLILVYAPICHWVWG
Helix 5: FAGGAVVHINAGVAGLVLAKFL
Helix 6: APDNLVLTVTGAGMLWVGWFGF
Helix 7: AAHAFVTTQIAAASAVLVWI
Helix 8: VLGAASGAIAGLVAITPAA
Helix 9: WAAFVIGSCGAFGAYWGVTAL
Helix 10: AFGLHGLGGLVGAVLTGVFAS
Helix 11: QTWGALAAAMYCGVVTTVILFV

Query ID: A0A495D4X4
Helix 1: FNTLLFLIGGFLVMLMAAGFA
Helix 2: IALYSIAGIMFYLVGYQVMY
Helix 3: WFFQMVFVATAASIVSGTIA
Helix 4: LGPFFIFVVVLTAVIYPI
Helix 5: FAGSTLVHSTGGWAALAGAILLGA
Helix 6: MIPGSLPLATLGTFILWFGWFGF
Helix 7: IFANTNMAAAGGVVTAYLLSMLL
Helix 8: LAYCLNGALAGLVAITA
Helix 9: TIMEAIAIGAVGSVIATFG
Helix 10: VVGAIPVHLFAGIWGTMAVPLT
Helix 11: FFGQAVGVGAIGAFVFATSFVVWLVL

Query ID: Q0AT01
Helix 1: FNTLLFLIGGFLVMLMAAGFA
Helix 2: IALYSIAGIMFYLVGYQVMY
Helix 3: WFFQMVFVATAASIVSGTIA
Helix 4: LGPFFIFVIVLTAVIYPI
Helix 5: FAGSTLVHSTGGWAALAGAILLGA
Helix 6: MMPGSLPLATLGTFILWFGWFGF
Helix 7: IFANTNMAAAGGVVTAYLLSMLL
Helix 8: LAYCLNGALAGLVAITA
Helix 9: TILQAIAIGAVGAVIATFG
Helix 10: VVGAIPVHLFAGIWGTMAVPLT
Helix 11: FFGQAVGVGAIGAFVFVTSFVVWMIL

Query ID: Q0ARJ4
Helix 1: NAWILTSTALVLLMTLPGLALFYG
Helix 2: LMQSLGAAAVVTVLWALVGYSLA
Helix 3: LFLMFQLTFAIITVAIIAGAAV
Helix 4: AFMVFGAAWLILVYAPICHWVWG
Helix 5: FAGGAVVHINAGVAGLVLAKFL
Helix 6: APDNLVLTVIGAGLLWVGWFGF
Helix 7: AAHAFVTTQIAAASAVLVWI
Helix 8: VLGAASGAIAGLVAITPAA
Helix 9: WSAFIIGAGGAFGAYWGVTAL
Helix 10: AFGLHGVGGLVGAILTGVFAS
Helix 11: QTWGALAAAIYCGVVTTVILFV

Query ID: W0DZS7
Helix 1: MLTATALVLFMTLPGLSLFYAGL
Helix 2: LSVLMQCFAIACLMSLLWAVY
Helix 3: LFMTFQMTFAIITPALMVGAFA
Helix 4: AMLIFMALWLTLVYIPIAHWVWG
Helix 5: FAGGTVVHINAGIAALVAAIVLG
Helix 6: PHNLGLTVMGAAMLWVGWFGF
Helix 7: AAMALTVTQLATATAALTWM
Helix 8: VLGIATGAVAGLVAITPAS
Helix 9: MGAIVIGFSGAIFAFIAST
Helix 10: LDVWGVHGVAGIVGALLTGVFAA
Helix 11: WIQFVSVIATLVYGGIVSLLLLL

Query ID: W0E077
Helix 1: AAGLVFLMQAGFTALESGLV
Helix 2: NISDFLVAVILFWLIGFALMFGTSQ
Helix 3: YAFFLFQATFVGTAATIVAGAVA
Helix 4: AYLIISAMISLLIYPVSGHWVW
Helix 5: FAGSTVVHSVGGWVALAGVIVL
Helix 6: LLLATLGIFILWFGWFGF
Helix 7: IILNTVLSASAGGLASLLLAL
Helix 8: VLNGTLAGLVSITAGCAFV
Helix 9: LWIGAIGGLLVYGIESALLHL
Helix 10: VGAIAAHGFGGVWGTLALALFAPA
Helix 11: FGVQLIGVVAVFVWAFGSGLVVFLGL

Query ID: W0DYY3
Helix 1: FYFLVTGALVMWMAAGFAMLEAGLV
Helix 2: NIALFAIASTTYMVIGYDLM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WSFLLFATVMTAVIYPIQGYW
Helix 5: LVHLCGAAAALAGVLLLGA
Helix 6: NAIPGANLPLATLGTFVLWLGW
Helix 7: VAAIFVNTNMAAAGGTLLGLITARLLF
Helix 8: MALNGALAGLVAITAEPL
Helix 9: FATLIGGVGGVLVVFSIVTL
Helix 10: ISVHGVVGMWGLMAVPIT
Helix 11: FAAQAIGLGAILGWVFTTSLLAWLLI

Query ID: W0DZX1
Helix 1: FLLVGAVMVLAMHAGFAFLEVGTV
Helix 2: IMADFAVSTIAYFFIGYSLAYGI
Helix 3: FFFLLTFAAAIPAIVSGGIA
Helix 4: LLASFLVVGLLYPSFEGVVWN
Helix 5: FAGSVVVHGFGGWLALAAVLLL
Helix 6: IPFLSLGAWTLTVGWFGFNVMS
Helix 7: AVSGLVAVNSLMAMVGGILAALLA
Helix 8: FLHNGPLAGLVAVCAGSDL
Helix 9: ALATGAVAGAIFVYTFTLA
Helix 10: VWPLHGLCGLWGGLAAGIFGLPLL
Helix 11: ALGSLAGALFAFVGGALVYGMA

Query ID: A0A1T4SFY6
Helix 1: NTAWVLVSAALVMLMTPGLAFFY
Helix 2: MMLMSFTSIAIVSVLWVLVGYSL
Helix 3: LVFAGFQMMFAVITVALISGAIA
Helix 4: AWLLFVPIWALIVYFPVAHWVW
Helix 5: IFGLGVIDFAGGTAVHINAGAAALALTLVLG
Helix 6: PHNLPFVLLGAALLWFGWFGF
Helix 7: AALALVNTQVATAAATGAWML
Helix 8: VTALGFASGAVAGLVAITPAA
Helix 9: VGSVILGLIAGAVCAYAISW
Helix 10: VVGIHLVGGIIGSLAIGLLA
Helix 11: LLGLQALGVFAVLVYSFAVTWVIA

Query ID: A0A2T0XPP2
Helix 1: MLWVLIAAAMVMFMQPGFAMV
Helix 2: FSVGSLMFWLIGFSIMFGTDLG
Helix 3: YAILIFQTVFAATAATIVSGAVA
Helix 4: AYILASFFITAVIYPISGHWVWG
Helix 5: FAGSTVVHSVGGWLGLVGAATVG
Helix 6: AIPGHSLTIGALGVFILWFGW
Helix 7: VASIFVTTNLSAAAGTVTAMIISWM
Helix 8: LGLSLNGALAGLVAITAG
Helix 9: PGGAVIIGVIAGFVLIFGV
Helix 10: VGAVTVHGFSGAVGTIMVGLLA
Helix 11: SLLGVQALGVISVAAWALAMGFILF

Query ID: M7XJ51
Helix 1: VWMMLCTAMVFIMHLGFAGV
Helix 2: PIIGIATYALIGFFLMYPGF
Helix 3: FLFQAMFAATCATIVSGAIA
Helix 4: AYLVFTVFFVGLVYPLIGSW
Helix 5: LVHSVGGWGALAGVILVGPRIG
Helix 6: GASIPLAVIGTFLLWFGWFGF
Helix 7: LVSSVLVITSLGATAGGLGGFLAAYF
Helix 8: LGMLLNGILAGLVGITAGA
Helix 9: AAALLIGFIAGILVVISAVMLD
Helix 10: VVGAVSVHLTCGIWGTLAVGIF
Helix 11: LIGVAICGAVAFGAAFLIFYIL

Query ID: F2NNQ0
Helix 1: TAWMLISTALVLLMTPGLAFFYGGL
Helix 2: MSFAALGAVGMSWVLVGYSLA
Helix 3: VAFQGTFAIIAAALISGGIV
Helix 4: AYLAFITLWSLTVYAPLAHWV
Helix 5: FAGGTVVHINAGVAALVAALVV
Helix 6: LPHNVPFVLLGAALLWFGWFGF
Helix 7: AALAFTNTFLAPAATLVVWGAL
Helix 8: RITAVGAATAIVVGLVAVTPAAG
Helix 9: GALWIGALAAFPSYLFILW
Helix 10: VFGTHGLGGITGALLTGVLASAEW
Helix 11: AVLYAVGYSAAATFVLLRLVG

Query ID: F2JYR9
Helix 1: FYWWCTAIMIMIHAGFLAYEM
Helix 2: GVKNVLALAVIIPTFYLFGWWIY
Helix 3: GIFWAAFALFGATTGSILSGAVI
Helix 4: AFLILTVVLGSAVWILAGAWGW
Helix 5: VVHAVAGFFTLGVLINLGA
Helix 6: TLIGLMMIIFGFFGFLGGCIIFNG
Helix 7: LSAFAFNTLMGFAGGVIGCY
Helix 8: FWTMSGGLCGIISVAAGL
Helix 9: ALAFIIATSMGFIAVKVA
Helix 10: VGAVTVHGFVGFVAVILVGVFAGG
Helix 11: LYGQTVAAVVMAVVGFLPGYLIS

Query ID: F2JZ83
Helix 1: FFILLGAIMVFAMHAGFAFL
Helix 2: FAISALVYFFIGYQIAYGINFF
Helix 3: YALVKFFFLMTFAAAIPAIIS
Helix 4: MLISAAVIVGVAYPFLEGLIWN
Helix 5: FAGSIVVHGFGGWVALAAIILL
Helix 6: LVAFAPSNIPFLALGAWILCIGWFG
Helix 7: ISGLVAVNSLMAMVGGIIAAMIL
Helix 8: FIHNGPLAGLVAVCAGSDI
Helix 9: ALATGLVAGALFTWLFTLI
Helix 10: GVWPLHGICGAWGGIAAGIFG
Helix 11: FLSQLVGSAIGISIALVSGFVVY

Query ID: F2JTN3
Helix 1: FYFLVCGALVMWMAAGFAMLEAGLV
Helix 2: NVALFAISCIMYLVVGYHIM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WAFLAFAVVMTAVIYPLEGGWT
Helix 5: FAGSGIVHMAGAAAALAGVLVL
Helix 6: LPLATLGTFILWMGWFGF
Helix 7: VFLNTNAAAAGGAIAALILA
Helix 8: ADLTMLLNGALAGLVAITA
Helix 9: SALGATLIGVVGGLIVVVSILTL
Helix 10: ISVHGVVGVWGLLAVPLT
Helix 11: FGGQIAGALTIFVWVFVASLVVWLII

Query ID: Q0F2M7
Helix 1: AWMLTSTVLVLLMTLPGLALFY
Helix 2: VAMQSLSIAALMSILWVVCGYSLA
Helix 3: VFATFQMTFAIITPVLIIGAFA
Helix 4: AVLLFTGAWVLAVYAPITHWVWG
Helix 5: FAGGTVVHINAGVAGLVCALVL
Helix 6: LPHNLTYTLIGTSMLWVGWFGF
Helix 7: AGMAMLVTQVATAMAVLAWT
Helix 8: LLGACSGAVAGLVAITPAS
Helix 9: MGALAIGLAAGLICFWAVASL
Helix 10: AFGVHGIGGIVGALLTGVFV
Helix 11: IVQLEAIGATIAYCAVVTFVIL

Query ID: Q0F2M5
Helix 1: LDVFFLTMGAAMVLAMHAGFAFL
Helix 2: FGFSTIAYFFVGFSVAYGINFFV
Helix 3: FFFLLTFAAAIPAIISGGI
Helix 4: WPNALATLIIVSLIYPFYEGLIWG
Helix 5: FAGSVVVHSMGGFLAVGAVVLLG
Helix 6: VVAILPSNIPFLALGSWILCVGWFGF
Helix 7: SGLVAINSLLAMVGGLLAALVA
Helix 8: FVHNGALAGLVAICAGSDI
Helix 9: ALVIGLVAGACFVYGFQFV
Helix 10: VIPLHGGAGLWGGIAAGIFG
Helix 11: FMAQLVGTLTGVSIALVAGFVIYGLV

Query ID: A0A2R4MBA2
Helix 1: TSWILVASALVLLMTMPGLALFY
Helix 2: VLMHCVAIACVASILWVVAGYTLA
Helix 3: LWIMFQMTFAIITPALMVGAFV
Helix 4: AVLIISSLWLMLVYVPVTHWVWG
Helix 5: FAGGIVVHVTAGVSAAAIAVFLGA
Helix 6: HAPWMVMVGASLLWVGWFGF
Helix 7: ASMAILVTHLSAATASLVWMVIEWV
Helix 8: IVGIVTGTIAGLATITPAS
Helix 9: MGGIVLGLVGGFVCFYAVDLV
Helix 10: VLAVHGIGGATGTLLVALLLGFG
Helix 11: LVGVVATAIWSLLVTIILVWL

Query ID: E4TRS4
Helix 1: WMMLCIALVFIMHLGFACVEAGFT
Helix 2: NTLTPAIGLVSYTIIGFNLMY
Helix 3: FLFQAMFAATAATIVSGAVA
Helix 4: AYFIFTIIFVGFVYPAIGSW
Helix 5: LVHSVGGWGALAGIIVLGPRIG
Helix 6: GSSVPLATIGVFLLWFGWFGF
Helix 7: ATSLVIMNTSLAAAAGALGGFVMGYL
Helix 8: LGMVLNGTLAGLVGITAGA
Helix 9: GLSLLIGFIAGNLVVLSAIGL
Helix 10: VSVHLTCGIFGTLAVGIFG
Helix 11: LIGTAICGAAAFGCAIILFYLL

Query ID: A0A4R3NVT3
Helix 1: TLLFLIGGFLVMWMAAGFAMLEMGLV
Helix 2: NIALYSVGGIMFWFTGYNLM
Helix 3: WFFQMVFCATTASIVSGTVA
Helix 4: FWPFIIFTVILTGILYPI
Helix 5: AGSTLVHSVGGWAALAGAIVL
Helix 6: IPLAVLGTFILWLGWFGF
Helix 7: IFVNTNLAAAAGAVVAMILLQIIY
Helix 8: MVLNGALAGLVSITAEPL
Helix 9: MALFIGGIGGVIVVLVVPLLD
Helix 10: VVGAIPVHLVAGIWGTFIVAAT
Helix 11: YGVQLIGIVAIGAFTFIASLIVWFIL

Query ID: A0A1U9YY82
Helix 1: FNTLLFLIGGFLVMWMAAGFA
Helix 2: IALYAVGGIMFWFTGYNLMY
Helix 3: WFFQMVFCATTASIVSGTVA
Helix 4: FWPFIIFTVILTGILYPI
Helix 5: AGSTLVHSVGGWAALAGALVL
Helix 6: IPLAVLGTFILWLGWFGF
Helix 7: IFVNTNLAAAAGAVVTMILLQIVY
Helix 8: MVLNGALAGLVSITAEPL
Helix 9: AALFIGGIGGVIVIVVVPLLD
Helix 10: VVGAIPVHLVAGIWGTFIVP
Helix 11: IVGIVAIGAFTFIVSFVIWFIL

Query ID: A0A1U9Z147

Helix 1: AGDTAFVLICTALVCMMTPALALFYGGLV
Helix 2: NFVCIGIVSIIWVFGGFSLAFGPSIGGII
Helix 3: YAPHIPFMMVFAYQMMFAIITPALM
Helix 4: AYLFFVGLWTILVYLPAAHWIWG
Helix 5: FAGGIVIHTAAGFSALAAARFLG
Helix 6: QPASLPLVALGAGLLWFGWFGF
Helix 7: AAYAFTNTMLAGAIAMLVWMLW
Helix 8: RVSFSGVLVGAVTGLATITPAA
Helix 9: MAALLIGAIGATVCYNAKYV
Helix 10: VWRAHGVGGMTGAILIGFMASS
Helix 11: LGVQVLAVVIVAAYSWIITTILL

Query ID: C6LBD3
Helix 1: FAVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVVFIVIGFGLLLGEDVAGL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FLSYCVYSAVISAVIYPI
Helix 5: AGSNCIHMVGGISALIGAALL
Helix 6: FPGHNLPIGCLGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAIATVVCMIFTWI
Helix 8: VSMCLNASLAGLVAITAG
Helix 9: ATGSIIIGAVSGVLVVFGVWLL
Helix 10: AVAVHCLNGIWGTLAVGLFA
Helix 11: LGIQFVGMLSTAAWTAVTITITFLAI

Query ID: A0A7C3HEP6
Helix 1: TGWMLVATGLVLLMTPALAFFYG
Helix 2: MMMSFSALGFVAVTWTLLGYTLA
Helix 3: MLWMIFQGTFAIITAALVSGAVV
Helix 4: AFLLFITLWSLAVYAPLAKWVWG
Helix 5: FAGGTVVHINAGFAAVVAALVL
Helix 6: LPHNVPFVLLGAALLWFGWFGF
Helix 7: WAASATAGLAMTNTILAPAATIVI
Helix 8: VTAVGLATAIVVGLVVITPAA
Helix 9: LFAMVMGAIGAFPSYYVLLW
Helix 10: VFAAHGVGGITGAILTGVFA
Helix 11: LIQAFAVLIAMIYSGTITFLLL

Query ID: D3PKL4
Helix 1: TAWMLVATGLVLLMTPALAFFYG
Helix 2: MMMSFSALGFVAVAWALLGYTLA
Helix 3: MLWMIFQGTFAIITAALISGAVV
Helix 4: AFLLFITLWSLLVYAPIAKWVWG
Helix 5: FAGGTVVHINSGIAAVVAALVL
Helix 6: LPHNVPFVLLGAALLWFGWFGF
Helix 7: WAASATAGLALTNTILAPAATIVA
Helix 8: VTAVGLATAIVVGLVVITPAA
Helix 9: FYALVMGAIGAFPSYFVLLW
Helix 10: VFAAHGVGGITGAILTGVFA
Helix 11: LIQAFAVLIAVVYSGAITFVLL

Query ID: I6Z905
Helix 1: TMVAAFLVFFMQAGFAMVEAGLT
Helix 2: LIFWAIGFGIMFGTTTTGFF
Helix 3: AFWLFQVVFATTAATIVSGA
Helix 4: FIGYIAYSAVITAIIYPVF
Helix 5: FIDFAGSTVVHSVGGWAALAGAIVL
Helix 6: ITLAALGTFILWFGWFGF
Helix 7: IASIAVNTNLAAAGGAVAAMLTAWAVI
Helix 8: MAFNGALAGLVGITAGCANVS
Helix 9: IIGLTSGVIVVLSVIFV
Helix 10: AISVHGVCGAWGTLMAGVL
Helix 11: VQLLGIVSAFVWTFTTAFILF

Query ID: I6YYI6
Helix 1: WILISTALVFIMHLGFASLEA
Helix 2: LFKNSIIPGIGLLTYAFIGFNLMY
Helix 3: FLFQGMFAATAATIVSGAVA
Helix 4: SFLIFSTVFVAISYPITGMWKWG
Helix 5: FAGSTLVHSVGGWGALTGIILL
Helix 6: MPLATIGVFLLWLGWFGF
Helix 7: AVSLVLVTTSIAAAAGGIAAAFTSWLYL
Helix 8: MLLNGILAGLVGITAGADV
Helix 9: ALIVGGIAGVIVVFSVIIF
Helix 10: LSVHLVCGIWGTLAVGIFGQL
Helix 11: LINQFIGIVSVGVFTLVFTYILW

Query ID: A0A2T1N7R1
Helix 1: TNNVWMMICTALVFFMHLGFSLLEI
Helix 2: LFKNIFIICVGLLLYCLVGFNLMY
Helix 3: FLFQGMFAATAATIVSGAVA
Helix 4: PFMIFTIIYVGLVYPIAGSW
Helix 5: LVHSVGGWAALVAVWLLG
Helix 6: FVILGHNLPLATAGVLILWLGW
Helix 7: LVTTSLAAAAGGVSSFLISTLAY
Helix 8: MFLNGILGGLVGITAGADQ
Helix 9: AILIGVIAGGLIVGAVALV
Helix 10: IAVHLICGIWGTLAVGIFG
Helix 11: LIGVAAYAVFCLVTSFIILFTL

Query ID: L0KGR8
Helix 1: AWMLTSTALVLMMTIPGLALFYGG
Helix 2: VLATVMQSFAITCLVTVLWFMF
Helix 3: FVFSMFQMTFAIITPALIAGAFA
Helix 4: ALLIFMALWLLIVYVPIAHWVWG
Helix 5: FAGGTVVHINAGVAGLVCALVL
Helix 6: APHNLVYSVIGASLLWVGWFGF
Helix 7: AGAAMLNTQVATAAAALAWM
Helix 8: VLGIISGAVAGLVAVTPASGF
Helix 9: AFIVGIVAGVVCYLSAVKV
Helix 10: AFGVHGVGGVVGALLTGVLADPAI
Helix 11: QIYGVAVTIVWTAVATFVILYVV

Query ID: A0A088E6Q7
Helix 1: WILTATTLVMIQSVPALALFYA
Helix 2: VMMVLYSFASTFLVWTILGYSL
Helix 3: FLTFVMFQFAFAAITPGLMVGAIV
Helix 4: AWMLFSPIWIILVYAPVAYWLFA
Helix 5: YSGGYVIHMTAGYSALALAMAI
Helix 6: AHNLLLTALGFGLDWMGWNGF
Helix 7: AAIAVFNTNLAAAAAAITWMAI
Helix 8: GLANGAFAGLVAITPMAGMV
Helix 9: LVTGVVTAPVVWLGLYKLL
Helix 10: FPVHGIGGTVGGLLTGLMI
Helix 11: WHQFLVQALAVVVVGIYSFMVSFGLA

Query ID: A4YGZ2
Helix 1: WILTATTLVMIQSVPALALFYA
Helix 2: VMMVLYSFASTFLVWTILGYSL
Helix 3: FLTFVMFQFAFAAITPGLMVGAIV
Helix 4: AWMLFSPIWIILVYAPVAYWLFA
Helix 5: YSGGYVIHMTAGYSALALAMAI
Helix 6: AHNLLLTALGFGLDWMGWNGF
Helix 7: AAIAVFNTNLAAAAAAITWMAI
Helix 8: GLANGAFAGLVAITPMAGMV
Helix 9: LVTGVVTAPVVWLGLYKLL
Helix 10: FPVHGIGGTVGGLLTGLMI
Helix 11: WHQFLVQALAVVVVGIYSFMVSFGLA

Query ID: B9ACS5
Helix 1: VLICSLLVLLMSIPAVAFFYG
Helix 2: MFLTFIAFSIVSVIWVIFGYQFA
Helix 3: LLFVMFQLAFAGLTAALISGGVV
Helix 4: AWVIFIPIWACLVYIPIAHWVWG
Helix 5: FAGGTVVHINSGVSALAIALVLG
Helix 6: LGYAVLGAALLWFGWMGF
Helix 7: AANAIIVSNVAAAAALIVWTIL
Helix 8: TVLGAISGGIAGLVAITPAAGF
Helix 9: ALVIGAVAPLVSYFAIYYL
Helix 10: VFGIHGMSGIWGAIATGIFAAPYI
Helix 11: YQVVIQIISVVATIVYAFVISYVLA

Query ID: D2ZRW2
Helix 1: VLICSLLVLLMSIPAVAFFYG
Helix 2: MFLTFIAFSIVSVIWVIFGYQFA
Helix 3: LLFVMFQLAFAGLTAALISGGVV
Helix 4: AWVIFIPIWACLVYIPIAHWVWG
Helix 5: FAGGTVVHINSGVSALAIALVLG
Helix 6: LGYAVLGAALLWFGWMGF
Helix 7: AANAIIVSNVAAAAALIVWTIL
Helix 8: TVLGAISGGIAGLVAITPAAGF
Helix 9: ALVIGAVAPLVSYFAIYYL
Helix 10: VFGIHGMSGIWGAIATGIFAAPYI
Helix 11: YQVVIQIISVVATIVYAFVISYVLA

Query ID: A0A2H4U5R1
Helix 1: VLICSLLVLLMSIPAVAFFYG
Helix 2: MFLTFIAFSIVSVIWVIFGYQFA
Helix 3: LLFVMFQLAFAGLTAALISGGVV
Helix 4: AWVIFIPIWACLVYIPIAHWVWG
Helix 5: FAGGTVVHINSGVSALAIALVLG
Helix 6: LGYAVLGAALLWFGWMGF
Helix 7: AANAIIVSNVAAAAALIVWTIL
Helix 8: TVLGAISGGIAGLVAITPAAGF
Helix 9: ALVIGAVAPLVSYFAIYYL
Helix 10: VFGIHGMSGIWGAIATGIFAAPYI
Helix 11: YQVVIQIISVVATIVYAFVISYVLA

Query ID: R7PZ71
Helix 1: VLVCSLLVLLMSIPAVAFFYG
Helix 2: MFLTFIAFSIVSVIWVIFGYQFA
Helix 3: LLFVMFQLAFAGLTAALISGGVV
Helix 4: AWVIFIPIWACLVYIPIAHWVWG
Helix 5: FAGGTVVHINSGVSALAIALVLG
Helix 6: LGYAVLGAALLWFGWMGF
Helix 7: AANAIIVSNVAAAAALIVWTIL
Helix 8: TVLGAISGGIAGLVAITPAAGF
Helix 9: ALVIGAVAPLVSYFAIYYL
Helix 10: VFGIHGMSGIWGAIATGIFAAPYI
Helix 11: YQVVIQIISVVATIVYAFVISYVLA

Query ID: A5UJR1
Helix 1: VLVCSLLVLLMSIPAVAFFYG
Helix 2: MFLTFIAFSIVSVIWVIFGYQFA
Helix 3: LLFVMFQLAFAGLTAALISGGVV
Helix 4: AWVIFIPIWACLVYIPIAHWVWG
Helix 5: FAGGTVVHINSGVSALAIALVLG
Helix 6: LGYAVLGAALLWFGWMGF
Helix 7: AANAIIVSNVAAAAALIVWTIL
Helix 8: TVLGAISGGIAGLVAITPAAGF
Helix 9: ALVIGAVAPLVSYFAIYYL
Helix 10: VFGIHGMSGIWGAIATGIFAAPYI
Helix 11: YQVVIQIISVVATIVYAFVISYVLA

Query ID: Q58739
Helix 1: VFFLVVMGVLVFMMQWGFAML
Helix 2: NMVDWLIGCVAWLFIGGILCS
Helix 3: SWFFGLVFCATAATIVSGGVA
Helix 4: VLISLIITGLLYPLFVYLGPW
Helix 5: AGSLVVHGLGGFLALGAIAAL
Helix 6: IPMAVFGAFALAIGWYGFNVG
Helix 7: GLVCATTTMAMAGGGIGALIA
Helix 8: NDVLFTANGIVAGLVAICSGT
Helix 9: VVSPIGGLIIGLIAGLQVPIV
Helix 10: VIGAILTGILGLKIFGGAGGV
Helix 11: IIGAVFCIIYGTGLGYILAKI

Query ID: A0A832WGB6
Helix 1: VFFLVVMGVLVFMMQWGFAML
Helix 2: WLIGCVAWLFIGGILCSKGFDLSAFI
Helix 3: SWFFGLVFCATAATIVSGGVA
Helix 4: AYVLISLIITGLLYPLFVYLG
Helix 5: YAGSLVVHGLGGFLALGAIAALG
Helix 6: VPILGHNIPMAVFGAFALAIGWYG
Helix 7: ISGLVCATTTMAMAGGGIGAL
Helix 8: VLFTANGIVAGLVAICSGT
Helix 9: IGGLIIGLIAGLQVPIVYKLV
Helix 10: VPVHGTAGVIGAILTGILGLKIF
Helix 11: IIGAVFCIIYGTGLGYILAKIVGIALGGL

Query ID: G0H0Z6
Helix 1: VMFLIFTGAFIFIMHLGFAML
Helix 2: WIIGCISWLLVGSVIARTL
Helix 3: LANWFLGLVFAATAATIVAGGIA
Helix 4: SYILISIVITALLYPFFSYLG
Helix 5: YAGSLMVHGVGGFLALGLIAAI
Helix 6: IPMSILGAYILAFGWYGF
Helix 7: LALSDISGLVCATTTLAMAGG
Helix 8: VLYTANGLLAGTVAICAGTDI
Helix 9: ALIIGFIAGSQVPLIFKIV
Helix 10: IPVHATSGALGAILAGIFGMTAF
Helix 11: IIATLICAVYGTGAGFILGKLV

Query ID: A0A7J9P8J7
Helix 1: VMFLIFTGAFIFIMHLGFAML
Helix 2: WIIGCISWLLVGSVIARTL
Helix 3: LANWFLGLVFAATAATIVAGGIA
Helix 4: SYILISIVITALLYPFFSYLG
Helix 5: YAGSLMVHGVGGFLALGLIAAI
Helix 6: IPMSILGAYILAFGWYGF
Helix 7: LALSDISGLVCATTTLAMAGG
Helix 8: VLYTANGLLAGTVAICAGTDI
Helix 9: ALIIGFIAGSQVPLIFKIV
Helix 10: IPVHATSGALGAILAGIFGMTAF
Helix 11: IIATLICAVYGTGAGFILGKLV

Query ID: A2SS52
Helix 1: SVAWVLASTALVLLMTPALGLFY
Helix 2: VLMLVFASLMIVILQWFLLGYSLV
Helix 3: LLFAAFQMTFAGLTLAIIVSGVA
Helix 4: AFLLFGVLWTTFVYDPIAHWLWG
Helix 5: FAGGTVVHISAGFGALALAIYIG
Helix 6: PQNIPLTFFAGGVLLFGWMGF
Helix 7: AIHAIMVTLISAAAGTISWM
Helix 8: LGFISGTIAGLGAITPAA
Helix 9: WAALLIGTVAGILCYYALIW
Helix 10: FWGTIACGIFATAAVGGVSGLI
Helix 11: LLGIQILDACVTAVFAFGVTYLLAWVV

Query ID: A2SPS8
Helix 1: LISAALVLMMVPAVGLFYGGM
Helix 2: LSFVALALGIVQWIIIGYSLAFGADVAGVIGWSL
Helix 3: ILFICFQMMFACLALAILTSGIVG
Helix 4: YIVVGLLWLTLVYAPLAHWAWG
Helix 5: FAGGTVVHISSGFAALALALVIG
Helix 6: PHNIPMTLIGGMFLIVGWFGF
Helix 7: AASAFLVTAAAAATGALTWMAL
Helix 8: FISGAIAGLVGITPAAGYV
Helix 9: LLIGIITAAVCYAALSWRI
Helix 10: AIHGMGGFAGAILTGVFAVSAICGVGGL
Helix 11: ILDAVIAVVYAFGMTFIIGWII

Query ID: A0A831PTC2
Helix 1: FIWVLICGFLVMFMQAGFSMV
Helix 2: FSIGALSYWAVGFAIMYGTM
Helix 3: WFFQMVFAATAATIVSGAVA
Helix 4: TYILASVAITALIYPLYGHWIWG
Helix 5: FAGSGVVHALGGWVALAGALLL
Helix 6: VTLGILGVFILWFGWYGF
Helix 7: RISIIATNTTLAAAAAMVTAMIFTWL
Helix 8: VSMAGNAAIAGLVAITAGCAW
Helix 9: AVLIGIVGGILVVLGVWFL
Helix 10: AWGLIALGIFADGTYGGVAGLLF
Helix 11: FTAQVISTVVNFAWAFGMGLLVFGIL

Query ID: A0A831LSC0
Helix 1: FISTALVMLMTPAVGLFYGG
Helix 2: IISMIALSFIAFSLVTVQWML
Helix 3: IPHLLFMAFQLTFAGVTLAIVT
Helix 4: FIVFGLLWTTLVYDPIAHWAWG
Helix 5: LAGGMAVEICSGFAALALCLVIG
Helix 6: PHNIPMTLIGGALLWFGWFGF
Helix 7: AANALVTTNAAAAAGALAWLFASWY
Helix 8: LGMISGAIGGLVAITPAA
Helix 9: MGALAIGAVAGLLCYGAMLL
Helix 10: LWGTVATGVFAVTAVGGTAGLLA
Helix 11: LLVQIVCALAAMAYAFGMTYLLA

Query ID: J0S2I0

Helix 1: FIWVLICGFLVMFMQAGFSMV
Helix 2: FSIGALSYWAVGFAIMYGTM
Helix 3: WFFQMVFAATAATIVSGAVA
Helix 4: TYILASVAITALIYPLYGHWIWG
Helix 5: FAGSGVVHALGGWVALAGALLL
Helix 6: VTLGILGVFILWFGWYGF
Helix 7: RISVIAANTTLAAAAAMLTAMAFTWLW
Helix 8: AAIAGLVAITAGCAWVN
Helix 9: LIGVIAGILVVVGVWFL
Helix 10: AWGLIALGIFADGTYGGVAGLLF
Helix 11: FTAQVISTVVNFAWAFGMGLLVFGIL

Query ID: J1ASR8
Helix 1: GDTAFILICTAMVMLMTPGVGLFYGG
Helix 2: IIAMITLAFIAFSVVSLQWIL
Helix 3: LLFMVFQLVFAGLTLAIVT
Helix 4: FIVFGLLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVHISSGFGALALALVIG
Helix 6: PHNIPLTLIGGALLWFGWFGF
Helix 7: AASAFVVTNTSAAAGAIAWLVASWY
Helix 8: LGMISGAIAGLVAITPAA
Helix 9: VSAIAIGGVAGLLCYGAMLF
Helix 10: LWGAIATGIFAVAAVGGVDGLLY
Helix 11: FVIQVVDAGAALVYAFGMTYALAWIV

Query ID: J1L5M8
Helix 1: AFVFISTALVMLMTPAVGLFYGG
Helix 2: IISMIALSFIAFSLVTVQWML
Helix 3: IPGLLFMAFQLTFAGVTLAIVT
Helix 4: FIVFGLLWTTLVYDPIAHWAWG
Helix 5: LAGGMAVEICSGFAALALCLVIG
Helix 6: PHNIPMTLIGGALLWFGWFGF
Helix 7: AANALVTTNAAAAAGALAWLFASWY
Helix 8: LGMISGAIGGLVAITPAA
Helix 9: MGALAIGAVAGLLCYGAMLL
Helix 10: LWGTVATGVFAVAAVGGTAGLLA
Helix 11: LLVQVVCALAAMAYAFGMTYLLA

Query ID: D7E934
Helix 1: TLTFVWLILSGAIVFLMHAGF
Helix 2: FMTISLGVLVYWAVGWAIM
Helix 3: WWFQMVFAATAATIVSGAVA
Helix 4: AYLIYAILMVALIYPVYGHWVW
Helix 5: FAGSSVVHAVGGYAALAAVIIL
Helix 6: LAYAFLGTLILAFGWIGF
Helix 7: YMNLVIVNTFIAAAAGAVSAMLV
Helix 8: LTANGLLAGLVAITAPC
Helix 9: WAALIIGTIGGIIVYAGVMF
Helix 10: GSWGLLSVGIFSVGLGNGIL
Helix 11: FLIQLVGVIVNIIWAFGASFFIF

Query ID: D5E995
Helix 1: FVWLLIASALVFFMHTGFSLV
Helix 2: ITLGILIYWAVGWGVMYGADAAG
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVFCILMVAIIYPVYGHWVW
Helix 5: IGGYAALAGVLLVGARVG
Helix 6: GHNLTFAFMGTLILALGWMGF
Helix 7: YMNLVLVNTFLSAAAGAIMVMLI
Helix 8: LTANGLLGGLVAITAPCG
Helix 9: ASILIGIVGGIIIYAGVMF
Helix 10: GAVAVHGYCGSWGLLSVGLFSI
Helix 11: FYGGGVGLLAIQAVGVILSIVWAFGISYIVF

Query ID: L0KW14
Helix 1: GDTAFILICTAMVMLMTPGVGLFYGG
Helix 2: VISMIAMSFIAFAIVTIQWV
Helix 3: ILFMVFQLVFAGVTLAILT
Helix 4: FIVLGVLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVHISSGFGALALALVIG
Helix 6: AENISLTLIGGALLWFGWFAF
Helix 7: AANAFVVTNISAASGALTWMLA
Helix 8: PSSLGMVSGAVAGLVAI
Helix 9: FVGPMAAIAIGGIAGVLCYRMLL
Helix 10: GLWGALATGIFASASIGGVDGLIY
Helix 11: FLIQALDAGVAITYAFVVTYILA

Query ID: A7I8Z2
Helix 1: GAIAWVLASTALVMIMTPGVGFFY
Helix 2: MITLSFVAFALVSIQWVLFGYSLA
Helix 3: GMLYMVFQLVFATVTMAIVT
Helix 4: YLIFALIWTTIVYDPLAHWVWG
Helix 5: FAGGTVVHISSGFAALALALVIG
Helix 6: PANIPWSILGAVLLWFGWFGF
Helix 7: AVNAFVTTNTATAVAAMAWLL
Helix 8: LGFISGAVAGLVAITPAA
Helix 9: MASIAIGAVAGVMCYFIMLW
Helix 10: AWAVHGMGGLWGAIATGIFASA
Helix 11: IVGAGSAVIYAFVVTYILAVIV

Query ID: A7I8Z4
Helix 1: MVSALLVMLMTPGVGFFYGG
Helix 2: FISMIALSFLVLSLTSIQWIL
Helix 3: LVYMVFQLFFASVTLTIVTSAVA
Helix 4: SFIVFSLIWLTIVYCPIAHWAWG
Helix 5: FAGGTVVEICSGFAALALAMVIG
Helix 6: PHNIPIALLGAALLWFGWFGF
Helix 7: LAVNASAVTAFVNTNTAAAAGALAW
Helix 8: SLGMVSGAIAGMVAITPAA
Helix 9: LVAVLIGAVAGVLCFGMMLL
Helix 10: VWGTLATGLFAAAAVAGFSGFF
Helix 11: IGALAAVAYAFVMTFVIAWIL

Query ID: F7XP68
Helix 1: MDVWFMLMLVAFLMLFI
Helix 2: ICLATLLVLAGSFITYMAIQ
Helix 3: LMILSIFCSITVVIAIGVFLG
Helix 4: YFLAGILFAPAWIAIDWFMF
Helix 5: SMLVHMVAAYWGWGVILAL
Helix 6: VWLASMLLFVLWPSFVTALLP
Helix 7: WGMFTAYMAGLGSIIAAYFTCMLL
Helix 8: LVYTYALLAGLVAIGSPLI
Helix 9: TALGIGLVAGTVSVFCFV
Helix 10: VLDVMGVHNLHGVPGIVGAIFGAIFA
Helix 11: IISLVGVLILSLVTGAITGLIL

Query ID: F7XMD8
Helix 1: ALTFVWIILAGAIVFFMHAGF
Helix 2: LITISLGVVIYWLVGWGIMYGASAYG
Helix 3: WWFQMVFAATGATIVSGTMA
Helix 4: GYLAFTILMVAFIYPIHGHWV
Helix 5: ISILAGSASPLVMAVGAGL
Helix 6: IGGYAALAGAMVVGARLG
Helix 7: GHNLTFAFLGTLILAFGWVGF
Helix 8: YMNLVIVNTFLSGAAGALTVLLITWF
Helix 9: VANWSALVIGIIGGIILYAGV
Helix 10: YAGSWGLLSVGIFSIGMGNGIL
Helix 11: FAIQLIGVVVSIVWAFGLSYILF

Query ID: A0A0G3C9G5
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVYCVMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVILVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAAAVGALTVMII
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALVIGLVAGIIIYVGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSI
Helix 11: FYGGGISLLLIQLVSVLVTMVWGFGISYIIF

Query ID: A0A0G3CAR5
Helix 1: VAINIMWTLLAGFLVMFMQAGF
Helix 2: FFVYPLGMLGFFLTGFAIMFGGFGPLAT
Helix 3: FGLFGMTGFALIGTYDVGVFALFLFQ
Helix 4: FLAFCFMGFAIGAFIYPLFGNWVWG
Helix 5: FAGSSVVHMTGGVIGLVGAWII
Helix 6: IPMAIIGTFILAFGWFGF
Helix 7: RLAVVATNTMLASATGAIAATAWMW
Helix 8: ACNGMLAGLVAITAPCAF
Helix 9: AAIIGLVSGILVVESVFFI
Helix 10: AVSVHMVNGAWGCLALGLFA
Helix 11: FVAQLIGVATNFIVVGGLAFIIY

Query ID: A0A0G3CJ36
Helix 1: LISSALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAYVAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGISSLAILTYLG
Helix 6: PHNVTLTLLGTGLLWFGWFG
Helix 7: IASLAFITTLVAPAAAGFVWM
Helix 8: LGYPTALGFATGILAGLVAI
Helix 9: FVTPMAAIPIGAITSFVCYNAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVVTIVYAAAGTLLIGFIL

Query ID: A0A2U1SS17
Helix 1: LISAALVLMMSVPGLALFYGGL
Helix 2: LSVLTQTFAIVALVGVVWTLY
Helix 3: YAYFVFQMTFAMITPALIIGAFA
Helix 4: AAFVFVLLWVTIIYFPVAHWVW
Helix 5: FAGGTVVHINAGIAGFVGALILG
Helix 6: PHSLTLSMVGASLLWVGWFGF
Helix 7: TALAFVNTMVATAAAALSWL
Helix 8: LLGLISGAVAGLVAVTPAS
Helix 9: IGSIALGFIVSPISLFFVS
Helix 10: LDVFGVHAIGGITGALATGILV
Helix 11: MISQATAVGATILYSGIGSAILY

Query ID: A0A0E3QYF3
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVYCVMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVILVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAAAVGALTVMII
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALVIGLVAGIIIYVGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSI
Helix 11: FYGGGISLLLIQLVSVLVTMVWGFGISYIIF

Query ID: A0A0E3R6S1
Helix 1: LLATSLVMLMTPGLAFFYGGL
Helix 2: LGIMMQSFVSMGVTTVLWFFI
Helix 3: IVFVAYQMMFAIITPALITGAFA
Helix 4: AYLIFLVLWQLFVYYPFVHMVWG
Helix 5: FAGGIVVHATAGFAALASVFYVG
Helix 6: NVPLMAIGTALLWFGWYGF
Helix 7: TSLAFLNSDIAASFAAITWM
Helix 8: FVGLMTGAVAGLATITPAAG
Helix 9: VAALMGILGSVVCYFAVHL
Helix 10: VWGVHGIGGVTGTILLGVFASTAI
Helix 11: VVVVAATSVYAFVFTYIMLMLI

Query ID: A0A0E3R4G0
Helix 1: VAINIMWTLLAGFLVMFMQAGF
Helix 2: FFVYPLGMLGFFLTGFAIMFGGFGPLAT
Helix 3: FGLFGMTGFALIGTYDVGVFALFLFQ
Helix 4: FLAFCLMGFAIGAFIYPLFGNWVWG
Helix 5: FAGSSVVHMTGGVIGLVGAWII
Helix 6: IPMAIIGTFILAFGWFGF
Helix 7: RLAVVATNTMLASATGAIAATAWMW
Helix 8: ACNGMLAGLVAITAPCAF
Helix 9: AAIIGLVSGILVVESVFFI
Helix 10: AVSVHMVNGAWGCLALGLFA
Helix 11: FVAQLIGVATNFIVVGGLAFIIY

Query ID: A0A0E3SHQ9
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: IWNSWFFQMVFAATGATIVS
Helix 4: YLVYCVMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVLLVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAGAAGALTVMVI
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALAIGLVAGIIIYAGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSIGIGNGIL
Helix 11: LFYGGGISLLLIQLVSVLVTMVWGFGLSYIIF

Query ID: A0A0E3LMT4
Helix 1: VAINIMWTLLAGFLVMFMQAGF
Helix 2: FFVYPLGMLGFFLTGFAIMFGGFGPLAT
Helix 3: FGLFGMTGFALIGTYDVGVFALFLFQ
Helix 4: FLAFCFMGFAIGAFIYPLFGNWVWG
Helix 5: FAGSSVVHMTGGVIGLVGAWII
Helix 6: IPMAIIGTFILAFGWFGF
Helix 7: RLAVVATNTMLASATGAIAATAWMW
Helix 8: ACNGMLAGLVAITAPCAF
Helix 9: AAIIGLVSGILVVESVFFI
Helix 10: AVSVHMVNGAWGCLALGLFA
Helix 11: FVAQLIGVATNFIVVGGLAFIIY

Query ID: A0A0E3QUS2
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVYCVMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVILVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAAAVGALTVMII
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALVIGLVAGIIIYVGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSI
Helix 11: FYGGGISLLLIQLVSVLVTMVWGFGISYIIF

Query ID: A0A0E3WZH5
Helix 1: VAINIMWTLLAGFLVMFMQAGF
Helix 2: FFVYPLGMLGFFLTGFAIMFGGIGPLAT
Helix 3: FGLFGMTGFGLIGTYDVGVFALFLFQ
Helix 4: FLSFCFMGFAIGAFIYPLFGNWVWG
Helix 5: FAGSSVVHMTGGVIGLVGAWLI
Helix 6: IPMAIVGTFILAFGWFGF
Helix 7: RLAVVATNTMLASATGAVAATAWMW
Helix 8: ACNGMLAGLVAITAPCAF
Helix 9: AAVIGLVSGVLVVESVFFV
Helix 10: AVSVHMVNGAWGCLALGLFA
Helix 11: FIAEFIGVATNFIVVGGLAFIIY

Query ID: A0A0E3QY45
Helix 1: LLATSLVMLMTPGLAFFYGGL
Helix 2: LGIMMQSFVSMGVTTVLWFFI
Helix 3: IVFVAYQMMFAIITPALITGAFA
Helix 4: AYLIFLVLWQLFVYYPFVHMVWG
Helix 5: FAGGIVVHATAGFAALASVFYVG
Helix 6: NVPLMAIGTALLWFGWYGF
Helix 7: TSLAFLNSDIAASFAAITWM
Helix 8: FVGLMTGAVAGLATITPAAG
Helix 9: VAALMGILGSVVCYFAVHL
Helix 10: VWGVHGIGGVTGTILLGVFASTAI
Helix 11: VVVVAATSVYAFVFTYIMLMLI

Query ID: A0A0E3SP24
Helix 1: LISAALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAFIAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGVSSLAILTYIG
Helix 6: PHNVTLTLLGGGLLWFGWFG
Helix 7: IAALAFITTLIAPAAAGFVWM
Helix 8: FGYPTALGFATGVLAGLVAI
Helix 9: FVTPMAAIPIGMITSFVCYKAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVITIVYAAVGTLLIGFIL

Query ID: A0A0E3R6E1

Helix 1: LISSALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAYVAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGISSLAILTYLG
Helix 6: PHNVTLTLLGTGLLWFGWFG
Helix 7: IASLAFITTLVAPAAAGFVWM
Helix 8: LGYPTALGFATGILAGLVAI
Helix 9: FVTPMAAIPIGAITSFVCYNAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVVTIVYAAAGTLLIGFIL

Query ID: A0A0E3QY86
Helix 1: LISSALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAYVAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGISSLAILTYLG
Helix 6: PHNVTLTLLGTGLLWFGWFG
Helix 7: IASLAFITTLVAPAAAGFVWM
Helix 8: LGYPTALGFATGILAGLVAI
Helix 9: FVTPMAAIPIGAITSFVCYNAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVVTIVYAAAGTLLIGFIL

Query ID: A0A0E3QJ16
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVYCIMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVILVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAAAAGALMVMII
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALVIGLVAGIIIYVGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSI
Helix 11: FYGGGISLLLIQLVSVLVTMVWGFGISYIIF

Query ID: A0A0E3QKN0
Helix 1: LISSALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAYVAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGVSSLAILTYLG
Helix 6: PHNVTLTLLGTGLLWFGWFG
Helix 7: IASLAFITTLVAPAAAGFIWM
Helix 8: LGYPTALGFATGILAGLVAI
Helix 9: FVTPMAAIPIGAITSFVCYNAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVVTIVYAAVGTLLIGFIL

Query ID: Q466Y3
Helix 1: TLTFMWLLLASGLVFFMHAGF
Helix 2: FMTVVLGILVYWAVGWGIMYGA
Helix 3: WFFQMVFAATGATIVSGAMA
Helix 4: AYLVYCIMMVAVIYPIYGHWVW
Helix 5: IGGYSALAGVILVGARIG
Helix 6: GHNLTITFLGTLILALGWLGF
Helix 7: YMNLVVVNTFLAAAAGALMVMII
Helix 8: LTANGLLGGLVAVTAPC
Helix 9: WAALVIGLVAGIIIYVGVMF
Helix 10: GAIAVHGYCGSWGLISVGLFSI
Helix 11: FYGGGISLLLIQLVSVLVTMVWGFGISYIIF

Query ID: Q46G49
Helix 1: LISSALVLLMLPGLALFYGGLV
Helix 2: SFVAMGVMALEWVLIGYSLAFA
Helix 3: YAYVAFQGMFAIITPALISGAIVG
Helix 4: YIAFIALWGLIVYAPVCHWVW
Helix 5: FAGGTVVHITSGVSSLAILTYLG
Helix 6: PHNVTLTLLGTGLLWFGWFG
Helix 7: IASLAFITTLVAPAAAGFIWM
Helix 8: LGYPTALGFATGILAGLVAI
Helix 9: FVTPMAAIPIGAITSFVCYNAV
Helix 10: LDAFGVHGVGGIVGALLVGVFASVG
Helix 11: MLIQLQGVVVTIVYAAVGTLLIGFIL

Query ID: A0A328Q6M1
Helix 1: TAWILMSTALVMIMTLPGLALFY
Helix 2: TMFLSLTGFAIASVIWIAY
Helix 3: LLYVVFQATFAAITVALISGAVV
Helix 4: AWMVFVALWLTLVYVPIAHWVWG
Helix 5: FAGGAVVHLNSGIAALALITVLG
Helix 6: LGYAVIGAALLWFGWFGF
Helix 7: AANAFITTNTAAAMAMIAWILLDIW
Helix 8: ILGAITGAVAGLVAITPAAGFV
Helix 9: LIIGFTTVFVSYFGISYL
Helix 10: TWGAILTGVFACPAINEAAGLLY
Helix 11: LVIQIISIVAVALYSFIVTYIIA

Query ID: Q2NGJ2
Helix 1: TAWILMSTALVMIMTLPGLALFY
Helix 2: TMFLSLTGFAIASVIWIAY
Helix 3: LLYVVFQATFAAITVALISGAVV
Helix 4: AWMVFVALWLTLVYVPIAHWVWG
Helix 5: FAGGAVVHLNSGIAALALITVLG
Helix 6: LGYAVIGAALLWFGWFGF
Helix 7: AANAFITTNTAAAMAMIAWILLDIW
Helix 8: ILGAITGAVAGLVAITPAAGFV
Helix 9: LIIGFTTVFVSYFGISYL
Helix 10: TWGAILTGVFACPAINEAAGLLY
Helix 11: LVIQIISIVAVALYSFIVTYIIA

Query ID: B8GGC1
Helix 1: GATAWILAATALVFVMTPGVGFFY
Helix 2: MIALSFLAFALVSVQWVICGYSLA
Helix 3: LIYPPILFVMWQLVFATVTLAILT
Helix 4: FIVLGLLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVHISSGFGALALALVIG
Helix 6: PHNIPMTLLGATMLWFGWFGF
Helix 7: AGSAFLVTNTAAAIGALAWL
Helix 8: LGMVSGGIAGLVAITPAAG
Helix 9: AALVIGAVAGVLCYGCMLL
Helix 10: AWAIHGMGGLWGALATGIFATA
Helix 11: AMGAFAAVAYAFVVTYILATIV

Query ID: B8GGC3
Helix 1: LIATALVMFMTPGVGLFYGG
Helix 2: FISMIALSFIALAVVTVQWVF
Helix 3: ILFAAFQLTFAAVTLAVIT
Helix 4: FIVLALLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVEINSGFSALALAFVIG
Helix 6: PHNIPMALLGAAILWFGWFG
Helix 7: IAANAFMVTNVAAAVGALAWL
Helix 8: LGMVTGAVAGLVAITPAA
Helix 9: LAAVVIGGVAGVLCYKAMLF
Helix 10: AWAVHGVGGLWGMLATGIFATV
Helix 11: VLAAGVVLVYAFVASYLIGWVV

Query ID: A0A8F5VN39
Helix 1: TAFVLICTTLVILMTFGVGFFYAG
Helix 2: IISMITLSFISFALISLQWMF
Helix 3: MVFMVFQMAFAAITLAIVTSAVA
Helix 4: SFLIFGLAWSTFIYDPVAHWVWG
Helix 5: FAGGIVVHICAGFSALALAFVIG
Helix 6: PYNIPITLLGGAMLWFGWFGF
Helix 7: LSVNAVAINAFVVTNISAAAGTFSYM
Helix 8: LSMISGTIAGLGAITPAAGF
Helix 9: AFIIGTISGIICYYALVF
Helix 10: LWGTIAAGIFATATIGGVNGLIA
Helix 11: VITQAGGAFIILAYSFIGTWILALAI

Query ID: A0A8F5ZDT8
Helix 1: GATAWILASTCLVMLMTPGVGLFYGG
Helix 2: VISMVALAFLCYALVSVQWVF
Helix 3: ILFAAFQLVFAALTLAILTSGVA
Helix 4: AFVLFGLLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVHISSGFGALAIALVI
Helix 6: LLGAALLWFGWFGFNAGSAIAA
Helix 7: NAFMVTNTAAAAGALTWLLA
Helix 8: SVGMVSGAIAGLVGITPAAG
Helix 9: AALIIGAVAGLICYSALLW
Helix 10: AWAIHGVGGLWGAIATGIFASV
Helix 11: ALIAAAYAFVVTYILALVI

Query ID: Q2FS34
Helix 1: GATAWILASTCLVMLMTPGVGLFYGG
Helix 2: VIAMVALAFLSYALVSVQWVF
Helix 3: ILFAAFQLVFAALTLAILTSGVA
Helix 4: AFVVFGLLWTTLVYDPLAHWAWG
Helix 5: FAGGTVVHISSGFGALAIALVI
Helix 6: LLGAALLWFGWFGFNAGSAIAA
Helix 7: NALMVTNTAAAAGALTWLLA
Helix 8: MVSGAIAGLVGITPAAGFV
Helix 9: LVIGGVAGLICYGALLW
Helix 10: AWAIHGVGGLWGAIATGIFASV
Helix 11: ALIAVGYAFVVTYILAMII

Query ID: Q2FQT3
Helix 1: TAFVLLCTALVILMTFGVGFFYAG
Helix 2: IISMITLSFISFALISLQWIF
Helix 3: MVFMVFQMAFAGITLAIVTSAVA
Helix 4: SFLLFGLAWSTIIYDPIAHWVWG
Helix 5: FAGGIVVHICAGFSALALAFVIG
Helix 6: PYNIPLTLLGGGLLWFGWFGF
Helix 7: LAVNTIAVNAFIVTNISAAAGTFSYM
Helix 8: LSMISGTIAGLGAITPAAGF
Helix 9: AFIIGTVSGIICYYALVF
Helix 10: LWGTLAAGIFATAAIGGVNGLIA
Helix 11: LITQAGAAFVILAYSFIGTWILALAI

Query ID: O26757
query O26757 has 12, using last 11 helices
Helix 1: FVSLGIVSLLWFLFGYGLIFG
Helix 2: VSGIIGSHQVGISLINLGSAS
Helix 3: FAIFQMTFAAITVALISGAVV
Helix 4: WILFIPLWFALVYVPVAHWVW
Helix 5: FAGGIVVHITSGIAALALALV
Helix 6: LGYSVIGTGLLWFGWFGFNAG
Helix 7: ANAMIVTNTSAAAGMIGWILM
Helix 8: LGALSGAVAGLASITPAAGFV
Helix 9: IGASIVTGLVAAVICYLAVSW
Helix 10: VFGIHGVSGIIGTLGVGLFAV
Helix 11: IGVVTVTVYTFVVTYILAMLL

Query ID: O26759
Helix 1: AWMLVSTALVMLMTVPGVALF
Helix 2: VLNTMFLSLIAFAVTSIIWVL
Helix 3: FAFGADIMGFIGSPVNLLMNG
Helix 4: FLYIAFQLTFAAITVALISGA
Helix 5: WLAFIVLWVSLVYVPVAHWVW
Helix 6: FAGGTVVHINSGVAALALVYL
Helix 7: LGYSVIGASLLWFGWFGFNAG
Helix 8: ASAFLVTNTAAAAGMVSWVIM
Helix 9: VAITPAAGFVTVPAALIIGLV
Helix 10: VFGIHGMSGIWGSVATGLFAA
Helix 11: AQVIAVAVVAAYSFVVTLIIG

Query ID: A0A842YNC7
Helix 1: WMLVSTALVMLMTVPGVALFYGGL
Helix 2: VLNTMFLSLIAFAVTSIIWVLY
Helix 3: FLYIAFQLTFAAITVALISGAVV
Helix 4: AWLAFIVLWVSLVYVPVAHWVWG
Helix 5: FAGGTVVHINSGVAALALVYLLG
Helix 6: LGYSVIGASLLWFGWFGF
Helix 7: LTAGGLAASAFLVTNTAAAAGMVSWV
Helix 8: VLGGISGAVAGLVAITPAAG
Helix 9: AALIIGLVTSVISYLAVSYL
Helix 10: VFGIHGMSGIWGSVATGLFAAPFI
Helix 11: LAVAVVAAYSFVVTLIIGKLL

Query ID: A0A7J4MVN6
Helix 1: WMLVSTALVMLMTVPGVALFYGGL
Helix 2: VLNTMFLSLIAFAVTSIIWVLY
Helix 3: FLYIAFQLTFAAITVALISGAVV
Helix 4: AWLAFIVLWVSLVYVPVAHWVWG
Helix 5: FAGGTVVHINSGVAALALVYLLG
Helix 6: LGYSVIGASLLWFGWFGF
Helix 7: LTAGGLAASAFLVTNTAAAAGMVSWV
Helix 8: VLGGISGAVAGLVAITPAAG
Helix 9: AALIIGLVTSVISYLAVSYL
Helix 10: VFGIHGMSGIWGSVATGLFAAPFI
Helix 11: IAVAVVAAYSFVVTLIIGKLL

Query ID: A0A842YPK2
Helix 1: LISTALVILMTVPGVAMFYS
Helix 2: IFLSFVSLGIVSLLWFLFGYGLI
Helix 3: LFAIFQMTFAAITVALISGAVV
Helix 4: SWILFIPLWFALVYVPVAHWVWG
Helix 5: FAGGIVVHITSGIAALALALVTG
Helix 6: LGYSVIGTGLLWFGWFGF
Helix 7: AVNAMIVTNTSAAAGMIGWIL
Helix 8: LGALSGAVTGLASITPAAGFV
Helix 9: TVTGLVAAVICYLAVSWL
Helix 10: VFGIHGVSGIIGTLGVGLFAV
Helix 11: LVSQLIGVVTVTVYTFIVTYLLAMLL

Query ID: A0A832YRB5
Helix 1: VFFLVVMGVLVFMMQWGFAML
Helix 2: WLIGCVSWLFIGSVLAVSI
Helix 3: WFFGLVFAATAATIVSGGVA
Helix 4: AYVLISIVITALLYPLFVYLG
Helix 5: YAGSLIVHGLGGFLSLGAIAALG
Helix 6: VPILGHNIPMAVFGALALAIGWYG
Helix 7: VSGLVCATTTLAMAGGGIGALL
Helix 8: LFTANGLVAGLVAICAGTDI
Helix 9: ALIIGTIAGAQVPIVYRLL
Helix 10: VPVHGTAGVTGAILAGIFGMTAF
Helix 11: IIASGFVIVYGTGFGYILG

Query ID: A0A832ZZI9
Helix 1: FFLVVMGVLVFLMQLGFAML
Helix 2: WLVGCVSWLFIGYILCTSLN
Helix 3: LAQWFFGLVFAATAATIVSGGVA
Helix 4: AYVLLSILITAFVYPLFVYLS
Helix 5: YAGSLIVHGLGGFLALGAIAALG
Helix 6: VPILGHNIPMAVFGAFALAIGWYG
Helix 7: ISGLVCATTTMAMAGGGIGALLV
Helix 8: FTANGLIAGLVAICAGTDI
Helix 9: ALIIGLIAGAQVPLVYRLL
Helix 10: VPVHGTAGVIGTILAGIFGMTAL
Helix 11: ILASILCIVYGTVLGFLLAKIV

Query ID: A0A832Z6L4
Helix 1: VFFLVVMGVLVFLMQLGFAML
Helix 2: WLVGCVSWLLIGYILCTSIN
Helix 3: LANWFFGLVFAATAATIVSGGVA
Helix 4: AYILLSILITAFIYPLFVYLG
Helix 5: YAGSLIVHGLGGFLALGAIAALG
Helix 6: VPILGHNIPMAVFGAFALAIGWYG
Helix 7: ISGLVCATTTLAMAGGGIGALLV
Helix 8: FTANGLIAGLVAICAGTDIV
Helix 9: LIIGLIAGAQVPLVYRLL
Helix 10: VAVHGTAGVIGAILAGILG
Helix 11: IVNQIIASIVCIVYGTVLGYVLA

Query ID: F6BEI0

Helix 1: VFFLVVMGVLVFMMQWGFAML
Helix 2: WFIGCVSWLFIGGVLCASIN
Helix 3: WFFGLVFCATAATIVSGGVA
Helix 4: AYVLISIIITAFLYPFFVYLG
Helix 5: YAGSLIVHGLGGFLALGAIAAVG
Helix 6: VPILGHNIPMAVFGALALAIGWYG
Helix 7: ISGLVCATTTLAMAGGGIGAL
Helix 8: VLFTANGIVAGLVAICSGT
Helix 9: IGGLLIGLIAGLQVPIVFRLL
Helix 10: VPVHGTAGVVGAILAGILGMEAL
Helix 11: IIASVVTIIYGTALGFIIAKIAGVICGGL

Query ID: A0A832RS03
Helix 1: LAATALVMLMTPGVGLFYGG
Helix 2: VISMIALSFIAFALVSIQWVL
Helix 3: LLFMVFQLVFAAITLAILT
Helix 4: FIIFGVLWTTIVYDPLAHWVWG
Helix 5: FAGGTVVHISSGFSALALALVV
Helix 6: LLGAALLWFGWFGFNAGSALA
Helix 7: ANAFVVTNTAAAAGALAWMFASWV
Helix 8: VGFVSGAIAGLVAITPAAGFV
Helix 9: IVIGAVAGLICYRAMLFRI
Helix 10: AVHGVGGLWGALATGIFAVPAIGG
Helix 11: FIAQALGAGAALVYAFGATYVIA

Query ID: B3DUX7
query B3DUX7 has 12, using last 11 helices
Helix 1: AWLLTSTALVLFMTLPGLALFY
Helix 2: VLAQCFGITGLVAVLWWAVGYSLV
Helix 3: YSFWVSQNVFCMFQMMFAVITPALI
Helix 4: AVLIFITLWMLFVYFPQAHMVWG
Helix 5: FAGGTVVHMTSGWSALILALLL
Helix 6: IPNNMAYCMTGAAILWIGWYG
Helix 7: IAANAFLTTTMATAVASLTW
Helix 8: TVLGFSTGAVAGLVAITPA
Helix 9: TTGAVVIGLAAGIIPYFACSVL
Helix 10: AFGVHGVGGMLGAFLTGVFATA
Helix 11: AILITIVIATLASLIIGFIV

Query ID: Q1GYA8
Helix 1: AWTIVATVLVLAMIIPGVALFY
Helix 2: ILTQVFVTTALMSVIWVVYGY
Helix 3: YVFVTFQLTFAAITPALIVGGFA
Helix 4: AVLAFLALWVTFIYIPIAHMVWG
Helix 5: FAGGTVVHMNAGIAALVGAIVVG
Helix 6: PHSITLTMVGASMLWVGWFG
Helix 7: IAGLALINTQAATGAAVLGWV
Helix 8: LLGAVSGAVAGLVAITPA
Helix 9: PVGAIVLGFVASVIAFWAVT
Helix 10: LDVFGIHGVAGLIGAFGTGIL
Helix 11: LYAQAVAIGVTIVWGGIGSYILF

Query ID: Q1H0G2
Helix 1: VWVAISGALVFMMQAGFAML
Helix 2: LAVGALLFWLVGYGLMFG
Helix 3: WGASMLFFQVMFAATAATIVSGA
Helix 4: FIAYLLGACGIMALIYPVF
Helix 5: AGSTVVHSVGAWCALAGIMVL
Helix 6: LSLVAMGGFLLWFGWFGF
Helix 7: IGPILLNTHMAGAAGAVGALLVAL
Helix 8: LMAYVVNGSLGGLVAITAG
Helix 9: VPFAVLTGFIGGIVTMLGVWAL
Helix 10: VAVHGFSGVWGTVAAGLFL
Helix 11: VQMIGVAVAFVWVFLSALLMYGLL

Query ID: Q1H483
Helix 1: TAWMIVATVLVIIMAVPGLAIFY
Helix 2: VLMQVLVTFSLLSVLWAVY
Helix 3: LLFVTFQMTFAAITPALIVGGFA
Helix 4: AVLLFMVLWMTFSYLPMAHMVWG
Helix 5: FAGGTVVHMNAGIAALVGALVLG
Helix 6: PHNMVLTMVGGSLLWAGWFGF
Helix 7: AGLAVVNTQLATASAVVGWVIAEWL
Helix 8: MLGAISGAIAGLVAITPA
Helix 9: PMGAIVLGFIASLISFWSVT
Helix 10: MDVFGVHGIAGIVGALGTGIF
Helix 11: LYVQAVSVGFTVVYVSIVSYILF

Query ID: A0A2S6GKF6
Helix 1: AWMIVATVLVTLMVIPGLALFY
Helix 2: MLMQVFVIFSMMAILWAIY
Helix 3: YIYVAFQLTFSAITPALIVGAFA
Helix 4: AVLLFMFIWFTFSYLPMAHMVWYW
Helix 5: FAGGTVVHINAGIAGLIGCLM
Helix 6: LAPHSVTMTMIGASLLWIGWFG
Helix 7: LAGLVFINTLLASAAATLAWV
Helix 8: MLGGASGAVAGLVAITPA
Helix 9: PMGAILLGLVAGAICFWAV
Helix 10: IGGIIGALGTGIVASPALGGTGVW
Helix 11: AWGVGVCIVWSAVVSFIAY

Query ID: A0A2S6H643
Helix 1: AWMIVATVLVILMVIPGLALFY
Helix 2: MLMQVFVIFSMMAILWAIY
Helix 3: YIYVAFQLTFAAITPALIVGAFA
Helix 4: AVLLFMFLWFTFSYLPMAHMVWYW
Helix 5: FAGGTVVHINAGIAGLVGCLM
Helix 6: LAPHSVTMTMIGASLLWVGWFG
Helix 7: LAALVFVNTLLASAAATLAWV
Helix 8: MLGGASGAVAGLVAITPACGWAG
Helix 9: MLGLVAGAVCFWAVTMLKGALGY
Helix 10: IGGIIGALGTGIVASPSLGGTGVW
Helix 11: AWGVGVCIIWSSVVSFIAY

Query ID: G3IYW2
Helix 1: AWMIVATVLVILMVIPGLALFY
Helix 2: MLMQVFVIFSMMAILWAIY
Helix 3: YIYVAFQLTFAAITPALIVGAFA
Helix 4: AVLLFMFLWFTFSYLPMAHMVWYW
Helix 5: FAGGTVVHINAGIAGLVGCLM
Helix 6: LAPHSVTMTMIGASLLWVGWFG
Helix 7: LAALVFVNTLLASAAATLAWV
Helix 8: MLGGASGAVAGLVAITPACGWAG
Helix 9: MLGLVAGAVCFWAVTMLKGALGY
Helix 10: IGGIIGALGTGIVASPSLGGTGVW
Helix 11: AWGVGVCIIWSSVVSFIAY

Query ID: A0A2S6GKN5
Helix 1: WVLTSTALVLFMTLPGLSLFY
Helix 2: VLMQCFAIACLVSMLWLAGVYSFI
Helix 3: VFFMFQMTFAIITPALIVGGFA
Helix 4: AMLWFSGLWLIMVYLPICHWMWG
Helix 5: FAGGIVIHVNAGVAALVSALVLG
Helix 6: PHNMTMVVTGAGMLWVGWFGF
Helix 7: AGMAMLVTHIGAASGALTWMFI
Helix 8: SVLGIVTGMVAGLGTITPAS
Helix 9: AGALVIGITAGAVCFYATQYV
Helix 10: VFSVHGVGGVTGSLLTGVFAA
Helix 11: VQALAIVVTAAWSGLFSYLIL

Query ID: A0A2S6H6B7
Helix 1: WVLTSTALVLFMTIPGLSLFY
Helix 2: VLMQCFAITCLVSILWLAGVYSFI
Helix 3: VFFMFQMTFAIITPALIVGGFA
Helix 4: AMLWFSGLWLIVVYLPICHWMWG
Helix 5: FAGGIVIHVNAGVAALVSALVLG
Helix 6: PHNMTMVVTGAGMLWVGWFGF
Helix 7: AGMAMLVTHIGAASGALTWMFI
Helix 8: SVLGIVTGMVAGLGTITPAS
Helix 9: FGALVIGITAGVVCFYATQYV
Helix 10: VFSVHGVGGVTGSLLTGVFAA
Helix 11: IQALAIVVTAAWSGLFSFLIL

Query ID: G3IYW0
Helix 1: WVLTSTALVLFMTIPGLSLFY
Helix 2: VLMQCFAITCLVSILWLAGVYSFI
Helix 3: VFFMFQMTFAIITPALIVGGFA
Helix 4: AMLWFSGLWLIVVYLPICHWMWG
Helix 5: FAGGIVIHVNAGVAALVSALVLG
Helix 6: PHNMTMVVTGAGMLWVGWFGF
Helix 7: AGMAMLVTHIGAASGALTWMFI
Helix 8: SVLGIVTGMVAGLGTITPAS
Helix 9: FGALVIGVTAGVVCFYATQYV
Helix 10: VFSVHGVGGVTGSLLTGVFAA
Helix 11: VQALAIVVTAAWSGLFSFLIL

Query ID: A0A2J7TJ33
Helix 1: TAWMLVSTALVLMMSVPGLALFY
Helix 2: VLSQVFAIVALVSIIWVVYGY
Helix 3: FVYMAFQMTFACITPALII
Helix 4: LLVFITLWVTFIYFPIAHAVWYWA
Helix 5: FAGGTVVHINAGIAGFVGCLVMG
Helix 6: PHSVTMSMIGASLLWVGWFGF
Helix 7: TALAFVNTFVATSAATLSWM
Helix 8: LLGIISGAVAGLVAVTPASGFA
Helix 9: VVLGLAVGAICFFFVDYV
Helix 10: VFGVHCVGGIVGAIATGFLVAPAL
Helix 11: AVSFTLLYSGIGSFILYKLV

Query ID: B8ENL9
Helix 1: TAWMLVSTALVLMMSVPGLALFY
Helix 2: VLSQVFAIVALVSIIWVVYGY
Helix 3: FVYMAFQMTFACITPALII
Helix 4: LLVFITLWVTFIYFPIAHAVWYWA
Helix 5: FAGGTVVHINAGIAGFVGCLVMG
Helix 6: PHSVTMSMIGASLLWVGWFGF
Helix 7: TALAFVNTFVATSAATLSWM
Helix 8: LLGIISGAVAGLVAVTPASGFA
Helix 9: VVLGLAVGAICFFFVDYV
Helix 10: VFGVHCIGGIVGAIATGILVAPAL
Helix 11: AVAFTLLYSGIGSFILYKLV

Query ID: B8EMQ8
Helix 1: AWMLTSVALVLMMTVPGLGLFY
Helix 2: TVMTSFAITCLITFLFAAVTY
Helix 3: TVYICFQMTFAIITPALIAGAFA
Helix 4: AMLWFIGLWAILVYAPIAHWVW
Helix 5: FAGGTVVHVNSGVAGLMCALML
Helix 6: VVLTFIGASLLWVGWFGF
Helix 7: AGMAMTVTQIATAVAALAWM
Helix 8: VVGICSGAVAGLVAITPASGFV
Helix 9: MAIGAIAGVLCYASVTWL
Helix 10: CFGVHGVGGATGAILTGVFAIQ
Helix 11: LVGVVIVIAYDAIVSLILLFLI

Query ID: Q60C43
Helix 1: WILTSTGFAWFMTVPGLALLY
Helix 2: VLAQCFAVAALVSLVWMGAGYSLA
Helix 3: IYHLGFAVLAPTVMVGGFA
Helix 4: AMLWFTTLWMLLVYAPVCHWLWG
Helix 5: FSGGVVVHATAGVSALTAAWLVG
Helix 6: PHNLTLTAAGAGMLWIGWHGF
Helix 7: LITNGAAALSMLNTHLAASAGAMVWM
Helix 8: LLGLVTGMIAGLVALSPAAGY
Helix 9: AVIVGGAGGLACFFAIPWI
Helix 10: VFPVHAAGALLGVLLTPLV
Helix 11: IGVQLVAIAAAGVWSGTVSYFIL

Query ID: Q605Y6
Helix 1: AWMIVATVLVTLMVIPGLALFY
Helix 2: VLMQVFVIFSLMAVLWAVYGYSIA
Helix 3: LIYVAFQLTFACITPALIVGAFA
Helix 4: AVLLFMVLWFTFSYLPIAHMVWYWA
Helix 5: FAGGTVVHINAGIAGLVGCLLV
Helix 6: APHSVPMTMIGASLLWVGWFGF
Helix 7: AALAFVNTMLATAAATLAWSA
Helix 8: LGGASGAVAGLVAITPACGFIG
Helix 9: VLGLAAGAVCFWSVTTL
Helix 10: VFGVHGVGGIIGALGTGIFASPALGGAGVY
Helix 11: SWGVGVTIVWSGVVSLIAY

Query ID: Q60BI2
Helix 1: TAWILTSTGLVLFMTMPGLALLY
Helix 2: VMVQIFTATSLVSVLWVIAGYTLA
Helix 3: MYHLTFAIFAPALMLGAIV
Helix 4: VTLWFTGIWTLLVYVPVCHWVWG
Helix 5: FAGGVVVHTTAGVSALVGAWMLG
Helix 6: PHNLTLTAIGAGILAVGWHGF
Helix 7: LMATGAAGMAMLTTHIGASVGALVW
Helix 8: TLLGALTGMIAGLGVISPAA
Helix 9: LGAIAMGTAAGVICFGAIHWI
Helix 10: VFPVHGVGGMIGTVLTAPFA
Helix 11: LTQILAVGSVAAWSGLISWLLL

Query ID: Q608B6
Helix 1: VLFVLLGAIMVLAMHAGFAFL
Helix 2: FAMSTIAYFFIGYELAYGV
Helix 3: FFFLLTFAAAIPAIVSGGIA
Helix 4: LAATFLLVGFVYPLFEGIAWN
Helix 5: FAGSVVVHAVGGWIGLAAVLLL
Helix 6: IPFLALGAWILTVGWFGFNVMSA
Helix 7: ISGLVAVNSLMAMVGGTLAALLA
Helix 8: FVHNGPLAGLVAVCAGSDL
Helix 9: ALAVGAVAGFLFVYLFTLT
Helix 10: VWPLHGLCGAWGGIAAGIFG
Helix 11: FMAQVLGTGLGVAIALAGGLAVY

Query ID: V5E0F3
Helix 1: WILTSTALVLFMTIPGLSLFY
Helix 2: VLMQCFAITCLVSILWLAGAYSLI
Helix 3: LYFMFQMTFAIITPALIVGAFA
Helix 4: AMLWFSGLWLCLVYVPICHWIWG
Helix 5: FAGGIVIHINAGIAALVSALVIG
Helix 6: PHNMTMVVTGAGMLWVGWFGF
Helix 7: AGMAMLVTHIGAAAGSLTWM
Helix 8: MLGIVTGMVAGLGTITPAS
Helix 9: MGALVIGITAGIVCFFATQIV
Helix 10: VFPVHGIGGITGSLLTGVFAA
Helix 11: IQALAILATIAWSGLFSYLIL

Query ID: V5BYZ7
Helix 1: TAWMIVATVLVILMVIPGLALFY
Helix 2: VLMQVFIIFSMMAILWAIY
Helix 3: YIYVVFQLTFAAITPALIIGAFA
Helix 4: AVLLFMLIWFTFSYLPIAHMVWYWA
Helix 5: FAGGTVVHINAGIAGLVGCLM
Helix 6: LAPHSVTMTMIGASLLWVGWFG
Helix 7: LAALVFVNTLLATAAATLSWM
Helix 8: MLGGASGAIAGLVAITPA
Helix 9: PMGAIVLGLVVGAVCFWSVTGL
Helix 10: AFGVHGVGGIIGAIGTGIVA
Helix 11: LWGVGVSIIWSGTVSFIAF

Query ID: I1YG38
Helix 1: DVLFILLGAIMVLAMHAGFAFL
Helix 2: FGISTIAYFFIGYGIAYGL
Helix 3: FFFLLTFAAAIPAIVSGGIA
Helix 4: LIASFVIAGFVYPLFEGISWN
Helix 5: FAGSIVVHAVGGWIALAAVLHL
Helix 6: IPFLALGAWILTVGWFGFNVMS
Helix 7: GISGIVAVNSLMAMVGGTLAACFM
Helix 8: FVHNGPLAGLVAICAGSNV
Helix 9: ALVTGAVAGVLFVYFFT
Helix 10: LGVWPLHGICGVWGGIAAGIFGQVAL
Helix 11: LLGTVLGVTIAFAGGWVVYGML

Query ID: I1YJH7
Helix 1: FYFLISGAFVMWMAAGFAMLEAGLV
Helix 2: NVMLFAIACTAYLVVGYDIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFAAFAIVMTAFIYPM
Helix 5: LGFLDFAGSGIVHMAGAAAALAGVMLL
Helix 6: LPLATLGTFILWLGWFGF
Helix 7: VFMNTNAAAAGGVLAALIVA
Helix 8: ADLTMILNGALAGLVAITAGP
Helix 9: LMATIIGAIGGLIVVFSIVF
Helix 10: AISVHGVVGLWGLLAVPLT
Helix 11: FSAQIIGAVTIFVWVFVTSLIVWGVL

Query ID: F5RGM7

Helix 1: VWMMLASILVIMMAVPGLALFY
Helix 2: ILMQVMTVFSLIVVLWFVYGY
Helix 3: MIFAAFQSTFAGITAALIIGAFA
Helix 4: AVLLFSVLWFTFSYIPVAHMVWYW
Helix 5: FAGGTVVHINAGVAGLVGAYMV
Helix 6: APHSLVMTMVGASLLWVGWFGF
Helix 7: AVLAFATTLIATAAATVSWL
Helix 8: MLGAASGAVAGLVAITPA
Helix 9: PMGALIMGLVSGIVCLWGV
Helix 10: ALDVFGVHGVGGILGAILTGVFA
Helix 11: VITQATAVGVTIIWTAVVSFIAF

Query ID: F5R974
Helix 1: FILLGAIMVLAMHAGFAFLEVGTV
Helix 2: ILVDFAVSTLVYFFIGYGIAYGV
Helix 3: FFFLLTFAAAIPAIVSGGI
Helix 4: ATALIVGLLYPLFEGMIWN
Helix 5: FAGSVVVHAFGGWIALAAVLLL
Helix 6: IPFLALGAWILTVGWFGFNVMS
Helix 7: AVNGLVAVNSLMAMVGGTLVALVA
Helix 8: FVHNGPLAGLVAVCAGSDL
Helix 9: ALLTGGIAGGLFVLMFTLT
Helix 10: VWPLHGLCGAWGGIAAGIFG
Helix 11: FMTQLVGTVAGVALALAGGAIIY

Query ID: A0A2W5HTC3
Helix 1: LTSSLLVLMMSVPGLALFYGGL
Helix 2: LATLMQTVAVCAVVSLLWPVI
Helix 3: VFIMFQMTFAIITAALLL
Helix 4: VLVFVPLWMLAVYAPVAHWVW
Helix 5: FGFALDFAGGTVVHIASGVAGLVAALVL
Helix 6: SPANIVMSLIGTGLLWVGWFGF
Helix 7: AGMAMLVTNTSAAVACLAWIF
Helix 8: VGALSGVVSGLVAITPAAGFV
Helix 9: IVIGFAAGVVCFLACTYL
Helix 10: VFGIHGIGGIVGCILTGVF
Helix 11: IAQLISIVIVVAYVTVITFILI

Query ID: A0A2W4ZXC0
Helix 1: IAWMLVACALVLLMTPGVAFFYGG
Helix 2: FQSFACLGVVGLLWAVCGYSLV
Helix 3: IPHVLFMLFQCTFAIITPALI
Helix 4: AWLVIMAAWSLIVYVPVAHWVW
Helix 5: LDFAGGLVVHMTSGYAALIAALMLG
Helix 6: SFSVLLVMLGGTMLWFGWFGF
Helix 7: AGQAAATTFFAAATTMTVWML
Helix 8: VGAMVGVVAGLVAITPAAG
Helix 9: AALAIGGITAVACNYACRIV
Helix 10: VFACHGVGGTIGTILTAVFA
Helix 11: MIANIVGALAVVSYTIMMTAFIFFLV

Query ID: M4VEJ9
Helix 1: IAWMLMATALVLLMTPGVAFFYG
Helix 2: VVGLIWAVCGYSLVFSEGNIFIGGF
Helix 3: IPHVLFMLFQATFAIITPALI
Helix 4: AWLIIMALWSLCVYVPVAHWVW
Helix 5: LDFAGGLVVHMTSGFAALVAAIMLG
Helix 6: SFSVLMVWLGATFLWFGWFGF
Helix 7: AAYAAGTTFFAAATSMTIWMI
Helix 8: VGAAVGAVAGLVAITPAAG
Helix 9: AALIIGVVAAVGCYFAARLV
Helix 10: VFACHGVGGMIGTILTAVFASTAI
Helix 11: VIGALVVVGYTGVVTAVIFKLV

Query ID: A0A1H1MB73
Helix 1: NISWAITATALVLLMTPGVAFFY
Helix 2: MMMMSFGSIGLVAVLWILF
Helix 3: VALLSVAYGATFAIITVALIS
Helix 4: WLIFAGVFATVGYFPVAAWVWG
Helix 5: VIDYAGGTAVHINAGAAALALALVLG
Helix 6: PHNVPLTLLGAALLWFGWFGF
Helix 7: GGVGLIGLNTLGATAAAILGWIL
Helix 8: VGAASGAVAGLVAITPACA
Helix 9: WSLLLGAVAGIVCALAVEL
Helix 10: VVGIHLVGGLIGTVYLGFFATGTGLFVG
Helix 11: LAVQVIAAAGVLIYSFVVAWVIGFVI

Query ID: A0A7U6DPL5
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A653ISC0
Helix 1: WMVVSAGLVLLMTPGLALFY
Helix 2: MMMMSFVSMGLVGVVWILW
Helix 3: GLIAAGFGATFAIITVALISGA
Helix 4: FLTWCVFVPVWVTLVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLA
Helix 6: VPFTMLGAALLWFGWFGF
Helix 7: GLIWINTLAAAAAGMLGWVV
Helix 8: IGTASGIVAGLVGITPAC
Helix 9: LGALVIGVASGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVVVAVVFTAVLTFLIALVL

Query ID: D3LL06
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALML
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A378NLG8
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIITVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A653N551
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A132HDB5
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALML
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPACAF
Helix 9: AVAIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A031H2S8
Helix 1: VWMMTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A031ISU7
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVATLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: C5CAG5
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A4P8HC89
Helix 1: VDVWVMVSAALVLLMTPGVAFLY
Helix 2: MLMMSFASMAVVGVVWVLW
Helix 3: AFGLSGLVGTTDLIGAGFGATFAIITVALI
Helix 4: AWMVFVPVWVTLVYCPMAFMVWG
Helix 5: YAGGTVVHINAGIAALVLALII
Helix 6: NIPFVMLGATLLWFGWFGF
Helix 7: GLIWVNTMAAPAAAFIAWIL
Helix 8: LGGASGIVAGLVAITPACA
Helix 9: GAIAIGIIAGICSALAVGL
Helix 10: VVGVHLVSGLVGTLALGLFALPV
Helix 11: TVAAVFAILFTAIVTFIIGMVI

Query ID: A0A509Y3R3
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVATLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A4U1LD24
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALML
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPACAF
Helix 9: AVAIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A410XNG8
Helix 1: IAWILAAAAMVLLMFPGLAFLY
Helix 2: MLMMVMSGLAVGGVAYVVLGHGLV
Helix 3: AGGTLSAAFFILFAAISVSLVA
Helix 4: WLVFAALWVLLVYSPLAHWVF
Helix 5: YAGGTAIHMNAGAAGLALAMVLG
Helix 6: NLPLMLIGVGMLMMGWIGF
Helix 7: AEYAVMTTILATCGGMLGFIAV
Helix 8: HATLLGMGTGIIASLVAITPVA
Helix 9: IGAILVGFLGAAAAAWAITW
Helix 10: VFAVHGIAGIAGAMFAVFFATAAA
Helix 11: ALAIVVTLVYSFGMTYAIAWVM

Query ID: A0A7T5AF95
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A1R4IK85
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGALVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A1M6ZIN6
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALML
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A562FQ17
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVATLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTAGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: A0A5E8QER8

Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALLL
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTAIALVL

Query ID: A0A2N6RP58
Helix 1: VWMVTSAAMVLLMTPGLAIFY
Helix 2: MIMMSFVSMGLVGVVWVLW
Helix 3: GLVAAAYGATFAIIAVALISGA
Helix 4: FVTWCVFVPVWTTVVYAPLAYMVWG
Helix 5: FAGGLVVHISAGVAALVLALML
Helix 6: NVPFTMLGAALLWFGWFGF
Helix 7: GLIWVDTLAAGAAGMLGWVF
Helix 8: IGTASGIVSGLVAITPAC
Helix 9: LGAVVIGLVSGAASALAVNL
Helix 10: VVGVHLTSGILGTVLIGFFAL
Helix 11: QTVAVLVAVVFTAVVTTVIALVL

Query ID: F5XN43
Helix 1: AWMLTSAALVLLMTPGLALFY
Helix 2: MMMMSFGAMAIIAILWVLY
Helix 3: MAFVAFQAMFAIITVALISGAIA
Helix 4: TWMIFAALWATIVYFPIAHWVF
Helix 5: FAGGTAVHINAGAAGLALALVLG
Helix 6: PHNLPLVMLGAGLLWFGWFGF
Helix 7: ASVAFVNTLVATAAASLAWLI
Helix 8: GHATSLGAASGIVAGLVAIT
Helix 9: VSPIGAIILGLVAGVLCALAIGL
Helix 10: VVGVHLVGGLWGTIAIGFFATAAA
Helix 11: AVGAFAVLIVSFVVTYLIGLIL

Query ID: A1ZGK6
Helix 1: WMMIATILVFIMHLGFATLE
Helix 2: ILFKNVLIIAIGLLTYTFIGFNLMY
Helix 3: FIFQAMFAATCITIVSGAVA
Helix 4: AFLLFAVFFVAIIYPMVGMW
Helix 5: FAGSSIVHSVGGWAALAGVLLLG
Helix 6: LAAMGVFLLWFGWFGFNGGS
Helix 7: VFVTTSLAAAAGALGAFFTSFFIL
Helix 8: MSLNGILGGLVGITAGADV
Helix 9: AVLIGLIAGILVVLAVLFF
Helix 10: IAVHLVCGVWGTMAVAILGA
Helix 11: IGISAIGLFSFGSAYVVFYIV

Query ID: A0A2S0P9T4
Helix 1: AWMLVSTALVLFMTIPGLALFYGG
Helix 2: VLATLMQSFAICSVVTVLWFAF
Helix 3: VFVVFQMTFAIITTALITGAFA
Helix 4: AMLVFMTLWLFVVYVPIAHWVW
Helix 5: VHINAGVAGLVCALVLGKRI
Helix 6: LVLTLVGASMLWVGWFGF
Helix 7: AGMAMLVTQVATGAAAATWMF
Helix 8: LGIASGAVAGLVAITPASGF
Helix 9: ALLIGLVAGGACYVGATSL
Helix 10: AFGVHGVGGIIGSLLVGPLAVKAIG
Helix 11: LMTQAIATVSTAGYTLVVTFILL

Query ID: C9KKP2
Helix 1: DTAWVLISAALVFVMTPGLAFFYG
Helix 2: IMQSFFIVAMISVEWVILGYAM
Helix 3: LAFVAFQCMFAVITPALITGAFA
Helix 4: AFAVLILLWAIFIYNPMAHWVWG
Helix 5: FAGGLVIHILSGVSGLTICILL
Helix 6: LPHNLPMTVLGATLLWFGWFGF
Helix 7: AANAFVTTQAAAAAATVSWVLVEWY
Helix 8: ILGAASGCIAGLVAITPAAGF
Helix 9: ALAIGLIGGIVCYFAVAVL
Helix 10: AFGVHGIGGTWGSIATGLWA
Helix 11: LFAQVVSVIVAYALAIVGTYILF

Query ID: A0A414NWT8
Helix 1: DTAWVLISAALVFVMTPGLAFFYG
Helix 2: IMQSFFIVAMISVEWVILGYAM
Helix 3: LAFVAFQCMFAVITPALITGAFA
Helix 4: AFAVLILLWAIFIYNPMAHWVWG
Helix 5: FAGGLVIHILSGVSGLTICILL
Helix 6: LPHNLPMTVLGAALLWFGWFGF
Helix 7: AANAFVTTQAAAAAATVSWVLVEWY
Helix 8: ILGAASGCIAGLVAITPAAGF
Helix 9: ALAIGLIGGIVCYFAVAVL
Helix 10: AFGVHGIGGTWGSIATGLWA
Helix 11: LFAQVVSVIVAYALAIVGTYILF

Query ID: H5UND3
Helix 1: LVSAALVMLMTPGLAFFYGG
Helix 2: VLNMMMMSLGTMGTVGVLWVLV
Helix 3: VPALAFVGFQAMFAIIATALVS
Helix 4: WLLFTAIWAVLVYFPVAHWVF
Helix 5: FAGGTAIHINAGAAALALVFVLG
Helix 6: PHNLTLVMLGAGLLWFGWFGF
Helix 7: AAVAFVNTLAAPAAAILGWLL
Helix 8: LGAASGIVAGLVGITPGA
Helix 9: VGAVVIGAVSGVLCALAVGL
Helix 10: VVGVHLVGGLAGTLLIGLLASSSA
Helix 11: AIGAFIVLVVSFVASYALGWVL

Query ID: D4XLN6
Helix 1: AWILVSTALVLLMTIPGLALFYG
Helix 2: MAHSFVAAAVVSIAWIVIGYTLA
Helix 3: ILFVVFQMTFAIITVAIISGSIA
Helix 4: AFVAFIAIWVVVVYAPITHWVWG
Helix 5: FAGGTVVHINSGVAGLVAAYML
Helix 6: APHNLALTVVGASLLWVGWFGF
Helix 7: ASYAIVVTQVAAAAAALSWL
Helix 8: VLGAASGAVAGLVVITPAAGF
Helix 9: ALIMGLIGGVVCFWGITAL
Helix 10: AFGLHGVGGIVGAILTAVFASEFIM
Helix 11: LWVQVEGVLATIAYSAVMTFIIL

Query ID: D4XSW0
Helix 1: FFLLLGAVLVLSMHAGFAFLELGTV
Helix 2: ILTDFCISAIAYFFVGYWIA
Helix 3: LMRCFFLLTFAAAIPAIVSG
Helix 4: ALATLLLVALIYPFFEGMIWN
Helix 5: FAGSVVVHAMGGWIALAAVLLLG
Helix 6: FLALGSWILIVGWFGFNVMS
Helix 7: AISGLVAINSLMAMAGGTLAANFM
Helix 8: FLHNGPLAGLVAICAGSDI
Helix 9: ALVIGASAGAIFVYFFTYT
Helix 10: VWPLHGICGAFGAIVAGIFG
Helix 11: FISQLIGTGLGISVALIGGFIVYGLL

Query ID: A9UR54
Helix 1: LYLIIMAIMVYNMQLGFALL
Helix 2: MFIGTVSFLVFGYAFAFGH
Helix 3: YPFFFFQAAFAAACTTIISGSVAG
Helix 4: YIVYSMGVTGLVYPVVVHWVW
Helix 5: GSGVVHTTGGIIALVGAWLL
Helix 6: VPLIIMGGLILVVGFLAFNAGSLISL
Helix 7: IAINTIVAASAGGLMGTFIDYI
Helix 8: LLQATNGMLAGSVAICASAH
Helix 9: AALLIGGIAGIVCLGWSYVL
Helix 10: FPVHAGAGLWGLFAVAFFST
Helix 11: LLGSLVIVAWSSVMALIMFYPL

Query ID: A9V5W4
query A9V5W4 has 12, using last 11 helices
Helix 1: YYQDVHVMIFIGFGMLMTFL
Helix 2: AVAYNMFLACIAFQWAQFTNTFW
Helix 3: LITGDFAAASVLVAYGAVIG
Helix 4: LLVMALLQLIFYSLNESIGVI
Helix 5: YVHAFGAYFGLAVSFMLGN
Helix 6: STSDVFAMIGTLFLFMFWPSF
Helix 7: RVVINTVIAIAFSAMSTFAFSNLF
Helix 8: NATLAGGVAVGSSADLLI
Helix 9: ALIGFVAGLISVVGYVYISGLL
Helix 10: VHNLHGMPGVVGGLGGVIAASLA
Helix 11: LLALVVTLGLAIGGGLATGFVLRLL

Query ID: A0A5D3HZ79
Helix 1: AFLLVASALVMLMTPGLAFFYGG
Helix 2: VLGIIMQCLAAMALISVQWVLW
Helix 3: VFAMFQLMFAIITPALIIGAFA
Helix 4: AFLLFTLMWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGATLLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGAVCCFSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVVGVAAAWIFTSIVTYGIL

Query ID: A0A1J5JH24
Helix 1: AFLLVASALVMLMTPGLAFFYGG
Helix 2: VLGIIMQCLAAMALISVQWVLW
Helix 3: IPHQVFAMFQLMFAIITPALI
Helix 4: AFLLFTLMWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGATLLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGAVCCFSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVIGVAAAWIFTSIVTYGIL

Query ID: A0A1J5NNB8
query A0A1J5NNB8 has 12, using last 11 helices
Helix 1: FVWTLLAGFLVFFMQAGFALV
Helix 2: VFLVGAVGFFVLGFGLMFGGLGAVA
Helix 3: VGVFALFLFQMVFMDTAVTIP
Helix 4: AVVLGSFFIAMFLYPIFGNWVWG
Helix 5: FAGSGVVHSIGGAAGLAGALIL
Helix 6: IPMAVLGTIILFFGWFGF
Helix 7: RIAVVAVNTMMAGAVGGLASMLY
Helix 8: MMCNGVLAGLVAITAPSAF
Helix 9: ACLIGAVAGILVVWSVYFF
Helix 10: AISVHLVNGLWGLLAVGLFA
Helix 11: LVAQLINMVVVFAWGFGASYVFY

Query ID: A0A853W4S3
Helix 1: AFLLVASALVMLMTPGLALFYGG
Helix 2: VLGIIMQCLAAMAIISVQWVLW
Helix 3: VFAMFQLMFAIITPALITGAFA
Helix 4: AFLLFTLMWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGATLLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGAVCCFSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVIGVAAAWIFTSIVTYGIL

Query ID: A0A1J5NTP7
Helix 1: AFLLVASALVMLMTPGVAFFYGG
Helix 2: VLGIIMQCLAVLALVSVQWVLW
Helix 3: VFAMFQLMFAIITPALIIGAFA
Helix 4: AFLLFTLIWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGAALLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGAVCCLSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVVGVAAAWIFTAAVTYGIL

Query ID: A0A1D7XAU3
Helix 1: FVWTLLAGFLVFFMQAGFALV
Helix 2: VFLVGAVGFFVLGFGLMFGGLGAVA
Helix 3: VGVFALFLFQMVFMDTAVTIP
Helix 4: AIVLGSFFIAMFLYPIFGNWVWG
Helix 5: FAGSGVVHSIGGAAGLAGALIL
Helix 6: IPMAVLGTIILFFGWFGF
Helix 7: RIAVVAVNTMMAGAVGGLTSMLY
Helix 8: MMCNGVLAGLVAITAPSAF
Helix 9: ACLIGAVAGILVVWSVYFF
Helix 10: AISVHLVNGLWGLLAVGLFA
Helix 11: LVAQLINMAVAFAWGFGASYVFY

Query ID: A0A0S6UEK9
Helix 1: AFLLVASALVMLMTPGLAFFYGG
Helix 2: VLGIIMQCLAAMAIISVQWVLW
Helix 3: VFAMFQLMFAIITPALITGAFA
Helix 4: AFLLFTLMWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGATLLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGAVCCFSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVVGVAAAWIFTSIVTYGIL

Query ID: A0A0S6UHP2
query A0A0S6UHP2 has 12, using last 11 helices
Helix 1: FVWTLLAGFLVFFMQAGFALV
Helix 2: VFLVGAVGFFVLGFGLMFGGLGAVA
Helix 3: VGVFALFLFQMVFMDTAVTIP
Helix 4: AIVLGSFFIAMFLYPIFGNWVWG
Helix 5: FAGSGVVHSIGGAAGLAGALIL
Helix 6: IPMAVLGTIILFFGWFGF
Helix 7: RIAVVAVNTMMAGAVGGLTSMLY
Helix 8: MMCNGVLAGLVAITAPSAF
Helix 9: ACLIGAVAGILVVWSVYFF
Helix 10: AISVHLVNGLWGLLAVGLFA
Helix 11: LVAQLINMAVALAWGFGASYVFY

Query ID: Q2RM12
Helix 1: AFILVASALVMLMTPGLAFFYGG
Helix 2: VLGIIMQCLATLALISVQWVLW
Helix 3: VFAMFQLMFAIITPALITGAFA
Helix 4: AFLLFTLMWATLVYDPLAHWVW
Helix 5: LDFAGGTVVHISAGVAGLVCALVLG
Helix 6: PHNLPMTVLGAALLWFGWFGF
Helix 7: AGNAFVTTNTAAGAAILGWL
Helix 8: ALGAASGAVAGLVAITPAAG
Helix 9: AALVIGGIGGALCCLSVAVA
Helix 10: AFGCHGVGGTWGAIATGIFA
Helix 11: LGVQVVGVAAAWIFTAAVTYGIL

Query ID: A0A7Z0V0A4
Helix 1: AWVLISTALVLMMTLPGLALFYAG
Helix 2: MHSYGATAVVSVLWVIIGYSLA
Helix 3: IPVILFVVFQLTFAVITVAILA
Helix 4: FMWFSAAWVVLAYAPVCHWVW
Helix 5: FAGGTVVHINAGVAGLVLAALL
Helix 6: APANLSLTLIGAGLVWVGWFGF
Helix 7: AAMALVVSQVAAAIGAIAWMV
Helix 8: LGGASGAIAGLVGITPAA
Helix 9: FGALAIGAITAIACFVMIHYG
Helix 10: AFGLHGVGGIVGAVLTGVFVSSTIY
Helix 11: LWLQIEGVLATIAYSAVMTAIIGLVI

Query ID: M1SJL5

Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: VAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A2S1BIN7
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: IAGAIVIGLVSGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: IWIQAESILVTVIWSGVITYIAF

Query ID: A0A1M7DGY1
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: IAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVIWSGVITYIAF

Query ID: A0A2C5TWB4
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: VAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A433ZQ80
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIASFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPAAG
Helix 9: GAVVIGLVSGIAGYWGVTAL
Helix 10: VFGIHGVCGIAGCLLTGIF
Helix 11: VWIQAESILVTMLWSGVITYIAF

Query ID: M7CDZ4
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: VAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A7U0APP4
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: VAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A8I0DAF6
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVVAGVLAWV
Helix 8: LLGACSGCVGGLVGITPA
Helix 9: IAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A8I0PWC5
Helix 1: NGFMLICAALVYFMTLPGIALFY
Helix 2: VMTQVIVSFALVLLLWVFY
Helix 3: VIFQGSFAAITVALITGALA
Helix 4: AFLLFTVIWFSLAYVPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYILG
Helix 6: PHSLPMVFTGTAILYIGWFG
Helix 7: IAALAFLNTVIAVAAGVLAWV
Helix 8: LLGACSGCIGGLVGITPA
Helix 9: VAGAIVIGLISGIAGYWGV
Helix 10: VCDVFGIHGVCGIAGCLLTGVF
Helix 11: VWIQAESILVTVLWSGVITYIAF

Query ID: A0A5J6WQU1
Helix 1: FLMSGVLVMWMAAGFAMLEAGLVR
Helix 2: VVLYSIACIMFLLVGYNIMYV
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFTVVLTGVIYPI
Helix 5: AGSGIVHMAGASAALAAVLLL
Helix 6: MPLATLGAFILWMGWFGF
Helix 7: IFANTNTAAAAGAVAALLI
Helix 8: MVLNGALAGLVTITADPL
Helix 9: FATLLGALGGVLVVFSIVAL
Helix 10: VGAISVHGVCGLFGLMVVPF
Helix 11: YGAAIIFAWVFGASILVWAVL

Query ID: A0A5J6WPP9
Helix 1: MFILLGAIMVLAMHAGFAFL
Helix 2: FAMSTLAYFFVGYQIAYGM
Helix 3: FFFLLTFAAAIPAIISGGVA
Helix 4: PMLFASVLIVGFVYPFFEGMIWN
Helix 5: FAGSVVVHSVGGWIAFAAIMVL
Helix 6: VIAFAPSNIPFLALGSWILTVGWFG
Helix 7: ISGLVAVNSLMAMVGGTLVAMVV
Helix 8: FIHNGPLAGLVAVCAGSDI
Helix 9: ALVVGGVAGGLFVAVFTLV
Helix 10: GVWPLHGLCGAWGGIAVGIFG
Helix 11: MMAQIVGTIAGTVVALVGGFLVYGVI

Query ID: H1YCC3
Helix 1: LLTSTALVLIMTPGLAFFYGGMVN
Helix 2: FICMGVITVIWVVFGFSLAFGDSIGGII
Helix 3: LAPTVPLVLFAMFQLKFAVITPALI
Helix 4: SYLIFICLFIVIIYAPL
Helix 5: AGGTVVHMSAGWAALASALYL
Helix 6: RISYVLLGTGLLWFGWFGF
Helix 7: AATALATTTTASAAAAMSWVFF
Helix 8: NACIGAVVGLVAVTPAAGFV
Helix 9: LIIGIVAAVVSNLVVMW
Helix 10: VFPCHGVGGMVGMLLTGVFA
Helix 11: HLFVTHLIALVSVSVFAFFGSLLLL

Query ID: H1YF74
query H1YF74 has 12, using last 11 helices
Helix 1: WTLVAAFLVFGMQAGFVMLEAGFA
Helix 2: CIFDTCLCGILFWAVGYAFMFGW
Helix 3: YAATGIPLLAHWIFQYAFA
Helix 4: ILYSIGITGFIYPIIGHWAW
Helix 5: FAGSTVVHTIGGIASLAGAIVL
Helix 6: PHNLTLAAIGGFILWFGW
Helix 7: IAANTTLAACGGGMAAMFIALW
Helix 8: YTINGFLAGLVAITCPCYWVS
Helix 9: LLGLVAGVLTYVFMNVVEWF
Helix 10: HGINGIWGTLSLGLFACGKYGA
Helix 11: AIGSAIITVSTFVVCLVMMYIV

Query ID: H1Y7T6
Helix 1: TAWMLSATGLVLIMTPGLAFFYG
Helix 2: MFQSFICMAIITIIWVVFGFSLAFGNSIYGII
Helix 3: LAPTIPLLLFAMYQLKFAIITPALI
Helix 4: SYIIFICLFFVFIYAPLAHCTWHP
Helix 5: FAGGTVVHMSAGWAALASALYL
Helix 6: RITYVMIGTGLLWFGWFGF
Helix 7: MGANLLAVTALATSTTASASAAVCWIFV
Helix 8: GACIGAVVGLVAITPAAGFV
Helix 9: VAIGIISSVISNMVVEW
Helix 10: VFPCHGVGGMVGMVLTGVFAH
Helix 11: LFLIQLEALVGVSVFAFFGSLLLL

Query ID: G2PRJ6
Helix 1: IGALWITLAAVLVFFMQAGFTLV
Helix 2: LAVGSIMFWAVGYAIMYGSDLVGGGFF
Helix 3: LFFQTVFCATAATIVSGAIAG
Helix 4: YLIFSAILTTLIYPISGSWYW
Helix 5: SVVHAVGGAAALVAAILV
Helix 6: MAFGALGVFILWLGWFGF
Helix 7: IINTNLAAAIGAIAALFFTWA
Helix 8: ISMTLNGALAGLVGITAG
Helix 9: AWGALAIGLICGIVVVASIEFI
Helix 10: AISVHGVCGFLGTVLIGLFAL
Helix 11: SLAYIVWAAVASFIVLFIL

Query ID: Q8BUX5
query Q8BUX5 has 12, using last 11 helices
Helix 1: PSFQDVHVMVFVGFGFLMVFL
Helix 2: FSSVGFTFLVASLTLQWATLL
Helix 3: SLINADFCAGAVLISFGAVLG
Helix 4: AQLLLMALLEAVLFSVNEFIL
Helix 5: AGGSMTIHTFGAYFGLFLSWVLY
Helix 6: LFAMIGTIFLWVFWPSFNSAP
Helix 7: VNTYYSLTASTLSTFALSALV
Helix 8: VQNAALAGGVVVGTSSEMMLT
Helix 9: FGALAAGFLAGTVSTLGYKFF
Helix 10: MPGVLGAILGVVVAALATHEA
Helix 11: LFGMFVTLVFASVGGSLGGLL

Query ID: Q9QUT0
query Q9QUT0 has 12, using last 11 helices
Helix 1: PLFQDVHVMIFVGFGFLMTFL
Helix 2: FSGVGFNLFLAALGLQWGTIM
Helix 3: IYNMINADFSTATVLISFGAV
Helix 4: IQMLIMTILEIAVFAGNEYLV
Helix 5: GASMTIHAFGAYFGLAVAGVL
Helix 6: LFAMIGTLFLWIFWPSFNSAI
Helix 7: IVNTYMSLAACVITAYALSSL
Helix 8: MVHIQNATLAGGVAVGTC
Helix 9: IPLYAAMTIGSIAGIISVLGY
Helix 10: LHGLPGVFGGLASIVAISWGM
Helix 11: AALGSSIGSAIVGGLLTGLIL

Query ID: Q9QXP0
query Q9QXP0 has 12, using last 11 helices
Helix 1: PSFQDVHAMVFVGFGFLMTFL
Helix 2: FSAVGFNFLLAAFGIQWALLM
Helix 3: NIIQADFCVASSCVAFGAVLG
Helix 4: IMTFFQVTLFTVNEFILLNLI
Helix 5: GGSMTIHTFGAYFGLTVTWIL
Helix 6: LFAMIGTLFLWIYWPSFNSAS
Helix 7: LNTYLSLAASVLTTVTVSSIV
Helix 8: MVHIQNATLAGGVGVGTAAEMML
Helix 9: YGALIVGFFCGIFSTLGFAYL
Helix 10: IHNLHGIPGIIGGIVGAVTAA
Helix 11: IFGLLLSLAMALVGGIIVGFI

Query ID: P55012
query P55012 has 12, using last 11 helices
Helix 1: VVIAMATVVTTITGLSTSAIAT
Helix 2: PEFGGAIGLIFAFANAVAVAMYVVGFAETVVELLKE
Helix 3: NDIRIIGAITVVILLGIS
Helix 4: WEAKAQIVLLVILLLAIADFVIGTF
Helix 5: FFSVFAIFFPAATGILAGANI
Helix 6: QSAIPKGTLLAILITTVVYIGIAVSVGS
Helix 7: APLISAGIFSATLSSALASLVSAPKIFQALCKD
Helix 8: GYILTFLIALGFILI
Helix 9: LNVIAPIISNFFLASYALINFSVFHAS
Helix 10: NMWISLIGAILCCIVMFVI
Helix 11: WWAALLTYVIVLGLYIYVTY

Query ID: Q9WTN6
query Q9WTN6 has 12, using last 11 helices
Helix 1: PLTTSFFYVGVLLGSFISGQL
Helix 2: LFLTMAMHTGFSFIQVFSVNF
Helix 3: LLYTLVGMGHISNYVAAFVLG
Helix 4: LGVCIFFAFGFMVLPLFAYFI
Helix 5: RLLLAITLPGVLCGALWWFIP
Helix 6: ILTIMSIILWLTISVGYFGLS
Helix 7: VNCFLLAAVEVPAYVLAWLLL
Helix 8: LFLGGSVLLLVQLVPSDLHYL
Helix 9: LVMVGKFGITSAYSMVYVYTA
Helix 10: VGVSSTASRLGSILSPYFVYL
Helix 11: RLPYILMGSLTILTAIITLFF

Query ID: Q9WVL3
query Q9WVL3 has 12, using last 11 helices
Helix 1: LTWIVGAAGVMESFLIVAMCC
Helix 2: VGLCFYLGTTFAGAMYILGTI
Helix 3: VYGSCALALMAVVVFVGVKYV
Helix 4: LALVFLACVVLSILAIYAGVI
Helix 5: IMTYFTMLVGIYFPSVTGIMA
Helix 6: LAIVTTSFIYLSCIVLFGACI
Helix 7: LVIGMLAWPSPWVIVIGSFFS
Helix 8: PTWALLLTALICETGILIASL
Helix 9: APILSMFFLMCYMFVNLACAV
Helix 10: LCLALMFICSWYYALFAMLIA
Helix 11: NIDVWWIVHDGGMLMLLPFLL

Query ID: Q8R4T9
query Q8R4T9 has 16, using last 11 helices
Helix 1: GGVILVALFISSPLICLHAAI
Helix 2: IYLGLWSYNCVLSCIAIGGMFYA
Helix 3: VVGVPSGTWAFCLSTLTFLLL
Helix 4: GILIVLGLFVQNPWWAISGCL
Helix 5: AIAAGLHGYNGVLVGLLMAVF
Helix 6: WWLLLPVIVMSMTCPILSSAL
Helix 7: LPVFTLPFNIAVTLYLAATGH
Helix 8: GGIFLVALFISSPLICLHAAI
Helix 9: IYFGLCGFNSTLACIAIGGMF
Helix 10: LLAIACALFAAYLGAALANML
Helix 11: VFGLPPCTWPFCLSALTFLLL

Query ID: Q91V14

query Q91V14 has 12, using last 11 helices
Helix 1: IMESFCMVFICCSCTMLTAISMSAI
Helix 2: EFGGAVGLCFYLGTTFAGAMYILGTIEILL
Helix 3: NMRVYGTCVLTCMATVVFVGVK
Helix 4: YVNKFALVFLGCVILSILAIYAGVIK
Helix 5: FTLLVGIYFPSVTGIMAGSNR
Helix 6: SIPTGTILAIATTSAVYISSVVLF
Helix 7: VIVIGSFFSTCGAGLQSLTGAPRLLQAIS
Helix 8: TWALLLTACICEIGILI
Helix 9: LDEVAPILSMFFLMCYMFVNLACAV
Helix 10: WTLSFLGMSLCLALMFIC
Helix 11: WYYALVAMLIAGLIYKYI

Query ID: Q924N4
query Q924N4 has 12, using last 11 helices
Helix 1: ILQAFAIVLICCCCTMLTAISMS
Helix 2: FGGAVGLCFYLGTTFAAAMYILGAIEIFL
Helix 3: NNMRVYGTAFLVLMVLVVFIGVR
Helix 4: YVNKFASLFLACVIVSILAIYAGAIK
Helix 5: FTLLVGIFFPSVTGIMAGSNR
Helix 6: IPIGTILAILTTSFVYLSNVVLF
Helix 7: WVIVIGSFFSTCGAGLQSLTGAPRLLQ
Helix 8: TWALLLTAAIAELGILIASLD
Helix 9: LVAPILSMFFLMCYLFVNLACAL
Helix 10: YYHWALSFMGMSICLALMFISSW
Helix 11: YYAIVAMVIAGMIYKY

Query ID: Q9Z306
query Q9Z306 has 12, using last 11 helices
Helix 1: PLTTSLFFVGVLCGSFVSGQL
Helix 2: VLFATMAVQTGFSFVQIFSTN
Helix 3: VLFAIVGMGQISNYVVAFILG
Helix 4: LGVCTFFAIGYMVLPLFAYFI
Helix 5: MLLLALTLPGLFCVPLWWFIP
Helix 6: IATITVMAVMLWMLTSVGYFA
Helix 7: LNCFLSGLIEVPAYFTAWLLL
Helix 8: YIIAGVLFWGGGVLLLIQVVP
Helix 9: IGLVMLGKFGITSAFSMLYVF
Helix 10: VGITSMASRVGSIIAPYFVYL
Helix 11: LLPYILMGSLTVLIGIITLFF

Query ID: O70577
query O70577 has 12, using last 11 helices
Helix 1: LFQSLVNVGFFIGAVGIGYLA
Helix 2: FCLLVTILINAISGVLMAISP
Helix 3: GLVSKAGWLIGYILITEFVGL
Helix 4: ICYQIAFTVGLLILAGVAYAL
Helix 5: WLQFAVTLPNFCFLLYFWCIP
Helix 6: LILMYNWFTSSVLYQGLIMHM
Helix 7: IYLDFFYSALVEFPAAFIIIL
Helix 8: YPWAVSNMVAGAACLASVFIP
Helix 9: ITVACLGRMGITIAYEMVCLV
Helix 10: LAVLVCSSMCDIGGIVTPFLV
Helix 11: FPLVVFAVVGLVAGGLVLLLP

Query ID: Q9Z0E8
query Q9Z0E8 has 12, using last 11 helices
Helix 1: PLTTSLFFVGVLMGSFISGQL
Helix 2: LFLTMGMQTGFSFLQVFSVNF
Helix 3: VLFVLVGMGQISNYVAAFVLG
Helix 4: LGVCIFYAFGFMVLPLFAYFI
Helix 5: MLLLALTVPGVLCGALWWFIP
Helix 6: VITIMSIILWLTISVGYFGLS
Helix 7: VNCFLLAAVEVPAYVLAWLLL
Helix 8: LFLGGSVLLFMQLVPSELFYL
Helix 9: LVMVGKFGITSAYSMVYVYTA
Helix 10: VGVSSTASRLGSILSPYFVYL
Helix 11: FLPYILMGSLTILTAILTLFF

Query ID: Q8BU91
query Q8BU91 has 14, using last 11 helices
Helix 1: AAMEAERLHVSATLACLTAVIQMALGFMQ
Helix 2: SFIRGFMTAAGLQILISVLKYIF
Helix 3: SLIFALVSGVFLVLVKELNAR
Helix 4: EMIVVVVATAISG
Helix 5: GTAFSLAIVGYVINLAMGRTLASK
Helix 6: NQEMIALGCSNFFG
Helix 7: LSVTLAVDGA
Helix 8: VASLCVSLVVMITM
Helix 9: AVLGALIAVNLKNSLKQLTDPYYLWR
Helix 10: DCCVWVVSFLSSFFL
Helix 11: YGVAVGVAFSILVVIFQTQ

Query ID: A0A4Y6D2A4
Helix 1: WILTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLIWVMMGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IVVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFMMHMLALVLVSVFSFAGSFLLY

Query ID: A0A7Y4MR39
Helix 1: WLLTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLIWVVVGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IVVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFMMHMLALVLVSVFSFGGSFLLY

Query ID: Q1CZ61
Helix 1: WILTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLIWVVVGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IFVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFMMHMLALVLVSVFSFAGSFLLY

Query ID: A0A8E4SIW9
Helix 1: WILTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLIWVVVGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IFVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFMMHMLALVLVSVFSFAGSFLLY

Query ID: A0A4Y6CGF6
Helix 1: WLLTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLIWVVVGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IFVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFLMHMLALVLVSVFSFAGSFLLY

Query ID: A0A7Y4N5I8
Helix 1: WLLTATALVLLMTPGLSFFYG
Helix 2: LLQSFIAMAVISLLWVVVGFSL
Helix 3: LMLFALFQLKFAIITPALITGAFA
Helix 4: AYVLFMVLFTLVIYAPLAHW
Helix 5: TVVHMSAGFAALAGALVLG
Helix 6: APANIPFVMLGTGMLWFGWFGF
Helix 7: ATLAFATTNTASAAAMLGWIAF
Helix 8: GACIGAVVGLVAVTPAAGFI
Helix 9: IFVGLVASFVSNAAVHF
Helix 10: VFPCHGLGGVVGMVLTGVLA
Helix 11: TFMMHMLALVLVSVFSFAGSFLLY

Query ID: A0A1E3PQH0
Helix 1: IGFMLLCSSLIMLMSPGIGLFYAGF
Helix 2: LNLIGITLMAGAVVFLEWFFW
Helix 3: FVFQGTFAVITATIFVGSI
Helix 4: LPALVFTFVWTTVVYNAIVYW
Helix 5: TAVHVSSGFAALAYSWFLG
Helix 6: PIPHNIVLVVLGTVILSIGWLGF
Helix 7: AVYVAVNTLLAGSIGGITWCI
Helix 8: YKWSIIGFCSGIICGLVAIT
Helix 9: VPAWAALIISVLTTLCCNFAT
Helix 10: LDIFAVHGVGGIIGMFLTGIFASAKIA
Helix 11: LGYQLAECITGAAFSFTLSCAILVIMNWI

Query ID: A0A1E3PSK5
Helix 1: IGYILISTAMVFIMIPGLGFLY
Helix 2: MIWACLMACCVAIFQWYFW
Helix 3: LLFAGFQGMFAAVTAAIIMGG
Helix 4: LLPAMIFVFVWLTIVYCPIACWIWG
Helix 5: VEIGSGLGGLGYAFVLGS
Helix 6: HNVSLVTLGTVLLWFGWLGF
Helix 7: AVYAVWNSNICAAFGAMAWCLL
Helix 8: KWSTVAVCSGIISGLVAAT
Helix 9: IPLWASVILGILAGVVCNFA
Helix 10: VAGIIGLIFNALFGADYII
Helix 11: LYKQIAYIAATCGYTFFMTVLICYVI

Query ID: D2V1J4
Helix 1: WVTVSSILVLAMMSALAFFEAGL
Helix 2: LTIFSQIWIGLAVLAVAWILF
Helix 3: FAIFQMMFACITPLLMTGAFA
Helix 4: AYIAFILIWEFLVYYPVAHIIW
Helix 5: FAGGIVIHVQSGIAALVCALVF
Helix 6: LAAIGAALLWMGWFGFNAGSAL
Helix 7: AIAAIVNTQAAACTSTVVWLIMHWI
Helix 8: LVSLLNGSIAGLAGITPA
Helix 9: VHAAMVLGLILGAFSYLGIYLL
Helix 10: VSSVHGITGLIGSIAIGFCATTSV
Helix 11: LVGVGLAFFWSGLITFILAISI

Query ID: D2V6Q5
Helix 1: LWVLVCTMMVFLMQTGFSFLEAGSV
Helix 2: NLLGTCMVTIAWWILGYGLA
Helix 3: WHIWVFEWAFVADTTTILS
Helix 4: YLIYAAIFAGWIYPVVAHWFW
Helix 5: GVIDFAGCAVVHLLGGVASLCGAVI
Helix 6: IPFQFLGTLLLFLGWFGF
Helix 7: MSIVAAKATVNTVLAAASAGLTGAFI
Helix 8: FLVWDAGNLQNCVLAGLVAVTAG
Helix 9: PWGAVCIGIIAAPIYIGLSFLL
Helix 10: VPVHGGCGLWGLIAAGIFSSPRGV
Helix 11: FGMQFLGAVVVIAWGAAWCIPLFIIM

Query ID: D2V6P8
query D2V6P8 has 12, using last 11 helices
Helix 1: MLDVGIMVFVGFGFLMTFL
Helix 2: AFGLNFFISAFIFQWGIL
Helix 3: LVEGHFAAASFLVSFGVIIG
Helix 4: LTIAGLIHTFFYALNYYI
Helix 5: GSMFIHLFGAVFGLLCSFVL
Helix 6: FFSLIGTIFLFLCWPSFNAA
Helix 7: FINTILSLMGSAVASFFCSRLV
Helix 8: NGTLAGGVAIGAVADFVI
Helix 9: LTVGVVSGFISVFGFRFF
Helix 10: CVPGFIGGVGAIIATGVAAA
Helix 11: WGYQFATLAITIGIAIIGGVVAGLVI

Query ID: D2VMN0
query D2VMN0 has 12, using last 11 helices
Helix 1: FVFYLVLFELFYVSMFWIFF
Helix 2: VAMMTLLGLGLSMSCIKNA
Helix 3: MTILLAALSFQFSIIAQGFW
Helix 4: WLVHGFYGAFAVLISTSCVIG
Helix 5: LILMAFSEVFIYSVNYFCIILVLGAI
Helix 6: MFIHVFGACYGLAASWSLY
Helix 7: IAIIGTVLLWVLMPSFNAAL
Helix 8: MTTFIAMAASCVIHFVVMRLL
Helix 9: LTIGLVAGALTGLGLCVLQPLI
Helix 10: FSTHLLIGVYGGLVSIVATGNAI
Helix 11: WGFQICALCITVVTSIAGGFLHGFV

Query ID: C8XBX8
Helix 1: TAWMLAAASLVLLMTPALAFFY
Helix 2: MMMMSFGAMAIVGPIWMLW
Helix 3: AVGYQATFAIITVALISGAIA
Helix 4: TWLVFSGLWVTLVYGPLAHMVWG
Helix 5: FAGGTVVHINAGMAGFMLALIIG
Helix 6: PHNLPFVMLGAGLLWFGWFGF
Helix 7: AWLNTCVATCVAALGWLIV
Helix 8: HATSLGAASGIVAGLVAITPA
Helix 9: IVGAMFIGVIAGAVCALAVGL
Helix 10: VVGVHLVGGIVGTVLIGLFA
Helix 11: LVALIAVVISGVMTLIIGYAL

Query ID: C8XB51
Helix 1: TAWILASSMAVSLMIPGLALFY
Helix 2: MMMMVLGSVAVTGVIWVLFGYSAV
Helix 3: ILVAAFQALFAAITVALIAGAVA
Helix 4: AWMVFAGLWVTLVYLPVAHWVF
Helix 5: AIDFAGGTAVHINAGIAGLAVVLVLG
Helix 6: HNLPATVLGAGILWFGWFGF
Helix 7: LAAGTAASVVFLNTFAAACTALLAWLVV
Helix 8: HATTLGAASGLIAGLVAI
Helix 9: AVSPVGALIIGVVAGTVCPFAIGL
Helix 10: VVGVHLVGGILGTLLIGLLA
Helix 11: LGVQAVAAGAVIAYSFVVTSIIALVL

Query ID: L0JT30
Helix 1: NYMWILVATFLIFFMHAGF
Helix 2: LLTWSVGVTVFFLIGVGVEGV
Helix 3: WLYGAVFAMTAATIVSGAVAG
Helix 4: YVSYTFLLAAVIYPVVTGLTW
Helix 5: FAGGMIVHGMGGIAGLTAAWVL
Helix 6: LTFAVLGTLILAFGWYGF
Helix 7: RVALTTTAAMACGAMGAGLVAWL
Helix 8: TLYVANGLLAGLAAITAI
Helix 9: WWGAFVVGGLAGVQLPLVF
Helix 10: VCAVFPVHGSAGVLGTLLFPFVA
Helix 11: FVAQVIGVVVIAAWTIVATGVIWYAF

Query ID: A0A1I0C958
Helix 1: TIWVLLAAALVFFMQAGFAMV
Helix 2: FSIGSLTYWIVGFSIMFGISSNGFIGN
Helix 3: AFLIFQTVFCATAATIVSGAMA
Helix 4: AYLIYSFFISLIIYPVVGHWTWG
Helix 5: FAGSTVVHSVGGWSALMGAWIIG
Helix 6: AIAIPGHSLTLGALGVFILWLGW
Helix 7: IFVTTNLAAAAGAFITMVITWL
Helix 8: VSMTLNGALAGLVGITAG
Helix 9: AVGSVAIGLIAGVTVVFGIEFI
Helix 10: AIGVHGICGAVGTVSVGLFAV
Helix 11: LLFVQVLGVFAVALWTLATSFIVF

Query ID: A0A1I3M286

Helix 1: LLWALTVTFLIFFMHAGFAML
Helix 2: WAVGIGVFFVIGMGISNNVGS
Helix 3: WAMWLFSAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPVVAALVWYA
Helix 5: ILAAFGFSDFAGGMVVHGVGGVAGLTAAWIL
Helix 6: LTFAVLGTLILCFGWFGFNVGTAATVI
Helix 7: YVGSVAMVTALGMGLGAIGASTVSLY
Helix 8: TLYVANGMLAGLVGVTGPT
Helix 9: MGAIAIGFLAGAQLPVVF
Helix 10: VCAVFPVHGSAGMLGLILYPLW
Helix 11: IVGVAVITIWTVAATAAVWGAF

Query ID: L0AHQ0
Helix 1: LLWALTVTFLIFFMHAGFAML
Helix 2: WAVGIGVFFVIGMGISNNVGS
Helix 3: WAMWLFSAVFAMTAATIVSGAVAG
Helix 4: YVTYTFLLAAVIYPVVAALVWYA
Helix 5: ILAAFGFSDFAGGMVVHGVGGVAGLTAAWIL
Helix 6: LTFAVLGTLILCFGWFGFNVGTAATVI
Helix 7: YVGSVAMVTALGMGLGAIGASTVSLY
Helix 8: TLYVANGMLAGLVGVTGPT
Helix 9: MGAIAIGFLAGAQLPVVF
Helix 10: VCAVFPVHGSAGMLGLILYPLW
Helix 11: IVGVAVITIWTVAATAAVWGAF

Query ID: A0A5P9P1L2
Helix 1: TWILIVTFLIFFMHAGFAMLEA
Helix 2: LTKNLLTWSVGVTVFFLIGVGI
Helix 3: WIGWLYGAVFAMTAATIVSGAVAG
Helix 4: YIGYTFLLAAVIYPVVTGITWAGGYI
Helix 5: AGGMIVHGMGGIAGLTAAWIL
Helix 6: LTFAVLGTLLLAFGWYGF
Helix 7: RVAMATTIAMACGAMGAGLVAWL
Helix 8: TLYVANGLLAGLVGITAI
Helix 9: WWGAFVVGGLAGAQLPIVFGFV
Helix 10: VFPVHGSAGVLGTLLFPFVA
Helix 11: FIAQLTGVVLITVWTVGATALIWFVF

Query ID: G0V8D6
Helix 1: VAFLVIGTALVFFMVPGLGFLY
Helix 2: LIWVVLMATLVGMVQWYFW
Helix 3: IAFASFEMTFMCVALSIVAGA
Helix 4: VFIFIFATLVYCPICYWIW
Helix 5: VEILSAVAGFVYSIFLGR
Helix 6: HNVSMVTLGTSVLWFGWLLF
Helix 7: SVYAFMNTNISAATGGMTWCLL
Helix 8: KWSTVGLCSGIICGLVAAT
Helix 9: ITLYGSFIQGIISGIVCNFA
Helix 10: IAGIVGLIFNALFAADWII
Helix 11: MYKQIAYIAATVGYCAVVTALICFII

Query ID: G0VI62
Helix 1: MVWLGVSAAGVWIMVPGIGLLY
Helix 2: LLWASMMASAVCIFQWFFW
Helix 3: VLWAGFQGMFAAVTGILMLG
Helix 4: MVFLFIWMTIVYCPIACWTWNP
Helix 5: YAGGGVVHINSGHGALVYALI
Helix 6: ITSVVLGTVFLFYGWLFF
Helix 7: AWYSMFSTSLAASCGGLTWMFI
Helix 8: WTTVGLCSGIIAGLVGITPA
Helix 9: IWASVIIGILTAAGCNFAV
Helix 10: LDCWALHGVGGCIGSALTGIFSA
Helix 11: YQLAAIMSSIAWCMTCTAIILLTM

Query ID: G0V6N4
query G0V6N4 has 13, using last 11 helices
Helix 1: VFIFGYAWYTLWSLLVGISRYA
Helix 2: TFFFFGRGCQGIGAAALFPSSLALL
Helix 3: IVFSLYGFCVPLGVVVGGVFSAIFTQLA
Helix 4: YWSMAIVSAFFTLISCFYIPP
Helix 5: FDYLGTFLYVASLLLFAVCW
Helix 6: QVYVTLIVSLVCFVAMVIV
Helix 7: ALLVVFFSYLSFTIWLFY
Helix 8: FVPLSIAGFIAALFSILLIS
Helix 9: IRLLAGACSFLLAHILFIT
Helix 10: FLTIIIISIGLDISFPSATLLL
Helix 11: FVKAIHIAAAVGIGASGIAVVVGLY

Query ID: B9L7N1
Helix 1: TAWMMVATAFVMLMTPAGLALFYA
Helix 2: YMMVFSAFAVATVVWVFWGY
Helix 3: YPTYVFIAFQGTFAAITVAIAS
Helix 4: WLIFVVLWVTFVYAPVAHMVWG
Helix 5: FAGGTVVHMNGGLAGLVAALMI
Helix 6: MPSSVILTALGAALLWFGWFGF
Helix 7: AGSAFIMTNFAAAAAAVTWIILDYI
Helix 8: LLGAASGAVAGLVAITPAA
Helix 9: VGALVIGIGGSLTGFFGVTVL
Helix 10: AFGIHFIAGLWGAIATGFF
Helix 11: IWVQIESVLVTIVFVAIMTAIVL

Query ID: B9L862
Helix 1: VIDTFFALFAFTLIILMVPGFAML
Helix 2: AVLTVNTMIYIVASLVFFLWGY
Helix 3: MSMYAAFLFQMAFVGKTVN
Helix 4: IVPLAIFTLFMAGLIYPLVVNW
Helix 5: LAGSTVIHSTGAWALLAAILIIG
Helix 6: VRVIPASNIPLVVLGALLLWIGW
Helix 7: VALVVMNTNNAGLIGGLVVMILGYL
Helix 8: ITMILNGALGGLVAITAGA
Helix 9: YAALIIGAIGGALVFYAV
Helix 10: VGALSVHLVNGIWGTIATGIW
Helix 11: GVVVVAVFAFVASYIIIFVI

Query ID: D6HAK3
query D6HAK3 has 12, using last 11 helices
Helix 1: AWVMTAAALVLLMTLPGLALFYG
Helix 2: MMHSFSIATLVGILWVAVGYSLA
Helix 3: VFMFFQMTFAIISTAIITGAFA
Helix 4: AMMLFSGIWFLLVYVPGAHWVWG
Helix 5: YAGGTVVHINAGIAGLVAALVLG
Helix 6: PHNMAMTLIGAAMLWFGWF
Helix 7: AAAGMAMAVTQVSAVFGAAGWL
Helix 8: ALGLASGAVSGLVGITPAAGF
Helix 9: AAAIGILTAAACFVSVTVV
Helix 10: AFGIHGFGGLVGGILTGIFF
Helix 11: GFIMAAYSGLMSWAILKAVG

Query ID: A0A1D3GAE9
Helix 1: AWVMTAAALVLLMTLPGLALFYG
Helix 2: MMHSFSIATLVGILWVAVGYSLA
Helix 3: VFMFFQMTFAIISTAIITGAFA
Helix 4: AMMLFSGIWFLLVYVPGAHWVWG
Helix 5: YAGGTVVHINAGIAGLVAALVLG
Helix 6: PHNMAMTLIGAAMLWFGWF
Helix 7: AAAGMAMAVTQVSAVFGAAGWL
Helix 8: ALGLASGAVSGLVGITPAAGF
Helix 9: AAAIGILTAAACFVSVTVV
Helix 10: AFGIHGFGGLVGGILTGIFF
Helix 11: GFIMAAYSGLMSWAILKAVG

Query ID: B4RJL6
query B4RJL6 has 12, using last 11 helices
Helix 1: AWVMTAAALVLLMTLPGLALFYG
Helix 2: MMHSFSIATLVGILWVAVGYSLA
Helix 3: VFMFFQMTFAIISTAIITGAFA
Helix 4: AMMLFSGIWFLLVYVPGAHWVWG
Helix 5: YAGGTVVHINAGIAGLVAALVLG
Helix 6: PHNMAMTLIGAAMLWFGWF
Helix 7: AAAGMAMAVTQVSAVFGAAGWL
Helix 8: ALGLASGAVSGLVGITPAAGF
Helix 9: AAAIGILTAAACFVSVTVV
Helix 10: AFGIHGFGGLVGGILTGIFF
Helix 11: GFIMAAYSGLMSWAILKAVG

Query ID: Q5FA36
Helix 1: AWVMTAAALVLLMTLPGLALFYG
Helix 2: MMHSFSIATLVGILWVAVGYSLA
Helix 3: VFMFFQMTFAIISTAIITGAFA
Helix 4: AMMLFSGIWFLLVYVPGAHWVWG
Helix 5: YAGGTVVHINAGIAGLVAALVLG
Helix 6: PHNMAMTLIGAAMLWFGWF
Helix 7: AAAGMAMAVTQVSAVFGAAGWL
Helix 8: ALGLASGAVSGLVGITPAAGF
Helix 9: AAAIGILTAAACFVSVTVV
Helix 10: AFGIHGFGGLVGGILTGIFF
Helix 11: GFIMAAYSGLMSWAILKAVG

Query ID: A7SGD4
Helix 1: WILTCSFIIFTMQSGFGLLE
Helix 2: ILVKNIADVLFGGLAFWMFGYAF
Helix 3: FFFQASFSTTATTIVSGSMA
Helix 4: SYCLFSFMNTIIFCLPAHWLW
Helix 5: VHLVGGVTGLTATIMLKP
Helix 6: TALLGLFMLWWGWLALNCGSTFGVT
Helix 7: VAARAAVMTINASVGGGTTAILLS
Helix 8: LLIRGILGSLVSISGLCGW
Helix 9: AILVGAVGSLIACYGVSLL
Helix 10: VSIHMFPAIWAMVAAGIFL
Helix 11: TLGVELLATVVVSVWCALMATVILFFI

Query ID: A7RNC3
Helix 1: VMSSAFIIFTMQSGFGLLESGMV
Helix 2: NVVDVIFGGLSFWAFGYAFA
Helix 3: FFFQLSFATTAVTIVSGAMA
Helix 4: SYCLFSSLGILVYCFPAHWVW
Helix 5: LATLGAVDIAGCGVVHVVGGVTGLVATIIL
Helix 6: PLSMGSPVTAILGLFVLWWGW
Helix 7: ARAAVNTLSASIGGGIFAFS
Helix 8: VSYVVVGILGGLVSVTGICPLA
Helix 9: ILIGTIGGVLSCFGRNLI
Helix 10: LAAHILSGIWGLVSVGFFT
Helix 11: GWLLGIQLLTVVALIAWSAAVSFILLMIL

Query ID: A7SQ16
Helix 1: ATWILTSAFIIFTMQSGFGLL
Helix 2: VIYGGLSYWLFGFAFSFG
Helix 3: YFFQLSFATTSTTIVSGAMA
Helix 4: AYTLFSFINTLSFSFPAHWIW
Helix 5: IDVAGCGPVHLVGGVSGLVATLML
Helix 6: PTNVLLGTFMLWWGWLGF
Helix 7: AVVTLNGSIGGGISGMVYSYL
Helix 8: LIDTFATGILGGLVSITAICAI
Helix 9: AILIGAIGGAIACGGCSLL
Helix 10: VPTHFFASVWGLIVVGLLV
Helix 11: WRLLGAQLLAIVCISVWSAVMTFVMLCGV

Query ID: A7S3L2
Helix 1: ATWILTSAFIIFTMQSGFGLL
Helix 2: VIYGGLAYWVFGFALSFGT
Helix 3: YFFQLSFSTTATTIVSGAMA
Helix 4: AYTLFSFVNTITYCFPAHWIW
Helix 5: VDIAGGSAVHLVGGISGLVATLIL
Helix 6: NVLLGTFMLWWGWLGFNCGSTFGI
Helix 7: AVVTINGSVGGGVLGMSYSYL
Helix 8: NIHVFVTGILGGLVSITAICSV
Helix 9: ALVIGSIGALIACSGCSLL
Helix 10: VPTHAFAGIWGLIAVGLFA
Helix 11: PWRFLGVQLLLIVAVVSWGAVTTFLEL

Query ID: A7S731
Helix 1: ATWILTSAFIIFTMQSGFGLL
Helix 2: VIYGGLAYWIFGFAFSFGQPI
Helix 3: YFFQLSFATTATTIVSGAMA
Helix 4: AYILYSFLNTLSYCFPAHWVW
Helix 5: VHLVGGVSGLVATLFLGA
Helix 6: NVLLGTFMLWWGWLGFNCGSTFGI
Helix 7: AVVTINGSIGGGIFATFYSY
Helix 8: LMVDVFVTGILGGLVGITAICAVV
Helix 9: LLIGFIGGMIACVGDALV
Helix 10: IATHGMAGIWGLLAVGLFV
Helix 11: WHLLGIQLLVVVSIGAWAAVTNFILLYVI

Query ID: A7SED8
query A7SED8 has 12, using last 11 helices
Helix 1: IYYPMFQDVHVMIFLGIGLLLAFL
Helix 2: FFAAAILCEWSTIINGVFWHII
Helix 3: FSAINADFAAAVILISYCVV
Helix 4: LQLLVMGVIELAVYVLNSWI
Helix 5: GISDIGASITIHMFAAYFGL
Helix 6: YHNDVFCLVGTIFLWLYW
Helix 7: NTYYSMLGACVMVFALSPM
Helix 8: VQNATLAGGVAIGTASNMIV
Helix 9: MLIGSIGGAMCTLGYVYL
Helix 10: ALPAFLSGIASAIASSLAAA
Helix 11: AGFQVAAMFVTIGISLLSGILTGFLIKLWI

Query ID: A7SED7
query A7SED7 has 12, using last 11 helices
Helix 1: IYYPMFQDVHVMIFLGIGLLLAFL
Helix 2: FFAAAILCEWSTIINGVFWHII
Helix 3: FSAINADFAAAVILISYCVV
Helix 4: LQLLVMGVIELAVYVLNSWI
Helix 5: GISDIGASITIHMFAAYFGL
Helix 6: YHNDVFCLVGTIFLWLYW
Helix 7: NTYYSMLGACVMVFALSPM
Helix 8: VQNATLAGGVAIGTASNMIV
Helix 9: MLIGSIGGAMCTLGYVYL
Helix 10: ALPAFLSGIASAIASSLAAA
Helix 11: AGFQVAAMFVTMGISLLSGIL

Query ID: A0A1E5TK21
Helix 1: VLFLFLCTLLVWLMTPGLSLFY
Helix 2: IVVVTFAWVILGFSLSFGSGEIFLGGF
Helix 3: IPLALFMLFQLMFCTIAVSILS
Helix 4: YLIFVFLWVIIVYSPVAHWVWG
Helix 5: YAGGTVVHITSGISGLVLAVMIGA
Helix 6: LIITLIGGILVWVGWYGF
Helix 7: AMTSFVNTVLAASAGSLGWSVM
Helix 8: TTSLIGMLSGMLAGLVAI
Helix 9: FVNYMSAIVIAFIGGVSCYFAI
Helix 10: ALDAFGIHGIGGIVGAILTGVFQS
Helix 11: VWVQFVAVFVTVIFSGAMTFLIA

Query ID: A0A6A1TYJ4
Helix 1: WMLISTILVLLMTIPGLALFY
Helix 2: VLMQVFMITAVVMIIWVTYGY
Helix 3: LTFVCFQMTFACITPALIVGAFA
Helix 4: AVMLFVILWVTFIYFPMAHMVWFWG
Helix 5: FAGGTVVHINAGIAGLVGAIML
Helix 6: APHSMTLTMVGASLLWVGWF
Helix 7: AYASLAMINTFVATAAAAVSWCL
Helix 8: LGAASGAVAGLVAVTPAAGFA
Helix 9: IVLGLIVSPVCYFFVDVV
Helix 10: VFGVHCVGGILGAIGTGILVNPALGGAGIV
Helix 11: AQFKGVLTTLLWSGIGSAILY

Query ID: A0A0T7FAP8
Helix 1: WMLISSILVLLMIVPGLALFY
Helix 2: VLMQVMMIAAVAMIVWVTY
Helix 3: LAFVCFQMTFAAITPALIIGAFA
Helix 4: AVILFTILWLTFVYFPMAHMVWFW
Helix 5: LIFGFGAIDFAGGTVVHINAGIAGLVGAIMV
Helix 6: APHSMTLTMVGAALLWVGWF
Helix 7: AYAALAMMNTFVATAAAIVGWAL
Helix 8: LGAASGAVAGLVVITPAAGF
Helix 9: AIIMGLIVSPVCYFFVSTV
Helix 10: VFGVHGVGGIIGAILTGVFVNPALGGAGIV
Helix 11: AQFKGVIVTVLWSGIGSAILY

Query ID: A0A0T7GZ59

Helix 1: WMLISSILVLLMIVPGLALFY
Helix 2: VLMQVMMIAAVAMIVWVTY
Helix 3: LAFVCFQMTFAAITPALIIGAFA
Helix 4: AVILFTILWLTFVYFPMAHMVWFW
Helix 5: LIFGFGAIDFAGGTVVHINAGIAGLVGAIMV
Helix 6: APHSMTLTMVGAALLWVGWF
Helix 7: AYAALAMMNTFVATAAAIVGWAL
Helix 8: LGAASGAVAGLVVITPAAGF
Helix 9: AIIMGLIVSPVCYFFVSTV
Helix 10: VFGVHGVGGIIGAILTGVFVNPALGGAGIV
Helix 11: AQFKGVIVTVLWSGIGSAILY

Query ID: A0A068SVR1
Helix 1: WMLISTILVLLMTIPGLALFY
Helix 2: VLMQVFMITAVVMIIWVTYGY
Helix 3: LTFVCFQMTFACITPALIVGAFA
Helix 4: AVMLFVILWVTFIYFPMAHMVWFWG
Helix 5: FAGGTVVHINAGIAGLVGAIML
Helix 6: APHSMTLTMVGASLLWVGWF
Helix 7: AYASLAMINTFVATAAAAVSWCL
Helix 8: LGAASGAVAGLVAVTPAAGFA
Helix 9: IVLGLIVSPVCYFFVDVV
Helix 10: VFGVHCVGGILGAIGTGILVNPALGGAGIV
Helix 11: AQFKGVLTTLLWSGIGSAILY

Query ID: A0A068TC78
Helix 1: MLISTILVLLMTIPGLALFY
Helix 2: VLMQVFMITAVVMIIWVTYGY
Helix 3: LTFVCFQMTFACITPALIVGAFA
Helix 4: AVMLFVILWVTFIYFPMAHMVWFWG
Helix 5: FAGGTVVHINAGIAGLVGAIML
Helix 6: APHSMTLTMVGASLLWVGWF
Helix 7: AYASLAMINTFVATAAAAVSWCL
Helix 8: LGAASGAVAGLVAVTPAAGFA
Helix 9: IVLGLIVSPVCYFFVDVV
Helix 10: VFGVHCVGGILGAIGTGILVNPALGGAGIV
Helix 11: AQFKGVLTTLLWSGIGSAILY

Query ID: A0A2G6JLT9
Helix 1: LFILMGAIMVFAMHAGFAFLEV
Helix 2: LVKILTDFGFSAMAYFFVGYWIA
Helix 3: LVKFFFLMTFAAAIPAIVSGG
Helix 4: FWPFLIASALIVAFVYPFF
Helix 5: FAGSIVVHGVGGWLALVAVLML
Helix 6: LVAFPPSNIPFLALGAWILCIGWFG
Helix 7: ISGLVAVNTLMAMVGGIITALIF
Helix 8: FIHNGPLAGLVAVCAGSDVM
Helix 9: LIVGAVAGATFVILFTKL
Helix 10: VWPLHGVCGAWGAIACGIFG
Helix 11: IISQMIGTAAGIAVALVGGAIVYGGV

Query ID: A0A7U8C744
Helix 1: FYFLVCGALVMWMAAGFAMLEAGLV
Helix 2: NIALYAISCIMYLVCGYAIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFAVVMTGIIYPM
Helix 5: LGFSDFAGSGIVHMAGAAAALAGVLVL
Helix 6: AVNAIPGANLPLATLGTFVLWLGW
Helix 7: VAVVFMNTNAAAAGGVVAALIVA
Helix 8: ADLTMALNGALAGLVAITA
Helix 9: SALQATLFGAMGGALVVFSIL
Helix 10: GAISVHGVVGLLGLLLVPVT
Helix 11: FSGQIIGALTIFVWVFGTSLVVWLAL

Query ID: A0A7U8C2Y6
Helix 1: LFILMGAIMVFAMHAGFAFLEV
Helix 2: LVKILTDFGFSAMAYFFVGYWVA
Helix 3: LVKFFFLMTFAAAIPAIVSGGI
Helix 4: WPFLIASALIVAFVYPFFEGIIWN
Helix 5: FAGSVVVHGVGGWLALVAVLML
Helix 6: LVAFPPSNIPFLALGAWILCIGWFG
Helix 7: ISGLVAVNTLMAMVGGIITALIF
Helix 8: FIHNGPLAGLVAVCAGSDVM
Helix 9: LVVGAVAGAIFVVLFTI
Helix 10: GVWPLHGVCGAWGAIACGIFG
Helix 11: LMSQIIGTVAGIAVAVIGGVIVYGGV

Query ID: A0A7R6PER3
Helix 1: FYFLICGALVMWMAAGFAMLEAGLV
Helix 2: NISLYAIACTMYLLCGYFIM
Helix 3: FFFQVVFVATAMSIVSGAVA
Helix 4: LWAFLAFAVVMTGFIYPV
Helix 5: AGSGIVHMAGASAALAGVLML
Helix 6: LPLATLGTFILWMGWFGF
Helix 7: VFINTNAAAAGGCIAALIVA
Helix 8: ADLTMALNGALAGLVAITA
Helix 9: TALSSTVIGAVGGVIVVFSIL
Helix 10: GAISVHGVVGIWGLLAVPLN
Helix 11: FGAQLLGIISIFAWVFIASLVVWSIL

Query ID: A0A7R6PPH5
Helix 1: LFILMGAIMVFAMHAGFAFLEV
Helix 2: LVKIMTDFGFSAVAYFFIGYWIA
Helix 3: LVKFFFLMTFAAAIPAIVSGGI
Helix 4: WPVLFASTLTVAFVYPLFEGIIWN
Helix 5: FAGSVVVHGVGGWIALVAVLFL
Helix 6: LVAFPPSNIPFLALGAWILSIGWFG
Helix 7: VSGLVAVNSLMAMVGGIIAALVV
Helix 8: FIHNGPLAGLVAVCAGS
Helix 9: IGALVVGAIAGVVFVWMFT
Helix 10: LGVWPLHGLCGVWGGIAAGIFG
Helix 11: LMSQVIGTFAGILVAVVGAAIVYGGI

Query ID: A0A0U1NJW3
Helix 1: IGPYIMTTLLFLVGGFLVFWMAAGF
Helix 2: IALFSLAGIMYWAVGFNLMY
Helix 3: FFFQLMFCATTASIVSGTLA
Helix 4: LWPFLIFVVVLTGFIYPI
Helix 5: AGSTLVHAAGGFAALAGALVL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNMAASAGAVAALLL
Helix 8: MVLNGALAGLVSITAGPL
Helix 9: GALWIGAVGGVIVVVAVPMLD
Helix 10: VVGAIPVHLIAGFWGTMVVPVY
Helix 11: FVTQFIGFAAIGIFVFVVSLIAFTL

Query ID: A0A0B0E8R7
Helix 1: WMLVCTALCWQITPAIGFLYA
Helix 2: AALTMVLQSLFCACACGIQFWI
Helix 3: ILYAAFGFTFVSCTAMILAGA
Helix 4: LLPSMLFLLCWTTFVYYFIAYW
Helix 5: GPVHIASGFGALAWSLMLG
Helix 6: SPLLMCLGTVFIWFGWFAF
Helix 7: SIYAIVNTNLAGCGGGVGWVLI
Helix 8: KFSLVGFCSGIIAGLVGIT
Helix 9: VPVYVASLIGFLTSATCYYAA
Helix 10: LDIFAIHGVGGYVGDLLTGIFA
Helix 11: FQFAGATTAAAWSFVVSCILLFII

Query ID: A0A0B0DML0
Helix 1: AFILVASCMVLIMIPGIAFLY
Helix 2: LIWVCMMSSSVVMFQWYFW
Helix 3: LLYAFYQMQFVGVTAALVVGA
Helix 4: VFIFIWATLVYCPLCCWAWNV
Helix 5: YAGGGPVEIGSGVSALAYSWVLG
Helix 6: PHNISLITIGTVFLWFGWLGF
Helix 7: AAMACWNSCLTAMFAAMTWTLL
Helix 8: KWSLVGWCSGTISGLVAAT
Helix 9: IPPWASIILGVVTGIVCNF
Helix 10: ALGGVVGLIFNGFFAADYIIG
Helix 11: LYIQIAYVCATMGYSFVMSAILA

Query ID: Q8X0D3
Helix 1: FGWIMTCTALVLLMVPGVGFFY
Helix 2: LIWLSLMSIAIVGFQWFFW
Helix 3: IPDLLFCLYQGMFAAITPALAI
Helix 4: ALVFMFIWTTIVYDPIAYWTW
Helix 5: LDFAGGTPVHISSGAAALAYSL
Helix 6: VTHVVLGTVFLWVGWFGF
Helix 7: AVMACIVTHIAACVGGLTWVLL
Helix 8: GFCSGAIAGLVAITPAAGYV
Helix 9: FIFGVVGGISCNFATKLKFLL
Helix 10: HGVGGIVGNLLTGIFAADYIAA
Helix 11: GFSYSFVMTCVILFLLNLV

Query ID: Q1K8A3
Helix 1: FGWIMTCTALVLLMVPGVGFFY
Helix 2: LIWLSLMSIAIVGFQWFFW
Helix 3: IPDLLFCLYQGMFAAITPALAI
Helix 4: ALVFMFIWTTIVYDPIAYWTW
Helix 5: LDFAGGTPVHISSGAAALAYSL
Helix 6: VTHVVLGTVFLWVGWFGF
Helix 7: AVMACIVTHIAACVGGLTWVLL
Helix 8: GFCSGAIAGLVAITPAAGYV
Helix 9: FIFGVVGGISCNFATKLKFLL
Helix 10: HGVGGIVGNLLTGIFAADYIAA
Helix 11: GFSYSFVMTCVILFLLNLV

Query ID: Q7S5K0
Helix 1: WMLVCTALCWQITPAIGFLYA
Helix 2: AALTMVLQSLFCACACGIQFWI
Helix 3: ILYAAFGFTFVSCTAMILAGA
Helix 4: LLPSMLFLLCWTTFVYYFIAYW
Helix 5: GPVHIASGFGALAWSLMLG
Helix 6: SPLLMCLGTVFIWFGWFAF
Helix 7: SIYAIVNTNLAGCGGGVGWVLI
Helix 8: KFSLVGFCSGIIAGLVGIT
Helix 9: VPVYVASLIGFLTSATCYYAA
Helix 10: LDIFAIHGVGGYVGDLLTGIFA
Helix 11: LQFAGATTAAAWSFVVSCILLFII

Query ID: Q7SEH0
Helix 1: AFILVASCMVLIMIPGIAFLY
Helix 2: LIWVCMMSSSVVMFQWYFW
Helix 3: LLYAFYQMQFVGVTAALVVGA
Helix 4: VFIFIWATLVYCPLCCWAWNV
Helix 5: YAGGGPVEIGSGVSALAYSWVLG
Helix 6: PHNISLITIGTVFLWFGWLGF
Helix 7: AAMACWNSCLTAMFAAMTWTLL
Helix 8: KWSLVGWCSGTISGLVAAT
Helix 9: IPPWASIILGVVTGIVCNF
Helix 10: ALGGVVGLIFNGFFAADYIIG
Helix 11: LYIQIAYVCATMGYSFVMSAILA

Query ID: A0A0B0DUN5
query A0A0B0DUN5 has 12, using last 11 helices
Helix 1: MLVIGYTWYAVWTMICGLSVF
Helix 2: IMMIVCRAFQGVGPSILLPNGLAIL
Helix 3: MVFALFGAMAPGGCVLGSAMAG
Helix 4: WWPWAFWSFAIALLCLAGAAQLII
Helix 5: LDAIGGTVGVSALILINIAW
Helix 6: YTYILLIIGILLVPLFFWI
Helix 7: IAFVLGCLACGWGSFGTWLF
Helix 8: YFSPVSVSGAVAAVVTGIVL
Helix 9: WTVVCAMSAFFTGNMLLVT
Helix 10: AASLINTVVNYSISIGLGFAT
Helix 11: YKAACWVAVGLTAFGLVLSVVYLMV

Query ID: A0A0B0DW36
query A0A0B0DW36 has 12, using last 11 helices
Helix 1: YGNLSWFSAAYSMTVGTFMLP
Helix 2: LIVMIGWAWFSLWSLVCGSCGPTNLIW
Helix 3: FAFACFGAAGPSGATAGAILSSL
Helix 4: SWHWCFWFLSMTCAVLVMMSWFII
Helix 5: YIRALLVLGLLSLLAFVCV
Helix 6: QAAFVLAIVFTGWSSHGIWVYY
Helix 7: TSPVAGTGIFFAMLTVYLL
Helix 8: SLIIFIAMFFFFVGTLLLVLT
Helix 9: YWANIFVAVLLMPGAMNLSFPAATILV
Helix 10: AASLVATVVNYSISCGLGLAGSI
Helix 11: MAVWLGVALAGFGVVIAGGVWGVQLLV

Query ID: Q7S6U7
query Q7S6U7 has 12, using last 11 helices
Helix 1: MLVIGYTWYAVWTMICGLSVF
Helix 2: IMMIVCRAFQGVGPSILLPNGLAIL
Helix 3: MVFALFGAMAPGGCVLGSAMAG
Helix 4: WWPWAFWSFAIALLCLAGAAQLII
Helix 5: LDAIGGTVGVSALILINIAW
Helix 6: YTYILLIIGILLVPLFFWI
Helix 7: IAFVLGCLACGWGSFGTWLF
Helix 8: YFSPVSVSGAVAAVVTGIVL
Helix 9: WTVVCAMSAFFTGNMLLVT
Helix 10: AASLINTVVNYSISIGLGFAT
Helix 11: YKAACWVAVGLTAFGLVLSVVYLMV

Query ID: Q7S343
query Q7S343 has 12, using last 11 helices
Helix 1: YGNLSWFSAAYSMTVGTFILP
Helix 2: LIAMIGWAWFSLWSLVCGSCGPTNLIW
Helix 3: LAFACFGAAGPTGAAAGAILSSL
Helix 4: SWHWCFWFLSMTCAVLVMMSWFII
Helix 5: YIRALLVLGLLSLLAFVCV
Helix 6: HAAFVLAIVFTGWSSHGIWVYY
Helix 7: TSPVAGTGIFFALLTVYLL
Helix 8: SLIMFIAMFFFFLGTLLLALT
Helix 9: YWANTFVAVLLMPGAMNLSFPAATILL
Helix 10: AASLVATVVNYSISCGLGLAGSI
Helix 11: MAVWLGVALAGFGVVIAGGVWGVQLLV

Query ID: W0F0I7
Helix 1: MLTSAALVLIMTPGLAFFYGGMV
Helix 2: SFICMAIVTMIWVIFGFSLAFGDSIGGII
Helix 3: LAATVPLAVFAFFQLKFAIITPALV
Helix 4: SLILFICLFIVFIYCPLAHATW
Helix 5: LDFAGGTVVHMSAGLAALAGAIYL
Helix 6: ARITYVLIGTGLLWFGWFGF
Helix 7: AASALATTAVASGAAAFCWIIF
Helix 8: GTSIGAVVGLVAITPAAGF
Helix 9: AMVIGIVAAIISNLMVEW
Helix 10: VFPCHGVGGMVGMLLTGVFA
Helix 11: FTTHVLVLIGVVVFVLTMSFILL

Query ID: G8TK79
Helix 1: IFLGKMIGLGLVFLAMIFLPGLL
Helix 2: VWTLVAAFLVFGMQAGFVMLEAGFA
Helix 3: CILDTCLCGILFWAIGYAFMF
Helix 4: ILYSIGVTGFIYPIIGHWAW
Helix 5: FAGSTVVHTIGGVISLAGAMVL
Helix 6: LTVAAVGGFLLWFGWYGF
Helix 7: NTTLAACSGGLAAMMAAFWWGA
Helix 8: LAFSINGFLAGLVAITCPCYW
Helix 9: AILLGAVAGFVVYAGAWLI
Helix 10: VAVHGFCGIWGTISLGFFA
Helix 11: FIGSAIITIGTFVVAFILMWVL

Query ID: G8TK77
Helix 1: IAWVLVSTALVFLMTPGLAFFYG
Helix 2: MIKSVVAAGVVGVLWIAVGFSLSF
Helix 3: LFALFQLMFAIITPGLVVGAVA
Helix 4: SYILFIVLFSLLVYAPVAHWSW
Helix 5: WDFAGGTVVHITAGCAALAGALVL
Helix 6: TPAANVPYVLIGTGLLWFGWFGF
Helix 7: AVNAFGTTNTAAAAAGLAWMFFDVV
Helix 8: VLGFCIGAVVGLVAITPAAGFV
Helix 9: IIIGVVGALISNIAVGI
Helix 10: VFPCHGIGGMVGMLLTGVFA
Helix 11: SFFFTQFKAMAIVVVYSFTVSYAIF

Query ID: A0A1H4KAQ7

Helix 1: TAFIFNTLLFLMGGFLVMWMAAGF
Helix 2: IALYSIAGIMYWVVGYSLMYV
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: LWPFLIFVVVLTGFIYPIA
Helix 5: GSTLVHSVGGWAALAGALLL
Helix 6: MALATLGTFILWLGWFGF
Helix 7: IFANTNLAAAAGVVAALILT
Helix 8: VDITFVLNGALAGLVSITA
Helix 9: SPFMAIVIGAVGGVIVVLTVPLL
Helix 10: IPVHLIAGIWGTLAVPLT
Helix 11: FSVQIVGIVAYGVFTFAVSFVVWMIL

Query ID: I5C044
Helix 1: TAFIFNTLLFLMGGFLVMWMAAGF
Helix 2: IALYSIAGIMYWVVGYSLMYV
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: LWPFLIFVVVLTGFIYPIA
Helix 5: GSTLVHSVGGWAALAGALLL
Helix 6: MALATLGTFILWLGWFGF
Helix 7: IFANTNLAAAAGVVAALILT
Helix 8: VDITFVLNGALAGLVSITA
Helix 9: SPFMAIVIGAVGGVIVVLTVPLL
Helix 10: IPVHLIAGIWGTLAVPLT
Helix 11: FSVQIVGIVAYGVFTFAVSFVVWMIL

Query ID: A0A063Y780
Helix 1: FYFLMCTALVMWMAAGFAMLEAGLVR
Helix 2: VLLYGVACTVYLFVGYNIMY
Helix 3: FIFQAVFAAATMSIVSGAV
Helix 4: WPFLVFAVFMVSVIYPVSGYW
Helix 5: FAGSIVVHAAGASAALAAVILV
Helix 6: LPMATLGMFILWMGWFGF
Helix 7: IFVNTNAAAAAGAVVAALFA
Helix 8: TDITMTINGALAGLVSITA
Helix 9: GAGLAVLIGAVGGIVVVLSVLML
Helix 10: ISVHGTAGIWGIFAVLLS
Helix 11: FMGQLIGTLVIIAWMFAASMIVLVIL

Query ID: A0A063Y394
Helix 1: FYWWCTALMVLIHAGFLSYEIG
Helix 2: VKNILAFALVIPMVYLIGWAIY
Helix 3: GIFWGAFALFAATTGSIFSGAII
Helix 4: AFLILAMLLGGVLWLLAAAWGW
Helix 5: VVHMVAGFFALAVVINLGP
Helix 6: MSVVGLMLIIVGFFGFLGGCIIYN
Helix 7: LSAFSFNTLMGFAGGVVGAYLI
Helix 8: FWMMSGGLVGIISVAPGL
Helix 9: GLAYLIALGVGCLAPMVNQLLL
Helix 10: AVGAFAVHGFAGFAGLLISGIF
Helix 11: IGALVMASLGFIPGYLISYLL

Query ID: I5BYV5
Helix 1: WILVATILVFIMHLGFASLEAGL
Helix 2: LLTYAFIGFNLMYPGDAFAGMFIGLGGIGL
Helix 3: FIFQAMFAATAATIVSGAVA
Helix 4: LGPFLTFSILYVGICYPIV
Helix 5: FAGSTIVHSVGGWGALVGAYLL
Helix 6: IPMATIGVFLLWFGWFGF
Helix 7: LVFVTTAIAGAAGAFGALLASYL
Helix 8: ITMVLNGILAGLVGITAGADL
Helix 9: AAIIGFVGGILVVLGVVFF
Helix 10: IAVHLVGGIWGTLAVGLFG
Helix 11: LIGIGATAAFCFGTSWLIFFSL

Query ID: Q1QS12
Helix 1: MLTATALVLMMTIPGLALFYG
Helix 2: VMQSFAIACLVSVLWMVIGYSWA
Helix 3: SVFMCFQMTFAIITPALICGAIA
Helix 4: AMMWFMGLWSLLVYAPIAHWVWG
Helix 5: FAGGTVVHINAGVAGLVCALVL
Helix 6: APHNLVLTVIGASLLWVGWFGF
Helix 7: AGMAMAVTQIATAAAALAWM
Helix 8: VLGICSGAVAGLVAITPASGF
Helix 9: ALVIGAAAGVGCYWGATGL
Helix 10: AFGVHGVGGIIGALLTGVFA
Helix 11: VIQIYGILATVVYDAIVTLIILLAI

Query ID: A4BMY5
Helix 1: AWMLTATALVLLMTIPGLSLFY
Helix 2: VMMQCFAITCLVSVLWAAYGY
Helix 3: VFVMFQLSFAVITPALIVGAFA
Helix 4: AMLWFVGLWLTLVYVPVAHWVWG
Helix 5: FAGGTVVHVNAGVAGLVTALVL
Helix 6: MPHNMVFTLVGAGMLWVGWFG
Helix 7: IAGRAVLVTQLATAAAALVWM
Helix 8: ALGIASGAVAGLVAITPA
Helix 9: ALGALVIGGSAALACFYAV
Helix 10: ALDCFGVHGVGGIVGALAMGVFAA
Helix 11: KQILGVAVTIIYDGIFTFLIL

Query ID: Q82X47
Helix 1: NYSINILAMLLVGFGFLMVFV
Helix 2: YLVVATGLPLYILLRANGIFGHALT
Helix 3: AVIYAEFAVATGLIAMGAVL
Helix 4: VFQYALLALFIVPVYLL
Helix 5: AGSIAIHAFGAYFGLGVSIAL
Helix 6: MLGSMVLWLFWPSFATAIVPF
Helix 7: TIVNTLLALCGATLATYFLSALF
Helix 8: IVDMANAALAGGVAIGSVC
Helix 9: VGAFVIGLLGGAISVVGFVFI
Helix 10: GLPGLLGGFSAILIVPGIAV
Helix 11: IGITLALALIGGVIAGALI

Query ID: Q5YL87
Helix 1: NYSINILAMLLVGFGFLMVFV
Helix 2: YLVVATGLPLYILLRANGIFGHALT
Helix 3: AVIYAEFAVATGLIAMGAVL
Helix 4: VFQYALLALFIVPVYLL
Helix 5: AGSIAIHAFGAYFGLGVSIAL
Helix 6: MLGSMVLWLFWPSFATAIVPF
Helix 7: TIVNTLLALCGATLATYFLSALF
Helix 8: IVDMANAALAGGVAIGSVC
Helix 9: VGAFVIGLLGGAISVVGFVFI
Helix 10: GLPGLLGGFSAILIVPGIAV
Helix 11: IGITLALALIGGVIAGALI

Query ID: A0A060HN92
Helix 1: LISTGLVMLMTPALGFFEAGLI
Helix 2: TFSGLAILSTLWFVLGFTLVFA
Helix 3: FGGYQMMFAVITPLLITGAFA
Helix 4: SFFVFIIAWSIFIYYPLAHWIWG
Helix 5: FAGGIVIHTSAGMASLAAALIL
Helix 6: VPHNIPLAVIGAALLWIGWFGF
Helix 7: AANTLLVTHIASATSAMVWIFL
Helix 8: AVINGAIAGLAGVTPAAGFI
Helix 9: FILGIVLGFASYYAILLL
Helix 10: VSSVHGVTGIVGSLAIGILA
Helix 11: FAIQALGVGVAGALGFGGTAVIM

Query ID: A0A060HFT5
Helix 1: AWMLTSSALVLMMTPAGLAIFY
Helix 2: TLHMVFITTGVIGIQFVLWGY
Helix 3: FMVFQMMFAIITPALIVASVA
Helix 4: AFIIFIVIWATFVYDFAAHWTW
Helix 5: FAGGTVIHITSGWSGLVIALMLG
Helix 6: PHNISLVVLGAALLWVGWFGF
Helix 7: AGSAFVATQIATGMAAVTWAL
Helix 8: IGAASGAVAGLVAITPAS
Helix 9: MSAIIIGIIASIVCYAAVAF
Helix 10: TWGVHGVGGLAGAILTGIFA
Helix 11: LYENAVGAFAALAWAMGLTAVII

Query ID: A0A060HSP0
query A0A060HSP0 has 12, using last 11 helices
Helix 1: AWMLTSAALVLMMTPAGLAMFYA
Helix 2: LHMTFITTGVIAVQWALWGY
Helix 3: MVFQMMFAIITPALIVASMA
Helix 4: AFIIFIVIWATFVYDFAAHWTW
Helix 5: FAGGTVIHITSGWSGLVIALMLG
Helix 6: PHNISLVVLGAALLWVGWFGF
Helix 7: ATSAFVATQIATGMAAVTWSL
Helix 8: VGAASGAVAGLVAITPAS
Helix 9: MSAIIIGILASIVCYAAVAF
Helix 10: TWGVHGIGGLAGALLTGILA
Helix 11: LYENAAGAFAAVAWAMGLTAAII

Query ID: A0A977NL98
Helix 1: LISTGLVMLMTPALGFFEAGLI
Helix 2: TFSGLAILSTLWFVLGFTLVFA
Helix 3: FGGYQMMFAVITPLLITGAFA
Helix 4: SFFVFIIAWSIFIYYPLAHWIWG
Helix 5: FAGGIVIHTSAGMASLAAALIL
Helix 6: VPHNIPLAVIGAALLWIGWFGF
Helix 7: AANTLLVTHIASATSAMVWIFL
Helix 8: AVINGAIAGLAGVTPAAGFI
Helix 9: FILGIVLGFASYYAILLL
Helix 10: VSSVHGVTGIVGSLAIGILA
Helix 11: FAIQALGVGVAGALGFGGTAVIM

Query ID: A0A977NM15
Helix 1: AWMLTSSALVLMMTPAGLAIFY
Helix 2: TLHMVFITTGVIGIQFVLWGY
Helix 3: FMVFQMMFAIITPALIVASVA
Helix 4: AFIIFIVIWATFVYDFAAHWTW
Helix 5: FAGGTVIHITSGWSGLVIALMLG
Helix 6: PHNISLVVLGAALLWVGWFGF
Helix 7: AGSAFVATQIATGMAAVTWAL
Helix 8: IGAASGAVAGLVAITPAS
Helix 9: MSAIIIGIIASIVCYAAVAF
Helix 10: TWGVHGVGGLAGAILTGIFA
Helix 11: LYENAVGAFAALAWAMGLTAVII

Query ID: A0A977NL43
query A0A977NL43 has 12, using last 11 helices
Helix 1: AWMLTSAALVLMMTPAGLAMFYA
Helix 2: LHMTFITTGVIAVQWALWGY
Helix 3: MVFQMMFAIITPALIVASMA
Helix 4: AFIIFIVIWATFVYDFAAHWTW
Helix 5: FAGGTVIHITSGWSGLVIALMLG
Helix 6: PHNISLVVLGAALLWVGWFGF
Helix 7: ATSAFVATQIATGMAAVTWSL
Helix 8: VGAASGAVAGLVAITPAS
Helix 9: MSAIIIGILASIVCYAAVAF
Helix 10: TWGVHGIGGLAGALLTGILA
Helix 11: LYENAAGAFAAVAWAMGLTAAII

Query ID: A0A1I7FBM5
Helix 1: YVIHILAMLLVGFGFLMVFV
Helix 2: YLVVAVGLPLYILLRANGVF
Helix 3: LLFAEFAVASGLIAMGAVL
Helix 4: VFQYALLALLLIPAYLL
Helix 5: AGSIIIHAFGAYFGLGLSLA
Helix 6: FAMLGSMVLWLFWPSFATAIVPF
Helix 7: TVVNTVLALCGATITTYFL
Helix 8: VDMANAALAGGVAIGSTCNIVS
Helix 9: GIGLLAGAVSVIGFVFIQPAL
Helix 10: VHNLHGMPGLLGAFVAILVV
Helix 11: AQFIGIAFSVVLALIAGLVAGALI

Query ID: A0A1H8D0R8
Helix 1: YVIHILAMLLVGFGFLMVFV
Helix 2: YLVVAVGLPLYILLRANGVF
Helix 3: LLFAEFAVASGLIAMGAVL
Helix 4: VFQYALLALLLIPAYLL
Helix 5: AGSLIIHAFGAYFGLGLSLA
Helix 6: FAMLGSMVLWLFWPSFATAIVPF
Helix 7: TVVNTVLALCGATITTYFL
Helix 8: VDMANAALAGGVAIGSTCNI
Helix 9: AFAIGLLAGAVSVIGFVFI
Helix 10: GMPGLLGALVAVLVVPGIAV
Helix 11: IAFSVVLALIAGLVAGALI

Query ID: A0A1I0AQM4
Helix 1: YVIHILAMLLVGFGFLMVFV
Helix 2: YLVVAVGLPLYILLRANGVF
Helix 3: LLFAEFAVASGLIAMGAVL
Helix 4: VFQYALLALLLIPAYLL
Helix 5: AGSIIIHAFGAYFGLGLSLA
Helix 6: FAMLGSMVLWLFWPSFATAIVPF
Helix 7: TVVNTVLALCGATITTYFL
Helix 8: VDMANAALAGGVAIGSTCNIVS
Helix 9: AIGLLAGAVSVIGFVFIQPAL
Helix 10: VHNLHGMPGLLGAFVAILVVPGI
Helix 11: IGIAFSVVLALIAGLVAGALI

Query ID: A0A2T5IHP0
Helix 1: YVIHILAMLLVGFGFLMVFV
Helix 2: YLVVAVGLPLYMLLRANGVF
Helix 3: LLFAEFAVASGLIAMGAVL
Helix 4: VFQYALLALFLIPAYLL
Helix 5: AGSIIIHAFGAYFGLGLSLA
Helix 6: FAMLGSMVLWLFWPSFATAIVPF
Helix 7: TVVNTVLALCGATITTYFL
Helix 8: VDMANAALAGGVAIGSTCNIVS
Helix 9: GIGLLAGAVSVIGFVFIQPAL
Helix 10: VHNLHGMPGLLGAFVAILVV
Helix 11: AQFIGIAFSVVLALITGLAAGALI

Query ID: Q2YBP7
Helix 1: YVIHILAMLLVGFGFLMVFV
Helix 2: YLVVAVGLPLYILLRANGVF
Helix 3: LLFAEFAVASGLIAMGAVL
Helix 4: VFQYALLALLLIPAYLL
Helix 5: AGSIIIHAFGAYFGLGLSLA
Helix 6: FAMLGSMVLWLFWPSFATAIVPF
Helix 7: TVVNTVLALCGATITTYFL
Helix 8: VDMANAALAGGVAIGSTCNIVS
Helix 9: AIGLLAGAVSVIGFVFIQPAL
Helix 10: VHNLHGMPGLLGAFVAVLVVPGI
Helix 11: IGIAFSVVFALIAGLAAGALI

Query ID: D8PD01
Helix 1: LVSSAFVLAMLMPGLALFYGGLV
Helix 2: SVMILSVVSLLWILFGYSLA
Helix 3: AFMLFQLMFAAIAPALITGAFA
Helix 4: AVVLFAALWSVFVYVPLAHWIWG
Helix 5: FAGGAVIHISSGAAALVCAIVL
Helix 6: APHNLPMTLLGTGFLWFGWFGF
Helix 7: LGANGIAVSAIIATHAAAAMGAIAWC
Helix 8: VLGVASGAVAGLATVTPAA
Helix 9: MSAIAIGLVAGMTCYAAIVW
Helix 10: VVGIHGVGGVIGILATGLFA
Helix 11: FGIQLLVVAVTTIFSIIGTFVIL

Query ID: A0A6G9XJV9
Helix 1: WLLVSTALVLLMTPALALFYG
Helix 2: LMMNFIAIPLVTVAWLLFGYSMV
Helix 3: LLFATFQLTFAILTAALVSGAI
Helix 4: AAWMVFVPVWALAVYAPIAHWVW
Helix 5: LDYAGGLVVEIASGASALALALVLG
Helix 6: PHNLPFVLLGAGLLWFGWFGF
Helix 7: LSANGIAAAVFLNTLVAGCLGMLGWL
Helix 8: TFGAASGVVAGLVAITPS
Helix 9: TLGALLVGLAAGVLCSFAVGW
Helix 10: VVGVHFVGGVVGTVLIGLLATQVM
Helix 11: LVGVLAVAAYAFLVSFALGKLI

Query ID: A0A6G9Y3Q0
Helix 1: ALVLLMTPGLAFFYGGM
Helix 2: LNMIMMSISAMGLVGVLWSLY
Helix 3: VFVGFQLMFAIITVALISGAVA
Helix 4: AWLLFAGIWVTVVYFPVAHWVF
Helix 5: FAGGTAVHINAGAAALALVLVLG
Helix 6: PHNLPFVMLGAGLLWFGWFGF
Helix 7: AGTTFVTTAVATAAAMLAWLLV
Helix 8: HATSLGAASGIVAGLVAIT
Helix 9: VNVLGALAVGAVAGALCALAVGL
Helix 10: VVGVHLVGGIVGTLMVGFVAA
Helix 11: WRQTVGAAVVLAFSFVASLIIAYIV

Query ID: A0A379A6M6

Helix 1: WLLVSTALVLLMTPALALFYG
Helix 2: LMMNFIAIPLVTVAWLLLGYSMA
Helix 3: LLFATFQLTFAILTAALVSGAI
Helix 4: AAWMVFVPVWALAVYAPIAHWVW
Helix 5: LDYAGGLVVEIASGASALALALVLG
Helix 6: PHNLPFVLLGAGLLWFGWFGF
Helix 7: LSANGIAAAVFLNTLVAGCLGMLGWL
Helix 8: TFGAASGVVAGLVAITPS
Helix 9: TLGALLVGLAAGVVCSFAVGW
Helix 10: VVGVHFVGGIVGTVLIGLLATQVM
Helix 11: LVGVLVVAAYAFLVTFALGKLI

Query ID: A0A379BXA9
Helix 1: AWMLASSALVLLMTPGLAFFYGG
Helix 2: VLNMIMMSVSAMGLVGVLWSLY
Helix 3: VFVAFQLMFAIITVALISGAVA
Helix 4: AWLLFAGIWVTVVYFPVAHWVF
Helix 5: FAGGTAVHINAGAAALALVLVLG
Helix 6: PHNLPFVMLGAGLLWFGWFGF
Helix 7: AGTTFVTTAVATAAAMLAWLLV
Helix 8: HATSLGAASGIVAGLVAIT
Helix 9: VNVLGALAVGVVAGALCALAVGL
Helix 10: VVGVHLVGGIVGTLMVGFVAA
Helix 11: WRQAVGAGVVLAFSFVASLIIAYIV

Query ID: A0A7K2IV20
Helix 1: NTAWLLMSAALVMLMTPGLAFFY
Helix 2: MMLMSFSSIALVSVLWVLV
Helix 3: AGFQLMFAVITVALISGAIA
Helix 4: AWLLFVPVWALAVYFPVAHWVW
Helix 5: FAGGTAVHINAGAAALALVIVLG
Helix 6: PHNMPFVLLGVALLWFGWFGF
Helix 7: AALALVNTQVATAAAMVAWMLV
Helix 8: RISALGLASGAISGLVAITPAA
Helix 9: VGAIVVGALAGSLCAYAIGW
Helix 10: VVGIHLVGGIVGCLALGLVA
Helix 11: LLAAQAVSIVGVLLYSFAVTWLIA

Query ID: J7L3W8
Helix 1: NTAWLLMSAALVMLMTPGLAFFY
Helix 2: MMLMSFSSIALISVLWVLV
Helix 3: AGFQLMFAVITVALISGAIA
Helix 4: AWLLFVPVWALAVYFPVAHWVW
Helix 5: FAGGTAVHINAGAAALALVIVLG
Helix 6: PHNMPFVLLGVALLWFGWFGF
Helix 7: AALALVNTQVATAAAMVAWMLV
Helix 8: RISALGLASGAISGLVAVTPAA
Helix 9: VGAIVVGALAGSLCAYAIGW
Helix 10: VVGIHLVGGVVGCLALGLVA
Helix 11: LLAAQAVSIVGVLLYSFAVTWLIA

Query ID: A0ZJU7
Helix 1: LDTLWVAIAAFLVFFMNAGF
Helix 2: LIVFALASVTFWAIGFGFMF
Helix 3: FLFQLAFAGTAATIVSGAVAE
Helix 4: FLIFSVLLVGIAYAITGHWIWG
Helix 5: FAGSTVVHSVGGWAALMGAAFL
Helix 6: IVAIPGHNMSIATLGCLILWLGWFGF
Helix 7: AIAHIALTTNMAAAAGGIAATGTAWIYL
Helix 8: MIINGVLAGLVGITASCAYVS
Helix 9: IIGFIAGIIVVFSVTLFD
Helix 10: SVHLVCGIWGTLAVGLWSVGPGVYSWY
Helix 11: LIQLVGVLSVGGMTVVFSSIFWLFL

Query ID: A0A166IS52
Helix 1: LDTLWVAIAAFLVFFMNAGF
Helix 2: LIVFALASITFWAIGFGFMF
Helix 3: FLFQLAFAGTAATIVSGAVAE
Helix 4: FLIFSVLLVGIAYAITGHWIWG
Helix 5: FAGSTVVHSVGGWAALMGAAFL
Helix 6: IVAIPGHNMSIATLGCLILWLGWFGF
Helix 7: AIAHIALTTNMAAAAGGIAATGTAWIYL
Helix 8: MIINGVLAGLVAITAPCAFVG
Helix 9: IIGFIAGVIVVFSVTLFD
Helix 10: SVHLVCGIWGTLAVGLWSVGPGIYSWY
Helix 11: IIQLVGVLSVGGMTVFFSSIFWLFL

Query ID: A0A2S0Q8P1
Helix 1: LDTLWVAIAAFLVFFMNAGF
Helix 2: LIVFALASVTFWAIGFGFMF
Helix 3: FLFQLAFAGTAATIVSGAVAE
Helix 4: FLIFSVLLVGIAYAITGHWIWG
Helix 5: FAGSTVVHSVGGWAALMGAAFL
Helix 6: IVAIPGHNMSIATLGCLILWLGWFGF
Helix 7: AIAHIALTTNMAAAAGGIAATGTAWIYL
Helix 8: MIINGVLAGLVGITASCAYVS
Helix 9: IIGFIAGIIVVFSVTLFD
Helix 10: SVHLVCGIWGTLAVGLWSVGPGVYSWY
Helix 11: LIQLVGVLSVGGMTVVFSSIFWLFL

Query ID: A0A7X0DNL6
Helix 1: TAWMLVSTAFVLMMTIPGLALFYGG
Helix 2: VLAIMAQSFAICCFVSVLWMVV
Helix 3: ALFLAFQMTFAVITPALITGAFA
Helix 4: AMLVFSLVWVLVVYVPVAHWVWG
Helix 5: FAGGTVVHINAGVAGLVAAIVL
Helix 6: APHNLTLSVVGAALLWVGWFGF
Helix 7: LTAGGLAAMALLVTHIAASAAAVSW
Helix 8: SVLGIISGAVGGLVAITPAAGF
Helix 9: ALIIGLLAGVACFWGAVWL
Helix 10: AFGVHGIGGLVGAVLTGVFAAS
Helix 11: IYGVVATVVWCAVATFIILKVL

Query ID: A0A7W9ZEG0
Helix 1: DVFFLLIGAAMVLAMHAGFAFL
Helix 2: LGVSTVVYFAVGYTIAYGTTFFV
Helix 3: LVKFFFLLMFAAAIPAIISG
Helix 4: LMATAIIVGLIYPLMEGMVWG
Helix 5: FAGSVVVHAFGGWLALGAVILL
Helix 6: IPFLALGSWILCVGWFGF
Helix 7: SGLVAMNSLLAMVGGLLAAVVA
Helix 8: FIHNGALAGLVAVCAGS
Helix 9: LGALVTGGLAGGLFVWGF
Helix 10: VLGVWPLHGLCGTLGGLAAGVFG
Helix 11: LTAQILGTAGGVAFAAVSGFVVYGLL

Query ID: A0A420WC79
Helix 1: FNTFSFLICGALVMWMAAGFAML
Helix 2: AICLKNITLYSVAGIMYYLI
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: FWPFIIFTTVLTGILYPI
Helix 5: AGSTIVHSVGGWAALTGAIIL
Helix 6: LPLATLGTFVLWLGWFGF
Helix 7: VFSNTNLAACGGVVAACLLTQILY
Helix 8: MALNGAIGGLVSITAGP
Helix 9: FLSIIIGAIGGILVVVTVPLL
Helix 10: IPAHLVCGIWGTLAVGIFGGG
Helix 11: VIGIVGIGVFMVVTSAILWLVL

Query ID: K2JVF8
Helix 1: FNTFSFLICGALVMWMAAGFAML
Helix 2: AICLKNITLYAIAGIMYYLI
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: FWPFIIFTTVLTGILYPI
Helix 5: AGSTIVHSVGGWAALTGAIIL
Helix 6: LPLATLGTFVLWLGWFGF
Helix 7: VFSNTNLAACGGVVAACLLTQILY
Helix 8: MALNGAIGGLVSITAGP
Helix 9: FLSIIIGAIGGILVVVTVPLL
Helix 10: IPAHLVCGIWGTLAVGIFGGG
Helix 11: VIGIVGIGVFMVVTSAILWLVL

Query ID: A3TVQ9
Helix 1: YIMTTLLFCMAGFLVFFMAAGF
Helix 2: IALYSVAAIMYWFIGFNLMY
Helix 3: FFFQLVFVAATASIVSGALA
Helix 4: LWPFLVFVVLLTGVMYPI
Helix 5: AGSTVVHSVGGWAALAGAIVL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNMAAAAGAVTALIL
Helix 8: MVLNGALAGLVSITAEPLA
Helix 9: ALWIGAIGGVIVVLTVPMLD
Helix 10: VVGAIPVHLFAGIWGTIAVVFY
Helix 11: LVTQITGIIAYGVFTFIASFVVWFIL

Query ID: A0A7C4VLK5
Helix 1: AWMLVSTALVLLMTPALAFFYGGL
Helix 2: MSFGALGFVTLVWALLGYSIA
Helix 3: VAFQGTFAVITAALISGSLV
Helix 4: AWLLFISLWTVFDYAVLAHWVW
Helix 5: TVVHINAAIAGVVGVAVL
Helix 6: LPHNIPFVLLGAGLLWFGWFGF
Helix 7: AGLAFTNTFLAPAATMAVWML
Helix 8: VGAATAAVVGLVAVTPAAGF
Helix 9: AIWLGAIAALPSFFFILV
Helix 10: VFGAHGIGGITGALLTGVFAAEAW
Helix 11: AVLAAVAMSAVVSLVLYKLVGLVL

Query ID: E4U5Z1
Helix 1: AWMLVSTALVLLMTPALAFFYGGL
Helix 2: MSFGALGFVTLVWALFGYSIA
Helix 3: VAFQGTFAVITAALISGSLV
Helix 4: AWLLFIALWTVFDYAVLAHWVW
Helix 5: TVVHINAAIAGVVGVAVLGA
Helix 6: HNIPFVLLGAGLLWFGWFGF
Helix 7: AALAFTNTFLAPAATMSVWML
Helix 8: VGAATAAVVGLVAVTPAAGF
Helix 9: AIWLGALAAFPSFFFILA
Helix 10: VFGAHGIGGITGAVLTGVFA
Helix 11: VQIVAVVAAVLLSAAASFVIFKLVGLVL

Query ID: Q8ERT9
Helix 1: LSVNLIWVMLGAFLVFFMHAGF
Helix 2: FLTISVASILFFLVGYGIMFGSS
Helix 3: FFVFQAMFVATCATIISGAVA
Helix 4: SYILIVAAMTTIIYPVVGHWVW
Helix 5: VHLTGAVGAFVVVLILGPRIG
Helix 6: GHNLPLGALGVFILWLGWFGF
Helix 7: LVPYVIGTTLLSTSAALVSSSLY
Helix 8: LSMNGVLGGLVGITAGAA
Helix 9: GSIIVGLISGVVLVEGIRFL
Helix 10: AIAVHGICGIWGTLAIGLFSVN
Helix 11: LGIQAIGVLAVVAWVAITAGGFTYVI

Query ID: M9RKT6
Helix 1: IGPYIMTTLLFLVAGFLVFFMAAGF
Helix 2: VALFSVAAIMYWMIGFNLMY
Helix 3: FFFQLVFVAATASIVSGALA
Helix 4: LWPFLGFVVVLTGVLYPI
Helix 5: AGSTIVHSVGGWAALAGAIVL
Helix 6: LALATLGMFILWLGWFGF
Helix 7: IFVNTNMAAAAGSLAALVMT
Helix 8: VDLTMVLNGALAGLVSITA
Helix 9: SLLGSLLIGGVGGVIVVFAVPLL
Helix 10: IPVHLFAGIWGTIAVVFSGSATLS
Helix 11: IAAYGVFTFVASFILWYVL

Query ID: M9RJS5
Helix 1: TAWIIVATALVLFMTLPGLALFY
Helix 2: VFMQCFGIACLMSILWLAFGYSIA
Helix 3: VLFFAFQMTFAIITPALIVGAYV
Helix 4: FVMTFSGLWMLLCYAPVAHWVW
Helix 5: FAGGIVVHQTAGLAALIVAFFL
Helix 6: NPGMVMIGAAMLWVGWFGF
Helix 7: AAMAITVTHISAAAASLTWA
Helix 8: LVGLVTGTIAGLASITPAS
Helix 9: IEALLIGAIAGIMCQELCHVV
Helix 10: VFAVHGVGGMFGIIMLAVFGHA
Helix 11: LGGLAVVGLWTVIVTTAIVLVV

Query ID: A0A375YPN6
Helix 1: FYWMSIALMMLIHAGFLAYEV
Helix 2: AMKNLLAFATIVASFFFVGWFLY
Helix 3: GIFWGAFALFAATTGSIMSGAVL
Helix 4: GFLVLTVLVGSVTWIIGAAWGW
Helix 5: VGAAGCVHMIAGFAALGILINL
Helix 6: LPLTMLGLFLIFTGFFGFLMGCVIYGA
Helix 7: TLSAFAFNTLMALAGGIIGAYL
Helix 8: FWTISGGLAGVIGCASGL
Helix 9: ALTFILGLGAGALIPYIG
Helix 10: VGAFSVHGGIGLYSVLMAGVFLSGY
Helix 11: WGQAVGALVFAALGFFPTYFLSLLL

Query ID: A0A483BDN6
Helix 1: VVNTMMSVFVMCGLAVVLWVI
Helix 2: FVGDFGGVFGSLSALLLHGV
Helix 3: TSLYLIFQMMFAVITPALFVGAVV
Helix 4: FLLLFTVFWSIFIYYPLVHMVWA
Helix 5: FAGGTVVHIDAGVTALVLAYFLG
Helix 6: GHYSLPWALLGTTILWIGWYG
Helix 7: IAVQAVLTTTVATACSMITWMLI
Helix 8: GICNGTLCGLVGITPATGYV
Helix 9: FWIGILAAVASYFFVNFL
Helix 10: AFGCHGVCGIVGSILTGLFAS
Helix 11: LFAVQLFATLFSVIFTALICFVII

Query ID: D3LBI0
Helix 1: VVNTMMSVFVMCGLAVVLWVI
Helix 2: FVGDFGGVFGSLSALLLHGV
Helix 3: TSLYLIFQMMFAVITPALFVGAVV
Helix 4: FLLLFTVFWSIFIYYPLVHMVWA
Helix 5: FAGGTVVHIDAGVTALVLAYFLG
Helix 6: GHYSLPWALLGTTILWIGWYG
Helix 7: IAVQAVLTTTVATACSMITWMLI
Helix 8: GICNGTLCGLVGITPATGYV
Helix 9: FWIGILAAVASYFFVNFL
Helix 10: AFGCHGVCGIVGSILTGLFAS
Helix 11: LFAVQLFATLFSVIFTALICFLII

Query ID: A0NJ07
Helix 1: VVNTMMSVFVMCGLAVVLWVI
Helix 2: FVGDFGGVFGSLSALLLHGV
Helix 3: TSLYLIFQMMFAVITPALFVGAVV
Helix 4: FLLLFTVFWSIFIYYPLVHMVWA
Helix 5: FAGGTVVHIDAGVTALVLAYFLG
Helix 6: GHYSLPWALLGTTILWIGWYG
Helix 7: IAVQAVLTTTVATACSMITWMLI
Helix 8: GICNGTLCGLVGITPATGYV
Helix 9: FWIGILAAVASYFFVNFL
Helix 10: AFGCHGVCGIVGSILTGLFAS
Helix 11: LFAVQLFATLFSVIFTALICFVII

Query ID: Q04DE4
Helix 1: VVNTMMSVFVMCGLAVVLWVI
Helix 2: FVGDFGGVFGSLSALLLHGV
Helix 3: TSLYLIFQMMFAVITPALFVGAVV
Helix 4: FLLLFTVFWSIFIYYPLVHMVWA
Helix 5: FAGGTVVHIDAGVTALVLAYFLG
Helix 6: GHYSLPWALLGTTILWIGWYG
Helix 7: IAVQAVLTTTVATACSMITWMLI
Helix 8: GICNGTLCGLVGITPATGYV
Helix 9: FWIGILAAVASYFFVNFL
Helix 10: AFGCHGVCGIVGSILTGLFAS
Helix 11: LFAVQLFATLFSVIFTALICFLII

Query ID: E4XXT2
Helix 1: DFFLVMNACMVLFMQSGFALL
Helix 2: VVVGAIVYWACGFAFAYGKV
Helix 3: FYGEFFFNFVFAATATTIISGAV
Helix 4: LSYLVYGVVATGFIQPVAVHWGW
Helix 5: YAGGGNVHAVGGIAALVGCVFMG
Helix 6: LTCMGAFILIIGFLAMVLG
Helix 7: LTIGGSMSGITCMCIVFIAPKL
Helix 8: QYWSFLVLVDATLAGMVAMCAG
Helix 9: PFGAAIIGIVAGFGFAVTEHWL
Helix 10: IPVHLTGGVIGVLMAPLFA
Helix 11: LLWQMIGIVAILMWTLVLSSFIFWICW

Query ID: E4YA63

Helix 1: LVMNACMVLFMQSGFALIEAGAV
Helix 2: NLLDACVGALVYWACGFAFAF
Helix 3: FFFNFVFAATATTIISGALA
Helix 4: AYLVYGIIASGFIQPVTVHWAW
Helix 5: YAGGGNVHAVGGIAALVSCIFIG
Helix 6: TPLTCLGAFILFIGFLSMVLG
Helix 7: LTLGGAASGLTSMMIVNLEPKVV
Helix 8: FWSFLVLVDATLAGMVSMCAG
Helix 9: PWGAVIIGIIVGFAFYYV
Helix 10: PVGSVAVHLVGGVIGVLLAPVFA
Helix 11: FAWQLVGILAILSWTIVCCIPLFFLLW

Query ID: B1ZSW9
Helix 1: AWQMTSTALVLFMTLPGLALFY
Helix 2: VLAQCLGIAGLVTILWWAV
Helix 3: MFQLTFAIITPALILGAIA
Helix 4: AVLVFVTIWMFLVYFPFAHMVWS
Helix 5: FAGGTVVHMTSGWSALVLCLILG
Helix 6: PHSMVLCMVGTGMLWVGWYG
Helix 7: IASNAFATTTLAAATAGFVWA
Helix 8: VLGFCSGIVAGLVVITPGAGFV
Helix 9: VIIGIAAGIIPFLAVAYL
Helix 10: TFGVHGVGGTLGAILTGVFA
Helix 11: LKAVLLTIVWSVVATAVIAFLV

Query ID: A0A4R8H081
Helix 1: IAIDTIWTLLAAFLVFFMQAGFAMV
Helix 2: FSVGSLIYWICGFAFMFGAGNAFI
Helix 3: LSAFWIFQAVFAATAATIVS
Helix 4: YLAYSAVITAIIYPVVGHWIW
Helix 5: AGSTVVHSVGGWAALAGAMVL
Helix 6: LLMAALGVFILWFGWFGF
Helix 7: SIADIAVTTNLAAAAGAALAMITSWI
Helix 8: VSMTLNGALAGLVGITAGT
Helix 9: FGAVAIGALAGVLIVYAV
Helix 10: VGAVAVHGVCGAFGTLMVGLFA
Helix 11: GVVAVAIWTFTTAFVLFKVIA

Query ID: A0A4R8GSH7
Helix 1: VLFLLLGAIMIFAMHAGFAFL
Helix 2: WAVSTVVYFLVGFPIAYGIS
Helix 3: FFFLLTFAACIPAIISGGIA
Helix 4: VIAGAIFAGVLYPFFESLIWGQ
Helix 5: YAGSVVVHSFGGWLALPAILILG
Helix 6: FLALGSWILAVGWFGFNVMSA
Helix 7: ISGLVAINSLFAMVGGIITALII
Helix 8: FIHNGALAGLVAVCAGSN
Helix 9: AAFIVGGIASIIFVKGFT
Helix 10: LGVFVLHGLVGSWGGIASGIFTHKIF
Helix 11: LVGTISAAIIALTGGFIVYYVI

Query ID: Q84KJ7
Helix 1: ASTLVGIQSMPGLVVLYGSIV
Helix 2: SAFMALYAYASSLLVWVLVGF
Helix 3: LVLFQFEFAAITLVLLAGSVL
Helix 4: LWLLLSYTVGAFSLWGGGFLY
Helix 5: GGYVIHLSSGIAGFTAAYWVG
Helix 6: ILLMIAGGGLLWMGWAGFNGG
Helix 7: IAASVAVLNTNVCAATSLLMW
Helix 8: VIGAVQGMMTGLVCITPGAGL
Helix 9: WAAVVMGIFAGSVPWFTMMIL
Helix 10: LAVFHTHAVAGLLGGILTGLL
Helix 11: FVIAWNLVVTTAILLGIGLFI

Query ID: Q7XQ12
Helix 1: LLFSAYLVFAMQLGFAMLCAG
Helix 2: VLDAAAGALFYYLFGFAFAFG
Helix 3: FFLFQWAFAIAAAGITSGSIA
Helix 4: YLIYSAFLTGFVYPVVSHWIW
Helix 5: FAGSGVVHMVGGVAGLWGALI
Helix 6: LVVLGTFLLWFGWYGFNPGSF
Helix 7: SGVGRTAVTTTLAGSVAALTTLF
Helix 8: VVDVCNGLLGGFAAITAGCSV
Helix 9: WAAIICGFVSAWVLIGLNALA
Helix 10: LEAAQLHGGCGAWGILFTALF
Helix 11: VIQILVIFGWVSCTMGPLFYG

Query ID: Q6K9G3
Helix 1: LLFSAYLVFAMQLGFAMLCAG
Helix 2: VLDAAAGALFYYLFGFAFAFG
Helix 3: FFLFQWAFAIAAAGITSGSIA
Helix 4: YLIYSAFLTGFVYPVVSHWFW
Helix 5: FAGSGVVHLVGGIAGLWGAFI
Helix 6: LVVLGTFLLWFGWFGFNPGSF
Helix 7: AVGRTAVTTSLAGSVAALTTLYG
Helix 8: WNVTDVCNGLLGGFAAITAGC
Helix 9: VVDPWASVICGFVSAWVLIGC
Helix 10: LEATQLHAGCGAWGIIFTALF
Helix 11: IVQILVIVGWVSATMGTLFYV

Query ID: Q94JG1
query Q94JG1 has 12, using last 11 helices
Helix 1: LGLTATDIGNAGIASVSGAVF
Helix 2: LASASLILLTTPAVYCSSIIQ
Helix 3: FFTGISLASFVSAQFWMSSMF
Helix 4: GVAGGWGNLGGGAVQLLMPLV
Helix 5: IAFFIPGLMQTFSAIAVLAFG
Helix 6: WILALTYGYSFGVELTIDNVV
Helix 7: TAGLIAASFGMANIISRPGGG
Helix 8: LWGLWTVQTIGGVLCVVLGI
Helix 9: VLFSFFVQAACGLTFGIVPFV
Helix 10: ISGMTGGGGNVGAVLTQYIFF
Helix 11: GIKYMGLMIIACTLPVMLIYF

Query ID: Q6K9G1
Helix 1: LLFSAYLVFAMQLGFAMLCAG
Helix 2: VLDAAAGALFYYLFGFAFAFG
Helix 3: FFLFQWAFAIAAAGITSGSIA
Helix 4: YLIYSAFLTGFVYPVVSHWIW
Helix 5: FAGSGVVHMVGGVAGLWGALI
Helix 6: LVVLGSFLLWFGWYGFNPGSF
Helix 7: SAVGRTAVTTTLAGSTAALTTLF
Helix 8: VIDVCNGLLGGFAAITAGCSV
Helix 9: WAAIICGFVSAWVLIGLNALA
Helix 10: LEAAQLHGGCGAWGVIFTALF
Helix 11: IVVILVIAAWVSFTMAPLFLV

Query ID: P0DKG9
query P0DKG9 has 12, using last 11 helices
Helix 1: IGNAGVASVSGSIFSRLAMGAI
Helix 2: AFLIMLAAPTVFCMSLIDSAA
Helix 3: FLIGFSLATFVSCQYWMSTMF
Helix 4: GLAAGWGNMGGGATQLIMPLV
Helix 5: LAYFVPGTLHVVMGVLVLTLG
Helix 6: WIFVLLYGYSMGVELTTDNVI
Helix 7: GIIAASFGMANIVARPTGGLL
Helix 8: ARLWNIWILQTAGGAFCLLLG
Helix 9: VLFSFCAQAACGAIFGVIPFV
Helix 10: IISGMTGAGGNFGAGLTQLLF
Helix 11: GLEYMGIMIMACTLPVVLVHF

Query ID: P0DKH0
query P0DKH0 has 12, using last 11 helices
Helix 1: IGNAGVASVSGSIFSRLAMGAI
Helix 2: AFLIMLAAPTVFCMSLIDSAA
Helix 3: FLIGFSLATFVSCQYWMSTMF
Helix 4: GLAAGWGNMGGGATQLIMPLV
Helix 5: LAYFVPGTLHVVMGVLVLTLG
Helix 6: WIFVLLYGYSMGVELTTDNVI
Helix 7: GIIAASFGMANIVARPTGGLL
Helix 8: ARLWNIWILQTAGGAFCLLLG
Helix 9: VLFSFCAQAACGAIFGVIPFV
Helix 10: IISGMTGAGGNFGAGLTQLLF
Helix 11: GLEYMGIMIMACTLPVVLVHF

Query ID: Q84KJ6
Helix 1: ISATLVGMQSVPGLVILYGSI
Helix 2: WAVNSAFMALYAFAAVWLCWV
Helix 3: MVYFQCVFAAITLILLAGSLL
Helix 4: WMLFVPLWLTFSYTVGAFSLW
Helix 5: GGYVIHLSSGVAGFTAAYWVG
Helix 6: VLLMLTGAGILWMGWAGFNGG
Helix 7: NTNICAATSLLVWTCLDVIFF
Helix 8: VIGAVQGMITGLVCITPGAGL
Helix 9: WAAIVMGILSGSIPWFTMMVV
Helix 10: GFLGGATTGLFAEPVLCSLFL
Helix 11: VAGALFIICWNVVVTSLVCLA

Query ID: Q69T29
Helix 1: SATLVGLQSMPGLVILYGSIV
Helix 2: SAFMALYAFAAVWICWVVWAY
Helix 3: MVYFQCMFASITIIILAGSLL
Helix 4: LWITFSYTVCAFSLWGGGFLF
Helix 5: GGYVIHLSSGIAGLTAAYWVG
Helix 6: ILLVLAGAGLLWLGWTGFNGG
Helix 7: AVLNTHICASTSLLVWTILDVFF
Helix 8: SVIGAVQGMITGLVCITPGAGLV
Helix 9: AAIVMGILSGSIPWYTMMVL
Helix 10: GFLGGATTGLFAEPILCSLFL
Helix 11: LFVTAWNIVITSIICVIISLI

Query ID: Q8S233
Helix 1: AATFVGLQSMPGLVVLYGSIV
Helix 2: SAFMALYAYASTLIVWVLVGF
Helix 3: MVLFQFELAAITLVLLAGSLL
Helix 4: LWLLFSYTVCAFSLWGGGFLY
Helix 5: GGYVIHLSSGIAGFTAAYWVG
Helix 6: ILLMIAGGGLLWLGWAGFNGG
Helix 7: TNVSAAASLLTWTCLDVIFFG
Helix 8: VIGAVQGMMTGLVCITPGAGL
Helix 9: WAAILMGICGGSLPWFSMMIL
Helix 10: LAVFHTHAVAGLLGGFLTGLF
Helix 11: FVVVWNVVATTVILLGVGLVV

Query ID: Q851M9
Helix 1: VAATVVGLQSVPGLVVLYGGV
Helix 2: WAVNSAFMALYAFAAVWICWV
Helix 3: VVYFQCVFAAITLILVAGSLL
Helix 4: FLAWMIFVPLWLTFSYTVGAF
Helix 5: GGYVIHVSAGIAGFTAAYWVG
Helix 6: ILFTLTGAGLLWMGWAGFNGG
Helix 7: NTNICTAMSLIVWTCLDVIFF
Helix 8: VVGAVQGMITGLVCITPAAGV
Helix 9: WAALVMGVLAGSIPWYTMMIL
Helix 10: LGVFHTHGVAGLLGGLLTGLF
Helix 11: IAGGLFVVAWNVAVTSLICLA

Query ID: Q8S230
Helix 1: VAATFVGIQSMPGLVVIYGSI
Helix 2: SAFMALYAYASTLIVWVLVGF
Helix 3: LVLFEFEFAAITLVLLAGSLL
Helix 4: LWLLFSYTVGAFSLWGGGFLY
Helix 5: GGYVIHLSSGVAGFTAAYWVG
Helix 6: ILLMIAGGGLLWLGWAGFNGG
Helix 7: TNVSAATSLLTWTCLDVIFFG
Helix 8: VIGAVQGMMTGLVCITPGAGL
Helix 9: WSAMLMGMFAGSVPWFTMMIL
Helix 10: LAVFHTHAVAGILGGVLTGLL
Helix 11: FVTVWNLIVTSAILLCIGLFI

Query ID: A0A158URW8
Helix 1: AWQMISATLVGMQSVPGLVILYG
Helix 2: AFMALYAFAAVWLCWVTWGY
Helix 3: VYFQCVFAAITLILLAGSLL
Helix 4: AWMLFVPLWLTFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGVAGFTAAYWVG
Helix 6: PNNVLLMLTGAGILWMGWAGF
Helix 7: SSLAVLNTNICAATSLLVWTCLDVI
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIVMGILSGSIPWFTMMVV
Helix 10: AVAGFLGGATTGLFAEPVLCSLFLPV
Helix 11: QVAGALFIICWNVVVTSLVCLAV

Query ID: E1IF27
Helix 1: ALSTIMHSFFMLGFVSVIWAL
Helix 2: LAFSPTIGGFIGGLSWVGL
Helix 3: FMVFQMMFAVITPALISGAFA
Helix 4: AFVIFSLFWLLLVYVPVAHWVW
Helix 5: LDFAGGTVVHITSGVSALVCALVLG
Helix 6: PHNATLSILGTGMLWFGWFGF
Helix 7: LGSGALAASAFVNTHLGASMGAITWM
Helix 8: VLGASAGAVAGLVGITPAA
Helix 9: LAAIIIGFLAGVGCFMAV
Helix 10: LDVFGVHGVGGIIGAIATGIFA
Helix 11: LVTQIIAVVVVAAYAALITWGLLFII

Query ID: G8R7U9
query G8R7U9 has 12, using last 11 helices
Helix 1: AWMLVSSAFVLLMTPGLSFFYG
Helix 2: MLQSFVALGVISVLWVIIGFSLAF
Helix 3: FLLYALFQLKFAIITPALIT
Helix 4: YILFMVLFSLLIYSPLAHMTW
Helix 5: LDFAGGTVVHMSAGFAALAGAIYL
Helix 6: NVPHVILGTGLLWFGWFGF
Helix 7: AVIAFANTNIASATAMITWLFY
Helix 8: SAIGACIGAVVGLVAITPA
Helix 9: IGQSVLIGFIASIISNWMI
Helix 10: IGGIVGMLLTGILASKVGLIY
Helix 11: FYAHLIALLITAIFTFGGSYILF

Query ID: C3X831
Helix 1: AWMLTSTMLVILMIIPGLALFY
Helix 2: VLIQVFVVFSLISLLWVMY
Helix 3: YVFVAFQGTFAAITAALIVGAFA
Helix 4: AVMLFMVLWFTFSYIPLAHIVWG
Helix 5: FAGGTVVHINAGIAALVGAYM
Helix 6: FMPHSLTLTMVGASLLWVGWFGF
Helix 7: AGLAFVNTVVATAAATLSWLA
Helix 8: LGAASGAVAGLVAVTPAAGYA
Helix 9: IVLGLISGIVCLWSVSWF
Helix 10: AFGVHGVGGIVGAILTGVVV
Helix 11: VWIQVKSVLVTIAWSGIVSFIAY

Query ID: C3X1J1
Helix 1: AWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVFVTFSLITVLWFLY
Helix 3: YVFSAFQGSFACITAVLIVGAFA
Helix 4: AVMAFMALWFTFSYVPMAHIVWG
Helix 5: FAGGTVVHINAAIAGLVGAYL
Helix 6: FMPHSLVLTMVGASLLWIGWFGF
Helix 7: AGLAFVNTVVATGAATLSWLL
Helix 8: LGAASGAVAGLVTITPAAGFA
Helix 9: LVMGLIAGPVCLWGVTGL
Helix 10: AFGVHGVGGILGAILTGIAV
Helix 11: LWIQFKSVMVTIVWSGVVSFMAY

Query ID: A0A9E9LS75
Helix 1: AWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVFMTFSLITVLWFLY
Helix 3: YVFSAFQGSFACITAVLIVGAFA
Helix 4: AVMAFMAIWFTFSYVPMAHIVWG
Helix 5: FAGGTVVHINAAIAGLVGAYL
Helix 6: FMPHSLVLTMVGASLLWIGWFGF
Helix 7: AGMAFVNTVVATAAATLTWSI
Helix 8: LGAASGAVAGLVTITPAAGFA
Helix 9: LVMGLIAGPVCLWGVTGL
Helix 10: AFGVHGVGGILGAILTGIAV
Helix 11: LWIQIKSVIVTIVWSGVVSFIAY

Query ID: A0A9E9L9J1

Helix 1: AWMLTSTLLVLLMVVPGLALFY
Helix 2: VLMQVFMTFSLITVLWFLY
Helix 3: YVFSAFQGSFACITAVLIVGAFA
Helix 4: AVMAFMAIWFTFSYVPMAHIVWG
Helix 5: FAGGTVVHINAAIAGLVGAYL
Helix 6: FMPHSLVLTMVGASLLWIGWFGF
Helix 7: AGMAFVNTVIATAGATLTWAI
Helix 8: LGAASGAVAGLVTITPAAGFA
Helix 9: LVMGLIAGPVCLWGVTGL
Helix 10: AFGVHGVGGILGAILTGIVV
Helix 11: LWIQFKSVIVTVVWSGVVSFIAY

Query ID: A0A9E9LXV9
Helix 1: TAWMLTSTMLVILMIIPGLALFY
Helix 2: VLMQVFVIFSLTSVLWCLYGY
Helix 3: YVFVAFQCTFAGITCALIVGAFA
Helix 4: AVLVFIFLWFTFSYVPMAHIVWG
Helix 5: FAGGTVVHINAGIAGLIGAYMVG
Helix 6: PHSLTLTMVGASLLWVGWFG
Helix 7: IAGLAFINTIVATAAATLAWIA
Helix 8: LGAASGAVAGLVAVTPAAGFA
Helix 9: IVLGVISGFVCLWGVSGL
Helix 10: AFGVHGVGGIVGAILTGVVV
Helix 11: WIQVKSVLVTVVWSGVVSVIAY

Query ID: A0A7S4LPL9
Helix 1: WILICAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLV
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: A0A7S4GND2
Helix 1: WILVCAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLI
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: A0A7S4GNJ2
Helix 1: WILICAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLV
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: A0A7S4LPS8
Helix 1: WILVCAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLI
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: A0A7S4GMD8
Helix 1: FFLIFAGALVFMMQAGFAMLCAGSV
Helix 2: NLLDACGGAIGFYTVGFGFAYG
Helix 3: YTNYAGFFFQFAFAATAATIVA
Helix 4: YLCYSLFLTGFVYPVVVRSVW
Helix 5: VDFAGSGVVHMTGGLTALIAAIVL
Helix 6: FPAHSVALQILGTFILWFGWYGF
Helix 7: ATAALCAVTTTMAAAAGCVSAMFT
Helix 8: TTYDLTMAMNGCLAGLVAVT
Helix 9: VTPWAAIIIGVVGGWVYIGM
Helix 10: FANGFWGVLATGLFANGGLMATA
Helix 11: GSLLICQLACLAWIIGWVTTIMTPFFILL

Query ID: A0A7S4GNI0
Helix 1: WILVCAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLI
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: A0A7S4GNF3
Helix 1: WILICAALVFFMHAGFTMLE
Helix 2: ILCKNGLVVVIATICWYLV
Helix 3: FFQWAFCATCGTIVSGAMA
Helix 4: GFAVYVAAMTTFVYPIVVHW
Helix 5: FAGSGIVHMCGGISALVGAAVV
Helix 6: VPILVLGTFILFFGWFGF
Helix 7: VAMNTTAGGAMGGLVVYLL
Helix 8: ALCNGILAGLVGITAACGS
Helix 9: AFVIGGVGGLFYLAGSALA
Helix 10: FAVHGCAGFWGVLAVGLFG
Helix 11: LGVQLLGALMITLWSGGFAALFFV

Query ID: G4H971
Helix 1: SVFVFLAALLVFFMQAGFALLEAGSV
Helix 2: TFLTFGISIVAFWAFGFGLAF
Helix 3: IMFLFHLSFAAVSLAIACGGMA
Helix 4: VYIVFGLLFTIVIYPVVAHWVWG
Helix 5: FAGSTVVHLTGATAALVATILL
Helix 6: QVLSVLGVFIIWIGWFGF
Helix 7: GFFGFVSLNTNIAAAAGALAALLISWAVL
Helix 8: SMLNGILAAFVAITGACAF
Helix 9: AVVIGAIAGTITFFTAQWF
Helix 10: FSVHGVAGMWGAVSTGLFAAPRL
Helix 11: LGVQLLGLIGTFAFVLVISFIILYI

Query ID: E4T3F3
Helix 1: IAINMVWVLITGFIVMFMQFGF
Helix 2: FLIYPLGMLGFFICGFAFMFGGVGAL
Helix 3: FFLNGAYDVSVFALFLFQMVF
Helix 4: FFIYGLLVGSIIYPIYGNWVWG
Helix 5: YAGSSVVHLSGGVLAFVGAKLL
Helix 6: IPIAILGAFVLAFCWFSF
Helix 7: RISIIAVNTMIASATGALASTLYMWF
Helix 8: INGLLAGLVAITAPCAFVT
Helix 9: IIGLISGILVIEAAFFVEL
Helix 10: PVGAVAVHGVNGAFGCIALGLFA
Helix 11: LAAQTIGVAANIVYIGLIGWVVF

Query ID: E4T3F7
Helix 1: AWMIVATAFVLLMSIPGLALFY
Helix 2: VFMQVFILVAVISVEWVII
Helix 3: IVFIMFQCMFAVITPALIIGAFA
Helix 4: GFLIFSVLWSIIIYNPVAHWVW
Helix 5: LDFAGGTVVHINAGVAAIVTAIMLG
Helix 6: AHNITYVVIGAGLLWVGWFGF
Helix 7: AANALMVTHIAAAAAALTWALLDWI
Helix 8: VVGISTGAVGGLVAITPAAGF
Helix 9: ALIIGVVVSLICFCMVAYV
Helix 10: AFGVHGVGGMIGAVSTGILATPAIQAAY
Helix 11: WVQLIAIGATIIFSGIGTFILF

Query ID: E4T0A4
Helix 1: LTTFMILATSLVMLMTPGLAFFY
Helix 2: IMMQSFVSMGISTVLWFAF
Helix 3: YIFIAYQMMFAIITPALITGAFI
Helix 4: SYIFFLVLWQIFVYYPFVHMVWG
Helix 5: FAGGITVHATAGFAALASVYFV
Helix 6: IPLVAIGTALLWFGWYGF
Helix 7: LAVNSVTISAFLNTDTAASFAAITWLL
Helix 8: FIGLMTGAVAGLATITPA
Helix 9: IYSAAIIGIIAAVGCFLAV
Helix 10: LDVWGVHGMGGVIGTICLGFFA
Helix 11: LLLKECVAILFAISYAFIFTVLLF

Query ID: A0A856LCH5
Helix 1: AWLLTCTALVILMTLPGLGLFY
Helix 2: VLMQCFIIFALIVVLWSIY
Helix 3: YAYMAFQAAFAAITCALIVGAFA
Helix 4: AVLLFTVIWFTFSYLPMAHMVWFWA
Helix 5: YAGGTVVHINAAIAGLVGSYMVG
Helix 6: PHSLTMTMIGASLLWFGWFGF
Helix 7: AALAFVNTLLATAAATLSWTA
Helix 8: LGGASGAVAGLVAVTPAAGFV
Helix 9: IVLGLIAGVVCLWGVNGL
Helix 10: VFGVHGVGGMLGAILTGVFAA
Helix 11: VWIQFQGVVTTLVWSGVVAFIAF

Query ID: A0A378YR15
Helix 1: AWLLTCTALVILMTLPGLGLFY
Helix 2: VLMQCFIIFALIVVLWSIY
Helix 3: YAYMAFQAAFAAITCALIVGAFA
Helix 4: AVLLFTVIWFTFSYLPMAHMVWFWA
Helix 5: YAGGTVVHINAAIAGLVGSYMVG
Helix 6: PHSLTMTMIGASLLWFGWFGF
Helix 7: AALAFVNTLLATAAATLSWTA
Helix 8: LGGASGAVAGLVAVTPAAGFV
Helix 9: IVLGLIAGVVCLWGVNGL
Helix 10: VFGVHGVGGMLGAILTGVFAA
Helix 11: VWIQFQGVVTTLVWSGVVAFIAF

Query ID: A0A8T8BI10
Helix 1: AWLLTCTAFVILMTLPGLGLFY
Helix 2: VLMQCFIIFSLVVVLWAIY
Helix 3: YAYMAFQAAFAAITCALIVGAFA
Helix 4: AVLLFTVIWFTFSYLPMAHMVWFW
Helix 5: YAGGTVVHINAAIAGLVGSYMVG
Helix 6: PHSLTMTMIGASLLWFGWFGF
Helix 7: AALAFVNTLLATAAATLSWTA
Helix 8: LGGASGAVAGLVAVTPAAGFV
Helix 9: IVLGLLAGLICLWGVNGL
Helix 10: VFGVHGVGGMLGAILTGVFAA
Helix 11: VWIQFQGVVTTLVWSGVVAFIAF

Query ID: A0A378YY10
Helix 1: FLLLGAILVLAMHAGFAFLEL
Helix 2: LVKILTDFAVSGLAYFFIGYPLA
Helix 3: LVRFFFLLTFAAAIPAIVSGGI
Helix 4: ATFFLVGVIYPFFEGIAWN
Helix 5: FAGSVVVHAVGGWIGLAAVVHLGA
Helix 6: FLALGAWILIVGWFGFNVMSA
Helix 7: ISGLVAVNSLMAMVGGTLAAMWV
Helix 8: FIHNGPLAGLVAVCAGS
Helix 9: LGALVVGAIAGVLFVKLFT
Helix 10: LGVWPLHGVCGVWGGIAAGLFG
Helix 11: FVAQVVGTVMGVAIAFAGGYVVY

Query ID: A0A8T8BK87
Helix 1: FLLLGAILVLAMHAGFAFLEL
Helix 2: LVKILTDFAVSGLAYFFIGYPLA
Helix 3: LIRFFFLLTFAAAIPAIVSGGI
Helix 4: ATFFLVGVIYPCFEGIAWN
Helix 5: FAGSVVVHAVGGWIGLAAVLHLGA
Helix 6: FLALGAWILIVGWFGFNVMSA
Helix 7: ISGLVAVNSLMAMVGGTLVAMWI
Helix 8: FIHNGPLAGLVAVCAGSDV
Helix 9: ALVVGAVAGGLFVWLFTVT
Helix 10: VWPLHGVCGIWGGLAAGIFG
Helix 11: FVAQVIGTVMGVAIAFAGGYLVY

Query ID: A0A379A0S9
Helix 1: YIFNTLLFLLGGFLVMWMAAGF
Helix 2: IALYSIAGILFWLTGYNLMY
Helix 3: WFFQMVFVATAASIVSGTLA
Helix 4: PFLLFTVVLTGLLYPIAGSWQWG
Helix 5: FAGSTLVHSVGGWAALAGAIVL
Helix 6: IPLATLGTFILWLGWFGF
Helix 7: IFANTNMAAAGGVVAAMALT
Helix 8: VDVTMALNGALAGLVSITA
Helix 9: TVAQAVFIGAVGGALVVFVVPLL
Helix 10: IPVHLVCGIWGTLIVPLS
Helix 11: YGIQLVGVVSYGAFIFVTSLVLWMIL

Query ID: A0A0H3KTD3
Helix 1: ICTALVLFMSIPGIALFYGGL
Helix 2: LSMLTQVAVTFSLVCVLWVIY
Helix 3: YIHVAFQASFACITVGLIVGAIA
Helix 4: AVLIFVAVWLTLAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAALAFLNTVVATAAAVLAW
Helix 8: SLLGACSGFIAGLVAITPA
Helix 9: VGGALIIGLAGGLAGIWGVTTL
Helix 10: VFGVHGVCGIIGCILTGVFA
Helix 11: AVQLFSVGVTIVWSAVVAFIGF

Query ID: D4GLQ6
Helix 1: ICTALVLFMSIPGIALFYGGL
Helix 2: LSMLTQVAVTFSLVCVLWVIY
Helix 3: YIHVAFQASFACITVGLIVGAIA
Helix 4: AVLIFVAVWLTLAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAALAFLNTVVATAAAVLAW
Helix 8: SLLGACSGFIAGLVAITPA
Helix 9: VGGALIIGLAGGLAGIWGVTTL
Helix 10: VFGVHGVCGIIGCILTGVFA
Helix 11: AVQLFSVGVTIVWSAVVAFIGF

Query ID: A0A6G6JU01
Helix 1: NAFMMICTALVLFMSIPGIALFY
Helix 2: MLTQVAVTFSLVCVLWVVY
Helix 3: YIHVAFQASFACITVGLVVGALA
Helix 4: AVLIFVGVWLTLAYLPIAHMVWA
Helix 5: FAGGTVVHINAAVAGLVGAYLVG
Helix 6: PHNLPMVFTGTAILYVGWFG
Helix 7: IAALAFLNTVVATAGAVLAW
Helix 8: SLLGACSGFIAGLVAITPA
Helix 9: VGGALIIGIVGGLAGIWGVTTL
Helix 10: VFGVHGVCGIIGCILTGVFA
Helix 11: AIQLLSVGVTIVWSAVVAFIGF

Query ID: A0A7K0HBQ0
Helix 1: VWMLLAAMLVFFMQPGFALV
Helix 2: FMLGSILFWAIGFGIMFGAGGFM
Helix 3: FLIFQTVFCATAATIVSGAMA
Helix 4: MYLAYTVLISVLIYPVSGHWTW
Helix 5: FAGSTVVHSVGGWVALVGAAII
Helix 6: LTIACLGVFILWFGWFGF
Helix 7: VFLTTNLAACTGGFFSLIVAWF
Helix 8: LSLTLNGVLAGLVGITAG
Helix 9: PVGAALIGAICGVVMIFAVDFI
Helix 10: ASSVHGVCGCLGTILSGLFAT
Helix 11: FLMAQIFGALVVGCWAAFMGFVVF

Query ID: A0A1D2JK63

Helix 1: AYILVASAMVMVMVPGLGFLY
Helix 2: MIWACMGSTSIVAFQWYFW
Helix 3: LLFAFYQMQFCAVTAAIIVGAV
Helix 4: LPAMVFIFFWATLVYCPVACWVWNI
Helix 5: YAGGGPVEICSGMSALAYSMVLG
Helix 6: PHNVSLILLGTVFLWFGWLGF
Helix 7: AVMACWNTNLTAGFAAVTWVLL
Helix 8: KWSMVGWCSGTISGLVAAT
Helix 9: IPPWASVVLGIVTGVVANY
Helix 10: GVAGVVGLIFNAFFGTDAVVGL
Helix 11: LYIQIAFIVAAAAYTFVVSAIIAYAI

Query ID: C1G973
Helix 1: AYILVASAMVMVMVPGLGFLY
Helix 2: MIWACMGSTSIVAFQWYFW
Helix 3: LLFAFYQMQFCAVTAAIIVGAV
Helix 4: LPAMVFIFFWATLVYCPVACWVWNI
Helix 5: YAGGGPVEICSGMSALAYSMVLG
Helix 6: PHNVSLILLGTVFLWFGWLGF
Helix 7: AVMACWNTNLTAGFAAVTWVLL
Helix 8: KWSMVGWCSGTISGLVAAT
Helix 9: IPPWASVVLGIVTGVVANY
Helix 10: GVAGVVGLIFNAFFGTDAVVGL
Helix 11: LYIQIAFIVAAAAYTFVVSAIIAYAI

Query ID: C0S0W9
Helix 1: AYILVASAMVMVMVPGLGFLY
Helix 2: MIWACMGSTSIVAFQWYFW
Helix 3: LLFAFYQMQFCAVTAAIIVGAV
Helix 4: LPAMVFIFFWATLVYCPVACWVWNI
Helix 5: YAGGGPVEICSGMSALAYSMVLG
Helix 6: PHNVSLILLGTVFLWFGWLGF
Helix 7: AVMACWNTNLTAGFAAVTWVLL
Helix 8: KWSMVGWCSGTISGLVAAT
Helix 9: IPPWASVVLGIVTGVVANY
Helix 10: GVAGVVGLIFNAFFGTDAVVGL
Helix 11: LYIQIAFIVAAAAYTFVVSAIIAYAI

Query ID: C1GR74
Helix 1: AYILVASAMVMVMVPGLGFLY
Helix 2: MIWACMGSTSIVVFQWYFW
Helix 3: LLYAFYQMQFCAVTAAIIVGAV
Helix 4: LPAMVFIFFWATLVYCPVACWVWNI
Helix 5: YAGGGPVEICSGMSALAYSMVLG
Helix 6: PHNVSLILLGTVFLWFGWLGF
Helix 7: AVMACWNTNLTAGFAAVTWVLL
Helix 8: KWSMVGWCSGTISGLVAAT
Helix 9: IPPWASVVLGIVTGVVANY
Helix 10: GVAGIVGLIFNALFGTDAIVGL
Helix 11: LYIQIAFIVAAAAYTFVVSAIIAYAI

Query ID: A0A533I6R2
Helix 1: LLSGILVMMMTIPGLALFYGGL
Helix 2: LSVLMQVLTTFCVMSLLWVMF
Helix 3: LSFVIFQLAFACIAPALIVGATA
Helix 4: AILMFIVIWFFLSYLPMAHMVWWWG
Helix 5: FAGGTVIHINAGVAGLVAAYVA
Helix 6: APHNLTFTLIGGCLLWIGWFG
Helix 7: LTAMALLNTVVAPAAAALAW
Helix 8: SLLGAVSGVVAGLVGVTPAA
Helix 9: MGAIVIGAVAGAVCFWAVVWL
Helix 10: VFGIHGIGGIVGAILTGVFAAPSLGG
Helix 11: VYAQTLGVVICIIWSGVVSFLAI

Query ID: A1B3N0
Helix 1: WMMISAILVMAMSIPGLALFY
Helix 2: VLMQVFTIFCIMSILWVCFGYSLA
Helix 3: YVFIIFQMAFACIAPALIVGA
Helix 4: FAAVLAFVVIWFFFSYLPMAHMVWWWG
Helix 5: FAGGTVIHINAGVAGLVAALVV
Helix 6: APHNLPFTFLGGCLLWIGWFGF
Helix 7: AAMAILNTTVATAAAALAWA
Helix 8: LLGGVSGAIAGLVGITPAA
Helix 9: MGAIVIGLAAGFLCMWFVVSL
Helix 10: VFGIHGIGGIVGAILTGVFAA
Helix 11: LGVIVAVTWSAVVSFIALMIVKAVI

Query ID: A0CBN6
Helix 1: WVMITSFSAQLTILGFAFIGS
Helix 2: VITVLLGSVITIFFFWLIGYGFA
Helix 3: FIHSTVGAVIVASLFGLG
Helix 4: YFSVSVCLAFITAILYPIA
Helix 5: GASYIHLFGGILALVVSIFL
Helix 6: IYIGYGSFILTIAILIFVNGA
Helix 7: GLIATNTIVASAFSALTSFFLY
Helix 8: LSLIALSRGSVAGIVAISAM
Helix 9: IWQSAFTGVLAGIVYIFLILVI
Helix 10: IASHLGPGLLGTILVGFLSLTHGLM
Helix 11: IVGIIVLVLWALFVALGLQAAAYWI

Query ID: A0DZ27
Helix 1: WLLIAGIVLAFSQLGFGFLE
Helix 2: IVIKVFLGMCLTVLIYWLF
Helix 3: FVFKATLSCIGVSIVSGGAA
Helix 4: FLAWGVLALFYSGFVSPAIVHW
Helix 5: FIFYSAGVAALVVTVVS
Helix 6: IYVAFGTVILFATWMFI
Helix 7: PYVQGLVAVNTLVAGAAGGFWSF
Helix 8: LFSISRGILAGLVASSAA
Helix 9: IWATTIVASIAGIVYTLTATA
Helix 10: VVPIFLHGGFIGVLFTGLL
Helix 11: LGLLIITVWVAFFVFFILIVL

Query ID: A0BIN7
Helix 1: WILISGFIIVLTQVGFAFIE
Helix 2: IVIKVILGLFLTILIWWLF
Helix 3: FVFRASGAAIAVSVLSGA
Helix 4: FLAWSILAIIYAGFIYAGLAHWTLA
Helix 5: FSGAGVVFFAAGVAGLVVTVLL
Helix 6: IYIAFGSILVFAGWLFYNGGVVA
Helix 7: VAVNTLVAGATGGFFAFIIRYF
Helix 8: LVALSRGIISALVAVSAAT
Helix 9: WTAFIYGLLAAVFYSVLAKV
Helix 10: VVPVFLGNGFLGIFLSAFF
Helix 11: LGLLIIFVWVAFFVLITLLIL

Query ID: A0BJ48
Helix 1: WLLIAGIVLAFSQLGFGFLE
Helix 2: IVIKVFLGMCLTVLIYWLF
Helix 3: FVFKATLSCIGVSIVSGGAA
Helix 4: FLAWGVLALFYSGFVSPAIVHW
Helix 5: FIFYSAGVAALVVTVVS
Helix 6: IYVAFGTVILFATWMFI
Helix 7: PYVQGLVAVNTLVAGAAGGFWSF
Helix 8: LFSISRGILAGLVASSAA
Helix 9: IWATTIVASIAGIVYTLTATA
Helix 10: VVPIFLHGGFIGVLFTGLL
Helix 11: LGLLIITVWVAFFVFFILIVL

Query ID: A0DQP0
Helix 1: WILISGFIIVLTQVGFAFIE
Helix 2: IVIKVMLGLFLTILIWWLF
Helix 3: YTYFVFRASGASIGVSVLSGA
Helix 4: FLAWSILTIVYAGFIYAGLAHWTLA
Helix 5: FSGAGVIFFAAGVAGLVLTVLL
Helix 6: IYIAFGSILVFSGWQFY
Helix 7: VNTMVAGATGGFFAFIIRYF
Helix 8: LIALSKGIISALVAVSAAT
Helix 9: WTAFFYGLMAAGVYSVLAKA
Helix 10: VIPVFLGNGFLGIFLSAFF
Helix 11: FGLLIIFVWVAFFILITLLIL

Query ID: A0BNP4
Helix 1: WVLVSGFIVILTQVGFAFIG
Helix 2: VVIKVFLGLFLTVLIWWLF
Helix 3: FVFRASGAAVGTAILAGA
Helix 4: FLGWSIFSVLYSGFIYAGL
Helix 5: GAGVVFFAAGVAGLILTILL
Helix 6: LYIGFGSLLVLAGWLFY
Helix 7: QYTQGLVAVNTLIAGATGGFFSF
Helix 8: LAALSRGVICGLVAVSAAA
Helix 9: WTAFLYGAIAALIYSFLAKV
Helix 10: VVSVYFGSGFIGIVLSALF
Helix 11: LGLLIIFAWVAFFTLIILLAF

Query ID: A0E7D8
Helix 1: TWVLSCAFFSILGLLGYSMIAA
Helix 2: IITILLGGILTILAFYITGYAFA
Helix 3: FVFHTIAAIFVTSIFALG
Helix 4: FFSFSFGVIILQGLLYPIVVHWTFG
Helix 5: FGGSSVIHVFGGVTALLASLLL
Helix 6: FFVGIGTILLVVVQIIFLSGL
Helix 7: VPVNALLAASFGGLSSYVSYYL
Helix 8: LITIARGSLAGVVAVSASV
Helix 9: WAAAFIGTLAGISYLVIQLIV
Helix 10: VGAHLVPGILGTLLYGIL
Helix 11: FGIQIVGVLSIAGWALLILAVLVPL

Query ID: A0EG61
Helix 1: TWVLSCAFFSVLGLLGYSMIAA
Helix 2: IITILLGGILTILAFYITGYAFA
Helix 3: FVFHTIAAIFVTSIFAFG
Helix 4: FFSFSFGVIILQGLLYPIVVHWTFG
Helix 5: FGGSSVIHAFGGVTALVASLLL
Helix 6: FFVGIGTILLVVVQIIFLSGL
Helix 7: VPVNTLLAASFGGLSSYVSYYL
Helix 8: LITIARGALAGVVAVSASV
Helix 9: WAAAFIGTLAGISYLVVQLIV
Helix 10: VGAHLVPGILGTLLYGIL
Helix 11: FGIQIVGVLSIAGWALLILAVLVPL

Query ID: A0CLK6
Helix 1: FWTTLTGAVVLIMQLGFAFLEGGCV
Helix 2: VYANTAISIIMMWIVGYGLM
Helix 3: FVFNTALAAAANSIVSGGAA
Helix 4: GYIALSVLFSGFIYPICIHWAY
Helix 5: FAGSGAIHLTAGIGALVVTFML
Helix 6: TFICLSCLTLYMAWMCFNSGSTLAL
Helix 7: IANTMVGGASGGLFVFFYHYF
Helix 8: FSLVMVCNGNLAGLVAVTGSN
Helix 9: WAAFVIGIIGGIIYVLVAKIL
Helix 10: IPIHAGCGLAGAMCPGWF
Helix 11: AYQWGVQVLGCVCFVAWSVAWHYV

Query ID: A0EC09
Helix 1: WVLVSGFIVILTQVGFAFIG
Helix 2: VVIKVFLGLFLTVLIWWLF
Helix 3: FVFRASGAAVGTAILAGA
Helix 4: FLGWSIFSVLYSGFIYAGL
Helix 5: GAGVVFFAAGVAGLILTVLL
Helix 6: LYIGFGSLLVLAGWLFY
Helix 7: QYVQGLVAVNTLIAGASGGFFSY
Helix 8: LAALSRGVLCGLVAVSAAA
Helix 9: WTAFLYGAIAALIYSFLAKV
Helix 10: VVSVYFGSGFIGIVLSALF
Helix 11: LGLLIIFAWVAFFTLIILLAF

Query ID: A0BE57
Helix 1: YFWTQFAGIVVLLMQLGFAFLEGGCV
Helix 2: VYLNTCIAVICWWLVGYGICMGSGKF
Helix 3: WVLQTSVGAAANSIVSGGAV
Helix 4: IIGYCFLSVAFSSFIYPICAHWT
Helix 5: IHFMSALGALVLTVMLGA
Helix 6: YICLSTLSLYTCWIFFNAG
Helix 7: AAGRATTNTIIAGASGGLTLMVL
Helix 8: FSLVMICNGNLAGLVAVTGS
Helix 9: LWAAFVIGILGGLTYWGFGIL
Helix 10: AFPIHGGCGLIGAQFPGWF
Helix 11: LGTVVWLGWSVVLHAIVIFVL

Query ID: A0E040
Helix 1: WVLISGFIVILTQVGFAFIG
Helix 2: VVIKVFLGLFLTILIWWLF
Helix 3: FVFRAAGAAFGIAILAGA
Helix 4: FLGWSVLTLIYSGFIYAGL
Helix 5: GAGVVFFAAGAAGLILTVIL
Helix 6: LYIGFGSLLVFAGWLFY
Helix 7: QYAQGLVAVNTLIAGATGGFVSFVIRYF
Helix 8: LVALSRGVVSGLVAVSAAA
Helix 9: WTAFIYGFVAALFYSILAKA
Helix 10: VIPVYLGSGFIGIFLSGFF
Helix 11: LGLLIIFAWVVFFTLLTLLAL

Query ID: A0EAD9
Helix 1: IGYLCICAAFVLLMQVGFAFLEGGCL
Helix 2: IFMNTCVTVVIWWLVGYGIA
Helix 3: FAFQTAVASAATSIVSGGAAG
Helix 4: YFILSVVFSSVIYPFCAHWGFG
Helix 5: YAGSGTIHASAGMGALMTTMLL
Helix 6: IYITLACLSLWVCWCFFNGGSSLGI
Helix 7: IMNTFIAGASGALTVFFIFYLMN
Helix 8: YSLVMICNGNLAGLVAITGP
Helix 9: AWAAFVIGILGGMMMVFANRVL
Helix 10: ISIHFACGMLGANLVSWF
Helix 11: LGSFIYIGWSALIHLITLLFI

Query ID: A0EGB0
Helix 1: IGYLCICAAFVLLMQVGFAFLEGGCL
Helix 2: IFMNTCVTIVIWWLVGYAIA
Helix 3: FAFQTAVASAATSIVSGGAAG
Helix 4: YFILSVVFSSVIYPFCAHWGFG
Helix 5: YAGSGTIHASAGMGALMTTMLL
Helix 6: IYITLACLSLWVCWCFFNGGSSLGI
Helix 7: IMNTFIAGASGALTVFFIFYLMN
Helix 8: YSLVMICNGNLAGLVAITGP
Helix 9: AWAAFVIGILGGMMMVFANRVL
Helix 10: ISIHFACGMLGANLVSWF
Helix 11: LGSFIYIGWSAIIHLITLLFI

Query ID: A0E1C2
Helix 1: STWVLITSFSALLTILGFAFI
Helix 2: SAVITVLLGAVITILFFWLLGYGF
Helix 3: LIFQSVGAIIVSSLFGLG
Helix 4: FFSVSVCLAVISGFLYPTALHW
Helix 5: YIHFFGGVTALVVSIFL
Helix 6: INIGYGSIILSVATLIFINGA
Helix 7: GLIAVNTLIAATFSALTSFVAQYL
Helix 8: LIAIARGSVAGIVAISAI
Helix 9: IWESALTGTLAGLVYIVLILVI
Helix 10: LATHLGPGLLGTLLVGVLTLS
Helix 11: FGLQLVGVLALLGWGLLIALFVI

Query ID: A0A1H1U2Q6
Helix 1: MLMSASLVLLMTPGLAFFYGG
Helix 2: VLNMMMMSFGSIAVVAVVYVLW
Helix 3: IVGVGFQATFAIITVALISGALA
Helix 4: TWMIFTAIWVTVCYFPLAHMVW
Helix 5: FAGGTVVHINAGIAALVLAIIIG
Helix 6: PHNLTLVMLGAALLWFGWFGF
Helix 7: AGLAWVNTTTATAAAVIGWLV
Helix 8: LGAASGVVAGLVAITPAA
Helix 9: VGSLAVGAVAGVLSALAVGL
Helix 10: VVGVHLVSGLWGTVAIGFLATETGLFYG
Helix 11: LVVQILIALVAVAFAGIVTFVIGLIL

Query ID: F3QPR6
Helix 1: TAWMIVATLLVFMMTIPGIALFY
Helix 2: LVMQSLAIAGVVSILWVAFGYSLA
Helix 3: MLFVMFQCMFALITPALILGAF
Helix 4: AGFLCFTVLWSILVYMPMAHWVWG
Helix 5: FAGGTVVHINAGVAALVMALMV
Helix 6: ITPHNIPFVFLGTALLWLGWFGF
Helix 7: AANAFLVTHIATCMAAVTWAA
Helix 8: VGACTGAVAGLVAITPAA
Helix 9: FGALCIGLITSAVCFWMVAVV
Helix 10: AFGVHGVGGIIGSILTGVFAT
Helix 11: LWIQVAATVISMAFSAVMTFVLF

Query ID: A0A6I3S3R3

Helix 1: VATTLVLFMTIPGIALFYAG
Helix 2: VLSVVMQSFAICCSITIVWYV
Helix 3: LFMMFQMTFAILTPALMCGAFA
Helix 4: ALFLFMVLWSLFCYVPICHWVW
Helix 5: LDYAGGTVVHINAGVAGLVACLML
Helix 6: APHNLILAMVGACFLWIGWFGF
Helix 7: AVMAIVVSQIAAAAAALIWM
Helix 8: VLGAISGAVAGLVAITPASGF
Helix 9: ALFIGLCGGFICYFGATRL
Helix 10: AFGVHGVGGIAGAILTGVFASEAI
Helix 11: VWIQTESVIATLIYASIVTYVLL

Query ID: F3QNA7
Helix 1: VATTLVLFMTIPGIALFYAG
Helix 2: VLSVVMQSFAICCSITIVWYV
Helix 3: LFMMFQMTFAILTPALMCGAFA
Helix 4: ALFLFMVLWSLFCYVPICHWVW
Helix 5: LDYAGGTVVHINAGVAGLVACLML
Helix 6: APHNLILAMVGACFLWIGWFGF
Helix 7: AVMAIVVSQIAAAAAALIWM
Helix 8: VLGAISGAVAGLVAITPASGF
Helix 9: ALFIGLCGGFICYFGATRL
Helix 10: AFGVHGVGGIAGAILTGVFASEAI
Helix 11: VWIQTESVIATLIYASIVTYVLL

Query ID: A7HSP2
Helix 1: LTATALVLLMTIPGLALFYGGMV
Helix 2: NFAIAALMSVIWMVIGYSLA
Helix 3: VFMTFQMTFAIITPALITGAFA
Helix 4: SMLVFMALWLVFIYAPICHWVWG
Helix 5: FAGGTVVHINAGVAGLVACLVL
Helix 6: APHNVVLTMVGASLLWVGWFGF
Helix 7: AGMAMAVTQIATAAAALSWM
Helix 8: LLGLATGAVAGLVAITPASGF
Helix 9: ALWIGLAAGIICFIASTSV
Helix 10: VFGVHAIGGIVGAVLTGVFASAA
Helix 11: IQIKGIVATIVYCGLGTFVLLMV

Query ID: A7HT14
Helix 1: WVLICTILVILMQAGFTCL
Helix 2: FCVAGLGFWLVGFGLMFGFSIGGFF
Helix 3: WVMVFFFFQLAFCSTSTTIVAGAVA
Helix 4: GYLITAAVLSMLIYPVFGHWAW
Helix 5: FAGSTVVHSIGGWIALAAILVI
Helix 6: MATLGMFLLWIGWFGFNGGSTLAL
Helix 7: YILVHTMLAAAAGGVAVMGLSW
Helix 8: LNGILAGLVAITANCHI
Helix 9: AVLIGIGGGIVCFLASELL
Helix 10: VPVHLAAGIWGTLAVALFG
Helix 11: QGVLAAGVFAFGVAFVVLTIV

Query ID: A7HSN9
Helix 1: VFFILMGAILVFAMHSGFAFL
Helix 2: FAISTIAYFFVGYAVAYGVDFLV
Helix 3: SLVKFFFLLTFAAAIPAIISG
Helix 4: AMATAIIVGLVYPFFEGLVWN
Helix 5: FAGSIVVHAVGGWLAFGAVLML
Helix 6: IPWLALGSWLLCMGWFGF
Helix 7: SGLVALNSLLAMAGGIIASLVV
Helix 8: FIHNGALAGLVAVCAGSDLM
Helix 9: LVVGAVAGALFVVMFEAC
Helix 10: VWPLHGLCGLWGGIAAGIFGL
Helix 11: LSQLVGSFAGVVYAGIAGFAVYGLL

Query ID: E0TGP9
Helix 1: VFIFNTLLFLIMGMVVMFMSAGF
Helix 2: ISLYAIAGLMVWLCGYNLIY
Helix 3: WFFQMVFVATAASIVSGTL
Helix 4: WPFFIFTAVLTGFIYPIQASW
Helix 5: LVHATGGWAALAGALALGA
Helix 6: VAFYGSSMPLATLGTFILWLGWFGF
Helix 7: IFVHTNMAAAAGVVTVLILSTLLL
Helix 8: MVLNGAIGGLVSITAEPLI
Helix 9: GTPILTAVIVGSVGGVIVFLT
Helix 10: VVGAIPAHLFCGIWGTLIVPFS
Helix 11: IGAQATGVAANAIFVFGTSLVLWFLL

Query ID: E0TCV4
Helix 1: ILNSFLFLFGGVLVMFMAAGF
Helix 2: MVLYALAGIAYYVIGYNLMY
Helix 3: WFFQMVFVATAASVVSGAV
Helix 4: FPFLIFVLVLTAIIYPIQGAW
Helix 5: IVHSVGGWAALTGVIILGP
Helix 6: AIPGSSLPLATLGTFILWLGWFGF
Helix 7: IFANTNMAAAGGVTAALITTKLVY
Helix 8: FVLNGALAGLVSITAEPLT
Helix 9: AILIGATGAVIVTFAVPMLD
Helix 10: VVGAIPVHLVAGIFGTLVVPL
Helix 11: LGVAAVAAWVIPTSAIVWGVL

Query ID: C6DB68
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A837DQS9
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A7T5QRS5
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A7V8TEX2
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCVAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A419AI10
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A419AVL2
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A7V8IKS6
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: AALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALVIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A0J6AS72
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVGLWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: AALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A086F0C2
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVVVCLVWSGVVAFVAF

Query ID: A0A433P2R5
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A7V8TJ53
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: IWVQLFSVIVCLVWSGVVAFVAF

Query ID: A0A221TCD6
Helix 1: NAFIMICTALVLFMTIPGIALFY
Helix 2: MMTQVSVTFAMVCILWVVY
Helix 3: VAYQASFACITVALIVGAIA
Helix 4: AVLIFVALWLTFSYLPMTHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAILYIGWFGF
Helix 7: GAANGIAALAFLNTVVATAAAILAWV
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALIIGLAGGVAGLWGVTVL
Helix 10: VFGVHGVCGIVGCILTGVF
Helix 11: VWVQLFSVIVCLVLSGVVAFVAF

Query ID: E0VUA6
Helix 1: WLMTSSFIIFTMQTGFGLLESGCI
Helix 2: NVVDIVLGGFTYWLFGYGL
Helix 3: LAAFIFQLSFATTATTIVSGAMA
Helix 4: AYCLFSFLNTVVYCVPAGWVW
Helix 5: VHVVGGSSAFASAFMLGPRL
Helix 6: LGNPINCCMGLFVLWWGWLAF
Helix 7: AVNTMLSSFSGGLFGLIYSLAF
Helix 8: ILHLINGVLGSLVSITAGCYLYT
Helix 9: IIGFVGSFLTNVSTPWFIHLGL
Helix 10: TSVHGLCGLWGVLSVGIFA
Helix 11: GWYLLGVQFLECICLSAWAIVTTLILLWVVNLVL

Query ID: G4R7P1
Helix 1: ILNSFLMIFGGVLVMWMAAGFAMLEA
Helix 2: LLKNISLFAIAAIFYYLI
Helix 3: FFFQVMFCATTASIVSGTLA
Helix 4: ILPFLIFTVVLTALIYPI
Helix 5: AGSTVVHSVGGWAALAGAILL
Helix 6: MPLATLGTFILWMGWFGF
Helix 7: IMANTNAGAAGGAVAALILTAIIY
Helix 8: FVLNGALAGLVSVTAEPLT
Helix 9: ASLIGAVGGVIVVFAVPLL
Helix 10: IPVHLLAGIWGTIAVIFTNA
Helix 11: VQLLSIVVVGIFTFVASFVVWLIL

Query ID: A0A165MFD1
Helix 1: FFIFICAVLVLFMQAGFALV
Helix 2: LSIGAILFYFVGYGIMYPG
Helix 3: FLFQVAFAATAATIVSGAVAG
Helix 4: YLIYSAVISGLVYPISGFWQWG
Helix 5: FAGSLLVHALGGFAGLAGAIVL
Helix 6: LALSTLGVFILLIGWYGF
Helix 7: IAANTTLAATAGAVVAMFFAWALF
Helix 8: MGLNGMLAGLVAITANCDAVT
Helix 9: IIGAVGGILVVAGIKLLDVL
Helix 10: GAWPVHGLNGVWGGVAAWIF
Helix 11: VAQLVGSIAIPLWGFATMLVLFFIL

Query ID: A0A165MAC2
Helix 1: TTSWMLTSTALVLLMIPGLAMFYG
Helix 2: MMHSFGAMVIIGVLWPMVGYAL
Helix 3: YVFAMFQGKFAIITPALIAGAFA
Helix 4: GYALFIALWSIIVYSPICHWVWA
Helix 5: TVVHISSGVTALVAALYLGS
Helix 6: NNLVMTLTGAGLLWVGWFGF
Helix 7: TARALTVTQVSAAAGAFTWMV
Helix 8: LGVASGILAGLVAITPAAG
Helix 9: GAFALGALASIVCYSAILI
Helix 10: AFGVHGVGGIVGALALVFFIRPAW
Helix 11: VQATAVGITVVYAAIVSLLILVLI

Query ID: Q3B3Q6

Helix 1: FFIFICAVLVLFMQAGFALV
Helix 2: LSIGAILFYFVGYGIMYPG
Helix 3: FLFQVAFAATAATIVSGAVAG
Helix 4: YLIYSAVISGLVYPISGFWQWG
Helix 5: FAGSLLVHALGGFAGLAGAIVL
Helix 6: LALSTLGVFILLIGWYGF
Helix 7: IAANTTLAATAGAVVAMFFAWALF
Helix 8: MGLNGMLAGLVAITANCDAVT
Helix 9: IIGAVGGILVVAGIKLLDVL
Helix 10: GAWPVHGLNGVWGGVAAWIF
Helix 11: VAQLVGSIAIPLWGFATMLVLFFIL

Query ID: Q3B6Q2
Helix 1: TTSWMLTSTALVLLMIPGLAMFYG
Helix 2: MMHSFGAMVIIGVLWPMVGYAL
Helix 3: YVFAMFQGKFAIITPALIAGAFA
Helix 4: GYALFIALWSIIVYSPICHWVWA
Helix 5: TVVHISSGVTALVAALYLGS
Helix 6: NNLVMTLTGAGLLWVGWFGF
Helix 7: TARALTVTQVSAAAGAFTWMV
Helix 8: LGVASGILAGLVAITPAAG
Helix 9: GAFALGALASIVCYCAILI
Helix 10: AFGVHGVGGIVGALALVFFIRPAW
Helix 11: VQATAVGITVVYAAVVSLFLLVLI

Query ID: A5D4I5
Helix 1: AWVLASTALVMLMTLPGLALFY
Helix 2: TIMYSFFAMVIISIQWALY
Helix 3: VFMIFQMMFAVITPALISGAFA
Helix 4: AFLAFLILWATFVYDPVAHWVW
Helix 5: LDFAGGTVVHILSGVSGLVACLVL
Helix 6: IPHNLPFVVVGAALLWFGWFGF
Helix 7: AAGAFVVTHLATAAAALSWVA
Helix 8: LGAASGAVAGLVAVTPASGF
Helix 9: ALIIGLVAGALCYLAVGVL
Helix 10: AFGVHGIGGTWGAIATGLFA
Helix 11: LANQLIAVAASWAAALAGTFIIL

Query ID: C5KTM6
Helix 1: IWLIVCGALVMFMQAGFASLEAGAV
Helix 2: NLIDVCVGTLFWWAFGFAIAYGY
Helix 3: WFFQWAFSATAATIVSGGVAE
Helix 4: YFVYSAIMTGFIYPFIVAWGWS
Helix 5: GIIHLTGGTGALVGAFIL
Helix 6: IPLIVIGVFILWFGWFGF
Helix 7: ATAHTAALAAVNTVLSGASGGFTLFII
Helix 8: VAAVCNGILAGLVSITASCAIVI
Helix 9: IIGAIGGIFYQCAAVGIRYL
Helix 10: FPIHGVCGTWGVLAVPFFDFA
Helix 11: IQLLAVVAIMAYVGGCSIIVFGV

Query ID: C5LAG4
Helix 1: IWLIICGALVMLMQFGFAAL
Helix 2: VSVGTLCWWALGFGIAYGVG
Helix 3: WFFQWAFCATAATIVSGGVAE
Helix 4: YFVYSAMMSAFIYPAVVQFTW
Helix 5: SAYYDFAGSGIVHLTGGVGALTGALIL
Helix 6: VPLIVLGTFVLWFGWFGF
Helix 7: AAVNTALAAAAGGFVTFLIRFL
Helix 8: VVGVCNGMLAGLVSITAGCA
Helix 9: SAIAIATIGAVVYQFASWSI
Helix 10: FAVHGACGIWGVLAAPLWD
Helix 11: FGIQLLGVVVIVAFVGASSAVIFGF

Query ID: C0QSY0
Helix 1: TAWMIVATAFVVLMSIGGLTLFY
Helix 2: TVMMVFLAYATATVVWVLW
Helix 3: FVFIAFQGTFAAITVALISGAAI
Helix 4: TWLIFVVLWVTAVYAPIAHVVWG
Helix 5: FAGGTVVHINAGVAGLVLAIL
Helix 6: ILPSSVILTLVGAALLWFGWFGF
Helix 7: AGVALLTTNVATAMGVISWTL
Helix 8: LGAASGAIAGLVAITPAAGF
Helix 9: AIIIGLVAGVVGWFGVFVL
Helix 10: AFGIHGLAGIWGAIATGFFAL
Helix 11: IMVQIESVVFTIIYTAIATAVVYLIA

Query ID: C0QTA4
Helix 1: LTATALVFLMSIPGLALFY
Helix 2: TIMMVMVAFCVVSILWIVY
Helix 3: LYHYLFIFFQMTFAAITVALMAGAFI
Helix 4: AWILISVLWATVVYFPVAHWIWG
Helix 5: FAGGIVVHETCGIGALVGAILL
Helix 6: NLPLVAVGTGLLWFGWFGF
Helix 7: AISAAFVTTIAALTGGLTWMF
Helix 8: LGLFTGFIAGLATITPAA
Helix 9: FASVIIGFLGGIVCFVAVVYV
Helix 10: VFGVHGVGGMLGTILLAIL
Helix 11: IPQIVGVIAVGIYTAVATFIIF

Query ID: A9BIZ7
Helix 1: WTLLAAFLVFFMQAGFALV
Helix 2: FLVGSILYWLVGFTIMFGVGNGFIG
Helix 3: IPLNAFLIFQTVFAATAATIVS
Helix 4: YLIYSVFISAFIYPIVGHWIW
Helix 5: AGSTVVHSVGGWAALMGTMVL
Helix 6: LVLAALGVFILWFGWFGF
Helix 7: TNLAAASGGLGALTIGWFIY
Helix 8: STLNGVLAGLVGITAGTA
Helix 9: GAAIIGALSGGLVVLAIDFF
Helix 10: ISVHGVGGAFGTLMVGIFAV
Helix 11: LFLTQLKGVLAVAGWTVVTTYILF

Query ID: A0A1B0ZRL8
Helix 1: INPYIFTTLLFLIGGFLVFWMAAGF
Helix 2: IALFSIAAIMYWLIGFNLMY
Helix 3: FFFQLMFCATTASIVSGTLA
Helix 4: LWPFLIFVAILTGVIYPI
Helix 5: AGSTLVHAAGGFAALAGALIL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNMAAAAGAVAALLL
Helix 8: MTLNGALAGLVSITAGPL
Helix 9: GALWIGAVGGVIVVFVVPMLD
Helix 10: VVGAIPVHLVAGFWGTFAVPFY
Helix 11: FVTQITGFVAIGAFTFIVSGIVWLIL

Query ID: A0A366WYI9
Helix 1: YILTSLLFLMGGFLVFWMAAGF
Helix 2: MALFSLAAVMYWLVGFNLMY
Helix 3: FFFQLMFCATTASIVSGT
Helix 4: LWPFLLFVVVLTGFIYPI
Helix 5: AGSTLVHAAGGFAALAGAMVL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNMAAAAGAIAALVL
Helix 8: MVLNGALAGLVSITAEPLA
Helix 9: ALLIGAVGGVIVVFAVPFLD
Helix 10: VVGAIPVHLIAGLWGTLVVVWS
Helix 11: LSAQLIGFFSIGLFVFVVSYLFF

Query ID: V9WGS2
Helix 1: LFLVGGFLVFWMAAGFAMLEAGLV
Helix 2: NVALFSLAAIFYYLIGYNLM
Helix 3: FFFQLMFCATTASIVSGT
Helix 4: LWPFLAFVIVLTAVIYPL
Helix 5: AGSTVVHSVGGWAALTGALIL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNAAAAGGAVAALLLTQLLF
Helix 8: MVLNGALAGLVSITAEPL
Helix 9: MATVIGAVGGVIVVFVVPMLD
Helix 10: VVGAIPVHLVAGIWGTLAVVLT
Helix 11: LVTQLTGIVVIALFVAISSAVVWLIL

Query ID: A0A291FN84
Helix 1: TAWIIVATALVLFMTLPGLALFYGGLV
Helix 2: CYAIACLMSVLWLAFGYSIAFGGGTSGLWGGL
Helix 3: VLFFAFQMTFAIITPALIVGAYV
Helix 4: FVLVFSGLWMLLCYAPVVHWIW
Helix 5: AGGIVVHETAGLAALIIAVFL
Helix 6: NPGYVFIGAAMLWVGWFGF
Helix 7: AAMALTVTHISAATASLTWAL
Helix 8: VGLVTGTIAGLASITPASGF
Helix 9: ALVIGAVAGILCQEAVNVV
Helix 10: VFAVHGVGGIFGTIMIAVFGAG
Helix 11: LGGLAVVGIFTAVVTVVLV

Query ID: A0A366XFS8
Helix 1: TAWIIVATALVLFMTLPGLALFY
Helix 2: VFMHCFAIACLMSILWMVAGYSIA
Helix 3: ILFFAFQMTFAIITPALIVGAYV
Helix 4: FVLLFSGLWMLVCYAPVVHWIW
Helix 5: AGGIVVHETAGLAALIIAAFL
Helix 6: NPGFVMIGAAMLWVGWFGF
Helix 7: AAMAMTVTHISAAAASLSWA
Helix 8: LVGLVTGTIAGLASITPAS
Helix 9: IQALIIGAVAGILCQEAVNVV
Helix 10: VFAVHGIGGIFGTIMIAVFGLG
Helix 11: LGGLAIVGLFTTVVTVVLV

Query ID: V9WF46
Helix 1: TAWIIVATALVLFMTLPGLALFYGGLV
Helix 2: CYAIACLMSVLWLAFGYSIAFGGGTSGIWGGL
Helix 3: VLFFAFQMTFAIITPALIVGAYV
Helix 4: FVLVFSGLWMLLCYAPVVHWIW
Helix 5: AGGIVVHETAGLAALIIAVFL
Helix 6: NPGYVFIGAAMLWVGWFGF
Helix 7: AAMALTVTHISAATASLTWAL
Helix 8: VGLVTGTIAGLASITPASGF
Helix 9: ALVIGAVAGILCQEAVNLV
Helix 10: VFAVHGVGGIFGTIMIAVF
Helix 11: FAQLGGLAIVGIFTAVVTVVLV

Query ID: A0A291G3C0
Helix 1: LFLVGGFLVFWMAAGFAMLEAGLV
Helix 2: NVALFSLAAIFYYLIGYNLM
Helix 3: FFFQLMFCATTASIVSGT
Helix 4: LWPFLSFVIVLTAVIYPL
Helix 5: AGSTVVHSVGGWAALTGALIL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNAAAAGGAVAALLLTQLLF
Helix 8: MVLNGALAGLVSITAEPL
Helix 9: MATLIGAVGGVIVVFVVPMLD
Helix 10: VVGAIPVHLVAGIWGTLAVVLT
Helix 11: LVTQLTGIVVIALFVVISSAVVWLIL

Query ID: A0A291FRY6
Helix 1: LFLVGGFLVFWMAAGFAMLEAGLV
Helix 2: NVALFSLAAIFYYLIGYNLM
Helix 3: FFFQLMFCATTASIVSGT
Helix 4: LWPFLAFVIVLTAVIYPL
Helix 5: AGSTVVHSVGGWAALTGALIL
Helix 6: LALATLGTFILWLGWFGF
Helix 7: IFANTNAAAAGGAVAALLLTQLLF
Helix 8: MVLNGALAGLVSITAEPL
Helix 9: MATLTGAVGGVIVVFVVPMLD
Helix 10: VVGAIPVHLVAGIWGTLAVVLT
Helix 11: LVTQLTGIVVIALFVVISSAVVWLIL

Query ID: A0A0B4DUR9
Helix 1: FILNSLLFLIGGCLVFWMAAGF
Helix 2: MALFSLAAVFYWLIGYNLM
Helix 3: FFFQLMFCAATASIVSGTLA
Helix 4: LWPFLIFTIILTAVIYPF
Helix 5: AGSTVVHSVGGWAALTGALIL
Helix 6: LALATLGTFILWMGWFGF
Helix 7: IFSNTNAAAAGGAVAALILTQLLF
Helix 8: MILNGALAGLVAITAEPL
Helix 9: LATLIGAIGGVIVVFAVPFLD
Helix 10: VVGAIPVHLLCGIWGTVAVVLS
Helix 11: LLTQLTGIAVVGVFTVAASAVVWIIL

Query ID: A0A0B4DVJ9
Helix 1: ILYASGIVGAILVVVGLLLI
Helix 2: FFLGFATYYVIGFGLWAGQYYI
Helix 3: FQIFIFFLAVFAGIINILL
Helix 4: AYFITCIVAAVVSSALSWATW
Helix 5: HDFFGVGFVYLFPAGMALVF
Helix 6: YLAPSIGLCAPGLLLIFAGLPMVILSCLFFF
Helix 7: INNYAMVWAGGAITGLLIAY
Helix 8: YAYTLLGPLAGYVAGASGF
Helix 9: WQAFIVGLVAPFAAYAVY
Helix 10: KLFPLFLGCGTLGMVLLGLF
Helix 11: LVMQLAGTAVCIGTGVVTALILSFLL

Query ID: A0A0B4E6X7
Helix 1: FYYWVTVVFMFLIHVGFCMYEV
Helix 2: LMKNIMIIPLVTVTFFFFGWWIY
Helix 3: GVFWAAFLLFSWTAASIVSGAVI
Helix 4: ALWVHAVMIGSVFWIIDAAWGW
Helix 5: VIHAIAGGYALGVIMVLG
Helix 6: WMLTIGIFLIYSGFWGFYAACNIPAI
Helix 7: YLAPTSLSAITFNFLMSLSGGLMAAY
Helix 8: AFWTFSGGLAGIITASAG
Helix 9: PIQAMLVGAVGVVIVYKLH
Helix 10: AVGAVAVHGYSGIVGLIIAGFLLW
Helix 11: IGAVIMFFVLGFLPAFVIS

Query ID: A0A8J9SEP2
Helix 1: ALVFFMQAGFAMLCAGAV
Helix 2: NLLDACGAAIAFFTVGYAFA
Helix 3: YSFWLFQYAFSAASATIVAGTLA
Helix 4: AYLGYSALLTGWVYPIVAHAVWNV
Helix 5: FAGSGVVHVTGGVTALFATIIL
Helix 6: FPGHSFALQMLGTLILWFGW
Helix 7: AALAAVNTTLSGGTAGIVALFFNLWY
Helix 8: LKFAMNGCLCGLVAITGG
Helix 9: PWAAVVIGFVAGLLYNIGSRGLI
Helix 10: WGLVAVGLFASPSRLLVIYGH
Helix 11: LASQLVGLIFIVFWVMFNMLPFFVWL

Query ID: A0A8J9S765
Helix 1: TFAGAIVFLMQAGFAMVCAGAV
Helix 2: NLLDACGASLAFFSIGYALG
Helix 3: YAFWLFQYAFSAASATIVAGTLA
Helix 4: AYLCYSLMLTGWVYPVILHSIW
Helix 5: VDFAGSGVVHVTGGITALFATMVL
Helix 6: ALQMLGTFILWFGFYGFNIGSALI
Helix 7: LAGVNTTLSGSAAGIVALFLNLWYL
Helix 8: LKYAMNGAICGLVAISGG
Helix 9: PWAAVVTGAVAGVIYLLG
Helix 10: AVDAIPVHLCGGAWGILAVGLFAA
Helix 11: VLFGIQLIGLMFIMGWVMIIMLPFFVWL

Query ID: B7FTM9
Helix 1: ALVFFMQAGFAMLCAGAV
Helix 2: NLLDACGAAIAFFTVGYAFA
Helix 3: YSFWLFQYAFSAASATIVAGTLA
Helix 4: AYLGYSALLTGWVYPIVAHAVWNV
Helix 5: FAGSGVVHVTGGVTALFATIIL
Helix 6: FPGHSFALQMLGTLILWFGW
Helix 7: AALAAVNTTLSGGTAGIVALFFNLWY
Helix 8: LKFAMNGCLCGLVAITGG
Helix 9: PWAAVVIGFVAGLLYNIGSRGLI
Helix 10: WGLVAVGLFASPSRLLVIYGH
Helix 11: LASQLVGLIFIVFWVMFNMLPFFVWL

Query ID: B7G0Y1
Helix 1: LIIAGALVFFMQSGFAMLCAGCV
Helix 2: NLLDACGAALGFYVIGYALA
Helix 3: AFWFFEFAFSATSVTIVAGTL
Helix 4: VAYLCYSVFLTGFVYPVVAHSIW
Helix 5: LDFAGSGVVHVTGGTTALVATYML
Helix 6: FPGHSMALQMMGTMILWFGW
Helix 7: VAALAAVNTSLSAASGAVSALFT
Helix 8: YSFNITMAMNGALAGLVGITAG
Helix 9: NWAACCTGLVSGWVYIFGSAFLL
Helix 10: AVDAIPVHMFCGAWGLIATGLF
Helix 11: LLGLLFILGWSAILMSPFFWWL

Query ID: B7G0Y4

Helix 1: FFLIFAGALVFMMQAGFAMLCAGSV
Helix 2: NLLDACGGAIGFYTVGFGFAYG
Helix 3: YTNYAGFFFQFAFAATAATIVA
Helix 4: YLCYSLFLTGFVYPVVVRSVW
Helix 5: VDFAGSGVVHMTGGLTALIAAIVL
Helix 6: FPAHSVALQILGTFILWFGWYGF
Helix 7: ATAALCAVTTTMAAAAGCVSAMFT
Helix 8: TTYDLTMAMNGCLAGLVAVT
Helix 9: VTPWAAIIIGVVGGWVYIGM
Helix 10: FANGFWGVLATGLFANGGLMATA
Helix 11: GSLLICQLACLAWIIGWVTTIMTPFFILL

Query ID: B7FSA7
Helix 1: TFAGAIVFLMQAGFAMVCAGAV
Helix 2: NLLDACGASLAFFSIGYALG
Helix 3: YAFWLFQYAFSAASATIVAGTLA
Helix 4: AYLCYSLMLTGWVYPVILHSIW
Helix 5: VDFAGSGVVHVTGGITALFATMVL
Helix 6: ALQMLGTFILWFGFYGFNIGSALI
Helix 7: LAGVNTTLSASAAGIVALFSNLWY
Helix 8: LKYAMNGAICGLVAISGG
Helix 9: PWAAVVTGAVAGVIYLLG
Helix 10: AVDAIPVHLCGGAWGILAVGLFAA
Helix 11: VLFGIQLIGLMFIMGWVMIIMLPFFVWL

Query ID: B7FW68
Helix 1: WLMLFSGGLIFFMQTGFAMLCAGCV
Helix 2: NLLDACGAALGFFLLGYAFA
Helix 3: FWFFQFAFSATAVTIVAGTL
Helix 4: VAYLCYSIFLTGFVYPVAAHTIW
Helix 5: IDFAGSGVVHVTGGTTALVATYIL
Helix 6: FPGHSVALQLLGTFVLWFGW
Helix 7: VASRAAVNTSLSAASGAVSALMT
Helix 8: YSFNIIMAMNGALAGLVSITAA
Helix 9: NWAALCTGCIGGLIYLWG
Helix 10: AVDAIPVHMFAGGWGLLAVGLL
Helix 11: VLELVFVAGWAFGTMTPFFLFI

Query ID: A0A098S5Y7
Helix 1: WMLVSTVLVFVMHLGFSALEAGFV
Helix 2: NAMIISIGLLTYFIVGFNLMY
Helix 3: FIFQGMFAATAATIVSGAVA
Helix 4: AFLIFATLFVAISYPITGMWKWG
Helix 5: FAGSTLVHAVGGWGALAAVLLL
Helix 6: MPLAAIGVFLLWFGWFGF
Helix 7: AVSLVFVTTSLAASAGAVGAFFLSYFLF
Helix 8: MVLNGILGGLVGITAGADL
Helix 9: AIMIGGIAGLIIPVSVVFF
Helix 10: TSVHLMCGLWGTLAVGIFGA
Helix 11: YGTLAVGGFTFAFAFGLMYIL

Query ID: A0A2W5PER0
Helix 1: AWMMVSAVFVLLMIIPGLALFY
Helix 2: MLMQTATVCVIGMIAWVIYGY
Helix 3: LAFIAFQMTFAAITACLVLGG
Helix 4: FAAVVVFAVLWPLLSYYPM
Helix 5: FAGGTVVHINAGIAALVGAIILG
Helix 6: PHSLTLTLVGAGLLWFGWFGF
Helix 7: AALAVVNTFIATAAAGFSWA
Helix 8: LLGMASGLVAGLVAVTPAA
Helix 9: VGALVLGLIVSPICVFFCSFV
Helix 10: AFGIHAVGGIVGALATGILVA
Helix 11: AVLLAIVWSGVASSIVFFII

Query ID: A0A227JQV4
Helix 1: AWILTSTALVLMMTIPGLALFYGG
Helix 2: IIATVAQSFAITCLVTVIWMVA
Helix 3: WITYQMTFAIITPALICGAFA
Helix 4: AMLLFMTLWSLVVYAPICHWVWG
Helix 5: FAGGTVVHINAGVAGLMCALVL
Helix 6: APSNLVYTMIGASLLWVGWFG
Helix 7: IASAAMLNTQVATAAAALSWMI
Helix 8: LGLASGAVAGLVAITPAAGF
Helix 9: ALIIGIVAGGICYLGAVWV
Helix 10: AFGVHGIGGIAGALLTGVLA
Helix 11: VVVTMAWTAIATLVILYIC

Query ID: Q6LMI6
Helix 1: YALDTFFFLISGALVMWMAAGF
Helix 2: FCLYAIACTTYLIVGYNIMYV
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWSFLLFSVVLTAFIYPM
Helix 5: AGSGIVHMAGASAALAGVLLL
Helix 6: MPLATLGTFILWLGWFGF
Helix 7: IFLNTNAAAAAGAVAALAVC
Helix 8: ADLTMILNGALAGLVAITA
Helix 9: SPIASVIVGVVAGALVIFSIIML
Helix 10: ISVHGVCGFFGLMVVPFS
Helix 11: FGAQLLGAAVIFAWVFTASFVVWFVI

Query ID: Q1Z4I4
Helix 1: YALDTFFFLISGALVMWMAAGF
Helix 2: FCLYAIACTTYLIVGYNIMYV
Helix 3: FFFQVVFVATAMSVVSGAVA
Helix 4: LWSFLLFSVVLTAFIYPM
Helix 5: AGSGIVHMAGASAALAGVLLL
Helix 6: MPLATLGTFILWLGWFGF
Helix 7: IFLNTNAAAAAGAIASLAVC
Helix 8: ADLTMILNGALAGLVAITA
Helix 9: SPIASVIVGVVAGVLVVFSILAL
Helix 10: ISVHGVCGFFGLMVVPFS
Helix 11: FGAQLLGAAVIFAWVFVASFVVWFVI

Query ID: Q1Z695
Helix 1: LFILLGAIMVLAMHAGFAFLEV
Helix 2: LVKIIADFGFSAIAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIISGG
Helix 4: FYPMLVASFFIVAFVYPFF
Helix 5: FAGSVVVHAVGGWIALIAVAML
Helix 6: LIAFAPSNIPFLALGAWILTIGWFG
Helix 7: ISGLVAVNTLMAMVGGILTSLFV
Helix 8: FIHNGPLAGLVAVCAGSDL
Helix 9: ALVTGAIAGALFVWLFTYI
Helix 10: VWPLHGVCGAWGGIAAGIFG
Helix 11: LASQVIGTLAGIAVAVIGAFIVYGII

Query ID: Q6LKC8
Helix 1: TLFILLGAIMVLAMHAGFAFLEV
Helix 2: LVKIIADFGFSAIAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIISGGV
Helix 4: YPMLVASFFIVAFVYPFFEGIMWN
Helix 5: FAGSVVVHAVGGWIALVAVAML
Helix 6: LIAFAPSNIPFLALGAWILTIGWFG
Helix 7: ISGLVAVNTLMAMVGGILTSLFV
Helix 8: FIHNGPLAGLVAVCAGSDL
Helix 9: ALVTGAIAGALFVWLFTYI
Helix 10: VWPLHGVCGAWGGIAAGIFG
Helix 11: LASQVIGTLAGIAIAVIGAFIVYGII

Query ID: A0A2S8QG68
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALIV
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSVIVAFVAF

Query ID: A0A4V2X6C2
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWI
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGIFTA
Helix 11: IQAFSILVCVVWSVVVAFIAF

Query ID: A0A5C4RNH5
Helix 1: NAFMMICTVLVLFMTIPGIALFYGGLL
Helix 2: VMVSFALVCVLWVIYGYSLAFAPGNGFF
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSVIVAFVAF

Query ID: A0A6L9JJM6
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IRFPALLVFTVLWLTFSYL
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTTVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVIWSVVVAFIAF

Query ID: Q7N0M6
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IRFPALLVFTVLWLTFSYL
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTTVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVIWSVVVAFIAF

Query ID: C7BJG7
Helix 1: NAFMMICTALVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHIAFQGSFACITVALII
Helix 4: IRFPALLIFSVLWLTFSYL
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAVLYIGWFG
Helix 7: IAALAFLNTVVATAAAVLSWV
Helix 8: LLGACSGCIAGLVGVTPAAG
Helix 9: GALIIGLIAGFAGLWGVVIL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSIVVAFIAF

Query ID: A0A4R4K1P9
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMVQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IYFPALLIFSVLWLTFSYL
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFIGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFAGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILICVVWSVIVSFIAF

Query ID: A0A1G5PWV0
Helix 1: NAFMMICTVLVLFMTIPGIALFYGGLL
Helix 2: VMVSFALVCVLWVIYGYSLAFAPGNGFF
Helix 3: FYQLIHVAFQGSFACITVALII
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWI
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGIFTA
Helix 11: IQAFSILVCVVWSVVVAFIAF

Query ID: A0A0A0CQ38
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALIV
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSVIVAFVAF

Query ID: A0A2S8R5K1
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALIV
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSVIVAFVAF

Query ID: A0A2S8QA29
Helix 1: NAFMMICTVLVLFMTIPGIALFY
Helix 2: LMAQVMVSFALVCVLWVIYGY
Helix 3: FYQLIHVAFQGSFACITVALIV
Helix 4: IRFSALLIFSVLWLTFSYL
Helix 5: FAGGTVVHVNAAVAGLVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTIVATAAAILSWV
Helix 8: LLGACSGCIAGLVGITPAAG
Helix 9: GALIIGLIAGFTGLWGVVAL
Helix 10: VFGIHGVCGIVGCLLTGVFTA
Helix 11: IQAFSILVCVVWSVIVAFVAF

Query ID: I0ICG0
Helix 1: LWILIAAVLVFSMHLGFGCL
Helix 2: IVLIGVLTYGICGFNLMYPGF
Helix 3: FLFQAMFAATAATIVSGAVAG
Helix 4: FLIFSTLFVGLAYPIAGSWKWG
Helix 5: FAGSSIVHAFGGGGALMGALLL
Helix 6: IPLAFIGVFVLWLGWFGF
Helix 7: LVSKAMTTTAIAASSGGVAAYFV
Helix 8: MILNGILAGLVGITAGA
Helix 9: GSASIVGLIAGVIVVFSVYFF
Helix 10: ISVHGVCGLWGTIAVGIFGVADYL
Helix 11: IVVQVIGTLTYFLFACIVAGILFGIL

Query ID: H3GCZ7
Helix 1: AWMLMSSALVMLMTPGVAFFYAGLAG
Helix 2: FVSMALVSIQFWAFGYSACFSSDGIFAWA
Helix 3: ILFAFFQTQFAMITPALLSGGIVG
Helix 4: YLLFVLLWTSLVYDPLAHWMW
Helix 5: GALDFAGGTVIHVSSGFGALVAAVVVG
Helix 6: HNVPLVMIGATLLWFGWFGF
Helix 7: GAANGIAAIAAINTHLAPASGFLT
Helix 8: FDPCGAISGAVAGLVAIT
Helix 9: VYPWAAVIFGVVGAATGFSAVHL
Helix 10: SFGIHGCSGFIGGLLTGLFA
Helix 11: LLHQFVSQCVAAGYSAAVTFIILMVL

Query ID: H3GCZ5

Helix 1: AWMLTASALVMVMTPGVAFFYAGL
Helix 2: MSFVSMALVSIQFWAFGYSAAFGSHGVF
Helix 3: IPHLLFAFFQTQFAMITPALL
Helix 4: TFLLFILLWTSLVYDPLAHWMW
Helix 5: FAGGTVIHISSGFGALAAALMVG
Helix 6: HNVPLVMIGVTLLWFGWFGF
Helix 7: AAIAAINTHLAASSGFLTWVGL
Helix 8: KFDPCGAASGAVAGLVAIT
Helix 9: VYPWASVIFGVVGAATGFSAI
Helix 10: LDSFAIHGCVGIMGGLLTGLFA
Helix 11: FVHQLVSQCVAAAYSFVVTMIILYLL

Query ID: H3G9J8
Helix 1: HVMIYIGFGFLMTFLRKY
Helix 2: LNFLIAVLALEWGIIAVTMAHQI
Helix 3: IPTMINGDFAAGAVLISFGAVLG
Helix 4: LVWMTFLEIIFYAFNEYIVL
Helix 5: MVIHSFGAFFGLALTIQLGAP
Helix 6: YHSDVFAMIGTLFLWMYW
Helix 7: MNTVLSIAASCASAFVASKL
Helix 8: IQNATLAGGVAMGTSCNLAI
Helix 9: ITVGLVVGIASVFGFSFVSPRL
Helix 10: ILNLHGMPGVVGGLAGAIITFSA
Helix 11: WYQLLAIVSSVGIGTISGFLVGFFL

Query ID: D2R355
Helix 1: AWMLTSAALVLFMTAPGLAMFY
Helix 2: VMMQCIFLMGLMTVIWALY
Helix 3: MLFQGMFFIITPALICGAFA
Helix 4: TMVVFSILWGTILYCPLCHMVW
Helix 5: FAGGTVVHISSGVSALVCALVIG
Helix 6: PHNLTYTTLGAAMLWVGWFGF
Helix 7: TSSAFAVTHFSAAAGTLSWA
Helix 8: VLGACSGAVAGLVCITPAA
Helix 9: MAALAMGFIAGIVCFLACTKL
Helix 10: AFGVHGVGGTLGAILTGVFATVNVA
Helix 11: VLVGQIVATLVTWVVSAIVTFVLLKVL

Query ID: D2R647
Helix 1: FILFICAVLVLFMQAGFALV
Helix 2: MCIGAVLYFICGYGIMYPG
Helix 3: FLFQAAFAATAATIVSGSVAG
Helix 4: YLIYTVIISAVIYPISGSWKWG
Helix 5: FAGSVVVHSVGGLAGLAGAIAL
Helix 6: IPYVALGVFILVIGWFGF
Helix 7: VAVNTLLAGCFGGVVSMIFSWGLF
Helix 8: MALNGTLAGLVAVTANCHIIT
Helix 9: IISGVAGVLVVLGIVLL
Helix 10: FPVHGICGMWAGVATGIFG
Helix 11: IVIQVIGTAVIGVWALGTSLVMFFA

Query ID: A0A2Z6CF98
query A0A2Z6CF98 has 12, using last 11 helices
Helix 1: NVAWVLVASILVIFMNAGF
Helix 2: LIVFALATLIFWAFGFSFMF
Helix 3: VSLYFLFQVAFAGTAATIVSGA
Helix 4: FIAFLLFSLLLVGIAYPI
Helix 5: FAGTTAVHSVGGWAALMGAAFL
Helix 6: MSIATLGCLILWVCWFGF
Helix 7: ISYIAVTTNLAAAAGAVTASATSWL
Helix 8: LSMIINGVLAGLVAITAS
Helix 9: YLSAVIIGAIAGVLVVYSVGFF
Helix 10: TSVHLVCGIFGTLAAGIFGGA
Helix 11: ILGILAVGGFTVALSTIFWLAL

Query ID: A0A073CP02
query A0A073CP02 has 12, using last 11 helices
Helix 1: NVAWVLVASILVIFMNAGF
Helix 2: LIVFALATLIFWAFGFSFMF
Helix 3: VSLYFLFQVAFAGTAATIVSGA
Helix 4: FIAFLLFSLLLVGIAYPI
Helix 5: FAGSTAVHSVGGWAALMGAAFL
Helix 6: MSIATLGCLILWVCWFGF
Helix 7: ISYIAVTTNLAAAAGAVTASATSWL
Helix 8: LSMIINGVLAGLVAITAS
Helix 9: YLSAVIIGAIAGVLVVYSVGFF
Helix 10: TSVHLVCGIFGTLAAGIFGGA
Helix 11: ILGILAVGGFTVALSTIFWLAL

Query ID: A0A1J1JH03
query A0A1J1JH03 has 12, using last 11 helices
Helix 1: NVAWVLVASILVIFMNAGF
Helix 2: LIVFALATLIFWAFGFSFMF
Helix 3: VSLYFLFQVAFAGTAATIVSGA
Helix 4: FIAFLLFSLLLVGIAYPI
Helix 5: FAGTTAVHSVGGWAALMGAAFL
Helix 6: MSIATLGCLILWVCWFGF
Helix 7: ISYIAVTTNLAAAAGAVTASATSWL
Helix 8: LSMIINGVLAGLVAITAS
Helix 9: YLSAVIIGAIAGVLVVYSVGFF
Helix 10: TSVHLVCGIFGTLAAGIFGGA
Helix 11: ILGILAVGGFTVALSTIFWLAL

Query ID: A0A4V0XUI3
query A0A4V0XUI3 has 12, using last 11 helices
Helix 1: NVAWVLVASILVIFMNAGF
Helix 2: LIVFALATLIFWAFGFSFMF
Helix 3: VSLYFLFQVAFAGTAATIVSGA
Helix 4: FIAFLLFSLLLVGIAYPI
Helix 5: FAGSTAVHSVGGWAALMGAAFL
Helix 6: MSIATLGCLILWVCWFGF
Helix 7: ISYIAVTTNLAAAAGAVTASATSWL
Helix 8: LSMIINGVLAGLVSITAS
Helix 9: YLQAVIIGAIAGVLVVYSVGFF
Helix 10: TSVHLVCGIFGTLAAGIFGGA
Helix 11: ILGILAVGGFTVALSTIFWLAL

Query ID: A0A1C7EL50
Helix 1: WVMLGAMLVFFMHAGFAMV
Helix 2: VSLGSILYFIVGYALMFG
Helix 3: IGFFVFQAVFAATCATIISGAVA
Helix 4: AYILLTIAMTAVIYPIVGHWVW
Helix 5: AQIGFIDFAGSTVVHLTGAVAALVAAW
Helix 6: SLPLGALGVFILWLGWFGF
Helix 7: LVPIVIANTLLAASAGIIATASY
Helix 8: LTMNGALAGLVGITAGAA
Helix 9: GAIVIGLLAGVIMTEAIRLL
Helix 10: AISVHGIAGIWGTLAIGLF
Helix 11: VGVFAVVAWASISTGLVLLAI

Query ID: E7RJZ0
Helix 1: WVMLGAMLVFFMHAGFAMV
Helix 2: VSLGSILYFIVGYALMFG
Helix 3: IGFFVFQAVFAATCATIISGAVA
Helix 4: AYILLTIAMTAVIYPIVGHWVW
Helix 5: AQIGFIDFAGSTVVHLTGAVAALIAAW
Helix 6: SLPLGALGVFILWLGWFGF
Helix 7: LVPIVIANTLLAASAGIIATASY
Helix 8: LTMNGALAGLVGITAGAA
Helix 9: GAIAIGLLAGVIMTEAIRLL
Helix 10: AISVHGIAGIWGTLAIGLF
Helix 11: VGVFAVIAWASISTGLVLLAI

Query ID: A6GJF5
Helix 1: LVNNVWMLVATVLVFAMHLGF
Helix 2: LCVVAIGLLTYAGVGFSLMY
Helix 3: FLFQGMFAATAATIVSGAVA
Helix 4: AFLIFSTLFVALVYPIVGMWQWG
Helix 5: FAGSTVVHGVGGWGALAGAIVL
Helix 6: MPLATVGTFLLWFGWFGF
Helix 7: AISRVLVVTALGGAGGIVTAAAT
Helix 8: MALNGALGGLVAVTAGADVI
Helix 9: VLLGLSAGTVVVVAVMLF
Helix 10: ISVHLVCGAWGTVAVGVLV
Helix 11: VGQLVGVGAVGAFSFASAWGLFWAL

Query ID: A1VIG8
Helix 1: AWMMVSTILVILMVVPGLALFY
Helix 2: VLMQVMVTFSLIVVLWFIY
Helix 3: IVFAAFQATFAGITCTLIVGAFA
Helix 4: AVLAFMVIWFTFSYAPMAHMVWFWM
Helix 5: YIWQTGALDFAGGTVVHINAAVAGLVGAFMV
Helix 6: APHSLTLTMVGASLLWVGWFG
Helix 7: FAALAFINTLGATAAAVLAWCV
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: AGGLAIGFIAGFACLWGVHGL
Helix 10: VFGVHGVGGIVGALLTGVF
Helix 11: VWIQAKAVLITIVWSGVVSLVAY

Query ID: A1VIM5
Helix 1: AWMMTSTALVLLMTLPGIALFY
Helix 2: VMACVVGTCAIVSLLWFAVGYSIA
Helix 3: VYSMFQLSFAIITASLVVGAFV
Helix 4: ATLIFMALWTVVVYAPIAHWVW
Helix 5: VHINAGIAGLVCAYALG
Helix 6: PFNLGLTMAGAGMLWVGWFGF
Helix 7: AGLAMTVTHIAASAGALSWM
Helix 8: LLGVCSGLVAGLVAITPGAGY
Helix 9: AVIFGLVAGVACYWGATGL
Helix 10: VFGVHGIGGIVGSLLTGVFA
Helix 11: WIQFVGAASVMLYSLVMTGLLLWI

Query ID: A4T0A4
Helix 1: WMMVCTALVLLMTLPGLALFYGG
Helix 2: ILSICMQCFMVFSMITVLWAIY
Helix 3: YVFMAFQAVFATITCCLIIGSFA
Helix 4: AILVFMIIWFTFSYLPIAHMVWFW
Helix 5: FAGGTVVHINAAVAGLVGSFVIG
Helix 6: PHNLVYVMTGAALLWFGWFGF
Helix 7: AALAFVNTYLATAAAVLGWSV
Helix 8: LGAASGCVAGLVAITPAAGFA
Helix 9: IIIGLIAGVVCLWGVTGL
Helix 10: VFGVHGVGGITGALLTGVFA
Helix 11: LWIQAQGVITTVIWSGVVSFVAF

Query ID: B9IGE2
Helix 1: AWQMIASILVATQSMPGLVILYA
Helix 2: AFMALYAFAAVLICWVLLCYRMA
Helix 3: VYFQFTFAAITLILLAGSVL
Helix 4: VPLWLIFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTAAYWVG
Helix 6: PNNVLLMLAGAGLLWMGWSGF
Helix 7: ASMAMLNTNVCAATSLLVWT
Helix 8: VIGAVQGMMTGLVCITPGA
Helix 9: WAAIVMGILSGSIPWVSMMILH
Helix 10: TLGVFHTHAVAGLLGGLLTGLLA
Helix 11: MVAALFVIGWNIVSTTLILLFIRLFI

Query ID: B9HCZ0
Helix 1: AWQMTASTLVALQSMPGLVILYA
Helix 2: AFMALYAFAAVLICWVLLGYRMA
Helix 3: VYFQFTFAAITLILLAGSVL
Helix 4: VPLWLIFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTAAYWVG
Helix 6: PNNVLLMLAGAGLLWMGWSGF
Helix 7: ASIAVLNTNVCAATSLLVWT
Helix 8: VIGAVQGMMTGLVCITPGA
Helix 9: WAAIVMGILSGSIPWVSMMILH
Helix 10: TLGVFHTHAVAGLLGGLLTGLLA
Helix 11: VVAALFVIGWNVVSTTIILLFIRLFI

Query ID: A0A2K2AEV5
Helix 1: AWQLTATTMVCLQSVPGLVILYG
Helix 2: WAVNSAFMAFYAFAAVLVCWVLL
Helix 3: FVFYQFAFAAITVILLAGSLL
Helix 4: AWMLFVPLWLFFSYTVGASTIWG
Helix 5: AGGYVIHLSSGVAGFTAAYWVG
Helix 6: PNNIIHMLGGAGFLWLGWTGF
Helix 7: FAAGLVASLAIFNTHLCTATSLLVWV
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAALLMGVMSGSIPWYTMMVLH
Helix 10: TLAVFHTHAVAGLLGGILSGIFA
Helix 11: IQLLGAAFITAWNGGATSLICILI

Query ID: B9GHA5
Helix 1: WQMISATLVGLQSMPGLVILYG
Helix 2: AFMALYAFAAVVLCWVVWAY
Helix 3: MVWFQCVFAAITLILLAGSVL
Helix 4: VPLWLTFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTTAFWVGP
Helix 6: NNVLLMLAGAGLLWMGWAGF
Helix 7: SSMAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIIMGILSGSVPWFTMMIV
Helix 10: AVAGLLGGVLTGLFAEPQLCALFLPV
Helix 11: LVGAAFIIGWNVVVTSIICVVINLVI

Query ID: U5FE59
Helix 1: AWQMISATLVGLQSVPGLVILYG
Helix 2: AFMAFYAFAAVVICWVVWAY
Helix 3: MVWFQCVFAAITLILLAGSVL
Helix 4: VPLWLTFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTTAFWVGP
Helix 6: NNVLLMLAGAGLLWMGWAGF
Helix 7: SSMAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIIMGILSGSVPWFTMMIV
Helix 10: AVAGLLGGVLTGLFAEPELCALFLPV
Helix 11: LVGGAFIIGWNVVVTSIICVVINFVI

Query ID: A0A2K1RA77
Helix 1: AWQMISATLVGLQSVPGLVILYG
Helix 2: AFMAFYAFAAVVICWVVWAY
Helix 3: MVWFQCVFAAITLILLAGSVL
Helix 4: VPLWLTFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTTAFWVGP
Helix 6: NNVLLMLAGAGLLWMGWAGF
Helix 7: SSMAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIIMGILSGSVPWFTMMIV
Helix 10: AVAGLLGGVLTGLFAEPELCALFLPV
Helix 11: LVGGAFIIGWNVVVTSIICVVINFVI

Query ID: A0A2K1RA81
Helix 1: AWQMISATLVGLQSVPGLVILYG
Helix 2: AFMAFYAFAAVVICWVVWAY
Helix 3: MVWFQCVFAAITLILLAGSVL
Helix 4: VPLWLTFSYTVGAFSLWGGGFL
Helix 5: YVIHLSSGIAGLTTAFWVGP
Helix 6: NNVLLMLAGAGLLWMGWAGF
Helix 7: SSMAVLNTNICAATSLLVWT
Helix 8: VIGAVQGMITGLVCITPGA
Helix 9: WAAIIMGILSGSVPWFTMMIV
Helix 10: AVAGLLGGVLTGLFAEPELCALFLPV
Helix 11: LVGGAFIIGWNVVVTSIICVVINFVI

Query ID: A0A2K1WV98
Helix 1: AWQLTAATLVGLQSIPGLMILY
Helix 2: SAFMVLYAFACVMFCWVTWGY
Helix 3: VYFQSVFAAITLILIAGAVL
Helix 4: FYAWMIFVPLWLTFSYTFTAFS
Helix 5: YVIHLSSGVAGYTAAYWVG
Helix 6: PNNILLMLFGAGLLWMGWTGF
Helix 7: ASLAVLNTHLCTATSLLTWVALDII
Helix 8: VIGAVQGMITGLVCITPAA
Helix 9: WAATIMGLCSGSIPWITMMVIH
Helix 10: TMAVLHTHAIAGSLGGILTGLFA
Helix 11: FIGILFVVFVNVLTTSIICILIRLVV

Query ID: A0A8H7U3I1

Helix 1: IAFIAICGILVSFMVPGVAFLY
Helix 2: LIWAVAASNAVVIFQWFFW
Helix 3: LLYSFYQMEFACVTVAILMGAL
Helix 4: VPAMIFAFIWMTIVYCPLACWAWA
Helix 5: GGGPVEIGSGVSGLAYSWVLG
Helix 6: PHNVSQVCMGTFMLWFGWLGF
Helix 7: AVLAIWNSMIAAAMAGLVWCLL
Helix 8: KVSMVGFCSGTIAGLVAAT
Helix 9: IPQWASLIMGIVVGVVANYAT
Helix 10: LDLYAEHAIGGIVGLLFNALF
Helix 11: LYIQFAYVCAVVGYSFVVTALLA

Query ID: A0A8H7P8U1
Helix 1: IAWVLCSTALVWIMIPGVGFFY
Helix 2: MIWMCMMTIAVVSFQGTRCSFSLAF
Helix 3: VPSIAFCVFQLMFAAITPMLAI
Helix 4: VMVFVFIWSTIVYDPIACWTWN
Helix 5: FILGGLDFAGGTPVHISSGTAALAI
Helix 6: NTTYVVLGTVFLWFGWFGF
Helix 7: AVQACIVTNLAASVGGLTWMLW
Helix 8: KWSTVGFCSGAIAGLVAI
Helix 9: FVGSPAAVLFGFMAGTVCNFA
Helix 10: CLDIFASHAIGGVVGNILTGLFA
Helix 11: GMSYSFVMTTIILWVMHYI

Query ID: A0A1X6N3Q5
Helix 1: IAWVLCSTALVWIMIPGVGFFY
Helix 2: MIWMCMMTIAVVSFQWFFW
Helix 3: VPSIAFCVFQLMFAAITPMLAI
Helix 4: VMVFVFIWSTIVYDPIACWTWN
Helix 5: FILGGLDFAGGTPVHISSGTAALAI
Helix 6: NTTYVVLGTVFLWFGWFGF
Helix 7: AVQACIVTNLAASVGGLTWML
Helix 8: VGFCSGAIAGLVAITPGSGFV
Helix 9: VLFGFMAGTVCNFATQLKFYL
Helix 10: HAIGGVVGNILTGLFAQASVAGF
Helix 11: YQLADSVSGMSYSFVMTTIILWV

Query ID: A0A0G3CP57
Helix 1: NGFMMISTALVLFMCIPGIALFY
Helix 2: LLTQVMATFSLVSVLWVIYGY
Helix 3: LIHVAFQGSFACITVGLIVGGFA
Helix 4: AVMLFVFIWFTLAYLPMAHMVWG
Helix 5: FAGGTVVHINAAIAALVGAYMLG
Helix 6: PHNLPMVFIGTAILYVGWFG
Helix 7: IAALAFINTLSATAGAVLSWL
Helix 8: LLGACSGCIAGLVAITPAAG
Helix 9: GALILGIIAGVAGLWGVVVL
Helix 10: VFGVHGVCGIVGCIGTGIL
Helix 11: VGIQAASIGVCLLWSGLVAYVAY

Query ID: A0A660CH85
Helix 1: AWLLTSAALVLLMTPGLAFFY
Helix 2: MLMMCFGAMGLIGVLWVVY
Helix 3: VAFQAMFAIITVALIAGAVA
Helix 4: AWMLFGGLWATLVYFPVAHWVW
Helix 5: VHTNAGAAALGLVLVLGKRA
Helix 6: LPYVMLGAGLLWFGWFGF
Helix 7: AGIAFINTVTATCAAMLGWLL
Helix 8: LGAASGVVAGLVAITPA
Helix 9: TWGALAIGAIAGIACAAAVGL
Helix 10: VVGVHLVGGLIGTVMLGFVATASVVP
Helix 11: QVLSVVVVMIYSGVVAAILGLIV

Query ID: A2C095
query A2C095 has 12, using last 11 helices
Helix 1: LWLFIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWVI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFSIVLTAFIYPIAGSWQWN
Helix 5: FAGSSIVHSVGGWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VAYVAVTTTLAAAGGAIAATVLSTI
Helix 8: LTMIINGILAGLVSITAG
Helix 9: FAGSWLAGAVGGLIVVVAVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGV
Helix 11: QFFIQALGAAAYGIWTVVTCWIAW

Query ID: A2BP62
query A2BP62 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A8I1X2A6
query A0A8I1X2A6 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0A2BBY0
Helix 1: WLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0A1ZMZ9
Helix 1: WLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWFV
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFALVLTAFIYPVAGSW
Helix 5: AGSSIVHSVGAWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VPYVAVTTTLAAAGGGIAATIL
Helix 8: MIINGILAGLVSITAGCGNLT
Helix 9: VAGFIGGIIVVFSVAALDA
Helix 10: VGAFSVHGVCGVWGTIVIGLWGY
Helix 11: LGIQALGAGAYAIWSIITCWIAWSII

Query ID: Q7VDS3
query Q7VDS3 has 12, using last 11 helices
Helix 1: LWLFIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWFI
Helix 3: FLFQAAFAGTAATIVSGLVA
Helix 4: FGEFVVFSLVLTAFIYPIA
Helix 5: AGSSIVHSVGGWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VAYVAVTTTLAAAGGAIAATLL
Helix 8: MIINGILAGLVSITAGCGNMT
Helix 9: LAGFVGGLIVVFAVSAL
Helix 10: FSVHGVCGVWGTVVIGLWGV
Helix 11: TLLIQALGAGAYAIWTVVTCWLAWTVI

Query ID: Q7V4T8
query Q7V4T8 has 12, using last 11 helices
Helix 1: LWLLVATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVSSYWFI
Helix 3: FLFQAAFAGTAATIVSGLVAE
Helix 4: FVVFSLVLTGFIYPIAGSW
Helix 5: FAGSSIVHSVGAWAGLVGAMLL
Helix 6: MSIATLGALILWIGWYGF
Helix 7: VPYVAVTTTLAAAGGAIGATIISTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LVGAWVAGLIGGFIVVFSVSAL
Helix 10: FSVHGICGIWGTLVIGLWGF
Helix 11: LWAQFVGCAAYAIWTVVTCWIAWSVI

Query ID: A2CCK1
query A2CCK1 has 12, using last 11 helices
Helix 1: FLANNLWLLIAAVLVIFMNAGF
Helix 2: LFVFTLAVTAYWFIGFQIMY
Helix 3: FLFQAAFAGTAATIVSGLVA
Helix 4: FGEFVVFSLILTAFIYPIA
Helix 5: AGSTLVHSVGAWAGLVGAIAL
Helix 6: MAIATLGCLILWIGWYGF
Helix 7: VPYIAVTTTLAAAGGAIGATIISTL
Helix 8: LTMIINGILAGLVSITAGC
Helix 9: WAAWLIGLIGGVIVVFSVAFI
Helix 10: FSVHGTCGIWGTLAVGLFNT
Helix 11: CISYAVFIVVSCWIAWSVIGALF

Query ID: A3PAY4
query A3PAY4 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A2BUP4
query A2BUP4 has 12, using last 11 helices
Helix 1: FLANNLWLLIATILVIFMNAGF
Helix 2: LFVFALAVTSYWFIGYSLMY
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAV
Helix 10: FSVHGVCGVWGTLVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A8G2S3
query A8G2S3 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTLVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: B9NZY2
query B9NZY2 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTIVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A9BDN5
Helix 1: SLIWLACVPLALFGLGLF
Helix 2: LWIMVAAVLVIFMNAGFAMVE
Helix 3: ILAKNLIVFTLAVSAYWFI
Helix 4: FLFQAAFAGTAATIVSGVVA
Helix 5: FGEFVVFSLVLTAVIYPIA
Helix 6: AGSSIVHSVGAWAGLIGAIAL
Helix 7: MAIATLGALILWIGWYGF
Helix 8: VPYVAVTTTLGAAGGGIAATLL
Helix 9: WSSWLVGAIGGLLVVWSVAFV
Helix 10: VSVHGTCGVWGTLAVGLFYG
Helix 11: AASYAIFTILTCWIAWSIIGGFFGGI

Query ID: Q7V330
query Q7V330 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALILWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTLVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSII

Query ID: Q9REX3
query Q9REX3 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALILWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTLVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSII

Query ID: A0A318QZ80
query A0A318QZ80 has 12, using last 11 helices
Helix 1: LWLFIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWVI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFSIVLTAFIYPIAGSWQWN
Helix 5: FAGSSIVHSVGGWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VAYVAVTTTLAAAGGAIAATVLSTI
Helix 8: LTMIINGILAGLVSITAG
Helix 9: FAGSWLAGAVGGLIVVVAVAAL
Helix 10: FSVHGVCGVWGTIVIGLWGV
Helix 11: QFFIQALGAAAYGIWTVVTCWIAW

Query ID: A0A9D9G322

query A0A9D9G322 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A9D9C0X8
query A0A9D9C0X8 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: Q46HB1
query Q46HB1 has 12, using last 11 helices
Helix 1: LWLFIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWVI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFSIVLTAFIYPIAGSWQWN
Helix 5: FAGSSIVHSVGGWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VAYVAVTTTLAAAGGAIAATVLSTI
Helix 8: LTMIINGILAGLVSITAG
Helix 9: FAGSWLAGAVGGLIVVVAVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGV
Helix 11: QFFIQALGAAAYGIWTVVTCWIAW

Query ID: A0A0A1ZJU5
query A0A0A1ZJU5 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0A2B651
Helix 1: WLLVATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTSYWFI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAVVLTAFIYPIAGSW
Helix 5: IVHSVGAWAGLVGAMLLGPRIG
Helix 6: GHNMAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LAGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGTA
Helix 11: LVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0A2C6L1
query A0A0A2C6L1 has 12, using last 11 helices
Helix 1: LWLFIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWVI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFSVVLTAFIYPIAGSWQWN
Helix 5: FAGSSIVHSVGGWAGLVGAMLL
Helix 6: MAIATLGALILWIGWYGF
Helix 7: VAYVAVTTTLAAAGGAIAATVLSTI
Helix 8: LTMIINGILAGLVSITAG
Helix 9: FAGSWLAGAVGGLIVVVAVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGV
Helix 11: QFFIQALGAAAYGIWTVVTCWIAW

Query ID: Q31CR9
query Q31CR9 has 12, using last 11 helices
Helix 1: FLANNLWLFVATILVIFMNAGF
Helix 2: LFVFALAVTSYWFIGFGIMYYG
Helix 3: FLFQAAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSW
Helix 5: FIDFAGSSIVHSVGAWAGLVGAMLL
Helix 6: MAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LVGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTIVIGLWGT
Helix 11: LLVQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0A2A5X1
query A0A0A2A5X1 has 12, using last 11 helices
Helix 1: LWLLIATILVIFMNAGFAMVE
Helix 2: ILAKNLFVFALAVTAYWVI
Helix 3: FLFQSAFAGTAATIVSGLVAE
Helix 4: FVVFAIVLTAFIYPIAGSWQWN
Helix 5: FAGSSIVHSVGAWAGLVGAMLL
Helix 6: MAIATLGALVLWIGWYGF
Helix 7: VPYVAVTTTLAAAAGAIGATIVSTL
Helix 8: LTMIINGILAGLVSITAG
Helix 9: LVGAWFAGLVGGIIVVFSVAAL
Helix 10: FSVHGVCGVWGTVVIGLWGT
Helix 11: LLIQALGAAAYAIWTLVTCWIAWSVI

Query ID: A0A0M2PZN7
Helix 1: FQWAWVACVPLTALIVIGWGLA
Helix 2: MYPIFLLNNLWVFVGAILVIFMNAGF
Helix 3: LIVFTLATAAYWFIGYSLM
Helix 4: FLFQAAFAGTSATIVSGAVA
Helix 5: AFLIFSLVLTGFIYPIAGGWQWN
Helix 6: FAGSTLVHSVGGWAALTGAFIL
Helix 7: LSIATLGCLILWIGWFGF
Helix 8: VPYIAVTTNLAGAAGGIAATATSWFTA
Helix 9: ILAGLVGVTAGCSVVGMGGAFIIGFIAGILVVF
Helix 10: HLVNGVWGTLAVGLFANG
Helix 11: FIGVFAYGIWTLITTAGLWYAL

Query ID: A0A5M4AWD2
Helix 1: VWVLVAAVLVMFMQPGFAMV
Helix 2: FSVGSLAFWLVGFSLMFGGDIGGLI
Helix 3: ILFFQTVFAATAATIVSGAVA
Helix 4: TYLIFSIVITLFIYPVSGHWVWG
Helix 5: FAGSTVVHSVGAWLGLVGAIMVG
Helix 6: AIPGHNLTFGALGVFILWFGW
Helix 7: ISLIFITTNLAAAAGALSSMFV
Helix 8: FPSLSLTLNGALAGLVAITAG
Helix 9: PGGAIAIGAIAGIILVFGVEFI
Helix 10: AVSVHGLGGAAGTLMVGLF
Helix 11: AHLLGVQAIGVLAVMAWAMGTGFILF

Query ID: A0A5M4B0G1
Helix 1: MILSTSLVMLMTPGLAFFYGGL
Helix 2: LGIMMQTFVSLGITTIMWISV
Helix 3: VYIFIAYQMMFAIITPALITGAFV
Helix 4: AYLVFLVLWQLFVYYPFVHMIWG
Helix 5: FAGGVVVHATAGFAALASVFYV
Helix 6: SIPLVAIGTGLLWFGWYGF
Helix 7: TTLAFLNTDVAASFATITWLIIEWV
Helix 8: FVGLLTGAVAGMATITPA
Helix 9: LWAAIVIGIAAGSLCYVAV
Helix 10: LDVWGVHGMGGVIGTISLGIFASA
Helix 11: VVAVLIGAVYAFVFTYLMLAVINLF

Query ID: A0A5M4ATH9
query A0A5M4ATH9 has 12, using last 11 helices
Helix 1: VAWMLTSTALVLLMTPGLAFFYG
Helix 2: ILQSFMAMGLISIIWIVVGFSLAF
Helix 3: IPFALFAIFQLKFAIITPALI
Helix 4: AYMLFISLFTIFIYAPLAHW
Helix 5: TVVHMSAGFAALAGAMFLG
Helix 6: ANIPFVMLGAGMLWFGWFGF
Helix 7: AVLALVNTNTASAAAMLAWIF
Helix 8: LGAAIGLVVGLVAITPAAG
Helix 9: ASIFIGVAAAVVSNYAITL
Helix 10: VFPAHGMGGIVGMILTGVFAR
Helix 11: FFYHLLALVVVSVFTFGGSYLLY

Query ID: A0A5M4AUM9
Helix 1: LTAFMIIATSLVMLMTPGLAFFY
Helix 2: IMMQSFVSLGITSLLWISI
Helix 3: FIFIAYQMMFAIITPALITGAFI
Helix 4: SYIIFLIFWQIFVYYPFVHMIWG
Helix 5: FAGGITVHATAGFAALASVLFVG
Helix 6: IPLVAIGTALLWFGWYGF
Helix 7: TAQAFLNTDIAASASAVTWLI
Helix 8: FIGLMTGAVAGLATITPAAG
Helix 9: AALFFGLLAGVVCYLAVKFV
Helix 10: WGVHGVGGVLGTLLLGFFGSLAV
Helix 11: QLTAIILASAWGFVFTLAMLKII

Query ID: A0A1H7CU41
Helix 1: WVLISAALVFVMTPGLAFFYG
Helix 2: IMQSFFIVALISVEWILIGYTMA
Helix 3: LAFVAFQCMFAVITPALITGAFA
Helix 4: AFVMFILLWAIFIYNPMAHWVWG
Helix 5: FAGGLVIHILSGVSGLTICLML
Helix 6: LPHHLPMTVLGASLLWFGWFGF
Helix 7: LGANALAANAFVTTQAAAAAATLSWV
Helix 8: ILGAVSGCIAGLVAITPAA
Helix 9: LPAVIIGLVGGVVCYFAVAIV
Helix 10: AFGVHGIGGTWGAIATGLWA
Helix 11: IVAQLISIVVAYVLAIVGSFVLI

Query ID: A0A1G7VM92
Helix 1: AWVLVSAALVILMSIPGLALFY
Helix 2: VLMQVFVTFSLISVLWVVYGYS
Helix 3: LAYVVFQGAFAAITCGLIVGAFA
Helix 4: AVLVFMVLWFTFSYLPMAHMVWYWA
Helix 5: FAGGTVVHINAAVAGLVGAYLM
Helix 6: APHGLTFTMIGASLLWFGWFGF
Helix 7: AALAMVNTWVATAAAAMSWML
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: VGAIVIGLLAGVVCLWGVNGL
Helix 10: VFGVHGVGGILGSILTGVFCAPSLGG
Helix 11: VISQLWGVGTAIVWSGIVSVVAF

Query ID: A0A1G7UZX2
Helix 1: FILLGGIMVLAMHSGFAFLELGTV
Helix 2: ILVDFSVSTIAYFFIGFSVAYGV
Helix 3: FFFLLTFAAAIPAIISGGVA
Helix 4: LIATFVIVGLIYPFFEGIAWN
Helix 5: FAGSVVVHAMGGWIALPAVILLGA
Helix 6: FLALGAWILTVGWFGFNVMSA
Helix 7: ISGLVALNSLMAMVGGTLVALIL
Helix 8: FVHNGPLAGLVAVCAGSDV
Helix 9: ALAVGGVAGALFVVMFTLT
Helix 10: VWPLHGLCGAWGGIAAGIFG
Helix 11: LVAQVIMTVMAIGVALIGSTIVYGSL

Query ID: B4S394
Helix 1: TAWMLTATTLVLLMVPGLAMFYGGLV
Helix 2: SFAAMVVIGVLWPTIGYALSFGSGILGGLVGWNP
Helix 3: YVFAMFQGKFAIIAPALIAGAFA
Helix 4: GYVVFIALWSIAVYSPICHWVWA
Helix 5: TVVHISSGVSALVAALFLGA
Helix 6: NNLVMTLIGAGLLWVGWFGF
Helix 7: TGRALTVTQIAAAAGASAWML
Helix 8: LGVVSGILAGLVAITPAAG
Helix 9: GAIIIGAVASLFCFLAIQV
Helix 10: AFGIHGVGGIVGALVLTFFI
Helix 11: FGIQAAAVGVTIVYAAVMSVILLFLV

Query ID: A0A0P6VSR8
Helix 1: TWMLISTILVILMTLPGLALFY
Helix 2: VLMQVLCGFSLIAILWVVYGY
Helix 3: IVFVIFQLTFAAITPALIIGAFA
Helix 4: AVMVFLVLWFTFAYLPMAHMVWFWA
Helix 5: FAGGTVVHINAGVAGLVCAIMA
Helix 6: APHNLVLTMIGASLLWVGWFGF
Helix 7: TALAVLNTIVATAAAALAWSL
Helix 8: LGGASGAVAGLVAVTPAAGF
Helix 9: AIVIGLVAGIVCFWAVTSL
Helix 10: VFGVHGIGGIVGAILTGIFV
Helix 11: LWGVGVSVVWTAVVSIVALLLI

Query ID: A0A101HKN9
Helix 1: TFWVLFAAVLVFFMQTGFALV
Helix 2: FCMGTIAFWVIGYGIMYGTGSGFF
Helix 3: SAFFIFQLVFAATAATIVSGAMA
Helix 4: AYLMYSVAITAIIYPVSGHWVW
Helix 5: VVHSMGGWLAFIGAAFLGP
Helix 6: AIPGHSLTLAALGVFILWLGW
Helix 7: IFVTTNGAAAAGGIATLLITWI
Helix 8: FSMTLNGVLAGLVAITAG
Helix 9: PGGAVVIGFLAGILVVFSVEFL
Helix 10: AVSVHGVCGAFGTLMVGLFSA
Helix 11: FIGVLAIAAWAGVTGTVLFSLL

Query ID: A0A7U1H267
Helix 1: ICSALVFFMTIPGIALFYGGLL
Helix 2: VMLIFSVVIILWIMFGYSLAFTA
Helix 3: YVHVVFQGSFAVITVALIVGALG
Helix 4: ALLIFTVIWFTFSYIPIAHMVW
Helix 5: LDFAGGTVVHINAAVAALVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTVVATAGAVLAWT
Helix 8: MLGSCSGCIAGLVAITPAA
Helix 9: IGALVIGIIAGIIGLWGVVVL
Helix 10: VFGIHGTCGIAGCLLTGIFTASFLGGI
Helix 11: VLTQLFSVVITLIWSSVVAYIAF

Query ID: B4EU65
Helix 1: ICSALVFFMTIPGIALFYGGLL
Helix 2: VMLIFSVVIILWIMFGYSLAFTA
Helix 3: YVHVVFQGSFAVITVALIVGALG
Helix 4: ALLIFTVIWFTFSYIPIAHMVW
Helix 5: LDFAGGTVVHINAAVAALVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTVVATAGAVLAWT
Helix 8: MLGSCSGCIAGLVAITPAA
Helix 9: IGALVIGIIAGIIGLWGVVVL
Helix 10: VFGIHGTCGIAGCLLTGIFTASFLGGI
Helix 11: VLTQLFSVVITLIWSSVVAYIAF

Query ID: A0A2X2C038
Helix 1: ICSALVFFMTIPGIALFYGGLL
Helix 2: VMLIFSVVIILWIMFGYSLAFTA
Helix 3: YVHVVFQGSFAVITVALIVGALG
Helix 4: ALLIFTVIWFTFSYIPIAHMVW
Helix 5: LDFAGGTVVHINAAVAALVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTVVATAGAVLAWT
Helix 8: MLGSCSGCIAGLVAITPAA
Helix 9: IGALVIGIIAGIIGLWGVVVL
Helix 10: VFGIHGTCGIAGCLLTGIFTASFLGGI
Helix 11: VLTQLFSVVITLIWSSVVAYIAF

Query ID: A0A1S5XW08

Helix 1: TIQLTLTTYLVMIGAGQLLF
Helix 2: VLLGGGLAYVVASMGLAL
Helix 3: VFLGLRILQACGASACLVSTFATV
Helix 4: VIYGILGSMLAMVPAVGPLLGALV
Helix 5: WRAIFAFLGLGMIAASAAAW
Helix 6: FWLYTLCYAAGMGSFFVFFSIA
Helix 7: QLGFSLLFATVAIAMVFTARFM
Helix 8: VLRMGMGCLIAGAVLLAITEIWAL
Helix 9: FIAPMWLVGIGVATAVSVAPNGAL
Helix 10: AVYFCLGGVLLGSIGTLIISLL
Helix 11: WPVVVYCLTLATVVLGLSCV

Query ID: A0A264VQM8
Helix 1: NAFMMIATALVIFMILPGIALFY
Helix 2: LMAQTAVIFALVSVIWIVYGY
Helix 3: FIHVVFQGAFACLTVALVIGALG
Helix 4: AILIFTVIWTTFAYLPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTSILFIGWFG
Helix 7: IAALAFVNTIAAAAGAILSWT
Helix 8: LLGACSGCLAGLVGVTPAAG
Helix 9: GALIIGLLSGLAGLWGVVIL
Helix 10: VFGVHGVCGILGCLLTGVF
Helix 11: VGIQAISILVCVVWTAIVAYIAF

Query ID: A0A1Z1SZE8
Helix 1: ICSALVFFMTIPGIALFYGGLL
Helix 2: VMLIFSVVIILWIMFGYSLAFTA
Helix 3: YVHVVFQGSFAVITVALIVGALG
Helix 4: ALLIFTVIWFTFSYIPIAHMVW
Helix 5: LDFAGGTVVHINAAVAALVGAYLLG
Helix 6: PHNLPMVFTGTAVLYIGWFG
Helix 7: IAALAFLNTVVATAGAVLAWT
Helix 8: MLGSCSGCIAGLVAITPAA
Helix 9: IGALVIGIIAGIIGLWGVVVL
Helix 10: VFGIHGTCGIAGCLLTGIFTASFLGGI
Helix 11: VLTQLFSVVITLIWSSVVAYIAF

Query ID: A0A1S1HRJ0
Helix 1: NAFMMICTALVLFMIVPGIALFY
Helix 2: LMAQTMVILALVSVIWVVYGY
Helix 3: VAFQGAFACLTVALVVGALG
Helix 4: AVLIFAFIWTTFAYIPMAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILFIGWLG
Helix 7: IAALAFINTVVATSGAVLSWV
Helix 8: LLGACSGCLAGLVGVTPGA
Helix 9: AGALIIGLISGIAGLWGVVIL
Helix 10: VFGVHGVCGIVGCLLTGVFASAA
Helix 11: AFSIIVCVIWTAVIAYLAFLIA

Query ID: A0A379GJ68
Helix 1: NAFMMVCTALVLFMIVPGIALFYGG
Helix 2: VLALMAQTMVIFALVSVIWVIY
Helix 3: FIHVAFQGAFACLTVALVVGALG
Helix 4: AILIFTVIWTTFAYLPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILFIGWFGF
Helix 7: AALAFINTVVAASGAILSWV
Helix 8: LLGACSGCLAGLVGVTPAA
Helix 9: AGALIIGLLSGIAGLWGVVVL
Helix 10: VFGVHGVCGVVGCLLTGVFTSAAL
Helix 11: FSILICVVWTSIVAYLAFLIA

Query ID: B2Q716
Helix 1: NAFMMVCTALVLFMIVPGIALFYGG
Helix 2: VLALMAQTMVIFALVSVIWVIY
Helix 3: FIHVAFQGAFACLTVALVVGALG
Helix 4: AILIFTVIWTTFAYLPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILFIGWFGF
Helix 7: AALAFINTVVAASGAILSWV
Helix 8: LLGACSGCLAGLVGVTPAA
Helix 9: AGALIIGLLSGIAGLWGVVVL
Helix 10: VFGVHGVCGVVGCLLTGVFTSAAL
Helix 11: FSILICVVWTSIVAYLAFLIA

Query ID: A0A140NHJ5
Helix 1: NAFMMVCTALVLFMIVPGIALFYGG
Helix 2: VLALMAQTMVIFALVSVIWVIY
Helix 3: FIHVAFQGAFACLTVALVVGALG
Helix 4: AILIFTVIWTTFAYLPIAHMVWG
Helix 5: FAGGTVVHINAAVAGLVGAYLLG
Helix 6: PHNLPMVFMGTAILFIGWFGF
Helix 7: AALAFINTVVAASGAILSWV
Helix 8: LLGACSGCLAGLVGVTPAA
Helix 9: AGALIIGLLSGIAGLWGVVVL
Helix 10: VFGVHGVCGVVGCLLTGVFTSAAL
Helix 11: FSILICVVWTSIVAYLAFLIA

Query ID: A0A1S1HM83
Helix 1: FMLLCTSLVMLMTPGLAFFYGGLV
Helix 2: SFFSMGWVAIIWFVVGYSL
Helix 3: ILVHFSYQMMFAIITPALITGAFA
Helix 4: AYLIFLTLWTLFVYCPFVHMVW
Helix 5: VDFAGGIVVHATAGFAAIASALYV
Helix 6: NIPYIALGAALLWFGWYGF
Helix 7: TVSAFLTTDIAAAFAAVTWF
Helix 8: LVGFLTGAVAGLATITPA
Helix 9: IGSAAIIGIIASLVCYFFVFL
Helix 10: FGVHGVGGITGSILVGVFASTVW
Helix 11: LVAVVFTSVWSFVFTLLILWII

Query ID: A0A370FPU0
Helix 1: LLVILMTVPGLALFYGGL
Helix 2: LSVLMQVFVTFSLIVVLWCIYGY
Helix 3: LLFAAFQATFAGITCCLIVGAFA
Helix 4: GVLVFMVIWFTFSYTPLAHMVWFWM
Helix 5: FAGGTVVHINAAVAGLVGAYVIG
Helix 6: PHSLTLTMVGASLLWVGWFGF
Helix 7: AVLAFINTFSATAAAVLAWSL
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: MGAIVMGFIAGFACLWGVSGL
Helix 10: VFGVHGVGGIVGALLTGVF
Helix 11: VWIQLKGVLLTIVWSGVVSFIAY

Query ID: A0A147GP06
Helix 1: LLVILMTIPGLALFYGGL
Helix 2: LSVLMQVFVTFSLIVVLWCIYGY
Helix 3: LLFAAFQATFAGITCCLIVGAFA
Helix 4: GVLVFMVIWFTFSYTPLAHMVWFWM
Helix 5: FAGGTVVHINAAVAGLVGAYVIG
Helix 6: PHSLTLTMVGASLLWVGWFGF
Helix 7: AVLAFINTFSATAAAVLAWSL
Helix 8: LGAASGAVAGLVAITPAA
Helix 9: MGAIVVGFIAGFACLWGVSGL
Helix 10: VFGVHGVGGIVGALLTGVF
Helix 11: VWIQLKGVLLTIVWSAVVSFIAY

Query ID: A0A316BQ38
Helix 1: WMLVSTALVLFMILPGLALFY
Helix 2: VLMQCTMITAVVIVVWVLWGY
Helix 3: YVFICFQMTFACITPALIIGGFA
Helix 4: AVILFVVLWATFVYFPIAHMAW
Helix 5: VHINAGIAALVGAVMIGR
Helix 6: HALPLTLTGAGILWVGWFGF
Helix 7: AALAMINTFTATAGAVIAWSA
Helix 8: LGGASGVVAGLVAVTPAA
Helix 9: VGAIVLGMIASAVAYYFVTVV
Helix 10: VFGIHGVAGIIGAIGTGVLA
Helix 11: WTQFVAVAVTVVWCGVVSAILY

Query ID: A0A9J9BAE8
Helix 1: FYFLVCGALVMWMAAGFSMLEAGLV
Helix 2: NIALFAISCLMYLVCGYAIM
Helix 3: FFFQVVFVATAMSIVSGAV
Helix 4: WAFLAFAVVMTAFIYPMEGGWTW
Helix 5: FAGSGIVHMAGAAAALAGVLLLG
Helix 6: VNAIPGANLPMATLGTFILWMGW
Helix 7: VAMVFLNTNAAAAGGAVAALVLA
Helix 8: ADLTMVLNGALAGLVAITA
Helix 9: SALGATIIGAIGGVIVVFSII
Helix 10: GAISVHGVVGFFGVMVVPAT
Helix 11: YLGQFVGAMTIFVWVFFASLIVWAIL

Query ID: A0A9J9ES23
Helix 1: YFLLIGAIMVFAMHAGFAFLEV
Helix 2: LVKIITDFGVSCVAYFFIGYWVA
Helix 3: LVKFFFLMTFAAAIPAIIS
Helix 4: FLLASAVIVALVYPFFEGIVWN
Helix 5: FAGSVVVHGIGGWLALVAVFFL
Helix 6: LIAFAPSNIPFLALGTWILCIGWFG
Helix 7: ISGLVAMNSLMAMAGGIIAAWLF
Helix 8: FVHNGPLAGLVAICAGSDI
Helix 9: ALAIGVVAGWLFVTLFTFI
Helix 10: VWPLHGLCGAWGGIAAGIFG
Helix 11: IAAQAMGTIGGILVALIGGVIVYGLI

Query ID: A0A9J9ETF7
Helix 1: NAGIIFTLLAIVVILLKWG
Helix 2: LFTFIAILFTSGLDVGLIMFPL
Helix 3: FGYWGFLIWGFYFLTCFYFCV
Helix 4: LVKLINNVVIIGTCAFTAFLLLSNL
Helix 5: SIVPSFYFIVFAAICFAVY
Helix 6: YVRILSISTTWLFIALIAFMWA
Helix 7: LFWWFAWSIMIGQFTSRFVG
Helix 8: VLGAMLIFPSIPIAVWFSVIYQYH
Helix 9: FAMAFVGIVFVINSLDSLIRLYT
Helix 10: KLGYIALNVITLSLLTLLF
Helix 11: QIQWVGALVIGLFFSCAIFIAY

Query ID: A0A927UCK5
Helix 1: SMLFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFIILGFGLMFGENALFGL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCIYSGVISLIIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGICALVGAKIL
Helix 6: FPGHNIALGALGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAVATCTTMAFTWI
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: ALGAIIIGVVSGFLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFAT
Helix 11: LGLQLLGVLTVGTWAAVTITIAFTVI

Query ID: A0A1H7IQT2
Helix 1: SMLFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFIVLGFGLMFGEDCLFGL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCVYSGIISLVIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGICALIGAKIL
Helix 6: FPGHNIALGALGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAVATVTTMSYTWI
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: ALGAIIIGIVSGFLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFAT
Helix 11: LGIQLLGVLTVGAWAAVTITIAFTVI

Query ID: A0A285RSQ4
Helix 1: SMLFGVWFLIGAALVFWMQAGFAMV
Helix 2: FCIGTVMFIVLGFGLMFGEDCLFGL
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCVYSGIISLVIYPIEAHWIWG
Helix 5: FAGSCAIHMVGGICALIGAKIL
Helix 6: FPGHNIALGALGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAVATVTTMSYTWI
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: ALGAIIIGIVSGFLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFAT
Helix 11: LGIQLLGVLSVGAWAAVTITIAFSVI

Query ID: A0A2G3DSU6
Helix 1: SILFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTVMFVLLGFGLMF
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCIYSGVISLVIYPI
Helix 5: AGSAAIHMVGGICALIGAKIL
Helix 6: FPGHNIALGALGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAVATCTTMAYTWI
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: ALGAAIIGIVSGFLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFAT
Helix 11: LGIQLLGILSVGAWAAVTITIAFSVI

Query ID: A0A2G3E8V2
Helix 1: SLLFGVWFLIGAALVFWMQAGF
Helix 2: LMDFCIGTVMFVLLGFGLMF
Helix 3: FVFNLVFCATTATIVSGA
Helix 4: FISYCIYSGVISLVIYPI
Helix 5: AGSAAIHMVGGICALIGAKIL
Helix 6: FPGHNIALGALGVFILWLGWYGF
Helix 7: ASIFVTTTIAPAVATCTTMAYTWI
Helix 8: VSMSLNASLAGLVAITAP
Helix 9: ALGAAIIGIVSGFLVVFGVWLL
Helix 10: AVAVHMMNGIWGTIAVGLFAT
Helix 11: LGIQLLGILSVGAWAAVTITIAFSVI

In [8]:
len(matches)

11561

In [9]:
with open('lest.txt', 'w') as fp:
    for ite in lest:
        # write each item on a new line
        fp.write("%s\n" % ite)
    print('Done')

Done

In [10]:
with open('spoen.txt', 'w') as fp:
    for items in spoen:
        # write each item on a new line
        fp.write("%s\n" % items)
    print('Done')

Done

In [11]:
with open('matches.txt', 'w') as fp:
    for itemi in matches:
        # write each item on a new line
        fp.write("%s\n" % itemi)
    print('Done')

Done

In [12]:
strong = ' '.join([str(item) for item in lest])

In [13]:

stant = strong.replace(' ', '\n')

In [14]:
textfile = open('helices2.fasta', 'w')
textfile.write(stant)
textfile.close()

In [15]:
def countOccurrence(a):
  k = {}
  for j in a:
    if j in k:
      k[j] +=1
    else:
      k[j] =1
  return k


ths = countOccurrence(spoen)

In [16]:
ths = {key:val for key, val in ths.items() if val >= 11}

In [17]:
hip = []

for u in ths:
    hip.append(u)

In [18]:
with open('hip', 'w') as fp:
    for iteme in hip:
        # write each item on a new line
        fp.write("%s\n" % iteme)
    print('Done')

Done

In [19]:
len(hip)

1051

In [20]:
hip

['A0A011VQM7',
 'A0A063ZJU6',
 'A0A081EVR3',
 'A0A099I9L1',
 'A0A0D8IWY3',
 'A0A0E2HBL2',
 'A0A0F0CIE1',
 'A0A0G3WG46',
 'A0A0G9LEF6',
 'A0A0H5SG89',
 'A0A0J6ZRU4',
 'A0A0J9EMW5',
 'A0A0M2NHW4',
 'A0A0M6WCZ2',
 'A0A0M9AS13',
 'A0A0S2W112',
 'A0A0U5JBG5',
 'A0A0W7TMH6',
 'A0A136Q6K1',
 'A0A136WGT4',
 'A0A140DTE7',
 'A0A143Y517',
 'A0A143Y9S4',
 'A0A143YNF2',
 'A0A143YTA3',
 'A0A143YZV1',
 'A0A143Z212',
 'A0A143ZCA8',
 'A0A151AI36',
 'A0A169X118',
 'A0A173R3X4',
 'A0A173R662',
 'A0A173V441',
 'A0A173X4T2',
 'A0A173XV88',
 'A0A173XVK8',
 'A0A173Z4K3',
 'A0A173ZTK6',
 'A0A174C5U1',
 'A0A174D1D6',
 'A0A174H6C4',
 'A0A174JG28',
 'A0A174RYE8',
 'A0A174TIU3',
 'A0A174VZ55',
 'A0A174XKK3',
 'A0A174YTX7',
 'A0A174Z5H4',
 'A0A175A4T9',
 'A0A1B1YE78',
 'A0A1B1YLE9',
 'A0A1C0BVB4',
 'A0A1C5M0W8',
 'A0A1C5MDL8',
 'A0A1C5N7S1',
 'A0A1C5PFK7',
 'A0A1C5PIG4',
 'A0A1C5PQC5',
 'A0A1C5QAX9',
 'A0A1C5QDA2',
 'A0A1C5QHK8',
 'A0A1C5QX74',
 'A0A1C5R1D9',
 'A0A1C5R365',
 'A0A1C5R381',
 'A0A1C5RAN1',
 'A0A1C5S8B5',
 'A0A1C5SQE8',
 'A0A1C5SVL0',
 'A0A1C5T8Y6',
 'A0A1C5TF49',
 'A0A1C5U2K1',
 'A0A1C5UAP1',
 'A0A1C5UEH7',
 'A0A1C5UU75',
 'A0A1C5VCM0',
 'A0A1C5WY82',
 'A0A1C5Y526',
 'A0A1C5YFR7',
 'A0A1C5YH18',
 'A0A1C5Z331',
 'A0A1C5Z9P9',
 'A0A1C5ZTV2',
 'A0A1C6B393',
 'A0A1C6B4K0',
 'A0A1C6BQA1',
 'A0A1C6CXT8',
 'A0A1C6D1W9',
 'A0A1C6DAP7',
 'A0A1C6DLP9',
 'A0A1C6DWH2',
 'A0A1C6E048',
 'A0A1C6E379',
 'A0A1C6F4A8',
 'A0A1C6FKD5',
 'A0A1C6G7R3',
 'A0A1C6G8E0',
 'A0A1C6G8R0',
 'A0A1C6GHV1',
 'A0A1C6GPW7',
 'A0A1C6HLR1',
 'A0A1C6HNA9',
 'A0A1C6HP51',
 'A0A1C6K3R3',
 'A0A1C6KIH8',
 'A0A1C7GTZ0',
 'A0A1C7HSA7',
 'A0A1C7IDV8',
 'A0A1D3TYQ0',
 'A0A1D9NY31',
 'A0A1F8V8B8',
 'A0A1F9ZPG7',
 'A0A1G4QLQ0',
 'A0A1G4SPK4',
 'A0A1G4VHU5',
 'A0A1G5BLA9',
 'A0A1G5DDJ5',
 'A0A1G5DER5',
 'A0A1G5EK45',
 'A0A1G5FBQ7',
 'A0A1G5RVB0',
 'A0A1G5WAS9',
 'A0A1G5WH50',
 'A0A1G6AA59',
 'A0A1G6AEH9',
 'A0A1G6BHE0',
 'A0A1G6C6K5',
 'A0A1G6KUG1',
 'A0A1G7RHP6',
 'A0A1G8BB52',
 'A0A1G8V2D8',
 'A0A1G8VFZ5',
 'A0A1G9BC39',
 'A0A1G9IKK4',
 'A0A1G9THY2',
 'A0A1G9XUV1',
 'A0A1H2V0V3',
 'A0A1H3HZ52',
 'A0A1H3LXY5',
 'A0A1H3Z0R0',
 'A0A1H3ZKY2',
 'A0A1H4EZX0',
 'A0A1H5WFC4',
 'A0A1H5YYF4',
 'A0A1H6INP9',
 'A0A1H6J2A5',
 'A0A1H6R9C6',
 'A0A1H6W8Z9',
 'A0A1H7IQT2',
 'A0A1H7M3E0',
 'A0A1H7NPU9',
 'A0A1H8S6J8',
 'A0A1H9A9D8',
 'A0A1H9J573',
 'A0A1H9P153',
 'A0A1H9Z210',
 'A0A1I0G858',
 'A0A1I0H5B4',
 'A0A1I0HDV9',
 'A0A1I0IK57',
 'A0A1I0PYA2',
 'A0A1I0QEC7',
 'A0A1I0ZNG3',
 'A0A1I1D0R6',
 'A0A1I1HT54',
 'A0A1I2AKI3',
 'A0A1I2TGT7',
 'A0A1I3B7Y0',
 'A0A1I3FXW0',
 'A0A1I3M286',
 'A0A1I4EUS9',
 'A0A1I4ZMN5',
 'A0A1I5FF58',
 'A0A1I5RRK2',
 'A0A1I5SDH6',
 'A0A1I5Y4A3',
 'A0A1I6FK65',
 'A0A1I6JQR0',
 'A0A1I6KGS1',
 'A0A1I6PBV6',
 'A0A1I7GLL6',
 'A0A1I7IQQ2',
 'A0A1I7ITC5',
 'A0A1J4LTC1',
 'A0A1K1NCM8',
 'A0A1K1PQ76',
 'A0A1L8N3F6',
 'A0A1L8STM4',
 'A0A1M2Z9L9',
 'A0A1M4ZJQ1',
 'A0A1M5QDY1',
 'A0A1M6AMI5',
 'A0A1M6CHL9',
 'A0A1M6FDK6',
 'A0A1M7LS20',
 'A0A1M7N5X0',
 'A0A1M7SHA9',
 'A0A1N7BYW4',
 'A0A1N7EMQ2',
 'A0A1N7ESV5',
 'A0A1P8RI15',
 'A0A1Q6NJY1',
 'A0A1Q6PWR8',
 'A0A1Q6QFY3',
 'A0A1Q9JE84',
 'A0A1Q9YFT7',
 'A0A1Q9YMG2',
 'A0A1S8AZU6',
 'A0A1S9BS50',
 'A0A1S9CM79',
 'A0A1T4JI33',
 'A0A1T4JSS3',
 'A0A1T4M6N6',
 'A0A1T4MPV2',
 'A0A1T4V9X3',
 'A0A1T4XH92',
 'A0A1T4XJ61',
 'A0A1T5FXA3',
 'A0A1U7NFL4',
 'A0A1U7NFM1',
 'A0A1V2M684',
 'A0A1V2M6R2',
 'A0A1V2MD01',
 'A0A1V2YEL3',
 'A0A1V4SQP7',
 'A0A1V5Q5C8',
 'A0A1V5TUL5',
 'A0A1W1IDJ2',
 'A0A1W1IEF4',
 'A0A1W1IG68',
 'A0A1W1ZEY0',
 'A0A1W2AX19',
 'A0A1W2CRU9',
 'A0A1X4HAD1',
 'A0A1Y3A9W7',
 'A0A1Y3AEB2',
 'A0A1Y3AJI8',
 'A0A1Y3RFC7',
 'A0A1Y3RRY4',
 'A0A1Y3SMX9',
 'A0A1Y3TZQ9',
 'A0A1Y3WRK2',
 'A0A1Y3X5L2',
 'A0A1Y3ZW06',
 'A0A1Y4F2V1',
 'A0A1Y4HI56',
 'A0A1Y4J8M1',
 'A0A1Y4L5P0',
 'A0A1Y4LM49',
 'A0A1Y4NDW8',
 'A0A1Y4T9I4',
 'A0A238X318',
 'A0A239QIB5',
 'A0A239R8Y4',
 'A0A252F2L0',
 'A0A256HFN6',
 'A0A256HIH6',
 'A0A256HU74',
 'A0A256HVI6',
 'A0A256HXJ0',
 'A0A256IAU5',
 'A0A256KBC6',
 'A0A261EQJ5',
 'A0A285PCX6',
 'A0A285PVN6',
 'A0A285RSQ4',
 'A0A2A2FDF5',
 'A0A2A5QZ19',
 'A0A2A6ZC76',
 'A0A2A7A1L3',
 'A0A2A7AAI1',
 'A0A2A7ART1',
 'A0A2A7AY63',
 'A0A2A7B470',
 'A0A2A7BC95',
 'A0A2B7GTQ4',
 'A0A2G1WEG4',
 'A0A2G1WTK5',
 'A0A2G3DSU6',
 'A0A2G3E3V2',
 'A0A2G3E8V2',
 'A0A2G3PYR5',
 'A0A2J4JM91',
 'A0A2K9P203',
 'A0A2N0UWP7',
 'A0A2N1RFZ0',
 'A0A2N1ZZK7',
 'A0A2N2A3X2',
 'A0A2N2CN54',
 'A0A2R6CGI2',
 'A0A2R6DG65',
 'A0A2R6EHW0',
 'A0A2R6ETP9',
 'A0A2R6EZG2',
 'A0A2R6FM49',
 'A0A2R6FX01',
 'A0A2R6FYC5',
 'A0A2R6GLV1',
 'A0A2R6H2H7',
 'A0A2R6HFY0',
 'A0A2R6HGN0',
 'A0A2R6I3E5',
 'A0A2R6IP35',
 'A0A2R6JNJ8',
 'A0A2R6K016',
 'A0A2R6KFC5',
 'A0A2R6L1E7',
 'A0A2R6LZL3',
 'A0A2R6M9Y9',
 'A0A2R6N841',
 'A0A2R6N9Z3',
 'A0A2T0B6K8',
 'A0A2T5IEE6',
 'A0A2T5IJN6',
 'A0A2T5IP85',
 'A0A2U2EER7',
 'A0A2V1JRW0',
 'A0A2V2CWD0',
 'A0A2V2DIY8',
 'A0A2V2DR78',
 'A0A2V2DSP1',
 'A0A2V2E7V3',
 'A0A2V2EWK3',
 'A0A2V2EXD4',
 'A0A2V2F5A3',
 'A0A2V2GRB1',
 'A0A2Y9CAP5',
 'A0A2Z2HRJ4',
 'A0A315Y7U6',
 'A0A316C0R3',
 'A0A316L7Q2',
 'A0A316LYI4',
 'A0A316M754',
 'A0A316PAM5',
 'A0A316QTT7',
 'A0A317G0I6',
 'A0A317ULB1',
 'A0A318XMF9',
 'A0A328UCK6',
 'A0A329T9W9',
 'A0A329TIZ6',
 'A0A329U1X5',
 'A0A329U912',
 'A0A329U9C4',
 'A0A329UNK8',
 'A0A343TP47',
 'A0A345E078',
 'A0A345E9S5',
 'A0A346PKS2',
 'A0A348SZ39',
 'A0A349IJT1',
 'A0A350VVQ9',
 'A0A350WYP9',
 'A0A350X0B6',
 'A0A351PIU1',
 'A0A351Q9K7',
 'A0A351XND4',
 'A0A352CNH9',
 'A0A352DPV9',
 'A0A354M8Q0',
 'A0A354MTA6',
 'A0A354UXJ2',
 'A0A354WS17',
 'A0A355L532',
 'A0A355U0T8',
 'A0A355YJX2',
 'A0A356JZA1',
 'A0A358M7Q9',
 'A0A358WFN9',
 'A0A365TD36',
 'A0A367G5A8',
 'A0A367G6Z8',
 'A0A367GD87',
 'A0A368NBY6',
 'A0A372MIA9',
 'A0A373HQJ5',
 'A0A373LV07',
 'A0A373NBW8',
 'A0A373NHW0',
 'A0A373TDA5',
 'A0A373VPI8',
 'A0A373WB21',
 'A0A373WB62',
 'A0A373WNC9',
 'A0A374AZ37',
 'A0A374BTC5',
 'A0A374BV99',
 'A0A374E8I7',
 'A0A374ESQ7',
 'A0A374JZE1',
 'A0A374NIG5',
 'A0A374UM72',
 'A0A374VUC3',
 'A0A380RE50',
 'A0A383TB64',
 'A0A383TEW4',
 'A0A391P2Q7',
 'A0A395V2H0',
 'A0A395WC27',
 'A0A395XAX9',
 'A0A395ZJI4',
 'A0A396KF07',
 'A0A396KTS7',
 'A0A396LLV1',
 'A0A396QBZ7',
 'A0A3A5JCB5',
 'A0A3A6CZX2',
 'A0A3A6DCQ4',
 'A0A3A6DXE2',
 'A0A3A6F2C6',
 'A0A3A6JGR4',
 'A0A3A6JNP8',
 'A0A3A6Q4N4',
 'A0A3A6QA08',
 'A0A3A8U1R4',
 'A0A3A8YRM8',
 'A0A3A8ZR18',
 'A0A3A9A686',
 'A0A3A9AHU2',
 'A0A3A9EQQ1',
 'A0A3A9EZ61',
 'A0A3A9FED2',
 'A0A3A9GFS9',
 'A0A3A9SKZ0',
 'A0A3A9SXB6',
 'A0A3A9T3Z5',
 'A0A3B9DWD0',
 'A0A3B9RR30',
 'A0A3B9SH16',
 'A0A3B9WUZ1',
 'A0A3C0TH36',
 'A0A3C0VS63',
 'A0A3C0ZR78',
 'A0A3C1C0C6',
 'A0A3D1HCR6',
 'A0A3D1HWC2',
 'A0A3D1PR94',
 'A0A3D1YAC0',
 'A0A3D2H4D1',
 'A0A3D2I2I4',
 'A0A3D2IMX9',
 'A0A3D2KFJ0',
 'A0A3D2TS24',
 'A0A3D2YDM4',
 'A0A3D4CDJ0',
 'A0A3D4KWZ7',
 'A0A3D5IDU5',
 'A0A3D5PVN4',
 'A0A3D5T795',
 'A0A3D5WGV8',
 'A0A3E2T713',
 'A0A3E2TW06',
 'A0A3E2UCG9',
 'A0A3E2UHE6',
 'A0A3E2VY88',
 'A0A3E2W4X7',
 'A0A3E4EG44',
 'A0A3E4LX30',
 'A0A3E4LZF5',
 'A0A3E4X059',
 'A0A3E4Y6Y1',
 'A0A3E5AD41',
 'A0A3E5ANY3',
 'A0A3G5FID2',
 'A0A3N0I4G0',
 'A0A3N1XQV6',
 'A0A3N6LYC9',
 'A0A3P3RFN3',
 'A0A3Q9EFA7',
 'A0A3R6HVQ8',
 'A0A3R6LP12',
 'A0A3R6S1G0',
 'A0A3R6S323',
 'A0A3R6T2E2',
 'A0A3R6TUH4',
 'A0A3R6VD02',
 'A0A3R6W9Z0',
 'A0A3R6XWA9',
 'A0A3R7JYP2',
 'A0A410TQW1',
 'A0A412ESC4',
 'A0A412I1L5',
 'A0A412JAI5',
 'A0A412L3Z0',
 'A0A412Q5D9',
 'A0A412Z6T2',
 'A0A413CZM9',
 'A0A413G885',
 'A0A413Q4A5',
 'A0A413U0U1',
 'A0A413UEQ5',
 'A0A413YZC1',
 'A0A414A8A1',
 'A0A414ARU4',
 'A0A414B8U4',
 'A0A414I9E5',
 'A0A414JCA5',
 'A0A414KBZ4',
 'A0A414M657',
 'A0A414P7H7',
 'A0A415D8Z0',
 'A0A415HNX0',
 'A0A415JYM8',
 'A0A415LJU4',
 'A0A415MGB1',
 'A0A415TWJ3',
 'A0A415WAR6',
 'A0A415Y7N4',
 'A0A416CAR5',
 'A0A416CS21',
 'A0A416E8F9',
 'A0A416NNC5',
 'A0A416RXX8',
 'A0A417JY11',
 'A0A417LI53',
 'A0A417PNF3',
 'A0A417R8P8',
 'A0A417U2N8',
 'A0A417UET6',
 'A0A417URP4',
 'A0A417VTC3',
 'A0A419WE02',
 'A0A425W499',
 'A0A425WHC3',
 'A0A426DRR9',
 'A0A430AFK9',
 'A0A448W1N8',
 'A0A482Y865',
 'A0A482YEN8',
 'A0A498EUJ2',
 'A0A498FNH3',
 'A0A498FNJ6',
 'A0A4P5P5X0',
 'A0A4P8WNY4',
 'A0A4P8XWV5',
 'A0A4P9E8H5',
 'A0A4P9TIR6',
 'A0A4Q0I9H8',
 'A0A4Q1RIE4',
 'A0A4Q7PNC0',
 'A0A4R1R5V0',
 'A0A4R3K8Z8',
 'A0A4S2HI78',
 'A0A4U7C4Z3',
 'A0A4U7CDN6',
 'A0A4U7CEX7',
 'A0A4U7CTH9',
 'A0A4U7CX07',
 'A0A4U7D6B8',
 'A0A4U7DHS4',
 'A0A4U7DV69',
 'A0A4U7DZC2',
 'A0A4U7ELJ5',
 'A0A4U7EV64',
 'A0A4U7FCH1',
 'A0A4V0Z790',
 'A0A4V1YJW1',
 'A0A4V2W5N5',
 'A0A4V6E5W0',
 'A0A4V6E8U1',
 'A0A518SEK0',
 'A0A521CIM3',
 'A0A544QNG1',
 'A0A554NB52',
 'A0A562IDY7',
 'A0A564UFL7',
 'A0A564W4H7',
 'A0A564WKL7',
 'A0A5B9YAF3',
 'A0A5C5EBG6',
 'A0A5C5EC53',
 'A0A5D5AW34',
 'A0A5P6VUB9',
 'A0A5P9P1L2',
 'A0A5S4VQ68',
 'A0A644VC25',
 'A0A644WX04',
 'A0A644ZIW7',
 'A0A644ZNG6',
 'A0A6A8KQL6',
 'A0A6A9TAA9',
 'A0A6B0GS07',
 'A0A6B0HI83',
 'A0A6B0SYS2',
 'A0A6B0T2D3',
 'A0A6B1IRM6',
 'A0A6B9F5H2',
 'A0A6B9Y9J0',
 'A0A6G2HCU3',
 'A0A6I2U995',
 'A0A6L5GU43',
 'A0A6L5T631',
 'A0A6L5X9N9',
 'A0A6L5YGT4',
 'A0A6L6LSN8',
 'A0A6L8T527',
 'A0A6L8TE47',
 'A0A6L8XWF0',
 'A0A6M0LJV3',
 'A0A6N2TIA4',
 'A0A6N2TQM8',
 'A0A6N2U4M3',
 'A0A6N2U7D4',
 'A0A6N2W069',
 'A0A6N3AA00',
 'A0A6N3UYL6',
 'A0A6N4AJ78',
 'A0A6N7IXA3',
 'A0A6N7TQV4',
 'A0A6N7V013',
 'A0A6N7YD48',
 'A0A6N8H849',
 'A0A6N9NSM1',
 'A0A6P1TKI8',
 'A0A6S6Y9W4',
 'A0A7C1PK71',
 'A0A7C4F263',
 'A0A7C6H9Z6',
 'A0A7C6NVQ5',
 'A0A7C6R6E7',
 'A0A7C7EJX6',
 'A0A7C8HFW2',
 'A0A7C8LE71',
 'A0A7C9KXI6',
 'A0A7D4BPZ6',
 'A0A7D4Y6E4',
 'A0A7D5E5D8',
 'A0A7D5GLZ7',
 'A0A7D5HVG8',
 'A0A7D5KDW5',
 'A0A7D6H3L9',
 'A0A7G9FKU0',
 'A0A7G9FW70',
 'A0A7G9G952',
 'A0A7S7EV90',
 'A0A7T3RCF2',
 'A0A7U9R1V9',
 'A0A7U9R3D7',
 'A0A7U9R5J5',
 'A0A7U9T6R9',
 'A0A7U9X625',
 'A0A7W8D0F3',
 'A0A7W8G7U4',
 'A0A7X2PCT8',
 'A0A7X2TAH0',
 'A0A7X2TKZ1',
 'A0A7X3BVN0',
 'A0A7X3MJ87',
 'A0A7X4IAQ1',
 'A0A7X4Z7P0',
 'A0A7X5ITR0',
 'A0A7X6Z9C6',
 'A0A7X7EBR4',
 'A0A7X7MUH8',
 'A0A7X7SX82',
 'A0A7X8LYU7',
 'A0A7X8ZM44',
 'A0A828T2Z2',
 'A0A829VSR2',
 'A0A830EVM0',
 'A0A830EVZ3',
 'A0A830EZG5',
 'A0A830G1F5',
 'A0A830G1M4',
 'A0A830G6D7',
 'A0A830G7F1',
 'A0A830GGW9',
 'A0A840UFH7',
 'A0A844DI00',
 'A0A844DSN8',
 'A0A844E1F8',
 'A0A844EBW4',
 'A0A844GK08',
 'A0A847CH26',
 'A0A847D572',
 'A0A847D5D1',
 'A0A847N1P0',
 'A0A848CN11',
 'A0A855A551',
 'A0A897MVN0',
 'A0A8A2UE16',
 'A0A8A2VRW2',
 'A0A8E0R6M4',
 'A0A8E8EWD3',
 'A0A8F2F0Z1',
 'A0A8G1HA07',
 'A0A8G1TG76',
 'A0A8H9WS41',
 'A0A8I0AFC7',
 'A0A8I0AML0',
 'A0A8J6MF22',
 'A0A8J7H066',
 'A0A8J7RSZ7',
 'A0A8J7W099',
 'A0A8J7ZL15',
 'A0A8J8GL03',
 'A0A8J8JLU4',
 'A0A8J8TCR8',
 'A0A8T4JNY7',
 'A0A8T8E5C4',
 'A0A8T8LM48',
 'A0A8T8WGV8',
 'A0A8U0A4W0',
 'A0A8U0HXP0',
 'A0A921CQD5',
 'A0A921IJH5',
 'A0A923L9M9',
 'A0A923LJB6',
 'A0A923LT31',
 'A0A923MJ15',
 'A0A926D072',
 'A0A926DNP9',
 'A0A926I1D1',
 'A0A926ITG4',
 'A0A927TT45',
 'A0A927U2I5',
 'A0A927UCK5',
 'A0A927UFI4',
 'A0A927VG47',
 'A0A927Y2C9',
 'A0A927Z8W5',
 'A0A928MLI3',
 'A0A928PDI2',
 'A0A929PZG7',
 'A0A931YR25',
 'A0A934U4C2',
 'A0A934WTK7',
 'A0A939UJD4',
 'A0A939UJK2',
 'A0A939W7Z3',
 'A0A939WC21',
 'A0A939YG34',
 'A0A939YK48',
 'A0A939ZGI3',
 'A0A940AES9',
 'A0A940C6R1',
 'A0A940HNM9',
 'A0A940QD87',
 'A0A942AJH2',
 'A0A942ZYB7',
 'A0A943BNF2',
 'A0A943C7N0',
 'A0A943ED55',
 'A0A943GCU7',
 'A0A943GRX7',
 'A0A943HIE2',
 'A0A943J076',
 'A0A943NYK0',
 'A0A943QFJ1',
 'A0A943SBH9',
 'A0A943SBR8',
 'A0A943TBR5',
 'A0A943WTH4',
 'A0A943WXB1',
 'A0A944A298',
 'A0A965Y123',
 'A0A966DAA4',
 'A0A970EGU6',
 'A0A970EUV8',
 'A0A970FKS3',
 'A0A970MCH7',
 'A0A970R0N6',
 'A0A970WAS2',
 'A0A970XEB3',
 'A0A970YC48',
 'A0A970ZDE8',
 'A0A971AMS4',
 'A0A971G133',
 'A0A971PA06',
 'A0A971UX20',
 'A0A971YEX5',
 'A0A975CXD7',
 'A0A9D0XUZ3',
 'A0A9D1AF25',
 'A0A9D1AN72',
 'A0A9D1DY38',
 'A0A9D1E5J4',
 'A0A9D1EJI6',
 'A0A9D1FSP6',
 'A0A9D1H983',
 'A0A9D1HIU9',
 'A0A9D1IAR5',
 'A0A9D1IFL3',
 'A0A9D1K626',
 'A0A9D1LT03',
 'A0A9D1MK71',
 'A0A9D1NUM8',
 'A0A9D1P0E7',
 'A0A9D1PAS3',
 'A0A9D1PI59',
 'A0A9D1Q0C9',
 'A0A9D1R782',
 'A0A9D1RDL4',
 'A0A9D1RTV9',
 'A0A9D1TW90',
 'A0A9D1VYY3',
 'A0A9D1WJ49',
 'A0A9D1XX72',
 'A0A9D1XZ54',
 'A0A9D1Y891',
 'A0A9D1YLV6',
 'A0A9D1Z3V4',
 'A0A9D2AJ74',
 'A0A9D2B956',
 'A0A9D2C039',
 'A0A9D2DQS4',
 'A0A9D2ET86',
 'A0A9D2FHB1',
 'A0A9D2I7W5',
 'A0A9D2ISQ7',
 'A0A9D2L3A6',
 'A0A9D2LXL7',
 'A0A9D2MKL6',
 'A0A9D2MY18',
 'A0A9D2NFE9',
 'A0A9D2PL68',
 'A0A9D2QIP9',
 'A0A9D2S172',
 'A0A9D2TL68',
 'A0A9D5LWH3',
 'A0A9D5MBH6',
 'A0A9D5RG35',
 'A0A9D9EKF2',
 'A0A9E0BIP8',
 'A0A9E0CWJ9',
 'A0A9E0E141',
 'A0A9E0ZT81',
 'A0A9E1AU37',
 'A0A9E1B092',
 'A0A9E1BBE4',
 'A0A9E1GPE1',
 'A0A9E1HWM8',
 'A0A9E1LZN9',
 'A0A9E1M5L6',
 'A0A9E2KLD9',
 'A0A9E5G8Q6',
 'A0A9E5SGS8',
 'A0A9E5SYZ5',
 'A0A9E7NER7',
 'A0A9N6YWI2',
 'A0A9P1BFQ1',
 'A0A9Q4L4W6',
 'A0A9R1CQJ0',
 'A0A9X5BDZ9',
 'A0A9X5CBN7',
 'A0A9X8CWY5',
 'A0A9Y2E7Z6',
 'A0AA35G8C0',
 'A0AA37N4P2',
 'A0AA41K7Q2',
 'A0AA42DKQ7',
 'A0AA51DY56',
 'A0AA96PW81',
 'A0AA97D792',
 'A0AA97DUI0',
 'A0AAE3D748',
 'A0AAE3DG60',
 'A0AAE3DN91',
 'A0AAE3E9V9',
 'A0AAE3FVH7',
 'A0AAE3IFS2',
 'A0AAE3IFX0',
 'A0AAE3IK34',
 'A0AAE3TNI8',
 'A0AAE5HBT0',
 'A0AAF0PE89',
 'A0AAI9K111',
 'A0AAJ1D443',
 'A0AAJ2WED0',
 'A0AAJ4RA85',
 'A0AAP2ULS0',
 'A0AAP3E1B7',
 'A0AAP4EYC2',
 'A0AAP5KD54',
 'A0AAP9MGG7',
 'A0AAQ1R4F2',
 'A0AAU8A953',
 'A0AAV3S8B5',
 'A0AAV3S8M2',
 'A0AAV3SSM3',
 'A0AAV3T0D2',
 'A0AAV3T9N5',
 'A0AAV3UFU8',
 'A0AAW3JSL2',
 'A0AAW4MRY2',
 'A0AAW4VYU4',
 'A0AAW5BVA4',
 'A0AAW5CEX0',
 'A0AAW5JS35',
 'A0AAW5KIA1',
 'A0AAW5KKH1',
 'A0AAW6CZW8',
 'A0AAW6E135',
 'A0AAW6E1G4',
 'A0AAW6E1L3',
 'A0AAW6E6L2',
 'A0AAW6E800',
 'A0AAW6EBC8',
 'A0AAW6EF18',
 'A0AAW6EG62',
 'A0AAW8SM42',
 'A0AAW8STE1',
 'A0AAW9L200',
 'A0AAW9L5U5',
 'A0AAX0BFH2',
 'A0AAX1QGG3',
 'A3DFJ8',
 'A5KIW3',
 'A5ZXR8',
 'A7VSI5',
 'A8RR22',
 'A8S9D1',
 'B0MJN0',
 'B5CSB8',
 'B7ATM0',
 'B7CC80',
 'B9LU00',
 'C0EAH3',
 'C4Z544',
 'C4ZEH3',
 'C6LBD3',
 'D1PQI1',
 'D2RU19',
 'D3ASW2',
 'D4LUB7',
 'D4MIA0',
 'D8J4C6',
 'E0RUI1',
 'E2ZFN4',
 'E5VHJ9',
 'F0RVD2',
 'F1TCK5',
 'F2JQ39',
 'F2NWX7',
 'F3AS48',
 'F4LNJ2',
 'F7JQQ0',
 'F7V881',
 'F8D7H6',
 'G1VN54',
 'G5HMB9',
 'G8QQ37',
 'H1B9D4',
 'H1D386',
 'H2JF35',
 'H7EIN0',
 'I5ASC3',
 'I7CDY2',
 'L0AHQ0',
 'L0JT30',
 'L1QIL7',
 'L9X2V2',
 'L9XS69',
 'L9XTL3',
 'L9YY28',
 'L9YZJ4',
 'L9ZG19',
 'L9ZNI9',
 'M0AHA9',
 'M0B6S6',
 'M0B7J9',
 'M0BW44',
 'M0C732',
 'M0CJN2',
 'M0D7V4',
 'M0DV62',
 'M0E1M5',
 'M0EBA7',
 'M0EBX9',
 'M0EL38',
 'M0EWN7',
 'M0F7H2',
 'M0LRJ9',
 'M0M6R9',
 'M0MDP9',
 'M0NET8',
 'M0NRE6',
 'M0NRJ2',
 'M0P8Z5',
 'M0PEA5',
 'M0PKL9',
 'M1XLN4',
 'N9WDC4',
 'R0AQW9',
 'R0BZC3',
 'R0C600',
 'R2RPW4',
 'R2SYZ8',
 'R4W0C0',
 'R5A6V9',
 'R5CN13',
 'R5E2R0',
 'R5EA84',
 'R5EIE5',
 'R5GVC5',
 'R5KIH9',
 'R5P5I7',
 'R5QL68',
 'R5R1D4',
 'R5TYE5',
 ...]

In [21]:
u = UniProt(verbose=False)

In [22]:
losht = []

for bats in hip:
    headers = u.search(bats, frmt = 'fasta')
#     print(headers)
    record = SeqIO.read(StringIO(headers), "fasta")
    print(record)
    losht.append(record)

ID: tr|A0A011VQM7|A0A011VQM7_RUMAL
Name: tr|A0A011VQM7|A0A011VQM7_RUMAL
Description: tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1
Number of features: 0
Seq('MDVQEIVQEVTQASDKTVFGVWFMIAVALVFFMQAGFAMVETGFTRAKNAGNII...PAT')
ID: tr|A0A063ZJU6|A0A063ZJU6_9EURY
Name: tr|A0A063ZJU6|A0A063ZJU6_9EURY
Description: tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp. A56 OX=1495067 GN=EL22_10090 PE=3 SV=1
Number of features: 0
Seq('MDATPLQVDPEVIVEGVNLMWVLIATFLIFFMHAGFAMLEAGQVRSKNVANQLT...DAV')
ID: tr|A0A081EVR3|A0A081EVR3_9EURY
Name: tr|A0A081EVR3|A0A081EVR3_9EURY
Description: tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1
Number of features: 0
Seq('MTAGVLASIDPSVLAEGVNLMWVAVVCFLIFFMHAGFAMLEAGQVRAKNVANQL...EAV')
ID: tr|A0A099I9L1|A0A099I9L1_CLOIN
Name: tr|A0A099I9L1|A0A099I9L1_CLOIN
Description: tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1
Number of features: 0
Seq('MLYSPVNTIWVLVGAALVFFMQAGFSLCEAGFTRAKNTGNILMKNLMDFCIGTP...DID')
ID: tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM
Name: tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM
Description: tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1
Number of features: 0
Seq('MMYSSVDTIWVLLGAALVFFMQAGFAMVETGLTRAKNAGNIIMKNLMDFALGTV...DTH')
ID: tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM
Name: tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM
Description: tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTP...QGE')
ID: tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT
Name: tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT
Description: tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp. FS41 OX=1609975 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTP...QGE')
ID: tr|A0A0G3WG46|A0A0G3WG46_9BACT
Name: tr|A0A0G3WG46|A0A0G3WG46_9BACT
Description: tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEPATFSSVDTLWVLFGAALVFFMQPGFAMLEAGLTRAKNAGNIVLKNLMDFAF...DVK')
ID: tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT
Name: tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT
Description: tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp. C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1
Number of features: 0
Seq('MNSTMIIDTVWVFLAAILVFFMNLGFASVEAGFARSKNTVNILSKNFIVFAVSS...DEE')
ID: tr|A0A0H5SG89|A0A0H5SG89_HERHM
Name: tr|A0A0H5SG89|A0A0H5SG89_HERHM
Description: tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1
Number of features: 0
Seq('MDYVMIVDTIWVVLAAVLVFFMNLGFAAVESGFARSKNTVNILSKNFIVFAVSS...DEE')
ID: tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM
Name: tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM
Description: tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1
Number of features: 0
Seq('MIYPTAEFSWLIVAAFLAFIIQPGVAMVESGLSRSKNAADMMIRVYTNFGIIII...YTI')
ID: tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM
Name: tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM
Description: tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTP...QGE')
ID: tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM
Name: tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM
Description: tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1
Number of features: 0
Seq('MYSAVDTVWVLLGAALVFFMQAGFAMVETGLTRAKNAGNIVMKNLMDFSLGSIV...DEE')
ID: tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM
Name: tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM
Description: tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTEEISGVIFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNILMKNLMDFCI...DVE')
ID: tr|A0A0M9AS13|A0A0M9AS13_9EURY
Name: tr|A0A0M9AS13|A0A0M9AS13_9EURY
Description: tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1
Number of features: 0
Seq('MTAGVLATIDPSTFASAMNGTWILVVTFLIFFMHAGFAMLEAGQVRSKNVANQL...EAV')
ID: tr|A0A0S2W112|A0A0S2W112_9FIRM
Name: tr|A0A0S2W112|A0A0S2W112_9FIRM
Description: tr|A0A0S2W112|A0A0S2W112_9FIRM Ammonium transporter OS=Intestinimonas butyriciproducens OX=1297617 GN=C7373_1064 PE=3 SV=1
Number of features: 0
Seq('MYSSVNTIWVLLGAAMVFFMQAGFAMCEAGFTRSKNTGNILMKNLMDFCIGTPA...QGD')
ID: tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT
Name: tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT
Description: tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT Ammonia channel OS=Clostridium sp. C105KSO13 OX=1776045 GN=amt PE=3 SV=1
Number of features: 0
Seq('MSQIIIDSFWVALAAFLVFWMNLGFASVEAGMARAKNTVNILSKNFIVFAVSSL...DEV')
ID: tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM
Name: tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM
Description: tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=ASJ35_15960 PE=3 SV=1
Number of features: 0
Seq('MMYSSVDTIWVLLGAALVFFMQAGFAMVETGLTRAKNAGNIIMKNLMDFALGTV...DTH')
ID: tr|A0A136Q6K1|A0A136Q6K1_9FIRM
Name: tr|A0A136Q6K1|A0A136Q6K1_9FIRM
Description: tr|A0A136Q6K1|A0A136Q6K1_9FIRM Nitrogen regulatory protein P-II OS=Christensenella minuta OX=626937 GN=HMPREF3293_01017 PE=3 SV=1
Number of features: 0
Seq('MFSSVDTVWVLLGAALVFFMQAGFAMVETGLTRAKNAGNIIMKNLMDFSLGSVV...ECD')
ID: tr|A0A136WGT4|A0A136WGT4_9FIRM
Name: tr|A0A136WGT4|A0A136WGT4_9FIRM
Description: tr|A0A136WGT4|A0A136WGT4_9FIRM Ammonia channel OS=Anaerotignum neopropionicum OX=36847 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNALELFEQASSDLFGIWFLMGAVLVFFMQAGFAMVETGFTRAKNAGNIIMKNL...GEE')
ID: tr|A0A140DTE7|A0A140DTE7_9FIRM
Name: tr|A0A140DTE7|A0A140DTE7_9FIRM
Description: tr|A0A140DTE7|A0A140DTE7_9FIRM Ammonium transporter OS=Faecalibaculum rodentium OX=1702221 GN=AALO17_07900 PE=3 SV=1
Number of features: 0
Seq('MIEEAISQIFGIWYLIGAALVFFMQAGFAMVEAGFTRAKNAGNIIMKNTMDFCL...YED')
ID: tr|A0A143Y517|A0A143Y517_9LACT
Name: tr|A0A143Y517|A0A143Y517_9LACT
Description: tr|A0A143Y517|A0A143Y517_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_251 PE=3 SV=1
Number of features: 0
Seq('MENINMADTTFMFLATVMVLLMTPALSLFYGGMVRAKNVLSTTMHSYAAIVVVV...ATS')
ID: tr|A0A143Y9S4|A0A143Y9S4_9LACT
Name: tr|A0A143Y9S4|A0A143Y9S4_9LACT
Description: tr|A0A143Y9S4|A0A143Y9S4_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_303 PE=3 SV=1
Number of features: 0
Seq('MENINYADTTFVFLATILVLLMTPALSLFYGGMVRKKNILSTTMHSYVAIAVVS...PTE')
ID: tr|A0A143YNF2|A0A143YNF2_9LACT
Name: tr|A0A143YNF2|A0A143YNF2_9LACT
Description: tr|A0A143YNF2|A0A143YNF2_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_1615 PE=3 SV=1
Number of features: 0
Seq('MENINYADTTFVFFATALVMLMTPALSLFYGGMVRGKNVLSTTMHSYAAIAVVS...VEA')
ID: tr|A0A143YTA3|A0A143YTA3_9LACT
Name: tr|A0A143YTA3|A0A143YTA3_9LACT
Description: tr|A0A143YTA3|A0A143YTA3_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1428 PE=3 SV=1
Number of features: 0
Seq('MFSSVDTLWTLVGTVLVFFMQAGFAMVETGFTRAKNAANIIMKNLMDFVLGSLG...KYY')
ID: tr|A0A143YZV1|A0A143YZV1_9LACT
Name: tr|A0A143YZV1|A0A143YZV1_9LACT
Description: tr|A0A143YZV1|A0A143YZV1_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_1725 PE=3 SV=1
Number of features: 0
Seq('MFSSVDTLWTLLGTVLVFFMQAGFAMVETGFTRAKNAANIIMKNLMDFVLGSLG...KYY')
ID: tr|A0A143Z212|A0A143Z212_9LACT
Name: tr|A0A143Z212|A0A143Z212_9LACT
Description: tr|A0A143Z212|A0A143Z212_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1990 PE=3 SV=1
Number of features: 0
Seq('MENINYADTTFVFLATILVMLMTPALSLFYAGMVRRKNVLSTTMHSYAAIAVVS...PTE')
ID: tr|A0A143ZCA8|A0A143ZCA8_9LACT
Name: tr|A0A143ZCA8|A0A143ZCA8_9LACT
Description: tr|A0A143ZCA8|A0A143ZCA8_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_2799 PE=3 SV=1
Number of features: 0
Seq('MEINMADTTFMFLATVMVLLMTPALSLFYGGMVREKNVLSTTMHSYAAIVVVVI...ATS')
ID: tr|A0A151AI36|A0A151AI36_9EURY
Name: tr|A0A151AI36|A0A151AI36_9EURY
Description: tr|A0A151AI36|A0A151AI36_9EURY Putative ammonium transporter OS=Halalkalicoccus paucihalophilus OX=1008153 GN=HAPAU_09570 PE=3 SV=1
Number of features: 0
Seq('MQVDPSVLAEGVNMMWVLVVTFLIFFMHAGFAMLEAGQVRSKNVANQLTKNLLT...EAV')
ID: tr|A0A169X118|A0A169X118_9EURY
Name: tr|A0A169X118|A0A169X118_9EURY
Description: tr|A0A169X118|A0A169X118_9EURY Ammonium transporter OS=Haladaptatus sp. R4 OX=1679489 GN=A4G99_00420 PE=3 SV=1
Number of features: 0
Seq('MSDLEVIAQGINLLWVLIATFLIFFMHAGFAMLEAGQVRSKNVANQLTKNLLTW...DAV')
ID: tr|A0A173R3X4|A0A173R3X4_ANAHA
Name: tr|A0A173R3X4|A0A173R3X4_ANAHA
Description: tr|A0A173R3X4|A0A173R3X4_ANAHA Ammonia transporter OS=Anaerostipes hadrus OX=649756 GN=amt_1 PE=3 SV=1
Number of features: 0
Seq('MTKEIMNAVNTQIFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNAGNIIMKNLM...DVE')
ID: tr|A0A173R662|A0A173R662_EUBRA
Name: tr|A0A173R662|A0A173R662_EUBRA
Description: tr|A0A173R662|A0A173R662_EUBRA Ammonia transporter OS=Eubacterium ramulus OX=39490 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTQEIMTFINDNIFGVWFLMGAALVFWMQAGFAMVEAGFTRAKNTGNILMKNLM...LQD')
ID: tr|A0A173V441|A0A173V441_9FIRM
Name: tr|A0A173V441|A0A173V441_9FIRM
Description: tr|A0A173V441|A0A173V441_9FIRM Ammonia transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A173X4T2|A0A173X4T2_9FIRM
Name: tr|A0A173X4T2|A0A173X4T2_9FIRM
Description: tr|A0A173X4T2|A0A173X4T2_9FIRM Ammonia transporter OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTEEISGVIFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNILMKNLMDFCI...DVE')
ID: tr|A0A173XV88|A0A173XV88_9FIRM
Name: tr|A0A173XV88|A0A173XV88_9FIRM
Description: tr|A0A173XV88|A0A173XV88_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSSVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...PLE')
ID: tr|A0A173XVK8|A0A173XVK8_9CLOT
Name: tr|A0A173XVK8|A0A173XVK8_9CLOT
Description: tr|A0A173XVK8|A0A173XVK8_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_1 PE=3 SV=1
Number of features: 0
Seq('MYSALDTIWTLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTVV...DEK')
ID: tr|A0A173Z4K3|A0A173Z4K3_9FIRM
Name: tr|A0A173Z4K3|A0A173Z4K3_9FIRM
Description: tr|A0A173Z4K3|A0A173Z4K3_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...DTK')
ID: tr|A0A173ZTK6|A0A173ZTK6_9FIRM
Name: tr|A0A173ZTK6|A0A173ZTK6_9FIRM
Description: tr|A0A173ZTK6|A0A173ZTK6_9FIRM Ammonia transporter OS=[Ruminococcus] torques OX=33039 GN=amt PE=3 SV=1
Number of features: 0
Seq('MYSSVNTIWVLFGTALVFFMQAGFSLCEAGFIRAKNTGNILMKNLMDFCIGTPA...DVE')
ID: tr|A0A174C5U1|A0A174C5U1_9FIRM
Name: tr|A0A174C5U1|A0A174C5U1_9FIRM
Description: tr|A0A174C5U1|A0A174C5U1_9FIRM Ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTP...QGE')
ID: tr|A0A174D1D6|A0A174D1D6_9FIRM
Name: tr|A0A174D1D6|A0A174D1D6_9FIRM
Description: tr|A0A174D1D6|A0A174D1D6_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...DTK')
ID: tr|A0A174H6C4|A0A174H6C4_9CLOT
Name: tr|A0A174H6C4|A0A174H6C4_9CLOT
Description: tr|A0A174H6C4|A0A174H6C4_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_2 PE=3 SV=1
Number of features: 0
Seq('MYSSLDTIWTLFGAVLVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTVV...DEE')
ID: tr|A0A174JG28|A0A174JG28_9FIRM
Name: tr|A0A174JG28|A0A174JG28_9FIRM
Description: tr|A0A174JG28|A0A174JG28_9FIRM Ammonia transporter OS=Blautia wexlerae OX=418240 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...DTK')
ID: tr|A0A174RYE8|A0A174RYE8_9FIRM
Name: tr|A0A174RYE8|A0A174RYE8_9FIRM
Description: tr|A0A174RYE8|A0A174RYE8_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSSVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...PLE')
ID: tr|A0A174TIU3|A0A174TIU3_ANAHA
Name: tr|A0A174TIU3|A0A174TIU3_ANAHA
Description: tr|A0A174TIU3|A0A174TIU3_ANAHA Adenylate cyclase OS=Anaerostipes hadrus OX=649756 GN=amt_2 PE=3 SV=1
Number of features: 0
Seq('MTKEIMNAVNTQIFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNAGNIIMKNLM...DVE')
ID: tr|A0A174VZ55|A0A174VZ55_9FIRM
Name: tr|A0A174VZ55|A0A174VZ55_9FIRM
Description: tr|A0A174VZ55|A0A174VZ55_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEFSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...DTK')
ID: tr|A0A174XKK3|A0A174XKK3_9FIRM
Name: tr|A0A174XKK3|A0A174XKK3_9FIRM
Description: tr|A0A174XKK3|A0A174XKK3_9FIRM Ammonium transporter OS=Hungatella hathewayi OX=154046 GN=amt PE=3 SV=1
Number of features: 0
Seq('MSAVNTIWVLFGAALVFFMQAGFAMVETGFTRAKNSGNIIMKNLMDFCIGTPIF...DQD')
ID: tr|A0A174YTX7|A0A174YTX7_9FIRM
Name: tr|A0A174YTX7|A0A174YTX7_9FIRM
Description: tr|A0A174YTX7|A0A174YTX7_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1
Number of features: 0
Seq('MQEILSAVDAELFGVWFLIGAALVFWMQAGFAMVETGFTRAKNSGNIIMKNLMD...EDD')
ID: tr|A0A174Z5H4|A0A174Z5H4_9FIRM
Name: tr|A0A174Z5H4|A0A174Z5H4_9FIRM
Description: tr|A0A174Z5H4|A0A174Z5H4_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1
Number of features: 0
Seq('MQEILSAVDAELFGVWFLIGAALVFWMQAGFAMVETGFTRAKNSGNIIMKNLMD...EDD')
ID: tr|A0A175A4T9|A0A175A4T9_9FIRM
Name: tr|A0A175A4T9|A0A175A4T9_9FIRM
Description: tr|A0A175A4T9|A0A175A4T9_9FIRM Ammonia transporter OS=[Eubacterium] siraeum OX=39492 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDFLSTLTLAAESADKIQETVNATMFNVGDGNGIWYLIGAALVFFMQCGFAMVE...DND')
ID: tr|A0A1B1YE78|A0A1B1YE78_THEST
Name: tr|A0A1B1YE78|A0A1B1YE78_THEST
Description: tr|A0A1B1YE78|A0A1B1YE78_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. thermolacticum DSM 2910 OX=1121336 GN=CSTERTH_08555 PE=3 SV=1
Number of features: 0
Seq('MDITMFVDTLWVVFAGILVFFMNLGFAAVESGFARSKNTVNILSKNFIVFAVSS...DKE')
ID: tr|A0A1B1YLE9|A0A1B1YLE9_THEST
Name: tr|A0A1B1YLE9|A0A1B1YLE9_THEST
Description: tr|A0A1B1YLE9|A0A1B1YLE9_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. leptospartum DSM 9219 OX=1346611 GN=CSTERLE_08480 PE=3 SV=1
Number of features: 0
Seq('MDITMFVDTLWVVFAGILVFFMNLGFAAVESGFARSKNTVNILSKNFIVFAVSS...DKE')
ID: tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM
Name: tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM
Description: tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium MTC7 OX=1768196 GN=A4S06_10005 PE=3 SV=1
Number of features: 0
Seq('MGSFSGLDTLWVLLGATLVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFALGT...YED')
ID: tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT
Name: tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT
Description: tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTQEILSAIDGQLFAVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNILMKNLM...DVE')
ID: tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM
Name: tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM
Description: tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...AEK')
ID: tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT
Name: tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT
Description: tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIGTP...QGE')
ID: tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM
Name: tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM
Description: tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSSVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...PLE')
ID: tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT
Name: tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT
Description: tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTQEILSAISGEVYGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNILMKNLM...DVE')
ID: tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM
Name: tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM
Description: tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM Ammonia transporter OS=uncultured Dorea sp OX=286138 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSQDILTAISDAVGTEVFGIWFLIGAALVFFMQAGFAMVEAGFTRAKNAGNIIM...DVE')
ID: tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT
Name: tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT
Description: tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTEEILSVLNGEVFGVWFLIGAALVFWMQAGFAMVETGFTRAKNAGNILMKNLM...DVE')
ID: tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM
Name: tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM
Description: tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MFSSINTCWVLVAAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM
Name: tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM
Description: tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1
Number of features: 0
Seq('MEQLFSSVDTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFAIG...GDD')
ID: tr|A0A1C5QX74|A0A1C5QX74_9FIRM
Name: tr|A0A1C5QX74|A0A1C5QX74_9FIRM
Description: tr|A0A1C5QX74|A0A1C5QX74_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTNTVTVLAESTGFSAVNTIWVLLGAALVFFMQAGFAMVETGFTRAKNAGNIIM...QDD')
ID: tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM
Name: tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM
Description: tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTDEILSVINGQVYGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLM...DVE')
ID: tr|A0A1C5R365|A0A1C5R365_9FIRM
Name: tr|A0A1C5R365|A0A1C5R365_9FIRM
Description: tr|A0A1C5R365|A0A1C5R365_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MFSSINTCWTLVAAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A1C5R381|A0A1C5R381_9FIRM
Name: tr|A0A1C5R381|A0A1C5R381_9FIRM
Description: tr|A0A1C5R381|A0A1C5R381_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1
Number of features: 0
Seq('MYSSLDTVWVLLCTALIFFMQAGFAMLETGFTREKNAGNIIMKNLMDYCIGSVL...ALE')
ID: tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM
Name: tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM
Description: tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...HEE')
ID: tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM
Name: tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM
Description: tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNFSSVDVIWTLLGAALVYFMQAGFAMCEAGLTRAKNTGNILMKNMMDFCIGTP...DVE')
ID: tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM
Name: tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM
Description: tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1
Number of features: 0
Seq('MYSSVNTIWVLFGTALVFFMQAGFSLCEAGFTRAKNTGNILMKNLMDFCIGTPA...DVE')
ID: tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM
Name: tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM
Description: tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDYSAVNTIWVLVGAALVFFMQAGFAMVETGFTRAKNAGNIIMKNLMDFCIGTP...AEA')
ID: tr|A0A1C5T8Y6|A0A1C5T8Y6_9FIRM
Name: tr|A0A1C5T8Y6|A0A1C5T8Y6_9FIRM

ID: tr|W7QGE0|W7QGE0_9ALTE
Name: tr|W7QGE0|W7QGE0_9ALTE
Description: tr|W7QGE0|W7QGE0_9ALTE Ammonium transporter OS=Catenovulum agarivorans DS-2 OX=1328313 GN=DS2_05440 PE=3 SV=1
Number of features: 0
Seq('MRAIIALLLLLPLTASAEGLDTGDTAWILTASALVLFMTLPGLSFFYAGLVRSK...YNL')
ID: tr|W7QG13|W7QG13_9ALTE
Name: tr|W7QG13|W7QG13_9ALTE
Description: tr|W7QG13|W7QG13_9ALTE Ammonium transporter OS=Catenovulum agarivorans DS-2 OX=1328313 GN=DS2_06106 PE=3 SV=1
Number of features: 0
Seq('MENNVFHLQYAMDTFYFLVCGALVMWMAAGFAMLEAGLVRAKNTTEILTKNIAL...SAK')
ID: tr|W7QGM4|W7QGM4_9ALTE
Name: tr|W7QGM4|W7QGM4_9ALTE
Description: tr|W7QGM4|W7QGM4_9ALTE Diguanylate cyclase/phosphodiesterase (GGDEF & EAL domains) with PAS/PAC sensor(S) OS=Catenovulum agarivorans DS-2 OX=1328313 GN=DS2_00080 PE=3 SV=1
Number of features: 0
Seq('MTIDILWVLFCAVLVLVMQGGFLFLESGLTRKKNAINVALKNATDFALTFLLWW...LVS')
ID: tr|C7QGX3|C7QGX3_CATAD
Name: tr|C7QGX3|C7QGX3_CATAD
Description: tr|C7QGX3|C7QGX3_CATAD Ammonium transporter OS=Catenulispora acidiphila (strain DSM 44928 / JCM 14897 / NBRC 102108 / NRRL B-24433 / ID139908) OX=479433 GN=Caci_8000 PE=3 SV=1
Number of features: 0
Seq('MPSAFSNGDTAWVLASSALVLLMTPGLAFFYGGMVRAKSVLNMLMMNFIAIAVV...VKA')
ID: tr|C7Q1E4|C7Q1E4_CATAD
Name: tr|C7Q1E4|C7Q1E4_CATAD
Description: tr|C7Q1E4|C7Q1E4_CATAD Ammonium transporter OS=Catenulispora acidiphila (strain DSM 44928 / JCM 14897 / NBRC 102108 / NRRL B-24433 / ID139908) OX=479433 GN=Caci_4812 PE=3 SV=1
Number of features: 0
Seq('MPSAFNSGDTAWVLASSAMVLLMTPALAFFYGGMVRAKSVLNMLMMNFIAIAVV...VST')
ID: tr|A0A2W5VAZ2|A0A2W5VAZ2_9CAUL
Name: tr|A0A2W5VAZ2|A0A2W5VAZ2_9CAUL
Description: tr|A0A2W5VAZ2|A0A2W5VAZ2_9CAUL Ammonium transporter OS=Caulobacter segnis OX=88688 GN=DI526_12590 PE=3 SV=1
Number of features: 0
Seq('MKLTFKPLAGLMLAATIAGAPLGATAFAQEAAPAPAAATAAPAEAAPAPAPAAT...YHS')
ID: tr|D5VJ32|D5VJ32_CAUST
Name: tr|D5VJ32|D5VJ32_CAUST
Description: tr|D5VJ32|D5VJ32_CAUST Ammonium transporter OS=Caulobacter segnis (strain ATCC 21756 / DSM 7131 / JCM 7823 / NBRC 15250 / LMG 17158 / TK0059) OX=509190 GN=Cseg_1635 PE=3 SV=1
Number of features: 0
Seq('MKLTFKPLAGLMLAATIAGAPLGATAFAQEAAPAAAAAAPAEAAPAPTAAAPAE...YHS')
ID: tr|K1LDP0|K1LDP0_9BACT
Name: tr|K1LDP0|K1LDP0_9BACT
Description: tr|K1LDP0|K1LDP0_9BACT Ammonium transporter OS=Cecembia lonarensis LW9 OX=1225176 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNQELFTINNLWVMVATLLVFVMHLGFASLEAGLTRAKNTVNILFKNTLIPAIG...PKD')
ID: tr|S3K1S2|S3K1S2_9ENTR
Name: tr|S3K1S2|S3K1S2_9ENTR
Description: tr|S3K1S2|S3K1S2_9ENTR Ammonium transporter OS=Cedecea davisae DSM 4568 OX=566551 GN=HMPREF0201_00872 PE=3 SV=1
Number of features: 0
Seq('MGKMKKLASLLGFGGLALLPSLALAADAAPAVADKADNAFMMISTALVLFMTIP...YNN')
ID: tr|D5UD26|D5UD26_CELFN
Name: tr|D5UD26|D5UD26_CELFN
Description: tr|D5UD26|D5UD26_CELFN Ammonium transporter OS=Cellulomonas flavigena (strain ATCC 482 / DSM 20109 / BCRC 11376 / JCM 18109 / NBRC 3775 / NCIMB 8073 / NRS 134) OX=446466 GN=Cfla_1465 PE=3 SV=1
Number of features: 0
Seq('MEWDTGAAAWMLTSASLVLLMTPGLAFFYGGMVRGKSVLNMMMMSFGAIGVVGV...EVK')
ID: tr|F0RHS0|F0RHS0_CELLC
Name: tr|F0RHS0|F0RHS0_CELLC
Description: tr|F0RHS0|F0RHS0_CELLC Ammonium transporter OS=Cellulophaga lytica (strain ATCC 23178 / DSM 7489 / JCM 8516 / NBRC 14961 / NCIMB 1423 / VKM B-1433 / Cy l20) OX=867900 GN=Celly_0344 PE=3 SV=1
Number of features: 0
Seq('MINEQQEALSKAVESINSDMGALWITIAAILVFFMQAGFTLVEVGFTRSKNSGN...TEK')
ID: tr|A0A1X7EED4|A0A1X7EED4_CELCE
Name: tr|A0A1X7EED4|A0A1X7EED4_CELCE
Description: tr|A0A1X7EED4|A0A1X7EED4_CELCE Ammonium transporter OS=Cellulosimicrobium cellulans J1 OX=903523 GN=SAMN02744115_02647 PE=3 SV=1
Number of features: 0
Seq('MVVAEVLGDGSALDAGNTAWMLVSASLVLLMTPGLAFFYGGMVRSKSVLNMMMM...VRA')
ID: tr|A0A4Y4DZN4|A0A4Y4DZN4_CELCE
Name: tr|A0A4Y4DZN4|A0A4Y4DZN4_CELCE
Description: tr|A0A4Y4DZN4|A0A4Y4DZN4_CELCE Ammonium transporter OS=Cellulosimicrobium cellulans OX=1710 GN=CCE02nite_28880 PE=3 SV=1
Number of features: 0
Seq('MEWDTGATAWMLTSASLVLLMTPGLAFFYGGMVRAKSVLNMMMMSFGAMAVVGV...VRA')
ID: tr|A0A1Y0HX98|A0A1Y0HX98_CELCE
Name: tr|A0A1Y0HX98|A0A1Y0HX98_CELCE
Description: tr|A0A1Y0HX98|A0A1Y0HX98_CELCE Ammonium transporter OS=Cellulosimicrobium cellulans OX=1710 GN=CBR64_16285 PE=3 SV=1
Number of features: 0
Seq('MEWDTGATAWMLTSASLVLLMTPGLAFFYGGMVRAKSVLNMMMMSFGAMAVVGV...VRA')
ID: tr|A0A516N903|A0A516N903_CELCE
Name: tr|A0A516N903|A0A516N903_CELCE
Description: tr|A0A516N903|A0A516N903_CELCE Ammonium transporter OS=Cellulosimicrobium cellulans OX=1710 GN=FOG94_09810 PE=3 SV=1
Number of features: 0
Seq('MEWDTGATAWMLTSASLVLLMTPGLAFFYGGMVRAKSVLNMMMMSFGAMAVVGV...VRA')
ID: tr|B3PIH2|B3PIH2_CELJU
Name: tr|B3PIH2|B3PIH2_CELJU
Description: tr|B3PIH2|B3PIH2_CELJU Ammonium transporter OS=Cellvibrio japonicus (strain Ueda107) OX=498211 GN=CJA_2112 PE=3 SV=1
Number of features: 0
Seq('MKKLNSMSISMLAGLCLSVLASGSMAQDTGINGANTAWVLTATALVLFMTLPGL...YKL')
ID: tr|B3PF77|B3PF77_CELJU
Name: tr|B3PF77|B3PF77_CELJU
Description: tr|B3PF77|B3PF77_CELJU Ammonium transporter OS=Cellvibrio japonicus (strain Ueda107) OX=498211 GN=CJA_3391 PE=3 SV=1
Number of features: 0
Seq('MEENLYHLQYAMDTFYFLVCGALVMWMAAGFAMLESGLVRAKNTTEILAKNVGM...RSK')
ID: tr|A0RUZ2|A0RUZ2_CENSY
Name: tr|A0RUZ2|A0RUZ2_CENSY
Description: tr|A0RUZ2|A0RUZ2_CENSY Ammonium transporter OS=Cenarchaeum symbiosum (strain A) OX=414004 GN=CENSYa_0526 PE=3 SV=1
Number of features: 0
Seq('MESISKRALILAAAVAIAATGAMSTAYSQTMEDDADGYDNRGLYTGNPNECWVD...TNE')
ID: tr|A0RXK8|A0RXK8_CENSY
Name: tr|A0RXK8|A0RXK8_CENSY
Description: tr|A0RXK8|A0RXK8_CENSY Ammonia permease OS=Cenarchaeum symbiosum (strain A) OX=414004 GN=CENSYa_1453 PE=3 SV=1
Number of features: 0
Seq('MKTKNHKYALMLVAAVAVTATGAMSTAYAQSVEDGMDGYVLGNSGIYTGNPNEC...VNE')
ID: tr|U7VB41|U7VB41_9FUSO
Name: tr|U7VB41|U7VB41_9FUSO
Description: tr|U7VB41|U7VB41_9FUSO Ammonium transporter OS=Cetobacterium somerae ATCC BAA-474 OX=1319815 GN=HMPREF0202_01748 PE=3 SV=1
Number of features: 0
Seq('MFQGVVHGNVAFMVIATVLVFFMTPGLAFFYGGLVEKKHSLTLMLQIFISIGVV...SDD')
ID: tr|Q2HD43|Q2HD43_CHAGB
Name: tr|Q2HD43|Q2HD43_CHAGB
Description: tr|Q2HD43|Q2HD43_CHAGB Ammonium transporter OS=Chaetomium globosum (strain ATCC 6205 / CBS 148.51 / DSM 1962 / NBRC 6347 / NRRL 1970) OX=306901 GN=CHGG_01861 PE=3 SV=1
Number of features: 0
Seq('MSTADDSSGNVGTDPTVHDLNAPFNAGDQAYIIVSAAMVLLMVPGIAFLYSGLA...PPQ')
ID: tr|Q2GX26|Q2GX26_CHAGB
Name: tr|Q2GX26|Q2GX26_CHAGB
Description: tr|Q2GX26|Q2GX26_CHAGB Ammonium transporter OS=Chaetomium globosum (strain ATCC 6205 / CBS 148.51 / DSM 1962 / NBRC 6347 / NRRL 1970) OX=306901 GN=CHGG_07478 PE=3 SV=1
Number of features: 0
Seq('MSTGPLTTYTGVTGVADPGGDSMTEDLNLYYSAGDFAWIMTSSALVLLMVPGVG...KTA')
ID: tr|A0A5C6LWQ1|A0A5C6LWQ1_9BACT
Name: tr|A0A5C6LWQ1|A0A5C6LWQ1_9BACT
Description: tr|A0A5C6LWQ1|A0A5C6LWQ1_9BACT Ammonium transporter OS=Chitinophaga pinensis OX=79329 GN=FEF09_03740 PE=3 SV=1
Number of features: 0
Seq('MKKTSFQDYLPFIVLALIAIFALFIPGELPFADPEGKYNYGDIAWILVASCLVF...MAH')
ID: tr|A0A979GQ79|A0A979GQ79_CHIPD
Name: tr|A0A979GQ79|A0A979GQ79_CHIPD
Description: tr|A0A979GQ79|A0A979GQ79_CHIPD Ammonium transporter OS=Chitinophaga pinensis (strain ATCC 43595 / DSM 2588 / LMG 13176 / NBRC 15968 / NCIMB 11800 / UQM 2034) OX=485918 GN=Cpin_0541 PE=3 SV=1
Number of features: 0
Seq('MKKTSFQDYLPFIVLALVAIVALFVPGELPFADPEGKYNYGDIAWILVASCLVF...MAH')
ID: tr|Q8LRM4|Q8LRM4_CHLRE
Name: tr|Q8LRM4|Q8LRM4_CHLRE
Description: tr|Q8LRM4|Q8LRM4_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 PE=2 SV=1
Number of features: 0
Seq('MASPAPSGSPPLVIYSCTDEQMLEVTELVGDSATAAIVCSQYDCSFTAVSCVLK...GYD')
ID: tr|Q8LRM5|Q8LRM5_CHLRE
Name: tr|Q8LRM5|Q8LRM5_CHLRE
Description: tr|Q8LRM5|Q8LRM5_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 PE=3 SV=1
Number of features: 0
Seq('MASPAPSGSPPLVIYSCTDEQMLEVTELVGDSATAAIVCSQYDCSFTAVSCVLK...GYD')
ID: tr|A0A2K3DWA2|A0A2K3DWA2_CHLRE
Name: tr|A0A2K3DWA2|A0A2K3DWA2_CHLRE
Description: tr|A0A2K3DWA2|A0A2K3DWA2_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 GN=CHLRE_03g159254v5 PE=3 SV=1
Number of features: 0
Seq('MSGDFGSEPLGSCSVETVTALLGYGLEQDSITALCQPEGGAGCTSTDNCMFQYL...SIP')
ID: tr|A8HSA2|A8HSA2_CHLRE
Name: tr|A8HSA2|A8HSA2_CHLRE
Description: tr|A8HSA2|A8HSA2_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 GN=CHLRE_13g569850v5 PE=3 SV=1
Number of features: 0
Seq('MADEMDPMTACITALTDAAMTTAQATALCGQFAFAADNSDLSDRLDQTNQGLNT...LGL')

ID: tr|A0A2K3DQF8|A0A2K3DQF8_CHLRE
Name: tr|A0A2K3DQF8|A0A2K3DQF8_CHLRE
Description: tr|A0A2K3DQF8|A0A2K3DQF8_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 GN=CHLRE_06g293051v5 PE=3 SV=1
Number of features: 0
Seq('MDGTAKAEVALSLDVAFLLFSAYLVFGPMQLGFALLCAGAIRSKNSMNVLMKNI...IAQ')
ID: tr|Q6QH01|Q6QH01_CHLRE
Name: tr|Q6QH01|Q6QH01_CHLRE
Description: tr|Q6QH01|Q6QH01_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 GN=Amt1-4 PE=2 SV=1
Number of features: 0
Seq('MADEMDPMTACITALTDAAMTTAQATALCGQFAFAADNSDLSDRLDQTNQGLNT...LGL')
ID: tr|Q8RUT6|Q8RUT6_CHLRE
Name: tr|Q8RUT6|Q8RUT6_CHLRE
Description: tr|Q8RUT6|Q8RUT6_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 GN=Amt1;1 PE=2 SV=1
Number of features: 0
Seq('MSGDFGSEPLGSCSVETVTALLGYGLEQDSITALCQPEGGAGCTSTDNCMFQYL...GKA')
ID: tr|Q8LJU0|Q8LJU0_CHLRE
Name: tr|Q8LJU0|Q8LJU0_CHLRE
Description: tr|Q8LJU0|Q8LJU0_CHLRE Ammonium transporter OS=Chlamydomonas reinhardtii OX=3055 PE=2 SV=2
Number of features: 0
Seq('MSEACLLAAKSALVGVANGDSLASAICAAMEAAAPVARHLQETTVDLTTLQETV...VTA')
ID: tr|A0A2K3DPU7|A0A2K3DPU7_CHLRE
Name: tr|A0A2K3DPU7|A0A2K3DPU7_CHLRE
Description: tr|A0A2K3DPU7|A0A2K3DPU7_CHLRE Ammonium transporter AmtB-like domain-containing protein OS=Chlamydomonas reinhardtii OX=3055 GN=CHLRE_06g284150v5 PE=4 SV=1
Number of features: 0
Seq('MLSRRRSVSTRLRFFSVSRLRVIHIMSSVLKIPTAMASGAASRRHSLDWSHVGL...NNV')
ID: tr|Q8RUE9|Q8RUE9_CHLRE
Name: tr|Q8RUE9|Q8RUE9_CHLRE
Description: tr|Q8RUE9|Q8RUE9_CHLRE Rh protein homolog-2 OS=Chlamydomonas reinhardtii OX=3055 GN=Rhp-2 PE=2 SV=1
Number of features: 0
Seq('MSSVLKIPTAMASGAASRRHSLDWSHVGLPPREPQLRTGFAPSVIAIAAVIVGL...NNV')
ID: tr|Q8S2R6|Q8S2R6_CHLRE
Name: tr|Q8S2R6|Q8S2R6_CHLRE
Description: tr|Q8S2R6|Q8S2R6_CHLRE Rh2 protein OS=Chlamydomonas reinhardtii OX=3055 PE=2 SV=1
Number of features: 0
Seq('MSSVLKIPTAMASGAASRRHSLDWSHVGLPPREPQLRTGFAPSVIAIAAVIVGL...NNV')
ID: tr|Q94CJ2|Q94CJ2_CHLRE
Name: tr|Q94CJ2|Q94CJ2_CHLRE
Description: tr|Q94CJ2|Q94CJ2_CHLRE Rh protein OS=Chlamydomonas reinhardtii OX=3055 GN=CHLRE_06g284100v5 PE=2 SV=1
Number of features: 0
Seq('MQALPPKIPASVSGHGTQSRRHSLDWSHIGLPSRETQLRAGFVPSAAVVIVIFV...GNV')
ID: tr|A0A7C5DH83|A0A7C5DH83_9CHLB
Name: tr|A0A7C5DH83|A0A7C5DH83_9CHLB
Description: tr|A0A7C5DH83|A0A7C5DH83_9CHLB Ammonium transporter OS=Chlorobaculum parvum OX=274539 GN=ENL07_08100 PE=3 SV=1
Number of features: 0
Seq('MGKRLRASLLALLAVMMAHQTGWAAESVASDTGTTSWMLTSTALVLLMVPGLAM...NPN')
ID: tr|B3QRJ4|B3QRJ4_CHLP8
Name: tr|B3QRJ4|B3QRJ4_CHLP8
Description: tr|B3QRJ4|B3QRJ4_CHLP8 Ammonium transporter OS=Chlorobaculum parvum (strain DSM 263 / NCIMB 8327) OX=517417 GN=Cpar_0088 PE=3 SV=1
Number of features: 0
Seq('MFMGNKLRSSLLVLFALMMAHNTGWAAESVTSDTGTTSWMLTSTALVLLMVPGL...NPN')
ID: tr|Q3AP28|Q3AP28_CHLCH
Name: tr|Q3AP28|Q3AP28_CHLCH
Description: tr|Q3AP28|Q3AP28_CHLCH Ammonium transporter OS=Chlorobium chlorochromatii (strain CaD3) OX=340177 GN=Cag_1999 PE=3 SV=1
Number of features: 0
Seq('MKHKHLTALLMLGALLLTGGNAWAADEVVTDSGTTSWMLTSTALVLLMIPGLAM...NLN')
ID: tr|A9WHW6|A9WHW6_CHLAA
Name: tr|A9WHW6|A9WHW6_CHLAA
Description: tr|A9WHW6|A9WHW6_CHLAA Ammonium transporter OS=Chloroflexus aurantiacus (strain ATCC 29366 / DSM 635 / J-10-fl) OX=324602 GN=Caur_1002 PE=3 SV=1
Number of features: 0
Seq('MKLAWRTKIGLGLGFGLGLWLVGTGRAFAQEGPTTAELAVAMNTFFLIVAAALV...LAR')
ID: tr|B3QVV5|B3QVV5_CHLT3
Name: tr|B3QVV5|B3QVV5_CHLT3
Description: tr|B3QVV5|B3QVV5_CHLT3 Ammonium transporter OS=Chloroherpeton thalassium (strain ATCC 35110 / GB-78) OX=517418 GN=Ctha_0693 PE=3 SV=1
Number of features: 0
Seq('MKKYWSIPLGLLLMVSLYGAVVPHVPQSVTGGDIVPGDVAWMLTATALVLLMTP...SMN')
ID: tr|A0A017SYR8|A0A017SYR8_9BACT
Name: tr|A0A017SYR8|A0A017SYR8_9BACT
Description: tr|A0A017SYR8|A0A017SYR8_9BACT Ammonium transporter OS=Chondromyces apiculatus DSM 436 OX=1192034 GN=CAP_7454 PE=3 SV=1
Number of features: 0
Seq('MQIDSGDTAWLLVSTALVLFMTPGLALFYGGMVRRKNVLSTLMHAFAALGVISL...YAL')
ID: tr|A0A202B535|A0A202B535_CHRVL
Name: tr|A0A202B535|A0A202B535_CHRVL
Description: tr|A0A202B535|A0A202B535_CHRVL Ammonium transporter OS=Chromobacterium violaceum OX=536 GN=CBW21_17860 PE=3 SV=1
Number of features: 0
Seq('MKKILAAMASGLAALSLPALADAPAGPAVAAAKVINSGDTAWMLTSTALVLFMT...RVE')
ID: tr|A0A381KRM8|A0A381KRM8_CHRVL
Name: tr|A0A381KRM8|A0A381KRM8_CHRVL
Description: tr|A0A381KRM8|A0A381KRM8_CHRVL Ammonium transporter OS=Chromobacterium violaceum OX=536 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKILAAMASGLAALSLPALADAPAGPAVAAAKVINSGDTAWMLTSTALVLFMT...RVE')
ID: tr|Q7NQY2|Q7NQY2_CHRVO
Name: tr|Q7NQY2|Q7NQY2_CHRVO
Description: tr|Q7NQY2|Q7NQY2_CHRVO Ammonium transporter OS=Chromobacterium violaceum (strain ATCC 12472 / DSM 30191 / JCM 1249 / NBRC 12614 / NCIMB 9131 / NCTC 9757) OX=243365 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKILAAMASGLAALSLPALADAPAGPAVAAAKVINSGDTAWMLTSTALVLFMT...RVE')
ID: tr|A0A7Y8VM35|A0A7Y8VM35_CHRSL
Name: tr|A0A7Y8VM35|A0A7Y8VM35_CHRSL
Description: tr|A0A7Y8VM35|A0A7Y8VM35_CHRSL Ammonium transporter OS=Chromohalobacter salexigens OX=158080 GN=HLV40_08945 PE=3 SV=1
Number of features: 0
Seq('MTEDITQLSYALDTFYFLVCAVLVMWMAAGFAMLEAGLVRAKNTAEILTKNVVL...GKK')
ID: tr|A0A317R456|A0A317R456_CHRSL
Name: tr|A0A317R456|A0A317R456_CHRSL
Description: tr|A0A317R456|A0A317R456_CHRSL Ammonium transporter OS=Chromohalobacter salexigens OX=158080 GN=DFO74_108122 PE=3 SV=1
Number of features: 0
Seq('MTEDITQLSYALDTFYFLVCAVLVMWMAAGFAMLEAGLVRAKNTAEILTKNVVL...GKK')
ID: tr|Q1QSQ2|Q1QSQ2_CHRSD
Name: tr|Q1QSQ2|Q1QSQ2_CHRSD
Description: tr|Q1QSQ2|Q1QSQ2_CHRSD Ammonium transporter OS=Chromohalobacter salexigens (strain ATCC BAA-138 / DSM 3043 / CIP 106854 / NCIMB 13768 / 1H11) OX=290398 GN=Csal_3162 PE=3 SV=1
Number of features: 0
Seq('MTEDITQLSYALDTFYFLVCAVLVMWMAAGFAMLEAGLVRAKNTAEILTKNVVL...GKK')
ID: tr|K9U8C7|K9U8C7_CHRTP
Name: tr|K9U8C7|K9U8C7_CHRTP
Description: tr|K9U8C7|K9U8C7_CHRTP Ammonium transporter OS=Chroococcidiopsis thermalis (strain PCC 7203) OX=251229 GN=Chro_5509 PE=3 SV=1
Number of features: 0
Seq('MMLKLRPKNKRRINRKRLPAAGMKRLSQHTSLFTQLKLAVKRLSPSWQACIPLT...NPY')
ID: tr|B4CV94|B4CV94_9BACT
Name: tr|B4CV94|B4CV94_9BACT
Description: tr|B4CV94|B4CV94_9BACT Ammonium transporter OS=Chthoniobacter flavus Ellin428 OX=497964 GN=CfE428DRAFT_0032 PE=3 SV=1
Number of features: 0
Seq('MLEAYLTNGDPTVPLKTGPKDKDGNPTLPPEWAKLSADALAAAAPSTATSGPGH...GYI')
ID: tr|B4D7W2|B4D7W2_9BACT
Name: tr|B4D7W2|B4D7W2_9BACT
Description: tr|B4D7W2|B4D7W2_9BACT Ammonium transporter OS=Chthoniobacter flavus Ellin428 OX=497964 GN=CfE428DRAFT_5002 PE=3 SV=1
Number of features: 0
Seq('MTHTTRSGRCAWLFAAAFACLGATLHAQAPGAPSKIDSGDNAWMLTSAALVLMM...YNQ')
ID: tr|S0ET45|S0ET45_CHTCT
Name: tr|S0ET45|S0ET45_CHTCT
Description: tr|S0ET45|S0ET45_CHTCT Ammonium transporter OS=Chthonomonas calidirosea (strain DSM 23976 / ICMP 18418 / T49) OX=1303518 GN=CCALI_00383 PE=3 SV=1
Number of features: 0
Seq('MFHKFIKSNTQIALTAATTLLIILLANANACAQPPTPSSPAINTGDTAWMLVAA...MAE')
ID: tr|S0EUS1|S0EUS1_CHTCT
Name: tr|S0EUS1|S0EUS1_CHTCT
Description: tr|S0EUS1|S0EUS1_CHTCT Ammonium transporter OS=Chthonomonas calidirosea (strain DSM 23976 / ICMP 18418 / T49) OX=1303518 GN=CCALI_01636 PE=3 SV=1
Number of features: 0
Seq('MTTYLSRFRVCWTRTALLLGLFGVIFALCAHTAAWAQTVKPDPGGTNTGTYADV...GAK')
ID: tr|A0A482PLH3|A0A482PLH3_CITRO
Name: tr|A0A482PLH3|A0A482PLH3_CITRO
Description: tr|A0A482PLH3|A0A482PLH3_CITRO Ammonium transporter OS=Citrobacter rodentium OX=67825 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATMRTGLATLAMLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|D2TLS8|D2TLS8_CITRI
Name: tr|D2TLS8|D2TLS8_CITRI
Description: tr|D2TLS8|D2TLS8_CITRI Ammonium transporter OS=Citrobacter rodentium (strain ICC168) OX=637910 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATMRTGLATLAMLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A251Y3N4|A0A251Y3N4_9MICO
Name: tr|A0A251Y3N4|A0A251Y3N4_9MICO
Description: tr|A0A251Y3N4|A0A251Y3N4_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A251YU48|A0A251YU48_9MICO
Name: tr|A0A251YU48|A0A251YU48_9MICO
Description: tr|A0A251YU48|A0A251YU48_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A251Z278|A0A251Z278_9MICO
Name: tr|A0A251Z278|A0A251Z278_9MICO
Description: tr|A0A251Z278|A0A251Z278_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')

ID: tr|A0A251YFS0|A0A251YFS0_9MICO
Name: tr|A0A251YFS0|A0A251YFS0_9MICO
Description: tr|A0A251YFS0|A0A251YFS0_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A251XJT0|A0A251XJT0_CLAMM
Name: tr|A0A251XJT0|A0A251XJT0_CLAMM
Description: tr|A0A251XJT0|A0A251XJT0_CLAMM Ammonium transporter OS=Clavibacter michiganensis subsp. michiganensis OX=33013 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A399NT81|A0A399NT81_9MICO
Name: tr|A0A399NT81|A0A399NT81_9MICO
Description: tr|A0A399NT81|A0A399NT81_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A5CRL2|A5CRL2_CLAM3
Name: tr|A5CRL2|A5CRL2_CLAM3
Description: tr|A5CRL2|A5CRL2_CLAM3 Ammonium transporter OS=Clavibacter michiganensis subsp. michiganensis (strain NCPPB 382) OX=443906 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A251XU71|A0A251XU71_9MICO
Name: tr|A0A251XU71|A0A251XU71_9MICO
Description: tr|A0A251XU71|A0A251XU71_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A399QCH4|A0A399QCH4_9MICO
Name: tr|A0A399QCH4|A0A399QCH4_9MICO
Description: tr|A0A399QCH4|A0A399QCH4_9MICO Ammonium transporter OS=Clavibacter michiganensis subsp. nebraskensis OX=31963 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|M5B925|M5B925_9MICO
Name: tr|M5B925|M5B925_9MICO
Description: tr|M5B925|M5B925_9MICO Ammonium transporter OS=Clavibacter michiganensis subsp. nebraskensis NCPPB 2581 OX=1097677 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A0D5CI78|A0A0D5CI78_9MICO
Name: tr|A0A0D5CI78|A0A0D5CI78_9MICO
Description: tr|A0A0D5CI78|A0A0D5CI78_9MICO Ammonium transporter OS=Clavibacter michiganensis subsp. insidiosus OX=33014 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLACFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGH')
ID: tr|A0A399NMH5|A0A399NMH5_9MICO
Name: tr|A0A399NMH5|A0A399NMH5_9MICO
Description: tr|A0A399NMH5|A0A399NMH5_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=DZF95_01220 PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A2S5VFE3|A0A2S5VFE3_9MICO
Name: tr|A0A2S5VFE3|A0A2S5VFE3_9MICO
Description: tr|A0A2S5VFE3|A0A2S5VFE3_9MICO Ammonium transporter OS=Clavibacter michiganensis OX=28447 GN=C5C13_00485 PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A0M5JZH4|A0A0M5JZH4_9MICO
Name: tr|A0A0M5JZH4|A0A0M5JZH4_9MICO
Description: tr|A0A0M5JZH4|A0A0M5JZH4_9MICO Ammonium transporter OS=Clavibacter michiganensis subsp. capsici OX=1874630 GN=GW571_08095 PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A225CMT8|A0A225CMT8_9MICO
Name: tr|A0A225CMT8|A0A225CMT8_9MICO
Description: tr|A0A225CMT8|A0A225CMT8_9MICO Ammonium transporter OS=Clavibacter michiganensis subsp. tessellarius OX=31965 GN=B5P24_12240 PE=3 SV=1
Number of features: 0
Seq('MDQGNTAFLLIAAALVLLMTPGLAFFYGGLVKAKSVISMMMMSFGAMGLIGLLW...SGR')
ID: tr|A0A202G7R7|A0A202G7R7_CLALS
Name: tr|A0A202G7R7|A0A202G7R7_CLALS
Description: tr|A0A202G7R7|A0A202G7R7_CLALS Ammonium transporter OS=Clavispora lusitaniae OX=36911 GN=EJF15_30612 PE=3 SV=1
Number of features: 0
Seq('MLPSKRKLFTENEEYNESYVLLFTIASSMIWIMVPGLAFLYSGLARRKSALSMI...KQD')
ID: tr|A0A5Q0IBT9|A0A5Q0IBT9_CLALS
Name: tr|A0A5Q0IBT9|A0A5Q0IBT9_CLALS
Description: tr|A0A5Q0IBT9|A0A5Q0IBT9_CLALS Putative ammonium transporter OS=Clavispora lusitaniae OX=36911 GN=EJF15_80092 PE=3 SV=1
Number of features: 0
Seq('MTQAFDAKGAVDTLYMFSCTLLLFSVVFGLSLFYSGLIQRRSSFTMLAIPMFLA...RSA')
ID: tr|C4Y298|C4Y298_CLAL4
Name: tr|C4Y298|C4Y298_CLAL4
Description: tr|C4Y298|C4Y298_CLAL4 Ammonium transporter OS=Clavispora lusitaniae (strain ATCC 42720) OX=306902 GN=CLUG_02661 PE=3 SV=1
Number of features: 0
Seq('MLPSKRKLFTENEEYNESYVLLFTIASSMIWIMVPGLAFLYSGLARRKSALSMI...KQD')
ID: tr|C4YC30|C4YC30_CLAL4
Name: tr|C4YC30|C4YC30_CLAL4
Description: tr|C4YC30|C4YC30_CLAL4 Ammonium transporter AmtB-like domain-containing protein OS=Clavispora lusitaniae (strain ATCC 42720) OX=306902 GN=CLUG_05847 PE=3 SV=1
Number of features: 0
Seq('MTQAFDAKGAVDTLYMFSCTLLLFSVVFGLSLFYSGLIQRRSSFTMLAIPMFLA...RSA')
ID: tr|Q97L80|Q97L80_CLOAB
Name: tr|Q97L80|Q97L80_CLOAB
Description: tr|Q97L80|Q97L80_CLOAB Ammonium transporter OS=Clostridium acetobutylicum (strain ATCC 824 / DSM 792 / JCM 1419 / LMG 5710 / VKM B-1787) OX=272562 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MNFADTTFVFLSTVLVMIMTPALAMFYGGMVKTKNTLGTMMHSYACMIIVSLQW...HID')
ID: tr|A6LV49|A6LV49_CLOB8
Name: tr|A6LV49|A6LV49_CLOB8
Description: tr|A6LV49|A6LV49_CLOB8 Ammonium transporter OS=Clostridium beijerinckii (strain ATCC 51743 / NCIMB 8052) OX=290402 GN=Cbei_2061 PE=3 SV=1
Number of features: 0
Seq('MEINLGDCSFILICSALVLLMTPGLAFFYGGMVRRKNVLNTLMSSFFVCGLASI...GLD')
ID: tr|A6M3G0|A6M3G0_CLOB8
Name: tr|A6M3G0|A6M3G0_CLOB8
Description: tr|A6M3G0|A6M3G0_CLOB8 Ammonium transporter OS=Clostridium beijerinckii (strain ATCC 51743 / NCIMB 8052) OX=290402 GN=Cbei_5034 PE=3 SV=1
Number of features: 0
Seq('MEINFGDSSFILICSALVLLMTPGLAFFYGGMVRRKNVLNTLMSSFFICGLASV...GLD')
ID: tr|A6LRS5|A6LRS5_CLOB8
Name: tr|A6LRS5|A6LRS5_CLOB8
Description: tr|A6LRS5|A6LRS5_CLOB8 Ammonium transporter OS=Clostridium beijerinckii (strain ATCC 51743 / NCIMB 8052) OX=290402 GN=Cbei_0871 PE=3 SV=1
Number of features: 0
Seq('MELLNGADMGFVIISAALVMLMVPGLALFYGGMVKSKNVLSITVHSYAALVIIS...LNM')
ID: tr|A0A4V5PX72|A0A4V5PX72_COBMA
Name: tr|A0A4V5PX72|A0A4V5PX72_COBMA
Description: tr|A0A4V5PX72|A0A4V5PX72_COBMA Ammonium transporter OS=Cobetia marina OX=28258 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNEIIEVKYALDTFYFLVCGALVLWMAAGFAMLEAGLVRAKNTTEILTKNVALF...SRK')
ID: tr|A0A4U1M1R6|A0A4U1M1R6_COBMA
Name: tr|A0A4U1M1R6|A0A4U1M1R6_COBMA
Description: tr|A0A4U1M1R6|A0A4U1M1R6_COBMA Ammonium transporter OS=Cobetia marina OX=28258 GN=FBG13_02145 PE=3 SV=1
Number of features: 0
Seq('MDRKPLTTALADNNKGETLVNIDVLQLSYALDTFYFLMCTALVMFMACGFAMLE...AAR')
ID: tr|A0A4U1LV47|A0A4U1LV47_COBMA
Name: tr|A0A4U1LV47|A0A4U1LV47_COBMA
Description: tr|A0A4U1LV47|A0A4U1LV47_COBMA Ammonium transporter OS=Cobetia marina OX=28258 GN=FBG13_12850 PE=4 SV=1
Number of features: 0
Seq('MDEKTLQSILDMHQAMNIEVFYWWCTAIMFLIHAGFLAYEIGASRSKNALASGM...DIS')
ID: tr|A0A3T0KAE2|A0A3T0KAE2_9GAMM
Name: tr|A0A3T0KAE2|A0A3T0KAE2_9GAMM
Description: tr|A0A3T0KAE2|A0A3T0KAE2_9GAMM Ammonium transporter OS=Cobetia sp. ICG0124 OX=2053669 GN=CU110_15165 PE=3 SV=1
Number of features: 0
Seq('MNEIIEVKYALDTFYFLVCGALVLWMAAGFAMLEAGLVRAKNTTEILTKNVALF...SRK')
ID: tr|A0A3T0K738|A0A3T0K738_9GAMM
Name: tr|A0A3T0K738|A0A3T0K738_9GAMM
Description: tr|A0A3T0K738|A0A3T0K738_9GAMM Ammonium transporter OS=Cobetia sp. ICG0124 OX=2053669 GN=CU110_09265 PE=3 SV=1
Number of features: 0
Seq('MDRKPLTKALANNNKGETLVNIDVLQLSYALDTFYFLMCTALVMFMACGFAMLE...AAR')
ID: tr|A0A3T0K667|A0A3T0K667_9GAMM
Name: tr|A0A3T0K667|A0A3T0K667_9GAMM
Description: tr|A0A3T0K667|A0A3T0K667_9GAMM Ammonium transporter OS=Cobetia sp. ICG0124 OX=2053669 GN=CU110_06625 PE=4 SV=1
Number of features: 0
Seq('MDEKTLQSILDMHQAMNIEVFYWWCTAIMFLIHAGFLAYEIGASRSKNALASGM...DIS')
ID: tr|A0A2G5BGA9|A0A2G5BGA9_COERN
Name: tr|A0A2G5BGA9|A0A2G5BGA9_COERN
Description: tr|A0A2G5BGA9|A0A2G5BGA9_COERN Ammonium transporter OS=Coemansia reversa (strain ATCC 12441 / NRRL 1564) OX=763665 GN=COEREDRAFT_80000 PE=3 SV=1
Number of features: 0
Seq('MVQLLKRLDTDESHINGSDTSWILVSAALVFIMSPGVGYFYSGMARSKNAVSMV...TST')
ID: tr|A0A2G5BI87|A0A2G5BI87_COERN
Name: tr|A0A2G5BI87|A0A2G5BI87_COERN
Description: tr|A0A2G5BI87|A0A2G5BI87_COERN Ammonium transporter OS=Coemansia reversa (strain ATCC 12441 / NRRL 1564) OX=763665 GN=COEREDRAFT_85192 PE=3 SV=1
Number of features: 0
Seq('MATNINDIDMGATVWMIASTALVFLMIPGLGYFYGGMVRSKNALSLVFLCMMAL...YPL')

ID: tr|A0A127PIQ9|A0A127PIQ9_9BURK
Name: tr|A0A127PIQ9|A0A127PIQ9_9BURK
Description: tr|A0A127PIQ9|A0A127PIQ9_9BURK Ammonium transporter OS=Collimonas fungivorans OX=158899 GN=amt PE=3 SV=1
Number of features: 0
Seq('MNIKSTFATILAACTLIAATSMLPASAADEPSASASASVAAASADAPAAAPAAV...YHD')
ID: tr|G0AFH4|G0AFH4_COLFT
Name: tr|G0AFH4|G0AFH4_COLFT
Description: tr|G0AFH4|G0AFH4_COLFT Ammonium transporter OS=Collimonas fungivorans (strain Ter331) OX=1005048 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MPASAADEPSASASASVAAASADAPAAASAAVAAAPAASAPAAAAPAASAPAAA...YHD')
ID: tr|A0A1Y5E3E3|A0A1Y5E3E3_COLPS
Name: tr|A0A1Y5E3E3|A0A1Y5E3E3_COLPS
Description: tr|A0A1Y5E3E3|A0A1Y5E3E3_COLPS Ammonium transporter OS=Colwellia psychrerythraea OX=28229 GN=A9Q75_17915 PE=3 SV=1
Number of features: 0
Seq('METTMSKALILCLTLLSFFISGTAWADEGQLNGANTSWILTSTALVLLMTLPGV...YHL')
ID: tr|A0A099KL22|A0A099KL22_COLPS
Name: tr|A0A099KL22|A0A099KL22_COLPS
Description: tr|A0A099KL22|A0A099KL22_COLPS Ammonium transporter OS=Colwellia psychrerythraea OX=28229 GN=ND2E_3471 PE=3 SV=1
Number of features: 0
Seq('MVRYGTVLMHGVFNVLKLNVLFFGLFCALFMTVIELFTMETTMSKALILCLTLL...YYL')
ID: tr|Q47X17|Q47X17_COLP3
Name: tr|Q47X17|Q47X17_COLP3
Description: tr|Q47X17|Q47X17_COLP3 Ammonium transporter OS=Colwellia psychrerythraea (strain 34H / ATCC BAA-681) OX=167879 GN=amt PE=3 SV=1
Number of features: 0
Seq('MSVIELFTMETTMSKALILCLTLLSFFISGTAWAEEGQLNGANTSWILTSTALV...YHL')
ID: tr|A0A1Y5E8I7|A0A1Y5E8I7_COLPS
Name: tr|A0A1Y5E8I7|A0A1Y5E8I7_COLPS
Description: tr|A0A1Y5E8I7|A0A1Y5E8I7_COLPS Ammonium transporter OS=Colwellia psychrerythraea OX=28229 GN=A9Q75_12675 PE=3 SV=1
Number of features: 0
Seq('MEQNIFQLQYALDTFYFLMCGALVMWMAAGFSMLEAGLVRAKNTTEILTKNVAL...TRG')
ID: tr|A0A099KEY7|A0A099KEY7_COLPS
Name: tr|A0A099KEY7|A0A099KEY7_COLPS
Description: tr|A0A099KEY7|A0A099KEY7_COLPS Putative ammonium transporter, marine subtype OS=Colwellia psychrerythraea OX=28229 GN=ND2E_0163 PE=3 SV=1
Number of features: 0
Seq('MEQNIFQLQYALDTFYFLMCGALVMWMAAGFSMLEAGLVRAKNTTEILTKNVSL...TRG')
ID: tr|A0A099KW74|A0A099KW74_COLPS
Name: tr|A0A099KW74|A0A099KW74_COLPS
Description: tr|A0A099KW74|A0A099KW74_COLPS Putative ammonium transporter, marine subtype OS=Colwellia psychrerythraea OX=28229 GN=GAB14E_2223 PE=3 SV=1
Number of features: 0
Seq('MEQNIFQLQYALDTFYFLMCGALVMWMAAGFSMLEAGLVRAKNTTEILTKNVAL...TRG')
ID: tr|Q488X2|Q488X2_COLP3
Name: tr|Q488X2|Q488X2_COLP3
Description: tr|Q488X2|Q488X2_COLP3 Putative ammonium transporter OS=Colwellia psychrerythraea (strain 34H / ATCC BAA-681) OX=167879 GN=CPS_0642 PE=3 SV=1
Number of features: 0
Seq('MEQNIFQLQYALDTFYFLICGALVMWMAAGFSMLEAGLVRAKNTTEILTKNVAL...TRG')
ID: tr|A0A1Y1J9V1|A0A1Y1J9V1_COMTE
Name: tr|A0A1Y1J9V1|A0A1Y1J9V1_COMTE
Description: tr|A0A1Y1J9V1|A0A1Y1J9V1_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=CTR2_4614 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGVTGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A373FQ71|A0A373FQ71_COMTE
Name: tr|A0A373FQ71|A0A373FQ71_COMTE
Description: tr|A0A373FQ71|A0A373FQ71_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTKKLLSAGLGLGLLAAGASAFAQEGAAAAAAAAPAVAAAVEAVPTLSAGDTAW...YTR')
ID: tr|A0A076PL76|A0A076PL76_COMTE
Name: tr|A0A076PL76|A0A076PL76_COMTE
Description: tr|A0A076PL76|A0A076PL76_COMTE Ammonium transporter OS=Comamonas testosteroni TK102 OX=1392005 GN=O987_00985 PE=3 SV=1
Number of features: 0
Seq('MTKKLLSAGLGLGLLAASAAGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A5A7MAJ9|A0A5A7MAJ9_COMTE
Name: tr|A0A5A7MAJ9|A0A5A7MAJ9_COMTE
Description: tr|A0A5A7MAJ9|A0A5A7MAJ9_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGATGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A096FEE6|A0A096FEE6_COMTE
Name: tr|A0A096FEE6|A0A096FEE6_COMTE
Description: tr|A0A096FEE6|A0A096FEE6_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=GL58_16250 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAASATGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A8B4RWH8|A0A8B4RWH8_COMTE
Name: tr|A0A8B4RWH8|A0A8B4RWH8_COMTE
Description: tr|A0A8B4RWH8|A0A8B4RWH8_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=amtB_1 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGATGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|D0IWD0|D0IWD0_COMT2
Name: tr|D0IWD0|D0IWD0_COMT2
Description: tr|D0IWD0|D0IWD0_COMT2 Ammonium transporter OS=Comamonas testosteroni (strain CNB-2) OX=688245 GN=CtCNB1_0202 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGVTGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|B7X047|B7X047_COMTK
Name: tr|B7X047|B7X047_COMTK
Description: tr|B7X047|B7X047_COMTK Ammonium transporter OS=Comamonas testosteroni (strain DSM 14576 / KF-1) OX=399795 GN=CtesDRAFT_PD4903 PE=3 SV=1
Number of features: 0
Seq('MTKKLLSAGLGLGLLAASAAGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A096EEV9|A0A096EEV9_9BURK
Name: tr|A0A096EEV9|A0A096EEV9_9BURK
Description: tr|A0A096EEV9|A0A096EEV9_9BURK Ammonium transporter OS=Comamonas thiooxydans OX=363952 GN=P245_24000 PE=3 SV=1
Number of features: 0
Seq('MKKLLSAGLGLGLLAAGATGFAQEAATAAAAAAPVAEAAAEAVPTLSAGDTAWM...YTR')
ID: tr|A0A0E3BR91|A0A0E3BR91_9BURK
Name: tr|A0A0E3BR91|A0A0E3BR91_9BURK
Description: tr|A0A0E3BR91|A0A0E3BR91_9BURK Ammonium transporter OS=Comamonas thiooxydans OX=363952 GN=P608_18985 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGATGFAQEAATAAAAAPVAEAAAEAVPTLSAGDTAWM...YTR')
ID: tr|A0A7U9A2V9|A0A7U9A2V9_9BURK
Name: tr|A0A7U9A2V9|A0A7U9A2V9_9BURK
Description: tr|A0A7U9A2V9|A0A7U9A2V9_9BURK Ammonium transporter OS=Comamonas thiooxydans OX=363952 GN=CTS44_23431 PE=3 SV=1
Number of features: 0
Seq('MIKKLLSAGLGLGLLAAGATGFAQEAATAAAAAAPMAEAAAEAVPTLSAGDTAW...YTR')
ID: tr|A0A373FQ83|A0A373FQ83_COMTE
Name: tr|A0A373FQ83|A0A373FQ83_COMTE
Description: tr|A0A373FQ83|A0A373FQ83_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=DZC30_03665 PE=3 SV=1
Number of features: 0
Seq('MELVPLTAIDKADTAWVMTSAALVLLMTLPGIALFYAGLVRRKNVVNTMAAVFA...RQH')
ID: tr|A0A1Y1JBP5|A0A1Y1JBP5_COMTE
Name: tr|A0A1Y1JBP5|A0A1Y1JBP5_COMTE
Description: tr|A0A1Y1JBP5|A0A1Y1JBP5_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=CTR2_4151 PE=3 SV=1
Number of features: 0
Seq('MQALKQGADALFILMGAVMVLAMHAGFAFLELGTVRRKNQVNALVKILVDFSVS...ANW')
ID: tr|A0A5A7MBN6|A0A5A7MBN6_COMTE
Name: tr|A0A5A7MBN6|A0A5A7MBN6_COMTE
Description: tr|A0A5A7MBN6|A0A5A7MBN6_COMTE Ammonium transporter OS=Comamonas testosteroni OX=285 GN=CTTA_1955 PE=3 SV=1
Number of features: 0
Seq('MEMVPLTAIDKADTGWVMVASALVLLMTLPGIALFYAGLVRRKNVVNTMVAVFA...RQH')
ID: tr|A0A3P2A7W8|A0A3P2A7W8_9NEIS
Name: tr|A0A3P2A7W8|A0A3P2A7W8_9NEIS
Description: tr|A0A3P2A7W8|A0A3P2A7W8_9NEIS Ammonium transporter OS=Conchiformibius steedae OX=153493 GN=EII21_00045 PE=3 SV=1
Number of features: 0
Seq('MKRGVLVSSLIFPTVVQAAATDGWRQPFSVLDSGDTAWVMVSAILVLFMTLPGL...RVE')
ID: tr|A0A7D7SF27|A0A7D7SF27_9NEIS
Name: tr|A0A7D7SF27|A0A7D7SF27_9NEIS
Description: tr|A0A7D7SF27|A0A7D7SF27_9NEIS Ammonium transporter OS=Conchiformibius steedae OX=153493 GN=H3L98_07935 PE=3 SV=1
Number of features: 0
Seq('MKRGVWVSSLIFPTVVQAAATDGWRQPFSVLDSGDTAWVMVSAILVLFMTLPGL...RVE')
ID: tr|D3F0Z1|D3F0Z1_CONWI
Name: tr|D3F0Z1|D3F0Z1_CONWI
Description: tr|D3F0Z1|D3F0Z1_CONWI Ammonium transporter OS=Conexibacter woesei (strain DSM 14684 / CIP 108061 / JCM 11494 / NBRC 100937 / ID131577) OX=469383 GN=Cwoe_1639 PE=3 SV=1
Number of features: 0
Seq('MLAIKVQEGSVLHSRLGRAAVLGVLVTLLLPATALAQDSPTIEIVKGELNTTWL...VPA')
ID: tr|D3F545|D3F545_CONWI
Name: tr|D3F545|D3F545_CONWI
Description: tr|D3F545|D3F545_CONWI Ammonium transporter OS=Conexibacter woesei (strain DSM 14684 / CIP 108061 / JCM 11494 / NBRC 100937 / ID131577) OX=469383 GN=Cwoe_0187 PE=3 SV=1
Number of features: 0
Seq('MTESLVLAARSLGEVTIDLDALWLVVAAVLVMFMQAGFACVEIGFSRGRNAGAV...PER')
ID: tr|D3FBG3|D3FBG3_CONWI
Name: tr|D3FBG3|D3FBG3_CONWI
Description: tr|D3FBG3|D3FBG3_CONWI Ammonium transporter OS=Conexibacter woesei (strain DSM 14684 / CIP 108061 / JCM 11494 / NBRC 100937 / ID131577) OX=469383 GN=Cwoe_0899 PE=3 SV=1
Number of features: 0
Seq('MGTTMAAVAQVDTGDTAWMLMATALVLLMTPALGLFYAGLVRSKNTLNTFMMSV...EPA')
ID: tr|A4ABK3|A4ABK3_9GAMM
Name: tr|A4ABK3|A4ABK3_9GAMM
Description: tr|A4ABK3|A4ABK3_9GAMM Ammonium transporter OS=Congregibacter litoralis KT71 OX=314285 GN=KT71_07029 PE=3 SV=2
Number of features: 0
Seq('MENQIFELSYALDTFYFLVCGALVMWMAAGFAMLEAGLVRSKNTTEILTKNVAL...SAK')
ID: tr|A8N2H6|A8N2H6_COPC7
Name: tr|A8N2H6|A8N2H6_COPC7
Description: tr|A8N2H6|A8N2H6_COPC7 Ammonium transporter OS=Coprinopsis cinerea (strain Okayama-7 / 130 / ATCC MYA-4618 / FGSC 9003) OX=240176 GN=CC1G_01676 PE=3 SV=2
Number of features: 0
Seq('MSSTILRRAPGDPVYDRGDLSFIMLCGALVFFMVPGLAFLYSGLSRRKSALSMI...GQQ')

ID: tr|A8P923|A8P923_COPC7
Name: tr|A8P923|A8P923_COPC7
Description: tr|A8P923|A8P923_COPC7 Ammonium transporter OS=Coprinopsis cinerea (strain Okayama-7 / 130 / ATCC MYA-4618 / FGSC 9003) OX=240176 GN=CC1G_12816 PE=3 SV=2
Number of features: 0
Seq('MVNLTYDASGEIVYYDNVTGETTVYNMGDMAFIMVCMALVWIMIPGVGFFYSGL...ESQ')
ID: tr|A8NAG3|A8NAG3_COPC7
Name: tr|A8NAG3|A8NAG3_COPC7
Description: tr|A8NAG3|A8NAG3_COPC7 Ammonium transporter OS=Coprinopsis cinerea (strain Okayama-7 / 130 / ATCC MYA-4618 / FGSC 9003) OX=240176 GN=CC1G_05914 PE=3 SV=2
Number of features: 0
Seq('MVEVTYDDSGSLNTLDAEGTPVVYSPGDIAFILVCAALVWIMIPGLGFFYSGLL...HAS')
ID: tr|A0A316RGA5|A0A316RGA5_9BACT
Name: tr|A0A316RGA5|A0A316RGA5_9BACT
Description: tr|A0A316RGA5|A0A316RGA5_9BACT Ammonium transporter OS=Coprobacter fastidiosus OX=1099853 GN=DDY73_00165 PE=3 SV=1
Number of features: 0
Seq('MQKRWIILFVALLSISFLGLFYSGHEGVFTDIDSNLNFADIAWMITATIFVLMM...TKS')
ID: tr|A0A495WJM6|A0A495WJM6_9BACT
Name: tr|A0A495WJM6|A0A495WJM6_9BACT
Description: tr|A0A495WJM6|A0A495WJM6_9BACT Ammonium transporter OS=Coprobacter fastidiosus NSB1 OX=1349822 GN=BC742_0514 PE=3 SV=1
Number of features: 0
Seq('MQKRWIILFVALLSISFLGLFYSGHEGVFTDIDSNLNFADIAWMITATIFVLMM...TKS')
ID: tr|D5EP68|D5EP68_CORAD
Name: tr|D5EP68|D5EP68_CORAD
Description: tr|D5EP68|D5EP68_CORAD Ammonium transporter OS=Coraliomargarita akajimensis (strain DSM 45221 / IAM 15411 / JCM 23193 / KCTC 12865 / 04OKA010-24) OX=583355 GN=Caka_2562 PE=3 SV=1
Number of features: 0
Seq('MKITKYLLALLLASSAFLMTGSLGAEEAAEAVEAVEAAASFEDGYAAFMESPAA...SSR')
ID: tr|D5ELM4|D5ELM4_CORAD
Name: tr|D5ELM4|D5ELM4_CORAD
Description: tr|D5ELM4|D5ELM4_CORAD Ammonium transporter OS=Coraliomargarita akajimensis (strain DSM 45221 / IAM 15411 / JCM 23193 / KCTC 12865 / 04OKA010-24) OX=583355 GN=Caka_0172 PE=3 SV=1
Number of features: 0
Seq('MRQRFTKITRWLAPSLLALAPSIARAEEATAEVAYLPQNTADILWYLLAAVLVF...ELA')
ID: tr|D5EP71|D5EP71_CORAD
Name: tr|D5EP71|D5EP71_CORAD
Description: tr|D5EP71|D5EP71_CORAD Ammonium transporter OS=Coraliomargarita akajimensis (strain DSM 45221 / IAM 15411 / JCM 23193 / KCTC 12865 / 04OKA010-24) OX=583355 GN=Caka_2565 PE=3 SV=1
Number of features: 0
Seq('MTKILRNWLVLALFMVSGALFAQDVETATAAVEAPEVAAEAATIVTGDTAWMLT...HFE')
ID: tr|K9W6F3|K9W6F3_9CYAN
Name: tr|K9W6F3|K9W6F3_9CYAN
Description: tr|K9W6F3|K9W6F3_9CYAN Ammonium transporter OS=Crinalium epipsammum PCC 9333 OX=1173022 GN=Cri9333_4609 PE=3 SV=1
Number of features: 0
Seq('MPKVAGGEGSKQVFKKVLLVGIIVLWMLSFPLAGSAYAQTADEVTIDTGDTAFM...KGV')
ID: tr|K9W4V5|K9W4V5_9CYAN
Name: tr|K9W4V5|K9W4V5_9CYAN
Description: tr|K9W4V5|K9W4V5_9CYAN Ammonium transporter OS=Crinalium epipsammum PCC 9333 OX=1173022 GN=Cri9333_4608 PE=3 SV=1
Number of features: 0
Seq('MPSLTKYWIMLKQGLMPKLSKTQSKRTDNSALALSQLNWQGTVRRTAKSFRQLQ...VIS')
ID: tr|A3U857|A3U857_CROAH
Name: tr|A3U857|A3U857_CROAH
Description: tr|A3U857|A3U857_CROAH Ammonium transporter OS=Croceibacter atlanticus (strain ATCC BAA-628 / HTCC2559 / KCTC 12090) OX=216432 GN=CA2559_06675 PE=3 SV=1
Number of features: 0
Seq('MSKKLNFIILTVIVIISLICSAEYTFIESTNYSIDTGDTAWMIVASAFVLLMTP...ERI')
ID: tr|T2J0N1|T2J0N1_CROWT
Name: tr|T2J0N1|T2J0N1_CROWT
Description: tr|T2J0N1|T2J0N1_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 0005 OX=423472 GN=CWATWH0005_290 PE=3 SV=1
Number of features: 0
Seq('MKKAKDVINHDFSRWFVYLALAVLMLVVTISPSLAEDLSSLQEQLNQTKIAVDT...LKE')
ID: tr|T2IEJ2|T2IEJ2_CROWT
Name: tr|T2IEJ2|T2IEJ2_CROWT
Description: tr|T2IEJ2|T2IEJ2_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 8502 OX=423474 GN=CWATWH8502_899 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESIELIT...AGI')
ID: tr|G5IYK4|G5IYK4_CROWT
Name: tr|G5IYK4|G5IYK4_CROWT
Description: tr|G5IYK4|G5IYK4_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 0003 OX=423471 GN=CWATWH0003_0353 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESVELIT...AGI')
ID: tr|Q4CA23|Q4CA23_CROWT
Name: tr|Q4CA23|Q4CA23_CROWT
Description: tr|Q4CA23|Q4CA23_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 8501 OX=165597 GN=CwatDRAFT_6547 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESVELIT...AGI')
ID: tr|T2IKW0|T2IKW0_CROWT
Name: tr|T2IKW0|T2IKW0_CROWT
Description: tr|T2IKW0|T2IKW0_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 0005 OX=423472 GN=CWATWH0005_3244 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESVELIT...AGI')
ID: tr|T2JFS5|T2JFS5_CROWT
Name: tr|T2JFS5|T2JFS5_CROWT
Description: tr|T2JFS5|T2JFS5_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 0401 OX=555881 GN=CWATWH0401_764 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESVELIT...AGI')
ID: tr|T2JZP8|T2JZP8_CROWT
Name: tr|T2JZP8|T2JZP8_CROWT
Description: tr|T2JZP8|T2JZP8_CROWT Ammonium transporter OS=Crocosphaera watsonii WH 0402 OX=1284629 GN=CWATWH0402_1202 PE=3 SV=1
Number of features: 0
Seq('MVSTRTKKDVPIWQPLKVIARSFSPYWIACIPLAAIITIVWNKAVVAESVELIT...AGI')
ID: tr|A0A7V7RI44|A0A7V7RI44_CROSK
Name: tr|A0A7V7RI44|A0A7V7RI44_CROSK
Description: tr|A0A7V7RI44|A0A7V7RI44_CROSK Ammonium transporter OS=Cronobacter sakazakii OX=28141 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLALFY...YNA')
ID: tr|A7MFK3|A7MFK3_CROS8
Name: tr|A7MFK3|A7MFK3_CROS8
Description: tr|A7MFK3|A7MFK3_CROS8 Ammonium transporter OS=Cronobacter sakazakii (strain ATCC BAA-894) OX=290339 GN=ESA_02842 PE=3 SV=1
Number of features: 0
Seq('MHKMKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLA...YNA')
ID: tr|V5U2Z4|V5U2Z4_9ENTR
Name: tr|V5U2Z4|V5U2Z4_9ENTR
Description: tr|V5U2Z4|V5U2Z4_9ENTR Ammonium transporter OS=Cronobacter malonaticus OX=413503 GN=P262_04228 PE=3 SV=1
Number of features: 0
Seq('MHKMKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLA...YNA')
ID: tr|A0A423Y4I6|A0A423Y4I6_9ENTR
Name: tr|A0A423Y4I6|A0A423Y4I6_9ENTR
Description: tr|A0A423Y4I6|A0A423Y4I6_9ENTR Ammonium transporter OS=Cronobacter malonaticus OX=413503 GN=C3E80_00960 PE=3 SV=1
Number of features: 0
Seq('MKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLALFY...YNA')
ID: tr|K8CKZ7|K8CKZ7_CROSK
Name: tr|K8CKZ7|K8CKZ7_CROSK
Description: tr|K8CKZ7|K8CKZ7_CROSK Ammonium transporter OS=Cronobacter sakazakii 696 OX=1208664 GN=BN128_4157 PE=3 SV=1
Number of features: 0
Seq('MKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLALFY...YNA')
ID: tr|K8C851|K8C851_CROSK
Name: tr|K8C851|K8C851_CROSK
Description: tr|K8C851|K8C851_CROSK Ammonium transporter OS=Cronobacter sakazakii 701 OX=1208663 GN=BN129_4196 PE=3 SV=1
Number of features: 0
Seq('MKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLALFY...YNA')
ID: tr|A0A3Q9CHX8|A0A3Q9CHX8_CROSK
Name: tr|A0A3Q9CHX8|A0A3Q9CHX8_CROSK
Description: tr|A0A3Q9CHX8|A0A3Q9CHX8_CROSK Ammonium transporter AmtB OS=Cronobacter sakazakii OX=28141 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKHTAFKSGFGLLALLPGIALAAPAVADKADNAFMMICTALVLFMTIPGLALFY...YNA')
ID: tr|Q560M9|Q560M9_CRYNB
Name: tr|Q560M9|Q560M9_CRYNB
Description: tr|Q560M9|Q560M9_CRYNB Ammonium transporter OS=Cryptococcus neoformans var. neoformans serotype D (strain B-3501A) OX=283643 GN=CNBA2110 PE=3 SV=1
Number of features: 0
Seq('MVNITYGALLSSSDGAVHFEPLGTDIISTLAGQPTAFDPGDIAWVLTCSALIVF...HRE')
ID: tr|F5HBK8|F5HBK8_CRYNB
Name: tr|F5HBK8|F5HBK8_CRYNB
Description: tr|F5HBK8|F5HBK8_CRYNB Ammonium transporter OS=Cryptococcus neoformans var. neoformans serotype D (strain B-3501A) OX=283643 GN=CNBJ1590 PE=3 SV=1
Number of features: 0
Seq('MVNVTYTDSSSDMIYTADDGTQYLYNLGDMSFVIAAMALVWIMVPGVGLFYSGL...VDV')
ID: tr|Q5KPM5|Q5KPM5_CRYNJ
Name: tr|Q5KPM5|Q5KPM5_CRYNJ
Description: tr|Q5KPM5|Q5KPM5_CRYNJ Ammonium transporter OS=Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565) OX=214684 GN=CNA02250 PE=3 SV=1
Number of features: 0
Seq('MVNITYGALLSSSDGAVHFEPLGTDIISTLAGQPTAFDPGDIAWVLTCSALIVF...HRE')
ID: tr|Q5KAF6|Q5KAF6_CRYNJ
Name: tr|Q5KAF6|Q5KAF6_CRYNJ
Description: tr|Q5KAF6|Q5KAF6_CRYNJ Ammonium transporter OS=Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565) OX=214684 GN=CNJ01880 PE=3 SV=1
Number of features: 0
Seq('MVNVTYTDSSSDMIYTADDGTQYLYNLGDMSFVIAAMALVWIMVPGVGLFYSGL...VDV')
ID: tr|A0A225XW14|A0A225XW14_CRYNV
Name: tr|A0A225XW14|A0A225XW14_CRYNV
Description: tr|A0A225XW14|A0A225XW14_CRYNV Ammonium transporter OS=Cryptococcus neoformans var. grubii c45 OX=1230068 GN=C356_05372 PE=3 SV=1
Number of features: 0
Seq('MVNVTYTDSSSDMIYTADDGTQYLYNLGDMSFSESYHPQFSTLEWLTPPLVIAA...VDV')

ID: tr|A0A226A1N0|A0A226A1N0_CRYNV
Name: tr|A0A226A1N0|A0A226A1N0_CRYNV
Description: tr|A0A226A1N0|A0A226A1N0_CRYNV Ammonium transporter OS=Cryptococcus neoformans var. grubii c45 OX=1230068 GN=C356_00242 PE=3 SV=1
Number of features: 0
Seq('MVNITYGALVSSDGAVHFEPLGTDIISTLAGQATAFDPGDIAWMLTCSALIVFM...QRE')
ID: tr|A0A854Q6X9|A0A854Q6X9_CRYNV
Name: tr|A0A854Q6X9|A0A854Q6X9_CRYNV
Description: tr|A0A854Q6X9|A0A854Q6X9_CRYNV Ammonium transporter OS=Cryptococcus neoformans var. grubii Tu259-1 OX=1230072 GN=C361_05853 PE=3 SV=1
Number of features: 0
Seq('MVNVTYTDSSSDMIYTADDGTQYLYNLGDMSFSESYHPQFSTLEWLTPPLVIAA...VDV')
ID: tr|A0A854QN45|A0A854QN45_CRYNV
Name: tr|A0A854QN45|A0A854QN45_CRYNV
Description: tr|A0A854QN45|A0A854QN45_CRYNV Ammonium transporter OS=Cryptococcus neoformans var. grubii Tu259-1 OX=1230072 GN=C361_00236 PE=3 SV=1
Number of features: 0
Seq('MVNITYGALVSSDGAVHFEPLGTDIISTLAGQATAFDPGDIAWMLTCSALIVFM...QRE')
ID: tr|J9VID9|J9VID9_CRYNH
Name: tr|J9VID9|J9VID9_CRYNH
Description: tr|J9VID9|J9VID9_CRYNH Ammonium transporter OS=Cryptococcus neoformans var. grubii serotype A (strain H99 / ATCC 208821 / CBS 10515 / FGSC 9487) OX=235443 GN=CNAG_00235 PE=3 SV=1
Number of features: 0
Seq('MVNITYGALVSSDGAVHFEPLGTDIISTLAGQATAFDPGDIAWMLTCSALIVFM...QRE')
ID: tr|J9VXX9|J9VXX9_CRYNH
Name: tr|J9VXX9|J9VXX9_CRYNH
Description: tr|J9VXX9|J9VXX9_CRYNH Ammonium transporter OS=Cryptococcus neoformans var. grubii serotype A (strain H99 / ATCC 208821 / CBS 10515 / FGSC 9487) OX=235443 GN=CNAG_04758 PE=3 SV=1
Number of features: 0
Seq('MVNVTYTDSSSDMIYTADDGTQYLYNLGDMSFIIAAMALVWIMVPGVGLFYSGL...VDV')
ID: tr|Q55T67|Q55T67_CRYNB
Name: tr|Q55T67|Q55T67_CRYNB
Description: tr|Q55T67|Q55T67_CRYNB Major facilitator superfamily (MFS) profile domain-containing protein OS=Cryptococcus neoformans var. neoformans serotype D (strain B-3501A) OX=283643 GN=CNBD5850 PE=4 SV=1
Number of features: 0
Seq('MSTHHTNQIHDHSPSSPSNQPVLEEGEDEYRPLPHAWSGATLYEPYTLSRDKLK...HPV')
ID: tr|Q55T73|Q55T73_CRYNB
Name: tr|Q55T73|Q55T73_CRYNB
Description: tr|Q55T73|Q55T73_CRYNB Major facilitator superfamily (MFS) profile domain-containing protein OS=Cryptococcus neoformans var. neoformans serotype D (strain B-3501A) OX=283643 GN=CNBD5790 PE=4 SV=1
Number of features: 0
Seq('MIQSPITQNEPRQDTVDSATETANEGQYKRVESEQTLCDKLGTVSPKTEKFFSY...AEH')
ID: tr|F5HID9|F5HID9_CRYNB
Name: tr|F5HID9|F5HID9_CRYNB
Description: tr|F5HID9|F5HID9_CRYNB Major facilitator superfamily (MFS) profile domain-containing protein OS=Cryptococcus neoformans var. neoformans serotype D (strain B-3501A) OX=283643 GN=CNBJ0240 PE=4 SV=1
Number of features: 0
Seq('MGEQRYEIEKRDITAPQDSKIREDMEKGFEQTMESDVAPVKQEAPPTEHELSMF...DVH')
ID: tr|A0A225YUL7|A0A225YUL7_CRYNV
Name: tr|A0A225YUL7|A0A225YUL7_CRYNV
Description: tr|A0A225YUL7|A0A225YUL7_CRYNV Multidrug efflux pump OS=Cryptococcus neoformans var. grubii c45 OX=1230068 GN=C356_03115 PE=4 SV=1
Number of features: 0
Seq('MPTNRINQKEDPFPSIPSNQPVLEENEDEYRPLPHVWSGATLCEPWTLSGDKLK...HAV')
ID: tr|A0A225YUR6|A0A225YUR6_CRYNV
Name: tr|A0A225YUR6|A0A225YUR6_CRYNV
Description: tr|A0A225YUR6|A0A225YUR6_CRYNV MFS transporter OS=Cryptococcus neoformans var. grubii c45 OX=1230068 GN=C356_03108 PE=4 SV=1
Number of features: 0
Seq('MDVRETRSTSAFLPPMTRSPITQNEPQQDTVDFATETANEGEYKRVESEQTLCD...AEH')
ID: tr|Q5KJ68|Q5KJ68_CRYNJ
Name: tr|Q5KJ68|Q5KJ68_CRYNJ
Description: tr|Q5KJ68|Q5KJ68_CRYNJ MFS transporter, putative OS=Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565) OX=214684 GN=CND00450 PE=4 SV=2
Number of features: 0
Seq('MADPFESHLCSYVSLISTTYTMNVRETRSSSASPPPMIQSPITQNEPRQDTVDS...AEH')
ID: tr|Q5KJ74|Q5KJ74_CRYNJ
Name: tr|Q5KJ74|Q5KJ74_CRYNJ
Description: tr|Q5KJ74|Q5KJ74_CRYNJ Multidrug efflux pump, putative OS=Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565) OX=214684 GN=CND00390 PE=4 SV=1
Number of features: 0
Seq('MSTHHTNQIHDHSPSSPSNQPVLEEGEDEYRPLPHAWSGATLYEPYTLSRDKLK...HPV')
ID: tr|Q5KA34|Q5KA34_CRYNJ
Name: tr|Q5KA34|Q5KA34_CRYNJ
Description: tr|Q5KA34|Q5KA34_CRYNJ MFS transporter, putative OS=Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565) OX=214684 GN=CNJ03220 PE=4 SV=1
Number of features: 0
Seq('MGEQRYEIEKRDITAPQDSKIREDMEKGFEQTMESDVAPVKQEAPPTEHELSMF...DVH')
ID: tr|A0A854QKG0|A0A854QKG0_CRYNV
Name: tr|A0A854QKG0|A0A854QKG0_CRYNV
Description: tr|A0A854QKG0|A0A854QKG0_CRYNV MFS transporter OS=Cryptococcus neoformans var. grubii Tu259-1 OX=1230072 GN=C361_03522 PE=4 SV=1
Number of features: 0
Seq('MHGRPLCLSFVQLHITFSTIYTMNVRETRSTSASPPPMTRSPITQNEPQQDTVD...AEH')
ID: tr|A0A854QBS6|A0A854QBS6_CRYNV
Name: tr|A0A854QBS6|A0A854QBS6_CRYNV
Description: tr|A0A854QBS6|A0A854QBS6_CRYNV Multidrug efflux pump OS=Cryptococcus neoformans var. grubii Tu259-1 OX=1230072 GN=C361_03529 PE=4 SV=1
Number of features: 0
Seq('MPTNRINQKEDAFPSIPSNQPVLEDNEDEYRPLPHVWSGATLCEPWTLSGDKLK...HAV')
ID: tr|J9VL73|J9VL73_CRYNH
Name: tr|J9VL73|J9VL73_CRYNH
Description: tr|J9VL73|J9VL73_CRYNH Multidrug efflux pump OS=Cryptococcus neoformans var. grubii serotype A (strain H99 / ATCC 208821 / CBS 10515 / FGSC 9487) OX=235443 GN=CNAG_00898 PE=4 SV=2
Number of features: 0
Seq('MPTNRINQKEDAFPSIPSNQPVLEDNEDEYRPLPHVWSGATLCEPWTLSGDKLK...HAV')
ID: tr|J9VU12|J9VU12_CRYNH
Name: tr|J9VU12|J9VU12_CRYNH
Description: tr|J9VU12|J9VU12_CRYNH MFS transporter OS=Cryptococcus neoformans var. grubii serotype A (strain H99 / ATCC 208821 / CBS 10515 / FGSC 9487) OX=235443 GN=CNAG_00905 PE=4 SV=2
Number of features: 0
Seq('MHGRPLCLSFVQLHITFSTIYTMNVRETRSTSASPPPMTRSPITQNEPQQDTVD...AEH')
ID: tr|A0A8D8DV88|A0A8D8DV88_CULPI
Name: tr|A0A8D8DV88|A0A8D8DV88_CULPI
Description: tr|A0A8D8DV88|A0A8D8DV88_CULPI Ammonium transporter OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MDNVTNVTESSVVPALYDFGQSDGVFIMICAFLLVTLQTGFVLLESGCVSPRNE...SLA')
ID: tr|A0A8D8GPY1|A0A8D8GPY1_CULPI
Name: tr|A0A8D8GPY1|A0A8D8GPY1_CULPI
Description: tr|A0A8D8GPY1|A0A8D8GPY1_CULPI Ammonium transporter OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MDNVTNVTESALVPALYDFGQSDGVFIMICAFLLVTLQTGFVLLESGCVSPRNE...SLA')
ID: tr|A0A8D8B493|A0A8D8B493_CULPI
Name: tr|A0A8D8B493|A0A8D8B493_CULPI
Description: tr|A0A8D8B493|A0A8D8B493_CULPI Ammonium transporter OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MDNVTNVTESALVPALYDFGQSDGVFIMICAFLLVTLQTGFVLLESGCVSPRNE...SLA')
ID: tr|A0A8D8FDY2|A0A8D8FDY2_CULPI
Name: tr|A0A8D8FDY2|A0A8D8FDY2_CULPI
Description: tr|A0A8D8FDY2|A0A8D8FDY2_CULPI Ammonium transporter (Fragment) OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MDNVTNVTESALVPALYDFGQSDGVFIMICAFLLVTLQTGFVLLESGCVSPRNE...NDK')
ID: tr|A0A8D8GTE1|A0A8D8GTE1_CULPI
Name: tr|A0A8D8GTE1|A0A8D8GTE1_CULPI
Description: tr|A0A8D8GTE1|A0A8D8GTE1_CULPI Ammonium transporter (Fragment) OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MDNVTNVTESSVVPALYDFGQSDGVFIMICAFLLVTLQTGFVLLESGCVSPRNE...DKS')
ID: tr|A0A8D8ET63|A0A8D8ET63_CULPI
Name: tr|A0A8D8ET63|A0A8D8ET63_CULPI
Description: tr|A0A8D8ET63|A0A8D8ET63_CULPI Ammonium transporter Rh type B OS=Culex pipiens OX=7175 PE=3 SV=1
Number of features: 0
Seq('MHTPGSSVAGYGLLLVVQIVFVIVFGFFTDYSKELLPKNETGTGLEASHGAAEE...SSD')
ID: tr|A0A502C8T9|A0A502C8T9_9MICO
Name: tr|A0A502C8T9|A0A502C8T9_9MICO
Description: tr|A0A502C8T9|A0A502C8T9_9MICO Ammonium transporter OS=Curtobacterium flaccumfaciens OX=2035 GN=amt PE=3 SV=1
Number of features: 0
Seq('MLDQGQTGFIMIMAALVLFMTPGLAFFYGGLVKAKSVISMMMMSFGAIALVGVL...SVR')
ID: tr|A0A6N1D0L9|A0A6N1D0L9_9MICO
Name: tr|A0A6N1D0L9|A0A6N1D0L9_9MICO
Description: tr|A0A6N1D0L9|A0A6N1D0L9_9MICO Ammonium transporter OS=Curtobacterium flaccumfaciens pv. flaccumfaciens OX=138532 GN=FK523_08175 PE=3 SV=1
Number of features: 0
Seq('MLDQGQTGFIMIMAALVLFMTPGLAFFYGGLVKAKSVISMMMMSFGAIALVGVL...SVR')
ID: tr|A0A4R6DFU8|A0A4R6DFU8_9MICO
Name: tr|A0A4R6DFU8|A0A4R6DFU8_9MICO
Description: tr|A0A4R6DFU8|A0A4R6DFU8_9MICO Ammonium transporter OS=Curtobacterium flaccumfaciens OX=2035 GN=EDF64_110159 PE=3 SV=1
Number of features: 0
Seq('MLDQGNTTFVLVMAALVLFMTPGLAFFYGGLVKAKSVISMMMMSFGAIALVSVL...SVR')
ID: tr|M1V7W3|M1V7W3_CYAM1
Name: tr|M1V7W3|M1V7W3_CYAM1
Description: tr|M1V7W3|M1V7W3_CYAM1 Probable ammonium transporter OS=Cyanidioschyzon merolae (strain NIES-3377 / 10D) OX=280699 GN=CYME_CMT526C PE=3 SV=1
Number of features: 0
Seq('MHYLADRFGLNADAPKLSAANQSLYFALANIVDGVNSAFLLLTAALVFCMQAGF...VAV')
ID: tr|K9YJQ3|K9YJQ3_CYASC
Name: tr|K9YJQ3|K9YJQ3_CYASC
Description: tr|K9YJQ3|K9YJQ3_CYASC Ammonium transporter OS=Cyanobacterium stanieri (strain ATCC 29140 / PCC 7202) OX=292563 GN=Cyast_0659 PE=3 SV=1
Number of features: 0
Seq('MSRSQGQDSFILNSMGWLRSKLPSYWVGCIPLSALIFVVWSFSAQAQGFDPPET...TEG')

ID: tr|K9YN27|K9YN27_CYASC
Name: tr|K9YN27|K9YN27_CYASC
Description: tr|K9YN27|K9YN27_CYASC Ammonium transporter OS=Cyanobacterium stanieri (strain ATCC 29140 / PCC 7202) OX=292563 GN=Cyast_2395 PE=3 SV=1
Number of features: 0
Seq('MLRLKTIEKRLKRIVKKIQLYPTWQGCVILSVILLLSCATSVGAQDTLAEMSAA...VEE')
ID: tr|K9P5D1|K9P5D1_CYAGP
Name: tr|K9P5D1|K9P5D1_CYAGP
Description: tr|K9P5D1|K9P5D1_CYAGP Ammonium transporter OS=Cyanobium gracile (strain ATCC 27147 / PCC 6307) OX=292564 GN=Cyagr_1022 PE=3 SV=1
Number of features: 0
Seq('MQGSPTGASSSSAPSAPSALTTFDRLRSRCLVGLQDQRLRSIAFLLLALGAGIG...MTN')
ID: tr|K9P718|K9P718_CYAGP
Name: tr|K9P718|K9P718_CYAGP
Description: tr|K9P718|K9P718_CYAGP Ammonium transporter OS=Cyanobium gracile (strain ATCC 27147 / PCC 6307) OX=292564 GN=Cyagr_2082 PE=3 SV=1
Number of features: 0
Seq('MIDSSHPHKVRPPRNLSEASLLEAPAVLMRKVRGLSSRTSLTWFACVPLALFIL...STN')
ID: tr|G0J614|G0J614_CYCMS
Name: tr|G0J614|G0J614_CYCMS
Description: tr|G0J614|G0J614_CYCMS Ammonium transporter OS=Cyclobacterium marinum (strain ATCC 25205 / DSM 745 / LMG 13164 / NCIMB 1802) OX=880070 GN=Cycma_2335 PE=3 SV=1
Number of features: 0
Seq('MTQELFTINNLWIMVATILVFIMHLGFAALEAGLTRAKNTVNILFKNTIIPAIG...TKE')
ID: tr|G0IYI2|G0IYI2_CYCMS
Name: tr|G0IYI2|G0IYI2_CYCMS
Description: tr|G0IYI2|G0IYI2_CYCMS Ammonium transporter OS=Cyclobacterium marinum (strain ATCC 25205 / DSM 745 / LMG 13164 / NCIMB 1802) OX=880070 GN=Cycma_2666 PE=3 SV=1
Number of features: 0
Seq('MKNILPPLLQVDSSGIDYADAITQNLLTTNNVWMMLATALVFIMHLGFAGVEAG...YDE')
ID: tr|A0A1X4G8K1|A0A1X4G8K1_9CYAN
Name: tr|A0A1X4G8K1|A0A1X4G8K1_9CYAN
Description: tr|A0A1X4G8K1|A0A1X4G8K1_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii CENA303 OX=1170769 GN=B7O87_06430 PE=3 SV=1
Number of features: 0
Seq('MLRKFLVISGLIVLLLTFPFAGNAVAQTNTPAPDTGDTTFVLMSSALVLLMTPG...INI')
ID: tr|A0A8T9DUD0|A0A8T9DUD0_9CYAN
Name: tr|A0A8T9DUD0|A0A8T9DUD0_9CYAN
Description: tr|A0A8T9DUD0|A0A8T9DUD0_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii Cr2010 OX=2108055 GN=C6N34_004400 PE=3 SV=1
Number of features: 0
Seq('MTRIRSKRLRRKRGSALRLSFPWLSAGNLAPIGRACITVAMLIVISWGYAAVAA...GNR')
ID: tr|A0A1X4GBG2|A0A1X4GBG2_9CYAN
Name: tr|A0A1X4GBG2|A0A1X4GBG2_9CYAN
Description: tr|A0A1X4GBG2|A0A1X4GBG2_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii CENA303 OX=1170769 GN=B7O87_02640 PE=3 SV=1
Number of features: 0
Seq('MSMTRIRSKRLRRKRGSALRLSFPWLSAGKLAPIGRACITVAMLIIVGWGYAAV...GNR')
ID: tr|A0A853MG28|A0A853MG28_9CYAN
Name: tr|A0A853MG28|A0A853MG28_9CYAN
Description: tr|A0A853MG28|A0A853MG28_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii CS-505 OX=533240 GN=A9P98_04670 PE=3 SV=1
Number of features: 0
Seq('MRSKRLRRKRGSALRLSFPWLSAGNLAPIGRACITVAMLIVISWGYAAVAADPP...GNR')
ID: tr|A0A7W1WEA6|A0A7W1WEA6_9CYAN
Name: tr|A0A7W1WEA6|A0A7W1WEA6_9CYAN
Description: tr|A0A7W1WEA6|A0A7W1WEA6_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii CS-506_D OX=2585137 GN=FHK94_14700 PE=3 SV=1
Number of features: 0
Seq('MSMTRIRSKRLRRKRGSALRLSFPWLSAGNLAPIGRACITVAMLIVISWGYAAV...GNR')
ID: tr|A0A838WPM9|A0A838WPM9_9CYAN
Name: tr|A0A838WPM9|A0A838WPM9_9CYAN
Description: tr|A0A838WPM9|A0A838WPM9_9CYAN Ammonium transporter OS=Cylindrospermopsis raciborskii CS-506_A OX=2585140 GN=FHK98_14815 PE=3 SV=1
Number of features: 0
Seq('MSMTRIRSKRLRRKRGSALRLSFPWLSAGNLAPIGRACITVAMLIVISWGYAAV...GNR')
ID: tr|K9WT03|K9WT03_9NOST
Name: tr|K9WT03|K9WT03_9NOST
Description: tr|K9WT03|K9WT03_9NOST Ammonium transporter OS=Cylindrospermum stagnale PCC 7417 OX=56107 GN=Cylst_0578 PE=3 SV=1
Number of features: 0
Seq('MFKKVVMIGVLTLLLLGVPLTGNAFAQAAAATPPAADTGDTAFMLISSALVLLM...NVS')
ID: tr|K9WSX4|K9WSX4_9NOST
Name: tr|K9WSX4|K9WSX4_9NOST
Description: tr|K9WSX4|K9WSX4_9NOST Ammonium transporter OS=Cylindrospermum stagnale PCC 7417 OX=56107 GN=Cylst_0549 PE=3 SV=1
Number of features: 0
Seq('MNKRIRPWHRLLALAIGSMVFAVCAPTVVQAADPPTLNSLAETTTKLQISIDTT...DSE')
ID: tr|A0A6N4SWV7|A0A6N4SWV7_CYTH3
Name: tr|A0A6N4SWV7|A0A6N4SWV7_CYTH3
Description: tr|A0A6N4SWV7|A0A6N4SWV7_CYTH3 Ammonium transporter OS=Cytophaga hutchinsonii (strain ATCC 33406 / DSM 1761 / CIP 103989 / NBRC 15051 / NCIMB 9469 / D465) OX=269798 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNEITELAAQQAELTHAVDTVWVAICAALIFQMEGGFALLESGFVRSKNAISII...TIE')
ID: tr|A0A6N4SPH9|A0A6N4SPH9_CYTH3
Name: tr|A0A6N4SPH9|A0A6N4SPH9_CYTH3
Description: tr|A0A6N4SPH9|A0A6N4SPH9_CYTH3 Ammonium transporter OS=Cytophaga hutchinsonii (strain ATCC 33406 / DSM 1761 / CIP 103989 / NBRC 15051 / NCIMB 9469 / D465) OX=269798 GN=amtB PE=3 SV=1
Number of features: 0
Seq('METAVLDTIEAAVPAIDSIKAVAAITVDTLASKSSLAATDAAVSQLGLTANNIW...KEY')
ID: tr|A0A6N4SWE0|A0A6N4SWE0_CYTH3
Name: tr|A0A6N4SWE0|A0A6N4SWE0_CYTH3
Description: tr|A0A6N4SWE0|A0A6N4SWE0_CYTH3 Ammonium transporter OS=Cytophaga hutchinsonii (strain ATCC 33406 / DSM 1761 / CIP 103989 / NBRC 15051 / NCIMB 9469 / D465) OX=269798 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MLVDSLNHAQAALNDSLHATNDLMFKTRTELQLTQNSLANSSFKANNIWMMVAT...MSK')
ID: tr|K9YR86|K9YR86_DACS8
Name: tr|K9YR86|K9YR86_DACS8
Description: tr|K9YR86|K9YR86_DACS8 Ammonium transporter OS=Dactylococcopsis salina (strain PCC 8305) OX=13035 GN=Dacsa_0652 PE=3 SV=1
Number of features: 0
Seq('MMSQSKSKPKKTTLWDLPLLKPLRVITRSFSPYWLACIPLTAVIVVVWESAAQA...SET')
ID: tr|K9Z0D3|K9Z0D3_DACS8
Name: tr|K9Z0D3|K9Z0D3_DACS8
Description: tr|K9Z0D3|K9Z0D3_DACS8 Ammonia permease OS=Dactylococcopsis salina (strain PCC 8305) OX=13035 GN=Dacsa_3557 PE=4 SV=1
Number of features: 0
Seq('MSAEAQNFLATFVTETYYYWASVFMLVIHVGFLAYEGGAARTKNVLSTMVKNLL...QKS')
ID: sp|A0A0G2KTI4|S12A2_DANRE
Name: sp|A0A0G2KTI4|S12A2_DANRE
Description: sp|A0A0G2KTI4|S12A2_DANRE Solute carrier family 12 member 2 OS=Danio rerio OX=7955 GN=slc12a2 PE=1 SV=3
Number of features: 0
Seq('MSASPPISAGDYLSAPEPDALKPAGPTPSQSRFQVDLVTESAGDGETTVGFDSS...FYS')
ID: sp|Q8JI14|RHCL2_DANRE
Name: sp|Q8JI14|RHCL2_DANRE
Description: sp|Q8JI14|RHCL2_DANRE Ammonium transporter Rh type C-like 2 OS=Danio rerio OX=7955 GN=rhcgl2 PE=2 SV=2
Number of features: 0
Seq('MGNCFGSRGICDRPKNTNIRLSLPAVCFVWQVSMIILFGVFVRYNEEADTNWVY...EQS')
ID: sp|Q7T070|RHBG_DANRE
Name: sp|Q7T070|RHBG_DANRE
Description: sp|Q7T070|RHBG_DANRE Ammonium transporter Rh type B OS=Danio rerio OX=7955 GN=rhbg PE=2 SV=1
Number of features: 0
Seq('MAESTNLRLRLPLICIILEVILIILFGVLVEYNDDTDAKKWNKNNSTDPATNEF...LNS')
ID: tr|A0A8M3AW33|A0A8M3AW33_DANRE
Name: tr|A0A8M3AW33|A0A8M3AW33_DANRE
Description: tr|A0A8M3AW33|A0A8M3AW33_DANRE Ammonium transporter Rh type A isoform X1 OS=Danio rerio OX=7955 GN=rhag PE=3 SV=1
Number of features: 0
Seq('MPTYSTNMRLKFPILALILEIITIVLYALFVVYDTGDDKGHGDHHEKSNQTESP...WEV')
ID: tr|Q7T067|Q7T067_DANRE
Name: tr|Q7T067|Q7T067_DANRE
Description: tr|Q7T067|Q7T067_DANRE Ammonium transporter Rh type A OS=Danio rerio OX=7955 GN=wu:fj61d12 PE=2 SV=1
Number of features: 0
Seq('MPTYSTNMRLKFPILALILEIITIVLYALFVVYDTGDDKGHGDHHEKSNQTESP...AEA')
ID: tr|A4QNU4|A4QNU4_DANRE
Name: tr|A4QNU4|A4QNU4_DANRE
Description: tr|A4QNU4|A4QNU4_DANRE Rh family, C glycoprotein a OS=Danio rerio OX=7955 GN=zgc:162132 PE=2 SV=1
Number of features: 0
Seq('MGNFIECCRGFWCGPKNPNVRVSLPIVCFIWQIAMIILFGLFVRYDIESDAHWA...EHR')
ID: tr|Q4VV70|Q4VV70_DANRE
Name: tr|Q4VV70|Q4VV70_DANRE
Description: tr|Q4VV70|Q4VV70_DANRE Rh blood group, D antigen OS=Danio rerio OX=7955 GN=rh30 PE=2 SV=1
Number of features: 0
Seq('MAPQYAPSLRSRLPLVAFLLETLFLLLFVFWVKIEKQEYRRSESEPFVHSYADF...TKK')
ID: tr|E9FWC4|E9FWC4_DAPPU
Name: tr|E9FWC4|E9FWC4_DAPPU
Description: tr|E9FWC4|E9FWC4_DAPPU Ammonium transporter AmtB-like domain-containing protein OS=Daphnia pulex OX=6669 GN=DAPPUDRAFT_311255 PE=3 SV=1
Number of features: 0
Seq('MASPLINQSDPIASINLIHDELESFKKNVDIFFLVVMGSIVFFLQAGFAFYESG...QAW')
ID: tr|E9H9L9|E9H9L9_DAPPU
Name: tr|E9H9L9|E9H9L9_DAPPU
Description: tr|E9H9L9|E9H9L9_DAPPU Ammonium transporter AmtB-like domain-containing protein OS=Daphnia pulex OX=6669 GN=DAPPUDRAFT_327165 PE=3 SV=1
Number of features: 0
Seq('MSPSNQSILQPELKLQEDLAAFKKNVDNMFLITMGIFVFCLQGGFAFYESACVR...QNG')
ID: tr|E9HAT0|E9HAT0_DAPPU
Name: tr|E9HAT0|E9HAT0_DAPPU
Description: tr|E9HAT0|E9HAT0_DAPPU Ammonium transporter AmtB-like domain-containing protein OS=Daphnia pulex OX=6669 GN=DAPPUDRAFT_256123 PE=3 SV=1
Number of features: 0
Seq('MSMSVRQHPKKKNQQFMKVQSLRVADHQTTTRFDLDSIAAAAEKNQRNEFLVHI...MNR')

ID: tr|Q6BJI7|Q6BJI7_DEBHA
Name: tr|Q6BJI7|Q6BJI7_DEBHA
Description: tr|Q6BJI7|Q6BJI7_DEBHA Ammonium transporter OS=Debaryomyces hansenii (strain ATCC 36239 / CBS 767 / BCRC 21394 / JCM 1990 / NBRC 0083 / IGC 2968) OX=284592 GN=DEHA2G02156g PE=3 SV=1
Number of features: 0
Seq('MTISSVTTGILNRRKLFTANEDYKESDILLFSIASSLIWIMIPGLAFLYSGLAR...IEE')
ID: tr|Q6BT62|Q6BT62_DEBHA
Name: tr|Q6BT62|Q6BT62_DEBHA
Description: tr|Q6BT62|Q6BT62_DEBHA Ammonium transporter OS=Debaryomyces hansenii (strain ATCC 36239 / CBS 767 / BCRC 21394 / JCM 1990 / NBRC 0083 / IGC 2968) OX=284592 GN=DEHA2D03234g PE=3 SV=1
Number of features: 0
Seq('MANDGFTGTGPGGDIMKVDLNEQFDKADMVWVGVSAALVWLMVPGVGLLYSGLS...TKE')
ID: tr|Q6BK68|Q6BK68_DEBHA
Name: tr|Q6BK68|Q6BK68_DEBHA
Description: tr|Q6BK68|Q6BK68_DEBHA DEHA2F24442p OS=Debaryomyces hansenii (strain ATCC 36239 / CBS 767 / BCRC 21394 / JCM 1990 / NBRC 0083 / IGC 2968) OX=284592 GN=DEHA2F24442g PE=3 SV=2
Number of features: 0
Seq('MNSSHYQVSTSIEDVWTIINSLYMIYCTSLLPLAMIGIALFYSGLTQRRSSLTM...KGE')
ID: tr|Q6BVC6|Q6BVC6_DEBHA
Name: tr|Q6BVC6|Q6BVC6_DEBHA
Description: tr|Q6BVC6|Q6BVC6_DEBHA DEHA2C03718p OS=Debaryomyces hansenii (strain ATCC 36239 / CBS 767 / BCRC 21394 / JCM 1990 / NBRC 0083 / IGC 2968) OX=284592 GN=DEHA2C03718g PE=4 SV=2
Number of features: 0
Seq('MESSCRDNIDLNRDVSQDSNYIEEDEISEIKSSISTLKPTPPPEEISVGREILF...PAV')
ID: tr|Q47K18|Q47K18_DECAR
Name: tr|Q47K18|Q47K18_DECAR
Description: tr|Q47K18|Q47K18_DECAR Ammonium transporter OS=Dechloromonas aromatica (strain RCB) OX=159087 GN=Daro_0054 PE=3 SV=1
Number of features: 0
Seq('MKRLLALLALVGAVGFGAPAWAEEKAAAPEAVAATAPAAAPAAAAPAAAPAAAA...YHH')
ID: tr|D3PAH1|D3PAH1_DEFDS
Name: tr|D3PAH1|D3PAH1_DEFDS
Description: tr|D3PAH1|D3PAH1_DEFDS Ammonium transporter OS=Deferribacter desulfuricans (strain DSM 14783 / JCM 11476 / NBRC 101012 / SSM1) OX=639282 GN=DEFDS_0082 PE=3 SV=1
Number of features: 0
Seq('MEDLSMKRFLISLFFIFTFSCFAFANDNQTINWVDTVWMIVATAFVMLMTPAGL...FNL')
ID: tr|D3PE53|D3PE53_DEFDS
Name: tr|D3PE53|D3PE53_DEFDS
Description: tr|D3PE53|D3PE53_DEFDS Ammonium transporter OS=Deferribacter desulfuricans (strain DSM 14783 / JCM 11476 / NBRC 101012 / SSM1) OX=639282 GN=DEFDS_1415 PE=3 SV=1
Number of features: 0
Seq('MRLFFITSILFLTHNVYAFNGKVNSADTLWVIISSILVLLMIPALSIFYGGMVR...AYN')
ID: tr|A0A857DDJ7|A0A857DDJ7_9FIRM
Name: tr|A0A857DDJ7|A0A857DDJ7_9FIRM
Description: tr|A0A857DDJ7|A0A857DDJ7_9FIRM Ammonium transporter OS=Dehalobacter restrictus OX=55583 GN=amt PE=3 SV=1
Number of features: 0
Seq('MNYGDIAFMLFSTALVFLMIPGLAFFYGGLVKRRHVLSIMMQSIAAIGIISILW...MVN')
ID: tr|A0A857DMN9|A0A857DMN9_9FIRM
Name: tr|A0A857DMN9|A0A857DMN9_9FIRM
Description: tr|A0A857DMN9|A0A857DMN9_9FIRM Ammonium transporter OS=Dehalobacter restrictus OX=55583 GN=amt PE=3 SV=1
Number of features: 0
Seq('MNYTTGDIGFMIISTALVMLMTPGLAFFYGGLVKKRHVLSMMMQSIIAMGVVTL...YNL')
ID: tr|A0A916NVE1|A0A916NVE1_DEHMC
Name: tr|A0A916NVE1|A0A916NVE1_DEHMC
Description: tr|A0A916NVE1|A0A916NVE1_DEHMC Ammonium transporter OS=Dehalococcoides mccartyi (strain CBDB1) OX=255470 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SVR')
ID: tr|D2BIB2|D2BIB2_DEHMV
Name: tr|D2BIB2|D2BIB2_DEHMV
Description: tr|D2BIB2|D2BIB2_DEHMV Ammonium transporter OS=Dehalococcoides mccartyi (strain VS) OX=311424 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SLR')
ID: tr|Q3Z7F9|Q3Z7F9_DEHM1
Name: tr|Q3Z7F9|Q3Z7F9_DEHM1
Description: tr|Q3Z7F9|Q3Z7F9_DEHM1 Ammonium transporter OS=Dehalococcoides mccartyi (strain ATCC BAA-2266 / KCTC 15142 / 195) OX=243164 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SLR')
ID: tr|A0A142VAD6|A0A142VAD6_9CHLR
Name: tr|A0A142VAD6|A0A142VAD6_9CHLR
Description: tr|A0A142VAD6|A0A142VAD6_9CHLR Ammonium transporter OS=Dehalococcoides mccartyi OX=61435 GN=Dm11a5_0974 PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SVR')
ID: tr|A0A1S7AU71|A0A1S7AU71_9CHLR
Name: tr|A0A1S7AU71|A0A1S7AU71_9CHLR
Description: tr|A0A1S7AU71|A0A1S7AU71_9CHLR Ammonium transporter OS=Dehalococcoides mccartyi OX=61435 GN=B1775_04505 PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SVR')
ID: tr|A0A328EMN2|A0A328EMN2_9CHLR
Name: tr|A0A328EMN2|A0A328EMN2_9CHLR
Description: tr|A0A328EMN2|A0A328EMN2_9CHLR Ammonium transporter OS=Dehalococcoides mccartyi OX=61435 GN=C1G87_0999 PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SVR')
ID: tr|A0A2J1DY21|A0A2J1DY21_9CHLR
Name: tr|A0A2J1DY21|A0A2J1DY21_9CHLR
Description: tr|A0A2J1DY21|A0A2J1DY21_9CHLR Ammonium transporter OS=Dehalococcoides mccartyi OX=61435 GN=CVH13_00786 PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SVR')
ID: tr|A0A0V8M0W6|A0A0V8M0W6_9CHLR
Name: tr|A0A0V8M0W6|A0A0V8M0W6_9CHLR
Description: tr|A0A0V8M0W6|A0A0V8M0W6_9CHLR Ammonium transporter OS=Dehalococcoides mccartyi OX=61435 GN=C1O63_0110 PE=3 SV=1
Number of features: 0
Seq('MDSGDTTWLLVSTALVMLMTPGVALFYGGMVRRKNLVSTLMMSFGAMALGGVLW...SLR')
ID: tr|A0A089ZBW5|A0A089ZBW5_METFO
Name: tr|A0A089ZBW5|A0A089ZBW5_METFO
Description: tr|A0A089ZBW5|A0A089ZBW5_METFO Ammonium transporter OS=Methanobacterium formicicum OX=2162 GN=amt2 PE=3 SV=1
Number of features: 0
Seq('MDPVLNSGDTAWMLISTALVMIMTVPGVALFYGGLTKKVNVLNTMFMSLIAFSI...YRI')
ID: tr|A0A843AKI5|A0A843AKI5_METFO
Name: tr|A0A843AKI5|A0A843AKI5_METFO
Description: tr|A0A843AKI5|A0A843AKI5_METFO Ammonium transporter OS=Methanobacterium formicicum OX=2162 GN=ISP06_09620 PE=3 SV=1
Number of features: 0
Seq('MDPILSSGDTAWILISTALVILMTIPGVALFYGGLIRRENVLNTLFLSFITFSI...RLS')
ID: tr|A0A843AH20|A0A843AH20_METAZ
Name: tr|A0A843AH20|A0A843AH20_METAZ
Description: tr|A0A843AH20|A0A843AH20_METAZ Ammonium transporter OS=Methanobrevibacter arboriphilus OX=39441 GN=ISP01_03170 PE=3 SV=1
Number of features: 0
Seq('MEGILNAGDTSWVLISTILVLLMSIPGIAFFYGGLAKKKNVLNTMFLTLIAFSI...YRL')
ID: tr|A0A843AFK5|A0A843AFK5_METAZ
Name: tr|A0A843AFK5|A0A843AFK5_METAZ
Description: tr|A0A843AFK5|A0A843AFK5_METAZ Ammonium transporter OS=Methanobrevibacter arboriphilus OX=39441 GN=ISP01_08790 PE=3 SV=1
Number of features: 0
Seq('MVDILNTGDTAWILISTVLVLLMSIPGIAFFYGGLAKKKNVLNTMFLTLIAFAI...YML')
ID: tr|Q1IWN6|Q1IWN6_DEIGD
Name: tr|Q1IWN6|Q1IWN6_DEIGD
Description: tr|Q1IWN6|Q1IWN6_DEIGD Ammonium transporter OS=Deinococcus geothermalis (strain DSM 11300 / AG-3a) OX=319795 GN=Dgeo_2054 PE=3 SV=1
Number of features: 0
Seq('MKRLPLLVLLSGAALAQSATPTLDTGDTAWMLIAAALVLLMTPGLAFFYGGLTR...GGD')
ID: tr|A0A2W5H7U7|A0A2W5H7U7_DELAC
Name: tr|A0A2W5H7U7|A0A2W5H7U7_DELAC
Description: tr|A0A2W5H7U7|A0A2W5H7U7_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=DI604_01935 PE=3 SV=1
Number of features: 0
Seq('MGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPALSAGDTAW...YYR')
ID: tr|A0A7T2W1B3|A0A7T2W1B3_DELAC
Name: tr|A0A7T2W1B3|A0A7T2W1B3_DELAC
Description: tr|A0A7T2W1B3|A0A7T2W1B3_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=I6G66_11500 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQAAEQAITRPSLVAVESISAVDTVWLMTATV...LGG')
ID: tr|A0A2W5G0A5|A0A2W5G0A5_DELAC
Name: tr|A0A2W5G0A5|A0A2W5G0A5_DELAC
Description: tr|A0A2W5G0A5|A0A2W5G0A5_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=DI604_32370 PE=3 SV=1
Number of features: 0
Seq('MKRLIALLTLCASVGVAAPALAQQSTEGAGVPAAAQTEAKPAEAAPVTAAPVPA...AYN')
ID: tr|A0A286J4U5|A0A286J4U5_DELAC
Name: tr|A0A286J4U5|A0A286J4U5_DELAC
Description: tr|A0A286J4U5|A0A286J4U5_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=SAMN05216519_3445 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQTAQAAEQAITRPSLVAVESISAVDTVWLMT...LSG')
ID: tr|A0A2M9PTR1|A0A2M9PTR1_DELAC
Name: tr|A0A2M9PTR1|A0A2M9PTR1_DELAC
Description: tr|A0A2M9PTR1|A0A2M9PTR1_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=CTI10_006075 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVGGGWVAVLGAAQTAQAAEQAITRPSLVAVESISAVDTVWLMT...LSG')
ID: tr|A0A2W5IG33|A0A2W5IG33_DELAC
Name: tr|A0A2W5IG33|A0A2W5IG33_DELAC
Description: tr|A0A2W5IG33|A0A2W5IG33_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=DI604_17100 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQAAEQAITRPSLVAVESLSAVDTVWLMTATV...LSG')

ID: tr|A0A7T2S0Z6|A0A7T2S0Z6_DELAC
Name: tr|A0A7T2S0Z6|A0A7T2S0Z6_DELAC
Description: tr|A0A7T2S0Z6|A0A7T2S0Z6_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTKRLLSMGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPAL...YYR')
ID: tr|A0A7T4EM77|A0A7T4EM77_DELAC
Name: tr|A0A7T4EM77|A0A7T4EM77_DELAC
Description: tr|A0A7T4EM77|A0A7T4EM77_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTKRLLSMGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPAL...YYR')
ID: tr|A0A7U9HJZ8|A0A7U9HJZ8_DELAC
Name: tr|A0A7U9HJZ8|A0A7U9HJZ8_DELAC
Description: tr|A0A7U9HJZ8|A0A7U9HJZ8_DELAC Ammonium transporter OS=Delftia acidovorans CCUG 274B OX=883101 GN=HMPREF9701_03976 PE=3 SV=1
Number of features: 0
Seq('MGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPALSAGDTAW...YYR')
ID: tr|A0A7U9HH57|A0A7U9HH57_DELAC
Name: tr|A0A7U9HH57|A0A7U9HH57_DELAC
Description: tr|A0A7U9HH57|A0A7U9HH57_DELAC Ammonium transporter OS=Delftia acidovorans CCUG 274B OX=883101 GN=HMPREF9701_05247 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQAAEQAITRPSLVAVESLSAVDTVWLMTATV...LSG')
ID: tr|A9BQZ4|A9BQZ4_DELAS
Name: tr|A9BQZ4|A9BQZ4_DELAS
Description: tr|A9BQZ4|A9BQZ4_DELAS Ammonium transporter OS=Delftia acidovorans (strain DSM 14801 / SPH-1) OX=398578 GN=Daci_0303 PE=3 SV=1
Number of features: 0
Seq('MTKRLLSMGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPAL...YYR')
ID: tr|A9BTK1|A9BTK1_DELAS
Name: tr|A9BTK1|A9BTK1_DELAS
Description: tr|A9BTK1|A9BTK1_DELAS Ammonium transporter OS=Delftia acidovorans (strain DSM 14801 / SPH-1) OX=398578 GN=Daci_2331 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQTAQAAEQAITRPSLVAVESISAVDTVWLMT...LSG')
ID: tr|A0A1D8J0B0|A0A1D8J0B0_9BURK
Name: tr|A0A1D8J0B0|A0A1D8J0B0_9BURK
Description: tr|A0A1D8J0B0|A0A1D8J0B0_9BURK Ammonium transporter OS=Delftia tsuruhatensis OX=180282 GN=BI380_12545 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVAGGWVAVLGAAQTAQAAEQAITRPSLVAADSISAVDTVWLMT...LSG')
ID: tr|A0A1D8J5Y7|A0A1D8J5Y7_9BURK
Name: tr|A0A1D8J5Y7|A0A1D8J5Y7_9BURK
Description: tr|A0A1D8J5Y7|A0A1D8J5Y7_9BURK Ammonium transporter OS=Delftia tsuruhatensis OX=180282 GN=amt PE=3 SV=1
Number of features: 0
Seq('MGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPALSAGDTAW...YYR')
ID: tr|A0A080NRN5|A0A080NRN5_DELAC
Name: tr|A0A080NRN5|A0A080NRN5_DELAC
Description: tr|A0A080NRN5|A0A080NRN5_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=SAMN05216519_5351 PE=3 SV=1
Number of features: 0
Seq('MGLGLGLLAAGAAALAQEPAAAAAVADAAAAAAPAAAAAAEAPAPALSAGDTAW...YYR')
ID: tr|A0A7T4EQX0|A0A7T4EQX0_DELAC
Name: tr|A0A7T4EQX0|A0A7T4EQX0_DELAC
Description: tr|A0A7T4EQX0|A0A7T4EQX0_DELAC Ammonium transporter OS=Delftia acidovorans OX=80866 GN=I6H54_05900 PE=3 SV=1
Number of features: 0
Seq('MHRCARALRTLVGGGWAAVLGAARAAEQAITRPSLVAVESISAVDTVWLMTATV...LSG')
ID: tr|A0A172RYW3|A0A172RYW3_9ACTN
Name: tr|A0A172RYW3|A0A172RYW3_9ACTN
Description: tr|A0A172RYW3|A0A172RYW3_9ACTN Ammonium transporter OS=Denitrobacterium detoxificans OX=79604 GN=SAMN02910314_00987 PE=3 SV=1
Number of features: 0
Seq('MLDTGSSGFMLVSAMLVLLMTPGLAFFYGGLSRRKNVINTMFMSLAAIGIVGVV...GLD')
ID: tr|D4H2Y7|D4H2Y7_DENA2
Name: tr|D4H2Y7|D4H2Y7_DENA2
Description: tr|D4H2Y7|D4H2Y7_DENA2 Ammonium transporter OS=Denitrovibrio acetiphilus (strain DSM 12809 / NBRC 114555 / N2460) OX=522772 GN=Dacet_2248 PE=3 SV=1
Number of features: 0
Seq('MIRKILTTLILTGLAATAFAAEEPVTLETLSNDIASVQANADWLWTLIAAFMVF...YIK')
ID: tr|D4H0Y2|D4H0Y2_DENA2
Name: tr|D4H0Y2|D4H0Y2_DENA2
Description: tr|D4H0Y2|D4H0Y2_DENA2 Ammonium transporter OS=Denitrovibrio acetiphilus (strain DSM 12809 / NBRC 114555 / N2460) OX=522772 GN=Dacet_1881 PE=3 SV=1
Number of features: 0
Seq('MKSSESLLILYICFGILFAYNCYEIELRGDSMIRLLIVLLITMSASTAFADGLN...NFF')
ID: tr|D4H5F9|D4H5F9_DENA2
Name: tr|D4H5F9|D4H5F9_DENA2
Description: tr|D4H5F9|D4H5F9_DENA2 Ammonium transporter OS=Denitrovibrio acetiphilus (strain DSM 12809 / NBRC 114555 / N2460) OX=522772 GN=Dacet_0799 PE=3 SV=1
Number of features: 0
Seq('MDAVYSNIMWVLVCSFLVALMQAGFACLETGFVRSKNNVNVAVKNLVDFCISAS...SGT')
ID: tr|A0A075JIN0|A0A075JIN0_9MICO
Name: tr|A0A075JIN0|A0A075JIN0_9MICO
Description: tr|A0A075JIN0|A0A075JIN0_9MICO Ammonium transporter OS=Dermacoccus nishinomiyaensis OX=1274 GN=HX89_09745 PE=3 SV=1
Number of features: 0
Seq('MNAHLLAAEAAPKLDYAATAFVLVCASLVLMMTPALALFYGGMTRSKSVLNMMM...VQA')
ID: tr|A0A4U0RRD7|A0A4U0RRD7_9MICO
Name: tr|A0A4U0RRD7|A0A4U0RRD7_9MICO
Description: tr|A0A4U0RRD7|A0A4U0RRD7_9MICO Ammonium transporter OS=Dermacoccus nishinomiyaensis OX=1274 GN=FA951_01080 PE=3 SV=1
Number of features: 0
Seq('MNAHLLAAEAAPKLDYAATAFVLVCASLVLMMTPALALFYGGMTRSKSVLNMMM...VQA')
ID: tr|A0A8B6X901|A0A8B6X901_9BURK
Name: tr|A0A8B6X901|A0A8B6X901_9BURK
Description: tr|A0A8B6X901|A0A8B6X901_9BURK Ammonium transporter OS=Derxia gummosa DSM 723 OX=1121388 PE=3 SV=1
Number of features: 0
Seq('MQRRTHLETKGCGRLGALAASSALLLPLAARADDVPTQPFVVGFDAISAGDTAW...QVA')
ID: tr|A0A8B6X9K6|A0A8B6X9K6_9BURK
Name: tr|A0A8B6X9K6|A0A8B6X9K6_9BURK
Description: tr|A0A8B6X9K6|A0A8B6X9K6_9BURK Ammonium transporter OS=Derxia gummosa DSM 723 OX=1121388 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTRTLSSLLAAAVLTAGLGFSSVQAQDKPADAPAATAPAAEAPAAPAAAPAVEA...YHS')
ID: tr|A0A8B6XC37|A0A8B6XC37_9BURK
Name: tr|A0A8B6XC37|A0A8B6XC37_9BURK
Description: tr|A0A8B6XC37|A0A8B6XC37_9BURK Ammonium transporter OS=Derxia gummosa DSM 723 OX=1121388 PE=3 SV=1
Number of features: 0
Seq('MAQAGPPEPPSVEPPSHVDDAGRAAPEAVPVATPAVAPGAEPVTPIAASAPVAQ...ESA')
ID: tr|E1QIU3|E1QIU3_DESB2
Name: tr|E1QIU3|E1QIU3_DESB2
Description: tr|E1QIU3|E1QIU3_DESB2 Ammonium transporter OS=Desulfarculus baarsii (strain ATCC 33931 / DSM 2075 / LMG 7858 / VKM B-1802 / 2st14) OX=644282 GN=Deba_1148 PE=3 SV=1
Number of features: 0
Seq('MLRRITKNTMKLLTLGLLLPGAVMAEESAPPAVNDMDTMWVLLAAFLVFFMQPG...TTR')
ID: tr|E1QFA8|E1QFA8_DESB2
Name: tr|E1QFA8|E1QFA8_DESB2
Description: tr|E1QFA8|E1QFA8_DESB2 Ammonium transporter OS=Desulfarculus baarsii (strain ATCC 33931 / DSM 2075 / LMG 7858 / VKM B-1802 / 2st14) OX=644282 GN=Deba_0874 PE=3 SV=1
Number of features: 0
Seq('MAQINAGDTAWLMVCCSLVLMMTPALAFFYGGMVRKKNILSTLTLSYVFMALIG...AYS')
ID: tr|A0A1M6ZMI3|A0A1M6ZMI3_9BACT
Name: tr|A0A1M6ZMI3|A0A1M6ZMI3_9BACT
Description: tr|A0A1M6ZMI3|A0A1M6ZMI3_9BACT Ammonium transporter OS=Desulfatibacillum alkenivorans DSM 16219 OX=1121393 GN=SAMN02745216_05003 PE=3 SV=1
Number of features: 0
Seq('MKKAIYTLIFGIAASYAMADDAVPTVATNADAIALVQTHANFLWTLVAAALVFF...SHM')
ID: tr|A0A1M6JKY3|A0A1M6JKY3_9BACT
Name: tr|A0A1M6JKY3|A0A1M6JKY3_9BACT
Description: tr|A0A1M6JKY3|A0A1M6JKY3_9BACT Ammonium transporter OS=Desulfatibacillum alkenivorans DSM 16219 OX=1121393 GN=SAMN02745216_01699 PE=3 SV=1
Number of features: 0
Seq('MKKRIALLLLFIALALPQAALAQEGAPCDSGTTAWMLTSTALVLLMVPGLAMFY...NLA')
ID: tr|B8FL88|B8FL88_DESAL
Name: tr|B8FL88|B8FL88_DESAL
Description: tr|B8FL88|B8FL88_DESAL Ammonium transporter OS=Desulfatibacillum aliphaticivorans OX=218208 GN=Dalk_3033 PE=3 SV=1
Number of features: 0
Seq('MKKAIYTLIFGIAASYAMADDAVPTVATNADAIALVQTHANFLWTLVAAALVFF...SHM')
ID: tr|B8FGW0|B8FGW0_DESAL
Name: tr|B8FGW0|B8FGW0_DESAL
Description: tr|B8FGW0|B8FGW0_DESAL Ammonium transporter OS=Desulfatibacillum aliphaticivorans OX=218208 GN=Dalk_3652 PE=3 SV=1
Number of features: 0
Seq('MKKRIALLLLFIALALPQAAFAQEGGACDSGTTAWMLTSTALVLLMVPGLAMFY...NLA')
ID: tr|A0A1M6BPM0|A0A1M6BPM0_9BACT
Name: tr|A0A1M6BPM0|A0A1M6BPM0_9BACT
Description: tr|A0A1M6BPM0|A0A1M6BPM0_9BACT Ammonium transporter OS=Desulfatibacillum alkenivorans DSM 16219 OX=1121393 GN=SAMN02745216_00035 PE=3 SV=1
Number of features: 0
Seq('MNSGDIAWMLCASAMVLFMTPGLAIFYGGLVRSKNVLGTIMHSFIIMGVVSIMW...RIV')
ID: tr|B8FDY8|B8FDY8_DESAL
Name: tr|B8FDY8|B8FDY8_DESAL
Description: tr|B8FDY8|B8FDY8_DESAL Ammonium transporter OS=Desulfatibacillum aliphaticivorans OX=218208 GN=Dalk_5098 PE=3 SV=1
Number of features: 0
Seq('MNSGDIAWMLCASAMVLFMTPGLAIFYGGLVRSKNVLGTIMHSFIIMGVVSIMW...RIV')
ID: tr|A0A7C4RTW1|A0A7C4RTW1_9BACT
Name: tr|A0A7C4RTW1|A0A7C4RTW1_9BACT
Description: tr|A0A7C4RTW1|A0A7C4RTW1_9BACT Ammonium transporter OS=Desulfatirhabdium butyrativorans OX=340467 GN=ENS29_14540 PE=3 SV=1
Number of features: 0
Seq('MLKRVVSGLIVILGLANQVWAADGMDSGNTAWVLVSAALVMMMTPAGLALFYGG...IQV')

ID: tr|A0A098B6P8|A0A098B6P8_DESHA
Name: tr|A0A098B6P8|A0A098B6P8_DESHA
Description: tr|A0A098B6P8|A0A098B6P8_DESHA Ammonium transporter OS=Desulfitobacterium hafniense OX=49338 GN=DPCES_4623 PE=3 SV=1
Number of features: 0
Seq('MKRVWVLLLAIISMLALPVAVLAEDGAVVDTGDTSFIILSAALVFLMTPGLALF...PGK')
ID: tr|A0A0W1JII4|A0A0W1JII4_DESHA
Name: tr|A0A0W1JII4|A0A0W1JII4_DESHA
Description: tr|A0A0W1JII4|A0A0W1JII4_DESHA Ammonium transporter OS=Desulfitobacterium hafniense OX=49338 GN=AT727_21725 PE=3 SV=1
Number of features: 0
Seq('MKRVWVLLLAIISMLALPVAVLAEDGAVVDTGDTSFIILSAALVFLMTPGLALF...PGK')
ID: tr|Q24PJ2|Q24PJ2_DESHY
Name: tr|Q24PJ2|Q24PJ2_DESHY
Description: tr|Q24PJ2|Q24PJ2_DESHY Ammonium transporter OS=Desulfitobacterium hafniense (strain Y51) OX=138119 GN=DSY4261 PE=3 SV=1
Number of features: 0
Seq('MKRVWVLLLAIISMLALPVAVLAEDGAVVDTGDTSFIILSAALVFLMTPGLALF...PGK')
ID: tr|B8FZP7|B8FZP7_DESHD
Name: tr|B8FZP7|B8FZP7_DESHD
Description: tr|B8FZP7|B8FZP7_DESHD Ammonium transporter OS=Desulfitobacterium hafniense (strain DSM 10664 / DCB-2) OX=272564 GN=Dhaf_1061 PE=3 SV=1
Number of features: 0
Seq('MKRVWVLLLAIISMLALPVAVLAEDGAVVDTGDTSFIILSAALVFLMTPGLALF...PGK')
ID: tr|G9XQB9|G9XQB9_DESHA
Name: tr|G9XQB9|G9XQB9_DESHA
Description: tr|G9XQB9|G9XQB9_DESHA Ammonium transporter OS=Desulfitobacterium hafniense DP7 OX=537010 GN=HMPREF0322_03165 PE=3 SV=1
Number of features: 0
Seq('MCKSKRENPGWSISGGSLFFFSTDVHHYYLNKNHFKERGEWTRRTSTVFENYLS...PGK')
ID: tr|A0A7C3Z0B6|A0A7C3Z0B6_9BACT
Name: tr|A0A7C3Z0B6|A0A7C3Z0B6_9BACT
Description: tr|A0A7C3Z0B6|A0A7C3Z0B6_9BACT Ammonium transporter OS=Desulfobacca acetoxidans OX=60893 GN=ENW96_03930 PE=3 SV=1
Number of features: 0
Seq('MHTAISAGDTAWVLVSCALVLMMTPALALFYGGMARRKNTLSTLTLSFVFMALI...AYS')
ID: tr|A0A7C3WRX0|A0A7C3WRX0_9BACT
Name: tr|A0A7C3WRX0|A0A7C3WRX0_9BACT
Description: tr|A0A7C3WRX0|A0A7C3WRX0_9BACT Ammonium transporter OS=Desulfobacca acetoxidans OX=60893 GN=ENV62_09410 PE=3 SV=1
Number of features: 0
Seq('MNPADTAFVLFSAALVMLMTPGLALFYGGLVRSKNVLGTIMQNFFLLGVMGIQW...YSL')
ID: tr|A0A7V6A2R5|A0A7V6A2R5_9BACT
Name: tr|A0A7V6A2R5|A0A7V6A2R5_9BACT
Description: tr|A0A7V6A2R5|A0A7V6A2R5_9BACT Ammonium transporter OS=Desulfobacca acetoxidans OX=60893 GN=ENV52_05140 PE=3 SV=1
Number of features: 0
Seq('MNTAINAGDTAWVLMSCALVLMMTPALAFFYGGMARRKNMLSTLTLTYVFLALI...AYS')
ID: tr|A0A7C3ZC37|A0A7C3ZC37_9BACT
Name: tr|A0A7C3ZC37|A0A7C3ZC37_9BACT
Description: tr|A0A7C3ZC37|A0A7C3ZC37_9BACT Ammonium transporter OS=Desulfobacca acetoxidans OX=60893 GN=ENW96_12680 PE=3 SV=1
Number of features: 0
Seq('MNAANTAFVLVSAALVMFMTPGLALFYGGMVRGKNVLGTLMQNFILIALIGVEW...YSL')
ID: tr|A0A7V6A1Z5|A0A7V6A1Z5_9BACT
Name: tr|A0A7V6A1Z5|A0A7V6A1Z5_9BACT
Description: tr|A0A7V6A1Z5|A0A7V6A1Z5_9BACT Ammonium transporter OS=Desulfobacca acetoxidans OX=60893 GN=ENV52_02690 PE=3 SV=1
Number of features: 0
Seq('MNAANTAFVLISAALVLFMTPGLALFYGGMVRGKNVLGTLMQNFILIALMGVQW...YSL')
ID: tr|F2NGJ8|F2NGJ8_DESAR
Name: tr|F2NGJ8|F2NGJ8_DESAR
Description: tr|F2NGJ8|F2NGJ8_DESAR Ammonium transporter OS=Desulfobacca acetoxidans (strain ATCC 700848 / DSM 11109 / ASRB2) OX=880072 GN=Desac_0006 PE=3 SV=1
Number of features: 0
Seq('MNSGDTAFVLFSAALVLFMTPGLALFYGGMARSKNVLNTLMQNFIMIALVGVQW...YSL')
ID: tr|I5AZQ4|I5AZQ4_9BACT
Name: tr|I5AZQ4|I5AZQ4_9BACT
Description: tr|I5AZQ4|I5AZQ4_9BACT Ammonium transporter OS=Desulfobacter postgatei 2ac9 OX=879212 GN=DespoDRAFT_00726 PE=3 SV=1
Number of features: 0
Seq('MMFKHCILTIVLIMFNVCPALAGEGTIDTGNTAWVIMSTALVMMMTPAGLALFY...EIE')
ID: tr|I5B3H0|I5B3H0_9BACT
Name: tr|I5B3H0|I5B3H0_9BACT
Description: tr|I5B3H0|I5B3H0_9BACT Ammonium transporter OS=Desulfobacter postgatei 2ac9 OX=879212 GN=DespoDRAFT_02147 PE=3 SV=1
Number of features: 0
Seq('MKYALMILTSLACTITAAWAGTDDAPTVVSNAEAIQLVQTHADYVWTLVSAALV...GSH')
ID: tr|K0NJH2|K0NJH2_DESTT
Name: tr|K0NJH2|K0NJH2_DESTT
Description: tr|K0NJH2|K0NJH2_DESTT Ammonium transporter OS=Desulfobacula toluolica (strain DSM 7467 / Tol2) OX=651182 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKLALTIVCCLACSISVVWAGDDAPTITSNKAAIALVQSHADYVWTLVAAMLV...KQT')
ID: tr|K0N2R5|K0N2R5_DESTT
Name: tr|K0N2R5|K0N2R5_DESTT
Description: tr|K0N2R5|K0N2R5_DESTT Ammonium transporter OS=Desulfobacula toluolica (strain DSM 7467 / Tol2) OX=651182 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MLGKKILMSSGGVLLTATRAFAEAGVIDTGDTAWVTISTALVMMMTPAGLALFY...EIE')
ID: tr|A0A562RGZ4|A0A562RGZ4_9BACT
Name: tr|A0A562RGZ4|A0A562RGZ4_9BACT
Description: tr|A0A562RGZ4|A0A562RGZ4_9BACT Ammonium transporter OS=Desulfobotulus alkaliphilus OX=622671 GN=LZ24_02625 PE=3 SV=1
Number of features: 0
Seq('MRWFIPTSILISMATPALAGDVTPMTNAEAIALVQEHANFVWTLMAACLVFFMQ...TQS')
ID: tr|A0A562S8V2|A0A562S8V2_9BACT
Name: tr|A0A562S8V2|A0A562S8V2_9BACT
Description: tr|A0A562S8V2|A0A562S8V2_9BACT Ammonium transporter OS=Desulfobotulus alkaliphilus OX=622671 GN=LZ24_00488 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAFMLVAAALVMFMTPGLALFYGGLVRSRNVLSTILQSFICLGMVSLIW...YTL')
ID: tr|A0A7U3YMN6|A0A7U3YMN6_DESPD
Name: tr|A0A7U3YMN6|A0A7U3YMN6_DESPD
Description: tr|A0A7U3YMN6|A0A7U3YMN6_DESPD Ammonium transporter OS=Desulfobulbus propionicus (strain ATCC 33891 / DSM 2032 / VKM B-1956 / 1pr3) OX=577650 GN=Despr_2064 PE=3 SV=1
Number of features: 0
Seq('MKKSTVVSSLILAAIAVVAAAMPVLAETAAPVPEKGDTAWMIVATLLVTLMTIP...YHY')
ID: tr|A0A7U4DN04|A0A7U4DN04_DESPD
Name: tr|A0A7U4DN04|A0A7U4DN04_DESPD
Description: tr|A0A7U4DN04|A0A7U4DN04_DESPD Ammonium transporter OS=Desulfobulbus propionicus (strain ATCC 33891 / DSM 2032 / VKM B-1956 / 1pr3) OX=577650 GN=Despr_0370 PE=3 SV=1
Number of features: 0
Seq('MINGADTAFILAAAGLVLLMTPGLALFYAGMVRSKNVLGTIMQSLVLISLVSLE...AYN')
ID: tr|M1P5F0|M1P5F0_DESSD
Name: tr|M1P5F0|M1P5F0_DESSD
Description: tr|M1P5F0|M1P5F0_DESSD Ammonium transporter OS=Desulfocapsa sulfexigens (strain DSM 10523 / SB164P1) OX=1167006 GN=UWK_00327 PE=3 SV=1
Number of features: 0
Seq('MKNSVTMTRKTFWGGVAVLSGLALAGPAIAEEAAAASSVADNLIQLAYSVDTFY...TRD')
ID: tr|M1NZT5|M1NZT5_DESSD
Name: tr|M1NZT5|M1NZT5_DESSD
Description: tr|M1NZT5|M1NZT5_DESSD Ammonium transporter OS=Desulfocapsa sulfexigens (strain DSM 10523 / SB164P1) OX=1167006 GN=UWK_00207 PE=3 SV=1
Number of features: 0
Seq('MKNSVTMNGKTFWGGVVFLSGLALAGPAIAEEAAAASSVADNLIQLAYSVDTFY...TRD')
ID: tr|M1WRK6|M1WRK6_PSEP2
Name: tr|M1WRK6|M1WRK6_PSEP2
Description: tr|M1WRK6|M1WRK6_PSEP2 Ammonium transporter OS=Pseudodesulfovibrio piezophilus (strain DSM 21447 / JCM 15486 / C1TLV30) OX=1322246 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MNFVDNAFILICAALVMFMTPGLALFYGGLVRSKNVLATIMQSFIMLGLVSILW...YQW')
ID: tr|C8WZE0|C8WZE0_DESRD
Name: tr|C8WZE0|C8WZE0_DESRD
Description: tr|C8WZE0|C8WZE0_DESRD Ammonium transporter OS=Desulfohalobium retbaense (strain ATCC 49708 / DSM 5692 / JCM 16813 / HR100) OX=485915 GN=Dret_0113 PE=3 SV=1
Number of features: 0
Seq('MRSRKTSLCKSNVLRPLAFAAVLGFVPTMALAAEAPLSQFHGNILWTLIAAILV...STE')
ID: tr|C8X554|C8X554_DESRD
Name: tr|C8X554|C8X554_DESRD
Description: tr|C8X554|C8X554_DESRD Ammonium transporter OS=Desulfohalobium retbaense (strain ATCC 49708 / DSM 5692 / JCM 16813 / HR100) OX=485915 GN=Dret_2267 PE=3 SV=1
Number of features: 0
Seq('MSPADTGFILICAALVMLMTPGLALFYAGMTRSKNVLGTLMQSFIALAVVTVVW...YQW')
ID: tr|C7LW88|C7LW88_DESBD
Name: tr|C7LW88|C7LW88_DESBD
Description: tr|C7LW88|C7LW88_DESBD Ammonium transporter OS=Desulfomicrobium baculatum (strain DSM 4028 / VKM B-1378 / X) OX=525897 GN=Dbac_3049 PE=3 SV=1
Number of features: 0
Seq('MFEEKKQTTALLRPKVWALTLLLATLTPAMAFAEGEALSQSNANLLWTLLAAIL...TNE')
ID: tr|C7LW87|C7LW87_DESBD
Name: tr|C7LW87|C7LW87_DESBD
Description: tr|C7LW87|C7LW87_DESBD Ammonium transporter OS=Desulfomicrobium baculatum (strain DSM 4028 / VKM B-1378 / X) OX=525897 GN=Dbac_3048 PE=3 SV=1
Number of features: 0
Seq('MNPTDTAFIIVCAALVMFMTPGLALFYAGMTRSKNALGTIMQSFASLGVITLVW...YQA')
ID: tr|C7LQR9|C7LQR9_DESBD
Name: tr|C7LQR9|C7LQR9_DESBD
Description: tr|C7LQR9|C7LQR9_DESBD Diguanylate cyclase/phosphodiesterase with PAS/PAC sensor(S) OS=Desulfomicrobium baculatum (strain DSM 4028 / VKM B-1378 / X) OX=525897 GN=Dbac_1035 PE=3 SV=1
Number of features: 0
Seq('MNNVDMLWIIISASLVFLMQPGFMCLESGMTRSKNSINVAIKNFADFVLSAGVF...VPN')
ID: tr|A0A7C4EVF7|A0A7C4EVF7_9BACT
Name: tr|A0A7C4EVF7|A0A7C4EVF7_9BACT
Description: tr|A0A7C4EVF7|A0A7C4EVF7_9BACT Ammonium transporter OS=Desulfomonile tiedjei OX=2358 GN=ENV54_12725 PE=3 SV=1
Number of features: 0
Seq('MNAADNAWVLVSSALVLLMTPGLAMFYGGLTRSKNVLSTMMHSFFLMGLASVIW...YTL')

ID: tr|I4C9L0|I4C9L0_DESTA
Name: tr|I4C9L0|I4C9L0_DESTA
Description: tr|I4C9L0|I4C9L0_DESTA Ammonium transporter OS=Desulfomonile tiedjei (strain ATCC 49306 / DSM 6799 / DCB-1) OX=706587 GN=Desti_3603 PE=3 SV=1
Number of features: 0
Seq('MNPADNAWVLVASALVLLMTPGLAMFYGGLTRSKNVLSTMMHSFFLMGLASIIW...YTL')
ID: tr|I4CCD1|I4CCD1_DESTA
Name: tr|I4CCD1|I4CCD1_DESTA
Description: tr|I4CCD1|I4CCD1_DESTA Ammonium transporter OS=Desulfomonile tiedjei (strain ATCC 49306 / DSM 6799 / DCB-1) OX=706587 GN=Desti_4596 PE=3 SV=1
Number of features: 0
Seq('MNTGDNAWVLASAALVFLMTPAVALFYGGMTRTKNVLATIMQSFIVMGLVSVVW...YNF')
ID: tr|I4C9L2|I4C9L2_DESTA
Name: tr|I4C9L2|I4C9L2_DESTA
Description: tr|I4C9L2|I4C9L2_DESTA Ammonium transporter OS=Desulfomonile tiedjei (strain ATCC 49306 / DSM 6799 / DCB-1) OX=706587 GN=Desti_3605 PE=3 SV=1
Number of features: 0
Seq('MDGANTAFVMACSALVLVMTPGLAIFYGGLTNSKNVLSTMMHSFFLMGLASVAW...YNF')
ID: tr|D6SPD1|D6SPD1_9BACT
Name: tr|D6SPD1|D6SPD1_9BACT
Description: tr|D6SPD1|D6SPD1_9BACT Ammonium transporter OS=Desulfonatronospira thiodismutans ASO3-1 OX=555779 GN=Dthio_PD1979 PE=3 SV=1
Number of features: 0
Seq('MEGLLELSYALDTFYFLLSGLLVMWMAAGFTMLESGLVRSKNTVEILTKNVALY...GTK')
ID: tr|A0A975GIX9|A0A975GIX9_9BACT
Name: tr|A0A975GIX9|A0A975GIX9_9BACT
Description: tr|A0A975GIX9|A0A975GIX9_9BACT Ammonium transporter OS=Desulfonema limicola OX=45656 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKQKTLMLTLILSFLPLSSAFAEDVLNTGDTAWIIVSTALVMMMTPAGLALFYG...IEF')
ID: tr|A0A975BTN0|A0A975BTN0_9BACT
Name: tr|A0A975BTN0|A0A975BTN0_9BACT
Description: tr|A0A975BTN0|A0A975BTN0_9BACT Ammonium transporter OS=Desulfonema magnum OX=45655 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKLKSLVLTAIFSMMPFSLAFAEGDTLNSGDTAWLIVSTALVMVMTPAGLALFY...EIE')
ID: tr|G7WFX2|G7WFX2_DESOD
Name: tr|G7WFX2|G7WFX2_DESOD
Description: tr|G7WFX2|G7WFX2_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_4045 PE=3 SV=1
Number of features: 0
Seq('MNINHLWLIVSACFVFFMQAGFVCYEVGFIRSKNVISVAIENILTFVITTLVYC...YEY')
ID: tr|I4D6Z9|I4D6Z9_DESAJ
Name: tr|I4D6Z9|I4D6Z9_DESAJ
Description: tr|I4D6Z9|I4D6Z9_DESAJ Ammonium transporter OS=Desulfosporosinus acidiphilus (strain DSM 22704 / JCM 16185 / SJ4) OX=646529 GN=Desaci_2640 PE=3 SV=1
Number of features: 0
Seq('MSINHLWIIVSACFVFFMQAGFVCYEVGFIQSKNVISVAIENIITFVITTLVYC...FED')
ID: tr|G7WDB5|G7WDB5_DESOD
Name: tr|G7WDB5|G7WDB5_DESOD
Description: tr|G7WDB5|G7WDB5_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_1989 PE=3 SV=1
Number of features: 0
Seq('MDFVSMLTEENAYMFNSIWVMVAAVFVFLMQPGFALMESGFSRSKNACNIWLKN...YHQ')
ID: tr|G7WFX4|G7WFX4_DESOD
Name: tr|G7WFX4|G7WFX4_DESOD
Description: tr|G7WFX4|G7WFX4_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_4047 PE=3 SV=1
Number of features: 0
Seq('MINSGDTAFVLISAALVCLMTPGLAFFYGGLVRKKNVLTIMIQSFISMGIVTAI...YEL')
ID: tr|G7WCB6|G7WCB6_DESOD
Name: tr|G7WCB6|G7WCB6_DESOD
Description: tr|G7WCB6|G7WCB6_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_5356 PE=3 SV=1
Number of features: 0
Seq('MSKQWRFGILARGLKVLLVFKEGLRVDTGDTAFIIVSSAMVLLMTPGLALFYGG...EFI')
ID: tr|G7WJN0|G7WJN0_DESOD
Name: tr|G7WJN0|G7WJN0_DESOD
Description: tr|G7WJN0|G7WJN0_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_5075 PE=3 SV=1
Number of features: 0
Seq('MKTRTPLLKKGIILGLITALFLSIPGIALGADPSVESNAVAIDTVWTLVAGFLV...VNI')
ID: tr|G7WA28|G7WA28_DESOD
Name: tr|G7WA28|G7WA28_DESOD
Description: tr|G7WA28|G7WA28_DESOD Ammonium transporter OS=Desulfosporosinus orientis (strain ATCC 19365 / DSM 765 / NCIMB 8382 / VKM B-1628 / Singapore I) OX=768706 GN=Desor_0310 PE=3 SV=1
Number of features: 0
Seq('MSALNPGDISFVVICTLIVFLMTPGLALFYGGMVRKRNVLSIMMQSFVAIAVVT...VYI')
ID: tr|I4D1H5|I4D1H5_DESAJ
Name: tr|I4D1H5|I4D1H5_DESAJ
Description: tr|I4D1H5|I4D1H5_DESAJ Ammonium transporter OS=Desulfosporosinus acidiphilus (strain DSM 22704 / JCM 16185 / SJ4) OX=646529 GN=Desaci_0587 PE=3 SV=1
Number of features: 0
Seq('MALNSGDIAFVFLSTILVFLMTPGLALFYGGMVRKRNVLSIMMQSFAAIGLVTV...VYI')
ID: tr|I4D6Z7|I4D6Z7_DESAJ
Name: tr|I4D6Z7|I4D6Z7_DESAJ
Description: tr|I4D6Z7|I4D6Z7_DESAJ Ammonium transporter OS=Desulfosporosinus acidiphilus (strain DSM 22704 / JCM 16185 / SJ4) OX=646529 GN=Desaci_2638 PE=3 SV=1
Number of features: 0
Seq('MINTGDTAFVLISAALVCLMTPGLAFFYGGLVRKKNVLTIMIQNFVSMGIVTAI...AYL')
ID: tr|I4DBY0|I4DBY0_DESAJ
Name: tr|I4DBY0|I4DBY0_DESAJ
Description: tr|I4DBY0|I4DBY0_DESAJ Ammonium transporter OS=Desulfosporosinus acidiphilus (strain DSM 22704 / JCM 16185 / SJ4) OX=646529 GN=Desaci_4461 PE=3 SV=1
Number of features: 0
Seq('MNTGDTAFVLVSTALVLLMTPGLAFFYGGMVRKKNVLSTIMHSWIIIGLISLQW...DFI')
ID: tr|J7IVQ1|J7IVQ1_DESMD
Name: tr|J7IVQ1|J7IVQ1_DESMD
Description: tr|J7IVQ1|J7IVQ1_DESMD Ammonium transporter OS=Desulfosporosinus meridiei (strain ATCC BAA-275 / DSM 13257 / KCTC 12902 / NCIMB 13706 / S10) OX=768704 GN=Desmer_4071 PE=3 SV=1
Number of features: 0
Seq('MKTRFRKNGIFLGIFTALLLAIPGIALGAEPSVESNAVAIDTIWTLIAGFLVFF...VNI')
ID: tr|J7ITF6|J7ITF6_DESMD
Name: tr|J7ITF6|J7ITF6_DESMD
Description: tr|J7ITF6|J7ITF6_DESMD Ammonium transporter OS=Desulfosporosinus meridiei (strain ATCC BAA-275 / DSM 13257 / KCTC 12902 / NCIMB 13706 / S10) OX=768704 GN=Desmer_0312 PE=3 SV=1
Number of features: 0
Seq('MTTLDTGDISFLVVCTLLVFLMTPGLALFYGGMVRKRNVLSIMMQSYAAMGIVT...VYI')
ID: tr|J7J5E7|J7J5E7_DESMD
Name: tr|J7J5E7|J7J5E7_DESMD
Description: tr|J7J5E7|J7J5E7_DESMD Ammonium transporter OS=Desulfosporosinus meridiei (strain ATCC BAA-275 / DSM 13257 / KCTC 12902 / NCIMB 13706 / S10) OX=768704 GN=Desmer_4354 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAFILVSSAMVLLMTPGLALFYGGMVRKKNVLGTFMHSWITIGLISLQW...EFI')
ID: tr|Q6ARH0|Q6ARH0_DESPS
Name: tr|Q6ARH0|Q6ARH0_DESPS
Description: tr|Q6ARH0|Q6ARH0_DESPS Ammonium transporter OS=Desulfotalea psychrophila (strain LSv54 / DSM 12343) OX=177439 GN=DP0326 PE=3 SV=1
Number of features: 0
Seq('MTRRAGIKFTGIGLAFLSLSVTGQPVHGAEQELTHSVAEIAYGLDTLYLLLSGA...TKD')
ID: tr|S0G181|S0G181_9BACT
Name: tr|S0G181|S0G181_9BACT
Description: tr|S0G181|S0G181_9BACT Ammonium transporter OS=Desulfotignum phosphitoxidans DSM 13687 OX=1286635 GN=Dpo_11c00990 PE=3 SV=1
Number of features: 0
Seq('MKSRSLHKRILPLTITMSTLPAAALAADGAAEITGAAATYVANNTWMLVATFLV...SAI')
ID: tr|A0A4Y3TAU0|A0A4Y3TAU0_DESDE
Name: tr|A0A4Y3TAU0|A0A4Y3TAU0_DESDE
Description: tr|A0A4Y3TAU0|A0A4Y3TAU0_DESDE Ammonium transporter OS=Desulfovibrio desulfuricans OX=876 GN=amt PE=3 SV=1
Number of features: 0
Seq('MNAADTAFILICAALVMLMTPGLALFYGGLVRAKNVLSTTMHSFVLVGVASVVW...YEQ')
ID: tr|A0A8G2F718|A0A8G2F718_DESNO
Name: tr|A0A8G2F718|A0A8G2F718_DESNO
Description: tr|A0A8G2F718|A0A8G2F718_DESNO Ammonium transporter OS=Desulfomicrobium norvegicum (strain DSM 1741 / NCIMB 8310) OX=52561 GN=SAMN05421830_10290 PE=3 SV=1
Number of features: 0
Seq('MFEEKKQTTALLRPKVWALTLLLATFTPAMAFAEGEALSQSNANLLWTLLAAIL...TNE')
ID: tr|A0A4P7UHQ5|A0A4P7UHQ5_DESDE
Name: tr|A0A4P7UHQ5|A0A4P7UHQ5_DESDE
Description: tr|A0A4P7UHQ5|A0A4P7UHQ5_DESDE Ammonium transporter OS=Desulfovibrio desulfuricans OX=876 GN=DDIC_08045 PE=3 SV=1
Number of features: 0
Seq('MNASDTAFILICASMVMLMTPALALFYGGLVRSRNILSTHMHSYGALALISVLW...YSL')
ID: tr|B8IZX4|B8IZX4_DESDA
Name: tr|B8IZX4|B8IZX4_DESDA
Description: tr|B8IZX4|B8IZX4_DESDA Ammonium transporter OS=Desulfovibrio desulfuricans (strain ATCC 27774 / DSM 6949 / MB) OX=525146 GN=Ddes_1147 PE=3 SV=1
Number of features: 0
Seq('MNAPDTAFVIICATMVMLMIPALALFYGGLVRARNVLSTHMYSYACLGLVSVLW...YNL')
ID: tr|A0A8G2F3G4|A0A8G2F3G4_DESNO
Name: tr|A0A8G2F3G4|A0A8G2F3G4_DESNO
Description: tr|A0A8G2F3G4|A0A8G2F3G4_DESNO Ammonium transporter OS=Desulfomicrobium norvegicum (strain DSM 1741 / NCIMB 8310) OX=52561 GN=SAMN05421830_10289 PE=3 SV=1
Number of features: 0
Seq('MNPTDTAFIIICAALVMFMTPGLALFYAGMTRSKNALGTIMQSFAALGVITLVW...YQA')
ID: tr|A0A8G2C5E0|A0A8G2C5E0_DESNO
Name: tr|A0A8G2C5E0|A0A8G2C5E0_DESNO
Description: tr|A0A8G2C5E0|A0A8G2C5E0_DESNO Ammonium transporter, Amt family OS=Desulfomicrobium norvegicum (strain DSM 1741 / NCIMB 8310) OX=52561 GN=SAMN05421830_11448 PE=3 SV=1
Number of features: 0
Seq('MEKIDLLWILISASLVFLMQPGFMCLESGLTRSKNSINVAIKNFADFVLSAAVF...GSN')

ID: tr|F0JGZ1|F0JGZ1_9BACT
Name: tr|F0JGZ1|F0JGZ1_9BACT
Description: tr|F0JGZ1|F0JGZ1_9BACT Ammonium transporter OS=Pseudodesulfovibrio mercurii OX=641491 GN=DND132_1975 PE=3 SV=1
Number of features: 0
Seq('MNYTDNAFILVCAALVMFMTPGLALFYGGLVRSKNVLATIMQSFIMLGLMSVLW...YQW')
ID: tr|A0A7C2VMH5|A0A7C2VMH5_DESAE
Name: tr|A0A7C2VMH5|A0A7C2VMH5_DESAE
Description: tr|A0A7C2VMH5|A0A7C2VMH5_DESAE Ammonium transporter OS=Desulfurella acetivorans OX=33002 GN=ENO40_03605 PE=3 SV=1
Number of features: 0
Seq('MFIKSFYRFFGVLLFLLMPSIALAQNHPLNQANTAWMLISTALVLSMTPVGLGL...FDI')
ID: tr|E6W5C1|E6W5C1_DESIS
Name: tr|E6W5C1|E6W5C1_DESIS
Description: tr|E6W5C1|E6W5C1_DESIS Ammonium transporter OS=Desulfurispirillum indicum (strain ATCC BAA-1389 / DSM 22839 / S5) OX=653733 GN=Selin_0093 PE=3 SV=1
Number of features: 0
Seq('MEGIVLELPFILDSFLMVFAGILVMIMACGFAMLESGLTRSKNTATIMTKNVLI...KIL')
ID: tr|D6Z5V9|D6Z5V9_DESAT
Name: tr|D6Z5V9|D6Z5V9_DESAT
Description: tr|D6Z5V9|D6Z5V9_DESAT Ammonium transporter OS=Desulfurivibrio alkaliphilus (strain DSM 19089 / UNIQEM U267 / AHT2) OX=589865 GN=DaAHT2_0128 PE=3 SV=1
Number of features: 0
Seq('MKSKSIIAAAVCGLVATALPVAGWAGEQAVSGGDAIFTANNTWMLVATFLVFLM...NTK')
ID: tr|F0S0G1|F0S0G1_DESTD
Name: tr|F0S0G1|F0S0G1_DESTD
Description: tr|F0S0G1|F0S0G1_DESTD Ammonium transporter OS=Desulfurobacterium thermolithotrophum (strain DSM 11699 / BSA) OX=868864 GN=Dester_0029 PE=3 SV=1
Number of features: 0
Seq('MKRILGVLLMALTPLAAMAEETPTLNSGDTAWMLVSTALVMLMTPAGLALFYGG...FNL')
ID: tr|F0S3Z6|F0S3Z6_DESTD
Name: tr|F0S3Z6|F0S3Z6_DESTD
Description: tr|F0S3Z6|F0S3Z6_DESTD Ammonium transporter OS=Desulfurobacterium thermolithotrophum (strain DSM 11699 / BSA) OX=868864 GN=Dester_0929 PE=3 SV=1
Number of features: 0
Seq('MVEESIKQLIQSLNVFYLLAGAVMILSMHAGFAFLEAGTVRKKNQVNALVKIIV...LKV')
ID: tr|Q1K3N8|Q1K3N8_DESA6
Name: tr|Q1K3N8|Q1K3N8_DESA6
Description: tr|Q1K3N8|Q1K3N8_DESA6 Ammonium transporter OS=Desulfuromonas acetoxidans (strain DSM 684 / 11070) OX=281689 GN=Dace_2802 PE=3 SV=1
Number of features: 0
Seq('MKRLLSLILVGAFLALPVFALADEAAPITPDDVQNNLNFVWTLVAAFLVFLMQA...TQA')
ID: tr|Q1JXS5|Q1JXS5_DESA6
Name: tr|Q1JXS5|Q1JXS5_DESA6
Description: tr|Q1JXS5|Q1JXS5_DESA6 Ammonium transporter OS=Desulfuromonas acetoxidans (strain DSM 684 / 11070) OX=281689 GN=Dace_1145 PE=3 SV=1
Number of features: 0
Seq('MLRYACRMVPGLLFAPATCLAAETTCDSGTTAWMMISVALVLLMIPGLAMFYGG...ING')
ID: tr|Q1K0H9|Q1K0H9_DESA6
Name: tr|Q1K0H9|Q1K0H9_DESA6
Description: tr|Q1K0H9|Q1K0H9_DESA6 Ammonium transporter OS=Desulfuromonas acetoxidans (strain DSM 684 / 11070) OX=281689 GN=Dace_2262 PE=3 SV=1
Number of features: 0
Seq('MKKLKLLTLVALLIALPSLALAEEEAVSEMTYILNTFSFLISGVLVMWMAAGFA...NKR')
ID: tr|Q1K433|Q1K433_DESA6
Name: tr|Q1K433|Q1K433_DESA6
Description: tr|Q1K433|Q1K433_DESA6 Ammonium transporter OS=Desulfuromonas acetoxidans (strain DSM 684 / 11070) OX=281689 GN=Dace_3136 PE=3 SV=1
Number of features: 0
Seq('MTLHSELDYHWVILCAFLVFMMQLGFAMVETGCVRSKNTINVAMKNLADATFGF...CCS')
ID: tr|A0A1H4DJ49|A0A1H4DJ49_9BACT
Name: tr|A0A1H4DJ49|A0A1H4DJ49_9BACT
Description: tr|A0A1H4DJ49|A0A1H4DJ49_9BACT Ammonium transporter OS=Desulfuromusa kysingii OX=37625 GN=SAMN05660420_02991 PE=3 SV=1
Number of features: 0
Seq('MKKFMFLLAGLLILPTLALAEDAPVSEMSYILNTFSFLVMGILVMWMAAGFGML...SRP')
ID: tr|C0GKN4|C0GKN4_DETAL
Name: tr|C0GKN4|C0GKN4_DETAL
Description: tr|C0GKN4|C0GKN4_DETAL Ammonium transporter OS=Dethiobacter alkaliphilus AHT 1 OX=555088 GN=DealDRAFT_3043 PE=3 SV=1
Number of features: 0
Seq('MTEMAIDTIWVLLAAFLVFLMQLGFAMVESGFTRAKNAGNIIMKNVMDFACGSL...QVH')
ID: tr|D2BUJ8|D2BUJ8_DICZ5
Name: tr|D2BUJ8|D2BUJ8_DICZ5
Description: tr|D2BUJ8|D2BUJ8_DICZ5 Ammonium transporter OS=Dickeya zeae (strain Ech586) OX=590409 GN=Dd586_1044 PE=3 SV=1
Number of features: 0
Seq('MKKLSLSLGLGAAAMLPTWVMADTPAPVVDKADNAFMMICTALVLFMTIPGLAL...YNQ')
ID: tr|C6CBB1|C6CBB1_MUSP7
Name: tr|C6CBB1|C6CBB1_MUSP7
Description: tr|C6CBB1|C6CBB1_MUSP7 Ammonium transporter OS=Musicola paradisiaca (strain Ech703) OX=579405 GN=Dd703_2864 PE=3 SV=1
Number of features: 0
Seq('MKKLSLSLGLGAAAMLPAWVLADTPAPVVDKADNAFMMICTALVLFMTIPGLAL...YNQ')
ID: tr|E0SD83|E0SD83_DICD3
Name: tr|E0SD83|E0SD83_DICD3
Description: tr|E0SD83|E0SD83_DICD3 Ammonium transporter OS=Dickeya dadantii (strain 3937) OX=198628 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLSLSLGLGAAAMLPAWAMADTPAPVADKADNAFMMICTALVLFMTIPGLAL...YNQ')
ID: tr|A0A7V3ZHK6|A0A7V3ZHK6_DICTH
Name: tr|A0A7V3ZHK6|A0A7V3ZHK6_DICTH
Description: tr|A0A7V3ZHK6|A0A7V3ZHK6_DICTH Ammonium transporter OS=Dictyoglomus thermophilum OX=14 GN=amt PE=3 SV=1
Number of features: 0
Seq('MENKVILDTIWVLFTGMLVFFMNLGFAMVESGFARVKNTVNILSKNFIVFAISS...VRK')
ID: sp|Q9BLG3|AMT2_DICDI
Name: sp|Q9BLG3|AMT2_DICDI
Description: sp|Q9BLG3|AMT2_DICDI Ammonium transporter 2 OS=Dictyostelium discoideum OX=44689 GN=amtB PE=1 SV=1
Number of features: 0
Seq('MEYLELNGTKEGLSAAVDDMWVLNATYLVFYMQAGFCMLEAGVVRAKNAKSIIM...WDN')
ID: sp|Q9BLG4|AMT1_DICDI
Name: sp|Q9BLG4|AMT1_DICDI
Description: sp|Q9BLG4|AMT1_DICDI Ammonium transporter 1 OS=Dictyostelium discoideum OX=44689 GN=amtA PE=1 SV=1
Number of features: 0
Seq('MVAGEIIKGVAAEITNGSSSSVVQKYLDCANQVAPDPGNTTWVLLSTILVLGMM...FFK')
ID: sp|Q8MXY0|AMT3_DICDI
Name: sp|Q8MXY0|AMT3_DICDI
Description: sp|Q8MXY0|AMT3_DICDI Ammonium transporter 3 OS=Dictyostelium discoideum OX=44689 GN=amtC PE=2 SV=1
Number of features: 0
Seq('MEQFSTSSSESSDSSSEYSLEFYMDTSWVLDAANLVFFMQAGFGMLEAGMVRAK...IFD')
ID: sp|Q9NIV0|RHGA_DICDI
Name: sp|Q9NIV0|RHGA_DICDI
Description: sp|Q9NIV0|RHGA_DICDI Rhesus-like glycoprotein A OS=Dictyostelium discoideum OX=44689 GN=rhgA PE=1 SV=1
Number of features: 0
Seq('MTHNDDDHKWVTTKRKEPIFFTVILFIFQIFMIICFAALTGYDTNKNYTGSENP...EPI')
ID: sp|Q8I0L6|RHGB_DICDI
Name: sp|Q8I0L6|RHGB_DICDI
Description: sp|Q8I0L6|RHGB_DICDI Rhesus-like glycoprotein B OS=Dictyostelium discoideum OX=44689 GN=rhgB PE=2 SV=1
Number of features: 0
Seq('MSKDEHKLPLSKRKESIIFMMILFAFQVFMVVLFSVWVRYSKNEVNYSTLTPEQ...SKV')
ID: tr|F0ZWG6|F0ZWG6_DICPU
Name: tr|F0ZWG6|F0ZWG6_DICPU
Description: tr|F0ZWG6|F0ZWG6_DICPU Ammonium transporter OS=Dictyostelium purpureum OX=5786 GN=DICPUDRAFT_50024 PE=3 SV=1
Number of features: 0
Seq('MLYDSSANGTHTDYPDCEGKVQPDPGNTTWVLLSTILVLGMMPALAFFEAGLLR...FFK')
ID: tr|F0ZPL3|F0ZPL3_DICPU
Name: tr|F0ZPL3|F0ZPL3_DICPU
Description: tr|F0ZPL3|F0ZPL3_DICPU Ammonium transporter OS=Dictyostelium purpureum OX=5786 GN=DICPUDRAFT_48548 PE=3 SV=1
Number of features: 0
Seq('MEQFSMSSSSDEASSSEYSLEYYMDTSWILDAANLVFFMQAGFGMLEAGMVRAK...TFD')
ID: tr|F0ZCX7|F0ZCX7_DICPU
Name: tr|F0ZCX7|F0ZCX7_DICPU
Description: tr|F0ZCX7|F0ZCX7_DICPU Ammonium transporter AmtB-like domain-containing protein OS=Dictyostelium purpureum OX=5786 GN=DICPUDRAFT_96981 PE=4 SV=1
Number of features: 0
Seq('MSKDESHIKTLSKRKESVIFMMILFGFQIFMIVLLSVWVDYKSDHDYLEEGEGT...SEV')
ID: tr|A0A4R3ZZ35|A0A4R3ZZ35_9ACTN
Name: tr|A0A4R3ZZ35|A0A4R3ZZ35_9ACTN
Description: tr|A0A4R3ZZ35|A0A4R3ZZ35_9ACTN Ammonium transporter OS=Dietzia cinnamea OX=321318 GN=EDD19_102200 PE=3 SV=1
Number of features: 0
Seq('MIGDSVALLAQEATPEFDTGDTAWMLMAASLVLLMTPALALFYGGMSRQKSVLN...LIR')
ID: tr|A0A4R3ZNW3|A0A4R3ZNW3_9ACTN
Name: tr|A0A4R3ZNW3|A0A4R3ZNW3_9ACTN
Description: tr|A0A4R3ZNW3|A0A4R3ZNW3_9ACTN Ammonium transporter OS=Dietzia cinnamea OX=321318 GN=EDD19_1287 PE=3 SV=1
Number of features: 0
Seq('MDVAIAAADTAWVLAAMVAVALMVPGLALFYGGMVSIRSTLNMMMMTIGAVAVM...AGT')
ID: tr|E6JCU6|E6JCU6_9ACTN
Name: tr|E6JCU6|E6JCU6_9ACTN
Description: tr|E6JCU6|E6JCU6_9ACTN Ammonium transporter OS=Dietzia cinnamea P4 OX=910954 GN=ES5_15330 PE=3 SV=1
Number of features: 0
Seq('MIGDSVALLAQEATPEFDTGDTAWMLMAASLVLLMTPALALFYGGMSRQKSVLN...LIR')
ID: tr|A8LKQ0|A8LKQ0_DINSH
Name: tr|A8LKQ0|A8LKQ0_DINSH
Description: tr|A8LKQ0|A8LKQ0_DINSH Ammonium transporter OS=Dinoroseobacter shibae (strain DSM 16493 / NCIMB 14021 / DFL 12) OX=398580 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKLTKLLPLAAAAIVLPSLGLAQDAAPSFDEIGPYIMTTLLFCMAGFLVFFMAC...TKG')
ID: tr|A0A1I0BYN1|A0A1I0BYN1_9BACT
Name: tr|A0A1I0BYN1|A0A1I0BYN1_9BACT
Description: tr|A0A1I0BYN1|A0A1I0BYN1_9BACT Ammonium transporter OS=Draconibacterium orientale OX=1168034 GN=SAMN05444285_10682 PE=3 SV=1
Number of features: 0
Seq('MSCMVLYRLKISNLKIIDMRNSTSWWFILALLIIVAALGVIIPGGVAEIDTSNL...SED')
ID: tr|X5DX97|X5DX97_9BACT
Name: tr|X5DX97|X5DX97_9BACT
Description: tr|X5DX97|X5DX97_9BACT Ammonium transporter OS=Draconibacterium orientale OX=1168034 GN=SAMN05444285_10797 PE=3 SV=1
Number of features: 0
Seq('MEETLQGLQIGIDNMWLLVAAFLVMFMQPGFALVEAGFTRSKNTANILMKNLMD...AYN')

ID: tr|C6VZA0|C6VZA0_DYAFD
Name: tr|C6VZA0|C6VZA0_DYAFD
Description: tr|C6VZA0|C6VZA0_DYAFD Ammonium transporter OS=Dyadobacter fermentans (strain ATCC 700827 / DSM 18053 / CIP 107007 / KCTC 52180 / NS114) OX=471854 GN=Dfer_0443 PE=3 SV=1
Number of features: 0
Seq('MEKRNFIPLIILLVISILGAFIPNVPTQIATEGINSGDTAWMLVSAALVLLMTP...VEA')
ID: tr|A0A075JZ35|A0A075JZ35_9GAMM
Name: tr|A0A075JZ35|A0A075JZ35_9GAMM
Description: tr|A0A075JZ35|A0A075JZ35_9GAMM Ammonium transporter OS=Dyella japonica A8 OX=1217721 GN=HY57_08775 PE=3 SV=1
Number of features: 0
Seq('MAGLTLVGPALAQTAAPTHIDSGDTAWMLTATAFVLLMTIPGLALFYGGMVRAK...NLS')
ID: tr|A0A0G9HEC5|A0A0G9HEC5_9GAMM
Name: tr|A0A0G9HEC5|A0A0G9HEC5_9GAMM
Description: tr|A0A0G9HEC5|A0A0G9HEC5_9GAMM Ammonium transporter OS=Dyella japonica DSM 16301 OX=1440762 GN=Y882_01080 PE=3 SV=1
Number of features: 0
Seq('MGLLATSPVWAQAAAAPTHIDSGDTAWMLTATALVLLMTIPGLALFYGGMVRAK...NLS')
ID: tr|F5ISF6|F5ISF6_9BACT
Name: tr|F5ISF6|F5ISF6_9BACT
Description: tr|F5ISF6|F5ISF6_9BACT Ammonium transporter OS=Dysgonomonas gadei ATCC BAA-286 OX=742766 GN=HMPREF9455_00023 PE=3 SV=1
Number of features: 0
Seq('MKRRLFKYITILLFASLTLPTAVIAQDSLATSTDSLQVVATTVVEGVAAAEAPA...ENE')
ID: tr|L0FU80|L0FU80_ECHVK
Name: tr|L0FU80|L0FU80_ECHVK
Description: tr|L0FU80|L0FU80_ECHVK Ammonium transporter OS=Echinicola vietnamensis (strain DSM 17526 / LMG 23754 / KMM 6221) OX=926556 GN=Echvi_0579 PE=3 SV=1
Number of features: 0
Seq('MKWSFNDLAQVSTDALAQGADLSADITQNLLTTNNVWMMLSTALVFIMHLGFAG...YDE')
ID: tr|D7G265|D7G265_ECTSI
Name: tr|D7G265|D7G265_ECTSI
Description: tr|D7G265|D7G265_ECTSI Ammonium transporter OS=Ectocarpus siliculosus OX=2880 GN=Esi_0047_0002 PE=3 SV=1
Number of features: 0
Seq('MDTAEISATDVALAVDTAWVLLGAAMVFFMQAGFAMLEVGSVSIKNTKNILIKN...ANI')
ID: tr|A0A3R9Q7C4|A0A3R9Q7C4_9BACT
Name: tr|A0A3R9Q7C4|A0A3R9Q7C4_9BACT
Description: tr|A0A3R9Q7C4|A0A3R9Q7C4_9BACT Ammonium transporter OS=Edaphobacter aggregans OX=570835 GN=EDE15_0608 PE=3 SV=1
Number of features: 0
Seq('MRFSAVKVFLVLVLALIFGGAVVSGPVAVAQATAPQSGATQPDRIAALEKQAAD...WAH')
ID: tr|A0A2A7U6W1|A0A2A7U6W1_EDWTA
Name: tr|A0A2A7U6W1|A0A2A7U6W1_EDWTA
Description: tr|A0A2A7U6W1|A0A2A7U6W1_EDWTA Ammonium transporter OS=Edwardsiella tarda OX=636 GN=CRM76_16200 PE=3 SV=1
Number of features: 0
Seq('MTLRKGMVAALWLPGTALAATPLADRADNGFMLIATALVLFMTLPGIALFYGGL...YNR')
ID: tr|D4F313|D4F313_EDWTA
Name: tr|D4F313|D4F313_EDWTA
Description: tr|D4F313|D4F313_EDWTA Ammonium transporter OS=Edwardsiella tarda ATCC 23685 OX=500638 GN=amt PE=3 SV=1
Number of features: 0
Seq('MMGKEGESMMTLRKGMVAALWLPGTALAATPLADRADNGFMLIATALVLFMTLP...YNR')
ID: tr|D0ZEB8|D0ZEB8_EDWTE
Name: tr|D0ZEB8|D0ZEB8_EDWTE
Description: tr|D0ZEB8|D0ZEB8_EDWTE Ammonium transporter OS=Edwardsiella tarda (strain EIB202) OX=498217 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MALLPGVALAGAPQMDRADNGFMMLATALVLLMTLPGIALFYGGLLRAKNVLSL...YNR')
ID: tr|A0A0H3DR67|A0A0H3DR67_EDWTF
Name: tr|A0A0H3DR67|A0A0H3DR67_EDWTF
Description: tr|A0A0H3DR67|A0A0H3DR67_EDWTF Ammonium transporter OS=Edwardsiella tarda (strain FL6-60) OX=718251 GN=ETAF_0936 PE=3 SV=1
Number of features: 0
Seq('MALLPGVALAGAPQMDRADNGFMMLATALVLLMTLPGIALFYGGLLRAKNVLSL...YNR')
ID: tr|A0A369MRW6|A0A369MRW6_EGGLN
Name: tr|A0A369MRW6|A0A369MRW6_EGGLN
Description: tr|A0A369MRW6|A0A369MRW6_EGGLN Ammonium transporter OS=Eggerthella lenta OX=84112 GN=C1872_06105 PE=3 SV=1
Number of features: 0
Seq('MFDAGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMIMSFAVIGIVGVT...GLD')
ID: tr|A0A369N7Y3|A0A369N7Y3_EGGLN
Name: tr|A0A369N7Y3|A0A369N7Y3_EGGLN
Description: tr|A0A369N7Y3|A0A369N7Y3_EGGLN Ammonium transporter OS=Eggerthella lenta OX=84112 GN=C1871_06270 PE=3 SV=1
Number of features: 0
Seq('MFDAGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMIMSFAVIGIVGVT...GLD')
ID: tr|A0A369MHK2|A0A369MHK2_EGGLN
Name: tr|A0A369MHK2|A0A369MHK2_EGGLN
Description: tr|A0A369MHK2|A0A369MHK2_EGGLN Ammonium transporter OS=Eggerthella lenta OX=84112 GN=C1875_08500 PE=3 SV=1
Number of features: 0
Seq('MFDAGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMIMSFAVIGIVGVT...GLD')
ID: tr|A0A5C5BWI6|A0A5C5BWI6_EGGLN
Name: tr|A0A5C5BWI6|A0A5C5BWI6_EGGLN
Description: tr|A0A5C5BWI6|A0A5C5BWI6_EGGLN Ammonium transporter OS=Eggerthella lenta OX=84112 GN=FIC87_07460 PE=3 SV=1
Number of features: 0
Seq('MFDAGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMIMSFAVIGIVGVT...GLD')
ID: tr|C8WLL8|C8WLL8_EGGLE
Name: tr|C8WLL8|C8WLL8_EGGLE
Description: tr|C8WLL8|C8WLL8_EGGLE Ammonium transporter OS=Eggerthella lenta (strain ATCC 25559 / DSM 2243 / CCUG 17323 / JCM 9979 / KCTC 3265 / NCTC 11813 / VPI 0255 / 1899 B) OX=479437 GN=Elen_2526 PE=3 SV=1
Number of features: 0
Seq('MFDTGSTGFMIVCAMLVLLMTPGLAFFYGGLSRRKNVVSTMIMSFAVLGIVGIT...GLD')
ID: tr|A0A1T3DAU3|A0A1T3DAU3_9FLAO
Name: tr|A0A1T3DAU3|A0A1T3DAU3_9FLAO
Description: tr|A0A1T3DAU3|A0A1T3DAU3_9FLAO Ammonium transporter OS=Elizabethkingia anophelis OX=1117645 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKIEKHWVISFIIICIISLGALVGSNTDQINMQNFLPESNINSADTAWILTASG...QLC')
ID: tr|A0A1T3DXP7|A0A1T3DXP7_9FLAO
Name: tr|A0A1T3DXP7|A0A1T3DXP7_9FLAO
Description: tr|A0A1T3DXP7|A0A1T3DXP7_9FLAO Ammonium transporter OS=Elizabethkingia anophelis OX=1117645 GN=BBD32_19230 PE=3 SV=1
Number of features: 0
Seq('MKIEKHWVISFVIICIISLGALVGSNTDQINMQNFLPESNINSADTAWILTASG...QLC')
ID: tr|A0A077EFU9|A0A077EFU9_9FLAO
Name: tr|A0A077EFU9|A0A077EFU9_9FLAO
Description: tr|A0A077EFU9|A0A077EFU9_9FLAO Ammonium transporter OS=Elizabethkingia anophelis NUHP1 OX=1338011 GN=BD94_2552 PE=3 SV=1
Number of features: 0
Seq('MKIEKHWVISFVIICIISLGALVGSNTDQINMQNFLPESNINSADTAWILTASG...QLC')
ID: tr|A0A807YBT3|A0A807YBT3_9FLAO
Name: tr|A0A807YBT3|A0A807YBT3_9FLAO
Description: tr|A0A807YBT3|A0A807YBT3_9FLAO Ammonium transporter OS=Elizabethkingia anophelis R26 OX=1246994 GN=BAZ09_004010 PE=3 SV=1
Number of features: 0
Seq('MKIEKHWVISFVIICIISLGALVGSNTDQINMQNFLPESNINSADTAWILTASG...QLC')
ID: tr|A0A494JB70|A0A494JB70_9FLAO
Name: tr|A0A494JB70|A0A494JB70_9FLAO
Description: tr|A0A494JB70|A0A494JB70_9FLAO Ammonium transporter OS=Elizabethkingia anophelis OX=1117645 GN=AYC66_15775 PE=3 SV=1
Number of features: 0
Seq('MKIEKHWVISFVIICIISLGALVGSNTDQINMQNFLSESNINSADTAWILTASG...QLC')
ID: tr|R1EDV9|R1EDV9_EMIHU
Name: tr|R1EDV9|R1EDV9_EMIHU
Description: tr|R1EDV9|R1EDV9_EMIHU Ammonium transporter OS=Emiliania huxleyi OX=2903 GN=AMT9 PE=3 SV=1
Number of features: 0
Seq('MASPPSPSAPPFPPNGVTLANLQNGQALDAFYLLVCGVFVFFMQCGFALLEAGT...YHN')
ID: tr|R1D1H4|R1D1H4_EMIHU
Name: tr|R1D1H4|R1D1H4_EMIHU
Description: tr|R1D1H4|R1D1H4_EMIHU Ammonium transporter OS=Emiliania huxleyi OX=2903 GN=AMT7 PE=3 SV=1
Number of features: 0
Seq('MEDEDLKSAINVAWVLLCTALVFWEQAGFAMWEAGCLRSTSLHSILLKNMCDAA...TYA')
ID: tr|R1EGK6|R1EGK6_EMIHU
Name: tr|R1EGK6|R1EGK6_EMIHU
Description: tr|R1EGK6|R1EGK6_EMIHU Ammonium transporter OS=Emiliania huxleyi OX=2903 GN=AMT5 PE=3 SV=1
Number of features: 0
Seq('MEDEDLKSAINVAWVLLCTALVFWEQAGFAMWEAGCLRSTSLHSILLKNMCDAA...TYA')
ID: tr|R1FI09|R1FI09_EMIHU
Name: tr|R1FI09|R1FI09_EMIHU
Description: tr|R1FI09|R1FI09_EMIHU Ammonium transporter OS=Emiliania huxleyi OX=2903 GN=EMIHUDRAFT_467882 PE=3 SV=1
Number of features: 0
Seq('MGDIGAEFAAFKSDMQKKDQALDAFYLLVCGTFVFFMQCGFALLEAGTVRSKNT...AYN')
ID: tr|R1CIA4|R1CIA4_EMIHU
Name: tr|R1CIA4|R1CIA4_EMIHU
Description: tr|R1CIA4|R1CIA4_EMIHU Ammonium transporter (Fragment) OS=Emiliania huxleyi OX=2903 GN=EMIHUDRAFT_65124 PE=3 SV=1
Number of features: 0
Seq('MESCDSACEGIEDSDTGFMVMATTFVMLQTPALGLCQAGLIRRKNALSMLMQVL...QAY')
ID: tr|A0A5P2GF55|A0A5P2GF55_9FLAO
Name: tr|A0A5P2GF55|A0A5P2GF55_9FLAO
Description: tr|A0A5P2GF55|A0A5P2GF55_9FLAO Ammonium transporter OS=Empedobacter brevis OX=247 GN=F0358_10415 PE=3 SV=1
Number of features: 0
Seq('MKVGLKWRVAFAIITLIALAGLFWKPVVDIPNTGEFLSEENIVNSDVAWILAAA...ING')
ID: tr|A0A6P1G3R3|A0A6P1G3R3_9FLAO
Name: tr|A0A6P1G3R3|A0A6P1G3R3_9FLAO
Description: tr|A0A6P1G3R3|A0A6P1G3R3_9FLAO Ammonium transporter OS=Empedobacter brevis OX=247 GN=AS589_09080 PE=3 SV=1
Number of features: 0
Seq('MKVGLKWKVAFAIITLIAFAGLFWKPVVDIPNTGEFLSEENIVNSDVAWILAAA...ING')
ID: tr|A0A511NGC7|A0A511NGC7_9FLAO
Name: tr|A0A511NGC7|A0A511NGC7_9FLAO
Description: tr|A0A511NGC7|A0A511NGC7_9FLAO Ammonium transporter OS=Empedobacter brevis NBRC 14943 = ATCC 43319 OX=1218108 GN=EB1_16500 PE=3 SV=1
Number of features: 0
Seq('MKVGLKWKVAFAIITLIALAGLFWKPVVDIPNTGEFLSEENIVNSDVAWILAAA...ING')
ID: tr|A0A142BI19|A0A142BI19_9GAMM
Name: tr|A0A142BI19|A0A142BI19_9GAMM
Description: tr|A0A142BI19|A0A142BI19_9GAMM Ammonium transporter OS=Endozoicomonas montiporae CL-33 OX=570277 GN=amt2 PE=3 SV=1
Number of features: 0
Seq('MENLAQVSYALDTFYFLMSGALVMWMAAGFAMLEAGLVRSKNTVEILTKNIALF...GKQ')

ID: tr|A0A081N2G5|A0A081N2G5_9GAMM
Name: tr|A0A081N2G5|A0A081N2G5_9GAMM
Description: tr|A0A081N2G5|A0A081N2G5_9GAMM Ammonium transporter OS=Endozoicomonas montiporae OX=1027273 GN=GZ77_19260 PE=3 SV=1
Number of features: 0
Seq('MENLAQVSYALDTFYFLMSGALVMWMAAGFAMLEAGLVRSKNTVEILTKNIALF...GKQ')
ID: tr|A0A1T4SFK4|A0A1T4SFK4_9HYPH
Name: tr|A0A1T4SFK4|A0A1T4SFK4_9HYPH
Description: tr|A0A1T4SFK4|A0A1T4SFK4_9HYPH Ammonium transporter OS=Enhydrobacter aerosaccus OX=225324 GN=SAMN02745126_04601 PE=3 SV=1
Number of features: 0
Seq('MFKSIKRSTALAAVVTAVLASTEPSAWAAGRPTIDTGDTAWLLVATALVLMMNI...RVQ')
ID: tr|A0A1T4SF40|A0A1T4SF40_9HYPH
Name: tr|A0A1T4SF40|A0A1T4SF40_9HYPH
Description: tr|A0A1T4SF40|A0A1T4SF40_9HYPH Ammonium transporter OS=Enhydrobacter aerosaccus OX=225324 GN=SAMN02745126_04599 PE=3 SV=1
Number of features: 0
Seq('MKRKLSSALAGLGAAGTLLLPVMAFAADEKPKLDTGDTAWMLTSTALVLMMTVP...TVH')
ID: tr|A0A1Y3U5V2|A0A1Y3U5V2_9ACTN
Name: tr|A0A1Y3U5V2|A0A1Y3U5V2_9ACTN
Description: tr|A0A1Y3U5V2|A0A1Y3U5V2_9ACTN Ammonium transporter OS=Enorma massiliensis OX=1472761 GN=B5G21_02505 PE=3 SV=1
Number of features: 0
Seq('MYDTGSTAFMFVCTMLVLLMTPGLAFFYGGLSRRKNVINTMFMSFMVIGIAGLT...LDV')
ID: tr|A0A0L8BVU4|A0A0L8BVU4_ENSAD
Name: tr|A0A0L8BVU4|A0A0L8BVU4_ENSAD
Description: tr|A0A0L8BVU4|A0A0L8BVU4_ENSAD Ammonium transporter OS=Ensifer adhaerens OX=106592 GN=AC244_12585 PE=3 SV=1
Number of features: 0
Seq('MSSSKLSISLARIGAASAALLAPVVAFAQEAAPAAAAATAAAPVPDKADTAFMF...YHS')
ID: tr|W8I6E4|W8I6E4_ENSAD
Name: tr|W8I6E4|W8I6E4_ENSAD
Description: tr|W8I6E4|W8I6E4_ENSAD Ammonium transporter OS=Ensifer adhaerens OV14 OX=1416753 GN=OV14_0709 PE=3 SV=1
Number of features: 0
Seq('MFISTLLVFFMLIPGLALFYGGLVRAKNMLSVLMQCTVIGATMMIVWVVYGYSF...YHS')
ID: tr|A0A6S5XW90|A0A6S5XW90_ENTCL
Name: tr|A0A6S5XW90|A0A6S5XW90_ENTCL
Description: tr|A0A6S5XW90|A0A6S5XW90_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=WP8W19C02_09460 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTALGSLALLPGLALAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A6S5K4J1|A0A6S5K4J1_ENTCL
Name: tr|A0A6S5K4J1|A0A6S5K4J1_ENTCL
Description: tr|A0A6S5K4J1|A0A6S5K4J1_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=WP5S18C02_11710 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A6S5KAW5|A0A6S5KAW5_ENTCL
Name: tr|A0A6S5KAW5|A0A6S5KAW5_ENTCL
Description: tr|A0A6S5KAW5|A0A6S5KAW5_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=WP5S18E01_09140 PE=3 SV=1
Number of features: 0
Seq('MKIATIKTALGSLALLPGLAMAAAPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A2T4XZC1|A0A2T4XZC1_ENTCL
Name: tr|A0A2T4XZC1|A0A2T4XZC1_ENTCL
Description: tr|A0A2T4XZC1|A0A2T4XZC1_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=DA103_15920 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAAPAVADKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A330EZR0|A0A330EZR0_ENTCL
Name: tr|A0A330EZR0|A0A330EZR0_ENTCL
Description: tr|A0A330EZR0|A0A330EZR0_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=DP187_11355 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAAPAVADKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A4Q2EAG7|A0A4Q2EAG7_ENTCL
Name: tr|A0A4Q2EAG7|A0A4Q2EAG7_ENTCL
Description: tr|A0A4Q2EAG7|A0A4Q2EAG7_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=DM877_05855 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAAPAVADKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A0M3F8F9|A0A0M3F8F9_ENTCL
Name: tr|A0A0M3F8F9|A0A0M3F8F9_ENTCL
Description: tr|A0A0M3F8F9|A0A0M3F8F9_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=OA46_01195 PE=3 SV=1
Number of features: 0
Seq('MKKTTLNAVLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A330GB00|A0A330GB00_ENTCL
Name: tr|A0A330GB00|A0A330GB00_ENTCL
Description: tr|A0A330GB00|A0A330GB00_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=DP202_14460 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAATPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A443Y093|A0A443Y093_ENTCL
Name: tr|A0A443Y093|A0A443Y093_ENTCL
Description: tr|A0A443Y093|A0A443Y093_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=DN595_00660 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A144NLT9|A0A144NLT9_ENTCL
Name: tr|A0A144NLT9|A0A144NLT9_ENTCL
Description: tr|A0A144NLT9|A0A144NLT9_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAATPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A7H9JPM9|A0A7H9JPM9_ENTCL
Name: tr|A0A7H9JPM9|A0A7H9JPM9_ENTCL
Description: tr|A0A7H9JPM9|A0A7H9JPM9_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKATMKTGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A7H8UK07|A0A7H8UK07_ENTCL
Name: tr|A0A7H8UK07|A0A7H8UK07_ENTCL
Description: tr|A0A7H8UK07|A0A7H8UK07_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATIKTGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A411GDE8|A0A411GDE8_ENTCL
Name: tr|A0A411GDE8|A0A411GDE8_ENTCL
Description: tr|A0A411GDE8|A0A411GDE8_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAATPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A427KNL6|A0A427KNL6_ENTCL
Name: tr|A0A427KNL6|A0A427KNL6_ENTCL
Description: tr|A0A427KNL6|A0A427KNL6_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATIKTGLGSLALLPGLAMAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A4Q4A8K6|A0A4Q4A8K6_ENTCL
Name: tr|A0A4Q4A8K6|A0A4Q4A8K6_ENTCL
Description: tr|A0A4Q4A8K6|A0A4Q4A8K6_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRTTMKTALGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A801DSC9|A0A801DSC9_9ENTR
Name: tr|A0A801DSC9|A0A801DSC9_9ENTR
Description: tr|A0A801DSC9|A0A801DSC9_9ENTR Ammonium transporter OS=Enterobacter cloacae complex sp OX=2027919 GN=AM401_12625 PE=3 SV=1
Number of features: 0
Seq('MKKATMKTGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A2W0GQV0|A0A2W0GQV0_9ENTR
Name: tr|A0A2W0GQV0|A0A2W0GQV0_9ENTR
Description: tr|A0A2W0GQV0|A0A2W0GQV0_9ENTR Ammonium transporter OS=Enterobacter cloacae complex sp OX=2027919 GN=DNK77_11870 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A8H9CE40|A0A8H9CE40_ENTCL
Name: tr|A0A8H9CE40|A0A8H9CE40_ENTCL
Description: tr|A0A8H9CE40|A0A8H9CE40_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKATMKTGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A1Z3MS36|A0A1Z3MS36_9ENTR
Name: tr|A0A1Z3MS36|A0A1Z3MS36_9ENTR
Description: tr|A0A1Z3MS36|A0A1Z3MS36_9ENTR Ammonium transporter OS=Enterobacter cloacae complex sp. ECNIH7 OX=1915310 GN=WM95_05515 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAATPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A2S4SRB5|A0A2S4SRB5_9ENTR
Name: tr|A0A2S4SRB5|A0A2S4SRB5_9ENTR
Description: tr|A0A2S4SRB5|A0A2S4SRB5_9ENTR Ammonium transporter OS=Enterobacter cloacae complex sp. ECNIH11 OX=2080662 GN=C3394_11995 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAATPAVVDKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A421IL65|A0A421IL65_ENTCL
Name: tr|A0A421IL65|A0A421IL65_ENTCL
Description: tr|A0A421IL65|A0A421IL65_ENTCL Ammonium transporter OS=Enterobacter cloacae OX=550 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATIKTGLGSLALLPGLAMAAPAVADKADNAFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|A0A855M376|A0A855M376_9ENTR
Name: tr|A0A855M376|A0A855M376_9ENTR
Description: tr|A0A855M376|A0A855M376_9ENTR Ammonium transporter OS=Enterobacter cloacae complex sp. ECNIH14 OX=2080664 GN=C3399_13945 PE=3 SV=1
Number of features: 0
Seq('MKIATLKTGLGSLALLPGLALAAAPAVADKADNAFMMISTALVLFMSIPGIALF...YNA')
ID: tr|A0A0M2ADU2|A0A0M2ADU2_ENTFL
Name: tr|A0A0M2ADU2|A0A0M2ADU2_ENTFL
Description: tr|A0A0M2ADU2|A0A0M2ADU2_ENTFL Ammonium transporter OS=Enterococcus faecalis EnGen0302 OX=1158660 GN=UMC_00634 PE=3 SV=1
Number of features: 0
Seq('MNNLFIFVCFCFMWLMIFGVILYYVGLVNHRYIHHTLILGLVTIISGTLCWLFV...CIR')
ID: tr|R3H4W8|R3H4W8_ENTFL
Name: tr|R3H4W8|R3H4W8_ENTFL
Description: tr|R3H4W8|R3H4W8_ENTFL Ammonium transporter OS=Enterococcus faecalis EnGen0359 OX=1169307 GN=WOK_00623 PE=3 SV=1
Number of features: 0
Seq('MNNLFIFVCFCFMWLMIFGVILYYVGLVNHRYIHHTLILGLVTIISGTLCWLFV...CIR')

ID: tr|V7ZMI3|V7ZMI3_ENTFL
Name: tr|V7ZMI3|V7ZMI3_ENTFL
Description: tr|V7ZMI3|V7ZMI3_ENTFL Ammonium transporter OS=Enterococcus faecalis PF3 OX=1410655 GN=T481_12805 PE=3 SV=1
Number of features: 0
Seq('MNNLFIFVCFCFMWLMIFGVILYYVGLVNHRYIHHTLILGLVTIISGTLCWLFV...CIR')
ID: tr|A0A2N7LCD7|A0A2N7LCD7_9GAMM
Name: tr|A0A2N7LCD7|A0A2N7LCD7_9GAMM
Description: tr|A0A2N7LCD7|A0A2N7LCD7_9GAMM Ammonium transporter OS=Enterovibrio norvegicus OX=188144 GN=BCT23_03270 PE=3 SV=1
Number of features: 0
Seq('MELTTTVTELRYALDTFFFLMSGALVMWMAAGFAMLEAGLVRSKNTTEILTKNV...SVK')
ID: tr|A0A2N7L7C8|A0A2N7L7C8_9GAMM
Name: tr|A0A2N7L7C8|A0A2N7L7C8_9GAMM
Description: tr|A0A2N7L7C8|A0A2N7L7C8_9GAMM Ammonium transporter OS=Enterovibrio norvegicus OX=188144 GN=BCT23_21635 PE=3 SV=1
Number of features: 0
Seq('MENISSAIQTLTESANTLFILMGAIMVLAMHAGFAFLEVGTVRHRNQVNALVKI...SED')
ID: tr|A0A1E5BXA4|A0A1E5BXA4_9GAMM
Name: tr|A0A1E5BXA4|A0A1E5BXA4_9GAMM
Description: tr|A0A1E5BXA4|A0A1E5BXA4_9GAMM Ammonium transporter OS=Enterovibrio norvegicus FF-454 OX=1185651 GN=A1OK_04440 PE=3 SV=1
Number of features: 0
Seq('MELSTTVTELRYALDTFFFLISGALVMWMAAGFAMLEAGLVRSKNTTEILTKNV...SVR')
ID: tr|A0A1E5C7W4|A0A1E5C7W4_9GAMM
Name: tr|A0A1E5C7W4|A0A1E5C7W4_9GAMM
Description: tr|A0A1E5C7W4|A0A1E5C7W4_9GAMM Ammonium transporter OS=Enterovibrio norvegicus FF-454 OX=1185651 GN=A1OK_09580 PE=3 SV=1
Number of features: 0
Seq('MENISSAIQTLTESANTLFILMGAIMVLAMHAGFAFLEVGTVRHRNQVNALVKI...SED')
ID: tr|A0A1I5W440|A0A1I5W440_9GAMM
Name: tr|A0A1I5W440|A0A1I5W440_9GAMM
Description: tr|A0A1I5W440|A0A1I5W440_9GAMM Ammonium transporter, Amt family OS=Enterovibrio norvegicus DSM 15893 OX=1121869 GN=SAMN03084138_04167 PE=3 SV=1
Number of features: 0
Seq('MELTTTVTELRYALDTFFFLMSGALVMWMAAGFAMLEAGLVRSKNTTEILTKNV...SVK')
ID: tr|A0A1I5SNU9|A0A1I5SNU9_9GAMM
Name: tr|A0A1I5SNU9|A0A1I5SNU9_9GAMM
Description: tr|A0A1I5SNU9|A0A1I5SNU9_9GAMM Ammonium transporter, Amt family OS=Enterovibrio norvegicus DSM 15893 OX=1121869 GN=SAMN03084138_02946 PE=3 SV=1
Number of features: 0
Seq('MENISSAIQTLTESANTLFILMGAIMVLAMHAGFAFLEVGTVRHRNQVNALVKI...SED')
ID: tr|G8JTW0|G8JTW0_ERECY
Name: tr|G8JTW0|G8JTW0_ERECY
Description: tr|G8JTW0|G8JTW0_ERECY Ammonium transporter OS=Eremothecium cymbalariae (strain CBS 270.75 / DBVPG 7215 / KCTC 17166 / NRRL Y-17582) OX=931890 GN=Ecym_4411 PE=3 SV=1
Number of features: 0
Seq('MVYVWNETYDSAAVGFIFMGSVLVFFMVPGLGFLYSGLARRKSALSLIWAVLMA...KEQ')
ID: tr|G8JUJ2|G8JUJ2_ERECY
Name: tr|G8JUJ2|G8JUJ2_ERECY
Description: tr|G8JUJ2|G8JUJ2_ERECY Ammonium transporter OS=Eremothecium cymbalariae (strain CBS 270.75 / DBVPG 7215 / KCTC 17166 / NRRL Y-17582) OX=931890 GN=Ecym_6398 PE=3 SV=1
Number of features: 0
Seq('MSGSDSAISFVDSVKNPLSTDVNVEYQLFNLVWVGMAAVLVWLVVPGVGLLYSG...AVA')
ID: tr|D4HY35|D4HY35_ERWAC
Name: tr|D4HY35|D4HY35_ERWAC
Description: tr|D4HY35|D4HY35_ERWAC Ammonium transporter OS=Erwinia amylovora (strain CFBP1430) OX=665029 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEWDKMKKIANFCLAGATFLPSLAMAAAPAVADKADNAFMMICTALVLFMTIPG...YNN')
ID: tr|A0A830ZZN8|A0A830ZZN8_ERWAM
Name: tr|A0A830ZZN8|A0A830ZZN8_ERWAM
Description: tr|A0A830ZZN8|A0A830ZZN8_ERWAM Ammonium transporter OS=Erwinia amylovora NBRC 12687 = CFBP 1232 OX=1219359 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKIANFCLAGATFLPSLAMAAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNN')
ID: tr|E5B358|E5B358_ERWAM
Name: tr|E5B358|E5B358_ERWAM
Description: tr|E5B358|E5B358_ERWAM Ammonium transporter OS=Erwinia amylovora ATCC BAA-2158 OX=889211 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEWDKMKKIANFCLAGATFLPSLAMAAAPAVADKADNAFMMICTALVLFMTIPG...YNN')
ID: tr|A0A074ME37|A0A074ME37_9SPHN
Name: tr|A0A074ME37|A0A074ME37_9SPHN
Description: tr|A0A074ME37|A0A074ME37_9SPHN Ammonium transporter OS=Erythrobacter litoralis OX=39960 GN=EH32_01590 PE=3 SV=1
Number of features: 0
Seq('MTRIYKTFAAAALAFAASQPALAAVPAVPNPGNNAWMMTATLLVLLMILPGLAL...AYN')
ID: tr|Q2N625|Q2N625_ERYLH
Name: tr|Q2N625|Q2N625_ERYLH
Description: tr|Q2N625|Q2N625_ERYLH Ammonium transporter OS=Erythrobacter litoralis (strain HTCC2594) OX=314225 GN=ELI_13870 PE=3 SV=1
Number of features: 0
Seq('MIRSLFCSAGALAFTGLVSTAAIAQEAAEAAPVPNPGNNAWMMTATVLVLLMIL...AYN')
ID: tr|A0A7V8RCZ2|A0A7V8RCZ2_9SPHN
Name: tr|A0A7V8RCZ2|A0A7V8RCZ2_9SPHN
Description: tr|A0A7V8RCZ2|A0A7V8RCZ2_9SPHN Ammonium transporter OS=Sphingomonas ursincola OX=56361 GN=FG486_07610 PE=3 SV=1
Number of features: 0
Seq('MKPLHKIGAVVGTTALSVFTAAQAWAATAAPAAEVVEEAVTAVAEGPIKAPTAE...YNY')
ID: tr|A0A7V8RAY5|A0A7V8RAY5_9SPHN
Name: tr|A0A7V8RAY5|A0A7V8RAY5_9SPHN
Description: tr|A0A7V8RAY5|A0A7V8RAY5_9SPHN Ammonium transporter OS=Sphingomonas ursincola OX=56361 GN=FG486_02045 PE=3 SV=1
Number of features: 0
Seq('MIARLARIFTLATAALAAPAWAAPALVDPATLDVSNSGDTAFMLICGALLMLFA...PQG')
ID: sp|P69681|AMTB_ECOLI
Name: sp|P69681|AMTB_ECOLI
Description: sp|P69681|AMTB_ECOLI Ammonium transporter AmtB OS=Escherichia coli (strain K12) OX=83333 GN=amtB PE=1 SV=1
Number of features: 0
Seq('MKIATIKTGLASLAMLPGLVMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: sp|P25527|GABP_ECOLI
Name: sp|P25527|GABP_ECOLI
Description: sp|P25527|GABP_ECOLI Gamma-aminobutyric acid permease OS=Escherichia coli (strain K12) OX=83333 GN=gabP PE=1 SV=1
Number of features: 0
Seq('MGQSSQPHELGGGLKSRHVTMLSIAGVIGASLFVGSSVAIAEAGPAVLLAYLFA...NTR')
ID: sp|P39386|MDTM_ECOLI
Name: sp|P39386|MDTM_ECOLI
Description: sp|P39386|MDTM_ECOLI Multidrug resistance protein MdtM OS=Escherichia coli (strain K12) OX=83333 GN=mdtM PE=1 SV=1
Number of features: 0
Seq('MPRFFTRHAATLFFPMALILYDFAAYLSTDLIQPGIINVVRDFNADVSLAPAAV...EEQ')
ID: sp|P69680|AMTB_ECO57
Name: sp|P69680|AMTB_ECO57
Description: sp|P69680|AMTB_ECO57 Ammonium transporter AmtB OS=Escherichia coli O157:H7 OX=83334 GN=amtB PE=1 SV=1
Number of features: 0
Seq('MKIATIKTGLASLAMLPGLVMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A942VQZ7|A0A942VQZ7_EUBLI
Name: tr|A0A942VQZ7|A0A942VQZ7_EUBLI
Description: tr|A0A942VQZ7|A0A942VQZ7_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=KH042_09865 PE=3 SV=1
Number of features: 0
Seq('MEMQQLADIVWVFLAACLVMFMQPGFAMVETGFTRAKNAGNIIMKNFVDFMVGS...RIQ')
ID: tr|A0A1H0VGF5|A0A1H0VGF5_EUBLI
Name: tr|A0A1H0VGF5|A0A1H0VGF5_EUBLI
Description: tr|A0A1H0VGF5|A0A1H0VGF5_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=SAMN04515624_12921 PE=3 SV=1
Number of features: 0
Seq('MINFADTGFILVCAAMVCLMTPALAVFYAGLLRKGNIVDIMFQCFIAMGIVTVL...MTE')
ID: tr|A0A317RN92|A0A317RN92_EUBLI
Name: tr|A0A317RN92|A0A317RN92_EUBLI
Description: tr|A0A317RN92|A0A317RN92_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=C7955_106188 PE=3 SV=1
Number of features: 0
Seq('MEMQQLADIVWVFLAACLVMFMQPGFAMVETGFTRAKNAGNIIMKNFVDFMVGS...RIQ')
ID: tr|A0A317RMH8|A0A317RMH8_EUBLI
Name: tr|A0A317RMH8|A0A317RMH8_EUBLI
Description: tr|A0A317RMH8|A0A317RMH8_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=C7955_10996 PE=3 SV=1
Number of features: 0
Seq('MINFADTGFILVCAAMVCLMTPALAVFYAGLLRKGNIVDIMFQCFIAMGIVTVL...IVE')
ID: tr|A0A942ZQQ0|A0A942ZQQ0_EUBLI
Name: tr|A0A942ZQQ0|A0A942ZQQ0_EUBLI
Description: tr|A0A942ZQQ0|A0A942ZQQ0_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=KH042_09155 PE=3 SV=1
Number of features: 0
Seq('MINFADTGFILVCAAMVCLMTPALAVFYAGLLRKGNIVDIMFQCFIAMGIVTVL...MVE')
ID: tr|A0A317RML7|A0A317RML7_EUBLI
Name: tr|A0A317RML7|A0A317RML7_EUBLI
Description: tr|A0A317RML7|A0A317RML7_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=C7955_106271 PE=3 SV=1
Number of features: 0
Seq('MFNTGDIAFVLICTILVFFMTPGLSLFYAGMVRRKNTLNTIMSTVFCCGLAIVM...IDQ')
ID: tr|A0A6N2Z556|A0A6N2Z556_EUBLI
Name: tr|A0A6N2Z556|A0A6N2Z556_EUBLI
Description: tr|A0A6N2Z556|A0A6N2Z556_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEMQQLADIVWVFLAACLVMFMQPGFAMVETGFTRAKNAGNIIMKNFVDFMVGS...RIQ')
ID: tr|A0A6N2YNZ0|A0A6N2YNZ0_EUBLI
Name: tr|A0A6N2YNZ0|A0A6N2YNZ0_EUBLI
Description: tr|A0A6N2YNZ0|A0A6N2YNZ0_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MINFADTGFILVCAAMVCLMTPALAVFYAGLLRKGNIVDIMFQCFIAMGIVTVL...MVE')
ID: tr|A0A0U2VGX2|A0A0U2VGX2_EUBLI
Name: tr|A0A0U2VGX2|A0A0U2VGX2_EUBLI
Description: tr|A0A0U2VGX2|A0A0U2VGX2_EUBLI Ammonium transporter OS=Eubacterium limosum OX=1736 GN=ACH52_0371 PE=3 SV=1
Number of features: 0
Seq('MEMQQLADIVWVFLAACLVMFMQPGFAMVETGFTRAKNAGNIIMKNFVDFMVGS...RIQ')
ID: tr|E3GQ97|E3GQ97_9FIRM
Name: tr|E3GQ97|E3GQ97_9FIRM
Description: tr|E3GQ97|E3GQ97_9FIRM Ammonium transporter OS=Eubacterium callanderi OX=53442 GN=ELI_4204 PE=3 SV=1
Number of features: 0
Seq('MEMQQLADIVWVFLAACLVMFMQPGFAMVETGFTRAKNAGNIIMKNFVDFMVGS...RIQ')

ID: tr|E3GI40|E3GI40_9FIRM
Name: tr|E3GI40|E3GI40_9FIRM
Description: tr|E3GI40|E3GI40_9FIRM Ammonium transporter OS=Eubacterium callanderi OX=53442 GN=ELI_0306 PE=3 SV=1
Number of features: 0
Seq('MINFADTGFILVCAAMVCLMTPALAVFYAGLLRKGNIVDIMFQCFIAMGIVTVL...MVE')
ID: tr|A0A2N0MZ27|A0A2N0MZ27_9GAMM
Name: tr|A0A2N0MZ27|A0A2N0MZ27_9GAMM
Description: tr|A0A2N0MZ27|A0A2N0MZ27_9GAMM Ammonium transporter OS=Ewingella americana OX=41202 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLAMMGLGATALLPSIAMAAAPAVANGADNAFMMICTALVLFMTVPGVALF...YNQ')
ID: tr|A0A502GPV4|A0A502GPV4_9GAMM
Name: tr|A0A502GPV4|A0A502GPV4_9GAMM
Description: tr|A0A502GPV4|A0A502GPV4_9GAMM Ammonium transporter OS=Ewingella americana OX=41202 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLSMMGLGAVAMLPSLAMAAAPAVANGADNAFMMICTALVLFMTVPGVALF...YNQ')
ID: tr|A0A085G774|A0A085G774_9GAMM
Name: tr|A0A085G774|A0A085G774_9GAMM
Description: tr|A0A085G774|A0A085G774_9GAMM Ammonium transporter OS=Ewingella americana ATCC 33852 OX=910964 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLAMMGLGATALLPSIAMAAAPAVANGADNAFMMICTALVLFMTVPGVALF...YNQ')
ID: tr|A0A3E2TW06|A0A3E2TW06_9FIRM
Name: tr|A0A3E2TW06|A0A3E2TW06_9FIRM
Description: tr|A0A3E2TW06|A0A3E2TW06_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3R6HLW9|A0A3R6HLW9_9FIRM
Name: tr|A0A3R6HLW9|A0A3R6HLW9_9FIRM
Description: tr|A0A3R6HLW9|A0A3R6HLW9_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A6A8KQL6|A0A6A8KQL6_9FIRM
Name: tr|A0A6A8KQL6|A0A6A8KQL6_9FIRM
Description: tr|A0A6A8KQL6|A0A6A8KQL6_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A844DSN8|A0A844DSN8_9FIRM
Name: tr|A0A844DSN8|A0A844DSN8_9FIRM
Description: tr|A0A844DSN8|A0A844DSN8_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSINTCWVLVAAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A844DI00|A0A844DI00_9FIRM
Name: tr|A0A844DI00|A0A844DI00_9FIRM
Description: tr|A0A844DI00|A0A844DI00_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A413D0R3|A0A413D0R3_9FIRM
Name: tr|A0A413D0R3|A0A413D0R3_9FIRM
Description: tr|A0A413D0R3|A0A413D0R3_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3E2UCG9|A0A3E2UCG9_9FIRM
Name: tr|A0A3E2UCG9|A0A3E2UCG9_9FIRM
Description: tr|A0A3E2UCG9|A0A3E2UCG9_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3E2UHE6|A0A3E2UHE6_9FIRM
Name: tr|A0A3E2UHE6|A0A3E2UHE6_9FIRM
Description: tr|A0A3E2UHE6|A0A3E2UHE6_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3E2VY88|A0A3E2VY88_9FIRM
Name: tr|A0A3E2VY88|A0A3E2VY88_9FIRM
Description: tr|A0A3E2VY88|A0A3E2VY88_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSVNTCWTLVGAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3E2T713|A0A3E2T713_9FIRM
Name: tr|A0A3E2T713|A0A3E2T713_9FIRM
Description: tr|A0A3E2T713|A0A3E2T713_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSINTCWVLVAAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|A0A3E2XB32|A0A3E2XB32_9FIRM
Name: tr|A0A3E2XB32|A0A3E2XB32_9FIRM
Description: tr|A0A3E2XB32|A0A3E2XB32_9FIRM Ammonium transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1
Number of features: 0
Seq('MFSSINTCWVLVAAFLVYFMQAGFALCEAGFTRAKNTGNILMKNMMDFCIGTPC...DVE')
ID: tr|E1SLM7|E1SLM7_FERBD
Name: tr|E1SLM7|E1SLM7_FERBD
Description: tr|E1SLM7|E1SLM7_FERBD Ammonium transporter OS=Ferrimonas balearica (strain DSM 9799 / CCM 4581 / KCTC 23876 / PAT) OX=550540 GN=Fbal_3380 PE=3 SV=1
Number of features: 0
Seq('MEQVTALGATVAELRFALDTFYFLISGALVMWMAAGFAMLEAGLVRSKNTTEIL...TAG')
ID: tr|D3S2L0|D3S2L0_FERPA
Name: tr|D3S2L0|D3S2L0_FERPA
Description: tr|D3S2L0|D3S2L0_FERPA Ammonium transporter OS=Ferroglobus placidus (strain DSM 10642 / AEDII12DO) OX=589924 GN=Ferp_0362 PE=3 SV=1
Number of features: 0
Seq('MEPNGWILTSAALVMLMVPGLALFYAGMVRRKNAVNMIMLSLVSYVIVSLQWVL...AYS')
ID: tr|S0APH6|S0APH6_FERAC
Name: tr|S0APH6|S0APH6_FERAC
Description: tr|S0APH6|S0APH6_FERAC Ammonium transporter OS=Ferroplasma acidarmanus Fer1 OX=333146 GN=FACI_IFERC00001G0119 PE=3 SV=1
Number of features: 0
Seq('MLLNSMILYYTTIPDSTSWLNTGNNGWMLTASTLVGLMSIPGLAIYYAGLTKRK...DKD')
ID: tr|S0AM98|S0AM98_FERAC
Name: tr|S0AM98|S0AM98_FERAC
Description: tr|S0AM98|S0AM98_FERAC Ammonium transporter AmtB-like domain-containing protein OS=Ferroplasma acidarmanus Fer1 OX=333146 GN=FACI_IFERC00001G0428 PE=3 SV=1
Number of features: 0
Seq('MFDFIDYLSISNILINNLWIVIAAIFIFAMTIAVGFLEVGELGKKFKNSMLKTI...SER')
ID: tr|I0KDC6|I0KDC6_9BACT
Name: tr|I0KDC6|I0KDC6_9BACT
Description: tr|I0KDC6|I0KDC6_9BACT Ammonium transporter OS=Fibrella aestuarina BUZ 2 OX=1166018 GN=FAES_4129 PE=3 SV=1
Number of features: 0
Seq('MQKPAIIPLLILLAISVMGVFVPSVPTTIVTEGINSGDTAWMLMATALVLLMTP...IDA')
ID: tr|I2GD40|I2GD40_9BACT
Name: tr|I2GD40|I2GD40_9BACT
Description: tr|I2GD40|I2GD40_9BACT Ammonium transporter OS=Fibrisoma limi BUZ 3 OX=1185876 GN=BN8_00761 PE=3 SV=1
Number of features: 0
Seq('MQKPNYVPLVLLLAVAILGIIPGFNAVPTQIVTEGINSGDTAWMLVATALVLLM...IEG')
ID: tr|A0A068NPW2|A0A068NPW2_FIMGI
Name: tr|A0A068NPW2|A0A068NPW2_FIMGI
Description: tr|A0A068NPW2|A0A068NPW2_FIMGI Ammonium transporter OS=Fimbriimonas ginsengisoli Gsoil 348 OX=661478 GN=OP10G_2103 PE=3 SV=1
Number of features: 0
Seq('MFKSRPFAAFVAATLCTSALAQAPTTPAAPAINWTDTLWVIIAAALVLLMTPAL...YNL')
ID: tr|A0A931PT48|A0A931PT48_FIMGI
Name: tr|A0A931PT48|A0A931PT48_FIMGI
Description: tr|A0A931PT48|A0A931PT48_FIMGI Ammonium transporter OS=Fimbriimonas ginsengisoli OX=1005039 GN=HYR64_02630 PE=3 SV=1
Number of features: 0
Seq('MDKADTAWVLVASVLVLLMTPALSLFYGGLVRHKNVLSTMMQSIWLMGLGTLIW...ATP')
ID: tr|A0A068NV61|A0A068NV61_FIMGI
Name: tr|A0A068NV61|A0A068NV61_FIMGI
Description: tr|A0A068NV61|A0A068NV61_FIMGI Ammonium transporter OS=Fimbriimonas ginsengisoli Gsoil 348 OX=661478 GN=OP10G_2101 PE=3 SV=1
Number of features: 0
Seq('MFYRTRRSLRYLRTAVPIRTVTPAERIKLGATVLGGKFLGLALLFLLLAGGSAL...AQA')
ID: tr|A0A2N6K4Y5|A0A2N6K4Y5_FISMU
Name: tr|A0A2N6K4Y5|A0A2N6K4Y5_FISMU
Description: tr|A0A2N6K4Y5|A0A2N6K4Y5_FISMU Ammonium transporter OS=Fischerella muscicola CCMEE 5323 OX=2019572 GN=CEN44_08680 PE=3 SV=1
Number of features: 0
Seq('MLKKVVMIGAIALVLLAGPLIGNALAAPVDVNAAISNAQTAADTAFMLISAALV...SDK')
ID: tr|A0A2N6JV02|A0A2N6JV02_FISMU
Name: tr|A0A2N6JV02|A0A2N6JV02_FISMU
Description: tr|A0A2N6JV02|A0A2N6JV02_FISMU Ammonium transporter OS=Fischerella muscicola CCMEE 5323 OX=2019572 GN=CEN44_27705 PE=3 SV=1
Number of features: 0
Seq('MLKNKKKSKAKHRRQSRNWNAYKTQSNSIVNQIFWVIQRLSPSWQACIPIACLI...TSL')
ID: tr|A0A243SC06|A0A243SC06_9FLAO
Name: tr|A0A243SC06|A0A243SC06_9FLAO
Description: tr|A0A243SC06|A0A243SC06_9FLAO Ammonium transporter OS=Flavobacterium sp. FPG59 OX=1929267 GN=FPG59_15940 PE=3 SV=1
Number of features: 0
Seq('MRKIVLSVLLIAILLFTLFSNYLIIDTPAPAEAVKFDTGDTAWIIVATALVLIM...EFL')
ID: tr|F8E6R1|F8E6R1_FLESM
Name: tr|F8E6R1|F8E6R1_FLESM
Description: tr|F8E6R1|F8E6R1_FLESM Ammonium transporter OS=Flexistipes sinusarabici (strain ATCC 49648 / DSM 4947 / MAS 10) OX=717231 GN=Flexsi_2339 PE=3 SV=1
Number of features: 0
Seq('MESIVHLSYAIDTFYFLICGALVMWMAAGFAMLEAGLVRSKNTTVILTKNVVLF...TSK')
ID: tr|A0A1I4ZIZ6|A0A1I4ZIZ6_9NEIS
Name: tr|A0A1I4ZIZ6|A0A1I4ZIZ6_9NEIS
Description: tr|A0A1I4ZIZ6|A0A1I4ZIZ6_9NEIS Ammonium transporter OS=Formivibrio citricus OX=83765 GN=SAMN05660284_01654 PE=3 SV=1
Number of features: 0
Seq('MKKLLALIALFGAMTLAAPCFADASAPASAAVTASAVTASDTAAASAPAAAPAP...RVE')
ID: tr|T2KJ59|T2KJ59_FORAG
Name: tr|T2KJ59|T2KJ59_FORAG
Description: tr|T2KJ59|T2KJ59_FORAG Ammonium transporter OS=Formosa agariphila (strain DSM 15362 / KCTC 12365 / LMG 23005 / KMM 3901 / M-2Alg 35-1) OX=1347342 GN=BN863_3170 PE=3 SV=1
Number of features: 0
Seq('MMLLLNSTPALQDAAAVAASVKDDMGMLWMLIAGILVFFMQAGFFLVESGMTDS...FEE')

ID: tr|T2KGT3|T2KGT3_FORAG
Name: tr|T2KGT3|T2KGT3_FORAG
Description: tr|T2KGT3|T2KGT3_FORAG Ammonium transporter OS=Formosa agariphila (strain DSM 15362 / KCTC 12365 / LMG 23005 / KMM 3901 / M-2Alg 35-1) OX=1347342 GN=BN863_3150 PE=3 SV=1
Number of features: 0
Seq('MEGLTINNVWMMVCTALVFFMHLGFAFLEIGLTRQKNTLNILFKNIFIICIGLL...NEH')
ID: tr|Q0RPB4|Q0RPB4_FRAAA
Name: tr|Q0RPB4|Q0RPB4_FRAAA
Description: tr|Q0RPB4|Q0RPB4_FRAAA Ammonium transporter OS=Frankia alni (strain DSM 45986 / CECT 9034 / ACN14a) OX=326424 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MPFDFGTIDTGDTAWVLASAALVLLMTPGLAFFYGGMVRVENVLSMIMQNFFCM...RLW')
ID: tr|H8L2Q4|H8L2Q4_FRAAD
Name: tr|H8L2Q4|H8L2Q4_FRAAD
Description: tr|H8L2Q4|H8L2Q4_FRAAD Ammonium transporter OS=Frateuria aurantia (strain ATCC 33424 / DSM 6220 / KCTC 2777 / LMG 1558 / NBRC 3245 / NCIMB 13370) OX=767434 GN=Fraau_2029 PE=3 SV=1
Number of features: 0
Seq('MRCKSALIPLLAGLGASGPLLAQSTPAAALDHGDTAWMLTSSMLVLLMTIPGLA...YNL')
ID: tr|A0A3F3HWV6|A0A3F3HWV6_9LACO
Name: tr|A0A3F3HWV6|A0A3F3HWV6_9LACO
Description: tr|A0A3F3HWV6|A0A3F3HWV6_9LACO Ammonium transporter OS=Fructobacillus fructosus KCTC 3544 OX=930946 GN=IV71_GL000616 PE=3 SV=1
Number of features: 0
Seq('MQAGDIAFILISSLLVWLMTPGLAFFYAGVADEKNRLYMLRLGLIIIGLVSILW...GLN')
ID: tr|A0A0P0Z9P6|A0A0P0Z9P6_9HYPH
Name: tr|A0A0P0Z9P6|A0A0P0Z9P6_9HYPH
Description: tr|A0A0P0Z9P6|A0A0P0Z9P6_9HYPH Ammonium transporter OS=Fulvimarina pelagi OX=217511 PE=3 SV=1
Number of features: 0
Seq('MAAASVTVAAFLQASVALAQDAGAGAEAAAATVDKGDVAWMMTATLLVLFMTMP...YHS')
ID: tr|Q0G0A4|Q0G0A4_9HYPH
Name: tr|Q0G0A4|Q0G0A4_9HYPH
Description: tr|Q0G0A4|Q0G0A4_9HYPH Ammonium transporter OS=Fulvimarina pelagi HTCC2506 OX=314231 GN=FP2506_03144 PE=3 SV=1
Number of features: 0
Seq('MAAASVTVAAFLQASVALAQDAGAGAEAAAATVDKGDVAWMMTATLLVLFMTMP...YHS')
ID: tr|A0A0N7KZ12|A0A0N7KZ12_9HYPH
Name: tr|A0A0N7KZ12|A0A0N7KZ12_9HYPH
Description: tr|A0A0N7KZ12|A0A0N7KZ12_9HYPH Ammonium transporter OS=Fulvimarina pelagi OX=217511 PE=3 SV=1
Number of features: 0
Seq('MNLKKIFYFAALGAGLTATAAFAQDAAAPAAEAAADAAAPAADAAASGEAPGDQ...GQR')
ID: tr|Q0G0A3|Q0G0A3_9HYPH
Name: tr|Q0G0A3|Q0G0A3_9HYPH
Description: tr|Q0G0A3|Q0G0A3_9HYPH Ammonium transporter OS=Fulvimarina pelagi HTCC2506 OX=314231 GN=FP2506_03149 PE=3 SV=1
Number of features: 0
Seq('MNLKKIFYFAALGAGLTATAAFAQDAAAPAAEAAADAAAPAADAAASGEAPGDQ...GQR')
ID: tr|Q0G2V0|Q0G2V0_9HYPH
Name: tr|Q0G2V0|Q0G2V0_9HYPH
Description: tr|Q0G2V0|Q0G2V0_9HYPH Ammonium transporter family protein OS=Fulvimarina pelagi HTCC2506 OX=314231 GN=FP2506_16649 PE=4 SV=1
Number of features: 0
Seq('MEQQLMELGQKVAALEAGTGMSNTVNMEIFYWWCTALMITIHAGFLAYEMGASR...PAE')
ID: tr|Q0G2U1|Q0G2U1_9HYPH
Name: tr|Q0G2U1|Q0G2U1_9HYPH
Description: tr|Q0G2U1|Q0G2U1_9HYPH Ammonium transporter family protein OS=Fulvimarina pelagi HTCC2506 OX=314231 GN=FP2506_16694 PE=4 SV=1
Number of features: 0
Seq('MFAEQVTLSSLVQNLIYASGTVGAIMVVIGLLLIDAGTVRTNNLFNTTIEKVIG...PAE')
ID: tr|Q0G2T1|Q0G2T1_9HYPH
Name: tr|Q0G2T1|Q0G2T1_9HYPH
Description: tr|Q0G2T1|Q0G2T1_9HYPH Ammonium transporter family protein OS=Fulvimarina pelagi HTCC2506 OX=314231 GN=FP2506_16744 PE=4 SV=1
Number of features: 0
Seq('MGSNIEALTTLFTEFYYWVTVVFMFLIHVGFCLYEVAASRRRNHLHTLMKNTMC...SKT')
ID: tr|L8JUH3|L8JUH3_9BACT
Name: tr|L8JUH3|L8JUH3_9BACT
Description: tr|L8JUH3|L8JUH3_9BACT Ammonium transporter OS=Fulvivirga imtechensis AK7 OX=1237149 GN=C900_02263 PE=3 SV=1
Number of features: 0
Seq('MQVIMEKLFLSEFLMASGESALDATAKVDDLMAISVEGLFTANNVWMMLATVLV...YDE')
ID: tr|K2IMJ7|K2IMJ7_9GAMM
Name: tr|K2IMJ7|K2IMJ7_9GAMM
Description: tr|K2IMJ7|K2IMJ7_9GAMM Ammonium transporter OS=Gallaecimonas xiamenensis 3-C-1 OX=745411 GN=B3C1_12284 PE=3 SV=1
Number of features: 0
Seq('MDQPSIQIAYALDTFYLLVSGAFVMWMAAGFAMLEAGLVRAKNTTEILTKNAVL...ISK')
ID: tr|A0A837CWL2|A0A837CWL2_9PAST
Name: tr|A0A837CWL2|A0A837CWL2_9PAST
Description: tr|A0A837CWL2|A0A837CWL2_9PAST Ammonium transporter OS=Gallibacterium anatis OX=750 GN=JP27_07720 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|A0A0A3A148|A0A0A3A148_9PAST
Name: tr|A0A0A3A148|A0A0A3A148_9PAST
Description: tr|A0A0A3A148|A0A0A3A148_9PAST Ammonium transporter OS=Gallibacterium anatis OX=750 GN=IO49_11315 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|A0A0A2ZRL7|A0A0A2ZRL7_9PAST
Name: tr|A0A0A2ZRL7|A0A0A2ZRL7_9PAST
Description: tr|A0A0A2ZRL7|A0A0A2ZRL7_9PAST Ammonium transporter OS=Gallibacterium anatis 4895 OX=1396510 GN=IO48_10695 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|F4H924|F4H924_GALAU
Name: tr|F4H924|F4H924_GALAU
Description: tr|F4H924|F4H924_GALAU Ammonium transporter OS=Gallibacterium anatis (strain UMN179) OX=1005058 GN=UMN179_02343 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|A0A0A2Y4H8|A0A0A2Y4H8_9PAST
Name: tr|A0A0A2Y4H8|A0A0A2Y4H8_9PAST
Description: tr|A0A0A2Y4H8|A0A0A2Y4H8_9PAST Ammonium transporter OS=Gallibacterium anatis IPDH697-78 OX=1396514 GN=JP30_10540 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|U1H1F7|U1H1F7_9PAST
Name: tr|U1H1F7|U1H1F7_9PAST
Description: tr|U1H1F7|U1H1F7_9PAST Ammonium transporter OS=Gallibacterium anatis 12656/12 OX=1195244 GN=N561_07070 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|A0A0A3AIB6|A0A0A3AIB6_9PAST
Name: tr|A0A0A3AIB6|A0A0A3AIB6_9PAST
Description: tr|A0A0A3AIB6|A0A0A3AIB6_9PAST Ammonium transporter OS=Gallibacterium anatis OX=750 GN=CF557_07155 PE=3 SV=1
Number of features: 0
Seq('MKKYRWLLAFLPITAHAELTDWIQPISAISAGDTAWVMLAAILVLFMTIPGLAL...RLE')
ID: tr|D9SI59|D9SI59_GALCS
Name: tr|D9SI59|D9SI59_GALCS
Description: tr|D9SI59|D9SI59_GALCS Ammonium transporter OS=Gallionella capsiferriformans (strain ES-2) OX=395494 GN=Galf_0071 PE=3 SV=1
Number of features: 0
Seq('MRKIFASFMLIAALCGLSASGFAEEAASAVVSATEVASAVVSATEAAPVMAVVA...YNY')
ID: tr|D9SI36|D9SI36_GALCS
Name: tr|D9SI36|D9SI36_GALCS
Description: tr|D9SI36|D9SI36_GALCS Ammonium transporter OS=Gallionella capsiferriformans (strain ES-2) OX=395494 GN=Galf_2121 PE=3 SV=1
Number of features: 0
Seq('MENLQTSNDVLFILLGAIMVLAMHAGFAFLELGTVRKKNQVNALVKILTDFSVS...SGW')
ID: tr|C1A872|C1A872_GEMAT
Name: tr|C1A872|C1A872_GEMAT
Description: tr|C1A872|C1A872_GEMAT Ammonium transporter OS=Gemmatimonas aurantiaca (strain T-27 / DSM 14586 / JCM 11422 / NBRC 100505) OX=379066 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MSFALSTLLAAQEVVAAEVAAPATLAPAISAGDTAWVLVSTALVAFMVPGLAFF...RTA')
ID: tr|A0A3D4V557|A0A3D4V557_9BACT
Name: tr|A0A3D4V557|A0A3D4V557_9BACT
Description: tr|A0A3D4V557|A0A3D4V557_9BACT Ammonium transporter OS=Gemmatimonas aurantiaca OX=173480 GN=DGD08_03400 PE=3 SV=1
Number of features: 0
Seq('MSFALSTLLAAQEVVAAEVAAPATLAPAISAGDTAWVLVSTALVAFMVPGLAFF...RTA')
ID: tr|A0A1G9P6Q0|A0A1G9P6Q0_9BACT
Name: tr|A0A1G9P6Q0|A0A1G9P6Q0_9BACT
Description: tr|A0A1G9P6Q0|A0A1G9P6Q0_9BACT Ammonium transporter OS=Geoalkalibacter ferrihydriticus OX=392333 GN=SAMN05660860_01491 PE=3 SV=1
Number of features: 0
Seq('MKKTTLFIVAAVLGVLALPASALAEETVISEVAFILNSFSFLISGVLVMWMAAG...KLR')
ID: tr|A0A0C2HHF2|A0A0C2HHF2_9BACT
Name: tr|A0A0C2HHF2|A0A0C2HHF2_9BACT
Description: tr|A0A0C2HHF2|A0A0C2HHF2_9BACT Ammonium transporter OS=Geoalkalibacter ferrihydriticus DSM 17813 OX=1121915 GN=GFER_09385 PE=3 SV=1
Number of features: 0
Seq('MKKTTLFIVAAVLGVLALPASALAEETVISEVAFILNSFSFLISGVLVMWMAAG...KLR')
ID: tr|A0A0B5FNH4|A0A0B5FNH4_9BACT
Name: tr|A0A0B5FNH4|A0A0B5FNH4_9BACT
Description: tr|A0A0B5FNH4|A0A0B5FNH4_9BACT Ammonium transporter OS=Geoalkalibacter subterraneus OX=483547 GN=GSUB_05885 PE=3 SV=1
Number of features: 0
Seq('MKKILTLILAFSALLLLSSPALAQVEVGPEVAFILNTFSFLISGVLVMWMAAGF...GLK')
ID: tr|A0A0D8BQX6|A0A0D8BQX6_GEOKU
Name: tr|A0A0D8BQX6|A0A0D8BQX6_GEOKU
Description: tr|A0A0D8BQX6|A0A0D8BQX6_GEOKU Ammonium transporter OS=Geobacillus kaustophilus OX=1462 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTLGLDALWMMLSAVLVIGMQAGFALLEAGSTRMKNSGHVAGKQILSFSIASLA...AQQ')
ID: tr|U2WTW8|U2WTW8_GEOKU
Name: tr|U2WTW8|U2WTW8_GEOKU
Description: tr|U2WTW8|U2WTW8_GEOKU Ammonium transporter OS=Geobacillus kaustophilus GBlys OX=1337888 GN=GBL_2433 PE=3 SV=1
Number of features: 0
Seq('MRKMDEKTLTLGLDALWVMLSAVLVIGMQAGFALLEAGSTRMKNSGHVAGKQIL...AQQ')
ID: tr|Q5KZZ9|Q5KZZ9_GEOKA
Name: tr|Q5KZZ9|Q5KZZ9_GEOKA
Description: tr|Q5KZZ9|Q5KZZ9_GEOKA Ammonium transporter OS=Geobacillus kaustophilus (strain HTA426) OX=235909 GN=GK1452 PE=3 SV=1
Number of features: 0
Seq('MRKMDEKTLTLGLDALWVMLSAVLVIGMQAGFALLEAGSTRMKNSGHVAGKQIL...AQQ')

ID: tr|A0A4D7Q9P4|A0A4D7Q9P4_GEOKU
Name: tr|A0A4D7Q9P4|A0A4D7Q9P4_GEOKU
Description: tr|A0A4D7Q9P4|A0A4D7Q9P4_GEOKU Ammonium transporter OS=Geobacillus kaustophilus NBRC 102445 OX=1220595 GN=E5Z46_11155 PE=3 SV=1
Number of features: 0
Seq('MDEKTLTLGLDALWVMLSAVLVIGMQAGFALLEAGSTRMKNSGHVAGKQILSFA...AQQ')
ID: tr|A0A1I5GN22|A0A1I5GN22_9ACTN
Name: tr|A0A1I5GN22|A0A1I5GN22_9ACTN
Description: tr|A0A1I5GN22|A0A1I5GN22_9ACTN Ammonium transporter OS=Geodermatophilus obscurus OX=1861 GN=SAMN05660359_02930 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAWVLISAALVLFMTPGLALFYGGMVRAKSVLNMMMMSFGALALISVLW...SRV')
ID: tr|A0A1M7UEG2|A0A1M7UEG2_9ACTN
Name: tr|A0A1M7UEG2|A0A1M7UEG2_9ACTN
Description: tr|A0A1M7UEG2|A0A1M7UEG2_9ACTN Ammonium transporter OS=Geodermatophilus obscurus OX=1861 GN=SAMN05660350_03060 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAWVLASAALVLFMTPGLALFYGGMVRAKSVLNMMMMSFGALALISVLW...SRA')
ID: tr|D2SE15|D2SE15_GEOOG
Name: tr|D2SE15|D2SE15_GEOOG
Description: tr|D2SE15|D2SE15_GEOOG Ammonium transporter OS=Geodermatophilus obscurus (strain ATCC 25078 / DSM 43160 / JCM 3152 / KCC A-0152 / KCTC 9177 / NBRC 13315 / NRRL B-3577 / G-20) OX=526225 GN=Gobs_4015 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAWVLASAALVLFMTPGLALFYGGMVRAKSVLNMMMMSFGALALISVLW...SRA')
ID: tr|A0A410JZR4|A0A410JZR4_9BACT
Name: tr|A0A410JZR4|A0A410JZR4_9BACT
Description: tr|A0A410JZR4|A0A410JZR4_9BACT Ammonium transporter OS=Geovibrio thiophilus OX=139438 GN=EP073_09115 PE=3 SV=1
Number of features: 0
Seq('MKFVAGVLTLLLSVTAFAGEGEINSGDTAWVLVSAALVLFMLPGLAMFYGGMVR...IKL')
ID: tr|A0A410K1J5|A0A410K1J5_9BACT
Name: tr|A0A410K1J5|A0A410K1J5_9BACT
Description: tr|A0A410K1J5|A0A410K1J5_9BACT Ammonium transporter OS=Geovibrio thiophilus OX=139438 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKIIIMLGLVLMAASGFADDEPLTLEGVQASVDAVQANADWLWTLIAAFMVFF...LIK')
ID: tr|A0A1H9M798|A0A1H9M798_9BURK
Name: tr|A0A1H9M798|A0A1H9M798_9BURK
Description: tr|A0A1H9M798|A0A1H9M798_9BURK Ammonium transporter OS=Giesbergeria anulus OX=180197 GN=SAMN02982919_01893 PE=3 SV=1
Number of features: 0
Seq('MQTKRYKAGLMMVWALGMLLAWGPASAQVASAPIRPTLVAQDTLHDADTVWILV...LGN')
ID: tr|A0A1H9RTW8|A0A1H9RTW8_9BURK
Name: tr|A0A1H9RTW8|A0A1H9RTW8_9BURK
Description: tr|A0A1H9RTW8|A0A1H9RTW8_9BURK Ammonium transporter OS=Giesbergeria anulus OX=180197 GN=SAMN02982919_02961 PE=3 SV=1
Number of features: 0
Seq('MKKLLASVLLGLGVLASALPASAQTTAASEPAAVVAPAAPAAADPAAVAPAPAA...YTR')
ID: tr|A0A1B9JHS5|A0A1B9JHS5_9GAMM
Name: tr|A0A1B9JHS5|A0A1B9JHS5_9GAMM
Description: tr|A0A1B9JHS5|A0A1B9JHS5_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G17_03200 PE=3 SV=1
Number of features: 0
Seq('MLKKCILPLCLIFPSYAFADVVLEHADNADNGFMMICTALVLFMSIPGIALFYG...FNS')
ID: tr|A0A1B9JZS5|A0A1B9JZS5_9GAMM
Name: tr|A0A1B9JZS5|A0A1B9JZS5_9GAMM
Description: tr|A0A1B9JZS5|A0A1B9JZS5_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G12_09815 PE=3 SV=1
Number of features: 0
Seq('MFKKFTLSVLFLLASPAFADEVAVADKADNGFMMICTALVLFMSVPGIALFYGG...FNN')
ID: tr|A0A1B9LFW3|A0A1B9LFW3_9GAMM
Name: tr|A0A1B9LFW3|A0A1B9LFW3_9GAMM
Description: tr|A0A1B9LFW3|A0A1B9LFW3_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G22_02995 PE=3 SV=1
Number of features: 0
Seq('MLKKFIFSLAILFSSSAFADEAGIVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1B9NQ91|A0A1B9NQ91_9GAMM
Name: tr|A0A1B9NQ91|A0A1B9NQ91_9GAMM
Description: tr|A0A1B9NQ91|A0A1B9NQ91_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G44_01675 PE=3 SV=1
Number of features: 0
Seq('MLKKIIPFLVILFSSSAFAEEAAVVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1B9K8L2|A0A1B9K8L2_9GAMM
Name: tr|A0A1B9K8L2|A0A1B9K8L2_9GAMM
Description: tr|A0A1B9K8L2|A0A1B9K8L2_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G13_05735 PE=3 SV=1
Number of features: 0
Seq('MFKKLTLSLMFLLASPVFADEVAVADKADNGFMMICTALVLFMSVPGIALFYGG...FNN')
ID: tr|A0A2V4EA49|A0A2V4EA49_9GAMM
Name: tr|A0A2V4EA49|A0A2V4EA49_9GAMM
Description: tr|A0A2V4EA49|A0A2V4EA49_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=DKK70_05315 PE=3 SV=1
Number of features: 0
Seq('MLKKIIFSLGLLLTCPVFAEEVAIVDKADNGFMMICTALVLFMSVPGIAFFYGG...FNN')
ID: tr|A0A1B9M5B8|A0A1B9M5B8_9GAMM
Name: tr|A0A1B9M5B8|A0A1B9M5B8_9GAMM
Description: tr|A0A1B9M5B8|A0A1B9M5B8_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G35_08100 PE=3 SV=1
Number of features: 0
Seq('MLKKIIFSLIILFSSSVFADESAIVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1B9MYL7|A0A1B9MYL7_9GAMM
Name: tr|A0A1B9MYL7|A0A1B9MYL7_9GAMM
Description: tr|A0A1B9MYL7|A0A1B9MYL7_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G48_00855 PE=3 SV=1
Number of features: 0
Seq('MLIKLLSLITLVLLTVPAFAEEVTISDKADNGFMMISTVLVLFMSFPGIALFYG...FNS')
ID: tr|A0A1B9N3H7|A0A1B9N3H7_9GAMM
Name: tr|A0A1B9N3H7|A0A1B9N3H7_9GAMM
Description: tr|A0A1B9N3H7|A0A1B9N3H7_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G43_07555 PE=3 SV=1
Number of features: 0
Seq('MLKKIILFLVILFSSSAFAEGAAIVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1C0A1D9|A0A1C0A1D9_9GAMM
Name: tr|A0A1C0A1D9|A0A1C0A1D9_9GAMM
Description: tr|A0A1C0A1D9|A0A1C0A1D9_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G07_08865 PE=3 SV=1
Number of features: 0
Seq('MLKKIILSLSLVLASPVFADEVEIADKADNGFMMICTALVLFMSVPGIAFFYGG...FNS')
ID: tr|A0A1B9JPL5|A0A1B9JPL5_9GAMM
Name: tr|A0A1B9JPL5|A0A1B9JPL5_9GAMM
Description: tr|A0A1B9JPL5|A0A1B9JPL5_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G10_10435 PE=3 SV=1
Number of features: 0
Seq('MLKKISLVFGLLVSGSVLANEIPIADKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1B9KID3|A0A1B9KID3_9GAMM
Name: tr|A0A1B9KID3|A0A1B9KID3_9GAMM
Description: tr|A0A1B9KID3|A0A1B9KID3_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G09_11405 PE=3 SV=1
Number of features: 0
Seq('MLKKFILPLGLALSSSAIAQEATVADNADNGFMMICTALVLFMSVPGIALFYGG...FNN')
ID: tr|A0A1B9M1A9|A0A1B9M1A9_9GAMM
Name: tr|A0A1B9M1A9|A0A1B9M1A9_9GAMM
Description: tr|A0A1B9M1A9|A0A1B9M1A9_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G25_05850 PE=3 SV=1
Number of features: 0
Seq('MLKKIIPFLVILFSSSAFAEEAAVVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A1B9MBX6|A0A1B9MBX6_9GAMM
Name: tr|A0A1B9MBX6|A0A1B9MBX6_9GAMM
Description: tr|A0A1B9MBX6|A0A1B9MBX6_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G40_13865 PE=3 SV=1
Number of features: 0
Seq('MLKKAILCLTILFSSSAFAGEVGIADKADNGFMMICTALVLFMSIPGIALFYGG...FNS')
ID: tr|A0A1B9MZ78|A0A1B9MZ78_9GAMM
Name: tr|A0A1B9MZ78|A0A1B9MZ78_9GAMM
Description: tr|A0A1B9MZ78|A0A1B9MZ78_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G30_06755 PE=3 SV=1
Number of features: 0
Seq('MLKKAILCLMILFSSSAFAGEVDIADKADNGFMMICTTLVLFMSIPGIALFYGG...FNS')
ID: tr|A0A242NIL1|A0A242NIL1_9GAMM
Name: tr|A0A242NIL1|A0A242NIL1_9GAMM
Description: tr|A0A242NIL1|A0A242NIL1_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=B6D08_07640 PE=3 SV=1
Number of features: 0
Seq('MLKKCILPLCLIFPTCAFADVVIDHADNADNGFMMICTALVLFMSIPGIALFYG...FNS')
ID: tr|A0A657K391|A0A657K391_9GAMM
Name: tr|A0A657K391|A0A657K391_9GAMM
Description: tr|A0A657K391|A0A657K391_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G31_05245 PE=3 SV=1
Number of features: 0
Seq('MLKKIIPFLVILFSSSAFAEEAAVVDKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A556RTU3|A0A556RTU3_9GAMM
Name: tr|A0A556RTU3|A0A556RTU3_9GAMM
Description: tr|A0A556RTU3|A0A556RTU3_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MLKKFILCFGLALASPVFAEEVAIADKADNGFMMICTALVLFMSVPGIALFYGG...FNS')
ID: tr|A0A556SRH6|A0A556SRH6_9GAMM
Name: tr|A0A556SRH6|A0A556SRH6_9GAMM
Description: tr|A0A556SRH6|A0A556SRH6_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MLKKCILPLCLIFPTCAFADVVLEHADNADNGFMMICTALVLFMSIPGIALFYG...FNS')
ID: tr|A0A1B9NRG7|A0A1B9NRG7_9GAMM
Name: tr|A0A1B9NRG7|A0A1B9NRG7_9GAMM
Description: tr|A0A1B9NRG7|A0A1B9NRG7_9GAMM Ammonium transporter OS=Gilliamella apicola OX=1196095 GN=A9G42_12745 PE=3 SV=1
Number of features: 0
Seq('MLKKAILYLTILFSSSAFAGEVGIADKADNGFMMICTALVLFMSIPGIALFYGG...FNS')
ID: tr|G4QHD2|G4QHD2_GLANF
Name: tr|G4QHD2|G4QHD2_GLANF
Description: tr|G4QHD2|G4QHD2_GLANF Diguanylate cyclase/phosphodiesterase with PAS/PAC and GAF sensor(S) OS=Glaciecola nitratireducens (strain JCM 12485 / KCTC 12276 / FR1064) OX=1085623 GN=GNIT_1647 PE=3 SV=1
Number of features: 0
Seq('MDYGWLLLSSMLVFLMQAGFLCLETGKIRSKNSINVAAKNISDFIIAAIIFWLF...NSH')
ID: tr|Q7NCB8|Q7NCB8_GLOVI
Name: tr|Q7NCB8|Q7NCB8_GLOVI
Description: tr|Q7NCB8|Q7NCB8_GLOVI Ammonium transporter OS=Gloeobacter violaceus (strain ATCC 29082 / PCC 7421) OX=251221 GN=glr3061 PE=3 SV=1
Number of features: 0
Seq('MLMKCKWKWGLGTLAAALATAAPAFAQDAPKIDTGDTAWVLVSAALVLLMTPGL...QQE')

ID: tr|Q8GQS1|Q8GQS1_GLUDI
Name: tr|Q8GQS1|Q8GQS1_GLUDI
Description: tr|Q8GQS1|Q8GQS1_GLUDI Ammonium transporter OS=Gluconacetobacter diazotrophicus OX=33996 GN=amtB1 PE=3 SV=1
Number of features: 0
Seq('MSLPRTIRTFSPRGTTIALATLAGAALPAMAAPAMAADPAPPAINTGDTAWMLV...RIN')
ID: tr|A0A7W4NFW5|A0A7W4NFW5_GLUDI
Name: tr|A0A7W4NFW5|A0A7W4NFW5_GLUDI
Description: tr|A0A7W4NFW5|A0A7W4NFW5_GLUDI Ammonium transporter OS=Gluconacetobacter diazotrophicus OX=33996 GN=HLH33_11875 PE=3 SV=1
Number of features: 0
Seq('MNGSNSCFRRLTLAAPAAAMALLAAPSIASAADPAPPPPINTGDTAWMLTSTAL...KIS')
ID: tr|A0A7W4FEM1|A0A7W4FEM1_GLUDI
Name: tr|A0A7W4FEM1|A0A7W4FEM1_GLUDI
Description: tr|A0A7W4FEM1|A0A7W4FEM1_GLUDI Ammonium transporter OS=Gluconacetobacter diazotrophicus OX=33996 GN=HLH33_08510 PE=3 SV=1
Number of features: 0
Seq('MSLPRTIRTFSPRGTTIALATLAGAALPAMAAPAMAADPAPPAINTGDTAWMLV...RIN')
ID: tr|B5ZDQ6|B5ZDQ6_GLUDA
Name: tr|B5ZDQ6|B5ZDQ6_GLUDA
Description: tr|B5ZDQ6|B5ZDQ6_GLUDA Ammonium transporter OS=Gluconacetobacter diazotrophicus (strain ATCC 49037 / DSM 5601 / CCUG 37298 / CIP 103539 / LMG 7603 / PAl5) OX=272568 GN=Gdia_0598 PE=3 SV=1
Number of features: 0
Seq('MSLPRTIRTFSPRGTTIALATLAGAALPAMAAPAMAADPAPPAINTGDTAWMLV...RIN')
ID: tr|A9HMD6|A9HMD6_GLUDA
Name: tr|A9HMD6|A9HMD6_GLUDA
Description: tr|A9HMD6|A9HMD6_GLUDA Ammonium transporter OS=Gluconacetobacter diazotrophicus (strain ATCC 49037 / DSM 5601 / CCUG 37298 / CIP 103539 / LMG 7603 / PAl5) OX=272568 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MSLPRTIRTFSPRGTTIALATLAGAALPAMAAPAMAADPAPPAINTGDTPWMLV...RIN')
ID: tr|A9H9C4|A9H9C4_GLUDA
Name: tr|A9H9C4|A9H9C4_GLUDA
Description: tr|A9H9C4|A9H9C4_GLUDA Ammonium transporter OS=Gluconacetobacter diazotrophicus (strain ATCC 49037 / DSM 5601 / CCUG 37298 / CIP 103539 / LMG 7603 / PAl5) OX=272568 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNGSNSCFRRLTLAAPAAAMALLAAPSIASAADPAPPPPINTGDTAWMLTSTAL...KIS')
ID: tr|A0A149RYW7|A0A149RYW7_GLUOY
Name: tr|A0A149RYW7|A0A149RYW7_GLUOY
Description: tr|A0A149RYW7|A0A149RYW7_GLUOY Ammonium transporter OS=Gluconobacter oxydans OX=442 GN=AD934_03790 PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGAVALPAIAHAAPASAPIDTGDTAWMLVSTAFVLMMTIP...RIN')
ID: tr|A0A149UA34|A0A149UA34_GLUOY
Name: tr|A0A149UA34|A0A149UA34_GLUOY
Description: tr|A0A149UA34|A0A149UA34_GLUOY Ammonium transporter OS=Gluconobacter oxydans OX=442 GN=AD950_12300 PE=3 SV=1
Number of features: 0
Seq('MRRSVLSLAAGAVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIPGLALF...RIN')
ID: tr|A0A4R4A245|A0A4R4A245_GLUOY
Name: tr|A0A4R4A245|A0A4R4A245_GLUOY
Description: tr|A0A4R4A245|A0A4R4A245_GLUOY Ammonium transporter OS=Gluconobacter oxydans OX=442 GN=EDC20_1041 PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGVVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIP...LGW')
ID: tr|Q5FSX6|Q5FSX6_GLUOX
Name: tr|Q5FSX6|Q5FSX6_GLUOX
Description: tr|Q5FSX6|Q5FSX6_GLUOX Ammonium transporter OS=Gluconobacter oxydans (strain 621H) OX=290633 GN=GOX0743 PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGVVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIP...RIN')
ID: tr|A0A829X098|A0A829X098_GLUOY
Name: tr|A0A829X098|A0A829X098_GLUOY
Description: tr|A0A829X098|A0A829X098_GLUOY Ammonium transporter OS=Gluconobacter oxydans NBRC 3293 OX=1315969 GN=NBRC3293_0687 PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGVVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIP...RIN')
ID: tr|A0A067Z3S3|A0A067Z3S3_GLUOY
Name: tr|A0A067Z3S3|A0A067Z3S3_GLUOY
Description: tr|A0A067Z3S3|A0A067Z3S3_GLUOY Ammonium transporter OS=Gluconobacter oxydans DSM 3504 OX=1288313 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGAVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIP...RIN')
ID: tr|A0A149SNB1|A0A149SNB1_GLUTH
Name: tr|A0A149SNB1|A0A149SNB1_GLUTH
Description: tr|A0A149SNB1|A0A149SNB1_GLUTH Ammonium transporter OS=Gluconobacter thailandicus OX=257438 GN=AD940_13320 PE=3 SV=1
Number of features: 0
Seq('MKGSCLSLMAAAALLPASAMAADVPAAIDTGDTAWMLISTALVLMMTVPGLALF...RIN')
ID: tr|A0A149QSR6|A0A149QSR6_9PROT
Name: tr|A0A149QSR6|A0A149QSR6_9PROT
Description: tr|A0A149QSR6|A0A149QSR6_9PROT Ammonium transporter OS=Gluconobacter potus OX=2724927 GN=AD929_12160 PE=3 SV=1
Number of features: 0
Seq('MAAPALRRSVLSLAAGAVALPAIAHAAPAAAPIDTGDTAWMLVSTAFVLMMTIP...RIN')
ID: tr|A0A149S1Z1|A0A149S1Z1_GLUJA
Name: tr|A0A149S1Z1|A0A149S1Z1_GLUJA
Description: tr|A0A149S1Z1|A0A149S1Z1_GLUJA Ammonium transporter OS=Gluconobacter japonicus OX=376620 GN=AD935_10550 PE=3 SV=1
Number of features: 0
Seq('MKGSCLSLMAAAALLPASAMAADAPAAIDTGDTSWMLVSTALVLMMTVPGLALF...RIN')
ID: tr|A0A149QAW7|A0A149QAW7_9PROT
Name: tr|A0A149QAW7|A0A149QAW7_9PROT
Description: tr|A0A149QAW7|A0A149QAW7_9PROT Ammonium transporter OS=Acetobacter cerevisiae OX=178900 GN=AD928_07480 PE=3 SV=1
Number of features: 0
Seq('MNSRFLTGSPRASVFSKLSALSALAGSVVFFLSARIAHAADTAPTIDTGDTAWM...RIN')
ID: tr|A0A149U2G9|A0A149U2G9_9PROT
Name: tr|A0A149U2G9|A0A149U2G9_9PROT
Description: tr|A0A149U2G9|A0A149U2G9_9PROT Ammonium transporter OS=Acetobacter senegalensis OX=446692 GN=AD948_07960 PE=3 SV=1
Number of features: 0
Seq('MASRSFTVSPVSGGLNRQAVISALVGGILLLPSGLAHAADAEPAIDTGDTAWML...RIN')
ID: tr|A0A149TSA9|A0A149TSA9_9PROT
Name: tr|A0A149TSA9|A0A149TSA9_9PROT
Description: tr|A0A149TSA9|A0A149TSA9_9PROT Ammonium transporter OS=Acetobacter tropicalis OX=104102 GN=AD947_13215 PE=3 SV=1
Number of features: 0
Seq('MASRSFTVSPVSGGLNRQAVISALVGGILLLPSGFAHAADAGPAIDTGDTAWML...RIN')
ID: tr|I1KKI2|I1KKI2_SOYBN
Name: tr|I1KKI2|I1KKI2_SOYBN
Description: tr|I1KKI2|I1KKI2_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=GLYMA_07G153800 PE=3 SV=1
Number of features: 0
Seq('MATPLAYQEHLPAAPEWLNKGDNAWQLTAATLVGLQSMPGLVILYASIVKKKWA...INL')
ID: tr|K7K8C3|K7K8C3_SOYBN
Name: tr|K7K8C3|K7K8C3_SOYBN
Description: tr|K7K8C3|K7K8C3_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=GLYMA_02G143600 PE=3 SV=1
Number of features: 0
Seq('MSHLPSNLLPVDGSPEWMNRGDNTWQLTSATLVGLQSVPGLVILYGSIVKKKWA...LRT')
ID: tr|K7K3F5|K7K3F5_SOYBN
Name: tr|K7K3F5|K7K3F5_SOYBN
Description: tr|K7K3F5|K7K3F5_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=100798599 PE=3 SV=1
Number of features: 0
Seq('MATPTAYQEHLPASPHWLNKGDNAWQLTAATLVGLQSMPGLVILYASMVKKKWA...IDL')
ID: tr|I1L774|I1L774_SOYBN
Name: tr|I1L774|I1L774_SOYBN
Description: tr|I1L774|I1L774_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=100787856 PE=3 SV=2
Number of features: 0
Seq('MSGVPLPSNLLPGDGSPEWFSRADNAWQLIAATLVGLQSVPGLIILYGGAVKKK...MSN')
ID: tr|I1N306|I1N306_SOYBN
Name: tr|I1N306|I1N306_SOYBN
Description: tr|I1N306|I1N306_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=100783281 PE=3 SV=1
Number of features: 0
Seq('MATPLAYQEHLPAAPSWLNKGDNAWQLTAATLVGLQSMPGLVILYASIVKKKWA...INL')
ID: tr|I1K536|I1K536_SOYBN
Name: tr|I1K536|I1K536_SOYBN
Description: tr|I1K536|I1K536_SOYBN Ammonium transporter OS=Glycine max OX=3847 GN=100785993 PE=3 SV=2
Number of features: 0
Seq('MATPPVNSLPIAYQAWTSLGVPDWLNKGDNAWQMVSATLVGIQSMPGLVILYGS...QVV')
ID: tr|A0A7X5BZ76|A0A7X5BZ76_9BACL
Name: tr|A0A7X5BZ76|A0A7X5BZ76_9BACL
Description: tr|A0A7X5BZ76|A0A7X5BZ76_9BACL Ammonium transporter OS=Paenibacillus sacheonensis OX=742054 GN=amt PE=3 SV=1
Number of features: 0
Seq('MVKKLILSLGALSLLFPAMAFADDPSAGTLNMGLNSIWVLVAAVLVILMQGGFI...QNM')
ID: tr|A0A7X4YNT4|A0A7X4YNT4_9BACL
Name: tr|A0A7X4YNT4|A0A7X4YNT4_9BACL
Description: tr|A0A7X4YNT4|A0A7X4YNT4_9BACL Ammonium transporter OS=Paenibacillus sacheonensis OX=742054 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDVAALSVGLNTIWVVLTAAMILLMEGGFALLEAGFVRQKNAVSIIMKVFVDIT...SRQ')
ID: tr|A0A8H6MPB9|A0A8H6MPB9_9PEZI
Name: tr|A0A8H6MPB9|A0A8H6MPB9_9PEZI
Description: tr|A0A8H6MPB9|A0A8H6MPB9_9PEZI Ammonium transporter OS=Colletotrichum sojae OX=2175907 GN=CSOJ01_11056 PE=3 SV=1
Number of features: 0
Seq('MSYTHTGAPTEFNGTNADFGGDSTTTNLNQWYQSGDQSYILVSAAMVLLMIPGI...PSL')
ID: tr|A0A8H6NAG3|A0A8H6NAG3_9PEZI
Name: tr|A0A8H6NAG3|A0A8H6NAG3_9PEZI
Description: tr|A0A8H6NAG3|A0A8H6NAG3_9PEZI Ammonium transporter OS=Colletotrichum plurivorum OX=2175906 GN=CPLU01_09822 PE=3 SV=1
Number of features: 0
Seq('MSYTHTGAPTEFNGTNADFGGDSTTTNLNQWYQSGDQSYILVSAAMVLLMIPGI...PSL')
ID: tr|A0A8H6K7L7|A0A8H6K7L7_9PEZI
Name: tr|A0A8H6K7L7|A0A8H6K7L7_9PEZI
Description: tr|A0A8H6K7L7|A0A8H6K7L7_9PEZI Ammonium transporter OS=Colletotrichum musicola OX=2175873 GN=CMUS01_09462 PE=3 SV=1
Number of features: 0
Seq('MSYTHTGAPTEFNGTNADFGGDSTTTNLNQWYQSGDQSYILVSAAMVLLMIPGI...PSL')
ID: tr|D0L8H3|D0L8H3_GORB4
Name: tr|D0L8H3|D0L8H3_GORB4
Description: tr|D0L8H3|D0L8H3_GORB4 Ammonium transporter OS=Gordonia bronchialis (strain ATCC 25592 / DSM 43247 / BCRC 13721 / JCM 3198 / KCTC 3076 / NBRC 16047 / NCTC 10667) OX=526226 GN=Gbro_4808 PE=3 SV=1
Number of features: 0
Seq('MEPVIAANADLAWMLAAFVFVLLMFPGLALYYGGMVGARNILNMMTMVMSTLGI...GHS')

ID: tr|D0LAL7|D0LAL7_GORB4
Name: tr|D0LAL7|D0LAL7_GORB4
Description: tr|D0LAL7|D0LAL7_GORB4 Ammonium transporter OS=Gordonia bronchialis (strain ATCC 25592 / DSM 43247 / BCRC 13721 / JCM 3198 / KCTC 3076 / NBRC 16047 / NCTC 10667) OX=526226 GN=Gbro_2078 PE=3 SV=1
Number of features: 0
Seq('MVSALPESVFGEPDAGNTAWMLASASMVLLMTPALAFFYGGLSRGKSVLNMMMM...ELA')
ID: tr|A0A369M386|A0A369M386_9ACTN
Name: tr|A0A369M386|A0A369M386_9ACTN
Description: tr|A0A369M386|A0A369M386_9ACTN Ammonium transporter OS=Gordonibacter pamelaeae OX=471189 GN=C1877_09420 PE=3 SV=1
Number of features: 0
Seq('MFDTGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMLMSFAVLGIVGVT...GLD')
ID: tr|D6E7B3|D6E7B3_9ACTN
Name: tr|D6E7B3|D6E7B3_9ACTN
Description: tr|D6E7B3|D6E7B3_9ACTN Ammonium transporter OS=Gordonibacter pamelaeae 7-10-1-b OX=657308 GN=GPA_07810 PE=3 SV=1
Number of features: 0
Seq('MFDTGSTGFMLVCAMLVLLMTPGLAFFYGGLSRRKNVVNTMLMSFAVLGIVGVT...GLD')
ID: tr|A0A1L3RLF1|A0A1L3RLF1_9PROT
Name: tr|A0A1L3RLF1|A0A1L3RLF1_9PROT
Description: tr|A0A1L3RLF1|A0A1L3RLF1_9PROT Ammonium transporter OS=Granulibacter bethesdensis OX=364410 GN=GbCGDNIH6_2135 PE=3 SV=1
Number of features: 0
Seq('MCFIGGHQRMKADLPCPENCRAQARLPSRKMGSRKLGLGAAAAALPLFAAMPAW...RLG')
ID: tr|A0A1L3REC0|A0A1L3REC0_9PROT
Name: tr|A0A1L3REC0|A0A1L3REC0_9PROT
Description: tr|A0A1L3REC0|A0A1L3REC0_9PROT Ammonium transporter OS=Granulibacter bethesdensis OX=364410 GN=GbCGDNIH8_2135 PE=3 SV=1
Number of features: 0
Seq('MKTQSSQKSATRRGCKECWPTHARRMCFIGGHQRMKADLPCPENCRAQARLPGR...RLG')
ID: tr|W6I7E0|W6I7E0_9PROT
Name: tr|W6I7E0|W6I7E0_9PROT
Description: tr|W6I7E0|W6I7E0_9PROT Ammonium transporter OS=Granulibacter bethesdensis OX=364410 GN=GbCGDNIH3_2135 PE=3 SV=1
Number of features: 0
Seq('MCFIGGHQRMKADLPCPENCRAQARLPSRKMGSRKLGLGAAAAALPLFAAMPAW...RLG')
ID: tr|Q0BQ69|Q0BQ69_GRABC
Name: tr|Q0BQ69|Q0BQ69_GRABC
Description: tr|Q0BQ69|Q0BQ69_GRABC Ammonium transporter OS=Granulibacter bethesdensis (strain ATCC BAA-1260 / CGDNIH1) OX=391165 GN=GbCGDNIH1_2135 PE=3 SV=1
Number of features: 0
Seq('MCFIGGHQRMKADLPCPENCRAQARLPSRKMGSRKLGLGAAAAALPLFAAMPAW...RLG')
ID: tr|L1IYP4|L1IYP4_GUITC
Name: tr|L1IYP4|L1IYP4_GUITC
Description: tr|L1IYP4|L1IYP4_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_112916 PE=3 SV=1
Number of features: 0
Seq('MPRFLYCVLKYFSVVIFLVSCSAEGQVDWKVKPQSPALRASVEAVKSKEFPNAK...GFI')
ID: tr|L1IYW7|L1IYW7_GUITC
Name: tr|L1IYW7|L1IYW7_GUITC
Description: tr|L1IYW7|L1IYW7_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_112985 PE=3 SV=1
Number of features: 0
Seq('MARVIYHVIMFMIMVGEILSGQIDASNDSFKKIVENQANVIKSLEARISQLEKE...NSH')
ID: tr|A0A7S4NPK3|A0A7S4NPK3_GUITH
Name: tr|A0A7S4NPK3|A0A7S4NPK3_GUITH
Description: tr|A0A7S4NPK3|A0A7S4NPK3_GUITH Ammonium transporter OS=Guillardia theta OX=55529 GN=GTHE00462_LOCUS15751 PE=3 SV=1
Number of features: 0
Seq('MKNLSMPRFLYCVLKYFSVVIFLVSCSAEGQVDWKVKPQSPALRASVEAVKSKE...GFI')
ID: tr|L1IHZ8|L1IHZ8_GUITC
Name: tr|L1IHZ8|L1IHZ8_GUITC
Description: tr|L1IHZ8|L1IHZ8_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_79503 PE=3 SV=1
Number of features: 0
Seq('MDSGDTAWMLTSSAIVLMMTIPGLALFYGGLARTPNVLSTVIQSFAITCLVTFW...ITN')
ID: tr|L1J6I4|L1J6I4_GUITC
Name: tr|L1J6I4|L1J6I4_GUITC
Description: tr|L1J6I4|L1J6I4_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_110337 PE=3 SV=1
Number of features: 0
Seq('MASVNSLASQVQAMSEQVNNISASLLAAQFAIKSQRQQIQELIAAQASNSVIIT...QDE')
ID: tr|L1JEX0|L1JEX0_GUITC
Name: tr|L1JEX0|L1JEX0_GUITC
Description: tr|L1JEX0|L1JEX0_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_106960 PE=4 SV=1
Number of features: 0
Seq('MFVLSSPEAPLHAGASIFCMNIGLVLIEASSLKSSRYERVALRTITSISLAALS...MAE')
ID: tr|L1INN6|L1INN6_GUITC
Name: tr|L1INN6|L1INN6_GUITC
Description: tr|L1INN6|L1INN6_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_158588 PE=3 SV=1
Number of features: 0
Seq('MATMPAPDARNFMGLMKNLEKGFNFTIRYVDQLDAEINTTLVSVGQNSNDLDTA...CSL')
ID: tr|L1IUV5|L1IUV5_GUITC
Name: tr|L1IUV5|L1IUV5_GUITC
Description: tr|L1IUV5|L1IUV5_GUITC Ammonium transporter OS=Guillardia theta (strain CCMP2712) OX=905079 GN=GUITHDRAFT_158372 PE=3 SV=1
Number of features: 0
Seq('MLEQNAKEEGDIAFMLISTALVLMMTIPGLALFYGGLARAPNVLSTVMQSFAIT...NAE')
ID: tr|A0A212AV03|A0A212AV03_9RHOB
Name: tr|A0A212AV03|A0A212AV03_9RHOB
Description: tr|A0A212AV03|A0A212AV03_9RHOB Ammonium transporter OS=Haematobacter missouriensis OX=366616 GN=CDV52_05095 PE=3 SV=1
Number of features: 0
Seq('MKSRNILWGGAATALTALAPALAWAQDATAPAVETVVEAAGPTMDKGDVAWMLV...YHY')
ID: tr|A0A1C6Z081|A0A1C6Z081_HAFAL
Name: tr|A0A1C6Z081|A0A1C6Z081_HAFAL
Description: tr|A0A1C6Z081|A0A1C6Z081_HAFAL Ammonium transporter OS=Hafnia alvei OX=569 GN=BN1044_02030 PE=3 SV=1
Number of features: 0
Seq('MMKTRLSTLALGSALLLPGAAMAATPAVADKADNAFMMICTALVLFMTIPGIGL...YNQ')
ID: tr|A0A377PBY1|A0A377PBY1_HAFAL
Name: tr|A0A377PBY1|A0A377PBY1_HAFAL
Description: tr|A0A377PBY1|A0A377PBY1_HAFAL Ammonium transporter OS=Hafnia alvei OX=569 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKTRLSTLALGSALLLPGAAMAATPAVADKADNAFMMICTALVLFMTIPGIGL...YNQ')
ID: tr|A0A377PLP5|A0A377PLP5_HAFAL
Name: tr|A0A377PLP5|A0A377PLP5_HAFAL
Description: tr|A0A377PLP5|A0A377PLP5_HAFAL Ammonium transporter OS=Hafnia alvei OX=569 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKTRLSTLALGSALLLPSAAMAATPAVADKADNAFMMICTALVLFMTIPGIGL...YNQ')
ID: tr|A0A4Q9EZY8|A0A4Q9EZY8_HAFAL
Name: tr|A0A4Q9EZY8|A0A4Q9EZY8_HAFAL
Description: tr|A0A4Q9EZY8|A0A4Q9EZY8_HAFAL Ammonium transporter OS=Hafnia alvei OX=569 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKTRLSTLALGSALLLPSAAMAATPAVADKADNAFMMICTALVLFMTIPGIGLF...YNQ')
ID: tr|A0A097R891|A0A097R891_HAFAL
Name: tr|A0A097R891|A0A097R891_HAFAL
Description: tr|A0A097R891|A0A097R891_HAFAL Ammonium transporter OS=Hafnia alvei FB1 OX=1453496 GN=AT03_16525 PE=3 SV=1
Number of features: 0
Seq('MKTRLSTLALGSALLLPGAAMAATPAVADKADNAFMMICTALVLFMTIPGIGLF...YNQ')
ID: tr|G9Y5B0|G9Y5B0_HAFAL
Name: tr|G9Y5B0|G9Y5B0_HAFAL
Description: tr|G9Y5B0|G9Y5B0_HAFAL Ammonium transporter OS=Hafnia alvei ATCC 51873 OX=1002364 GN=HMPREF0454_01737 PE=3 SV=1
Number of features: 0
Seq('MKIRLSTLGLGSALLLPGVAMAAAPAVADKADNAFMMICTALVLFMTIPGIGLF...YNQ')
ID: tr|A0A2A2M8K7|A0A2A2M8K7_9GAMM
Name: tr|A0A2A2M8K7|A0A2A2M8K7_9GAMM
Description: tr|A0A2A2M8K7|A0A2A2M8K7_9GAMM Ammonium transporter OS=Hafnia paralvei OX=546367 GN=CJD50_20700 PE=3 SV=1
Number of features: 0
Seq('MKIRLSTLGLGSASLLPGVAMAAAPAVADKADNAFMMICTALVLFMTIPGIGLF...YNQ')
ID: tr|A0A2A2MCP3|A0A2A2MCP3_9GAMM
Name: tr|A0A2A2MCP3|A0A2A2MCP3_9GAMM
Description: tr|A0A2A2MCP3|A0A2A2MCP3_9GAMM Ammonium transporter OS=Hafnia paralvei OX=546367 GN=CJD50_11790 PE=3 SV=1
Number of features: 0
Seq('MSHIAIAFHQIDVGNTAFMLLCTSLVMLMTPGLAFFYGGLVSRKDVLTIMFQSF...ADK')
ID: tr|Q2S8H9|Q2S8H9_HAHCH
Name: tr|Q2S8H9|Q2S8H9_HAHCH
Description: tr|Q2S8H9|Q2S8H9_HAHCH Ammonium transporter OS=Hahella chejuensis (strain KCTC 2396) OX=349521 GN=amt PE=3 SV=1
Number of features: 0
Seq('MENNVFHLQYALDTFYFLVMGALVMWMAAGFAMLESGLVRAKNTTEILTKNVAL...TRD')
ID: tr|Q2SIR0|Q2SIR0_HAHCH
Name: tr|Q2SIR0|Q2SIR0_HAHCH
Description: tr|Q2SIR0|Q2SIR0_HAHCH Ammonia permease OS=Hahella chejuensis (strain KCTC 2396) OX=349521 GN=HCH_02676 PE=3 SV=1
Number of features: 0
Seq('MNDTNNAVETLLQGADTLFILLGAIMVLAMHAGFAFLEVGTVRHKNQVNALVKI...SMD')
ID: tr|E7QV43|E7QV43_HALPU
Name: tr|E7QV43|E7QV43_HALPU
Description: tr|E7QV43|E7QV43_HALPU Ammonium transporter OS=Haladaptatus paucihalophilus DX253 OX=797209 GN=SAMN05444342_3402 PE=3 SV=1
Number of features: 0
Seq('MVDLNAIASGVNSVWVLTVSFLIFFMQPGFAMLEAGQVRAKNVANVLMKNMMDW...ENK')
ID: tr|D8J4C6|D8J4C6_HALJB
Name: tr|D8J4C6|D8J4C6_HALJB
Description: tr|D8J4C6|D8J4C6_HALJB Rh family protein/ammonium transporter OS=Halalkalicoccus jeotgali (strain DSM 18796 / CECT 7217 / JCM 14584 / KCTC 4019 / B3) OX=795797 GN=HacjB3_00475 PE=3 SV=1
Number of features: 0
Seq('MQVDPSVLAEGVNMMWVLVVTFLIFFMHAGFAMLEAGQVRSKNVANQLTKNLLT...EAV')
ID: tr|D0LTW3|D0LTW3_HALO1
Name: tr|D0LTW3|D0LTW3_HALO1
Description: tr|D0LTW3|D0LTW3_HALO1 Ammonium transporter OS=Haliangium ochraceum (strain DSM 14365 / JCM 11303 / SMP-2) OX=502025 GN=Hoch_3305 PE=3 SV=1
Number of features: 0
Seq('MEPNVMVNTLWVLLSGFLVFFMNAGFALVESGLCRSKNTVNILAKNFIVFGLAV...HRD')
ID: tr|A0A3C1KS02|A0A3C1KS02_9GAMM
Name: tr|A0A3C1KS02|A0A3C1KS02_9GAMM
Description: tr|A0A3C1KS02|A0A3C1KS02_9GAMM Ammonium transporter OS=Haliea salexigens OX=287487 GN=DCP75_14880 PE=3 SV=1
Number of features: 0
Seq('MENQIFELQYAMDTFYFLVCGALVMWMAAGFAMLEAGLVRAKNTTEILTKNVAL...AQK')

ID: tr|F4KY49|F4KY49_HALH1
Name: tr|F4KY49|F4KY49_HALH1
Description: tr|F4KY49|F4KY49_HALH1 Ammonium transporter OS=Haliscomenobacter hydrossis (strain ATCC 27775 / DSM 1100 / LMG 10767 / O) OX=760192 GN=Halhy_5851 PE=3 SV=1
Number of features: 0
Seq('MTQLITNKPMATFSFVLLLIISAIASVYPASFPTPAEGVTFDSGNVAWMLVASS...LAM')
ID: tr|I0JI83|I0JI83_HALH3
Name: tr|I0JI83|I0JI83_HALH3
Description: tr|I0JI83|I0JI83_HALH3 Ammonium transporter OS=Halobacillus halophilus (strain ATCC 35676 / DSM 2266 / JCM 20832 / KCTC 3685 / LMG 17431 / NBRC 102448 / NCIMB 2269) OX=866895 GN=HBHAL_1479 PE=3 SV=1
Number of features: 0
Seq('MDATFLMNNLWIVVCTVLVLLMQGGFILLEAGSTRMKNAGHIAGKTVFTIGIVS...PGA')
ID: tr|L0K9M1|L0K9M1_HALHC
Name: tr|L0K9M1|L0K9M1_HALHC
Description: tr|L0K9M1|L0K9M1_HALHC Ammonium transporter OS=Halobacteroides halobius (strain ATCC 35273 / DSM 5150 / MD-1) OX=748449 GN=Halha_0812 PE=3 SV=1
Number of features: 0
Seq('MRSRVVLLTMIIVLSLSTVGWAAEPTAKSNAVAIDTMWTLLAAFLVFFMQAGFA...KSE')
ID: tr|M0MDP9|M0MDP9_9EURY
Name: tr|M0MDP9|M0MDP9_9EURY
Description: tr|M0MDP9|M0MDP9_9EURY Rh family protein/ammonium transporter OS=Halococcus saccharolyticus DSM 5350 OX=1227455 GN=C449_12645 PE=3 SV=1
Number of features: 0
Seq('MIGGAMIPLQAGGMEAVVESVNLVWVLTVTFLIFFMHAGFAMLEAGQVRAKNVA...EAV')
ID: sp|I3R0S7|AMT1_HALMT
Name: sp|I3R0S7|AMT1_HALMT
Description: sp|I3R0S7|AMT1_HALMT Ammonium transporter Amt1 OS=Haloferax mediterranei (strain ATCC 33500 / DSM 1411 / JCM 8866 / NBRC 14739 / NCIMB 2177 / R-4) OX=523841 GN=amt1 PE=1 SV=1
Number of features: 0
Seq('MIPLQVDPNVVAQGVNYVWILVVSFLIFFMQPGFALLEAGQVRAKNVGNVLMKN...ENQ')
ID: sp|I3R635|NASB_HALMT
Name: sp|I3R635|NASB_HALMT
Description: sp|I3R635|NASB_HALMT Probable nitrate transporter OS=Haloferax mediterranei (strain ATCC 33500 / DSM 1411 / JCM 8866 / NBRC 14739 / NCIMB 2177 / R-4) OX=523841 GN=nasB PE=2 SV=1
Number of features: 0
Seq('MGLVKMTRWRTLVLATAAFNLSFLIWFSFAPFTGQIAAEFGLSLTDLGILASAA...SDD')
ID: tr|M0J579|M0J579_HALMT
Name: tr|M0J579|M0J579_HALMT
Description: tr|M0J579|M0J579_HALMT Ammonium transporter OS=Haloferax mediterranei (strain ATCC 33500 / DSM 1411 / JCM 8866 / NBRC 14739 / NCIMB 2177 / R-4) OX=523841 GN=C439_09915 PE=4 SV=1
Number of features: 0
Seq('MQVDPNVVAQGVNYVWILVVSFLIFFMQPGFALLEAGQVRAKNVGNVLMKNMTD...ENQ')
ID: tr|A0A482TED1|A0A482TED1_9EURY
Name: tr|A0A482TED1|A0A482TED1_9EURY
Description: tr|A0A482TED1|A0A482TED1_9EURY Ammonium transporter OS=Halogeometricum borinquense OX=60847 GN=ELS19_14705 PE=4 SV=1
Number of features: 0
Seq('MSVPLQADASTIAAGVNNVWILVVTFLIFFMQPGFALLEAGQVRAKNVGNVLMK...ERE')
ID: tr|E4NS62|E4NS62_HALBP
Name: tr|E4NS62|E4NS62_HALBP
Description: tr|E4NS62|E4NS62_HALBP Ammonium transporter OS=Halogeometricum borinquense (strain ATCC 700274 / DSM 11551 / JCM 10706 / KCTC 4070 / PR3) OX=469382 GN=Hbor_01360 PE=4 SV=1
Number of features: 0
Seq('MSVPLQADASTIAAGVNNVWILVVTFLIFFMQPGFALLEAGQVRAKNVGNVLMK...ERE')
ID: tr|J2ZGN6|J2ZGN6_9EURY
Name: tr|J2ZGN6|J2ZGN6_9EURY
Description: tr|J2ZGN6|J2ZGN6_9EURY Ammonium transporter OS=Halogranum salarium B-1 OX=1210908 GN=HSB1_20130 PE=3 SV=1
Number of features: 0
Seq('MSLASLPLQTGMDAIVTGVNLVWVLTVTFLIFFMHAGFAMLEAGQVRSKNVANQ...KDE')
ID: tr|J3EXK0|J3EXK0_9EURY
Name: tr|J3EXK0|J3EXK0_9EURY
Description: tr|J3EXK0|J3EXK0_9EURY Ammonium transporter OS=Halogranum salarium B-1 OX=1210908 GN=HSB1_20100 PE=4 SV=1
Number of features: 0
Seq('MGLPLQADPATIANGINYVWILVVSFLIFFMQPGFALLEAGQVRAKNVGNVLMK...DDE')
ID: tr|A0A1H6R9C6|A0A1H6R9C6_9EURY
Name: tr|A0A1H6R9C6|A0A1H6R9C6_9EURY
Description: tr|A0A1H6R9C6|A0A1H6R9C6_9EURY Ammonium transporter, Amt family OS=Halohasta litchfieldiae OX=1073996 GN=SAMN05444271_101140 PE=3 SV=1
Number of features: 0
Seq('MSTLLQVDPTEFAAAMNGTWILVVTFLIFFMHAGFAMLEAGQVRSKNVANQLTK...EAI')
ID: tr|A0A847UCB6|A0A847UCB6_9EURY
Name: tr|A0A847UCB6|A0A847UCB6_9EURY
Description: tr|A0A847UCB6|A0A847UCB6_9EURY Ammonium transporter OS=Halomicrobium mukohataei OX=57705 GN=GOC74_04100 PE=3 SV=1
Number of features: 0
Seq('MTYELLQSSPETIVEGVNLLWVLVVTFLIFFMHAGFAMLEAGQVRSKNVANQLT...NDD')
ID: tr|A0A4D6KHD1|A0A4D6KHD1_9EURY
Name: tr|A0A4D6KHD1|A0A4D6KHD1_9EURY
Description: tr|A0A4D6KHD1|A0A4D6KHD1_9EURY Ammonium transporter OS=Halomicrobium mukohataei OX=57705 GN=E5139_07780 PE=3 SV=1
Number of features: 0
Seq('MTYELLQSNPESIVEGVNLLWVLVVTFLIFFMHAGFAMLEAGQVRSKNVANQLT...NDD')
ID: tr|C7P0S0|C7P0S0_HALMD
Name: tr|C7P0S0|C7P0S0_HALMD
Description: tr|C7P0S0|C7P0S0_HALMD Ammonium transporter OS=Halomicrobium mukohataei (strain ATCC 700874 / DSM 12286 / JCM 9738 / NCIMB 13541) OX=485914 GN=Hmuk_0923 PE=3 SV=1
Number of features: 0
Seq('MTYELLQSNPESIVEGVNLLWVLVVTFLIFFMHAGFAMLEAGQVRSKNVANQLT...NDD')
ID: tr|A0A329Q0D7|A0A329Q0D7_HALEL
Name: tr|A0A329Q0D7|A0A329Q0D7_HALEL
Description: tr|A0A329Q0D7|A0A329Q0D7_HALEL Ammonium transporter OS=Halomonas elongata OX=2746 GN=DKQ62_15985 PE=3 SV=1
Number of features: 0
Seq('MTELAYALDTFYFLVCGALVMWMAAGFSMLEAGLVRSKNTAEILTKNIALFAIA...AKK')
ID: tr|E1V4T3|E1V4T3_HALED
Name: tr|E1V4T3|E1V4T3_HALED
Description: tr|E1V4T3|E1V4T3_HALED Ammonium transporter OS=Halomonas elongata (strain ATCC 33173 / DSM 2581 / NBRC 15536 / NCIMB 2198 / 1H9) OX=768066 GN=HELO_1099 PE=3 SV=1
Number of features: 0
Seq('MTELAYALDTFYFLVCGALVMWMAAGFSMLEAGLVRSKNTAEILTKNIALFAIA...AKK')
ID: tr|F8D7H6|F8D7H6_HALXS
Name: tr|F8D7H6|F8D7H6_HALXS
Description: tr|F8D7H6|F8D7H6_HALXS Ammonium transporter OS=Halopiger xanaduensis (strain DSM 18323 / JCM 14033 / SH-6) OX=797210 GN=Halxa_1519 PE=3 SV=1
Number of features: 0
Seq('MEPTVLQTDVEMLTEAINYTWILVATFLIFFMHAGFAMLEAGQVRSKNVANQLT...DAV')
ID: tr|Q18ES8|Q18ES8_HALWD
Name: tr|Q18ES8|Q18ES8_HALWD
Description: tr|Q18ES8|Q18ES8_HALWD Transport protein (Probable substrate ammonium) OS=Haloquadratum walsbyi (strain DSM 16790 / HBSQ001) OX=362976 GN=amtB PE=4 SV=1
Number of features: 0
Seq('MIPLQIDAGAIASGVNNVWILVVCFLIFFMQPGFALLEAGQVRAKNVGNVLMKN...NDE')
ID: tr|G0LFE3|G0LFE3_HALWC
Name: tr|G0LFE3|G0LFE3_HALWC
Description: tr|G0LFE3|G0LFE3_HALWC Transport protein (Probable substrate ammonium) OS=Haloquadratum walsbyi (strain DSM 16854 / JCM 12705 / C23) OX=768065 GN=amtB PE=4 SV=1
Number of features: 0
Seq('MIPLQIDAGAIASGVNNVWILVVCFLIFFMQPGFALLEAGQVRAKNVGNVLMKN...NDE')
ID: tr|U1PPI7|U1PPI7_9EURY
Name: tr|U1PPI7|U1PPI7_9EURY
Description: tr|U1PPI7|U1PPI7_9EURY Ammonia permease OS=Haloquadratum walsbyi J07HQW2 OX=1238425 GN=J07HQW2_02122 PE=4 SV=1
Number of features: 0
Seq('MIPLQIDAGAIASGVNNVWILVVCFLIFFMQPGFALLEAGQVRAKNVGNVLMKN...EQK')
ID: tr|U1PIR6|U1PIR6_9EURY
Name: tr|U1PIR6|U1PIR6_9EURY
Description: tr|U1PIR6|U1PIR6_9EURY Ammonia permease OS=Haloquadratum walsbyi J07HQW1 OX=1238424 GN=J07HQW1_03611 PE=4 SV=1
Number of features: 0
Seq('MIPLQIDAGAIASGVNNVWILVVCFLIFFMQPGFALLEAGQVRAKNVGNVLMKN...DNE')
ID: tr|C7NND6|C7NND6_HALUD
Name: tr|C7NND6|C7NND6_HALUD
Description: tr|C7NND6|C7NND6_HALUD Ammonium transporter OS=Halorhabdus utahensis (strain DSM 12940 / JCM 11049 / AX-2) OX=519442 GN=Huta_1360 PE=3 SV=1
Number of features: 0
Seq('MPVGGEVASGVNTVWALVVAFLIFFMQPGFALLESGQVRAKNVGNVLMKNMTDW...DNE')
ID: tr|C7NND3|C7NND3_HALUD
Name: tr|C7NND3|C7NND3_HALUD
Description: tr|C7NND3|C7NND3_HALUD Rh family protein/ammonium transporter OS=Halorhabdus utahensis (strain DSM 12940 / JCM 11049 / AX-2) OX=519442 GN=Huta_1357 PE=3 SV=1
Number of features: 0
Seq('MIEALPLQVEPSALTDAISNVWVLTVTFLIFFMHAGFAMLEAGQVRAKNVANQL...SDE')
ID: tr|A0A0X8X7Y7|A0A0X8X7Y7_HALHR
Name: tr|A0A0X8X7Y7|A0A0X8X7Y7_HALHR
Description: tr|A0A0X8X7Y7|A0A0X8X7Y7_HALHR Ammonium transporter OS=Halorhodospira halochloris OX=1052 GN=HH1059_25470 PE=3 SV=1
Number of features: 0
Seq('MEDVMEMAYALDTFYLLLSGALVMWMAAGFTMLEAGMVRAKNTTEILTKNVGLY...RSK')
ID: tr|W8KM07|W8KM07_9GAMM
Name: tr|W8KM07|W8KM07_9GAMM
Description: tr|W8KM07|W8KM07_9GAMM Ammonium transporter OS=Ectothiorhodospira haloalkaliphila OX=421628 GN=M911_14620 PE=3 SV=1
Number of features: 0
Seq('MENQVIEVAYGLDTFYFLVSGALVMWMAAGFTMLEAGLVRSKSTVEILTKNIAL...GRK')
ID: tr|B9LU00|B9LU00_HALLT
Name: tr|B9LU00|B9LU00_HALLT
Description: tr|B9LU00|B9LU00_HALLT Rh family protein/ammonium transporter OS=Halorubrum lacusprofundi (strain ATCC 49239 / DSM 5036 / JCM 8891 / ACAM 34) OX=416348 GN=Hlac_2623 PE=3 SV=1
Number of features: 0
Seq('MTTGVLASIDPSVLAEGVNLMWVAMVCFLIFFMHAGFAMLEAGQVRAKNVANQL...GAV')
ID: tr|M0D3Q9|M0D3Q9_9EURY
Name: tr|M0D3Q9|M0D3Q9_9EURY
Description: tr|M0D3Q9|M0D3Q9_9EURY Ammonium transporter OS=Halosimplex carlsbadense 2-9-1 OX=797114 GN=C475_03909 PE=3 SV=1
Number of features: 0
Seq('MLELTALQTETQTLIDAINTTWVLVVTFLIFFMHAGFAMLEAGQVRSKNVSNQL...RSD')

ID: tr|M0D580|M0D580_9EURY
Name: tr|M0D580|M0D580_9EURY
Description: tr|M0D580|M0D580_9EURY Ammonium transport protein OS=Halosimplex carlsbadense 2-9-1 OX=797114 GN=C475_03894 PE=4 SV=1
Number of features: 0
Seq('MTALLAPAADALLQLDPTQVANGVNNVWVLVVCFLIFFMQPGFALLESGQVRAK...SDE')
ID: tr|W0JIB3|W0JIB3_9EURY
Name: tr|W0JIB3|W0JIB3_9EURY
Description: tr|W0JIB3|W0JIB3_9EURY Ammonium transporter OS=Halostagnicola larsenii XH-48 OX=797299 GN=HALLA_04985 PE=3 SV=1
Number of features: 0
Seq('MEAAPLQADPEVVAEGINLVWVLMATFLIFFMHAGFAMLEAGQVRSKNVANQLT...DAV')
ID: tr|A0A172YCA7|A0A172YCA7_9GAMM
Name: tr|A0A172YCA7|A0A172YCA7_9GAMM
Description: tr|A0A172YCA7|A0A172YCA7_9GAMM Ammonium transporter OS=Halotalea alkalilenta OX=376489 GN=A5892_04720 PE=3 SV=1
Number of features: 0
Seq('MSARSALIPAAGLFGVLPLSAFAQEAPPVADSGDTAWMLVSTVLVLMMTIPGLA...YNL')
ID: tr|A0A172YBR4|A0A172YBR4_9GAMM
Name: tr|A0A172YBR4|A0A172YBR4_9GAMM
Description: tr|A0A172YBR4|A0A172YBR4_9GAMM Ammonium transporter OS=Halotalea alkalilenta OX=376489 GN=A5892_03770 PE=3 SV=1
Number of features: 0
Seq('MNEAADLANQVTEIAYAIDTFYFLICGVLVMWMAGGFAMLEAGLVRAKNTTEIL...SSK')
ID: tr|D2RU19|D2RU19_HALTV
Name: tr|D2RU19|D2RU19_HALTV
Description: tr|D2RU19|D2RU19_HALTV Ammonium transporter OS=Haloterrigena turkmenica (strain ATCC 51198 / DSM 5511 / JCM 9101 / NCIMB 13204 / VKM B-1734 / 4k) OX=543526 GN=Htur_0187 PE=3 SV=1
Number of features: 0
Seq('MEPTLLQSETEIEMLMEAVNYTWILVATFLIFFMHAGFAMLEAGQVRSKNVANQ...DAV')
ID: tr|D0KXQ0|D0KXQ0_HALNC
Name: tr|D0KXQ0|D0KXQ0_HALNC
Description: tr|D0KXQ0|D0KXQ0_HALNC Ammonium transporter OS=Halothiobacillus neapolitanus (strain ATCC 23641 / c2) OX=555778 GN=Hneap_0360 PE=3 SV=1
Number of features: 0
Seq('METASLVSAVDVLFVLSGAIMVLAMHAGFAFLEVGTVRRKNQVNALAKIMADFA...KYD')
ID: tr|Q45HK8|Q45HK8_HERSE
Name: tr|Q45HK8|Q45HK8_HERSE
Description: tr|Q45HK8|Q45HK8_HERSE Ammonium transporter OS=Herbaspirillum seropedicae OX=964 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSMKKMFSGALAIGALLFAVSFTAPAQAQDAPKPEAAAAAAAAPAAAPAAPKAE...AYH')
ID: tr|D8ITX4|D8ITX4_HERSS
Name: tr|D8ITX4|D8ITX4_HERSS
Description: tr|D8ITX4|D8ITX4_HERSS Ammonium transporter OS=Herbaspirillum seropedicae (strain SmR1) OX=757424 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSMKKMFSGALAIGALLFAVSFTAPAQAQDAPKPEAAAAAAAAPAAAPAAPKAE...AYH')
ID: tr|A0A6M3ZJI1|A0A6M3ZJI1_9BURK
Name: tr|A0A6M3ZJI1|A0A6M3ZJI1_9BURK
Description: tr|A0A6M3ZJI1|A0A6M3ZJI1_9BURK Ammonium transporter OS=Herbaspirillum rubrisubalbicans Os34 OX=1235827 GN=C798_00685 PE=3 SV=1
Number of features: 0
Seq('MSMKKMFSGALAIGALLLAVGFTAPAQAQDAPKPEAAAATAAAPAAAAPAAPKA...AYH')
ID: tr|A0A5B8DZA7|A0A5B8DZA7_HERSE
Name: tr|A0A5B8DZA7|A0A5B8DZA7_HERSE
Description: tr|A0A5B8DZA7|A0A5B8DZA7_HERSE Ammonium transporter OS=Herbaspirillum seropedicae OX=964 GN=EJD96_03150 PE=3 SV=1
Number of features: 0
Seq('MDDHKNGADALFILLGAIMILAMHAGFAFLELGTVRKKNQVNALVKILADFAVS...TSW')
ID: tr|A0A6M3ZKU5|A0A6M3ZKU5_9BURK
Name: tr|A0A6M3ZKU5|A0A6M3ZKU5_9BURK
Description: tr|A0A6M3ZKU5|A0A6M3ZKU5_9BURK Ammonium transporter OS=Herbaspirillum rubrisubalbicans Os34 OX=1235827 GN=C798_03065 PE=3 SV=1
Number of features: 0
Seq('MDDHKNGADALFILLGAIMILAMHAGFAFLELGTVRKKNQVNALVKILADFAVS...TSW')
ID: tr|A4G1J2|A4G1J2_HERAR
Name: tr|A4G1J2|A4G1J2_HERAR
Description: tr|A4G1J2|A4G1J2_HERAR Ammonium transporter OS=Herminiimonas arsenicoxydans OX=204773 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSIKKIFASALATGALLVAVGFAAPAIAEEAATAPAASATVAAPAPAATTEAPA...YHS')
ID: tr|A9B874|A9B874_HERA2
Name: tr|A9B874|A9B874_HERA2
Description: tr|A9B874|A9B874_HERA2 Ammonium transporter OS=Herpetosiphon aurantiacus (strain ATCC 23779 / DSM 785 / 114-95) OX=316274 GN=Haur_3791 PE=3 SV=1
Number of features: 0
Seq('MFRRRRWIVPAAVASLAIPTATFAQEAAPVATETITTQIDIIWLLIAAVLVFFM...STK')
ID: tr|A9AUR8|A9AUR8_HERA2
Name: tr|A9AUR8|A9AUR8_HERA2
Description: tr|A9AUR8|A9AUR8_HERA2 Ammonium transporter OS=Herpetosiphon aurantiacus (strain ATCC 23779 / DSM 785 / 114-95) OX=316274 GN=Haur_1952 PE=3 SV=1
Number of features: 0
Seq('MDMINGADTVWVLLSAALVMLMTPALGLFYGGMVRQKNVLSTLMHSFFMLALIS...MGI')
ID: tr|C6XKC2|C6XKC2_HIRBI
Name: tr|C6XKC2|C6XKC2_HIRBI
Description: tr|C6XKC2|C6XKC2_HIRBI Ammonium transporter OS=Hirschia baltica (strain ATCC 49814 / DSM 5838 / IFAM 1418) OX=582402 GN=Hbal_0018 PE=3 SV=1
Number of features: 0
Seq('MRSGMTGKLAGAATLAAITCGVAAFAQEAEVPSASDVSAYVDNTYLFLLGGLVV...FTK')
ID: tr|B0UT87|B0UT87_HISS2
Name: tr|B0UT87|B0UT87_HISS2
Description: tr|B0UT87|B0UT87_HISS2 Ammonium transporter OS=Histophilus somni (strain 2336) OX=228400 GN=HSM_1006 PE=3 SV=1
Number of features: 0
Seq('MIFYFIDVVIMKKFILLGLLLSFSSSSIAELSDWIKPISDISSGDTAWVMISAI...RIE')
ID: tr|Q0I445|Q0I445_HISS1
Name: tr|Q0I445|Q0I445_HISS1
Description: tr|Q0I445|Q0I445_HISS1 Ammonium transporter OS=Histophilus somni (strain 129Pt) OX=205914 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKFILLGLLLSFSSSSIAELSDWIKPISDISSGDTAWVMISAILVLFMTIPGL...RIE')
ID: sp|Q9H310|RHBG_HUMAN
Name: sp|Q9H310|RHBG_HUMAN
Description: sp|Q9H310|RHBG_HUMAN Ammonium transporter Rh type B OS=Homo sapiens OX=9606 GN=RHBG PE=1 SV=3
Number of features: 0
Seq('MAGSPSRAAGRRLQLPLLCLFLQGATAVLFAVFVRYNHKTDAALWHRSNHSNAD...TQA')
ID: sp|Q9UBD6|RHCG_HUMAN
Name: sp|Q9UBD6|RHCG_HUMAN
Description: sp|Q9UBD6|RHCG_HUMAN Ammonium transporter Rh type C OS=Homo sapiens OX=9606 GN=RHCG PE=1 SV=1
Number of features: 0
Seq('MAWNTNLRWRLPLTCLLLQVIMVILFGVFVRYDFEADAHWWSERTHKNLSDMEN...LVP')
ID: sp|Q02094|RHAG_HUMAN
Name: sp|Q02094|RHAG_HUMAN
Description: sp|Q02094|RHAG_HUMAN Ammonium transporter Rh type A OS=Homo sapiens OX=9606 GN=RHAG PE=1 SV=2
Number of features: 0
Seq('MRFTFPLMAIVLEIAMIVLFGLFVEYETDQTVLEQLNITKPTDMGIFFELYPLF...KTR')
ID: sp|Q02161|RHD_HUMAN
Name: sp|Q02161|RHD_HUMAN
Description: sp|Q02161|RHD_HUMAN Blood group Rh(D) polypeptide OS=Homo sapiens OX=9606 GN=RHD PE=1 SV=3
Number of features: 0
Seq('MSSKYPRSVRRCLPLWALTLEAALILLFYFFTHYDASLEDQKGLVASYQVGQDL...VGF')
ID: sp|P18577|RHCE_HUMAN
Name: sp|P18577|RHCE_HUMAN
Description: sp|P18577|RHCE_HUMAN Blood group Rh(CE) polypeptide OS=Homo sapiens OX=9606 GN=RHCE PE=1 SV=2
Number of features: 0
Seq('MSSKYPRSVRRCLPLWALTLEAALILLFYFFTHYDASLEDQKGLVASYQVGQDL...VGF')
ID: sp|Q15849|UT2_HUMAN
Name: sp|Q15849|UT2_HUMAN
Description: sp|Q15849|UT2_HUMAN Urea transporter 2 OS=Homo sapiens OX=9606 GN=SLC14A2 PE=1 SV=3
Number of features: 0
Seq('MSDPHSSPLLPEPLSSRYKLYEAEFTSPSWPSTSPDTHPALPLLEMPEEKDLRS...DVS')
ID: sp|Q9Y666|S12A7_HUMAN
Name: sp|Q9Y666|S12A7_HUMAN
Description: sp|Q9Y666|S12A7_HUMAN Solute carrier family 12 member 7 OS=Homo sapiens OX=9606 GN=SLC12A7 PE=1 SV=3
Number of features: 0
Seq('MPTNFTVVPVEAHADGGGDETAERTEAPGTPEGPEPERPSPGDGNPRENSPFLN...IYS')
ID: sp|P55011|S12A2_HUMAN
Name: sp|P55011|S12A2_HUMAN
Description: sp|P55011|S12A2_HUMAN Solute carrier family 12 member 2 OS=Homo sapiens OX=9606 GN=SLC12A2 PE=1 SV=1
Number of features: 0
Seq('MEPRPTAPSSGAPGLAGVGETPSAAALAAARVELPGTAVPSVPEDAAPASRDGG...FYS')
ID: sp|Q9UP95|S12A4_HUMAN
Name: sp|Q9UP95|S12A4_HUMAN
Description: sp|Q9UP95|S12A4_HUMAN Solute carrier family 12 member 4 OS=Homo sapiens OX=9606 GN=SLC12A4 PE=1 SV=2
Number of features: 0
Seq('MPHFTVVPVDGPRRGDYDNLEGLSWVDYGERAELDDSDGHGNHRESSPFLSPLE...IYS')
ID: sp|Q9H015|S22A4_HUMAN
Name: sp|Q9H015|S22A4_HUMAN
Description: sp|Q9H015|S22A4_HUMAN Solute carrier family 22 member 4 OS=Homo sapiens OX=9606 GN=SLC22A4 PE=1 SV=3
Number of features: 0
Seq('MRDYDEVIAFLGEWGPFQRLIFFLLSASIIPNGFNGMSVVFLAGTPEHRCRVPD...TAF')
ID: sp|Q7LBE3|S26A9_HUMAN
Name: sp|Q7LBE3|S26A9_HUMAN
Description: sp|Q7LBE3|S26A9_HUMAN Solute carrier family 26 member 9 OS=Homo sapiens OX=9606 GN=SLC26A9 PE=1 SV=1
Number of features: 0
Seq('MSQPRPRYVVDRAAYSLTLFDDEFEKKDRTYPVGEKLRNAFRCSSAKIKAVVFG...TAL')
ID: sp|Q9UHW9|S12A6_HUMAN
Name: sp|Q9UHW9|S12A6_HUMAN
Description: sp|Q9UHW9|S12A6_HUMAN Solute carrier family 12 member 6 OS=Homo sapiens OX=9606 GN=SLC12A6 PE=1 SV=2
Number of features: 0
Seq('MHPPETTTKMASVRFMVTPTKIDDIPGLSDTSPDLSSRSSSRVRFSSRESVPET...IYS')
ID: sp|Q9H2X9|S12A5_HUMAN
Name: sp|Q9H2X9|S12A5_HUMAN
Description: sp|Q9H2X9|S12A5_HUMAN Solute carrier family 12 member 5 OS=Homo sapiens OX=9606 GN=SLC12A5 PE=1 SV=3
Number of features: 0
Seq('MSRRFTVTSLPPAGPARSPDPESRRHSVADPRHLPGEDVKGDGNPKESSPFINS...IYS')
ID: tr|I8TC71|I8TC71_9GAMM
Name: tr|I8TC71|I8TC71_9GAMM
Description: tr|I8TC71|I8TC71_9GAMM Ammonium transporter OS=Hydrocarboniphaga effusa AP103 OX=1172194 GN=WQQ_16270 PE=3 SV=1
Number of features: 0
Seq('MIRKFVLALMLAASCGSATVWAQDEAPAAATEAPAAEAAAPAETPAAEAAPAAE...YIL')
ID: tr|I7ZHW3|I7ZHW3_9GAMM
Name: tr|I7ZHW3|I7ZHW3_9GAMM
Description: tr|I7ZHW3|I7ZHW3_9GAMM Ammonium transporter OS=Hydrocarboniphaga effusa AP103 OX=1172194 GN=WQQ_16260 PE=3 SV=1
Number of features: 0
Seq('MPNRLLSLLALILCLASGLSFAQEPASSPSPAAAAEVPAAAATPAIETPAAPAT...YNP')

ID: tr|D3DJN2|D3DJN2_HYDTT
Name: tr|D3DJN2|D3DJN2_HYDTT
Description: tr|D3DJN2|D3DJN2_HYDTT Ammonium transporter OS=Hydrogenobacter thermophilus (strain DSM 6534 / IAM 12695 / TK-6) OX=608538 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MRRVAGIIPLLLVHLSFAQEQAPKLDTGDTAWMLISTALVMLMTLPGLALFYGG...NIT')
ID: tr|A0A066ZTE4|A0A066ZTE4_HYDMR
Name: tr|A0A066ZTE4|A0A066ZTE4_HYDMR
Description: tr|A0A066ZTE4|A0A066ZTE4_HYDMR Ammonium transporter OS=Hydrogenovibrio marinus OX=28885 GN=EI16_04435 PE=3 SV=1
Number of features: 0
Seq('MEQLIQTNYALDTFYFLVTGALVMWMAAGFAMLEAGLVRAKNTTEILAKNVGLF...FTK')
ID: tr|A0A066ZRQ5|A0A066ZRQ5_HYDMR
Name: tr|A0A066ZRQ5|A0A066ZRQ5_HYDMR
Description: tr|A0A066ZRQ5|A0A066ZRQ5_HYDMR Ammonium transporter OS=Hydrogenovibrio marinus OX=28885 GN=EI16_09530 PE=3 SV=1
Number of features: 0
Seq('MSEQPVDILWVLFSAVLVAIMQPGFTALEAGATRTKNSISTAIKNFSDFLIAFM...VVA')
ID: tr|A0A4P6UIK6|A0A4P6UIK6_9BURK
Name: tr|A0A4P6UIK6|A0A4P6UIK6_9BURK
Description: tr|A0A4P6UIK6|A0A4P6UIK6_9BURK Ammonium transporter OS=Hylemonella gracilis OX=80880 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKLLLSLIVGLGLLAGSVSWAQTAPAAEAAPAAAAPAAAAPAAAEAAPAPSAN...YNR')
ID: tr|F3KUN4|F3KUN4_9BURK
Name: tr|F3KUN4|F3KUN4_9BURK
Description: tr|F3KUN4|F3KUN4_9BURK Ammonium transporter OS=Hylemonella gracilis ATCC 19624 OX=887062 GN=HGR_10842 PE=3 SV=1
Number of features: 0
Seq('MKKLLLSLVVGLGLLAGSVSWAQTAPAAEAAPAAAAPAAAAPAAAEAAPAPTAN...YNR')
ID: tr|A0A016XCG9|A0A016XCG9_9BURK
Name: tr|A0A016XCG9|A0A016XCG9_9BURK
Description: tr|A0A016XCG9|A0A016XCG9_9BURK Ammonium transporter OS=Hylemonella gracilis str. Niagara R OX=1458275 GN=AZ34_01095 PE=3 SV=1
Number of features: 0
Seq('MKKLLLSLVVGLGLLAGSASWAQTAPAAEAAPAAAAAPAAAEPAAAAAPAPTVN...YNR')
ID: tr|A0A4P6UIJ8|A0A4P6UIJ8_9BURK
Name: tr|A0A4P6UIJ8|A0A4P6UIJ8_9BURK
Description: tr|A0A4P6UIJ8|A0A4P6UIJ8_9BURK Ammonium transporter OS=Hylemonella gracilis OX=80880 GN=DW355_03115 PE=3 SV=1
Number of features: 0
Seq('MSIELAWLLLCAALVIFMTPGLAFFYGGLVKSKSVVSMMMLSFGSIIVVAILYV...YGI')
ID: tr|A0A016XDZ5|A0A016XDZ5_9BURK
Name: tr|A0A016XDZ5|A0A016XDZ5_9BURK
Description: tr|A0A016XDZ5|A0A016XDZ5_9BURK Ammonium transporter OS=Hylemonella gracilis str. Niagara R OX=1458275 GN=AZ34_01110 PE=3 SV=1
Number of features: 0
Seq('MSIELAWLLLCAALVIFMTPGLAFFYGGLVKSKSVVSMMMLSFGSIIVVAILYV...YGI')
ID: tr|A0A0D2NYP3|A0A0D2NYP3_HYPSF
Name: tr|A0A0D2NYP3|A0A0D2NYP3_HYPSF
Description: tr|A0A0D2NYP3|A0A0D2NYP3_HYPSF Ammonium transporter OS=Hypholoma sublateritium (strain FD-334 SS-4) OX=945553 GN=HYPSUDRAFT_187349 PE=3 SV=1
Number of features: 0
Seq('MVNVTYDASGDLIAYTPDGAPVVYNLGDISFVVLSMALVWIMIPGVGLFYSGLL...EKV')
ID: tr|A0A0D2LEF5|A0A0D2LEF5_HYPSF
Name: tr|A0A0D2LEF5|A0A0D2LEF5_HYPSF
Description: tr|A0A0D2LEF5|A0A0D2LEF5_HYPSF Ammonium transporter OS=Hypholoma sublateritium (strain FD-334 SS-4) OX=945553 GN=HYPSUDRAFT_75862 PE=3 SV=1
Number of features: 0
Seq('MDAGDALTPSSGRVMARVSQYDRGDLAFITVAGAMVFFMVPGLAFLYSGLSRRK...PPQ')
ID: tr|A0A0D2KGN8|A0A0D2KGN8_HYPSF
Name: tr|A0A0D2KGN8|A0A0D2KGN8_HYPSF
Description: tr|A0A0D2KGN8|A0A0D2KGN8_HYPSF Ammonium transporter OS=Hypholoma sublateritium (strain FD-334 SS-4) OX=945553 GN=HYPSUDRAFT_81061 PE=3 SV=1
Number of features: 0
Seq('MVNVTYDGSGSLEWFDTDVSPPTEVVYNPGDIAWVLASTALVWIMVPGVGFFYS...GSS')
ID: tr|V5SAJ5|V5SAJ5_9HYPH
Name: tr|V5SAJ5|V5SAJ5_9HYPH
Description: tr|V5SAJ5|V5SAJ5_9HYPH Ammonium transporter OS=Hyphomicrobium nitrativorans NL23 OX=1029756 GN=W911_02075 PE=3 SV=1
Number of features: 0
Seq('MKESLFSRSTLALAAGLALTLVAGPGFAQEVIAPAAPAAAAAAEPALSAGDTAW...VVH')
ID: tr|Q0BWD0|Q0BWD0_HYPNA
Name: tr|Q0BWD0|Q0BWD0_HYPNA
Description: tr|Q0BWD0|Q0BWD0_HYPNA Ammonium transporter family protein OS=Hyphomonas neptunium (strain ATCC 15444) OX=228405 GN=HNE_3542 PE=3 SV=1
Number of features: 0
Seq('MGQLIGRWIRGATLAPLALLTAGMAFAQEDDVATRLAALEEAVGGSASAYVDNS...SNR')
ID: tr|Q5QVH2|Q5QVH2_IDILO
Name: tr|Q5QVH2|Q5QVH2_IDILO
Description: tr|Q5QVH2|Q5QVH2_IDILO Ammonia permease OS=Idiomarina loihiensis (strain ATCC BAA-735 / DSM 15497 / L2-TR) OX=283942 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEAQNLQQLTFAVDTLYLLISGALVMWMAAGFSMLEAGLVRSKNTTEILTKNIV...KDG')
ID: tr|E3H8C9|E3H8C9_ILYPC
Name: tr|E3H8C9|E3H8C9_ILYPC
Description: tr|E3H8C9|E3H8C9_ILYPC Ammonium transporter OS=Ilyobacter polytropus (strain ATCC 51220 / DSM 2926 / LMG 16218 / CuHBu1) OX=572544 GN=Ilyop_0913 PE=3 SV=1
Number of features: 0
Seq('MKKMKWKAIVLCLMLTMGLSAFAEVGAEEVQTNLNWTWTLIAAAMVFFMQAGFA...LFK')
ID: tr|E3H8A6|E3H8A6_ILYPC
Name: tr|E3H8A6|E3H8A6_ILYPC
Description: tr|E3H8A6|E3H8A6_ILYPC Ammonium transporter OS=Ilyobacter polytropus (strain ATCC 51220 / DSM 2926 / LMG 16218 / CuHBu1) OX=572544 GN=Ilyop_0887 PE=3 SV=1
Number of features: 0
Seq('MKKMSFLGKLGVISLICPTLLFASSDIQTNLNIVWLGIAGAMVMFMQVGFIALE...LFK')
ID: tr|I0WJ97|I0WJ97_9FLAO
Name: tr|I0WJ97|I0WJ97_9FLAO
Description: tr|I0WJ97|I0WJ97_9FLAO Ammonium transporter OS=Imtechella halotolerans K1 OX=946077 GN=W5A_00530 PE=3 SV=1
Number of features: 0
Seq('MICTGLVFFMHLGFSFLEIGLTRQKNTINILFKNLFIICIGLLLYSLVGFNLMY...NQH')
ID: tr|A0A211ZGL5|A0A211ZGL5_9PROT
Name: tr|A0A211ZGL5|A0A211ZGL5_9PROT
Description: tr|A0A211ZGL5|A0A211ZGL5_9PROT Ammonium transporter OS=Inquilinus limosus OX=171674 GN=BWR60_24760 PE=3 SV=1
Number of features: 0
Seq('MKRTFWGLGGAVSALLMALPAMAQDAAPTLNSGDTAWMQTSTALVLMMTIPGLA...AVQ')
ID: tr|A0A952FNL7|A0A952FNL7_9PROT
Name: tr|A0A952FNL7|A0A952FNL7_9PROT
Description: tr|A0A952FNL7|A0A952FNL7_9PROT Ammonium transporter OS=Inquilinus limosus OX=171674 GN=JF625_10400 PE=3 SV=1
Number of features: 0
Seq('MKRTFWGLGGVCAALLTALPAWAQDAAAAPTLNSGDTAWMLTSSALVLMMTIPG...AVQ')
ID: tr|A0A0A0D6K5|A0A0A0D6K5_9PROT
Name: tr|A0A0A0D6K5|A0A0A0D6K5_9PROT
Description: tr|A0A0A0D6K5|A0A0A0D6K5_9PROT Ammonium transporter OS=Inquilinus limosus MP06 OX=1398085 GN=P409_15580 PE=3 SV=1
Number of features: 0
Seq('MKRTFWGLGGAVSALLMALPAMAQDAAAAPTLNSGDTAWMQTSTALVLMMTIPG...AVQ')
ID: tr|E6SF19|E6SF19_INTC7
Name: tr|E6SF19|E6SF19_INTC7
Description: tr|E6SF19|E6SF19_INTC7 Ammonium transporter OS=Intrasporangium calvum (strain ATCC 23552 / DSM 43043 / JCM 3097 / NBRC 12989 / 7 KIP) OX=710696 GN=Intca_2299 PE=3 SV=1
Number of features: 0
Seq('MTTALVPLAAEAPEINEAATAFMLIASAMVLLMTPGLALFYGGMTRAKSVLNMM...AHA')
ID: tr|F6FRU9|F6FRU9_ISOV2
Name: tr|F6FRU9|F6FRU9_ISOV2
Description: tr|F6FRU9|F6FRU9_ISOV2 Ammonium transporter OS=Isoptericola variabilis (strain 225) OX=743718 GN=Isova_1181 PE=3 SV=1
Number of features: 0
Seq('MELDTGVTAWMLTSASLVLLMTPGLALFYGGMVRGKSVLNMMMMSFGAMAVVGV...VRA')
ID: tr|B7QKQ6|B7QKQ6_IXOSC
Name: tr|B7QKQ6|B7QKQ6_IXOSC
Description: tr|B7QKQ6|B7QKQ6_IXOSC Ammonium transporter OS=Ixodes scapularis OX=6945 GN=IscW_ISCW023492 PE=3 SV=1
Number of features: 0
Seq('MANSLDVTTVNPTFLPDEEDFTYDDATWVLTAAIVIFTMQTGFGLLESGCVSQK...VLL')
ID: tr|B7Q7U2|B7Q7U2_IXOSC
Name: tr|B7Q7U2|B7Q7U2_IXOSC
Description: tr|B7Q7U2|B7Q7U2_IXOSC Ammonium transporter (Fragment) OS=Ixodes scapularis OX=6945 GN=IscW_ISCW024688 PE=3 SV=1
Number of features: 0
Seq('DSIMNNADLSWMLVSTLLVLMMAAPGLALFYSGMVRQKNALSMLSQTLLVFSLG...YQH')
ID: tr|C7R314|C7R314_JONDD
Name: tr|C7R314|C7R314_JONDD
Description: tr|C7R314|C7R314_JONDD Ammonium transporter OS=Jonesia denitrificans (strain ATCC 14870 / DSM 20603 / BCRC 15368 / CIP 55.134 / JCM 11481 / NBRC 15587 / NCTC 10816 / Prevot 55134) OX=471856 GN=Jden_0980 PE=3 SV=1
Number of features: 0
Seq('MIDSGMTAWMLISASLVLLMTPGLAFFYGGMVRGKSVLNMLMMSFGAMGVIGIL...VKP')
ID: tr|I3C0V3|I3C0V3_9FLAO
Name: tr|I3C0V3|I3C0V3_9FLAO
Description: tr|I3C0V3|I3C0V3_9FLAO Ammonium transporter OS=Joostella marina DSM 19592 OX=926559 GN=JoomaDRAFT_0186 PE=3 SV=1
Number of features: 0
Seq('METNVIEVNAVLDIMWIMIAGILVFFMQAGFTLVESGFTRSKNVINIVMKNFVD...IDR')
ID: tr|A0A7W4TJ72|A0A7W4TJ72_KINRA
Name: tr|A0A7W4TJ72|A0A7W4TJ72_KINRA
Description: tr|A0A7W4TJ72|A0A7W4TJ72_KINRA Ammonium transporter OS=Kineococcus radiotolerans OX=131568 GN=FHR75_000707 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAWVLTSAALVLLMTPGLALFYGGMVRAKSVLNMMMMSFGAMALIGVLW...VNA')
ID: tr|A6W7U2|A6W7U2_KINRD
Name: tr|A6W7U2|A6W7U2_KINRD
Description: tr|A6W7U2|A6W7U2_KINRD Ammonium transporter OS=Kineococcus radiotolerans (strain ATCC BAA-149 / DSM 14245 / SRS30216) OX=266940 GN=Krad_1393 PE=3 SV=1
Number of features: 0
Seq('MDTGDTAWVLTSAALVLLMTPGLALFYGGMVRAKSVLNMMMMSFGAMALIGVLW...VNA')

ID: tr|K6W5X0|K6W5X0_9MICO
Name: tr|K6W5X0|K6W5X0_9MICO
Description: tr|K6W5X0|K6W5X0_9MICO Ammonium transporter OS=Kineosphaera limosa NBRC 100340 OX=1184609 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MEINSGDTAWVLTSAALVMFMTPGVAFFYGGMVRAKAVLNMMMMCFGAMATIGV...VSS')
ID: tr|E4NAC1|E4NAC1_KITSK
Name: tr|E4NAC1|E4NAC1_KITSK
Description: tr|E4NAC1|E4NAC1_KITSK Ammonium transporter OS=Kitasatospora setae (strain ATCC 33774 / DSM 43861 / JCM 3304 / KCC A-0304 / NBRC 14216 / KM-6054) OX=452652 GN=amtB2 PE=3 SV=1
Number of features: 0
Seq('MLLADTPPTLDSGDTAWLLACTALVLLMTPGLALFYGGMVRTKSVLNMIMMSFV...RTV')
ID: tr|E4NHH7|E4NHH7_KITSK
Name: tr|E4NHH7|E4NHH7_KITSK
Description: tr|E4NHH7|E4NHH7_KITSK Ammonium transporter OS=Kitasatospora setae (strain ATCC 33774 / DSM 43861 / JCM 3304 / KCC A-0304 / NBRC 14216 / KM-6054) OX=452652 GN=amtB1 PE=3 SV=1
Number of features: 0
Seq('MPDGFSAGDTAFVFICAALVMLMTPGLAFFYGGMVRVKSTLNMLVMSFISLAIV...DAR')
ID: tr|E4N1T5|E4N1T5_KITSK
Name: tr|E4N1T5|E4N1T5_KITSK
Description: tr|E4N1T5|E4N1T5_KITSK Ammonium transporter OS=Kitasatospora setae (strain ATCC 33774 / DSM 43861 / JCM 3304 / KCC A-0304 / NBRC 14216 / KM-6054) OX=452652 GN=KSE_63600 PE=3 SV=1
Number of features: 0
Seq('MPPAYNAGDTAWLLASTAMVLLMTPGLAFFYGGMVRLKHVLMMIKMSFAALALG...DGS')
ID: tr|A0A318FY98|A0A318FY98_KLEOX
Name: tr|A0A318FY98|A0A318FY98_KLEOX
Description: tr|A0A318FY98|A0A318FY98_KLEOX Ammonium transporter OS=Klebsiella oxytoca OX=571 GN=DET57_10676 PE=3 SV=1
Number of features: 0
Seq('MKIATMKTGLGALALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A6B8N021|A0A6B8N021_KLEOX
Name: tr|A0A6B8N021|A0A6B8N021_KLEOX
Description: tr|A0A6B8N021|A0A6B8N021_KLEOX Ammonium transporter OS=Klebsiella oxytoca OX=571 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKTGLGALALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFYGGLIR...YNA')
ID: tr|A0A168EVK8|A0A168EVK8_KLEOX
Name: tr|A0A168EVK8|A0A168EVK8_KLEOX
Description: tr|A0A168EVK8|A0A168EVK8_KLEOX Ammonium transporter OS=Klebsiella oxytoca OX=571 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATMKTGLGALALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A0H3H4I7|A0A0H3H4I7_KLEOK
Name: tr|A0A0H3H4I7|A0A0H3H4I7_KLEOK
Description: tr|A0A0H3H4I7|A0A0H3H4I7_KLEOK Ammonium transporter OS=Klebsiella oxytoca (strain ATCC 8724 / DSM 4798 / JCM 20051 / NBRC 3318 / NRRL B-199 / KCTC 1686 / BUCSAV 143 / CCM 1901) OX=1006551 GN=KOX_12825 PE=3 SV=1
Number of features: 0
Seq('MKTGLGALALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFYGGLIR...YNA')
ID: tr|A0A0J2IA68|A0A0J2IA68_9ENTR
Name: tr|A0A0J2IA68|A0A0J2IA68_9ENTR
Description: tr|A0A0J2IA68|A0A0J2IA68_9ENTR Ammonium transporter OS=Klebsiella michiganensis OX=1134687 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKIATMKTGLGALALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A378GLU3|A0A378GLU3_9ENTR
Name: tr|A0A378GLU3|A0A378GLU3_9ENTR
Description: tr|A0A378GLU3|A0A378GLU3_9ENTR Ammonium transporter OS=Kluyvera ascorbata OX=51288 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKKTMVKTGLSALALLPGLAMAAPAVVDKADNAFMMLCTALVLFMTIPGIALF...YNA')
ID: tr|A0A3N2SFS2|A0A3N2SFS2_9ENTR
Name: tr|A0A3N2SFS2|A0A3N2SFS2_9ENTR
Description: tr|A0A3N2SFS2|A0A3N2SFS2_9ENTR Ammonium transporter OS=Kluyvera ascorbata OX=51288 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKTMVKTGLSALALLPGLAMAAPAVVDKADNAFMMLCTALVLFMTIPGIALFY...YNA')
ID: tr|A0A2T2Y0D5|A0A2T2Y0D5_9ENTR
Name: tr|A0A2T2Y0D5|A0A2T2Y0D5_9ENTR
Description: tr|A0A2T2Y0D5|A0A2T2Y0D5_9ENTR Ammonium transporter OS=Kluyvera genomosp. 2 OX=2774054 GN=C8256_14685 PE=3 SV=1
Number of features: 0
Seq('MKKTMVKTGLSALALLPGLAMAAPAAVDKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A5P2U5F4|A0A5P2U5F4_KLULC
Name: tr|A0A5P2U5F4|A0A5P2U5F4_KLULC
Description: tr|A0A5P2U5F4|A0A5P2U5F4_KLULC Ammonium transporter OS=Kluyveromyces lactis OX=28985 GN=KDRO_D03300 PE=3 SV=1
Number of features: 0
Seq('MSEFTGVPTDTGTGGNSLDTDLNTPYDKANMAWIMVAGSFVWLMVPGIGLLYSG...VNA')
ID: tr|A0A5P2U5E9|A0A5P2U5E9_KLULC
Name: tr|A0A5P2U5E9|A0A5P2U5E9_KLULC
Description: tr|A0A5P2U5E9|A0A5P2U5E9_KLULC Ammonium transporter OS=Kluyveromyces lactis OX=28985 GN=KDRO_D03310 PE=3 SV=1
Number of features: 0
Seq('MSEFTGIPTDTGTGGNSLDTDLNTPYDKADMVWIFIAGSFVWLMVPGIGLLYSG...TNA')
ID: tr|Q6CRN1|Q6CRN1_KLULA
Name: tr|Q6CRN1|Q6CRN1_KLULA
Description: tr|Q6CRN1|Q6CRN1_KLULA Ammonium transporter OS=Kluyveromyces lactis (strain ATCC 8585 / CBS 2359 / DSM 70799 / NBRC 1267 / NRRL Y-1140 / WM37) OX=284590 GN=KLLA0_D07744g PE=3 SV=1
Number of features: 0
Seq('MSEFTGIPTDTGTGGNSLDTDLNTPYDKANMAWIMVAGSFVWLMVPGIGLLYSG...ANA')
ID: tr|Q6CRN0|Q6CRN0_KLULA
Name: tr|Q6CRN0|Q6CRN0_KLULA
Description: tr|Q6CRN0|Q6CRN0_KLULA Ammonium transporter OS=Kluyveromyces lactis (strain ATCC 8585 / CBS 2359 / DSM 70799 / NBRC 1267 / NRRL Y-1140 / WM37) OX=284590 GN=KLLA0_D07766g PE=3 SV=1
Number of features: 0
Seq('MSEFTGIPTDTGTGGNSLDTDLNAPYDKADMVWIFIAGSFVWLMVPGIGLLYSG...TNA')
ID: tr|A0A5P2U8K3|A0A5P2U8K3_KLULC
Name: tr|A0A5P2U8K3|A0A5P2U8K3_KLULC
Description: tr|A0A5P2U8K3|A0A5P2U8K3_KLULC Ammonium transporter OS=Kluyveromyces lactis OX=28985 GN=KDRO_E06490 PE=3 SV=1
Number of features: 0
Seq('MTSVWHETYDGSTIAFIFMGCALVFIMIPGLGFLYSGLARRKSALSLIWAVIMA...TPI')
ID: tr|Q6CVL9|Q6CVL9_KLULA
Name: tr|Q6CVL9|Q6CVL9_KLULA
Description: tr|Q6CVL9|Q6CVL9_KLULA Ammonium transporter OS=Kluyveromyces lactis (strain ATCC 8585 / CBS 2359 / DSM 70799 / NBRC 1267 / NRRL Y-1140 / WM37) OX=284590 GN=KLLA0_B11033g PE=3 SV=1
Number of features: 0
Seq('MTSVWHETYDGSTIAFIFMGCALVFIMVPGLGFLYSGLARRKSALSLIWAVIMA...TPI')
ID: tr|A0A5P2UBW0|A0A5P2UBW0_KLULC
Name: tr|A0A5P2UBW0|A0A5P2UBW0_KLULC
Description: tr|A0A5P2UBW0|A0A5P2UBW0_KLULC Major facilitator superfamily (MFS) profile domain-containing protein OS=Kluyveromyces lactis OX=28985 GN=KDRO_F00180 PE=4 SV=1
Number of features: 0
Seq('MSSKKLNSHEEQDSLLSQNSEEWTSLLKEVFSIMVLCSAQLMTQAGLAQSIVPL...KYV')
ID: tr|Q6CWZ4|Q6CWZ4_KLULA
Name: tr|Q6CWZ4|Q6CWZ4_KLULA
Description: tr|Q6CWZ4|Q6CWZ4_KLULA KLLA0B00352p OS=Kluyveromyces lactis (strain ATCC 8585 / CBS 2359 / DSM 70799 / NBRC 1267 / NRRL Y-1140 / WM37) OX=284590 GN=KLLA0_B00352g PE=4 SV=1
Number of features: 0
Seq('MSSKKLNSHEEQDSLLLQNSREWTSLLKEGFAIMVLCSAQLMTQAGLAQSIVPL...KYV')
ID: tr|A0A0B4EV76|A0A0B4EV76_KOCRH
Name: tr|A0A0B4EV76|A0A0B4EV76_KOCRH
Description: tr|A0A0B4EV76|A0A0B4EV76_KOCRH Ammonium transporter OS=Kocuria rhizophila OX=72000 GN=RK09_00005 PE=3 SV=1
Number of features: 0
Seq('MELTAGHVWMVVAAGLVFFMTPGLALFYGGMTRAKGVLNMMMMSFAALGVVGVV...RIS')
ID: tr|A0A101Y6H3|A0A101Y6H3_KOCRH
Name: tr|A0A101Y6H3|A0A101Y6H3_KOCRH
Description: tr|A0A101Y6H3|A0A101Y6H3_KOCRH Ammonium transporter OS=Kocuria rhizophila OX=72000 GN=IX41_11380 PE=3 SV=1
Number of features: 0
Seq('MLARDRDEVIRVELTAGHVWMVVAAGLVFFMTPGLALFYGGMTRAKGVLNMMMM...SNP')
ID: tr|A0A2I1P2U4|A0A2I1P2U4_KOCRH
Name: tr|A0A2I1P2U4|A0A2I1P2U4_KOCRH
Description: tr|A0A2I1P2U4|A0A2I1P2U4_KOCRH Ammonium transporter OS=Kocuria rhizophila OX=72000 GN=CYJ75_07360 PE=3 SV=1
Number of features: 0
Seq('MLARDRDEVIRVELTAGHVWMVVAAGLVFFMTPGLALFYGGMTRAKGVLNMMMM...SNP')
ID: tr|B2GFN1|B2GFN1_KOCRD
Name: tr|B2GFN1|B2GFN1_KOCRD
Description: tr|B2GFN1|B2GFN1_KOCRD Ammonium transporter OS=Kocuria rhizophila (strain ATCC 9341 / DSM 348 / NBRC 103217 / DC2201) OX=378753 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MPARDRDEVIRMELTAGHVWMVVAAGLVFFMTPGLALFYGGMTRAKGVLNMMMM...SNQ')
ID: tr|A0A9E1C4G3|A0A9E1C4G3_KOCRH
Name: tr|A0A9E1C4G3|A0A9E1C4G3_KOCRH
Description: tr|A0A9E1C4G3|A0A9E1C4G3_KOCRH Ammonium transporter OS=Kocuria rhizophila OX=72000 GN=KH989_04400 PE=3 SV=1
Number of features: 0
Seq('MPTRNRDEVIRVELTAGHVWTVVAAGLVFFMTPGLALFYGGMTRAKGVLNMMMM...DNQ')
ID: tr|A9DQM8|A9DQM8_9FLAO
Name: tr|A9DQM8|A9DQM8_9FLAO
Description: tr|A9DQM8|A9DQM8_9FLAO Ammonium transporter OS=Kordia algicida OT-1 OX=391587 GN=KAOT1_15938 PE=3 SV=1
Number of features: 0
Seq('MDNFLTILPNFITIQDATAVSSEDLKAAIEAINTDMGMLWMLLSGILVFFMQAG...RGE')
ID: tr|A0A165BP25|A0A165BP25_9ENTR
Name: tr|A0A165BP25|A0A165BP25_9ENTR
Description: tr|A0A165BP25|A0A165BP25_9ENTR Ammonium transporter OS=Kosakonia radicincitans OX=283686 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MKNTTLKTGLASLALLPGLAMAAPAVADKADNGFMMISTALVLFMSIPGIALFY...YNA')
ID: tr|C5CIT6|C5CIT6_KOSOT
Name: tr|C5CIT6|C5CIT6_KOSOT
Description: tr|C5CIT6|C5CIT6_KOSOT Ammonium transporter OS=Kosmotoga olearia (strain ATCC BAA-1733 / DSM 21960 / TBF 19.5.1) OX=521045 GN=Kole_0200 PE=3 SV=1
Number of features: 0
Seq('MKKLTEEVKKVFDTGNTGFMLVATSLVMLMTPGLAFFYGGLVSRKNVLTIMMQS...YVE')

ID: tr|A0A1D8UWJ6|A0A1D8UWJ6_9PROT
Name: tr|A0A1D8UWJ6|A0A1D8UWJ6_9PROT
Description: tr|A0A1D8UWJ6|A0A1D8UWJ6_9PROT Ammonium transporter OS=Kozakia baliensis OX=153496 GN=A0U89_13455 PE=3 SV=1
Number of features: 0
Seq('MSRNLSKFLPLALAALPLSAQAATPAIDTGDTAWMLTSTALVLMMTIPGLALFY...RIN')
ID: tr|D2Q0J8|D2Q0J8_KRIFD
Name: tr|D2Q0J8|D2Q0J8_KRIFD
Description: tr|D2Q0J8|D2Q0J8_KRIFD Ammonium transporter OS=Kribbella flavida (strain DSM 17836 / JCM 10339 / NBRC 14399) OX=479435 GN=Kfla_4781 PE=3 SV=1
Number of features: 0
Seq('MEGMTLMEINAGDTAWVLVSAALVFLMTPGLAFFYGGMVRVKSVLNMMMMSAIT...ANA')
ID: tr|D6TFE1|D6TFE1_KTERA
Name: tr|D6TFE1|D6TFE1_KTERA
Description: tr|D6TFE1|D6TFE1_KTERA Ammonium transporter OS=Ktedonobacter racemifer DSM 44963 OX=485913 GN=Krac_10098 PE=3 SV=1
Number of features: 0
Seq('MTKLLRTTWERLRTNASNPIVRKNVALLMTGKLLGLALVLTAMWVILPTVVHAT...GED')
ID: tr|D6TCH6|D6TCH6_KTERA
Name: tr|D6TCH6|D6TCH6_KTERA
Description: tr|D6TCH6|D6TCH6_KTERA Ammonium transporter OS=Ktedonobacter racemifer DSM 44963 OX=485913 GN=Krac_11587 PE=3 SV=1
Number of features: 0
Seq('MLGAGIGYATTFFAGSSAGAYDAKIINAGDTAWVLLSAALVMLMTPAVGFFYGG...YRL')
ID: tr|W5WIX6|W5WIX6_9PSEU
Name: tr|W5WIX6|W5WIX6_9PSEU
Description: tr|W5WIX6|W5WIX6_9PSEU Ammonium transporter OS=Kutzneria albida DSM 43870 OX=1449976 GN=KALB_7323 PE=3 SV=1
Number of features: 0
Seq('MNTGDTAWVLVSAALVMLMTPGLAFFYGGMVRAKSVLNMLMMNFIALGVVTVLW...SKP')
ID: tr|B0DY50|B0DY50_LACBS
Name: tr|B0DY50|B0DY50_LACBS
Description: tr|B0DY50|B0DY50_LACBS Ammonium transporter (Fragment) OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT1.1b PE=3 SV=1
Number of features: 0
Seq('VNVTYDASASLVVTDDNIPYVYSPGDIAWVLASTALVWIMMPGVGFFYSGLLRQ...END')
ID: tr|B0DU91|B0DU91_LACBS
Name: tr|B0DU91|B0DU91_LACBS
Description: tr|B0DU91|B0DU91_LACBS Ammonium transporter OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT2.3b PE=3 SV=1
Number of features: 0
Seq('MDLIRAVSTNSYDRGDLSFIIISGAMVSFMIPGLAFLYSGLSRRKSALSLIWAV...VVA')
ID: tr|B0DXT9|B0DXT9_LACBS
Name: tr|B0DXT9|B0DXT9_LACBS
Description: tr|B0DXT9|B0DXT9_LACBS Ammonium transporter OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT2.3c PE=3 SV=1
Number of features: 0
Seq('MDLIRAVSTNSYDRGDLSFIIISGAMVSFMIPGLAFLYSGLSRRKSALSLIWAV...VVA')
ID: tr|B0CQX4|B0CQX4_LACBS
Name: tr|B0CQX4|B0CQX4_LACBS
Description: tr|B0CQX4|B0CQX4_LACBS Ammonium transporter OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT2.1 PE=3 SV=1
Number of features: 0
Seq('MGFSPDGSTSSYRAFFSRAVNDLKQYDHGDLSFIIIAGAMVSFMIPGLAFLYSG...AAT')
ID: tr|B0DU93|B0DU93_LACBS
Name: tr|B0DU93|B0DU93_LACBS
Description: tr|B0DU93|B0DU93_LACBS Ammonium transporter (Fragment) OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT2.3a PE=3 SV=1
Number of features: 0
Seq('THRYDRGDLSFIIISGAMVSFMIPGLAFLYSGLSRRKSALSLIWAVSASNAVVV...VVA')
ID: tr|B0CXH8|B0CXH8_LACBS
Name: tr|B0CXH8|B0CXH8_LACBS
Description: tr|B0CXH8|B0CXH8_LACBS Ammonium transporter OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT1.1a PE=3 SV=1
Number of features: 0
Seq('MVNVTYDASASLIVTDNATPNLYNPGDIAWVLASTALVWIMIPGVGYFYAGLLR...ENV')
ID: tr|B0DFJ4|B0DFJ4_LACBS
Name: tr|B0DFJ4|B0DFJ4_LACBS
Description: tr|B0DFJ4|B0DFJ4_LACBS Ammonium transporter OS=Laccaria bicolor (strain S238N-H82 / ATCC MYA-4686) OX=486041 GN=LbAMT1.2 PE=3 SV=1
Number of features: 0
Seq('MVNVTYDASGDLNWVDGDGKTVVYNLGDIGFVIAATALVWIMIPGVGFFYSGLL...TEA')
ID: tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM
Name: tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM
Description: tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM Ammonium transporter, Amt family OS=Lachnobacterium bovis DSM 14045 OX=1122142 GN=SAMN02910414_01015 PE=3 SV=1
Number of features: 0
Seq('MTKEIVSGLVNKEAFAVWFLCGAALVFWMQAGFAMVETGFTRAKNSGNIIMKNL...DVE')
ID: tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM
Name: tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM
Description: tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM Ammonium transporter, Amt family OS=Lachnospira multipara OX=28051 GN=SAMN05216537_11526 PE=3 SV=1
Number of features: 0
Seq('MNEVLEAVNSQVFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNAGNIIMKNMMD...DVE')
ID: tr|Q5FLR6|Q5FLR6_LACAC
Name: tr|Q5FLR6|Q5FLR6_LACAC
Description: tr|Q5FLR6|Q5FLR6_LACAC Ammonium transporter OS=Lactobacillus acidophilus (strain ATCC 700396 / NCK56 / N2 / NCFM) OX=272621 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MINQTNTLFVFVASVLVFFMTPGLAFFYGGMVSKKNAVNTMISVFMITGVAIVL...EEK')
ID: tr|A0A809KDP7|A0A809KDP7_LACAI
Name: tr|A0A809KDP7|A0A809KDP7_LACAI
Description: tr|A0A809KDP7|A0A809KDP7_LACAI Ammonium transporter OS=Lactobacillus acidophilus OX=1579 GN=CXB72_08645 PE=3 SV=1
Number of features: 0
Seq('MINQTNTLFVFVASVLVFFMTPGLAFFYGGMVSKKNAVNTMISVFMITGVAIVL...EEK')
ID: tr|A0A0U2KG74|A0A0U2KG74_LACDE
Name: tr|A0A0U2KG74|A0A0U2KG74_LACDE
Description: tr|A0A0U2KG74|A0A0U2KG74_LACDE Ammonium transporter OS=Lactobacillus delbrueckii subsp. bulgaricus OX=1585 GN=AT236_01619 PE=3 SV=1
Number of features: 0
Seq('MNTANTVFLIIAAVLVLMMTPGLAFFYGGLVSKKNVVNTMISVFIICALAIVLF...FGK')
ID: tr|C1D4X0|C1D4X0_LARHH
Name: tr|C1D4X0|C1D4X0_LARHH
Description: tr|C1D4X0|C1D4X0_LARHH Ammonium transporter OS=Laribacter hongkongensis (strain HLHK9) OX=557598 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKAIGILALAGMLGIGTALVLTRSGTPAHVPLVSITTPAPADGTVPIETAAAG...RVE')
ID: tr|A0A248LMH8|A0A248LMH8_9NEIS
Name: tr|A0A248LMH8|A0A248LMH8_9NEIS
Description: tr|A0A248LMH8|A0A248LMH8_9NEIS Ammonium transporter OS=Laribacter hongkongensis OX=168471 GN=LHGZ1_3107 PE=3 SV=1
Number of features: 0
Seq('MKKAIGILALAGVLGIGTALVLTRSGTPAHVPLVSITTPAPADGTVPIETAAAG...RVE')
ID: tr|A0A248LNK5|A0A248LNK5_9NEIS
Name: tr|A0A248LNK5|A0A248LNK5_9NEIS
Description: tr|A0A248LNK5|A0A248LNK5_9NEIS Ammonium transporter OS=Laribacter hongkongensis OX=168471 GN=LHGZ1_3487 PE=3 SV=1
Number of features: 0
Seq('MLAINTGDTAFIILCTALVALMTPGLALFYGGLVRSRDMLTIMMQNFISMGIVT...DKN')
ID: tr|A0A248LNW8|A0A248LNW8_9NEIS
Name: tr|A0A248LNW8|A0A248LNW8_9NEIS
Description: tr|A0A248LNW8|A0A248LNW8_9NEIS Ammonium transporter family protein OS=Laribacter hongkongensis OX=168471 GN=LHGZ1_3338 PE=3 SV=1
Number of features: 0
Seq('MPLAPPPSAADVLFLLLGAIMILAMHAGFAFLELGTVRKKNQVNALVKILTDFA...TSW')
ID: tr|C1D6X6|C1D6X6_LARHH
Name: tr|C1D6X6|C1D6X6_LARHH
Description: tr|C1D6X6|C1D6X6_LARHH Ammonium transporter OS=Laribacter hongkongensis (strain HLHK9) OX=557598 GN=LHK_03249 PE=3 SV=1
Number of features: 0
Seq('MLAINTGDTAFIILCTALVALMTPGLALFYGGLVRSRDMLTIMMQNFISMGIVT...DKN')
ID: tr|E4RTK5|E4RTK5_LEAB4
Name: tr|E4RTK5|E4RTK5_LEAB4
Description: tr|E4RTK5|E4RTK5_LEAB4 Ammonium transporter OS=Leadbetterella byssophila (strain DSM 17132 / JCM 16389 / KACC 11308 / NBRC 106382 / 4M15) OX=649349 GN=Lbys_1140 PE=3 SV=1
Number of features: 0
Seq('MTNSKLSPVPLIILLVITGLALFFPFTPTAIVTEGIDAADTAWVLISAALVLIM...IEA')
ID: tr|A0A855EH99|A0A855EH99_9ENTR
Name: tr|A0A855EH99|A0A855EH99_9ENTR
Description: tr|A0A855EH99|A0A855EH99_9ENTR Ammonium transporter OS=Leclercia adecarboxylata OX=83655 GN=CRX53_03405 PE=3 SV=1
Number of features: 0
Seq('MNTTTLKAGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A514VEB8|A0A514VEB8_9ENTR
Name: tr|A0A514VEB8|A0A514VEB8_9ENTR
Description: tr|A0A514VEB8|A0A514VEB8_9ENTR Ammonium transporter OS=Leclercia adecarboxylata OX=83655 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNTTTFKAGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A3XNG6|A3XNG6_LEEBM
Name: tr|A3XNG6|A3XNG6_LEEBM
Description: tr|A3XNG6|A3XNG6_LEEBM Ammonium transporter OS=Leeuwenhoekiella blandensis (strain CECT 7118 / CCUG 51940 / KCTC 22103 / MED217) OX=398720 GN=MED217_10202 PE=3 SV=1
Number of features: 0
Seq('MNFMANMLLQEPADAVQAAVDAVNADLGILWIIIAAILVFFMQAGFTLVETGFT...DEE')
ID: tr|A0A1E2SKM1|A0A1E2SKM1_LEIXY
Name: tr|A0A1E2SKM1|A0A1E2SKM1_LEIXY
Description: tr|A0A1E2SKM1|A0A1E2SKM1_LEIXY Ammonium transporter OS=Leifsonia xyli subsp. xyli OX=59736 GN=ATY41_01855 PE=3 SV=1
Number of features: 0
Seq('MMAATSQQVDALLLLVFGALTLLAVPSLGFLSGGLGGRQGVARAVLFGLTGTAV...CDG')
ID: tr|Q6AFC6|Q6AFC6_LEIXX
Name: tr|Q6AFC6|Q6AFC6_LEIXX
Description: tr|Q6AFC6|Q6AFC6_LEIXX Ammonium transporter OS=Leifsonia xyli subsp. xyli (strain CTCB07) OX=281090 GN=amt PE=3 SV=1
Number of features: 0
Seq('MMAATSQQVDALLLLVFGALTLLAVPSLGFLSGGLGGRQGVARAVLFGLTGTAV...CDG')

ID: tr|U3P8G1|U3P8G1_LEIXC
Name: tr|U3P8G1|U3P8G1_LEIXC
Description: tr|U3P8G1|U3P8G1_LEIXC Ammonium transporter OS=Leifsonia xyli subsp. cynodontis DSM 46306 OX=1389489 GN=O159_11350 PE=3 SV=1
Number of features: 0
Seq('MDYAAAGTVNSLWLLVAAALVLLMTPGVAFFYGGMVRAKSVVSMMMMSVGAMAI...ETV')
ID: tr|U3PCH5|U3PCH5_LEIXC
Name: tr|U3PCH5|U3PCH5_LEIXC
Description: tr|U3PCH5|U3PCH5_LEIXC Ammonium transporter AmtB-like domain-containing protein OS=Leifsonia xyli subsp. cynodontis DSM 46306 OX=1389489 GN=O159_11360 PE=3 SV=1
Number of features: 0
Seq('MAATSQQVDALLLVVFGTLTLLAVPGLGFLSGGLGGRQGVARAVLFALAGTAVV...SDG')
ID: tr|A0A1A9F8V6|A0A1A9F8V6_LELAM
Name: tr|A0A1A9F8V6|A0A1A9F8V6_LELAM
Description: tr|A0A1A9F8V6|A0A1A9F8V6_LELAM Ammonium transporter OS=Lelliottia amnigena OX=61646 GN=A8A57_04955 PE=3 SV=1
Number of features: 0
Seq('MKKSTIKLGLGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A3S5XY87|A0A3S5XY87_LELAM
Name: tr|A0A3S5XY87|A0A3S5XY87_LELAM
Description: tr|A0A3S5XY87|A0A3S5XY87_LELAM Ammonium transporter OS=Lelliottia amnigena OX=61646 GN=CO697_21595 PE=3 SV=1
Number of features: 0
Seq('MKKTTIKLALGSLALLPGLAMAAPAVADKADNAFMMICTALVLFMTIPGIALFY...YNA')
ID: tr|A0A085HMI3|A0A085HMI3_9GAMM
Name: tr|A0A085HMI3|A0A085HMI3_9GAMM
Description: tr|A0A085HMI3|A0A085HMI3_9GAMM Ammonium transporter OS=Leminorella grimontii ATCC 33999 = DSM 5078 OX=1005999 GN=GLGR_0716 PE=3 SV=1
Number of features: 0
Seq('MKRYLSRTAVGLLILLPGVAAAQTAADKADNAFMMISTAMVLFMSIPGIALFYG...YNP')
ID: tr|A6DN47|A6DN47_9BACT
Name: tr|A6DN47|A6DN47_9BACT
Description: tr|A6DN47|A6DN47_9BACT Ammonium transporter OS=Lentisphaera araneosa HTCC2155 OX=313628 GN=LNTAR_06104 PE=3 SV=1
Number of features: 0
Seq('MKKLMFAFVCLLATGIFSVSAGTELAPAAEGVTLKSFQEKVQVDFDNQTEKAEV...TNQ')
ID: tr|A6DUG4|A6DUG4_9BACT
Name: tr|A6DUG4|A6DUG4_9BACT
Description: tr|A6DUG4|A6DUG4_9BACT Ammonium transporter OS=Lentisphaera araneosa HTCC2155 OX=313628 GN=LNTAR_06084 PE=3 SV=1
Number of features: 0
Seq('MNKLIIALLCLMTLGVFTAQAGTELAVSGEGATLESFKEGVKASWDELETKEET...TNQ')
ID: tr|A0A833LX85|A0A833LX85_9LEPT
Name: tr|A0A833LX85|A0A833LX85_9LEPT
Description: tr|A0A833LX85|A0A833LX85_9LEPT Ammonium transporter OS=Leptonema illini OX=183 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKRWIKSTGRPALSAVLFFCLAVPGLLLADEPPATVDVTKVLGDLTGGASALRI...RAR')
ID: tr|A0A833H2R7|A0A833H2R7_9LEPT
Name: tr|A0A833H2R7|A0A833H2R7_9LEPT
Description: tr|A0A833H2R7|A0A833H2R7_9LEPT Ammonium transporter OS=Leptonema illini OX=183 GN=amt PE=3 SV=1
Number of features: 0
Seq('MIRPVNANPLMRVARIVLTVAVAFIPLSLFAQEAPDPVAVLRQETNWLWTMIAS...EQI')
ID: tr|A0A833GZR2|A0A833GZR2_9LEPT
Name: tr|A0A833GZR2|A0A833GZR2_9LEPT
Description: tr|A0A833GZR2|A0A833GZR2_9LEPT Ammonium transporter OS=Leptonema illini OX=183 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDRSAADILWILISAGLVLLMQAGFLAIESGLTRSKNSINVAIKNITDFGVAAI...REG')
ID: tr|H2CLF7|H2CLF7_9LEPT
Name: tr|H2CLF7|H2CLF7_9LEPT
Description: tr|H2CLF7|H2CLF7_9LEPT Ammonium transporter OS=Leptonema illini DSM 21528 OX=929563 GN=Lepil_4090 PE=3 SV=1
Number of features: 0
Seq('MKRWIKSTGRPALSAVLFFCLAVPGLLLADEPPATVDVTKVLDDLTGGASALRI...RAR')
ID: tr|H2CJI0|H2CJI0_9LEPT
Name: tr|H2CJI0|H2CJI0_9LEPT
Description: tr|H2CJI0|H2CJI0_9LEPT Ammonium transporter OS=Leptonema illini DSM 21528 OX=929563 GN=Lepil_2462 PE=3 SV=1
Number of features: 0
Seq('MDRSAADILWILISAGLVLLMQAGFLAIESGLTRSKNSINVAIKNITDFGVAAI...REG')
ID: tr|H2CDR5|H2CDR5_9LEPT
Name: tr|H2CDR5|H2CDR5_9LEPT
Description: tr|H2CDR5|H2CDR5_9LEPT Ammonium transporter OS=Leptonema illini DSM 21528 OX=929563 GN=Lepil_2936 PE=3 SV=1
Number of features: 0
Seq('MIRPVNANPLMRVARIVLTVAVAFIPLSLFAQEAPDPVAVLRQETNWLWTMIAS...EQI')
ID: tr|B0SLB7|B0SLB7_LEPBP
Name: tr|B0SLB7|B0SLB7_LEPBP
Description: tr|B0SLB7|B0SLB7_LEPBP Ammonium transporter OS=Leptospira biflexa serovar Patoc (strain Patoc 1 / ATCC 23582 / Paris) OX=456481 GN=amtB1 PE=3 SV=1
Number of features: 0
Seq('MNVQMVLRPVLFGFLLLLPNILLAEGETGTVNPIDKSDTTWMLVSSALVFFMIP...DIR')
ID: tr|B0SL05|B0SL05_LEPBP
Name: tr|B0SL05|B0SL05_LEPBP
Description: tr|B0SL05|B0SL05_LEPBP Ammonium transporter OS=Leptospira biflexa serovar Patoc (strain Patoc 1 / ATCC 23582 / Paris) OX=456481 GN=amtB2 PE=3 SV=1
Number of features: 0
Seq('MERIHGNMKQYFKSIAFLLLVVPMFLFADEAATVVSPAEETAKAIQTLTVGLDT...VRG')
ID: tr|B0SRS8|B0SRS8_LEPBP
Name: tr|B0SRS8|B0SRS8_LEPBP
Description: tr|B0SRS8|B0SRS8_LEPBP Ammonium transporter OS=Leptospira biflexa serovar Patoc (strain Patoc 1 / ATCC 23582 / Paris) OX=456481 GN=LEPBI_I1767 PE=3 SV=1
Number of features: 0
Seq('MKHFGIYFTLMALFLVSVLNAESLENGEKESLESLAKDLAVIKASLAETKLALE...VSK')
ID: tr|A0A094W9G3|A0A094W9G3_9BACT
Name: tr|A0A094W9G3|A0A094W9G3_9BACT
Description: tr|A0A094W9G3|A0A094W9G3_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=LptCag_1825 PE=3 SV=1
Number of features: 0
Seq('MGKSCFLTRRKVAIGMFFRKNFPELQFYRRKGHFFLGLLAVGGGCLSDISSVWA...GQG')
ID: tr|A0A1V3SSW1|A0A1V3SSW1_9BACT
Name: tr|A0A1V3SSW1|A0A1V3SSW1_9BACT
Description: tr|A0A1V3SSW1|A0A1V3SSW1_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=BOX24_10260 PE=3 SV=1
Number of features: 0
Seq('MSCYAIGQSWKGEEQRIFHQDRKEVSGKSCFFMKRKVESGMFFRKNFPELQFYR...GQG')
ID: tr|A0A2I2MEF2|A0A2I2MEF2_9BACT
Name: tr|A0A2I2MEF2|A0A2I2MEF2_9BACT
Description: tr|A0A2I2MEF2|A0A2I2MEF2_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=nrgA2 PE=3 SV=1
Number of features: 0
Seq('MFFRKNFPELQFYRRKGHFFLGLLAVGGGCLSDISSVWADAPSENQVMEGMDTL...GQG')
ID: tr|A0A7C3QR70|A0A7C3QR70_9BACT
Name: tr|A0A7C3QR70|A0A7C3QR70_9BACT
Description: tr|A0A7C3QR70|A0A7C3QR70_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=amt PE=3 SV=1
Number of features: 0
Seq('MAGNWLNSGDNAWQLTAATIVGIQSVPGLVVLYGGIVKKKWAVNSAFMALYAFA...LGD')
ID: tr|A0A059XYD5|A0A059XYD5_9BACT
Name: tr|A0A059XYD5|A0A059XYD5_9BACT
Description: tr|A0A059XYD5|A0A059XYD5_9BACT Ammonium transporter OS=Leptospirillum ferriphilum YSK OX=1441628 GN=Y981_04165 PE=3 SV=1
Number of features: 0
Seq('MSCYAIGQSWKGEEQRIFHQDRKEVWGKSCFFMKRKVESGMFFRKNFPELQFYR...GQG')
ID: tr|J9ZB82|J9ZB82_LEPFM
Name: tr|J9ZB82|J9ZB82_LEPFM
Description: tr|J9ZB82|J9ZB82_LEPFM Ammonium transporter OS=Leptospirillum ferriphilum (strain ML-04) OX=1048260 GN=nrgA2 PE=3 SV=1
Number of features: 0
Seq('MSCYAIGQSWKGEEQRIFHQDRKEVSGKSCFFMKRKVESGMFFRKNFPELQFYR...GQG')
ID: tr|J9Z839|J9Z839_LEPFM
Name: tr|J9Z839|J9Z839_LEPFM
Description: tr|J9Z839|J9Z839_LEPFM Ammonium transporter OS=Leptospirillum ferriphilum (strain ML-04) OX=1048260 GN=amt-1 PE=3 SV=1
Number of features: 0
Seq('MAGNWLNSGDNAWQLTAATIVGIQSVPGLVVLYGGIVKKKWAVNSAFMALYAFA...LGD')
ID: tr|A0A7C3LUF9|A0A7C3LUF9_9BACT
Name: tr|A0A7C3LUF9|A0A7C3LUF9_9BACT
Description: tr|A0A7C3LUF9|A0A7C3LUF9_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=ENX03_02355 PE=3 SV=1
Number of features: 0
Seq('MGPAHQSSLRTHFWGMILLMGIWAGSVRPAWADSTPSDKLVMEGLDTLWVVVAA...TGR')
ID: tr|A0A059XXR1|A0A059XXR1_9BACT
Name: tr|A0A059XXR1|A0A059XXR1_9BACT
Description: tr|A0A059XXR1|A0A059XXR1_9BACT Ammonium transporter OS=Leptospirillum ferriphilum YSK OX=1441628 GN=Y981_01880 PE=3 SV=1
Number of features: 0
Seq('MAGNWLNSGDNAWQLTAATIVGIQSVPGLVVLYGGIVKKKWAVNSAFMALYAFA...LGD')
ID: tr|A0A094YPF5|A0A094YPF5_9BACT
Name: tr|A0A094YPF5|A0A094YPF5_9BACT
Description: tr|A0A094YPF5|A0A094YPF5_9BACT Ammonium transporter OS=Leptospirillum ferriphilum OX=178606 GN=BOX24_00275 PE=3 SV=1
Number of features: 0
Seq('MAGNWLNSGDNAWQLTAATIVGIQSVPGLVVLYGGIVKKKWAVNSAFMALYAFA...LGD')
ID: tr|B1Y8C9|B1Y8C9_LEPCP
Name: tr|B1Y8C9|B1Y8C9_LEPCP
Description: tr|B1Y8C9|B1Y8C9_LEPCP Ammonium transporter OS=Leptothrix cholodnii (strain ATCC 51168 / LMG 8142 / SP-6) OX=395495 GN=Lcho_3941 PE=3 SV=1
Number of features: 0
Seq('MKKFLAKLALGLAVLGFTGAVLAQAASEPVAAAAVMEAASAAVEAAADAASAAE...YHK')
ID: tr|B1Y6V4|B1Y6V4_LEPCP
Name: tr|B1Y6V4|B1Y6V4_LEPCP
Description: tr|B1Y6V4|B1Y6V4_LEPCP Ammonium transporter OS=Leptothrix cholodnii (strain ATCC 51168 / LMG 8142 / SP-6) OX=395495 GN=Lcho_0157 PE=3 SV=1
Number of features: 0
Seq('MKLFQALRWLAPAALSVSPTALWAEEATAAATAVAAVAAPVLSAGDTAFIFACC...YKY')
ID: tr|B1Y0E5|B1Y0E5_LEPCP
Name: tr|B1Y0E5|B1Y0E5_LEPCP
Description: tr|B1Y0E5|B1Y0E5_LEPCP Ammonium transporter OS=Leptothrix cholodnii (strain ATCC 51168 / LMG 8142 / SP-6) OX=395495 GN=Lcho_4373 PE=3 SV=1
Number of features: 0
Seq('MRFPSAATRGCLAASAWLSCASAAAQPAARGLQSAAVIDSGDTAWMMAATALVL...RVE')

ID: tr|B1XZU2|B1XZU2_LEPCP
Name: tr|B1XZU2|B1XZU2_LEPCP
Description: tr|B1XZU2|B1XZU2_LEPCP Ammonium transporter OS=Leptothrix cholodnii (strain ATCC 51168 / LMG 8142 / SP-6) OX=395495 GN=Lcho_0663 PE=3 SV=1
Number of features: 0
Seq('MNELINLAWVGICTALVFFMQAGFALVEGGLARAKNSVNVIMKIYLGTCFIGVG...RDA')
ID: tr|B1Y842|B1Y842_LEPCP
Name: tr|B1Y842|B1Y842_LEPCP
Description: tr|B1Y842|B1Y842_LEPCP Rh family protein/ammonium transporter OS=Leptothrix cholodnii (strain ATCC 51168 / LMG 8142 / SP-6) OX=395495 GN=Lcho_2647 PE=3 SV=1
Number of features: 0
Seq('MDSYKQGADALFILLGAIMVLAMHAGFAFLELGTVRKKNQVNALVKILVDFAVS...VSW')
ID: tr|A0A1H1BPD6|A0A1H1BPD6_9MICO
Name: tr|A0A1H1BPD6|A0A1H1BPD6_9MICO
Description: tr|A0A1H1BPD6|A0A1H1BPD6_9MICO Ammonium transporter OS=Leucobacter chromiiresistens OX=1079994 GN=SAMN04488565_2955 PE=3 SV=1
Number of features: 0
Seq('MELTPSDVWTLTSAALVLIMTPGLALFYGGLVRVRSVVNMMLFSVSAMGVVGVL...PTR')
ID: tr|A0A147EQL9|A0A147EQL9_9MICO
Name: tr|A0A147EQL9|A0A147EQL9_9MICO
Description: tr|A0A147EQL9|A0A147EQL9_9MICO Ammonium transporter OS=Leucobacter chromiiresistens OX=1079994 GN=NS354_03055 PE=3 SV=1
Number of features: 0
Seq('MELTPSDVWTLTSAALVLIMTPGLALFYGGLVRVRSVVNMMLFSVSAMGVVGVL...PTR')
ID: tr|D5T4N9|D5T4N9_LEUKI
Name: tr|D5T4N9|D5T4N9_LEUKI
Description: tr|D5T4N9|D5T4N9_LEUKI Ammonium transporter OS=Leuconostoc kimchii (strain IMSNU 11154 / KCTC 2386 / IH25) OX=762051 GN=LKI_09855 PE=3 SV=1
Number of features: 0
Seq('MNTGDLAWVLISSALVWLMTPGLALFYGGLGEKRNLLHTMFIPVLIIGIASLTW...TVE')
ID: tr|A0A7V2SZE0|A0A7V2SZE0_LEUMU
Name: tr|A0A7V2SZE0|A0A7V2SZE0_LEUMU
Description: tr|A0A7V2SZE0|A0A7V2SZE0_LEUMU Ammonium transporter OS=Leucothrix mucor OX=45248 GN=ENJ51_05785 PE=3 SV=1
Number of features: 0
Seq('MNLKSIMGLFSLTLLMPTLAFAEDKLSSGDTAWMLVATVLVLFMTIPGLSMFYA...YIL')
ID: tr|A0A7V2T108|A0A7V2T108_LEUMU
Name: tr|A0A7V2T108|A0A7V2T108_LEUMU
Description: tr|A0A7V2T108|A0A7V2T108_LEUMU Ammonium transporter OS=Leucothrix mucor OX=45248 GN=ENJ51_07500 PE=3 SV=1
Number of features: 0
Seq('MSMMDELQLILNTLWVVFAASLVFFMQAGFAMLESGMVRSKNAVNVIMKNYIDM...GKR')
ID: tr|A0AIW5|A0AIW5_LISW6
Name: tr|A0AIW5|A0AIW5_LISW6
Description: tr|A0AIW5|A0AIW5_LISW6 Ammonium transporter OS=Listeria welshimeri serovar 6b (strain ATCC 35897 / DSM 20650 / CIP 8149 / NCTC 11857 / SLCC 5334 / V8) OX=386043 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MESVFMYFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|A0A7X0WHY1|A0A7X0WHY1_LISIO
Name: tr|A0A7X0WHY1|A0A7X0WHY1_LISIO
Description: tr|A0A7X0WHY1|A0A7X0WHY1_LISIO Ammonium transporter OS=Listeria innocua OX=1642 GN=HB837_02170 PE=3 SV=1
Number of features: 0
Seq('MESVFMFFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|A0A842BMP4|A0A842BMP4_LISIO
Name: tr|A0A842BMP4|A0A842BMP4_LISIO
Description: tr|A0A842BMP4|A0A842BMP4_LISIO Ammonium transporter OS=Listeria innocua OX=1642 GN=HCA51_06605 PE=3 SV=1
Number of features: 0
Seq('MESVFMFFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|A0A660JU19|A0A660JU19_LISIO
Name: tr|A0A660JU19|A0A660JU19_LISIO
Description: tr|A0A660JU19|A0A660JU19_LISIO Ammonium transporter OS=Listeria innocua OX=1642 GN=amt PE=3 SV=1
Number of features: 0
Seq('MESVFMFFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|H1GDT6|H1GDT6_LISIO
Name: tr|H1GDT6|H1GDT6_LISIO
Description: tr|H1GDT6|H1GDT6_LISIO Ammonium transporter OS=Listeria innocua ATCC 33091 OX=1002366 GN=HMPREF0557_02179 PE=3 SV=1
Number of features: 0
Seq('MESVFMFFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|Q92BJ7|Q92BJ7_LISIN
Name: tr|Q92BJ7|Q92BJ7_LISIN
Description: tr|Q92BJ7|Q92BJ7_LISIN Ammonium transporter OS=Listeria innocua serovar 6a (strain ATCC BAA-680 / CLIP 11262) OX=272626 GN=lin1551 PE=3 SV=1
Number of features: 0
Seq('MESVFMFFCTLLVWLMTPGIALFYGGMVRRKNVLSTAMYSFSSMAIISILWVIV...YQE')
ID: tr|A5DYQ2|A5DYQ2_LODEL
Name: tr|A5DYQ2|A5DYQ2_LODEL
Description: tr|A5DYQ2|A5DYQ2_LODEL Ammonium transporter OS=Lodderomyces elongisporus (strain ATCC 11503 / CBS 2605 / JCM 1781 / NBRC 1676 / NRRL YB-4239) OX=379508 GN=LELG_02489 PE=3 SV=1
Number of features: 0
Seq('MTEEVIKQLLTRRQLFTQNLEYDESYVLLFTIASAMIWIMVPGLAFLYSGLARR...LAE')
ID: tr|A5E3X2|A5E3X2_LODEL
Name: tr|A5E3X2|A5E3X2_LODEL
Description: tr|A5E3X2|A5E3X2_LODEL Ammonium transporter OS=Lodderomyces elongisporus (strain ATCC 11503 / CBS 2605 / JCM 1781 / NBRC 1676 / NRRL YB-4239) OX=379508 GN=LELG_04310 PE=3 SV=1
Number of features: 0
Seq('MSDSGFTGTGTGGDVFKVDLNEQFEQGDMVWIGTASVLVWIMIPGVGLLYSGLS...VKK')
ID: tr|A5E1S5|A5E1S5_LODEL
Name: tr|A5E1S5|A5E1S5_LODEL
Description: tr|A5E1S5|A5E1S5_LODEL Major facilitator superfamily (MFS) profile domain-containing protein OS=Lodderomyces elongisporus (strain ATCC 11503 / CBS 2605 / JCM 1781 / NBRC 1676 / NRRL YB-4239) OX=379508 GN=LELG_03562 PE=4 SV=1
Number of features: 0
Seq('MSDHSLDLDANSAASETPRNEKQENISKQTTREEVYHSQPNFEEISFPHEAAFI...EAK')
ID: tr|A0A1H3WA00|A0A1H3WA00_9GAMM
Name: tr|A0A1H3WA00|A0A1H3WA00_9GAMM
Description: tr|A0A1H3WA00|A0A1H3WA00_9GAMM Ammonium transporter OS=Lonsdalea quercina OX=71657 GN=SAMN02982996_00373 PE=3 SV=1
Number of features: 0
Seq('MKKLSFLSGLGTVAMLPACALAETAAPVIDKADNAFMMICTALVLFMTIPGIAL...YNQ')
ID: tr|A0A1X3RP39|A0A1X3RP39_9GAMM
Name: tr|A0A1X3RP39|A0A1X3RP39_9GAMM
Description: tr|A0A1X3RP39|A0A1X3RP39_9GAMM Ammonium transporter OS=Lonsdalea iberica OX=1082703 GN=AU511_15030 PE=3 SV=1
Number of features: 0
Seq('MKKLSFLSGLGTAAMLPACAMADTAAPVIDKADNAFMMICTALVLFMTIPGIAL...YNQ')
ID: tr|A0A1X3RR37|A0A1X3RR37_9GAMM
Name: tr|A0A1X3RR37|A0A1X3RR37_9GAMM
Description: tr|A0A1X3RR37|A0A1X3RR37_9GAMM Ammonium transporter OS=Lonsdalea britannica OX=1082704 GN=AU510_12620 PE=3 SV=1
Number of features: 0
Seq('MKKLSFLSGLGTAAMLPACAMADTAAPVIDKADNAFMMICTALVLFMTIPGIAL...YNQ')
ID: tr|V4CRP5|V4CRP5_LOTGI
Name: tr|V4CRP5|V4CRP5_LOTGI
Description: tr|V4CRP5|V4CRP5_LOTGI Ammonium transporter OS=Lottia gigantea OX=225164 GN=LOTGIDRAFT_102290 PE=3 SV=1
Number of features: 0
Seq('MEVSNNSSLSYEQTGGLGPSGPITWDDATWILTSSFIIFTMQSGFGLLEAGSVS...LHL')
ID: tr|V3ZVE4|V3ZVE4_LOTGI
Name: tr|V3ZVE4|V3ZVE4_LOTGI
Description: tr|V3ZVE4|V3ZVE4_LOTGI Ammonium transporter (Fragment) OS=Lottia gigantea OX=225164 GN=LOTGIDRAFT_126447 PE=3 SV=1
Number of features: 0
Seq('MDEGNFTYHGSRNLKIRSHDDATWILTSAFIIFTMQSGFGLLESGSVSAKNEVN...HGI')
ID: tr|V4AP67|V4AP67_LOTGI
Name: tr|V4AP67|V4AP67_LOTGI
Description: tr|V4AP67|V4AP67_LOTGI Ammonium transporter (Fragment) OS=Lottia gigantea OX=225164 GN=LOTGIDRAFT_188698 PE=3 SV=1
Number of features: 0
Seq('MDGSNGTKDMNNTMTQMEMDFNALQSNLDQFFLLTNGMIVLLMQCGFAFLEAGA...EEK')
ID: tr|V4A9D7|V4A9D7_LOTGI
Name: tr|V4A9D7|V4A9D7_LOTGI
Description: tr|V4A9D7|V4A9D7_LOTGI Ammonium transporter AmtB-like domain-containing protein OS=Lottia gigantea OX=225164 GN=LOTGIDRAFT_233447 PE=4 SV=1
Number of features: 0
Seq('MSGRLNTRILQENLQTELSCVVVALSTLFILGLQIGYSLLEAGISRSRNVYTII...NQS')
ID: tr|A0A562BXM4|A0A562BXM4_9GAMM
Name: tr|A0A562BXM4|A0A562BXM4_9GAMM
Description: tr|A0A562BXM4|A0A562BXM4_9GAMM Ammonium transporter OS=Luteimonas sp. J16 OX=935283 GN=L599_003600000150 PE=3 SV=1
Number of features: 0
Seq('MKTKMFSGLKTRTRAAALALLFGVAAAFAASPVLAQEAEADAPVAEAVAAVEDA...YES')
ID: tr|A0A839WU60|A0A839WU60_9GAMM
Name: tr|A0A839WU60|A0A839WU60_9GAMM
Description: tr|A0A839WU60|A0A839WU60_9GAMM Ammonium transporter OS=Luteimonas sp. RC10 OX=2587035 GN=FHW73_000522 PE=3 SV=1
Number of features: 0
Seq('MNSIQTRGWTPRMQAAGPSLLCALALLGVSTGALAQAPEAAAPVFDSGNVAWML...YET')
ID: tr|A0A853JAB6|A0A853JAB6_9GAMM
Name: tr|A0A853JAB6|A0A853JAB6_9GAMM
Description: tr|A0A853JAB6|A0A853JAB6_9GAMM Ammonium transporter OS=Luteimonas salinisoli OX=2752307 GN=H0E84_07010 PE=3 SV=1
Number of features: 0
Seq('MKIRDFSGWKTRVHLLCMLTLLAVLGLGFAAGAVAQDAGVPQPETVEEGYEVPA...YET')
ID: tr|A0A5C5TYS5|A0A5C5TYS5_9GAMM
Name: tr|A0A5C5TYS5|A0A5C5TYS5_9GAMM
Description: tr|A0A5C5TYS5|A0A5C5TYS5_9GAMM Ammonium transporter OS=Luteimonas marina OX=488485 GN=FQY83_13220 PE=3 SV=1
Number of features: 0
Seq('MKMHLCSGWKTRLQAAGLAVLFGVAAMAAAPGVFAQDAEAPVAEAAGEVADATV...YES')
ID: tr|A0A290XBB5|A0A290XBB5_9GAMM
Name: tr|A0A290XBB5|A0A290XBB5_9GAMM
Description: tr|A0A290XBB5|A0A290XBB5_9GAMM Ammonium transporter OS=Luteimonas chenhongjianii OX=2006110 GN=CNR27_02370 PE=3 SV=1
Number of features: 0
Seq('MKTIEIRGWKTRMQLLLQMLVCACAMLGVAGGAFAQDLPAVEAAAVVLETTGAV...YEK')

ID: tr|A0A653N397|A0A653N397_9GAMM
Name: tr|A0A653N397|A0A653N397_9GAMM
Description: tr|A0A653N397|A0A653N397_9GAMM Ammonium transporter OS=Luteimonas sp. 9C OX=2653148 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKIESRGWQTRMQALCLMLLCACALFGVAGGAFAQDLPAAETAVAVVETAEAV...YEK')
ID: tr|A0A4R5U5V1|A0A4R5U5V1_9GAMM
Name: tr|A0A4R5U5V1|A0A4R5U5V1_9GAMM
Description: tr|A0A4R5U5V1|A0A4R5U5V1_9GAMM Ammonium transporter OS=Luteimonas terrae OX=1530191 GN=E2F49_15095 PE=3 SV=1
Number of features: 0
Seq('MKTIEFRGWKTRMQAVCLMLLCAFALSGVAGIAMAQDVAPEVTGAVVDATVVVE...YEK')
ID: tr|A0A7Z0QPG3|A0A7Z0QPG3_9GAMM
Name: tr|A0A7Z0QPG3|A0A7Z0QPG3_9GAMM
Description: tr|A0A7Z0QPG3|A0A7Z0QPG3_9GAMM Ammonium transporter OS=Luteimonas deserti OX=2752306 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTTTTTRGWATRTRAFGLTLLCALALLGVAGGALAQMPPTDPPAVPVAATAEAL...YEN')
ID: tr|A0A5C5TUT2|A0A5C5TUT2_9GAMM
Name: tr|A0A5C5TUT2|A0A5C5TUT2_9GAMM
Description: tr|A0A5C5TUT2|A0A5C5TUT2_9GAMM Ammonium transporter OS=Luteimonas wenzhouensis OX=2599615 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKTKMFSGLKTRTRAAALALLFGVAAAFAASPVLAQEAEADAPVAEAVAAVEDA...YES')
ID: tr|A0A4V3ALP8|A0A4V3ALP8_9GAMM
Name: tr|A0A4V3ALP8|A0A4V3ALP8_9GAMM
Description: tr|A0A4V3ALP8|A0A4V3ALP8_9GAMM Ammonium transporter OS=Luteimonas aestuarii OX=453837 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKTCHPPGWKTRLQAAVFAVMCAVAVLAAPQSAFAQDAEAPVAEAVEETVEATE...YEN')
ID: tr|V4REY8|V4REY8_9HYPH
Name: tr|V4REY8|V4REY8_9HYPH
Description: tr|V4REY8|V4REY8_9HYPH Ammonium transporter OS=Lutibaculum baratangense AMV1 OX=631454 GN=N177_2864 PE=3 SV=1
Number of features: 0
Seq('MSQLRENSQKENEMTLARKFTWALLALPLAALIEPALAQEAAEAVETAEEAAPA...QRF')
ID: tr|V4RK08|V4RK08_9HYPH
Name: tr|V4RK08|V4RK08_9HYPH
Description: tr|V4RK08|V4RK08_9HYPH Ammonium transporter OS=Lutibaculum baratangense AMV1 OX=631454 GN=N177_1502 PE=4 SV=1
Number of features: 0
Seq('MEQQLLELGEKVAALEAGAGMSNTINMEIFYWWCTALMITIHAGFLAYEMGASR...PAQ')
ID: tr|V4RHR4|V4RHR4_9HYPH
Name: tr|V4RHR4|V4RHR4_9HYPH
Description: tr|V4RHR4|V4RHR4_9HYPH Ammonium transporter OS=Lutibaculum baratangense AMV1 OX=631454 GN=N177_1504 PE=4 SV=1
Number of features: 0
Seq('MGNNLDALTTLFTEFYYWVTVVFMFLIHVGFCLYEVAASRRRNHLHTLMKNTMC...MVR')
ID: tr|F4XTK4|F4XTK4_9CYAN
Name: tr|F4XTK4|F4XTK4_9CYAN
Description: tr|F4XTK4|F4XTK4_9CYAN Ammonium transporter OS=Moorena producens 3L OX=489825 GN=LYNGBM3L_29950 PE=3 SV=1
Number of features: 0
Seq('MKNKGTLVKSRRPMAHQSSRSSWDSPYLEPLKAIAKSFSPYWLACIPLTGIIVL...SEF')
ID: tr|F4Y3C5|F4Y3C5_9CYAN
Name: tr|F4Y3C5|F4Y3C5_9CYAN
Description: tr|F4Y3C5|F4Y3C5_9CYAN Ammonium transporter OS=Moorena producens 3L OX=489825 GN=LYNGBM3L_72170 PE=3 SV=1
Number of features: 0
Seq('MAITILLGWLGVAVAQDSNTNNFTNLSTIWLLVSSFLVFFMNAGFAMLEAGLCR...YNP')
ID: tr|A0A2S5CTX8|A0A2S5CTX8_LYSSH
Name: tr|A0A2S5CTX8|A0A2S5CTX8_LYSSH
Description: tr|A0A2S5CTX8|A0A2S5CTX8_LYSSH Ammonium transporter OS=Lysinibacillus sphaericus OX=1421 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MDDVLLSVNLVWIMLGTILVFFMHAGFAMVEAGFTRSKNAVNIIMKNFLTISLG...KHV')
ID: tr|A0A2S0JW39|A0A2S0JW39_LYSSH
Name: tr|A0A2S0JW39|A0A2S0JW39_LYSSH
Description: tr|A0A2S0JW39|A0A2S0JW39_LYSSH Ammonium transporter OS=Lysinibacillus sphaericus OX=1421 GN=LS41612_02975 PE=3 SV=1
Number of features: 0
Seq('MDDVLLSVNLVWIMLGTILVFFMHAGFAMVEAGFTRSKNAVNIIMKNFLTISLG...KHV')
ID: tr|A0A0S2FHD7|A0A0S2FHD7_LYSAN
Name: tr|A0A0S2FHD7|A0A0S2FHD7_LYSAN
Description: tr|A0A0S2FHD7|A0A0S2FHD7_LYSAN Ammonium transporter OS=Lysobacter antibioticus OX=84531 GN=amt PE=3 SV=1
Number of features: 0
Seq('MLTSTLLVLLMTVPGLALFYGGLVRSKNVLSVLMQVLAVFSLIVLLWVTYGYSL...YES')
ID: tr|A0A0S2DQB6|A0A0S2DQB6_LYSEN
Name: tr|A0A0S2DQB6|A0A0S2DQB6_LYSEN
Description: tr|A0A0S2DQB6|A0A0S2DQB6_LYSEN Ammonium transporter OS=Lysobacter enzymogenes OX=69 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKYAKMKYAKTFDDRSRERMCKTMLWTALPLAALLAFGPAHAQDAAAAAEAAKP...YEN')
ID: tr|Q2WBF7|Q2WBF7_MAGSA
Name: tr|Q2WBF7|Q2WBF7_MAGSA
Description: tr|Q2WBF7|Q2WBF7_MAGSA Ammonium transporter OS=Magnetospirillum magneticum (strain AMB-1 / ATCC 700264) OX=342108 GN=amb0014 PE=3 SV=1
Number of features: 0
Seq('MNHRLKSVLLGVGPALGLTLLASMAGAEEAAAPAAAAAPVVLDTGSTAWMLTST...TVH')
ID: tr|Q2W5V2|Q2W5V2_MAGSA
Name: tr|Q2W5V2|Q2W5V2_MAGSA
Description: tr|Q2W5V2|Q2W5V2_MAGSA Ammonia permease OS=Magnetospirillum magneticum (strain AMB-1 / ATCC 700264) OX=342108 GN=amb1969 PE=3 SV=1
Number of features: 0
Seq('MHLEAAPPSRGGGSIFGQRNPMETTKTGADVLFILLGAVMVLAMHSGFAFLEVG...KAG')
ID: tr|F3ZYD6|F3ZYD6_MAHA5
Name: tr|F3ZYD6|F3ZYD6_MAHA5
Description: tr|F3ZYD6|F3ZYD6_MAHA5 Ammonium transporter OS=Mahella australiensis (strain DSM 15567 / CIP 107919 / 50-1 BON) OX=697281 GN=Mahau_1488 PE=3 SV=1
Number of features: 0
Seq('MKRIAFITVLLALLLLPALAFAANEPTAASNAVAIDTIWTLLAGFLVFFMQAGF...ILE')
ID: tr|F3ZVV4|F3ZVV4_MAHA5
Name: tr|F3ZVV4|F3ZVV4_MAHA5
Description: tr|F3ZVV4|F3ZVV4_MAHA5 Ammonium transporter OS=Mahella australiensis (strain DSM 15567 / CIP 107919 / 50-1 BON) OX=697281 GN=Mahau_0105 PE=3 SV=1
Number of features: 0
Seq('MKEFIKRIWRYVYLTGAFMIIPVIALAAEENATINTGDTAFVLISAALVMLMTP...QRA')
ID: tr|A8PXT8|A8PXT8_MALGO
Name: tr|A8PXT8|A8PXT8_MALGO
Description: tr|A8PXT8|A8PXT8_MALGO Ammonium transporter OS=Malassezia globosa (strain ATCC MYA-4612 / CBS 7966) OX=425265 GN=MGL_1523 PE=3 SV=1
Number of features: 0
Seq('MVTFNTTADENIRIISDGEPLVYNLGDIAWVLTCTCLVFLMIPGVAFFYSGLLR...VLE')
ID: tr|A0A495DND0|A0A495DND0_9PROT
Name: tr|A0A495DND0|A0A495DND0_9PROT
Description: tr|A0A495DND0|A0A495DND0_9PROT Ammonium transporter OS=Maricaulis maris OX=74318 GN=C7435_0614 PE=3 SV=1
Number of features: 0
Seq('MCTISRRAAANPAKTLLKSRLSPIPRPSSWRSQEHQGPFTESPMDSGNNAWILT...SVG')
ID: tr|A0A495D4X4|A0A495D4X4_9PROT
Name: tr|A0A495D4X4|A0A495D4X4_9PROT
Description: tr|A0A495D4X4|A0A495D4X4_9PROT Ammonium transporter OS=Maricaulis maris OX=74318 GN=C7435_1789 PE=3 SV=1
Number of features: 0
Seq('MIGRTQMNKTLARGALCAVVAGIGLTGAAHAEVSEETAFVFNTLLFLIGGFLVM...PAQ')
ID: tr|Q0AT01|Q0AT01_MARMM
Name: tr|Q0AT01|Q0AT01_MARMM
Description: tr|Q0AT01|Q0AT01_MARMM Ammonium transporter OS=Maricaulis maris (strain MCS10) OX=394221 GN=Mmar10_0293 PE=3 SV=1
Number of features: 0
Seq('MIGRTQMSKTLARGALCAVVAGIGLTGAAHAEVSEETAFVFNTLLFLIGGFLVM...PAQ')
ID: tr|Q0ARJ4|Q0ARJ4_MARMM
Name: tr|Q0ARJ4|Q0ARJ4_MARMM
Description: tr|Q0ARJ4|Q0ARJ4_MARMM Ammonium transporter OS=Maricaulis maris (strain MCS10) OX=394221 GN=Mmar10_0800 PE=3 SV=1
Number of features: 0
Seq('MDSGNNAWILTSTALVLLMTLPGLALFYGGMVRRKNVLSTLMQSLGAAAVVTVL...SVG')
ID: tr|W0DZS7|W0DZS7_MARPU
Name: tr|W0DZS7|W0DZS7_MARPU
Description: tr|W0DZS7|W0DZS7_MARPU Ammonium transporter OS=Marichromatium purpuratum 984 OX=765910 GN=MARPU_00460 PE=3 SV=1
Number of features: 0
Seq('MNPMRHSTTLRAPLLVALLLSPLLAWGQDDAALSAGDTAWMLTATALVLFMTLP...YIL')
ID: tr|W0E077|W0E077_MARPU
Name: tr|W0E077|W0E077_MARPU
Description: tr|W0E077|W0E077_MARPU Ammonium transporter OS=Marichromatium purpuratum 984 OX=765910 GN=MARPU_02835 PE=3 SV=1
Number of features: 0
Seq('MWVLIAAGLVFLMQAGFTALESGLVRAKNSYNVAIKNISDFLVAVILFWLIGFA...FST')
ID: tr|W0DYY3|W0DYY3_MARPU
Name: tr|W0DYY3|W0DYY3_MARPU
Description: tr|W0DYY3|W0DYY3_MARPU Ammonium transporter OS=Marichromatium purpuratum 984 OX=765910 GN=MARPU_00455 PE=3 SV=1
Number of features: 0
Seq('MESTTQLVYALDTFYFLVTGALVMWMAAGFAMLEAGLVRAKNTAEILTKNIALF...RAS')
ID: tr|W0DZX1|W0DZX1_MARPU
Name: tr|W0DZX1|W0DZX1_MARPU
Description: tr|W0DZX1|W0DZX1_MARPU Ammonium transporter OS=Marichromatium purpuratum 984 OX=765910 GN=MARPU_09085 PE=3 SV=1
Number of features: 0
Seq('MQPSQAGTDVLFLLVGAVMVLAMHAGFAFLEVGTVRAKNQVNALAKIMADFAVS...GEV')
ID: tr|A0A1T4SFY6|A0A1T4SFY6_9ACTN
Name: tr|A0A1T4SFY6|A0A1T4SFY6_9ACTN
Description: tr|A0A1T4SFY6|A0A1T4SFY6_9ACTN Ammonium transporter OS=Marinactinospora thermotolerans DSM 45154 OX=1122192 GN=SAMN02745673_03519 PE=3 SV=1
Number of features: 0
Seq('MIDSGNTAWVLVSAALVMLMTPGLAFFYGGMARAKSVLNMMLMSFTSIAIVSVL...VRL')
ID: tr|A0A2T0XPP2|A0A2T0XPP2_9BACT
Name: tr|A0A2T0XPP2|A0A2T0XPP2_9BACT
Description: tr|A0A2T0XPP2|A0A2T0XPP2_9BACT Ammonium transporter OS=Marinilabilia salmonicolor OX=989 GN=DFO77_12237 PE=3 SV=1
Number of features: 0
Seq('MEEITKQVSEITVSLDMLWVLIAAAMVMFMQPGFAMVEAGFSRAKNTANILMKN...NLT')
ID: tr|M7XJ51|M7XJ51_9BACT
Name: tr|M7XJ51|M7XJ51_9BACT
Description: tr|M7XJ51|M7XJ51_9BACT Ammonium transporter OS=Mariniradius saccharolyticus AK6 OX=1239962 GN=C943_03165 PE=3 SV=1
Number of features: 0
Seq('MKWINVTLAHVSEDPGVVDLTAEITQNLLTTNNVWMMLCTAMVFIMHLGFAGVE...FDE')

ID: tr|F2NNQ0|F2NNQ0_MARHT
Name: tr|F2NNQ0|F2NNQ0_MARHT
Description: tr|F2NNQ0|F2NNQ0_MARHT Ammonium transporter OS=Marinithermus hydrothermalis (strain DSM 14884 / JCM 11576 / T1) OX=869210 GN=Marky_0310 PE=3 SV=1
Number of features: 0
Seq('MTQRSRYLGVAVGLGGVAFAQEAGVDPATTAWMLISTALVLLMTPGLAFFYGGL...GRA')
ID: tr|F2JYR9|F2JYR9_MARM1
Name: tr|F2JYR9|F2JYR9_MARM1
Description: tr|F2JYR9|F2JYR9_MARM1 Ammonium transporter OS=Marinomonas mediterranea (strain ATCC 700492 / JCM 21426 / NBRC 103028 / MMB-1) OX=717774 GN=Marme_0394 PE=4 SV=1
Number of features: 0
Seq('MSTETPTLESLQAALDAQQAVFEMHQSMNVEVFYWWCTAIMIMIHAGFLAYEMG...QGA')
ID: tr|F2JZ83|F2JZ83_MARM1
Name: tr|F2JZ83|F2JZ83_MARM1
Description: tr|F2JZ83|F2JZ83_MARM1 Ammonium transporter OS=Marinomonas mediterranea (strain ATCC 700492 / JCM 21426 / NBRC 103028 / MMB-1) OX=717774 GN=Marme_3960 PE=3 SV=1
Number of features: 0
Seq('MTATNSAVEMLIANSNTFFILLGAIMVFAMHAGFAFLEVGTVRSKNQVNALVKI...SKD')
ID: tr|F2JTN3|F2JTN3_MARM1
Name: tr|F2JTN3|F2JTN3_MARM1
Description: tr|F2JTN3|F2JTN3_MARM1 Ammonium transporter OS=Marinomonas mediterranea (strain ATCC 700492 / JCM 21426 / NBRC 103028 / MMB-1) OX=717774 GN=Marme_3437 PE=3 SV=1
Number of features: 0
Seq('MQEVYHLQYAMDTFYFLVCGALVMWMAAGFAMLEAGLVRSKNTTEILTKNVALF...NKN')
ID: tr|Q0F2M7|Q0F2M7_9PROT
Name: tr|Q0F2M7|Q0F2M7_9PROT
Description: tr|Q0F2M7|Q0F2M7_9PROT Ammonium transporter OS=Mariprofundus ferrooxydans PV-1 OX=314345 GN=SPV1_01207 PE=3 SV=1
Number of features: 0
Seq('MKHIISKIGLMLPVALLAPGMAMAEDTLNSGDTAWMLTSTVLVLLMTLPGLALF...VYE')
ID: tr|Q0F2M5|Q0F2M5_9PROT
Name: tr|Q0F2M5|Q0F2M5_9PROT
Description: tr|Q0F2M5|Q0F2M5_9PROT Putative ammonium transporter OS=Mariprofundus ferrooxydans PV-1 OX=314345 GN=SPV1_01217 PE=3 SV=1
Number of features: 0
Seq('MNTAGLDVFFLTMGAAMVLAMHAGFAFLEAGTVRKKNQVNALVRVITDFGFSTI...ASH')
ID: tr|A0A2R4MBA2|A0A2R4MBA2_9HYPH
Name: tr|A0A2R4MBA2|A0A2R4MBA2_9HYPH
Description: tr|A0A2R4MBA2|A0A2R4MBA2_9HYPH Ammonium transporter OS=Maritalea myrionectae OX=454601 GN=MXMO3_00748 PE=3 SV=1
Number of features: 0
Seq('MIAADTSWILVASALVLLMTMPGLALFYAGLVQSKNILSVLMHCVAIACVASIL...YRH')
ID: tr|E4TRS4|E4TRS4_MARTH
Name: tr|E4TRS4|E4TRS4_MARTH
Description: tr|E4TRS4|E4TRS4_MARTH Ammonium transporter OS=Marivirga tractuosa (strain ATCC 23168 / DSM 4126 / NBRC 15989 / NCIMB 1408 / VKM B-1430 / H-43) OX=643867 GN=Ftrac_2795 PE=3 SV=1
Number of features: 0
Seq('MDLSFLSSIQGLFSPLLAANIENTTKAASEINLEILTVNNLWMMLCIALVFIMH...TYE')
ID: tr|A0A4R3NVT3|A0A4R3NVT3_9HYPH
Name: tr|A0A4R3NVT3|A0A4R3NVT3_9HYPH
Description: tr|A0A4R3NVT3|A0A4R3NVT3_9HYPH Ammonium transporter OS=Martelella mediterranea OX=293089 GN=EDC90_100681 PE=3 SV=1
Number of features: 0
Seq('MSSKLKLFAGATAIAAASFALPALAQEETIIDLTTATGVSPATQEIFNTLLFLI...EFM')
ID: tr|A0A1U9YY82|A0A1U9YY82_9HYPH
Name: tr|A0A1U9YY82|A0A1U9YY82_9HYPH
Description: tr|A0A1U9YY82|A0A1U9YY82_9HYPH Ammonium transporter OS=Martelella mediterranea DSM 17316 OX=1122214 GN=amt_1 PE=3 SV=1
Number of features: 0
Seq('MSSKLKYIAGFAALAAATAAFPAFAQEEAAEAVVEVASGAPAADTVVIFNTLLF...EFM')
ID: tr|A0A1U9Z147|A0A1U9Z147_9HYPH
Name: tr|A0A1U9Z147|A0A1U9Z147_9HYPH
Description: tr|A0A1U9Z147|A0A1U9Z147_9HYPH Ammonium transporter OS=Martelella mediterranea DSM 17316 OX=1122214 GN=amt_2 PE=3 SV=1
Number of features: 0
Seq('MQAINAGDTAFVLICTALVCMMTPALALFYGGLVKQRDVLSIMIQNFVCIGIVS...INK')
ID: tr|C6LBD3|C6LBD3_9FIRM
Name: tr|C6LBD3|C6LBD3_9FIRM
Description: tr|C6LBD3|C6LBD3_9FIRM Nitrogen regulatory protein P-II OS=Marvinbryantia formatexigens DSM 14469 OX=478749 GN=BRYFOR_05928 PE=3 SV=1
Number of features: 0
Seq('MRSGEYLPFSLGERGGKIMMDEIMSAVSGEVFAVWFLIGAALVFWMQAGFAMVE...DVE')
ID: tr|A0A7C3HEP6|A0A7C3HEP6_MEIRU
Name: tr|A0A7C3HEP6|A0A7C3HEP6_MEIRU
Description: tr|A0A7C3HEP6|A0A7C3HEP6_MEIRU Ammonium transporter OS=Meiothermus ruber OX=277 GN=ENS82_07550 PE=3 SV=1
Number of features: 0
Seq('MKNLRLPLFLLTLLGGLAFAEDPEFSAADTGWMLVATGLVLLMTPALAFFYGGM...GTD')
ID: tr|D3PKL4|D3PKL4_MEIRD
Name: tr|D3PKL4|D3PKL4_MEIRD
Description: tr|D3PKL4|D3PKL4_MEIRD Ammonium transporter OS=Meiothermus ruber (strain ATCC 35948 / DSM 1279 / VKM B-1258 / 21) OX=504728 GN=Mrub_0114 PE=3 SV=1
Number of features: 0
Seq('MKNLRLPFGLAALLGGLAFAQDPEFSAADTAWMLVATGLVLLMTPALAFFYGGM...GTD')
ID: tr|I6Z905|I6Z905_MELRP
Name: tr|I6Z905|I6Z905_MELRP
Description: tr|I6Z905|I6Z905_MELRP Ammonium transporter OS=Melioribacter roseus (strain JCM 17771 / P3M-2) OX=1191523 GN=MROS_2400 PE=3 SV=1
Number of features: 0
Seq('MKNSKKVILFLFALPVLLTAQSSTPTLESNAEKIAEVQTHADYVWTMVAAFLVF...VSK')
ID: tr|I6YYI6|I6YYI6_MELRP
Name: tr|I6YYI6|I6YYI6_MELRP
Description: tr|I6YYI6|I6YYI6_MELRP Ammonium transporter OS=Melioribacter roseus (strain JCM 17771 / P3M-2) OX=1191523 GN=MROS_2397 PE=3 SV=1
Number of features: 0
Seq('MEKELSVAVYDNLFTINNLWILISTALVFIMHLGFASLEAGLTQSKNTINILFK...KLV')
ID: tr|A0A2T1N7R1|A0A2T1N7R1_9FLAO
Name: tr|A0A2T1N7R1|A0A2T1N7R1_9FLAO
Description: tr|A0A2T1N7R1|A0A2T1N7R1_9FLAO Ammonium transporter OS=Mesoflavibacter zeaxanthinifaciens subsp. sabulilitoris OX=1520893 GN=C7H61_11915 PE=3 SV=1
Number of features: 0
Seq('MELLTTNNVWMMICTALVFFMHLGFSLLEIGLTRQKNTINILFKNIFIICVGLL...NEH')
ID: tr|L0KGR8|L0KGR8_MESAW
Name: tr|L0KGR8|L0KGR8_MESAW
Description: tr|L0KGR8|L0KGR8_MESAW Ammonium transporter OS=Mesorhizobium australicum (strain HAMBI 3006 / LMG 24608 / WSM2073) OX=754035 GN=Mesau_01100 PE=3 SV=1
Number of features: 0
Seq('MNIPSTLKTTGRAALLGTLALAALGSVAAFAQEAAPAAAAAAPAAAPTPVLDTG...VVP')
ID: tr|A0A088E6Q7|A0A088E6Q7_9CREN
Name: tr|A0A088E6Q7|A0A088E6Q7_9CREN
Description: tr|A0A088E6Q7|A0A088E6Q7_9CREN Ammonium transporter OS=Metallosphaera sedula OX=43687 GN=HA72_1539 PE=3 SV=1
Number of features: 0
Seq('MALGNLATYPPAAVPQWLSLGSNSWILTATTLVMIQSVPALALFYAGMTRRRFS...EEK')
ID: tr|A4YGZ2|A4YGZ2_METS5
Name: tr|A4YGZ2|A4YGZ2_METS5
Description: tr|A4YGZ2|A4YGZ2_METS5 Ammonium transporter OS=Metallosphaera sedula (strain ATCC 51363 / DSM 5348 / JCM 9185 / NBRC 15509 / TH2) OX=399549 GN=Msed_1539 PE=3 SV=1
Number of features: 0
Seq('MALGNLATYPPAAVPQWLSLGSNSWILTATTLVMIQSVPALALFYAGMTRRRFS...EEK')
ID: tr|B9ACS5|B9ACS5_METSM
Name: tr|B9ACS5|B9ACS5_METSM
Description: tr|B9ACS5|B9ACS5_METSM Ammonium transporter OS=Methanobrevibacter smithii DSM 2375 OX=483214 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDIFSAGDTAWVLICSLLVLLMSIPAVAFFYGGLSKRKNVLNTMFLTFIAFSIV...NFN')
ID: tr|D2ZRW2|D2ZRW2_METSM
Name: tr|D2ZRW2|D2ZRW2_METSM
Description: tr|D2ZRW2|D2ZRW2_METSM Ammonium transporter OS=Methanobrevibacter smithii DSM 2374 OX=521002 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDIFSAGDTAWVLICSLLVLLMSIPAVAFFYGGLSKRKNVLNTMFLTFIAFSIV...NFN')
ID: tr|A0A2H4U5R1|A0A2H4U5R1_METSM
Name: tr|A0A2H4U5R1|A0A2H4U5R1_METSM
Description: tr|A0A2H4U5R1|A0A2H4U5R1_METSM Ammonium transporter OS=Methanobrevibacter smithii OX=2173 GN=BK798_03070 PE=3 SV=1
Number of features: 0
Seq('MDIFSAGDTAWVLICSLLVLLMSIPAVAFFYGGLSKRKNVLNTMFLTFIAFSIV...NFN')
ID: tr|R7PZ71|R7PZ71_9EURY
Name: tr|R7PZ71|R7PZ71_9EURY
Description: tr|R7PZ71|R7PZ71_9EURY Ammonium transporter OS=Methanobrevibacter smithii CAG:186 OX=1263088 GN=BN522_00062 PE=3 SV=1
Number of features: 0
Seq('MDIFSAGDTAWVLVCSLLVLLMSIPAVAFFYGGLSKRKNVLNTMFLTFIAFSIV...NFN')
ID: tr|A5UJR1|A5UJR1_METS3
Name: tr|A5UJR1|A5UJR1_METS3
Description: tr|A5UJR1|A5UJR1_METS3 Ammonium transporter OS=Methanobrevibacter smithii (strain ATCC 35061 / DSM 861 / OCM 144 / PS) OX=420247 GN=Msm_0234 PE=3 SV=1
Number of features: 0
Seq('MDIFSAGDTAWVLVCSLLVLLMSIPAVAFFYGGLSKRKNVLNTMFLTFIAFSIV...NFN')
ID: sp|Q58739|AMT2_METJA
Name: sp|Q58739|AMT2_METJA
Description: sp|Q58739|AMT2_METJA Ammonium transporter Amt2 OS=Methanocaldococcus jannaschii (strain ATCC 43067 / DSM 2661 / JAL-1 / JCM 10045 / NBRC 100440) OX=243232 GN=amt2 PE=1 SV=1
Number of features: 0
Seq('MWGENIATADLFANATDIHSIVQALTTLANASDVFFLVVMGVLVFMMQWGFAML...TVI')
ID: tr|A0A832WGB6|A0A832WGB6_9EURY
Name: tr|A0A832WGB6|A0A832WGB6_9EURY
Description: tr|A0A832WGB6|A0A832WGB6_9EURY Ammonium transporter OS=Methanocaldococcus jannaschii OX=2190 GN=HA335_05100 PE=3 SV=1
Number of features: 0
Seq('MATADLFANATDIHSIVQALTTLANASDVFFLVVMGVLVFMMQWGFAMLEGGQV...TVI')
ID: tr|G0H0Z6|G0H0Z6_METMI
Name: tr|G0H0Z6|G0H0Z6_METMI
Description: tr|G0H0Z6|G0H0Z6_METMI Ammonium transporter OS=Methanococcus maripaludis X1 OX=1053692 GN=GYY_00345 PE=3 SV=1
Number of features: 0
Seq('MVTADLFNNPTNIMDALNTLANSSDVMFLIFTGAFIFIMHLGFAMLEGGQVREK...KEN')

ID: tr|A0A7J9P8J7|A0A7J9P8J7_METMI
Name: tr|A0A7J9P8J7|A0A7J9P8J7_METMI
Description: tr|A0A7J9P8J7|A0A7J9P8J7_METMI Amt family ammonium transporter OS=Methanococcus maripaludis OX=39152 GN=HNP93_001835 PE=3 SV=1
Number of features: 0
Seq('MVTADLFNNPTNIMDALNTLANSSDVMFLIFTGAFIFIMHLGFAMLEGGQVREK...KEN')
ID: tr|A2SS52|A2SS52_METLZ
Name: tr|A2SS52|A2SS52_METLZ
Description: tr|A2SS52|A2SS52_METLZ Ammonium transporter OS=Methanocorpusculum labreanum (strain ATCC 43576 / DSM 4855 / Z) OX=410358 GN=Mlab_0989 PE=3 SV=1
Number of features: 0
Seq('MIDTGSVAWVLASTALVLLMTPALGLFYGGMVRKKNFISVLMLVFASLMIVILQ...MVR')
ID: tr|A2SPS8|A2SPS8_METLZ
Name: tr|A2SPS8|A2SPS8_METLZ
Description: tr|A2SPS8|A2SPS8_METLZ Ammonium transporter OS=Methanocorpusculum labreanum (strain ATCC 43576 / DSM 4855 / Z) OX=410358 GN=Mlab_0157 PE=3 SV=1
Number of features: 0
Seq('MDLDTGATAWVLISAALVLMMVPAVGLFYGGMVRKKNVISTMMLSFVALALGIV...EQA')
ID: tr|A0A831PTC2|A0A831PTC2_9EURY
Name: tr|A0A831PTC2|A0A831PTC2_9EURY
Description: tr|A0A831PTC2|A0A831PTC2_9EURY Ammonium transporter OS=Methanofollis liminatans OX=2201 GN=ENN52_04675 PE=3 SV=1
Number of features: 0
Seq('MMKRQHIMWALAALCVMLLIAAPVAAADPSGEETIAENPGAALDFIWVLICGFL...EAE')
ID: tr|A0A831LSC0|A0A831LSC0_9EURY
Name: tr|A0A831LSC0|A0A831LSC0_9EURY
Description: tr|A0A831LSC0|A0A831LSC0_9EURY Ammonium transporter OS=Methanofollis liminatans OX=2201 GN=ENN52_07700 PE=3 SV=1
Number of features: 0
Seq('MAIDAGDTAFVFISTALVMLMTPAVGLFYGGLVRRKNIISMIALSFIAFSLVTV...LQM')
ID: tr|J0S2I0|J0S2I0_9EURY
Name: tr|J0S2I0|J0S2I0_9EURY
Description: tr|J0S2I0|J0S2I0_9EURY Ammonium transporter OS=Methanofollis liminatans DSM 4140 OX=28892 GN=Metli_2180 PE=3 SV=1
Number of features: 0
Seq('MMKRQHIMWALAALCVMLLIAAPVAAADPSGEETIAENPGAALDFIWVLICGFL...EAE')
ID: tr|J1ASR8|J1ASR8_9EURY
Name: tr|J1ASR8|J1ASR8_9EURY
Description: tr|J1ASR8|J1ASR8_9EURY Ammonium transporter OS=Methanofollis liminatans DSM 4140 OX=28892 GN=Metli_2172 PE=3 SV=1
Number of features: 0
Seq('MAIDAGDTAFILICTAMVMLMTPGVGLFYGGLVRRKNIIAMITLAFIAFSVVSL...AHT')
ID: tr|J1L5M8|J1L5M8_9EURY
Name: tr|J1L5M8|J1L5M8_9EURY
Description: tr|J1L5M8|J1L5M8_9EURY Ammonium transporter OS=Methanofollis liminatans DSM 4140 OX=28892 GN=Metli_2174 PE=3 SV=1
Number of features: 0
Seq('MRTIAIDAGDTAFVFISTALVMLMTPAVGLFYGGLVRRKNIISMIALSFIAFSL...LQM')
ID: tr|D7E934|D7E934_METEZ
Name: tr|D7E934|D7E934_METEZ
Description: tr|D7E934|D7E934_METEZ Ammonium transporter OS=Methanohalobium evestigatum (strain ATCC BAA-1072 / DSM 3721 / NBRC 107634 / OCM 161 / Z-7303) OX=644295 GN=Metev_1100 PE=3 SV=1
Number of features: 0
Seq('MYRISIKSKRITLVIATLILVLLTLTNSAYATSIEENAASITSLETTLTFVWLI...ESE')
ID: tr|D5E995|D5E995_METMS
Name: tr|D5E995|D5E995_METMS
Description: tr|D5E995|D5E995_METMS Ammonium transporter OS=Methanohalophilus mahii (strain ATCC 35705 / DSM 5219 / SLP) OX=547558 GN=Mmah_0212 PE=3 SV=1
Number of features: 0
Seq('MSINMEKIGKLMILTCVILIVLLSPGAAVTAEENAQAISDMETALTFVWLLIAS...IED')
ID: tr|L0KW14|L0KW14_METHD
Name: tr|L0KW14|L0KW14_METHD
Description: tr|L0KW14|L0KW14_METHD Ammonium transporter OS=Methanomethylovorans hollandica (strain DSM 15978 / NBRC 107637 / DMS1) OX=867904 GN=Metho_1066 PE=3 SV=1
Number of features: 0
Seq('MALDTGDTAFILICTAMVMLMTPGVGLFYGGMVRNKNVISMIAMSFIAFAIVTI...TKG')
ID: tr|A7I8Z2|A7I8Z2_METB6
Name: tr|A7I8Z2|A7I8Z2_METB6
Description: tr|A7I8Z2|A7I8Z2_METB6 Ammonium transporter OS=Methanoregula boonei (strain DSM 21154 / JCM 14090 / 6A8) OX=456442 GN=Mboo_1686 PE=3 SV=1
Number of features: 0
Seq('MALDSGAIAWVLASTALVMIMTPGVGFFYGGLVRKKNFIDMITLSFVAFALVSI...ERA')
ID: tr|A7I8Z4|A7I8Z4_METB6
Name: tr|A7I8Z4|A7I8Z4_METB6
Description: tr|A7I8Z4|A7I8Z4_METB6 Ammonium transporter OS=Methanoregula boonei (strain DSM 21154 / JCM 14090 / 6A8) OX=456442 GN=Mboo_1688 PE=3 SV=1
Number of features: 0
Seq('MALDTGVTTWLMVSALLVMLMTPGVGFFYGGLVRKKNFISMIALSFLVLSLTSI...ERA')
ID: tr|F7XP68|F7XP68_METZD
Name: tr|F7XP68|F7XP68_METZD
Description: tr|F7XP68|F7XP68_METZD Ammonium transporter OS=Methanosalsum zhilinae (strain DSM 4017 / NBRC 107636 / OCM 62 / WeN5) OX=679901 GN=Mzhil_1521 PE=4 SV=1
Number of features: 0
Seq('MGNSMFRGTLLLILVMCLVNLLVPAVSADLTTPTGQEGLTEDMTHLEDELHKYH...LNE')
ID: tr|F7XMD8|F7XMD8_METZD
Name: tr|F7XMD8|F7XMD8_METZD
Description: tr|F7XMD8|F7XMD8_METZD Ammonium transporter OS=Methanosalsum zhilinae (strain DSM 4017 / NBRC 107636 / OCM 62 / WeN5) OX=679901 GN=Mzhil_1848 PE=3 SV=1
Number of features: 0
Seq('MIEHLKLNYISKTGIVMLAVVVVCLLLTVPVSAADIDETTESIANLETALTFVW...GDR')
ID: tr|A0A0G3C9G5|A0A0G3C9G5_METBA
Name: tr|A0A0G3C9G5|A0A0G3C9G5_METBA
Description: tr|A0A0G3C9G5|A0A0G3C9G5_METBA Ammonium transporter OS=Methanosarcina barkeri CM1 OX=796385 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MVKKMERLKKLSIVTFVLLIALVSPALAVTSDQNAASIEEIKTTLTFMWLLLAS...REE')
ID: tr|A0A0G3CAR5|A0A0G3CAR5_METBA
Name: tr|A0A0G3CAR5|A0A0G3CAR5_METBA
Description: tr|A0A0G3CAR5|A0A0G3CAR5_METBA Ammonium transporter OS=Methanosarcina barkeri CM1 OX=796385 GN=amt2 PE=3 SV=1
Number of features: 0
Seq('MRKKINELFVSFLVLFILVVVFPAIVLADQQADPTGADTDYSGYVASSTEDAPS...KAI')
ID: tr|A0A0G3CJ36|A0A0G3CJ36_METBA
Name: tr|A0A0G3CJ36|A0A0G3CJ36_METBA
Description: tr|A0A0G3CJ36|A0A0G3CJ36_METBA Ammonium transporter OS=Methanosarcina barkeri CM1 OX=796385 GN=amt3 PE=3 SV=1
Number of features: 0
Seq('MAIEAADTVWVLISSALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNI')
ID: tr|A0A2U1SS17|A0A2U1SS17_METSR
Name: tr|A0A2U1SS17|A0A2U1SS17_METSR
Description: tr|A0A2U1SS17|A0A2U1SS17_METSR Ammonium transporter OS=Methylosinus sporium OX=428 GN=C5689_07740 PE=3 SV=1
Number of features: 0
Seq('MRLRLPRSLSAASTLVGAAIAVGLADPALAAGNAPVPNPGDTAWVLISAALVLM...YNY')
ID: tr|A0A0E3QYF3|A0A0E3QYF3_METBA
Name: tr|A0A0E3QYF3|A0A0E3QYF3_METBA
Description: tr|A0A0E3QYF3|A0A0E3QYF3_METBA Ammonium transporter OS=Methanosarcina barkeri 227 OX=1434106 GN=MSBR2_0242 PE=3 SV=1
Number of features: 0
Seq('MVKKMERLKKLSIVTFVLLIALVSPALAVTSDQNAASIEEIKTTLTFMWLLLAS...REE')
ID: tr|A0A0E3R6S1|A0A0E3R6S1_METBA
Name: tr|A0A0E3R6S1|A0A0E3R6S1_METBA
Description: tr|A0A0E3R6S1|A0A0E3R6S1_METBA Ammonium transporter OS=Methanosarcina barkeri 227 OX=1434106 GN=MSBR2_2758 PE=3 SV=1
Number of features: 0
Seq('MYKYRWDDIMLNTGSTGFMLLATSLVMLMTPGLAFFYGGLSCKRNILGIMMQSF...TIH')
ID: tr|A0A0E3R4G0|A0A0E3R4G0_METBA
Name: tr|A0A0E3R4G0|A0A0E3R4G0_METBA
Description: tr|A0A0E3R4G0|A0A0E3R4G0_METBA Ammonium transporter OS=Methanosarcina barkeri 227 OX=1434106 GN=MSBR2_1801 PE=3 SV=1
Number of features: 0
Seq('MRKKINELFVSFLVLFILVVVFPAIVLADQQADPTGADTDYSGYVASSTEDAPS...KAI')
ID: tr|A0A0E3SHQ9|A0A0E3SHQ9_METBA
Name: tr|A0A0E3SHQ9|A0A0E3SHQ9_METBA
Description: tr|A0A0E3SHQ9|A0A0E3SHQ9_METBA Ammonium transporter OS=Methanosarcina barkeri 3 OX=1434107 GN=MSBR3_0193 PE=3 SV=1
Number of features: 0
Seq('MLKKMEKLNRLPIVTFVLLIALVSPAFAVTADENAAAIEEVKTTLTFMWLLLAS...RED')
ID: tr|A0A0E3LMT4|A0A0E3LMT4_METBA
Name: tr|A0A0E3LMT4|A0A0E3LMT4_METBA
Description: tr|A0A0E3LMT4|A0A0E3LMT4_METBA Ammonium transporter OS=Methanosarcina barkeri MS OX=1434108 GN=MSBRM_0578 PE=3 SV=1
Number of features: 0
Seq('MRKKINELFVSFLVLFILVVVFPAIVLADQQADPTGADTDYSGYVAASTEDAPS...KAI')
ID: tr|A0A0E3QUS2|A0A0E3QUS2_METBA
Name: tr|A0A0E3QUS2|A0A0E3QUS2_METBA
Description: tr|A0A0E3QUS2|A0A0E3QUS2_METBA Ammonium transporter OS=Methanosarcina barkeri MS OX=1434108 GN=MSBRM_2166 PE=3 SV=1
Number of features: 0
Seq('MVKKMERLKKLSIVTFVLLIALVSPALAVTSDQNAASIEEIKTTLTFMWLLLAS...REE')
ID: tr|A0A0E3WZH5|A0A0E3WZH5_METBA
Name: tr|A0A0E3WZH5|A0A0E3WZH5_METBA
Description: tr|A0A0E3WZH5|A0A0E3WZH5_METBA Ammonium transporter OS=Methanosarcina barkeri 3 OX=1434107 GN=MSBR3_2856 PE=3 SV=1
Number of features: 0
Seq('MRKKINWLFVSFFVLFSLVAAFPAVVLADQQADPTGANTDYSSYVTSSTGGAPS...RVT')
ID: tr|A0A0E3QY45|A0A0E3QY45_METBA
Name: tr|A0A0E3QY45|A0A0E3QY45_METBA
Description: tr|A0A0E3QY45|A0A0E3QY45_METBA Ammonium transporter OS=Methanosarcina barkeri MS OX=1434108 GN=MSBRM_2801 PE=3 SV=1
Number of features: 0
Seq('MYKYRWDDIMLNTGSTGFMLLATSLVMLMTPGLAFFYGGLSCKRNILGIMMQSF...TIH')
ID: tr|A0A0E3SP24|A0A0E3SP24_METBA
Name: tr|A0A0E3SP24|A0A0E3SP24_METBA
Description: tr|A0A0E3SP24|A0A0E3SP24_METBA Ammonium transporter OS=Methanosarcina barkeri 3 OX=1434107 GN=MSBR3_2665 PE=3 SV=1
Number of features: 0
Seq('MAIEGADTVWVLISAALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNV')

ID: tr|A0A0E3R6E1|A0A0E3R6E1_METBA
Name: tr|A0A0E3R6E1|A0A0E3R6E1_METBA
Description: tr|A0A0E3R6E1|A0A0E3R6E1_METBA Ammonium transporter OS=Methanosarcina barkeri 227 OX=1434106 GN=MSBR2_2757 PE=3 SV=1
Number of features: 0
Seq('MAIEAADTVWVLISSALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNI')
ID: tr|A0A0E3QY86|A0A0E3QY86_METBA
Name: tr|A0A0E3QY86|A0A0E3QY86_METBA
Description: tr|A0A0E3QY86|A0A0E3QY86_METBA Ammonium transporter OS=Methanosarcina barkeri MS OX=1434108 GN=MSBRM_2800 PE=3 SV=1
Number of features: 0
Seq('MAIEAADTVWVLISSALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNI')
ID: tr|A0A0E3QJ16|A0A0E3QJ16_METBA
Name: tr|A0A0E3QJ16|A0A0E3QJ16_METBA
Description: tr|A0A0E3QJ16|A0A0E3QJ16_METBA Ammonium transporter OS=Methanosarcina barkeri str. Wiesmoor OX=1434109 GN=MSBRW_1561 PE=3 SV=1
Number of features: 0
Seq('MVKKMERLKKLSIVTFILLIALVSPALAATSDQNAASIEEIKTTLTFMWLLLAS...REE')
ID: tr|A0A0E3QKN0|A0A0E3QKN0_METBA
Name: tr|A0A0E3QKN0|A0A0E3QKN0_METBA
Description: tr|A0A0E3QKN0|A0A0E3QKN0_METBA Ammonium transporter OS=Methanosarcina barkeri str. Wiesmoor OX=1434109 GN=MSBRW_0839 PE=3 SV=1
Number of features: 0
Seq('MTIEAADTVWVLISSALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNI')
ID: tr|Q466Y3|Q466Y3_METBF
Name: tr|Q466Y3|Q466Y3_METBF
Description: tr|Q466Y3|Q466Y3_METBF Ammonium transporter OS=Methanosarcina barkeri (strain Fusaro / DSM 804) OX=269797 GN=Mbar_A3175 PE=3 SV=1
Number of features: 0
Seq('MVKKMERLKKLSIVTFILLIALVSPALAATSDQNAASIEEIKTTLTFMWLLLAS...REE')
ID: tr|Q46G49|Q46G49_METBF
Name: tr|Q46G49|Q46G49_METBF
Description: tr|Q46G49|Q46G49_METBF Ammonium transporter OS=Methanosarcina barkeri (strain Fusaro / DSM 804) OX=269797 GN=Mbar_A0158 PE=3 SV=1
Number of features: 0
Seq('MTIEAADTVWVLISSALVLLMLPGLALFYGGLVQRKNVLSSMMHSFVAMGVMAL...YNI')
ID: tr|A0A328Q6M1|A0A328Q6M1_9EURY
Name: tr|A0A328Q6M1|A0A328Q6M1_9EURY
Description: tr|A0A328Q6M1|A0A328Q6M1_9EURY Ammonium transporter OS=Methanosphaera stadtmanae OX=2317 GN=CA615_03215 PE=3 SV=1
Number of features: 0
Seq('MVAESLLNTGDTAWILMSTALVMIMTLPGLALFYGGMSKNKNVLNTMFLSLTGF...YRI')
ID: tr|Q2NGJ2|Q2NGJ2_METST
Name: tr|Q2NGJ2|Q2NGJ2_METST
Description: tr|Q2NGJ2|Q2NGJ2_METST Ammonium transporter OS=Methanosphaera stadtmanae (strain ATCC 43021 / DSM 3091 / JCM 11832 / MCB-3) OX=339860 GN=Msp_0663 PE=3 SV=1
Number of features: 0
Seq('MVAESLLNTGDTAWILMSTALVMIMTLPGLALFYGGMSKNKNVLNTMFLSLTGF...YRI')
ID: tr|B8GGC1|B8GGC1_METPE
Name: tr|B8GGC1|B8GGC1_METPE
Description: tr|B8GGC1|B8GGC1_METPE Ammonium transporter OS=Methanosphaerula palustris (strain ATCC BAA-1556 / DSM 19958 / E1-9c) OX=521011 GN=Mpal_2784 PE=3 SV=1
Number of features: 0
Seq('MVLDSGATAWILAATALVFVMTPGVGFFYGGMVRRKNFISMIALSFLAFALVSV...IPN')
ID: tr|B8GGC3|B8GGC3_METPE
Name: tr|B8GGC3|B8GGC3_METPE
Description: tr|B8GGC3|B8GGC3_METPE Ammonium transporter OS=Methanosphaerula palustris (strain ATCC BAA-1556 / DSM 19958 / E1-9c) OX=521011 GN=Mpal_2786 PE=3 SV=1
Number of features: 0
Seq('MALDTGTTAWLLIATALVMFMTPGVGLFYGGMVRRKNFISMIALSFIALAVVTV...ERI')
ID: tr|A0A8F5VN39|A0A8F5VN39_METHU
Name: tr|A0A8F5VN39|A0A8F5VN39_METHU
Description: tr|A0A8F5VN39|A0A8F5VN39_METHU Ammonium transporter OS=Methanospirillum hungatei OX=2203 GN=KSK55_01950 PE=3 SV=1
Number of features: 0
Seq('MQAVDTAFVLICTTLVILMTFGVGFFYAGLVHRKNIISMITLSFISFALISLQW...ARS')
ID: tr|A0A8F5ZDT8|A0A8F5ZDT8_METHU
Name: tr|A0A8F5ZDT8|A0A8F5ZDT8_METHU
Description: tr|A0A8F5ZDT8|A0A8F5ZDT8_METHU Ammonium transporter OS=Methanospirillum hungatei OX=2203 GN=KSK55_09865 PE=3 SV=1
Number of features: 0
Seq('MTLDSGATAWILASTCLVMLMTPGVGLFYGGLVRRKNVISMVALAFLCYALVSV...ARS')
ID: tr|Q2FS34|Q2FS34_METHJ
Name: tr|Q2FS34|Q2FS34_METHJ
Description: tr|Q2FS34|Q2FS34_METHJ Ammonium transporter OS=Methanospirillum hungatei JF-1 (strain ATCC 27890 / DSM 864 / NBRC 100397 / JF-1) OX=323259 GN=Mhun_2504 PE=3 SV=1
Number of features: 0
Seq('MTLDSGATAWILASTCLVMLMTPGVGLFYGGLVRRKNVIAMVALAFLSYALVSV...ARS')
ID: tr|Q2FQT3|Q2FQT3_METHJ
Name: tr|Q2FQT3|Q2FQT3_METHJ
Description: tr|Q2FQT3|Q2FQT3_METHJ Ammonium transporter OS=Methanospirillum hungatei JF-1 (strain ATCC 27890 / DSM 864 / NBRC 100397 / JF-1) OX=323259 GN=Mhun_0771 PE=3 SV=1
Number of features: 0
Seq('MQAVDTAFVLLCTALVILMTFGVGFFYAGLVHRKNIISMITLSFISFALISLQW...SRA')
ID: sp|O26757|Y661_METTH
Name: sp|O26757|Y661_METTH
Description: sp|O26757|Y661_METTH Putative ammonium transporter MTH_661 OS=Methanothermobacter thermautotrophicus (strain ATCC 29096 / DSM 1053 / JCM 10044 / NBRC 100330 / Delta H) OX=187420 GN=MTH_661 PE=3 SV=1
Number of features: 0
Seq('MMLNSGDTAWMLISTALVILMTVPGVAMFYSGLTKRENVLNTIFLSFVSLGIVS...RLT')
ID: sp|O26759|Y663_METTH
Name: sp|O26759|Y663_METTH
Description: sp|O26759|Y663_METTH Putative ammonium transporter MTH_663 OS=Methanothermobacter thermautotrophicus (strain ATCC 29096 / DSM 1053 / JCM 10044 / NBRC 100330 / Delta H) OX=187420 GN=MTH_663 PE=3 SV=1
Number of features: 0
Seq('MEMTLMDAVLNSGDTAWMLVSTALVMLMTVPGVALFYGGLTKKENVLNTMFLSL...YRI')
ID: tr|A0A842YNC7|A0A842YNC7_METTF
Name: tr|A0A842YNC7|A0A842YNC7_METTF
Description: tr|A0A842YNC7|A0A842YNC7_METTF Ammonium transporter OS=Methanothermobacter thermautotrophicus OX=145262 GN=DNK57_08835 PE=3 SV=1
Number of features: 0
Seq('MDAVLNSGDTAWMLVSTALVMLMTVPGVALFYGGLTKKENVLNTMFLSLIAFAV...YRI')
ID: tr|A0A7J4MVN6|A0A7J4MVN6_METTF
Name: tr|A0A7J4MVN6|A0A7J4MVN6_METTF
Description: tr|A0A7J4MVN6|A0A7J4MVN6_METTF Ammonium transporter OS=Methanothermobacter thermautotrophicus OX=145262 GN=HA285_04230 PE=3 SV=1
Number of features: 0
Seq('MDAVLNSGDTAWMLVSTALVMLMTVPGVALFYGGLTKKENVLNTMFLSLIAFAV...YRI')
ID: tr|A0A842YPK2|A0A842YPK2_METTF
Name: tr|A0A842YPK2|A0A842YPK2_METTF
Description: tr|A0A842YPK2|A0A842YPK2_METTF Ammonium transporter OS=Methanothermobacter thermautotrophicus OX=145262 GN=DNK57_08825 PE=3 SV=1
Number of features: 0
Seq('MMLNSGDTAWMLISTALVILMTVPGVAMFYSGLTKRENVLNTIFLSFVSLGIVS...RLT')
ID: tr|A0A832YRB5|A0A832YRB5_9EURY
Name: tr|A0A832YRB5|A0A832YRB5_9EURY
Description: tr|A0A832YRB5|A0A832YRB5_9EURY Ammonium transporter OS=Methanothermococcus okinawensis OX=155863 GN=EYG76_00565 PE=3 SV=1
Number of features: 0
Seq('MIAADLNSIADALTSLVTAGNVFFLVVMGVLVFMMQWGFAMLEGGQVRKKNVNN...ERV')
ID: tr|A0A832ZZI9|A0A832ZZI9_9EURY
Name: tr|A0A832ZZI9|A0A832ZZI9_9EURY
Description: tr|A0A832ZZI9|A0A832ZZI9_9EURY Ammonium transporter OS=Methanothermococcus okinawensis OX=155863 GN=EYH55_05995 PE=3 SV=1
Number of features: 0
Seq('MAEMNITEALTQLITAGDVFFLVVMGVLVFLMQLGFAMLEGGQVRSKNVNNVMM...EAM')
ID: tr|A0A832Z6L4|A0A832Z6L4_9EURY
Name: tr|A0A832Z6L4|A0A832Z6L4_9EURY
Description: tr|A0A832Z6L4|A0A832Z6L4_9EURY Ammonium transporter OS=Methanothermococcus okinawensis OX=155863 GN=EYH15_00735 PE=3 SV=1
Number of features: 0
Seq('MTVNILETLNQLITAGDVFFLVVMGVLVFLMQLGFAMLEGGQVRSKNVNNVMMK...ESM')
ID: tr|F6BEI0|F6BEI0_METIK
Name: tr|F6BEI0|F6BEI0_METIK
Description: tr|F6BEI0|F6BEI0_METIK Ammonium transporter OS=Methanotorris igneus (strain DSM 5666 / JCM 11834 / Kol 5) OX=880724 GN=Metig_0080 PE=3 SV=1
Number of features: 0
Seq('MATADLFQNAADINSIVQALTAMANASDVFFLVVMGVLVFMMQWGFAMLEGGQV...SVA')
ID: tr|A0A832RS03|A0A832RS03_9EURY
Name: tr|A0A832RS03|A0A832RS03_9EURY
Description: tr|A0A832RS03|A0A832RS03_9EURY Ammonium transporter OS=Methermicoccus shengliensis OX=660064 GN=HA299_00445 PE=3 SV=1
Number of features: 0
Seq('MVLDSGDTAWILAATALVMLMTPGVGLFYGGLVRRKNVISMIALSFIAFALVSI...EKV')
ID: tr|B3DUX7|B3DUX7_METI4
Name: tr|B3DUX7|B3DUX7_METI4
Description: tr|B3DUX7|B3DUX7_METI4 Ammonium transporter OS=Methylacidiphilum infernorum (isolate V4) OX=481448 GN=Minf_1075 PE=3 SV=1
Number of features: 0
Seq('MMKNPTSTVLIDRSRPKLEAFIFLAILAAIVLIALGISFSNKQPSGALAQSSSA...YSI')
ID: tr|Q1GYA8|Q1GYA8_METFK
Name: tr|Q1GYA8|Q1GYA8_METFK
Description: tr|Q1GYA8|Q1GYA8_METFK Ammonium transporter OS=Methylobacillus flagellatus (strain KT / ATCC 51484 / DSM 6875) OX=265072 GN=Mfla_2514 PE=3 SV=1
Number of features: 0
Seq('MKKILSMIALVSALGFSGLALAEEEVVIVDEAVSTEIAPAAAEAVDTATEAMLA...YHY')
ID: tr|Q1H0G2|Q1H0G2_METFK
Name: tr|Q1H0G2|Q1H0G2_METFK
Description: tr|Q1H0G2|Q1H0G2_METFK Ammonium transporter OS=Methylobacillus flagellatus (strain KT / ATCC 51484 / DSM 6875) OX=265072 GN=Mfla_1757 PE=3 SV=1
Number of features: 0
Seq('MPISLLPLTLLFSLCIVPLPVSAGEGAPQALAVDSVWVAISGALVFMMQAGFAM...SRL')
ID: tr|Q1H483|Q1H483_METFK
Name: tr|Q1H483|Q1H483_METFK
Description: tr|Q1H483|Q1H483_METFK Ammonium transporter OS=Methylobacillus flagellatus (strain KT / ATCC 51484 / DSM 6875) OX=265072 GN=Mfla_0434 PE=3 SV=1
Number of features: 0
Seq('MKRFLSISTLLGGMLAAGSSLAEEVAEEAPAILNSGDTAWMIVATVLVIIMAVP...YHS')

ID: tr|A0A2S6GKF6|A0A2S6GKF6_9GAMM
Name: tr|A0A2S6GKF6|A0A2S6GKF6_9GAMM
Description: tr|A0A2S6GKF6|A0A2S6GKF6_9GAMM Ammonium transporter OS=Methylobacter tundripaludum OX=173365 GN=B0F88_11910 PE=3 SV=1
Number of features: 0
Seq('MKQLLTTFILFALLGYAGFSFADAAVPVPPAANKGDTAWMIVATVLVTLMVIPG...YHL')
ID: tr|A0A2S6H643|A0A2S6H643_9GAMM
Name: tr|A0A2S6H643|A0A2S6H643_9GAMM
Description: tr|A0A2S6H643|A0A2S6H643_9GAMM Ammonium transporter OS=Methylobacter tundripaludum OX=173365 GN=B0F87_11624 PE=3 SV=1
Number of features: 0
Seq('MKQLLTTFILFALLGYAGFSFAETVVPVPPAANKGDTAWMIVATVLVILMVIPG...YHS')
ID: tr|G3IYW2|G3IYW2_METTV
Name: tr|G3IYW2|G3IYW2_METTV
Description: tr|G3IYW2|G3IYW2_METTV Ammonium transporter OS=Methylobacter tundripaludum (strain ATCC BAA-1195 / DSM 17260 / SV96) OX=697282 GN=Mettu_3261 PE=3 SV=1
Number of features: 0
Seq('MKQLLTTFILFALLGYAGFSFAETAVPVPPAANKGDTAWMIVATVLVILMVIPG...YHS')
ID: tr|A0A2S6GKN5|A0A2S6GKN5_9GAMM
Name: tr|A0A2S6GKN5|A0A2S6GKN5_9GAMM
Description: tr|A0A2S6GKN5|A0A2S6GKN5_9GAMM Ammonium transporter OS=Methylobacter tundripaludum OX=173365 GN=B0F88_1198 PE=3 SV=1
Number of features: 0
Seq('MLLRIINRRLFLGLMLLPDLAFADQLNQANTAWVLTSTALVLFMTLPGLSLFYA...LDL')
ID: tr|A0A2S6H6B7|A0A2S6H6B7_9GAMM
Name: tr|A0A2S6H6B7|A0A2S6H6B7_9GAMM
Description: tr|A0A2S6H6B7|A0A2S6H6B7_9GAMM Ammonium transporter OS=Methylobacter tundripaludum OX=173365 GN=B0F87_11622 PE=3 SV=1
Number of features: 0
Seq('MLLNIINRRLFLGLLLLPDLAFADQLNQANTAWVLTSTALVLFMTIPGLSLFYA...LDL')
ID: tr|G3IYW0|G3IYW0_METTV
Name: tr|G3IYW0|G3IYW0_METTV
Description: tr|G3IYW0|G3IYW0_METTV Ammonium transporter OS=Methylobacter tundripaludum (strain ATCC BAA-1195 / DSM 17260 / SV96) OX=697282 GN=Mettu_3259 PE=3 SV=1
Number of features: 0
Seq('MLLNIINRRLFLGLLLLPDLAFADQLNQANTAWVLTSTALVLFMTIPGLSLFYA...LDL')
ID: tr|A0A2J7TJ33|A0A2J7TJ33_METSI
Name: tr|A0A2J7TJ33|A0A2J7TJ33_METSI
Description: tr|A0A2J7TJ33|A0A2J7TJ33_METSI Ammonium transporter OS=Methylocella silvestris OX=199596 GN=CR492_06850 PE=3 SV=1
Number of features: 0
Seq('MRARSVGLGLLLAGAAAGLAFAQTAAAAPAPVPNKGDTAWMLVSTALVLMMSVP...YNP')
ID: tr|B8ENL9|B8ENL9_METSB
Name: tr|B8ENL9|B8ENL9_METSB
Description: tr|B8ENL9|B8ENL9_METSB Ammonium transporter OS=Methylocella silvestris (strain DSM 15510 / CIP 108128 / LMG 27833 / NCIMB 13906 / BL2) OX=395965 GN=Msil_1860 PE=3 SV=1
Number of features: 0
Seq('MRFAFPPIRARSVGLGLLLAGAAAGLAFAQTAAAAPAPVPNKGDTAWMLVSTAL...YNP')
ID: tr|B8EMQ8|B8EMQ8_METSB
Name: tr|B8EMQ8|B8EMQ8_METSB
Description: tr|B8EMQ8|B8EMQ8_METSB Ammonium transporter OS=Methylocella silvestris (strain DSM 15510 / CIP 108128 / LMG 27833 / NCIMB 13906 / BL2) OX=395965 GN=Msil_3855 PE=3 SV=1
Number of features: 0
Seq('MTRFMSTWGRLRRPACALFVAALAAPLLINPALAQDAAAAAAPPACDAKTLLAC...LVH')
ID: tr|Q60C43|Q60C43_METCA
Name: tr|Q60C43|Q60C43_METCA
Description: tr|Q60C43|Q60C43_METCA Ammonium transporter OS=Methylococcus capsulatus (strain ATCC 33009 / NCIMB 11132 / Bath) OX=243233 GN=amt-1 PE=3 SV=1
Number of features: 0
Seq('MGQGPKFFGFSLLGCLLVARPLEAAELEAADTAWILTSTGFAWFMTVPGLALLY...YYF')
ID: tr|Q605Y6|Q605Y6_METCA
Name: tr|Q605Y6|Q605Y6_METCA
Description: tr|Q605Y6|Q605Y6_METCA Ammonium transporter OS=Methylococcus capsulatus (strain ATCC 33009 / NCIMB 11132 / Bath) OX=243233 GN=amt-3 PE=3 SV=1
Number of features: 0
Seq('MKNIPTSLVTLACLGFSAAAQAEGATEIVETVVETVQQAATPAVPTPDKGDTAW...YHP')
ID: tr|Q60BI2|Q60BI2_METCA
Name: tr|Q60BI2|Q60BI2_METCA
Description: tr|Q60BI2|Q60BI2_METCA Ammonium transporter OS=Methylococcus capsulatus (strain ATCC 33009 / NCIMB 11132 / Bath) OX=243233 GN=amt-2 PE=3 SV=1
Number of features: 0
Seq('MKFPVAMMRVLALSGLTWPVLAAPEGPNAADTAWILTSTGLVLFMTMPGLALLY...YHF')
ID: tr|Q608B6|Q608B6_METCA
Name: tr|Q608B6|Q608B6_METCA
Description: tr|Q608B6|Q608B6_METCA Ammonium transporter family protein OS=Methylococcus capsulatus (strain ATCC 33009 / NCIMB 11132 / Bath) OX=243233 GN=MCA1581 PE=3 SV=1
Number of features: 0
Seq('MPLIFGVCCLVVAAAHMVPAARAAAGEFFNGLLGKRMTKSADVLFVLLGAIMVL...AGW')
ID: tr|V5E0F3|V5E0F3_9GAMM
Name: tr|V5E0F3|V5E0F3_9GAMM
Description: tr|V5E0F3|V5E0F3_9GAMM Ammonium transporter OS=Methyloglobulus morosus KoM1 OX=1116472 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MPSKRHLDYTMNNKNNYNKLKFLLVLLLTPGLASAAELNQANTAWILTSTALVL...LDI')
ID: tr|V5BYZ7|V5BYZ7_9GAMM
Name: tr|V5BYZ7|V5BYZ7_9GAMM
Description: tr|V5BYZ7|V5BYZ7_9GAMM Ammonium transporter OS=Methyloglobulus morosus KoM1 OX=1116472 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNIRISSLMGMGWLLLLMTFSYPVSAEEVAAAVTPTVNKGDTAWMIVATVLVIL...YHD')
ID: tr|I1YG38|I1YG38_METFJ
Name: tr|I1YG38|I1YG38_METFJ
Description: tr|I1YG38|I1YG38_METFJ Ammonium transporter OS=Methylophaga frappieri (strain ATCC BAA-2434 / DSM 25690 / JAM7) OX=754477 GN=Q7C_710 PE=4 SV=1
Number of features: 0
Seq('MQTATDVLFILLGAIMVLAMHAGFAFLEVGTVRKKNQVNALVKIITDFGISTIA...VND')
ID: tr|I1YJH7|I1YJH7_METFJ
Name: tr|I1YJH7|I1YJH7_METFJ
Description: tr|I1YJH7|I1YJH7_METFJ Ammonium transporter OS=Methylophaga frappieri (strain ATCC BAA-2434 / DSM 25690 / JAM7) OX=754477 GN=Q7C_1929 PE=3 SV=1
Number of features: 0
Seq('MENEIFQLQYALDTFYFLISGAFVMWMAAGFAMLEAGLVRAKNTTEILTKNVML...SGK')
ID: tr|F5RGM7|F5RGM7_METUF
Name: tr|F5RGM7|F5RGM7_METUF
Description: tr|F5RGM7|F5RGM7_METUF Ammonium transporter OS=Methyloversatilis universalis (strain ATCC BAA-1314 / JCM 13912 / FAM5) OX=1000565 GN=METUNv1_03320 PE=3 SV=1
Number of features: 0
Seq('MMRFKGEREMKRFLSILCATLAIGLAAPVMAEDPPAAPAAATAEAAAPAAAPAA...YRL')
ID: tr|F5R974|F5R974_METUF
Name: tr|F5R974|F5R974_METUF
Description: tr|F5R974|F5R974_METUF Ammonium transporter OS=Methyloversatilis universalis (strain ATCC BAA-1314 / JCM 13912 / FAM5) OX=1000565 GN=METUNv1_00694 PE=3 SV=1
Number of features: 0
Seq('MDSFKTSADVLFILLGAIMVLAMHAGFAFLEVGTVRRKNQVNALVKILVDFAVS...TLW')
ID: tr|A0A2W5HTC3|A0A2W5HTC3_9BACT
Name: tr|A0A2W5HTC3|A0A2W5HTC3_9BACT
Description: tr|A0A2W5HTC3|A0A2W5HTC3_9BACT Ammonium transporter OS=Micavibrio aeruginosavorus OX=349221 GN=DI586_02325 PE=3 SV=1
Number of features: 0
Seq('MNKLKVLSSLLTVLFALMPVAAFAQDTGPALDSGDTAWMLTSSLLVLMMSVPGL...TYK')
ID: tr|A0A2W4ZXC0|A0A2W4ZXC0_9BACT
Name: tr|A0A2W4ZXC0|A0A2W4ZXC0_9BACT
Description: tr|A0A2W4ZXC0|A0A2W4ZXC0_9BACT Ammonium transporter OS=Micavibrio aeruginosavorus OX=349221 GN=DI626_05190 PE=3 SV=1
Number of features: 0
Seq('MIGADIAWMLVACALVLLMTPGVAFFYGGMVPAKSVVSTKFQSFACLGVVGLLW...TAG')
ID: tr|M4VEJ9|M4VEJ9_9BACT
Name: tr|M4VEJ9|M4VEJ9_9BACT
Description: tr|M4VEJ9|M4VEJ9_9BACT Ammonium transporter OS=Micavibrio aeruginosavorus EPB OX=349215 GN=A11S_83 PE=3 SV=1
Number of features: 0
Seq('MIPADIAWMLMATALVLLMTPGVAFFYGGMVPVRSVISTKFQSFACMGVVGLIW...ALR')
ID: tr|A0A1H1MB73|A0A1H1MB73_9MICO
Name: tr|A0A1H1MB73|A0A1H1MB73_9MICO
Description: tr|A0A1H1MB73|A0A1H1MB73_9MICO Ammonium transporter OS=Microbacterium paraoxydans OX=199592 GN=SAMN04489809_0461 PE=3 SV=1
Number of features: 0
Seq('MDAPGNISWAITATALVLLMTPGVAFFYGGLVKAKSVVSMMMMSFGSIGLVAVL...ANA')
ID: tr|A0A7U6DPL5|A0A7U6DPL5_MICLU
Name: tr|A0A7U6DPL5|A0A7U6DPL5_MICLU
Description: tr|A0A7U6DPL5|A0A7U6DPL5_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A653ISC0|A0A653ISC0_MICLU
Name: tr|A0A653ISC0|A0A653ISC0_MICLU
Description: tr|A0A653ISC0|A0A653ISC0_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MNEMTLDAGTVWMVVSAGLVLLMTPGLALFYGGMTRSKSALNMMMMSFVSMGLV...AAG')
ID: tr|D3LL06|D3LL06_MICLU
Name: tr|D3LL06|D3LL06_MICLU
Description: tr|D3LL06|D3LL06_MICLU Ammonium transporter OS=Micrococcus luteus SK58 OX=596312 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A378NLG8|A0A378NLG8_MICLU
Name: tr|A0A378NLG8|A0A378NLG8_MICLU
Description: tr|A0A378NLG8|A0A378NLG8_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A653N551|A0A653N551_MICLU
Name: tr|A0A653N551|A0A653N551_MICLU
Description: tr|A0A653N551|A0A653N551_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')

ID: tr|A0A132HDB5|A0A132HDB5_MICLU
Name: tr|A0A132HDB5|A0A132HDB5_MICLU
Description: tr|A0A132HDB5|A0A132HDB5_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A031H2S8|A0A031H2S8_MICLU
Name: tr|A0A031H2S8|A0A031H2S8_MICLU
Description: tr|A0A031H2S8|A0A031H2S8_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMMTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A031ISU7|A0A031ISU7_MICLU
Name: tr|A0A031ISU7|A0A031ISU7_MICLU
Description: tr|A0A031ISU7|A0A031ISU7_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|C5CAG5|C5CAG5_MICLC
Name: tr|C5CAG5|C5CAG5_MICLC
Description: tr|C5CAG5|C5CAG5_MICLC Ammonium transporter OS=Micrococcus luteus (strain ATCC 4698 / DSM 20030 / JCM 1464 / NBRC 3333 / NCIMB 9278 / NCTC 2665 / VKM Ac-2230) OX=465515 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A4P8HC89|A0A4P8HC89_9MICO
Name: tr|A0A4P8HC89|A0A4P8HC89_9MICO
Description: tr|A0A4P8HC89|A0A4P8HC89_9MICO Ammonium transporter OS=Brevibacterium sp. CS2 OX=2575923 GN=FDF13_13765 PE=3 SV=1
Number of features: 0
Seq('MEITAVDVWVMVSAALVLLMTPGVAFLYGGMTRAKSVLNMLMMSFASMAVVGVV...VNA')
ID: tr|A0A509Y3R3|A0A509Y3R3_MICLU
Name: tr|A0A509Y3R3|A0A509Y3R3_MICLU
Description: tr|A0A509Y3R3|A0A509Y3R3_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=C0205_03390 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A4U1LD24|A0A4U1LD24_MICLU
Name: tr|A0A4U1LD24|A0A4U1LD24_MICLU
Description: tr|A0A4U1LD24|A0A4U1LD24_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=FBF74_07985 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A410XNG8|A0A410XNG8_MICLU
Name: tr|A0A410XNG8|A0A410XNG8_MICLU
Description: tr|A0A410XNG8|A0A410XNG8_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=MT1254_01595 PE=3 SV=1
Number of features: 0
Seq('MQPADIAWILAAAAMVLLMFPGLAFLYGGMLDDRNVLNMLMMVMSGLAVGGVAY...GII')
ID: tr|A0A7T5AF95|A0A7T5AF95_MICLU
Name: tr|A0A7T5AF95|A0A7T5AF95_MICLU
Description: tr|A0A7T5AF95|A0A7T5AF95_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=I6H91_07590 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A1R4IK85|A0A1R4IK85_MICLU
Name: tr|A0A1R4IK85|A0A1R4IK85_MICLU
Description: tr|A0A1R4IK85|A0A1R4IK85_MICLU Ammonium transporter OS=Micrococcus luteus Mu201 OX=1255578 GN=FM117_01980 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A1M6ZIN6|A0A1M6ZIN6_MICLU
Name: tr|A0A1M6ZIN6|A0A1M6ZIN6_MICLU
Description: tr|A0A1M6ZIN6|A0A1M6ZIN6_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=SAMN04487849_101170 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A562FQ17|A0A562FQ17_MICLU
Name: tr|A0A562FQ17|A0A562FQ17_MICLU
Description: tr|A0A562FQ17|A0A562FQ17_MICLU Ammonium transporter OS=Micrococcus luteus J28 OX=935864 GN=L597_000400000200 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A5E8QER8|A0A5E8QER8_MICLU
Name: tr|A0A5E8QER8|A0A5E8QER8_MICLU
Description: tr|A0A5E8QER8|A0A5E8QER8_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=CYJ94_01210 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|A0A2N6RP58|A0A2N6RP58_MICLU
Name: tr|A0A2N6RP58|A0A2N6RP58_MICLU
Description: tr|A0A2N6RP58|A0A2N6RP58_MICLU Ammonium transporter OS=Micrococcus luteus OX=1270 GN=CJ227_02475 PE=3 SV=1
Number of features: 0
Seq('MEESNVLDAGTVWMVTSAAMVLLMTPGLAIFYGGMTRAKSSLNMIMMSFVSMGL...EAR')
ID: tr|F5XN43|F5XN43_MICPN
Name: tr|F5XN43|F5XN43_MICPN
Description: tr|F5XN43|F5XN43_MICPN Ammonium transporter OS=Microlunatus phosphovorus (strain ATCC 700054 / DSM 10555 / JCM 9379 / NBRC 101784 / NCIMB 13414 / VKM Ac-1990 / NM-1) OX=1032480 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSPLELNSGDTAWMLTSAALVLLMTPGLALFYGGMVRAKSVLNMMMMSFGAMAI...VKA')
ID: tr|A1ZGK6|A1ZGK6_MICM2
Name: tr|A1ZGK6|A1ZGK6_MICM2
Description: tr|A1ZGK6|A1ZGK6_MICM2 Ammonium transporter OS=Microscilla marina ATCC 23134 OX=313606 GN=M23134_03261 PE=3 SV=1
Number of features: 0
Seq('MKEALFTVHNLWMMIATILVFIMHLGFATLESGLTQSKNTVNILFKNVLIIAIG...IKT')
ID: tr|A0A2S0P9T4|A0A2S0P9T4_9NEIS
Name: tr|A0A2S0P9T4|A0A2S0P9T4_9NEIS
Description: tr|A0A2S0P9T4|A0A2S0P9T4_9NEIS Ammonium transporter OS=Microvirgula aerodenitrificans OX=57480 GN=DAI18_09010 PE=3 SV=1
Number of features: 0
Seq('MKKTLSILALIGVLGIGAAVIMKQTPVATSPVATSPAPTTTDSAGSAPATAADA...RIE')
ID: tr|C9KKP2|C9KKP2_9FIRM
Name: tr|C9KKP2|C9KKP2_9FIRM
Description: tr|C9KKP2|C9KKP2_9FIRM Ammonium transporter OS=Mitsuokella multacida DSM 20544 OX=500635 GN=amt PE=3 SV=1
Number of features: 0
Seq('MIDTGDTAWVLISAALVFVMTPGLAFFYGGMVRSKNVLTTIMQSFFIVAMISVE...QKE')
ID: tr|A0A414NWT8|A0A414NWT8_9FIRM
Name: tr|A0A414NWT8|A0A414NWT8_9FIRM
Description: tr|A0A414NWT8|A0A414NWT8_9FIRM Ammonium transporter OS=Mitsuokella multacida OX=52226 GN=DW674_07435 PE=3 SV=1
Number of features: 0
Seq('MIDTGDTAWVLISAALVFVMTPGLAFFYGGMVRSKNVLTTIMQSFFIVAMISVE...QKE')
ID: tr|H5UND3|H5UND3_9MICO
Name: tr|H5UND3|H5UND3_9MICO
Description: tr|H5UND3|H5UND3_9MICO Ammonium transporter OS=Mobilicoccus pelagius NBRC 104925 OX=1089455 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTIDSGDTAWILVSAALVMLMTPGLAFFYGGMVRAKSVLNMMMMSLGTMGTVGV...PVS')
ID: tr|D4XLN6|D4XLN6_ACIHA
Name: tr|D4XLN6|D4XLN6_ACIHA
Description: tr|D4XLN6|D4XLN6_ACIHA Ammonium transporter OS=Acinetobacter haemolyticus ATCC 19194 OX=707232 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKMLMALSLSGALLGGSTVVWAEEAASTPVTEQTVVVTETNTIPEAIEAEAPV...RVE')
ID: tr|D4XSW0|D4XSW0_ACIHA
Name: tr|D4XSW0|D4XSW0_ACIHA
Description: tr|D4XSW0|D4XSW0_ACIHA Ammonium transporter OS=Acinetobacter haemolyticus ATCC 19194 OX=707232 GN=HMP0015_2802 PE=3 SV=1
Number of features: 0
Seq('MHQIGFSTYIEHVMQNVDIFFLLLGAVLVLSMHAGFAFLELGTVRHKNQVNALS...SMF')
ID: tr|A9UR54|A9UR54_MONBE
Name: tr|A9UR54|A9UR54_MONBE
Description: tr|A9UR54|A9UR54_MONBE Ammonium transporter OS=Monosiga brevicollis OX=81824 GN=MONBRDRAFT_14204 PE=3 SV=1
Number of features: 0
Seq('MKFDECGTDVATVVDGLYLIIMAIMVYNMQLGFALLEAGTVSINATMATLFKNV...RVI')
ID: tr|A9V5W4|A9V5W4_MONBE
Name: tr|A9V5W4|A9V5W4_MONBE
Description: tr|A9V5W4|A9V5W4_MONBE Ammonium transporter AmtB-like domain-containing protein OS=Monosiga brevicollis OX=81824 GN=MONBRDRAFT_38134 PE=4 SV=1
Number of features: 0
Seq('MASRRFGVLALLSQIILLILFVVWVRYDGDLGDSSGMDQSCATRLTEIDCLAAG...PLM')
ID: tr|A0A5D3HZ79|A0A5D3HZ79_MOOTH
Name: tr|A0A5D3HZ79|A0A5D3HZ79_MOOTH
Description: tr|A0A5D3HZ79|A0A5D3HZ79_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MKHRNIGIVSGRSNILLRPEGTALFLVLFLAAGTVLARPALAAAGDAVDTGDTA...RQE')
ID: tr|A0A1J5JH24|A0A1J5JH24_MOOTH
Name: tr|A0A1J5JH24|A0A1J5JH24_MOOTH
Description: tr|A0A1J5JH24|A0A1J5JH24_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MKHRNIGIVSGRSNILLRPEGTALFLVLFLAAGTVLARPALAAAGDAVDTGDTA...RQE')
ID: tr|A0A1J5NNB8|A0A1J5NNB8_MOOTH
Name: tr|A0A1J5NNB8|A0A1J5NNB8_MOOTH
Description: tr|A0A1J5NNB8|A0A1J5NNB8_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSCKINKSALINGLILAAVIILILALPAWAGDPSGTATGSAADIPAAQAGTPTL...VHN')
ID: tr|A0A853W4S3|A0A853W4S3_MOOTH
Name: tr|A0A853W4S3|A0A853W4S3_MOOTH
Description: tr|A0A853W4S3|A0A853W4S3_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MKHRNIGIVSGRSNILLRPEGTALFLVLFLAAGTVLARPALAAAGDAVDTGDTA...RQE')
ID: tr|A0A1J5NTP7|A0A1J5NTP7_MOOTH
Name: tr|A0A1J5NTP7|A0A1J5NTP7_MOOTH
Description: tr|A0A1J5NTP7|A0A1J5NTP7_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=nrgA PE=3 SV=1
Number of features: 0
Seq('MKQRNVIIERGRSNILLRPAGRTTFLLVFFLAAGTVLARPALAAAGDAVDTGDT...RQE')
ID: tr|A0A1D7XAU3|A0A1D7XAU3_MOOTH
Name: tr|A0A1D7XAU3|A0A1D7XAU3_MOOTH
Description: tr|A0A1D7XAU3|A0A1D7XAU3_MOOTH Ammonium transporter OS=Moorella thermoacetica OX=1525 GN=amtB_1 PE=3 SV=1
Number of features: 0
Seq('MSCKISKSALINGLILAAVIILLLALPAWAGDPTGTATGSAADIPAAQAGTPTL...VHN')

ID: tr|A0A0S6UEK9|A0A0S6UEK9_MOOTH
Name: tr|A0A0S6UEK9|A0A0S6UEK9_MOOTH
Description: tr|A0A0S6UEK9|A0A0S6UEK9_MOOTH Ammonium transporter OS=Moorella thermoacetica Y72 OX=1325331 GN=MTY_1298 PE=3 SV=1
Number of features: 0
Seq('MNHRNVDIVSGRSNILLRPEGTALFLVLFLAAGTVLARPALAAAGDAVDTGDTA...RQE')
ID: tr|A0A0S6UHP2|A0A0S6UHP2_MOOTH
Name: tr|A0A0S6UHP2|A0A0S6UHP2_MOOTH
Description: tr|A0A0S6UHP2|A0A0S6UHP2_MOOTH Ammonium transporter OS=Moorella thermoacetica Y72 OX=1325331 GN=MTY_2422 PE=3 SV=1
Number of features: 0
Seq('MGNAVQSKNLLNKEAPTMSCKISKSALINGLILAAVIILLLALPAWAGDPTGTA...VHN')
ID: tr|Q2RM12|Q2RM12_MOOTA
Name: tr|Q2RM12|Q2RM12_MOOTA
Description: tr|Q2RM12|Q2RM12_MOOTA Ammonium transporter OS=Moorella thermoacetica (strain ATCC 39073 / JCM 9320) OX=264732 GN=Moth_0192 PE=3 SV=1
Number of features: 0
Seq('MFLAAGTVLARPALAAAGDAVDTGDTAFILVASALVMLMTPGLAFFYGGMVRQK...RQE')
ID: tr|A0A7Z0V0A4|A0A7Z0V0A4_MORCA
Name: tr|A0A7Z0V0A4|A0A7Z0V0A4_MORCA
Description: tr|A0A7Z0V0A4|A0A7Z0V0A4_MORCA Ammonium transporter OS=Moraxella catarrhalis OX=480 GN=AO382_0372 PE=3 SV=1
Number of features: 0
Seq('MNRFGKWASLSVGLGLLSASNLAYAEDVLDTGDTAWVLISTALVLMMTLPGLAL...IAD')
ID: tr|M1SJL5|M1SJL5_MORMO
Name: tr|M1SJL5|M1SJL5_MORMO
Description: tr|M1SJL5|M1SJL5_MORMO Ammonium transporter OS=Morganella morganii subsp. morganii KT OX=1124991 GN=MU9_3229 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAALPLPAFSATEGMERADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A2S1BIN7|A0A2S1BIN7_MORMO
Name: tr|A0A2S1BIN7|A0A2S1BIN7_MORMO
Description: tr|A0A2S1BIN7|A0A2S1BIN7_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=AM380_10815 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAVLPLPAFSATEGMDRADNGFMLICAALVYFMTLPGIALFY...NRL')
ID: tr|A0A1M7DGY1|A0A1M7DGY1_MORMO
Name: tr|A0A1M7DGY1|A0A1M7DGY1_MORMO
Description: tr|A0A1M7DGY1|A0A1M7DGY1_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=SAMN05216301_1171 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAMLPLPAFSATEGMDRADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A2C5TWB4|A0A2C5TWB4_MORMO
Name: tr|A0A2C5TWB4|A0A2C5TWB4_MORMO
Description: tr|A0A2C5TWB4|A0A2C5TWB4_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=CRX48_12425 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAALPLPAFSATEGMERADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A433ZQ80|A0A433ZQ80_MORMO
Name: tr|A0A433ZQ80|A0A433ZQ80_MORMO
Description: tr|A0A433ZQ80|A0A433ZQ80_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=CKG00_17725 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSALLPIQAFSATEGMDRADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|M7CDZ4|M7CDZ4_MORMO
Name: tr|M7CDZ4|M7CDZ4_MORMO
Description: tr|M7CDZ4|M7CDZ4_MORMO Ammonium transporter OS=Morganella morganii SC01 OX=1239989 GN=C790_00394 PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAVLPLPAFSATEGMDRADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A7U0APP4|A0A7U0APP4_MORMO
Name: tr|A0A7U0APP4|A0A7U0APP4_MORMO
Description: tr|A0A7U0APP4|A0A7U0APP4_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAVLPLPAFSATEGMERADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A8I0DAF6|A0A8I0DAF6_MORMO
Name: tr|A0A8I0DAF6|A0A8I0DAF6_MORMO
Description: tr|A0A8I0DAF6|A0A8I0DAF6_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKRKMALPVVMSAVLPLPAFSATEGMDRADNGFMLICAALVYFMTLPGIALFY...NRA')
ID: tr|A0A8I0PWC5|A0A8I0PWC5_MORMO
Name: tr|A0A8I0PWC5|A0A8I0PWC5_MORMO
Description: tr|A0A8I0PWC5|A0A8I0PWC5_MORMO Ammonium transporter OS=Morganella morganii OX=582 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMKRKMVLPVVMSAVLPLPAFSATEGMERADNGFMLICAALVYFMTLPGIALFY...NRS')
ID: tr|A0A5J6WQU1|A0A5J6WQU1_MORMI
Name: tr|A0A5J6WQU1|A0A5J6WQU1_MORMI
Description: tr|A0A5J6WQU1|A0A5J6WQU1_MORMI Ammonium transporter OS=Moritella marina ATCC 15381 OX=1202962 GN=FR932_16110 PE=3 SV=1
Number of features: 0
Seq('MQELTTTVTELRFALDTFYFLMSGVLVMWMAAGFAMLEAGLVRSKNTTEILTKN...SVK')
ID: tr|A0A5J6WPP9|A0A5J6WPP9_MORMI
Name: tr|A0A5J6WPP9|A0A5J6WPP9_MORMI
Description: tr|A0A5J6WPP9|A0A5J6WPP9_MORMI Ammonium transporter OS=Moritella marina ATCC 15381 OX=1202962 GN=FR932_11345 PE=3 SV=1
Number of features: 0
Seq('MENVNSAVETLVQSSNTMFILLGAIMVLAMHAGFAFLEVGTVRHKNQVNALVKI...MDK')
ID: tr|H1YCC3|H1YCC3_9SPHI
Name: tr|H1YCC3|H1YCC3_9SPHI
Description: tr|H1YCC3|H1YCC3_9SPHI Ammonium transporter OS=Mucilaginibacter paludis DSM 18603 OX=714943 GN=Mucpa_6056 PE=3 SV=1
Number of features: 0
Seq('MKKIIPFALLVIVVILALIFPSAETVNIATNKIDTGDTAWLLTSTALVLIMTPG...EEL')
ID: tr|H1YF74|H1YF74_9SPHI
Name: tr|H1YF74|H1YF74_9SPHI
Description: tr|H1YF74|H1YF74_9SPHI Ammonium transporter OS=Mucilaginibacter paludis DSM 18603 OX=714943 GN=Mucpa_2073 PE=3 SV=1
Number of features: 0
Seq('MNLKNDKNKLLGLNLFKDSGGGKNTSSKWSTITPEQWKMGITIFSGKILGLMLV...YAK')
ID: tr|H1Y7T6|H1Y7T6_9SPHI
Name: tr|H1Y7T6|H1Y7T6_9SPHI
Description: tr|H1Y7T6|H1Y7T6_9SPHI Ammonium transporter OS=Mucilaginibacter paludis DSM 18603 OX=714943 GN=Mucpa_5865 PE=3 SV=1
Number of features: 0
Seq('MKRLIPISFLVVILLLSFIFPSVDVINTNANISAADTAWMLSATGLVLIMTPGL...ETL')
ID: tr|G2PRJ6|G2PRJ6_MURRD
Name: tr|G2PRJ6|G2PRJ6_MURRD
Description: tr|G2PRJ6|G2PRJ6_MURRD Ammonium transporter OS=Muricauda ruestringensis (strain DSM 13258 / CIP 107369 / LMG 19739 / B1) OX=886377 GN=Murru_0391 PE=3 SV=1
Number of features: 0
Seq('MIVQEQEAIDKAVEAITGDIGALWITLAAVLVFFMQAGFTLVEIGFTRSKNSGN...QDK')
ID: sp|Q8BUX5|RHBG_MOUSE
Name: sp|Q8BUX5|RHBG_MOUSE
Description: sp|Q8BUX5|RHBG_MOUSE Ammonium transporter Rh type B OS=Mus musculus OX=10090 GN=Rhbg PE=1 SV=1
Number of features: 0
Seq('MARVPRHRRLVLPLLCLLFQGATALLFAIFVRYNHETDAALWHWGNHSNVDNEF...TRA')
ID: sp|Q9QUT0|RHAG_MOUSE
Name: sp|Q9QUT0|RHAG_MOUSE
Description: sp|Q9QUT0|RHAG_MOUSE Ammonium transporter Rh type A OS=Mus musculus OX=10090 GN=Rhag PE=1 SV=1
Number of features: 0
Seq('MRFKFPLMAISLEVAMIVLFGLFVEYETPQNASQKNASHQNASQQGNTSSSAKK...HEV')
ID: sp|Q9QXP0|RHCG_MOUSE
Name: sp|Q9QXP0|RHCG_MOUSE
Description: sp|Q9QXP0|RHCG_MOUSE Ammonium transporter Rh type C OS=Mus musculus OX=10090 GN=Rhcg PE=1 SV=2
Number of features: 0
Seq('MAWNTNLRGRLPITCLILQVTMVVLFGVFVRYDIQADAHWWLEKKRKNISSDVE...LVH')
ID: sp|P55012|S12A2_MOUSE
Name: sp|P55012|S12A2_MOUSE
Description: sp|P55012|S12A2_MOUSE Solute carrier family 12 member 2 OS=Mus musculus OX=10090 GN=Slc12a2 PE=1 SV=2
Number of features: 0
Seq('MEPGPARPRLAPAARPGWGRAAGCRRRGGPARHGRASGQEDATTAGRQAGGGVR...FYS')
ID: sp|Q9WTN6|S22AL_MOUSE
Name: sp|Q9WTN6|S22AL_MOUSE
Description: sp|Q9WTN6|S22AL_MOUSE Solute carrier family 22 member 21 OS=Mus musculus OX=10090 GN=Slc22a21 PE=2 SV=1
Number of features: 0
Seq('MLDYDEVTAFLGEWGTFQRLIFFLLSASIIPNGFTGLSAVFLTAIPEHRCRIPD...KGF')
ID: sp|Q9WVL3|S12A7_MOUSE
Name: sp|Q9WVL3|S12A7_MOUSE
Description: sp|Q9WVL3|S12A7_MOUSE Solute carrier family 12 member 7 OS=Mus musculus OX=10090 GN=Slc12a7 PE=1 SV=1
Number of features: 0
Seq('MPTNFTVVPVEARADGAGDEAAERTEEPESPESVDQTSPTPGDGNPRENSPFIN...IYS')
ID: sp|Q8R4T9|UT2_MOUSE
Name: sp|Q8R4T9|UT2_MOUSE
Description: sp|Q8R4T9|UT2_MOUSE Urea transporter 2 OS=Mus musculus OX=10090 GN=Slc14a2 PE=1 SV=2
Number of features: 0
Seq('MSDHHPLKEMSDSNSSPLLPEPLSSRYKLYESELSSPTWPSSSQDTHPALPLLE...DVS')
ID: sp|Q91V14|S12A5_MOUSE
Name: sp|Q91V14|S12A5_MOUSE
Description: sp|Q91V14|S12A5_MOUSE Solute carrier family 12 member 5 OS=Mus musculus OX=10090 GN=Slc12a5 PE=1 SV=2
Number of features: 0
Seq('MSRRFTVTSLPPAASAASADPESRRHSVADPRRLPREDVKGDGNPKESSPFINS...IYS')
ID: sp|Q924N4|S12A6_MOUSE
Name: sp|Q924N4|S12A6_MOUSE
Description: sp|Q924N4|S12A6_MOUSE Solute carrier family 12 member 6 OS=Mus musculus OX=10090 GN=Slc12a6 PE=1 SV=2
Number of features: 0
Seq('MHPPEATTKMSSVRFMVTPTKIDDIPGLSDTSPDLSSRSSSRVRFSSRESVPET...IYS')
ID: sp|Q9Z306|S22A4_MOUSE
Name: sp|Q9Z306|S22A4_MOUSE
Description: sp|Q9Z306|S22A4_MOUSE Solute carrier family 22 member 4 OS=Mus musculus OX=10090 GN=Slc22a4 PE=1 SV=1
Number of features: 0
Seq('MRDYDEVIAFLGEWGPFQRLIFFLLSASIIPNGFNGMSVVFLAGTPEHRCLVPD...TAF')
ID: sp|O70577|S22A2_MOUSE
Name: sp|O70577|S22A2_MOUSE
Description: sp|O70577|S22A2_MOUSE Solute carrier family 22 member 2 OS=Mus musculus OX=10090 GN=Slc22a2 PE=1 SV=1
Number of features: 0
Seq('MPTVDDILEHIGEFHLFQKQTFFLLALLSGAFTPIYVGIVFLGFTPNHHCRSPG...ELS')
ID: sp|Q9Z0E8|OCTN2_MOUSE
Name: sp|Q9Z0E8|OCTN2_MOUSE
Description: sp|Q9Z0E8|OCTN2_MOUSE Organic cation/carnitine transporter 2 OS=Mus musculus OX=10090 GN=Slc22a5 PE=1 SV=1
Number of features: 0
Seq('MRDYDEVTAFLGEWGPFQRLIFFLLSASIIPNGFNGMSIVFLAGTPEHRCLVPH...TAF')
ID: sp|Q8BU91|S26A9_MOUSE
Name: sp|Q8BU91|S26A9_MOUSE
Description: sp|Q8BU91|S26A9_MOUSE Solute carrier family 26 member 9 OS=Mus musculus OX=10090 GN=Slc26a9 PE=1 SV=1
Number of features: 0
Seq('MNQPRPRYVVDRAAYSLSLFDDEFEKKDRAYPVGEKLRNTFRCSSAKFKAFVFG...TAL')

ID: tr|A0A4Y6D2A4|A0A4Y6D2A4_MYXXA
Name: tr|A0A4Y6D2A4|A0A4Y6D2A4_MYXXA
Description: tr|A0A4Y6D2A4|A0A4Y6D2A4_MYXXA Ammonium transporter OS=Myxococcus xanthus OX=34 GN=BHS05_30880 PE=3 SV=1
Number of features: 0
Seq('MKKWFAMALLVGVGVAGLLVEPAAQLKQGGPINTADTAWILTATALVLLMTPGL...QPA')
ID: tr|A0A7Y4MR39|A0A7Y4MR39_MYXXA
Name: tr|A0A7Y4MR39|A0A7Y4MR39_MYXXA
Description: tr|A0A7Y4MR39|A0A7Y4MR39_MYXXA Ammonium transporter OS=Myxococcus xanthus OX=34 GN=HNV28_11885 PE=3 SV=1
Number of features: 0
Seq('MKKWLAMALLVGVGVAGLLVEPAAQLKQGGPVDTADTAWLLTATALVLLMTPGL...QPA')
ID: tr|Q1CZ61|Q1CZ61_MYXXD
Name: tr|Q1CZ61|Q1CZ61_MYXXD
Description: tr|Q1CZ61|Q1CZ61_MYXXD Ammonium transporter OS=Myxococcus xanthus (strain DK1622) OX=246197 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKWFAMALLVGVGVTGLLVEPAAQLKQGGPIDTSDTAWILTATALVLLMTPGL...QPA')
ID: tr|A0A8E4SIW9|A0A8E4SIW9_MYXXA
Name: tr|A0A8E4SIW9|A0A8E4SIW9_MYXXA
Description: tr|A0A8E4SIW9|A0A8E4SIW9_MYXXA Ammonium transporter OS=Myxococcus xanthus OX=34 GN=I5Q59_30520 PE=3 SV=1
Number of features: 0
Seq('MKKWFAMALLVGVGVTGLLVEPAAQLKQGGPIDTSDTAWILTATALVLLMTPGL...QPA')
ID: tr|A0A4Y6CGF6|A0A4Y6CGF6_MYXXA
Name: tr|A0A4Y6CGF6|A0A4Y6CGF6_MYXXA
Description: tr|A0A4Y6CGF6|A0A4Y6CGF6_MYXXA Ammonium transporter OS=Myxococcus xanthus OX=34 GN=BHS06_29240 PE=3 SV=1
Number of features: 0
Seq('MKKSLAMALLVGVGVAGLLVEPAAQLKQGGPIDTADTAWLLTATALVLLMTPGL...QPA')
ID: tr|A0A7Y4N5I8|A0A7Y4N5I8_MYXXA
Name: tr|A0A7Y4N5I8|A0A7Y4N5I8_MYXXA
Description: tr|A0A7Y4N5I8|A0A7Y4N5I8_MYXXA Ammonium transporter OS=Myxococcus xanthus OX=34 GN=HNV27_03750 PE=3 SV=1
Number of features: 0
Seq('MKKWLAMALLVGVGVAGLLVEPAAQLKQGGPINTADTAWLLTATALVLLMTPGL...QPA')
ID: tr|A0A1E3PQH0|A0A1E3PQH0_9ASCO
Name: tr|A0A1E3PQH0|A0A1E3PQH0_9ASCO
Description: tr|A0A1E3PQH0|A0A1E3PQH0_9ASCO Ammonium transporter OS=Nadsonia fulvescens var. elongata DSM 6958 OX=857566 GN=NADFUDRAFT_49530 PE=3 SV=1
Number of features: 0
Seq('MATLDLISRALTLAVTAVENDSDSDYDTTSIGFMLLCSSLIMLMSPGIGLFYAG...REN')
ID: tr|A0A1E3PSK5|A0A1E3PSK5_9ASCO
Name: tr|A0A1E3PSK5|A0A1E3PSK5_9ASCO
Description: tr|A0A1E3PSK5|A0A1E3PSK5_9ASCO Ammonium transporter OS=Nadsonia fulvescens var. elongata DSM 6958 OX=857566 GN=NADFUDRAFT_48967 PE=3 SV=1
Number of features: 0
Seq('MYYPFNSVAASARAGLQATGDVISKRATLPDSNVWEFTYNPAEIGYILISTAMV...EEK')
ID: tr|D2V1J4|D2V1J4_NAEGR
Name: tr|D2V1J4|D2V1J4_NAEGR
Description: tr|D2V1J4|D2V1J4_NAEGR Ammonium transporter OS=Naegleria gruberi OX=5762 GN=NAEGRDRAFT_30176 PE=3 SV=1
Number of features: 0
Seq('MKIHFLFDVDHCYIIGDTAWVTVSSILVLAMMSALAFFEAGLSRKKETLTIFSQ...NLH')
ID: tr|D2V6Q5|D2V6Q5_NAEGR
Name: tr|D2V6Q5|D2V6Q5_NAEGR
Description: tr|D2V6Q5|D2V6Q5_NAEGR Ammonium transporter OS=Naegleria gruberi OX=5762 GN=NAEGRDRAFT_55677 PE=3 SV=1
Number of features: 0
Seq('MSSSNTTIASLEAAIAQTHTDMDTLWVLVCTMMVFLMQTGFSFLEAGSVRSTSV...STT')
ID: tr|D2V6P8|D2V6P8_NAEGR
Name: tr|D2V6P8|D2V6P8_NAEGR
Description: tr|D2V6P8|D2V6P8_NAEGR Rh-like glycoprotein OS=Naegleria gruberi OX=5762 GN=NAEGRDRAFT_78812 PE=4 SV=1
Number of features: 0
Seq('MLHHHESQTHMINHDNPVVNSSSLDLEASENVVRASTSIDNGLGQQEQIEQQQQ...VNV')
ID: tr|D2VMN0|D2VMN0_NAEGR
Name: tr|D2VMN0|D2VMN0_NAEGR
Description: tr|D2VMN0|D2VMN0_NAEGR Predicted protein OS=Naegleria gruberi OX=5762 GN=NAEGRDRAFT_50811 PE=4 SV=1
Number of features: 0
Seq('MNSTNSTIAETLATNKNRYISGIVISSVFLIVYFIYLIGCFIYYGVKKIKGLTA...VVQ')
ID: tr|C8XBX8|C8XBX8_NAKMY
Name: tr|C8XBX8|C8XBX8_NAKMY
Description: tr|C8XBX8|C8XBX8_NAKMY Ammonium transporter OS=Nakamurella multipartita (strain ATCC 700099 / DSM 44233 / CIP 104796 / JCM 9543 / NBRC 105858 / Y-104) OX=479431 GN=Namu_3149 PE=3 SV=1
Number of features: 0
Seq('MDSTFELDAGNTAWMLAAASLVLLMTPALAFFYGGMTRSKSVLNMMMMSFGAMA...VKA')
ID: tr|C8XB51|C8XB51_NAKMY
Name: tr|C8XB51|C8XB51_NAKMY
Description: tr|C8XB51|C8XB51_NAKMY Ammonium transporter OS=Nakamurella multipartita (strain ATCC 700099 / DSM 44233 / CIP 104796 / JCM 9543 / NBRC 105858 / Y-104) OX=479431 GN=Namu_5072 PE=3 SV=1
Number of features: 0
Seq('MDTGSTAWILASSMAVSLMIPGLALFYGGMTAARSTLNMMMMVLGSVAVTGVIW...PVS')
ID: tr|L0JT30|L0JT30_NATP1
Name: tr|L0JT30|L0JT30_NATP1
Description: tr|L0JT30|L0JT30_NATP1 Ammonia permease OS=Natrinema pellirubrum (strain DSM 15624 / CIP 106293 / JCM 10476 / NCIMB 786 / 157) OX=797303 GN=Natpe_3786 PE=3 SV=1
Number of features: 0
Seq('MEPTLLQSEAEVEMLIDSINYMWILVATFLIFFMHAGFAMLEAGQVRSKNVANQ...DAV')
ID: tr|A0A1I0C958|A0A1I0C958_9CLOT
Name: tr|A0A1I0C958|A0A1I0C958_9CLOT
Description: tr|A0A1I0C958|A0A1I0C958_9CLOT Ammonium transporter OS=Natronincola peptidivorans OX=426128 GN=SAMN05660297_01542 PE=3 SV=1
Number of features: 0
Seq('METHEFVTAIDTIWVLLAAALVFFMQAGFAMVETGFTRSKNAGNIIMKNLMDFS...MTN')
ID: tr|A0A1I3M286|A0A1I3M286_9EURY
Name: tr|A0A1I3M286|A0A1I3M286_9EURY
Description: tr|A0A1I3M286|A0A1I3M286_9EURY Ammonium transporter, Amt family OS=Natronobacterium gregoryi OX=44930 GN=SAMN05443661_10953 PE=3 SV=1
Number of features: 0
Seq('MIEPVALEVTTGDLESLATGMNLLWALTVTFLIFFMHAGFAMLEAGQVRSKNVA...DAV')
ID: tr|L0AHQ0|L0AHQ0_NATGS
Name: tr|L0AHQ0|L0AHQ0_NATGS
Description: tr|L0AHQ0|L0AHQ0_NATGS Ammonia permease OS=Natronobacterium gregoryi (strain ATCC 43098 / DSM 3393 / CCM 3738 / CIP 104747 / IAM 13177 / JCM 8860 / NBRC 102187 / NCIMB 2189 / SP2) OX=797304 GN=Natgr_1462 PE=3 SV=1
Number of features: 0
Seq('MIEPVALEVTTGDLESLATGMNLLWALTVTFLIFFMHAGFAMLEAGQVRSKNVA...DAV')
ID: tr|A0A5P9P1L2|A0A5P9P1L2_9EURY
Name: tr|A0A5P9P1L2|A0A5P9P1L2_9EURY
Description: tr|A0A5P9P1L2|A0A5P9P1L2_9EURY Ammonium transporter OS=Natronorubrum aibiense OX=348826 GN=GCU68_05460 PE=3 SV=1
Number of features: 0
Seq('MDPILLQAETEMLTEAINNTWILIVTFLIFFMHAGFAMLEAGQVRSKNVANQLT...DAV')
ID: tr|G0V8D6|G0V8D6_NAUCC
Name: tr|G0V8D6|G0V8D6_NAUCC
Description: tr|G0V8D6|G0V8D6_NAUCC Ammonium transporter OS=Naumovozyma castellii (strain ATCC 76901 / BCRC 22586 / CBS 4309 / NBRC 1992 / NRRL Y-12630) OX=1064592 GN=NCAS0A11760 PE=3 SV=1
Number of features: 0
Seq('MGRGNGYLWTEEYDGSTVAFLVIGTALVFFMVPGLGFLYSGLARRKSALSLIWV...QSA')
ID: tr|G0VI62|G0VI62_NAUCC
Name: tr|G0VI62|G0VI62_NAUCC
Description: tr|G0VI62|G0VI62_NAUCC Ammonium transporter OS=Naumovozyma castellii (strain ATCC 76901 / BCRC 22586 / CBS 4309 / NBRC 1992 / NRRL Y-12630) OX=1064592 GN=NCAS0G02090 PE=3 SV=1
Number of features: 0
Seq('MSFNFTGTPTGHGTGGDSLTTDLNAQFELADMVWLGVSAAGVWIMVPGIGLLYS...NEK')
ID: tr|G0V6N4|G0V6N4_NAUCC
Name: tr|G0V6N4|G0V6N4_NAUCC
Description: tr|G0V6N4|G0V6N4_NAUCC Major facilitator superfamily (MFS) profile domain-containing protein OS=Naumovozyma castellii (strain ATCC 76901 / BCRC 22586 / CBS 4309 / NBRC 1992 / NRRL Y-12630) OX=1064592 GN=NCAS0A05720 PE=4 SV=1
Number of features: 0
Seq('MVAASSSTSTTDRTLKIQDTGNTDHYLPSNSTASSLHSQRTKEQCSNLQPAQAQ...DDE')
ID: tr|B9L7N1|B9L7N1_NAUPA
Name: tr|B9L7N1|B9L7N1_NAUPA
Description: tr|B9L7N1|B9L7N1_NAUPA Ammonium transporter OS=Nautilia profundicola (strain ATCC BAA-1463 / DSM 18972 / AmH) OX=598659 GN=amt PE=3 SV=1
Number of features: 0
Seq('MLFRVLSLLGLASLAFAGEPKLDSGNTAWMMVATAFVMLMTPAGLALFYAGMTR...FNL')
ID: tr|B9L862|B9L862_NAUPA
Name: tr|B9L862|B9L862_NAUPA
Description: tr|B9L862|B9L862_NAUPA Ammonium transporter OS=Nautilia profundicola (strain ATCC BAA-1463 / DSM 18972 / AmH) OX=598659 GN=amt PE=4 SV=1
Number of features: 0
Seq('MDFAWVIDTFFALFAFTLIILMVPGFAMLEAGLVRTKNVTAVLTVNTMIYIVAS...RAI')
ID: tr|D6HAK3|D6HAK3_NEIGO
Name: tr|D6HAK3|D6HAK3_NEIGO
Description: tr|D6HAK3|D6HAK3_NEIGO Ammonium transporter OS=Neisseria gonorrhoeae DGI2 OX=528348 GN=NGMG_00286 PE=3 SV=1
Number of features: 0
Seq('MRYFHIQTRDLFHAQGGTSAKSPRRSGRACAHPGQAPTPPFRKTGPTIKETLIK...HVE')
ID: tr|A0A1D3GAE9|A0A1D3GAE9_NEIGO
Name: tr|A0A1D3GAE9|A0A1D3GAE9_NEIGO
Description: tr|A0A1D3GAE9|A0A1D3GAE9_NEIGO Ammonium transporter OS=Neisseria gonorrhoeae OX=485 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKHIWAASLLPASLSAEPLNWWKPYSAVNSGDTAWVMTAAALVLLMTLPGLAL...HVE')
ID: tr|B4RJL6|B4RJL6_NEIG2
Name: tr|B4RJL6|B4RJL6_NEIG2
Description: tr|B4RJL6|B4RJL6_NEIG2 Ammonium transporter OS=Neisseria gonorrhoeae (strain NCCP11945) OX=521006 GN=NGK_0326 PE=3 SV=1
Number of features: 0
Seq('MRYFHIQTRDLFHAQGGTSAKSPRRSGRACAHPGQAPTPPFRKTGPTIKETLIK...HVE')
ID: tr|Q5FA36|Q5FA36_NEIG1
Name: tr|Q5FA36|Q5FA36_NEIG1
Description: tr|Q5FA36|Q5FA36_NEIG1 Ammonium transporter OS=Neisseria gonorrhoeae (strain ATCC 700825 / FA 1090) OX=242231 GN=NGO_0198 PE=3 SV=2
Number of features: 0
Seq('MKKHIWAASLLPASLSAEPLNWWKPYSAVNSGDTAWVMTAAALVLLMTLPGLAL...HVE')

ID: tr|A7SGD4|A7SGD4_NEMVE
Name: tr|A7SGD4|A7SGD4_NEMVE
Description: tr|A7SGD4|A7SGD4_NEMVE Ammonium transporter (Fragment) OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g50474 PE=3 SV=1
Number of features: 0
Seq('WDDAIWILTCSFIIFTMQSGFGLLESGMVSRKHEINILVKNIADVLFGGLAFWM...SQE')
ID: tr|A7RNC3|A7RNC3_NEMVE
Name: tr|A7RNC3|A7RNC3_NEMVE
Description: tr|A7RNC3|A7RNC3_NEMVE Ammonium transporter (Fragment) OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g87550 PE=3 SV=1
Number of features: 0
Seq('DDATWVMSSAFIIFTMQSGFGLLESGMVSRKNEVNIMVKNVVDVIFGGLSFWAF...SKI')
ID: tr|A7SQ16|A7SQ16_NEMVE
Name: tr|A7SQ16|A7SQ16_NEMVE
Description: tr|A7SQ16|A7SQ16_NEMVE Ammonium transporter (Fragment) OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g126819 PE=2 SV=1
Number of features: 0
Seq('MNKSNLTSASPPADQRDIIVPDDATWILTSAFIIFTMQSGFGLLEAGMVSKKNE...HGI')
ID: tr|A7S3L2|A7S3L2_NEMVE
Name: tr|A7S3L2|A7S3L2_NEMVE
Description: tr|A7S3L2|A7S3L2_NEMVE Ammonium transporter OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g206265 PE=2 SV=1
Number of features: 0
Seq('MKINGTIPPSWNFSTTPFITNTTEYPTVHKSYTEISSDDATWILTSAFIIFTMQ...PMI')
ID: tr|A7S731|A7S731_NEMVE
Name: tr|A7S731|A7S731_NEMVE
Description: tr|A7S731|A7S731_NEMVE Ammonium transporter OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g207836 PE=2 SV=1
Number of features: 0
Seq('MANNTTNTTLTPPPMEYPMNLRPDDATWILTSAFIIFTMQSGFGLLESGMVSRK...LVN')
ID: tr|A7SED8|A7SED8_NEMVE
Name: tr|A7SED8|A7SED8_NEMVE
Description: tr|A7SED8|A7SED8_NEMVE Ammonium transporter AmtB-like domain-containing protein OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g115127 PE=3 SV=1
Number of features: 0
Seq('MSRPTFTILTILLQVLFVVIFAIFGEYGDDARPNHKRPNPGAAGINAVNIYYPM...SKC')
ID: tr|A7SED7|A7SED7_NEMVE
Name: tr|A7SED7|A7SED7_NEMVE
Description: tr|A7SED7|A7SED7_NEMVE Ammonia transporter OS=Nematostella vectensis OX=45351 GN=NEMVEDRAFT_v1g115269 PE=2 SV=1
Number of features: 0
Seq('MSRPTFTILTILLQVLFVVIFAIFGEYGDDARPNHKRPNPGAAGINAVNIYYPM...YIL')
ID: tr|A0A1E5TK21|A0A1E5TK21_9STAP
Name: tr|A0A1E5TK21|A0A1E5TK21_9STAP
Description: tr|A0A1E5TK21|A0A1E5TK21_9STAP Ammonium transporter OS=Staphylococcus equorum OX=246432 GN=ASS94_06110 PE=3 SV=1
Number of features: 0
Seq('MNMNDVLFLFLCTLLVWLMTPGLSLFYGGLVQSKNVLNTIMQSMSAIVVVTFAW...KRL')
ID: tr|A0A6A1TYJ4|A0A6A1TYJ4_NEOGA
Name: tr|A0A6A1TYJ4|A0A6A1TYJ4_NEOGA
Description: tr|A0A6A1TYJ4|A0A6A1TYJ4_NEOGA Ammonium transporter OS=Neorhizobium galegae OX=399 GN=F4V91_20155 PE=3 SV=1
Number of features: 0
Seq('MQFNRISTLGRVGAAAAALLAPAVAFAQTAAAPAAAAAAAPAMTMDKGDNTWML...HAS')
ID: tr|A0A0T7FAP8|A0A0T7FAP8_NEOGA
Name: tr|A0A0T7FAP8|A0A0T7FAP8_NEOGA
Description: tr|A0A0T7FAP8|A0A0T7FAP8_NEOGA Ammonium transporter OS=Neorhizobium galegae bv. officinalis OX=323656 GN=NGAL_HAMBI1145_08800 PE=3 SV=1
Number of features: 0
Seq('MQFNRISTLGRLSAAAAALLAPAVAFAQTAAAPAAEAAAAAPAMTVDKGDTTWM...YHS')
ID: tr|A0A0T7GZ59|A0A0T7GZ59_NEOGA
Name: tr|A0A0T7GZ59|A0A0T7GZ59_NEOGA
Description: tr|A0A0T7GZ59|A0A0T7GZ59_NEOGA Ammonium transporter OS=Neorhizobium galegae bv. officinalis OX=323656 GN=NGAL_HAMBI1189_45480 PE=3 SV=1
Number of features: 0
Seq('MQFNRISTLGRLSAAAAALLAPAVAFAQTAAAPAAEAAAAAPAMTVDKGDTTWM...YHS')
ID: tr|A0A068SVR1|A0A068SVR1_NEOGA
Name: tr|A0A068SVR1|A0A068SVR1_NEOGA
Description: tr|A0A068SVR1|A0A068SVR1_NEOGA Ammonium transporter OS=Neorhizobium galegae bv. orientalis str. HAMBI 540 OX=1028800 GN=RG540_CH37620 PE=3 SV=1
Number of features: 0
Seq('MQFNRISTLGRVGAAAAALLAPAVAFAQTAAAPAAAAAAAPAMTMDKGDNTWML...HAS')
ID: tr|A0A068TC78|A0A068TC78_NEOGA
Name: tr|A0A068TC78|A0A068TC78_NEOGA
Description: tr|A0A068TC78|A0A068TC78_NEOGA Ammonium transporter OS=Neorhizobium galegae bv. officinalis bv. officinalis str. HAMBI 1141 OX=1028801 GN=RG1141_CH37000 PE=3 SV=1
Number of features: 0
Seq('MQFNRISTLGRVGAAAAALLAPAVAFAQTAAAPAAAAAAPAMTMDKGDNTWMLI...HAS')
ID: tr|A0A2G6JLT9|A0A2G6JLT9_NEPCE
Name: tr|A0A2G6JLT9|A0A2G6JLT9_NEPCE
Description: tr|A0A2G6JLT9|A0A2G6JLT9_NEPCE Ammonium transporter OS=Neptuniibacter caesariensis OX=207954 GN=CSA60_03270 PE=3 SV=1
Number of features: 0
Seq('MENINSAVETLIQSSNTLFILMGAIMVFAMHAGFAFLEVGTVRHKNQVNALVKI...FDR')
ID: tr|A0A7U8C744|A0A7U8C744_NEPCE
Name: tr|A0A7U8C744|A0A7U8C744_NEPCE
Description: tr|A0A7U8C744|A0A7U8C744_NEPCE Putative ammonium transporter OS=Neptuniibacter caesariensis OX=207954 GN=MED92_06731 PE=3 SV=1
Number of features: 0
Seq('MEELLNSTAADVTQLKYALDTFYFLVCGALVMWMAAGFAMLEAGLVRAKNTTEI...SAK')
ID: tr|A0A7U8C2Y6|A0A7U8C2Y6_NEPCE
Name: tr|A0A7U8C2Y6|A0A7U8C2Y6_NEPCE
Description: tr|A0A7U8C2Y6|A0A7U8C2Y6_NEPCE Putative ammonium permease OS=Neptuniibacter caesariensis OX=207954 GN=MED92_12576 PE=3 SV=1
Number of features: 0
Seq('MENVNSAVETLIQSSNTLFILMGAIMVFAMHAGFAFLEVGTVRHKNQVNALVKI...CDN')
ID: tr|A0A7R6PER3|A0A7R6PER3_9GAMM
Name: tr|A0A7R6PER3|A0A7R6PER3_9GAMM
Description: tr|A0A7R6PER3|A0A7R6PER3_9GAMM Ammonium transporter OS=Neptunomonas japonica JAMM 1380 OX=1441457 GN=NEJAP_0219 PE=3 SV=1
Number of features: 0
Seq('MEELLNTTAGDLAQLKYAVDTFYFLICGALVMWMAAGFAMLEAGLVRAKNTTEI...AGK')
ID: tr|A0A7R6PPH5|A0A7R6PPH5_9GAMM
Name: tr|A0A7R6PPH5|A0A7R6PPH5_9GAMM
Description: tr|A0A7R6PPH5|A0A7R6PPH5_9GAMM Ammonium transporter, Amt family OS=Neptunomonas japonica JAMM 1380 OX=1441457 GN=NEJAP_2276 PE=3 SV=1
Number of features: 0
Seq('MDNVNSAVETLVQSSNTLFILMGAIMVFAMHAGFAFLEVGTVRHKNQVNALVKI...TND')
ID: tr|A0A0U1NJW3|A0A0U1NJW3_9RHOB
Name: tr|A0A0U1NJW3|A0A0U1NJW3_9RHOB
Description: tr|A0A0U1NJW3|A0A0U1NJW3_9RHOB Ammonium transporter OS=Nereida ignava OX=282199 GN=amtB_2 PE=3 SV=1
Number of features: 0
Seq('MKFMKSLPLAAAAIALPSMGFAQDAAPGFDEIGPYIMTTLLFLVGGFLVFWMAA...SKG')
ID: tr|A0A0B0E8R7|A0A0B0E8R7_NEUCS
Name: tr|A0A0B0E8R7|A0A0B0E8R7_NEUCS
Description: tr|A0A0B0E8R7|A0A0B0E8R7_NEUCS Ammonium transporter OS=Neurospora crassa OX=5141 GN=GE21DRAFT_1203778 PE=3 SV=1
Number of features: 0
Seq('MAEPEIVPVTEWPDWHANPNGGDPFTQNLNSPYNKGDLCWMLVCTALCWQITPA...KRD')
ID: tr|A0A0B0DML0|A0A0B0DML0_NEUCS
Name: tr|A0A0B0DML0|A0A0B0DML0_NEUCS
Description: tr|A0A0B0DML0|A0A0B0DML0_NEUCS Ammonium transporter OS=Neurospora crassa OX=5141 GN=GE21DRAFT_1315 PE=3 SV=1
Number of features: 0
Seq('MSYSWFGAPTPFNGTTPNGGDSASENLNQWYQSGDQAFILVASCMVLIMIPGIA...TSE')
ID: tr|Q8X0D3|Q8X0D3_NEUCS
Name: tr|Q8X0D3|Q8X0D3_NEUCS
Description: tr|Q8X0D3|Q8X0D3_NEUCS Ammonium transporter OS=Neurospora crassa OX=5141 GN=B14A6.240 PE=3 SV=1
Number of features: 0
Seq('MSSGPVETYEGVAGVANNGGNPLLEDLNRYYSAGDFGWIMTCTALVLLMVPGVG...KQV')
ID: tr|Q1K8A3|Q1K8A3_NEUCR
Name: tr|Q1K8A3|Q1K8A3_NEUCR
Description: tr|Q1K8A3|Q1K8A3_NEUCR Ammonium transporter OS=Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987) OX=367110 GN=NCU01065 PE=3 SV=1
Number of features: 0
Seq('MSSGPVETYEGVAGVANNGGNPLLEDLNRYYSAGDFGWIMTCTALVLLMVPGVG...KQV')
ID: tr|Q7S5K0|Q7S5K0_NEUCR
Name: tr|Q7S5K0|Q7S5K0_NEUCR
Description: tr|Q7S5K0|Q7S5K0_NEUCR Ammonium transporter OS=Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987) OX=367110 GN=NCU05843 PE=3 SV=1
Number of features: 0
Seq('MAEPEIVPVTEWPDWHANPNGGDPFTQNLNSPYDKGDLCWMLVCTALCWQITPA...KRD')
ID: tr|Q7SEH0|Q7SEH0_NEUCR
Name: tr|Q7SEH0|Q7SEH0_NEUCR
Description: tr|Q7SEH0|Q7SEH0_NEUCR Ammonium transporter OS=Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987) OX=367110 GN=NCU03257 PE=3 SV=1
Number of features: 0
Seq('MSYSWFGAPTPFNGTTPNGGDSASENLNQWYQSGDQAFILVASCMVLIMIPGIA...TSE')
ID: tr|A0A0B0DUN5|A0A0B0DUN5_NEUCS
Name: tr|A0A0B0DUN5|A0A0B0DUN5_NEUCS
Description: tr|A0A0B0DUN5|A0A0B0DUN5_NEUCS Major facilitator superfamily (MFS) profile domain-containing protein OS=Neurospora crassa OX=5141 GN=GE21DRAFT_9037 PE=4 SV=1
Number of features: 0
Seq('MSATPRLSSGGHPADPSIEGYREKGMDSSSPSSEGEMDETDLEYAAAQGQRDDL...AKR')
ID: tr|A0A0B0DW36|A0A0B0DW36_NEUCS
Name: tr|A0A0B0DW36|A0A0B0DW36_NEUCS
Description: tr|A0A0B0DW36|A0A0B0DW36_NEUCS MFS general substrate transporter (Fragment) OS=Neurospora crassa OX=5141 GN=GE21DRAFT_3831 PE=4 SV=1
Number of features: 0
Seq('MAQRKHETIVPPAGIPPPQQKRTGLSFVHEVVLVFVLCLAQFLSLAAMNQTVAP...GRN')
ID: tr|Q7S6U7|Q7S6U7_NEUCR
Name: tr|Q7S6U7|Q7S6U7_NEUCR
Description: tr|Q7S6U7|Q7S6U7_NEUCR Drug resistance protein OS=Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987) OX=367110 GN=NCU05492 PE=4 SV=1
Number of features: 0
Seq('MSATPRLSSGGHPADPSIEGYREKGMDSSSPSSEGEMDETDLEYAAAQGQRDDL...AKR')

ID: tr|Q7S343|Q7S343_NEUCR
Name: tr|Q7S343|Q7S343_NEUCR
Description: tr|Q7S343|Q7S343_NEUCR Major facilitator superfamily (MFS) profile domain-containing protein OS=Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987) OX=367110 GN=NCU09172 PE=4 SV=1
Number of features: 0
Seq('MAQRKHETIVPSAKIPPPQRKRTGLSLVHEVVLVFVLCLAQFLSLAAMNQTVAP...QNG')
ID: tr|W0F0I7|W0F0I7_9BACT
Name: tr|W0F0I7|W0F0I7_9BACT
Description: tr|W0F0I7|W0F0I7_9BACT Ammonium transporter OS=Niabella soli DSM 19437 OX=929713 GN=NIASO_09565 PE=3 SV=1
Number of features: 0
Seq('MTRRLAIIPFTLVILVGILCLFCGHNPVKIEQHAEINSGDTAWMLTSAALVLIM...ESL')
ID: tr|G8TK79|G8TK79_NIAKG
Name: tr|G8TK79|G8TK79_NIAKG
Description: tr|G8TK79|G8TK79_NIAKG Ammonium transporter OS=Niastella koreensis (strain DSM 17620 / KACC 11465 / NBRC 106392 / GR20-10) OX=700598 GN=Niako_0112 PE=3 SV=1
Number of features: 0
Seq('MQAKHLSFFRVFSSLTGKSKNVLEPAIQLTRSEKWKLGSTIFLGKMIGLGLVFL...VFS')
ID: tr|G8TK77|G8TK77_NIAKG
Name: tr|G8TK77|G8TK77_NIAKG
Description: tr|G8TK77|G8TK77_NIAKG Ammonium transporter OS=Niastella koreensis (strain DSM 17620 / KACC 11465 / NBRC 106392 / GR20-10) OX=700598 GN=Niako_0110 PE=3 SV=1
Number of features: 0
Seq('MKLSFKNVMPFLVLVVVALAAMFIKPEADHVPGATETAYSAADIAWVLVSTALV...AEF')
ID: tr|A0A1H4KAQ7|A0A1H4KAQ7_9HYPH
Name: tr|A0A1H4KAQ7|A0A1H4KAQ7_9HYPH
Description: tr|A0A1H4KAQ7|A0A1H4KAQ7_9HYPH Ammonium transporter OS=Nitratireductor aquibiodomus OX=204799 GN=SAMN05216452_2097 PE=3 SV=1
Number of features: 0
Seq('MMYRTLKSAAGPLALGGLALAAMSFPALAQESAEAAPEFASASETAFIFNTLLF...HGR')
ID: tr|I5C044|I5C044_9HYPH
Name: tr|I5C044|I5C044_9HYPH
Description: tr|I5C044|I5C044_9HYPH Ammonium transporter OS=Nitratireductor aquibiodomus RA22 OX=1189611 GN=A33O_09359 PE=3 SV=1
Number of features: 0
Seq('MENQMMYRTLKSAAGPLALGGLALATMSFPALAQEAAEAAPEFASASETAFIFN...HGR')
ID: tr|A0A063Y780|A0A063Y780_9GAMM
Name: tr|A0A063Y780|A0A063Y780_9GAMM
Description: tr|A0A063Y780|A0A063Y780_9GAMM Ammonium transporter OS=Nitrincola lacisaponensis OX=267850 GN=ADINL_1213 PE=3 SV=1
Number of features: 0
Seq('MDSMILELGYALDTFYFLMCTALVMWMAAGFAMLEAGLVRSKNTVEILNKNVLL...ATS')
ID: tr|A0A063Y394|A0A063Y394_9GAMM
Name: tr|A0A063Y394|A0A063Y394_9GAMM
Description: tr|A0A063Y394|A0A063Y394_9GAMM Ammonium transporter OS=Nitrincola lacisaponensis OX=267850 GN=ADINL_1908 PE=4 SV=1
Number of features: 0
Seq('MDELQPPSLEELQALIEMTNTLNMEIFYWWCTALMVLIHAGFLSYEIGASRLKN...KLA')
ID: tr|I5BYV5|I5BYV5_9BACT
Name: tr|I5BYV5|I5BYV5_9BACT
Description: tr|I5BYV5|I5BYV5_9BACT Ammonium transporter OS=Nitritalea halalkaliphila LW7 OX=1189621 GN=A3SI_14996 PE=3 SV=1
Number of features: 0
Seq('MNQEIFTINNLWILVATILVFIMHLGFASLEAGLTRSKNTVNILFKNTLIPAIG...KQG')
ID: tr|Q1QS12|Q1QS12_NITHX
Name: tr|Q1QS12|Q1QS12_NITHX
Description: tr|Q1QS12|Q1QS12_NITHX Ammonium transporter OS=Nitrobacter hamburgensis (strain DSM 10229 / NCIMB 13809 / X14) OX=323097 GN=Nham_0084 PE=3 SV=1
Number of features: 0
Seq('MRFERPARAGLAIAAILGAAGLAGFADTALAQTAVAVAPAATSPPKIDSGDTAW...VVQ')
ID: tr|A4BMY5|A4BMY5_9GAMM
Name: tr|A4BMY5|A4BMY5_9GAMM
Description: tr|A4BMY5|A4BMY5_9GAMM Ammonium transporter OS=Nitrococcus mobilis Nb-231 OX=314278 GN=NB231_09038 PE=3 SV=1
Number of features: 0
Seq('MALLLAMCLPWCAPLAATAAGEVDSGDTAWMLTATALVLLMTIPGLSLFYAGMV...YNL')
ID: tr|Q82X47|Q82X47_NITEU
Name: tr|Q82X47|Q82X47_NITEU
Description: tr|Q82X47|Q82X47_NITEU Ammonium transporter family OS=Nitrosomonas europaea (strain ATCC 19718 / CIP 103999 / KCTC 2705 / NBRC 14298) OX=228410 GN=Rh50 PE=1 SV=1
Number of features: 0
Seq('MSKHLCFTAFSSIALFLLCFSSWASAVAPAEINEARLVAQYNYSINILAMLLVG...SEG')
ID: tr|Q5YL87|Q5YL87_NITER
Name: tr|Q5YL87|Q5YL87_NITER
Description: tr|Q5YL87|Q5YL87_NITER Rh-like protein OS=Nitrosomonas europaea OX=915 PE=2 SV=1
Number of features: 0
Seq('MSKHLCFTAFSSIALFLLCFSSWASAVAPAEINEARLVAQYNYSINILAMLLVG...SEG')
ID: tr|A0A060HN92|A0A060HN92_9ARCH
Name: tr|A0A060HN92|A0A060HN92_9ARCH
Description: tr|A0A060HN92|A0A060HN92_9ARCH Ammonium transporter OS=Nitrososphaera viennensis EN76 OX=926571 GN=amt3 PE=3 SV=1
Number of features: 0
Seq('MPIDTGDTTWMLISTGLVMLMTPALGFFEAGLIRSKNSLSVLMQTFSGLAILST...YVT')
ID: tr|A0A060HFT5|A0A060HFT5_9ARCH
Name: tr|A0A060HFT5|A0A060HFT5_9ARCH
Description: tr|A0A060HFT5|A0A060HFT5_9ARCH Ammonium transporter OS=Nitrososphaera viennensis EN76 OX=926571 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MNADSKAKSLLSFRLGLASLAAVVMALVAVGYTGSAFAYAPDDPAVPYHCWQTN...VTE')
ID: tr|A0A060HSP0|A0A060HSP0_9ARCH
Name: tr|A0A060HSP0|A0A060HSP0_9ARCH
Description: tr|A0A060HSP0|A0A060HSP0_9ARCH Ammonium transporter OS=Nitrososphaera viennensis EN76 OX=926571 GN=amt2 PE=3 SV=1
Number of features: 0
Seq('MSKPDWHRLYTIAIVAVAFLVVLGLLQQQHAFAYAPDDPAVPYHCWQTNEDGTF...VTE')
ID: tr|A0A977NL98|A0A977NL98_9ARCH
Name: tr|A0A977NL98|A0A977NL98_9ARCH
Description: tr|A0A977NL98|A0A977NL98_9ARCH Ammonium transporter OS=Nitrososphaera viennensis OX=1034015 GN=NWT39_11750 PE=3 SV=1
Number of features: 0
Seq('MPIDTGDTTWMLISTGLVMLMTPALGFFEAGLIRSKNSLSVLMQTFSGLAILST...YVT')
ID: tr|A0A977NM15|A0A977NM15_9ARCH
Name: tr|A0A977NM15|A0A977NM15_9ARCH
Description: tr|A0A977NM15|A0A977NM15_9ARCH Ammonium transporter OS=Nitrososphaera viennensis OX=1034015 GN=NWT39_01155 PE=3 SV=1
Number of features: 0
Seq('MALVAVGYTGSAFAYAPDDPAVPYHCWQTNEDGTFVIQTGEDGSQNLVPCEINT...VTE')
ID: tr|A0A977NL43|A0A977NL43_9ARCH
Name: tr|A0A977NL43|A0A977NL43_9ARCH
Description: tr|A0A977NL43|A0A977NL43_9ARCH Ammonium transporter OS=Nitrososphaera viennensis OX=1034015 GN=NWT39_10900 PE=3 SV=1
Number of features: 0
Seq('MSKPDWHRLYTIAIVAVAFLVVLGLLQQQHAFAYAPDDPAVPYHCWQTNEDGTF...VTE')
ID: tr|A0A1I7FBM5|A0A1I7FBM5_9PROT
Name: tr|A0A1I7FBM5|A0A1I7FBM5_9PROT
Description: tr|A0A1I7FBM5|A0A1I7FBM5_9PROT Ammonium transporter OS=Nitrosospira multiformis OX=1231 GN=SAMN05216417_101320 PE=4 SV=1
Number of features: 0
Seq('MKKSLCMTLCGTAGFFLLFLSAWASEGGAAPELNEARQVAQYNYVIHILAMLLV...TST')
ID: tr|A0A1H8D0R8|A0A1H8D0R8_9PROT
Name: tr|A0A1H8D0R8|A0A1H8D0R8_9PROT
Description: tr|A0A1H8D0R8|A0A1H8D0R8_9PROT Ammonium transporter OS=Nitrosospira multiformis OX=1231 GN=SAMN05216404_102116 PE=4 SV=1
Number of features: 0
Seq('MKKSLCMTLCGTAGFFLLYLSAWASEGGSAPELNEARQVAQYNYVIHILAMLLV...TST')
ID: tr|A0A1I0AQM4|A0A1I0AQM4_9PROT
Name: tr|A0A1I0AQM4|A0A1I0AQM4_9PROT
Description: tr|A0A1I0AQM4|A0A1I0AQM4_9PROT Ammonium transporter OS=Nitrosospira multiformis OX=1231 GN=SAMN05216412_102358 PE=4 SV=1
Number of features: 0
Seq('MKKSLCMTLCGTAGFFLLYLSAWASEGGTAPELNEARQVAQYNYVIHILAMLLV...TST')
ID: tr|A0A2T5IHP0|A0A2T5IHP0_9PROT
Name: tr|A0A2T5IHP0|A0A2T5IHP0_9PROT
Description: tr|A0A2T5IHP0|A0A2T5IHP0_9PROT Ammonium transporter OS=Nitrosospira multiformis OX=1231 GN=C8R21_10117 PE=4 SV=1
Number of features: 0
Seq('MKKSLCMTLCGTAGFFLLYLSAWASEGGTAPELNEARQVAQYNYVIHILAMLLV...TST')
ID: tr|Q2YBP7|Q2YBP7_NITMU
Name: tr|Q2YBP7|Q2YBP7_NITMU
Description: tr|Q2YBP7|Q2YBP7_NITMU Ammonium transporter OS=Nitrosospira multiformis (strain ATCC 25196 / NCIMB 11849 / C 71) OX=323848 GN=Nmul_A0516 PE=4 SV=1
Number of features: 0
Seq('MKKSLCMTLCGTAGFFLLYLSAWASEGGTAPQLNEARQVAQYNYVIHILAMLLV...TST')
ID: tr|D8PD01|D8PD01_9BACT
Name: tr|D8PD01|D8PD01_9BACT
Description: tr|D8PD01|D8PD01_9BACT Ammonium transporter OS=Nitrospira defluvii OX=330214 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRSAQRKTVVVGVAGALILLAESWGTQVWAQNTPLKVDTGDTAWVLVSSAFVL...AYS')
ID: tr|A0A6G9XJV9|A0A6G9XJV9_NOCBR
Name: tr|A0A6G9XJV9|A0A6G9XJV9_NOCBR
Description: tr|A0A6G9XJV9|A0A6G9XJV9_NOCBR Ammonium transporter OS=Nocardia brasiliensis OX=37326 GN=amt PE=3 SV=1
Number of features: 0
Seq('MPTPLDPAATAWLLVSTALVLLMTPALALFYGGMVRSTGVLNMLMMNFIAIPLV...RDH')
ID: tr|A0A6G9Y3Q0|A0A6G9Y3Q0_NOCBR
Name: tr|A0A6G9Y3Q0|A0A6G9Y3Q0_NOCBR
Description: tr|A0A6G9Y3Q0|A0A6G9Y3Q0_NOCBR Ammonium transporter OS=Nocardia brasiliensis OX=37326 GN=amt PE=3 SV=1
Number of features: 0
Seq('MLASAALVLLMTPGLAFFYGGMVRSKNVLNMIMMSISAMGLVGVLWSLYGFSTA...KEA')
ID: tr|A0A379A6M6|A0A379A6M6_NOCBR
Name: tr|A0A379A6M6|A0A379A6M6_NOCBR
Description: tr|A0A379A6M6|A0A379A6M6_NOCBR Ammonium transporter OS=Nocardia brasiliensis OX=37326 GN=amt_1 PE=3 SV=1
Number of features: 0
Seq('MPTPLDPAATAWLLVSTALVLLMTPALALFYGGMVRSTGVLNMLMMNFIAIPLV...RDH')
ID: tr|A0A379BXA9|A0A379BXA9_NOCBR
Name: tr|A0A379BXA9|A0A379BXA9_NOCBR
Description: tr|A0A379BXA9|A0A379BXA9_NOCBR Ammonium transporter OS=Nocardia brasiliensis OX=37326 GN=amt_2 PE=3 SV=1
Number of features: 0
Seq('MAFPLTGAPDTGDTAWMLASSALVLLMTPGLAFFYGGMVRSKNVLNMIMMSVSA...KEA')
ID: tr|A0A7K2IV20|A0A7K2IV20_9ACTN
Name: tr|A0A7K2IV20|A0A7K2IV20_9ACTN
Description: tr|A0A7K2IV20|A0A7K2IV20_9ACTN Ammonium transporter OS=Nocardiopsis alba OX=53437 GN=amt PE=3 SV=1
Number of features: 0
Seq('MIDTGNTAWLLMSAALVMLMTPGLAFFYGGMARAKSVLNMMLMSFSSIALVSVL...STR')

ID: tr|J7L3W8|J7L3W8_NOCAA
Name: tr|J7L3W8|J7L3W8_NOCAA
Description: tr|J7L3W8|J7L3W8_NOCAA Ammonium transporter OS=Nocardiopsis alba (strain ATCC BAA-2165 / BE74) OX=1205910 GN=amt PE=3 SV=1
Number of features: 0
Seq('MIDTGNTAWLLMSAALVMLMTPGLAFFYGGMARAKSVLNMMLMSFSSIALISVL...STR')
ID: tr|A0ZJU7|A0ZJU7_NODSP
Name: tr|A0ZJU7|A0ZJU7_NODSP
Description: tr|A0ZJU7|A0ZJU7_NODSP Ammonium transporter OS=Nodularia spumigena CCY9414 OX=313624 GN=NSP_25180 PE=3 SV=1
Number of features: 0
Seq('MYKQKSRIKNRRISAIKSAKSIRLNSKIKGFNLAIKQLSPSWQACLPLACLIVL...DKY')
ID: tr|A0A166IS52|A0A166IS52_NODSP
Name: tr|A0A166IS52|A0A166IS52_NODSP
Description: tr|A0A166IS52|A0A166IS52_NODSP Ammonium transporter OS=Nodularia spumigena CENA596 OX=1819295 GN=A2T98_16265 PE=3 SV=1
Number of features: 0
Seq('MYKQKSIIKNRRISAKKSAKSIRLNSKIKGFNLAIKQLSPSWQACLPLACLIVL...DKY')
ID: tr|A0A2S0Q8P1|A0A2S0Q8P1_NODSP
Name: tr|A0A2S0Q8P1|A0A2S0Q8P1_NODSP
Description: tr|A0A2S0Q8P1|A0A2S0Q8P1_NODSP Ammonium transporter OS=Nodularia spumigena UHCC 0039 OX=1914872 GN=BMF81_02833 PE=3 SV=1
Number of features: 0
Seq('MYKQKSRIKNRRISAIKSAKSIRLNSKIKGFNLAIKQLSPSWQACLPLACLIVL...DKY')
ID: tr|A0A7X0DNL6|A0A7X0DNL6_NOVIT
Name: tr|A0A7X0DNL6|A0A7X0DNL6_NOVIT
Description: tr|A0A7X0DNL6|A0A7X0DNL6_NOVIT Ammonium transporter OS=Novispirillum itersonii OX=189 GN=FHS48_002943 PE=3 SV=1
Number of features: 0
Seq('MMSISKRMVSSLPRLSAVAGGAAAGLLAALPAFAEDAPAAPVATLNSGDTAWML...TIH')
ID: tr|A0A7W9ZEG0|A0A7W9ZEG0_NOVIT
Name: tr|A0A7W9ZEG0|A0A7W9ZEG0_NOVIT
Description: tr|A0A7W9ZEG0|A0A7W9ZEG0_NOVIT Amt family ammonium transporter OS=Novispirillum itersonii OX=189 GN=FHS48_000493 PE=3 SV=1
Number of features: 0
Seq('MHAGLDVFFLLIGAAMVLAMHAGFAFLEAGTVRRKNQVNALVKIITDLGVSTVV...LIR')
ID: tr|A0A420WC79|A0A420WC79_9PROT
Name: tr|A0A420WC79|A0A420WC79_9PROT
Description: tr|A0A420WC79|A0A420WC79_9PROT Ammonium transporter OS=Oceanibaculum indicum OX=526216 GN=BCL74_3056 PE=3 SV=1
Number of features: 0
Seq('MMGFNKLAAKLSKGAGLATLVAIPVALTATPAAAEVSAETAFVFNTFSFLICGA...GRG')
ID: tr|K2JVF8|K2JVF8_9PROT
Name: tr|K2JVF8|K2JVF8_9PROT
Description: tr|K2JVF8|K2JVF8_9PROT Ammonium transporter OS=Oceanibaculum indicum P24 OX=1207063 GN=P24_03291 PE=3 SV=1
Number of features: 0
Seq('MMMGFNKLAAKLSKGAGLAALVAIPVALTATPAAAEVSAETAFVFNTFSFLICG...GRG')
ID: tr|A3TVQ9|A3TVQ9_PSEBH
Name: tr|A3TVQ9|A3TVQ9_PSEBH
Description: tr|A3TVQ9|A3TVQ9_PSEBH Ammonium transporter OS=Pseudooceanicola batsensis (strain ATCC BAA-863 / DSM 15984 / KCTC 12145 / HTCC2597) OX=252305 GN=OB2597_10696 PE=3 SV=1
Number of features: 0
Seq('MKLLNTLLPAAALIALPSLGFAQDAEAAAPGFDEIGPYIMTTLLFCMAGFLVFF...SKG')
ID: tr|A0A7C4VLK5|A0A7C4VLK5_9DEIN
Name: tr|A0A7C4VLK5|A0A7C4VLK5_9DEIN
Description: tr|A0A7C4VLK5|A0A7C4VLK5_9DEIN Ammonium transporter OS=Oceanithermus profundus OX=187137 GN=ENK37_08755 PE=3 SV=1
Number of features: 0
Seq('MTRIGTLFLPLLLGAALAAGEPDTGTTAWMLVSTALVLLMTPALAFFYGGLVRQ...GAA')
ID: tr|E4U5Z1|E4U5Z1_OCEP5
Name: tr|E4U5Z1|E4U5Z1_OCEP5
Description: tr|E4U5Z1|E4U5Z1_OCEP5 Ammonium transporter OS=Oceanithermus profundus (strain DSM 14977 / NBRC 100410 / VKM B-2274 / 506) OX=670487 GN=Ocepr_0352 PE=3 SV=1
Number of features: 0
Seq('MMMRLGTLFLFLLPGAALAAGDTDTGTTAWMLVSTALVLLMTPALAFFYGGLVR...GAA')
ID: tr|Q8ERT9|Q8ERT9_OCEIH
Name: tr|Q8ERT9|Q8ERT9_OCEIH
Description: tr|Q8ERT9|Q8ERT9_OCEIH Ammonium transporter OS=Oceanobacillus iheyensis (strain DSM 14371 / CIP 107618 / JCM 11309 / KCTC 3954 / HTE831) OX=221109 GN=OB1211 PE=3 SV=1
Number of features: 0
Seq('MLKKSFLIFTALLLLATPVYAATPTPESLELSVNLIWVMLGAFLVFFMHAGFAM...QSS')
ID: tr|M9RKT6|M9RKT6_9RHOB
Name: tr|M9RKT6|M9RKT6_9RHOB
Description: tr|M9RKT6|M9RKT6_9RHOB Ammonium transporter OS=Octadecabacter arcticus 238 OX=391616 GN=OA238_c01560 PE=3 SV=1
Number of features: 0
Seq('MKLLKTSLVAGALTALPTLALAQDAAPTFDEIGPYIMTTLLFLVAGFLVFFMAA...SKG')
ID: tr|M9RJS5|M9RJS5_9RHOB
Name: tr|M9RJS5|M9RJS5_9RHOB
Description: tr|M9RJS5|M9RJS5_9RHOB Ammonium transporter OS=Octadecabacter arcticus 238 OX=391616 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNGADTAWIIVATALVLFMTLPGLALFYGGLVRARNVLSVFMQCFGIACLMSIL...MSS')
ID: tr|A0A375YPN6|A0A375YPN6_MYCPF
Name: tr|A0A375YPN6|A0A375YPN6_MYCPF
Description: tr|A0A375YPN6|A0A375YPN6_MYCPF Putative ammonium transporter [Octadecabacter arcticus 238] OS=Mycolicibacterium parafortuitum OX=39692 GN=MPP7335_04788 PE=4 SV=1
Number of features: 0
Seq('MTPEVEDALATMASVNNEFFYWMSIALMMLIHAGFLAYEVGASRSKNVLATAMK...EVK')
ID: tr|A0A483BDN6|A0A483BDN6_OENOE
Name: tr|A0A483BDN6|A0A483BDN6_OENOE
Description: tr|A0A483BDN6|A0A483BDN6_OENOE Ammonium transporter OS=Oenococcus oeni OX=1247 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSTANTTFLILASVLVLFMTPGLAFFYGGLGSKKNVVNTMMSVFVMCGLAVVLW...TIS')
ID: tr|D3LBI0|D3LBI0_OENOE
Name: tr|D3LBI0|D3LBI0_OENOE
Description: tr|D3LBI0|D3LBI0_OENOE Ammonium transporter OS=Oenococcus oeni AWRIB429 OX=655225 GN=AWRIB429_1710 PE=3 SV=1
Number of features: 0
Seq('MSTANTTFLILSSVLVLFMTPGLAFFYGGLGSKKNVVNTMMSVFVMCGLAVVLW...TIS')
ID: tr|A0NJ07|A0NJ07_OENOE
Name: tr|A0NJ07|A0NJ07_OENOE
Description: tr|A0NJ07|A0NJ07_OENOE Ammonium transporter OS=Oenococcus oeni ATCC BAA-1163 OX=379360 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSTANTTFLILSSVLVLFMTPGLAFFYGGLGSKKNVVNTMMSVFVMCGLAVVLW...TIS')
ID: tr|Q04DE4|Q04DE4_OENOB
Name: tr|Q04DE4|Q04DE4_OENOB
Description: tr|Q04DE4|Q04DE4_OENOB Ammonium transporter OS=Oenococcus oeni (strain ATCC BAA-331 / PSU-1) OX=203123 GN=OEOE_1679 PE=3 SV=1
Number of features: 0
Seq('MSTANTTFLILSSVLVLFMTPGLAFFYGGLGSKKNVVNTMMSVFVMCGLAVVLW...TIS')
ID: tr|E4XXT2|E4XXT2_OIKDI
Name: tr|E4XXT2|E4XXT2_OIKDI
Description: tr|E4XXT2|E4XXT2_OIKDI Ammonium transporter AmtB-like domain-containing protein OS=Oikopleura dioica OX=34765 GN=GSOID_T00007483001 PE=3 SV=1
Number of features: 0
Seq('MGRDYDFFLVMNACMVLFMQSGFALLEAGSVRAKNVTNILIKNLLDVVVGAIVY...GGS')
ID: tr|E4YA63|E4YA63_OIKDI
Name: tr|E4YA63|E4YA63_OIKDI
Description: tr|E4YA63|E4YA63_OIKDI Ammonium transporter AmtB-like domain-containing protein OS=Oikopleura dioica OX=34765 GN=GSOID_T00030881001 PE=3 SV=1
Number of features: 0
Seq('MKKFGEGVYHDSREQDSVEEVLKSLTLVMNACMVLFMQSGFALIEAGAVRAKNV...TEF')
ID: tr|B1ZSW9|B1ZSW9_OPITP
Name: tr|B1ZSW9|B1ZSW9_OPITP
Description: tr|B1ZSW9|B1ZSW9_OPITP Ammonium transporter OS=Opitutus terrae (strain DSM 11246 / JCM 15787 / PB90-1) OX=452637 GN=Oter_2476 PE=3 SV=1
Number of features: 0
Seq('MPERIGAISDAGIAPAFGRLHMNKAPSLPLRVFALLCLLTLGAFSASAEQTAAT...YIA')
ID: tr|A0A4R8H081|A0A4R8H081_9FIRM
Name: tr|A0A4R8H081|A0A4R8H081_9FIRM
Description: tr|A0A4R8H081|A0A4R8H081_9FIRM Ammonium transporter OS=Orenia marismortui OX=46469 GN=C7959_10570 PE=3 SV=1
Number of features: 0
Seq('MSRRVMVLLTLVLLISLSSVAFAADATAESNAIAIDTIWTLLAAFLVFFMQAGF...SKK')
ID: tr|A0A4R8GSH7|A0A4R8GSH7_9FIRM
Name: tr|A0A4R8GSH7|A0A4R8GSH7_9FIRM
Description: tr|A0A4R8GSH7|A0A4R8GSH7_9FIRM Ammonium transporter OS=Orenia marismortui OX=46469 GN=C7959_1243 PE=3 SV=1
Number of features: 0
Seq('MTLNNLIQSSNVLFLLLGAIMIFAMHAGFAFLEVGSVRKKNQINALVKILTDWA...NAV')
ID: sp|Q84KJ7|AMT21_ORYSJ
Name: sp|Q84KJ7|AMT21_ORYSJ
Description: sp|Q84KJ7|AMT21_ORYSJ Ammonium transporter 2 member 1 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT2-1 PE=2 SV=1
Number of features: 0
Seq('MAAAGAYSASLPAVPDWLNKGDNAWQLTASTLVGIQSMPGLVVLYGSIVKKKWA...IQL')
ID: sp|Q7XQ12|AMT11_ORYSJ
Name: sp|Q7XQ12|AMT11_ORYSJ
Description: sp|Q7XQ12|AMT11_ORYSJ Ammonium transporter 1 member 1 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT1-1 PE=2 SV=1
Number of features: 0
Seq('MATCAADLAPLLGPVAANATDYLCNRFADTTSAVDATYLLFSAYLVFAMQLGFA...NQV')
ID: sp|Q6K9G3|AMT13_ORYSJ
Name: sp|Q6K9G3|AMT13_ORYSJ
Description: sp|Q6K9G3|AMT13_ORYSJ Ammonium transporter 1 member 3 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT1-3 PE=2 SV=1
Number of features: 0
Seq('MATCLDSLGPLLGGAANSTDAANYICNRFTDTSSAVDATYLLFSAYLVFAMQLG...QFV')
ID: sp|Q94JG1|NRT23_ORYSJ
Name: sp|Q94JG1|NRT23_ORYSJ
Description: sp|Q94JG1|NRT23_ORYSJ High-affinity nitrate transporter 2.3 OS=Oryza sativa subsp. japonica OX=39947 GN=NRT2.3 PE=1 SV=1
Number of features: 0
Seq('MEAKPVAMEVEGVEAAGGKPRFRMPVDSDLKATEFWLFSFARPHMASFHMAWFS...AGV')
ID: sp|Q6K9G1|AMT12_ORYSJ
Name: sp|Q6K9G1|AMT12_ORYSJ
Description: sp|Q6K9G1|AMT12_ORYSJ Ammonium transporter 1 member 2 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT1-2 PE=2 SV=1
Number of features: 0
Seq('MATCADTLGPLLGTAAANATDYLCNQFADTTSAVDSTYLLFSAYLVFAMQLGFA...GHV')
ID: sp|P0DKG9|NRT21_ORYSJ
Name: sp|P0DKG9|NRT21_ORYSJ
Description: sp|P0DKG9|NRT21_ORYSJ High-affinity nitrate transporter 2.1 OS=Oryza sativa subsp. japonica OX=39947 GN=NRT2.1 PE=1 SV=1
Number of features: 0
Seq('MDSSTVGAPGSSLHGVTGREPAFAFSTEVGGEDAAAASKFDLPVDSEHKAKTIR...EHA')

ID: sp|P0DKH0|NRT22_ORYSJ
Name: sp|P0DKH0|NRT22_ORYSJ
Description: sp|P0DKH0|NRT22_ORYSJ High-affinity nitrate transporter 2.2 OS=Oryza sativa subsp. japonica OX=39947 GN=NRT2.2 PE=1 SV=1
Number of features: 0
Seq('MDSSTVGAPGSSLHGVTGREPAFAFSTEVGGEDAAAASKFDLPVDSEHKAKTIR...EHA')
ID: sp|Q84KJ6|AMT31_ORYSJ
Name: sp|Q84KJ6|AMT31_ORYSJ
Description: sp|Q84KJ6|AMT31_ORYSJ Ammonium transporter 3 member 1 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT3-1 PE=2 SV=1
Number of features: 0
Seq('MSGDAFNMSVAYQPSGMAVPEWLNKGDNAWQMISATLVGMQSVPGLVILYGSIV...QNV')
ID: sp|Q69T29|AMT33_ORYSJ
Name: sp|Q69T29|AMT33_ORYSJ
Description: sp|Q69T29|AMT33_ORYSJ Ammonium transporter 3 member 3 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT3-3 PE=2 SV=1
Number of features: 0
Seq('MAAGAIPMAYQTTPSSPDWLNKGDNAWQMTSATLVGLQSMPGLVILYGSIVKKK...QNV')
ID: sp|Q8S233|AMT23_ORYSJ
Name: sp|Q8S233|AMT23_ORYSJ
Description: sp|Q8S233|AMT23_ORYSJ Ammonium transporter 2 member 3 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT2-3 PE=2 SV=1
Number of features: 0
Seq('MASPTRPGPYMPRPPAVPEWLNTGDNGWQLAAATFVGLQSMPGLVVLYGSIVKK...IQL')
ID: sp|Q851M9|AMT32_ORYSJ
Name: sp|Q851M9|AMT32_ORYSJ
Description: sp|Q851M9|AMT32_ORYSJ Ammonium transporter 3 member 2 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT3-2 PE=2 SV=1
Number of features: 0
Seq('MSSSATVVPLAYQGNTSASVADWLNKGDNAWQLVAATVVGLQSVPGLVVLYGGV...VVV')
ID: sp|Q8S230|AMT22_ORYSJ
Name: sp|Q8S230|AMT22_ORYSJ
Description: sp|Q8S230|AMT22_ORYSJ Ammonium transporter 2 member 2 OS=Oryza sativa subsp. japonica OX=39947 GN=AMT2-2 PE=2 SV=2
Number of features: 0
Seq('MHLRMASPPQPGPYMPDLPAVPAWLNKGDTAWQLVAATFVGIQSMPGLVVIYGS...IQL')
ID: tr|A0A158URW8|A0A158URW8_ORYSA
Name: tr|A0A158URW8|A0A158URW8_ORYSA
Description: tr|A0A158URW8|A0A158URW8_ORYSA Ammonium transporter OS=Oryza sativa OX=4530 PE=2 SV=1
Number of features: 0
Seq('MSGDAFNMSVAYQPSGMAVPEWLNKGDNAWQMISATLVGMQSVPGLVILYGSIV...QNV')
ID: tr|E1IF27|E1IF27_9CHLR
Name: tr|E1IF27|E1IF27_9CHLR
Description: tr|E1IF27|E1IF27_9CHLR Ammonium transporter OS=Oscillochloris trichoides DG-6 OX=765420 GN=OSCT_1928 PE=3 SV=1
Number of features: 0
Seq('MLMTPALGFFYGGLVRQKNALSTIMHSFFMLGFVSVIWALVGYSLAFSPTIGGF...YQI')
ID: tr|G8R7U9|G8R7U9_OWEHD
Name: tr|G8R7U9|G8R7U9_OWEHD
Description: tr|G8R7U9|G8R7U9_OWEHD Ammonium transporter OS=Owenweeksia hongkongensis (strain DSM 17368 / CIP 108786 / JCM 12287 / NRRL B-23963 / UST20020801) OX=926562 GN=Oweho_2510 PE=3 SV=1
Number of features: 0
Seq('MSRKINFIVLSILVVFCAFTATGYQELSTQIDKADTAWMLVSSAFVLLMTPGLS...QLE')
ID: tr|C3X831|C3X831_OXAFO
Name: tr|C3X831|C3X831_OXAFO
Description: tr|C3X831|C3X831_OXAFO Ammonium transporter OS=Oxalobacter formigenes OXCC13 OX=556269 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKPARVHFDEETVVKALISILLVAGLGVLTGSAFAEEMTVSYGVMVSDPVSQLS...YRY')
ID: tr|C3X1J1|C3X1J1_9BURK
Name: tr|C3X1J1|C3X1J1_9BURK
Description: tr|C3X1J1|C3X1J1_9BURK Ammonium transporter OS=Oxalobacter paraformigenes OX=556268 GN=OFAG_00230 PE=3 SV=1
Number of features: 0
Seq('MKNLCSGMLAAITAGFAGEVLAQDASVVSETATVAVETAVIATVEASSALNPGD...YHY')
ID: tr|A0A9E9LS75|A0A9E9LS75_9BURK
Name: tr|A0A9E9LS75|A0A9E9LS75_9BURK
Description: tr|A0A9E9LS75|A0A9E9LS75_9BURK Ammonium transporter OS=Oxalobacter aliiformigenes OX=2946593 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKNLFSILLAATGLGLAGGAFAQDAVAPAAETTVTVAETAAASAVSALSAGDTA...YHY')
ID: tr|A0A9E9L9J1|A0A9E9L9J1_9BURK
Name: tr|A0A9E9L9J1|A0A9E9L9J1_9BURK
Description: tr|A0A9E9L9J1|A0A9E9L9J1_9BURK Ammonium transporter OS=Oxalobacter aliiformigenes OX=2946593 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKNLFSILLASTGLGLAGGAFAQDAAAPAAETTVTVAETAAASAVSALSAGDTA...YHY')
ID: tr|A0A9E9LXV9|A0A9E9LXV9_9BURK
Name: tr|A0A9E9LXV9|A0A9E9LXV9_9BURK
Description: tr|A0A9E9LXV9|A0A9E9LXV9_9BURK Ammonium transporter OS=Oxalobacter vibrioformis OX=933080 GN=amt PE=3 SV=1
Number of features: 0
Seq('MAQESAVANSVAVVTAGAAEVAQAAPAVLSAGDTAWMLTSTMLVILMIIPGLAL...YRY')
ID: tr|A0A7S4LPL9|A0A7S4LPL9_OXYMA
Name: tr|A0A7S4LPL9|A0A7S4LPL9_OXYMA
Description: tr|A0A7S4LPL9|A0A7S4LPL9_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1697 PE=3 SV=1
Number of features: 0
Seq('MAATVPATVAELAEQLAQMKTDYDEALDTCWILICAALVFFMHAGFTMLETGCV...LKG')
ID: tr|A0A7S4GND2|A0A7S4GND2_OXYMA
Name: tr|A0A7S4GND2|A0A7S4GND2_OXYMA
Description: tr|A0A7S4GND2|A0A7S4GND2_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1701 PE=3 SV=1
Number of features: 0
Seq('MADAAPPTLAELTAQVAQMKADYDEALDTCWILVCAALVFFMHAGFTMLETGCV...HES')
ID: tr|A0A7S4GNJ2|A0A7S4GNJ2_OXYMA
Name: tr|A0A7S4GNJ2|A0A7S4GNJ2_OXYMA
Description: tr|A0A7S4GNJ2|A0A7S4GNJ2_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1698 PE=3 SV=1
Number of features: 0
Seq('MAATVPATVAELAEQLAQMKTDYDEALDTCWILICAALVFFMHAGFTMLETGCV...AQV')
ID: tr|A0A7S4LPS8|A0A7S4LPS8_OXYMA
Name: tr|A0A7S4LPS8|A0A7S4LPS8_OXYMA
Description: tr|A0A7S4LPS8|A0A7S4LPS8_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1702 PE=3 SV=1
Number of features: 0
Seq('MADAAPPTLAELTAQVAQMKADYDEALDTCWILVCAALVFFMHAGFTMLETGCV...AQV')
ID: tr|A0A7S4GMD8|A0A7S4GMD8_OXYMA
Name: tr|A0A7S4GMD8|A0A7S4GMD8_OXYMA
Description: tr|A0A7S4GMD8|A0A7S4GMD8_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1040 PE=3 SV=1
Number of features: 0
Seq('MSFNLDAFCTGLTAASSSSEQAVCALQTIVAGVSETVGGIDAEGITAGVDTFFL...ETA')
ID: tr|A0A7S4GNI0|A0A7S4GNI0_OXYMA
Name: tr|A0A7S4GNI0|A0A7S4GNI0_OXYMA
Description: tr|A0A7S4GNI0|A0A7S4GNI0_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1700 PE=3 SV=1
Number of features: 0
Seq('MADAAPPTLAELTAQVAQMKADYDEALDTCWILVCAALVFFMHAGFTMLETGCV...LKG')
ID: tr|A0A7S4GNF3|A0A7S4GNF3_OXYMA
Name: tr|A0A7S4GNF3|A0A7S4GNF3_OXYMA
Description: tr|A0A7S4GNF3|A0A7S4GNF3_OXYMA Ammonium transporter OS=Oxyrrhis marina OX=2969 GN=OMAR00294_LOCUS1699 PE=3 SV=1
Number of features: 0
Seq('MAATVPATVAELAEQLAQMKTDYDEALDTCWILICAALVFFMHAGFTMLETGCV...HES')
ID: tr|G4H971|G4H971_9BACL
Name: tr|G4H971|G4H971_9BACL
Description: tr|G4H971|G4H971_9BACL Ammonium transporter OS=Paenibacillus lactis 154 OX=743719 GN=PaelaDRAFT_0532 PE=3 SV=1
Number of features: 0
Seq('MKKRWIGLMVGMLALLVFPVNAFAAEEGASNVELTAGLNSVFVFLAALLVFFMQ...PAL')
ID: tr|E4T3F3|E4T3F3_PALPW
Name: tr|E4T3F3|E4T3F3_PALPW
Description: tr|E4T3F3|E4T3F3_PALPW Ammonium transporter OS=Paludibacter propionicigenes (strain DSM 17365 / JCM 13257 / WB4) OX=694427 GN=Palpr_1099 PE=3 SV=1
Number of features: 0
Seq('MKKYLLMMLLMLVTAAASSYIYAEKAPDSTGATTGTAADVTAVTAGKPTLDEVA...LSR')
ID: tr|E4T3F7|E4T3F7_PALPW
Name: tr|E4T3F7|E4T3F7_PALPW
Description: tr|E4T3F7|E4T3F7_PALPW Ammonium transporter OS=Paludibacter propionicigenes (strain DSM 17365 / JCM 13257 / WB4) OX=694427 GN=Palpr_1103 PE=3 SV=1
Number of features: 0
Seq('MKKYILSLIALLTLFSSTLVAQTPAVTAPKIDSGDTAWMIVATAFVLLMSIPGL...NFD')
ID: tr|E4T0A4|E4T0A4_PALPW
Name: tr|E4T0A4|E4T0A4_PALPW
Description: tr|E4T0A4|E4T0A4_PALPW Ammonium transporter OS=Paludibacter propionicigenes (strain DSM 17365 / JCM 13257 / WB4) OX=694427 GN=Palpr_0328 PE=3 SV=1
Number of features: 0
Seq('MLDVGLTTFMILATSLVMLMTPGLAFFYGGLGCKKNILSIMMQSFVSMGISTVL...RQQ')
ID: tr|A0A856LCH5|A0A856LCH5_9BURK
Name: tr|A0A856LCH5|A0A856LCH5_9BURK
Description: tr|A0A856LCH5|A0A856LCH5_9BURK Ammonium transporter OS=Pandoraea pnomenusa OX=93220 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKLFAKLLLAAAFLGVTGAVGLGSGAAFAQDASAPAAASEATAPAAAAAAAPA...YHN')
ID: tr|A0A378YR15|A0A378YR15_9BURK
Name: tr|A0A378YR15|A0A378YR15_9BURK
Description: tr|A0A378YR15|A0A378YR15_9BURK Ammonium transporter OS=Pandoraea pnomenusa OX=93220 GN=amtB_1 PE=3 SV=1
Number of features: 0
Seq('MKKLFAKLLLAAAFLGVTGAVGLGSGAAFAQDASAPAAASEAAAPAAAAAAAPA...YHN')
ID: tr|A0A8T8BI10|A0A8T8BI10_9BURK
Name: tr|A0A8T8BI10|A0A8T8BI10_9BURK
Description: tr|A0A8T8BI10|A0A8T8BI10_9BURK Ammonium transporter OS=Pandoraea fibrosis OX=1891094 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKLLAKLLLAAAFLGVAGTVSLGSTAALAQDASAPAAASEAASPAAAAAAASA...YHN')
ID: tr|A0A378YY10|A0A378YY10_9BURK
Name: tr|A0A378YY10|A0A378YY10_9BURK
Description: tr|A0A378YY10|A0A378YY10_9BURK Ammonia transporter OS=Pandoraea pnomenusa OX=93220 GN=amtB_2 PE=4 SV=1
Number of features: 0
Seq('MPNTNTPGDVLFLLLGAILVLAMHAGFAFLELGTVRKKNQVNALVKILTDFAVS...TNW')
ID: tr|A0A8T8BK87|A0A8T8BK87_9BURK
Name: tr|A0A8T8BK87|A0A8T8BK87_9BURK
Description: tr|A0A8T8BK87|A0A8T8BK87_9BURK Ammonium transporter OS=Pandoraea fibrosis OX=1891094 GN=PJ20_007680 PE=4 SV=1
Number of features: 0
Seq('MPNSNTPGDVLFLLLGAILVLAMHAGFAFLELGTVRKKNQVNALVKILTDFAVS...TNW')

ID: tr|A0A379A0S9|A0A379A0S9_9HYPH
Name: tr|A0A379A0S9|A0A379A0S9_9HYPH
Description: tr|A0A379A0S9|A0A379A0S9_9HYPH Ammonia transporter OS=Pannonibacter phragmitetus OX=121719 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKKSFAYAAIGMAVLGLMADPGLAQTAAPAATEAPAAAAEAPVYALAADTAYIF...QRL')
ID: tr|A0A0H3KTD3|A0A0H3KTD3_PANAA
Name: tr|A0A0H3KTD3|A0A0H3KTD3_PANAA
Description: tr|A0A0H3KTD3|A0A0H3KTD3_PANAA Ammonium transporter OS=Pantoea ananatis (strain AJ13355) OX=932677 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MGWKKMNKMLTKLGLTSLALLPSLAMAAAPAVADKADNAFMMICTALVLFMSIP...YNH')
ID: tr|D4GLQ6|D4GLQ6_PANAM
Name: tr|D4GLQ6|D4GLQ6_PANAM
Description: tr|D4GLQ6|D4GLQ6_PANAM Ammonium transporter OS=Pantoea ananatis (strain LMG 20103) OX=706191 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MMGWKKMNKMLTKLGLTSLALLPSLAMAAAPAVADKADNAFMMICTALVLFMSI...YNH')
ID: tr|A0A6G6JU01|A0A6G6JU01_9GAMM
Name: tr|A0A6G6JU01|A0A6G6JU01_9GAMM
Description: tr|A0A6G6JU01|A0A6G6JU01_9GAMM Ammonium transporter OS=Pantoea stewartii OX=66269 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNKMLTKLGLTSLALLPSLAMAAPAVADKADNAFMMICTALVLFMSIPGIALFY...YNQ')
ID: tr|A0A7K0HBQ0|A0A7K0HBQ0_9BACT
Name: tr|A0A7K0HBQ0|A0A7K0HBQ0_9BACT
Description: tr|A0A7K0HBQ0|A0A7K0HBQ0_9BACT Ammonium transporter OS=Parabacteroides distasonis OX=823 GN=amt PE=3 SV=1
Number of features: 0
Seq('MDTTYTITDLALSLDTVWMLLAAMLVFFMQPGFALVEAGFTRTKNTANILMKNL...YNN')
ID: tr|A0A1D2JK63|A0A1D2JK63_PARBR
Name: tr|A0A1D2JK63|A0A1D2JK63_PARBR
Description: tr|A0A1D2JK63|A0A1D2JK63_PARBR Ammonium transporter OS=Paracoccidioides brasiliensis OX=121759 GN=ACO22_01877 PE=3 SV=1
Number of features: 0
Seq('MSASKGPFAPDYASYNWTGAPSNFNLTTNANLGGNSRVENLNKWFQSGDQAYIL...GEK')
ID: tr|C1G973|C1G973_PARBD
Name: tr|C1G973|C1G973_PARBD
Description: tr|C1G973|C1G973_PARBD Ammonium transporter OS=Paracoccidioides brasiliensis (strain Pb18) OX=502780 GN=PADG_03809 PE=3 SV=1
Number of features: 0
Seq('MSASKGPFAPDYASYNWTGAPSNFNLTTNANLGGNSRVENLNKWFQSGDQAYIL...GEK')
ID: tr|C0S0W9|C0S0W9_PARBP
Name: tr|C0S0W9|C0S0W9_PARBP
Description: tr|C0S0W9|C0S0W9_PARBP Ammonium transporter OS=Paracoccidioides brasiliensis (strain Pb03) OX=482561 GN=PABG_01234 PE=3 SV=1
Number of features: 0
Seq('MSASKGPFAPDYASYNWTGAPSNFNLTTNANLGGNSRVENLNKWFQSGDQAYIL...GEK')
ID: tr|C1GR74|C1GR74_PARBA
Name: tr|C1GR74|C1GR74_PARBA
Description: tr|C1GR74|C1GR74_PARBA Ammonium transporter OS=Paracoccidioides lutzii (strain ATCC MYA-826 / Pb01) OX=502779 GN=PAAG_01019 PE=3 SV=2
Number of features: 0
Seq('MSVSKAPFAPDYASYNWTGAPSNFNLTTNADLGGNSRVENLNKWFQSGDQAYIL...GGK')
ID: tr|A0A533I6R2|A0A533I6R2_PARDE
Name: tr|A0A533I6R2|A0A533I6R2_PARDE
Description: tr|A0A533I6R2|A0A533I6R2_PARDE Ammonium transporter OS=Paracoccus denitrificans OX=266 GN=DI616_06370 PE=3 SV=1
Number of features: 0
Seq('MRKIFPLAIALALAAGAAHAQDAAPVPDKGDTTWMLLSGILVMMMTIPGLALFY...AYN')
ID: tr|A1B3N0|A1B3N0_PARDP
Name: tr|A1B3N0|A1B3N0_PARDP
Description: tr|A1B3N0|A1B3N0_PARDP Ammonium transporter OS=Paracoccus denitrificans (strain Pd 1222) OX=318586 GN=Pden_2032 PE=3 SV=1
Number of features: 0
Seq('MMRPTAIKPMIPALALPLIGLAMPVLAQDAEAPAATIEAVVEAVAPIVDKGDTT...YNN')
ID: tr|A0CBN6|A0CBN6_PARTE
Name: tr|A0CBN6|A0CBN6_PARTE
Description: tr|A0CBN6|A0CBN6_PARTE Chromosome undetermined scaffold_165, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00036986001 PE=4 SV=1
Number of features: 0
Seq('MYLRPAINIFKAMDLAVAYRSIPAPSHPDIDWVMITSFSAQLTILGFAFIGSGA...SSN')
ID: tr|A0DZ27|A0DZ27_PARTE
Name: tr|A0DZ27|A0DZ27_PARTE
Description: tr|A0DZ27|A0DZ27_PARTE Chromosome undetermined scaffold_7, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00003263001 PE=4 SV=1
Number of features: 0
Seq('MQQHYLDSPNTANPPPSAPNPSAGATGGSHLDEDWLLIAGIVLAFSQLGFGFLE...VSH')
ID: tr|A0BIN7|A0BIN7_PARTE
Name: tr|A0BIN7|A0BIN7_PARTE
Description: tr|A0BIN7|A0BIN7_PARTE Chromosome undetermined scaffold_11, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00004776001 PE=4 SV=1
Number of features: 0
Seq('MGHLFRHQEGEAAPPPAIANIPAPQASTIDYDWILISGFIIVLTQVGFAFIEAG...GFR')
ID: tr|A0BJ48|A0BJ48_PARTE
Name: tr|A0BJ48|A0BJ48_PARTE
Description: tr|A0BJ48|A0BJ48_PARTE Chromosome undetermined scaffold_11, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00004938001 PE=4 SV=1
Number of features: 0
Seq('MQQHYLDSPNTANPPPVSNPPAGAPGASHLDEDWLLIAGIVLAFSQLGFGFLEA...VSY')
ID: tr|A0DQP0|A0DQP0_PARTE
Name: tr|A0DQP0|A0DQP0_PARTE
Description: tr|A0DQP0|A0DQP0_PARTE Chromosome undetermined scaffold_6, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00002757001 PE=4 SV=1
Number of features: 0
Seq('MGHLFRHQYANGEPPAIANIPAPQATTIDYDWILISGFIIVLTQVGFAFIEAGS...GFL')
ID: tr|A0BNP4|A0BNP4_PARTE
Name: tr|A0BNP4|A0BNP4_PARTE
Description: tr|A0BNP4|A0BNP4_PARTE Chromosome undetermined scaffold_119, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00030800001 PE=4 SV=1
Number of features: 0
Seq('MSSLLRHNQDAAAVPALASIPSPQTTDYDWVLVSGFIVILTQVGFAFIGAGSVR...GFR')
ID: tr|A0E7D8|A0E7D8_PARTE
Name: tr|A0E7D8|A0E7D8_PARTE
Description: tr|A0E7D8|A0E7D8_PARTE Chromosome undetermined scaffold_81, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00023933001 PE=4 SV=1
Number of features: 0
Seq('MALDETWVLSCAFFSILGLLGYSMIAAGAVRYKSVQSAIITILLGGILTILAFY...IFH')
ID: tr|A0EG61|A0EG61_PARTE
Name: tr|A0EG61|A0EG61_PARTE
Description: tr|A0EG61|A0EG61_PARTE Chromosome undetermined scaffold_94, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00026626001 PE=4 SV=1
Number of features: 0
Seq('MALDETWVLSCAFFSVLGLLGYSMIAAGAVRYKSVQSAIITILLGGILTILAFY...IFH')
ID: tr|A0CLK6|A0CLK6_PARTE
Name: tr|A0CLK6|A0CLK6_PARTE
Description: tr|A0CLK6|A0CLK6_PARTE Chromosome undetermined scaffold_20, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00008222001 PE=4 SV=1
Number of features: 0
Seq('MNEQFNQAHYDIKQQITHYEHDLDHFWTTLTGAVVLIMQLGFAFLEGGCVRYRN...QIS')
ID: tr|A0EC09|A0EC09_PARTE
Name: tr|A0EC09|A0EC09_PARTE
Description: tr|A0EC09|A0EC09_PARTE Chromosome undetermined scaffold_89, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00025562001 PE=4 SV=1
Number of features: 0
Seq('MSSLLRHNEDAGGIPALASIPSPQSPDYDWVLVSGFIVILTQVGFAFIGAGSVR...GFK')
ID: tr|A0BE57|A0BE57_PARTE
Name: tr|A0BE57|A0BE57_PARTE
Description: tr|A0BE57|A0BE57_PARTE Chromosome undetermined scaffold_101, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00027856001 PE=4 SV=1
Number of features: 0
Seq('MSTDFSVEDKLGLLENTIDYFWTQFAGIVVLLMQLGFAFLEGGCVRYKNMQSIM...QVL')
ID: tr|A0E040|A0E040_PARTE
Name: tr|A0E040|A0E040_PARTE
Description: tr|A0E040|A0E040_PARTE Chromosome undetermined scaffold_71, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00021825001 PE=4 SV=1
Number of features: 0
Seq('MSHLLRHNEGADPTLSIPSPQPKDYDWVLISGFIVILTQVGFAFIGAGSVRYKN...GFK')
ID: tr|A0EAD9|A0EAD9_PARTE
Name: tr|A0EAD9|A0EAD9_PARTE
Description: tr|A0EAD9|A0EAD9_PARTE Chromosome undetermined scaffold_86, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00024988001 PE=3 SV=1
Number of features: 0
Seq('MTDLGIAIERMEQLKESIDIGYLCICAAFVLLMQVGFAFLEGGCLRYKDMQSIM...LQQ')
ID: tr|A0EGB0|A0EGB0_PARTE
Name: tr|A0EGB0|A0EGB0_PARTE
Description: tr|A0EGB0|A0EGB0_PARTE Chromosome undetermined scaffold_95, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00026675001 PE=3 SV=1
Number of features: 0
Seq('MADLGIAIERMEQLKESIDIGYLCICAAFVLLMQVGFAFLEGGCLRYKDMQSIM...LQQ')
ID: tr|A0E1C2|A0E1C2_PARTE
Name: tr|A0E1C2|A0E1C2_PARTE
Description: tr|A0E1C2|A0E1C2_PARTE Chromosome undetermined scaffold_73, whole genome shotgun sequence OS=Paramecium tetraurelia OX=5888 GN=GSPATT00022258001 PE=3 SV=1
Number of features: 0
Seq('MNHLTGIDAVLNVAQASTPAPSNIDSTWVLITSFSALLTILGFAFISSGAVRYK...IFQ')
ID: tr|A0A1H1U2Q6|A0A1H1U2Q6_9CELL
Name: tr|A0A1H1U2Q6|A0A1H1U2Q6_9CELL
Description: tr|A0A1H1U2Q6|A0A1H1U2Q6_9CELL Ammonium transporter OS=Paraoerskovia marina OX=545619 GN=SAMN04489860_2072 PE=3 SV=1
Number of features: 0
Seq('MVELDTGATAWMLMSASLVLLMTPGLAFFYGGMVRTKSVLNMMMMSFGSIAVVA...VRA')
ID: tr|F3QPR6|F3QPR6_9BACT
Name: tr|F3QPR6|F3QPR6_9BACT
Description: tr|F3QPR6|F3QPR6_9BACT Ammonium transporter OS=Paraprevotella xylaniphila YIT 11841 OX=762982 GN=HMPREF9442_00153 PE=3 SV=1
Number of features: 0
Seq('MDTSVILDSGHTAWMIVATLLVFMMTIPGIALFYGGLVRQKNMLSLVMQSLAIA...YDL')

ID: tr|A0A6I3S3R3|A0A6I3S3R3_9BURK
Name: tr|A0A6I3S3R3|A0A6I3S3R3_9BURK
Description: tr|A0A6I3S3R3|A0A6I3S3R3_9BURK Ammonium transporter OS=Parasutterella excrementihominis OX=487175 GN=amt PE=3 SV=1
Number of features: 0
Seq('MRVTALLLALLSPAAWAAEESAMNAADVSWMMVATTLVLFMTIPGIALFYAGMV...RVE')
ID: tr|F3QNA7|F3QNA7_9BURK
Name: tr|F3QNA7|F3QNA7_9BURK
Description: tr|F3QNA7|F3QNA7_9BURK Ammonium transporter OS=Parasutterella excrementihominis YIT 11859 OX=762966 GN=HMPREF9439_02438 PE=3 SV=1
Number of features: 0
Seq('MRVTALLLALLSPAAWAAEESAMNAADVSWMMVATTLVLFMTIPGIALFYAGMV...RVE')
ID: tr|A7HSP2|A7HSP2_PARL1
Name: tr|A7HSP2|A7HSP2_PARL1
Description: tr|A7HSP2|A7HSP2_PARL1 Ammonium transporter OS=Parvibaculum lavamentivorans (strain DS-1 / DSM 13023 / NCIMB 13966) OX=402881 GN=Plav_1305 PE=3 SV=1
Number of features: 0
Seq('MTDNFRFKALVRSGAAGLAASFALLATAGSAFAQEEAPTLNSGDTAWMLTATAL...VIQ')
ID: tr|A7HT14|A7HT14_PARL1
Name: tr|A7HT14|A7HT14_PARL1
Description: tr|A7HT14|A7HT14_PARL1 Ammonium transporter OS=Parvibaculum lavamentivorans (strain DS-1 / DSM 13023 / NCIMB 13966) OX=402881 GN=Plav_1427 PE=3 SV=1
Number of features: 0
Seq('MGSAAQSIDTIWVLICTILVILMQAGFTCLESGLVRAKNSINVAVKNVMDFCVA...RIA')
ID: tr|A7HSN9|A7HSN9_PARL1
Name: tr|A7HSN9|A7HSN9_PARL1
Description: tr|A7HSN9|A7HSN9_PARL1 Rh family protein/ammonium transporter OS=Parvibaculum lavamentivorans (strain DS-1 / DSM 13023 / NCIMB 13966) OX=402881 GN=Plav_1302 PE=3 SV=1
Number of features: 0
Seq('MDPIESAGAGLSAGGDVFFILMGAILVFAMHSGFAFLEVGTVRHKNQVNALVKI...PGR')
ID: tr|E0TGP9|E0TGP9_PARBH
Name: tr|E0TGP9|E0TGP9_PARBH
Description: tr|E0TGP9|E0TGP9_PARBH Ammonium transporter OS=Parvularcula bermudensis (strain ATCC BAA-594 / HTCC2503 / KCTC 12087) OX=314260 GN=PB2503_13104 PE=3 SV=1
Number of features: 0
Seq('MVNARLSRILATASVASVAIAPAVAQDGAPAPDTVFIFNTLLFLIMGMVVMFMS...PAE')
ID: tr|E0TCV4|E0TCV4_PARBH
Name: tr|E0TCV4|E0TCV4_PARBH
Description: tr|E0TCV4|E0TCV4_PARBH Ammonium transporter OS=Parvularcula bermudensis (strain ATCC BAA-594 / HTCC2503 / KCTC 12087) OX=314260 GN=PB2503_11459 PE=3 SV=1
Number of features: 0
Seq('MSLGRLVSRYSVALVLPALTLSSVAVAQDATPDTSAALDTQFILNSFLFLFGGV...SKA')
ID: tr|C6DB68|C6DB68_PECCP
Name: tr|C6DB68|C6DB68_PECCP
Description: tr|C6DB68|C6DB68_PECCP Ammonium transporter OS=Pectobacterium carotovorum subsp. carotovorum (strain PC1) OX=561230 GN=PC1_1061 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A837DQS9|A0A837DQS9_PECCC
Name: tr|A0A837DQS9|A0A837DQS9_PECCC
Description: tr|A0A837DQS9|A0A837DQS9_PECCC Ammonium transporter OS=Pectobacterium carotovorum subsp. carotovorum OX=555 GN=RC98_06480 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A7T5QRS5|A0A7T5QRS5_PECCA
Name: tr|A0A7T5QRS5|A0A7T5QRS5_PECCA
Description: tr|A0A7T5QRS5|A0A7T5QRS5_PECCA Ammonium transporter OS=Pectobacterium carotovorum OX=554 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAVLLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A7V8TEX2|A0A7V8TEX2_PECCA
Name: tr|A0A7V8TEX2|A0A7V8TEX2_PECCA
Description: tr|A0A7V8TEX2|A0A7V8TEX2_PECCA Ammonium transporter OS=Pectobacterium carotovorum OX=554 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A419AI10|A0A419AI10_PECCA
Name: tr|A0A419AI10|A0A419AI10_PECCA
Description: tr|A0A419AI10|A0A419AI10_PECCA Ammonium transporter OS=Pectobacterium carotovorum OX=554 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKMKKLLSSLGFGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIAL...YNQ')
ID: tr|A0A419AVL2|A0A419AVL2_PECCA
Name: tr|A0A419AVL2|A0A419AVL2_PECCA
Description: tr|A0A419AVL2|A0A419AVL2_PECCA Ammonium transporter OS=Pectobacterium carotovorum OX=554 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKMKKRLSSLGLGVAALLPCWAMAATPTIDKADNAFIMICTALVLFMTIPGIAL...YNQ')
ID: tr|A0A7V8IKS6|A0A7V8IKS6_9GAMM
Name: tr|A0A7V8IKS6|A0A7V8IKS6_9GAMM
Description: tr|A0A7V8IKS6|A0A7V8IKS6_9GAMM Ammonium transporter OS=Pectobacterium fontis OX=2558042 GN=OI69_05020 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A0J6AS72|A0A0J6AS72_9GAMM
Name: tr|A0A0J6AS72|A0A0J6AS72_9GAMM
Description: tr|A0A0J6AS72|A0A0J6AS72_9GAMM Ammonium transporter OS=Pectobacterium peruviense OX=2066479 GN=G033_05915 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A086F0C2|A0A086F0C2_9GAMM
Name: tr|A0A086F0C2|A0A086F0C2_9GAMM
Description: tr|A0A086F0C2|A0A086F0C2_9GAMM Ammonium transporter OS=Pectobacterium brasiliense OX=180957 GN=IW01_03640 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A433P2R5|A0A433P2R5_9GAMM
Name: tr|A0A433P2R5|A0A433P2R5_9GAMM
Description: tr|A0A433P2R5|A0A433P2R5_9GAMM Ammonium transporter OS=Pectobacterium polaris OX=2042057 GN=KHDHEBDM_00788 PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPTWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A7V8TJ53|A0A7V8TJ53_9GAMM
Name: tr|A0A7V8TJ53|A0A7V8TJ53_9GAMM
Description: tr|A0A7V8TJ53|A0A7V8TJ53_9GAMM Ammonium transporter OS=Pectobacterium brasiliense OX=180957 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|A0A221TCD6|A0A221TCD6_9GAMM
Name: tr|A0A221TCD6|A0A221TCD6_9GAMM
Description: tr|A0A221TCD6|A0A221TCD6_9GAMM Ammonium transporter OS=Pectobacterium versatile OX=2488639 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKLLSSLGLGVAALLPSWAMAATPTIDKADNAFIMICTALVLFMTIPGIALFY...YNQ')
ID: tr|E0VUA6|E0VUA6_PEDHC
Name: tr|E0VUA6|E0VUA6_PEDHC
Description: tr|E0VUA6|E0VUA6_PEDHC Ammonium transporter OS=Pediculus humanus subsp. corporis OX=121224 GN=8229983 PE=3 SV=1
Number of features: 0
Seq('MEFSNNENQTEKDIPIIYQLNQEDTNWLMTSSFIIFTMQTGFGLLESGCISLKN...TDS')
ID: tr|G4R7P1|G4R7P1_PELHB
Name: tr|G4R7P1|G4R7P1_PELHB
Description: tr|G4R7P1|G4R7P1_PELHB Ammonium transporter OS=Pelagibacterium halotolerans (strain DSM 22347 / JCM 15775 / CGMCC 1.7692 / B2) OX=1082931 GN=KKY_3314 PE=3 SV=1
Number of features: 0
Seq('MNFKTSKLLGAAALASLLIALPALGQDAEVAEEVVETLSEGVSADVVFILNSFL...EFR')
ID: tr|A0A165MFD1|A0A165MFD1_PELLU
Name: tr|A0A165MFD1|A0A165MFD1_PELLU
Description: tr|A0A165MFD1|A0A165MFD1_PELLU Ammonium transporter OS=Pelodictyon luteolum OX=1100 GN=A3K90_05540 PE=3 SV=1
Number of features: 0
Seq('MKRSTLTSGALSVGAFLALALLSPPLQAAEATADAVNAYAIDNFFIFICAVLVL...TTQ')
ID: tr|A0A165MAC2|A0A165MAC2_PELLU
Name: tr|A0A165MAC2|A0A165MAC2_PELLU
Description: tr|A0A165MAC2|A0A165MAC2_PELLU Ammonium transporter OS=Pelodictyon luteolum OX=1100 GN=A3K90_00590 PE=3 SV=1
Number of features: 0
Seq('MRKRMVTALLMLPFLMQVSATAAAAPEVYTDSGTTSWMLTSTALVLLMIPGLAM...NLN')
ID: tr|Q3B3Q6|Q3B3Q6_CHLL3
Name: tr|Q3B3Q6|Q3B3Q6_CHLL3
Description: tr|Q3B3Q6|Q3B3Q6_CHLL3 Ammonium transporter OS=Chlorobium luteolum (strain DSM 273 / BCRC 81028 / 2530) OX=319225 GN=Plut_1163 PE=3 SV=1
Number of features: 0
Seq('MKRSTLTSGALSVGAFLALALLSPPLQAAEATADAVNAYAIDNFFIFICAVLVL...TTQ')
ID: tr|Q3B6Q2|Q3B6Q2_CHLL3
Name: tr|Q3B6Q2|Q3B6Q2_CHLL3
Description: tr|Q3B6Q2|Q3B6Q2_CHLL3 Ammonium transporter OS=Chlorobium luteolum (strain DSM 273 / BCRC 81028 / 2530) OX=319225 GN=Plut_0089 PE=3 SV=1
Number of features: 0
Seq('MRKRIATAMLMLPVLMQVSATAAAAPEVYTDSGTTSWMLTSTALVLLMIPGLAM...NLN')
ID: tr|A5D4I5|A5D4I5_PELTS
Name: tr|A5D4I5|A5D4I5_PELTS
Description: tr|A5D4I5|A5D4I5_PELTS Ammonium transporter OS=Pelotomaculum thermopropionicum (strain DSM 13744 / JCM 10971 / SI) OX=370438 GN=AmtB PE=3 SV=1
Number of features: 0
Seq('MKNRLLRTASLAAVFLMTVPALAWAEEAAEAVAGAAPVDTGDTAWVLASTALVM...PAL')
ID: tr|C5KTM6|C5KTM6_PERM5
Name: tr|C5KTM6|C5KTM6_PERM5
Description: tr|C5KTM6|C5KTM6_PERM5 Ammonium transporter OS=Perkinsus marinus (strain ATCC 50983 / TXsc) OX=423536 GN=Pmar_PMAR016604 PE=3 SV=1
Number of features: 0
Seq('MVSSTFFMLLMMLIVVTASDDSSIADLVRDYRLLQARVADLEESSRGLQTVTND...GGN')
ID: tr|C5LAG4|C5LAG4_PERM5
Name: tr|C5LAG4|C5LAG4_PERM5
Description: tr|C5LAG4|C5LAG4_PERM5 Ammonium transporter OS=Perkinsus marinus (strain ATCC 50983 / TXsc) OX=423536 GN=Pmar_PMAR006230 PE=3 SV=1
Number of features: 0
Seq('MVVLYMKVVILASFIAASVLPDASTEITMNQRILELEAKTAKLERLLESYGSAP...DSC')

ID: tr|C0QSY0|C0QSY0_PERMH
Name: tr|C0QSY0|C0QSY0_PERMH
Description: tr|C0QSY0|C0QSY0_PERMH Ammonium transporter OS=Persephonella marina (strain DSM 14350 / EX-H1) OX=123214 GN=PERMA_2024 PE=3 SV=1
Number of features: 0
Seq('MNIRLLALFSSLIPAVSFAEEAKLDTGDTAWMIVATAFVVLMSIGGLTLFYGGM...FNL')
ID: tr|C0QTA4|C0QTA4_PERMH
Name: tr|C0QTA4|C0QTA4_PERMH
Description: tr|C0QTA4|C0QTA4_PERMH Ammonium transporter OS=Persephonella marina (strain DSM 14350 / EX-H1) OX=123214 GN=PERMA_0121 PE=3 SV=1
Number of features: 0
Seq('MSIVPADNVWILTATALVFLMSIPGLALFYSGLSKGKSMLNTIMMVMVAFCVVS...EIL')
ID: tr|A9BIZ7|A9BIZ7_PETMO
Name: tr|A9BIZ7|A9BIZ7_PETMO
Description: tr|A9BIZ7|A9BIZ7_PETMO Ammonium transporter OS=Petrotoga mobilis (strain DSM 10674 / SJ95) OX=403833 GN=Pmob_1796 PE=3 SV=1
Number of features: 0
Seq('MKRVWKSLLMMSVAFIVPTVLLADSITMEDVVSSIDTMWTLLAAFLVFFMQAGF...EGE')
ID: tr|A0A1B0ZRL8|A0A1B0ZRL8_9RHOB
Name: tr|A0A1B0ZRL8|A0A1B0ZRL8_9RHOB
Description: tr|A0A1B0ZRL8|A0A1B0ZRL8_9RHOB Ammonium transporter OS=Phaeobacter gallaeciensis OX=60890 GN=JL2886_01830 PE=3 SV=1
Number of features: 0
Seq('MRKLKLSLAATAFAALPGLALAQDAAAETPDINPYIFTTLLFLIGGFLVFWMAA...KAG')
ID: tr|A0A366WYI9|A0A366WYI9_9RHOB
Name: tr|A0A366WYI9|A0A366WYI9_9RHOB
Description: tr|A0A366WYI9|A0A366WYI9_9RHOB Ammonium transporter OS=Phaeobacter gallaeciensis OX=60890 GN=DS909_11935 PE=3 SV=1
Number of features: 0
Seq('MTLMKTLTPAALLIALPSLGWAQDTAVDPNEVALHTKYILTSLLFLMGGFLVFW...SKG')
ID: tr|V9WGS2|V9WGS2_9RHOB
Name: tr|V9WGS2|V9WGS2_9RHOB
Description: tr|V9WGS2|V9WGS2_9RHOB Ammonium transporter AmtB-like domain-containing protein OS=Phaeobacter gallaeciensis DSM 26640 OX=1423144 GN=Gal_00490 PE=3 SV=1
Number of features: 0
Seq('MRKSPLSLAVVTAALALPGLAVAQETATAAPAGAAATDTVFILNSLLFLVGGFL...SPS')
ID: tr|A0A291FN84|A0A291FN84_9RHOB
Name: tr|A0A291FN84|A0A291FN84_9RHOB
Description: tr|A0A291FN84|A0A291FN84_9RHOB Ammonium transporter OS=Phaeobacter piscinae OX=1580596 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MNAADTAWIIVATALVLFMTLPGLALFYGGLVRARNVLSVFMQCYAIACLMSVL...MTS')
ID: tr|A0A366XFS8|A0A366XFS8_9RHOB
Name: tr|A0A366XFS8|A0A366XFS8_9RHOB
Description: tr|A0A366XFS8|A0A366XFS8_9RHOB Ammonium transporter OS=Phaeobacter gallaeciensis OX=60890 GN=DS909_01305 PE=3 SV=1
Number of features: 0
Seq('MNGADTAWIIVATALVLFMTLPGLALFYGGLVRARNVLSVFMHCFAIACLMSIL...MSS')
ID: tr|V9WF46|V9WF46_9RHOB
Name: tr|V9WF46|V9WF46_9RHOB
Description: tr|V9WF46|V9WF46_9RHOB Ammonium transporter OS=Phaeobacter gallaeciensis DSM 26640 OX=1423144 GN=Gal_01929 PE=3 SV=1
Number of features: 0
Seq('MNAADTAWIIVATALVLFMTLPGLALFYGGLVRARNVLSVFMQCYAIACLMSVL...MTS')
ID: tr|A0A291G3C0|A0A291G3C0_9RHOB
Name: tr|A0A291G3C0|A0A291G3C0_9RHOB
Description: tr|A0A291G3C0|A0A291G3C0_9RHOB Ammonium transporter OS=Phaeobacter piscinae OX=1580596 GN=PhaeoP13_02719 PE=3 SV=1
Number of features: 0
Seq('MRKSPLTLAAVTAALALPGLAVAQEAATAAPAGAAATDTVFILNSLLFLVGGFL...SPS')
ID: tr|A0A291FRY6|A0A291FRY6_9RHOB
Name: tr|A0A291FRY6|A0A291FRY6_9RHOB
Description: tr|A0A291FRY6|A0A291FRY6_9RHOB Ammonium transporter OS=Phaeobacter piscinae OX=1580596 GN=PhaeoP36_02734 PE=3 SV=1
Number of features: 0
Seq('MRKSPLTLAAVTVALALPGLAVAQEAATAAPVGAAATDTVFILNSLLFLVGGFL...SPS')
ID: tr|A0A0B4DUR9|A0A0B4DUR9_9RHOB
Name: tr|A0A0B4DUR9|A0A0B4DUR9_9RHOB
Description: tr|A0A0B4DUR9|A0A0B4DUR9_9RHOB Ammonium transporter OS=Leisingera sp. ANG1 OX=1002340 GN=GC1_10460 PE=3 SV=1
Number of features: 0
Seq('MKTLKLPLAALALSALPGLALAQDGPAPGVNPATDTVFILNSLLFLIGGCLVFW...SPS')
ID: tr|A0A0B4DVJ9|A0A0B4DVJ9_9RHOB
Name: tr|A0A0B4DVJ9|A0A0B4DVJ9_9RHOB
Description: tr|A0A0B4DVJ9|A0A0B4DVJ9_9RHOB Ammonium transporter OS=Leisingera sp. ANG1 OX=1002340 GN=GC1_10020 PE=4 SV=1
Number of features: 0
Seq('MPLDMSTIHVQQVTLNSLVQNILYASGIVGAILVVVGLLLIDAGTARRRNLFNS...QHA')
ID: tr|A0A0B4E6X7|A0A0B4E6X7_9RHOB
Name: tr|A0A0B4E6X7|A0A0B4E6X7_9RHOB
Description: tr|A0A0B4E6X7|A0A0B4E6X7_9RHOB Ammonium transporter OS=Leisingera sp. ANG1 OX=1002340 GN=GC1_12015 PE=4 SV=1
Number of features: 0
Seq('MDGNLNALTTVFTEFYYWVTVVFMFLIHVGFCMYEVGASRHRNHMHTLMKNIMI...PAE')
ID: tr|A0A8J9SEP2|A0A8J9SEP2_PHATR
Name: tr|A0A8J9SEP2|A0A8J9SEP2_PHATR
Description: tr|A0A8J9SEP2|A0A8J9SEP2_PHATR Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum OX=2850 GN=PTTT1_LOCUS48645 PE=3 SV=1
Number of features: 0
Seq('VVFAAALVFFMQAGFAMLCAGAVRAKNVQNTMLKNLLDACGAAIAFFTVGYAFA...GGL')
ID: tr|A0A8J9S765|A0A8J9S765_PHATR
Name: tr|A0A8J9S765|A0A8J9S765_PHATR
Description: tr|A0A8J9S765|A0A8J9S765_PHATR Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum OX=2850 GN=PTTT1_LOCUS28228 PE=3 SV=1
Number of features: 0
Seq('STLVLTFAGAIVFLMQAGFAMVCAGAVRTKNVQNAMLKNLLDACGASLAFFSIG...GLA')
ID: tr|B7FTM9|B7FTM9_PHATC
Name: tr|B7FTM9|B7FTM9_PHATC
Description: tr|B7FTM9|B7FTM9_PHATC Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum (strain CCAP 1055/1) OX=556484 GN=PHATRDRAFT_10881 PE=3 SV=1
Number of features: 0
Seq('VVFAAALVFFMQAGFAMLCAGAVRAKNVQNTMLKNLLDACGAAIAFFTVGYAFA...GGL')
ID: tr|B7G0Y1|B7G0Y1_PHATC
Name: tr|B7G0Y1|B7G0Y1_PHATC
Description: tr|B7G0Y1|B7G0Y1_PHATC Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum (strain CCAP 1055/1) OX=556484 GN=PHATRDRAFT_1813 PE=3 SV=1
Number of features: 0
Seq('LNNWFLIIAGALVFFMQSGFAMLCAGCVRKKNVQNTMLKNLLDACGAALGFYVI...HGG')
ID: tr|B7G0Y4|B7G0Y4_PHATC
Name: tr|B7G0Y4|B7G0Y4_PHATC
Description: tr|B7G0Y4|B7G0Y4_PHATC Ammonium transporter OS=Phaeodactylum tricornutum (strain CCAP 1055/1) OX=556484 GN=PHATRDRAFT_27877 PE=3 SV=1
Number of features: 0
Seq('MSFDLDAFCTGLTAASSSSEQAVCALQTIVAGVSKTVGGIDAEGITAGVDTFFL...ETA')
ID: tr|B7FSA7|B7FSA7_PHATC
Name: tr|B7FSA7|B7FSA7_PHATC
Description: tr|B7FSA7|B7FSA7_PHATC Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum (strain CCAP 1055/1) OX=556484 GN=PHATRDRAFT_1862 PE=3 SV=1
Number of features: 0
Seq('STLVLTFAGAIVFLMQAGFAMVCAGAVRTKNVQNAMLKNLLDACGASLAFFSIG...GLA')
ID: tr|B7FW68|B7FW68_PHATC
Name: tr|B7FW68|B7FW68_PHATC
Description: tr|B7FW68|B7FW68_PHATC Ammonium transporter (Fragment) OS=Phaeodactylum tricornutum (strain CCAP 1055/1) OX=556484 GN=PHATRDRAFT_11128 PE=3 SV=1
Number of features: 0
Seq('MEQKQLEGDRNVNRWLMLFSGGLIFFMQTGFAMLCAGCVRKKNVQNTMLKNLLD...HGG')
ID: tr|A0A098S5Y7|A0A098S5Y7_9BACT
Name: tr|A0A098S5Y7|A0A098S5Y7_9BACT
Description: tr|A0A098S5Y7|A0A098S5Y7_9BACT Ammonium transporter OS=Phaeodactylibacter xiamenensis OX=1524460 GN=IX84_20390 PE=3 SV=1
Number of features: 0
Seq('MDQALFTANNVWMLVSTVLVFVMHLGFSALEAGFVQKKNTVNILFKNAMIISIG...LMK')
ID: tr|A0A2W5PER0|A0A2W5PER0_9CAUL
Name: tr|A0A2W5PER0|A0A2W5PER0_9CAUL
Description: tr|A0A2W5PER0|A0A2W5PER0_9CAUL Ammonium transporter OS=Phenylobacterium zucineum OX=284016 GN=DI570_06830 PE=3 SV=1
Number of features: 0
Seq('MLMNFIGKQRLAGLMLAAAMVGAPLASTAFAQEAAPPAAAAAPAAAEAAAPAPE...YHS')
ID: tr|A0A227JQV4|A0A227JQV4_9CAUL
Name: tr|A0A227JQV4|A0A227JQV4_9CAUL
Description: tr|A0A227JQV4|A0A227JQV4_9CAUL Ammonium transporter OS=Phenylobacterium zucineum OX=284016 GN=CGW95_00405 PE=3 SV=1
Number of features: 0
Seq('MATAAPEAAPAAPPEAATPEAATPAAAAPAEAAPAAALLPHQVKLELDSGGTAW...LHE')
ID: tr|Q6LMI6|Q6LMI6_PHOPR
Name: tr|Q6LMI6|Q6LMI6_PHOPR
Description: tr|Q6LMI6|Q6LMI6_PHOPR Ammonium transporter OS=Photobacterium profundum (strain SS9) OX=298386 GN=AMT-2 PE=3 SV=1
Number of features: 0
Seq('MELTTTVTELRYALDTFFFLISGALVMWMAAGFAMLEAGLVRSKNTTEILTKNF...SLK')
ID: tr|Q1Z4I4|Q1Z4I4_9GAMM
Name: tr|Q1Z4I4|Q1Z4I4_9GAMM
Description: tr|Q1Z4I4|Q1Z4I4_9GAMM Ammonium transporter OS=Photobacterium profundum 3TCK OX=314280 GN=P3TCK_24521 PE=3 SV=1
Number of features: 0
Seq('MELTTTVTELRYALDTFFFLISGALVMWMAAGFAMLEAGLVRSKNTTEILTKNF...SLK')
ID: tr|Q1Z695|Q1Z695_9GAMM
Name: tr|Q1Z695|Q1Z695_9GAMM
Description: tr|Q1Z695|Q1Z695_9GAMM Putative ammonium permease OS=Photobacterium profundum 3TCK OX=314280 GN=P3TCK_12211 PE=3 SV=1
Number of features: 0
Seq('MDNISHAVETLVQSSDTLFILLGAIMVLAMHAGFAFLEVGTVRQKNQVNALVKI...SDD')
ID: tr|Q6LKC8|Q6LKC8_PHOPR
Name: tr|Q6LKC8|Q6LKC8_PHOPR
Description: tr|Q6LKC8|Q6LKC8_PHOPR Ammonium permease OS=Photobacterium profundum (strain SS9) OX=298386 GN=MK0053 PE=3 SV=1
Number of features: 0
Seq('MTFVDNISHAVETLVQSSDTLFILLGAIMVLAMHAGFAFLEVGTVRQKNQVNAL...SDD')
ID: tr|A0A2S8QG68|A0A2S8QG68_PHOLU
Name: tr|A0A2S8QG68|A0A2S8QG68_PHOLU
Description: tr|A0A2S8QG68|A0A2S8QG68_PHOLU Ammonium transporter OS=Photorhabdus luminescens OX=29488 GN=C6H69_06535 PE=3 SV=1
Number of features: 0
Seq('MKRQFSVAAGIVASCVPSLSQAAEGVADKADNAFMMICTVLVLFMTIPGIALFY...AYN')
ID: tr|A0A4V2X6C2|A0A4V2X6C2_PHOLU
Name: tr|A0A4V2X6C2|A0A4V2X6C2_PHOLU
Description: tr|A0A4V2X6C2|A0A4V2X6C2_PHOLU Ammonium transporter OS=Photorhabdus luminescens subsp. mexicana OX=2100167 GN=C5468_12010 PE=3 SV=1
Number of features: 0
Seq('MKKQFSVAAGVVASCVPSLSQAAEGVADKADNAFMMICTVLVLFMTIPGIALFY...AYN')

ID: tr|A0A5C4RNH5|A0A5C4RNH5_PHOLU
Name: tr|A0A5C4RNH5|A0A5C4RNH5_PHOLU
Description: tr|A0A5C4RNH5|A0A5C4RNH5_PHOLU Ammonium transporter OS=Photorhabdus luminescens subsp. sonorensis OX=1173677 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKKQFSVAAGVAASCVPSLSQAAEGVADKADNAFMMICTVLVLFMTIPGIALFY...AYN')
ID: tr|A0A6L9JJM6|A0A6L9JJM6_PHOLM
Name: tr|A0A6L9JJM6|A0A6L9JJM6_PHOLM
Description: tr|A0A6L9JJM6|A0A6L9JJM6_PHOLM Ammonium transporter OS=Photorhabdus laumondii subsp. laumondii OX=141679 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRQFSVAASVVASCVPSLSQAAEGVVDKADNAFMMICTVLVLFMTIPGIALFY...AYN')
ID: tr|Q7N0M6|Q7N0M6_PHOLL
Name: tr|Q7N0M6|Q7N0M6_PHOLL
Description: tr|Q7N0M6|Q7N0M6_PHOLL Ammonium transporter OS=Photorhabdus laumondii subsp. laumondii (strain DSM 15139 / CIP 105565 / TT01) OX=243265 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MRHCNSLIEKIDMKRQFSVAASVVASCVPSLSQAAEGVVDKADNAFMMICTVLV...AYN')
ID: tr|C7BJG7|C7BJG7_PHOAA
Name: tr|C7BJG7|C7BJG7_PHOAA
Description: tr|C7BJG7|C7BJG7_PHOAA Ammonium transporter OS=Photorhabdus asymbiotica subsp. asymbiotica (strain ATCC 43949 / 3105-77) OX=553480 GN=PAU_03404 PE=3 SV=1
Number of features: 0
Seq('MKRQFSVAAGVAASCLPSLSQAAEGVADKADNAFMMICTALVLFMTIPGIALFY...AYN')
ID: tr|A0A4R4K1P9|A0A4R4K1P9_9GAMM
Name: tr|A0A4R4K1P9|A0A4R4K1P9_9GAMM
Description: tr|A0A4R4K1P9|A0A4R4K1P9_9GAMM Ammonium transporter OS=Photorhabdus khanii subsp. guanajuatensis OX=2100166 GN=C5467_07635 PE=3 SV=1
Number of features: 0
Seq('MKRQFSVATGVVASFLPSLSQAAEGVADKADNAFMMICTVLVLFMTIPGIALFY...AYN')
ID: tr|A0A1G5PWV0|A0A1G5PWV0_PHOLU
Name: tr|A0A1G5PWV0|A0A1G5PWV0_PHOLU
Description: tr|A0A1G5PWV0|A0A1G5PWV0_PHOLU Ammonium transporter OS=Photorhabdus luminescens OX=29488 GN=SAMN02982990_00500 PE=3 SV=1
Number of features: 0
Seq('MRHCNSLIEKIDMKRKFSVAAGIVASCLPSLSQAAEGVVDKADNAFMMICTVLV...AYN')
ID: tr|A0A0A0CQ38|A0A0A0CQ38_PHOLU
Name: tr|A0A0A0CQ38|A0A0A0CQ38_PHOLU
Description: tr|A0A0A0CQ38|A0A0A0CQ38_PHOLU Ammonium transporter OS=Photorhabdus luminescens OX=29488 GN=KS18_08685 PE=3 SV=1
Number of features: 0
Seq('MAAGIVASCVPSLSQAAEGVADKADNAFMMICTVLVLFMTIPGIALFYGGLLRS...AYN')
ID: tr|A0A2S8R5K1|A0A2S8R5K1_PHOLU
Name: tr|A0A2S8R5K1|A0A2S8R5K1_PHOLU
Description: tr|A0A2S8R5K1|A0A2S8R5K1_PHOLU Ammonium transporter OS=Photorhabdus luminescens OX=29488 GN=C6H65_01980 PE=3 SV=1
Number of features: 0
Seq('MRHCNLLIEKIDVKKRFSVAAGIMVSCVPSLSQAAEGVADKADNAFMMICTVLV...AYN')
ID: tr|A0A2S8QA29|A0A2S8QA29_PHOLU
Name: tr|A0A2S8QA29|A0A2S8QA29_PHOLU
Description: tr|A0A2S8QA29|A0A2S8QA29_PHOLU Ammonium transporter OS=Photorhabdus luminescens OX=29488 GN=C6H66_00315 PE=3 SV=1
Number of features: 0
Seq('MRHCNLLIEKIDVKKRFSVAAGIMVSCVPSLSQAAEGVADKADNAFMMICTVLV...AYN')
ID: tr|I0ICG0|I0ICG0_PHYMF
Name: tr|I0ICG0|I0ICG0_PHYMF
Description: tr|I0ICG0|I0ICG0_PHYMF Ammonium transporter OS=Phycisphaera mikurensis (strain NBRC 102666 / KCTC 22515 / FYK2301M01) OX=1142394 GN=PSMK_07890 PE=3 SV=1
Number of features: 0
Seq('MRRTRGTWLPLLGVGAVAALFAGQAMGQDEAEAVVATADSATQAAADAAFMTNN...GEL')
ID: tr|H3GCZ7|H3GCZ7_PHYRM
Name: tr|H3GCZ7|H3GCZ7_PHYRM
Description: tr|H3GCZ7|H3GCZ7_PHYRM Ammonium transporter OS=Phytophthora ramorum OX=164328 PE=3 SV=1
Number of features: 0
Seq('MLRPNNPSLARLALAATALVALGALAVSAQDTSGSTVTCDVSQYLDSATNECVA...MNV')
ID: tr|H3GCZ5|H3GCZ5_PHYRM
Name: tr|H3GCZ5|H3GCZ5_PHYRM
Description: tr|H3GCZ5|H3GCZ5_PHYRM Ammonium transporter OS=Phytophthora ramorum OX=164328 PE=3 SV=1
Number of features: 0
Seq('MNGYIRAALLVALALVLTSTAVAQSGSGSTVTCLVSQYLDTVTGECIDYKSQGE...APL')
ID: tr|H3G9J8|H3G9J8_PHYRM
Name: tr|H3G9J8|H3G9J8_PHYRM
Description: tr|H3G9J8|H3G9J8_PHYRM Ammonium transporter AmtB-like domain-containing protein OS=Phytophthora ramorum OX=164328 PE=4 SV=1
Number of features: 0
Seq('MYMDVHVMIYIGFGFLMTFLRKYSMSAVSLNFLIAVLALEWGIIAVTMAHQIGG...CHA')
ID: tr|D2R355|D2R355_PIRSD
Name: tr|D2R355|D2R355_PIRSD
Description: tr|D2R355|D2R355_PIRSD Ammonium transporter OS=Pirellula staleyi (strain ATCC 27377 / DSM 6068 / ICPB 4128) OX=530564 GN=Psta_4138 PE=3 SV=1
Number of features: 0
Seq('MSSTLSVVKCSWLALLLLGCATVGWAQEGSSAPPSIEERVTAVEGAASSAALAG...IFL')
ID: tr|D2R647|D2R647_PIRSD
Name: tr|D2R647|D2R647_PIRSD
Description: tr|D2R647|D2R647_PIRSD Ammonium transporter OS=Pirellula staleyi (strain ATCC 27377 / DSM 6068 / ICPB 4128) OX=530564 GN=Psta_4490 PE=3 SV=1
Number of features: 0
Seq('MSRSSFSWAGMFLALLLCTSFAVTAYGQEATPPAETPAAEAPAETPAEPAAETP...EAV')
ID: tr|A0A2Z6CF98|A0A2Z6CF98_PLAAG
Name: tr|A0A2Z6CF98|A0A2Z6CF98_PLAAG
Description: tr|A0A2Z6CF98|A0A2Z6CF98_PLAAG Ammonium transporter OS=Planktothrix agardhii NIES-204 OX=282423 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MMFISKKTTDLGNRRHKNVSRFTAKTNRVISKLQHSRWLSPTWLACIPLTAIIV...SRY')
ID: tr|A0A073CP02|A0A073CP02_PLAAG
Name: tr|A0A073CP02|A0A073CP02_PLAAG
Description: tr|A0A073CP02|A0A073CP02_PLAAG Ammonium transporter OS=Planktothrix agardhii NIVA-CYA 126/8 OX=388467 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MSIHKPNMMFISKKTTDLGNRRHKNVSRFTAKTNRVISKLQHSRWLSPTWLACI...SRY')
ID: tr|A0A1J1JH03|A0A1J1JH03_PLAAG
Name: tr|A0A1J1JH03|A0A1J1JH03_PLAAG
Description: tr|A0A1J1JH03|A0A1J1JH03_PLAAG Ammonium transporter OS=Planktothrix agardhii OX=1160 GN=PLAM_2772 PE=3 SV=1
Number of features: 0
Seq('MSIHKPNMMFISKKTTDLGNRRHKNVSRFTAKTNRVISKLQHSRWLSPTWLACI...SRY')
ID: tr|A0A4V0XUI3|A0A4V0XUI3_PLAAG
Name: tr|A0A4V0XUI3|A0A4V0XUI3_PLAAG
Description: tr|A0A4V0XUI3|A0A4V0XUI3_PLAAG Ammonium transporter OS=Planktothrix agardhii CCAP 1459/11A OX=282420 GN=PA905_18890 PE=3 SV=1
Number of features: 0
Seq('MMFISKKTTDLGNRRHKNVSRFTAKTNRVISKLQHSRWLSPTWLACIPLTAIIV...KSR')
ID: tr|A0A1C7EL50|A0A1C7EL50_9BACL
Name: tr|A0A1C7EL50|A0A1C7EL50_9BACL
Description: tr|A0A1C7EL50|A0A1C7EL50_9BACL Ammonium transporter OS=Planococcus donghaensis OX=414778 GN=BCM40_13925 PE=3 SV=1
Number of features: 0
Seq('MEAVQSSVDMIWVMLGAMLVFFMHAGFAMVESGFTRSKNTLNILMKNMITVSLG...SIS')
ID: tr|E7RJZ0|E7RJZ0_9BACL
Name: tr|E7RJZ0|E7RJZ0_9BACL
Description: tr|E7RJZ0|E7RJZ0_9BACL Ammonium transporter OS=Planococcus donghaensis MPA1U2 OX=933115 GN=GPDM_14051 PE=3 SV=1
Number of features: 0
Seq('MEAVQSSVDMIWVMLGAMLVFFMHAGFAMVESGFTRSKNTLNILMKNMITVSLG...SIS')
ID: tr|A6GJF5|A6GJF5_9BACT
Name: tr|A6GJF5|A6GJF5_9BACT
Description: tr|A6GJF5|A6GJF5_9BACT Ammonium transporter OS=Plesiocystis pacifica SIR-1 OX=391625 GN=PPSIR1_00025 PE=3 SV=1
Number of features: 0
Seq('MFFAGLLLTPGAAWANPEGDPEQALQALELLVNNVWMLVATVLVFAMHLGFATL...RMS')
ID: tr|A1VIG8|A1VIG8_POLNA
Name: tr|A1VIG8|A1VIG8_POLNA
Description: tr|A1VIG8|A1VIG8_POLNA Ammonium transporter OS=Polaromonas naphthalenivorans (strain CJ2) OX=365044 GN=Pnap_0121 PE=3 SV=1
Number of features: 0
Seq('MKKLIASLLLGLSLLGTGATAWAQAPAEAPAATASAPAEAKPDAAAAPASAPAD...YNR')
ID: tr|A1VIM5|A1VIM5_POLNA
Name: tr|A1VIM5|A1VIM5_POLNA
Description: tr|A1VIM5|A1VIM5_POLNA Ammonium transporter OS=Polaromonas naphthalenivorans (strain CJ2) OX=365044 GN=Pnap_0178 PE=3 SV=1
Number of features: 0
Seq('MHAMRWIAVSLFFWLCLGLVTQQARAQAPAGAPTAALAAPALAVSAPPNDASVA...MGT')
ID: tr|A4T0A4|A4T0A4_POLAQ
Name: tr|A4T0A4|A4T0A4_POLAQ
Description: tr|A4T0A4|A4T0A4_POLAQ Ammonium transporter OS=Polynucleobacter asymbioticus (strain DSM 18221 / CIP 109841 / QLW-P1DMWA-1) OX=312153 GN=Pnuc_1956 PE=3 SV=1
Number of features: 0
Seq('MLTWMKRLVAGGAMALAIGATGVIVTSPAHADEVKKPAVTAPAATPAAAEPAPV...YES')
ID: tr|B9IGE2|B9IGE2_POPTR
Name: tr|B9IGE2|B9IGE2_POPTR
Description: tr|B9IGE2|B9IGE2_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_016G121400 PE=3 SV=2
Number of features: 0
Seq('MDAPAYEQVSPAVPSWLNKGDNAWQMIASILVATQSMPGLVILYASIVKKKWAV...INL')
ID: tr|B9HCZ0|B9HCZ0_POPTR
Name: tr|B9HCZ0|B9HCZ0_POPTR
Description: tr|B9HCZ0|B9HCZ0_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_006G102800 PE=3 SV=1
Number of features: 0
Seq('MNASTAYEQVSPAVPSWLNKGDNAWQMTASTLVALQSMPGLVILYASIVKKKWA...INL')
ID: tr|A0A2K2AEV5|A0A2K2AEV5_POPTR
Name: tr|A0A2K2AEV5|A0A2K2AEV5_POPTR
Description: tr|A0A2K2AEV5|A0A2K2AEV5_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_005G106000 PE=3 SV=2
Number of features: 0
Seq('MNFPQGLNPDEGSPEWMNKADSAWQLTATTMVCLQSVPGLVILYGSMVKKKWAV...QRF')
ID: tr|B9GHA5|B9GHA5_POPTR
Name: tr|B9GHA5|B9GHA5_POPTR
Description: tr|B9GHA5|B9GHA5_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_001G305400 PE=3 SV=2
Number of features: 0
Seq('MAALPPNPVPVAYQGGSASVPDWLNKGDNSWQMISATLVGLQSMPGLVILYGSI...QVL')
ID: tr|U5FE59|U5FE59_POPTR
Name: tr|U5FE59|U5FE59_POPTR
Description: tr|U5FE59|U5FE59_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_019G000800 PE=3 SV=1
Number of features: 0
Seq('MAAPPPNPVPVAYQGGLAASVPDWLNKGDNAWQMISATLVGLQSVPGLVILYGS...QVM')

ID: tr|A0A2K1RA77|A0A2K1RA77_POPTR
Name: tr|A0A2K1RA77|A0A2K1RA77_POPTR
Description: tr|A0A2K1RA77|A0A2K1RA77_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_T000200 PE=3 SV=1
Number of features: 0
Seq('MAAPPPNLVPVAYQGGSPSVPDWLNKGDNAWQMISATLVGLQSVPGLVILYGSI...QVM')
ID: tr|A0A2K1RA81|A0A2K1RA81_POPTR
Name: tr|A0A2K1RA81|A0A2K1RA81_POPTR
Description: tr|A0A2K1RA81|A0A2K1RA81_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_T000600 PE=3 SV=1
Number of features: 0
Seq('MAAPPPNPVPVAYRGGLVASVPDWLNKGDNAWQMISATLVGLQSVPGLVILYGS...QVM')
ID: tr|A0A2K1WV98|A0A2K1WV98_POPTR
Name: tr|A0A2K1WV98|A0A2K1WV98_POPTR
Description: tr|A0A2K1WV98|A0A2K1WV98_POPTR Ammonium transporter OS=Populus trichocarpa OX=3694 GN=POPTR_018G033500 PE=3 SV=1
Number of features: 0
Seq('MSNDTAFPPNLLPDEASPEWFNKADNAWQLTAATLVGLQSIPGLMILYGGGVKK...EKT')
ID: tr|A0A8H7U3I1|A0A8H7U3I1_9APHY
Name: tr|A0A8H7U3I1|A0A8H7U3I1_9APHY
Description: tr|A0A8H7U3I1|A0A8H7U3I1_9APHY Ammonium transporter OS=Postia placenta OX=104341 GN=IEO21_03416 PE=3 SV=1
Number of features: 0
Seq('MSSTHPTAWRYDGGDIAFIAICGILVSFMVPGVAFLYSGLSRRKSALSLIWAVA...SHS')
ID: tr|A0A8H7P8U1|A0A8H7P8U1_9APHY
Name: tr|A0A8H7P8U1|A0A8H7P8U1_9APHY
Description: tr|A0A8H7P8U1|A0A8H7P8U1_9APHY Ammonium transporter OS=Postia placenta OX=104341 GN=IEO21_01981 PE=3 SV=1
Number of features: 0
Seq('MVNVTYDASGDLVWYDSSTDTTYVYNLGDIAWVLCSTALVWIMIPGVGFFYSGL...AQS')
ID: tr|A0A1X6N3Q5|A0A1X6N3Q5_9APHY
Name: tr|A0A1X6N3Q5|A0A1X6N3Q5_9APHY
Description: tr|A0A1X6N3Q5|A0A1X6N3Q5_9APHY Ammonium transporter OS=Postia placenta MAD-698-R-SB12 OX=670580 GN=POSPLADRAFT_1055307 PE=3 SV=1
Number of features: 0
Seq('MVNVTYDASGDLVWYDSSTDTTYVYNLGDIAWVLCSTALVWIMIPGVGFFYSGL...AQS')
ID: tr|A0A0G3CP57|A0A0G3CP57_9GAMM
Name: tr|A0A0G3CP57|A0A0G3CP57_9GAMM
Description: tr|A0A0G3CP57|A0A0G3CP57_9GAMM Ammonium transporter OS=Pragia fontium OX=82985 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRFLSTVMLSASAIFPEVTMAAENVADKADNGFMMISTALVLFMCIPGIALFY...YNQ')
ID: tr|A0A660CH85|A0A660CH85_9PSEU
Name: tr|A0A660CH85|A0A660CH85_9PSEU
Description: tr|A0A660CH85|A0A660CH85_9PSEU Ammonium transporter OS=Prauserella rugosa OX=43354 GN=JD82_04790 PE=3 SV=1
Number of features: 0
Seq('MEGNTAWLLTSAALVLLMTPGLAFFYGGMVRSKSVLNMLMMCFGAMGLIGVLWV...STS')
ID: tr|A2C095|A2C095_PROM1
Name: tr|A2C095|A2C095_PROM1
Description: tr|A2C095|A2C095_PROM1 Ammonium transporter OS=Prochlorococcus marinus (strain NATL1A) OX=167555 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTALQSPPRRTTSRLQDASLLNGPMLLLRSIKGFRRSQSWAWLASIPLALLGL...ASS')
ID: tr|A2BP62|A2BP62_PROMS
Name: tr|A2BP62|A2BP62_PROMS
Description: tr|A2BP62|A2BP62_PROMS Ammonium transporter OS=Prochlorococcus marinus (strain AS9601) OX=146891 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSRLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A8I1X2A6|A0A8I1X2A6_PROMR
Name: tr|A0A8I1X2A6|A0A8I1X2A6_PROMR
Description: tr|A0A8I1X2A6|A0A8I1X2A6_PROMR Ammonium transporter OS=Prochlorococcus marinus str. XMU1401 OX=2052594 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSRLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A0A2BBY0|A0A0A2BBY0_PROMR
Name: tr|A0A0A2BBY0|A0A0A2BBY0_PROMR
Description: tr|A0A0A2BBY0|A0A0A2BBY0_PROMR Ammonium transporter OS=Prochlorococcus marinus str. MIT 9401 OX=167551 GN=EV01_0517 PE=3 SV=1
Number of features: 0
Seq('MLWLATVPLALFGLGIFNLSAHAADLPELNAAFLANNLWLLIATILVIFMNAGF...SAK')
ID: tr|A0A0A1ZMZ9|A0A0A1ZMZ9_PROMR
Name: tr|A0A0A1ZMZ9|A0A0A1ZMZ9_PROMR
Description: tr|A0A0A1ZMZ9|A0A0A1ZMZ9_PROMR Ammonium transporter OS=Prochlorococcus marinus str. MIT 9116 OX=167544 GN=EU93_1761 PE=3 SV=1
Number of features: 0
Seq('MLWLATVPLALFGLGIFNLSAHAADFPDLNAQFLANNLWLLIATILVIFMNAGF...SAK')
ID: tr|Q7VDS3|Q7VDS3_PROMA
Name: tr|Q7VDS3|Q7VDS3_PROMA
Description: tr|Q7VDS3|Q7VDS3_PROMA Ammonium transporter OS=Prochlorococcus marinus (strain SARG / CCMP1375 / SS120) OX=167539 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTALQSPPRRRIARLQEVSLLEGPMLLLRSIRGFRSNQSLIWLATVPLALLGL...SSN')
ID: tr|Q7V4T8|Q7V4T8_PROMM
Name: tr|Q7V4T8|Q7V4T8_PROMM
Description: tr|Q7V4T8|Q7V4T8_PROMM Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9313) OX=74547 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MTTAPLPRSRRRTVRLQEASLLEGPMLLLRSIRGFSSNRSLTWLACVPLALFGL...AGN')
ID: tr|A2CCK1|A2CCK1_PROM3
Name: tr|A2CCK1|A2CCK1_PROM3
Description: tr|A2CCK1|A2CCK1_PROM3 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9303) OX=59922 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTAPLPPSRRRTMRLQEASLLEGPMLLLRSIRGFSSNRSITWLACVPFALFGL...AGN')
ID: tr|A3PAY4|A3PAY4_PROM0
Name: tr|A3PAY4|A3PAY4_PROM0
Description: tr|A3PAY4|A3PAY4_PROM0 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9301) OX=167546 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A2BUP4|A2BUP4_PROM5
Name: tr|A2BUP4|A2BUP4_PROM5
Description: tr|A2BUP4|A2BUP4_PROM5 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9515) OX=167542 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MTNALQTPHRRSSSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLSLFGL...SAK')
ID: tr|A8G2S3|A8G2S3_PROM2
Name: tr|A8G2S3|A8G2S3_PROM2
Description: tr|A8G2S3|A8G2S3_PROM2 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9215) OX=93060 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|B9NZY2|B9NZY2_PROMR
Name: tr|B9NZY2|B9NZY2_PROMR
Description: tr|B9NZY2|B9NZY2_PROMR Ammonium transporter OS=Prochlorococcus marinus str. MIT 9202 OX=93058 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A9BDN5|A9BDN5_PROM4
Name: tr|A9BDN5|A9BDN5_PROM4
Description: tr|A9BDN5|A9BDN5_PROM4 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9211) OX=93059 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MTSALQTPSSRRVERLQEASLLRGPMLLLKSIRGFNSRSSLIWLACVPLALFGL...SAQ')
ID: tr|Q7V330|Q7V330_PROMP
Name: tr|Q7V330|Q7V330_PROMP
Description: tr|Q7V330|Q7V330_PROMP Ammonium transporter OS=Prochlorococcus marinus subsp. pastoris (strain CCMP1986 / NIES-2087 / MED4) OX=59919 GN=amt1 PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|Q9REX3|Q9REX3_PROMR
Name: tr|Q9REX3|Q9REX3_PROMR
Description: tr|Q9REX3|Q9REX3_PROMR Ammonium transporter OS=Prochlorococcus marinus OX=1219 GN=amt PE=3 SV=1
Number of features: 0
Seq('MQTNFLFMTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATV...SAK')
ID: tr|A0A318QZ80|A0A318QZ80_PROMR
Name: tr|A0A318QZ80|A0A318QZ80_PROMR
Description: tr|A0A318QZ80|A0A318QZ80_PROMR Ammonium transporter OS=Prochlorococcus marinus XMU1408 OX=2213228 GN=DNJ73_01630 PE=3 SV=1
Number of features: 0
Seq('MTTALQSPPRRTTSRLQDASLLNGPMLLLRSIKGFRRSQSWAWLASVPLALLGL...ASS')
ID: tr|A0A9D9G322|A0A9D9G322_PROMR
Name: tr|A0A9D9G322|A0A9D9G322_PROMR
Description: tr|A0A9D9G322|A0A9D9G322_PROMR Ammonium transporter OS=Prochlorococcus marinus CUG1433 OX=2774506 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A9D9C0X8|A0A9D9C0X8_PROMR
Name: tr|A0A9D9C0X8|A0A9D9C0X8_PROMR
Description: tr|A0A9D9C0X8|A0A9D9C0X8_PROMR Ammonium transporter OS=Prochlorococcus marinus XMU1424 OX=2774497 GN=amt PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|Q46HB1|Q46HB1_PROMT
Name: tr|Q46HB1|Q46HB1_PROMT
Description: tr|Q46HB1|Q46HB1_PROMT Ammonium transporter OS=Prochlorococcus marinus (strain NATL2A) OX=59920 GN=PMN2A_1629 PE=3 SV=1
Number of features: 0
Seq('MTTALQSPPRRTTSRLQDASLLNGPMLLLRSIKGFRRSQSWAWLASIPLALLGL...ASS')
ID: tr|A0A0A1ZJU5|A0A0A1ZJU5_PROMR
Name: tr|A0A0A1ZJU5|A0A0A1ZJU5_PROMR
Description: tr|A0A0A1ZJU5|A0A0A1ZJU5_PROMR Ammonium transporter OS=Prochlorococcus marinus str. GP2 OX=59925 GN=EU91_0432 PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSKLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A0A2B651|A0A0A2B651_PROMR
Name: tr|A0A0A2B651|A0A0A2B651_PROMR
Description: tr|A0A0A2B651|A0A0A2B651_PROMR Ammonium transporter OS=Prochlorococcus marinus str. SB OX=59926 GN=EV02_0958 PE=3 SV=1
Number of features: 0
Seq('MLWLATVPVALFGLGIFNLSAHAGDLPELNAAFLANNLWLLVATILVIFMNAGF...SAK')
ID: tr|A0A0A2C6L1|A0A0A2C6L1_PROMR
Name: tr|A0A0A2C6L1|A0A0A2C6L1_PROMR
Description: tr|A0A0A2C6L1|A0A0A2C6L1_PROMR Ammonium transporter OS=Prochlorococcus marinus str. PAC1 OX=59924 GN=EV03_1246 PE=3 SV=1
Number of features: 0
Seq('MLLLRSIKGFRRSQSWAWLASIPLALLGLGVFTFSARAEVALSDLTGPQAASFL...ASS')

ID: tr|Q31CR9|Q31CR9_PROM9
Name: tr|Q31CR9|Q31CR9_PROM9
Description: tr|Q31CR9|Q31CR9_PROM9 Ammonium transporter OS=Prochlorococcus marinus (strain MIT 9312) OX=74546 GN=PMT9312_0265 PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRTRLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A0A2A5X1|A0A0A2A5X1_PROMR
Name: tr|A0A0A2A5X1|A0A0A2A5X1_PROMR
Description: tr|A0A0A2A5X1|A0A0A2A5X1_PROMR Ammonium transporter OS=Prochlorococcus marinus str. MIT 9302 OX=74545 GN=EU96_1970 PE=3 SV=1
Number of features: 0
Seq('MTTALQTPQRRSRSRLQDASLVNGPMLLLRSIRGFSSNRSMLWLATVPLALFGL...SAK')
ID: tr|A0A0M2PZN7|A0A0M2PZN7_PROHO
Name: tr|A0A0M2PZN7|A0A0M2PZN7_PROHO
Description: tr|A0A0M2PZN7|A0A0M2PZN7_PROHO Ammonium transporter OS=Prochlorothrix hollandica PCC 9006 = CALU 1027 OX=317619 GN=PROH_09485 PE=3 SV=1
Number of features: 0
Seq('MVHSLRQFLPRFQWAWVACVPLTALIVIGWGLAAHAQDAPEMDPMYPIFLLNNL...ISE')
ID: tr|A0A5M4AWD2|A0A5M4AWD2_9BACT
Name: tr|A0A5M4AWD2|A0A5M4AWD2_9BACT
Description: tr|A0A5M4AWD2|A0A5M4AWD2_9BACT Ammonium transporter OS=Prolixibacter bellariivorans OX=314319 GN=PbJCM13498_09470 PE=3 SV=1
Number of features: 0
Seq('MQETLKIADIASAVSSNATSLDTVWVLVAAVLVMFMQPGFAMVEAGFTRAKNTA...AYN')
ID: tr|A0A5M4B0G1|A0A5M4B0G1_9BACT
Name: tr|A0A5M4B0G1|A0A5M4B0G1_9BACT
Description: tr|A0A5M4B0G1|A0A5M4B0G1_9BACT Ammonium transporter OS=Prolixibacter bellariivorans OX=314319 GN=PbJCM13498_25150 PE=3 SV=1
Number of features: 0
Seq('MATFDTGTTAFMILSTSLVMLMTPGLAFFYGGLAGKRNILGIMMQTFVSLGITT...GAL')
ID: tr|A0A5M4ATH9|A0A5M4ATH9_9BACT
Name: tr|A0A5M4ATH9|A0A5M4ATH9_9BACT
Description: tr|A0A5M4ATH9|A0A5M4ATH9_9BACT Ammonium transporter OS=Prolixibacter bellariivorans OX=314319 GN=PbJCM13498_01030 PE=3 SV=1
Number of features: 0
Seq('MRHKNKWLRTLIVLIIVSILGIFFPTTNFGDGGGALVTGDVAWMLTSTALVLLM...YMD')
ID: tr|A0A5M4AUM9|A0A5M4AUM9_9BACT
Name: tr|A0A5M4AUM9|A0A5M4AUM9_9BACT
Description: tr|A0A5M4AUM9|A0A5M4AUM9_9BACT Ammonium transporter OS=Prolixibacter bellariivorans OX=314319 GN=PbJCM13498_01040 PE=3 SV=1
Number of features: 0
Seq('MFDKGLTAFMIIATSLVMLMTPGLAFFYGGLSCKKNILSIMMQSFVSLGITSLL...RRQ')
ID: tr|A0A1H7CU41|A0A1H7CU41_9FIRM
Name: tr|A0A1H7CU41|A0A1H7CU41_9FIRM
Description: tr|A0A1H7CU41|A0A1H7CU41_9FIRM Ammonium transporter OS=Propionispira arboris OX=84035 GN=SAMN05660742_12543 PE=3 SV=1
Number of features: 0
Seq('MKKIWSTILATLMLVVLIAPVALAADDAAKATIDTGDTAWVLISAALVFVMTPG...DIK')
ID: tr|A0A1G7VM92|A0A1G7VM92_9RHOO
Name: tr|A0A1G7VM92|A0A1G7VM92_9RHOO
Description: tr|A0A1G7VM92|A0A1G7VM92_9RHOO Ammonium transporter OS=Propionivibrio dicarboxylicus OX=83767 GN=SAMN05660652_00243 PE=3 SV=1
Number of features: 0
Seq('MKKLLAVLAFVSALGLFTSAFAADTAAPAASAVVTATAAAPAAAAAAPAPTVNK...YKF')
ID: tr|A0A1G7UZX2|A0A1G7UZX2_9RHOO
Name: tr|A0A1G7UZX2|A0A1G7UZX2_9RHOO
Description: tr|A0A1G7UZX2|A0A1G7UZX2_9RHOO Ammonium transporter (TC 1.A.11) OS=Propionivibrio dicarboxylicus OX=83767 GN=SAMN05660652_00037 PE=3 SV=1
Number of features: 0
Seq('MEAAKTGSDVLFILLGGIMVLAMHSGFAFLELGTVRKKNQVNALVKILVDFSVS...PNW')
ID: tr|B4S394|B4S394_PROA2
Name: tr|B4S394|B4S394_PROA2
Description: tr|B4S394|B4S394_PROA2 Ammonium transporter OS=Prosthecochloris aestuarii (strain DSM 271 / SK 413) OX=290512 GN=Paes_0128 PE=3 SV=1
Number of features: 0
Seq('MKKLIRSGGATLVALLAANTVMAASPETDSGTTAWMLTATTLVLLMVPGLAMFY...NPN')
ID: tr|A0A0P6VSR8|A0A0P6VSR8_9HYPH
Name: tr|A0A0P6VSR8|A0A0P6VSR8_9HYPH
Description: tr|A0A0P6VSR8|A0A0P6VSR8_9HYPH Ammonium transporter OS=Prosthecomicrobium hirschii OX=665126 GN=ABB55_13410 PE=3 SV=1
Number of features: 0
Seq('MLPERSRIAKTASAALGILALTTLSAAAAGPEPNKGDTTWMLISTILVILMTLP...AYN')
ID: tr|A0A101HKN9|A0A101HKN9_9BACT
Name: tr|A0A101HKN9|A0A101HKN9_9BACT
Description: tr|A0A101HKN9|A0A101HKN9_9BACT Ammonium transporter OS=Proteiniphilum acetatigenes OX=294710 GN=XD92_0190 PE=3 SV=1
Number of features: 0
Seq('MDTATLTYALNTFWVLFAAVLVFFMQTGFALVEAGFSRTKNTTNILFKNLMDFC...AYN')
ID: tr|A0A7U1H267|A0A7U1H267_PROMI
Name: tr|A0A7U1H267|A0A7U1H267_PROMI
Description: tr|A0A7U1H267|A0A7U1H267_PROMI Ammonium transporter OS=Proteus mirabilis OX=584 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRFISYFFTLALTYFLLPQLAIGATTIDIDKADNSFMLICSALVFFMTIPGIA...YEQ')
ID: tr|B4EU65|B4EU65_PROMH
Name: tr|B4EU65|B4EU65_PROMH
Description: tr|B4EU65|B4EU65_PROMH Ammonium transporter OS=Proteus mirabilis (strain HI4320) OX=529507 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRFISYFFTLALTYFLLPQLAIGATTIDIDKADNSFMLICSALVFFMTIPGIA...YEQ')
ID: tr|A0A2X2C038|A0A2X2C038_PROMI
Name: tr|A0A2X2C038|A0A2X2C038_PROMI
Description: tr|A0A2X2C038|A0A2X2C038_PROMI Ammonium transporter OS=Proteus mirabilis OX=584 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MKRFISYFFTLALTYFLLPQLAIGATTIDIDKADNSFMLICSALVFFMTIPGIA...YEQ')
ID: tr|A0A1S5XW08|A0A1S5XW08_PROMI
Name: tr|A0A1S5XW08|A0A1S5XW08_PROMI
Description: tr|A0A1S5XW08|A0A1S5XW08_PROMI Bcr/CflA family efflux transporter OS=Proteus mirabilis OX=584 PE=3 SV=1
Number of features: 0
Seq('MSSKNFSWRYSLAATVLLLSPFDLLASLGMDMYLPAVPFMPNALGTTASTIQLT...PNR')
ID: tr|A0A264VQM8|A0A264VQM8_PRORE
Name: tr|A0A264VQM8|A0A264VQM8_PRORE
Description: tr|A0A264VQM8|A0A264VQM8_PRORE Ammonium transporter OS=Providencia rettgeri OX=587 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSKGFQYLFLLISMGGFPITVFAAEETLDKADNAFMMIATALVIFMILPGIALF...AYN')
ID: tr|A0A1Z1SZE8|A0A1Z1SZE8_PROMI
Name: tr|A0A1Z1SZE8|A0A1Z1SZE8_PROMI
Description: tr|A0A1Z1SZE8|A0A1Z1SZE8_PROMI Ammonium transporter OS=Proteus mirabilis OX=584 GN=AM402_18845 PE=3 SV=1
Number of features: 0
Seq('MKRFISYFFTLALTYFLLPQLAIGATTIDIDKADNSFMLICSALVFFMTIPGIA...YEQ')
ID: tr|A0A1S1HRJ0|A0A1S1HRJ0_PROST
Name: tr|A0A1S1HRJ0|A0A1S1HRJ0_PROST
Description: tr|A0A1S1HRJ0|A0A1S1HRJ0_PROST Ammonium transporter OS=Providencia stuartii OX=588 GN=A3Q29_03035 PE=3 SV=1
Number of features: 0
Seq('MSKLFQCVYLLLIASFPASVLASEEGIDKADNAFMMICTALVLFMIVPGIALFY...AYN')
ID: tr|A0A379GJ68|A0A379GJ68_PROST
Name: tr|A0A379GJ68|A0A379GJ68_PROST
Description: tr|A0A379GJ68|A0A379GJ68_PROST Ammonium transporter OS=Providencia stuartii OX=588 GN=amtB PE=3 SV=1
Number of features: 0
Seq('MSKLFQRLCWLFIASFPARVFASDDGVDKADNAFMMVCTALVLFMIVPGIALFY...AYN')
ID: tr|B2Q716|B2Q716_PROST
Name: tr|B2Q716|B2Q716_PROST
Description: tr|B2Q716|B2Q716_PROST Ammonium transporter OS=Providencia stuartii ATCC 25827 OX=471874 GN=amt PE=3 SV=1
Number of features: 0
Seq('MKHYRRVAMSKLFQRLCWLFIASFPARVFASDDGVDKADNAFMMVCTALVLFMI...AYN')
ID: tr|A0A140NHJ5|A0A140NHJ5_PROSM
Name: tr|A0A140NHJ5|A0A140NHJ5_PROSM
Description: tr|A0A140NHJ5|A0A140NHJ5_PROSM Ammonium transporter OS=Providencia stuartii (strain MRSN 2154) OX=1157951 GN=S70_06715 PE=3 SV=1
Number of features: 0
Seq('MSKLFQRLCWLFIASFPARVFASDDGVDKADNAFMMVCTALVLFMIVPGIALFY...AYN')
ID: tr|A0A1S1HM83|A0A1S1HM83_PROST
Name: tr|A0A1S1HM83|A0A1S1HM83_PROST
Description: tr|A0A1S1HM83|A0A1S1HM83_PROST Ammonium transporter OS=Providencia stuartii OX=588 GN=A3Q29_07180 PE=3 SV=1
Number of features: 0
Seq('MENILSVLDVPNTAFMLLCTSLVMLMTPGLAFFYGGLVSRKSVITIMSQSFFSM...KSN')
ID: tr|A0A370FPU0|A0A370FPU0_9BURK
Name: tr|A0A370FPU0|A0A370FPU0_9BURK
Description: tr|A0A370FPU0|A0A370FPU0_9BURK Ammonium transporter OS=Pseudacidovorax intermedius OX=433924 GN=DFR41_101650 PE=3 SV=1
Number of features: 0
Seq('MLVSTLLVILMTVPGLALFYGGLVRSKNMLSVLMQVFVTFSLIVVLWCIYGYSL...YNR')
ID: tr|A0A147GP06|A0A147GP06_9BURK
Name: tr|A0A147GP06|A0A147GP06_9BURK
Description: tr|A0A147GP06|A0A147GP06_9BURK Ammonium transporter OS=Pseudacidovorax intermedius OX=433924 GN=NS331_21020 PE=3 SV=1
Number of features: 0
Seq('MLVSTLLVILMTIPGLALFYGGLVRSKNMLSVLMQVFVTFSLIVVLWCIYGYSL...YNR')
ID: tr|A0A316BQ38|A0A316BQ38_PSESE
Name: tr|A0A316BQ38|A0A316BQ38_PSESE
Description: tr|A0A316BQ38|A0A316BQ38_PSESE Ammonium transporter OS=Pseudaminobacter salicylatoxidans OX=93369 GN=C7441_12243 PE=3 SV=1
Number of features: 0
Seq('MRIPTCFAQMARAALTGPVALAALGVLPALAQETAPEAAPADAAAPALNSGDTA...YHT')
ID: tr|A0A9J9BAE8|A0A9J9BAE8_PSEA6
Name: tr|A0A9J9BAE8|A0A9J9BAE8_PSEA6
Description: tr|A0A9J9BAE8|A0A9J9BAE8_PSEA6 Ammonium transporter OS=Pseudoalteromonas atlantica (strain T6c / ATCC BAA-1087) OX=342610 GN=Patl_0492 PE=3 SV=1
Number of features: 0
Seq('MEQAFHLQYAMDTFYFLVCGALVMWMAAGFSMLEAGLVRSKNTTEILTKNIALF...SGR')
ID: tr|A0A9J9ES23|A0A9J9ES23_PSEA6
Name: tr|A0A9J9ES23|A0A9J9ES23_PSEA6
Description: tr|A0A9J9ES23|A0A9J9ES23_PSEA6 Ammonium transporter OS=Pseudoalteromonas atlantica (strain T6c / ATCC BAA-1087) OX=342610 GN=Patl_0637 PE=3 SV=1
Number of features: 0
Seq('MQDVTSATELLVQSSNTYFLLIGAIMVFAMHAGFAFLEVGTVRHKNQVNALVKI...NDD')
ID: tr|A0A9J9ETF7|A0A9J9ETF7_PSEA6
Name: tr|A0A9J9ETF7|A0A9J9ETF7_PSEA6
Description: tr|A0A9J9ETF7|A0A9J9ETF7_PSEA6 Quaternary ammonium permease OS=Pseudoalteromonas atlantica (strain T6c / ATCC BAA-1087) OX=342610 GN=Patl_2586 PE=4 SV=1
Number of features: 0
Seq('MTLWLNAGIIFTLLAIVVILLKWGNVVCVGVTPVRLFTFIAILFTSGLDVGLIM...SVD')

ID: tr|A0A927UCK5|A0A927UCK5_9FIRM
Name: tr|A0A927UCK5|A0A927UCK5_9FIRM
Description: tr|A0A927UCK5|A0A927UCK5_9FIRM Ammonium transporter OS=Pseudobutyrivibrio ruminis OX=46206 GN=amt PE=3 SV=1
Number of features: 0
Seq('MEEYSSMLFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLMDFCIG...DVE')
ID: tr|A0A1H7IQT2|A0A1H7IQT2_9FIRM
Name: tr|A0A1H7IQT2|A0A1H7IQT2_9FIRM
Description: tr|A0A1H7IQT2|A0A1H7IQT2_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio ruminis OX=46206 GN=SAMN02910377_01423 PE=3 SV=1
Number of features: 0
Seq('MEAYSSMLFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLMDFCIG...DVE')
ID: tr|A0A285RSQ4|A0A285RSQ4_9FIRM
Name: tr|A0A285RSQ4|A0A285RSQ4_9FIRM
Description: tr|A0A285RSQ4|A0A285RSQ4_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio ruminis DSM 9787 OX=1123011 GN=SAMN02910411_1303 PE=3 SV=1
Number of features: 0
Seq('MEAYSSMLFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLMDFCIG...DVE')
ID: tr|A0A2G3DSU6|A0A2G3DSU6_9FIRM
Name: tr|A0A2G3DSU6|A0A2G3DSU6_9FIRM
Description: tr|A0A2G3DSU6|A0A2G3DSU6_9FIRM Adenylate cyclase OS=Pseudobutyrivibrio ruminis OX=46206 GN=CSX01_11995 PE=3 SV=1
Number of features: 0
Seq('MEEYTSILFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLMDFCIG...DVE')
ID: tr|A0A2G3E8V2|A0A2G3E8V2_9FIRM
Name: tr|A0A2G3E8V2|A0A2G3E8V2_9FIRM
Description: tr|A0A2G3E8V2|A0A2G3E8V2_9FIRM Adenylate cyclase OS=Pseudobutyrivibrio ruminis OX=46206 GN=CSX00_09535 PE=3 SV=1
Number of features: 0
Seq('MEEYTSLLFGVWFLIGAALVFWMQAGFAMVEAGFTRAKNTGNIIMKNLMDFCIG...DVE')

In [23]:
lousht = ','.join([str(item) for item in losht])

In [24]:
def Convert(string):
    li = list(string.split(","))
    return li

In [25]:
def Convart(strung):
    la = list(strung.split('\n'))
    return la

In [26]:
boxes = Convart(lousht)

In [27]:
nmes = []

for x in boxes:
    if 'Description' in x:
        nmes.append(x)
        
nmes

['Description: tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1',
 'Description: tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp. A56 OX=1495067 GN=EL22_10090 PE=3 SV=1',
 'Description: tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1',
 'Description: tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1',
 'Description: tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1',
 'Description: tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1',
 'Description: tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp. FS41 OX=1609975 GN=nrgA PE=3 SV=1',
 'Description: tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1',
 'Description: tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp. C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1',
 'Description: tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1',
 'Description: tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1',
 'Description: tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1',
 'Description: tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1',
 'Description: tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 'Description: tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1',
 'Description: tr|A0A0S2W112|A0A0S2W112_9FIRM Ammonium transporter OS=Intestinimonas butyriciproducens OX=1297617 GN=C7373_1064 PE=3 SV=1',
 'Description: tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT Ammonia channel OS=Clostridium sp. C105KSO13 OX=1776045 GN=amt PE=3 SV=1',
 'Description: tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=ASJ35_15960 PE=3 SV=1',
 'Description: tr|A0A136Q6K1|A0A136Q6K1_9FIRM Nitrogen regulatory protein P-II OS=Christensenella minuta OX=626937 GN=HMPREF3293_01017 PE=3 SV=1',
 'Description: tr|A0A136WGT4|A0A136WGT4_9FIRM Ammonia channel OS=Anaerotignum neopropionicum OX=36847 GN=amtB PE=3 SV=1',
 'Description: tr|A0A140DTE7|A0A140DTE7_9FIRM Ammonium transporter OS=Faecalibaculum rodentium OX=1702221 GN=AALO17_07900 PE=3 SV=1',
 'Description: tr|A0A143Y517|A0A143Y517_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_251 PE=3 SV=1',
 'Description: tr|A0A143Y9S4|A0A143Y9S4_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_303 PE=3 SV=1',
 'Description: tr|A0A143YNF2|A0A143YNF2_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_1615 PE=3 SV=1',
 'Description: tr|A0A143YTA3|A0A143YTA3_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1428 PE=3 SV=1',
 'Description: tr|A0A143YZV1|A0A143YZV1_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_1725 PE=3 SV=1',
 'Description: tr|A0A143Z212|A0A143Z212_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1990 PE=3 SV=1',
 'Description: tr|A0A143ZCA8|A0A143ZCA8_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_2799 PE=3 SV=1',
 'Description: tr|A0A151AI36|A0A151AI36_9EURY Putative ammonium transporter OS=Halalkalicoccus paucihalophilus OX=1008153 GN=HAPAU_09570 PE=3 SV=1',
 'Description: tr|A0A169X118|A0A169X118_9EURY Ammonium transporter OS=Haladaptatus sp. R4 OX=1679489 GN=A4G99_00420 PE=3 SV=1',
 'Description: tr|A0A173R3X4|A0A173R3X4_ANAHA Ammonia transporter OS=Anaerostipes hadrus OX=649756 GN=amt_1 PE=3 SV=1',
 'Description: tr|A0A173R662|A0A173R662_EUBRA Ammonia transporter OS=Eubacterium ramulus OX=39490 GN=amt PE=3 SV=1',
 'Description: tr|A0A173V441|A0A173V441_9FIRM Ammonia transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1',
 'Description: tr|A0A173X4T2|A0A173X4T2_9FIRM Ammonia transporter OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 'Description: tr|A0A173XV88|A0A173XV88_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'Description: tr|A0A173XVK8|A0A173XVK8_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_1 PE=3 SV=1',
 'Description: tr|A0A173Z4K3|A0A173Z4K3_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'Description: tr|A0A173ZTK6|A0A173ZTK6_9FIRM Ammonia transporter OS=[Ruminococcus] torques OX=33039 GN=amt PE=3 SV=1',
 'Description: tr|A0A174C5U1|A0A174C5U1_9FIRM Ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=amt PE=3 SV=1',
 'Description: tr|A0A174D1D6|A0A174D1D6_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'Description: tr|A0A174H6C4|A0A174H6C4_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_2 PE=3 SV=1',
 'Description: tr|A0A174JG28|A0A174JG28_9FIRM Ammonia transporter OS=Blautia wexlerae OX=418240 GN=amtB PE=3 SV=1',
 'Description: tr|A0A174RYE8|A0A174RYE8_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'Description: tr|A0A174TIU3|A0A174TIU3_ANAHA Adenylate cyclase OS=Anaerostipes hadrus OX=649756 GN=amt_2 PE=3 SV=1',
 'Description: tr|A0A174VZ55|A0A174VZ55_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'Description: tr|A0A174XKK3|A0A174XKK3_9FIRM Ammonium transporter OS=Hungatella hathewayi OX=154046 GN=amt PE=3 SV=1',
 'Description: tr|A0A174YTX7|A0A174YTX7_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 'Description: tr|A0A174Z5H4|A0A174Z5H4_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 'Description: tr|A0A175A4T9|A0A175A4T9_9FIRM Ammonia transporter OS=[Eubacterium] siraeum OX=39492 GN=amt PE=3 SV=1',
 'Description: tr|A0A1B1YE78|A0A1B1YE78_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. thermolacticum DSM 2910 OX=1121336 GN=CSTERTH_08555 PE=3 SV=1',
 'Description: tr|A0A1B1YLE9|A0A1B1YLE9_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. leptospartum DSM 9219 OX=1346611 GN=CSTERLE_08480 PE=3 SV=1',
 'Description: tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium MTC7 OX=1768196 GN=A4S06_10005 PE=3 SV=1',
 'Description: tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM Ammonia transporter OS=uncultured Dorea sp OX=286138 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'Description: tr|A0A1C5QX74|A0A1C5QX74_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5R365|A0A1C5R365_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5R381|A0A1C5R381_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C5T8Y6|A0A1C5T8Y6_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_1 PE=3 SV=1',
 'Description: tr|A0A1C5TF49|A0A1C5TF49_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'Description: tr|A0A1C5U2K1|A0A1C5U2K1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5UAP1|A0A1C5UAP1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'Description: tr|A0A1C5UEH7|A0A1C5UEH7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5UU75|A0A1C5UU75_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5VCM0|A0A1C5VCM0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'Description: tr|A0A1C5WY82|A0A1C5WY82_9FIRM Ammonia transporter OS=uncultured Coprococcus sp OX=458253 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5Y526|A0A1C5Y526_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5YFR7|A0A1C5YFR7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5YH18|A0A1C5YH18_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'Description: tr|A0A1C5Z331|A0A1C5Z331_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5Z9P9|A0A1C5Z9P9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C5ZTV2|A0A1C5ZTV2_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6B393|A0A1C6B393_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6B4K0|A0A1C6B4K0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 'Description: tr|A0A1C6BQA1|A0A1C6BQA1_9FIRM Ammonia transporter OS=uncultured Butyricicoccus sp OX=1193532 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6CXT8|A0A1C6CXT8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6D1W9|A0A1C6D1W9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6DAP7|A0A1C6DAP7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'Description: tr|A0A1C6DLP9|A0A1C6DLP9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6DWH2|A0A1C6DWH2_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6E048|A0A1C6E048_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6E379|A0A1C6E379_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt_1 PE=3 SV=1',
 'Description: tr|A0A1C6F4A8|A0A1C6F4A8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 'Description: tr|A0A1C6FKD5|A0A1C6FKD5_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6G7R3|A0A1C6G7R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6G8E0|A0A1C6G8E0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6G8R0|A0A1C6G8R0_9FIRM Ammonia transporter OS=uncultured Flavonifractor sp OX=1193534 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6GHV1|A0A1C6GHV1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_2 PE=3 SV=1',
 'Description: tr|A0A1C6GPW7|A0A1C6GPW7_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 'Description: tr|A0A1C6HLR1|A0A1C6HLR1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_1 PE=3 SV=1',
 'Description: tr|A0A1C6HNA9|A0A1C6HNA9_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6HP51|A0A1C6HP51_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6K3R3|A0A1C6K3R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'Description: tr|A0A1C6KIH8|A0A1C6KIH8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt_1 PE=3 SV=1',
 'Description: tr|A0A1C7GTZ0|A0A1C7GTZ0_9FIRM Adenylate cyclase OS=Hungateiclostridiaceae bacterium KB18 OX=1834198 GN=A4V00_15225 PE=3 SV=1',
 'Description: tr|A0A1C7HSA7|A0A1C7HSA7_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium I46 OX=1834207 GN=A4V01_11425 PE=3 SV=1',
 'Description: tr|A0A1C7IDV8|A0A1C7IDV8_9FIRM Adenylate cyclase OS=Blautia pseudococcoides OX=1796616 GN=A4V09_20040 PE=3 SV=1',
 'Description: tr|A0A1D3TYQ0|A0A1D3TYQ0_9FIRM Ammonium transporter, Amt family OS=Anaerobium acetethylicum OX=1619234 GN=SAMN05421730_10495 PE=3 SV=1',
 'Description: tr|A0A1D9NY31|A0A1D9NY31_9FIRM Ammonium transporter Amt OS=Butyrivibrio hungatei OX=185008 GN=bhn_I0137 PE=3 SV=1',
 'Description: tr|A0A1F8V8B8|A0A1F8V8B8_9FIRM Adenylate cyclase OS=Clostridiales bacterium GWF2_38_85 OX=1797683 GN=A2Y17_06980 PE=3 SV=1',
 'Description: tr|A0A1F9ZPG7|A0A1F9ZPG7_9FIRM Ammonium transporter OS=Firmicutes bacterium GWF2_51_9 OX=1798011 GN=A2Y20_03855 PE=3 SV=1',
 'Description: tr|A0A1G4QLQ0|A0A1G4QLQ0_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium C10 OX=1520822 GN=SAMN02910400_00838 PE=3 SV=1',
 'Description: tr|A0A1G4SPK4|A0A1G4SPK4_9FIRM Ammonium transporter, Amt family OS=Ruminococcaceae bacterium YRB3002 OX=1520819 GN=SAMN02910456_02677 PE=3 SV=1',
 'Description: tr|A0A1G4VHU5|A0A1G4VHU5_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium YSD2013 OX=1520828 GN=SAMN02910339_00972 PE=3 SV=1',
 'Description: tr|A0A1G5BLA9|A0A1G5BLA9_9FIRM Ammonium transporter, Amt family OS=Blautia sp. SF-50 OX=1520805 GN=SAMN02910433_00527 PE=3 SV=1',
 'Description: tr|A0A1G5DDJ5|A0A1G5DDJ5_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium XPB1003 OX=1520825 GN=SAMN02910370_01425 PE=3 SV=1',
 'Description: tr|A0A1G5DER5|A0A1G5DER5_9FIRM Ammonium transporter, Amt family OS=Butyrivibrio hungatei OX=185008 GN=SAMN02910451_01499 PE=3 SV=1',
 'Description: tr|A0A1G5EK45|A0A1G5EK45_9FIRM Ammonium transporter, Amt family OS=Butyrivibrio sp. INlla14 OX=1520808 GN=SAMN02910371_01637 PE=3 SV=1',
 'Description: tr|A0A1G5FBQ7|A0A1G5FBQ7_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio sp. AR14 OX=1520804 GN=SAMN05660668_02380 PE=3 SV=1',
 'Description: tr|A0A1G5RVB0|A0A1G5RVB0_PSEXY Ammonium transporter, Amt family OS=Pseudobutyrivibrio xylanivorans OX=185007 GN=SAMN02910350_01131 PE=3 SV=1',
 'Description: tr|A0A1G5WAS9|A0A1G5WAS9_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium G11 OX=1200747 GN=SAMN02910368_01187 PE=3 SV=1',
 'Description: tr|A0A1G5WH50|A0A1G5WH50_9FIRM Ammonium transporter, Amt family OS=Butyrivibrio sp. INlla18 OX=1520806 GN=SAMN02910275_01330 PE=3 SV=1',
 'Description: tr|A0A1G6AA59|A0A1G6AA59_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio sp. YE44 OX=1520802 GN=SAMN02910298_00105 PE=3 SV=1',
 'Description: tr|A0A1G6AEH9|A0A1G6AEH9_EUBOX Ammonium transporter, Amt family OS=Eubacterium oxidoreducens OX=1732 GN=SAMN02910417_00488 PE=3 SV=1',
 'Description: tr|A0A1G6BHE0|A0A1G6BHE0_9FIRM Ammonium transporter, Amt family OS=Ruminococcaceae bacterium FB2012 OX=1520817 GN=SAMN02910317_00984 PE=3 SV=1',
 'Description: tr|A0A1G6C6K5|A0A1G6C6K5_9FIRM Ammonium transporter, Amt family OS=Butyrivibrio sp. INlla16 OX=1520807 GN=SAMN02910263_01376 PE=3 SV=1',
 'Description: tr|A0A1G6KUG1|A0A1G6KUG1_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Succiniclasticum ruminis OX=40841 GN=SAMN04487864_105108 PE=3 SV=1',
 'Description: tr|A0A1G7RHP6|A0A1G7RHP6_9EURY Ammonium transporter OS=Halorubrum xinjiangense OX=261291 GN=SAMN04488067_11550 PE=3 SV=1',
 'Description: tr|A0A1G8BB52|A0A1G8BB52_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio sp. 49 OX=1855344 GN=SAMN05421493_101177 PE=3 SV=1',
 'Description: tr|A0A1G8V2D8|A0A1G8V2D8_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium G41 OX=1200749 GN=SAMN04487760_10977 PE=3 SV=1',
 'Description: tr|A0A1G8VFZ5|A0A1G8VFZ5_9EURY Ammonium transporter, Amt family OS=Halovenus aranensis OX=890420 GN=SAMN05216226_106168 PE=3 SV=1',
 'Description: tr|A0A1G9BC39|A0A1G9BC39_9EURY Ammonium transporter, Amt family OS=Natronorubrum texcoconense OX=1095776 GN=SAMN04515672_2901 PE=3 SV=1',
 'Description: tr|A0A1G9IKK4|A0A1G9IKK4_9CLOT Ammonium transporter, Amt family OS=Sarcina sp. DSM 11001 OX=1798184 GN=SAMN04487833_11546 PE=3 SV=1',
 'Description: tr|A0A1G9THY2|A0A1G9THY2_9FIRM Ammonium transporter, Amt family OS=Lachnospira pectinoschiza OX=28052 GN=SAMN05216544_0358 PE=3 SV=1',
 'Description: tr|A0A1G9XUV1|A0A1G9XUV1_9FIRM Ammonium transporter, Amt family OS=Acetanaerobacterium elongatum OX=258515 GN=SAMN05192585_10943 PE=3 SV=1',
 'Description: tr|A0A1H2V0V3|A0A1H2V0V3_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Lachnospiraceae bacterium KHCPX20 OX=1855375 GN=SAMN05216391_11266 PE=3 SV=1',
 'Description: tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM Ammonium transporter, Amt family OS=Lachnobacterium bovis DSM 14045 OX=1122142 GN=SAMN02910414_01015 PE=3 SV=1',
 'Description: tr|A0A1H3LXY5|A0A1H3LXY5_9EURY Ammonium transporter, Amt family OS=Halopenitus persicus OX=1048396 GN=SAMN05216564_10851 PE=3 SV=1',
 'Description: tr|A0A1H3Z0R0|A0A1H3Z0R0_9EURY Ammonium transporter, Amt family OS=Haloplanus vescus OX=555874 GN=SAMN04488065_2065 PE=3 SV=1',
 'Description: tr|A0A1H3ZKY2|A0A1H3ZKY2_9FIRM Ammonium transporter, Amt family OS=Pseudobutyrivibrio sp. ACV-2 OX=1520801 GN=SAMN02910384_01142 PE=3 SV=1',
 'Description: tr|A0A1H4EZX0|A0A1H4EZX0_9FIRM Ammonium transporter, Amt family OS=Oribacterium sp. KHPX15 OX=1855342 GN=SAMN05216349_1495 PE=3 SV=1',
 'Description: tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM Ammonium transporter, Amt family OS=Lachnospira multipara OX=28051 GN=SAMN05216537_11526 PE=3 SV=1',
 'Description: tr|A0A1H5YYF4|A0A1H5YYF4_9FIRM Ammonium transporter, Amt family OS=Butyrivibrio sp. Su6 OX=1520810 GN=SAMN02910276_02397 PE=3 SV=1',
 'Description: tr|A0A1H6INP9|A0A1H6INP9_9EURY Ammonium transporter, Amt family OS=Halopenitus malekzadehii OX=1267564 GN=SAMN05192561_103210 PE=3 SV=1',
 'Description: tr|A0A1H6J2A5|A0A1H6J2A5_RUMFL Ammonium transporter, Amt family OS=Ruminococcus flavefaciens OX=1265 GN=SAMN02910265_01289 PE=3 SV=1',
 'Description: tr|A0A1H6R9C6|A0A1H6R9C6_9EURY Ammonium transporter, Amt family OS=Halohasta litchfieldiae OX=1073996 GN=SAMN05444271_101140 PE=3 SV=1',
 'Description: tr|A0A1H6W8Z9|A0A1H6W8Z9_9FIRM Ammonium transporter, Amt family OS=Lachnospiraceae bacterium A10 OX=1520821 GN=SAMN02910453_2178 PE=3 SV=1',

In [28]:
baxes = ', '.join([str(item) for item in nmes])

In [29]:
baxes = baxes.replace('Description: Description: ', '')

In [30]:
baxes = baxes.replace('Description: ', '')

In [31]:
baxes = Convert(baxes)

In [32]:
baxes

['tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1',
 ' tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp. A56 OX=1495067 GN=EL22_10090 PE=3 SV=1',
 ' tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1',
 ' tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1',
 ' tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1',
 ' tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1',
 ' tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp. FS41 OX=1609975 GN=nrgA PE=3 SV=1',
 ' tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1',
 ' tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp. C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1',
 ' tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1',
 ' tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1',
 ' tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1',
 ' tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1',
 ' tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 ' tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1',
 ' tr|A0A0S2W112|A0A0S2W112_9FIRM Ammonium transporter OS=Intestinimonas butyriciproducens OX=1297617 GN=C7373_1064 PE=3 SV=1',
 ' tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT Ammonia channel OS=Clostridium sp. C105KSO13 OX=1776045 GN=amt PE=3 SV=1',
 ' tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=ASJ35_15960 PE=3 SV=1',
 ' tr|A0A136Q6K1|A0A136Q6K1_9FIRM Nitrogen regulatory protein P-II OS=Christensenella minuta OX=626937 GN=HMPREF3293_01017 PE=3 SV=1',
 ' tr|A0A136WGT4|A0A136WGT4_9FIRM Ammonia channel OS=Anaerotignum neopropionicum OX=36847 GN=amtB PE=3 SV=1',
 ' tr|A0A140DTE7|A0A140DTE7_9FIRM Ammonium transporter OS=Faecalibaculum rodentium OX=1702221 GN=AALO17_07900 PE=3 SV=1',
 ' tr|A0A143Y517|A0A143Y517_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_251 PE=3 SV=1',
 ' tr|A0A143Y9S4|A0A143Y9S4_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_303 PE=3 SV=1',
 ' tr|A0A143YNF2|A0A143YNF2_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_1615 PE=3 SV=1',
 ' tr|A0A143YTA3|A0A143YTA3_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1428 PE=3 SV=1',
 ' tr|A0A143YZV1|A0A143YZV1_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_1725 PE=3 SV=1',
 ' tr|A0A143Z212|A0A143Z212_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1990 PE=3 SV=1',
 ' tr|A0A143ZCA8|A0A143ZCA8_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_2799 PE=3 SV=1',
 ' tr|A0A151AI36|A0A151AI36_9EURY Putative ammonium transporter OS=Halalkalicoccus paucihalophilus OX=1008153 GN=HAPAU_09570 PE=3 SV=1',
 ' tr|A0A169X118|A0A169X118_9EURY Ammonium transporter OS=Haladaptatus sp. R4 OX=1679489 GN=A4G99_00420 PE=3 SV=1',
 ' tr|A0A173R3X4|A0A173R3X4_ANAHA Ammonia transporter OS=Anaerostipes hadrus OX=649756 GN=amt_1 PE=3 SV=1',
 ' tr|A0A173R662|A0A173R662_EUBRA Ammonia transporter OS=Eubacterium ramulus OX=39490 GN=amt PE=3 SV=1',
 ' tr|A0A173V441|A0A173V441_9FIRM Ammonia transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1',
 ' tr|A0A173X4T2|A0A173X4T2_9FIRM Ammonia transporter OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 ' tr|A0A173XV88|A0A173XV88_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 ' tr|A0A173XVK8|A0A173XVK8_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_1 PE=3 SV=1',
 ' tr|A0A173Z4K3|A0A173Z4K3_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 ' tr|A0A173ZTK6|A0A173ZTK6_9FIRM Ammonia transporter OS=[Ruminococcus] torques OX=33039 GN=amt PE=3 SV=1',
 ' tr|A0A174C5U1|A0A174C5U1_9FIRM Ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=amt PE=3 SV=1',
 ' tr|A0A174D1D6|A0A174D1D6_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 ' tr|A0A174H6C4|A0A174H6C4_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_2 PE=3 SV=1',
 ' tr|A0A174JG28|A0A174JG28_9FIRM Ammonia transporter OS=Blautia wexlerae OX=418240 GN=amtB PE=3 SV=1',
 ' tr|A0A174RYE8|A0A174RYE8_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 ' tr|A0A174TIU3|A0A174TIU3_ANAHA Adenylate cyclase OS=Anaerostipes hadrus OX=649756 GN=amt_2 PE=3 SV=1',
 ' tr|A0A174VZ55|A0A174VZ55_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 ' tr|A0A174XKK3|A0A174XKK3_9FIRM Ammonium transporter OS=Hungatella hathewayi OX=154046 GN=amt PE=3 SV=1',
 ' tr|A0A174YTX7|A0A174YTX7_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 ' tr|A0A174Z5H4|A0A174Z5H4_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 ' tr|A0A175A4T9|A0A175A4T9_9FIRM Ammonia transporter OS=[Eubacterium] siraeum OX=39492 GN=amt PE=3 SV=1',
 ' tr|A0A1B1YE78|A0A1B1YE78_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. thermolacticum DSM 2910 OX=1121336 GN=CSTERTH_08555 PE=3 SV=1',
 ' tr|A0A1B1YLE9|A0A1B1YLE9_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. leptospartum DSM 9219 OX=1346611 GN=CSTERLE_08480 PE=3 SV=1',
 ' tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium MTC7 OX=1768196 GN=A4S06_10005 PE=3 SV=1',
 ' tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM Ammonia transporter OS=uncultured Dorea sp OX=286138 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 ' tr|A0A1C5QX74|A0A1C5QX74_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 ' tr|A0A1C5R365|A0A1C5R365_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5R381|A0A1C5R381_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 ' tr|A0A1C5T8Y6|A0A1C5T8Y6_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_1 PE=3 SV=1',
 ' tr|A0A1C5TF49|A0A1C5TF49_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 ' tr|A0A1C5U2K1|A0A1C5U2K1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C5UAP1|A0A1C5UAP1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 ' tr|A0A1C5UEH7|A0A1C5UEH7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5UU75|A0A1C5UU75_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5VCM0|A0A1C5VCM0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 ' tr|A0A1C5WY82|A0A1C5WY82_9FIRM Ammonia transporter OS=uncultured Coprococcus sp OX=458253 GN=amt PE=3 SV=1',
 ' tr|A0A1C5Y526|A0A1C5Y526_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amt PE=3 SV=1',
 ' tr|A0A1C5YFR7|A0A1C5YFR7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5YH18|A0A1C5YH18_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 ' tr|A0A1C5Z331|A0A1C5Z331_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C5Z9P9|A0A1C5Z9P9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C5ZTV2|A0A1C5ZTV2_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C6B393|A0A1C6B393_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 ' tr|A0A1C6B4K0|A0A1C6B4K0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 ' tr|A0A1C6BQA1|A0A1C6BQA1_9FIRM Ammonia transporter OS=uncultured Butyricicoccus sp OX=1193532 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6CXT8|A0A1C6CXT8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6D1W9|A0A1C6D1W9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C6DAP7|A0A1C6DAP7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 ' tr|A0A1C6DLP9|A0A1C6DLP9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C6DWH2|A0A1C6DWH2_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6E048|A0A1C6E048_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C6E379|A0A1C6E379_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt_1 PE=3 SV=1',
 ' tr|A0A1C6F4A8|A0A1C6F4A8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 ' tr|A0A1C6FKD5|A0A1C6FKD5_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6G7R3|A0A1C6G7R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6G8E0|A0A1C6G8E0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 ' tr|A0A1C6G8R0|A0A1C6G8R0_9FIRM Ammonia transporter OS=uncultured Flavonifractor sp OX=1193534 GN=amt PE=3 SV=1',
 ' tr|A0A1C6GHV1|A0A1C6GHV1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_2 PE=3 SV=1',
 ' tr|A0A1C6GPW7|A0A1C6GPW7_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 ' tr|A0A1C6HLR1|A0A1C6HLR1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_1 PE=3 SV=1',
 ' tr|A0A1C6HNA9|A0A1C6HNA9_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6HP51|A0A1C6HP51_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6K3R3|A0A1C6K3R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 ' tr|A0A1C6KIH8|A0A1C6KIH8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt_1 PE=3 SV=1',
 ' tr|A0A1C7GTZ0|A0A1C7GTZ0_9FIRM Adenylate cyclase OS=Hungateiclostridiaceae bacterium KB18 OX=1834198 GN=A4V00_15225 PE=3 SV=1',
 ' tr|A0A1C7HSA7|A0A1C7HSA7_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium I46 OX=1834207 GN=A4V01_11425 PE=3 SV=1',
 ' tr|A0A1C7IDV8|A0A1C7IDV8_9FIRM Adenylate cyclase OS=Blautia pseudococcoides OX=1796616 GN=A4V09_20040 PE=3 SV=1',
 ' tr|A0A1D3TYQ0|A0A1D3TYQ0_9FIRM Ammonium transporter',
 ' Amt family OS=Anaerobium acetethylicum OX=1619234 GN=SAMN05421730_10495 PE=3 SV=1',
 ' tr|A0A1D9NY31|A0A1D9NY31_9FIRM Ammonium transporter Amt OS=Butyrivibrio hungatei OX=185008 GN=bhn_I0137 PE=3 SV=1',
 ' tr|A0A1F8V8B8|A0A1F8V8B8_9FIRM Adenylate cyclase OS=Clostridiales bacterium GWF2_38_85 OX=1797683 GN=A2Y17_06980 PE=3 SV=1',
 ' tr|A0A1F9ZPG7|A0A1F9ZPG7_9FIRM Ammonium transporter OS=Firmicutes bacterium GWF2_51_9 OX=1798011 GN=A2Y20_03855 PE=3 SV=1',
 ' tr|A0A1G4QLQ0|A0A1G4QLQ0_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium C10 OX=1520822 GN=SAMN02910400_00838 PE=3 SV=1',
 ' tr|A0A1G4SPK4|A0A1G4SPK4_9FIRM Ammonium transporter',
 ' Amt family OS=Ruminococcaceae bacterium YRB3002 OX=1520819 GN=SAMN02910456_02677 PE=3 SV=1',
 ' tr|A0A1G4VHU5|A0A1G4VHU5_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium YSD2013 OX=1520828 GN=SAMN02910339_00972 PE=3 SV=1',
 ' tr|A0A1G5BLA9|A0A1G5BLA9_9FIRM Ammonium transporter',
 ' Amt family OS=Blautia sp. SF-50 OX=1520805 GN=SAMN02910433_00527 PE=3 SV=1',
 ' tr|A0A1G5DDJ5|A0A1G5DDJ5_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium XPB1003 OX=1520825 GN=SAMN02910370_01425 PE=3 SV=1',
 ' tr|A0A1G5DER5|A0A1G5DER5_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio hungatei OX=185008 GN=SAMN02910451_01499 PE=3 SV=1',
 ' tr|A0A1G5EK45|A0A1G5EK45_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio sp. INlla14 OX=1520808 GN=SAMN02910371_01637 PE=3 SV=1',
 ' tr|A0A1G5FBQ7|A0A1G5FBQ7_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio sp. AR14 OX=1520804 GN=SAMN05660668_02380 PE=3 SV=1',
 ' tr|A0A1G5RVB0|A0A1G5RVB0_PSEXY Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio xylanivorans OX=185007 GN=SAMN02910350_01131 PE=3 SV=1',
 ' tr|A0A1G5WAS9|A0A1G5WAS9_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium G11 OX=1200747 GN=SAMN02910368_01187 PE=3 SV=1',
 ' tr|A0A1G5WH50|A0A1G5WH50_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio sp. INlla18 OX=1520806 GN=SAMN02910275_01330 PE=3 SV=1',
 ' tr|A0A1G6AA59|A0A1G6AA59_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio sp. YE44 OX=1520802 GN=SAMN02910298_00105 PE=3 SV=1',
 ' tr|A0A1G6AEH9|A0A1G6AEH9_EUBOX Ammonium transporter',
 ' Amt family OS=Eubacterium oxidoreducens OX=1732 GN=SAMN02910417_00488 PE=3 SV=1',
 ' tr|A0A1G6BHE0|A0A1G6BHE0_9FIRM Ammonium transporter',
 ' Amt family OS=Ruminococcaceae bacterium FB2012 OX=1520817 GN=SAMN02910317_00984 PE=3 SV=1',
 ' tr|A0A1G6C6K5|A0A1G6C6K5_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio sp. INlla16 OX=1520807 GN=SAMN02910263_01376 PE=3 SV=1',
 ' tr|A0A1G6KUG1|A0A1G6KUG1_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Succiniclasticum ruminis OX=40841 GN=SAMN04487864_105108 PE=3 SV=1',
 ' tr|A0A1G7RHP6|A0A1G7RHP6_9EURY Ammonium transporter OS=Halorubrum xinjiangense OX=261291 GN=SAMN04488067_11550 PE=3 SV=1',
 ' tr|A0A1G8BB52|A0A1G8BB52_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio sp. 49 OX=1855344 GN=SAMN05421493_101177 PE=3 SV=1',
 ' tr|A0A1G8V2D8|A0A1G8V2D8_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium G41 OX=1200749 GN=SAMN04487760_10977 PE=3 SV=1',
 ' tr|A0A1G8VFZ5|A0A1G8VFZ5_9EURY Ammonium transporter',
 ' Amt family OS=Halovenus aranensis OX=890420 GN=SAMN05216226_106168 PE=3 SV=1',
 ' tr|A0A1G9BC39|A0A1G9BC39_9EURY Ammonium transporter',
 ' Amt family OS=Natronorubrum texcoconense OX=1095776 GN=SAMN04515672_2901 PE=3 SV=1',
 ' tr|A0A1G9IKK4|A0A1G9IKK4_9CLOT Ammonium transporter',
 ' Amt family OS=Sarcina sp. DSM 11001 OX=1798184 GN=SAMN04487833_11546 PE=3 SV=1',
 ' tr|A0A1G9THY2|A0A1G9THY2_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospira pectinoschiza OX=28052 GN=SAMN05216544_0358 PE=3 SV=1',
 ' tr|A0A1G9XUV1|A0A1G9XUV1_9FIRM Ammonium transporter',
 ' Amt family OS=Acetanaerobacterium elongatum OX=258515 GN=SAMN05192585_10943 PE=3 SV=1',
 ' tr|A0A1H2V0V3|A0A1H2V0V3_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Lachnospiraceae bacterium KHCPX20 OX=1855375 GN=SAMN05216391_11266 PE=3 SV=1',
 ' tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnobacterium bovis DSM 14045 OX=1122142 GN=SAMN02910414_01015 PE=3 SV=1',
 ' tr|A0A1H3LXY5|A0A1H3LXY5_9EURY Ammonium transporter',
 ' Amt family OS=Halopenitus persicus OX=1048396 GN=SAMN05216564_10851 PE=3 SV=1',
 ' tr|A0A1H3Z0R0|A0A1H3Z0R0_9EURY Ammonium transporter',
 ' Amt family OS=Haloplanus vescus OX=555874 GN=SAMN04488065_2065 PE=3 SV=1',
 ' tr|A0A1H3ZKY2|A0A1H3ZKY2_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio sp. ACV-2 OX=1520801 GN=SAMN02910384_01142 PE=3 SV=1',
 ' tr|A0A1H4EZX0|A0A1H4EZX0_9FIRM Ammonium transporter',
 ' Amt family OS=Oribacterium sp. KHPX15 OX=1855342 GN=SAMN05216349_1495 PE=3 SV=1',
 ' tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospira multipara OX=28051 GN=SAMN05216537_11526 PE=3 SV=1',
 ' tr|A0A1H5YYF4|A0A1H5YYF4_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio sp. Su6 OX=1520810 GN=SAMN02910276_02397 PE=3 SV=1',
 ' tr|A0A1H6INP9|A0A1H6INP9_9EURY Ammonium transporter',
 ' Amt family OS=Halopenitus malekzadehii OX=1267564 GN=SAMN05192561_103210 PE=3 SV=1',
 ' tr|A0A1H6J2A5|A0A1H6J2A5_RUMFL Ammonium transporter',
 ' Amt family OS=Ruminococcus flavefaciens OX=1265 GN=SAMN02910265_01289 PE=3 SV=1',
 ' tr|A0A1H6R9C6|A0A1H6R9C6_9EURY Ammonium transporter',
 ' Amt family OS=Halohasta litchfieldiae OX=1073996 GN=SAMN05444271_101140 PE=3 SV=1',
 ' tr|A0A1H6W8Z9|A0A1H6W8Z9_9FIRM Ammonium transporter',
 ' Amt family OS=Lachnospiraceae bacterium A10 OX=1520821 GN=SAMN02910453_2178 PE=3 SV=1',
 ' tr|A0A1H7IQT2|A0A1H7IQT2_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio ruminis OX=46206 GN=SAMN02910377_01423 PE=3 SV=1',
 ' tr|A0A1H7M3E0|A0A1H7M3E0_9FIRM Nitrogen regulatory protein P-II family OS=Butyrivibrio sp. ob235 OX=1761780 GN=SAMN04487770_105122 PE=3 SV=1',
 ' tr|A0A1H7NPU9|A0A1H7NPU9_RUMAL Ammonium transporter',
 ' Amt family OS=Ruminococcus albus OX=1264 GN=SAMN05216469_11622 PE=3 SV=1',
 ' tr|A0A1H8S6J8|A0A1H8S6J8_9BACI Ammonium transporter',
 ' Amt family OS=Amphibacillus marinus OX=872970 GN=SAMN04488134_11215 PE=3 SV=1',
 ' tr|A0A1H9A9D8|A0A1H9A9D8_9FIRM Ammonium transporter',
 ' Amt family OS=Butyrivibrio sp. TB OX=1520809 GN=SAMN02910382_00873 PE=3 SV=1',
 ' tr|A0A1H9J573|A0A1H9J573_9EURY Ammonium transporter',
 ' Amt family OS=Natrinema salaciae OX=1186196 GN=SAMN04489841_2439 PE=3 SV=1',
 ' tr|A0A1H9P153|A0A1H9P153_BUTFI Ammonium transporter',
 ' Amt family OS=Butyrivibrio fibrisolvens OX=831 GN=SAMN04487884_10591 PE=3 SV=1',
 ' tr|A0A1H9Z210|A0A1H9Z210_9FIRM Ammonium transporter',
 ' Amt family OS=Pseudobutyrivibrio sp. C4 OX=1520803 GN=SAMN02910413_0769 PE=3 SV=1',
 ' tr|A0A1I0G858|A0A1I0G858_9FIRM Ammonium transporter',
 ' Amt family OS=[Clostridium] aminophilum OX=1526 GN=SAMN04487771_103123 PE=3 SV=1',
 ' tr|A0A1I0H5B4|A0A1I0H5B4_9EURY Ammonium transporter',
 ' Amt family OS=Natrinema hispanicum OX=392421 GN=SAMN04488694_11283 PE=3 SV=1',
 ' tr|A0A1I0HDV9|A0A1I0HDV9_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=SAMN05216521_102715 PE=3 SV=1',

In [92]:
!seqkit grep -r -v -n -p '.*Helix_10.*'  helices2.fasta > helix.fasta
!seqkit grep -r -v -n -p '.*Helix_11.*'  helix.fasta > helixone.fasta
# !seqkit grep -r -v -n -p '.*Helix_12.*'  helixone.fasta > helixgone.fasta
!seqkit grep -r -n -p '.*Helix_1.*'  helixone.fasta > helix1.fasta

In [93]:
!seqkit grep -r -n -p '.*Helix_2.*'  helices2.fasta > helix2.fasta
!seqkit grep -r -n -p '.*Helix_3.*'  helices2.fasta > helix3.fasta
!seqkit grep -r -n -p '.*Helix_4.*'  helices2.fasta > helix4.fasta
!seqkit grep -r -n -p '.*Helix_5.*'  helices2.fasta > helix5.fasta
!seqkit grep -r -n -p '.*Helix_6.*'  helices2.fasta > helix6.fasta
!seqkit grep -r -n -p '.*Helix_7.*'  helices2.fasta > helix7.fasta
!seqkit grep -r -n -p '.*Helix_8.*'  helices2.fasta > helix8.fasta
!seqkit grep -r -n -p '.*Helix_9.*'  helices2.fasta > helix9.fasta
!seqkit grep -r -n -p '.*Helix_10.*'  helices2.fasta > helix10.fasta
!seqkit grep -r -n -p '.*Helix_11.*'  helices2.fasta > helix11.fasta
# !seqkit grep -r -n -p '.*Helix_12.*'  helices.fasta > helix12.fasta

In [35]:
with open('baxes.txt', 'w') as fp:
    for itemq in baxes:
        # write each item on a new line
        fp.write("%s\n" % itemq)
    print('Done')

Done

In [60]:
filtere = []

for hops in hip:
    for ide in baxes:
        if hops in ide:
            juic = ide
            if juic[0] == ' ':
                juic = juic[1:]
            filtere.append(juic)

In [61]:
filtere

['tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1',
 'tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp. A56 OX=1495067 GN=EL22_10090 PE=3 SV=1',
 'tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1',
 'tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1',
 'tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1',
 'tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1',
 'tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp. FS41 OX=1609975 GN=nrgA PE=3 SV=1',
 'tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1',
 'tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp. C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1',
 'tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1',
 'tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1',
 'tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1',
 'tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1',
 'tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 'tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1',
 'tr|A0A0S2W112|A0A0S2W112_9FIRM Ammonium transporter OS=Intestinimonas butyriciproducens OX=1297617 GN=C7373_1064 PE=3 SV=1',
 'tr|A0A0U5JBG5|A0A0U5JBG5_9CLOT Ammonia channel OS=Clostridium sp. C105KSO13 OX=1776045 GN=amt PE=3 SV=1',
 'tr|A0A0W7TMH6|A0A0W7TMH6_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=ASJ35_15960 PE=3 SV=1',
 'tr|A0A136Q6K1|A0A136Q6K1_9FIRM Nitrogen regulatory protein P-II OS=Christensenella minuta OX=626937 GN=HMPREF3293_01017 PE=3 SV=1',
 'tr|A0A136WGT4|A0A136WGT4_9FIRM Ammonia channel OS=Anaerotignum neopropionicum OX=36847 GN=amtB PE=3 SV=1',
 'tr|A0A140DTE7|A0A140DTE7_9FIRM Ammonium transporter OS=Faecalibaculum rodentium OX=1702221 GN=AALO17_07900 PE=3 SV=1',
 'tr|A0A143Y517|A0A143Y517_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_251 PE=3 SV=1',
 'tr|A0A143Y9S4|A0A143Y9S4_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_303 PE=3 SV=1',
 'tr|A0A143YNF2|A0A143YNF2_9LACT Nitrogen regulatory protein pii OS=Trichococcus palustris OX=140314 GN=Tpal_1615 PE=3 SV=1',
 'tr|A0A143YTA3|A0A143YTA3_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1428 PE=3 SV=1',
 'tr|A0A143YZV1|A0A143YZV1_9LACT Nitrogen regulatory protein pii OS=Trichococcus sp. ES5 OX=872292 GN=TES5_1725 PE=3 SV=1',
 'tr|A0A143Z212|A0A143Z212_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_1990 PE=3 SV=1',
 'tr|A0A143ZCA8|A0A143ZCA8_9LACT Nitrogen regulatory protein pii OS=Trichococcus ilyis OX=640938 GN=TR210_2799 PE=3 SV=1',
 'tr|A0A151AI36|A0A151AI36_9EURY Putative ammonium transporter OS=Halalkalicoccus paucihalophilus OX=1008153 GN=HAPAU_09570 PE=3 SV=1',
 'tr|A0A169X118|A0A169X118_9EURY Ammonium transporter OS=Haladaptatus sp. R4 OX=1679489 GN=A4G99_00420 PE=3 SV=1',
 'tr|A0A173R3X4|A0A173R3X4_ANAHA Ammonia transporter OS=Anaerostipes hadrus OX=649756 GN=amt_1 PE=3 SV=1',
 'tr|A0A173R662|A0A173R662_EUBRA Ammonia transporter OS=Eubacterium ramulus OX=39490 GN=amt PE=3 SV=1',
 'tr|A0A173V441|A0A173V441_9FIRM Ammonia transporter OS=Faecalibacterium prausnitzii OX=853 GN=amt PE=3 SV=1',
 'tr|A0A173X4T2|A0A173X4T2_9FIRM Ammonia transporter OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1',
 'tr|A0A173XV88|A0A173XV88_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'tr|A0A173XVK8|A0A173XVK8_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_1 PE=3 SV=1',
 'tr|A0A173Z4K3|A0A173Z4K3_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'tr|A0A173ZTK6|A0A173ZTK6_9FIRM Ammonia transporter OS=[Ruminococcus] torques OX=33039 GN=amt PE=3 SV=1',
 'tr|A0A174C5U1|A0A174C5U1_9FIRM Ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=amt PE=3 SV=1',
 'tr|A0A174D1D6|A0A174D1D6_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'tr|A0A174H6C4|A0A174H6C4_9CLOT Ammonium transporter OS=Clostridium disporicum OX=84024 GN=amt_2 PE=3 SV=1',
 'tr|A0A174JG28|A0A174JG28_9FIRM Ammonia transporter OS=Blautia wexlerae OX=418240 GN=amtB PE=3 SV=1',
 'tr|A0A174RYE8|A0A174RYE8_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'tr|A0A174TIU3|A0A174TIU3_ANAHA Adenylate cyclase OS=Anaerostipes hadrus OX=649756 GN=amt_2 PE=3 SV=1',
 'tr|A0A174VZ55|A0A174VZ55_9FIRM Ammonia transporter OS=Blautia obeum OX=40520 GN=amtB PE=3 SV=1',
 'tr|A0A174XKK3|A0A174XKK3_9FIRM Ammonium transporter OS=Hungatella hathewayi OX=154046 GN=amt PE=3 SV=1',
 'tr|A0A174YTX7|A0A174YTX7_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 'tr|A0A174Z5H4|A0A174Z5H4_9FIRM Ammonia transporter OS=Lachnospira eligens OX=39485 GN=amt PE=3 SV=1',
 'tr|A0A175A4T9|A0A175A4T9_9FIRM Ammonia transporter OS=[Eubacterium] siraeum OX=39492 GN=amt PE=3 SV=1',
 'tr|A0A1B1YE78|A0A1B1YE78_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. thermolacticum DSM 2910 OX=1121336 GN=CSTERTH_08555 PE=3 SV=1',
 'tr|A0A1B1YLE9|A0A1B1YLE9_THEST Adenylate cyclase OS=Thermoclostridium stercorarium subsp. leptospartum DSM 9219 OX=1346611 GN=CSTERLE_08480 PE=3 SV=1',
 'tr|A0A1C0BVB4|A0A1C0BVB4_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium MTC7 OX=1768196 GN=A4S06_10005 PE=3 SV=1',
 'tr|A0A1C5M0W8|A0A1C5M0W8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5MDL8|A0A1C5MDL8_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'tr|A0A1C5N7S1|A0A1C5N7S1_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5PFK7|A0A1C5PFK7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'tr|A0A1C5PIG4|A0A1C5PIG4_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'tr|A0A1C5PQC5|A0A1C5PQC5_9FIRM Ammonia transporter OS=uncultured Dorea sp OX=286138 GN=amtB PE=3 SV=1',
 'tr|A0A1C5QAX9|A0A1C5QAX9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5QDA2|A0A1C5QDA2_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 'tr|A0A1C5QHK8|A0A1C5QHK8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'tr|A0A1C5QX74|A0A1C5QX74_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'tr|A0A1C5R1D9|A0A1C5R1D9_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 'tr|A0A1C5R365|A0A1C5R365_9FIRM Ammonia transporter OS=uncultured Faecalibacterium sp OX=259315 GN=amtB PE=3 SV=1',
 'tr|A0A1C5R381|A0A1C5R381_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C5RAN1|A0A1C5RAN1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'tr|A0A1C5S8B5|A0A1C5S8B5_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'tr|A0A1C5SQE8|A0A1C5SQE8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C5SVL0|A0A1C5SVL0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'tr|A0A1C5T8Y6|A0A1C5T8Y6_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_1 PE=3 SV=1',
 'tr|A0A1C5TF49|A0A1C5TF49_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'tr|A0A1C5U2K1|A0A1C5U2K1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C5UAP1|A0A1C5UAP1_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'tr|A0A1C5UEH7|A0A1C5UEH7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5UU75|A0A1C5UU75_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5VCM0|A0A1C5VCM0_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB_2 PE=3 SV=1',
 'tr|A0A1C5WY82|A0A1C5WY82_9FIRM Ammonia transporter OS=uncultured Coprococcus sp OX=458253 GN=amt PE=3 SV=1',
 'tr|A0A1C5Y526|A0A1C5Y526_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amt PE=3 SV=1',
 'tr|A0A1C5YFR7|A0A1C5YFR7_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5YH18|A0A1C5YH18_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'tr|A0A1C5Z331|A0A1C5Z331_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C5Z9P9|A0A1C5Z9P9_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C5ZTV2|A0A1C5ZTV2_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C6B393|A0A1C6B393_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt PE=3 SV=1',
 'tr|A0A1C6B4K0|A0A1C6B4K0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 'tr|A0A1C6BQA1|A0A1C6BQA1_9FIRM Ammonia transporter OS=uncultured Butyricicoccus sp OX=1193532 GN=amtB PE=3 SV=1',
 'tr|A0A1C6CXT8|A0A1C6CXT8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB PE=3 SV=1',
 'tr|A0A1C6D1W9|A0A1C6D1W9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C6DAP7|A0A1C6DAP7_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_1 PE=3 SV=1',
 'tr|A0A1C6DLP9|A0A1C6DLP9_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C6DWH2|A0A1C6DWH2_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amtB PE=3 SV=1',
 'tr|A0A1C6E048|A0A1C6E048_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C6E379|A0A1C6E379_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt_1 PE=3 SV=1',
 'tr|A0A1C6F4A8|A0A1C6F4A8_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amtB_2 PE=3 SV=1',
 'tr|A0A1C6FKD5|A0A1C6FKD5_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'tr|A0A1C6G7R3|A0A1C6G7R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'tr|A0A1C6G8E0|A0A1C6G8E0_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt PE=3 SV=1',
 'tr|A0A1C6G8R0|A0A1C6G8R0_9FIRM Ammonia transporter OS=uncultured Flavonifractor sp OX=1193534 GN=amt PE=3 SV=1',
 'tr|A0A1C6GHV1|A0A1C6GHV1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_2 PE=3 SV=1',
 'tr|A0A1C6GPW7|A0A1C6GPW7_9FIRM Ammonia transporter OS=uncultured Eubacterium sp OX=165185 GN=amt PE=3 SV=1',
 'tr|A0A1C6HLR1|A0A1C6HLR1_9FIRM Ammonia transporter OS=uncultured Ruminococcus sp OX=165186 GN=amt_1 PE=3 SV=1',
 'tr|A0A1C6HNA9|A0A1C6HNA9_9FIRM Ammonia transporter OS=uncultured Blautia sp OX=765821 GN=amtB PE=3 SV=1',
 'tr|A0A1C6HP51|A0A1C6HP51_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'tr|A0A1C6K3R3|A0A1C6K3R3_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amtB PE=3 SV=1',
 'tr|A0A1C6KIH8|A0A1C6KIH8_9CLOT Ammonia transporter OS=uncultured Clostridium sp OX=59620 GN=amt_1 PE=3 SV=1',
 'tr|A0A1C7GTZ0|A0A1C7GTZ0_9FIRM Adenylate cyclase OS=Hungateiclostridiaceae bacterium KB18 OX=1834198 GN=A4V00_15225 PE=3 SV=1',
 'tr|A0A1C7HSA7|A0A1C7HSA7_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium I46 OX=1834207 GN=A4V01_11425 PE=3 SV=1',
 'tr|A0A1C7IDV8|A0A1C7IDV8_9FIRM Adenylate cyclase OS=Blautia pseudococcoides OX=1796616 GN=A4V09_20040 PE=3 SV=1',
 'tr|A0A1D3TYQ0|A0A1D3TYQ0_9FIRM Ammonium transporter',
 'tr|A0A1D9NY31|A0A1D9NY31_9FIRM Ammonium transporter Amt OS=Butyrivibrio hungatei OX=185008 GN=bhn_I0137 PE=3 SV=1',
 'tr|A0A1F8V8B8|A0A1F8V8B8_9FIRM Adenylate cyclase OS=Clostridiales bacterium GWF2_38_85 OX=1797683 GN=A2Y17_06980 PE=3 SV=1',
 'tr|A0A1F9ZPG7|A0A1F9ZPG7_9FIRM Ammonium transporter OS=Firmicutes bacterium GWF2_51_9 OX=1798011 GN=A2Y20_03855 PE=3 SV=1',
 'tr|A0A1G4QLQ0|A0A1G4QLQ0_9FIRM Ammonium transporter',
 'tr|A0A1G4SPK4|A0A1G4SPK4_9FIRM Ammonium transporter',
 'tr|A0A1G4VHU5|A0A1G4VHU5_9FIRM Ammonium transporter',
 'tr|A0A1G5BLA9|A0A1G5BLA9_9FIRM Ammonium transporter',
 'tr|A0A1G5DDJ5|A0A1G5DDJ5_9FIRM Ammonium transporter',
 'tr|A0A1G5DER5|A0A1G5DER5_9FIRM Ammonium transporter',
 'tr|A0A1G5EK45|A0A1G5EK45_9FIRM Ammonium transporter',
 'tr|A0A1G5FBQ7|A0A1G5FBQ7_9FIRM Ammonium transporter',
 'tr|A0A1G5RVB0|A0A1G5RVB0_PSEXY Ammonium transporter',
 'tr|A0A1G5WAS9|A0A1G5WAS9_9FIRM Ammonium transporter',
 'tr|A0A1G5WH50|A0A1G5WH50_9FIRM Ammonium transporter',
 'tr|A0A1G6AA59|A0A1G6AA59_9FIRM Ammonium transporter',
 'tr|A0A1G6AEH9|A0A1G6AEH9_EUBOX Ammonium transporter',
 'tr|A0A1G6BHE0|A0A1G6BHE0_9FIRM Ammonium transporter',
 'tr|A0A1G6C6K5|A0A1G6C6K5_9FIRM Ammonium transporter',
 'tr|A0A1G6KUG1|A0A1G6KUG1_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Succiniclasticum ruminis OX=40841 GN=SAMN04487864_105108 PE=3 SV=1',
 'tr|A0A1G7RHP6|A0A1G7RHP6_9EURY Ammonium transporter OS=Halorubrum xinjiangense OX=261291 GN=SAMN04488067_11550 PE=3 SV=1',
 'tr|A0A1G8BB52|A0A1G8BB52_9FIRM Ammonium transporter',
 'tr|A0A1G8V2D8|A0A1G8V2D8_9FIRM Ammonium transporter',
 'tr|A0A1G8VFZ5|A0A1G8VFZ5_9EURY Ammonium transporter',
 'tr|A0A1G9BC39|A0A1G9BC39_9EURY Ammonium transporter',
 'tr|A0A1G9IKK4|A0A1G9IKK4_9CLOT Ammonium transporter',
 'tr|A0A1G9THY2|A0A1G9THY2_9FIRM Ammonium transporter',
 'tr|A0A1G9XUV1|A0A1G9XUV1_9FIRM Ammonium transporter',
 'tr|A0A1H2V0V3|A0A1H2V0V3_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Lachnospiraceae bacterium KHCPX20 OX=1855375 GN=SAMN05216391_11266 PE=3 SV=1',
 'tr|A0A1H3HZ52|A0A1H3HZ52_9FIRM Ammonium transporter',
 'tr|A0A1H3LXY5|A0A1H3LXY5_9EURY Ammonium transporter',
 'tr|A0A1H3Z0R0|A0A1H3Z0R0_9EURY Ammonium transporter',
 'tr|A0A1H3ZKY2|A0A1H3ZKY2_9FIRM Ammonium transporter',
 'tr|A0A1H4EZX0|A0A1H4EZX0_9FIRM Ammonium transporter',
 'tr|A0A1H5WFC4|A0A1H5WFC4_9FIRM Ammonium transporter',
 'tr|A0A1H5YYF4|A0A1H5YYF4_9FIRM Ammonium transporter',
 'tr|A0A1H6INP9|A0A1H6INP9_9EURY Ammonium transporter',
 'tr|A0A1H6J2A5|A0A1H6J2A5_RUMFL Ammonium transporter',
 'tr|A0A1H6R9C6|A0A1H6R9C6_9EURY Ammonium transporter',
 'tr|A0A1H6W8Z9|A0A1H6W8Z9_9FIRM Ammonium transporter',
 'tr|A0A1H7IQT2|A0A1H7IQT2_9FIRM Ammonium transporter',
 'tr|A0A1H7M3E0|A0A1H7M3E0_9FIRM Nitrogen regulatory protein P-II family OS=Butyrivibrio sp. ob235 OX=1761780 GN=SAMN04487770_105122 PE=3 SV=1',
 'tr|A0A1H7NPU9|A0A1H7NPU9_RUMAL Ammonium transporter',
 'tr|A0A1H8S6J8|A0A1H8S6J8_9BACI Ammonium transporter',
 'tr|A0A1H9A9D8|A0A1H9A9D8_9FIRM Ammonium transporter',
 'tr|A0A1H9J573|A0A1H9J573_9EURY Ammonium transporter',
 'tr|A0A1H9P153|A0A1H9P153_BUTFI Ammonium transporter',
 'tr|A0A1H9Z210|A0A1H9Z210_9FIRM Ammonium transporter',
 'tr|A0A1I0G858|A0A1I0G858_9FIRM Ammonium transporter',
 'tr|A0A1I0H5B4|A0A1I0H5B4_9EURY Ammonium transporter',
 'tr|A0A1I0HDV9|A0A1I0HDV9_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Enterocloster clostridioformis OX=1531 GN=SAMN05216521_102715 PE=3 SV=1',
 'tr|A0A1I0IK57|A0A1I0IK57_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Enterocloster lavalensis OX=460384 GN=SAMN05216313_1227 PE=3 SV=1',
 'tr|A0A1I0PYA2|A0A1I0PYA2_9FIRM Ammonium transporter',
 'tr|A0A1I0QEC7|A0A1I0QEC7_9EURY Ammonium transporter',
 'tr|A0A1I0ZNG3|A0A1I0ZNG3_9FIRM Ammonium transporter',
 'tr|A0A1I1D0R6|A0A1I1D0R6_RUMAL Ammonium transporter',
 'tr|A0A1I1HT54|A0A1I1HT54_HALHE Ammonium transporter',
 'tr|A0A1I2AKI3|A0A1I2AKI3_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Succiniclasticum ruminis DSM 9236 OX=1123323 GN=SAMN05216245_10659 PE=3 SV=1',
 'tr|A0A1I2TGT7|A0A1I2TGT7_9FIRM Ammonium transporter',
 'tr|A0A1I3B7Y0|A0A1I3B7Y0_9EURY Ammonium transporter',
 'tr|A0A1I3FXW0|A0A1I3FXW0_9FIRM Ammonium transporter',
 'tr|A0A1I3M286|A0A1I3M286_9EURY Ammonium transporter',
 'tr|A0A1I4EUS9|A0A1I4EUS9_9FIRM Ammonium transporter',
 'tr|A0A1I4ZMN5|A0A1I4ZMN5_9FIRM Ammonium transporter',
 'tr|A0A1I5FF58|A0A1I5FF58_9FIRM Ammonium transporter',
 'tr|A0A1I5RRK2|A0A1I5RRK2_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Oscillibacter sp. PC13 OX=1855299 GN=SAMN05216343_11071 PE=3 SV=1',
 'tr|A0A1I5SDH6|A0A1I5SDH6_9FIRM Ammonium transporter',
 'tr|A0A1I5Y4A3|A0A1I5Y4A3_9LACT Ammonium transporter',
 'tr|A0A1I6FK65|A0A1I6FK65_HALSD Ammonium transporter',
 'tr|A0A1I6JQR0|A0A1I6JQR0_9FIRM Ammonium transporter',
 'tr|A0A1I6KGS1|A0A1I6KGS1_9FIRM Ammonium transporter',
 'tr|A0A1I6PBV6|A0A1I6PBV6_9EURY Ammonium transporter',
 'tr|A0A1I7GLL6|A0A1I7GLL6_9CLOT Nitrogen regulatory protein P-II family /ammonium transporter OS=Clostridium sp. DSM 8431 OX=1761781 GN=SAMN04487886_104017 PE=3 SV=1',
 'tr|A0A1I7IQQ2|A0A1I7IQQ2_9FIRM Ammonium transporter',
 'tr|A0A1I7ITC5|A0A1I7ITC5_9FIRM Ammonium transporter',
 'tr|A0A1J4LTC1|A0A1J4LTC1_9EURY Ammonium transporter OS=Natrialba sp. SSL1 OX=1869245 GN=BBD46_04650 PE=3 SV=1',
 'tr|A0A1K1NCM8|A0A1K1NCM8_RUMFL Ammonium transporter',
 'tr|A0A1K1PQ76|A0A1K1PQ76_9FIRM Ammonium transporter',
 'tr|A0A1L8N3F6|A0A1L8N3F6_9SPIR Adenylate cyclase OS=Treponema sp. CETP13 OX=1908540 GN=BKP49_00435 PE=3 SV=1',
 'tr|A0A1L8STM4|A0A1L8STM4_9ENTE Ammonium transporter OS=Enterococcus devriesei OX=319970 GN=RV00_GL002634 PE=3 SV=1',
 'tr|A0A1M2Z9L9|A0A1M2Z9L9_9FIRM Adenylate cyclase OS=Clostridiales bacterium 43-6 OX=1895747 GN=BGN88_13305 PE=3 SV=1',
 'tr|A0A1M4ZJQ1|A0A1M4ZJQ1_9FIRM Ammonium transporter',
 'tr|A0A1M5QDY1|A0A1M5QDY1_9EURY Ammonium transporter',
 'tr|A0A1M6AMI5|A0A1M6AMI5_9FIRM Nitrogen regulatory protein P-II family /ammonium transporter OS=Thermoclostridium caenicola OX=659425 GN=SAMN05444373_100193 PE=3 SV=1',
 'tr|A0A1M6CHL9|A0A1M6CHL9_PSEXY Ammonium transporter',
 'tr|A0A1M6FDK6|A0A1M6FDK6_BUTFI Ammonium transporter',
 'tr|A0A1M7LS20|A0A1M7LS20_RUMFL Ammonium transporter',
 'tr|A0A1M7N5X0|A0A1M7N5X0_9FIRM Ammonium transporter',
 'tr|A0A1M7SHA9|A0A1M7SHA9_9FIRM Ammonium transporter',
 'tr|A0A1N7BYW4|A0A1N7BYW4_9EURY Ammonium transporter',
 'tr|A0A1N7EMQ2|A0A1N7EMQ2_9EURY Ammonium transporter',
 'tr|A0A1N7ESV5|A0A1N7ESV5_9EURY Ammonium transporter',
 'tr|A0A1P8RI15|A0A1P8RI15_9EURY Ammonium transporter OS=Natronorubrum daqingense OX=588898 GN=BB347_15195 PE=3 SV=1',
 'tr|A0A1Q6NJY1|A0A1Q6NJY1_9FIRM Adenylate cyclase OS=Eubacterium sp. 38_16 OX=1897002 GN=BHW19_05820 PE=3 SV=1',
 'tr|A0A1Q6PWR8|A0A1Q6PWR8_9FIRM Adenylate cyclase OS=Faecalibacterium sp. CAG:74_58_120 OX=1897005 GN=BHW29_08590 PE=3 SV=1',
 'tr|A0A1Q6QFY3|A0A1Q6QFY3_9FIRM Adenylate cyclase OS=Firmicutes bacterium CAG_194_44_15 OX=1897037 GN=BHW30_09060 PE=3 SV=1',
 'tr|A0A1Q9JE84|A0A1Q9JE84_9FIRM Adenylate cyclase OS=Roseburia sp. 499 OX=1261634 GN=BIV20_12520 PE=3 SV=1',
 'tr|A0A1Q9YFT7|A0A1Q9YFT7_9FIRM Adenylate cyclase OS=Erysipelotrichaceae bacterium NYU-BL-F16 OX=1917462 GN=BM735_02815 PE=3 SV=1',
 'tr|A0A1Q9YMG2|A0A1Q9YMG2_9FIRM Adenylate cyclase OS=Faecalibaculum rodentium OX=1702221 GN=BO223_02350 PE=3 SV=1',

In [39]:
with open('filtere.txt', 'w') as fp:
    for itema in filtere:
        # write each item on a new line
        fp.write("%s\n" % itema)
    print('Done')

Done

In [62]:
filtere11 = np.repeat(filtere, 11)

In [41]:
with open('filtere11.txt', 'w') as fp:
    for itemd in filtere:
        # write each item on a new line
        fp.write("%s\n" % itemd)
    print('Done')

Done

In [63]:
len(filtere11)

11561

In [64]:
df = pd.DataFrame(filtere11)

In [44]:

# opening the file in read mode 
my_file = open("filtere11.txt", "r") 
  
# reading the file 
data = my_file.read() 
  
# replacing end of line('/n') with ' ' and 
# splitting the text it further when '.' is seen. 
filtere = data.replace('\n', ' ').split(".") 
  
# printing the data 
print(filtere) 
my_file.close()

['tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp', ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp', ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp', ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0H5SG89|A0A0H5SG89_HERHM Putative membrane protein OS=Herbinix hemicellulosilytica OX=1564487 GN=HHT355_0827 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J6ZRU4|A0A0J6ZRU4_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=Megasphaera cerevisiae DSM 20462 OX=1122219 GN=AB840_01505 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0J9EMW5|A0A0J9EMW5_9FIRM Ammonium transporter AmtB-like domain-containing protein OS=[Clostridium] citroniae WAL-19142 OX=742734 GN=HMPREF9470_03668 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M2NHW4|A0A0M2NHW4_9FIRM Ammonium transporter OS=Christensenella hongkongensis OX=270498 GN=CHK_0399 PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M6WCZ2|A0A0M6WCZ2_9FIRM Adenylate/guanylate cyclase OS=Agathobacter rectalis OX=39491 GN=amt PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0M9AS13|A0A0M9AS13_9EURY Ammonium transporter OS=Halorubrum tropicale OX=1765655 GN=AMR74_01795 PE=3 SV=1 tr|A0A0S2W112|A0A0S2W112_9FIRM Am

In [59]:
filtere

['tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cyclase OS=Ruminococcus albus SY3 OX=1341156 GN=RASY3_13175 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A063ZJU6|A0A063ZJU6_9EURY Ammonium transporter OS=Halostagnicola sp',
 ' A56 OX=1495067 GN=EL22_10090 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A081EVR3|A0A081EVR3_9EURY Ammonium transporter OS=Halorubrum saccharovorum OX=2248 GN=FK85_01485 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A099I9L1|A0A099I9L1_CLOIN Adenylate cyclase OS=Clostridium innocuum OX=1522 GN=CIAN88_08185 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0D8IWY3|A0A0D8IWY3_9FIRM Adenylate cyclase OS=Ruthenibacterium lactatiformans OX=1550024 GN=TQ39_16150 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0E2HBL2|A0A0E2HBL2_9FIRM Ammonium transporter OS=[Clostridium] clostridioforme 90A8 OX=999408 GN=HMPREF1090_02007 PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0F0CIE1|A0A0F0CIE1_9CLOT Ammonium transporter NrgA OS=Clostridium sp',
 ' FS41 OX=1609975 GN=nrgA PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G3WG46|A0A0G3WG46_9BACT Ammonium transporter OS=Endomicrobium proavitum OX=1408281 GN=amtB PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',
 ' C8 OX=1667357 GN=AAT22_02580 PE=3 SV=1 tr|A0A0G9LEF6|A0A0G9LEF6_9CLOT Adenylate cyclase OS=Clostridium sp',

In [65]:
df

                                                       0
0      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...
1      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...
2      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...
3      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...
4      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...
...                                                  ...
11556  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...
11557  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...
11558  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...
11559  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...
11560  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...

[11561 rows x 1 columns]

In [55]:
len(hip)

1051

In [46]:
str_end = []


for boots in hip:
    result = u.search(boots, frmt="tsv", columns='ft_transmem')
#     print(result)
    transmems = result.split("\n")[1]
    transmems = re.findall("(?<=TRANSMEM )(?P<tmemstart>[0-9]*)..(?P<tmemend>[0-9]*)", transmems)
#     print(transmems)
    transmems = [(int(start), int(end)) for start, end in transmems]
#     print(transmems)
    starts = list(parse_ft_transmembrane(result))
    if len(starts) != 11:
        print(f"{boots} has {len(starts)} helices, will use last 11")
        starts = starts[-11:]
    for start, end in starts:
        print(f"{boots}/{start}-{end}'")
        backs = f'/{start}-{end}'
        str_end.append(backs)

A0A011VQM7/20-40'
A0A011VQM7/61-78'
A0A011VQM7/98-119'
A0A011VQM7/131-152'
A0A011VQM7/164-186'
A0A011VQM7/207-226'
A0A011VQM7/241-262'
A0A011VQM7/269-287'
A0A011VQM7/293-313'
A0A011VQM7/325-344'
A0A011VQM7/374-399'
A0A063ZJU6/20-39'
A0A063ZJU6/60-82'
A0A063ZJU6/102-125'
A0A063ZJU6/137-159'
A0A063ZJU6/179-200'
A0A063ZJU6/221-238'
A0A063ZJU6/265-286'
A0A063ZJU6/293-311'
A0A063ZJU6/317-337'
A0A063ZJU6/349-369'
A0A063ZJU6/381-402'
A0A081EVR3/20-37'
A0A081EVR3/58-79'
A0A081EVR3/99-119'
A0A081EVR3/126-149'
A0A081EVR3/161-182'
A0A081EVR3/203-220'
A0A081EVR3/240-265'
A0A081EVR3/277-293'
A0A081EVR3/299-317'
A0A081EVR3/329-352'
A0A081EVR3/364-385'
A0A099I9L1/6-28'
A0A099I9L1/49-71'
A0A099I9L1/91-112'
A0A099I9L1/124-145'
A0A099I9L1/157-178'
A0A099I9L1/199-216'
A0A099I9L1/236-257'
A0A099I9L1/264-281'
A0A099I9L1/287-308'
A0A099I9L1/320-342'
A0A099I9L1/362-382'
A0A0D8IWY3/6-28'
A0A0D8IWY3/49-67'
A0A0D8IWY3/87-108'
A0A0D8IWY3/120-141'
A0A0D8IWY3/153-174'
A0A0D8IWY3/195-212'
A0A0D8IWY3/232-253'
A0A0D8IWY3/260-277'
A0A0D8IWY3/283-304'
A0A0D8IWY3/316-335'
A0A0D8IWY3/341-374'
A0A0E2HBL2/6-28'
A0A0E2HBL2/49-73'
A0A0E2HBL2/93-114'
A0A0E2HBL2/121-145'
A0A0E2HBL2/157-178'
A0A0E2HBL2/199-216'
A0A0E2HBL2/236-257'
A0A0E2HBL2/264-282'
A0A0E2HBL2/288-308'
A0A0E2HBL2/320-340'
A0A0E2HBL2/352-378'
A0A0F0CIE1/6-28'
A0A0F0CIE1/49-73'
A0A0F0CIE1/93-114'
A0A0F0CIE1/121-145'
A0A0F0CIE1/157-178'
A0A0F0CIE1/199-216'
A0A0F0CIE1/236-257'
A0A0F0CIE1/264-282'
A0A0F0CIE1/288-308'
A0A0F0CIE1/320-340'
A0A0F0CIE1/352-378'
A0A0G3WG46/12-31'
A0A0G3WG46/52-78'
A0A0G3WG46/90-111'
A0A0G3WG46/123-144'
A0A0G3WG46/156-177'
A0A0G3WG46/198-215'
A0A0G3WG46/227-252'
A0A0G3WG46/264-284'
A0A0G3WG46/290-306'
A0A0G3WG46/318-338'
A0A0G3WG46/350-376'
A0A0G9LEF6/6-26'
A0A0G9LEF6/47-68'
A0A0G9LEF6/103-121'
A0A0G9LEF6/128-151'
A0A0G9LEF6/163-184'
A0A0G9LEF6/205-222'
A0A0G9LEF6/242-262'
A0A0G9LEF6/269-289'
A0A0G9LEF6/295-311'
A0A0G9LEF6/323-341'
A0A0G9LEF6/361-388'
A0A0H5SG89/6-26'
A0A0H5SG89/47-65'
A0A0H5SG89/103-121'
A0A0H5SG89/128-150'
A0A0H5SG89/170-188'
A0A0H5SG89/200-219'
A0A0H5SG89/239-262'
A0A0H5SG89/269-289'
A0A0H5SG89/295-311'
A0A0H5SG89/323-341'
A0A0H5SG89/367-388'
A0A0J6ZRU4/12-33'
A0A0J6ZRU4/45-65'
A0A0J6ZRU4/94-113'
A0A0J6ZRU4/120-141'
A0A0J6ZRU4/156-176'
A0A0J6ZRU4/197-221'
A0A0J6ZRU4/233-252'
A0A0J6ZRU4/259-276'
A0A0J6ZRU4/282-303'
A0A0J6ZRU4/315-335'
A0A0J6ZRU4/347-372'
A0A0J9EMW5/6-28'
A0A0J9EMW5/49-73'
A0A0J9EMW5/93-114'
A0A0J9EMW5/121-145'
A0A0J9EMW5/157-178'
A0A0J9EMW5/199-216'
A0A0J9EMW5/236-257'
A0A0J9EMW5/264-282'
A0A0J9EMW5/288-308'
A0A0J9EMW5/320-340'
A0A0J9EMW5/352-378'
A0A0M2NHW4/6-27'
A0A0M2NHW4/48-71'
A0A0M2NHW4/91-109'
A0A0M2NHW4/121-141'
A0A0M2NHW4/161-179'
A0A0M2NHW4/191-212'
A0A0M2NHW4/232-253'
A0A0M2NHW4/260-277'
A0A0M2NHW4/283-304'
A0A0M2NHW4/316-336'
A0A0M2NHW4/348-374'
A0A0M6WCZ2/6-28'
A0A0M6WCZ2/49-68'
A0A0M6WCZ2/95-112'
A0A0M6WCZ2/119-143'
A0A0M6WCZ2/155-176'
A0A0M6WCZ2/197-219'
A0A0M6WCZ2/231-254'
A0A0M6WCZ2/261-278'
A0A0M6WCZ2/284-305'
A0A0M6WCZ2/326-346'
A0A0M6WCZ2/366-390'
A0A0M9AS13/20-40'
A0A0M9AS13/61-91'
A0A0M9AS13/111-131'
A0A0M9AS13/138-158'
A0A0M9AS13/178-198'
A0A0M9AS13/219-236'
A0A0M9AS13/256-278'
A0A0M9AS13/285-302'
A0A0M9AS13/308-326'
A0A0M9AS13/338-361'
A0A0M9AS13/373-398'
A0A0S2W112/6-27'
A0A0S2W112/48-72'
A0A0S2W112/92-113'
A0A0S2W112/120-144'
A0A0S2W112/156-177'
A0A0S2W112/198-215'
A0A0S2W112/230-256'
A0A0S2W112/263-280'
A0A0S2W112/286-307'
A0A0S2W112/319-339'
A0A0S2W112/351-374'
A0A0U5JBG5/6-25'
A0A0U5JBG5/46-65'
A0A0U5JBG5/105-123'
A0A0U5JBG5/130-153'
A0A0U5JBG5/165-186'
A0A0U5JBG5/207-224'
A0A0U5JBG5/239-262'
A0A0U5JBG5/269-288'
A0A0U5JBG5/294-313'
A0A0U5JBG5/325-344'
A0A0U5JBG5/364-387'
A0A0W7TMH6/6-28'
A0A0W7TMH6/49-67'
A0A0W7TMH6/87-108'
A0A0W7TMH6/120-141'
A0A0W7TMH6/153-174'
A0A0W7TMH6/195-212'
A0A0W7TMH6/232-253'
A0A0W7TMH6/260-277'
A0A0W7TMH6/283-304'
A0A0W7TMH6/316-335'
A0A0W7TMH6/341-374'
A0A136Q6K1/6-27'
A0A136Q6K1/48-71'
A0A136Q6K1/91-113'
A0A136Q6K1/120-142'
A0A136Q6K1/154-175'
A0A136Q6K1/196-213'
A0A136Q6K1/233-253'
A0A136Q6K1/260-278'
A0A136Q6K1/284-304'
A0A136Q6K1/316-336'
A0A136Q6K1/348-374'
A0A136WGT4/15-36'
A0A136WGT4/57-84'
A0A136WGT4/96-118'
A0A136WGT4/125-142'
A0A136WGT4/162-184'
A0A136WGT4/205-225'
A0A136WGT4/237-260'
A0A136WGT4/267-284'
A0A136WGT4/290-311'
A0A136WGT4/323-343'
A0A136WGT4/363-384'
A0A140DTE7/12-31'
A0A140DTE7/52-74'
A0A140DTE7/94-111'
A0A140DTE7/118-135'
A0A140DTE7/155-176'
A0A140DTE7/196-213'
A0A140DTE7/225-248'
A0A140DTE7/255-272'
A0A140DTE7/278-299'
A0A140DTE7/311-331'
A0A140DTE7/351-376'
A0A143Y517/12-32'
A0A143Y517/44-64'
A0A143Y517/99-120'
A0A143Y517/127-148'
A0A143Y517/160-184'
A0A143Y517/196-214'
A0A143Y517/226-245'
A0A143Y517/257-275'
A0A143Y517/281-301'
A0A143Y517/313-332'
A0A143Y517/352-374'
A0A143Y9S4/12-34'
A0A143Y9S4/46-65'
A0A143Y9S4/95-115'
A0A143Y9S4/127-148'
A0A143Y9S4/160-184'
A0A143Y9S4/196-214'
A0A143Y9S4/226-245'
A0A143Y9S4/257-275'
A0A143Y9S4/281-301'
A0A143Y9S4/313-332'
A0A143Y9S4/352-374'
A0A143YNF2/12-34'
A0A143YNF2/46-65'
A0A143YNF2/99-120'
A0A143YNF2/127-148'
A0A143YNF2/160-184'
A0A143YNF2/196-214'
A0A143YNF2/220-245'
A0A143YNF2/257-278'
A0A143YNF2/284-301'
A0A143YNF2/313-332'
A0A143YNF2/352-374'
A0A143YTA3/6-27'
A0A143YTA3/48-72'
A0A143YTA3/92-112'
A0A143YTA3/119-140'
A0A143YTA3/152-173'
A0A143YTA3/193-210'
A0A143YTA3/230-250'
A0A143YTA3/262-280'
A0A143YTA3/286-302'
A0A143YTA3/314-334'
A0A143YTA3/346-369'
A0A143YZV1/6-27'
A0A143YZV1/48-72'
A0A143YZV1/92-112'
A0A143YZV1/119-140'
A0A143YZV1/152-173'
A0A143YZV1/193-210'
A0A143YZV1/230-250'
A0A143YZV1/262-280'
A0A143YZV1/286-302'
A0A143YZV1/314-334'
A0A143YZV1/346-369'
A0A143Z212/12-34'
A0A143Z212/46-66'
A0A143Z212/95-115'
A0A143Z212/127-148'
A0A143Z212/160-184'
A0A143Z212/196-214'
A0A143Z212/226-246'
A0A143Z212/258-275'
A0A143Z212/281-301'
A0A143Z212/313-332'
A0A143Z212/352-374'
A0A143ZCA8/12-33'
A0A143ZCA8/45-63'
A0A143ZCA8/94-114'
A0A143ZCA8/126-147'
A0A143ZCA8/159-183'
A0A143ZCA8/195-213'
A0A143ZCA8/225-244'
A0A143ZCA8/256-274'
A0A143ZCA8/280-297'
A0A143ZCA8/309-331'
A0A143ZCA8/351-373'
A0A151AI36/14-34'
A0A151AI36/55-82'
A0A151AI36/102-122'
A0A151AI36/129-150'
A0A151AI36/162-183'
A0A151AI36/204-221'
A0A151AI36/248-270'
A0A151AI36/277-293'
A0A151AI36/299-317'
A0A151AI36/329-353'
A0A151AI36/359-384'
A0A169X118/6-30'
A0A169X118/51-72'
A0A169X118/103-123'
A0A169X118/130-151'
A0A169X118/163-184'
A0A169X118/205-222'
A0A169X118/249-270'
A0A169X118/277-294'
A0A169X118/300-318'
A0A169X118/330-356'
A0A169X118/368-390'
A0A173R3X4/12-32'
A0A173R3X4/53-72'
A0A173R3X4/96-116'
A0A173R3X4/123-147'
A0A173R3X4/159-180'
A0A173R3X4/201-223'
A0A173R3X4/235-258'
A0A173R3X4/265-282'
A0A173R3X4/288-309'
A0A173R3X4/321-341'
A0A173R3X4/361-386'
A0A173R662/12-32'
A0A173R662/53-73'
A0A173R662/93-114'
A0A173R662/126-147'
A0A173R662/159-180'
A0A173R662/201-223'
A0A173R662/235-258'
A0A173R662/265-282'
A0A173R662/288-309'
A0A173R662/330-349'
A0A173R662/369-394'
A0A173V441/12-32'
A0A173V441/53-71'
A0A173V441/91-110'
A0A173V441/122-143'
A0A173V441/155-176'
A0A173V441/197-214'
A0A173V441/226-255'
A0A173V441/262-280'
A0A173V441/286-306'
A0A173V441/318-336'
A0A173V441/356-378'
A0A173X4T2/6-28'
A0A173X4T2/49-68'
A0A173X4T2/95-112'
A0A173X4T2/119-143'
A0A173X4T2/155-176'
A0A173X4T2/197-219'
A0A173X4T2/231-254'
A0A173X4T2/261-278'
A0A173X4T2/284-305'
A0A173X4T2/326-346'
A0A173X4T2/366-390'
A0A173XV88/6-28'
A0A173XV88/49-73'
A0A173XV88/93-114'
A0A173XV88/126-147'
A0A173XV88/159-180'
A0A173XV88/201-218'
A0A173XV88/238-258'
A0A173XV88/265-282'
A0A173XV88/288-309'
A0A173XV88/321-339'
A0A173XV88/359-381'
A0A173XVK8/6-27'
A0A173XVK8/48-66'
A0A173XVK8/86-107'
A0A173XVK8/119-140'
A0A173XVK8/152-173'
A0A173XVK8/194-211'
A0A173XVK8/231-252'
A0A173XVK8/259-276'
A0A173XVK8/282-303'
A0A173XVK8/315-335'
A0A173XVK8/347-373'
A0A173Z4K3/6-28'
A0A173Z4K3/49-73'
A0A173Z4K3/93-114'
A0A173Z4K3/126-147'
A0A173Z4K3/159-180'
A0A173Z4K3/201-218'
A0A173Z4K3/238-258'
A0A173Z4K3/265-282'
A0A173Z4K3/288-309'
A0A173Z4K3/321-339'
A0A173Z4K3/359-381'
A0A173ZTK6/6-32'
A0A173ZTK6/44-64'
A0A173ZTK6/92-111'
A0A173ZTK6/123-144'
A0A173ZTK6/156-177'
A0A173ZTK6/198-215'
A0A173ZTK6/235-256'
A0A173ZTK6/263-280'
A0A173ZTK6/286-307'
A0A173ZTK6/319-338'
A0A173ZTK6/358-381'
A0A174C5U1/6-28'
A0A174C5U1/49-73'
A0A174C5U1/93-114'
A0A174C5U1/121-145'
A0A174C5U1/157-178'
A0A174C5U1/199-216'
A0A174C5U1/236-257'
A0A174C5U1/264-282'
A0A174C5U1/288-308'
A0A174C5U1/320-340'
A0A174C5U1/352-378'
A0A174D1D6/6-28'
A0A174D1D6/49-73'
A0A174D1D6/93-114'
A0A174D1D6/126-147'
A0A174D1D6/159-180'
A0A174D1D6/201-218'
A0A174D1D6/238-258'
A0A174D1D6/265-282'
A0A174D1D6/288-309'
A0A174D1D6/321-339'
A0A174D1D6/359-381'
A0A174H6C4/6-27'
A0A174H6C4/48-66'
A0A174H6C4/86-107'
A0A174H6C4/119-140'
A0A174H6C4/152-173'
A0A174H6C4/194-211'
A0A174H6C4/231-252'
A0A174H6C4/259-277'
A0A174H6C4/283-303'
A0A174H6C4/315-335'
A0A174H6C4/347-373'
A0A174JG28/6-28'
A0A174JG28/49-73'
A0A174JG28/93-114'
A0A174JG28/126-147'
A0A174JG28/159-180'
A0A174JG28/201-218'
A0A174JG28/238-258'
A0A174JG28/265-282'
A0A174JG28/288-309'
A0A174JG28/321-339'
A0A174JG28/359-381'
A0A174RYE8/6-28'
A0A174RYE8/49-73'
A0A174RYE8/93-114'
A0A174RYE8/126-147'
A0A174RYE8/159-180'
A0A174RYE8/201-218'
A0A174RYE8/238-258'
A0A174RYE8/265-282'
A0A174RYE8/288-309'
A0A174RYE8/321-339'
A0A174RYE8/359-381'
A0A174TIU3/12-32'
A0A174TIU3/53-72'
A0A174TIU3/96-116'
A0A174TIU3/123-147'
A0A174TIU3/159-180'
A0A174TIU3/201-223'
A0A174TIU3/235-258'
A0A174TIU3/265-282'
A0A174TIU3/288-309'
A0A174TIU3/321-341'
A0A174TIU3/361-386'
A0A174VZ55/6-28'
A0A174VZ55/49-73'
A0A174VZ55/93-114'
A0A174VZ55/126-147'
A0A174VZ55/159-180'
A0A174VZ55/201-218'
A0A174VZ55/238-258'
A0A174VZ55/265-282'
A0A174VZ55/288-309'
A0A174VZ55/321-339'
A0A174VZ55/359-381'
A0A174XKK3/6-26'
A0A174XKK3/47-69'
A0A174XKK3/89-110'
A0A174XKK3/122-143'
A0A174XKK3/155-176'
A0A174XKK3/197-214'
A0A174XKK3/234-254'
A0A174XKK3/261-278'
A0A174XKK3/284-302'
A0A174XKK3/314-336'
A0A174XKK3/342-372'
A0A174YTX7/12-34'
A0A174YTX7/55-73'
A0A174YTX7/93-115'
A0A174YTX7/122-146'
A0A174YTX7/158-179'
A0A174YTX7/200-222'
A0A174YTX7/234-257'
A0A174YTX7/264-281'
A0A174YTX7/287-308'
A0A174YTX7/329-349'
A0A174YTX7/369-394'
A0A174Z5H4/12-34'
A0A174Z5H4/55-73'
A0A174Z5H4/93-115'
A0A174Z5H4/122-146'
A0A174Z5H4/158-179'
A0A174Z5H4/200-222'
A0A174Z5H4/234-257'
A0A174Z5H4/264-281'
A0A174Z5H4/287-308'
A0A174Z5H4/329-349'
A0A174Z5H4/369-394'
A0A175A4T9/33-53'
A0A175A4T9/74-99'
A0A175A4T9/119-136'
A0A175A4T9/143-165'
A0A175A4T9/185-204'
A0A175A4T9/216-236'
A0A175A4T9/248-273'
A0A175A4T9/280-297'
A0A175A4T9/303-324'
A0A175A4T9/336-355'
A0A175A4T9/375-400'
A0A1B1YE78/12-34'
A0A1B1YE78/46-65'
A0A1B1YE78/103-122'
A0A1B1YE78/129-151'
A0A1B1YE78/163-184'
A0A1B1YE78/205-222'
A0A1B1YE78/242-262'
A0A1B1YE78/269-289'
A0A1B1YE78/295-311'
A0A1B1YE78/323-342'
A0A1B1YE78/362-388'
A0A1B1YLE9/12-34'
A0A1B1YLE9/46-65'
A0A1B1YLE9/103-122'
A0A1B1YLE9/129-151'
A0A1B1YLE9/163-184'
A0A1B1YLE9/205-222'
A0A1B1YLE9/242-262'
A0A1B1YLE9/269-289'
A0A1B1YLE9/295-311'
A0A1B1YLE9/323-342'
A0A1B1YLE9/362-388'
A0A1C0BVB4/12-29'
A0A1C0BVB4/50-67'
A0A1C0BVB4/89-110'
A0A1C0BVB4/122-143'
A0A1C0BVB4/155-176'
A0A1C0BVB4/197-214'
A0A1C0BVB4/234-255'
A0A1C0BVB4/262-279'
A0A1C0BVB4/285-306'
A0A1C0BVB4/318-338'
A0A1C0BVB4/350-376'
A0A1C5M0W8/14-35'
A0A1C5M0W8/56-79'
A0A1C5M0W8/99-116'
A0A1C5M0W8/123-147'
A0A1C5M0W8/159-180'
A0A1C5M0W8/201-223'
A0A1C5M0W8/235-258'
A0A1C5M0W8/265-283'
A0A1C5M0W8/289-309'
A0A1C5M0W8/321-346'
A0A1C5M0W8/366-387'
A0A1C5MDL8/6-28'
A0A1C5MDL8/49-73'
A0A1C5MDL8/93-114'
A0A1C5MDL8/126-147'
A0A1C5MDL8/159-180'
A0A1C5MDL8/201-218'
A0A1C5MDL8/238-258'
A0A1C5MDL8/265-282'
A0A1C5MDL8/288-309'
A0A1C5MDL8/321-339'
A0A1C5MDL8/359-381'
A0A1C5N7S1/6-28'
A0A1C5N7S1/49-73'
A0A1C5N7S1/93-114'
A0A1C5N7S1/121-145'
A0A1C5N7S1/157-178'
A0A1C5N7S1/199-216'
A0A1C5N7S1/236-257'
A0A1C5N7S1/264-282'
A0A1C5N7S1/288-308'
A0A1C5N7S1/320-340'
A0A1C5N7S1/352-378'
A0A1C5PFK7/6-28'
A0A1C5PFK7/49-73'
A0A1C5PFK7/93-114'
A0A1C5PFK7/126-147'
A0A1C5PFK7/159-180'
A0A1C5PFK7/201-218'
A0A1C5PFK7/238-258'
A0A1C5PFK7/265-282'
A0A1C5PFK7/288-309'
A0A1C5PFK7/321-339'
A0A1C5PFK7/359-381'
A0A1C5PIG4/14-35'
A0A1C5PIG4/56-79'
A0A1C5PIG4/99-116'
A0A1C5PIG4/123-140'
A0A1C5PIG4/160-180'
A0A1C5PIG4/201-223'
A0A1C5PIG4/235-258'
A0A1C5PIG4/265-282'
A0A1C5PIG4/288-309'
A0A1C5PIG4/321-340'
A0A1C5PIG4/382-401'
A0A1C5PQC5/20-39'
A0A1C5PQC5/60-81'
A0A1C5PQC5/101-121'
A0A1C5PQC5/128-152'
A0A1C5PQC5/164-184'
A0A1C5PQC5/205-228'
A0A1C5PQC5/240-263'
A0A1C5PQC5/270-287'
A0A1C5PQC5/293-314'
A0A1C5PQC5/326-346'
A0A1C5PQC5/366-388'
A0A1C5QAX9/14-35'
A0A1C5QAX9/56-79'
A0A1C5QAX9/99-116'
A0A1C5QAX9/123-140'
A0A1C5QAX9/160-180'
A0A1C5QAX9/201-223'
A0A1C5QAX9/235-258'
A0A1C5QAX9/265-282'
A0A1C5QAX9/288-309'
A0A1C5QAX9/321-340'
A0A1C5QAX9/376-401'
A0A1C5QDA2/6-27'
A0A1C5QDA2/48-71'
A0A1C5QDA2/91-110'
A0A1C5QDA2/122-143'
A0A1C5QDA2/155-176'
A0A1C5QDA2/197-214'
A0A1C5QDA2/234-255'
A0A1C5QDA2/262-280'
A0A1C5QDA2/286-306'
A0A1C5QDA2/318-336'
A0A1C5QDA2/356-378'
A0A1C5QHK8/12-30'
A0A1C5QHK8/51-74'
A0A1C5QHK8/94-113'
A0A1C5QHK8/125-146'
A0A1C5QHK8/158-179'
A0A1C5QHK8/200-217'
A0A1C5QHK8/237-258'
A0A1C5QHK8/265-283'
A0A1C5QHK8/289-309'
A0A1C5QHK8/321-341'
A0A1C5QHK8/353-379'
A0A1C5QX74/20-39'
A0A1C5QX74/60-83'
A0A1C5QX74/103-124'
A0A1C5QX74/131-148'
A0A1C5QX74/168-188'
A0A1C5QX74/209-226'
A0A1C5QX74/246-266'
A0A1C5QX74/273-290'
A0A1C5QX74/296-317'
A0A1C5QX74/329-348'
A0A1C5QX74/368-391'
A0A1C5R1D9/14-35'
A0A1C5R1D9/56-79'
A0A1C5R1D9/99-116'
A0A1C5R1D9/123-147'
A0A1C5R1D9/159-180'
A0A1C5R1D9/201-223'
A0A1C5R1D9/235-258'
A0A1C5R1D9/265-283'
A0A1C5R1D9/289-309'
A0A1C5R1D9/321-346'
A0A1C5R1D9/366-387'
A0A1C5R365/12-32'
A0A1C5R365/53-71'
A0A1C5R365/91-110'
A0A1C5R365/122-143'
A0A1C5R365/155-176'
A0A1C5R365/197-214'
A0A1C5R365/234-255'
A0A1C5R365/262-280'
A0A1C5R365/286-306'
A0A1C5R365/318-340'
A0A1C5R365/360-378'
A0A1C5R381/6-27'
A0A1C5R381/48-73'
A0A1C5R381/93-115'
A0A1C5R381/122-142'
A0A1C5R381/162-181'
A0A1C5R381/193-215'
A0A1C5R381/235-256'
A0A1C5R381/263-280'
A0A1C5R381/286-304'
A0A1C5R381/316-337'
A0A1C5R381/352-376'
A0A1C5RAN1/6-28'
A0A1C5RAN1/49-73'
A0A1C5RAN1/93-114'
A0A1C5RAN1/126-147'
A0A1C5RAN1/159-180'
A0A1C5RAN1/201-218'
A0A1C5RAN1/238-258'
A0A1C5RAN1/265-282'
A0A1C5RAN1/288-309'
A0A1C5RAN1/321-339'
A0A1C5RAN1/359-381'
A0A1C5S8B5/6-28'
A0A1C5S8B5/49-68'
A0A1C5S8B5/88-109'
A0A1C5S8B5/121-142'
A0A1C5S8B5/154-175'
A0A1C5S8B5/196-213'
A0A1C5S8B5/233-254'
A0A1C5S8B5/261-279'
A0A1C5S8B5/285-305'
A0A1C5S8B5/317-337'
A0A1C5S8B5/349-372'
A0A1C5SQE8/6-27'
A0A1C5SQE8/48-72'
A0A1C5SQE8/92-111'
A0A1C5SQE8/123-144'
A0A1C5SQE8/156-177'
A0A1C5SQE8/198-215'
A0A1C5SQE8/235-256'
A0A1C5SQE8/263-280'
A0A1C5SQE8/286-307'
A0A1C5SQE8/319-338'
A0A1C5SQE8/358-381'
A0A1C5SVL0/6-28'
A0A1C5SVL0/49-73'
A0A1C5SVL0/93-114'
A0A1C5SVL0/126-147'
A0A1C5SVL0/159-180'
A0A1C5SVL0/201-218'
A0A1C5SVL0/238-258'
A0A1C5SVL0/265-282'
A0A1C5SVL0/288-309'
A0A1C5SVL0/321-339'
A0A1C5SVL0/359-381'
A0A1C5T8Y6/6-27'
A0A1C5T8Y6/48-72'
A0A1C5T8Y6/92-113'
A0A1C5T8Y6/125-146'
A0A1C5T8Y6/158-179'
A0A1C5T8Y6/200-217'
A0A1C5T8Y6/237-257'
A0A1C5T8Y6/264-281'
A0A1C5T8Y6/287-308'
A0A1C5T8Y6/320-338'
A0A1C5T8Y6/358-380'
A0A1C5TF49/6-27'
A0A1C5TF49/48-72'
A0A1C5TF49/92-113'
A0A1C5TF49/125-146'
A0A1C5TF49/158-179'
A0A1C5TF49/200-217'
A0A1C5TF49/237-257'
A0A1C5TF49/264-281'
A0A1C5TF49/287-308'
A0A1C5TF49/320-338'
A0A1C5TF49/358-380'
A0A1C5U2K1/14-35'
A0A1C5U2K1/56-79'
A0A1C5U2K1/99-116'
A0A1C5U2K1/123-147'
A0A1C5U2K1/159-180'
A0A1C5U2K1/201-223'
A0A1C5U2K1/235-258'
A0A1C5U2K1/265-283'
A0A1C5U2K1/289-309'
A0A1C5U2K1/321-346'
A0A1C5U2K1/366-387'
A0A1C5UAP1/6-27'
A0A1C5UAP1/48-72'
A0A1C5UAP1/92-113'
A0A1C5UAP1/125-146'
A0A1C5UAP1/158-179'
A0A1C5UAP1/200-217'
A0A1C5UAP1/237-257'
A0A1C5UAP1/264-281'
A0A1C5UAP1/287-308'
A0A1C5UAP1/320-338'
A0A1C5UAP1/358-380'
A0A1C5UEH7/14-35'
A0A1C5UEH7/56-79'
A0A1C5UEH7/99-116'
A0A1C5UEH7/123-147'
A0A1C5UEH7/159-180'
A0A1C5UEH7/201-223'
A0A1C5UEH7/235-258'
A0A1C5UEH7/265-283'
A0A1C5UEH7/289-309'
A0A1C5UEH7/321-342'
A0A1C5UEH7/362-387'
A0A1C5UU75/14-35'
A0A1C5UU75/56-79'
A0A1C5UU75/99-116'
A0A1C5UU75/123-147'
A0A1C5UU75/159-180'
A0A1C5UU75/201-223'
A0A1C5UU75/235-258'
A0A1C5UU75/265-282'
A0A1C5UU75/288-309'
A0A1C5UU75/321-342'
A0A1C5UU75/362-387'
A0A1C5VCM0/6-27'
A0A1C5VCM0/48-72'
A0A1C5VCM0/92-113'
A0A1C5VCM0/125-146'
A0A1C5VCM0/158-179'
A0A1C5VCM0/200-217'
A0A1C5VCM0/237-257'
A0A1C5VCM0/264-281'
A0A1C5VCM0/287-308'
A0A1C5VCM0/320-338'
A0A1C5VCM0/358-380'
A0A1C5WY82/14-35'
A0A1C5WY82/56-73'
A0A1C5WY82/99-116'
A0A1C5WY82/123-140'
A0A1C5WY82/160-180'
A0A1C5WY82/201-223'
A0A1C5WY82/235-258'
A0A1C5WY82/265-282'
A0A1C5WY82/288-309'
A0A1C5WY82/321-340'
A0A1C5WY82/376-401'
A0A1C5Y526/12-32'
A0A1C5Y526/53-72'
A0A1C5Y526/99-116'
A0A1C5Y526/123-147'
A0A1C5Y526/159-180'
A0A1C5Y526/201-223'
A0A1C5Y526/235-258'
A0A1C5Y526/265-282'
A0A1C5Y526/288-309'
A0A1C5Y526/321-346'
A0A1C5Y526/366-387'
A0A1C5YFR7/14-35'
A0A1C5YFR7/56-79'
A0A1C5YFR7/99-116'
A0A1C5YFR7/123-147'
A0A1C5YFR7/159-180'
A0A1C5YFR7/201-223'
A0A1C5YFR7/235-258'
A0A1C5YFR7/265-283'
A0A1C5YFR7/289-309'
A0A1C5YFR7/321-346'
A0A1C5YFR7/366-387'
A0A1C5YH18/6-27'
A0A1C5YH18/48-74'
A0A1C5YH18/94-115'
A0A1C5YH18/122-144'
A0A1C5YH18/156-177'
A0A1C5YH18/198-215'
A0A1C5YH18/235-256'
A0A1C5YH18/263-281'
A0A1C5YH18/287-307'
A0A1C5YH18/319-339'
A0A1C5YH18/351-377'
A0A1C5Z331/6-28'
A0A1C5Z331/49-73'
A0A1C5Z331/93-114'
A0A1C5Z331/126-147'
A0A1C5Z331/159-180'
A0A1C5Z331/201-218'
A0A1C5Z331/238-258'
A0A1C5Z331/265-282'
A0A1C5Z331/288-309'
A0A1C5Z331/321-339'
A0A1C5Z331/359-381'
A0A1C5Z9P9/14-35'
A0A1C5Z9P9/56-79'
A0A1C5Z9P9/99-116'
A0A1C5Z9P9/123-147'
A0A1C5Z9P9/159-180'
A0A1C5Z9P9/201-223'
A0A1C5Z9P9/235-258'
A0A1C5Z9P9/265-283'
A0A1C5Z9P9/289-309'
A0A1C5Z9P9/321-342'
A0A1C5Z9P9/362-387'
A0A1C5ZTV2/6-27'
A0A1C5ZTV2/48-73'
A0A1C5ZTV2/93-115'
A0A1C5ZTV2/122-142'
A0A1C5ZTV2/162-181'
A0A1C5ZTV2/193-215'
A0A1C5ZTV2/235-256'
A0A1C5ZTV2/263-280'
A0A1C5ZTV2/286-304'
A0A1C5ZTV2/316-337'
A0A1C5ZTV2/352-376'
A0A1C6B393/14-35'
A0A1C6B393/56-79'
A0A1C6B393/99-116'
A0A1C6B393/123-140'
A0A1C6B393/160-180'
A0A1C6B393/201-223'
A0A1C6B393/235-258'
A0A1C6B393/265-282'
A0A1C6B393/288-309'
A0A1C6B393/321-340'
A0A1C6B393/376-401'
A0A1C6B4K0/20-39'
A0A1C6B4K0/60-83'
A0A1C6B4K0/103-124'
A0A1C6B4K0/131-148'
A0A1C6B4K0/168-188'
A0A1C6B4K0/209-226'
A0A1C6B4K0/246-266'
A0A1C6B4K0/273-290'
A0A1C6B4K0/296-317'
A0A1C6B4K0/329-348'
A0A1C6B4K0/368-391'
A0A1C6BQA1/14-33'
A0A1C6BQA1/54-77'
A0A1C6BQA1/97-116'
A0A1C6BQA1/123-145'
A0A1C6BQA1/157-178'
A0A1C6BQA1/199-216'
A0A1C6BQA1/236-256'
A0A1C6BQA1/263-280'
A0A1C6BQA1/286-307'
A0A1C6BQA1/319-342'
A0A1C6BQA1/362-386'
A0A1C6CXT8/6-28'
A0A1C6CXT8/49-73'
A0A1C6CXT8/93-114'
A0A1C6CXT8/126-147'
A0A1C6CXT8/159-180'
A0A1C6CXT8/201-218'
A0A1C6CXT8/238-258'
A0A1C6CXT8/265-282'
A0A1C6CXT8/288-309'
A0A1C6CXT8/321-339'
A0A1C6CXT8/359-381'
A0A1C6D1W9/6-27'
A0A1C6D1W9/48-73'
A0A1C6D1W9/93-115'
A0A1C6D1W9/122-142'
A0A1C6D1W9/162-181'
A0A1C6D1W9/193-215'
A0A1C6D1W9/235-256'
A0A1C6D1W9/263-280'
A0A1C6D1W9/286-304'
A0A1C6D1W9/316-337'
A0A1C6D1W9/352-376'
A0A1C6DAP7/20-39'
A0A1C6DAP7/60-83'
A0A1C6DAP7/103-124'
A0A1C6DAP7/131-148'
A0A1C6DAP7/168-188'
A0A1C6DAP7/209-226'
A0A1C6DAP7/246-266'
A0A1C6DAP7/273-290'
A0A1C6DAP7/296-317'
A0A1C6DAP7/329-348'
A0A1C6DAP7/368-391'
A0A1C6DLP9/6-26'
A0A1C6DLP9/47-64'
A0A1C6DLP9/90-107'
A0A1C6DLP9/114-138'
A0A1C6DLP9/150-172'
A0A1C6DLP9/193-213'
A0A1C6DLP9/225-248'
A0A1C6DLP9/255-272'
A0A1C6DLP9/278-299'
A0A1C6DLP9/311-330'
A0A1C6DLP9/360-381'
A0A1C6DWH2/6-28'
A0A1C6DWH2/49-66'
A0A1C6DWH2/95-116'
A0A1C6DWH2/123-140'
A0A1C6DWH2/160-180'
A0A1C6DWH2/201-218'
A0A1C6DWH2/238-258'
A0A1C6DWH2/265-282'
A0A1C6DWH2/288-309'
A0A1C6DWH2/321-343'
A0A1C6DWH2/363-389'
A0A1C6E048/20-40'
A0A1C6E048/61-78'
A0A1C6E048/98-119'
A0A1C6E048/131-152'
A0A1C6E048/164-185'
A0A1C6E048/206-228'
A0A1C6E048/240-263'
A0A1C6E048/270-288'
A0A1C6E048/294-314'
A0A1C6E048/326-345'
A0A1C6E048/382-403'
A0A1C6E379/12-32'
A0A1C6E379/53-72'
A0A1C6E379/96-116'
A0A1C6E379/123-147'
A0A1C6E379/159-180'
A0A1C6E379/201-223'
A0A1C6E379/235-258'
A0A1C6E379/265-282'
A0A1C6E379/288-309'
A0A1C6E379/321-341'
A0A1C6E379/361-386'
A0A1C6F4A8/6-27'
A0A1C6F4A8/48-74'

A0A516N903/6-29'
A0A516N903/41-61'
A0A516N903/108-127'
A0A516N903/134-155'
A0A516N903/186-208'
A0A516N903/220-240'
A0A516N903/252-272'
A0A516N903/284-301'
A0A516N903/307-326'
A0A516N903/338-365'
A0A516N903/371-396'
B3PIH2/36-58'
B3PIH2/70-93'
B3PIH2/127-146'
B3PIH2/153-174'
B3PIH2/186-209'
B3PIH2/229-250'
B3PIH2/256-278'
B3PIH2/285-305'
B3PIH2/311-329'
B3PIH2/341-364'
B3PIH2/384-404'
B3PF77/15-35'
B3PF77/47-69'
B3PF77/111-130'
B3PF77/135-152'
B3PF77/177-199'
B3PF77/211-233'
B3PF77/253-275'
B3PF77/282-301'
B3PF77/307-328'
B3PF77/340-357'
B3PF77/363-388'
A0RUZ2/72-93'
A0RUZ2/100-119'
A0RUZ2/191-213'
A0RUZ2/220-241'
A0RUZ2/261-287'
A0RUZ2/299-319'
A0RUZ2/331-355'
A0RUZ2/362-380'
A0RUZ2/386-405'
A0RUZ2/417-436'
A0RUZ2/463-483'
A0RXK8/75-96'
A0RXK8/103-122'
A0RXK8/195-217'
A0RXK8/224-245'
A0RXK8/265-291'
A0RXK8/303-322'
A0RXK8/334-354'
A0RXK8/366-384'
A0RXK8/390-409'
A0RXK8/421-445'
A0RXK8/465-486'
U7VB41/12-35'
U7VB41/47-75'
U7VB41/95-119'
U7VB41/131-153'
U7VB41/165-186'
U7VB41/198-217'
U7VB41/223-248'
U7VB41/260-279'
U7VB41/285-301'
U7VB41/313-336'
U7VB41/348-370'
Q2HD43/30-50'
Q2HD43/62-80'
Q2HD43/120-140'
Q2HD43/147-170'
Q2HD43/190-206'
Q2HD43/218-238'
Q2HD43/250-271'
Q2HD43/278-296'
Q2HD43/302-321'
Q2HD43/342-361'
Q2HD43/381-403'
Q2GX26/36-57'
Q2GX26/69-87'
Q2GX26/125-144'
Q2GX26/156-176'
Q2GX26/188-209'
Q2GX26/230-247'
Q2GX26/259-280'
Q2GX26/292-311'
Q2GX26/317-337'
Q2GX26/349-369'
Q2GX26/389-413'
A0A5C6LWQ1 has 12 helices, if 12, will use last 11, if other won't include
A0A5C6LWQ1/43-65'
A0A5C6LWQ1/77-108'
A0A5C6LWQ1/128-153'
A0A5C6LWQ1/165-185'
A0A5C6LWQ1/197-220'
A0A5C6LWQ1/232-254'
A0A5C6LWQ1/266-290'
A0A5C6LWQ1/297-318'
A0A5C6LWQ1/324-340'
A0A5C6LWQ1/352-371'
A0A5C6LWQ1/391-413'
A0A979GQ79 has 12 helices, if 12, will use last 11, if other won't include
A0A979GQ79/43-65'
A0A979GQ79/77-108'
A0A979GQ79/128-153'
A0A979GQ79/165-185'
A0A979GQ79/197-220'
A0A979GQ79/232-254'
A0A979GQ79/266-290'
A0A979GQ79/297-318'
A0A979GQ79/324-340'
A0A979GQ79/352-371'
A0A979GQ79/391-413'
Q8LRM4/81-107'
Q8LRM4/119-138'
Q8LRM4/181-203'
Q8LRM4/210-231'
Q8LRM4/258-279'
Q8LRM4/300-317'
Q8LRM4/329-355'
Q8LRM4/362-382'
Q8LRM4/388-410'
Q8LRM4/422-440'
Q8LRM4/482-500'
Q8LRM5/81-107'
Q8LRM5/119-138'
Q8LRM5/181-203'
Q8LRM5/210-231'
Q8LRM5/258-279'
Q8LRM5/300-317'
Q8LRM5/329-355'
Q8LRM5/362-382'
Q8LRM5/388-410'
Q8LRM5/422-440'
Q8LRM5/482-500'
A0A2K3DWA2/76-99'
A0A2K3DWA2/111-130'
A0A2K3DWA2/172-190'
A0A2K3DWA2/197-218'
A0A2K3DWA2/245-266'
A0A2K3DWA2/287-304'
A0A2K3DWA2/324-342'
A0A2K3DWA2/349-369'
A0A2K3DWA2/375-397'
A0A2K3DWA2/409-433'
A0A2K3DWA2/462-487'
A8HSA2/55-79'
A8HSA2/91-113'
A8HSA2/147-166'
A8HSA2/173-195'
A8HSA2/215-240'
A8HSA2/261-278'
A8HSA2/298-319'
A8HSA2/326-344'
A8HSA2/350-371'
A8HSA2/383-400'
A8HSA2/430-452'
A0A2K3DQF8/20-41'
A0A2K3DQF8/53-72'
A0A2K3DQF8/115-137'
A0A2K3DQF8/144-165'
A0A2K3DQF8/192-213'
A0A2K3DQF8/234-251'
A0A2K3DQF8/263-289'
A0A2K3DQF8/296-316'
A0A2K3DQF8/322-344'
A0A2K3DQF8/356-374'
A0A2K3DQF8/416-434'
Q6QH01/55-79'
Q6QH01/91-113'
Q6QH01/147-166'
Q6QH01/173-195'
Q6QH01/215-240'
Q6QH01/261-278'
Q6QH01/298-319'
Q6QH01/326-344'
Q6QH01/350-371'
Q6QH01/383-400'
Q6QH01/429-451'
Q8RUT6/76-99'
Q8RUT6/111-130'
Q8RUT6/172-190'
Q8RUT6/197-218'
Q8RUT6/245-266'
Q8RUT6/287-304'
Q8RUT6/324-342'
Q8RUT6/349-369'
Q8RUT6/375-397'
Q8RUT6/409-433'
Q8RUT6/462-487'
Q8LJU0/72-95'
Q8LJU0/107-129'
Q8LJU0/163-181'
Q8LJU0/188-209'
Q8LJU0/229-252'
Q8LJU0/273-290'
Q8LJU0/302-328'
Q8LJU0/335-354'
Q8LJU0/360-383'
Q8LJU0/395-412'
Q8LJU0/462-483'
A0A2K3DPU7 has 12 helices, if 12, will use last 11, if other won't include
A0A2K3DPU7/61-83'
A0A2K3DPU7/103-122'
A0A2K3DPU7/134-156'
A0A2K3DPU7/168-189'
A0A2K3DPU7/227-246'
A0A2K3DPU7/266-292'
A0A2K3DPU7/304-325'
A0A2K3DPU7/337-356'
A0A2K3DPU7/363-381'
A0A2K3DPU7/401-417'
A0A2K3DPU7/437-461'
Q8RUE9 has 12 helices, if 12, will use last 11, if other won't include
Q8RUE9/78-97'
Q8RUE9/109-131'
Q8RUE9/143-164'
Q8RUE9/170-190'
Q8RUE9/202-221'
Q8RUE9/241-267'
Q8RUE9/279-300'
Q8RUE9/312-331'
Q8RUE9/338-356'
Q8RUE9/376-392'
Q8RUE9/412-436'
Q8S2R6 has 12 helices, if 12, will use last 11, if other won't include
Q8S2R6/78-97'
Q8S2R6/109-131'
Q8S2R6/143-164'
Q8S2R6/170-190'
Q8S2R6/202-221'
Q8S2R6/241-267'
Q8S2R6/279-300'
Q8S2R6/312-331'
Q8S2R6/338-356'
Q8S2R6/376-392'
Q8S2R6/412-436'
Q94CJ2 has 12 helices, if 12, will use last 11, if other won't include
Q94CJ2/80-99'
Q94CJ2/111-132'
Q94CJ2/144-166'
Q94CJ2/173-192'
Q94CJ2/204-222'
Q94CJ2/243-263'
Q94CJ2/283-307'
Q94CJ2/319-335'
Q94CJ2/341-362'
Q94CJ2/374-394'
Q94CJ2/414-438'
A0A7C5DH83/34-57'
A0A7C5DH83/69-90'
A0A7C5DH83/125-147'
A0A7C5DH83/154-176'
A0A7C5DH83/196-215'
A0A7C5DH83/227-246'
A0A7C5DH83/258-278'
A0A7C5DH83/290-307'
A0A7C5DH83/313-332'
A0A7C5DH83/344-367'
A0A7C5DH83/387-410'
B3QRJ4/36-59'
B3QRJ4/71-92'
B3QRJ4/127-149'
B3QRJ4/156-178'
B3QRJ4/198-217'
B3QRJ4/229-248'
B3QRJ4/260-280'
B3QRJ4/292-309'
B3QRJ4/315-334'
B3QRJ4/346-369'
B3QRJ4/389-412'
Q3AP28/34-57'
Q3AP28/69-90'
Q3AP28/125-147'
Q3AP28/154-176'
Q3AP28/196-214'
Q3AP28/226-246'
Q3AP28/258-278'
Q3AP28/290-307'
Q3AP28/313-332'
Q3AP28/344-367'
Q3AP28/387-411'
A9WHW6/45-64'
A9WHW6/85-109'
A9WHW6/129-148'
A9WHW6/155-178'
A9WHW6/200-221'
A9WHW6/242-259'
A9WHW6/275-299'
A9WHW6/311-328'
A9WHW6/334-351'
A9WHW6/363-381'
A9WHW6/401-426'
B3QVV5/39-61'
B3QVV5/73-96'
B3QVV5/128-148'
B3QVV5/160-179'
B3QVV5/199-217'
B3QVV5/229-250'
B3QVV5/262-283'
B3QVV5/290-307'
B3QVV5/313-336'
B3QVV5/348-368'
B3QVV5/380-402'
A0A017SYR8/12-30'
A0A017SYR8/42-64'
A0A017SYR8/94-117'
A0A017SYR8/124-145'
A0A017SYR8/157-181'
A0A017SYR8/193-213'
A0A017SYR8/225-246'
A0A017SYR8/255-274'
A0A017SYR8/280-299'
A0A017SYR8/311-330'
A0A017SYR8/350-372'
A0A202B535/42-63'
A0A202B535/75-97'
A0A202B535/138-159'
A0A202B535/166-187'
A0A202B535/207-226'
A0A202B535/238-255'
A0A202B535/267-286'
A0A202B535/298-318'
A0A202B535/324-342'
A0A202B535/354-374'
A0A202B535/386-406'
A0A381KRM8/42-63'
A0A381KRM8/75-97'
A0A381KRM8/138-159'
A0A381KRM8/166-187'
A0A381KRM8/207-226'
A0A381KRM8/238-255'
A0A381KRM8/267-286'
A0A381KRM8/298-318'
A0A381KRM8/324-342'
A0A381KRM8/354-374'
A0A381KRM8/386-406'
Q7NQY2/42-63'
Q7NQY2/75-97'
Q7NQY2/138-159'
Q7NQY2/166-187'
Q7NQY2/207-226'
Q7NQY2/238-255'
Q7NQY2/267-286'
Q7NQY2/298-318'
Q7NQY2/324-342'
Q7NQY2/354-374'
Q7NQY2/386-406'
A0A7Y8VM35/15-39'
A0A7Y8VM35/51-70'
A0A7Y8VM35/110-128'
A0A7Y8VM35/135-155'
A0A7Y8VM35/175-192'
A0A7Y8VM35/204-229'
A0A7Y8VM35/249-268'
A0A7Y8VM35/275-293'
A0A7Y8VM35/299-321'
A0A7Y8VM35/333-350'
A0A7Y8VM35/356-381'
A0A317R456/15-39'
A0A317R456/51-70'
A0A317R456/110-128'
A0A317R456/135-155'
A0A317R456/175-192'
A0A317R456/204-229'
A0A317R456/249-268'
A0A317R456/275-293'
A0A317R456/299-321'
A0A317R456/333-354'
A0A317R456/360-381'
Q1QSQ2/15-39'
Q1QSQ2/51-70'
Q1QSQ2/110-128'
Q1QSQ2/135-155'
Q1QSQ2/175-192'
Q1QSQ2/204-229'
Q1QSQ2/249-268'
Q1QSQ2/275-293'
Q1QSQ2/299-321'
Q1QSQ2/333-354'
Q1QSQ2/360-381'
K9U8C7/91-108'
K9U8C7/129-148'
K9U8C7/193-213'
K9U8C7/220-241'
K9U8C7/253-274'
K9U8C7/294-311'
K9U8C7/323-349'
K9U8C7/356-376'
K9U8C7/382-398'
K9U8C7/410-428'
K9U8C7/457-482'
B4CV94/56-79'
B4CV94/86-107'
B4CV94/148-170'
B4CV94/177-200'
B4CV94/220-247'
B4CV94/259-280'
B4CV94/292-316'
B4CV94/323-345'
B4CV94/351-373'
B4CV94/380-401'
B4CV94/437-460'
B4D7W2/43-67'
B4D7W2/79-100'
B4D7W2/135-155'
B4D7W2/162-182'
B4D7W2/202-223'
B4D7W2/235-256'
B4D7W2/262-286'
B4D7W2/298-319'
B4D7W2/325-343'
B4D7W2/355-376'
B4D7W2/402-424'
S0ET45/48-68'
S0ET45/80-100'
S0ET45/139-159'
S0ET45/166-187'
S0ET45/199-221'
S0ET45/241-258'
S0ET45/264-289'
S0ET45/301-319'
S0ET45/325-342'
S0ET45/354-379'
S0ET45/399-418'
S0EUS1/118-136'
S0EUS1/148-172'
S0EUS1/211-232'
S0EUS1/239-265'
S0EUS1/285-306'
S0EUS1/327-344'
S0EUS1/356-381'
S0EUS1/388-408'
S0EUS1/414-431'
S0EUS1/443-463'
S0EUS1/498-520'
A0A482PLH3/32-54'
A0A482PLH3/66-89'
A0A482PLH3/120-142'
A0A482PLH3/149-171'
A0A482PLH3/183-205'
A0A482PLH3/217-236'
A0A482PLH3/248-268'
A0A482PLH3/280-297'
A0A482PLH3/303-324'
A0A482PLH3/336-362'
A0A482PLH3/374-396'
D2TLS8/32-54'
D2TLS8/66-89'
D2TLS8/120-142'
D2TLS8/149-171'
D2TLS8/183-205'
D2TLS8/217-236'
D2TLS8/248-268'
D2TLS8/280-297'
D2TLS8/303-324'
D2TLS8/336-362'
D2TLS8/374-396'
A0A251Y3N4/6-27'
A0A251Y3N4/39-60'
A0A251Y3N4/110-132'
A0A251Y3N4/139-160'
A0A251Y3N4/180-205'
A0A251Y3N4/217-236'
A0A251Y3N4/248-270'
A0A251Y3N4/282-300'
A0A251Y3N4/306-324'
A0A251Y3N4/336-362'
A0A251Y3N4/374-394'
A0A251YU48/6-27'
A0A251YU48/39-60'
A0A251YU48/110-132'
A0A251YU48/139-160'
A0A251YU48/180-205'
A0A251YU48/217-236'
A0A251YU48/248-270'
A0A251YU48/282-300'
A0A251YU48/306-324'
A0A251YU48/336-353'
A0A251YU48/373-394'

A0A251Z278/6-27'
A0A251Z278/39-60'
A0A251Z278/110-132'
A0A251Z278/139-160'
A0A251Z278/180-205'
A0A251Z278/217-236'
A0A251Z278/248-270'
A0A251Z278/282-300'
A0A251Z278/306-324'
A0A251Z278/336-362'
A0A251Z278/374-394'
A0A251YFS0/6-27'
A0A251YFS0/39-60'
A0A251YFS0/110-132'
A0A251YFS0/139-160'
A0A251YFS0/180-205'
A0A251YFS0/217-236'
A0A251YFS0/248-270'
A0A251YFS0/282-300'
A0A251YFS0/306-324'
A0A251YFS0/336-362'
A0A251YFS0/374-394'
A0A251XJT0/6-27'
A0A251XJT0/39-60'
A0A251XJT0/110-132'
A0A251XJT0/139-160'
A0A251XJT0/180-205'
A0A251XJT0/217-236'
A0A251XJT0/248-270'
A0A251XJT0/282-300'
A0A251XJT0/306-324'
A0A251XJT0/336-362'
A0A251XJT0/374-394'
A0A399NT81/6-27'
A0A399NT81/39-60'
A0A399NT81/110-132'
A0A399NT81/139-160'
A0A399NT81/180-205'
A0A399NT81/217-236'
A0A399NT81/248-270'
A0A399NT81/282-300'
A0A399NT81/306-324'
A0A399NT81/336-362'
A0A399NT81/374-394'
A5CRL2/6-27'
A5CRL2/39-60'
A5CRL2/110-132'
A5CRL2/139-160'
A5CRL2/180-205'
A5CRL2/217-236'
A5CRL2/248-270'
A5CRL2/282-300'
A5CRL2/306-324'
A5CRL2/336-362'
A5CRL2/374-394'
A0A251XU71/6-27'
A0A251XU71/39-60'
A0A251XU71/110-132'
A0A251XU71/139-164'
A0A251XU71/184-205'
A0A251XU71/217-236'
A0A251XU71/248-270'
A0A251XU71/282-298'
A0A251XU71/304-322'
A0A251XU71/334-353'
A0A251XU71/373-394'
A0A399QCH4/6-27'
A0A399QCH4/39-60'
A0A399QCH4/110-132'
A0A399QCH4/139-160'
A0A399QCH4/180-205'
A0A399QCH4/217-236'
A0A399QCH4/248-270'
A0A399QCH4/282-300'
A0A399QCH4/306-324'
A0A399QCH4/336-362'
A0A399QCH4/374-394'
M5B925/6-27'
M5B925/39-60'
M5B925/110-132'
M5B925/139-160'
M5B925/180-205'
M5B925/217-236'
M5B925/248-270'
M5B925/282-300'
M5B925/306-324'
M5B925/336-362'
M5B925/374-394'
A0A0D5CI78/6-30'
A0A0D5CI78/42-62'
A0A0D5CI78/110-132'
A0A0D5CI78/139-160'
A0A0D5CI78/180-205'
A0A0D5CI78/217-236'
A0A0D5CI78/248-270'
A0A0D5CI78/282-300'
A0A0D5CI78/306-324'
A0A0D5CI78/336-362'
A0A0D5CI78/374-394'
A0A399NMH5/6-27'
A0A399NMH5/39-60'
A0A399NMH5/110-132'
A0A399NMH5/139-160'
A0A399NMH5/180-205'
A0A399NMH5/217-236'
A0A399NMH5/248-270'
A0A399NMH5/282-300'
A0A399NMH5/306-324'
A0A399NMH5/336-362'
A0A399NMH5/374-394'
A0A2S5VFE3/6-27'
A0A2S5VFE3/39-60'
A0A2S5VFE3/110-132'
A0A2S5VFE3/139-160'
A0A2S5VFE3/180-205'
A0A2S5VFE3/217-236'
A0A2S5VFE3/248-270'
A0A2S5VFE3/282-300'
A0A2S5VFE3/306-324'
A0A2S5VFE3/336-362'
A0A2S5VFE3/374-394'
A0A0M5JZH4/6-27'
A0A0M5JZH4/39-60'
A0A0M5JZH4/110-132'
A0A0M5JZH4/139-160'
A0A0M5JZH4/180-205'
A0A0M5JZH4/217-236'
A0A0M5JZH4/248-270'
A0A0M5JZH4/282-300'
A0A0M5JZH4/306-324'
A0A0M5JZH4/336-362'
A0A0M5JZH4/374-394'
A0A225CMT8/6-27'
A0A225CMT8/39-60'
A0A225CMT8/110-132'
A0A225CMT8/139-160'
A0A225CMT8/180-205'
A0A225CMT8/217-236'
A0A225CMT8/248-270'
A0A225CMT8/282-300'
A0A225CMT8/306-324'
A0A225CMT8/336-362'
A0A225CMT8/374-394'
A0A202G7R7/20-41'
A0A202G7R7/53-71'
A0A202G7R7/109-130'
A0A202G7R7/137-160'
A0A202G7R7/180-197'
A0A202G7R7/209-229'
A0A202G7R7/241-262'
A0A202G7R7/269-287'
A0A202G7R7/293-311'
A0A202G7R7/332-351'
A0A202G7R7/371-399'
A0A5Q0IBT9/14-37'
A0A5Q0IBT9/44-64'
A0A5Q0IBT9/104-128'
A0A5Q0IBT9/135-157'
A0A5Q0IBT9/177-196'
A0A5Q0IBT9/217-238'
A0A5Q0IBT9/244-263'
A0A5Q0IBT9/302-323'
A0A5Q0IBT9/329-347'
A0A5Q0IBT9/359-380'
A0A5Q0IBT9/400-423'
C4Y298/20-41'
C4Y298/53-71'
C4Y298/109-130'
C4Y298/137-160'
C4Y298/180-197'
C4Y298/209-229'
C4Y298/241-262'
C4Y298/269-287'
C4Y298/293-311'
C4Y298/332-351'
C4Y298/371-399'
C4YC30/14-37'
C4YC30/44-64'
C4YC30/104-128'
C4YC30/135-157'
C4YC30/177-196'
C4YC30/217-238'
C4YC30/244-263'
C4YC30/302-323'
C4YC30/329-347'
C4YC30/359-380'
C4YC30/400-423'
Q97L80/6-29'
Q97L80/41-62'
Q97L80/98-119'
Q97L80/126-147'
Q97L80/159-182'
Q97L80/194-212'
Q97L80/224-243'
Q97L80/255-272'
Q97L80/278-299'
Q97L80/311-330'
Q97L80/361-379'
A6LV49/6-29'
A6LV49/41-59'
A6LV49/99-120'
A6LV49/127-143'
A6LV49/163-184'
A6LV49/196-216'
A6LV49/228-249'
A6LV49/258-276'
A6LV49/282-300'
A6LV49/312-334'
A6LV49/354-377'
A6M3G0/6-30'
A6M3G0/42-64'
A6M3G0/99-120'
A6M3G0/127-147'
A6M3G0/167-184'
A6M3G0/196-216'
A6M3G0/228-249'
A6M3G0/258-277'
A6M3G0/283-303'
A6M3G0/315-334'
A6M3G0/354-377'
A6LRS5/12-32'
A6LRS5/44-65'
A6LRS5/102-122'
A6LRS5/129-150'
A6LRS5/170-186'
A6LRS5/198-215'
A6LRS5/227-247'
A6LRS5/259-276'
A6LRS5/282-302'
A6LRS5/314-333'
A6LRS5/353-375'
A0A4V5PX72/14-38'
A0A4V5PX72/50-69'
A0A4V5PX72/109-128'
A0A4V5PX72/133-150'
A0A4V5PX72/170-190'
A0A4V5PX72/211-228'
A0A4V5PX72/248-271'
A0A4V5PX72/278-296'
A0A4V5PX72/302-320'
A0A4V5PX72/332-349'
A0A4V5PX72/355-380'
A0A4U1M1R6/34-58'
A0A4U1M1R6/70-89'
A0A4U1M1R6/131-150'
A0A4U1M1R6/155-172'
A0A4U1M1R6/192-212'
A0A4U1M1R6/233-250'
A0A4U1M1R6/270-288'
A0A4U1M1R6/300-318'
A0A4U1M1R6/324-342'
A0A4U1M1R6/354-371'
A0A4U1M1R6/377-402'
A0A4U1LV47/20-41'
A0A4U1LV47/53-75'
A0A4U1LV47/107-129'
A0A4U1LV47/136-157'
A0A4U1LV47/177-195'
A0A4U1LV47/216-240'
A0A4U1LV47/255-274'
A0A4U1LV47/281-298'
A0A4U1LV47/304-324'
A0A4U1LV47/336-357'
A0A4U1LV47/369-394'
A0A3T0KAE2/14-38'
A0A3T0KAE2/50-69'
A0A3T0KAE2/109-128'
A0A3T0KAE2/133-150'
A0A3T0KAE2/170-190'
A0A3T0KAE2/211-228'
A0A3T0KAE2/248-271'
A0A3T0KAE2/278-296'
A0A3T0KAE2/302-320'
A0A3T0KAE2/332-349'
A0A3T0KAE2/355-380'
A0A3T0K738/34-58'
A0A3T0K738/70-89'
A0A3T0K738/131-150'
A0A3T0K738/155-172'
A0A3T0K738/192-212'
A0A3T0K738/233-250'
A0A3T0K738/270-288'
A0A3T0K738/300-318'
A0A3T0K738/324-342'
A0A3T0K738/354-371'
A0A3T0K738/377-402'
A0A3T0K667/20-41'
A0A3T0K667/53-75'
A0A3T0K667/107-129'
A0A3T0K667/136-157'
A0A3T0K667/177-195'
A0A3T0K667/216-240'
A0A3T0K667/255-274'
A0A3T0K667/281-298'
A0A3T0K667/304-324'
A0A3T0K667/336-357'
A0A3T0K667/369-394'
A0A2G5BGA9/20-41'
A0A2G5BGA9/53-71'
A0A2G5BGA9/112-131'
A0A2G5BGA9/138-161'
A0A2G5BGA9/181-199'
A0A2G5BGA9/211-229'
A0A2G5BGA9/241-261'
A0A2G5BGA9/273-291'
A0A2G5BGA9/297-316'
A0A2G5BGA9/328-351'
A0A2G5BGA9/371-396'
A0A2G5BI87/12-34'
A0A2G5BI87/46-66'
A0A2G5BI87/104-123'
A0A2G5BI87/135-154'
A0A2G5BI87/166-189'
A0A2G5BI87/205-222'
A0A2G5BI87/234-257'
A0A2G5BI87/264-283'
A0A2G5BI87/289-306'
A0A2G5BI87/318-339'
A0A2G5BI87/363-385'
A0A127PIQ9/87-108'
A0A127PIQ9/120-138'
A0A127PIQ9/180-202'
A0A127PIQ9/209-232'
A0A127PIQ9/262-284'
A0A127PIQ9/296-316'
A0A127PIQ9/328-348'
A0A127PIQ9/360-379'
A0A127PIQ9/385-403'
A0A127PIQ9/415-435'
A0A127PIQ9/461-483'
G0AFH4/67-88'
G0AFH4/100-118'
G0AFH4/160-182'
G0AFH4/189-212'
G0AFH4/242-264'
G0AFH4/276-296'
G0AFH4/308-328'
G0AFH4/340-359'
G0AFH4/365-383'
G0AFH4/395-415'
G0AFH4/441-463'
A0A1Y5E3E3/36-58'
A0A1Y5E3E3/70-93'
A0A1Y5E3E3/125-146'
A0A1Y5E3E3/153-175'
A0A1Y5E3E3/187-208'
A0A1Y5E3E3/220-241'
A0A1Y5E3E3/253-272'
A0A1Y5E3E3/284-304'
A0A1Y5E3E3/310-328'
A0A1Y5E3E3/349-372'
A0A1Y5E3E3/384-404'
A0A099KL22 has 13 helices, if 12, will use last 11, if other won't include
A0A099KL22/76-96'
A0A099KL22/108-131'
A0A099KL22/163-184'
A0A099KL22/191-213'
A0A099KL22/225-246'
A0A099KL22/258-279'
A0A099KL22/291-310'
A0A099KL22/322-342'
A0A099KL22/348-366'
A0A099KL22/378-400'
A0A099KL22/420-442'
Q47X17/44-66'
Q47X17/78-101'
Q47X17/133-154'
Q47X17/161-183'
Q47X17/195-216'
Q47X17/228-249'
Q47X17/261-280'
Q47X17/292-312'
Q47X17/318-336'
Q47X17/348-370'
Q47X17/390-412'
A0A1Y5E8I7/15-39'
A0A1Y5E8I7/51-70'
A0A1Y5E8I7/116-135'
A0A1Y5E8I7/140-157'
A0A1Y5E8I7/182-204'
A0A1Y5E8I7/216-238'
A0A1Y5E8I7/258-280'
A0A1Y5E8I7/287-305'
A0A1Y5E8I7/311-333'
A0A1Y5E8I7/345-366'
A0A1Y5E8I7/372-393'
A0A099KEY7/15-34'
A0A099KEY7/54-77'
A0A099KEY7/116-135'
A0A099KEY7/140-157'
A0A099KEY7/182-204'
A0A099KEY7/216-238'
A0A099KEY7/258-280'
A0A099KEY7/287-305'
A0A099KEY7/311-333'
A0A099KEY7/345-366'
A0A099KEY7/372-393'
A0A099KW74/15-39'
A0A099KW74/51-70'
A0A099KW74/116-134'
A0A099KW74/141-163'
A0A099KW74/183-204'
A0A099KW74/216-238'
A0A099KW74/258-280'
A0A099KW74/287-305'
A0A099KW74/311-333'
A0A099KW74/342-361'
A0A099KW74/373-393'
Q488X2/15-39'
Q488X2/51-70'
Q488X2/116-135'
Q488X2/140-157'
Q488X2/182-204'
Q488X2/216-238'
Q488X2/258-280'
Q488X2/287-305'
Q488X2/311-333'
Q488X2/342-361'
Q488X2/373-393'
A0A1Y1J9V1/52-74'
A0A1Y1J9V1/86-106'
A0A1Y1J9V1/143-161'
A0A1Y1J9V1/168-186'
A0A1Y1J9V1/206-228'
A0A1Y1J9V1/240-260'
A0A1Y1J9V1/272-292'
A0A1Y1J9V1/304-324'
A0A1Y1J9V1/330-347'
A0A1Y1J9V1/359-382'
A0A1Y1J9V1/402-421'
A0A373FQ71/54-74'
A0A373FQ71/86-106'
A0A373FQ71/143-161'
A0A373FQ71/168-186'
A0A373FQ71/206-228'
A0A373FQ71/240-260'
A0A373FQ71/272-292'
A0A373FQ71/304-324'
A0A373FQ71/330-347'
A0A373FQ71/359-383'
A0A373FQ71/403-427'

A0A076PL76/52-74'
A0A076PL76/86-106'
A0A076PL76/143-161'
A0A076PL76/168-186'
A0A076PL76/206-228'
A0A076PL76/240-259'
A0A076PL76/271-292'
A0A076PL76/304-324'
A0A076PL76/330-347'
A0A076PL76/359-377'
A0A076PL76/397-418'
A0A5A7MAJ9/52-74'
A0A5A7MAJ9/86-106'
A0A5A7MAJ9/143-161'
A0A5A7MAJ9/168-186'
A0A5A7MAJ9/206-228'
A0A5A7MAJ9/240-260'
A0A5A7MAJ9/272-292'
A0A5A7MAJ9/304-324'
A0A5A7MAJ9/330-347'
A0A5A7MAJ9/359-382'
A0A5A7MAJ9/402-421'
A0A096FEE6/52-74'
A0A096FEE6/86-106'
A0A096FEE6/143-161'
A0A096FEE6/168-186'
A0A096FEE6/206-228'
A0A096FEE6/240-259'
A0A096FEE6/271-292'
A0A096FEE6/304-324'
A0A096FEE6/330-347'
A0A096FEE6/359-377'
A0A096FEE6/397-418'
A0A8B4RWH8/52-74'
A0A8B4RWH8/86-106'
A0A8B4RWH8/143-161'
A0A8B4RWH8/168-186'
A0A8B4RWH8/206-228'
A0A8B4RWH8/240-259'
A0A8B4RWH8/271-292'
A0A8B4RWH8/304-324'
A0A8B4RWH8/330-347'
A0A8B4RWH8/359-377'
A0A8B4RWH8/397-418'
D0IWD0/52-74'
D0IWD0/86-106'
D0IWD0/143-161'
D0IWD0/168-186'
D0IWD0/206-228'
D0IWD0/240-260'
D0IWD0/272-292'
D0IWD0/304-324'
D0IWD0/330-347'
D0IWD0/359-377'
D0IWD0/397-418'
B7X047/52-74'
B7X047/86-106'
B7X047/143-161'
B7X047/168-186'
B7X047/206-228'
B7X047/240-259'
B7X047/271-292'
B7X047/304-324'
B7X047/330-347'
B7X047/359-377'
B7X047/397-418'
A0A096EEV9/51-73'
A0A096EEV9/85-105'
A0A096EEV9/142-160'
A0A096EEV9/167-185'
A0A096EEV9/205-227'
A0A096EEV9/239-259'
A0A096EEV9/271-291'
A0A096EEV9/303-323'
A0A096EEV9/329-346'
A0A096EEV9/358-376'
A0A096EEV9/396-417'
A0A0E3BR91/54-73'
A0A0E3BR91/85-105'
A0A0E3BR91/142-160'
A0A0E3BR91/167-185'
A0A0E3BR91/205-227'
A0A0E3BR91/239-259'
A0A0E3BR91/271-291'
A0A0E3BR91/303-323'
A0A0E3BR91/329-346'
A0A0E3BR91/358-376'
A0A0E3BR91/396-417'
A0A7U9A2V9/52-74'
A0A7U9A2V9/86-106'
A0A7U9A2V9/143-161'
A0A7U9A2V9/168-186'
A0A7U9A2V9/206-228'
A0A7U9A2V9/240-260'
A0A7U9A2V9/272-292'
A0A7U9A2V9/304-324'
A0A7U9A2V9/330-347'
A0A7U9A2V9/359-377'
A0A7U9A2V9/397-418'
A0A373FQ83/15-37'
A0A373FQ83/49-71'
A0A373FQ83/111-133'
A0A373FQ83/140-161'
A0A373FQ83/173-197'
A0A373FQ83/209-229'
A0A373FQ83/241-262'
A0A373FQ83/269-292'
A0A373FQ83/298-316'
A0A373FQ83/328-347'
A0A373FQ83/359-383'
A0A1Y1JBP5/12-32'
A0A1Y1JBP5/44-66'
A0A1Y1JBP5/86-105'
A0A1Y1JBP5/117-137'
A0A1Y1JBP5/157-178'
A0A1Y1JBP5/199-221'
A0A1Y1JBP5/227-249'
A0A1Y1JBP5/256-274'
A0A1Y1JBP5/280-298'
A0A1Y1JBP5/310-330'
A0A1Y1JBP5/342-366'
A0A5A7MBN6/15-37'
A0A5A7MBN6/49-71'
A0A5A7MBN6/111-133'
A0A5A7MBN6/140-161'
A0A5A7MBN6/173-197'
A0A5A7MBN6/209-229'
A0A5A7MBN6/241-265'
A0A5A7MBN6/272-292'
A0A5A7MBN6/298-316'
A0A5A7MBN6/328-347'
A0A5A7MBN6/359-383'
A0A3P2A7W8/37-59'
A0A3P2A7W8/71-93'
A0A3P2A7W8/134-155'
A0A3P2A7W8/162-184'
A0A3P2A7W8/196-218'
A0A3P2A7W8/230-250'
A0A3P2A7W8/256-281'
A0A3P2A7W8/293-313'
A0A3P2A7W8/319-337'
A0A3P2A7W8/349-371'
A0A3P2A7W8/391-408'
A0A7D7SF27/37-59'
A0A7D7SF27/71-93'
A0A7D7SF27/134-155'
A0A7D7SF27/162-184'
A0A7D7SF27/196-218'
A0A7D7SF27/230-250'
A0A7D7SF27/256-281'
A0A7D7SF27/293-313'
A0A7D7SF27/319-337'
A0A7D7SF27/349-371'
A0A7D7SF27/391-408'
D3F0Z1/52-71'
D3F0Z1/92-115'
D3F0Z1/135-158'
D3F0Z1/165-183'
D3F0Z1/203-224'
D3F0Z1/245-262'
D3F0Z1/278-299'
D3F0Z1/306-324'
D3F0Z1/330-350'
D3F0Z1/357-379'
D3F0Z1/403-428'
D3F545/21-46'
D3F545/58-85'
D3F545/115-133'
D3F545/140-158'
D3F545/178-199'
D3F545/220-241'
D3F545/253-274'
D3F545/281-299'
D3F545/305-325'
D3F545/337-359'
D3F545/379-401'
D3FBG3/17-38'
D3FBG3/50-72'
D3FBG3/104-126'
D3FBG3/133-155'
D3FBG3/167-188'
D3FBG3/200-221'
D3FBG3/233-254'
D3FBG3/261-282'
D3FBG3/288-307'
D3FBG3/319-338'
D3FBG3/358-379'
A4ABK3/15-39'
A4ABK3/51-70'
A4ABK3/102-121'
A4ABK3/126-143'
A4ABK3/163-190'
A4ABK3/202-224'
A4ABK3/244-266'
A4ABK3/273-291'
A4ABK3/297-316'
A4ABK3/328-346'
A4ABK3/358-379'
A8N2H6/20-41'
A8N2H6/53-71'
A8N2H6/111-131'
A8N2H6/143-163'
A8N2H6/175-197'
A8N2H6/209-229'
A8N2H6/241-262'
A8N2H6/269-287'
A8N2H6/293-312'
A8N2H6/324-345'
A8N2H6/376-397'
A8P923/30-51'
A8P923/63-91'
A8P923/139-160'
A8P923/172-193'
A8P923/199-223'
A8P923/244-262'
A8P923/274-294'
A8P923/306-326'
A8P923/332-354'
A8P923/366-386'
A8P923/406-428'
A8NAG3/29-50'
A8NAG3/62-87'
A8NAG3/117-140'
A8NAG3/149-169'
A8NAG3/175-199'
A8NAG3/220-238'
A8NAG3/250-271'
A8NAG3/278-295'
A8NAG3/301-321'
A8NAG3/333-355'
A8NAG3/380-404'
A0A316RGA5 has 12 helices, if 12, will use last 11, if other won't include
A0A316RGA5/42-63'
A0A316RGA5/75-98'
A0A316RGA5/132-150'
A0A316RGA5/162-183'
A0A316RGA5/195-218'
A0A316RGA5/230-247'
A0A316RGA5/259-280'
A0A316RGA5/292-311'
A0A316RGA5/317-334'
A0A316RGA5/346-366'
A0A316RGA5/378-402'
A0A495WJM6 has 12 helices, if 12, will use last 11, if other won't include
A0A495WJM6/42-63'
A0A495WJM6/75-98'
A0A495WJM6/132-150'
A0A495WJM6/162-183'
A0A495WJM6/195-218'
A0A495WJM6/230-247'
A0A495WJM6/259-280'
A0A495WJM6/292-311'
A0A495WJM6/317-334'
A0A495WJM6/346-366'
A0A495WJM6/378-402'
D5EP68/53-73'
D5EP68/94-112'
D5EP68/157-176'
D5EP68/183-205'
D5EP68/217-238'
D5EP68/258-275'
D5EP68/287-314'
D5EP68/321-337'
D5EP68/343-363'
D5EP68/375-392'
D5EP68/398-423'
D5ELM4/42-63'
D5ELM4/84-117'
D5ELM4/137-154'
D5ELM4/161-185'
D5ELM4/197-218'
D5ELM4/239-256'
D5ELM4/268-292'
D5ELM4/299-316'
D5ELM4/322-343'
D5ELM4/355-375'
D5ELM4/395-417'
D5EP71/49-71'
D5EP71/83-105'
D5EP71/138-159'
D5EP71/166-188'
D5EP71/200-221'
D5EP71/233-254'
D5EP71/266-285'
D5EP71/297-315'
D5EP71/321-341'
D5EP71/353-376'
D5EP71/388-413'
K9W6F3/54-75'
K9W6F3/87-111'
K9W6F3/163-182'
K9W6F3/189-211'
K9W6F3/223-244'
K9W6F3/256-277'
K9W6F3/283-308'
K9W6F3/320-338'
K9W6F3/344-363'
K9W6F3/375-394'
K9W6F3/414-436'
K9W4V5 has 12 helices, if 12, will use last 11, if other won't include
K9W4V5/105-122'
K9W4V5/143-162'
K9W4V5/207-227'
K9W4V5/234-255'
K9W4V5/267-288'
K9W4V5/300-325'
K9W4V5/337-364'
K9W4V5/371-391'
K9W4V5/397-413'
K9W4V5/425-445'
K9W4V5/474-499'
A3U857 has 12 helices, if 12, will use last 11, if other won't include
A3U857/39-64'
A3U857/76-96'
A3U857/128-148'
A3U857/160-181'
A3U857/193-216'
A3U857/228-246'
A3U857/258-279'
A3U857/291-310'
A3U857/316-332'
A3U857/344-363'
A3U857/375-398'
T2J0N1 has 12 helices, if 12, will use last 11, if other won't include
T2J0N1/55-79'
T2J0N1/91-110'
T2J0N1/141-160'
T2J0N1/167-188'
T2J0N1/200-221'
T2J0N1/274-291'
T2J0N1/303-328'
T2J0N1/335-353'
T2J0N1/359-377'
T2J0N1/389-411'
T2J0N1/451-483'
T2IEJ2 has 12 helices, if 12, will use last 11, if other won't include
T2IEJ2/67-88'
T2IEJ2/109-128'
T2IEJ2/159-182'
T2IEJ2/189-206'
T2IEJ2/226-247'
T2IEJ2/267-284'
T2IEJ2/296-320'
T2IEJ2/327-344'
T2IEJ2/350-369'
T2IEJ2/381-400'
T2IEJ2/420-441'
G5IYK4 has 12 helices, if 12, will use last 11, if other won't include
G5IYK4/67-88'
G5IYK4/109-128'
G5IYK4/159-182'
G5IYK4/189-206'
G5IYK4/226-247'
G5IYK4/267-284'
G5IYK4/296-320'
G5IYK4/327-344'
G5IYK4/350-369'
G5IYK4/381-400'
G5IYK4/420-441'
Q4CA23 has 12 helices, if 12, will use last 11, if other won't include
Q4CA23/67-88'
Q4CA23/109-128'
Q4CA23/159-182'
Q4CA23/189-206'
Q4CA23/226-247'
Q4CA23/267-284'
Q4CA23/296-320'
Q4CA23/327-344'
Q4CA23/350-369'
Q4CA23/381-400'
Q4CA23/420-441'
T2IKW0 has 12 helices, if 12, will use last 11, if other won't include
T2IKW0/67-88'
T2IKW0/109-128'
T2IKW0/159-182'
T2IKW0/189-206'
T2IKW0/226-247'
T2IKW0/267-284'
T2IKW0/296-320'
T2IKW0/327-344'
T2IKW0/350-369'
T2IKW0/381-400'
T2IKW0/420-441'
T2JFS5 has 12 helices, if 12, will use last 11, if other won't include
T2JFS5/67-88'
T2JFS5/109-128'
T2JFS5/159-182'
T2JFS5/189-206'
T2JFS5/226-247'
T2JFS5/267-284'
T2JFS5/296-320'
T2JFS5/327-344'
T2JFS5/350-369'
T2JFS5/381-400'
T2JFS5/420-441'
T2JZP8 has 12 helices, if 12, will use last 11, if other won't include
T2JZP8/67-88'
T2JZP8/109-128'
T2JZP8/159-182'
T2JZP8/189-206'
T2JZP8/226-247'
T2JZP8/267-284'
T2JZP8/296-320'
T2JZP8/327-344'
T2JZP8/350-369'
T2JZP8/381-400'
T2JZP8/420-441'
A0A7V7RI44/32-58'
A0A7V7RI44/70-97'
A0A7V7RI44/117-142'
A0A7V7RI44/149-171'
A0A7V7RI44/183-205'
A0A7V7RI44/217-236'
A0A7V7RI44/248-268'
A0A7V7RI44/280-302'
A0A7V7RI44/308-324'
A0A7V7RI44/336-355'
A0A7V7RI44/375-396'
A7MFK3/35-61'
A7MFK3/73-100'
A7MFK3/120-145'
A7MFK3/152-174'
A7MFK3/186-208'
A7MFK3/220-239'
A7MFK3/251-271'
A7MFK3/283-305'
A7MFK3/311-327'
A7MFK3/339-358'
A7MFK3/378-399'
V5U2Z4/35-61'
V5U2Z4/73-100'
V5U2Z4/120-145'
V5U2Z4/152-174'
V5U2Z4/186-208'
V5U2Z4/220-239'
V5U2Z4/251-271'
V5U2Z4/283-305'
V5U2Z4/311-327'
V5U2Z4/339-358'
V5U2Z4/378-399'
A0A423Y4I6/32-58'
A0A423Y4I6/70-97'
A0A423Y4I6/117-142'
A0A423Y4I6/149-171'
A0A423Y4I6/183-205'
A0A423Y4I6/217-236'
A0A423Y4I6/248-268'
A0A423Y4I6/280-302'
A0A423Y4I6/308-324'
A0A423Y4I6/336-355'
A0A423Y4I6/375-396'

K8CKZ7/32-58'
K8CKZ7/70-97'
K8CKZ7/117-142'
K8CKZ7/149-171'
K8CKZ7/183-205'
K8CKZ7/217-236'
K8CKZ7/248-268'
K8CKZ7/280-302'
K8CKZ7/308-324'
K8CKZ7/336-355'
K8CKZ7/375-396'
K8C851/32-58'
K8C851/70-97'
K8C851/117-142'
K8C851/149-171'
K8C851/183-205'
K8C851/217-236'
K8C851/248-268'
K8C851/280-302'
K8C851/308-324'
K8C851/336-355'
K8C851/375-396'
A0A3Q9CHX8/32-58'
A0A3Q9CHX8/70-97'
A0A3Q9CHX8/117-142'
A0A3Q9CHX8/149-171'
A0A3Q9CHX8/183-205'
A0A3Q9CHX8/217-236'
A0A3Q9CHX8/248-268'
A0A3Q9CHX8/280-302'
A0A3Q9CHX8/308-324'
A0A3Q9CHX8/336-355'
A0A3Q9CHX8/375-396'
Q560M9/42-63'
Q560M9/75-98'
Q560M9/133-153'
Q560M9/160-183'
Q560M9/195-217'
Q560M9/229-253'
Q560M9/265-285'
Q560M9/297-315'
Q560M9/321-339'
Q560M9/351-370'
Q560M9/399-420'
F5HBK8/30-51'
F5HBK8/63-81'
F5HBK8/117-138'
F5HBK8/150-171'
F5HBK8/177-203'
F5HBK8/223-240'
F5HBK8/252-273'
F5HBK8/280-297'
F5HBK8/303-324'
F5HBK8/336-357'
F5HBK8/392-410'
Q5KPM5/42-63'
Q5KPM5/75-98'
Q5KPM5/133-153'
Q5KPM5/160-183'
Q5KPM5/195-217'
Q5KPM5/229-253'
Q5KPM5/265-285'
Q5KPM5/297-315'
Q5KPM5/321-339'
Q5KPM5/351-370'
Q5KPM5/399-420'
Q5KAF6/30-51'
Q5KAF6/63-81'
Q5KAF6/117-138'
Q5KAF6/150-171'
Q5KAF6/177-203'
Q5KAF6/223-240'
Q5KAF6/252-273'
Q5KAF6/280-297'
Q5KAF6/303-324'
Q5KAF6/336-357'
Q5KAF6/392-410'
A0A225XW14/50-69'
A0A225XW14/81-99'
A0A225XW14/135-156'
A0A225XW14/168-189'
A0A225XW14/195-221'
A0A225XW14/241-258'
A0A225XW14/270-291'
A0A225XW14/298-315'
A0A225XW14/321-342'
A0A225XW14/354-375'
A0A225XW14/410-428'
A0A226A1N0/41-62'
A0A226A1N0/74-97'
A0A226A1N0/132-152'
A0A226A1N0/159-182'
A0A226A1N0/194-216'
A0A226A1N0/228-252'
A0A226A1N0/264-284'
A0A226A1N0/296-314'
A0A226A1N0/320-338'
A0A226A1N0/350-369'
A0A226A1N0/398-419'
A0A854Q6X9/50-69'
A0A854Q6X9/81-99'
A0A854Q6X9/135-156'
A0A854Q6X9/168-189'
A0A854Q6X9/195-221'
A0A854Q6X9/241-258'
A0A854Q6X9/270-291'
A0A854Q6X9/298-315'
A0A854Q6X9/321-342'
A0A854Q6X9/354-375'
A0A854Q6X9/410-428'
A0A854QN45/41-62'
A0A854QN45/74-97'
A0A854QN45/132-152'
A0A854QN45/159-182'
A0A854QN45/194-216'
A0A854QN45/228-252'
A0A854QN45/264-284'
A0A854QN45/296-314'
A0A854QN45/320-338'
A0A854QN45/350-369'
A0A854QN45/398-419'
J9VID9/41-62'
J9VID9/74-97'
J9VID9/132-152'
J9VID9/159-182'
J9VID9/194-216'
J9VID9/228-252'
J9VID9/264-284'
J9VID9/296-314'
J9VID9/320-338'
J9VID9/350-369'
J9VID9/398-419'
J9VXX9/30-51'
J9VXX9/63-81'
J9VXX9/117-138'
J9VXX9/150-171'
J9VXX9/177-203'
J9VXX9/223-240'
J9VXX9/252-271'
J9VXX9/283-302'
J9VXX9/308-324'
J9VXX9/336-357'
J9VXX9/392-410'
Q55T67 has 14 helices, if 12, will use last 11, if other won't include
Q55T67/281-301'
Q55T67/313-338'
Q55T67/344-364'
Q55T67/376-397'
Q55T67/409-427'
Q55T67/447-472'
Q55T67/484-505'
Q55T67/512-533'
Q55T67/545-566'
Q55T67/578-600'
Q55T67/620-640'
Q55T73 has 12 helices, if 12, will use last 11, if other won't include
Q55T73/172-189'
Q55T73/201-219'
Q55T73/231-248'
Q55T73/260-284'
Q55T73/290-309'
Q55T73/329-347'
Q55T73/353-372'
Q55T73/392-416'
Q55T73/428-450'
Q55T73/457-476'
Q55T73/559-583'
F5HID9 has 14 helices, if 12, will use last 11, if other won't include
F5HID9/198-215'
F5HID9/227-250'
F5HID9/256-279'
F5HID9/291-311'
F5HID9/323-341'
F5HID9/361-381'
F5HID9/401-419'
F5HID9/426-445'
F5HID9/451-476'
F5HID9/488-511'
F5HID9/531-551'
A0A225YUL7 has 14 helices, if 12, will use last 11, if other won't include
A0A225YUL7/281-301'
A0A225YUL7/313-338'
A0A225YUL7/344-366'
A0A225YUL7/378-397'
A0A225YUL7/409-427'
A0A225YUL7/447-472'
A0A225YUL7/484-505'
A0A225YUL7/512-531'
A0A225YUL7/574-593'
A0A225YUL7/605-624'
A0A225YUL7/640-660'
A0A225YUR6 has 12 helices, if 12, will use last 11, if other won't include
A0A225YUR6/187-204'
A0A225YUR6/216-234'
A0A225YUR6/275-300'
A0A225YUR6/306-327'
A0A225YUR6/339-357'
A0A225YUR6/369-389'
A0A225YUR6/409-429'
A0A225YUR6/449-467'
A0A225YUR6/474-493'
A0A225YUR6/499-524'
A0A225YUR6/576-600'
Q5KJ68 has 12 helices, if 12, will use last 11, if other won't include
Q5KJ68/208-225'
Q5KJ68/237-255'
Q5KJ68/267-284'
Q5KJ68/296-321'
Q5KJ68/327-347'
Q5KJ68/367-385'
Q5KJ68/391-410'
Q5KJ68/430-454'
Q5KJ68/466-488'
Q5KJ68/495-514'
Q5KJ68/597-621'
Q5KJ74 has 14 helices, if 12, will use last 11, if other won't include
Q5KJ74/280-300'
Q5KJ74/312-337'
Q5KJ74/343-363'
Q5KJ74/375-396'
Q5KJ74/408-426'
Q5KJ74/446-471'
Q5KJ74/483-504'
Q5KJ74/511-532'
Q5KJ74/544-565'
Q5KJ74/577-599'
Q5KJ74/619-639'
Q5KA34 has 14 helices, if 12, will use last 11, if other won't include
Q5KA34/198-215'
Q5KA34/227-250'
Q5KA34/256-279'
Q5KA34/291-311'
Q5KA34/323-341'
Q5KA34/361-381'
Q5KA34/401-419'
Q5KA34/426-445'
Q5KA34/451-476'
Q5KA34/488-511'
Q5KA34/531-551'
A0A854QKG0 has 13 helices, if 12, will use last 11, if other won't include
A0A854QKG0/268-285'
A0A854QKG0/297-322'
A0A854QKG0/328-349'
A0A854QKG0/361-379'
A0A854QKG0/391-411'
A0A854QKG0/431-451'
A0A854QKG0/471-489'
A0A854QKG0/496-515'
A0A854QKG0/521-546'
A0A854QKG0/558-578'
A0A854QKG0/618-638'
A0A854QBS6 has 13 helices, if 12, will use last 11, if other won't include
A0A854QBS6/254-275'
A0A854QBS6/281-301'
A0A854QBS6/313-338'
A0A854QBS6/344-364'
A0A854QBS6/376-397'
A0A854QBS6/409-427'
A0A854QBS6/447-472'
A0A854QBS6/484-505'
A0A854QBS6/512-533'
A0A854QBS6/578-600'
A0A854QBS6/620-640'
J9VL73 has 13 helices, if 12, will use last 11, if other won't include
J9VL73/254-275'
J9VL73/281-301'
J9VL73/313-338'
J9VL73/344-364'
J9VL73/376-397'
J9VL73/409-427'
J9VL73/447-472'
J9VL73/484-505'
J9VL73/512-533'
J9VL73/578-600'
J9VL73/620-640'
J9VU12 has 13 helices, if 12, will use last 11, if other won't include
J9VU12/268-285'
J9VU12/297-322'
J9VU12/328-349'
J9VU12/361-379'
J9VU12/391-411'
J9VU12/431-451'
J9VU12/471-489'
J9VU12/496-515'
J9VU12/521-546'
J9VU12/558-578'
J9VU12/598-622'
A0A8D8DV88/24-44'
A0A8D8DV88/65-82'
A0A8D8DV88/113-135'
A0A8D8DV88/142-162'
A0A8D8DV88/182-201'
A0A8D8DV88/213-230'
A0A8D8DV88/250-272'
A0A8D8DV88/284-302'
A0A8D8DV88/308-325'
A0A8D8DV88/337-359'
A0A8D8DV88/379-404'
A0A8D8GPY1/24-44'
A0A8D8GPY1/65-82'
A0A8D8GPY1/113-135'
A0A8D8GPY1/142-162'
A0A8D8GPY1/182-201'
A0A8D8GPY1/213-230'
A0A8D8GPY1/250-272'
A0A8D8GPY1/284-302'
A0A8D8GPY1/308-325'
A0A8D8GPY1/337-359'
A0A8D8GPY1/379-404'
A0A8D8B493/24-44'
A0A8D8B493/65-82'
A0A8D8B493/113-135'
A0A8D8B493/142-162'
A0A8D8B493/182-201'
A0A8D8B493/213-230'
A0A8D8B493/250-272'
A0A8D8B493/284-302'
A0A8D8B493/308-325'
A0A8D8B493/337-359'
A0A8D8B493/379-404'
A0A8D8FDY2/24-44'
A0A8D8FDY2/65-82'
A0A8D8FDY2/113-135'
A0A8D8FDY2/142-162'
A0A8D8FDY2/182-201'
A0A8D8FDY2/213-230'
A0A8D8FDY2/250-272'
A0A8D8FDY2/284-302'
A0A8D8FDY2/308-325'
A0A8D8FDY2/337-359'
A0A8D8FDY2/379-404'
A0A8D8GTE1/24-44'
A0A8D8GTE1/65-82'
A0A8D8GTE1/113-135'
A0A8D8GTE1/142-162'
A0A8D8GTE1/182-201'
A0A8D8GTE1/213-230'
A0A8D8GTE1/250-272'
A0A8D8GTE1/284-302'
A0A8D8GTE1/308-325'
A0A8D8GTE1/337-359'
A0A8D8GTE1/379-404'
A0A8D8ET63/7-28'
A0A8D8ET63/63-81'
A0A8D8ET63/88-105'
A0A8D8ET63/125-143'
A0A8D8ET63/150-169'
A0A8D8ET63/181-198'
A0A8D8ET63/219-236'
A0A8D8ET63/248-270'
A0A8D8ET63/303-323'
A0A8D8ET63/343-361'
A0A8D8ET63/411-429'
A0A502C8T9/6-28'
A0A502C8T9/40-61'
A0A502C8T9/108-130'
A0A502C8T9/137-158'
A0A502C8T9/178-200'
A0A502C8T9/212-235'
A0A502C8T9/241-259'
A0A502C8T9/271-289'
A0A502C8T9/295-313'
A0A502C8T9/325-344'
A0A502C8T9/364-383'
A0A6N1D0L9/6-28'
A0A6N1D0L9/40-61'
A0A6N1D0L9/108-130'
A0A6N1D0L9/137-158'
A0A6N1D0L9/178-200'
A0A6N1D0L9/212-235'
A0A6N1D0L9/241-259'
A0A6N1D0L9/271-289'
A0A6N1D0L9/295-313'
A0A6N1D0L9/325-344'
A0A6N1D0L9/364-383'
A0A4R6DFU8/6-28'
A0A4R6DFU8/40-61'
A0A4R6DFU8/103-125'
A0A4R6DFU8/137-158'
A0A4R6DFU8/178-200'
A0A4R6DFU8/212-231'
A0A4R6DFU8/237-259'
A0A4R6DFU8/271-289'
A0A4R6DFU8/295-313'
A0A4R6DFU8/325-342'
A0A4R6DFU8/362-383'
M1V7W3/38-59'
M1V7W3/71-95'
M1V7W3/163-183'
M1V7W3/190-212'
M1V7W3/248-269'
M1V7W3/290-307'
M1V7W3/344-364'
M1V7W3/371-393'
M1V7W3/399-418'
M1V7W3/430-451'
M1V7W3/486-506'
K9YJQ3 has 12 helices, if 12, will use last 11, if other won't include
K9YJQ3/64-81'
K9YJQ3/102-121'
K9YJQ3/159-178'
K9YJQ3/185-207'
K9YJQ3/219-240'
K9YJQ3/261-278'
K9YJQ3/290-314'
K9YJQ3/321-338'
K9YJQ3/344-365'
K9YJQ3/377-396'
K9YJQ3/402-427'
K9YN27 has 12 helices, if 12, will use last 11, if other won't include
K9YN27/64-81'
K9YN27/102-121'
K9YN27/166-186'
K9YN27/193-214'
K9YN27/226-247'
K9YN27/268-285'
K9YN27/297-323'
K9YN27/330-348'
K9YN27/354-372'
K9YN27/384-406'
K9YN27/426-449'
K9P5D1 has 12 helices, if 12, will use last 11, if other won't include
K9P5D1/76-99'
K9P5D1/111-131'
K9P5D1/165-187'
K9P5D1/199-216'
K9P5D1/236-259'
K9P5D1/271-290'
K9P5D1/302-320'
K9P5D1/332-353'
K9P5D1/359-377'
K9P5D1/389-411'
K9P5D1/431-457'

K9P718 has 12 helices, if 12, will use last 11, if other won't include
K9P718/78-98'
K9P718/110-128'
K9P718/171-190'
K9P718/195-213'
K9P718/233-254'
K9P718/274-291'
K9P718/303-324'
K9P718/336-352'
K9P718/358-375'
K9P718/387-407'
K9P718/427-447'
G0J614/12-32'
G0J614/44-67'
G0J614/105-124'
G0J614/129-147'
G0J614/167-188'
G0J614/208-225'
G0J614/237-259'
G0J614/271-289'
G0J614/295-313'
G0J614/325-343'
G0J614/355-376'
G0IYI2/32-51'
G0IYI2/72-91'
G0IYI2/131-149'
G0IYI2/156-176'
G0IYI2/196-217'
G0IYI2/229-249'
G0IYI2/261-286'
G0IYI2/293-311'
G0IYI2/317-338'
G0IYI2/345-366'
G0IYI2/378-399'
A0A1X4G8K1/40-60'
A0A1X4G8K1/72-91'
A0A1X4G8K1/141-161'
A0A1X4G8K1/168-190'
A0A1X4G8K1/210-229'
A0A1X4G8K1/241-260'
A0A1X4G8K1/266-291'
A0A1X4G8K1/303-321'
A0A1X4G8K1/327-346'
A0A1X4G8K1/358-377'
A0A1X4G8K1/397-419'
A0A8T9DUD0 has 12 helices, if 12, will use last 11, if other won't include
A0A8T9DUD0/71-92'
A0A8T9DUD0/113-132'
A0A8T9DUD0/177-195'
A0A8T9DUD0/202-225'
A0A8T9DUD0/237-258'
A0A8T9DUD0/279-296'
A0A8T9DUD0/308-336'
A0A8T9DUD0/343-363'
A0A8T9DUD0/369-385'
A0A8T9DUD0/397-421'
A0A8T9DUD0/441-462'
A0A1X4GBG2/79-102'
A0A1X4GBG2/114-134'
A0A1X4GBG2/179-197'
A0A1X4GBG2/204-226'
A0A1X4GBG2/238-260'
A0A1X4GBG2/281-298'
A0A1X4GBG2/310-338'
A0A1X4GBG2/345-365'
A0A1X4GBG2/371-387'
A0A1X4GBG2/399-419'
A0A1X4GBG2/439-464'
A0A853MG28 has 12 helices, if 12, will use last 11, if other won't include
A0A853MG28/68-89'
A0A853MG28/110-129'
A0A853MG28/174-192'
A0A853MG28/199-222'
A0A853MG28/234-255'
A0A853MG28/276-293'
A0A853MG28/305-333'
A0A853MG28/340-360'
A0A853MG28/366-382'
A0A853MG28/394-418'
A0A853MG28/438-459'
A0A7W1WEA6/79-102'
A0A7W1WEA6/114-134'
A0A7W1WEA6/179-197'
A0A7W1WEA6/204-227'
A0A7W1WEA6/239-260'
A0A7W1WEA6/281-298'
A0A7W1WEA6/310-338'
A0A7W1WEA6/345-365'
A0A7W1WEA6/371-387'
A0A7W1WEA6/399-423'
A0A7W1WEA6/443-464'
A0A838WPM9/79-102'
A0A838WPM9/114-134'
A0A838WPM9/179-197'
A0A838WPM9/204-227'
A0A838WPM9/239-260'
A0A838WPM9/281-298'
A0A838WPM9/310-338'
A0A838WPM9/345-365'
A0A838WPM9/371-387'
A0A838WPM9/399-423'
A0A838WPM9/443-464'
K9WT03/42-62'
K9WT03/74-92'
K9WT03/154-174'
K9WT03/181-203'
K9WT03/223-242'
K9WT03/254-273'
K9WT03/279-304'
K9WT03/316-334'
K9WT03/340-359'
K9WT03/371-390'
K9WT03/410-432'
K9WSX4/55-73'
K9WSX4/94-118'
K9WSX4/146-168'
K9WSX4/180-199'
K9WSX4/219-236'
K9WSX4/248-269'
K9WSX4/281-304'
K9WSX4/316-336'
K9WSX4/342-358'
K9WSX4/370-388'
K9WSX4/408-431'
A0A6N4SWV7/20-40'
A0A6N4SWV7/61-85'
A0A6N4SWV7/105-124'
A0A6N4SWV7/131-148'
A0A6N4SWV7/168-189'
A0A6N4SWV7/210-227'
A0A6N4SWV7/247-266'
A0A6N4SWV7/273-290'
A0A6N4SWV7/296-317'
A0A6N4SWV7/329-348'
A0A6N4SWV7/360-386'
A0A6N4SPH9/53-73'
A0A6N4SPH9/85-105'
A0A6N4SPH9/150-169'
A0A6N4SPH9/176-198'
A0A6N4SPH9/210-231'
A0A6N4SPH9/251-268'
A0A6N4SPH9/280-307'
A0A6N4SPH9/314-332'
A0A6N4SPH9/338-356'
A0A6N4SPH9/368-386'
A0A6N4SPH9/406-427'
A0A6N4SWE0/48-65'
A0A6N4SWE0/86-104'
A0A6N4SWE0/144-162'
A0A6N4SWE0/169-189'
A0A6N4SWE0/209-230'
A0A6N4SWE0/242-262'
A0A6N4SWE0/274-299'
A0A6N4SWE0/306-323'
A0A6N4SWE0/329-350'
A0A6N4SWE0/362-381'
A0A6N4SWE0/393-413'
K9YR86 has 12 helices, if 12, will use last 11, if other won't include
K9YR86/68-89'
K9YR86/110-129'
K9YR86/161-182'
K9YR86/189-206'
K9YR86/226-246'
K9YR86/267-284'
K9YR86/296-320'
K9YR86/327-344'
K9YR86/350-371'
K9YR86/383-400'
K9YR86/406-431'
K9Z0D3/17-35'
K9Z0D3/56-77'
K9Z0D3/126-148'
K9Z0D3/155-174'
K9Z0D3/194-213'
K9Z0D3/234-260'
K9Z0D3/272-293'
K9Z0D3/300-317'
K9Z0D3/323-343'
K9Z0D3/355-378'
K9Z0D3/390-412'
A0A0G2KTI4 has 12 helices, if 12, will use last 11, if other won't include
A0A0G2KTI4/239-264'
A0A0G2KTI4/284-319'
A0A0G2KTI4/328-348'
A0A0G2KTI4/351-376'
A0A0G2KTI4/410-428'
A0A0G2KTI4/434-463'
A0A0G2KTI4/525-555'
A0A0G2KTI4/576-591'
A0A0G2KTI4/595-625'
A0A0G2KTI4/637-655'
A0A0G2KTI4/657-674'
Q8JI14 has 12 helices, if 12, will use last 11, if other won't include
Q8JI14/74-94'
Q8JI14/99-119'
Q8JI14/140-160'
Q8JI14/163-183'
Q8JI14/192-214'
Q8JI14/233-253'
Q8JI14/265-285'
Q8JI14/299-319'
Q8JI14/321-341'
Q8JI14/357-377'
Q8JI14/410-430'
Q7T070 has 12 helices, if 12, will use last 11, if other won't include
Q7T070/59-79'
Q7T070/88-108'
Q7T070/122-142'
Q7T070/150-170'
Q7T070/177-197'
Q7T070/217-237'
Q7T070/249-269'
Q7T070/275-295'
Q7T070/297-317'
Q7T070/341-361'
Q7T070/393-413'
A0A8M3AW33/12-33'
A0A8M3AW33/57-75'
A0A8M3AW33/82-102'
A0A8M3AW33/122-141'
A0A8M3AW33/148-167'
A0A8M3AW33/179-197'
A0A8M3AW33/209-229'
A0A8M3AW33/249-268'
A0A8M3AW33/301-321'
A0A8M3AW33/341-358'
A0A8M3AW33/370-391'
Q7T067/12-33'
Q7T067/57-75'
Q7T067/82-102'
Q7T067/122-141'
Q7T067/148-167'
Q7T067/179-197'
Q7T067/209-229'
Q7T067/249-268'
Q7T067/301-321'
Q7T067/341-358'
Q7T067/370-391'
A4QNU4 has 12 helices, if 12, will use last 11, if other won't include
A4QNU4/77-95'
A4QNU4/102-120'
A4QNU4/140-160'
A4QNU4/167-186'
A4QNU4/198-216'
A4QNU4/228-247'
A4QNU4/267-286'
A4QNU4/298-317'
A4QNU4/323-344'
A4QNU4/365-383'
A4QNU4/411-432'
Q4VV70/12-32'
Q4VV70/57-76'
Q4VV70/82-102'
Q4VV70/145-163'
Q4VV70/175-193'
Q4VV70/213-229'
Q4VV70/241-264'
Q4VV70/276-295'
Q4VV70/301-318'
Q4VV70/338-358'
Q4VV70/370-396'
E9FWC4/31-51'
E9FWC4/63-89'
E9FWC4/109-127'
E9FWC4/139-159'
E9FWC4/174-195'
E9FWC4/216-236'
E9FWC4/248-272'
E9FWC4/284-304'
E9FWC4/310-328'
E9FWC4/349-368'
E9FWC4/374-402'
E9H9L9/29-48'
E9H9L9/69-87'
E9H9L9/107-125'
E9H9L9/137-158'
E9H9L9/178-194'
E9H9L9/214-234'
E9H9L9/246-269'
E9H9L9/281-298'
E9H9L9/304-321'
E9H9L9/333-353'
E9H9L9/373-396'
E9HAT0/168-189'
E9HAT0/252-270'
E9HAT0/326-348'
E9HAT0/355-378'
E9HAT0/398-425'
E9HAT0/446-467'
E9HAT0/479-497'
E9HAT0/518-535'
E9HAT0/568-588'
E9HAT0/609-627'
E9HAT0/677-700'
Q6BJI7/28-49'
Q6BJI7/61-79'
Q6BJI7/118-138'
Q6BJI7/150-169'
Q6BJI7/189-206'
Q6BJI7/218-238'
Q6BJI7/250-271'
Q6BJI7/278-296'
Q6BJI7/302-320'
Q6BJI7/341-360'
Q6BJI7/380-405'
Q6BT62/29-50'
Q6BT62/62-80'
Q6BT62/117-138'
Q6BT62/150-168'
Q6BT62/180-202'
Q6BT62/223-240'
Q6BT62/252-273'
Q6BT62/285-302'
Q6BT62/308-327'
Q6BT62/339-359'
Q6BT62/389-413'
Q6BK68/23-45'
Q6BK68/52-72'
Q6BK68/118-137'
Q6BK68/144-166'
Q6BK68/178-201'
Q6BK68/222-240'
Q6BK68/252-271'
Q6BK68/334-357'
Q6BK68/363-381'
Q6BK68/393-414'
Q6BK68/434-457'
Q6BVC6 has 12 helices, if 12, will use last 11, if other won't include
Q6BVC6/154-175'
Q6BVC6/187-207'
Q6BVC6/219-240'
Q6BVC6/256-275'
Q6BVC6/287-305'
Q6BVC6/325-345'
Q6BVC6/357-381'
Q6BVC6/388-406'
Q6BVC6/418-439'
Q6BVC6/451-476'
Q6BVC6/496-515'
Q47K18/72-93'
Q47K18/105-125'
Q47K18/165-187'
Q47K18/194-218'
Q47K18/247-268'
Q47K18/280-301'
Q47K18/313-333'
Q47K18/345-365'
Q47K18/371-388'
Q47K18/400-419'
Q47K18/449-470'
D3PAH1/39-59'
D3PAH1/71-94'
D3PAH1/125-147'
D3PAH1/154-176'
D3PAH1/188-208'
D3PAH1/220-242'
D3PAH1/254-279'
D3PAH1/286-306'
D3PAH1/312-329'
D3PAH1/341-360'
D3PAH1/380-404'
D3PE53/28-52'
D3PE53/64-86'
D3PE53/117-138'
D3PE53/145-166'
D3PE53/178-201'
D3PE53/213-234'
D3PE53/246-267'
D3PE53/274-291'
D3PE53/297-317'
D3PE53/329-353'
D3PE53/365-387'
A0A857DDJ7/6-27'
A0A857DDJ7/39-62'
A0A857DDJ7/93-113'
A0A857DDJ7/125-147'
A0A857DDJ7/159-180'
A0A857DDJ7/192-212'
A0A857DDJ7/224-246'
A0A857DDJ7/255-273'
A0A857DDJ7/279-300'
A0A857DDJ7/312-335'
A0A857DDJ7/355-374'
A0A857DMN9/12-33'
A0A857DMN9/45-64'
A0A857DMN9/95-115'
A0A857DMN9/127-149'
A0A857DMN9/161-182'
A0A857DMN9/194-213'
A0A857DMN9/225-246'
A0A857DMN9/258-280'
A0A857DMN9/286-302'
A0A857DMN9/314-337'
A0A857DMN9/357-376'
A0A916NVE1/6-28'
A0A916NVE1/40-61'
A0A916NVE1/97-119'
A0A916NVE1/126-147'
A0A916NVE1/167-184'
A0A916NVE1/196-215'
A0A916NVE1/227-250'
A0A916NVE1/257-275'
A0A916NVE1/281-300'
A0A916NVE1/312-335'
A0A916NVE1/355-376'
D2BIB2/6-28'
D2BIB2/40-61'
D2BIB2/97-119'
D2BIB2/126-147'
D2BIB2/167-184'
D2BIB2/196-215'
D2BIB2/227-250'
D2BIB2/257-275'
D2BIB2/281-300'
D2BIB2/312-335'
D2BIB2/355-376'
Q3Z7F9/6-28'
Q3Z7F9/40-61'
Q3Z7F9/97-119'
Q3Z7F9/126-147'
Q3Z7F9/167-184'
Q3Z7F9/196-215'
Q3Z7F9/227-250'
Q3Z7F9/257-275'
Q3Z7F9/281-300'
Q3Z7F9/312-335'
Q3Z7F9/355-376'
A0A142VAD6/6-28'
A0A142VAD6/40-61'
A0A142VAD6/97-119'
A0A142VAD6/126-147'
A0A142VAD6/167-184'
A0A142VAD6/196-215'
A0A142VAD6/227-250'
A0A142VAD6/257-275'
A0A142VAD6/281-300'
A0A142VAD6/312-335'
A0A142VAD6/355-376'
A0A1S7AU71/6-28'
A0A1S7AU71/40-61'
A0A1S7AU71/97-119'
A0A1S7AU71/126-147'
A0A1S7AU71/167-184'
A0A1S7AU71/196-215'
A0A1S7AU71/227-250'
A0A1S7AU71/257-275'
A0A1S7AU71/281-300'
A0A1S7AU71/312-335'
A0A1S7AU71/355-376'

A0A328EMN2/6-28'
A0A328EMN2/40-61'
A0A328EMN2/97-119'
A0A328EMN2/126-147'
A0A328EMN2/167-184'
A0A328EMN2/196-215'
A0A328EMN2/227-250'
A0A328EMN2/257-275'
A0A328EMN2/281-300'
A0A328EMN2/312-335'
A0A328EMN2/355-376'
A0A2J1DY21/6-28'
A0A2J1DY21/40-61'
A0A2J1DY21/97-119'
A0A2J1DY21/126-147'
A0A2J1DY21/167-184'
A0A2J1DY21/196-215'
A0A2J1DY21/227-250'
A0A2J1DY21/257-275'
A0A2J1DY21/281-300'
A0A2J1DY21/312-335'
A0A2J1DY21/355-376'
A0A0V8M0W6/6-28'
A0A0V8M0W6/40-61'
A0A0V8M0W6/97-119'
A0A0V8M0W6/126-147'
A0A0V8M0W6/167-184'
A0A0V8M0W6/196-215'
A0A0V8M0W6/227-250'
A0A0V8M0W6/257-275'
A0A0V8M0W6/281-300'
A0A0V8M0W6/312-335'
A0A0V8M0W6/355-376'
A0A089ZBW5/12-33'
A0A089ZBW5/45-64'
A0A089ZBW5/104-125'
A0A089ZBW5/132-154'
A0A089ZBW5/166-188'
A0A089ZBW5/200-217'
A0A089ZBW5/229-253'
A0A089ZBW5/260-279'
A0A089ZBW5/285-304'
A0A089ZBW5/316-339'
A0A089ZBW5/354-376'
A0A843AKI5/12-32'
A0A843AKI5/44-62'
A0A843AKI5/103-125'
A0A843AKI5/132-154'
A0A843AKI5/166-188'
A0A843AKI5/200-217'
A0A843AKI5/229-248'
A0A843AKI5/260-278'
A0A843AKI5/284-301'
A0A843AKI5/313-335'
A0A843AKI5/355-377'
A0A843AH20/12-32'
A0A843AH20/44-64'
A0A843AH20/99-121'
A0A843AH20/128-150'
A0A843AH20/162-183'
A0A843AH20/195-213'
A0A843AH20/219-244'
A0A843AH20/256-276'
A0A843AH20/282-300'
A0A843AH20/312-337'
A0A843AH20/349-371'
A0A843AFK5/12-32'
A0A843AFK5/44-64'
A0A843AFK5/99-121'
A0A843AFK5/128-150'
A0A843AFK5/162-183'
A0A843AFK5/195-213'
A0A843AFK5/219-244'
A0A843AFK5/256-276'
A0A843AFK5/282-300'
A0A843AFK5/312-335'
A0A843AFK5/347-371'
Q1IWN6/28-52'
Q1IWN6/64-86'
Q1IWN6/106-132'
Q1IWN6/144-165'
Q1IWN6/185-206'
Q1IWN6/218-239'
Q1IWN6/245-264'
Q1IWN6/276-293'
Q1IWN6/299-317'
Q1IWN6/329-351'
Q1IWN6/363-385'
A0A2W5H7U7/56-77'
A0A2W5H7U7/84-104'
A0A2W5H7U7/143-165'
A0A2W5H7U7/172-194'
A0A2W5H7U7/206-228'
A0A2W5H7U7/240-260'
A0A2W5H7U7/266-291'
A0A2W5H7U7/303-321'
A0A2W5H7U7/327-347'
A0A2W5H7U7/359-382'
A0A2W5H7U7/402-421'
A0A7T2W1B3/49-70'
A0A7T2W1B3/77-98'
A0A7T2W1B3/143-165'
A0A7T2W1B3/172-193'
A0A7T2W1B3/205-229'
A0A7T2W1B3/241-261'
A0A7T2W1B3/273-291'
A0A7T2W1B3/303-322'
A0A7T2W1B3/328-348'
A0A7T2W1B3/360-379'
A0A7T2W1B3/391-415'
A0A2W5G0A5/76-97'
A0A2W5G0A5/109-132'
A0A2W5G0A5/167-189'
A0A2W5G0A5/196-218'
A0A2W5G0A5/230-252'
A0A2W5G0A5/264-284'
A0A2W5G0A5/296-316'
A0A2W5G0A5/328-349'
A0A2W5G0A5/355-371'
A0A2W5G0A5/383-404'
A0A2W5G0A5/424-443'
A0A286J4U5/52-73'
A0A286J4U5/80-101'
A0A286J4U5/146-168'
A0A286J4U5/175-196'
A0A286J4U5/208-232'
A0A286J4U5/244-264'
A0A286J4U5/276-294'
A0A286J4U5/306-325'
A0A286J4U5/331-351'
A0A286J4U5/363-382'
A0A286J4U5/394-418'
A0A2M9PTR1/52-73'
A0A2M9PTR1/80-101'
A0A2M9PTR1/146-168'
A0A2M9PTR1/175-196'
A0A2M9PTR1/208-232'
A0A2M9PTR1/244-264'
A0A2M9PTR1/276-294'
A0A2M9PTR1/306-325'
A0A2M9PTR1/331-351'
A0A2M9PTR1/363-382'
A0A2M9PTR1/394-418'
A0A2W5IG33/49-70'
A0A2W5IG33/77-98'
A0A2W5IG33/143-165'
A0A2W5IG33/172-193'
A0A2W5IG33/205-229'
A0A2W5IG33/241-261'
A0A2W5IG33/273-291'
A0A2W5IG33/303-322'
A0A2W5IG33/328-348'
A0A2W5IG33/360-379'
A0A2W5IG33/391-415'
A0A7T2S0Z6/59-81'
A0A7T2S0Z6/93-113'
A0A7T2S0Z6/150-172'
A0A7T2S0Z6/179-201'
A0A7T2S0Z6/213-235'
A0A7T2S0Z6/247-266'
A0A7T2S0Z6/278-299'
A0A7T2S0Z6/311-330'
A0A7T2S0Z6/336-354'
A0A7T2S0Z6/366-389'
A0A7T2S0Z6/409-428'
A0A7T4EM77/59-81'
A0A7T4EM77/93-113'
A0A7T4EM77/150-172'
A0A7T4EM77/179-201'
A0A7T4EM77/213-235'
A0A7T4EM77/247-267'
A0A7T4EM77/273-298'
A0A7T4EM77/310-328'
A0A7T4EM77/334-354'
A0A7T4EM77/366-389'
A0A7T4EM77/409-428'
A0A7U9HJZ8/56-77'
A0A7U9HJZ8/84-104'
A0A7U9HJZ8/143-165'
A0A7U9HJZ8/172-194'
A0A7U9HJZ8/206-228'
A0A7U9HJZ8/240-260'
A0A7U9HJZ8/266-291'
A0A7U9HJZ8/303-321'
A0A7U9HJZ8/327-347'
A0A7U9HJZ8/359-382'
A0A7U9HJZ8/402-421'
A0A7U9HH57/49-70'
A0A7U9HH57/77-98'
A0A7U9HH57/143-165'
A0A7U9HH57/172-193'
A0A7U9HH57/205-229'
A0A7U9HH57/241-261'
A0A7U9HH57/273-291'
A0A7U9HH57/303-322'
A0A7U9HH57/328-348'
A0A7U9HH57/360-379'
A0A7U9HH57/391-415'
A9BQZ4/59-81'
A9BQZ4/93-113'
A9BQZ4/150-172'
A9BQZ4/179-201'
A9BQZ4/213-235'
A9BQZ4/247-267'
A9BQZ4/273-298'
A9BQZ4/310-328'
A9BQZ4/334-354'
A9BQZ4/366-389'
A9BQZ4/409-428'
A9BTK1/52-73'
A9BTK1/80-101'
A9BTK1/146-168'
A9BTK1/175-196'
A9BTK1/208-232'
A9BTK1/244-264'
A9BTK1/276-294'
A9BTK1/306-325'
A9BTK1/331-351'
A9BTK1/363-382'
A9BTK1/394-418'
A0A1D8J0B0/52-73'
A0A1D8J0B0/80-101'
A0A1D8J0B0/146-168'
A0A1D8J0B0/175-196'
A0A1D8J0B0/208-232'
A0A1D8J0B0/244-264'
A0A1D8J0B0/276-294'
A0A1D8J0B0/306-325'
A0A1D8J0B0/331-351'
A0A1D8J0B0/363-382'
A0A1D8J0B0/394-418'
A0A1D8J5Y7/56-77'
A0A1D8J5Y7/84-104'
A0A1D8J5Y7/143-165'
A0A1D8J5Y7/172-194'
A0A1D8J5Y7/206-228'
A0A1D8J5Y7/240-260'
A0A1D8J5Y7/266-291'
A0A1D8J5Y7/303-321'
A0A1D8J5Y7/327-347'
A0A1D8J5Y7/359-382'
A0A1D8J5Y7/402-421'
A0A080NRN5/56-77'
A0A080NRN5/84-104'
A0A080NRN5/143-165'
A0A080NRN5/172-194'
A0A080NRN5/206-228'
A0A080NRN5/240-260'
A0A080NRN5/266-291'
A0A080NRN5/303-321'
A0A080NRN5/327-347'
A0A080NRN5/359-382'
A0A080NRN5/402-421'
A0A7T4EQX0/49-70'
A0A7T4EQX0/77-98'
A0A7T4EQX0/143-165'
A0A7T4EQX0/172-193'
A0A7T4EQX0/205-229'
A0A7T4EQX0/241-261'
A0A7T4EQX0/273-291'
A0A7T4EQX0/303-322'
A0A7T4EQX0/328-348'
A0A7T4EQX0/360-379'
A0A7T4EQX0/391-415'
A0A172RYW3/6-29'
A0A172RYW3/41-63'
A0A172RYW3/122-141'
A0A172RYW3/148-170'
A0A172RYW3/190-207'
A0A172RYW3/219-239'
A0A172RYW3/251-270'
A0A172RYW3/282-300'
A0A172RYW3/306-323'
A0A172RYW3/335-358'
A0A172RYW3/378-403'
D4H2Y7/44-63'
D4H2Y7/84-108'
D4H2Y7/128-148'
D4H2Y7/155-177'
D4H2Y7/189-215'
D4H2Y7/236-253'
D4H2Y7/265-291'
D4H2Y7/298-315'
D4H2Y7/321-340'
D4H2Y7/352-369'
D4H2Y7/381-404'
D4H0Y2 has 13 helices, if 12, will use last 11, if other won't include
D4H0Y2/59-80'
D4H0Y2/92-115'
D4H0Y2/135-163'
D4H0Y2/175-197'
D4H0Y2/209-230'
D4H0Y2/242-262'
D4H0Y2/274-296'
D4H0Y2/303-323'
D4H0Y2/329-348'
D4H0Y2/360-382'
D4H0Y2/394-419'
D4H5F9/6-28'
D4H5F9/49-72'
D4H5F9/92-111'
D4H5F9/118-139'
D4H5F9/159-180'
D4H5F9/201-224'
D4H5F9/230-250'
D4H5F9/262-280'
D4H5F9/286-303'
D4H5F9/315-336'
D4H5F9/348-370'
A0A075JIN0/20-40'
A0A075JIN0/52-70'
A0A075JIN0/115-137'
A0A075JIN0/144-165'
A0A075JIN0/196-218'
A0A075JIN0/230-250'
A0A075JIN0/262-283'
A0A075JIN0/290-307'
A0A075JIN0/313-334'
A0A075JIN0/346-365'
A0A075JIN0/385-406'
A0A4U0RRD7/20-40'
A0A4U0RRD7/52-70'
A0A4U0RRD7/115-137'
A0A4U0RRD7/144-165'
A0A4U0RRD7/196-218'
A0A4U0RRD7/230-250'
A0A4U0RRD7/262-283'
A0A4U0RRD7/290-307'
A0A4U0RRD7/313-334'
A0A4U0RRD7/346-365'
A0A4U0RRD7/385-406'
A0A8B6X901/56-76'
A0A8B6X901/83-104'
A0A8B6X901/151-172'
A0A8B6X901/179-200'
A0A8B6X901/212-235'
A0A8B6X901/247-268'
A0A8B6X901/280-301'
A0A8B6X901/308-325'
A0A8B6X901/331-352'
A0A8B6X901/364-385'
A0A8B6X901/397-419'
A0A8B6X9K6/79-99'
A0A8B6X9K6/111-131'
A0A8B6X9K6/171-193'
A0A8B6X9K6/200-223'
A0A8B6X9K6/253-274'
A0A8B6X9K6/286-307'
A0A8B6X9K6/319-339'
A0A8B6X9K6/351-372'
A0A8B6X9K6/378-394'
A0A8B6X9K6/406-426'
A0A8B6X9K6/459-481'
A0A8B6XC37/67-88'
A0A8B6XC37/100-123'
A0A8B6XC37/159-179'
A0A8B6XC37/186-209'
A0A8B6XC37/221-244'
A0A8B6XC37/256-277'
A0A8B6XC37/289-308'
A0A8B6XC37/320-337'
A0A8B6XC37/343-364'
A0A8B6XC37/376-400'
A0A8B6XC37/406-428'
E1QIU3/41-58'
E1QIU3/79-96'
E1QIU3/116-137'
E1QIU3/149-171'
E1QIU3/183-204'
E1QIU3/225-242'
E1QIU3/262-285'
E1QIU3/292-311'
E1QIU3/317-334'
E1QIU3/346-364'
E1QIU3/384-409'
E1QFA8/12-32'
E1QFA8/39-59'
E1QFA8/99-122'
E1QFA8/129-150'
E1QFA8/170-188'
E1QFA8/200-218'
E1QFA8/230-254'
E1QFA8/261-278'
E1QFA8/284-301'
E1QFA8/313-334'
E1QFA8/354-376'
A0A1M6ZMI3/43-62'
A0A1M6ZMI3/83-107'
A0A1M6ZMI3/127-147'
A0A1M6ZMI3/154-172'
A0A1M6ZMI3/192-216'
A0A1M6ZMI3/237-254'
A0A1M6ZMI3/266-292'
A0A1M6ZMI3/299-318'
A0A1M6ZMI3/324-341'
A0A1M6ZMI3/353-370'
A0A1M6ZMI3/382-402'
A0A1M6JKY3/32-58'
A0A1M6JKY3/70-89'
A0A1M6JKY3/122-144'
A0A1M6JKY3/151-173'
A0A1M6JKY3/193-211'
A0A1M6JKY3/223-243'
A0A1M6JKY3/255-275'
A0A1M6JKY3/287-304'
A0A1M6JKY3/310-329'
A0A1M6JKY3/341-361'
A0A1M6JKY3/381-406'
B8FL88/43-62'
B8FL88/83-107'
B8FL88/127-147'
B8FL88/154-172'
B8FL88/192-216'
B8FL88/237-254'
B8FL88/266-292'
B8FL88/299-319'
B8FL88/325-341'
B8FL88/353-370'
B8FL88/382-402'
B8FGW0/32-58'
B8FGW0/70-89'
B8FGW0/122-144'
B8FGW0/151-173'
B8FGW0/193-211'
B8FGW0/223-243'
B8FGW0/255-275'
B8FGW0/287-304'
B8FGW0/310-329'
B8FGW0/341-361'
B8FGW0/381-406'
A0A1M6BPM0/6-29'
A0A1M6BPM0/36-57'
A0A1M6BPM0/96-119'
A0A1M6BPM0/126-147'
A0A1M6BPM0/159-183'
A0A1M6BPM0/195-215'
A0A1M6BPM0/227-247'
A0A1M6BPM0/259-276'
A0A1M6BPM0/282-301'
A0A1M6BPM0/313-338'
A0A1M6BPM0/350-372'
B8FDY8/6-29'
B8FDY8/36-57'
B8FDY8/96-119'
B8FDY8/126-147'
B8FDY8/159-183'
B8FDY8/195-215'
B8FDY8/227-247'
B8FDY8/259-276'
B8FDY8/282-301'
B8FDY8/313-338'
B8FDY8/350-372'

A0A7C4RTW1/31-54'
A0A7C4RTW1/66-87'
A0A7C4RTW1/116-137'
A0A7C4RTW1/149-170'
A0A7C4RTW1/182-203'
A0A7C4RTW1/215-236'
A0A7C4RTW1/248-268'
A0A7C4RTW1/280-300'
A0A7C4RTW1/306-323'
A0A7C4RTW1/335-354'
A0A7C4RTW1/374-395'
A0A098B6P8/33-56'
A0A098B6P8/68-91'
A0A098B6P8/122-142'
A0A098B6P8/154-177'
A0A098B6P8/189-210'
A0A098B6P8/222-243'
A0A098B6P8/255-274'
A0A098B6P8/286-307'
A0A098B6P8/313-330'
A0A098B6P8/342-361'
A0A098B6P8/381-401'
A0A0W1JII4/33-56'
A0A0W1JII4/68-91'
A0A0W1JII4/122-142'
A0A0W1JII4/154-177'
A0A0W1JII4/189-210'
A0A0W1JII4/222-243'
A0A0W1JII4/255-274'
A0A0W1JII4/286-307'
A0A0W1JII4/313-330'
A0A0W1JII4/342-361'
A0A0W1JII4/381-401'
Q24PJ2/33-56'
Q24PJ2/68-91'
Q24PJ2/122-142'
Q24PJ2/154-177'
Q24PJ2/189-210'
Q24PJ2/222-243'
Q24PJ2/255-274'
Q24PJ2/286-307'
Q24PJ2/313-330'
Q24PJ2/342-361'
Q24PJ2/381-401'
B8FZP7/33-56'
B8FZP7/68-91'
B8FZP7/122-142'
B8FZP7/154-177'
B8FZP7/189-210'
B8FZP7/222-243'
B8FZP7/255-274'
B8FZP7/286-307'
B8FZP7/313-330'
B8FZP7/342-361'
B8FZP7/381-401'
G9XQB9 has 12 helices, if 12, will use last 11, if other won't include
G9XQB9/96-117'
G9XQB9/129-152'
G9XQB9/183-203'
G9XQB9/215-238'
G9XQB9/250-271'
G9XQB9/283-304'
G9XQB9/316-335'
G9XQB9/347-368'
G9XQB9/374-391'
G9XQB9/403-422'
G9XQB9/442-462'
A0A7C3Z0B6/12-31'
A0A7C3Z0B6/43-61'
A0A7C3Z0B6/102-123'
A0A7C3Z0B6/130-151'
A0A7C3Z0B6/163-187'
A0A7C3Z0B6/199-219'
A0A7C3Z0B6/231-255'
A0A7C3Z0B6/262-279'
A0A7C3Z0B6/285-302'
A0A7C3Z0B6/314-335'
A0A7C3Z0B6/355-377'
A0A7C3WRX0/6-31'
A0A7C3WRX0/43-62'
A0A7C3WRX0/97-119'
A0A7C3WRX0/126-147'
A0A7C3WRX0/159-182'
A0A7C3WRX0/194-215'
A0A7C3WRX0/227-246'
A0A7C3WRX0/258-276'
A0A7C3WRX0/282-301'
A0A7C3WRX0/313-332'
A0A7C3WRX0/352-374'
A0A7V6A2R5/12-32'
A0A7V6A2R5/44-66'
A0A7V6A2R5/102-123'
A0A7V6A2R5/130-150'
A0A7V6A2R5/170-188'
A0A7V6A2R5/200-219'
A0A7V6A2R5/231-255'
A0A7V6A2R5/262-279'
A0A7V6A2R5/285-302'
A0A7V6A2R5/314-335'
A0A7V6A2R5/355-377'
A0A7C3ZC37/40-62'
A0A7C3ZC37/74-91'
A0A7C3ZC37/97-119'
A0A7C3ZC37/126-147'
A0A7C3ZC37/159-182'
A0A7C3ZC37/194-215'
A0A7C3ZC37/221-246'
A0A7C3ZC37/258-276'
A0A7C3ZC37/282-301'
A0A7C3ZC37/313-332'
A0A7C3ZC37/352-374'
A0A7V6A1Z5/6-28'
A0A7V6A1Z5/40-62'
A0A7V6A1Z5/97-119'
A0A7V6A1Z5/126-147'
A0A7V6A1Z5/159-181'
A0A7V6A1Z5/193-215'
A0A7V6A1Z5/227-247'
A0A7V6A1Z5/259-278'
A0A7V6A1Z5/284-301'
A0A7V6A1Z5/313-332'
A0A7V6A1Z5/352-374'
F2NGJ8/6-28'
F2NGJ8/40-62'
F2NGJ8/99-120'
F2NGJ8/127-148'
F2NGJ8/160-183'
F2NGJ8/195-216'
F2NGJ8/222-246'
F2NGJ8/258-277'
F2NGJ8/283-302'
F2NGJ8/314-333'
F2NGJ8/353-375'
I5AZQ4/32-54'
I5AZQ4/66-86'
I5AZQ4/118-139'
I5AZQ4/151-172'
I5AZQ4/184-205'
I5AZQ4/217-238'
I5AZQ4/250-269'
I5AZQ4/281-301'
I5AZQ4/307-325'
I5AZQ4/337-356'
I5AZQ4/376-399'
I5B3H0/44-64'
I5B3H0/85-106'
I5B3H0/126-146'
I5B3H0/158-179'
I5B3H0/191-217'
I5B3H0/238-255'
I5B3H0/267-291'
I5B3H0/298-317'
I5B3H0/323-342'
I5B3H0/354-374'
I5B3H0/380-403'
K0NJH2/45-69'
K0NJH2/90-116'
K0NJH2/128-146'
K0NJH2/158-179'
K0NJH2/191-217'
K0NJH2/238-255'
K0NJH2/267-291'
K0NJH2/298-317'
K0NJH2/323-342'
K0NJH2/354-371'
K0NJH2/383-403'
K0N2R5/32-54'
K0N2R5/66-86'
K0N2R5/118-139'
K0N2R5/151-172'
K0N2R5/184-205'
K0N2R5/217-237'
K0N2R5/249-269'
K0N2R5/281-299'
K0N2R5/305-325'
K0N2R5/337-356'
K0N2R5/376-399'
A0A562RGZ4/43-65'
A0A562RGZ4/86-112'
A0A562RGZ4/124-144'
A0A562RGZ4/151-169'
A0A562RGZ4/189-213'
A0A562RGZ4/234-251'
A0A562RGZ4/263-287'
A0A562RGZ4/294-311'
A0A562RGZ4/317-338'
A0A562RGZ4/350-368'
A0A562RGZ4/374-399'
A0A562S8V2/6-27'
A0A562S8V2/39-57'
A0A562S8V2/96-118'
A0A562S8V2/125-147'
A0A562S8V2/159-181'
A0A562S8V2/193-212'
A0A562S8V2/224-244'
A0A562S8V2/256-274'
A0A562S8V2/280-299'
A0A562S8V2/311-334'
A0A562S8V2/354-375'
A0A7U3YMN6/38-60'
A0A7U3YMN6/72-90'
A0A7U3YMN6/132-154'
A0A7U3YMN6/161-185'
A0A7U3YMN6/214-235'
A0A7U3YMN6/247-267'
A0A7U3YMN6/279-298'
A0A7U3YMN6/310-328'
A0A7U3YMN6/334-352'
A0A7U3YMN6/364-386'
A0A7U3YMN6/416-437'
A0A7U4DN04/6-30'
A0A7U4DN04/37-58'
A0A7U4DN04/100-120'
A0A7U4DN04/127-148'
A0A7U4DN04/160-183'
A0A7U4DN04/195-216'
A0A7U4DN04/228-248'
A0A7U4DN04/260-278'
A0A7U4DN04/284-300'
A0A7U4DN04/312-333'
A0A7U4DN04/353-375'
M1P5F0/54-78'
M1P5F0/90-108'
M1P5F0/148-166'
M1P5F0/173-193'
M1P5F0/213-231'
M1P5F0/243-263'
M1P5F0/283-304'
M1P5F0/316-333'
M1P5F0/339-358'
M1P5F0/367-386'
M1P5F0/398-418'
M1NZT5/54-78'
M1NZT5/90-108'
M1NZT5/148-166'
M1NZT5/173-193'
M1NZT5/213-231'
M1NZT5/243-263'
M1NZT5/283-304'
M1NZT5/316-333'
M1NZT5/339-358'
M1NZT5/367-386'
M1NZT5/398-418'
M1WRK6 has 12 helices, if 12, will use last 11, if other won't include
M1WRK6/36-56'
M1WRK6/63-82'
M1WRK6/94-114'
M1WRK6/126-148'
M1WRK6/160-181'
M1WRK6/193-214'
M1WRK6/226-246'
M1WRK6/258-275'
M1WRK6/281-300'
M1WRK6/312-334'
M1WRK6/346-368'
C8WZE0/42-64'
C8WZE0/85-110'
C8WZE0/130-152'
C8WZE0/159-181'
C8WZE0/201-222'
C8WZE0/243-260'
C8WZE0/272-296'
C8WZE0/303-320'
C8WZE0/326-347'
C8WZE0/359-379'
C8WZE0/399-419'
C8X554/6-28'
C8X554/40-60'
C8X554/94-114'
C8X554/126-148'
C8X554/160-181'
C8X554/193-214'
C8X554/226-246'
C8X554/258-275'
C8X554/281-300'
C8X554/312-331'
C8X554/351-373'
C7LW88/45-65'
C7LW88/86-106'
C7LW88/126-148'
C7LW88/160-181'
C7LW88/201-224'
C7LW88/245-262'
C7LW88/274-297'
C7LW88/309-327'
C7LW88/333-349'
C7LW88/361-383'
C7LW88/403-424'
C7LW87/6-28'
C7LW87/40-59'
C7LW87/97-119'
C7LW87/126-148'
C7LW87/160-181'
C7LW87/193-214'
C7LW87/226-246'
C7LW87/258-274'
C7LW87/280-298'
C7LW87/310-331'
C7LW87/351-373'
C7LQR9/6-26'
C7LQR9/47-68'
C7LQR9/88-110'
C7LQR9/117-138'
C7LQR9/158-179'
C7LQR9/200-217'
C7LQR9/229-250'
C7LQR9/262-282'
C7LQR9/288-305'
C7LQR9/312-334'
C7LQR9/349-371'
A0A7C4EVF7/6-30'
A0A7C4EVF7/42-64'
A0A7C4EVF7/105-125'
A0A7C4EVF7/132-153'
A0A7C4EVF7/165-188'
A0A7C4EVF7/200-221'
A0A7C4EVF7/233-253'
A0A7C4EVF7/265-282'
A0A7C4EVF7/288-307'
A0A7C4EVF7/319-342'
A0A7C4EVF7/362-383'
I4C9L0/6-30'
I4C9L0/42-63'
I4C9L0/98-118'
I4C9L0/125-146'
I4C9L0/158-181'
I4C9L0/193-214'
I4C9L0/226-246'
I4C9L0/258-275'
I4C9L0/281-300'
I4C9L0/312-335'
I4C9L0/355-376'
I4CCD1/6-29'
I4CCD1/36-57'
I4CCD1/93-114'
I4CCD1/126-146'
I4CCD1/158-181'
I4CCD1/193-214'
I4CCD1/226-246'
I4CCD1/258-275'
I4CCD1/281-300'
I4CCD1/312-332'
I4CCD1/352-378'
I4C9L2/6-27'
I4C9L2/39-59'
I4C9L2/96-117'
I4C9L2/124-146'
I4C9L2/158-179'
I4C9L2/191-212'
I4C9L2/224-244'
I4C9L2/256-275'
I4C9L2/281-298'
I4C9L2/310-329'
I4C9L2/349-374'
D6SPD1/13-30'
D6SPD1/51-69'
D6SPD1/109-127'
D6SPD1/134-154'
D6SPD1/174-192'
D6SPD1/204-225'
D6SPD1/245-267'
D6SPD1/274-292'
D6SPD1/298-320'
D6SPD1/332-350'
D6SPD1/356-381'
A0A975GIX9/32-53'
A0A975GIX9/65-83'
A0A975GIX9/120-142'
A0A975GIX9/149-171'
A0A975GIX9/183-204'
A0A975GIX9/216-237'
A0A975GIX9/249-269'
A0A975GIX9/281-301'
A0A975GIX9/307-324'
A0A975GIX9/336-355'
A0A975GIX9/375-398'
A0A975BTN0/32-54'
A0A975BTN0/66-84'
A0A975BTN0/122-143'
A0A975BTN0/150-172'
A0A975BTN0/184-205'
A0A975BTN0/217-237'
A0A975BTN0/249-269'
A0A975BTN0/281-302'
A0A975BTN0/308-325'
A0A975BTN0/337-356'
A0A975BTN0/376-399'
G7WFX2/6-30'
G7WFX2/42-67'
G7WFX2/87-107'
G7WFX2/119-139'
G7WFX2/159-179'
G7WFX2/200-217'
G7WFX2/229-251'
G7WFX2/263-282'
G7WFX2/288-305'
G7WFX2/317-337'
G7WFX2/349-374'
I4D6Z9/6-30'
I4D6Z9/42-63'
I4D6Z9/83-105'
I4D6Z9/117-138'
I4D6Z9/158-179'
I4D6Z9/200-217'
I4D6Z9/229-251'
I4D6Z9/263-282'
I4D6Z9/288-305'
I4D6Z9/317-337'
I4D6Z9/349-372'
G7WDB5/12-30'
G7WDB5/50-68'
G7WDB5/108-128'
G7WDB5/135-157'
G7WDB5/169-190'
G7WDB5/210-227'
G7WDB5/239-260'
G7WDB5/272-291'
G7WDB5/297-314'
G7WDB5/323-343'
G7WDB5/363-384'
G7WFX4/6-28'
G7WFX4/40-64'
G7WFX4/95-119'
G7WFX4/131-149'
G7WFX4/161-183'
G7WFX4/195-215'
G7WFX4/221-247'
G7WFX4/259-276'
G7WFX4/282-299'
G7WFX4/311-338'
G7WFX4/350-372'
G7WCB6/32-53'
G7WCB6/65-88'
G7WCB6/119-139'
G7WCB6/151-171'
G7WCB6/191-208'
G7WCB6/220-240'
G7WCB6/252-273'
G7WCB6/280-297'
G7WCB6/303-324'
G7WCB6/336-358'
G7WCB6/378-400'
G7WJN0/46-64'
G7WJN0/85-103'
G7WJN0/123-148'
G7WJN0/160-181'
G7WJN0/193-214'
G7WJN0/235-252'
G7WJN0/272-291'
G7WJN0/298-318'
G7WJN0/324-344'
G7WJN0/351-372'
G7WJN0/384-407'
G7WA28/6-30'
G7WA28/42-65'
G7WA28/97-117'
G7WA28/129-150'
G7WA28/162-185'
G7WA28/197-218'
G7WA28/230-251'
G7WA28/258-279'
G7WA28/285-305'
G7WA28/317-338'
G7WA28/358-379'
I4D1H5/6-29'
I4D1H5/41-59'
I4D1H5/96-116'
I4D1H5/128-151'
I4D1H5/163-184'
I4D1H5/196-217'
I4D1H5/229-253'
I4D1H5/260-281'
I4D1H5/287-304'
I4D1H5/316-335'
I4D1H5/355-378'
I4D6Z7/12-32'
I4D6Z7/44-64'
I4D6Z7/95-119'
I4D6Z7/131-149'
I4D6Z7/161-182'
I4D6Z7/194-215'
I4D6Z7/221-247'
I4D6Z7/259-276'
I4D6Z7/282-299'
I4D6Z7/311-334'
I4D6Z7/350-372'

I4DBY0/6-28'
I4DBY0/40-62'
I4DBY0/90-114'
I4DBY0/126-146'
I4DBY0/166-183'
I4DBY0/195-215'
I4DBY0/227-248'
I4DBY0/257-276'
I4DBY0/282-299'
I4DBY0/311-333'
I4DBY0/353-375'
J7IVQ1/38-62'
J7IVQ1/83-101'
J7IVQ1/121-146'
J7IVQ1/158-179'
J7IVQ1/191-212'
J7IVQ1/233-250'
J7IVQ1/270-287'
J7IVQ1/294-311'
J7IVQ1/317-338'
J7IVQ1/350-370'
J7IVQ1/382-408'
J7ITF6/6-30'
J7ITF6/42-60'
J7ITF6/97-117'
J7ITF6/129-150'
J7ITF6/162-185'
J7ITF6/197-218'
J7ITF6/224-247'
J7ITF6/259-279'
J7ITF6/285-305'
J7ITF6/317-338'
J7ITF6/358-379'
J7J5E7/6-28'
J7J5E7/40-63'
J7J5E7/90-114'
J7J5E7/126-146'
J7J5E7/166-183'
J7J5E7/195-215'
J7J5E7/227-248'
J7J5E7/257-275'
J7J5E7/281-302'
J7J5E7/314-333'
J7J5E7/353-375'
Q6ARH0/47-71'
Q6ARH0/83-102'
Q6ARH0/140-158'
Q6ARH0/165-185'
Q6ARH0/197-221'
Q6ARH0/241-258'
Q6ARH0/278-297'
Q6ARH0/304-322'
Q6ARH0/328-350'
Q6ARH0/362-379'
Q6ARH0/385-410'
S0G181/45-66'
S0G181/78-101'
S0G181/142-161'
S0G181/168-184'
S0G181/204-223'
S0G181/243-260'
S0G181/272-297'
S0G181/304-322'
S0G181/328-348'
S0G181/360-377'
S0G181/383-408'
A0A4Y3TAU0/6-31'
A0A4Y3TAU0/43-62'
A0A4Y3TAU0/93-113'
A0A4Y3TAU0/125-147'
A0A4Y3TAU0/159-180'
A0A4Y3TAU0/192-213'
A0A4Y3TAU0/219-245'
A0A4Y3TAU0/257-276'
A0A4Y3TAU0/282-299'
A0A4Y3TAU0/311-329'
A0A4Y3TAU0/349-370'
A0A8G2F718/45-65'
A0A8G2F718/86-106'
A0A8G2F718/126-148'
A0A8G2F718/160-181'
A0A8G2F718/201-224'
A0A8G2F718/245-262'
A0A8G2F718/274-297'
A0A8G2F718/309-327'
A0A8G2F718/333-349'
A0A8G2F718/361-380'
A0A8G2F718/400-424'
A0A4P7UHQ5/6-31'
A0A4P7UHQ5/43-62'
A0A4P7UHQ5/98-118'
A0A4P7UHQ5/125-147'
A0A4P7UHQ5/159-181'
A0A4P7UHQ5/193-213'
A0A4P7UHQ5/225-245'
A0A4P7UHQ5/257-274'
A0A4P7UHQ5/280-299'
A0A4P7UHQ5/311-336'
A0A4P7UHQ5/348-370'
B8IZX4/6-30'
B8IZX4/42-62'
B8IZX4/97-118'
B8IZX4/125-147'
B8IZX4/159-181'
B8IZX4/193-212'
B8IZX4/218-244'
B8IZX4/256-275'
B8IZX4/281-298'
B8IZX4/310-335'
B8IZX4/347-369'
A0A8G2F3G4/6-28'
A0A8G2F3G4/40-59'
A0A8G2F3G4/94-114'
A0A8G2F3G4/126-148'
A0A8G2F3G4/160-181'
A0A8G2F3G4/193-214'
A0A8G2F3G4/226-246'
A0A8G2F3G4/258-274'
A0A8G2F3G4/280-298'
A0A8G2F3G4/310-331'
A0A8G2F3G4/351-373'
A0A8G2C5E0/6-26'
A0A8G2C5E0/47-68'
A0A8G2C5E0/88-109'
A0A8G2C5E0/116-138'
A0A8G2C5E0/158-179'
A0A8G2C5E0/200-217'
A0A8G2C5E0/229-253'
A0A8G2C5E0/260-278'
A0A8G2C5E0/284-304'
A0A8G2C5E0/316-334'
A0A8G2C5E0/349-371'
F0JGZ1/6-29'
F0JGZ1/36-57'
F0JGZ1/99-119'
F0JGZ1/126-148'
F0JGZ1/160-181'
F0JGZ1/193-214'
F0JGZ1/226-246'
F0JGZ1/258-275'
F0JGZ1/281-300'
F0JGZ1/312-334'
F0JGZ1/346-368'
A0A7C2VMH5/34-57'
A0A7C2VMH5/69-91'
A0A7C2VMH5/122-141'
A0A7C2VMH5/153-174'
A0A7C2VMH5/186-208'
A0A7C2VMH5/220-240'
A0A7C2VMH5/252-271'
A0A7C2VMH5/283-300'
A0A7C2VMH5/306-327'
A0A7C2VMH5/339-358'
A0A7C2VMH5/378-398'
E6W5C1/15-34'
E6W5C1/46-65'
E6W5C1/98-117'
E6W5C1/122-139'
E6W5C1/159-181'
E6W5C1/193-213'
E6W5C1/233-254'
E6W5C1/266-281'
E6W5C1/287-307'
E6W5C1/319-336'
E6W5C1/348-367'
D6Z5V9/41-59'
D6Z5V9/80-98'
D6Z5V9/138-157'
D6Z5V9/164-186'
D6Z5V9/198-219'
D6Z5V9/239-256'
D6Z5V9/268-290'
D6Z5V9/302-318'
D6Z5V9/324-344'
D6Z5V9/356-375'
D6Z5V9/381-404'
F0S0G1/35-54'
F0S0G1/61-82'
F0S0G1/119-141'
F0S0G1/148-170'
F0S0G1/182-202'
F0S0G1/214-236'
F0S0G1/248-267'
F0S0G1/279-299'
F0S0G1/305-323'
F0S0G1/335-354'
F0S0G1/374-396'
F0S3Z6/15-36'
F0S3Z6/48-71'
F0S3Z6/91-113'
F0S3Z6/120-141'
F0S3Z6/161-185'
F0S3Z6/205-222'
F0S3Z6/234-255'
F0S3Z6/262-280'
F0S3Z6/286-302'
F0S3Z6/314-335'
F0S3Z6/347-369'
Q1K3N8/38-59'
Q1K3N8/80-103'
Q1K3N8/123-144'
Q1K3N8/151-170'
Q1K3N8/190-211'
Q1K3N8/232-249'
Q1K3N8/261-285'
Q1K3N8/292-309'
Q1K3N8/315-336'
Q1K3N8/348-365'
Q1K3N8/377-397'
Q1JXS5/31-56'
Q1JXS5/68-86'
Q1JXS5/120-142'
Q1JXS5/149-171'
Q1JXS5/191-210'
Q1JXS5/222-241'
Q1JXS5/253-272'
Q1JXS5/284-302'
Q1JXS5/308-325'
Q1JXS5/337-359'
Q1JXS5/379-405'
Q1K0H9/32-54'
Q1K0H9/66-87'
Q1K0H9/129-148'
Q1K0H9/153-170'
Q1K0H9/190-210'
Q1K0H9/231-248'
Q1K0H9/268-291'
Q1K0H9/298-316'
Q1K0H9/322-341'
Q1K0H9/348-368'
Q1K0H9/380-400'
Q1K433/12-34'
Q1K433/46-66'
Q1K433/86-109'
Q1K433/116-134'
Q1K433/154-175'
Q1K433/196-220'
Q1K433/226-249'
Q1K433/256-276'
Q1K433/282-299'
Q1K433/306-328'
Q1K433/340-365'
A0A1H4DJ49/30-52'
A0A1H4DJ49/64-85'
A0A1H4DJ49/127-146'
A0A1H4DJ49/151-168'
A0A1H4DJ49/188-208'
A0A1H4DJ49/229-246'
A0A1H4DJ49/266-289'
A0A1H4DJ49/296-313'
A0A1H4DJ49/319-339'
A0A1H4DJ49/346-367'
A0A1H4DJ49/373-398'
C0GKN4/6-28'
C0GKN4/49-71'
C0GKN4/91-112'
C0GKN4/124-145'
C0GKN4/157-178'
C0GKN4/199-216'
C0GKN4/228-253'
C0GKN4/260-277'
C0GKN4/283-304'
C0GKN4/316-335'
C0GKN4/347-371'
D2BUJ8/38-60'
D2BUJ8/72-99'
D2BUJ8/119-140'
D2BUJ8/147-165'
D2BUJ8/185-207'
D2BUJ8/219-238'
D2BUJ8/250-270'
D2BUJ8/282-301'
D2BUJ8/307-326'
D2BUJ8/338-356'
D2BUJ8/376-398'
C6CBB1/38-60'
C6CBB1/72-99'
C6CBB1/119-140'
C6CBB1/147-165'
C6CBB1/185-207'
C6CBB1/219-238'
C6CBB1/250-270'
C6CBB1/282-301'
C6CBB1/307-326'
C6CBB1/338-364'
C6CBB1/376-398'
E0SD83/36-60'
E0SD83/72-99'
E0SD83/119-140'
E0SD83/147-165'
E0SD83/185-207'
E0SD83/219-239'
E0SD83/251-270'
E0SD83/282-301'
E0SD83/307-326'
E0SD83/338-356'
E0SD83/376-398'
A0A7V3ZHK6/6-26'
A0A7V3ZHK6/47-66'
A0A7V3ZHK6/112-130'
A0A7V3ZHK6/137-160'
A0A7V3ZHK6/172-193'
A0A7V3ZHK6/214-231'
A0A7V3ZHK6/243-270'
A0A7V3ZHK6/277-296'
A0A7V3ZHK6/302-319'
A0A7V3ZHK6/331-350'
A0A7V3ZHK6/370-396'
Q9BLG3/20-40'
Q9BLG3/57-77'
Q9BLG3/102-122'
Q9BLG3/130-150'
Q9BLG3/163-183'
Q9BLG3/207-227'
Q9BLG3/247-267'
Q9BLG3/277-295'
Q9BLG3/301-319'
Q9BLG3/327-347'
Q9BLG3/379-399'
Q9BLG4/40-60'
Q9BLG4/77-97'
Q9BLG4/128-148'
Q9BLG4/161-181'
Q9BLG4/195-215'
Q9BLG4/234-254'
Q9BLG4/266-286'
Q9BLG4/294-314'
Q9BLG4/317-337'
Q9BLG4/352-372'
Q9BLG4/393-413'
Q8MXY0/28-48'
Q8MXY0/64-84'
Q8MXY0/103-125'
Q8MXY0/135-155'
Q8MXY0/161-181'
Q8MXY0/212-232'
Q8MXY0/250-270'
Q8MXY0/301-321'
Q8MXY0/334-354'
Q8MXY0/358-378'
Q8MXY0/380-400'
Q9NIV0 has 12 helices, if 12, will use last 11, if other won't include
Q9NIV0/71-91'
Q9NIV0/100-120'
Q9NIV0/142-162'
Q9NIV0/167-187'
Q9NIV0/196-216'
Q9NIV0/237-257'
Q9NIV0/264-284'
Q9NIV0/300-319'
Q9NIV0/322-342'
Q9NIV0/358-378'
Q9NIV0/407-427'
Q8I0L6 has 12 helices, if 12, will use last 11, if other won't include
Q8I0L6/74-94'
Q8I0L6/103-123'
Q8I0L6/146-166'
Q8I0L6/171-191'
Q8I0L6/200-220'
Q8I0L6/241-261'
Q8I0L6/275-295'
Q8I0L6/304-323'
Q8I0L6/326-346'
Q8I0L6/362-382'
Q8I0L6/412-432'
F0ZWG6/30-52'
F0ZWG6/59-79'
F0ZWG6/120-141'
F0ZWG6/148-170'
F0ZWG6/182-204'
F0ZWG6/216-238'
F0ZWG6/250-271'
F0ZWG6/283-301'
F0ZWG6/307-324'
F0ZWG6/336-359'
F0ZWG6/379-400'
F0ZPL3/28-51'
F0ZPL3/63-84'
F0ZPL3/104-127'
F0ZPL3/134-155'
F0ZPL3/167-190'
F0ZPL3/211-229'
F0ZPL3/249-267'
F0ZPL3/279-297'
F0ZPL3/303-323'
F0ZPL3/335-356'
F0ZPL3/376-399'
F0ZCX7 has 12 helices, if 12, will use last 11, if other won't include
F0ZCX7/72-91'
F0ZCX7/98-120'
F0ZCX7/126-145'
F0ZCX7/152-171'
F0ZCX7/183-202'
F0ZCX7/222-241'
F0ZCX7/253-273'
F0ZCX7/285-304'
F0ZCX7/310-331'
F0ZCX7/343-362'
F0ZCX7/392-416'
A0A4R3ZZ35/23-43'
A0A4R3ZZ35/55-73'
A0A4R3ZZ35/114-135'
A0A4R3ZZ35/147-168'
A0A4R3ZZ35/204-226'
A0A4R3ZZ35/238-258'
A0A4R3ZZ35/270-290'
A0A4R3ZZ35/302-319'
A0A4R3ZZ35/325-344'
A0A4R3ZZ35/356-375'
A0A4R3ZZ35/395-419'
A0A4R3ZNW3/12-31'
A0A4R3ZNW3/43-65'
A0A4R3ZNW3/101-119'
A0A4R3ZNW3/131-151'
A0A4R3ZNW3/171-196'
A0A4R3ZNW3/208-227'
A0A4R3ZNW3/239-259'
A0A4R3ZNW3/271-288'
A0A4R3ZNW3/294-313'
A0A4R3ZNW3/325-344'
A0A4R3ZNW3/364-389'
E6JCU6/23-43'
E6JCU6/55-73'
E6JCU6/114-135'
E6JCU6/147-168'
E6JCU6/204-226'
E6JCU6/238-258'
E6JCU6/270-290'
E6JCU6/302-319'
E6JCU6/325-344'
E6JCU6/356-375'
E6JCU6/395-420'
A8LKQ0/32-56'
A8LKQ0/77-96'
A8LKQ0/134-153'
A8LKQ0/158-175'
A8LKQ0/195-215'
A8LKQ0/235-252'
A8LKQ0/272-295'
A8LKQ0/302-319'
A8LKQ0/325-345'
A8LKQ0/352-373'
A8LKQ0/379-404'
A0A1I0BYN1 has 12 helices, if 12, will use last 11, if other won't include
A0A1I0BYN1/59-82'
A0A1I0BYN1/94-116'
A0A1I0BYN1/152-172'
A0A1I0BYN1/184-203'
A0A1I0BYN1/223-241'
A0A1I0BYN1/253-272'
A0A1I0BYN1/284-305'
A0A1I0BYN1/317-336'
A0A1I0BYN1/342-358'
A0A1I0BYN1/370-390'
A0A1I0BYN1/402-424'
X5DX97/15-39'
X5DX97/60-81'
X5DX97/101-120'
X5DX97/127-149'
X5DX97/161-182'
X5DX97/203-220'
X5DX97/240-261'
X5DX97/268-285'
X5DX97/291-312'
X5DX97/324-345'
X5DX97/357-382'
C6VZA0/7-25'
C6VZA0/40-61'
C6VZA0/73-96'
C6VZA0/121-145'
C6VZA0/157-180'
C6VZA0/192-213'
C6VZA0/225-247'
C6VZA0/259-280'
C6VZA0/287-304'
C6VZA0/343-364'
C6VZA0/384-407'
A0A075JZ35/27-47'
A0A075JZ35/59-79'
A0A075JZ35/123-144'
A0A075JZ35/151-172'
A0A075JZ35/192-209'
A0A075JZ35/221-241'
A0A075JZ35/253-272'
A0A075JZ35/284-302'
A0A075JZ35/308-326'
A0A075JZ35/338-356'
A0A075JZ35/376-398'

A0A0G9HEC5/25-47'
A0A0G9HEC5/59-79'
A0A0G9HEC5/123-144'
A0A0G9HEC5/151-172'
A0A0G9HEC5/192-209'
A0A0G9HEC5/221-241'
A0A0G9HEC5/253-272'
A0A0G9HEC5/284-302'
A0A0G9HEC5/308-326'
A0A0G9HEC5/338-356'
A0A0G9HEC5/376-398'
F5ISF6/62-83'
F5ISF6/95-118'
F5ISF6/158-180'
F5ISF6/187-209'
F5ISF6/221-243'
F5ISF6/255-276'
F5ISF6/288-308'
F5ISF6/320-338'
F5ISF6/344-364'
F5ISF6/376-396'
F5ISF6/416-441'
L0FU80/36-55'
L0FU80/76-95'
L0FU80/135-153'
L0FU80/160-180'
L0FU80/200-221'
L0FU80/233-253'
L0FU80/265-292'
L0FU80/299-318'
L0FU80/324-342'
L0FU80/349-370'
L0FU80/382-403'
D7G265/18-39'
D7G265/51-68'
D7G265/111-129'
D7G265/136-157'
D7G265/182-203'
D7G265/224-243'
D7G265/255-277'
D7G265/289-308'
D7G265/314-332'
D7G265/344-370'
D7G265/390-414'
A0A3R9Q7C4/69-94'
A0A3R9Q7C4/106-126'
A0A3R9Q7C4/161-181'
A0A3R9Q7C4/188-209'
A0A3R9Q7C4/229-250'
A0A3R9Q7C4/262-282'
A0A3R9Q7C4/288-311'
A0A3R9Q7C4/323-343'
A0A3R9Q7C4/349-367'
A0A3R9Q7C4/379-404'
A0A3R9Q7C4/424-449'
A0A2A7U6W1/29-51'
A0A2A7U6W1/63-83'
A0A2A7U6W1/117-139'
A0A2A7U6W1/146-168'
A0A2A7U6W1/180-202'
A0A2A7U6W1/214-233'
A0A2A7U6W1/245-265'
A0A2A7U6W1/277-296'
A0A2A7U6W1/302-321'
A0A2A7U6W1/333-351'
A0A2A7U6W1/371-393'
D4F313/38-60'
D4F313/72-92'
D4F313/126-148'
D4F313/155-177'
D4F313/189-211'
D4F313/223-242'
D4F313/254-274'
D4F313/286-305'
D4F313/311-330'
D4F313/342-360'
D4F313/380-402'
D0ZEB8/22-42'
D0ZEB8/54-72'
D0ZEB8/108-130'
D0ZEB8/137-159'
D0ZEB8/171-193'
D0ZEB8/205-224'
D0ZEB8/236-256'
D0ZEB8/268-287'
D0ZEB8/293-312'
D0ZEB8/324-342'
D0ZEB8/362-384'
A0A0H3DR67/22-42'
A0A0H3DR67/54-72'
A0A0H3DR67/108-130'
A0A0H3DR67/137-159'
A0A0H3DR67/171-193'
A0A0H3DR67/205-224'
A0A0H3DR67/236-256'
A0A0H3DR67/268-287'
A0A0H3DR67/293-312'
A0A0H3DR67/324-342'
A0A0H3DR67/362-384'
A0A369MRW6/6-29'
A0A369MRW6/41-63'
A0A369MRW6/107-126'
A0A369MRW6/133-155'
A0A369MRW6/175-192'
A0A369MRW6/204-224'
A0A369MRW6/236-257'
A0A369MRW6/266-285'
A0A369MRW6/291-311'
A0A369MRW6/323-343'
A0A369MRW6/363-388'
A0A369N7Y3/6-29'
A0A369N7Y3/41-63'
A0A369N7Y3/107-126'
A0A369N7Y3/133-155'
A0A369N7Y3/175-192'
A0A369N7Y3/204-224'
A0A369N7Y3/236-257'
A0A369N7Y3/266-285'
A0A369N7Y3/291-311'
A0A369N7Y3/323-343'
A0A369N7Y3/363-388'
A0A369MHK2/6-29'
A0A369MHK2/41-63'
A0A369MHK2/107-126'
A0A369MHK2/133-155'
A0A369MHK2/175-192'
A0A369MHK2/204-224'
A0A369MHK2/236-257'
A0A369MHK2/266-285'
A0A369MHK2/291-311'
A0A369MHK2/323-343'
A0A369MHK2/363-388'
A0A5C5BWI6/6-29'
A0A5C5BWI6/41-63'
A0A5C5BWI6/107-126'
A0A5C5BWI6/133-155'
A0A5C5BWI6/175-192'
A0A5C5BWI6/204-224'
A0A5C5BWI6/236-257'
A0A5C5BWI6/266-285'
A0A5C5BWI6/291-311'
A0A5C5BWI6/323-343'
A0A5C5BWI6/363-388'
C8WLL8/6-29'
C8WLL8/41-63'
C8WLL8/107-126'
C8WLL8/133-155'
C8WLL8/175-192'
C8WLL8/204-224'
C8WLL8/236-257'
C8WLL8/266-285'
C8WLL8/291-311'
C8WLL8/323-341'
C8WLL8/361-388'
A0A1T3DAU3 has 12 helices, if 12, will use last 11, if other won't include
A0A1T3DAU3/47-68'
A0A1T3DAU3/80-103'
A0A1T3DAU3/143-164'
A0A1T3DAU3/176-196'
A0A1T3DAU3/216-233'
A0A1T3DAU3/245-262'
A0A1T3DAU3/268-293'
A0A1T3DAU3/305-326'
A0A1T3DAU3/332-348'
A0A1T3DAU3/360-381'
A0A1T3DAU3/393-416'
A0A1T3DXP7 has 12 helices, if 12, will use last 11, if other won't include
A0A1T3DXP7/47-68'
A0A1T3DXP7/80-103'
A0A1T3DXP7/143-164'
A0A1T3DXP7/176-196'
A0A1T3DXP7/216-233'
A0A1T3DXP7/245-262'
A0A1T3DXP7/268-293'
A0A1T3DXP7/305-326'
A0A1T3DXP7/332-348'
A0A1T3DXP7/360-381'
A0A1T3DXP7/393-416'
A0A077EFU9 has 12 helices, if 12, will use last 11, if other won't include
A0A077EFU9/47-68'
A0A077EFU9/80-103'
A0A077EFU9/143-164'
A0A077EFU9/176-196'
A0A077EFU9/216-233'
A0A077EFU9/245-262'
A0A077EFU9/268-293'
A0A077EFU9/305-326'
A0A077EFU9/332-348'
A0A077EFU9/360-381'
A0A077EFU9/393-416'
A0A807YBT3 has 12 helices, if 12, will use last 11, if other won't include
A0A807YBT3/47-68'
A0A807YBT3/80-103'
A0A807YBT3/143-164'
A0A807YBT3/176-196'
A0A807YBT3/216-233'
A0A807YBT3/245-262'
A0A807YBT3/268-293'
A0A807YBT3/305-326'
A0A807YBT3/332-348'
A0A807YBT3/360-381'
A0A807YBT3/393-416'
A0A494JB70 has 12 helices, if 12, will use last 11, if other won't include
A0A494JB70/47-68'
A0A494JB70/80-103'
A0A494JB70/143-164'
A0A494JB70/176-196'
A0A494JB70/216-233'
A0A494JB70/245-262'
A0A494JB70/268-293'
A0A494JB70/305-326'
A0A494JB70/332-348'
A0A494JB70/360-381'
A0A494JB70/393-416'
R1EDV9/30-51'
R1EDV9/63-81'
R1EDV9/121-138'
R1EDV9/145-166'
R1EDV9/191-212'
R1EDV9/233-250'
R1EDV9/262-288'
R1EDV9/295-314'
R1EDV9/320-338'
R1EDV9/350-371'
R1EDV9/408-429'
R1D1H4/12-32'
R1D1H4/53-73'
R1D1H4/100-118'
R1D1H4/130-150'
R1D1H4/170-193'
R1D1H4/213-234'
R1D1H4/246-267'
R1D1H4/279-295'
R1D1H4/301-320'
R1D1H4/332-352'
R1D1H4/376-398'
R1EGK6/12-32'
R1EGK6/53-73'
R1EGK6/93-111'
R1EGK6/123-143'
R1EGK6/163-186'
R1EGK6/206-227'
R1EGK6/239-260'
R1EGK6/272-288'
R1EGK6/294-313'
R1EGK6/325-345'
R1EGK6/369-391'
R1FI09/24-45'
R1FI09/57-75'
R1FI09/121-143'
R1FI09/150-171'
R1FI09/196-217'
R1FI09/238-255'
R1FI09/267-293'
R1FI09/300-319'
R1FI09/325-343'
R1FI09/355-376'
R1FI09/409-434'
R1CIA4/20-41'
R1CIA4/53-73'
R1CIA4/110-131'
R1CIA4/138-159'
R1CIA4/171-194'
R1CIA4/214-231'
R1CIA4/243-264'
R1CIA4/271-289'
R1CIA4/295-315'
R1CIA4/327-350'
R1CIA4/370-390'
A0A5P2GF55 has 12 helices, if 12, will use last 11, if other won't include
A0A5P2GF55/47-69'
A0A5P2GF55/81-104'
A0A5P2GF55/144-165'
A0A5P2GF55/177-197'
A0A5P2GF55/217-234'
A0A5P2GF55/246-263'
A0A5P2GF55/275-296'
A0A5P2GF55/303-320'
A0A5P2GF55/332-349'
A0A5P2GF55/361-380'
A0A5P2GF55/395-419'
A0A6P1G3R3 has 12 helices, if 12, will use last 11, if other won't include
A0A6P1G3R3/47-69'
A0A6P1G3R3/81-104'
A0A6P1G3R3/144-165'
A0A6P1G3R3/177-197'
A0A6P1G3R3/217-234'
A0A6P1G3R3/246-263'
A0A6P1G3R3/275-296'
A0A6P1G3R3/303-320'
A0A6P1G3R3/332-349'
A0A6P1G3R3/361-380'
A0A6P1G3R3/395-419'
A0A511NGC7 has 12 helices, if 12, will use last 11, if other won't include
A0A511NGC7/47-69'
A0A511NGC7/81-104'
A0A511NGC7/144-165'
A0A511NGC7/177-197'
A0A511NGC7/217-234'
A0A511NGC7/246-263'
A0A511NGC7/275-296'
A0A511NGC7/303-320'
A0A511NGC7/332-349'
A0A511NGC7/361-380'
A0A511NGC7/395-419'
A0A142BI19/14-38'
A0A142BI19/50-69'
A0A142BI19/111-130'
A0A142BI19/135-152'
A0A142BI19/172-192'
A0A142BI19/213-230'
A0A142BI19/250-269'
A0A142BI19/276-294'
A0A142BI19/300-322'
A0A142BI19/334-351'
A0A142BI19/357-382'
A0A081N2G5/14-38'
A0A081N2G5/50-69'
A0A081N2G5/111-130'
A0A081N2G5/135-152'
A0A081N2G5/172-192'
A0A081N2G5/213-230'
A0A081N2G5/250-269'
A0A081N2G5/276-294'
A0A081N2G5/300-322'
A0A081N2G5/334-351'
A0A081N2G5/357-382'
A0A1T4SFK4/38-63'
A0A1T4SFK4/70-91'
A0A1T4SFK4/134-154'
A0A1T4SFK4/161-183'
A0A1T4SFK4/195-216'
A0A1T4SFK4/228-249'
A0A1T4SFK4/269-286'
A0A1T4SFK4/293-310'
A0A1T4SFK4/316-336'
A0A1T4SFK4/348-370'
A0A1T4SFK4/390-412'
A0A1T4SF40/42-62'
A0A1T4SF40/69-90'
A0A1T4SF40/130-151'
A0A1T4SF40/158-180'
A0A1T4SF40/192-213'
A0A1T4SF40/225-246'
A0A1T4SF40/258-277'
A0A1T4SF40/289-307'
A0A1T4SF40/313-333'
A0A1T4SF40/345-368'
A0A1T4SF40/388-406'
A0A1Y3U5V2/6-29'
A0A1Y3U5V2/41-63'
A0A1Y3U5V2/107-126'
A0A1Y3U5V2/133-155'
A0A1Y3U5V2/175-192'
A0A1Y3U5V2/204-223'
A0A1Y3U5V2/235-255'
A0A1Y3U5V2/267-285'
A0A1Y3U5V2/291-311'
A0A1Y3U5V2/323-347'
A0A1Y3U5V2/367-388'
A0A0L8BVU4/51-72'
A0A0L8BVU4/84-104'
A0A0L8BVU4/145-167'
A0A0L8BVU4/174-195'
A0A0L8BVU4/201-230'
A0A0L8BVU4/242-263'
A0A0L8BVU4/275-295'
A0A0L8BVU4/307-326'
A0A0L8BVU4/332-350'
A0A0L8BVU4/362-380'
A0A0L8BVU4/400-422'
W8I6E4/6-23'
W8I6E4/30-50'
W8I6E4/93-115'
W8I6E4/122-143'
W8I6E4/149-178'
W8I6E4/190-211'
W8I6E4/223-243'
W8I6E4/255-274'
W8I6E4/280-298'
W8I6E4/310-328'
W8I6E4/348-370'
A0A6S5XW90/32-58'
A0A6S5XW90/70-97'
A0A6S5XW90/117-142'
A0A6S5XW90/149-171'
A0A6S5XW90/183-205'
A0A6S5XW90/217-236'
A0A6S5XW90/248-268'
A0A6S5XW90/280-297'
A0A6S5XW90/303-324'
A0A6S5XW90/336-356'
A0A6S5XW90/376-396'
A0A6S5K4J1/37-58'
A0A6S5K4J1/70-97'
A0A6S5K4J1/117-142'
A0A6S5K4J1/149-171'
A0A6S5K4J1/183-205'
A0A6S5K4J1/217-236'
A0A6S5K4J1/248-268'
A0A6S5K4J1/280-297'
A0A6S5K4J1/303-324'
A0A6S5K4J1/336-356'
A0A6S5K4J1/376-396'
A0A6S5KAW5/38-59'
A0A6S5KAW5/71-98'
A0A6S5KAW5/118-143'
A0A6S5KAW5/150-172'
A0A6S5KAW5/184-206'
A0A6S5KAW5/218-237'
A0A6S5KAW5/249-269'
A0A6S5KAW5/281-298'
A0A6S5KAW5/304-325'
A0A6S5KAW5/337-357'
A0A6S5KAW5/377-397'
A0A2T4XZC1/38-59'
A0A2T4XZC1/71-98'
A0A2T4XZC1/118-143'
A0A2T4XZC1/150-172'
A0A2T4XZC1/184-206'
A0A2T4XZC1/218-237'
A0A2T4XZC1/249-269'
A0A2T4XZC1/281-298'
A0A2T4XZC1/304-325'
A0A2T4XZC1/337-357'
A0A2T4XZC1/377-397'

A0A330EZR0/38-59'
A0A330EZR0/71-98'
A0A330EZR0/118-143'
A0A330EZR0/150-172'
A0A330EZR0/184-206'
A0A330EZR0/218-237'
A0A330EZR0/249-269'
A0A330EZR0/281-298'
A0A330EZR0/304-325'
A0A330EZR0/337-357'
A0A330EZR0/377-397'
A0A4Q2EAG7/38-59'
A0A4Q2EAG7/71-98'
A0A4Q2EAG7/118-143'
A0A4Q2EAG7/150-172'
A0A4Q2EAG7/184-206'
A0A4Q2EAG7/218-237'
A0A4Q2EAG7/249-269'
A0A4Q2EAG7/281-298'
A0A4Q2EAG7/304-325'
A0A4Q2EAG7/337-357'
A0A4Q2EAG7/377-397'
A0A0M3F8F9/32-54'
A0A0M3F8F9/66-84'
A0A0M3F8F9/120-142'
A0A0M3F8F9/149-171'
A0A0M3F8F9/183-205'
A0A0M3F8F9/217-236'
A0A0M3F8F9/248-268'
A0A0M3F8F9/280-297'
A0A0M3F8F9/303-324'
A0A0M3F8F9/336-362'
A0A0M3F8F9/374-396'
A0A330GB00/38-59'
A0A330GB00/71-98'
A0A330GB00/118-143'
A0A330GB00/150-172'
A0A330GB00/184-206'
A0A330GB00/218-237'
A0A330GB00/249-269'
A0A330GB00/281-298'
A0A330GB00/304-325'
A0A330GB00/337-357'
A0A330GB00/377-397'
A0A443Y093/37-58'
A0A443Y093/70-97'
A0A443Y093/117-142'
A0A443Y093/149-171'
A0A443Y093/183-205'
A0A443Y093/217-236'
A0A443Y093/248-268'
A0A443Y093/280-297'
A0A443Y093/303-324'
A0A443Y093/336-356'
A0A443Y093/376-396'
A0A144NLT9/38-59'
A0A144NLT9/71-98'
A0A144NLT9/118-143'
A0A144NLT9/150-172'
A0A144NLT9/184-206'
A0A144NLT9/218-237'
A0A144NLT9/249-269'
A0A144NLT9/281-298'
A0A144NLT9/304-325'
A0A144NLT9/337-357'
A0A144NLT9/377-397'
A0A7H9JPM9/32-54'
A0A7H9JPM9/66-84'
A0A7H9JPM9/120-142'
A0A7H9JPM9/149-171'
A0A7H9JPM9/183-205'
A0A7H9JPM9/217-236'
A0A7H9JPM9/248-268'
A0A7H9JPM9/280-297'
A0A7H9JPM9/303-324'
A0A7H9JPM9/336-356'
A0A7H9JPM9/376-396'
A0A7H8UK07/32-54'
A0A7H8UK07/66-84'
A0A7H8UK07/120-142'
A0A7H8UK07/149-171'
A0A7H8UK07/183-205'
A0A7H8UK07/217-236'
A0A7H8UK07/248-268'
A0A7H8UK07/280-297'
A0A7H8UK07/303-324'
A0A7H8UK07/336-356'
A0A7H8UK07/376-396'
A0A411GDE8/38-59'
A0A411GDE8/71-98'
A0A411GDE8/118-143'
A0A411GDE8/150-172'
A0A411GDE8/184-206'
A0A411GDE8/218-237'
A0A411GDE8/249-269'
A0A411GDE8/281-298'
A0A411GDE8/304-325'
A0A411GDE8/337-357'
A0A411GDE8/377-397'
A0A427KNL6/32-54'
A0A427KNL6/66-84'
A0A427KNL6/120-142'
A0A427KNL6/149-171'
A0A427KNL6/183-205'
A0A427KNL6/217-236'
A0A427KNL6/248-268'
A0A427KNL6/280-297'
A0A427KNL6/303-324'
A0A427KNL6/336-356'
A0A427KNL6/376-396'
A0A4Q4A8K6/32-54'
A0A4Q4A8K6/66-84'
A0A4Q4A8K6/120-142'
A0A4Q4A8K6/149-171'
A0A4Q4A8K6/183-205'
A0A4Q4A8K6/217-236'
A0A4Q4A8K6/248-268'
A0A4Q4A8K6/280-297'
A0A4Q4A8K6/303-324'
A0A4Q4A8K6/336-356'
A0A4Q4A8K6/376-396'
A0A801DSC9/32-54'
A0A801DSC9/66-84'
A0A801DSC9/120-142'
A0A801DSC9/149-171'
A0A801DSC9/183-205'
A0A801DSC9/217-236'
A0A801DSC9/248-268'
A0A801DSC9/280-297'
A0A801DSC9/303-324'
A0A801DSC9/336-356'
A0A801DSC9/376-396'
A0A2W0GQV0/37-58'
A0A2W0GQV0/70-97'
A0A2W0GQV0/117-142'
A0A2W0GQV0/149-171'
A0A2W0GQV0/183-205'
A0A2W0GQV0/217-236'
A0A2W0GQV0/248-268'
A0A2W0GQV0/280-297'
A0A2W0GQV0/303-324'
A0A2W0GQV0/336-356'
A0A2W0GQV0/376-396'
A0A8H9CE40/32-54'
A0A8H9CE40/66-84'
A0A8H9CE40/120-142'
A0A8H9CE40/149-171'
A0A8H9CE40/183-205'
A0A8H9CE40/217-236'
A0A8H9CE40/248-268'
A0A8H9CE40/280-297'
A0A8H9CE40/303-324'
A0A8H9CE40/336-356'
A0A8H9CE40/376-396'
A0A1Z3MS36/38-59'
A0A1Z3MS36/71-98'
A0A1Z3MS36/118-143'
A0A1Z3MS36/150-172'
A0A1Z3MS36/184-206'
A0A1Z3MS36/218-237'
A0A1Z3MS36/249-269'
A0A1Z3MS36/281-298'
A0A1Z3MS36/304-325'
A0A1Z3MS36/337-357'
A0A1Z3MS36/377-397'
A0A2S4SRB5/38-59'
A0A2S4SRB5/71-98'
A0A2S4SRB5/118-143'
A0A2S4SRB5/150-172'
A0A2S4SRB5/184-206'
A0A2S4SRB5/218-237'
A0A2S4SRB5/249-269'
A0A2S4SRB5/281-298'
A0A2S4SRB5/304-325'
A0A2S4SRB5/337-357'
A0A2S4SRB5/377-397'
A0A421IL65/32-54'
A0A421IL65/66-84'
A0A421IL65/120-142'
A0A421IL65/149-171'
A0A421IL65/183-205'
A0A421IL65/217-236'
A0A421IL65/248-268'
A0A421IL65/280-297'
A0A421IL65/303-324'
A0A421IL65/336-356'
A0A421IL65/376-396'
A0A855M376/38-59'
A0A855M376/71-98'
A0A855M376/118-143'
A0A855M376/150-172'
A0A855M376/184-206'
A0A855M376/218-237'
A0A855M376/249-269'
A0A855M376/281-298'
A0A855M376/304-325'
A0A855M376/337-357'
A0A855M376/377-397'
A0A0M2ADU2/6-25'
A0A0M2ADU2/37-58'
A0A0M2ADU2/78-100'
A0A0M2ADU2/107-128'
A0A0M2ADU2/148-167'
A0A0M2ADU2/179-197'
A0A0M2ADU2/209-232'
A0A0M2ADU2/239-259'
A0A0M2ADU2/265-283'
A0A0M2ADU2/295-313'
A0A0M2ADU2/319-343'
R3H4W8/6-25'
R3H4W8/37-58'
R3H4W8/78-100'
R3H4W8/107-128'
R3H4W8/148-167'
R3H4W8/179-197'
R3H4W8/209-232'
R3H4W8/239-258'
R3H4W8/264-283'
R3H4W8/295-313'
R3H4W8/319-343'
V7ZMI3/6-25'
V7ZMI3/37-58'
V7ZMI3/78-100'
V7ZMI3/107-128'
V7ZMI3/148-167'
V7ZMI3/179-197'
V7ZMI3/209-232'
V7ZMI3/239-258'
V7ZMI3/264-283'
V7ZMI3/295-313'
V7ZMI3/319-343'
A0A2N7LCD7/12-33'
A0A2N7LCD7/54-74'
A0A2N7LCD7/104-123'
A0A2N7LCD7/128-145'
A0A2N7LCD7/165-185'
A0A2N7LCD7/206-223'
A0A2N7LCD7/243-262'
A0A2N7LCD7/269-287'
A0A2N7LCD7/293-315'
A0A2N7LCD7/327-344'
A0A2N7LCD7/350-375'
A0A2N7L7C8/18-39'
A0A2N7L7C8/51-73'
A0A2N7L7C8/93-111'
A0A2N7L7C8/123-144'
A0A2N7L7C8/164-185'
A0A2N7L7C8/197-221'
A0A2N7L7C8/233-255'
A0A2N7L7C8/262-280'
A0A2N7L7C8/286-304'
A0A2N7L7C8/316-336'
A0A2N7L7C8/348-372'
A0A1E5BXA4/12-33'
A0A1E5BXA4/54-74'
A0A1E5BXA4/104-123'
A0A1E5BXA4/128-145'
A0A1E5BXA4/165-185'
A0A1E5BXA4/206-223'
A0A1E5BXA4/243-262'
A0A1E5BXA4/269-287'
A0A1E5BXA4/293-315'
A0A1E5BXA4/327-344'
A0A1E5BXA4/350-375'
A0A1E5C7W4/18-39'
A0A1E5C7W4/51-73'
A0A1E5C7W4/93-111'
A0A1E5C7W4/123-144'
A0A1E5C7W4/164-185'
A0A1E5C7W4/197-221'
A0A1E5C7W4/233-255'
A0A1E5C7W4/262-280'
A0A1E5C7W4/286-304'
A0A1E5C7W4/316-336'
A0A1E5C7W4/348-372'
A0A1I5W440/12-33'
A0A1I5W440/54-74'
A0A1I5W440/104-123'
A0A1I5W440/128-145'
A0A1I5W440/165-185'
A0A1I5W440/206-223'
A0A1I5W440/243-262'
A0A1I5W440/269-287'
A0A1I5W440/293-315'
A0A1I5W440/327-344'
A0A1I5W440/350-375'
A0A1I5SNU9/18-39'
A0A1I5SNU9/51-73'
A0A1I5SNU9/93-111'
A0A1I5SNU9/123-144'
A0A1I5SNU9/164-185'
A0A1I5SNU9/197-221'
A0A1I5SNU9/233-255'
A0A1I5SNU9/262-280'
A0A1I5SNU9/286-304'
A0A1I5SNU9/316-336'
A0A1I5SNU9/348-372'
G8JTW0/12-35'
G8JTW0/47-65'
G8JTW0/105-125'
G8JTW0/137-155'
G8JTW0/175-191'
G8JTW0/203-223'
G8JTW0/235-256'
G8JTW0/263-281'
G8JTW0/287-305'
G8JTW0/326-345'
G8JTW0/365-390'
G8JUJ2/31-52'
G8JUJ2/64-82'
G8JUJ2/122-141'
G8JUJ2/153-174'
G8JUJ2/186-206'
G8JUJ2/227-244'
G8JUJ2/256-277'
G8JUJ2/286-305'
G8JUJ2/311-329'
G8JUJ2/341-363'
G8JUJ2/391-414'
D4HY35 has 12 helices, if 12, will use last 11, if other won't include
D4HY35/38-59'
D4HY35/71-89'
D4HY35/125-147'
D4HY35/154-176'
D4HY35/188-210'
D4HY35/222-241'
D4HY35/253-272'
D4HY35/284-302'
D4HY35/308-329'
D4HY35/341-360'
D4HY35/380-401'
A0A830ZZN8/31-54'
A0A830ZZN8/66-84'
A0A830ZZN8/120-142'
A0A830ZZN8/149-171'
A0A830ZZN8/183-205'
A0A830ZZN8/217-236'
A0A830ZZN8/248-267'
A0A830ZZN8/279-297'
A0A830ZZN8/303-324'
A0A830ZZN8/336-355'
A0A830ZZN8/375-396'
E5B358 has 12 helices, if 12, will use last 11, if other won't include
E5B358/38-59'
E5B358/71-89'
E5B358/125-147'
E5B358/154-176'
E5B358/188-210'
E5B358/222-241'
E5B358/253-272'
E5B358/284-302'
E5B358/308-329'
E5B358/341-360'
E5B358/380-401'
A0A074ME37/39-59'
A0A074ME37/71-91'
A0A074ME37/132-150'
A0A074ME37/162-184'
A0A074ME37/196-218'
A0A074ME37/230-250'
A0A074ME37/262-281'
A0A074ME37/293-311'
A0A074ME37/317-337'
A0A074ME37/349-368'
A0A074ME37/388-411'
Q2N625/40-61'
Q2N625/73-91'
Q2N625/132-150'
Q2N625/162-184'
Q2N625/196-218'
Q2N625/230-250'
Q2N625/262-281'
Q2N625/293-311'
Q2N625/317-335'
Q2N625/347-371'
Q2N625/391-411'
A0A7V8RCZ2/66-87'
A0A7V8RCZ2/99-119'
A0A7V8RCZ2/159-181'
A0A7V8RCZ2/188-212'
A0A7V8RCZ2/232-257'
A0A7V8RCZ2/269-289'
A0A7V8RCZ2/301-321'
A0A7V8RCZ2/333-353'
A0A7V8RCZ2/359-376'
A0A7V8RCZ2/388-407'
A0A7V8RCZ2/441-460'
A0A7V8RAY5/41-61'
A0A7V8RAY5/73-92'
A0A7V8RAY5/130-151'
A0A7V8RAY5/158-180'
A0A7V8RAY5/192-213'
A0A7V8RAY5/225-246'
A0A7V8RAY5/258-279'
A0A7V8RAY5/286-307'
A0A7V8RAY5/313-333'
A0A7V8RAY5/345-364'
A0A7V8RAY5/384-409'
P69681/33-54'
P69681/66-90'
P69681/120-142'
P69681/147-171'
P69681/186-201'
P69681/222-241'
P69681/249-273'
P69681/280-300'
P69681/303-321'
P69681/334-355'
P69681/371-399'
P25527 has 12 helices, if 12, will use last 11, if other won't include
P25527/42-62'
P25527/97-117'
P25527/119-139'
P25527/154-174'
P25527/200-220'
P25527/247-267'
P25527/287-307'
P25527/335-355'
P25527/359-379'
P25527/403-423'
P25527/429-449'
P39386 has 12 helices, if 12, will use last 11, if other won't include
P39386/49-69'
P39386/79-99'
P39386/104-124'
P39386/141-161'
P39386/168-188'
P39386/217-237'
P39386/252-272'
P39386/283-303'
P39386/308-328'
P39386/349-369'
P39386/374-394'
P69680/33-54'
P69680/66-90'
P69680/120-142'
P69680/147-171'
P69680/186-201'
P69680/222-241'
P69680/249-273'
P69680/280-300'
P69680/303-321'
P69680/334-355'
P69680/371-399'

A0A942VQZ7/6-29'
A0A942VQZ7/50-76'
A0A942VQZ7/96-117'
A0A942VQZ7/124-146'
A0A942VQZ7/158-179'
A0A942VQZ7/200-217'
A0A942VQZ7/229-253'
A0A942VQZ7/260-277'
A0A942VQZ7/283-304'
A0A942VQZ7/316-337'
A0A942VQZ7/357-382'
A0A1H0VGF5/6-28'
A0A1H0VGF5/40-64'
A0A1H0VGF5/90-116'
A0A1H0VGF5/128-149'
A0A1H0VGF5/161-183'
A0A1H0VGF5/195-212'
A0A1H0VGF5/224-248'
A0A1H0VGF5/255-273'
A0A1H0VGF5/279-296'
A0A1H0VGF5/308-328'
A0A1H0VGF5/348-369'
A0A317RN92/6-29'
A0A317RN92/50-76'
A0A317RN92/96-117'
A0A317RN92/124-146'
A0A317RN92/158-179'
A0A317RN92/200-217'
A0A317RN92/229-253'
A0A317RN92/260-277'
A0A317RN92/283-304'
A0A317RN92/316-337'
A0A317RN92/357-382'
A0A317RMH8/7-28'
A0A317RMH8/40-64'
A0A317RMH8/97-120'
A0A317RMH8/127-149'
A0A317RMH8/161-183'
A0A317RMH8/195-212'
A0A317RMH8/224-248'
A0A317RMH8/255-273'
A0A317RMH8/279-296'
A0A317RMH8/308-328'
A0A317RMH8/348-369'
A0A942ZQQ0/7-28'
A0A942ZQQ0/40-64'
A0A942ZQQ0/97-120'
A0A942ZQQ0/127-149'
A0A942ZQQ0/161-183'
A0A942ZQQ0/195-212'
A0A942ZQQ0/224-248'
A0A942ZQQ0/255-273'
A0A942ZQQ0/279-296'
A0A942ZQQ0/308-328'
A0A942ZQQ0/348-369'
A0A317RML7/6-29'
A0A317RML7/41-62'
A0A317RML7/97-118'
A0A317RML7/130-150'
A0A317RML7/170-187'
A0A317RML7/199-218'
A0A317RML7/230-251'
A0A317RML7/258-276'
A0A317RML7/282-302'
A0A317RML7/314-336'
A0A317RML7/356-382'
A0A6N2Z556/6-29'
A0A6N2Z556/50-76'
A0A6N2Z556/96-117'
A0A6N2Z556/124-146'
A0A6N2Z556/158-179'
A0A6N2Z556/200-217'
A0A6N2Z556/229-253'
A0A6N2Z556/260-277'
A0A6N2Z556/283-304'
A0A6N2Z556/316-337'
A0A6N2Z556/357-382'
A0A6N2YNZ0/7-28'
A0A6N2YNZ0/40-64'
A0A6N2YNZ0/97-120'
A0A6N2YNZ0/127-149'
A0A6N2YNZ0/161-183'
A0A6N2YNZ0/195-212'
A0A6N2YNZ0/224-248'
A0A6N2YNZ0/255-273'
A0A6N2YNZ0/279-296'
A0A6N2YNZ0/308-328'
A0A6N2YNZ0/348-369'
A0A0U2VGX2/6-29'
A0A0U2VGX2/50-76'
A0A0U2VGX2/96-117'
A0A0U2VGX2/124-146'
A0A0U2VGX2/158-179'
A0A0U2VGX2/200-217'
A0A0U2VGX2/229-253'
A0A0U2VGX2/260-277'
A0A0U2VGX2/283-304'
A0A0U2VGX2/316-337'
A0A0U2VGX2/357-382'
E3GQ97/6-29'
E3GQ97/50-76'
E3GQ97/96-117'
E3GQ97/124-146'
E3GQ97/158-179'
E3GQ97/200-217'
E3GQ97/229-253'
E3GQ97/260-277'
E3GQ97/283-304'
E3GQ97/316-337'
E3GQ97/357-382'
E3GI40/7-28'
E3GI40/40-64'
E3GI40/97-120'
E3GI40/127-149'
E3GI40/161-183'
E3GI40/195-212'
E3GI40/224-248'
E3GI40/255-273'
E3GI40/279-296'
E3GI40/308-328'
E3GI40/348-369'
A0A2N0MZ27/32-55'
A0A2N0MZ27/67-85'
A0A2N0MZ27/121-143'
A0A2N0MZ27/150-172'
A0A2N0MZ27/184-206'
A0A2N0MZ27/218-238'
A0A2N0MZ27/244-268'
A0A2N0MZ27/280-298'
A0A2N0MZ27/304-325'
A0A2N0MZ27/337-355'
A0A2N0MZ27/375-397'
A0A502GPV4/32-55'
A0A502GPV4/67-85'
A0A502GPV4/121-143'
A0A502GPV4/150-172'
A0A502GPV4/184-206'
A0A502GPV4/218-238'
A0A502GPV4/244-268'
A0A502GPV4/280-298'
A0A502GPV4/304-325'
A0A502GPV4/337-355'
A0A502GPV4/375-397'
A0A085G774/32-55'
A0A085G774/67-85'
A0A085G774/121-143'
A0A085G774/150-172'
A0A085G774/184-206'
A0A085G774/218-238'
A0A085G774/244-268'
A0A085G774/280-298'
A0A085G774/304-325'
A0A085G774/337-355'
A0A085G774/375-397'
A0A3E2TW06/12-32'
A0A3E2TW06/53-71'
A0A3E2TW06/91-110'
A0A3E2TW06/122-143'
A0A3E2TW06/155-176'
A0A3E2TW06/197-214'
A0A3E2TW06/226-255'
A0A3E2TW06/262-280'
A0A3E2TW06/286-306'
A0A3E2TW06/318-336'
A0A3E2TW06/356-378'
A0A3R6HLW9/12-32'
A0A3R6HLW9/53-71'
A0A3R6HLW9/91-110'
A0A3R6HLW9/122-143'
A0A3R6HLW9/155-176'
A0A3R6HLW9/197-214'
A0A3R6HLW9/226-255'
A0A3R6HLW9/262-280'
A0A3R6HLW9/286-306'
A0A3R6HLW9/318-336'
A0A3R6HLW9/356-378'
A0A6A8KQL6/12-32'
A0A6A8KQL6/53-71'
A0A6A8KQL6/91-110'
A0A6A8KQL6/122-143'
A0A6A8KQL6/155-176'
A0A6A8KQL6/197-214'
A0A6A8KQL6/226-255'
A0A6A8KQL6/262-280'
A0A6A8KQL6/286-306'
A0A6A8KQL6/318-336'
A0A6A8KQL6/356-378'
A0A844DSN8/6-27'
A0A844DSN8/48-71'
A0A844DSN8/91-110'
A0A844DSN8/122-143'
A0A844DSN8/155-176'
A0A844DSN8/197-214'
A0A844DSN8/234-255'
A0A844DSN8/262-280'
A0A844DSN8/286-306'
A0A844DSN8/318-336'
A0A844DSN8/356-378'
A0A844DI00/12-32'
A0A844DI00/53-71'
A0A844DI00/91-110'
A0A844DI00/122-143'
A0A844DI00/155-176'
A0A844DI00/197-214'
A0A844DI00/226-255'
A0A844DI00/262-280'
A0A844DI00/286-306'
A0A844DI00/318-336'
A0A844DI00/356-378'
A0A413D0R3/12-32'
A0A413D0R3/53-71'
A0A413D0R3/91-110'
A0A413D0R3/122-143'
A0A413D0R3/155-176'
A0A413D0R3/197-214'
A0A413D0R3/226-255'
A0A413D0R3/262-280'
A0A413D0R3/286-306'
A0A413D0R3/318-336'
A0A413D0R3/356-378'
A0A3E2UCG9/12-32'
A0A3E2UCG9/53-71'
A0A3E2UCG9/91-110'
A0A3E2UCG9/122-143'
A0A3E2UCG9/155-176'
A0A3E2UCG9/197-214'
A0A3E2UCG9/230-252'
A0A3E2UCG9/264-280'
A0A3E2UCG9/286-306'
A0A3E2UCG9/318-336'
A0A3E2UCG9/356-378'
A0A3E2UHE6/12-32'
A0A3E2UHE6/53-71'
A0A3E2UHE6/91-110'
A0A3E2UHE6/122-143'
A0A3E2UHE6/155-176'
A0A3E2UHE6/197-214'
A0A3E2UHE6/226-255'
A0A3E2UHE6/262-280'
A0A3E2UHE6/286-306'
A0A3E2UHE6/318-336'
A0A3E2UHE6/356-378'
A0A3E2VY88/12-32'
A0A3E2VY88/53-71'
A0A3E2VY88/91-110'
A0A3E2VY88/122-143'
A0A3E2VY88/155-176'
A0A3E2VY88/197-214'
A0A3E2VY88/226-255'
A0A3E2VY88/262-280'
A0A3E2VY88/286-306'
A0A3E2VY88/318-336'
A0A3E2VY88/356-378'
A0A3E2T713/6-27'
A0A3E2T713/48-71'
A0A3E2T713/91-110'
A0A3E2T713/122-143'
A0A3E2T713/155-176'
A0A3E2T713/197-214'
A0A3E2T713/234-255'
A0A3E2T713/262-280'
A0A3E2T713/286-306'
A0A3E2T713/318-336'
A0A3E2T713/356-378'
A0A3E2XB32/6-27'
A0A3E2XB32/48-71'
A0A3E2XB32/91-110'
A0A3E2XB32/122-143'
A0A3E2XB32/155-176'
A0A3E2XB32/197-214'
A0A3E2XB32/234-255'
A0A3E2XB32/262-280'
A0A3E2XB32/286-306'
A0A3E2XB32/318-336'
A0A3E2XB32/356-378'
E1SLM7/20-40'
E1SLM7/60-78'
E1SLM7/108-127'
E1SLM7/132-149'
E1SLM7/169-190'
E1SLM7/211-228'
E1SLM7/248-267'
E1SLM7/274-292'
E1SLM7/298-318'
E1SLM7/330-349'
E1SLM7/355-380'
D3S2L0/6-26'
D3S2L0/38-59'
D3S2L0/79-99'
D3S2L0/106-128'
D3S2L0/140-162'
D3S2L0/174-194'
D3S2L0/206-227'
D3S2L0/234-253'
D3S2L0/259-277'
D3S2L0/289-308'
D3S2L0/314-335'
S0APH6/27-50'
S0APH6/62-81'
S0APH6/130-149'
S0APH6/156-178'
S0APH6/190-211'
S0APH6/223-240'
S0APH6/252-273'
S0APH6/285-303'
S0APH6/309-328'
S0APH6/340-361'
S0APH6/381-406'
S0AM98 has 12 helices, if 12, will use last 11, if other won't include
S0AM98/60-81'
S0AM98/121-141'
S0AM98/148-167'
S0AM98/187-205'
S0AM98/225-242'
S0AM98/254-276'
S0AM98/283-304'
S0AM98/310-330'
S0AM98/342-360'
S0AM98/366-387'
S0AM98/394-415'
I0KDC6/40-61'
I0KDC6/73-96'
I0KDC6/122-148'
I0KDC6/160-181'
I0KDC6/193-216'
I0KDC6/228-250'
I0KDC6/262-282'
I0KDC6/294-313'
I0KDC6/319-336'
I0KDC6/348-368'
I0KDC6/388-410'
I2GD40/42-63'
I2GD40/75-98'
I2GD40/124-150'
I2GD40/162-183'
I2GD40/195-218'
I2GD40/230-252'
I2GD40/264-285'
I2GD40/292-309'
I2GD40/315-336'
I2GD40/348-369'
I2GD40/389-412'
A0A068NPW2/37-59'
A0A068NPW2/71-93'
A0A068NPW2/129-149'
A0A068NPW2/161-184'
A0A068NPW2/196-217'
A0A068NPW2/229-250'
A0A068NPW2/262-282'
A0A068NPW2/294-312'
A0A068NPW2/318-337'
A0A068NPW2/349-370'
A0A068NPW2/390-412'
A0A931PT48/6-31'
A0A931PT48/43-63'
A0A931PT48/92-112'
A0A931PT48/124-147'
A0A931PT48/159-181'
A0A931PT48/193-210'
A0A931PT48/216-240'
A0A931PT48/252-273'
A0A931PT48/279-296'
A0A931PT48/308-335'
A0A931PT48/347-369'
A0A068NV61/79-102'
A0A068NV61/114-135'
A0A068NV61/155-173'
A0A068NV61/194-216'
A0A068NV61/236-260'
A0A068NV61/281-298'
A0A068NV61/318-340'
A0A068NV61/347-369'
A0A068NV61/375-393'
A0A068NV61/405-429'
A0A068NV61/449-474'
A0A2N6K4Y5/45-66'
A0A2N6K4Y5/78-97'
A0A2N6K4Y5/142-162'
A0A2N6K4Y5/174-195'
A0A2N6K4Y5/215-235'
A0A2N6K4Y5/247-266'
A0A2N6K4Y5/272-297'
A0A2N6K4Y5/309-327'
A0A2N6K4Y5/333-352'
A0A2N6K4Y5/364-387'
A0A2N6K4Y5/407-428'
A0A2N6JV02 has 12 helices, if 12, will use last 11, if other won't include
A0A2N6JV02/84-108'
A0A2N6JV02/120-140'
A0A2N6JV02/185-205'
A0A2N6JV02/212-233'
A0A2N6JV02/245-267'
A0A2N6JV02/279-303'
A0A2N6JV02/315-342'
A0A2N6JV02/349-369'
A0A2N6JV02/375-391'
A0A2N6JV02/403-422'
A0A2N6JV02/451-476'
A0A243SC06/43-67'
A0A243SC06/79-106'
A0A243SC06/126-148'
A0A243SC06/160-178'
A0A243SC06/198-219'
A0A243SC06/231-248'
A0A243SC06/260-281'
A0A243SC06/293-311'
A0A243SC06/317-335'
A0A243SC06/347-365'
A0A243SC06/393-412'
F8E6R1/14-38'
F8E6R1/50-69'
F8E6R1/110-129'
F8E6R1/134-151'
F8E6R1/171-191'
F8E6R1/212-229'
F8E6R1/249-272'
F8E6R1/279-297'
F8E6R1/303-321'
F8E6R1/333-351'
F8E6R1/357-382'
A0A1I4ZIZ6/71-93'
A0A1I4ZIZ6/105-127'
A0A1I4ZIZ6/168-189'
A0A1I4ZIZ6/196-217'
A0A1I4ZIZ6/223-252'
A0A1I4ZIZ6/264-285'
A0A1I4ZIZ6/297-316'
A0A1I4ZIZ6/328-348'
A0A1I4ZIZ6/354-372'
A0A1I4ZIZ6/384-404'
A0A1I4ZIZ6/416-436'
T2KJ59/28-47'
T2KJ59/68-88'
T2KJ59/108-128'
T2KJ59/135-153'
T2KJ59/173-193'
T2KJ59/214-230'
T2KJ59/250-270'
T2KJ59/277-296'
T2KJ59/302-321'
T2KJ59/333-353'
T2KJ59/373-395'

T2KGT3/6-30'
T2KGT3/42-65'
T2KGT3/104-123'
T2KGT3/128-146'
T2KGT3/166-185'
T2KGT3/205-222'
T2KGT3/234-256'
T2KGT3/268-286'
T2KGT3/292-310'
T2KGT3/322-342'
T2KGT3/348-373'
Q0RPB4/14-35'
Q0RPB4/47-69'
Q0RPB4/103-123'
Q0RPB4/135-156'
Q0RPB4/176-193'
Q0RPB4/205-224'
Q0RPB4/236-257'
Q0RPB4/264-285'
Q0RPB4/291-310'
Q0RPB4/322-343'
Q0RPB4/363-385'
H8L2Q4/38-57'
H8L2Q4/69-89'
H8L2Q4/133-154'
H8L2Q4/161-182'
H8L2Q4/194-219'
H8L2Q4/231-251'
H8L2Q4/263-282'
H8L2Q4/294-313'
H8L2Q4/319-338'
H8L2Q4/350-373'
H8L2Q4/393-411'
A0A3F3HWV6/6-30'
A0A3F3HWV6/42-62'
A0A3F3HWV6/95-117'
A0A3F3HWV6/124-145'
A0A3F3HWV6/157-180'
A0A3F3HWV6/192-209'
A0A3F3HWV6/221-243'
A0A3F3HWV6/255-273'
A0A3F3HWV6/279-296'
A0A3F3HWV6/308-327'
A0A3F3HWV6/350-368'
A0A0P0Z9P6/40-60'
A0A0P0Z9P6/72-95'
A0A0P0Z9P6/133-155'
A0A0P0Z9P6/162-183'
A0A0P0Z9P6/203-224'
A0A0P0Z9P6/236-257'
A0A0P0Z9P6/269-290'
A0A0P0Z9P6/297-315'
A0A0P0Z9P6/321-344'
A0A0P0Z9P6/356-382'
A0A0P0Z9P6/394-416'
Q0G0A4/40-60'
Q0G0A4/72-95'
Q0G0A4/133-155'
Q0G0A4/162-183'
Q0G0A4/203-224'
Q0G0A4/236-257'
Q0G0A4/269-290'
Q0G0A4/297-315'
Q0G0A4/321-344'
Q0G0A4/356-382'
Q0G0A4/394-416'
A0A0N7KZ12/57-78'
A0A0N7KZ12/99-117'
A0A0N7KZ12/152-171'
A0A0N7KZ12/178-200'
A0A0N7KZ12/212-233'
A0A0N7KZ12/254-271'
A0A0N7KZ12/291-310'
A0A0N7KZ12/317-335'
A0A0N7KZ12/341-363'
A0A0N7KZ12/375-392'
A0A0N7KZ12/398-423'
Q0G0A3/57-78'
Q0G0A3/99-117'
Q0G0A3/152-171'
Q0G0A3/178-200'
Q0G0A3/212-233'
Q0G0A3/254-271'
Q0G0A3/291-310'
Q0G0A3/317-335'
Q0G0A3/341-363'
Q0G0A3/375-392'
Q0G0A3/398-423'
Q0G2V0/29-46'
Q0G2V0/66-84'
Q0G2V0/117-139'
Q0G2V0/146-167'
Q0G2V0/182-203'
Q0G2V0/224-250'
Q0G2V0/262-283'
Q0G2V0/290-307'
Q0G2V0/313-330'
Q0G2V0/342-365'
Q0G2V0/377-399'
Q0G2U1/15-34'
Q0G2U1/55-76'
Q0G2U1/114-132'
Q0G2U1/144-166'
Q0G2U1/178-199'
Q0G2U1/220-245'
Q0G2U1/265-284'
Q0G2U1/291-307'
Q0G2U1/313-330'
Q0G2U1/342-361'
Q0G2U1/387-412'
Q0G2T1/15-34'
Q0G2T1/54-73'
Q0G2T1/108-130'
Q0G2T1/137-158'
Q0G2T1/178-195'
Q0G2T1/216-241'
Q0G2T1/261-287'
Q0G2T1/294-311'
Q0G2T1/317-334'
Q0G2T1/346-368'
Q0G2T1/388-407'
L8JUH3/45-66'
L8JUH3/78-101'
L8JUH3/139-158'
L8JUH3/165-187'
L8JUH3/199-220'
L8JUH3/240-257'
L8JUH3/269-296'
L8JUH3/303-319'
L8JUH3/325-345'
L8JUH3/357-376'
L8JUH3/388-410'
K2IMJ7/15-39'
K2IMJ7/51-70'
K2IMJ7/112-131'
K2IMJ7/136-153'
K2IMJ7/173-193'
K2IMJ7/214-231'
K2IMJ7/251-274'
K2IMJ7/281-298'
K2IMJ7/304-323'
K2IMJ7/332-351'
K2IMJ7/357-383'
A0A837CWL2/36-57'
A0A837CWL2/69-91'
A0A837CWL2/132-153'
A0A837CWL2/160-183'
A0A837CWL2/195-217'
A0A837CWL2/229-249'
A0A837CWL2/261-281'
A0A837CWL2/293-312'
A0A837CWL2/318-336'
A0A837CWL2/348-367'
A0A837CWL2/379-402'
A0A0A3A148/36-57'
A0A0A3A148/69-91'
A0A0A3A148/132-153'
A0A0A3A148/160-183'
A0A0A3A148/195-217'
A0A0A3A148/229-249'
A0A0A3A148/261-281'
A0A0A3A148/293-312'
A0A0A3A148/318-336'
A0A0A3A148/348-367'
A0A0A3A148/379-402'
A0A0A2ZRL7/36-57'
A0A0A2ZRL7/69-91'
A0A0A2ZRL7/132-153'
A0A0A2ZRL7/160-183'
A0A0A2ZRL7/195-217'
A0A0A2ZRL7/229-249'
A0A0A2ZRL7/261-281'
A0A0A2ZRL7/293-312'
A0A0A2ZRL7/318-336'
A0A0A2ZRL7/348-367'
A0A0A2ZRL7/379-402'
F4H924/36-57'
F4H924/69-91'
F4H924/132-153'
F4H924/160-183'
F4H924/195-217'
F4H924/229-249'
F4H924/261-281'
F4H924/293-312'
F4H924/318-336'
F4H924/348-367'
F4H924/379-402'
A0A0A2Y4H8/36-57'
A0A0A2Y4H8/69-91'
A0A0A2Y4H8/132-153'
A0A0A2Y4H8/160-183'
A0A0A2Y4H8/195-217'
A0A0A2Y4H8/229-249'
A0A0A2Y4H8/261-281'
A0A0A2Y4H8/293-312'
A0A0A2Y4H8/318-336'
A0A0A2Y4H8/348-367'
A0A0A2Y4H8/379-402'
U1H1F7/36-57'
U1H1F7/69-91'
U1H1F7/132-153'
U1H1F7/160-183'
U1H1F7/195-217'
U1H1F7/229-249'
U1H1F7/261-281'
U1H1F7/293-312'
U1H1F7/318-336'
U1H1F7/348-367'
U1H1F7/379-402'
A0A0A3AIB6/36-57'
A0A0A3AIB6/69-91'
A0A0A3AIB6/132-153'
A0A0A3AIB6/160-183'
A0A0A3AIB6/195-217'
A0A0A3AIB6/229-249'
A0A0A3AIB6/261-281'
A0A0A3AIB6/293-312'
A0A0A3AIB6/318-336'
A0A0A3AIB6/348-367'
A0A0A3AIB6/379-402'
D9SI59/75-95'
D9SI59/107-125'
D9SI59/172-194'
D9SI59/201-224'
D9SI59/254-275'
D9SI59/287-308'
D9SI59/320-339'
D9SI59/351-368'
D9SI59/374-392'
D9SI59/404-425'
D9SI59/452-474'
D9SI36/12-35'
D9SI36/47-69'
D9SI36/89-108'
D9SI36/120-137'
D9SI36/157-180'
D9SI36/201-221'
D9SI36/227-249'
D9SI36/256-274'
D9SI36/280-298'
D9SI36/310-329'
D9SI36/341-363'
C1A872/35-56'
C1A872/68-90'
C1A872/124-146'
C1A872/153-174'
C1A872/186-209'
C1A872/221-241'
C1A872/253-273'
C1A872/285-303'
C1A872/309-328'
C1A872/340-359'
C1A872/379-401'
A0A3D4V557/35-56'
A0A3D4V557/68-90'
A0A3D4V557/124-146'
A0A3D4V557/153-174'
A0A3D4V557/186-209'
A0A3D4V557/221-241'
A0A3D4V557/253-273'
A0A3D4V557/285-303'
A0A3D4V557/309-328'
A0A3D4V557/340-359'
A0A3D4V557/379-401'
A0A1G9P6Q0/34-58'
A0A1G9P6Q0/78-98'
A0A1G9P6Q0/131-149'
A0A1G9P6Q0/156-176'
A0A1G9P6Q0/196-214'
A0A1G9P6Q0/235-258'
A0A1G9P6Q0/270-293'
A0A1G9P6Q0/300-316'
A0A1G9P6Q0/322-343'
A0A1G9P6Q0/350-371'
A0A1G9P6Q0/377-401'
A0A0C2HHF2/34-58'
A0A0C2HHF2/78-98'
A0A0C2HHF2/131-149'
A0A0C2HHF2/156-176'
A0A0C2HHF2/196-214'
A0A0C2HHF2/235-258'
A0A0C2HHF2/270-293'
A0A0C2HHF2/300-316'
A0A0C2HHF2/322-343'
A0A0C2HHF2/350-371'
A0A0C2HHF2/377-401'
A0A0B5FNH4/33-57'
A0A0B5FNH4/77-97'
A0A0B5FNH4/130-148'
A0A0B5FNH4/155-175'
A0A0B5FNH4/195-213'
A0A0B5FNH4/234-257'
A0A0B5FNH4/269-292'
A0A0B5FNH4/299-316'
A0A0B5FNH4/322-342'
A0A0B5FNH4/349-370'
A0A0B5FNH4/376-401'
A0A0D8BQX6/6-27'
A0A0D8BQX6/48-71'
A0A0D8BQX6/99-118'
A0A0D8BQX6/125-147'
A0A0D8BQX6/159-181'
A0A0D8BQX6/202-218'
A0A0D8BQX6/230-252'
A0A0D8BQX6/264-282'
A0A0D8BQX6/288-306'
A0A0D8BQX6/318-340'
A0A0D8BQX6/360-384'
U2WTW8/15-35'
U2WTW8/56-79'
U2WTW8/107-126'
U2WTW8/133-155'
U2WTW8/167-189'
U2WTW8/210-226'
U2WTW8/238-260'
U2WTW8/272-290'
U2WTW8/296-314'
U2WTW8/326-348'
U2WTW8/368-393'
Q5KZZ9/15-35'
Q5KZZ9/56-79'
Q5KZZ9/107-126'
Q5KZZ9/133-155'
Q5KZZ9/167-189'
Q5KZZ9/210-226'
Q5KZZ9/238-260'
Q5KZZ9/272-290'
Q5KZZ9/296-314'
Q5KZZ9/326-348'
Q5KZZ9/368-393'
A0A4D7Q9P4/12-32'
A0A4D7Q9P4/53-76'
A0A4D7Q9P4/104-123'
A0A4D7Q9P4/130-152'
A0A4D7Q9P4/164-186'
A0A4D7Q9P4/207-223'
A0A4D7Q9P4/235-257'
A0A4D7Q9P4/269-287'
A0A4D7Q9P4/293-311'
A0A4D7Q9P4/323-345'
A0A4D7Q9P4/365-390'
A0A1I5GN22/6-27'
A0A1I5GN22/39-57'
A0A1I5GN22/99-124'
A0A1I5GN22/136-158'
A0A1I5GN22/178-200'
A0A1I5GN22/212-232'
A0A1I5GN22/244-264'
A0A1I5GN22/276-293'
A0A1I5GN22/299-318'
A0A1I5GN22/330-353'
A0A1I5GN22/373-395'
A0A1M7UEG2/6-27'
A0A1M7UEG2/39-57'
A0A1M7UEG2/99-124'
A0A1M7UEG2/136-158'
A0A1M7UEG2/178-200'
A0A1M7UEG2/212-232'
A0A1M7UEG2/244-265'
A0A1M7UEG2/272-292'
A0A1M7UEG2/298-318'
A0A1M7UEG2/330-349'
A0A1M7UEG2/369-394'
D2SE15/6-27'
D2SE15/39-57'
D2SE15/99-124'
D2SE15/136-158'
D2SE15/178-200'
D2SE15/212-232'
D2SE15/244-265'
D2SE15/272-292'
D2SE15/298-318'
D2SE15/330-349'
D2SE15/369-395'
A0A410JZR4/28-50'
A0A410JZR4/62-85'
A0A410JZR4/117-138'
A0A410JZR4/145-166'
A0A410JZR4/178-201'
A0A410JZR4/213-234'
A0A410JZR4/246-265'
A0A410JZR4/277-294'
A0A410JZR4/300-317'
A0A410JZR4/329-352'
A0A410JZR4/372-390'
A0A410K1J5/43-62'
A0A410K1J5/83-107'
A0A410K1J5/127-147'
A0A410K1J5/154-175'
A0A410K1J5/187-214'
A0A410K1J5/235-252'
A0A410K1J5/264-290'
A0A410K1J5/297-314'
A0A410K1J5/320-339'
A0A410K1J5/351-368'
A0A410K1J5/380-403'
A0A1H9M798/51-72'
A0A1H9M798/84-106'
A0A1H9M798/147-168'
A0A1H9M798/175-196'
A0A1H9M798/208-232'
A0A1H9M798/244-264'
A0A1H9M798/276-295'
A0A1H9M798/307-325'
A0A1H9M798/331-351'
A0A1H9M798/363-382'
A0A1H9M798/394-417'
A0A1H9RTW8/89-110'
A0A1H9RTW8/122-140'
A0A1H9RTW8/179-201'
A0A1H9RTW8/208-230'
A0A1H9RTW8/242-264'
A0A1H9RTW8/276-296'
A0A1H9RTW8/308-328'
A0A1H9RTW8/340-360'
A0A1H9RTW8/366-383'
A0A1H9RTW8/395-415'
A0A1H9RTW8/435-457'
A0A1B9JHS5/33-53'
A0A1B9JHS5/65-85'
A0A1B9JHS5/119-141'
A0A1B9JHS5/148-170'
A0A1B9JHS5/182-204'
A0A1B9JHS5/216-236'
A0A1B9JHS5/248-268'
A0A1B9JHS5/280-299'
A0A1B9JHS5/305-323'
A0A1B9JHS5/335-354'
A0A1B9JHS5/374-395'
A0A1B9JZS5/35-56'
A0A1B9JZS5/68-87'
A0A1B9JZS5/118-140'
A0A1B9JZS5/147-169'
A0A1B9JZS5/181-203'
A0A1B9JZS5/215-234'
A0A1B9JZS5/246-267'
A0A1B9JZS5/279-298'
A0A1B9JZS5/304-322'
A0A1B9JZS5/334-352'
A0A1B9JZS5/372-394'
A0A1B9LFW3/29-52'
A0A1B9LFW3/64-84'
A0A1B9LFW3/118-140'
A0A1B9LFW3/147-169'
A0A1B9LFW3/181-203'
A0A1B9LFW3/215-234'
A0A1B9LFW3/246-267'
A0A1B9LFW3/279-298'
A0A1B9LFW3/304-322'
A0A1B9LFW3/334-353'
A0A1B9LFW3/373-394'
A0A1B9NQ91/32-52'
A0A1B9NQ91/64-84'
A0A1B9NQ91/118-140'
A0A1B9NQ91/147-169'
A0A1B9NQ91/181-203'
A0A1B9NQ91/215-234'
A0A1B9NQ91/246-267'
A0A1B9NQ91/279-298'
A0A1B9NQ91/304-322'
A0A1B9NQ91/334-352'
A0A1B9NQ91/372-394'

A0A1B9K8L2/35-56'
A0A1B9K8L2/68-87'
A0A1B9K8L2/118-140'
A0A1B9K8L2/147-169'
A0A1B9K8L2/181-203'
A0A1B9K8L2/215-234'
A0A1B9K8L2/246-267'
A0A1B9K8L2/279-298'
A0A1B9K8L2/304-322'
A0A1B9K8L2/334-352'
A0A1B9K8L2/372-394'
A0A2V4EA49/29-52'
A0A2V4EA49/64-84'
A0A2V4EA49/119-140'
A0A2V4EA49/147-169'
A0A2V4EA49/181-203'
A0A2V4EA49/215-234'
A0A2V4EA49/246-267'
A0A2V4EA49/279-298'
A0A2V4EA49/304-322'
A0A2V4EA49/334-353'
A0A2V4EA49/373-394'
A0A1B9M5B8/29-52'
A0A1B9M5B8/64-84'
A0A1B9M5B8/118-140'
A0A1B9M5B8/147-169'
A0A1B9M5B8/181-203'
A0A1B9M5B8/215-234'
A0A1B9M5B8/246-267'
A0A1B9M5B8/279-298'
A0A1B9M5B8/304-322'
A0A1B9M5B8/334-353'
A0A1B9M5B8/373-394'
A0A1B9MYL7/36-56'
A0A1B9MYL7/63-83'
A0A1B9MYL7/119-141'
A0A1B9MYL7/148-170'
A0A1B9MYL7/182-203'
A0A1B9MYL7/215-235'
A0A1B9MYL7/247-268'
A0A1B9MYL7/280-299'
A0A1B9MYL7/305-323'
A0A1B9MYL7/335-353'
A0A1B9MYL7/373-395'
A0A1B9N3H7/31-52'
A0A1B9N3H7/64-84'
A0A1B9N3H7/118-140'
A0A1B9N3H7/147-169'
A0A1B9N3H7/181-203'
A0A1B9N3H7/215-234'
A0A1B9N3H7/246-267'
A0A1B9N3H7/279-298'
A0A1B9N3H7/304-322'
A0A1B9N3H7/334-353'
A0A1B9N3H7/373-394'
A0A1C0A1D9/29-52'
A0A1C0A1D9/64-84'
A0A1C0A1D9/118-140'
A0A1C0A1D9/147-169'
A0A1C0A1D9/181-203'
A0A1C0A1D9/215-234'
A0A1C0A1D9/246-267'
A0A1C0A1D9/279-298'
A0A1C0A1D9/304-322'
A0A1C0A1D9/334-352'
A0A1C0A1D9/372-394'
A0A1B9JPL5/29-52'
A0A1B9JPL5/64-84'
A0A1B9JPL5/118-140'
A0A1B9JPL5/147-169'
A0A1B9JPL5/181-203'
A0A1B9JPL5/215-234'
A0A1B9JPL5/246-267'
A0A1B9JPL5/279-298'
A0A1B9JPL5/304-322'
A0A1B9JPL5/334-354'
A0A1B9JPL5/374-394'
A0A1B9KID3/31-52'
A0A1B9KID3/64-84'
A0A1B9KID3/118-140'
A0A1B9KID3/147-169'
A0A1B9KID3/181-203'
A0A1B9KID3/215-234'
A0A1B9KID3/246-267'
A0A1B9KID3/279-298'
A0A1B9KID3/304-322'
A0A1B9KID3/334-352'
A0A1B9KID3/372-394'
A0A1B9M1A9/32-52'
A0A1B9M1A9/64-84'
A0A1B9M1A9/118-140'
A0A1B9M1A9/147-169'
A0A1B9M1A9/181-203'
A0A1B9M1A9/215-234'
A0A1B9M1A9/246-267'
A0A1B9M1A9/279-298'
A0A1B9M1A9/304-322'
A0A1B9M1A9/334-352'
A0A1B9M1A9/372-394'
A0A1B9MBX6/29-52'
A0A1B9MBX6/64-84'
A0A1B9MBX6/118-140'
A0A1B9MBX6/147-169'
A0A1B9MBX6/181-203'
A0A1B9MBX6/215-234'
A0A1B9MBX6/246-267'
A0A1B9MBX6/279-298'
A0A1B9MBX6/304-322'
A0A1B9MBX6/334-353'
A0A1B9MBX6/373-394'
A0A1B9MZ78/29-52'
A0A1B9MZ78/64-84'
A0A1B9MZ78/118-140'
A0A1B9MZ78/147-169'
A0A1B9MZ78/181-203'
A0A1B9MZ78/215-234'
A0A1B9MZ78/246-267'
A0A1B9MZ78/279-298'
A0A1B9MZ78/304-322'
A0A1B9MZ78/334-353'
A0A1B9MZ78/373-394'
A0A242NIL1/29-53'
A0A242NIL1/65-85'
A0A242NIL1/119-141'
A0A242NIL1/148-170'
A0A242NIL1/182-204'
A0A242NIL1/216-236'
A0A242NIL1/248-268'
A0A242NIL1/280-299'
A0A242NIL1/305-323'
A0A242NIL1/335-354'
A0A242NIL1/374-395'
A0A657K391/32-52'
A0A657K391/64-84'
A0A657K391/118-140'
A0A657K391/147-169'
A0A657K391/181-203'
A0A657K391/215-234'
A0A657K391/246-267'
A0A657K391/279-298'
A0A657K391/304-322'
A0A657K391/334-352'
A0A657K391/372-394'
A0A556RTU3/29-52'
A0A556RTU3/64-84'
A0A556RTU3/119-140'
A0A556RTU3/147-169'
A0A556RTU3/181-203'
A0A556RTU3/215-234'
A0A556RTU3/246-267'
A0A556RTU3/279-298'
A0A556RTU3/304-322'
A0A556RTU3/334-353'
A0A556RTU3/373-394'
A0A556SRH6/33-53'
A0A556SRH6/65-85'
A0A556SRH6/119-141'
A0A556SRH6/148-170'
A0A556SRH6/182-204'
A0A556SRH6/216-235'
A0A556SRH6/247-268'
A0A556SRH6/280-299'
A0A556SRH6/305-323'
A0A556SRH6/335-354'
A0A556SRH6/374-395'
A0A1B9NRG7/29-52'
A0A1B9NRG7/64-84'
A0A1B9NRG7/118-140'
A0A1B9NRG7/147-169'
A0A1B9NRG7/181-203'
A0A1B9NRG7/215-234'
A0A1B9NRG7/246-267'
A0A1B9NRG7/279-298'
A0A1B9NRG7/304-322'
A0A1B9NRG7/334-353'
A0A1B9NRG7/373-394'
G4QHD2/6-23'
G4QHD2/44-64'
G4QHD2/84-106'
G4QHD2/113-134'
G4QHD2/154-176'
G4QHD2/188-211'
G4QHD2/226-249'
G4QHD2/256-276'
G4QHD2/282-299'
G4QHD2/306-328'
G4QHD2/343-365'
Q7NCB8/36-59'
Q7NCB8/71-93'
Q7NCB8/127-149'
Q7NCB8/156-177'
Q7NCB8/197-224'
Q7NCB8/236-257'
Q7NCB8/263-288'
Q7NCB8/300-318'
Q7NCB8/324-343'
Q7NCB8/355-374'
Q7NCB8/394-419'
Q8GQS1/52-72'
Q8GQS1/84-106'
Q8GQS1/155-176'
Q8GQS1/183-204'
Q8GQS1/210-240'
Q8GQS1/252-272'
Q8GQS1/284-304'
Q8GQS1/316-335'
Q8GQS1/341-359'
Q8GQS1/371-394'
Q8GQS1/414-436'
A0A7W4NFW5/47-69'
A0A7W4NFW5/76-97'
A0A7W4NFW5/151-172'
A0A7W4NFW5/179-200'
A0A7W4NFW5/206-236'
A0A7W4NFW5/248-268'
A0A7W4NFW5/280-299'
A0A7W4NFW5/311-331'
A0A7W4NFW5/337-355'
A0A7W4NFW5/367-387'
A0A7W4NFW5/407-429'
A0A7W4FEM1/52-72'
A0A7W4FEM1/84-106'
A0A7W4FEM1/155-176'
A0A7W4FEM1/183-204'
A0A7W4FEM1/210-240'
A0A7W4FEM1/252-272'
A0A7W4FEM1/284-304'
A0A7W4FEM1/316-335'
A0A7W4FEM1/341-359'
A0A7W4FEM1/371-394'
A0A7W4FEM1/414-436'
B5ZDQ6/52-72'
B5ZDQ6/84-106'
B5ZDQ6/155-176'
B5ZDQ6/183-204'
B5ZDQ6/210-240'
B5ZDQ6/252-272'
B5ZDQ6/284-304'
B5ZDQ6/316-335'
B5ZDQ6/341-359'
B5ZDQ6/371-394'
B5ZDQ6/414-436'
A9HMD6/52-72'
A9HMD6/84-106'
A9HMD6/155-176'
A9HMD6/183-204'
A9HMD6/210-240'
A9HMD6/252-272'
A9HMD6/284-304'
A9HMD6/316-335'
A9HMD6/341-359'
A9HMD6/371-394'
A9HMD6/414-436'
A9H9C4/47-69'
A9H9C4/76-97'
A9H9C4/151-172'
A9H9C4/179-200'
A9H9C4/206-236'
A9H9C4/248-268'
A9H9C4/280-299'
A9H9C4/311-331'
A9H9C4/337-355'
A9H9C4/367-387'
A9H9C4/407-429'
A0A149RYW7/42-62'
A0A149RYW7/69-90'
A0A149RYW7/144-165'
A0A149RYW7/172-193'
A0A149RYW7/213-230'
A0A149RYW7/242-261'
A0A149RYW7/273-293'
A0A149RYW7/305-324'
A0A149RYW7/330-348'
A0A149RYW7/360-380'
A0A149RYW7/400-422'
A0A149UA34/37-57'
A0A149UA34/64-85'
A0A149UA34/139-160'
A0A149UA34/167-188'
A0A149UA34/208-225'
A0A149UA34/237-256'
A0A149UA34/268-288'
A0A149UA34/300-319'
A0A149UA34/325-343'
A0A149UA34/355-375'
A0A149UA34/395-417'
A0A4R4A245/42-62'
A0A4R4A245/69-90'
A0A4R4A245/144-165'
A0A4R4A245/172-193'
A0A4R4A245/213-230'
A0A4R4A245/242-261'
A0A4R4A245/273-293'
A0A4R4A245/305-324'
A0A4R4A245/330-348'
A0A4R4A245/360-380'
A0A4R4A245/400-422'
Q5FSX6/42-62'
Q5FSX6/69-90'
Q5FSX6/144-165'
Q5FSX6/172-193'
Q5FSX6/213-230'
Q5FSX6/242-261'
Q5FSX6/273-293'
Q5FSX6/305-324'
Q5FSX6/330-348'
Q5FSX6/360-380'
Q5FSX6/400-422'
A0A829X098/42-62'
A0A829X098/69-90'
A0A829X098/144-165'
A0A829X098/172-193'
A0A829X098/213-230'
A0A829X098/242-261'
A0A829X098/273-293'
A0A829X098/305-324'
A0A829X098/330-348'
A0A829X098/360-380'
A0A829X098/400-422'
A0A067Z3S3/42-62'
A0A067Z3S3/69-90'
A0A067Z3S3/144-165'
A0A067Z3S3/172-193'
A0A067Z3S3/213-230'
A0A067Z3S3/242-261'
A0A067Z3S3/273-293'
A0A067Z3S3/305-324'
A0A067Z3S3/330-348'
A0A067Z3S3/360-380'
A0A067Z3S3/400-422'
A0A149SNB1/37-57'
A0A149SNB1/64-85'
A0A149SNB1/139-160'
A0A149SNB1/167-188'
A0A149SNB1/200-224'
A0A149SNB1/236-256'
A0A149SNB1/268-288'
A0A149SNB1/300-319'
A0A149SNB1/325-343'
A0A149SNB1/355-375'
A0A149SNB1/395-417'
A0A149QSR6/42-62'
A0A149QSR6/69-90'
A0A149QSR6/144-165'
A0A149QSR6/172-193'
A0A149QSR6/213-230'
A0A149QSR6/242-261'
A0A149QSR6/273-293'
A0A149QSR6/305-324'
A0A149QSR6/330-348'
A0A149QSR6/360-380'
A0A149QSR6/400-422'
A0A149S1Z1/37-57'
A0A149S1Z1/64-85'
A0A149S1Z1/139-160'
A0A149S1Z1/167-188'
A0A149S1Z1/200-224'
A0A149S1Z1/236-256'
A0A149S1Z1/268-288'
A0A149S1Z1/300-319'
A0A149S1Z1/325-343'
A0A149S1Z1/355-375'
A0A149S1Z1/395-417'
A0A149QAW7/55-75'
A0A149QAW7/82-103'
A0A149QAW7/157-178'
A0A149QAW7/185-206'
A0A149QAW7/226-242'
A0A149QAW7/254-274'
A0A149QAW7/286-307'
A0A149QAW7/316-337'
A0A149QAW7/343-361'
A0A149QAW7/373-393'
A0A149QAW7/413-435'
A0A149U2G9/54-74'
A0A149U2G9/81-102'
A0A149U2G9/156-177'
A0A149U2G9/184-205'
A0A149U2G9/225-241'
A0A149U2G9/253-273'
A0A149U2G9/285-305'
A0A149U2G9/317-336'
A0A149U2G9/342-360'
A0A149U2G9/372-392'
A0A149U2G9/412-434'
A0A149TSA9/51-73'
A0A149TSA9/85-107'
A0A149TSA9/156-177'
A0A149TSA9/184-205'
A0A149TSA9/225-241'
A0A149TSA9/253-273'
A0A149TSA9/285-305'
A0A149TSA9/317-336'
A0A149TSA9/342-360'
A0A149TSA9/372-392'
A0A149TSA9/412-434'
I1KKI2/24-46'
I1KKI2/58-80'
I1KKI2/133-153'
I1KKI2/165-186'
I1KKI2/198-216'
I1KKI2/228-248'
I1KKI2/254-278'
I1KKI2/290-309'
I1KKI2/315-335'
I1KKI2/356-381'
I1KKI2/401-426'
K7K8C3/25-46'
K7K8C3/53-75'
K7K8C3/116-135'
K7K8C3/142-165'
K7K8C3/177-198'
K7K8C3/210-228'
K7K8C3/248-269'
K7K8C3/281-300'
K7K8C3/306-324'
K7K8C3/336-358'
K7K8C3/395-423'
K7K3F5/24-46'
K7K3F5/58-80'
K7K3F5/134-153'
K7K3F5/165-186'
K7K3F5/198-216'
K7K3F5/228-248'
K7K3F5/260-279'
K7K3F5/291-309'
K7K3F5/315-336'
K7K3F5/348-370'
K7K3F5/401-426'
I1L774/26-48'
I1L774/60-79'
I1L774/118-137'
I1L774/144-165'
I1L774/185-204'
I1L774/216-233'
I1L774/245-269'
I1L774/276-294'
I1L774/300-321'
I1L774/333-355'
I1L774/393-418'
I1N306/24-46'
I1N306/58-80'
I1N306/133-153'
I1N306/165-186'
I1N306/198-216'
I1N306/228-248'
I1N306/254-278'
I1N306/290-309'
I1N306/315-335'
I1N306/356-381'
I1N306/401-426'

I1K536/31-53'
I1K536/65-84'
I1K536/142-162'
I1K536/174-197'
I1K536/203-224'
I1K536/236-256'
I1K536/268-287'
I1K536/299-317'
I1K536/323-344'
I1K536/356-378'
I1K536/409-434'
A0A7X5BZ76/38-57'
A0A7X5BZ76/69-92'
A0A7X5BZ76/129-148'
A0A7X5BZ76/155-173'
A0A7X5BZ76/193-213'
A0A7X5BZ76/234-251'
A0A7X5BZ76/263-288'
A0A7X5BZ76/295-312'
A0A7X5BZ76/318-336'
A0A7X5BZ76/348-373'
A0A7X5BZ76/393-415'
A0A7X4YNT4/12-37'
A0A7X4YNT4/49-69'
A0A7X4YNT4/100-120'
A0A7X4YNT4/127-148'
A0A7X4YNT4/160-183'
A0A7X4YNT4/204-221'
A0A7X4YNT4/233-255'
A0A7X4YNT4/267-287'
A0A7X4YNT4/293-309'
A0A7X4YNT4/321-339'
A0A7X4YNT4/359-388'
A0A8H6MPB9/38-59'
A0A8H6MPB9/71-88'
A0A8H6MPB9/127-146'
A0A8H6MPB9/158-180'
A0A8H6MPB9/192-214'
A0A8H6MPB9/226-246'
A0A8H6MPB9/258-279'
A0A8H6MPB9/286-304'
A0A8H6MPB9/310-329'
A0A8H6MPB9/350-370'
A0A8H6MPB9/390-411'
A0A8H6NAG3/38-59'
A0A8H6NAG3/71-88'
A0A8H6NAG3/127-146'
A0A8H6NAG3/158-180'
A0A8H6NAG3/192-214'
A0A8H6NAG3/226-246'
A0A8H6NAG3/258-279'
A0A8H6NAG3/286-304'
A0A8H6NAG3/310-329'
A0A8H6NAG3/350-370'
A0A8H6NAG3/390-411'
A0A8H6K7L7/38-59'
A0A8H6K7L7/71-88'
A0A8H6K7L7/127-146'
A0A8H6K7L7/158-180'
A0A8H6K7L7/192-214'
A0A8H6K7L7/226-246'
A0A8H6K7L7/258-279'
A0A8H6K7L7/286-304'
A0A8H6K7L7/310-329'
A0A8H6K7L7/350-370'
A0A8H6K7L7/390-411'
D0L8H3/12-32'
D0L8H3/44-66'
D0L8H3/101-120'
D0L8H3/132-153'
D0L8H3/173-195'
D0L8H3/207-224'
D0L8H3/230-256'
D0L8H3/268-285'
D0L8H3/291-310'
D0L8H3/322-342'
D0L8H3/362-383'
D0LAL7/20-42'
D0LAL7/49-69'
D0LAL7/123-144'
D0LAL7/156-176'
D0LAL7/211-233'
D0LAL7/245-265'
D0LAL7/277-298'
D0LAL7/305-322'
D0LAL7/328-351'
D0LAL7/363-382'
D0LAL7/397-421'
A0A369M386/6-29'
A0A369M386/41-63'
A0A369M386/107-126'
A0A369M386/133-155'
A0A369M386/175-193'
A0A369M386/205-224'
A0A369M386/236-257'
A0A369M386/266-285'
A0A369M386/291-311'
A0A369M386/323-343'
A0A369M386/363-388'
D6E7B3/6-29'
D6E7B3/41-63'
D6E7B3/107-126'
D6E7B3/133-155'
D6E7B3/175-193'
D6E7B3/205-224'
D6E7B3/236-257'
D6E7B3/266-285'
D6E7B3/291-311'
D6E7B3/323-343'
D6E7B3/363-388'
A0A1L3RLF1 has 12 helices, if 12, will use last 11, if other won't include
A0A1L3RLF1/67-91'
A0A1L3RLF1/103-123'
A0A1L3RLF1/162-183'
A0A1L3RLF1/190-211'
A0A1L3RLF1/231-250'
A0A1L3RLF1/262-279'
A0A1L3RLF1/291-315'
A0A1L3RLF1/322-342'
A0A1L3RLF1/348-366'
A0A1L3RLF1/378-398'
A0A1L3RLF1/418-440'
A0A1L3REC0 has 12 helices, if 12, will use last 11, if other won't include
A0A1L3REC0/92-116'
A0A1L3REC0/128-148'
A0A1L3REC0/187-208'
A0A1L3REC0/215-236'
A0A1L3REC0/256-275'
A0A1L3REC0/287-304'
A0A1L3REC0/316-340'
A0A1L3REC0/347-367'
A0A1L3REC0/373-391'
A0A1L3REC0/403-423'
A0A1L3REC0/443-465'
W6I7E0 has 12 helices, if 12, will use last 11, if other won't include
W6I7E0/67-91'
W6I7E0/103-123'
W6I7E0/162-183'
W6I7E0/190-211'
W6I7E0/231-250'
W6I7E0/262-279'
W6I7E0/291-315'
W6I7E0/322-342'
W6I7E0/348-366'
W6I7E0/378-398'
W6I7E0/418-440'
Q0BQ69 has 12 helices, if 12, will use last 11, if other won't include
Q0BQ69/67-91'
Q0BQ69/103-123'
Q0BQ69/162-183'
Q0BQ69/190-211'
Q0BQ69/231-250'
Q0BQ69/262-279'
Q0BQ69/291-311'
Q0BQ69/323-342'
Q0BQ69/348-366'
Q0BQ69/378-398'
Q0BQ69/418-440'
L1IYP4/97-121'
L1IYP4/133-152'
L1IYP4/188-208'
L1IYP4/215-236'
L1IYP4/256-275'
L1IYP4/287-306'
L1IYP4/326-345'
L1IYP4/357-375'
L1IYP4/381-398'
L1IYP4/410-432'
L1IYP4/452-475'
L1IYW7 has 12 helices, if 12, will use last 11, if other won't include
L1IYW7/106-128'
L1IYW7/140-161'
L1IYW7/198-218'
L1IYW7/225-245'
L1IYW7/265-283'
L1IYW7/295-314'
L1IYW7/326-345'
L1IYW7/357-375'
L1IYW7/381-398'
L1IYW7/410-432'
L1IYW7/452-475'
A0A7S4NPK3/102-126'
A0A7S4NPK3/138-157'
A0A7S4NPK3/193-213'
A0A7S4NPK3/220-241'
A0A7S4NPK3/261-280'
A0A7S4NPK3/292-311'
A0A7S4NPK3/331-350'
A0A7S4NPK3/362-380'
A0A7S4NPK3/386-403'
A0A7S4NPK3/415-437'
A0A7S4NPK3/457-480'
L1IHZ8/6-29'
L1IHZ8/41-62'
L1IHZ8/95-116'
L1IHZ8/123-142'
L1IHZ8/162-180'
L1IHZ8/192-213'
L1IHZ8/225-245'
L1IHZ8/257-276'
L1IHZ8/282-299'
L1IHZ8/311-332'
L1IHZ8/352-370'
L1J6I4/66-90'
L1J6I4/111-133'
L1J6I4/153-174'
L1J6I4/181-201'
L1J6I4/221-238'
L1J6I4/250-271'
L1J6I4/283-302'
L1J6I4/314-331'
L1J6I4/337-355'
L1J6I4/367-388'
L1J6I4/408-431'
L1JEX0/12-32'
L1JEX0/44-66'
L1JEX0/97-115'
L1JEX0/127-155'
L1JEX0/175-199'
L1JEX0/220-237'
L1JEX0/257-279'
L1JEX0/286-306'
L1JEX0/312-329'
L1JEX0/341-364'
L1JEX0/384-407'
L1INN6/54-78'
L1INN6/90-109'
L1INN6/150-168'
L1INN6/175-196'
L1INN6/230-251'
L1INN6/272-289'
L1INN6/309-327'
L1INN6/339-357'
L1INN6/363-383'
L1INN6/390-409'
L1INN6/438-458'
L1IUV5/12-35'
L1IUV5/47-68'
L1IUV5/99-120'
L1IUV5/127-147'
L1IUV5/167-184'
L1IUV5/196-217'
L1IUV5/229-248'
L1IUV5/260-280'
L1IUV5/286-303'
L1IUV5/315-340'
L1IUV5/352-374'
A0A212AV03/49-71'
A0A212AV03/83-103'
A0A212AV03/144-162'
A0A212AV03/174-194'
A0A212AV03/214-233'
A0A212AV03/245-262'
A0A212AV03/274-294'
A0A212AV03/306-323'
A0A212AV03/329-349'
A0A212AV03/361-380'
A0A212AV03/400-421'
A0A1C6Z081/39-60'
A0A1C6Z081/72-99'
A0A1C6Z081/119-140'
A0A1C6Z081/147-165'
A0A1C6Z081/185-207'
A0A1C6Z081/219-238'
A0A1C6Z081/250-270'
A0A1C6Z081/282-301'
A0A1C6Z081/307-326'
A0A1C6Z081/338-358'
A0A1C6Z081/378-398'
A0A377PBY1/39-60'
A0A377PBY1/72-99'
A0A377PBY1/119-140'
A0A377PBY1/147-165'
A0A377PBY1/185-207'
A0A377PBY1/219-238'
A0A377PBY1/250-270'
A0A377PBY1/282-301'
A0A377PBY1/307-326'
A0A377PBY1/338-358'
A0A377PBY1/378-398'
A0A377PLP5/39-60'
A0A377PLP5/72-99'
A0A377PLP5/119-140'
A0A377PLP5/147-165'
A0A377PLP5/185-207'
A0A377PLP5/219-238'
A0A377PLP5/250-270'
A0A377PLP5/282-301'
A0A377PLP5/307-326'
A0A377PLP5/338-356'
A0A377PLP5/376-398'
A0A4Q9EZY8/38-59'
A0A4Q9EZY8/71-98'
A0A4Q9EZY8/118-139'
A0A4Q9EZY8/146-164'
A0A4Q9EZY8/184-206'
A0A4Q9EZY8/218-237'
A0A4Q9EZY8/249-269'
A0A4Q9EZY8/281-300'
A0A4Q9EZY8/306-325'
A0A4Q9EZY8/337-355'
A0A4Q9EZY8/375-397'
A0A097R891/38-59'
A0A097R891/71-98'
A0A097R891/118-139'
A0A097R891/146-164'
A0A097R891/184-206'
A0A097R891/218-237'
A0A097R891/249-269'
A0A097R891/281-300'
A0A097R891/306-325'
A0A097R891/337-357'
A0A097R891/377-397'
G9Y5B0/38-59'
G9Y5B0/71-98'
G9Y5B0/118-139'
G9Y5B0/146-164'
G9Y5B0/184-206'
G9Y5B0/218-237'
G9Y5B0/249-269'
G9Y5B0/281-300'
G9Y5B0/306-325'
G9Y5B0/337-355'
G9Y5B0/375-397'
A0A2A2M8K7/38-59'
A0A2A2M8K7/71-98'
A0A2A2M8K7/118-139'
A0A2A2M8K7/146-164'
A0A2A2M8K7/184-206'
A0A2A2M8K7/218-237'
A0A2A2M8K7/249-269'
A0A2A2M8K7/281-300'
A0A2A2M8K7/306-325'
A0A2A2M8K7/337-355'
A0A2A2M8K7/375-397'
A0A2A2MCP3/17-40'
A0A2A2MCP3/61-81'
A0A2A2MCP3/108-131'
A0A2A2MCP3/138-159'
A0A2A2MCP3/171-194'
A0A2A2MCP3/206-224'
A0A2A2MCP3/236-256'
A0A2A2MCP3/268-286'
A0A2A2MCP3/292-310'
A0A2A2MCP3/322-344'
A0A2A2MCP3/364-385'
Q2S8H9/15-34'
Q2S8H9/54-78'
Q2S8H9/114-133'
Q2S8H9/138-155'
Q2S8H9/180-202'
Q2S8H9/214-236'
Q2S8H9/256-282'
Q2S8H9/289-305'
Q2S8H9/311-331'
Q2S8H9/340-359'
Q2S8H9/365-390'
Q2SIR0/18-37'
Q2SIR0/58-76'
Q2SIR0/96-115'
Q2SIR0/120-138'
Q2SIR0/164-185'
Q2SIR0/197-221'
Q2SIR0/233-255'
Q2SIR0/262-280'
Q2SIR0/286-303'
Q2SIR0/315-336'
Q2SIR0/348-373'
E7QV43/12-33'
E7QV43/54-76'
E7QV43/96-118'
E7QV43/125-146'
E7QV43/176-197'
E7QV43/218-235'
E7QV43/261-283'
E7QV43/290-307'
E7QV43/313-330'
E7QV43/342-364'
E7QV43/370-395'
D8J4C6/14-34'
D8J4C6/55-82'
D8J4C6/102-121'
D8J4C6/128-150'
D8J4C6/162-183'
D8J4C6/204-221'
D8J4C6/248-270'
D8J4C6/277-293'
D8J4C6/299-317'
D8J4C6/329-353'
D8J4C6/359-384'
D0LTW3/12-34'
D0LTW3/46-65'
D0LTW3/93-116'
D0LTW3/123-144'
D0LTW3/156-179'
D0LTW3/200-217'
D0LTW3/229-253'
D0LTW3/260-277'
D0LTW3/283-304'
D0LTW3/316-333'
D0LTW3/353-373'
A0A3C1KS02/15-39'
A0A3C1KS02/51-70'
A0A3C1KS02/115-134'
A0A3C1KS02/139-156'
A0A3C1KS02/178-199'
A0A3C1KS02/220-237'
A0A3C1KS02/257-276'
A0A3C1KS02/283-301'
A0A3C1KS02/307-328'
A0A3C1KS02/340-358'
A0A3C1KS02/364-389'
F4KY49/45-68'
F4KY49/80-103'
F4KY49/137-158'
F4KY49/170-190'
F4KY49/202-226'
F4KY49/238-259'
F4KY49/271-292'
F4KY49/301-319'
F4KY49/325-344'
F4KY49/365-385'
F4KY49/391-414'
I0JI83/6-30'
I0JI83/42-65'
I0JI83/96-114'
I0JI83/121-144'
I0JI83/156-177'
I0JI83/198-215'
I0JI83/227-252'
I0JI83/259-276'
I0JI83/282-300'
I0JI83/312-334'
I0JI83/354-376'
L0K9M1/38-56'
L0K9M1/77-100'
L0K9M1/120-139'
L0K9M1/151-171'
L0K9M1/183-203'
L0K9M1/224-241'
L0K9M1/253-275'
L0K9M1/287-305'
L0K9M1/311-329'
L0K9M1/341-359'
L0K9M1/371-395'
M0MDP9/23-43'
M0MDP9/64-85'
M0MDP9/105-130'
M0MDP9/137-161'
M0MDP9/173-194'
M0MDP9/215-232'
M0MDP9/252-275'
M0MDP9/287-304'
M0MDP9/310-328'
M0MDP9/340-363'
M0MDP9/375-396'

I3R0S7/17-37'
I3R0S7/59-79'
I3R0S7/101-121'
I3R0S7/130-150'
I3R0S7/170-190'
I3R0S7/214-234'
I3R0S7/258-278'
I3R0S7/286-306'
I3R0S7/307-327'
I3R0S7/342-362'
I3R0S7/374-394'
I3R635 has 12 helices, if 12, will use last 11, if other won't include
I3R635/36-56'
I3R635/76-96'
I3R635/106-126'
I3R635/134-154'
I3R635/171-191'
I3R635/221-241'
I3R635/250-270'
I3R635/300-320'
I3R635/327-347'
I3R635/359-379'
I3R635/391-411'
M0J579/14-34'
M0J579/55-77'
M0J579/97-119'
M0J579/126-149'
M0J579/169-190'
M0J579/211-228'
M0J579/248-272'
M0J579/284-301'
M0J579/307-324'
M0J579/336-359'
M0J579/371-398'
A0A482TED1/20-38'
A0A482TED1/59-81'
A0A482TED1/101-123'
A0A482TED1/130-153'
A0A482TED1/173-194'
A0A482TED1/215-232'
A0A482TED1/252-276'
A0A482TED1/288-305'
A0A482TED1/311-328'
A0A482TED1/340-365'
A0A482TED1/371-396'
E4NS62/20-38'
E4NS62/59-81'
E4NS62/101-123'
E4NS62/130-153'
E4NS62/173-194'
E4NS62/215-232'
E4NS62/252-276'
E4NS62/288-305'
E4NS62/311-328'
E4NS62/340-365'
E4NS62/371-396'
J2ZGN6/20-38'
J2ZGN6/59-80'
J2ZGN6/112-132'
J2ZGN6/139-160'
J2ZGN6/172-193'
J2ZGN6/214-233'
J2ZGN6/253-277'
J2ZGN6/289-308'
J2ZGN6/314-331'
J2ZGN6/343-366'
J2ZGN6/372-398'
J3EXK0/18-38'
J3EXK0/59-81'
J3EXK0/101-123'
J3EXK0/130-153'
J3EXK0/173-194'
J3EXK0/215-232'
J3EXK0/252-276'
J3EXK0/288-305'
J3EXK0/311-328'
J3EXK0/340-366'
J3EXK0/372-397'
A0A1H6R9C6/12-35'
A0A1H6R9C6/56-77'
A0A1H6R9C6/110-130'
A0A1H6R9C6/137-157'
A0A1H6R9C6/177-197'
A0A1H6R9C6/218-235'
A0A1H6R9C6/255-277'
A0A1H6R9C6/284-301'
A0A1H6R9C6/307-325'
A0A1H6R9C6/337-360'
A0A1H6R9C6/372-397'
A0A847UCB6/20-39'
A0A847UCB6/60-82'
A0A847UCB6/94-117'
A0A847UCB6/124-145'
A0A847UCB6/151-179'
A0A847UCB6/200-217'
A0A847UCB6/244-265'
A0A847UCB6/272-289'
A0A847UCB6/295-313'
A0A847UCB6/325-348'
A0A847UCB6/368-389'
A0A4D6KHD1/20-39'
A0A4D6KHD1/60-82'
A0A4D6KHD1/94-117'
A0A4D6KHD1/124-145'
A0A4D6KHD1/151-179'
A0A4D6KHD1/200-217'
A0A4D6KHD1/244-265'
A0A4D6KHD1/272-289'
A0A4D6KHD1/295-316'
A0A4D6KHD1/328-348'
A0A4D6KHD1/368-389'
C7P0S0/20-39'
C7P0S0/60-82'
C7P0S0/94-117'
C7P0S0/124-145'
C7P0S0/151-179'
C7P0S0/200-217'
C7P0S0/244-265'
C7P0S0/272-289'
C7P0S0/295-316'
C7P0S0/328-348'
C7P0S0/368-389'
A0A329Q0D7/12-35'
A0A329Q0D7/47-66'
A0A329Q0D7/107-125'
A0A329Q0D7/132-152'
A0A329Q0D7/172-189'
A0A329Q0D7/201-226'
A0A329Q0D7/246-265'
A0A329Q0D7/272-290'
A0A329Q0D7/296-318'
A0A329Q0D7/330-347'
A0A329Q0D7/353-378'
E1V4T3/12-35'
E1V4T3/47-66'
E1V4T3/107-125'
E1V4T3/132-152'
E1V4T3/172-189'
E1V4T3/201-226'
E1V4T3/246-265'
E1V4T3/272-290'
E1V4T3/296-318'
E1V4T3/330-347'
E1V4T3/353-378'
F8D7H6/16-36'
F8D7H6/57-77'
F8D7H6/97-117'
F8D7H6/124-147'
F8D7H6/159-180'
F8D7H6/201-218'
F8D7H6/238-260'
F8D7H6/267-284'
F8D7H6/290-311'
F8D7H6/323-342'
F8D7H6/354-379'
Q18ES8/18-37'
Q18ES8/58-81'
Q18ES8/101-123'
Q18ES8/130-153'
Q18ES8/173-194'
Q18ES8/215-232'
Q18ES8/258-280'
Q18ES8/287-304'
Q18ES8/310-331'
Q18ES8/343-370'
Q18ES8/376-405'
G0LFE3/18-37'
G0LFE3/58-81'
G0LFE3/101-123'
G0LFE3/130-153'
G0LFE3/173-194'
G0LFE3/215-232'
G0LFE3/258-280'
G0LFE3/287-304'
G0LFE3/310-331'
G0LFE3/343-370'
G0LFE3/376-405'
U1PPI7/18-37'
U1PPI7/58-81'
U1PPI7/101-123'
U1PPI7/130-153'
U1PPI7/173-194'
U1PPI7/215-232'
U1PPI7/258-280'
U1PPI7/287-304'
U1PPI7/310-331'
U1PPI7/343-370'
U1PPI7/376-401'
U1PIR6/18-37'
U1PIR6/58-81'
U1PIR6/101-123'
U1PIR6/130-153'
U1PIR6/173-194'
U1PIR6/215-232'
U1PIR6/258-280'
U1PIR6/287-304'
U1PIR6/310-331'
U1PIR6/343-370'
U1PIR6/376-401'
C7NND6/12-33'
C7NND6/54-77'
C7NND6/97-119'
C7NND6/126-147'
C7NND6/175-196'
C7NND6/217-234'
C7NND6/254-273'
C7NND6/285-302'
C7NND6/308-325'
C7NND6/337-360'
C7NND6/380-404'
C7NND3/20-37'
C7NND3/58-79'
C7NND3/99-118'
C7NND3/130-152'
C7NND3/164-182'
C7NND3/203-227'
C7NND3/247-268'
C7NND3/275-292'
C7NND3/298-319'
C7NND3/331-351'
C7NND3/371-392'
A0A0X8X7Y7/14-33'
A0A0X8X7Y7/53-70'
A0A0X8X7Y7/111-129'
A0A0X8X7Y7/136-156'
A0A0X8X7Y7/176-195'
A0A0X8X7Y7/207-230'
A0A0X8X7Y7/250-273'
A0A0X8X7Y7/280-296'
A0A0X8X7Y7/302-322'
A0A0X8X7Y7/331-350'
A0A0X8X7Y7/362-382'
W8KM07/15-39'
W8KM07/51-70'
W8KM07/111-129'
W8KM07/136-156'
W8KM07/176-194'
W8KM07/206-230'
W8KM07/250-273'
W8KM07/280-297'
W8KM07/303-322'
W8KM07/334-351'
W8KM07/357-382'
B9LU00/20-37'
B9LU00/58-79'
B9LU00/99-119'
B9LU00/126-149'
B9LU00/161-182'
B9LU00/203-220'
B9LU00/240-265'
B9LU00/277-293'
B9LU00/299-317'
B9LU00/329-352'
B9LU00/364-385'
M0D3Q9/20-37'
M0D3Q9/58-79'
M0D3Q9/99-119'
M0D3Q9/126-149'
M0D3Q9/169-190'
M0D3Q9/211-228'
M0D3Q9/248-271'
M0D3Q9/278-295'
M0D3Q9/301-322'
M0D3Q9/334-355'
M0D3Q9/367-392'
M0D580/27-46'
M0D580/67-90'
M0D580/110-132'
M0D580/139-160'
M0D580/180-201'
M0D580/222-242'
M0D580/262-285'
M0D580/297-314'
M0D580/320-341'
M0D580/353-374'
M0D580/386-408'
W0JIB3/16-36'
W0JIB3/57-78'
W0JIB3/98-118'
W0JIB3/125-147'
W0JIB3/167-188'
W0JIB3/209-226'
W0JIB3/254-275'
W0JIB3/282-299'
W0JIB3/305-326'
W0JIB3/338-357'
W0JIB3/377-398'
A0A172YCA7/39-57'
A0A172YCA7/69-89'
A0A172YCA7/133-154'
A0A172YCA7/161-182'
A0A172YCA7/202-220'
A0A172YCA7/232-252'
A0A172YCA7/264-283'
A0A172YCA7/295-313'
A0A172YCA7/319-339'
A0A172YCA7/351-375'
A0A172YCA7/387-409'
A0A172YBR4/20-45'
A0A172YBR4/57-76'
A0A172YBR4/117-136'
A0A172YBR4/141-162'
A0A172YBR4/182-200'
A0A172YBR4/212-236'
A0A172YBR4/256-275'
A0A172YBR4/282-300'
A0A172YBR4/306-326'
A0A172YBR4/338-357'
A0A172YBR4/363-388'
D2RU19/20-41'
D2RU19/62-87'
D2RU19/99-119'
D2RU19/126-147'
D2RU19/162-183'
D2RU19/204-221'
D2RU19/241-263'
D2RU19/270-287'
D2RU19/293-313'
D2RU19/325-344'
D2RU19/364-385'
D0KXQ0/12-32'
D0KXQ0/53-71'
D0KXQ0/91-110'
D0KXQ0/119-139'
D0KXQ0/159-180'
D0KXQ0/201-220'
D0KXQ0/226-251'
D0KXQ0/258-276'
D0KXQ0/282-300'
D0KXQ0/312-332'
D0KXQ0/344-368'
Q45HK8/83-104'
Q45HK8/116-134'
Q45HK8/176-198'
Q45HK8/205-228'
Q45HK8/258-280'
Q45HK8/292-312'
Q45HK8/324-344'
Q45HK8/356-373'
Q45HK8/379-399'
Q45HK8/411-431'
Q45HK8/457-479'
D8ITX4/83-104'
D8ITX4/116-134'
D8ITX4/176-198'
D8ITX4/205-228'
D8ITX4/258-280'
D8ITX4/292-312'
D8ITX4/324-344'
D8ITX4/356-373'
D8ITX4/379-399'
D8ITX4/411-431'
D8ITX4/457-479'
A0A6M3ZJI1/84-105'
A0A6M3ZJI1/117-135'
A0A6M3ZJI1/177-199'
A0A6M3ZJI1/206-229'
A0A6M3ZJI1/259-281'
A0A6M3ZJI1/293-313'
A0A6M3ZJI1/325-345'
A0A6M3ZJI1/357-374'
A0A6M3ZJI1/380-400'
A0A6M3ZJI1/412-432'
A0A6M3ZJI1/458-480'
A0A5B8DZA7/12-32'
A0A5B8DZA7/44-66'
A0A5B8DZA7/86-105'
A0A5B8DZA7/117-137'
A0A5B8DZA7/157-178'
A0A5B8DZA7/199-219'
A0A5B8DZA7/231-249'
A0A5B8DZA7/256-274'
A0A5B8DZA7/280-296'
A0A5B8DZA7/308-333'
A0A5B8DZA7/345-366'
A0A6M3ZKU5/12-32'
A0A6M3ZKU5/44-66'
A0A6M3ZKU5/86-105'
A0A6M3ZKU5/117-137'
A0A6M3ZKU5/157-178'
A0A6M3ZKU5/199-219'
A0A6M3ZKU5/231-249'
A0A6M3ZKU5/256-274'
A0A6M3ZKU5/280-296'
A0A6M3ZKU5/308-333'
A0A6M3ZKU5/345-366'
A4G1J2/71-92'
A4G1J2/104-124'
A4G1J2/158-180'
A4G1J2/187-210'
A4G1J2/222-244'
A4G1J2/256-276'
A4G1J2/282-307'
A4G1J2/319-340'
A4G1J2/346-363'
A4G1J2/375-398'
A4G1J2/418-437'
A9B874/40-61'
A9B874/82-106'
A9B874/126-147'
A9B874/154-174'
A9B874/180-210'
A9B874/231-248'
A9B874/260-286'
A9B874/293-311'
A9B874/317-336'
A9B874/348-371'
A9B874/391-417'
A9AUR8/12-31'
A9AUR8/43-65'
A9AUR8/102-122'
A9AUR8/129-150'
A9AUR8/162-186'
A9AUR8/198-218'
A9AUR8/224-249'
A9AUR8/261-279'
A9AUR8/285-302'
A9AUR8/314-335'
A9AUR8/355-377'
C6XKC2/45-69'
C6XKC2/81-100'
C6XKC2/135-154'
C6XKC2/159-176'
C6XKC2/196-216'
C6XKC2/236-253'
C6XKC2/273-296'
C6XKC2/303-320'
C6XKC2/326-346'
C6XKC2/353-374'
C6XKC2/380-405'
B0UT87/47-69'
B0UT87/81-102'
B0UT87/144-165'
B0UT87/172-193'
B0UT87/213-232'
B0UT87/244-261'
B0UT87/273-293'
B0UT87/305-324'
B0UT87/330-348'
B0UT87/360-379'
B0UT87/391-412'
Q0I445/37-59'
Q0I445/71-92'
Q0I445/134-155'
Q0I445/162-183'
Q0I445/203-222'
Q0I445/234-251'
Q0I445/263-283'
Q0I445/295-314'
Q0I445/320-338'
Q0I445/350-369'
Q0I445/381-402'
Q9H310 has 12 helices, if 12, will use last 11, if other won't include
Q9H310/62-82'
Q9H310/87-107'
Q9H310/125-145'
Q9H310/150-170'
Q9H310/179-201'
Q9H310/220-240'
Q9H310/252-272'
Q9H310/283-303'
Q9H310/305-325'
Q9H310/347-367'
Q9H310/394-414'
Q9UBD6 has 12 helices, if 12, will use last 11, if other won't include
Q9UBD6/61-81'
Q9UBD6/86-106'
Q9UBD6/124-144'
Q9UBD6/149-169'
Q9UBD6/178-200'
Q9UBD6/219-239'
Q9UBD6/251-271'
Q9UBD6/282-302'
Q9UBD6/304-324'
Q9UBD6/346-366'
Q9UBD6/395-415'
Q02094 has 12 helices, if 12, will use last 11, if other won't include
Q02094/52-72'
Q02094/80-100'
Q02094/114-134'
Q02094/143-163'
Q02094/168-188'
Q02094/209-229'
Q02094/240-260'
Q02094/269-291'
Q02094/296-318'
Q02094/333-353'
Q02094/363-383'

Q02161/12-32'
Q02161/44-64'
Q02161/77-97'
Q02161/107-127'
Q02161/130-150'
Q02161/167-187'
Q02161/203-223'
Q02161/238-258'
Q02161/287-307'
Q02161/334-354'
Q02161/358-378'
P18577/12-32'
P18577/44-64'
P18577/77-97'
P18577/125-145'
P18577/172-192'
P18577/203-223'
P18577/238-258'
P18577/265-285'
P18577/287-307'
P18577/331-351'
P18577/358-378'
Q15849 has 17 helices, if 12, will use last 11, if other won't include
Q15849/346-366'
Q15849/370-390'
Q15849/392-412'
Q15849/600-620'
Q15849/638-658'
Q15849/666-686'
Q15849/695-715'
Q15849/764-784'
Q15849/803-823'
Q15849/832-852'
Q15849/854-874'
Q9Y666 has 12 helices, if 12, will use last 11, if other won't include
Q9Y666/141-161'
Q9Y666/215-235'
Q9Y666/253-273'
Q9Y666/276-296'
Q9Y666/416-436'
Q9Y666/457-477'
Q9Y666/494-514'
Q9Y666/554-574'
Q9Y666/578-598'
Q9Y666/625-645'
Q9Y666/845-865'
P55011 has 12 helices, if 12, will use last 11, if other won't include
P55011/322-343'
P55011/362-397'
P55011/407-424'
P55011/430-454'
P55011/487-507'
P55011/515-542'
P55011/600-632'
P55011/654-668'
P55011/671-697'
P55011/712-730'
P55011/732-751'
Q9UP95 has 12 helices, if 12, will use last 11, if other won't include
Q9UP95/150-172'
Q9UP95/197-225'
Q9UP95/249-271'
Q9UP95/272-297'
Q9UP95/420-440'
Q9UP95/451-473'
Q9UP95/505-531'
Q9UP95/555-575'
Q9UP95/576-598'
Q9UP95/613-635'
Q9UP95/636-651'
Q9H015 has 12 helices, if 12, will use last 11, if other won't include
Q9H015/142-162'
Q9H015/172-192'
Q9H015/198-218'
Q9H015/233-253'
Q9H015/258-278'
Q9H015/338-358'
Q9H015/372-392'
Q9H015/400-420'
Q9H015/427-447'
Q9H015/461-481'
Q9H015/487-507'
Q7LBE3 has 14 helices, if 12, will use last 11, if other won't include
Q7LBE3/172-190'
Q7LBE3/203-224'
Q7LBE3/255-273'
Q7LBE3/282-297'
Q7LBE3/328-348'
Q7LBE3/367-382'
Q7LBE3/391-400'
Q7LBE3/405-423'
Q7LBE3/429-450'
Q7LBE3/465-476'
Q7LBE3/478-489'
Q9UHW9 has 12 helices, if 12, will use last 11, if other won't include
Q9UHW9/217-239'
Q9UHW9/264-292'
Q9UHW9/316-338'
Q9UHW9/339-364'
Q9UHW9/485-505'
Q9UHW9/516-538'
Q9UHW9/570-596'
Q9UHW9/620-640'
Q9UHW9/641-663'
Q9UHW9/678-700'
Q9UHW9/701-716'
Q9H2X9 has 12 helices, if 12, will use last 11, if other won't include
Q9H2X9/152-176'
Q9H2X9/198-227'
Q9H2X9/252-273'
Q9H2X9/274-299'
Q9H2X9/423-443'
Q9H2X9/453-476'
Q9H2X9/509-537'
Q9H2X9/558-574'
Q9H2X9/577-601'
Q9H2X9/619-636'
Q9H2X9/638-655'
I8TC71/76-97'
I8TC71/109-129'
I8TC71/172-194'
I8TC71/201-222'
I8TC71/242-259'
I8TC71/271-291'
I8TC71/303-327'
I8TC71/334-353'
I8TC71/359-378'
I8TC71/390-411'
I8TC71/431-453'
I7ZHW3/76-98'
I7ZHW3/110-128'
I7ZHW3/175-197'
I7ZHW3/204-227'
I7ZHW3/257-278'
I7ZHW3/290-309'
I7ZHW3/321-342'
I7ZHW3/354-371'
I7ZHW3/377-398'
I7ZHW3/410-429'
I7ZHW3/454-479'
D3DJN2/34-53'
D3DJN2/65-84'
D3DJN2/119-137'
D3DJN2/149-170'
D3DJN2/182-203'
D3DJN2/215-233'
D3DJN2/245-264'
D3DJN2/276-294'
D3DJN2/300-320'
D3DJN2/332-351'
D3DJN2/371-395'
A0A066ZTE4/14-38'
A0A066ZTE4/50-69'
A0A066ZTE4/111-130'
A0A066ZTE4/137-156'
A0A066ZTE4/176-195'
A0A066ZTE4/207-227'
A0A066ZTE4/247-268'
A0A066ZTE4/280-298'
A0A066ZTE4/304-322'
A0A066ZTE4/334-352'
A0A066ZTE4/358-383'
A0A066ZRQ5/6-28'
A0A066ZRQ5/49-69'
A0A066ZRQ5/89-110'
A0A066ZRQ5/117-138'
A0A066ZRQ5/158-178'
A0A066ZRQ5/190-209'
A0A066ZRQ5/215-243'
A0A066ZRQ5/255-273'
A0A066ZRQ5/279-296'
A0A066ZRQ5/308-326'
A0A066ZRQ5/338-357'
A0A4P6UIK6/59-80'
A0A4P6UIK6/92-110'
A0A4P6UIK6/152-174'
A0A4P6UIK6/181-205'
A0A4P6UIK6/234-255'
A0A4P6UIK6/267-288'
A0A4P6UIK6/300-319'
A0A4P6UIK6/331-348'
A0A4P6UIK6/354-375'
A0A4P6UIK6/387-407'
A0A4P6UIK6/433-455'
F3KUN4/59-80'
F3KUN4/92-110'
F3KUN4/152-174'
F3KUN4/181-205'
F3KUN4/234-255'
F3KUN4/267-288'
F3KUN4/300-319'
F3KUN4/331-348'
F3KUN4/354-375'
F3KUN4/387-407'
F3KUN4/433-455'
A0A016XCG9/59-80'
A0A016XCG9/92-110'
A0A016XCG9/152-174'
A0A016XCG9/181-205'
A0A016XCG9/234-255'
A0A016XCG9/267-288'
A0A016XCG9/300-319'
A0A016XCG9/331-348'
A0A016XCG9/354-375'
A0A016XCG9/387-411'
A0A016XCG9/431-455'
A0A4P6UIJ8/6-29'
A0A4P6UIJ8/41-61'
A0A4P6UIJ8/99-119'
A0A4P6UIJ8/126-149'
A0A4P6UIJ8/174-195'
A0A4P6UIJ8/207-228'
A0A4P6UIJ8/240-261'
A0A4P6UIJ8/270-288'
A0A4P6UIJ8/294-314'
A0A4P6UIJ8/326-346'
A0A4P6UIJ8/366-387'
A0A016XDZ5/6-29'
A0A016XDZ5/41-61'
A0A016XDZ5/99-119'
A0A016XDZ5/126-149'
A0A016XDZ5/174-195'
A0A016XDZ5/207-228'
A0A016XDZ5/240-261'
A0A016XDZ5/270-288'
A0A016XDZ5/294-314'
A0A016XDZ5/326-350'
A0A016XDZ5/362-387'
A0A0D2NYP3/29-50'
A0A0D2NYP3/62-80'
A0A0D2NYP3/116-137'
A0A0D2NYP3/149-170'
A0A0D2NYP3/176-200'
A0A0D2NYP3/221-239'
A0A0D2NYP3/251-272'
A0A0D2NYP3/279-296'
A0A0D2NYP3/302-322'
A0A0D2NYP3/334-356'
A0A0D2NYP3/391-409'
A0A0D2LEF5/26-47'
A0A0D2LEF5/59-77'
A0A0D2LEF5/117-138'
A0A0D2LEF5/145-169'
A0A0D2LEF5/181-203'
A0A0D2LEF5/215-235'
A0A0D2LEF5/247-268'
A0A0D2LEF5/280-299'
A0A0D2LEF5/305-325'
A0A0D2LEF5/337-357'
A0A0D2LEF5/377-402'
A0A0D2KGN8/32-53'
A0A0D2KGN8/65-89'
A0A0D2KGN8/121-140'
A0A0D2KGN8/152-174'
A0A0D2KGN8/186-207'
A0A0D2KGN8/227-248'
A0A0D2KGN8/254-275'
A0A0D2KGN8/282-299'
A0A0D2KGN8/305-326'
A0A0D2KGN8/338-361'
A0A0D2KGN8/381-408'
V5SAJ5/52-75'
V5SAJ5/87-109'
V5SAJ5/144-165'
V5SAJ5/172-194'
V5SAJ5/206-227'
V5SAJ5/239-260'
V5SAJ5/272-291'
V5SAJ5/303-324'
V5SAJ5/330-347'
V5SAJ5/359-378'
V5SAJ5/398-421'
Q0BWD0/55-79'
Q0BWD0/91-110'
Q0BWD0/148-167'
Q0BWD0/172-190'
Q0BWD0/210-230'
Q0BWD0/250-267'
Q0BWD0/287-310'
Q0BWD0/317-336'
Q0BWD0/342-361'
Q0BWD0/368-389'
Q0BWD0/395-420'
Q5QVH2/16-36'
Q5QVH2/48-66'
Q5QVH2/86-105'
Q5QVH2/112-134'
Q5QVH2/146-167'
Q5QVH2/188-205'
Q5QVH2/225-243'
Q5QVH2/255-272'
Q5QVH2/278-297'
Q5QVH2/309-326'
Q5QVH2/332-357'
E3H8C9/37-56'
E3H8C9/77-94'
E3H8C9/114-134'
E3H8C9/141-163'
E3H8C9/183-204'
E3H8C9/224-241'
E3H8C9/253-274'
E3H8C9/286-303'
E3H8C9/309-328'
E3H8C9/340-359'
E3H8C9/371-393'
E3H8A6/33-53'
E3H8A6/74-95'
E3H8A6/115-135'
E3H8A6/142-160'
E3H8A6/180-200'
E3H8A6/221-238'
E3H8A6/250-272'
E3H8A6/279-300'
E3H8A6/306-326'
E3H8A6/338-357'
E3H8A6/363-383'
I0WJ97/6-23'
I0WJ97/35-54'
I0WJ97/92-111'
I0WJ97/118-140'
I0WJ97/152-173'
I0WJ97/194-211'
I0WJ97/223-250'
I0WJ97/257-275'
I0WJ97/281-299'
I0WJ97/311-330'
I0WJ97/342-363'
A0A211ZGL5/39-57'
A0A211ZGL5/69-92'
A0A211ZGL5/124-145'
A0A211ZGL5/152-173'
A0A211ZGL5/179-209'
A0A211ZGL5/221-244'
A0A211ZGL5/250-275'
A0A211ZGL5/287-305'
A0A211ZGL5/311-331'
A0A211ZGL5/343-362'
A0A211ZGL5/382-406'
A0A952FNL7/39-61'
A0A952FNL7/68-89'
A0A952FNL7/126-147'
A0A952FNL7/154-175'
A0A952FNL7/181-211'
A0A952FNL7/223-246'
A0A952FNL7/258-277'
A0A952FNL7/289-307'
A0A952FNL7/313-333'
A0A952FNL7/345-364'
A0A952FNL7/384-408'
A0A0A0D6K5/38-59'
A0A0A0D6K5/71-94'
A0A0A0D6K5/126-147'
A0A0A0D6K5/154-175'
A0A0A0D6K5/181-211'
A0A0A0D6K5/223-246'
A0A0A0D6K5/252-277'
A0A0A0D6K5/289-307'
A0A0A0D6K5/313-333'
A0A0A0D6K5/345-364'
A0A0A0D6K5/384-408'
E6SF19/20-41'
E6SF19/53-71'
E6SF19/121-143'
E6SF19/150-171'
E6SF19/207-227'
E6SF19/239-256'
E6SF19/268-289'
E6SF19/296-313'
E6SF19/319-342'
E6SF19/354-381'
E6SF19/387-412'
F6FRU9/6-29'
F6FRU9/41-59'
F6FRU9/105-124'
F6FRU9/131-153'
F6FRU9/173-195'
F6FRU9/207-227'
F6FRU9/239-259'
F6FRU9/271-288'
F6FRU9/294-313'
F6FRU9/325-344'
F6FRU9/356-383'
B7QKQ6/26-46'
B7QKQ6/67-83'
B7QKQ6/115-134'
B7QKQ6/141-161'
B7QKQ6/173-196'
B7QKQ6/217-238'
B7QKQ6/250-270'
B7QKQ6/277-299'
B7QKQ6/305-324'
B7QKQ6/331-352'
B7QKQ6/372-398'
B7Q7U2/12-31'
B7Q7U2/43-63'
B7Q7U2/102-124'
B7Q7U2/131-154'
B7Q7U2/174-195'
B7Q7U2/207-224'
B7Q7U2/236-255'
B7Q7U2/267-287'
B7Q7U2/293-311'
B7Q7U2/323-341'
B7Q7U2/361-383'
C7R314/6-28'
C7R314/40-58'
C7R314/107-126'
C7R314/133-154'
C7R314/174-196'
C7R314/208-227'
C7R314/239-260'
C7R314/272-289'
C7R314/295-314'
C7R314/326-346'
C7R314/358-384'
I3C0V3/14-34'
I3C0V3/55-75'
I3C0V3/95-114'
I3C0V3/121-142'
I3C0V3/154-177'
I3C0V3/198-216'
I3C0V3/228-251'
I3C0V3/263-283'
I3C0V3/289-305'
I3C0V3/317-336'
I3C0V3/351-375'
A0A7W4TJ72/6-27'
A0A7W4TJ72/39-57'
A0A7W4TJ72/94-114'
A0A7W4TJ72/126-147'
A0A7W4TJ72/159-190'
A0A7W4TJ72/202-222'
A0A7W4TJ72/234-254'
A0A7W4TJ72/266-283'
A0A7W4TJ72/289-308'
A0A7W4TJ72/320-339'
A0A7W4TJ72/359-381'
A6W7U2/6-27'
A6W7U2/39-57'
A6W7U2/94-114'
A6W7U2/126-147'
A6W7U2/159-190'
A6W7U2/202-222'
A6W7U2/234-254'
A6W7U2/266-283'
A6W7U2/289-308'
A6W7U2/320-339'
A6W7U2/359-381'
K6W5X0/12-30'
K6W5X0/37-59'
K6W5X0/95-116'
K6W5X0/128-148'
K6W5X0/168-193'
K6W5X0/205-225'
K6W5X0/237-257'
K6W5X0/269-286'
K6W5X0/292-311'
K6W5X0/323-342'
K6W5X0/362-387'
E4NAC1/16-36'
E4NAC1/48-71'
E4NAC1/104-126'
E4NAC1/133-154'
E4NAC1/174-194'
E4NAC1/206-223'
E4NAC1/235-256'
E4NAC1/263-283'
E4NAC1/289-309'
E4NAC1/321-344'
E4NAC1/364-382'

E4NHH7/12-31'
E4NHH7/43-61'
E4NHH7/91-116'
E4NHH7/128-149'
E4NHH7/169-190'
E4NHH7/202-222'
E4NHH7/228-255'
E4NHH7/262-282'
E4NHH7/288-308'
E4NHH7/320-343'
E4NHH7/363-381'
E4N1T5/12-31'
E4N1T5/43-61'
E4N1T5/97-117'
E4N1T5/129-150'
E4N1T5/170-189'
E4N1T5/201-219'
E4N1T5/231-252'
E4N1T5/259-279'
E4N1T5/285-305'
E4N1T5/317-338'
E4N1T5/358-377'
A0A318FY98/32-58'
A0A318FY98/70-97'
A0A318FY98/117-142'
A0A318FY98/149-171'
A0A318FY98/183-205'
A0A318FY98/217-236'
A0A318FY98/248-268'
A0A318FY98/280-302'
A0A318FY98/308-324'
A0A318FY98/336-362'
A0A318FY98/374-396'
A0A6B8N021/27-53'
A0A6B8N021/65-92'
A0A6B8N021/112-137'
A0A6B8N021/144-166'
A0A6B8N021/178-200'
A0A6B8N021/212-231'
A0A6B8N021/243-262'
A0A6B8N021/274-292'
A0A6B8N021/298-319'
A0A6B8N021/331-357'
A0A6B8N021/369-391'
A0A168EVK8/32-58'
A0A168EVK8/70-97'
A0A168EVK8/117-142'
A0A168EVK8/149-171'
A0A168EVK8/183-205'
A0A168EVK8/217-236'
A0A168EVK8/248-267'
A0A168EVK8/279-297'
A0A168EVK8/303-324'
A0A168EVK8/336-362'
A0A168EVK8/374-396'
A0A0H3H4I7/27-53'
A0A0H3H4I7/65-92'
A0A0H3H4I7/112-137'
A0A0H3H4I7/144-166'
A0A0H3H4I7/178-200'
A0A0H3H4I7/212-231'
A0A0H3H4I7/243-262'
A0A0H3H4I7/274-292'
A0A0H3H4I7/298-319'
A0A0H3H4I7/331-357'
A0A0H3H4I7/369-391'
A0A0J2IA68/32-58'
A0A0J2IA68/70-97'
A0A0J2IA68/117-142'
A0A0J2IA68/149-171'
A0A0J2IA68/183-205'
A0A0J2IA68/217-236'
A0A0J2IA68/248-267'
A0A0J2IA68/279-297'
A0A0J2IA68/303-324'
A0A0J2IA68/336-362'
A0A0J2IA68/374-396'
A0A378GLU3/33-59'
A0A378GLU3/71-98'
A0A378GLU3/118-143'
A0A378GLU3/150-172'
A0A378GLU3/184-206'
A0A378GLU3/218-237'
A0A378GLU3/249-269'
A0A378GLU3/281-298'
A0A378GLU3/304-325'
A0A378GLU3/337-363'
A0A378GLU3/375-397'
A0A3N2SFS2/32-58'
A0A3N2SFS2/70-97'
A0A3N2SFS2/117-142'
A0A3N2SFS2/149-171'
A0A3N2SFS2/183-205'
A0A3N2SFS2/217-236'
A0A3N2SFS2/248-268'
A0A3N2SFS2/280-297'
A0A3N2SFS2/303-324'
A0A3N2SFS2/336-362'
A0A3N2SFS2/374-396'
A0A2T2Y0D5/32-58'
A0A2T2Y0D5/70-97'
A0A2T2Y0D5/117-142'
A0A2T2Y0D5/149-171'
A0A2T2Y0D5/183-205'
A0A2T2Y0D5/217-236'
A0A2T2Y0D5/248-268'
A0A2T2Y0D5/280-297'
A0A2T2Y0D5/303-324'
A0A2T2Y0D5/336-362'
A0A2T2Y0D5/374-396'
A0A5P2U5F4/31-52'
A0A5P2U5F4/64-82'
A0A5P2U5F4/123-141'
A0A5P2U5F4/153-174'
A0A5P2U5F4/186-206'
A0A5P2U5F4/227-245'
A0A5P2U5F4/257-278'
A0A5P2U5F4/287-306'
A0A5P2U5F4/312-330'
A0A5P2U5F4/342-364'
A0A5P2U5F4/392-415'
A0A5P2U5E9/31-52'
A0A5P2U5E9/64-82'
A0A5P2U5E9/122-140'
A0A5P2U5E9/152-173'
A0A5P2U5E9/185-205'
A0A5P2U5E9/226-244'
A0A5P2U5E9/256-277'
A0A5P2U5E9/286-305'
A0A5P2U5E9/311-329'
A0A5P2U5E9/341-363'
A0A5P2U5E9/393-414'
Q6CRN1/31-52'
Q6CRN1/64-82'
Q6CRN1/123-141'
Q6CRN1/153-174'
Q6CRN1/186-206'
Q6CRN1/227-245'
Q6CRN1/257-278'
Q6CRN1/287-306'
Q6CRN1/312-330'
Q6CRN1/342-364'
Q6CRN1/392-415'
Q6CRN0/31-52'
Q6CRN0/64-82'
Q6CRN0/122-140'
Q6CRN0/152-173'
Q6CRN0/185-205'
Q6CRN0/226-244'
Q6CRN0/256-277'
Q6CRN0/286-305'
Q6CRN0/311-329'
Q6CRN0/341-363'
Q6CRN0/393-414'
A0A5P2U8K3/12-35'
A0A5P2U8K3/47-65'
A0A5P2U8K3/107-127'
A0A5P2U8K3/139-157'
A0A5P2U8K3/177-193'
A0A5P2U8K3/205-225'
A0A5P2U8K3/237-258'
A0A5P2U8K3/265-283'
A0A5P2U8K3/289-307'
A0A5P2U8K3/328-347'
A0A5P2U8K3/367-392'
Q6CVL9/12-35'
Q6CVL9/47-65'
Q6CVL9/107-127'
Q6CVL9/139-157'
Q6CVL9/177-193'
Q6CVL9/205-225'
Q6CVL9/237-258'
Q6CVL9/265-283'
Q6CVL9/289-307'
Q6CVL9/328-347'
Q6CVL9/367-392'
A0A5P2UBW0 has 13 helices, if 12, will use last 11, if other won't include
A0A5P2UBW0/130-148'
A0A5P2UBW0/160-178'
A0A5P2UBW0/190-210'
A0A5P2UBW0/230-247'
A0A5P2UBW0/259-277'
A0A5P2UBW0/297-315'
A0A5P2UBW0/335-353'
A0A5P2UBW0/360-379'
A0A5P2UBW0/385-410'
A0A5P2UBW0/422-443'
A0A5P2UBW0/463-484'
Q6CWZ4 has 13 helices, if 12, will use last 11, if other won't include
Q6CWZ4/130-148'
Q6CWZ4/160-178'
Q6CWZ4/190-210'
Q6CWZ4/230-247'
Q6CWZ4/259-277'
Q6CWZ4/297-315'
Q6CWZ4/335-353'
Q6CWZ4/360-379'
Q6CWZ4/385-410'
Q6CWZ4/422-443'
Q6CWZ4/463-484'
A0A0B4EV76/6-28'
A0A0B4EV76/40-58'
A0A0B4EV76/91-113'
A0A0B4EV76/120-142'
A0A0B4EV76/162-185'
A0A0B4EV76/197-217'
A0A0B4EV76/229-248'
A0A0B4EV76/260-278'
A0A0B4EV76/284-302'
A0A0B4EV76/314-334'
A0A0B4EV76/354-376'
A0A101Y6H3/20-39'
A0A101Y6H3/51-69'
A0A101Y6H3/102-124'
A0A101Y6H3/131-153'
A0A101Y6H3/173-196'
A0A101Y6H3/208-228'
A0A101Y6H3/240-259'
A0A101Y6H3/271-289'
A0A101Y6H3/295-313'
A0A101Y6H3/325-345'
A0A101Y6H3/365-387'
A0A2I1P2U4/20-39'
A0A2I1P2U4/51-69'
A0A2I1P2U4/102-124'
A0A2I1P2U4/131-153'
A0A2I1P2U4/173-196'
A0A2I1P2U4/208-228'
A0A2I1P2U4/240-259'
A0A2I1P2U4/271-289'
A0A2I1P2U4/295-313'
A0A2I1P2U4/325-345'
A0A2I1P2U4/365-387'
B2GFN1/20-39'
B2GFN1/51-69'
B2GFN1/103-124'
B2GFN1/131-153'
B2GFN1/173-196'
B2GFN1/208-228'
B2GFN1/240-259'
B2GFN1/271-289'
B2GFN1/295-313'
B2GFN1/325-345'
B2GFN1/365-387'
A0A9E1C4G3/20-39'
A0A9E1C4G3/51-69'
A0A9E1C4G3/107-124'
A0A9E1C4G3/131-153'
A0A9E1C4G3/173-196'
A0A9E1C4G3/208-228'
A0A9E1C4G3/240-259'
A0A9E1C4G3/271-289'
A0A9E1C4G3/295-313'
A0A9E1C4G3/325-345'
A0A9E1C4G3/365-387'
A9DQM8/38-58'
A9DQM8/79-96'
A9DQM8/116-135'
A9DQM8/140-157'
A9DQM8/177-198'
A9DQM8/219-235'
A9DQM8/255-277'
A9DQM8/284-301'
A9DQM8/307-326'
A9DQM8/338-358'
A9DQM8/378-400'
A0A165BP25/37-58'
A0A165BP25/70-89'
A0A165BP25/120-142'
A0A165BP25/149-171'
A0A165BP25/183-205'
A0A165BP25/217-236'
A0A165BP25/248-268'
A0A165BP25/280-297'
A0A165BP25/303-324'
A0A165BP25/336-362'
A0A165BP25/374-396'
C5CIT6/20-41'
C5CIT6/62-83'
C5CIT6/103-125'
C5CIT6/137-159'
C5CIT6/171-192'
C5CIT6/204-222'
C5CIT6/234-258'
C5CIT6/265-286'
C5CIT6/292-308'
C5CIT6/320-343'
C5CIT6/363-384'
A0A1D8UWJ6/32-55'
A0A1D8UWJ6/67-89'
A0A1D8UWJ6/138-159'
A0A1D8UWJ6/166-187'
A0A1D8UWJ6/199-223'
A0A1D8UWJ6/235-255'
A0A1D8UWJ6/267-286'
A0A1D8UWJ6/298-318'
A0A1D8UWJ6/324-342'
A0A1D8UWJ6/354-374'
A0A1D8UWJ6/394-416'
D2Q0J8/15-35'
D2Q0J8/47-69'
D2Q0J8/103-125'
D2Q0J8/132-153'
D2Q0J8/173-195'
D2Q0J8/207-227'
D2Q0J8/239-259'
D2Q0J8/271-288'
D2Q0J8/294-313'
D2Q0J8/325-348'
D2Q0J8/368-389'
D6TFE1 has 12 helices, if 12, will use last 11, if other won't include
D6TFE1/71-95'
D6TFE1/107-127'
D6TFE1/147-166'
D6TFE1/187-206'
D6TFE1/226-246'
D6TFE1/258-276'
D6TFE1/296-317'
D6TFE1/324-344'
D6TFE1/350-368'
D6TFE1/380-404'
D6TFE1/432-453'
D6TCH6/32-57'
D6TCH6/69-87'
D6TCH6/122-144'
D6TCH6/151-174'
D6TCH6/186-207'
D6TCH6/219-241'
D6TCH6/253-277'
D6TCH6/284-302'
D6TCH6/308-327'
D6TCH6/339-359'
D6TCH6/379-401'
W5WIX6/6-28'
W5WIX6/40-62'
W5WIX6/97-118'
W5WIX6/125-148'
W5WIX6/168-193'
W5WIX6/205-225'
W5WIX6/237-257'
W5WIX6/269-290'
W5WIX6/296-313'
W5WIX6/325-346'
W5WIX6/366-388'
B0DY50/27-48'
B0DY50/60-78'
B0DY50/114-135'
B0DY50/147-168'
B0DY50/188-208'
B0DY50/220-237'
B0DY50/249-270'
B0DY50/277-294'
B0DY50/300-320'
B0DY50/332-356'
B0DY50/376-403'
B0DU91/17-38'
B0DU91/50-68'
B0DU91/108-126'
B0DU91/138-160'
B0DU91/172-194'
B0DU91/206-226'
B0DU91/238-259'
B0DU91/266-284'
B0DU91/290-309'
B0DU91/329-349'
B0DU91/369-387'
B0DXT9/17-38'
B0DXT9/50-68'
B0DXT9/108-126'
B0DXT9/138-160'
B0DXT9/172-194'
B0DXT9/206-226'
B0DXT9/238-259'
B0DXT9/266-284'
B0DXT9/290-309'
B0DXT9/329-349'
B0DXT9/369-387'
B0CQX4/31-52'
B0CQX4/64-82'
B0CQX4/122-143'
B0CQX4/150-174'
B0CQX4/186-208'
B0CQX4/220-240'
B0CQX4/252-273'
B0CQX4/280-298'
B0CQX4/304-323'
B0CQX4/335-356'
B0CQX4/386-407'
B0DU93/12-30'
B0DU93/42-60'
B0DU93/102-120'
B0DU93/132-154'
B0DU93/166-188'
B0DU93/200-220'
B0DU93/232-253'
B0DU93/260-278'
B0DU93/284-303'
B0DU93/323-343'
B0DU93/363-381'
B0CXH8/28-50'
B0CXH8/62-81'
B0CXH8/115-136'
B0CXH8/143-160'
B0CXH8/172-199'
B0CXH8/220-238'
B0CXH8/250-271'
B0CXH8/278-295'
B0CXH8/301-322'
B0CXH8/334-355'
B0CXH8/390-408'
B0DFJ4/29-50'
B0DFJ4/62-80'
B0DFJ4/116-137'
B0DFJ4/149-170'
B0DFJ4/176-200'
B0DFJ4/221-239'
B0DFJ4/251-272'
B0DFJ4/279-296'
B0DFJ4/302-323'
B0DFJ4/335-356'
B0DFJ4/391-409'
A0A1H3HZ52/15-36'
A0A1H3HZ52/57-74'
A0A1H3HZ52/94-115'
A0A1H3HZ52/127-148'
A0A1H3HZ52/160-183'
A0A1H3HZ52/204-224'
A0A1H3HZ52/236-259'
A0A1H3HZ52/266-284'
A0A1H3HZ52/290-310'
A0A1H3HZ52/322-341'
A0A1H3HZ52/367-388'
A0A1H5WFC4/12-34'
A0A1H5WFC4/55-76'
A0A1H5WFC4/96-116'
A0A1H5WFC4/123-140'
A0A1H5WFC4/160-184'
A0A1H5WFC4/205-223'
A0A1H5WFC4/235-258'
A0A1H5WFC4/265-282'
A0A1H5WFC4/288-309'
A0A1H5WFC4/321-339'
A0A1H5WFC4/369-391'
Q5FLR6/6-28'
Q5FLR6/40-60'
Q5FLR6/97-120'
Q5FLR6/127-148'
Q5FLR6/168-188'
Q5FLR6/200-217'
Q5FLR6/229-249'
Q5FLR6/261-280'
Q5FLR6/286-304'
Q5FLR6/316-336'
Q5FLR6/356-381'
A0A809KDP7/6-28'
A0A809KDP7/40-60'
A0A809KDP7/97-120'
A0A809KDP7/127-148'
A0A809KDP7/168-188'
A0A809KDP7/200-217'
A0A809KDP7/229-249'
A0A809KDP7/261-280'
A0A809KDP7/286-304'
A0A809KDP7/316-336'
A0A809KDP7/356-381'

A0A0U2KG74/6-27'
A0A0U2KG74/39-59'
A0A0U2KG74/96-117'
A0A0U2KG74/124-142'
A0A0U2KG74/162-182'
A0A0U2KG74/194-212'
A0A0U2KG74/224-245'
A0A0U2KG74/257-275'
A0A0U2KG74/281-299'
A0A0U2KG74/311-330'
A0A0U2KG74/356-377'
C1D4X0/81-102'
C1D4X0/114-132'
C1D4X0/173-194'
C1D4X0/201-222'
C1D4X0/242-261'
C1D4X0/273-290'
C1D4X0/302-322'
C1D4X0/334-353'
C1D4X0/359-377'
C1D4X0/389-413'
C1D4X0/419-441'
A0A248LMH8/81-102'
A0A248LMH8/114-132'
A0A248LMH8/173-194'
A0A248LMH8/201-222'
A0A248LMH8/242-261'
A0A248LMH8/273-290'
A0A248LMH8/302-322'
A0A248LMH8/334-353'
A0A248LMH8/359-377'
A0A248LMH8/389-413'
A0A248LMH8/419-441'
A0A248LNK5/9-30'
A0A248LNK5/42-65'
A0A248LNK5/99-123'
A0A248LNK5/130-151'
A0A248LNK5/163-185'
A0A248LNK5/197-217'
A0A248LNK5/229-253'
A0A248LNK5/260-278'
A0A248LNK5/284-303'
A0A248LNK5/315-334'
A0A248LNK5/349-373'
A0A248LNW8/12-32'
A0A248LNW8/53-76'
A0A248LNW8/88-109'
A0A248LNW8/121-139'
A0A248LNW8/159-180'
A0A248LNW8/201-222'
A0A248LNW8/228-251'
A0A248LNW8/258-276'
A0A248LNW8/282-300'
A0A248LNW8/312-335'
A0A248LNW8/347-368'
C1D6X6/9-30'
C1D6X6/42-65'
C1D6X6/99-123'
C1D6X6/130-151'
C1D6X6/163-185'
C1D6X6/197-217'
C1D6X6/229-253'
C1D6X6/260-278'
C1D6X6/284-303'
C1D6X6/315-334'
C1D6X6/349-373'
E4RTK5 has 12 helices, if 12, will use last 11, if other won't include
E4RTK5/43-63'
E4RTK5/75-98'
E4RTK5/123-147'
E4RTK5/159-180'
E4RTK5/192-215'
E4RTK5/227-249'
E4RTK5/261-281'
E4RTK5/293-312'
E4RTK5/318-335'
E4RTK5/347-367'
E4RTK5/387-409'
A0A855EH99/32-54'
A0A855EH99/66-84'
A0A855EH99/120-142'
A0A855EH99/149-171'
A0A855EH99/183-205'
A0A855EH99/217-236'
A0A855EH99/248-268'
A0A855EH99/280-297'
A0A855EH99/303-324'
A0A855EH99/336-355'
A0A855EH99/375-396'
A0A514VEB8/32-54'
A0A514VEB8/66-84'
A0A514VEB8/120-142'
A0A514VEB8/149-171'
A0A514VEB8/183-205'
A0A514VEB8/217-236'
A0A514VEB8/248-268'
A0A514VEB8/280-297'
A0A514VEB8/303-324'
A0A514VEB8/336-355'
A0A514VEB8/375-396'
A3XNG6/29-49'
A3XNG6/70-93'
A3XNG6/113-133'
A3XNG6/140-160'
A3XNG6/172-197'
A3XNG6/218-235'
A3XNG6/255-275'
A3XNG6/282-299'
A3XNG6/305-326'
A3XNG6/338-357'
A3XNG6/377-396'
A0A1E2SKM1/12-32'
A0A1E2SKM1/44-72'
A0A1E2SKM1/92-117'
A0A1E2SKM1/124-145'
A0A1E2SKM1/151-181'
A0A1E2SKM1/193-211'
A0A1E2SKM1/223-243'
A0A1E2SKM1/255-275'
A0A1E2SKM1/281-299'
A0A1E2SKM1/306-327'
A0A1E2SKM1/347-367'
Q6AFC6/12-32'
Q6AFC6/44-72'
Q6AFC6/92-117'
Q6AFC6/124-145'
Q6AFC6/151-181'
Q6AFC6/193-211'
Q6AFC6/223-243'
Q6AFC6/255-275'
Q6AFC6/281-299'
Q6AFC6/306-327'
Q6AFC6/347-367'
U3P8G1/12-32'
U3P8G1/44-62'
U3P8G1/97-117'
U3P8G1/129-150'
U3P8G1/170-188'
U3P8G1/200-220'
U3P8G1/232-252'
U3P8G1/264-281'
U3P8G1/287-306'
U3P8G1/318-341'
U3P8G1/361-386'
U3PCH5/12-31'
U3PCH5/43-71'
U3PCH5/91-116'
U3PCH5/123-144'
U3PCH5/150-180'
U3PCH5/192-210'
U3PCH5/222-242'
U3PCH5/254-274'
U3PCH5/280-298'
U3PCH5/305-326'
U3PCH5/346-366'
A0A1A9F8V6/32-54'
A0A1A9F8V6/66-84'
A0A1A9F8V6/120-142'
A0A1A9F8V6/149-171'
A0A1A9F8V6/183-205'
A0A1A9F8V6/217-236'
A0A1A9F8V6/248-268'
A0A1A9F8V6/280-297'
A0A1A9F8V6/303-324'
A0A1A9F8V6/336-355'
A0A1A9F8V6/375-396'
A0A3S5XY87/32-54'
A0A3S5XY87/66-84'
A0A3S5XY87/120-142'
A0A3S5XY87/149-171'
A0A3S5XY87/183-205'
A0A3S5XY87/217-236'
A0A3S5XY87/248-268'
A0A3S5XY87/280-297'
A0A3S5XY87/303-324'
A0A3S5XY87/336-355'
A0A3S5XY87/375-396'
A0A085HMI3/32-53'
A0A085HMI3/65-83'
A0A085HMI3/119-141'
A0A085HMI3/148-170'
A0A085HMI3/182-204'
A0A085HMI3/216-235'
A0A085HMI3/247-267'
A0A085HMI3/279-298'
A0A085HMI3/304-323'
A0A085HMI3/335-353'
A0A085HMI3/373-395'
A6DN47/102-123'
A6DN47/135-158'
A6DN47/196-215'
A6DN47/222-244'
A6DN47/256-278'
A6DN47/290-314'
A6DN47/326-351'
A6DN47/358-377'
A6DN47/383-402'
A6DN47/414-432'
A6DN47/438-462'
A6DUG4/102-123'
A6DUG4/135-158'
A6DUG4/196-215'
A6DUG4/222-244'
A6DUG4/256-278'
A6DUG4/290-314'
A6DUG4/326-351'
A6DUG4/358-377'
A6DUG4/383-402'
A6DUG4/414-432'
A6DUG4/438-462'
A0A833LX85/59-79'
A0A833LX85/91-114'
A0A833LX85/172-191'
A0A833LX85/198-220'
A0A833LX85/232-253'
A0A833LX85/273-291'
A0A833LX85/303-330'
A0A833LX85/337-357'
A0A833LX85/363-379'
A0A833LX85/391-410'
A0A833LX85/430-455'
A0A833H2R7/47-67'
A0A833H2R7/88-109'
A0A833H2R7/132-153'
A0A833H2R7/165-185'
A0A833H2R7/205-226'
A0A833H2R7/247-264'
A0A833H2R7/276-303'
A0A833H2R7/310-330'
A0A833H2R7/336-355'
A0A833H2R7/362-382'
A0A833H2R7/402-427'
A0A833GZR2/6-28'
A0A833GZR2/49-73'
A0A833GZR2/93-112'
A0A833GZR2/119-140'
A0A833GZR2/160-180'
A0A833GZR2/201-219'
A0A833GZR2/231-252'
A0A833GZR2/264-283'
A0A833GZR2/289-306'
A0A833GZR2/318-339'
A0A833GZR2/351-373'
H2CLF7/59-79'
H2CLF7/91-114'
H2CLF7/172-191'
H2CLF7/198-220'
H2CLF7/232-253'
H2CLF7/273-291'
H2CLF7/303-330'
H2CLF7/337-357'
H2CLF7/363-379'
H2CLF7/391-410'
H2CLF7/430-455'
H2CJI0/6-28'
H2CJI0/49-73'
H2CJI0/93-112'
H2CJI0/119-140'
H2CJI0/160-180'
H2CJI0/201-219'
H2CJI0/231-252'
H2CJI0/264-283'
H2CJI0/289-306'
H2CJI0/318-339'
H2CJI0/351-373'
H2CDR5/47-67'
H2CDR5/88-109'
H2CDR5/132-153'
H2CDR5/165-185'
H2CDR5/205-226'
H2CDR5/247-264'
H2CDR5/276-303'
H2CDR5/310-330'
H2CDR5/336-355'
H2CDR5/362-382'
H2CDR5/402-427'
B0SLB7/40-64'
B0SLB7/76-95'
B0SLB7/126-148'
B0SLB7/155-176'
B0SLB7/188-212'
B0SLB7/224-244'
B0SLB7/256-276'
B0SLB7/288-307'
B0SLB7/313-330'
B0SLB7/342-362'
B0SLB7/374-399'
B0SL05/55-75'
B0SL05/87-105'
B0SL05/157-176'
B0SL05/183-205'
B0SL05/217-238'
B0SL05/259-276'
B0SL05/288-316'
B0SL05/323-341'
B0SL05/347-365'
B0SL05/377-396'
B0SL05/408-433'
B0SRS8/62-82'
B0SRS8/103-124'
B0SRS8/151-173'
B0SRS8/180-208'
B0SRS8/228-250'
B0SRS8/262-283'
B0SRS8/303-326'
B0SRS8/331-348'
B0SRS8/354-375'
B0SRS8/387-404'
B0SRS8/416-444'
A0A094W9G3/70-93'
A0A094W9G3/105-125'
A0A094W9G3/164-183'
A0A094W9G3/190-212'
A0A094W9G3/224-245'
A0A094W9G3/266-283'
A0A094W9G3/298-325'
A0A094W9G3/332-352'
A0A094W9G3/358-374'
A0A094W9G3/386-405'
A0A094W9G3/425-453'
A0A1V3SSW1 has 12 helices, if 12, will use last 11, if other won't include
A0A1V3SSW1/94-118'
A0A1V3SSW1/130-150'
A0A1V3SSW1/189-208'
A0A1V3SSW1/215-237'
A0A1V3SSW1/249-270'
A0A1V3SSW1/291-308'
A0A1V3SSW1/323-350'
A0A1V3SSW1/357-377'
A0A1V3SSW1/383-399'
A0A1V3SSW1/411-430'
A0A1V3SSW1/450-478'
A0A2I2MEF2/55-78'
A0A2I2MEF2/90-110'
A0A2I2MEF2/149-168'
A0A2I2MEF2/175-197'
A0A2I2MEF2/209-230'
A0A2I2MEF2/251-268'
A0A2I2MEF2/283-310'
A0A2I2MEF2/317-337'
A0A2I2MEF2/343-359'
A0A2I2MEF2/371-390'
A0A2I2MEF2/410-438'
A0A7C3QR70/12-34'
A0A7C3QR70/46-65'
A0A7C3QR70/110-129'
A0A7C3QR70/136-158'
A0A7C3QR70/170-191'
A0A7C3QR70/203-221'
A0A7C3QR70/241-260'
A0A7C3QR70/267-285'
A0A7C3QR70/291-311'
A0A7C3QR70/332-350'
A0A7C3QR70/370-392'
A0A059XYD5 has 12 helices, if 12, will use last 11, if other won't include
A0A059XYD5/94-118'
A0A059XYD5/130-150'
A0A059XYD5/189-208'
A0A059XYD5/215-237'
A0A059XYD5/249-270'
A0A059XYD5/291-308'
A0A059XYD5/323-350'
A0A059XYD5/357-377'
A0A059XYD5/383-399'
A0A059XYD5/411-430'
A0A059XYD5/450-478'
J9ZB82 has 12 helices, if 12, will use last 11, if other won't include
J9ZB82/94-118'
J9ZB82/130-150'
J9ZB82/189-208'
J9ZB82/215-237'
J9ZB82/249-270'
J9ZB82/291-308'
J9ZB82/323-350'
J9ZB82/357-377'
J9ZB82/383-399'
J9ZB82/411-430'
J9ZB82/450-478'
J9Z839/12-34'
J9Z839/46-65'
J9Z839/110-129'
J9Z839/136-158'
J9Z839/170-191'
J9Z839/203-221'
J9Z839/241-260'
J9Z839/267-285'
J9Z839/291-311'
J9Z839/332-350'
J9Z839/370-392'
A0A7C3LUF9/48-72'
A0A7C3LUF9/84-104'
A0A7C3LUF9/143-162'
A0A7C3LUF9/169-191'
A0A7C3LUF9/203-224'
A0A7C3LUF9/245-262'
A0A7C3LUF9/277-304'
A0A7C3LUF9/311-331'
A0A7C3LUF9/337-353'
A0A7C3LUF9/365-384'
A0A7C3LUF9/404-432'
A0A059XXR1/12-34'
A0A059XXR1/46-65'
A0A059XXR1/110-129'
A0A059XXR1/136-158'
A0A059XXR1/170-191'
A0A059XXR1/203-221'
A0A059XXR1/241-260'
A0A059XXR1/267-285'
A0A059XXR1/291-311'
A0A059XXR1/332-350'
A0A059XXR1/370-392'
A0A094YPF5/12-34'
A0A094YPF5/46-65'
A0A094YPF5/110-129'
A0A094YPF5/136-158'
A0A094YPF5/170-191'
A0A094YPF5/203-221'
A0A094YPF5/241-260'
A0A094YPF5/267-285'
A0A094YPF5/291-311'
A0A094YPF5/332-350'
A0A094YPF5/370-392'
B1Y8C9/68-89'
B1Y8C9/101-119'
B1Y8C9/166-188'
B1Y8C9/195-219'
B1Y8C9/239-268'
B1Y8C9/280-301'
B1Y8C9/313-333'
B1Y8C9/345-362'
B1Y8C9/368-389'
B1Y8C9/401-419'
B1Y8C9/450-472'
B1Y6V4/48-69'
B1Y6V4/81-99'
B1Y6V4/138-160'
B1Y6V4/167-186'
B1Y6V4/206-224'
B1Y6V4/245-263'
B1Y6V4/269-291'
B1Y6V4/298-315'
B1Y6V4/321-339'
B1Y6V4/351-374'
B1Y6V4/394-414'
B1Y0E5/44-66'
B1Y0E5/78-100'
B1Y0E5/142-162'
B1Y0E5/169-190'
B1Y0E5/210-229'
B1Y0E5/241-258'
B1Y0E5/270-289'
B1Y0E5/301-319'
B1Y0E5/325-345'
B1Y0E5/357-376'
B1Y0E5/396-416'
B1XZU2/6-32'
B1XZU2/44-63'
B1XZU2/90-109'
B1XZU2/116-135'
B1XZU2/155-173'
B1XZU2/193-210'
B1XZU2/222-245'
B1XZU2/252-272'
B1XZU2/278-295'
B1XZU2/307-328'
B1XZU2/340-360'

B1Y842/12-35'
B1Y842/47-69'
B1Y842/89-108'
B1Y842/117-137'
B1Y842/157-180'
B1Y842/201-219'
B1Y842/231-253'
B1Y842/260-278'
B1Y842/284-302'
B1Y842/314-337'
B1Y842/349-370'
A0A1H1BPD6/12-31'
A0A1H1BPD6/38-58'
A0A1H1BPD6/88-108'
A0A1H1BPD6/120-140'
A0A1H1BPD6/160-182'
A0A1H1BPD6/194-214'
A0A1H1BPD6/226-246'
A0A1H1BPD6/255-274'
A0A1H1BPD6/280-299'
A0A1H1BPD6/311-331'
A0A1H1BPD6/343-369'
A0A147EQL9/12-31'
A0A147EQL9/38-58'
A0A147EQL9/88-108'
A0A147EQL9/120-140'
A0A147EQL9/160-182'
A0A147EQL9/194-214'
A0A147EQL9/226-246'
A0A147EQL9/255-274'
A0A147EQL9/280-299'
A0A147EQL9/311-331'
A0A147EQL9/343-369'
D5T4N9/6-28'
D5T4N9/40-62'
D5T4N9/96-117'
D5T4N9/124-146'
D5T4N9/158-180'
D5T4N9/192-209'
D5T4N9/215-238'
D5T4N9/250-270'
D5T4N9/276-296'
D5T4N9/308-326'
D5T4N9/346-367'
A0A7V2SZE0/32-54'
A0A7V2SZE0/66-88'
A0A7V2SZE0/120-141'
A0A7V2SZE0/148-169'
A0A7V2SZE0/189-207'
A0A7V2SZE0/219-237'
A0A7V2SZE0/249-268'
A0A7V2SZE0/280-298'
A0A7V2SZE0/304-324'
A0A7V2SZE0/336-356'
A0A7V2SZE0/376-401'
A0A7V2T108/12-33'
A0A7V2T108/54-72'
A0A7V2T108/92-114'
A0A7V2T108/121-143'
A0A7V2T108/163-184'
A0A7V2T108/216-233'
A0A7V2T108/245-267'
A0A7V2T108/274-295'
A0A7V2T108/301-320'
A0A7V2T108/332-350'
A0A7V2T108/362-389'
A0AIW5/6-25'
A0AIW5/37-59'
A0AIW5/93-115'
A0AIW5/122-142'
A0AIW5/162-179'
A0AIW5/191-209'
A0AIW5/221-241'
A0AIW5/253-273'
A0AIW5/279-296'
A0AIW5/308-331'
A0AIW5/351-376'
A0A7X0WHY1/6-25'
A0A7X0WHY1/37-59'
A0A7X0WHY1/93-115'
A0A7X0WHY1/122-142'
A0A7X0WHY1/162-179'
A0A7X0WHY1/191-209'
A0A7X0WHY1/221-241'
A0A7X0WHY1/253-273'
A0A7X0WHY1/279-296'
A0A7X0WHY1/308-331'
A0A7X0WHY1/351-376'
A0A842BMP4/6-25'
A0A842BMP4/37-59'
A0A842BMP4/93-115'
A0A842BMP4/122-142'
A0A842BMP4/162-179'
A0A842BMP4/191-209'
A0A842BMP4/221-241'
A0A842BMP4/253-273'
A0A842BMP4/279-296'
A0A842BMP4/308-331'
A0A842BMP4/351-376'
A0A660JU19/6-25'
A0A660JU19/37-59'
A0A660JU19/93-115'
A0A660JU19/122-142'
A0A660JU19/162-179'
A0A660JU19/191-209'
A0A660JU19/221-241'
A0A660JU19/253-273'
A0A660JU19/279-296'
A0A660JU19/308-331'
A0A660JU19/351-376'
H1GDT6/6-25'
H1GDT6/37-59'
H1GDT6/93-115'
H1GDT6/122-142'
H1GDT6/162-179'
H1GDT6/191-209'
H1GDT6/221-241'
H1GDT6/253-273'
H1GDT6/279-296'
H1GDT6/308-331'
H1GDT6/351-376'
Q92BJ7/6-25'
Q92BJ7/37-59'
Q92BJ7/93-115'
Q92BJ7/122-142'
Q92BJ7/162-179'
Q92BJ7/191-209'
Q92BJ7/221-241'
Q92BJ7/253-273'
Q92BJ7/279-296'
Q92BJ7/308-331'
Q92BJ7/351-376'
A5DYQ2/26-48'
A5DYQ2/60-78'
A5DYQ2/117-139'
A5DYQ2/146-168'
A5DYQ2/188-205'
A5DYQ2/217-237'
A5DYQ2/249-270'
A5DYQ2/277-295'
A5DYQ2/301-319'
A5DYQ2/340-359'
A5DYQ2/379-404'
A5E3X2/29-50'
A5E3X2/62-85'
A5E3X2/105-136'
A5E3X2/148-168'
A5E3X2/174-202'
A5E3X2/223-240'
A5E3X2/252-273'
A5E3X2/285-302'
A5E3X2/308-327'
A5E3X2/339-362'
A5E3X2/382-406'
A5E1S5 has 13 helices, if 12, will use last 11, if other won't include
A5E1S5/153-170'
A5E1S5/182-201'
A5E1S5/213-233'
A5E1S5/245-264'
A5E1S5/276-294'
A5E1S5/314-332'
A5E1S5/352-370'
A5E1S5/377-395'
A5E1S5/407-431'
A5E1S5/443-465'
A5E1S5/485-505'
A0A1H3WA00/32-56'
A0A1H3WA00/68-88'
A0A1H3WA00/119-140'
A0A1H3WA00/147-165'
A0A1H3WA00/185-207'
A0A1H3WA00/219-238'
A0A1H3WA00/250-270'
A0A1H3WA00/282-301'
A0A1H3WA00/307-326'
A0A1H3WA00/338-356'
A0A1H3WA00/376-398'
A0A1X3RP39/36-60'
A0A1X3RP39/72-99'
A0A1X3RP39/119-140'
A0A1X3RP39/147-165'
A0A1X3RP39/185-207'
A0A1X3RP39/219-238'
A0A1X3RP39/250-270'
A0A1X3RP39/282-301'
A0A1X3RP39/307-326'
A0A1X3RP39/338-356'
A0A1X3RP39/376-398'
A0A1X3RR37/36-60'
A0A1X3RR37/72-99'
A0A1X3RR37/119-140'
A0A1X3RR37/147-165'
A0A1X3RR37/185-207'
A0A1X3RR37/219-238'
A0A1X3RR37/250-270'
A0A1X3RR37/282-301'
A0A1X3RR37/307-326'
A0A1X3RR37/338-356'
A0A1X3RR37/376-398'
V4CRP5/30-53'
V4CRP5/65-83'
V4CRP5/111-133'
V4CRP5/140-162'
V4CRP5/174-197'
V4CRP5/218-241'
V4CRP5/253-274'
V4CRP5/281-302'
V4CRP5/308-325'
V4CRP5/337-356'
V4CRP5/376-404'
V3ZVE4/22-43'
V3ZVE4/55-73'
V3ZVE4/111-130'
V3ZVE4/137-157'
V3ZVE4/169-192'
V3ZVE4/213-235'
V3ZVE4/247-268'
V3ZVE4/275-297'
V3ZVE4/303-319'
V3ZVE4/331-349'
V3ZVE4/376-398'
V4AP67/31-50'
V4AP67/71-89'
V4AP67/109-129'
V4AP67/136-154'
V4AP67/174-195'
V4AP67/216-237'
V4AP67/249-271'
V4AP67/280-296'
V4AP67/302-322'
V4AP67/334-355'
V4AP67/375-398'
V4A9D7/20-40'
V4A9D7/60-80'
V4A9D7/100-122'
V4A9D7/129-150'
V4A9D7/162-188'
V4A9D7/214-233'
V4A9D7/253-275'
V4A9D7/287-306'
V4A9D7/312-334'
V4A9D7/346-370'
V4A9D7/382-405'
A0A562BXM4/91-113'
A0A562BXM4/125-145'
A0A562BXM4/180-198'
A0A562BXM4/210-231'
A0A562BXM4/243-265'
A0A562BXM4/277-296'
A0A562BXM4/308-329'
A0A562BXM4/341-358'
A0A562BXM4/364-384'
A0A562BXM4/396-416'
A0A562BXM4/436-461'
A0A839WU60/51-72'
A0A839WU60/84-102'
A0A839WU60/139-161'
A0A839WU60/168-189'
A0A839WU60/201-226'
A0A839WU60/238-258'
A0A839WU60/270-290'
A0A839WU60/302-319'
A0A839WU60/325-345'
A0A839WU60/357-375'
A0A839WU60/395-417'
A0A853JAB6/81-103'
A0A853JAB6/115-133'
A0A853JAB6/170-188'
A0A853JAB6/195-215'
A0A853JAB6/235-257'
A0A853JAB6/269-289'
A0A853JAB6/301-321'
A0A853JAB6/333-350'
A0A853JAB6/356-376'
A0A853JAB6/388-408'
A0A853JAB6/428-448'
A0A5C5TYS5/89-111'
A0A5C5TYS5/123-141'
A0A5C5TYS5/178-200'
A0A5C5TYS5/207-228'
A0A5C5TYS5/240-265'
A0A5C5TYS5/277-297'
A0A5C5TYS5/309-329'
A0A5C5TYS5/341-358'
A0A5C5TYS5/364-384'
A0A5C5TYS5/396-416'
A0A5C5TYS5/436-457'
A0A290XBB5/61-83'
A0A290XBB5/95-113'
A0A290XBB5/150-172'
A0A290XBB5/179-200'
A0A290XBB5/212-237'
A0A290XBB5/249-269'
A0A290XBB5/281-301'
A0A290XBB5/313-330'
A0A290XBB5/336-356'
A0A290XBB5/368-388'
A0A290XBB5/408-433'
A0A653N397/61-83'
A0A653N397/95-113'
A0A653N397/150-172'
A0A653N397/179-200'
A0A653N397/212-237'
A0A653N397/249-269'
A0A653N397/281-301'
A0A653N397/313-330'
A0A653N397/336-356'
A0A653N397/368-388'
A0A653N397/408-433'
A0A4R5U5V1/69-91'
A0A4R5U5V1/103-121'
A0A4R5U5V1/158-180'
A0A4R5U5V1/187-208'
A0A4R5U5V1/220-245'
A0A4R5U5V1/257-277'
A0A4R5U5V1/289-309'
A0A4R5U5V1/321-338'
A0A4R5U5V1/344-364'
A0A4R5U5V1/376-400'
A0A4R5U5V1/412-437'
A0A7Z0QPG3/71-93'
A0A7Z0QPG3/105-123'
A0A7Z0QPG3/160-178'
A0A7Z0QPG3/185-205'
A0A7Z0QPG3/225-247'
A0A7Z0QPG3/259-279'
A0A7Z0QPG3/291-310'
A0A7Z0QPG3/322-340'
A0A7Z0QPG3/346-366'
A0A7Z0QPG3/378-398'
A0A7Z0QPG3/410-436'
A0A5C5TUT2/91-113'
A0A5C5TUT2/125-145'
A0A5C5TUT2/180-198'
A0A5C5TUT2/210-231'
A0A5C5TUT2/243-265'
A0A5C5TUT2/277-296'
A0A5C5TUT2/308-329'
A0A5C5TUT2/341-358'
A0A5C5TUT2/364-384'
A0A5C5TUT2/396-416'
A0A5C5TUT2/436-461'
A0A4V3ALP8/83-105'
A0A4V3ALP8/117-135'
A0A4V3ALP8/172-194'
A0A4V3ALP8/201-222'
A0A4V3ALP8/234-259'
A0A4V3ALP8/271-291'
A0A4V3ALP8/303-323'
A0A4V3ALP8/335-352'
A0A4V3ALP8/358-378'
A0A4V3ALP8/390-410'
A0A4V3ALP8/430-455'
V4REY8/62-84'
V4REY8/105-124'
V4REY8/156-175'
V4REY8/180-197'
V4REY8/217-237'
V4REY8/257-274'
V4REY8/294-313'
V4REY8/320-338'
V4REY8/344-366'
V4REY8/378-395'
V4REY8/401-426'
V4RK08/29-46'
V4RK08/66-84'
V4RK08/117-139'
V4RK08/146-167'
V4RK08/182-203'
V4RK08/224-250'
V4RK08/262-283'
V4RK08/290-307'
V4RK08/313-333'
V4RK08/345-366'
V4RK08/381-402'
V4RHR4/15-34'
V4RHR4/54-73'
V4RHR4/108-130'
V4RHR4/137-161'
V4RHR4/173-195'
V4RHR4/216-241'
V4RHR4/261-287'
V4RHR4/294-311'
V4RHR4/317-334'
V4RHR4/346-368'
V4RHR4/388-410'
F4XTK4 has 12 helices, if 12, will use last 11, if other won't include
F4XTK4/79-96'
F4XTK4/117-136'
F4XTK4/169-190'
F4XTK4/197-214'
F4XTK4/234-255'
F4XTK4/275-292'
F4XTK4/304-328'
F4XTK4/335-352'
F4XTK4/358-379'
F4XTK4/391-409'
F4XTK4/429-448'
F4Y3C5/25-45'
F4Y3C5/66-85'
F4Y3C5/140-161'
F4Y3C5/168-186'
F4Y3C5/206-227'
F4Y3C5/256-273'
F4Y3C5/293-311'
F4Y3C5/318-336'
F4Y3C5/342-359'
F4Y3C5/371-393'
F4Y3C5/413-441'
A0A2S5CTX8/6-27'
A0A2S5CTX8/48-68'
A0A2S5CTX8/88-108'
A0A2S5CTX8/115-138'
A0A2S5CTX8/150-173'
A0A2S5CTX8/185-210'
A0A2S5CTX8/222-244'
A0A2S5CTX8/256-275'
A0A2S5CTX8/281-298'
A0A2S5CTX8/310-328'
A0A2S5CTX8/348-369'
A0A2S0JW39/6-27'
A0A2S0JW39/48-68'
A0A2S0JW39/88-108'
A0A2S0JW39/115-138'
A0A2S0JW39/150-173'
A0A2S0JW39/185-206'
A0A2S0JW39/226-244'
A0A2S0JW39/256-275'
A0A2S0JW39/281-298'
A0A2S0JW39/310-328'
A0A2S0JW39/348-369'
A0A0S2FHD7/6-23'
A0A0S2FHD7/30-50'
A0A0S2FHD7/92-114'
A0A0S2FHD7/121-142'
A0A0S2FHD7/154-179'
A0A0S2FHD7/191-211'
A0A0S2FHD7/223-241'
A0A0S2FHD7/253-271'
A0A0S2FHD7/277-298'
A0A0S2FHD7/310-333'
A0A0S2FHD7/353-378'
A0A0S2DQB6/61-83'
A0A0S2DQB6/95-113'
A0A0S2DQB6/155-175'
A0A0S2DQB6/182-200'
A0A0S2DQB6/220-242'
A0A0S2DQB6/254-274'
A0A0S2DQB6/286-304'
A0A0S2DQB6/316-334'
A0A0S2DQB6/340-361'
A0A0S2DQB6/373-396'
A0A0S2DQB6/416-441'
Q2WBF7/47-73'
Q2WBF7/85-105'
Q2WBF7/138-159'
Q2WBF7/166-187'
Q2WBF7/207-228'
Q2WBF7/240-261'
Q2WBF7/273-293'
Q2WBF7/305-324'
Q2WBF7/330-348'
Q2WBF7/360-380'
Q2WBF7/400-419'

Q2W5V2/31-51'
Q2W5V2/72-94'
Q2W5V2/114-133'
Q2W5V2/145-165'
Q2W5V2/185-208'
Q2W5V2/229-249'
Q2W5V2/255-277'
Q2W5V2/284-302'
Q2W5V2/308-326'
Q2W5V2/338-357'
Q2W5V2/369-391'
F3ZYD6/38-57'
F3ZYD6/78-102'
F3ZYD6/122-141'
F3ZYD6/153-174'
F3ZYD6/186-207'
F3ZYD6/228-245'
F3ZYD6/257-282'
F3ZYD6/289-309'
F3ZYD6/315-333'
F3ZYD6/345-365'
F3ZYD6/377-403'
F3ZVV4 has 12 helices, if 12, will use last 11, if other won't include
F3ZVV4/40-62'
F3ZVV4/69-89'
F3ZVV4/132-152'
F3ZVV4/159-180'
F3ZVV4/192-214'
F3ZVV4/226-247'
F3ZVV4/259-279'
F3ZVV4/291-311'
F3ZVV4/317-335'
F3ZVV4/347-366'
F3ZVV4/386-408'
A8PXT8/28-52'
A8PXT8/59-79'
A8PXT8/117-140'
A8PXT8/147-164'
A8PXT8/184-203'
A8PXT8/224-244'
A8PXT8/250-271'
A8PXT8/283-302'
A8PXT8/308-324'
A8PXT8/336-355'
A8PXT8/381-405'
A0A495DND0/50-72'
A0A495DND0/84-106'
A0A495DND0/141-162'
A0A495DND0/169-191'
A0A495DND0/203-224'
A0A495DND0/236-257'
A0A495DND0/269-288'
A0A495DND0/300-318'
A0A495DND0/324-344'
A0A495DND0/356-376'
A0A495DND0/396-417'
A0A495D4X4/41-61'
A0A495D4X4/81-100'
A0A495D4X4/136-155'
A0A495D4X4/160-177'
A0A495D4X4/197-220'
A0A495D4X4/232-254'
A0A495D4X4/274-296'
A0A495D4X4/303-319'
A0A495D4X4/325-343'
A0A495D4X4/355-376'
A0A495D4X4/382-407'
Q0AT01/41-61'
Q0AT01/81-100'
Q0AT01/136-155'
Q0AT01/160-177'
Q0AT01/197-220'
Q0AT01/232-254'
Q0AT01/274-296'
Q0AT01/303-319'
Q0AT01/325-343'
Q0AT01/355-376'
Q0AT01/382-407'
Q0ARJ4/6-29'
Q0ARJ4/41-63'
Q0ARJ4/98-119'
Q0ARJ4/126-148'
Q0ARJ4/160-181'
Q0ARJ4/193-214'
Q0ARJ4/226-245'
Q0ARJ4/257-275'
Q0ARJ4/281-301'
Q0ARJ4/313-333'
Q0ARJ4/353-374'
W0DZS7/41-63'
W0DZS7/70-90'
W0DZS7/130-151'
W0DZS7/158-180'
W0DZS7/192-214'
W0DZS7/226-246'
W0DZS7/258-277'
W0DZS7/289-307'
W0DZS7/313-331'
W0DZS7/343-365'
W0DZS7/385-407'
W0E077/6-25'
W0E077/37-61'
W0E077/81-103'
W0E077/110-131'
W0E077/151-172'
W0E077/193-210'
W0E077/225-245'
W0E077/257-275'
W0E077/281-301'
W0E077/308-331'
W0E077/343-368'
W0DYY3/14-38'
W0DYY3/50-69'
W0DYY3/109-127'
W0DYY3/134-154'
W0DYY3/174-192'
W0DYY3/204-225'
W0DYY3/245-271'
W0DYY3/278-295'
W0DYY3/301-320'
W0DYY3/332-349'
W0DYY3/355-380'
W0DZX1/12-35'
W0DZX1/47-69'
W0DZX1/89-108'
W0DZX1/117-137'
W0DZX1/157-178'
W0DZX1/199-220'
W0DZX1/226-249'
W0DZX1/256-274'
W0DZX1/280-298'
W0DZX1/310-333'
W0DZX1/345-366'
A0A1T4SFY6/6-28'
A0A1T4SFY6/40-62'
A0A1T4SFY6/97-119'
A0A1T4SFY6/126-147'
A0A1T4SFY6/153-183'
A0A1T4SFY6/195-215'
A0A1T4SFY6/227-247'
A0A1T4SFY6/256-276'
A0A1T4SFY6/282-301'
A0A1T4SFY6/313-332'
A0A1T4SFY6/352-375'
A0A2T0XPP2/17-37'
A0A2T0XPP2/58-79'
A0A2T0XPP2/99-121'
A0A2T0XPP2/128-150'
A0A2T0XPP2/162-184'
A0A2T0XPP2/196-216'
A0A2T0XPP2/236-260'
A0A2T0XPP2/267-284'
A0A2T0XPP2/290-308'
A0A2T0XPP2/320-341'
A0A2T0XPP2/353-377'
M7XJ51/34-53'
M7XJ51/74-93'
M7XJ51/133-152'
M7XJ51/159-178'
M7XJ51/198-219'
M7XJ51/231-251'
M7XJ51/263-288'
M7XJ51/295-313'
M7XJ51/319-340'
M7XJ51/347-368'
M7XJ51/380-401'
F2NNQ0/30-54'
F2NNQ0/66-86'
F2NNQ0/118-137'
F2NNQ0/144-164'
F2NNQ0/176-197'
F2NNQ0/209-230'
F2NNQ0/242-263'
F2NNQ0/270-292'
F2NNQ0/298-316'
F2NNQ0/328-351'
F2NNQ0/371-391'
F2JYR9/33-53'
F2JYR9/65-87'
F2JYR9/119-141'
F2JYR9/148-169'
F2JYR9/189-207'
F2JYR9/228-251'
F2JYR9/266-285'
F2JYR9/292-309'
F2JYR9/315-332'
F2JYR9/344-367'
F2JYR9/379-401'
F2JZ83/18-37'
F2JZ83/58-79'
F2JZ83/91-111'
F2JZ83/123-144'
F2JZ83/164-185'
F2JZ83/197-221'
F2JZ83/233-255'
F2JZ83/262-280'
F2JZ83/286-304'
F2JZ83/316-336'
F2JZ83/348-370'
F2JTN3/14-38'
F2JTN3/50-69'
F2JTN3/110-128'
F2JTN3/135-156'
F2JTN3/176-197'
F2JTN3/218-235'
F2JTN3/255-274'
F2JTN3/281-299'
F2JTN3/305-327'
F2JTN3/339-356'
F2JTN3/362-387'
Q0F2M7/34-55'
Q0F2M7/67-90'
Q0F2M7/122-143'
Q0F2M7/150-172'
Q0F2M7/184-205'
Q0F2M7/217-238'
Q0F2M7/250-269'
Q0F2M7/281-299'
Q0F2M7/305-325'
Q0F2M7/337-356'
Q0F2M7/376-397'
Q0F2M5/6-28'
Q0F2M5/49-71'
Q0F2M5/91-109'
Q0F2M5/116-139'
Q0F2M5/159-181'
Q0F2M5/193-218'
Q0F2M5/230-251'
Q0F2M5/258-276'
Q0F2M5/282-300'
Q0F2M5/312-331'
Q0F2M5/343-368'
A0A2R4MBA2/6-28'
A0A2R4MBA2/40-63'
A0A2R4MBA2/95-116'
A0A2R4MBA2/123-145'
A0A2R4MBA2/157-180'
A0A2R4MBA2/192-211'
A0A2R4MBA2/223-247'
A0A2R4MBA2/254-272'
A0A2R4MBA2/278-298'
A0A2R4MBA2/310-332'
A0A2R4MBA2/352-372'
E4TRS4/42-65'
E4TRS4/77-97'
E4TRS4/132-151'
E4TRS4/158-177'
E4TRS4/197-218'
E4TRS4/230-250'
E4TRS4/262-287'
E4TRS4/294-312'
E4TRS4/318-338'
E4TRS4/350-368'
E4TRS4/380-401'
A0A4R3NVT3/49-74'
A0A4R3NVT3/86-105'
A0A4R3NVT3/140-159'
A0A4R3NVT3/164-181'
A0A4R3NVT3/201-221'
A0A4R3NVT3/242-259'
A0A4R3NVT3/279-302'
A0A4R3NVT3/309-326'
A0A4R3NVT3/332-352'
A0A4R3NVT3/359-380'
A0A4R3NVT3/386-411'
A0A1U9YY82/49-69'
A0A1U9YY82/89-108'
A0A1U9YY82/142-161'
A0A1U9YY82/166-183'
A0A1U9YY82/203-223'
A0A1U9YY82/244-261'
A0A1U9YY82/281-304'
A0A1U9YY82/311-328'
A0A1U9YY82/334-354'
A0A1U9YY82/361-380'
A0A1U9YY82/392-413'
A0A1U9Z147/6-34'
A0A1U9Z147/46-74'
A0A1U9Z147/94-118'
A0A1U9Z147/130-152'
A0A1U9Z147/164-186'
A0A1U9Z147/198-219'
A0A1U9Z147/231-252'
A0A1U9Z147/259-280'
A0A1U9Z147/286-305'
A0A1U9Z147/317-338'
A0A1U9Z147/350-372'
C6LBD3/32-53'
C6LBD3/74-97'
C6LBD3/117-134'
C6LBD3/141-158'
C6LBD3/178-198'
C6LBD3/219-241'
C6LBD3/253-276'
C6LBD3/283-300'
C6LBD3/306-327'
C6LBD3/339-358'
C6LBD3/394-419'
A0A7C3HEP6/30-52'
A0A7C3HEP6/64-86'
A0A7C3HEP6/121-143'
A0A7C3HEP6/150-172'
A0A7C3HEP6/184-205'
A0A7C3HEP6/217-238'
A0A7C3HEP6/244-267'
A0A7C3HEP6/279-299'
A0A7C3HEP6/305-324'
A0A7C3HEP6/336-355'
A0A7C3HEP6/375-396'
D3PKL4/30-52'
D3PKL4/64-86'
D3PKL4/121-143'
D3PKL4/150-172'
D3PKL4/184-205'
D3PKL4/217-238'
D3PKL4/244-267'
D3PKL4/279-299'
D3PKL4/305-324'
D3PKL4/336-355'
D3PKL4/375-396'
I6Z905/46-68'
I6Z905/89-108'
I6Z905/128-147'
I6Z905/154-172'
I6Z905/192-216'
I6Z905/237-254'
I6Z905/266-292'
I6Z905/299-319'
I6Z905/325-341'
I6Z905/353-371'
I6Z905/383-403'
I6YYI6/20-40'
I6YYI6/52-75'
I6YYI6/113-132'
I6YYI6/139-161'
I6YYI6/173-194'
I6YYI6/214-231'
I6YYI6/243-270'
I6YYI6/277-295'
I6YYI6/301-319'
I6YYI6/331-351'
I6YYI6/357-379'
A0A2T1N7R1/6-30'
A0A2T1N7R1/42-65'
A0A2T1N7R1/107-126'
A0A2T1N7R1/133-152'
A0A2T1N7R1/172-189'
A0A2T1N7R1/201-222'
A0A2T1N7R1/242-264'
A0A2T1N7R1/271-289'
A0A2T1N7R1/295-313'
A0A2T1N7R1/325-343'
A0A2T1N7R1/355-376'
L0KGR8/57-80'
L0KGR8/87-108'
L0KGR8/151-173'
L0KGR8/180-202'
L0KGR8/214-235'
L0KGR8/247-268'
L0KGR8/280-299'
L0KGR8/311-331'
L0KGR8/337-355'
L0KGR8/367-390'
L0KGR8/402-424'
A0A088E6Q7/25-46'
A0A088E6Q7/58-79'
A0A088E6Q7/122-145'
A0A088E6Q7/152-174'
A0A088E6Q7/186-207'
A0A088E6Q7/219-239'
A0A088E6Q7/251-272'
A0A088E6Q7/284-303'
A0A088E6Q7/309-327'
A0A088E6Q7/339-357'
A0A088E6Q7/377-402'
A4YGZ2/25-46'
A4YGZ2/58-79'
A4YGZ2/122-145'
A4YGZ2/152-174'
A4YGZ2/186-207'
A4YGZ2/219-239'
A4YGZ2/251-272'
A4YGZ2/284-303'
A4YGZ2/309-327'
A4YGZ2/339-357'
A4YGZ2/377-402'
B9ACS5/12-32'
B9ACS5/44-66'
B9ACS5/99-121'
B9ACS5/128-150'
B9ACS5/162-184'
B9ACS5/196-213'
B9ACS5/225-246'
B9ACS5/255-276'
B9ACS5/282-300'
B9ACS5/312-335'
B9ACS5/347-371'
D2ZRW2/12-32'
D2ZRW2/44-66'
D2ZRW2/99-121'
D2ZRW2/128-150'
D2ZRW2/162-184'
D2ZRW2/196-213'
D2ZRW2/225-246'
D2ZRW2/255-276'
D2ZRW2/282-300'
D2ZRW2/312-335'
D2ZRW2/347-371'
A0A2H4U5R1/12-32'
A0A2H4U5R1/44-66'
A0A2H4U5R1/99-121'
A0A2H4U5R1/128-150'
A0A2H4U5R1/162-184'
A0A2H4U5R1/196-213'
A0A2H4U5R1/225-246'
A0A2H4U5R1/255-276'
A0A2H4U5R1/282-300'
A0A2H4U5R1/312-335'
A0A2H4U5R1/347-371'
R7PZ71/12-32'
R7PZ71/44-66'
R7PZ71/99-121'
R7PZ71/128-150'
R7PZ71/162-184'
R7PZ71/196-213'
R7PZ71/225-246'
R7PZ71/255-276'
R7PZ71/282-300'
R7PZ71/312-335'
R7PZ71/347-371'
A5UJR1/12-32'
A5UJR1/44-66'
A5UJR1/99-121'
A5UJR1/128-150'
A5UJR1/162-184'
A5UJR1/196-213'
A5UJR1/225-246'
A5UJR1/255-276'
A5UJR1/282-300'
A5UJR1/312-335'
A5UJR1/347-371'
Q58739/34-54'
Q58739/71-91'
Q58739/120-140'
Q58739/149-169'
Q58739/180-200'
Q58739/220-240'
Q58739/250-270'
Q58739/273-293'
Q58739/295-315'
Q58739/339-359'
Q58739/365-385'
A0A832WGB6/29-49'
A0A832WGB6/70-95'
A0A832WGB6/115-135'
A0A832WGB6/142-162'
A0A832WGB6/174-196'
A0A832WGB6/208-231'
A0A832WGB6/243-263'
A0A832WGB6/270-288'
A0A832WGB6/294-314'
A0A832WGB6/326-348'
A0A832WGB6/360-388'
G0H0Z6/26-46'
G0H0Z6/67-85'
G0H0Z6/111-133'
G0H0Z6/140-160'
G0H0Z6/172-193'
G0H0Z6/213-230'
G0H0Z6/236-256'
G0H0Z6/268-288'
G0H0Z6/294-312'
G0H0Z6/324-346'
G0H0Z6/358-379'
A0A7J9P8J7/26-46'
A0A7J9P8J7/67-85'
A0A7J9P8J7/111-133'
A0A7J9P8J7/140-160'
A0A7J9P8J7/172-193'
A0A7J9P8J7/213-230'
A0A7J9P8J7/236-256'
A0A7J9P8J7/268-288'
A0A7J9P8J7/294-312'
A0A7J9P8J7/324-346'
A0A7J9P8J7/358-379'

A2SS52/6-28'
A2SS52/40-63'
A2SS52/95-117'
A2SS52/124-146'
A2SS52/158-180'
A2SS52/192-212'
A2SS52/224-243'
A2SS52/255-272'
A2SS52/278-297'
A2SS52/318-339'
A2SS52/345-371'
A2SPS8/12-32'
A2SPS8/44-77'
A2SPS8/97-120'
A2SPS8/127-148'
A2SPS8/160-182'
A2SPS8/194-214'
A2SPS8/226-247'
A2SPS8/259-277'
A2SPS8/283-301'
A2SPS8/313-340'
A2SPS8/352-373'
A0A831PTC2/45-65'
A0A831PTC2/86-105'
A0A831PTC2/132-151'
A0A831PTC2/158-180'
A0A831PTC2/192-213'
A0A831PTC2/234-251'
A0A831PTC2/263-288'
A0A831PTC2/295-315'
A0A831PTC2/321-339'
A0A831PTC2/360-382'
A0A831PTC2/388-413'
A0A831LSC0/12-31'
A0A831LSC0/38-58'
A0A831LSC0/91-112'
A0A831LSC0/124-145'
A0A831LSC0/157-179'
A0A831LSC0/191-211'
A0A831LSC0/223-247'
A0A831LSC0/254-271'
A0A831LSC0/277-296'
A0A831LSC0/317-339'
A0A831LSC0/345-367'
J0S2I0/45-65'
J0S2I0/86-105'
J0S2I0/132-151'
J0S2I0/158-180'
J0S2I0/192-213'
J0S2I0/234-251'
J0S2I0/263-289'
J0S2I0/301-317'
J0S2I0/323-339'
J0S2I0/360-382'
J0S2I0/388-413'
J1ASR8/6-31'
J1ASR8/38-58'
J1ASR8/94-112'
J1ASR8/124-145'
J1ASR8/157-179'
J1ASR8/191-211'
J1ASR8/223-247'
J1ASR8/254-271'
J1ASR8/277-296'
J1ASR8/317-339'
J1ASR8/345-370'
J1L5M8/12-34'
J1L5M8/41-61'
J1L5M8/94-115'
J1L5M8/127-148'
J1L5M8/160-182'
J1L5M8/194-214'
J1L5M8/226-250'
J1L5M8/257-274'
J1L5M8/280-299'
J1L5M8/320-342'
J1L5M8/348-370'
D7E934/47-67'
D7E934/88-106'
D7E934/133-152'
D7E934/159-180'
D7E934/206-227'
D7E934/247-264'
D7E934/276-298'
D7E934/310-326'
D7E934/332-351'
D7E934/372-391'
D7E934/411-433'
D5E995/47-67'
D5E995/88-110'
D5E995/130-149'
D5E995/156-177'
D5E995/212-229'
D5E995/241-261'
D5E995/273-295'
D5E995/307-324'
D5E995/330-348'
D5E995/360-381'
D5E995/401-431'
L0KW14/6-31'
L0KW14/38-57'
L0KW14/94-112'
L0KW14/124-145'
L0KW14/157-179'
L0KW14/191-211'
L0KW14/223-244'
L0KW14/251-267'
L0KW14/273-295'
L0KW14/316-339'
L0KW14/345-367'
A7I8Z2/6-29'
A7I8Z2/41-64'
A7I8Z2/98-117'
A7I8Z2/129-150'
A7I8Z2/162-184'
A7I8Z2/196-216'
A7I8Z2/228-248'
A7I8Z2/260-277'
A7I8Z2/283-302'
A7I8Z2/314-335'
A7I8Z2/355-376'
A7I8Z4/12-31'
A7I8Z4/38-58'
A7I8Z4/97-119'
A7I8Z4/126-148'
A7I8Z4/160-182'
A7I8Z4/194-214'
A7I8Z4/220-244'
A7I8Z4/256-274'
A7I8Z4/280-299'
A7I8Z4/320-341'
A7I8Z4/353-373'
F7XP68/57-73'
F7XP68/80-99'
F7XP68/111-131'
F7XP68/138-157'
F7XP68/169-187'
F7XP68/207-227'
F7XP68/233-256'
F7XP68/263-281'
F7XP68/287-304'
F7XP68/316-341'
F7XP68/347-368'
F7XMD8/49-69'
F7XMD8/90-115'
F7XMD8/135-154'
F7XMD8/161-181'
F7XMD8/187-205'
F7XMD8/217-234'
F7XMD8/246-266'
F7XMD8/278-303'
F7XMD8/331-351'
F7XMD8/372-393'
F7XMD8/413-435'
A0A0G3C9G5/44-64'
A0A0G3C9G5/85-106'
A0A0G3C9G5/130-149'
A0A0G3C9G5/156-177'
A0A0G3C9G5/212-229'
A0A0G3C9G5/241-261'
A0A0G3C9G5/273-295'
A0A0G3C9G5/307-323'
A0A0G3C9G5/329-348'
A0A0G3C9G5/360-381'
A0A0G3C9G5/401-431'
A0A0G3CAR5/67-88'
A0A0G3CAR5/109-136'
A0A0G3CAR5/156-181'
A0A0G3CAR5/202-226'
A0A0G3CAR5/246-267'
A0A0G3CAR5/288-305'
A0A0G3CAR5/317-341'
A0A0G3CAR5/353-370'
A0A0G3CAR5/376-394'
A0A0G3CAR5/406-425'
A0A0G3CAR5/451-473'
A0A0G3CJ36/12-33'
A0A0G3CJ36/45-66'
A0A0G3CJ36/95-118'
A0A0G3CJ36/125-145'
A0A0G3CJ36/157-179'
A0A0G3CJ36/191-210'
A0A0G3CJ36/222-242'
A0A0G3CJ36/249-268'
A0A0G3CJ36/274-295'
A0A0G3CJ36/307-331'
A0A0G3CJ36/343-368'
A0A2U1SS17/46-67'
A0A2U1SS17/74-94'
A0A2U1SS17/139-161'
A0A2U1SS17/168-189'
A0A2U1SS17/246-268'
A0A2U1SS17/280-300'
A0A2U1SS17/312-331'
A0A2U1SS17/343-361'
A0A2U1SS17/367-385'
A0A2U1SS17/397-418'
A0A2U1SS17/447-469'
A0A0E3QYF3/44-64'
A0A0E3QYF3/85-106'
A0A0E3QYF3/130-149'
A0A0E3QYF3/156-177'
A0A0E3QYF3/212-229'
A0A0E3QYF3/241-261'
A0A0E3QYF3/273-295'
A0A0E3QYF3/307-323'
A0A0E3QYF3/329-348'
A0A0E3QYF3/360-381'
A0A0E3QYF3/401-431'
A0A0E3R6S1/20-40'
A0A0E3R6S1/47-67'
A0A0E3R6S1/106-128'
A0A0E3R6S1/135-157'
A0A0E3R6S1/169-191'
A0A0E3R6S1/203-221'
A0A0E3R6S1/233-252'
A0A0E3R6S1/264-283'
A0A0E3R6S1/289-307'
A0A0E3R6S1/319-342'
A0A0E3R6S1/362-383'
A0A0E3R4G0/67-88'
A0A0E3R4G0/109-136'
A0A0E3R4G0/156-181'
A0A0E3R4G0/202-226'
A0A0E3R4G0/246-267'
A0A0E3R4G0/288-305'
A0A0E3R4G0/317-341'
A0A0E3R4G0/353-370'
A0A0E3R4G0/376-394'
A0A0E3R4G0/406-425'
A0A0E3R4G0/451-473'
A0A0E3SHQ9/44-64'
A0A0E3SHQ9/85-106'
A0A0E3SHQ9/126-145'
A0A0E3SHQ9/157-177'
A0A0E3SHQ9/212-229'
A0A0E3SHQ9/241-261'
A0A0E3SHQ9/273-295'
A0A0E3SHQ9/307-323'
A0A0E3SHQ9/329-348'
A0A0E3SHQ9/360-388'
A0A0E3SHQ9/400-431'
A0A0E3LMT4/67-88'
A0A0E3LMT4/109-136'
A0A0E3LMT4/156-181'
A0A0E3LMT4/202-226'
A0A0E3LMT4/246-267'
A0A0E3LMT4/288-305'
A0A0E3LMT4/317-341'
A0A0E3LMT4/353-370'
A0A0E3LMT4/376-394'
A0A0E3LMT4/406-425'
A0A0E3LMT4/451-473'
A0A0E3QUS2/44-64'
A0A0E3QUS2/85-106'
A0A0E3QUS2/130-149'
A0A0E3QUS2/156-177'
A0A0E3QUS2/212-229'
A0A0E3QUS2/241-261'
A0A0E3QUS2/273-295'
A0A0E3QUS2/307-323'
A0A0E3QUS2/329-348'
A0A0E3QUS2/360-381'
A0A0E3QUS2/401-431'
A0A0E3WZH5/67-88'
A0A0E3WZH5/109-136'
A0A0E3WZH5/156-181'
A0A0E3WZH5/202-226'
A0A0E3WZH5/246-267'
A0A0E3WZH5/288-305'
A0A0E3WZH5/317-341'
A0A0E3WZH5/353-370'
A0A0E3WZH5/376-394'
A0A0E3WZH5/406-425'
A0A0E3WZH5/451-473'
A0A0E3QY45/20-40'
A0A0E3QY45/47-67'
A0A0E3QY45/106-128'
A0A0E3QY45/135-157'
A0A0E3QY45/169-191'
A0A0E3QY45/203-221'
A0A0E3QY45/233-252'
A0A0E3QY45/264-283'
A0A0E3QY45/289-307'
A0A0E3QY45/319-342'
A0A0E3QY45/362-383'
A0A0E3SP24/12-33'
A0A0E3SP24/45-66'
A0A0E3SP24/95-118'
A0A0E3SP24/125-145'
A0A0E3SP24/157-179'
A0A0E3SP24/191-210'
A0A0E3SP24/222-242'
A0A0E3SP24/249-268'
A0A0E3SP24/274-295'
A0A0E3SP24/307-331'
A0A0E3SP24/343-368'
A0A0E3R6E1/12-33'
A0A0E3R6E1/45-66'
A0A0E3R6E1/95-118'
A0A0E3R6E1/125-145'
A0A0E3R6E1/157-179'
A0A0E3R6E1/191-210'
A0A0E3R6E1/222-242'
A0A0E3R6E1/249-268'
A0A0E3R6E1/274-295'
A0A0E3R6E1/307-331'
A0A0E3R6E1/343-368'
A0A0E3QY86/12-33'
A0A0E3QY86/45-66'
A0A0E3QY86/95-118'
A0A0E3QY86/125-145'
A0A0E3QY86/157-179'
A0A0E3QY86/191-210'
A0A0E3QY86/222-242'
A0A0E3QY86/249-268'
A0A0E3QY86/274-295'
A0A0E3QY86/307-331'
A0A0E3QY86/343-368'
A0A0E3QJ16/44-64'
A0A0E3QJ16/85-106'
A0A0E3QJ16/130-149'
A0A0E3QJ16/156-177'
A0A0E3QJ16/212-229'
A0A0E3QJ16/241-261'
A0A0E3QJ16/273-295'
A0A0E3QJ16/307-323'
A0A0E3QJ16/329-348'
A0A0E3QJ16/360-381'
A0A0E3QJ16/401-431'
A0A0E3QKN0/12-33'
A0A0E3QKN0/45-66'
A0A0E3QKN0/95-118'
A0A0E3QKN0/125-145'
A0A0E3QKN0/157-179'
A0A0E3QKN0/191-210'
A0A0E3QKN0/222-242'
A0A0E3QKN0/249-268'
A0A0E3QKN0/274-295'
A0A0E3QKN0/307-331'
A0A0E3QKN0/343-368'
Q466Y3/44-64'
Q466Y3/85-106'
Q466Y3/130-149'
Q466Y3/156-177'
Q466Y3/212-229'
Q466Y3/241-261'
Q466Y3/273-295'
Q466Y3/307-323'
Q466Y3/329-348'
Q466Y3/360-381'
Q466Y3/401-431'
Q46G49/12-33'
Q46G49/45-66'
Q46G49/95-118'
Q46G49/125-145'
Q46G49/157-179'
Q46G49/191-210'
Q46G49/222-242'
Q46G49/249-268'
Q46G49/274-295'
Q46G49/307-331'
Q46G49/343-368'
A0A328Q6M1/12-34'
A0A328Q6M1/46-64'
A0A328Q6M1/103-125'
A0A328Q6M1/132-154'
A0A328Q6M1/166-188'
A0A328Q6M1/200-217'
A0A328Q6M1/229-253'
A0A328Q6M1/260-281'
A0A328Q6M1/287-304'
A0A328Q6M1/325-347'
A0A328Q6M1/353-375'
Q2NGJ2/12-34'
Q2NGJ2/46-64'
Q2NGJ2/103-125'
Q2NGJ2/132-154'
Q2NGJ2/166-188'
Q2NGJ2/200-217'
Q2NGJ2/229-253'
Q2NGJ2/260-281'
Q2NGJ2/287-304'
Q2NGJ2/325-347'
Q2NGJ2/353-375'
B8GGC1/6-29'
B8GGC1/41-64'
B8GGC1/91-114'
B8GGC1/126-147'
B8GGC1/159-181'
B8GGC1/193-213'
B8GGC1/225-244'
B8GGC1/256-274'
B8GGC1/280-298'
B8GGC1/310-331'
B8GGC1/351-372'
B8GGC3/12-31'
B8GGC3/38-58'
B8GGC3/96-114'
B8GGC3/126-147'
B8GGC3/159-181'
B8GGC3/193-212'
B8GGC3/224-244'
B8GGC3/256-273'
B8GGC3/279-298'
B8GGC3/310-331'
B8GGC3/351-372'
A0A8F5VN39/6-29'
A0A8F5VN39/36-56'
A0A8F5VN39/92-114'
A0A8F5VN39/121-143'
A0A8F5VN39/155-177'
A0A8F5VN39/189-209'
A0A8F5VN39/215-240'
A0A8F5VN39/252-271'
A0A8F5VN39/277-294'
A0A8F5VN39/315-337'
A0A8F5VN39/343-368'
A0A8F5ZDT8/6-31'
A0A8F5ZDT8/38-58'
A0A8F5ZDT8/96-118'
A0A8F5ZDT8/125-147'
A0A8F5ZDT8/159-180'
A0A8F5ZDT8/200-221'
A0A8F5ZDT8/227-246'
A0A8F5ZDT8/255-274'
A0A8F5ZDT8/280-298'
A0A8F5ZDT8/310-331'
A0A8F5ZDT8/351-369'
Q2FS34/6-31'
Q2FS34/38-58'
Q2FS34/96-118'
Q2FS34/125-147'
Q2FS34/159-180'
Q2FS34/200-221'
Q2FS34/227-246'
Q2FS34/258-276'
Q2FS34/282-298'
Q2FS34/310-331'
Q2FS34/351-369'
Q2FQT3/6-29'
Q2FQT3/36-56'
Q2FQT3/92-114'
Q2FQT3/121-143'
Q2FQT3/155-177'
Q2FQT3/189-209'
Q2FQT3/215-240'
Q2FQT3/252-271'
Q2FQT3/277-294'
Q2FQT3/315-337'
Q2FQT3/343-368'
O26757 has 12 helices, if 12, will use last 11, if other won't include
O26757/47-67'
O26757/70-90'
O26757/101-121'
O26757/129-149'
O26757/162-182'
O26757/196-216'
O26757/226-246'
O26757/257-277'
O26757/279-299'
O26757/312-332'
O26757/357-377'

O26759/16-36'
O26759/46-66'
O26759/71-91'
O26759/107-127'
O26759/137-157'
O26759/170-190'
O26759/204-224'
O26759/234-254'
O26759/276-296'
O26759/320-340'
O26759/360-380'
A0A842YNC7/12-35'
A0A842YNC7/41-62'
A0A842YNC7/102-124'
A0A842YNC7/131-153'
A0A842YNC7/165-187'
A0A842YNC7/199-216'
A0A842YNC7/222-247'
A0A842YNC7/259-278'
A0A842YNC7/284-303'
A0A842YNC7/315-338'
A0A842YNC7/358-378'
A0A7J4MVN6/12-35'
A0A7J4MVN6/41-62'
A0A7J4MVN6/102-124'
A0A7J4MVN6/131-153'
A0A7J4MVN6/165-187'
A0A7J4MVN6/199-216'
A0A7J4MVN6/222-247'
A0A7J4MVN6/259-278'
A0A7J4MVN6/284-303'
A0A7J4MVN6/315-338'
A0A7J4MVN6/358-378'
A0A842YPK2/12-31'
A0A842YPK2/43-65'
A0A842YPK2/100-121'
A0A842YPK2/128-150'
A0A842YPK2/162-184'
A0A842YPK2/196-213'
A0A842YPK2/225-245'
A0A842YPK2/257-277'
A0A842YPK2/283-300'
A0A842YPK2/312-332'
A0A842YPK2/352-377'
A0A832YRB5/22-42'
A0A832YRB5/63-81'
A0A832YRB5/110-129'
A0A832YRB5/136-156'
A0A832YRB5/168-190'
A0A832YRB5/202-225'
A0A832YRB5/237-258'
A0A832YRB5/265-284'
A0A832YRB5/290-308'
A0A832YRB5/320-342'
A0A832YRB5/354-372'
A0A832ZZI9/20-39'
A0A832ZZI9/60-79'
A0A832ZZI9/104-126'
A0A832ZZI9/133-153'
A0A832ZZI9/165-187'
A0A832ZZI9/199-222'
A0A832ZZI9/234-256'
A0A832ZZI9/263-281'
A0A832ZZI9/287-305'
A0A832ZZI9/317-339'
A0A832ZZI9/351-372'
A0A832Z6L4/18-38'
A0A832Z6L4/59-78'
A0A832Z6L4/103-125'
A0A832Z6L4/132-152'
A0A832Z6L4/164-186'
A0A832Z6L4/198-221'
A0A832Z6L4/233-255'
A0A832Z6L4/262-281'
A0A832Z6L4/287-304'
A0A832Z6L4/316-334'
A0A832Z6L4/346-368'
F6BEI0/29-49'
F6BEI0/70-89'
F6BEI0/115-134'
F6BEI0/141-161'
F6BEI0/173-195'
F6BEI0/207-230'
F6BEI0/242-262'
F6BEI0/269-287'
F6BEI0/293-313'
F6BEI0/325-347'
F6BEI0/359-387'
A0A832RS03/12-31'
A0A832RS03/38-58'
A0A832RS03/96-114'
A0A832RS03/126-147'
A0A832RS03/159-180'
A0A832RS03/200-220'
A0A832RS03/226-249'
A0A832RS03/256-276'
A0A832RS03/282-300'
A0A832RS03/312-335'
A0A832RS03/347-369'
B3DUX7 has 12 helices, if 12, will use last 11, if other won't include
B3DUX7/92-113'
B3DUX7/125-148'
B3DUX7/181-205'
B3DUX7/217-239'
B3DUX7/259-280'
B3DUX7/292-312'
B3DUX7/324-343'
B3DUX7/355-373'
B3DUX7/379-400'
B3DUX7/412-433'
B3DUX7/466-485'
Q1GYA8/61-82'
Q1GYA8/94-114'
Q1GYA8/153-175'
Q1GYA8/182-204'
Q1GYA8/216-238'
Q1GYA8/250-269'
Q1GYA8/281-301'
Q1GYA8/313-330'
Q1GYA8/336-355'
Q1GYA8/367-387'
Q1GYA8/407-429'
Q1H0G2/36-55'
Q1H0G2/76-93'
Q1H0G2/113-135'
Q1H0G2/142-160'
Q1H0G2/180-200'
Q1H0G2/221-238'
Q1H0G2/250-273'
Q1H0G2/280-298'
Q1H0G2/304-325'
Q1H0G2/337-355'
Q1H0G2/367-390'
Q1H483/38-60'
Q1H483/72-90'
Q1H483/126-148'
Q1H483/155-177'
Q1H483/189-211'
Q1H483/223-243'
Q1H483/255-279'
Q1H483/286-303'
Q1H483/309-328'
Q1H483/340-360'
Q1H483/380-402'
A0A2S6GKF6/38-59'
A0A2S6GKF6/71-89'
A0A2S6GKF6/131-153'
A0A2S6GKF6/160-183'
A0A2S6GKF6/213-233'
A0A2S6GKF6/245-266'
A0A2S6GKF6/278-298'
A0A2S6GKF6/310-327'
A0A2S6GKF6/333-351'
A0A2S6GKF6/372-395'
A0A2S6GKF6/415-433'
A0A2S6H643/38-59'
A0A2S6H643/71-89'
A0A2S6H643/131-153'
A0A2S6H643/160-183'
A0A2S6H643/213-233'
A0A2S6H643/245-266'
A0A2S6H643/278-298'
A0A2S6H643/310-332'
A0A2S6H643/338-360'
A0A2S6H643/372-395'
A0A2S6H643/415-433'
G3IYW2/38-59'
G3IYW2/71-89'
G3IYW2/131-153'
G3IYW2/160-183'
G3IYW2/213-233'
G3IYW2/245-266'
G3IYW2/278-298'
G3IYW2/310-332'
G3IYW2/338-360'
G3IYW2/372-395'
G3IYW2/415-433'
A0A2S6GKN5/33-53'
A0A2S6GKN5/65-88'
A0A2S6GKN5/123-144'
A0A2S6GKN5/151-173'
A0A2S6GKN5/185-207'
A0A2S6GKN5/219-239'
A0A2S6GKN5/251-272'
A0A2S6GKN5/281-300'
A0A2S6GKN5/306-326'
A0A2S6GKN5/338-358'
A0A2S6GKN5/378-398'
A0A2S6H6B7/33-53'
A0A2S6H6B7/65-88'
A0A2S6H6B7/123-144'
A0A2S6H6B7/151-173'
A0A2S6H6B7/185-207'
A0A2S6H6B7/219-239'
A0A2S6H6B7/251-272'
A0A2S6H6B7/281-300'
A0A2S6H6B7/306-326'
A0A2S6H6B7/338-358'
A0A2S6H6B7/378-398'
G3IYW0/33-53'
G3IYW0/65-88'
G3IYW0/123-144'
G3IYW0/151-173'
G3IYW0/185-207'
G3IYW0/219-239'
G3IYW0/251-272'
G3IYW0/281-300'
G3IYW0/306-326'
G3IYW0/338-358'
G3IYW0/378-398'
A0A2J7TJ33/38-60'
A0A2J7TJ33/72-92'
A0A2J7TJ33/144-162'
A0A2J7TJ33/174-197'
A0A2J7TJ33/243-265'
A0A2J7TJ33/277-297'
A0A2J7TJ33/309-328'
A0A2J7TJ33/340-361'
A0A2J7TJ33/367-384'
A0A2J7TJ33/396-419'
A0A2J7TJ33/451-470'
B8ENL9/45-67'
B8ENL9/79-99'
B8ENL9/151-169'
B8ENL9/181-204'
B8ENL9/250-272'
B8ENL9/284-304'
B8ENL9/316-335'
B8ENL9/347-368'
B8ENL9/374-391'
B8ENL9/403-426'
B8ENL9/458-477'
B8EMQ8/62-83'
B8EMQ8/95-115'
B8EMQ8/158-180'
B8EMQ8/187-208'
B8EMQ8/228-249'
B8EMQ8/261-278'
B8EMQ8/290-309'
B8EMQ8/321-342'
B8EMQ8/348-365'
B8EMQ8/377-398'
B8EMQ8/418-439'
Q60C43/34-54'
Q60C43/66-89'
Q60C43/127-145'
Q60C43/152-174'
Q60C43/186-208'
Q60C43/220-240'
Q60C43/246-271'
Q60C43/283-303'
Q60C43/309-327'
Q60C43/339-357'
Q60C43/377-399'
Q605Y6/53-74'
Q605Y6/86-109'
Q605Y6/146-168'
Q605Y6/175-199'
Q605Y6/228-249'
Q605Y6/261-282'
Q605Y6/294-314'
Q605Y6/326-347'
Q605Y6/353-369'
Q605Y6/381-410'
Q605Y6/430-448'
Q60BI2/32-54'
Q60BI2/66-89'
Q60BI2/127-145'
Q60BI2/152-174'
Q60BI2/186-208'
Q60BI2/220-240'
Q60BI2/246-270'
Q60BI2/282-301'
Q60BI2/307-327'
Q60BI2/339-358'
Q60BI2/378-399'
Q608B6/43-63'
Q608B6/84-102'
Q608B6/122-141'
Q608B6/150-170'
Q608B6/190-211'
Q608B6/232-254'
Q608B6/260-282'
Q608B6/289-307'
Q608B6/313-331'
Q608B6/343-362'
Q608B6/374-396'
V5E0F3/45-65'
V5E0F3/77-100'
V5E0F3/135-156'
V5E0F3/163-185'
V5E0F3/197-219'
V5E0F3/231-251'
V5E0F3/263-282'
V5E0F3/294-312'
V5E0F3/318-338'
V5E0F3/350-370'
V5E0F3/390-410'
V5BYZ7/42-64'
V5BYZ7/76-94'
V5BYZ7/136-158'
V5BYZ7/165-189'
V5BYZ7/218-238'
V5BYZ7/250-271'
V5BYZ7/283-303'
V5BYZ7/315-332'
V5BYZ7/338-359'
V5BYZ7/371-390'
V5BYZ7/420-438'
I1YG38/6-27'
I1YG38/48-66'
I1YG38/86-105'
I1YG38/114-134'
I1YG38/154-175'
I1YG38/196-217'
I1YG38/223-246'
I1YG38/253-271'
I1YG38/277-293'
I1YG38/305-330'
I1YG38/342-363'
I1YJH7/15-39'
I1YJH7/51-70'
I1YJH7/100-119'
I1YJH7/124-141'
I1YJH7/161-187'
I1YJH7/208-225'
I1YJH7/245-264'
I1YJH7/271-291'
I1YJH7/297-316'
I1YJH7/328-346'
I1YJH7/352-377'
F5RGM7/83-104'
F5RGM7/116-136'
F5RGM7/176-198'
F5RGM7/205-228'
F5RGM7/258-279'
F5RGM7/291-312'
F5RGM7/324-343'
F5RGM7/355-372'
F5RGM7/378-396'
F5RGM7/408-430'
F5RGM7/457-479'
F5R974/12-35'
F5R974/47-69'
F5R974/89-107'
F5R974/119-137'
F5R974/157-178'
F5R974/199-220'
F5R974/226-249'
F5R974/256-274'
F5R974/280-298'
F5R974/310-329'
F5R974/341-363'
A0A2W5HTC3/40-61'
A0A2W5HTC3/68-88'
A0A2W5HTC3/129-146'
A0A2W5HTC3/158-178'
A0A2W5HTC3/198-225'
A0A2W5HTC3/237-258'
A0A2W5HTC3/270-290'
A0A2W5HTC3/302-322'
A0A2W5HTC3/328-345'
A0A2W5HTC3/357-375'
A0A2W5HTC3/395-416'
A0A2W4ZXC0/6-29'
A0A2W4ZXC0/41-62'
A0A2W4ZXC0/95-115'
A0A2W4ZXC0/127-148'
A0A2W4ZXC0/160-184'
A0A2W4ZXC0/196-216'
A0A2W4ZXC0/228-248'
A0A2W4ZXC0/260-278'
A0A2W4ZXC0/284-303'
A0A2W4ZXC0/315-334'
A0A2W4ZXC0/354-379'
M4VEJ9/6-28'
M4VEJ9/49-73'
M4VEJ9/93-113'
M4VEJ9/125-146'
M4VEJ9/158-182'
M4VEJ9/194-214'
M4VEJ9/226-246'
M4VEJ9/258-276'
M4VEJ9/282-301'
M4VEJ9/313-336'
M4VEJ9/356-377'
A0A1H1MB73/6-28'
A0A1H1MB73/40-58'
A0A1H1MB73/92-112'
A0A1H1MB73/124-145'
A0A1H1MB73/165-190'
A0A1H1MB73/202-222'
A0A1H1MB73/234-256'
A0A1H1MB73/268-286'
A0A1H1MB73/292-310'
A0A1H1MB73/322-349'
A0A1H1MB73/355-380'
A0A7U6DPL5/12-32'
A0A7U6DPL5/44-62'
A0A7U6DPL5/93-114'
A0A7U6DPL5/121-145'
A0A7U6DPL5/165-186'
A0A7U6DPL5/202-220'
A0A7U6DPL5/232-251'
A0A7U6DPL5/263-280'
A0A7U6DPL5/286-305'
A0A7U6DPL5/317-337'
A0A7U6DPL5/357-379'
A0A653ISC0/12-31'
A0A653ISC0/43-61'
A0A653ISC0/92-113'
A0A653ISC0/120-144'
A0A653ISC0/164-182'
A0A653ISC0/202-219'
A0A653ISC0/231-250'
A0A653ISC0/262-279'
A0A653ISC0/285-304'
A0A653ISC0/316-336'
A0A653ISC0/356-378'
D3LL06/12-32'
D3LL06/44-62'
D3LL06/93-114'
D3LL06/121-145'
D3LL06/165-186'
D3LL06/202-220'
D3LL06/232-251'
D3LL06/263-280'
D3LL06/286-305'
D3LL06/317-337'
D3LL06/357-379'
A0A378NLG8/12-32'
A0A378NLG8/44-62'
A0A378NLG8/93-114'
A0A378NLG8/121-145'
A0A378NLG8/165-186'
A0A378NLG8/202-220'
A0A378NLG8/232-251'
A0A378NLG8/263-280'
A0A378NLG8/286-305'
A0A378NLG8/317-337'
A0A378NLG8/357-379'
A0A653N551/12-32'
A0A653N551/44-62'
A0A653N551/93-114'
A0A653N551/121-145'
A0A653N551/165-186'
A0A653N551/202-220'
A0A653N551/232-251'
A0A653N551/263-280'
A0A653N551/286-305'
A0A653N551/317-337'
A0A653N551/357-379'
A0A132HDB5/12-32'
A0A132HDB5/44-62'
A0A132HDB5/93-114'
A0A132HDB5/121-145'
A0A132HDB5/165-186'
A0A132HDB5/202-220'
A0A132HDB5/232-251'
A0A132HDB5/263-282'
A0A132HDB5/288-305'
A0A132HDB5/317-337'
A0A132HDB5/357-379'
A0A031H2S8/12-32'
A0A031H2S8/44-62'
A0A031H2S8/93-114'
A0A031H2S8/121-145'
A0A031H2S8/165-186'
A0A031H2S8/202-220'
A0A031H2S8/232-251'
A0A031H2S8/263-280'
A0A031H2S8/286-305'
A0A031H2S8/317-337'
A0A031H2S8/357-379'
A0A031ISU7/12-32'
A0A031ISU7/44-62'
A0A031ISU7/93-114'
A0A031ISU7/121-145'
A0A031ISU7/165-186'
A0A031ISU7/202-220'
A0A031ISU7/232-251'
A0A031ISU7/263-280'
A0A031ISU7/286-305'
A0A031ISU7/317-337'
A0A031ISU7/357-379'

C5CAG5/12-32'
C5CAG5/44-62'
C5CAG5/93-114'
C5CAG5/121-145'
C5CAG5/165-186'
C5CAG5/202-220'
C5CAG5/232-251'
C5CAG5/263-280'
C5CAG5/286-305'
C5CAG5/317-337'
C5CAG5/357-379'
A0A4P8HC89/6-28'
A0A4P8HC89/40-58'
A0A4P8HC89/78-107'
A0A4P8HC89/119-141'
A0A4P8HC89/161-182'
A0A4P8HC89/198-216'
A0A4P8HC89/228-247'
A0A4P8HC89/259-277'
A0A4P8HC89/283-301'
A0A4P8HC89/313-335'
A0A4P8HC89/355-376'
A0A509Y3R3/12-32'
A0A509Y3R3/44-62'
A0A509Y3R3/93-114'
A0A509Y3R3/121-145'
A0A509Y3R3/165-186'
A0A509Y3R3/202-220'
A0A509Y3R3/232-251'
A0A509Y3R3/263-280'
A0A509Y3R3/286-305'
A0A509Y3R3/317-337'
A0A509Y3R3/357-379'
A0A4U1LD24/12-32'
A0A4U1LD24/44-62'
A0A4U1LD24/93-114'
A0A4U1LD24/121-145'
A0A4U1LD24/165-186'
A0A4U1LD24/202-220'
A0A4U1LD24/232-251'
A0A4U1LD24/263-282'
A0A4U1LD24/288-305'
A0A4U1LD24/317-337'
A0A4U1LD24/357-379'
A0A410XNG8/6-27'
A0A410XNG8/39-62'
A0A410XNG8/91-112'
A0A410XNG8/124-144'
A0A410XNG8/167-189'
A0A410XNG8/201-219'
A0A410XNG8/231-252'
A0A410XNG8/259-280'
A0A410XNG8/286-305'
A0A410XNG8/317-340'
A0A410XNG8/360-381'
A0A7T5AF95/12-32'
A0A7T5AF95/44-62'
A0A7T5AF95/93-114'
A0A7T5AF95/121-145'
A0A7T5AF95/165-186'
A0A7T5AF95/202-220'
A0A7T5AF95/232-251'
A0A7T5AF95/263-280'
A0A7T5AF95/286-305'
A0A7T5AF95/317-337'
A0A7T5AF95/357-379'
A0A1R4IK85/12-32'
A0A1R4IK85/44-62'
A0A1R4IK85/93-114'
A0A1R4IK85/121-145'
A0A1R4IK85/165-186'
A0A1R4IK85/202-220'
A0A1R4IK85/232-251'
A0A1R4IK85/263-280'
A0A1R4IK85/286-305'
A0A1R4IK85/317-337'
A0A1R4IK85/357-379'
A0A1M6ZIN6/12-32'
A0A1M6ZIN6/44-62'
A0A1M6ZIN6/93-114'
A0A1M6ZIN6/121-145'
A0A1M6ZIN6/165-186'
A0A1M6ZIN6/202-220'
A0A1M6ZIN6/232-251'
A0A1M6ZIN6/263-280'
A0A1M6ZIN6/286-305'
A0A1M6ZIN6/317-337'
A0A1M6ZIN6/357-379'
A0A562FQ17/12-32'
A0A562FQ17/44-62'
A0A562FQ17/93-114'
A0A562FQ17/121-145'
A0A562FQ17/165-186'
A0A562FQ17/202-220'
A0A562FQ17/232-251'
A0A562FQ17/263-280'
A0A562FQ17/286-305'
A0A562FQ17/317-337'
A0A562FQ17/357-379'
A0A5E8QER8/12-32'
A0A5E8QER8/44-62'
A0A5E8QER8/93-114'
A0A5E8QER8/121-145'
A0A5E8QER8/165-186'
A0A5E8QER8/202-220'
A0A5E8QER8/232-251'
A0A5E8QER8/263-280'
A0A5E8QER8/286-305'
A0A5E8QER8/317-337'
A0A5E8QER8/357-379'
A0A2N6RP58/12-32'
A0A2N6RP58/44-62'
A0A2N6RP58/93-114'
A0A2N6RP58/121-145'
A0A2N6RP58/165-186'
A0A2N6RP58/202-220'
A0A2N6RP58/232-251'
A0A2N6RP58/263-280'
A0A2N6RP58/286-305'
A0A2N6RP58/317-337'
A0A2N6RP58/357-379'
F5XN43/12-32'
F5XN43/44-62'
F5XN43/100-122'
F5XN43/129-150'
F5XN43/177-199'
F5XN43/211-231'
F5XN43/243-263'
F5XN43/270-289'
F5XN43/295-317'
F5XN43/329-352'
F5XN43/372-393'
A1ZGK6/12-31'
A1ZGK6/43-67'
A1ZGK6/106-125'
A1ZGK6/132-151'
A1ZGK6/188-210'
A1ZGK6/231-250'
A1ZGK6/262-285'
A1ZGK6/292-310'
A1ZGK6/316-334'
A1ZGK6/346-365'
A1ZGK6/377-397'
A0A2S0P9T4/75-98'
A0A2S0P9T4/105-126'
A0A2S0P9T4/167-188'
A0A2S0P9T4/195-216'
A0A2S0P9T4/236-255'
A0A2S0P9T4/267-284'
A0A2S0P9T4/296-316'
A0A2S0P9T4/328-347'
A0A2S0P9T4/353-371'
A0A2S0P9T4/383-407'
A0A2S0P9T4/413-435'
C9KKP2/6-29'
C9KKP2/41-62'
C9KKP2/96-118'
C9KKP2/125-147'
C9KKP2/159-180'
C9KKP2/192-213'
C9KKP2/225-249'
C9KKP2/256-276'
C9KKP2/282-300'
C9KKP2/312-331'
C9KKP2/351-373'
A0A414NWT8/6-29'
A0A414NWT8/41-62'
A0A414NWT8/96-118'
A0A414NWT8/125-147'
A0A414NWT8/159-180'
A0A414NWT8/192-213'
A0A414NWT8/225-249'
A0A414NWT8/256-276'
A0A414NWT8/282-300'
A0A414NWT8/312-331'
A0A414NWT8/351-373'
H5UND3/12-31'
H5UND3/38-59'
H5UND3/95-116'
H5UND3/128-148'
H5UND3/175-197'
H5UND3/209-229'
H5UND3/241-261'
H5UND3/273-290'
H5UND3/296-315'
H5UND3/327-350'
H5UND3/370-391'
D4XLN6/72-94'
D4XLN6/106-128'
D4XLN6/159-181'
D4XLN6/188-210'
D4XLN6/222-243'
D4XLN6/255-276'
D4XLN6/288-307'
D4XLN6/319-339'
D4XLN6/345-363'
D4XLN6/375-399'
D4XLN6/411-433'
D4XSW0/20-44'
D4XSW0/56-75'
D4XSW0/95-114'
D4XSW0/126-146'
D4XSW0/166-188'
D4XSW0/209-228'
D4XSW0/234-257'
D4XSW0/264-282'
D4XSW0/288-306'
D4XSW0/318-337'
D4XSW0/349-374'
A9UR54/17-36'
A9UR54/57-75'
A9UR54/95-118'
A9UR54/125-145'
A9UR54/165-184'
A9UR54/205-230'
A9UR54/242-263'
A9UR54/270-289'
A9UR54/295-314'
A9UR54/326-345'
A9UR54/365-386'
A9V5W4 has 12 helices, if 12, will use last 11, if other won't include
A9V5W4/77-96'
A9V5W4/103-125'
A9V5W4/145-164'
A9V5W4/171-191'
A9V5W4/203-221'
A9V5W4/242-262'
A9V5W4/274-297'
A9V5W4/309-326'
A9V5W4/332-353'
A9V5W4/365-387'
A9V5W4/417-441'
A0A5D3HZ79/54-76'
A0A5D3HZ79/83-104'
A0A5D3HZ79/145-166'
A0A5D3HZ79/173-194'
A0A5D3HZ79/206-230'
A0A5D3HZ79/242-262'
A0A5D3HZ79/274-293'
A0A5D3HZ79/305-324'
A0A5D3HZ79/330-349'
A0A5D3HZ79/361-380'
A0A5D3HZ79/400-422'
A0A1J5JH24/54-76'
A0A1J5JH24/83-104'
A0A1J5JH24/141-161'
A0A1J5JH24/173-194'
A0A1J5JH24/206-230'
A0A1J5JH24/242-262'
A0A1J5JH24/274-293'
A0A1J5JH24/305-324'
A0A1J5JH24/330-349'
A0A1J5JH24/361-380'
A0A1J5JH24/400-422'
A0A1J5NNB8 has 12 helices, if 12, will use last 11, if other won't include
A0A1J5NNB8/70-90'
A0A1J5NNB8/110-134'
A0A1J5NNB8/168-188'
A0A1J5NNB8/200-222'
A0A1J5NNB8/242-263'
A0A1J5NNB8/283-300'
A0A1J5NNB8/312-334'
A0A1J5NNB8/346-364'
A0A1J5NNB8/370-388'
A0A1J5NNB8/400-419'
A0A1J5NNB8/454-476'
A0A853W4S3/54-76'
A0A853W4S3/83-104'
A0A853W4S3/145-166'
A0A853W4S3/173-194'
A0A853W4S3/206-230'
A0A853W4S3/242-262'
A0A853W4S3/274-293'
A0A853W4S3/305-324'
A0A853W4S3/330-349'
A0A853W4S3/361-380'
A0A853W4S3/400-422'
A0A1J5NTP7/55-77'
A0A1J5NTP7/84-105'
A0A1J5NTP7/146-167'
A0A1J5NTP7/174-195'
A0A1J5NTP7/207-231'
A0A1J5NTP7/243-263'
A0A1J5NTP7/275-294'
A0A1J5NTP7/306-325'
A0A1J5NTP7/331-350'
A0A1J5NTP7/362-381'
A0A1J5NTP7/401-423'
A0A1D7XAU3/70-90'
A0A1D7XAU3/110-134'
A0A1D7XAU3/168-188'
A0A1D7XAU3/200-222'
A0A1D7XAU3/242-263'
A0A1D7XAU3/283-300'
A0A1D7XAU3/312-334'
A0A1D7XAU3/346-364'
A0A1D7XAU3/370-388'
A0A1D7XAU3/400-419'
A0A1D7XAU3/454-476'
A0A0S6UEK9/54-76'
A0A0S6UEK9/83-104'
A0A0S6UEK9/145-166'
A0A0S6UEK9/173-194'
A0A0S6UEK9/206-230'
A0A0S6UEK9/242-262'
A0A0S6UEK9/274-293'
A0A0S6UEK9/305-324'
A0A0S6UEK9/330-349'
A0A0S6UEK9/361-380'
A0A0S6UEK9/400-422'
A0A0S6UHP2 has 12 helices, if 12, will use last 11, if other won't include
A0A0S6UHP2/87-107'
A0A0S6UHP2/127-151'
A0A0S6UHP2/185-205'
A0A0S6UHP2/217-239'
A0A0S6UHP2/259-280'
A0A0S6UHP2/300-317'
A0A0S6UHP2/329-351'
A0A0S6UHP2/363-381'
A0A0S6UHP2/387-405'
A0A0S6UHP2/417-436'
A0A0S6UHP2/471-493'
Q2RM12/27-49'
Q2RM12/56-77'
Q2RM12/118-139'
Q2RM12/146-167'
Q2RM12/179-203'
Q2RM12/215-235'
Q2RM12/247-266'
Q2RM12/278-297'
Q2RM12/303-322'
Q2RM12/334-353'
Q2RM12/373-395'
A0A7Z0V0A4/35-58'
A0A7Z0V0A4/70-91'
A0A7Z0V0A4/121-142'
A0A7Z0V0A4/154-174'
A0A7Z0V0A4/186-207'
A0A7Z0V0A4/219-240'
A0A7Z0V0A4/252-272'
A0A7Z0V0A4/284-301'
A0A7Z0V0A4/307-327'
A0A7Z0V0A4/339-363'
A0A7Z0V0A4/375-400'
M1SJL5/32-54'
M1SJL5/66-84'
M1SJL5/123-142'
M1SJL5/149-171'
M1SJL5/183-205'
M1SJL5/217-236'
M1SJL5/248-268'
M1SJL5/280-297'
M1SJL5/303-321'
M1SJL5/333-354'
M1SJL5/374-396'
A0A2S1BIN7/32-54'
A0A2S1BIN7/66-84'
A0A2S1BIN7/123-142'
A0A2S1BIN7/149-171'
A0A2S1BIN7/183-205'
A0A2S1BIN7/217-236'
A0A2S1BIN7/248-268'
A0A2S1BIN7/280-297'
A0A2S1BIN7/303-321'
A0A2S1BIN7/333-354'
A0A2S1BIN7/374-396'
A0A1M7DGY1/32-54'
A0A1M7DGY1/66-84'
A0A1M7DGY1/123-142'
A0A1M7DGY1/149-171'
A0A1M7DGY1/183-205'
A0A1M7DGY1/217-236'
A0A1M7DGY1/248-268'
A0A1M7DGY1/280-297'
A0A1M7DGY1/303-321'
A0A1M7DGY1/333-354'
A0A1M7DGY1/374-396'
A0A2C5TWB4/32-54'
A0A2C5TWB4/66-84'
A0A2C5TWB4/123-142'
A0A2C5TWB4/149-171'
A0A2C5TWB4/183-205'
A0A2C5TWB4/217-236'
A0A2C5TWB4/248-268'
A0A2C5TWB4/280-297'
A0A2C5TWB4/303-321'
A0A2C5TWB4/333-354'
A0A2C5TWB4/374-396'
A0A433ZQ80/32-54'
A0A433ZQ80/66-84'
A0A433ZQ80/123-142'
A0A433ZQ80/149-171'
A0A433ZQ80/183-205'
A0A433ZQ80/217-236'
A0A433ZQ80/248-268'
A0A433ZQ80/280-299'
A0A433ZQ80/305-324'
A0A433ZQ80/336-354'
A0A433ZQ80/374-396'
M7CDZ4/32-54'
M7CDZ4/66-84'
M7CDZ4/123-142'
M7CDZ4/149-171'
M7CDZ4/183-205'
M7CDZ4/217-236'
M7CDZ4/248-268'
M7CDZ4/280-297'
M7CDZ4/303-321'
M7CDZ4/333-354'
M7CDZ4/374-396'
A0A7U0APP4/32-54'
A0A7U0APP4/66-84'
A0A7U0APP4/123-142'
A0A7U0APP4/149-171'
A0A7U0APP4/183-205'
A0A7U0APP4/217-236'
A0A7U0APP4/248-268'
A0A7U0APP4/280-297'
A0A7U0APP4/303-321'
A0A7U0APP4/333-354'
A0A7U0APP4/374-396'
A0A8I0DAF6/32-54'
A0A8I0DAF6/66-84'
A0A8I0DAF6/123-142'
A0A8I0DAF6/149-171'
A0A8I0DAF6/183-205'
A0A8I0DAF6/217-236'
A0A8I0DAF6/248-268'
A0A8I0DAF6/280-297'
A0A8I0DAF6/303-321'
A0A8I0DAF6/333-354'
A0A8I0DAF6/374-396'
A0A8I0PWC5/32-54'
A0A8I0PWC5/66-84'
A0A8I0PWC5/123-142'
A0A8I0PWC5/149-171'
A0A8I0PWC5/183-205'
A0A8I0PWC5/217-236'
A0A8I0PWC5/248-268'
A0A8I0PWC5/280-297'
A0A8I0PWC5/303-321'
A0A8I0PWC5/333-354'
A0A8I0PWC5/374-396'
A0A5J6WQU1/20-43'
A0A5J6WQU1/55-75'
A0A5J6WQU1/105-124'
A0A5J6WQU1/129-146'
A0A5J6WQU1/166-186'
A0A5J6WQU1/207-224'
A0A5J6WQU1/244-262'
A0A5J6WQU1/274-291'
A0A5J6WQU1/297-316'
A0A5J6WQU1/325-344'
A0A5J6WQU1/356-376'

A0A5J6WPP9/18-37'
A0A5J6WPP9/58-76'
A0A5J6WPP9/96-115'
A0A5J6WPP9/122-144'
A0A5J6WPP9/164-185'
A0A5J6WPP9/197-221'
A0A5J6WPP9/233-255'
A0A5J6WPP9/262-280'
A0A5J6WPP9/286-304'
A0A5J6WPP9/316-336'
A0A5J6WPP9/348-373'
H1YCC3/41-64'
H1YCC3/76-103'
H1YCC3/123-147'
H1YCC3/159-175'
H1YCC3/195-215'
H1YCC3/227-245'
H1YCC3/257-278'
H1YCC3/290-309'
H1YCC3/315-331'
H1YCC3/343-362'
H1YCC3/382-406'
H1YF74 has 12 helices, if 12, will use last 11, if other won't include
H1YF74/92-115'
H1YF74/127-149'
H1YF74/178-196'
H1YF74/217-236'
H1YF74/262-283'
H1YF74/304-321'
H1YF74/341-362'
H1YF74/374-394'
H1YF74/400-419'
H1YF74/431-452'
H1YF74/480-501'
H1Y7T6/37-59'
H1Y7T6/71-102'
H1Y7T6/122-146'
H1Y7T6/158-181'
H1Y7T6/193-214'
H1Y7T6/226-244'
H1Y7T6/250-277'
H1Y7T6/289-308'
H1Y7T6/314-330'
H1Y7T6/342-362'
H1Y7T6/382-405'
G2PRJ6/20-42'
G2PRJ6/63-89'
G2PRJ6/109-129'
G2PRJ6/136-156'
G2PRJ6/176-193'
G2PRJ6/213-230'
G2PRJ6/250-270'
G2PRJ6/277-294'
G2PRJ6/300-321'
G2PRJ6/333-353'
G2PRJ6/373-391'
Q8BUX5 has 12 helices, if 12, will use last 11, if other won't include
Q8BUX5/59-79'
Q8BUX5/84-104'
Q8BUX5/122-142'
Q8BUX5/147-167'
Q8BUX5/176-198'
Q8BUX5/217-237'
Q8BUX5/249-269'
Q8BUX5/280-300'
Q8BUX5/302-322'
Q8BUX5/344-364'
Q8BUX5/391-411'
Q9QUT0 has 12 helices, if 12, will use last 11, if other won't include
Q9QUT0/62-82'
Q9QUT0/87-107'
Q9QUT0/122-142'
Q9QUT0/149-169'
Q9QUT0/179-199'
Q9QUT0/219-239'
Q9QUT0/250-270'
Q9QUT0/279-296'
Q9QUT0/301-321'
Q9QUT0/343-363'
Q9QUT0/373-393'
Q9QXP0 has 12 helices, if 12, will use last 11, if other won't include
Q9QXP0/62-82'
Q9QXP0/87-107'
Q9QXP0/125-145'
Q9QXP0/154-174'
Q9QXP0/180-200'
Q9QXP0/220-240'
Q9QXP0/252-272'
Q9QXP0/280-302'
Q9QXP0/305-325'
Q9QXP0/341-361'
Q9QXP0/396-416'
P55012 has 12 helices, if 12, will use last 11, if other won't include
P55012/315-336'
P55012/355-390'
P55012/400-417'
P55012/423-447'
P55012/480-500'
P55012/508-535'
P55012/593-625'
P55012/647-661'
P55012/664-690'
P55012/705-723'
P55012/725-744'
Q9WTN6 has 12 helices, if 12, will use last 11, if other won't include
Q9WTN6/143-163'
Q9WTN6/173-193'
Q9WTN6/198-218'
Q9WTN6/233-253'
Q9WTN6/258-278'
Q9WTN6/345-365'
Q9WTN6/377-397'
Q9WTN6/410-430'
Q9WTN6/434-454'
Q9WTN6/466-486'
Q9WTN6/492-512'
Q9WVL3 has 12 helices, if 12, will use last 11, if other won't include
Q9WVL3/141-161'
Q9WVL3/201-221'
Q9WVL3/253-273'
Q9WVL3/276-296'
Q9WVL3/416-436'
Q9WVL3/457-477'
Q9WVL3/494-514'
Q9WVL3/554-574'
Q9WVL3/578-598'
Q9WVL3/625-645'
Q9WVL3/845-865'
Q8R4T9 has 16 helices, if 12, will use last 11, if other won't include
Q8R4T9/311-331'
Q8R4T9/350-372'
Q8R4T9/401-421'
Q8R4T9/610-630'
Q8R4T9/648-668'
Q8R4T9/676-696'
Q8R4T9/705-725'
Q8R4T9/774-794'
Q8R4T9/813-833'
Q8R4T9/842-862'
Q8R4T9/864-884'
Q91V14 has 12 helices, if 12, will use last 11, if other won't include
Q91V14/152-176'
Q91V14/198-227'
Q91V14/252-273'
Q91V14/274-299'
Q91V14/423-443'
Q91V14/453-476'
Q91V14/509-537'
Q91V14/558-574'
Q91V14/577-601'
Q91V14/619-636'
Q91V14/638-655'
Q924N4 has 12 helices, if 12, will use last 11, if other won't include
Q924N4/217-239'
Q924N4/264-292'
Q924N4/316-338'
Q924N4/339-364'
Q924N4/485-505'
Q924N4/516-538'
Q924N4/570-596'
Q924N4/620-640'
Q924N4/641-663'
Q924N4/678-700'
Q924N4/701-716'
Q9Z306 has 12 helices, if 12, will use last 11, if other won't include
Q9Z306/143-163'
Q9Z306/172-192'
Q9Z306/198-218'
Q9Z306/233-253'
Q9Z306/258-278'
Q9Z306/340-360'
Q9Z306/374-394'
Q9Z306/401-421'
Q9Z306/429-449'
Q9Z306/463-483'
Q9Z306/489-509'
O70577 has 12 helices, if 12, will use last 11, if other won't include
O70577/151-171'
O70577/178-198'
O70577/211-231'
O70577/239-259'
O70577/264-284'
O70577/349-369'
O70577/376-396'
O70577/405-425'
O70577/433-453'
O70577/465-485'
O70577/495-515'
Q9Z0E8 has 12 helices, if 12, will use last 11, if other won't include
Q9Z0E8/143-163'
Q9Z0E8/173-193'
Q9Z0E8/198-218'
Q9Z0E8/233-253'
Q9Z0E8/258-278'
Q9Z0E8/342-362'
Q9Z0E8/374-394'
Q9Z0E8/407-427'
Q9Z0E8/431-451'
Q9Z0E8/463-483'
Q9Z0E8/489-509'
Q8BU91 has 14 helices, if 12, will use last 11, if other won't include
Q8BU91/163-191'
Q8BU91/202-224'
Q8BU91/255-275'
Q8BU91/287-299'
Q8BU91/335-358'
Q8BU91/366-379'
Q8BU91/391-400'
Q8BU91/406-419'
Q8BU91/432-457'
Q8BU91/462-476'
Q8BU91/480-498'
A0A4Y6D2A4/39-59'
A0A4Y6D2A4/71-92'
A0A4Y6D2A4/128-151'
A0A4Y6D2A4/158-177'
A0A4Y6D2A4/197-215'
A0A4Y6D2A4/227-248'
A0A4Y6D2A4/260-281'
A0A4Y6D2A4/293-312'
A0A4Y6D2A4/318-334'
A0A4Y6D2A4/346-365'
A0A4Y6D2A4/377-400'
A0A7Y4MR39/39-59'
A0A7Y4MR39/71-92'
A0A7Y4MR39/128-151'
A0A7Y4MR39/158-177'
A0A7Y4MR39/197-215'
A0A7Y4MR39/227-248'
A0A7Y4MR39/260-281'
A0A7Y4MR39/293-312'
A0A7Y4MR39/318-334'
A0A7Y4MR39/346-365'
A0A7Y4MR39/377-400'
Q1CZ61/39-59'
Q1CZ61/71-92'
Q1CZ61/128-151'
Q1CZ61/158-177'
Q1CZ61/197-215'
Q1CZ61/227-248'
Q1CZ61/260-281'
Q1CZ61/293-312'
Q1CZ61/318-334'
Q1CZ61/346-365'
Q1CZ61/377-400'
A0A8E4SIW9/39-59'
A0A8E4SIW9/71-92'
A0A8E4SIW9/128-151'
A0A8E4SIW9/158-177'
A0A8E4SIW9/197-215'
A0A8E4SIW9/227-248'
A0A8E4SIW9/260-281'
A0A8E4SIW9/293-312'
A0A8E4SIW9/318-334'
A0A8E4SIW9/346-365'
A0A8E4SIW9/377-400'
A0A4Y6CGF6/39-59'
A0A4Y6CGF6/71-92'
A0A4Y6CGF6/128-151'
A0A4Y6CGF6/158-177'
A0A4Y6CGF6/197-215'
A0A4Y6CGF6/227-248'
A0A4Y6CGF6/260-281'
A0A4Y6CGF6/293-312'
A0A4Y6CGF6/318-334'
A0A4Y6CGF6/346-365'
A0A4Y6CGF6/377-400'
A0A7Y4N5I8/39-59'
A0A7Y4N5I8/71-92'
A0A7Y4N5I8/128-151'
A0A7Y4N5I8/158-177'
A0A7Y4N5I8/197-215'
A0A7Y4N5I8/227-248'
A0A7Y4N5I8/260-281'
A0A7Y4N5I8/293-312'
A0A7Y4N5I8/318-334'
A0A7Y4N5I8/346-365'
A0A7Y4N5I8/377-400'
A0A1E3PQH0/31-55'
A0A1E3PQH0/62-82'
A0A1E3PQH0/131-149'
A0A1E3PQH0/156-176'
A0A1E3PQH0/196-214'
A0A1E3PQH0/226-248'
A0A1E3PQH0/260-280'
A0A1E3PQH0/287-306'
A0A1E3PQH0/312-332'
A0A1E3PQH0/344-370'
A0A1E3PQH0/390-418'
A0A1E3PSK5/44-65'
A0A1E3PSK5/77-95'
A0A1E3PSK5/134-154'
A0A1E3PSK5/161-185'
A0A1E3PSK5/205-222'
A0A1E3PSK5/234-253'
A0A1E3PSK5/265-286'
A0A1E3PSK5/293-311'
A0A1E3PSK5/317-336'
A0A1E3PSK5/357-375'
A0A1E3PSK5/395-420'
D2V1J4/20-42'
D2V1J4/49-69'
D2V1J4/111-131'
D2V1J4/138-159'
D2V1J4/174-195'
D2V1J4/215-236'
D2V1J4/242-266'
D2V1J4/273-290'
D2V1J4/296-317'
D2V1J4/329-352'
D2V1J4/372-393'
D2V6Q5/25-49'
D2V6Q5/61-80'
D2V6Q5/109-127'
D2V6Q5/139-159'
D2V6Q5/179-203'
D2V6Q5/224-241'
D2V6Q5/253-278'
D2V6Q5/285-307'
D2V6Q5/313-334'
D2V6Q5/346-369'
D2V6Q5/389-414'
D2V6P8 has 12 helices, if 12, will use last 11, if other won't include
D2V6P8/133-151'
D2V6P8/158-175'
D2V6P8/211-230'
D2V6P8/237-254'
D2V6P8/266-285'
D2V6P8/305-324'
D2V6P8/336-357'
D2V6P8/369-386'
D2V6P8/392-409'
D2V6P8/430-449'
D2V6P8/469-494'
D2VMN0 has 12 helices, if 12, will use last 11, if other won't include
D2VMN0/109-128'
D2VMN0/148-166'
D2VMN0/173-192'
D2VMN0/220-240'
D2VMN0/247-272'
D2VMN0/278-296'
D2VMN0/317-336'
D2VMN0/348-368'
D2VMN0/402-423'
D2VMN0/435-457'
D2VMN0/482-506'
C8XBX8/12-33'
C8XBX8/45-63'
C8XBX8/106-126'
C8XBX8/133-155'
C8XBX8/175-197'
C8XBX8/209-229'
C8XBX8/244-262'
C8XBX8/269-289'
C8XBX8/295-315'
C8XBX8/327-346'
C8XBX8/384-404'
C8XB51/6-27'
C8XB51/39-62'
C8XB51/97-119'
C8XB51/126-147'
C8XB51/167-192'
C8XB51/204-223'
C8XB51/229-256'
C8XB51/263-280'
C8XB51/286-309'
C8XB51/321-340'
C8XB51/360-385'
L0JT30/20-38'
L0JT30/59-79'
L0JT30/99-119'
L0JT30/126-146'
L0JT30/161-182'
L0JT30/203-220'
L0JT30/240-262'
L0JT30/269-286'
L0JT30/292-310'
L0JT30/322-344'
L0JT30/356-381'
A0A1I0C958/12-32'
A0A1I0C958/53-79'
A0A1I0C958/99-120'
A0A1I0C958/127-149'
A0A1I0C958/161-183'
A0A1I0C958/195-217'
A0A1I0C958/237-258'
A0A1I0C958/265-282'
A0A1I0C958/288-309'
A0A1I0C958/321-341'
A0A1I0C958/353-376'
A0A1I3M286/23-43'
A0A1I3M286/64-84'
A0A1I3M286/104-127'
A0A1I3M286/134-156'
A0A1I3M286/162-192'
A0A1I3M286/213-239'
A0A1I3M286/251-276'
A0A1I3M286/283-301'
A0A1I3M286/307-324'
A0A1I3M286/336-357'
A0A1I3M286/385-406'
L0AHQ0/23-43'
L0AHQ0/64-84'
L0AHQ0/104-127'
L0AHQ0/134-156'
L0AHQ0/162-192'
L0AHQ0/213-239'
L0AHQ0/251-276'
L0AHQ0/283-301'
L0AHQ0/307-324'
L0AHQ0/336-357'
L0AHQ0/385-406'
A0A5P9P1L2/20-41'
A0A5P9P1L2/53-74'
A0A5P9P1L2/94-117'
A0A5P9P1L2/124-149'
A0A5P9P1L2/161-181'
A0A5P9P1L2/202-219'
A0A5P9P1L2/239-261'
A0A5P9P1L2/268-285'
A0A5P9P1L2/291-312'
A0A5P9P1L2/324-343'
A0A5P9P1L2/355-380'
G0V8D6/18-39'
G0V8D6/51-69'
G0V8D6/110-130'
G0V8D6/142-160'
G0V8D6/180-197'
G0V8D6/209-228'
G0V8D6/240-261'
G0V8D6/268-286'
G0V8D6/292-311'
G0V8D6/332-350'
G0V8D6/370-395'

G0VI62/32-53'
G0VI62/65-83'
G0VI62/123-142'
G0VI62/154-175'
G0VI62/187-207'
G0VI62/228-245'
G0VI62/257-278'
G0VI62/287-306'
G0VI62/312-330'
G0VI62/342-364'
G0VI62/392-415'
G0V6N4 has 13 helices, if 12, will use last 11, if other won't include
G0V6N4/143-164'
G0V6N4/170-194'
G0V6N4/206-233'
G0V6N4/239-259'
G0V6N4/280-299'
G0V6N4/311-329'
G0V6N4/350-367'
G0V6N4/387-406'
G0V6N4/413-431'
G0V6N4/443-464'
G0V6N4/515-539'
B9L7N1/27-50'
B9L7N1/62-81'
B9L7N1/114-135'
B9L7N1/147-168'
B9L7N1/180-201'
B9L7N1/213-234'
B9L7N1/246-270'
B9L7N1/277-295'
B9L7N1/301-321'
B9L7N1/333-351'
B9L7N1/371-393'
B9L862/6-29'
B9L862/41-62'
B9L862/74-92'
B9L862/104-125'
B9L862/145-167'
B9L862/179-201'
B9L862/221-245'
B9L862/252-270'
B9L862/276-293'
B9L862/305-325'
B9L862/337-356'
D6HAK3 has 12 helices, if 12, will use last 11, if other won't include
D6HAK3/89-111'
D6HAK3/123-145'
D6HAK3/186-207'
D6HAK3/214-236'
D6HAK3/248-270'
D6HAK3/282-300'
D6HAK3/312-333'
D6HAK3/345-365'
D6HAK3/371-389'
D6HAK3/401-420'
D6HAK3/442-461'
A0A1D3GAE9/35-57'
A0A1D3GAE9/69-91'
A0A1D3GAE9/132-153'
A0A1D3GAE9/160-182'
A0A1D3GAE9/194-216'
A0A1D3GAE9/228-246'
A0A1D3GAE9/258-279'
A0A1D3GAE9/291-311'
A0A1D3GAE9/317-335'
A0A1D3GAE9/347-366'
A0A1D3GAE9/388-407'
B4RJL6 has 12 helices, if 12, will use last 11, if other won't include
B4RJL6/89-111'
B4RJL6/123-145'
B4RJL6/186-207'
B4RJL6/214-236'
B4RJL6/248-270'
B4RJL6/282-300'
B4RJL6/312-333'
B4RJL6/345-365'
B4RJL6/371-389'
B4RJL6/401-420'
B4RJL6/442-461'
Q5FA36/35-57'
Q5FA36/69-91'
Q5FA36/132-153'
Q5FA36/160-182'
Q5FA36/194-216'
Q5FA36/228-246'
Q5FA36/258-279'
Q5FA36/291-311'
Q5FA36/317-335'
Q5FA36/347-366'
Q5FA36/388-407'
A7SGD4/6-25'
A7SGD4/37-59'
A7SGD4/92-111'
A7SGD4/118-138'
A7SGD4/158-175'
A7SGD4/196-220'
A7SGD4/226-249'
A7SGD4/261-279'
A7SGD4/285-303'
A7SGD4/315-333'
A7SGD4/353-379'
A7RNC3/6-28'
A7RNC3/40-59'
A7RNC3/91-110'
A7RNC3/117-137'
A7RNC3/143-172'
A7RNC3/184-204'
A7RNC3/224-243'
A7RNC3/255-276'
A7RNC3/282-299'
A7RNC3/311-329'
A7RNC3/349-377'
A7SQ16/24-44'
A7SQ16/65-82'
A7SQ16/112-131'
A7SQ16/138-158'
A7SQ16/170-193'
A7SQ16/214-231'
A7SQ16/251-271'
A7SQ16/278-299'
A7SQ16/305-323'
A7SQ16/335-353'
A7SQ16/373-401'
A7S3L2/40-60'
A7S3L2/81-99'
A7S3L2/128-147'
A7S3L2/154-174'
A7S3L2/186-209'
A7S3L2/230-253'
A7S3L2/265-285'
A7S3L2/292-313'
A7S3L2/319-337'
A7S3L2/349-367'
A7S3L2/387-413'
A7S731/26-46'
A7S731/67-87'
A7S731/112-131'
A7S731/138-158'
A7S731/178-195'
A7S731/216-239'
A7S731/251-270'
A7S731/277-300'
A7S731/306-323'
A7S731/335-353'
A7S731/373-401'
A7SED8 has 12 helices, if 12, will use last 11, if other won't include
A7SED8/50-73'
A7SED8/85-106'
A7SED8/118-137'
A7SED8/144-163'
A7SED8/169-188'
A7SED8/209-226'
A7SED8/246-264'
A7SED8/276-295'
A7SED8/301-318'
A7SED8/339-358'
A7SED8/370-399'
A7SED7 has 12 helices, if 12, will use last 11, if other won't include
A7SED7/50-73'
A7SED7/85-106'
A7SED7/118-137'
A7SED7/144-163'
A7SED7/169-188'
A7SED7/209-226'
A7SED7/246-264'
A7SED7/276-295'
A7SED7/301-318'
A7SED7/339-358'
A7SED7/370-390'
A0A1E5TK21/6-27'
A0A1E5TK21/47-73'
A0A1E5TK21/93-114'
A0A1E5TK21/126-147'
A0A1E5TK21/159-182'
A0A1E5TK21/194-211'
A0A1E5TK21/223-244'
A0A1E5TK21/251-268'
A0A1E5TK21/274-295'
A0A1E5TK21/307-330'
A0A1E5TK21/350-372'
A0A6A1TYJ4/52-72'
A0A6A1TYJ4/84-104'
A0A6A1TYJ4/147-169'
A0A6A1TYJ4/176-200'
A0A6A1TYJ4/220-241'
A0A6A1TYJ4/253-272'
A0A6A1TYJ4/284-306'
A0A6A1TYJ4/318-338'
A0A6A1TYJ4/344-361'
A0A6A1TYJ4/373-402'
A0A6A1TYJ4/422-442'
A0A0T7FAP8/53-73'
A0A0T7FAP8/85-103'
A0A0T7FAP8/148-170'
A0A0T7FAP8/177-200'
A0A0T7FAP8/212-242'
A0A0T7FAP8/254-273'
A0A0T7FAP8/285-307'
A0A0T7FAP8/319-338'
A0A0T7FAP8/344-362'
A0A0T7FAP8/374-403'
A0A0T7FAP8/423-443'
A0A0T7GZ59/53-73'
A0A0T7GZ59/85-103'
A0A0T7GZ59/148-170'
A0A0T7GZ59/177-200'
A0A0T7GZ59/212-242'
A0A0T7GZ59/254-273'
A0A0T7GZ59/285-307'
A0A0T7GZ59/319-338'
A0A0T7GZ59/344-362'
A0A0T7GZ59/374-403'
A0A0T7GZ59/423-443'
A0A068SVR1/52-72'
A0A068SVR1/84-104'
A0A068SVR1/147-169'
A0A068SVR1/176-200'
A0A068SVR1/220-241'
A0A068SVR1/253-272'
A0A068SVR1/284-306'
A0A068SVR1/318-338'
A0A068SVR1/344-361'
A0A068SVR1/373-402'
A0A068SVR1/422-442'
A0A068TC78/52-71'
A0A068TC78/83-103'
A0A068TC78/146-168'
A0A068TC78/175-199'
A0A068TC78/219-240'
A0A068TC78/252-271'
A0A068TC78/283-305'
A0A068TC78/317-337'
A0A068TC78/343-360'
A0A068TC78/372-401'
A0A068TC78/421-441'
A0A2G6JLT9/18-39'
A0A2G6JLT9/51-73'
A0A2G6JLT9/93-113'
A0A2G6JLT9/120-138'
A0A2G6JLT9/164-185'
A0A2G6JLT9/197-221'
A0A2G6JLT9/233-255'
A0A2G6JLT9/262-281'
A0A2G6JLT9/287-304'
A0A2G6JLT9/316-335'
A0A2G6JLT9/347-372'
A0A7U8C744/22-46'
A0A7U8C744/58-77'
A0A7U8C744/107-126'
A0A7U8C744/131-148'
A0A7U8C744/168-194'
A0A7U8C744/206-229'
A0A7U8C744/249-271'
A0A7U8C744/278-296'
A0A7U8C744/302-322'
A0A7U8C744/334-353'
A0A7U8C744/359-384'
A0A7U8C2Y6/18-39'
A0A7U8C2Y6/51-73'
A0A7U8C2Y6/93-114'
A0A7U8C2Y6/121-144'
A0A7U8C2Y6/164-185'
A0A7U8C2Y6/197-221'
A0A7U8C2Y6/233-255'
A0A7U8C2Y6/262-281'
A0A7U8C2Y6/287-303'
A0A7U8C2Y6/315-335'
A0A7U8C2Y6/347-372'
A0A7R6PER3/22-46'
A0A7R6PER3/58-77'
A0A7R6PER3/118-137'
A0A7R6PER3/142-159'
A0A7R6PER3/179-199'
A0A7R6PER3/220-237'
A0A7R6PER3/257-276'
A0A7R6PER3/283-301'
A0A7R6PER3/307-327'
A0A7R6PER3/339-358'
A0A7R6PER3/364-389'
A0A7R6PPH5/18-39'
A0A7R6PPH5/51-73'
A0A7R6PPH5/93-114'
A0A7R6PPH5/121-144'
A0A7R6PPH5/164-185'
A0A7R6PPH5/197-221'
A0A7R6PPH5/233-255'
A0A7R6PPH5/262-278'
A0A7R6PPH5/284-302'
A0A7R6PPH5/314-335'
A0A7R6PPH5/347-372'
A0A0U1NJW3/32-56'
A0A0U1NJW3/77-96'
A0A0U1NJW3/135-154'
A0A0U1NJW3/159-176'
A0A0U1NJW3/196-216'
A0A0U1NJW3/236-253'
A0A0U1NJW3/273-291'
A0A0U1NJW3/303-320'
A0A0U1NJW3/326-346'
A0A0U1NJW3/353-374'
A0A0U1NJW3/380-404'
A0A0B0E8R7/40-60'
A0A0B0E8R7/67-88'
A0A0B0E8R7/128-148'
A0A0B0E8R7/155-176'
A0A0B0E8R7/196-214'
A0A0B0E8R7/235-253'
A0A0B0E8R7/265-286'
A0A0B0E8R7/293-311'
A0A0B0E8R7/317-337'
A0A0B0E8R7/349-370'
A0A0B0E8R7/399-422'
A0A0B0DML0/37-57'
A0A0B0DML0/69-87'
A0A0B0DML0/127-147'
A0A0B0DML0/159-179'
A0A0B0DML0/191-213'
A0A0B0DML0/225-245'
A0A0B0DML0/257-278'
A0A0B0DML0/285-303'
A0A0B0DML0/309-327'
A0A0B0DML0/348-368'
A0A0B0DML0/388-410'
Q8X0D3/36-57'
Q8X0D3/69-87'
Q8X0D3/123-144'
Q8X0D3/156-176'
Q8X0D3/188-209'
Q8X0D3/230-247'
Q8X0D3/259-280'
Q8X0D3/292-311'
Q8X0D3/317-337'
Q8X0D3/349-370'
Q8X0D3/403-421'
Q1K8A3/36-57'
Q1K8A3/69-87'
Q1K8A3/123-144'
Q1K8A3/156-176'
Q1K8A3/188-209'
Q1K8A3/230-247'
Q1K8A3/259-280'
Q1K8A3/292-311'
Q1K8A3/317-337'
Q1K8A3/349-370'
Q1K8A3/403-421'
Q7S5K0/40-60'
Q7S5K0/67-88'
Q7S5K0/128-148'
Q7S5K0/155-176'
Q7S5K0/196-214'
Q7S5K0/235-253'
Q7S5K0/265-286'
Q7S5K0/293-311'
Q7S5K0/317-337'
Q7S5K0/349-370'
Q7S5K0/399-422'
Q7SEH0/37-57'
Q7SEH0/69-87'
Q7SEH0/127-147'
Q7SEH0/159-179'
Q7SEH0/191-213'
Q7SEH0/225-245'
Q7SEH0/257-278'
Q7SEH0/285-303'
Q7SEH0/309-327'
Q7SEH0/348-368'
Q7SEH0/388-410'
A0A0B0DUN5 has 12 helices, if 12, will use last 11, if other won't include
A0A0B0DUN5/144-164'
A0A0B0DUN5/170-194'
A0A0B0DUN5/206-227'
A0A0B0DUN5/233-256'
A0A0B0DUN5/276-295'
A0A0B0DUN5/307-325'
A0A0B0DUN5/345-364'
A0A0B0DUN5/384-403'
A0A0B0DUN5/410-428'
A0A0B0DUN5/473-493'
A0A0B0DUN5/513-537'
A0A0B0DW36 has 12 helices, if 12, will use last 11, if other won't include
A0A0B0DW36/67-87'
A0A0B0DW36/99-125'
A0A0B0DW36/160-182'
A0A0B0DW36/188-211'
A0A0B0DW36/286-304'
A0A0B0DW36/325-346'
A0A0B0DW36/366-384'
A0A0B0DW36/391-411'
A0A0B0DW36/417-443'
A0A0B0DW36/455-477'
A0A0B0DW36/519-545'
Q7S6U7 has 12 helices, if 12, will use last 11, if other won't include
Q7S6U7/144-164'
Q7S6U7/170-194'
Q7S6U7/206-227'
Q7S6U7/233-256'
Q7S6U7/276-295'
Q7S6U7/307-325'
Q7S6U7/345-364'
Q7S6U7/384-403'
Q7S6U7/410-428'
Q7S6U7/473-493'
Q7S6U7/513-537'
Q7S343 has 12 helices, if 12, will use last 11, if other won't include
Q7S343/67-87'
Q7S343/99-125'
Q7S343/160-182'
Q7S343/188-211'
Q7S343/287-305'
Q7S343/326-347'
Q7S343/367-385'
Q7S343/392-412'
Q7S343/418-444'
Q7S343/456-478'
Q7S343/520-546'
W0F0I7/44-66'
W0F0I7/78-106'
W0F0I7/126-150'
W0F0I7/162-183'
W0F0I7/195-218'
W0F0I7/230-249'
W0F0I7/261-282'
W0F0I7/294-312'
W0F0I7/318-335'
W0F0I7/347-366'
W0F0I7/386-408'
G8TK79/41-63'
G8TK79/87-111'
G8TK79/123-143'
G8TK79/203-222'
G8TK79/248-269'
G8TK79/290-307'
G8TK79/327-348'
G8TK79/355-375'
G8TK79/381-399'
G8TK79/411-429'
G8TK79/463-484'
G8TK77/44-66'
G8TK77/78-101'
G8TK77/137-158'
G8TK77/165-186'
G8TK77/198-221'
G8TK77/233-255'
G8TK77/267-291'
G8TK77/298-319'
G8TK77/325-341'
G8TK77/353-372'
G8TK77/392-416'

A0A1H4KAQ7/45-68'
A0A1H4KAQ7/89-109'
A0A1H4KAQ7/140-159'
A0A1H4KAQ7/164-182'
A0A1H4KAQ7/202-221'
A0A1H4KAQ7/242-259'
A0A1H4KAQ7/279-298'
A0A1H4KAQ7/305-323'
A0A1H4KAQ7/329-351'
A0A1H4KAQ7/363-380'
A0A1H4KAQ7/386-411'
I5C044/49-72'
I5C044/93-113'
I5C044/144-163'
I5C044/168-186'
I5C044/206-225'
I5C044/246-263'
I5C044/283-302'
I5C044/309-327'
I5C044/333-355'
I5C044/367-384'
I5C044/390-415'
A0A063Y780/15-40'
A0A063Y780/52-71'
A0A063Y780/112-130'
A0A063Y780/137-157'
A0A063Y780/172-193'
A0A063Y780/214-231'
A0A063Y780/251-270'
A0A063Y780/277-295'
A0A063Y780/301-323'
A0A063Y780/335-352'
A0A063Y780/358-383'
A0A063Y394/27-48'
A0A063Y394/60-81'
A0A063Y394/115-137'
A0A063Y394/144-165'
A0A063Y394/185-203'
A0A063Y394/224-247'
A0A063Y394/262-283'
A0A063Y394/288-305'
A0A063Y394/311-332'
A0A063Y394/339-360'
A0A063Y394/380-400'
I5BYV5/12-34'
I5BYV5/55-84'
I5BYV5/104-123'
I5BYV5/128-146'
I5BYV5/166-187'
I5BYV5/207-224'
I5BYV5/239-261'
I5BYV5/268-288'
I5BYV5/294-312'
I5BYV5/324-342'
I5BYV5/354-375'
Q1QS12/55-75'
Q1QS12/87-109'
Q1QS12/143-165'
Q1QS12/172-194'
Q1QS12/206-227'
Q1QS12/239-260'
Q1QS12/272-291'
Q1QS12/303-323'
Q1QS12/329-347'
Q1QS12/359-378'
Q1QS12/398-422'
A4BMY5/29-50'
A4BMY5/62-82'
A4BMY5/121-142'
A4BMY5/149-171'
A4BMY5/183-204'
A4BMY5/216-236'
A4BMY5/248-268'
A4BMY5/280-297'
A4BMY5/303-321'
A4BMY5/333-356'
A4BMY5/376-396'
Q82X47/42-62'
Q82X47/74-98'
Q82X47/104-123'
Q82X47/128-144'
Q82X47/164-184'
Q82X47/205-225'
Q82X47/231-253'
Q82X47/260-278'
Q82X47/284-304'
Q82X47/325-344'
Q82X47/350-368'
Q5YL87/42-62'
Q5YL87/74-98'
Q5YL87/104-123'
Q5YL87/128-144'
Q5YL87/164-184'
Q5YL87/205-225'
Q5YL87/231-253'
Q5YL87/260-278'
Q5YL87/284-304'
Q5YL87/325-344'
Q5YL87/350-368'
A0A060HN92/12-33'
A0A060HN92/45-66'
A0A060HN92/101-121'
A0A060HN92/128-150'
A0A060HN92/162-183'
A0A060HN92/195-216'
A0A060HN92/228-249'
A0A060HN92/261-280'
A0A060HN92/286-303'
A0A060HN92/315-334'
A0A060HN92/354-376'
A0A060HFT5/82-103'
A0A060HFT5/115-135'
A0A060HFT5/178-198'
A0A060HFT5/205-226'
A0A060HFT5/254-276'
A0A060HFT5/288-308'
A0A060HFT5/320-340'
A0A060HFT5/352-369'
A0A060HFT5/375-394'
A0A060HFT5/406-425'
A0A060HFT5/445-467'
A0A060HSP0 has 12 helices, if 12, will use last 11, if other won't include
A0A060HSP0/78-100'
A0A060HSP0/112-131'
A0A060HSP0/179-198'
A0A060HSP0/205-226'
A0A060HSP0/254-276'
A0A060HSP0/288-308'
A0A060HSP0/320-340'
A0A060HSP0/352-369'
A0A060HSP0/375-394'
A0A060HSP0/406-425'
A0A060HSP0/445-467'
A0A977NL98/12-33'
A0A977NL98/45-66'
A0A977NL98/101-121'
A0A977NL98/128-150'
A0A977NL98/162-183'
A0A977NL98/195-216'
A0A977NL98/228-249'
A0A977NL98/261-280'
A0A977NL98/286-303'
A0A977NL98/315-334'
A0A977NL98/354-376'
A0A977NM15/58-79'
A0A977NM15/91-111'
A0A977NM15/154-174'
A0A977NM15/181-202'
A0A977NM15/230-252'
A0A977NM15/264-284'
A0A977NM15/296-316'
A0A977NM15/328-345'
A0A977NM15/351-370'
A0A977NM15/382-401'
A0A977NM15/421-443'
A0A977NL43 has 12 helices, if 12, will use last 11, if other won't include
A0A977NL43/78-100'
A0A977NL43/112-131'
A0A977NL43/179-198'
A0A977NL43/205-226'
A0A977NL43/254-276'
A0A977NL43/288-308'
A0A977NL43/320-340'
A0A977NL43/352-369'
A0A977NL43/375-394'
A0A977NL43/406-425'
A0A977NL43/445-467'
A0A1I7FBM5/44-63'
A0A1I7FBM5/75-94'
A0A1I7FBM5/106-124'
A0A1I7FBM5/129-145'
A0A1I7FBM5/165-184'
A0A1I7FBM5/204-226'
A0A1I7FBM5/232-250'
A0A1I7FBM5/262-283'
A0A1I7FBM5/289-309'
A0A1I7FBM5/321-340'
A0A1I7FBM5/346-369'
A0A1H8D0R8/44-63'
A0A1H8D0R8/75-94'
A0A1H8D0R8/106-124'
A0A1H8D0R8/129-145'
A0A1H8D0R8/165-184'
A0A1H8D0R8/204-226'
A0A1H8D0R8/232-250'
A0A1H8D0R8/262-281'
A0A1H8D0R8/287-305'
A0A1H8D0R8/326-345'
A0A1H8D0R8/351-369'
A0A1I0AQM4/44-63'
A0A1I0AQM4/75-94'
A0A1I0AQM4/106-124'
A0A1I0AQM4/129-145'
A0A1I0AQM4/165-184'
A0A1I0AQM4/204-226'
A0A1I0AQM4/232-250'
A0A1I0AQM4/262-283'
A0A1I0AQM4/289-309'
A0A1I0AQM4/321-343'
A0A1I0AQM4/349-369'
A0A2T5IHP0/44-63'
A0A2T5IHP0/75-94'
A0A2T5IHP0/106-124'
A0A2T5IHP0/129-145'
A0A2T5IHP0/165-184'
A0A2T5IHP0/204-226'
A0A2T5IHP0/232-250'
A0A2T5IHP0/262-283'
A0A2T5IHP0/289-309'
A0A2T5IHP0/321-340'
A0A2T5IHP0/346-369'
Q2YBP7/44-63'
Q2YBP7/75-94'
Q2YBP7/106-124'
Q2YBP7/129-145'
Q2YBP7/165-184'
Q2YBP7/204-226'
Q2YBP7/232-250'
Q2YBP7/262-283'
Q2YBP7/289-309'
Q2YBP7/321-343'
Q2YBP7/349-369'
D8PD01/47-69'
D8PD01/81-100'
D8PD01/136-157'
D8PD01/164-186'
D8PD01/198-219'
D8PD01/231-252'
D8PD01/258-283'
D8PD01/295-313'
D8PD01/319-338'
D8PD01/350-369'
D8PD01/389-411'
A0A6G9XJV9/12-32'
A0A6G9XJV9/44-66'
A0A6G9XJV9/99-120'
A0A6G9XJV9/127-149'
A0A6G9XJV9/161-185'
A0A6G9XJV9/197-217'
A0A6G9XJV9/223-248'
A0A6G9XJV9/260-277'
A0A6G9XJV9/283-303'
A0A6G9XJV9/315-338'
A0A6G9XJV9/358-379'
A0A6G9Y3Q0/6-22'
A0A6G9Y3Q0/29-49'
A0A6G9Y3Q0/108-129'
A0A6G9Y3Q0/136-157'
A0A6G9Y3Q0/184-206'
A0A6G9Y3Q0/218-238'
A0A6G9Y3Q0/250-271'
A0A6G9Y3Q0/278-296'
A0A6G9Y3Q0/302-324'
A0A6G9Y3Q0/336-356'
A0A6G9Y3Q0/376-400'
A0A379A6M6/12-32'
A0A379A6M6/44-66'
A0A379A6M6/99-120'
A0A379A6M6/127-149'
A0A379A6M6/161-185'
A0A379A6M6/197-217'
A0A379A6M6/223-248'
A0A379A6M6/260-277'
A0A379A6M6/283-303'
A0A379A6M6/315-338'
A0A379A6M6/358-379'
A0A379BXA9/15-37'
A0A379BXA9/44-65'
A0A379BXA9/124-145'
A0A379BXA9/152-173'
A0A379BXA9/200-222'
A0A379BXA9/234-254'
A0A379BXA9/266-287'
A0A379BXA9/294-312'
A0A379BXA9/318-340'
A0A379BXA9/352-372'
A0A379BXA9/392-416'
A0A7K2IV20/6-28'
A0A7K2IV20/40-58'
A0A7K2IV20/102-121'
A0A7K2IV20/128-149'
A0A7K2IV20/169-191'
A0A7K2IV20/203-223'
A0A7K2IV20/235-256'
A0A7K2IV20/263-284'
A0A7K2IV20/290-309'
A0A7K2IV20/321-340'
A0A7K2IV20/360-383'
J7L3W8/6-28'
J7L3W8/40-58'
J7L3W8/102-121'
J7L3W8/128-149'
J7L3W8/169-191'
J7L3W8/203-223'
J7L3W8/235-256'
J7L3W8/263-284'
J7L3W8/290-309'
J7L3W8/321-340'
J7L3W8/360-383'
A0ZJU7/78-97'
A0ZJU7/118-137'
A0ZJU7/182-202'
A0ZJU7/209-230'
A0ZJU7/242-263'
A0ZJU7/275-300'
A0ZJU7/312-339'
A0ZJU7/346-366'
A0ZJU7/372-389'
A0ZJU7/401-427'
A0ZJU7/447-471'
A0A166IS52/78-97'
A0A166IS52/118-137'
A0A166IS52/182-202'
A0A166IS52/209-230'
A0A166IS52/242-263'
A0A166IS52/275-300'
A0A166IS52/312-339'
A0A166IS52/346-366'
A0A166IS52/372-389'
A0A166IS52/401-427'
A0A166IS52/447-471'
A0A2S0Q8P1/78-97'
A0A2S0Q8P1/118-137'
A0A2S0Q8P1/182-202'
A0A2S0Q8P1/209-230'
A0A2S0Q8P1/242-263'
A0A2S0Q8P1/275-300'
A0A2S0Q8P1/312-339'
A0A2S0Q8P1/346-366'
A0A2S0Q8P1/372-389'
A0A2S0Q8P1/401-427'
A0A2S0Q8P1/447-471'
A0A7X0DNL6/50-74'
A0A7X0DNL6/81-102'
A0A7X0DNL6/138-160'
A0A7X0DNL6/167-189'
A0A7X0DNL6/201-222'
A0A7X0DNL6/234-255'
A0A7X0DNL6/261-285'
A0A7X0DNL6/297-318'
A0A7X0DNL6/324-342'
A0A7X0DNL6/354-375'
A0A7X0DNL6/395-416'
A0A7W9ZEG0/6-27'
A0A7W9ZEG0/48-70'
A0A7W9ZEG0/90-109'
A0A7W9ZEG0/121-141'
A0A7W9ZEG0/161-182'
A0A7W9ZEG0/203-220'
A0A7W9ZEG0/232-253'
A0A7W9ZEG0/260-276'
A0A7W9ZEG0/282-299'
A0A7W9ZEG0/311-333'
A0A7W9ZEG0/345-370'
A0A420WC79/44-66'
A0A420WC79/78-97'
A0A420WC79/151-170'
A0A420WC79/175-192'
A0A420WC79/212-232'
A0A420WC79/253-270'
A0A420WC79/290-313'
A0A420WC79/320-336'
A0A420WC79/342-362'
A0A420WC79/374-394'
A0A420WC79/400-421'
K2JVF8/45-67'
K2JVF8/79-98'
K2JVF8/152-171'
K2JVF8/176-193'
K2JVF8/213-233'
K2JVF8/254-271'
K2JVF8/291-314'
K2JVF8/321-337'
K2JVF8/343-363'
K2JVF8/375-395'
K2JVF8/401-422'
A3TVQ9/38-59'
A3TVQ9/80-99'
A3TVQ9/137-156'
A3TVQ9/161-178'
A3TVQ9/198-218'
A3TVQ9/239-256'
A3TVQ9/276-294'
A3TVQ9/306-324'
A3TVQ9/330-349'
A3TVQ9/356-377'
A3TVQ9/383-408'
A0A7C4VLK5/28-51'
A0A7C4VLK5/63-83'
A0A7C4VLK5/114-133'
A0A7C4VLK5/140-161'
A0A7C4VLK5/181-198'
A0A7C4VLK5/210-231'
A0A7C4VLK5/243-263'
A0A7C4VLK5/275-294'
A0A7C4VLK5/300-317'
A0A7C4VLK5/329-352'
A0A7C4VLK5/372-395'
E4U5Z1/29-52'
E4U5Z1/64-84'
E4U5Z1/115-134'
E4U5Z1/141-162'
E4U5Z1/182-201'
E4U5Z1/213-232'
E4U5Z1/244-264'
E4U5Z1/276-295'
E4U5Z1/301-318'
E4U5Z1/330-349'
E4U5Z1/369-396'
Q8ERT9/31-52'
Q8ERT9/73-95'
Q8ERT9/115-135'
Q8ERT9/142-163'
Q8ERT9/183-203'
Q8ERT9/215-235'
Q8ERT9/247-269'
Q8ERT9/281-298'
Q8ERT9/304-323'
Q8ERT9/335-356'
Q8ERT9/368-393'
M9RKT6/32-56'
M9RKT6/77-96'
M9RKT6/134-153'
M9RKT6/158-175'
M9RKT6/195-215'
M9RKT6/235-252'
M9RKT6/272-291'
M9RKT6/298-316'
M9RKT6/322-344'
M9RKT6/356-379'
M9RKT6/385-403'
M9RJS5/6-28'
M9RJS5/40-63'
M9RJS5/94-116'
M9RJS5/123-144'
M9RJS5/164-185'
M9RJS5/197-215'
M9RJS5/227-246'
M9RJS5/258-276'
M9RJS5/282-302'
M9RJS5/314-335'
M9RJS5/341-362'
A0A375YPN6/20-40'
A0A375YPN6/52-74'
A0A375YPN6/108-130'
A0A375YPN6/137-158'
A0A375YPN6/173-194'
A0A375YPN6/215-241'
A0A375YPN6/253-274'
A0A375YPN6/281-298'
A0A375YPN6/304-321'
A0A375YPN6/333-357'
A0A375YPN6/369-393'

A0A483BDN6/36-56'
A0A483BDN6/63-82'
A0A483BDN6/94-117'
A0A483BDN6/124-146'
A0A483BDN6/158-180'
A0A483BDN6/192-212'
A0A483BDN6/224-246'
A0A483BDN6/258-277'
A0A483BDN6/283-300'
A0A483BDN6/312-332'
A0A483BDN6/352-375'
D3LBI0/36-56'
D3LBI0/63-82'
D3LBI0/94-117'
D3LBI0/124-146'
D3LBI0/158-180'
D3LBI0/192-212'
D3LBI0/224-246'
D3LBI0/258-277'
D3LBI0/283-300'
D3LBI0/312-332'
D3LBI0/352-375'
A0NJ07/36-56'
A0NJ07/63-82'
A0NJ07/94-117'
A0NJ07/124-146'
A0NJ07/158-180'
A0NJ07/192-212'
A0NJ07/224-246'
A0NJ07/258-277'
A0NJ07/283-300'
A0NJ07/312-332'
A0NJ07/352-375'
Q04DE4/36-56'
Q04DE4/63-82'
Q04DE4/94-117'
Q04DE4/124-146'
Q04DE4/158-180'
Q04DE4/192-212'
Q04DE4/224-246'
Q04DE4/258-277'
Q04DE4/283-300'
Q04DE4/312-332'
Q04DE4/352-375'
E4XXT2/6-26'
E4XXT2/47-66'
E4XXT2/86-108'
E4XXT2/115-137'
E4XXT2/160-182'
E4XXT2/203-221'
E4XXT2/233-254'
E4XXT2/275-296'
E4XXT2/302-323'
E4XXT2/335-353'
E4XXT2/388-414'
E4YA63/27-49'
E4YA63/61-81'
E4YA63/138-157'
E4YA63/164-185'
E4YA63/208-230'
E4YA63/251-271'
E4YA63/283-305'
E4YA63/326-346'
E4YA63/352-369'
E4YA63/381-403'
E4YA63/464-490'
B1ZSW9/93-114'
B1ZSW9/126-144'
B1ZSW9/187-205'
B1ZSW9/212-234'
B1ZSW9/254-276'
B1ZSW9/288-307'
B1ZSW9/319-339'
B1ZSW9/351-372'
B1ZSW9/378-395'
B1ZSW9/407-426'
B1ZSW9/446-467'
A0A4R8H081/33-57'
A0A4R8H081/78-101'
A0A4R8H081/121-140'
A0A4R8H081/152-172'
A0A4R8H081/184-204'
A0A4R8H081/225-242'
A0A4R8H081/254-279'
A0A4R8H081/286-304'
A0A4R8H081/310-327'
A0A4R8H081/339-360'
A0A4R8H081/380-400'
A0A4R8GSH7/12-32'
A0A4R8GSH7/53-72'
A0A4R8GSH7/92-111'
A0A4R8GSH7/120-141'
A0A4R8GSH7/161-183'
A0A4R8GSH7/204-224'
A0A4R8GSH7/230-252'
A0A4R8GSH7/259-276'
A0A4R8GSH7/282-299'
A0A4R8GSH7/311-336'
A0A4R8GSH7/348-369'
Q84KJ7/29-49'
Q84KJ7/57-77'
Q84KJ7/127-147'
Q84KJ7/161-181'
Q84KJ7/190-210'
Q84KJ7/225-245'
Q84KJ7/252-272'
Q84KJ7/285-305'
Q84KJ7/309-329'
Q84KJ7/343-363'
Q84KJ7/399-419'
Q7XQ12/39-59'
Q7XQ12/74-94'
Q7XQ12/120-140'
Q7XQ12/148-168'
Q7XQ12/192-212'
Q7XQ12/236-256'
Q7XQ12/274-296'
Q7XQ12/307-327'
Q7XQ12/331-351'
Q7XQ12/360-380'
Q7XQ12/411-431'
Q6K9G3/41-61'
Q6K9G3/76-96'
Q6K9G3/122-142'
Q6K9G3/150-170'
Q6K9G3/194-214'
Q6K9G3/238-258'
Q6K9G3/277-299'
Q6K9G3/307-327'
Q6K9G3/329-349'
Q6K9G3/362-382'
Q6K9G3/414-434'
Q94JG1 has 12 helices, if 12, will use last 11, if other won't include
Q94JG1/76-96'
Q94JG1/112-132'
Q94JG1/142-162'
Q94JG1/172-192'
Q94JG1/209-229'
Q94JG1/265-285'
Q94JG1/299-319'
Q94JG1/335-354'
Q94JG1/367-387'
Q94JG1/395-415'
Q94JG1/425-445'
Q6K9G1/39-59'
Q6K9G1/74-94'
Q6K9G1/120-140'
Q6K9G1/148-168'
Q6K9G1/192-212'
Q6K9G1/236-256'
Q6K9G1/274-296'
Q6K9G1/307-327'
Q6K9G1/331-351'
Q6K9G1/360-380'
Q6K9G1/412-432'
P0DKG9 has 12 helices, if 12, will use last 11, if other won't include
P0DKG9/101-122'
P0DKG9/133-153'
P0DKG9/160-180'
P0DKG9/190-210'
P0DKG9/227-247'
P0DKG9/283-303'
P0DKG9/319-339'
P0DKG9/351-371'
P0DKG9/384-404'
P0DKG9/411-431'
P0DKG9/442-462'
P0DKH0 has 12 helices, if 12, will use last 11, if other won't include
P0DKH0/101-122'
P0DKH0/133-153'
P0DKH0/160-180'
P0DKH0/190-210'
P0DKH0/227-247'
P0DKH0/283-303'
P0DKH0/319-339'
P0DKH0/351-371'
P0DKH0/384-404'
P0DKH0/411-431'
P0DKH0/442-462'
Q84KJ6/33-53'
Q84KJ6/58-78'
Q84KJ6/143-163'
Q84KJ6/171-191'
Q84KJ6/206-226'
Q84KJ6/241-261'
Q84KJ6/276-296'
Q84KJ6/301-321'
Q84KJ6/325-345'
Q84KJ6/369-389'
Q84KJ6/412-432'
Q69T29/31-51'
Q69T29/59-79'
Q69T29/135-155'
Q69T29/169-189'
Q69T29/198-218'
Q69T29/233-253'
Q69T29/265-287'
Q69T29/292-314'
Q69T29/318-337'
Q69T29/361-381'
Q69T29/407-427'
Q8S233/32-52'
Q8S233/60-80'
Q8S233/136-156'
Q8S233/170-190'
Q8S233/199-219'
Q8S233/234-254'
Q8S233/270-290'
Q8S233/294-314'
Q8S233/318-338'
Q8S233/352-372'
Q8S233/408-428'
Q851M9/34-54'
Q851M9/59-79'
Q851M9/139-159'
Q851M9/164-184'
Q851M9/202-222'
Q851M9/237-257'
Q851M9/272-292'
Q851M9/297-317'
Q851M9/321-341'
Q851M9/355-375'
Q851M9/407-427'
Q8S230/35-55'
Q8S230/64-84'
Q8S230/140-160'
Q8S230/174-194'
Q8S230/203-223'
Q8S230/238-258'
Q8S230/274-294'
Q8S230/298-318'
Q8S230/322-342'
Q8S230/356-376'
Q8S230/412-432'
A0A158URW8/29-51'
A0A158URW8/63-82'
A0A158URW8/144-163'
A0A158URW8/170-196'
A0A158URW8/208-226'
A0A158URW8/238-258'
A0A158URW8/270-294'
A0A158URW8/301-319'
A0A158URW8/325-345'
A0A158URW8/366-391'
A0A158URW8/411-433'
E1IF27/20-40'
E1IF27/45-63'
E1IF27/83-103'
E1IF27/110-131'
E1IF27/143-167'
E1IF27/179-199'
E1IF27/205-230'
E1IF27/242-260'
E1IF27/266-283'
E1IF27/295-316'
E1IF27/336-361'
G8R7U9 has 12 helices, if 12, will use last 11, if other won't include
G8R7U9/37-58'
G8R7U9/70-93'
G8R7U9/127-146'
G8R7U9/158-178'
G8R7U9/190-213'
G8R7U9/225-243'
G8R7U9/255-276'
G8R7U9/285-303'
G8R7U9/309-327'
G8R7U9/347-367'
G8R7U9/373-395'
C3X831/59-80'
C3X831/92-110'
C3X831/149-171'
C3X831/178-200'
C3X831/212-232'
C3X831/244-266'
C3X831/278-298'
C3X831/310-330'
C3X831/336-353'
C3X831/365-384'
C3X831/404-426'
C3X1J1/56-77'
C3X1J1/89-107'
C3X1J1/146-168'
C3X1J1/175-197'
C3X1J1/209-229'
C3X1J1/241-263'
C3X1J1/275-295'
C3X1J1/307-327'
C3X1J1/333-350'
C3X1J1/362-381'
C3X1J1/401-423'
A0A9E9LS75/54-75'
A0A9E9LS75/87-105'
A0A9E9LS75/144-166'
A0A9E9LS75/173-195'
A0A9E9LS75/207-227'
A0A9E9LS75/239-261'
A0A9E9LS75/273-293'
A0A9E9LS75/305-325'
A0A9E9LS75/331-348'
A0A9E9LS75/360-379'
A0A9E9LS75/399-421'
A0A9E9L9J1/54-75'
A0A9E9L9J1/87-105'
A0A9E9L9J1/144-166'
A0A9E9L9J1/173-195'
A0A9E9L9J1/207-227'
A0A9E9L9J1/239-261'
A0A9E9L9J1/273-293'
A0A9E9L9J1/305-325'
A0A9E9L9J1/331-348'
A0A9E9L9J1/360-379'
A0A9E9L9J1/399-421'
A0A9E9LXV9/34-56'
A0A9E9LXV9/68-88'
A0A9E9LXV9/125-147'
A0A9E9LXV9/154-176'
A0A9E9LXV9/188-210'
A0A9E9LXV9/222-241'
A0A9E9LXV9/253-274'
A0A9E9LXV9/286-306'
A0A9E9LXV9/312-329'
A0A9E9LXV9/341-360'
A0A9E9LXV9/380-401'
A0A7S4LPL9/31-50'
A0A7S4LPL9/62-80'
A0A7S4LPL9/122-140'
A0A7S4LPL9/147-166'
A0A7S4LPL9/186-207'
A0A7S4LPL9/228-245'
A0A7S4LPL9/265-283'
A0A7S4LPL9/295-313'
A0A7S4LPL9/319-337'
A0A7S4LPL9/349-367'
A0A7S4LPL9/387-410'
A0A7S4GND2/31-50'
A0A7S4GND2/62-80'
A0A7S4GND2/122-140'
A0A7S4GND2/147-166'
A0A7S4GND2/186-207'
A0A7S4GND2/228-245'
A0A7S4GND2/265-283'
A0A7S4GND2/295-313'
A0A7S4GND2/319-337'
A0A7S4GND2/349-367'
A0A7S4GND2/387-410'
A0A7S4GNJ2/31-50'
A0A7S4GNJ2/62-80'
A0A7S4GNJ2/122-140'
A0A7S4GNJ2/147-166'
A0A7S4GNJ2/186-207'
A0A7S4GNJ2/228-245'
A0A7S4GNJ2/265-283'
A0A7S4GNJ2/295-313'
A0A7S4GNJ2/319-337'
A0A7S4GNJ2/349-367'
A0A7S4GNJ2/387-410'
A0A7S4LPS8/31-50'
A0A7S4LPS8/62-80'
A0A7S4LPS8/122-140'
A0A7S4LPS8/147-166'
A0A7S4LPS8/186-207'
A0A7S4LPS8/228-245'
A0A7S4LPS8/265-283'
A0A7S4LPS8/295-313'
A0A7S4LPS8/319-337'
A0A7S4LPS8/349-367'
A0A7S4LPS8/387-410'
A0A7S4GMD8/52-76'
A0A7S4GMD8/88-109'
A0A7S4GMD8/129-150'
A0A7S4GMD8/162-182'
A0A7S4GMD8/202-225'
A0A7S4GMD8/246-268'
A0A7S4GMD8/283-306'
A0A7S4GMD8/318-337'
A0A7S4GMD8/343-362'
A0A7S4GMD8/382-404'
A0A7S4GMD8/424-452'
A0A7S4GNI0/31-50'
A0A7S4GNI0/62-80'
A0A7S4GNI0/122-140'
A0A7S4GNI0/147-166'
A0A7S4GNI0/186-207'
A0A7S4GNI0/228-245'
A0A7S4GNI0/265-283'
A0A7S4GNI0/295-313'
A0A7S4GNI0/319-337'
A0A7S4GNI0/349-367'
A0A7S4GNI0/387-410'
A0A7S4GNF3/31-50'
A0A7S4GNF3/62-80'
A0A7S4GNF3/122-140'
A0A7S4GNF3/147-166'
A0A7S4GNF3/186-207'
A0A7S4GNF3/228-245'
A0A7S4GNF3/265-283'
A0A7S4GNF3/295-313'
A0A7S4GNF3/319-337'
A0A7S4GNF3/349-367'
A0A7S4GNF3/387-410'
G4H971/40-65'
G4H971/77-97'
G4H971/132-153'
G4H971/160-182'
G4H971/194-215'
G4H971/236-253'
G4H971/265-293'
G4H971/300-318'
G4H971/324-342'
G4H971/354-376'
G4H971/396-420'
E4T3F3/62-83'
E4T3F3/104-129'
E4T3F3/159-179'
E4T3F3/200-221'
E4T3F3/241-262'
E4T3F3/283-300'
E4T3F3/312-337'
E4T3F3/349-367'
E4T3F3/373-391'
E4T3F3/398-420'
E4T3F3/446-468'
E4T3F7/37-58'
E4T3F7/70-88'
E4T3F7/145-167'
E4T3F7/174-195'
E4T3F7/207-231'
E4T3F7/243-263'
E4T3F7/275-299'
E4T3F7/306-326'
E4T3F7/332-350'
E4T3F7/362-389'
E4T3F7/401-422'
E4T0A4/6-28'
E4T0A4/40-58'
E4T0A4/104-126'
E4T0A4/133-155'
E4T0A4/167-188'
E4T0A4/200-217'
E4T0A4/223-249'
E4T0A4/261-278'
E4T0A4/284-302'
E4T0A4/314-335'
E4T0A4/355-378'
A0A856LCH5/83-104'
A0A856LCH5/116-134'
A0A856LCH5/176-198'
A0A856LCH5/205-229'
A0A856LCH5/258-280'
A0A856LCH5/292-312'
A0A856LCH5/324-344'
A0A856LCH5/356-376'
A0A856LCH5/382-399'
A0A856LCH5/411-431'
A0A856LCH5/457-479'
A0A378YR15/83-104'
A0A378YR15/116-134'
A0A378YR15/176-198'
A0A378YR15/205-229'
A0A378YR15/258-280'
A0A378YR15/292-312'
A0A378YR15/324-344'
A0A378YR15/356-376'
A0A378YR15/382-399'
A0A378YR15/411-431'
A0A378YR15/457-479'

A0A8T8BI10/86-107'
A0A8T8BI10/119-137'
A0A8T8BI10/179-201'
A0A8T8BI10/208-231'
A0A8T8BI10/261-283'
A0A8T8BI10/295-315'
A0A8T8BI10/327-347'
A0A8T8BI10/359-379'
A0A8T8BI10/385-402'
A0A8T8BI10/414-434'
A0A8T8BI10/460-482'
A0A378YY10/12-32'
A0A378YY10/44-66'
A0A378YY10/86-107'
A0A378YY10/119-137'
A0A378YY10/157-180'
A0A378YY10/201-221'
A0A378YY10/227-249'
A0A378YY10/256-272'
A0A378YY10/278-296'
A0A378YY10/308-329'
A0A378YY10/341-363'
A0A8T8BK87/12-32'
A0A8T8BK87/44-66'
A0A8T8BK87/86-107'
A0A8T8BK87/119-137'
A0A8T8BK87/157-180'
A0A8T8BK87/201-221'
A0A8T8BK87/227-249'
A0A8T8BK87/256-274'
A0A8T8BK87/280-298'
A0A8T8BK87/310-329'
A0A8T8BK87/341-363'
A0A379A0S9/52-73'
A0A379A0S9/94-113'
A0A379A0S9/147-166'
A0A379A0S9/173-195'
A0A379A0S9/207-228'
A0A379A0S9/249-266'
A0A379A0S9/286-305'
A0A379A0S9/312-330'
A0A379A0S9/336-358'
A0A379A0S9/370-387'
A0A379A0S9/393-418'
A0A0H3KTD3/43-63'
A0A0H3KTD3/70-90'
A0A0H3KTD3/126-148'
A0A0H3KTD3/155-177'
A0A0H3KTD3/189-211'
A0A0H3KTD3/223-242'
A0A0H3KTD3/254-273'
A0A0H3KTD3/285-303'
A0A0H3KTD3/309-330'
A0A0H3KTD3/342-361'
A0A0H3KTD3/381-402'
D4GLQ6/44-64'
D4GLQ6/71-91'
D4GLQ6/127-149'
D4GLQ6/156-178'
D4GLQ6/190-212'
D4GLQ6/224-243'
D4GLQ6/255-274'
D4GLQ6/286-304'
D4GLQ6/310-331'
D4GLQ6/343-362'
D4GLQ6/382-403'
A0A6G6JU01/32-54'
A0A6G6JU01/66-84'
A0A6G6JU01/120-142'
A0A6G6JU01/149-171'
A0A6G6JU01/183-205'
A0A6G6JU01/217-236'
A0A6G6JU01/248-267'
A0A6G6JU01/279-297'
A0A6G6JU01/303-324'
A0A6G6JU01/336-355'
A0A6G6JU01/375-396'
A0A7K0HBQ0/17-36'
A0A7K0HBQ0/57-79'
A0A7K0HBQ0/99-119'
A0A7K0HBQ0/126-147'
A0A7K0HBQ0/172-193'
A0A7K0HBQ0/214-231'
A0A7K0HBQ0/251-272'
A0A7K0HBQ0/279-296'
A0A7K0HBQ0/302-323'
A0A7K0HBQ0/335-355'
A0A7K0HBQ0/367-390'
A0A1D2JK63/51-71'
A0A1D2JK63/83-101'
A0A1D2JK63/141-162'
A0A1D2JK63/169-193'
A0A1D2JK63/205-227'
A0A1D2JK63/239-259'
A0A1D2JK63/271-292'
A0A1D2JK63/299-317'
A0A1D2JK63/323-341'
A0A1D2JK63/362-383'
A0A1D2JK63/403-428'
C1G973/51-71'
C1G973/83-101'
C1G973/141-162'
C1G973/169-193'
C1G973/205-227'
C1G973/239-259'
C1G973/271-292'
C1G973/299-317'
C1G973/323-341'
C1G973/362-383'
C1G973/403-428'
C0S0W9/51-71'
C0S0W9/83-101'
C0S0W9/141-162'
C0S0W9/169-193'
C0S0W9/205-227'
C0S0W9/239-259'
C0S0W9/271-292'
C0S0W9/299-317'
C0S0W9/323-341'
C0S0W9/362-383'
C0S0W9/403-428'
C1GR74/51-71'
C1GR74/83-101'
C1GR74/141-162'
C1GR74/169-193'
C1GR74/205-227'
C1GR74/239-259'
C1GR74/271-292'
C1GR74/299-317'
C1GR74/323-341'
C1GR74/362-383'
C1GR74/403-428'
A0A533I6R2/36-57'
A0A533I6R2/64-84'
A0A533I6R2/135-157'
A0A533I6R2/164-188'
A0A533I6R2/208-229'
A0A533I6R2/241-261'
A0A533I6R2/273-292'
A0A533I6R2/304-323'
A0A533I6R2/329-349'
A0A533I6R2/361-386'
A0A533I6R2/406-428'
A1B3N0/55-75'
A1B3N0/87-110'
A1B3N0/156-176'
A1B3N0/183-209'
A1B3N0/229-250'
A1B3N0/262-283'
A1B3N0/295-314'
A1B3N0/326-344'
A1B3N0/350-370'
A1B3N0/382-402'
A1B3N0/433-457'
A0CBN6/32-52'
A0CBN6/64-86'
A0CBN6/118-135'
A0CBN6/142-160'
A0CBN6/180-199'
A0CBN6/220-240'
A0CBN6/252-273'
A0CBN6/280-299'
A0CBN6/305-326'
A0CBN6/338-362'
A0CBN6/374-398'
A0DZ27/35-54'
A0DZ27/66-84'
A0DZ27/121-140'
A0DZ27/145-166'
A0DZ27/186-202'
A0DZ27/223-239'
A0DZ27/251-273'
A0DZ27/285-302'
A0DZ27/308-328'
A0DZ27/340-358'
A0DZ27/378-398'
A0BIN7/33-52'
A0BIN7/64-82'
A0BIN7/119-136'
A0BIN7/143-167'
A0BIN7/179-200'
A0BIN7/221-243'
A0BIN7/255-276'
A0BIN7/283-301'
A0BIN7/307-326'
A0BIN7/338-356'
A0BIN7/376-396'
A0BJ48/34-53'
A0BJ48/65-83'
A0BJ48/120-139'
A0BJ48/144-165'
A0BJ48/185-201'
A0BJ48/222-238'
A0BJ48/250-272'
A0BJ48/284-301'
A0BJ48/307-327'
A0BJ48/339-357'
A0BJ48/377-397'
A0DQP0/32-51'
A0DQP0/63-81'
A0DQP0/115-135'
A0DQP0/142-166'
A0DQP0/178-199'
A0DQP0/220-236'
A0DQP0/256-275'
A0DQP0/282-300'
A0DQP0/306-325'
A0DQP0/337-355'
A0DQP0/375-395'
A0BNP4/30-49'
A0BNP4/61-79'
A0BNP4/116-133'
A0BNP4/140-158'
A0BNP4/178-197'
A0BNP4/218-234'
A0BNP4/246-268'
A0BNP4/280-298'
A0BNP4/304-323'
A0BNP4/335-353'
A0BNP4/373-393'
A0E7D8/6-27'
A0E7D8/39-61'
A0E7D8/92-109'
A0E7D8/116-140'
A0E7D8/152-173'
A0E7D8/194-214'
A0E7D8/226-247'
A0E7D8/254-272'
A0E7D8/278-298'
A0E7D8/310-327'
A0E7D8/342-366'
A0EG61/6-27'
A0EG61/39-61'
A0EG61/92-109'
A0EG61/116-140'
A0EG61/152-173'
A0EG61/194-214'
A0EG61/226-247'
A0EG61/254-272'
A0EG61/278-298'
A0EG61/310-327'
A0EG61/342-366'
A0CLK6/26-50'
A0CLK6/62-81'
A0CLK6/111-130'
A0CLK6/137-158'
A0CLK6/170-191'
A0CLK6/212-236'
A0CLK6/248-268'
A0CLK6/277-297'
A0CLK6/303-323'
A0CLK6/335-352'
A0CLK6/364-387'
A0EC09/30-49'
A0EC09/61-79'
A0EC09/116-133'
A0EC09/140-158'
A0EC09/178-197'
A0EC09/218-234'
A0EC09/246-268'
A0EC09/280-298'
A0EC09/304-323'
A0EC09/335-353'
A0EC09/373-393'
A0BE57/20-45'
A0BE57/57-82'
A0BE57/102-121'
A0BE57/126-148'
A0BE57/168-185'
A0BE57/205-223'
A0BE57/235-257'
A0BE57/269-288'
A0BE57/294-314'
A0BE57/326-344'
A0BE57/364-384'
A0E040/27-46'
A0E040/58-76'
A0E040/113-130'
A0E040/137-155'
A0E040/175-194'
A0E040/215-231'
A0E040/243-270'
A0E040/277-295'
A0E040/301-320'
A0E040/332-350'
A0E040/370-390'
A0EAD9/20-45'
A0EAD9/57-76'
A0EAD9/104-124'
A0EAD9/131-152'
A0EAD9/164-185'
A0EAD9/206-230'
A0EAD9/242-264'
A0EAD9/271-290'
A0EAD9/296-317'
A0EAD9/329-346'
A0EAD9/366-386'
A0EGB0/20-45'
A0EGB0/57-76'
A0EGB0/104-124'
A0EGB0/131-152'
A0EGB0/164-185'
A0EGB0/206-230'
A0EGB0/242-264'
A0EGB0/271-290'
A0EGB0/296-317'
A0EGB0/329-346'
A0EGB0/366-386'
A0E1C2/26-46'
A0E1C2/58-81'
A0E1C2/114-131'
A0E1C2/138-159'
A0E1C2/179-195'
A0E1C2/216-236'
A0E1C2/248-271'
A0E1C2/278-295'
A0E1C2/301-322'
A0E1C2/334-354'
A0E1C2/366-388'
A0A1H1U2Q6/12-32'
A0A1H1U2Q6/39-60'
A0A1H1U2Q6/104-126'
A0A1H1U2Q6/133-154'
A0A1H1U2Q6/189-211'
A0A1H1U2Q6/223-243'
A0A1H1U2Q6/255-275'
A0A1H1U2Q6/287-304'
A0A1H1U2Q6/310-329'
A0A1H1U2Q6/341-368'
A0A1H1U2Q6/374-399'
F3QPR6/12-34'
F3QPR6/46-69'
F3QPR6/108-129'
F3QPR6/136-159'
F3QPR6/171-192'
F3QPR6/204-226'
F3QPR6/238-258'
F3QPR6/270-287'
F3QPR6/293-313'
F3QPR6/325-345'
F3QPR6/365-387'
A0A6I3S3R3/33-52'
A0A6I3S3R3/59-79'
A0A6I3S3R3/117-138'
A0A6I3S3R3/145-166'
A0A6I3S3R3/178-201'
A0A6I3S3R3/213-234'
A0A6I3S3R3/246-265'
A0A6I3S3R3/277-297'
A0A6I3S3R3/303-321'
A0A6I3S3R3/333-356'
A0A6I3S3R3/368-390'
F3QNA7/33-52'
F3QNA7/59-79'
F3QNA7/117-138'
F3QNA7/145-166'
F3QNA7/178-201'
F3QNA7/213-234'
F3QNA7/246-265'
F3QNA7/277-297'
F3QNA7/303-321'
F3QNA7/333-356'
F3QNA7/368-390'
A7HSP2/49-71'
A7HSP2/83-102'
A7HSP2/137-158'
A7HSP2/165-187'
A7HSP2/199-220'
A7HSP2/232-253'
A7HSP2/265-284'
A7HSP2/296-316'
A7HSP2/322-340'
A7HSP2/352-374'
A7HSP2/394-416'
A7HT14/12-30'
A7HT14/51-75'
A7HT14/95-119'
A7HT14/126-147'
A7HT14/167-188'
A7HT14/209-232'
A7HT14/238-259'
A7HT14/271-287'
A7HT14/293-311'
A7HT14/323-341'
A7HT14/361-381'
A7HSN9/17-37'
A7HSN9/58-80'
A7HSN9/100-120'
A7HSN9/132-152'
A7HSN9/172-193'
A7HSN9/214-231'
A7HSN9/243-264'
A7HSN9/271-290'
A7HSN9/296-313'
A7HSN9/325-345'
A7HSN9/357-381'
E0TGP9/35-57'
E0TGP9/78-97'
E0TGP9/129-147'
E0TGP9/154-174'
E0TGP9/194-212'
E0TGP9/224-248'
E0TGP9/268-291'
E0TGP9/298-316'
E0TGP9/322-342'
E0TGP9/354-375'
E0TGP9/381-406'
E0TCV4/43-63'
E0TCV4/84-103'
E0TCV4/139-157'
E0TCV4/164-184'
E0TCV4/204-222'
E0TCV4/234-257'
E0TCV4/277-300'
E0TCV4/307-325'
E0TCV4/331-350'
E0TCV4/357-377'
E0TCV4/389-409'
C6DB68/32-54'
C6DB68/66-84'
C6DB68/123-142'
C6DB68/149-171'
C6DB68/183-205'
C6DB68/217-237'
C6DB68/243-268'
C6DB68/280-299'
C6DB68/305-324'
C6DB68/336-354'
C6DB68/374-396'
A0A837DQS9/32-54'
A0A837DQS9/66-84'
A0A837DQS9/123-142'
A0A837DQS9/149-171'
A0A837DQS9/183-205'
A0A837DQS9/217-237'
A0A837DQS9/243-268'
A0A837DQS9/280-299'
A0A837DQS9/305-324'
A0A837DQS9/336-354'
A0A837DQS9/374-396'
A0A7T5QRS5/32-54'
A0A7T5QRS5/66-84'
A0A7T5QRS5/123-142'
A0A7T5QRS5/149-171'
A0A7T5QRS5/183-205'
A0A7T5QRS5/217-237'
A0A7T5QRS5/243-268'
A0A7T5QRS5/280-299'
A0A7T5QRS5/305-324'
A0A7T5QRS5/336-354'
A0A7T5QRS5/374-396'
A0A7V8TEX2/32-54'
A0A7V8TEX2/66-84'
A0A7V8TEX2/123-142'
A0A7V8TEX2/149-171'
A0A7V8TEX2/183-205'
A0A7V8TEX2/217-237'
A0A7V8TEX2/243-268'
A0A7V8TEX2/280-299'
A0A7V8TEX2/305-324'
A0A7V8TEX2/336-354'
A0A7V8TEX2/374-396'
A0A419AI10/34-56'
A0A419AI10/68-86'
A0A419AI10/125-144'
A0A419AI10/151-173'
A0A419AI10/185-207'
A0A419AI10/219-239'
A0A419AI10/245-270'
A0A419AI10/282-301'
A0A419AI10/307-326'
A0A419AI10/338-356'
A0A419AI10/376-398'
A0A419AVL2/34-56'
A0A419AVL2/68-86'
A0A419AVL2/125-144'
A0A419AVL2/151-173'
A0A419AVL2/185-207'
A0A419AVL2/219-239'
A0A419AVL2/245-270'
A0A419AVL2/282-301'
A0A419AVL2/307-326'
A0A419AVL2/338-356'
A0A419AVL2/376-398'
A0A7V8IKS6/32-54'
A0A7V8IKS6/66-84'
A0A7V8IKS6/123-142'
A0A7V8IKS6/149-171'
A0A7V8IKS6/183-205'
A0A7V8IKS6/217-237'
A0A7V8IKS6/249-268'
A0A7V8IKS6/280-299'
A0A7V8IKS6/305-324'
A0A7V8IKS6/336-354'
A0A7V8IKS6/374-396'

A0A0J6AS72/32-54'
A0A0J6AS72/66-84'
A0A0J6AS72/123-142'
A0A0J6AS72/149-171'
A0A0J6AS72/183-205'
A0A0J6AS72/217-237'
A0A0J6AS72/249-268'
A0A0J6AS72/280-299'
A0A0J6AS72/305-324'
A0A0J6AS72/336-354'
A0A0J6AS72/374-396'
A0A086F0C2/32-54'
A0A086F0C2/66-84'
A0A086F0C2/123-142'
A0A086F0C2/149-171'
A0A086F0C2/183-205'
A0A086F0C2/217-237'
A0A086F0C2/243-268'
A0A086F0C2/280-299'
A0A086F0C2/305-324'
A0A086F0C2/336-354'
A0A086F0C2/374-396'
A0A433P2R5/32-54'
A0A433P2R5/66-84'
A0A433P2R5/123-142'
A0A433P2R5/149-171'
A0A433P2R5/183-205'
A0A433P2R5/217-237'
A0A433P2R5/243-268'
A0A433P2R5/280-299'
A0A433P2R5/305-324'
A0A433P2R5/336-354'
A0A433P2R5/374-396'
A0A7V8TJ53/32-54'
A0A7V8TJ53/66-84'
A0A7V8TJ53/123-142'
A0A7V8TJ53/149-171'
A0A7V8TJ53/183-205'
A0A7V8TJ53/217-237'
A0A7V8TJ53/243-268'
A0A7V8TJ53/280-299'
A0A7V8TJ53/305-324'
A0A7V8TJ53/336-354'
A0A7V8TJ53/374-396'
A0A221TCD6/32-54'
A0A221TCD6/66-84'
A0A221TCD6/123-142'
A0A221TCD6/149-171'
A0A221TCD6/183-205'
A0A221TCD6/217-237'
A0A221TCD6/243-268'
A0A221TCD6/280-299'
A0A221TCD6/305-324'
A0A221TCD6/336-354'
A0A221TCD6/374-396'
E0VUA6/27-50'
E0VUA6/62-80'
E0VUA6/112-134'
E0VUA6/141-161'
E0VUA6/181-200'
E0VUA6/212-232'
E0VUA6/252-273'
E0VUA6/280-302'
E0VUA6/308-329'
E0VUA6/336-354'
E0VUA6/374-407'
G4R7P1/49-74'
G4R7P1/86-103'
G4R7P1/155-174'
G4R7P1/179-196'
G4R7P1/216-236'
G4R7P1/257-274'
G4R7P1/294-317'
G4R7P1/324-342'
G4R7P1/348-366'
G4R7P1/378-397'
G4R7P1/403-426'
A0A165MFD1/44-63'
A0A165MFD1/84-102'
A0A165MFD1/135-155'
A0A165MFD1/162-183'
A0A165MFD1/195-216'
A0A165MFD1/237-254'
A0A165MFD1/274-297'
A0A165MFD1/304-324'
A0A165MFD1/330-349'
A0A165MFD1/356-375'
A0A165MFD1/381-405'
A0A165MAC2/34-57'
A0A165MAC2/69-90'
A0A165MAC2/125-147'
A0A165MAC2/154-176'
A0A165MAC2/196-215'
A0A165MAC2/227-246'
A0A165MAC2/258-278'
A0A165MAC2/290-308'
A0A165MAC2/314-332'
A0A165MAC2/344-367'
A0A165MAC2/387-410'
Q3B3Q6/44-63'
Q3B3Q6/84-102'
Q3B3Q6/135-155'
Q3B3Q6/162-183'
Q3B3Q6/195-216'
Q3B3Q6/237-254'
Q3B3Q6/274-297'
Q3B3Q6/304-324'
Q3B3Q6/330-349'
Q3B3Q6/356-375'
Q3B3Q6/381-405'
Q3B6Q2/34-57'
Q3B6Q2/69-90'
Q3B6Q2/125-147'
Q3B6Q2/154-176'
Q3B6Q2/196-215'
Q3B6Q2/227-246'
Q3B6Q2/258-278'
Q3B6Q2/290-308'
Q3B6Q2/314-332'
Q3B6Q2/344-367'
Q3B6Q2/387-410'
A5D4I5/44-65'
A5D4I5/77-95'
A5D4I5/136-157'
A5D4I5/164-185'
A5D4I5/197-220'
A5D4I5/232-253'
A5D4I5/265-285'
A5D4I5/297-316'
A5D4I5/322-340'
A5D4I5/352-371'
A5D4I5/391-413'
C5KTM6/63-87'
C5KTM6/99-121'
C5KTM6/153-173'
C5KTM6/180-201'
C5KTM6/221-238'
C5KTM6/259-276'
C5KTM6/288-314'
C5KTM6/326-348'
C5KTM6/354-373'
C5KTM6/382-402'
C5KTM6/422-444'
C5LAG4/74-93'
C5LAG4/114-133'
C5LAG4/163-183'
C5LAG4/190-210'
C5LAG4/222-248'
C5LAG4/269-286'
C5LAG4/306-327'
C5LAG4/334-353'
C5LAG4/359-378'
C5LAG4/390-408'
C5LAG4/428-452'
C0QSY0/29-51'
C0QSY0/63-81'
C0QSY0/121-143'
C0QSY0/150-172'
C0QSY0/184-204'
C0QSY0/216-238'
C0QSY0/250-270'
C0QSY0/282-301'
C0QSY0/307-325'
C0QSY0/337-357'
C0QSY0/377-402'
C0QTA4/12-30'
C0QTA4/42-60'
C0QTA4/97-122'
C0QTA4/129-151'
C0QTA4/163-184'
C0QTA4/196-214'
C0QTA4/226-246'
C0QTA4/258-275'
C0QTA4/281-301'
C0QTA4/313-331'
C0QTA4/351-372'
A9BIZ7/39-57'
A9BIZ7/78-102'
A9BIZ7/114-135'
A9BIZ7/147-167'
A9BIZ7/179-199'
A9BIZ7/220-237'
A9BIZ7/257-276'
A9BIZ7/283-300'
A9BIZ7/306-325'
A9BIZ7/337-356'
A9BIZ7/368-391'
A0A1B0ZRL8/32-56'
A0A1B0ZRL8/77-96'
A0A1B0ZRL8/136-155'
A0A1B0ZRL8/160-177'
A0A1B0ZRL8/197-217'
A0A1B0ZRL8/237-254'
A0A1B0ZRL8/274-292'
A0A1B0ZRL8/304-321'
A0A1B0ZRL8/327-347'
A0A1B0ZRL8/354-375'
A0A1B0ZRL8/381-406'
A0A366WYI9/38-59'
A0A366WYI9/80-99'
A0A366WYI9/139-156'
A0A366WYI9/163-180'
A0A366WYI9/200-220'
A0A366WYI9/241-258'
A0A366WYI9/278-296'
A0A366WYI9/308-326'
A0A366WYI9/332-351'
A0A366WYI9/358-379'
A0A366WYI9/385-407'
V9WGS2/47-70'
V9WGS2/82-101'
V9WGS2/144-161'
V9WGS2/168-185'
V9WGS2/205-225'
V9WGS2/245-262'
V9WGS2/282-305'
V9WGS2/312-329'
V9WGS2/335-355'
V9WGS2/362-383'
V9WGS2/389-414'
A0A291FN84/6-32'
A0A291FN84/44-75'
A0A291FN84/95-117'
A0A291FN84/124-145'
A0A291FN84/165-185'
A0A291FN84/197-215'
A0A291FN84/227-247'
A0A291FN84/259-278'
A0A291FN84/284-302'
A0A291FN84/314-335'
A0A291FN84/341-359'
A0A366XFS8/6-28'
A0A366XFS8/40-63'
A0A366XFS8/95-117'
A0A366XFS8/124-145'
A0A366XFS8/165-185'
A0A366XFS8/197-215'
A0A366XFS8/227-246'
A0A366XFS8/258-276'
A0A366XFS8/282-302'
A0A366XFS8/314-335'
A0A366XFS8/341-359'
V9WF46/6-32'
V9WF46/44-75'
V9WF46/95-117'
V9WF46/124-145'
V9WF46/165-185'
V9WF46/197-215'
V9WF46/227-247'
V9WF46/259-278'
V9WF46/284-302'
V9WF46/314-332'
V9WF46/338-359'
A0A291G3C0/47-70'
A0A291G3C0/82-101'
A0A291G3C0/144-161'
A0A291G3C0/168-185'
A0A291G3C0/205-225'
A0A291G3C0/245-262'
A0A291G3C0/282-305'
A0A291G3C0/312-329'
A0A291G3C0/335-355'
A0A291G3C0/362-383'
A0A291G3C0/389-414'
A0A291FRY6/47-70'
A0A291FRY6/82-101'
A0A291FRY6/144-161'
A0A291FRY6/168-185'
A0A291FRY6/205-225'
A0A291FRY6/245-262'
A0A291FRY6/282-305'
A0A291FRY6/312-329'
A0A291FRY6/335-355'
A0A291FRY6/362-383'
A0A291FRY6/389-414'
A0A0B4DUR9/38-59'
A0A0B4DUR9/80-98'
A0A0B4DUR9/141-160'
A0A0B4DUR9/165-182'
A0A0B4DUR9/202-222'
A0A0B4DUR9/242-259'
A0A0B4DUR9/279-302'
A0A0B4DUR9/309-326'
A0A0B4DUR9/332-352'
A0A0B4DUR9/359-380'
A0A0B4DUR9/386-411'
A0A0B4DVJ9/22-41'
A0A0B4DVJ9/62-83'
A0A0B4DVJ9/121-139'
A0A0B4DVJ9/151-171'
A0A0B4DVJ9/183-202'
A0A0B4DVJ9/222-252'
A0A0B4DVJ9/272-291'
A0A0B4DVJ9/296-314'
A0A0B4DVJ9/320-337'
A0A0B4DVJ9/349-368'
A0A0B4DVJ9/394-419'
A0A0B4E6X7/15-36'
A0A0B4E6X7/48-70'
A0A0B4E6X7/107-129'
A0A0B4E6X7/136-157'
A0A0B4E6X7/177-194'
A0A0B4E6X7/215-240'
A0A0B4E6X7/260-285'
A0A0B4E6X7/292-309'
A0A0B4E6X7/315-333'
A0A0B4E6X7/345-368'
A0A0B4E6X7/388-406'
A0A8J9SEP2/6-23'
A0A8J9SEP2/35-54'
A0A8J9SEP2/89-111'
A0A8J9SEP2/118-141'
A0A8J9SEP2/161-182'
A0A8J9SEP2/203-222'
A0A8J9SEP2/242-267'
A0A8J9SEP2/279-296'
A0A8J9SEP2/302-324'
A0A8J9SEP2/344-364'
A0A8J9SEP2/384-409'
A0A8J9S765/6-27'
A0A8J9S765/39-58'
A0A8J9S765/85-107'
A0A8J9S765/114-135'
A0A8J9S765/155-178'
A0A8J9S765/205-228'
A0A8J9S765/240-264'
A0A8J9S765/276-293'
A0A8J9S765/299-316'
A0A8J9S765/328-351'
A0A8J9S765/379-406'
B7FTM9/6-23'
B7FTM9/35-54'
B7FTM9/89-111'
B7FTM9/118-141'
B7FTM9/161-182'
B7FTM9/203-222'
B7FTM9/242-267'
B7FTM9/279-296'
B7FTM9/302-324'
B7FTM9/344-364'
B7FTM9/384-409'
B7G0Y1/6-28'
B7G0Y1/40-59'
B7G0Y1/89-109'
B7G0Y1/116-138'
B7G0Y1/158-181'
B7G0Y1/202-221'
B7G0Y1/241-263'
B7G0Y1/275-296'
B7G0Y1/302-324'
B7G0Y1/331-352'
B7G0Y1/388-409'
B7G0Y4/52-76'
B7G0Y4/88-109'
B7G0Y4/129-150'
B7G0Y4/162-182'
B7G0Y4/202-225'
B7G0Y4/246-268'
B7G0Y4/283-306'
B7G0Y4/318-337'
B7G0Y4/343-362'
B7G0Y4/382-404'
B7G0Y4/424-452'
B7FSA7/6-27'
B7FSA7/39-58'
B7FSA7/85-107'
B7FSA7/114-135'
B7FSA7/155-178'
B7FSA7/205-228'
B7FSA7/240-263'
B7FSA7/275-292'
B7FSA7/298-315'
B7FSA7/327-350'
B7FSA7/378-405'
B7FW68/15-39'
B7FW68/51-70'
B7FW68/98-117'
B7FW68/124-146'
B7FW68/166-189'
B7FW68/210-229'
B7FW68/249-271'
B7FW68/283-304'
B7FW68/310-327'
B7FW68/339-360'
B7FW68/396-417'
A0A098S5Y7/12-35'
A0A098S5Y7/47-67'
A0A098S5Y7/106-125'
A0A098S5Y7/132-154'
A0A098S5Y7/166-187'
A0A098S5Y7/208-225'
A0A098S5Y7/237-264'
A0A098S5Y7/271-289'
A0A098S5Y7/295-313'
A0A098S5Y7/325-344'
A0A098S5Y7/356-376'
A0A2W5PER0/85-106'
A0A2W5PER0/118-138'
A0A2W5PER0/181-201'
A0A2W5PER0/208-226'
A0A2W5PER0/260-282'
A0A2W5PER0/294-314'
A0A2W5PER0/326-345'
A0A2W5PER0/357-375'
A0A2W5PER0/381-401'
A0A2W5PER0/413-433'
A0A2W5PER0/474-493'
A0A227JQV4/53-76'
A0A227JQV4/83-104'
A0A227JQV4/150-170'
A0A227JQV4/177-199'
A0A227JQV4/211-232'
A0A227JQV4/244-264'
A0A227JQV4/276-297'
A0A227JQV4/309-328'
A0A227JQV4/334-352'
A0A227JQV4/364-383'
A0A227JQV4/403-421'
Q6LMI6/12-33'
Q6LMI6/54-74'
Q6LMI6/104-123'
Q6LMI6/128-145'
Q6LMI6/165-185'
Q6LMI6/206-223'
Q6LMI6/243-262'
Q6LMI6/269-287'
Q6LMI6/293-315'
Q6LMI6/327-344'
Q6LMI6/350-375'
Q1Z4I4/12-33'
Q1Z4I4/54-74'
Q1Z4I4/104-123'
Q1Z4I4/128-145'
Q1Z4I4/165-185'
Q1Z4I4/206-223'
Q1Z4I4/243-262'
Q1Z4I4/269-287'
Q1Z4I4/293-315'
Q1Z4I4/327-344'
Q1Z4I4/350-375'
Q1Z695/18-39'
Q1Z695/51-73'
Q1Z695/93-113'
Q1Z695/120-138'
Q1Z695/164-185'
Q1Z695/197-221'
Q1Z695/233-255'
Q1Z695/262-280'
Q1Z695/286-304'
Q1Z695/316-335'
Q1Z695/347-372'
Q6LKC8/20-42'
Q6LKC8/54-76'
Q6LKC8/96-117'
Q6LKC8/124-147'
Q6LKC8/167-188'
Q6LKC8/200-224'
Q6LKC8/236-258'
Q6LKC8/265-283'
Q6LKC8/289-307'
Q6LKC8/319-338'
Q6LKC8/350-375'
A0A2S8QG68/32-54'
A0A2S8QG68/66-86'
A0A2S8QG68/117-138'
A0A2S8QG68/145-163'
A0A2S8QG68/183-205'
A0A2S8QG68/217-236'
A0A2S8QG68/248-268'
A0A2S8QG68/280-299'
A0A2S8QG68/305-324'
A0A2S8QG68/336-356'
A0A2S8QG68/376-396'
A0A4V2X6C2/32-54'
A0A4V2X6C2/66-86'
A0A4V2X6C2/117-138'
A0A4V2X6C2/145-163'
A0A4V2X6C2/183-205'
A0A4V2X6C2/217-236'
A0A4V2X6C2/248-268'
A0A4V2X6C2/280-299'
A0A4V2X6C2/305-324'
A0A4V2X6C2/336-356'
A0A4V2X6C2/376-396'

A0A5C4RNH5/32-58'
A0A5C4RNH5/70-97'
A0A5C4RNH5/117-138'
A0A5C4RNH5/145-163'
A0A5C4RNH5/183-205'
A0A5C4RNH5/217-236'
A0A5C4RNH5/248-268'
A0A5C4RNH5/280-299'
A0A5C4RNH5/305-324'
A0A5C4RNH5/336-356'
A0A5C4RNH5/376-396'
A0A6L9JJM6/32-54'
A0A6L9JJM6/66-86'
A0A6L9JJM6/117-138'
A0A6L9JJM6/145-163'
A0A6L9JJM6/183-205'
A0A6L9JJM6/217-236'
A0A6L9JJM6/248-268'
A0A6L9JJM6/280-299'
A0A6L9JJM6/305-324'
A0A6L9JJM6/336-356'
A0A6L9JJM6/376-396'
Q7N0M6/44-66'
Q7N0M6/78-98'
Q7N0M6/129-150'
Q7N0M6/157-175'
Q7N0M6/195-217'
Q7N0M6/229-248'
Q7N0M6/260-280'
Q7N0M6/292-311'
Q7N0M6/317-336'
Q7N0M6/348-368'
Q7N0M6/388-408'
C7BJG7/32-54'
C7BJG7/66-86'
C7BJG7/117-138'
C7BJG7/145-163'
C7BJG7/183-205'
C7BJG7/217-236'
C7BJG7/248-268'
C7BJG7/280-299'
C7BJG7/305-324'
C7BJG7/336-356'
C7BJG7/376-396'
A0A4R4K1P9/32-54'
A0A4R4K1P9/66-86'
A0A4R4K1P9/117-138'
A0A4R4K1P9/145-163'
A0A4R4K1P9/183-205'
A0A4R4K1P9/217-236'
A0A4R4K1P9/248-268'
A0A4R4K1P9/280-299'
A0A4R4K1P9/305-324'
A0A4R4K1P9/336-356'
A0A4R4K1P9/376-396'
A0A1G5PWV0/44-70'
A0A1G5PWV0/82-109'
A0A1G5PWV0/129-150'
A0A1G5PWV0/157-175'
A0A1G5PWV0/195-217'
A0A1G5PWV0/229-248'
A0A1G5PWV0/260-280'
A0A1G5PWV0/292-311'
A0A1G5PWV0/317-336'
A0A1G5PWV0/348-368'
A0A1G5PWV0/388-408'
A0A0A0CQ38/26-48'
A0A0A0CQ38/60-80'
A0A0A0CQ38/111-132'
A0A0A0CQ38/139-157'
A0A0A0CQ38/177-199'
A0A0A0CQ38/211-230'
A0A0A0CQ38/242-262'
A0A0A0CQ38/274-293'
A0A0A0CQ38/299-318'
A0A0A0CQ38/330-350'
A0A0A0CQ38/370-390'
A0A2S8R5K1/44-66'
A0A2S8R5K1/78-98'
A0A2S8R5K1/129-150'
A0A2S8R5K1/157-175'
A0A2S8R5K1/195-217'
A0A2S8R5K1/229-248'
A0A2S8R5K1/260-280'
A0A2S8R5K1/292-311'
A0A2S8R5K1/317-336'
A0A2S8R5K1/348-368'
A0A2S8R5K1/388-408'
A0A2S8QA29/44-66'
A0A2S8QA29/78-98'
A0A2S8QA29/129-150'
A0A2S8QA29/157-175'
A0A2S8QA29/195-217'
A0A2S8QA29/229-248'
A0A2S8QA29/260-280'
A0A2S8QA29/292-311'
A0A2S8QA29/317-336'
A0A2S8QA29/348-368'
A0A2S8QA29/388-408'
I0ICG0/55-74'
I0ICG0/94-114'
I0ICG0/152-172'
I0ICG0/179-200'
I0ICG0/212-233'
I0ICG0/254-271'
I0ICG0/283-305'
I0ICG0/317-333'
I0ICG0/339-359'
I0ICG0/371-394'
I0ICG0/406-431'
H3GCZ7/76-101'
H3GCZ7/113-141'
H3GCZ7/161-184'
H3GCZ7/191-211'
H3GCZ7/231-257'
H3GCZ7/269-288'
H3GCZ7/294-317'
H3GCZ7/329-346'
H3GCZ7/352-374'
H3GCZ7/386-405'
H3GCZ7/425-450'
H3GCZ5/70-93'
H3GCZ5/105-132'
H3GCZ5/152-172'
H3GCZ5/184-205'
H3GCZ5/229-251'
H3GCZ5/263-282'
H3GCZ5/294-315'
H3GCZ5/322-340'
H3GCZ5/346-366'
H3GCZ5/378-399'
H3GCZ5/419-444'
H3G9J8/6-23'
H3G9J8/30-52'
H3G9J8/64-86'
H3G9J8/93-112'
H3G9J8/124-144'
H3G9J8/156-173'
H3G9J8/193-212'
H3G9J8/224-243'
H3G9J8/249-270'
H3G9J8/282-304'
H3G9J8/330-354'
D2R355/57-78'
D2R355/90-108'
D2R355/163-182'
D2R355/189-210'
D2R355/240-262'
D2R355/274-294'
D2R355/306-325'
D2R355/337-355'
D2R355/361-381'
D2R355/393-417'
D2R355/437-463'
D2R647/89-108'
D2R647/129-147'
D2R647/181-201'
D2R647/208-229'
D2R647/241-262'
D2R647/282-299'
D2R647/319-342'
D2R647/349-369'
D2R647/375-391'
D2R647/403-421'
D2R647/433-457'
A0A2Z6CF98 has 12 helices, if 12, will use last 11, if other won't include
A0A2Z6CF98/80-98'
A0A2Z6CF98/119-138'
A0A2Z6CF98/170-191'
A0A2Z6CF98/198-215'
A0A2Z6CF98/235-256'
A0A2Z6CF98/277-294'
A0A2Z6CF98/306-330'
A0A2Z6CF98/337-354'
A0A2Z6CF98/360-381'
A0A2Z6CF98/393-413'
A0A2Z6CF98/419-440'
A0A073CP02 has 12 helices, if 12, will use last 11, if other won't include
A0A073CP02/87-105'
A0A073CP02/126-145'
A0A073CP02/177-198'
A0A073CP02/205-222'
A0A073CP02/242-263'
A0A073CP02/284-301'
A0A073CP02/313-337'
A0A073CP02/344-361'
A0A073CP02/367-388'
A0A073CP02/400-420'
A0A073CP02/426-447'
A0A1J1JH03 has 12 helices, if 12, will use last 11, if other won't include
A0A1J1JH03/87-105'
A0A1J1JH03/126-145'
A0A1J1JH03/177-198'
A0A1J1JH03/205-222'
A0A1J1JH03/242-263'
A0A1J1JH03/284-301'
A0A1J1JH03/313-337'
A0A1J1JH03/344-361'
A0A1J1JH03/367-388'
A0A1J1JH03/400-420'
A0A1J1JH03/426-447'
A0A4V0XUI3 has 12 helices, if 12, will use last 11, if other won't include
A0A4V0XUI3/80-98'
A0A4V0XUI3/119-138'
A0A4V0XUI3/170-191'
A0A4V0XUI3/198-215'
A0A4V0XUI3/235-256'
A0A4V0XUI3/277-294'
A0A4V0XUI3/306-330'
A0A4V0XUI3/337-354'
A0A4V0XUI3/360-381'
A0A4V0XUI3/393-413'
A0A4V0XUI3/419-440'
A0A1C7EL50/12-30'
A0A1C7EL50/51-68'
A0A1C7EL50/88-110'
A0A1C7EL50/117-138'
A0A1C7EL50/144-170'
A0A1C7EL50/191-209'
A0A1C7EL50/221-243'
A0A1C7EL50/255-272'
A0A1C7EL50/278-297'
A0A1C7EL50/309-327'
A0A1C7EL50/347-367'
E7RJZ0/12-30'
E7RJZ0/51-68'
E7RJZ0/88-110'
E7RJZ0/117-138'
E7RJZ0/144-170'
E7RJZ0/191-209'
E7RJZ0/221-243'
E7RJZ0/255-272'
E7RJZ0/278-297'
E7RJZ0/309-327'
E7RJZ0/347-367'
A6GJF5/31-51'
A6GJF5/72-91'
A6GJF5/130-149'
A6GJF5/156-178'
A6GJF5/190-211'
A6GJF5/232-249'
A6GJF5/261-283'
A6GJF5/295-314'
A6GJF5/320-337'
A6GJF5/349-367'
A6GJF5/373-397'
A1VIG8/85-106'
A1VIG8/118-136'
A1VIG8/183-205'
A1VIG8/212-236'
A1VIG8/256-286'
A1VIG8/298-318'
A1VIG8/330-351'
A1VIG8/363-380'
A1VIG8/386-406'
A1VIG8/418-436'
A1VIG8/467-489'
A1VIM5/82-103'
A1VIM5/115-138'
A1VIM5/183-204'
A1VIM5/211-232'
A1VIM5/252-268'
A1VIM5/280-300'
A1VIM5/312-331'
A1VIM5/343-363'
A1VIM5/369-387'
A1VIM5/399-418'
A1VIM5/430-453'
A4T0A4/67-89'
A4T0A4/96-117'
A4T0A4/159-181'
A4T0A4/188-211'
A4T0A4/241-263'
A4T0A4/275-295'
A4T0A4/307-327'
A4T0A4/339-359'
A4T0A4/365-382'
A4T0A4/394-413'
A4T0A4/440-462'
B9IGE2/23-45'
B9IGE2/57-79'
B9IGE2/131-150'
B9IGE2/162-183'
B9IGE2/195-213'
B9IGE2/225-245'
B9IGE2/257-276'
B9IGE2/288-306'
B9IGE2/312-333'
B9IGE2/345-367'
B9IGE2/397-422'
B9HCZ0/24-46'
B9HCZ0/58-80'
B9HCZ0/132-151'
B9HCZ0/163-184'
B9HCZ0/196-214'
B9HCZ0/226-246'
B9HCZ0/258-277'
B9HCZ0/289-307'
B9HCZ0/313-334'
B9HCZ0/346-368'
B9HCZ0/398-423'
A0A2K2AEV5/23-45'
A0A2K2AEV5/52-74'
A0A2K2AEV5/114-134'
A0A2K2AEV5/141-163'
A0A2K2AEV5/175-196'
A0A2K2AEV5/208-228'
A0A2K2AEV5/234-259'
A0A2K2AEV5/271-289'
A0A2K2AEV5/295-316'
A0A2K2AEV5/328-350'
A0A2K2AEV5/386-409'
B9GHA5/31-52'
B9GHA5/64-83'
B9GHA5/139-159'
B9GHA5/171-192'
B9GHA5/204-223'
B9GHA5/235-254'
B9GHA5/266-285'
B9GHA5/297-315'
B9GHA5/321-341'
B9GHA5/362-387'
B9GHA5/407-432'
U5FE59/31-53'
U5FE59/65-84'
U5FE59/140-160'
U5FE59/172-193'
U5FE59/205-224'
U5FE59/236-255'
U5FE59/267-286'
U5FE59/298-316'
U5FE59/322-342'
U5FE59/363-388'
U5FE59/408-433'
A0A2K1RA77/30-52'
A0A2K1RA77/64-83'
A0A2K1RA77/139-159'
A0A2K1RA77/171-192'
A0A2K1RA77/204-223'
A0A2K1RA77/235-254'
A0A2K1RA77/266-285'
A0A2K1RA77/297-315'
A0A2K1RA77/321-341'
A0A2K1RA77/362-387'
A0A2K1RA77/407-432'
A0A2K1RA81/31-53'
A0A2K1RA81/65-84'
A0A2K1RA81/140-160'
A0A2K1RA81/172-193'
A0A2K1RA81/205-224'
A0A2K1RA81/236-255'
A0A2K1RA81/267-286'
A0A2K1RA81/298-316'
A0A2K1RA81/322-342'
A0A2K1RA81/363-388'
A0A2K1RA81/408-433'
A0A2K1WV98/27-48'
A0A2K1WV98/60-80'
A0A2K1WV98/119-138'
A0A2K1WV98/143-164'
A0A2K1WV98/184-202'
A0A2K1WV98/214-234'
A0A2K1WV98/246-270'
A0A2K1WV98/277-295'
A0A2K1WV98/301-322'
A0A2K1WV98/334-356'
A0A2K1WV98/395-420'
A0A8H7U3I1/16-37'
A0A8H7U3I1/49-67'
A0A8H7U3I1/107-128'
A0A8H7U3I1/135-158'
A0A8H7U3I1/173-193'
A0A8H7U3I1/205-225'
A0A8H7U3I1/237-258'
A0A8H7U3I1/265-283'
A0A8H7U3I1/289-309'
A0A8H7U3I1/321-341'
A0A8H7U3I1/368-390'
A0A8H7P8U1/30-51'
A0A8H7P8U1/63-87'
A0A8H7P8U1/118-139'
A0A8H7P8U1/151-172'
A0A8H7P8U1/178-202'
A0A8H7P8U1/223-241'
A0A8H7P8U1/253-274'
A0A8H7P8U1/281-298'
A0A8H7P8U1/304-324'
A0A8H7P8U1/336-358'
A0A8H7P8U1/393-411'
A0A1X6N3Q5/30-51'
A0A1X6N3Q5/63-81'
A0A1X6N3Q5/118-139'
A0A1X6N3Q5/151-172'
A0A1X6N3Q5/178-202'
A0A1X6N3Q5/223-241'
A0A1X6N3Q5/253-273'
A0A1X6N3Q5/285-305'
A0A1X6N3Q5/311-331'
A0A1X6N3Q5/343-365'
A0A1X6N3Q5/385-407'
A0A0G3CP57/32-54'
A0A0G3CP57/66-86'
A0A0G3CP57/120-142'
A0A0G3CP57/149-171'
A0A0G3CP57/183-205'
A0A0G3CP57/217-236'
A0A0G3CP57/248-268'
A0A0G3CP57/280-299'
A0A0G3CP57/305-324'
A0A0G3CP57/336-354'
A0A0G3CP57/374-396'
A0A660CH85/6-26'
A0A660CH85/38-56'
A0A660CH85/96-115'
A0A660CH85/122-143'
A0A660CH85/163-182'
A0A660CH85/194-211'
A0A660CH85/223-243'
A0A660CH85/255-271'
A0A660CH85/277-297'
A0A660CH85/309-334'
A0A660CH85/354-376'
A2C095 has 12 helices, if 12, will use last 11, if other won't include
A2C095/83-103'
A2C095/115-133'
A2C095/180-200'
A2C095/207-228'
A2C095/240-261'
A2C095/281-298'
A2C095/310-334'
A2C095/341-358'
A2C095/364-385'
A2C095/397-416'
A2C095/436-459'
A2BP62 has 12 helices, if 12, will use last 11, if other won't include
A2BP62/78-98'
A2BP62/110-128'
A2BP62/170-190'
A2BP62/197-215'
A2BP62/235-256'
A2BP62/268-288'
A2BP62/300-324'
A2BP62/331-348'
A2BP62/354-375'
A2BP62/387-407'
A2BP62/427-451'

A0A8I1X2A6 has 12 helices, if 12, will use last 11, if other won't include
A0A8I1X2A6/78-98'
A0A8I1X2A6/110-128'
A0A8I1X2A6/170-190'
A0A8I1X2A6/197-215'
A0A8I1X2A6/235-256'
A0A8I1X2A6/268-288'
A0A8I1X2A6/300-324'
A0A8I1X2A6/331-348'
A0A8I1X2A6/354-375'
A0A8I1X2A6/387-407'
A0A8I1X2A6/427-451'
A0A0A2BBY0/39-58'
A0A0A2BBY0/70-88'
A0A0A2BBY0/130-150'
A0A0A2BBY0/157-175'
A0A0A2BBY0/195-216'
A0A0A2BBY0/228-248'
A0A0A2BBY0/260-284'
A0A0A2BBY0/291-308'
A0A0A2BBY0/314-335'
A0A0A2BBY0/347-367'
A0A0A2BBY0/387-411'
A0A0A1ZMZ9/39-58'
A0A0A1ZMZ9/70-88'
A0A0A1ZMZ9/130-150'
A0A0A1ZMZ9/157-175'
A0A0A1ZMZ9/195-215'
A0A0A1ZMZ9/235-252'
A0A0A1ZMZ9/264-285'
A0A0A1ZMZ9/297-317'
A0A0A1ZMZ9/323-341'
A0A0A1ZMZ9/348-370'
A0A0A1ZMZ9/390-415'
Q7VDS3 has 12 helices, if 12, will use last 11, if other won't include
Q7VDS3/83-103'
Q7VDS3/115-133'
Q7VDS3/184-203'
Q7VDS3/208-226'
Q7VDS3/246-266'
Q7VDS3/286-303'
Q7VDS3/315-336'
Q7VDS3/348-368'
Q7VDS3/374-390'
Q7VDS3/402-421'
Q7VDS3/441-467'
Q7V4T8 has 12 helices, if 12, will use last 11, if other won't include
Q7V4T8/78-98'
Q7V4T8/110-128'
Q7V4T8/170-190'
Q7V4T8/197-215'
Q7V4T8/235-256'
Q7V4T8/276-293'
Q7V4T8/305-329'
Q7V4T8/336-353'
Q7V4T8/359-380'
Q7V4T8/392-411'
Q7V4T8/431-456'
A2CCK1 has 12 helices, if 12, will use last 11, if other won't include
A2CCK1/73-94'
A2CCK1/115-134'
A2CCK1/171-190'
A2CCK1/195-213'
A2CCK1/233-253'
A2CCK1/273-290'
A2CCK1/302-326'
A2CCK1/333-351'
A2CCK1/357-377'
A2CCK1/389-408'
A2CCK1/428-450'
A3PAY4 has 12 helices, if 12, will use last 11, if other won't include
A3PAY4/78-98'
A3PAY4/110-128'
A3PAY4/170-190'
A3PAY4/197-215'
A3PAY4/235-256'
A3PAY4/268-288'
A3PAY4/300-324'
A3PAY4/331-348'
A3PAY4/354-375'
A3PAY4/387-407'
A3PAY4/427-451'
A2BUP4 has 12 helices, if 12, will use last 11, if other won't include
A2BUP4/73-94'
A2BUP4/115-134'
A2BUP4/170-190'
A2BUP4/197-215'
A2BUP4/235-256'
A2BUP4/268-288'
A2BUP4/300-324'
A2BUP4/331-348'
A2BUP4/354-375'
A2BUP4/387-407'
A2BUP4/427-451'
A8G2S3 has 12 helices, if 12, will use last 11, if other won't include
A8G2S3/78-98'
A8G2S3/110-128'
A8G2S3/170-190'
A8G2S3/197-215'
A8G2S3/235-256'
A8G2S3/268-288'
A8G2S3/300-324'
A8G2S3/331-348'
A8G2S3/354-375'
A8G2S3/387-407'
A8G2S3/427-451'
B9NZY2 has 12 helices, if 12, will use last 11, if other won't include
B9NZY2/78-98'
B9NZY2/110-128'
B9NZY2/170-190'
B9NZY2/197-215'
B9NZY2/235-256'
B9NZY2/268-288'
B9NZY2/300-324'
B9NZY2/331-348'
B9NZY2/354-375'
B9NZY2/387-407'
B9NZY2/427-451'
A9BDN5/40-57'
A9BDN5/77-97'
A9BDN5/109-127'
A9BDN5/166-185'
A9BDN5/190-208'
A9BDN5/228-248'
A9BDN5/268-285'
A9BDN5/297-318'
A9BDN5/352-372'
A9BDN5/384-403'
A9BDN5/423-448'
Q7V330 has 12 helices, if 12, will use last 11, if other won't include
Q7V330/78-98'
Q7V330/110-128'
Q7V330/170-190'
Q7V330/197-215'
Q7V330/235-256'
Q7V330/268-288'
Q7V330/300-324'
Q7V330/331-348'
Q7V330/354-375'
Q7V330/387-407'
Q7V330/427-451'
Q9REX3 has 12 helices, if 12, will use last 11, if other won't include
Q9REX3/85-105'
Q9REX3/117-135'
Q9REX3/177-197'
Q9REX3/204-222'
Q9REX3/242-263'
Q9REX3/275-295'
Q9REX3/307-331'
Q9REX3/338-355'
Q9REX3/361-382'
Q9REX3/394-414'
Q9REX3/434-458'
A0A318QZ80 has 12 helices, if 12, will use last 11, if other won't include
A0A318QZ80/83-103'
A0A318QZ80/115-133'
A0A318QZ80/180-200'
A0A318QZ80/207-228'
A0A318QZ80/240-261'
A0A318QZ80/281-298'
A0A318QZ80/310-334'
A0A318QZ80/341-358'
A0A318QZ80/364-385'
A0A318QZ80/397-416'
A0A318QZ80/436-459'
A0A9D9G322 has 12 helices, if 12, will use last 11, if other won't include
A0A9D9G322/78-98'
A0A9D9G322/110-128'
A0A9D9G322/170-190'
A0A9D9G322/197-215'
A0A9D9G322/235-256'
A0A9D9G322/268-288'
A0A9D9G322/300-324'
A0A9D9G322/331-348'
A0A9D9G322/354-375'
A0A9D9G322/387-407'
A0A9D9G322/427-451'
A0A9D9C0X8 has 12 helices, if 12, will use last 11, if other won't include
A0A9D9C0X8/78-98'
A0A9D9C0X8/110-128'
A0A9D9C0X8/170-190'
A0A9D9C0X8/197-215'
A0A9D9C0X8/235-256'
A0A9D9C0X8/268-288'
A0A9D9C0X8/300-324'
A0A9D9C0X8/331-348'
A0A9D9C0X8/354-375'
A0A9D9C0X8/387-407'
A0A9D9C0X8/427-451'
Q46HB1 has 12 helices, if 12, will use last 11, if other won't include
Q46HB1/83-103'
Q46HB1/115-133'
Q46HB1/180-200'
Q46HB1/207-228'
Q46HB1/240-261'
Q46HB1/281-298'
Q46HB1/310-334'
Q46HB1/341-358'
Q46HB1/364-385'
Q46HB1/397-416'
Q46HB1/436-459'
A0A0A1ZJU5 has 12 helices, if 12, will use last 11, if other won't include
A0A0A1ZJU5/78-98'
A0A0A1ZJU5/110-128'
A0A0A1ZJU5/170-190'
A0A0A1ZJU5/197-215'
A0A0A1ZJU5/235-256'
A0A0A1ZJU5/268-288'
A0A0A1ZJU5/300-324'
A0A0A1ZJU5/331-348'
A0A0A1ZJU5/354-375'
A0A0A1ZJU5/387-407'
A0A0A1ZJU5/427-451'
A0A0A2B651/39-58'
A0A0A2B651/70-88'
A0A0A2B651/130-150'
A0A0A2B651/157-175'
A0A0A2B651/195-216'
A0A0A2B651/228-248'
A0A0A2B651/260-284'
A0A0A2B651/291-308'
A0A0A2B651/314-335'
A0A0A2B651/347-367'
A0A0A2B651/387-411'
A0A0A2C6L1 has 12 helices, if 12, will use last 11, if other won't include
A0A0A2C6L1/58-78'
A0A0A2C6L1/90-108'
A0A0A2C6L1/155-175'
A0A0A2C6L1/182-203'
A0A0A2C6L1/215-236'
A0A0A2C6L1/256-273'
A0A0A2C6L1/285-309'
A0A0A2C6L1/316-333'
A0A0A2C6L1/339-360'
A0A0A2C6L1/372-391'
A0A0A2C6L1/411-434'
Q31CR9 has 12 helices, if 12, will use last 11, if other won't include
Q31CR9/73-94'
Q31CR9/115-136'
Q31CR9/171-191'
Q31CR9/198-216'
Q31CR9/228-252'
Q31CR9/272-289'
Q31CR9/301-325'
Q31CR9/332-349'
Q31CR9/355-376'
Q31CR9/388-407'
Q31CR9/427-452'
A0A0A2A5X1 has 12 helices, if 12, will use last 11, if other won't include
A0A0A2A5X1/78-98'
A0A0A2A5X1/110-128'
A0A0A2A5X1/170-190'
A0A0A2A5X1/197-218'
A0A0A2A5X1/230-251'
A0A0A2A5X1/271-288'
A0A0A2A5X1/300-324'
A0A0A2A5X1/331-348'
A0A0A2A5X1/354-375'
A0A0A2A5X1/387-406'
A0A0A2A5X1/426-451'
A0A0M2PZN7/12-33'
A0A0M2PZN7/45-70'
A0A0M2PZN7/91-109'
A0A0M2PZN7/145-164'
A0A0M2PZN7/171-193'
A0A0M2PZN7/205-226'
A0A0M2PZN7/247-264'
A0A0M2PZN7/276-302'
A0A0M2PZN7/314-346'
A0A0M2PZN7/366-383'
A0A0M2PZN7/404-425'
A0A5M4AWD2/24-43'
A0A5M4AWD2/64-88'
A0A5M4AWD2/108-128'
A0A5M4AWD2/135-157'
A0A5M4AWD2/169-191'
A0A5M4AWD2/203-223'
A0A5M4AWD2/243-264'
A0A5M4AWD2/271-291'
A0A5M4AWD2/297-318'
A0A5M4AWD2/330-348'
A0A5M4AWD2/360-385'
A0A5M4B0G1/12-33'
A0A5M4B0G1/40-60'
A0A5M4B0G1/100-123'
A0A5M4B0G1/130-152'
A0A5M4B0G1/164-185'
A0A5M4B0G1/197-215'
A0A5M4B0G1/227-251'
A0A5M4B0G1/258-275'
A0A5M4B0G1/281-299'
A0A5M4B0G1/311-334'
A0A5M4B0G1/354-378'
A0A5M4ATH9 has 12 helices, if 12, will use last 11, if other won't include
A0A5M4ATH9/41-63'
A0A5M4ATH9/75-98'
A0A5M4ATH9/134-154'
A0A5M4ATH9/166-185'
A0A5M4ATH9/205-223'
A0A5M4ATH9/235-254'
A0A5M4ATH9/266-286'
A0A5M4ATH9/298-316'
A0A5M4ATH9/322-340'
A0A5M4ATH9/352-372'
A0A5M4ATH9/384-406'
A0A5M4AUM9/6-28'
A0A5M4AUM9/40-58'
A0A5M4AUM9/104-126'
A0A5M4AUM9/133-155'
A0A5M4AUM9/167-189'
A0A5M4AUM9/201-218'
A0A5M4AUM9/230-250'
A0A5M4AUM9/262-281'
A0A5M4AUM9/287-306'
A0A5M4AUM9/318-340'
A0A5M4AUM9/360-382'
A0A1H7CU41/40-60'
A0A1H7CU41/72-94'
A0A1H7CU41/127-149'
A0A1H7CU41/156-178'
A0A1H7CU41/190-211'
A0A1H7CU41/223-244'
A0A1H7CU41/250-275'
A0A1H7CU41/287-305'
A0A1H7CU41/311-331'
A0A1H7CU41/343-362'
A0A1H7CU41/382-404'
A0A1G7VM92/58-79'
A0A1G7VM92/91-112'
A0A1G7VM92/151-173'
A0A1G7VM92/180-204'
A0A1G7VM92/233-254'
A0A1G7VM92/266-287'
A0A1G7VM92/299-319'
A0A1G7VM92/331-348'
A0A1G7VM92/354-374'
A0A1G7VM92/386-411'
A0A1G7VM92/431-453'
A0A1G7UZX2/12-35'
A0A1G7UZX2/47-69'
A0A1G7UZX2/89-108'
A0A1G7UZX2/117-137'
A0A1G7UZX2/157-180'
A0A1G7UZX2/201-221'
A0A1G7UZX2/227-249'
A0A1G7UZX2/256-274'
A0A1G7UZX2/280-298'
A0A1G7UZX2/310-329'
A0A1G7UZX2/341-366'
B4S394/33-58'
B4S394/70-103'
B4S394/123-145'
B4S394/152-174'
B4S394/194-213'
B4S394/225-244'
B4S394/256-276'
B4S394/288-306'
B4S394/312-330'
B4S394/342-361'
B4S394/383-408'
A0A0P6VSR8/39-60'
A0A0P6VSR8/72-92'
A0A0P6VSR8/145-167'
A0A0P6VSR8/174-198'
A0A0P6VSR8/265-286'
A0A0P6VSR8/298-319'
A0A0P6VSR8/331-351'
A0A0P6VSR8/363-382'
A0A0P6VSR8/388-406'
A0A0P6VSR8/418-437'
A0A0P6VSR8/470-491'
A0A101HKN9/12-32'
A0A101HKN9/53-76'
A0A101HKN9/96-118'
A0A101HKN9/125-146'
A0A101HKN9/166-184'
A0A101HKN9/196-216'
A0A101HKN9/236-257'
A0A101HKN9/264-281'
A0A101HKN9/287-308'
A0A101HKN9/320-340'
A0A101HKN9/360-381'
A0A7U1H267/40-61'
A0A7U1H267/73-95'
A0A7U1H267/123-145'
A0A7U1H267/152-173'
A0A7U1H267/185-209'
A0A7U1H267/221-240'
A0A7U1H267/252-272'
A0A7U1H267/284-302'
A0A7U1H267/308-328'
A0A7U1H267/340-366'
A0A7U1H267/378-400'
B4EU65/40-61'
B4EU65/73-95'
B4EU65/123-145'
B4EU65/152-173'
B4EU65/185-209'
B4EU65/221-240'
B4EU65/252-272'
B4EU65/284-302'
B4EU65/308-328'
B4EU65/340-366'
B4EU65/378-400'
A0A2X2C038/40-61'
A0A2X2C038/73-95'
A0A2X2C038/123-145'
A0A2X2C038/152-173'
A0A2X2C038/185-209'
A0A2X2C038/221-240'
A0A2X2C038/252-272'
A0A2X2C038/284-302'
A0A2X2C038/308-328'
A0A2X2C038/340-366'
A0A2X2C038/378-400'

A0A1S5XW08/50-69'
A0A1S5XW08/81-98'
A0A1S5XW08/104-127'
A0A1S5XW08/139-162'
A0A1S5XW08/168-187'
A0A1S5XW08/215-236'
A0A1S5XW08/248-269'
A0A1S5XW08/281-304'
A0A1S5XW08/310-333'
A0A1S5XW08/345-366'
A0A1S5XW08/372-391'
A0A264VQM8/33-55'
A0A264VQM8/67-87'
A0A264VQM8/121-143'
A0A264VQM8/150-172'
A0A264VQM8/184-206'
A0A264VQM8/218-237'
A0A264VQM8/249-269'
A0A264VQM8/281-300'
A0A264VQM8/306-325'
A0A264VQM8/337-355'
A0A264VQM8/375-397'
A0A1Z1SZE8/40-61'
A0A1Z1SZE8/73-95'
A0A1Z1SZE8/123-145'
A0A1Z1SZE8/152-173'
A0A1Z1SZE8/185-209'
A0A1Z1SZE8/221-240'
A0A1Z1SZE8/252-272'
A0A1Z1SZE8/284-302'
A0A1Z1SZE8/308-328'
A0A1Z1SZE8/340-366'
A0A1Z1SZE8/378-400'
A0A1S1HRJ0/32-54'
A0A1S1HRJ0/66-86'
A0A1S1HRJ0/123-142'
A0A1S1HRJ0/149-171'
A0A1S1HRJ0/183-205'
A0A1S1HRJ0/217-236'
A0A1S1HRJ0/248-268'
A0A1S1HRJ0/280-298'
A0A1S1HRJ0/304-324'
A0A1S1HRJ0/336-358'
A0A1S1HRJ0/378-399'
A0A379GJ68/32-56'
A0A379GJ68/63-84'
A0A379GJ68/120-142'
A0A379GJ68/149-171'
A0A379GJ68/183-205'
A0A379GJ68/217-237'
A0A379GJ68/249-268'
A0A379GJ68/280-298'
A0A379GJ68/304-324'
A0A379GJ68/336-359'
A0A379GJ68/379-399'
B2Q716/40-64'
B2Q716/71-92'
B2Q716/128-150'
B2Q716/157-179'
B2Q716/191-213'
B2Q716/225-245'
B2Q716/257-276'
B2Q716/288-306'
B2Q716/312-332'
B2Q716/344-367'
B2Q716/387-407'
A0A140NHJ5/32-56'
A0A140NHJ5/63-84'
A0A140NHJ5/120-142'
A0A140NHJ5/149-171'
A0A140NHJ5/183-205'
A0A140NHJ5/217-237'
A0A140NHJ5/249-268'
A0A140NHJ5/280-298'
A0A140NHJ5/304-324'
A0A140NHJ5/336-359'
A0A140NHJ5/379-399'
A0A1S1HM83/15-38'
A0A1S1HM83/50-68'
A0A1S1HM83/105-128'
A0A1S1HM83/135-156'
A0A1S1HM83/168-191'
A0A1S1HM83/203-221'
A0A1S1HM83/233-252'
A0A1S1HM83/264-281'
A0A1S1HM83/287-307'
A0A1S1HM83/319-341'
A0A1S1HM83/361-382'
A0A370FPU0/6-23'
A0A370FPU0/30-52'
A0A370FPU0/97-119'
A0A370FPU0/126-150'
A0A370FPU0/179-201'
A0A370FPU0/213-233'
A0A370FPU0/245-265'
A0A370FPU0/277-294'
A0A370FPU0/300-320'
A0A370FPU0/332-350'
A0A370FPU0/378-400'
A0A147GP06/6-23'
A0A147GP06/30-52'
A0A147GP06/97-119'
A0A147GP06/126-150'
A0A147GP06/179-201'
A0A147GP06/213-233'
A0A147GP06/245-265'
A0A147GP06/277-294'
A0A147GP06/300-320'
A0A147GP06/332-350'
A0A147GP06/378-400'
A0A316BQ38/55-75'
A0A316BQ38/87-107'
A0A316BQ38/142-164'
A0A316BQ38/171-192'
A0A316BQ38/212-229'
A0A316BQ38/241-260'
A0A316BQ38/272-292'
A0A316BQ38/304-321'
A0A316BQ38/327-347'
A0A316BQ38/359-378'
A0A316BQ38/398-419'
A0A9J9BAE8/14-38'
A0A9J9BAE8/50-69'
A0A9J9BAE8/110-128'
A0A9J9BAE8/135-157'
A0A9J9BAE8/177-199'
A0A9J9BAE8/211-233'
A0A9J9BAE8/253-275'
A0A9J9BAE8/282-300'
A0A9J9BAE8/306-326'
A0A9J9BAE8/338-357'
A0A9J9BAE8/363-388'
A0A9J9ES23/18-39'
A0A9J9ES23/51-73'
A0A9J9ES23/93-111'
A0A9J9ES23/123-144'
A0A9J9ES23/164-185'
A0A9J9ES23/197-221'
A0A9J9ES23/233-255'
A0A9J9ES23/262-280'
A0A9J9ES23/286-304'
A0A9J9ES23/316-335'
A0A9J9ES23/347-372'
A0A9J9ETF7/6-24'
A0A9J9ETF7/36-57'
A0A9J9ETF7/82-102'
A0A9J9ETF7/114-138'
A0A9J9ETF7/150-168'
A0A9J9ETF7/175-196'
A0A9J9ETF7/238-257'
A0A9J9ETF7/264-287'
A0A9J9ETF7/299-321'
A0A9J9ETF7/333-351'
A0A9J9ETF7/357-378'
A0A927UCK5/6-30'
A0A927UCK5/51-75'
A0A927UCK5/95-112'
A0A927UCK5/119-143'
A0A927UCK5/155-176'
A0A927UCK5/197-219'
A0A927UCK5/231-254'
A0A927UCK5/261-278'
A0A927UCK5/284-305'
A0A927UCK5/317-337'
A0A927UCK5/357-382'
A0A1H7IQT2/6-30'
A0A1H7IQT2/51-75'
A0A1H7IQT2/95-112'
A0A1H7IQT2/119-143'
A0A1H7IQT2/155-176'
A0A1H7IQT2/197-219'
A0A1H7IQT2/231-254'
A0A1H7IQT2/261-278'
A0A1H7IQT2/284-305'
A0A1H7IQT2/317-337'
A0A1H7IQT2/357-382'
A0A285RSQ4/6-30'
A0A285RSQ4/51-75'
A0A285RSQ4/95-112'
A0A285RSQ4/119-143'
A0A285RSQ4/155-176'
A0A285RSQ4/197-219'
A0A285RSQ4/231-254'
A0A285RSQ4/261-278'
A0A285RSQ4/284-305'
A0A285RSQ4/317-337'
A0A285RSQ4/357-382'
A0A2G3DSU6/6-27'
A0A2G3DSU6/48-67'
A0A2G3DSU6/95-112'
A0A2G3DSU6/119-136'
A0A2G3DSU6/156-176'
A0A2G3DSU6/197-219'
A0A2G3DSU6/231-254'
A0A2G3DSU6/261-278'
A0A2G3DSU6/284-305'
A0A2G3DSU6/317-337'
A0A2G3DSU6/357-382'
A0A2G3E8V2/6-27'
A0A2G3E8V2/48-67'
A0A2G3E8V2/95-112'
A0A2G3E8V2/119-136'
A0A2G3E8V2/156-176'
A0A2G3E8V2/197-219'
A0A2G3E8V2/231-254'
A0A2G3E8V2/261-278'
A0A2G3E8V2/284-305'
A0A2G3E8V2/317-337'
A0A2G3E8V2/357-382'

In [47]:
with open('str_end.txt', 'w') as fp:
    for itemt in str_end:
        # write each item on a new line
        fp.write("%s\n" % itemt)
    print('Done')

Done

In [48]:

# # opening the file in read mode 
# my_file = open("str_end.txt", "r") 
  
# # reading the file 
# data = my_file.read() 
  
# # replacing end of line('/n') with ' ' and 
# # splitting the text it further when '.' is seen. 
# str_end = data.replace('\n', ' ').split(".") 
  
# # printing the data 
# print(str_end) 
# my_file.close()

In [70]:
df

                                                       0   numbers
0      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...    /20-40
1      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...    /61-78
2      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...   /98-119
3      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...  /131-152
4      tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...  /164-186
...                                                  ...       ...
11556  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...  /239-262
11557  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...  /269-287
11558  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...  /293-313
11559  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...  /325-344
11560  tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...  /377-398

[11561 rows x 2 columns]

In [66]:
len(str_end)

11561

In [67]:
df['numbers'] = str_end

In [72]:
df[['split', 'splat']] = df[0].str.split(pat=None, n=1, expand = True)

In [73]:
df['header'] = df['split'] + df['numbers'] + ' ' + df['splat']

In [74]:
df.to_csv('df.csv')

In [75]:
df2 = pd.read_csv('df.csv')

In [76]:
df2

,Unnamed: 0,0,numbers,split,splat,header
0,0,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/20-40,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/20-40 Adenylate...
1,1,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/61-78,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/61-78 Adenylate...
2,2,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/98-119,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/98-119 Adenylat...
3,3,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/131-152,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/131-152 Adenyla...
4,4,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/164-186,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/164-186 Adenyla...
...,...,...,...,...,...,...
11556,11556,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/239-262,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/239-262 Adenylate cycla...
11557,11557,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/269-287,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/269-287 Adenylate cycla...
11558,11558,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/293-313,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/293-313 Adenylate cycla...
11559,11559,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/325-344,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/325-344 Adenylate cycla...
11560,11560,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/377-398,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/377-398 Adenylate cycla...

In [77]:
ids = []

for i in df2['split']:
    ids.append(i.split('|')[1])

In [78]:
df2['ids'] = ids

In [79]:
df2

,Unnamed: 0,0,numbers,split,splat,header,ids
0,0,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/20-40,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/20-40 Adenylate...,A0A011VQM7
1,1,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/61-78,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/61-78 Adenylate...,A0A011VQM7
2,2,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/98-119,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/98-119 Adenylat...,A0A011VQM7
3,3,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/131-152,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/131-152 Adenyla...,A0A011VQM7
4,4,tr|A0A011VQM7|A0A011VQM7_RUMAL Adenylate cycla...,/164-186,tr|A0A011VQM7|A0A011VQM7_RUMAL,Adenylate cyclase OS=Ruminococcus albus SY3 OX...,tr|A0A011VQM7|A0A011VQM7_RUMAL/164-186 Adenyla...,A0A011VQM7
...,...,...,...,...,...,...,...
11556,11556,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/239-262,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/239-262 Adenylate cycla...,W7UD62
11557,11557,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/269-287,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/269-287 Adenylate cycla...,W7UD62
11558,11558,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/293-313,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/293-313 Adenylate cycla...,W7UD62
11559,11559,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/325-344,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/325-344 Adenylate cycla...,W7UD62
11560,11560,tr|W7UD62|W7UD62_RUMFL Adenylate cyclase OS=Ru...,/377-398,tr|W7UD62|W7UD62_RUMFL,Adenylate cyclase OS=Ruminococcus flavefaciens...,tr|W7UD62|W7UD62_RUMFL/377-398 Adenylate cycla...,W7UD62

In [87]:
df2['combine'] = df2['ids'] + '_' + df2['helices']

KeyError: 'helices'

In [ ]:
df2

In [81]:
headers = []

for itims in df['header']:
    headers.append(itims)

In [82]:
headers = df['header'].to_list()

In [83]:
len(headers)

11561

In [85]:
with open('headers.txt', 'w') as fp:
    for itemy in headers:
        # write each item on a new line
        fp.write("%s\n" % itemy)
    print('Done')

Done

In [88]:
this_file = open("matches.txt", "r") 
  
# reading the file 
date = this_file.read() 
  
# replacing end splitting the text  
# when newline ('\n') is seen. 
data_list = date.split("\n") 
print(data_list) 
this_file.close()

['A0A011VQM7_Helix_1', 'A0A011VQM7_Helix_2', 'A0A011VQM7_Helix_3', 'A0A011VQM7_Helix_4', 'A0A011VQM7_Helix_5', 'A0A011VQM7_Helix_6', 'A0A011VQM7_Helix_7', 'A0A011VQM7_Helix_8', 'A0A011VQM7_Helix_9', 'A0A011VQM7_Helix_10', 'A0A011VQM7_Helix_11', 'A0A063ZJU6_Helix_1', 'A0A063ZJU6_Helix_2', 'A0A063ZJU6_Helix_3', 'A0A063ZJU6_Helix_4', 'A0A063ZJU6_Helix_5', 'A0A063ZJU6_Helix_6', 'A0A063ZJU6_Helix_7', 'A0A063ZJU6_Helix_8', 'A0A063ZJU6_Helix_9', 'A0A063ZJU6_Helix_10', 'A0A063ZJU6_Helix_11', 'A0A081EVR3_Helix_1', 'A0A081EVR3_Helix_2', 'A0A081EVR3_Helix_3', 'A0A081EVR3_Helix_4', 'A0A081EVR3_Helix_5', 'A0A081EVR3_Helix_6', 'A0A081EVR3_Helix_7', 'A0A081EVR3_Helix_8', 'A0A081EVR3_Helix_9', 'A0A081EVR3_Helix_10', 'A0A081EVR3_Helix_11', 'A0A099I9L1_Helix_1', 'A0A099I9L1_Helix_2', 'A0A099I9L1_Helix_3', 'A0A099I9L1_Helix_4', 'A0A099I9L1_Helix_5', 'A0A099I9L1_Helix_6', 'A0A099I9L1_Helix_7', 'A0A099I9L1_Helix_8', 'A0A099I9L1_Helix_9', 'A0A099I9L1_Helix_10', 'A0A099I9L1_Helix_11', 'A0A0D8IWY3_Helix_1', 'A0A0D8IWY3_Helix_2', 'A0A0D8IWY3_Helix_3', 'A0A0D8IWY3_Helix_4', 'A0A0D8IWY3_Helix_5', 'A0A0D8IWY3_Helix_6', 'A0A0D8IWY3_Helix_7', 'A0A0D8IWY3_Helix_8', 'A0A0D8IWY3_Helix_9', 'A0A0D8IWY3_Helix_10', 'A0A0D8IWY3_Helix_11', 'A0A0E2HBL2_Helix_1', 'A0A0E2HBL2_Helix_2', 'A0A0E2HBL2_Helix_3', 'A0A0E2HBL2_Helix_4', 'A0A0E2HBL2_Helix_5', 'A0A0E2HBL2_Helix_6', 'A0A0E2HBL2_Helix_7', 'A0A0E2HBL2_Helix_8', 'A0A0E2HBL2_Helix_9', 'A0A0E2HBL2_Helix_10', 'A0A0E2HBL2_Helix_11', 'A0A0F0CIE1_Helix_1', 'A0A0F0CIE1_Helix_2', 'A0A0F0CIE1_Helix_3', 'A0A0F0CIE1_Helix_4', 'A0A0F0CIE1_Helix_5', 'A0A0F0CIE1_Helix_6', 'A0A0F0CIE1_Helix_7', 'A0A0F0CIE1_Helix_8', 'A0A0F0CIE1_Helix_9', 'A0A0F0CIE1_Helix_10', 'A0A0F0CIE1_Helix_11', 'A0A0G3WG46_Helix_1', 'A0A0G3WG46_Helix_2', 'A0A0G3WG46_Helix_3', 'A0A0G3WG46_Helix_4', 'A0A0G3WG46_Helix_5', 'A0A0G3WG46_Helix_6', 'A0A0G3WG46_Helix_7', 'A0A0G3WG46_Helix_8', 'A0A0G3WG46_Helix_9', 'A0A0G3WG46_Helix_10', 'A0A0G3WG46_Helix_11', 'A0A0G9LEF6_Helix_1', 'A0A0G9LEF6_Helix_2', 'A0A0G9LEF6_Helix_3', 'A0A0G9LEF6_Helix_4', 'A0A0G9LEF6_Helix_5', 'A0A0G9LEF6_Helix_6', 'A0A0G9LEF6_Helix_7', 'A0A0G9LEF6_Helix_8', 'A0A0G9LEF6_Helix_9', 'A0A0G9LEF6_Helix_10', 'A0A0G9LEF6_Helix_11', 'A0A0H5SG89_Helix_1', 'A0A0H5SG89_Helix_2', 'A0A0H5SG89_Helix_3', 'A0A0H5SG89_Helix_4', 'A0A0H5SG89_Helix_5', 'A0A0H5SG89_Helix_6', 'A0A0H5SG89_Helix_7', 'A0A0H5SG89_Helix_8', 'A0A0H5SG89_Helix_9', 'A0A0H5SG89_Helix_10', 'A0A0H5SG89_Helix_11', 'A0A0J6ZRU4_Helix_1', 'A0A0J6ZRU4_Helix_2', 'A0A0J6ZRU4_Helix_3', 'A0A0J6ZRU4_Helix_4', 'A0A0J6ZRU4_Helix_5', 'A0A0J6ZRU4_Helix_6', 'A0A0J6ZRU4_Helix_7', 'A0A0J6ZRU4_Helix_8', 'A0A0J6ZRU4_Helix_9', 'A0A0J6ZRU4_Helix_10', 'A0A0J6ZRU4_Helix_11', 'A0A0J9EMW5_Helix_1', 'A0A0J9EMW5_Helix_2', 'A0A0J9EMW5_Helix_3', 'A0A0J9EMW5_Helix_4', 'A0A0J9EMW5_Helix_5', 'A0A0J9EMW5_Helix_6', 'A0A0J9EMW5_Helix_7', 'A0A0J9EMW5_Helix_8', 'A0A0J9EMW5_Helix_9', 'A0A0J9EMW5_Helix_10', 'A0A0J9EMW5_Helix_11', 'A0A0M2NHW4_Helix_1', 'A0A0M2NHW4_Helix_2', 'A0A0M2NHW4_Helix_3', 'A0A0M2NHW4_Helix_4', 'A0A0M2NHW4_Helix_5', 'A0A0M2NHW4_Helix_6', 'A0A0M2NHW4_Helix_7', 'A0A0M2NHW4_Helix_8', 'A0A0M2NHW4_Helix_9', 'A0A0M2NHW4_Helix_10', 'A0A0M2NHW4_Helix_11', 'A0A0M6WCZ2_Helix_1', 'A0A0M6WCZ2_Helix_2', 'A0A0M6WCZ2_Helix_3', 'A0A0M6WCZ2_Helix_4', 'A0A0M6WCZ2_Helix_5', 'A0A0M6WCZ2_Helix_6', 'A0A0M6WCZ2_Helix_7', 'A0A0M6WCZ2_Helix_8', 'A0A0M6WCZ2_Helix_9', 'A0A0M6WCZ2_Helix_10', 'A0A0M6WCZ2_Helix_11', 'A0A0M9AS13_Helix_1', 'A0A0M9AS13_Helix_2', 'A0A0M9AS13_Helix_3', 'A0A0M9AS13_Helix_4', 'A0A0M9AS13_Helix_5', 'A0A0M9AS13_Helix_6', 'A0A0M9AS13_Helix_7', 'A0A0M9AS13_Helix_8', 'A0A0M9AS13_Helix_9', 'A0A0M9AS13_Helix_10', 'A0A0M9AS13_Helix_11', 'A0A0S2W112_Helix_1', 'A0A0S2W112_Helix_2', 'A0A0S2W112_Helix_3', 'A0A0S2W112_Helix_4', 'A0A0S2W112_Helix_5', 'A0A0S2W112_Helix_6', 'A0A0S2W112_Helix_7', 'A0A0S2W112_Helix_8', 'A0A0S2W112_Helix_9', 'A0A0S2W112_Helix_10', 'A0A0S2W112_Helix_11', 'A0A0U5JBG5_Helix_1', 'A0A0U5JBG5_Helix_2', 'A0A0U5JBG5_Helix_3', 'A0A0U5JBG5_Helix_4', 'A0A0U5JBG5_Helix_5', 'A0A0U5JBG5_Helix_6', 'A0A0U5JBG5_Helix_7', 'A0A0U5JBG5_Helix_8', 'A0A0U5JBG5_Helix_9', 'A0A0U5JBG5_Helix_10', 'A0A0U5JBG5_Helix_11', 'A0A0W7TMH6_Helix_1', 'A0A0W7TMH6_Helix_2', 'A0A0W7TMH6_Helix_3', 'A0A0W7TMH6_Helix_4', 'A0A0W7TMH6_Helix_5', 'A0A0W7TMH6_Helix_6', 'A0A0W7TMH6_Helix_7', 'A0A0W7TMH6_Helix_8', 'A0A0W7TMH6_Helix_9', 'A0A0W7TMH6_Helix_10', 'A0A0W7TMH6_Helix_11', 'A0A136Q6K1_Helix_1', 'A0A136Q6K1_Helix_2', 'A0A136Q6K1_Helix_3', 'A0A136Q6K1_Helix_4', 'A0A136Q6K1_Helix_5', 'A0A136Q6K1_Helix_6', 'A0A136Q6K1_Helix_7', 'A0A136Q6K1_Helix_8', 'A0A136Q6K1_Helix_9', 'A0A136Q6K1_Helix_10', 'A0A136Q6K1_Helix_11', 'A0A136WGT4_Helix_1', 'A0A136WGT4_Helix_2', 'A0A136WGT4_Helix_3', 'A0A136WGT4_Helix_4', 'A0A136WGT4_Helix_5', 'A0A136WGT4_Helix_6', 'A0A136WGT4_Helix_7', 'A0A136WGT4_Helix_8', 'A0A136WGT4_Helix_9', 'A0A136WGT4_Helix_10', 'A0A136WGT4_Helix_11', 'A0A140DTE7_Helix_1', 'A0A140DTE7_Helix_2', 'A0A140DTE7_Helix_3', 'A0A140DTE7_Helix_4', 'A0A140DTE7_Helix_5', 'A0A140DTE7_Helix_6', 'A0A140DTE7_Helix_7', 'A0A140DTE7_Helix_8', 'A0A140DTE7_Helix_9', 'A0A140DTE7_Helix_10', 'A0A140DTE7_Helix_11', 'A0A143Y517_Helix_1', 'A0A143Y517_Helix_2', 'A0A143Y517_Helix_3', 'A0A143Y517_Helix_4', 'A0A143Y517_Helix_5', 'A0A143Y517_Helix_6', 'A0A143Y517_Helix_7', 'A0A143Y517_Helix_8', 'A0A143Y517_Helix_9', 'A0A143Y517_Helix_10', 'A0A143Y517_Helix_11', 'A0A143Y9S4_Helix_1', 'A0A143Y9S4_Helix_2', 'A0A143Y9S4_Helix_3', 'A0A143Y9S4_Helix_4', 'A0A143Y9S4_Helix_5', 'A0A143Y9S4_Helix_6', 'A0A143Y9S4_Helix_7', 'A0A143Y9S4_Helix_8', 'A0A143Y9S4_Helix_9', 'A0A143Y9S4_Helix_10', 'A0A143Y9S4_Helix_11', 'A0A143YNF2_Helix_1', 'A0A143YNF2_Helix_2', 'A0A143YNF2_Helix_3', 'A0A143YNF2_Helix_4', 'A0A143YNF2_Helix_5', 'A0A143YNF2_Helix_6', 'A0A143YNF2_Helix_7', 'A0A143YNF2_Helix_8', 'A0A143YNF2_Helix_9', 'A0A143YNF2_Helix_10', 'A0A143YNF2_Helix_11', 'A0A143YTA3_Helix_1', 'A0A143YTA3_Helix_2', 'A0A143YTA3_Helix_3', 'A0A143YTA3_Helix_4', 'A0A143YTA3_Helix_5', 'A0A143YTA3_Helix_6', 'A0A143YTA3_Helix_7', 'A0A143YTA3_Helix_8', 'A0A143YTA3_Helix_9', 'A0A143YTA3_Helix_10', 'A0A143YTA3_Helix_11', 'A0A143YZV1_Helix_1', 'A0A143YZV1_Helix_2', 'A0A143YZV1_Helix_3', 'A0A143YZV1_Helix_4', 'A0A143YZV1_Helix_5', 'A0A143YZV1_Helix_6', 'A0A143YZV1_Helix_7', 'A0A143YZV1_Helix_8', 'A0A143YZV1_Helix_9', 'A0A143YZV1_Helix_10', 'A0A143YZV1_Helix_11', 'A0A143Z212_Helix_1', 'A0A143Z212_Helix_2', 'A0A143Z212_Helix_3', 'A0A143Z212_Helix_4', 'A0A143Z212_Helix_5', 'A0A143Z212_Helix_6', 'A0A143Z212_Helix_7', 'A0A143Z212_Helix_8', 'A0A143Z212_Helix_9', 'A0A143Z212_Helix_10', 'A0A143Z212_Helix_11', 'A0A143ZCA8_Helix_1', 'A0A143ZCA8_Helix_2', 'A0A143ZCA8_Helix_3', 'A0A143ZCA8_Helix_4', 'A0A143ZCA8_Helix_5', 'A0A143ZCA8_Helix_6', 'A0A143ZCA8_Helix_7', 'A0A143ZCA8_Helix_8', 'A0A143ZCA8_Helix_9', 'A0A143ZCA8_Helix_10', 'A0A143ZCA8_Helix_11', 'A0A151AI36_Helix_1', 'A0A151AI36_Helix_2', 'A0A151AI36_Helix_3', 'A0A151AI36_Helix_4', 'A0A151AI36_Helix_5', 'A0A151AI36_Helix_6', 'A0A151AI36_Helix_7', 'A0A151AI36_Helix_8', 'A0A151AI36_Helix_9', 'A0A151AI36_Helix_10', 'A0A151AI36_Helix_11', 'A0A169X118_Helix_1', 'A0A169X118_Helix_2', 'A0A169X118_Helix_3', 'A0A169X118_Helix_4', 'A0A169X118_Helix_5', 'A0A169X118_Helix_6', 'A0A169X118_Helix_7', 'A0A169X118_Helix_8', 'A0A169X118_Helix_9', 'A0A169X118_Helix_10', 'A0A169X118_Helix_11', 'A0A173R3X4_Helix_1', 'A0A173R3X4_Helix_2', 'A0A173R3X4_Helix_3', 'A0A173R3X4_Helix_4', 'A0A173R3X4_Helix_5', 'A0A173R3X4_Helix_6', 'A0A173R3X4_Helix_7', 'A0A173R3X4_Helix_8', 'A0A173R3X4_Helix_9', 'A0A173R3X4_Helix_10', 'A0A173R3X4_Helix_11', 'A0A173R662_Helix_1', 'A0A173R662_Helix_2', 'A0A173R662_Helix_3', 'A0A173R662_Helix_4', 'A0A173R662_Helix_5', 'A0A173R662_Helix_6', 'A0A173R662_Helix_7', 'A0A173R662_Helix_8', 'A0A173R662_Helix_9', 'A0A173R662_Helix_10', 'A0A173R662_Helix_11', 'A0A173V441_Helix_1', 'A0A173V441_Helix_2', 'A0A173V441_Helix_3', 'A0A173V441_Helix_4', 'A0A173V441_Helix_5', 'A0A173V441_Helix_6', 'A0A173V441_Helix_7', 'A0A173V441_Helix_8', 'A0A173V441_Helix_9', 'A0A173V441_Helix_10', 'A0A173V441_Helix_11', 'A0A173X4T2_Helix_1', 'A0A173X4T2_Helix_2', 'A0A173X4T2_Helix_3', 'A0A173X4T2_Helix_4', 'A0A173X4T2_Helix_5', 'A0A173X4T2_Helix_6', 'A0A173X4T2_Helix_7', 'A0A173X4T2_Helix_8', 'A0A173X4T2_Helix_9', 'A0A173X4T2_Helix_10', 'A0A173X4T2_Helix_11', 'A0A173XV88_Helix_1', 'A0A173XV88_Helix_2', 'A0A173XV88_Helix_3', 'A0A173XV88_Helix_4', 'A0A173XV88_Helix_5', 'A0A173XV88_Helix_6', 'A0A173XV88_Helix_7', 'A0A173XV88_Helix_8', 'A0A173XV88_Helix_9', 'A0A173XV88_Helix_10', 'A0A173XV88_Helix_11', 'A0A173XVK8_Helix_1', 'A0A173XVK8_Helix_2', 'A0A173XVK8_Helix_3', 'A0A173XVK8_Helix_4', 'A0A173XVK8_Helix_5', 'A0A173XVK8_Helix_6', 'A0A173XVK8_Helix_7', 'A0A173XVK8_Helix_8', 'A0A173XVK8_Helix_9', 'A0A173XVK8_Helix_10', 'A0A173XVK8_Helix_11', 'A0A173Z4K3_Helix_1', 'A0A173Z4K3_Helix_2', 'A0A173Z4K3_Helix_3', 'A0A173Z4K3_Helix_4', 'A0A173Z4K3_Helix_5', 'A0A173Z4K3_Helix_6', 'A0A173Z4K3_Helix_7', 'A0A173Z4K3_Helix_8', 'A0A173Z4K3_Helix_9', 'A0A173Z4K3_Helix_10', 'A0A173Z4K3_Helix_11', 'A0A173ZTK6_Helix_1', 'A0A173ZTK6_Helix_2', 'A0A173ZTK6_Helix_3', 'A0A173ZTK6_Helix_4', 'A0A173ZTK6_Helix_5', 'A0A173ZTK6_Helix_6', 'A0A173ZTK6_Helix_7', 'A0A173ZTK6_Helix_8', 'A0A173ZTK6_Helix_9', 'A0A173ZTK6_Helix_10', 'A0A173ZTK6_Helix_11', 'A0A174C5U1_Helix_1', 'A0A174C5U1_Helix_2', 'A0A174C5U1_Helix_3', 'A0A174C5U1_Helix_4', 'A0A174C5U1_Helix_5', 'A0A174C5U1_Helix_6', 'A0A174C5U1_Helix_7', 'A0A174C5U1_Helix_8', 'A0A174C5U1_Helix_9', 'A0A174C5U1_Helix_10', 'A0A174C5U1_Helix_11', 'A0A174D1D6_Helix_1', 'A0A174D1D6_Helix_2', 'A0A174D1D6_Helix_3', 'A0A174D1D6_Helix_4', 'A0A174D1D6_Helix_5', 'A0A174D1D6_Helix_6', 'A0A174D1D6_Helix_7', 'A0A174D1D6_Helix_8', 'A0A174D1D6_Helix_9', 'A0A174D1D6_Helix_10', 'A0A174D1D6_Helix_11', 'A0A174H6C4_Helix_1', 'A0A174H6C4_Helix_2', 'A0A174H6C4_Helix_3', 'A0A174H6C4_Helix_4', 'A0A174H6C4_Helix_5', 'A0A174H6C4_Helix_6', 'A0A174H6C4_Helix_7', 'A0A174H6C4_Helix_8', 'A0A174H6C4_Helix_9', 'A0A174H6C4_Helix_10', 'A0A174H6C4_Helix_11', 'A0A174JG28_Helix_1', 'A0A174JG28_Helix_2', 'A0A174JG28_Helix_3', 'A0A174JG28_Helix_4', 'A0A174JG28_Helix_5', 'A0A174JG28_Helix_6', 'A0A174JG28_Helix_7', 'A0A174JG28_Helix_8', 'A0A174JG28_Helix_9', 'A0A174JG28_Helix_10', 'A0A174JG28_Helix_11', 'A0A174RYE8_Helix_1', 'A0A174RYE8_Helix_2', 'A0A174RYE8_Helix_3', 'A0A174RYE8_Helix_4', 'A0A174RYE8_Helix_5', 'A0A174RYE8_Helix_6', 'A0A174RYE8_Helix_7', 'A0A174RYE8_Helix_8', 'A0A174RYE8_Helix_9', 'A0A174RYE8_Helix_10', 'A0A174RYE8_Helix_11', 'A0A174TIU3_Helix_1', 'A0A174TIU3_Helix_2', 'A0A174TIU3_Helix_3', 'A0A174TIU3_Helix_4', 'A0A174TIU3_Helix_5', 'A0A174TIU3_Helix_6', 'A0A174TIU3_Helix_7', 'A0A174TIU3_Helix_8', 'A0A174TIU3_Helix_9', 'A0A174TIU3_Helix_10', 'A0A174TIU3_Helix_11', 'A0A174VZ55_Helix_1', 'A0A174VZ55_Helix_2', 'A0A174VZ55_Helix_3', 'A0A174VZ55_Helix_4', 'A0A174VZ55_Helix_5', 'A0A174VZ55_Helix_6', 'A0A174VZ55_Helix_7', 'A0A174VZ55_Helix_8', 'A0A174VZ55_Helix_9', 'A0A174VZ55_Helix_10', 'A0A174VZ55_Helix_11', 'A0A174XKK3_Helix_1', 'A0A174XKK3_Helix_2', 'A0A174XKK3_Helix_3', 'A0A174XKK3_Helix_4', 'A0A174XKK3_Helix_5', 'A0A174XKK3_Helix_6', 'A0A174XKK3_Helix_7', 'A0A174XKK3_Helix_8', 'A0A174XKK3_Helix_9', 'A0A174XKK3_Helix_10', 'A0A174XKK3_Helix_11', 'A0A174YTX7_Helix_1', 'A0A174YTX7_Helix_2', 'A0A174YTX7_Helix_3', 'A0A174YTX7_Helix_4', 'A0A174YTX7_Helix_5', 'A0A174YTX7_Helix_6', 'A0A174YTX7_Helix_7', 'A0A174YTX7_Helix_8', 'A0A174YTX7_Helix_9', 'A0A174YTX7_Helix_10', 'A0A174YTX7_Helix_11', 'A0A174Z5H4_Helix_1', 'A0A174Z5H4_Helix_2', 'A0A174Z5H4_Helix_3', 'A0A174Z5H4_Helix_4', 'A0A174Z5H4_Helix_5', 'A0A174Z5H4_Helix_6', 'A0A174Z5H4_Helix_7', 'A0A174Z5H4_Helix_8', 'A0A174Z5H4_Helix_9', 'A0A174Z5H4_Helix_10', 'A0A174Z5H4_Helix_11', 'A0A175A4T9_Helix_1', 'A0A175A4T9_Helix_2', 'A0A175A4T9_Helix_3', 'A0A175A4T9_Helix_4', 'A0A175A4T9_Helix_5', 'A0A175A4T9_Helix_6', 'A0A175A4T9_Helix_7', 'A0A175A4T9_Helix_8', 'A0A175A4T9_Helix_9', 'A0A175A4T9_Helix_10', 'A0A175A4T9_Helix_11', 'A0A1B1YE78_Helix_1', 'A0A1B1YE78_Helix_2', 'A0A1B1YE78_Helix_3', 'A0A1B1YE78_Helix_4', 'A0A1B1YE78_Helix_5', 'A0A1B1YE78_Helix_6', 'A0A1B1YE78_Helix_7', 'A0A1B1YE78_Helix_8', 'A0A1B1YE78_Helix_9', 'A0A1B1YE78_Helix_10', 'A0A1B1YE78_Helix_11', 'A0A1B1YLE9_Helix_1', 'A0A1B1YLE9_Helix_2', 'A0A1B1YLE9_Helix_3', 'A0A1B1YLE9_Helix_4', 'A0A1B1YLE9_Helix_5', 'A0A1B1YLE9_Helix_6', 'A0A1B1YLE9_Helix_7', 'A0A1B1YLE9_Helix_8', 'A0A1B1YLE9_Helix_9', 'A0A1B1YLE9_Helix_10', 'A0A1B1YLE9_Helix_11', 'A0A1C0BVB4_Helix_1', 'A0A1C0BVB4_Helix_2', 'A0A1C0BVB4_Helix_3', 'A0A1C0BVB4_Helix_4', 'A0A1C0BVB4_Helix_5', 'A0A1C0BVB4_Helix_6', 'A0A1C0BVB4_Helix_7', 'A0A1C0BVB4_Helix_8', 'A0A1C0BVB4_Helix_9', 'A0A1C0BVB4_Helix_10', 'A0A1C0BVB4_Helix_11', 'A0A1C5M0W8_Helix_1', 'A0A1C5M0W8_Helix_2', 'A0A1C5M0W8_Helix_3', 'A0A1C5M0W8_Helix_4', 'A0A1C5M0W8_Helix_5', 'A0A1C5M0W8_Helix_6', 'A0A1C5M0W8_Helix_7', 'A0A1C5M0W8_Helix_8', 'A0A1C5M0W8_Helix_9', 'A0A1C5M0W8_Helix_10', 'A0A1C5M0W8_Helix_11', 'A0A1C5MDL8_Helix_1', 'A0A1C5MDL8_Helix_2', 'A0A1C5MDL8_Helix_3', 'A0A1C5MDL8_Helix_4', 'A0A1C5MDL8_Helix_5', 'A0A1C5MDL8_Helix_6', 'A0A1C5MDL8_Helix_7', 'A0A1C5MDL8_Helix_8', 'A0A1C5MDL8_Helix_9', 'A0A1C5MDL8_Helix_10', 'A0A1C5MDL8_Helix_11', 'A0A1C5N7S1_Helix_1', 'A0A1C5N7S1_Helix_2', 'A0A1C5N7S1_Helix_3', 'A0A1C5N7S1_Helix_4', 'A0A1C5N7S1_Helix_5', 'A0A1C5N7S1_Helix_6', 'A0A1C5N7S1_Helix_7', 'A0A1C5N7S1_Helix_8', 'A0A1C5N7S1_Helix_9', 'A0A1C5N7S1_Helix_10', 'A0A1C5N7S1_Helix_11', 'A0A1C5PFK7_Helix_1', 'A0A1C5PFK7_Helix_2', 'A0A1C5PFK7_Helix_3', 'A0A1C5PFK7_Helix_4', 'A0A1C5PFK7_Helix_5', 'A0A1C5PFK7_Helix_6', 'A0A1C5PFK7_Helix_7', 'A0A1C5PFK7_Helix_8', 'A0A1C5PFK7_Helix_9', 'A0A1C5PFK7_Helix_10', 'A0A1C5PFK7_Helix_11', 'A0A1C5PIG4_Helix_1', 'A0A1C5PIG4_Helix_2', 'A0A1C5PIG4_Helix_3', 'A0A1C5PIG4_Helix_4', 'A0A1C5PIG4_Helix_5', 'A0A1C5PIG4_Helix_6', 'A0A1C5PIG4_Helix_7', 'A0A1C5PIG4_Helix_8', 'A0A1C5PIG4_Helix_9', 'A0A1C5PIG4_Helix_10', 'A0A1C5PIG4_Helix_11', 'A0A1C5PQC5_Helix_1', 'A0A1C5PQC5_Helix_2', 'A0A1C5PQC5_Helix_3', 'A0A1C5PQC5_Helix_4', 'A0A1C5PQC5_Helix_5', 'A0A1C5PQC5_Helix_6', 'A0A1C5PQC5_Helix_7', 'A0A1C5PQC5_Helix_8', 'A0A1C5PQC5_Helix_9', 'A0A1C5PQC5_Helix_10', 'A0A1C5PQC5_Helix_11', 'A0A1C5QAX9_Helix_1', 'A0A1C5QAX9_Helix_2', 'A0A1C5QAX9_Helix_3', 'A0A1C5QAX9_Helix_4', 'A0A1C5QAX9_Helix_5', 'A0A1C5QAX9_Helix_6', 'A0A1C5QAX9_Helix_7', 'A0A1C5QAX9_Helix_8', 'A0A1C5QAX9_Helix_9', 'A0A1C5QAX9_Helix_10', 'A0A1C5QAX9_Helix_11', 'A0A1C5QDA2_Helix_1', 'A0A1C5QDA2_Helix_2', 'A0A1C5QDA2_Helix_3', 'A0A1C5QDA2_Helix_4', 'A0A1C5QDA2_Helix_5', 'A0A1C5QDA2_Helix_6', 'A0A1C5QDA2_Helix_7', 'A0A1C5QDA2_Helix_8', 'A0A1C5QDA2_Helix_9', 'A0A1C5QDA2_Helix_10', 'A0A1C5QDA2_Helix_11', 'A0A1C5QHK8_Helix_1', 'A0A1C5QHK8_Helix_2', 'A0A1C5QHK8_Helix_3', 'A0A1C5QHK8_Helix_4', 'A0A1C5QHK8_Helix_5', 'A0A1C5QHK8_Helix_6', 'A0A1C5QHK8_Helix_7', 'A0A1C5QHK8_Helix_8', 'A0A1C5QHK8_Helix_9', 'A0A1C5QHK8_Helix_10', 'A0A1C5QHK8_Helix_11', 'A0A1C5QX74_Helix_1', 'A0A1C5QX74_Helix_2', 'A0A1C5QX74_Helix_3', 'A0A1C5QX74_Helix_4', 'A0A1C5QX74_Helix_5', 'A0A1C5QX74_Helix_6', 'A0A1C5QX74_Helix_7', 'A0A1C5QX74_Helix_8', 'A0A1C5QX74_Helix_9', 'A0A1C5QX74_Helix_10', 'A0A1C5QX74_Helix_11', 'A0A1C5R1D9_Helix_1', 'A0A1C5R1D9_Helix_2', 'A0A1C5R1D9_Helix_3', 'A0A1C5R1D9_Helix_4', 'A0A1C5R1D9_Helix_5', 'A0A1C5R1D9_Helix_6', 'A0A1C5R1D9_Helix_7', 'A0A1C5R1D9_Helix_8', 'A0A1C5R1D9_Helix_9', 'A0A1C5R1D9_Helix_10', 'A0A1C5R1D9_Helix_11', 'A0A1C5R365_Helix_1', 'A0A1C5R365_Helix_2', 'A0A1C5R365_Helix_3', 'A0A1C5R365_Helix_4', 'A0A1C5R365_Helix_5', 'A0A1C5R365_Helix_6', 'A0A1C5R365_Helix_7', 'A0A1C5R365_Helix_8', 'A0A1C5R365_Helix_9', 'A0A1C5R365_Helix_10', 'A0A1C5R365_Helix_11', 'A0A1C5R381_Helix_1', 'A0A1C5R381_Helix_2', 'A0A1C5R381_Helix_3', 'A0A1C5R381_Helix_4', 'A0A1C5R381_Helix_5', 'A0A1C5R381_Helix_6', 'A0A1C5R381_Helix_7', 'A0A1C5R381_Helix_8', 'A0A1C5R381_Helix_9', 'A0A1C5R381_Helix_10', 'A0A1C5R381_Helix_11', 'A0A1C5RAN1_Helix_1', 'A0A1C5RAN1_Helix_2', 'A0A1C5RAN1_Helix_3', 'A0A1C5RAN1_Helix_4', 'A0A1C5RAN1_Helix_5', 'A0A1C5RAN1_Helix_6', 'A0A1C5RAN1_Helix_7', 'A0A1C5RAN1_Helix_8', 'A0A1C5RAN1_Helix_9', 'A0A1C5RAN1_Helix_10', 'A0A1C5RAN1_Helix_11', 'A0A1C5S8B5_Helix_1', 'A0A1C5S8B5_Helix_2', 'A0A1C5S8B5_Helix_3', 'A0A1C5S8B5_Helix_4', 'A0A1C5S8B5_Helix_5', 'A0A1C5S8B5_Helix_6', 'A0A1C5S8B5_Helix_7', 'A0A1C5S8B5_Helix_8', 'A0A1C5S8B5_Helix_9', 'A0A1C5S8B5_Helix_10', 'A0A1C5S8B5_Helix_11', 'A0A1C5SQE8_Helix_1', 'A0A1C5SQE8_Helix_2', 'A0A1C5SQE8_Helix_3', 'A0A1C5SQE8_Helix_4', 'A0A1C5SQE8_Helix_5', 'A0A1C5SQE8_Helix_6', 'A0A1C5SQE8_Helix_7', 'A0A1C5SQE8_Helix_8', 'A0A1C5SQE8_Helix_9', 'A0A1C5SQE8_Helix_10', 'A0A1C5SQE8_Helix_11', 'A0A1C5SVL0_Helix_1', 'A0A1C5SVL0_Helix_2', 'A0A1C5SVL0_Helix_3', 'A0A1C5SVL0_Helix_4', 'A0A1C5SVL0_Helix_5', 'A0A1C5SVL0_Helix_6', 'A0A1C5SVL0_Helix_7', 'A0A1C5SVL0_Helix_8', 'A0A1C5SVL0_Helix_9', 'A0A1C5SVL0_Helix_10', 'A0A1C5SVL0_Helix_11', 'A0A1C5T8Y6_Helix_1', 'A0A1C5T8Y6_Helix_2', 'A0A1C5T8Y6_Helix_3', 'A0A1C5T8Y6_Helix_4', 'A0A1C5T8Y6_Helix_5', 'A0A1C5T8Y6_Helix_6', 'A0A1C5T8Y6_Helix_7', 'A0A1C5T8Y6_Helix_8', 'A0A1C5T8Y6_Helix_9', 'A0A1C5T8Y6_Helix_10', 'A0A1C5T8Y6_Helix_11', 'A0A1C5TF49_Helix_1', 'A0A1C5TF49_Helix_2', 'A0A1C5TF49_Helix_3', 'A0A1C5TF49_Helix_4', 'A0A1C5TF49_Helix_5', 'A0A1C5TF49_Helix_6', 'A0A1C5TF49_Helix_7', 'A0A1C5TF49_Helix_8', 'A0A1C5TF49_Helix_9', 'A0A1C5TF49_Helix_10', 'A0A1C5TF49_Helix_11', 'A0A1C5U2K1_Helix_1', 'A0A1C5U2K1_Helix_2', 'A0A1C5U2K1_Helix_3', 'A0A1C5U2K1_Helix_4', 'A0A1C5U2K1_Helix_5', 'A0A1C5U2K1_Helix_6', 'A0A1C5U2K1_Helix_7', 'A0A1C5U2K1_Helix_8', 'A0A1C5U2K1_Helix_9', 'A0A1C5U2K1_Helix_10', 'A0A1C5U2K1_Helix_11', 'A0A1C5UAP1_Helix_1', 'A0A1C5UAP1_Helix_2', 'A0A1C5UAP1_Helix_3', 'A0A1C5UAP1_Helix_4', 'A0A1C5UAP1_Helix_5', 'A0A1C5UAP1_Helix_6', 'A0A1C5UAP1_Helix_7', 'A0A1C5UAP1_Helix_8', 'A0A1C5UAP1_Helix_9', 'A0A1C5UAP1_Helix_10', 'A0A1C5UAP1_Helix_11', 'A0A1C5UEH7_Helix_1', 'A0A1C5UEH7_Helix_2', 'A0A1C5UEH7_Helix_3', 'A0A1C5UEH7_Helix_4', 'A0A1C5UEH7_Helix_5', 'A0A1C5UEH7_Helix_6', 'A0A1C5UEH7_Helix_7', 'A0A1C5UEH7_Helix_8', 'A0A1C5UEH7_Helix_9', 'A0A1C5UEH7_Helix_10', 'A0A1C5UEH7_Helix_11', 'A0A1C5UU75_Helix_1', 'A0A1C5UU75_Helix_2', 'A0A1C5UU75_Helix_3', 'A0A1C5UU75_Helix_4', 'A0A1C5UU75_Helix_5', 'A0A1C5UU75_Helix_6', 'A0A1C5UU75_Helix_7', 'A0A1C5UU75_Helix_8', 'A0A1C5UU75_Helix_9', 'A0A1C5UU75_Helix_10', 'A0A1C5UU75_Helix_11', 'A0A1C5VCM0_Helix_1', 'A0A1C5VCM0_Helix_2', 'A0A1C5VCM0_Helix_3', 'A0A1C5VCM0_Helix_4', 'A0A1C5VCM0_Helix_5', 'A0A1C5VCM0_Helix_6', 'A0A1C5VCM0_Helix_7', 'A0A1C5VCM0_Helix_8', 'A0A1C5VCM0_Helix_9', 'A0A1C5VCM0_Helix_10', 'A0A1C5VCM0_Helix_11', 'A0A1C5WY82_Helix_1', 'A0A1C5WY82_Helix_2', 'A0A1C5WY82_Helix_3', 'A0A1C5WY82_Helix_4', 'A0A1C5WY82_Helix_5', 'A0A1C5WY82_Helix_6', 'A0A1C5WY82_Helix_7', 'A0A1C5WY82_Helix_8', 'A0A1C5WY82_Helix_9', 'A0A1C5WY82_Helix_10', 'A0A1C5WY82_Helix_11', 'A0A1C5Y526_Helix_1', 'A0A1C5Y526_Helix_2', 'A0A1C5Y526_Helix_3', 'A0A1C5Y526_Helix_4', 'A0A1C5Y526_Helix_5', 'A0A1C5Y526_Helix_6', 'A0A1C5Y526_Helix_7', 'A0A1C5Y526_Helix_8', 'A0A1C5Y526_Helix_9', 'A0A1C5Y526_Helix_10', 'A0A1C5Y526_Helix_11', 'A0A1C5YFR7_Helix_1', 'A0A1C5YFR7_Helix_2', 'A0A1C5YFR7_Helix_3', 'A0A1C5YFR7_Helix_4', 'A0A1C5YFR7_Helix_5', 'A0A1C5YFR7_Helix_6', 'A0A1C5YFR7_Helix_7', 'A0A1C5YFR7_Helix_8', 'A0A1C5YFR7_Helix_9', 'A0A1C5YFR7_Helix_10', 'A0A1C5YFR7_Helix_11', 'A0A1C5YH18_Helix_1', 'A0A1C5YH18_Helix_2', 'A0A1C5YH18_Helix_3', 'A0A1C5YH18_Helix_4', 'A0A1C5YH18_Helix_5', 'A0A1C5YH18_Helix_6', 'A0A1C5YH18_Helix_7', 'A0A1C5YH18_Helix_8', 'A0A1C5YH18_Helix_9', 'A0A1C5YH18_Helix_10', 'A0A1C5YH18_Helix_11', 'A0A1C5Z331_Helix_1', 'A0A1C5Z331_Helix_2', 'A0A1C5Z331_Helix_3', 'A0A1C5Z331_Helix_4', 'A0A1C5Z331_Helix_5', 'A0A1C5Z331_Helix_6', 'A0A1C5Z331_Helix_7', 'A0A1C5Z331_Helix_8', 'A0A1C5Z331_Helix_9', 'A0A1C5Z331_Helix_10', 'A0A1C5Z331_Helix_11', 'A0A1C5Z9P9_Helix_1', 'A0A1C5Z9P9_Helix_2', 'A0A1C5Z9P9_Helix_3', 'A0A1C5Z9P9_Helix_4', 'A0A1C5Z9P9_Helix_5', 'A0A1C5Z9P9_Helix_6', 'A0A1C5Z9P9_Helix_7', 'A0A1C5Z9P9_Helix_8', 'A0A1C5Z9P9_Helix_9', 'A0A1C5Z9P9_Helix_10', 'A0A1C5Z9P9_He

In [86]:
rees = dict(zip(combine, headers))

NameError: name 'combine' is not defined

In [ ]:
len(rees)

In [ ]:
new_dict = {k: v for k, v in zip(ods, headers)}

In [ ]:
len(new_dict)
new_dict

In [ ]:
def list_duplicates(seq):
  seen = set()
  seen_add = seen.add
  # adds all elements it doesn't know yet to seen and all other to seen_twice
  seen_twice = set( x for x in seq if x in seen or seen_add(x) )
  # turn the set into a list (as requested)
  return list( seen_twice )

In [ ]:
len(data_list)

In [ ]:
soon = list_duplicates(data_list)
nondup = []
dup = []

for fits in data_list:
    if fits in soon:
        dup.append(fits)
    else:
        nondup.append(fits)

In [ ]:
dup

In [ ]:
sopn = list_duplicates(soon)
undup = []
dupu = []

for thuts in data_into_list:
    if thuts in sopn:
        dupu.append(thuts)
    else:
        undup.append(thuts)

In [ ]:
len(nondup)

In [89]:
rees = {}
for key in matches:
    for value in headers:
        rees[key] = value
        headers.remove(value)
        break

In [90]:
len(rees)

11561

In [ ]:
# !seqkit rmdup -n helix1.fasta > helixrmdup1.fasta

In [91]:
with open("rees_dict.txt", 'w') as f:  
    for key, value in rees.items():  
        f.write('%s:%s\n' % (key, value))

In [94]:
with open('helix1.fasta') as original, open('helix1n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [95]:
with open('helix2.fasta') as original, open('helix2n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [96]:
with open('helix3.fasta') as original, open('helix3n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [97]:
with open('helix4.fasta') as original, open('helix4n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [98]:
with open('helix5.fasta') as original, open('helix5n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [99]:
with open('helix6.fasta') as original, open('helix6n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [100]:
with open('helix7.fasta') as original, open('helix7n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [101]:
with open('helix8.fasta') as original, open('helix8n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [102]:
with open('helix9.fasta') as original, open('helix9n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [103]:
with open('helix10.fasta') as original, open('helix10n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [104]:
with open('helix11.fasta') as original, open('helix11n2.fasta', 'w') as corrected:
    for seq_record in SeqIO.parse(original, 'fasta'):
        if seq_record.id in rees:
            seq_record.id = rees[seq_record.id]
        SeqIO.write(seq_record, corrected, 'fasta')

In [ ]:
loshtit = []

headers = u.search("B2I573", frmt = 'fasta')
#     print(headers)
record = SeqIO.read(StringIO(headers), "fasta")
print(record)
loshtit.append(record)