In [9]:
import pandas as pd
from Bio import SeqIO
from bioservices.uniprot import UniProt
from tqdm import tqdm
import ete3
from ete3 import Tree
from ete3 import NodeStyle

In [ ]:
u = UniProt(verbose=False)

In [ ]:
tree = Tree('TBE_named_tree.new')

ids = []

for leaf in tree:
    a = leaf.name.split(' ')[-1]
    ids.append(a)

In [ ]:
linige = []
for item in tqdm(ids):
    lineage = u.search(item, columns='lineage')
    print(item)
    print(lineage)
    finige = f"{item}:{lineage}" 
    linige.append(finige)

In [ ]:
kingdom1 = []
kingdom2 = []
together = []


for items in linige:
    if "(domain)" in items:
        first = items.split(' (domain)')[0]
        second = first.split(' ')[-1]
        third = first.split(':')[0]

                    
        kingdom1.append(third)
        kingdom2.append(second)
        together.append(f"{third}: {second}")

dicking = dict(zip(kingdom1, kingdom2))

In [ ]:
with open('kingdom.txt', 'w') as fp:
    for ite in together:
        # write each item on a new line
        fp.write("%s\n" % ite)
    print('Done')

In [2]:
# with open('kingdom.txt', 'r') as file:

#     linage = []
#     for line in file:
#         line = line.strip()
#         linage.append(line)

# print(linage)

['A0A7I7U7Q2: Bacteria', 'A0A375YPN6: Bacteria', 'A0A0B4E6X7: Bacteria', 'V4RHR4: Bacteria', 'Q0G2T1: Bacteria', 'K9Z0D3: Bacteria', 'F7ZJZ1: Bacteria', 'A0A063Y394: Bacteria', 'A0A1G8M218: Bacteria', 'A0A7G5DK09: Bacteria', 'V4RK08: Bacteria', 'Q0G2V0: Bacteria', 'Q0G2U1: Bacteria', 'A0A0B4DVJ9: Bacteria', 'A0AA35G8C0: Bacteria', 'A0A0E3WZH5: Archaea', 'A0A0E3R4G0: Archaea', 'A0A0G3CAR5: Archaea', 'A0A1J5NNB8: Bacteria', 'A0A0S6UHP2: Bacteria', 'Q6QH01: Eukaryota', 'A0A2K3DWA2: Eukaryota', 'J9ZB82: Bacteria', 'A0AAE6G518: Bacteria', 'Q1CZ61: Bacteria', 'A0A5M4ATH9: Bacteria', 'A0A1I0BYN1: Bacteria', 'R9GM11: Bacteria', 'M4VEJ9: Bacteria', 'A0A2W4ZXC0: Bacteria', 'A0A5M4B0G1: Bacteria', 'A0A0E3QY45: Archaea', 'A0A2A2MCP3: Bacteria', 'K8VYU6: Bacteria', 'A0A5M4AUM9: Bacteria', 'G7WFX4: Bacteria', 'I4D6Z7: Bacteria', 'E5Y678: Bacteria', 'A0A1U9Z147: Bacteria', 'A0A248LNK5: Bacteria', 'C1D6X6: Bacteria', 'E3GI40: Bacteria', 'A0A017SYR8: Bacteria', 'Q2IHY5: Bacteria', 'A0A1H7CU41: Bacteria', 'A0A414NWT8: Bacteria', 'C9KKP2: Bacteria', 'A0A857DMN9: Bacteria', 'A0A857DDJ7: Bacteria', 'I4D1H5: Bacteria', 'J7ITF6: Bacteria', 'G7WA28: Bacteria', 'B3DUX7: Bacteria', 'B8FZP7: Bacteria', 'J7J5E7: Bacteria', 'G7WCB6: Bacteria', 'I4DBY0: Bacteria', 'F7NPQ3: Bacteria', 'F8IJE0: Bacteria', 'A0A1G5W0P2: Bacteria', 'A0A383TEW4: Bacteria', 'A0A2T5IEE6: Bacteria', 'A0A143ZCA8: Bacteria', 'A0A5C5EBG6: Bacteria', 'A0A1W1IDJ2: Bacteria', 'A0A143Y517: Bacteria', 'A0A5C5EC53: Bacteria', 'A0A383TB64: Bacteria', 'A0A2T5IP85: Bacteria', 'A0A1W1IEF4: Bacteria', 'A0A143Z212: Bacteria', 'A0A143Y9S4: Bacteria', 'A0A143YNF2: Bacteria', 'Q97L80: Bacteria', 'Q1JXS5: Bacteria', 'A0A1M6JKY3: Bacteria', 'B8FGW0: Bacteria', 'Q3AP28: Bacteria', 'Q46G49: Archaea', 'A0A0E3R6E1: Archaea', 'A0A0E3SP24: Archaea', 'A0A6H9FYW4: Bacteria', 'A0A6H9GFU4: Bacteria', 'K9W6F3: Bacteria', 'A0A2N6K4Y5: Bacteria', 'K9WT03: Bacteria', 'A0A9Q5QVI9: Bacteria', 'A0A1X4G8K1: Bacteria', 'A0A977NL98: Archaea', 'Q3Z7F9: Bacteria', 'D2BIB2: Bacteria', 'A0A2J1DY21: Bacteria', 'A0A328EMN2: Bacteria', 'A0A8F5VN39: Archaea', 'Q2FQT3: Archaea', 'J1ASR8: Archaea', 'J1L5M8: Archaea', 'A0A8F5ZDT8: Archaea', 'Q2FS34: Archaea', 'A0A075WEB4: Archaea', 'A0A075WBP9: Archaea', 'A0A060HSP0: Archaea', 'A0A060HFT5: Archaea', 'A0RXK8: Archaea', 'A0RUZ2: Archaea', 'A0A0S6UEK9: Bacteria', 'A0A1J5JH24: Bacteria', 'A0A1J5NTP7: Bacteria', 'A0AAC9HF66: Bacteria', 'H6LKH9: Bacteria', 'H6LKH6: Bacteria', 'A0A1Q2C7H7: Bacteria', 'A0A173R3W6: Bacteria', 'A0A174SD65: Bacteria', 'A0AAQ3JHU5: Bacteria', 'K8EJ02: Bacteria', 'A0A0N0UVD0: Bacteria', 'A0A0R1FQX7: Bacteria', 'A0A1L8CGR2: Bacteria', 'A0A087EQK8: Bacteria', 'A0A836YVS6: Bacteria', 'A0A0M9DF80: Bacteria', 'E6ME92: Bacteria', 'A0A369MHK2: Bacteria', 'A0A369MRW6: Bacteria', 'A0A5C5BWI6: Bacteria', 'A0A369N7Y3: Bacteria', 'C8WLL8: Bacteria', 'D6E7B3: Bacteria', 'A0A369M386: Bacteria', 'A0A369NYJ2: Bacteria', 'A0A3N0AQL8: Bacteria', 'A0A172RYW3: Bacteria', 'A0A1Y3U5V2: Bacteria', 'A0AA94HTL8: Bacteria', 'B8IZX4: Bacteria', 'A0A4P7UHQ5: Bacteria', 'A0A8G2F3G4: Bacteria', 'E5Y789: Bacteria', 'F0JGZ1: Bacteria', 'M1WRK6: Bacteria', 'D8PD01: Bacteria', 'A0A562S8V2: Bacteria', 'B8FDY8: Bacteria', 'A0A1M6BPM0: Bacteria', 'A0A0A2VPU3: Eukaryota', 'A0A410JZR4: Bacteria', 'A0A3P2A7W8: Bacteria', 'A0AAE9HXH3: Bacteria', 'A0AB74ES40: Bacteria', 'B4RJL6: Bacteria', 'A0A377I7W9: Bacteria', 'A0AAE5THS3: Bacteria', 'A0A0F5EZP7: Bacteria', 'U1H1F7: Bacteria', 'A0A0A2ZRL7: Bacteria', 'F4H924: Bacteria', 'Q0I445: Bacteria', 'A0A060UWC8: Bacteria', 'G0JRG6: Bacteria', 'A0A257T8W6: Bacteria', 'A0A6A6KH23: Eukaryota', 'A0A6A6LR03: Eukaryota', 'B9RP82: Eukaryota', 'B9SXC7: Eukaryota', 'A0A6A6MHQ0: Eukaryota', 'A0A8T2FW07: Eukaryota', 'Q9M6N7: Eukaryota', 'A0A257SYX3: Bacteria', 'A0A257T7G4: Bacteria', 'G0JRG9: Bacteria', 'A0A7T4WEP4: Bacteria', 'A0A1B9BUU6: Bacteria', 'A0A060URC3: Bacteria', 'A0A6A6KSX7: Eukaryota', 'A0A6A6KHV7: Eukaryota', 'J9Z839: Bacteria', 'A0A059XXR1: Bacteria', 'C0QTA4: Bacteria', 'R7PZ71: Archaea', 'A0A2H4U5R1: Archaea', 'D2ZRW2: Archaea', 'B9ACS5: Archaea', 'A5UJR1: Archaea', 'A0A1V6N1K2: Archaea', 'A0A1V6N3J8: Archaea', 'A0A089ZBW5: Archaea', 'Q2NGJ2: Archaea', 'O26757: Archaea', 'K0N2R5: Bacteria', 'I5AZQ4: Bacteria', 'A0A975BTN0: Bacteria', 'A0A975GIX9: Bacteria', 'A0AAI9F1Z0: Bacteria', 'C0QSY0: Bacteria', 'D4XLN6: Bacteria', 'A0A4R1YA82: Bacteria', 'A0A4Y7XC43: Bacteria', 'A0A7Z0V0A4: Bacteria', 'A0A2L1VKW1: Bacteria', 'A0AA36K8C1: Bacteria', 'A0A836MMQ8: Bacteria', 'A0A1V2USG9: Bacteria', 'N8S8Q9: Bacteria', 'A0A1S2FYQ6: Bacteria', 'A0AAV3JZ83: Bacteria', 'A0A062IU58: Bacteria', 'A0A009HRP0: Bacteria', 'A0A836M2B6: Bacteria', 'N9KCW3: Bacteria', 'A0A0D5YN10: Bacteria', 'A0A009TDB1: Bacteria', 'A0A009PYN3: Bacteria', 'A0A385ER44: Bacteria', 'A0A9P3CXY2: Bacteria', 'A0A242U7D1: Bacteria', 'A0A009HIT6: Bacteria', 'A0A009NKA6: Bacteria', 'A0A009QS91: Bacteria', 'A0AAE8G914: Bacteria', 'A0A010ILW8: Bacteria', 'A0A3R9QC30: Bacteria', 'R8XXZ3: Bacteria', 'A0A446ZP57: Bacteria', 'A0A009ZC67: Bacteria', 'A0A0M3AB44: Bacteria', 'A1AVV2: Bacteria', 'Q47X17: Bacteria', 'A0A1Y5E3E3: Bacteria', 'W7QGE0: Bacteria', 'V5E0F3: Bacteria', 'O26759: Archaea', 'A9BDN5: Bacteria', 'A0A2S8FE64: Bacteria', 'A0A1F9ZPG7: Bacteria', 'B3PIH2: Bacteria', 'Q0F2M7: Bacteria', 'F5ISF6: Bacteria', 'F3QPR6: Bacteria', 'A4BMY5: Bacteria', 'I7ZHW3: Bacteria', 'A0A7G5DK18: Bacteria', 'A0A1G8M2C4: Bacteria', 'A0A1A9KDK6: Bacteria', 'A0A4R5U5V1: Bacteria', 'A0A653N397: Bacteria', 'A0A7V8CC59: Bacteria', 'A0A498BYJ1: Bacteria', 'A0A290XBB5: Bacteria', 'A0A4V3ALP8: Bacteria', 'A0A5C5TYS5: Bacteria', 'A0A562BXM4: Bacteria', 'A0A5C5TUT2: Bacteria', 'A0A3N2RMC5: Bacteria', 'A0A0S2DQB6: Bacteria', 'A0AAU9AYK2: Bacteria', 'A0A0S2FHD7: Bacteria', 'D9SI59: Bacteria', 'A0A087L0B9: Bacteria', 'A0AAU0KYH5: Bacteria', 'A0A502GPV4: Bacteria', 'A0A2N0MZ27: Bacteria', 'A0A4R2Z2K6: Bacteria', 'A0A4R7GKA0: Bacteria', 'E5B358: Bacteria', 'D4GLQ6: Bacteria', 'A0A0H3KTD3: Bacteria', 'A0A3N1VXY4: Bacteria', 'A0AAX3LDB0: Bacteria', 'G8LPW2: Bacteria', 'A0A2T4XZC1: Bacteria', 'A0A4Q2EAG7: Bacteria', 'A0A376F4E3: Bacteria', 'A0A1Z3MS36: Bacteria', 'A0AAQ0J9B4: Bacteria', 'A0A144NLT9: Bacteria', 'A0A0X4EQN7: Bacteria', 'A0AB37VPC6: Bacteria', 'A0A330GB00: Bacteria', 'A0AAW3HMY8: Bacteria', 'A0A837LGM5: Bacteria', 'A0AAU7FWX7: Bacteria', 'A0A2W0GQV0: Bacteria', 'A0A6S5K4J1: Bacteria', 'A0A9Q7K161: Bacteria', 'A0AA96M6A7: Bacteria', 'A0A7T0DXY9: Bacteria', 'A0A4R6ECY1: Bacteria', 'A0A3N2EN92: Bacteria', 'A0A318FY98: Bacteria', 'A0A6B8N021: Bacteria', 'A0A249WDJ1: Bacteria', 'A0A0H3H4I7: Bacteria', 'A0A1Y6GLJ1: Bacteria', 'A0A855F5Y8: Bacteria', 'A7MFK3: Bacteria', 'V5U2Z4: Bacteria', 'A0A423Y4I6: Bacteria', 'A0A2T2Y0D5: Bacteria', 'A0A6G9RRZ9: Bacteria', 'A0A085GI50: Bacteria', 'A0A4R8F1T3: Bacteria', 'A0A381CAY8: Bacteria', 'S3K1S2: Bacteria', 'A0A9W5JBA9: Bacteria', 'A0A4Q2QWS1: Bacteria', 'A0A837FET6: Bacteria', 'A0AA37ANA5: Bacteria', 'A0A154YNA3: Bacteria', 'A0A7H8UK07: Bacteria', 'A0A0H3CJM5: Bacteria', 'A0AAE2JRT5: Bacteria', 'A0A427KNL6: Bacteria', 'A0A855EH99: Bacteria', 'A0AAP9AKL4: Bacteria', 'A0A3N1I597: Bacteria', 'A0A165BP25: Bacteria', 'F5NRG4: Bacteria', 'I6D653: Bacteria', 'A0A6N3R8E8: Bacteria', 'A0A2S8JW40: Bacteria', 'S1Q791: Bacteria', 'F4SUS0: Bacteria', 'A0AAJ3NZS1: Bacteria', 'A0AAV3IBF7: Bacteria', 'A0A1X3JM59: Bacteria', 'P69681: Bacteria', 'P69680: Bacteria', 'A0A1X3J661: Bacteria', 'A0A6C8LST1: Bacteria', 'G5PZ41: Bacteria', 'D2TLS8: Bacteria', 'A0AA86MAT4: Bacteria', 'A0A2A7U6W1: Bacteria', 'D4F313: Bacteria', 'A0AAU8P297: Bacteria', 'A0A022PMF0: Bacteria', 'A0A2S8QA29: Bacteria', 'A0A4V2X6C2: Bacteria', 'A0A1G5PWV0: Bacteria', 'A0A5C4RNH5: Bacteria', 'Q7N0M6: Bacteria', 'A0A4R4K1P9: Bacteria', 'C7BJG7: Bacteria', 'D2BUJ8: Bacteria', 'E0SD83: Bacteria', 'C6CBB1: Bacteria', 'A0A1X3RP39: Bacteria', 'A0A1H3WA00: Bacteria', 'A0A097R891: Bacteria', 'A0A377PLP5: Bacteria', 'A0A1C6Z081: Bacteria', 'G9Y5B0: Bacteria', 'A0A4Q9EVG0: Bacteria', 'A0A2A2M8K7: Bacteria', 'B4EU65: Bacteria', 'A0A2X2C038: Bacteria', 'B6XI39: Bacteria', 'A0A4R3NLV5: Bacteria', 'A0A140NHJ5: Bacteria', 'A0AA86YS65: Bacteria', 'A0A379FML4: Bacteria', 'A0A264VQM8: Bacteria', 'K8VZC6: Bacteria', 'K8W1E2: Bacteria', 'A0A1B9K8L2: Bacteria', 'A0A1B9M1A9: Bacteria', 'A0A1B9N3H7: Bacteria', 'A0A657K391: Bacteria', 'A0A066TEF8: Bacteria', 'A0A1B9M5B8: Bacteria', 'A0A1B9LFW3: Bacteria', 'A0A1B9MZ78: Bacteria', 'A0A1B9MBX6: Bacteria', 'A0A1B9JHS5: Bacteria', 'A0A556SRH6: Bacteria', 'A0A242NIL1: Bacteria', 'A0A2V4EA49: Bacteria', 'A0A556RTU3: Bacteria', 'A0A1B9JPL5: Bacteria', 'A0A2C6C0X3: Bacteria', 'A0AAJ4W8U3: Bacteria', 'C6DB68: Bacteria', 'A0AAI9PDD6: Bacteria', 'A0A419AVL2: Bacteria', 'A0A7V8IKS6: Bacteria', 'M1SJL5: Bacteria', 'A0AAN5RUB6: Bacteria', 'A0A433ZQ80: Bacteria', 'G7UUY6: Bacteria', 'A0A378YR15: Bacteria', 'A0AA92K392: Bacteria', 'A0AA92EGF5: Bacteria', 'G2ZN72: Bacteria', 'A0AAD0WI43: Bacteria', 'G3A431: Bacteria', 'A0AAP7ZLZ1: Bacteria', 'A0AB33VI30: Bacteria', 'F6G5I9: Bacteria', 'A0A0S4WFM4: Bacteria', 'A0A0S4VNK2: Bacteria', 'A0A6M3ZJI1: Bacteria', 'Q45HK8: Bacteria', 'A0A127PIQ9: Bacteria', 'G0AFH4: Bacteria', 'K1K628: Bacteria', 'Q47K18: Bacteria', 'A0A1G7VM92: Bacteria', 'A0A4R2M206: Bacteria', 'A1VIG8: Bacteria', 'A0A1W9KSU5: Bacteria', 'Q221S8: Bacteria', 'A0A1R1IDV3: Bacteria', 'A0A3N1WP41: Bacteria', 'A0A147GP06: Bacteria', 'A0A370FPU0: Bacteria', 'A0A9E9LXV9: Bacteria', 'F5Y3C1: Bacteria', 'A0A4P6UIK6: Bacteria', 'F3KUN4: Bacteria', 'A0A016XCG9: Bacteria', 'A0A127JTU2: Bacteria', 'Q2KZK9: Bacteria', 'A0A0C6P439: Bacteria', 'A0A0H3LUA3: Bacteria', 'Q7W7D3: Bacteria', 'E3HJW8: Bacteria', 'A0A424WAH3: Bacteria', 'A0A0X8NXA9: Bacteria', 'A4G1J2: Bacteria', 'A0A8B4RWH8: Bacteria', 'A0A0E3BR91: Bacteria', 'A0A096EEV9: Bacteria', 'A0A5A7MAJ9: Bacteria', 'A0A076PL76: Bacteria', 'B7X047: Bacteria', 'A0A373FQ71: Bacteria', 'A0AAU0LJI3: Bacteria', 'A0A7T2S0Z6: Bacteria', 'A0A4R7FTT2: Bacteria', 'A0A7G5EC77: Bacteria', 'A0A1H9RTW8: Bacteria', 'A0A430AFK9: Bacteria', 'C3X831: Bacteria', 'A0A9E9L9J1: Bacteria', 'C3X1J1: Bacteria', 'A0A420KGW4: Bacteria', 'A0A858ZNJ3: Bacteria', 'F4GED5: Bacteria', 'A0A071M4L5: Bacteria', 'V5BYZ7: Bacteria', 'A0AA35XVN2: Bacteria', 'Q605Y6: Bacteria', 'Q13E03: Bacteria', 'Q6ND34: Bacteria', 'A0AAX3DYV3: Bacteria', 'Q07UM3: Bacteria', 'A0A0D7F2Y9: Bacteria', 'A0A323UE08: Bacteria', 'E6VIW4: Bacteria', 'Q2J376: Bacteria', 'A0A418VIJ8: Bacteria', 'A0A1Y2JH43: Bacteria', 'A0A4Y9V2I5: Bacteria', 'A0A837C6X5: Bacteria', 'A0A1X3H719: Bacteria', 'A0A2T2Q5D5: Bacteria', 'A8HSW6: Bacteria', 'A0A4U1K1W1: Bacteria', 'A0A2U1SS17: Bacteria', 'A0A1H1Z2M2: Bacteria', 'B8ENL9: Bacteria', 'A0A2J7TJ33: Bacteria', 'A0A0T7GZ59: Bacteria', 'A0A0T7FAP8: Bacteria', 'A0A068TC78: Bacteria', 'A0A6A1TYJ4: Bacteria', 'A0A068SVR1: Bacteria', 'A0A8G2IZM3: Bacteria', 'A0A4R3A5P7: Bacteria', 'A0A9Q9D9I3: Bacteria', 'A0A0L8BVU4: Bacteria', 'S9QZ09: Bacteria', 'Q0G0A4: Bacteria', 'A0A011U1K7: Bacteria', 'A0A316BQ38: Bacteria', 'A0A212AV03: Bacteria', 'A0A1G7DX68: Bacteria', 'A0A2W5VAZ2: Bacteria', 'D5VJ32: Bacteria', 'A0A0M2LU39: Bacteria', 'A0A9Q8ZRH9: Bacteria', 'A0A074ME37: Bacteria', 'Q2N625: Bacteria', 'A0A5B2V3B9: Bacteria', 'A0A533I6R2: Bacteria', 'A1B3N0: Bacteria', 'A0A0P6VSR8: Bacteria', 'A0A009IJW0: Bacteria', 'A0A9Q8L398: Bacteria', 'A0A1A0DHK0: Bacteria', 'A0A401WXG0: Bacteria', 'A0A1Y0V4A5: Bacteria', 'A0A009IHG4: Bacteria', 'A0AAE6V1K1: Bacteria', 'A0A399MBI8: Bacteria', 'V9V1P3: Bacteria', 'A0AAQ1KIG0: Bacteria', 'A0A127N1G1: Bacteria', 'A0A5R9A7F0: Bacteria', 'A0A7Z3BHX5: Bacteria', 'A0A6G6J5H2: Bacteria', 'A0A246F6Y0: Bacteria', 'A0A1H0QD41: Bacteria', 'M9YAI9: Bacteria', 'A0A1G8E3L8: Bacteria', 'A0A7G5DPV0: Bacteria', 'V9V818: Bacteria', 'A0A2N1IRT6: Bacteria', 'A0A4R7VEK0: Bacteria', 'A0A5C4PNC3: Bacteria', 'A0A1H4UM25: Bacteria', 'A0A0H2ZKS0: Bacteria', 'A0A9P1R6B9: Bacteria', 'Q9HTR7: Bacteria', 'A0A2R3IMJ8: Bacteria', 'A6VE60: Bacteria', 'A0A075JZ35: Bacteria', 'A0A0G9HEC5: Bacteria', 'A0A172YCA7: Bacteria', 'I8TC71: Bacteria', 'A0A3G9G4Q4: Bacteria', 'E8RSE4: Bacteria', 'A0A258HS77: Bacteria', 'A0A258FS85: Bacteria', 'D9QPC8: Bacteria', 'E8RLT5: Bacteria', 'A0A3G9G2C9: Bacteria', 'A0A2S8WAE5: Bacteria', 'D9QPE5: Bacteria', 'A0A258HPP1: Bacteria', 'A0A258FTB0: Bacteria', 'A0A2S8W2Q0: Bacteria', 'A0A2W5HTC3: Bacteria', 'A0A1T4SFK4: Bacteria', 'A0A060URB8: Bacteria', 'A0A1B9BUZ8: Bacteria', 'G0JRH4: Bacteria', 'A0A1T4SF40: Bacteria', 'A0A009YHU5: Bacteria', 'F3QNA7: Bacteria', 'A0A2S0P9T4: Bacteria', 'W0DZS7: Bacteria', 'C1MX19: Eukaryota', 'B4CV94: Bacteria', 'A0A6J5IRX5: Bacteria', 'A0A0H2XSU4: Bacteria', 'B1JZ69: Bacteria', 'A0A071MMV1: Bacteria', 'A0A3S9N9F3: Bacteria', 'A0AAN0VNJ0: Bacteria', 'A0A248LMH8: Bacteria', 'C1D4X0: Bacteria', 'A0A1I4ZIZ6: Bacteria', 'Q0ARJ4: Bacteria', 'A0A495DND0: Bacteria', 'Q7NQY2: Bacteria', 'A0A1S8D478: Bacteria', 'A0A4Y1MSE7: Bacteria', 'A0A1H9M798: Bacteria', 'A0A076PC09: Bacteria', 'B7X0B4: Bacteria', 'A0A5A7MBN6: Bacteria', 'A0A4R7FI90: Bacteria', 'A0A7G5ENL7: Bacteria', 'A0A096EDY7: Bacteria', 'A0A0L7MC77: Bacteria', 'A0A096HB30: Bacteria', 'A0A373FQ83: Bacteria', 'A0AAU0LAM9: Bacteria', 'A0A7T2W1B3: Bacteria', 'A1VIM5: Bacteria', 'A0A1G6ABL9: Bacteria', 'B8EMQ8: Bacteria', 'A0A1H1P1Y3: Bacteria', 'Q2YLQ6: Bacteria', 'Q21CP1: Bacteria', 'Q07UM1: Bacteria', 'A0A0D7F328: Bacteria', 'A0AAX3DYT1: Bacteria', 'A0AAF0BM73: Bacteria', 'A0A323UDG5: Bacteria', 'A0A1H1Z201: Bacteria', 'A0A1X3FU16: Bacteria', 'A0A2T2Q5F1: Bacteria', 'Q60BI2: Bacteria', 'A0AA35XZV0: Bacteria', 'Q60C43: Bacteria', 'A0A037ZJY5: Bacteria', 'M9RJS5: Bacteria', 'A0A366XFS8: Bacteria', 'A0AAD0ED18: Bacteria', 'A0A4U1JNL6: Bacteria', 'A0A1G7H8X3: Bacteria', 'A0A2R4MBA2: Bacteria', 'A0A1Y0Y7K0: Bacteria', 'A0A1A0CF26: Bacteria', 'A0AAN1PKE9: Bacteria', 'A0A1Y0UZX2: Bacteria', 'F1YU33: Bacteria', 'A0A1D8QW75: Bacteria', 'A0A401WUW1: Bacteria', 'A0AAC9SUX5: Bacteria', 'A0A252A952: Bacteria', 'A0A149TSA9: Bacteria', 'A0A095B4M5: Bacteria', 'A0A511FKZ2: Bacteria', 'A0A252EGD8: Bacteria', 'A0A0U5EV31: Bacteria', 'A0A149U2G9: Bacteria', 'F7VFV0: Bacteria', 'A0A149V963: Bacteria', 'A0A149QAW7: Bacteria', 'A0A149UWF2: Bacteria', 'A0A1D8UWJ6: Bacteria', 'Q8GQS1: Bacteria', 'A0A211ZGL5: Bacteria', 'A0A0A0D6K5: Bacteria', 'B4D7W2: Bacteria', 'A0A3R9Q7C4: Bacteria', 'F2B2B8: Bacteria', 'L7CG11: Bacteria', 'K5CFE5: Bacteria', 'M5S735: Bacteria', 'M2A398: Bacteria', 'M5SY07: Bacteria', 'M5U9F0: Bacteria', 'A0A2S8GSU9: Bacteria', 'A3ZZL7: Bacteria', 'A0A2S8F473: Bacteria', 'A0A2S8FR08: Bacteria', 'A0A9P1BFQ1: Eukaryota', 'A0A9R0NTP8: Bacteria', 'W5WIX6: Bacteria', 'E2SD33: Bacteria', 'A0A2S5XAB8: Bacteria', 'A0A2S5WV24: Bacteria', 'A0A8E2UDJ3: Bacteria', 'A0A2S5WZU0: Bacteria', 'A0A2S5UW29: Bacteria', 'U3P8G1: Bacteria', 'A0A2T0GTU1: Bacteria', 'H5UND3: Bacteria', 'K6W5X0: Bacteria', 'A0A1I5GN22: Bacteria', 'D2SE15: Bacteria', 'A0A1M7UEG2: Bacteria', 'A0A4Q7Y9I7: Bacteria', 'H6RWK9: Bacteria', 'A0A7I7U271: Bacteria', 'A0A375YC85: Bacteria', 'K0K7J4: Bacteria', 'A0A068NPW2: Bacteria', 'A0LV78: Bacteria', 'A0A542XGT4: Bacteria', 'A8M670: Bacteria', 'A0A562IDY7: Bacteria', 'A0A9Y2AG30: Bacteria', 'A0A4P8HC89: Bacteria', 'U1SIR9: Bacteria', 'A0A2I1M481: Bacteria', 'B8DVH9: Bacteria', 'A0A021VMC6: Bacteria', 'A0A7I7U9R8: Bacteria', 'A0A375YJF2: Bacteria', 'A0A4R3ZZ35: Bacteria', 'F6FRU9: Bacteria', 'A0A1H1U2Q6: Bacteria', 'A0A1Y0HX98: Bacteria', 'A0A4Y4DZN4: Bacteria', 'A0AAV5P931: Bacteria', 'A0A251XJT0: Bacteria', 'A5CRL2: Bacteria', 'A0A399NT81: Bacteria', 'B0RC35: Bacteria', 'A0A399T909: Bacteria', 'A0A251YU48: Bacteria', 'A0A251Y3N4: Bacteria', 'A0AAI9EKL2: Bacteria', 'A0A251YFS0: Bacteria', 'A0A225CMT8: Bacteria', 'A0A251XU71: Bacteria', 'A0A2S5V5H2: Bacteria', 'A0A2S5WX34: Bacteria', 'A0A8E2R1Y5: Bacteria', 'A0A2S5X482: Bacteria', 'A0A2S5WMT7: Bacteria', 'A0A4P6UIJ8: Bacteria', 'A0A016XDZ5: Bacteria', 'E2SD44: Bacteria', 'A0A2S5WUP6: Bacteria', 'A0A2S5V2F6: Bacteria', 'A0A2S5WGI8: Bacteria', 'A0A8E2QZI6: Bacteria', 'A0A2S5X1J4: Bacteria', 'U3PCH5: Bacteria', 'A0A1E2SKM1: Bacteria', 'A0A4R3ZNW3: Bacteria', 'A0A6G9Y3Q0: Bacteria', 'K0F9X7: Bacteria', 'A0A660CH85: Bacteria', 'A0A1I4W3A0: Bacteria', 'A0A1T4SFY6: Bacteria', 'A0A6G9XJV9: Bacteria', 'M0J579: Archaea', 'I3R0S7: Archaea', 'J3EXK0: Archaea', 'E4NS62: Archaea', 'A0A482TED1: Archaea', 'U1PIR6: Archaea', 'U1PPI7: Archaea', 'M0D580: Archaea', 'A0A518SEK0: Archaea', 'A0A830EZG5: Archaea', 'A0A365TD36: Archaea', 'A0A169X118: Archaea', 'A0AAV3UFU8: Archaea', 'A0A2R6IP35: Archaea', 'A0A8T8WGV8: Archaea', 'A0A7D5GLZ7: Archaea', 'M0AHA9: Archaea', 'M0B6S6: Archaea', 'L9ZNI9: Archaea', 'A0A5P9P1L2: Archaea', 'L9XS69: Archaea', 'M0C732: Archaea', 'A0A482YEN8: Archaea', 'A0AAF0PE89: Archaea', 'L0JT30: Archaea', 'A0A1S8AZU6: Archaea', 'A0A419WE02: Archaea', 'F8D7H6: Archaea', 'A0A7D6H3L9: Archaea', 'A0A8A2VRW2: Archaea', 'D2RU19: Archaea', 'A0A8T8E5C4: Archaea', 'A0A4P9TIR6: Archaea', 'L9YZJ4: Archaea', 'I7CDY2: Archaea', 'L9YY28: Archaea', 'L9ZG19: Archaea', 'A0A482Y865: Archaea', 'A0A2A5QZ19: Archaea', 'M0CJN2: Archaea', 'A0A4P8WNY4: Archaea', 'A0AAV3T9N5: Archaea', 'M0D3Q9: Archaea', 'W0JIB3: Archaea', 'A0A8A2UE16: Archaea', 'A0A7D5KDW5: Archaea', 'A0A9E7NER7: Archaea', 'A0A4D6KHD1: Archaea', 'A0A2R6HGN0: Archaea', 'A0A2R6L1E7: Archaea', 'A0A2R6N841: Archaea', 'A0A2R6M9Y9: Archaea', 'A0A2R6CGI2: Archaea', 'U1NXA4: Archaea', 'Q5UZ98: Archaea', 'M0PEA5: Archaea', 'A0A8J8TCR8: Archaea', 'A0A7D4Y6E4: Archaea', 'A0A4U7FCH1: Archaea', 'A0A256HVI6: Archaea', 'A0A4V6E8U1: Archaea', 'A0A1Y3A9W7: Archaea', 'A0A4U7CDN6: Archaea', 'A0A1Y3AEB2: Archaea', 'A0A2G1WEG4: Archaea', 'A0A3Q9EFA7: Archaea', 'A0A4U7ELJ5: Archaea', 'A0A256HU74: Archaea', 'A0A256HFN6: Archaea', 'A0A256HIH6: Archaea', 'A0A8E8EWD3: Archaea', 'A0AAV3SSM3: Archaea', 'M0EL38: Archaea', 'A0A4U7D6B8: Archaea', 'A0A4V6E5W0: Archaea', 'A0A8T8LM48: Archaea', 'A0A0M9AS13: Archaea', 'A0A498EUJ2: Archaea', 'A0A4U7DV69: Archaea', 'A0A4U7CX07: Archaea', 'A0A498FNH3: Archaea', 'A0A2R6JNJ8: Archaea', 'A0A2R6GLV1: Archaea', 'M1XLN4: Archaea', 'A0A3A6Q4N4: Archaea', 'U1QPB0: Archaea', 'A0A3A6QA08: Archaea', 'A0A544QNG1: Archaea', 'R4W0C0: Archaea', 'A0A2B7GTQ4: Archaea', 'L9XTL3: Archaea', 'A0A2R6FM49: Archaea', 'A0A9N6YWI2: Archaea', 'M0DV62: Archaea', 'M0F7H2: Archaea', 'A0A410TQW1: Archaea', 'A0A7D4BPZ6: Archaea', 'A0A4U7DHS4: Archaea', 'A0A498FNJ6: Archaea', 'M0EBX9: Archaea', 'A0A4U7EV64: Archaea', 'M0NRJ2: Archaea', 'M0D7V4: Archaea', 'M0EBA7: Archaea', 'A0A1Y3AJI8: Archaea', 'A0A2A2FDF5: Archaea', 'B9LU00: Archaea', 'A0A081EVR3: Archaea', 'M0E1M5: Archaea', 'A0A1G7RHP6: Archaea', 'M0P8Z5: Archaea', 'M0NRE6: Archaea', 'A0A6B9Y9J0: Archaea', 'A0A329T9W9: Archaea', 'A0A256IAU5: Archaea', 'A0A2R6KFC5: Archaea', 'J2ZGN6: Archaea', 'A0A2R6ETP9: Archaea', 'A0AAJ4RA85: Archaea', 'A0A554NB52: Archaea', 'A0A2R6I3E5: Archaea', 'A0A8U0HXP0: Archaea', 'M0M6R9: Archaea', 'A0A3A5JCB5: Archaea', 'A0A2R6HFY0: Archaea', 'A0A2R6K016: Archaea', 'A0A063ZJU6: Archaea', 'B8ZYW3: Archaea', 'A0A2R6FX01: Archaea', 'A0A2R6EZG2: Archaea', 'A0A2R6DG65: Archaea', 'A0A368NBY6: Archaea', 'A0A6B9F5H2: Archaea', 'A0A9Y2E7Z6: Archaea', 'A0A2Z2HRJ4: Archaea', 'A0A5D5AW34: Archaea', 'A0A3N6LYC9: Archaea', 'A0A1P8RI15: Archaea', 'L0AHQ0: Archaea', 'A0A346PKS2: Archaea', 'M0B7J9: Archaea', 'A0A1J4LTC1: Archaea', 'A0A897MVN0: Archaea', 'L9X2V2: Archaea', 'A0A8G1HA07: Archaea', 'M0BW44: Archaea', 'A0A8U0A4W0: Archaea', 'A0A3P3RFN3: Archaea', 'A0A345E078: Archaea', 'A0A345E9S5: Archaea', 'A0A2R6H2H7: Archaea', 'A0A2R6LZL3: Archaea', 'A0A2R6N9Z3: Archaea', 'M0NET8: Archaea', 'M0MDP9: Archaea', 'A0A2R6EHW0: Archaea', 'A0A151AI36: Archaea', 'D8J4C6: Archaea', 'A0A830GGW9: Archaea', 'A0AAV3S8M2: Archaea', 'A0A830G7F1: Archaea', 'A0A830G1F5: Archaea', 'U3A921: Archaea', 'A0A830EVM0: Archaea', 'A0A7D5E5D8: Archaea', 'A0A830G6D7: Archaea', 'A0A830G1M4: Archaea', 'A0AAV3S8B5: Archaea', 'A0A7D5HVG8: Archaea', 'A0A830EVZ3: Archaea', 'A0AAV3T0D2: Archaea', 'U2

In [3]:
id = []
king = []

for a in together:
    b = a.split(':')[0]
    id.append(b)
    c = a.split(' ')[1]
    king.append(c)

In [4]:
df = pd.DataFrame()

In [5]:
df['id'] = id

In [6]:
df['kingdom'] = king

In [7]:
df = df.set_index('id')

In [8]:
df

             kingdom
id
A0A7I7U7Q2  Bacteria
A0A375YPN6  Bacteria
A0A0B4E6X7  Bacteria
V4RHR4      Bacteria
Q0G2T1      Bacteria
...              ...
A0A1X4GBG2  Bacteria
A0A2N6JV02  Bacteria
A0A2S0Q8P1  Bacteria
A0A166IS52  Bacteria
K9W4V5      Bacteria

[1531 rows x 1 columns]

In [11]:
fuseid = []

for record in SeqIO.parse('Amt-fuse.fasta','fasta'):
    a = record.id.split('|')[1]
    fuseid.append(a)

In [14]:
df['match'] = pd.Series(df.index.isin(fuseid), index=df.index).map({True: 'yes', False: ''})

print(df)

             kingdom match
id
A0A7I7U7Q2  Bacteria
A0A375YPN6  Bacteria
A0A0B4E6X7  Bacteria
V4RHR4      Bacteria
Q0G2T1      Bacteria
...              ...   ...
A0A1X4GBG2  Bacteria
A0A2N6JV02  Bacteria
A0A2S0Q8P1  Bacteria
A0A166IS52  Bacteria
K9W4V5      Bacteria

[1531 rows x 2 columns]

In [16]:
df.to_csv('annotations.csv')

             kingdom match
id
A0A7I7U7Q2  Bacteria
A0A375YPN6  Bacteria
A0A0B4E6X7  Bacteria
V4RHR4      Bacteria
Q0G2T1      Bacteria
...              ...   ...
A0A1X4GBG2  Bacteria
A0A2N6JV02  Bacteria
A0A2S0Q8P1  Bacteria
A0A166IS52  Bacteria
K9W4V5      Bacteria

[1531 rows x 2 columns]