In [1]:
import ete3
from ete3 import Tree
from ete3 import NodeStyle
from bioservices.uniprot import UniProt
from Bio import SeqIO
from tqdm import tqdm

In [2]:
from Bio import AlignIO

alignment = AlignIO.read("concatali.fasta", "fasta")

print("Number of rows: %i" % len(alignment))


for record in alignment:

    print("%s - %s" % (record.seq, record.id))

Number of rows: 1281
------------------------------------YSS-GDIA-----WVVTSTALVL-LMI-PGVGFFYS---------GLA-------R---------KSALSLIWLSIMSVGVVSFQ--------WFFWGYSL-------A-----------------------------------------------------------------SKV-PDLL----------FAVFQGMFACITVALAVGA-AAERG----- - A1D2Y5
----------------------------------S--LA-IDSL-----WVMLGAILVI-GMQ-VGFALLEA---------GST-----------------KQILSF--------AIASLA--------FWAAGFAI-------TF-------GK------------------------GNG-------L---------------------------P-------LELKFLFQLAFVGVSLAIAWGG-FAERAKL--- - M8E0R3
------------------------------MEEYT--SI-LFGV-----WFLIGAALVF-WMQ-AGFAMVEA---------II-----------------MKNLMDF--------CIGTVM--------FVLLGFGL-------MF-------GE---------------DTF-----------------------------------------FDWS----------NFVFNLVFCATTATIVSGA-MAERT----- - A0A2G3DSU6
------------------------------------MDS-GDTT-----WLLVSTALVM-LMT-PGVALFYG---------GMV-------R---------RNLVSTLMMSFGAMALGGVL--------WVLIGYSL-------GF-------GN------------------------------------------------------DTTV-PHLA----------FMMFQGMFAIISLALITGA-VVERIRF--- - A0A328EMN2
--------------------------------------K-GDNT-----WMLISTILVL-LMTIPGLALFYG---------GLV-------R---------KNMLSVLMQVFMITAVVMII--------WVTYGYSL-------AF-------T--------------------------------------------------------VAI-PELT----------FVCFQMTFACITPALIVGA-FAERIKF--- - A0A6A1TYJ4
-------------------------------------DT-GDTA-----WMLTATALVL-FMTIPGLSLFYA---------GLV-------R---------KNVLSVLMQCFAITAMMSLL--------WAIYGYSL-------AY-------T---------------------------------------------------------TI-PESV----------YMTFQMTFAIITPALIVGA-FAERMKF--- - D3RMV7
-------------------------------------DS-GDTA-----WMLTSSVLVL-MMTVPGLALYYG---------GLL-------R---------KNILAMLMQCFFATALISVL--------WVVIGYSL-------AF-------TKG----------------N------G---------------------------TLSGTI-PETV----------FCMFQCTFAIITPVLILGG-PAD------- - F0J3F9
-------------------------------------NK-GDTA-----WLLVSTAFVI-LMTLPGLALFYG---------GLV-------R---------KNMLSVLMQCTGIFSLVMIL--------WAIYGYSI-------A-----------------------------------------------------------------VVV-PEYA----------YFAFQGAFAAITCALIIGA-FAERAKF--- - G2ZN72
-------------------------------------NS-GDTA-----WMLMATALVL-LMT-PGLAYFYG---------GMV-------N---------NNVISTMLQSFVAMGVISII--------WVVCGFSL-------AF-------GDS---------------IG------L-D---------GKP------------WSLAATI-PLAV----------FAFFQLKFAVITPALITGS-MA-------- - I0KDC6
-------------------------------------YA-LDTF-----YFLMSGALVM-WMA-AGFAMLEA---------GLV-------R-SKNTEILTKNIALF--------AIACTM--------YLLCGYAI-------MY-------PGT-----------------------N----------------------------------SLRS----------DFFFQVVFVATAMSIVSGA-VAERMKL--- - A0A081N2G5
------------------------------------------NA-----FMMISTALVL-FMSIPGIALFYG---------GLI-------R---------GKNVSMLTQVAVTFALVCVL--------WVVYGYSL-------AF-------GTG----------------N------AFF---------G-----------NFDWALMGSF-YQYI----------HVAFQGSFACITVGLIVGA-LAERIRF--- - A0A144NLT9
--------------------------------------S-GDNA-----WMLTSAALVL-MMTGPGLALFYG---------GLV-------R---------TKNVATMMQSFFLISMISLL--------WFLFGYGA-------AF-------GKG-----------------------------------------------------NAFI-PAQT----------FMVYQMMFAIITPGLITGA-FAERMRF--- - B4D7W2
------------------------------------------VS-----WMMVATTLVL-FMTIPGIALFYA---------GMV-------R-KKVR---KKNVLSVVMQSFAICCSITIV--------WYVCGYSL--------------------------------------------------------------------------SI-PEML----------FMMFQMTFAILTPALMCGA-FAERMKF--- - F3QNA7
-------------------------------------QS-GDQA-----YIIVASAMVM-VMI-PGLGFLYS---------GLA-------R---------KSALSMIWACMASFSVVTFQ--------WYFWGYSL-------A-----------------------------------------------------------------PLI-PNLL----------YAFYQMQFCGVTAAIIMGA-VAERGR---- - Q4WHC6
--------------------------------FYFRYPSFQDVH----------------VMIFVGFGFLMT-FLKRY---SFLK------R------------------------------YS-----FGAVGFNFLIA----AF----------------------GLQWALLM--QGWFS----------------------------GI---------------ENLINADFCVASCLIAYGA-VLGKVSPVQL - Q8JI14
--------------------------------------M-DMSV-----WFLMGAALVF-FMQ-CGFAMVEA---------GFT-------R-AKNVNITMKNLMDF--------CIGTVA--------FYLLGYNL-------LC-------GD---------------GKF--------------------------------------GE-TDWS----------AFVFNLVFCATAATIVSGA-MAERT----- - A0A395VB65
-------------------------------------NT-GDTA-----WIIVSTALVM-MMTPAGLALFYG---------GMS-------R---------KNLLNTYAMTLVSYCLGSIV--------WVMWGYTL-------A-----------------------------------------------------------------GTI-PSFV----------FIVFQMTFAGITVALILGA-IVDRMKF--- - A0A975GIX9
-------------------------------------EG-VNLL-----WVLTVSFLIF-FMH-AGFAMLEA---------GQV-----------------KNLLTW--------SVGVVV--------FFLIGSGI-------SS-------LV------------------------GT----------GSFAPAFG-----------EAA-NDYVG----------WLFGAVFAMTAATIVSGA-VAGRAKLR-- - Q5UZ98
------------------------------------ADK-ADNA-----FMMICTVLVL-FMTIPGIALFYG---------GLL-------R---------KNVLSLMVQVMVSFALVCVL--------WVIYGYSL-------AF-------E-----------------------------------------------------NLSGNF-YQLI----------HVAFQGSFACITVALIIGA-LGE------- - A0A4R4K1P9
-------------------------------------NT-GDNA-----WQLTAATVVG-LQSVPGLVVLYA---------GIVK----------------KWAINSAFMAFYAFAAVLIA--------WVLWAYNM-------GF-------G------------------------------------------------------------PMST----------MVYFQFVFAAITLIIMAGA-FLGRMSF--- - A0A7T4WEP4
---------------------------------VS--GE-VFAV-----WFLIGAALVF-WMQ-AGFAMVEA---------GF-----------------TKNLMDF--------CIGTVV--------FIVIGFGL-------LL-------GE---------------DVA------GLI---------G------------------KPG-FDWS----------NFVFNLVFCATTATIVSGA-MAERT----- - C6LBD3
-------------------------------------YV-IDTF-----FALFAMTLII-FMV-PGFAMLEA---------GLV-------T-KNVSAVLMVNTMIY--------AVASLA--------FLLVGYSV-------AF-------GD-----------F------------G------------------------------DSM-SKWA----------AFLFQMAFVGKVINIMSGG-VSE------- - D5V7B3
--------------------------------------A-ADTA-----WVLAAMVAVA-LMV-PGLALFYG---------GMVS----------------RSTLNMMMMTIGAVAVMAVL--------WVVVGYSL-------TF-------GDS------------------------------------------------------PGL-PPAL----------FAGFLLLFAGITVALVAGG-VAD------- - A0A4R3ZNW3
------------------------------------LSA-GDTA-----WMLTSTMLVI-LMVIPGLALFYG---------GLV-------R---------KNMLSVLCQVFVIFSLITLL--------WAVYGYSL-------AF-------A--------------------------------------------------------PTI-PEYV----------FVAFQSTFAAITVALIVGA-FAERIKF--- - A9BQZ4
----------------------------------------LNTV-----WMLLAAMLVF-FMQ-PGFALVEA---------GF-----------------TRVKNTF--------MFGSLL--------YWFIGFGL-------MF-------G-----------------IG------GFI---------GTPH-------FFLPS---------EG----------FLVFQTVFCATAATIVSGA-MAERTKF--- - A0A642KQG8
--------------------------------------S-IDTM-----WTLLAAFLVF-FMQ-AGFALVEA---------GF-----------------TKNFTDF--------LVGSIL--------YWLVGFTI-------MF-------GV---------------GNGF----IGWQ---------GSFY-------LGLNIPL-------NA----------FLIFQTVFAATAATIVSGA-MAE------- - A9BIZ7
-------------------------------------SH-ADYV-----WTLVAAMLVF-FMQ-AGFAMVET---------GF-----------------TRAKNAF--------SMGSIV--------YWAVGFGL-------MF-------GV---------------SET------GCF---------GTSG-------FFLSDFKVEDP-WVLV----------FWMFQAVFAATAATIVSGA-MAE------- - K0NJH2
-------------------------------------VG-LDTI-----WVMIAAFLVF-FMN-LGFALVESGFCRKNTVNIL-----------------FKNFVVF--------AISSLA--------FLVIGYGL-------MF-------G-----------------DG------N----------------------------------PLWA----------KFFFQLVFAGTAATIVSGA-VAERIKF--- - Q2IK04
-------------------------------------DD-MGML-----WMLIAGILVF-FMQ-AGFFLVES---------GM-----------------TKNFLDI--------AVGSLA--------FWFIGYSL-------MY-------GA---------------DVTE----GGF---------------------------------QGPA----------DLFFQTVFAATTATIVSGA-IAGRTKYT-- - T2KJ59
-----------------------------------IVDK-ADNG-----FMMICTALVL-FMSVPGIALFYG---------GLL-------R---------KNVLSMLSQVLVIFSLIAVL--------WITYGYSL-------SF-------G--------------------------------------------------------GSI-YEFI----------WVAFQGSFACITCCLIPGA-FAERIRF--- - A0A1B9M5B8
-------------------------------------NK-GDNA-----WMMTSTVLVL-LMTIPGLALFYG---------GLV-------R---------KNMLSVLAQVFYTVCVACII--------WALYGYSL-------A-----------------------------------------------------------------ANI-TELI----------FVCFQMTFCAITPALIVGA-FAERTRF--- - A0A323UE08
-----------------------------------------HTS-----WIIVSTALVL-LMTLPGLALFYG---------GMV-------R-KKVR---KKNVLATMAQSVAAAVVVSVL--------WIVAGYSL-----------------------------------S------P-------------------------------QL-PEFL----------WIAYQMTFAIITPALIAGA-FAERLKF--- - E8RLT5
-------------------------------------NK-GDTA-----WLLVSTAFVI-LMTLPGLALFYG---------GLV-------R---------KNMLSILMQCTGIFSLVMIL--------WAVYGYSI-------A-----------------------------------------------------------------VVV-PEYA----------YFAFQGAFAAITCALIIGA-FAERAKF--- - F6G5I9
-------------------------------------NK-GDTA-----WLLVSTAFVI-LMTLPGLALFYG---------GLV-------R---------KNMLSVLMQCTGIFSLVMIL--------WAIYGYSI-------A-----------------------------------------------------------------VVV-PEYA----------YFAFQGAFAAITCALIIGA-FAERAKF--- - G3A431
----------------------------------T--AG-LNSV-----FVFLAALLVF-FMQ-AGFALLEA---------GSV-------R-MKNAHVAGKTFLTF--------GISIVA--------FWAFGFGL-------AF-------GN------------------------GN---------------------------------SDVP-------TTIMFLFHLSFAAVSLAIACGG-MAERAKL--- - G4H971
--------------------------------------SHGDNA-----WILASTALVV-MMTIPGLALFYG---------GLA-------Q-A-------PNIMCT----------VSFL--------WFSFGYSLC-FTAGDVF------YGNSSNFW-----------LN------D----------------------------------SEKL----------FMVYQMTFAVISAAIICGS-FAERMRF--- - L1J6I4
----------------------------------A--QG-VNYV-----WILVVSFLIF-FMQ-PGFALLEA---------GQV-----------------KNMTDW--------ALGVLV--------YFVVGAGV-------AT-------IV------------------------GGLT--------SPGG--FG------------DS-GAWID----------WLFGAVFAMTAATIVSGA-VAERMDF--- - M0J579
------------------------------------------NA-----FMMICTALVL-FMTIPGIGLFYG---------GLL-------R---------SKNVSLMTQVMVTFAAICVL--------WIVYGYSL-------AF-------GSG----------------N------AIF---------G-----------NLDEDLTGSF-YKMI----------HVAFQGSFACITVGLIVGS-FAE------- - A0A377PBY1
-------------------------------------DT-GDTA-----WMLVSTALVL-MMTIPGLALFYA---------GMV-------R---------KNVLATLMQSFALCCIISIV--------WMVAGYSL-------AF-------TTG----------------S--------------------------------------TI-PESI----------FMMFQMTFAIITPALISGA-YAERMKF--- - A0A401WUW1
-------------------------------------SA-GDSA-----WVLTSSALVL-MMTIPGLALFYG---------GMV-------R---------VNVLSTVMQSFSIVCLITVL--------WMCFGYSL-------SF-------TT--------------------------------------------------------GI-PEPL----------FMVYELMFAIITPALICGA-FADRMRF--- - L1IYW7
----------------------------------------GNAA-----WILTSACLVF-LMT-PGVALFYG---------GMV-------R-AMVR---AKAVLNMLIMEAAALSVTMII--------WGLWGWSI-------A---------------------------------------------------------------------PASV----------DVAFQAAFAMITVALICGA-IAERVKY--- - A0A315S845
--------------------------------------G-ADAL-----FILLGAIMIL-AMH-AGFAFLEL---------GTV-------R-KNQVNALVKILADF--------AVSTIV--------YFFIGYYV-------AY-------GV------------------------SFK-----------------------------SG-FELVK----------FFFLLTFAAAIPAIISGG-IAER------ - A0A6M3ZKU5
-----------------------------------VANG-ADNA-----FMMICTALVL-FMTVPGVALFYG---------GLL-------R---------KNVLSMLTQVIVTFALVCVL--------WMLYGYSL-------A-----------------------------------------------------------------GTF-SQLI----------HVAFQCSFACITVALVVGG-LAERVRF--- - A0A502GPV4
-------------------------------------YA-MDTF-----YFLVCGALVM-WMA-AGFSMLEA---------GLV-------R-SKNTEILTKNIALF--------AISCLM--------YLVCGYAI-------MY-------GGD-----------------------Y----------------------------------SGAS----------DFFFQVVFVATAMSIVSGA-VAERMK---- - A0A9J9BAE8
-------------------------------------NG-ADTA-----WIMTSTALVL-FMTLPGLALFYG---------GLV-------R---------KNILSILMQCFAIAGIISIL--------WFVVGYSI-------AF-------SGD----------------N--------------------------------------SI-PESL----------FAVFQMTFAIITPALIIGS-YAERMKF--- - A1AVV2
----------------------------------------MNEL-INLAWVGICTALVF-FMQ-AGFALVEG---------GLA-------R-AKNSNVIMKIYLGT--------CFIGVG--------FWLVGYGV-------AF-------GPSV-------------TQAM------------------------------------------------------SLLYQMMFATTAVTIVSGA-VAERMRY--- - B1XZU2
--------------------------------------P-ADVL-----FVLLGAIMVL-AMH-AGFAFLEV---------GTV-------R-KNQVNALVKIISDF--------AMSSIA--------YFIVGYSL-------AY-------GS------------------------DFD-----------------------------SG-YELVK----------FFFLLTFAAAIPAIISGG-IAER------ - Q5P1S8
--------------------------------------A-GDTA-----WVMLSTILVL-FMTIPGLALFYA---------GMV-------R---------KNILSVMVQSFAACSLIAVI--------WFVCGYSL-------AF-------TPN----------------N--------------------------------------TI-PESV----------FMLFQMAFAIIAGAIMTGA-FAERMKF--- - A0A0F5EZP7
-------------------------------------------------FMMICTALVL-FMTVPGVALFYG---------GLL-------R-SKNR---SKNVLSMLTQVIVTFALVCVL--------WILYGYSL-------A-----------------------------------------------------------------GTF-SQMI----------HVAFQCSFACITVALIVGG-IAERVRF--- - A0A4R7GKA0
------------------------------------MDQ-GNTA-----FLLIAAALVL-LMT-PGLAFFYG---------GLV-------R---------KSVISMMMLSFGAMGLIGVL--------WVLYGYAI-------AF-------GNL---------------G-----------------------------------EQTAAY-PTIA----------FAAFQATFAIITVALISGA-IA-------- - A0A2T4UWF1
----------------------------------A--YS-LNTF-----YLLVSGALVM-WMA-AGFTMLES--------------------------ILTKNIGLY--------SIACLM--------YMLVGYQI-------MY-------GGS-----------------------D----------------------------------ANLS----------DFFFQVVFVATAMSIVSGA-VAERMK---- - A0A3E0X011
------------------------------AESNA--IA-IDTI-----WTLLAAFLVF-FMQ-AGFAMVEA---------GF-----------------TKNLMDF--------SVGSLI--------YWICGFAF-------MF-------GA---------------GNA-------FI---------GSKG-------FGLDIPL-------SA----------FWIFQAVFAATAATIVSGA-MAE------- - A0A4R8H081
----------------------------------M--NN-VDML-----WIIISASLVF-LMQ-PGFMCLES---------G-----------------MTKNFADF--------VLSAGV--------FWLLGFGL-------MF-------GD--------------ISWE------YFR---------AAT---------GF----------KAA----------FFFFQVMFCGTATTIFSGA-VAERMRF--- - C7LQR9
-------------------------------------FL-ANNL-----WLLIATILVI-FMN-AGFAMVEAGMCRKNAVNIL-----------------AKNLFVF--------ALAVTS--------YWFIGYSL-------M-------------------------------------------------------------------V-P-TV----------DFLFQSAFAGTAATIVSGL-VAERVKFG-- - A0A0A2A0Y9
-------------------------------------FL-ANNL-----WLLIATILVI-FMN-AGFAMVEAGMCRKNAVNIL-----------------AKNLFVF--------ALAVTA--------YWVIGYKL-------M-------------------------------------------------------------------V-P-TV----------DFLFQSAFAGTAATIVSGL-VAERVKFG-- - A0A0A2A5X1
---------------------------------TP--PG-GNVF-----FLLMGAILVF-AMH-GGFAFLEL---------GTV-----------------KILSDF--------GISTMV--------YFFVGYHI-------AY-------GI------------------------SFF----------------------------GDV-FEMVR----------FFFLLTFAAAVPAIISGG-IAERARF--- - A0A7T5BFQ2
------------------------------------IDT-GDTA-----WMIVASAFVL-LMT-PGLAFFYG---------GLV-------N---------RKNVSTMLQSFVALGVMSVL--------WVFIGFSL-------AF-------GES---------------YH----------------------------------DFSSTI-PFLL----------FALFQLKFAIIAPALITGS-FA-------- - A3U857
--------------------------------------A-LDTF-----YFLVCGALVM-WMA-AGFSMLEA---------GLV-------R-SKNTEILTKNIALF--------AIACTM--------YLLVGYYL-------MY-------SSS-----------------------A----------------------------------SARA----------DFFFQVVFVATAMSIVSGA-VAERMK---- - E1V4T3
-------------------------------------NT-GDNA-----WQLTAATVVG-LQSVPGLVVMYA---------GIVK----------------KWAINSAFMAFYAFAAVLIA--------WLLWAYNM-------GF-------G------------------------------------------------------------PMST----------MVYFQFVFAAITLIIMAGA-FIGRMNF--- - F0J7D3
-------------------------------------LT-TNNV-----WMMLCTAMVF-IMH-LGFAGVET---------GFG-----------------KNTVTP--------IIGIAT--------YALIGFFL-------MY------PGFESP---------------------GW---------------------------------TYWT----------DFLFQAMFAATCATIVSGA-IAERVKL--- - M7XJ51
------------------------------VSEMT--YI-LNTF-----SFLISGVLVM-WMA-AGFAMLEA---------GVR-------S-KNVATICLKNIALF--------GVAGIL--------FYLIGYNL-------M---------------------------------------------------------------------SAGS----------DWFFQMVFCGAACSVVSGC-VAERIKL--- - Q1K0H9
------------------------------------MDQ-GNTA-----FILFAAALVL-LMT-PGLAFFYG---------GLV-------K---------KSVISMMMMSFGAIGLIGVL--------WVLYGYSI-------AF-------PAA---------------D----------------------------------VPEDAAY-PPLA----------FAAFQATFAIITVALVSGA-IAD------- - A0A2S5XAB8
------------------------------------IDK-ADNA-----FIMICTALVL-FMTIPGIALFYG---------GLI-------R---------KNVLSMMTQVTVAFAMVCIL--------WVVYGYSL-------A---------------------------------------------------------------------YQFV----------HVAYQASFACITVALIVGA-IAERIRF--- - A0A366IE34
-------------------------------------QS-SDTL-----FILLGAIMVL-AMH-AGFAFLEV---------GTV-------R-QNQVNALVKIIADF--------GFSAIA--------YFFIGYWV-------AY-------DV------------------------TFI-----------------------------NG-YELVK----------FFFLMTFAAAIPAIISGG-VAERA----- - Q1Z695
--------------------------------------K-GDNT-----WMLVSSALVL-LMTIPGLALFYG---------GLV-------R---------KNMLSVLMQVFMITAVVALI--------WVTYGYSL-------AF-------T--------------------------------------------------------VAI-PEYT----------FIVFQMTFACITPGLIVGA-FAERVKF--- - A0A8G2IZM3
-------------------------------------NK-GDTA-----WMIVATVLVI-LMVIPGLALFYG---------GMV-------R---------KNMLSMLMQVFVIFSMMAIL--------WAIYGYSI-------A-----------------------------------------------------------------VYV-PEYI----------YVAFQLTFAAITPALIVGA-FAERVKF--- - G3IYW2
------------------------------------ING-SDTS-----WILVSAALVF-IMS-PGVGYFYS---------GMA-------R---------KNAVSMVFLCMIAMSVVSVQ--------WMIWGYSL-------A------------------------------------------------------------------TI-PGSV----------YAIFQCMFAALTPALAIGG-AAERI----- - A0A2G5BGA9
-----------------------------------MFDK-GLTA-----FMIIATSLVM-LMT-PGLAFFYG---------GLSC------K----------NILSIMMQSFVSLGITSLL--------WISIGYTM-------C-----------------------------------------------------------------RNF-PEFI----------FIAYQMMFAIITPALITGA-FINRVTF--- - A0A5M4AUM9
------------------------------------MDK-ADIS-----WLLVSTLLVL-MMAVPGLAMFYG---------GLV-------R---------KNVLSVLLQVLCTFVLGLVL--------WFIYGYSL-------A-----------------------------------------------------------------NSL-TELL----------FASFQATFAGITCALIVGS-FAERARF--- - E3HJW8
-------------------------------------SG-VNNV-----WILVVCFLIF-FMQ-PGFALLEA---------GQV-----------------KNMTDW--------TLGVLV--------FFIIGAGV-------SS-------LV------------------------GMLT--------APGA-AVS------------DP-SAYIG----------WFFGAVFAMTAATIVSGA-VAGRMNF--- - U1PIR6
-------------------------------------DK-ADNG-----FMMICTALVL-FMSVPGIALFYG---------GLL-------R---------KNVLSMLTQVLVTFSLIAVL--------WIVYGYSL-------AF-------G--------------------------------------------------------GSI-YELI----------WIAFQGSFACITCCLILGA-FAERIRF--- - A0A1B9N3H7
------------------------------------MDQ-GNTA-----FILFAAALVL-LMT-PGLAFFYG---------GLV-------K---------KSVISMMMMSFGAIGLIGVL--------WVLYGYSI-------AF-------PAA---------------D----------------------------------VPEDAAY-PPLA----------FAAFQATFAIITVALVSGA-IAD------- - A0A2S5WV24
----------------------------------E--SN-LDVL-----WLLFGAYLVF-FMQ-CGFALLEA---------GSV-------R-KNTKNILLKNVLDA--------CLGGLI--------WWTIGFPI-------AS-------S----------------------------------------------------------S-TYYA----------MWLFQWAFAATSATIVSGA-VAERCAF--- - A0A6U2BIY7
-------------------------------------IG-LDTV-----WVLIAGILVF-WMN-AGFALVESGFNRKNTVNIL-----------------AKNFVVF--------GIATLS--------FWIIGWGL-------MF-------G-----------------DG------N----------------------------------PLWA----------KFFFQLVFAGTAATIVSGA-VAERIKF--- - A0A833LX85

In [3]:
print(alignment[:, 241])

AATAAAVAASGGAALTATAITNAATTTTTCAAAAAATGAAAAASATAAAASTTTTAASITSAAAGAAAATCATTSAATAATAATAAATAAAALTASTAGGTSSAAAAATTAAATTTACGAATGAMTTTAAAGAAACIATAAAATATATAATSMCVAAAGTAAATATAAATSAGATTAGAAATSASAAATASAGAASTSASATAAAAAALATAACAAAAAAGSACATATAAGATTAAATTTTTASASATATGSAAAGSAAATATGGGTTAAAATATATAAAAAATAASAAAIAATTSAAA-TAAVATTAAAALTTAAAAAATAATGTSTLMSGCSTATTAAAAGATGATVTAATAATAAATTAAASSAAAVASAAATGTAISTATASATASTAASAIMTTTTTALAAAAATISSAATAAGAATTTGLAGAAASGAATTAIAATCAATAATIAAAAAATAAATATTSASIITVATAAACAAALTALSATPTTAGTVSAAGILAAAAATAASSTATTAAATTAAAAATAATVATA-ATTAASGCAATAAAAAAATATCATAAAAASLATATTIAAAAAAAATAAMAAATCGAAAACTAATATTAAASAGAAATAAAAAGATTAAGATIALAGAAAAATAAATASTAAATTAAATATAAAASATISAATITAGGTTS-ATATSTATATAIAAAAAGATALACAATAATTAAAAVTAAATAACSATGSAAASSTAAITAATLATAGGASCTATTTTTCAATGTAAAAATAAAAAALTSAAAAAASTATAAAASAMSSASAAATGAAATSAAMITAAAAAGAAAAAATAGCASTAATTATAATAATCAAGAAAAALITCTATGAVGAAATAAGAATAAATAAASAAAAAA-ATIAAAATSTTAAVATA-ATTAAAATATTYTAACATSTMATTAAATAAAASAATAAATAAAAAATAAAAAAAAILAALTATTVACSTSAAAALSAAGALLAAATAATAGATATAAASTSAAASASATAVTSSATAATATAAATAAAAASSAAAAAIAAASASTVAVTATTGTAAISIAAGALSTTATTTGAAAAGTASTAAASSMSAAGTSAACTGTTAASASASSCAGASMAAITTAASTTLAAAATATTAGSAAATAAVAATATATAAAAIALSMSAAAATAAAAATTAGAATATVAAAASATTALATGSASTTATAAAASTSATTAGTTATATTTGAAAATTSAAAGATAAATGTTATGAGAAAAAATALTAAAAAAAAAATAAASTATCLAG

In [4]:
seventyone = alignment[:, 70:71]

In [5]:
sevenone = []
seqseq = []
idid = []


for i in seventyone:
    print(i.id, i.seq)
    sevenone.append(f"{i.id} {i.seq}")
    idid.append(i.id)
    seqseq.append(i.seq)

A1D2Y5 Y
M8E0R3 E
A0A2G3DSU6 E
A0A328EMN2 Y
A0A6A1TYJ4 Y
D3RMV7 Y
F0J3F9 Y
G2ZN72 Y
I0KDC6 Y
A0A081N2G5 E
A0A144NLT9 Y
B4D7W2 Y
F3QNA7 Y
Q4WHC6 Y
Q8JI14 M
A0A395VB65 E
A0A975GIX9 Y
Q5UZ98 E
A0A4R4K1P9 Y
A0A7T4WEP4 Y
C6LBD3 E
D5V7B3 E
A0A4R3ZNW3 Y
A9BQZ4 Y
A0A642KQG8 E
A9BIZ7 E
K0NJH2 E
Q2IK04 E
T2KJ59 E
A0A1B9M5B8 Y
A0A323UE08 Y
E8RLT5 Y
F6G5I9 Y
G3A431 Y
G4H971 E
L1J6I4 Y
M0J579 E
A0A377PBY1 Y
A0A401WUW1 Y
L1IYW7 Y
A0A315S845 Y
A0A6M3ZKU5 E
A0A502GPV4 Y
A0A9J9BAE8 E
A1AVV2 Y
B1XZU2 E
Q5P1S8 E
A0A0F5EZP7 Y
A0A4R7GKA0 Y
A0A2T4UWF1 Y
A0A3E0X011 E
A0A4R8H081 E
C7LQR9 E
A0A0A2A0Y9 E
A0A0A2A5X1 E
A0A7T5BFQ2 E
A3U857 Y
E1V4T3 E
F0J7D3 Y
M7XJ51 E
Q1K0H9 E
A0A2S5XAB8 Y
A0A366IE34 Y
Q1Z695 E
A0A8G2IZM3 Y
G3IYW2 Y
A0A2G5BGA9 Y
A0A5M4AUM9 Y
E3HJW8 Y
U1PIR6 E
A0A1B9N3H7 Y
A0A2S5WV24 Y
A0A6U2BIY7 E
A0A833LX85 E
I9P003 E
K8VZC6 Y
L1IUV5 Y
A0A0K2STQ7 E
A0A2H1HV86 Y
Q2GX26 Y
A0A074KY88 E
A0A858ZNJ3 Y
A0A3P2A7W8 Y
A0A7S4GND2 E
O26757 -
Q46G49 Y
A0A140NHJ5 Y
A0A2S8GF54 E
B1JZ69 Y
E5Y678 Y
A0A149U2G9 Y
A0A9Q5QVI9 Y
Q18PF5 M
A0A317FZW2 E
G5EB13 Y
Q1YDY8 E
A0A1X4GBG2 E
A0A4Q7Y9I7 Y
I0HKQ8 Y
A0A097R891 Y
A0A7S4GMD8 C
Q488X2 E
U3PCH5 S
A0A378YR15 Y
I1YG38 E
F5XN43 Y
Q1IWN6 Y
A0A1E3PSK5 Y
A0A833H2R7 E
A0A2T0XPP2 E
A0A399T909 Y
L8GGA0 Y
A0A0D8BQX6 E
A0A1M5ZVP9 E
I5BYV5 E
A0A0K2STH0 E
A0A2N6K4Y5 Y
A0A1B9JZS5 Y
A0A2W0GQV0 Y
A0A369MHK2 Y
A0A087L0B9 Y
A0A0A2AMW2 E
A0A377PLP5 Y
Q6BJI7 Y
Q7S5K0 Y
Q7Z1M1 E
T2JFS5 E
W0JIB3 E
A0A1V2XMU9 Y
A0A2S6GKN5 Y
A0A7G5DK18 Y
A0A830ZZN8 Y
A0A8B4RWH8 Y
A0A9Q6P4A5 Y
B8ENL9 Y
Q9QXP0 M
A0A060URC3 Y
A0A2W5HTC3 Y
A7S731 E
A0A1Y0UZX2 Y
A0A257TE48 E
Q2RVB5 Y
Q605Y6 Y
A0A918MJ52 E
K6W5X0 Y
V4AP67 E
A0A7Z0V0A4 Y
C0GKN4 E
A9HMD6 Y
B1ZSW9 Y
K5DBA0 E
V4REY8 E
A0A0D2KGN8 Y
A0A242NIL1 Y
A8PXT8 Y
B7X047 Y
D2ZRW2 Y
H1Y7T6 Y
Q97L80 Y
A0A0S6UHP2 E
A0A323UDG5 Y
E3I393 Y
A0A4V2X6C2 Y
D7G265 E
A6LRS5 Y
D8J4C6 E
F2NGJ8 Y
A0A0E9NHV4 Y
A1CQ21 Y
A0A6N2Z556 E
Q0BWD0 E
A0A071MMV1 Y
A0A168EVK8 Y
B3DUX7 Y
F5L8M7 E
G7WJN0 E
Q0BQ69 Y
A0A3N2SFS2 Y
A0A9Y2AG30 Y
A0AA46Q839 Y
E8RSE4 Y
F6BEI0 E
I1DSU5 E
I4C9L2 Y
Q5QVH2 E
A0A068NPW2 Y
A0A6J5IRX5 Y
A0A3R9Q7C4 Y
A3ZT81 E
K0ER80 Y
Q0VLH1 E
Q2KZK9 Y
R9GM11 Y
A0A0T7GZ59 Y
A0A1G5PWV0 Y
S5ABR8 E
W7QGM4 E
F5Y3C1 Y
I8TC71 Y
M1P5F0 E
A0A149RYW7 Y
A0A1J1JH03 E
A0A1U9Z147 Y
A0A243SC06 Y
A0A3G9G2C9 Y
I4C9L0 Y
I4D1H5 Y
Q7W7D3 Y
A0A0B4M163 M
A0A1M7UEG2 Y
A7HT14 E
C8X554 Y
A0A127PIQ9 Y
A0A1B9JPL5 Y
W5WIX6 Y
A0AA40J491 Y
D8PD01 Y
A0A251XU71 Y
A0A2N6P374 Y
B3QVV5 Y
K1K628 Y
A0A1E2SKM1 S
A0A1I0BYN1 Y
A0A556RTU3 Y
A0A829X098 Y
D5EP68 -
F0J6E8 Y
A0A073CP02 E
A0A127JTU2 Y
C7BJG7 Y
D2BUJ8 Y
B8IZX4 Y
I3R0S7 E
A0A3E2TW06 E
B1Y0E5 Y
E6ME92 Y
A0A251Y3N4 Y
A0A380S5X4 E
F0YLV7 E
F8D7H6 E
Q31CR9 E
W0E077 E
A5DYQ2 Y
A8LKQ0 E
A0A4Y1MSE7 Y
A3TVQ9 E
F2B2B8 Y
L0K9M1 E
Q4WT12 Y
Q8ERT9 E
A0A1H3WA00 Y
A0A1U9YY82 E
A1DG05 Y
B8GGC1 Y
F3ZVV4 Y
P69680 Y
Q0G2T1 E
A0A3T0SZ22 Y
A0A4R2Z2K6 Y
L1IYP4 Y
Q46HB1 E
A0A149QAW7 Y
A0A1Y4L5P0 E
A0A6B8N021 Y
D5EP71 Y
V5U2Z4 Y
A0A0E3QYF3 E
A0A0K2STK6 E
A0A8H7U3I1 Y
A0A062IU58 Y
A0A178TA08 E
A0A3G9G4Q4 Y
A0A6H9FPY5 E
A1C5Z7 Y
A0A0A1ZJU5 E
A0A258HPP1 Y
G0H0Z6 E
A0A2Z4MD56 E
G0EFF3 Y
E2SD33 Y
E4TJ50 Y
A0A016XCG9 Y
A0A2S5Y0D3 Y
K9YN27 E
Q3AFY9 Y
Q7N0M6 Y
W8KM07 E
A0A0G9HEC5 Y
A5UJR1 Y
A0A9Q9D9I3 Y
B9SXC7 Y
C0QTA4 Y
A0A176XNC5 Y
A0A317G0I6 E
A0A2S5CTX8 E
U2EN72 E
A0A248LNW8 E
A0A4P8HC89 Y
G7UUY6 Y
A0A0E3WZH5 E
A0A165K0X5 E
D3FBG3 Y
Q608B6 E
A0A854Q6X9 Y
H2IZ00 Y
A0A4V0XUI3 E
A0A7S4GNJ2 E
A0A2S5WX34 Y
C1D6X6 Y
A0A418VIJ8 Y
A0A857DMN9 Y
Q7T3R4 M
R1D1H4 E
T2J0N1 E
A0A419AVL2 Y
K0K7J4 Y
A0A4U1K1W1 Y
A0A9R0NTP8 Y
B0RC35 Y
C8XB51 Y
E4NS62 E
R9PMC6 E
A0A1R1IDV3 Y
A0A2N6JV02 E
A7MFK3 Y
B0BZN3 E
F7ZEU9 E
K9P718 E
Q82X47 M
Q8RUE9 M
A0A0M2LU39 Y
A0A3N1VXY4 Y
A0A370FPU0 Y
A0A7G5DPV1 E
A9UR54 E
F0S0G1 Y
K9W4V5 E
A0A015YIP3 E
A0A291PMC6 Y
G8R7U9 Y
U1H1F7 Y
A0A021VMC6 Y
A0A855F5Y8 Y
A0A2W5VAZ2 Y
M0MDP9 E
A0A1X3RP39 Y
A0A653N397 Y
A0A8G2F718 E
F4B548 Y
I0ICG0 E
A0A009TDB1 Y
A0A1G7DX68 Y
E4YA63 E
Q2W5V2 E
Q3AP28 Y
Q9BLG3 E
A0A0D5YN10 Y
A0A0L0S493 Y
H1YCC3 Y
L8JUH3 E
A0A0E3SHQ9 E
A0A366XFS8 Y
E6VIW4 Y
F6FRU9 Y
A1VIM5 Y
E0TGP9 E
A0A0E3SP24 Y
A0A8H6NAG3 Y
B8FGW0 Y
C3X1J1 Y
D9SI36 E
E0TCV4 E
E4U5Z1 Y
A0A094W9G3 E
A0A7G5EC77 Y
A0A482TED1 E
A0A4Q2QWS1 Y
A3PAY4 E
A0A173R3W6 Y
A0A1B9BUU6 Y
A0A495D4X4 E
A0A833GZR2 E
D0L8H3 Y
F4XTK4 E
I4D6Z7 Y
L8H844 E
A0A0S6UEK9 Y
A0A1M6ZMI3 E
U1SIR9 Y
A0A066ZTE4 E
A9DQM8 E
A0A0A0D6K5 Y
D6E7B3 Y
A0A562USB9 E
C7LW87 Y
G0JRG6 Y
A0A1X6N3Q5 Y
A0A1Y4LM49 E
B7FSA7 C
E1QIU3 E
H2CDR5 E
Q1K433 E
Q1QS12 Y
Q7T070 M
A0A0H3DR67 Y
A5CRL2 Y
A0A836M2B6 Y
E6SF19 Y
I2GD40 Y
Q18ES8 E
A0A060UWC8 Y
A0A0U1NJW3 E
A0A7R6PER3 E
A4G1J2 Y
A9AUR8 Y
C1N5A7 C
D3S2L0 Y
F8IJE0 Y
A0A0D2LEF5 Y
A0A1H1MB73 Y
W7QGE0 Y
G2T1Y3 E
L7CG99 E
A0A1I0C958 E
A0KPE9 Y
A9V5W4 M
F5RGM7 Y
A0A1C6Z081 Y
A0A1D3GAE9 Y
A0A410JZR4 Y
A8N2H6 Y
I1YJH7 E
A0A2G5BI87 Y
A0A2N6NEK4 Y
A0A1Y0HX98 Y
C3YB74 E
Q1H0G2 E
Q2FQT3 Y
S0APH6 Y
A0A075WEB4 Y
A0A172RYW3 Y
I3C0V3 E
A0A556SRH6 Y
A0A7U4DN04 Y
A0A1V3SSW1 E
Q466Y3 E
A0A0A2ZRL7 Y
A0A0H3LUA3 Y
A4G0C5 E
A5E3X2 Y
A8P923 Y
B8EMQ8 Y
D0MFE9 Y
A0A060HFT5 Y
A0A060JMP6 Y
A0A8E2UDJ3 Y
I4D6Z9 E
Q13E03 Y
Q1JXS5 Y
A0A076PL76 Y
A0A6N2TIA4 E
Q1AUG3 E
A0A098S5Y7 E
A0A7S4GNF3 E
A0A5J6WQU1 E
A2SS52 Y
M9RKT6 E
A0A2K1RA77 Y
A0A2K1RA81 Y
A0A2S0JW39 E
A0A2T9X1V4 Y
D3F545 E
A0A1E3PQH0 Y
A0A1J5JH24 Y
C4Y298 Y
Q3B6Q2 Y
Q7TNN9 M
A0A4Y7XC43 Y
A0A5B2V3B9 Y
B9L7N1 Y
C7M2A9 Y
D2V6Q5 E
E4T3F7 Y
F2YIC4 M
Q0G0A3 E
A0A424WAH3 Y
B8ZYW3 E
U7VB41 Y
A0A7S0KKL8 C
A0A1C7EL50 E
A0A6G9Y3Q0 Y
A0A6S5K4J1 Y
G0LFE3 E
J9VXX9 Y
V4RHR4 E
A0A0D7F2Y9 Y
A0A1S8D478 Y
Q47K18 Y
B9SWW9 Y
L8H5K0 M
A0A369N7Y3 Y
A0A399NT81 Y
B0SLB7 Y
B4CV94 Y
E1IF27 -
G2PRJ6 E
A0A202B535 Y
A0A2M9D7S8 Y
Q6LMI6 E
K2JVF8 E
Q1Q357 E
B8FDY8 Y
B8FL88 E
E3H8A6 E
H8L2Q4 Y
A0A248LMH8 Y
A0A5C5BWI6 Y
L1INN6 E
M7NFH3 E
A0A060URB8 Y
K9W6F3 Y
A0A7S0D560 Y
D2Q0J8 Y
A0A251YU48 Y
A0A6H9GEE4 E
A0A8F5ZDT8 Y
C1G973 Y
M0D580 E
A0A1Y5E3E3 Y
A0A328Q6M1 Y
Q7UGU7 E
A0A660CH85 Y
E4T3F3 E
A0A6H9GFU4 Y
A3XNG6 E
B9LU00 E
E4RTK5 Y
H6LKH9 Y
Q0AT01 E
A0A330GB00 Y
A0A657K391 Y
Q2N625 Y
E3GI40 Y
F4Y3C5 E
A0A017SYR8 Y
A0A494JB70 Y
D4XLN6 Y
Q1YDY7 Y
A0A2G5RQK9 E
A0A369NYJ2 Y
A0A1Q2C7H7 Y
C5LAG4 E
K0F9X7 Y
Q1K3N8 E
A0A2V4EA49 Y
A0A562BXM4 Y
A0A4D6KHD1 E
A0A4R6DFU8 Y
A0A4R7VEK0 Y
G0AFH4 Y
K5CFE5 Y
Q1H483 Y
A0A063Y780 E
A0A1W5PRD1 M
Q2YLQ6 Y
U5C4L4 E
A0A8G2F3G4 Y
D5ELM4 E
J2ZGN6 E
Q84KJ6 Y
A0A211ZGL5 Y
A0A373FQ71 Y
A0A2S8FR08 Y
A0A7T2W1B3 Y
D4F313 Y
F4KY49 Y
A0A149V596 Y
A0A2S7YPJ9 Y
A0A2S0Q8P1 E
Q7UYZ3 Y
J7ITF6 Y
Q9NIV0 M
A0A1D8UWJ6 Y
C1MHX0 Y
F3QPR6 Y
A0A068NV61 E
A0A1B9LFW3 Y
A0A7H8UK07 Y
A0AA91Q161 Y
A0AA92EGF5 Y
G7WFX4 Y
M9RJS5 Y
A0A1B9KID3 Y
A0A3E2UCG9 E
S9QZ09 Y
A0A2S8GSU9 Y
J7IVQ1 E
F0JGZ1 Y
F2AUF4 E
A0A2S8GEJ5 E
C6WEW7 Y
E5Y789 Y
J4KM12 Y
Q21P82 E
Q5P470 Y
A0A0H3H4I7 Y
D5VJ32 Y
C8WLL8 Y
D2R355 Y
H2CJI0 E
A0A2S5WGI8 Y
C1GR74 Y
A0A2S6GKF6 Y
A0A8H4GS02 Y
A0NJ07 -
C6CBB1 Y
Q7NQY2 Y
A0A173R3X4 E
A0A2G3E8V2 E
A0A2S6H6B7 Y
A0A316BQ38 Y
A0A9W3LFI9 Y
B4S394 Y
F0ZPL3 E
G0VI62 Y
A0A177W826 Y
A0A1H8D0R8 M
Q07UM3 Y
S3K1S2 Y
A0A4V3ALP8 Y
A0A6G9XJV9 Y
F7NPQ3 Y
J4UGB7 Y
J7L3W8 Y
A0A0A2B651 E
A0A258FTB0 Y
A4FMG0 Y
B7GKP4 E
C3YB73 E
C5BWX7 Y
I5C044 E
T2KGT3 E
A0A060UN76 E
A0A258FS85 Y
A0A975BTN0 Y
A1SY01 E
A8G2S3 E
B2IJT1 Y
C0Z5S5 E
Q21CP1 Y
A0A0A2C6L1 E
A0A1H9M798 Y
D5E995 E
C5CIT6 Y
D3RN22 E
A0A5M4ATH9 Y
A0A9J9ES23 E
C6XKC2 E
D2SE15 Y
K9U8C7 E
Q59UP8 Y
A0A1H4KAQ7 E
A0A1I5GN22 Y
V5E0F3 Y
C1N6X9 C
Q6CRN1 Y
R1EGK6 E
W0F0I7 Y
A0A088E6Q7 Y
A0A318FY98 Y
D7E934 E
K9ZLY2 E
M1V7W3 T
A0A2K3DPU7 M
A0A2S7YIM5 Y
F3ZYD6 E
F5R974 E
I6Z905 E
A1SZ12 E
A2BP62 E
B8FZP7 Y
K1LDP0 E
A0A3S9N9F3 Y
A2C095 E
C6DB68 Y
G0JRG9 Y
J7J5E7 Y
Q1K8A3 Y
Q2RM12 Y
Q7NCB8 Y
A0A2S0P9T4 Y
B0DU93 Y
D0LAL7 Y
D0MFE8 E
I5AZQ4 Y
Q2YBP7 M
Q81GN5 Y
A0A1B9NQ91 Y
A0A1T4SFY6 Y
A0A6H9FYW4 Y
A8ZQD5 E
E2SD44 Y
F2JZ83 E
H6LFQ2 E
I3Z3H7 E
A0A1M6JKY3 Y
A0A2J7TJ33 Y
Q7SEH0 Y
L8GFX3 Y
Q5KAF6 Y
K9YJQ3 E
Q5FA36 Y
A6M3G0 Y
D9SI59 Y
B7G0Y1 C
C1MX19 Y
D5T4N9 Y
A0A1B9M1A9 Y
A0A4R3NVT3 E
A0A420KGW4 Y
B0SRS8 E
D4GLQ6 Y
Q0ACK1 E
S0ET45 Y
A0A1G7H8X3 Y
A0A1X4G8K1 Y
F8E6R1 E
Q0G2V0 E
A0A5P9P1L2 E
A0A979GQ79 Y
A6VE60 Y
B9SA70 Y
E3H8C9 E
M2A398 Y
A0A1J5NTP7 Y
A0A2S8F4W0 E
Q9H310 M
W0DZX1 E
Q221S8 Y
Q6ND36 Y
A0A2C6C0X3 Y
A0A427KNL6 Y
A7HSN9 E
A0A0X8X7Y7 E
A0A248TDF2 E
A0A5M5PZE2 E
B1Y842 E
D2R647 E
D4H5F9 E
D9QS43 E
H1XV27 E
A0A0A1ZMZ9 E
A0A147GP06 Y
H6RWK9 Y
K9ZG59 Y
M2ALH9 E
A0A423Y4I6 Y
A7S3L2 E
A0AA35XZV0 Y
C7Q1E4 Y
G7WCB6 Y
R7PZ71 Y
A0A1H1U2Q6 Y
A0A562RGZ4 E
F4GED5 Y
A0A0X8NXA9 Y
F3KUN4 Y
C8WSI9 Y
O66395 Y
Q0I445 Y
Q95P70 M
A0A1W2GZ82 E
A0A7U8C744 E
A0A0E3R6S1 Y
A0A1I4ZIZ6 Y
Q6ND34 Y
A0A1G6ABL9 Y
A5D4I5 Y
K9P5D1 Y
A0A1B0ZRL8 E
A7RNC3 E
J1ASR8 Y
L0FU80 E
A0A510HHK8 E
D5AU98 Y
A0AA94HTL8 Y
A6W7U2 Y
F2JYR9 E
M5SY07 Y
Q94CJ2 M
W7QG13 E
A0A1G9P6Q0 E
A0A9Q8L398 Y
Q1QSQ2 E
Q5KPM5 Y
A0A068SVR1 Y
A0A4P7UHQ5 Y
A0A101HKN9 E
A0A1Y6GLJ1 Y
A0A562S8V2 Y
A0A8H6K7L7 Y
A0AA86YS65 Y
E7RJZ0 E
A0A037ZMW1 E
A0A0E3QY86 Y
F4H924 Y
Q8I0L6 M
A0A257T7G4 Y
I0JI83 E
Q45HK8 Y
K8EJ02 Y
Q2WBF7 Y
I4DBY0 Y
A0A142VAD6 Y
A0A482PLH3 Y
Q2IHY5 Y
R4FZE3 E
A0A2A2MCP3 Y
A0A5M8QF12 Y
A0A5A7MAJ9 Y
A0A9P3CXY2 Y
B3MX93 E
B9ACS5 Y
A0A085GI50 Y
A0A1B9K8L2 Y
A0A2X2C038 Y
Q1Z4I4 E
A0A075WG29 E
A0A2S6H643 Y
A0A6M3ZJI1 Y
A1ZGK6 E
A2CCK1 E
C7QGX3 Y
D0LTW3 E
D3PKL4 Y
A0A0S4VNK2 Y
A0A410K1J5 E
D5ASL9 Y
A0A369MRW6 Y
A6GJF5 E
Q9UBD6 M
A0A0A3XTJ3 Y
A0A264VQM8 Y
A0A1Z3MS36 Y
B3PIH2 Y
Q5FLR6 Y
A0A087MGU4 Y
A0A1Y2JH43 Y
L7CG11 Y
Q2RWY7 Q
Q6CRN0 Y
T2IEJ2 E
A0A1B9MBX6 Y
B8J5X4 E
A0A7S0ILH2 Y
A1VIG8 Y
P69681 Y
Q6LKC8 E
Q84KJ7 Y
A0A0H3KTD3 Y
A0A1T4SFK4 Y
D3DJN2 Y
Q2FS34 Y
A0A165MFD1 E
A0A1B9BUZ8 Y
A0A1G5W0P2 Y
A0A2T2Y0D5 Y
H6LKH6 Y
L0KGR8 Y
A0A0A2BBY0 E
A0A0M3AB44 Y
A0A3N0AQL8 Y
A0A854QN45 Y
A7SGD4 E
C1D4X0 Y
U3P8G1 Y
A0A147EQL9 Y
A0A375YPN6 E
A0A533I6R2 Y
A0A1H1BPD6 Y
A0A495DND0 Y
A0A2N0MZ27 Y
A0A2U1SS17 Y
A0A0D7F328 Y
A0A0E3LMT4 E
A0A7U3XVQ4 Y
B1Y6V4 Y
Q6BT62 Y
A0A0S2DQB6 Y
A0A258HS77 Y
A0A5C5TYS5 Y
A0A7U8C2Y6 E
D4H2Y7 E
G4R7P1 E
R1FI09 E
A0A074KZD8 E
A0A2W4ZXC0 Y
A0A1H9RTW8 Y
A0A9E9L9J1 Y
A1SVA8 E
M0D3Q9 E
A0A087EQK8 Y
A0A0E3R4G0 E
A0A369M386 Y
A0A3E2VY88 E
I0WJ97 E
Q6HM26 Y
W0DZS7 Y
A0A0E3BR91 Y
A0A1G6ABK5 E
B7G0Y4 C
B8JBH5 Y
D6Z5V9 E
M5S9B4 E
S0EUS1 T
V4CRP5 E
A0A149UWF2 Y
A0RXK8 Y
B1Y8C9 Y
A0A212AV03 Y
A2BUP4 E
A0A1E5BXA4 E
A7SQ16 E
B0DY50 Y
A0A0S4WFM4 Y
A0A6N4SPH9 E
C5KTM6 E
C9R9J0 Y
Q0F2M5 E
Q2SIR0 E
Q9VFA9 E
A0A4Y4DZN4 Y
A0A977NL43 Y
A0A0A2VPU3 Y
A8MCL4 Y
A0A379A0S9 E
A0A6F8TLE9 Y
Q8GQS1 Y
V3ZVE4 E
A0A1T4SF40 Y
A0A2N7L7C8 E
A0A074ME37 Y
Q8RUT6 C
B0VMH1 Y
Q92BJ7 Y
A0A0L0TDW1 Y
A0A857DDJ7 Y
A0AA92K392 Y
B8GGC3 Y
Q7V4T8 E
A0A0V8M0W6 Y
A0A5C4RNH5 Y
A0A511NGC7 Y
A0A149UP06 Y
A0A4R3A5P7 Y
A0A4U1JNL6 Y
Q21J04 Y
A0AIW5 Y
X5CNT2 Y
A0A2T5IHP0 M
A0A5C6LWQ1 Y
A0A433ZQ80 Y
A7SED8 L
A0A853MG28 E
C0QSY0 Y
H1YF74 E
H6LKX6 E
Q47X17 Y
A0A037ZJY5 Y
A0A1B9MZ78 Y
B3PF77 E
B4HDZ9 E
E6W5C1 E
M1WRK6 -
A0A2G6JLT9 E
A7I8Z2 Y
B2GFN1 Y
D2V6P8 M
F2G6G4 E
A0A1H7CU41 Y
A0A2S5WMT7 Y
A0A4Q2EAG7 Y
Q5KZZ9 E
A0A1I0AQM4 M
A0A1I7FBM5 M
A8AC17 Y
A0A0D2UPA8 Y
A0A4R8GSH7 E
C7NND3 E
D3LBI0 -
I7ZHW3 Y
Q0VPH4 E
A8M670 Y
B0DU91 Y
E4T0A4 Y
F0Y9X3 E
Q0G0A4 Y
A0A2S8FTB5 E
A0LV78 Y
A0A2S8QA29 Y
D3PAH1 Y
A0A6T9XUR2 E
A7I8Z4 Y
B0CQX4 Y
D6TCH6 Y
K0N2R5 Y
K8W1E2 Y
A0A1G6ABX1 E
A0A2S5WZU0 Y
D6SPD1 E
M5S735 Y
U1PPI7 E
A0A0C6P439 Y
A0A257SYX3 Y
A7NKH2 E
Q1Q879 E
A4BAE1 E
D2BIB2 Y
A0A2K3DQF8 C
A0A7V8IKS6 Y
A0A7U3YMN6 Y
Q9REX3 E
A0A2S5WUP6 Y
D6TFE1 E
Q3Z7F9 Y
A0A0L8BVU4 Y
A0A2R4MBA2 Y
A0A2I0UUY1 E
G0JRQ3 E
A0A067Z3S3 Y
A0A161SKF4 Y
A4BMY5 Y
B0XVV6 Y
K2IMJ7 E
P40260 Y
A0A414NWT8 Y
A0A8F5VN39 Y
A0A837C6X5 Y
C9KKP2 Y
D4XSW0 E
J9Z839 Y
Q07UM1 Y
Q60BI2 Y
A0A0L0STS6 Y
A0A366WYI9 E
A0A251YFS0 Y
F7ZJZ1 E
J3EXK0 E
Q0F2M7 Y
A0A016XDZ5 Y
A0A1A0DHK0 Y
G0IYI2 E
G5EB09 Y
Q60C43 Y
A0A034WGQ2 E
A0A2A2M8K7 Y
A0A066ZRQ5 E
B3QRJ4 Y
A0A165MAC2 Y
G8JUJ2 Y
R9PI53 E
A0A059XXR1 Y
A0A075JZ35 Y
F2NNQ0 Y
O04161 C
A0A2A7U6W1 Y
A0A7M6UUM4 M
A0A420WC79 E
A0A7G5DKA9 E
A0A7S4LPS8 E
A0A7U4E420 Y
C8WZE0 E
E4TRS4 E
A0A1W2H3F0 E
A0A2T4XZC1 Y
A0A248LNK5 Y
A0A251XJT0 Y
A0A4P6UIJ8 Y
A0A7G5DPV0 Y
B0DXT9 Y
J0S2I0 E
A0A071M4L5 Y
A0A0B4E6X7 E
K9WSX4 E
K9WT03 Y
A9BTK1 Y
D5UD26 Y
M1NZT5 E
A0A0B5FNH4 E
A0A8H7P8U1 Y
A0A495WJM6 Y
A0A075JIN0 Y
A0A091AXI3 Y
A0A381CAY8 Y
A0A3E2T713 E
E1SLM7 E
M9YAI9 Y
A0A0T7FAP8 Y
A0A1B9MYL7 Y
A0A1G5RZU9 E
A0A1G7VM92 Y
A0A1J5NNB8 E
A0A3E2UHE6 E
G7WA28 Y
H5UND3 Y
A0A0B4DUR9 E
A0A149QSR6 Y
W0DYY3 E
M1SJL5 Y
V4RK08 E
A0A063Y394 E
A0A1B9JHS5 Y
A0A5M4B0G1 Y
A0A6C8LST1 Y
A0A8E2R1Y5 Y
A6DUG4 E
B0CXH8 Y
F4D1J0 Y
A0A1L3F1X5 Y
A0A257T8W6 Y
U5DEY6 E
A4CMI3 E
A0A011U1K7 Y
A0A401X433 Y
Q2S8H9 E
F7ZJM0 E
L0JT30 E
Q22947 M
Q63EK5 Y
A0A1I4W3A0 Y
D0KXQ0 E
A6LV49 Y
C7LW88 E
L0KW14 Y
S0G181 E
A0A1W9KSU5 Y
A0A377I7W9 Y
E5B358 Y
G0V8D6 Y
L1IHZ8 Y
A7HSP2 Y
C1A872 Y
A0A6H9GWG4 E
F0S3Z6 E
A0A0P6VSR8 Y
A0A1Y0V4A5 Y
E1QFA8 Y
E4N1T5 Y
R1EDV9 E
B0DFJ4 Y
D2RU19 E
A0A2H4U5R1 Y
A0A2T1N7R1 E
A0A5J6WPP9 E
A1B3N0 Y
A0A142NNN1 Y
A0A172YCA7 Y
Q9M6N7 Y
V5BYZ7 Y
A0A060HN92 E
A0A2N7LCD7 E
F0ZCX7 M
Q6ARH0 E
A0A009PYN3 Y
A0A075WBP9 Y
A0A9E9LXV9 Y
A0A089ZBW5 Y
A0A6P4JM51 E
A0A2S5X482 Y
F5ISF6 Y
Q0ARJ4 Y
A0A0H2XSU4 Y
A0A290XBB5 Y
A8NAG3 Y
B0SL05 E
G8JTW0 Y
A0A9W5JBA9 Y
A2SPS8 Y
A0A5C5TUT2 Y
C1F584 E
C7R314 Y
H2CLF7 E
A0A401WXG0 Y
A0A542XGT4 Y
A0A0S2FHD7 Y
A0A2S5YID7 Y
A0A149RQX0 Y
A6DN47 E
A0A225CMT8 Y
G4QHD2 E
K9YR86 E
A0A174SD65 Y
D7UQE2 M
D9QPC8 Y
G7WDB5 -
G8TK77 Y
K9Z0D3 E
A0A101DCS3 Y
A0A172YBR4 E
Q1L727 E
A0A318QZ80 E
A0A8H6MPB9 Y
N1WR17 E
Q2J376 Y
A0A0D2NYP3 Y
A0A2I1M481 Y
I0HGY4 Y
A4ABK3 E
C9RS76 E
F2JTN3 E
G0JRH4 Y
M5U2P1 E
Q1PX09 -
Q2HD43 Y
A0A165BP25 Y
A0A2C9CK98 E
G0J614 E
M4VEJ9 Y
U5C2K4 E
A0A1S1HM83 Y
F0RHS0 E
A0A5M4AWD2 E
B7FW68 C
G9Y5B0 Y
Q5FSX6 Y
A0A149TSA9 Y
A0A1G7UZX2 E
A3ZZL7 Y
A9WHW6 T
B7FTM9 C
A0A1H4DJ49 E
A0AA35XVN2 Y
A0A2T0GTU1 Y
A0A4R3ZZ35 Y
A0A855EH99 Y
D9QPE5 Y
M5SYZ1 E
Q0VQH6 Y
A0A096EEV9 Y
A0A2R3IMJ8 Y
Q6QH01 C
E0SD83 Y
I5B3H0 E
X5DX97 E
A0A7T2S0Z6 Y
A9B874 E
A0A2R4TRE0 Y
D3F0Z1 E
A0A4R2M206 Y
A4BEP1 E
P41948 Y
A0A1S1HRJ0 Y
A0A2S5V2F6 Y
B9WDK0 Y
C8XBX8 Y
R8VWI7 E
A0A4R3NLV5 Y
A6XBM2 M
A8HSA2 C
C3X831 Y
U2WTW8 E
A0A1M6BPM0 Y
A0A4P6UIK6 Y
A0A4R5U5V1 Y
A0RUZ2 Y
I4CCD1 Y
J1L5M8 Y
Q89WR5 Y
A0A068TC78 Y
A0A166IS52 E
D3PE53 Y
A0A077EFU9 Y
A0A160KTE9 Y
A0A1Y5E8I7 E
A0A6H9GLV4 E
G3IYW0 Y
G7WFX2 E
Q6BK68 Y
Q9QUT0 M
A0A1E5C7W4 E
A0A1Y3U5V2 Y

In [6]:
mer = []

for u in idid:

SyntaxError: incomplete input (2829510097.py, line 4)

In [7]:
sevenone

['A1D2Y5 Y',
 'M8E0R3 E',
 'A0A2G3DSU6 E',
 'A0A328EMN2 Y',
 'A0A6A1TYJ4 Y',
 'D3RMV7 Y',
 'F0J3F9 Y',
 'G2ZN72 Y',
 'I0KDC6 Y',
 'A0A081N2G5 E',
 'A0A144NLT9 Y',
 'B4D7W2 Y',
 'F3QNA7 Y',
 'Q4WHC6 Y',
 'Q8JI14 M',
 'A0A395VB65 E',
 'A0A975GIX9 Y',
 'Q5UZ98 E',
 'A0A4R4K1P9 Y',
 'A0A7T4WEP4 Y',
 'C6LBD3 E',
 'D5V7B3 E',
 'A0A4R3ZNW3 Y',
 'A9BQZ4 Y',
 'A0A642KQG8 E',
 'A9BIZ7 E',
 'K0NJH2 E',
 'Q2IK04 E',
 'T2KJ59 E',
 'A0A1B9M5B8 Y',
 'A0A323UE08 Y',
 'E8RLT5 Y',
 'F6G5I9 Y',
 'G3A431 Y',
 'G4H971 E',
 'L1J6I4 Y',
 'M0J579 E',
 'A0A377PBY1 Y',
 'A0A401WUW1 Y',
 'L1IYW7 Y',
 'A0A315S845 Y',
 'A0A6M3ZKU5 E',
 'A0A502GPV4 Y',
 'A0A9J9BAE8 E',
 'A1AVV2 Y',
 'B1XZU2 E',
 'Q5P1S8 E',
 'A0A0F5EZP7 Y',
 'A0A4R7GKA0 Y',
 'A0A2T4UWF1 Y',
 'A0A3E0X011 E',
 'A0A4R8H081 E',
 'C7LQR9 E',
 'A0A0A2A0Y9 E',
 'A0A0A2A5X1 E',
 'A0A7T5BFQ2 E',
 'A3U857 Y',
 'E1V4T3 E',
 'F0J7D3 Y',
 'M7XJ51 E',
 'Q1K0H9 E',
 'A0A2S5XAB8 Y',
 'A0A366IE34 Y',
 'Q1Z695 E',
 'A0A8G2IZM3 Y',
 'G3IYW2 Y',
 'A0A2G5BGA9 Y',
 'A0A5M4AUM9 Y',
 'E3HJW8 Y',
 'U1PIR6 E',
 'A0A1B9N3H7 Y',
 'A0A2S5WV24 Y',
 'A0A6U2BIY7 E',
 'A0A833LX85 E',
 'I9P003 E',
 'K8VZC6 Y',
 'L1IUV5 Y',
 'A0A0K2STQ7 E',
 'A0A2H1HV86 Y',
 'Q2GX26 Y',
 'A0A074KY88 E',
 'A0A858ZNJ3 Y',
 'A0A3P2A7W8 Y',
 'A0A7S4GND2 E',
 'O26757 -',
 'Q46G49 Y',
 'A0A140NHJ5 Y',
 'A0A2S8GF54 E',
 'B1JZ69 Y',
 'E5Y678 Y',
 'A0A149U2G9 Y',
 'A0A9Q5QVI9 Y',
 'Q18PF5 M',
 'A0A317FZW2 E',
 'G5EB13 Y',
 'Q1YDY8 E',
 'A0A1X4GBG2 E',
 'A0A4Q7Y9I7 Y',
 'I0HKQ8 Y',
 'A0A097R891 Y',
 'A0A7S4GMD8 C',
 'Q488X2 E',
 'U3PCH5 S',
 'A0A378YR15 Y',
 'I1YG38 E',
 'F5XN43 Y',
 'Q1IWN6 Y',
 'A0A1E3PSK5 Y',
 'A0A833H2R7 E',
 'A0A2T0XPP2 E',
 'A0A399T909 Y',
 'L8GGA0 Y',
 'A0A0D8BQX6 E',
 'A0A1M5ZVP9 E',
 'I5BYV5 E',
 'A0A0K2STH0 E',
 'A0A2N6K4Y5 Y',
 'A0A1B9JZS5 Y',
 'A0A2W0GQV0 Y',
 'A0A369MHK2 Y',
 'A0A087L0B9 Y',
 'A0A0A2AMW2 E',
 'A0A377PLP5 Y',
 'Q6BJI7 Y',
 'Q7S5K0 Y',
 'Q7Z1M1 E',
 'T2JFS5 E',
 'W0JIB3 E',
 'A0A1V2XMU9 Y',
 'A0A2S6GKN5 Y',
 'A0A7G5DK18 Y',
 'A0A830ZZN8 Y',
 'A0A8B4RWH8 Y',
 'A0A9Q6P4A5 Y',
 'B8ENL9 Y',
 'Q9QXP0 M',
 'A0A060URC3 Y',
 'A0A2W5HTC3 Y',
 'A7S731 E',
 'A0A1Y0UZX2 Y',
 'A0A257TE48 E',
 'Q2RVB5 Y',
 'Q605Y6 Y',
 'A0A918MJ52 E',
 'K6W5X0 Y',
 'V4AP67 E',
 'A0A7Z0V0A4 Y',
 'C0GKN4 E',
 'A9HMD6 Y',
 'B1ZSW9 Y',
 'K5DBA0 E',
 'V4REY8 E',
 'A0A0D2KGN8 Y',
 'A0A242NIL1 Y',
 'A8PXT8 Y',
 'B7X047 Y',
 'D2ZRW2 Y',
 'H1Y7T6 Y',
 'Q97L80 Y',
 'A0A0S6UHP2 E',
 'A0A323UDG5 Y',
 'E3I393 Y',
 'A0A4V2X6C2 Y',
 'D7G265 E',
 'A6LRS5 Y',
 'D8J4C6 E',
 'F2NGJ8 Y',
 'A0A0E9NHV4 Y',
 'A1CQ21 Y',
 'A0A6N2Z556 E',
 'Q0BWD0 E',
 'A0A071MMV1 Y',
 'A0A168EVK8 Y',
 'B3DUX7 Y',
 'F5L8M7 E',
 'G7WJN0 E',
 'Q0BQ69 Y',
 'A0A3N2SFS2 Y',
 'A0A9Y2AG30 Y',
 'A0AA46Q839 Y',
 'E8RSE4 Y',
 'F6BEI0 E',
 'I1DSU5 E',
 'I4C9L2 Y',
 'Q5QVH2 E',
 'A0A068NPW2 Y',
 'A0A6J5IRX5 Y',
 'A0A3R9Q7C4 Y',
 'A3ZT81 E',
 'K0ER80 Y',
 'Q0VLH1 E',
 'Q2KZK9 Y',
 'R9GM11 Y',
 'A0A0T7GZ59 Y',
 'A0A1G5PWV0 Y',
 'S5ABR8 E',
 'W7QGM4 E',
 'F5Y3C1 Y',
 'I8TC71 Y',
 'M1P5F0 E',
 'A0A149RYW7 Y',
 'A0A1J1JH03 E',
 'A0A1U9Z147 Y',
 'A0A243SC06 Y',
 'A0A3G9G2C9 Y',
 'I4C9L0 Y',
 'I4D1H5 Y',
 'Q7W7D3 Y',
 'A0A0B4M163 M',
 'A0A1M7UEG2 Y',
 'A7HT14 E',
 'C8X554 Y',
 'A0A127PIQ9 Y',
 'A0A1B9JPL5 Y',
 'W5WIX6 Y',
 'A0AA40J491 Y',
 'D8PD01 Y',
 'A0A251XU71 Y',
 'A0A2N6P374 Y',
 'B3QVV5 Y',
 'K1K628 Y',
 'A0A1E2SKM1 S',
 'A0A1I0BYN1 Y',
 'A0A556RTU3 Y',
 'A0A829X098 Y',
 'D5EP68 -',
 'F0J6E8 Y',
 'A0A073CP02 E',
 'A0A127JTU2 Y',
 'C7BJG7 Y',
 'D2BUJ8 Y',
 'B8IZX4 Y',
 'I3R0S7 E',
 'A0A3E2TW06 E',
 'B1Y0E5 Y',
 'E6ME92 Y',
 'A0A251Y3N4 Y',
 'A0A380S5X4 E',
 'F0YLV7 E',
 'F8D7H6 E',
 'Q31CR9 E',
 'W0E077 E',
 'A5DYQ2 Y',
 'A8LKQ0 E',
 'A0A4Y1MSE7 Y',
 'A3TVQ9 E',
 'F2B2B8 Y',
 'L0K9M1 E',
 'Q4WT12 Y',
 'Q8ERT9 E',
 'A0A1H3WA00 Y',
 'A0A1U9YY82 E',
 'A1DG05 Y',
 'B8GGC1 Y',
 'F3ZVV4 Y',
 'P69680 Y',
 'Q0G2T1 E',
 'A0A3T0SZ22 Y',
 'A0A4R2Z2K6 Y',
 'L1IYP4 Y',
 'Q46HB1 E',
 'A0A149QAW7 Y',
 'A0A1Y4L5P0 E',
 'A0A6B8N021 Y',
 'D5EP71 Y',
 'V5U2Z4 Y',
 'A0A0E3QYF3 E',
 'A0A0K2STK6 E',
 'A0A8H7U3I1 Y',
 'A0A062IU58 Y',
 'A0A178TA08 E',
 'A0A3G9G4Q4 Y',
 'A0A6H9FPY5 E',
 'A1C5Z7 Y',
 'A0A0A1ZJU5 E',
 'A0A258HPP1 Y',
 'G0H0Z6 E',
 'A0A2Z4MD56 E',
 'G0EFF3 Y',
 'E2SD33 Y',
 'E4TJ50 Y',
 'A0A016XCG9 Y',
 'A0A2S5Y0D3 Y',
 'K9YN27 E',
 'Q3AFY9 Y',
 'Q7N0M6 Y',
 'W8KM07 E',
 'A0A0G9HEC5 Y',
 'A5UJR1 Y',
 'A0A9Q9D9I3 Y',
 'B9SXC7 Y',
 'C0QTA4 Y',
 'A0A176XNC5 Y',
 'A0A317G0I6 E',
 'A0A2S5CTX8 E',
 'U2EN72 E',
 'A0A248LNW8 E',
 'A0A4P8HC89 Y',
 'G7UUY6 Y',
 'A0A0E3WZH5 E',
 'A0A165K0X5 E',
 'D3FBG3 Y',
 'Q608B6 E',
 'A0A854Q6X9 Y',
 'H2IZ00 Y',
 'A0A4V0XUI3 E',
 'A0A7S4GNJ2 E',
 'A0A2S5WX34 Y',
 'C1D6X6 Y',
 'A0A418VIJ8 Y',
 'A0A857DMN9 Y',
 'Q7T3R4 M',
 'R1D1H4 E',
 'T2J0N1 E',
 'A0A419AVL2 Y',
 'K0K7J4 Y',
 'A0A4U1K1W1 Y',
 'A0A9R0NTP8 Y',
 'B0RC35 Y',
 'C8XB51 Y',
 'E4NS62 E',
 'R9PMC6 E',
 'A0A1R1IDV3 Y',
 'A0A2N6JV02 E',
 'A7MFK3 Y',
 'B0BZN3 E',
 'F7ZEU9 E',
 'K9P718 E',
 'Q82X47 M',
 'Q8RUE9 M',
 'A0A0M2LU39 Y',
 'A0A3N1VXY4 Y',
 'A0A370FPU0 Y',
 'A0A7G5DPV1 E',
 'A9UR54 E',
 'F0S0G1 Y',
 'K9W4V5 E',
 'A0A015YIP3 E',
 'A0A291PMC6 Y',
 'G8R7U9 Y',
 'U1H1F7 Y',
 'A0A021VMC6 Y',
 'A0A855F5Y8 Y',
 'A0A2W5VAZ2 Y',
 'M0MDP9 E',
 'A0A1X3RP39 Y',
 'A0A653N397 Y',
 'A0A8G2F718 E',
 'F4B548 Y',
 'I0ICG0 E',
 'A0A009TDB1 Y',
 'A0A1G7DX68 Y',
 'E4YA63 E',
 'Q2W5V2 E',
 'Q3AP28 Y',
 'Q9BLG3 E',
 'A0A0D5YN10 Y',
 'A0A0L0S493 Y',
 'H1YCC3 Y',
 'L8JUH3 E',
 'A0A0E3SHQ9 E',
 'A0A366XFS8 Y',
 'E6VIW4 Y',
 'F6FRU9 Y',
 'A1VIM5 Y',
 'E0TGP9 E',
 'A0A0E3SP24 Y',
 'A0A8H6NAG3 Y',
 'B8FGW0 Y',
 'C3X1J1 Y',
 'D9SI36 E',
 'E0TCV4 E',
 'E4U5Z1 Y',
 'A0A094W9G3 E',
 'A0A7G5EC77 Y',
 'A0A482TED1 E',
 'A0A4Q2QWS1 Y',
 'A3PAY4 E',
 'A0A173R3W6 Y',
 'A0A1B9BUU6 Y',
 'A0A495D4X4 E',
 'A0A833GZR2 E',
 'D0L8H3 Y',
 'F4XTK4 E',
 'I4D6Z7 Y',
 'L8H844 E',
 'A0A0S6UEK9 Y',
 'A0A1M6ZMI3 E',
 'U1SIR9 Y',
 'A0A066ZTE4 E',
 'A9DQM8 E',
 'A0A0A0D6K5 Y',
 'D6E7B3 Y',
 'A0A562USB9 E',
 'C7LW87 Y',
 'G0JRG6 Y',
 'A0A1X6N3Q5 Y',
 'A0A1Y4LM49 E',
 'B7FSA7 C',
 'E1QIU3 E',
 'H2CDR5 E',
 'Q1K433 E',
 'Q1QS12 Y',
 'Q7T070 M',
 'A0A0H3DR67 Y',
 'A5CRL2 Y',
 'A0A836M2B6 Y',
 'E6SF19 Y',
 'I2GD40 Y',
 'Q18ES8 E',
 'A0A060UWC8 Y',
 'A0A0U1NJW3 E',
 'A0A7R6PER3 E',
 'A4G1J2 Y',
 'A9AUR8 Y',
 'C1N5A7 C',
 'D3S2L0 Y',
 'F8IJE0 Y',
 'A0A0D2LEF5 Y',
 'A0A1H1MB73 Y',
 'W7QGE0 Y',
 'G2T1Y3 E',
 'L7CG99 E',
 'A0A1I0C958 E',
 'A0KPE9 Y',
 'A9V5W4 M',
 'F5RGM7 Y',
 'A0A1C6Z081 Y',
 'A0A1D3GAE9 Y',
 'A0A410JZR4 Y',
 'A8N2H6 Y',
 'I1YJH7 E',
 'A0A2G5BI87 Y',
 'A0A2N6NEK4 Y',
 'A0A1Y0HX98 Y',
 'C3YB74 E',
 'Q1H0G2 E',
 'Q2FQT3 Y',
 'S0APH6 Y',
 'A0A075WEB4 Y',
 'A0A172RYW3 Y',
 'I3C0V3 E',
 'A0A556SRH6 Y',
 'A0A7U4DN04 Y',
 'A0A1V3SSW1 E',
 'Q466Y3 E',
 'A0A0A2ZRL7 Y',
 'A0A0H3LUA3 Y',
 'A4G0C5 E',
 'A5E3X2 Y',
 'A8P923 Y',
 'B8EMQ8 Y',
 'D0MFE9 Y',
 'A0A060HFT5 Y',
 'A0A060JMP6 Y',
 'A0A8E2UDJ3 Y',
 'I4D6Z9 E',
 'Q13E03 Y',
 'Q1JXS5 Y',
 'A0A076PL76 Y',
 'A0A6N2TIA4 E',
 'Q1AUG3 E',
 'A0A098S5Y7 E',
 'A0A7S4GNF3 E',
 'A0A5J6WQU1 E',
 'A2SS52 Y',
 'M9RKT6 E',
 'A0A2K1RA77 Y',
 'A0A2K1RA81 Y',
 'A0A2S0JW39 E',
 'A0A2T9X1V4 Y',
 'D3F545 E',
 'A0A1E3PQH0 Y',
 'A0A1J5JH24 Y',
 'C4Y298 Y',
 'Q3B6Q2 Y',
 'Q7TNN9 M',
 'A0A4Y7XC43 Y',
 'A0A5B2V3B9 Y',
 'B9L7N1 Y',
 'C7M2A9 Y',
 'D2V6Q5 E',
 'E4T3F7 Y',
 'F2YIC4 M',
 'Q0G0A3 E',
 'A0A424WAH3 Y',
 'B8ZYW3 E',
 'U7VB41 Y',
 'A0A7S0KKL8 C',
 'A0A1C7EL50 E',
 'A0A6G9Y3Q0 Y',
 'A0A6S5K4J1 Y',
 'G0LFE3 E',
 'J9VXX9 Y',
 'V4RHR4 E',
 'A0A0D7F2Y9 Y',
 'A0A1S8D478 Y',
 'Q47K18 Y',
 'B9SWW9 Y',
 'L8H5K0 M',
 'A0A369N7Y3 Y',
 'A0A399NT81 Y',
 'B0SLB7 Y',
 'B4CV94 Y',
 'E1IF27 -',
 'G2PRJ6 E',
 'A0A202B535 Y',
 'A0A2M9D7S8 Y',
 'Q6LMI6 E',
 'K2JVF8 E',
 'Q1Q357 E',
 'B8FDY8 Y',
 'B8FL88 E',
 'E3H8A6 E',
 'H8L2Q4 Y',
 'A0A248LMH8 Y',
 'A0A5C5BWI6 Y',
 'L1INN6 E',
 'M7NFH3 E',
 'A0A060URB8 Y',
 'K9W6F3 Y',
 'A0A7S0D560 Y',
 'D2Q0J8 Y',
 'A0A251YU48 Y',
 'A0A6H9GEE4 E',
 'A0A8F5ZDT8 Y',
 'C1G973 Y',
 'M0D580 E',
 'A0A1Y5E3E3 Y',
 'A0A328Q6M1 Y',
 'Q7UGU7 E',
 'A0A660CH85 Y',
 'E4T3F3 E',
 'A0A6H9GFU4 Y',
 'A3XNG6 E',
 'B9LU00 E',
 'E4RTK5 Y',
 'H6LKH9 Y',
 'Q0AT01 E',
 'A0A330GB00 Y',
 'A0A657K391 Y',
 'Q2N625 Y',
 'E3GI40 Y',
 'F4Y3C5 E',
 'A0A017SYR8 Y',
 'A0A494JB70 Y',
 'D4XLN6 Y',
 'Q1YDY7 Y',
 'A0A2G5RQK9 E',
 'A0A369NYJ2 Y',
 'A0A1Q2C7H7 Y',
 'C5LAG4 E',
 'K0F9X7 Y',
 'Q1K3N8 E',
 'A0A2V4EA49 Y',
 'A0A562BXM4 Y',
 'A0A4D6KHD1 E',
 'A0A4R6DFU8 Y',
 'A0A4R7VEK0 Y',
 'G0AFH4 Y',
 'K5CFE5 Y',
 'Q1H483 Y',
 'A0A063Y780 E',
 'A0A1W5PRD1 M',
 'Q2YLQ6 Y',
 'U5C4L4 E',
 'A0A8G2F3G4 Y',
 'D5ELM4 E',
 'J2ZGN6 E',
 'Q84KJ6 Y',
 'A0A211ZGL5 Y',
 'A0A373FQ71 Y',
 'A0A2S8FR08 Y',
 'A0A7T2W1B3 Y',
 'D4F313 Y',
 'F4KY49 Y',
 'A0A149V596 Y',
 'A0A2S7YPJ9 Y',
 'A0A2S0Q8P1 E',
 'Q7UYZ3 Y',
 'J7ITF6 Y',
 'Q9NIV0 M',
 'A0A1D8UWJ6 Y',
 'C1MHX0 Y',
 'F3QPR6 Y',
 'A0A068NV61 E',
 'A0A1B9LFW3 Y',
 'A0A7H8UK07 Y',
 'A0AA91Q161 Y',
 'A0AA92EGF5 Y',
 'G7WFX4 Y',
 'M9RJS5 Y',
 'A0A1B9KID3 Y',
 'A0A3E2UCG9 E',
 'S9QZ09 Y',
 'A0A2S8GSU9 Y',
 'J7IVQ1 E',
 'F0JGZ1 Y',
 'F2AUF4 E',
 'A0A2S8GEJ5 E',
 'C6WEW7 Y',
 'E5Y789 Y',
 'J4KM12 Y',
 'Q21P82 E',
 'Q5P470 Y',
 'A0A0H3H4I7 Y',
 'D5VJ32 Y',
 'C8WLL8 Y',
 'D2R355 Y',
 'H2CJI0 E',
 'A0A2S5WGI8 Y',
 'C1GR74 Y',
 'A0A2S6GKF6 Y',
 'A0A8H4GS02 Y',
 'A0NJ07 -',
 'C6CBB1 Y',
 'Q7NQY2 Y',
 'A0A173R3X4 E',
 'A0A2G3E8V2 E',
 'A0A2S6H6B7 Y',
 'A0A316BQ38 Y',
 'A0A9W3LFI9 Y',
 'B4S394 Y',
 'F0ZPL3 E',
 'G0VI62 Y',
 'A0A177W826 Y',
 'A0A1H8D0R8 M',
 'Q07UM3 Y',
 'S3K1S2 Y',
 'A0A4V3ALP8 Y',
 'A0A6G9XJV9 Y',
 'F7NPQ3 Y',
 'J4UGB7 Y',
 'J7L3W8 Y',
 'A0A0A2B651 E',
 'A0A258FTB0 Y',
 'A4FMG0 Y',
 'B7GKP4 E',
 'C3YB73 E',
 'C5BWX7 Y',
 'I5C044 E',
 'T2KGT3 E',
 'A0A060UN76 E',
 'A0A258FS85 Y',
 'A0A975BTN0 Y',
 'A1SY01 E',
 'A8G2S3 E',
 'B2IJT1 Y',
 'C0Z5S5 E',
 'Q21CP1 Y',
 'A0A0A2C6L1 E',
 'A0A1H9M798 Y',
 'D5E995 E',
 'C5CIT6 Y',
 'D3RN22 E',
 'A0A5M4ATH9 Y',
 'A0A9J9ES23 E',
 'C6XKC2 E',
 'D2SE15 Y',
 'K9U8C7 E',
 'Q59UP8 Y',
 'A0A1H4KAQ7 E',
 'A0A1I5GN22 Y',
 'V5E0F3 Y',
 'C1N6X9 C',
 'Q6CRN1 Y',
 'R1EGK6 E',
 'W0F0I7 Y',
 'A0A088E6Q7 Y',
 'A0A318FY98 Y',
 'D7E934 E',
 'K9ZLY2 E',
 'M1V7W3 T',
 'A0A2K3DPU7 M',
 'A0A2S7YIM5 Y',
 'F3ZYD6 E',
 'F5R974 E',
 'I6Z905 E',
 'A1SZ12 E',
 'A2BP62 E',
 'B8FZP7 Y',
 'K1LDP0 E',
 'A0A3S9N9F3 Y',
 'A2C095 E',
 'C6DB68 Y',
 'G0JRG9 Y',
 'J7J5E7 Y',
 'Q1K8A3 Y',
 'Q2RM12 Y',
 'Q7NCB8 Y',
 'A0A2S0P9T4 Y',
 'B0DU93 Y',
 'D0LAL7 Y',
 'D0MFE8 E',
 'I5AZQ4 Y',
 'Q2YBP7 M',
 'Q81GN5 Y',
 'A0A1B9NQ91 Y',
 'A0A1T4SFY6 Y',
 'A0A6H9FYW4 Y',
 'A8ZQD5 E',
 'E2SD44 Y',
 'F2JZ83 E',
 'H6LFQ2 E',
 'I3Z3H7 E',
 'A0A1M6JKY3 Y',
 'A0A2J7TJ33 Y',
 'Q7SEH0 Y',
 'L8GFX3 Y',
 'Q5KAF6 Y',
 'K9YJQ3 E',
 'Q5FA36 Y',
 'A6M3G0 Y',
 'D9SI59 Y',
 'B7G0Y1 C',
 'C1MX19 Y',
 'D5T4N9 Y',
 'A0A1B9M1A9 Y',
 'A0A4R3NVT3 E',
 'A0A420KGW4 Y',
 'B0SRS8 E',
 'D4GLQ6 Y',
 'Q0ACK1 E',
 'S0ET45 Y',
 'A0A1G7H8X3 Y',
 'A0A1X4G8K1 Y',
 'F8E6R1 E',
 'Q0G2V0 E',
 'A0A5P9P1L2 E',
 'A0A979GQ79 Y',
 'A6VE60 Y',
 'B9SA70 Y',
 'E3H8C9 E',
 'M2A398 Y',
 'A0A1J5NTP7 Y',
 'A0A2S8F4W0 E',
 'Q9H310 M',
 'W0DZX1 E',
 'Q221S8 Y',
 'Q6ND36 Y',
 'A0A2C6C0X3 Y',
 'A0A427KNL6 Y',
 'A7HSN9 E',
 'A0A0X8X7Y7 E',
 'A0A248TDF2 E',
 'A0A5M5PZE2 E',
 'B1Y842 E',
 'D2R647 E',
 'D4H5F9 E',
 'D9QS43 E',
 'H1XV27 E',
 'A0A0A1ZMZ9 E',
 'A0A147GP06 Y',
 'H6RWK9 Y',
 'K9ZG59 Y',
 'M2ALH9 E',
 'A0A423Y4I6 Y',
 'A7S3L2 E',
 'A0AA35XZV0 Y',
 'C7Q1E4 Y',
 'G7WCB6 Y',
 'R7PZ71 Y',
 'A0A1H1U2Q6 Y',
 'A0A562RGZ4 E',
 'F4GED5 Y',
 'A0A0X8NXA9 Y',
 'F3KUN4 Y',
 'C8WSI9 Y',
 'O66395 Y',
 'Q0I445 Y',
 'Q95P70 M',
 'A0A1W2GZ82 E',
 'A0A7U8C744 E',
 'A0A0E3R6S1 Y',
 'A0A1I4ZIZ6 Y',
 'Q6ND34 Y',
 'A0A1G6ABL9 Y',
 'A5D4I5 Y',
 'K9P5D1 Y',
 'A0A1B0ZRL8 E',
 'A7RNC3 E',
 'J1ASR8 Y',
 'L0FU80 E',
 'A0A510HHK8 E',
 'D5AU98 Y',
 'A0AA94HTL8 Y',
 'A6W7U2 Y',
 'F2JYR9 E',
 'M5SY07 Y',
 'Q94CJ2 M',
 'W7QG13 E',
 'A0A1G9P6Q0 E',
 'A0A9Q8L398 Y',
 'Q1QSQ2 E',
 'Q5KPM5 Y',
 'A0A068SVR1 Y',
 'A0A4P7UHQ5 Y',
 'A0A101HKN9 E',
 'A0A1Y6GLJ1 Y',
 'A0A562S8V2 Y',
 'A0A8H6K7L7 Y',
 'A0AA86YS65 Y',
 'E7RJZ0 E',
 'A0A037ZMW1 E',
 'A0A0E3QY86 Y',
 'F4H924 Y',
 'Q8I0L6 M',
 'A0A257T7G4 Y',
 'I0JI83 E',
 'Q45HK8 Y',
 'K8EJ02 Y',
 'Q2WBF7 Y',
 'I4DBY0 Y',
 'A0A142VAD6 Y',
 'A0A482PLH3 Y',
 'Q2IHY5 Y',
 'R4FZE3 E',
 'A0A2A2MCP3 Y',
 'A0A5M8QF12 Y',
 'A0A5A7MAJ9 Y',
 'A0A9P3CXY2 Y',
 'B3MX93 E',
 'B9ACS5 Y',
 'A0A085GI50 Y',
 'A0A1B9K8L2 Y',
 'A0A2X2C038 Y',
 'Q1Z4I4 E',
 'A0A075WG29 E',
 'A0A2S6H643 Y',
 'A0A6M3ZJI1 Y',
 'A1ZGK6 E',
 'A2CCK1 E',
 'C7QGX3 Y',
 'D0LTW3 E',
 'D3PKL4 Y',
 'A0A0S4VNK2 Y',
 'A0A410K1J5 E',
 'D5ASL9 Y',
 'A0A369MRW6 Y',
 'A6GJF5 E',
 'Q9UBD6 M',
 'A0A0A3XTJ3 Y',
 'A0A264VQM8 Y',
 'A0A1Z3MS36 Y',
 'B3PIH2 Y',
 'Q5FLR6 Y',
 'A0A087MGU4 Y',
 'A0A1Y2JH43 Y',
 'L7CG11 Y',
 'Q2RWY7 Q',
 'Q6CRN0 Y',
 'T2IEJ2 E',
 'A0A1B9MBX6 Y',
 'B8J5X4 E',
 'A0A7S0ILH2 Y',
 'A1VIG8 Y',
 'P69681 Y',
 'Q6LKC8 E',
 'Q84KJ7 Y',
 'A0A0H3KTD3 Y',
 'A0A1T4SFK4 Y',
 'D3DJN2 Y',
 'Q2FS34 Y',
 'A0A165MFD1 E',
 'A0A1B9BUZ8 Y',
 'A0A1G5W0P2 Y',
 'A0A2T2Y0D5 Y',
 'H6LKH6 Y',
 'L0KGR8 Y',
 'A0A0A2BBY0 E',
 'A0A0M3AB44 Y',
 'A0A3N0AQL8 Y',
 'A0A854QN45 Y',
 'A7SGD4 E',
 'C1D4X0 Y',
 'U3P8G1 Y',
 'A0A147EQL9 Y',
 'A0A375YPN6 E',
 'A0A533I6R2 Y',
 'A0A1H1BPD6 Y',
 'A0A495DND0 Y',
 'A0A2N0MZ27 Y',
 'A0A2U1SS17 Y',
 'A0A0D7F328 Y',
 'A0A0E3LMT4 E',
 'A0A7U3XVQ4 Y',
 'B1Y6V4 Y',
 'Q6BT62 Y',
 'A0A0S2DQB6 Y',
 'A0A258HS77 Y',
 'A0A5C5TYS5 Y',
 'A0A7U8C2Y6 E',
 'D4H2Y7 E',
 'G4R7P1 E',
 'R1FI09 E',
 'A0A074KZD8 E',
 'A0A2W4ZXC0 Y',
 'A0A1H9RTW8 Y',
 'A0A9E9L9J1 Y',
 'A1SVA8 E',
 'M0D3Q9 E',
 'A0A087EQK8 Y',
 'A0A0E3R4G0 E',
 'A0A369M386 Y',
 'A0A3E2VY88 E',
 'I0WJ97 E',
 'Q6HM26 Y',
 'W0DZS7 Y',
 'A0A0E3BR91 Y',
 'A0A1G6ABK5 E',
 'B7G0Y4 C',
 'B8JBH5 Y',
 'D6Z5V9 E',
 'M5S9B4 E',
 'S0EUS1 T',
 'V4CRP5 E',
 'A0A149UWF2 Y',
 'A0RXK8 Y',
 'B1Y8C9 Y',
 'A0A212AV03 Y',
 'A2BUP4 E',
 'A0A1E5BXA4 E',
 'A7SQ16 E',
 'B0DY50 Y',
 'A0A0S4WFM4 Y',
 'A0A6N4SPH9 E',
 'C5KTM6 E',
 'C9R9J0 Y',
 'Q0F2M5 E',
 'Q2SIR0 E',
 'Q9VFA9 E',
 'A0A4Y4DZN4 Y',
 'A0A977NL43 Y',
 'A0A0A2VPU3 Y',
 'A8MCL4 Y',
 'A0A379A0S9 E',
 'A0A6F8TLE9 Y',
 'Q8GQS1 Y',
 'V3ZVE4 E',
 'A0A1T4SF40 Y',
 'A0A2N7L7C8 E',
 'A0A074ME37 Y',
 'Q8RUT6 C',
 'B0VMH1 Y',
 'Q92BJ7 Y',
 'A0A0L0TDW1 Y',
 'A0A857DDJ7 Y',
 'A0AA92K392 Y',
 'B8GGC3 Y',
 'Q7V4T8 E',
 'A0A0V8M0W6 Y',
 'A0A5C4RNH5 Y',
 'A0A511NGC7 Y',
 'A0A149UP06 Y',
 'A0A4R3A5P7 Y',
 'A0A4U1JNL6 Y',
 'Q21J04 Y',
 'A0AIW5 Y',
 'X5CNT2 Y',
 'A0A2T5IHP0 M',
 'A0A5C6LWQ1 Y',
 'A0A433ZQ80 Y',
 'A7SED8 L',
 'A0A853MG28 E',
 'C0QSY0 Y',
 'H1YF74 E',
 'H6LKX6 E',
 'Q47X17 Y',
 'A0A037ZJY5 Y',
 'A0A1B9MZ78 Y',
 'B3PF77 E',
 'B4HDZ9 E',
 'E6W5C1 E',
 'M1WRK6 -',
 'A0A2G6JLT9 E',
 'A7I8Z2 Y',
 'B2GFN1 Y',
 'D2V6P8 M',
 'F2G6G4 E',
 'A0A1H7CU41 Y',
 'A0A2S5WMT7 Y',
 'A0A4Q2EAG7 Y',
 'Q5KZZ9 E',
 'A0A1I0AQM4 M',
 'A0A1I7FBM5 M',
 'A8AC17 Y',
 'A0A0D2UPA8 Y',
 'A0A4R8GSH7 E',
 'C7NND3 E',
 'D3LBI0 -',
 'I7ZHW3 Y',
 'Q0VPH4 E',
 'A8M670 Y',
 'B0DU91 Y',
 'E4T0A4 Y',
 'F0Y9X3 E',
 'Q0G0A4 Y',
 'A0A2S8FTB5 E',
 'A0LV78 Y',
 'A0A2S8QA29 Y',
 ...]

In [8]:
onethree = alignment[:, 102:103]

In [9]:
onethree = alignment[:, 102:103]

onethr = []
seqot = []

for i in onethree:
    print(i.id, i.seq)
    onethr.append(f"{i.id} {i.seq}")
    seqot.append(i.seq)

A1D2Y5 S
M8E0R3 Q
A0A2G3DSU6 N
A0A328EMN2 N
A0A6A1TYJ4 N
D3RMV7 N
F0J3F9 N
G2ZN72 N
I0KDC6 N
A0A081N2G5 N
A0A144NLT9 K
B4D7W2 K
F3QNA7 N
Q4WHC6 S
Q8JI14 -
A0A395VB65 N
A0A975GIX9 N
Q5UZ98 N
A0A4R4K1P9 N
A0A7T4WEP4 W
C6LBD3 N
D5V7B3 N
A0A4R3ZNW3 S
A9BQZ4 N
A0A642KQG8 V
A9BIZ7 N
K0NJH2 A
Q2IK04 N
T2KJ59 N
A0A1B9M5B8 N
A0A323UE08 N
E8RLT5 N
F6G5I9 N
G3A431 N
G4H971 T
L1J6I4 N
M0J579 N
A0A377PBY1 K
A0A401WUW1 N
L1IYW7 N
A0A315S845 A
A0A6M3ZKU5 I
A0A502GPV4 N
A0A9J9BAE8 N
A1AVV2 N
B1XZU2 I
Q5P1S8 I
A0A0F5EZP7 N
A0A4R7GKA0 N
A0A2T4UWF1 S
A0A3E0X011 N
A0A4R8H081 N
C7LQR9 N
A0A0A2A0Y9 N
A0A0A2A5X1 N
A0A7T5BFQ2 I
A3U857 K
E1V4T3 N
F0J7D3 W
M7XJ51 N
Q1K0H9 N
A0A2S5XAB8 S
A0A366IE34 N
Q1Z695 I
A0A8G2IZM3 N
G3IYW2 N
A0A2G5BGA9 N
A0A5M4AUM9 N
E3HJW8 N
U1PIR6 N
A0A1B9N3H7 N
A0A2S5WV24 S
A0A6U2BIY7 N
A0A833LX85 N
I9P003 N
K8VZC6 N
L1IUV5 N
A0A0K2STQ7 N
A0A2H1HV86 S
Q2GX26 S
A0A074KY88 N
A0A858ZNJ3 N
A0A3P2A7W8 N
A0A7S4GND2 N
O26757 -
Q46G49 K
A0A140NHJ5 N
A0A2S8GF54 N
B1JZ69 N
E5Y678 K
A0A149U2G9 N
A0A9Q5QVI9 N
Q18PF5 -
A0A317FZW2 N
G5EB13 S
Q1YDY8 N
A0A1X4GBG2 N
A0A4Q7Y9I7 S
I0HKQ8 N
A0A097R891 K
A0A7S4GMD8 N
Q488X2 N
U3PCH5 G
A0A378YR15 N
I1YG38 I
F5XN43 S
Q1IWN6 G
A0A1E3PSK5 S
A0A833H2R7 N
A0A2T0XPP2 N
A0A399T909 S
L8GGA0 N
A0A0D8BQX6 Q
A0A1M5ZVP9 N
I5BYV5 N
A0A0K2STH0 N
A0A2N6K4Y5 N
A0A1B9JZS5 K
A0A2W0GQV0 K
A0A369MHK2 N
A0A087L0B9 N
A0A0A2AMW2 N
A0A377PLP5 K
Q6BJI7 S
Q7S5K0 A
Q7Z1M1 N
T2JFS5 N
W0JIB3 N
A0A1V2XMU9 N
A0A2S6GKN5 N
A0A7G5DK18 N
A0A830ZZN8 N
A0A8B4RWH8 N
A0A9Q6P4A5 N
B8ENL9 N
Q9QXP0 -
A0A060URC3 W
A0A2W5HTC3 N
A7S731 N
A0A1Y0UZX2 N
A0A257TE48 I
Q2RVB5 K
Q605Y6 N
A0A918MJ52 N
K6W5X0 A
V4AP67 N
A0A7Z0V0A4 K
C0GKN4 N
A9HMD6 N
B1ZSW9 N
K5DBA0 N
V4REY8 N
A0A0D2KGN8 N
A0A242NIL1 N
A8PXT8 N
B7X047 N
D2ZRW2 N
H1Y7T6 N
Q97L80 K
A0A0S6UHP2 N
A0A323UDG5 N
E3I393 N
A0A4V2X6C2 N
D7G265 N
A6LRS5 K
D8J4C6 N
F2NGJ8 N
A0A0E9NHV4 S
A1CQ21 S
A0A6N2Z556 N
Q0BWD0 N
A0A071MMV1 N
A0A168EVK8 K
B3DUX7 N
F5L8M7 T
G7WJN0 N
Q0BQ69 K
A0A3N2SFS2 K
A0A9Y2AG30 G
A0AA46Q839 N
E8RSE4 N
F6BEI0 N
I1DSU5 N
I4C9L2 N
Q5QVH2 N
A0A068NPW2 N
A0A6J5IRX5 N
A0A3R9Q7C4 K
A3ZT81 N
K0ER80 G
Q0VLH1 N
Q2KZK9 N
R9GM11 N
A0A0T7GZ59 N
A0A1G5PWV0 K
S5ABR8 N
W7QGM4 N
F5Y3C1 N
I8TC71 N
M1P5F0 N
A0A149RYW7 N
A0A1J1JH03 N
A0A1U9Z147 R
A0A243SC06 K
A0A3G9G2C9 N
I4C9L0 K
I4D1H5 N
Q7W7D3 N
A0A0B4M163 -
A0A1M7UEG2 S
A7HT14 N
C8X554 N
A0A127PIQ9 N
A0A1B9JPL5 N
W5WIX6 S
A0AA40J491 N
D8PD01 K
A0A251XU71 S
A0A2N6P374 S
B3QVV5 N
K1K628 N
A0A1E2SKM1 G
A0A1I0BYN1 R
A0A556RTU3 N
A0A829X098 N
D5EP68 N
F0J6E8 N
A0A073CP02 N
A0A127JTU2 N
C7BJG7 N
D2BUJ8 K
B8IZX4 R
I3R0S7 N
A0A3E2TW06 A
B1Y0E5 N
E6ME92 K
A0A251Y3N4 S
A0A380S5X4 N
F0YLV7 N
F8D7H6 N
Q31CR9 N
W0E077 N
A5DYQ2 S
A8LKQ0 N
A0A4Y1MSE7 K
A3TVQ9 N
F2B2B8 N
L0K9M1 N
Q4WT12 S
Q8ERT9 N
A0A1H3WA00 N
A0A1U9YY82 N
A1DG05 S
B8GGC1 N
F3ZVV4 N
P69680 N
Q0G2T1 N
A0A3T0SZ22 S
A0A4R2Z2K6 N
L1IYP4 Q
Q46HB1 N
A0A149QAW7 N
A0A1Y4L5P0 N
A0A6B8N021 K
D5EP71 N
V5U2Z4 K
A0A0E3QYF3 N
A0A0K2STK6 N
A0A8H7U3I1 S
A0A062IU58 K
A0A178TA08 Q
A0A3G9G4Q4 N
A0A6H9FPY5 N
A1C5Z7 S
A0A0A1ZJU5 N
A0A258HPP1 N
G0H0Z6 N
A0A2Z4MD56 T
G0EFF3 R
E2SD33 S
E4TJ50 -
A0A016XCG9 N
A0A2S5Y0D3 S
K9YN27 N
Q3AFY9 N
Q7N0M6 N
W8KM07 N
A0A0G9HEC5 N
A5UJR1 N
A0A9Q9D9I3 N
B9SXC7 W
C0QTA4 S
A0A176XNC5 N
A0A317G0I6 N
A0A2S5CTX8 N
U2EN72 N
A0A248LNW8 I
A0A4P8HC89 S
G7UUY6 N
A0A0E3WZH5 N
A0A165K0X5 N
D3FBG3 N
Q608B6 I
A0A854Q6X9 N
H2IZ00 N
A0A4V0XUI3 N
A0A7S4GNJ2 N
A0A2S5WX34 S
C1D6X6 D
A0A418VIJ8 N
A0A857DMN9 R
Q7T3R4 -
R1D1H4 N
T2J0N1 N
A0A419AVL2 N
K0K7J4 S
A0A4U1K1W1 N
A0A9R0NTP8 S
B0RC35 S
C8XB51 S
E4NS62 N
R9PMC6 I
A0A1R1IDV3 N
A0A2N6JV02 N
A7MFK3 K
B0BZN3 N
F7ZEU9 N
K9P718 N
Q82X47 -
Q8RUE9 -
A0A0M2LU39 N
A0A3N1VXY4 N
A0A370FPU0 N
A0A7G5DPV1 N
A9UR54 N
F0S0G1 N
K9W4V5 N
A0A015YIP3 N
A0A291PMC6 N
G8R7U9 N
U1H1F7 N
A0A021VMC6 S
A0A855F5Y8 K
A0A2W5VAZ2 N
M0MDP9 N
A0A1X3RP39 K
A0A653N397 N
A0A8G2F718 N
F4B548 Y
I0ICG0 N
A0A009TDB1 K
A0A1G7DX68 N
E4YA63 N
Q2W5V2 I
Q3AP28 N
Q9BLG3 S
A0A0D5YN10 K
A0A0L0S493 N
H1YCC3 K
L8JUH3 N
A0A0E3SHQ9 N
A0A366XFS8 N
E6VIW4 N
F6FRU9 S
A1VIM5 S
E0TGP9 N
A0A0E3SP24 K
A0A8H6NAG3 S
B8FGW0 K
C3X1J1 N
D9SI36 I
E0TCV4 N
E4U5Z1 K
A0A094W9G3 N
A0A7G5EC77 N
A0A482TED1 N
A0A4Q2QWS1 N
A3PAY4 N
A0A173R3W6 N
A0A1B9BUU6 W
A0A495D4X4 N
A0A833GZR2 N
D0L8H3 N
F4XTK4 N
I4D6Z7 K
L8H844 N
A0A0S6UEK9 N
A0A1M6ZMI3 N
U1SIR9 A
A0A066ZTE4 N
A9DQM8 N
A0A0A0D6K5 N
D6E7B3 N
A0A562USB9 N
C7LW87 N
G0JRG6 W
A0A1X6N3Q5 N
A0A1Y4LM49 N
B7FSA7 N
E1QIU3 N
H2CDR5 N
Q1K433 N
Q1QS12 N
Q7T070 -
A0A0H3DR67 N
A5CRL2 S
A0A836M2B6 K
E6SF19 S
I2GD40 N
Q18ES8 N
A0A060UWC8 W
A0A0U1NJW3 N
A0A7R6PER3 N
A4G1J2 N
A9AUR8 N
C1N5A7 N
D3S2L0 N
F8IJE0 N
A0A0D2LEF5 S
A0A1H1MB73 S
W7QGE0 N
G2T1Y3 N
L7CG99 N
A0A1I0C958 N
A0KPE9 N
A9V5W4 -
F5RGM7 N
A0A1C6Z081 K
A0A1D3GAE9 N
A0A410JZR4 N
A8N2H6 S
I1YJH7 N
A0A2G5BI87 N
A0A2N6NEK4 S
A0A1Y0HX98 S
C3YB74 N
Q1H0G2 N
Q2FQT3 N
S0APH6 Y
A0A075WEB4 N
A0A172RYW3 N
I3C0V3 N
A0A556SRH6 N
A0A7U4DN04 N
A0A1V3SSW1 N
Q466Y3 N
A0A0A2ZRL7 N
A0A0H3LUA3 N
A4G0C5 N
A5E3X2 H
A8P923 N
B8EMQ8 N
D0MFE9 K
A0A060HFT5 N
A0A060JMP6 S
A0A8E2UDJ3 S
I4D6Z9 N
Q13E03 N
Q1JXS5 K
A0A076PL76 N
A0A6N2TIA4 N
Q1AUG3 I
A0A098S5Y7 N
A0A7S4GNF3 N
A0A5J6WQU1 N
A2SS52 N
M9RKT6 N
A0A2K1RA77 W
A0A2K1RA81 W
A0A2S0JW39 N
A0A2T9X1V4 Y
D3F545 V
A0A1E3PQH0 N
A0A1J5JH24 N
C4Y298 S
Q3B6Q2 N
Q7TNN9 -
A0A4Y7XC43 N
A0A5B2V3B9 N
B9L7N1 N
C7M2A9 W
D2V6Q5 N
E4T3F7 N
F2YIC4 -
Q0G0A3 N
A0A424WAH3 N
B8ZYW3 V
U7VB41 K
A0A7S0KKL8 N
A0A1C7EL50 N
A0A6G9Y3Q0 N
A0A6S5K4J1 K
G0LFE3 N
J9VXX9 N
V4RHR4 N
A0A0D7F2Y9 N
A0A1S8D478 N
Q47K18 N
B9SWW9 W
L8H5K0 -
A0A369N7Y3 N
A0A399NT81 S
B0SLB7 K
B4CV94 N
E1IF27 N
G2PRJ6 N
A0A202B535 N
A0A2M9D7S8 K
Q6LMI6 N
K2JVF8 N
Q1Q357 N
B8FDY8 N
B8FL88 N
E3H8A6 G
H8L2Q4 N
A0A248LMH8 N
A0A5C5BWI6 N
L1INN6 N
M7NFH3 T
A0A060URB8 N
K9W6F3 R
A0A7S0D560 N
D2Q0J8 S
A0A251YU48 S
A0A6H9GEE4 N
A0A8F5ZDT8 N
C1G973 S
M0D580 N
A0A1Y5E3E3 N
A0A328Q6M1 N
Q7UGU7 N
A0A660CH85 S
E4T3F3 N
A0A6H9GFU4 N
A3XNG6 N
B9LU00 N
E4RTK5 N
H6LKH9 N
Q0AT01 N
A0A330GB00 K
A0A657K391 N
Q2N625 N
E3GI40 N
F4Y3C5 N
A0A017SYR8 N
A0A494JB70 N
D4XLN6 N
Q1YDY7 N
A0A2G5RQK9 Q
A0A369NYJ2 N
A0A1Q2C7H7 N
C5LAG4 N
K0F9X7 N
Q1K3N8 N
A0A2V4EA49 N
A0A562BXM4 N
A0A4D6KHD1 N
A0A4R6DFU8 S
A0A4R7VEK0 N
G0AFH4 N
K5CFE5 N
Q1H483 N
A0A063Y780 N
A0A1W5PRD1 -
Q2YLQ6 N
U5C4L4 N
A0A8G2F3G4 N
D5ELM4 N
J2ZGN6 N
Q84KJ6 W
A0A211ZGL5 N
A0A373FQ71 N
A0A2S8FR08 N
A0A7T2W1B3 N
D4F313 N
F4KY49 N
A0A149V596 N
A0A2S7YPJ9 S
A0A2S0Q8P1 N
Q7UYZ3 N
J7ITF6 N
Q9NIV0 -
A0A1D8UWJ6 N
C1MHX0 Q
F3QPR6 N
A0A068NV61 N
A0A1B9LFW3 N
A0A7H8UK07 N
A0AA91Q161 S
A0AA92EGF5 N
G7WFX4 N
M9RJS5 N
A0A1B9KID3 N
A0A3E2UCG9 A
S9QZ09 N
A0A2S8GSU9 N
J7IVQ1 N
F0JGZ1 N
F2AUF4 N
A0A2S8GEJ5 N
C6WEW7 S
E5Y789 R
J4KM12 S
Q21P82 N
Q5P470 N
A0A0H3H4I7 K
D5VJ32 N
C8WLL8 N
D2R355 N
H2CJI0 N
A0A2S5WGI8 N
C1GR74 S
A0A2S6GKF6 N
A0A8H4GS02 S
A0NJ07 N
C6CBB1 K
Q7NQY2 N
A0A173R3X4 N
A0A2G3E8V2 N
A0A2S6H6B7 N
A0A316BQ38 N
A0A9W3LFI9 N
B4S394 K
F0ZPL3 N
G0VI62 H
A0A177W826 N
A0A1H8D0R8 -
Q07UM3 N
S3K1S2 K
A0A4V3ALP8 N
A0A6G9XJV9 G
F7NPQ3 N
J4UGB7 S
J7L3W8 S
A0A0A2B651 N
A0A258FTB0 N
A4FMG0 G
B7GKP4 Q
C3YB73 N
C5BWX7 S
I5C044 N
T2KGT3 N
A0A060UN76 I
A0A258FS85 N
A0A975BTN0 N
A1SY01 N
A8G2S3 N
B2IJT1 K
C0Z5S5 T
Q21CP1 N
A0A0A2C6L1 N
A0A1H9M798 N
D5E995 N
C5CIT6 -
D3RN22 I
A0A5M4ATH9 N
A0A9J9ES23 I
C6XKC2 N
D2SE15 S
K9U8C7 N
Q59UP8 H
A0A1H4KAQ7 N
A0A1I5GN22 S
V5E0F3 N
C1N6X9 N
Q6CRN1 H
R1EGK6 N
W0F0I7 K
A0A088E6Q7 F
A0A318FY98 K
D7E934 N
K9ZLY2 N
M1V7W3 N
A0A2K3DPU7 -
A0A2S7YIM5 S
F3ZYD6 N
F5R974 I
I6Z905 A
A1SZ12 N
A2BP62 N
B8FZP7 N
K1LDP0 N
A0A3S9N9F3 N
A2C095 N
C6DB68 N
G0JRG9 W
J7J5E7 N
Q1K8A3 S
Q2RM12 N
Q7NCB8 N
A0A2S0P9T4 N
B0DU93 S
D0LAL7 S
D0MFE8 N
I5AZQ4 N
Q2YBP7 -
Q81GN5 K
A0A1B9NQ91 N
A0A1T4SFY6 S
A0A6H9FYW4 N
A8ZQD5 N
E2SD44 S
F2JZ83 I
H6LFQ2 N
I3Z3H7 N
A0A1M6JKY3 K
A0A2J7TJ33 N
Q7SEH0 S
L8GFX3 N
Q5KAF6 N
K9YJQ3 N
Q5FA36 N
A6M3G0 N
D9SI59 N
B7G0Y1 N
C1MX19 N
D5T4N9 N
A0A1B9M1A9 N
A0A4R3NVT3 N
A0A420KGW4 N
B0SRS8 N
D4GLQ6 N
Q0ACK1 N
S0ET45 N
A0A1G7H8X3 S
A0A1X4G8K1 N
F8E6R1 N
Q0G2V0 N
A0A5P9P1L2 N
A0A979GQ79 N
A6VE60 N
B9SA70 W
E3H8C9 N
M2A398 N
A0A1J5NTP7 N
A0A2S8F4W0 N
Q9H310 -
W0DZX1 I
Q221S8 N
Q6ND36 N
A0A2C6C0X3 N
A0A427KNL6 N
A7HSN9 I
A0A0X8X7Y7 N
A0A248TDF2 T
A0A5M5PZE2 V
B1Y842 I
D2R647 N
D4H5F9 N
D9QS43 A
H1XV27 N
A0A0A1ZMZ9 N
A0A147GP06 N
H6RWK9 S
K9ZG59 N
M2ALH9 N
A0A423Y4I6 K
A7S3L2 N
A0AA35XZV0 N
C7Q1E4 S
G7WCB6 N
R7PZ71 N
A0A1H1U2Q6 S
A0A562RGZ4 A
F4GED5 N
A0A0X8NXA9 N
F3KUN4 N
C8WSI9 K
O66395 N
Q0I445 N
Q95P70 -
A0A1W2GZ82 N
A0A7U8C744 N
A0A0E3R6S1 N
A0A1I4ZIZ6 N
Q6ND34 N
A0A1G6ABL9 K
A5D4I5 N
K9P5D1 K
A0A1B0ZRL8 N
A7RNC3 N
J1ASR8 N
L0FU80 N
A0A510HHK8 I
D5AU98 S
A0AA94HTL8 R
A6W7U2 S
F2JYR9 N
M5SY07 N
Q94CJ2 -
W7QG13 N
A0A1G9P6Q0 N
A0A9Q8L398 N
Q1QSQ2 N
Q5KPM5 N
A0A068SVR1 N
A0A4P7UHQ5 R
A0A101HKN9 N
A0A1Y6GLJ1 K
A0A562S8V2 N
A0A8H6K7L7 S
A0AA86YS65 N
E7RJZ0 N
A0A037ZMW1 N
A0A0E3QY86 K
F4H924 N
Q8I0L6 -
A0A257T7G4 W
I0JI83 T
Q45HK8 N
K8EJ02 N
Q2WBF7 K
I4DBY0 N
A0A142VAD6 N
A0A482PLH3 N
Q2IHY5 K
R4FZE3 Q
A0A2A2MCP3 -
A0A5M8QF12 S
A0A5A7MAJ9 N
A0A9P3CXY2 K
B3MX93 N
B9ACS5 N
A0A085GI50 K
A0A1B9K8L2 K
A0A2X2C038 K
Q1Z4I4 N
A0A075WG29 N
A0A2S6H643 N
A0A6M3ZJI1 N
A1ZGK6 N
A2CCK1 N
C7QGX3 S
D0LTW3 N
D3PKL4 N
A0A0S4VNK2 N
A0A410K1J5 N
D5ASL9 N
A0A369MRW6 N
A6GJF5 N
Q9UBD6 -
A0A0A3XTJ3 N
A0A264VQM8 N
A0A1Z3MS36 K
B3PIH2 N
Q5FLR6 N
A0A087MGU4 N
A0A1Y2JH43 N
L7CG11 N
Q2RWY7 G
Q6CRN0 H
T2IEJ2 N
A0A1B9MBX6 N
B8J5X4 N
A0A7S0ILH2 Q
A1VIG8 N
P69681 N
Q6LKC8 I
Q84KJ7 W
A0A0H3KTD3 N
A0A1T4SFK4 N
D3DJN2 D
Q2FS34 N
A0A165MFD1 N
A0A1B9BUZ8 N
A0A1G5W0P2 N
A0A2T2Y0D5 K
H6LKH6 N
L0KGR8 N
A0A0A2BBY0 N
A0A0M3AB44 N
A0A3N0AQL8 N
A0A854QN45 N
A7SGD4 N
C1D4X0 N
U3P8G1 S
A0A147EQL9 S
A0A375YPN6 N
A0A533I6R2 N
A0A1H1BPD6 S
A0A495DND0 N
A0A2N0MZ27 N
A0A2U1SS17 N
A0A0D7F328 N
A0A0E3LMT4 N
A0A7U3XVQ4 K
B1Y6V4 N
Q6BT62 H
A0A0S2DQB6 N
A0A258HS77 N
A0A5C5TYS5 N
A0A7U8C2Y6 I
D4H2Y7 N
G4R7P1 N
R1FI09 N
A0A074KZD8 N
A0A2W4ZXC0 K
A0A1H9RTW8 N
A0A9E9L9J1 N
A1SVA8 I
M0D3Q9 N
A0A087EQK8 K
A0A0E3R4G0 N
A0A369M386 N
A0A3E2VY88 A
I0WJ97 N
Q6HM26 K
W0DZS7 N
A0A0E3BR91 N
A0A1G6ABK5 I
B7G0Y4 N
B8JBH5 K
D6Z5V9 N
M5S9B4 N
S0EUS1 N
V4CRP5 N
A0A149UWF2 N
A0RXK8 N
B1Y8C9 N
A0A212AV03 N
A2BUP4 N
A0A1E5BXA4 N
A7SQ16 N
B0DY50 N
A0A0S4WFM4 N
A0A6N4SPH9 N
C5KTM6 N
C9R9J0 N
Q0F2M5 V
Q2SIR0 I
Q9VFA9 N
A0A4Y4DZN4 S
A0A977NL43 N
A0A0A2VPU3 S
A8MCL4 Y
A0A379A0S9 N
A0A6F8TLE9 K
Q8GQS1 N
V3ZVE4 N
A0A1T4SF40 N
A0A2N7L7C8 I
A0A074ME37 K
Q8RUT6 N
B0VMH1 K
Q92BJ7 N
A0A0L0TDW1 N
A0A857DDJ7 H
A0AA92K392 N
B8GGC3 N
Q7V4T8 N
A0A0V8M0W6 N
A0A5C4RNH5 K
A0A511NGC7 N
A0A149UP06 N
A0A4R3A5P7 N
A0A4U1JNL6 S
Q21J04 N
A0AIW5 N
X5CNT2 W
A0A2T5IHP0 -
A0A5C6LWQ1 N
A0A433ZQ80 N
A7SED8 -
A0A853MG28 N
C0QSY0 N
H1YF74 N
H6LKX6 N
Q47X17 N
A0A037ZJY5 N
A0A1B9MZ78 N
B3PF77 N
B4HDZ9 N
E6W5C1 N
M1WRK6 N
A0A2G6JLT9 I
A7I8Z2 N
B2GFN1 G
D2V6P8 -
F2G6G4 N
A0A1H7CU41 N
A0A2S5WMT7 S
A0A4Q2EAG7 K
Q5KZZ9 Q
A0A1I0AQM4 -
A0A1I7FBM5 -
A8AC17 R
A0A0D2UPA8 N
A0A4R8GSH7 I
C7NND3 N
D3LBI0 N
I7ZHW3 N
Q0VPH4 N
A8M670 G
B0DU91 S
E4T0A4 N
F0Y9X3 N
Q0G0A4 N
A0A2S8FTB5 N
A0LV78 N
A0A2S8QA29 N
D3PAH1 N
A0A6T9XUR2 N
A7I8Z4 N
B0CQX4 S
D6TCH6 N
K0N2R5 N
K8W1E2 N
A0A1G6ABX1 N
A0A2S5WZU0 S
D6SPD1 N
M5S735 N
U1PPI7 N
A0A0C6P439 N
A0A257SYX3 W
A7NKH2 N
Q1Q879 N
A4BAE1 N
D2BIB2 N
A0A2K3DQF8 N
A0A7V8IKS6 N
A0A7U3YMN6 N
Q9REX3 N
A0A2S5WUP6 N
D6TFE1 N
Q3Z7F9 N
A0A0L8BVU4 N
A0A2R4MBA2 N
A0A2I0UUY1 N
G0JRQ3 I
A0A067Z3S3 N
A0A161SKF4 S
A4BMY5 N
B0XVV6 S
K2IMJ7 N
P40260 S
A0A414NWT8 N
A0A8F5VN39 N
A0A837C6X5 N
C9KKP2 N
D4XSW0 I
J9Z839 W
Q07UM1 N
Q60BI2 N
A0A0L0STS6 N
A0A366WYI9 N
A0A251YFS0 S
F7ZJZ1 N
J3EXK0 N
Q0F2M7 N
A0A016XDZ5 K
A0A1A0DHK0 -
G0IYI2 N
G5EB09 S
Q60C43 N
A0A034WGQ2 N
A0A2A2M8K7 K
A0A066ZRQ5 N
B3QRJ4 N
A0A165MAC2 N
G8JUJ2 H
R9PI53 N
A0A059XXR1 W
A0A075JZ35 N
F2NNQ0 K
O04161 N
A0A2A7U6W1 N
A0A7M6UUM4 -
A0A420WC79 N
A0A7G5DKA9 N
A0A7S4LPS8 N
A0A7U4E420 N
C8WZE0 N
E4TRS4 N
A0A1W2H3F0 N
A0A2T4XZC1 K
A0A248LNK5 D
A0A251XJT0 S
A0A4P6UIJ8 K
A0A7G5DPV0 N
B0DXT9 S
J0S2I0 N
A0A071M4L5 N
A0A0B4E6X7 N
K9WSX4 N
K9WT03 N
A9BTK1 N
D5UD26 S
M1NZT5 N
A0A0B5FNH4 N
A0A8H7P8U1 N
A0A495WJM6 N
A0A075JIN0 S
A0A091AXI3 N
A0A381CAY8 K
A0A3E2T713 N
E1SLM7 N
M9YAI9 N
A0A0T7FAP8 N
A0A1B9MYL7 N
A0A1G5RZU9 N
A0A1G7VM92 N
A0A1J5NNB8 N
A0A3E2UHE6 A
G7WA28 N
H5UND3 S
A0A0B4DUR9 N
A0A149QSR6 N
W0DYY3 N
M1SJL5 N
V4RK08 N
A0A063Y394 N
A0A1B9JHS5 N
A0A5M4B0G1 N
A0A6C8LST1 N
A0A8E2R1Y5 S
A6DUG4 N
B0CXH8 N
F4D1J0 S
A0A1L3F1X5 N
A0A257T8W6 W
U5DEY6 N
A4CMI3 N
A0A011U1K7 N
A0A401X433 N
Q2S8H9 N
F7ZJM0 N
L0JT30 N
Q22947 -
Q63EK5 K
A0A1I4W3A0 S
D0KXQ0 I
A6LV49 N
C7LW88 N
L0KW14 N
S0G181 N
A0A1W9KSU5 N
A0A377I7W9 N
E5B358 N
G0V8D6 S
L1IHZ8 N
A7HSP2 K
C1A872 S
A0A6H9GWG4 N
F0S3Z6 I
A0A0P6VSR8 N
A0A1Y0V4A5 -
E1QFA8 N
E4N1T5 H
R1EDV9 N
B0DFJ4 N
D2RU19 N
A0A2H4U5R1 N
A0A2T1N7R1 N
A0A5J6WPP9 I
A1B3N0 N
A0A142NNN1 S
A0A172YCA7 N
Q9M6N7 W
V5BYZ7 N
A0A060HN92 K
A0A2N7LCD7 N
F0ZCX7 -
Q6ARH0 N
A0A009PYN3 K
A0A075WBP9 N
A0A9E9LXV9 N
A0A089ZBW5 N
A0A6P4JM51 N
A0A2S5X482 S
F5ISF6 N
Q0ARJ4 N
A0A0H2XSU4 N
A0A290XBB5 N
A8NAG3 N
B0SL05 N
G8JTW0 S
A0A9W5JBA9 N
A2SPS8 K
A0A5C5TUT2 N
C1F584 N
C7R314 S
H2CLF7 N
A0A401WXG0 -
A0A542XGT4 G
A0A0S2FHD7 N
A0A2S5YID7 S
A0A149RQX0 N
A6DN47 N
A0A225CMT8 S
G4QHD2 N
K9YR86 N
A0A174SD65 N
D7UQE2 -
D9QPC8 N
G7WDB5 N
G8TK77 N
K9Z0D3 N
A0A101DCS3 N
A0A172YBR4 N
Q1L727 N
A0A318QZ80 N
A0A8H6MPB9 S
N1WR17 N
Q2J376 N
A0A0D2NYP3 N
A0A2I1M481 A
I0HGY4 G
A4ABK3 N
C9RS76 N
F2JTN3 N
G0JRH4 N
M5U2P1 N
Q1PX09 N
Q2HD43 S
A0A165BP25 K
A0A2C9CK98 N
G0J614 N
M4VEJ9 -
U5C2K4 N
A0A1S1HM83 -
F0RHS0 N
A0A5M4AWD2 N
B7FW68 N
G9Y5B0 K
Q5FSX6 N
A0A149TSA9 N
A0A1G7UZX2 I
A3ZZL7 N
A9WHW6 N
B7FTM9 N
A0A1H4DJ49 N
A0AA35XVN2 N
A0A2T0GTU1 G
A0A4R3ZZ35 S
A0A855EH99 N
D9QPE5 N
M5SYZ1 N
Q0VQH6 N
A0A096EEV9 N
A0A2R3IMJ8 N
Q6QH01 T
E0SD83 K
I5B3H0 N
X5DX97 S
A0A7T2S0Z6 N
A9B874 N
A0A2R4TRE0 N
D3F0Z1 I
A0A4R2M206 N
A4BEP1 I
P41948 H
A0A1S1HRJ0 N
A0A2S5V2F6 N
B9WDK0 S
C8XBX8 S
R8VWI7 N
A0A4R3NLV5 N
A6XBM2 -
A8HSA2 T
C3X831 N
U2WTW8 Q
A0A1M6BPM0 N
A0A4P6UIK6 N
A0A4R5U5V1 N
A0RUZ2 N
I4CCD1 N
J1L5M8 N
Q89WR5 N
A0A068TC78 N
A0A166IS52 N
D3PE53 K
A0A077EFU9 N
A0A160KTE9 S
A0A1Y5E8I7 N
A0A6H9GLV4 N
G3IYW0 N
G7WFX2 N
Q6BK68 S
Q9QUT0 -
A0A1E5C7W4 I
A0A1Y3U5V2 N

In [10]:
os = alignment[:, 105:106]

In [11]:
onesix = []
seqos = []


for i in os:
    print(i.id, i.seq)
    onesix.append(f"{i.id} {i.seq}")
    seqos.append(i.seq)

A1D2Y5 S
M8E0R3 S
A0A2G3DSU6 D
A0A328EMN2 S
A0A6A1TYJ4 S
D3RMV7 S
F0J3F9 A
G2ZN72 S
I0KDC6 S
A0A081N2G5 L
A0A144NLT9 S
B4D7W2 A
F3QNA7 S
Q4WHC6 S
Q8JI14 -
A0A395VB65 D
A0A975GIX9 N
Q5UZ98 T
A0A4R4K1P9 S
A0A7T4WEP4 N
C6LBD3 D
D5V7B3 I
A0A4R3ZNW3 N
A9BQZ4 S
A0A642KQG8 T
A9BIZ7 D
K0NJH2 A
Q2IK04 V
T2KJ59 D
A0A1B9M5B8 S
A0A323UE08 S
E8RLT5 A
F6G5I9 S
G3A431 S
G4H971 T
L1J6I4 C
M0J579 D
A0A377PBY1 S
A0A401WUW1 A
L1IYW7 S
A0A315S845 N
A0A6M3ZKU5 D
A0A502GPV4 S
A0A9J9BAE8 L
A1AVV2 S
B1XZU2 G
Q5P1S8 D
A0A0F5EZP7 S
A0A4R7GKA0 S
A0A2T4UWF1 S
A0A3E0X011 L
A0A4R8H081 D
C7LQR9 D
A0A0A2A0Y9 V
A0A0A2A5X1 V
A0A7T5BFQ2 D
A3U857 S
E1V4T3 L
F0J7D3 N
M7XJ51 T
Q1K0H9 L
A0A2S5XAB8 S
A0A366IE34 S
Q1Z695 D
A0A8G2IZM3 S
G3IYW2 S
A0A2G5BGA9 S
A0A5M4AUM9 S
E3HJW8 S
U1PIR6 D
A0A1B9N3H7 S
A0A2S5WV24 S
A0A6U2BIY7 D
A0A833LX85 V
I9P003 L
K8VZC6 S
L1IUV5 S
A0A0K2STQ7 V
A0A2H1HV86 N
Q2GX26 A
A0A074KY88 I
A0A858ZNJ3 S
A0A3P2A7W8 S
A0A7S4GND2 V
O26757 -
Q46G49 S
A0A140NHJ5 A
A0A2S8GF54 D
B1JZ69 A
E5Y678 T
A0A149U2G9 A
A0A9Q5QVI9 N
Q18PF5 -
A0A317FZW2 D
G5EB13 S
Q1YDY8 L
A0A1X4GBG2 V
A0A4Q7Y9I7 N
I0HKQ8 S
A0A097R891 S
A0A7S4GMD8 D
Q488X2 L
U3PCH5 R
A0A378YR15 S
I1YG38 D
F5XN43 N
Q1IWN6 N
A0A1E3PSK5 S
A0A833H2R7 D
A0A2T0XPP2 D
A0A399T909 S
L8GGA0 N
A0A0D8BQX6 S
A0A1M5ZVP9 D
I5BYV5 I
A0A0K2STH0 V
A0A2N6K4Y5 N
A0A1B9JZS5 S
A0A2W0GQV0 S
A0A369MHK2 N
A0A087L0B9 S
A0A0A2AMW2 V
A0A377PLP5 S
Q6BJI7 S
Q7S5K0 T
Q7Z1M1 D
T2JFS5 V
W0JIB3 T
A0A1V2XMU9 A
A0A2S6GKN5 S
A0A7G5DK18 S
A0A830ZZN8 S
A0A8B4RWH8 S
A0A9Q6P4A5 S
B8ENL9 S
Q9QXP0 -
A0A060URC3 N
A0A2W5HTC3 A
A7S731 D
A0A1Y0UZX2 A
A0A257TE48 D
Q2RVB5 A
Q605Y6 S
A0A918MJ52 I
K6W5X0 N
V4AP67 D
A0A7Z0V0A4 S
C0GKN4 D
A9HMD6 A
B1ZSW9 S
K5DBA0 D
V4REY8 L
A0A0D2KGN8 S
A0A242NIL1 S
A8PXT8 M
B7X047 S
D2ZRW2 N
H1Y7T6 S
Q97L80 G
A0A0S6UHP2 V
A0A323UDG5 A
E3I393 S
A0A4V2X6C2 S
D7G265 D
A6LRS5 S
D8J4C6 T
F2NGJ8 N
A0A0E9NHV4 S
A1CQ21 S
A0A6N2Z556 D
Q0BWD0 L
A0A071MMV1 A
A0A168EVK8 S
B3DUX7 S
F5L8M7 T
G7WJN0 D
Q0BQ69 A
A0A3N2SFS2 S
A0A9Y2AG30 N
A0AA46Q839 S
E8RSE4 A
F6BEI0 D
I1DSU5 L
I4C9L2 S
Q5QVH2 L
A0A068NPW2 S
A0A6J5IRX5 A
A0A3R9Q7C4 G
A3ZT81 D
K0ER80 N
Q0VLH1 L
Q2KZK9 S
R9GM11 S
A0A0T7GZ59 S
A0A1G5PWV0 S
S5ABR8 L
W7QGM4 D
F5Y3C1 S
I8TC71 S
M1P5F0 L
A0A149RYW7 A
A0A1J1JH03 V
A0A1U9Z147 S
A0A243SC06 I
A0A3G9G2C9 A
I4C9L0 S
I4D1H5 S
Q7W7D3 S
A0A0B4M163 -
A0A1M7UEG2 N
A7HT14 D
C8X554 G
A0A127PIQ9 S
A0A1B9JPL5 S
W5WIX6 N
A0AA40J491 S
D8PD01 G
A0A251XU71 S
A0A2N6P374 Q
B3QVV5 S
K1K628 S
A0A1E2SKM1 R
A0A1I0BYN1 S
A0A556RTU3 S
A0A829X098 A
D5EP68 I
F0J6E8 S
A0A073CP02 V
A0A127JTU2 S
C7BJG7 S
D2BUJ8 S
B8IZX4 S
I3R0S7 D
A0A3E2TW06 T
B1Y0E5 A
E6ME92 N
A0A251Y3N4 S
A0A380S5X4 V
F0YLV7 D
F8D7H6 T
Q31CR9 V
W0E077 D
A5DYQ2 S
A8LKQ0 L
A0A4Y1MSE7 A
A3TVQ9 L
F2B2B8 S
L0K9M1 D
Q4WT12 S
Q8ERT9 T
A0A1H3WA00 S
A0A1U9YY82 L
A1DG05 S
B8GGC1 S
F3ZVV4 N
P69680 S
Q0G2T1 C
A0A3T0SZ22 S
A0A4R2Z2K6 S
L1IYP4 S
Q46HB1 V
A0A149QAW7 A
A0A1Y4L5P0 D
A0A6B8N021 S
D5EP71 S
V5U2Z4 S
A0A0E3QYF3 T
A0A0K2STK6 V
A0A8H7U3I1 S
A0A062IU58 S
A0A178TA08 S
A0A3G9G4Q4 A
A0A6H9FPY5 V
A1C5Z7 S
A0A0A1ZJU5 V
A0A258HPP1 A
G0H0Z6 D
A0A2Z4MD56 T
G0EFF3 S
E2SD33 N
E4TJ50 -
A0A016XCG9 S
A0A2S5Y0D3 S
K9YN27 V
Q3AFY9 N
Q7N0M6 S
W8KM07 L
A0A0G9HEC5 S
A5UJR1 N
A0A9Q9D9I3 S
B9SXC7 N
C0QTA4 N
A0A176XNC5 S
A0A317G0I6 D
A0A2S5CTX8 T
U2EN72 L
A0A248LNW8 D
A0A4P8HC89 N
G7UUY6 S
A0A0E3WZH5 V
A0A165K0X5 T
D3FBG3 N
Q608B6 D
A0A854Q6X9 S
H2IZ00 S
A0A4V0XUI3 V
A0A7S4GNJ2 V
A0A2S5WX34 S
C1D6X6 T
A0A418VIJ8 S
A0A857DMN9 S
Q7T3R4 -
R1D1H4 D
T2J0N1 V
A0A419AVL2 S
K0K7J4 N
A0A4U1K1W1 S
A0A9R0NTP8 N
B0RC35 S
C8XB51 N
E4NS62 D
R9PMC6 D
A0A1R1IDV3 S
A0A2N6JV02 V
A7MFK3 S
B0BZN3 V
F7ZEU9 L
K9P718 V
Q82X47 -
Q8RUE9 -
A0A0M2LU39 S
A0A3N1VXY4 S
A0A370FPU0 S
A0A7G5DPV1 L
A9UR54 D
F0S0G1 N
K9W4V5 V
A0A015YIP3 D
A0A291PMC6 A
G8R7U9 S
U1H1F7 A
A0A021VMC6 N
A0A855F5Y8 S
A0A2W5VAZ2 S
M0MDP9 T
A0A1X3RP39 S
A0A653N397 S
A0A8G2F718 D
F4B548 N
I0ICG0 I
A0A009TDB1 S
A0A1G7DX68 S
E4YA63 D
Q2W5V2 D
Q3AP28 G
Q9BLG3 D
A0A0D5YN10 S
A0A0L0S493 S
H1YCC3 L
L8JUH3 T
A0A0E3SHQ9 T
A0A366XFS8 S
E6VIW4 S
F6FRU9 N
A1VIM5 N
E0TGP9 L
A0A0E3SP24 S
A0A8H6NAG3 S
B8FGW0 G
C3X1J1 S
D9SI36 D
E0TCV4 L
E4U5Z1 N
A0A094W9G3 I
A0A7G5EC77 S
A0A482TED1 D
A0A4Q2QWS1 S
A3PAY4 V
A0A173R3W6 N
A0A1B9BUU6 N
A0A495D4X4 L
A0A833GZR2 D
D0L8H3 N
F4XTK4 V
I4D6Z7 T
L8H844 D
A0A0S6UEK9 G
A0A1M6ZMI3 D
U1SIR9 H
A0A066ZTE4 L
A9DQM8 D
A0A0A0D6K5 S
D6E7B3 N
A0A562USB9 L
C7LW87 G
G0JRG6 N
A0A1X6N3Q5 S
A0A1Y4LM49 D
B7FSA7 D
E1QIU3 D
H2CDR5 D
Q1K433 D
Q1QS12 A
Q7T070 -
A0A0H3DR67 S
A5CRL2 S
A0A836M2B6 S
E6SF19 N
I2GD40 S
Q18ES8 D
A0A060UWC8 N
A0A0U1NJW3 L
A0A7R6PER3 L
A4G1J2 S
A9AUR8 S
C1N5A7 D
D3S2L0 N
F8IJE0 T
A0A0D2LEF5 S
A0A1H1MB73 S
W7QGE0 S
G2T1Y3 D
L7CG99 D
A0A1I0C958 D
A0KPE9 S
A9V5W4 -
F5RGM7 S
A0A1C6Z081 S
A0A1D3GAE9 S
A0A410JZR4 N
A8N2H6 S
I1YJH7 L
A0A2G5BI87 S
A0A2N6NEK4 S
A0A1Y0HX98 N
C3YB74 D
Q1H0G2 D
Q2FQT3 S
S0APH6 N
A0A075WEB4 S
A0A172RYW3 N
I3C0V3 D
A0A556SRH6 S
A0A7U4DN04 G
A0A1V3SSW1 I
Q466Y3 T
A0A0A2ZRL7 A
A0A0H3LUA3 S
A4G0C5 D
A5E3X2 S
A8P923 S
B8EMQ8 D
D0MFE9 N
A0A060HFT5 N
A0A060JMP6 S
A0A8E2UDJ3 S
I4D6Z9 T
Q13E03 S
Q1JXS5 S
A0A076PL76 S
A0A6N2TIA4 D
Q1AUG3 N
A0A098S5Y7 I
A0A7S4GNF3 V
A0A5J6WQU1 L
A2SS52 S
M9RKT6 L
A0A2K1RA77 N
A0A2K1RA81 N
A0A2S0JW39 T
A0A2T9X1V4 N
D3F545 N
A0A1E3PQH0 N
A0A1J5JH24 G
C4Y298 S
Q3B6Q2 G
Q7TNN9 -
A0A4Y7XC43 S
A0A5B2V3B9 S
B9L7N1 N
C7M2A9 N
D2V6Q5 G
E4T3F7 N
F2YIC4 -
Q0G0A3 L
A0A424WAH3 S
B8ZYW3 T
U7VB41 T
A0A7S0KKL8 D
A0A1C7EL50 T
A0A6G9Y3Q0 N
A0A6S5K4J1 S
G0LFE3 D
J9VXX9 S
V4RHR4 C
A0A0D7F2Y9 S
A0A1S8D478 A
Q47K18 S
B9SWW9 N
L8H5K0 -
A0A369N7Y3 N
A0A399NT81 S
B0SLB7 S
B4CV94 S
E1IF27 S
G2PRJ6 D
A0A202B535 A
A0A2M9D7S8 S
Q6LMI6 L
K2JVF8 L
Q1Q357 D
B8FDY8 G
B8FL88 D
E3H8A6 D
H8L2Q4 S
A0A248LMH8 S
A0A5C5BWI6 N
L1INN6 D
M7NFH3 S
A0A060URB8 A
K9W6F3 N
A0A7S0D560 S
D2Q0J8 N
A0A251YU48 S
A0A6H9GEE4 V
A0A8F5ZDT8 S
C1G973 S
M0D580 D
A0A1Y5E3E3 S
A0A328Q6M1 N
Q7UGU7 D
A0A660CH85 N
E4T3F3 I
A0A6H9GFU4 N
A3XNG6 D
B9LU00 T
E4RTK5 S
H6LKH9 N
Q0AT01 L
A0A330GB00 S
A0A657K391 S
Q2N625 S
E3GI40 D
F4Y3C5 V
A0A017SYR8 S
A0A494JB70 S
D4XLN6 S
Q1YDY7 S
A0A2G5RQK9 S
A0A369NYJ2 N
A0A1Q2C7H7 N
C5LAG4 D
K0F9X7 N
Q1K3N8 D
A0A2V4EA49 S
A0A562BXM4 S
A0A4D6KHD1 T
A0A4R6DFU8 S
A0A4R7VEK0 S
G0AFH4 S
K5CFE5 S
Q1H483 S
A0A063Y780 L
A0A1W5PRD1 -
Q2YLQ6 S
U5C4L4 T
A0A8G2F3G4 G
D5ELM4 D
J2ZGN6 T
Q84KJ6 N
A0A211ZGL5 S
A0A373FQ71 S
A0A2S8FR08 G
A0A7T2W1B3 N
D4F313 S
F4KY49 S
A0A149V596 A
A0A2S7YPJ9 S
A0A2S0Q8P1 V
Q7UYZ3 S
J7ITF6 S
Q9NIV0 -
A0A1D8UWJ6 A
C1MHX0 T
F3QPR6 S
A0A068NV61 M
A0A1B9LFW3 S
A0A7H8UK07 S
A0AA91Q161 S
A0AA92EGF5 S
G7WFX4 T
M9RJS5 S
A0A1B9KID3 S
A0A3E2UCG9 T
S9QZ09 S
A0A2S8GSU9 S
J7IVQ1 D
F0JGZ1 A
F2AUF4 D
A0A2S8GEJ5 D
C6WEW7 N
E5Y789 S
J4KM12 S
Q21P82 L
Q5P470 S
A0A0H3H4I7 S
D5VJ32 S
C8WLL8 S
D2R355 G
H2CJI0 D
A0A2S5WGI8 N
C1GR74 S
A0A2S6GKF6 S
A0A8H4GS02 S
A0NJ07 N
C6CBB1 S
Q7NQY2 A
A0A173R3X4 D
A0A2G3E8V2 D
A0A2S6H6B7 S
A0A316BQ38 S
A0A9W3LFI9 S
B4S394 G
F0ZPL3 N
G0VI62 S
A0A177W826 S
A0A1H8D0R8 -
Q07UM3 S
S3K1S2 S
A0A4V3ALP8 S
A0A6G9XJV9 N
F7NPQ3 S
J4UGB7 Q
J7L3W8 N
A0A0A2B651 V
A0A258FTB0 S
A4FMG0 N
B7GKP4 S
C3YB73 D
C5BWX7 N
I5C044 L
T2KGT3 I
A0A060UN76 D
A0A258FS85 A
A0A975BTN0 N
A1SY01 D
A8G2S3 V
B2IJT1 S
C0Z5S5 T
Q21CP1 A
A0A0A2C6L1 V
A0A1H9M798 N
D5E995 T
C5CIT6 -
D3RN22 D
A0A5M4ATH9 S
A0A9J9ES23 D
C6XKC2 L
D2SE15 N
K9U8C7 V
Q59UP8 S
A0A1H4KAQ7 L
A0A1I5GN22 N
V5E0F3 S
C1N6X9 D
Q6CRN1 S
R1EGK6 D
W0F0I7 S
A0A088E6Q7 N
A0A318FY98 S
D7E934 T
K9ZLY2 D
M1V7W3 D
A0A2K3DPU7 -
A0A2S7YIM5 Q
F3ZYD6 D
F5R974 D
I6Z905 T
A1SZ12 L
A2BP62 V
B8FZP7 S
K1LDP0 I
A0A3S9N9F3 A
A2C095 V
C6DB68 S
G0JRG9 N
J7J5E7 G
Q1K8A3 A
Q2RM12 G
Q7NCB8 N
A0A2S0P9T4 A
B0DU93 S
D0LAL7 N
D0MFE8 D
I5AZQ4 N
Q2YBP7 -
Q81GN5 S
A0A1B9NQ91 S
A0A1T4SFY6 N
A0A6H9FYW4 N
A8ZQD5 D
E2SD44 S
F2JZ83 D
H6LFQ2 D
I3Z3H7 I
A0A1M6JKY3 G
A0A2J7TJ33 S
Q7SEH0 S
L8GFX3 N
Q5KAF6 S
K9YJQ3 V
Q5FA36 S
A6M3G0 N
D9SI59 S
B7G0Y1 D
C1MX19 S
D5T4N9 H
A0A1B9M1A9 S
A0A4R3NVT3 L
A0A420KGW4 S
B0SRS8 D
D4GLQ6 S
Q0ACK1 L
S0ET45 N
A0A1G7H8X3 S
A0A1X4G8K1 N
F8E6R1 L
Q0G2V0 A
A0A5P9P1L2 T
A0A979GQ79 S
A6VE60 S
B9SA70 N
E3H8C9 D
M2A398 S
A0A1J5NTP7 G
A0A2S8F4W0 D
Q9H310 -
W0DZX1 D
Q221S8 S
Q6ND36 A
A0A2C6C0X3 S
A0A427KNL6 S
A7HSN9 D
A0A0X8X7Y7 L
A0A248TDF2 T
A0A5M5PZE2 T
B1Y842 D
D2R647 D
D4H5F9 D
D9QS43 D
H1XV27 D
A0A0A1ZMZ9 V
A0A147GP06 S
H6RWK9 N
K9ZG59 N
M2ALH9 D
A0A423Y4I6 S
A7S3L2 D
A0AA35XZV0 S
C7Q1E4 N
G7WCB6 G
R7PZ71 N
A0A1H1U2Q6 N
A0A562RGZ4 A
F4GED5 S
A0A0X8NXA9 S
F3KUN4 S
C8WSI9 T
O66395 S
Q0I445 S
Q95P70 -
A0A1W2GZ82 I
A0A7U8C744 L
A0A0E3R6S1 G
A0A1I4ZIZ6 A
Q6ND34 S
A0A1G6ABL9 S
A5D4I5 S
K9P5D1 N
A0A1B0ZRL8 L
A7RNC3 D
J1ASR8 A
L0FU80 T
A0A510HHK8 N
D5AU98 S
A0AA94HTL8 S
A6W7U2 N
F2JYR9 A
M5SY07 S
Q94CJ2 -
W7QG13 L
A0A1G9P6Q0 L
A0A9Q8L398 S
Q1QSQ2 L
Q5KPM5 S
A0A068SVR1 S
A0A4P7UHQ5 S
A0A101HKN9 D
A0A1Y6GLJ1 S
A0A562S8V2 S
A0A8H6K7L7 S
A0AA86YS65 A
E7RJZ0 T
A0A037ZMW1 L
A0A0E3QY86 S
F4H924 A
Q8I0L6 -
A0A257T7G4 N
I0JI83 T
Q45HK8 S
K8EJ02 N
Q2WBF7 G
I4DBY0 S
A0A142VAD6 S
A0A482PLH3 S
Q2IHY5 H
R4FZE3 S
A0A2A2MCP3 -
A0A5M8QF12 S
A0A5A7MAJ9 S
A0A9P3CXY2 S
B3MX93 D
B9ACS5 N
A0A085GI50 S
A0A1B9K8L2 S
A0A2X2C038 S
Q1Z4I4 L
A0A075WG29 D
A0A2S6H643 S
A0A6M3ZJI1 S
A1ZGK6 I
A2CCK1 V
C7QGX3 N
D0LTW3 V
D3PKL4 N
A0A0S4VNK2 S
A0A410K1J5 D
D5ASL9 S
A0A369MRW6 N
A6GJF5 V
Q9UBD6 -
A0A0A3XTJ3 S
A0A264VQM8 S
A0A1Z3MS36 S
B3PIH2 S
Q5FLR6 N
A0A087MGU4 S
A0A1Y2JH43 S
L7CG11 S
Q2RWY7 G
Q6CRN0 S
T2IEJ2 V
A0A1B9MBX6 S
B8J5X4 V
A0A7S0ILH2 T
A1VIG8 S
P69681 S
Q6LKC8 D
Q84KJ7 N
A0A0H3KTD3 S
A0A1T4SFK4 A
D3DJN2 N
Q2FS34 A
A0A165MFD1 D
A0A1B9BUZ8 A
A0A1G5W0P2 N
A0A2T2Y0D5 S
H6LKH6 N
L0KGR8 A
A0A0A2BBY0 V
A0A0M3AB44 S
A0A3N0AQL8 N
A0A854QN45 S
A7SGD4 D
C1D4X0 S
U3P8G1 S
A0A147EQL9 N
A0A375YPN6 A
A0A533I6R2 S
A0A1H1BPD6 N
A0A495DND0 S
A0A2N0MZ27 S
A0A2U1SS17 S
A0A0D7F328 A
A0A0E3LMT4 V
A0A7U3XVQ4 S
B1Y6V4 S
Q6BT62 S
A0A0S2DQB6 S
A0A258HS77 A
A0A5C5TYS5 S
A0A7U8C2Y6 D
D4H2Y7 D
G4R7P1 L
R1FI09 D
A0A074KZD8 I
A0A2W4ZXC0 S
A0A1H9RTW8 S
A0A9E9L9J1 S
A1SVA8 D
M0D3Q9 T
A0A087EQK8 N
A0A0E3R4G0 V
A0A369M386 N
A0A3E2VY88 T
I0WJ97 I
Q6HM26 S
W0DZS7 S
A0A0E3BR91 S
A0A1G6ABK5 D
B7G0Y4 D
B8JBH5 H
D6Z5V9 I
M5S9B4 D
S0EUS1 A
V4CRP5 D
A0A149UWF2 A
A0RXK8 N
B1Y8C9 S
A0A212AV03 S
A2BUP4 V
A0A1E5BXA4 L
A7SQ16 D
B0DY50 S
A0A0S4WFM4 S
A0A6N4SPH9 T
C5KTM6 D
C9R9J0 N
Q0F2M5 D
Q2SIR0 D
Q9VFA9 D
A0A4Y4DZN4 N
A0A977NL43 N
A0A0A2VPU3 Q
A8MCL4 N
A0A379A0S9 L
A0A6F8TLE9 S
Q8GQS1 A
V3ZVE4 D
A0A1T4SF40 A
A0A2N7L7C8 D
A0A074ME37 S
Q8RUT6 D
B0VMH1 S
Q92BJ7 S
A0A0L0TDW1 S
A0A857DDJ7 S
A0AA92K392 S
B8GGC3 S
Q7V4T8 V
A0A0V8M0W6 S
A0A5C4RNH5 S
A0A511NGC7 S
A0A149UP06 A
A0A4R3A5P7 S
A0A4U1JNL6 S
Q21J04 S
A0AIW5 S
X5CNT2 N
A0A2T5IHP0 -
A0A5C6LWQ1 S
A0A433ZQ80 S
A7SED8 -
A0A853MG28 V
C0QSY0 N
H1YF74 M
H6LKX6 D
Q47X17 S
A0A037ZJY5 S
A0A1B9MZ78 S
B3PF77 M
B4HDZ9 D
E6W5C1 I
M1WRK6 A
A0A2G6JLT9 D
A7I8Z2 D
B2GFN1 N
D2V6P8 -
F2G6G4 L
A0A1H7CU41 G
A0A2S5WMT7 S
A0A4Q2EAG7 S
Q5KZZ9 S
A0A1I0AQM4 -
A0A1I7FBM5 -
A8AC17 S
A0A0D2UPA8 G
A0A4R8GSH7 D
C7NND3 T
D3LBI0 N
I7ZHW3 S
Q0VPH4 D
A8M670 N
B0DU91 S
E4T0A4 S
F0Y9X3 D
Q0G0A4 S
A0A2S8FTB5 D
A0LV78 A
A0A2S8QA29 S
D3PAH1 N
A0A6T9XUR2 L
A7I8Z4 S
B0CQX4 S
D6TCH6 -
K0N2R5 N
K8W1E2 S
A0A1G6ABX1 L
A0A2S5WZU0 S
D6SPD1 L
M5S735 S
U1PPI7 D
A0A0C6P439 S
A0A257SYX3 N
A7NKH2 D
Q1Q879 L
A4BAE1 L
D2BIB2 S
A0A2K3DQF8 D
A0A7V8IKS6 S
A0A7U3YMN6 S
Q9REX3 V
A0A2S5WUP6 N
D6TFE1 V
Q3Z7F9 S
A0A0L8BVU4 S
A0A2R4MBA2 S
A0A2I0UUY1 T
G0JRQ3 D
A0A067Z3S3 A
A0A161SKF4 S
A4BMY5 S
B0XVV6 S
K2IMJ7 L
P40260 A
A0A414NWT8 T
A0A8F5VN39 S
A0A837C6X5 S
C9KKP2 T
D4XSW0 D
J9Z839 N
Q07UM1 A
Q60BI2 S
A0A0L0STS6 S
A0A366WYI9 L
A0A251YFS0 S
F7ZJZ1 A
J3EXK0 D
Q0F2M7 S
A0A016XDZ5 S
A0A1A0DHK0 -
G0IYI2 T
G5EB09 S
Q60C43 S
A0A034WGQ2 D
A0A2A2M8K7 S
A0A066ZRQ5 D
B3QRJ4 G
A0A165MAC2 G
G8JUJ2 S
R9PI53 L
A0A059XXR1 N
A0A075JZ35 S
F2NNQ0 N
O04161 D
A0A2A7U6W1 S
A0A7M6UUM4 -
A0A420WC79 L
A0A7G5DKA9 D
A0A7S4LPS8 V
A0A7U4E420 S
C8WZE0 D
E4TRS4 T
A0A1W2H3F0 T
A0A2T4XZC1 S
A0A248LNK5 T
A0A251XJT0 S
A0A4P6UIJ8 S
A0A7G5DPV0 S
B0DXT9 S
J0S2I0 D
A0A071M4L5 S
A0A0B4E6X7 I
K9WSX4 D
K9WT03 N
A9BTK1 N
D5UD26 N
M1NZT5 L
A0A0B5FNH4 L
A0A8H7P8U1 S
A0A495WJM6 S
A0A075JIN0 N
A0A091AXI3 S
A0A381CAY8 S
A0A3E2T713 D
E1SLM7 L
M9YAI9 S
A0A0T7FAP8 S
A0A1B9MYL7 S
A0A1G5RZU9 T
A0A1G7VM92 S
A0A1J5NNB8 V
A0A3E2UHE6 T
G7WA28 S
H5UND3 N
A0A0B4DUR9 L
A0A149QSR6 A
W0DYY3 L
M1SJL5 S
V4RK08 A
A0A063Y394 A
A0A1B9JHS5 S
A0A5M4B0G1 G
A0A6C8LST1 S
A0A8E2R1Y5 S
A6DUG4 I
B0CXH8 S
F4D1J0 N
A0A1L3F1X5 S
A0A257T8W6 N
U5DEY6 V
A4CMI3 I
A0A011U1K7 S
A0A401X433 A
Q2S8H9 L
F7ZJM0 D
L0JT30 T
Q22947 -
Q63EK5 S
A0A1I4W3A0 N
D0KXQ0 D
A6LV49 N
C7LW88 D
L0KW14 S
S0G181 I
A0A1W9KSU5 S
A0A377I7W9 S
E5B358 S
G0V8D6 S
L1IHZ8 S
A7HSP2 A
C1A872 N
A0A6H9GWG4 V
F0S3Z6 D
A0A0P6VSR8 S
A0A1Y0V4A5 -
E1QFA8 S
E4N1T5 M
R1EDV9 D
B0DFJ4 S
D2RU19 T
A0A2H4U5R1 N
A0A2T1N7R1 I
A0A5J6WPP9 D
A1B3N0 S
A0A142NNN1 N
A0A172YCA7 S
Q9M6N7 N
V5BYZ7 S
A0A060HN92 S
A0A2N7LCD7 L
F0ZCX7 -
Q6ARH0 L
A0A009PYN3 S
A0A075WBP9 N
A0A9E9LXV9 S
A0A089ZBW5 N
A0A6P4JM51 D
A0A2S5X482 S
F5ISF6 S
Q0ARJ4 S
A0A0H2XSU4 A
A0A290XBB5 S
A8NAG3 S
B0SL05 V
G8JTW0 S
A0A9W5JBA9 S
A2SPS8 S
A0A5C5TUT2 S
C1F584 V
C7R314 N
H2CLF7 V
A0A401WXG0 -
A0A542XGT4 N
A0A0S2FHD7 S
A0A2S5YID7 S
A0A149RQX0 A
A6DN47 I
A0A225CMT8 S
G4QHD2 D
K9YR86 V
A0A174SD65 N
D7UQE2 -
D9QPC8 A
G7WDB5 D
G8TK77 S
K9Z0D3 T
A0A101DCS3 N
A0A172YBR4 L
Q1L727 D
A0A318QZ80 V
A0A8H6MPB9 S
N1WR17 I
Q2J376 S
A0A0D2NYP3 S
A0A2I1M481 H
I0HGY4 N
A4ABK3 L
C9RS76 V
F2JTN3 L
G0JRH4 A
M5U2P1 D
Q1PX09 A
Q2HD43 S
A0A165BP25 S
A0A2C9CK98 D
G0J614 I
M4VEJ9 -
U5C2K4 I
A0A1S1HM83 T
F0RHS0 D
A0A5M4AWD2 D
B7FW68 D
G9Y5B0 S
Q5FSX6 A
A0A149TSA9 A
A0A1G7UZX2 D
A3ZZL7 S
A9WHW6 D
B7FTM9 D
A0A1H4DJ49 L
A0AA35XVN2 S
A0A2T0GTU1 N
A0A4R3ZZ35 N
A0A855EH99 S
D9QPE5 A
M5SYZ1 D
Q0VQH6 S
A0A096EEV9 S
A0A2R3IMJ8 S
Q6QH01 D
E0SD83 S
I5B3H0 D
X5DX97 T
A0A7T2S0Z6 S
A9B874 D
A0A2R4TRE0 S
D3F0Z1 N
A0A4R2M206 S
A4BEP1 D
P41948 S
A0A1S1HRJ0 S
A0A2S5V2F6 N
B9WDK0 S
C8XBX8 N
R8VWI7 D
A0A4R3NLV5 S
A6XBM2 -
A8HSA2 D
C3X831 S
U2WTW8 S
A0A1M6BPM0 G
A0A4P6UIK6 S
A0A4R5U5V1 S
A0RUZ2 N
I4CCD1 A
J1L5M8 S
Q89WR5 S
A0A068TC78 S
A0A166IS52 V
D3PE53 S
A0A077EFU9 S
A0A160KTE9 S
A0A1Y5E8I7 L
A0A6H9GLV4 V
G3IYW0 S
G7WFX2 T
Q6BK68 T
Q9QUT0 -
A0A1E5C7W4 D
A0A1Y3U5V2 N

In [12]:
tft = alignment[:, 241:242]

In [13]:
twofourtwo = []
seqtft = []


for i in tft:
    print(i.id, i.seq)
    twofourtwo.append(f"{i.id} {i.seq}")
    seqtft.append(i.seq)

A1D2Y5 A
M8E0R3 A
A0A2G3DSU6 T
A0A328EMN2 A
A0A6A1TYJ4 A
D3RMV7 A
F0J3F9 V
G2ZN72 A
I0KDC6 A
A0A081N2G5 S
A0A144NLT9 G
B4D7W2 G
F3QNA7 A
Q4WHC6 A
Q8JI14 L
A0A395VB65 T
A0A975GIX9 A
Q5UZ98 T
A0A4R4K1P9 A
A0A7T4WEP4 I
C6LBD3 T
D5V7B3 N
A0A4R3ZNW3 A
A9BQZ4 A
A0A642KQG8 T
A9BIZ7 T
K0NJH2 T
Q2IK04 T
T2KJ59 T
A0A1B9M5B8 C
A0A323UE08 A
E8RLT5 A
F6G5I9 A
G3A431 A
G4H971 A
L1J6I4 A
M0J579 T
A0A377PBY1 G
A0A401WUW1 A
L1IYW7 A
A0A315S845 A
A0A6M3ZKU5 A
A0A502GPV4 A
A0A9J9BAE8 S
A1AVV2 A
B1XZU2 T
Q5P1S8 A
A0A0F5EZP7 A
A0A4R7GKA0 A
A0A2T4UWF1 A
A0A3E0X011 S
A0A4R8H081 T
C7LQR9 T
A0A0A2A0Y9 T
A0A0A2A5X1 T
A0A7T5BFQ2 A
A3U857 A
E1V4T3 S
F0J7D3 I
M7XJ51 T
Q1K0H9 S
A0A2S5XAB8 A
A0A366IE34 A
Q1Z695 A
A0A8G2IZM3 G
G3IYW2 A
A0A2G5BGA9 A
A0A5M4AUM9 A
E3HJW8 A
U1PIR6 T
A0A1B9N3H7 C
A0A2S5WV24 A
A0A6U2BIY7 T
A0A833LX85 T
I9P003 S
K8VZC6 A
L1IUV5 A
A0A0K2STQ7 T
A0A2H1HV86 A
Q2GX26 A
A0A074KY88 T
A0A858ZNJ3 A
A0A3P2A7W8 A
A0A7S4GND2 T
O26757 A
Q46G49 A
A0A140NHJ5 A
A0A2S8GF54 T
B1JZ69 A
E5Y678 A
A0A149U2G9 A
A0A9Q5QVI9 A
Q18PF5 L
A0A317FZW2 T
G5EB13 A
Q1YDY8 S
A0A1X4GBG2 T
A0A4Q7Y9I7 A
I0HKQ8 G
A0A097R891 G
A0A7S4GMD8 T
Q488X2 S
U3PCH5 S
A0A378YR15 A
I1YG38 A
F5XN43 A
Q1IWN6 A
A0A1E3PSK5 A
A0A833H2R7 T
A0A2T0XPP2 T
A0A399T909 A
L8GGA0 A
A0A0D8BQX6 A
A0A1M5ZVP9 T
I5BYV5 T
A0A0K2STH0 T
A0A2N6K4Y5 A
A0A1B9JZS5 C
A0A2W0GQV0 G
A0A369MHK2 A
A0A087L0B9 A
A0A0A2AMW2 T
A0A377PLP5 G
Q6BJI7 A
Q7S5K0 M
Q7Z1M1 T
T2JFS5 T
W0JIB3 T
A0A1V2XMU9 A
A0A2S6GKN5 A
A0A7G5DK18 A
A0A830ZZN8 G
A0A8B4RWH8 A
A0A9Q6P4A5 A
B8ENL9 A
Q9QXP0 C
A0A060URC3 I
A0A2W5HTC3 A
A7S731 T
A0A1Y0UZX2 A
A0A257TE48 A
Q2RVB5 A
Q605Y6 A
A0A918MJ52 T
K6W5X0 A
V4AP67 T
A0A7Z0V0A4 A
C0GKN4 T
A9HMD6 A
B1ZSW9 A
K5DBA0 T
V4REY8 S
A0A0D2KGN8 M
A0A242NIL1 C
A8PXT8 V
B7X047 A
D2ZRW2 A
H1Y7T6 A
Q97L80 G
A0A0S6UHP2 T
A0A323UDG5 A
E3I393 A
A0A4V2X6C2 A
D7G265 T
A6LRS5 A
D8J4C6 T
F2NGJ8 A
A0A0E9NHV4 A
A1CQ21 A
A0A6N2Z556 T
Q0BWD0 S
A0A071MMV1 A
A0A168EVK8 G
B3DUX7 A
F5L8M7 T
G7WJN0 T
Q0BQ69 A
A0A3N2SFS2 G
A0A9Y2AG30 A
A0AA46Q839 A
E8RSE4 A
F6BEI0 T
I1DSU5 S
I4C9L2 A
Q5QVH2 S
A0A068NPW2 A
A0A6J5IRX5 A
A0A3R9Q7C4 A
A3ZT81 T
K0ER80 A
Q0VLH1 S
Q2KZK9 A
R9GM11 G
A0A0T7GZ59 A
A0A1G5PWV0 A
S5ABR8 S
W7QGM4 T
F5Y3C1 S
I8TC71 A
M1P5F0 S
A0A149RYW7 A
A0A1J1JH03 T
A0A1U9Z147 A
A0A243SC06 A
A0A3G9G2C9 A
I4C9L0 A
I4D1H5 A
Q7W7D3 A
A0A0B4M163 L
A0A1M7UEG2 A
A7HT14 T
C8X554 A
A0A127PIQ9 A
A0A1B9JPL5 C
W5WIX6 A
A0AA40J491 A
D8PD01 A
A0A251XU71 A
A0A2N6P374 A
B3QVV5 A
K1K628 G
A0A1E2SKM1 S
A0A1I0BYN1 A
A0A556RTU3 C
A0A829X098 A
D5EP68 T
F0J6E8 A
A0A073CP02 T
A0A127JTU2 A
C7BJG7 A
D2BUJ8 G
B8IZX4 A
I3R0S7 T
A0A3E2TW06 T
B1Y0E5 A
E6ME92 A
A0A251Y3N4 A
A0A380S5X4 T
F0YLV7 T
F8D7H6 T
Q31CR9 T
W0E077 T
A5DYQ2 A
A8LKQ0 S
A0A4Y1MSE7 A
A3TVQ9 S
F2B2B8 A
L0K9M1 T
Q4WT12 A
Q8ERT9 T
A0A1H3WA00 G
A0A1U9YY82 S
A1DG05 A
B8GGC1 A
F3ZVV4 A
P69680 G
Q0G2T1 S
A0A3T0SZ22 A
A0A4R2Z2K6 A
L1IYP4 A
Q46HB1 T
A0A149QAW7 A
A0A1Y4L5P0 T
A0A6B8N021 G
D5EP71 G
V5U2Z4 G
A0A0E3QYF3 T
A0A0K2STK6 T
A0A8H7U3I1 A
A0A062IU58 A
A0A178TA08 A
A0A3G9G4Q4 A
A0A6H9FPY5 T
A1C5Z7 A
A0A0A1ZJU5 T
A0A258HPP1 A
G0H0Z6 T
A0A2Z4MD56 A
G0EFF3 A
E2SD33 A
E4TJ50 A
A0A016XCG9 A
A0A2S5Y0D3 A
K9YN27 T
Q3AFY9 A
Q7N0M6 A
W8KM07 S
A0A0G9HEC5 A
A5UJR1 A
A0A9Q9D9I3 A
B9SXC7 I
C0QTA4 A
A0A176XNC5 A
A0A317G0I6 T
A0A2S5CTX8 T
U2EN72 S
A0A248LNW8 A
A0A4P8HC89 A
G7UUY6 A
A0A0E3WZH5 -
A0A165K0X5 T
D3FBG3 A
Q608B6 A
A0A854Q6X9 V
H2IZ00 A
A0A4V0XUI3 T
A0A7S4GNJ2 T
A0A2S5WX34 A
C1D6X6 A
A0A418VIJ8 A
A0A857DMN9 A
Q7T3R4 L
R1D1H4 T
T2J0N1 T
A0A419AVL2 A
K0K7J4 A
A0A4U1K1W1 A
A0A9R0NTP8 A
B0RC35 A
C8XB51 A
E4NS62 T
R9PMC6 A
A0A1R1IDV3 A
A0A2N6JV02 T
A7MFK3 G
B0BZN3 T
F7ZEU9 S
K9P718 T
Q82X47 L
Q8RUE9 M
A0A0M2LU39 S
A0A3N1VXY4 G
A0A370FPU0 C
A0A7G5DPV1 S
A9UR54 T
F0S0G1 A
K9W4V5 T
A0A015YIP3 T
A0A291PMC6 A
G8R7U9 A
U1H1F7 A
A0A021VMC6 A
A0A855F5Y8 G
A0A2W5VAZ2 A
M0MDP9 T
A0A1X3RP39 G
A0A653N397 A
A0A8G2F718 T
F4B548 V
I0ICG0 T
A0A009TDB1 A
A0A1G7DX68 A
E4YA63 T
Q2W5V2 A
Q3AP28 A
Q9BLG3 T
A0A0D5YN10 A
A0A0L0S493 A
H1YCC3 A
L8JUH3 T
A0A0E3SHQ9 T
A0A366XFS8 A
E6VIW4 A
F6FRU9 A
A1VIM5 S
E0TGP9 S
A0A0E3SP24 A
A0A8H6NAG3 A
B8FGW0 A
C3X1J1 V
D9SI36 A
E0TCV4 S
E4U5Z1 A
A0A094W9G3 A
A0A7G5EC77 A
A0A482TED1 T
A0A4Q2QWS1 G
A3PAY4 T
A0A173R3W6 A
A0A1B9BUU6 I
A0A495D4X4 S
A0A833GZR2 T
D0L8H3 A
F4XTK4 T
I4D6Z7 A
L8H844 S
A0A0S6UEK9 A
A0A1M6ZMI3 T
U1SIR9 A
A0A066ZTE4 S
A9DQM8 T
A0A0A0D6K5 A
D6E7B3 A
A0A562USB9 S
C7LW87 A
G0JRG6 I
A0A1X6N3Q5 M
A0A1Y4LM49 T
B7FSA7 T
E1QIU3 T
H2CDR5 T
Q1K433 T
Q1QS12 A
Q7T070 L
A0A0H3DR67 A
A5CRL2 A
A0A836M2B6 A
E6SF19 A
I2GD40 A
Q18ES8 T
A0A060UWC8 I
A0A0U1NJW3 S
A0A7R6PER3 S
A4G1J2 A
A9AUR8 A
C1N5A7 T
D3S2L0 A
F8IJE0 A
A0A0D2LEF5 G
A0A1H1MB73 A
W7QGE0 A
G2T1Y3 T
L7CG99 T
A0A1I0C958 T
A0KPE9 G
A9V5W4 L
F5RGM7 A
A0A1C6Z081 G
A0A1D3GAE9 A
A0A410JZR4 A
A8N2H6 A
I1YJH7 S
A0A2G5BI87 G
A0A2N6NEK4 A
A0A1Y0HX98 A
C3YB74 T
Q1H0G2 T
Q2FQT3 A
S0APH6 I
A0A075WEB4 A
A0A172RYW3 A
I3C0V3 T
A0A556SRH6 C
A0A7U4DN04 A
A0A1V3SSW1 A
Q466Y3 T
A0A0A2ZRL7 A
A0A0H3LUA3 A
A4G0C5 T
A5E3X2 I
A8P923 A
B8EMQ8 A
D0MFE9 A
A0A060HFT5 A
A0A060JMP6 A
A0A8E2UDJ3 A
I4D6Z9 T
Q13E03 A
Q1JXS5 A
A0A076PL76 A
A0A6N2TIA4 T
Q1AUG3 A
A0A098S5Y7 T
A0A7S4GNF3 T
A0A5J6WQU1 S
A2SS52 A
M9RKT6 S
A0A2K1RA77 I
A0A2K1RA81 I
A0A2S0JW39 T
A0A2T9X1V4 V
D3F545 A
A0A1E3PQH0 T
A0A1J5JH24 A
C4Y298 A
Q3B6Q2 A
Q7TNN9 C
A0A4Y7XC43 A
A0A5B2V3B9 A
B9L7N1 A
C7M2A9 L
D2V6Q5 T
E4T3F7 A
F2YIC4 L
Q0G0A3 S
A0A424WAH3 A
B8ZYW3 T
U7VB41 P
A0A7S0KKL8 T
A0A1C7EL50 T
A0A6G9Y3Q0 A
A0A6S5K4J1 G
G0LFE3 T
J9VXX9 V
V4RHR4 S
A0A0D7F2Y9 A
A0A1S8D478 A
Q47K18 G
B9SWW9 I
L8H5K0 L
A0A369N7Y3 A
A0A399NT81 A
B0SLB7 A
B4CV94 A
E1IF27 A
G2PRJ6 T
A0A202B535 A
A0A2M9D7S8 A
Q6LMI6 S
K2JVF8 S
Q1Q357 T
B8FDY8 A
B8FL88 T
E3H8A6 T
H8L2Q4 A
A0A248LMH8 A
A0A5C5BWI6 A
L1INN6 T
M7NFH3 T
A0A060URB8 A
K9W6F3 A
A0A7S0D560 A
D2Q0J8 A
A0A251YU48 A
A0A6H9GEE4 T
A0A8F5ZDT8 A
C1G973 A
M0D580 T
A0A1Y5E3E3 V
A0A328Q6M1 A
Q7UGU7 T
A0A660CH85 A
E4T3F3 -
A0A6H9GFU4 A
A3XNG6 T
B9LU00 T
E4RTK5 A
H6LKH9 A
Q0AT01 S
A0A330GB00 G
A0A657K391 C
Q2N625 A
E3GI40 A
F4Y3C5 T
A0A017SYR8 A
A0A494JB70 A
D4XLN6 A
Q1YDY7 A
A0A2G5RQK9 A
A0A369NYJ2 A
A0A1Q2C7H7 A
C5LAG4 T
K0F9X7 A
Q1K3N8 T
A0A2V4EA49 C
A0A562BXM4 A
A0A4D6KHD1 T
A0A4R6DFU8 A
A0A4R7VEK0 A
G0AFH4 A
K5CFE5 A
Q1H483 A
A0A063Y780 S
A0A1W5PRD1 L
Q2YLQ6 A
U5C4L4 T
A0A8G2F3G4 A
D5ELM4 T
J2ZGN6 T
Q84KJ6 I
A0A211ZGL5 A
A0A373FQ71 A
A0A2S8FR08 A
A0A7T2W1B3 A
D4F313 A
F4KY49 A
A0A149V596 A
A0A2S7YPJ9 A
A0A2S0Q8P1 T
Q7UYZ3 A
J7ITF6 A
Q9NIV0 M
A0A1D8UWJ6 A
C1MHX0 A
F3QPR6 A
A0A068NV61 T
A0A1B9LFW3 C
A0A7H8UK07 G
A0AA91Q161 A
A0AA92EGF5 A
G7WFX4 A
M9RJS5 A
A0A1B9KID3 C
A0A3E2UCG9 T
S9QZ09 A
A0A2S8GSU9 A
J7IVQ1 T
F0JGZ1 A
F2AUF4 T
A0A2S8GEJ5 T
C6WEW7 A
E5Y789 A
J4KM12 A
Q21P82 S
Q5P470 A
A0A0H3H4I7 G
D5VJ32 A
C8WLL8 A
D2R355 A
H2CJI0 T
A0A2S5WGI8 A
C1GR74 A
A0A2S6GKF6 A
A0A8H4GS02 A
A0NJ07 A
C6CBB1 G
Q7NQY2 A
A0A173R3X4 T
A0A2G3E8V2 T
A0A2S6H6B7 A
A0A316BQ38 A
A0A9W3LFI9 G
B4S394 A
F0ZPL3 T
G0VI62 I
A0A177W826 A
A0A1H8D0R8 L
Q07UM3 A
S3K1S2 G
A0A4V3ALP8 A
A0A6G9XJV9 A
F7NPQ3 A
J4UGB7 A
J7L3W8 A
A0A0A2B651 T
A0A258FTB0 A
A4FMG0 A
B7GKP4 A
C3YB73 T
C5BWX7 A
I5C044 S
T2KGT3 T
A0A060UN76 A
A0A258FS85 A
A0A975BTN0 A
A1SY01 T
A8G2S3 T
B2IJT1 A
C0Z5S5 A
Q21CP1 A
A0A0A2C6L1 T
A0A1H9M798 A
D5E995 T
C5CIT6 A
D3RN22 A
A0A5M4ATH9 A
A0A9J9ES23 A
C6XKC2 S
D2SE15 A
K9U8C7 T
Q59UP8 I
A0A1H4KAQ7 S
A0A1I5GN22 A
V5E0F3 A
C1N6X9 T
Q6CRN1 I
R1EGK6 T
W0F0I7 A
A0A088E6Q7 G
A0A318FY98 G
D7E934 T
K9ZLY2 T
M1V7W3 S
A0A2K3DPU7 -
A0A2S7YIM5 A
F3ZYD6 T
F5R974 A
I6Z905 T
A1SZ12 S
A2BP62 T
B8FZP7 A
K1LDP0 T
A0A3S9N9F3 A
A2C095 T
C6DB68 A
G0JRG9 I
J7J5E7 A
Q1K8A3 A
Q2RM12 A
Q7NCB8 A
A0A2S0P9T4 A
B0DU93 G
D0LAL7 A
D0MFE8 T
I5AZQ4 A
Q2YBP7 L
Q81GN5 A
A0A1B9NQ91 C
A0A1T4SFY6 A
A0A6H9FYW4 A
A8ZQD5 T
E2SD44 A
F2JZ83 A
H6LFQ2 T
I3Z3H7 T
A0A1M6JKY3 A
A0A2J7TJ33 A
Q7SEH0 A
L8GFX3 A
Q5KAF6 V
K9YJQ3 T
Q5FA36 A
A6M3G0 A
D9SI59 A
B7G0Y1 T
C1MX19 A
D5T4N9 A
A0A1B9M1A9 C
A0A4R3NVT3 S
A0A420KGW4 A
B0SRS8 T
D4GLQ6 G
Q0ACK1 S
S0ET45 A
A0A1G7H8X3 A
A0A1X4G8K1 A
F8E6R1 S
Q0G2V0 S
A0A5P9P1L2 T
A0A979GQ79 A
A6VE60 A
B9SA70 I
E3H8C9 T
M2A398 A
A0A1J5NTP7 A
A0A2S8F4W0 T
Q9H310 L
W0DZX1 A
Q221S8 T
Q6ND36 A
A0A2C6C0X3 G
A0A427KNL6 G
A7HSN9 A
A0A0X8X7Y7 S
A0A248TDF2 C
A0A5M5PZE2 T
B1Y842 A
D2R647 T
D4H5F9 T
D9QS43 T
H1XV27 T
A0A0A1ZMZ9 T
A0A147GP06 C
H6RWK9 A
K9ZG59 A
M2ALH9 T
A0A423Y4I6 G
A7S3L2 T
A0AA35XZV0 A
C7Q1E4 A
G7WCB6 A
R7PZ71 A
A0A1H1U2Q6 A
A0A562RGZ4 T
F4GED5 A
A0A0X8NXA9 A
F3KUN4 A
C8WSI9 A
O66395 A
Q0I445 A
Q95P70 L
A0A1W2GZ82 T
A0A7U8C744 S
A0A0E3R6S1 A
A0A1I4ZIZ6 A
Q6ND34 A
A0A1G6ABL9 A
A5D4I5 A
K9P5D1 A
A0A1B0ZRL8 S
A7RNC3 T
J1ASR8 A
L0FU80 T
A0A510HHK8 A
D5AU98 A
A0AA94HTL8 A
A6W7U2 A
F2JYR9 S
M5SY07 A
Q94CJ2 M
W7QG13 S
A0A1G9P6Q0 S
A0A9Q8L398 A
Q1QSQ2 S
Q5KPM5 A
A0A068SVR1 A
A0A4P7UHQ5 A
A0A101HKN9 T
A0A1Y6GLJ1 G
A0A562S8V2 A
A0A8H6K7L7 A
A0AA86YS65 A
E7RJZ0 T
A0A037ZMW1 S
A0A0E3QY86 A
F4H924 A
Q8I0L6 M
A0A257T7G4 I
I0JI83 T
Q45HK8 A
K8EJ02 A
Q2WBF7 A
I4DBY0 A
A0A142VAD6 A
A0A482PLH3 G
Q2IHY5 A
R4FZE3 A
A0A2A2MCP3 A
A0A5M8QF12 A
A0A5A7MAJ9 A
A0A9P3CXY2 A
B3MX93 T
B9ACS5 A
A0A085GI50 G
A0A1B9K8L2 C
A0A2X2C038 A
Q1Z4I4 S
A0A075WG29 T
A0A2S6H643 A
A0A6M3ZJI1 A
A1ZGK6 T
A2CCK1 T
C7QGX3 A
D0LTW3 T
D3PKL4 A
A0A0S4VNK2 A
A0A410K1J5 T
D5ASL9 A
A0A369MRW6 A
A6GJF5 T
Q9UBD6 C
A0A0A3XTJ3 A
A0A264VQM8 A
A0A1Z3MS36 G
B3PIH2 A
Q5FLR6 A
A0A087MGU4 A
A0A1Y2JH43 A
L7CG11 A
Q2RWY7 L
Q6CRN0 I
T2IEJ2 T
A0A1B9MBX6 C
B8J5X4 T
A0A7S0ILH2 A
A1VIG8 T
P69681 G
Q6LKC8 A
Q84KJ7 V
A0A0H3KTD3 G
A0A1T4SFK4 A
D3DJN2 A
Q2FS34 A
A0A165MFD1 T
A0A1B9BUZ8 A
A0A1G5W0P2 A
A0A2T2Y0D5 G
H6LKH6 A
L0KGR8 A
A0A0A2BBY0 T
A0A0M3AB44 A
A0A3N0AQL8 A
A0A854QN45 A
A7SGD4 T
C1D4X0 A
U3P8G1 A
A0A147EQL9 A
A0A375YPN6 S
A0A533I6R2 A
A0A1H1BPD6 A
A0A495DND0 A
A0A2N0MZ27 A
A0A2U1SS17 A
A0A0D7F328 A
A0A0E3LMT4 -
A0A7U3XVQ4 A
B1Y6V4 T
Q6BT62 I
A0A0S2DQB6 A
A0A258HS77 A
A0A5C5TYS5 A
A0A7U8C2Y6 A
D4H2Y7 T
G4R7P1 S
R1FI09 T
A0A074KZD8 T
A0A2W4ZXC0 A
A0A1H9RTW8 A
A0A9E9L9J1 V
A1SVA8 A
M0D3Q9 T
A0A087EQK8 A
A0A0E3R4G0 -
A0A369M386 A
A0A3E2VY88 T
I0WJ97 T
Q6HM26 A
W0DZS7 A
A0A0E3BR91 A
A0A1G6ABK5 A
B7G0Y4 T
B8JBH5 A
D6Z5V9 T
M5S9B4 T
S0EUS1 Y
V4CRP5 T
A0A149UWF2 A
A0RXK8 A
B1Y8C9 C
A0A212AV03 A
A2BUP4 T
A0A1E5BXA4 S
A7SQ16 T
B0DY50 M
A0A0S4WFM4 A
A0A6N4SPH9 T
C5KTM6 T
C9R9J0 A
Q0F2M5 A
Q2SIR0 A
Q9VFA9 T
A0A4Y4DZN4 A
A0A977NL43 A
A0A0A2VPU3 A
A8MCL4 A
A0A379A0S9 S
A0A6F8TLE9 A
Q8GQS1 A
V3ZVE4 T
A0A1T4SF40 A
A0A2N7L7C8 A
A0A074ME37 A
Q8RUT6 T
B0VMH1 A
Q92BJ7 A
A0A0L0TDW1 A
A0A857DDJ7 A
A0AA92K392 A
B8GGC3 A
Q7V4T8 T
A0A0V8M0W6 A
A0A5C4RNH5 A
A0A511NGC7 A
A0A149UP06 A
A0A4R3A5P7 A
A0A4U1JNL6 A
Q21J04 A
A0AIW5 A
X5CNT2 I
A0A2T5IHP0 L
A0A5C6LWQ1 A
A0A433ZQ80 A
A7SED8 L
A0A853MG28 T
C0QSY0 A
H1YF74 T
H6LKX6 T
Q47X17 V
A0A037ZJY5 A
A0A1B9MZ78 C
B3PF77 S
B4HDZ9 T
E6W5C1 S
M1WRK6 A
A0A2G6JLT9 A
A7I8Z2 A
B2GFN1 A
D2V6P8 L
F2G6G4 S
A0A1H7CU41 A
A0A2S5WMT7 A
A0A4Q2EAG7 G
Q5KZZ9 A
A0A1I0AQM4 L
A0A1I7FBM5 L
A8AC17 A
A0A0D2UPA8 A
A0A4R8GSH7 A
C7NND3 T
D3LBI0 A
I7ZHW3 A
Q0VPH4 T
A8M670 A
B0DU91 G
E4T0A4 A
F0Y9X3 T
Q0G0A4 A
A0A2S8FTB5 T
A0LV78 A
A0A2S8QA29 A
D3PAH1 A
A0A6T9XUR2 S
A7I8Z4 T
B0CQX4 S
D6TCH6 A
K0N2R5 A
K8W1E2 A
A0A1G6ABX1 S
A0A2S5WZU0 A
D6SPD1 S
M5S735 A
U1PPI7 T
A0A0C6P439 A
A0A257SYX3 V
A7NKH2 T
Q1Q879 S
A4BAE1 S
D2BIB2 A
A0A2K3DQF8 T
A0A7V8IKS6 A
A0A7U3YMN6 A
Q9REX3 T
A0A2S5WUP6 A
D6TFE1 T
Q3Z7F9 A
A0A0L8BVU4 A
A0A2R4MBA2 A
A0A2I0UUY1 T
G0JRQ3 A
A0A067Z3S3 A
A0A161SKF4 A
A4BMY5 A
B0XVV6 A
K2IMJ7 S
P40260 S
A0A414NWT8 A
A0A8F5VN39 A
A0A837C6X5 A
C9KKP2 A
D4XSW0 A
J9Z839 I
Q07UM1 A
Q60BI2 A
A0A0L0STS6 A
A0A366WYI9 S
A0A251YFS0 A
F7ZJZ1 S
J3EXK0 T
Q0F2M7 V
A0A016XDZ5 A
A0A1A0DHK0 V
G0IYI2 T
G5EB09 A
Q60C43 T
A0A034WGQ2 T
A0A2A2M8K7 G
A0A066ZRQ5 T
B3QRJ4 A
A0A165MAC2 A
G8JUJ2 I
R9PI53 S
A0A059XXR1 I
A0A075JZ35 A
F2NNQ0 A
O04161 G
A0A2A7U6W1 A
A0A7M6UUM4 L
A0A420WC79 S
A0A7G5DKA9 T
A0A7S4LPS8 T
A0A7U4E420 A
C8WZE0 T
E4TRS4 T
A0A1W2H3F0 T
A0A2T4XZC1 G
A0A248LNK5 A
A0A251XJT0 A
A0A4P6UIJ8 A
A0A7G5DPV0 A
B0DXT9 G
J0S2I0 T
A0A071M4L5 A
A0A0B4E6X7 S
K9WSX4 T
K9WT03 A
A9BTK1 A
D5UD26 A
M1NZT5 S
A0A0B5FNH4 S
A0A8H7P8U1 M
A0A495WJM6 S
A0A075JIN0 A
A0A091AXI3 A
A0A381CAY8 G
A0A3E2T713 T
E1SLM7 S
M9YAI9 A
A0A0T7FAP8 A
A0A1B9MYL7 C
A0A1G5RZU9 T
A0A1G7VM92 G
A0A1J5NNB8 T
A0A3E2UHE6 T
G7WA28 A
H5UND3 A
A0A0B4DUR9 S
A0A149QSR6 A
W0DYY3 S
M1SJL5 A
V4RK08 S
A0A063Y394 S
A0A1B9JHS5 C
A0A5M4B0G1 A
A0A6C8LST1 G
A0A8E2R1Y5 A
A6DUG4 S
B0CXH8 M
F4D1J0 A
A0A1L3F1X5 A
A0A257T8W6 I
U5DEY6 T
A4CMI3 T
A0A011U1K7 A
A0A401X433 A
Q2S8H9 S
F7ZJM0 T
L0JT30 T
Q22947 L
Q63EK5 A
A0A1I4W3A0 A
D0KXQ0 A
A6LV49 A
C7LW88 T
L0KW14 A
S0G181 T
A0A1W9KSU5 T
A0A377I7W9 A
E5B358 G
G0V8D6 S
L1IHZ8 A
A7HSP2 A
C1A872 A
A0A6H9GWG4 T
F0S3Z6 A
A0A0P6VSR8 A
A0A1Y0V4A5 V
E1QFA8 A
E4N1T5 A
R1EDV9 T
B0DFJ4 A
D2RU19 T
A0A2H4U5R1 A
A0A2T1N7R1 T
A0A5J6WPP9 A
A1B3N0 A
A0A142NNN1 A
A0A172YCA7 A
Q9M6N7 I
V5BYZ7 A
A0A060HN92 L
A0A2N7LCD7 S
F0ZCX7 M
Q6ARH0 S
A0A009PYN3 A
A0A075WBP9 A
A0A9E9LXV9 A
A0A089ZBW5 A
A0A6P4JM51 T
A0A2S5X482 A
F5ISF6 A
Q0ARJ4 A
A0A0H2XSU4 A
A0A290XBB5 A
A8NAG3 T
B0SL05 T
G8JTW0 A
A0A9W5JBA9 G
A2SPS8 A
A0A5C5TUT2 A
C1F584 T
C7R314 A
H2CLF7 T
A0A401WXG0 V
A0A542XGT4 A
A0A0S2FHD7 A
A0A2S5YID7 A
A0A149RQX0 A
A6DN47 S
A0A225CMT8 A
G4QHD2 T
K9YR86 T
A0A174SD65 A
D7UQE2 L
D9QPC8 A
G7WDB5 T
G8TK77 G
K9Z0D3 S
A0A101DCS3 A
A0A172YBR4 S
Q1L727 T
A0A318QZ80 T
A0A8H6MPB9 A
N1WR17 T
Q2J376 A
A0A0D2NYP3 A
A0A2I1M481 A
I0HGY4 A
A4ABK3 S
C9RS76 T
F2JTN3 S
G0JRH4 A
M5U2P1 T
Q1PX09 T
Q2HD43 A
A0A165BP25 G
A0A2C9CK98 T
G0J614 T
M4VEJ9 A
U5C2K4 T
A0A1S1HM83 A
F0RHS0 T
A0A5M4AWD2 T
B7FW68 T
G9Y5B0 G
Q5FSX6 A
A0A149TSA9 A
A0A1G7UZX2 A
A3ZZL7 A
A9WHW6 T
B7FTM9 T
A0A1H4DJ49 S
A0AA35XVN2 A
A0A2T0GTU1 A
A0A4R3ZZ35 A
A0A855EH99 G
D9QPE5 A
M5SYZ1 T
Q0VQH6 A
A0A096EEV9 A
A0A2R3IMJ8 A
Q6QH01 T
E0SD83 G
I5B3H0 T
X5DX97 T
A0A7T2S0Z6 A
A9B874 T
A0A2R4TRE0 G
D3F0Z1 A
A0A4R2M206 G
A4BEP1 A
P41948 A
A0A1S1HRJ0 A
A0A2S5V2F6 A
B9WDK0 A
C8XBX8 A
R8VWI7 T
A0A4R3NLV5 A
A6XBM2 L
A8HSA2 T
C3X831 A
U2WTW8 A
A0A1M6BPM0 A
A0A4P6UIK6 A
A0A4R5U5V1 A
A0RUZ2 A
I4CCD1 A
J1L5M8 A
Q89WR5 A
A0A068TC78 A
A0A166IS52 T
D3PE53 A
A0A077EFU9 A
A0A160KTE9 A
A0A1Y5E8I7 S
A0A6H9GLV4 T
G3IYW0 A
G7WFX2 T
Q6BK68 C
Q9QUT0 L
A0A1E5C7W4 A
A0A1Y3U5V2 G

In [14]:
twofourtwo

['A1D2Y5 A',
 'M8E0R3 A',
 'A0A2G3DSU6 T',
 'A0A328EMN2 A',
 'A0A6A1TYJ4 A',
 'D3RMV7 A',
 'F0J3F9 V',
 'G2ZN72 A',
 'I0KDC6 A',
 'A0A081N2G5 S',
 'A0A144NLT9 G',
 'B4D7W2 G',
 'F3QNA7 A',
 'Q4WHC6 A',
 'Q8JI14 L',
 'A0A395VB65 T',
 'A0A975GIX9 A',
 'Q5UZ98 T',
 'A0A4R4K1P9 A',
 'A0A7T4WEP4 I',
 'C6LBD3 T',
 'D5V7B3 N',
 'A0A4R3ZNW3 A',
 'A9BQZ4 A',
 'A0A642KQG8 T',
 'A9BIZ7 T',
 'K0NJH2 T',
 'Q2IK04 T',
 'T2KJ59 T',
 'A0A1B9M5B8 C',
 'A0A323UE08 A',
 'E8RLT5 A',
 'F6G5I9 A',
 'G3A431 A',
 'G4H971 A',
 'L1J6I4 A',
 'M0J579 T',
 'A0A377PBY1 G',
 'A0A401WUW1 A',
 'L1IYW7 A',
 'A0A315S845 A',
 'A0A6M3ZKU5 A',
 'A0A502GPV4 A',
 'A0A9J9BAE8 S',
 'A1AVV2 A',
 'B1XZU2 T',
 'Q5P1S8 A',
 'A0A0F5EZP7 A',
 'A0A4R7GKA0 A',
 'A0A2T4UWF1 A',
 'A0A3E0X011 S',
 'A0A4R8H081 T',
 'C7LQR9 T',
 'A0A0A2A0Y9 T',
 'A0A0A2A5X1 T',
 'A0A7T5BFQ2 A',
 'A3U857 A',
 'E1V4T3 S',
 'F0J7D3 I',
 'M7XJ51 T',
 'Q1K0H9 S',
 'A0A2S5XAB8 A',
 'A0A366IE34 A',
 'Q1Z695 A',
 'A0A8G2IZM3 G',
 'G3IYW2 A',
 'A0A2G5BGA9 A',
 'A0A5M4AUM9 A',
 'E3HJW8 A',
 'U1PIR6 T',
 'A0A1B9N3H7 C',
 'A0A2S5WV24 A',
 'A0A6U2BIY7 T',
 'A0A833LX85 T',
 'I9P003 S',
 'K8VZC6 A',
 'L1IUV5 A',
 'A0A0K2STQ7 T',
 'A0A2H1HV86 A',
 'Q2GX26 A',
 'A0A074KY88 T',
 'A0A858ZNJ3 A',
 'A0A3P2A7W8 A',
 'A0A7S4GND2 T',
 'O26757 A',
 'Q46G49 A',
 'A0A140NHJ5 A',
 'A0A2S8GF54 T',
 'B1JZ69 A',
 'E5Y678 A',
 'A0A149U2G9 A',
 'A0A9Q5QVI9 A',
 'Q18PF5 L',
 'A0A317FZW2 T',
 'G5EB13 A',
 'Q1YDY8 S',
 'A0A1X4GBG2 T',
 'A0A4Q7Y9I7 A',
 'I0HKQ8 G',
 'A0A097R891 G',
 'A0A7S4GMD8 T',
 'Q488X2 S',
 'U3PCH5 S',
 'A0A378YR15 A',
 'I1YG38 A',
 'F5XN43 A',
 'Q1IWN6 A',
 'A0A1E3PSK5 A',
 'A0A833H2R7 T',
 'A0A2T0XPP2 T',
 'A0A399T909 A',
 'L8GGA0 A',
 'A0A0D8BQX6 A',
 'A0A1M5ZVP9 T',
 'I5BYV5 T',
 'A0A0K2STH0 T',
 'A0A2N6K4Y5 A',
 'A0A1B9JZS5 C',
 'A0A2W0GQV0 G',
 'A0A369MHK2 A',
 'A0A087L0B9 A',
 'A0A0A2AMW2 T',
 'A0A377PLP5 G',
 'Q6BJI7 A',
 'Q7S5K0 M',
 'Q7Z1M1 T',
 'T2JFS5 T',
 'W0JIB3 T',
 'A0A1V2XMU9 A',
 'A0A2S6GKN5 A',
 'A0A7G5DK18 A',
 'A0A830ZZN8 G',
 'A0A8B4RWH8 A',
 'A0A9Q6P4A5 A',
 'B8ENL9 A',
 'Q9QXP0 C',
 'A0A060URC3 I',
 'A0A2W5HTC3 A',
 'A7S731 T',
 'A0A1Y0UZX2 A',
 'A0A257TE48 A',
 'Q2RVB5 A',
 'Q605Y6 A',
 'A0A918MJ52 T',
 'K6W5X0 A',
 'V4AP67 T',
 'A0A7Z0V0A4 A',
 'C0GKN4 T',
 'A9HMD6 A',
 'B1ZSW9 A',
 'K5DBA0 T',
 'V4REY8 S',
 'A0A0D2KGN8 M',
 'A0A242NIL1 C',
 'A8PXT8 V',
 'B7X047 A',
 'D2ZRW2 A',
 'H1Y7T6 A',
 'Q97L80 G',
 'A0A0S6UHP2 T',
 'A0A323UDG5 A',
 'E3I393 A',
 'A0A4V2X6C2 A',
 'D7G265 T',
 'A6LRS5 A',
 'D8J4C6 T',
 'F2NGJ8 A',
 'A0A0E9NHV4 A',
 'A1CQ21 A',
 'A0A6N2Z556 T',
 'Q0BWD0 S',
 'A0A071MMV1 A',
 'A0A168EVK8 G',
 'B3DUX7 A',
 'F5L8M7 T',
 'G7WJN0 T',
 'Q0BQ69 A',
 'A0A3N2SFS2 G',
 'A0A9Y2AG30 A',
 'A0AA46Q839 A',
 'E8RSE4 A',
 'F6BEI0 T',
 'I1DSU5 S',
 'I4C9L2 A',
 'Q5QVH2 S',
 'A0A068NPW2 A',
 'A0A6J5IRX5 A',
 'A0A3R9Q7C4 A',
 'A3ZT81 T',
 'K0ER80 A',
 'Q0VLH1 S',
 'Q2KZK9 A',
 'R9GM11 G',
 'A0A0T7GZ59 A',
 'A0A1G5PWV0 A',
 'S5ABR8 S',
 'W7QGM4 T',
 'F5Y3C1 S',
 'I8TC71 A',
 'M1P5F0 S',
 'A0A149RYW7 A',
 'A0A1J1JH03 T',
 'A0A1U9Z147 A',
 'A0A243SC06 A',
 'A0A3G9G2C9 A',
 'I4C9L0 A',
 'I4D1H5 A',
 'Q7W7D3 A',
 'A0A0B4M163 L',
 'A0A1M7UEG2 A',
 'A7HT14 T',
 'C8X554 A',
 'A0A127PIQ9 A',
 'A0A1B9JPL5 C',
 'W5WIX6 A',
 'A0AA40J491 A',
 'D8PD01 A',
 'A0A251XU71 A',
 'A0A2N6P374 A',
 'B3QVV5 A',
 'K1K628 G',
 'A0A1E2SKM1 S',
 'A0A1I0BYN1 A',
 'A0A556RTU3 C',
 'A0A829X098 A',
 'D5EP68 T',
 'F0J6E8 A',
 'A0A073CP02 T',
 'A0A127JTU2 A',
 'C7BJG7 A',
 'D2BUJ8 G',
 'B8IZX4 A',
 'I3R0S7 T',
 'A0A3E2TW06 T',
 'B1Y0E5 A',
 'E6ME92 A',
 'A0A251Y3N4 A',
 'A0A380S5X4 T',
 'F0YLV7 T',
 'F8D7H6 T',
 'Q31CR9 T',
 'W0E077 T',
 'A5DYQ2 A',
 'A8LKQ0 S',
 'A0A4Y1MSE7 A',
 'A3TVQ9 S',
 'F2B2B8 A',
 'L0K9M1 T',
 'Q4WT12 A',
 'Q8ERT9 T',
 'A0A1H3WA00 G',
 'A0A1U9YY82 S',
 'A1DG05 A',
 'B8GGC1 A',
 'F3ZVV4 A',
 'P69680 G',
 'Q0G2T1 S',
 'A0A3T0SZ22 A',
 'A0A4R2Z2K6 A',
 'L1IYP4 A',
 'Q46HB1 T',
 'A0A149QAW7 A',
 'A0A1Y4L5P0 T',
 'A0A6B8N021 G',
 'D5EP71 G',
 'V5U2Z4 G',
 'A0A0E3QYF3 T',
 'A0A0K2STK6 T',
 'A0A8H7U3I1 A',
 'A0A062IU58 A',
 'A0A178TA08 A',
 'A0A3G9G4Q4 A',
 'A0A6H9FPY5 T',
 'A1C5Z7 A',
 'A0A0A1ZJU5 T',
 'A0A258HPP1 A',
 'G0H0Z6 T',
 'A0A2Z4MD56 A',
 'G0EFF3 A',
 'E2SD33 A',
 'E4TJ50 A',
 'A0A016XCG9 A',
 'A0A2S5Y0D3 A',
 'K9YN27 T',
 'Q3AFY9 A',
 'Q7N0M6 A',
 'W8KM07 S',
 'A0A0G9HEC5 A',
 'A5UJR1 A',
 'A0A9Q9D9I3 A',
 'B9SXC7 I',
 'C0QTA4 A',
 'A0A176XNC5 A',
 'A0A317G0I6 T',
 'A0A2S5CTX8 T',
 'U2EN72 S',
 'A0A248LNW8 A',
 'A0A4P8HC89 A',
 'G7UUY6 A',
 'A0A0E3WZH5 -',
 'A0A165K0X5 T',
 'D3FBG3 A',
 'Q608B6 A',
 'A0A854Q6X9 V',
 'H2IZ00 A',
 'A0A4V0XUI3 T',
 'A0A7S4GNJ2 T',
 'A0A2S5WX34 A',
 'C1D6X6 A',
 'A0A418VIJ8 A',
 'A0A857DMN9 A',
 'Q7T3R4 L',
 'R1D1H4 T',
 'T2J0N1 T',
 'A0A419AVL2 A',
 'K0K7J4 A',
 'A0A4U1K1W1 A',
 'A0A9R0NTP8 A',
 'B0RC35 A',
 'C8XB51 A',
 'E4NS62 T',
 'R9PMC6 A',
 'A0A1R1IDV3 A',
 'A0A2N6JV02 T',
 'A7MFK3 G',
 'B0BZN3 T',
 'F7ZEU9 S',
 'K9P718 T',
 'Q82X47 L',
 'Q8RUE9 M',
 'A0A0M2LU39 S',
 'A0A3N1VXY4 G',
 'A0A370FPU0 C',
 'A0A7G5DPV1 S',
 'A9UR54 T',
 'F0S0G1 A',
 'K9W4V5 T',
 'A0A015YIP3 T',
 'A0A291PMC6 A',
 'G8R7U9 A',
 'U1H1F7 A',
 'A0A021VMC6 A',
 'A0A855F5Y8 G',
 'A0A2W5VAZ2 A',
 'M0MDP9 T',
 'A0A1X3RP39 G',
 'A0A653N397 A',
 'A0A8G2F718 T',
 'F4B548 V',
 'I0ICG0 T',
 'A0A009TDB1 A',
 'A0A1G7DX68 A',
 'E4YA63 T',
 'Q2W5V2 A',
 'Q3AP28 A',
 'Q9BLG3 T',
 'A0A0D5YN10 A',
 'A0A0L0S493 A',
 'H1YCC3 A',
 'L8JUH3 T',
 'A0A0E3SHQ9 T',
 'A0A366XFS8 A',
 'E6VIW4 A',
 'F6FRU9 A',
 'A1VIM5 S',
 'E0TGP9 S',
 'A0A0E3SP24 A',
 'A0A8H6NAG3 A',
 'B8FGW0 A',
 'C3X1J1 V',
 'D9SI36 A',
 'E0TCV4 S',
 'E4U5Z1 A',
 'A0A094W9G3 A',
 'A0A7G5EC77 A',
 'A0A482TED1 T',
 'A0A4Q2QWS1 G',
 'A3PAY4 T',
 'A0A173R3W6 A',
 'A0A1B9BUU6 I',
 'A0A495D4X4 S',
 'A0A833GZR2 T',
 'D0L8H3 A',
 'F4XTK4 T',
 'I4D6Z7 A',
 'L8H844 S',
 'A0A0S6UEK9 A',
 'A0A1M6ZMI3 T',
 'U1SIR9 A',
 'A0A066ZTE4 S',
 'A9DQM8 T',
 'A0A0A0D6K5 A',
 'D6E7B3 A',
 'A0A562USB9 S',
 'C7LW87 A',
 'G0JRG6 I',
 'A0A1X6N3Q5 M',
 'A0A1Y4LM49 T',
 'B7FSA7 T',
 'E1QIU3 T',
 'H2CDR5 T',
 'Q1K433 T',
 'Q1QS12 A',
 'Q7T070 L',
 'A0A0H3DR67 A',
 'A5CRL2 A',
 'A0A836M2B6 A',
 'E6SF19 A',
 'I2GD40 A',
 'Q18ES8 T',
 'A0A060UWC8 I',
 'A0A0U1NJW3 S',
 'A0A7R6PER3 S',
 'A4G1J2 A',
 'A9AUR8 A',
 'C1N5A7 T',
 'D3S2L0 A',
 'F8IJE0 A',
 'A0A0D2LEF5 G',
 'A0A1H1MB73 A',
 'W7QGE0 A',
 'G2T1Y3 T',
 'L7CG99 T',
 'A0A1I0C958 T',
 'A0KPE9 G',
 'A9V5W4 L',
 'F5RGM7 A',
 'A0A1C6Z081 G',
 'A0A1D3GAE9 A',
 'A0A410JZR4 A',
 'A8N2H6 A',
 'I1YJH7 S',
 'A0A2G5BI87 G',
 'A0A2N6NEK4 A',
 'A0A1Y0HX98 A',
 'C3YB74 T',
 'Q1H0G2 T',
 'Q2FQT3 A',
 'S0APH6 I',
 'A0A075WEB4 A',
 'A0A172RYW3 A',
 'I3C0V3 T',
 'A0A556SRH6 C',
 'A0A7U4DN04 A',
 'A0A1V3SSW1 A',
 'Q466Y3 T',
 'A0A0A2ZRL7 A',
 'A0A0H3LUA3 A',
 'A4G0C5 T',
 'A5E3X2 I',
 'A8P923 A',
 'B8EMQ8 A',
 'D0MFE9 A',
 'A0A060HFT5 A',
 'A0A060JMP6 A',
 'A0A8E2UDJ3 A',
 'I4D6Z9 T',
 'Q13E03 A',
 'Q1JXS5 A',
 'A0A076PL76 A',
 'A0A6N2TIA4 T',
 'Q1AUG3 A',
 'A0A098S5Y7 T',
 'A0A7S4GNF3 T',
 'A0A5J6WQU1 S',
 'A2SS52 A',
 'M9RKT6 S',
 'A0A2K1RA77 I',
 'A0A2K1RA81 I',
 'A0A2S0JW39 T',
 'A0A2T9X1V4 V',
 'D3F545 A',
 'A0A1E3PQH0 T',
 'A0A1J5JH24 A',
 'C4Y298 A',
 'Q3B6Q2 A',
 'Q7TNN9 C',
 'A0A4Y7XC43 A',
 'A0A5B2V3B9 A',
 'B9L7N1 A',
 'C7M2A9 L',
 'D2V6Q5 T',
 'E4T3F7 A',
 'F2YIC4 L',
 'Q0G0A3 S',
 'A0A424WAH3 A',
 'B8ZYW3 T',
 'U7VB41 P',
 'A0A7S0KKL8 T',
 'A0A1C7EL50 T',
 'A0A6G9Y3Q0 A',
 'A0A6S5K4J1 G',
 'G0LFE3 T',
 'J9VXX9 V',
 'V4RHR4 S',
 'A0A0D7F2Y9 A',
 'A0A1S8D478 A',
 'Q47K18 G',
 'B9SWW9 I',
 'L8H5K0 L',
 'A0A369N7Y3 A',
 'A0A399NT81 A',
 'B0SLB7 A',
 'B4CV94 A',
 'E1IF27 A',
 'G2PRJ6 T',
 'A0A202B535 A',
 'A0A2M9D7S8 A',
 'Q6LMI6 S',
 'K2JVF8 S',
 'Q1Q357 T',
 'B8FDY8 A',
 'B8FL88 T',
 'E3H8A6 T',
 'H8L2Q4 A',
 'A0A248LMH8 A',
 'A0A5C5BWI6 A',
 'L1INN6 T',
 'M7NFH3 T',
 'A0A060URB8 A',
 'K9W6F3 A',
 'A0A7S0D560 A',
 'D2Q0J8 A',
 'A0A251YU48 A',
 'A0A6H9GEE4 T',
 'A0A8F5ZDT8 A',
 'C1G973 A',
 'M0D580 T',
 'A0A1Y5E3E3 V',
 'A0A328Q6M1 A',
 'Q7UGU7 T',
 'A0A660CH85 A',
 'E4T3F3 -',
 'A0A6H9GFU4 A',
 'A3XNG6 T',
 'B9LU00 T',
 'E4RTK5 A',
 'H6LKH9 A',
 'Q0AT01 S',
 'A0A330GB00 G',
 'A0A657K391 C',
 'Q2N625 A',
 'E3GI40 A',
 'F4Y3C5 T',
 'A0A017SYR8 A',
 'A0A494JB70 A',
 'D4XLN6 A',
 'Q1YDY7 A',
 'A0A2G5RQK9 A',
 'A0A369NYJ2 A',
 'A0A1Q2C7H7 A',
 'C5LAG4 T',
 'K0F9X7 A',
 'Q1K3N8 T',
 'A0A2V4EA49 C',
 'A0A562BXM4 A',
 'A0A4D6KHD1 T',
 'A0A4R6DFU8 A',
 'A0A4R7VEK0 A',
 'G0AFH4 A',
 'K5CFE5 A',
 'Q1H483 A',
 'A0A063Y780 S',
 'A0A1W5PRD1 L',
 'Q2YLQ6 A',
 'U5C4L4 T',
 'A0A8G2F3G4 A',
 'D5ELM4 T',
 'J2ZGN6 T',
 'Q84KJ6 I',
 'A0A211ZGL5 A',
 'A0A373FQ71 A',
 'A0A2S8FR08 A',
 'A0A7T2W1B3 A',
 'D4F313 A',
 'F4KY49 A',
 'A0A149V596 A',
 'A0A2S7YPJ9 A',
 'A0A2S0Q8P1 T',
 'Q7UYZ3 A',
 'J7ITF6 A',
 'Q9NIV0 M',
 'A0A1D8UWJ6 A',
 'C1MHX0 A',
 'F3QPR6 A',
 'A0A068NV61 T',
 'A0A1B9LFW3 C',
 'A0A7H8UK07 G',
 'A0AA91Q161 A',
 'A0AA92EGF5 A',
 'G7WFX4 A',
 'M9RJS5 A',
 'A0A1B9KID3 C',
 'A0A3E2UCG9 T',
 'S9QZ09 A',
 'A0A2S8GSU9 A',
 'J7IVQ1 T',
 'F0JGZ1 A',
 'F2AUF4 T',
 'A0A2S8GEJ5 T',
 'C6WEW7 A',
 'E5Y789 A',
 'J4KM12 A',
 'Q21P82 S',
 'Q5P470 A',
 'A0A0H3H4I7 G',
 'D5VJ32 A',
 'C8WLL8 A',
 'D2R355 A',
 'H2CJI0 T',
 'A0A2S5WGI8 A',
 'C1GR74 A',
 'A0A2S6GKF6 A',
 'A0A8H4GS02 A',
 'A0NJ07 A',
 'C6CBB1 G',
 'Q7NQY2 A',
 'A0A173R3X4 T',
 'A0A2G3E8V2 T',
 'A0A2S6H6B7 A',
 'A0A316BQ38 A',
 'A0A9W3LFI9 G',
 'B4S394 A',
 'F0ZPL3 T',
 'G0VI62 I',
 'A0A177W826 A',
 'A0A1H8D0R8 L',
 'Q07UM3 A',
 'S3K1S2 G',
 'A0A4V3ALP8 A',
 'A0A6G9XJV9 A',
 'F7NPQ3 A',
 'J4UGB7 A',
 'J7L3W8 A',
 'A0A0A2B651 T',
 'A0A258FTB0 A',
 'A4FMG0 A',
 'B7GKP4 A',
 'C3YB73 T',
 'C5BWX7 A',
 'I5C044 S',
 'T2KGT3 T',
 'A0A060UN76 A',
 'A0A258FS85 A',
 'A0A975BTN0 A',
 'A1SY01 T',
 'A8G2S3 T',
 'B2IJT1 A',
 'C0Z5S5 A',
 'Q21CP1 A',
 'A0A0A2C6L1 T',
 'A0A1H9M798 A',
 'D5E995 T',
 'C5CIT6 A',
 'D3RN22 A',
 'A0A5M4ATH9 A',
 'A0A9J9ES23 A',
 'C6XKC2 S',
 'D2SE15 A',
 'K9U8C7 T',
 'Q59UP8 I',
 'A0A1H4KAQ7 S',
 'A0A1I5GN22 A',
 'V5E0F3 A',
 'C1N6X9 T',
 'Q6CRN1 I',
 'R1EGK6 T',
 'W0F0I7 A',
 'A0A088E6Q7 G',
 'A0A318FY98 G',
 'D7E934 T',
 'K9ZLY2 T',
 'M1V7W3 S',
 'A0A2K3DPU7 -',
 'A0A2S7YIM5 A',
 'F3ZYD6 T',
 'F5R974 A',
 'I6Z905 T',
 'A1SZ12 S',
 'A2BP62 T',
 'B8FZP7 A',
 'K1LDP0 T',
 'A0A3S9N9F3 A',
 'A2C095 T',
 'C6DB68 A',
 'G0JRG9 I',
 'J7J5E7 A',
 'Q1K8A3 A',
 'Q2RM12 A',
 'Q7NCB8 A',
 'A0A2S0P9T4 A',
 'B0DU93 G',
 'D0LAL7 A',
 'D0MFE8 T',
 'I5AZQ4 A',
 'Q2YBP7 L',
 'Q81GN5 A',
 'A0A1B9NQ91 C',
 'A0A1T4SFY6 A',
 'A0A6H9FYW4 A',
 'A8ZQD5 T',
 'E2SD44 A',
 'F2JZ83 A',
 'H6LFQ2 T',
 'I3Z3H7 T',
 'A0A1M6JKY3 A',
 'A0A2J7TJ33 A',
 'Q7SEH0 A',
 'L8GFX3 A',
 'Q5KAF6 V',
 'K9YJQ3 T',
 'Q5FA36 A',
 'A6M3G0 A',
 'D9SI59 A',
 'B7G0Y1 T',
 'C1MX19 A',
 'D5T4N9 A',
 'A0A1B9M1A9 C',
 'A0A4R3NVT3 S',
 'A0A420KGW4 A',
 'B0SRS8 T',
 'D4GLQ6 G',
 'Q0ACK1 S',
 'S0ET45 A',
 'A0A1G7H8X3 A',
 'A0A1X4G8K1 A',
 'F8E6R1 S',
 'Q0G2V0 S',
 'A0A5P9P1L2 T',
 'A0A979GQ79 A',
 'A6VE60 A',
 'B9SA70 I',
 'E3H8C9 T',
 'M2A398 A',
 'A0A1J5NTP7 A',
 'A0A2S8F4W0 T',
 'Q9H310 L',
 'W0DZX1 A',
 'Q221S8 T',
 'Q6ND36 A',
 'A0A2C6C0X3 G',
 'A0A427KNL6 G',
 'A7HSN9 A',
 'A0A0X8X7Y7 S',
 'A0A248TDF2 C',
 'A0A5M5PZE2 T',
 'B1Y842 A',
 'D2R647 T',
 'D4H5F9 T',
 'D9QS43 T',
 'H1XV27 T',
 'A0A0A1ZMZ9 T',
 'A0A147GP06 C',
 'H6RWK9 A',
 'K9ZG59 A',
 'M2ALH9 T',
 'A0A423Y4I6 G',
 'A7S3L2 T',
 'A0AA35XZV0 A',
 'C7Q1E4 A',
 'G7WCB6 A',
 'R7PZ71 A',
 'A0A1H1U2Q6 A',
 'A0A562RGZ4 T',
 'F4GED5 A',
 'A0A0X8NXA9 A',
 'F3KUN4 A',
 'C8WSI9 A',
 'O66395 A',
 'Q0I445 A',
 'Q95P70 L',
 'A0A1W2GZ82 T',
 'A0A7U8C744 S',
 'A0A0E3R6S1 A',
 'A0A1I4ZIZ6 A',
 'Q6ND34 A',
 'A0A1G6ABL9 A',
 'A5D4I5 A',
 'K9P5D1 A',
 'A0A1B0ZRL8 S',
 'A7RNC3 T',
 'J1ASR8 A',
 'L0FU80 T',
 'A0A510HHK8 A',
 'D5AU98 A',
 'A0AA94HTL8 A',
 'A6W7U2 A',
 'F2JYR9 S',
 'M5SY07 A',
 'Q94CJ2 M',
 'W7QG13 S',
 'A0A1G9P6Q0 S',
 'A0A9Q8L398 A',
 'Q1QSQ2 S',
 'Q5KPM5 A',
 'A0A068SVR1 A',
 'A0A4P7UHQ5 A',
 'A0A101HKN9 T',
 'A0A1Y6GLJ1 G',
 'A0A562S8V2 A',
 'A0A8H6K7L7 A',
 'A0AA86YS65 A',
 'E7RJZ0 T',
 'A0A037ZMW1 S',
 'A0A0E3QY86 A',
 'F4H924 A',
 'Q8I0L6 M',
 'A0A257T7G4 I',
 'I0JI83 T',
 'Q45HK8 A',
 'K8EJ02 A',
 'Q2WBF7 A',
 'I4DBY0 A',
 'A0A142VAD6 A',
 'A0A482PLH3 G',
 'Q2IHY5 A',
 'R4FZE3 A',
 'A0A2A2MCP3 A',
 'A0A5M8QF12 A',
 'A0A5A7MAJ9 A',
 'A0A9P3CXY2 A',
 'B3MX93 T',
 'B9ACS5 A',
 'A0A085GI50 G',
 'A0A1B9K8L2 C',
 'A0A2X2C038 A',
 'Q1Z4I4 S',
 'A0A075WG29 T',
 'A0A2S6H643 A',
 'A0A6M3ZJI1 A',
 'A1ZGK6 T',
 'A2CCK1 T',
 'C7QGX3 A',
 'D0LTW3 T',
 'D3PKL4 A',
 'A0A0S4VNK2 A',
 'A0A410K1J5 T',
 'D5ASL9 A',
 'A0A369MRW6 A',
 'A6GJF5 T',
 'Q9UBD6 C',
 'A0A0A3XTJ3 A',
 'A0A264VQM8 A',
 'A0A1Z3MS36 G',
 'B3PIH2 A',
 'Q5FLR6 A',
 'A0A087MGU4 A',
 'A0A1Y2JH43 A',
 'L7CG11 A',
 'Q2RWY7 L',
 'Q6CRN0 I',
 'T2IEJ2 T',
 'A0A1B9MBX6 C',
 'B8J5X4 T',
 'A0A7S0ILH2 A',
 'A1VIG8 T',
 'P69681 G',
 'Q6LKC8 A',
 'Q84KJ7 V',
 'A0A0H3KTD3 G',
 'A0A1T4SFK4 A',
 'D3DJN2 A',
 'Q2FS34 A',
 'A0A165MFD1 T',
 'A0A1B9BUZ8 A',
 'A0A1G5W0P2 A',
 'A0A2T2Y0D5 G',
 'H6LKH6 A',
 'L0KGR8 A',
 'A0A0A2BBY0 T',
 'A0A0M3AB44 A',
 'A0A3N0AQL8 A',
 'A0A854QN45 A',
 'A7SGD4 T',
 'C1D4X0 A',
 'U3P8G1 A',
 'A0A147EQL9 A',
 'A0A375YPN6 S',
 'A0A533I6R2 A',
 'A0A1H1BPD6 A',
 'A0A495DND0 A',
 'A0A2N0MZ27 A',
 'A0A2U1SS17 A',
 'A0A0D7F328 A',
 'A0A0E3LMT4 -',
 'A0A7U3XVQ4 A',
 'B1Y6V4 T',
 'Q6BT62 I',
 'A0A0S2DQB6 A',
 'A0A258HS77 A',
 'A0A5C5TYS5 A',
 'A0A7U8C2Y6 A',
 'D4H2Y7 T',
 'G4R7P1 S',
 'R1FI09 T',
 'A0A074KZD8 T',
 'A0A2W4ZXC0 A',
 'A0A1H9RTW8 A',
 'A0A9E9L9J1 V',
 'A1SVA8 A',
 'M0D3Q9 T',
 'A0A087EQK8 A',
 'A0A0E3R4G0 -',
 'A0A369M386 A',
 'A0A3E2VY88 T',
 'I0WJ97 T',
 'Q6HM26 A',
 'W0DZS7 A',
 'A0A0E3BR91 A',
 'A0A1G6ABK5 A',
 'B7G0Y4 T',
 'B8JBH5 A',
 'D6Z5V9 T',
 'M5S9B4 T',
 'S0EUS1 Y',
 'V4CRP5 T',
 'A0A149UWF2 A',
 'A0RXK8 A',
 'B1Y8C9 C',
 'A0A212AV03 A',
 'A2BUP4 T',
 'A0A1E5BXA4 S',
 'A7SQ16 T',
 'B0DY50 M',
 'A0A0S4WFM4 A',
 'A0A6N4SPH9 T',
 'C5KTM6 T',
 'C9R9J0 A',
 'Q0F2M5 A',
 'Q2SIR0 A',
 'Q9VFA9 T',
 'A0A4Y4DZN4 A',
 'A0A977NL43 A',
 'A0A0A2VPU3 A',
 'A8MCL4 A',
 'A0A379A0S9 S',
 'A0A6F8TLE9 A',
 'Q8GQS1 A',
 'V3ZVE4 T',
 'A0A1T4SF40 A',
 'A0A2N7L7C8 A',
 'A0A074ME37 A',
 'Q8RUT6 T',
 'B0VMH1 A',
 'Q92BJ7 A',
 'A0A0L0TDW1 A',
 'A0A857DDJ7 A',
 'A0AA92K392 A',
 'B8GGC3 A',
 'Q7V4T8 T',
 'A0A0V8M0W6 A',
 'A0A5C4RNH5 A',
 'A0A511NGC7 A',
 'A0A149UP06 A',
 'A0A4R3A5P7 A',
 'A0A4U1JNL6 A',
 'Q21J04 A',
 'A0AIW5 A',
 'X5CNT2 I',
 'A0A2T5IHP0 L',
 'A0A5C6LWQ1 A',
 'A0A433ZQ80 A',
 'A7SED8 L',
 'A0A853MG28 T',
 'C0QSY0 A',
 'H1YF74 T',
 'H6LKX6 T',
 'Q47X17 V',
 'A0A037ZJY5 A',
 'A0A1B9MZ78 C',
 'B3PF77 S',
 'B4HDZ9 T',
 'E6W5C1 S',
 'M1WRK6 A',
 'A0A2G6JLT9 A',
 'A7I8Z2 A',
 'B2GFN1 A',
 'D2V6P8 L',
 'F2G6G4 S',
 'A0A1H7CU41 A',
 'A0A2S5WMT7 A',
 'A0A4Q2EAG7 G',
 'Q5KZZ9 A',
 'A0A1I0AQM4 L',
 'A0A1I7FBM5 L',
 'A8AC17 A',
 'A0A0D2UPA8 A',
 'A0A4R8GSH7 A',
 'C7NND3 T',
 'D3LBI0 A',
 'I7ZHW3 A',
 'Q0VPH4 T',
 'A8M670 A',
 'B0DU91 G',
 'E4T0A4 A',
 'F0Y9X3 T',
 'Q0G0A4 A',
 'A0A2S8FTB5 T',
 'A0LV78 A',
 'A0A2S8QA29 A',
 ...]

In [15]:
onesix

['A1D2Y5 S',
 'M8E0R3 S',
 'A0A2G3DSU6 D',
 'A0A328EMN2 S',
 'A0A6A1TYJ4 S',
 'D3RMV7 S',
 'F0J3F9 A',
 'G2ZN72 S',
 'I0KDC6 S',
 'A0A081N2G5 L',
 'A0A144NLT9 S',
 'B4D7W2 A',
 'F3QNA7 S',
 'Q4WHC6 S',
 'Q8JI14 -',
 'A0A395VB65 D',
 'A0A975GIX9 N',
 'Q5UZ98 T',
 'A0A4R4K1P9 S',
 'A0A7T4WEP4 N',
 'C6LBD3 D',
 'D5V7B3 I',
 'A0A4R3ZNW3 N',
 'A9BQZ4 S',
 'A0A642KQG8 T',
 'A9BIZ7 D',
 'K0NJH2 A',
 'Q2IK04 V',
 'T2KJ59 D',
 'A0A1B9M5B8 S',
 'A0A323UE08 S',
 'E8RLT5 A',
 'F6G5I9 S',
 'G3A431 S',
 'G4H971 T',
 'L1J6I4 C',
 'M0J579 D',
 'A0A377PBY1 S',
 'A0A401WUW1 A',
 'L1IYW7 S',
 'A0A315S845 N',
 'A0A6M3ZKU5 D',
 'A0A502GPV4 S',
 'A0A9J9BAE8 L',
 'A1AVV2 S',
 'B1XZU2 G',
 'Q5P1S8 D',
 'A0A0F5EZP7 S',
 'A0A4R7GKA0 S',
 'A0A2T4UWF1 S',
 'A0A3E0X011 L',
 'A0A4R8H081 D',
 'C7LQR9 D',
 'A0A0A2A0Y9 V',
 'A0A0A2A5X1 V',
 'A0A7T5BFQ2 D',
 'A3U857 S',
 'E1V4T3 L',
 'F0J7D3 N',
 'M7XJ51 T',
 'Q1K0H9 L',
 'A0A2S5XAB8 S',
 'A0A366IE34 S',
 'Q1Z695 D',
 'A0A8G2IZM3 S',
 'G3IYW2 S',
 'A0A2G5BGA9 S',
 'A0A5M4AUM9 S',
 'E3HJW8 S',
 'U1PIR6 D',
 'A0A1B9N3H7 S',
 'A0A2S5WV24 S',
 'A0A6U2BIY7 D',
 'A0A833LX85 V',
 'I9P003 L',
 'K8VZC6 S',
 'L1IUV5 S',
 'A0A0K2STQ7 V',
 'A0A2H1HV86 N',
 'Q2GX26 A',
 'A0A074KY88 I',
 'A0A858ZNJ3 S',
 'A0A3P2A7W8 S',
 'A0A7S4GND2 V',
 'O26757 -',
 'Q46G49 S',
 'A0A140NHJ5 A',
 'A0A2S8GF54 D',
 'B1JZ69 A',
 'E5Y678 T',
 'A0A149U2G9 A',
 'A0A9Q5QVI9 N',
 'Q18PF5 -',
 'A0A317FZW2 D',
 'G5EB13 S',
 'Q1YDY8 L',
 'A0A1X4GBG2 V',
 'A0A4Q7Y9I7 N',
 'I0HKQ8 S',
 'A0A097R891 S',
 'A0A7S4GMD8 D',
 'Q488X2 L',
 'U3PCH5 R',
 'A0A378YR15 S',
 'I1YG38 D',
 'F5XN43 N',
 'Q1IWN6 N',
 'A0A1E3PSK5 S',
 'A0A833H2R7 D',
 'A0A2T0XPP2 D',
 'A0A399T909 S',
 'L8GGA0 N',
 'A0A0D8BQX6 S',
 'A0A1M5ZVP9 D',
 'I5BYV5 I',
 'A0A0K2STH0 V',
 'A0A2N6K4Y5 N',
 'A0A1B9JZS5 S',
 'A0A2W0GQV0 S',
 'A0A369MHK2 N',
 'A0A087L0B9 S',
 'A0A0A2AMW2 V',
 'A0A377PLP5 S',
 'Q6BJI7 S',
 'Q7S5K0 T',
 'Q7Z1M1 D',
 'T2JFS5 V',
 'W0JIB3 T',
 'A0A1V2XMU9 A',
 'A0A2S6GKN5 S',
 'A0A7G5DK18 S',
 'A0A830ZZN8 S',
 'A0A8B4RWH8 S',
 'A0A9Q6P4A5 S',
 'B8ENL9 S',
 'Q9QXP0 -',
 'A0A060URC3 N',
 'A0A2W5HTC3 A',
 'A7S731 D',
 'A0A1Y0UZX2 A',
 'A0A257TE48 D',
 'Q2RVB5 A',
 'Q605Y6 S',
 'A0A918MJ52 I',
 'K6W5X0 N',
 'V4AP67 D',
 'A0A7Z0V0A4 S',
 'C0GKN4 D',
 'A9HMD6 A',
 'B1ZSW9 S',
 'K5DBA0 D',
 'V4REY8 L',
 'A0A0D2KGN8 S',
 'A0A242NIL1 S',
 'A8PXT8 M',
 'B7X047 S',
 'D2ZRW2 N',
 'H1Y7T6 S',
 'Q97L80 G',
 'A0A0S6UHP2 V',
 'A0A323UDG5 A',
 'E3I393 S',
 'A0A4V2X6C2 S',
 'D7G265 D',
 'A6LRS5 S',
 'D8J4C6 T',
 'F2NGJ8 N',
 'A0A0E9NHV4 S',
 'A1CQ21 S',
 'A0A6N2Z556 D',
 'Q0BWD0 L',
 'A0A071MMV1 A',
 'A0A168EVK8 S',
 'B3DUX7 S',
 'F5L8M7 T',
 'G7WJN0 D',
 'Q0BQ69 A',
 'A0A3N2SFS2 S',
 'A0A9Y2AG30 N',
 'A0AA46Q839 S',
 'E8RSE4 A',
 'F6BEI0 D',
 'I1DSU5 L',
 'I4C9L2 S',
 'Q5QVH2 L',
 'A0A068NPW2 S',
 'A0A6J5IRX5 A',
 'A0A3R9Q7C4 G',
 'A3ZT81 D',
 'K0ER80 N',
 'Q0VLH1 L',
 'Q2KZK9 S',
 'R9GM11 S',
 'A0A0T7GZ59 S',
 'A0A1G5PWV0 S',
 'S5ABR8 L',
 'W7QGM4 D',
 'F5Y3C1 S',
 'I8TC71 S',
 'M1P5F0 L',
 'A0A149RYW7 A',
 'A0A1J1JH03 V',
 'A0A1U9Z147 S',
 'A0A243SC06 I',
 'A0A3G9G2C9 A',
 'I4C9L0 S',
 'I4D1H5 S',
 'Q7W7D3 S',
 'A0A0B4M163 -',
 'A0A1M7UEG2 N',
 'A7HT14 D',
 'C8X554 G',
 'A0A127PIQ9 S',
 'A0A1B9JPL5 S',
 'W5WIX6 N',
 'A0AA40J491 S',
 'D8PD01 G',
 'A0A251XU71 S',
 'A0A2N6P374 Q',
 'B3QVV5 S',
 'K1K628 S',
 'A0A1E2SKM1 R',
 'A0A1I0BYN1 S',
 'A0A556RTU3 S',
 'A0A829X098 A',
 'D5EP68 I',
 'F0J6E8 S',
 'A0A073CP02 V',
 'A0A127JTU2 S',
 'C7BJG7 S',
 'D2BUJ8 S',
 'B8IZX4 S',
 'I3R0S7 D',
 'A0A3E2TW06 T',
 'B1Y0E5 A',
 'E6ME92 N',
 'A0A251Y3N4 S',
 'A0A380S5X4 V',
 'F0YLV7 D',
 'F8D7H6 T',
 'Q31CR9 V',
 'W0E077 D',
 'A5DYQ2 S',
 'A8LKQ0 L',
 'A0A4Y1MSE7 A',
 'A3TVQ9 L',
 'F2B2B8 S',
 'L0K9M1 D',
 'Q4WT12 S',
 'Q8ERT9 T',
 'A0A1H3WA00 S',
 'A0A1U9YY82 L',
 'A1DG05 S',
 'B8GGC1 S',
 'F3ZVV4 N',
 'P69680 S',
 'Q0G2T1 C',
 'A0A3T0SZ22 S',
 'A0A4R2Z2K6 S',
 'L1IYP4 S',
 'Q46HB1 V',
 'A0A149QAW7 A',
 'A0A1Y4L5P0 D',
 'A0A6B8N021 S',
 'D5EP71 S',
 'V5U2Z4 S',
 'A0A0E3QYF3 T',
 'A0A0K2STK6 V',
 'A0A8H7U3I1 S',
 'A0A062IU58 S',
 'A0A178TA08 S',
 'A0A3G9G4Q4 A',
 'A0A6H9FPY5 V',
 'A1C5Z7 S',
 'A0A0A1ZJU5 V',
 'A0A258HPP1 A',
 'G0H0Z6 D',
 'A0A2Z4MD56 T',
 'G0EFF3 S',
 'E2SD33 N',
 'E4TJ50 -',
 'A0A016XCG9 S',
 'A0A2S5Y0D3 S',
 'K9YN27 V',
 'Q3AFY9 N',
 'Q7N0M6 S',
 'W8KM07 L',
 'A0A0G9HEC5 S',
 'A5UJR1 N',
 'A0A9Q9D9I3 S',
 'B9SXC7 N',
 'C0QTA4 N',
 'A0A176XNC5 S',
 'A0A317G0I6 D',
 'A0A2S5CTX8 T',
 'U2EN72 L',
 'A0A248LNW8 D',
 'A0A4P8HC89 N',
 'G7UUY6 S',
 'A0A0E3WZH5 V',
 'A0A165K0X5 T',
 'D3FBG3 N',
 'Q608B6 D',
 'A0A854Q6X9 S',
 'H2IZ00 S',
 'A0A4V0XUI3 V',
 'A0A7S4GNJ2 V',
 'A0A2S5WX34 S',
 'C1D6X6 T',
 'A0A418VIJ8 S',
 'A0A857DMN9 S',
 'Q7T3R4 -',
 'R1D1H4 D',
 'T2J0N1 V',
 'A0A419AVL2 S',
 'K0K7J4 N',
 'A0A4U1K1W1 S',
 'A0A9R0NTP8 N',
 'B0RC35 S',
 'C8XB51 N',
 'E4NS62 D',
 'R9PMC6 D',
 'A0A1R1IDV3 S',
 'A0A2N6JV02 V',
 'A7MFK3 S',
 'B0BZN3 V',
 'F7ZEU9 L',
 'K9P718 V',
 'Q82X47 -',
 'Q8RUE9 -',
 'A0A0M2LU39 S',
 'A0A3N1VXY4 S',
 'A0A370FPU0 S',
 'A0A7G5DPV1 L',
 'A9UR54 D',
 'F0S0G1 N',
 'K9W4V5 V',
 'A0A015YIP3 D',
 'A0A291PMC6 A',
 'G8R7U9 S',
 'U1H1F7 A',
 'A0A021VMC6 N',
 'A0A855F5Y8 S',
 'A0A2W5VAZ2 S',
 'M0MDP9 T',
 'A0A1X3RP39 S',
 'A0A653N397 S',
 'A0A8G2F718 D',
 'F4B548 N',
 'I0ICG0 I',
 'A0A009TDB1 S',
 'A0A1G7DX68 S',
 'E4YA63 D',
 'Q2W5V2 D',
 'Q3AP28 G',
 'Q9BLG3 D',
 'A0A0D5YN10 S',
 'A0A0L0S493 S',
 'H1YCC3 L',
 'L8JUH3 T',
 'A0A0E3SHQ9 T',
 'A0A366XFS8 S',
 'E6VIW4 S',
 'F6FRU9 N',
 'A1VIM5 N',
 'E0TGP9 L',
 'A0A0E3SP24 S',
 'A0A8H6NAG3 S',
 'B8FGW0 G',
 'C3X1J1 S',
 'D9SI36 D',
 'E0TCV4 L',
 'E4U5Z1 N',
 'A0A094W9G3 I',
 'A0A7G5EC77 S',
 'A0A482TED1 D',
 'A0A4Q2QWS1 S',
 'A3PAY4 V',
 'A0A173R3W6 N',
 'A0A1B9BUU6 N',
 'A0A495D4X4 L',
 'A0A833GZR2 D',
 'D0L8H3 N',
 'F4XTK4 V',
 'I4D6Z7 T',
 'L8H844 D',
 'A0A0S6UEK9 G',
 'A0A1M6ZMI3 D',
 'U1SIR9 H',
 'A0A066ZTE4 L',
 'A9DQM8 D',
 'A0A0A0D6K5 S',
 'D6E7B3 N',
 'A0A562USB9 L',
 'C7LW87 G',
 'G0JRG6 N',
 'A0A1X6N3Q5 S',
 'A0A1Y4LM49 D',
 'B7FSA7 D',
 'E1QIU3 D',
 'H2CDR5 D',
 'Q1K433 D',
 'Q1QS12 A',
 'Q7T070 -',
 'A0A0H3DR67 S',
 'A5CRL2 S',
 'A0A836M2B6 S',
 'E6SF19 N',
 'I2GD40 S',
 'Q18ES8 D',
 'A0A060UWC8 N',
 'A0A0U1NJW3 L',
 'A0A7R6PER3 L',
 'A4G1J2 S',
 'A9AUR8 S',
 'C1N5A7 D',
 'D3S2L0 N',
 'F8IJE0 T',
 'A0A0D2LEF5 S',
 'A0A1H1MB73 S',
 'W7QGE0 S',
 'G2T1Y3 D',
 'L7CG99 D',
 'A0A1I0C958 D',
 'A0KPE9 S',
 'A9V5W4 -',
 'F5RGM7 S',
 'A0A1C6Z081 S',
 'A0A1D3GAE9 S',
 'A0A410JZR4 N',
 'A8N2H6 S',
 'I1YJH7 L',
 'A0A2G5BI87 S',
 'A0A2N6NEK4 S',
 'A0A1Y0HX98 N',
 'C3YB74 D',
 'Q1H0G2 D',
 'Q2FQT3 S',
 'S0APH6 N',
 'A0A075WEB4 S',
 'A0A172RYW3 N',
 'I3C0V3 D',
 'A0A556SRH6 S',
 'A0A7U4DN04 G',
 'A0A1V3SSW1 I',
 'Q466Y3 T',
 'A0A0A2ZRL7 A',
 'A0A0H3LUA3 S',
 'A4G0C5 D',
 'A5E3X2 S',
 'A8P923 S',
 'B8EMQ8 D',
 'D0MFE9 N',
 'A0A060HFT5 N',
 'A0A060JMP6 S',
 'A0A8E2UDJ3 S',
 'I4D6Z9 T',
 'Q13E03 S',
 'Q1JXS5 S',
 'A0A076PL76 S',
 'A0A6N2TIA4 D',
 'Q1AUG3 N',
 'A0A098S5Y7 I',
 'A0A7S4GNF3 V',
 'A0A5J6WQU1 L',
 'A2SS52 S',
 'M9RKT6 L',
 'A0A2K1RA77 N',
 'A0A2K1RA81 N',
 'A0A2S0JW39 T',
 'A0A2T9X1V4 N',
 'D3F545 N',
 'A0A1E3PQH0 N',
 'A0A1J5JH24 G',
 'C4Y298 S',
 'Q3B6Q2 G',
 'Q7TNN9 -',
 'A0A4Y7XC43 S',
 'A0A5B2V3B9 S',
 'B9L7N1 N',
 'C7M2A9 N',
 'D2V6Q5 G',
 'E4T3F7 N',
 'F2YIC4 -',
 'Q0G0A3 L',
 'A0A424WAH3 S',
 'B8ZYW3 T',
 'U7VB41 T',
 'A0A7S0KKL8 D',
 'A0A1C7EL50 T',
 'A0A6G9Y3Q0 N',
 'A0A6S5K4J1 S',
 'G0LFE3 D',
 'J9VXX9 S',
 'V4RHR4 C',
 'A0A0D7F2Y9 S',
 'A0A1S8D478 A',
 'Q47K18 S',
 'B9SWW9 N',
 'L8H5K0 -',
 'A0A369N7Y3 N',
 'A0A399NT81 S',
 'B0SLB7 S',
 'B4CV94 S',
 'E1IF27 S',
 'G2PRJ6 D',
 'A0A202B535 A',
 'A0A2M9D7S8 S',
 'Q6LMI6 L',
 'K2JVF8 L',
 'Q1Q357 D',
 'B8FDY8 G',
 'B8FL88 D',
 'E3H8A6 D',
 'H8L2Q4 S',
 'A0A248LMH8 S',
 'A0A5C5BWI6 N',
 'L1INN6 D',
 'M7NFH3 S',
 'A0A060URB8 A',
 'K9W6F3 N',
 'A0A7S0D560 S',
 'D2Q0J8 N',
 'A0A251YU48 S',
 'A0A6H9GEE4 V',
 'A0A8F5ZDT8 S',
 'C1G973 S',
 'M0D580 D',
 'A0A1Y5E3E3 S',
 'A0A328Q6M1 N',
 'Q7UGU7 D',
 'A0A660CH85 N',
 'E4T3F3 I',
 'A0A6H9GFU4 N',
 'A3XNG6 D',
 'B9LU00 T',
 'E4RTK5 S',
 'H6LKH9 N',
 'Q0AT01 L',
 'A0A330GB00 S',
 'A0A657K391 S',
 'Q2N625 S',
 'E3GI40 D',
 'F4Y3C5 V',
 'A0A017SYR8 S',
 'A0A494JB70 S',
 'D4XLN6 S',
 'Q1YDY7 S',
 'A0A2G5RQK9 S',
 'A0A369NYJ2 N',
 'A0A1Q2C7H7 N',
 'C5LAG4 D',
 'K0F9X7 N',
 'Q1K3N8 D',
 'A0A2V4EA49 S',
 'A0A562BXM4 S',
 'A0A4D6KHD1 T',
 'A0A4R6DFU8 S',
 'A0A4R7VEK0 S',
 'G0AFH4 S',
 'K5CFE5 S',
 'Q1H483 S',
 'A0A063Y780 L',
 'A0A1W5PRD1 -',
 'Q2YLQ6 S',
 'U5C4L4 T',
 'A0A8G2F3G4 G',
 'D5ELM4 D',
 'J2ZGN6 T',
 'Q84KJ6 N',
 'A0A211ZGL5 S',
 'A0A373FQ71 S',
 'A0A2S8FR08 G',
 'A0A7T2W1B3 N',
 'D4F313 S',
 'F4KY49 S',
 'A0A149V596 A',
 'A0A2S7YPJ9 S',
 'A0A2S0Q8P1 V',
 'Q7UYZ3 S',
 'J7ITF6 S',
 'Q9NIV0 -',
 'A0A1D8UWJ6 A',
 'C1MHX0 T',
 'F3QPR6 S',
 'A0A068NV61 M',
 'A0A1B9LFW3 S',
 'A0A7H8UK07 S',
 'A0AA91Q161 S',
 'A0AA92EGF5 S',
 'G7WFX4 T',
 'M9RJS5 S',
 'A0A1B9KID3 S',
 'A0A3E2UCG9 T',
 'S9QZ09 S',
 'A0A2S8GSU9 S',
 'J7IVQ1 D',
 'F0JGZ1 A',
 'F2AUF4 D',
 'A0A2S8GEJ5 D',
 'C6WEW7 N',
 'E5Y789 S',
 'J4KM12 S',
 'Q21P82 L',
 'Q5P470 S',
 'A0A0H3H4I7 S',
 'D5VJ32 S',
 'C8WLL8 S',
 'D2R355 G',
 'H2CJI0 D',
 'A0A2S5WGI8 N',
 'C1GR74 S',
 'A0A2S6GKF6 S',
 'A0A8H4GS02 S',
 'A0NJ07 N',
 'C6CBB1 S',
 'Q7NQY2 A',
 'A0A173R3X4 D',
 'A0A2G3E8V2 D',
 'A0A2S6H6B7 S',
 'A0A316BQ38 S',
 'A0A9W3LFI9 S',
 'B4S394 G',
 'F0ZPL3 N',
 'G0VI62 S',
 'A0A177W826 S',
 'A0A1H8D0R8 -',
 'Q07UM3 S',
 'S3K1S2 S',
 'A0A4V3ALP8 S',
 'A0A6G9XJV9 N',
 'F7NPQ3 S',
 'J4UGB7 Q',
 'J7L3W8 N',
 'A0A0A2B651 V',
 'A0A258FTB0 S',
 'A4FMG0 N',
 'B7GKP4 S',
 'C3YB73 D',
 'C5BWX7 N',
 'I5C044 L',
 'T2KGT3 I',
 'A0A060UN76 D',
 'A0A258FS85 A',
 'A0A975BTN0 N',
 'A1SY01 D',
 'A8G2S3 V',
 'B2IJT1 S',
 'C0Z5S5 T',
 'Q21CP1 A',
 'A0A0A2C6L1 V',
 'A0A1H9M798 N',
 'D5E995 T',
 'C5CIT6 -',
 'D3RN22 D',
 'A0A5M4ATH9 S',
 'A0A9J9ES23 D',
 'C6XKC2 L',
 'D2SE15 N',
 'K9U8C7 V',
 'Q59UP8 S',
 'A0A1H4KAQ7 L',
 'A0A1I5GN22 N',
 'V5E0F3 S',
 'C1N6X9 D',
 'Q6CRN1 S',
 'R1EGK6 D',
 'W0F0I7 S',
 'A0A088E6Q7 N',
 'A0A318FY98 S',
 'D7E934 T',
 'K9ZLY2 D',
 'M1V7W3 D',
 'A0A2K3DPU7 -',
 'A0A2S7YIM5 Q',
 'F3ZYD6 D',
 'F5R974 D',
 'I6Z905 T',
 'A1SZ12 L',
 'A2BP62 V',
 'B8FZP7 S',
 'K1LDP0 I',
 'A0A3S9N9F3 A',
 'A2C095 V',
 'C6DB68 S',
 'G0JRG9 N',
 'J7J5E7 G',
 'Q1K8A3 A',
 'Q2RM12 G',
 'Q7NCB8 N',
 'A0A2S0P9T4 A',
 'B0DU93 S',
 'D0LAL7 N',
 'D0MFE8 D',
 'I5AZQ4 N',
 'Q2YBP7 -',
 'Q81GN5 S',
 'A0A1B9NQ91 S',
 'A0A1T4SFY6 N',
 'A0A6H9FYW4 N',
 'A8ZQD5 D',
 'E2SD44 S',
 'F2JZ83 D',
 'H6LFQ2 D',
 'I3Z3H7 I',
 'A0A1M6JKY3 G',
 'A0A2J7TJ33 S',
 'Q7SEH0 S',
 'L8GFX3 N',
 'Q5KAF6 S',
 'K9YJQ3 V',
 'Q5FA36 S',
 'A6M3G0 N',
 'D9SI59 S',
 'B7G0Y1 D',
 'C1MX19 S',
 'D5T4N9 H',
 'A0A1B9M1A9 S',
 'A0A4R3NVT3 L',
 'A0A420KGW4 S',
 'B0SRS8 D',
 'D4GLQ6 S',
 'Q0ACK1 L',
 'S0ET45 N',
 'A0A1G7H8X3 S',
 'A0A1X4G8K1 N',
 'F8E6R1 L',
 'Q0G2V0 A',
 'A0A5P9P1L2 T',
 'A0A979GQ79 S',
 'A6VE60 S',
 'B9SA70 N',
 'E3H8C9 D',
 'M2A398 S',
 'A0A1J5NTP7 G',
 'A0A2S8F4W0 D',
 'Q9H310 -',
 'W0DZX1 D',
 'Q221S8 S',
 'Q6ND36 A',
 'A0A2C6C0X3 S',
 'A0A427KNL6 S',
 'A7HSN9 D',
 'A0A0X8X7Y7 L',
 'A0A248TDF2 T',
 'A0A5M5PZE2 T',
 'B1Y842 D',
 'D2R647 D',
 'D4H5F9 D',
 'D9QS43 D',
 'H1XV27 D',
 'A0A0A1ZMZ9 V',
 'A0A147GP06 S',
 'H6RWK9 N',
 'K9ZG59 N',
 'M2ALH9 D',
 'A0A423Y4I6 S',
 'A7S3L2 D',
 'A0AA35XZV0 S',
 'C7Q1E4 N',
 'G7WCB6 G',
 'R7PZ71 N',
 'A0A1H1U2Q6 N',
 'A0A562RGZ4 A',
 'F4GED5 S',
 'A0A0X8NXA9 S',
 'F3KUN4 S',
 'C8WSI9 T',
 'O66395 S',
 'Q0I445 S',
 'Q95P70 -',
 'A0A1W2GZ82 I',
 'A0A7U8C744 L',
 'A0A0E3R6S1 G',
 'A0A1I4ZIZ6 A',
 'Q6ND34 S',
 'A0A1G6ABL9 S',
 'A5D4I5 S',
 'K9P5D1 N',
 'A0A1B0ZRL8 L',
 'A7RNC3 D',
 'J1ASR8 A',
 'L0FU80 T',
 'A0A510HHK8 N',
 'D5AU98 S',
 'A0AA94HTL8 S',
 'A6W7U2 N',
 'F2JYR9 A',
 'M5SY07 S',
 'Q94CJ2 -',
 'W7QG13 L',
 'A0A1G9P6Q0 L',
 'A0A9Q8L398 S',
 'Q1QSQ2 L',
 'Q5KPM5 S',
 'A0A068SVR1 S',
 'A0A4P7UHQ5 S',
 'A0A101HKN9 D',
 'A0A1Y6GLJ1 S',
 'A0A562S8V2 S',
 'A0A8H6K7L7 S',
 'A0AA86YS65 A',
 'E7RJZ0 T',
 'A0A037ZMW1 L',
 'A0A0E3QY86 S',
 'F4H924 A',
 'Q8I0L6 -',
 'A0A257T7G4 N',
 'I0JI83 T',
 'Q45HK8 S',
 'K8EJ02 N',
 'Q2WBF7 G',
 'I4DBY0 S',
 'A0A142VAD6 S',
 'A0A482PLH3 S',
 'Q2IHY5 H',
 'R4FZE3 S',
 'A0A2A2MCP3 -',
 'A0A5M8QF12 S',
 'A0A5A7MAJ9 S',
 'A0A9P3CXY2 S',
 'B3MX93 D',
 'B9ACS5 N',
 'A0A085GI50 S',
 'A0A1B9K8L2 S',
 'A0A2X2C038 S',
 'Q1Z4I4 L',
 'A0A075WG29 D',
 'A0A2S6H643 S',
 'A0A6M3ZJI1 S',
 'A1ZGK6 I',
 'A2CCK1 V',
 'C7QGX3 N',
 'D0LTW3 V',
 'D3PKL4 N',
 'A0A0S4VNK2 S',
 'A0A410K1J5 D',
 'D5ASL9 S',
 'A0A369MRW6 N',
 'A6GJF5 V',
 'Q9UBD6 -',
 'A0A0A3XTJ3 S',
 'A0A264VQM8 S',
 'A0A1Z3MS36 S',
 'B3PIH2 S',
 'Q5FLR6 N',
 'A0A087MGU4 S',
 'A0A1Y2JH43 S',
 'L7CG11 S',
 'Q2RWY7 G',
 'Q6CRN0 S',
 'T2IEJ2 V',
 'A0A1B9MBX6 S',
 'B8J5X4 V',
 'A0A7S0ILH2 T',
 'A1VIG8 S',
 'P69681 S',
 'Q6LKC8 D',
 'Q84KJ7 N',
 'A0A0H3KTD3 S',
 'A0A1T4SFK4 A',
 'D3DJN2 N',
 'Q2FS34 A',
 'A0A165MFD1 D',
 'A0A1B9BUZ8 A',
 'A0A1G5W0P2 N',
 'A0A2T2Y0D5 S',
 'H6LKH6 N',
 'L0KGR8 A',
 'A0A0A2BBY0 V',
 'A0A0M3AB44 S',
 'A0A3N0AQL8 N',
 'A0A854QN45 S',
 'A7SGD4 D',
 'C1D4X0 S',
 'U3P8G1 S',
 'A0A147EQL9 N',
 'A0A375YPN6 A',
 'A0A533I6R2 S',
 'A0A1H1BPD6 N',
 'A0A495DND0 S',
 'A0A2N0MZ27 S',
 'A0A2U1SS17 S',
 'A0A0D7F328 A',
 'A0A0E3LMT4 V',
 'A0A7U3XVQ4 S',
 'B1Y6V4 S',
 'Q6BT62 S',
 'A0A0S2DQB6 S',
 'A0A258HS77 A',
 'A0A5C5TYS5 S',
 'A0A7U8C2Y6 D',
 'D4H2Y7 D',
 'G4R7P1 L',
 'R1FI09 D',
 'A0A074KZD8 I',
 'A0A2W4ZXC0 S',
 'A0A1H9RTW8 S',
 'A0A9E9L9J1 S',
 'A1SVA8 D',
 'M0D3Q9 T',
 'A0A087EQK8 N',
 'A0A0E3R4G0 V',
 'A0A369M386 N',
 'A0A3E2VY88 T',
 'I0WJ97 I',
 'Q6HM26 S',
 'W0DZS7 S',
 'A0A0E3BR91 S',
 'A0A1G6ABK5 D',
 'B7G0Y4 D',
 'B8JBH5 H',
 'D6Z5V9 I',
 'M5S9B4 D',
 'S0EUS1 A',
 'V4CRP5 D',
 'A0A149UWF2 A',
 'A0RXK8 N',
 'B1Y8C9 S',
 'A0A212AV03 S',
 'A2BUP4 V',
 'A0A1E5BXA4 L',
 'A7SQ16 D',
 'B0DY50 S',
 'A0A0S4WFM4 S',
 'A0A6N4SPH9 T',
 'C5KTM6 D',
 'C9R9J0 N',
 'Q0F2M5 D',
 'Q2SIR0 D',
 'Q9VFA9 D',
 'A0A4Y4DZN4 N',
 'A0A977NL43 N',
 'A0A0A2VPU3 Q',
 'A8MCL4 N',
 'A0A379A0S9 L',
 'A0A6F8TLE9 S',
 'Q8GQS1 A',
 'V3ZVE4 D',
 'A0A1T4SF40 A',
 'A0A2N7L7C8 D',
 'A0A074ME37 S',
 'Q8RUT6 D',
 'B0VMH1 S',
 'Q92BJ7 S',
 'A0A0L0TDW1 S',
 'A0A857DDJ7 S',
 'A0AA92K392 S',
 'B8GGC3 S',
 'Q7V4T8 V',
 'A0A0V8M0W6 S',
 'A0A5C4RNH5 S',
 'A0A511NGC7 S',
 'A0A149UP06 A',
 'A0A4R3A5P7 S',
 'A0A4U1JNL6 S',
 'Q21J04 S',
 'A0AIW5 S',
 'X5CNT2 N',
 'A0A2T5IHP0 -',
 'A0A5C6LWQ1 S',
 'A0A433ZQ80 S',
 'A7SED8 -',
 'A0A853MG28 V',
 'C0QSY0 N',
 'H1YF74 M',
 'H6LKX6 D',
 'Q47X17 S',
 'A0A037ZJY5 S',
 'A0A1B9MZ78 S',
 'B3PF77 M',
 'B4HDZ9 D',
 'E6W5C1 I',
 'M1WRK6 A',
 'A0A2G6JLT9 D',
 'A7I8Z2 D',
 'B2GFN1 N',
 'D2V6P8 -',
 'F2G6G4 L',
 'A0A1H7CU41 G',
 'A0A2S5WMT7 S',
 'A0A4Q2EAG7 S',
 'Q5KZZ9 S',
 'A0A1I0AQM4 -',
 'A0A1I7FBM5 -',
 'A8AC17 S',
 'A0A0D2UPA8 G',
 'A0A4R8GSH7 D',
 'C7NND3 T',
 'D3LBI0 N',
 'I7ZHW3 S',
 'Q0VPH4 D',
 'A8M670 N',
 'B0DU91 S',
 'E4T0A4 S',
 'F0Y9X3 D',
 'Q0G0A4 S',
 'A0A2S8FTB5 D',
 'A0LV78 A',
 'A0A2S8QA29 S',
 ...]

In [16]:
mer = []

for a in sevenone:
    ab = a.split(' ')[0]
    ac = a.split(' ')[1]

In [17]:
mer

[]

In [18]:
for record in alignment:
    print(alignment[:, 70])

YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY
YEEYYYYYYEYYYYMEYEYYEEYYEEEEEYYYYYEYEYYYYEYEYEEYYYEEEEEEYEYEEYYEYYYYYEYYEEEYYEYYEYYE-YYEYYYYMEYEEYYYCESYEYYYEEYYEEEEYYYYYEYYYEEEYYYYYYYMYYEYEYYEYEYEYYEEYYYYYYYEYYYEYEYYYEEYYYEEYYYYYEEYEYYYEYEYYYYEEYYEYEYYYYYYMYEYYYYYYYYYYSYYY-YEYYYYEEYYYEEEEEYEYEYEYEYEYYYYEYYYEYEYYYEEYYEYEYEYEEYYYYYEYYEYYYYYYEEEEYYEEYEYYEEYYYYMEEYYYYYYEEYEYEEEMMYYYEEYEEYYYYYYEYYEYEYYEEYEYYYEEYYYYEYYYYEEYEYEYEYYEEYEYEYEYEEYYEYYYECEEEYMYYYYYEYEEYYCYYYYYEEEYMYYYYYEYYYEEYYYYEYYEEYYEYYYYYYYEYYYEEEEEYEYYEYEYYYYMYYYYEYMEYEYCEYYEYEYYYYMYYYY-EYYEEEYEEYYYEEYYYYYEYYEYYEYEYEEYYEYYYYEYYYYEYYEYEYYEYYYYYEMYEYEEYYYYYYYYYEYYMYYYEYYYYYYYEYYEYEEYYYEYYYYYEYYYY-YYEEYYYYEYYMYYYYYYYEYYEEYEEEYYEEYEYEYEYEYEEYEYEYYCYEYYYEETMYEEEEEYEYEYYYYYYYYYEYMYYYYEYEEEYYYYYEYYYCYYYEYEYEYYYEEEYYYEYYEMEYYYYEEEEEEEEEEYYYEYEYYYYYEYYYYYYMEEYYYYYYEEYEEYYYEYMEEYEYYYEYYYYEEYYMYEYYYYYYYEYYYYEYYYYEEYYEEYEYYEYYEMYYYYYYYYQYEYEYYYEYYYYYEYYYYYEYYYEYYYEYYYYYYEYYYYYYEEEEEYYYEEYEYEEYYYECYEETEYYYYEEEYYEEYEEEYYYYEYYEYEYCYYYYYYEYYYYYYYYYMYYLEYEEYYYEEE-EYYMEYYYEMMYYEE-YEYYYEYEYYYEYYYYYEYEYEYYEEEYCYYEYEYYYEEYYYYEYYYYYEYYYYEYEEYYYEYYEYEYYYEYYYCYMEEEYEEEYYYYYYEYEEYYYEEYYYYYEEYYYEYEEYYEYEYEEYYYYEYYYYEEYYEEEMYYEYEYEYYYYYYYEEYYYYEYEYEEYYYYYEEMEYYYYEYYYYYYEYYYYEYEYYYYYEYEEYMY-YEYEEEYEYYYYEEEYE-YYEEYEYEECYYYEYTCEYYYYYEYYYCYEEYEYEYEYYYYYEYMCYEYYYYYYYYEYYYEEYEYMEY

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(idid)

In [21]:
df['71'] = seqseq

In [22]:
df

               0   71
0         A1D2Y5  (Y)
1         M8E0R3  (E)
2     A0A2G3DSU6  (E)
3     A0A328EMN2  (Y)
4     A0A6A1TYJ4  (Y)
...          ...  ...
1276      G7WFX2  (E)
1277      Q6BK68  (Y)
1278      Q9QUT0  (M)
1279  A0A1E5C7W4  (E)
1280  A0A1Y3U5V2  (Y)

[1281 rows x 2 columns]

In [23]:
df['103'] = seqot

In [24]:
df['106'] = seqos

In [25]:
df['242'] = seqtft

In [26]:
df

               0   71  103  106  242
0         A1D2Y5  (Y)  (S)  (S)  (A)
1         M8E0R3  (E)  (Q)  (S)  (A)
2     A0A2G3DSU6  (E)  (N)  (D)  (T)
3     A0A328EMN2  (Y)  (N)  (S)  (A)
4     A0A6A1TYJ4  (Y)  (N)  (S)  (A)
...          ...  ...  ...  ...  ...
1276      G7WFX2  (E)  (N)  (T)  (T)
1277      Q6BK68  (Y)  (S)  (T)  (C)
1278      Q9QUT0  (M)  (-)  (-)  (L)
1279  A0A1E5C7W4  (E)  (I)  (D)  (A)
1280  A0A1Y3U5V2  (Y)  (N)  (N)  (G)

[1281 rows x 5 columns]

In [27]:
df = df.set_index(0)

In [28]:
df['merged'] = df.index.astype(str) + ' ' + df['71'].astype(str) + df['103'].astype(str) + df['106'].astype(str)+ df['242'].astype(str)

In [29]:
df['first'] = df.index + ' ' + df['71'].astype(str)

In [30]:
df

             71  103  106  242           merged         first
0
A1D2Y5      (Y)  (S)  (S)  (A)      A1D2Y5 YSSA      A1D2Y5 Y
M8E0R3      (E)  (Q)  (S)  (A)      M8E0R3 EQSA      M8E0R3 E
A0A2G3DSU6  (E)  (N)  (D)  (T)  A0A2G3DSU6 ENDT  A0A2G3DSU6 E
A0A328EMN2  (Y)  (N)  (S)  (A)  A0A328EMN2 YNSA  A0A328EMN2 Y
A0A6A1TYJ4  (Y)  (N)  (S)  (A)  A0A6A1TYJ4 YNSA  A0A6A1TYJ4 Y
...         ...  ...  ...  ...              ...           ...
G7WFX2      (E)  (N)  (T)  (T)      G7WFX2 ENTT      G7WFX2 E
Q6BK68      (Y)  (S)  (T)  (C)      Q6BK68 YSTC      Q6BK68 Y
Q9QUT0      (M)  (-)  (-)  (L)      Q9QUT0 M--L      Q9QUT0 M
A0A1E5C7W4  (E)  (I)  (D)  (A)  A0A1E5C7W4 EIDA  A0A1E5C7W4 E
A0A1Y3U5V2  (Y)  (N)  (N)  (G)  A0A1Y3U5V2 YNNG  A0A1Y3U5V2 Y

[1281 rows x 6 columns]

In [31]:
df['four_residues'] = df['71'].astype(str) + df['103'].astype(str) + df['106'].astype(str)+ df['242'].astype(str)

In [32]:
df['first_residue'] = df['71'].astype(str)

In [33]:
df_new = pd.DataFrame(df.index)

In [34]:
df_new = df_new.set_index(0)

In [35]:
df_new['first residue'] = df['first_residue']

In [36]:
df_new['four residues'] = df['four_residues']

In [37]:
df_new

           first residue four residues
0
A1D2Y5                 Y          YSSA
M8E0R3                 E          EQSA
A0A2G3DSU6             E          ENDT
A0A328EMN2             Y          YNSA
A0A6A1TYJ4             Y          YNSA
...                  ...           ...
G7WFX2                 E          ENTT
Q6BK68                 Y          YSTC
Q9QUT0                 M          M--L
A0A1E5C7W4             E          EIDA
A0A1Y3U5V2             Y          YNNG

[1281 rows x 2 columns]

In [38]:
full = df['merged'].to_list()

In [39]:
first = df['first'].to_list()

In [40]:
seqs = []
for u in full:
    seqs.append(u.split(' ')[1])

In [41]:
seqsset = set(seqs)

In [42]:
seqsset

{'---A',
 '-NAA',
 '-NAT',
 '-NDT',
 '-NIT',
 '-NNA',
 '-NSA',
 'CNDG',
 'CNDT',
 'CTDT',
 'EAAT',
 'EADT',
 'EATT',
 'EGDT',
 'EIDA',
 'EIGT',
 'EINA',
 'EKSL',
 'ENAS',
 'ENCS',
 'ENDS',
 'ENDT',
 'ENGT',
 'ENI-',
 'ENIA',
 'ENIN',
 'ENIS',
 'ENIT',
 'ENLS',
 'ENMS',
 'ENMT',
 'ENNT',
 'ENTS',
 'ENTT',
 'ENV-',
 'ENVT',
 'EQSA',
 'ESDT',
 'ESTT',
 'ETST',
 'ETTA',
 'ETTC',
 'ETTT',
 'EVDA',
 'EVNA',
 'EVTT',
 'L--L',
 'M---',
 'M--C',
 'M--L',
 'M--M',
 'QGGL',
 'SGRS',
 'TNAY',
 'TNDS',
 'TNDT',
 'Y--A',
 'Y--V',
 'Y-TA',
 'YAHA',
 'YANA',
 'YATM',
 'YDNA',
 'YDTA',
 'YFNG',
 'YGNA',
 'YHMA',
 'YHSA',
 'YHSI',
 'YKAA',
 'YKAG',
 'YKGA',
 'YKGG',
 'YKHA',
 'YKIA',
 'YKLA',
 'YKNA',
 'YKSA',
 'YKSC',
 'YKSG',
 'YKTA',
 'YKTP',
 'YN-A',
 'YNAA',
 'YNAV',
 'YNCA',
 'YNDA',
 'YNGA',
 'YNHA',
 'YNMV',
 'YNNA',
 'YNNG',
 'YNNT',
 'YNSA',
 'YNSC',
 'YNSG',
 'YNSM',
 'YNSS',
 'YNST',
 'YNSV',
 'YNTA',
 'YQSA',
 'YQTA',
 'YRNA',
 'YRSA',
 'YSAA',
 'YSAS',
 'YSNA',
 'YSNS',
 'YSQA',
 'YSSA',
 'YSSG',
 'YSSS',
 'YSTC',
 'YWNI',
 'YWNL',
 'YWNV',
 'YYNA',
 'YYNI',
 'YYNV'}

In [133]:
ENDT = []
ENTT = []

for o in full:
    if o.split(' ')[1] == "ENDT":
        # print(o.split(' ')[0])
        ENDT.append(o.split(' ')[0])
    elif o.split(' ')[1] == "ENTT":
        # print(o.split(' ')[0])
        ENTT.append(o.split(' ')[0])

In [148]:
Y = []
E =[]
M=[]

for y in first:
    if y.split(' ')[1] == 'Y':
        Y.append(y.split(' ')[0])
    elif y.split(' ')[1] == 'E':
        E.append(y.split(' ')[0])
    elif y.split(' ')[1] == 'M':
        M.append(y.split(' ')[0])

In [127]:
t = Tree('TBE_named_tree_midpoint_ladder.new')

In [182]:
tr = Tree('TBE_named_tree.new')

In [183]:
tr.ladderize()

1332

In [214]:
def conditional_function(node):
        for node in t:
            if node.name.split(' ')[-1] in idhh:
                nst1 = NodeStyle()
                nst1['bgcolor'] = 'IndianRed'
                node.set_style(nst1)
            elif node.name.split(' ')[-1] in idhe:
                nst2 = NodeStyle()
                nst2['bgcolor'] = 'ForestGreen'
                node.set_style(nst2)
            # elif node.name.split(' ')[-1] in M:
            #     nst3 = NodeStyle()
            #     nst3['bgcolor'] = 'Tan'
            #     node.set_style(nst3)

In [215]:
new_size = 2

def make_branches_bigger(node):
    node.img_style["hz_line_width"] = new_size # Change the horizotal lines stroke size
    node.img_style["vt_line_width"] = new_size # Change the vertical lines stroke size
    for c in node.children:
        make_branches_bigger(c)

In [217]:
ts = ete3.TreeStyle()
ts.layout_fn = conditional_function, make_branches_bigger
ts.mode = "c"

ts.show_branch_support = True
ts.show_leaf_name = True

t.render("twinHis.pdf", tree_style=ts)

{'nodes': [[10808.088540562107,
   9349.558989595149,
   10812.623830676383,
   9354.094279709425,
   0,
   None],
  [11041.266571057857,
   9125.150489463227,
   11045.316394315181,
   9129.200312720552,
   1,
   None],
  [11971.314454807021,
   9100.851289716027,
   11975.314454807021,
   9104.851289716027,
   2,
   None],
  [13146.855029487831,
   9202.25517365329,
   13150.954039707736,
   9206.354183873194,
   3,
   None],
  [13898.845114838232,
   9140.33303131802,
   13902.877906956375,
   9144.365823436163,
   4,
   None],
  [14118.497995628004,
   9124.44514734616,
   14122.51676731546,
   9128.463919033615,
   5,
   None],
  [13967.110133148512,
   9158.05806246023,
   13971.156895502038,
   9162.104824813756,
   6,
   None],
  [14576.322744127147,
   9152.347527008696,
   14580.360198576273,
   9156.384981457823,
   7,
   None],
  [13971.969148684437,
   9169.569484161002,
   13976.025196556042,
   9173.625532032607,
   8,
   None],
  [13275.07539442952,
   9275.803537966462,
   13279.23946071776,
   9279.967604254702,
   9,
   None],
  [14561.178800196703,
   9228.45373619075,
   14565.271191198502,
   9232.546127192549,
   10,
   None],
  [14587.34028225234,
   9204.060743212298,
   14591.414833795805,
   9208.135294755763,
   11,
   None],
  [14612.248784039108,
   9254.771225800394,
   14616.358929515669,
   9258.881371276955,
   12,
   None],
  [15426.679535280848,
   9249.616917648518,
   15430.77250033611,
   9253.70988270378,
   13,
   None],
  [14636.503597809264,
   9279.875273539032,
   14640.63084377263,
   9284.002519502397,
   14,
   None],
  [14673.897350575742,
   9258.132749230961,
   14678.008638575295,
   9262.244037230514,
   15,
   None],
  [14656.706701707471,
   9303.416505300107,
   14660.849835713105,
   9307.559639305739,
   16,
   None],
  [14787.816419255567,
   9288.116879408732,
   14791.94593922646,
   9292.246399379625,
   17,
   None],
  [14677.73531617277,
   9323.881256700537,
   14681.892012644435,
   9328.037953172203,
   18,
   None],
  [14721.805318966755,
   9312.408026377092,
   14725.952979532605,
   9316.555686942942,
   19,
   None],
  [14710.367965144182,
   9338.398581139803,
   14714.533674527202,
   9342.564290522821,
   20,
   None],
  [13508.912465867663,
   9367.491903539547,
   13513.146777121832,
   9371.726214793716,
   21,
   None],
  [15105.730439537087,
   9383.4420067895,
   15109.91410556011,
   9387.625672812523,
   22,
   None],
  [13755.57087981781,
   9445.05553240846,
   13759.855075938982,
   9449.339728529632,
   23,
   None],
  [14998.963226656715,
   9427.082835406805,
   15003.17809380448,
   9431.297702554568,
   24,
   None],
  [15235.012346775358,
   9418.445559384403,
   15239.213876863883,
   9422.647089472926,
   25,
   None],
  [15096.198128213238,
   9453.677392292873,
   15100.426279958689,
   9457.905544038324,
   26,
   None],
  [15351.298483437078,
   9453.948528206618,
   15355.517784621312,
   9458.16782939085,
   27,
   None],
  [15350.868961689248,
   9483.418517580303,
   15355.105940606165,
   9487.65549649722,
   28,
   None],
  [14065.8921308106,
   9560.822682716203,
   14070.24417870799,
   9565.174730613593,
   29,
   None],
  [14268.72801989079,
   9453.767040457124,
   14272.991339495957,
   9458.030360062288,
   30,
   None],
  [16042.426476493478,
   9558.53910118274,
   16046.68103938889,
   9562.793664078152,
   31,
   None],
  [14857.443116051194,
   9507.585696443359,
   14861.71516878182,
   9511.857749173985,
   32,
   None],
  [14278.69072897216,
   9707.210110614931,
   14283.128956092103,
   9711.648337734874,
   33,
   None],
  [14322.223471183825,
   9521.751930227007,
   14326.532038710695,
   9526.060497753877,
   34,
   None],
  [15022.86130657482,
   9547.275447134465,
   15027.150754610371,
   9551.564895170015,
   35,
   None],
  [14580.650534979868,
   9571.276410827866,
   14584.978105488903,
   9575.603981336903,
   36,
   None],
  [15222.310919729265,
   9591.277558136631,
   15226.617668154535,
   9595.584306561901,
   37,
   None],
  [14613.418908955688,
   9605.730295447558,
   14617.767161130867,
   9610.078547622736,
   38,
   None],
  [15306.247020004566,
   9627.38592578123,
   15310.570973521533,
   9631.709879298196,
   39,
   None],
  [14665.450844677001,
   9648.042354784384,
   14669.823200987319,
   9652.4147110947,
   40,
   None],
  [15531.20542279936,
   9676.950947403435,
   15535.546485729294,
   9681.292010333369,
   41,
   None],
  [14752.209375319473,
   9706.096119979618,
   14756.612696119106,
   9710.499440779253,
   42,
   None],
  [14963.498195595177,
   9674.749926690674,
   14967.868968633335,
   9679.120699728832,
   43,
   None],
  [15061.756875502591,
   9663.151945801352,
   15066.114951788175,
   9667.510022086935,
   44,
   None],
  [15197.113010838846,
   9719.341728378433,
   15201.496426227495,
   9723.725143767084,
   45,
   None],
  [15426.76135365766,
   9727.622090078019,
   15431.136346865109,
   9731.997083285467,
   46,
   None],
  [15212.917181280256,
   9735.469396484039,
   15217.308994601453,
   9739.861209805236,
   47,
   None],
  [14969.311068818539,
   9783.495050936199,
   14973.746571619886,
   9787.930553737548,
   48,
   None],
  [15227.478527357314,
   9766.120199852263,
   15231.887063611957,
   9770.528736106906,
   49,
   None],
  [15021.28002420318,
   9835.442223195145,
   15025.742234382473,
   9839.904433374437,
   50,
   None],
  [15249.606154071686,
   9819.773226288284,
   15254.04372050796,
   9824.21079272456,
   51,
   None],
  [15608.759330775116,
   9838.517516156926,
   15613.18449241286,
   9842.942677794672,
   52,
   None],
  [15363.450541773622,
   9855.489027811167,
   15367.900457774984,
   9859.938943812529,
   53,
   None],
  [16104.35148174373,
   9928.086599925206,
   16108.793170846357,
   9932.52828902783,
   54,
   None],
  [15610.373817638902,
   9900.785071711363,
   15614.831935922472,
   9905.243189994933,
   55,
   None],
  [15136.969585346005,
   9893.077237551219,
   15141.456217108283,
   9897.563869313497,
   56,
   None],
  [15342.576742148756,
   9897.684245418955,
   15347.051190965796,
   9902.158694235995,
   57,
   None],
  [15284.54868151711,
   9934.649910317987,
   15289.047440380476,
   9939.148669181353,
   58,
   None],
  [15371.102512364543,
   9931.31542315322,
   15375.593192706225,
   9935.806103494902,
   59,
   None],
  [15756.904158003352,
   10014.299986517091,
   15761.41097050168,
   10018.80679901542,
   60,
   None],
  [14400.877625813764,
   9916.606221172904,
   14405.439713747324,
   9921.168309106466,
   61,
   None],
  [14764.299938132213,
   9918.792555928196,
   14768.830761770263,
   9923.323379566245,
   62,
   None],
  [14946.108696741614,
   9931.030051438951,
   14950.63154167163,
   9935.552896368967,
   63,
   None],
  [14919.426665092244,
   9955.175819986509,
   14923.965442374227,
   9959.71459726849,
   64,
   None],
  [14502.124019678038,
   9983.618235890543,
   14506.716978304381,
   9988.211194516885,
   65,
   None],
  [15668.809887644546,
   10096.81392675039,
   15673.36449684623,
   10101.368535952075,
   66,
   None],
  [14601.316507908226,
   10065.013417634786,
   14605.947206312758,
   10069.644116039317,
   67,
   None],
  [14919.841636731746,
   10032.27099443843,
   14924.423709075329,
   10036.85306678201,
   68,
   None],
  [15072.453099466333,
   10035.113356419728,
   15077.023439805133,
   10039.68369675853,
   69,
   None],
  [14970.229267328323,
   10061.584692012053,
   14974.823014644608,
   10066.178439328336,
   70,
   None],
  [15112.372686706447,
   10070.347527302549,
   15116.958657051684,
   10074.933497647788,
   71,
   None],
  [15260.367283031412,
   10123.96720710812,
   15264.968781906553,
   10128.568705983262,
   72,
   None],
  [14743.978581538287,
   10176.388694834492,
   14748.656890307415,
   10181.067003603619,
   73,
   None],
  [14863.400048989499,
   10112.930082100513,
   14868.031821780292,
   10117.561854891306,
   74,
   None],
  [15461.882316367357,
   10188.21534019411,
   15466.499241952259,
   10192.83226577901,
   75,
   None],
  [14951.411092561139,
   10155.892953227987,
   14956.05761637332,
   10160.539477040167,
   76,
   None],
  [15985.380251078022,
   10311.07775990447,
   15990.012501211186,
   10315.710010037632,
   77,
   None],
  [15074.613689955606,
   10205.334840917847,
   15079.274397080779,
   10209.99554804302,
   78,
   None],
  [15572.578606319492,
   10269.90171469433,
   15577.226078500322,
   10274.54918687516,
   79,
   None],
  [15256.46538546475,
   10265.184666016463,
   15261.13924857511,
   10269.858529126823,
   80,
   None],
  [16097.658114304013,
   10398.785443401106,
   16102.320705695087,
   10403.44803479218,
   81,
   None],
  [15668.785028407083,
   10367.2070962164,
   15673.47010506215,
   10371.892172871467,
   82,
   None],
  [17585.413018066774,
   10716.144281963514,
   17590.09062549612,
   10720.821889392859,
   83,
   None],
  [16696.580024426417,
   10583.954222988443,
   16701.27254438979,
   10588.646742951816,
   84,
   None],
  [14826.006783326819,
   10278.167759855005,
   14830.730647255028,
   10282.891623783215,
   85,
   None],
  [16035.45793804398,
   10488.73434410795,
   16040.165266707161,
   10493.44167277113,
   86,
   None],
  [15120.444676380894,
   10371.966007591696,
   15125.184943281214,
   10376.706274492017,
   87,
   None],
  [15522.655350651661,
   10417.526206547554,
   15527.377383852745,
   10422.24823974864,
   88,
   None],
  [15537.28537765985,
   10499.586920426445,
   15542.043714367781,
   10504.345257134379,
   89,
   None],
  [15663.466227860918,
   10494.721302419506,
   15668.210121854163,
   10499.465196412752,
   90,
   None],
  [15677.95014271698,
   10481.640775484628,
   15682.68677596869,
   10486.377408736338,
   91,
   None],
  [15690.076774111312,
   10516.577952731723,
   15694.827902603305,
   10521.329081223716,
   92,
   None],
  [15576.748794024532,
   10540.09580549285,
   15581.521468156563,
   10544.868479624884,
   93,
   None],
  [15665.31190562131,
   10543.590461387403,
   15670.0774242225,
   10548.35597998859,
   94,
   None],
  [15819.142467227664,
   10610.567297653466,
   15823.922270488543,
   10615.347100914345,
   95,
   None],
  [10966.971977706171,
   9631.168736159887,
   10971.913519012664,
   9636.110277466378,
   96,
   None],
  [11037.320865168951,
   9570.75839749527,
   11042.151777750374,
   9575.589310076693,
   97,
   None],
  [11991.9397649098,
   9764.655001678453,
   11996.733747064774,
   9769.448983833428,
   98,
   None],
  [11103.448002554329,
   9613.230751854944,
   11108.315100191636,
   9618.097849492251,
   99,
   None],
  [11610.55503367542,
   9701.172509818422,
   11615.376185290457,
   9705.993661433457,
   100,
   None],
  [12063.74910154729,
   9795.835737091784,
   12068.557156517025,
   9800.643792061519,
   101,
   None],
  [12103.678342139367,
   9833.201826805616,
   12108.512496637495,
   9838.035981303745,
   102,
   None],
  [12659.606267929688,
   9953.342223538788,
   12664.42828932345,
   9958.16424493255,
   103,
   None],
  [12352.583808641555,
   9908.125328769627,
   12357.430014346446,
   9912.971534474518,
   104,
   None],
  [12360.291465208336,
   9897.843929926954,
   12365.127346326348,
   9902.679811044965,
   105,
   None],
  [12374.25216810764,
   9925.776276817278,
   12379.10863807972,
   9930.632746789357,
   106,
   None],
  [12468.249415679415,
   9941.056543803741,
   12473.099049515215,
   9945.90617763954,
   107,
   None],
  [12397.37291319223,
   9939.854819170829,
   12402.236192435043,
   9944.718098413641,
   108,
   None],
  [11326.78372564835,
   9707.860395691792,
   11331.69556520424,
   9712.772235247681,
   109,
   None],
  [11606.515896104549,
   9760.50072569872,
   11611.402795686246,
   9765.387625280418,
   110,
   None],
  [11774.94554453819,
   9794.786686543857,
   11779.822361575301,
   9799.66350358097,
   111,
   None],
  [11810.32410689271,
   9824.412257135147,
   11815.221028192795,
   9829.309178435233,
   112,
   None],
  [11844.04251092646,
   9826.513921672798,
   11848.932757845598,
   9831.404168591935,
   113,
   None],
  [11842.438661858849,
   9839.903849977849,
   11847.342230450564,
   9844.807418569566,
   114,
   None],
  [11399.818107484884,
   9749.622736433164,
   11404.754504913166,
   9754.559133861445,
   115,
   None],
  [11962.417310984987,
   9893.958793942835,
   11967.340658548696,
   9898.882141506541,
   116,
   None],
  [12053.736211719768,
   9911.806182932862,
   12058.652993479844,
   9916.722964692935,
   117,
   None],
  [11984.895774241846,
   9907.49989495762,
   11989.825660373679,
   9912.429781089455,
   118,
   None],
  [11549.819993496003,
   9804.428121369585,
   11554.769331558211,
   9809.377459431795,
   119,
   None],
  [12095.135853551748,
   9953.55187261517,
   12100.078734968776,
   9958.494754032197,
   120,
   None],
  [12122.008839577042,
   9976.591204303351,
   12126.964606905143,
   9981.546971631455,
   121,
   None],
  [11040.549964780499,
   9734.448520098224,
   11045.594682897243,
   9739.493238214967,
   122,
   None],
  [11189.662793812751,
   9734.957148652144,
   11194.652647869883,
   9739.947002709276,
   123,
   None],
  [11452.11417357291,
   9800.353999853267,
   11457.08906406808,
   9805.328890348437,
   124,
   None],
  [11773.162954890995,
   9889.076680676473,
   11778.131498470917,
   9894.045224256393,
   125,
   None],
  [11871.25703873328,
   9932.20768219999,
   11876.238248623058,
   9937.188892089769,
   126,
   None],
  [11261.423377348741,
   9769.95639200988,
   11266.428039267648,
   9774.96105392879,
   127,
   None],
  [11546.506314247335,
   9847.271901154116,
   11551.500080224732,
   9852.265667131513,
   128,
   None],
  [11571.41095764538,
   9877.16379486003,
   11576.42643071955,
   9882.179267934198,
   129,
   None],
  [11780.253821191585,
   9932.442502336931,
   11785.260032756527,
   9937.448713901875,
   130,
   None],
  [11651.704878162796,
   9912.30414569035,
   11656.729550319671,
   9917.328817847223,
   131,
   None],
  [11996.63891894594,
   10014.58410893911,
   12001.657465322964,
   10019.602655316132,
   132,
   None],
  [11895.100341365047,
   9997.006481733451,
   11900.131111505745,
   10002.03725187415,
   133,
   None],
  [11096.555198583328,
   9799.467661283355,
   11101.652555556422,
   9804.565018256451,
   134,
   None],
  [11427.223268292913,
   9865.03699913446,
   11432.27216527236,
   9870.085896113904,
   135,
   None],
  [12033.381079627368,
   10056.608717847923,
   12038.423962212855,
   10061.65160043341,
   136,
   None],
  [11719.392786712418,
   9967.884100684772,
   11724.447670155787,
   9972.93898412814,
   137,
   None],
  [11202.841017757004,
   9882.712063027357,
   11207.984922801654,
   9887.855968072006,
   138,
   None],
  [11334.619360374882,
   9860.88914332731,
   11339.69497601622,
   9865.964758968648,
   139,
   None],
  [11738.102607268951,
   9987.86892981968,
   11743.169379717743,
   9992.935702268473,
   140,
   None],
  [11516.842936628627,
   9932.441550667483,
   11521.927332287401,
   9937.52594632626,
   141,
   None],
  [11724.328168725446,
   9996.992989320363,
   11729.406718064132,
   10002.071538659047,
   142,
   None],
  [11623.511987119307,
   9975.814767948421,
   11628.60220097176,
   9980.904981800873,
   143,
   None],
  [11300.733975341971,
   9990.410152307435,
   11305.942093734004,
   9995.618270699468,
   144,
   None],
  [11364.992335906214,
   9932.64935968626,
   11370.126683580807,
   9937.783707360853,
   145,
   None],
  [11526.314870320748,
   9966.129934200786,
   11531.426651351047,
   9971.241715231083,
   146,
   None],
  [12099.97717011011,
   10156.971449857643,
   12105.078935842097,
   10162.07321558963,
   147,
   None],
  [11622.230561705883,
   10012.078362578008,
   11627.352271433489,
   10017.200072305615,
   148,
   None],
  [12096.80368454313,
   10171.720948275282,
   12101.9168892648,
   10176.834152996951,
   149,
   None],
  [11855.709367353651,
   10107.494022844914,
   11860.839518338365,
   10112.624173829628,
   150,
   None],
  [12099.272440773462,
   10188.537763781163,
   12104.396971341846,
   10193.662294349548,
   151,
   None],
  [12075.11418829991,
   10195.631263179477,
   12080.24993132143,
   10200.767006200997,
   152,
   None],
  [11397.501813604742,
   9969.208488981678,
   11402.658273482906,
   9974.364948859842,
   153,
   None],
  [11951.675729160865,
   10165.435076872043,
   11956.822570993832,
   10170.581918705013,
   154,
   None],
  [11501.614951567148,
   10019.902498340529,
   11506.78094213258,
   10025.068488905961,
   155,
   None],
  [12093.04852685529,
   10234.313207852814,
   12098.206353612433,
   10239.471034609958,
   156,
   None],
  [12277.170206040344,
   10329.780709619405,
   12282.34429611408,
   10334.954799693141,
   157,
   None],
  [12323.39439038219,
   10338.963547188574,
   12328.563087933162,
   10344.132244739545,
   158,
   None],
  [12627.565866518922,
   10474.935686108442,
   12632.74532049283,
   10480.115140082351,
   159,
   None],
  [11383.24467177941,
   10110.452410500986,
   11388.521163643087,
   10115.728902364663,
   160,
   None],
  [11475.680384942649,
   10071.75922377662,
   11480.89690402486,
   10076.975742858831,
   161,
   None],
  [11614.64265696582,
   10104.089367069191,
   11619.840658760444,
   10109.287368863816,
   162,
   None],
  [12153.515576854843,
   10306.758297908176,
   12158.705672642787,
   10311.948393696119,
   163,
   None],
  [11735.874615290628,
   10163.283099921748,
   11741.080458393513,
   10168.488943024633,
   164,
   None],
  [12069.386735885591,
   10289.689287359894,
   12074.587358643186,
   10294.889910117488,
   165,
   None],
  [12186.996637319236,
   10353.683015071336,
   12192.207671969165,
   10358.894049721264,
   166,
   None],
  [11576.544150856138,
   10137.30905753351,
   11581.77882098811,
   10142.543727665481,
   167,
   None],
  [12152.830443183753,
   10356.565377684887,
   12158.051774418305,
   10361.786708919439,
   168,
   None],
  [11715.048458404723,
   10214.335507962076,
   11720.296267897887,
   10219.583317455239,
   169,
   None],
  [12474.779020535492,
   10516.987637455431,
   12480.015579947329,
   10522.224196867268,
   170,
   None],
  [12485.56225829216,
   10512.15976781108,
   12490.79377057579,
   10517.39128009471,
   171,
   None],
  [12476.05496123709,
   10526.870570062267,
   12481.296538808967,
   10532.112147634141,
   172,
   None],
  [12230.810197947356,
   10453.704238253713,
   12236.069110555714,
   10458.963150862071,
   173,
   None],
  [12258.076835642394,
   10452.291557295992,
   12263.328362518967,
   10457.543084172565,
   174,
   None],
  [12325.709320423903,
   10508.25824414657,
   12330.975553307479,
   10513.524477030145,
   175,
   None],
  [12415.748699572896,
   10538.290310373664,
   12421.01005955046,
   10543.55167035123,
   176,
   None],
  [12326.978743600148,
   10517.855930749267,
   12332.249820257415,
   10523.127007406536,
   177,
   None],
  [11468.143688603437,
   10229.385136009338,
   11473.47590628786,
   10234.717353693759,
   178,
   None],
  [11704.02562083471,
   10269.829472058856,
   11709.313420897492,
   10275.117272121639,
   179,
   None],
  [12041.28766851822,
   10408.877752195014,
   12046.568345218899,
   10414.158428895693,
   180,
   None],
  [12645.439041640964,
   10707.760966466523,
   12650.733899249728,
   10713.055824075289,
   181,
   None],
  [12653.784609101054,
   10701.480685650085,
   12659.074768996421,
   10706.770845545452,
   182,
   None],
  [12654.445155607385,
   10721.932610982356,
   12659.74468163888,
   10727.23213701385,
   183,
   None],
  [11578.773545319098,
   10352.223787014873,
   11584.147412292783,
   10357.59765398856,
   184,
   None],
  [12069.463722675127,
   10471.926404074777,
   12074.772497576938,
   10477.235178976589,
   185,
   None],
  [11601.994464973912,

In [43]:
align = AlignIO.read("concat36FFali.fasta", "fasta")

print("Number of rows: %i" % len(alignment))


for record in align:

    print("%s - %s" % (record.seq, record.id))

Number of rows: 1281
---------------------I---PH---------------QA-YMI-YQAMFAIITPAL-ISGAIAER----MS----F----R--L-T-P------PHNVP------FILLGAGLLWF--------GWFG-FNAGSA------------------ - A0A1X4G8K1
-------------------GEI---NQ---------------YV-HVV-FQGSFAVITVAL-IVGALGER----IR----F-------H-T-A-IK---PHNLP------MVFTGTAVLYI--------GWFG-FNAGS------------------- - A0A2X2C038
-------------------YNY---DD---------------YP-YFM-FQWAFATTAVSI-ISGSLAER----TQ----F---------H-D-IP---GHNSP------LIALGIFILWF--------GWFG-FNSGS------------------- - L8H844
--------------------SL---SN---------------TT-LML-FHAMFASTAVTI-ISGAIAER----TK-YHSF---------D--------QSNLA------FSALGVFLIWL--------GWIG-FNGGSV------------------ - A0A066ZRQ5
-------------------GNI---PE---------------LA-FVG-FQLTFAGLTVAL-ISGAIADR----VK----F-------R-V-P-MR---PHNVP------LTMLGAGLLWF--------GWFG-FNAGSE------------------ - A0A075JIN0
-------------------------VP---------------AV-DFL-FQSAFAGTAATI-VSGLVAER----VK----FG------------MP---GHNMA------IATLGALILWI--------GWYG-FNPGSE------------------ - A0A318QZ80
-------------------PLI---PN---------------LL-YAF-YQMQFCGVTAAI-IMGAVAER----GR---ML-----------N-FR---PHNVS------LILLGTVFLWF--------GWLG-FNGGSS------------------ - A1DG05
-------------------AAV---PD---------------VL-WAG-FQGMFAAVTGIL-MLGGACER------------------------YK---PHSIT------SVVLGTVFLFY--------GWLF-FNAGSA------------------ - G0VI62
--------------------AG---YG-------A-------FA-GHA-FLVAFCIITVAL-ASGAVADR----A----------G--K-QLA-----TSHNVP------LVLIGTAVLWF--------GWFG-FNTGVH------------------ - A0A016XDZ5
--------------------TI---PH---------------QV-FAM-FQLMFAIITPAL-ITGAFAER----MR----F-------R-I-P-LP---PHNLP------MTVLGATLLWF--------GWFG-FNAGSA------------------ - A0A0S6UEK9
------------------SSRL---PA---------------IV-FAF-YQLMFAAITPTI-AIGAFAER----AR----L-----------A-YK---PHNTT------YVVLGTVFLWF--------GWFG-FNGGSA------------------ - A8NAG3
--------------------------G---------------WH-QFF-FQWSFCAATTTI-VSGAVAER----CT----F-------------MR---GHSST------LVVMGTFLLWF--------GWFG-FNPGSN------------------ - Q8RUT6
---------------------Y---PMAS----------------MVW-FQCVFAAITLIL-LAGSVLGR----MN----F---------E-R-FP---PNNVL------LMLAGAGLLWM--------GWAG-FNGGDP------------------ - A0A2K1RA81
----------------NLSGNF---YQ---------------LI-HVA-FQGSFACITVAL-IIGALGE-------------------K-E-A-FK---PHNLP------MVFIGTAVLYI--------GWFG-FNAGS------------------- - A0A4R4K1P9
-------------------ALF---PE---------------AV-FIT-FQMTFAIITPAL-IVGAFAER----MK----F----P--T-T-P-MA---PHNLG------YTLMGAAMLWV--------GWFG-FNAGSA------------------ - A0A4R7VEK0
--------------------------R---------------WR-DWF-FQWAFCATCGTI-VSGAMAERT---AL----FV-----------------PHNVP------ILVLGTFILFF--------GWFG-FNPGSS------------------ - A0A7S4GNJ2
-------------------SGI---PE---------------YV-FAM-FQGKFAIIAPAL-IAGAFAER----VS----F-------N-V---MH---PNNLV------MTLIGAGLLWV--------GWFG-FNAGSA------------------ - B4S394
------------------APSI---PF---------------IM-VFA-YQMMFAIITPAL-ITGAFAGR----FR-------FSN----D-P-PR---PANIP------LVAVGTGLLWF--------GWFG-FNAGGA------------------ - C1D6X6
-------------------GTI---PT---------------YA-YVA-FQGMFAIITPAL-ISGAIVGR----VK----F-------KVD-P-LK---PHNVT------LTLLGTGLLWF--------GWFG-FNAGS------------------- - A0A0E3QY86
-------------------GSI---YE---------------LI-WVA-FQGSFACITCCL-ILGAFAER----MR----F-------R-E-P-LK---PFNLP------YVYLGAAILYI--------GWFG-FNAGS------------------- - A0A1B9LFW3
-------------------PGI---PE---------------FL-FIS-FQMTFAIITPAL-ITGAFAER----FK----Y-------T-D-V-IT---AHNPV------LTMIGASLLLV--------GWIG-FNAGSA------------------ - A0A258HS77
----------------AAASD-------------------------WF-FQMVFVATAASI-VSGTIAER----VK----L--PDA--KP--M-IP---GS-LP------LATLGTFILWF--------GWFG-FNGASQ------------------ - A0A495D4X4
---------------------P---WD---------------YT-FLL-FQMMFAVTAATI-ASGAMAER----TR----Y-------------IP---GHNLG------MVALGGFILWF--------GWFG-FNAGSN------------------ - A0A7G5DKA9
-------------------ATI---PQ---------------FI-HVA-FQGAFACLTVAL-VVGALGER----VK----F-------K-E-A-IK---PHNLP------MVFMGTAILFI--------GWFG-FNAGS------------------- - K8VZC6
-------------------VYI---PE---------------MI-FAA-FQSTFAGITAAL-IIGAFAER----VK----F----G--K-E-S-MA---PHSLV------MTMVGASLLWV--------GWFG-FNAGSN------------------ - F5RGM7
--------------------DP---WL---------------FA-FWL-FQVVFATTAATI-VSGAMAER----T-------------------IP---GHNIT------LAALGTFILWF--------GWFG-FNPGST------------------ - I6Z905
---------------------V---ST---------------IE-LWF-FMLVFAATAATI-VSGSIAER----PK----F-------------IP---GHNLA------FAVIGTFILWF--------GWFG-FNAGST------------------ - A0A075WG29
---------------SDRITGV-----------------------FWAAF-LLFSWTAASI-VSGAVIER----IR----------------S--P---PHNPW------MLTIGIFLIYS--------GFWG-FYAACN----IPAISPEGI----- - A0A0B4E6X7
---------------------I---PH---------------QA-FMI-YQMMFAVITPAL-ISGAFAER----KR----F----K----E-A-ME---PHDTT------MTVIGTALLWF--------GWFG-FNAGSS------------------ - A9AUR8
-------------------VPV----N---------------QA-FWF-FEFAFSATSVTI-VAGTLAER----CQ----E-------KPK-A-FP---GHSMA------LQMMGTMILWF--------GWYG-FNP--------------------- - B7G0Y1
-------------------GSI---PH---------------LL-FMA-FQGTFAIITAAL-ISGAIVER----MQ----F----G--R-Q-A-ML---PHNVP------FVLLGAGLLWF--------GWFG-FNGGSA------------------ - D0MFE9
-------------------GTI---PE---------------YV-FIG-FQLMFAIITVAL-ISGAIADR----AK----F-------R-E-P-MR---PHNLP------FVLLGAGLLWF--------GWFG-FNAGSA------------------ - E2SD33
----------------DLTGSF---YK---------------MI-HVA-FQGSFACITVGL-IVGSFAE-------------------K-E-A-FK---PHNLP------MVFMGTAILYI--------GWFG-FNAGS------------------- - A0A097R891
----------------ALMGSF---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F-------K-E-A-FK---PHNLP------MVFTGTAILYV--------GWFG-FNAGS------------------- - A0A0H3H4I7
----------------TYWTD-------------------------FL-FQAMFAATAATI-VSGAVAER----IK----L-I------------P---GHSLP------LATIGVFLLWL--------GWFG-FNGGSV------------------ - A0A6N4SPH9
--------------------TI---PQ---------------EL-FAA-FQMMFAIITPAL-ITGALVER----MK----F-------I-M-A-YR---PHNIP------FVVLGVALLWF--------GWFG-FNAGSA------------------ - A6LV49
---------------------S---AD---------------TG-YVF-FQLAFCAVSFAI-VWGTTLER----------I-------------IP---GHSMP------MFGVGVLILWL--------GWFG-FNAGSTLTT-A------------- - D3F545
-------------------SAY---PE---------------LL-FAG-FQGMFAAVTAAI-IMGGAAER----G-----L-----------N-FR---PHNVS------LVTLGTVLLWF--------GWLG-FNGGSA------------------ - A0A1E3PSK5
----------------DLMGSF---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F-------K-E-A-FK---PHNLP------MVFIGTAILYF--------GWFG-FNAGS------------------- - A0A3N2SFS2
--------------------TI---PE---------------SI-FMM-FQMTFAIITPAL-ISGAYAER----MK----F-------Q-D-D-LS---PFNLT------YAVIGASLLWV--------GWFG-FNAGSA------------------ - A0A401X433
-------------------RNF---PE---------------FI-FIA-YQMMFAIITPAL-ITGAFINR----VT----F-------------DG---PNNIP------LVAIGTALLWF--------GWYG-FNAGSE------------------ - A0A5M4AUM9
--------------------TI---PE---------------SI-FMM-FQMTFAIITPAL-ISGAYAER----MK----F-------Q-D-D-LS---PFNLT------YAIIGASLLWV--------GWFG-FNAGSA------------------ - A0A149U2G9
---------------VPEDAAY---PP---------------LA-FAA-FQATFAIITVAL-VSGAIADG--------------KG------A-HV---PHNPP------FVLLGAGLLWF--------GWFG-FNAGSE------------------ - A0A2S5WV24
-------------------DAT---PD---------------IL-FCL-YQGMFAAITPAL-AIGAVADR----GR------------------YR---PHSVT------NVLLGTVFLWV--------GWFG-FNGGSA------------------ - A0A2S7YIM5
------------------GLDI---PL---------------WV-YIV-FQTVFCATAATI-VSGSMAE-------------------------IP---GHNLT------AGALGVFILWF--------CWFG-FNGGSS------------------ - A0A3E2T713
----------------SVYAD-------------------------FF-FQMVFVATAASV-ISGTVAER----IK----L---GG--KIR-A-IP---GSNIP------LATLGTFLLWF--------GWFG-FNG--------------------- - E6W5C1
-------------------VNI---PE---------------FA-FIA-FQMTFAMITPAL-IFGAFAER----VK----F-------K-E-A-FQ---PHSLT------LTLVGAGLLWV--------GWFG-FNAGSN------------------ - O66395
-------------------GSI---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F------------------PHNLP------MVFTGTAILYI--------GWFG-FNAGSAGTA-N------------- - P69680
-----------------GVSDPLFGPI---------------FA-AFL-FQLSFSTTATTI-VSGAMATD----P-----L--------------P---LGNPV------NACMGLFVLWW--------GWLA-FNSGST------------------ - Q7Z1M1
-------------------GTL---PE---------------VL-FFA-FQMTFAIITPAL-IVGAYVER----VT----F----S--------KP---PHNPG------YVMIGAAMLWV--------GWFG-FNGGSQ------------------ - A0A037ZJY5
-------------------STI---PQ---------------IL-FAL-FQMAFAILTPAI-VSGGIVER----TR----F-------------LR---PHNIP------YVCLGGSLLWM--------GWFG-FNAGAG------------------ - A0A1G5W0P2
-------------------------FD---------------WS-NFV-FNLVFCATTATI-VSGAMAERT---VK----V---------N-A-FP---GHNIA------LGALGVFILWL--------GWYG-FNGAAA------------------ - A0A2G3E8V2
--------------------DI---PE---------------TV-FFM-FQMTFAIITPAL-IVGGFAER----MK----F-------N-T-A-MP---PHNMT------MVVTGAGMLWV--------GWFG-FNAGSA------------------ - A0A2S6GKN5
-------------------GSF---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F-------K-E-A-FK---PHNLP------MVFTGTAILYF--------GWFG-FNAGS------------------- - A0A7H8UK07
------------------ETGV---PL---------------YV-FMA-FQMMFAVITVAL-ISGAISD-------------------------MK---PHNVP------MVALGAGLLWF--------GWFG-FNAGSE------------------ - A8M670
-------------------------TT---------------FR-TWF-FQGAFCATGATI-VSGAMAERT---------FD-----------------GHSVP------FCVLGTFFLWF--------GWYG-FNPGST------------------ - A0A0K2STQ7
----------------DLGPTI---PF---------------AL-FAI-FQLKFAIITPAL-ITGSFAG-----------------------P-ER---RANIP------FVMLGAGMLWF--------GWFG-FNAGSA------------------ - A0A5M4ATH9
--------------GEG--ADL-------------------------F-FQTMFAATAATI-VSGAIAGR----TK----Y--------------P---GHNQI------MATLGVFILWL--------GWFG-FNGGSQ------------------ - A9DQM8
------------NATWKLAPTV---PL---------------VL-FAM-FQLKFAVITPAL-ITGAFAV-------------------------HA---PARIS------YVLLGTGLLWF--------GWFG-FNAGSA------------------ - H1YCC3
-------------------VAL---PE---------------YL-FIA-FQMTFAVITPAL-IVGAFAER----IK----F----G--R-D-M-MA---PHSMT------LTMVGASILWV--------GWFG-FNAGSN------------------ - Q1YDY7
-------------------VVI---PE---------------LV-FVA-FQGAFAAITVAL-IIGAFAER----VK----F-------K-E-A-FK---PHSLT------LTMVGASLLWF--------GWFG-FNAGSG------------------ - Q45HK8
------------------VGDL---PA---------------LV-YAM-FQLMFAIVTAAI-ISGS----------------------------VA---THNVP------YVMLGAALLWF--------GWFG-FNAGSALTA-GQLAG--------- - A0A0D2UPA8
-------------------TTV---PH---------------LA-FMM-FQGMFAIISLAL-ITGAVVER----IR----F----E--Q-----ME---PNNLP------MVMLGAALLWF--------GWFG-FNGGSA------------------ - A0A142VAD6
----------------ALMGSF---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F-------K-E-A-FK---PHNLP------MVFTGTAILYF--------GWFG-FNAGS------------------- - A0A2T4XZC1
----------------SVMSD-------------------------WF-FQMVFVATAASI-VSGTLAER----IK----------------F-LP---GANLP------LATLGTFVLWL--------GWFG-FNGGSQ------------------ - A0A420WC79
-------------------GTI---PE---------------YV-FVA-FQSTFAAITCAL-IVGAFAER----MK----F-------K-E-A-MP---PHSLT------LTMVGASLLWV--------GWFG-FNAGSA------------------ - A4G1J2
-------------------ANI---SE---------------LV-YVC-FQMTFCAITPAL-IVGAFAER----TR----F----G--K-E-L-MA---PHSLT------MTMIGASLLWV--------GWFG-FNAGSN------------------ - Q6ND34
-------------------------WV---------------YS-KFF-FQASFATTATTI-VSGAMAER----TK----L-------------------GSPT------NALLGMFMLWW--------GWLG-FNCGSTFG-----ISGLKW----- - V3ZVE4
--------------------DI---PE---------------TV-FFM-FQMTFAIITPAL-IVGGFAER----MK----F-------N-T-A-MP---PHNMT------MVVTGAGMLWV--------GWFG-FNAGSA------------------ - A0A2S6H6B7
-------------------SAY---PT---------------LA-FAA-FQATFAIITVAL-ISGAIADR----AK----F------------------PHNPP------FVLLGAGLLWF--------GWFG-FNAGSELAA-D------------- - A0A3T0SZ22
-------------------------PA---------------LL-DVA-FQGTFAVITAAL-ISGSLVGR----MR----F---------L-A-FL---PHNIP------FVLLGAGLLWF--------GWFG-FNGGSA------------------ - E4U5Z1
----------------TFFTD-------------------------FI-FQAMFAATAATI-VSGAVAER----IK----L-I------------P---GHNIP------LAVFGVFLLWF--------GWFG-FNGGSV------------------ - G0J614
-------------------TKV---PD---------------LL-FAV-FQGMFAAITVAL-AVGAVAER----GR------------------YR---PHNVT------HVVIGTVFLWV--------GWFG-FNAGSA------------------ - G5EB13
-------------------ATV---PD---------------VL-FAF-YQGMFAMVTGIL-MVGGACER------------------------YM---PHSIT------SVVLGTVFLWF--------GWFG-FNGGSA------------------ - G8JUJ2
------------SPNDTYAPHI---PF---------------MM-VFA-YQMMFAIITPAL-MTGAFVG---------------------D-PESQ---PASLP------LVALGAGLLWF--------GWFG-FNAGGA------------------ - A0A1U9Z147
----------------TYWTD-------------------------FL-FQGMFAATAATI-VSGAVAER----IK----I-KDGK--S-F-V-IL---GHNLP------LATAGVLILWL--------GWFG-FNG--------------------- - A0A2T1N7R1
----------------TFYTD-------------------------FI-FQAMFAATAATI-VSGAVAER----IK----L-I------------P---GHNIP------LAVIGVFLLWF--------GWFG-FNGGSV------------------ - U5C2K4
--------------------TI---PE---------------SV-FMM-FQMTFAVITPAL-ITGAYAER----MK----F-------E---D-LS---PFNLT------YAIIGASLLWV--------GWFG-FNAGSA------------------ - Q5FSX6
-------------------------VP---------------TV-DFL-FQSAFAGTAATI-VSGLVAER----VK----FG------------MP---GHNMA------IATLGALVLWI--------GWYG-FNPGSQ------------------ - A0A0A2A5X1
-------------------GDP---WV---------------LA-FWM-FQVVFAATAATI-VSGAMAER----T-------------------IP---GHNMP------LAALGVFILWL--------GWFG-FNPGST------------------ - A0A1M6ZMI3
--------------------TI---PE---------------SV-FIM-FQMTFAVITPAL-ITGAYAER----MK----F-------E---D-LS---PFNLT------YAIIGASLLWV--------GWFG-FNAGSA------------------ - A0A829X098
--------------------TI---PE---------------SV-FMI-FQMTFAIIAGAI-ITGATVER----MK----F-------------MM---PHNLV------LTLIGTAMLQI--------GWFG-FNAGSA------------------ - A0A9Q6P4A5
-------------------------AD---------------QA-SWF-FALSFANTSATI-VSGAIAER----CK----L-------------MR---QQSVV------LQTLGTLTLWI--------GWFY-FNAVST------------------ - F0Y9X3
-------------------VVI---PE---------------IV-FAA-FQATFAGITCTL-IVGAFAER----MK----F----G--R-E-S-MA---PHSLT------LTMVGASLLWV--------GWFG-FNAGS------------------- - Q221S8
--------------------SI---PE---------------SV-FMV-FQMAFAIIAGAI-ITGAFAER----IK----F-------K-D-A-MP---PYNLT------LTLIGCAMLWI--------GWFG-FNAGSA------------------ - F4H924
--------------------TI---PG---------------SV-YAI-FQCMFAALTPAL-AIGGAAER----I-----------------K-FQ---PHNYL------NIILGTALLWF--------GWFG-FNGGSA------------------ - A0A2G5BGA9
------------------GLDI---PL---------------WV-YIV-FQTVFCATAATI-VSGSMAE-------------------------IP---GHNLT------AGALGVFILWF--------CWFG-FNGGSS------------------ - A0A3E2UCG9
-------------------VYI---PE---------------LS-FVI-FQLAFACIAPAL-IVGATAER----LK----F----N--R-E-L-LA---PHNLT------FTLIGGCLLWI--------GWFG-FNAGS------------------- - A0A533I6R2
----------------STAAD-------------------------FF-FQVVFVATAVSI-TSGAVAER----MK----L-GPNG--EIN-A-IT---GANLP------LATLGMFILWM--------GWFG-FNG--------------------- - B3PF77
-------------------KRF---PE---------------YI-FIA-YQMMFAIITPAL-ITGAFINR----VS----F-------------TD---PNNIP------LVAIGTALLWF--------GWYG-FNAGSE------------------ - E4T0A4
-------------------ATI---PE---------------YV-FLA-FQGTFAAITVAL-VVGSFAER----MR----F-------R-E-A-FT---PHSLT------LTMVGASLLWV--------GWFG-FNAGSA------------------ - F4GED5
----------------AARAD-------------------------FF-FQIVFAATCMSI-VSGAVAER----MK----L--SNG--QVN-A-IP---GANLP------LATLGMFILWM--------GWFG-FNGGSQ------------------ - A0A7G5DPV1
-------------------NGV---PE---------------YV-LAM-FQGKFAIITPAL-ISGAVAER----VY----F-------E-R-P-IQ---PNNMV------MTMMGAGLLWV--------GWFG-FNAGST------------------ - B8FGW0
---------------------I---PH---------------QA-FMI-YQAMFAIITPAL-ISGAIAER----IS----F----R--L-S-P------PHNVP------FILLGAGLLWF--------GWFG-FNAGSA------------------ - K9WT03
-------------------------PL---------------KA-QFF-FQLTFAGTAATI-VSGAVAER----IK----F-------------FG---GHNLS------LATLGCLILWF--------GWFG-FNAGST------------------ - T2J0N1
----------------ARMSD-------------------------FF-FQVVFVATAMSI-VSGAVAER----MK-------KDG--SIN-A-IP---GANLP------LATLGTFVLWL--------GWFG-FNG--------------------- - W0DYY3
----------------GMFNEL---PI---------------GV-FIF-FHTVFCATSATI-VSGAMAE-------------------------IP---GHNLP------LGVLGVFILWF--------AWFG-FNCGST------------------ - A0A1M5ZVP9
--------------------TI---PH---------------TV-FMT-FQGMFAIITPAL-ISGAFAER----MK----F----G--S-R-A-FI---PHNLT------LTLLGVGLLWF--------GWFG-FNAGSR------------------ - I4C9L2
--------------------TI---PH---------------GI-YSF-YQLTFAIVTPAI-ISGAVVER----IS----F-------------------HNVP------MFVLGTVILWFVDFHHASIGWFG-FNGGS------------------- - L8GGA0
----------------ALSDTI---PT---------------FA-FAA-FQAMFAILTVAL-ISGAVADR--------------------E-T-GK---PHNLP------LVVLGAGLLWF--------GWFG-FNAGSA------------------ - A0A2T0GTU1
-------------------------ID---------------LA-NWF-FGLVFAATAATI-VSGGVAER----IK----F-------------IP---GHNIP------MSVFGAFVLAI--------GWYG-FNVGSS------------------ - A4G0C5
---------------SDNATGV-----------------------FWAAF-ALFAATTASI-MSGAVIER----IR----------------L-IK---AHSVP------LTVIGLMLIIV--------GFFG-FLGGC-------IIYMGGAQ-WT- - Q0G2V0
-------------------SHI---PE---------------YV-FAM-FQGKFAIITPAL-IAGAFAER----VN----F-------N-V---MH---PNNLV------MTLTGAGLLWV--------GWFG-FNAGSA------------------ - Q3B6Q2
----------------SRIAD-------------------------FF-FQVVFVATAMSV-VSGAIAER----MK------------------IP---GSNLP------LASLGTFILWF--------GWFG-FNGGSQ------------------ - Q6ARH0
-------------------MGF---PE---------------IV-FVA-YQMMFAIITPAL-ITGAFANR----VT----F-----------I-TK---PNNVP------LMAIGTALLWF--------GWYG-FNAGSE------------------ - A0A0E3R6S1
------------------GEQY---PV---------------YI-FIA-YQMMFAIITPAL-ITGAFVNR----VT----F-----------A-SK---PNSIP------LVAIGTGLLWF--------GWYG-FNAGSE------------------ - A0A5M4B0G1
-------------------ATV---PE---------------YV-FVS-FQATFAAITVAL-IVGAFAER----IK----F----G--R-E-A-LA---PHNLT------LTMVGASLLWV--------GWFG-FNAGS------------------- - A0A7G5EC77
-------------------PLI---PN---------------LL-YAF-YQMQFCGVTAAI-VMGAVAER----GR---ML-----------N-FR---PHNVS------LILLGTVFLWF--------GWLG-FNGGSA------------------ - A1C5Z7
-------------------------ET---------------AA-LFF-FQLAFAATAATI-VSGAVAER-----------------------------ERSTA------MKALGAVFLWI--------GWGA-FNGGSALFF-GEAVGP-------- - F7ZJM0
------------------SPLV---PA---------------LL-YSF-YQMMFCAVTAAL-TVGAVAER----GR---MM-----------N-FR---PHNIS------LITLGTILLWF--------GWLG-FNGGSA------------------ - J4KM12
-------------------------PA---------------II-DIV-FQMAFAMITTAI-ITGAVAGR----MK----V---ML------S-YR---PHNVP------FVFLGATLLWF--------GWFG-FNAGSA------------------ - A0A172RYW3
-------------------GSI---YE---------------FI-WVA-FQGSFACITCCL-IPGAFAER----IR----F-------R-E-P-LK---PFNLP------YVYLGAAILYI--------GWFG-FNAGS------------------- - A0A1B9M5B8
--------------------II---AV---------------DA-YWGAFYILFAAISIAI-VASGAAGR------------------MKE---LR---PHNMP------LVLLGAGLLFF--------GWIG-FNGGTA------------------ - A0A2S5WGI8
-------------------PTI---PE---------------YV-FVA-FQSTFAAITVAL-IVGAFAER----IK----F-------R-E-A-LP---PHSLT------LTMVGASLLWV--------GWFG-FNAGSA------------------ - A9BQZ4
------------------GGGL---HL---------------YA-MFF-FQLCFAVTAATI-VSGAVAER----IK----I-------------IP---GHNLA------MVTLGGLILWL--------GWFG-FNGGTE------------------ - D0LTW3
----------------EFHFGI---------------Y----NM-----INADFSTATVLI-SFGAVLGK----TS----------------------------VYHSDLFAMIGTLFLWI--------FWPS-FNSAIADPGD-------------- - Q9QUT0
-------------------GTL---PE---------------IL-FFA-FQMTFAVITPAL-ILGAFVER----VN----H----T---------P---PHNPG------MVAIGAGLLWV--------GWFG-FNGGSE------------------ - A0A1G7H8X3

In [44]:
ff = align[:, 53:54]

In [45]:
otf = align[:, 134:135]

In [46]:
fiftyfour = []
seqff = []


for i in ff:
    print(i.id, i.seq)
    fiftyfour.append(f"{i.id} {i.seq}")
    seqff.append(i.seq)

A0A1X4G8K1 F
A0A2X2C038 F
L8H844 F
A0A066ZRQ5 F
A0A075JIN0 F
A0A318QZ80 F
A1DG05 F
G0VI62 F
A0A016XDZ5 F
A0A0S6UEK9 F
A8NAG3 F
Q8RUT6 F
A0A2K1RA81 F
A0A4R4K1P9 F
A0A4R7VEK0 F
A0A7S4GNJ2 F
B4S394 F
C1D6X6 F
A0A0E3QY86 F
A0A1B9LFW3 F
A0A258HS77 F
A0A495D4X4 F
A0A7G5DKA9 F
K8VZC6 F
F5RGM7 F
I6Z905 F
A0A075WG29 F
A0A0B4E6X7 F
A9AUR8 F
B7G0Y1 F
D0MFE9 F
E2SD33 F
A0A097R891 F
A0A0H3H4I7 F
A0A6N4SPH9 F
A6LV49 F
D3F545 F
A0A1E3PSK5 F
A0A3N2SFS2 F
A0A401X433 F
A0A5M4AUM9 F
A0A149U2G9 F
A0A2S5WV24 F
A0A2S7YIM5 F
A0A3E2T713 F
E6W5C1 F
O66395 F
P69680 F
Q7Z1M1 F
A0A037ZJY5 F
A0A1G5W0P2 F
A0A2G3E8V2 F
A0A2S6GKN5 F
A0A7H8UK07 F
A8M670 F
A0A0K2STQ7 F
A0A5M4ATH9 F
A9DQM8 F
H1YCC3 F
Q1YDY7 F
Q45HK8 F
A0A0D2UPA8 F
A0A142VAD6 F
A0A2T4XZC1 F
A0A420WC79 F
A4G1J2 F
Q6ND34 F
V3ZVE4 F
A0A2S6H6B7 F
A0A3T0SZ22 F
E4U5Z1 F
G0J614 F
G5EB13 F
G8JUJ2 F
A0A1U9Z147 F
A0A2T1N7R1 F
U5C2K4 F
Q5FSX6 F
A0A0A2A5X1 F
A0A1M6ZMI3 F
A0A829X098 F
A0A9Q6P4A5 F
F0Y9X3 F
Q221S8 F
F4H924 F
A0A2G5BGA9 F
A0A3E2UCG9 F
A0A533I6R2 F
B3PF77 F
E4T0A4 F
F4GED5 F
A0A7G5DPV1 F
B8FGW0 F
K9WT03 F
T2J0N1 F
W0DYY3 F
A0A1M5ZVP9 F
I4C9L2 F
L8GGA0 F
A0A2T0GTU1 F
A4G0C5 F
Q0G2V0 F
Q3B6Q2 F
Q6ARH0 F
A0A0E3R6S1 F
A0A5M4B0G1 F
A0A7G5EC77 F
A1C5Z7 F
F7ZJM0 F
J4KM12 F
A0A172RYW3 F
A0A1B9M5B8 F
A0A2S5WGI8 F
A9BQZ4 F
D0LTW3 F
Q9QUT0 F
A0A1G7H8X3 F
A0A1G7UZX2 F
A0A2S8FTB5 F
A0A087MGU4 F
A0A410JZR4 F
A0A6U2BIY7 F
B3QVV5 F
C7BJG7 F
Q82X47 F
A0A066ZTE4 F
A0A7S4LPS8 F
B0DFJ4 F
G4H971 F
I5AZQ4 F
Q0ARJ4 F
A0A5J6WPP9 F
L1IYP4 F
M1P5F0 F
A0A0D2LEF5 F
A0A562S8V2 F
D2SE15 F
F2B2B8 F
H6LFQ2 F
H6LKH9 F
Q1PX09 F
A0A0A2BBY0 F
A0A2S8GSU9 F
A0A7S4GMD8 F
L8H5K0 F
A0A1B9JPL5 F
A0A1B9MZ78 F
A0A1S1HRJ0 F
A0A317G0I6 F
A7HSN9 F
Q5FA36 F
E3HJW8 F
Q2IK04 F
A0A0E3SHQ9 F
A0A101DCS3 F
A0A1I0AQM4 F
A0A377I7W9 F
A0A975BTN0 F
A9HMD6 F
A0A2S0JW39 F
A0A975GIX9 F
A0A0D8BQX6 F
A0A1Y5E3E3 F
A0A9J9BAE8 F
D7E934 F
E5Y678 F
A0A1G5PWV0 F
A0A1G5RZU9 F
A0A1M6BPM0 F
A0A7T2W1B3 F
G2PRJ6 F
A0A1U9YY82 F
A0A918MJ52 F
D7UQE2 F
K9U8C7 F
M1WRK6 F
K1K628 F
A0A068NV61 F
A0A1H3WA00 F
A0A2N6K4Y5 F
A5DYQ2 F
B0RC35 F
J3EXK0 F
A0A1J1JH03 F
A0AIW5 F
K2IMJ7 F
L1IHZ8 F
Q2RM12 F
Q6CRN0 F
A0A075WBP9 F
A0A160KTE9 F
L1J6I4 F
A0A0E3WZH5 F
A0A4D6KHD1 F
D3RN22 F
M2ALH9 F
G0JRQ3 F
H6LKX6 F
A0A009PYN3 F
A0A3G9G2C9 F
A0A562RGZ4 F
B2GFN1 F
B3PIH2 F
E7RJZ0 F
K9ZG59 F
M7XJ51 F
Q13E03 F
Q59UP8 F
A0A021VMC6 F
A0A1H4KAQ7 F
A0A248LNW8 F
D0KXQ0 F
Q1AUG3 F
Q1K0H9 F
A0A4Q2EAG7 F
A2BP62 F
A0A071M4L5 F
A0A1C7EL50 F
A0A257T7G4 F
A0A2J7TJ33 F
A0A2S0P9T4 F
A0A2V4EA49 F
Q7UYZ3 F
A0A0S4VNK2 F
G7WDB5 F
I5B3H0 F
A0A5M8QF12 F
A0AA86YS65 F
A0A166IS52 F
A0A1I5GN22 F
A0A1Y0UZX2 F
A0A2A2M8K7 F
A0A2K3DQF8 F
A0A395VB65 F
D2RU19 F
M0MDP9 F
J1ASR8 F
Q7UGU7 F
A0A089ZBW5 F
A0A2S5WX34 F
A0A6H9GLV4 F
A0A6H9GWG4 F
A0A854Q6X9 F
E5B358 F
W7QGM4 F
A0A4V0XUI3 F
A7SED8 F
D4XLN6 F
D5VJ32 F
F2JYR9 F
Q8RUE9 F
A0A1I0C958 F
A0A1V3SSW1 F
A0A410K1J5 F
A0LV78 F
Q0BWD0 F
S0EUS1 F
A0A1R1IDV3 F
B8ENL9 F
G0JRG6 F
S0G181 F
S5ABR8 F
A0A0L8BVU4 F
A0A0T7GZ59 F
A0A323UDG5 F
A0A556SRH6 F
A0A251Y3N4 F
A0A373FQ71 F
K0ER80 F
A7I8Z2 F
M5S735 F
A8HSA2 F
B0VMH1 F
G3IYW2 F
H5UND3 F
Q2S8H9 F
A0A2S6GKF6 F
A0A6M3ZKU5 F
Q21CP1 F
A0A8E2UDJ3 F
C7LQR9 F
A0A060UWC8 F
Q7V4T8 F
S0APH6 F
A0A2H1HV86 F
A0A482PLH3 F
A0A7G5DPV0 F
A0A7V8IKS6 F
G5EB09 F
M5SY07 F
A0A127PIQ9 F
A0A4Q7Y9I7 F
A0A562BXM4 F
A0A6H9GFU4 F
W0DZS7 F
A0A1B9N3H7 F
A0A5A7MAJ9 F
A1D2Y5 F
C5LAG4 F
C9RS76 F
A0A8H7P8U1 F
A0AA35XVN2 F
Q7W7D3 F
V5BYZ7 F
A0A0D2NYP3 F
A0A4V2X6C2 F
A3PAY4 F
C5CIT6 F
C6XKC2 F
U2EN72 F
A0A379A0S9 F
D5T4N9 F
G7WJN0 F
Q5KPM5 F
A0A147EQL9 F
A0A1I4ZIZ6 F
A0A7S4GNF3 F
D3LBI0 F
I1DSU5 F
A0A2U1SS17 F
K9YN27 F
P40260 F
A0A1T4SF40 F
A0A8G2F3G4 F
D6E7B3 F
I5BYV5 F
Q9QXP0 F
V5U2Z4 F
A0RXK8 F
H1Y7T6 F
A0A074KZD8 F
A0A074ME37 F
A0A5M4AWD2 F
J9VXX9 F
L8JUH3 F
Q21J04 F
A0A8F5VN39 F
E1QFA8 F
E1SLM7 F
G3IYW0 F
A0A017SYR8 F
A0A2S7YPJ9 F
A0A7U3XVQ4 F
B8GGC3 F
B9LU00 F
I0KDC6 F
Q1L727 Y
A0A009TDB1 F
A0A1D3GAE9 F
A0A317FZW2 F
A0A4R2M206 F
C0Z5S5 F
F0S3Z6 F
A0A1Y4LM49 F
A0A369MHK2 F
A4BMY5 F
B9SXC7 F
D2ZRW2 F
Q1H483 F
A0A062IU58 F
A0A1B9JHS5 F
A0A1T4SFK4 F
A0A9E9L9J1 F
J7ITF6 F
A0A2C6C0X3 F
I9P003 F
Q488X2 F
X5CNT2 F
A0A4R8GSH7 F
D5UD26 F
S9QZ09 F
A0A149RQX0 F
A0A419AVL2 F
A0A4Y1MSE7 F
Q81GN5 F
U7VB41 F
G0V8D6 F
Q5KZZ9 F
A0A0H3DR67 F
A0A1B9MYL7 F
D0L8H3 F
D3RMV7 F
F2JTN3 F
F2NNQ0 F
Q6QH01 F
E4T3F7 F
G0H0Z6 F
A0A6B8N021 F
A8AC17 F
A8G2S3 F
Q0F2M7 F
S0ET45 F
K1LDP0 F
Q1QSQ2 F
A0A330GB00 F
A0A9Q5QVI9 F
A3XNG6 F
D6TFE1 F
E1V4T3 F
H2CJI0 F
T2IEJ2 F
A0A833GZR2 F
A1SY01 F
C8X554 F
E1QIU3 F
Q1K8A3 F
Q9M6N7 F
A0A8B4RWH8 F
A1VIM5 F
A0A060URC3 F
A0A328Q6M1 F
Q8GQS1 F
A0A2T4UWF1 F
A0A420KGW4 F
A9WHW6 F
B3QRJ4 F
I3C0V3 F
Q8ERT9 F
C1G973 F
E4TRS4 F
G7UUY6 F
M2A398 F
Q60C43 F
A0A0M2LU39 F
A0A1H1BPD6 F
A0A257SYX3 F
A0A2S5WMT7 F
B1ZSW9 F
Q5UZ98 F
A0A0B5FNH4 F
A0A173R3X4 F
A0A380S5X4 F
A0A9W3LFI9 F
D4H2Y7 F
G8TK77 F
A0A1Y4L5P0 F
A0A2S8GF54 F
A0A2T9X1V4 F
A0A401WXG0 F
A0A642KQG8 F
A0A161SKF4 F
A0A9Q9D9I3 F
A1B3N0 F
D4GLQ6 F
Q94CJ2 F
A0A0H2XSU4 F
C4Y298 F
D2V6P8 F
E3H8C9 F
F5R974 F
M5U2P1 F
Q0BQ69 F
A0A073CP02 F
B0DU91 F
B1JZ69 F
B7GKP4 F
D9SI36 F
G7WA28 F
Q1Z4I4 F
Q9REX3 F
A0A0A2VPU3 F
A0A1A0DHK0 F
A0A1S1HM83 F
A0A248LMH8 F
A2C095 F
D0LAL7 F
E6VIW4 F
A0A316BQ38 F
A0A369NYJ2 F
A0A370FPU0 F
A0A8H6MPB9 F
A1VIG8 F
A7S731 F
K9W4V5 F
A0A0D5YN10 F
A0A2R3IMJ8 F
B7G0Y4 F
Q07UM3 F
U3P8G1 F
A0A830ZZN8 F
A1ZGK6 F
A8LKQ0 F
C1MX19 F
D9SI59 F
A0A977NL43 F
A1SVA8 F
C1N6X9 F
C7QGX3 F
A0A2S6H643 F
Q7NCB8 F
Q2FS34 F
A0A3R9Q7C4 F
A0A495WJM6 F
A0A7T2S0Z6 F
A0A7U4DN04 F
F4XTK4 F
M9RKT6 F
A0A0X8X7Y7 F
A0A7U8C2Y6 F
A0A8G2F718 F
A6DN47 F
Q5KAF6 F
A0A060URB8 F
A0A1H9RTW8 F
A0A4V3ALP8 F
D9QS43 F
A0A2W0GQV0 F
A0A6G9XJV9 F
C6DB68 F
D6TCH6 F
Q3AP28 F
A0A060UN76 F
A0A077EFU9 F
A0A1J5NNB8 F
A0A424WAH3 F
E1IF27 F
Q6LMI6 F
I0WJ97 F
A0A1X3RP39 F
A0A318FY98 F
A0A377PLP5 F
A0AA40J491 F
Q97L80 F
A0A068TC78 F
A0A2I1M481 F
A0A2K1RA77 F
F4D1J0 F
F8D7H6 F
A0A1G7VM92 F
A0A8H6NAG3 F
A7MFK3 F
B9SWW9 F
C7LW88 F
E0TCV4 F
A0A3E2VY88 F
A0NJ07 F
I4CCD1 F
A0A1I0BYN1 F
A0A4R3A5P7 F
A0A6H9FPY5 F
K0K7J4 F
Q1Q357 F
A0A0L0S493 F
A0A1H1MB73 F
A3ZT81 F
A7RNC3 F
Q2FQT3 F
A0A096EEV9 F
A0A1M7UEG2 F
B1Y842 F
A0A087L0B9 F
A0A2S5XAB8 F
Q2HD43 F
F4KY49 F
A0A4R3ZNW3 F
D7G265 F
Q2J376 F
A0A0D2KGN8 F
A4ABK3 F
F2AUF4 F
Q89WR5 F
A0A1B0ZRL8 F
A0A1B9K8L2 F
A0A2G5BI87 F
L8GFX3 F
E6SF19 F
S3K1S2 F
A0A0L0STS6 F
A0A2N0MZ27 F
A0A7G5DK18 F
A0A837C6X5 F
A9B874 F
D5EP68 F
U1PIR6 F
A0A063Y394 F
A0A1W2GZ82 F
A0A2W4ZXC0 F
A0A4R6DFU8 F
A0A7M6UUM4 V
Q84KJ7 F
A0A251XJT0 F
A0A2Z4MD56 F
A0A8H7U3I1 F
R9PMC6 F
A0A0E9NHV4 F
F0RHS0 F
F3KUN4 F
K9ZLY2 F
Q2GX26 F
A0A0B4M163 F
A0A4Y7XC43 F
A0A511NGC7 F
A4BAE1 F
A7HT14 F
Q1YDY8 F
U5DEY6 F
A0A172YBR4 F
A0A1E3PQH0 F
A0A2A7U6W1 F
A0A4R3ZZ35 F
P69681 F
Q2W5V2 F
A0A1G6ABK5 F
A0A1H4DJ49 F
D3F0Z1 F
A0A0E3BR91 F
A0A414NWT8 F
M5SYZ1 F
Q18PF5 F
Q2YBP7 F
A0A3E2UHE6 F
C3YB74 F
Q6LKC8 F
A0A1T4SFY6 F
Q1Q879 F
E0TGP9 F
A0A0E3QYF3 F
A0A248TDF2 F
A0A2G3DSU6 F
A0A494JB70 F
A4FMG0 F
A6VE60 F
A0A088E6Q7 F
A0A0C6P439 F
B0CQX4 F
K0N2R5 F
Q0I445 F
R1FI09 F
A0A8H4GS02 F
C1A872 F
D9QPC8 F
K0F9X7 F
Q1QS12 F
A0A0X8NXA9 F
A0A1H1U2Q6 F
A0A1H8D0R8 F
A0A257T8W6 F
A0A0A2B651 F
A5UJR1 F
P41948 F
Q0VQH6 F
A0A0G9HEC5 F
A0A165MFD1 F
A0A2S5V2F6 F
A0A433ZQ80 F
Q2IHY5 F
A0A0T7FAP8 F
M5S9B4 F
Q7NQY2 F
R9PI53 F
A0A1G7DX68 F
C7R314 F
K0NJH2 F
A0A176XNC5 F
A0A2G5RQK9 F
A0A562USB9 F
G9Y5B0 F
Q60BI2 F
W5WIX6 F
A0A1C6Z081 F
A0A2W5VAZ2 F
A5E3X2 F
D4XSW0 F
I5C044 F
Q2N625 F
Q47X17 F
V4AP67 F
A0A0F5EZP7 F
A0A248LNK5 F
A0AA46Q839 F
C9KKP2 F
J7IVQ1 F
K6W5X0 F
A0A0A3XTJ3 F
A0A4P6UIJ8 F
A0A4R8H081 F
B8J5X4 F
C1N5A7 F
Q63EK5 F
A0A011U1K7 F
A0A1X6N3Q5 F
A0A251XU71 F
A0A6N2Z556 F
B8GGC1 F
C1MHX0 F
F8IJE0 F
A0A085GI50 F
A0A291PMC6 F
A0A2T0XPP2 F
B0DXT9 F
C6WEW7 F
D4H5F9 F
A0A1J5NTP7 F
C3YB73 F
F2YIC4 F
K9W6F3 F
A0A4Y4DZN4 F
M8E0R3 F
Q1IWN6 F
Q2SIR0 F
Q7N0M6 F
Q8I0L6 F
A0A0A2C6L1 F
A0A101HKN9 F
A0A2W5HTC3 F
A0A660CH85 F
A0A6C8LST1 F
C1GR74 F
M4VEJ9 F
A0A0M3AB44 F
A0A1Y0HX98 F
A0A258FTB0 F
A0RUZ2 F
E3H8A6 F
I1YG38 F
A0A323UE08 F
D5V7B3 F
F4Y3C5 F
K9YJQ3 F
L0KGR8 F
L1IUV5 F
D2BUJ8 F
D3PE53 F
A0A0D7F328 F
A0A172YCA7 F
A0A1H9M798 F
A0A427KNL6 F
A0A7S0D560 F
A9BTK1 F
D3PKL4 F
E2SD44 F
F8E6R1 F
Q31CR9 F
Q5P1S8 F
A0A015YIP3 F
A0A9J9ES23 F
B9WDK0 F
G4R7P1 F
G8R7U9 F
Q1K433 F
A0A1I7FBM5 F
A0A5B2V3B9 F
I3Z3H7 F
A0A257TE48 F
B9SA70 F
E4T3F3 F
E8RSE4 F
J0S2I0 F
M1NZT5 F
A0A0E3SP24 F
A0A1L3F1X5 F
A0A6M3ZJI1 F
A0A258FS85 F
A0A3P2A7W8 F
A0A3S9N9F3 F
A0A5C5TUT2 F
C8WSI9 F
A0A6S5K4J1 F
A1AVV2 F
Q47K18 F
Q7T070 F
V4CRP5 F
A0A060JMP6 F
A0A7U3YMN6 F
A8P923 F
F7ZJZ1 F
I0HKQ8 F
V5E0F3 F
K9WSX4 F
A0A0A1ZMZ9 F
A0A1Z3MS36 F
A0A7S4GND2 F
A0A855EH99 F
C7LW87 F
H6RWK9 F
B0BZN3 F
O26757 F
Q4WHC6 F
X5DX97 F
A0A1B9JZS5 F
H2CDR5 F
Q5P470 F
A0A147GP06 F
A0A4R5U5V1 F
A0A5C5BWI6 F
A6M3G0 F
A8N2H6 F
A9V5W4 F
A0A0E3LMT4 F
A0A1B9NQ91 F
A0A3N0AQL8 F
C5KTM6 F
G0AFH4 F
W7QG13 F
T2KJ59 F
V4RHR4 F
A0A1G6ABL9 F
A0A858ZNJ3 F
F0J3F9 F
F2NGJ8 F
G0LFE3 F
Q6CRN1 F
H8L2Q4 F
L1INN6 F
A0A225CMT8 F
A0A2N6JV02 F
A0A482TED1 F
A0A6F8TLE9 F
A0A853MG28 F
A0A9E9LXV9 F
Q1Z695 F
Q46G49 F
Q84KJ6 F
F4B548 F
H6LKH6 F
A0A149UWF2 F
A0A1E5C7W4 F
A0A2T5IHP0 F
A0A401WUW1 F
A0A8F5ZDT8 F
F0ZCX7 F
I4C9L0 F
I4D1H5 F
Q0F2M5 F
A0A1B9M1A9 F
C9R9J0 F
Q95P70 F
R1EDV9 F
A0A063Y780 F
A0A5M5PZE2 F
B0DU93 F
B8EMQ8 F
D3DJN2 F
Q0G0A3 F
A0A060HFT5 F
A8PXT8 F
C8XB51 F
I4DBY0 F
J7J5E7 F
Q9H310 F
Q9UBD6 F
A0A1W5PRD1 F
A0A2S5Y0D3 F
A0A4R2Z2K6 F
B7X047 F
Q18ES8 F
Q5QVH2 F
A0A1W2H3F0 F
B3MX93 F
O04161 F
A0A556RTU3 F
A0A833LX85 F
A0A9R0NTP8 F
D2Q0J8 F
E3GI40 F
A0A2S5CTX8 F
A0A016XCG9 F
A0A165BP25 F
D2R647 F
A0A2T2Y0D5 F
A0A366WYI9 F
A0AA92EGF5 F
B0XVV6 F
F5ISF6 F
A0A142NNN1 F
A0A855F5Y8 F
A6DUG4 F
M7NFH3 F
N1WR17 F
C0QTA4 F
Q9VFA9 F
T2JFS5 F
A7HSP2 F
J2ZGN6 F
L7CG99 F
A0A0H3KTD3 F
A1SZ12 F
C0GKN4 F
A7S3L2 F
E4YA63 F
E5Y789 F
F0JGZ1 F
G3A431 F
R7PZ71 F
A7I8Z4 F
F7NPQ3 F
A0A399NT81 F
A0A6A1TYJ4 F
A0A6H9FYW4 F
A0A833H2R7 F
A0A1E2SKM1 L
A7SQ16 F
B8FZP7 F
C7M2A9 F
Q2WBF7 F
B8ZYW3 F
A0A2N6P374 F
A0A4R3NLV5 F
A0A7T5BFQ2 F
A4BEP1 F
A6GJF5 F
B8FDY8 F
A0A7R6PER3 F
D2BIB2 F
F6G5I9 F
Q605Y6 F
Q6BJI7 F
A0A0A1ZJU5 F
A0A0S6UHP2 F
A0A3E0X011 F
A0A4U1K1W1 F
A1CQ21 F
D6SPD1 F
A0A0A0D6K5 F
C0QSY0 F
F2G6G4 F
Q2RVB5 F
Q7T3R4 F
A0A251YU48 F
A0A2S8FR08 F
A0A4R3NVT3 F
A6W7U2 F
E4RTK5 F
A0A075JZ35 F
A0A2S5WUP6 F
Q46HB1 F
A0A1Y2JH43 F
A0A857DDJ7 F
K9P718 F
I1YJH7 F
Q0AT01 F
A0A149TSA9 F
A0A165K0X5 F
A0A1E5BXA4 F
A0A1G9P6Q0 F
A0A2S5X482 F
A0A657K391 F
A0A211ZGL5 F
A0A377PBY1 F
A0A7T4WEP4 F
C8WZE0 F
A0A173R3W6 F
A0A2N7L7C8 F
A0A5C6LWQ1 F
T2KGT3 F
A0A7U4E420 F
B2IJT1 F
D6Z5V9 F
Q2KZK9 F
A0A6N2TIA4 F
A8MCL4 F
F5XN43 F
A0A087EQK8 F
A0A094W9G3 F
A0A9Q8L398 F
A2SPS8 F
A0A1Q2C7H7 F
A0A2C9CK98 F
J1L5M8 F
C3X831 F
M0J579 F
A0A037ZMW1 F
A0A068SVR1 F
A0A251YFS0 F
A0A258HPP1 F
A3TVQ9 F
A6LRS5 F
Q2RWY7 F
V4REY8 F
A0A1H7CU41 F
A0AA92K392 F
B9ACS5 F
W0DZX1 F
A5CRL2 F
M0D580 F
M1SJL5 F
Q92BJ7 F
U5C4L4 F
D8J4C6 F
A0A060HN92 F
A0A098S5Y7 F
A0A0K2STH0 F
A0A174SD65 F
A0A2N7LCD7 F
A0A4P7UHQ5 F
B0SLB7 F
D2R355 F
D3S2L0 F
F0S0G1 F
I4D6Z7 F
A0A071MMV1 F
A0A168EVK8 F
A0A1D8UWJ6 F
A0A502GPV4 F
A0A542XGT4 F
A0A7U8C744 F
A0A2S5WZU0 F
A0A369M386 F
W0JIB3 F
Q6HM26 F
Q7SEH0 F
A0A177W826 F
A0A1M6JKY3 F
A0A375YPN6 F
B0SL05 F
B4D7W2 F
D2V6Q5 F
A0A7Z0V0A4 F
C1D4X0 F
E3I393 F
Q5FLR6 F
Q1K3N8 F
A0A091AXI3 F
A0A2R4TRE0 F
A0A5P9P1L2 F
J4UGB7 F
L0FU80 F
Q1JXS5 F
G4QHD2 F
J7L3W8 F
A0A0P6VSR8 F
A0A1B9MBX6 F
A0A328EMN2 F
A3ZZL7 F
B0CXH8 F
D5AU98 F
L7CG11 F
A0A3E2TW06 F
D4F313 F
R1D1H4 F
U3PCH5 L
A0A127JTU2 F
A0A7S0ILH2 F
V4RK08 F
A0A2N6NEK4 F
A0A2R4MBA2 F
F0ZPL3 Y
G0EFF3 F
G2ZN72 F
Q6BK68 M
A0A0S2DQB6 F
A0A1G6ABX1 F
A0A2S8QA29 F
A7SGD4 F
M1V7W3 F
D5EP71 F
L1IYW7 F
A0A075WEB4 F
A0AA94HTL8 F
B8IZX4 F
C7NND3 F
D3FBG3 F
D5ELM4 F
M9YAI9 F
Q07UM1 F
Q4WT12 F
Q9BLG3 F
A0A242NIL1 F
A0A6J5IRX5 F
A0A836M2B6 F
A0A9W5JBA9 F
L0K9M1 F
Q3Z7F9 F
W0F0I7 F
A0A6G9Y3Q0 F
G7WCB6 F
G7WFX4 F
K9YR86 F
Q7S5K0 F
Q9NIV0 F
A0A0V8M0W6 F
B4CV94 F
B7FSA7 F
F6FRU9 F
A0A1S8D478 F
A0A1W9KSU5 F
A0A2M9D7S8 F
A0A2S8F4W0 F
I4D6Z9 F
L0KW14 F
A0A212AV03 F
A0A9Y2AG30 F
A3U857 F
B4HDZ9 F
B9L7N1 F
J9Z839 F
U1PPI7 F
A0A059XXR1 F
A0A067Z3S3 F
A0A0A2A0Y9 F
A0A178TA08 F
A0A7S0KKL8 F
Q466Y3 F
A0A076PL76 F
A0A243SC06 F
B0DY50 F
G2T1Y3 F
A0A0U1NJW3 F
A0A264VQM8 F
A0A2S5YID7 F
A0A8G2IZM3 F
E4NS62 F
Q1H0G2 F
A0A0A2ZRL7 F
A0A149QSR6 F
A8ZQD5 F
I8TC71 F
K2JVF8 F
B3DUX7 F
I2GD40 F
K5CFE5 F
Q6ND36 F
A0A366IE34 F
A6XBM2 F
C3X1J1 F
F7ZEU9 F
G0IYI2 F
G0JRH4 F
Q2YLQ6 F
A0A4P8HC89 F
A0A5J6WQU1 F
A0A8E2R1Y5 F
A5D4I5 F
B1XZU2 F
B1Y6V4 F
C8XBX8 F
F0YLV7 F
Q0G2T1 F
A0A034WGQ2 F
A0KPE9 F
K9P5D1 F
Q6BT62 F
A0A0L0TDW1 F
A0A165MAC2 F
A0A1B9KID3 F
A0AA91Q161 F
I0HGY4 F
A0A6H9GEE4 F
A0A979GQ79 F
C6LBD3 F
F3QPR6 F
F3ZVV4 F
F6BEI0 F
A0A140NHJ5 F
A0A653N397 F
A0AA35XZV0 F
A7NKH2 F
B8JBH5 F
D3PAH1 F
Q0VPH4 F
W0E077 F
A0A074KY88 F
A0A0S4WFM4 F
A0A495DND0 F
B7FTM9 F
A0A423Y4I6 F
A0A4U1JNL6 F
A0A6T9XUR2 F
A0A9P3CXY2 F
A2BUP4 F
A4CMI3 F
R4FZE3 F
U2WTW8 F
A0A1B9BUU6 F
A9BIZ7 F
B7FW68 F
D8PD01 F
K9Z0D3 F
W7QGE0 F
A0A381CAY8 F
B1Y8C9 F
C6CBB1 F
K8W1E2 F
Q21P82 F
A0A0H3LUA3 F
A0A2S8GEJ5 F
A0A315S845 F
I0JI83 F
Q7TNN9 F
A0A149UP06 F
A0A369MRW6 F
E0SD83 F
F3QNA7 F
A0A0D7F2Y9 F
A0A0S2FHD7 F
A2CCK1 F
Q0G0A4 F
R1EGK6 F
R9GM11 F
A0A202B535 F
A0A854QN45 F
A0A8H6K7L7 F
C1F584 F
I3R0S7 F
A0A1I4W3A0 F
A0A1J5JH24 F
A0A2H4U5R1 F
A0A6P4JM51 F
B8FL88 F
C8WLL8 F
Q0VLH1 F
A0A081N2G5 F
A0A378YR15 F
D9QPE5 F
E6ME92 F
F3ZYD6 F
G0JRG9 F
K8EJ02 F
A0A290XBB5 F
A0A2A2MCP3 F
A0A2I0UUY1 F
A0A5C5TYS5 F
B1Y0E5 F
D0MFE8 F
A0A2G6JLT9 F
A0A510HHK8 F
A0A5C4RNH5 F
C5BWX7 F
D5E995 F
A0A0B4DUR9 F
A0A1V2XMU9 F
A0A1Y6GLJ1 F
A0A2S0Q8P1 F
A0A369N7Y3 F
A0A1Y3U5V2 F
F2JZ83 F
G8JTW0 F
Q0ACK1 F
A0A1Y5E8I7 F
A0A4R7GKA0 F
D5ASL9 F
E8RLT5 F
L0JT30 F
A0A068NPW2 F
A0A149RYW7 F
A0A1B9BUZ8 F
A0A3N1VXY4 F
B0SRS8 F
C7Q1E4 F
A0A144NLT9 F
A2SS52 F
F5Y3C1 F
A0A149V596 F
F0J6E8 F
A0A0K2STK6 F
A0A366XFS8 F
A0A418VIJ8 F
M9RJS5 F
W8KM07 F
A0A0E3R4G0 F
A0A3G9G4Q4 F
F5L8M7 F
H1XV27 F
M0D3Q9 F
Q22947 F
A0A4Q2QWS1 F
H2CLF7 F
Q608B6 F
A0A1X4GBG2 F
A0A4P6UIK6 F
A0A857DMN9 F
E4TJ50 F
F0J7D3 F
Q8JI14 F
A0A1Y0V4A5 F
I0ICG0 F
Q3AFY9 F
A0A0A2AMW2 F
H2IZ00 F
K5DBA0 F
A0A149QAW7 F
A0A2K3DPU7 F
I7ZHW3 F
U1SIR9 F
U1H1F7 F
A0A399T909 F
A9UR54 F
E4N1T5 F
G7WFX2 F
H1YF74 F
R8VWI7 F

In [47]:
onethreefive = []
seqotf = []
ididid = []

for i in otf:
    print(i.id, i.seq)
    onethreefive.append(f"{i.id} {i.seq}")
    seqotf.append(i.seq)
    ididid.append(i.id)

A0A1X4G8K1 F
A0A2X2C038 F
L8H844 F
A0A066ZRQ5 F
A0A075JIN0 F
A0A318QZ80 F
A1DG05 F
G0VI62 F
A0A016XDZ5 F
A0A0S6UEK9 F
A8NAG3 F
Q8RUT6 F
A0A2K1RA81 F
A0A4R4K1P9 F
A0A4R7VEK0 F
A0A7S4GNJ2 F
B4S394 F
C1D6X6 F
A0A0E3QY86 F
A0A1B9LFW3 F
A0A258HS77 F
A0A495D4X4 F
A0A7G5DKA9 F
K8VZC6 F
F5RGM7 F
I6Z905 F
A0A075WG29 F
A0A0B4E6X7 F
A9AUR8 F
B7G0Y1 F
D0MFE9 F
E2SD33 F
A0A097R891 F
A0A0H3H4I7 F
A0A6N4SPH9 F
A6LV49 F
D3F545 F
A0A1E3PSK5 F
A0A3N2SFS2 F
A0A401X433 F
A0A5M4AUM9 F
A0A149U2G9 F
A0A2S5WV24 F
A0A2S7YIM5 F
A0A3E2T713 F
E6W5C1 F
O66395 F
P69680 F
Q7Z1M1 F
A0A037ZJY5 F
A0A1G5W0P2 F
A0A2G3E8V2 F
A0A2S6GKN5 F
A0A7H8UK07 F
A8M670 F
A0A0K2STQ7 F
A0A5M4ATH9 F
A9DQM8 F
H1YCC3 F
Q1YDY7 F
Q45HK8 F
A0A0D2UPA8 F
A0A142VAD6 F
A0A2T4XZC1 F
A0A420WC79 F
A4G1J2 F
Q6ND34 F
V3ZVE4 F
A0A2S6H6B7 F
A0A3T0SZ22 F
E4U5Z1 F
G0J614 F
G5EB13 F
G8JUJ2 F
A0A1U9Z147 F
A0A2T1N7R1 F
U5C2K4 F
Q5FSX6 F
A0A0A2A5X1 F
A0A1M6ZMI3 F
A0A829X098 F
A0A9Q6P4A5 F
F0Y9X3 F
Q221S8 F
F4H924 F
A0A2G5BGA9 F
A0A3E2UCG9 F
A0A533I6R2 F
B3PF77 F
E4T0A4 F
F4GED5 F
A0A7G5DPV1 F
B8FGW0 F
K9WT03 F
T2J0N1 F
W0DYY3 F
A0A1M5ZVP9 F
I4C9L2 F
L8GGA0 F
A0A2T0GTU1 F
A4G0C5 F
Q0G2V0 F
Q3B6Q2 F
Q6ARH0 F
A0A0E3R6S1 F
A0A5M4B0G1 F
A0A7G5EC77 F
A1C5Z7 F
F7ZJM0 F
J4KM12 F
A0A172RYW3 F
A0A1B9M5B8 F
A0A2S5WGI8 F
A9BQZ4 F
D0LTW3 F
Q9QUT0 F
A0A1G7H8X3 F
A0A1G7UZX2 F
A0A2S8FTB5 F
A0A087MGU4 F
A0A410JZR4 F
A0A6U2BIY7 F
B3QVV5 F
C7BJG7 F
Q82X47 F
A0A066ZTE4 F
A0A7S4LPS8 F
B0DFJ4 F
G4H971 F
I5AZQ4 F
Q0ARJ4 F
A0A5J6WPP9 F
L1IYP4 F
M1P5F0 F
A0A0D2LEF5 F
A0A562S8V2 F
D2SE15 F
F2B2B8 F
H6LFQ2 F
H6LKH9 F
Q1PX09 F
A0A0A2BBY0 F
A0A2S8GSU9 F
A0A7S4GMD8 F
L8H5K0 F
A0A1B9JPL5 F
A0A1B9MZ78 F
A0A1S1HRJ0 F
A0A317G0I6 F
A7HSN9 F
Q5FA36 F
E3HJW8 F
Q2IK04 F
A0A0E3SHQ9 F
A0A101DCS3 F
A0A1I0AQM4 F
A0A377I7W9 F
A0A975BTN0 F
A9HMD6 F
A0A2S0JW39 F
A0A975GIX9 F
A0A0D8BQX6 F
A0A1Y5E3E3 F
A0A9J9BAE8 F
D7E934 F
E5Y678 F
A0A1G5PWV0 F
A0A1G5RZU9 F
A0A1M6BPM0 F
A0A7T2W1B3 F
G2PRJ6 F
A0A1U9YY82 F
A0A918MJ52 F
D7UQE2 F
K9U8C7 F
M1WRK6 F
K1K628 F
A0A068NV61 F
A0A1H3WA00 F
A0A2N6K4Y5 F
A5DYQ2 F
B0RC35 F
J3EXK0 F
A0A1J1JH03 F
A0AIW5 F
K2IMJ7 F
L1IHZ8 F
Q2RM12 F
Q6CRN0 F
A0A075WBP9 F
A0A160KTE9 F
L1J6I4 F
A0A0E3WZH5 F
A0A4D6KHD1 F
D3RN22 F
M2ALH9 F
G0JRQ3 F
H6LKX6 F
A0A009PYN3 F
A0A3G9G2C9 F
A0A562RGZ4 F
B2GFN1 F
B3PIH2 F
E7RJZ0 F
K9ZG59 F
M7XJ51 F
Q13E03 F
Q59UP8 F
A0A021VMC6 F
A0A1H4KAQ7 F
A0A248LNW8 F
D0KXQ0 F
Q1AUG3 F
Q1K0H9 F
A0A4Q2EAG7 F
A2BP62 F
A0A071M4L5 F
A0A1C7EL50 F
A0A257T7G4 F
A0A2J7TJ33 F
A0A2S0P9T4 F
A0A2V4EA49 F
Q7UYZ3 F
A0A0S4VNK2 F
G7WDB5 F
I5B3H0 F
A0A5M8QF12 F
A0AA86YS65 F
A0A166IS52 F
A0A1I5GN22 F
A0A1Y0UZX2 F
A0A2A2M8K7 F
A0A2K3DQF8 F
A0A395VB65 F
D2RU19 F
M0MDP9 F
J1ASR8 F
Q7UGU7 F
A0A089ZBW5 F
A0A2S5WX34 F
A0A6H9GLV4 F
A0A6H9GWG4 F
A0A854Q6X9 F
E5B358 F
W7QGM4 F
A0A4V0XUI3 F
A7SED8 F
D4XLN6 F
D5VJ32 F
F2JYR9 F
Q8RUE9 F
A0A1I0C958 F
A0A1V3SSW1 F
A0A410K1J5 F
A0LV78 F
Q0BWD0 F
S0EUS1 F
A0A1R1IDV3 F
B8ENL9 F
G0JRG6 F
S0G181 F
S5ABR8 F
A0A0L8BVU4 F
A0A0T7GZ59 F
A0A323UDG5 F
A0A556SRH6 F
A0A251Y3N4 F
A0A373FQ71 F
K0ER80 F
A7I8Z2 F
M5S735 F
A8HSA2 F
B0VMH1 F
G3IYW2 F
H5UND3 F
Q2S8H9 F
A0A2S6GKF6 F
A0A6M3ZKU5 F
Q21CP1 F
A0A8E2UDJ3 F
C7LQR9 F
A0A060UWC8 F
Q7V4T8 F
S0APH6 F
A0A2H1HV86 F
A0A482PLH3 F
A0A7G5DPV0 F
A0A7V8IKS6 F
G5EB09 F
M5SY07 F
A0A127PIQ9 F
A0A4Q7Y9I7 F
A0A562BXM4 F
A0A6H9GFU4 F
W0DZS7 F
A0A1B9N3H7 F
A0A5A7MAJ9 F
A1D2Y5 F
C5LAG4 F
C9RS76 F
A0A8H7P8U1 F
A0AA35XVN2 F
Q7W7D3 F
V5BYZ7 F
A0A0D2NYP3 F
A0A4V2X6C2 F
A3PAY4 F
C5CIT6 F
C6XKC2 F
U2EN72 F
A0A379A0S9 F
D5T4N9 F
G7WJN0 F
Q5KPM5 F
A0A147EQL9 F
A0A1I4ZIZ6 F
A0A7S4GNF3 F
D3LBI0 F
I1DSU5 F
A0A2U1SS17 F
K9YN27 F
P40260 F
A0A1T4SF40 F
A0A8G2F3G4 F
D6E7B3 F
I5BYV5 F
Q9QXP0 F
V5U2Z4 F
A0RXK8 F
H1Y7T6 F
A0A074KZD8 F
A0A074ME37 F
A0A5M4AWD2 F
J9VXX9 F
L8JUH3 F
Q21J04 F
A0A8F5VN39 F
E1QFA8 F
E1SLM7 F
G3IYW0 F
A0A017SYR8 F
A0A2S7YPJ9 F
A0A7U3XVQ4 F
B8GGC3 F
B9LU00 F
I0KDC6 F
Q1L727 F
A0A009TDB1 F
A0A1D3GAE9 F
A0A317FZW2 F
A0A4R2M206 F
C0Z5S5 F
F0S3Z6 F
A0A1Y4LM49 F
A0A369MHK2 F
A4BMY5 F
B9SXC7 F
D2ZRW2 F
Q1H483 F
A0A062IU58 F
A0A1B9JHS5 F
A0A1T4SFK4 F
A0A9E9L9J1 F
J7ITF6 F
A0A2C6C0X3 F
I9P003 F
Q488X2 F
X5CNT2 F
A0A4R8GSH7 F
D5UD26 F
S9QZ09 F
A0A149RQX0 F
A0A419AVL2 F
A0A4Y1MSE7 F
Q81GN5 F
U7VB41 F
G0V8D6 F
Q5KZZ9 F
A0A0H3DR67 F
A0A1B9MYL7 F
D0L8H3 F
D3RMV7 F
F2JTN3 F
F2NNQ0 F
Q6QH01 F
E4T3F7 F
G0H0Z6 F
A0A6B8N021 F
A8AC17 F
A8G2S3 F
Q0F2M7 F
S0ET45 F
K1LDP0 F
Q1QSQ2 F
A0A330GB00 F
A0A9Q5QVI9 F
A3XNG6 F
D6TFE1 F
E1V4T3 F
H2CJI0 F
T2IEJ2 F
A0A833GZR2 F
A1SY01 F
C8X554 F
E1QIU3 F
Q1K8A3 F
Q9M6N7 F
A0A8B4RWH8 F
A1VIM5 F
A0A060URC3 F
A0A328Q6M1 F
Q8GQS1 F
A0A2T4UWF1 F
A0A420KGW4 F
A9WHW6 F
B3QRJ4 F
I3C0V3 F
Q8ERT9 F
C1G973 F
E4TRS4 F
G7UUY6 F
M2A398 F
Q60C43 F
A0A0M2LU39 F
A0A1H1BPD6 F
A0A257SYX3 F
A0A2S5WMT7 F
B1ZSW9 F
Q5UZ98 F
A0A0B5FNH4 F
A0A173R3X4 F
A0A380S5X4 F
A0A9W3LFI9 F
D4H2Y7 F
G8TK77 F
A0A1Y4L5P0 F
A0A2S8GF54 F
A0A2T9X1V4 F
A0A401WXG0 F
A0A642KQG8 F
A0A161SKF4 F
A0A9Q9D9I3 F
A1B3N0 F
D4GLQ6 F
Q94CJ2 F
A0A0H2XSU4 F
C4Y298 F
D2V6P8 F
E3H8C9 F
F5R974 F
M5U2P1 F
Q0BQ69 F
A0A073CP02 F
B0DU91 F
B1JZ69 F
B7GKP4 F
D9SI36 F
G7WA28 F
Q1Z4I4 F
Q9REX3 F
A0A0A2VPU3 F
A0A1A0DHK0 F
A0A1S1HM83 F
A0A248LMH8 F
A2C095 F
D0LAL7 F
E6VIW4 F
A0A316BQ38 F
A0A369NYJ2 F
A0A370FPU0 F
A0A8H6MPB9 F
A1VIG8 F
A7S731 F
K9W4V5 F
A0A0D5YN10 F
A0A2R3IMJ8 F
B7G0Y4 F
Q07UM3 F
U3P8G1 F
A0A830ZZN8 F
A1ZGK6 F
A8LKQ0 F
C1MX19 F
D9SI59 F
A0A977NL43 F
A1SVA8 F
C1N6X9 F
C7QGX3 F
A0A2S6H643 F
Q7NCB8 F
Q2FS34 F
A0A3R9Q7C4 F
A0A495WJM6 F
A0A7T2S0Z6 F
A0A7U4DN04 F
F4XTK4 F
M9RKT6 F
A0A0X8X7Y7 F
A0A7U8C2Y6 F
A0A8G2F718 F
A6DN47 F
Q5KAF6 F
A0A060URB8 F
A0A1H9RTW8 F
A0A4V3ALP8 F
D9QS43 F
A0A2W0GQV0 F
A0A6G9XJV9 F
C6DB68 F
D6TCH6 F
Q3AP28 F
A0A060UN76 F
A0A077EFU9 F
A0A1J5NNB8 F
A0A424WAH3 F
E1IF27 F
Q6LMI6 F
I0WJ97 F
A0A1X3RP39 F
A0A318FY98 F
A0A377PLP5 F
A0AA40J491 F
Q97L80 F
A0A068TC78 F
A0A2I1M481 F
A0A2K1RA77 F
F4D1J0 F
F8D7H6 F
A0A1G7VM92 F
A0A8H6NAG3 F
A7MFK3 F
B9SWW9 F
C7LW88 F
E0TCV4 F
A0A3E2VY88 F
A0NJ07 F
I4CCD1 F
A0A1I0BYN1 F
A0A4R3A5P7 F
A0A6H9FPY5 F
K0K7J4 F
Q1Q357 F
A0A0L0S493 F
A0A1H1MB73 F
A3ZT81 F
A7RNC3 F
Q2FQT3 F
A0A096EEV9 F
A0A1M7UEG2 F
B1Y842 F
A0A087L0B9 F
A0A2S5XAB8 F
Q2HD43 F
F4KY49 F
A0A4R3ZNW3 F
D7G265 F
Q2J376 F
A0A0D2KGN8 F
A4ABK3 F
F2AUF4 F
Q89WR5 F
A0A1B0ZRL8 F
A0A1B9K8L2 F
A0A2G5BI87 F
L8GFX3 F
E6SF19 F
S3K1S2 F
A0A0L0STS6 F
A0A2N0MZ27 F
A0A7G5DK18 F
A0A837C6X5 F
A9B874 F
D5EP68 F
U1PIR6 F
A0A063Y394 F
A0A1W2GZ82 F
A0A2W4ZXC0 F
A0A4R6DFU8 F
A0A7M6UUM4 F
Q84KJ7 F
A0A251XJT0 F
A0A2Z4MD56 F
A0A8H7U3I1 F
R9PMC6 F
A0A0E9NHV4 F
F0RHS0 F
F3KUN4 F
K9ZLY2 F
Q2GX26 F
A0A0B4M163 F
A0A4Y7XC43 F
A0A511NGC7 F
A4BAE1 F
A7HT14 F
Q1YDY8 F
U5DEY6 F
A0A172YBR4 F
A0A1E3PQH0 F
A0A2A7U6W1 F
A0A4R3ZZ35 F
P69681 F
Q2W5V2 F
A0A1G6ABK5 F
A0A1H4DJ49 F
D3F0Z1 F
A0A0E3BR91 F
A0A414NWT8 F
M5SYZ1 F
Q18PF5 F
Q2YBP7 F
A0A3E2UHE6 F
C3YB74 F
Q6LKC8 F
A0A1T4SFY6 F
Q1Q879 F
E0TGP9 F
A0A0E3QYF3 F
A0A248TDF2 F
A0A2G3DSU6 F
A0A494JB70 F
A4FMG0 F
A6VE60 F
A0A088E6Q7 F
A0A0C6P439 F
B0CQX4 F
K0N2R5 F
Q0I445 F
R1FI09 F
A0A8H4GS02 F
C1A872 F
D9QPC8 F
K0F9X7 F
Q1QS12 F
A0A0X8NXA9 F
A0A1H1U2Q6 F
A0A1H8D0R8 F
A0A257T8W6 F
A0A0A2B651 F
A5UJR1 F
P41948 F
Q0VQH6 F
A0A0G9HEC5 F
A0A165MFD1 F
A0A2S5V2F6 F
A0A433ZQ80 F
Q2IHY5 F
A0A0T7FAP8 F
M5S9B4 F
Q7NQY2 F
R9PI53 F
A0A1G7DX68 F
C7R314 F
K0NJH2 F
A0A176XNC5 F
A0A2G5RQK9 F
A0A562USB9 F
G9Y5B0 F
Q60BI2 F
W5WIX6 F
A0A1C6Z081 F
A0A2W5VAZ2 F
A5E3X2 F
D4XSW0 F
I5C044 F
Q2N625 F
Q47X17 F
V4AP67 F
A0A0F5EZP7 F
A0A248LNK5 F
A0AA46Q839 F
C9KKP2 F
J7IVQ1 F
K6W5X0 F
A0A0A3XTJ3 F
A0A4P6UIJ8 F
A0A4R8H081 F
B8J5X4 F
C1N5A7 F
Q63EK5 F
A0A011U1K7 F
A0A1X6N3Q5 F
A0A251XU71 F
A0A6N2Z556 F
B8GGC1 F
C1MHX0 F
F8IJE0 F
A0A085GI50 F
A0A291PMC6 F
A0A2T0XPP2 F
B0DXT9 F
C6WEW7 F
D4H5F9 F
A0A1J5NTP7 F
C3YB73 F
F2YIC4 F
K9W6F3 F
A0A4Y4DZN4 F
M8E0R3 F
Q1IWN6 F
Q2SIR0 F
Q7N0M6 F
Q8I0L6 F
A0A0A2C6L1 F
A0A101HKN9 F
A0A2W5HTC3 F
A0A660CH85 F
A0A6C8LST1 F
C1GR74 F
M4VEJ9 F
A0A0M3AB44 F
A0A1Y0HX98 F
A0A258FTB0 F
A0RUZ2 F
E3H8A6 F
I1YG38 F
A0A323UE08 F
D5V7B3 F
F4Y3C5 F
K9YJQ3 F
L0KGR8 F
L1IUV5 F
D2BUJ8 F
D3PE53 F
A0A0D7F328 F
A0A172YCA7 F
A0A1H9M798 F
A0A427KNL6 F
A0A7S0D560 F
A9BTK1 F
D3PKL4 F
E2SD44 F
F8E6R1 F
Q31CR9 F
Q5P1S8 F
A0A015YIP3 F
A0A9J9ES23 F
B9WDK0 F
G4R7P1 F
G8R7U9 F
Q1K433 F
A0A1I7FBM5 F
A0A5B2V3B9 F
I3Z3H7 F
A0A257TE48 F
B9SA70 F
E4T3F3 F
E8RSE4 F
J0S2I0 F
M1NZT5 F
A0A0E3SP24 F
A0A1L3F1X5 F
A0A6M3ZJI1 F
A0A258FS85 F
A0A3P2A7W8 F
A0A3S9N9F3 F
A0A5C5TUT2 F
C8WSI9 F
A0A6S5K4J1 F
A1AVV2 F
Q47K18 F
Q7T070 F
V4CRP5 F
A0A060JMP6 F
A0A7U3YMN6 F
A8P923 F
F7ZJZ1 F
I0HKQ8 F
V5E0F3 F
K9WSX4 F
A0A0A1ZMZ9 F
A0A1Z3MS36 F
A0A7S4GND2 F
A0A855EH99 F
C7LW87 F
H6RWK9 F
B0BZN3 F
O26757 F
Q4WHC6 F
X5DX97 F
A0A1B9JZS5 F
H2CDR5 F
Q5P470 F
A0A147GP06 F
A0A4R5U5V1 F
A0A5C5BWI6 F
A6M3G0 F
A8N2H6 F
A9V5W4 F
A0A0E3LMT4 F
A0A1B9NQ91 F
A0A3N0AQL8 F
C5KTM6 F
G0AFH4 F
W7QG13 F
T2KJ59 F
V4RHR4 F
A0A1G6ABL9 F
A0A858ZNJ3 F
F0J3F9 F
F2NGJ8 F
G0LFE3 F
Q6CRN1 F
H8L2Q4 F
L1INN6 F
A0A225CMT8 F
A0A2N6JV02 F
A0A482TED1 F
A0A6F8TLE9 F
A0A853MG28 F
A0A9E9LXV9 F
Q1Z695 F
Q46G49 F
Q84KJ6 F
F4B548 F
H6LKH6 F
A0A149UWF2 F
A0A1E5C7W4 F
A0A2T5IHP0 F
A0A401WUW1 F
A0A8F5ZDT8 F
F0ZCX7 F
I4C9L0 F
I4D1H5 F
Q0F2M5 F
A0A1B9M1A9 F
C9R9J0 F
Q95P70 F
R1EDV9 F
A0A063Y780 F
A0A5M5PZE2 F
B0DU93 F
B8EMQ8 F
D3DJN2 F
Q0G0A3 F
A0A060HFT5 F
A8PXT8 F
C8XB51 F
I4DBY0 F
J7J5E7 F
Q9H310 F
Q9UBD6 F
A0A1W5PRD1 F
A0A2S5Y0D3 F
A0A4R2Z2K6 F
B7X047 F
Q18ES8 F
Q5QVH2 F
A0A1W2H3F0 F
B3MX93 F
O04161 F
A0A556RTU3 F
A0A833LX85 F
A0A9R0NTP8 F
D2Q0J8 F
E3GI40 F
A0A2S5CTX8 F
A0A016XCG9 F
A0A165BP25 F
D2R647 F
A0A2T2Y0D5 F
A0A366WYI9 F
A0AA92EGF5 F
B0XVV6 F
F5ISF6 F
A0A142NNN1 F
A0A855F5Y8 F
A6DUG4 F
M7NFH3 F
N1WR17 F
C0QTA4 F
Q9VFA9 F
T2JFS5 F
A7HSP2 F
J2ZGN6 F
L7CG99 F
A0A0H3KTD3 F
A1SZ12 F
C0GKN4 F
A7S3L2 F
E4YA63 M
E5Y789 F
F0JGZ1 F
G3A431 F
R7PZ71 F
A7I8Z4 F
F7NPQ3 F
A0A399NT81 F
A0A6A1TYJ4 F
A0A6H9FYW4 F
A0A833H2R7 F
A0A1E2SKM1 L
A7SQ16 F
B8FZP7 F
C7M2A9 F
Q2WBF7 F
B8ZYW3 F
A0A2N6P374 F
A0A4R3NLV5 F
A0A7T5BFQ2 F
A4BEP1 F
A6GJF5 F
B8FDY8 F
A0A7R6PER3 F
D2BIB2 F
F6G5I9 F
Q605Y6 F
Q6BJI7 F
A0A0A1ZJU5 F
A0A0S6UHP2 F
A0A3E0X011 F
A0A4U1K1W1 F
A1CQ21 F
D6SPD1 F
A0A0A0D6K5 F
C0QSY0 F
F2G6G4 F
Q2RVB5 F
Q7T3R4 F
A0A251YU48 F
A0A2S8FR08 F
A0A4R3NVT3 F
A6W7U2 F
E4RTK5 F
A0A075JZ35 F
A0A2S5WUP6 F
Q46HB1 F
A0A1Y2JH43 F
A0A857DDJ7 F
K9P718 F
I1YJH7 F
Q0AT01 F
A0A149TSA9 F
A0A165K0X5 F
A0A1E5BXA4 F
A0A1G9P6Q0 F
A0A2S5X482 F
A0A657K391 F
A0A211ZGL5 F
A0A377PBY1 F
A0A7T4WEP4 F
C8WZE0 F
A0A173R3W6 F
A0A2N7L7C8 F
A0A5C6LWQ1 F
T2KGT3 F
A0A7U4E420 F
B2IJT1 F
D6Z5V9 F
Q2KZK9 F
A0A6N2TIA4 F
A8MCL4 F
F5XN43 F
A0A087EQK8 F
A0A094W9G3 F
A0A9Q8L398 F
A2SPS8 F
A0A1Q2C7H7 F
A0A2C9CK98 F
J1L5M8 F
C3X831 F
M0J579 F
A0A037ZMW1 F
A0A068SVR1 F
A0A251YFS0 F
A0A258HPP1 F
A3TVQ9 F
A6LRS5 F
Q2RWY7 L
V4REY8 F
A0A1H7CU41 F
A0AA92K392 F
B9ACS5 F
W0DZX1 F
A5CRL2 F
M0D580 F
M1SJL5 F
Q92BJ7 F
U5C4L4 F
D8J4C6 F
A0A060HN92 F
A0A098S5Y7 F
A0A0K2STH0 F
A0A174SD65 F
A0A2N7LCD7 F
A0A4P7UHQ5 F
B0SLB7 F
D2R355 F
D3S2L0 F
F0S0G1 F
I4D6Z7 F
A0A071MMV1 F
A0A168EVK8 F
A0A1D8UWJ6 F
A0A502GPV4 F
A0A542XGT4 F
A0A7U8C744 F
A0A2S5WZU0 F
A0A369M386 F
W0JIB3 F
Q6HM26 F
Q7SEH0 F
A0A177W826 F
A0A1M6JKY3 F
A0A375YPN6 F
B0SL05 F
B4D7W2 F
D2V6Q5 F
A0A7Z0V0A4 F
C1D4X0 F
E3I393 F
Q5FLR6 F
Q1K3N8 F
A0A091AXI3 F
A0A2R4TRE0 F
A0A5P9P1L2 F
J4UGB7 F
L0FU80 F
Q1JXS5 F
G4QHD2 F
J7L3W8 F
A0A0P6VSR8 F
A0A1B9MBX6 F
A0A328EMN2 F
A3ZZL7 F
B0CXH8 F
D5AU98 F
L7CG11 F
A0A3E2TW06 F
D4F313 F
R1D1H4 F
U3PCH5 L
A0A127JTU2 F
A0A7S0ILH2 F
V4RK08 F
A0A2N6NEK4 F
A0A2R4MBA2 F
F0ZPL3 Y
G0EFF3 F
G2ZN72 F
Q6BK68 F
A0A0S2DQB6 F
A0A1G6ABX1 F
A0A2S8QA29 F
A7SGD4 L
M1V7W3 F
D5EP71 F
L1IYW7 F
A0A075WEB4 F
A0AA94HTL8 F
B8IZX4 F
C7NND3 F
D3FBG3 F
D5ELM4 F
M9YAI9 F
Q07UM1 F
Q4WT12 F
Q9BLG3 F
A0A242NIL1 F
A0A6J5IRX5 F
A0A836M2B6 F
A0A9W5JBA9 F
L0K9M1 F
Q3Z7F9 F
W0F0I7 F
A0A6G9Y3Q0 F
G7WCB6 F
G7WFX4 F
K9YR86 F
Q7S5K0 F
Q9NIV0 F
A0A0V8M0W6 F
B4CV94 F
B7FSA7 F
F6FRU9 F
A0A1S8D478 F
A0A1W9KSU5 F
A0A2M9D7S8 F
A0A2S8F4W0 F
I4D6Z9 F
L0KW14 F
A0A212AV03 F
A0A9Y2AG30 F
A3U857 F
B4HDZ9 F
B9L7N1 F
J9Z839 F
U1PPI7 F
A0A059XXR1 F
A0A067Z3S3 F
A0A0A2A0Y9 F
A0A178TA08 F
A0A7S0KKL8 F
Q466Y3 F
A0A076PL76 F
A0A243SC06 F
B0DY50 F
G2T1Y3 F
A0A0U1NJW3 F
A0A264VQM8 F
A0A2S5YID7 F
A0A8G2IZM3 F
E4NS62 F
Q1H0G2 F
A0A0A2ZRL7 F
A0A149QSR6 F
A8ZQD5 F
I8TC71 F
K2JVF8 F
B3DUX7 F
I2GD40 F
K5CFE5 F
Q6ND36 F
A0A366IE34 F
A6XBM2 F
C3X1J1 F
F7ZEU9 F
G0IYI2 F
G0JRH4 F
Q2YLQ6 F
A0A4P8HC89 F
A0A5J6WQU1 F
A0A8E2R1Y5 F
A5D4I5 F
B1XZU2 F
B1Y6V4 F
C8XBX8 F
F0YLV7 F
Q0G2T1 F
A0A034WGQ2 F
A0KPE9 F
K9P5D1 F
Q6BT62 F
A0A0L0TDW1 F
A0A165MAC2 F
A0A1B9KID3 F
A0AA91Q161 F
I0HGY4 F
A0A6H9GEE4 F
A0A979GQ79 F
C6LBD3 F
F3QPR6 F
F3ZVV4 F
F6BEI0 F
A0A140NHJ5 F
A0A653N397 F
A0AA35XZV0 F
A7NKH2 F
B8JBH5 F
D3PAH1 F
Q0VPH4 F
W0E077 F
A0A074KY88 F
A0A0S4WFM4 F
A0A495DND0 F
B7FTM9 F
A0A423Y4I6 F
A0A4U1JNL6 F
A0A6T9XUR2 F
A0A9P3CXY2 F
A2BUP4 F
A4CMI3 F
R4FZE3 F
U2WTW8 F
A0A1B9BUU6 F
A9BIZ7 F
B7FW68 F
D8PD01 F
K9Z0D3 F
W7QGE0 F
A0A381CAY8 F
B1Y8C9 F
C6CBB1 F
K8W1E2 F
Q21P82 F
A0A0H3LUA3 F
A0A2S8GEJ5 F
A0A315S845 F
I0JI83 F
Q7TNN9 F
A0A149UP06 F
A0A369MRW6 F
E0SD83 F
F3QNA7 F
A0A0D7F2Y9 F
A0A0S2FHD7 F
A2CCK1 F
Q0G0A4 F
R1EGK6 F
R9GM11 F
A0A202B535 F
A0A854QN45 F
A0A8H6K7L7 F
C1F584 F
I3R0S7 F
A0A1I4W3A0 F
A0A1J5JH24 F
A0A2H4U5R1 F
A0A6P4JM51 F
B8FL88 F
C8WLL8 F
Q0VLH1 F
A0A081N2G5 F
A0A378YR15 F
D9QPE5 F
E6ME92 F
F3ZYD6 F
G0JRG9 F
K8EJ02 F
A0A290XBB5 F
A0A2A2MCP3 F
A0A2I0UUY1 F
A0A5C5TYS5 F
B1Y0E5 F
D0MFE8 F
A0A2G6JLT9 F
A0A510HHK8 F
A0A5C4RNH5 F
C5BWX7 F
D5E995 F
A0A0B4DUR9 F
A0A1V2XMU9 F
A0A1Y6GLJ1 F
A0A2S0Q8P1 F
A0A369N7Y3 F
A0A1Y3U5V2 F
F2JZ83 F
G8JTW0 F
Q0ACK1 F
A0A1Y5E8I7 F
A0A4R7GKA0 F
D5ASL9 F
E8RLT5 F
L0JT30 F
A0A068NPW2 F
A0A149RYW7 F
A0A1B9BUZ8 F
A0A3N1VXY4 F
B0SRS8 F
C7Q1E4 F
A0A144NLT9 F
A2SS52 F
F5Y3C1 F
A0A149V596 F
F0J6E8 F
A0A0K2STK6 F
A0A366XFS8 F
A0A418VIJ8 F
M9RJS5 F
W8KM07 F
A0A0E3R4G0 F
A0A3G9G4Q4 F
F5L8M7 F
H1XV27 F
M0D3Q9 F
Q22947 F
A0A4Q2QWS1 F
H2CLF7 F
Q608B6 F
A0A1X4GBG2 F
A0A4P6UIK6 F
A0A857DMN9 F
E4TJ50 F
F0J7D3 F
Q8JI14 F
A0A1Y0V4A5 F
I0ICG0 F
Q3AFY9 F
A0A0A2AMW2 F
H2IZ00 F
K5DBA0 F
A0A149QAW7 F
A0A2K3DPU7 F
I7ZHW3 F
U1SIR9 F
U1H1F7 F
A0A399T909 F
A9UR54 F
E4N1T5 F
G7WFX2 F
H1YF74 F
R8VWI7 F

In [48]:
df2 = pd.DataFrame(ididid)

In [49]:
df2['54'] = seqff

In [50]:
df2['135'] = seqotf

In [51]:
df2['merged'] = df2[0] + ' ' + df2['54'].astype(str) + df2['135'].astype(str)

In [52]:
fullff = df2['merged'].to_list()

In [84]:
df2

               0   54  135         merged
0     A0A1X4G8K1  (F)  (F)  A0A1X4G8K1 FF
1     A0A2X2C038  (F)  (F)  A0A2X2C038 FF
2         L8H844  (F)  (F)      L8H844 FF
3     A0A066ZRQ5  (F)  (F)  A0A066ZRQ5 FF
4     A0A075JIN0  (F)  (F)  A0A075JIN0 FF
...          ...  ...  ...            ...
1276      A9UR54  (F)  (F)      A9UR54 FF
1277      E4N1T5  (F)  (F)      E4N1T5 FF
1278      G7WFX2  (F)  (F)      G7WFX2 FF
1279      H1YF74  (F)  (F)      H1YF74 FF
1280      R8VWI7  (F)  (F)      R8VWI7 FF

[1281 rows x 4 columns]

In [53]:
right = []

for u in fullff:
    right.append(u.split(' ')[1])

In [54]:
rightset = set(right)

In [55]:
rightset

{'FF', 'FL', 'FM', 'LL', 'MF', 'VF', 'YF', 'YY'}

In [56]:
idff = [] 

for y in fullff:
    if y.split(' ')[1] == 'FF':
        idff.append(y.split(' ')[0])

In [57]:
len(idff)

1272

In [58]:
len(fullff)

1281

In [59]:
aligne = AlignIO.read("concat510HHali.fasta", "fasta")

print("Number of rows: %i" % len(alignment))


for record in aligne:

    print("%s - %s" % (record.seq, record.id))

Number of rows: 1281
-------------EGSLDFAGGTVVHINASVAGLIGAYLLK-NR-I--------G--Y-------DD-----TCDVFGVHGVCGIVG-CL-LTGIFT----AE-------SLG---------G----------- - A0A1B9JPL5
-------------DGALDFAGGTVVHINAAIAGLVGAYLLG-KR-A--------G--F-------DD-----TCDVFGVHGVCGIVG-CL-ATGILT----AT-------SL---------------------- - A0A377PLP5
-----YSLGD---LGFSDFAGSGIVHMAGAAAALSGVLLLG-AR-L--------G-----------D-----PVGAISVHGVVGLFG-LL-IVPLTN----PA------AS----------------------- - Q1Q879
-------------LGALDYAGGGPVHICSGHGALMYALILG-KR-N--------R--I-------DD-----GLDVYALHGVGGCIG-SV-LTGIFA----AD-------YINA-------------------- - Q6CRN0
-------------LNAKDAGGSMVIHTFGAYYGLSISRVL--YR-P--------NL----N------------CGIHNLHAMPGVIG-GI--VGAIS------------AAAASKE----VYG----------- - Q8JI14
-------------KGALDFAGGTVVHINAAIAGLVGSYVIG-KR-V--------G--F-------DD-----ALDVFGVHGVGGILG-AL-LTGVFA----AP-------SLG---------G----------- - A0A127PIQ9
-------------KGTRDFAGGIVVHETAALAALLLAVMIG-PR-R--------N----------DD-----SLDVFAVHGVGGIFG-TI-MVAVYG----AA-------SFT---------AQ---------- - A0A1G7H8X3
-------------AGYLDFAGATVVHMCGGVAGLVAAKMVG-AR-K--------G--L-----KVDD-----VCGVFAVHGVAGAVG-TA-LIPVFA----V----------GGFS------ASQ--------- - A0A482TED1
-------------LGAWDFAGGTVVHINSGIAAVVAALVLG-AR-K--------D----------DD-----SLDVFAAHGVGGITG-AI-LTGVFA----QK-------SVN--------------------- - D3PKL4
------------------AYASGVIHAIAGGFALGILIVLG-PR-L--------GK-F-----KIDD-----AVGAVAVHGYAGFIG-VV-IAGFML----WG-----QPS----------------------- - Q0G2T1
------------------FAGGTVVHINAGIAGLVACLVIG-KR-R--------GYGY-------DD-----SLDVFGVHAIAGIIG-AL-LTGPLA----SP------------------------------- - A0A0G9HEC5
-------------YGVMDYAGGGPVEIGSGMAALAYSMVLG-RR-Q-------------------ER---------FAEHGVAGIVG-LL-FNALFG----DD------AIVG-------LDGVNT-------- - A1C5Z7
-------------MGFIDFAGSTVVHSVGGWAALAAAIVLG-PR-I--------G-----------D-----PVGAVSVHGVNGAWG-TL-AAGIFN----AE------KLFD--------------------- - E3H8C9
-------------SGALDFAGGTVVHINAAVAGLVGAYMVG-KR-I--------G----------DD-----SLDVFGVHGVGGIVG-AL-LTGVFN----SP-------AL---------------------- - Q221S8
-------------DGALDFAGGTVVHINAAVAGLVGAYLLG-KR-T--------G--F-------DD-----VCDVFGIHGVCGIVG-CL-LTGVFT----AK-------SLG---------G----------- - Q7N0M6
--------------GVLDFAGGTVVHMSAGWAALAGAIFLG-KR-K--------V----------QD-----ALDVFACHGVGGMVG-ML-LTGVFA----SK-------SIN--------------------- - A0A243SC06
-------------KGALDFAGGTVVHINAGIAGLVGCLMIG-KR-I------------------------------FGVHGIGGIIG-AL-GTGIVA----SP-------SLG---------GTGVWDYVAN-- - A0A2S6H643
-------------MGALDFAGGTVVHINSGVSALAIALVLG-KR-K--------D--I-------DD-----ALDVFGIHGMSGIWG-AI-ATGIFA----AP-------YINE-------AAG---------- - B9ACS5
------------------FAGGNVVHISSGFSGLVLALIIG-KR-R--------G--Y-LG---YDD-----ALDAFGCHGIGGIWG-GI-ATGLFA----SR-------SVN--------------------- - E6ME92
--------FQ---MGGLDFAGGTPVHISSGAAALAYSLMLG-KR------------------------------DIFAEHGVGGIVG-NL-LTGLFA----AD-------YIAR------LDGS---------- - Q2GX26
--------------GFSDFAGSGIVHMAGAAAALAAVILLG-AR-K--------G---------LDD-----PVGALSVHGVCGLFG-LL-VVPLNN----EG------A------------------------ - A1SZ12
--------RT---MGALDFAGGTVVHITSGVSALVCALVLG-KR-T--------G--Y--R---VDD-----SLDVFGVHGVGGIIG-AI-ATGIFA----TK-------SIN--------------------- - E1IF27
-------------IGFSDFAGSTAVHSVGAYAAFAGAFMVG-PR-I--------G-------LRVDD-----VVGAVSLHGCSGIIG-TL-LAGFLS----RD------A------------------------ - G7WDB5
-------------PDVIDLAGGTVIHINAGAAALALALVAG-KR-I-----------------GFDD-----SLDVVGLHLVAGVIG-SL-YLGFFA----FS------DGLF--------------------- - A0A1H1BPD6
-------------MGALDFAGGAVVHMSSGAAALACAQALG-PR-L--------S--T-------DD-----ALDVVGIHGVGGTWG-AL-ATGLFA----CA-------AIN---------NTDGLF------ - A0A4P7UHQ5
-------------DGALDFAGGTVVHINAAVAGLVGAYLLG-KR-A--------G--F-------DD-----PCDVFGVHGVCGIVG-CI-LTGVFS----SA-------SL---------------------- - A0A7V8IKS6
-------------AAFHDYAGSMVVHGMGGWIAIAAVLLLG-PR-H--------G----------DD-----VLGVWSLHGVCGLWG-AL-AAGIFG----LK------ALGG--------------------- - D0KXQ0
--------------GVLDFAGGTVVHMSAGWAALASALYLK-QR-N--------E----------DD-----TLDVFPCHGVGGMVG-ML-LTGVFA----NT-------NVN--------------------- - H1YCC3
-----------------DFGCSAVVHGVSGFFALGVLINLG-PR-I--------GR-Y--------D-----AVGAFAVHGYCGLLG-AM-AVGVMA----TGYQIGNYPA----------------------- - K9Z0D3
-------LAH---KGVIDFAGGTVVHINAGIAGLVGAYFLG-KR-L--------G--Y-------DD-----TADVFGVHAVGGIVG-AL-LTGVFS----AQ-------SLG---------G----------- - A0A5C5TYS5
-------------WGVLDFAGGGPVEIGSGIGGLAYSWVLG-RR-H-------------------ERMRIDDALDLFAEHAVGGMIG-LI-LNAFFA----SS------SI----------------------- - B0CQX4
-------------IPFHDYAGSLMVHGVGGFLALGLIAAIG-PR-F--------G-----------D-----VCGVIPVHATSGALG-AI-LAGIFG----MT------AFGGVG-------G----------- - G0H0Z6
-------------LGYHDAYASGVIHAIAGGFALGVLVVLG-PR-I--------GK-F-----KIDD-----AVGAVAVHGYAGFLG-VV-IAGFML----WG-----QPS----------------------- - V4RHR4
--------------GTLDFAGGTVVHINAGVTALVLSIYLG-KR-L--------N--F-------DD-----TLDAFGCHGVSGMVG-SI-MTGLFA----TK-------AVNS-------------------- - A0A087EQK8
-------------WGVLDFAGGGPVEIGSGVAGLAYSWVLG-RR-N-------------------ER-------DLFAEHAVGGIIG-LM-LNAFFA----SP------SIIA-------MDDV---------- - A0A0D2LEF5
-------------------AGSGPVHLIGGASAFASAAMLG-PR-L--------GR-Y-----S-ED-----PVGASAVHGVCGIWG-VI-AVGLFA----DN------PIP---------------------- - B3MX93
--APNGFLYT---MGVIDVAGTGAVHLCGASCGLVATLLLK-PR-I--------G---------IDD-----PVGAVPVHGFAAIWG-ML-AVGLFA----LN------DGLE--------------------- - C3YB74
--------------GFHDFAGGMIVHGMGGIAGLTAAWIIG-PR-M--------N----------DD-----VCAVFPVHGSAGVLG-TL-LYPVFA----VP-------VWH---------E----------- - B8ZYW3
--------------GAVDFAGGNVIHISSGVSGLIACIFLG-TR-K--------G--YGFG---YDD-----ALDAFGCHGIGGIWG-GI-ATGLFA----QS-------AIN--------------------- - H6LKH6
-------------LGVRDAGGSMTIHTFGAYFGLVLSRVL--YR-P--------QL----E---------------HNLHGMPGVLG-AL--LGVLV------------AGLATHE----AYG-DGL------- - Q9H310
---GLQETFG---VGVIDFAGGTAVHICAGAAALALALVLG-RR-V--------G----------DD-----SLDVVGIHLVGGLIG-TL-YLGFFA----NG------TGLF--------L------------ - A0A2S5WV24
------------------FAGGDVVHISSGLTGLILCLMLG-RR-K--------G--FLG----YDD-----ALDAFGCHCVGGIVG-GI-LTGLFC----VP-------GLS---------WTEHG------- - A0A369NYJ2
-------------------AGGTVVHINAGVAGLVCALVLG-RR-K--------G--Y-------DD-----SLDAFGVHGVGGIVG-AL-LTGLFA----YG-------PLS---------A----------- - A0A401X433
-------------NNFRDFAGSTVVHSVGGWAALAGILFLG-PR-L--------G-----------D-----PVGAIPVHLGNGIWG-TL-ALGLFY----NN------DIAT--------------------- - A0A833LX85
-------------LGALDFAGGTVIHITSGWSGLVIALMLG-RR-L--------G--Y-------DD-----ALDTWGVHGIGGLAG-AL-LTGILA----EK-------RFT--------------------- - A0A977NL43
-------------FGFHDVGAAGCVHLIAGAFTLGILLNLG-PR-H--------G-----------D-----AVGAVAVHGFGGAWG-VL-AMGLFA----SG-----YPNVDG-------------------- - V4RK08
-------------VGAIDFAGGTAVHINAGAAALALSLVLG-KR-V--------G--------GFDD-----SLDVVGIHLIGGLIG-TL-YIGLFA----TD------V------------------------ - A0A251XU71
-------------YGAIDFAGGTVVHINAGIAGLVGAIMLG-KR-T--------G----------DD-----SLDVFGVHCIGGIIG-AL-GTGILV----NP-------ALG--------------------- - A0A8G2IZM3
-------------MGVLDFAGGAVVHVNSGVAGLVAALFLG-RR-K--------G----------DD-----SLDAFGIHGAGGALG-AV-LTGVFA----DP-------AIN--------------------- - A0A3G9G4Q4
-------------APFHDFAGSVVVHAMGGWMALMAVWLLG-PR-K--------G----------DD-----VLGVWPMHGVCGVWG-GL-AVGIFG----HQ------FLG---------------------- - G0JRQ3
-------------DGVLDYAGGTVIHINAGVAGLCAALFIG-KR-I--------G--Y-------DD-----SLDAFGIHGIGGIVG-AV-LTGVFV----ST-------DIT--------------------- - A0A0A2ZRL7
------TEEG---GAALDFAGGTVVHINAGIAALMAAIVLG-PR-K--------GYGY-------DD-----SLDVWGVHGVAGIVG-AI-LTGVFA----AP-------ILG--------------------- - D3RMV7
-------------HGALDFAGGTVVHINAAVAGLVGAYLVG-KR-L--------G--Y-------DD-----SLDVFGVHGVCGILG-AL-LTGVFA----SP-------DLG--------------------- - K1K628
-------------GEALDFAGGTVVHITSGVSSLAILTYLG-KR-R--------GFGY-------DD-----SLDAFGVHGVGGIVG-AL-LVGVFA-------------SVG---------GTGLL------- - Q46G49
-------------WGALDFAGGTVVHINAAVAGLVGAYVIG-KR-I--------G--F-------DD-----SLDVFGVHGVGGIVG-AL-LTGVFN----TQ-------AL---------------------- - A0A370FPU0
-------------ATFHDFAGSTVVHSVGGWISLVGAAILG-PR-I--------G----------DD-----PVGASSVHGVCGFLG-TL-LTGLFS----TS------EG----------------------- - A0A5M5PZE2
--AENGWLAT---LGAVDIAGCGVVHVVGGVTGLVATIILK-PR-I--------G-----------D-----PTGCLAAHILSGIWG-LV-SVGFFT----EV------DNL---------------------- - A7RNC3
-------LEG---LGFIDFAGSTVVHSVGGWAALAGAIVLG-PR-I--------G----------DD-----PVGAISVHGVCGAWG-TL-MAGVLD----IN------GF----------------------- - I6Z905
--------------GYLDFAGSGVVHVLGGIAAFVAAFFLG-PR-K--------GR------LWIDD-----PLDAVAVHFGGGSWG-VI-AVAFLH----KE------RG----------------------- - V4AP67
-------------VLFHDFAGGMIVHGMGGIAGLTAAWVLG-PR-M--------D--L-----KIDD-----VCAVFPVHGSAGVLG-TL-LFPFVA----AP-------GVV--------------------- - L0JT30
-------------DGALDFAGGTVVHINAGVSGLVLAYLLG-KR-R--------G--W-------DD-----ALDAFGIHGVGGIVG-AI-GTAIVY----QP-------FLG--------------------- - A0A074ME37
--------------GSYDFAGGTPVHISSGTAALAYSVMLG-KR------------------------------DIFAEHGVGGIVG-NL-LTAFFA----AD-------YIGA------LDGV---------- - A0A0E9NHV4
--------------GFSDFAGSGIVHMAGASAALAGVLMLG-AR-K--------GI---------DD-----PVGAISVHGVVGIWG-LL-AVPLNN----AD------AT----------------------- - A0A7R6PER3
-----------------DAGGSMVIHCFGGYYGLAISWML--YR-P--------NL----H----QD-----TCGVHNLHAVPGMLG-GF--IGAIV------------AAAASTE----VY------------ - A6XBM2
-----------------DLAGSTLVHSVGGWAALAGVMILG-PR-I--------G-----------D-----PVGALSVHLVNGVWG-TL-AVGIFD----IT------GD----------------------- - C9RS76
----------------LDFAGGTVVHINAAIAGLVGAYLIG-KR-V-------------------DD-----PCDVFGVHGVCGIVG-CI-MTGIFA----AS-------SLG--------------------- - P69681
-------------MGFMDFAGSTVVHSVGGWVALAGVIVLG-AR-R--------G--------RLDD-----PVGAIAAHGFGGVWG-TL-ALALFA----PA------DQLAT-------------------- - W0E077
--------------GFSDFAGSTLVHAAGGFAALAGALVLG-AR-I--------G-------LKIDD-----VVGAIPVHLIAGFWG-TM-VVPVYT----AD------TS----------------------- - A0A0U1NJW3
-------------LGFKDFAGSTVVHSVGGWSALTGAAILG-PR-M--------G-----------D-----PVGATSVHLVCGVFG-TL-AVGIFN----KD------AGL---------------------- - A0A6H9GEE4
-------------------GGAGPVHLLGGVCSLVATLILG-PR-H--------GR-L-----RIDD-----PVGCFPVHGLCSVWA-IL-AVGIFG----HV------DAL---------------------- - C3YB73
------------------FAGGNVVHISSGYSALIAALILG-KR-K--------G--L-FG---YDD-----ALDAFGCHGIGGTWG-AL-ATGIFA----TT-------SIN--------------------- - G7WCB6
--------LK---LGALDFAGGTVVHINAGVAGLACCIVLG-KR-K--------G----------DD-----SLDVVGVHAVGGIWG-AL-ATGLFA----SK-------AIN---------AAGN-------- - I4C9L0
------------------FAGSSIVHSVGAWAGLVGAMLLG-PR-I--------GK------YSDGD-----PVGAFSVHGVCGVWG-TV-VIGLWG----TA------VQGDG-------------------- - A0A0A2A0Y9
-----------------DLAGSTVIHSTGGWALLAAILIIG-AR-R--------GR-Y-------PD-----PVGALSVHLLNGIWG-TL-AVGIFA----SN------GDN---------------------- - D5V7B3
-------------MGALDFAGGAVVHMSSGAAALACAQALG-PR-I--------S--T-------DD-----ALDVVGIHGLGGTWG-AL-ATGLFA----SA-------AVN---------GVDGLF------ - A0AA94HTL8
-------------DGMQDFAGSTVVHLTGATGGLAALLLLG-PR-R--------G-----------------PVGALSAHGVAGVWG-TL-SCGLFA----AP------RLVDAP-------GV---------- - D3F545
-----------------DYSGGYVIHVAAGISGFVAAAVIG-PR-L------FAD----RV--KIDD-----TLGVLHTHAVAGAVG-GL-MVGLLG----DP-------RM---------------------- - G0JRG6
-------------VGYLDFAGATVVHMVGGLAGLVGAKMVG-PR-K-------------------TD-----VCGVFVVHGSAGAIG-TI-LIPVFG----VT-------AAGGYT----FLGVNQ-------- - U1PPI7
-------------LGLHDYAGGTAVHMNAGASAVALALVLG-RR-K--------N----------DD-----ALDAFSVHGIGGIVG-AL-FVVFLGAAA-AP------AGIA--------------------- - A0A2S5WGI8
-------------DGALDFAGGTVVHINAGIAGLVGAYMVG-KR-I--------G--F-------DD-----AFDVFGVHGVGGIVG-AI-LTGVFA----AQ-------GLG---------G----------- - A0A420KGW4
-------LEK---LGFIDFAGSTVVHSIGGWLALAGAIMVG-PR-I--------G----------DD-----PVGAISVHGVCGALG-TI-FVGFFA----VD------GGLF--------------------- - H1XV27
-------------LGFADFAGSTVVHSVGAWIALAGAIVVG-PR-L--------G----------DD-----PVGCVSVHGTCGAFG-TL-CVGLLA----AP------GYGG--------------------- - C8WZE0
-------------LGFIDFAGSSIVHSVGGWAGLVGAMLLG-PR-I--------G-----------D-----PVGAFSVHGVCGVWG-TV-VIGLWG----VD------GMDP--------------------- - Q46HB1
--------GG--GYGALDFAGSGVVHALGGYIALAAVMLLG-PR-L--------G-----------D-----VVGAIPVHGFSGTWG-LI-ALGIFA----DG------SYG------L--Y------------ - A0A075WG29
-------------LGALDFAGGTVVHINSGVAALALILLLG-KR-K--------D--T-------DD-----ALDVFGIHGMSGLWG-AL-ATGLFA----AP-------FINE-------LGT---------- - A0A089ZBW5
-------LDQ---LGYLDFAGSGIVHLAGAAAALAAVLVLG-PR-K--------G-----------D-----PVGAISVHGVVGIWG-VL-AVLLSN----DQ------AT----------------------- - A0A3E0X011
--------RS---LGALDFAGGTVVHISAGVTAVVLAVVLG-PR-R--------D----------DD-----TLDVFACHGVAGIMG-AV-LTGVFA----SK-------EVN--------------------- - C1A872
--------GDK-SLAYHDFAGSGVVHMVGGFSGLMGAIMVG-PR-T--------G-----------D-----PLEAFPVHGACGMWG-VL-AVGLFA----KE------KYL---------------------- - C1N5A7
-------------KGFVDFAGSVVVHSVGGLAGLAGAIALG-PR-I--------G-----------D-----PVGAFPVHGICGMWA-GV-ATGIFG----DL------AEG---------------------- - D2R647
-------------MGAIDFAGGTVVHISSGVTGLVLALLIG-HR-H--------N--D-------DD-----TLDAFGIHGIGGAVG-AI-LTGVFA----DK-------NI---------------------- - D5T4N9
-------------VPFYDFAGSTIVHSVGGWGALVGACLLG-PR-L--------G-----------D-----PVGAISVHLVGGIWG-TL-AVGLFG----NL------ASFQQ-------------------- - U5C2K4
-------------LGFHDFAGSCAVHMVGGTAAFIGAKILG-PR-I--------G----------DD-----PVGAVGVHGLCGLTG-TL-LTGVFA----YY------LTDDL-------------------- - R8VWI7
-------------MGMQDFAGSTVVHLQGAIAALVATILLG-PR-I--------GK----------D-----PIYAFSVHGIAGIIG-TI-STGFFA----SP------RLVEIT-------G----------- - A0A0D8BQX6
---------------FQDFAGSTLVHSVGGWAALAGALLLG-AR-N--------G-----------D-----VVGAIPVHLIAGIWG-TL-AVPLTN----SD------AS----------------------- - A0A1H4KAQ7
-------------DGALDFAGGTVVHINAAVAGLVGALLLG-KR-V--------G--F-------DD-----PCDVFGVHGVCGVVG-CL-LTGVFT----AA-------SL---------------------- - E0SD83
-------------PEALDFAGGVVVHIASGFSALMLALLLG-RR-R--------T----------DE-----TLDAWAVHGMSGLWG-SI-AAGIFA----NP-------AVS--------------------- - G0EFF3
-------LDH---LGFLDFAGSGVVHLCGASAALAGVLLLG-PR-L--------G-----------D-----PVGAISVHGVSGIWG-LL-AVTITN----PE------AS----------------------- - Q6ARH0
------------------FAGGDVVHISSGVSGLVACIVLG-KR-R--------------G---YDD-----ALDAFGCHGIGGVWG-GI-ATGLFG----QT-------AIN--------------------- - A6M3G0
-------------LGALDFAGGTVVHMASGFSALTACVICG-PR-H-----------Y------VDD-----SLDVFLCHGVGGMLG-AF-LLGWFA----SL-------EVN--------------------- - L8GFX3
--------------GALDFAGGTVVHISSGISALVAALLIG-PR-M--------G--Y-------DD-----ALDAFGVHGIGGTLG-AV-LTGVFA----TR-------AAW---------DVSGG------- - M5SY07
-------------HGALDFAGGTVVHINAAVAGLVGAYLVG-KR-V--------G--F-------DD-----PCDVFGVHGVCGIIG-CI-MTGIFA----AT-------SLG---------GVGYAEG----- - S3K1S2
-------------KGALDFAGGTVVHINAGVAGLVGAYVLG-KR-L--------G----------DD-----ALDVFGVHGVGGIVG-AL-LTGVFA----AP-------SLG---------GTGVY------- - A0A016XCG9
-----------------DYSGGYVIHLSSGIAGLTTAFWVG-PR-S------SN--------------------DVFHTHAVAGLLG-GV-LTGLFA----EP-------ELCALFLP-VTKSRG--------- - A0A2K1RA81
-------------AGALDFAGGTVVHINSGVAGLVAAYMLG-KR-I--------G----------DD-----ALDAFGLHAVGGIVG-AI-LTGVFY----SD-------EII--------------------- - A0A6F8TLE9
---SNGWSFV---LGGLDFAGGTPVHISSGMAGLAISIYLG-------------G--F-------DD-----TLDIFASHAVGGIVG-NI-LTAFFA----QA-------SVA--------------------- - B0DFJ4
-------------LGVLDFAGGLVVHLNCGVAALVAAIVVG-KR-K--------G----------DD-----SLDVVGIHGVGGVWG-TL-ATGLFA----SK-------LIN--------------------- - I4C9L2
-------------WGVLDFAGGTAVHISAGVTSFVGAMVLG-KR-K--------G--W-------DD-----ALDVFSVHGIGGVVG-CI-LTAIFC----IP-------SLG---------GNIED------- - A0A9Q8L398
--------------DMVDFAGSTVVHSVGGWAALMGTMVLG-PR-T--------G-----------D-----PVGAISVHGVGGAFG-TL-MVGIFA----VD------GGLL--------------------- - A9BIZ7
-------------KGFLDFAGSTVVHSIGGWAALAGILVLG-PR-L--------G-----------D-----PVGATAVHLANGVFG-TI-ALGLFA----DP------TVA---------------------- - B8J5X4
-------------TGFVDFAGSTVVHSIGGWVALAAVIIIG-PR-I--------G-------LKLDD-----AISAIPVHLFAGIWG-TL-AVAFFA----DL------DVL---------------------- - W7QGM4
-------------AAFHDFAGSVVVHAVGGWIALAAVLILG-VR-K--------G----------DD-----VLGVWPLHGVCGMWG-GL-AAGIFG----LE------ALGG--------------------- - A0A2N7L7C8
-------------HGALDFAGGTVVHINAAVAGLVGAYLIG-KR-V--------G--F-------DD-----PCDVFGVHGVCGIIG-CI-MTGIFA----AQ-------SLG---------G----------- - A0A7H8UK07
--GPGGAMAA---AGVLDFAGGIVVHITAGIGALVGAAVLG-PR-K--------E----------DD-----SLDVFGVHGVGGFIG-TC-LLGIVA----AP-------ALG---------GFNFE------- - A0A7S0D560
-----------------DFAGGTVVHISSGVTALVAALYLG-AR-R--------G--Y------PDD-----SLDAFGVHGVGGIVG-AL-FLTFFI----RPSWM----AEA---------A----------- - B3QRJ4
-------------LGALDFAGGAVIHISSGAAALVCAIVLG-KR-R--------G----------DD-----SLDVVGIHGVGGVIG-IL-ATGLFA----SK-------VVN--------------------- - D8PD01
-----------------DFAGGTVVHINAGVAGLVGAYVVG-RR-I--------G--YLR----ADD-----ALDVFGVHGVGGIVG-AL-LTGVFN----AK-------VL---------------------- - Q7W7D3
-------------AAFHDFAGSVVVHASGGWMALAAVLLLG-PR-R--------G----------DD-----VLGVWPLHGLCGVWG-GL-ACGIFG----QT------ALGGLG-------G----------- - A0A248LNW8
-------------VAPIDFAGGTVVHINAGVAALVLAILIG-KR-K--------G--F-------DD-----SLDVVGVHLVSGLWG-TV-AIGFLA----TD------TGLF--------FGGGVQQ------ - A0A4Y4DZN4
-----YTLGD---LGFSDFAGSGIVHMAGAAAALAGVLVLG-AR-K--------GI---------DD-----PVGAISVHGVVGLLG-LL-LVPVTN----DG------SS----------------------- - A0A7U8C744
--------FK---LGVLDFAGGTVVHMSAGWAALAGAIYLK-RR-R--------S----------DD-----TLDVFPCHGVGGMVG-MI-LTGVFA----TS-------SVN---------E----------- - E4RTK5
-------------AGFWDFAGSTVVHSVGGWAALMGAAFLG-PR-I--------G-----------D-----PVGATSVHLVCGIFG-TL-CVGLFA----EG------PGG---------------------- - K9U8C7
-------------KGALDFAGGTVVHINAAVAGLVGAFLFG-KR-I--------G--F-------DD-----TLDVFGVHGVGGILG-AL-LTGVFA----SP-------SLG--------------------- - G3A431
-------------LGMQDFAGSTVVHLSGAMAALAGTLLLG-PR-L--------G-----------D-----PLGAIAAHGMGGVWG-TL-SAGLFT----TP------ELAA--------------------- - Q1AUG3
-------------VGYLDFAGATVVHMVGGLAGLVGAKMVG-PR-K-------------------TD-----VCGVFVVHGSAGAIG-TI-LIPVFG----VT-------TAGGYT----FLGVNQ-------- - U1PIR6
-------------LGVFDFAGGIVIHTSAGMASLAAALILG-RR-K--------N----------DD-----ALDVSSVHGVTGIVG-SL-AIGILA----TQ-------VVN--------------------- - A0A060HN92
-------------MGVLDFAGGIVVHATAGFAALASVFYVG-SR-K--------Y--N-------DD-----ALDVWGVHGIGGVTG-TI-LLGVFA----ST-------AIN---------PVGA-------- - A0A0E3R6S1
-------------EGALDFAGGTVVHINAAIAGIVGAYLIK-NR-L--------G--Y-------DD-----TCDVFGVHGVCGIVG-CI-LTGIFA----SK-------SLG--------------------- - A0A1B9LFW3
-------------KGALDFAGGTVVHINAAVAGLVGAFMVG-KR-I--------G---LG----ADD-----ALDVFGIHGIGGILG-AL-LTGVFN----SW-------SM---------------------- - D9SI59
-------------MGFFDFAGSTIVHSTGGWIALVGTMFLG-P------------R-Y-------GD-----PVGAIPVHAFNGAFG-TL-AVGVWG----QK------ALG---------------------- - E1QIU3
-------------MGVLDFAGGAVVHVNSGVAGLVAALFLG-RR-K--------G----------DD-----SLDAFGIHGAGGALG-AI-LTGVFA----DP-------AIN--------------------- - E8RSE4
-------------AGVLDFAGGLVVHLNAGIAGLVCALVLG-RR-E--------G----------DD-----SLDVFGVHGVSGIVG-SV-LVGVFA----TR-------AVNDV------E------------ - A0A1T4SFK4
-----------------DYSGGYVIHLSAGVAGFIGAAVIG-PR-L------ARD----RE---------------FHTHAVAGLLG-GV-MTGLLA----TK-------AGCAAFAL-STPGGAI-------- - A0A257T7G4
-PVKSGLIWG---FGALDFAGGTVVHINAGIAALVGALVLG-KR-Q--------G--F-------DD-----SLDAFGIHGVGGIVG-AI-ATGLLV----NP-------AWG---------GAGV-------- - A0A2W5VAZ2
--------AK---LGVLDFAGGLVVHATCGAAALASVLVIG-PR-R-------GK--F-------DD-----SLDVVGIHGVGGVSG-TL-LLGVFA----SK-------SVN--------------------- - A0A7U4DN04
-TGKAGYIWQ---TGALDFAGGTVVHINAAVAGLVGAFMVG-KR-I--------G----------DD-----SLDVFGVHGVGGIVG-AL-LTGVFN----SP-------AL---------------------- - A1VIG8
-------------MGFIDFAGSTVVHSVGGWLALAGAIVVG-PR-L--------G-----------D-----PVGAVSVHGVCGAWG-TL-AAGLFD----SA------GF----------------------- - Q1K3N8
-------------KGAIDFAGGTVVHINAGIAGLVGALLIG-KR-T--------G----------DD-----SLDVFGVHCIGGIVG-AL-GTGILV----NP-------ALG---------GAGIIDYTAI-- - Q89WR5

In [60]:
ts = aligne[:, 25:26]

In [61]:
et = aligne[:, 79:80]

In [62]:
tsid = []
seqts = []

for i in ts:
    print(i.id, i.seq)
    tsid.append(i.id)
    seqts.append(i.seq)

A0A1B9JPL5 H
A0A377PLP5 H
Q1Q879 H
Q6CRN0 H
Q8JI14 H
A0A127PIQ9 H
A0A1G7H8X3 H
A0A482TED1 H
D3PKL4 H
Q0G2T1 H
A0A0G9HEC5 H
A1C5Z7 E
E3H8C9 H
Q221S8 H
Q7N0M6 H
A0A243SC06 H
A0A2S6H643 H
B9ACS5 H
E6ME92 H
Q2GX26 H
A1SZ12 H
E1IF27 H
G7WDB5 H
A0A1H1BPD6 H
A0A4P7UHQ5 H
A0A7V8IKS6 H
D0KXQ0 H
H1YCC3 H
K9Z0D3 H
A0A5C5TYS5 H
B0CQX4 E
G0H0Z6 H
V4RHR4 H
A0A087EQK8 H
A0A0D2LEF5 E
B3MX93 H
C3YB74 H
B8ZYW3 H
H6LKH6 H
Q9H310 H
A0A2S5WV24 H
A0A369NYJ2 H
A0A401X433 H
A0A833LX85 H
A0A977NL43 H
V4RK08 H
A0A251XU71 H
A0A8G2IZM3 H
A0A3G9G4Q4 H
G0JRQ3 H
A0A0A2ZRL7 H
D3RMV7 H
K1K628 H
Q46G49 H
A0A370FPU0 H
A0A5M5PZE2 H
A7RNC3 H
I6Z905 H
V4AP67 H
L0JT30 H
A0A074ME37 H
A0A0E9NHV4 H
A0A7R6PER3 H
A6XBM2 H
C9RS76 H
P69681 H
W0E077 H
A0A0U1NJW3 H
A0A6H9GEE4 H
C3YB73 H
G7WCB6 H
I4C9L0 H
A0A0A2A0Y9 H
D5V7B3 H
A0AA94HTL8 H
D3F545 H
G0JRG6 H
U1PPI7 H
A0A2S5WGI8 H
A0A420KGW4 H
H1XV27 H
C8WZE0 H
Q46HB1 H
A0A075WG29 H
A0A089ZBW5 H
A0A3E0X011 H
C1A872 H
C1N5A7 H
D2R647 H
D5T4N9 H
U5C2K4 H
R8VWI7 H
A0A0D8BQX6 H
A0A1H4KAQ7 H
E0SD83 H
G0EFF3 H
Q6ARH0 H
A6M3G0 H
L8GFX3 H
M5SY07 H
S3K1S2 H
A0A016XCG9 H
A0A2K1RA81 H
A0A6F8TLE9 H
B0DFJ4 H
I4C9L2 H
A0A9Q8L398 H
A9BIZ7 H
B8J5X4 H
W7QGM4 H
A0A2N7L7C8 H
A0A7H8UK07 H
A0A7S0D560 H
B3QRJ4 H
D8PD01 H
Q7W7D3 H
A0A248LNW8 H
A0A4Y4DZN4 H
A0A7U8C744 H
E4RTK5 H
K9U8C7 H
G3A431 H
Q1AUG3 H
U1PIR6 H
A0A060HN92 H
A0A0E3R6S1 H
A0A1B9LFW3 H
D9SI59 H
E1QIU3 H
E8RSE4 H
A0A1T4SFK4 H
A0A257T7G4 H
A0A2W5VAZ2 H
A0A7U4DN04 H
A1VIG8 H
Q1K3N8 H
Q89WR5 H
Q0VLH1 H
Q1YDY8 H
A0A495D4X4 H
A0A4Y1MSE7 H
A7S3L2 H
D0L8H3 H
E4T3F3 H
K9YN27 H
A1ZGK6 H
C5LAG4 H
D9SI36 H
A0A165K0X5 H
A0A1G9P6Q0 H
A0A1I5GN22 H
A0A1X4G8K1 H
A0A7G5DKA9 H
F8IJE0 H
Q2YBP7 H
Q466Y3 H
T2JFS5 H
A0A1E2SKM1 -
A0A2W4ZXC0 H
A0A4R2M206 H
A0A5M4AWD2 H
D6SPD1 H
A0A1M5ZVP9 H
F5R974 H
Q95P70 H
Q2RM12 H
Q6LMI6 H
A0A091AXI3 H
A0A0A1ZMZ9 H
A0A330GB00 H
B0BZN3 H
C7LW88 H
A9V5W4 H
E5Y678 H
G4H971 H
A0A075JIN0 H
A0A1M6ZMI3 H
C7BJG7 H
Q1JXS5 H
Q2FS34 H
C5KTM6 H
A0A068SVR1 H
A0A0K2STH0 H
A0A2N6JV02 H
A0A3N0AQL8 H
A6W7U2 H
A0A2N6K4Y5 H
D0LTW3 H
Q1K433 H
A0A063Y780 H
A0A168EVK8 H
A0A1G7DX68 H
A0A1W2H3F0 H
A0A2H4U5R1 H
A0A060URC3 H
A0A0D5YN10 H
A0A1H1U2Q6 H
A0A399NT81 H
Q5KPM5 E
Q9QUT0 H
Q5P1S8 H
A0A0E3QY86 H
A0A2S6GKF6 H
A6LV49 H
E2SD44 H
M2A398 H
B0RC35 H
E4TRS4 H
Q81GN5 H
A0A1B0ZRL8 H
A0A1I0BYN1 H
A0A1M7UEG2 H
A0A202B535 H
A0A5M8QF12 H
B4D7W2 H
C9KKP2 H
E6SF19 H
A0A021VMC6 H
A0A0E3WZH5 H
A0A165MAC2 H
A0A1C7EL50 H
A0A5M4ATH9 H
F5L8M7 H
Q2RWY7 H
U3P8G1 H
M4VEJ9 H
Q5FLR6 H
A0A147GP06 H
A0A1B9K8L2 H
A7MFK3 H
C8WSI9 H
K1LDP0 H
Q82X47 H
A0A2T1N7R1 H
A0A833H2R7 H
D2RU19 H
G8JTW0 E
Q59UP8 H
A0A1Y0V4A5 H
A0A258HS77 H
A0A369MHK2 H
H1Y7T6 H
Q07UM3 H
R9GM11 H
A0A9E9L9J1 H
A0RXK8 H
B7GKP4 H
I4D6Z9 H
I5AZQ4 H
A0A149V596 H
A0A257SYX3 H
A0A2A2M8K7 H
A8G2S3 H
C6DB68 H
E4YA63 H
G2ZN72 H
A0A074KZD8 H
A0A225CMT8 H
A0A7S4GNJ2 H
E1SLM7 H
A0A088E6Q7 H
C7Q1E4 E
H6LFQ2 H
J7J5E7 H
Q0ARJ4 H
A0A2R4TRE0 H
A0A4Q2QWS1 H
B0DU91 E
A0A3E2VY88 H
A0A533I6R2 H
A0A9R0NTP8 H
A8LKQ0 H
Q84KJ6 H
Q9REX3 H
A0A087MGU4 H
A0A377I7W9 H
A0A7T5BFQ2 H
B3DUX7 H
C0GKN4 H
J9Z839 H
K8EJ02 H
A0A1B9MZ78 H
A0A2G6JLT9 H
A0A6T9XUR2 H
A0A7G5EC77 H
F2G6G4 H
A0A2Z4MD56 H
A0A317FZW2 H
H6LKH9 E
Q7T070 H
Q0ACK1 H
Q1Z695 H
Q5FSX6 H
A0A7Z0V0A4 H
C6CBB1 H
I5BYV5 H
K2IMJ7 H
M2ALH9 H
V5BYZ7 H
C5CIT6 H
Q0F2M5 H
Q2J376 H
A0A1G6ABK5 H
A0A2W0GQV0 H
A0A6U2BIY7 H
A0A7M6UUM4 H
B7FW68 H
K2JVF8 H
R4FZE3 H
A0A016XDZ5 H
A0A1A0DHK0 H
A0A2S0Q8P1 H
A0A317G0I6 H
B1ZSW9 H
A0A2C6C0X3 H
D5E995 H
Q2IHY5 H
U2WTW8 H
A0A1C6Z081 H
A0A5M4AUM9 H
E6VIW4 H
G0JRH4 H
I2GD40 H
A0A1H9RTW8 H
A0A4U1K1W1 H
B1Y0E5 H
Q21J04 H
B7X047 H
F2NGJ8 H
A2C095 H
K9ZLY2 H
A0A2N6NEK4 E
A0A6N2Z556 H
F2AUF4 H
S0APH6 H
A0A160KTE9 H
A0A4V3ALP8 H
P41948 H
Q0G2V0 H
Q7NCB8 H
Q488X2 H
A0A1I4ZIZ6 H
A0A211ZGL5 H
A0A258HPP1 H
A0A6M3ZKU5 H
D5EP71 H
A0A1B9MYL7 H
A0A2N7LCD7 H
A4BAE1 H
I5C044 H
C5BWX7 H
R1D1H4 H
A0A1B9JZS5 H
A0A3E2TW06 H
A0A4R6DFU8 H
A0A7T4WEP4 H
B4CV94 H
A0A414NWT8 H
A0A2S8GF54 H
A0A3S9N9F3 H
L0KW14 H
O66395 H
B0VMH1 H
A0A0A2C6L1 H
A0A1H8D0R8 H
A0A1Y0UZX2 H
A0A6C8LST1 H
A9AUR8 H
A0A0H3H4I7 H
A0A556SRH6 H
A2CCK1 H
E7RJZ0 H
M1V7W3 H
A0A1B9NQ91 H
A0A1V3SSW1 H
W0DYY3 H
A0A067Z3S3 H
A0A418VIJ8 H
A0A5C4RNH5 H
A0A830ZZN8 H
A7SGD4 H
A0A9Q9D9I3 H
A0A096EEV9 H
A0A423Y4I6 H
A0A854QN45 E
A0LV78 H
K9W4V5 H
Q1YDY7 H
U3PCH5 -
A0A0L0S493 E
A0A2S8GSU9 H
A0A4R8GSH7 H
A0A7S0KKL8 H
I0KDC6 H
A0A4Y7XC43 H
I9P003 H
Q0VPH4 H
Q5KAF6 H
A0A1B9BUU6 H
A0A2T5IHP0 H
B8IZX4 H
D2ZRW2 H
A0A0A2VPU3 H
A0A7U8C2Y6 H
F0ZPL3 H
K8W1E2 H
Q3AP28 H
A0A0A2B651 H
A0A257T8W6 H
A0A2G5BI87 E
D2BUJ8 H
G5EB09 E
Q1PX09 H
Q5QVH2 H
A0A1D8UWJ6 H
A0A1J5NTP7 H
A0A395VB65 H
A0A8G2F3G4 H
E5Y789 H
J1L5M8 E
A0A066ZRQ5 H
A0A2S5Y0D3 H
A0A315S845 H
A0A6H9GFU4 H
B0SL05 H
A0A5J6WQU1 H
C3X831 H
M1WRK6 H
M9RJS5 H
K6W5X0 H
P69680 H
R9PMC6 H
A0A0H3KTD3 H
A0A178TA08 H
A0A1Z3MS36 H
A7SED8 H
F7NPQ3 H
T2KJ59 H
A0A177W826 H
A0A2I0UUY1 H
E4NS62 H
R1EDV9 H
E1V4T3 H
Q6BT62 H
A0A0B5FNH4 H
A0A0T7FAP8 H
A0A1J1JH03 H
A0A251YU48 H
C1G973 E
A0A1H1MB73 H
A0A323UDG5 H
D7UQE2 H
Q22947 H
Q2YLQ6 H
A0A9W5JBA9 H
A0KPE9 H
B2GFN1 H
S0G181 H
A0A510HHK8 H
A8AC17 H
A9BTK1 H
B7FTM9 H
A0A316BQ38 H
A0A4P6UIK6 H
J2ZGN6 H
M8E0R3 H
A0A066ZTE4 H
G8R7U9 H
Q21P82 H
A0A2K3DQF8 H
E5B358 H
F8D7H6 H
Q1K0H9 H
A0A149QSR6 H
A0A4R2Z2K6 H
A0A562USB9 H
A0A975BTN0 H
G4QHD2 H
A5E3X2 H
A7HT14 H
B1JZ69 H
A0A060HFT5 H
A0A0C6P439 H
A0A149UP06 H
A0A174SD65 H
A0A251XJT0 H
B8FGW0 H
E0TGP9 H
A0A0L8BVU4 H
A0A1U9Z147 H
A0A2T4XZC1 H
A0A3E2T713 H
Q7UGU7 H
A0A062IU58 H
A0A4R3A5P7 H
G7WJN0 H
I4CCD1 H
B8FZP7 H
D0MFE8 H
F8E6R1 H
A0A071M4L5 H
A0A248LNK5 H
A0A653N397 H
A5D4I5 H
A7SQ16 H
F5ISF6 H
G3IYW0 H
A0A3N1VXY4 H
A0A6N4SPH9 H
A1DG05 E
A4ABK3 H
C1D4X0 H
A0A149TSA9 H
A0A2S5WMT7 H
A0A837C6X5 H
D3FBG3 E
U2EN72 H
A0A2S7YIM5 H
D6TCH6 H
Q1IWN6 H
Q9BLG3 H
Q1QSQ2 H
A0A0D2KGN8 H
A0A0H3DR67 H
A0A149RYW7 H
A0A290XBB5 H
F4B548 H
U1H1F7 H
W7QGE0 H
A0A0E3BR91 H
J4UGB7 H
Q5UZ98 H
W0DZS7 H
Q2W5V2 H
A0A068NPW2 H
A0A855F5Y8 H
A7HSN9 H
G2T1Y3 H
H6LKX6 H
A0A1X6N3Q5 H
F2JZ83 H
R9PI53 H
A0A381CAY8 H
A0A657K391 H
Q2HD43 E
A0A3R9Q7C4 H
A0A562S8V2 H
A0A854Q6X9 H
A7I8Z2 H
G7WFX4 H
E6W5C1 H
K9YJQ3 H
A0A410JZR4 H
A0A482PLH3 H
A0A6H9FPY5 H
A2SS52 H
D3LBI0 H
B2IJT1 H
B3PF77 H
O04161 H
A0A059XXR1 H
A0A2G5BGA9 H
A0A2S8FTB5 H
A0A323UE08 H
B1XZU2 H
Q3B6Q2 H
G5EB13 H
L1IYW7 H
Q8ERT9 H
A1SY01 H
B4S394 H
B8FDY8 H
D6E7B3 H
F0YLV7 H
A0A4R3ZZ35 H
A0A9J9BAE8 H
A1SVA8 H
M5SYZ1 H
Q2N625 H
Q6QH01 H
Q9VFA9 H
A0A2S8FR08 H
A0A375YPN6 H
Q3Z7F9 H
R7PZ71 H
T2J0N1 H
B9SWW9 H
A0A1H7CU41 H
A0A318FY98 H
A0A502GPV4 H
B3PIH2 H
B8EMQ8 H
A0A074KY88 H
A0A1I4W3A0 H
A0A2T9X1V4 H
A0A4R3ZNW3 H
A0A7T2S0Z6 H
A0A4V0XUI3 H
F2JTN3 H
A0A0E3QYF3 H
A0A248TDF2 H
F2NNQ0 H
M9YAI9 H
Q1Z4I4 H
E3I393 H
G7WFX2 H
A0A075WBP9 H
A0A1T4SFY6 H
A0A2S5V2F6 H
A3ZT81 H
A9DQM8 H
I0HKQ8 H
L8H5K0 H
A0A068NV61 H
A0A1R1IDV3 H
A0A1W5PRD1 H
A0A2S5X482 H
A0A4R3NLV5 H
A0A0S6UEK9 H
A0A165BP25 H
I1DSU5 H
Q0AT01 H
U1SIR9 H
C7R314 H
I3Z3H7 H
K9ZG59 H
A0A073CP02 H
A0A2H1HV86 H
A0A328EMN2 H
A0A836M2B6 H
B9L7N1 H
L1INN6 H
A0A4V2X6C2 H
A8ZQD5 H
D2Q0J8 H
A0A0A2A5X1 H
A0A0E3SP24 H
A0A0M2LU39 H
A0A1Y4LM49 H
A0A1Y6GLJ1 H
E4N1T5 E
A0A0S4WFM4 H
A0A2U1SS17 H
A0A2X2C038 H
D2BIB2 H
I0ICG0 H
D0LAL7 H
E1QFA8 H
I5B3H0 H
A0A6A1TYJ4 H
A0A7U4E420 H
A0A8H7U3I1 E
A0A9Q5QVI9 H
A0AA35XZV0 H
P40260 E
Q4WT12 H
W0DZX1 H
C6WEW7 H
E4TJ50 H
K9YR86 H
A0A172YBR4 H
A0A2G3E8V2 H
A0A4R7VEK0 H
A0A660CH85 H
A1D2Y5 H
B8FL88 H
B9SA70 H
M1NZT5 H
Q84KJ7 H
F0ZCX7 H
A0A2T2Y0D5 H
A0A9J9ES23 H
D3F0Z1 H
D5ASL9 H
D9QS43 H
A8PXT8 H
I3R0S7 H
X5CNT2 H
L7CG99 H
A0A0A0D6K5 H
A0A1B9M1A9 H
A0A4R5U5V1 H
A7S731 H
H5UND3 H
A0A401WUW1 H
A0A556RTU3 H
D5ELM4 H
D6TFE1 H
Q2RVB5 H
A0A1H3WA00 H
G0JRG9 H
L1J6I4 H
D5EP68 H
A0A2S5YID7 H
A0A6P4JM51 H
A0A918MJ52 H
A1AVV2 H
D4F313 H
F0J3F9 H
Q7NQY2 H
Q92BJ7 H
A0A248LMH8 H
A5DYQ2 E
C7QGX3 H
Q605Y6 H
F4D1J0 H
A0A2S5CTX8 H
A0A2S7YPJ9 E
A0A9P3CXY2 H
C7LQR9 H
F2YIC4 H
M0J579 H
Q7UYZ3 H
A0A0B4M163 H
A0A149RQX0 H
A0A1I0AQM4 H
A0A2K1RA77 H
C1D6X6 H
A0A366IE34 H
A7HSP2 H
A0A833GZR2 H
A5UJR1 H
B0DY50 H
A0A161SKF4 H
A0A165MFD1 H
A0A7G5DPV0 H
A0AIW5 H
D3DJN2 H
A0A495WJM6 H
A0A0S4VNK2 H
A0A172RYW3 H
A0A1H9M798 H
A0A975GIX9 H
A0A2M9D7S8 H
A0A427KNL6 H
A0AA35XVN2 H
E4U5Z1 H
G0V8D6 E
I4D1H5 E
L8H844 H
A0A433ZQ80 H
A0A6G9XJV9 E
A0A8H4GS02 H
A0A0S2DQB6 H
A0A1S8D478 H
A0A2A7U6W1 H
A0A2I1M481 H
A0A2S0JW39 H
A0A8H6MPB9 E
B8ENL9 H
D5UD26 H
E0TCV4 H
E8RLT5 H
Q6BJI7 E
A0A1B9MBX6 H
A0A858ZNJ3 H
J3EXK0 H
M0MDP9 H
S0EUS1 H
A0A2S0P9T4 H
A0A2T4UWF1 H
G0IYI2 H
Q3AFY9 H
Q7S5K0 H
A0A0L0STS6 E
A0A7T2W1B3 H
C8XBX8 H
D6Z5V9 H
Q8RUT6 H
F4Y3C5 H
Q45HK8 H
A0A101DCS3 H
A0A258FS85 H
A0A7S4GND2 H
G8TK77 H
A0A1G5PWV0 H
A1CQ21 H
Q47K18 H
Q60C43 H
A0A0D2UPA8 H
A0A1X4GBG2 H
A0A2N6P374 H
D3PAH1 H
Q18PF5 H
A0A097R891 H
A0AA92EGF5 H
D7G265 H
A0A6J5IRX5 H
Q18ES8 H
Q47X17 H
Q9UBD6 H
A0A068TC78 H
A0A085GI50 H
A0A0B4E6X7 H
A0A1U9YY82 H
A0A419AVL2 H
A0A4R7GKA0 H
J7IVQ1 H
L8JUH3 H
Q94CJ2 H
A0A1J5NNB8 H
A0A257TE48 H
A0A4U1JNL6 H
B8JBH5 H
F2JYR9 H
Q7TNN9 H
A0A017SYR8 H
A0A2S8QA29 H
A0A369MRW6 H
M0D3Q9 H
Q2WBF7 H
A0A1Y5E3E3 H
D3RN22 H
D9QPE5 H
I7ZHW3 H
A0A1G5W0P2 H
A0A2V4EA49 H
A0A401WXG0 H
A0A5M4B0G1 H
G3IYW2 H
A0A2S8F4W0 H
A0A4Q2EAG7 H
A0A8G2F718 H
A9B874 H
K0F9X7 H
I8TC71 H
M7NFH3 H
W0F0I7 H
A0A081N2G5 H
A0A0D7F2Y9 H
A0A0T7GZ59 H
E3HJW8 H
G7UUY6 H
A0A264VQM8 H
A0A366XFS8 H
A0A424WAH3 H
Q9M6N7 H
A0A0A2BBY0 H
A0A0H2XSU4 H
A0A9Y2AG30 H
W0JIB3 H
F6BEI0 H
M5U2P1 H
A0A011U1K7 H
A0A0X8NXA9 H
A0A829X098 H
A0A8H6NAG3 E
A8NAG3 H
N1WR17 H
A0A4D6KHD1 H
A0A1T4SF40 H
A3PAY4 H
V5U2Z4 H
W8KM07 H
A0A379A0S9 H
A0A380S5X4 H
A0A7S4GNF3 H
J1ASR8 H
A0A1D3GAE9 H
B9LU00 H
E4T0A4 H
J9VXX9 H
A0A2T0XPP2 H
A0A328Q6M1 H
A0A399T909 H
A0A009PYN3 H
A0A5C6LWQ1 H
A0AA46Q839 H
B0DU93 E
D9QPC8 H
A0A2T0GTU1 H
A0A8H7P8U1 H
A0A9Q6P4A5 H
Q0BWD0 H
Q0G0A3 H
Q1Q357 H
Q5KZZ9 H
A0A2J7TJ33 H
A0A410K1J5 H
C6XKC2 H
H2CDR5 H
Q4WHC6 E
A0A8E2UDJ3 H
D2V6Q5 H
Q0I445 H
A0A3T0SZ22 H
A0A495DND0 H
Q9NIV0 H
A0A857DMN9 H
A3XNG6 H
B7G0Y4 H
Q1K8A3 H
Q8I0L6 H
A0A2G5RQK9 H
A0A2R3IMJ8 H
A0A420WC79 H
D2V6P8 H
D8J4C6 H
Q1L727 H
A0A0P6VSR8 H
A0A6H9FYW4 H
A0A6N2TIA4 H
A6LRS5 E
Q0VQH6 H
A0A075WEB4 H
A0A144NLT9 H
A0A2S5WX34 H
C8WLL8 H
F0S3Z6 H
I1YG38 H
A0A075JZ35 H
A0A0E3LMT4 H
A0A0F5EZP7 H
A4CMI3 H
A5CRL2 H
Q60BI2 H
Q8RUE9 H
A0A0K2STQ7 H
A0A2G3DSU6 H
A0A5J6WPP9 H
G0VI62 H
K0K7J4 H
M9RKT6 H
S5ABR8 H
V3ZVE4 H
A0A094W9G3 H
A0A2W5HTC3 H
A2SPS8 H
C7LW87 H
H1YF74 H
B4HDZ9 H
D3PE53 H
M7XJ51 H
A0A0K2STK6 H
A0A149QAW7 H
A0A1G6ABL9 H
A0A1V2XMU9 H
A1B3N0 H
Q6ND36 H
A0A015YIP3 H
A0A212AV03 H
A0A318QZ80 H
A0A6B8N021 H
Q07UM1 H
A0A2S6GKN5 H
A0A373FQ71 H
A0AA91Q161 E
K0NJH2 H
L8GGA0 H
A0A060UWC8 H
A6VE60 H
F0RHS0 H
A0A4Q7Y9I7 H
A8N2H6 E
Q2KZK9 H
A9WHW6 H
K9W6F3 H
K9WT03 H
A0A037ZMW1 H
A0A140NHJ5 H
A0A366WYI9 H
A0A4P6UIJ8 H
A0A5C5TUT2 H
C1MX19 H
E3GI40 H
L0K9M1 H
A0A1Y5E8I7 H
A0A251Y3N4 H
A1VIM5 H
A7NKH2 H
B0SRS8 H
Q608B6 H
J7L3W8 H
A0A0A3XTJ3 H
A0A5P9P1L2 H
A0A642KQG8 H
D0MFE9 H
I4D6Z7 H
G0AFH4 H
H2CJI0 H
Q21CP1 H
A0A0E3SHQ9 H
A0A1B9BUZ8 H
A0A1E3PSK5 E
A0A1I7FBM5 H
A0A2A2MCP3 H
Q2IK04 H
U5DEY6 H
A0A1Y0HX98 H
A0A258FTB0 H
J4KM12 E
M1SJL5 H
Q0BQ69 H
D4XSW0 H
E3H8A6 H
E4T3F7 H
A0A0V8M0W6 H
A0A166IS52 H
A0A7S4LPS8 H
C0Z5S5 H
C3X1J1 H
F7ZJM0 H
K0N2R5 H
O26757 H
D4XLN6 H
H6RWK9 H
J7ITF6 E
A0A1G7UZX2 H
A0A1S1HRJ0 H
A0A378YR15 H
A0A7S0ILH2 H
B9WDK0 E
Q2FQT3 H
S0ET45 H
A0A291PMC6 H
A0A1G6ABX1 H
F4H924 H
A0A0A1ZJU5 H
A0A0X8X7Y7 H
F0J7D3 H
K5CFE5 H
M5S9B4 H
H2CLF7 H
I0WJ97 H
Q0F2M7 H
A0A4R4K1P9 H
A4FMG0 H
A6GJF5 H
F0Y9X3 H
G4R7P1 H
Q5P470 H
A0A6G9Y3Q0 H
A0A8H6K7L7 E
A6DN47 H
A0A071MMV1 H
A0A1B9M5B8 H
A0A1G7VM92 H
A0A1Y2JH43 H
A0A494JB70 H
F5Y3C1 H
G0J614 H
G0LFE3 H
A7I8Z4 E
C1MHX0 H
D4H2Y7 H
F3ZYD6 H
F5XN43 H
L0FU80 H
L1IHZ8 H
M0D580 H
T2KGT3 H
I3C0V3 H
A0A1E5BXA4 H
A0A7G5DPV1 H
A3TVQ9 H
B7G0Y1 H
C6LBD3 H
A0A7U3XVQ4 H
D5VJ32 H
L0KGR8 H
L1IYP4 H
R1FI09 H
A0A1L3F1X5 H
A0A2S8GEJ5 H
F3ZVV4 H
J0S2I0 H
Q97L80 H
A0A063Y394 H
A0A142VAD6 H
F7ZJZ1 H
Q6HM26 H
A0A369M386 H
A0A7U3YMN6 H
F6FRU9 H
I1YJH7 H
Q7V4T8 H
B0SLB7 H
F3QNA7 H
A0A0A2AMW2 H
A0A0E3R4G0 H
A0A853MG28 H
Q0G0A4 H
A0A5C5BWI6 H
K9WSX4 H
Q13E03 H
R1EGK6 H
A0A060URB8 H
A0A251YFS0 H
C1N6X9 H
S9QZ09 H
A0A173R3X4 H
A0A4R8H081 H
C7M2A9 H
Q6ND34 H
X5DX97 H
A9HMD6 H
Q6LKC8 H
Q8GQS1 H
A0A037ZJY5 H
A0A098S5Y7 H
A0A4R3NVT3 H
C9R9J0 H
Q9QXP0 H
K5DBA0 H
A0A060JMP6 H
A0A1W2GZ82 H
A0A1W9KSU5 H
A0A857DDJ7 H
A2BUP4 H
A0AA40J491 H
C8X554 H
H2IZ00 H
V4CRP5 H
A0A1I0C958 H
A4BEP1 H
Q1H0G2 H
A0A176XNC5 H
A0A1B9KID3 H
A0A3G9G2C9 H
M1P5F0 H
I4DBY0 H
A0A562RGZ4 H
A0A6H9GLV4 H
A8MCL4 H
A9UR54 H
D4H5F9 H
L7CG11 H
V5E0F3 H
A0A060UN76 H
A0A142NNN1 H
A0A2S5WZU0 H
A0A4P8HC89 H
A0A542XGT4 H
A0A1S1HM83 H
A0A1Y3U5V2 H
C1GR74 E
A0A0M3AB44 H
A0A2R4MBA2 H
U7VB41 H
F4GED5 H
A0A034WGQ2 H
A0A0S6UHP2 H
A0A173R3W6 H
A0A3E2UCG9 H
B7FSA7 H
A0A3P2A7W8 H
A4BMY5 H
G9Y5B0 H
D2SE15 H
Q31CR9 H
A0A149U2G9 H
A0A3N2SFS2 H
A0AA92K392 H
A8HSA2 H
C0QSY0 H
A6DUG4 H
Q5FA36 H
Q6BK68 H
A0A1X3RP39 H
A0A369N7Y3 H
A0A6H9GWG4 H
A0A7S4GMD8 H
A4G1J2 H
A0A0D2NYP3 H
A0A8B4RWH8 H
B1Y6V4 H
Q2SIR0 H
T2IEJ2 H
A0A1G5RZU9 H
A4G0C5 H
B9SXC7 H
C4Y298 E
C7NND3 H
A0A1B9JHS5 H
D3S2L0 H
I0HGY4 H
F0JGZ1 H
A0A6M3ZJI1 H
A0A8F5VN39 H
A0A9W3LFI9 H
A9BQZ4 H
F0J6E8 E
A0A087L0B9 H
A0A127JTU2 H
A0A2S5WUP6 H
D5AU98 H
U5C4L4 H
A0A009TDB1 H
A0A1B9N3H7 H
A0NJ07 H
D2R355 H
K9P5D1 H
K8VZC6 H
L1IUV5 H
W7QG13 H
A0A101HKN9 H
A0A1E3PQH0 H
A2BP62 H
B1Y842 H
G8JUJ2 H
H8L2Q4 H
Q7SEH0 E
A0A0D7F328 H
A0A2K3DPU7 H
A0A562BXM4 H
A0A855EH99 H
D4GLQ6 H
F0S0G1 H
F4XTK4 H
A0A2S5XAB8 H
A0A3E2UHE6 H
F4KY49 H
A0AA86YS65 H
A3ZZL7 H
B0CXH8 H
B8GGC1 H
Q2S8H9 H
A0A149UWF2 H
A0A172YCA7 H
A8M670 H
D7E934 H
Q7T3R4 H
A0A0L0TDW1 H
A0A1M6BPM0 H
A0A6S5K4J1 H
A0A7G5DK18 H
E2SD33 H
A0A0B4DUR9 H
A0A8F5ZDT8 H
F3KUN4 H
Q63EK5 H
A0A2S6H6B7 H
A0A9E9LXV9 H
M5S735 H
Q1H483 H
B3QVV5 H
F3QPR6 H
A0A0S2FHD7 H
A0A1Y4L5P0 H
A0A242NIL1 H
A0A511NGC7 H
A8P923 H
A3U857 H
B8GGC3 E
F5RGM7 H
I0JI83 H
Q1QS12 H
A0A377PBY1 H
B1Y8C9 H
C8XB51 H
F7ZEU9 H
G7WA28 E
A0A5B2V3B9 H
A0A979GQ79 H
A0RUZ2 H
A0A076PL76 H
A0A0H3LUA3 H
A0A1J5JH24 H
A0A1Q2C7H7 H
A0A5A7MAJ9 H
Q6CRN1 H
Q7Z1M1 H
A0A1E5C7W4 H
A0A8E2R1Y5 H
K9P718 H
A0A147EQL9 H
A0A2N0MZ27 H
B0DXT9 E
G2PRJ6 H
B0XVV6 E
C0QTA4 H
C1F584 H
V4REY8 H
W5WIX6 H
A0A077EFU9 H
A0A1H4DJ49 H
A0A1M6JKY3 H
A0A2C9CK98 H
K0ER80 E
F2B2B8 H
F6G5I9 H

In [63]:
seqet = []

for i in et:
    # print(i.id, i.seq)
    # fiftyfour.append(f"{i.id} {i.seq}")
    seqet.append(i.seq)

In [64]:
seqet

[Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('A'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('A'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('-'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 Seq('H'),
 ...]

In [65]:
df3 = pd.DataFrame(tsid)

In [66]:
df3['26'] = seqts

In [67]:
df3['80'] = seqet

In [68]:
df3['merged'] = df3[0] + ' ' + df3['26'].astype(str) + df3['80'].astype(str)

In [69]:
fullhh = df3['merged'].to_list()

In [70]:
rig = []

for u in fullhh:
    rig.append(u.split(' ')[1])

In [71]:
regset = set(rig)

In [72]:
regset

{'-A', 'EH', 'H-', 'HH'}

In [213]:
idhh = [] 
idhe = []

for y in fullhh:
    if y.split(' ')[1] == 'HH':
        idhh.append(y.split(' ')[0])
    elif y.split(' ')[1] =='EH':
        idhe.append(y.split(' ')[0])

In [122]:
u = UniProt(verbose=False)

In [147]:
linige = []
for item in tqdm(idid):
    lineage = u.search(item, columns='lineage')
    print(item)
    print(lineage.split(',')[1])
    finige = f"{item}:{lineage.split(',')[1]}" 
    linige.append(finige)

  0%|▏                                                                                                                                                       | 2/1281 [00:00<03:54,  5.45it/s]

A0A858ZNJ3
 Bacteria (superkingdom)
A0A1H9M798
 Bacteria (superkingdom)

  0%|▍                                                                                                                                                       | 4/1281 [00:00<03:51,  5.52it/s]

B0DY50
 Eukaryota (superkingdom)
P69680
 Bacteria (superkingdom)

  0%|▋                                                                                                                                                       | 6/1281 [00:01<03:48,  5.58it/s]

A0A3G9G4Q4
 Bacteria (superkingdom)
A0A149UP06
 Bacteria (superkingdom)

  1%|▉                                                                                                                                                       | 8/1281 [00:01<03:47,  5.60it/s]

F2G6G4
 Bacteria (superkingdom)
A0A2M9D7S8
 Bacteria (superkingdom)

  1%|█▏                                                                                                                                                     | 10/1281 [00:01<03:43,  5.68it/s]

A0A034WGQ2
 Eukaryota (superkingdom)
I0KDC6
 Bacteria (superkingdom)

  1%|█▎                                                                                                                                                     | 11/1281 [00:02<04:24,  4.80it/s]

F8D7H6
 Archaea (superkingdom)
K9W4V5
 Bacteria (superkingdom)

  1%|█▌                                                                                                                                                     | 13/1281 [00:02<04:14,  4.99it/s]

Q466Y3
 Archaea (superkingdom)
D2SE15
 Bacteria (superkingdom)

  1%|█▊                                                                                                                                                     | 15/1281 [00:02<04:10,  5.06it/s]

A0A377PBY1
 Bacteria (superkingdom)
B1JZ69
 Bacteria (superkingdom)

  1%|██                                                                                                                                                     | 17/1281 [00:03<04:08,  5.10it/s]

A0A2W5HTC3
 Bacteria (superkingdom)
A8G2S3
 Bacteria (superkingdom)

  1%|██▏                                                                                                                                                    | 19/1281 [00:03<04:06,  5.13it/s]

D5T4N9
 Bacteria (superkingdom)
Q2RWY7
 Bacteria (superkingdom)

  2%|██▍                                                                                                                                                    | 21/1281 [00:04<04:06,  5.12it/s]

A0A0E3R4G0
 Archaea (superkingdom)
I4C9L0
 Bacteria (superkingdom)

  2%|██▋                                                                                                                                                    | 23/1281 [00:04<04:04,  5.14it/s]

D5VJ32
 Bacteria (superkingdom)
C0Z5S5
 Bacteria (superkingdom)

  2%|██▉                                                                                                                                                    | 25/1281 [00:04<04:03,  5.16it/s]

C1N6X9
 Eukaryota (superkingdom)
J7ITF6
 Bacteria (superkingdom)

  2%|███▏                                                                                                                                                   | 27/1281 [00:05<04:02,  5.17it/s]

A0A068SVR1
 Bacteria (superkingdom)
A0A0D7F328
 Bacteria (superkingdom)

  2%|███▍                                                                                                                                                   | 29/1281 [00:05<04:03,  5.13it/s]

Q0G0A4
 Bacteria (superkingdom)
F0J3F9
 Bacteria (superkingdom)

  2%|███▋                                                                                                                                                   | 31/1281 [00:06<04:05,  5.09it/s]

Q0BQ69
 Bacteria (superkingdom)
F2YIC4
 Eukaryota (superkingdom)

  3%|███▉                                                                                                                                                   | 33/1281 [00:06<04:04,  5.10it/s]

D4XLN6
 Bacteria (superkingdom)
A0A420WC79
 Bacteria (superkingdom)

  3%|████▏                                                                                                                                                  | 35/1281 [00:06<04:03,  5.11it/s]

A0A5C5TUT2
 Bacteria (superkingdom)
A0RUZ2
 Archaea (superkingdom)

  3%|████▎                                                                                                                                                  | 37/1281 [00:07<04:03,  5.11it/s]

A0A0A2ZRL7
 Bacteria (superkingdom)
J4UGB7
 Eukaryota (superkingdom)

  3%|████▌                                                                                                                                                  | 39/1281 [00:07<04:03,  5.10it/s]

E5Y678
 Bacteria (superkingdom)
A0A0D2KGN8
 Eukaryota (superkingdom)

  3%|████▊                                                                                                                                                  | 41/1281 [00:08<04:03,  5.10it/s]

S5ABR8
 Bacteria (superkingdom)
A9DQM8
 Bacteria (superkingdom)

  3%|█████                                                                                                                                                  | 43/1281 [00:08<04:04,  5.07it/s]

G5EB13
 Eukaryota (superkingdom)
A0A2N6NEK4
 Eukaryota (superkingdom)

  4%|█████▎                                                                                                                                                 | 45/1281 [00:08<04:03,  5.07it/s]

C6DB68
 Bacteria (superkingdom)
Q81GN5
 Bacteria (superkingdom)

  4%|█████▌                                                                                                                                                 | 47/1281 [00:09<04:01,  5.10it/s]

Q0F2M5
 Bacteria (superkingdom)
A0A0C6P439
 Bacteria (superkingdom)

  4%|█████▊                                                                                                                                                 | 49/1281 [00:09<03:59,  5.14it/s]

B9SWW9
 Eukaryota (superkingdom)
L8H5K0
 Eukaryota (superkingdom)

  4%|██████                                                                                                                                                 | 51/1281 [00:09<03:58,  5.15it/s]

Q9NIV0
 Eukaryota (superkingdom)
C1N5A7
 Eukaryota (superkingdom)

  4%|██████▏                                                                                                                                                | 53/1281 [00:10<03:58,  5.15it/s]

Q1JXS5
 Bacteria (superkingdom)
A0A1M6JKY3
 Bacteria (superkingdom)

  4%|██████▍                                                                                                                                                | 55/1281 [00:10<03:58,  5.13it/s]

F4D1J0
 Bacteria (superkingdom)
A0A257SYX3
 Bacteria (superkingdom)

  4%|██████▋                                                                                                                                                | 57/1281 [00:11<03:57,  5.15it/s]

V4RK08
 Bacteria (superkingdom)
G0V8D6
 Eukaryota (superkingdom)

  5%|██████▉                                                                                                                                                | 59/1281 [00:11<03:58,  5.12it/s]

A0A7S4GMD8
 Eukaryota (superkingdom)
B3QVV5
 Bacteria (superkingdom)

  5%|███████▏                                                                                                                                               | 61/1281 [00:11<03:57,  5.13it/s]

F2JZ83
 Bacteria (superkingdom)
A0A857DDJ7
 Bacteria (superkingdom)

  5%|███████▍                                                                                                                                               | 63/1281 [00:12<03:56,  5.15it/s]

A0A0S6UHP2
 Bacteria (superkingdom)
D5EP71
 Bacteria (superkingdom)

  5%|███████▋                                                                                                                                               | 65/1281 [00:12<03:54,  5.18it/s]

F4KY49
 Bacteria (superkingdom)
M5S9B4
 Bacteria (superkingdom)

  5%|███████▉                                                                                                                                               | 67/1281 [00:13<03:55,  5.15it/s]

A0A009PYN3
 Bacteria (superkingdom)
A0A3T0SZ22
 Bacteria (superkingdom)

  5%|████████▏                                                                                                                                              | 69/1281 [00:13<03:55,  5.15it/s]

A0A248LMH8
 Bacteria (superkingdom)
A0A6H9GEE4
 Bacteria (superkingdom)

  6%|████████▎                                                                                                                                              | 71/1281 [00:13<03:55,  5.13it/s]

A7HSP2
 Bacteria (superkingdom)
A0A7V8IKS6
 Bacteria (superkingdom)

  6%|████████▌                                                                                                                                              | 73/1281 [00:14<03:55,  5.14it/s]

T2JFS5
 Bacteria (superkingdom)
F6FRU9
 Bacteria (superkingdom)

  6%|████████▊                                                                                                                                              | 75/1281 [00:14<03:54,  5.13it/s]

A0A9E9L9J1
 Bacteria (superkingdom)
A0AIW5
 Bacteria (superkingdom)

  6%|█████████                                                                                                                                              | 77/1281 [00:15<03:56,  5.09it/s]

A0A0E9NHV4
 Eukaryota (superkingdom)
Q2N625
 Bacteria (superkingdom)

  6%|█████████▎                                                                                                                                             | 79/1281 [00:15<03:57,  5.07it/s]

C8WSI9
 Bacteria (superkingdom)
A0A1H1BPD6
 Bacteria (superkingdom)

  6%|█████████▌                                                                                                                                             | 81/1281 [00:15<03:54,  5.11it/s]

A0A176XNC5
 Bacteria (superkingdom)
A0A4V0XUI3
 Bacteria (superkingdom)

  6%|█████████▊                                                                                                                                             | 83/1281 [00:16<03:53,  5.12it/s]

A7S3L2
 Eukaryota (superkingdom)
M5U2P1
 Bacteria (superkingdom)

  7%|██████████                                                                                                                                             | 85/1281 [00:16<03:52,  5.15it/s]

K9P5D1
 Bacteria (superkingdom)
Q0F2M7
 Bacteria (superkingdom)

  7%|██████████▎                                                                                                                                            | 87/1281 [00:16<03:50,  5.18it/s]

A0A2R3IMJ8
 Bacteria (superkingdom)
Q2RVB5
 Bacteria (superkingdom)

  7%|██████████▍                                                                                                                                            | 89/1281 [00:17<03:49,  5.18it/s]

A0A556RTU3
 Bacteria (superkingdom)
E0TGP9
 Bacteria (superkingdom)

  7%|██████████▋                                                                                                                                            | 91/1281 [00:17<03:50,  5.17it/s]

B7G0Y1
 Eukaryota (superkingdom)
A0A1G9P6Q0
 Bacteria (superkingdom)

  7%|██████████▉                                                                                                                                            | 93/1281 [00:18<03:55,  5.05it/s]

D0LTW3
 Bacteria (superkingdom)
Q6BT62
 Eukaryota (superkingdom)

  7%|███████████▏                                                                                                                                           | 95/1281 [00:18<03:54,  5.06it/s]

Q2IK04
 Bacteria (superkingdom)
Q6BJI7
 Eukaryota (superkingdom)

  8%|███████████▍                                                                                                                                           | 97/1281 [00:18<03:54,  5.06it/s]

B7X047
 Bacteria (superkingdom)
A0A068NPW2
 Bacteria (superkingdom)

  8%|███████████▋                                                                                                                                           | 99/1281 [00:19<03:51,  5.10it/s]

A0A399NT81
 Bacteria (superkingdom)
K0F9X7
 Bacteria (superkingdom)

  8%|███████████▊                                                                                                                                          | 101/1281 [00:19<03:49,  5.13it/s]

A0A037ZMW1
 Bacteria (superkingdom)
A0A075JZ35
 Bacteria (superkingdom)

  8%|████████████                                                                                                                                          | 103/1281 [00:20<03:49,  5.14it/s]

A0A369MHK2
 Bacteria (superkingdom)
A0A1B9JPL5
 Bacteria (superkingdom)

  8%|████████████▎                                                                                                                                         | 105/1281 [00:20<03:48,  5.15it/s]

D8PD01
 Bacteria (superkingdom)
A0A2G5BI87
 Eukaryota (superkingdom)

  8%|████████████▌                                                                                                                                         | 107/1281 [00:20<03:47,  5.16it/s]

A0A2G5BGA9
 Eukaryota (superkingdom)
A0A657K391
 Bacteria (superkingdom)

  9%|████████████▊                                                                                                                                         | 109/1281 [00:21<03:45,  5.20it/s]

P69681
 Bacteria (superkingdom)
A0A4P6UIJ8
 Bacteria (superkingdom)

  9%|████████████▉                                                                                                                                         | 111/1281 [00:21<03:43,  5.23it/s]

A0A0V8M0W6
 Bacteria (superkingdom)
A0A0H2XSU4
 Bacteria (superkingdom)

  9%|█████████████▏                                                                                                                                        | 113/1281 [00:22<03:44,  5.20it/s]

Q1Z695
 Bacteria (superkingdom)
A0A7Z0V0A4
 Bacteria (superkingdom)

  9%|█████████████▍                                                                                                                                        | 115/1281 [00:22<03:44,  5.19it/s]

K0ER80
 Bacteria (superkingdom)
A0A149UWF2
 Bacteria (superkingdom)

  9%|█████████████▋                                                                                                                                        | 117/1281 [00:22<03:44,  5.20it/s]

G0H0Z6
 Archaea (superkingdom)
G0EFF3
 Archaea (superkingdom)

  9%|█████████████▉                                                                                                                                        | 119/1281 [00:23<03:44,  5.18it/s]

C8WLL8
 Bacteria (superkingdom)
X5CNT2
 Eukaryota (superkingdom)

  9%|██████████████▏                                                                                                                                       | 121/1281 [00:23<03:44,  5.16it/s]

A0A4Y1MSE7
 Bacteria (superkingdom)
H2CLF7
 Bacteria (superkingdom)

 10%|██████████████▍                                                                                                                                       | 123/1281 [00:23<03:44,  5.16it/s]

M4VEJ9
 Bacteria (superkingdom)
A0A4V2X6C2
 Bacteria (superkingdom)

 10%|██████████████▋                                                                                                                                       | 125/1281 [00:24<03:47,  5.09it/s]

A0A2K1RA77
 Eukaryota (superkingdom)
A0A375YPN6
 Bacteria (superkingdom)

 10%|██████████████▊                                                                                                                                       | 127/1281 [00:24<03:45,  5.11it/s]

A0A7M6UUM4
 Eukaryota (superkingdom)
A0A172YCA7
 Bacteria (superkingdom)

 10%|███████████████                                                                                                                                       | 129/1281 [00:25<03:46,  5.08it/s]

A0A918MJ52
 Bacteria (superkingdom)
A0A2S8QA29
 Bacteria (superkingdom)

 10%|███████████████▎                                                                                                                                      | 131/1281 [00:25<03:44,  5.12it/s]

A0A251XJT0
 Bacteria (superkingdom)
A0A0B4E6X7
 Bacteria (superkingdom)

 10%|███████████████▌                                                                                                                                      | 133/1281 [00:25<03:43,  5.13it/s]

A0A0K2STQ7
 Eukaryota (superkingdom)
A1C5Z7
 Eukaryota (superkingdom)

 11%|███████████████▊                                                                                                                                      | 135/1281 [00:26<03:43,  5.14it/s]

C9KKP2
 Bacteria (superkingdom)
A0A2Z4MD56
 Bacteria (superkingdom)

 11%|████████████████                                                                                                                                      | 137/1281 [00:26<03:42,  5.14it/s]

Q9VFA9
 Eukaryota (superkingdom)
A0A502GPV4
 Bacteria (superkingdom)

 11%|████████████████▎                                                                                                                                     | 139/1281 [00:27<03:41,  5.16it/s]

I5C044
 Bacteria (superkingdom)
D2V6P8
 Eukaryota (superkingdom)

 11%|████████████████▌                                                                                                                                     | 141/1281 [00:27<03:40,  5.18it/s]

D3RN22
 Bacteria (superkingdom)
Q97L80
 Bacteria (superkingdom)

 11%|████████████████▋                                                                                                                                     | 143/1281 [00:27<03:38,  5.20it/s]

A0A0D5YN10
 Bacteria (superkingdom)
A0A1I5GN22
 Bacteria (superkingdom)

 11%|████████████████▉                                                                                                                                     | 145/1281 [00:28<03:38,  5.19it/s]

A0A1Y5E8I7
 Bacteria (superkingdom)
B1Y8C9
 Bacteria (superkingdom)

 11%|█████████████████▏                                                                                                                                    | 147/1281 [00:28<03:40,  5.15it/s]

M5SYZ1
 Bacteria (superkingdom)
Q6HM26
 Bacteria (superkingdom)

 12%|█████████████████▍                                                                                                                                    | 149/1281 [00:29<03:39,  5.15it/s]

A0A379A0S9
 Bacteria (superkingdom)
A0A101DCS3
 Archaea (superkingdom)

 12%|█████████████████▋                                                                                                                                    | 151/1281 [00:29<03:38,  5.17it/s]

A0A1Y3U5V2
 Bacteria (superkingdom)
A0A202B535
 Bacteria (superkingdom)

 12%|█████████████████▉                                                                                                                                    | 153/1281 [00:29<03:38,  5.17it/s]

F8E6R1
 Bacteria (superkingdom)
Q6ND36
 Bacteria (superkingdom)

 12%|██████████████████▏                                                                                                                                   | 155/1281 [00:30<03:37,  5.18it/s]

A0A8H6K7L7
 Eukaryota (superkingdom)
Q7NCB8
 Bacteria (superkingdom)

 12%|██████████████████▍                                                                                                                                   | 157/1281 [00:30<03:36,  5.18it/s]

A0A369MRW6
 Bacteria (superkingdom)
C9RS76
 Bacteria (superkingdom)

 12%|██████████████████▌                                                                                                                                   | 159/1281 [00:30<03:38,  5.12it/s]

A3U857
 Bacteria (superkingdom)
A0A127PIQ9
 Bacteria (superkingdom)

 13%|██████████████████▊                                                                                                                                   | 161/1281 [00:31<03:38,  5.13it/s]

B8FGW0
 Bacteria (superkingdom)
A0A060JMP6
 Bacteria (superkingdom)

 13%|███████████████████                                                                                                                                   | 163/1281 [00:31<03:38,  5.13it/s]

D5V7B3
 Bacteria (superkingdom)
A0A494JB70
 Bacteria (superkingdom)

 13%|███████████████████▎                                                                                                                                  | 165/1281 [00:32<03:37,  5.13it/s]

A0A5M8QF12
 Bacteria (superkingdom)
A0A8G2F3G4
 Bacteria (superkingdom)

 13%|███████████████████▌                                                                                                                                  | 167/1281 [00:32<03:36,  5.15it/s]

J7L3W8
 Bacteria (superkingdom)
G0JRG9
 Bacteria (superkingdom)

 13%|███████████████████▊                                                                                                                                  | 169/1281 [00:32<03:35,  5.15it/s]

D3DJN2
 Bacteria (superkingdom)
A0A1Y2JH43
 Bacteria (superkingdom)

 13%|████████████████████                                                                                                                                  | 171/1281 [00:33<03:34,  5.18it/s]

Q1L727
 Eukaryota (superkingdom)
A0A7T2S0Z6
 Bacteria (superkingdom)

 14%|████████████████████▎                                                                                                                                 | 173/1281 [00:33<03:33,  5.20it/s]

A0A315S845
 Bacteria (superkingdom)
A0A2S6H6B7
 Bacteria (superkingdom)

 14%|████████████████████▍                                                                                                                                 | 175/1281 [00:34<03:32,  5.20it/s]

A0A1J5NTP7
 Bacteria (superkingdom)
A0A0E3QY86
 Archaea (superkingdom)

 14%|████████████████████▋                                                                                                                                 | 177/1281 [00:34<03:32,  5.19it/s]

A0A096EEV9
 Bacteria (superkingdom)
A0A380S5X4
 Bacteria (superkingdom)

 14%|████████████████████▉                                                                                                                                 | 179/1281 [00:34<03:32,  5.18it/s]

B8ZYW3
 Archaea (superkingdom)
A0A2S8GEJ5
 Bacteria (superkingdom)

 14%|█████████████████████▏                                                                                                                                | 181/1281 [00:35<03:31,  5.19it/s]

A0A248TDF2
 Bacteria (superkingdom)
B2GFN1
 Bacteria (superkingdom)

 14%|█████████████████████▍                                                                                                                                | 183/1281 [00:35<03:31,  5.20it/s]

U1PPI7
 Archaea (superkingdom)
C7LW88
 Bacteria (superkingdom)

 14%|█████████████████████▋                                                                                                                                | 185/1281 [00:35<03:30,  5.20it/s]

G3A431
 Bacteria (superkingdom)
A0A066ZTE4
 Bacteria (superkingdom)

 15%|█████████████████████▉                                                                                                                                | 187/1281 [00:36<03:30,  5.20it/s]

L7CG99
 Bacteria (superkingdom)
S0ET45
 Bacteria (superkingdom)

 15%|██████████████████████▏                                                                                                                               | 189/1281 [00:36<03:31,  5.17it/s]

A0A178TA08
 Bacteria (superkingdom)
H1XV27
 Bacteria (superkingdom)

 15%|██████████████████████▎                                                                                                                               | 191/1281 [00:37<03:32,  5.14it/s]

A0A6M3ZJI1
 Bacteria (superkingdom)
U5DEY6
 Bacteria (superkingdom)

 15%|██████████████████████▌                                                                                                                               | 193/1281 [00:37<03:33,  5.10it/s]

H6LFQ2
 Bacteria (superkingdom)
Q6CRN0
 Eukaryota (superkingdom)

 15%|██████████████████████▊                                                                                                                               | 195/1281 [00:37<03:30,  5.16it/s]

A0A4Q2EAG7
 Bacteria (superkingdom)
A0A1J5NNB8
 Bacteria (superkingdom)

 15%|███████████████████████                                                                                                                               | 197/1281 [00:38<03:29,  5.16it/s]

E3I393
 Bacteria (superkingdom)
A0A243SC06
 Bacteria (superkingdom)

 16%|███████████████████████▎                                                                                                                              | 199/1281 [00:38<03:29,  5.16it/s]

D4F313
 Bacteria (superkingdom)
W0F0I7
 Bacteria (superkingdom)

 16%|███████████████████████▌                                                                                                                              | 201/1281 [00:39<03:29,  5.17it/s]

A9B874
 Bacteria (superkingdom)
A1D2Y5
 Eukaryota (superkingdom)

 16%|███████████████████████▊                                                                                                                              | 203/1281 [00:39<03:28,  5.18it/s]

T2J0N1
 Bacteria (superkingdom)
Q2FQT3
 Archaea (superkingdom)

 16%|████████████████████████                                                                                                                              | 205/1281 [00:39<03:28,  5.17it/s]

A0A075WG29
 Archaea (superkingdom)
A0A979GQ79
 Bacteria (superkingdom)

 16%|████████████████████████▏                                                                                                                             | 207/1281 [00:40<03:28,  5.15it/s]

A0A381CAY8
 Bacteria (superkingdom)
A0A2G3DSU6
 Bacteria (superkingdom)

 16%|████████████████████████▍                                                                                                                             | 209/1281 [00:40<03:27,  5.18it/s]

A0A168EVK8
 Bacteria (superkingdom)
A0A094W9G3
 Bacteria (superkingdom)

 16%|████████████████████████▋                                                                                                                             | 211/1281 [00:41<03:26,  5.18it/s]

A0A4R3NVT3
 Bacteria (superkingdom)
W0DYY3
 Bacteria (superkingdom)

 17%|█████████████████████████                                                                                                                             | 214/1281 [00:41<03:29,  5.10it/s]

G8JTW0
 Eukaryota (superkingdom)
A0A4P6UIK6
 Bacteria (superkingdom)

 17%|█████████████████████████▎                                                                                                                            | 216/1281 [00:42<03:24,  5.21it/s]

I9P003
 Bacteria (superkingdom)
G2T1Y3
 Bacteria (superkingdom)

 17%|█████████████████████████▌                                                                                                                            | 218/1281 [00:42<03:19,  5.32it/s]

B8EMQ8
 Bacteria (superkingdom)
I6Z905
 Bacteria (superkingdom)

 17%|█████████████████████████▊                                                                                                                            | 220/1281 [00:42<03:16,  5.41it/s]

E0TCV4
 Bacteria (superkingdom)
A3XNG6
 Bacteria (superkingdom)

 17%|█████████████████████████▉                                                                                                                            | 222/1281 [00:43<03:13,  5.46it/s]

A0A087MGU4
 Bacteria (superkingdom)
A2BUP4
 Bacteria (superkingdom)

 17%|██████████████████████████▏                                                                                                                           | 224/1281 [00:43<03:16,  5.39it/s]

A0A562S8V2
 Bacteria (superkingdom)
A0A495DND0
 Bacteria (superkingdom)

 18%|██████████████████████████▍                                                                                                                           | 226/1281 [00:43<03:13,  5.45it/s]

A0A0S2FHD7
 Bacteria (superkingdom)
F3QPR6
 Bacteria (superkingdom)

 18%|██████████████████████████▋                                                                                                                           | 228/1281 [00:44<03:11,  5.51it/s]

A0A063Y394
 Bacteria (superkingdom)
F6G5I9
 Bacteria (superkingdom)

 18%|██████████████████████████▉                                                                                                                           | 230/1281 [00:44<03:09,  5.55it/s]

A0A323UDG5
 Bacteria (superkingdom)
A0A0G9HEC5
 Bacteria (superkingdom)

 18%|███████████████████████████▏                                                                                                                          | 232/1281 [00:45<03:09,  5.55it/s]

B8FDY8
 Bacteria (superkingdom)
Q5KPM5
 Eukaryota (superkingdom)

 18%|███████████████████████████▍                                                                                                                          | 234/1281 [00:45<03:10,  5.49it/s]

A0A147EQL9
 Bacteria (superkingdom)
A0A854Q6X9
 Eukaryota (superkingdom)

 18%|███████████████████████████▋                                                                                                                          | 236/1281 [00:45<03:09,  5.52it/s]

C3X1J1
 Bacteria (superkingdom)
A0A5B2V3B9
 Bacteria (superkingdom)

 19%|███████████████████████████▊                                                                                                                          | 238/1281 [00:46<03:10,  5.49it/s]

A0A258FS85
 Bacteria (superkingdom)
A0A7T2W1B3
 Bacteria (superkingdom)

 19%|████████████████████████████                                                                                                                          | 240/1281 [00:46<03:09,  5.49it/s]

A0A060UN76
 Bacteria (superkingdom)
G0JRQ3
 Bacteria (superkingdom)

 19%|████████████████████████████▎                                                                                                                         | 242/1281 [00:46<03:11,  5.43it/s]

D5UD26
 Bacteria (superkingdom)
G2ZN72
 Bacteria (superkingdom)

 19%|████████████████████████████▌                                                                                                                         | 244/1281 [00:47<03:09,  5.48it/s]

A0AA46Q839
 Bacteria (superkingdom)
A5UJR1
 Archaea (superkingdom)

 19%|████████████████████████████▊                                                                                                                         | 246/1281 [00:47<03:17,  5.24it/s]

L1INN6
 Eukaryota (superkingdom)
C1F584
 Bacteria (superkingdom)

 19%|█████████████████████████████                                                                                                                         | 248/1281 [00:48<03:21,  5.12it/s]

C5LAG4
 Eukaryota (superkingdom)
A0A2A2MCP3
 Bacteria (superkingdom)

 20%|█████████████████████████████▎                                                                                                                        | 250/1281 [00:48<03:22,  5.09it/s]

B1Y6V4
 Bacteria (superkingdom)
A0A1G6ABK5
 Bacteria (superkingdom)

 20%|█████████████████████████████▌                                                                                                                        | 252/1281 [00:48<03:19,  5.16it/s]

A0A6A1TYJ4
 Bacteria (superkingdom)
A0A2T4UWF1
 Bacteria (superkingdom)

 20%|█████████████████████████████▋                                                                                                                        | 253/1281 [00:49<03:17,  5.21it/s]

V4AP67
 Eukaryota (superkingdom)

 20%|█████████████████████████████▊                                                                                                                        | 255/1281 [00:49<03:16,  5.21it/s]

A0A173R3W6
 Bacteria (superkingdom)
C7NND3
 Archaea (superkingdom)

 20%|██████████████████████████████                                                                                                                        | 257/1281 [00:49<03:15,  5.24it/s]

B0DFJ4
 Eukaryota (superkingdom)
A0A3E2VY88
 Bacteria (superkingdom)

 20%|██████████████████████████████▎                                                                                                                       | 259/1281 [00:50<03:17,  5.17it/s]

R1EDV9
 Eukaryota (superkingdom)
J1L5M8
 Archaea (superkingdom)

 20%|██████████████████████████████▌                                                                                                                       | 261/1281 [00:50<03:16,  5.18it/s]

D7G265
 Eukaryota (superkingdom)
Q8ERT9
 Bacteria (superkingdom)

 21%|██████████████████████████████▊                                                                                                                       | 263/1281 [00:51<03:13,  5.25it/s]

I4D6Z9
 Bacteria (superkingdom)
A0A4R6DFU8
 Bacteria (superkingdom)

 21%|███████████████████████████████                                                                                                                       | 265/1281 [00:51<03:12,  5.27it/s]

A0A060URC3
 Bacteria (superkingdom)
D2BIB2
 Bacteria (superkingdom)

 21%|███████████████████████████████▎                                                                                                                      | 267/1281 [00:51<03:10,  5.31it/s]

F5ISF6
 Bacteria (superkingdom)
A5CRL2
 Bacteria (superkingdom)

 21%|███████████████████████████████▍                                                                                                                      | 269/1281 [00:52<03:09,  5.33it/s]

A0A6G9XJV9
 Bacteria (superkingdom)
Q59UP8
 Eukaryota (superkingdom)

 21%|███████████████████████████████▋                                                                                                                      | 271/1281 [00:52<03:08,  5.36it/s]

A0A6N4SPH9
 Bacteria (superkingdom)
I0HGY4
 Bacteria (superkingdom)

 21%|███████████████████████████████▉                                                                                                                      | 273/1281 [00:52<03:07,  5.37it/s]

X5DX97
 Bacteria (superkingdom)
L1J6I4
 Eukaryota (superkingdom)

 21%|████████████████████████████████▏                                                                                                                     | 275/1281 [00:53<03:05,  5.41it/s]

I1DSU5
 Bacteria (superkingdom)
B9L7N1
 Bacteria (superkingdom)

 22%|████████████████████████████████▍                                                                                                                     | 277/1281 [00:53<03:07,  5.36it/s]

Q1Z4I4
 Bacteria (superkingdom)
Q21CP1
 Bacteria (superkingdom)

 22%|████████████████████████████████▋                                                                                                                     | 279/1281 [00:54<03:06,  5.38it/s]

A0A165MFD1
 Bacteria (superkingdom)
V4CRP5
 Eukaryota (superkingdom)

 22%|████████████████████████████████▉                                                                                                                     | 281/1281 [00:54<03:02,  5.47it/s]

Q7S5K0
 Eukaryota (superkingdom)
A0A071MMV1
 Bacteria (superkingdom)

 22%|█████████████████████████████████▏                                                                                                                    | 283/1281 [00:54<03:00,  5.52it/s]

A0A149RYW7
 Bacteria (superkingdom)
A0A7G5EC77
 Bacteria (superkingdom)

 22%|█████████████████████████████████▎                                                                                                                    | 285/1281 [00:55<02:58,  5.57it/s]

A0A1W2GZ82
 Bacteria (superkingdom)
A0A7U3XVQ4
 Bacteria (superkingdom)

 22%|█████████████████████████████████▌                                                                                                                    | 287/1281 [00:55<02:56,  5.62it/s]

A0A071M4L5
 Bacteria (superkingdom)
U5C2K4
 Bacteria (superkingdom)

 23%|█████████████████████████████████▊                                                                                                                    | 289/1281 [00:56<02:54,  5.67it/s]

A0A248LNW8
 Bacteria (superkingdom)
L8H844
 Eukaryota (superkingdom)

 23%|█████████████████████████████████▉                                                                                                                    | 290/1281 [00:56<03:25,  4.83it/s]

A0A149V596
 Bacteria (superkingdom)
S9QZ09
 Bacteria (superkingdom)

 23%|██████████████████████████████████▏                                                                                                                   | 292/1281 [00:56<03:19,  4.95it/s]

B1ZSW9
 Bacteria (superkingdom)
D2BUJ8
 Bacteria (superkingdom)

 23%|██████████████████████████████████▍                                                                                                                   | 294/1281 [00:57<03:15,  5.05it/s]

A0A9Q8L398
 Bacteria (superkingdom)
M5S735
 Bacteria (superkingdom)

 23%|██████████████████████████████████▋                                                                                                                   | 296/1281 [00:57<03:13,  5.10it/s]

Q6ARH0
 Bacteria (superkingdom)
K6W5X0
 Bacteria (superkingdom)

 23%|██████████████████████████████████▉                                                                                                                   | 298/1281 [00:57<03:11,  5.13it/s]

G0JRG6
 Bacteria (superkingdom)
A0A6H9FYW4
 Bacteria (superkingdom)

 23%|███████████████████████████████████▏                                                                                                                  | 300/1281 [00:58<03:10,  5.16it/s]

A0A0S4WFM4
 Bacteria (superkingdom)
A0A101HKN9
 Bacteria (superkingdom)

 24%|███████████████████████████████████▎                                                                                                                  | 302/1281 [00:58<03:11,  5.11it/s]

Q9REX3
 Bacteria (superkingdom)
F0S3Z6
 Bacteria (superkingdom)

 24%|███████████████████████████████████▌                                                                                                                  | 304/1281 [00:59<03:10,  5.13it/s]

A8NAG3
 Eukaryota (superkingdom)
C6LBD3
 Bacteria (superkingdom)

 24%|███████████████████████████████████▊                                                                                                                  | 306/1281 [00:59<03:12,  5.06it/s]

A0A149U2G9
 Bacteria (superkingdom)
V4REY8
 Bacteria (superkingdom)

 24%|████████████████████████████████████                                                                                                                  | 308/1281 [00:59<03:10,  5.10it/s]

A0A0H3H4I7
 Bacteria (superkingdom)
A8N2H6
 Eukaryota (superkingdom)

 24%|████████████████████████████████████▎                                                                                                                 | 310/1281 [01:00<03:09,  5.13it/s]

S0APH6
 Archaea (superkingdom)
A0A017SYR8
 Bacteria (superkingdom)

 24%|████████████████████████████████████▌                                                                                                                 | 312/1281 [01:00<03:08,  5.14it/s]

A0A1B9MZ78
 Bacteria (superkingdom)
E4T3F3
 Bacteria (superkingdom)

 25%|████████████████████████████████████▊                                                                                                                 | 314/1281 [01:00<03:07,  5.14it/s]

D7E934
 Archaea (superkingdom)
A0A0M3AB44
 Bacteria (superkingdom)

 25%|█████████████████████████████████████                                                                                                                 | 316/1281 [01:01<03:07,  5.16it/s]

A9WHW6
 Bacteria (superkingdom)
A0A5M4AUM9
 Bacteria (superkingdom)

 25%|█████████████████████████████████████▏                                                                                                                | 318/1281 [01:01<03:06,  5.16it/s]

A0A1X4GBG2
 Bacteria (superkingdom)
I4D1H5
 Bacteria (superkingdom)

 25%|█████████████████████████████████████▍                                                                                                                | 320/1281 [01:02<03:06,  5.15it/s]

A0A0E3QYF3
 Archaea (superkingdom)
B0CQX4
 Eukaryota (superkingdom)

 25%|█████████████████████████████████████▋                                                                                                                | 322/1281 [01:02<03:05,  5.16it/s]

A0A378YR15
 Bacteria (superkingdom)
A0A495D4X4
 Bacteria (superkingdom)

 25%|█████████████████████████████████████▉                                                                                                                | 324/1281 [01:02<03:05,  5.17it/s]

A0A076PL76
 Bacteria (superkingdom)
Q1YDY7
 Bacteria (superkingdom)

 25%|██████████████████████████████████████▏                                                                                                               | 326/1281 [01:03<03:05,  5.16it/s]

A0A3E2UCG9
 Bacteria (superkingdom)
A0A2K3DPU7
 Eukaryota (superkingdom)

 26%|██████████████████████████████████████▍                                                                                                               | 328/1281 [01:03<03:06,  5.12it/s]

A0A3R9Q7C4
 Bacteria (superkingdom)
V5U2Z4
 Bacteria (superkingdom)

 26%|██████████████████████████████████████▋                                                                                                               | 330/1281 [01:04<03:05,  5.14it/s]

K9P718
 Bacteria (superkingdom)
M1V7W3
 Eukaryota (superkingdom)

 26%|██████████████████████████████████████▉                                                                                                               | 332/1281 [01:04<03:04,  5.15it/s]

Q6LKC8
 Bacteria (superkingdom)
E5Y789
 Bacteria (superkingdom)

 26%|███████████████████████████████████████                                                                                                               | 334/1281 [01:04<03:03,  5.15it/s]

J9Z839
 Bacteria (superkingdom)
A0A1G7VM92
 Bacteria (superkingdom)

 26%|███████████████████████████████████████▎                                                                                                              | 336/1281 [01:05<03:03,  5.16it/s]

K9Z0D3
 Bacteria (superkingdom)
A0A482TED1
 Archaea (superkingdom)

 26%|███████████████████████████████████████▌                                                                                                              | 338/1281 [01:05<03:02,  5.17it/s]

R1EGK6
 Eukaryota (superkingdom)
J1ASR8
 Archaea (superkingdom)

 27%|███████████████████████████████████████▊                                                                                                              | 340/1281 [01:06<03:02,  5.17it/s]

A0A7U4E420
 Bacteria (superkingdom)
K9YR86
 Bacteria (superkingdom)

 27%|████████████████████████████████████████                                                                                                              | 342/1281 [01:06<03:03,  5.13it/s]

A8PXT8
 Eukaryota (superkingdom)
A0A0U1NJW3
 Bacteria (superkingdom)

 27%|████████████████████████████████████████▎                                                                                                             | 344/1281 [01:06<03:00,  5.18it/s]

B8FL88
 Bacteria (superkingdom)
A2CCK1
 Bacteria (superkingdom)

 27%|████████████████████████████████████████▌                                                                                                             | 346/1281 [01:07<03:00,  5.19it/s]

D6TFE1
 Bacteria (superkingdom)
A0A2H4U5R1
 Archaea (superkingdom)

 27%|████████████████████████████████████████▋                                                                                                             | 348/1281 [01:07<02:59,  5.20it/s]

I2GD40
 Bacteria (superkingdom)
A0A060HFT5
 Archaea (superkingdom)

 27%|████████████████████████████████████████▉                                                                                                             | 350/1281 [01:07<02:58,  5.21it/s]

B1Y842
 Bacteria (superkingdom)
A0A0X8NXA9
 Bacteria (superkingdom)

 27%|█████████████████████████████████████████▏                                                                                                            | 352/1281 [01:08<03:00,  5.14it/s]

A0A0A2A5X1
 Bacteria (superkingdom)
A0A318FY98
 Bacteria (superkingdom)

 28%|█████████████████████████████████████████▍                                                                                                            | 354/1281 [01:08<02:59,  5.16it/s]

Q7V4T8
 Bacteria (superkingdom)
A0A1A0DHK0
 Bacteria (superkingdom)

 28%|█████████████████████████████████████████▋                                                                                                            | 356/1281 [01:09<02:59,  5.16it/s]

C1A872
 Bacteria (superkingdom)
A0A395VB65
 Bacteria (superkingdom)

 28%|█████████████████████████████████████████▉                                                                                                            | 358/1281 [01:09<02:58,  5.17it/s]

A7MFK3
 Bacteria (superkingdom)
J4KM12
 Eukaryota (superkingdom)

 28%|██████████████████████████████████████████▏                                                                                                           | 360/1281 [01:09<02:58,  5.17it/s]

A1SY01
 Bacteria (superkingdom)
A0A1H4DJ49
 Bacteria (superkingdom)

 28%|██████████████████████████████████████████▍                                                                                                           | 362/1281 [01:10<02:57,  5.18it/s]

A0A9R0NTP8
 Bacteria (superkingdom)
A3PAY4
 Bacteria (superkingdom)

 28%|██████████████████████████████████████████▌                                                                                                           | 364/1281 [01:10<02:57,  5.16it/s]

B4CV94
 Bacteria (superkingdom)
A2C095
 Bacteria (superkingdom)

 29%|██████████████████████████████████████████▊                                                                                                           | 366/1281 [01:11<02:56,  5.19it/s]

Q2HD43
 Eukaryota (superkingdom)
A0A836M2B6
 Bacteria (superkingdom)

 29%|███████████████████████████████████████████                                                                                                           | 368/1281 [01:11<02:58,  5.12it/s]

H6RWK9
 Bacteria (superkingdom)
A0A087EQK8
 Bacteria (superkingdom)

 29%|███████████████████████████████████████████▎                                                                                                          | 370/1281 [01:11<02:57,  5.13it/s]

A0A1I0AQM4
 Bacteria (superkingdom)
L7CG11
 Bacteria (superkingdom)

 29%|███████████████████████████████████████████▌                                                                                                          | 372/1281 [01:12<02:58,  5.10it/s]

A0A248LNK5
 Bacteria (superkingdom)
B7FTM9
 Eukaryota (superkingdom)

 29%|███████████████████████████████████████████▊                                                                                                          | 374/1281 [01:12<02:56,  5.15it/s]

L0K9M1
 Bacteria (superkingdom)
I4D6Z7
 Bacteria (superkingdom)

 29%|████████████████████████████████████████████                                                                                                          | 376/1281 [01:12<02:56,  5.12it/s]

A0A2K1RA81
 Eukaryota (superkingdom)
Q2WBF7
 Bacteria (superkingdom)

 30%|████████████████████████████████████████████▎                                                                                                         | 378/1281 [01:13<02:56,  5.11it/s]

A0A1B9BUU6
 Bacteria (superkingdom)
A0A2S0JW39
 Bacteria (superkingdom)

 30%|████████████████████████████████████████████▍                                                                                                         | 380/1281 [01:13<02:55,  5.14it/s]

A0A2S5YID7
 Bacteria (superkingdom)
B3PIH2
 Bacteria (superkingdom)

 30%|████████████████████████████████████████████▋                                                                                                         | 382/1281 [01:14<02:53,  5.18it/s]

U3P8G1
 Bacteria (superkingdom)
C9R9J0
 Bacteria (superkingdom)

 30%|████████████████████████████████████████████▉                                                                                                         | 384/1281 [01:14<02:53,  5.16it/s]

A8AC17
 Archaea (superkingdom)
F0YLV7
 Eukaryota (superkingdom)

 30%|█████████████████████████████████████████████▏                                                                                                        | 386/1281 [01:14<02:53,  5.16it/s]

A0A1D3GAE9
 Bacteria (superkingdom)
C1MHX0
 Eukaryota (superkingdom)

 30%|█████████████████████████████████████████████▍                                                                                                        | 388/1281 [01:15<02:52,  5.17it/s]

A0A1H4KAQ7
 Bacteria (superkingdom)
A0A2T4XZC1
 Bacteria (superkingdom)

 30%|█████████████████████████████████████████████▋                                                                                                        | 390/1281 [01:15<02:52,  5.17it/s]

A1B3N0
 Bacteria (superkingdom)
C7LW87
 Bacteria (superkingdom)

 31%|█████████████████████████████████████████████▉                                                                                                        | 392/1281 [01:16<02:52,  5.14it/s]

A1SZ12
 Bacteria (superkingdom)
A0A2T2Y0D5
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████████▏                                                                                                       | 394/1281 [01:16<02:52,  5.15it/s]

A0A1H8D0R8
 Bacteria (superkingdom)
A0A2S5V2F6
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████████▎                                                                                                       | 396/1281 [01:16<02:50,  5.18it/s]

G3IYW2
 Bacteria (superkingdom)
F5L8M7
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████████▌                                                                                                       | 398/1281 [01:17<02:50,  5.17it/s]

C7BJG7
 Bacteria (superkingdom)
E4U5Z1
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████████▊                                                                                                       | 400/1281 [01:17<02:50,  5.17it/s]

A0A1B9K8L2
 Bacteria (superkingdom)
A0A2S5WMT7
 Bacteria (superkingdom)

 31%|███████████████████████████████████████████████                                                                                                       | 402/1281 [01:18<02:51,  5.11it/s]

A0A0D2UPA8
 Eukaryota (superkingdom)
A0A161SKF4
 Bacteria (superkingdom)

 32%|███████████████████████████████████████████████▎                                                                                                      | 404/1281 [01:18<02:50,  5.14it/s]

B4D7W2
 Bacteria (superkingdom)
A0A1H3WA00
 Bacteria (superkingdom)

 32%|███████████████████████████████████████████████▌                                                                                                      | 406/1281 [01:18<02:49,  5.16it/s]

C1D6X6
 Bacteria (superkingdom)
A0A4D6KHD1
 Archaea (superkingdom)

 32%|███████████████████████████████████████████████▊                                                                                                      | 408/1281 [01:19<02:49,  5.16it/s]

Q488X2
 Bacteria (superkingdom)
A9V5W4
 Eukaryota (superkingdom)

 32%|████████████████████████████████████████████████                                                                                                      | 410/1281 [01:19<02:49,  5.15it/s]

A0A5M4ATH9
 Bacteria (superkingdom)
E4TRS4
 Bacteria (superkingdom)

 32%|████████████████████████████████████████████████▏                                                                                                     | 412/1281 [01:19<02:49,  5.12it/s]

A0A011U1K7
 Bacteria (superkingdom)
C7R314
 Bacteria (superkingdom)

 32%|████████████████████████████████████████████████▍                                                                                                     | 414/1281 [01:20<02:48,  5.15it/s]

A0A077EFU9
 Bacteria (superkingdom)
A0A0A2A0Y9
 Bacteria (superkingdom)

 32%|████████████████████████████████████████████████▋                                                                                                     | 416/1281 [01:20<02:47,  5.17it/s]

A0A0D8BQX6
 Bacteria (superkingdom)
A0A0L0S493
 Eukaryota (superkingdom)

 33%|████████████████████████████████████████████████▉                                                                                                     | 418/1281 [01:21<02:48,  5.11it/s]

A0A328Q6M1
 Archaea (superkingdom)
A0A016XCG9
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████████▏                                                                                                    | 420/1281 [01:21<02:47,  5.15it/s]

B7FSA7
 Eukaryota (superkingdom)
G0AFH4
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████████▍                                                                                                    | 422/1281 [01:21<02:46,  5.15it/s]

A0A177W826
 Eukaryota (superkingdom)
A0A2S8GF54
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████████▋                                                                                                    | 424/1281 [01:22<02:46,  5.14it/s]

Q1YDY8
 Bacteria (superkingdom)
Q5QVH2
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████████▉                                                                                                    | 426/1281 [01:22<02:45,  5.16it/s]

A3ZT81
 Bacteria (superkingdom)
A0AA35XZV0
 Bacteria (superkingdom)

 33%|██████████████████████████████████████████████████                                                                                                    | 428/1281 [01:23<02:45,  5.17it/s]

F4H924
 Bacteria (superkingdom)
K0NJH2
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████████▎                                                                                                   | 430/1281 [01:23<02:44,  5.18it/s]

A0A1V3SSW1
 Bacteria (superkingdom)
F2AUF4
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████████▌                                                                                                   | 432/1281 [01:23<02:43,  5.20it/s]

A6DN47
 Bacteria (superkingdom)
W8KM07
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████████▊                                                                                                   | 434/1281 [01:24<02:42,  5.20it/s]

A0A1X3RP39
 Bacteria (superkingdom)
A0A7S0KKL8
 Eukaryota (superkingdom)

 34%|███████████████████████████████████████████████████                                                                                                   | 436/1281 [01:24<02:43,  5.18it/s]

A0A318QZ80
 Bacteria (superkingdom)
K8VZC6
 Bacteria (superkingdom)

 34%|███████████████████████████████████████████████████▎                                                                                                  | 438/1281 [01:25<02:42,  5.19it/s]

A0A1B9JZS5
 Bacteria (superkingdom)
A0A2S6GKN5
 Bacteria (superkingdom)

 34%|███████████████████████████████████████████████████▌                                                                                                  | 440/1281 [01:25<02:42,  5.18it/s]

A0A4R2Z2K6
 Bacteria (superkingdom)
H1YCC3
 Bacteria (superkingdom)

 35%|███████████████████████████████████████████████████▊                                                                                                  | 442/1281 [01:25<02:41,  5.20it/s]

E1QIU3
 Bacteria (superkingdom)
A0A8H6MPB9
 Eukaryota (superkingdom)

 35%|███████████████████████████████████████████████████▉                                                                                                  | 444/1281 [01:26<02:40,  5.20it/s]

A0A369N7Y3
 Bacteria (superkingdom)
T2IEJ2
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████████▏                                                                                                 | 446/1281 [01:26<02:40,  5.19it/s]

H5UND3
 Bacteria (superkingdom)
Q1PX09
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████████▍                                                                                                 | 448/1281 [01:26<02:40,  5.18it/s]

A0A149TSA9
 Bacteria (superkingdom)
F2NGJ8
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████████▋                                                                                                 | 450/1281 [01:27<02:39,  5.22it/s]

A0A0E3SHQ9
 Archaea (superkingdom)
Q5FLR6
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████████▉                                                                                                 | 452/1281 [01:27<02:39,  5.18it/s]

S0EUS1
 Bacteria (superkingdom)
A0A369M386
 Bacteria (superkingdom)

 35%|█████████████████████████████████████████████████████▏                                                                                                | 454/1281 [01:28<02:42,  5.08it/s]

W0DZS7
 Bacteria (superkingdom)
A8MCL4
 Archaea (superkingdom)

 36%|█████████████████████████████████████████████████████▍                                                                                                | 456/1281 [01:28<02:40,  5.13it/s]

V3ZVE4
 Eukaryota (superkingdom)
O26757
 Archaea (superkingdom)

 36%|█████████████████████████████████████████████████████▋                                                                                                | 458/1281 [01:28<02:42,  5.07it/s]

A0A317FZW2
 Bacteria (superkingdom)
A0A085GI50
 Bacteria (superkingdom)

 36%|█████████████████████████████████████████████████████▊                                                                                                | 460/1281 [01:29<02:40,  5.11it/s]

A1ZGK6
 Bacteria (superkingdom)
G0IYI2
 Bacteria (superkingdom)

 36%|██████████████████████████████████████████████████████                                                                                                | 462/1281 [01:29<02:39,  5.13it/s]

A7S731
 Eukaryota (superkingdom)
A0A1U9YY82
 Bacteria (superkingdom)

 36%|██████████████████████████████████████████████████████▎                                                                                               | 464/1281 [01:30<02:38,  5.14it/s]

A0A328EMN2
 Bacteria (superkingdom)
A0A8E2UDJ3
 Bacteria (superkingdom)

 36%|██████████████████████████████████████████████████████▌                                                                                               | 466/1281 [01:30<02:41,  5.04it/s]

A0A2S5WUP6
 Bacteria (superkingdom)
A0A8H7P8U1
 Eukaryota (superkingdom)

 37%|██████████████████████████████████████████████████████▊                                                                                               | 468/1281 [01:30<02:39,  5.10it/s]

A0A257T7G4
 Bacteria (superkingdom)
B3MX93
 Eukaryota (superkingdom)

 37%|███████████████████████████████████████████████████████                                                                                               | 470/1281 [01:31<02:41,  5.03it/s]

A0A1G5W0P2
 Bacteria (superkingdom)
D4H2Y7
 Bacteria (superkingdom)

 37%|███████████████████████████████████████████████████████▎                                                                                              | 472/1281 [01:31<02:39,  5.07it/s]

A0A4P8HC89
 Bacteria (superkingdom)
Q7T070
 Eukaryota (superkingdom)

 37%|███████████████████████████████████████████████████████▌                                                                                              | 474/1281 [01:32<02:38,  5.09it/s]

F7NPQ3
 Bacteria (superkingdom)
B9SA70
 Eukaryota (superkingdom)

 37%|███████████████████████████████████████████████████████▋                                                                                              | 476/1281 [01:32<02:37,  5.10it/s]

Q9M6N7
 Eukaryota (superkingdom)
I7ZHW3
 Bacteria (superkingdom)

 37%|███████████████████████████████████████████████████████▉                                                                                              | 478/1281 [01:32<02:37,  5.10it/s]

F4XTK4
 Bacteria (superkingdom)
A4G1J2
 Bacteria (superkingdom)

 37%|████████████████████████████████████████████████████████▏                                                                                             | 480/1281 [01:33<02:37,  5.07it/s]

G7WFX4
 Bacteria (superkingdom)
B8JBH5
 Bacteria (superkingdom)

 38%|████████████████████████████████████████████████████████▍                                                                                             | 482/1281 [01:33<02:37,  5.08it/s]

D9QPC8
 Bacteria (superkingdom)
A0A4R7GKA0
 Bacteria (superkingdom)

 38%|████████████████████████████████████████████████████████▋                                                                                             | 484/1281 [01:34<02:36,  5.11it/s]

R9PMC6
 Bacteria (superkingdom)
A0A0E3LMT4
 Archaea (superkingdom)

 38%|████████████████████████████████████████████████████████▉                                                                                             | 486/1281 [01:34<02:35,  5.10it/s]

A0A511NGC7
 Bacteria (superkingdom)
E4NS62
 Archaea (superkingdom)

 38%|█████████████████████████████████████████████████████████▏                                                                                            | 488/1281 [01:34<02:34,  5.13it/s]

E4T3F7
 Bacteria (superkingdom)
M0D580
 Archaea (superkingdom)

 38%|█████████████████████████████████████████████████████████▍                                                                                            | 490/1281 [01:35<02:33,  5.16it/s]

J7J5E7
 Bacteria (superkingdom)
B1XZU2
 Bacteria (superkingdom)

 38%|█████████████████████████████████████████████████████████▌                                                                                            | 492/1281 [01:35<02:32,  5.18it/s]

A0A366IE34
 Bacteria (superkingdom)
A0A6U2BIY7
 Eukaryota (superkingdom)

 39%|█████████████████████████████████████████████████████████▊                                                                                            | 494/1281 [01:35<02:31,  5.21it/s]

Q9QXP0
 Eukaryota (superkingdom)
A0A424WAH3
 Bacteria (superkingdom)

 39%|██████████████████████████████████████████████████████████                                                                                            | 496/1281 [01:36<02:30,  5.22it/s]

A0A410K1J5
 Bacteria (superkingdom)
L1IHZ8
 Eukaryota (superkingdom)

 39%|██████████████████████████████████████████████████████████▎                                                                                           | 498/1281 [01:36<02:30,  5.19it/s]

I8TC71
 Bacteria (superkingdom)
A0A7U8C744
 Bacteria (superkingdom)

 39%|██████████████████████████████████████████████████████████▌                                                                                           | 500/1281 [01:37<02:32,  5.13it/s]

A8M670
 Bacteria (superkingdom)
A0A0S4VNK2
 Bacteria (superkingdom)

 39%|██████████████████████████████████████████████████████████▊                                                                                           | 502/1281 [01:37<02:31,  5.14it/s]

Q2SIR0
 Bacteria (superkingdom)
A0A5C4RNH5
 Bacteria (superkingdom)

 39%|███████████████████████████████████████████████████████████                                                                                           | 504/1281 [01:37<02:31,  5.13it/s]

A0A3E0X011
 Bacteria (superkingdom)
A0A0E3SP24
 Archaea (superkingdom)

 40%|███████████████████████████████████████████████████████████▎                                                                                          | 506/1281 [01:38<02:30,  5.14it/s]

E1IF27
 Bacteria (superkingdom)
Q2YBP7
 Bacteria (superkingdom)

 40%|███████████████████████████████████████████████████████████▍                                                                                          | 508/1281 [01:38<02:30,  5.15it/s]

A0A2S5WZU0
 Bacteria (superkingdom)
A0A172YBR4
 Bacteria (superkingdom)

 40%|███████████████████████████████████████████████████████████▋                                                                                          | 510/1281 [01:39<02:29,  5.14it/s]

A0A0K2STK6
 Eukaryota (superkingdom)
A0A2N6JV02
 Bacteria (superkingdom)

 40%|███████████████████████████████████████████████████████████▉                                                                                          | 512/1281 [01:39<02:29,  5.16it/s]

F0S0G1
 Bacteria (superkingdom)
A0A1C7EL50
 Bacteria (superkingdom)

 40%|████████████████████████████████████████████████████████████▏                                                                                         | 514/1281 [01:39<02:29,  5.14it/s]

Q18PF5
 Eukaryota (superkingdom)
A0A1I0C958
 Bacteria (superkingdom)

 40%|████████████████████████████████████████████████████████████▍                                                                                         | 516/1281 [01:40<02:27,  5.19it/s]

A0AA35XVN2
 Bacteria (superkingdom)
L8GGA0
 Eukaryota (superkingdom)

 40%|████████████████████████████████████████████████████████████▋                                                                                         | 518/1281 [01:40<02:26,  5.21it/s]

Q3AP28
 Bacteria (superkingdom)
D0MFE9
 Bacteria (superkingdom)

 41%|████████████████████████████████████████████████████████████▉                                                                                         | 520/1281 [01:40<02:26,  5.20it/s]

J9VXX9
 Eukaryota (superkingdom)
A0A166IS52
 Bacteria (superkingdom)

 41%|█████████████████████████████████████████████████████████████                                                                                         | 522/1281 [01:41<02:30,  5.04it/s]

F0J7D3
 Bacteria (superkingdom)
W7QG13
 Bacteria (superkingdom)

 41%|█████████████████████████████████████████████████████████████▎                                                                                        | 524/1281 [01:41<02:28,  5.08it/s]

A4BMY5
 Bacteria (superkingdom)
A6LV49
 Bacteria (superkingdom)

 41%|█████████████████████████████████████████████████████████████▌                                                                                        | 526/1281 [01:42<02:26,  5.15it/s]

Q1H483
 Bacteria (superkingdom)
A6M3G0
 Bacteria (superkingdom)

 41%|█████████████████████████████████████████████████████████████▊                                                                                        | 528/1281 [01:42<02:25,  5.18it/s]

E4T0A4
 Bacteria (superkingdom)
A0A3E2UHE6
 Bacteria (superkingdom)

 41%|██████████████████████████████████████████████████████████████                                                                                        | 530/1281 [01:42<02:24,  5.19it/s]

A0A174SD65
 Bacteria (superkingdom)
A0A855EH99
 Bacteria (superkingdom)

 42%|██████████████████████████████████████████████████████████████▎                                                                                       | 532/1281 [01:43<02:23,  5.21it/s]

C3YB74
 Eukaryota (superkingdom)
A0A074KZD8
 Bacteria (superkingdom)

 42%|██████████████████████████████████████████████████████████████▌                                                                                       | 534/1281 [01:43<02:23,  5.19it/s]

J0S2I0
 Archaea (superkingdom)
K9WSX4
 Bacteria (superkingdom)

 42%|██████████████████████████████████████████████████████████████▊                                                                                       | 536/1281 [01:44<02:23,  5.19it/s]

E8RLT5
 Bacteria (superkingdom)
Q2FS34
 Archaea (superkingdom)

 42%|██████████████████████████████████████████████████████████████▉                                                                                       | 538/1281 [01:44<02:23,  5.18it/s]

Q3Z7F9
 Bacteria (superkingdom)
Q2S8H9
 Bacteria (superkingdom)

 42%|███████████████████████████████████████████████████████████████▏                                                                                      | 540/1281 [01:44<02:23,  5.18it/s]

A0A060HN92
 Archaea (superkingdom)
E6ME92
 Bacteria (superkingdom)

 42%|███████████████████████████████████████████████████████████████▍                                                                                      | 542/1281 [01:45<02:23,  5.15it/s]

A0A172RYW3
 Bacteria (superkingdom)
L0FU80
 Bacteria (superkingdom)

 42%|███████████████████████████████████████████████████████████████▋                                                                                      | 544/1281 [01:45<02:24,  5.10it/s]

C8WZE0
 Bacteria (superkingdom)
A0A2S8F4W0
 Bacteria (superkingdom)

 43%|███████████████████████████████████████████████████████████████▉                                                                                      | 546/1281 [01:46<02:23,  5.13it/s]

A0A2C6C0X3
 Bacteria (superkingdom)
F3ZVV4
 Bacteria (superkingdom)

 43%|████████████████████████████████████████████████████████████████▏                                                                                     | 548/1281 [01:46<02:22,  5.15it/s]

A0A7R6PER3
 Bacteria (superkingdom)
A0A495WJM6
 Bacteria (superkingdom)

 43%|████████████████████████████████████████████████████████████████▍                                                                                     | 550/1281 [01:46<02:20,  5.19it/s]

A0A0B4DUR9
 Bacteria (superkingdom)
A0A251YU48
 Bacteria (superkingdom)

 43%|████████████████████████████████████████████████████████████████▋                                                                                     | 552/1281 [01:47<02:20,  5.18it/s]

A5D4I5
 Bacteria (superkingdom)
A0A2X2C038
 Bacteria (superkingdom)

 43%|████████████████████████████████████████████████████████████████▊                                                                                     | 554/1281 [01:47<02:20,  5.16it/s]

A0A2A2M8K7
 Bacteria (superkingdom)
D3FBG3
 Bacteria (superkingdom)

 43%|█████████████████████████████████████████████████████████████████                                                                                     | 556/1281 [01:47<02:21,  5.13it/s]

A0A2V4EA49
 Bacteria (superkingdom)
D0MFE8
 Bacteria (superkingdom)

 44%|█████████████████████████████████████████████████████████████████▎                                                                                    | 558/1281 [01:48<02:19,  5.17it/s]

Q3B6Q2
 Bacteria (superkingdom)
A0A1B9KID3
 Bacteria (superkingdom)

 44%|█████████████████████████████████████████████████████████████████▌                                                                                    | 560/1281 [01:48<02:19,  5.18it/s]

A0A9J9ES23
 Bacteria (superkingdom)
A0A3N2SFS2
 Bacteria (superkingdom)

 44%|█████████████████████████████████████████████████████████████████▊                                                                                    | 562/1281 [01:49<02:19,  5.15it/s]

Q0VLH1
 Bacteria (superkingdom)
A0A1U9Z147
 Bacteria (superkingdom)

 44%|██████████████████████████████████████████████████████████████████                                                                                    | 564/1281 [01:49<02:19,  5.14it/s]

Q0G2T1
 Bacteria (superkingdom)
A6GJF5
 Bacteria (superkingdom)

 44%|██████████████████████████████████████████████████████████████████▎                                                                                   | 566/1281 [01:49<02:18,  5.17it/s]

A0A059XXR1
 Bacteria (superkingdom)
A0A5J6WPP9
 Bacteria (superkingdom)

 44%|██████████████████████████████████████████████████████████████████▌                                                                                   | 568/1281 [01:50<02:17,  5.18it/s]

P41948
 Eukaryota (superkingdom)
L1IUV5
 Eukaryota (superkingdom)

 44%|██████████████████████████████████████████████████████████████████▋                                                                                   | 570/1281 [01:50<02:18,  5.15it/s]

A0A2W0GQV0
 Bacteria (superkingdom)
Q1K433
 Bacteria (superkingdom)

 45%|██████████████████████████████████████████████████████████████████▉                                                                                   | 572/1281 [01:51<02:17,  5.17it/s]

A0A4Y7XC43
 Bacteria (superkingdom)
D5AU98
 Bacteria (superkingdom)

 45%|███████████████████████████████████████████████████████████████████▏                                                                                  | 574/1281 [01:51<02:16,  5.17it/s]

E1QFA8
 Bacteria (superkingdom)
A0A075WBP9
 Archaea (superkingdom)

 45%|███████████████████████████████████████████████████████████████████▍                                                                                  | 576/1281 [01:51<02:16,  5.18it/s]

Q0BWD0
 Bacteria (superkingdom)
A0A1Y0HX98
 Bacteria (superkingdom)

 45%|███████████████████████████████████████████████████████████████████▋                                                                                  | 578/1281 [01:52<02:15,  5.19it/s]

A0A098S5Y7
 Bacteria (superkingdom)
Q0I445
 Bacteria (superkingdom)

 45%|███████████████████████████████████████████████████████████████████▉                                                                                  | 580/1281 [01:52<02:15,  5.18it/s]

A0A1E5BXA4
 Bacteria (superkingdom)
A0A2C9CK98
 Bacteria (superkingdom)

 45%|████████████████████████████████████████████████████████████████████▏                                                                                 | 582/1281 [01:52<02:15,  5.17it/s]

G4H971
 Bacteria (superkingdom)
A0A1I0BYN1
 Bacteria (superkingdom)

 46%|████████████████████████████████████████████████████████████████████▍                                                                                 | 584/1281 [01:53<02:14,  5.17it/s]

A0A330GB00
 Bacteria (superkingdom)
A0A2S8FR08
 Bacteria (superkingdom)

 46%|████████████████████████████████████████████████████████████████████▌                                                                                 | 586/1281 [01:53<02:14,  5.18it/s]

Q84KJ6
 Eukaryota (superkingdom)
A0A2S5WGI8
 Bacteria (superkingdom)

 46%|████████████████████████████████████████████████████████████████████▊                                                                                 | 588/1281 [01:54<02:13,  5.19it/s]

M2ALH9
 Bacteria (superkingdom)
A0A2K3DQF8
 Eukaryota (superkingdom)

 46%|█████████████████████████████████████████████████████████████████████                                                                                 | 590/1281 [01:54<02:13,  5.19it/s]

A0A8G2IZM3
 Bacteria (superkingdom)
F5Y3C1
 Bacteria (superkingdom)

 46%|█████████████████████████████████████████████████████████████████████▎                                                                                | 592/1281 [01:54<02:13,  5.18it/s]

A0A370FPU0
 Bacteria (superkingdom)
F5RGM7
 Bacteria (superkingdom)

 46%|█████████████████████████████████████████████████████████████████████▌                                                                                | 594/1281 [01:55<02:12,  5.17it/s]

A0A4R4K1P9
 Bacteria (superkingdom)
R8VWI7
 Bacteria (superkingdom)

 47%|█████████████████████████████████████████████████████████████████████▊                                                                                | 596/1281 [01:55<02:11,  5.20it/s]

A0A0A2AMW2
 Bacteria (superkingdom)
Q7Z1M1
 Eukaryota (superkingdom)

 47%|██████████████████████████████████████████████████████████████████████                                                                                | 598/1281 [01:56<02:11,  5.18it/s]

A0A414NWT8
 Bacteria (superkingdom)
A0A0P6VSR8
 Bacteria (superkingdom)

 47%|██████████████████████████████████████████████████████████████████████▎                                                                               | 600/1281 [01:56<02:11,  5.19it/s]

A0A0L0TDW1
 Eukaryota (superkingdom)
U3PCH5
 Bacteria (superkingdom)

 47%|██████████████████████████████████████████████████████████████████████▍                                                                               | 602/1281 [01:56<02:11,  5.18it/s]

W7QGE0
 Bacteria (superkingdom)
C5BWX7
 Bacteria (superkingdom)

 47%|██████████████████████████████████████████████████████████████████████▋                                                                               | 604/1281 [01:57<02:12,  5.12it/s]

A0A1B9M1A9
 Bacteria (superkingdom)
B8GGC3
 Archaea (superkingdom)

 47%|██████████████████████████████████████████████████████████████████████▉                                                                               | 606/1281 [01:57<02:11,  5.15it/s]

D6SPD1
 Bacteria (superkingdom)
A0A0H3DR67
 Bacteria (superkingdom)

 47%|███████████████████████████████████████████████████████████████████████▏                                                                              | 608/1281 [01:58<02:11,  5.13it/s]

A0A4R7VEK0
 Bacteria (superkingdom)
G4R7P1
 Bacteria (superkingdom)

 48%|███████████████████████████████████████████████████████████████████████▍                                                                              | 610/1281 [01:58<02:09,  5.17it/s]

A0A1M5ZVP9
 Bacteria (superkingdom)
A0A2S5Y0D3
 Bacteria (superkingdom)

 48%|███████████████████████████████████████████████████████████████████████▋                                                                              | 612/1281 [01:58<02:11,  5.09it/s]

I0ICG0
 Bacteria (superkingdom)
D0L8H3
 Bacteria (superkingdom)

 48%|███████████████████████████████████████████████████████████████████████▉                                                                              | 614/1281 [01:59<02:10,  5.11it/s]

A0A1B9LFW3
 Bacteria (superkingdom)
Q6ND34
 Bacteria (superkingdom)

 48%|████████████████████████████████████████████████████████████████████████▏                                                                             | 616/1281 [01:59<02:09,  5.13it/s]

A0A6H9GWG4
 Bacteria (superkingdom)
Q5UZ98
 Archaea (superkingdom)

 48%|████████████████████████████████████████████████████████████████████████▎                                                                             | 618/1281 [01:59<02:09,  5.13it/s]

A0A2S0P9T4
 Bacteria (superkingdom)
H2CDR5
 Bacteria (superkingdom)

 48%|████████████████████████████████████████████████████████████████████████▌                                                                             | 620/1281 [02:00<02:08,  5.15it/s]

T2KGT3
 Bacteria (superkingdom)
A0A088E6Q7
 Archaea (superkingdom)

 49%|████████████████████████████████████████████████████████████████████████▊                                                                             | 622/1281 [02:00<02:07,  5.15it/s]

A0A258HS77
 Bacteria (superkingdom)
E1V4T3
 Bacteria (superkingdom)

 49%|█████████████████████████████████████████████████████████████████████████                                                                             | 624/1281 [02:01<02:07,  5.15it/s]

B7GKP4
 Bacteria (superkingdom)
Q9QUT0
 Eukaryota (superkingdom)

 49%|█████████████████████████████████████████████████████████████████████████▎                                                                            | 626/1281 [02:01<02:06,  5.18it/s]

I3Z3H7
 Bacteria (superkingdom)
G7WCB6
 Bacteria (superkingdom)

 49%|█████████████████████████████████████████████████████████████████████████▌                                                                            | 628/1281 [02:01<02:07,  5.12it/s]

A0A1Y6GLJ1
 Bacteria (superkingdom)
A0A0S2DQB6
 Bacteria (superkingdom)

 49%|█████████████████████████████████████████████████████████████████████████▊                                                                            | 630/1281 [02:02<02:07,  5.12it/s]

Q6CRN1
 Eukaryota (superkingdom)
A0A401X433
 Bacteria (superkingdom)

 49%|██████████████████████████████████████████████████████████████████████████                                                                            | 632/1281 [02:02<02:06,  5.14it/s]

A7HT14
 Bacteria (superkingdom)
A0A009TDB1
 Bacteria (superkingdom)

 49%|██████████████████████████████████████████████████████████████████████████▏                                                                           | 634/1281 [02:03<02:05,  5.14it/s]

D4XSW0
 Bacteria (superkingdom)
B0SRS8
 Bacteria (superkingdom)

 50%|██████████████████████████████████████████████████████████████████████████▍                                                                           | 636/1281 [02:03<02:04,  5.18it/s]

A0A149QSR6
 Bacteria (superkingdom)
B1Y0E5
 Bacteria (superkingdom)

 50%|██████████████████████████████████████████████████████████████████████████▋                                                                           | 638/1281 [02:03<02:05,  5.13it/s]

Q7UGU7
 Bacteria (superkingdom)
A0A2S0Q8P1
 Bacteria (superkingdom)

 50%|██████████████████████████████████████████████████████████████████████████▉                                                                           | 640/1281 [02:04<02:05,  5.11it/s]

F0ZPL3
 Eukaryota (superkingdom)
A0A2T0GTU1
 Bacteria (superkingdom)

 50%|███████████████████████████████████████████████████████████████████████████▏                                                                          | 642/1281 [02:04<02:05,  5.10it/s]

I4CCD1
 Bacteria (superkingdom)
A0A9Q6P4A5
 Bacteria (superkingdom)

 50%|███████████████████████████████████████████████████████████████████████████▍                                                                          | 644/1281 [02:05<02:04,  5.12it/s]

A0A418VIJ8
 Bacteria (superkingdom)
C1MX19
 Eukaryota (superkingdom)

 50%|███████████████████████████████████████████████████████████████████████████▋                                                                          | 646/1281 [02:05<02:03,  5.14it/s]

A0A1B9BUZ8
 Bacteria (superkingdom)
K9W6F3
 Bacteria (superkingdom)

 51%|███████████████████████████████████████████████████████████████████████████▉                                                                          | 648/1281 [02:05<02:03,  5.14it/s]

Q1K8A3
 Eukaryota (superkingdom)
L8GFX3
 Eukaryota (superkingdom)

 51%|████████████████████████████████████████████████████████████████████████████                                                                          | 650/1281 [02:06<02:01,  5.18it/s]

A0A1G6ABL9
 Bacteria (superkingdom)
A0A087L0B9
 Bacteria (superkingdom)

 51%|████████████████████████████████████████████████████████████████████████████▎                                                                         | 652/1281 [02:06<02:00,  5.20it/s]

A0A073CP02
 Bacteria (superkingdom)
A0A0A1ZJU5
 Bacteria (superkingdom)

 51%|████████████████████████████████████████████████████████████████████████████▌                                                                         | 654/1281 [02:06<02:00,  5.20it/s]

A0A258HPP1
 Bacteria (superkingdom)
A0A149QAW7
 Bacteria (superkingdom)

 51%|████████████████████████████████████████████████████████████████████████████▊                                                                         | 656/1281 [02:07<01:59,  5.21it/s]

D2V6Q5
 Eukaryota (superkingdom)
A0A1X4G8K1
 Bacteria (superkingdom)

 51%|█████████████████████████████████████████████████████████████████████████████                                                                         | 658/1281 [02:07<01:59,  5.22it/s]

A0A067Z3S3
 Bacteria (superkingdom)
A0A8F5ZDT8
 Archaea (superkingdom)

 52%|█████████████████████████████████████████████████████████████████████████████▎                                                                        | 660/1281 [02:08<01:59,  5.20it/s]

A0A854QN45
 Eukaryota (superkingdom)
A0A2N7LCD7
 Bacteria (superkingdom)

 52%|█████████████████████████████████████████████████████████████████████████████▌                                                                        | 662/1281 [02:08<01:59,  5.20it/s]

G7WFX2
 Bacteria (superkingdom)
A0A7S4GNJ2
 Eukaryota (superkingdom)

 52%|█████████████████████████████████████████████████████████████████████████████▊                                                                        | 664/1281 [02:08<01:59,  5.15it/s]

A4G0C5
 Archaea (superkingdom)
A6VE60
 Bacteria (superkingdom)

 52%|█████████████████████████████████████████████████████████████████████████████▉                                                                        | 666/1281 [02:09<01:59,  5.17it/s]

A0A1S1HM83
 Bacteria (superkingdom)
A0A037ZJY5
 Bacteria (superkingdom)

 52%|██████████████████████████████████████████████████████████████████████████████▏                                                                       | 668/1281 [02:09<01:58,  5.18it/s]

N1WR17
 Bacteria (superkingdom)
Q2W5V2
 Bacteria (superkingdom)

 52%|██████████████████████████████████████████████████████████████████████████████▍                                                                       | 670/1281 [02:10<01:57,  5.20it/s]

A1VIM5
 Bacteria (superkingdom)
A0A1Y5E3E3
 Bacteria (superkingdom)

 52%|██████████████████████████████████████████████████████████████████████████████▋                                                                       | 672/1281 [02:10<01:58,  5.14it/s]

A0A1T4SFK4
 Bacteria (superkingdom)
A7RNC3
 Eukaryota (superkingdom)

 53%|██████████████████████████████████████████████████████████████████████████████▉                                                                       | 674/1281 [02:10<01:58,  5.11it/s]

M7XJ51
 Bacteria (superkingdom)
A0A399T909
 Bacteria (superkingdom)

 53%|███████████████████████████████████████████████████████████████████████████████▏                                                                      | 676/1281 [02:11<01:58,  5.11it/s]

A0A2N6P374
 Eukaryota (superkingdom)
H8L2Q4
 Bacteria (superkingdom)

 53%|███████████████████████████████████████████████████████████████████████████████▍                                                                      | 678/1281 [02:11<01:57,  5.13it/s]

D5EP68
 Bacteria (superkingdom)
E6SF19
 Bacteria (superkingdom)

 53%|███████████████████████████████████████████████████████████████████████████████▋                                                                      | 680/1281 [02:11<01:56,  5.15it/s]

A0A1T4SFY6
 Bacteria (superkingdom)
D3LBI0
 Bacteria (superkingdom)

 53%|███████████████████████████████████████████████████████████████████████████████▊                                                                      | 682/1281 [02:12<01:55,  5.19it/s]

E6W5C1
 Bacteria (superkingdom)
Q0VPH4
 Bacteria (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████████████                                                                      | 684/1281 [02:12<01:55,  5.19it/s]

K9WT03
 Bacteria (superkingdom)
L0KW14
 Archaea (superkingdom)

 54%|████████████████████████████████████████████████████████████████████████████████▎                                                                     | 686/1281 [02:13<01:54,  5.22it/s]

A0A4R8H081
 Bacteria (superkingdom)
A0A1B9N3H7
 Bacteria (superkingdom)

 54%|████████████████████████████████████████████████████████████████████████████████▌                                                                     | 688/1281 [02:13<01:53,  5.20it/s]

B0RC35
 Bacteria (superkingdom)
A0A420KGW4
 Bacteria (superkingdom)

 54%|████████████████████████████████████████████████████████████████████████████████▊                                                                     | 690/1281 [02:13<01:53,  5.22it/s]

A0A4R3NLV5
 Bacteria (superkingdom)
Q47K18
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████████████                                                                     | 692/1281 [02:14<01:54,  5.16it/s]

Q21P82
 Bacteria (superkingdom)
M1WRK6
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████████████▎                                                                    | 694/1281 [02:14<01:53,  5.17it/s]

A0A290XBB5
 Bacteria (superkingdom)
A0A6T9XUR2
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████████████▍                                                                    | 696/1281 [02:15<01:53,  5.13it/s]

A0A1J1JH03
 Bacteria (superkingdom)
I3R0S7
 Archaea (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████████████▋                                                                    | 698/1281 [02:15<01:53,  5.12it/s]

A9UR54
 Eukaryota (superkingdom)
A0A1G7H8X3
 Bacteria (superkingdom)

 55%|█████████████████████████████████████████████████████████████████████████████████▉                                                                    | 700/1281 [02:15<01:52,  5.14it/s]

A0A8G2F718
 Bacteria (superkingdom)
Q1H0G2
 Bacteria (superkingdom)

 55%|██████████████████████████████████████████████████████████████████████████████████▏                                                                   | 702/1281 [02:16<01:52,  5.17it/s]

D0LAL7
 Bacteria (superkingdom)
C7LQR9
 Bacteria (superkingdom)

 55%|██████████████████████████████████████████████████████████████████████████████████▍                                                                   | 704/1281 [02:16<01:51,  5.18it/s]

A0A1G5PWV0
 Bacteria (superkingdom)
K1K628
 Bacteria (superkingdom)

 55%|██████████████████████████████████████████████████████████████████████████████████▋                                                                   | 706/1281 [02:17<01:50,  5.19it/s]

B9SXC7
 Eukaryota (superkingdom)
G7WA28
 Bacteria (superkingdom)

 55%|██████████████████████████████████████████████████████████████████████████████████▉                                                                   | 708/1281 [02:17<01:50,  5.18it/s]

Q1IWN6
 Bacteria (superkingdom)
H6LKH9
 Bacteria (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████████████▏                                                                  | 710/1281 [02:17<01:50,  5.19it/s]

A0A1H7CU41
 Bacteria (superkingdom)
G8JUJ2
 Eukaryota (superkingdom)

 56%|███████████████████████████████████████████████████████████████████████████████████▎                                                                  | 712/1281 [02:18<01:49,  5.18it/s]

A0A081N2G5
 Bacteria (superkingdom)
A0A074ME37
 Bacteria (superkingdom)

 56%|███████████████████████████████████████████████████████████████████████████████████▌                                                                  | 714/1281 [02:18<01:49,  5.20it/s]

Q0VQH6
 Bacteria (superkingdom)
C8XB51
 Bacteria (superkingdom)

 56%|███████████████████████████████████████████████████████████████████████████████████▊                                                                  | 716/1281 [02:18<01:50,  5.13it/s]

A1VIG8
 Bacteria (superkingdom)
Q8GQS1
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████████████                                                                  | 718/1281 [02:19<01:50,  5.12it/s]

A0A1I7FBM5
 Bacteria (superkingdom)
A0A1M6ZMI3
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 720/1281 [02:19<01:49,  5.15it/s]

A0A482PLH3
 Bacteria (superkingdom)
A0RXK8
 Archaea (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 722/1281 [02:20<01:48,  5.15it/s]

D0KXQ0
 Bacteria (superkingdom)
Q8JI14
 Eukaryota (superkingdom)

 57%|████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 724/1281 [02:20<01:47,  5.17it/s]

A0A7T4WEP4
 Bacteria (superkingdom)
A0A4R3ZNW3
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████████████                                                                 | 726/1281 [02:20<01:46,  5.21it/s]

A0A074KY88
 Bacteria (superkingdom)
A0A6M3ZKU5
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                | 728/1281 [02:21<01:46,  5.21it/s]

M1SJL5
 Bacteria (superkingdom)
A0A1W9KSU5
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                | 730/1281 [02:21<01:45,  5.20it/s]

E3GI40
 Bacteria (superkingdom)
A0A369NYJ2
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                | 732/1281 [02:22<01:45,  5.21it/s]

A0AA92K392
 Bacteria (superkingdom)
O04161
 Eukaryota (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                | 734/1281 [02:22<01:44,  5.21it/s]

A9BQZ4
 Bacteria (superkingdom)
A0A6N2Z556
 Bacteria (superkingdom)

 57%|██████████████████████████████████████████████████████████████████████████████████████▏                                                               | 736/1281 [02:22<01:44,  5.22it/s]

A0A8H6NAG3
 Eukaryota (superkingdom)
A0A2T9X1V4
 Archaea (superkingdom)

 58%|██████████████████████████████████████████████████████████████████████████████████████▍                                                               | 738/1281 [02:23<01:44,  5.22it/s]

Q2J376
 Bacteria (superkingdom)
A0A0F5EZP7
 Bacteria (superkingdom)

 58%|██████████████████████████████████████████████████████████████████████████████████████▋                                                               | 740/1281 [02:23<01:43,  5.23it/s]

A0A7G5DK18
 Bacteria (superkingdom)
M9YAI9
 Bacteria (superkingdom)

 58%|██████████████████████████████████████████████████████████████████████████████████████▉                                                               | 742/1281 [02:23<01:42,  5.25it/s]

D2ZRW2
 Archaea (superkingdom)
G7UUY6
 Bacteria (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████████████                                                               | 744/1281 [02:24<01:42,  5.24it/s]

A0A8H4GS02
 Eukaryota (superkingdom)
A0A2T5IHP0
 Bacteria (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████████████▎                                                              | 746/1281 [02:24<01:42,  5.23it/s]

A0A165MAC2
 Bacteria (superkingdom)
A0A7S4LPS8
 Eukaryota (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████████████▌                                                              | 748/1281 [02:25<01:42,  5.22it/s]

A0A075JIN0
 Bacteria (superkingdom)
C8X554
 Bacteria (superkingdom)

 59%|███████████████████████████████████████████████████████████████████████████████████████▊                                                              | 750/1281 [02:25<01:41,  5.24it/s]

B8FZP7
 Bacteria (superkingdom)
Q5KAF6
 Eukaryota (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████████████                                                              | 752/1281 [02:25<01:40,  5.24it/s]

A0A427KNL6
 Bacteria (superkingdom)
A0A7G5DPV0
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 754/1281 [02:26<01:40,  5.23it/s]

Q22947
 Eukaryota (superkingdom)
A0A1S1HRJ0
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 756/1281 [02:26<01:40,  5.24it/s]

A0A3N1VXY4
 Bacteria (superkingdom)
A0A2S7YPJ9
 Eukaryota (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 758/1281 [02:26<01:39,  5.23it/s]

I0JI83
 Bacteria (superkingdom)
A0A7U3YMN6
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 760/1281 [02:27<01:39,  5.23it/s]

Q9BLG3
 Eukaryota (superkingdom)
A0A1H9RTW8
 Bacteria (superkingdom)

 59%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 762/1281 [02:27<01:40,  5.19it/s]

A0A1I4W3A0
 Bacteria (superkingdom)
A0A0B4M163
 Eukaryota (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 764/1281 [02:28<01:39,  5.19it/s]

U2EN72
 Bacteria (superkingdom)
A0A2W5VAZ2
 Bacteria (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 766/1281 [02:28<01:39,  5.19it/s]

E4YA63
 Eukaryota (superkingdom)
D5ELM4
 Bacteria (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 768/1281 [02:28<01:38,  5.20it/s]

M9RJS5
 Bacteria (superkingdom)
A0A2G3E8V2
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 770/1281 [02:29<01:38,  5.21it/s]

Q5FSX6
 Bacteria (superkingdom)
I0HKQ8
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 772/1281 [02:29<01:37,  5.21it/s]

A0A833H2R7
 Bacteria (superkingdom)
B8ENL9
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 774/1281 [02:30<01:37,  5.20it/s]

B3DUX7
 Bacteria (superkingdom)
A0A1D8UWJ6
 Bacteria (superkingdom)

 61%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 776/1281 [02:30<01:37,  5.20it/s]

D5E995
 Archaea (superkingdom)
A0A7U8C2Y6
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████████████                                                           | 778/1281 [02:30<01:36,  5.20it/s]

L0KGR8
 Bacteria (superkingdom)
B0VMH1
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 780/1281 [02:31<01:36,  5.19it/s]

P40260
 Eukaryota (superkingdom)
L0JT30
 Archaea (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 782/1281 [02:31<01:38,  5.09it/s]

C1GR74
 Eukaryota (superkingdom)
A0A423Y4I6
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 784/1281 [02:32<01:37,  5.11it/s]

A0A4P7UHQ5
 Bacteria (superkingdom)
A0A8E2R1Y5
 Bacteria (superkingdom)

 61%|████████████████████████████████████████████████████████████████████████████████████████████                                                          | 786/1281 [02:32<01:36,  5.12it/s]

I5BYV5
 Bacteria (superkingdom)
A0A6B8N021
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 788/1281 [02:32<01:35,  5.14it/s]

A0A7G5DPV1
 Bacteria (superkingdom)
A0A2G5RQK9
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 790/1281 [02:33<01:34,  5.17it/s]

A0A5M4B0G1
 Bacteria (superkingdom)
A0A6S5K4J1
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 792/1281 [02:33<01:34,  5.18it/s]

C1D4X0
 Bacteria (superkingdom)
A1SVA8
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 794/1281 [02:33<01:34,  5.17it/s]

H1YF74
 Bacteria (superkingdom)
A0A8B4RWH8
 Bacteria (superkingdom)

 62%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 796/1281 [02:34<01:33,  5.19it/s]

A0A0A0D6K5
 Bacteria (superkingdom)
A0A0A2BBY0
 Bacteria (superkingdom)

 62%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 798/1281 [02:34<01:33,  5.18it/s]

A0A089ZBW5
 Archaea (superkingdom)
A0A068TC78
 Bacteria (superkingdom)

 62%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 800/1281 [02:35<01:32,  5.17it/s]

Q46G49
 Archaea (superkingdom)
A1CQ21
 Eukaryota (superkingdom)

 63%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 802/1281 [02:35<01:32,  5.18it/s]

A0A1G6ABX1
 Bacteria (superkingdom)
E1SLM7
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 804/1281 [02:35<01:32,  5.16it/s]

K5CFE5
 Bacteria (superkingdom)
Q2YLQ6
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 806/1281 [02:36<01:32,  5.14it/s]

Q0G2V0
 Bacteria (superkingdom)
A4ABK3
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 808/1281 [02:36<01:31,  5.18it/s]

A0A9Q5QVI9
 Bacteria (superkingdom)
A0A4Q7Y9I7
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 810/1281 [02:37<01:30,  5.19it/s]

A9HMD6
 Bacteria (superkingdom)
K9YN27
 Bacteria (superkingdom)

 63%|███████████████████████████████████████████████████████████████████████████████████████████████                                                       | 812/1281 [02:37<01:30,  5.17it/s]

Q9UBD6
 Eukaryota (superkingdom)
D9SI59
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 814/1281 [02:37<01:30,  5.19it/s]

Q8I0L6
 Eukaryota (superkingdom)
A0A142VAD6
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 816/1281 [02:38<01:29,  5.17it/s]

G3IYW0
 Bacteria (superkingdom)
A0A062IU58
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 818/1281 [02:38<01:29,  5.19it/s]

R1D1H4
 Eukaryota (superkingdom)
A0A366XFS8
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 820/1281 [02:38<01:29,  5.13it/s]

A0A7S4GNF3
 Eukaryota (superkingdom)
F0J6E8
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 822/1281 [02:39<01:29,  5.14it/s]

A0A7U4DN04
 Bacteria (superkingdom)
V4RHR4
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 824/1281 [02:39<01:28,  5.15it/s]

F7ZJM0
 Bacteria (superkingdom)
A0A2S5XAB8
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 826/1281 [02:40<01:28,  5.16it/s]

U5C4L4
 Bacteria (superkingdom)
Q21J04
 Bacteria (superkingdom)

 65%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 828/1281 [02:40<01:27,  5.19it/s]

A0A142NNN1
 Bacteria (superkingdom)
H1Y7T6
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 830/1281 [02:40<01:26,  5.19it/s]

F5R974
 Bacteria (superkingdom)
B0DU91
 Eukaryota (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 832/1281 [02:41<01:26,  5.20it/s]

A2BP62
 Bacteria (superkingdom)
A7HSN9
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 834/1281 [02:41<01:26,  5.19it/s]

A0A377I7W9
 Bacteria (superkingdom)
D2RU19
 Archaea (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 836/1281 [02:42<01:25,  5.20it/s]

G7WJN0
 Bacteria (superkingdom)
E2SD33
 Bacteria (superkingdom)

 65%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 838/1281 [02:42<01:25,  5.17it/s]

A0A0D7F2Y9
 Bacteria (superkingdom)
A0AA92EGF5
 Bacteria (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 840/1281 [02:42<01:25,  5.14it/s]

A0A9E9LXV9
 Bacteria (superkingdom)
A4BEP1
 Bacteria (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 842/1281 [02:43<01:24,  5.17it/s]

A0A0E3WZH5
 Archaea (superkingdom)
F7ZEU9
 Bacteria (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 844/1281 [02:43<01:24,  5.18it/s]

A5E3X2
 Eukaryota (superkingdom)
A0A0A3XTJ3
 Bacteria (superkingdom)

 66%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 846/1281 [02:44<01:23,  5.21it/s]

A0A830ZZN8
 Bacteria (superkingdom)
A0A1S8D478
 Bacteria (superkingdom)

 66%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 848/1281 [02:44<01:23,  5.21it/s]

J7IVQ1
 Bacteria (superkingdom)
A0A2U1SS17
 Bacteria (superkingdom)

 66%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 850/1281 [02:44<01:22,  5.20it/s]

S3K1S2
 Bacteria (superkingdom)
C6XKC2
 Bacteria (superkingdom)

 67%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 852/1281 [02:45<01:22,  5.17it/s]

A0A2S7YIM5
 Eukaryota (superkingdom)
K2IMJ7
 Bacteria (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 854/1281 [02:45<01:22,  5.18it/s]

Q5P1S8
 Bacteria (superkingdom)
A0A7T5BFQ2
 Bacteria (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 856/1281 [02:45<01:21,  5.19it/s]

A0A556SRH6
 Bacteria (superkingdom)
A8P923
 Eukaryota (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 858/1281 [02:46<01:21,  5.20it/s]

A0A7G5DKA9
 Bacteria (superkingdom)
L8JUH3
 Bacteria (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 860/1281 [02:46<01:20,  5.20it/s]

A0A0D2LEF5
 Eukaryota (superkingdom)
A0A258FTB0
 Bacteria (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 862/1281 [02:47<01:20,  5.23it/s]

A0A5P9P1L2
 Archaea (superkingdom)
M8E0R3
 Bacteria (superkingdom)

 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 864/1281 [02:47<01:19,  5.24it/s]

A0A6J5IRX5
 Bacteria (superkingdom)
W5WIX6
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 866/1281 [02:47<01:19,  5.22it/s]

Q82X47
 Bacteria (superkingdom)
I4DBY0
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 868/1281 [02:48<01:18,  5.25it/s]

A0A6F8TLE9
 Bacteria (superkingdom)
A0A1G7UZX2
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 870/1281 [02:48<01:20,  5.12it/s]

A0A6P4JM51
 Eukaryota (superkingdom)
G0J614
 Bacteria (superkingdom)

 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 872/1281 [02:49<01:20,  5.07it/s]

U2WTW8
 Bacteria (superkingdom)
A0A642KQG8
 Bacteria (superkingdom)

 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 874/1281 [02:49<01:19,  5.13it/s]

Q1AUG3
 Bacteria (superkingdom)
A0A6G9Y3Q0
 Bacteria (superkingdom)

 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 876/1281 [02:49<01:18,  5.15it/s]

B8J5X4
 Bacteria (superkingdom)
M7NFH3
 Bacteria (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 878/1281 [02:50<01:17,  5.19it/s]

A0A0E3R6S1
 Archaea (superkingdom)
Q2IHY5
 Bacteria (superkingdom)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 880/1281 [02:50<01:16,  5.22it/s]

A7I8Z2
 Archaea (superkingdom)
L1IYP4
 Eukaryota (superkingdom)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 882/1281 [02:50<01:16,  5.20it/s]

B4HDZ9
 Eukaryota (superkingdom)
A0A366WYI9
 Bacteria (superkingdom)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 884/1281 [02:51<01:15,  5.24it/s]

E4TJ50
 Bacteria (superkingdom)
A0A7S0ILH2
 Eukaryota (superkingdom)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 886/1281 [02:51<01:15,  5.24it/s]

A4BAE1
 Bacteria (superkingdom)
B3QRJ4
 Bacteria (superkingdom)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 888/1281 [02:52<01:15,  5.21it/s]

A0A5C5BWI6
 Bacteria (superkingdom)
Q7NQY2
 Bacteria (superkingdom)

 69%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 890/1281 [02:52<01:15,  5.19it/s]

A0A091AXI3
 Bacteria (superkingdom)
Q1QSQ2
 Bacteria (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 892/1281 [02:52<01:14,  5.20it/s]

R4FZE3
 Bacteria (superkingdom)
A0A2N0MZ27
 Bacteria (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 894/1281 [02:53<01:14,  5.20it/s]

A9BTK1
 Bacteria (superkingdom)
A0A242NIL1
 Bacteria (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 896/1281 [02:53<01:14,  5.17it/s]

G0LFE3
 Archaea (superkingdom)
A0A1B9NQ91
 Bacteria (superkingdom)

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 898/1281 [02:54<01:13,  5.18it/s]

A0A5M5PZE2
 Bacteria (superkingdom)
A0A0D2NYP3
 Eukaryota (superkingdom)

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 900/1281 [02:54<01:13,  5.18it/s]

D9QPE5
 Bacteria (superkingdom)
I5B3H0
 Bacteria (superkingdom)

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 902/1281 [02:54<01:13,  5.13it/s]

L1IYW7
 Eukaryota (superkingdom)
C6WEW7
 Bacteria (superkingdom)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 904/1281 [02:55<01:13,  5.16it/s]

B7FW68
 Eukaryota (superkingdom)
F4GED5
 Bacteria (superkingdom)

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 906/1281 [02:55<01:12,  5.16it/s]

A0A4R8GSH7
 Bacteria (superkingdom)
A0A1W2H3F0
 Bacteria (superkingdom)

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 908/1281 [02:55<01:12,  5.17it/s]

A0A3E2T713
 Bacteria (superkingdom)
A0A0H3KTD3
 Bacteria (superkingdom)

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 910/1281 [02:56<01:11,  5.17it/s]

A0A1Y4LM49
 Bacteria (superkingdom)
G2PRJ6
 Bacteria (superkingdom)

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 912/1281 [02:56<01:11,  5.18it/s]

A0A0X8X7Y7
 Bacteria (superkingdom)
K8EJ02
 Bacteria (superkingdom)

 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 914/1281 [02:57<01:12,  5.08it/s]

A0A1L3F1X5
 Bacteria (superkingdom)
G8TK77
 Bacteria (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 916/1281 [02:57<01:11,  5.14it/s]

A0A855F5Y8
 Bacteria (superkingdom)
A0A975BTN0
 Bacteria (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 918/1281 [02:57<01:09,  5.19it/s]

A0A562RGZ4
 Bacteria (superkingdom)
G5EB09
 Eukaryota (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 920/1281 [02:58<01:09,  5.21it/s]

A0A833LX85
 Bacteria (superkingdom)
U1H1F7
 Bacteria (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 922/1281 [02:58<01:08,  5.21it/s]

K8W1E2
 Bacteria (superkingdom)
E3HJW8
 Bacteria (superkingdom)

 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 924/1281 [02:59<01:08,  5.21it/s]

Q7SEH0
 Eukaryota (superkingdom)
Q47X17
 Bacteria (superkingdom)

 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 926/1281 [02:59<01:08,  5.22it/s]

B0DXT9
 Eukaryota (superkingdom)
A0A3G9G2C9
 Bacteria (superkingdom)

 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 928/1281 [02:59<01:07,  5.21it/s]

Q95P70
 Eukaryota (superkingdom)
A0A837C6X5
 Bacteria (superkingdom)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 930/1281 [03:00<01:07,  5.21it/s]

Q89WR5
 Bacteria (superkingdom)
A6DUG4
 Bacteria (superkingdom)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 932/1281 [03:00<01:06,  5.22it/s]

D7UQE2
 Eukaryota (superkingdom)
A0A2I1M481
 Bacteria (superkingdom)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 934/1281 [03:00<01:06,  5.18it/s]

A0A0T7GZ59
 Bacteria (superkingdom)
O66395
 Bacteria (superkingdom)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 936/1281 [03:01<01:06,  5.19it/s]

J3EXK0
 Archaea (superkingdom)
A0A1B9MYL7
 Bacteria (superkingdom)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 938/1281 [03:01<01:06,  5.19it/s]

K9U8C7
 Bacteria (superkingdom)
E2SD44
 Bacteria (superkingdom)

 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 940/1281 [03:02<01:06,  5.16it/s]

H6LKH6
 Bacteria (superkingdom)
Q605Y6
 Bacteria (superkingdom)

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 942/1281 [03:02<01:05,  5.17it/s]

A0A9Q9D9I3
 Bacteria (superkingdom)
A0A6N2TIA4
 Bacteria (superkingdom)

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 944/1281 [03:02<01:04,  5.20it/s]

A0A1E3PQH0
 Eukaryota (superkingdom)
A4CMI3
 Bacteria (superkingdom)

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 946/1281 [03:03<01:04,  5.21it/s]

Q1K0H9
 Bacteria (superkingdom)
A0A0S6UEK9
 Bacteria (superkingdom)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 948/1281 [03:03<01:03,  5.22it/s]

A0A0H3LUA3
 Bacteria (superkingdom)
B9LU00
 Archaea (superkingdom)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 950/1281 [03:04<01:03,  5.22it/s]

A9BIZ7
 Bacteria (superkingdom)
A0A7H8UK07
 Bacteria (superkingdom)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 952/1281 [03:04<01:03,  5.22it/s]

E3H8C9
 Bacteria (superkingdom)
M2A398
 Bacteria (superkingdom)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 954/1281 [03:04<01:02,  5.22it/s]

Q1QS12
 Bacteria (superkingdom)
G0VI62
 Eukaryota (superkingdom)

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 956/1281 [03:05<01:02,  5.20it/s]

A0A1Z3MS36
 Bacteria (superkingdom)
A0A0B5FNH4
 Bacteria (superkingdom)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 958/1281 [03:05<01:01,  5.23it/s]

D9SI36
 Bacteria (superkingdom)
A0A410JZR4
 Bacteria (superkingdom)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 960/1281 [03:05<01:01,  5.22it/s]

F7ZJZ1
 Bacteria (superkingdom)
F0ZCX7
 Eukaryota (superkingdom)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 962/1281 [03:06<01:01,  5.22it/s]

W0DZX1
 Bacteria (superkingdom)
A0A4R3ZZ35
 Bacteria (superkingdom)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 964/1281 [03:06<01:00,  5.23it/s]

A0A317G0I6
 Bacteria (superkingdom)
Q0ARJ4
 Bacteria (superkingdom)

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 966/1281 [03:07<01:00,  5.22it/s]

A7I8Z4
 Archaea (superkingdom)
T2KJ59
 Bacteria (superkingdom)

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 968/1281 [03:07<00:59,  5.22it/s]

I3C0V3
 Bacteria (superkingdom)
E3H8A6
 Bacteria (superkingdom)

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 970/1281 [03:07<00:59,  5.22it/s]

B2IJT1
 Bacteria (superkingdom)
A0A2G6JLT9
 Bacteria (superkingdom)

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 972/1281 [03:08<00:58,  5.24it/s]

A3ZZL7
 Bacteria (superkingdom)
A0A2T0XPP2
 Bacteria (superkingdom)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 974/1281 [03:08<00:58,  5.25it/s]

Q31CR9
 Bacteria (superkingdom)
A0A1R1IDV3
 Bacteria (superkingdom)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 976/1281 [03:09<00:58,  5.23it/s]

K2JVF8
 Bacteria (superkingdom)
V5BYZ7
 Bacteria (superkingdom)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 978/1281 [03:09<00:58,  5.21it/s]

D8J4C6
 Archaea (superkingdom)
D4H5F9
 Bacteria (superkingdom)

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 980/1281 [03:09<00:57,  5.21it/s]

K9ZG59
 Bacteria (superkingdom)
A0AA86YS65
 Bacteria (superkingdom)

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 982/1281 [03:10<00:58,  5.08it/s]

Q608B6
 Bacteria (superkingdom)
A0A562BXM4
 Bacteria (superkingdom)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 984/1281 [03:10<00:58,  5.06it/s]

A0A401WXG0
 Bacteria (superkingdom)
A0A857DMN9
 Bacteria (superkingdom)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 986/1281 [03:10<00:57,  5.11it/s]

A0A1X6N3Q5
 Eukaryota (superkingdom)
A0A173R3X4
 Bacteria (superkingdom)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 988/1281 [03:11<00:57,  5.08it/s]

Q63EK5
 Bacteria (superkingdom)
K9ZLY2
 Bacteria (superkingdom)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 990/1281 [03:11<00:56,  5.13it/s]

A0A533I6R2
 Bacteria (superkingdom)
I0WJ97
 Bacteria (superkingdom)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 992/1281 [03:12<00:55,  5.18it/s]

K0N2R5
 Bacteria (superkingdom)
M0J579
 Archaea (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 994/1281 [03:12<00:56,  5.10it/s]

B8GGC1
 Archaea (superkingdom)
A0A6H9GFU4
 Bacteria (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 996/1281 [03:12<00:56,  5.08it/s]

C6CBB1
 Bacteria (superkingdom)
A0A510HHK8
 Bacteria (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 998/1281 [03:13<00:55,  5.11it/s]

A0A1B9MBX6
 Bacteria (superkingdom)
A0A9Y2AG30
 Bacteria (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 1000/1281 [03:13<00:54,  5.15it/s]

E8RSE4
 Bacteria (superkingdom)
F2B2B8
 Bacteria (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 1002/1281 [03:14<00:54,  5.16it/s]

Q7UYZ3
 Bacteria (superkingdom)
I1YJH7
 Bacteria (superkingdom)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 1004/1281 [03:14<00:54,  5.13it/s]

A0A853MG28
 Bacteria (superkingdom)
A0A0L0STS6
 Eukaryota (superkingdom)

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 1006/1281 [03:14<00:53,  5.16it/s]

A0A251XU71
 Bacteria (superkingdom)
Q60BI2
 Bacteria (superkingdom)

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 1008/1281 [03:15<00:52,  5.17it/s]

A0A829X098
 Bacteria (superkingdom)
F3KUN4
 Bacteria (superkingdom)

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 1010/1281 [03:15<00:52,  5.20it/s]

Q60C43
 Bacteria (superkingdom)
A0A0T7FAP8
 Bacteria (superkingdom)

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 1012/1281 [03:16<00:51,  5.19it/s]

A0A3E2TW06
 Bacteria (superkingdom)
W0E077
 Bacteria (superkingdom)

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 1014/1281 [03:16<00:51,  5.19it/s]

A0KPE9
 Bacteria (superkingdom)
R7PZ71
 Archaea (superkingdom)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 1016/1281 [03:16<00:51,  5.15it/s]

A0A0A1ZMZ9
 Bacteria (superkingdom)
A0AA40J491
 Bacteria (superkingdom)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 1018/1281 [03:17<00:50,  5.17it/s]

D3S2L0
 Archaea (superkingdom)
A0A373FQ71
 Bacteria (superkingdom)

 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 1020/1281 [03:17<00:51,  5.07it/s]

A0A0A2C6L1
 Bacteria (superkingdom)
Q7W7D3
 Bacteria (superkingdom)

 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 1022/1281 [03:18<00:50,  5.10it/s]

A0A165K0X5
 Bacteria (superkingdom)
A0A2S5X482
 Bacteria (superkingdom)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 1024/1281 [03:18<00:49,  5.15it/s]

R9GM11
 Bacteria (superkingdom)
Q0G0A3
 Bacteria (superkingdom)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 1026/1281 [03:18<00:49,  5.16it/s]

D4GLQ6
 Bacteria (superkingdom)
E7RJZ0
 Bacteria (superkingdom)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 1028/1281 [03:19<00:49,  5.14it/s]

F8IJE0
 Bacteria (superkingdom)
A0A1V2XMU9
 Bacteria (superkingdom)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 1030/1281 [03:19<00:48,  5.13it/s]

Q7TNN9
 Eukaryota (superkingdom)
A0A1G5RZU9
 Bacteria (superkingdom)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 1032/1281 [03:19<00:48,  5.16it/s]

A0A2N6K4Y5
 Bacteria (superkingdom)
B0SLB7
 Bacteria (superkingdom)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 1034/1281 [03:20<00:48,  5.09it/s]

A0A251YFS0
 Bacteria (superkingdom)
B9WDK0
 Eukaryota (superkingdom)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 1036/1281 [03:20<00:47,  5.16it/s]

Q7N0M6
 Bacteria (superkingdom)
A0A0M2LU39
 Bacteria (superkingdom)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 1038/1281 [03:21<00:47,  5.15it/s]

F4B548
 Archaea (superkingdom)
D6Z5V9
 Bacteria (superkingdom)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 1040/1281 [03:21<00:46,  5.18it/s]

A0A4R2M206
 Bacteria (superkingdom)
A0A1E2SKM1
 Bacteria (superkingdom)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 1042/1281 [03:21<00:46,  5.18it/s]

A0A127JTU2
 Bacteria (superkingdom)
A0A212AV03
 Bacteria (superkingdom)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 1044/1281 [03:22<00:45,  5.20it/s]

G4QHD2
 Bacteria (superkingdom)
A0A021VMC6
 Bacteria (superkingdom)

 82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 1046/1281 [03:22<00:45,  5.18it/s]

A0A2J7TJ33
 Bacteria (superkingdom)
G7WDB5
 Bacteria (superkingdom)

 82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 1048/1281 [03:23<00:44,  5.19it/s]

Q6BK68
 Eukaryota (superkingdom)
Q1K3N8
 Bacteria (superkingdom)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 1050/1281 [03:23<00:44,  5.19it/s]

A0AA91Q161
 Eukaryota (superkingdom)
A0NJ07
 Bacteria (superkingdom)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 1052/1281 [03:23<00:44,  5.19it/s]

A0A316BQ38
 Bacteria (superkingdom)
A0A377PLP5
 Bacteria (superkingdom)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 1054/1281 [03:24<00:43,  5.18it/s]

W7QGM4
 Bacteria (superkingdom)
A0A015YIP3
 Bacteria (superkingdom)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1056/1281 [03:24<00:43,  5.15it/s]

A0A060UWC8
 Bacteria (superkingdom)
A0A1I4ZIZ6
 Bacteria (superkingdom)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 1058/1281 [03:24<00:43,  5.13it/s]

A0A264VQM8
 Bacteria (superkingdom)
A9AUR8
 Bacteria (superkingdom)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 1060/1281 [03:25<00:42,  5.15it/s]

A0A1W5PRD1
 Eukaryota (superkingdom)
A0A0E3BR91
 Bacteria (superkingdom)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 1062/1281 [03:25<00:42,  5.16it/s]

A0A1B0ZRL8
 Bacteria (superkingdom)
B9ACS5
 Archaea (superkingdom)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 1064/1281 [03:26<00:42,  5.16it/s]

Q92BJ7
 Bacteria (superkingdom)
F2JTN3
 Bacteria (superkingdom)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 1066/1281 [03:26<00:41,  5.18it/s]

A1AVV2
 Bacteria (superkingdom)
D2Q0J8
 Bacteria (superkingdom)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 1068/1281 [03:26<00:41,  5.15it/s]

A0A3S9N9F3
 Bacteria (superkingdom)
A8ZQD5
 Bacteria (superkingdom)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 1070/1281 [03:27<00:40,  5.20it/s]

C3X831
 Bacteria (superkingdom)
A0A1M6BPM0
 Bacteria (superkingdom)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 1072/1281 [03:27<00:40,  5.18it/s]

A0A8F5VN39
 Archaea (superkingdom)
A0A1E5C7W4
 Bacteria (superkingdom)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 1074/1281 [03:28<00:39,  5.20it/s]

A0A2S5WV24
 Bacteria (superkingdom)
A0A833GZR2
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 1076/1281 [03:28<00:39,  5.20it/s]

C7M2A9
 Bacteria (superkingdom)
A6W7U2
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 1078/1281 [03:28<00:38,  5.21it/s]

W0JIB3
 Archaea (superkingdom)
Q07UM3
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 1080/1281 [03:29<00:38,  5.18it/s]

A0A066ZRQ5
 Bacteria (superkingdom)
S0G181
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 1082/1281 [03:29<00:38,  5.18it/s]

D3PAH1
 Bacteria (superkingdom)
Q4WHC6
 Eukaryota (superkingdom)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 1084/1281 [03:29<00:38,  5.16it/s]

A0AA94HTL8
 Bacteria (superkingdom)
D5ASL9
 Bacteria (superkingdom)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 1086/1281 [03:30<00:37,  5.17it/s]

A0A4U1JNL6
 Bacteria (superkingdom)
M0MDP9
 Archaea (superkingdom)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 1088/1281 [03:30<00:37,  5.18it/s]

A0A653N397
 Bacteria (superkingdom)
A0A2S8GSU9
 Bacteria (superkingdom)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1090/1281 [03:31<00:36,  5.17it/s]

A0A097R891
 Bacteria (superkingdom)
A0A8H7U3I1
 Eukaryota (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 1092/1281 [03:31<00:36,  5.20it/s]

A0A1H1MB73
 Bacteria (superkingdom)
A0A016XDZ5
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 1094/1281 [03:31<00:35,  5.23it/s]

A0A1B9JHS5
 Bacteria (superkingdom)
D3PE53
 Bacteria (superkingdom)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 1096/1281 [03:32<00:35,  5.22it/s]

A0A9J9BAE8
 Bacteria (superkingdom)
Q2RM12
 Bacteria (superkingdom)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 1098/1281 [03:32<00:35,  5.22it/s]

A0A3N0AQL8
 Bacteria (superkingdom)
C5KTM6
 Eukaryota (superkingdom)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 1100/1281 [03:33<00:34,  5.21it/s]

M1P5F0
 Bacteria (superkingdom)
I1YG38
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 1102/1281 [03:33<00:34,  5.19it/s]

A0A660CH85
 Bacteria (superkingdom)
A0A2N7L7C8
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 1104/1281 [03:33<00:34,  5.15it/s]

Q5KZZ9
 Bacteria (superkingdom)
M1NZT5
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 1106/1281 [03:34<00:33,  5.15it/s]

A0A225CMT8
 Bacteria (superkingdom)
A0A068NV61
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 1108/1281 [03:34<00:33,  5.18it/s]

H2CJI0
 Bacteria (superkingdom)
B0DU93
 Eukaryota (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 1110/1281 [03:34<00:32,  5.21it/s]

Q221S8
 Bacteria (superkingdom)
F4Y3C5
 Bacteria (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 1112/1281 [03:35<00:32,  5.21it/s]

Q94CJ2
 Eukaryota (superkingdom)
M0D3Q9
 Archaea (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 1114/1281 [03:35<00:32,  5.08it/s]

A0A3P2A7W8
 Bacteria (superkingdom)
C0GKN4
 Bacteria (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 1116/1281 [03:36<00:32,  5.12it/s]

Q7T3R4
 Eukaryota (superkingdom)
A0A562USB9
 Bacteria (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 1118/1281 [03:36<00:31,  5.13it/s]

A2SS52
 Archaea (superkingdom)
A0A211ZGL5
 Bacteria (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 1120/1281 [03:36<00:31,  5.16it/s]

A0A4V3ALP8
 Bacteria (superkingdom)
A0A147GP06
 Bacteria (superkingdom)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 1122/1281 [03:37<00:30,  5.14it/s]

H2IZ00
 Bacteria (superkingdom)
Q45HK8
 Bacteria (superkingdom)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 1124/1281 [03:37<00:30,  5.16it/s]

A0A6C8LST1
 Bacteria (superkingdom)
A0A257T8W6
 Bacteria (superkingdom)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 1126/1281 [03:38<00:29,  5.18it/s]

Q5P470
 Bacteria (superkingdom)
I5AZQ4
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 1128/1281 [03:38<00:30,  5.08it/s]

Q07UM1
 Bacteria (superkingdom)
E5B358
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 1130/1281 [03:38<00:29,  5.11it/s]

A0A1Y4L5P0
 Bacteria (superkingdom)
Q3AFY9
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 1132/1281 [03:39<00:28,  5.15it/s]

B0BZN3
 Bacteria (superkingdom)
A0A1Q2C7H7
 Bacteria (superkingdom)

 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 1134/1281 [03:39<00:28,  5.20it/s]

A0A4R5U5V1
 Bacteria (superkingdom)
H6LKX6
 Bacteria (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 1136/1281 [03:40<00:27,  5.18it/s]

A0A1Y0UZX2
 Bacteria (superkingdom)
F6BEI0
 Archaea (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 1138/1281 [03:40<00:27,  5.15it/s]

M9RKT6
 Bacteria (superkingdom)
A7SGD4
 Eukaryota (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 1140/1281 [03:40<00:27,  5.18it/s]

A0A257TE48
 Bacteria (superkingdom)
R1FI09
 Eukaryota (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 1142/1281 [03:41<00:26,  5.18it/s]

E4N1T5
 Bacteria (superkingdom)
U1PIR6
 Archaea (superkingdom)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 1144/1281 [03:41<00:26,  5.19it/s]

F2JYR9
 Bacteria (superkingdom)
Q84KJ7
 Eukaryota (superkingdom)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 1146/1281 [03:41<00:26,  5.16it/s]

A0A2S8FTB5
 Bacteria (superkingdom)
D2R647
 Bacteria (superkingdom)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 1148/1281 [03:42<00:25,  5.16it/s]

G9Y5B0
 Bacteria (superkingdom)
A0A144NLT9
 Bacteria (superkingdom)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 1150/1281 [03:42<00:25,  5.19it/s]

A0A5J6WQU1
 Bacteria (superkingdom)
D2R355
 Bacteria (superkingdom)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 1152/1281 [03:43<00:24,  5.19it/s]

F3ZYD6
 Bacteria (superkingdom)
B0SL05
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 1154/1281 [03:43<00:24,  5.19it/s]

A0A5A7MAJ9
 Bacteria (superkingdom)
A0A977NL43
 Archaea (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 1156/1281 [03:43<00:24,  5.20it/s]

A0A433ZQ80
 Bacteria (superkingdom)
A0A1Y0V4A5
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 1158/1281 [03:44<00:24,  5.10it/s]

A0A1M7UEG2
 Bacteria (superkingdom)
G8R7U9
 Bacteria (superkingdom)

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 1160/1281 [03:44<00:23,  5.13it/s]

K1LDP0
 Bacteria (superkingdom)
B7G0Y4
 Eukaryota (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 1162/1281 [03:45<00:23,  5.11it/s]

A0A2W4ZXC0
 Bacteria (superkingdom)
B3PF77
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 1164/1281 [03:45<00:22,  5.11it/s]

Q2KZK9
 Bacteria (superkingdom)
Q18ES8
 Archaea (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 1166/1281 [03:45<00:22,  5.15it/s]

D3F545
 Bacteria (superkingdom)
B4S394
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 1168/1281 [03:46<00:21,  5.16it/s]

Q1Q357
 Bacteria (superkingdom)
Q9H310
 Eukaryota (superkingdom)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 1170/1281 [03:46<00:21,  5.10it/s]

D3PKL4
 Bacteria (superkingdom)
M5SY07
 Bacteria (superkingdom)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 1172/1281 [03:47<00:21,  5.13it/s]

Q8RUT6
 Eukaryota (superkingdom)
A7NKH2
 Bacteria (superkingdom)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 1174/1281 [03:47<00:20,  5.18it/s]

Q1Q879
 Bacteria (superkingdom)
A0A1B9M5B8
 Bacteria (superkingdom)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 1176/1281 [03:47<00:20,  5.21it/s]

A6LRS5
 Bacteria (superkingdom)
J2ZGN6
 Archaea (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 1178/1281 [03:48<00:19,  5.20it/s]

V5E0F3
 Bacteria (superkingdom)
A0A149RQX0
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 1180/1281 [03:48<00:19,  5.19it/s]

A0A165BP25
 Bacteria (superkingdom)
C0QSY0
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 1182/1281 [03:48<00:19,  5.20it/s]

B0XVV6
 Eukaryota (superkingdom)
E0SD83
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 1184/1281 [03:49<00:18,  5.16it/s]

A8HSA2
 Eukaryota (superkingdom)
A0A1E3PSK5
 Eukaryota (superkingdom)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 1186/1281 [03:49<00:18,  5.17it/s]

A5DYQ2
 Eukaryota (superkingdom)
A0A4U1K1W1
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 1188/1281 [03:50<00:17,  5.19it/s]

Q0AT01
 Bacteria (superkingdom)
A4FMG0
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 1190/1281 [03:50<00:17,  5.19it/s]

C3YB73
 Eukaryota (superkingdom)
A0A9P3CXY2
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 1192/1281 [03:50<00:17,  5.22it/s]

A0A0L8BVU4
 Bacteria (superkingdom)
A0A401WUW1
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 1194/1281 [03:51<00:16,  5.19it/s]

I4C9L2
 Bacteria (superkingdom)
Q8RUE9
 Eukaryota (superkingdom)

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 1196/1281 [03:51<00:16,  5.16it/s]

F0JGZ1
 Bacteria (superkingdom)
A0A2I0UUY1
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 1198/1281 [03:52<00:16,  5.18it/s]

A0A542XGT4
 Bacteria (superkingdom)
G0JRH4
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 1200/1281 [03:52<00:15,  5.17it/s]

A2SPS8
 Archaea (superkingdom)
A0A5M4AWD2
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 1202/1281 [03:52<00:15,  5.17it/s]

Q6QH01
 Eukaryota (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 1204/1281 [03:53<00:14,  5.34it/s]

D3F0Z1
 Bacteria (superkingdom)
A6XBM2
 Eukaryota (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 1206/1281 [03:53<00:13,  5.46it/s]

D6E7B3
 Bacteria (superkingdom)
Q13E03
 Bacteria (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 1208/1281 [03:53<00:13,  5.58it/s]

A0A060URB8
 Bacteria (superkingdom)
A0A2T1N7R1
 Bacteria (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 1210/1281 [03:54<00:12,  5.66it/s]

D6TCH6
 Bacteria (superkingdom)
B0CXH8
 Eukaryota (superkingdom)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 1212/1281 [03:54<00:12,  5.67it/s]

A3TVQ9
 Bacteria (superkingdom)
Q4WT12
 Eukaryota (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 1213/1281 [03:54<00:14,  4.85it/s]

C7QGX3
 Bacteria (superkingdom)
F0Y9X3
 Eukaryota (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 1215/1281 [03:55<00:13,  4.92it/s]

A0A7S0D560
 Eukaryota (superkingdom)
A0A160KTE9
 Bacteria (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1217/1281 [03:55<00:12,  5.04it/s]

A0A2H1HV86
 Bacteria (superkingdom)
A0A251Y3N4
 Bacteria (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 1219/1281 [03:56<00:12,  5.09it/s]

A0A419AVL2
 Bacteria (superkingdom)
A0A4Q2QWS1
 Bacteria (superkingdom)

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1221/1281 [03:56<00:11,  5.13it/s]

C7Q1E4
 Bacteria (superkingdom)
A0A5C5TYS5
 Bacteria (superkingdom)

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 1223/1281 [03:56<00:11,  5.17it/s]

F2NNQ0
 Bacteria (superkingdom)
A0A2R4TRE0
 Bacteria (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 1225/1281 [03:57<00:10,  5.20it/s]

K9YJQ3
 Bacteria (superkingdom)
D9QS43
 Bacteria (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 1227/1281 [03:57<00:10,  5.18it/s]

A7SQ16
 Eukaryota (superkingdom)
A1DG05
 Eukaryota (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 1229/1281 [03:58<00:10,  5.18it/s]

U1SIR9
 Bacteria (superkingdom)
C4Y298
 Eukaryota (superkingdom)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 1231/1281 [03:58<00:09,  5.17it/s]

A0A9W3LFI9
 Bacteria (superkingdom)
D3RMV7
 Bacteria (superkingdom)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 1233/1281 [03:58<00:09,  5.16it/s]

F3QNA7
 Bacteria (superkingdom)
E4RTK5
 Bacteria (superkingdom)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 1235/1281 [03:59<00:08,  5.18it/s]

C8XBX8
 Bacteria (superkingdom)
C0QTA4
 Bacteria (superkingdom)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 1237/1281 [03:59<00:08,  5.19it/s]

E6VIW4
 Bacteria (superkingdom)
A0A2S6H643
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 1239/1281 [03:59<00:08,  5.19it/s]

Q46HB1
 Bacteria (superkingdom)
A0A2S5CTX8
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 1241/1281 [04:00<00:07,  5.20it/s]

A0A1T4SF40
 Bacteria (superkingdom)
K0K7J4
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 1243/1281 [04:00<00:07,  5.20it/s]

A0A1J5JH24
 Bacteria (superkingdom)
Q6LMI6
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 1245/1281 [04:01<00:06,  5.19it/s]

A0A9W5JBA9
 Bacteria (superkingdom)
A0A291PMC6
 Bacteria (superkingdom)

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 1247/1281 [04:01<00:06,  5.17it/s]

A0A4Y4DZN4
 Bacteria (superkingdom)
A0A2R4MBA2
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 1249/1281 [04:01<00:06,  5.09it/s]

R9PI53
 Bacteria (superkingdom)
A0A6H9GLV4
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 1251/1281 [04:02<00:05,  5.12it/s]

A0A7S4GND2
 Eukaryota (superkingdom)
A0A6H9FPY5
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 1253/1281 [04:02<00:05,  5.13it/s]

A0A1G7DX68
 Bacteria (superkingdom)
A0A075WEB4
 Archaea (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 1255/1281 [04:03<00:05,  4.98it/s]

A0A140NHJ5
 Bacteria (superkingdom)
A0A1C6Z081
 Bacteria (superkingdom)

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 1257/1281 [04:03<00:04,  5.06it/s]

Q5FA36
 Bacteria (superkingdom)
Q0ACK1
 Bacteria (superkingdom)

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 1259/1281 [04:03<00:04,  5.11it/s]

A0A975GIX9
 Bacteria (superkingdom)
A0A323UE08
 Bacteria (superkingdom)

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 1261/1281 [04:04<00:03,  5.14it/s]

U7VB41
 Bacteria (superkingdom)
A0A063Y780
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 1263/1281 [04:04<00:03,  5.14it/s]

C5CIT6
 Bacteria (superkingdom)
A0A0A2VPU3
 Eukaryota (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 1265/1281 [04:05<00:03,  5.11it/s]

F0RHS0
 Bacteria (superkingdom)
A0A2S5WX34
 Bacteria (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 1267/1281 [04:05<00:02,  5.12it/s]

C1G973
 Eukaryota (superkingdom)
A0A2S6GKF6
 Bacteria (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 1269/1281 [04:05<00:02,  5.16it/s]

A0A0A2B651
 Bacteria (superkingdom)
A0A4R3A5P7
 Bacteria (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1271/1281 [04:06<00:01,  5.19it/s]

A0A2A7U6W1
 Bacteria (superkingdom)
Q2GX26
 Eukaryota (superkingdom)

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 1273/1281 [04:06<00:01,  5.23it/s]

F5XN43
 Bacteria (superkingdom)
A0A0K2STH0
 Eukaryota (superkingdom)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 1275/1281 [04:06<00:01,  5.25it/s]

A0A1H1U2Q6
 Bacteria (superkingdom)
A7SED8
 Eukaryota (superkingdom)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1277/1281 [04:07<00:00,  5.26it/s]

A0LV78
 Bacteria (superkingdom)
K5DBA0
 Bacteria (superkingdom)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1279/1281 [04:07<00:00,  5.24it/s]

B8IZX4
 Bacteria (superkingdom)
A8LKQ0
 Bacteria (superkingdom)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1281/1281 [04:08<00:00,  5.16it/s]

A0A5C6LWQ1
 Bacteria (superkingdom)

In [168]:
with open('kingdom.txt', 'w') as fp:
    for ite in linige:
        # write each item on a new line
        fp.write("%s\n" % ite)
    print('Done')

Done

In [73]:
with open('kingdom.txt', 'r') as file:

    linage = []
    for line in file:
        line = line.strip()
        linage.append(line)

print(linage)

['A1D2Y5: Eukaryota (superkingdom)', 'M8E0R3: Bacteria (superkingdom)', 'A0A2G3DSU6: Bacteria (superkingdom)', 'A0A328EMN2: Bacteria (superkingdom)', 'A0A6A1TYJ4: Bacteria (superkingdom)', 'D3RMV7: Bacteria (superkingdom)', 'F0J3F9: Bacteria (superkingdom)', 'G2ZN72: Bacteria (superkingdom)', 'I0KDC6: Bacteria (superkingdom)', 'A0A081N2G5: Bacteria (superkingdom)', 'A0A144NLT9: Bacteria (superkingdom)', 'B4D7W2: Bacteria (superkingdom)', 'F3QNA7: Bacteria (superkingdom)', 'Q4WHC6: Eukaryota (superkingdom)', 'Q8JI14: Eukaryota (superkingdom)', 'A0A395VB65: Bacteria (superkingdom)', 'A0A975GIX9: Bacteria (superkingdom)', 'Q5UZ98: Archaea (superkingdom)', 'A0A4R4K1P9: Bacteria (superkingdom)', 'A0A7T4WEP4: Bacteria (superkingdom)', 'C6LBD3: Bacteria (superkingdom)', 'D5V7B3: Bacteria (superkingdom)', 'A0A4R3ZNW3: Bacteria (superkingdom)', 'A9BQZ4: Bacteria (superkingdom)', 'A0A642KQG8: Bacteria (superkingdom)', 'A9BIZ7: Bacteria (superkingdom)', 'K0NJH2: Bacteria (superkingdom)', 'Q2IK04: Bacteria (superkingdom)', 'T2KJ59: Bacteria (superkingdom)', 'A0A1B9M5B8: Bacteria (superkingdom)', 'A0A323UE08: Bacteria (superkingdom)', 'E8RLT5: Bacteria (superkingdom)', 'F6G5I9: Bacteria (superkingdom)', 'G3A431: Bacteria (superkingdom)', 'G4H971: Bacteria (superkingdom)', 'L1J6I4: Eukaryota (superkingdom)', 'M0J579: Archaea (superkingdom)', 'A0A377PBY1: Bacteria (superkingdom)', 'A0A401WUW1: Bacteria (superkingdom)', 'L1IYW7: Eukaryota (superkingdom)', 'A0A315S845: Bacteria (superkingdom)', 'A0A6M3ZKU5: Bacteria (superkingdom)', 'A0A502GPV4: Bacteria (superkingdom)', 'A0A9J9BAE8: Bacteria (superkingdom)', 'A1AVV2: Bacteria (superkingdom)', 'B1XZU2: Bacteria (superkingdom)', 'Q5P1S8: Bacteria (superkingdom)', 'A0A0F5EZP7: Bacteria (superkingdom)', 'A0A4R7GKA0: Bacteria (superkingdom)', 'A0A2T4UWF1: Bacteria (superkingdom)', 'A0A3E0X011: Bacteria (superkingdom)', 'A0A4R8H081: Bacteria (superkingdom)', 'C7LQR9: Bacteria (superkingdom)', 'A0A0A2A0Y9: Bacteria (superkingdom)', 'A0A0A2A5X1: Bacteria (superkingdom)', 'A0A7T5BFQ2: Bacteria (superkingdom)', 'A3U857: Bacteria (superkingdom)', 'E1V4T3: Bacteria (superkingdom)', 'F0J7D3: Bacteria (superkingdom)', 'M7XJ51: Bacteria (superkingdom)', 'Q1K0H9: Bacteria (superkingdom)', 'A0A2S5XAB8: Bacteria (superkingdom)', 'A0A366IE34: Bacteria (superkingdom)', 'Q1Z695: Bacteria (superkingdom)', 'A0A8G2IZM3: Bacteria (superkingdom)', 'G3IYW2: Bacteria (superkingdom)', 'A0A2G5BGA9: Eukaryota (superkingdom)', 'A0A5M4AUM9: Bacteria (superkingdom)', 'E3HJW8: Bacteria (superkingdom)', 'U1PIR6: Archaea (superkingdom)', 'A0A1B9N3H7: Bacteria (superkingdom)', 'A0A2S5WV24: Bacteria (superkingdom)', 'A0A6U2BIY7: Eukaryota (superkingdom)', 'A0A833LX85: Bacteria (superkingdom)', 'I9P003: Bacteria (superkingdom)', 'K8VZC6: Bacteria (superkingdom)', 'L1IUV5: Eukaryota (superkingdom)', 'A0A0K2STQ7: Eukaryota (superkingdom)', 'A0A2H1HV86: Bacteria (superkingdom)', 'Q2GX26: Eukaryota (superkingdom)', 'A0A074KY88: Bacteria (superkingdom)', 'A0A858ZNJ3: Bacteria (superkingdom)', 'A0A3P2A7W8: Bacteria (superkingdom)', 'A0A7S4GND2: Eukaryota (superkingdom)', 'O26757: Archaea (superkingdom)', 'Q46G49: Archaea (superkingdom)', 'A0A140NHJ5: Bacteria (superkingdom)', 'A0A2S8GF54: Bacteria (superkingdom)', 'B1JZ69: Bacteria (superkingdom)', 'E5Y678: Bacteria (superkingdom)', 'A0A149U2G9: Bacteria (superkingdom)', 'A0A9Q5QVI9: Bacteria (superkingdom)', 'Q18PF5: Eukaryota (superkingdom)', 'A0A317FZW2: Bacteria (superkingdom)', 'G5EB13: Eukaryota (superkingdom)', 'Q1YDY8: Bacteria (superkingdom)', 'A0A1X4GBG2: Bacteria (superkingdom)', 'A0A4Q7Y9I7: Bacteria (superkingdom)', 'I0HKQ8: Bacteria (superkingdom)', 'A0A097R891: Bacteria (superkingdom)', 'A0A7S4GMD8: Eukaryota (superkingdom)', 'Q488X2: Bacteria (superkingdom)', 'U3PCH5: Bacteria (superkingdom)', 'A0A378YR15: Bacteria (superkingdom)', 'I1YG38: Bacteria (superkingdom)', 'F5XN43: Bacteria (superkingdom)', 'Q1IWN6: Bacteria (superkingdom)', 'A0A1E3PSK5: Eukaryota (superkingdom)', 'A0A833H2R7: Bacteria (superkingdom)', 'A0A2T0XPP2: Bacteria (superkingdom)', 'A0A399T909: Bacteria (superkingdom)', 'L8GGA0: Eukaryota (superkingdom)', 'A0A0D8BQX6: Bacteria (superkingdom)', 'A0A1M5ZVP9: Bacteria (superkingdom)', 'I5BYV5: Bacteria (superkingdom)', 'A0A0K2STH0: Eukaryota (superkingdom)', 'A0A2N6K4Y5: Bacteria (superkingdom)', 'A0A1B9JZS5: Bacteria (superkingdom)', 'A0A2W0GQV0: Bacteria (superkingdom)', 'A0A369MHK2: Bacteria (superkingdom)', 'A0A087L0B9: Bacteria (superkingdom)', 'A0A0A2AMW2: Bacteria (superkingdom)', 'A0A377PLP5: Bacteria (superkingdom)', 'Q6BJI7: Eukaryota (superkingdom)', 'Q7S5K0: Eukaryota (superkingdom)', 'Q7Z1M1: Eukaryota (superkingdom)', 'T2JFS5: Bacteria (superkingdom)', 'W0JIB3: Archaea (superkingdom)', 'A0A1V2XMU9: Bacteria (superkingdom)', 'A0A2S6GKN5: Bacteria (superkingdom)', 'A0A7G5DK18: Bacteria (superkingdom)', 'A0A830ZZN8: Bacteria (superkingdom)', 'A0A8B4RWH8: Bacteria (superkingdom)', 'A0A9Q6P4A5: Bacteria (superkingdom)', 'B8ENL9: Bacteria (superkingdom)', 'Q9QXP0: Eukaryota (superkingdom)', 'A0A060URC3: Bacteria (superkingdom)', 'A0A2W5HTC3: Bacteria (superkingdom)', 'A7S731: Eukaryota (superkingdom)', 'A0A1Y0UZX2: Bacteria (superkingdom)', 'A0A257TE48: Bacteria (superkingdom)', 'Q2RVB5: Bacteria (superkingdom)', 'Q605Y6: Bacteria (superkingdom)', 'A0A918MJ52: Bacteria (superkingdom)', 'K6W5X0: Bacteria (superkingdom)', 'V4AP67: Eukaryota (superkingdom)', 'A0A7Z0V0A4: Bacteria (superkingdom)', 'C0GKN4: Bacteria (superkingdom)', 'A9HMD6: Bacteria (superkingdom)', 'B1ZSW9: Bacteria (superkingdom)', 'K5DBA0: Bacteria (superkingdom)', 'V4REY8: Bacteria (superkingdom)', 'A0A0D2KGN8: Eukaryota (superkingdom)', 'A0A242NIL1: Bacteria (superkingdom)', 'A8PXT8: Eukaryota (superkingdom)', 'B7X047: Bacteria (superkingdom)', 'D2ZRW2: Archaea (superkingdom)', 'H1Y7T6: Bacteria (superkingdom)', 'Q97L80: Bacteria (superkingdom)', 'A0A0S6UHP2: Bacteria (superkingdom)', 'A0A323UDG5: Bacteria (superkingdom)', 'E3I393: Bacteria (superkingdom)', 'A0A4V2X6C2: Bacteria (superkingdom)', 'D7G265: Eukaryota (superkingdom)', 'A6LRS5: Bacteria (superkingdom)', 'D8J4C6: Archaea (superkingdom)', 'F2NGJ8: Bacteria (superkingdom)', 'A0A0E9NHV4: Eukaryota (superkingdom)', 'A1CQ21: Eukaryota (superkingdom)', 'A0A6N2Z556: Bacteria (superkingdom)', 'Q0BWD0: Bacteria (superkingdom)', 'A0A071MMV1: Bacteria (superkingdom)', 'A0A168EVK8: Bacteria (superkingdom)', 'B3DUX7: Bacteria (superkingdom)', 'F5L8M7: Bacteria (superkingdom)', 'G7WJN0: Bacteria (superkingdom)', 'Q0BQ69: Bacteria (superkingdom)', 'A0A3N2SFS2: Bacteria (superkingdom)', 'A0A9Y2AG30: Bacteria (superkingdom)', 'A0AA46Q839: Bacteria (superkingdom)', 'E8RSE4: Bacteria (superkingdom)', 'F6BEI0: Archaea (superkingdom)', 'I1DSU5: Bacteria (superkingdom)', 'I4C9L2: Bacteria (superkingdom)', 'Q5QVH2: Bacteria (superkingdom)', 'A0A068NPW2: Bacteria (superkingdom)', 'A0A6J5IRX5: Bacteria (superkingdom)', 'A0A3R9Q7C4: Bacteria (superkingdom)', 'A3ZT81: Bacteria (superkingdom)', 'K0ER80: Bacteria (superkingdom)', 'Q0VLH1: Bacteria (superkingdom)', 'Q2KZK9: Bacteria (superkingdom)', 'R9GM11: Bacteria (superkingdom)', 'A0A0T7GZ59: Bacteria (superkingdom)', 'A0A1G5PWV0: Bacteria (superkingdom)', 'S5ABR8: Bacteria (superkingdom)', 'W7QGM4: Bacteria (superkingdom)', 'F5Y3C1: Bacteria (superkingdom)', 'I8TC71: Bacteria (superkingdom)', 'M1P5F0: Bacteria (superkingdom)', 'A0A149RYW7: Bacteria (superkingdom)', 'A0A1J1JH03: Bacteria (superkingdom)', 'A0A1U9Z147: Bacteria (superkingdom)', 'A0A243SC06: Bacteria (superkingdom)', 'A0A3G9G2C9: Bacteria (superkingdom)', 'I4C9L0: Bacteria (superkingdom)', 'I4D1H5: Bacteria (superkingdom)', 'Q7W7D3: Bacteria (superkingdom)', 'A0A0B4M163: Eukaryota (superkingdom)', 'A0A1M7UEG2: Bacteria (superkingdom)', 'A7HT14: Bacteria (superkingdom)', 'C8X554: Bacteria (superkingdom)', 'A0A127PIQ9: Bacteria (superkingdom)', 'A0A1B9JPL5: Bacteria (superkingdom)', 'W5WIX6: Bacteria (superkingdom)', 'A0AA40J491: Bacteria (superkingdom)', 'D8PD01: Bacteria (superkingdom)', 'A0A251XU71: Bacteria (superkingdom)', 'A0A2N6P374: Eukaryota (superkingdom)', 'B3QVV5: Bacteria (superkingdom)', 'K1K628: Bacteria (superkingdom)', 'A0A1E2SKM1: Bacteria (superkingdom)', 'A0A1I0BYN1: Bacteria (superkingdom)', 'A0A556RTU3: Bacteria (superkingdom)', 'A0A829X098: Bacteria (superkingdom)', 'D5EP68: Bacteria (superkingdom)', 'F0J6E8: Bacteria (superkingdom)', 'A0A073CP02: Bacteria (superkingdom)', 'A0A127JTU2: Bacteria (superkingdom)', 'C7BJG7: Bacteria (superkingdom)', 'D2BUJ8: Bacteria (superkingdom)', 'B8IZX4: Bacteria (superkingdom)', 'I3R0S7: Archaea (superkingdom)', 'A0A3E2TW06: Bacteria (superkingdom)', 'B1Y0E5: Bacteria (superkingdom)', 'E6ME92: Bacteria (superkingdom)', 'A0A251Y3N4: Bacteria (superkingdom)', 'A0A380S5X4: Bacteria (superkingdom)', 'F0YLV7: Eukaryota (superkingdom)', 'F8D7H6: Archaea (superkingdom)', 'Q31CR9: Bacteria (superkingdom)', 'W0E077: Bacteria (superkingdom)', 'A5DYQ2: Eukaryota (superkingdom)', 'A8LKQ0: Bacteria (superkingdom)', 'A0A4Y1MSE7: Bacteria (superkingdom)', 'A3TVQ9: Bacteria (superkingdom)', 'F2B2B8: Bacteria (superkingdom)', 'L0K9M1: Bacteria (superkingdom)', 'Q4WT12: Eukaryota (superkingdom)', 'Q8ERT9: Bacteria (superkingdom)', 'A0A1H3WA00: Bacteria (superkingdom)', 'A0A1U9YY82: Bacteria (superkingdom)', 'A1DG05: Eukaryota (superkingdom)', 'B8GGC1: Archaea (superkingdom)', 'F3ZVV4: Bacteria (superkingdom)', 'P69680: Bacteria (superkingdom)', 'Q0G2T1: Bacteria (superkingdom)', 'A0A3T0SZ22: Bacteria (superkingdom)', 'A0A4R2Z2K6: Bacteria (superkingdom)', 'L1IYP4: Eukaryota (superkingdom)', 'Q46HB1: Bacteria (superkingdom)', 'A0A149QAW7: Bacteria (superkingdom)', 'A0A1Y4L5P0: Bacteria (superkingdom)', 'A0A6B8N021: Bacteria (superkingdom)', 'D5EP71: Bacteria (superkingdom)', 'V5U2Z4: Bacteria (superkingdom)', 'A0A0E3QYF3: Archaea (superkingdom)', 'A0A0K2STK6: Eukaryota (superkingdom)', 'A0A8H7U3I1: Eukaryota (superkingdom)', 'A0A062IU58: Bacteria (superkingdom)', 'A0A178TA08: Bacteria (superkingdom)', 'A0A3G9G4Q4: Bacteria (superkingdom)', 'A0A6H9FPY5: Bacteria (superkingdom)', 'A1C5Z7: Eukaryota (superkingdom)', 'A0A0A1ZJU5: Bacteria (superkingdom)', 'A0A258HPP1: Bacteria (superkingdom)', 'G0H0Z6: Archaea (superkingdom)', 'A0A2Z4MD56: Bacteria (superkingdom)', 'G0EFF3: Archaea (superkingdom)', 'E2SD33: Bacteria (superkingdom)', 'E4TJ50: Bacteria (superkingdom)', 'A0A016XCG9: Bacteria (superkingdom)', 'A0A2S5Y0D3: Bacteria (superkingdom)', 'K9YN27: Bacteria (superkingdom)', 'Q3AFY9: Bacteria (superkingdom)', 'Q7N0M6: Bacteria (superkingdom)', 'W8KM07: Bacteria (superkingdom)', 'A0A0G9HEC5: Bacteria (superkingdom)', 'A5UJR1: Archaea (superkingdom)', 'A0A9Q9D9I3: Bacteria (superkingdom)', 'B9SXC7: Eukaryota (superkingdom)', 'C0QTA4: Bacteria (superkingdom)', 'A0A176XNC5: Bacteria (superkingdom)', 'A0A317G0I6: Bacteria (superkingdom)', 'A0A2S5CTX8: Bacteria (superkingdom)', 'U2EN72: Bacteria (superkingdom)', 'A0A248LNW8: Bacteria (superkingdom)', 'A0A4P8HC89: Bacteria (superkingdom)', 'G7UUY6: Bacteria (superkingdom)', 'A0A0E3WZH5: Archaea (superkingdom)', 'A0A165K0X5: Bacteria (superkingdom)', 'D3FBG3: Bacteria (superkingdom)', 'Q608B6: Bacteria (superkingdom)', 'A0A854Q6X9: Eukaryota (superkingdom)', 'H2IZ00: Bacteria (superkingdom)', 'A0A4V0XUI3: Bacteria (superkingdom)', 'A0A7S4GNJ2: Eukaryota (superkingdom)', 'A0A2S5WX34: Bacteria (superkingdom)', 'C1D6X6: Bacteria (superkingdom)', 'A0A418VIJ8: Bacteria (superkingdom)', 'A0A857DMN9: Bacteria (superkingdom)', 'Q7T3R4: Eukaryota (superkingdom)', 'R1D1H4: Eukaryota (superkingdom)', 'T2J0N1: Bacteria (superkingdom)', 'A0A419AVL2: Bacteria (superkingdom)', 'K0K7J4: Bacteria (superkingdom)', 'A0A4U1K1W1: Bacteria (superkingdom)', 'A0A9R0NTP8: Bacteria (superkingdom)', 'B0RC35: Bacteria (superkingdom)', 'C8XB51: Bacteria (superkingdom)', 'E4NS62: Archaea (superkingdom)', 'R9PMC6: Bacteria (superkingdom)', 'A0A1R1IDV3: Bacteria (superkingdom)', 'A0A2N6JV02: Bacteria (superkingdom)', 'A7MFK3: Bacteria (superkingdom)', 'B0BZN3: Bacteria (superkingdom)', 'F7ZEU9: Bacteria (superkingdom)', 'K9P718: Bacteria (superkingdom)', 'Q82X47: Bacteria (superkingdom)', 'Q8RUE9: Eukaryota (superkingdom)', 'A0A0M2LU39: Bacteria (superkingdom)', 'A0A3N1VXY4: Bacteria (superkingdom)', 'A0A370FPU0: Bacteria (superkingdom)', 'A0A7G5DPV1: Bacteria (superkingdom)', 'A9UR54: Eukaryota (superkingdom)', 'F0S0G1: Bacteria (superkingdom)', 'K9W4V5: Bacteria (superkingdom)', 'A0A015YIP3: Bacteria (superkingdom)', 'A0A291PMC6: Bacteria (superkingdom)', 'G8R7U9: Bacteria (superkingdom)', 'U1H1F7: Bacteria (superkingdom)', 'A0A021VMC6: Bacteria (superkingdom)', 'A0A855F5Y8: Bacteria (superkingdom)', 'A0A2W5VAZ2: Bacteria (superkingdom)', 'M0MDP9: Archaea (superkingdom)', 'A0A1X3RP39: Bacteria (superkingdom)', 'A0A653N397: Bacteria (superkingdom)', 'A0A8G2F718: Bacteria (superkingdom)', 'F4B548: Archaea (superkingdom)', 'I0ICG0: Bacteria (superkingdom)', 'A0A009TDB1: Bacteria (superkingdom)', 'A0A1G7DX68: Bacteria (superkingdom)', 'E4YA63: Eukaryota (superkingdom)', 'Q2W5V2: Bacteria (superkingdom)', 'Q3AP28: Bacteria (superkingdom)', 'Q9BLG3: Eukaryota (superkingdom)', 'A0A0D5YN10: Bacteria (superkingdom)', 'A0A0L0S493: Eukaryota (superkingdom)', 'H1YCC3: Bacteria (superkingdom)', 'L8JUH3: Bacteria (superkingdom)', 'A0A0E3SHQ9: Archaea (superkingdom)', 'A0A366XFS8: Bacteria (superkingdom)', 'E6VIW4: Bacteria (superkingdom)', 'F6FRU9: Bacteria (superkingdom)', 'A1VIM5: Bacteria (superkingdom)', 'E0TGP9: Bacteria (superkingdom)', 'A0A0E3SP24: Archaea (superkingdom)', 'A0A8H6NAG3: Eukaryota (superkingdom)', 'B8FGW0: Bacteria (superkingdom)', 'C3X1J1: Bacteria (superkingdom)', 'D9SI36: Bacteria (superkingdom)', 'E0TCV4: Bacteria (superkingdom)', 'E4U5Z1: Bacteria (superkingdom)', 'A0A094W9G3: Bacteria (superkingdom)', 'A0A7G5EC77: Bacteria (superkingdom)', 'A0A482TED1: Archaea (superkingdom)', 'A0A4Q2QWS1: Bacteria (superkingdom)', 'A3PAY4: Bacteria (superkingdom)', 'A0A173R3W6: Bacteria (superkingdom)', 'A0A1B9BUU6: Bacteria (superkingdom)', 'A0A495D4X4: Bacteria (superkingdom)', 'A0A833GZR2: Bacteria (superkingdom)', 'D0L8H3: Bacteria (superkingdom)', 'F4XTK4: Bacteria (superkingdom)', 'I4D6Z7: Bacteria (superkingdom)', 'L8H844: Eukaryota (superkingdom)', 'A0A0S6UEK9: Bacteria (superkingdom)', 'A0A1M6ZMI3: Bacteria (superkingdom)', 'U1SIR9: Bacteria (superkingdom)', 'A0A066ZTE4: Bacteria (superkingdom)', 'A9DQM8: Bacteria (superkingdom)', 'A0A0A0D6K5: Bacteria (superkingdom)', 'D6E7B3: Bacteria (superkingdom)', 'A0A562USB9: Bacteria (superkingdom)', 'C7LW87: Bacteria (superkingdom)', 'G0JRG6: Bacteria (superkingdom)', 'A0A1X6N3Q5: Eukaryota (superkingdom)', 'A0A1Y4LM49: Bacteria (superkingdom)', 'B7FSA7: Eukaryota (superkingdom)', 'E1QIU3: Bacteria (superkingdom)', 'H2CDR5: Bacteria (superkingdom)', 'Q1K433: Bacteria (superkingdom)', 'Q1QS12: Bacteria (superkingdom)', 'Q7T070: Eukaryota (superkingdom)', 'A0A0H3DR67: Bacteria (superkingdom)', 'A5CRL2: Bacteria (superkingdom)', 'A0A836M2B6: Bacteria (superkingdom)', 'E6SF19: Bacteria (superkingdom)', 'I2GD40: Bacteria (superkingdom)', 'Q18ES8: Archaea (superkingdom)', 'A0A060UWC8: Bacteria (superkingdom)', 'A0A0U1NJW3: Bacteria (superkingdom)', 'A0A7R6PER3: Bacteria (superkingdom)', 'A4G1J2: Bacteria (superkingdom)', 'A9AUR8: Bacteria (superkingdom)', 'C1N5A7: Eukaryota (superkingdom)', 'D3S2L0: Archaea (superkingdom)', 'F8IJE0: Bacteria (superkingdom)', 'A0A0D2LEF5: Eukaryota (superkingdom)', 'A0A1H1MB73: Bacteria (superkingdom)', 'W7QGE0: Bacteria (superkingdom)', 'G2T1Y3: Bacteria (superkingdom)', 'L7CG99: Bacteria (superkingdom)', 'A0A1I0C958: Bacteria (superkingdom)', 'A0KPE9: Bacteria (superkingdom)', 'A9V5W4: Eukaryota (superkingdom)', 'F5RGM7: Bacteria (superkingdom)', 'A0A1C6Z081: Bacteria (superkingdom)', 'A0A1D3GAE9: Bacteria (superkingdom)', 'A0A410JZR4: Bacteria (superkingdom)', 'A8N2H6: Eukaryota (superkingdom)', 'I1YJH7: Bacteria (superkingdom)', 'A0A2G5BI87: Eukaryota (superkingdom)', 'A0A2N6NEK4: Eukaryota (superkingdom)', 'A0A1Y0HX98: Bacteria (superkingdom)', 'C3YB74: Eukaryota (superkingdom)', 'Q1H0G2: Bacteria (superkingdom)', 'Q2FQT3: Archaea (superkingdom)', 'S0APH6: Archaea (superkingdom)', 'A0A075WEB4: Archaea (superkingdom)', 'A0A172RYW3: Bacteria (superkingdom)', 'I3C0V3: Bacteria (superkingdom)', 'A0A556SRH6: Bacteria (superkingdom)', 'A0A7U4DN04: Bacteria (superkingdom)', 'A0A1V3SSW1: Bacteria (superkingdom)', 'Q466Y3: Archaea (superkingdom)', 'A0A0A2ZRL7: Bacteria (superkingdom)', 'A0A0H3LUA3: Bacteria (superkingdom)', 'A4G0C5: Archaea (superkingdom)', 'A5E3X2: Eukaryota (superkingdom)', 'A8P923: Eukaryota (superkingdom)', 'B8EMQ8: Bacteria (superkingdom)', 'D0MFE9: Bacteria (superkingdom)', 'A0A060HFT5: Archaea (superkingdom)', 'A0A060JMP6: Bacteria (superkingdom)', 'A0A8E2UDJ3: Bacteria (superkingdom)', 'I4D6Z9: Bacteria (superkingdom)', 'Q13E03: Bacteria (superkingdom)', 'Q1JXS5: Bacteria (superkingdom)', 'A0A076PL76: Bacteria (superkingdom)', 'A0A6N2TIA4: Bacteria (superkingdom)', 'Q1AUG3: Bacteria (superkingdom)', 'A0A098S5Y7: Bacteria (superkingdom)', 'A0A7S4GNF3: Eukaryota (superkingdom)', 'A0A5J6WQU1: Bacteria (superkingdom)', 'A2SS52: Archaea (superkingdom)', 'M9RKT6: Bacteria (superkingdom)', 'A0A2K1RA77: Eukaryota (superkingdom)', 'A0A2K1RA81: Eukaryota (superkingdom)', 'A0A2S0JW39: Bacteria (superkingdom)', 'A0A2T9X1V4: Archaea (superkingdom)', 'D3F545: Bacteria (superkingdom)', 'A0A1E3PQH0: Eukaryota (superkingdom)', 'A0A1J5JH24: Bacteria (superkingdom)', 'C4Y298: Eukaryota (superkingdom)', 'Q3B6Q2: Bacteria (superkingdom)', 'Q7TNN9: Eukaryota (superkingdom)', 'A0A4Y7XC43: Bacteria (superkingdom)', 'A0A5B2V3B9: Bacteria (superkingdom)', 'B9L7N1: Bacteria (superkingdom)', 'C7M2A9: Bacteria (superkingdom)', 'D2V6Q5: Eukaryota (superkingdom)', 'E4T3F7: Bacteria (superkingdom)', 'F2YIC4: Eukaryota (superkingdom)', 'Q0G0A3: Bacteria (superkingdom)', 'A0A424WAH3: Bacteria (superkingdom)', 'B8ZYW3: Archaea (superkingdom)', 'U7VB41: Bacteria (superkingdom)', 'A0A7S0KKL8: Eukaryota (superkingdom)', 'A0A1C7EL50: Bacteria (superkingdom)', 'A0A6G9Y3Q0: Bacteria (superkingdom)', 'A0A6S5K4J1: Bacteria (superkingdom)', 'G0LFE3: Archaea (superkingdom)', 'J9VXX9: Eukaryota (superkingdom)', 'V4RHR4: Bacteria (superkingdom)', 'A0A0D7F2Y9: Bacteria (superkingdom)', 'A0A1S8D478: Bacteria (superkingdom)', 'Q47K18: Bacteria (superkingdom)', 'B9SWW9: Eukaryota (superkingdom)', 'L8H5K0: Eukaryota (superkingdom)', 'A0A369N7Y3: Bacteria (superkingdom)', 'A0A399NT81: Bacteria (superkingdom)', 'B0SLB7: Bacteria (superkingdom)', 'B4CV94: Bacteria (superkingdom)', 'E1IF27: Bacteria (superkingdom)', 'G2PRJ6: Bacteria (superkingdom)', 'A0A202B535: Bacteria (superkingdom)', 'A0A2M9D7S8: Bacteria (superkingdom)', 'Q6LMI6: Bacteria (superkingdom)', 'K2JVF8: Bacteria (superkingdom)', 'Q1Q357: Bacteria (superkingdom)', 'B8FDY8: Bacteria (superkingdom)', 'B8FL88: Bacteria (superkingdom)', 'E3H8A6: Bacteria (superkingdom)', 'H8L2Q4: Bacteria (superkingdom)', 'A0A248LMH8: Bacteria (superkingdom)', 'A0A5C5BWI6: Bacteria (superkingdom)', 'L1INN6: Eukaryota (superkingdom)', 'M7NFH3: Bacteria (superkingdom)', 'A0A060URB8: Bacteria (superkingdom)', 'K9W6F3: Bacteria (superkingdom)', 'A0A7S0D560: Eukaryota (superkingdom)', 'D2Q0J8: Bacteria (superkingdom)', 'A0A251YU48: Bacteria (superkingdom)', 'A0A6H9GEE4: Bacteria (superkingdom)', 'A0A8F5ZDT8: Archaea (superkingdom)', 'C1G973: Eukaryota (superkingdom)', 'M0D580: Archaea (superkingdom)', 'A0A1Y5E3E3: Bacteria (superkingdom)', 'A0A328Q6M1: Archaea (superkingdom)', 'Q7UGU7: Bacteria (superkingdom)', 'A0A660CH85: Bacteria (superkingdom)', 'E4T3F3: Bacteria (superkingdom)', 'A0A6H9GFU4: Bacteria (superkingdom)', 'A3XNG6: Bacteria (superkingdom)', 'B9LU00: Archaea (superkingdom)', 'E4RTK5: Bacteria (superkingdom)', 'H6LKH9: Bacteria (superkingdom)', 'Q0AT01: Bacteria (superkingdom)', 'A0A330GB00: Bacteria (superkingdom)', 'A0A657K391: Bacteria (superkingdom)', 'Q2N625: Bacteria 

In [75]:
linage

['A1D2Y5: Eukaryota (superkingdom)',
 'M8E0R3: Bacteria (superkingdom)',
 'A0A2G3DSU6: Bacteria (superkingdom)',
 'A0A328EMN2: Bacteria (superkingdom)',
 'A0A6A1TYJ4: Bacteria (superkingdom)',
 'D3RMV7: Bacteria (superkingdom)',
 'F0J3F9: Bacteria (superkingdom)',
 'G2ZN72: Bacteria (superkingdom)',
 'I0KDC6: Bacteria (superkingdom)',
 'A0A081N2G5: Bacteria (superkingdom)',
 'A0A144NLT9: Bacteria (superkingdom)',
 'B4D7W2: Bacteria (superkingdom)',
 'F3QNA7: Bacteria (superkingdom)',
 'Q4WHC6: Eukaryota (superkingdom)',
 'Q8JI14: Eukaryota (superkingdom)',
 'A0A395VB65: Bacteria (superkingdom)',
 'A0A975GIX9: Bacteria (superkingdom)',
 'Q5UZ98: Archaea (superkingdom)',
 'A0A4R4K1P9: Bacteria (superkingdom)',
 'A0A7T4WEP4: Bacteria (superkingdom)',
 'C6LBD3: Bacteria (superkingdom)',
 'D5V7B3: Bacteria (superkingdom)',
 'A0A4R3ZNW3: Bacteria (superkingdom)',
 'A9BQZ4: Bacteria (superkingdom)',
 'A0A642KQG8: Bacteria (superkingdom)',
 'A9BIZ7: Bacteria (superkingdom)',
 'K0NJH2: Bacteria (superkingdom)',
 'Q2IK04: Bacteria (superkingdom)',
 'T2KJ59: Bacteria (superkingdom)',
 'A0A1B9M5B8: Bacteria (superkingdom)',
 'A0A323UE08: Bacteria (superkingdom)',
 'E8RLT5: Bacteria (superkingdom)',
 'F6G5I9: Bacteria (superkingdom)',
 'G3A431: Bacteria (superkingdom)',
 'G4H971: Bacteria (superkingdom)',
 'L1J6I4: Eukaryota (superkingdom)',
 'M0J579: Archaea (superkingdom)',
 'A0A377PBY1: Bacteria (superkingdom)',
 'A0A401WUW1: Bacteria (superkingdom)',
 'L1IYW7: Eukaryota (superkingdom)',
 'A0A315S845: Bacteria (superkingdom)',
 'A0A6M3ZKU5: Bacteria (superkingdom)',
 'A0A502GPV4: Bacteria (superkingdom)',
 'A0A9J9BAE8: Bacteria (superkingdom)',
 'A1AVV2: Bacteria (superkingdom)',
 'B1XZU2: Bacteria (superkingdom)',
 'Q5P1S8: Bacteria (superkingdom)',
 'A0A0F5EZP7: Bacteria (superkingdom)',
 'A0A4R7GKA0: Bacteria (superkingdom)',
 'A0A2T4UWF1: Bacteria (superkingdom)',
 'A0A3E0X011: Bacteria (superkingdom)',
 'A0A4R8H081: Bacteria (superkingdom)',
 'C7LQR9: Bacteria (superkingdom)',
 'A0A0A2A0Y9: Bacteria (superkingdom)',
 'A0A0A2A5X1: Bacteria (superkingdom)',
 'A0A7T5BFQ2: Bacteria (superkingdom)',
 'A3U857: Bacteria (superkingdom)',
 'E1V4T3: Bacteria (superkingdom)',
 'F0J7D3: Bacteria (superkingdom)',
 'M7XJ51: Bacteria (superkingdom)',
 'Q1K0H9: Bacteria (superkingdom)',
 'A0A2S5XAB8: Bacteria (superkingdom)',
 'A0A366IE34: Bacteria (superkingdom)',
 'Q1Z695: Bacteria (superkingdom)',
 'A0A8G2IZM3: Bacteria (superkingdom)',
 'G3IYW2: Bacteria (superkingdom)',
 'A0A2G5BGA9: Eukaryota (superkingdom)',
 'A0A5M4AUM9: Bacteria (superkingdom)',
 'E3HJW8: Bacteria (superkingdom)',
 'U1PIR6: Archaea (superkingdom)',
 'A0A1B9N3H7: Bacteria (superkingdom)',
 'A0A2S5WV24: Bacteria (superkingdom)',
 'A0A6U2BIY7: Eukaryota (superkingdom)',
 'A0A833LX85: Bacteria (superkingdom)',
 'I9P003: Bacteria (superkingdom)',
 'K8VZC6: Bacteria (superkingdom)',
 'L1IUV5: Eukaryota (superkingdom)',
 'A0A0K2STQ7: Eukaryota (superkingdom)',
 'A0A2H1HV86: Bacteria (superkingdom)',
 'Q2GX26: Eukaryota (superkingdom)',
 'A0A074KY88: Bacteria (superkingdom)',
 'A0A858ZNJ3: Bacteria (superkingdom)',
 'A0A3P2A7W8: Bacteria (superkingdom)',
 'A0A7S4GND2: Eukaryota (superkingdom)',
 'O26757: Archaea (superkingdom)',
 'Q46G49: Archaea (superkingdom)',
 'A0A140NHJ5: Bacteria (superkingdom)',
 'A0A2S8GF54: Bacteria (superkingdom)',
 'B1JZ69: Bacteria (superkingdom)',
 'E5Y678: Bacteria (superkingdom)',
 'A0A149U2G9: Bacteria (superkingdom)',
 'A0A9Q5QVI9: Bacteria (superkingdom)',
 'Q18PF5: Eukaryota (superkingdom)',
 'A0A317FZW2: Bacteria (superkingdom)',
 'G5EB13: Eukaryota (superkingdom)',
 'Q1YDY8: Bacteria (superkingdom)',
 'A0A1X4GBG2: Bacteria (superkingdom)',
 'A0A4Q7Y9I7: Bacteria (superkingdom)',
 'I0HKQ8: Bacteria (superkingdom)',
 'A0A097R891: Bacteria (superkingdom)',
 'A0A7S4GMD8: Eukaryota (superkingdom)',
 'Q488X2: Bacteria (superkingdom)',
 'U3PCH5: Bacteria (superkingdom)',
 'A0A378YR15: Bacteria (superkingdom)',
 'I1YG38: Bacteria (superkingdom)',
 'F5XN43: Bacteria (superkingdom)',
 'Q1IWN6: Bacteria (superkingdom)',
 'A0A1E3PSK5: Eukaryota (superkingdom)',
 'A0A833H2R7: Bacteria (superkingdom)',
 'A0A2T0XPP2: Bacteria (superkingdom)',
 'A0A399T909: Bacteria (superkingdom)',
 'L8GGA0: Eukaryota (superkingdom)',
 'A0A0D8BQX6: Bacteria (superkingdom)',
 'A0A1M5ZVP9: Bacteria (superkingdom)',
 'I5BYV5: Bacteria (superkingdom)',
 'A0A0K2STH0: Eukaryota (superkingdom)',
 'A0A2N6K4Y5: Bacteria (superkingdom)',
 'A0A1B9JZS5: Bacteria (superkingdom)',
 'A0A2W0GQV0: Bacteria (superkingdom)',
 'A0A369MHK2: Bacteria (superkingdom)',
 'A0A087L0B9: Bacteria (superkingdom)',
 'A0A0A2AMW2: Bacteria (superkingdom)',
 'A0A377PLP5: Bacteria (superkingdom)',
 'Q6BJI7: Eukaryota (superkingdom)',
 'Q7S5K0: Eukaryota (superkingdom)',
 'Q7Z1M1: Eukaryota (superkingdom)',
 'T2JFS5: Bacteria (superkingdom)',
 'W0JIB3: Archaea (superkingdom)',
 'A0A1V2XMU9: Bacteria (superkingdom)',
 'A0A2S6GKN5: Bacteria (superkingdom)',
 'A0A7G5DK18: Bacteria (superkingdom)',
 'A0A830ZZN8: Bacteria (superkingdom)',
 'A0A8B4RWH8: Bacteria (superkingdom)',
 'A0A9Q6P4A5: Bacteria (superkingdom)',
 'B8ENL9: Bacteria (superkingdom)',
 'Q9QXP0: Eukaryota (superkingdom)',
 'A0A060URC3: Bacteria (superkingdom)',
 'A0A2W5HTC3: Bacteria (superkingdom)',
 'A7S731: Eukaryota (superkingdom)',
 'A0A1Y0UZX2: Bacteria (superkingdom)',
 'A0A257TE48: Bacteria (superkingdom)',
 'Q2RVB5: Bacteria (superkingdom)',
 'Q605Y6: Bacteria (superkingdom)',
 'A0A918MJ52: Bacteria (superkingdom)',
 'K6W5X0: Bacteria (superkingdom)',
 'V4AP67: Eukaryota (superkingdom)',
 'A0A7Z0V0A4: Bacteria (superkingdom)',
 'C0GKN4: Bacteria (superkingdom)',
 'A9HMD6: Bacteria (superkingdom)',
 'B1ZSW9: Bacteria (superkingdom)',
 'K5DBA0: Bacteria (superkingdom)',
 'V4REY8: Bacteria (superkingdom)',
 'A0A0D2KGN8: Eukaryota (superkingdom)',
 'A0A242NIL1: Bacteria (superkingdom)',
 'A8PXT8: Eukaryota (superkingdom)',
 'B7X047: Bacteria (superkingdom)',
 'D2ZRW2: Archaea (superkingdom)',
 'H1Y7T6: Bacteria (superkingdom)',
 'Q97L80: Bacteria (superkingdom)',
 'A0A0S6UHP2: Bacteria (superkingdom)',
 'A0A323UDG5: Bacteria (superkingdom)',
 'E3I393: Bacteria (superkingdom)',
 'A0A4V2X6C2: Bacteria (superkingdom)',
 'D7G265: Eukaryota (superkingdom)',
 'A6LRS5: Bacteria (superkingdom)',
 'D8J4C6: Archaea (superkingdom)',
 'F2NGJ8: Bacteria (superkingdom)',
 'A0A0E9NHV4: Eukaryota (superkingdom)',
 'A1CQ21: Eukaryota (superkingdom)',
 'A0A6N2Z556: Bacteria (superkingdom)',
 'Q0BWD0: Bacteria (superkingdom)',
 'A0A071MMV1: Bacteria (superkingdom)',
 'A0A168EVK8: Bacteria (superkingdom)',
 'B3DUX7: Bacteria (superkingdom)',
 'F5L8M7: Bacteria (superkingdom)',
 'G7WJN0: Bacteria (superkingdom)',
 'Q0BQ69: Bacteria (superkingdom)',
 'A0A3N2SFS2: Bacteria (superkingdom)',
 'A0A9Y2AG30: Bacteria (superkingdom)',
 'A0AA46Q839: Bacteria (superkingdom)',
 'E8RSE4: Bacteria (superkingdom)',
 'F6BEI0: Archaea (superkingdom)',
 'I1DSU5: Bacteria (superkingdom)',
 'I4C9L2: Bacteria (superkingdom)',
 'Q5QVH2: Bacteria (superkingdom)',
 'A0A068NPW2: Bacteria (superkingdom)',
 'A0A6J5IRX5: Bacteria (superkingdom)',
 'A0A3R9Q7C4: Bacteria (superkingdom)',
 'A3ZT81: Bacteria (superkingdom)',
 'K0ER80: Bacteria (superkingdom)',
 'Q0VLH1: Bacteria (superkingdom)',
 'Q2KZK9: Bacteria (superkingdom)',
 'R9GM11: Bacteria (superkingdom)',
 'A0A0T7GZ59: Bacteria (superkingdom)',
 'A0A1G5PWV0: Bacteria (superkingdom)',
 'S5ABR8: Bacteria (superkingdom)',
 'W7QGM4: Bacteria (superkingdom)',
 'F5Y3C1: Bacteria (superkingdom)',
 'I8TC71: Bacteria (superkingdom)',
 'M1P5F0: Bacteria (superkingdom)',
 'A0A149RYW7: Bacteria (superkingdom)',
 'A0A1J1JH03: Bacteria (superkingdom)',
 'A0A1U9Z147: Bacteria (superkingdom)',
 'A0A243SC06: Bacteria (superkingdom)',
 'A0A3G9G2C9: Bacteria (superkingdom)',
 'I4C9L0: Bacteria (superkingdom)',
 'I4D1H5: Bacteria (superkingdom)',
 'Q7W7D3: Bacteria (superkingdom)',
 'A0A0B4M163: Eukaryota (superkingdom)',
 'A0A1M7UEG2: Bacteria (superkingdom)',
 'A7HT14: Bacteria (superkingdom)',
 'C8X554: Bacteria (superkingdom)',
 'A0A127PIQ9: Bacteria (superkingdom)',
 'A0A1B9JPL5: Bacteria (superkingdom)',
 'W5WIX6: Bacteria (superkingdom)',
 'A0AA40J491: Bacteria (superkingdom)',
 'D8PD01: Bacteria (superkingdom)',
 'A0A251XU71: Bacteria (superkingdom)',
 'A0A2N6P374: Eukaryota (superkingdom)',
 'B3QVV5: Bacteria (superkingdom)',
 'K1K628: Bacteria (superkingdom)',
 'A0A1E2SKM1: Bacteria (superkingdom)',
 'A0A1I0BYN1: Bacteria (superkingdom)',
 'A0A556RTU3: Bacteria (superkingdom)',
 'A0A829X098: Bacteria (superkingdom)',
 'D5EP68: Bacteria (superkingdom)',
 'F0J6E8: Bacteria (superkingdom)',
 'A0A073CP02: Bacteria (superkingdom)',
 'A0A127JTU2: Bacteria (superkingdom)',
 'C7BJG7: Bacteria (superkingdom)',
 'D2BUJ8: Bacteria (superkingdom)',
 'B8IZX4: Bacteria (superkingdom)',
 'I3R0S7: Archaea (superkingdom)',
 'A0A3E2TW06: Bacteria (superkingdom)',
 'B1Y0E5: Bacteria (superkingdom)',
 'E6ME92: Bacteria (superkingdom)',
 'A0A251Y3N4: Bacteria (superkingdom)',
 'A0A380S5X4: Bacteria (superkingdom)',
 'F0YLV7: Eukaryota (superkingdom)',
 'F8D7H6: Archaea (superkingdom)',
 'Q31CR9: Bacteria (superkingdom)',
 'W0E077: Bacteria (superkingdom)',
 'A5DYQ2: Eukaryota (superkingdom)',
 'A8LKQ0: Bacteria (superkingdom)',
 'A0A4Y1MSE7: Bacteria (superkingdom)',
 'A3TVQ9: Bacteria (superkingdom)',
 'F2B2B8: Bacteria (superkingdom)',
 'L0K9M1: Bacteria (superkingdom)',
 'Q4WT12: Eukaryota (superkingdom)',
 'Q8ERT9: Bacteria (superkingdom)',
 'A0A1H3WA00: Bacteria (superkingdom)',
 'A0A1U9YY82: Bacteria (superkingdom)',
 'A1DG05: Eukaryota (superkingdom)',
 'B8GGC1: Archaea (superkingdom)',
 'F3ZVV4: Bacteria (superkingdom)',
 'P69680: Bacteria (superkingdom)',
 'Q0G2T1: Bacteria (superkingdom)',
 'A0A3T0SZ22: Bacteria (superkingdom)',
 'A0A4R2Z2K6: Bacteria (superkingdom)',
 'L1IYP4: Eukaryota (superkingdom)',
 'Q46HB1: Bacteria (superkingdom)',
 'A0A149QAW7: Bacteria (superkingdom)',
 'A0A1Y4L5P0: Bacteria (superkingdom)',
 'A0A6B8N021: Bacteria (superkingdom)',
 'D5EP71: Bacteria (superkingdom)',
 'V5U2Z4: Bacteria (superkingdom)',
 'A0A0E3QYF3: Archaea (superkingdom)',
 'A0A0K2STK6: Eukaryota (superkingdom)',
 'A0A8H7U3I1: Eukaryota (superkingdom)',
 'A0A062IU58: Bacteria (superkingdom)',
 'A0A178TA08: Bacteria (superkingdom)',
 'A0A3G9G4Q4: Bacteria (superkingdom)',
 'A0A6H9FPY5: Bacteria (superkingdom)',
 'A1C5Z7: Eukaryota (superkingdom)',
 'A0A0A1ZJU5: Bacteria (superkingdom)',
 'A0A258HPP1: Bacteria (superkingdom)',
 'G0H0Z6: Archaea (superkingdom)',
 'A0A2Z4MD56: Bacteria (superkingdom)',
 'G0EFF3: Archaea (superkingdom)',
 'E2SD33: Bacteria (superkingdom)',
 'E4TJ50: Bacteria (superkingdom)',
 'A0A016XCG9: Bacteria (superkingdom)',
 'A0A2S5Y0D3: Bacteria (superkingdom)',
 'K9YN27: Bacteria (superkingdom)',
 'Q3AFY9: Bacteria (superkingdom)',
 'Q7N0M6: Bacteria (superkingdom)',
 'W8KM07: Bacteria (superkingdom)',
 'A0A0G9HEC5: Bacteria (superkingdom)',
 'A5UJR1: Archaea (superkingdom)',
 'A0A9Q9D9I3: Bacteria (superkingdom)',
 'B9SXC7: Eukaryota (superkingdom)',
 'C0QTA4: Bacteria (superkingdom)',
 'A0A176XNC5: Bacteria (superkingdom)',
 'A0A317G0I6: Bacteria (superkingdom)',
 'A0A2S5CTX8: Bacteria (superkingdom)',
 'U2EN72: Bacteria (superkingdom)',
 'A0A248LNW8: Bacteria (superkingdom)',
 'A0A4P8HC89: Bacteria (superkingdom)',
 'G7UUY6: Bacteria (superkingdom)',
 'A0A0E3WZH5: Archaea (superkingdom)',
 'A0A165K0X5: Bacteria (superkingdom)',
 'D3FBG3: Bacteria (superkingdom)',
 'Q608B6: Bacteria (superkingdom)',
 'A0A854Q6X9: Eukaryota (superkingdom)',
 'H2IZ00: Bacteria (superkingdom)',
 'A0A4V0XUI3: Bacteria (superkingdom)',
 'A0A7S4GNJ2: Eukaryota (superkingdom)',
 'A0A2S5WX34: Bacteria (superkingdom)',
 'C1D6X6: Bacteria (superkingdom)',
 'A0A418VIJ8: Bacteria (superkingdom)',
 'A0A857DMN9: Bacteria (superkingdom)',
 'Q7T3R4: Eukaryota (superkingdom)',
 'R1D1H4: Eukaryota (superkingdom)',
 'T2J0N1: Bacteria (superkingdom)',
 'A0A419AVL2: Bacteria (superkingdom)',
 'K0K7J4: Bacteria (superkingdom)',
 'A0A4U1K1W1: Bacteria (superkingdom)',
 'A0A9R0NTP8: Bacteria (superkingdom)',
 'B0RC35: Bacteria (superkingdom)',
 'C8XB51: Bacteria (superkingdom)',
 'E4NS62: Archaea (superkingdom)',
 'R9PMC6: Bacteria (superkingdom)',
 'A0A1R1IDV3: Bacteria (superkingdom)',
 'A0A2N6JV02: Bacteria (superkingdom)',
 'A7MFK3: Bacteria (superkingdom)',
 'B0BZN3: Bacteria (superkingdom)',
 'F7ZEU9: Bacteria (superkingdom)',
 'K9P718: Bacteria (superkingdom)',
 'Q82X47: Bacteria (superkingdom)',
 'Q8RUE9: Eukaryota (superkingdom)',
 'A0A0M2LU39: Bacteria (superkingdom)',
 'A0A3N1VXY4: Bacteria (superkingdom)',
 'A0A370FPU0: Bacteria (superkingdom)',
 'A0A7G5DPV1: Bacteria (superkingdom)',
 'A9UR54: Eukaryota (superkingdom)',
 'F0S0G1: Bacteria (superkingdom)',
 'K9W4V5: Bacteria (superkingdom)',
 'A0A015YIP3: Bacteria (superkingdom)',
 'A0A291PMC6: Bacteria (superkingdom)',
 'G8R7U9: Bacteria (superkingdom)',
 'U1H1F7: Bacteria (superkingdom)',
 'A0A021VMC6: Bacteria (superkingdom)',
 'A0A855F5Y8: Bacteria (superkingdom)',
 'A0A2W5VAZ2: Bacteria (superkingdom)',
 'M0MDP9: Archaea (superkingdom)',
 'A0A1X3RP39: Bacteria (superkingdom)',
 'A0A653N397: Bacteria (superkingdom)',
 'A0A8G2F718: Bacteria (superkingdom)',
 'F4B548: Archaea (superkingdom)',
 'I0ICG0: Bacteria (superkingdom)',
 'A0A009TDB1: Bacteria (superkingdom)',
 'A0A1G7DX68: Bacteria (superkingdom)',
 'E4YA63: Eukaryota (superkingdom)',
 'Q2W5V2: Bacteria (superkingdom)',
 'Q3AP28: Bacteria (superkingdom)',
 'Q9BLG3: Eukaryota (superkingdom)',
 'A0A0D5YN10: Bacteria (superkingdom)',
 'A0A0L0S493: Eukaryota (superkingdom)',
 'H1YCC3: Bacteria (superkingdom)',
 'L8JUH3: Bacteria (superkingdom)',
 'A0A0E3SHQ9: Archaea (superkingdom)',
 'A0A366XFS8: Bacteria (superkingdom)',
 'E6VIW4: Bacteria (superkingdom)',
 'F6FRU9: Bacteria (superkingdom)',
 'A1VIM5: Bacteria (superkingdom)',
 'E0TGP9: Bacteria (superkingdom)',
 'A0A0E3SP24: Archaea (superkingdom)',
 'A0A8H6NAG3: Eukaryota (superkingdom)',
 'B8FGW0: Bacteria (superkingdom)',
 'C3X1J1: Bacteria (superkingdom)',
 'D9SI36: Bacteria (superkingdom)',
 'E0TCV4: Bacteria (superkingdom)',
 'E4U5Z1: Bacteria (superkingdom)',
 'A0A094W9G3: Bacteria (superkingdom)',
 'A0A7G5EC77: Bacteria (superkingdom)',
 'A0A482TED1: Archaea (superkingdom)',
 'A0A4Q2QWS1: Bacteria (superkingdom)',
 'A3PAY4: Bacteria (superkingdom)',
 'A0A173R3W6: Bacteria (superkingdom)',
 'A0A1B9BUU6: Bacteria (superkingdom)',
 'A0A495D4X4: Bacteria (superkingdom)',
 'A0A833GZR2: Bacteria (superkingdom)',
 'D0L8H3: Bacteria (superkingdom)',
 'F4XTK4: Bacteria (superkingdom)',
 'I4D6Z7: Bacteria (superkingdom)',
 'L8H844: Eukaryota (superkingdom)',
 'A0A0S6UEK9: Bacteria (superkingdom)',
 'A0A1M6ZMI3: Bacteria (superkingdom)',
 'U1SIR9: Bacteria (superkingdom)',
 'A0A066ZTE4: Bacteria (superkingdom)',
 'A9DQM8: Bacteria (superkingdom)',
 'A0A0A0D6K5: Bacteria (superkingdom)',
 'D6E7B3: Bacteria (superkingdom)',
 'A0A562USB9: Bacteria (superkingdom)',
 'C7LW87: Bacteria (superkingdom)',
 'G0JRG6: Bacteria (superkingdom)',
 'A0A1X6N3Q5: Eukaryota (superkingdom)',
 'A0A1Y4LM49: Bacteria (superkingdom)',
 'B7FSA7: Eukaryota (superkingdom)',
 'E1QIU3: Bacteria (superkingdom)',
 'H2CDR5: Bacteria (superkingdom)',
 'Q1K433: Bacteria (superkingdom)',
 'Q1QS12: Bacteria (superkingdom)',
 'Q7T070: Eukaryota (superkingdom)',
 'A0A0H3DR67: Bacteria (superkingdom)',
 'A5CRL2: Bacteria (superkingdom)',
 'A0A836M2B6: Bacteria (superkingdom)',
 'E6SF19: Bacteria (superkingdom)',
 'I2GD40: Bacteria (superkingdom)',
 'Q18ES8: Archaea (superkingdom)',
 'A0A060UWC8: Bacteria (superkingdom)',
 'A0A0U1NJW3: Bacteria (superkingdom)',
 'A0A7R6PER3: Bacteria (superkingdom)',
 'A4G1J2: Bacteria (superkingdom)',
 'A9AUR8: Bacteria (superkingdom)',
 'C1N5A7: Eukaryota (superkingdom)',
 'D3S2L0: Archaea (superkingdom)',
 'F8IJE0: Bacteria (superkingdom)',
 'A0A0D2LEF5: Eukaryota (superkingdom)',
 'A0A1H1MB73: Bacteria (superkingdom)',
 'W7QGE0: Bacteria (superkingdom)',
 'G2T1Y3: Bacteria (superkingdom)',
 'L7CG99: Bacteria (superkingdom)',
 'A0A1I0C958: Bacteria (superkingdom)',
 'A0KPE9: Bacteria (superkingdom)',
 'A9V5W4: Eukaryota (superkingdom)',
 'F5RGM7: Bacteria (superkingdom)',
 'A0A1C6Z081: Bacteria (superkingdom)',
 'A0A1D3GAE9: Bacteria (superkingdom)',
 'A0A410JZR4: Bacteria (superkingdom)',
 'A8N2H6: Eukaryota (superkingdom)',
 'I1YJH7: Bacteria (superkingdom)',
 'A0A2G5BI87: Eukaryota (superkingdom)',
 'A0A2N6NEK4: Eukaryota (superkingdom)',
 'A0A1Y0HX98: Bacteria (superkingdom)',
 'C3YB74: Eukaryota (superkingdom)',
 'Q1H0G2: Bacteria (superkingdom)',
 'Q2FQT3: Archaea (superkingdom)',
 'S0APH6: Archaea (superkingdom)',
 'A0A075WEB4: Archaea (superkingdom)',
 'A0A172RYW3: Bacteria (superkingdom)',
 'I3C0V3: Bacteria (superkingdom)',
 'A0A556SRH6: Bacteria (superkingdom)',
 'A0A7U4DN04: Bacteria (superkingdom)',
 'A0A1V3SSW1: Bacteria (superkingdom)',
 'Q466Y3: Archaea (superkingdom)',
 'A0A0A2ZRL7: Bacteria (superkingdom)',
 'A0A0H3LUA3: Bacteria (superkingdom)',
 'A4G0C5: Archaea (superkingdom)',
 'A5E3X2: Eukaryota (superkingdom)',
 'A8P923: Eukaryota (superkingdom)',
 'B8EMQ8: Bacteria (superkingdom)',
 'D0MFE9: Bacteria (superkingdom)',
 'A0A060HFT5: Archaea (superkingdom)',
 'A0A060JMP6: Bacteria (superkingdom)',
 'A0A8E2UDJ3: Bacteria (superkingdom)',
 'I4D6Z9: Bacteria (superkingdom)',
 'Q13E03: Bacteria (superkingdom)',
 'Q1JXS5: Bacteria (superkingdom)',
 'A0A076PL76: Bacteria (superkingdom)',
 'A0A6N2TIA4: Bacteria (superkingdom)',
 'Q1AUG3: Bacteria (superkingdom)',
 'A0A098S5Y7: Bacteria (superkingdom)',
 'A0A7S4GNF3: Eukaryota (superkingdom)',
 'A0A5J6WQU1: Bacteria (superkingdom)',
 'A2SS52: Archaea (superkingdom)',
 'M9RKT6: Bacteria (superkingdom)',
 'A0A2K1RA77: Eukaryota (superkingdom)',
 'A0A2K1RA81: Eukaryota (superkingdom)',
 'A0A2S0JW39: Bacteria (superkingdom)',
 'A0A2T9X1V4: Archaea (superkingdom)',
 'D3F545: Bacteria (superkingdom)',
 'A0A1E3PQH0: Eukaryota (superkingdom)',
 'A0A1J5JH24: Bacteria (superkingdom)',
 'C4Y298: Eukaryota (superkingdom)',
 'Q3B6Q2: Bacteria (superkingdom)',
 'Q7TNN9: Eukaryota (superkingdom)',
 'A0A4Y7XC43: Bacteria (superkingdom)',
 'A0A5B2V3B9: Bacteria (superkingdom)',
 'B9L7N1: Bacteria (superkingdom)',
 'C7M2A9: Bacteria (superkingdom)',
 'D2V6Q5: Eukaryota (superkingdom)',
 'E4T3F7: Bacteria (superkingdom)',
 'F2YIC4: Eukaryota (superkingdom)',
 'Q0G0A3: Bacteria (superkingdom)',
 'A0A424WAH3: Bacteria (superkingdom)',
 'B8ZYW3: Archaea (superkingdom)',
 'U7VB41: Bacteria (superkingdom)',
 'A0A7S0KKL8: Eukaryota (superkingdom)',
 'A0A1C7EL50: Bacteria (superkingdom)',
 'A0A6G9Y3Q0: Bacteria (superkingdom)',
 'A0A6S5K4J1: Bacteria (superkingdom)',
 'G0LFE3: Archaea (superkingdom)',
 'J9VXX9: Eukaryota (superkingdom)',
 'V4RHR4: Bacteria (superkingdom)',
 'A0A0D7F2Y9: Bacteria (superkingdom)',
 'A0A1S8D478: Bacteria (superkingdom)',
 'Q47K18: Bacteria (superkingdom)',
 'B9SWW9: Eukaryota (superkingdom)',
 'L8H5K0: Eukaryota (superkingdom)',
 'A0A369N7Y3: Bacteria (superkingdom)',
 'A0A399NT81: Bacteria (superkingdom)',
 'B0SLB7: Bacteria (superkingdom)',
 'B4CV94: Bacteria (superkingdom)',
 'E1IF27: Bacteria (superkingdom)',
 'G2PRJ6: Bacteria (superkingdom)',
 'A0A202B535: Bacteria (superkingdom)',
 'A0A2M9D7S8: Bacteria (superkingdom)',
 'Q6LMI6: Bacteria (superkingdom)',
 'K2JVF8: Bacteria (superkingdom)',
 'Q1Q357: Bacteria (superkingdom)',
 'B8FDY8: Bacteria (superkingdom)',
 'B8FL88: Bacteria (superkingdom)',
 'E3H8A6: Bacteria (superkingdom)',
 'H8L2Q4: Bacteria (superkingdom)',
 'A0A248LMH8: Bacteria (superkingdom)',
 'A0A5C5BWI6: Bacteria (superkingdom)',
 'L1INN6: Eukaryota (superkingdom)',
 'M7NFH3: Bacteria (superkingdom)',
 'A0A060URB8: Bacteria (superkingdom)',
 'K9W6F3: Bacteria (superkingdom)',
 'A0A7S0D560: Eukaryota (superkingdom)',
 'D2Q0J8: Bacteria (superkingdom)',
 'A0A251YU48: Bacteria (superkingdom)',
 'A0A6H9GEE4: Bacteria (superkingdom)',
 'A0A8F5ZDT8: Archaea (superkingdom)',
 'C1G973: Eukaryota (superkingdom)',

In [169]:
king = []
eyed = []

for y in linige:
    eyed.append(y.split(':')[0])
    king.append(y.split(' ')[1])

In [170]:
df2['eyed'] = eyed

In [171]:
df2['kingdom'] = king

In [172]:
df2

               0  four first PheGate TwinHis SN        eyed    kingdom
0     A0A858ZNJ3  YNSA     Y      FF      HH  S  A0A858ZNJ3   Bacteria
1     A0A1H9M798  YNNA     Y      FF      HH  S  A0A1H9M798   Bacteria
2         B0DY50  YNSM     Y      FF      HH  S      B0DY50  Eukaryota
3         P69680  YNSG     Y      FF      HH  S      P69680   Bacteria
4     A0A3G9G4Q4  YNAA     Y      FF      HH  S  A0A3G9G4Q4   Bacteria
...          ...   ...   ...     ...     ... ..         ...        ...
1276      A0LV78  YNAA     Y      FF      HH  S      A0LV78   Bacteria
1277      K5DBA0  ENDT     E      FF      HH  N      K5DBA0   Bacteria
1278      B8IZX4  YRSA     Y      FF      HH  S      B8IZX4   Bacteria
1279      A8LKQ0  ENLS     E      FF      HH  N      A8LKQ0   Bacteria
1280  A0A5C6LWQ1  YNSA     Y      FF      HH  I  A0A5C6LWQ1   Bacteria

[1281 rows x 8 columns]

In [173]:
df2 = df2.drop('eyed', axis=1)

In [81]:
df_new

           first residue four residues    kingdom
0
A1D2Y5                 Y          YSSA  Eukaryota
M8E0R3                 E          EQSA   Bacteria
A0A2G3DSU6             E          ENDT   Bacteria
A0A328EMN2             Y          YNSA   Bacteria
A0A6A1TYJ4             Y          YNSA   Bacteria
...                  ...           ...        ...
G7WFX2                 E          ENTT   Bacteria
Q6BK68                 Y          YSTC  Eukaryota
Q9QUT0                 M          M--L  Eukaryota
A0A1E5C7W4             E          EIDA   Bacteria
A0A1Y3U5V2             Y          YNNG   Bacteria

[1281 rows x 3 columns]

In [82]:
df_new['Phe Gate'] = right

In [83]:
df_new

           first residue four residues    kingdom Phe Gate
0
A1D2Y5                 Y          YSSA  Eukaryota       FF
M8E0R3                 E          EQSA   Bacteria       FF
A0A2G3DSU6             E          ENDT   Bacteria       FF
A0A328EMN2             Y          YNSA   Bacteria       FF
A0A6A1TYJ4             Y          YNSA   Bacteria       FF
...                  ...           ...        ...      ...
G7WFX2                 E          ENTT   Bacteria       FF
Q6BK68                 Y          YSTC  Eukaryota       FF
Q9QUT0                 M          M--L  Eukaryota       FF
A0A1E5C7W4             E          EIDA   Bacteria       FF
A0A1Y3U5V2             Y          YNNG   Bacteria       FF

[1281 rows x 4 columns]

In [247]:
df_new.to_csv('annotations.csv')

In [144]:
alignment = AlignIO.read("all8concat.fasta", "fasta")

print("Number of rows: %i" % len(alignment))


for record in alignment:

    print("%s - %s" % (record.seq, record.id))

Number of rows: 1281
-------------------------------------DS-GDTA-----WMLTSTLLVI-LMTIPGLALFYG---------GLG-------R---------KNMLSVLMQVFVVFSLISIL--------WSLYGYSL-------A-----------------------------------------------------------------ATI-PEYV----------FLAFQGTFAAITVALVVGS-FAERMRF----------------------ATI---PE---------------YV-FLA-FQGTFAAITVAL-VVGSFAER----MR----F-------R-E-A-FT---PHSLT------LTMVGASLLWV--------GWFG-FNAGSA-------------------------------DGALDFAGGTVVHINAGIAGLVGAYMVG-KR-I--------G--F-------DD-----AFDVFGVHGVGGIVG-AI-LTGVFA----AQ-------GLG---------G-----------------KGKASMLGA-------------ASGAVAGLVAVTPAAGF-VGP------- - A0A858ZNJ3
--------------------------------------D-ADTV-----WILVSTALVL-LMTLPGIALFYA---------GMV-------R-R--------NVLNTMASVLGITCLVSLL--------WFAVGYSW-------AF-------TPG------------------------------------------------------SHI-PESV----------YAMFQLAFAIITAALVVGA-LVERMRF-----------------------HI---PE---------------SV-YAM-FQLAFAIITAAL-VVGALVER----MR----F-------R-E-A-FE---PYNLG------LTMVGASLLWV--------GWFG-FNAGSA--------------------------AR---MGALDFAGGAVVHINAGVAGLVCAWFLG-PR-K--------G--Y-------DD-----SLDVFGVHGIGGIVG-AL-LTGVLA----DK-------SIG---------------------------RGRGSLLGL-------------CSGLVAGLVAITPAAGF-VTP------- - A0A1H9M798
------------------------------------YSP-GDIA-----WVLASTALVW-IMM-PGVGFFYS---------GLL-------R---------KNALSMIYLSMMTSAVVSFQ--------WVFWGYSL-------TI-------V-------------------------------------------------------SARI-PSIV----------FCVYQLMFAAFTPMIAVGA-FAE-----------------------IVSARI---PS---------------IV-FCV-YQLMFAAFTPMI-AVGAFAE-------------------------YE---PHNTT------YVVLGTVFLWF--------GWFG-FNGGSA--------------------------------------GGTPVHISSGTAALAISIYLG-QR-HGYGSEELAG--Y-------DD-----ALDIFASHAVGGLVG-NI-LTALFA----QA-------SVAG------S----------------YRIEKKWSVVGF-------------CSGAIAGLVAITPGSG------------ - B0DY50
-------------------------------------DK-ADNA-----FMMICTALVL-FMTIPGIALFYG---------GLI-------R---------KNVLSMLTQVTVTFALVCIL--------WVVYGYSL-------AF-------GEG----------------N------------------------------------NGSI-YQYI----------HVAFQGSFACITVGLIVGA-LAERIRF----------------------GSI---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F------------------PHNLP------MVFTGTAILYI--------GWFG-FNAGSAGTA-N-----------------------------LDFAGGTVVHINAAIAGLVGAYLIG-KR-V-------------------DD-----PCDVFGVHGVCGIVG-CI-MTGIFA----AS-------SLG---------------------------RGKPSLLGA-------------CSGAIAGLVGVTPACGY-IGVGG----- - P69680
------------------------------------LDL-ASSS-----FVFLSTALVL-MMTLPGLALFYG---------GMV-------R-KKVR---KKNVIATVTQSVAVSCVAGIL--------WYVVGYSL--------------------------------------------------------------------------SL-PEML----------WISYQMTFAIITPALITGA-FAERIKL------------------------L---PE---------------ML-WIS-YQMTFAIITPAL-ITGAFAER----IK----L----G--T-E-E-MA---PNNLI------FVMIGAALLFV--------GWIG-FNAGS--------------------------------MGVLDFAGGAVVHVNSGVAGLVAALFLG-RR-K--------G----------DD-----SLDAFGIHGAGGALG-AV-LTGVFA----DP-------AIN--------------------------IRRKPSLLGI-------------LSGLVAGLVAITPAAGF-VNPTG----- - A0A3G9G4Q4
-----------------------------------------DTA-----WMLVSTAFVL-MMTIPGLALFYA---------GMV-------R-KKVR---KKNVLATLMQSFALCCIMSIV--------WMVAGYSL-------A------------------------------------------------------------------TI-PESL----------FMMFQMTFAIITPALISGA-YAERMKF-----------------------TI---PE---------------SL-FMM-FQMTFAIITPAL-ISGAYAER----MK----F-------Q-D-D-LS---PFNLT------YAIIGASLLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGIAGLVCALVLG-KR-K--------G--F-------DD-----SLDAFGVHGVGGIVG-AM-LTGLFA----YG-------PLS---------A----------------RSGKPTVLGV-------------ISGVVGGLVAITPAAGF-VLPGS----- - A0A149UP06
-------------------------------------YA-LDTF-----YFLICGALVM-WMA-AGFAMLEA---------GLV-------R-AKNTEILTKNVALF--------AIACTM--------YMICGYGI-------MY-------GGG-----------------------D----------------------------------APSA----------DFFFQVVFVATAMSIVSGA-VAERMK--------------------APSAD-------------------------FF-FQVVFVATAMSI-VSGAVAER----MK------TADG--KVN-A-IP---GANLP------LATLGTFILWM--------GWFG-FNG-----------------------------------GFSDFAGSGIVHMAGAAAALAGVLVLG-AR-K--------GK-K------IDD-----PVGAISVHGVVGLLG-LI-LVPFTN----DG------S----------------------------ILFGKADLTMV-------------LNGALAGLVAITAEPST-P--------- - F2G6G4
------------------------------------MDT---VV-----WVLISTALVL-LMT-PGLAFFYG---------GLV-------K---------EKSVSMMMMSFGSLGLVAVL--------WILIGANM-------SS------IDGSVW-----------FGQE------GVA---------G----------------------SDLL----------FVAFGGTFAIITTALISGA-IAD-----------------------FGQEGV---AGSD-------------LL-FVA-FGGTFAIITTAL-ISGAIADK----DI------------------TQ---PHNVP------LVLIGAALLWF--------GWFG-FNAGAA-------------------------------PAVIDYAGGTAVHINAGAAALGLALVLG-KR-V--------G--F-----GFDD-----SLDVVGLHLVAGIIG-TI-YLGFFA----TD------TG--------------------------KLRTGKATAVGA-------------VSGVVAGLVAITPACAN-LT-------- - A0A2M9D7S8
--------------------------------------V-EDTN-----WVLTSSFIIF-TMQ-TGFGMLES---------GCV-------SIKNE-NIMMKNVIDI--------VLGGFT--------YWLFGYGM-------SY-------GRGP------------------------------------------------VG-DPLMG-QIFA----------AFLFQLSFATTATTIVSGA-MA-------------------------PVGDPLMGQI---------------FA-AFL-FQLSFATTATTI-VSGAMAYD----P-----L--------------P---LGNPV------NACMGLFVLWW--------GWLA-FNSGST-------------------------------------AGSGPVHLIGGAAAFASAAMLG-PR-L--------GR-Y-----A-DD-----PVGASSVHGVCGIWG-VI-AVGLFA----DN------PVP-------------------------------MDIIDL-------------INGVLGSLVSITAGCFL-YRAWEA---- - A0A034WGQ2
-------------------------------------NS-GDTA-----WMLMATALVL-LMT-PGLAYFYG---------GMV-------N---------NNVISTMLQSFVAMGVISII--------WVVCGFSL-------AF-------GDS---------------IG------L-D---------GKP------------WSLAATI-PLAV----------FAFFQLKFAVITPALITGS-MA------------------LDGKPWSLAATI---PL---------------AV-FAF-FQLKFAVITPAL-ITGSMA---------------MEA----N-F-LP---PANIP------YVLLGTGLLWF--------GWFG-FNAGSA--------------------------FK---LGVLDFAGGTVVHMSAGWAALAGAIYLK-RR-K--------N----------DD-----TLDVFPCHGVGGMVG-MI-MTGIFA----SK-------GVN---------A------------------KKVSALGF-------------CIGAVVGLVAITPAAGF-VTVPQ----- - I0KDC6
-------------------------------EMLT--EA-INYT-----WILVATFLIF-FMH-AGFAMLEA---------QLT-----------------KNLLTW--------SVGVTV--------FFLIGATV-------EG-------IV------------------------AG----------NG---------------------ASWMD----------WLYGAVFAMTAATIVSGA-VAGRAKLR---------------------------AS---------------WM-DWL-YGAVFAMTAATI-VSGAVAGR----AK----LR------------IP---GHSLT------FAALGTLILAF--------GWYG-FNVGTS-------------------------------VVFHDFAGGMIVHGMGGIAGLTAAWVLG-PR-M--------D----------DD-----VCAVFPVHGSAGVLG-TL-LFPFVA----AP-------GVV---------------------------TGKVDTLYV-------------ANGLLAGLAAITAIPDT-TA-------- - F8D7H6
----------------------------------K--VA-MDTL-----WVAIAAFLVF-FMN-AGFCMLET---------VL-----------------AKNLIVF--------ALATIA--------FWAIGFGL-------MF-------G-----------------DG------N--------------------------------D-PLNA----------KFLFQLVFAGTAATIVSGA-VAERIKFL---------------------------PL---------------NA-KFL-FQLVFAGTAATI-VSGAVAER----IK----FLYQDG--QVI-A-IP---GHNMS------IATLGCLILWL--------GWFG-FNPGST-------------------------------MGFYDFAGSTVIHSFGGWAALMGAAFLG-PR-I--------G-----------D-----PVGATSVHLVCGIWG-TL-AVGLFS----VG------PGGYP----------------------------KPDLSMI-------------INGVLAGLVGVTASCAY-VSMTSAL--- - K9W4V5
-------------------------------EEIK--TT-LTFM-----WLLLASGLVF-FMH-AGFSLVET---------IL-----------------MKNFMTV--------VLGILV--------YWAVGWGI-------MY-------GA---------------DAA------GL---------------------------------ATWN----------SWFFQMVFAATGATIVSGA-MAERTNF----------------------------AT---------------WN-SWF-FQMVFAATGATI-VSGAMAER----TN----FPI---------P-IP---GHNLT------ITFLGTLILAL--------GWLG-FNGGST----------------------------------------GVVHSIGGYSALAGVILVG-AR-I--------GR-FK---NGLDD-----PVGAIAVHGYCGSWG-LI-SVGLFS----IG------MGNG-----------------------------KPDPSLT-------------ANGLLGGLVAVTAPCGS-ISN------- - Q466Y3
------------------------------------MDT-GDTA-----WVLASAALVL-FMT-PGLALFYG---------GMV-------R---------KSVLNMMMMSFGALALISVL--------WVLYGYSM-------AF-------QPE---------------------------------------------------SLVFTV-PSMA----------FVAFQAMFAILTVALISGA-IAD-------------------FQPESLVFTV---PS---------------MA-FVA-FQAMFAILTVAL-ISGAIADR--------------------D-P-MR---PHNLP------LVMIGAGILWF--------GWFG-FNAGSA-------------------------------LLAIDFAGGTAVHINAGAAGLALALVLG-KR-R--------G--F-------DD-----SLDVVGVHLVGGIWG-TL-AVGLFA----SA------STT-------------------------KLRDGHATSLGA-------------ASGVVAGLVAITPACSS-VT-------- - D2SE15
------------------------------------------NA-----FMMICTALVL-FMTIPGIGLFYG---------GLL-------R---------SKNVSLMTQVMVTFAAICVL--------WIVYGYSL-------AF-------GSG----------------N------AIF---------G-----------NLDEDLTGSF-YKMI----------HVAFQGSFACITVGLIVGS-FAE-----------------------DLTGSF---YK---------------MI-HVA-FQGSFACITVGL-IVGSFAE-------------------K-E-A-FK---PHNLP------MVFMGTAILYI--------GWFG-FNAGS--------------------------------DGALDFAGGTVVHINAAIAGLVGAYLLG-KR-A--------G--F-------DD-----TCDVFGVHGVCGIVG-CL-ATGILT----AT-------SLG---------G-----------------RGKPSLLGA-------------CSGCIAGLVAVTPAAGT-VGVG------ - A0A377PBY1
-------------------------------------SA-GDTA-----WMLTSTALVL-FMTIPGLALFYA---------GMV-------R-KKVR---KKNVLATVMQSFAITAVITVL--------WTVVGYSL--------------------------------------------------------------------------AI-PESV----------YFVYQMTFAIITPALICGA-FADRMKF------------------------I---PE---------------SV-YFV-YQMTFAIITPAL-ICGAFADR----MK----F-------------MA---PHNLV------LTMIGGSMLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGIAGLVSCLVLG-KR-V--------G--YGR----EDD-----SLDAFGVHGIGGILG-AL-LTGVFA----VK-------DIG---------G-----------------KGKPSVLGI-------------VSGAVAGLVAITPAAGF-VGV------- - B1JZ69
-----------------------------------------DTA-----WMLTSSLLVL-MMSVPGLALFYG---------GLVKRN--NKR---------NNVLATLMQTVAVCAVVSLL--------WPVIGYSL-------V------------------------------------------------------------------TI-PESV----------FIMFQMTFAIITAALLLGS-VAD---------------------------TI---PE---------------SV-FIM-FQMTFAIITAAL-LLGSVADH----DR----------------T-PS---PANIV------MSLIGTGLLWV--------GWFG-FNAGSA----------------------AGMLGF---GFALDFAGGTVVHIASGVAGLVAALVLG-RS-Y--------D----------DD-----SLDVFGIHGIGGIVG-CI-LTGVFA----TK-------AI-----------------------------GKPSVVGA-------------LSGVVSGLVAITPAAGF-VGFGTS---- - A0A2W5HTC3
-------------------------------------FL-ANNL-----WLLIATILVI-FMN-AGFAMVEAGMCRKNAVNIL-----------------AKNLFVF--------ALAVTS--------YWFIGYSL-------M-------------------------------------------------------------------V-P-TV----------DFLFQSAFAGTAATIVSGL-VAERVKFG---------------------------VP---------------TV-DFL-FQSAFAGTAATI-VSGLVAER----VK----FGPQ--------A-MP---GHNMA------IATLGALVLWI--------GWYG-FNPGSQ------------------------------------FAGSSIVHSVGAWAGLVGAMLLG-PR-I--------GK------YSDGD-----PVGAFSVHGVCGVWG-TL-VIGLWG----TA------VQGDG--------------------------SGKPDLTMI-------------INGILAGLVSITAGCGD-MT-------- - A8G2S3
------------------------------------MNT-GDLA-----WVLISSALVW-LMT-PGLALFYG---------GL-------------G---EKNLLHTMFIPVLIIGIASLT--------WFLVGYSL-------AF-------GGN------------------------------------------------------GTI-PDGA----------FALFQGMFPIITAAIITGS-VIGRMKI-----------------------TI---PD---------------GA-FAL-FQGMFPIITAAI-ITGSVIGR----MK----I--------------------HIPV--RPSYVLIGGALLWV--------GWFG-FNSGSA-------------------------------MGAIDFAGGTVVHISSGVTGLVLALLIG-HR-H--------N--D-------DD-----TLDAFGIHGIGGAVG-AI-LTGVFA----DK-------NI--------------------------KTHGRVTLAGI-------------TSGGVAGLVVITPAAGF-VAP------- - D5T4N9
------------------------------------------PV--PL-PLLMQGLLVMGLL--AGLTLFQS---------GLV-------R-PGASAQAIKGICGS--------ALAVLA--------FFFIGSNVLMVGVNGGF------HGTF-----------------------AFF--------------------------------DAMA----------EWFLRAPFAALPVLIVAGA-LAERLR------------------------DA--------------------MA-EWF-LRAPFAALPVLI-VAGALAER----LR------------------LP---TNSLA------LATFGTFAGWI--------GWFG-LTGGAVLLA-VPEAGP---------------------LGFVDIGGATVLHSAAGWAALVGAVLLG-AR-K--------G-----------D-----ATGAISVHLICGLWA-TL-VVSVID----PT------VPLTTQ---------------------------RNGVMAR----------G--LQGALAGLVSISAAPHL-PMP------- - Q2RWY7
------------------------------VGHNS--VA-INIM-----WTLLAGFLVM-FMQ-AGFAMVET---------TM-----------------SMNFFVY--------PLGMLG--------FFLTGFAI-------MF-------GGFG--------PL--ATLG------GYTLLGHPFGLFGMTG-------FAL--IGTYDV-GVFA----------LFLFQMVFMD--------------------LLGHPFGLFGMTGFALIGTYDV------------GV------FA-LFL-FQMVFMD--------------------------------------IP---GHSIP------MAIIGTFILAF--------GWFG-FNAGST-------------------------------NGHVDFAGSSVVHMTGGVIGLVGAWIIG-PR-I--------G----------DD-----PVGAVSVHMVNGAWG-CL-ALGLFA----DG------SYG-------------------------------PDPGMA-------------CNGMLAGLVAITAPCAF-VNQIS----- - A0A0E3R4G0
------------------------------------MNP-ADNA-----WVLVASALVL-LMT-PGLAMFYG---------GLT-------R---------SKNLSTMMHSFFLMGLASII--------WLFYGFSL-------AF-------GTD------------------------------------------------------IGI-TGST----------FMIFQCMFAVITPALISGA-FAERMKF------------------------I---TG---------------ST-FMI-FQCMFAVITPAL-ISGAFAER----MK----F----G--T-V-P-MI---PHNLT------LTLLGAGLLWF--------GWFG-FNAGSA--------------------------LK---LGALDFAGGTVVHINAGVAGLACCIVLG-KR-K--------G----------DD-----SLDVVGVHAVGGIWG-AL-ATGLFA----SK-------AIN---------AAGN---------------GKPTTLGV-------------ASGAVAGLVAITPAAGY-VGP------- - I4C9L0
-------------------------------------DK-GDNA-----WMLTSALLVL-LMILPGLALFYG---------GLV-------R---------KNMLSVMMQVSTVALIGFVA--------WMLWGYSF-------A-----------------------------------------------------------------VVI-PELT----------FIAFQSTFAAITAALVVGS-LVERMKF----------------------VVI---PE---------------LT-FIA-FQSTFAAITAAL-VVGSLVER----MK----F-------K-E-P-MP---PHSLT------LTLVGAGLLWV--------GWFG-FNAGSN---------------------KSGLLWG---FGALDFAGGTVVHINAGIAALVGALILG-KR-Q--------G--Y-------DD-----SLDAFGIHGIGGIVG-AI-GTGLLV----NP-------AWG---------GAGV---------------GKPSALGL-------------ASGIVAGLVAVTPAAGF-AGPMG----- - D5VJ32
----------------------------------S--SA-IDAT-----WVMVSAILVI-LMQ-VGFALLEA---------GST-------R-KNAGHVAGKTVLTF--------GICSIA--------FWAFGFGL-------TF-------GD------------------------GNS-------F-GMQKDAFS--AFS--------A-ATVP-------ISILFLFQLAFAAVSLAIAWGG-FA--------------G-MQKDAFSAFSAATV---PI---------------SI-LFL-FQLAFAAVSLAI-AWGGFA--------------------------IP---GHNQV------YSVLGVLFLWI--------GWFG-FNAGST-------------------------------LGMQDFAGSTVVHLQGAIVALVATILLK-PR-I--------GG--------IDD-----PVFAFSVHGVAGIWG-TL-STGLFA----TP------ELVE-----------------------------KADIPSM-------------LNGVLAALVAITASCAF-VDPWA----- - C0Z5S5
--------------------------------------A-ANTN-----LLLFCSALVF-FMQ-AGFAMLCA---------GSI-------R-SKNVNILIKNVLDA--------CVGALA--------FFAVGYGL-------AY-------GRK----------------------------------------------------------TGWT----------NFLFNWAFAAAAATICSGA-MAERTQF-----------------------------G---------------WT-NFL-FNWAFAAAAATI-CSGAMAER----TQ----F-------------MP---GHNAT------LTVLGTFVLWV--------GWYG-FNPGSV-----------------------KWSG----VGFIDLAGSGVVHMVGGFAGLMGAIMLG-PR-T--------GR--------IDD-----PLEAFPIHGACGVWG-CL-AVGLFA----KK------KFL-------------------------RAFNKVWDLVAV-------------CNGILAGLVSITAGCHV-MD-------- - C1N6X9
---------------------------------MTTLDT-GDIS-----FLVVCTLLVF-LMT-PGLALFYG---------GMV-------R---------RNVLSIMMQSYAAMGIVTVI--------WVLFGYSL-------A---------------------------D------Y-----------------------------APTI-PHLL----------FFLFQLMFAIITPAVISGA-TA------------------------DYAPTI---PH---------------LL-FFL-FQLMFAIITPAV-ISGATAGY----EW------------------NI---PHHMP------NVLFGGGLLWF--------GWFG-FNSGGA--------------------------RN---LGVLDFAGGTVVEVASGVSGLVAAYVLG-KR-L--------K----------DD-----ALDVFGIHGVGGTWG-TI-ATGIFA----DL-------SLN---------PQ--------------LHRRQITVFGA-------------VSGIISALVAITPAAGY-VST------- - J7ITF6
--------------------------------------K-GDNT-----WMLISTILVL-LMTIPGLALFYG---------GLV-------R---------KNMLSVLMQVFMITAVVMII--------WVTYGYSL-------AF-------T--------------------------------------------------------VAI-PELT----------FVCFQMTFACITPALIVGA-FAERIKF----------------------VAI---PE---------------LT-FVC-FQMTFACITPAL-IVGAFAER----IK----F----K--K-D-I-MA---PHSMT------LTMVGASLLWV--------GWFG-FNAG---------------------------------YGAIDFAGGTVVHINAGIAGLVGAIMLG-KR-T--------G----------DD-----SLDVFGVHCVGGILG-AI-GTGILV----NP-------ALG---------GAGIVDYSTA---------GKASMLGA-------------ASGAVAGLVAVTPAAGF-AGPMGS---- - A0A068SVR1
-----------------------------------------DTA-----WMMVASAFVL-MMTIPGLALFYS---------GMV-------R--------KKNV-ATMAQSLAAVAIISVL--------WVAFGYSL-------AF-------VGD----------------G------A-------------------------------WI-PEAL----------FMLYEMTFAVITVALVAGS-VADRMRF------------------------I---PE---------------AL-FML-YEMTFAVITVAL-VAGSVADR----MR----F-------A-D-N-LS---PFDLS------LAVIGTGLLWV--------GWFG-FNGGSA-------------------------------AGVLDFAGGLVVHLSAGTGGLVGAMVLG-RR-H--------G--Y-------DD-----SLDVFGVHGIGGLTG-TV-LAGVFA----TA-------AIGGT------SGLI---------------RRKPSVLGM-------------ISGAVAGLGTITPASGY-VEP------- - A0A0D7F328
--------------------------------------K-GDVA-----WMMTATLLVL-FMTMPGLALFYG---------GLV-------R---------KNMLSVLMQCTMICGIMIIA--------WVVYGYSF-------AF-------GGG-----------------------------------------------------TVEI-PEYL----------FIAFQMTFAVITPALIVGG-FAERIKF----------------------VEI---PE---------------YL-FIA-FQMTFAVITPAL-IVGGFAER----IK----F----G--K-D-N-MA---PHSMT------LTMVGAAILWV--------GWFG-FNAGSN-------------------------------IAAVDFAGGTVVHINAGIAALVGAFVVG-KR-L--------G----------DD-----SLDVFGIHGIGGIIG-AV-GTGVFT----SS-------ALG---------GIGYGEG--------AAARGKASMLGG-------------ASGIVAGLVAVTPACGT----------- - Q0G0A4
-------------------------------------DS-GDTA-----WMLTSSVLVL-MMTVPGLALYYG---------GLL-------R---------KNILAMLMQCFFATALISVL--------WVVIGYSL-------AF-------TKG----------------N------G---------------------------TLSGTI-PETV----------FCMFQCTFAIITPVLILGG-PAD----------------------GTLSGTI---PE---------------TV-FCM-FQCTFAIITPVL-ILGGPADG----SV----------------N-MA---PADLG------YTLVGASLLWV--------GWFG-FNAGSA--------------------------GG---QGVLDFAGGTVVHINSATAGLIAAIMVG-KR-T--------G----------DD-----ALDVWGVHGLGGIAG-AL-LTGVFA----VK-------SIG--------------------------IKGKPSLLGA-------------VSGAVAGLVAITPACGF-VP-------- - F0J3F9
--------------------------------------S-GDTA-----WMLISSVIVL-MMTVPGLGLFYA---------GMV-------R---------KKNIATMMQAFSAAAVLSIV--------WMVAGYSL-------AF-------GTG----------------N------A-------------------------------TI-PESL----------FMFFQMTFAIITPALIAGA-FADRMKF-----------------------TI---PE---------------SL-FMF-FQMTFAIITPAL-IAGAFADR----MK----F-------------MS---PHDLS------YALIGASLLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGVAGLVCALVLG-KR-Y--------G--YGR----DDD-----SLDAWGVHGIGGITG-AL-LTGIFA----YG-------PLS---------A------------------GKPTVLGA-------------LSGAVAGLVAITPAAGF-VLPGP----- - Q0BQ69
---------------------------------SKSYPMFQDVH----------------VMIFIGFGFLMM-FLKRY---GL------------------------------------------------AVGLNFMIA----AL----------------------CLQWAILV--NGFFHLKK-----G----------------TIVDL---------------NAMLGADFTAAAVLISFGV-LLGKTTPT---------------------VDL---------------N----AM-----LGADFTAAAVLI-SFGVLLGK----TT----------------P-T-T--EKEGSSYQSDLFAMIGTVFLWL--------YWPS-FNA-------------------------------------IDMGDSMFVHVFGAYFGLAVSLML--HR-R--------DA----------D-----TCGVHNLHGLPGILA-AI--IGAVA------------AGVASEA----SY----------------------DMVHV-------------QNSTLAGGVAVGTAADLMIHPWGA---- - F2YIC4

In [148]:
ey = alignment[:, 70:71]
n = alignment[:, 102:103]
d = alignment[:, 105:106]
t = alignment[:, 241:242]
f1 = alignment[:, 311:312]
f2 = alignment[:, 392:393]
h1 = alignment[:, 441:442]
h2 = alignment[:, 495:496]
sn = alignment[:, 579:580]

In [149]:
idid = []
seqe = []

for i in ey:
    print(i.id, i.seq)
    idid.append(i.id)
    seqe.append(i.seq)

A0A858ZNJ3 Y
A0A1H9M798 Y
B0DY50 Y
P69680 Y
A0A3G9G4Q4 Y
A0A149UP06 Y
F2G6G4 E
A0A2M9D7S8 Y
A0A034WGQ2 E
I0KDC6 Y
F8D7H6 E
K9W4V5 E
Q466Y3 E
D2SE15 Y
A0A377PBY1 Y
B1JZ69 Y
A0A2W5HTC3 Y
A8G2S3 E
D5T4N9 Y
Q2RWY7 Q
A0A0E3R4G0 E
I4C9L0 Y
D5VJ32 Y
C0Z5S5 E
C1N6X9 C
J7ITF6 Y
A0A068SVR1 Y
A0A0D7F328 Y
Q0G0A4 Y
F0J3F9 Y
Q0BQ69 Y
F2YIC4 M
D4XLN6 Y
A0A420WC79 E
A0A5C5TUT2 Y
A0RUZ2 Y
A0A0A2ZRL7 Y
J4UGB7 Y
E5Y678 Y
A0A0D2KGN8 Y
S5ABR8 E
A9DQM8 E
G5EB13 Y
A0A2N6NEK4 Y
C6DB68 Y
Q81GN5 Y
Q0F2M5 E
A0A0C6P439 Y
B9SWW9 Y
L8H5K0 M
Q9NIV0 M
C1N5A7 C
Q1JXS5 Y
A0A1M6JKY3 Y
F4D1J0 Y
A0A257SYX3 Y
V4RK08 E
G0V8D6 Y
A0A7S4GMD8 C
B3QVV5 Y
F2JZ83 E
A0A857DDJ7 Y
A0A0S6UHP2 E
D5EP71 Y
F4KY49 Y
M5S9B4 E
A0A009PYN3 Y
A0A3T0SZ22 Y
A0A248LMH8 Y
A0A6H9GEE4 E
A7HSP2 Y
A0A7V8IKS6 Y
T2JFS5 E
F6FRU9 Y
A0A9E9L9J1 Y
A0AIW5 Y
A0A0E9NHV4 Y
Q2N625 Y
C8WSI9 Y
A0A1H1BPD6 Y
A0A176XNC5 Y
A0A4V0XUI3 E
A7S3L2 E
M5U2P1 E
K9P5D1 Y
Q0F2M7 Y
A0A2R3IMJ8 Y
Q2RVB5 Y
A0A556RTU3 Y
E0TGP9 E
B7G0Y1 C
A0A1G9P6Q0 E
D0LTW3 E
Q6BT62 Y
Q2IK04 E
Q6BJI7 Y
B7X047 Y
A0A068NPW2 Y
A0A399NT81 Y
K0F9X7 Y
A0A037ZMW1 E
A0A075JZ35 Y
A0A369MHK2 Y
A0A1B9JPL5 Y
D8PD01 Y
A0A2G5BI87 Y
A0A2G5BGA9 Y
A0A657K391 Y
P69681 Y
A0A4P6UIJ8 Y
A0A0V8M0W6 Y
A0A0H2XSU4 Y
Q1Z695 E
A0A7Z0V0A4 Y
K0ER80 Y
A0A149UWF2 Y
G0H0Z6 E
G0EFF3 Y
C8WLL8 Y
X5CNT2 Y
A0A4Y1MSE7 Y
H2CLF7 E
M4VEJ9 Y
A0A4V2X6C2 Y
A0A2K1RA77 Y
A0A375YPN6 E
A0A7M6UUM4 M
A0A172YCA7 Y
A0A918MJ52 E
A0A2S8QA29 Y
A0A251XJT0 Y
A0A0B4E6X7 E
A0A0K2STQ7 E
A1C5Z7 Y
C9KKP2 Y
A0A2Z4MD56 E
Q9VFA9 E
A0A502GPV4 Y
I5C044 E
D2V6P8 M
D3RN22 E
Q97L80 Y
A0A0D5YN10 Y
A0A1I5GN22 Y
A0A1Y5E8I7 E
B1Y8C9 Y
M5SYZ1 E
Q6HM26 Y
A0A379A0S9 E
A0A101DCS3 Y
A0A1Y3U5V2 Y
A0A202B535 Y
F8E6R1 E
Q6ND36 Y
A0A8H6K7L7 Y
Q7NCB8 Y
A0A369MRW6 Y
C9RS76 E
A3U857 Y
A0A127PIQ9 Y
B8FGW0 Y
A0A060JMP6 Y
D5V7B3 E
A0A494JB70 Y
A0A5M8QF12 Y
A0A8G2F3G4 Y
J7L3W8 Y
G0JRG9 Y
D3DJN2 Y
A0A1Y2JH43 Y
Q1L727 E
A0A7T2S0Z6 Y
A0A315S845 Y
A0A2S6H6B7 Y
A0A1J5NTP7 Y
A0A0E3QY86 Y
A0A096EEV9 Y
A0A380S5X4 E
B8ZYW3 E
A0A2S8GEJ5 E
A0A248TDF2 E
B2GFN1 Y
U1PPI7 E
C7LW88 E
G3A431 Y
A0A066ZTE4 E
L7CG99 E
S0ET45 Y
A0A178TA08 E
H1XV27 E
A0A6M3ZJI1 Y
U5DEY6 E
H6LFQ2 E
Q6CRN0 Y
A0A4Q2EAG7 Y
A0A1J5NNB8 E
E3I393 Y
A0A243SC06 Y
D4F313 Y
W0F0I7 Y
A9B874 E
A1D2Y5 Y
T2J0N1 E
Q2FQT3 Y
A0A075WG29 E
A0A979GQ79 Y
A0A381CAY8 Y
A0A2G3DSU6 E
A0A168EVK8 Y
A0A094W9G3 E
A0A4R3NVT3 E
W0DYY3 E
G8JTW0 Y
A0A4P6UIK6 Y
I9P003 E
G2T1Y3 E
B8EMQ8 Y
I6Z905 E
E0TCV4 E
A3XNG6 E
A0A087MGU4 Y
A2BUP4 E
A0A562S8V2 Y
A0A495DND0 Y
A0A0S2FHD7 Y
F3QPR6 Y
A0A063Y394 E
F6G5I9 Y
A0A323UDG5 Y
A0A0G9HEC5 Y
B8FDY8 Y
Q5KPM5 Y
A0A147EQL9 Y
A0A854Q6X9 Y
C3X1J1 Y
A0A5B2V3B9 Y
A0A258FS85 Y
A0A7T2W1B3 Y
A0A060UN76 E
G0JRQ3 E
D5UD26 Y
G2ZN72 Y
A0AA46Q839 Y
A5UJR1 Y
L1INN6 E
C1F584 E
C5LAG4 E
A0A2A2MCP3 Y
B1Y6V4 Y
A0A1G6ABK5 E
A0A6A1TYJ4 Y
A0A2T4UWF1 Y
V4AP67 E
A0A173R3W6 Y
C7NND3 E
B0DFJ4 Y
A0A3E2VY88 E
R1EDV9 E
J1L5M8 Y
D7G265 E
Q8ERT9 E
I4D6Z9 E
A0A4R6DFU8 Y
A0A060URC3 Y
D2BIB2 Y
F5ISF6 Y
A5CRL2 Y
A0A6G9XJV9 Y
Q59UP8 Y
A0A6N4SPH9 E
I0HGY4 Y
X5DX97 E
L1J6I4 Y
I1DSU5 E
B9L7N1 Y
Q1Z4I4 E
Q21CP1 Y
A0A165MFD1 E
V4CRP5 E
Q7S5K0 Y
A0A071MMV1 Y
A0A149RYW7 Y
A0A7G5EC77 Y
A0A1W2GZ82 E
A0A7U3XVQ4 Y
A0A071M4L5 Y
U5C2K4 E
A0A248LNW8 E
L8H844 E
A0A149V596 Y
S9QZ09 Y
B1ZSW9 Y
D2BUJ8 Y
A0A9Q8L398 Y
M5S735 Y
Q6ARH0 E
K6W5X0 Y
G0JRG6 Y
A0A6H9FYW4 Y
A0A0S4WFM4 Y
A0A101HKN9 E
Q9REX3 E
F0S3Z6 E
A8NAG3 Y
C6LBD3 E
A0A149U2G9 Y
V4REY8 E
A0A0H3H4I7 Y
A8N2H6 Y
S0APH6 Y
A0A017SYR8 Y
A0A1B9MZ78 Y
E4T3F3 E
D7E934 E
A0A0M3AB44 Y
A9WHW6 T
A0A5M4AUM9 Y
A0A1X4GBG2 E
I4D1H5 Y
A0A0E3QYF3 E
B0CQX4 Y
A0A378YR15 Y
A0A495D4X4 E
A0A076PL76 Y
Q1YDY7 Y
A0A3E2UCG9 E
A0A2K3DPU7 M
A0A3R9Q7C4 Y
V5U2Z4 Y
K9P718 E
M1V7W3 T
Q6LKC8 E
E5Y789 Y
J9Z839 Y
A0A1G7VM92 Y
K9Z0D3 E
A0A482TED1 E
R1EGK6 E
J1ASR8 Y
A0A7U4E420 Y
K9YR86 E
A8PXT8 Y
A0A0U1NJW3 E
B8FL88 E
A2CCK1 E
D6TFE1 E
A0A2H4U5R1 Y
I2GD40 Y
A0A060HFT5 Y
B1Y842 E
A0A0X8NXA9 Y
A0A0A2A5X1 E
A0A318FY98 Y
Q7V4T8 E
A0A1A0DHK0 Y
C1A872 Y
A0A395VB65 E
A7MFK3 Y
J4KM12 Y
A1SY01 E
A0A1H4DJ49 E
A0A9R0NTP8 Y
A3PAY4 E
B4CV94 Y
A2C095 E
Q2HD43 Y
A0A836M2B6 Y
H6RWK9 Y
A0A087EQK8 Y
A0A1I0AQM4 M
L7CG11 Y
A0A248LNK5 Y
B7FTM9 C
L0K9M1 E
I4D6Z7 Y
A0A2K1RA81 Y
Q2WBF7 Y
A0A1B9BUU6 Y
A0A2S0JW39 E
A0A2S5YID7 Y
B3PIH2 Y
U3P8G1 Y
C9R9J0 Y
A8AC17 Y
F0YLV7 E
A0A1D3GAE9 Y
C1MHX0 Y
A0A1H4KAQ7 E
A0A2T4XZC1 Y
A1B3N0 Y
C7LW87 Y
A1SZ12 E
A0A2T2Y0D5 Y
A0A1H8D0R8 M
A0A2S5V2F6 Y
G3IYW2 Y
F5L8M7 E
C7BJG7 Y
E4U5Z1 Y
A0A1B9K8L2 Y
A0A2S5WMT7 Y
A0A0D2UPA8 Y
A0A161SKF4 Y
B4D7W2 Y
A0A1H3WA00 Y
C1D6X6 Y
A0A4D6KHD1 E
Q488X2 E
A9V5W4 M
A0A5M4ATH9 Y
E4TRS4 E
A0A011U1K7 Y
C7R314 Y
A0A077EFU9 Y
A0A0A2A0Y9 E
A0A0D8BQX6 E
A0A0L0S493 Y
A0A328Q6M1 Y
A0A016XCG9 Y
B7FSA7 C
G0AFH4 Y
A0A177W826 Y
A0A2S8GF54 E
Q1YDY8 E
Q5QVH2 E
A3ZT81 E
A0AA35XZV0 Y
F4H924 Y
K0NJH2 E
A0A1V3SSW1 E
F2AUF4 E
A6DN47 E
W8KM07 E
A0A1X3RP39 Y
A0A7S0KKL8 C
A0A318QZ80 E
K8VZC6 Y
A0A1B9JZS5 Y
A0A2S6GKN5 Y
A0A4R2Z2K6 Y
H1YCC3 Y
E1QIU3 E
A0A8H6MPB9 Y
A0A369N7Y3 Y
T2IEJ2 E
H5UND3 Y
Q1PX09 -
A0A149TSA9 Y
F2NGJ8 Y
A0A0E3SHQ9 E
Q5FLR6 Y
S0EUS1 T
A0A369M386 Y
W0DZS7 Y
A8MCL4 Y
V3ZVE4 E
O26757 -
A0A317FZW2 E
A0A085GI50 Y
A1ZGK6 E
G0IYI2 E
A7S731 E
A0A1U9YY82 E
A0A328EMN2 Y
A0A8E2UDJ3 Y
A0A2S5WUP6 Y
A0A8H7P8U1 Y
A0A257T7G4 Y
B3MX93 E
A0A1G5W0P2 Y
D4H2Y7 E
A0A4P8HC89 Y
Q7T070 M
F7NPQ3 Y
B9SA70 Y
Q9M6N7 Y
I7ZHW3 Y
F4XTK4 E
A4G1J2 Y
G7WFX4 Y
B8JBH5 Y
D9QPC8 Y
A0A4R7GKA0 Y
R9PMC6 E
A0A0E3LMT4 E
A0A511NGC7 Y
E4NS62 E
E4T3F7 Y
M0D580 E
J7J5E7 Y
B1XZU2 E
A0A366IE34 Y
A0A6U2BIY7 E
Q9QXP0 M
A0A424WAH3 Y
A0A410K1J5 E
L1IHZ8 Y
I8TC71 Y
A0A7U8C744 E
A8M670 Y
A0A0S4VNK2 Y
Q2SIR0 E
A0A5C4RNH5 Y
A0A3E0X011 E
A0A0E3SP24 Y
E1IF27 -
Q2YBP7 M
A0A2S5WZU0 Y
A0A172YBR4 E
A0A0K2STK6 E
A0A2N6JV02 E
F0S0G1 Y
A0A1C7EL50 E
Q18PF5 M
A0A1I0C958 E
A0AA35XVN2 Y
L8GGA0 Y
Q3AP28 Y
D0MFE9 Y
J9VXX9 Y
A0A166IS52 E
F0J7D3 Y
W7QG13 E
A4BMY5 Y
A6LV49 Y
Q1H483 Y
A6M3G0 Y
E4T0A4 Y
A0A3E2UHE6 E
A0A174SD65 Y
A0A855EH99 Y
C3YB74 E
A0A074KZD8 E
J0S2I0 E
K9WSX4 E
E8RLT5 Y
Q2FS34 Y
Q3Z7F9 Y
Q2S8H9 E
A0A060HN92 E
E6ME92 Y
A0A172RYW3 Y
L0FU80 E
C8WZE0 E
A0A2S8F4W0 E
A0A2C6C0X3 Y
F3ZVV4 Y
A0A7R6PER3 E
A0A495WJM6 Y
A0A0B4DUR9 E
A0A251YU48 Y
A5D4I5 Y
A0A2X2C038 Y
A0A2A2M8K7 Y
D3FBG3 Y
A0A2V4EA49 Y
D0MFE8 E
Q3B6Q2 Y
A0A1B9KID3 Y
A0A9J9ES23 E
A0A3N2SFS2 Y
Q0VLH1 E
A0A1U9Z147 Y
Q0G2T1 E
A6GJF5 E
A0A059XXR1 Y
A0A5J6WPP9 E
P41948 Y
L1IUV5 Y
A0A2W0GQV0 Y
Q1K433 E
A0A4Y7XC43 Y
D5AU98 Y
E1QFA8 Y
A0A075WBP9 Y
Q0BWD0 E
A0A1Y0HX98 Y
A0A098S5Y7 E
Q0I445 Y
A0A1E5BXA4 E
A0A2C9CK98 E
G4H971 E
A0A1I0BYN1 Y
A0A330GB00 Y
A0A2S8FR08 Y
Q84KJ6 Y
A0A2S5WGI8 Y
M2ALH9 E
A0A2K3DQF8 C
A0A8G2IZM3 Y
F5Y3C1 Y
A0A370FPU0 Y
F5RGM7 Y
A0A4R4K1P9 Y
R8VWI7 E
A0A0A2AMW2 E
Q7Z1M1 E
A0A414NWT8 Y
A0A0P6VSR8 Y
A0A0L0TDW1 Y
U3PCH5 S
W7QGE0 Y
C5BWX7 Y
A0A1B9M1A9 Y
B8GGC3 Y
D6SPD1 E
A0A0H3DR67 Y
A0A4R7VEK0 Y
G4R7P1 E
A0A1M5ZVP9 E
A0A2S5Y0D3 Y
I0ICG0 E
D0L8H3 Y
A0A1B9LFW3 Y
Q6ND34 Y
A0A6H9GWG4 E
Q5UZ98 E
A0A2S0P9T4 Y
H2CDR5 E
T2KGT3 E
A0A088E6Q7 Y
A0A258HS77 Y
E1V4T3 E
B7GKP4 E
Q9QUT0 M
I3Z3H7 E
G7WCB6 Y
A0A1Y6GLJ1 Y
A0A0S2DQB6 Y
Q6CRN1 Y
A0A401X433 Y
A7HT14 E
A0A009TDB1 Y
D4XSW0 E
B0SRS8 E
A0A149QSR6 Y
B1Y0E5 Y
Q7UGU7 E
A0A2S0Q8P1 E
F0ZPL3 E
A0A2T0GTU1 Y
I4CCD1 Y
A0A9Q6P4A5 Y
A0A418VIJ8 Y
C1MX19 Y
A0A1B9BUZ8 Y
K9W6F3 Y
Q1K8A3 Y
L8GFX3 Y
A0A1G6ABL9 Y
A0A087L0B9 Y
A0A073CP02 E
A0A0A1ZJU5 E
A0A258HPP1 Y
A0A149QAW7 Y
D2V6Q5 E
A0A1X4G8K1 Y
A0A067Z3S3 Y
A0A8F5ZDT8 Y
A0A854QN45 Y
A0A2N7LCD7 E
G7WFX2 E
A0A7S4GNJ2 E
A4G0C5 E
A6VE60 Y
A0A1S1HM83 Y
A0A037ZJY5 Y
N1WR17 E
Q2W5V2 E
A1VIM5 Y
A0A1Y5E3E3 Y
A0A1T4SFK4 Y
A7RNC3 E
M7XJ51 E
A0A399T909 Y
A0A2N6P374 Y
H8L2Q4 Y
D5EP68 -
E6SF19 Y
A0A1T4SFY6 Y
D3LBI0 -
E6W5C1 E
Q0VPH4 E
K9WT03 Y
L0KW14 Y
A0A4R8H081 E
A0A1B9N3H7 Y
B0RC35 Y
A0A420KGW4 Y
A0A4R3NLV5 Y
Q47K18 Y
Q21P82 E
M1WRK6 -
A0A290XBB5 Y
A0A6T9XUR2 E
A0A1J1JH03 E
I3R0S7 E
A9UR54 E
A0A1G7H8X3 Y
A0A8G2F718 E
Q1H0G2 E
D0LAL7 Y
C7LQR9 E
A0A1G5PWV0 Y
K1K628 Y
B9SXC7 Y
G7WA28 Y
Q1IWN6 Y
H6LKH9 Y
A0A1H7CU41 Y
G8JUJ2 Y
A0A081N2G5 E
A0A074ME37 Y
Q0VQH6 Y
C8XB51 Y
A1VIG8 Y
Q8GQS1 Y
A0A1I7FBM5 M
A0A1M6ZMI3 E
A0A482PLH3 Y
A0RXK8 Y
D0KXQ0 E
Q8JI14 M
A0A7T4WEP4 Y
A0A4R3ZNW3 Y
A0A074KY88 E
A0A6M3ZKU5 E
M1SJL5 Y
A0A1W9KSU5 Y
E3GI40 Y
A0A369NYJ2 Y
A0AA92K392 Y
O04161 C
A9BQZ4 Y
A0A6N2Z556 E
A0A8H6NAG3 Y
A0A2T9X1V4 Y
Q2J376 Y
A0A0F5EZP7 Y
A0A7G5DK18 Y
M9YAI9 Y
D2ZRW2 Y
G7UUY6 Y
A0A8H4GS02 Y
A0A2T5IHP0 M
A0A165MAC2 Y
A0A7S4LPS8 E
A0A075JIN0 Y
C8X554 Y
B8FZP7 Y
Q5KAF6 Y
A0A427KNL6 Y
A0A7G5DPV0 Y
Q22947 M
A0A1S1HRJ0 Y
A0A3N1VXY4 Y
A0A2S7YPJ9 Y
I0JI83 E
A0A7U3YMN6 Y
Q9BLG3 E
A0A1H9RTW8 Y
A0A1I4W3A0 Y
A0A0B4M163 M
U2EN72 E
A0A2W5VAZ2 Y
E4YA63 E
D5ELM4 E
M9RJS5 Y
A0A2G3E8V2 E
Q5FSX6 Y
I0HKQ8 Y
A0A833H2R7 E
B8ENL9 Y
B3DUX7 Y
A0A1D8UWJ6 Y
D5E995 E
A0A7U8C2Y6 E
L0KGR8 Y
B0VMH1 Y
P40260 Y
L0JT30 E
C1GR74 Y
A0A423Y4I6 Y
A0A4P7UHQ5 Y
A0A8E2R1Y5 Y
I5BYV5 E
A0A6B8N021 Y
A0A7G5DPV1 E
A0A2G5RQK9 E
A0A5M4B0G1 Y
A0A6S5K4J1 Y
C1D4X0 Y
A1SVA8 E
H1YF74 E
A0A8B4RWH8 Y
A0A0A0D6K5 Y
A0A0A2BBY0 E
A0A089ZBW5 Y
A0A068TC78 Y
Q46G49 Y
A1CQ21 Y
A0A1G6ABX1 E
E1SLM7 E
K5CFE5 Y
Q2YLQ6 Y
Q0G2V0 E
A4ABK3 E
A0A9Q5QVI9 Y
A0A4Q7Y9I7 Y
A9HMD6 Y
K9YN27 E
Q9UBD6 M
D9SI59 Y
Q8I0L6 M
A0A142VAD6 Y
G3IYW0 Y
A0A062IU58 Y
R1D1H4 E
A0A366XFS8 Y
A0A7S4GNF3 E
F0J6E8 Y
A0A7U4DN04 Y
V4RHR4 E
F7ZJM0 E
A0A2S5XAB8 Y
U5C4L4 E
Q21J04 Y
A0A142NNN1 Y
H1Y7T6 Y
F5R974 E
B0DU91 Y
A2BP62 E
A7HSN9 E
A0A377I7W9 Y
D2RU19 E
G7WJN0 E
E2SD33 Y
A0A0D7F2Y9 Y
A0AA92EGF5 Y
A0A9E9LXV9 Y
A4BEP1 E
A0A0E3WZH5 E
F7ZEU9 E
A5E3X2 Y
A0A0A3XTJ3 Y
A0A830ZZN8 Y
A0A1S8D478 Y
J7IVQ1 E
A0A2U1SS17 Y
S3K1S2 Y
C6XKC2 E
A0A2S7YIM5 Y
K2IMJ7 E
Q5P1S8 E
A0A7T5BFQ2 E
A0A556SRH6 Y
A8P923 Y
A0A7G5DKA9 E
L8JUH3 E
A0A0D2LEF5 Y
A0A258FTB0 Y
A0A5P9P1L2 E
M8E0R3 E
A0A6J5IRX5 Y
W5WIX6 Y
Q82X47 M
I4DBY0 Y
A0A6F8TLE9 Y
A0A1G7UZX2 E
A0A6P4JM51 E
G0J614 E
U2WTW8 E
A0A642KQG8 E
Q1AUG3 E
A0A6G9Y3Q0 Y
B8J5X4 E
M7NFH3 E
A0A0E3R6S1 Y
Q2IHY5 Y
A7I8Z2 Y
L1IYP4 Y
B4HDZ9 E
A0A366WYI9 E
E4TJ50 Y
A0A7S0ILH2 Y
A4BAE1 E
B3QRJ4 Y
A0A5C5BWI6 Y
Q7NQY2 Y
A0A091AXI3 Y
Q1QSQ2 E
R4FZE3 E
A0A2N0MZ27 Y
A9BTK1 Y
A0A242NIL1 Y
G0LFE3 E
A0A1B9NQ91 Y
A0A5M5PZE2 E
A0A0D2NYP3 Y
D9QPE5 Y
I5B3H0 E
L1IYW7 Y
C6WEW7 Y
B7FW68 C
F4GED5 Y
A0A4R8GSH7 E
A0A1W2H3F0 E
A0A3E2T713 E
A0A0H3KTD3 Y
A0A1Y4LM49 E
G2PRJ6 E
A0A0X8X7Y7 E
K8EJ02 Y
A0A1L3F1X5 Y
G8TK77 Y
A0A855F5Y8 Y
A0A975BTN0 Y
A0A562RGZ4 E
G5EB09 Y
A0A833LX85 E
U1H1F7 Y
K8W1E2 Y
E3HJW8 Y
Q7SEH0 Y
Q47X17 Y
B0DXT9 Y
A0A3G9G2C9 Y
Q95P70 M
A0A837C6X5 Y
Q89WR5 Y
A6DUG4 E
D7UQE2 M
A0A2I1M481 Y
A0A0T7GZ59 Y
O66395 Y
J3EXK0 E
A0A1B9MYL7 Y
K9U8C7 E
E2SD44 Y
H6LKH6 Y
Q605Y6 Y
A0A9Q9D9I3 Y
A0A6N2TIA4 E
A0A1E3PQH0 Y
A4CMI3 E
Q1K0H9 E
A0A0S6UEK9 Y
A0A0H3LUA3 Y
B9LU00 E
A9BIZ7 E
A0A7H8UK07 Y
E3H8C9 E
M2A398 Y
Q1QS12 Y
G0VI62 Y
A0A1Z3MS36 Y
A0A0B5FNH4 E
D9SI36 E
A0A410JZR4 Y
F7ZJZ1 E
F0ZCX7 M
W0DZX1 E
A0A4R3ZZ35 Y
A0A317G0I6 E
Q0ARJ4 Y
A7I8Z4 Y
T2KJ59 E
I3C0V3 E
E3H8A6 E
B2IJT1 Y
A0A2G6JLT9 E
A3ZZL7 Y
A0A2T0XPP2 E
Q31CR9 E
A0A1R1IDV3 Y
K2JVF8 E
V5BYZ7 Y
D8J4C6 E
D4H5F9 E
K9ZG59 Y
A0AA86YS65 Y
Q608B6 E
A0A562BXM4 Y
A0A401WXG0 Y
A0A857DMN9 Y
A0A1X6N3Q5 Y
A0A173R3X4 E
Q63EK5 Y
K9ZLY2 E
A0A533I6R2 Y
I0WJ97 E
K0N2R5 Y
M0J579 E
B8GGC1 Y
A0A6H9GFU4 Y
C6CBB1 Y
A0A510HHK8 E
A0A1B9MBX6 Y
A0A9Y2AG30 Y
E8RSE4 Y
F2B2B8 Y
Q7UYZ3 Y
I1YJH7 E
A0A853MG28 E
A0A0L0STS6 Y
A0A251XU71 Y
Q60BI2 Y
A0A829X098 Y
F3KUN4 Y
Q60C43 Y
A0A0T7FAP8 Y
A0A3E2TW06 E
W0E077 E
A0KPE9 Y
R7PZ71 Y
A0A0A1ZMZ9 E
A0AA40J491 Y
D3S2L0 Y
A0A373FQ71 Y
A0A0A2C6L1 E
Q7W7D3 Y
A0A165K0X5 E
A0A2S5X482 Y
R9GM11 Y
Q0G0A3 E
D4GLQ6 Y
E7RJZ0 E
F8IJE0 Y
A0A1V2XMU9 Y
Q7TNN9 M
A0A1G5RZU9 E
A0A2N6K4Y5 Y
B0SLB7 Y
A0A251YFS0 Y
B9WDK0 Y
Q7N0M6 Y
A0A0M2LU39 Y
F4B548 Y
D6Z5V9 E
A0A4R2M206 Y
A0A1E2SKM1 S
A0A127JTU2 Y
A0A212AV03 Y
G4QHD2 E
A0A021VMC6 Y
A0A2J7TJ33 Y
G7WDB5 -
Q6BK68 Y
Q1K3N8 E
A0AA91Q161 Y
A0NJ07 -
A0A316BQ38 Y
A0A377PLP5 Y
W7QGM4 E
A0A015YIP3 E
A0A060UWC8 Y
A0A1I4ZIZ6 Y
A0A264VQM8 Y
A9AUR8 Y
A0A1W5PRD1 M
A0A0E3BR91 Y
A0A1B0ZRL8 E
B9ACS5 Y
Q92BJ7 Y
F2JTN3 E
A1AVV2 Y
D2Q0J8 Y
A0A3S9N9F3 Y
A8ZQD5 E
C3X831 Y
A0A1M6BPM0 Y
A0A8F5VN39 Y
A0A1E5C7W4 E
A0A2S5WV24 Y
A0A833GZR2 E
C7M2A9 Y
A6W7U2 Y
W0JIB3 E
Q07UM3 Y
A0A066ZRQ5 E
S0G181 E
D3PAH1 Y
Q4WHC6 Y
A0AA94HTL8 Y
D5ASL9 Y
A0A4U1JNL6 Y
M0MDP9 E
A0A653N397 Y
A0A2S8GSU9 Y
A0A097R891 Y
A0A8H7U3I1 Y
A0A1H1MB73 Y
A0A016XDZ5 Y
A0A1B9JHS5 Y
D3PE53 Y
A0A9J9BAE8 E
Q2RM12 Y
A0A3N0AQL8 Y
C5KTM6 E
M1P5F0 E
I1YG38 E
A0A660CH85 Y
A0A2N7L7C8 E
Q5KZZ9 E
M1NZT5 E
A0A225CMT8 Y
A0A068NV61 E
H2CJI0 E
B0DU93 Y
Q221S8 Y
F4Y3C5 E
Q94CJ2 M
M0D3Q9 E
A0A3P2A7W8 Y
C0GKN4 E
Q7T3R4 M
A0A562USB9 E
A2SS52 Y
A0A211ZGL5 Y
A0A4V3ALP8 Y
A0A147GP06 Y
H2IZ00 Y
Q45HK8 Y
A0A6C8LST1 Y
A0A257T8W6 Y
Q5P470 Y
I5AZQ4 Y
Q07UM1 Y
E5B358 Y
A0A1Y4L5P0 E
Q3AFY9 Y
B0BZN3 E
A0A1Q2C7H7 Y
A0A4R5U5V1 Y
H6LKX6 E
A0A1Y0UZX2 Y
F6BEI0 E
M9RKT6 E
A7SGD4 E
A0A257TE48 E
R1FI09 E
E4N1T5 Y
U1PIR6 E
F2JYR9 E
Q84KJ7 Y
A0A2S8FTB5 E
D2R647 E
G9Y5B0 Y
A0A144NLT9 Y
A0A5J6WQU1 E
D2R355 Y
F3ZYD6 E
B0SL05 E
A0A5A7MAJ9 Y
A0A977NL43 Y
A0A433ZQ80 Y
A0A1Y0V4A5 Y
A0A1M7UEG2 Y
G8R7U9 Y
K1LDP0 E
B7G0Y4 C
A0A2W4ZXC0 Y
B3PF77 E
Q2KZK9 Y
Q18ES8 E
D3F545 E
B4S394 Y
Q1Q357 E
Q9H310 M
D3PKL4 Y
M5SY07 Y
Q8RUT6 C
A7NKH2 E
Q1Q879 E
A0A1B9M5B8 Y
A6LRS5 Y
J2ZGN6 E
V5E0F3 Y
A0A149RQX0 Y
A0A165BP25 Y
C0QSY0 Y
B0XVV6 Y
E0SD83 Y
A8HSA2 C
A0A1E3PSK5 Y
A5DYQ2 Y
A0A4U1K1W1 Y
Q0AT01 E
A4FMG0 Y
C3YB73 E
A0A9P3CXY2 Y
A0A0L8BVU4 Y
A0A401WUW1 Y
I4C9L2 Y
Q8RUE9 M
F0JGZ1 Y
A0A2I0UUY1 E
A0A542XGT4 Y
G0JRH4 Y
A2SPS8 Y
A0A5M4AWD2 E
Q6QH01 C
D3F0Z1 E
A6XBM2 M
D6E7B3 Y
Q13E03 Y
A0A060URB8 Y
A0A2T1N7R1 E
D6TCH6 Y
B0CXH8 Y
A3TVQ9 E
Q4WT12 Y
C7QGX3 Y
F0Y9X3 E
A0A7S0D560 Y
A0A160KTE9 Y
A0A2H1HV86 Y
A0A251Y3N4 Y
A0A419AVL2 Y
A0A4Q2QWS1 Y
C7Q1E4 Y
A0A5C5TYS5 Y
F2NNQ0 Y
A0A2R4TRE0 Y
K9YJQ3 E
D9QS43 E
A7SQ16 E
A1DG05 Y
U1SIR9 Y
C4Y298 Y
A0A9W3LFI9 Y
D3RMV7 Y
F3QNA7 Y
E4RTK5 Y
C8XBX8 Y
C0QTA4 Y
E6VIW4 Y
A0A2S6H643 Y
Q46HB1 E
A0A2S5CTX8 E
A0A1T4SF40 Y
K0K7J4 Y
A0A1J5JH24 Y
Q6LMI6 E
A0A9W5JBA9 Y
A0A291PMC6 Y
A0A4Y4DZN4 Y
A0A2R4MBA2 Y
R9PI53 E
A0A6H9GLV4 E
A0A7S4GND2 E
A0A6H9FPY5 E
A0A1G7DX68 Y
A0A075WEB4 Y
A0A140NHJ5 Y
A0A1C6Z081 Y
Q5FA36 Y
Q0ACK1 E
A0A975GIX9 Y
A0A323UE08 Y
U7VB41 Y
A0A063Y780 E
C5CIT6 Y
A0A0A2VPU3 Y
F0RHS0 E
A0A2S5WX34 Y
C1G973 Y
A0A2S6GKF6 Y
A0A0A2B651 E
A0A4R3A5P7 Y
A0A2A7U6W1 Y
Q2GX26 Y
F5XN43 Y
A0A0K2STH0 E
A0A1H1U2Q6 Y
A7SED8 L
A0LV78 Y
K5DBA0 E
B8IZX4 Y
A8LKQ0 E
A0A5C6LWQ1 Y

In [150]:
seqn = []

for i in n:
    print(i.id, i.seq)
    seqn.append(i.seq)

A0A858ZNJ3 N
A0A1H9M798 N
B0DY50 N
P69680 N
A0A3G9G4Q4 N
A0A149UP06 N
F2G6G4 N
A0A2M9D7S8 K
A0A034WGQ2 N
I0KDC6 N
F8D7H6 N
K9W4V5 N
Q466Y3 N
D2SE15 S
A0A377PBY1 K
B1JZ69 N
A0A2W5HTC3 N
A8G2S3 N
D5T4N9 N
Q2RWY7 G
A0A0E3R4G0 N
I4C9L0 K
D5VJ32 N
C0Z5S5 T
C1N6X9 N
J7ITF6 N
A0A068SVR1 N
A0A0D7F328 N
Q0G0A4 N
F0J3F9 N
Q0BQ69 K
F2YIC4 -
D4XLN6 N
A0A420WC79 N
A0A5C5TUT2 N
A0RUZ2 N
A0A0A2ZRL7 N
J4UGB7 S
E5Y678 K
A0A0D2KGN8 N
S5ABR8 N
A9DQM8 N
G5EB13 S
A0A2N6NEK4 S
C6DB68 N
Q81GN5 K
Q0F2M5 V
A0A0C6P439 N
B9SWW9 W
L8H5K0 -
Q9NIV0 -
C1N5A7 N
Q1JXS5 K
A0A1M6JKY3 K
F4D1J0 S
A0A257SYX3 W
V4RK08 N
G0V8D6 S
A0A7S4GMD8 N
B3QVV5 N
F2JZ83 I
A0A857DDJ7 H
A0A0S6UHP2 N
D5EP71 N
F4KY49 N
M5S9B4 N
A0A009PYN3 K
A0A3T0SZ22 S
A0A248LMH8 N
A0A6H9GEE4 N
A7HSP2 K
A0A7V8IKS6 N
T2JFS5 N
F6FRU9 S
A0A9E9L9J1 N
A0AIW5 N
A0A0E9NHV4 S
Q2N625 N
C8WSI9 K
A0A1H1BPD6 S
A0A176XNC5 N
A0A4V0XUI3 N
A7S3L2 N
M5U2P1 N
K9P5D1 K
Q0F2M7 N
A0A2R3IMJ8 N
Q2RVB5 K
A0A556RTU3 N
E0TGP9 N
B7G0Y1 N
A0A1G9P6Q0 N
D0LTW3 N
Q6BT62 H
Q2IK04 N
Q6BJI7 S
B7X047 N
A0A068NPW2 N
A0A399NT81 S
K0F9X7 N
A0A037ZMW1 N
A0A075JZ35 N
A0A369MHK2 N
A0A1B9JPL5 N
D8PD01 K
A0A2G5BI87 N
A0A2G5BGA9 N
A0A657K391 N
P69681 N
A0A4P6UIJ8 K
A0A0V8M0W6 N
A0A0H2XSU4 N
Q1Z695 I
A0A7Z0V0A4 K
K0ER80 G
A0A149UWF2 N
G0H0Z6 N
G0EFF3 R
C8WLL8 N
X5CNT2 W
A0A4Y1MSE7 K
H2CLF7 N
M4VEJ9 -
A0A4V2X6C2 N
A0A2K1RA77 W
A0A375YPN6 N
A0A7M6UUM4 -
A0A172YCA7 N
A0A918MJ52 N
A0A2S8QA29 N
A0A251XJT0 S
A0A0B4E6X7 N
A0A0K2STQ7 N
A1C5Z7 S
C9KKP2 N
A0A2Z4MD56 T
Q9VFA9 N
A0A502GPV4 N
I5C044 N
D2V6P8 -
D3RN22 I
Q97L80 K
A0A0D5YN10 K
A0A1I5GN22 S
A0A1Y5E8I7 N
B1Y8C9 N
M5SYZ1 N
Q6HM26 K
A0A379A0S9 N
A0A101DCS3 N
A0A1Y3U5V2 N
A0A202B535 N
F8E6R1 N
Q6ND36 N
A0A8H6K7L7 S
Q7NCB8 N
A0A369MRW6 N
C9RS76 N
A3U857 K
A0A127PIQ9 N
B8FGW0 K
A0A060JMP6 S
D5V7B3 N
A0A494JB70 N
A0A5M8QF12 S
A0A8G2F3G4 N
J7L3W8 S
G0JRG9 W
D3DJN2 D
A0A1Y2JH43 N
Q1L727 N
A0A7T2S0Z6 N
A0A315S845 A
A0A2S6H6B7 N
A0A1J5NTP7 N
A0A0E3QY86 K
A0A096EEV9 N
A0A380S5X4 N
B8ZYW3 V
A0A2S8GEJ5 N
A0A248TDF2 T
B2GFN1 G
U1PPI7 N
C7LW88 N
G3A431 N
A0A066ZTE4 N
L7CG99 N
S0ET45 N
A0A178TA08 Q
H1XV27 N
A0A6M3ZJI1 N
U5DEY6 N
H6LFQ2 N
Q6CRN0 H
A0A4Q2EAG7 K
A0A1J5NNB8 N
E3I393 N
A0A243SC06 K
D4F313 N
W0F0I7 K
A9B874 N
A1D2Y5 S
T2J0N1 N
Q2FQT3 N
A0A075WG29 N
A0A979GQ79 N
A0A381CAY8 K
A0A2G3DSU6 N
A0A168EVK8 K
A0A094W9G3 N
A0A4R3NVT3 N
W0DYY3 N
G8JTW0 S
A0A4P6UIK6 N
I9P003 N
G2T1Y3 N
B8EMQ8 N
I6Z905 A
E0TCV4 N
A3XNG6 N
A0A087MGU4 N
A2BUP4 N
A0A562S8V2 N
A0A495DND0 N
A0A0S2FHD7 N
F3QPR6 N
A0A063Y394 N
F6G5I9 N
A0A323UDG5 N
A0A0G9HEC5 N
B8FDY8 N
Q5KPM5 N
A0A147EQL9 S
A0A854Q6X9 N
C3X1J1 N
A0A5B2V3B9 N
A0A258FS85 N
A0A7T2W1B3 N
A0A060UN76 I
G0JRQ3 I
D5UD26 S
G2ZN72 N
A0AA46Q839 N
A5UJR1 N
L1INN6 N
C1F584 N
C5LAG4 N
A0A2A2MCP3 -
B1Y6V4 N
A0A1G6ABK5 I
A0A6A1TYJ4 N
A0A2T4UWF1 S
V4AP67 N
A0A173R3W6 N
C7NND3 N
B0DFJ4 N
A0A3E2VY88 A
R1EDV9 N
J1L5M8 N
D7G265 N
Q8ERT9 N
I4D6Z9 N
A0A4R6DFU8 S
A0A060URC3 W
D2BIB2 N
F5ISF6 N
A5CRL2 S
A0A6G9XJV9 G
Q59UP8 H
A0A6N4SPH9 N
I0HGY4 G
X5DX97 S
L1J6I4 N
I1DSU5 N
B9L7N1 N
Q1Z4I4 N
Q21CP1 N
A0A165MFD1 N
V4CRP5 N
Q7S5K0 A
A0A071MMV1 N
A0A149RYW7 N
A0A7G5EC77 N
A0A1W2GZ82 N
A0A7U3XVQ4 K
A0A071M4L5 N
U5C2K4 N
A0A248LNW8 I
L8H844 N
A0A149V596 N
S9QZ09 N
B1ZSW9 N
D2BUJ8 K
A0A9Q8L398 N
M5S735 N
Q6ARH0 N
K6W5X0 A
G0JRG6 W
A0A6H9FYW4 N
A0A0S4WFM4 N
A0A101HKN9 N
Q9REX3 N
F0S3Z6 I
A8NAG3 N
C6LBD3 N
A0A149U2G9 N
V4REY8 N
A0A0H3H4I7 K
A8N2H6 S
S0APH6 Y
A0A017SYR8 N
A0A1B9MZ78 N
E4T3F3 N
D7E934 N
A0A0M3AB44 N
A9WHW6 N
A0A5M4AUM9 N
A0A1X4GBG2 N
I4D1H5 N
A0A0E3QYF3 N
B0CQX4 S
A0A378YR15 N
A0A495D4X4 N
A0A076PL76 N
Q1YDY7 N
A0A3E2UCG9 A
A0A2K3DPU7 -
A0A3R9Q7C4 K
V5U2Z4 K
K9P718 N
M1V7W3 N
Q6LKC8 I
E5Y789 R
J9Z839 W
A0A1G7VM92 N
K9Z0D3 N
A0A482TED1 N
R1EGK6 N
J1ASR8 N
A0A7U4E420 N
K9YR86 N
A8PXT8 N
A0A0U1NJW3 N
B8FL88 N
A2CCK1 N
D6TFE1 N
A0A2H4U5R1 N
I2GD40 N
A0A060HFT5 N
B1Y842 I
A0A0X8NXA9 N
A0A0A2A5X1 N
A0A318FY98 K
Q7V4T8 N
A0A1A0DHK0 -
C1A872 S
A0A395VB65 N
A7MFK3 K
J4KM12 S
A1SY01 N
A0A1H4DJ49 N
A0A9R0NTP8 S
A3PAY4 N
B4CV94 N
A2C095 N
Q2HD43 S
A0A836M2B6 K
H6RWK9 S
A0A087EQK8 K
A0A1I0AQM4 -
L7CG11 N
A0A248LNK5 D
B7FTM9 N
L0K9M1 N
I4D6Z7 K
A0A2K1RA81 W
Q2WBF7 K
A0A1B9BUU6 W
A0A2S0JW39 N
A0A2S5YID7 S
B3PIH2 N
U3P8G1 S
C9R9J0 N
A8AC17 R
F0YLV7 N
A0A1D3GAE9 N
C1MHX0 Q
A0A1H4KAQ7 N
A0A2T4XZC1 K
A1B3N0 N
C7LW87 N
A1SZ12 N
A0A2T2Y0D5 K
A0A1H8D0R8 -
A0A2S5V2F6 N
G3IYW2 N
F5L8M7 T
C7BJG7 N
E4U5Z1 K
A0A1B9K8L2 K
A0A2S5WMT7 S
A0A0D2UPA8 N
A0A161SKF4 S
B4D7W2 K
A0A1H3WA00 N
C1D6X6 D
A0A4D6KHD1 N
Q488X2 N
A9V5W4 -
A0A5M4ATH9 N
E4TRS4 N
A0A011U1K7 N
C7R314 S
A0A077EFU9 N
A0A0A2A0Y9 N
A0A0D8BQX6 Q
A0A0L0S493 N
A0A328Q6M1 N
A0A016XCG9 N
B7FSA7 N
G0AFH4 N
A0A177W826 N
A0A2S8GF54 N
Q1YDY8 N
Q5QVH2 N
A3ZT81 N
A0AA35XZV0 N
F4H924 N
K0NJH2 A
A0A1V3SSW1 N
F2AUF4 N
A6DN47 N
W8KM07 N
A0A1X3RP39 K
A0A7S0KKL8 N
A0A318QZ80 N
K8VZC6 N
A0A1B9JZS5 K
A0A2S6GKN5 N
A0A4R2Z2K6 N
H1YCC3 K
E1QIU3 N
A0A8H6MPB9 S
A0A369N7Y3 N
T2IEJ2 N
H5UND3 S
Q1PX09 N
A0A149TSA9 N
F2NGJ8 N
A0A0E3SHQ9 N
Q5FLR6 N
S0EUS1 N
A0A369M386 N
W0DZS7 N
A8MCL4 Y
V3ZVE4 N
O26757 -
A0A317FZW2 N
A0A085GI50 K
A1ZGK6 N
G0IYI2 N
A7S731 N
A0A1U9YY82 N
A0A328EMN2 N
A0A8E2UDJ3 S
A0A2S5WUP6 N
A0A8H7P8U1 N
A0A257T7G4 W
B3MX93 N
A0A1G5W0P2 N
D4H2Y7 N
A0A4P8HC89 S
Q7T070 -
F7NPQ3 N
B9SA70 W
Q9M6N7 W
I7ZHW3 N
F4XTK4 N
A4G1J2 N
G7WFX4 N
B8JBH5 K
D9QPC8 N
A0A4R7GKA0 N
R9PMC6 I
A0A0E3LMT4 N
A0A511NGC7 N
E4NS62 N
E4T3F7 N
M0D580 N
J7J5E7 N
B1XZU2 I
A0A366IE34 N
A0A6U2BIY7 N
Q9QXP0 -
A0A424WAH3 N
A0A410K1J5 N
L1IHZ8 N
I8TC71 N
A0A7U8C744 N
A8M670 G
A0A0S4VNK2 N
Q2SIR0 I
A0A5C4RNH5 K
A0A3E0X011 N
A0A0E3SP24 K
E1IF27 N
Q2YBP7 -
A0A2S5WZU0 S
A0A172YBR4 N
A0A0K2STK6 N
A0A2N6JV02 N
F0S0G1 N
A0A1C7EL50 N
Q18PF5 -
A0A1I0C958 N
A0AA35XVN2 N
L8GGA0 N
Q3AP28 N
D0MFE9 K
J9VXX9 N
A0A166IS52 N
F0J7D3 W
W7QG13 N
A4BMY5 N
A6LV49 N
Q1H483 N
A6M3G0 N
E4T0A4 N
A0A3E2UHE6 A
A0A174SD65 N
A0A855EH99 N
C3YB74 N
A0A074KZD8 N
J0S2I0 N
K9WSX4 N
E8RLT5 N
Q2FS34 N
Q3Z7F9 N
Q2S8H9 N
A0A060HN92 K
E6ME92 K
A0A172RYW3 N
L0FU80 N
C8WZE0 N
A0A2S8F4W0 N
A0A2C6C0X3 N
F3ZVV4 N
A0A7R6PER3 N
A0A495WJM6 N
A0A0B4DUR9 N
A0A251YU48 S
A5D4I5 N
A0A2X2C038 K
A0A2A2M8K7 K
D3FBG3 N
A0A2V4EA49 N
D0MFE8 N
Q3B6Q2 N
A0A1B9KID3 N
A0A9J9ES23 I
A0A3N2SFS2 K
Q0VLH1 N
A0A1U9Z147 R
Q0G2T1 N
A6GJF5 N
A0A059XXR1 W
A0A5J6WPP9 I
P41948 H
L1IUV5 N
A0A2W0GQV0 K
Q1K433 N
A0A4Y7XC43 N
D5AU98 S
E1QFA8 N
A0A075WBP9 N
Q0BWD0 N
A0A1Y0HX98 S
A0A098S5Y7 N
Q0I445 N
A0A1E5BXA4 N
A0A2C9CK98 N
G4H971 T
A0A1I0BYN1 R
A0A330GB00 K
A0A2S8FR08 N
Q84KJ6 W
A0A2S5WGI8 N
M2ALH9 N
A0A2K3DQF8 N
A0A8G2IZM3 N
F5Y3C1 N
A0A370FPU0 N
F5RGM7 N
A0A4R4K1P9 N
R8VWI7 N
A0A0A2AMW2 N
Q7Z1M1 N
A0A414NWT8 N
A0A0P6VSR8 N
A0A0L0TDW1 N
U3PCH5 G
W7QGE0 N
C5BWX7 S
A0A1B9M1A9 N
B8GGC3 N
D6SPD1 N
A0A0H3DR67 N
A0A4R7VEK0 N
G4R7P1 N
A0A1M5ZVP9 N
A0A2S5Y0D3 S
I0ICG0 N
D0L8H3 N
A0A1B9LFW3 N
Q6ND34 N
A0A6H9GWG4 N
Q5UZ98 N
A0A2S0P9T4 N
H2CDR5 N
T2KGT3 N
A0A088E6Q7 F
A0A258HS77 N
E1V4T3 N
B7GKP4 Q
Q9QUT0 -
I3Z3H7 N
G7WCB6 N
A0A1Y6GLJ1 K
A0A0S2DQB6 N
Q6CRN1 H
A0A401X433 N
A7HT14 N
A0A009TDB1 K
D4XSW0 I
B0SRS8 N
A0A149QSR6 N
B1Y0E5 N
Q7UGU7 N
A0A2S0Q8P1 N
F0ZPL3 N
A0A2T0GTU1 G
I4CCD1 N
A0A9Q6P4A5 N
A0A418VIJ8 N
C1MX19 N
A0A1B9BUZ8 N
K9W6F3 R
Q1K8A3 S
L8GFX3 N
A0A1G6ABL9 K
A0A087L0B9 N
A0A073CP02 N
A0A0A1ZJU5 N
A0A258HPP1 N
A0A149QAW7 N
D2V6Q5 N
A0A1X4G8K1 N
A0A067Z3S3 N
A0A8F5ZDT8 N
A0A854QN45 N
A0A2N7LCD7 N
G7WFX2 N
A0A7S4GNJ2 N
A4G0C5 N
A6VE60 N
A0A1S1HM83 -
A0A037ZJY5 N
N1WR17 N
Q2W5V2 I
A1VIM5 S
A0A1Y5E3E3 N
A0A1T4SFK4 N
A7RNC3 N
M7XJ51 N
A0A399T909 S
A0A2N6P374 S
H8L2Q4 N
D5EP68 N
E6SF19 S
A0A1T4SFY6 S
D3LBI0 N
E6W5C1 N
Q0VPH4 N
K9WT03 N
L0KW14 N
A0A4R8H081 N
A0A1B9N3H7 N
B0RC35 S
A0A420KGW4 N
A0A4R3NLV5 N
Q47K18 N
Q21P82 N
M1WRK6 N
A0A290XBB5 N
A0A6T9XUR2 N
A0A1J1JH03 N
I3R0S7 N
A9UR54 N
A0A1G7H8X3 S
A0A8G2F718 N
Q1H0G2 N
D0LAL7 S
C7LQR9 N
A0A1G5PWV0 K
K1K628 N
B9SXC7 W
G7WA28 N
Q1IWN6 G
H6LKH9 N
A0A1H7CU41 N
G8JUJ2 H
A0A081N2G5 N
A0A074ME37 K
Q0VQH6 N
C8XB51 S
A1VIG8 N
Q8GQS1 N
A0A1I7FBM5 -
A0A1M6ZMI3 N
A0A482PLH3 N
A0RXK8 N
D0KXQ0 I
Q8JI14 -
A0A7T4WEP4 W
A0A4R3ZNW3 S
A0A074KY88 N
A0A6M3ZKU5 I
M1SJL5 N
A0A1W9KSU5 N
E3GI40 N
A0A369NYJ2 N
A0AA92K392 N
O04161 N
A9BQZ4 N
A0A6N2Z556 N
A0A8H6NAG3 S
A0A2T9X1V4 Y
Q2J376 N
A0A0F5EZP7 N
A0A7G5DK18 N
M9YAI9 N
D2ZRW2 N
G7UUY6 N
A0A8H4GS02 S
A0A2T5IHP0 -
A0A165MAC2 N
A0A7S4LPS8 N
A0A075JIN0 S
C8X554 N
B8FZP7 N
Q5KAF6 N
A0A427KNL6 N
A0A7G5DPV0 N
Q22947 -
A0A1S1HRJ0 N
A0A3N1VXY4 N
A0A2S7YPJ9 S
I0JI83 T
A0A7U3YMN6 N
Q9BLG3 S
A0A1H9RTW8 N
A0A1I4W3A0 S
A0A0B4M163 -
U2EN72 N
A0A2W5VAZ2 N
E4YA63 N
D5ELM4 N
M9RJS5 N
A0A2G3E8V2 N
Q5FSX6 N
I0HKQ8 N
A0A833H2R7 N
B8ENL9 N
B3DUX7 N
A0A1D8UWJ6 N
D5E995 N
A0A7U8C2Y6 I
L0KGR8 N
B0VMH1 K
P40260 S
L0JT30 N
C1GR74 S
A0A423Y4I6 K
A0A4P7UHQ5 R
A0A8E2R1Y5 S
I5BYV5 N
A0A6B8N021 K
A0A7G5DPV1 N
A0A2G5RQK9 Q
A0A5M4B0G1 N
A0A6S5K4J1 K
C1D4X0 N
A1SVA8 I
H1YF74 N
A0A8B4RWH8 N
A0A0A0D6K5 N
A0A0A2BBY0 N
A0A089ZBW5 N
A0A068TC78 N
Q46G49 K
A1CQ21 S
A0A1G6ABX1 N
E1SLM7 N
K5CFE5 N
Q2YLQ6 N
Q0G2V0 N
A4ABK3 N
A0A9Q5QVI9 N
A0A4Q7Y9I7 S
A9HMD6 N
K9YN27 N
Q9UBD6 -
D9SI59 N
Q8I0L6 -
A0A142VAD6 N
G3IYW0 N
A0A062IU58 K
R1D1H4 N
A0A366XFS8 N
A0A7S4GNF3 N
F0J6E8 N
A0A7U4DN04 N
V4RHR4 N
F7ZJM0 N
A0A2S5XAB8 S
U5C4L4 N
Q21J04 N
A0A142NNN1 S
H1Y7T6 N
F5R974 I
B0DU91 S
A2BP62 N
A7HSN9 I
A0A377I7W9 N
D2RU19 N
G7WJN0 N
E2SD33 S
A0A0D7F2Y9 N
A0AA92EGF5 N
A0A9E9LXV9 N
A4BEP1 I
A0A0E3WZH5 N
F7ZEU9 N
A5E3X2 H
A0A0A3XTJ3 N
A0A830ZZN8 N
A0A1S8D478 N
J7IVQ1 N
A0A2U1SS17 N
S3K1S2 K
C6XKC2 N
A0A2S7YIM5 S
K2IMJ7 N
Q5P1S8 I
A0A7T5BFQ2 I
A0A556SRH6 N
A8P923 N
A0A7G5DKA9 N
L8JUH3 N
A0A0D2LEF5 S
A0A258FTB0 N
A0A5P9P1L2 N
M8E0R3 Q
A0A6J5IRX5 N
W5WIX6 S
Q82X47 -
I4DBY0 N
A0A6F8TLE9 K
A0A1G7UZX2 I
A0A6P4JM51 N
G0J614 N
U2WTW8 Q
A0A642KQG8 V
Q1AUG3 I
A0A6G9Y3Q0 N
B8J5X4 N
M7NFH3 T
A0A0E3R6S1 N
Q2IHY5 K
A7I8Z2 N
L1IYP4 Q
B4HDZ9 N
A0A366WYI9 N
E4TJ50 -
A0A7S0ILH2 Q
A4BAE1 N
B3QRJ4 N
A0A5C5BWI6 N
Q7NQY2 N
A0A091AXI3 N
Q1QSQ2 N
R4FZE3 Q
A0A2N0MZ27 N
A9BTK1 N
A0A242NIL1 N
G0LFE3 N
A0A1B9NQ91 N
A0A5M5PZE2 V
A0A0D2NYP3 N
D9QPE5 N
I5B3H0 N
L1IYW7 N
C6WEW7 S
B7FW68 N
F4GED5 N
A0A4R8GSH7 I
A0A1W2H3F0 N
A0A3E2T713 N
A0A0H3KTD3 N
A0A1Y4LM49 N
G2PRJ6 N
A0A0X8X7Y7 N
K8EJ02 N
A0A1L3F1X5 N
G8TK77 N
A0A855F5Y8 K
A0A975BTN0 N
A0A562RGZ4 A
G5EB09 S
A0A833LX85 N
U1H1F7 N
K8W1E2 N
E3HJW8 N
Q7SEH0 S
Q47X17 N
B0DXT9 S
A0A3G9G2C9 N
Q95P70 -
A0A837C6X5 N
Q89WR5 N
A6DUG4 N
D7UQE2 -
A0A2I1M481 A
A0A0T7GZ59 N
O66395 N
J3EXK0 N
A0A1B9MYL7 N
K9U8C7 N
E2SD44 S
H6LKH6 N
Q605Y6 N
A0A9Q9D9I3 N
A0A6N2TIA4 N
A0A1E3PQH0 N
A4CMI3 N
Q1K0H9 N
A0A0S6UEK9 N
A0A0H3LUA3 N
B9LU00 N
A9BIZ7 N
A0A7H8UK07 N
E3H8C9 N
M2A398 N
Q1QS12 N
G0VI62 H
A0A1Z3MS36 K
A0A0B5FNH4 N
D9SI36 I
A0A410JZR4 N
F7ZJZ1 N
F0ZCX7 -
W0DZX1 I
A0A4R3ZZ35 S
A0A317G0I6 N
Q0ARJ4 N
A7I8Z4 N
T2KJ59 N
I3C0V3 N
E3H8A6 G
B2IJT1 K
A0A2G6JLT9 I
A3ZZL7 N
A0A2T0XPP2 N
Q31CR9 N
A0A1R1IDV3 N
K2JVF8 N
V5BYZ7 N
D8J4C6 N
D4H5F9 N
K9ZG59 N
A0AA86YS65 N
Q608B6 I
A0A562BXM4 N
A0A401WXG0 -
A0A857DMN9 R
A0A1X6N3Q5 N
A0A173R3X4 N
Q63EK5 K
K9ZLY2 N
A0A533I6R2 N
I0WJ97 N
K0N2R5 N
M0J579 N
B8GGC1 N
A0A6H9GFU4 N
C6CBB1 K
A0A510HHK8 I
A0A1B9MBX6 N
A0A9Y2AG30 G
E8RSE4 N
F2B2B8 N
Q7UYZ3 N
I1YJH7 N
A0A853MG28 N
A0A0L0STS6 N
A0A251XU71 S
Q60BI2 N
A0A829X098 N
F3KUN4 N
Q60C43 N
A0A0T7FAP8 N
A0A3E2TW06 A
W0E077 N
A0KPE9 N
R7PZ71 N
A0A0A1ZMZ9 N
A0AA40J491 N
D3S2L0 N
A0A373FQ71 N
A0A0A2C6L1 N
Q7W7D3 N
A0A165K0X5 N
A0A2S5X482 S
R9GM11 N
Q0G0A3 N
D4GLQ6 N
E7RJZ0 N
F8IJE0 N
A0A1V2XMU9 N
Q7TNN9 -
A0A1G5RZU9 N
A0A2N6K4Y5 N
B0SLB7 K
A0A251YFS0 S
B9WDK0 S
Q7N0M6 N
A0A0M2LU39 N
F4B548 Y
D6Z5V9 N
A0A4R2M206 N
A0A1E2SKM1 G
A0A127JTU2 N
A0A212AV03 N
G4QHD2 N
A0A021VMC6 S
A0A2J7TJ33 N
G7WDB5 N
Q6BK68 S
Q1K3N8 N
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 N
A0A377PLP5 K
W7QGM4 N
A0A015YIP3 N
A0A060UWC8 W
A0A1I4ZIZ6 N
A0A264VQM8 N
A9AUR8 N
A0A1W5PRD1 -
A0A0E3BR91 N
A0A1B0ZRL8 N
B9ACS5 N
Q92BJ7 N
F2JTN3 N
A1AVV2 N
D2Q0J8 S
A0A3S9N9F3 N
A8ZQD5 N
C3X831 N
A0A1M6BPM0 N
A0A8F5VN39 N
A0A1E5C7W4 I
A0A2S5WV24 S
A0A833GZR2 N
C7M2A9 W
A6W7U2 S
W0JIB3 N
Q07UM3 N
A0A066ZRQ5 N
S0G181 N
D3PAH1 N
Q4WHC6 S
A0AA94HTL8 R
D5ASL9 N
A0A4U1JNL6 S
M0MDP9 N
A0A653N397 N
A0A2S8GSU9 N
A0A097R891 K
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 K
A0A1B9JHS5 N
D3PE53 K
A0A9J9BAE8 N
Q2RM12 N
A0A3N0AQL8 N
C5KTM6 N
M1P5F0 N
I1YG38 I
A0A660CH85 S
A0A2N7L7C8 I
Q5KZZ9 Q
M1NZT5 N
A0A225CMT8 S
A0A068NV61 N
H2CJI0 N
B0DU93 S
Q221S8 N
F4Y3C5 N
Q94CJ2 -
M0D3Q9 N
A0A3P2A7W8 N
C0GKN4 N
Q7T3R4 -
A0A562USB9 N
A2SS52 N
A0A211ZGL5 N
A0A4V3ALP8 N
A0A147GP06 N
H2IZ00 N
Q45HK8 N
A0A6C8LST1 N
A0A257T8W6 W
Q5P470 N
I5AZQ4 N
Q07UM1 N
E5B358 N
A0A1Y4L5P0 N
Q3AFY9 N
B0BZN3 N
A0A1Q2C7H7 N
A0A4R5U5V1 N
H6LKX6 N
A0A1Y0UZX2 N
F6BEI0 N
M9RKT6 N
A7SGD4 N
A0A257TE48 I
R1FI09 N
E4N1T5 H
U1PIR6 N
F2JYR9 N
Q84KJ7 W
A0A2S8FTB5 N
D2R647 N
G9Y5B0 K
A0A144NLT9 K
A0A5J6WQU1 N
D2R355 N
F3ZYD6 N
B0SL05 N
A0A5A7MAJ9 N
A0A977NL43 N
A0A433ZQ80 N
A0A1Y0V4A5 -
A0A1M7UEG2 S
G8R7U9 N
K1LDP0 N
B7G0Y4 N
A0A2W4ZXC0 K
B3PF77 N
Q2KZK9 N
Q18ES8 N
D3F545 V
B4S394 K
Q1Q357 N
Q9H310 -
D3PKL4 N
M5SY07 N
Q8RUT6 N
A7NKH2 N
Q1Q879 N
A0A1B9M5B8 N
A6LRS5 K
J2ZGN6 N
V5E0F3 N
A0A149RQX0 N
A0A165BP25 K
C0QSY0 N
B0XVV6 S
E0SD83 K
A8HSA2 T
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 N
Q0AT01 N
A4FMG0 G
C3YB73 N
A0A9P3CXY2 K
A0A0L8BVU4 N
A0A401WUW1 N
I4C9L2 N
Q8RUE9 -
F0JGZ1 N
A0A2I0UUY1 N
A0A542XGT4 G
G0JRH4 N
A2SPS8 K
A0A5M4AWD2 N
Q6QH01 T
D3F0Z1 I
A6XBM2 -
D6E7B3 N
Q13E03 N
A0A060URB8 N
A0A2T1N7R1 N
D6TCH6 N
B0CXH8 N
A3TVQ9 N
Q4WT12 S
C7QGX3 S
F0Y9X3 N
A0A7S0D560 N
A0A160KTE9 S
A0A2H1HV86 S
A0A251Y3N4 S
A0A419AVL2 N
A0A4Q2QWS1 N
C7Q1E4 S
A0A5C5TYS5 N
F2NNQ0 K
A0A2R4TRE0 N
K9YJQ3 N
D9QS43 A
A7SQ16 N
A1DG05 S
U1SIR9 A
C4Y298 S
A0A9W3LFI9 N
D3RMV7 N
F3QNA7 N
E4RTK5 N
C8XBX8 S
C0QTA4 S
E6VIW4 N
A0A2S6H643 N
Q46HB1 N
A0A2S5CTX8 N
A0A1T4SF40 N
K0K7J4 S
A0A1J5JH24 N
Q6LMI6 N
A0A9W5JBA9 N
A0A291PMC6 N
A0A4Y4DZN4 S
A0A2R4MBA2 N
R9PI53 N
A0A6H9GLV4 N
A0A7S4GND2 N
A0A6H9FPY5 N
A0A1G7DX68 N
A0A075WEB4 N
A0A140NHJ5 N
A0A1C6Z081 K
Q5FA36 N
Q0ACK1 N
A0A975GIX9 N
A0A323UE08 N
U7VB41 K
A0A063Y780 N
C5CIT6 -
A0A0A2VPU3 S
F0RHS0 N
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 N
A0A0A2B651 N
A0A4R3A5P7 N
A0A2A7U6W1 N
Q2GX26 S
F5XN43 S
A0A0K2STH0 N
A0A1H1U2Q6 S
A7SED8 -
A0LV78 N
K5DBA0 N
B8IZX4 R
A8LKQ0 N
A0A5C6LWQ1 N

In [151]:
seqd = []

for i in d:
    print(i.id, i.seq)
    seqd.append(i.seq)

A0A858ZNJ3 S
A0A1H9M798 N
B0DY50 S
P69680 S
A0A3G9G4Q4 A
A0A149UP06 A
F2G6G4 L
A0A2M9D7S8 S
A0A034WGQ2 D
I0KDC6 S
F8D7H6 T
K9W4V5 V
Q466Y3 T
D2SE15 N
A0A377PBY1 S
B1JZ69 A
A0A2W5HTC3 A
A8G2S3 V
D5T4N9 H
Q2RWY7 G
A0A0E3R4G0 V
I4C9L0 S
D5VJ32 S
C0Z5S5 T
C1N6X9 D
J7ITF6 S
A0A068SVR1 S
A0A0D7F328 A
Q0G0A4 S
F0J3F9 A
Q0BQ69 A
F2YIC4 -
D4XLN6 S
A0A420WC79 L
A0A5C5TUT2 S
A0RUZ2 N
A0A0A2ZRL7 A
J4UGB7 Q
E5Y678 T
A0A0D2KGN8 S
S5ABR8 L
A9DQM8 D
G5EB13 S
A0A2N6NEK4 S
C6DB68 S
Q81GN5 S
Q0F2M5 D
A0A0C6P439 S
B9SWW9 N
L8H5K0 -
Q9NIV0 -
C1N5A7 D
Q1JXS5 S
A0A1M6JKY3 G
F4D1J0 N
A0A257SYX3 N
V4RK08 A
G0V8D6 S
A0A7S4GMD8 D
B3QVV5 S
F2JZ83 D
A0A857DDJ7 S
A0A0S6UHP2 V
D5EP71 S
F4KY49 S
M5S9B4 D
A0A009PYN3 S
A0A3T0SZ22 S
A0A248LMH8 S
A0A6H9GEE4 V
A7HSP2 A
A0A7V8IKS6 S
T2JFS5 V
F6FRU9 N
A0A9E9L9J1 S
A0AIW5 S
A0A0E9NHV4 S
Q2N625 S
C8WSI9 T
A0A1H1BPD6 N
A0A176XNC5 S
A0A4V0XUI3 V
A7S3L2 D
M5U2P1 D
K9P5D1 N
Q0F2M7 S
A0A2R3IMJ8 S
Q2RVB5 A
A0A556RTU3 S
E0TGP9 L
B7G0Y1 D
A0A1G9P6Q0 L
D0LTW3 V
Q6BT62 S
Q2IK04 V
Q6BJI7 S
B7X047 S
A0A068NPW2 S
A0A399NT81 S
K0F9X7 N
A0A037ZMW1 L
A0A075JZ35 S
A0A369MHK2 N
A0A1B9JPL5 S
D8PD01 G
A0A2G5BI87 S
A0A2G5BGA9 S
A0A657K391 S
P69681 S
A0A4P6UIJ8 S
A0A0V8M0W6 S
A0A0H2XSU4 A
Q1Z695 D
A0A7Z0V0A4 S
K0ER80 N
A0A149UWF2 A
G0H0Z6 D
G0EFF3 S
C8WLL8 S
X5CNT2 N
A0A4Y1MSE7 A
H2CLF7 V
M4VEJ9 -
A0A4V2X6C2 S
A0A2K1RA77 N
A0A375YPN6 A
A0A7M6UUM4 -
A0A172YCA7 S
A0A918MJ52 I
A0A2S8QA29 S
A0A251XJT0 S
A0A0B4E6X7 I
A0A0K2STQ7 V
A1C5Z7 S
C9KKP2 T
A0A2Z4MD56 T
Q9VFA9 D
A0A502GPV4 S
I5C044 L
D2V6P8 -
D3RN22 D
Q97L80 G
A0A0D5YN10 S
A0A1I5GN22 N
A0A1Y5E8I7 L
B1Y8C9 S
M5SYZ1 D
Q6HM26 S
A0A379A0S9 L
A0A101DCS3 N
A0A1Y3U5V2 N
A0A202B535 A
F8E6R1 L
Q6ND36 A
A0A8H6K7L7 S
Q7NCB8 N
A0A369MRW6 N
C9RS76 V
A3U857 S
A0A127PIQ9 S
B8FGW0 G
A0A060JMP6 S
D5V7B3 I
A0A494JB70 S
A0A5M8QF12 S
A0A8G2F3G4 G
J7L3W8 N
G0JRG9 N
D3DJN2 N
A0A1Y2JH43 S
Q1L727 D
A0A7T2S0Z6 S
A0A315S845 N
A0A2S6H6B7 S
A0A1J5NTP7 G
A0A0E3QY86 S
A0A096EEV9 S
A0A380S5X4 V
B8ZYW3 T
A0A2S8GEJ5 D
A0A248TDF2 T
B2GFN1 N
U1PPI7 D
C7LW88 D
G3A431 S
A0A066ZTE4 L
L7CG99 D
S0ET45 N
A0A178TA08 S
H1XV27 D
A0A6M3ZJI1 S
U5DEY6 V
H6LFQ2 D
Q6CRN0 S
A0A4Q2EAG7 S
A0A1J5NNB8 V
E3I393 S
A0A243SC06 I
D4F313 S
W0F0I7 S
A9B874 D
A1D2Y5 S
T2J0N1 V
Q2FQT3 S
A0A075WG29 D
A0A979GQ79 S
A0A381CAY8 S
A0A2G3DSU6 D
A0A168EVK8 S
A0A094W9G3 I
A0A4R3NVT3 L
W0DYY3 L
G8JTW0 S
A0A4P6UIK6 S
I9P003 L
G2T1Y3 D
B8EMQ8 D
I6Z905 T
E0TCV4 L
A3XNG6 D
A0A087MGU4 S
A2BUP4 V
A0A562S8V2 S
A0A495DND0 S
A0A0S2FHD7 S
F3QPR6 S
A0A063Y394 A
F6G5I9 S
A0A323UDG5 A
A0A0G9HEC5 S
B8FDY8 G
Q5KPM5 S
A0A147EQL9 N
A0A854Q6X9 S
C3X1J1 S
A0A5B2V3B9 S
A0A258FS85 A
A0A7T2W1B3 N
A0A060UN76 D
G0JRQ3 D
D5UD26 N
G2ZN72 S
A0AA46Q839 S
A5UJR1 N
L1INN6 D
C1F584 V
C5LAG4 D
A0A2A2MCP3 -
B1Y6V4 S
A0A1G6ABK5 D
A0A6A1TYJ4 S
A0A2T4UWF1 S
V4AP67 D
A0A173R3W6 N
C7NND3 T
B0DFJ4 S
A0A3E2VY88 T
R1EDV9 D
J1L5M8 S
D7G265 D
Q8ERT9 T
I4D6Z9 T
A0A4R6DFU8 S
A0A060URC3 N
D2BIB2 S
F5ISF6 S
A5CRL2 S
A0A6G9XJV9 N
Q59UP8 S
A0A6N4SPH9 T
I0HGY4 N
X5DX97 T
L1J6I4 C
I1DSU5 L
B9L7N1 N
Q1Z4I4 L
Q21CP1 A
A0A165MFD1 D
V4CRP5 D
Q7S5K0 T
A0A071MMV1 A
A0A149RYW7 A
A0A7G5EC77 S
A0A1W2GZ82 I
A0A7U3XVQ4 S
A0A071M4L5 S
U5C2K4 I
A0A248LNW8 D
L8H844 D
A0A149V596 A
S9QZ09 S
B1ZSW9 S
D2BUJ8 S
A0A9Q8L398 S
M5S735 S
Q6ARH0 L
K6W5X0 N
G0JRG6 N
A0A6H9FYW4 N
A0A0S4WFM4 S
A0A101HKN9 D
Q9REX3 V
F0S3Z6 D
A8NAG3 S
C6LBD3 D
A0A149U2G9 A
V4REY8 L
A0A0H3H4I7 S
A8N2H6 S
S0APH6 N
A0A017SYR8 S
A0A1B9MZ78 S
E4T3F3 I
D7E934 T
A0A0M3AB44 S
A9WHW6 D
A0A5M4AUM9 S
A0A1X4GBG2 V
I4D1H5 S
A0A0E3QYF3 T
B0CQX4 S
A0A378YR15 S
A0A495D4X4 L
A0A076PL76 S
Q1YDY7 S
A0A3E2UCG9 T
A0A2K3DPU7 -
A0A3R9Q7C4 G
V5U2Z4 S
K9P718 V
M1V7W3 D
Q6LKC8 D
E5Y789 S
J9Z839 N
A0A1G7VM92 S
K9Z0D3 T
A0A482TED1 D
R1EGK6 D
J1ASR8 A
A0A7U4E420 S
K9YR86 V
A8PXT8 M
A0A0U1NJW3 L
B8FL88 D
A2CCK1 V
D6TFE1 V
A0A2H4U5R1 N
I2GD40 S
A0A060HFT5 N
B1Y842 D
A0A0X8NXA9 S
A0A0A2A5X1 V
A0A318FY98 S
Q7V4T8 V
A0A1A0DHK0 -
C1A872 N
A0A395VB65 D
A7MFK3 S
J4KM12 S
A1SY01 D
A0A1H4DJ49 L
A0A9R0NTP8 N
A3PAY4 V
B4CV94 S
A2C095 V
Q2HD43 S
A0A836M2B6 S
H6RWK9 N
A0A087EQK8 N
A0A1I0AQM4 -
L7CG11 S
A0A248LNK5 T
B7FTM9 D
L0K9M1 D
I4D6Z7 T
A0A2K1RA81 N
Q2WBF7 G
A0A1B9BUU6 N
A0A2S0JW39 T
A0A2S5YID7 S
B3PIH2 S
U3P8G1 S
C9R9J0 N
A8AC17 S
F0YLV7 D
A0A1D3GAE9 S
C1MHX0 T
A0A1H4KAQ7 L
A0A2T4XZC1 S
A1B3N0 S
C7LW87 G
A1SZ12 L
A0A2T2Y0D5 S
A0A1H8D0R8 -
A0A2S5V2F6 N
G3IYW2 S
F5L8M7 T
C7BJG7 S
E4U5Z1 N
A0A1B9K8L2 S
A0A2S5WMT7 S
A0A0D2UPA8 G
A0A161SKF4 S
B4D7W2 A
A0A1H3WA00 S
C1D6X6 T
A0A4D6KHD1 T
Q488X2 L
A9V5W4 -
A0A5M4ATH9 S
E4TRS4 T
A0A011U1K7 S
C7R314 N
A0A077EFU9 S
A0A0A2A0Y9 V
A0A0D8BQX6 S
A0A0L0S493 S
A0A328Q6M1 N
A0A016XCG9 S
B7FSA7 D
G0AFH4 S
A0A177W826 S
A0A2S8GF54 D
Q1YDY8 L
Q5QVH2 L
A3ZT81 D
A0AA35XZV0 S
F4H924 A
K0NJH2 A
A0A1V3SSW1 I
F2AUF4 D
A6DN47 I
W8KM07 L
A0A1X3RP39 S
A0A7S0KKL8 D
A0A318QZ80 V
K8VZC6 S
A0A1B9JZS5 S
A0A2S6GKN5 S
A0A4R2Z2K6 S
H1YCC3 L
E1QIU3 D
A0A8H6MPB9 S
A0A369N7Y3 N
T2IEJ2 V
H5UND3 N
Q1PX09 A
A0A149TSA9 A
F2NGJ8 N
A0A0E3SHQ9 T
Q5FLR6 N
S0EUS1 A
A0A369M386 N
W0DZS7 S
A8MCL4 N
V3ZVE4 D
O26757 -
A0A317FZW2 D
A0A085GI50 S
A1ZGK6 I
G0IYI2 T
A7S731 D
A0A1U9YY82 L
A0A328EMN2 S
A0A8E2UDJ3 S
A0A2S5WUP6 N
A0A8H7P8U1 S
A0A257T7G4 N
B3MX93 D
A0A1G5W0P2 N
D4H2Y7 D
A0A4P8HC89 N
Q7T070 -
F7NPQ3 S
B9SA70 N
Q9M6N7 N
I7ZHW3 S
F4XTK4 V
A4G1J2 S
G7WFX4 T
B8JBH5 H
D9QPC8 A
A0A4R7GKA0 S
R9PMC6 D
A0A0E3LMT4 V
A0A511NGC7 S
E4NS62 D
E4T3F7 N
M0D580 D
J7J5E7 G
B1XZU2 G
A0A366IE34 S
A0A6U2BIY7 D
Q9QXP0 -
A0A424WAH3 S
A0A410K1J5 D
L1IHZ8 S
I8TC71 S
A0A7U8C744 L
A8M670 N
A0A0S4VNK2 S
Q2SIR0 D
A0A5C4RNH5 S
A0A3E0X011 L
A0A0E3SP24 S
E1IF27 S
Q2YBP7 -
A0A2S5WZU0 S
A0A172YBR4 L
A0A0K2STK6 V
A0A2N6JV02 V
F0S0G1 N
A0A1C7EL50 T
Q18PF5 -
A0A1I0C958 D
A0AA35XVN2 S
L8GGA0 N
Q3AP28 G
D0MFE9 N
J9VXX9 S
A0A166IS52 V
F0J7D3 N
W7QG13 L
A4BMY5 S
A6LV49 N
Q1H483 S
A6M3G0 N
E4T0A4 S
A0A3E2UHE6 T
A0A174SD65 N
A0A855EH99 S
C3YB74 D
A0A074KZD8 I
J0S2I0 D
K9WSX4 D
E8RLT5 A
Q2FS34 A
Q3Z7F9 S
Q2S8H9 L
A0A060HN92 S
E6ME92 N
A0A172RYW3 N
L0FU80 T
C8WZE0 D
A0A2S8F4W0 D
A0A2C6C0X3 S
F3ZVV4 N
A0A7R6PER3 L
A0A495WJM6 S
A0A0B4DUR9 L
A0A251YU48 S
A5D4I5 S
A0A2X2C038 S
A0A2A2M8K7 S
D3FBG3 N
A0A2V4EA49 S
D0MFE8 D
Q3B6Q2 G
A0A1B9KID3 S
A0A9J9ES23 D
A0A3N2SFS2 S
Q0VLH1 L
A0A1U9Z147 S
Q0G2T1 C
A6GJF5 V
A0A059XXR1 N
A0A5J6WPP9 D
P41948 S
L1IUV5 S
A0A2W0GQV0 S
Q1K433 D
A0A4Y7XC43 S
D5AU98 S
E1QFA8 S
A0A075WBP9 N
Q0BWD0 L
A0A1Y0HX98 N
A0A098S5Y7 I
Q0I445 S
A0A1E5BXA4 L
A0A2C9CK98 D
G4H971 T
A0A1I0BYN1 S
A0A330GB00 S
A0A2S8FR08 G
Q84KJ6 N
A0A2S5WGI8 N
M2ALH9 D
A0A2K3DQF8 D
A0A8G2IZM3 S
F5Y3C1 S
A0A370FPU0 S
F5RGM7 S
A0A4R4K1P9 S
R8VWI7 D
A0A0A2AMW2 V
Q7Z1M1 D
A0A414NWT8 T
A0A0P6VSR8 S
A0A0L0TDW1 S
U3PCH5 R
W7QGE0 S
C5BWX7 N
A0A1B9M1A9 S
B8GGC3 S
D6SPD1 L
A0A0H3DR67 S
A0A4R7VEK0 S
G4R7P1 L
A0A1M5ZVP9 D
A0A2S5Y0D3 S
I0ICG0 I
D0L8H3 N
A0A1B9LFW3 S
Q6ND34 S
A0A6H9GWG4 V
Q5UZ98 T
A0A2S0P9T4 A
H2CDR5 D
T2KGT3 I
A0A088E6Q7 N
A0A258HS77 A
E1V4T3 L
B7GKP4 S
Q9QUT0 -
I3Z3H7 I
G7WCB6 G
A0A1Y6GLJ1 S
A0A0S2DQB6 S
Q6CRN1 S
A0A401X433 A
A7HT14 D
A0A009TDB1 S
D4XSW0 D
B0SRS8 D
A0A149QSR6 A
B1Y0E5 A
Q7UGU7 D
A0A2S0Q8P1 V
F0ZPL3 N
A0A2T0GTU1 N
I4CCD1 A
A0A9Q6P4A5 S
A0A418VIJ8 S
C1MX19 S
A0A1B9BUZ8 A
K9W6F3 N
Q1K8A3 A
L8GFX3 N
A0A1G6ABL9 S
A0A087L0B9 S
A0A073CP02 V
A0A0A1ZJU5 V
A0A258HPP1 A
A0A149QAW7 A
D2V6Q5 G
A0A1X4G8K1 N
A0A067Z3S3 A
A0A8F5ZDT8 S
A0A854QN45 S
A0A2N7LCD7 L
G7WFX2 T
A0A7S4GNJ2 V
A4G0C5 D
A6VE60 S
A0A1S1HM83 T
A0A037ZJY5 S
N1WR17 I
Q2W5V2 D
A1VIM5 N
A0A1Y5E3E3 S
A0A1T4SFK4 A
A7RNC3 D
M7XJ51 T
A0A399T909 S
A0A2N6P374 Q
H8L2Q4 S
D5EP68 I
E6SF19 N
A0A1T4SFY6 N
D3LBI0 N
E6W5C1 I
Q0VPH4 D
K9WT03 N
L0KW14 S
A0A4R8H081 D
A0A1B9N3H7 S
B0RC35 S
A0A420KGW4 S
A0A4R3NLV5 S
Q47K18 S
Q21P82 L
M1WRK6 A
A0A290XBB5 S
A0A6T9XUR2 L
A0A1J1JH03 V
I3R0S7 D
A9UR54 D
A0A1G7H8X3 S
A0A8G2F718 D
Q1H0G2 D
D0LAL7 N
C7LQR9 D
A0A1G5PWV0 S
K1K628 S
B9SXC7 N
G7WA28 S
Q1IWN6 N
H6LKH9 N
A0A1H7CU41 G
G8JUJ2 S
A0A081N2G5 L
A0A074ME37 S
Q0VQH6 S
C8XB51 N
A1VIG8 S
Q8GQS1 A
A0A1I7FBM5 -
A0A1M6ZMI3 D
A0A482PLH3 S
A0RXK8 N
D0KXQ0 D
Q8JI14 -
A0A7T4WEP4 N
A0A4R3ZNW3 N
A0A074KY88 I
A0A6M3ZKU5 D
M1SJL5 S
A0A1W9KSU5 S
E3GI40 D
A0A369NYJ2 N
A0AA92K392 S
O04161 D
A9BQZ4 S
A0A6N2Z556 D
A0A8H6NAG3 S
A0A2T9X1V4 N
Q2J376 S
A0A0F5EZP7 S
A0A7G5DK18 S
M9YAI9 S
D2ZRW2 N
G7UUY6 S
A0A8H4GS02 S
A0A2T5IHP0 -
A0A165MAC2 G
A0A7S4LPS8 V
A0A075JIN0 N
C8X554 G
B8FZP7 S
Q5KAF6 S
A0A427KNL6 S
A0A7G5DPV0 S
Q22947 -
A0A1S1HRJ0 S
A0A3N1VXY4 S
A0A2S7YPJ9 S
I0JI83 T
A0A7U3YMN6 S
Q9BLG3 D
A0A1H9RTW8 S
A0A1I4W3A0 N
A0A0B4M163 -
U2EN72 L
A0A2W5VAZ2 S
E4YA63 D
D5ELM4 D
M9RJS5 S
A0A2G3E8V2 D
Q5FSX6 A
I0HKQ8 S
A0A833H2R7 D
B8ENL9 S
B3DUX7 S
A0A1D8UWJ6 A
D5E995 T
A0A7U8C2Y6 D
L0KGR8 A
B0VMH1 S
P40260 A
L0JT30 T
C1GR74 S
A0A423Y4I6 S
A0A4P7UHQ5 S
A0A8E2R1Y5 S
I5BYV5 I
A0A6B8N021 S
A0A7G5DPV1 L
A0A2G5RQK9 S
A0A5M4B0G1 G
A0A6S5K4J1 S
C1D4X0 S
A1SVA8 D
H1YF74 M
A0A8B4RWH8 S
A0A0A0D6K5 S
A0A0A2BBY0 V
A0A089ZBW5 N
A0A068TC78 S
Q46G49 S
A1CQ21 S
A0A1G6ABX1 L
E1SLM7 L
K5CFE5 S
Q2YLQ6 S
Q0G2V0 A
A4ABK3 L
A0A9Q5QVI9 N
A0A4Q7Y9I7 N
A9HMD6 A
K9YN27 V
Q9UBD6 -
D9SI59 S
Q8I0L6 -
A0A142VAD6 S
G3IYW0 S
A0A062IU58 S
R1D1H4 D
A0A366XFS8 S
A0A7S4GNF3 V
F0J6E8 S
A0A7U4DN04 G
V4RHR4 C
F7ZJM0 D
A0A2S5XAB8 S
U5C4L4 T
Q21J04 S
A0A142NNN1 N
H1Y7T6 S
F5R974 D
B0DU91 S
A2BP62 V
A7HSN9 D
A0A377I7W9 S
D2RU19 T
G7WJN0 D
E2SD33 N
A0A0D7F2Y9 S
A0AA92EGF5 S
A0A9E9LXV9 S
A4BEP1 D
A0A0E3WZH5 V
F7ZEU9 L
A5E3X2 S
A0A0A3XTJ3 S
A0A830ZZN8 S
A0A1S8D478 A
J7IVQ1 D
A0A2U1SS17 S
S3K1S2 S
C6XKC2 L
A0A2S7YIM5 Q
K2IMJ7 L
Q5P1S8 D
A0A7T5BFQ2 D
A0A556SRH6 S
A8P923 S
A0A7G5DKA9 D
L8JUH3 T
A0A0D2LEF5 S
A0A258FTB0 S
A0A5P9P1L2 T
M8E0R3 S
A0A6J5IRX5 A
W5WIX6 N
Q82X47 -
I4DBY0 S
A0A6F8TLE9 S
A0A1G7UZX2 D
A0A6P4JM51 D
G0J614 I
U2WTW8 S
A0A642KQG8 T
Q1AUG3 N
A0A6G9Y3Q0 N
B8J5X4 V
M7NFH3 S
A0A0E3R6S1 G
Q2IHY5 H
A7I8Z2 D
L1IYP4 S
B4HDZ9 D
A0A366WYI9 L
E4TJ50 -
A0A7S0ILH2 T
A4BAE1 L
B3QRJ4 G
A0A5C5BWI6 N
Q7NQY2 A
A0A091AXI3 S
Q1QSQ2 L
R4FZE3 S
A0A2N0MZ27 S
A9BTK1 N
A0A242NIL1 S
G0LFE3 D
A0A1B9NQ91 S
A0A5M5PZE2 T
A0A0D2NYP3 S
D9QPE5 A
I5B3H0 D
L1IYW7 S
C6WEW7 N
B7FW68 D
F4GED5 S
A0A4R8GSH7 D
A0A1W2H3F0 T
A0A3E2T713 D
A0A0H3KTD3 S
A0A1Y4LM49 D
G2PRJ6 D
A0A0X8X7Y7 L
K8EJ02 N
A0A1L3F1X5 S
G8TK77 S
A0A855F5Y8 S
A0A975BTN0 N
A0A562RGZ4 A
G5EB09 S
A0A833LX85 V
U1H1F7 A
K8W1E2 S
E3HJW8 S
Q7SEH0 S
Q47X17 S
B0DXT9 S
A0A3G9G2C9 A
Q95P70 -
A0A837C6X5 S
Q89WR5 S
A6DUG4 I
D7UQE2 -
A0A2I1M481 H
A0A0T7GZ59 S
O66395 S
J3EXK0 D
A0A1B9MYL7 S
K9U8C7 V
E2SD44 S
H6LKH6 N
Q605Y6 S
A0A9Q9D9I3 S
A0A6N2TIA4 D
A0A1E3PQH0 N
A4CMI3 I
Q1K0H9 L
A0A0S6UEK9 G
A0A0H3LUA3 S
B9LU00 T
A9BIZ7 D
A0A7H8UK07 S
E3H8C9 D
M2A398 S
Q1QS12 A
G0VI62 S
A0A1Z3MS36 S
A0A0B5FNH4 L
D9SI36 D
A0A410JZR4 N
F7ZJZ1 A
F0ZCX7 -
W0DZX1 D
A0A4R3ZZ35 N
A0A317G0I6 D
Q0ARJ4 S
A7I8Z4 S
T2KJ59 D
I3C0V3 D
E3H8A6 D
B2IJT1 S
A0A2G6JLT9 D
A3ZZL7 S
A0A2T0XPP2 D
Q31CR9 V
A0A1R1IDV3 S
K2JVF8 L
V5BYZ7 S
D8J4C6 T
D4H5F9 D
K9ZG59 N
A0AA86YS65 A
Q608B6 D
A0A562BXM4 S
A0A401WXG0 -
A0A857DMN9 S
A0A1X6N3Q5 S
A0A173R3X4 D
Q63EK5 S
K9ZLY2 D
A0A533I6R2 S
I0WJ97 I
K0N2R5 N
M0J579 D
B8GGC1 S
A0A6H9GFU4 N
C6CBB1 S
A0A510HHK8 N
A0A1B9MBX6 S
A0A9Y2AG30 N
E8RSE4 A
F2B2B8 S
Q7UYZ3 S
I1YJH7 L
A0A853MG28 V
A0A0L0STS6 S
A0A251XU71 S
Q60BI2 S
A0A829X098 A
F3KUN4 S
Q60C43 S
A0A0T7FAP8 S
A0A3E2TW06 T
W0E077 D
A0KPE9 S
R7PZ71 N
A0A0A1ZMZ9 V
A0AA40J491 S
D3S2L0 N
A0A373FQ71 S
A0A0A2C6L1 V
Q7W7D3 S
A0A165K0X5 T
A0A2S5X482 S
R9GM11 S
Q0G0A3 L
D4GLQ6 S
E7RJZ0 T
F8IJE0 T
A0A1V2XMU9 A
Q7TNN9 -
A0A1G5RZU9 T
A0A2N6K4Y5 N
B0SLB7 S
A0A251YFS0 S
B9WDK0 S
Q7N0M6 S
A0A0M2LU39 S
F4B548 N
D6Z5V9 I
A0A4R2M206 S
A0A1E2SKM1 R
A0A127JTU2 S
A0A212AV03 S
G4QHD2 D
A0A021VMC6 N
A0A2J7TJ33 S
G7WDB5 D
Q6BK68 T
Q1K3N8 D
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 S
A0A377PLP5 S
W7QGM4 D
A0A015YIP3 D
A0A060UWC8 N
A0A1I4ZIZ6 A
A0A264VQM8 S
A9AUR8 S
A0A1W5PRD1 -
A0A0E3BR91 S
A0A1B0ZRL8 L
B9ACS5 N
Q92BJ7 S
F2JTN3 L
A1AVV2 S
D2Q0J8 N
A0A3S9N9F3 A
A8ZQD5 D
C3X831 S
A0A1M6BPM0 G
A0A8F5VN39 S
A0A1E5C7W4 D
A0A2S5WV24 S
A0A833GZR2 D
C7M2A9 N
A6W7U2 N
W0JIB3 T
Q07UM3 S
A0A066ZRQ5 D
S0G181 I
D3PAH1 N
Q4WHC6 S
A0AA94HTL8 S
D5ASL9 S
A0A4U1JNL6 S
M0MDP9 T
A0A653N397 S
A0A2S8GSU9 S
A0A097R891 S
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 S
A0A1B9JHS5 S
D3PE53 S
A0A9J9BAE8 L
Q2RM12 G
A0A3N0AQL8 N
C5KTM6 D
M1P5F0 L
I1YG38 D
A0A660CH85 N
A0A2N7L7C8 D
Q5KZZ9 S
M1NZT5 L
A0A225CMT8 S
A0A068NV61 M
H2CJI0 D
B0DU93 S
Q221S8 S
F4Y3C5 V
Q94CJ2 -
M0D3Q9 T
A0A3P2A7W8 S
C0GKN4 D
Q7T3R4 -
A0A562USB9 L
A2SS52 S
A0A211ZGL5 S
A0A4V3ALP8 S
A0A147GP06 S
H2IZ00 S
Q45HK8 S
A0A6C8LST1 S
A0A257T8W6 N
Q5P470 S
I5AZQ4 N
Q07UM1 A
E5B358 S
A0A1Y4L5P0 D
Q3AFY9 N
B0BZN3 V
A0A1Q2C7H7 N
A0A4R5U5V1 S
H6LKX6 D
A0A1Y0UZX2 A
F6BEI0 D
M9RKT6 L
A7SGD4 D
A0A257TE48 D
R1FI09 D
E4N1T5 M
U1PIR6 D
F2JYR9 A
Q84KJ7 N
A0A2S8FTB5 D
D2R647 D
G9Y5B0 S
A0A144NLT9 S
A0A5J6WQU1 L
D2R355 G
F3ZYD6 D
B0SL05 V
A0A5A7MAJ9 S
A0A977NL43 N
A0A433ZQ80 S
A0A1Y0V4A5 -
A0A1M7UEG2 N
G8R7U9 S
K1LDP0 I
B7G0Y4 D
A0A2W4ZXC0 S
B3PF77 M
Q2KZK9 S
Q18ES8 D
D3F545 N
B4S394 G
Q1Q357 D
Q9H310 -
D3PKL4 N
M5SY07 S
Q8RUT6 D
A7NKH2 D
Q1Q879 L
A0A1B9M5B8 S
A6LRS5 S
J2ZGN6 T
V5E0F3 S
A0A149RQX0 A
A0A165BP25 S
C0QSY0 N
B0XVV6 S
E0SD83 S
A8HSA2 D
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 S
Q0AT01 L
A4FMG0 N
C3YB73 D
A0A9P3CXY2 S
A0A0L8BVU4 S
A0A401WUW1 A
I4C9L2 S
Q8RUE9 -
F0JGZ1 A
A0A2I0UUY1 T
A0A542XGT4 N
G0JRH4 A
A2SPS8 S
A0A5M4AWD2 D
Q6QH01 D
D3F0Z1 N
A6XBM2 -
D6E7B3 N
Q13E03 S
A0A060URB8 A
A0A2T1N7R1 I
D6TCH6 -
B0CXH8 S
A3TVQ9 L
Q4WT12 S
C7QGX3 N
F0Y9X3 D
A0A7S0D560 S
A0A160KTE9 S
A0A2H1HV86 N
A0A251Y3N4 S
A0A419AVL2 S
A0A4Q2QWS1 S
C7Q1E4 N
A0A5C5TYS5 S
F2NNQ0 N
A0A2R4TRE0 S
K9YJQ3 V
D9QS43 D
A7SQ16 D
A1DG05 S
U1SIR9 H
C4Y298 S
A0A9W3LFI9 S
D3RMV7 S
F3QNA7 S
E4RTK5 S
C8XBX8 N
C0QTA4 N
E6VIW4 S
A0A2S6H643 S
Q46HB1 V
A0A2S5CTX8 T
A0A1T4SF40 A
K0K7J4 N
A0A1J5JH24 G
Q6LMI6 L
A0A9W5JBA9 S
A0A291PMC6 A
A0A4Y4DZN4 N
A0A2R4MBA2 S
R9PI53 L
A0A6H9GLV4 V
A0A7S4GND2 V
A0A6H9FPY5 V
A0A1G7DX68 S
A0A075WEB4 S
A0A140NHJ5 A
A0A1C6Z081 S
Q5FA36 S
Q0ACK1 L
A0A975GIX9 N
A0A323UE08 S
U7VB41 T
A0A063Y780 L
C5CIT6 -
A0A0A2VPU3 Q
F0RHS0 D
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 S
A0A0A2B651 V
A0A4R3A5P7 S
A0A2A7U6W1 S
Q2GX26 A
F5XN43 N
A0A0K2STH0 V
A0A1H1U2Q6 N
A7SED8 -
A0LV78 A
K5DBA0 D
B8IZX4 S
A8LKQ0 L
A0A5C6LWQ1 S

In [152]:
seqt = []

for i in t:
    print(i.id, i.seq)
    seqt.append(i.seq)

A0A858ZNJ3 A
A0A1H9M798 A
B0DY50 M
P69680 G
A0A3G9G4Q4 A
A0A149UP06 A
F2G6G4 S
A0A2M9D7S8 A
A0A034WGQ2 T
I0KDC6 A
F8D7H6 T
K9W4V5 T
Q466Y3 T
D2SE15 A
A0A377PBY1 G
B1JZ69 A
A0A2W5HTC3 A
A8G2S3 T
D5T4N9 A
Q2RWY7 L
A0A0E3R4G0 -
I4C9L0 A
D5VJ32 A
C0Z5S5 A
C1N6X9 T
J7ITF6 A
A0A068SVR1 A
A0A0D7F328 A
Q0G0A4 A
F0J3F9 V
Q0BQ69 A
F2YIC4 L
D4XLN6 A
A0A420WC79 S
A0A5C5TUT2 A
A0RUZ2 A
A0A0A2ZRL7 A
J4UGB7 A
E5Y678 A
A0A0D2KGN8 M
S5ABR8 S
A9DQM8 T
G5EB13 A
A0A2N6NEK4 A
C6DB68 A
Q81GN5 A
Q0F2M5 A
A0A0C6P439 A
B9SWW9 I
L8H5K0 L
Q9NIV0 M
C1N5A7 T
Q1JXS5 A
A0A1M6JKY3 A
F4D1J0 A
A0A257SYX3 V
V4RK08 S
G0V8D6 S
A0A7S4GMD8 T
B3QVV5 A
F2JZ83 A
A0A857DDJ7 A
A0A0S6UHP2 T
D5EP71 G
F4KY49 A
M5S9B4 T
A0A009PYN3 A
A0A3T0SZ22 A
A0A248LMH8 A
A0A6H9GEE4 T
A7HSP2 A
A0A7V8IKS6 A
T2JFS5 T
F6FRU9 A
A0A9E9L9J1 V
A0AIW5 A
A0A0E9NHV4 A
Q2N625 A
C8WSI9 A
A0A1H1BPD6 A
A0A176XNC5 A
A0A4V0XUI3 T
A7S3L2 T
M5U2P1 T
K9P5D1 A
Q0F2M7 V
A0A2R3IMJ8 A
Q2RVB5 A
A0A556RTU3 C
E0TGP9 S
B7G0Y1 T
A0A1G9P6Q0 S
D0LTW3 T
Q6BT62 I
Q2IK04 T
Q6BJI7 A
B7X047 A
A0A068NPW2 A
A0A399NT81 A
K0F9X7 A
A0A037ZMW1 S
A0A075JZ35 A
A0A369MHK2 A
A0A1B9JPL5 C
D8PD01 A
A0A2G5BI87 G
A0A2G5BGA9 A
A0A657K391 C
P69681 G
A0A4P6UIJ8 A
A0A0V8M0W6 A
A0A0H2XSU4 A
Q1Z695 A
A0A7Z0V0A4 A
K0ER80 A
A0A149UWF2 A
G0H0Z6 T
G0EFF3 A
C8WLL8 A
X5CNT2 I
A0A4Y1MSE7 A
H2CLF7 T
M4VEJ9 A
A0A4V2X6C2 A
A0A2K1RA77 I
A0A375YPN6 S
A0A7M6UUM4 L
A0A172YCA7 A
A0A918MJ52 T
A0A2S8QA29 A
A0A251XJT0 A
A0A0B4E6X7 S
A0A0K2STQ7 T
A1C5Z7 A
C9KKP2 A
A0A2Z4MD56 A
Q9VFA9 T
A0A502GPV4 A
I5C044 S
D2V6P8 L
D3RN22 A
Q97L80 G
A0A0D5YN10 A
A0A1I5GN22 A
A0A1Y5E8I7 S
B1Y8C9 C
M5SYZ1 T
Q6HM26 A
A0A379A0S9 S
A0A101DCS3 A
A0A1Y3U5V2 G
A0A202B535 A
F8E6R1 S
Q6ND36 A
A0A8H6K7L7 A
Q7NCB8 A
A0A369MRW6 A
C9RS76 T
A3U857 A
A0A127PIQ9 A
B8FGW0 A
A0A060JMP6 A
D5V7B3 N
A0A494JB70 A
A0A5M8QF12 A
A0A8G2F3G4 A
J7L3W8 A
G0JRG9 I
D3DJN2 A
A0A1Y2JH43 A
Q1L727 T
A0A7T2S0Z6 A
A0A315S845 A
A0A2S6H6B7 A
A0A1J5NTP7 A
A0A0E3QY86 A
A0A096EEV9 A
A0A380S5X4 T
B8ZYW3 T
A0A2S8GEJ5 T
A0A248TDF2 C
B2GFN1 A
U1PPI7 T
C7LW88 T
G3A431 A
A0A066ZTE4 S
L7CG99 T
S0ET45 A
A0A178TA08 A
H1XV27 T
A0A6M3ZJI1 A
U5DEY6 T
H6LFQ2 T
Q6CRN0 I
A0A4Q2EAG7 G
A0A1J5NNB8 T
E3I393 A
A0A243SC06 A
D4F313 A
W0F0I7 A
A9B874 T
A1D2Y5 A
T2J0N1 T
Q2FQT3 A
A0A075WG29 T
A0A979GQ79 A
A0A381CAY8 G
A0A2G3DSU6 T
A0A168EVK8 G
A0A094W9G3 A
A0A4R3NVT3 S
W0DYY3 S
G8JTW0 A
A0A4P6UIK6 A
I9P003 S
G2T1Y3 T
B8EMQ8 A
I6Z905 T
E0TCV4 S
A3XNG6 T
A0A087MGU4 A
A2BUP4 T
A0A562S8V2 A
A0A495DND0 A
A0A0S2FHD7 A
F3QPR6 A
A0A063Y394 S
F6G5I9 A
A0A323UDG5 A
A0A0G9HEC5 A
B8FDY8 A
Q5KPM5 A
A0A147EQL9 A
A0A854Q6X9 V
C3X1J1 V
A0A5B2V3B9 A
A0A258FS85 A
A0A7T2W1B3 A
A0A060UN76 A
G0JRQ3 A
D5UD26 A
G2ZN72 A
A0AA46Q839 A
A5UJR1 A
L1INN6 T
C1F584 T
C5LAG4 T
A0A2A2MCP3 A
B1Y6V4 T
A0A1G6ABK5 A
A0A6A1TYJ4 A
A0A2T4UWF1 A
V4AP67 T
A0A173R3W6 A
C7NND3 T
B0DFJ4 A
A0A3E2VY88 T
R1EDV9 T
J1L5M8 A
D7G265 T
Q8ERT9 T
I4D6Z9 T
A0A4R6DFU8 A
A0A060URC3 I
D2BIB2 A
F5ISF6 A
A5CRL2 A
A0A6G9XJV9 A
Q59UP8 I
A0A6N4SPH9 T
I0HGY4 A
X5DX97 T
L1J6I4 A
I1DSU5 S
B9L7N1 A
Q1Z4I4 S
Q21CP1 A
A0A165MFD1 T
V4CRP5 T
Q7S5K0 M
A0A071MMV1 A
A0A149RYW7 A
A0A7G5EC77 A
A0A1W2GZ82 T
A0A7U3XVQ4 A
A0A071M4L5 A
U5C2K4 T
A0A248LNW8 A
L8H844 S
A0A149V596 A
S9QZ09 A
B1ZSW9 A
D2BUJ8 G
A0A9Q8L398 A
M5S735 A
Q6ARH0 S
K6W5X0 A
G0JRG6 I
A0A6H9FYW4 A
A0A0S4WFM4 A
A0A101HKN9 T
Q9REX3 T
F0S3Z6 A
A8NAG3 T
C6LBD3 T
A0A149U2G9 A
V4REY8 S
A0A0H3H4I7 G
A8N2H6 A
S0APH6 I
A0A017SYR8 A
A0A1B9MZ78 C
E4T3F3 -
D7E934 T
A0A0M3AB44 A
A9WHW6 T
A0A5M4AUM9 A
A0A1X4GBG2 T
I4D1H5 A
A0A0E3QYF3 T
B0CQX4 S
A0A378YR15 A
A0A495D4X4 S
A0A076PL76 A
Q1YDY7 A
A0A3E2UCG9 T
A0A2K3DPU7 -
A0A3R9Q7C4 A
V5U2Z4 G
K9P718 T
M1V7W3 S
Q6LKC8 A
E5Y789 A
J9Z839 I
A0A1G7VM92 G
K9Z0D3 S
A0A482TED1 T
R1EGK6 T
J1ASR8 A
A0A7U4E420 A
K9YR86 T
A8PXT8 V
A0A0U1NJW3 S
B8FL88 T
A2CCK1 T
D6TFE1 T
A0A2H4U5R1 A
I2GD40 A
A0A060HFT5 A
B1Y842 A
A0A0X8NXA9 A
A0A0A2A5X1 T
A0A318FY98 G
Q7V4T8 T
A0A1A0DHK0 V
C1A872 A
A0A395VB65 T
A7MFK3 G
J4KM12 A
A1SY01 T
A0A1H4DJ49 S
A0A9R0NTP8 A
A3PAY4 T
B4CV94 A
A2C095 T
Q2HD43 A
A0A836M2B6 A
H6RWK9 A
A0A087EQK8 A
A0A1I0AQM4 L
L7CG11 A
A0A248LNK5 A
B7FTM9 T
L0K9M1 T
I4D6Z7 A
A0A2K1RA81 I
Q2WBF7 A
A0A1B9BUU6 I
A0A2S0JW39 T
A0A2S5YID7 A
B3PIH2 A
U3P8G1 A
C9R9J0 A
A8AC17 A
F0YLV7 T
A0A1D3GAE9 A
C1MHX0 A
A0A1H4KAQ7 S
A0A2T4XZC1 G
A1B3N0 A
C7LW87 A
A1SZ12 S
A0A2T2Y0D5 G
A0A1H8D0R8 L
A0A2S5V2F6 A
G3IYW2 A
F5L8M7 T
C7BJG7 A
E4U5Z1 A
A0A1B9K8L2 C
A0A2S5WMT7 A
A0A0D2UPA8 A
A0A161SKF4 A
B4D7W2 G
A0A1H3WA00 G
C1D6X6 A
A0A4D6KHD1 T
Q488X2 S
A9V5W4 L
A0A5M4ATH9 A
E4TRS4 T
A0A011U1K7 A
C7R314 A
A0A077EFU9 A
A0A0A2A0Y9 T
A0A0D8BQX6 A
A0A0L0S493 A
A0A328Q6M1 A
A0A016XCG9 A
B7FSA7 T
G0AFH4 A
A0A177W826 A
A0A2S8GF54 T
Q1YDY8 S
Q5QVH2 S
A3ZT81 T
A0AA35XZV0 A
F4H924 A
K0NJH2 T
A0A1V3SSW1 A
F2AUF4 T
A6DN47 S
W8KM07 S
A0A1X3RP39 G
A0A7S0KKL8 T
A0A318QZ80 T
K8VZC6 A
A0A1B9JZS5 C
A0A2S6GKN5 A
A0A4R2Z2K6 A
H1YCC3 A
E1QIU3 T
A0A8H6MPB9 A
A0A369N7Y3 A
T2IEJ2 T
H5UND3 A
Q1PX09 T
A0A149TSA9 A
F2NGJ8 A
A0A0E3SHQ9 T
Q5FLR6 A
S0EUS1 Y
A0A369M386 A
W0DZS7 A
A8MCL4 A
V3ZVE4 T
O26757 A
A0A317FZW2 T
A0A085GI50 G
A1ZGK6 T
G0IYI2 T
A7S731 T
A0A1U9YY82 S
A0A328EMN2 A
A0A8E2UDJ3 A
A0A2S5WUP6 A
A0A8H7P8U1 M
A0A257T7G4 I
B3MX93 T
A0A1G5W0P2 A
D4H2Y7 T
A0A4P8HC89 A
Q7T070 L
F7NPQ3 A
B9SA70 I
Q9M6N7 I
I7ZHW3 A
F4XTK4 T
A4G1J2 A
G7WFX4 A
B8JBH5 A
D9QPC8 A
A0A4R7GKA0 A
R9PMC6 A
A0A0E3LMT4 -
A0A511NGC7 A
E4NS62 T
E4T3F7 A
M0D580 T
J7J5E7 A
B1XZU2 T
A0A366IE34 A
A0A6U2BIY7 T
Q9QXP0 C
A0A424WAH3 A
A0A410K1J5 T
L1IHZ8 A
I8TC71 A
A0A7U8C744 S
A8M670 A
A0A0S4VNK2 A
Q2SIR0 A
A0A5C4RNH5 A
A0A3E0X011 S
A0A0E3SP24 A
E1IF27 A
Q2YBP7 L
A0A2S5WZU0 A
A0A172YBR4 S
A0A0K2STK6 T
A0A2N6JV02 T
F0S0G1 A
A0A1C7EL50 T
Q18PF5 L
A0A1I0C958 T
A0AA35XVN2 A
L8GGA0 A
Q3AP28 A
D0MFE9 A
J9VXX9 V
A0A166IS52 T
F0J7D3 I
W7QG13 S
A4BMY5 A
A6LV49 A
Q1H483 A
A6M3G0 A
E4T0A4 A
A0A3E2UHE6 T
A0A174SD65 A
A0A855EH99 G
C3YB74 T
A0A074KZD8 T
J0S2I0 T
K9WSX4 T
E8RLT5 A
Q2FS34 A
Q3Z7F9 A
Q2S8H9 S
A0A060HN92 L
E6ME92 A
A0A172RYW3 A
L0FU80 T
C8WZE0 T
A0A2S8F4W0 T
A0A2C6C0X3 G
F3ZVV4 A
A0A7R6PER3 S
A0A495WJM6 S
A0A0B4DUR9 S
A0A251YU48 A
A5D4I5 A
A0A2X2C038 A
A0A2A2M8K7 G
D3FBG3 A
A0A2V4EA49 C
D0MFE8 T
Q3B6Q2 A
A0A1B9KID3 C
A0A9J9ES23 A
A0A3N2SFS2 G
Q0VLH1 S
A0A1U9Z147 A
Q0G2T1 S
A6GJF5 T
A0A059XXR1 I
A0A5J6WPP9 A
P41948 A
L1IUV5 A
A0A2W0GQV0 G
Q1K433 T
A0A4Y7XC43 A
D5AU98 A
E1QFA8 A
A0A075WBP9 A
Q0BWD0 S
A0A1Y0HX98 A
A0A098S5Y7 T
Q0I445 A
A0A1E5BXA4 S
A0A2C9CK98 T
G4H971 A
A0A1I0BYN1 A
A0A330GB00 G
A0A2S8FR08 A
Q84KJ6 I
A0A2S5WGI8 A
M2ALH9 T
A0A2K3DQF8 T
A0A8G2IZM3 G
F5Y3C1 S
A0A370FPU0 C
F5RGM7 A
A0A4R4K1P9 A
R8VWI7 T
A0A0A2AMW2 T
Q7Z1M1 T
A0A414NWT8 A
A0A0P6VSR8 A
A0A0L0TDW1 A
U3PCH5 S
W7QGE0 A
C5BWX7 A
A0A1B9M1A9 C
B8GGC3 A
D6SPD1 S
A0A0H3DR67 A
A0A4R7VEK0 A
G4R7P1 S
A0A1M5ZVP9 T
A0A2S5Y0D3 A
I0ICG0 T
D0L8H3 A
A0A1B9LFW3 C
Q6ND34 A
A0A6H9GWG4 T
Q5UZ98 T
A0A2S0P9T4 A
H2CDR5 T
T2KGT3 T
A0A088E6Q7 G
A0A258HS77 A
E1V4T3 S
B7GKP4 A
Q9QUT0 L
I3Z3H7 T
G7WCB6 A
A0A1Y6GLJ1 G
A0A0S2DQB6 A
Q6CRN1 I
A0A401X433 A
A7HT14 T
A0A009TDB1 A
D4XSW0 A
B0SRS8 T
A0A149QSR6 A
B1Y0E5 A
Q7UGU7 T
A0A2S0Q8P1 T
F0ZPL3 T
A0A2T0GTU1 A
I4CCD1 A
A0A9Q6P4A5 A
A0A418VIJ8 A
C1MX19 A
A0A1B9BUZ8 A
K9W6F3 A
Q1K8A3 A
L8GFX3 A
A0A1G6ABL9 A
A0A087L0B9 A
A0A073CP02 T
A0A0A1ZJU5 T
A0A258HPP1 A
A0A149QAW7 A
D2V6Q5 T
A0A1X4G8K1 A
A0A067Z3S3 A
A0A8F5ZDT8 A
A0A854QN45 A
A0A2N7LCD7 S
G7WFX2 T
A0A7S4GNJ2 T
A4G0C5 T
A6VE60 A
A0A1S1HM83 A
A0A037ZJY5 A
N1WR17 T
Q2W5V2 A
A1VIM5 S
A0A1Y5E3E3 V
A0A1T4SFK4 A
A7RNC3 T
M7XJ51 T
A0A399T909 A
A0A2N6P374 A
H8L2Q4 A
D5EP68 T
E6SF19 A
A0A1T4SFY6 A
D3LBI0 A
E6W5C1 S
Q0VPH4 T
K9WT03 A
L0KW14 A
A0A4R8H081 T
A0A1B9N3H7 C
B0RC35 A
A0A420KGW4 A
A0A4R3NLV5 A
Q47K18 G
Q21P82 S
M1WRK6 A
A0A290XBB5 A
A0A6T9XUR2 S
A0A1J1JH03 T
I3R0S7 T
A9UR54 T
A0A1G7H8X3 A
A0A8G2F718 T
Q1H0G2 T
D0LAL7 A
C7LQR9 T
A0A1G5PWV0 A
K1K628 G
B9SXC7 I
G7WA28 A
Q1IWN6 A
H6LKH9 A
A0A1H7CU41 A
G8JUJ2 I
A0A081N2G5 S
A0A074ME37 A
Q0VQH6 A
C8XB51 A
A1VIG8 T
Q8GQS1 A
A0A1I7FBM5 L
A0A1M6ZMI3 T
A0A482PLH3 G
A0RXK8 A
D0KXQ0 A
Q8JI14 L
A0A7T4WEP4 I
A0A4R3ZNW3 A
A0A074KY88 T
A0A6M3ZKU5 A
M1SJL5 A
A0A1W9KSU5 T
E3GI40 A
A0A369NYJ2 A
A0AA92K392 A
O04161 G
A9BQZ4 A
A0A6N2Z556 T
A0A8H6NAG3 A
A0A2T9X1V4 V
Q2J376 A
A0A0F5EZP7 A
A0A7G5DK18 A
M9YAI9 A
D2ZRW2 A
G7UUY6 A
A0A8H4GS02 A
A0A2T5IHP0 L
A0A165MAC2 A
A0A7S4LPS8 T
A0A075JIN0 A
C8X554 A
B8FZP7 A
Q5KAF6 V
A0A427KNL6 G
A0A7G5DPV0 A
Q22947 L
A0A1S1HRJ0 A
A0A3N1VXY4 G
A0A2S7YPJ9 A
I0JI83 T
A0A7U3YMN6 A
Q9BLG3 T
A0A1H9RTW8 A
A0A1I4W3A0 A
A0A0B4M163 L
U2EN72 S
A0A2W5VAZ2 A
E4YA63 T
D5ELM4 T
M9RJS5 A
A0A2G3E8V2 T
Q5FSX6 A
I0HKQ8 G
A0A833H2R7 T
B8ENL9 A
B3DUX7 A
A0A1D8UWJ6 A
D5E995 T
A0A7U8C2Y6 A
L0KGR8 A
B0VMH1 A
P40260 S
L0JT30 T
C1GR74 A
A0A423Y4I6 G
A0A4P7UHQ5 A
A0A8E2R1Y5 A
I5BYV5 T
A0A6B8N021 G
A0A7G5DPV1 S
A0A2G5RQK9 A
A0A5M4B0G1 A
A0A6S5K4J1 G
C1D4X0 A
A1SVA8 A
H1YF74 T
A0A8B4RWH8 A
A0A0A0D6K5 A
A0A0A2BBY0 T
A0A089ZBW5 A
A0A068TC78 A
Q46G49 A
A1CQ21 A
A0A1G6ABX1 S
E1SLM7 S
K5CFE5 A
Q2YLQ6 A
Q0G2V0 S
A4ABK3 S
A0A9Q5QVI9 A
A0A4Q7Y9I7 A
A9HMD6 A
K9YN27 T
Q9UBD6 C
D9SI59 A
Q8I0L6 M
A0A142VAD6 A
G3IYW0 A
A0A062IU58 A
R1D1H4 T
A0A366XFS8 A
A0A7S4GNF3 T
F0J6E8 A
A0A7U4DN04 A
V4RHR4 S
F7ZJM0 T
A0A2S5XAB8 A
U5C4L4 T
Q21J04 A
A0A142NNN1 A
H1Y7T6 A
F5R974 A
B0DU91 G
A2BP62 T
A7HSN9 A
A0A377I7W9 A
D2RU19 T
G7WJN0 T
E2SD33 A
A0A0D7F2Y9 A
A0AA92EGF5 A
A0A9E9LXV9 A
A4BEP1 A
A0A0E3WZH5 -
F7ZEU9 S
A5E3X2 I
A0A0A3XTJ3 A
A0A830ZZN8 G
A0A1S8D478 A
J7IVQ1 T
A0A2U1SS17 A
S3K1S2 G
C6XKC2 S
A0A2S7YIM5 A
K2IMJ7 S
Q5P1S8 A
A0A7T5BFQ2 A
A0A556SRH6 C
A8P923 A
A0A7G5DKA9 T
L8JUH3 T
A0A0D2LEF5 G
A0A258FTB0 A
A0A5P9P1L2 T
M8E0R3 A
A0A6J5IRX5 A
W5WIX6 A
Q82X47 L
I4DBY0 A
A0A6F8TLE9 A
A0A1G7UZX2 A
A0A6P4JM51 T
G0J614 T
U2WTW8 A
A0A642KQG8 T
Q1AUG3 A
A0A6G9Y3Q0 A
B8J5X4 T
M7NFH3 T
A0A0E3R6S1 A
Q2IHY5 A
A7I8Z2 A
L1IYP4 A
B4HDZ9 T
A0A366WYI9 S
E4TJ50 A
A0A7S0ILH2 A
A4BAE1 S
B3QRJ4 A
A0A5C5BWI6 A
Q7NQY2 A
A0A091AXI3 A
Q1QSQ2 S
R4FZE3 A
A0A2N0MZ27 A
A9BTK1 A
A0A242NIL1 C
G0LFE3 T
A0A1B9NQ91 C
A0A5M5PZE2 T
A0A0D2NYP3 A
D9QPE5 A
I5B3H0 T
L1IYW7 A
C6WEW7 A
B7FW68 T
F4GED5 A
A0A4R8GSH7 A
A0A1W2H3F0 T
A0A3E2T713 T
A0A0H3KTD3 G
A0A1Y4LM49 T
G2PRJ6 T
A0A0X8X7Y7 S
K8EJ02 A
A0A1L3F1X5 A
G8TK77 G
A0A855F5Y8 G
A0A975BTN0 A
A0A562RGZ4 T
G5EB09 A
A0A833LX85 T
U1H1F7 A
K8W1E2 A
E3HJW8 A
Q7SEH0 A
Q47X17 V
B0DXT9 G
A0A3G9G2C9 A
Q95P70 L
A0A837C6X5 A
Q89WR5 A
A6DUG4 S
D7UQE2 L
A0A2I1M481 A
A0A0T7GZ59 A
O66395 A
J3EXK0 T
A0A1B9MYL7 C
K9U8C7 T
E2SD44 A
H6LKH6 A
Q605Y6 A
A0A9Q9D9I3 A
A0A6N2TIA4 T
A0A1E3PQH0 T
A4CMI3 T
Q1K0H9 S
A0A0S6UEK9 A
A0A0H3LUA3 A
B9LU00 T
A9BIZ7 T
A0A7H8UK07 G
E3H8C9 T
M2A398 A
Q1QS12 A
G0VI62 I
A0A1Z3MS36 G
A0A0B5FNH4 S
D9SI36 A
A0A410JZR4 A
F7ZJZ1 S
F0ZCX7 M
W0DZX1 A
A0A4R3ZZ35 A
A0A317G0I6 T
Q0ARJ4 A
A7I8Z4 T
T2KJ59 T
I3C0V3 T
E3H8A6 T
B2IJT1 A
A0A2G6JLT9 A
A3ZZL7 A
A0A2T0XPP2 T
Q31CR9 T
A0A1R1IDV3 A
K2JVF8 S
V5BYZ7 A
D8J4C6 T
D4H5F9 T
K9ZG59 A
A0AA86YS65 A
Q608B6 A
A0A562BXM4 A
A0A401WXG0 V
A0A857DMN9 A
A0A1X6N3Q5 M
A0A173R3X4 T
Q63EK5 A
K9ZLY2 T
A0A533I6R2 A
I0WJ97 T
K0N2R5 A
M0J579 T
B8GGC1 A
A0A6H9GFU4 A
C6CBB1 G
A0A510HHK8 A
A0A1B9MBX6 C
A0A9Y2AG30 A
E8RSE4 A
F2B2B8 A
Q7UYZ3 A
I1YJH7 S
A0A853MG28 T
A0A0L0STS6 A
A0A251XU71 A
Q60BI2 A
A0A829X098 A
F3KUN4 A
Q60C43 T
A0A0T7FAP8 A
A0A3E2TW06 T
W0E077 T
A0KPE9 G
R7PZ71 A
A0A0A1ZMZ9 T
A0AA40J491 A
D3S2L0 A
A0A373FQ71 A
A0A0A2C6L1 T
Q7W7D3 A
A0A165K0X5 T
A0A2S5X482 A
R9GM11 G
Q0G0A3 S
D4GLQ6 G
E7RJZ0 T
F8IJE0 A
A0A1V2XMU9 A
Q7TNN9 C
A0A1G5RZU9 T
A0A2N6K4Y5 A
B0SLB7 A
A0A251YFS0 A
B9WDK0 A
Q7N0M6 A
A0A0M2LU39 S
F4B548 V
D6Z5V9 T
A0A4R2M206 G
A0A1E2SKM1 S
A0A127JTU2 A
A0A212AV03 A
G4QHD2 T
A0A021VMC6 A
A0A2J7TJ33 A
G7WDB5 T
Q6BK68 C
Q1K3N8 T
A0AA91Q161 A
A0NJ07 A
A0A316BQ38 A
A0A377PLP5 G
W7QGM4 T
A0A015YIP3 T
A0A060UWC8 I
A0A1I4ZIZ6 A
A0A264VQM8 A
A9AUR8 A
A0A1W5PRD1 L
A0A0E3BR91 A
A0A1B0ZRL8 S
B9ACS5 A
Q92BJ7 A
F2JTN3 S
A1AVV2 A
D2Q0J8 A
A0A3S9N9F3 A
A8ZQD5 T
C3X831 A
A0A1M6BPM0 A
A0A8F5VN39 A
A0A1E5C7W4 A
A0A2S5WV24 A
A0A833GZR2 T
C7M2A9 L
A6W7U2 A
W0JIB3 T
Q07UM3 A
A0A066ZRQ5 T
S0G181 T
D3PAH1 A
Q4WHC6 A
A0AA94HTL8 A
D5ASL9 A
A0A4U1JNL6 A
M0MDP9 T
A0A653N397 A
A0A2S8GSU9 A
A0A097R891 G
A0A8H7U3I1 A
A0A1H1MB73 A
A0A016XDZ5 A
A0A1B9JHS5 C
D3PE53 A
A0A9J9BAE8 S
Q2RM12 A
A0A3N0AQL8 A
C5KTM6 T
M1P5F0 S
I1YG38 A
A0A660CH85 A
A0A2N7L7C8 A
Q5KZZ9 A
M1NZT5 S
A0A225CMT8 A
A0A068NV61 T
H2CJI0 T
B0DU93 G
Q221S8 T
F4Y3C5 T
Q94CJ2 M
M0D3Q9 T
A0A3P2A7W8 A
C0GKN4 T
Q7T3R4 L
A0A562USB9 S
A2SS52 A
A0A211ZGL5 A
A0A4V3ALP8 A
A0A147GP06 C
H2IZ00 A
Q45HK8 A
A0A6C8LST1 G
A0A257T8W6 I
Q5P470 A
I5AZQ4 A
Q07UM1 A
E5B358 G
A0A1Y4L5P0 T
Q3AFY9 A
B0BZN3 T
A0A1Q2C7H7 A
A0A4R5U5V1 A
H6LKX6 T
A0A1Y0UZX2 A
F6BEI0 T
M9RKT6 S
A7SGD4 T
A0A257TE48 A
R1FI09 T
E4N1T5 A
U1PIR6 T
F2JYR9 S
Q84KJ7 V
A0A2S8FTB5 T
D2R647 T
G9Y5B0 G
A0A144NLT9 G
A0A5J6WQU1 S
D2R355 A
F3ZYD6 T
B0SL05 T
A0A5A7MAJ9 A
A0A977NL43 A
A0A433ZQ80 A
A0A1Y0V4A5 V
A0A1M7UEG2 A
G8R7U9 A
K1LDP0 T
B7G0Y4 T
A0A2W4ZXC0 A
B3PF77 S
Q2KZK9 A
Q18ES8 T
D3F545 A
B4S394 A
Q1Q357 T
Q9H310 L
D3PKL4 A
M5SY07 A
Q8RUT6 T
A7NKH2 T
Q1Q879 S
A0A1B9M5B8 C
A6LRS5 A
J2ZGN6 T
V5E0F3 A
A0A149RQX0 A
A0A165BP25 G
C0QSY0 A
B0XVV6 A
E0SD83 G
A8HSA2 T
A0A1E3PSK5 A
A5DYQ2 A
A0A4U1K1W1 A
Q0AT01 S
A4FMG0 A
C3YB73 T
A0A9P3CXY2 A
A0A0L8BVU4 A
A0A401WUW1 A
I4C9L2 A
Q8RUE9 M
F0JGZ1 A
A0A2I0UUY1 T
A0A542XGT4 A
G0JRH4 A
A2SPS8 A
A0A5M4AWD2 T
Q6QH01 T
D3F0Z1 A
A6XBM2 L
D6E7B3 A
Q13E03 A
A0A060URB8 A
A0A2T1N7R1 T
D6TCH6 A
B0CXH8 M
A3TVQ9 S
Q4WT12 A
C7QGX3 A
F0Y9X3 T
A0A7S0D560 A
A0A160KTE9 A
A0A2H1HV86 A
A0A251Y3N4 A
A0A419AVL2 A
A0A4Q2QWS1 G
C7Q1E4 A
A0A5C5TYS5 A
F2NNQ0 A
A0A2R4TRE0 G
K9YJQ3 T
D9QS43 T
A7SQ16 T
A1DG05 A
U1SIR9 A
C4Y298 A
A0A9W3LFI9 G
D3RMV7 A
F3QNA7 A
E4RTK5 A
C8XBX8 A
C0QTA4 A
E6VIW4 A
A0A2S6H643 A
Q46HB1 T
A0A2S5CTX8 T
A0A1T4SF40 A
K0K7J4 A
A0A1J5JH24 A
Q6LMI6 S
A0A9W5JBA9 G
A0A291PMC6 A
A0A4Y4DZN4 A
A0A2R4MBA2 A
R9PI53 S
A0A6H9GLV4 T
A0A7S4GND2 T
A0A6H9FPY5 T
A0A1G7DX68 A
A0A075WEB4 A
A0A140NHJ5 A
A0A1C6Z081 G
Q5FA36 A
Q0ACK1 S
A0A975GIX9 A
A0A323UE08 A
U7VB41 P
A0A063Y780 S
C5CIT6 A
A0A0A2VPU3 A
F0RHS0 T
A0A2S5WX34 A
C1G973 A
A0A2S6GKF6 A
A0A0A2B651 T
A0A4R3A5P7 A
A0A2A7U6W1 A
Q2GX26 A
F5XN43 A
A0A0K2STH0 T
A0A1H1U2Q6 A
A7SED8 L
A0LV78 A
K5DBA0 T
B8IZX4 A
A8LKQ0 S
A0A5C6LWQ1 A

In [153]:
seqf1 = []

for i in f1:
    print(i.id, i.seq)
    seqf1.append(i.seq)

A0A858ZNJ3 F
A0A1H9M798 F
B0DY50 F
P69680 F
A0A3G9G4Q4 F
A0A149UP06 F
F2G6G4 F
A0A2M9D7S8 F
A0A034WGQ2 F
I0KDC6 F
F8D7H6 F
K9W4V5 F
Q466Y3 F
D2SE15 F
A0A377PBY1 F
B1JZ69 F
A0A2W5HTC3 F
A8G2S3 F
D5T4N9 F
Q2RWY7 F
A0A0E3R4G0 F
I4C9L0 F
D5VJ32 F
C0Z5S5 F
C1N6X9 F
J7ITF6 F
A0A068SVR1 F
A0A0D7F328 F
Q0G0A4 F
F0J3F9 F
Q0BQ69 F
F2YIC4 F
D4XLN6 F
A0A420WC79 F
A0A5C5TUT2 F
A0RUZ2 F
A0A0A2ZRL7 F
J4UGB7 F
E5Y678 F
A0A0D2KGN8 F
S5ABR8 F
A9DQM8 F
G5EB13 F
A0A2N6NEK4 F
C6DB68 F
Q81GN5 F
Q0F2M5 F
A0A0C6P439 F
B9SWW9 F
L8H5K0 F
Q9NIV0 F
C1N5A7 F
Q1JXS5 F
A0A1M6JKY3 F
F4D1J0 F
A0A257SYX3 F
V4RK08 F
G0V8D6 F
A0A7S4GMD8 F
B3QVV5 F
F2JZ83 F
A0A857DDJ7 F
A0A0S6UHP2 F
D5EP71 F
F4KY49 F
M5S9B4 F
A0A009PYN3 F
A0A3T0SZ22 F
A0A248LMH8 F
A0A6H9GEE4 F
A7HSP2 F
A0A7V8IKS6 F
T2JFS5 F
F6FRU9 F
A0A9E9L9J1 F
A0AIW5 F
A0A0E9NHV4 F
Q2N625 F
C8WSI9 F
A0A1H1BPD6 F
A0A176XNC5 F
A0A4V0XUI3 F
A7S3L2 F
M5U2P1 F
K9P5D1 F
Q0F2M7 F
A0A2R3IMJ8 F
Q2RVB5 F
A0A556RTU3 F
E0TGP9 F
B7G0Y1 F
A0A1G9P6Q0 F
D0LTW3 F
Q6BT62 F
Q2IK04 F
Q6BJI7 F
B7X047 F
A0A068NPW2 F
A0A399NT81 F
K0F9X7 F
A0A037ZMW1 F
A0A075JZ35 F
A0A369MHK2 F
A0A1B9JPL5 F
D8PD01 F
A0A2G5BI87 F
A0A2G5BGA9 F
A0A657K391 F
P69681 F
A0A4P6UIJ8 F
A0A0V8M0W6 F
A0A0H2XSU4 F
Q1Z695 F
A0A7Z0V0A4 F
K0ER80 F
A0A149UWF2 F
G0H0Z6 F
G0EFF3 F
C8WLL8 F
X5CNT2 F
A0A4Y1MSE7 F
H2CLF7 F
M4VEJ9 F
A0A4V2X6C2 F
A0A2K1RA77 F
A0A375YPN6 F
A0A7M6UUM4 V
A0A172YCA7 F
A0A918MJ52 F
A0A2S8QA29 F
A0A251XJT0 F
A0A0B4E6X7 F
A0A0K2STQ7 F
A1C5Z7 F
C9KKP2 F
A0A2Z4MD56 F
Q9VFA9 F
A0A502GPV4 F
I5C044 F
D2V6P8 F
D3RN22 F
Q97L80 F
A0A0D5YN10 F
A0A1I5GN22 F
A0A1Y5E8I7 F
B1Y8C9 F
M5SYZ1 F
Q6HM26 F
A0A379A0S9 F
A0A101DCS3 F
A0A1Y3U5V2 F
A0A202B535 F
F8E6R1 F
Q6ND36 F
A0A8H6K7L7 F
Q7NCB8 F
A0A369MRW6 F
C9RS76 F
A3U857 F
A0A127PIQ9 F
B8FGW0 F
A0A060JMP6 F
D5V7B3 F
A0A494JB70 F
A0A5M8QF12 F
A0A8G2F3G4 F
J7L3W8 F
G0JRG9 F
D3DJN2 F
A0A1Y2JH43 F
Q1L727 Y
A0A7T2S0Z6 F
A0A315S845 F
A0A2S6H6B7 F
A0A1J5NTP7 F
A0A0E3QY86 F
A0A096EEV9 F
A0A380S5X4 F
B8ZYW3 F
A0A2S8GEJ5 F
A0A248TDF2 F
B2GFN1 F
U1PPI7 F
C7LW88 F
G3A431 F
A0A066ZTE4 F
L7CG99 F
S0ET45 F
A0A178TA08 F
H1XV27 F
A0A6M3ZJI1 F
U5DEY6 F
H6LFQ2 F
Q6CRN0 F
A0A4Q2EAG7 F
A0A1J5NNB8 F
E3I393 F
A0A243SC06 F
D4F313 F
W0F0I7 F
A9B874 F
A1D2Y5 F
T2J0N1 F
Q2FQT3 F
A0A075WG29 F
A0A979GQ79 F
A0A381CAY8 F
A0A2G3DSU6 F
A0A168EVK8 F
A0A094W9G3 F
A0A4R3NVT3 F
W0DYY3 F
G8JTW0 F
A0A4P6UIK6 F
I9P003 F
G2T1Y3 F
B8EMQ8 F
I6Z905 F
E0TCV4 F
A3XNG6 F
A0A087MGU4 F
A2BUP4 F
A0A562S8V2 F
A0A495DND0 F
A0A0S2FHD7 F
F3QPR6 F
A0A063Y394 F
F6G5I9 F
A0A323UDG5 F
A0A0G9HEC5 F
B8FDY8 F
Q5KPM5 F
A0A147EQL9 F
A0A854Q6X9 F
C3X1J1 F
A0A5B2V3B9 F
A0A258FS85 F
A0A7T2W1B3 F
A0A060UN76 F
G0JRQ3 F
D5UD26 F
G2ZN72 F
A0AA46Q839 F
A5UJR1 F
L1INN6 F
C1F584 F
C5LAG4 F
A0A2A2MCP3 F
B1Y6V4 F
A0A1G6ABK5 F
A0A6A1TYJ4 F
A0A2T4UWF1 F
V4AP67 F
A0A173R3W6 F
C7NND3 F
B0DFJ4 F
A0A3E2VY88 F
R1EDV9 F
J1L5M8 F
D7G265 F
Q8ERT9 F
I4D6Z9 F
A0A4R6DFU8 F
A0A060URC3 F
D2BIB2 F
F5ISF6 F
A5CRL2 F
A0A6G9XJV9 F
Q59UP8 F
A0A6N4SPH9 F
I0HGY4 F
X5DX97 F
L1J6I4 F
I1DSU5 F
B9L7N1 F
Q1Z4I4 F
Q21CP1 F
A0A165MFD1 F
V4CRP5 F
Q7S5K0 F
A0A071MMV1 F
A0A149RYW7 F
A0A7G5EC77 F
A0A1W2GZ82 F
A0A7U3XVQ4 F
A0A071M4L5 F
U5C2K4 F
A0A248LNW8 F
L8H844 F
A0A149V596 F
S9QZ09 F
B1ZSW9 F
D2BUJ8 F
A0A9Q8L398 F
M5S735 F
Q6ARH0 F
K6W5X0 F
G0JRG6 F
A0A6H9FYW4 F
A0A0S4WFM4 F
A0A101HKN9 F
Q9REX3 F
F0S3Z6 F
A8NAG3 F
C6LBD3 F
A0A149U2G9 F
V4REY8 F
A0A0H3H4I7 F
A8N2H6 F
S0APH6 F
A0A017SYR8 F
A0A1B9MZ78 F
E4T3F3 F
D7E934 F
A0A0M3AB44 F
A9WHW6 F
A0A5M4AUM9 F
A0A1X4GBG2 F
I4D1H5 F
A0A0E3QYF3 F
B0CQX4 F
A0A378YR15 F
A0A495D4X4 F
A0A076PL76 F
Q1YDY7 F
A0A3E2UCG9 F
A0A2K3DPU7 F
A0A3R9Q7C4 F
V5U2Z4 F
K9P718 F
M1V7W3 F
Q6LKC8 F
E5Y789 F
J9Z839 F
A0A1G7VM92 F
K9Z0D3 F
A0A482TED1 F
R1EGK6 F
J1ASR8 F
A0A7U4E420 F
K9YR86 F
A8PXT8 F
A0A0U1NJW3 F
B8FL88 F
A2CCK1 F
D6TFE1 F
A0A2H4U5R1 F
I2GD40 F
A0A060HFT5 F
B1Y842 F
A0A0X8NXA9 F
A0A0A2A5X1 F
A0A318FY98 F
Q7V4T8 F
A0A1A0DHK0 F
C1A872 F
A0A395VB65 F
A7MFK3 F
J4KM12 F
A1SY01 F
A0A1H4DJ49 F
A0A9R0NTP8 F
A3PAY4 F
B4CV94 F
A2C095 F
Q2HD43 F
A0A836M2B6 F
H6RWK9 F
A0A087EQK8 F
A0A1I0AQM4 F
L7CG11 F
A0A248LNK5 F
B7FTM9 F
L0K9M1 F
I4D6Z7 F
A0A2K1RA81 F
Q2WBF7 F
A0A1B9BUU6 F
A0A2S0JW39 F
A0A2S5YID7 F
B3PIH2 F
U3P8G1 F
C9R9J0 F
A8AC17 F
F0YLV7 F
A0A1D3GAE9 F
C1MHX0 F
A0A1H4KAQ7 F
A0A2T4XZC1 F
A1B3N0 F
C7LW87 F
A1SZ12 F
A0A2T2Y0D5 F
A0A1H8D0R8 F
A0A2S5V2F6 F
G3IYW2 F
F5L8M7 F
C7BJG7 F
E4U5Z1 F
A0A1B9K8L2 F
A0A2S5WMT7 F
A0A0D2UPA8 F
A0A161SKF4 F
B4D7W2 F
A0A1H3WA00 F
C1D6X6 F
A0A4D6KHD1 F
Q488X2 F
A9V5W4 F
A0A5M4ATH9 F
E4TRS4 F
A0A011U1K7 F
C7R314 F
A0A077EFU9 F
A0A0A2A0Y9 F
A0A0D8BQX6 F
A0A0L0S493 F
A0A328Q6M1 F
A0A016XCG9 F
B7FSA7 F
G0AFH4 F
A0A177W826 F
A0A2S8GF54 F
Q1YDY8 F
Q5QVH2 F
A3ZT81 F
A0AA35XZV0 F
F4H924 F
K0NJH2 F
A0A1V3SSW1 F
F2AUF4 F
A6DN47 F
W8KM07 F
A0A1X3RP39 F
A0A7S0KKL8 F
A0A318QZ80 F
K8VZC6 F
A0A1B9JZS5 F
A0A2S6GKN5 F
A0A4R2Z2K6 F
H1YCC3 F
E1QIU3 F
A0A8H6MPB9 F
A0A369N7Y3 F
T2IEJ2 F
H5UND3 F
Q1PX09 F
A0A149TSA9 F
F2NGJ8 F
A0A0E3SHQ9 F
Q5FLR6 F
S0EUS1 F
A0A369M386 F
W0DZS7 F
A8MCL4 F
V3ZVE4 F
O26757 F
A0A317FZW2 F
A0A085GI50 F
A1ZGK6 F
G0IYI2 F
A7S731 F
A0A1U9YY82 F
A0A328EMN2 F
A0A8E2UDJ3 F
A0A2S5WUP6 F
A0A8H7P8U1 F
A0A257T7G4 F
B3MX93 F
A0A1G5W0P2 F
D4H2Y7 F
A0A4P8HC89 F
Q7T070 F
F7NPQ3 F
B9SA70 F
Q9M6N7 F
I7ZHW3 F
F4XTK4 F
A4G1J2 F
G7WFX4 F
B8JBH5 F
D9QPC8 F
A0A4R7GKA0 F
R9PMC6 F
A0A0E3LMT4 F
A0A511NGC7 F
E4NS62 F
E4T3F7 F
M0D580 F
J7J5E7 F
B1XZU2 F
A0A366IE34 F
A0A6U2BIY7 F
Q9QXP0 F
A0A424WAH3 F
A0A410K1J5 F
L1IHZ8 F
I8TC71 F
A0A7U8C744 F
A8M670 F
A0A0S4VNK2 F
Q2SIR0 F
A0A5C4RNH5 F
A0A3E0X011 F
A0A0E3SP24 F
E1IF27 F
Q2YBP7 F
A0A2S5WZU0 F
A0A172YBR4 F
A0A0K2STK6 F
A0A2N6JV02 F
F0S0G1 F
A0A1C7EL50 F
Q18PF5 F
A0A1I0C958 F
A0AA35XVN2 F
L8GGA0 F
Q3AP28 F
D0MFE9 F
J9VXX9 F
A0A166IS52 F
F0J7D3 F
W7QG13 F
A4BMY5 F
A6LV49 F
Q1H483 F
A6M3G0 F
E4T0A4 F
A0A3E2UHE6 F
A0A174SD65 F
A0A855EH99 F
C3YB74 F
A0A074KZD8 F
J0S2I0 F
K9WSX4 F
E8RLT5 F
Q2FS34 F
Q3Z7F9 F
Q2S8H9 F
A0A060HN92 F
E6ME92 F
A0A172RYW3 F
L0FU80 F
C8WZE0 F
A0A2S8F4W0 F
A0A2C6C0X3 F
F3ZVV4 F
A0A7R6PER3 F
A0A495WJM6 F
A0A0B4DUR9 F
A0A251YU48 F
A5D4I5 F
A0A2X2C038 F
A0A2A2M8K7 F
D3FBG3 F
A0A2V4EA49 F
D0MFE8 F
Q3B6Q2 F
A0A1B9KID3 F
A0A9J9ES23 F
A0A3N2SFS2 F
Q0VLH1 F
A0A1U9Z147 F
Q0G2T1 F
A6GJF5 F
A0A059XXR1 F
A0A5J6WPP9 F
P41948 F
L1IUV5 F
A0A2W0GQV0 F
Q1K433 F
A0A4Y7XC43 F
D5AU98 F
E1QFA8 F
A0A075WBP9 F
Q0BWD0 F
A0A1Y0HX98 F
A0A098S5Y7 F
Q0I445 F
A0A1E5BXA4 F
A0A2C9CK98 F
G4H971 F
A0A1I0BYN1 F
A0A330GB00 F
A0A2S8FR08 F
Q84KJ6 F
A0A2S5WGI8 F
M2ALH9 F
A0A2K3DQF8 F
A0A8G2IZM3 F
F5Y3C1 F
A0A370FPU0 F
F5RGM7 F
A0A4R4K1P9 F
R8VWI7 F
A0A0A2AMW2 F
Q7Z1M1 F
A0A414NWT8 F
A0A0P6VSR8 F
A0A0L0TDW1 F
U3PCH5 L
W7QGE0 F
C5BWX7 F
A0A1B9M1A9 F
B8GGC3 F
D6SPD1 F
A0A0H3DR67 F
A0A4R7VEK0 F
G4R7P1 F
A0A1M5ZVP9 F
A0A2S5Y0D3 F
I0ICG0 F
D0L8H3 F
A0A1B9LFW3 F
Q6ND34 F
A0A6H9GWG4 F
Q5UZ98 F
A0A2S0P9T4 F
H2CDR5 F
T2KGT3 F
A0A088E6Q7 F
A0A258HS77 F
E1V4T3 F
B7GKP4 F
Q9QUT0 F
I3Z3H7 F
G7WCB6 F
A0A1Y6GLJ1 F
A0A0S2DQB6 F
Q6CRN1 F
A0A401X433 F
A7HT14 F
A0A009TDB1 F
D4XSW0 F
B0SRS8 F
A0A149QSR6 F
B1Y0E5 F
Q7UGU7 F
A0A2S0Q8P1 F
F0ZPL3 Y
A0A2T0GTU1 F
I4CCD1 F
A0A9Q6P4A5 F
A0A418VIJ8 F
C1MX19 F
A0A1B9BUZ8 F
K9W6F3 F
Q1K8A3 F
L8GFX3 F
A0A1G6ABL9 F
A0A087L0B9 F
A0A073CP02 F
A0A0A1ZJU5 F
A0A258HPP1 F
A0A149QAW7 F
D2V6Q5 F
A0A1X4G8K1 F
A0A067Z3S3 F
A0A8F5ZDT8 F
A0A854QN45 F
A0A2N7LCD7 F
G7WFX2 F
A0A7S4GNJ2 F
A4G0C5 F
A6VE60 F
A0A1S1HM83 F
A0A037ZJY5 F
N1WR17 F
Q2W5V2 F
A1VIM5 F
A0A1Y5E3E3 F
A0A1T4SFK4 F
A7RNC3 F
M7XJ51 F
A0A399T909 F
A0A2N6P374 F
H8L2Q4 F
D5EP68 F
E6SF19 F
A0A1T4SFY6 F
D3LBI0 F
E6W5C1 F
Q0VPH4 F
K9WT03 F
L0KW14 F
A0A4R8H081 F
A0A1B9N3H7 F
B0RC35 F
A0A420KGW4 F
A0A4R3NLV5 F
Q47K18 F
Q21P82 F
M1WRK6 F
A0A290XBB5 F
A0A6T9XUR2 F
A0A1J1JH03 F
I3R0S7 F
A9UR54 F
A0A1G7H8X3 F
A0A8G2F718 F
Q1H0G2 F
D0LAL7 F
C7LQR9 F
A0A1G5PWV0 F
K1K628 F
B9SXC7 F
G7WA28 F
Q1IWN6 F
H6LKH9 F
A0A1H7CU41 F
G8JUJ2 F
A0A081N2G5 F
A0A074ME37 F
Q0VQH6 F
C8XB51 F
A1VIG8 F
Q8GQS1 F
A0A1I7FBM5 F
A0A1M6ZMI3 F
A0A482PLH3 F
A0RXK8 F
D0KXQ0 F
Q8JI14 F
A0A7T4WEP4 F
A0A4R3ZNW3 F
A0A074KY88 F
A0A6M3ZKU5 F
M1SJL5 F
A0A1W9KSU5 F
E3GI40 F
A0A369NYJ2 F
A0AA92K392 F
O04161 F
A9BQZ4 F
A0A6N2Z556 F
A0A8H6NAG3 F
A0A2T9X1V4 F
Q2J376 F
A0A0F5EZP7 F
A0A7G5DK18 F
M9YAI9 F
D2ZRW2 F
G7UUY6 F
A0A8H4GS02 F
A0A2T5IHP0 F
A0A165MAC2 F
A0A7S4LPS8 F
A0A075JIN0 F
C8X554 F
B8FZP7 F
Q5KAF6 F
A0A427KNL6 F
A0A7G5DPV0 F
Q22947 F
A0A1S1HRJ0 F
A0A3N1VXY4 F
A0A2S7YPJ9 F
I0JI83 F
A0A7U3YMN6 F
Q9BLG3 F
A0A1H9RTW8 F
A0A1I4W3A0 F
A0A0B4M163 F
U2EN72 F
A0A2W5VAZ2 F
E4YA63 F
D5ELM4 F
M9RJS5 F
A0A2G3E8V2 F
Q5FSX6 F
I0HKQ8 F
A0A833H2R7 F
B8ENL9 F
B3DUX7 F
A0A1D8UWJ6 F
D5E995 F
A0A7U8C2Y6 F
L0KGR8 F
B0VMH1 F
P40260 F
L0JT30 F
C1GR74 F
A0A423Y4I6 F
A0A4P7UHQ5 F
A0A8E2R1Y5 F
I5BYV5 F
A0A6B8N021 F
A0A7G5DPV1 F
A0A2G5RQK9 F
A0A5M4B0G1 F
A0A6S5K4J1 F
C1D4X0 F
A1SVA8 F
H1YF74 F
A0A8B4RWH8 F
A0A0A0D6K5 F
A0A0A2BBY0 F
A0A089ZBW5 F
A0A068TC78 F
Q46G49 F
A1CQ21 F
A0A1G6ABX1 F
E1SLM7 F
K5CFE5 F
Q2YLQ6 F
Q0G2V0 F
A4ABK3 F
A0A9Q5QVI9 F
A0A4Q7Y9I7 F
A9HMD6 F
K9YN27 F
Q9UBD6 F
D9SI59 F
Q8I0L6 F
A0A142VAD6 F
G3IYW0 F
A0A062IU58 F
R1D1H4 F
A0A366XFS8 F
A0A7S4GNF3 F
F0J6E8 F
A0A7U4DN04 F
V4RHR4 F
F7ZJM0 F
A0A2S5XAB8 F
U5C4L4 F
Q21J04 F
A0A142NNN1 F
H1Y7T6 F
F5R974 F
B0DU91 F
A2BP62 F
A7HSN9 F
A0A377I7W9 F
D2RU19 F
G7WJN0 F
E2SD33 F
A0A0D7F2Y9 F
A0AA92EGF5 F
A0A9E9LXV9 F
A4BEP1 F
A0A0E3WZH5 F
F7ZEU9 F
A5E3X2 F
A0A0A3XTJ3 F
A0A830ZZN8 F
A0A1S8D478 F
J7IVQ1 F
A0A2U1SS17 F
S3K1S2 F
C6XKC2 F
A0A2S7YIM5 F
K2IMJ7 F
Q5P1S8 F
A0A7T5BFQ2 F
A0A556SRH6 F
A8P923 F
A0A7G5DKA9 F
L8JUH3 F
A0A0D2LEF5 F
A0A258FTB0 F
A0A5P9P1L2 F
M8E0R3 F
A0A6J5IRX5 F
W5WIX6 F
Q82X47 F
I4DBY0 F
A0A6F8TLE9 F
A0A1G7UZX2 F
A0A6P4JM51 F
G0J614 F
U2WTW8 F
A0A642KQG8 F
Q1AUG3 F
A0A6G9Y3Q0 F
B8J5X4 F
M7NFH3 F
A0A0E3R6S1 F
Q2IHY5 F
A7I8Z2 F
L1IYP4 F
B4HDZ9 F
A0A366WYI9 F
E4TJ50 F
A0A7S0ILH2 F
A4BAE1 F
B3QRJ4 F
A0A5C5BWI6 F
Q7NQY2 F
A0A091AXI3 F
Q1QSQ2 F
R4FZE3 F
A0A2N0MZ27 F
A9BTK1 F
A0A242NIL1 F
G0LFE3 F
A0A1B9NQ91 F
A0A5M5PZE2 F
A0A0D2NYP3 F
D9QPE5 F
I5B3H0 F
L1IYW7 F
C6WEW7 F
B7FW68 F
F4GED5 F
A0A4R8GSH7 F
A0A1W2H3F0 F
A0A3E2T713 F
A0A0H3KTD3 F
A0A1Y4LM49 F
G2PRJ6 F
A0A0X8X7Y7 F
K8EJ02 F
A0A1L3F1X5 F
G8TK77 F
A0A855F5Y8 F
A0A975BTN0 F
A0A562RGZ4 F
G5EB09 F
A0A833LX85 F
U1H1F7 F
K8W1E2 F
E3HJW8 F
Q7SEH0 F
Q47X17 F
B0DXT9 F
A0A3G9G2C9 F
Q95P70 F
A0A837C6X5 F
Q89WR5 F
A6DUG4 F
D7UQE2 F
A0A2I1M481 F
A0A0T7GZ59 F
O66395 F
J3EXK0 F
A0A1B9MYL7 F
K9U8C7 F
E2SD44 F
H6LKH6 F
Q605Y6 F
A0A9Q9D9I3 F
A0A6N2TIA4 F
A0A1E3PQH0 F
A4CMI3 F
Q1K0H9 F
A0A0S6UEK9 F
A0A0H3LUA3 F
B9LU00 F
A9BIZ7 F
A0A7H8UK07 F
E3H8C9 F
M2A398 F
Q1QS12 F
G0VI62 F
A0A1Z3MS36 F
A0A0B5FNH4 F
D9SI36 F
A0A410JZR4 F
F7ZJZ1 F
F0ZCX7 F
W0DZX1 F
A0A4R3ZZ35 F
A0A317G0I6 F
Q0ARJ4 F
A7I8Z4 F
T2KJ59 F
I3C0V3 F
E3H8A6 F
B2IJT1 F
A0A2G6JLT9 F
A3ZZL7 F
A0A2T0XPP2 F
Q31CR9 F
A0A1R1IDV3 F
K2JVF8 F
V5BYZ7 F
D8J4C6 F
D4H5F9 F
K9ZG59 F
A0AA86YS65 F
Q608B6 F
A0A562BXM4 F
A0A401WXG0 F
A0A857DMN9 F
A0A1X6N3Q5 F
A0A173R3X4 F
Q63EK5 F
K9ZLY2 F
A0A533I6R2 F
I0WJ97 F
K0N2R5 F
M0J579 F
B8GGC1 F
A0A6H9GFU4 F
C6CBB1 F
A0A510HHK8 F
A0A1B9MBX6 F
A0A9Y2AG30 F
E8RSE4 F
F2B2B8 F
Q7UYZ3 F
I1YJH7 F
A0A853MG28 F
A0A0L0STS6 F
A0A251XU71 F
Q60BI2 F
A0A829X098 F
F3KUN4 F
Q60C43 F
A0A0T7FAP8 F
A0A3E2TW06 F
W0E077 F
A0KPE9 F
R7PZ71 F
A0A0A1ZMZ9 F
A0AA40J491 F
D3S2L0 F
A0A373FQ71 F
A0A0A2C6L1 F
Q7W7D3 F
A0A165K0X5 F
A0A2S5X482 F
R9GM11 F
Q0G0A3 F
D4GLQ6 F
E7RJZ0 F
F8IJE0 F
A0A1V2XMU9 F
Q7TNN9 F
A0A1G5RZU9 F
A0A2N6K4Y5 F
B0SLB7 F
A0A251YFS0 F
B9WDK0 F
Q7N0M6 F
A0A0M2LU39 F
F4B548 F
D6Z5V9 F
A0A4R2M206 F
A0A1E2SKM1 L
A0A127JTU2 F
A0A212AV03 F
G4QHD2 F
A0A021VMC6 F
A0A2J7TJ33 F
G7WDB5 F
Q6BK68 M
Q1K3N8 F
A0AA91Q161 F
A0NJ07 F
A0A316BQ38 F
A0A377PLP5 F
W7QGM4 F
A0A015YIP3 F
A0A060UWC8 F
A0A1I4ZIZ6 F
A0A264VQM8 F
A9AUR8 F
A0A1W5PRD1 F
A0A0E3BR91 F
A0A1B0ZRL8 F
B9ACS5 F
Q92BJ7 F
F2JTN3 F
A1AVV2 F
D2Q0J8 F
A0A3S9N9F3 F
A8ZQD5 F
C3X831 F
A0A1M6BPM0 F
A0A8F5VN39 F
A0A1E5C7W4 F
A0A2S5WV24 F
A0A833GZR2 F
C7M2A9 F
A6W7U2 F
W0JIB3 F
Q07UM3 F
A0A066ZRQ5 F
S0G181 F
D3PAH1 F
Q4WHC6 F
A0AA94HTL8 F
D5ASL9 F
A0A4U1JNL6 F
M0MDP9 F
A0A653N397 F
A0A2S8GSU9 F
A0A097R891 F
A0A8H7U3I1 F
A0A1H1MB73 F
A0A016XDZ5 F
A0A1B9JHS5 F
D3PE53 F
A0A9J9BAE8 F
Q2RM12 F
A0A3N0AQL8 F
C5KTM6 F
M1P5F0 F
I1YG38 F
A0A660CH85 F
A0A2N7L7C8 F
Q5KZZ9 F
M1NZT5 F
A0A225CMT8 F
A0A068NV61 F
H2CJI0 F
B0DU93 F
Q221S8 F
F4Y3C5 F
Q94CJ2 F
M0D3Q9 F
A0A3P2A7W8 F
C0GKN4 F
Q7T3R4 F
A0A562USB9 F
A2SS52 F
A0A211ZGL5 F
A0A4V3ALP8 F
A0A147GP06 F
H2IZ00 F
Q45HK8 F
A0A6C8LST1 F
A0A257T8W6 F
Q5P470 F
I5AZQ4 F
Q07UM1 F
E5B358 F
A0A1Y4L5P0 F
Q3AFY9 F
B0BZN3 F
A0A1Q2C7H7 F
A0A4R5U5V1 F
H6LKX6 F
A0A1Y0UZX2 F
F6BEI0 F
M9RKT6 F
A7SGD4 F
A0A257TE48 F
R1FI09 F
E4N1T5 F
U1PIR6 F
F2JYR9 F
Q84KJ7 F
A0A2S8FTB5 F
D2R647 F
G9Y5B0 F
A0A144NLT9 F
A0A5J6WQU1 F
D2R355 F
F3ZYD6 F
B0SL05 F
A0A5A7MAJ9 F
A0A977NL43 F
A0A433ZQ80 F
A0A1Y0V4A5 F
A0A1M7UEG2 F
G8R7U9 F
K1LDP0 F
B7G0Y4 F
A0A2W4ZXC0 F
B3PF77 F
Q2KZK9 F
Q18ES8 F
D3F545 F
B4S394 F
Q1Q357 F
Q9H310 F
D3PKL4 F
M5SY07 F
Q8RUT6 F
A7NKH2 F
Q1Q879 F
A0A1B9M5B8 F
A6LRS5 F
J2ZGN6 F
V5E0F3 F
A0A149RQX0 F
A0A165BP25 F
C0QSY0 F
B0XVV6 F
E0SD83 F
A8HSA2 F
A0A1E3PSK5 F
A5DYQ2 F
A0A4U1K1W1 F
Q0AT01 F
A4FMG0 F
C3YB73 F
A0A9P3CXY2 F
A0A0L8BVU4 F
A0A401WUW1 F
I4C9L2 F
Q8RUE9 F
F0JGZ1 F
A0A2I0UUY1 F
A0A542XGT4 F
G0JRH4 F
A2SPS8 F
A0A5M4AWD2 F
Q6QH01 F
D3F0Z1 F
A6XBM2 F
D6E7B3 F
Q13E03 F
A0A060URB8 F
A0A2T1N7R1 F
D6TCH6 F
B0CXH8 F
A3TVQ9 F
Q4WT12 F
C7QGX3 F
F0Y9X3 F
A0A7S0D560 F
A0A160KTE9 F
A0A2H1HV86 F
A0A251Y3N4 F
A0A419AVL2 F
A0A4Q2QWS1 F
C7Q1E4 F
A0A5C5TYS5 F
F2NNQ0 F
A0A2R4TRE0 F
K9YJQ3 F
D9QS43 F
A7SQ16 F
A1DG05 F
U1SIR9 F
C4Y298 F
A0A9W3LFI9 F
D3RMV7 F
F3QNA7 F
E4RTK5 F
C8XBX8 F
C0QTA4 F
E6VIW4 F
A0A2S6H643 F
Q46HB1 F
A0A2S5CTX8 F
A0A1T4SF40 F
K0K7J4 F
A0A1J5JH24 F
Q6LMI6 F
A0A9W5JBA9 F
A0A291PMC6 F
A0A4Y4DZN4 F
A0A2R4MBA2 F
R9PI53 F
A0A6H9GLV4 F
A0A7S4GND2 F
A0A6H9FPY5 F
A0A1G7DX68 F
A0A075WEB4 F
A0A140NHJ5 F
A0A1C6Z081 F
Q5FA36 F
Q0ACK1 F
A0A975GIX9 F
A0A323UE08 F
U7VB41 F
A0A063Y780 F
C5CIT6 F
A0A0A2VPU3 F
F0RHS0 F
A0A2S5WX34 F
C1G973 F
A0A2S6GKF6 F
A0A0A2B651 F
A0A4R3A5P7 F
A0A2A7U6W1 F
Q2GX26 F
F5XN43 F
A0A0K2STH0 F
A0A1H1U2Q6 F
A7SED8 F
A0LV78 F
K5DBA0 F
B8IZX4 F
A8LKQ0 F
A0A5C6LWQ1 F

In [154]:
seqf2 = []

for i in f2:
    print(i.id, i.seq)
    seqf2.append(i.seq)

A0A858ZNJ3 F
A0A1H9M798 F
B0DY50 F
P69680 F
A0A3G9G4Q4 F
A0A149UP06 F
F2G6G4 F
A0A2M9D7S8 F
A0A034WGQ2 F
I0KDC6 F
F8D7H6 F
K9W4V5 F
Q466Y3 F
D2SE15 F
A0A377PBY1 F
B1JZ69 F
A0A2W5HTC3 F
A8G2S3 F
D5T4N9 F
Q2RWY7 L
A0A0E3R4G0 F
I4C9L0 F
D5VJ32 F
C0Z5S5 F
C1N6X9 F
J7ITF6 F
A0A068SVR1 F
A0A0D7F328 F
Q0G0A4 F
F0J3F9 F
Q0BQ69 F
F2YIC4 F
D4XLN6 F
A0A420WC79 F
A0A5C5TUT2 F
A0RUZ2 F
A0A0A2ZRL7 F
J4UGB7 F
E5Y678 F
A0A0D2KGN8 F
S5ABR8 F
A9DQM8 F
G5EB13 F
A0A2N6NEK4 F
C6DB68 F
Q81GN5 F
Q0F2M5 F
A0A0C6P439 F
B9SWW9 F
L8H5K0 F
Q9NIV0 F
C1N5A7 F
Q1JXS5 F
A0A1M6JKY3 F
F4D1J0 F
A0A257SYX3 F
V4RK08 F
G0V8D6 F
A0A7S4GMD8 F
B3QVV5 F
F2JZ83 F
A0A857DDJ7 F
A0A0S6UHP2 F
D5EP71 F
F4KY49 F
M5S9B4 F
A0A009PYN3 F
A0A3T0SZ22 F
A0A248LMH8 F
A0A6H9GEE4 F
A7HSP2 F
A0A7V8IKS6 F
T2JFS5 F
F6FRU9 F
A0A9E9L9J1 F
A0AIW5 F
A0A0E9NHV4 F
Q2N625 F
C8WSI9 F
A0A1H1BPD6 F
A0A176XNC5 F
A0A4V0XUI3 F
A7S3L2 F
M5U2P1 F
K9P5D1 F
Q0F2M7 F
A0A2R3IMJ8 F
Q2RVB5 F
A0A556RTU3 F
E0TGP9 F
B7G0Y1 F
A0A1G9P6Q0 F
D0LTW3 F
Q6BT62 F
Q2IK04 F
Q6BJI7 F
B7X047 F
A0A068NPW2 F
A0A399NT81 F
K0F9X7 F
A0A037ZMW1 F
A0A075JZ35 F
A0A369MHK2 F
A0A1B9JPL5 F
D8PD01 F
A0A2G5BI87 F
A0A2G5BGA9 F
A0A657K391 F
P69681 F
A0A4P6UIJ8 F
A0A0V8M0W6 F
A0A0H2XSU4 F
Q1Z695 F
A0A7Z0V0A4 F
K0ER80 F
A0A149UWF2 F
G0H0Z6 F
G0EFF3 F
C8WLL8 F
X5CNT2 F
A0A4Y1MSE7 F
H2CLF7 F
M4VEJ9 F
A0A4V2X6C2 F
A0A2K1RA77 F
A0A375YPN6 F
A0A7M6UUM4 F
A0A172YCA7 F
A0A918MJ52 F
A0A2S8QA29 F
A0A251XJT0 F
A0A0B4E6X7 F
A0A0K2STQ7 F
A1C5Z7 F
C9KKP2 F
A0A2Z4MD56 F
Q9VFA9 F
A0A502GPV4 F
I5C044 F
D2V6P8 F
D3RN22 F
Q97L80 F
A0A0D5YN10 F
A0A1I5GN22 F
A0A1Y5E8I7 F
B1Y8C9 F
M5SYZ1 F
Q6HM26 F
A0A379A0S9 F
A0A101DCS3 F
A0A1Y3U5V2 F
A0A202B535 F
F8E6R1 F
Q6ND36 F
A0A8H6K7L7 F
Q7NCB8 F
A0A369MRW6 F
C9RS76 F
A3U857 F
A0A127PIQ9 F
B8FGW0 F
A0A060JMP6 F
D5V7B3 F
A0A494JB70 F
A0A5M8QF12 F
A0A8G2F3G4 F
J7L3W8 F
G0JRG9 F
D3DJN2 F
A0A1Y2JH43 F
Q1L727 F
A0A7T2S0Z6 F
A0A315S845 F
A0A2S6H6B7 F
A0A1J5NTP7 F
A0A0E3QY86 F
A0A096EEV9 F
A0A380S5X4 F
B8ZYW3 F
A0A2S8GEJ5 F
A0A248TDF2 F
B2GFN1 F
U1PPI7 F
C7LW88 F
G3A431 F
A0A066ZTE4 F
L7CG99 F
S0ET45 F
A0A178TA08 F
H1XV27 F
A0A6M3ZJI1 F
U5DEY6 F
H6LFQ2 F
Q6CRN0 F
A0A4Q2EAG7 F
A0A1J5NNB8 F
E3I393 F
A0A243SC06 F
D4F313 F
W0F0I7 F
A9B874 F
A1D2Y5 F
T2J0N1 F
Q2FQT3 F
A0A075WG29 F
A0A979GQ79 F
A0A381CAY8 F
A0A2G3DSU6 F
A0A168EVK8 F
A0A094W9G3 F
A0A4R3NVT3 F
W0DYY3 F
G8JTW0 F
A0A4P6UIK6 F
I9P003 F
G2T1Y3 F
B8EMQ8 F
I6Z905 F
E0TCV4 F
A3XNG6 F
A0A087MGU4 F
A2BUP4 F
A0A562S8V2 F
A0A495DND0 F
A0A0S2FHD7 F
F3QPR6 F
A0A063Y394 F
F6G5I9 F
A0A323UDG5 F
A0A0G9HEC5 F
B8FDY8 F
Q5KPM5 F
A0A147EQL9 F
A0A854Q6X9 F
C3X1J1 F
A0A5B2V3B9 F
A0A258FS85 F
A0A7T2W1B3 F
A0A060UN76 F
G0JRQ3 F
D5UD26 F
G2ZN72 F
A0AA46Q839 F
A5UJR1 F
L1INN6 F
C1F584 F
C5LAG4 F
A0A2A2MCP3 F
B1Y6V4 F
A0A1G6ABK5 F
A0A6A1TYJ4 F
A0A2T4UWF1 F
V4AP67 F
A0A173R3W6 F
C7NND3 F
B0DFJ4 F
A0A3E2VY88 F
R1EDV9 F
J1L5M8 F
D7G265 F
Q8ERT9 F
I4D6Z9 F
A0A4R6DFU8 F
A0A060URC3 F
D2BIB2 F
F5ISF6 F
A5CRL2 F
A0A6G9XJV9 F
Q59UP8 F
A0A6N4SPH9 F
I0HGY4 F
X5DX97 F
L1J6I4 F
I1DSU5 F
B9L7N1 F
Q1Z4I4 F
Q21CP1 F
A0A165MFD1 F
V4CRP5 F
Q7S5K0 F
A0A071MMV1 F
A0A149RYW7 F
A0A7G5EC77 F
A0A1W2GZ82 F
A0A7U3XVQ4 F
A0A071M4L5 F
U5C2K4 F
A0A248LNW8 F
L8H844 F
A0A149V596 F
S9QZ09 F
B1ZSW9 F
D2BUJ8 F
A0A9Q8L398 F
M5S735 F
Q6ARH0 F
K6W5X0 F
G0JRG6 F
A0A6H9FYW4 F
A0A0S4WFM4 F
A0A101HKN9 F
Q9REX3 F
F0S3Z6 F
A8NAG3 F
C6LBD3 F
A0A149U2G9 F
V4REY8 F
A0A0H3H4I7 F
A8N2H6 F
S0APH6 F
A0A017SYR8 F
A0A1B9MZ78 F
E4T3F3 F
D7E934 F
A0A0M3AB44 F
A9WHW6 F
A0A5M4AUM9 F
A0A1X4GBG2 F
I4D1H5 F
A0A0E3QYF3 F
B0CQX4 F
A0A378YR15 F
A0A495D4X4 F
A0A076PL76 F
Q1YDY7 F
A0A3E2UCG9 F
A0A2K3DPU7 F
A0A3R9Q7C4 F
V5U2Z4 F
K9P718 F
M1V7W3 F
Q6LKC8 F
E5Y789 F
J9Z839 F
A0A1G7VM92 F
K9Z0D3 F
A0A482TED1 F
R1EGK6 F
J1ASR8 F
A0A7U4E420 F
K9YR86 F
A8PXT8 F
A0A0U1NJW3 F
B8FL88 F
A2CCK1 F
D6TFE1 F
A0A2H4U5R1 F
I2GD40 F
A0A060HFT5 F
B1Y842 F
A0A0X8NXA9 F
A0A0A2A5X1 F
A0A318FY98 F
Q7V4T8 F
A0A1A0DHK0 F
C1A872 F
A0A395VB65 F
A7MFK3 F
J4KM12 F
A1SY01 F
A0A1H4DJ49 F
A0A9R0NTP8 F
A3PAY4 F
B4CV94 F
A2C095 F
Q2HD43 F
A0A836M2B6 F
H6RWK9 F
A0A087EQK8 F
A0A1I0AQM4 F
L7CG11 F
A0A248LNK5 F
B7FTM9 F
L0K9M1 F
I4D6Z7 F
A0A2K1RA81 F
Q2WBF7 F
A0A1B9BUU6 F
A0A2S0JW39 F
A0A2S5YID7 F
B3PIH2 F
U3P8G1 F
C9R9J0 F
A8AC17 F
F0YLV7 F
A0A1D3GAE9 F
C1MHX0 F
A0A1H4KAQ7 F
A0A2T4XZC1 F
A1B3N0 F
C7LW87 F
A1SZ12 F
A0A2T2Y0D5 F
A0A1H8D0R8 F
A0A2S5V2F6 F
G3IYW2 F
F5L8M7 F
C7BJG7 F
E4U5Z1 F
A0A1B9K8L2 F
A0A2S5WMT7 F
A0A0D2UPA8 F
A0A161SKF4 F
B4D7W2 F
A0A1H3WA00 F
C1D6X6 F
A0A4D6KHD1 F
Q488X2 F
A9V5W4 F
A0A5M4ATH9 F
E4TRS4 F
A0A011U1K7 F
C7R314 F
A0A077EFU9 F
A0A0A2A0Y9 F
A0A0D8BQX6 F
A0A0L0S493 F
A0A328Q6M1 F
A0A016XCG9 F
B7FSA7 F
G0AFH4 F
A0A177W826 F
A0A2S8GF54 F
Q1YDY8 F
Q5QVH2 F
A3ZT81 F
A0AA35XZV0 F
F4H924 F
K0NJH2 F
A0A1V3SSW1 F
F2AUF4 F
A6DN47 F
W8KM07 F
A0A1X3RP39 F
A0A7S0KKL8 F
A0A318QZ80 F
K8VZC6 F
A0A1B9JZS5 F
A0A2S6GKN5 F
A0A4R2Z2K6 F
H1YCC3 F
E1QIU3 F
A0A8H6MPB9 F
A0A369N7Y3 F
T2IEJ2 F
H5UND3 F
Q1PX09 F
A0A149TSA9 F
F2NGJ8 F
A0A0E3SHQ9 F
Q5FLR6 F
S0EUS1 F
A0A369M386 F
W0DZS7 F
A8MCL4 F
V3ZVE4 F
O26757 F
A0A317FZW2 F
A0A085GI50 F
A1ZGK6 F
G0IYI2 F
A7S731 F
A0A1U9YY82 F
A0A328EMN2 F
A0A8E2UDJ3 F
A0A2S5WUP6 F
A0A8H7P8U1 F
A0A257T7G4 F
B3MX93 F
A0A1G5W0P2 F
D4H2Y7 F
A0A4P8HC89 F
Q7T070 F
F7NPQ3 F
B9SA70 F
Q9M6N7 F
I7ZHW3 F
F4XTK4 F
A4G1J2 F
G7WFX4 F
B8JBH5 F
D9QPC8 F
A0A4R7GKA0 F
R9PMC6 F
A0A0E3LMT4 F
A0A511NGC7 F
E4NS62 F
E4T3F7 F
M0D580 F
J7J5E7 F
B1XZU2 F
A0A366IE34 F
A0A6U2BIY7 F
Q9QXP0 F
A0A424WAH3 F
A0A410K1J5 F
L1IHZ8 F
I8TC71 F
A0A7U8C744 F
A8M670 F
A0A0S4VNK2 F
Q2SIR0 F
A0A5C4RNH5 F
A0A3E0X011 F
A0A0E3SP24 F
E1IF27 F
Q2YBP7 F
A0A2S5WZU0 F
A0A172YBR4 F
A0A0K2STK6 F
A0A2N6JV02 F
F0S0G1 F
A0A1C7EL50 F
Q18PF5 F
A0A1I0C958 F
A0AA35XVN2 F
L8GGA0 F
Q3AP28 F
D0MFE9 F
J9VXX9 F
A0A166IS52 F
F0J7D3 F
W7QG13 F
A4BMY5 F
A6LV49 F
Q1H483 F
A6M3G0 F
E4T0A4 F
A0A3E2UHE6 F
A0A174SD65 F
A0A855EH99 F
C3YB74 F
A0A074KZD8 F
J0S2I0 F
K9WSX4 F
E8RLT5 F
Q2FS34 F
Q3Z7F9 F
Q2S8H9 F
A0A060HN92 F
E6ME92 F
A0A172RYW3 F
L0FU80 F
C8WZE0 F
A0A2S8F4W0 F
A0A2C6C0X3 F
F3ZVV4 F
A0A7R6PER3 F
A0A495WJM6 F
A0A0B4DUR9 F
A0A251YU48 F
A5D4I5 F
A0A2X2C038 F
A0A2A2M8K7 F
D3FBG3 F
A0A2V4EA49 F
D0MFE8 F
Q3B6Q2 F
A0A1B9KID3 F
A0A9J9ES23 F
A0A3N2SFS2 F
Q0VLH1 F
A0A1U9Z147 F
Q0G2T1 F
A6GJF5 F
A0A059XXR1 F
A0A5J6WPP9 F
P41948 F
L1IUV5 F
A0A2W0GQV0 F
Q1K433 F
A0A4Y7XC43 F
D5AU98 F
E1QFA8 F
A0A075WBP9 F
Q0BWD0 F
A0A1Y0HX98 F
A0A098S5Y7 F
Q0I445 F
A0A1E5BXA4 F
A0A2C9CK98 F
G4H971 F
A0A1I0BYN1 F
A0A330GB00 F
A0A2S8FR08 F
Q84KJ6 F
A0A2S5WGI8 F
M2ALH9 F
A0A2K3DQF8 F
A0A8G2IZM3 F
F5Y3C1 F
A0A370FPU0 F
F5RGM7 F
A0A4R4K1P9 F
R8VWI7 F
A0A0A2AMW2 F
Q7Z1M1 F
A0A414NWT8 F
A0A0P6VSR8 F
A0A0L0TDW1 F
U3PCH5 L
W7QGE0 F
C5BWX7 F
A0A1B9M1A9 F
B8GGC3 F
D6SPD1 F
A0A0H3DR67 F
A0A4R7VEK0 F
G4R7P1 F
A0A1M5ZVP9 F
A0A2S5Y0D3 F
I0ICG0 F
D0L8H3 F
A0A1B9LFW3 F
Q6ND34 F
A0A6H9GWG4 F
Q5UZ98 F
A0A2S0P9T4 F
H2CDR5 F
T2KGT3 F
A0A088E6Q7 F
A0A258HS77 F
E1V4T3 F
B7GKP4 F
Q9QUT0 F
I3Z3H7 F
G7WCB6 F
A0A1Y6GLJ1 F
A0A0S2DQB6 F
Q6CRN1 F
A0A401X433 F
A7HT14 F
A0A009TDB1 F
D4XSW0 F
B0SRS8 F
A0A149QSR6 F
B1Y0E5 F
Q7UGU7 F
A0A2S0Q8P1 F
F0ZPL3 Y
A0A2T0GTU1 F
I4CCD1 F
A0A9Q6P4A5 F
A0A418VIJ8 F
C1MX19 F
A0A1B9BUZ8 F
K9W6F3 F
Q1K8A3 F
L8GFX3 F
A0A1G6ABL9 F
A0A087L0B9 F
A0A073CP02 F
A0A0A1ZJU5 F
A0A258HPP1 F
A0A149QAW7 F
D2V6Q5 F
A0A1X4G8K1 F
A0A067Z3S3 F
A0A8F5ZDT8 F
A0A854QN45 F
A0A2N7LCD7 F
G7WFX2 F
A0A7S4GNJ2 F
A4G0C5 F
A6VE60 F
A0A1S1HM83 F
A0A037ZJY5 F
N1WR17 F
Q2W5V2 F
A1VIM5 F
A0A1Y5E3E3 F
A0A1T4SFK4 F
A7RNC3 F
M7XJ51 F
A0A399T909 F
A0A2N6P374 F
H8L2Q4 F
D5EP68 F
E6SF19 F
A0A1T4SFY6 F
D3LBI0 F
E6W5C1 F
Q0VPH4 F
K9WT03 F
L0KW14 F
A0A4R8H081 F
A0A1B9N3H7 F
B0RC35 F
A0A420KGW4 F
A0A4R3NLV5 F
Q47K18 F
Q21P82 F
M1WRK6 F
A0A290XBB5 F
A0A6T9XUR2 F
A0A1J1JH03 F
I3R0S7 F
A9UR54 F
A0A1G7H8X3 F
A0A8G2F718 F
Q1H0G2 F
D0LAL7 F
C7LQR9 F
A0A1G5PWV0 F
K1K628 F
B9SXC7 F
G7WA28 F
Q1IWN6 F
H6LKH9 F
A0A1H7CU41 F
G8JUJ2 F
A0A081N2G5 F
A0A074ME37 F
Q0VQH6 F
C8XB51 F
A1VIG8 F
Q8GQS1 F
A0A1I7FBM5 F
A0A1M6ZMI3 F
A0A482PLH3 F
A0RXK8 F
D0KXQ0 F
Q8JI14 F
A0A7T4WEP4 F
A0A4R3ZNW3 F
A0A074KY88 F
A0A6M3ZKU5 F
M1SJL5 F
A0A1W9KSU5 F
E3GI40 F
A0A369NYJ2 F
A0AA92K392 F
O04161 F
A9BQZ4 F
A0A6N2Z556 F
A0A8H6NAG3 F
A0A2T9X1V4 F
Q2J376 F
A0A0F5EZP7 F
A0A7G5DK18 F
M9YAI9 F
D2ZRW2 F
G7UUY6 F
A0A8H4GS02 F
A0A2T5IHP0 F
A0A165MAC2 F
A0A7S4LPS8 F
A0A075JIN0 F
C8X554 F
B8FZP7 F
Q5KAF6 F
A0A427KNL6 F
A0A7G5DPV0 F
Q22947 F
A0A1S1HRJ0 F
A0A3N1VXY4 F
A0A2S7YPJ9 F
I0JI83 F
A0A7U3YMN6 F
Q9BLG3 F
A0A1H9RTW8 F
A0A1I4W3A0 F
A0A0B4M163 F
U2EN72 F
A0A2W5VAZ2 F
E4YA63 M
D5ELM4 F
M9RJS5 F
A0A2G3E8V2 F
Q5FSX6 F
I0HKQ8 F
A0A833H2R7 F
B8ENL9 F
B3DUX7 F
A0A1D8UWJ6 F
D5E995 F
A0A7U8C2Y6 F
L0KGR8 F
B0VMH1 F
P40260 F
L0JT30 F
C1GR74 F
A0A423Y4I6 F
A0A4P7UHQ5 F
A0A8E2R1Y5 F
I5BYV5 F
A0A6B8N021 F
A0A7G5DPV1 F
A0A2G5RQK9 F
A0A5M4B0G1 F
A0A6S5K4J1 F
C1D4X0 F
A1SVA8 F
H1YF74 F
A0A8B4RWH8 F
A0A0A0D6K5 F
A0A0A2BBY0 F
A0A089ZBW5 F
A0A068TC78 F
Q46G49 F
A1CQ21 F
A0A1G6ABX1 F
E1SLM7 F
K5CFE5 F
Q2YLQ6 F
Q0G2V0 F
A4ABK3 F
A0A9Q5QVI9 F
A0A4Q7Y9I7 F
A9HMD6 F
K9YN27 F
Q9UBD6 F
D9SI59 F
Q8I0L6 F
A0A142VAD6 F
G3IYW0 F
A0A062IU58 F
R1D1H4 F
A0A366XFS8 F
A0A7S4GNF3 F
F0J6E8 F
A0A7U4DN04 F
V4RHR4 F
F7ZJM0 F
A0A2S5XAB8 F
U5C4L4 F
Q21J04 F
A0A142NNN1 F
H1Y7T6 F
F5R974 F
B0DU91 F
A2BP62 F
A7HSN9 F
A0A377I7W9 F
D2RU19 F
G7WJN0 F
E2SD33 F
A0A0D7F2Y9 F
A0AA92EGF5 F
A0A9E9LXV9 F
A4BEP1 F
A0A0E3WZH5 F
F7ZEU9 F
A5E3X2 F
A0A0A3XTJ3 F
A0A830ZZN8 F
A0A1S8D478 F
J7IVQ1 F
A0A2U1SS17 F
S3K1S2 F
C6XKC2 F
A0A2S7YIM5 F
K2IMJ7 F
Q5P1S8 F
A0A7T5BFQ2 F
A0A556SRH6 F
A8P923 F
A0A7G5DKA9 F
L8JUH3 F
A0A0D2LEF5 F
A0A258FTB0 F
A0A5P9P1L2 F
M8E0R3 F
A0A6J5IRX5 F
W5WIX6 F
Q82X47 F
I4DBY0 F
A0A6F8TLE9 F
A0A1G7UZX2 F
A0A6P4JM51 F
G0J614 F
U2WTW8 F
A0A642KQG8 F
Q1AUG3 F
A0A6G9Y3Q0 F
B8J5X4 F
M7NFH3 F
A0A0E3R6S1 F
Q2IHY5 F
A7I8Z2 F
L1IYP4 F
B4HDZ9 F
A0A366WYI9 F
E4TJ50 F
A0A7S0ILH2 F
A4BAE1 F
B3QRJ4 F
A0A5C5BWI6 F
Q7NQY2 F
A0A091AXI3 F
Q1QSQ2 F
R4FZE3 F
A0A2N0MZ27 F
A9BTK1 F
A0A242NIL1 F
G0LFE3 F
A0A1B9NQ91 F
A0A5M5PZE2 F
A0A0D2NYP3 F
D9QPE5 F
I5B3H0 F
L1IYW7 F
C6WEW7 F
B7FW68 F
F4GED5 F
A0A4R8GSH7 F
A0A1W2H3F0 F
A0A3E2T713 F
A0A0H3KTD3 F
A0A1Y4LM49 F
G2PRJ6 F
A0A0X8X7Y7 F
K8EJ02 F
A0A1L3F1X5 F
G8TK77 F
A0A855F5Y8 F
A0A975BTN0 F
A0A562RGZ4 F
G5EB09 F
A0A833LX85 F
U1H1F7 F
K8W1E2 F
E3HJW8 F
Q7SEH0 F
Q47X17 F
B0DXT9 F
A0A3G9G2C9 F
Q95P70 F
A0A837C6X5 F
Q89WR5 F
A6DUG4 F
D7UQE2 F
A0A2I1M481 F
A0A0T7GZ59 F
O66395 F
J3EXK0 F
A0A1B9MYL7 F
K9U8C7 F
E2SD44 F
H6LKH6 F
Q605Y6 F
A0A9Q9D9I3 F
A0A6N2TIA4 F
A0A1E3PQH0 F
A4CMI3 F
Q1K0H9 F
A0A0S6UEK9 F
A0A0H3LUA3 F
B9LU00 F
A9BIZ7 F
A0A7H8UK07 F
E3H8C9 F
M2A398 F
Q1QS12 F
G0VI62 F
A0A1Z3MS36 F
A0A0B5FNH4 F
D9SI36 F
A0A410JZR4 F
F7ZJZ1 F
F0ZCX7 F
W0DZX1 F
A0A4R3ZZ35 F
A0A317G0I6 F
Q0ARJ4 F
A7I8Z4 F
T2KJ59 F
I3C0V3 F
E3H8A6 F
B2IJT1 F
A0A2G6JLT9 F
A3ZZL7 F
A0A2T0XPP2 F
Q31CR9 F
A0A1R1IDV3 F
K2JVF8 F
V5BYZ7 F
D8J4C6 F
D4H5F9 F
K9ZG59 F
A0AA86YS65 F
Q608B6 F
A0A562BXM4 F
A0A401WXG0 F
A0A857DMN9 F
A0A1X6N3Q5 F
A0A173R3X4 F
Q63EK5 F
K9ZLY2 F
A0A533I6R2 F
I0WJ97 F
K0N2R5 F
M0J579 F
B8GGC1 F
A0A6H9GFU4 F
C6CBB1 F
A0A510HHK8 F
A0A1B9MBX6 F
A0A9Y2AG30 F
E8RSE4 F
F2B2B8 F
Q7UYZ3 F
I1YJH7 F
A0A853MG28 F
A0A0L0STS6 F
A0A251XU71 F
Q60BI2 F
A0A829X098 F
F3KUN4 F
Q60C43 F
A0A0T7FAP8 F
A0A3E2TW06 F
W0E077 F
A0KPE9 F
R7PZ71 F
A0A0A1ZMZ9 F
A0AA40J491 F
D3S2L0 F
A0A373FQ71 F
A0A0A2C6L1 F
Q7W7D3 F
A0A165K0X5 F
A0A2S5X482 F
R9GM11 F
Q0G0A3 F
D4GLQ6 F
E7RJZ0 F
F8IJE0 F
A0A1V2XMU9 F
Q7TNN9 F
A0A1G5RZU9 F
A0A2N6K4Y5 F
B0SLB7 F
A0A251YFS0 F
B9WDK0 F
Q7N0M6 F
A0A0M2LU39 F
F4B548 F
D6Z5V9 F
A0A4R2M206 F
A0A1E2SKM1 L
A0A127JTU2 F
A0A212AV03 F
G4QHD2 F
A0A021VMC6 F
A0A2J7TJ33 F
G7WDB5 F
Q6BK68 F
Q1K3N8 F
A0AA91Q161 F
A0NJ07 F
A0A316BQ38 F
A0A377PLP5 F
W7QGM4 F
A0A015YIP3 F
A0A060UWC8 F
A0A1I4ZIZ6 F
A0A264VQM8 F
A9AUR8 F
A0A1W5PRD1 F
A0A0E3BR91 F
A0A1B0ZRL8 F
B9ACS5 F
Q92BJ7 F
F2JTN3 F
A1AVV2 F
D2Q0J8 F
A0A3S9N9F3 F
A8ZQD5 F
C3X831 F
A0A1M6BPM0 F
A0A8F5VN39 F
A0A1E5C7W4 F
A0A2S5WV24 F
A0A833GZR2 F
C7M2A9 F
A6W7U2 F
W0JIB3 F
Q07UM3 F
A0A066ZRQ5 F
S0G181 F
D3PAH1 F
Q4WHC6 F
A0AA94HTL8 F
D5ASL9 F
A0A4U1JNL6 F
M0MDP9 F
A0A653N397 F
A0A2S8GSU9 F
A0A097R891 F
A0A8H7U3I1 F
A0A1H1MB73 F
A0A016XDZ5 F
A0A1B9JHS5 F
D3PE53 F
A0A9J9BAE8 F
Q2RM12 F
A0A3N0AQL8 F
C5KTM6 F
M1P5F0 F
I1YG38 F
A0A660CH85 F
A0A2N7L7C8 F
Q5KZZ9 F
M1NZT5 F
A0A225CMT8 F
A0A068NV61 F
H2CJI0 F
B0DU93 F
Q221S8 F
F4Y3C5 F
Q94CJ2 F
M0D3Q9 F
A0A3P2A7W8 F
C0GKN4 F
Q7T3R4 F
A0A562USB9 F
A2SS52 F
A0A211ZGL5 F
A0A4V3ALP8 F
A0A147GP06 F
H2IZ00 F
Q45HK8 F
A0A6C8LST1 F
A0A257T8W6 F
Q5P470 F
I5AZQ4 F
Q07UM1 F
E5B358 F
A0A1Y4L5P0 F
Q3AFY9 F
B0BZN3 F
A0A1Q2C7H7 F
A0A4R5U5V1 F
H6LKX6 F
A0A1Y0UZX2 F
F6BEI0 F
M9RKT6 F
A7SGD4 L
A0A257TE48 F
R1FI09 F
E4N1T5 F
U1PIR6 F
F2JYR9 F
Q84KJ7 F
A0A2S8FTB5 F
D2R647 F
G9Y5B0 F
A0A144NLT9 F
A0A5J6WQU1 F
D2R355 F
F3ZYD6 F
B0SL05 F
A0A5A7MAJ9 F
A0A977NL43 F
A0A433ZQ80 F
A0A1Y0V4A5 F
A0A1M7UEG2 F
G8R7U9 F
K1LDP0 F
B7G0Y4 F
A0A2W4ZXC0 F
B3PF77 F
Q2KZK9 F
Q18ES8 F
D3F545 F
B4S394 F
Q1Q357 F
Q9H310 F
D3PKL4 F
M5SY07 F
Q8RUT6 F
A7NKH2 F
Q1Q879 F
A0A1B9M5B8 F
A6LRS5 F
J2ZGN6 F
V5E0F3 F
A0A149RQX0 F
A0A165BP25 F
C0QSY0 F
B0XVV6 F
E0SD83 F
A8HSA2 F
A0A1E3PSK5 F
A5DYQ2 F
A0A4U1K1W1 F
Q0AT01 F
A4FMG0 F
C3YB73 F
A0A9P3CXY2 F
A0A0L8BVU4 F
A0A401WUW1 F
I4C9L2 F
Q8RUE9 F
F0JGZ1 F
A0A2I0UUY1 F
A0A542XGT4 F
G0JRH4 F
A2SPS8 F
A0A5M4AWD2 F
Q6QH01 F
D3F0Z1 F
A6XBM2 F
D6E7B3 F
Q13E03 F
A0A060URB8 F
A0A2T1N7R1 F
D6TCH6 F
B0CXH8 F
A3TVQ9 F
Q4WT12 F
C7QGX3 F
F0Y9X3 F
A0A7S0D560 F
A0A160KTE9 F
A0A2H1HV86 F
A0A251Y3N4 F
A0A419AVL2 F
A0A4Q2QWS1 F
C7Q1E4 F
A0A5C5TYS5 F
F2NNQ0 F
A0A2R4TRE0 F
K9YJQ3 F
D9QS43 F
A7SQ16 F
A1DG05 F
U1SIR9 F
C4Y298 F
A0A9W3LFI9 F
D3RMV7 F
F3QNA7 F
E4RTK5 F
C8XBX8 F
C0QTA4 F
E6VIW4 F
A0A2S6H643 F
Q46HB1 F
A0A2S5CTX8 F
A0A1T4SF40 F
K0K7J4 F
A0A1J5JH24 F
Q6LMI6 F
A0A9W5JBA9 F
A0A291PMC6 F
A0A4Y4DZN4 F
A0A2R4MBA2 F
R9PI53 F
A0A6H9GLV4 F
A0A7S4GND2 F
A0A6H9FPY5 F
A0A1G7DX68 F
A0A075WEB4 F
A0A140NHJ5 F
A0A1C6Z081 F
Q5FA36 F
Q0ACK1 F
A0A975GIX9 F
A0A323UE08 F
U7VB41 F
A0A063Y780 F
C5CIT6 F
A0A0A2VPU3 F
F0RHS0 F
A0A2S5WX34 F
C1G973 F
A0A2S6GKF6 F
A0A0A2B651 F
A0A4R3A5P7 F
A0A2A7U6W1 F
Q2GX26 F
F5XN43 F
A0A0K2STH0 F
A0A1H1U2Q6 F
A7SED8 F
A0LV78 F
K5DBA0 F
B8IZX4 F
A8LKQ0 F
A0A5C6LWQ1 F

In [155]:
seqh1 = []

for i in h1:
    print(i.id, i.seq)
    seqh1.append(i.seq)

A0A858ZNJ3 H
A0A1H9M798 H
B0DY50 H
P69680 H
A0A3G9G4Q4 H
A0A149UP06 H
F2G6G4 H
A0A2M9D7S8 H
A0A034WGQ2 H
I0KDC6 H
F8D7H6 H
K9W4V5 H
Q466Y3 H
D2SE15 H
A0A377PBY1 H
B1JZ69 H
A0A2W5HTC3 H
A8G2S3 H
D5T4N9 H
Q2RWY7 H
A0A0E3R4G0 H
I4C9L0 H
D5VJ32 H
C0Z5S5 H
C1N6X9 H
J7ITF6 E
A0A068SVR1 H
A0A0D7F328 H
Q0G0A4 H
F0J3F9 H
Q0BQ69 H
F2YIC4 H
D4XLN6 H
A0A420WC79 H
A0A5C5TUT2 H
A0RUZ2 H
A0A0A2ZRL7 H
J4UGB7 H
E5Y678 H
A0A0D2KGN8 H
S5ABR8 H
A9DQM8 H
G5EB13 H
A0A2N6NEK4 E
C6DB68 H
Q81GN5 H
Q0F2M5 H
A0A0C6P439 H
B9SWW9 H
L8H5K0 H
Q9NIV0 H
C1N5A7 H
Q1JXS5 H
A0A1M6JKY3 H
F4D1J0 H
A0A257SYX3 H
V4RK08 H
G0V8D6 E
A0A7S4GMD8 H
B3QVV5 H
F2JZ83 H
A0A857DDJ7 H
A0A0S6UHP2 H
D5EP71 H
F4KY49 H
M5S9B4 H
A0A009PYN3 H
A0A3T0SZ22 H
A0A248LMH8 H
A0A6H9GEE4 H
A7HSP2 H
A0A7V8IKS6 H
T2JFS5 H
F6FRU9 H
A0A9E9L9J1 H
A0AIW5 H
A0A0E9NHV4 H
Q2N625 H
C8WSI9 H
A0A1H1BPD6 H
A0A176XNC5 H
A0A4V0XUI3 H
A7S3L2 H
M5U2P1 H
K9P5D1 H
Q0F2M7 H
A0A2R3IMJ8 H
Q2RVB5 H
A0A556RTU3 H
E0TGP9 H
B7G0Y1 H
A0A1G9P6Q0 H
D0LTW3 H
Q6BT62 H
Q2IK04 H
Q6BJI7 E
B7X047 H
A0A068NPW2 H
A0A399NT81 H
K0F9X7 H
A0A037ZMW1 H
A0A075JZ35 H
A0A369MHK2 H
A0A1B9JPL5 H
D8PD01 H
A0A2G5BI87 E
A0A2G5BGA9 H
A0A657K391 H
P69681 H
A0A4P6UIJ8 H
A0A0V8M0W6 H
A0A0H2XSU4 H
Q1Z695 H
A0A7Z0V0A4 H
K0ER80 E
A0A149UWF2 H
G0H0Z6 H
G0EFF3 H
C8WLL8 H
X5CNT2 H
A0A4Y1MSE7 H
H2CLF7 H
M4VEJ9 H
A0A4V2X6C2 H
A0A2K1RA77 H
A0A375YPN6 H
A0A7M6UUM4 H
A0A172YCA7 H
A0A918MJ52 H
A0A2S8QA29 H
A0A251XJT0 H
A0A0B4E6X7 H
A0A0K2STQ7 H
A1C5Z7 E
C9KKP2 H
A0A2Z4MD56 H
Q9VFA9 H
A0A502GPV4 H
I5C044 H
D2V6P8 H
D3RN22 H
Q97L80 H
A0A0D5YN10 H
A0A1I5GN22 H
A0A1Y5E8I7 H
B1Y8C9 H
M5SYZ1 H
Q6HM26 H
A0A379A0S9 H
A0A101DCS3 H
A0A1Y3U5V2 H
A0A202B535 H
F8E6R1 H
Q6ND36 H
A0A8H6K7L7 E
Q7NCB8 H
A0A369MRW6 H
C9RS76 H
A3U857 H
A0A127PIQ9 H
B8FGW0 H
A0A060JMP6 H
D5V7B3 H
A0A494JB70 H
A0A5M8QF12 H
A0A8G2F3G4 H
J7L3W8 H
G0JRG9 H
D3DJN2 H
A0A1Y2JH43 H
Q1L727 H
A0A7T2S0Z6 H
A0A315S845 H
A0A2S6H6B7 H
A0A1J5NTP7 H
A0A0E3QY86 H
A0A096EEV9 H
A0A380S5X4 H
B8ZYW3 H
A0A2S8GEJ5 H
A0A248TDF2 H
B2GFN1 H
U1PPI7 H
C7LW88 H
G3A431 H
A0A066ZTE4 H
L7CG99 H
S0ET45 H
A0A178TA08 H
H1XV27 H
A0A6M3ZJI1 H
U5DEY6 H
H6LFQ2 H
Q6CRN0 H
A0A4Q2EAG7 H
A0A1J5NNB8 H
E3I393 H
A0A243SC06 H
D4F313 H
W0F0I7 H
A9B874 H
A1D2Y5 H
T2J0N1 H
Q2FQT3 H
A0A075WG29 H
A0A979GQ79 H
A0A381CAY8 H
A0A2G3DSU6 H
A0A168EVK8 H
A0A094W9G3 H
A0A4R3NVT3 H
W0DYY3 H
G8JTW0 E
A0A4P6UIK6 H
I9P003 H
G2T1Y3 H
B8EMQ8 H
I6Z905 H
E0TCV4 H
A3XNG6 H
A0A087MGU4 H
A2BUP4 H
A0A562S8V2 H
A0A495DND0 H
A0A0S2FHD7 H
F3QPR6 H
A0A063Y394 H
F6G5I9 H
A0A323UDG5 H
A0A0G9HEC5 H
B8FDY8 H
Q5KPM5 E
A0A147EQL9 H
A0A854Q6X9 H
C3X1J1 H
A0A5B2V3B9 H
A0A258FS85 H
A0A7T2W1B3 H
A0A060UN76 H
G0JRQ3 H
D5UD26 H
G2ZN72 H
A0AA46Q839 H
A5UJR1 H
L1INN6 H
C1F584 H
C5LAG4 H
A0A2A2MCP3 H
B1Y6V4 H
A0A1G6ABK5 H
A0A6A1TYJ4 H
A0A2T4UWF1 H
V4AP67 H
A0A173R3W6 H
C7NND3 H
B0DFJ4 H
A0A3E2VY88 H
R1EDV9 H
J1L5M8 E
D7G265 H
Q8ERT9 H
I4D6Z9 H
A0A4R6DFU8 H
A0A060URC3 H
D2BIB2 H
F5ISF6 H
A5CRL2 H
A0A6G9XJV9 E
Q59UP8 H
A0A6N4SPH9 H
I0HGY4 H
X5DX97 H
L1J6I4 H
I1DSU5 H
B9L7N1 H
Q1Z4I4 H
Q21CP1 H
A0A165MFD1 H
V4CRP5 H
Q7S5K0 H
A0A071MMV1 H
A0A149RYW7 H
A0A7G5EC77 H
A0A1W2GZ82 H
A0A7U3XVQ4 H
A0A071M4L5 H
U5C2K4 H
A0A248LNW8 H
L8H844 H
A0A149V596 H
S9QZ09 H
B1ZSW9 H
D2BUJ8 H
A0A9Q8L398 H
M5S735 H
Q6ARH0 H
K6W5X0 H
G0JRG6 H
A0A6H9FYW4 H
A0A0S4WFM4 H
A0A101HKN9 H
Q9REX3 H
F0S3Z6 H
A8NAG3 H
C6LBD3 H
A0A149U2G9 H
V4REY8 H
A0A0H3H4I7 H
A8N2H6 E
S0APH6 H
A0A017SYR8 H
A0A1B9MZ78 H
E4T3F3 H
D7E934 H
A0A0M3AB44 H
A9WHW6 H
A0A5M4AUM9 H
A0A1X4GBG2 H
I4D1H5 E
A0A0E3QYF3 H
B0CQX4 E
A0A378YR15 H
A0A495D4X4 H
A0A076PL76 H
Q1YDY7 H
A0A3E2UCG9 H
A0A2K3DPU7 H
A0A3R9Q7C4 H
V5U2Z4 H
K9P718 H
M1V7W3 H
Q6LKC8 H
E5Y789 H
J9Z839 H
A0A1G7VM92 H
K9Z0D3 H
A0A482TED1 H
R1EGK6 H
J1ASR8 H
A0A7U4E420 H
K9YR86 H
A8PXT8 H
A0A0U1NJW3 H
B8FL88 H
A2CCK1 H
D6TFE1 H
A0A2H4U5R1 H
I2GD40 H
A0A060HFT5 H
B1Y842 H
A0A0X8NXA9 H
A0A0A2A5X1 H
A0A318FY98 H
Q7V4T8 H
A0A1A0DHK0 H
C1A872 H
A0A395VB65 H
A7MFK3 H
J4KM12 E
A1SY01 H
A0A1H4DJ49 H
A0A9R0NTP8 H
A3PAY4 H
B4CV94 H
A2C095 H
Q2HD43 E
A0A836M2B6 H
H6RWK9 H
A0A087EQK8 H
A0A1I0AQM4 H
L7CG11 H
A0A248LNK5 H
B7FTM9 H
L0K9M1 H
I4D6Z7 H
A0A2K1RA81 H
Q2WBF7 H
A0A1B9BUU6 H
A0A2S0JW39 H
A0A2S5YID7 H
B3PIH2 H
U3P8G1 H
C9R9J0 H
A8AC17 H
F0YLV7 H
A0A1D3GAE9 H
C1MHX0 H
A0A1H4KAQ7 H
A0A2T4XZC1 H
A1B3N0 H
C7LW87 H
A1SZ12 H
A0A2T2Y0D5 H
A0A1H8D0R8 H
A0A2S5V2F6 H
G3IYW2 H
F5L8M7 H
C7BJG7 H
E4U5Z1 H
A0A1B9K8L2 H
A0A2S5WMT7 H
A0A0D2UPA8 H
A0A161SKF4 H
B4D7W2 H
A0A1H3WA00 H
C1D6X6 H
A0A4D6KHD1 H
Q488X2 H
A9V5W4 H
A0A5M4ATH9 H
E4TRS4 H
A0A011U1K7 H
C7R314 H
A0A077EFU9 H
A0A0A2A0Y9 H
A0A0D8BQX6 H
A0A0L0S493 E
A0A328Q6M1 H
A0A016XCG9 H
B7FSA7 H
G0AFH4 H
A0A177W826 H
A0A2S8GF54 H
Q1YDY8 H
Q5QVH2 H
A3ZT81 H
A0AA35XZV0 H
F4H924 H
K0NJH2 H
A0A1V3SSW1 H
F2AUF4 H
A6DN47 H
W8KM07 H
A0A1X3RP39 H
A0A7S0KKL8 H
A0A318QZ80 H
K8VZC6 H
A0A1B9JZS5 H
A0A2S6GKN5 H
A0A4R2Z2K6 H
H1YCC3 H
E1QIU3 H
A0A8H6MPB9 E
A0A369N7Y3 H
T2IEJ2 H
H5UND3 H
Q1PX09 H
A0A149TSA9 H
F2NGJ8 H
A0A0E3SHQ9 H
Q5FLR6 H
S0EUS1 H
A0A369M386 H
W0DZS7 H
A8MCL4 H
V3ZVE4 H
O26757 H
A0A317FZW2 H
A0A085GI50 H
A1ZGK6 H
G0IYI2 H
A7S731 H
A0A1U9YY82 H
A0A328EMN2 H
A0A8E2UDJ3 H
A0A2S5WUP6 H
A0A8H7P8U1 H
A0A257T7G4 H
B3MX93 H
A0A1G5W0P2 H
D4H2Y7 H
A0A4P8HC89 H
Q7T070 H
F7NPQ3 H
B9SA70 H
Q9M6N7 H
I7ZHW3 H
F4XTK4 H
A4G1J2 H
G7WFX4 H
B8JBH5 H
D9QPC8 H
A0A4R7GKA0 H
R9PMC6 H
A0A0E3LMT4 H
A0A511NGC7 H
E4NS62 H
E4T3F7 H
M0D580 H
J7J5E7 H
B1XZU2 H
A0A366IE34 H
A0A6U2BIY7 H
Q9QXP0 H
A0A424WAH3 H
A0A410K1J5 H
L1IHZ8 H
I8TC71 H
A0A7U8C744 H
A8M670 H
A0A0S4VNK2 H
Q2SIR0 H
A0A5C4RNH5 H
A0A3E0X011 H
A0A0E3SP24 H
E1IF27 H
Q2YBP7 H
A0A2S5WZU0 H
A0A172YBR4 H
A0A0K2STK6 H
A0A2N6JV02 H
F0S0G1 H
A0A1C7EL50 H
Q18PF5 H
A0A1I0C958 H
A0AA35XVN2 H
L8GGA0 H
Q3AP28 H
D0MFE9 H
J9VXX9 H
A0A166IS52 H
F0J7D3 H
W7QG13 H
A4BMY5 H
A6LV49 H
Q1H483 H
A6M3G0 H
E4T0A4 H
A0A3E2UHE6 H
A0A174SD65 H
A0A855EH99 H
C3YB74 H
A0A074KZD8 H
J0S2I0 H
K9WSX4 H
E8RLT5 H
Q2FS34 H
Q3Z7F9 H
Q2S8H9 H
A0A060HN92 H
E6ME92 H
A0A172RYW3 H
L0FU80 H
C8WZE0 H
A0A2S8F4W0 H
A0A2C6C0X3 H
F3ZVV4 H
A0A7R6PER3 H
A0A495WJM6 H
A0A0B4DUR9 H
A0A251YU48 H
A5D4I5 H
A0A2X2C038 H
A0A2A2M8K7 H
D3FBG3 E
A0A2V4EA49 H
D0MFE8 H
Q3B6Q2 H
A0A1B9KID3 H
A0A9J9ES23 H
A0A3N2SFS2 H
Q0VLH1 H
A0A1U9Z147 H
Q0G2T1 H
A6GJF5 H
A0A059XXR1 H
A0A5J6WPP9 H
P41948 H
L1IUV5 H
A0A2W0GQV0 H
Q1K433 H
A0A4Y7XC43 H
D5AU98 H
E1QFA8 H
A0A075WBP9 H
Q0BWD0 H
A0A1Y0HX98 H
A0A098S5Y7 H
Q0I445 H
A0A1E5BXA4 H
A0A2C9CK98 H
G4H971 H
A0A1I0BYN1 H
A0A330GB00 H
A0A2S8FR08 H
Q84KJ6 H
A0A2S5WGI8 H
M2ALH9 H
A0A2K3DQF8 H
A0A8G2IZM3 H
F5Y3C1 H
A0A370FPU0 H
F5RGM7 H
A0A4R4K1P9 H
R8VWI7 H
A0A0A2AMW2 H
Q7Z1M1 H
A0A414NWT8 H
A0A0P6VSR8 H
A0A0L0TDW1 H
U3PCH5 -
W7QGE0 H
C5BWX7 H
A0A1B9M1A9 H
B8GGC3 E
D6SPD1 H
A0A0H3DR67 H
A0A4R7VEK0 H
G4R7P1 H
A0A1M5ZVP9 H
A0A2S5Y0D3 H
I0ICG0 H
D0L8H3 H
A0A1B9LFW3 H
Q6ND34 H
A0A6H9GWG4 H
Q5UZ98 H
A0A2S0P9T4 H
H2CDR5 H
T2KGT3 H
A0A088E6Q7 H
A0A258HS77 H
E1V4T3 H
B7GKP4 H
Q9QUT0 H
I3Z3H7 H
G7WCB6 H
A0A1Y6GLJ1 H
A0A0S2DQB6 H
Q6CRN1 H
A0A401X433 H
A7HT14 H
A0A009TDB1 H
D4XSW0 H
B0SRS8 H
A0A149QSR6 H
B1Y0E5 H
Q7UGU7 H
A0A2S0Q8P1 H
F0ZPL3 H
A0A2T0GTU1 H
I4CCD1 H
A0A9Q6P4A5 H
A0A418VIJ8 H
C1MX19 H
A0A1B9BUZ8 H
K9W6F3 H
Q1K8A3 H
L8GFX3 H
A0A1G6ABL9 H
A0A087L0B9 H
A0A073CP02 H
A0A0A1ZJU5 H
A0A258HPP1 H
A0A149QAW7 H
D2V6Q5 H
A0A1X4G8K1 H
A0A067Z3S3 H
A0A8F5ZDT8 H
A0A854QN45 E
A0A2N7LCD7 H
G7WFX2 H
A0A7S4GNJ2 H
A4G0C5 H
A6VE60 H
A0A1S1HM83 H
A0A037ZJY5 H
N1WR17 H
Q2W5V2 H
A1VIM5 H
A0A1Y5E3E3 H
A0A1T4SFK4 H
A7RNC3 H
M7XJ51 H
A0A399T909 H
A0A2N6P374 H
H8L2Q4 H
D5EP68 H
E6SF19 H
A0A1T4SFY6 H
D3LBI0 H
E6W5C1 H
Q0VPH4 H
K9WT03 H
L0KW14 H
A0A4R8H081 H
A0A1B9N3H7 H
B0RC35 H
A0A420KGW4 H
A0A4R3NLV5 H
Q47K18 H
Q21P82 H
M1WRK6 H
A0A290XBB5 H
A0A6T9XUR2 H
A0A1J1JH03 H
I3R0S7 H
A9UR54 H
A0A1G7H8X3 H
A0A8G2F718 H
Q1H0G2 H
D0LAL7 H
C7LQR9 H
A0A1G5PWV0 H
K1K628 H
B9SXC7 H
G7WA28 E
Q1IWN6 H
H6LKH9 E
A0A1H7CU41 H
G8JUJ2 H
A0A081N2G5 H
A0A074ME37 H
Q0VQH6 H
C8XB51 H
A1VIG8 H
Q8GQS1 H
A0A1I7FBM5 H
A0A1M6ZMI3 H
A0A482PLH3 H
A0RXK8 H
D0KXQ0 H
Q8JI14 H
A0A7T4WEP4 H
A0A4R3ZNW3 H
A0A074KY88 H
A0A6M3ZKU5 H
M1SJL5 H
A0A1W9KSU5 H
E3GI40 H
A0A369NYJ2 H
A0AA92K392 H
O04161 H
A9BQZ4 H
A0A6N2Z556 H
A0A8H6NAG3 E
A0A2T9X1V4 H
Q2J376 H
A0A0F5EZP7 H
A0A7G5DK18 H
M9YAI9 H
D2ZRW2 H
G7UUY6 H
A0A8H4GS02 H
A0A2T5IHP0 H
A0A165MAC2 H
A0A7S4LPS8 H
A0A075JIN0 H
C8X554 H
B8FZP7 H
Q5KAF6 H
A0A427KNL6 H
A0A7G5DPV0 H
Q22947 H
A0A1S1HRJ0 H
A0A3N1VXY4 H
A0A2S7YPJ9 E
I0JI83 H
A0A7U3YMN6 H
Q9BLG3 H
A0A1H9RTW8 H
A0A1I4W3A0 H
A0A0B4M163 H
U2EN72 H
A0A2W5VAZ2 H
E4YA63 H
D5ELM4 H
M9RJS5 H
A0A2G3E8V2 H
Q5FSX6 H
I0HKQ8 H
A0A833H2R7 H
B8ENL9 H
B3DUX7 H
A0A1D8UWJ6 H
D5E995 H
A0A7U8C2Y6 H
L0KGR8 H
B0VMH1 H
P40260 E
L0JT30 H
C1GR74 E
A0A423Y4I6 H
A0A4P7UHQ5 H
A0A8E2R1Y5 H
I5BYV5 H
A0A6B8N021 H
A0A7G5DPV1 H
A0A2G5RQK9 H
A0A5M4B0G1 H
A0A6S5K4J1 H
C1D4X0 H
A1SVA8 H
H1YF74 H
A0A8B4RWH8 H
A0A0A0D6K5 H
A0A0A2BBY0 H
A0A089ZBW5 H
A0A068TC78 H
Q46G49 H
A1CQ21 H
A0A1G6ABX1 H
E1SLM7 H
K5CFE5 H
Q2YLQ6 H
Q0G2V0 H
A4ABK3 H
A0A9Q5QVI9 H
A0A4Q7Y9I7 H
A9HMD6 H
K9YN27 H
Q9UBD6 H
D9SI59 H
Q8I0L6 H
A0A142VAD6 H
G3IYW0 H
A0A062IU58 H
R1D1H4 H
A0A366XFS8 H
A0A7S4GNF3 H
F0J6E8 E
A0A7U4DN04 H
V4RHR4 H
F7ZJM0 H
A0A2S5XAB8 H
U5C4L4 H
Q21J04 H
A0A142NNN1 H
H1Y7T6 H
F5R974 H
B0DU91 E
A2BP62 H
A7HSN9 H
A0A377I7W9 H
D2RU19 H
G7WJN0 H
E2SD33 H
A0A0D7F2Y9 H
A0AA92EGF5 H
A0A9E9LXV9 H
A4BEP1 H
A0A0E3WZH5 H
F7ZEU9 H
A5E3X2 H
A0A0A3XTJ3 H
A0A830ZZN8 H
A0A1S8D478 H
J7IVQ1 H
A0A2U1SS17 H
S3K1S2 H
C6XKC2 H
A0A2S7YIM5 H
K2IMJ7 H
Q5P1S8 H
A0A7T5BFQ2 H
A0A556SRH6 H
A8P923 H
A0A7G5DKA9 H
L8JUH3 H
A0A0D2LEF5 E
A0A258FTB0 H
A0A5P9P1L2 H
M8E0R3 H
A0A6J5IRX5 H
W5WIX6 H
Q82X47 H
I4DBY0 H
A0A6F8TLE9 H
A0A1G7UZX2 H
A0A6P4JM51 H
G0J614 H
U2WTW8 H
A0A642KQG8 H
Q1AUG3 H
A0A6G9Y3Q0 H
B8J5X4 H
M7NFH3 H
A0A0E3R6S1 H
Q2IHY5 H
A7I8Z2 H
L1IYP4 H
B4HDZ9 H
A0A366WYI9 H
E4TJ50 H
A0A7S0ILH2 H
A4BAE1 H
B3QRJ4 H
A0A5C5BWI6 H
Q7NQY2 H
A0A091AXI3 H
Q1QSQ2 H
R4FZE3 H
A0A2N0MZ27 H
A9BTK1 H
A0A242NIL1 H
G0LFE3 H
A0A1B9NQ91 H
A0A5M5PZE2 H
A0A0D2NYP3 H
D9QPE5 H
I5B3H0 H
L1IYW7 H
C6WEW7 H
B7FW68 H
F4GED5 H
A0A4R8GSH7 H
A0A1W2H3F0 H
A0A3E2T713 H
A0A0H3KTD3 H
A0A1Y4LM49 H
G2PRJ6 H
A0A0X8X7Y7 H
K8EJ02 H
A0A1L3F1X5 H
G8TK77 H
A0A855F5Y8 H
A0A975BTN0 H
A0A562RGZ4 H
G5EB09 E
A0A833LX85 H
U1H1F7 H
K8W1E2 H
E3HJW8 H
Q7SEH0 E
Q47X17 H
B0DXT9 E
A0A3G9G2C9 H
Q95P70 H
A0A837C6X5 H
Q89WR5 H
A6DUG4 H
D7UQE2 H
A0A2I1M481 H
A0A0T7GZ59 H
O66395 H
J3EXK0 H
A0A1B9MYL7 H
K9U8C7 H
E2SD44 H
H6LKH6 H
Q605Y6 H
A0A9Q9D9I3 H
A0A6N2TIA4 H
A0A1E3PQH0 H
A4CMI3 H
Q1K0H9 H
A0A0S6UEK9 H
A0A0H3LUA3 H
B9LU00 H
A9BIZ7 H
A0A7H8UK07 H
E3H8C9 H
M2A398 H
Q1QS12 H
G0VI62 H
A0A1Z3MS36 H
A0A0B5FNH4 H
D9SI36 H
A0A410JZR4 H
F7ZJZ1 H
F0ZCX7 H
W0DZX1 H
A0A4R3ZZ35 H
A0A317G0I6 H
Q0ARJ4 H
A7I8Z4 E
T2KJ59 H
I3C0V3 H
E3H8A6 H
B2IJT1 H
A0A2G6JLT9 H
A3ZZL7 H
A0A2T0XPP2 H
Q31CR9 H
A0A1R1IDV3 H
K2JVF8 H
V5BYZ7 H
D8J4C6 H
D4H5F9 H
K9ZG59 H
A0AA86YS65 H
Q608B6 H
A0A562BXM4 H
A0A401WXG0 H
A0A857DMN9 H
A0A1X6N3Q5 H
A0A173R3X4 H
Q63EK5 H
K9ZLY2 H
A0A533I6R2 H
I0WJ97 H
K0N2R5 H
M0J579 H
B8GGC1 H
A0A6H9GFU4 H
C6CBB1 H
A0A510HHK8 H
A0A1B9MBX6 H
A0A9Y2AG30 H
E8RSE4 H
F2B2B8 H
Q7UYZ3 H
I1YJH7 H
A0A853MG28 H
A0A0L0STS6 E
A0A251XU71 H
Q60BI2 H
A0A829X098 H
F3KUN4 H
Q60C43 H
A0A0T7FAP8 H
A0A3E2TW06 H
W0E077 H
A0KPE9 H
R7PZ71 H
A0A0A1ZMZ9 H
A0AA40J491 H
D3S2L0 H
A0A373FQ71 H
A0A0A2C6L1 H
Q7W7D3 H
A0A165K0X5 H
A0A2S5X482 H
R9GM11 H
Q0G0A3 H
D4GLQ6 H
E7RJZ0 H
F8IJE0 H
A0A1V2XMU9 H
Q7TNN9 H
A0A1G5RZU9 H
A0A2N6K4Y5 H
B0SLB7 H
A0A251YFS0 H
B9WDK0 E
Q7N0M6 H
A0A0M2LU39 H
F4B548 H
D6Z5V9 H
A0A4R2M206 H
A0A1E2SKM1 -
A0A127JTU2 H
A0A212AV03 H
G4QHD2 H
A0A021VMC6 H
A0A2J7TJ33 H
G7WDB5 H
Q6BK68 H
Q1K3N8 H
A0AA91Q161 E
A0NJ07 H
A0A316BQ38 H
A0A377PLP5 H
W7QGM4 H
A0A015YIP3 H
A0A060UWC8 H
A0A1I4ZIZ6 H
A0A264VQM8 H
A9AUR8 H
A0A1W5PRD1 H
A0A0E3BR91 H
A0A1B0ZRL8 H
B9ACS5 H
Q92BJ7 H
F2JTN3 H
A1AVV2 H
D2Q0J8 H
A0A3S9N9F3 H
A8ZQD5 H
C3X831 H
A0A1M6BPM0 H
A0A8F5VN39 H
A0A1E5C7W4 H
A0A2S5WV24 H
A0A833GZR2 H
C7M2A9 H
A6W7U2 H
W0JIB3 H
Q07UM3 H
A0A066ZRQ5 H
S0G181 H
D3PAH1 H
Q4WHC6 E
A0AA94HTL8 H
D5ASL9 H
A0A4U1JNL6 H
M0MDP9 H
A0A653N397 H
A0A2S8GSU9 H
A0A097R891 H
A0A8H7U3I1 E
A0A1H1MB73 H
A0A016XDZ5 H
A0A1B9JHS5 H
D3PE53 H
A0A9J9BAE8 H
Q2RM12 H
A0A3N0AQL8 H
C5KTM6 H
M1P5F0 H
I1YG38 H
A0A660CH85 H
A0A2N7L7C8 H
Q5KZZ9 H
M1NZT5 H
A0A225CMT8 H
A0A068NV61 H
H2CJI0 H
B0DU93 E
Q221S8 H
F4Y3C5 H
Q94CJ2 H
M0D3Q9 H
A0A3P2A7W8 H
C0GKN4 H
Q7T3R4 H
A0A562USB9 H
A2SS52 H
A0A211ZGL5 H
A0A4V3ALP8 H
A0A147GP06 H
H2IZ00 H
Q45HK8 H
A0A6C8LST1 H
A0A257T8W6 H
Q5P470 H
I5AZQ4 H
Q07UM1 H
E5B358 H
A0A1Y4L5P0 H
Q3AFY9 H
B0BZN3 H
A0A1Q2C7H7 H
A0A4R5U5V1 H
H6LKX6 H
A0A1Y0UZX2 H
F6BEI0 H
M9RKT6 H
A7SGD4 H
A0A257TE48 H
R1FI09 H
E4N1T5 E
U1PIR6 H
F2JYR9 H
Q84KJ7 H
A0A2S8FTB5 H
D2R647 H
G9Y5B0 H
A0A144NLT9 H
A0A5J6WQU1 H
D2R355 H
F3ZYD6 H
B0SL05 H
A0A5A7MAJ9 H
A0A977NL43 H
A0A433ZQ80 H
A0A1Y0V4A5 H
A0A1M7UEG2 H
G8R7U9 H
K1LDP0 H
B7G0Y4 H
A0A2W4ZXC0 H
B3PF77 H
Q2KZK9 H
Q18ES8 H
D3F545 H
B4S394 H
Q1Q357 H
Q9H310 H
D3PKL4 H
M5SY07 H
Q8RUT6 H
A7NKH2 H
Q1Q879 H
A0A1B9M5B8 H
A6LRS5 E
J2ZGN6 H
V5E0F3 H
A0A149RQX0 H
A0A165BP25 H
C0QSY0 H
B0XVV6 E
E0SD83 H
A8HSA2 H
A0A1E3PSK5 E
A5DYQ2 E
A0A4U1K1W1 H
Q0AT01 H
A4FMG0 H
C3YB73 H
A0A9P3CXY2 H
A0A0L8BVU4 H
A0A401WUW1 H
I4C9L2 H
Q8RUE9 H
F0JGZ1 H
A0A2I0UUY1 H
A0A542XGT4 H
G0JRH4 H
A2SPS8 H
A0A5M4AWD2 H
Q6QH01 H
D3F0Z1 H
A6XBM2 H
D6E7B3 H
Q13E03 H
A0A060URB8 H
A0A2T1N7R1 H
D6TCH6 H
B0CXH8 H
A3TVQ9 H
Q4WT12 H
C7QGX3 H
F0Y9X3 H
A0A7S0D560 H
A0A160KTE9 H
A0A2H1HV86 H
A0A251Y3N4 H
A0A419AVL2 H
A0A4Q2QWS1 H
C7Q1E4 E
A0A5C5TYS5 H
F2NNQ0 H
A0A2R4TRE0 H
K9YJQ3 H
D9QS43 H
A7SQ16 H
A1DG05 E
U1SIR9 H
C4Y298 E
A0A9W3LFI9 H
D3RMV7 H
F3QNA7 H
E4RTK5 H
C8XBX8 H
C0QTA4 H
E6VIW4 H
A0A2S6H643 H
Q46HB1 H
A0A2S5CTX8 H
A0A1T4SF40 H
K0K7J4 H
A0A1J5JH24 H
Q6LMI6 H
A0A9W5JBA9 H
A0A291PMC6 H
A0A4Y4DZN4 H
A0A2R4MBA2 H
R9PI53 H
A0A6H9GLV4 H
A0A7S4GND2 H
A0A6H9FPY5 H
A0A1G7DX68 H
A0A075WEB4 H
A0A140NHJ5 H
A0A1C6Z081 H
Q5FA36 H
Q0ACK1 H
A0A975GIX9 H
A0A323UE08 H
U7VB41 H
A0A063Y780 H
C5CIT6 H
A0A0A2VPU3 H
F0RHS0 H
A0A2S5WX34 H
C1G973 E
A0A2S6GKF6 H
A0A0A2B651 H
A0A4R3A5P7 H
A0A2A7U6W1 H
Q2GX26 H
F5XN43 H
A0A0K2STH0 H
A0A1H1U2Q6 H
A7SED8 H
A0LV78 H
K5DBA0 H
B8IZX4 H
A8LKQ0 H
A0A5C6LWQ1 H

In [156]:
seqh2 = []

for i in h2:
    print(i.id, i.seq)
    seqh2.append(i.seq)

A0A858ZNJ3 H
A0A1H9M798 H
B0DY50 H
P69680 H
A0A3G9G4Q4 H
A0A149UP06 H
F2G6G4 H
A0A2M9D7S8 H
A0A034WGQ2 H
I0KDC6 H
F8D7H6 H
K9W4V5 H
Q466Y3 H
D2SE15 H
A0A377PBY1 H
B1JZ69 H
A0A2W5HTC3 H
A8G2S3 H
D5T4N9 H
Q2RWY7 H
A0A0E3R4G0 H
I4C9L0 H
D5VJ32 H
C0Z5S5 H
C1N6X9 H
J7ITF6 H
A0A068SVR1 H
A0A0D7F328 H
Q0G0A4 H
F0J3F9 H
Q0BQ69 H
F2YIC4 H
D4XLN6 H
A0A420WC79 H
A0A5C5TUT2 H
A0RUZ2 H
A0A0A2ZRL7 H
J4UGB7 H
E5Y678 H
A0A0D2KGN8 H
S5ABR8 H
A9DQM8 H
G5EB13 H
A0A2N6NEK4 H
C6DB68 H
Q81GN5 H
Q0F2M5 H
A0A0C6P439 H
B9SWW9 H
L8H5K0 H
Q9NIV0 H
C1N5A7 H
Q1JXS5 H
A0A1M6JKY3 H
F4D1J0 H
A0A257SYX3 H
V4RK08 H
G0V8D6 H
A0A7S4GMD8 H
B3QVV5 H
F2JZ83 H
A0A857DDJ7 H
A0A0S6UHP2 H
D5EP71 H
F4KY49 H
M5S9B4 H
A0A009PYN3 H
A0A3T0SZ22 H
A0A248LMH8 H
A0A6H9GEE4 H
A7HSP2 H
A0A7V8IKS6 H
T2JFS5 H
F6FRU9 H
A0A9E9L9J1 H
A0AIW5 H
A0A0E9NHV4 H
Q2N625 H
C8WSI9 H
A0A1H1BPD6 H
A0A176XNC5 H
A0A4V0XUI3 H
A7S3L2 H
M5U2P1 H
K9P5D1 H
Q0F2M7 H
A0A2R3IMJ8 H
Q2RVB5 H
A0A556RTU3 H
E0TGP9 H
B7G0Y1 H
A0A1G9P6Q0 H
D0LTW3 H
Q6BT62 H
Q2IK04 H
Q6BJI7 H
B7X047 H
A0A068NPW2 H
A0A399NT81 H
K0F9X7 H
A0A037ZMW1 H
A0A075JZ35 H
A0A369MHK2 H
A0A1B9JPL5 H
D8PD01 H
A0A2G5BI87 H
A0A2G5BGA9 H
A0A657K391 H
P69681 H
A0A4P6UIJ8 H
A0A0V8M0W6 H
A0A0H2XSU4 H
Q1Z695 H
A0A7Z0V0A4 H
K0ER80 H
A0A149UWF2 H
G0H0Z6 H
G0EFF3 H
C8WLL8 H
X5CNT2 H
A0A4Y1MSE7 H
H2CLF7 H
M4VEJ9 H
A0A4V2X6C2 H
A0A2K1RA77 H
A0A375YPN6 H
A0A7M6UUM4 H
A0A172YCA7 H
A0A918MJ52 H
A0A2S8QA29 H
A0A251XJT0 H
A0A0B4E6X7 H
A0A0K2STQ7 H
A1C5Z7 H
C9KKP2 H
A0A2Z4MD56 H
Q9VFA9 H
A0A502GPV4 H
I5C044 H
D2V6P8 H
D3RN22 H
Q97L80 H
A0A0D5YN10 H
A0A1I5GN22 H
A0A1Y5E8I7 H
B1Y8C9 H
M5SYZ1 H
Q6HM26 H
A0A379A0S9 H
A0A101DCS3 H
A0A1Y3U5V2 H
A0A202B535 H
F8E6R1 H
Q6ND36 H
A0A8H6K7L7 H
Q7NCB8 H
A0A369MRW6 H
C9RS76 H
A3U857 H
A0A127PIQ9 H
B8FGW0 H
A0A060JMP6 H
D5V7B3 H
A0A494JB70 H
A0A5M8QF12 H
A0A8G2F3G4 H
J7L3W8 H
G0JRG9 H
D3DJN2 H
A0A1Y2JH43 H
Q1L727 H
A0A7T2S0Z6 H
A0A315S845 H
A0A2S6H6B7 H
A0A1J5NTP7 H
A0A0E3QY86 H
A0A096EEV9 H
A0A380S5X4 H
B8ZYW3 H
A0A2S8GEJ5 H
A0A248TDF2 H
B2GFN1 H
U1PPI7 H
C7LW88 H
G3A431 H
A0A066ZTE4 H
L7CG99 H
S0ET45 H
A0A178TA08 H
H1XV27 H
A0A6M3ZJI1 H
U5DEY6 H
H6LFQ2 H
Q6CRN0 H
A0A4Q2EAG7 H
A0A1J5NNB8 H
E3I393 H
A0A243SC06 H
D4F313 H
W0F0I7 H
A9B874 H
A1D2Y5 H
T2J0N1 H
Q2FQT3 H
A0A075WG29 H
A0A979GQ79 H
A0A381CAY8 H
A0A2G3DSU6 H
A0A168EVK8 H
A0A094W9G3 H
A0A4R3NVT3 H
W0DYY3 H
G8JTW0 H
A0A4P6UIK6 H
I9P003 H
G2T1Y3 H
B8EMQ8 H
I6Z905 H
E0TCV4 H
A3XNG6 H
A0A087MGU4 H
A2BUP4 H
A0A562S8V2 H
A0A495DND0 H
A0A0S2FHD7 H
F3QPR6 H
A0A063Y394 H
F6G5I9 H
A0A323UDG5 H
A0A0G9HEC5 H
B8FDY8 H
Q5KPM5 H
A0A147EQL9 H
A0A854Q6X9 H
C3X1J1 H
A0A5B2V3B9 H
A0A258FS85 H
A0A7T2W1B3 H
A0A060UN76 H
G0JRQ3 H
D5UD26 H
G2ZN72 H
A0AA46Q839 H
A5UJR1 H
L1INN6 H
C1F584 H
C5LAG4 H
A0A2A2MCP3 H
B1Y6V4 H
A0A1G6ABK5 H
A0A6A1TYJ4 H
A0A2T4UWF1 H
V4AP67 H
A0A173R3W6 H
C7NND3 H
B0DFJ4 H
A0A3E2VY88 H
R1EDV9 H
J1L5M8 H
D7G265 H
Q8ERT9 H
I4D6Z9 H
A0A4R6DFU8 H
A0A060URC3 H
D2BIB2 H
F5ISF6 H
A5CRL2 H
A0A6G9XJV9 H
Q59UP8 H
A0A6N4SPH9 H
I0HGY4 H
X5DX97 H
L1J6I4 H
I1DSU5 H
B9L7N1 H
Q1Z4I4 H
Q21CP1 H
A0A165MFD1 H
V4CRP5 H
Q7S5K0 H
A0A071MMV1 H
A0A149RYW7 H
A0A7G5EC77 H
A0A1W2GZ82 H
A0A7U3XVQ4 H
A0A071M4L5 H
U5C2K4 H
A0A248LNW8 H
L8H844 H
A0A149V596 H
S9QZ09 H
B1ZSW9 H
D2BUJ8 H
A0A9Q8L398 H
M5S735 H
Q6ARH0 H
K6W5X0 H
G0JRG6 H
A0A6H9FYW4 H
A0A0S4WFM4 H
A0A101HKN9 H
Q9REX3 H
F0S3Z6 H
A8NAG3 H
C6LBD3 H
A0A149U2G9 H
V4REY8 H
A0A0H3H4I7 H
A8N2H6 H
S0APH6 H
A0A017SYR8 H
A0A1B9MZ78 H
E4T3F3 H
D7E934 H
A0A0M3AB44 H
A9WHW6 H
A0A5M4AUM9 H
A0A1X4GBG2 H
I4D1H5 H
A0A0E3QYF3 H
B0CQX4 H
A0A378YR15 H
A0A495D4X4 H
A0A076PL76 H
Q1YDY7 H
A0A3E2UCG9 H
A0A2K3DPU7 H
A0A3R9Q7C4 H
V5U2Z4 H
K9P718 H
M1V7W3 H
Q6LKC8 H
E5Y789 H
J9Z839 H
A0A1G7VM92 H
K9Z0D3 H
A0A482TED1 H
R1EGK6 H
J1ASR8 H
A0A7U4E420 H
K9YR86 H
A8PXT8 H
A0A0U1NJW3 H
B8FL88 H
A2CCK1 H
D6TFE1 H
A0A2H4U5R1 H
I2GD40 H
A0A060HFT5 H
B1Y842 H
A0A0X8NXA9 H
A0A0A2A5X1 H
A0A318FY98 H
Q7V4T8 H
A0A1A0DHK0 H
C1A872 H
A0A395VB65 H
A7MFK3 H
J4KM12 H
A1SY01 H
A0A1H4DJ49 H
A0A9R0NTP8 H
A3PAY4 H
B4CV94 H
A2C095 H
Q2HD43 H
A0A836M2B6 H
H6RWK9 H
A0A087EQK8 H
A0A1I0AQM4 H
L7CG11 H
A0A248LNK5 H
B7FTM9 -
L0K9M1 H
I4D6Z7 H
A0A2K1RA81 H
Q2WBF7 H
A0A1B9BUU6 H
A0A2S0JW39 H
A0A2S5YID7 H
B3PIH2 H
U3P8G1 H
C9R9J0 H
A8AC17 H
F0YLV7 H
A0A1D3GAE9 H
C1MHX0 H
A0A1H4KAQ7 H
A0A2T4XZC1 H
A1B3N0 H
C7LW87 H
A1SZ12 H
A0A2T2Y0D5 H
A0A1H8D0R8 H
A0A2S5V2F6 H
G3IYW2 H
F5L8M7 H
C7BJG7 H
E4U5Z1 H
A0A1B9K8L2 H
A0A2S5WMT7 H
A0A0D2UPA8 H
A0A161SKF4 H
B4D7W2 H
A0A1H3WA00 H
C1D6X6 H
A0A4D6KHD1 H
Q488X2 H
A9V5W4 H
A0A5M4ATH9 H
E4TRS4 H
A0A011U1K7 H
C7R314 H
A0A077EFU9 H
A0A0A2A0Y9 H
A0A0D8BQX6 H
A0A0L0S493 H
A0A328Q6M1 H
A0A016XCG9 H
B7FSA7 H
G0AFH4 H
A0A177W826 H
A0A2S8GF54 H
Q1YDY8 H
Q5QVH2 H
A3ZT81 H
A0AA35XZV0 H
F4H924 H
K0NJH2 H
A0A1V3SSW1 H
F2AUF4 H
A6DN47 H
W8KM07 H
A0A1X3RP39 H
A0A7S0KKL8 H
A0A318QZ80 H
K8VZC6 H
A0A1B9JZS5 H
A0A2S6GKN5 H
A0A4R2Z2K6 H
H1YCC3 H
E1QIU3 H
A0A8H6MPB9 H
A0A369N7Y3 H
T2IEJ2 H
H5UND3 H
Q1PX09 H
A0A149TSA9 H
F2NGJ8 H
A0A0E3SHQ9 H
Q5FLR6 H
S0EUS1 H
A0A369M386 H
W0DZS7 H
A8MCL4 H
V3ZVE4 H
O26757 H
A0A317FZW2 H
A0A085GI50 H
A1ZGK6 H
G0IYI2 H
A7S731 H
A0A1U9YY82 H
A0A328EMN2 H
A0A8E2UDJ3 H
A0A2S5WUP6 H
A0A8H7P8U1 H
A0A257T7G4 H
B3MX93 H
A0A1G5W0P2 H
D4H2Y7 H
A0A4P8HC89 H
Q7T070 H
F7NPQ3 H
B9SA70 H
Q9M6N7 H
I7ZHW3 H
F4XTK4 H
A4G1J2 H
G7WFX4 H
B8JBH5 H
D9QPC8 H
A0A4R7GKA0 H
R9PMC6 H
A0A0E3LMT4 H
A0A511NGC7 H
E4NS62 H
E4T3F7 H
M0D580 H
J7J5E7 H
B1XZU2 H
A0A366IE34 H
A0A6U2BIY7 H
Q9QXP0 H
A0A424WAH3 H
A0A410K1J5 H
L1IHZ8 H
I8TC71 H
A0A7U8C744 H
A8M670 H
A0A0S4VNK2 H
Q2SIR0 H
A0A5C4RNH5 H
A0A3E0X011 H
A0A0E3SP24 H
E1IF27 H
Q2YBP7 H
A0A2S5WZU0 H
A0A172YBR4 H
A0A0K2STK6 H
A0A2N6JV02 H
F0S0G1 H
A0A1C7EL50 H
Q18PF5 H
A0A1I0C958 H
A0AA35XVN2 H
L8GGA0 H
Q3AP28 H
D0MFE9 H
J9VXX9 H
A0A166IS52 H
F0J7D3 H
W7QG13 H
A4BMY5 H
A6LV49 H
Q1H483 H
A6M3G0 H
E4T0A4 H
A0A3E2UHE6 H
A0A174SD65 H
A0A855EH99 H
C3YB74 H
A0A074KZD8 H
J0S2I0 H
K9WSX4 H
E8RLT5 H
Q2FS34 H
Q3Z7F9 H
Q2S8H9 H
A0A060HN92 H
E6ME92 H
A0A172RYW3 H
L0FU80 H
C8WZE0 H
A0A2S8F4W0 H
A0A2C6C0X3 H
F3ZVV4 H
A0A7R6PER3 H
A0A495WJM6 H
A0A0B4DUR9 H
A0A251YU48 H
A5D4I5 H
A0A2X2C038 H
A0A2A2M8K7 H
D3FBG3 H
A0A2V4EA49 H
D0MFE8 H
Q3B6Q2 H
A0A1B9KID3 H
A0A9J9ES23 H
A0A3N2SFS2 H
Q0VLH1 H
A0A1U9Z147 H
Q0G2T1 H
A6GJF5 H
A0A059XXR1 H
A0A5J6WPP9 H
P41948 H
L1IUV5 H
A0A2W0GQV0 H
Q1K433 H
A0A4Y7XC43 H
D5AU98 H
E1QFA8 H
A0A075WBP9 H
Q0BWD0 H
A0A1Y0HX98 H
A0A098S5Y7 H
Q0I445 H
A0A1E5BXA4 H
A0A2C9CK98 H
G4H971 H
A0A1I0BYN1 H
A0A330GB00 H
A0A2S8FR08 H
Q84KJ6 H
A0A2S5WGI8 H
M2ALH9 H
A0A2K3DQF8 H
A0A8G2IZM3 H
F5Y3C1 H
A0A370FPU0 H
F5RGM7 H
A0A4R4K1P9 H
R8VWI7 H
A0A0A2AMW2 H
Q7Z1M1 H
A0A414NWT8 H
A0A0P6VSR8 H
A0A0L0TDW1 H
U3PCH5 A
W7QGE0 H
C5BWX7 H
A0A1B9M1A9 H
B8GGC3 H
D6SPD1 H
A0A0H3DR67 H
A0A4R7VEK0 H
G4R7P1 H
A0A1M5ZVP9 H
A0A2S5Y0D3 H
I0ICG0 H
D0L8H3 H
A0A1B9LFW3 H
Q6ND34 H
A0A6H9GWG4 H
Q5UZ98 H
A0A2S0P9T4 H
H2CDR5 H
T2KGT3 H
A0A088E6Q7 H
A0A258HS77 H
E1V4T3 H
B7GKP4 H
Q9QUT0 H
I3Z3H7 H
G7WCB6 H
A0A1Y6GLJ1 H
A0A0S2DQB6 H
Q6CRN1 H
A0A401X433 H
A7HT14 H
A0A009TDB1 H
D4XSW0 H
B0SRS8 H
A0A149QSR6 H
B1Y0E5 H
Q7UGU7 H
A0A2S0Q8P1 H
F0ZPL3 H
A0A2T0GTU1 H
I4CCD1 H
A0A9Q6P4A5 H
A0A418VIJ8 H
C1MX19 H
A0A1B9BUZ8 H
K9W6F3 H
Q1K8A3 H
L8GFX3 H
A0A1G6ABL9 H
A0A087L0B9 H
A0A073CP02 H
A0A0A1ZJU5 H
A0A258HPP1 H
A0A149QAW7 H
D2V6Q5 H
A0A1X4G8K1 H
A0A067Z3S3 H
A0A8F5ZDT8 H
A0A854QN45 H
A0A2N7LCD7 H
G7WFX2 H
A0A7S4GNJ2 H
A4G0C5 H
A6VE60 H
A0A1S1HM83 H
A0A037ZJY5 H
N1WR17 H
Q2W5V2 H
A1VIM5 H
A0A1Y5E3E3 H
A0A1T4SFK4 H
A7RNC3 H
M7XJ51 H
A0A399T909 H
A0A2N6P374 H
H8L2Q4 H
D5EP68 H
E6SF19 H
A0A1T4SFY6 H
D3LBI0 H
E6W5C1 H
Q0VPH4 H
K9WT03 H
L0KW14 H
A0A4R8H081 H
A0A1B9N3H7 H
B0RC35 H
A0A420KGW4 H
A0A4R3NLV5 H
Q47K18 H
Q21P82 H
M1WRK6 H
A0A290XBB5 H
A0A6T9XUR2 H
A0A1J1JH03 H
I3R0S7 H
A9UR54 H
A0A1G7H8X3 H
A0A8G2F718 H
Q1H0G2 H
D0LAL7 H
C7LQR9 H
A0A1G5PWV0 H
K1K628 H
B9SXC7 H
G7WA28 H
Q1IWN6 H
H6LKH9 H
A0A1H7CU41 H
G8JUJ2 H
A0A081N2G5 H
A0A074ME37 H
Q0VQH6 H
C8XB51 H
A1VIG8 H
Q8GQS1 H
A0A1I7FBM5 H
A0A1M6ZMI3 H
A0A482PLH3 H
A0RXK8 H
D0KXQ0 H
Q8JI14 H
A0A7T4WEP4 H
A0A4R3ZNW3 H
A0A074KY88 H
A0A6M3ZKU5 H
M1SJL5 H
A0A1W9KSU5 H
E3GI40 H
A0A369NYJ2 H
A0AA92K392 H
O04161 H
A9BQZ4 H
A0A6N2Z556 H
A0A8H6NAG3 H
A0A2T9X1V4 H
Q2J376 H
A0A0F5EZP7 H
A0A7G5DK18 H
M9YAI9 H
D2ZRW2 H
G7UUY6 H
A0A8H4GS02 H
A0A2T5IHP0 H
A0A165MAC2 H
A0A7S4LPS8 H
A0A075JIN0 H
C8X554 H
B8FZP7 H
Q5KAF6 H
A0A427KNL6 H
A0A7G5DPV0 H
Q22947 H
A0A1S1HRJ0 H
A0A3N1VXY4 H
A0A2S7YPJ9 H
I0JI83 H
A0A7U3YMN6 H
Q9BLG3 H
A0A1H9RTW8 H
A0A1I4W3A0 H
A0A0B4M163 H
U2EN72 H
A0A2W5VAZ2 H
E4YA63 H
D5ELM4 H
M9RJS5 H
A0A2G3E8V2 H
Q5FSX6 H
I0HKQ8 H
A0A833H2R7 H
B8ENL9 H
B3DUX7 H
A0A1D8UWJ6 H
D5E995 H
A0A7U8C2Y6 H
L0KGR8 H
B0VMH1 H
P40260 H
L0JT30 H
C1GR74 H
A0A423Y4I6 H
A0A4P7UHQ5 H
A0A8E2R1Y5 H
I5BYV5 H
A0A6B8N021 H
A0A7G5DPV1 H
A0A2G5RQK9 H
A0A5M4B0G1 H
A0A6S5K4J1 H
C1D4X0 H
A1SVA8 H
H1YF74 H
A0A8B4RWH8 H
A0A0A0D6K5 H
A0A0A2BBY0 H
A0A089ZBW5 H
A0A068TC78 H
Q46G49 H
A1CQ21 H
A0A1G6ABX1 H
E1SLM7 H
K5CFE5 H
Q2YLQ6 H
Q0G2V0 H
A4ABK3 H
A0A9Q5QVI9 H
A0A4Q7Y9I7 H
A9HMD6 H
K9YN27 H
Q9UBD6 H
D9SI59 H
Q8I0L6 H
A0A142VAD6 H
G3IYW0 H
A0A062IU58 H
R1D1H4 H
A0A366XFS8 H
A0A7S4GNF3 H
F0J6E8 H
A0A7U4DN04 H
V4RHR4 H
F7ZJM0 H
A0A2S5XAB8 H
U5C4L4 H
Q21J04 H
A0A142NNN1 H
H1Y7T6 H
F5R974 H
B0DU91 H
A2BP62 H
A7HSN9 H
A0A377I7W9 H
D2RU19 H
G7WJN0 H
E2SD33 H
A0A0D7F2Y9 H
A0AA92EGF5 H
A0A9E9LXV9 H
A4BEP1 H
A0A0E3WZH5 H
F7ZEU9 H
A5E3X2 H
A0A0A3XTJ3 H
A0A830ZZN8 H
A0A1S8D478 H
J7IVQ1 H
A0A2U1SS17 H
S3K1S2 H
C6XKC2 H
A0A2S7YIM5 H
K2IMJ7 H
Q5P1S8 H
A0A7T5BFQ2 H
A0A556SRH6 H
A8P923 H
A0A7G5DKA9 H
L8JUH3 H
A0A0D2LEF5 H
A0A258FTB0 H
A0A5P9P1L2 H
M8E0R3 H
A0A6J5IRX5 H
W5WIX6 H
Q82X47 H
I4DBY0 H
A0A6F8TLE9 H
A0A1G7UZX2 H
A0A6P4JM51 H
G0J614 H
U2WTW8 H
A0A642KQG8 H
Q1AUG3 H
A0A6G9Y3Q0 H
B8J5X4 H
M7NFH3 H
A0A0E3R6S1 H
Q2IHY5 H
A7I8Z2 H
L1IYP4 H
B4HDZ9 H
A0A366WYI9 H
E4TJ50 H
A0A7S0ILH2 H
A4BAE1 H
B3QRJ4 H
A0A5C5BWI6 H
Q7NQY2 H
A0A091AXI3 H
Q1QSQ2 H
R4FZE3 H
A0A2N0MZ27 H
A9BTK1 H
A0A242NIL1 H
G0LFE3 H
A0A1B9NQ91 H
A0A5M5PZE2 H
A0A0D2NYP3 H
D9QPE5 H
I5B3H0 H
L1IYW7 H
C6WEW7 H
B7FW68 H
F4GED5 H
A0A4R8GSH7 H
A0A1W2H3F0 H
A0A3E2T713 H
A0A0H3KTD3 H
A0A1Y4LM49 H
G2PRJ6 H
A0A0X8X7Y7 H
K8EJ02 H
A0A1L3F1X5 H
G8TK77 H
A0A855F5Y8 H
A0A975BTN0 H
A0A562RGZ4 H
G5EB09 H
A0A833LX85 H
U1H1F7 H
K8W1E2 H
E3HJW8 H
Q7SEH0 H
Q47X17 H
B0DXT9 H
A0A3G9G2C9 H
Q95P70 H
A0A837C6X5 H
Q89WR5 H
A6DUG4 H
D7UQE2 H
A0A2I1M481 H
A0A0T7GZ59 H
O66395 H
J3EXK0 H
A0A1B9MYL7 H
K9U8C7 H
E2SD44 H
H6LKH6 H
Q605Y6 H
A0A9Q9D9I3 H
A0A6N2TIA4 H
A0A1E3PQH0 H
A4CMI3 H
Q1K0H9 H
A0A0S6UEK9 H
A0A0H3LUA3 H
B9LU00 H
A9BIZ7 H
A0A7H8UK07 H
E3H8C9 H
M2A398 H
Q1QS12 H
G0VI62 H
A0A1Z3MS36 H
A0A0B5FNH4 H
D9SI36 H
A0A410JZR4 H
F7ZJZ1 H
F0ZCX7 H
W0DZX1 H
A0A4R3ZZ35 H
A0A317G0I6 H
Q0ARJ4 H
A7I8Z4 H
T2KJ59 H
I3C0V3 H
E3H8A6 H
B2IJT1 H
A0A2G6JLT9 H
A3ZZL7 H
A0A2T0XPP2 H
Q31CR9 H
A0A1R1IDV3 H
K2JVF8 H
V5BYZ7 H
D8J4C6 H
D4H5F9 H
K9ZG59 H
A0AA86YS65 H
Q608B6 H
A0A562BXM4 H
A0A401WXG0 H
A0A857DMN9 H
A0A1X6N3Q5 H
A0A173R3X4 H
Q63EK5 H
K9ZLY2 H
A0A533I6R2 H
I0WJ97 H
K0N2R5 H
M0J579 H
B8GGC1 H
A0A6H9GFU4 H
C6CBB1 H
A0A510HHK8 H
A0A1B9MBX6 H
A0A9Y2AG30 H
E8RSE4 H
F2B2B8 H
Q7UYZ3 H
I1YJH7 H
A0A853MG28 H
A0A0L0STS6 H
A0A251XU71 H
Q60BI2 H
A0A829X098 H
F3KUN4 H
Q60C43 H
A0A0T7FAP8 H
A0A3E2TW06 H
W0E077 H
A0KPE9 H
R7PZ71 H
A0A0A1ZMZ9 H
A0AA40J491 H
D3S2L0 H
A0A373FQ71 H
A0A0A2C6L1 H
Q7W7D3 H
A0A165K0X5 H
A0A2S5X482 H
R9GM11 H
Q0G0A3 H
D4GLQ6 H
E7RJZ0 H
F8IJE0 H
A0A1V2XMU9 H
Q7TNN9 H
A0A1G5RZU9 H
A0A2N6K4Y5 H
B0SLB7 H
A0A251YFS0 H
B9WDK0 H
Q7N0M6 H
A0A0M2LU39 H
F4B548 H
D6Z5V9 H
A0A4R2M206 H
A0A1E2SKM1 A
A0A127JTU2 H
A0A212AV03 H
G4QHD2 H
A0A021VMC6 H
A0A2J7TJ33 H
G7WDB5 H
Q6BK68 H
Q1K3N8 H
A0AA91Q161 H
A0NJ07 H
A0A316BQ38 H
A0A377PLP5 H
W7QGM4 H
A0A015YIP3 H
A0A060UWC8 H
A0A1I4ZIZ6 H
A0A264VQM8 H
A9AUR8 H
A0A1W5PRD1 H
A0A0E3BR91 H
A0A1B0ZRL8 H
B9ACS5 H
Q92BJ7 H
F2JTN3 H
A1AVV2 H
D2Q0J8 H
A0A3S9N9F3 H
A8ZQD5 H
C3X831 H
A0A1M6BPM0 H
A0A8F5VN39 H
A0A1E5C7W4 H
A0A2S5WV24 H
A0A833GZR2 H
C7M2A9 H
A6W7U2 H
W0JIB3 H
Q07UM3 H
A0A066ZRQ5 H
S0G181 H
D3PAH1 H
Q4WHC6 H
A0AA94HTL8 H
D5ASL9 H
A0A4U1JNL6 H
M0MDP9 H
A0A653N397 H
A0A2S8GSU9 H
A0A097R891 H
A0A8H7U3I1 H
A0A1H1MB73 H
A0A016XDZ5 H
A0A1B9JHS5 H
D3PE53 H
A0A9J9BAE8 H
Q2RM12 H
A0A3N0AQL8 H
C5KTM6 H
M1P5F0 H
I1YG38 H
A0A660CH85 H
A0A2N7L7C8 H
Q5KZZ9 H
M1NZT5 H
A0A225CMT8 H
A0A068NV61 H
H2CJI0 H
B0DU93 H
Q221S8 H
F4Y3C5 H
Q94CJ2 H
M0D3Q9 H
A0A3P2A7W8 H
C0GKN4 H
Q7T3R4 H
A0A562USB9 H
A2SS52 H
A0A211ZGL5 H
A0A4V3ALP8 H
A0A147GP06 H
H2IZ00 H
Q45HK8 H
A0A6C8LST1 H
A0A257T8W6 H
Q5P470 H
I5AZQ4 H
Q07UM1 H
E5B358 H
A0A1Y4L5P0 H
Q3AFY9 H
B0BZN3 H
A0A1Q2C7H7 H
A0A4R5U5V1 H
H6LKX6 H
A0A1Y0UZX2 H
F6BEI0 H
M9RKT6 H
A7SGD4 H
A0A257TE48 H
R1FI09 H
E4N1T5 H
U1PIR6 H
F2JYR9 H
Q84KJ7 H
A0A2S8FTB5 H
D2R647 H
G9Y5B0 H
A0A144NLT9 H
A0A5J6WQU1 H
D2R355 H
F3ZYD6 H
B0SL05 H
A0A5A7MAJ9 H
A0A977NL43 H
A0A433ZQ80 H
A0A1Y0V4A5 H
A0A1M7UEG2 H
G8R7U9 H
K1LDP0 H
B7G0Y4 H
A0A2W4ZXC0 H
B3PF77 H
Q2KZK9 H
Q18ES8 H
D3F545 H
B4S394 H
Q1Q357 H
Q9H310 H
D3PKL4 H
M5SY07 H
Q8RUT6 H
A7NKH2 H
Q1Q879 H
A0A1B9M5B8 H
A6LRS5 H
J2ZGN6 H
V5E0F3 H
A0A149RQX0 H
A0A165BP25 H
C0QSY0 H
B0XVV6 H
E0SD83 H
A8HSA2 H
A0A1E3PSK5 H
A5DYQ2 H
A0A4U1K1W1 H
Q0AT01 H
A4FMG0 H
C3YB73 H
A0A9P3CXY2 H
A0A0L8BVU4 H
A0A401WUW1 H
I4C9L2 H
Q8RUE9 H
F0JGZ1 H
A0A2I0UUY1 H
A0A542XGT4 H
G0JRH4 H
A2SPS8 H
A0A5M4AWD2 H
Q6QH01 H
D3F0Z1 H
A6XBM2 H
D6E7B3 H
Q13E03 H
A0A060URB8 H
A0A2T1N7R1 H
D6TCH6 H
B0CXH8 H
A3TVQ9 H
Q4WT12 H
C7QGX3 H
F0Y9X3 H
A0A7S0D560 H
A0A160KTE9 H
A0A2H1HV86 H
A0A251Y3N4 H
A0A419AVL2 H
A0A4Q2QWS1 H
C7Q1E4 H
A0A5C5TYS5 H
F2NNQ0 H
A0A2R4TRE0 H
K9YJQ3 H
D9QS43 H
A7SQ16 H
A1DG05 H
U1SIR9 H
C4Y298 H
A0A9W3LFI9 H
D3RMV7 H
F3QNA7 H
E4RTK5 H
C8XBX8 H
C0QTA4 H
E6VIW4 H
A0A2S6H643 H
Q46HB1 H
A0A2S5CTX8 H
A0A1T4SF40 H
K0K7J4 H
A0A1J5JH24 H
Q6LMI6 H
A0A9W5JBA9 H
A0A291PMC6 H
A0A4Y4DZN4 H
A0A2R4MBA2 H
R9PI53 H
A0A6H9GLV4 H
A0A7S4GND2 H
A0A6H9FPY5 H
A0A1G7DX68 H
A0A075WEB4 H
A0A140NHJ5 H
A0A1C6Z081 H
Q5FA36 H
Q0ACK1 H
A0A975GIX9 H
A0A323UE08 H
U7VB41 H
A0A063Y780 H
C5CIT6 H
A0A0A2VPU3 H
F0RHS0 H
A0A2S5WX34 H
C1G973 H
A0A2S6GKF6 H
A0A0A2B651 H
A0A4R3A5P7 H
A0A2A7U6W1 H
Q2GX26 H
F5XN43 H
A0A0K2STH0 H
A0A1H1U2Q6 H
A7SED8 H
A0LV78 H
K5DBA0 H
B8IZX4 H
A8LKQ0 H
A0A5C6LWQ1 H

In [157]:
seqsn = []

for i in sn:
    print(i.id, i.seq)
    seqsn.append(i.seq)

A0A858ZNJ3 S
A0A1H9M798 S
B0DY50 S
P69680 S
A0A3G9G4Q4 S
A0A149UP06 S
F2G6G4 N
A0A2M9D7S8 S
A0A034WGQ2 N
I0KDC6 I
F8D7H6 N
K9W4V5 N
Q466Y3 N
D2SE15 S
A0A377PBY1 S
B1JZ69 S
A0A2W5HTC3 S
A8G2S3 N
D5T4N9 S
Q2RWY7 Q
A0A0E3R4G0 N
I4C9L0 S
D5VJ32 S
C0Z5S5 N
C1N6X9 N
J7ITF6 S
A0A068SVR1 S
A0A0D7F328 S
Q0G0A4 S
F0J3F9 S
Q0BQ69 S
F2YIC4 N
D4XLN6 S
A0A420WC79 N
A0A5C5TUT2 S
A0RUZ2 T
A0A0A2ZRL7 S
J4UGB7 S
E5Y678 V
A0A0D2KGN8 S
S5ABR8 N
A9DQM8 N
G5EB13 S
A0A2N6NEK4 S
C6DB68 S
Q81GN5 C
Q0F2M5 N
A0A0C6P439 S
B9SWW9 Q
L8H5K0 N
Q9NIV0 N
C1N5A7 N
Q1JXS5 S
A0A1M6JKY3 S
F4D1J0 S
A0A257SYX3 Q
V4RK08 S
G0V8D6 S
A0A7S4GMD8 N
B3QVV5 V
F2JZ83 N
A0A857DDJ7 S
A0A0S6UHP2 N
D5EP71 T
F4KY49 I
M5S9B4 N
A0A009PYN3 S
A0A3T0SZ22 S
A0A248LMH8 S
A0A6H9GEE4 N
A7HSP2 T
A0A7V8IKS6 S
T2JFS5 N
F6FRU9 S
A0A9E9L9J1 S
A0AIW5 S
A0A0E9NHV4 S
Q2N625 S
C8WSI9 A
A0A1H1BPD6 S
A0A176XNC5 S
A0A4V0XUI3 N
A7S3L2 T
M5U2P1 N
K9P5D1 T
Q0F2M7 S
A0A2R3IMJ8 S
Q2RVB5 S
A0A556RTU3 S
E0TGP9 N
B7G0Y1 N
A0A1G9P6Q0 N
D0LTW3 N
Q6BT62 T
Q2IK04 N
Q6BJI7 S
B7X047 S
A0A068NPW2 S
A0A399NT81 S
K0F9X7 S
A0A037ZMW1 N
A0A075JZ35 S
A0A369MHK2 T
A0A1B9JPL5 S
D8PD01 S
A0A2G5BI87 S
A0A2G5BGA9 S
A0A657K391 S
P69681 S
A0A4P6UIJ8 S
A0A0V8M0W6 T
A0A0H2XSU4 S
Q1Z695 N
A0A7Z0V0A4 S
K0ER80 S
A0A149UWF2 S
G0H0Z6 N
G0EFF3 S
C8WLL8 T
X5CNT2 Q
A0A4Y1MSE7 S
H2CLF7 N
M4VEJ9 V
A0A4V2X6C2 S
A0A2K1RA77 Q
A0A375YPN6 S
A0A7M6UUM4 N
A0A172YCA7 T
A0A918MJ52 N
A0A2S8QA29 S
A0A251XJT0 S
A0A0B4E6X7 S
A0A0K2STQ7 N
A1C5Z7 S
C9KKP2 S
A0A2Z4MD56 N
Q9VFA9 N
A0A502GPV4 S
I5C044 N
D2V6P8 N
D3RN22 N
Q97L80 T
A0A0D5YN10 S
A0A1I5GN22 S
A0A1Y5E8I7 N
B1Y8C9 S
M5SYZ1 N
Q6HM26 C
A0A379A0S9 N
A0A101DCS3 S
A0A1Y3U5V2 T
A0A202B535 S
F8E6R1 N
Q6ND36 S
A0A8H6K7L7 S
Q7NCB8 T
A0A369MRW6 T
C9RS76 N
A3U857 I
A0A127PIQ9 S
B8FGW0 S
A0A060JMP6 S
D5V7B3 N
A0A494JB70 I
A0A5M8QF12 S
A0A8G2F3G4 S
J7L3W8 S
G0JRG9 Q
D3DJN2 S
A0A1Y2JH43 S
Q1L727 N
A0A7T2S0Z6 S
A0A315S845 S
A0A2S6H6B7 T
A0A1J5NTP7 S
A0A0E3QY86 T
A0A096EEV9 S
A0A380S5X4 N
B8ZYW3 N
A0A2S8GEJ5 N
A0A248TDF2 N
B2GFN1 S
U1PPI7 N
C7LW88 N
G3A431 S
A0A066ZTE4 N
L7CG99 N
S0ET45 T
A0A178TA08 N
H1XV27 N
A0A6M3ZJI1 S
U5DEY6 N
H6LFQ2 N
Q6CRN0 S
A0A4Q2EAG7 S
A0A1J5NNB8 N
E3I393 S
A0A243SC06 I
D4F313 S
W0F0I7 I
A9B874 N
A1D2Y5 S
T2J0N1 N
Q2FQT3 S
A0A075WG29 N
A0A979GQ79 I
A0A381CAY8 S
A0A2G3DSU6 N
A0A168EVK8 S
A0A094W9G3 N
A0A4R3NVT3 N
W0DYY3 N
G8JTW0 S
A0A4P6UIK6 S
I9P003 N
G2T1Y3 N
B8EMQ8 S
I6Z905 N
E0TCV4 N
A3XNG6 N
A0A087MGU4 S
A2BUP4 N
A0A562S8V2 S
A0A495DND0 S
A0A0S2FHD7 S
F3QPR6 T
A0A063Y394 S
F6G5I9 S
A0A323UDG5 S
A0A0G9HEC5 S
B8FDY8 S
Q5KPM5 T
A0A147EQL9 S
A0A854Q6X9 S
C3X1J1 S
A0A5B2V3B9 S
A0A258FS85 S
A0A7T2W1B3 S
A0A060UN76 N
G0JRQ3 N
D5UD26 S
G2ZN72 S
A0AA46Q839 I
A5UJR1 S
L1INN6 N
C1F584 N
C5LAG4 N
A0A2A2MCP3 T
B1Y6V4 S
A0A1G6ABK5 N
A0A6A1TYJ4 S
A0A2T4UWF1 S
V4AP67 N
A0A173R3W6 T
C7NND3 N
B0DFJ4 S
A0A3E2VY88 N
R1EDV9 N
J1L5M8 S
D7G265 N
Q8ERT9 N
I4D6Z9 S
A0A4R6DFU8 S
A0A060URC3 Q
D2BIB2 T
F5ISF6 T
A5CRL2 S
A0A6G9XJV9 S
Q59UP8 M
A0A6N4SPH9 N
I0HGY4 S
X5DX97 N
L1J6I4 S
I1DSU5 N
B9L7N1 S
Q1Z4I4 N
Q21CP1 S
A0A165MFD1 N
V4CRP5 N
Q7S5K0 S
A0A071MMV1 S
A0A149RYW7 S
A0A7G5EC77 S
A0A1W2GZ82 N
A0A7U3XVQ4 S
A0A071M4L5 S
U5C2K4 N
A0A248LNW8 N
L8H844 N
A0A149V596 S
S9QZ09 S
B1ZSW9 S
D2BUJ8 S
A0A9Q8L398 S
M5S735 S
Q6ARH0 N
K6W5X0 S
G0JRG6 N
A0A6H9FYW4 S
A0A0S4WFM4 S
A0A101HKN9 N
Q9REX3 N
F0S3Z6 N
A8NAG3 S
C6LBD3 N
A0A149U2G9 S
V4REY8 N
A0A0H3H4I7 S
A8N2H6 S
S0APH6 V
A0A017SYR8 S
A0A1B9MZ78 S
E4T3F3 N
D7E934 N
A0A0M3AB44 S
A9WHW6 N
A0A5M4AUM9 T
A0A1X4GBG2 N
I4D1H5 S
A0A0E3QYF3 N
B0CQX4 S
A0A378YR15 S
A0A495D4X4 N
A0A076PL76 S
Q1YDY7 S
A0A3E2UCG9 N
A0A2K3DPU7 N
A0A3R9Q7C4 S
V5U2Z4 S
K9P718 N
M1V7W3 N
Q6LKC8 N
E5Y789 S
J9Z839 Q
A0A1G7VM92 S
K9Z0D3 S
A0A482TED1 N
R1EGK6 N
J1ASR8 S
A0A7U4E420 I
K9YR86 N
A8PXT8 S
A0A0U1NJW3 N
B8FL88 N
A2CCK1 N
D6TFE1 N
A0A2H4U5R1 S
I2GD40 I
A0A060HFT5 S
B1Y842 N
A0A0X8NXA9 S
A0A0A2A5X1 N
A0A318FY98 S
Q7V4T8 N
A0A1A0DHK0 S
C1A872 T
A0A395VB65 N
A7MFK3 S
J4KM12 S
A1SY01 N
A0A1H4DJ49 N
A0A9R0NTP8 S
A3PAY4 N
B4CV94 S
A2C095 N
Q2HD43 S
A0A836M2B6 S
H6RWK9 S
A0A087EQK8 T
A0A1I0AQM4 N
L7CG11 S
A0A248LNK5 V
B7FTM9 N
L0K9M1 N
I4D6Z7 T
A0A2K1RA81 Q
Q2WBF7 S
A0A1B9BUU6 Q
A0A2S0JW39 N
A0A2S5YID7 S
B3PIH2 T
U3P8G1 S
C9R9J0 S
A8AC17 S
F0YLV7 S
A0A1D3GAE9 S
C1MHX0 V
A0A1H4KAQ7 N
A0A2T4XZC1 S
A1B3N0 S
C7LW87 S
A1SZ12 N
A0A2T2Y0D5 S
A0A1H8D0R8 N
A0A2S5V2F6 T
G3IYW2 S
F5L8M7 N
C7BJG7 S
E4U5Z1 T
A0A1B9K8L2 S
A0A2S5WMT7 S
A0A0D2UPA8 I
A0A161SKF4 S
B4D7W2 S
A0A1H3WA00 S
C1D6X6 V
A0A4D6KHD1 N
Q488X2 N
A9V5W4 N
A0A5M4ATH9 I
E4TRS4 N
A0A011U1K7 S
C7R314 S
A0A077EFU9 I
A0A0A2A0Y9 N
A0A0D8BQX6 N
A0A0L0S493 T
A0A328Q6M1 T
A0A016XCG9 S
B7FSA7 N
G0AFH4 S
A0A177W826 S
A0A2S8GF54 N
Q1YDY8 N
Q5QVH2 N
A3ZT81 N
A0AA35XZV0 T
F4H924 S
K0NJH2 N
A0A1V3SSW1 N
F2AUF4 N
A6DN47 N
W8KM07 N
A0A1X3RP39 S
A0A7S0KKL8 N
A0A318QZ80 N
K8VZC6 S
A0A1B9JZS5 S
A0A2S6GKN5 T
A0A4R2Z2K6 S
H1YCC3 I
E1QIU3 N
A0A8H6MPB9 S
A0A369N7Y3 T
T2IEJ2 N
H5UND3 S
Q1PX09 N
A0A149TSA9 S
F2NGJ8 S
A0A0E3SHQ9 N
Q5FLR6 T
S0EUS1 N
A0A369M386 T
W0DZS7 T
A8MCL4 S
V3ZVE4 N
O26757 S
A0A317FZW2 N
A0A085GI50 S
A1ZGK6 N
G0IYI2 N
A7S731 T
A0A1U9YY82 N
A0A328EMN2 T
A0A8E2UDJ3 S
A0A2S5WUP6 T
A0A8H7P8U1 S
A0A257T7G4 Q
B3MX93 N
A0A1G5W0P2 T
D4H2Y7 N
A0A4P8HC89 S
Q7T070 N
F7NPQ3 S
B9SA70 Q
Q9M6N7 Q
I7ZHW3 S
F4XTK4 N
A4G1J2 S
G7WFX4 T
B8JBH5 S
D9QPC8 S
A0A4R7GKA0 S
R9PMC6 N
A0A0E3LMT4 N
A0A511NGC7 I
E4NS62 N
E4T3F7 T
M0D580 N
J7J5E7 S
B1XZU2 N
A0A366IE34 S
A0A6U2BIY7 N
Q9QXP0 N
A0A424WAH3 S
A0A410K1J5 N
L1IHZ8 S
I8TC71 S
A0A7U8C744 N
A8M670 S
A0A0S4VNK2 S
Q2SIR0 N
A0A5C4RNH5 S
A0A3E0X011 N
A0A0E3SP24 T
E1IF27 A
Q2YBP7 N
A0A2S5WZU0 S
A0A172YBR4 N
A0A0K2STK6 N
A0A2N6JV02 N
F0S0G1 S
A0A1C7EL50 N
Q18PF5 N
A0A1I0C958 N
A0AA35XVN2 S
L8GGA0 S
Q3AP28 S
D0MFE9 T
J9VXX9 S
A0A166IS52 N
F0J7D3 Q
W7QG13 N
A4BMY5 S
A6LV49 T
Q1H483 S
A6M3G0 T
E4T0A4 T
A0A3E2UHE6 N
A0A174SD65 T
A0A855EH99 S
C3YB74 N
A0A074KZD8 N
J0S2I0 N
K9WSX4 N
E8RLT5 S
Q2FS34 S
Q3Z7F9 T
Q2S8H9 N
A0A060HN92 N
E6ME92 T
A0A172RYW3 T
L0FU80 N
C8WZE0 N
A0A2S8F4W0 N
A0A2C6C0X3 S
F3ZVV4 S
A0A7R6PER3 N
A0A495WJM6 I
A0A0B4DUR9 N
A0A251YU48 S
A5D4I5 S
A0A2X2C038 S
A0A2A2M8K7 S
D3FBG3 T
A0A2V4EA49 S
D0MFE8 N
Q3B6Q2 S
A0A1B9KID3 S
A0A9J9ES23 N
A0A3N2SFS2 S
Q0VLH1 N
A0A1U9Z147 V
Q0G2T1 S
A6GJF5 N
A0A059XXR1 Q
A0A5J6WPP9 N
P41948 S
L1IUV5 S
A0A2W0GQV0 S
Q1K433 F
A0A4Y7XC43 S
D5AU98 T
E1QFA8 T
A0A075WBP9 S
Q0BWD0 N
A0A1Y0HX98 S
A0A098S5Y7 N
Q0I445 S
A0A1E5BXA4 N
A0A2C9CK98 T
G4H971 N
A0A1I0BYN1 I
A0A330GB00 S
A0A2S8FR08 S
Q84KJ6 Q
A0A2S5WGI8 T
M2ALH9 N
A0A2K3DQF8 N
A0A8G2IZM3 S
F5Y3C1 S
A0A370FPU0 S
F5RGM7 S
A0A4R4K1P9 S
R8VWI7 N
A0A0A2AMW2 N
Q7Z1M1 N
A0A414NWT8 S
A0A0P6VSR8 S
A0A0L0TDW1 S
U3PCH5 C
W7QGE0 T
C5BWX7 S
A0A1B9M1A9 S
B8GGC3 T
D6SPD1 N
A0A0H3DR67 S
A0A4R7VEK0 S
G4R7P1 N
A0A1M5ZVP9 N
A0A2S5Y0D3 S
I0ICG0 N
D0L8H3 T
A0A1B9LFW3 S
Q6ND34 S
A0A6H9GWG4 N
Q5UZ98 N
A0A2S0P9T4 S
H2CDR5 N
T2KGT3 N
A0A088E6Q7 N
A0A258HS77 S
E1V4T3 N
B7GKP4 N
Q9QUT0 N
I3Z3H7 N
G7WCB6 S
A0A1Y6GLJ1 S
A0A0S2DQB6 S
Q6CRN1 S
A0A401X433 S
A7HT14 N
A0A009TDB1 S
D4XSW0 N
B0SRS8 N
A0A149QSR6 S
B1Y0E5 S
Q7UGU7 N
A0A2S0Q8P1 N
F0ZPL3 N
A0A2T0GTU1 S
I4CCD1 S
A0A9Q6P4A5 S
A0A418VIJ8 S
C1MX19 T
A0A1B9BUZ8 S
K9W6F3 S
Q1K8A3 S
L8GFX3 S
A0A1G6ABL9 S
A0A087L0B9 S
A0A073CP02 N
A0A0A1ZJU5 N
A0A258HPP1 S
A0A149QAW7 S
D2V6Q5 N
A0A1X4G8K1 T
A0A067Z3S3 S
A0A8F5ZDT8 S
A0A854QN45 T
A0A2N7LCD7 N
G7WFX2 M
A0A7S4GNJ2 N
A4G0C5 N
A6VE60 S
A0A1S1HM83 T
A0A037ZJY5 T
N1WR17 N
Q2W5V2 N
A1VIM5 S
A0A1Y5E3E3 T
A0A1T4SFK4 S
A7RNC3 V
M7XJ51 N
A0A399T909 S
A0A2N6P374 S
H8L2Q4 S
D5EP68 N
E6SF19 S
A0A1T4SFY6 S
D3LBI0 N
E6W5C1 N
Q0VPH4 N
K9WT03 T
L0KW14 S
A0A4R8H081 N
A0A1B9N3H7 S
B0RC35 S
A0A420KGW4 S
A0A4R3NLV5 S
Q47K18 S
Q21P82 N
M1WRK6 S
A0A290XBB5 S
A0A6T9XUR2 N
A0A1J1JH03 N
I3R0S7 N
A9UR54 N
A0A1G7H8X3 T
A0A8G2F718 N
Q1H0G2 N
D0LAL7 S
C7LQR9 N
A0A1G5PWV0 S
K1K628 S
B9SXC7 Q
G7WA28 S
Q1IWN6 T
H6LKH9 T
A0A1H7CU41 S
G8JUJ2 S
A0A081N2G5 N
A0A074ME37 S
Q0VQH6 T
C8XB51 S
A1VIG8 S
Q8GQS1 S
A0A1I7FBM5 N
A0A1M6ZMI3 N
A0A482PLH3 S
A0RXK8 T
D0KXQ0 N
Q8JI14 N
A0A7T4WEP4 Q
A0A4R3ZNW3 S
A0A074KY88 N
A0A6M3ZKU5 N
M1SJL5 S
A0A1W9KSU5 S
E3GI40 M
A0A369NYJ2 T
A0AA92K392 S
O04161 N
A9BQZ4 S
A0A6N2Z556 N
A0A8H6NAG3 S
A0A2T9X1V4 S
Q2J376 S
A0A0F5EZP7 S
A0A7G5DK18 S
M9YAI9 S
D2ZRW2 S
G7UUY6 S
A0A8H4GS02 S
A0A2T5IHP0 N
A0A165MAC2 S
A0A7S4LPS8 N
A0A075JIN0 S
C8X554 S
B8FZP7 S
Q5KAF6 S
A0A427KNL6 S
A0A7G5DPV0 S
Q22947 N
A0A1S1HRJ0 S
A0A3N1VXY4 S
A0A2S7YPJ9 S
I0JI83 N
A0A7U3YMN6 S
Q9BLG3 N
A0A1H9RTW8 S
A0A1I4W3A0 S
A0A0B4M163 N
U2EN72 N
A0A2W5VAZ2 S
E4YA63 D
D5ELM4 N
M9RJS5 T
A0A2G3E8V2 N
Q5FSX6 S
I0HKQ8 S
A0A833H2R7 N
B8ENL9 S
B3DUX7 T
A0A1D8UWJ6 S
D5E995 N
A0A7U8C2Y6 N
L0KGR8 S
B0VMH1 S
P40260 S
L0JT30 N
C1GR74 S
A0A423Y4I6 S
A0A4P7UHQ5 S
A0A8E2R1Y5 S
I5BYV5 N
A0A6B8N021 S
A0A7G5DPV1 N
A0A2G5RQK9 N
A0A5M4B0G1 T
A0A6S5K4J1 S
C1D4X0 S
A1SVA8 N
H1YF74 N
A0A8B4RWH8 S
A0A0A0D6K5 S
A0A0A2BBY0 N
A0A089ZBW5 S
A0A068TC78 S
Q46G49 T
A1CQ21 S
A0A1G6ABX1 N
E1SLM7 N
K5CFE5 S
Q2YLQ6 S
Q0G2V0 S
A4ABK3 N
A0A9Q5QVI9 T
A0A4Q7Y9I7 S
A9HMD6 S
K9YN27 N
Q9UBD6 N
D9SI59 S
Q8I0L6 N
A0A142VAD6 T
G3IYW0 T
A0A062IU58 S
R1D1H4 N
A0A366XFS8 T
A0A7S4GNF3 N
F0J6E8 S
A0A7U4DN04 S
V4RHR4 S
F7ZJM0 N
A0A2S5XAB8 S
U5C4L4 N
Q21J04 T
A0A142NNN1 S
H1Y7T6 I
F5R974 N
B0DU91 S
A2BP62 N
A7HSN9 N
A0A377I7W9 S
D2RU19 N
G7WJN0 N
E2SD33 S
A0A0D7F2Y9 S
A0AA92EGF5 S
A0A9E9LXV9 S
A4BEP1 N
A0A0E3WZH5 N
F7ZEU9 N
A5E3X2 T
A0A0A3XTJ3 S
A0A830ZZN8 S
A0A1S8D478 S
J7IVQ1 N
A0A2U1SS17 S
S3K1S2 S
C6XKC2 N
A0A2S7YIM5 S
K2IMJ7 N
Q5P1S8 N
A0A7T5BFQ2 N
A0A556SRH6 S
A8P923 S
A0A7G5DKA9 N
L8JUH3 N
A0A0D2LEF5 S
A0A258FTB0 S
A0A5P9P1L2 N
M8E0R3 N
A0A6J5IRX5 S
W5WIX6 S
Q82X47 N
I4DBY0 S
A0A6F8TLE9 S
A0A1G7UZX2 N
A0A6P4JM51 N
G0J614 N
U2WTW8 N
A0A642KQG8 N
Q1AUG3 N
A0A6G9Y3Q0 S
B8J5X4 N
M7NFH3 N
A0A0E3R6S1 T
Q2IHY5 S
A7I8Z2 S
L1IYP4 S
B4HDZ9 N
A0A366WYI9 N
E4TJ50 S
A0A7S0ILH2 V
A4BAE1 N
B3QRJ4 S
A0A5C5BWI6 T
Q7NQY2 S
A0A091AXI3 S
Q1QSQ2 N
R4FZE3 N
A0A2N0MZ27 S
A9BTK1 S
A0A242NIL1 S
G0LFE3 N
A0A1B9NQ91 S
A0A5M5PZE2 N
A0A0D2NYP3 S
D9QPE5 S
I5B3H0 N
L1IYW7 S
C6WEW7 S
B7FW68 N
F4GED5 S
A0A4R8GSH7 N
A0A1W2H3F0 N
A0A3E2T713 N
A0A0H3KTD3 S
A0A1Y4LM49 N
G2PRJ6 N
A0A0X8X7Y7 N
K8EJ02 T
A0A1L3F1X5 S
G8TK77 I
A0A855F5Y8 S
A0A975BTN0 S
A0A562RGZ4 N
G5EB09 S
A0A833LX85 N
U1H1F7 S
K8W1E2 S
E3HJW8 S
Q7SEH0 S
Q47X17 T
B0DXT9 S
A0A3G9G2C9 S
Q95P70 N
A0A837C6X5 S
Q89WR5 S
A6DUG4 N
D7UQE2 N
A0A2I1M481 S
A0A0T7GZ59 S
O66395 S
J3EXK0 N
A0A1B9MYL7 S
K9U8C7 N
E2SD44 S
H6LKH6 T
Q605Y6 S
A0A9Q9D9I3 S
A0A6N2TIA4 N
A0A1E3PQH0 S
A4CMI3 N
Q1K0H9 N
A0A0S6UEK9 S
A0A0H3LUA3 S
B9LU00 N
A9BIZ7 N
A0A7H8UK07 S
E3H8C9 N
M2A398 S
Q1QS12 S
G0VI62 S
A0A1Z3MS36 S
A0A0B5FNH4 N
D9SI36 N
A0A410JZR4 S
F7ZJZ1 S
F0ZCX7 N
W0DZX1 N
A0A4R3ZZ35 S
A0A317G0I6 N
Q0ARJ4 S
A7I8Z4 S
T2KJ59 N
I3C0V3 N
E3H8A6 N
B2IJT1 S
A0A2G6JLT9 N
A3ZZL7 S
A0A2T0XPP2 N
Q31CR9 N
A0A1R1IDV3 S
K2JVF8 N
V5BYZ7 S
D8J4C6 N
D4H5F9 N
K9ZG59 T
A0AA86YS65 S
Q608B6 N
A0A562BXM4 S
A0A401WXG0 S
A0A857DMN9 S
A0A1X6N3Q5 S
A0A173R3X4 N
Q63EK5 C
K9ZLY2 N
A0A533I6R2 S
I0WJ97 N
K0N2R5 S
M0J579 N
B8GGC1 S
A0A6H9GFU4 S
C6CBB1 S
A0A510HHK8 N
A0A1B9MBX6 S
A0A9Y2AG30 S
E8RSE4 S
F2B2B8 S
Q7UYZ3 S
I1YJH7 N
A0A853MG28 N
A0A0L0STS6 T
A0A251XU71 S
Q60BI2 T
A0A829X098 S
F3KUN4 S
Q60C43 T
A0A0T7FAP8 S
A0A3E2TW06 N
W0E077 N
A0KPE9 S
R7PZ71 S
A0A0A1ZMZ9 N
A0AA40J491 S
D3S2L0 T
A0A373FQ71 S
A0A0A2C6L1 N
Q7W7D3 S
A0A165K0X5 N
A0A2S5X482 S
R9GM11 I
Q0G0A3 N
D4GLQ6 S
E7RJZ0 N
F8IJE0 A
A0A1V2XMU9 S
Q7TNN9 N
A0A1G5RZU9 N
A0A2N6K4Y5 T
B0SLB7 S
A0A251YFS0 S
B9WDK0 S
Q7N0M6 S
A0A0M2LU39 S
F4B548 S
D6Z5V9 N
A0A4R2M206 S
A0A1E2SKM1 C
A0A127JTU2 S
A0A212AV03 S
G4QHD2 N
A0A021VMC6 S
A0A2J7TJ33 S
G7WDB5 N
Q6BK68 S
Q1K3N8 N
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 S
A0A377PLP5 S
W7QGM4 N
A0A015YIP3 N
A0A060UWC8 N
A0A1I4ZIZ6 S
A0A264VQM8 S
A9AUR8 A
A0A1W5PRD1 N
A0A0E3BR91 S
A0A1B0ZRL8 N
B9ACS5 S
Q92BJ7 S
F2JTN3 N
A1AVV2 T
D2Q0J8 S
A0A3S9N9F3 S
A8ZQD5 N
C3X831 S
A0A1M6BPM0 S
A0A8F5VN39 S
A0A1E5C7W4 N
A0A2S5WV24 S
A0A833GZR2 N
C7M2A9 N
A6W7U2 S
W0JIB3 N
Q07UM3 S
A0A066ZRQ5 N
S0G181 N
D3PAH1 S
Q4WHC6 S
A0AA94HTL8 S
D5ASL9 S
A0A4U1JNL6 T
M0MDP9 N
A0A653N397 S
A0A2S8GSU9 S
A0A097R891 S
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 S
A0A1B9JHS5 S
D3PE53 S
A0A9J9BAE8 N
Q2RM12 S
A0A3N0AQL8 T
C5KTM6 N
M1P5F0 N
I1YG38 N
A0A660CH85 S
A0A2N7L7C8 N
Q5KZZ9 N
M1NZT5 N
A0A225CMT8 S
A0A068NV61 N
H2CJI0 N
B0DU93 S
Q221S8 S
F4Y3C5 N
Q94CJ2 N
M0D3Q9 N
A0A3P2A7W8 S
C0GKN4 N
Q7T3R4 N
A0A562USB9 N
A2SS52 S
A0A211ZGL5 S
A0A4V3ALP8 S
A0A147GP06 S
H2IZ00 S
Q45HK8 S
A0A6C8LST1 S
A0A257T8W6 N
Q5P470 S
I5AZQ4 S
Q07UM1 S
E5B358 S
A0A1Y4L5P0 N
Q3AFY9 T
B0BZN3 N
A0A1Q2C7H7 T
A0A4R5U5V1 S
H6LKX6 N
A0A1Y0UZX2 S
F6BEI0 N
M9RKT6 N
A7SGD4 R
A0A257TE48 N
R1FI09 N
E4N1T5 S
U1PIR6 N
F2JYR9 S
Q84KJ7 Q
A0A2S8FTB5 N
D2R647 N
G9Y5B0 S
A0A144NLT9 S
A0A5J6WQU1 N
D2R355 S
F3ZYD6 N
B0SL05 N
A0A5A7MAJ9 S
A0A977NL43 S
A0A433ZQ80 S
A0A1Y0V4A5 S
A0A1M7UEG2 S
G8R7U9 I
K1LDP0 N
B7G0Y4 N
A0A2W4ZXC0 V
B3PF77 N
Q2KZK9 S
Q18ES8 N
D3F545 N
B4S394 S
Q1Q357 T
Q9H310 N
D3PKL4 T
M5SY07 S
Q8RUT6 N
A7NKH2 N
Q1Q879 N
A0A1B9M5B8 S
A6LRS5 S
J2ZGN6 N
V5E0F3 T
A0A149RQX0 S
A0A165BP25 S
C0QSY0 S
B0XVV6 S
E0SD83 S
A8HSA2 N
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 T
Q0AT01 N
A4FMG0 S
C3YB73 N
A0A9P3CXY2 S
A0A0L8BVU4 S
A0A401WUW1 S
I4C9L2 S
Q8RUE9 N
F0JGZ1 S
A0A2I0UUY1 N
A0A542XGT4 S
G0JRH4 S
A2SPS8 S
A0A5M4AWD2 N
Q6QH01 N
D3F0Z1 N
A6XBM2 N
D6E7B3 T
Q13E03 S
A0A060URB8 S
A0A2T1N7R1 N
D6TCH6 T
B0CXH8 S
A3TVQ9 N
Q4WT12 S
C7QGX3 S
F0Y9X3 N
A0A7S0D560 T
A0A160KTE9 S
A0A2H1HV86 S
A0A251Y3N4 S
A0A419AVL2 S
A0A4Q2QWS1 S
C7Q1E4 S
A0A5C5TYS5 S
F2NNQ0 T
A0A2R4TRE0 S
K9YJQ3 N
D9QS43 N
A7SQ16 T
A1DG05 S
U1SIR9 S
C4Y298 S
A0A9W3LFI9 S
D3RMV7 T
F3QNA7 S
E4RTK5 I
C8XBX8 S
C0QTA4 T
E6VIW4 S
A0A2S6H643 S
Q46HB1 N
A0A2S5CTX8 N
A0A1T4SF40 S
K0K7J4 S
A0A1J5JH24 S
Q6LMI6 N
A0A9W5JBA9 S
A0A291PMC6 S
A0A4Y4DZN4 S
A0A2R4MBA2 T
R9PI53 N
A0A6H9GLV4 N
A0A7S4GND2 N
A0A6H9FPY5 N
A0A1G7DX68 S
A0A075WEB4 S
A0A140NHJ5 S
A0A1C6Z081 S
Q5FA36 S
Q0ACK1 N
A0A975GIX9 S
A0A323UE08 S
U7VB41 V
A0A063Y780 N
C5CIT6 T
A0A0A2VPU3 S
F0RHS0 N
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 S
A0A0A2B651 N
A0A4R3A5P7 S
A0A2A7U6W1 S
Q2GX26 S
F5XN43 S
A0A0K2STH0 N
A0A1H1U2Q6 S
A7SED8 N
A0LV78 S
K5DBA0 N
B8IZX4 S
A8LKQ0 N
A0A5C6LWQ1 I

In [158]:
df = pd.DataFrame(idid)

In [159]:
df['E'] = seqe
df['N'] = seqn
df['D'] = seqd
df['T'] = seqt
df['f1'] = seqf1
df['f2'] = seqf2
df['h1'] = seqh1
df['h2'] = seqh2
df['sn'] = seqsn

In [160]:
df

               0    E    N    D    T   f1   f2   h1   h2   sn
0     A0A858ZNJ3  (Y)  (N)  (S)  (A)  (F)  (F)  (H)  (H)  (S)
1     A0A1H9M798  (Y)  (N)  (N)  (A)  (F)  (F)  (H)  (H)  (S)
2         B0DY50  (Y)  (N)  (S)  (M)  (F)  (F)  (H)  (H)  (S)
3         P69680  (Y)  (N)  (S)  (G)  (F)  (F)  (H)  (H)  (S)
4     A0A3G9G4Q4  (Y)  (N)  (A)  (A)  (F)  (F)  (H)  (H)  (S)
...          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1276      A0LV78  (Y)  (N)  (A)  (A)  (F)  (F)  (H)  (H)  (S)
1277      K5DBA0  (E)  (N)  (D)  (T)  (F)  (F)  (H)  (H)  (N)
1278      B8IZX4  (Y)  (R)  (S)  (A)  (F)  (F)  (H)  (H)  (S)
1279      A8LKQ0  (E)  (N)  (L)  (S)  (F)  (F)  (H)  (H)  (N)
1280  A0A5C6LWQ1  (Y)  (N)  (S)  (A)  (F)  (F)  (H)  (H)  (I)

[1281 rows x 10 columns]

In [161]:
df2 = pd.DataFrame(df[0])

In [162]:
df2['four'] = df['E'].astype(str) + df['N'].astype(str) + df['D'].astype(str)+ df['T'].astype(str)

In [163]:
df2['first'] = df['E'].astype(str)

In [164]:
df2['PheGate'] = df['f1'].astype(str) + df['f2'].astype(str)

In [165]:
df2['TwinHis'] = df['h1'].astype(str) + df['h2'].astype(str)

In [166]:
df2['SN'] = df['sn'].astype(str)

In [174]:
df2

               0  four first PheGate TwinHis SN    kingdom
0     A0A858ZNJ3  YNSA     Y      FF      HH  S   Bacteria
1     A0A1H9M798  YNNA     Y      FF      HH  S   Bacteria
2         B0DY50  YNSM     Y      FF      HH  S  Eukaryota
3         P69680  YNSG     Y      FF      HH  S   Bacteria
4     A0A3G9G4Q4  YNAA     Y      FF      HH  S   Bacteria
...          ...   ...   ...     ...     ... ..        ...
1276      A0LV78  YNAA     Y      FF      HH  S   Bacteria
1277      K5DBA0  ENDT     E      FF      HH  N   Bacteria
1278      B8IZX4  YRSA     Y      FF      HH  S   Bacteria
1279      A8LKQ0  ENLS     E      FF      HH  N   Bacteria
1280  A0A5C6LWQ1  YNSA     Y      FF      HH  I   Bacteria

[1281 rows x 7 columns]

In [182]:
df2.to_csv('all_annotations.csv')

In [136]:
FFF = df2['PheGate'].to_list()

In [139]:
FFFset= set(FFF)

In [140]:
FFFset

{'FF', 'FL', 'FM', 'LL', 'MF', 'VF', 'YF', 'YY'}

In [141]:
hh = df2['TwinHis'].to_list()

In [142]:
sethh = set(hh)

In [143]:
sethh

{'-A', 'EH', 'H-', 'HH'}

In [179]:
SN = df2['SN'].to_list()

In [180]:
SNset = set(SN)

In [181]:
SNset

{'A', 'C', 'D', 'F', 'I', 'M', 'N', 'Q', 'R', 'S', 'T', 'V'}