In [84]:
import ete3
from ete3 import Tree
from ete3 import NodeStyle
from bioservices.uniprot import UniProt
from Bio import SeqIO
from tqdm import tqdm
import pandas as pd

In [85]:
alignment = AlignIO.read("all8concat.fasta", "fasta")

print("Number of rows: %i" % len(alignment))


for record in alignment:

    print("%s - %s" % (record.seq, record.id))

Number of rows: 1281
-------------------------------------DS-GDTA-----WMLTSTLLVI-LMTIPGLALFYG---------GLG-------R---------KNMLSVLMQVFVVFSLISIL--------WSLYGYSL-------A-----------------------------------------------------------------ATI-PEYV----------FLAFQGTFAAITVALVVGS-FAERMRF----------------------ATI---PE---------------YV-FLA-FQGTFAAITVAL-VVGSFAER----MR----F-------R-E-A-FT---PHSLT------LTMVGASLLWV--------GWFG-FNAGSA-------------------------------DGALDFAGGTVVHINAGIAGLVGAYMVG-KR-I--------G--F-------DD-----AFDVFGVHGVGGIVG-AI-LTGVFA----AQ-------GLG---------G-----------------KGKASMLGA-------------ASGAVAGLVAVTPAAGF-VGP------- - A0A858ZNJ3
--------------------------------------D-ADTV-----WILVSTALVL-LMTLPGIALFYA---------GMV-------R-R--------NVLNTMASVLGITCLVSLL--------WFAVGYSW-------AF-------TPG------------------------------------------------------SHI-PESV----------YAMFQLAFAIITAALVVGA-LVERMRF-----------------------HI---PE---------------SV-YAM-FQLAFAIITAAL-VVGALVER----MR----F-------R-E-A-FE---PYNLG------LTMVGASLLWV--------GWFG-FNAGSA--------------------------AR---MGALDFAGGAVVHINAGVAGLVCAWFLG-PR-K--------G--Y-------DD-----SLDVFGVHGIGGIVG-AL-LTGVLA----DK-------SIG---------------------------RGRGSLLGL-------------CSGLVAGLVAITPAAGF-VTP------- - A0A1H9M798
------------------------------------YSP-GDIA-----WVLASTALVW-IMM-PGVGFFYS---------GLL-------R---------KNALSMIYLSMMTSAVVSFQ--------WVFWGYSL-------TI-------V-------------------------------------------------------SARI-PSIV----------FCVYQLMFAAFTPMIAVGA-FAE-----------------------IVSARI---PS---------------IV-FCV-YQLMFAAFTPMI-AVGAFAE-------------------------YE---PHNTT------YVVLGTVFLWF--------GWFG-FNGGSA--------------------------------------GGTPVHISSGTAALAISIYLG-QR-HGYGSEELAG--Y-------DD-----ALDIFASHAVGGLVG-NI-LTALFA----QA-------SVAG------S----------------YRIEKKWSVVGF-------------CSGAIAGLVAITPGSG------------ - B0DY50
-------------------------------------DK-ADNA-----FMMICTALVL-FMTIPGIALFYG---------GLI-------R---------KNVLSMLTQVTVTFALVCIL--------WVVYGYSL-------AF-------GEG----------------N------------------------------------NGSI-YQYI----------HVAFQGSFACITVGLIVGA-LAERIRF----------------------GSI---YQ---------------YI-HVA-FQGSFACITVGL-IVGALAER----IR----F------------------PHNLP------MVFTGTAILYI--------GWFG-FNAGSAGTA-N-----------------------------LDFAGGTVVHINAAIAGLVGAYLIG-KR-V-------------------DD-----PCDVFGVHGVCGIVG-CI-MTGIFA----AS-------SLG---------------------------RGKPSLLGA-------------CSGAIAGLVGVTPACGY-IGVGG----- - P69680
------------------------------------LDL-ASSS-----FVFLSTALVL-MMTLPGLALFYG---------GMV-------R-KKVR---KKNVIATVTQSVAVSCVAGIL--------WYVVGYSL--------------------------------------------------------------------------SL-PEML----------WISYQMTFAIITPALITGA-FAERIKL------------------------L---PE---------------ML-WIS-YQMTFAIITPAL-ITGAFAER----IK----L----G--T-E-E-MA---PNNLI------FVMIGAALLFV--------GWIG-FNAGS--------------------------------MGVLDFAGGAVVHVNSGVAGLVAALFLG-RR-K--------G----------DD-----SLDAFGIHGAGGALG-AV-LTGVFA----DP-------AIN--------------------------IRRKPSLLGI-------------LSGLVAGLVAITPAAGF-VNPTG----- - A0A3G9G4Q4
-----------------------------------------DTA-----WMLVSTAFVL-MMTIPGLALFYA---------GMV-------R-KKVR---KKNVLATLMQSFALCCIMSIV--------WMVAGYSL-------A------------------------------------------------------------------TI-PESL----------FMMFQMTFAIITPALISGA-YAERMKF-----------------------TI---PE---------------SL-FMM-FQMTFAIITPAL-ISGAYAER----MK----F-------Q-D-D-LS---PFNLT------YAIIGASLLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGIAGLVCALVLG-KR-K--------G--F-------DD-----SLDAFGVHGVGGIVG-AM-LTGLFA----YG-------PLS---------A----------------RSGKPTVLGV-------------ISGVVGGLVAITPAAGF-VLPGS----- - A0A149UP06
-------------------------------------YA-LDTF-----YFLICGALVM-WMA-AGFAMLEA---------GLV-------R-AKNTEILTKNVALF--------AIACTM--------YMICGYGI-------MY-------GGG-----------------------D----------------------------------APSA----------DFFFQVVFVATAMSIVSGA-VAERMK--------------------APSAD-------------------------FF-FQVVFVATAMSI-VSGAVAER----MK------TADG--KVN-A-IP---GANLP------LATLGTFILWM--------GWFG-FNG-----------------------------------GFSDFAGSGIVHMAGAAAALAGVLVLG-AR-K--------GK-K------IDD-----PVGAISVHGVVGLLG-LI-LVPFTN----DG------S----------------------------ILFGKADLTMV-------------LNGALAGLVAITAEPST-P--------- - F2G6G4
------------------------------------MDT---VV-----WVLISTALVL-LMT-PGLAFFYG---------GLV-------K---------EKSVSMMMMSFGSLGLVAVL--------WILIGANM-------SS------IDGSVW-----------FGQE------GVA---------G----------------------SDLL----------FVAFGGTFAIITTALISGA-IAD-----------------------FGQEGV---AGSD-------------LL-FVA-FGGTFAIITTAL-ISGAIADK----DI------------------TQ---PHNVP------LVLIGAALLWF--------GWFG-FNAGAA-------------------------------PAVIDYAGGTAVHINAGAAALGLALVLG-KR-V--------G--F-----GFDD-----SLDVVGLHLVAGIIG-TI-YLGFFA----TD------TG--------------------------KLRTGKATAVGA-------------VSGVVAGLVAITPACAN-LT-------- - A0A2M9D7S8
--------------------------------------V-EDTN-----WVLTSSFIIF-TMQ-TGFGMLES---------GCV-------SIKNE-NIMMKNVIDI--------VLGGFT--------YWLFGYGM-------SY-------GRGP------------------------------------------------VG-DPLMG-QIFA----------AFLFQLSFATTATTIVSGA-MA-------------------------PVGDPLMGQI---------------FA-AFL-FQLSFATTATTI-VSGAMAYD----P-----L--------------P---LGNPV------NACMGLFVLWW--------GWLA-FNSGST-------------------------------------AGSGPVHLIGGAAAFASAAMLG-PR-L--------GR-Y-----A-DD-----PVGASSVHGVCGIWG-VI-AVGLFA----DN------PVP-------------------------------MDIIDL-------------INGVLGSLVSITAGCFL-YRAWEA---- - A0A034WGQ2
-------------------------------------NS-GDTA-----WMLMATALVL-LMT-PGLAYFYG---------GMV-------N---------NNVISTMLQSFVAMGVISII--------WVVCGFSL-------AF-------GDS---------------IG------L-D---------GKP------------WSLAATI-PLAV----------FAFFQLKFAVITPALITGS-MA------------------LDGKPWSLAATI---PL---------------AV-FAF-FQLKFAVITPAL-ITGSMA---------------MEA----N-F-LP---PANIP------YVLLGTGLLWF--------GWFG-FNAGSA--------------------------FK---LGVLDFAGGTVVHMSAGWAALAGAIYLK-RR-K--------N----------DD-----TLDVFPCHGVGGMVG-MI-MTGIFA----SK-------GVN---------A------------------KKVSALGF-------------CIGAVVGLVAITPAAGF-VTVPQ----- - I0KDC6
-------------------------------EMLT--EA-INYT-----WILVATFLIF-FMH-AGFAMLEA---------QLT-----------------KNLLTW--------SVGVTV--------FFLIGATV-------EG-------IV------------------------AG----------NG---------------------ASWMD----------WLYGAVFAMTAATIVSGA-VAGRAKLR---------------------------AS---------------WM-DWL-YGAVFAMTAATI-VSGAVAGR----AK----LR------------IP---GHSLT------FAALGTLILAF--------GWYG-FNVGTS-------------------------------VVFHDFAGGMIVHGMGGIAGLTAAWVLG-PR-M--------D----------DD-----VCAVFPVHGSAGVLG-TL-LFPFVA----AP-------GVV---------------------------TGKVDTLYV-------------ANGLLAGLAAITAIPDT-TA-------- - F8D7H6
----------------------------------K--VA-MDTL-----WVAIAAFLVF-FMN-AGFCMLET---------VL-----------------AKNLIVF--------ALATIA--------FWAIGFGL-------MF-------G-----------------DG------N--------------------------------D-PLNA----------KFLFQLVFAGTAATIVSGA-VAERIKFL---------------------------PL---------------NA-KFL-FQLVFAGTAATI-VSGAVAER----IK----FLYQDG--QVI-A-IP---GHNMS------IATLGCLILWL--------GWFG-FNPGST-------------------------------MGFYDFAGSTVIHSFGGWAALMGAAFLG-PR-I--------G-----------D-----PVGATSVHLVCGIWG-TL-AVGLFS----VG------PGGYP----------------------------KPDLSMI-------------INGVLAGLVGVTASCAY-VSMTSAL--- - K9W4V5
-------------------------------EEIK--TT-LTFM-----WLLLASGLVF-FMH-AGFSLVET---------IL-----------------MKNFMTV--------VLGILV--------YWAVGWGI-------MY-------GA---------------DAA------GL---------------------------------ATWN----------SWFFQMVFAATGATIVSGA-MAERTNF----------------------------AT---------------WN-SWF-FQMVFAATGATI-VSGAMAER----TN----FPI---------P-IP---GHNLT------ITFLGTLILAL--------GWLG-FNGGST----------------------------------------GVVHSIGGYSALAGVILVG-AR-I--------GR-FK---NGLDD-----PVGAIAVHGYCGSWG-LI-SVGLFS----IG------MGNG-----------------------------KPDPSLT-------------ANGLLGGLVAVTAPCGS-ISN------- - Q466Y3
------------------------------------MDT-GDTA-----WVLASAALVL-FMT-PGLALFYG---------GMV-------R---------KSVLNMMMMSFGALALISVL--------WVLYGYSM-------AF-------QPE---------------------------------------------------SLVFTV-PSMA----------FVAFQAMFAILTVALISGA-IAD-------------------FQPESLVFTV---PS---------------MA-FVA-FQAMFAILTVAL-ISGAIADR--------------------D-P-MR---PHNLP------LVMIGAGILWF--------GWFG-FNAGSA-------------------------------LLAIDFAGGTAVHINAGAAGLALALVLG-KR-R--------G--F-------DD-----SLDVVGVHLVGGIWG-TL-AVGLFA----SA------STT-------------------------KLRDGHATSLGA-------------ASGVVAGLVAITPACSS-VT-------- - D2SE15
------------------------------------------NA-----FMMICTALVL-FMTIPGIGLFYG---------GLL-------R---------SKNVSLMTQVMVTFAAICVL--------WIVYGYSL-------AF-------GSG----------------N------AIF---------G-----------NLDEDLTGSF-YKMI----------HVAFQGSFACITVGLIVGS-FAE-----------------------DLTGSF---YK---------------MI-HVA-FQGSFACITVGL-IVGSFAE-------------------K-E-A-FK---PHNLP------MVFMGTAILYI--------GWFG-FNAGS--------------------------------DGALDFAGGTVVHINAAIAGLVGAYLLG-KR-A--------G--F-------DD-----TCDVFGVHGVCGIVG-CL-ATGILT----AT-------SLG---------G-----------------RGKPSLLGA-------------CSGCIAGLVAVTPAAGT-VGVG------ - A0A377PBY1
-------------------------------------SA-GDTA-----WMLTSTALVL-FMTIPGLALFYA---------GMV-------R-KKVR---KKNVLATVMQSFAITAVITVL--------WTVVGYSL--------------------------------------------------------------------------AI-PESV----------YFVYQMTFAIITPALICGA-FADRMKF------------------------I---PE---------------SV-YFV-YQMTFAIITPAL-ICGAFADR----MK----F-------------MA---PHNLV------LTMIGGSMLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGIAGLVSCLVLG-KR-V--------G--YGR----EDD-----SLDAFGVHGIGGILG-AL-LTGVFA----VK-------DIG---------G-----------------KGKPSVLGI-------------VSGAVAGLVAITPAAGF-VGV------- - B1JZ69
-----------------------------------------DTA-----WMLTSSLLVL-MMSVPGLALFYG---------GLVKRN--NKR---------NNVLATLMQTVAVCAVVSLL--------WPVIGYSL-------V------------------------------------------------------------------TI-PESV----------FIMFQMTFAIITAALLLGS-VAD---------------------------TI---PE---------------SV-FIM-FQMTFAIITAAL-LLGSVADH----DR----------------T-PS---PANIV------MSLIGTGLLWV--------GWFG-FNAGSA----------------------AGMLGF---GFALDFAGGTVVHIASGVAGLVAALVLG-RS-Y--------D----------DD-----SLDVFGIHGIGGIVG-CI-LTGVFA----TK-------AI-----------------------------GKPSVVGA-------------LSGVVSGLVAITPAAGF-VGFGTS---- - A0A2W5HTC3
-------------------------------------FL-ANNL-----WLLIATILVI-FMN-AGFAMVEAGMCRKNAVNIL-----------------AKNLFVF--------ALAVTS--------YWFIGYSL-------M-------------------------------------------------------------------V-P-TV----------DFLFQSAFAGTAATIVSGL-VAERVKFG---------------------------VP---------------TV-DFL-FQSAFAGTAATI-VSGLVAER----VK----FGPQ--------A-MP---GHNMA------IATLGALVLWI--------GWYG-FNPGSQ------------------------------------FAGSSIVHSVGAWAGLVGAMLLG-PR-I--------GK------YSDGD-----PVGAFSVHGVCGVWG-TL-VIGLWG----TA------VQGDG--------------------------SGKPDLTMI-------------INGILAGLVSITAGCGD-MT-------- - A8G2S3
------------------------------------MNT-GDLA-----WVLISSALVW-LMT-PGLALFYG---------GL-------------G---EKNLLHTMFIPVLIIGIASLT--------WFLVGYSL-------AF-------GGN------------------------------------------------------GTI-PDGA----------FALFQGMFPIITAAIITGS-VIGRMKI-----------------------TI---PD---------------GA-FAL-FQGMFPIITAAI-ITGSVIGR----MK----I--------------------HIPV--RPSYVLIGGALLWV--------GWFG-FNSGSA-------------------------------MGAIDFAGGTVVHISSGVTGLVLALLIG-HR-H--------N--D-------DD-----TLDAFGIHGIGGAVG-AI-LTGVFA----DK-------NI--------------------------KTHGRVTLAGI-------------TSGGVAGLVVITPAAGF-VAP------- - D5T4N9
------------------------------------------PV--PL-PLLMQGLLVMGLL--AGLTLFQS---------GLV-------R-PGASAQAIKGICGS--------ALAVLA--------FFFIGSNVLMVGVNGGF------HGTF-----------------------AFF--------------------------------DAMA----------EWFLRAPFAALPVLIVAGA-LAERLR------------------------DA--------------------MA-EWF-LRAPFAALPVLI-VAGALAER----LR------------------LP---TNSLA------LATFGTFAGWI--------GWFG-LTGGAVLLA-VPEAGP---------------------LGFVDIGGATVLHSAAGWAALVGAVLLG-AR-K--------G-----------D-----ATGAISVHLICGLWA-TL-VVSVID----PT------VPLTTQ---------------------------RNGVMAR----------G--LQGALAGLVSISAAPHL-PMP------- - Q2RWY7
------------------------------VGHNS--VA-INIM-----WTLLAGFLVM-FMQ-AGFAMVET---------TM-----------------SMNFFVY--------PLGMLG--------FFLTGFAI-------MF-------GGFG--------PL--ATLG------GYTLLGHPFGLFGMTG-------FAL--IGTYDV-GVFA----------LFLFQMVFMD--------------------LLGHPFGLFGMTGFALIGTYDV------------GV------FA-LFL-FQMVFMD--------------------------------------IP---GHSIP------MAIIGTFILAF--------GWFG-FNAGST-------------------------------NGHVDFAGSSVVHMTGGVIGLVGAWIIG-PR-I--------G----------DD-----PVGAVSVHMVNGAWG-CL-ALGLFA----DG------SYG-------------------------------PDPGMA-------------CNGMLAGLVAITAPCAF-VNQIS----- - A0A0E3R4G0
------------------------------------MNP-ADNA-----WVLVASALVL-LMT-PGLAMFYG---------GLT-------R---------SKNLSTMMHSFFLMGLASII--------WLFYGFSL-------AF-------GTD------------------------------------------------------IGI-TGST----------FMIFQCMFAVITPALISGA-FAERMKF------------------------I---TG---------------ST-FMI-FQCMFAVITPAL-ISGAFAER----MK----F----G--T-V-P-MI---PHNLT------LTLLGAGLLWF--------GWFG-FNAGSA--------------------------LK---LGALDFAGGTVVHINAGVAGLACCIVLG-KR-K--------G----------DD-----SLDVVGVHAVGGIWG-AL-ATGLFA----SK-------AIN---------AAGN---------------GKPTTLGV-------------ASGAVAGLVAITPAAGY-VGP------- - I4C9L0
-------------------------------------DK-GDNA-----WMLTSALLVL-LMILPGLALFYG---------GLV-------R---------KNMLSVMMQVSTVALIGFVA--------WMLWGYSF-------A-----------------------------------------------------------------VVI-PELT----------FIAFQSTFAAITAALVVGS-LVERMKF----------------------VVI---PE---------------LT-FIA-FQSTFAAITAAL-VVGSLVER----MK----F-------K-E-P-MP---PHSLT------LTLVGAGLLWV--------GWFG-FNAGSN---------------------KSGLLWG---FGALDFAGGTVVHINAGIAALVGALILG-KR-Q--------G--Y-------DD-----SLDAFGIHGIGGIVG-AI-GTGLLV----NP-------AWG---------GAGV---------------GKPSALGL-------------ASGIVAGLVAVTPAAGF-AGPMG----- - D5VJ32
----------------------------------S--SA-IDAT-----WVMVSAILVI-LMQ-VGFALLEA---------GST-------R-KNAGHVAGKTVLTF--------GICSIA--------FWAFGFGL-------TF-------GD------------------------GNS-------F-GMQKDAFS--AFS--------A-ATVP-------ISILFLFQLAFAAVSLAIAWGG-FA--------------G-MQKDAFSAFSAATV---PI---------------SI-LFL-FQLAFAAVSLAI-AWGGFA--------------------------IP---GHNQV------YSVLGVLFLWI--------GWFG-FNAGST-------------------------------LGMQDFAGSTVVHLQGAIVALVATILLK-PR-I--------GG--------IDD-----PVFAFSVHGVAGIWG-TL-STGLFA----TP------ELVE-----------------------------KADIPSM-------------LNGVLAALVAITASCAF-VDPWA----- - C0Z5S5
--------------------------------------A-ANTN-----LLLFCSALVF-FMQ-AGFAMLCA---------GSI-------R-SKNVNILIKNVLDA--------CVGALA--------FFAVGYGL-------AY-------GRK----------------------------------------------------------TGWT----------NFLFNWAFAAAAATICSGA-MAERTQF-----------------------------G---------------WT-NFL-FNWAFAAAAATI-CSGAMAER----TQ----F-------------MP---GHNAT------LTVLGTFVLWV--------GWYG-FNPGSV-----------------------KWSG----VGFIDLAGSGVVHMVGGFAGLMGAIMLG-PR-T--------GR--------IDD-----PLEAFPIHGACGVWG-CL-AVGLFA----KK------KFL-------------------------RAFNKVWDLVAV-------------CNGILAGLVSITAGCHV-MD-------- - C1N6X9
---------------------------------MTTLDT-GDIS-----FLVVCTLLVF-LMT-PGLALFYG---------GMV-------R---------RNVLSIMMQSYAAMGIVTVI--------WVLFGYSL-------A---------------------------D------Y-----------------------------APTI-PHLL----------FFLFQLMFAIITPAVISGA-TA------------------------DYAPTI---PH---------------LL-FFL-FQLMFAIITPAV-ISGATAGY----EW------------------NI---PHHMP------NVLFGGGLLWF--------GWFG-FNSGGA--------------------------RN---LGVLDFAGGTVVEVASGVSGLVAAYVLG-KR-L--------K----------DD-----ALDVFGIHGVGGTWG-TI-ATGIFA----DL-------SLN---------PQ--------------LHRRQITVFGA-------------VSGIISALVAITPAAGY-VST------- - J7ITF6
--------------------------------------K-GDNT-----WMLISTILVL-LMTIPGLALFYG---------GLV-------R---------KNMLSVLMQVFMITAVVMII--------WVTYGYSL-------AF-------T--------------------------------------------------------VAI-PELT----------FVCFQMTFACITPALIVGA-FAERIKF----------------------VAI---PE---------------LT-FVC-FQMTFACITPAL-IVGAFAER----IK----F----K--K-D-I-MA---PHSMT------LTMVGASLLWV--------GWFG-FNAG---------------------------------YGAIDFAGGTVVHINAGIAGLVGAIMLG-KR-T--------G----------DD-----SLDVFGVHCVGGILG-AI-GTGILV----NP-------ALG---------GAGIVDYSTA---------GKASMLGA-------------ASGAVAGLVAVTPAAGF-AGPMGS---- - A0A068SVR1
-----------------------------------------DTA-----WMMVASAFVL-MMTIPGLALFYS---------GMV-------R--------KKNV-ATMAQSLAAVAIISVL--------WVAFGYSL-------AF-------VGD----------------G------A-------------------------------WI-PEAL----------FMLYEMTFAVITVALVAGS-VADRMRF------------------------I---PE---------------AL-FML-YEMTFAVITVAL-VAGSVADR----MR----F-------A-D-N-LS---PFDLS------LAVIGTGLLWV--------GWFG-FNGGSA-------------------------------AGVLDFAGGLVVHLSAGTGGLVGAMVLG-RR-H--------G--Y-------DD-----SLDVFGVHGIGGLTG-TV-LAGVFA----TA-------AIGGT------SGLI---------------RRKPSVLGM-------------ISGAVAGLGTITPASGY-VEP------- - A0A0D7F328
--------------------------------------K-GDVA-----WMMTATLLVL-FMTMPGLALFYG---------GLV-------R---------KNMLSVLMQCTMICGIMIIA--------WVVYGYSF-------AF-------GGG-----------------------------------------------------TVEI-PEYL----------FIAFQMTFAVITPALIVGG-FAERIKF----------------------VEI---PE---------------YL-FIA-FQMTFAVITPAL-IVGGFAER----IK----F----G--K-D-N-MA---PHSMT------LTMVGAAILWV--------GWFG-FNAGSN-------------------------------IAAVDFAGGTVVHINAGIAALVGAFVVG-KR-L--------G----------DD-----SLDVFGIHGIGGIIG-AV-GTGVFT----SS-------ALG---------GIGYGEG--------AAARGKASMLGG-------------ASGIVAGLVAVTPACGT----------- - Q0G0A4
-------------------------------------DS-GDTA-----WMLTSSVLVL-MMTVPGLALYYG---------GLL-------R---------KNILAMLMQCFFATALISVL--------WVVIGYSL-------AF-------TKG----------------N------G---------------------------TLSGTI-PETV----------FCMFQCTFAIITPVLILGG-PAD----------------------GTLSGTI---PE---------------TV-FCM-FQCTFAIITPVL-ILGGPADG----SV----------------N-MA---PADLG------YTLVGASLLWV--------GWFG-FNAGSA--------------------------GG---QGVLDFAGGTVVHINSATAGLIAAIMVG-KR-T--------G----------DD-----ALDVWGVHGLGGIAG-AL-LTGVFA----VK-------SIG--------------------------IKGKPSLLGA-------------VSGAVAGLVAITPACGF-VP-------- - F0J3F9
--------------------------------------S-GDTA-----WMLISSVIVL-MMTVPGLGLFYA---------GMV-------R---------KKNIATMMQAFSAAAVLSIV--------WMVAGYSL-------AF-------GTG----------------N------A-------------------------------TI-PESL----------FMFFQMTFAIITPALIAGA-FADRMKF-----------------------TI---PE---------------SL-FMF-FQMTFAIITPAL-IAGAFADR----MK----F-------------MS---PHDLS------YALIGASLLWV--------GWFG-FNAGSA-------------------------------------AGGTVVHINAGVAGLVCALVLG-KR-Y--------G--YGR----DDD-----SLDAWGVHGIGGITG-AL-LTGIFA----YG-------PLS---------A------------------GKPTVLGA-------------LSGAVAGLVAITPAAGF-VLPGP----- - Q0BQ69
---------------------------------SKSYPMFQDVH----------------VMIFIGFGFLMM-FLKRY---GL------------------------------------------------AVGLNFMIA----AL----------------------CLQWAILV--NGFFHLKK-----G----------------TIVDL---------------NAMLGADFTAAAVLISFGV-LLGKTTPT---------------------VDL---------------N----AM-----LGADFTAAAVLI-SFGVLLGK----TT----------------P-T-T--EKEGSSYQSDLFAMIGTVFLWL--------YWPS-FNA-------------------------------------IDMGDSMFVHVFGAYFGLAVSLML--HR-R--------DA----------D-----TCGVHNLHGLPGILA-AI--IGAVA------------AGVASEA----SY----------------------DMVHV-------------QNSTLAGGVAVGTAADLMIHPWGA---- - F2YIC4

In [134]:
ey = alignment[:, 70:71]
n = alignment[:, 102:103]
d = alignment[:, 105:106]
f = alignment[:, 106:107]
t = alignment[:, 241:242]
s = alignment[:, 244:245]
edg = alignment[:, 250:251]
f1 = alignment[:, 311:312]
f2 = alignment[:, 392:393]
h1 = alignment[:, 441:442]
h2 = alignment[:, 495:496]
sn = alignment[:, 579:580]

In [87]:
idid = []
seqe = []

for i in ey:
    print(i.id, i.seq)
    idid.append(i.id)
    seqe.append(i.seq)

A0A858ZNJ3 Y
A0A1H9M798 Y
B0DY50 Y
P69680 Y
A0A3G9G4Q4 Y
A0A149UP06 Y
F2G6G4 E
A0A2M9D7S8 Y
A0A034WGQ2 E
I0KDC6 Y
F8D7H6 E
K9W4V5 E
Q466Y3 E
D2SE15 Y
A0A377PBY1 Y
B1JZ69 Y
A0A2W5HTC3 Y
A8G2S3 E
D5T4N9 Y
Q2RWY7 Q
A0A0E3R4G0 E
I4C9L0 Y
D5VJ32 Y
C0Z5S5 E
C1N6X9 C
J7ITF6 Y
A0A068SVR1 Y
A0A0D7F328 Y
Q0G0A4 Y
F0J3F9 Y
Q0BQ69 Y
F2YIC4 M
D4XLN6 Y
A0A420WC79 E
A0A5C5TUT2 Y
A0RUZ2 Y
A0A0A2ZRL7 Y
J4UGB7 Y
E5Y678 Y
A0A0D2KGN8 Y
S5ABR8 E
A9DQM8 E
G5EB13 Y
A0A2N6NEK4 Y
C6DB68 Y
Q81GN5 Y
Q0F2M5 E
A0A0C6P439 Y
B9SWW9 Y
L8H5K0 M
Q9NIV0 M
C1N5A7 C
Q1JXS5 Y
A0A1M6JKY3 Y
F4D1J0 Y
A0A257SYX3 Y
V4RK08 E
G0V8D6 Y
A0A7S4GMD8 C
B3QVV5 Y
F2JZ83 E
A0A857DDJ7 Y
A0A0S6UHP2 E
D5EP71 Y
F4KY49 Y
M5S9B4 E
A0A009PYN3 Y
A0A3T0SZ22 Y
A0A248LMH8 Y
A0A6H9GEE4 E
A7HSP2 Y
A0A7V8IKS6 Y
T2JFS5 E
F6FRU9 Y
A0A9E9L9J1 Y
A0AIW5 Y
A0A0E9NHV4 Y
Q2N625 Y
C8WSI9 Y
A0A1H1BPD6 Y
A0A176XNC5 Y
A0A4V0XUI3 E
A7S3L2 E
M5U2P1 E
K9P5D1 Y
Q0F2M7 Y
A0A2R3IMJ8 Y
Q2RVB5 Y
A0A556RTU3 Y
E0TGP9 E
B7G0Y1 C
A0A1G9P6Q0 E
D0LTW3 E
Q6BT62 Y
Q2IK04 E
Q6BJI7 Y
B7X047 Y
A0A068NPW2 Y
A0A399NT81 Y
K0F9X7 Y
A0A037ZMW1 E
A0A075JZ35 Y
A0A369MHK2 Y
A0A1B9JPL5 Y
D8PD01 Y
A0A2G5BI87 Y
A0A2G5BGA9 Y
A0A657K391 Y
P69681 Y
A0A4P6UIJ8 Y
A0A0V8M0W6 Y
A0A0H2XSU4 Y
Q1Z695 E
A0A7Z0V0A4 Y
K0ER80 Y
A0A149UWF2 Y
G0H0Z6 E
G0EFF3 Y
C8WLL8 Y
X5CNT2 Y
A0A4Y1MSE7 Y
H2CLF7 E
M4VEJ9 Y
A0A4V2X6C2 Y
A0A2K1RA77 Y
A0A375YPN6 E
A0A7M6UUM4 M
A0A172YCA7 Y
A0A918MJ52 E
A0A2S8QA29 Y
A0A251XJT0 Y
A0A0B4E6X7 E
A0A0K2STQ7 E
A1C5Z7 Y
C9KKP2 Y
A0A2Z4MD56 E
Q9VFA9 E
A0A502GPV4 Y
I5C044 E
D2V6P8 M
D3RN22 E
Q97L80 Y
A0A0D5YN10 Y
A0A1I5GN22 Y
A0A1Y5E8I7 E
B1Y8C9 Y
M5SYZ1 E
Q6HM26 Y
A0A379A0S9 E
A0A101DCS3 Y
A0A1Y3U5V2 Y
A0A202B535 Y
F8E6R1 E
Q6ND36 Y
A0A8H6K7L7 Y
Q7NCB8 Y
A0A369MRW6 Y
C9RS76 E
A3U857 Y
A0A127PIQ9 Y
B8FGW0 Y
A0A060JMP6 Y
D5V7B3 E
A0A494JB70 Y
A0A5M8QF12 Y
A0A8G2F3G4 Y
J7L3W8 Y
G0JRG9 Y
D3DJN2 Y
A0A1Y2JH43 Y
Q1L727 E
A0A7T2S0Z6 Y
A0A315S845 Y
A0A2S6H6B7 Y
A0A1J5NTP7 Y
A0A0E3QY86 Y
A0A096EEV9 Y
A0A380S5X4 E
B8ZYW3 E
A0A2S8GEJ5 E
A0A248TDF2 E
B2GFN1 Y
U1PPI7 E
C7LW88 E
G3A431 Y
A0A066ZTE4 E
L7CG99 E
S0ET45 Y
A0A178TA08 E
H1XV27 E
A0A6M3ZJI1 Y
U5DEY6 E
H6LFQ2 E
Q6CRN0 Y
A0A4Q2EAG7 Y
A0A1J5NNB8 E
E3I393 Y
A0A243SC06 Y
D4F313 Y
W0F0I7 Y
A9B874 E
A1D2Y5 Y
T2J0N1 E
Q2FQT3 Y
A0A075WG29 E
A0A979GQ79 Y
A0A381CAY8 Y
A0A2G3DSU6 E
A0A168EVK8 Y
A0A094W9G3 E
A0A4R3NVT3 E
W0DYY3 E
G8JTW0 Y
A0A4P6UIK6 Y
I9P003 E
G2T1Y3 E
B8EMQ8 Y
I6Z905 E
E0TCV4 E
A3XNG6 E
A0A087MGU4 Y
A2BUP4 E
A0A562S8V2 Y
A0A495DND0 Y
A0A0S2FHD7 Y
F3QPR6 Y
A0A063Y394 E
F6G5I9 Y
A0A323UDG5 Y
A0A0G9HEC5 Y
B8FDY8 Y
Q5KPM5 Y
A0A147EQL9 Y
A0A854Q6X9 Y
C3X1J1 Y
A0A5B2V3B9 Y
A0A258FS85 Y
A0A7T2W1B3 Y
A0A060UN76 E
G0JRQ3 E
D5UD26 Y
G2ZN72 Y
A0AA46Q839 Y
A5UJR1 Y
L1INN6 E
C1F584 E
C5LAG4 E
A0A2A2MCP3 Y
B1Y6V4 Y
A0A1G6ABK5 E
A0A6A1TYJ4 Y
A0A2T4UWF1 Y
V4AP67 E
A0A173R3W6 Y
C7NND3 E
B0DFJ4 Y
A0A3E2VY88 E
R1EDV9 E
J1L5M8 Y
D7G265 E
Q8ERT9 E
I4D6Z9 E
A0A4R6DFU8 Y
A0A060URC3 Y
D2BIB2 Y
F5ISF6 Y
A5CRL2 Y
A0A6G9XJV9 Y
Q59UP8 Y
A0A6N4SPH9 E
I0HGY4 Y
X5DX97 E
L1J6I4 Y
I1DSU5 E
B9L7N1 Y
Q1Z4I4 E
Q21CP1 Y
A0A165MFD1 E
V4CRP5 E
Q7S5K0 Y
A0A071MMV1 Y
A0A149RYW7 Y
A0A7G5EC77 Y
A0A1W2GZ82 E
A0A7U3XVQ4 Y
A0A071M4L5 Y
U5C2K4 E
A0A248LNW8 E
L8H844 E
A0A149V596 Y
S9QZ09 Y
B1ZSW9 Y
D2BUJ8 Y
A0A9Q8L398 Y
M5S735 Y
Q6ARH0 E
K6W5X0 Y
G0JRG6 Y
A0A6H9FYW4 Y
A0A0S4WFM4 Y
A0A101HKN9 E
Q9REX3 E
F0S3Z6 E
A8NAG3 Y
C6LBD3 E
A0A149U2G9 Y
V4REY8 E
A0A0H3H4I7 Y
A8N2H6 Y
S0APH6 Y
A0A017SYR8 Y
A0A1B9MZ78 Y
E4T3F3 E
D7E934 E
A0A0M3AB44 Y
A9WHW6 T
A0A5M4AUM9 Y
A0A1X4GBG2 E
I4D1H5 Y
A0A0E3QYF3 E
B0CQX4 Y
A0A378YR15 Y
A0A495D4X4 E
A0A076PL76 Y
Q1YDY7 Y
A0A3E2UCG9 E
A0A2K3DPU7 M
A0A3R9Q7C4 Y
V5U2Z4 Y
K9P718 E
M1V7W3 T
Q6LKC8 E
E5Y789 Y
J9Z839 Y
A0A1G7VM92 Y
K9Z0D3 E
A0A482TED1 E
R1EGK6 E
J1ASR8 Y
A0A7U4E420 Y
K9YR86 E
A8PXT8 Y
A0A0U1NJW3 E
B8FL88 E
A2CCK1 E
D6TFE1 E
A0A2H4U5R1 Y
I2GD40 Y
A0A060HFT5 Y
B1Y842 E
A0A0X8NXA9 Y
A0A0A2A5X1 E
A0A318FY98 Y
Q7V4T8 E
A0A1A0DHK0 Y
C1A872 Y
A0A395VB65 E
A7MFK3 Y
J4KM12 Y
A1SY01 E
A0A1H4DJ49 E
A0A9R0NTP8 Y
A3PAY4 E
B4CV94 Y
A2C095 E
Q2HD43 Y
A0A836M2B6 Y
H6RWK9 Y
A0A087EQK8 Y
A0A1I0AQM4 M
L7CG11 Y
A0A248LNK5 Y
B7FTM9 C
L0K9M1 E
I4D6Z7 Y
A0A2K1RA81 Y
Q2WBF7 Y
A0A1B9BUU6 Y
A0A2S0JW39 E
A0A2S5YID7 Y
B3PIH2 Y
U3P8G1 Y
C9R9J0 Y
A8AC17 Y
F0YLV7 E
A0A1D3GAE9 Y
C1MHX0 Y
A0A1H4KAQ7 E
A0A2T4XZC1 Y
A1B3N0 Y
C7LW87 Y
A1SZ12 E
A0A2T2Y0D5 Y
A0A1H8D0R8 M
A0A2S5V2F6 Y
G3IYW2 Y
F5L8M7 E
C7BJG7 Y
E4U5Z1 Y
A0A1B9K8L2 Y
A0A2S5WMT7 Y
A0A0D2UPA8 Y
A0A161SKF4 Y
B4D7W2 Y
A0A1H3WA00 Y
C1D6X6 Y
A0A4D6KHD1 E
Q488X2 E
A9V5W4 M
A0A5M4ATH9 Y
E4TRS4 E
A0A011U1K7 Y
C7R314 Y
A0A077EFU9 Y
A0A0A2A0Y9 E
A0A0D8BQX6 E
A0A0L0S493 Y
A0A328Q6M1 Y
A0A016XCG9 Y
B7FSA7 C
G0AFH4 Y
A0A177W826 Y
A0A2S8GF54 E
Q1YDY8 E
Q5QVH2 E
A3ZT81 E
A0AA35XZV0 Y
F4H924 Y
K0NJH2 E
A0A1V3SSW1 E
F2AUF4 E
A6DN47 E
W8KM07 E
A0A1X3RP39 Y
A0A7S0KKL8 C
A0A318QZ80 E
K8VZC6 Y
A0A1B9JZS5 Y
A0A2S6GKN5 Y
A0A4R2Z2K6 Y
H1YCC3 Y
E1QIU3 E
A0A8H6MPB9 Y
A0A369N7Y3 Y
T2IEJ2 E
H5UND3 Y
Q1PX09 -
A0A149TSA9 Y
F2NGJ8 Y
A0A0E3SHQ9 E
Q5FLR6 Y
S0EUS1 T
A0A369M386 Y
W0DZS7 Y
A8MCL4 Y
V3ZVE4 E
O26757 -
A0A317FZW2 E
A0A085GI50 Y
A1ZGK6 E
G0IYI2 E
A7S731 E
A0A1U9YY82 E
A0A328EMN2 Y
A0A8E2UDJ3 Y
A0A2S5WUP6 Y
A0A8H7P8U1 Y
A0A257T7G4 Y
B3MX93 E
A0A1G5W0P2 Y
D4H2Y7 E
A0A4P8HC89 Y
Q7T070 M
F7NPQ3 Y
B9SA70 Y
Q9M6N7 Y
I7ZHW3 Y
F4XTK4 E
A4G1J2 Y
G7WFX4 Y
B8JBH5 Y
D9QPC8 Y
A0A4R7GKA0 Y
R9PMC6 E
A0A0E3LMT4 E
A0A511NGC7 Y
E4NS62 E
E4T3F7 Y
M0D580 E
J7J5E7 Y
B1XZU2 E
A0A366IE34 Y
A0A6U2BIY7 E
Q9QXP0 M
A0A424WAH3 Y
A0A410K1J5 E
L1IHZ8 Y
I8TC71 Y
A0A7U8C744 E
A8M670 Y
A0A0S4VNK2 Y
Q2SIR0 E
A0A5C4RNH5 Y
A0A3E0X011 E
A0A0E3SP24 Y
E1IF27 -
Q2YBP7 M
A0A2S5WZU0 Y
A0A172YBR4 E
A0A0K2STK6 E
A0A2N6JV02 E
F0S0G1 Y
A0A1C7EL50 E
Q18PF5 M
A0A1I0C958 E
A0AA35XVN2 Y
L8GGA0 Y
Q3AP28 Y
D0MFE9 Y
J9VXX9 Y
A0A166IS52 E
F0J7D3 Y
W7QG13 E
A4BMY5 Y
A6LV49 Y
Q1H483 Y
A6M3G0 Y
E4T0A4 Y
A0A3E2UHE6 E
A0A174SD65 Y
A0A855EH99 Y
C3YB74 E
A0A074KZD8 E
J0S2I0 E
K9WSX4 E
E8RLT5 Y
Q2FS34 Y
Q3Z7F9 Y
Q2S8H9 E
A0A060HN92 E
E6ME92 Y
A0A172RYW3 Y
L0FU80 E
C8WZE0 E
A0A2S8F4W0 E
A0A2C6C0X3 Y
F3ZVV4 Y
A0A7R6PER3 E
A0A495WJM6 Y
A0A0B4DUR9 E
A0A251YU48 Y
A5D4I5 Y
A0A2X2C038 Y
A0A2A2M8K7 Y
D3FBG3 Y
A0A2V4EA49 Y
D0MFE8 E
Q3B6Q2 Y
A0A1B9KID3 Y
A0A9J9ES23 E
A0A3N2SFS2 Y
Q0VLH1 E
A0A1U9Z147 Y
Q0G2T1 E
A6GJF5 E
A0A059XXR1 Y
A0A5J6WPP9 E
P41948 Y
L1IUV5 Y
A0A2W0GQV0 Y
Q1K433 E
A0A4Y7XC43 Y
D5AU98 Y
E1QFA8 Y
A0A075WBP9 Y
Q0BWD0 E
A0A1Y0HX98 Y
A0A098S5Y7 E
Q0I445 Y
A0A1E5BXA4 E
A0A2C9CK98 E
G4H971 E
A0A1I0BYN1 Y
A0A330GB00 Y
A0A2S8FR08 Y
Q84KJ6 Y
A0A2S5WGI8 Y
M2ALH9 E
A0A2K3DQF8 C
A0A8G2IZM3 Y
F5Y3C1 Y
A0A370FPU0 Y
F5RGM7 Y
A0A4R4K1P9 Y
R8VWI7 E
A0A0A2AMW2 E
Q7Z1M1 E
A0A414NWT8 Y
A0A0P6VSR8 Y
A0A0L0TDW1 Y
U3PCH5 S
W7QGE0 Y
C5BWX7 Y
A0A1B9M1A9 Y
B8GGC3 Y
D6SPD1 E
A0A0H3DR67 Y
A0A4R7VEK0 Y
G4R7P1 E
A0A1M5ZVP9 E
A0A2S5Y0D3 Y
I0ICG0 E
D0L8H3 Y
A0A1B9LFW3 Y
Q6ND34 Y
A0A6H9GWG4 E
Q5UZ98 E
A0A2S0P9T4 Y
H2CDR5 E
T2KGT3 E
A0A088E6Q7 Y
A0A258HS77 Y
E1V4T3 E
B7GKP4 E
Q9QUT0 M
I3Z3H7 E
G7WCB6 Y
A0A1Y6GLJ1 Y
A0A0S2DQB6 Y
Q6CRN1 Y
A0A401X433 Y
A7HT14 E
A0A009TDB1 Y
D4XSW0 E
B0SRS8 E
A0A149QSR6 Y
B1Y0E5 Y
Q7UGU7 E
A0A2S0Q8P1 E
F0ZPL3 E
A0A2T0GTU1 Y
I4CCD1 Y
A0A9Q6P4A5 Y
A0A418VIJ8 Y
C1MX19 Y
A0A1B9BUZ8 Y
K9W6F3 Y
Q1K8A3 Y
L8GFX3 Y
A0A1G6ABL9 Y
A0A087L0B9 Y
A0A073CP02 E
A0A0A1ZJU5 E
A0A258HPP1 Y
A0A149QAW7 Y
D2V6Q5 E
A0A1X4G8K1 Y
A0A067Z3S3 Y
A0A8F5ZDT8 Y
A0A854QN45 Y
A0A2N7LCD7 E
G7WFX2 E
A0A7S4GNJ2 E
A4G0C5 E
A6VE60 Y
A0A1S1HM83 Y
A0A037ZJY5 Y
N1WR17 E
Q2W5V2 E
A1VIM5 Y
A0A1Y5E3E3 Y
A0A1T4SFK4 Y
A7RNC3 E
M7XJ51 E
A0A399T909 Y
A0A2N6P374 Y
H8L2Q4 Y
D5EP68 -
E6SF19 Y
A0A1T4SFY6 Y
D3LBI0 -
E6W5C1 E
Q0VPH4 E
K9WT03 Y
L0KW14 Y
A0A4R8H081 E
A0A1B9N3H7 Y
B0RC35 Y
A0A420KGW4 Y
A0A4R3NLV5 Y
Q47K18 Y
Q21P82 E
M1WRK6 -
A0A290XBB5 Y
A0A6T9XUR2 E
A0A1J1JH03 E
I3R0S7 E
A9UR54 E
A0A1G7H8X3 Y
A0A8G2F718 E
Q1H0G2 E
D0LAL7 Y
C7LQR9 E
A0A1G5PWV0 Y
K1K628 Y
B9SXC7 Y
G7WA28 Y
Q1IWN6 Y
H6LKH9 Y
A0A1H7CU41 Y
G8JUJ2 Y
A0A081N2G5 E
A0A074ME37 Y
Q0VQH6 Y
C8XB51 Y
A1VIG8 Y
Q8GQS1 Y
A0A1I7FBM5 M
A0A1M6ZMI3 E
A0A482PLH3 Y
A0RXK8 Y
D0KXQ0 E
Q8JI14 M
A0A7T4WEP4 Y
A0A4R3ZNW3 Y
A0A074KY88 E
A0A6M3ZKU5 E
M1SJL5 Y
A0A1W9KSU5 Y
E3GI40 Y
A0A369NYJ2 Y
A0AA92K392 Y
O04161 C
A9BQZ4 Y
A0A6N2Z556 E
A0A8H6NAG3 Y
A0A2T9X1V4 Y
Q2J376 Y
A0A0F5EZP7 Y
A0A7G5DK18 Y
M9YAI9 Y
D2ZRW2 Y
G7UUY6 Y
A0A8H4GS02 Y
A0A2T5IHP0 M
A0A165MAC2 Y
A0A7S4LPS8 E
A0A075JIN0 Y
C8X554 Y
B8FZP7 Y
Q5KAF6 Y
A0A427KNL6 Y
A0A7G5DPV0 Y
Q22947 M
A0A1S1HRJ0 Y
A0A3N1VXY4 Y
A0A2S7YPJ9 Y
I0JI83 E
A0A7U3YMN6 Y
Q9BLG3 E
A0A1H9RTW8 Y
A0A1I4W3A0 Y
A0A0B4M163 M
U2EN72 E
A0A2W5VAZ2 Y
E4YA63 E
D5ELM4 E
M9RJS5 Y
A0A2G3E8V2 E
Q5FSX6 Y
I0HKQ8 Y
A0A833H2R7 E
B8ENL9 Y
B3DUX7 Y
A0A1D8UWJ6 Y
D5E995 E
A0A7U8C2Y6 E
L0KGR8 Y
B0VMH1 Y
P40260 Y
L0JT30 E
C1GR74 Y
A0A423Y4I6 Y
A0A4P7UHQ5 Y
A0A8E2R1Y5 Y
I5BYV5 E
A0A6B8N021 Y
A0A7G5DPV1 E
A0A2G5RQK9 E
A0A5M4B0G1 Y
A0A6S5K4J1 Y
C1D4X0 Y
A1SVA8 E
H1YF74 E
A0A8B4RWH8 Y
A0A0A0D6K5 Y
A0A0A2BBY0 E
A0A089ZBW5 Y
A0A068TC78 Y
Q46G49 Y
A1CQ21 Y
A0A1G6ABX1 E
E1SLM7 E
K5CFE5 Y
Q2YLQ6 Y
Q0G2V0 E
A4ABK3 E
A0A9Q5QVI9 Y
A0A4Q7Y9I7 Y
A9HMD6 Y
K9YN27 E
Q9UBD6 M
D9SI59 Y
Q8I0L6 M
A0A142VAD6 Y
G3IYW0 Y
A0A062IU58 Y
R1D1H4 E
A0A366XFS8 Y
A0A7S4GNF3 E
F0J6E8 Y
A0A7U4DN04 Y
V4RHR4 E
F7ZJM0 E
A0A2S5XAB8 Y
U5C4L4 E
Q21J04 Y
A0A142NNN1 Y
H1Y7T6 Y
F5R974 E
B0DU91 Y
A2BP62 E
A7HSN9 E
A0A377I7W9 Y
D2RU19 E
G7WJN0 E
E2SD33 Y
A0A0D7F2Y9 Y
A0AA92EGF5 Y
A0A9E9LXV9 Y
A4BEP1 E
A0A0E3WZH5 E
F7ZEU9 E
A5E3X2 Y
A0A0A3XTJ3 Y
A0A830ZZN8 Y
A0A1S8D478 Y
J7IVQ1 E
A0A2U1SS17 Y
S3K1S2 Y
C6XKC2 E
A0A2S7YIM5 Y
K2IMJ7 E
Q5P1S8 E
A0A7T5BFQ2 E
A0A556SRH6 Y
A8P923 Y
A0A7G5DKA9 E
L8JUH3 E
A0A0D2LEF5 Y
A0A258FTB0 Y
A0A5P9P1L2 E
M8E0R3 E
A0A6J5IRX5 Y
W5WIX6 Y
Q82X47 M
I4DBY0 Y
A0A6F8TLE9 Y
A0A1G7UZX2 E
A0A6P4JM51 E
G0J614 E
U2WTW8 E
A0A642KQG8 E
Q1AUG3 E
A0A6G9Y3Q0 Y
B8J5X4 E
M7NFH3 E
A0A0E3R6S1 Y
Q2IHY5 Y
A7I8Z2 Y
L1IYP4 Y
B4HDZ9 E
A0A366WYI9 E
E4TJ50 Y
A0A7S0ILH2 Y
A4BAE1 E
B3QRJ4 Y
A0A5C5BWI6 Y
Q7NQY2 Y
A0A091AXI3 Y
Q1QSQ2 E
R4FZE3 E
A0A2N0MZ27 Y
A9BTK1 Y
A0A242NIL1 Y
G0LFE3 E
A0A1B9NQ91 Y
A0A5M5PZE2 E
A0A0D2NYP3 Y
D9QPE5 Y
I5B3H0 E
L1IYW7 Y
C6WEW7 Y
B7FW68 C
F4GED5 Y
A0A4R8GSH7 E
A0A1W2H3F0 E
A0A3E2T713 E
A0A0H3KTD3 Y
A0A1Y4LM49 E
G2PRJ6 E
A0A0X8X7Y7 E
K8EJ02 Y
A0A1L3F1X5 Y
G8TK77 Y
A0A855F5Y8 Y
A0A975BTN0 Y
A0A562RGZ4 E
G5EB09 Y
A0A833LX85 E
U1H1F7 Y
K8W1E2 Y
E3HJW8 Y
Q7SEH0 Y
Q47X17 Y
B0DXT9 Y
A0A3G9G2C9 Y
Q95P70 M
A0A837C6X5 Y
Q89WR5 Y
A6DUG4 E
D7UQE2 M
A0A2I1M481 Y
A0A0T7GZ59 Y
O66395 Y
J3EXK0 E
A0A1B9MYL7 Y
K9U8C7 E
E2SD44 Y
H6LKH6 Y
Q605Y6 Y
A0A9Q9D9I3 Y
A0A6N2TIA4 E
A0A1E3PQH0 Y
A4CMI3 E
Q1K0H9 E
A0A0S6UEK9 Y
A0A0H3LUA3 Y
B9LU00 E
A9BIZ7 E
A0A7H8UK07 Y
E3H8C9 E
M2A398 Y
Q1QS12 Y
G0VI62 Y
A0A1Z3MS36 Y
A0A0B5FNH4 E
D9SI36 E
A0A410JZR4 Y
F7ZJZ1 E
F0ZCX7 M
W0DZX1 E
A0A4R3ZZ35 Y
A0A317G0I6 E
Q0ARJ4 Y
A7I8Z4 Y
T2KJ59 E
I3C0V3 E
E3H8A6 E
B2IJT1 Y
A0A2G6JLT9 E
A3ZZL7 Y
A0A2T0XPP2 E
Q31CR9 E
A0A1R1IDV3 Y
K2JVF8 E
V5BYZ7 Y
D8J4C6 E
D4H5F9 E
K9ZG59 Y
A0AA86YS65 Y
Q608B6 E
A0A562BXM4 Y
A0A401WXG0 Y
A0A857DMN9 Y
A0A1X6N3Q5 Y
A0A173R3X4 E
Q63EK5 Y
K9ZLY2 E
A0A533I6R2 Y
I0WJ97 E
K0N2R5 Y
M0J579 E
B8GGC1 Y
A0A6H9GFU4 Y
C6CBB1 Y
A0A510HHK8 E
A0A1B9MBX6 Y
A0A9Y2AG30 Y
E8RSE4 Y
F2B2B8 Y
Q7UYZ3 Y
I1YJH7 E
A0A853MG28 E
A0A0L0STS6 Y
A0A251XU71 Y
Q60BI2 Y
A0A829X098 Y
F3KUN4 Y
Q60C43 Y
A0A0T7FAP8 Y
A0A3E2TW06 E
W0E077 E
A0KPE9 Y
R7PZ71 Y
A0A0A1ZMZ9 E
A0AA40J491 Y
D3S2L0 Y
A0A373FQ71 Y
A0A0A2C6L1 E
Q7W7D3 Y
A0A165K0X5 E
A0A2S5X482 Y
R9GM11 Y
Q0G0A3 E
D4GLQ6 Y
E7RJZ0 E
F8IJE0 Y
A0A1V2XMU9 Y
Q7TNN9 M
A0A1G5RZU9 E
A0A2N6K4Y5 Y
B0SLB7 Y
A0A251YFS0 Y
B9WDK0 Y
Q7N0M6 Y
A0A0M2LU39 Y
F4B548 Y
D6Z5V9 E
A0A4R2M206 Y
A0A1E2SKM1 S
A0A127JTU2 Y
A0A212AV03 Y
G4QHD2 E
A0A021VMC6 Y
A0A2J7TJ33 Y
G7WDB5 -
Q6BK68 Y
Q1K3N8 E
A0AA91Q161 Y
A0NJ07 -
A0A316BQ38 Y
A0A377PLP5 Y
W7QGM4 E
A0A015YIP3 E
A0A060UWC8 Y
A0A1I4ZIZ6 Y
A0A264VQM8 Y
A9AUR8 Y
A0A1W5PRD1 M
A0A0E3BR91 Y
A0A1B0ZRL8 E
B9ACS5 Y
Q92BJ7 Y
F2JTN3 E
A1AVV2 Y
D2Q0J8 Y
A0A3S9N9F3 Y
A8ZQD5 E
C3X831 Y
A0A1M6BPM0 Y
A0A8F5VN39 Y
A0A1E5C7W4 E
A0A2S5WV24 Y
A0A833GZR2 E
C7M2A9 Y
A6W7U2 Y
W0JIB3 E
Q07UM3 Y
A0A066ZRQ5 E
S0G181 E
D3PAH1 Y
Q4WHC6 Y
A0AA94HTL8 Y
D5ASL9 Y
A0A4U1JNL6 Y
M0MDP9 E
A0A653N397 Y
A0A2S8GSU9 Y
A0A097R891 Y
A0A8H7U3I1 Y
A0A1H1MB73 Y
A0A016XDZ5 Y
A0A1B9JHS5 Y
D3PE53 Y
A0A9J9BAE8 E
Q2RM12 Y
A0A3N0AQL8 Y
C5KTM6 E
M1P5F0 E
I1YG38 E
A0A660CH85 Y
A0A2N7L7C8 E
Q5KZZ9 E
M1NZT5 E
A0A225CMT8 Y
A0A068NV61 E
H2CJI0 E
B0DU93 Y
Q221S8 Y
F4Y3C5 E
Q94CJ2 M
M0D3Q9 E
A0A3P2A7W8 Y
C0GKN4 E
Q7T3R4 M
A0A562USB9 E
A2SS52 Y
A0A211ZGL5 Y
A0A4V3ALP8 Y
A0A147GP06 Y
H2IZ00 Y
Q45HK8 Y
A0A6C8LST1 Y
A0A257T8W6 Y
Q5P470 Y
I5AZQ4 Y
Q07UM1 Y
E5B358 Y
A0A1Y4L5P0 E
Q3AFY9 Y
B0BZN3 E
A0A1Q2C7H7 Y
A0A4R5U5V1 Y
H6LKX6 E
A0A1Y0UZX2 Y
F6BEI0 E
M9RKT6 E
A7SGD4 E
A0A257TE48 E
R1FI09 E
E4N1T5 Y
U1PIR6 E
F2JYR9 E
Q84KJ7 Y
A0A2S8FTB5 E
D2R647 E
G9Y5B0 Y
A0A144NLT9 Y
A0A5J6WQU1 E
D2R355 Y
F3ZYD6 E
B0SL05 E
A0A5A7MAJ9 Y
A0A977NL43 Y
A0A433ZQ80 Y
A0A1Y0V4A5 Y
A0A1M7UEG2 Y
G8R7U9 Y
K1LDP0 E
B7G0Y4 C
A0A2W4ZXC0 Y
B3PF77 E
Q2KZK9 Y
Q18ES8 E
D3F545 E
B4S394 Y
Q1Q357 E
Q9H310 M
D3PKL4 Y
M5SY07 Y
Q8RUT6 C
A7NKH2 E
Q1Q879 E
A0A1B9M5B8 Y
A6LRS5 Y
J2ZGN6 E
V5E0F3 Y
A0A149RQX0 Y
A0A165BP25 Y
C0QSY0 Y
B0XVV6 Y
E0SD83 Y
A8HSA2 C
A0A1E3PSK5 Y
A5DYQ2 Y
A0A4U1K1W1 Y
Q0AT01 E
A4FMG0 Y
C3YB73 E
A0A9P3CXY2 Y
A0A0L8BVU4 Y
A0A401WUW1 Y
I4C9L2 Y
Q8RUE9 M
F0JGZ1 Y
A0A2I0UUY1 E
A0A542XGT4 Y
G0JRH4 Y
A2SPS8 Y
A0A5M4AWD2 E
Q6QH01 C
D3F0Z1 E
A6XBM2 M
D6E7B3 Y
Q13E03 Y
A0A060URB8 Y
A0A2T1N7R1 E
D6TCH6 Y
B0CXH8 Y
A3TVQ9 E
Q4WT12 Y
C7QGX3 Y
F0Y9X3 E
A0A7S0D560 Y
A0A160KTE9 Y
A0A2H1HV86 Y
A0A251Y3N4 Y
A0A419AVL2 Y
A0A4Q2QWS1 Y
C7Q1E4 Y
A0A5C5TYS5 Y
F2NNQ0 Y
A0A2R4TRE0 Y
K9YJQ3 E
D9QS43 E
A7SQ16 E
A1DG05 Y
U1SIR9 Y
C4Y298 Y
A0A9W3LFI9 Y
D3RMV7 Y
F3QNA7 Y
E4RTK5 Y
C8XBX8 Y
C0QTA4 Y
E6VIW4 Y
A0A2S6H643 Y
Q46HB1 E
A0A2S5CTX8 E
A0A1T4SF40 Y
K0K7J4 Y
A0A1J5JH24 Y
Q6LMI6 E
A0A9W5JBA9 Y
A0A291PMC6 Y
A0A4Y4DZN4 Y
A0A2R4MBA2 Y
R9PI53 E
A0A6H9GLV4 E
A0A7S4GND2 E
A0A6H9FPY5 E
A0A1G7DX68 Y
A0A075WEB4 Y
A0A140NHJ5 Y
A0A1C6Z081 Y
Q5FA36 Y
Q0ACK1 E
A0A975GIX9 Y
A0A323UE08 Y
U7VB41 Y
A0A063Y780 E
C5CIT6 Y
A0A0A2VPU3 Y
F0RHS0 E
A0A2S5WX34 Y
C1G973 Y
A0A2S6GKF6 Y
A0A0A2B651 E
A0A4R3A5P7 Y
A0A2A7U6W1 Y
Q2GX26 Y
F5XN43 Y
A0A0K2STH0 E
A0A1H1U2Q6 Y
A7SED8 L
A0LV78 Y
K5DBA0 E
B8IZX4 Y
A8LKQ0 E
A0A5C6LWQ1 Y

In [135]:

seqedg = []

for i in edg:
    print(i.id, i.seq)
    seqedg.append(i.seq)

A0A858ZNJ3 E
A0A1H9M798 E
B0DY50 E
P69680 E
A0A3G9G4Q4 E
A0A149UP06 E
F2G6G4 E
A0A2M9D7S8 D
A0A034WGQ2 -
I0KDC6 -
F8D7H6 G
K9W4V5 E
Q466Y3 E
D2SE15 D
A0A377PBY1 E
B1JZ69 D
A0A2W5HTC3 D
A8G2S3 E
D5T4N9 G
Q2RWY7 E
A0A0E3R4G0 -
I4C9L0 E
D5VJ32 E
C0Z5S5 -
C1N6X9 E
J7ITF6 -
A0A068SVR1 E
A0A0D7F328 D
Q0G0A4 E
F0J3F9 D
Q0BQ69 D
F2YIC4 G
D4XLN6 E
A0A420WC79 E
A0A5C5TUT2 E
A0RUZ2 D
A0A0A2ZRL7 E
J4UGB7 D
E5Y678 G
A0A0D2KGN8 E
S5ABR8 E
A9DQM8 G
G5EB13 E
A0A2N6NEK4 E
C6DB68 E
Q81GN5 E
Q0F2M5 E
A0A0C6P439 E
B9SWW9 A
L8H5K0 G
Q9NIV0 G
C1N5A7 E
Q1JXS5 E
A0A1M6JKY3 E
F4D1J0 D
A0A257SYX3 G
V4RK08 E
G0V8D6 E
A0A7S4GMD8 E
B3QVV5 -
F2JZ83 E
A0A857DDJ7 -
A0A0S6UHP2 -
D5EP71 E
F4KY49 E
M5S9B4 G
A0A009PYN3 -
A0A3T0SZ22 D
A0A248LMH8 E
A0A6H9GEE4 E
A7HSP2 D
A0A7V8IKS6 E
T2JFS5 E
F6FRU9 D
A0A9E9L9J1 E
A0AIW5 E
A0A0E9NHV4 E
Q2N625 E
C8WSI9 E
A0A1H1BPD6 D
A0A176XNC5 E
A0A4V0XUI3 E
A7S3L2 E
M5U2P1 G
K9P5D1 -
Q0F2M7 E
A0A2R3IMJ8 E
Q2RVB5 E
A0A556RTU3 E
E0TGP9 E
B7G0Y1 E
A0A1G9P6Q0 E
D0LTW3 E
Q6BT62 E
Q2IK04 E
Q6BJI7 E
B7X047 E
A0A068NPW2 -
A0A399NT81 D
K0F9X7 D
A0A037ZMW1 E
A0A075JZ35 E
A0A369MHK2 G
A0A1B9JPL5 E
D8PD01 E
A0A2G5BI87 E
A0A2G5BGA9 E
A0A657K391 E
P69681 E
A0A4P6UIJ8 D
A0A0V8M0W6 E
A0A0H2XSU4 D
Q1Z695 E
A0A7Z0V0A4 E
K0ER80 D
A0A149UWF2 E
G0H0Z6 E
G0EFF3 E
C8WLL8 G
X5CNT2 G
A0A4Y1MSE7 D
H2CLF7 E
M4VEJ9 -
A0A4V2X6C2 E
A0A2K1RA77 G
A0A375YPN6 E
A0A7M6UUM4 G
A0A172YCA7 E
A0A918MJ52 E
A0A2S8QA29 E
A0A251XJT0 D
A0A0B4E6X7 E
A0A0K2STQ7 E
A1C5Z7 E
C9KKP2 E
A0A2Z4MD56 -
Q9VFA9 -
A0A502GPV4 E
I5C044 E
D2V6P8 G
D3RN22 E
Q97L80 E
A0A0D5YN10 -
A0A1I5GN22 D
A0A1Y5E8I7 E
B1Y8C9 E
M5SYZ1 G
Q6HM26 E
A0A379A0S9 E
A0A101DCS3 E
A0A1Y3U5V2 G
A0A202B535 E
F8E6R1 E
Q6ND36 D
A0A8H6K7L7 E
Q7NCB8 D
A0A369MRW6 G
C9RS76 E
A3U857 -
A0A127PIQ9 E
B8FGW0 E
A0A060JMP6 D
D5V7B3 E
A0A494JB70 E
A0A5M8QF12 D
A0A8G2F3G4 -
J7L3W8 D
G0JRG9 G
D3DJN2 E
A0A1Y2JH43 E
Q1L727 -
A0A7T2S0Z6 E
A0A315S845 E
A0A2S6H6B7 E
A0A1J5NTP7 E
A0A0E3QY86 G
A0A096EEV9 E
A0A380S5X4 E
B8ZYW3 G
A0A2S8GEJ5 -
A0A248TDF2 E
B2GFN1 D
U1PPI7 G
C7LW88 -
G3A431 E
A0A066ZTE4 E
L7CG99 G
S0ET45 E
A0A178TA08 E
H1XV27 E
A0A6M3ZJI1 E
U5DEY6 E
H6LFQ2 G
Q6CRN0 E
A0A4Q2EAG7 E
A0A1J5NNB8 -
E3I393 E
A0A243SC06 -
D4F313 E
W0F0I7 -
A9B874 E
A1D2Y5 E
T2J0N1 E
Q2FQT3 E
A0A075WG29 E
A0A979GQ79 E
A0A381CAY8 E
A0A2G3DSU6 E
A0A168EVK8 E
A0A094W9G3 E
A0A4R3NVT3 E
W0DYY3 E
G8JTW0 E
A0A4P6UIK6 E
I9P003 E
G2T1Y3 E
B8EMQ8 E
I6Z905 E
E0TCV4 E
A3XNG6 G
A0A087MGU4 E
A2BUP4 E
A0A562S8V2 E
A0A495DND0 E
A0A0S2FHD7 E
F3QPR6 E
A0A063Y394 E
F6G5I9 E
A0A323UDG5 D
A0A0G9HEC5 E
B8FDY8 E
Q5KPM5 E
A0A147EQL9 D
A0A854Q6X9 E
C3X1J1 E
A0A5B2V3B9 E
A0A258FS85 E
A0A7T2W1B3 E
A0A060UN76 E
G0JRQ3 E
D5UD26 D
G2ZN72 E
A0AA46Q839 E
A5UJR1 G
L1INN6 E
C1F584 E
C5LAG4 E
A0A2A2MCP3 N
B1Y6V4 E
A0A1G6ABK5 E
A0A6A1TYJ4 E
A0A2T4UWF1 -
V4AP67 E
A0A173R3W6 -
C7NND3 G
B0DFJ4 E
A0A3E2VY88 E
R1EDV9 E
J1L5M8 E
D7G265 E
Q8ERT9 E
I4D6Z9 -
A0A4R6DFU8 -
A0A060URC3 G
D2BIB2 E
F5ISF6 E
A5CRL2 D
A0A6G9XJV9 D
Q59UP8 E
A0A6N4SPH9 E
I0HGY4 -
X5DX97 E
L1J6I4 E
I1DSU5 E
B9L7N1 E
Q1Z4I4 E
Q21CP1 D
A0A165MFD1 G
V4CRP5 E
Q7S5K0 E
A0A071MMV1 D
A0A149RYW7 E
A0A7G5EC77 E
A0A1W2GZ82 E
A0A7U3XVQ4 -
A0A071M4L5 E
U5C2K4 E
A0A248LNW8 E
L8H844 E
A0A149V596 E
S9QZ09 E
B1ZSW9 E
D2BUJ8 E
A0A9Q8L398 E
M5S735 E
Q6ARH0 E
K6W5X0 D
G0JRG6 G
A0A6H9FYW4 E
A0A0S4WFM4 E
A0A101HKN9 E
Q9REX3 E
F0S3Z6 E
A8NAG3 E
C6LBD3 E
A0A149U2G9 E
V4REY8 E
A0A0H3H4I7 E
A8N2H6 E
S0APH6 E
A0A017SYR8 E
A0A1B9MZ78 E
E4T3F3 -
D7E934 E
A0A0M3AB44 D
A9WHW6 E
A0A5M4AUM9 N
A0A1X4GBG2 E
I4D1H5 -
A0A0E3QYF3 E
B0CQX4 E
A0A378YR15 E
A0A495D4X4 E
A0A076PL76 E
Q1YDY7 E
A0A3E2UCG9 E
A0A2K3DPU7 -
A0A3R9Q7C4 E
V5U2Z4 E
K9P718 E
M1V7W3 E
Q6LKC8 E
E5Y789 -
J9Z839 G
A0A1G7VM92 E
K9Z0D3 E
A0A482TED1 E
R1EGK6 E
J1ASR8 E
A0A7U4E420 E
K9YR86 E
A8PXT8 D
A0A0U1NJW3 E
B8FL88 E
A2CCK1 E
D6TFE1 -
A0A2H4U5R1 G
I2GD40 -
A0A060HFT5 E
B1Y842 E
A0A0X8NXA9 E
A0A0A2A5X1 E
A0A318FY98 E
Q7V4T8 E
A0A1A0DHK0 E
C1A872 D
A0A395VB65 E
A7MFK3 E
J4KM12 E
A1SY01 -
A0A1H4DJ49 E
A0A9R0NTP8 D
A3PAY4 E
B4CV94 E
A2C095 E
Q2HD43 E
A0A836M2B6 -
H6RWK9 -
A0A087EQK8 G
A0A1I0AQM4 G
L7CG11 E
A0A248LNK5 G
B7FTM9 E
L0K9M1 E
I4D6Z7 D
A0A2K1RA81 G
Q2WBF7 D
A0A1B9BUU6 G
A0A2S0JW39 E
A0A2S5YID7 D
B3PIH2 E
U3P8G1 -
C9R9J0 E
A8AC17 E
F0YLV7 E
A0A1D3GAE9 E
C1MHX0 D
A0A1H4KAQ7 E
A0A2T4XZC1 E
A1B3N0 E
C7LW87 E
A1SZ12 E
A0A2T2Y0D5 E
A0A1H8D0R8 G
A0A2S5V2F6 G
G3IYW2 E
F5L8M7 E
C7BJG7 E
E4U5Z1 G
A0A1B9K8L2 E
A0A2S5WMT7 D
A0A0D2UPA8 T
A0A161SKF4 D
B4D7W2 E
A0A1H3WA00 E
C1D6X6 G
A0A4D6KHD1 G
Q488X2 E
A9V5W4 G
A0A5M4ATH9 -
E4TRS4 E
A0A011U1K7 E
C7R314 D
A0A077EFU9 E
A0A0A2A0Y9 E
A0A0D8BQX6 E
A0A0L0S493 E
A0A328Q6M1 G
A0A016XCG9 E
B7FSA7 E
G0AFH4 E
A0A177W826 E
A0A2S8GF54 E
Q1YDY8 E
Q5QVH2 E
A3ZT81 E
A0AA35XZV0 E
F4H924 E
K0NJH2 E
A0A1V3SSW1 E
F2AUF4 G
A6DN47 E
W8KM07 E
A0A1X3RP39 E
A0A7S0KKL8 E
A0A318QZ80 E
K8VZC6 E
A0A1B9JZS5 E
A0A2S6GKN5 E
A0A4R2Z2K6 E
H1YCC3 -
E1QIU3 -
A0A8H6MPB9 E
A0A369N7Y3 G
T2IEJ2 E
H5UND3 D
Q1PX09 E
A0A149TSA9 E
F2NGJ8 E
A0A0E3SHQ9 E
Q5FLR6 G
S0EUS1 E
A0A369M386 G
W0DZS7 E
A8MCL4 E
V3ZVE4 E
O26757 E
A0A317FZW2 E
A0A085GI50 E
A1ZGK6 E
G0IYI2 E
A7S731 E
A0A1U9YY82 E
A0A328EMN2 E
A0A8E2UDJ3 D
A0A2S5WUP6 G
A0A8H7P8U1 E
A0A257T7G4 G
B3MX93 -
A0A1G5W0P2 E
D4H2Y7 E
A0A4P8HC89 -
Q7T070 G
F7NPQ3 -
B9SA70 G
Q9M6N7 G
I7ZHW3 E
F4XTK4 E
A4G1J2 E
G7WFX4 D
B8JBH5 E
D9QPC8 E
A0A4R7GKA0 E
R9PMC6 E
A0A0E3LMT4 -
A0A511NGC7 E
E4NS62 E
E4T3F7 E
M0D580 E
J7J5E7 -
B1XZU2 E
A0A366IE34 E
A0A6U2BIY7 E
Q9QXP0 G
A0A424WAH3 E
A0A410K1J5 E
L1IHZ8 E
I8TC71 E
A0A7U8C744 E
A8M670 D
A0A0S4VNK2 E
Q2SIR0 E
A0A5C4RNH5 E
A0A3E0X011 E
A0A0E3SP24 G
E1IF27 E
Q2YBP7 G
A0A2S5WZU0 D
A0A172YBR4 E
A0A0K2STK6 E
A0A2N6JV02 E
F0S0G1 E
A0A1C7EL50 E
Q18PF5 G
A0A1I0C958 E
A0AA35XVN2 E
L8GGA0 E
Q3AP28 E
D0MFE9 E
J9VXX9 E
A0A166IS52 E
F0J7D3 G
W7QG13 E
A4BMY5 E
A6LV49 E
Q1H483 E
A6M3G0 G
E4T0A4 N
A0A3E2UHE6 E
A0A174SD65 -
A0A855EH99 E
C3YB74 E
A0A074KZD8 E
J0S2I0 E
K9WSX4 G
E8RLT5 E
Q2FS34 E
Q3Z7F9 E
Q2S8H9 E
A0A060HN92 E
E6ME92 G
A0A172RYW3 G
L0FU80 E
C8WZE0 E
A0A2S8F4W0 E
A0A2C6C0X3 E
F3ZVV4 E
A0A7R6PER3 E
A0A495WJM6 -
A0A0B4DUR9 E
A0A251YU48 D
A5D4I5 E
A0A2X2C038 E
A0A2A2M8K7 E
D3FBG3 E
A0A2V4EA49 E
D0MFE8 E
Q3B6Q2 E
A0A1B9KID3 E
A0A9J9ES23 E
A0A3N2SFS2 E
Q0VLH1 E
A0A1U9Z147 -
Q0G2T1 E
A6GJF5 E
A0A059XXR1 G
A0A5J6WPP9 E
P41948 E
L1IUV5 E
A0A2W0GQV0 E
Q1K433 E
A0A4Y7XC43 D
D5AU98 E
E1QFA8 E
A0A075WBP9 E
Q0BWD0 E
A0A1Y0HX98 D
A0A098S5Y7 E
Q0I445 E
A0A1E5BXA4 E
A0A2C9CK98 E
G4H971 E
A0A1I0BYN1 -
A0A330GB00 E
A0A2S8FR08 E
Q84KJ6 G
A0A2S5WGI8 G
M2ALH9 G
A0A2K3DQF8 E
A0A8G2IZM3 E
F5Y3C1 E
A0A370FPU0 E
F5RGM7 E
A0A4R4K1P9 E
R8VWI7 E
A0A0A2AMW2 E
Q7Z1M1 -
A0A414NWT8 E
A0A0P6VSR8 E
A0A0L0TDW1 E
U3PCH5 S
W7QGE0 E
C5BWX7 D
A0A1B9M1A9 E
B8GGC3 E
D6SPD1 E
A0A0H3DR67 E
A0A4R7VEK0 E
G4R7P1 E
A0A1M5ZVP9 E
A0A2S5Y0D3 D
I0ICG0 G
D0L8H3 G
A0A1B9LFW3 E
Q6ND34 E
A0A6H9GWG4 E
Q5UZ98 G
A0A2S0P9T4 E
H2CDR5 E
T2KGT3 E
A0A088E6Q7 E
A0A258HS77 E
E1V4T3 E
B7GKP4 E
Q9QUT0 G
I3Z3H7 E
G7WCB6 -
A0A1Y6GLJ1 E
A0A0S2DQB6 E
Q6CRN1 E
A0A401X433 E
A7HT14 E
A0A009TDB1 -
D4XSW0 E
B0SRS8 E
A0A149QSR6 E
B1Y0E5 E
Q7UGU7 G
A0A2S0Q8P1 E
F0ZPL3 E
A0A2T0GTU1 D
I4CCD1 E
A0A9Q6P4A5 E
A0A418VIJ8 E
C1MX19 E
A0A1B9BUZ8 E
K9W6F3 E
Q1K8A3 D
L8GFX3 E
A0A1G6ABL9 D
A0A087L0B9 E
A0A073CP02 E
A0A0A1ZJU5 E
A0A258HPP1 E
A0A149QAW7 E
D2V6Q5 E
A0A1X4G8K1 E
A0A067Z3S3 E
A0A8F5ZDT8 E
A0A854QN45 E
A0A2N7LCD7 E
G7WFX2 E
A0A7S4GNJ2 E
A4G0C5 E
A6VE60 E
A0A1S1HM83 N
A0A037ZJY5 E
N1WR17 E
Q2W5V2 E
A1VIM5 E
A0A1Y5E3E3 E
A0A1T4SFK4 E
A7RNC3 E
M7XJ51 E
A0A399T909 D
A0A2N6P374 D
H8L2Q4 E
D5EP68 E
E6SF19 D
A0A1T4SFY6 D
D3LBI0 G
E6W5C1 E
Q0VPH4 E
K9WT03 E
L0KW14 E
A0A4R8H081 E
A0A1B9N3H7 E
B0RC35 D
A0A420KGW4 E
A0A4R3NLV5 E
Q47K18 E
Q21P82 E
M1WRK6 -
A0A290XBB5 E
A0A6T9XUR2 E
A0A1J1JH03 E
I3R0S7 E
A9UR54 G
A0A1G7H8X3 E
A0A8G2F718 -
Q1H0G2 E
D0LAL7 E
C7LQR9 E
A0A1G5PWV0 E
K1K628 E
B9SXC7 G
G7WA28 -
Q1IWN6 -
H6LKH9 G
A0A1H7CU41 E
G8JUJ2 E
A0A081N2G5 E
A0A074ME37 E
Q0VQH6 E
C8XB51 D
A1VIG8 E
Q8GQS1 E
A0A1I7FBM5 G
A0A1M6ZMI3 E
A0A482PLH3 E
A0RXK8 D
D0KXQ0 E
Q8JI14 G
A0A7T4WEP4 G
A0A4R3ZNW3 D
A0A074KY88 E
A0A6M3ZKU5 E
M1SJL5 E
A0A1W9KSU5 E
E3GI40 E
A0A369NYJ2 G
A0AA92K392 E
O04161 E
A9BQZ4 E
A0A6N2Z556 G
A0A8H6NAG3 E
A0A2T9X1V4 E
Q2J376 E
A0A0F5EZP7 E
A0A7G5DK18 E
M9YAI9 E
D2ZRW2 G
G7UUY6 E
A0A8H4GS02 E
A0A2T5IHP0 G
A0A165MAC2 E
A0A7S4LPS8 E
A0A075JIN0 D
C8X554 -
B8FZP7 -
Q5KAF6 E
A0A427KNL6 E
A0A7G5DPV0 E
Q22947 G
A0A1S1HRJ0 E
A0A3N1VXY4 E
A0A2S7YPJ9 E
I0JI83 E
A0A7U3YMN6 E
Q9BLG3 E
A0A1H9RTW8 E
A0A1I4W3A0 D
A0A0B4M163 G
U2EN72 E
A0A2W5VAZ2 E
E4YA63 E
D5ELM4 E
M9RJS5 E
A0A2G3E8V2 E
Q5FSX6 E
I0HKQ8 E
A0A833H2R7 E
B8ENL9 E
B3DUX7 -
A0A1D8UWJ6 E
D5E995 E
A0A7U8C2Y6 E
L0KGR8 E
B0VMH1 -
P40260 E
L0JT30 G
C1GR74 E
A0A423Y4I6 E
A0A4P7UHQ5 E
A0A8E2R1Y5 D
I5BYV5 E
A0A6B8N021 E
A0A7G5DPV1 E
A0A2G5RQK9 E
A0A5M4B0G1 N
A0A6S5K4J1 E
C1D4X0 E
A1SVA8 E
H1YF74 -
A0A8B4RWH8 E
A0A0A0D6K5 D
A0A0A2BBY0 E
A0A089ZBW5 E
A0A068TC78 E
Q46G49 G
A1CQ21 E
A0A1G6ABX1 E
E1SLM7 E
K5CFE5 E
Q2YLQ6 E
Q0G2V0 E
A4ABK3 E
A0A9Q5QVI9 E
A0A4Q7Y9I7 -
A9HMD6 E
K9YN27 E
Q9UBD6 G
D9SI59 E
Q8I0L6 G
A0A142VAD6 E
G3IYW0 E
A0A062IU58 -
R1D1H4 E
A0A366XFS8 E
A0A7S4GNF3 E
F0J6E8 E
A0A7U4DN04 E
V4RHR4 E
F7ZJM0 E
A0A2S5XAB8 D
U5C4L4 E
Q21J04 E
A0A142NNN1 D
H1Y7T6 -
F5R974 E
B0DU91 E
A2BP62 E
A7HSN9 E
A0A377I7W9 E
D2RU19 G
G7WJN0 E
E2SD33 D
A0A0D7F2Y9 E
A0AA92EGF5 E
A0A9E9LXV9 E
A4BEP1 E
A0A0E3WZH5 -
F7ZEU9 E
A5E3X2 E
A0A0A3XTJ3 E
A0A830ZZN8 E
A0A1S8D478 D
J7IVQ1 E
A0A2U1SS17 E
S3K1S2 E
C6XKC2 E
A0A2S7YIM5 D
K2IMJ7 E
Q5P1S8 E
A0A7T5BFQ2 E
A0A556SRH6 E
A8P923 E
A0A7G5DKA9 E
L8JUH3 E
A0A0D2LEF5 E
A0A258FTB0 E
A0A5P9P1L2 G
M8E0R3 E
A0A6J5IRX5 D
W5WIX6 D
Q82X47 G
I4DBY0 -
A0A6F8TLE9 -
A0A1G7UZX2 E
A0A6P4JM51 -
G0J614 E
U2WTW8 E
A0A642KQG8 E
Q1AUG3 E
A0A6G9Y3Q0 D
B8J5X4 E
M7NFH3 E
A0A0E3R6S1 N
Q2IHY5 E
A7I8Z2 E
L1IYP4 D
B4HDZ9 -
A0A366WYI9 E
E4TJ50 -
A0A7S0ILH2 D
A4BAE1 E
B3QRJ4 E
A0A5C5BWI6 G
Q7NQY2 E
A0A091AXI3 E
Q1QSQ2 E
R4FZE3 E
A0A2N0MZ27 E
A9BTK1 E
A0A242NIL1 E
G0LFE3 G
A0A1B9NQ91 E
A0A5M5PZE2 E
A0A0D2NYP3 E
D9QPE5 E
I5B3H0 E
L1IYW7 D
C6WEW7 D
B7FW68 E
F4GED5 E
A0A4R8GSH7 E
A0A1W2H3F0 E
A0A3E2T713 E
A0A0H3KTD3 E
A0A1Y4LM49 E
G2PRJ6 G
A0A0X8X7Y7 E
K8EJ02 E
A0A1L3F1X5 E
G8TK77 E
A0A855F5Y8 E
A0A975BTN0 D
A0A562RGZ4 E
G5EB09 E
A0A833LX85 E
U1H1F7 E
K8W1E2 E
E3HJW8 E
Q7SEH0 E
Q47X17 E
B0DXT9 E
A0A3G9G2C9 E
Q95P70 G
A0A837C6X5 E
Q89WR5 E
A6DUG4 E
D7UQE2 G
A0A2I1M481 E
A0A0T7GZ59 E
O66395 E
J3EXK0 E
A0A1B9MYL7 E
K9U8C7 E
E2SD44 D
H6LKH6 G
Q605Y6 E
A0A9Q9D9I3 E
A0A6N2TIA4 E
A0A1E3PQH0 E
A4CMI3 E
Q1K0H9 E
A0A0S6UEK9 E
A0A0H3LUA3 E
B9LU00 G
A9BIZ7 E
A0A7H8UK07 E
E3H8C9 E
M2A398 E
Q1QS12 D
G0VI62 E
A0A1Z3MS36 E
A0A0B5FNH4 E
D9SI36 E
A0A410JZR4 E
F7ZJZ1 E
F0ZCX7 G
W0DZX1 E
A0A4R3ZZ35 -
A0A317G0I6 E
Q0ARJ4 E
A7I8Z4 E
T2KJ59 G
I3C0V3 E
E3H8A6 E
B2IJT1 E
A0A2G6JLT9 E
A3ZZL7 E
A0A2T0XPP2 E
Q31CR9 E
A0A1R1IDV3 E
K2JVF8 E
V5BYZ7 E
D8J4C6 G
D4H5F9 E
K9ZG59 E
A0AA86YS65 E
Q608B6 E
A0A562BXM4 E
A0A401WXG0 E
A0A857DMN9 -
A0A1X6N3Q5 E
A0A173R3X4 E
Q63EK5 E
K9ZLY2 G
A0A533I6R2 E
I0WJ97 E
K0N2R5 D
M0J579 E
B8GGC1 E
A0A6H9GFU4 E
C6CBB1 E
A0A510HHK8 E
A0A1B9MBX6 E
A0A9Y2AG30 D
E8RSE4 E
F2B2B8 E
Q7UYZ3 E
I1YJH7 E
A0A853MG28 E
A0A0L0STS6 E
A0A251XU71 D
Q60BI2 E
A0A829X098 E
F3KUN4 E
Q60C43 E
A0A0T7FAP8 E
A0A3E2TW06 E
W0E077 E
A0KPE9 E
R7PZ71 G
A0A0A1ZMZ9 E
A0AA40J491 E
D3S2L0 E
A0A373FQ71 E
A0A0A2C6L1 E
Q7W7D3 E
A0A165K0X5 E
A0A2S5X482 D
R9GM11 G
Q0G0A3 E
D4GLQ6 E
E7RJZ0 E
F8IJE0 E
A0A1V2XMU9 D
Q7TNN9 G
A0A1G5RZU9 E
A0A2N6K4Y5 -
B0SLB7 E
A0A251YFS0 D
B9WDK0 E
Q7N0M6 E
A0A0M2LU39 E
F4B548 E
D6Z5V9 E
A0A4R2M206 E
A0A1E2SKM1 S
A0A127JTU2 E
A0A212AV03 E
G4QHD2 E
A0A021VMC6 D
A0A2J7TJ33 E
G7WDB5 E
Q6BK68 E
Q1K3N8 E
A0AA91Q161 E
A0NJ07 G
A0A316BQ38 E
A0A377PLP5 E
W7QGM4 E
A0A015YIP3 E
A0A060UWC8 G
A0A1I4ZIZ6 E
A0A264VQM8 E
A9AUR8 E
A0A1W5PRD1 G
A0A0E3BR91 E
A0A1B0ZRL8 E
B9ACS5 G
Q92BJ7 E
F2JTN3 E
A1AVV2 E
D2Q0J8 D
A0A3S9N9F3 D
A8ZQD5 E
C3X831 E
A0A1M6BPM0 E
A0A8F5VN39 E
A0A1E5C7W4 E
A0A2S5WV24 D
A0A833GZR2 E
C7M2A9 G
A6W7U2 -
W0JIB3 G
Q07UM3 E
A0A066ZRQ5 E
S0G181 E
D3PAH1 E
Q4WHC6 E
A0AA94HTL8 E
D5ASL9 E
A0A4U1JNL6 E
M0MDP9 G
A0A653N397 E
A0A2S8GSU9 E
A0A097R891 E
A0A8H7U3I1 E
A0A1H1MB73 D
A0A016XDZ5 D
A0A1B9JHS5 E
D3PE53 E
A0A9J9BAE8 E
Q2RM12 E
A0A3N0AQL8 G
C5KTM6 E
M1P5F0 E
I1YG38 E
A0A660CH85 D
A0A2N7L7C8 E
Q5KZZ9 E
M1NZT5 E
A0A225CMT8 D
A0A068NV61 -
H2CJI0 E
B0DU93 E
Q221S8 E
F4Y3C5 E
Q94CJ2 G
M0D3Q9 G
A0A3P2A7W8 E
C0GKN4 E
Q7T3R4 G
A0A562USB9 E
A2SS52 E
A0A211ZGL5 D
A0A4V3ALP8 E
A0A147GP06 E
H2IZ00 E
Q45HK8 E
A0A6C8LST1 E
A0A257T8W6 G
Q5P470 E
I5AZQ4 D
Q07UM1 D
E5B358 E
A0A1Y4L5P0 E
Q3AFY9 -
B0BZN3 E
A0A1Q2C7H7 -
A0A4R5U5V1 E
H6LKX6 -
A0A1Y0UZX2 E
F6BEI0 E
M9RKT6 E
A7SGD4 E
A0A257TE48 E
R1FI09 E
E4N1T5 -
U1PIR6 G
F2JYR9 E
Q84KJ7 G
A0A2S8FTB5 E
D2R647 G
G9Y5B0 E
A0A144NLT9 E
A0A5J6WQU1 E
D2R355 E
F3ZYD6 E
B0SL05 E
A0A5A7MAJ9 E
A0A977NL43 E
A0A433ZQ80 E
A0A1Y0V4A5 E
A0A1M7UEG2 D
G8R7U9 G
K1LDP0 E
B7G0Y4 E
A0A2W4ZXC0 -
B3PF77 E
Q2KZK9 E
Q18ES8 G
D3F545 E
B4S394 E
Q1Q357 E
Q9H310 G
D3PKL4 E
M5SY07 E
Q8RUT6 E
A7NKH2 E
Q1Q879 E
A0A1B9M5B8 E
A6LRS5 E
J2ZGN6 G
V5E0F3 E
A0A149RQX0 E
A0A165BP25 E
C0QSY0 E
B0XVV6 E
E0SD83 E
A8HSA2 E
A0A1E3PSK5 E
A5DYQ2 E
A0A4U1K1W1 E
Q0AT01 E
A4FMG0 D
C3YB73 E
A0A9P3CXY2 -
A0A0L8BVU4 E
A0A401WUW1 E
I4C9L2 E
Q8RUE9 G
F0JGZ1 E
A0A2I0UUY1 E
A0A542XGT4 D
G0JRH4 E
A2SPS8 G
A0A5M4AWD2 E
Q6QH01 E
D3F0Z1 E
A6XBM2 G
D6E7B3 G
Q13E03 E
A0A060URB8 E
A0A2T1N7R1 E
D6TCH6 E
B0CXH8 E
A3TVQ9 E
Q4WT12 E
C7QGX3 -
F0Y9X3 E
A0A7S0D560 E
A0A160KTE9 -
A0A2H1HV86 D
A0A251Y3N4 D
A0A419AVL2 E
A0A4Q2QWS1 E
C7Q1E4 D
A0A5C5TYS5 E
F2NNQ0 E
A0A2R4TRE0 E
K9YJQ3 E
D9QS43 E
A7SQ16 E
A1DG05 E
U1SIR9 E
C4Y298 E
A0A9W3LFI9 E
D3RMV7 E
F3QNA7 E
E4RTK5 -
C8XBX8 D
C0QTA4 E
E6VIW4 E
A0A2S6H643 E
Q46HB1 E
A0A2S5CTX8 E
A0A1T4SF40 E
K0K7J4 D
A0A1J5JH24 -
Q6LMI6 E
A0A9W5JBA9 E
A0A291PMC6 E
A0A4Y4DZN4 D
A0A2R4MBA2 E
R9PI53 E
A0A6H9GLV4 E
A0A7S4GND2 E
A0A6H9FPY5 E
A0A1G7DX68 E
A0A075WEB4 E
A0A140NHJ5 E
A0A1C6Z081 E
Q5FA36 E
Q0ACK1 E
A0A975GIX9 D
A0A323UE08 E
U7VB41 -
A0A063Y780 E
C5CIT6 -
A0A0A2VPU3 D
F0RHS0 G
A0A2S5WX34 D
C1G973 E
A0A2S6GKF6 E
A0A0A2B651 E
A0A4R3A5P7 E
A0A2A7U6W1 E
Q2GX26 D
F5XN43 D
A0A0K2STH0 E
A0A1H1U2Q6 D
A7SED8 G
A0LV78 D
K5DBA0 G
B8IZX4 E
A8LKQ0 E
A0A5C6LWQ1 E

In [88]:
seqn = []

for i in n:
    print(i.id, i.seq)
    seqn.append(i.seq)

A0A858ZNJ3 N
A0A1H9M798 N
B0DY50 N
P69680 N
A0A3G9G4Q4 N
A0A149UP06 N
F2G6G4 N
A0A2M9D7S8 K
A0A034WGQ2 N
I0KDC6 N
F8D7H6 N
K9W4V5 N
Q466Y3 N
D2SE15 S
A0A377PBY1 K
B1JZ69 N
A0A2W5HTC3 N
A8G2S3 N
D5T4N9 N
Q2RWY7 G
A0A0E3R4G0 N
I4C9L0 K
D5VJ32 N
C0Z5S5 T
C1N6X9 N
J7ITF6 N
A0A068SVR1 N
A0A0D7F328 N
Q0G0A4 N
F0J3F9 N
Q0BQ69 K
F2YIC4 -
D4XLN6 N
A0A420WC79 N
A0A5C5TUT2 N
A0RUZ2 N
A0A0A2ZRL7 N
J4UGB7 S
E5Y678 K
A0A0D2KGN8 N
S5ABR8 N
A9DQM8 N
G5EB13 S
A0A2N6NEK4 S
C6DB68 N
Q81GN5 K
Q0F2M5 V
A0A0C6P439 N
B9SWW9 W
L8H5K0 -
Q9NIV0 -
C1N5A7 N
Q1JXS5 K
A0A1M6JKY3 K
F4D1J0 S
A0A257SYX3 W
V4RK08 N
G0V8D6 S
A0A7S4GMD8 N
B3QVV5 N
F2JZ83 I
A0A857DDJ7 H
A0A0S6UHP2 N
D5EP71 N
F4KY49 N
M5S9B4 N
A0A009PYN3 K
A0A3T0SZ22 S
A0A248LMH8 N
A0A6H9GEE4 N
A7HSP2 K
A0A7V8IKS6 N
T2JFS5 N
F6FRU9 S
A0A9E9L9J1 N
A0AIW5 N
A0A0E9NHV4 S
Q2N625 N
C8WSI9 K
A0A1H1BPD6 S
A0A176XNC5 N
A0A4V0XUI3 N
A7S3L2 N
M5U2P1 N
K9P5D1 K
Q0F2M7 N
A0A2R3IMJ8 N
Q2RVB5 K
A0A556RTU3 N
E0TGP9 N
B7G0Y1 N
A0A1G9P6Q0 N
D0LTW3 N
Q6BT62 H
Q2IK04 N
Q6BJI7 S
B7X047 N
A0A068NPW2 N
A0A399NT81 S
K0F9X7 N
A0A037ZMW1 N
A0A075JZ35 N
A0A369MHK2 N
A0A1B9JPL5 N
D8PD01 K
A0A2G5BI87 N
A0A2G5BGA9 N
A0A657K391 N
P69681 N
A0A4P6UIJ8 K
A0A0V8M0W6 N
A0A0H2XSU4 N
Q1Z695 I
A0A7Z0V0A4 K
K0ER80 G
A0A149UWF2 N
G0H0Z6 N
G0EFF3 R
C8WLL8 N
X5CNT2 W
A0A4Y1MSE7 K
H2CLF7 N
M4VEJ9 -
A0A4V2X6C2 N
A0A2K1RA77 W
A0A375YPN6 N
A0A7M6UUM4 -
A0A172YCA7 N
A0A918MJ52 N
A0A2S8QA29 N
A0A251XJT0 S
A0A0B4E6X7 N
A0A0K2STQ7 N
A1C5Z7 S
C9KKP2 N
A0A2Z4MD56 T
Q9VFA9 N
A0A502GPV4 N
I5C044 N
D2V6P8 -
D3RN22 I
Q97L80 K
A0A0D5YN10 K
A0A1I5GN22 S
A0A1Y5E8I7 N
B1Y8C9 N
M5SYZ1 N
Q6HM26 K
A0A379A0S9 N
A0A101DCS3 N
A0A1Y3U5V2 N
A0A202B535 N
F8E6R1 N
Q6ND36 N
A0A8H6K7L7 S
Q7NCB8 N
A0A369MRW6 N
C9RS76 N
A3U857 K
A0A127PIQ9 N
B8FGW0 K
A0A060JMP6 S
D5V7B3 N
A0A494JB70 N
A0A5M8QF12 S
A0A8G2F3G4 N
J7L3W8 S
G0JRG9 W
D3DJN2 D
A0A1Y2JH43 N
Q1L727 N
A0A7T2S0Z6 N
A0A315S845 A
A0A2S6H6B7 N
A0A1J5NTP7 N
A0A0E3QY86 K
A0A096EEV9 N
A0A380S5X4 N
B8ZYW3 V
A0A2S8GEJ5 N
A0A248TDF2 T
B2GFN1 G
U1PPI7 N
C7LW88 N
G3A431 N
A0A066ZTE4 N
L7CG99 N
S0ET45 N
A0A178TA08 Q
H1XV27 N
A0A6M3ZJI1 N
U5DEY6 N
H6LFQ2 N
Q6CRN0 H
A0A4Q2EAG7 K
A0A1J5NNB8 N
E3I393 N
A0A243SC06 K
D4F313 N
W0F0I7 K
A9B874 N
A1D2Y5 S
T2J0N1 N
Q2FQT3 N
A0A075WG29 N
A0A979GQ79 N
A0A381CAY8 K
A0A2G3DSU6 N
A0A168EVK8 K
A0A094W9G3 N
A0A4R3NVT3 N
W0DYY3 N
G8JTW0 S
A0A4P6UIK6 N
I9P003 N
G2T1Y3 N
B8EMQ8 N
I6Z905 A
E0TCV4 N
A3XNG6 N
A0A087MGU4 N
A2BUP4 N
A0A562S8V2 N
A0A495DND0 N
A0A0S2FHD7 N
F3QPR6 N
A0A063Y394 N
F6G5I9 N
A0A323UDG5 N
A0A0G9HEC5 N
B8FDY8 N
Q5KPM5 N
A0A147EQL9 S
A0A854Q6X9 N
C3X1J1 N
A0A5B2V3B9 N
A0A258FS85 N
A0A7T2W1B3 N
A0A060UN76 I
G0JRQ3 I
D5UD26 S
G2ZN72 N
A0AA46Q839 N
A5UJR1 N
L1INN6 N
C1F584 N
C5LAG4 N
A0A2A2MCP3 -
B1Y6V4 N
A0A1G6ABK5 I
A0A6A1TYJ4 N
A0A2T4UWF1 S
V4AP67 N
A0A173R3W6 N
C7NND3 N
B0DFJ4 N
A0A3E2VY88 A
R1EDV9 N
J1L5M8 N
D7G265 N
Q8ERT9 N
I4D6Z9 N
A0A4R6DFU8 S
A0A060URC3 W
D2BIB2 N
F5ISF6 N
A5CRL2 S
A0A6G9XJV9 G
Q59UP8 H
A0A6N4SPH9 N
I0HGY4 G
X5DX97 S
L1J6I4 N
I1DSU5 N
B9L7N1 N
Q1Z4I4 N
Q21CP1 N
A0A165MFD1 N
V4CRP5 N
Q7S5K0 A
A0A071MMV1 N
A0A149RYW7 N
A0A7G5EC77 N
A0A1W2GZ82 N
A0A7U3XVQ4 K
A0A071M4L5 N
U5C2K4 N
A0A248LNW8 I
L8H844 N
A0A149V596 N
S9QZ09 N
B1ZSW9 N
D2BUJ8 K
A0A9Q8L398 N
M5S735 N
Q6ARH0 N
K6W5X0 A
G0JRG6 W
A0A6H9FYW4 N
A0A0S4WFM4 N
A0A101HKN9 N
Q9REX3 N
F0S3Z6 I
A8NAG3 N
C6LBD3 N
A0A149U2G9 N
V4REY8 N
A0A0H3H4I7 K
A8N2H6 S
S0APH6 Y
A0A017SYR8 N
A0A1B9MZ78 N
E4T3F3 N
D7E934 N
A0A0M3AB44 N
A9WHW6 N
A0A5M4AUM9 N
A0A1X4GBG2 N
I4D1H5 N
A0A0E3QYF3 N
B0CQX4 S
A0A378YR15 N
A0A495D4X4 N
A0A076PL76 N
Q1YDY7 N
A0A3E2UCG9 A
A0A2K3DPU7 -
A0A3R9Q7C4 K
V5U2Z4 K
K9P718 N
M1V7W3 N
Q6LKC8 I
E5Y789 R
J9Z839 W
A0A1G7VM92 N
K9Z0D3 N
A0A482TED1 N
R1EGK6 N
J1ASR8 N
A0A7U4E420 N
K9YR86 N
A8PXT8 N
A0A0U1NJW3 N
B8FL88 N
A2CCK1 N
D6TFE1 N
A0A2H4U5R1 N
I2GD40 N
A0A060HFT5 N
B1Y842 I
A0A0X8NXA9 N
A0A0A2A5X1 N
A0A318FY98 K
Q7V4T8 N
A0A1A0DHK0 -
C1A872 S
A0A395VB65 N
A7MFK3 K
J4KM12 S
A1SY01 N
A0A1H4DJ49 N
A0A9R0NTP8 S
A3PAY4 N
B4CV94 N
A2C095 N
Q2HD43 S
A0A836M2B6 K
H6RWK9 S
A0A087EQK8 K
A0A1I0AQM4 -
L7CG11 N
A0A248LNK5 D
B7FTM9 N
L0K9M1 N
I4D6Z7 K
A0A2K1RA81 W
Q2WBF7 K
A0A1B9BUU6 W
A0A2S0JW39 N
A0A2S5YID7 S
B3PIH2 N
U3P8G1 S
C9R9J0 N
A8AC17 R
F0YLV7 N
A0A1D3GAE9 N
C1MHX0 Q
A0A1H4KAQ7 N
A0A2T4XZC1 K
A1B3N0 N
C7LW87 N
A1SZ12 N
A0A2T2Y0D5 K
A0A1H8D0R8 -
A0A2S5V2F6 N
G3IYW2 N
F5L8M7 T
C7BJG7 N
E4U5Z1 K
A0A1B9K8L2 K
A0A2S5WMT7 S
A0A0D2UPA8 N
A0A161SKF4 S
B4D7W2 K
A0A1H3WA00 N
C1D6X6 D
A0A4D6KHD1 N
Q488X2 N
A9V5W4 -
A0A5M4ATH9 N
E4TRS4 N
A0A011U1K7 N
C7R314 S
A0A077EFU9 N
A0A0A2A0Y9 N
A0A0D8BQX6 Q
A0A0L0S493 N
A0A328Q6M1 N
A0A016XCG9 N
B7FSA7 N
G0AFH4 N
A0A177W826 N
A0A2S8GF54 N
Q1YDY8 N
Q5QVH2 N
A3ZT81 N
A0AA35XZV0 N
F4H924 N
K0NJH2 A
A0A1V3SSW1 N
F2AUF4 N
A6DN47 N
W8KM07 N
A0A1X3RP39 K
A0A7S0KKL8 N
A0A318QZ80 N
K8VZC6 N
A0A1B9JZS5 K
A0A2S6GKN5 N
A0A4R2Z2K6 N
H1YCC3 K
E1QIU3 N
A0A8H6MPB9 S
A0A369N7Y3 N
T2IEJ2 N
H5UND3 S
Q1PX09 N
A0A149TSA9 N
F2NGJ8 N
A0A0E3SHQ9 N
Q5FLR6 N
S0EUS1 N
A0A369M386 N
W0DZS7 N
A8MCL4 Y
V3ZVE4 N
O26757 -
A0A317FZW2 N
A0A085GI50 K
A1ZGK6 N
G0IYI2 N
A7S731 N
A0A1U9YY82 N
A0A328EMN2 N
A0A8E2UDJ3 S
A0A2S5WUP6 N
A0A8H7P8U1 N
A0A257T7G4 W
B3MX93 N
A0A1G5W0P2 N
D4H2Y7 N
A0A4P8HC89 S
Q7T070 -
F7NPQ3 N
B9SA70 W
Q9M6N7 W
I7ZHW3 N
F4XTK4 N
A4G1J2 N
G7WFX4 N
B8JBH5 K
D9QPC8 N
A0A4R7GKA0 N
R9PMC6 I
A0A0E3LMT4 N
A0A511NGC7 N
E4NS62 N
E4T3F7 N
M0D580 N
J7J5E7 N
B1XZU2 I
A0A366IE34 N
A0A6U2BIY7 N
Q9QXP0 -
A0A424WAH3 N
A0A410K1J5 N
L1IHZ8 N
I8TC71 N
A0A7U8C744 N
A8M670 G
A0A0S4VNK2 N
Q2SIR0 I
A0A5C4RNH5 K
A0A3E0X011 N
A0A0E3SP24 K
E1IF27 N
Q2YBP7 -
A0A2S5WZU0 S
A0A172YBR4 N
A0A0K2STK6 N
A0A2N6JV02 N
F0S0G1 N
A0A1C7EL50 N
Q18PF5 -
A0A1I0C958 N
A0AA35XVN2 N
L8GGA0 N
Q3AP28 N
D0MFE9 K
J9VXX9 N
A0A166IS52 N
F0J7D3 W
W7QG13 N
A4BMY5 N
A6LV49 N
Q1H483 N
A6M3G0 N
E4T0A4 N
A0A3E2UHE6 A
A0A174SD65 N
A0A855EH99 N
C3YB74 N
A0A074KZD8 N
J0S2I0 N
K9WSX4 N
E8RLT5 N
Q2FS34 N
Q3Z7F9 N
Q2S8H9 N
A0A060HN92 K
E6ME92 K
A0A172RYW3 N
L0FU80 N
C8WZE0 N
A0A2S8F4W0 N
A0A2C6C0X3 N
F3ZVV4 N
A0A7R6PER3 N
A0A495WJM6 N
A0A0B4DUR9 N
A0A251YU48 S
A5D4I5 N
A0A2X2C038 K
A0A2A2M8K7 K
D3FBG3 N
A0A2V4EA49 N
D0MFE8 N
Q3B6Q2 N
A0A1B9KID3 N
A0A9J9ES23 I
A0A3N2SFS2 K
Q0VLH1 N
A0A1U9Z147 R
Q0G2T1 N
A6GJF5 N
A0A059XXR1 W
A0A5J6WPP9 I
P41948 H
L1IUV5 N
A0A2W0GQV0 K
Q1K433 N
A0A4Y7XC43 N
D5AU98 S
E1QFA8 N
A0A075WBP9 N
Q0BWD0 N
A0A1Y0HX98 S
A0A098S5Y7 N
Q0I445 N
A0A1E5BXA4 N
A0A2C9CK98 N
G4H971 T
A0A1I0BYN1 R
A0A330GB00 K
A0A2S8FR08 N
Q84KJ6 W
A0A2S5WGI8 N
M2ALH9 N
A0A2K3DQF8 N
A0A8G2IZM3 N
F5Y3C1 N
A0A370FPU0 N
F5RGM7 N
A0A4R4K1P9 N
R8VWI7 N
A0A0A2AMW2 N
Q7Z1M1 N
A0A414NWT8 N
A0A0P6VSR8 N
A0A0L0TDW1 N
U3PCH5 G
W7QGE0 N
C5BWX7 S
A0A1B9M1A9 N
B8GGC3 N
D6SPD1 N
A0A0H3DR67 N
A0A4R7VEK0 N
G4R7P1 N
A0A1M5ZVP9 N
A0A2S5Y0D3 S
I0ICG0 N
D0L8H3 N
A0A1B9LFW3 N
Q6ND34 N
A0A6H9GWG4 N
Q5UZ98 N
A0A2S0P9T4 N
H2CDR5 N
T2KGT3 N
A0A088E6Q7 F
A0A258HS77 N
E1V4T3 N
B7GKP4 Q
Q9QUT0 -
I3Z3H7 N
G7WCB6 N
A0A1Y6GLJ1 K
A0A0S2DQB6 N
Q6CRN1 H
A0A401X433 N
A7HT14 N
A0A009TDB1 K
D4XSW0 I
B0SRS8 N
A0A149QSR6 N
B1Y0E5 N
Q7UGU7 N
A0A2S0Q8P1 N
F0ZPL3 N
A0A2T0GTU1 G
I4CCD1 N
A0A9Q6P4A5 N
A0A418VIJ8 N
C1MX19 N
A0A1B9BUZ8 N
K9W6F3 R
Q1K8A3 S
L8GFX3 N
A0A1G6ABL9 K
A0A087L0B9 N
A0A073CP02 N
A0A0A1ZJU5 N
A0A258HPP1 N
A0A149QAW7 N
D2V6Q5 N
A0A1X4G8K1 N
A0A067Z3S3 N
A0A8F5ZDT8 N
A0A854QN45 N
A0A2N7LCD7 N
G7WFX2 N
A0A7S4GNJ2 N
A4G0C5 N
A6VE60 N
A0A1S1HM83 -
A0A037ZJY5 N
N1WR17 N
Q2W5V2 I
A1VIM5 S
A0A1Y5E3E3 N
A0A1T4SFK4 N
A7RNC3 N
M7XJ51 N
A0A399T909 S
A0A2N6P374 S
H8L2Q4 N
D5EP68 N
E6SF19 S
A0A1T4SFY6 S
D3LBI0 N
E6W5C1 N
Q0VPH4 N
K9WT03 N
L0KW14 N
A0A4R8H081 N
A0A1B9N3H7 N
B0RC35 S
A0A420KGW4 N
A0A4R3NLV5 N
Q47K18 N
Q21P82 N
M1WRK6 N
A0A290XBB5 N
A0A6T9XUR2 N
A0A1J1JH03 N
I3R0S7 N
A9UR54 N
A0A1G7H8X3 S
A0A8G2F718 N
Q1H0G2 N
D0LAL7 S
C7LQR9 N
A0A1G5PWV0 K
K1K628 N
B9SXC7 W
G7WA28 N
Q1IWN6 G
H6LKH9 N
A0A1H7CU41 N
G8JUJ2 H
A0A081N2G5 N
A0A074ME37 K
Q0VQH6 N
C8XB51 S
A1VIG8 N
Q8GQS1 N
A0A1I7FBM5 -
A0A1M6ZMI3 N
A0A482PLH3 N
A0RXK8 N
D0KXQ0 I
Q8JI14 -
A0A7T4WEP4 W
A0A4R3ZNW3 S
A0A074KY88 N
A0A6M3ZKU5 I
M1SJL5 N
A0A1W9KSU5 N
E3GI40 N
A0A369NYJ2 N
A0AA92K392 N
O04161 N
A9BQZ4 N
A0A6N2Z556 N
A0A8H6NAG3 S
A0A2T9X1V4 Y
Q2J376 N
A0A0F5EZP7 N
A0A7G5DK18 N
M9YAI9 N
D2ZRW2 N
G7UUY6 N
A0A8H4GS02 S
A0A2T5IHP0 -
A0A165MAC2 N
A0A7S4LPS8 N
A0A075JIN0 S
C8X554 N
B8FZP7 N
Q5KAF6 N
A0A427KNL6 N
A0A7G5DPV0 N
Q22947 -
A0A1S1HRJ0 N
A0A3N1VXY4 N
A0A2S7YPJ9 S
I0JI83 T
A0A7U3YMN6 N
Q9BLG3 S
A0A1H9RTW8 N
A0A1I4W3A0 S
A0A0B4M163 -
U2EN72 N
A0A2W5VAZ2 N
E4YA63 N
D5ELM4 N
M9RJS5 N
A0A2G3E8V2 N
Q5FSX6 N
I0HKQ8 N
A0A833H2R7 N
B8ENL9 N
B3DUX7 N
A0A1D8UWJ6 N
D5E995 N
A0A7U8C2Y6 I
L0KGR8 N
B0VMH1 K
P40260 S
L0JT30 N
C1GR74 S
A0A423Y4I6 K
A0A4P7UHQ5 R
A0A8E2R1Y5 S
I5BYV5 N
A0A6B8N021 K
A0A7G5DPV1 N
A0A2G5RQK9 Q
A0A5M4B0G1 N
A0A6S5K4J1 K
C1D4X0 N
A1SVA8 I
H1YF74 N
A0A8B4RWH8 N
A0A0A0D6K5 N
A0A0A2BBY0 N
A0A089ZBW5 N
A0A068TC78 N
Q46G49 K
A1CQ21 S
A0A1G6ABX1 N
E1SLM7 N
K5CFE5 N
Q2YLQ6 N
Q0G2V0 N
A4ABK3 N
A0A9Q5QVI9 N
A0A4Q7Y9I7 S
A9HMD6 N
K9YN27 N
Q9UBD6 -
D9SI59 N
Q8I0L6 -
A0A142VAD6 N
G3IYW0 N
A0A062IU58 K
R1D1H4 N
A0A366XFS8 N
A0A7S4GNF3 N
F0J6E8 N
A0A7U4DN04 N
V4RHR4 N
F7ZJM0 N
A0A2S5XAB8 S
U5C4L4 N
Q21J04 N
A0A142NNN1 S
H1Y7T6 N
F5R974 I
B0DU91 S
A2BP62 N
A7HSN9 I
A0A377I7W9 N
D2RU19 N
G7WJN0 N
E2SD33 S
A0A0D7F2Y9 N
A0AA92EGF5 N
A0A9E9LXV9 N
A4BEP1 I
A0A0E3WZH5 N
F7ZEU9 N
A5E3X2 H
A0A0A3XTJ3 N
A0A830ZZN8 N
A0A1S8D478 N
J7IVQ1 N
A0A2U1SS17 N
S3K1S2 K
C6XKC2 N
A0A2S7YIM5 S
K2IMJ7 N
Q5P1S8 I
A0A7T5BFQ2 I
A0A556SRH6 N
A8P923 N
A0A7G5DKA9 N
L8JUH3 N
A0A0D2LEF5 S
A0A258FTB0 N
A0A5P9P1L2 N
M8E0R3 Q
A0A6J5IRX5 N
W5WIX6 S
Q82X47 -
I4DBY0 N
A0A6F8TLE9 K
A0A1G7UZX2 I
A0A6P4JM51 N
G0J614 N
U2WTW8 Q
A0A642KQG8 V
Q1AUG3 I
A0A6G9Y3Q0 N
B8J5X4 N
M7NFH3 T
A0A0E3R6S1 N
Q2IHY5 K
A7I8Z2 N
L1IYP4 Q
B4HDZ9 N
A0A366WYI9 N
E4TJ50 -
A0A7S0ILH2 Q
A4BAE1 N
B3QRJ4 N
A0A5C5BWI6 N
Q7NQY2 N
A0A091AXI3 N
Q1QSQ2 N
R4FZE3 Q
A0A2N0MZ27 N
A9BTK1 N
A0A242NIL1 N
G0LFE3 N
A0A1B9NQ91 N
A0A5M5PZE2 V
A0A0D2NYP3 N
D9QPE5 N
I5B3H0 N
L1IYW7 N
C6WEW7 S
B7FW68 N
F4GED5 N
A0A4R8GSH7 I
A0A1W2H3F0 N
A0A3E2T713 N
A0A0H3KTD3 N
A0A1Y4LM49 N
G2PRJ6 N
A0A0X8X7Y7 N
K8EJ02 N
A0A1L3F1X5 N
G8TK77 N
A0A855F5Y8 K
A0A975BTN0 N
A0A562RGZ4 A
G5EB09 S
A0A833LX85 N
U1H1F7 N
K8W1E2 N
E3HJW8 N
Q7SEH0 S
Q47X17 N
B0DXT9 S
A0A3G9G2C9 N
Q95P70 -
A0A837C6X5 N
Q89WR5 N
A6DUG4 N
D7UQE2 -
A0A2I1M481 A
A0A0T7GZ59 N
O66395 N
J3EXK0 N
A0A1B9MYL7 N
K9U8C7 N
E2SD44 S
H6LKH6 N
Q605Y6 N
A0A9Q9D9I3 N
A0A6N2TIA4 N
A0A1E3PQH0 N
A4CMI3 N
Q1K0H9 N
A0A0S6UEK9 N
A0A0H3LUA3 N
B9LU00 N
A9BIZ7 N
A0A7H8UK07 N
E3H8C9 N
M2A398 N
Q1QS12 N
G0VI62 H
A0A1Z3MS36 K
A0A0B5FNH4 N
D9SI36 I
A0A410JZR4 N
F7ZJZ1 N
F0ZCX7 -
W0DZX1 I
A0A4R3ZZ35 S
A0A317G0I6 N
Q0ARJ4 N
A7I8Z4 N
T2KJ59 N
I3C0V3 N
E3H8A6 G
B2IJT1 K
A0A2G6JLT9 I
A3ZZL7 N
A0A2T0XPP2 N
Q31CR9 N
A0A1R1IDV3 N
K2JVF8 N
V5BYZ7 N
D8J4C6 N
D4H5F9 N
K9ZG59 N
A0AA86YS65 N
Q608B6 I
A0A562BXM4 N
A0A401WXG0 -
A0A857DMN9 R
A0A1X6N3Q5 N
A0A173R3X4 N
Q63EK5 K
K9ZLY2 N
A0A533I6R2 N
I0WJ97 N
K0N2R5 N
M0J579 N
B8GGC1 N
A0A6H9GFU4 N
C6CBB1 K
A0A510HHK8 I
A0A1B9MBX6 N
A0A9Y2AG30 G
E8RSE4 N
F2B2B8 N
Q7UYZ3 N
I1YJH7 N
A0A853MG28 N
A0A0L0STS6 N
A0A251XU71 S
Q60BI2 N
A0A829X098 N
F3KUN4 N
Q60C43 N
A0A0T7FAP8 N
A0A3E2TW06 A
W0E077 N
A0KPE9 N
R7PZ71 N
A0A0A1ZMZ9 N
A0AA40J491 N
D3S2L0 N
A0A373FQ71 N
A0A0A2C6L1 N
Q7W7D3 N
A0A165K0X5 N
A0A2S5X482 S
R9GM11 N
Q0G0A3 N
D4GLQ6 N
E7RJZ0 N
F8IJE0 N
A0A1V2XMU9 N
Q7TNN9 -
A0A1G5RZU9 N
A0A2N6K4Y5 N
B0SLB7 K
A0A251YFS0 S
B9WDK0 S
Q7N0M6 N
A0A0M2LU39 N
F4B548 Y
D6Z5V9 N
A0A4R2M206 N
A0A1E2SKM1 G
A0A127JTU2 N
A0A212AV03 N
G4QHD2 N
A0A021VMC6 S
A0A2J7TJ33 N
G7WDB5 N
Q6BK68 S
Q1K3N8 N
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 N
A0A377PLP5 K
W7QGM4 N
A0A015YIP3 N
A0A060UWC8 W
A0A1I4ZIZ6 N
A0A264VQM8 N
A9AUR8 N
A0A1W5PRD1 -
A0A0E3BR91 N
A0A1B0ZRL8 N
B9ACS5 N
Q92BJ7 N
F2JTN3 N
A1AVV2 N
D2Q0J8 S
A0A3S9N9F3 N
A8ZQD5 N
C3X831 N
A0A1M6BPM0 N
A0A8F5VN39 N
A0A1E5C7W4 I
A0A2S5WV24 S
A0A833GZR2 N
C7M2A9 W
A6W7U2 S
W0JIB3 N
Q07UM3 N
A0A066ZRQ5 N
S0G181 N
D3PAH1 N
Q4WHC6 S
A0AA94HTL8 R
D5ASL9 N
A0A4U1JNL6 S
M0MDP9 N
A0A653N397 N
A0A2S8GSU9 N
A0A097R891 K
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 K
A0A1B9JHS5 N
D3PE53 K
A0A9J9BAE8 N
Q2RM12 N
A0A3N0AQL8 N
C5KTM6 N
M1P5F0 N
I1YG38 I
A0A660CH85 S
A0A2N7L7C8 I
Q5KZZ9 Q
M1NZT5 N
A0A225CMT8 S
A0A068NV61 N
H2CJI0 N
B0DU93 S
Q221S8 N
F4Y3C5 N
Q94CJ2 -
M0D3Q9 N
A0A3P2A7W8 N
C0GKN4 N
Q7T3R4 -
A0A562USB9 N
A2SS52 N
A0A211ZGL5 N
A0A4V3ALP8 N
A0A147GP06 N
H2IZ00 N
Q45HK8 N
A0A6C8LST1 N
A0A257T8W6 W
Q5P470 N
I5AZQ4 N
Q07UM1 N
E5B358 N
A0A1Y4L5P0 N
Q3AFY9 N
B0BZN3 N
A0A1Q2C7H7 N
A0A4R5U5V1 N
H6LKX6 N
A0A1Y0UZX2 N
F6BEI0 N
M9RKT6 N
A7SGD4 N
A0A257TE48 I
R1FI09 N
E4N1T5 H
U1PIR6 N
F2JYR9 N
Q84KJ7 W
A0A2S8FTB5 N
D2R647 N
G9Y5B0 K
A0A144NLT9 K
A0A5J6WQU1 N
D2R355 N
F3ZYD6 N
B0SL05 N
A0A5A7MAJ9 N
A0A977NL43 N
A0A433ZQ80 N
A0A1Y0V4A5 -
A0A1M7UEG2 S
G8R7U9 N
K1LDP0 N
B7G0Y4 N
A0A2W4ZXC0 K
B3PF77 N
Q2KZK9 N
Q18ES8 N
D3F545 V
B4S394 K
Q1Q357 N
Q9H310 -
D3PKL4 N
M5SY07 N
Q8RUT6 N
A7NKH2 N
Q1Q879 N
A0A1B9M5B8 N
A6LRS5 K
J2ZGN6 N
V5E0F3 N
A0A149RQX0 N
A0A165BP25 K
C0QSY0 N
B0XVV6 S
E0SD83 K
A8HSA2 T
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 N
Q0AT01 N
A4FMG0 G
C3YB73 N
A0A9P3CXY2 K
A0A0L8BVU4 N
A0A401WUW1 N
I4C9L2 N
Q8RUE9 -
F0JGZ1 N
A0A2I0UUY1 N
A0A542XGT4 G
G0JRH4 N
A2SPS8 K
A0A5M4AWD2 N
Q6QH01 T
D3F0Z1 I
A6XBM2 -
D6E7B3 N
Q13E03 N
A0A060URB8 N
A0A2T1N7R1 N
D6TCH6 N
B0CXH8 N
A3TVQ9 N
Q4WT12 S
C7QGX3 S
F0Y9X3 N
A0A7S0D560 N
A0A160KTE9 S
A0A2H1HV86 S
A0A251Y3N4 S
A0A419AVL2 N
A0A4Q2QWS1 N
C7Q1E4 S
A0A5C5TYS5 N
F2NNQ0 K
A0A2R4TRE0 N
K9YJQ3 N
D9QS43 A
A7SQ16 N
A1DG05 S
U1SIR9 A
C4Y298 S
A0A9W3LFI9 N
D3RMV7 N
F3QNA7 N
E4RTK5 N
C8XBX8 S
C0QTA4 S
E6VIW4 N
A0A2S6H643 N
Q46HB1 N
A0A2S5CTX8 N
A0A1T4SF40 N
K0K7J4 S
A0A1J5JH24 N
Q6LMI6 N
A0A9W5JBA9 N
A0A291PMC6 N
A0A4Y4DZN4 S
A0A2R4MBA2 N
R9PI53 N
A0A6H9GLV4 N
A0A7S4GND2 N
A0A6H9FPY5 N
A0A1G7DX68 N
A0A075WEB4 N
A0A140NHJ5 N
A0A1C6Z081 K
Q5FA36 N
Q0ACK1 N
A0A975GIX9 N
A0A323UE08 N
U7VB41 K
A0A063Y780 N
C5CIT6 -
A0A0A2VPU3 S
F0RHS0 N
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 N
A0A0A2B651 N
A0A4R3A5P7 N
A0A2A7U6W1 N
Q2GX26 S
F5XN43 S
A0A0K2STH0 N
A0A1H1U2Q6 S
A7SED8 -
A0LV78 N
K5DBA0 N
B8IZX4 R
A8LKQ0 N
A0A5C6LWQ1 N

In [89]:
seqd = []

for i in d:
    print(i.id, i.seq)
    seqd.append(i.seq)

A0A858ZNJ3 S
A0A1H9M798 N
B0DY50 S
P69680 S
A0A3G9G4Q4 A
A0A149UP06 A
F2G6G4 L
A0A2M9D7S8 S
A0A034WGQ2 D
I0KDC6 S
F8D7H6 T
K9W4V5 V
Q466Y3 T
D2SE15 N
A0A377PBY1 S
B1JZ69 A
A0A2W5HTC3 A
A8G2S3 V
D5T4N9 H
Q2RWY7 G
A0A0E3R4G0 V
I4C9L0 S
D5VJ32 S
C0Z5S5 T
C1N6X9 D
J7ITF6 S
A0A068SVR1 S
A0A0D7F328 A
Q0G0A4 S
F0J3F9 A
Q0BQ69 A
F2YIC4 -
D4XLN6 S
A0A420WC79 L
A0A5C5TUT2 S
A0RUZ2 N
A0A0A2ZRL7 A
J4UGB7 Q
E5Y678 T
A0A0D2KGN8 S
S5ABR8 L
A9DQM8 D
G5EB13 S
A0A2N6NEK4 S
C6DB68 S
Q81GN5 S
Q0F2M5 D
A0A0C6P439 S
B9SWW9 N
L8H5K0 -
Q9NIV0 -
C1N5A7 D
Q1JXS5 S
A0A1M6JKY3 G
F4D1J0 N
A0A257SYX3 N
V4RK08 A
G0V8D6 S
A0A7S4GMD8 D
B3QVV5 S
F2JZ83 D
A0A857DDJ7 S
A0A0S6UHP2 V
D5EP71 S
F4KY49 S
M5S9B4 D
A0A009PYN3 S
A0A3T0SZ22 S
A0A248LMH8 S
A0A6H9GEE4 V
A7HSP2 A
A0A7V8IKS6 S
T2JFS5 V
F6FRU9 N
A0A9E9L9J1 S
A0AIW5 S
A0A0E9NHV4 S
Q2N625 S
C8WSI9 T
A0A1H1BPD6 N
A0A176XNC5 S
A0A4V0XUI3 V
A7S3L2 D
M5U2P1 D
K9P5D1 N
Q0F2M7 S
A0A2R3IMJ8 S
Q2RVB5 A
A0A556RTU3 S
E0TGP9 L
B7G0Y1 D
A0A1G9P6Q0 L
D0LTW3 V
Q6BT62 S
Q2IK04 V
Q6BJI7 S
B7X047 S
A0A068NPW2 S
A0A399NT81 S
K0F9X7 N
A0A037ZMW1 L
A0A075JZ35 S
A0A369MHK2 N
A0A1B9JPL5 S
D8PD01 G
A0A2G5BI87 S
A0A2G5BGA9 S
A0A657K391 S
P69681 S
A0A4P6UIJ8 S
A0A0V8M0W6 S
A0A0H2XSU4 A
Q1Z695 D
A0A7Z0V0A4 S
K0ER80 N
A0A149UWF2 A
G0H0Z6 D
G0EFF3 S
C8WLL8 S
X5CNT2 N
A0A4Y1MSE7 A
H2CLF7 V
M4VEJ9 -
A0A4V2X6C2 S
A0A2K1RA77 N
A0A375YPN6 A
A0A7M6UUM4 -
A0A172YCA7 S
A0A918MJ52 I
A0A2S8QA29 S
A0A251XJT0 S
A0A0B4E6X7 I
A0A0K2STQ7 V
A1C5Z7 S
C9KKP2 T
A0A2Z4MD56 T
Q9VFA9 D
A0A502GPV4 S
I5C044 L
D2V6P8 -
D3RN22 D
Q97L80 G
A0A0D5YN10 S
A0A1I5GN22 N
A0A1Y5E8I7 L
B1Y8C9 S
M5SYZ1 D
Q6HM26 S
A0A379A0S9 L
A0A101DCS3 N
A0A1Y3U5V2 N
A0A202B535 A
F8E6R1 L
Q6ND36 A
A0A8H6K7L7 S
Q7NCB8 N
A0A369MRW6 N
C9RS76 V
A3U857 S
A0A127PIQ9 S
B8FGW0 G
A0A060JMP6 S
D5V7B3 I
A0A494JB70 S
A0A5M8QF12 S
A0A8G2F3G4 G
J7L3W8 N
G0JRG9 N
D3DJN2 N
A0A1Y2JH43 S
Q1L727 D
A0A7T2S0Z6 S
A0A315S845 N
A0A2S6H6B7 S
A0A1J5NTP7 G
A0A0E3QY86 S
A0A096EEV9 S
A0A380S5X4 V
B8ZYW3 T
A0A2S8GEJ5 D
A0A248TDF2 T
B2GFN1 N
U1PPI7 D
C7LW88 D
G3A431 S
A0A066ZTE4 L
L7CG99 D
S0ET45 N
A0A178TA08 S
H1XV27 D
A0A6M3ZJI1 S
U5DEY6 V
H6LFQ2 D
Q6CRN0 S
A0A4Q2EAG7 S
A0A1J5NNB8 V
E3I393 S
A0A243SC06 I
D4F313 S
W0F0I7 S
A9B874 D
A1D2Y5 S
T2J0N1 V
Q2FQT3 S
A0A075WG29 D
A0A979GQ79 S
A0A381CAY8 S
A0A2G3DSU6 D
A0A168EVK8 S
A0A094W9G3 I
A0A4R3NVT3 L
W0DYY3 L
G8JTW0 S
A0A4P6UIK6 S
I9P003 L
G2T1Y3 D
B8EMQ8 D
I6Z905 T
E0TCV4 L
A3XNG6 D
A0A087MGU4 S
A2BUP4 V
A0A562S8V2 S
A0A495DND0 S
A0A0S2FHD7 S
F3QPR6 S
A0A063Y394 A
F6G5I9 S
A0A323UDG5 A
A0A0G9HEC5 S
B8FDY8 G
Q5KPM5 S
A0A147EQL9 N
A0A854Q6X9 S
C3X1J1 S
A0A5B2V3B9 S
A0A258FS85 A
A0A7T2W1B3 N
A0A060UN76 D
G0JRQ3 D
D5UD26 N
G2ZN72 S
A0AA46Q839 S
A5UJR1 N
L1INN6 D
C1F584 V
C5LAG4 D
A0A2A2MCP3 -
B1Y6V4 S
A0A1G6ABK5 D
A0A6A1TYJ4 S
A0A2T4UWF1 S
V4AP67 D
A0A173R3W6 N
C7NND3 T
B0DFJ4 S
A0A3E2VY88 T
R1EDV9 D
J1L5M8 S
D7G265 D
Q8ERT9 T
I4D6Z9 T
A0A4R6DFU8 S
A0A060URC3 N
D2BIB2 S
F5ISF6 S
A5CRL2 S
A0A6G9XJV9 N
Q59UP8 S
A0A6N4SPH9 T
I0HGY4 N
X5DX97 T
L1J6I4 C
I1DSU5 L
B9L7N1 N
Q1Z4I4 L
Q21CP1 A
A0A165MFD1 D
V4CRP5 D
Q7S5K0 T
A0A071MMV1 A
A0A149RYW7 A
A0A7G5EC77 S
A0A1W2GZ82 I
A0A7U3XVQ4 S
A0A071M4L5 S
U5C2K4 I
A0A248LNW8 D
L8H844 D
A0A149V596 A
S9QZ09 S
B1ZSW9 S
D2BUJ8 S
A0A9Q8L398 S
M5S735 S
Q6ARH0 L
K6W5X0 N
G0JRG6 N
A0A6H9FYW4 N
A0A0S4WFM4 S
A0A101HKN9 D
Q9REX3 V
F0S3Z6 D
A8NAG3 S
C6LBD3 D
A0A149U2G9 A
V4REY8 L
A0A0H3H4I7 S
A8N2H6 S
S0APH6 N
A0A017SYR8 S
A0A1B9MZ78 S
E4T3F3 I
D7E934 T
A0A0M3AB44 S
A9WHW6 D
A0A5M4AUM9 S
A0A1X4GBG2 V
I4D1H5 S
A0A0E3QYF3 T
B0CQX4 S
A0A378YR15 S
A0A495D4X4 L
A0A076PL76 S
Q1YDY7 S
A0A3E2UCG9 T
A0A2K3DPU7 -
A0A3R9Q7C4 G
V5U2Z4 S
K9P718 V
M1V7W3 D
Q6LKC8 D
E5Y789 S
J9Z839 N
A0A1G7VM92 S
K9Z0D3 T
A0A482TED1 D
R1EGK6 D
J1ASR8 A
A0A7U4E420 S
K9YR86 V
A8PXT8 M
A0A0U1NJW3 L
B8FL88 D
A2CCK1 V
D6TFE1 V
A0A2H4U5R1 N
I2GD40 S
A0A060HFT5 N
B1Y842 D
A0A0X8NXA9 S
A0A0A2A5X1 V
A0A318FY98 S
Q7V4T8 V
A0A1A0DHK0 -
C1A872 N
A0A395VB65 D
A7MFK3 S
J4KM12 S
A1SY01 D
A0A1H4DJ49 L
A0A9R0NTP8 N
A3PAY4 V
B4CV94 S
A2C095 V
Q2HD43 S
A0A836M2B6 S
H6RWK9 N
A0A087EQK8 N
A0A1I0AQM4 -
L7CG11 S
A0A248LNK5 T
B7FTM9 D
L0K9M1 D
I4D6Z7 T
A0A2K1RA81 N
Q2WBF7 G
A0A1B9BUU6 N
A0A2S0JW39 T
A0A2S5YID7 S
B3PIH2 S
U3P8G1 S
C9R9J0 N
A8AC17 S
F0YLV7 D
A0A1D3GAE9 S
C1MHX0 T
A0A1H4KAQ7 L
A0A2T4XZC1 S
A1B3N0 S
C7LW87 G
A1SZ12 L
A0A2T2Y0D5 S
A0A1H8D0R8 -
A0A2S5V2F6 N
G3IYW2 S
F5L8M7 T
C7BJG7 S
E4U5Z1 N
A0A1B9K8L2 S
A0A2S5WMT7 S
A0A0D2UPA8 G
A0A161SKF4 S
B4D7W2 A
A0A1H3WA00 S
C1D6X6 T
A0A4D6KHD1 T
Q488X2 L
A9V5W4 -
A0A5M4ATH9 S
E4TRS4 T
A0A011U1K7 S
C7R314 N
A0A077EFU9 S
A0A0A2A0Y9 V
A0A0D8BQX6 S
A0A0L0S493 S
A0A328Q6M1 N
A0A016XCG9 S
B7FSA7 D
G0AFH4 S
A0A177W826 S
A0A2S8GF54 D
Q1YDY8 L
Q5QVH2 L
A3ZT81 D
A0AA35XZV0 S
F4H924 A
K0NJH2 A
A0A1V3SSW1 I
F2AUF4 D
A6DN47 I
W8KM07 L
A0A1X3RP39 S
A0A7S0KKL8 D
A0A318QZ80 V
K8VZC6 S
A0A1B9JZS5 S
A0A2S6GKN5 S
A0A4R2Z2K6 S
H1YCC3 L
E1QIU3 D
A0A8H6MPB9 S
A0A369N7Y3 N
T2IEJ2 V
H5UND3 N
Q1PX09 A
A0A149TSA9 A
F2NGJ8 N
A0A0E3SHQ9 T
Q5FLR6 N
S0EUS1 A
A0A369M386 N
W0DZS7 S
A8MCL4 N
V3ZVE4 D
O26757 -
A0A317FZW2 D
A0A085GI50 S
A1ZGK6 I
G0IYI2 T
A7S731 D
A0A1U9YY82 L
A0A328EMN2 S
A0A8E2UDJ3 S
A0A2S5WUP6 N
A0A8H7P8U1 S
A0A257T7G4 N
B3MX93 D
A0A1G5W0P2 N
D4H2Y7 D
A0A4P8HC89 N
Q7T070 -
F7NPQ3 S
B9SA70 N
Q9M6N7 N
I7ZHW3 S
F4XTK4 V
A4G1J2 S
G7WFX4 T
B8JBH5 H
D9QPC8 A
A0A4R7GKA0 S
R9PMC6 D
A0A0E3LMT4 V
A0A511NGC7 S
E4NS62 D
E4T3F7 N
M0D580 D
J7J5E7 G
B1XZU2 G
A0A366IE34 S
A0A6U2BIY7 D
Q9QXP0 -
A0A424WAH3 S
A0A410K1J5 D
L1IHZ8 S
I8TC71 S
A0A7U8C744 L
A8M670 N
A0A0S4VNK2 S
Q2SIR0 D
A0A5C4RNH5 S
A0A3E0X011 L
A0A0E3SP24 S
E1IF27 S
Q2YBP7 -
A0A2S5WZU0 S
A0A172YBR4 L
A0A0K2STK6 V
A0A2N6JV02 V
F0S0G1 N
A0A1C7EL50 T
Q18PF5 -
A0A1I0C958 D
A0AA35XVN2 S
L8GGA0 N
Q3AP28 G
D0MFE9 N
J9VXX9 S
A0A166IS52 V
F0J7D3 N
W7QG13 L
A4BMY5 S
A6LV49 N
Q1H483 S
A6M3G0 N
E4T0A4 S
A0A3E2UHE6 T
A0A174SD65 N
A0A855EH99 S
C3YB74 D
A0A074KZD8 I
J0S2I0 D
K9WSX4 D
E8RLT5 A
Q2FS34 A
Q3Z7F9 S
Q2S8H9 L
A0A060HN92 S
E6ME92 N
A0A172RYW3 N
L0FU80 T
C8WZE0 D
A0A2S8F4W0 D
A0A2C6C0X3 S
F3ZVV4 N
A0A7R6PER3 L
A0A495WJM6 S
A0A0B4DUR9 L
A0A251YU48 S
A5D4I5 S
A0A2X2C038 S
A0A2A2M8K7 S
D3FBG3 N
A0A2V4EA49 S
D0MFE8 D
Q3B6Q2 G
A0A1B9KID3 S
A0A9J9ES23 D
A0A3N2SFS2 S
Q0VLH1 L
A0A1U9Z147 S
Q0G2T1 C
A6GJF5 V
A0A059XXR1 N
A0A5J6WPP9 D
P41948 S
L1IUV5 S
A0A2W0GQV0 S
Q1K433 D
A0A4Y7XC43 S
D5AU98 S
E1QFA8 S
A0A075WBP9 N
Q0BWD0 L
A0A1Y0HX98 N
A0A098S5Y7 I
Q0I445 S
A0A1E5BXA4 L
A0A2C9CK98 D
G4H971 T
A0A1I0BYN1 S
A0A330GB00 S
A0A2S8FR08 G
Q84KJ6 N
A0A2S5WGI8 N
M2ALH9 D
A0A2K3DQF8 D
A0A8G2IZM3 S
F5Y3C1 S
A0A370FPU0 S
F5RGM7 S
A0A4R4K1P9 S
R8VWI7 D
A0A0A2AMW2 V
Q7Z1M1 D
A0A414NWT8 T
A0A0P6VSR8 S
A0A0L0TDW1 S
U3PCH5 R
W7QGE0 S
C5BWX7 N
A0A1B9M1A9 S
B8GGC3 S
D6SPD1 L
A0A0H3DR67 S
A0A4R7VEK0 S
G4R7P1 L
A0A1M5ZVP9 D
A0A2S5Y0D3 S
I0ICG0 I
D0L8H3 N
A0A1B9LFW3 S
Q6ND34 S
A0A6H9GWG4 V
Q5UZ98 T
A0A2S0P9T4 A
H2CDR5 D
T2KGT3 I
A0A088E6Q7 N
A0A258HS77 A
E1V4T3 L
B7GKP4 S
Q9QUT0 -
I3Z3H7 I
G7WCB6 G
A0A1Y6GLJ1 S
A0A0S2DQB6 S
Q6CRN1 S
A0A401X433 A
A7HT14 D
A0A009TDB1 S
D4XSW0 D
B0SRS8 D
A0A149QSR6 A
B1Y0E5 A
Q7UGU7 D
A0A2S0Q8P1 V
F0ZPL3 N
A0A2T0GTU1 N
I4CCD1 A
A0A9Q6P4A5 S
A0A418VIJ8 S
C1MX19 S
A0A1B9BUZ8 A
K9W6F3 N
Q1K8A3 A
L8GFX3 N
A0A1G6ABL9 S
A0A087L0B9 S
A0A073CP02 V
A0A0A1ZJU5 V
A0A258HPP1 A
A0A149QAW7 A
D2V6Q5 G
A0A1X4G8K1 N
A0A067Z3S3 A
A0A8F5ZDT8 S
A0A854QN45 S
A0A2N7LCD7 L
G7WFX2 T
A0A7S4GNJ2 V
A4G0C5 D
A6VE60 S
A0A1S1HM83 T
A0A037ZJY5 S
N1WR17 I
Q2W5V2 D
A1VIM5 N
A0A1Y5E3E3 S
A0A1T4SFK4 A
A7RNC3 D
M7XJ51 T
A0A399T909 S
A0A2N6P374 Q
H8L2Q4 S
D5EP68 I
E6SF19 N
A0A1T4SFY6 N
D3LBI0 N
E6W5C1 I
Q0VPH4 D
K9WT03 N
L0KW14 S
A0A4R8H081 D
A0A1B9N3H7 S
B0RC35 S
A0A420KGW4 S
A0A4R3NLV5 S
Q47K18 S
Q21P82 L
M1WRK6 A
A0A290XBB5 S
A0A6T9XUR2 L
A0A1J1JH03 V
I3R0S7 D
A9UR54 D
A0A1G7H8X3 S
A0A8G2F718 D
Q1H0G2 D
D0LAL7 N
C7LQR9 D
A0A1G5PWV0 S
K1K628 S
B9SXC7 N
G7WA28 S
Q1IWN6 N
H6LKH9 N
A0A1H7CU41 G
G8JUJ2 S
A0A081N2G5 L
A0A074ME37 S
Q0VQH6 S
C8XB51 N
A1VIG8 S
Q8GQS1 A
A0A1I7FBM5 -
A0A1M6ZMI3 D
A0A482PLH3 S
A0RXK8 N
D0KXQ0 D
Q8JI14 -
A0A7T4WEP4 N
A0A4R3ZNW3 N
A0A074KY88 I
A0A6M3ZKU5 D
M1SJL5 S
A0A1W9KSU5 S
E3GI40 D
A0A369NYJ2 N
A0AA92K392 S
O04161 D
A9BQZ4 S
A0A6N2Z556 D
A0A8H6NAG3 S
A0A2T9X1V4 N
Q2J376 S
A0A0F5EZP7 S
A0A7G5DK18 S
M9YAI9 S
D2ZRW2 N
G7UUY6 S
A0A8H4GS02 S
A0A2T5IHP0 -
A0A165MAC2 G
A0A7S4LPS8 V
A0A075JIN0 N
C8X554 G
B8FZP7 S
Q5KAF6 S
A0A427KNL6 S
A0A7G5DPV0 S
Q22947 -
A0A1S1HRJ0 S
A0A3N1VXY4 S
A0A2S7YPJ9 S
I0JI83 T
A0A7U3YMN6 S
Q9BLG3 D
A0A1H9RTW8 S
A0A1I4W3A0 N
A0A0B4M163 -
U2EN72 L
A0A2W5VAZ2 S
E4YA63 D
D5ELM4 D
M9RJS5 S
A0A2G3E8V2 D
Q5FSX6 A
I0HKQ8 S
A0A833H2R7 D
B8ENL9 S
B3DUX7 S
A0A1D8UWJ6 A
D5E995 T
A0A7U8C2Y6 D
L0KGR8 A
B0VMH1 S
P40260 A
L0JT30 T
C1GR74 S
A0A423Y4I6 S
A0A4P7UHQ5 S
A0A8E2R1Y5 S
I5BYV5 I
A0A6B8N021 S
A0A7G5DPV1 L
A0A2G5RQK9 S
A0A5M4B0G1 G
A0A6S5K4J1 S
C1D4X0 S
A1SVA8 D
H1YF74 M
A0A8B4RWH8 S
A0A0A0D6K5 S
A0A0A2BBY0 V
A0A089ZBW5 N
A0A068TC78 S
Q46G49 S
A1CQ21 S
A0A1G6ABX1 L
E1SLM7 L
K5CFE5 S
Q2YLQ6 S
Q0G2V0 A
A4ABK3 L
A0A9Q5QVI9 N
A0A4Q7Y9I7 N
A9HMD6 A
K9YN27 V
Q9UBD6 -
D9SI59 S
Q8I0L6 -
A0A142VAD6 S
G3IYW0 S
A0A062IU58 S
R1D1H4 D
A0A366XFS8 S
A0A7S4GNF3 V
F0J6E8 S
A0A7U4DN04 G
V4RHR4 C
F7ZJM0 D
A0A2S5XAB8 S
U5C4L4 T
Q21J04 S
A0A142NNN1 N
H1Y7T6 S
F5R974 D
B0DU91 S
A2BP62 V
A7HSN9 D
A0A377I7W9 S
D2RU19 T
G7WJN0 D
E2SD33 N
A0A0D7F2Y9 S
A0AA92EGF5 S
A0A9E9LXV9 S
A4BEP1 D
A0A0E3WZH5 V
F7ZEU9 L
A5E3X2 S
A0A0A3XTJ3 S
A0A830ZZN8 S
A0A1S8D478 A
J7IVQ1 D
A0A2U1SS17 S
S3K1S2 S
C6XKC2 L
A0A2S7YIM5 Q
K2IMJ7 L
Q5P1S8 D
A0A7T5BFQ2 D
A0A556SRH6 S
A8P923 S
A0A7G5DKA9 D
L8JUH3 T
A0A0D2LEF5 S
A0A258FTB0 S
A0A5P9P1L2 T
M8E0R3 S
A0A6J5IRX5 A
W5WIX6 N
Q82X47 -
I4DBY0 S
A0A6F8TLE9 S
A0A1G7UZX2 D
A0A6P4JM51 D
G0J614 I
U2WTW8 S
A0A642KQG8 T
Q1AUG3 N
A0A6G9Y3Q0 N
B8J5X4 V
M7NFH3 S
A0A0E3R6S1 G
Q2IHY5 H
A7I8Z2 D
L1IYP4 S
B4HDZ9 D
A0A366WYI9 L
E4TJ50 -
A0A7S0ILH2 T
A4BAE1 L
B3QRJ4 G
A0A5C5BWI6 N
Q7NQY2 A
A0A091AXI3 S
Q1QSQ2 L
R4FZE3 S
A0A2N0MZ27 S
A9BTK1 N
A0A242NIL1 S
G0LFE3 D
A0A1B9NQ91 S
A0A5M5PZE2 T
A0A0D2NYP3 S
D9QPE5 A
I5B3H0 D
L1IYW7 S
C6WEW7 N
B7FW68 D
F4GED5 S
A0A4R8GSH7 D
A0A1W2H3F0 T
A0A3E2T713 D
A0A0H3KTD3 S
A0A1Y4LM49 D
G2PRJ6 D
A0A0X8X7Y7 L
K8EJ02 N
A0A1L3F1X5 S
G8TK77 S
A0A855F5Y8 S
A0A975BTN0 N
A0A562RGZ4 A
G5EB09 S
A0A833LX85 V
U1H1F7 A
K8W1E2 S
E3HJW8 S
Q7SEH0 S
Q47X17 S
B0DXT9 S
A0A3G9G2C9 A
Q95P70 -
A0A837C6X5 S
Q89WR5 S
A6DUG4 I
D7UQE2 -
A0A2I1M481 H
A0A0T7GZ59 S
O66395 S
J3EXK0 D
A0A1B9MYL7 S
K9U8C7 V
E2SD44 S
H6LKH6 N
Q605Y6 S
A0A9Q9D9I3 S
A0A6N2TIA4 D
A0A1E3PQH0 N
A4CMI3 I
Q1K0H9 L
A0A0S6UEK9 G
A0A0H3LUA3 S
B9LU00 T
A9BIZ7 D
A0A7H8UK07 S
E3H8C9 D
M2A398 S
Q1QS12 A
G0VI62 S
A0A1Z3MS36 S
A0A0B5FNH4 L
D9SI36 D
A0A410JZR4 N
F7ZJZ1 A
F0ZCX7 -
W0DZX1 D
A0A4R3ZZ35 N
A0A317G0I6 D
Q0ARJ4 S
A7I8Z4 S
T2KJ59 D
I3C0V3 D
E3H8A6 D
B2IJT1 S
A0A2G6JLT9 D
A3ZZL7 S
A0A2T0XPP2 D
Q31CR9 V
A0A1R1IDV3 S
K2JVF8 L
V5BYZ7 S
D8J4C6 T
D4H5F9 D
K9ZG59 N
A0AA86YS65 A
Q608B6 D
A0A562BXM4 S
A0A401WXG0 -
A0A857DMN9 S
A0A1X6N3Q5 S
A0A173R3X4 D
Q63EK5 S
K9ZLY2 D
A0A533I6R2 S
I0WJ97 I
K0N2R5 N
M0J579 D
B8GGC1 S
A0A6H9GFU4 N
C6CBB1 S
A0A510HHK8 N
A0A1B9MBX6 S
A0A9Y2AG30 N
E8RSE4 A
F2B2B8 S
Q7UYZ3 S
I1YJH7 L
A0A853MG28 V
A0A0L0STS6 S
A0A251XU71 S
Q60BI2 S
A0A829X098 A
F3KUN4 S
Q60C43 S
A0A0T7FAP8 S
A0A3E2TW06 T
W0E077 D
A0KPE9 S
R7PZ71 N
A0A0A1ZMZ9 V
A0AA40J491 S
D3S2L0 N
A0A373FQ71 S
A0A0A2C6L1 V
Q7W7D3 S
A0A165K0X5 T
A0A2S5X482 S
R9GM11 S
Q0G0A3 L
D4GLQ6 S
E7RJZ0 T
F8IJE0 T
A0A1V2XMU9 A
Q7TNN9 -
A0A1G5RZU9 T
A0A2N6K4Y5 N
B0SLB7 S
A0A251YFS0 S
B9WDK0 S
Q7N0M6 S
A0A0M2LU39 S
F4B548 N
D6Z5V9 I
A0A4R2M206 S
A0A1E2SKM1 R
A0A127JTU2 S
A0A212AV03 S
G4QHD2 D
A0A021VMC6 N
A0A2J7TJ33 S
G7WDB5 D
Q6BK68 T
Q1K3N8 D
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 S
A0A377PLP5 S
W7QGM4 D
A0A015YIP3 D
A0A060UWC8 N
A0A1I4ZIZ6 A
A0A264VQM8 S
A9AUR8 S
A0A1W5PRD1 -
A0A0E3BR91 S
A0A1B0ZRL8 L
B9ACS5 N
Q92BJ7 S
F2JTN3 L
A1AVV2 S
D2Q0J8 N
A0A3S9N9F3 A
A8ZQD5 D
C3X831 S
A0A1M6BPM0 G
A0A8F5VN39 S
A0A1E5C7W4 D
A0A2S5WV24 S
A0A833GZR2 D
C7M2A9 N
A6W7U2 N
W0JIB3 T
Q07UM3 S
A0A066ZRQ5 D
S0G181 I
D3PAH1 N
Q4WHC6 S
A0AA94HTL8 S
D5ASL9 S
A0A4U1JNL6 S
M0MDP9 T
A0A653N397 S
A0A2S8GSU9 S
A0A097R891 S
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 S
A0A1B9JHS5 S
D3PE53 S
A0A9J9BAE8 L
Q2RM12 G
A0A3N0AQL8 N
C5KTM6 D
M1P5F0 L
I1YG38 D
A0A660CH85 N
A0A2N7L7C8 D
Q5KZZ9 S
M1NZT5 L
A0A225CMT8 S
A0A068NV61 M
H2CJI0 D
B0DU93 S
Q221S8 S
F4Y3C5 V
Q94CJ2 -
M0D3Q9 T
A0A3P2A7W8 S
C0GKN4 D
Q7T3R4 -
A0A562USB9 L
A2SS52 S
A0A211ZGL5 S
A0A4V3ALP8 S
A0A147GP06 S
H2IZ00 S
Q45HK8 S
A0A6C8LST1 S
A0A257T8W6 N
Q5P470 S
I5AZQ4 N
Q07UM1 A
E5B358 S
A0A1Y4L5P0 D
Q3AFY9 N
B0BZN3 V
A0A1Q2C7H7 N
A0A4R5U5V1 S
H6LKX6 D
A0A1Y0UZX2 A
F6BEI0 D
M9RKT6 L
A7SGD4 D
A0A257TE48 D
R1FI09 D
E4N1T5 M
U1PIR6 D
F2JYR9 A
Q84KJ7 N
A0A2S8FTB5 D
D2R647 D
G9Y5B0 S
A0A144NLT9 S
A0A5J6WQU1 L
D2R355 G
F3ZYD6 D
B0SL05 V
A0A5A7MAJ9 S
A0A977NL43 N
A0A433ZQ80 S
A0A1Y0V4A5 -
A0A1M7UEG2 N
G8R7U9 S
K1LDP0 I
B7G0Y4 D
A0A2W4ZXC0 S
B3PF77 M
Q2KZK9 S
Q18ES8 D
D3F545 N
B4S394 G
Q1Q357 D
Q9H310 -
D3PKL4 N
M5SY07 S
Q8RUT6 D
A7NKH2 D
Q1Q879 L
A0A1B9M5B8 S
A6LRS5 S
J2ZGN6 T
V5E0F3 S
A0A149RQX0 A
A0A165BP25 S
C0QSY0 N
B0XVV6 S
E0SD83 S
A8HSA2 D
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 S
Q0AT01 L
A4FMG0 N
C3YB73 D
A0A9P3CXY2 S
A0A0L8BVU4 S
A0A401WUW1 A
I4C9L2 S
Q8RUE9 -
F0JGZ1 A
A0A2I0UUY1 T
A0A542XGT4 N
G0JRH4 A
A2SPS8 S
A0A5M4AWD2 D
Q6QH01 D
D3F0Z1 N
A6XBM2 -
D6E7B3 N
Q13E03 S
A0A060URB8 A
A0A2T1N7R1 I
D6TCH6 -
B0CXH8 S
A3TVQ9 L
Q4WT12 S
C7QGX3 N
F0Y9X3 D
A0A7S0D560 S
A0A160KTE9 S
A0A2H1HV86 N
A0A251Y3N4 S
A0A419AVL2 S
A0A4Q2QWS1 S
C7Q1E4 N
A0A5C5TYS5 S
F2NNQ0 N
A0A2R4TRE0 S
K9YJQ3 V
D9QS43 D
A7SQ16 D
A1DG05 S
U1SIR9 H
C4Y298 S
A0A9W3LFI9 S
D3RMV7 S
F3QNA7 S
E4RTK5 S
C8XBX8 N
C0QTA4 N
E6VIW4 S
A0A2S6H643 S
Q46HB1 V
A0A2S5CTX8 T
A0A1T4SF40 A
K0K7J4 N
A0A1J5JH24 G
Q6LMI6 L
A0A9W5JBA9 S
A0A291PMC6 A
A0A4Y4DZN4 N
A0A2R4MBA2 S
R9PI53 L
A0A6H9GLV4 V
A0A7S4GND2 V
A0A6H9FPY5 V
A0A1G7DX68 S
A0A075WEB4 S
A0A140NHJ5 A
A0A1C6Z081 S
Q5FA36 S
Q0ACK1 L
A0A975GIX9 N
A0A323UE08 S
U7VB41 T
A0A063Y780 L
C5CIT6 -
A0A0A2VPU3 Q
F0RHS0 D
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 S
A0A0A2B651 V
A0A4R3A5P7 S
A0A2A7U6W1 S
Q2GX26 A
F5XN43 N
A0A0K2STH0 V
A0A1H1U2Q6 N
A7SED8 -
A0LV78 A
K5DBA0 D
B8IZX4 S
A8LKQ0 L
A0A5C6LWQ1 S

In [90]:
seqt = []

for i in t:
    print(i.id, i.seq)
    seqt.append(i.seq)

A0A858ZNJ3 A
A0A1H9M798 A
B0DY50 M
P69680 G
A0A3G9G4Q4 A
A0A149UP06 A
F2G6G4 S
A0A2M9D7S8 A
A0A034WGQ2 T
I0KDC6 A
F8D7H6 T
K9W4V5 T
Q466Y3 T
D2SE15 A
A0A377PBY1 G
B1JZ69 A
A0A2W5HTC3 A
A8G2S3 T
D5T4N9 A
Q2RWY7 L
A0A0E3R4G0 -
I4C9L0 A
D5VJ32 A
C0Z5S5 A
C1N6X9 T
J7ITF6 A
A0A068SVR1 A
A0A0D7F328 A
Q0G0A4 A
F0J3F9 V
Q0BQ69 A
F2YIC4 L
D4XLN6 A
A0A420WC79 S
A0A5C5TUT2 A
A0RUZ2 A
A0A0A2ZRL7 A
J4UGB7 A
E5Y678 A
A0A0D2KGN8 M
S5ABR8 S
A9DQM8 T
G5EB13 A
A0A2N6NEK4 A
C6DB68 A
Q81GN5 A
Q0F2M5 A
A0A0C6P439 A
B9SWW9 I
L8H5K0 L
Q9NIV0 M
C1N5A7 T
Q1JXS5 A
A0A1M6JKY3 A
F4D1J0 A
A0A257SYX3 V
V4RK08 S
G0V8D6 S
A0A7S4GMD8 T
B3QVV5 A
F2JZ83 A
A0A857DDJ7 A
A0A0S6UHP2 T
D5EP71 G
F4KY49 A
M5S9B4 T
A0A009PYN3 A
A0A3T0SZ22 A
A0A248LMH8 A
A0A6H9GEE4 T
A7HSP2 A
A0A7V8IKS6 A
T2JFS5 T
F6FRU9 A
A0A9E9L9J1 V
A0AIW5 A
A0A0E9NHV4 A
Q2N625 A
C8WSI9 A
A0A1H1BPD6 A
A0A176XNC5 A
A0A4V0XUI3 T
A7S3L2 T
M5U2P1 T
K9P5D1 A
Q0F2M7 V
A0A2R3IMJ8 A
Q2RVB5 A
A0A556RTU3 C
E0TGP9 S
B7G0Y1 T
A0A1G9P6Q0 S
D0LTW3 T
Q6BT62 I
Q2IK04 T
Q6BJI7 A
B7X047 A
A0A068NPW2 A
A0A399NT81 A
K0F9X7 A
A0A037ZMW1 S
A0A075JZ35 A
A0A369MHK2 A
A0A1B9JPL5 C
D8PD01 A
A0A2G5BI87 G
A0A2G5BGA9 A
A0A657K391 C
P69681 G
A0A4P6UIJ8 A
A0A0V8M0W6 A
A0A0H2XSU4 A
Q1Z695 A
A0A7Z0V0A4 A
K0ER80 A
A0A149UWF2 A
G0H0Z6 T
G0EFF3 A
C8WLL8 A
X5CNT2 I
A0A4Y1MSE7 A
H2CLF7 T
M4VEJ9 A
A0A4V2X6C2 A
A0A2K1RA77 I
A0A375YPN6 S
A0A7M6UUM4 L
A0A172YCA7 A
A0A918MJ52 T
A0A2S8QA29 A
A0A251XJT0 A
A0A0B4E6X7 S
A0A0K2STQ7 T
A1C5Z7 A
C9KKP2 A
A0A2Z4MD56 A
Q9VFA9 T
A0A502GPV4 A
I5C044 S
D2V6P8 L
D3RN22 A
Q97L80 G
A0A0D5YN10 A
A0A1I5GN22 A
A0A1Y5E8I7 S
B1Y8C9 C
M5SYZ1 T
Q6HM26 A
A0A379A0S9 S
A0A101DCS3 A
A0A1Y3U5V2 G
A0A202B535 A
F8E6R1 S
Q6ND36 A
A0A8H6K7L7 A
Q7NCB8 A
A0A369MRW6 A
C9RS76 T
A3U857 A
A0A127PIQ9 A
B8FGW0 A
A0A060JMP6 A
D5V7B3 N
A0A494JB70 A
A0A5M8QF12 A
A0A8G2F3G4 A
J7L3W8 A
G0JRG9 I
D3DJN2 A
A0A1Y2JH43 A
Q1L727 T
A0A7T2S0Z6 A
A0A315S845 A
A0A2S6H6B7 A
A0A1J5NTP7 A
A0A0E3QY86 A
A0A096EEV9 A
A0A380S5X4 T
B8ZYW3 T
A0A2S8GEJ5 T
A0A248TDF2 C
B2GFN1 A
U1PPI7 T
C7LW88 T
G3A431 A
A0A066ZTE4 S
L7CG99 T
S0ET45 A
A0A178TA08 A
H1XV27 T
A0A6M3ZJI1 A
U5DEY6 T
H6LFQ2 T
Q6CRN0 I
A0A4Q2EAG7 G
A0A1J5NNB8 T
E3I393 A
A0A243SC06 A
D4F313 A
W0F0I7 A
A9B874 T
A1D2Y5 A
T2J0N1 T
Q2FQT3 A
A0A075WG29 T
A0A979GQ79 A
A0A381CAY8 G
A0A2G3DSU6 T
A0A168EVK8 G
A0A094W9G3 A
A0A4R3NVT3 S
W0DYY3 S
G8JTW0 A
A0A4P6UIK6 A
I9P003 S
G2T1Y3 T
B8EMQ8 A
I6Z905 T
E0TCV4 S
A3XNG6 T
A0A087MGU4 A
A2BUP4 T
A0A562S8V2 A
A0A495DND0 A
A0A0S2FHD7 A
F3QPR6 A
A0A063Y394 S
F6G5I9 A
A0A323UDG5 A
A0A0G9HEC5 A
B8FDY8 A
Q5KPM5 A
A0A147EQL9 A
A0A854Q6X9 V
C3X1J1 V
A0A5B2V3B9 A
A0A258FS85 A
A0A7T2W1B3 A
A0A060UN76 A
G0JRQ3 A
D5UD26 A
G2ZN72 A
A0AA46Q839 A
A5UJR1 A
L1INN6 T
C1F584 T
C5LAG4 T
A0A2A2MCP3 A
B1Y6V4 T
A0A1G6ABK5 A
A0A6A1TYJ4 A
A0A2T4UWF1 A
V4AP67 T
A0A173R3W6 A
C7NND3 T
B0DFJ4 A
A0A3E2VY88 T
R1EDV9 T
J1L5M8 A
D7G265 T
Q8ERT9 T
I4D6Z9 T
A0A4R6DFU8 A
A0A060URC3 I
D2BIB2 A
F5ISF6 A
A5CRL2 A
A0A6G9XJV9 A
Q59UP8 I
A0A6N4SPH9 T
I0HGY4 A
X5DX97 T
L1J6I4 A
I1DSU5 S
B9L7N1 A
Q1Z4I4 S
Q21CP1 A
A0A165MFD1 T
V4CRP5 T
Q7S5K0 M
A0A071MMV1 A
A0A149RYW7 A
A0A7G5EC77 A
A0A1W2GZ82 T
A0A7U3XVQ4 A
A0A071M4L5 A
U5C2K4 T
A0A248LNW8 A
L8H844 S
A0A149V596 A
S9QZ09 A
B1ZSW9 A
D2BUJ8 G
A0A9Q8L398 A
M5S735 A
Q6ARH0 S
K6W5X0 A
G0JRG6 I
A0A6H9FYW4 A
A0A0S4WFM4 A
A0A101HKN9 T
Q9REX3 T
F0S3Z6 A
A8NAG3 T
C6LBD3 T
A0A149U2G9 A
V4REY8 S
A0A0H3H4I7 G
A8N2H6 A
S0APH6 I
A0A017SYR8 A
A0A1B9MZ78 C
E4T3F3 -
D7E934 T
A0A0M3AB44 A
A9WHW6 T
A0A5M4AUM9 A
A0A1X4GBG2 T
I4D1H5 A
A0A0E3QYF3 T
B0CQX4 S
A0A378YR15 A
A0A495D4X4 S
A0A076PL76 A
Q1YDY7 A
A0A3E2UCG9 T
A0A2K3DPU7 -
A0A3R9Q7C4 A
V5U2Z4 G
K9P718 T
M1V7W3 S
Q6LKC8 A
E5Y789 A
J9Z839 I
A0A1G7VM92 G
K9Z0D3 S
A0A482TED1 T
R1EGK6 T
J1ASR8 A
A0A7U4E420 A
K9YR86 T
A8PXT8 V
A0A0U1NJW3 S
B8FL88 T
A2CCK1 T
D6TFE1 T
A0A2H4U5R1 A
I2GD40 A
A0A060HFT5 A
B1Y842 A
A0A0X8NXA9 A
A0A0A2A5X1 T
A0A318FY98 G
Q7V4T8 T
A0A1A0DHK0 V
C1A872 A
A0A395VB65 T
A7MFK3 G
J4KM12 A
A1SY01 T
A0A1H4DJ49 S
A0A9R0NTP8 A
A3PAY4 T
B4CV94 A
A2C095 T
Q2HD43 A
A0A836M2B6 A
H6RWK9 A
A0A087EQK8 A
A0A1I0AQM4 L
L7CG11 A
A0A248LNK5 A
B7FTM9 T
L0K9M1 T
I4D6Z7 A
A0A2K1RA81 I
Q2WBF7 A
A0A1B9BUU6 I
A0A2S0JW39 T
A0A2S5YID7 A
B3PIH2 A
U3P8G1 A
C9R9J0 A
A8AC17 A
F0YLV7 T
A0A1D3GAE9 A
C1MHX0 A
A0A1H4KAQ7 S
A0A2T4XZC1 G
A1B3N0 A
C7LW87 A
A1SZ12 S
A0A2T2Y0D5 G
A0A1H8D0R8 L
A0A2S5V2F6 A
G3IYW2 A
F5L8M7 T
C7BJG7 A
E4U5Z1 A
A0A1B9K8L2 C
A0A2S5WMT7 A
A0A0D2UPA8 A
A0A161SKF4 A
B4D7W2 G
A0A1H3WA00 G
C1D6X6 A
A0A4D6KHD1 T
Q488X2 S
A9V5W4 L
A0A5M4ATH9 A
E4TRS4 T
A0A011U1K7 A
C7R314 A
A0A077EFU9 A
A0A0A2A0Y9 T
A0A0D8BQX6 A
A0A0L0S493 A
A0A328Q6M1 A
A0A016XCG9 A
B7FSA7 T
G0AFH4 A
A0A177W826 A
A0A2S8GF54 T
Q1YDY8 S
Q5QVH2 S
A3ZT81 T
A0AA35XZV0 A
F4H924 A
K0NJH2 T
A0A1V3SSW1 A
F2AUF4 T
A6DN47 S
W8KM07 S
A0A1X3RP39 G
A0A7S0KKL8 T
A0A318QZ80 T
K8VZC6 A
A0A1B9JZS5 C
A0A2S6GKN5 A
A0A4R2Z2K6 A
H1YCC3 A
E1QIU3 T
A0A8H6MPB9 A
A0A369N7Y3 A
T2IEJ2 T
H5UND3 A
Q1PX09 T
A0A149TSA9 A
F2NGJ8 A
A0A0E3SHQ9 T
Q5FLR6 A
S0EUS1 Y
A0A369M386 A
W0DZS7 A
A8MCL4 A
V3ZVE4 T
O26757 A
A0A317FZW2 T
A0A085GI50 G
A1ZGK6 T
G0IYI2 T
A7S731 T
A0A1U9YY82 S
A0A328EMN2 A
A0A8E2UDJ3 A
A0A2S5WUP6 A
A0A8H7P8U1 M
A0A257T7G4 I
B3MX93 T
A0A1G5W0P2 A
D4H2Y7 T
A0A4P8HC89 A
Q7T070 L
F7NPQ3 A
B9SA70 I
Q9M6N7 I
I7ZHW3 A
F4XTK4 T
A4G1J2 A
G7WFX4 A
B8JBH5 A
D9QPC8 A
A0A4R7GKA0 A
R9PMC6 A
A0A0E3LMT4 -
A0A511NGC7 A
E4NS62 T
E4T3F7 A
M0D580 T
J7J5E7 A
B1XZU2 T
A0A366IE34 A
A0A6U2BIY7 T
Q9QXP0 C
A0A424WAH3 A
A0A410K1J5 T
L1IHZ8 A
I8TC71 A
A0A7U8C744 S
A8M670 A
A0A0S4VNK2 A
Q2SIR0 A
A0A5C4RNH5 A
A0A3E0X011 S
A0A0E3SP24 A
E1IF27 A
Q2YBP7 L
A0A2S5WZU0 A
A0A172YBR4 S
A0A0K2STK6 T
A0A2N6JV02 T
F0S0G1 A
A0A1C7EL50 T
Q18PF5 L
A0A1I0C958 T
A0AA35XVN2 A
L8GGA0 A
Q3AP28 A
D0MFE9 A
J9VXX9 V
A0A166IS52 T
F0J7D3 I
W7QG13 S
A4BMY5 A
A6LV49 A
Q1H483 A
A6M3G0 A
E4T0A4 A
A0A3E2UHE6 T
A0A174SD65 A
A0A855EH99 G
C3YB74 T
A0A074KZD8 T
J0S2I0 T
K9WSX4 T
E8RLT5 A
Q2FS34 A
Q3Z7F9 A
Q2S8H9 S
A0A060HN92 L
E6ME92 A
A0A172RYW3 A
L0FU80 T
C8WZE0 T
A0A2S8F4W0 T
A0A2C6C0X3 G
F3ZVV4 A
A0A7R6PER3 S
A0A495WJM6 S
A0A0B4DUR9 S
A0A251YU48 A
A5D4I5 A
A0A2X2C038 A
A0A2A2M8K7 G
D3FBG3 A
A0A2V4EA49 C
D0MFE8 T
Q3B6Q2 A
A0A1B9KID3 C
A0A9J9ES23 A
A0A3N2SFS2 G
Q0VLH1 S
A0A1U9Z147 A
Q0G2T1 S
A6GJF5 T
A0A059XXR1 I
A0A5J6WPP9 A
P41948 A
L1IUV5 A
A0A2W0GQV0 G
Q1K433 T
A0A4Y7XC43 A
D5AU98 A
E1QFA8 A
A0A075WBP9 A
Q0BWD0 S
A0A1Y0HX98 A
A0A098S5Y7 T
Q0I445 A
A0A1E5BXA4 S
A0A2C9CK98 T
G4H971 A
A0A1I0BYN1 A
A0A330GB00 G
A0A2S8FR08 A
Q84KJ6 I
A0A2S5WGI8 A
M2ALH9 T
A0A2K3DQF8 T
A0A8G2IZM3 G
F5Y3C1 S
A0A370FPU0 C
F5RGM7 A
A0A4R4K1P9 A
R8VWI7 T
A0A0A2AMW2 T
Q7Z1M1 T
A0A414NWT8 A
A0A0P6VSR8 A
A0A0L0TDW1 A
U3PCH5 S
W7QGE0 A
C5BWX7 A
A0A1B9M1A9 C
B8GGC3 A
D6SPD1 S
A0A0H3DR67 A
A0A4R7VEK0 A
G4R7P1 S
A0A1M5ZVP9 T
A0A2S5Y0D3 A
I0ICG0 T
D0L8H3 A
A0A1B9LFW3 C
Q6ND34 A
A0A6H9GWG4 T
Q5UZ98 T
A0A2S0P9T4 A
H2CDR5 T
T2KGT3 T
A0A088E6Q7 G
A0A258HS77 A
E1V4T3 S
B7GKP4 A
Q9QUT0 L
I3Z3H7 T
G7WCB6 A
A0A1Y6GLJ1 G
A0A0S2DQB6 A
Q6CRN1 I
A0A401X433 A
A7HT14 T
A0A009TDB1 A
D4XSW0 A
B0SRS8 T
A0A149QSR6 A
B1Y0E5 A
Q7UGU7 T
A0A2S0Q8P1 T
F0ZPL3 T
A0A2T0GTU1 A
I4CCD1 A
A0A9Q6P4A5 A
A0A418VIJ8 A
C1MX19 A
A0A1B9BUZ8 A
K9W6F3 A
Q1K8A3 A
L8GFX3 A
A0A1G6ABL9 A
A0A087L0B9 A
A0A073CP02 T
A0A0A1ZJU5 T
A0A258HPP1 A
A0A149QAW7 A
D2V6Q5 T
A0A1X4G8K1 A
A0A067Z3S3 A
A0A8F5ZDT8 A
A0A854QN45 A
A0A2N7LCD7 S
G7WFX2 T
A0A7S4GNJ2 T
A4G0C5 T
A6VE60 A
A0A1S1HM83 A
A0A037ZJY5 A
N1WR17 T
Q2W5V2 A
A1VIM5 S
A0A1Y5E3E3 V
A0A1T4SFK4 A
A7RNC3 T
M7XJ51 T
A0A399T909 A
A0A2N6P374 A
H8L2Q4 A
D5EP68 T
E6SF19 A
A0A1T4SFY6 A
D3LBI0 A
E6W5C1 S
Q0VPH4 T
K9WT03 A
L0KW14 A
A0A4R8H081 T
A0A1B9N3H7 C
B0RC35 A
A0A420KGW4 A
A0A4R3NLV5 A
Q47K18 G
Q21P82 S
M1WRK6 A
A0A290XBB5 A
A0A6T9XUR2 S
A0A1J1JH03 T
I3R0S7 T
A9UR54 T
A0A1G7H8X3 A
A0A8G2F718 T
Q1H0G2 T
D0LAL7 A
C7LQR9 T
A0A1G5PWV0 A
K1K628 G
B9SXC7 I
G7WA28 A
Q1IWN6 A
H6LKH9 A
A0A1H7CU41 A
G8JUJ2 I
A0A081N2G5 S
A0A074ME37 A
Q0VQH6 A
C8XB51 A
A1VIG8 T
Q8GQS1 A
A0A1I7FBM5 L
A0A1M6ZMI3 T
A0A482PLH3 G
A0RXK8 A
D0KXQ0 A
Q8JI14 L
A0A7T4WEP4 I
A0A4R3ZNW3 A
A0A074KY88 T
A0A6M3ZKU5 A
M1SJL5 A
A0A1W9KSU5 T
E3GI40 A
A0A369NYJ2 A
A0AA92K392 A
O04161 G
A9BQZ4 A
A0A6N2Z556 T
A0A8H6NAG3 A
A0A2T9X1V4 V
Q2J376 A
A0A0F5EZP7 A
A0A7G5DK18 A
M9YAI9 A
D2ZRW2 A
G7UUY6 A
A0A8H4GS02 A
A0A2T5IHP0 L
A0A165MAC2 A
A0A7S4LPS8 T
A0A075JIN0 A
C8X554 A
B8FZP7 A
Q5KAF6 V
A0A427KNL6 G
A0A7G5DPV0 A
Q22947 L
A0A1S1HRJ0 A
A0A3N1VXY4 G
A0A2S7YPJ9 A
I0JI83 T
A0A7U3YMN6 A
Q9BLG3 T
A0A1H9RTW8 A
A0A1I4W3A0 A
A0A0B4M163 L
U2EN72 S
A0A2W5VAZ2 A
E4YA63 T
D5ELM4 T
M9RJS5 A
A0A2G3E8V2 T
Q5FSX6 A
I0HKQ8 G
A0A833H2R7 T
B8ENL9 A
B3DUX7 A
A0A1D8UWJ6 A
D5E995 T
A0A7U8C2Y6 A
L0KGR8 A
B0VMH1 A
P40260 S
L0JT30 T
C1GR74 A
A0A423Y4I6 G
A0A4P7UHQ5 A
A0A8E2R1Y5 A
I5BYV5 T
A0A6B8N021 G
A0A7G5DPV1 S
A0A2G5RQK9 A
A0A5M4B0G1 A
A0A6S5K4J1 G
C1D4X0 A
A1SVA8 A
H1YF74 T
A0A8B4RWH8 A
A0A0A0D6K5 A
A0A0A2BBY0 T
A0A089ZBW5 A
A0A068TC78 A
Q46G49 A
A1CQ21 A
A0A1G6ABX1 S
E1SLM7 S
K5CFE5 A
Q2YLQ6 A
Q0G2V0 S
A4ABK3 S
A0A9Q5QVI9 A
A0A4Q7Y9I7 A
A9HMD6 A
K9YN27 T
Q9UBD6 C
D9SI59 A
Q8I0L6 M
A0A142VAD6 A
G3IYW0 A
A0A062IU58 A
R1D1H4 T
A0A366XFS8 A
A0A7S4GNF3 T
F0J6E8 A
A0A7U4DN04 A
V4RHR4 S
F7ZJM0 T
A0A2S5XAB8 A
U5C4L4 T
Q21J04 A
A0A142NNN1 A
H1Y7T6 A
F5R974 A
B0DU91 G
A2BP62 T
A7HSN9 A
A0A377I7W9 A
D2RU19 T
G7WJN0 T
E2SD33 A
A0A0D7F2Y9 A
A0AA92EGF5 A
A0A9E9LXV9 A
A4BEP1 A
A0A0E3WZH5 -
F7ZEU9 S
A5E3X2 I
A0A0A3XTJ3 A
A0A830ZZN8 G
A0A1S8D478 A
J7IVQ1 T
A0A2U1SS17 A
S3K1S2 G
C6XKC2 S
A0A2S7YIM5 A
K2IMJ7 S
Q5P1S8 A
A0A7T5BFQ2 A
A0A556SRH6 C
A8P923 A
A0A7G5DKA9 T
L8JUH3 T
A0A0D2LEF5 G
A0A258FTB0 A
A0A5P9P1L2 T
M8E0R3 A
A0A6J5IRX5 A
W5WIX6 A
Q82X47 L
I4DBY0 A
A0A6F8TLE9 A
A0A1G7UZX2 A
A0A6P4JM51 T
G0J614 T
U2WTW8 A
A0A642KQG8 T
Q1AUG3 A
A0A6G9Y3Q0 A
B8J5X4 T
M7NFH3 T
A0A0E3R6S1 A
Q2IHY5 A
A7I8Z2 A
L1IYP4 A
B4HDZ9 T
A0A366WYI9 S
E4TJ50 A
A0A7S0ILH2 A
A4BAE1 S
B3QRJ4 A
A0A5C5BWI6 A
Q7NQY2 A
A0A091AXI3 A
Q1QSQ2 S
R4FZE3 A
A0A2N0MZ27 A
A9BTK1 A
A0A242NIL1 C
G0LFE3 T
A0A1B9NQ91 C
A0A5M5PZE2 T
A0A0D2NYP3 A
D9QPE5 A
I5B3H0 T
L1IYW7 A
C6WEW7 A
B7FW68 T
F4GED5 A
A0A4R8GSH7 A
A0A1W2H3F0 T
A0A3E2T713 T
A0A0H3KTD3 G
A0A1Y4LM49 T
G2PRJ6 T
A0A0X8X7Y7 S
K8EJ02 A
A0A1L3F1X5 A
G8TK77 G
A0A855F5Y8 G
A0A975BTN0 A
A0A562RGZ4 T
G5EB09 A
A0A833LX85 T
U1H1F7 A
K8W1E2 A
E3HJW8 A
Q7SEH0 A
Q47X17 V
B0DXT9 G
A0A3G9G2C9 A
Q95P70 L
A0A837C6X5 A
Q89WR5 A
A6DUG4 S
D7UQE2 L
A0A2I1M481 A
A0A0T7GZ59 A
O66395 A
J3EXK0 T
A0A1B9MYL7 C
K9U8C7 T
E2SD44 A
H6LKH6 A
Q605Y6 A
A0A9Q9D9I3 A
A0A6N2TIA4 T
A0A1E3PQH0 T
A4CMI3 T
Q1K0H9 S
A0A0S6UEK9 A
A0A0H3LUA3 A
B9LU00 T
A9BIZ7 T
A0A7H8UK07 G
E3H8C9 T
M2A398 A
Q1QS12 A
G0VI62 I
A0A1Z3MS36 G
A0A0B5FNH4 S
D9SI36 A
A0A410JZR4 A
F7ZJZ1 S
F0ZCX7 M
W0DZX1 A
A0A4R3ZZ35 A
A0A317G0I6 T
Q0ARJ4 A
A7I8Z4 T
T2KJ59 T
I3C0V3 T
E3H8A6 T
B2IJT1 A
A0A2G6JLT9 A
A3ZZL7 A
A0A2T0XPP2 T
Q31CR9 T
A0A1R1IDV3 A
K2JVF8 S
V5BYZ7 A
D8J4C6 T
D4H5F9 T
K9ZG59 A
A0AA86YS65 A
Q608B6 A
A0A562BXM4 A
A0A401WXG0 V
A0A857DMN9 A
A0A1X6N3Q5 M
A0A173R3X4 T
Q63EK5 A
K9ZLY2 T
A0A533I6R2 A
I0WJ97 T
K0N2R5 A
M0J579 T
B8GGC1 A
A0A6H9GFU4 A
C6CBB1 G
A0A510HHK8 A
A0A1B9MBX6 C
A0A9Y2AG30 A
E8RSE4 A
F2B2B8 A
Q7UYZ3 A
I1YJH7 S
A0A853MG28 T
A0A0L0STS6 A
A0A251XU71 A
Q60BI2 A
A0A829X098 A
F3KUN4 A
Q60C43 T
A0A0T7FAP8 A
A0A3E2TW06 T
W0E077 T
A0KPE9 G
R7PZ71 A
A0A0A1ZMZ9 T
A0AA40J491 A
D3S2L0 A
A0A373FQ71 A
A0A0A2C6L1 T
Q7W7D3 A
A0A165K0X5 T
A0A2S5X482 A
R9GM11 G
Q0G0A3 S
D4GLQ6 G
E7RJZ0 T
F8IJE0 A
A0A1V2XMU9 A
Q7TNN9 C
A0A1G5RZU9 T
A0A2N6K4Y5 A
B0SLB7 A
A0A251YFS0 A
B9WDK0 A
Q7N0M6 A
A0A0M2LU39 S
F4B548 V
D6Z5V9 T
A0A4R2M206 G
A0A1E2SKM1 S
A0A127JTU2 A
A0A212AV03 A
G4QHD2 T
A0A021VMC6 A
A0A2J7TJ33 A
G7WDB5 T
Q6BK68 C
Q1K3N8 T
A0AA91Q161 A
A0NJ07 A
A0A316BQ38 A
A0A377PLP5 G
W7QGM4 T
A0A015YIP3 T
A0A060UWC8 I
A0A1I4ZIZ6 A
A0A264VQM8 A
A9AUR8 A
A0A1W5PRD1 L
A0A0E3BR91 A
A0A1B0ZRL8 S
B9ACS5 A
Q92BJ7 A
F2JTN3 S
A1AVV2 A
D2Q0J8 A
A0A3S9N9F3 A
A8ZQD5 T
C3X831 A
A0A1M6BPM0 A
A0A8F5VN39 A
A0A1E5C7W4 A
A0A2S5WV24 A
A0A833GZR2 T
C7M2A9 L
A6W7U2 A
W0JIB3 T
Q07UM3 A
A0A066ZRQ5 T
S0G181 T
D3PAH1 A
Q4WHC6 A
A0AA94HTL8 A
D5ASL9 A
A0A4U1JNL6 A
M0MDP9 T
A0A653N397 A
A0A2S8GSU9 A
A0A097R891 G
A0A8H7U3I1 A
A0A1H1MB73 A
A0A016XDZ5 A
A0A1B9JHS5 C
D3PE53 A
A0A9J9BAE8 S
Q2RM12 A
A0A3N0AQL8 A
C5KTM6 T
M1P5F0 S
I1YG38 A
A0A660CH85 A
A0A2N7L7C8 A
Q5KZZ9 A
M1NZT5 S
A0A225CMT8 A
A0A068NV61 T
H2CJI0 T
B0DU93 G
Q221S8 T
F4Y3C5 T
Q94CJ2 M
M0D3Q9 T
A0A3P2A7W8 A
C0GKN4 T
Q7T3R4 L
A0A562USB9 S
A2SS52 A
A0A211ZGL5 A
A0A4V3ALP8 A
A0A147GP06 C
H2IZ00 A
Q45HK8 A
A0A6C8LST1 G
A0A257T8W6 I
Q5P470 A
I5AZQ4 A
Q07UM1 A
E5B358 G
A0A1Y4L5P0 T
Q3AFY9 A
B0BZN3 T
A0A1Q2C7H7 A
A0A4R5U5V1 A
H6LKX6 T
A0A1Y0UZX2 A
F6BEI0 T
M9RKT6 S
A7SGD4 T
A0A257TE48 A
R1FI09 T
E4N1T5 A
U1PIR6 T
F2JYR9 S
Q84KJ7 V
A0A2S8FTB5 T
D2R647 T
G9Y5B0 G
A0A144NLT9 G
A0A5J6WQU1 S
D2R355 A
F3ZYD6 T
B0SL05 T
A0A5A7MAJ9 A
A0A977NL43 A
A0A433ZQ80 A
A0A1Y0V4A5 V
A0A1M7UEG2 A
G8R7U9 A
K1LDP0 T
B7G0Y4 T
A0A2W4ZXC0 A
B3PF77 S
Q2KZK9 A
Q18ES8 T
D3F545 A
B4S394 A
Q1Q357 T
Q9H310 L
D3PKL4 A
M5SY07 A
Q8RUT6 T
A7NKH2 T
Q1Q879 S
A0A1B9M5B8 C
A6LRS5 A
J2ZGN6 T
V5E0F3 A
A0A149RQX0 A
A0A165BP25 G
C0QSY0 A
B0XVV6 A
E0SD83 G
A8HSA2 T
A0A1E3PSK5 A
A5DYQ2 A
A0A4U1K1W1 A
Q0AT01 S
A4FMG0 A
C3YB73 T
A0A9P3CXY2 A
A0A0L8BVU4 A
A0A401WUW1 A
I4C9L2 A
Q8RUE9 M
F0JGZ1 A
A0A2I0UUY1 T
A0A542XGT4 A
G0JRH4 A
A2SPS8 A
A0A5M4AWD2 T
Q6QH01 T
D3F0Z1 A
A6XBM2 L
D6E7B3 A
Q13E03 A
A0A060URB8 A
A0A2T1N7R1 T
D6TCH6 A
B0CXH8 M
A3TVQ9 S
Q4WT12 A
C7QGX3 A
F0Y9X3 T
A0A7S0D560 A
A0A160KTE9 A
A0A2H1HV86 A
A0A251Y3N4 A
A0A419AVL2 A
A0A4Q2QWS1 G
C7Q1E4 A
A0A5C5TYS5 A
F2NNQ0 A
A0A2R4TRE0 G
K9YJQ3 T
D9QS43 T
A7SQ16 T
A1DG05 A
U1SIR9 A
C4Y298 A
A0A9W3LFI9 G
D3RMV7 A
F3QNA7 A
E4RTK5 A
C8XBX8 A
C0QTA4 A
E6VIW4 A
A0A2S6H643 A
Q46HB1 T
A0A2S5CTX8 T
A0A1T4SF40 A
K0K7J4 A
A0A1J5JH24 A
Q6LMI6 S
A0A9W5JBA9 G
A0A291PMC6 A
A0A4Y4DZN4 A
A0A2R4MBA2 A
R9PI53 S
A0A6H9GLV4 T
A0A7S4GND2 T
A0A6H9FPY5 T
A0A1G7DX68 A
A0A075WEB4 A
A0A140NHJ5 A
A0A1C6Z081 G
Q5FA36 A
Q0ACK1 S
A0A975GIX9 A
A0A323UE08 A
U7VB41 P
A0A063Y780 S
C5CIT6 A
A0A0A2VPU3 A
F0RHS0 T
A0A2S5WX34 A
C1G973 A
A0A2S6GKF6 A
A0A0A2B651 T
A0A4R3A5P7 A
A0A2A7U6W1 A
Q2GX26 A
F5XN43 A
A0A0K2STH0 T
A0A1H1U2Q6 A
A7SED8 L
A0LV78 A
K5DBA0 T
B8IZX4 A
A8LKQ0 S
A0A5C6LWQ1 A

In [91]:
seqf = []

for i in f:
    print(i.id, i.seq)
    seqf.append(i.seq)

A0A858ZNJ3 V
A0A1H9M798 T
B0DY50 M
P69680 M
A0A3G9G4Q4 T
A0A149UP06 T
F2G6G4 F
A0A2M9D7S8 M
A0A034WGQ2 I
I0KDC6 T
F8D7H6 W
K9W4V5 F
Q466Y3 V
D2SE15 M
A0A377PBY1 L
B1JZ69 T
A0A2W5HTC3 T
A8G2S3 F
D5T4N9 T
Q2RWY7 S
A0A0E3R4G0 Y
I4C9L0 T
D5VJ32 V
C0Z5S5 F
C1N6X9 A
J7ITF6 I
A0A068SVR1 V
A0A0D7F328 T
Q0G0A4 V
F0J3F9 M
Q0BQ69 T
F2YIC4 -
D4XLN6 T
A0A420WC79 Y
A0A5C5TUT2 V
A0RUZ2 V
A0A0A2ZRL7 T
J4UGB7 L
E5Y678 I
A0A0D2KGN8 M
S5ABR8 F
A9DQM8 I
G5EB13 L
A0A2N6NEK4 M
C6DB68 M
Q81GN5 T
Q0F2M5 F
A0A0C6P439 V
B9SWW9 S
L8H5K0 -
Q9NIV0 -
C1N5A7 A
Q1JXS5 T
A0A1M6JKY3 T
F4D1J0 M
A0A257SYX3 S
V4RK08 F
G0V8D6 L
A0A7S4GMD8 A
B3QVV5 T
F2JZ83 F
A0A857DDJ7 I
A0A0S6UHP2 F
D5EP71 V
F4KY49 T
M5S9B4 L
A0A009PYN3 T
A0A3T0SZ22 M
A0A248LMH8 T
A0A6H9GEE4 F
A7HSP2 M
A0A7V8IKS6 M
T2JFS5 F
F6FRU9 M
A0A9E9L9J1 V
A0AIW5 T
A0A0E9NHV4 L
Q2N625 T
C8WSI9 T
A0A1H1BPD6 M
A0A176XNC5 V
A0A4V0XUI3 F
A7S3L2 V
M5U2P1 L
K9P5D1 C
Q0F2M7 V
A0A2R3IMJ8 I
Q2RVB5 T
A0A556RTU3 M
E0TGP9 Y
B7G0Y1 A
A0A1G9P6Q0 Y
D0LTW3 F
Q6BT62 L
Q2IK04 F
Q6BJI7 M
B7X047 V
A0A068NPW2 T
A0A399NT81 M
K0F9X7 M
A0A037ZMW1 F
A0A075JZ35 V
A0A369MHK2 T
A0A1B9JPL5 M
D8PD01 T
A0A2G5BI87 L
A0A2G5BGA9 M
A0A657K391 M
P69681 M
A0A4P6UIJ8 M
A0A0V8M0W6 T
A0A0H2XSU4 T
Q1Z695 F
A0A7Z0V0A4 T
K0ER80 M
A0A149UWF2 T
G0H0Z6 W
G0EFF3 T
C8WLL8 T
X5CNT2 S
A0A4Y1MSE7 T
H2CLF7 F
M4VEJ9 -
A0A4V2X6C2 L
A0A2K1RA77 S
A0A375YPN6 F
A0A7M6UUM4 -
A0A172YCA7 V
A0A918MJ52 I
A0A2S8QA29 L
A0A251XJT0 M
A0A0B4E6X7 I
A0A0K2STQ7 V
A1C5Z7 M
C9KKP2 T
A0A2Z4MD56 F
Q9VFA9 I
A0A502GPV4 M
I5C044 Y
D2V6P8 -
D3RN22 F
Q97L80 T
A0A0D5YN10 T
A0A1I5GN22 M
A0A1Y5E8I7 Y
B1Y8C9 V
M5SYZ1 L
Q6HM26 T
A0A379A0S9 Y
A0A101DCS3 M
A0A1Y3U5V2 T
A0A202B535 T
F8E6R1 F
Q6ND36 T
A0A8H6K7L7 Q
Q7NCB8 T
A0A369MRW6 T
C9RS76 P
A3U857 T
A0A127PIQ9 V
B8FGW0 T
A0A060JMP6 M
D5V7B3 Y
A0A494JB70 T
A0A5M8QF12 M
A0A8G2F3G4 T
J7L3W8 M
G0JRG9 S
D3DJN2 T
A0A1Y2JH43 V
Q1L727 I
A0A7T2S0Z6 V
A0A315S845 M
A0A2S6H6B7 V
A0A1J5NTP7 I
A0A0E3QY86 S
A0A096EEV9 V
A0A380S5X4 P
B8ZYW3 W
A0A2S8GEJ5 F
A0A248TDF2 V
B2GFN1 M
U1PPI7 W
C7LW88 F
G3A431 V
A0A066ZTE4 F
L7CG99 L
S0ET45 M
A0A178TA08 F
H1XV27 F
A0A6M3ZJI1 V
U5DEY6 F
H6LFQ2 F
Q6CRN0 L
A0A4Q2EAG7 M
A0A1J5NNB8 F
E3I393 M
A0A243SC06 T
D4F313 L
W0F0I7 T
A9B874 F
A1D2Y5 L
T2J0N1 F
Q2FQT3 M
A0A075WG29 F
A0A979GQ79 T
A0A381CAY8 M
A0A2G3DSU6 F
A0A168EVK8 M
A0A094W9G3 L
A0A4R3NVT3 Y
W0DYY3 F
G8JTW0 L
A0A4P6UIK6 V
I9P003 Y
G2T1Y3 F
B8EMQ8 T
I6Z905 F
E0TCV4 Y
A3XNG6 L
A0A087MGU4 V
A2BUP4 F
A0A562S8V2 T
A0A495DND0 T
A0A0S2FHD7 V
F3QPR6 L
A0A063Y394 F
F6G5I9 I
A0A323UDG5 T
A0A0G9HEC5 V
B8FDY8 T
Q5KPM5 M
A0A147EQL9 M
A0A854Q6X9 M
C3X1J1 V
A0A5B2V3B9 V
A0A258FS85 T
A0A7T2W1B3 T
A0A060UN76 F
G0JRQ3 F
D5UD26 M
G2ZN72 V
A0AA46Q839 T
A5UJR1 T
L1INN6 A
C1F584 Y
C5LAG4 V
A0A2A2MCP3 -
B1Y6V4 I
A0A1G6ABK5 F
A0A6A1TYJ4 V
A0A2T4UWF1 M
V4AP67 Q
A0A173R3W6 T
C7NND3 W
B0DFJ4 M
A0A3E2VY88 F
R1EDV9 A
J1L5M8 M
D7G265 S
Q8ERT9 I
I4D6Z9 F
A0A4R6DFU8 M
A0A060URC3 S
D2BIB2 T
F5ISF6 I
A5CRL2 M
A0A6G9XJV9 M
Q59UP8 L
A0A6N4SPH9 P
I0HGY4 M
X5DX97 F
L1J6I4 T
I1DSU5 Y
B9L7N1 T
Q1Z4I4 Y
Q21CP1 T
A0A165MFD1 L
V4CRP5 V
Q7S5K0 M
A0A071MMV1 T
A0A149RYW7 T
A0A7G5EC77 V
A0A1W2GZ82 P
A0A7U3XVQ4 T
A0A071M4L5 I
U5C2K4 P
A0A248LNW8 F
L8H844 T
A0A149V596 T
S9QZ09 V
B1ZSW9 V
D2BUJ8 M
A0A9Q8L398 V
M5S735 V
Q6ARH0 F
K6W5X0 M
G0JRG6 S
A0A6H9FYW4 T
A0A0S4WFM4 V
A0A101HKN9 F
Q9REX3 F
F0S3Z6 V
A8NAG3 M
C6LBD3 F
A0A149U2G9 T
V4REY8 Y
A0A0H3H4I7 M
A8N2H6 M
S0APH6 A
A0A017SYR8 T
A0A1B9MZ78 M
E4T3F3 Y
D7E934 I
A0A0M3AB44 T
A9WHW6 F
A0A5M4AUM9 I
A0A1X4GBG2 F
I4D1H5 I
A0A0E3QYF3 V
B0CQX4 L
A0A378YR15 V
A0A495D4X4 Y
A0A076PL76 V
Q1YDY7 V
A0A3E2UCG9 F
A0A2K3DPU7 -
A0A3R9Q7C4 T
V5U2Z4 M
K9P718 F
M1V7W3 A
Q6LKC8 F
E5Y789 T
J9Z839 S
A0A1G7VM92 V
K9Z0D3 L
A0A482TED1 W
R1EGK6 A
J1ASR8 M
A0A7U4E420 T
K9YR86 F
A8PXT8 V
A0A0U1NJW3 F
B8FL88 F
A2CCK1 F
D6TFE1 E
A0A2H4U5R1 T
I2GD40 T
A0A060HFT5 T
B1Y842 F
A0A0X8NXA9 V
A0A0A2A5X1 F
A0A318FY98 M
Q7V4T8 F
A0A1A0DHK0 -
C1A872 T
A0A395VB65 F
A7MFK3 M
J4KM12 M
A1SY01 F
A0A1H4DJ49 F
A0A9R0NTP8 M
A3PAY4 F
B4CV94 V
A2C095 F
Q2HD43 L
A0A836M2B6 T
H6RWK9 M
A0A087EQK8 T
A0A1I0AQM4 -
L7CG11 V
A0A248LNK5 I
B7FTM9 A
L0K9M1 F
I4D6Z7 I
A0A2K1RA81 S
Q2WBF7 T
A0A1B9BUU6 S
A0A2S0JW39 I
A0A2S5YID7 M
B3PIH2 V
U3P8G1 M
C9R9J0 T
A8AC17 T
F0YLV7 V
A0A1D3GAE9 T
C1MHX0 I
A0A1H4KAQ7 Y
A0A2T4XZC1 M
A1B3N0 V
C7LW87 T
A1SZ12 Y
A0A2T2Y0D5 M
A0A1H8D0R8 -
A0A2S5V2F6 M
G3IYW2 M
F5L8M7 F
C7BJG7 L
E4U5Z1 T
A0A1B9K8L2 M
A0A2S5WMT7 M
A0A0D2UPA8 T
A0A161SKF4 M
B4D7W2 T
A0A1H3WA00 V
C1D6X6 I
A0A4D6KHD1 W
Q488X2 Y
A9V5W4 -
A0A5M4ATH9 T
E4TRS4 P
A0A011U1K7 V
C7R314 M
A0A077EFU9 T
A0A0A2A0Y9 F
A0A0D8BQX6 F
A0A0L0S493 L
A0A328Q6M1 T
A0A016XCG9 V
B7FSA7 A
G0AFH4 V
A0A177W826 L
A0A2S8GF54 F
Q1YDY8 Y
Q5QVH2 Y
A3ZT81 F
A0AA35XZV0 V
F4H924 T
K0NJH2 F
A0A1V3SSW1 L
F2AUF4 L
A6DN47 V
W8KM07 Y
A0A1X3RP39 V
A0A7S0KKL8 A
A0A318QZ80 F
K8VZC6 L
A0A1B9JZS5 M
A0A2S6GKN5 V
A0A4R2Z2K6 M
H1YCC3 T
E1QIU3 F
A0A8H6MPB9 Q
A0A369N7Y3 T
T2IEJ2 F
H5UND3 M
Q1PX09 H
A0A149TSA9 T
F2NGJ8 T
A0A0E3SHQ9 V
Q5FLR6 T
S0EUS1 Y
A0A369M386 T
W0DZS7 V
A8MCL4 T
V3ZVE4 V
O26757 T
A0A317FZW2 L
A0A085GI50 M
A1ZGK6 I
G0IYI2 P
A7S731 V
A0A1U9YY82 Y
A0A328EMN2 T
A0A8E2UDJ3 M
A0A2S5WUP6 M
A0A8H7P8U1 M
A0A257T7G4 S
B3MX93 I
A0A1G5W0P2 T
D4H2Y7 F
A0A4P8HC89 M
Q7T070 -
F7NPQ3 T
B9SA70 S
Q9M6N7 S
I7ZHW3 T
F4XTK4 F
A4G1J2 V
G7WFX4 I
B8JBH5 T
D9QPC8 T
A0A4R7GKA0 M
R9PMC6 F
A0A0E3LMT4 Y
A0A511NGC7 T
E4NS62 W
E4T3F7 V
M0D580 W
J7J5E7 T
B1XZU2 T
A0A366IE34 M
A0A6U2BIY7 A
Q9QXP0 -
A0A424WAH3 V
A0A410K1J5 F
L1IHZ8 T
I8TC71 V
A0A7U8C744 Y
A8M670 M
A0A0S4VNK2 V
Q2SIR0 F
A0A5C4RNH5 L
A0A3E0X011 Y
A0A0E3SP24 S
E1IF27 T
Q2YBP7 -
A0A2S5WZU0 M
A0A172YBR4 F
A0A0K2STK6 V
A0A2N6JV02 F
F0S0G1 T
A0A1C7EL50 V
Q18PF5 -
A0A1I0C958 F
A0AA35XVN2 V
L8GGA0 T
Q3AP28 T
D0MFE9 T
J9VXX9 M
A0A166IS52 F
F0J7D3 S
W7QG13 F
A4BMY5 V
A6LV49 T
Q1H483 V
A6M3G0 T
E4T0A4 I
A0A3E2UHE6 F
A0A174SD65 T
A0A855EH99 M
C3YB74 V
A0A074KZD8 P
J0S2I0 F
K9WSX4 A
E8RLT5 T
Q2FS34 M
Q3Z7F9 T
Q2S8H9 Y
A0A060HN92 V
E6ME92 T
A0A172RYW3 T
L0FU80 P
C8WZE0 F
A0A2S8F4W0 F
A0A2C6C0X3 L
F3ZVV4 M
A0A7R6PER3 Y
A0A495WJM6 T
A0A0B4DUR9 F
A0A251YU48 M
A5D4I5 T
A0A2X2C038 L
A0A2A2M8K7 L
D3FBG3 T
A0A2V4EA49 M
D0MFE8 F
Q3B6Q2 T
A0A1B9KID3 M
A0A9J9ES23 F
A0A3N2SFS2 M
Q0VLH1 F
A0A1U9Z147 I
Q0G2T1 I
A6GJF5 V
A0A059XXR1 S
A0A5J6WPP9 F
P41948 L
L1IUV5 T
A0A2W0GQV0 M
Q1K433 A
A0A4Y7XC43 T
D5AU98 I
E1QFA8 T
A0A075WBP9 M
Q0BWD0 F
A0A1Y0HX98 M
A0A098S5Y7 I
Q0I445 T
A0A1E5BXA4 Y
A0A2C9CK98 T
G4H971 F
A0A1I0BYN1 T
A0A330GB00 M
A0A2S8FR08 V
Q84KJ6 S
A0A2S5WGI8 M
M2ALH9 L
A0A2K3DQF8 A
A0A8G2IZM3 V
F5Y3C1 V
A0A370FPU0 V
F5RGM7 I
A0A4R4K1P9 L
R8VWI7 F
A0A0A2AMW2 F
Q7Z1M1 I
A0A414NWT8 T
A0A0P6VSR8 V
A0A0L0TDW1 L
U3PCH5 A
W7QGE0 V
C5BWX7 M
A0A1B9M1A9 M
B8GGC3 M
D6SPD1 Y
A0A0H3DR67 L
A0A4R7VEK0 V
G4R7P1 F
A0A1M5ZVP9 L
A0A2S5Y0D3 M
I0ICG0 V
D0L8H3 M
A0A1B9LFW3 M
Q6ND34 V
A0A6H9GWG4 F
Q5UZ98 W
A0A2S0P9T4 T
H2CDR5 A
T2KGT3 I
A0A088E6Q7 T
A0A258HS77 T
E1V4T3 F
B7GKP4 F
Q9QUT0 -
I3Z3H7 P
G7WCB6 T
A0A1Y6GLJ1 M
A0A0S2DQB6 V
Q6CRN1 L
A0A401X433 T
A7HT14 F
A0A009TDB1 T
D4XSW0 F
B0SRS8 L
A0A149QSR6 T
B1Y0E5 T
Q7UGU7 L
A0A2S0Q8P1 F
F0ZPL3 T
A0A2T0GTU1 M
I4CCD1 T
A0A9Q6P4A5 T
A0A418VIJ8 V
C1MX19 V
A0A1B9BUZ8 T
K9W6F3 T
Q1K8A3 L
L8GFX3 T
A0A1G6ABL9 T
A0A087L0B9 M
A0A073CP02 F
A0A0A1ZJU5 F
A0A258HPP1 T
A0A149QAW7 T
D2V6Q5 T
A0A1X4G8K1 T
A0A067Z3S3 T
A0A8F5ZDT8 M
A0A854QN45 M
A0A2N7LCD7 Y
G7WFX2 F
A0A7S4GNJ2 V
A4G0C5 W
A6VE60 I
A0A1S1HM83 I
A0A037ZJY5 V
N1WR17 I
Q2W5V2 F
A1VIM5 V
A0A1Y5E3E3 I
A0A1T4SFK4 T
A7RNC3 V
M7XJ51 P
A0A399T909 M
A0A2N6P374 L
H8L2Q4 V
D5EP68 I
E6SF19 M
A0A1T4SFY6 M
D3LBI0 T
E6W5C1 F
Q0VPH4 L
K9WT03 T
L0KW14 M
A0A4R8H081 F
A0A1B9N3H7 M
B0RC35 M
A0A420KGW4 V
A0A4R3NLV5 L
Q47K18 V
Q21P82 F
M1WRK6 T
A0A290XBB5 V
A0A6T9XUR2 F
A0A1J1JH03 F
I3R0S7 W
A9UR54 M
A0A1G7H8X3 I
A0A8G2F718 F
Q1H0G2 L
D0LAL7 M
C7LQR9 F
A0A1G5PWV0 L
K1K628 V
B9SXC7 S
G7WA28 I
Q1IWN6 T
H6LKH9 T
A0A1H7CU41 T
G8JUJ2 L
A0A081N2G5 F
A0A074ME37 T
Q0VQH6 V
C8XB51 M
A1VIG8 V
Q8GQS1 T
A0A1I7FBM5 -
A0A1M6ZMI3 F
A0A482PLH3 M
A0RXK8 V
D0KXQ0 F
Q8JI14 -
A0A7T4WEP4 S
A0A4R3ZNW3 M
A0A074KY88 P
A0A6M3ZKU5 F
M1SJL5 V
A0A1W9KSU5 V
E3GI40 I
A0A369NYJ2 T
A0AA92K392 V
O04161 A
A9BQZ4 V
A0A6N2Z556 F
A0A8H6NAG3 Q
A0A2T9X1V4 S
Q2J376 V
A0A0F5EZP7 V
A0A7G5DK18 I
M9YAI9 V
D2ZRW2 T
G7UUY6 I
A0A8H4GS02 L
A0A2T5IHP0 -
A0A165MAC2 T
A0A7S4LPS8 V
A0A075JIN0 M
C8X554 T
B8FZP7 T
Q5KAF6 M
A0A427KNL6 M
A0A7G5DPV0 V
Q22947 -
A0A1S1HRJ0 L
A0A3N1VXY4 M
A0A2S7YPJ9 M
I0JI83 I
A0A7U3YMN6 V
Q9BLG3 T
A0A1H9RTW8 V
A0A1I4W3A0 M
A0A0B4M163 -
U2EN72 Y
A0A2W5VAZ2 V
E4YA63 A
D5ELM4 F
M9RJS5 V
A0A2G3E8V2 F
Q5FSX6 T
I0HKQ8 V
A0A833H2R7 A
B8ENL9 V
B3DUX7 V
A0A1D8UWJ6 T
D5E995 I
A0A7U8C2Y6 F
L0KGR8 T
B0VMH1 T
P40260 L
L0JT30 W
C1GR74 M
A0A423Y4I6 M
A0A4P7UHQ5 T
A0A8E2R1Y5 M
I5BYV5 P
A0A6B8N021 M
A0A7G5DPV1 F
A0A2G5RQK9 F
A0A5M4B0G1 I
A0A6S5K4J1 M
C1D4X0 T
A1SVA8 F
H1YF74 E
A0A8B4RWH8 V
A0A0A0D6K5 I
A0A0A2BBY0 F
A0A089ZBW5 T
A0A068TC78 V
Q46G49 S
A1CQ21 L
A0A1G6ABX1 Y
E1SLM7 Y
K5CFE5 V
Q2YLQ6 T
Q0G2V0 F
A4ABK3 F
A0A9Q5QVI9 T
A0A4Q7Y9I7 M
A9HMD6 T
K9YN27 F
Q9UBD6 -
D9SI59 I
Q8I0L6 -
A0A142VAD6 T
G3IYW0 V
A0A062IU58 T
R1D1H4 A
A0A366XFS8 V
A0A7S4GNF3 V
F0J6E8 I
A0A7U4DN04 T
V4RHR4 I
F7ZJM0 I
A0A2S5XAB8 M
U5C4L4 P
Q21J04 V
A0A142NNN1 M
H1Y7T6 T
F5R974 F
B0DU91 L
A2BP62 F
A7HSN9 F
A0A377I7W9 V
D2RU19 W
G7WJN0 F
E2SD33 M
A0A0D7F2Y9 V
A0AA92EGF5 V
A0A9E9LXV9 V
A4BEP1 F
A0A0E3WZH5 Y
F7ZEU9 Y
A5E3X2 L
A0A0A3XTJ3 V
A0A830ZZN8 M
A0A1S8D478 T
J7IVQ1 F
A0A2U1SS17 V
S3K1S2 M
C6XKC2 Y
A0A2S7YIM5 L
K2IMJ7 F
Q5P1S8 F
A0A7T5BFQ2 F
A0A556SRH6 M
A8P923 M
A0A7G5DKA9 S
L8JUH3 P
A0A0D2LEF5 L
A0A258FTB0 T
A0A5P9P1L2 W
M8E0R3 F
A0A6J5IRX5 T
W5WIX6 M
Q82X47 -
I4DBY0 T
A0A6F8TLE9 T
A0A1G7UZX2 F
A0A6P4JM51 I
G0J614 P
U2WTW8 F
A0A642KQG8 F
Q1AUG3 L
A0A6G9Y3Q0 M
B8J5X4 F
M7NFH3 F
A0A0E3R6S1 I
Q2IHY5 T
A7I8Z2 M
L1IYP4 T
B4HDZ9 I
A0A366WYI9 F
E4TJ50 -
A0A7S0ILH2 M
A4BAE1 F
B3QRJ4 T
A0A5C5BWI6 T
Q7NQY2 T
A0A091AXI3 V
Q1QSQ2 F
R4FZE3 F
A0A2N0MZ27 M
A9BTK1 T
A0A242NIL1 M
G0LFE3 W
A0A1B9NQ91 M
A0A5M5PZE2 F
A0A0D2NYP3 M
D9QPE5 T
I5B3H0 F
L1IYW7 T
C6WEW7 M
B7FW68 A
F4GED5 V
A0A4R8GSH7 W
A0A1W2H3F0 P
A0A3E2T713 F
A0A0H3KTD3 M
A0A1Y4LM49 F
G2PRJ6 L
A0A0X8X7Y7 Y
K8EJ02 T
A0A1L3F1X5 V
G8TK77 T
A0A855F5Y8 M
A0A975BTN0 T
A0A562RGZ4 F
G5EB09 M
A0A833LX85 F
U1H1F7 T
K8W1E2 L
E3HJW8 V
Q7SEH0 L
Q47X17 I
B0DXT9 L
A0A3G9G2C9 T
Q95P70 -
A0A837C6X5 V
Q89WR5 V
A6DUG4 V
D7UQE2 -
A0A2I1M481 M
A0A0T7GZ59 V
O66395 V
J3EXK0 W
A0A1B9MYL7 I
K9U8C7 F
E2SD44 M
H6LKH6 T
Q605Y6 V
A0A9Q9D9I3 V
A0A6N2TIA4 F
A0A1E3PQH0 L
A4CMI3 I
Q1K0H9 F
A0A0S6UEK9 I
A0A0H3LUA3 V
B9LU00 W
A9BIZ7 F
A0A7H8UK07 M
E3H8C9 F
M2A398 V
Q1QS12 T
G0VI62 L
A0A1Z3MS36 M
A0A0B5FNH4 Y
D9SI36 F
A0A410JZR4 T
F7ZJZ1 F
F0ZCX7 -
W0DZX1 F
A0A4R3ZZ35 M
A0A317G0I6 F
Q0ARJ4 T
A7I8Z4 M
T2KJ59 I
I3C0V3 L
E3H8A6 F
B2IJT1 I
A0A2G6JLT9 F
A3ZZL7 V
A0A2T0XPP2 F
Q31CR9 F
A0A1R1IDV3 V
K2JVF8 Y
V5BYZ7 V
D8J4C6 W
D4H5F9 F
K9ZG59 T
A0AA86YS65 L
Q608B6 F
A0A562BXM4 V
A0A401WXG0 -
A0A857DMN9 M
A0A1X6N3Q5 M
A0A173R3X4 F
Q63EK5 T
K9ZLY2 A
A0A533I6R2 V
I0WJ97 I
K0N2R5 T
M0J579 W
B8GGC1 M
A0A6H9GFU4 T
C6CBB1 M
A0A510HHK8 L
A0A1B9MBX6 M
A0A9Y2AG30 M
E8RSE4 T
F2B2B8 V
Q7UYZ3 V
I1YJH7 F
A0A853MG28 F
A0A0L0STS6 L
A0A251XU71 M
Q60BI2 V
A0A829X098 T
F3KUN4 V
Q60C43 V
A0A0T7FAP8 V
A0A3E2TW06 F
W0E077 F
A0KPE9 M
R7PZ71 T
A0A0A1ZMZ9 F
A0AA40J491 M
D3S2L0 M
A0A373FQ71 V
A0A0A2C6L1 F
Q7W7D3 V
A0A165K0X5 V
A0A2S5X482 M
R9GM11 T
Q0G0A3 Y
D4GLQ6 M
E7RJZ0 V
F8IJE0 T
A0A1V2XMU9 T
Q7TNN9 -
A0A1G5RZU9 V
A0A2N6K4Y5 T
B0SLB7 T
A0A251YFS0 M
B9WDK0 M
Q7N0M6 L
A0A0M2LU39 V
F4B548 S
D6Z5V9 I
A0A4R2M206 V
A0A1E2SKM1 A
A0A127JTU2 V
A0A212AV03 V
G4QHD2 F
A0A021VMC6 M
A0A2J7TJ33 V
G7WDB5 F
Q6BK68 M
Q1K3N8 F
A0AA91Q161 M
A0NJ07 T
A0A316BQ38 V
A0A377PLP5 L
W7QGM4 F
A0A015YIP3 F
A0A060UWC8 S
A0A1I4ZIZ6 T
A0A264VQM8 L
A9AUR8 T
A0A1W5PRD1 -
A0A0E3BR91 V
A0A1B0ZRL8 F
B9ACS5 T
Q92BJ7 T
F2JTN3 F
A1AVV2 I
D2Q0J8 M
A0A3S9N9F3 T
A8ZQD5 F
C3X831 V
A0A1M6BPM0 T
A0A8F5VN39 M
A0A1E5C7W4 F
A0A2S5WV24 M
A0A833GZR2 F
C7M2A9 I
A6W7U2 M
W0JIB3 W
Q07UM3 V
A0A066ZRQ5 F
S0G181 I
D3PAH1 T
Q4WHC6 M
A0AA94HTL8 T
D5ASL9 V
A0A4U1JNL6 I
M0MDP9 W
A0A653N397 V
A0A2S8GSU9 V
A0A097R891 L
A0A8H7U3I1 L
A0A1H1MB73 M
A0A016XDZ5 M
A0A1B9JHS5 M
D3PE53 T
A0A9J9BAE8 F
Q2RM12 I
A0A3N0AQL8 T
C5KTM6 V
M1P5F0 Y
I1YG38 F
A0A660CH85 M
A0A2N7L7C8 F
Q5KZZ9 F
M1NZT5 Y
A0A225CMT8 M
A0A068NV61 E
H2CJI0 F
B0DU93 L
Q221S8 V
F4Y3C5 F
Q94CJ2 -
M0D3Q9 W
A0A3P2A7W8 T
C0GKN4 F
Q7T3R4 -
A0A562USB9 Y
A2SS52 V
A0A211ZGL5 I
A0A4V3ALP8 V
A0A147GP06 V
H2IZ00 M
Q45HK8 V
A0A6C8LST1 M
A0A257T8W6 S
Q5P470 V
I5AZQ4 T
Q07UM1 T
E5B358 M
A0A1Y4L5P0 F
Q3AFY9 T
B0BZN3 F
A0A1Q2C7H7 T
A0A4R5U5V1 V
H6LKX6 F
A0A1Y0UZX2 T
F6BEI0 W
M9RKT6 F
A7SGD4 V
A0A257TE48 F
R1FI09 A
E4N1T5 M
U1PIR6 W
F2JYR9 L
Q84KJ7 S
A0A2S8FTB5 F
D2R647 M
G9Y5B0 L
A0A144NLT9 M
A0A5J6WQU1 Y
D2R355 V
F3ZYD6 F
B0SL05 F
A0A5A7MAJ9 V
A0A977NL43 T
A0A433ZQ80 V
A0A1Y0V4A5 -
A0A1M7UEG2 M
G8R7U9 T
K1LDP0 P
B7G0Y4 A
A0A2W4ZXC0 T
B3PF77 F
Q2KZK9 V
Q18ES8 W
D3F545 F
B4S394 T
Q1Q357 T
Q9H310 -
D3PKL4 T
M5SY07 V
Q8RUT6 A
A7NKH2 F
Q1Q879 F
A0A1B9M5B8 M
A6LRS5 I
J2ZGN6 W
V5E0F3 V
A0A149RQX0 T
A0A165BP25 M
C0QSY0 T
B0XVV6 M
E0SD83 M
A8HSA2 A
A0A1E3PSK5 M
A5DYQ2 M
A0A4U1K1W1 L
Q0AT01 Y
A4FMG0 M
C3YB73 V
A0A9P3CXY2 T
A0A0L8BVU4 V
A0A401WUW1 T
I4C9L2 T
Q8RUE9 -
F0JGZ1 T
A0A2I0UUY1 I
A0A542XGT4 M
G0JRH4 T
A2SPS8 T
A0A5M4AWD2 F
Q6QH01 A
D3F0Z1 F
A6XBM2 -
D6E7B3 T
Q13E03 V
A0A060URB8 T
A0A2T1N7R1 I
D6TCH6 V
B0CXH8 M
A3TVQ9 Y
Q4WT12 L
C7QGX3 M
F0Y9X3 I
A0A7S0D560 V
A0A160KTE9 M
A0A2H1HV86 M
A0A251Y3N4 M
A0A419AVL2 M
A0A4Q2QWS1 M
C7Q1E4 M
A0A5C5TYS5 V
F2NNQ0 T
A0A2R4TRE0 V
K9YJQ3 F
D9QS43 V
A7SQ16 V
A1DG05 M
U1SIR9 M
C4Y298 M
A0A9W3LFI9 M
D3RMV7 V
F3QNA7 V
E4RTK5 T
C8XBX8 M
C0QTA4 T
E6VIW4 V
A0A2S6H643 M
Q46HB1 F
A0A2S5CTX8 I
A0A1T4SF40 T
K0K7J4 M
A0A1J5JH24 I
Q6LMI6 Y
A0A9W5JBA9 M
A0A291PMC6 T
A0A4Y4DZN4 M
A0A2R4MBA2 V
R9PI53 Y
A0A6H9GLV4 F
A0A7S4GND2 V
A0A6H9FPY5 F
A0A1G7DX68 V
A0A075WEB4 T
A0A140NHJ5 L
A0A1C6Z081 L
Q5FA36 T
Q0ACK1 Y
A0A975GIX9 T
A0A323UE08 V
U7VB41 L
A0A063Y780 Y
C5CIT6 -
A0A0A2VPU3 L
F0RHS0 L
A0A2S5WX34 M
C1G973 M
A0A2S6GKF6 M
A0A0A2B651 F
A0A4R3A5P7 V
A0A2A7U6W1 L
Q2GX26 L
F5XN43 M
A0A0K2STH0 V
A0A1H1U2Q6 M
A7SED8 -
A0LV78 M
K5DBA0 L
B8IZX4 T
A8LKQ0 Y
A0A5C6LWQ1 T

In [92]:
seqs = []

for i in s:
    print(i.id, i.seq)
    seqs.append(i.seq)

A0A858ZNJ3 V
A0A1H9M798 V
B0DY50 V
P69680 V
A0A3G9G4Q4 T
A0A149UP06 S
F2G6G4 S
A0A2M9D7S8 S
A0A034WGQ2 S
I0KDC6 T
F8D7H6 S
K9W4V5 S
Q466Y3 S
D2SE15 S
A0A377PBY1 V
B1JZ69 C
A0A2W5HTC3 L
A8G2S3 S
D5T4N9 T
Q2RWY7 A
A0A0E3R4G0 -
I4C9L0 S
D5VJ32 V
C0Z5S5 W
C1N6X9 S
J7ITF6 S
A0A068SVR1 V
A0A0D7F328 A
Q0G0A4 V
F0J3F9 L
Q0BQ69 A
F2YIC4 F
D4XLN6 S
A0A420WC79 S
A0A5C5TUT2 V
A0RUZ2 V
A0A0A2ZRL7 T
J4UGB7 I
E5Y678 T
A0A0D2KGN8 I
S5ABR8 S
A9DQM8 S
G5EB13 V
A0A2N6NEK4 V
C6DB68 V
Q81GN5 S
Q0F2M5 S
A0A0C6P439 V
B9SWW9 A
L8H5K0 F
Q9NIV0 Y
C1N5A7 S
Q1JXS5 S
A0A1M6JKY3 S
F4D1J0 S
A0A257SYX3 A
V4RK08 S
G0V8D6 A
A0A7S4GMD8 A
B3QVV5 T
F2JZ83 S
A0A857DDJ7 T
A0A0S6UHP2 T
D5EP71 V
F4KY49 T
M5S9B4 S
A0A009PYN3 S
A0A3T0SZ22 S
A0A248LMH8 A
A0A6H9GEE4 S
A7HSP2 T
A0A7V8IKS6 V
T2JFS5 S
F6FRU9 S
A0A9E9L9J1 V
A0AIW5 S
A0A0E9NHV4 I
Q2N625 L
C8WSI9 V
A0A1H1BPD6 S
A0A176XNC5 V
A0A4V0XUI3 S
A7S3L2 S
M5U2P1 S
K9P5D1 S
Q0F2M7 I
A0A2R3IMJ8 V
Q2RVB5 T
A0A556RTU3 L
E0TGP9 S
B7G0Y1 A
A0A1G9P6Q0 S
D0LTW3 S
Q6BT62 V
Q2IK04 S
Q6BJI7 A
B7X047 V
A0A068NPW2 S
A0A399NT81 S
K0F9X7 S
A0A037ZMW1 S
A0A075JZ35 I
A0A369MHK2 T
A0A1B9JPL5 L
D8PD01 T
A0A2G5BI87 I
A0A2G5BGA9 I
A0A657K391 P
P69681 V
A0A4P6UIJ8 S
A0A0V8M0W6 T
A0A0H2XSU4 C
Q1Z695 S
A0A7Z0V0A4 A
K0ER80 S
A0A149UWF2 S
G0H0Z6 A
G0EFF3 S
C8WLL8 T
X5CNT2 A
A0A4Y1MSE7 S
H2CLF7 S
M4VEJ9 T
A0A4V2X6C2 I
A0A2K1RA77 A
A0A375YPN6 S
A0A7M6UUM4 M
A0A172YCA7 V
A0A918MJ52 S
A0A2S8QA29 V
A0A251XJT0 S
A0A0B4E6X7 S
A0A0K2STQ7 S
A1C5Z7 M
C9KKP2 T
A0A2Z4MD56 W
Q9VFA9 S
A0A502GPV4 V
I5C044 S
D2V6P8 F
D3RN22 S
Q97L80 T
A0A0D5YN10 S
A0A1I5GN22 S
A0A1Y5E8I7 S
B1Y8C9 V
M5SYZ1 S
Q6HM26 S
A0A379A0S9 S
A0A101DCS3 T
A0A1Y3U5V2 T
A0A202B535 T
F8E6R1 S
Q6ND36 A
A0A8H6K7L7 A
Q7NCB8 S
A0A369MRW6 T
C9RS76 S
A3U857 T
A0A127PIQ9 I
B8FGW0 S
A0A060JMP6 S
D5V7B3 S
A0A494JB70 T
A0A5M8QF12 S
A0A8G2F3G4 S
J7L3W8 S
G0JRG9 A
D3DJN2 S
A0A1Y2JH43 V
Q1L727 S
A0A7T2S0Z6 V
A0A315S845 C
A0A2S6H6B7 V
A0A1J5NTP7 I
A0A0E3QY86 S
A0A096EEV9 V
A0A380S5X4 S
B8ZYW3 S
A0A2S8GEJ5 S
A0A248TDF2 L
B2GFN1 S
U1PPI7 S
C7LW88 S
G3A431 I
A0A066ZTE4 S
L7CG99 S
S0ET45 S
A0A178TA08 W
H1XV27 S
A0A6M3ZJI1 I
U5DEY6 S
H6LFQ2 S
Q6CRN0 V
A0A4Q2EAG7 V
A0A1J5NNB8 T
E3I393 V
A0A243SC06 T
D4F313 V
W0F0I7 T
A9B874 S
A1D2Y5 V
T2J0N1 S
Q2FQT3 T
A0A075WG29 S
A0A979GQ79 V
A0A381CAY8 V
A0A2G3DSU6 S
A0A168EVK8 V
A0A094W9G3 W
A0A4R3NVT3 S
W0DYY3 S
G8JTW0 A
A0A4P6UIK6 V
I9P003 S
G2T1Y3 S
B8EMQ8 A
I6Z905 S
E0TCV4 S
A3XNG6 S
A0A087MGU4 V
A2BUP4 S
A0A562S8V2 T
A0A495DND0 A
A0A0S2FHD7 V
F3QPR6 L
A0A063Y394 S
F6G5I9 I
A0A323UDG5 A
A0A0G9HEC5 I
B8FDY8 T
Q5KPM5 L
A0A147EQL9 S
A0A854Q6X9 I
C3X1J1 V
A0A5B2V3B9 V
A0A258FS85 T
A0A7T2W1B3 V
A0A060UN76 S
G0JRQ3 S
D5UD26 S
G2ZN72 I
A0AA46Q839 T
A5UJR1 S
L1INN6 A
C1F584 T
C5LAG4 S
A0A2A2MCP3 T
B1Y6V4 V
A0A1G6ABK5 S
A0A6A1TYJ4 V
A0A2T4UWF1 S
V4AP67 S
A0A173R3W6 T
C7NND3 S
B0DFJ4 V
A0A3E2VY88 S
R1EDV9 S
J1L5M8 T
D7G265 S
Q8ERT9 S
I4D6Z9 S
A0A4R6DFU8 S
A0A060URC3 A
D2BIB2 T
F5ISF6 I
A5CRL2 S
A0A6G9XJV9 S
Q59UP8 A
A0A6N4SPH9 S
I0HGY4 S
X5DX97 S
L1J6I4 C
I1DSU5 S
B9L7N1 S
Q1Z4I4 S
Q21CP1 A
A0A165MFD1 S
V4CRP5 S
Q7S5K0 A
A0A071MMV1 C
A0A149RYW7 T
A0A7G5EC77 V
A0A1W2GZ82 S
A0A7U3XVQ4 S
A0A071M4L5 V
U5C2K4 S
A0A248LNW8 S
L8H844 S
A0A149V596 S
S9QZ09 V
B1ZSW9 L
D2BUJ8 L
A0A9Q8L398 L
M5S735 C
Q6ARH0 S
K6W5X0 A
G0JRG6 A
A0A6H9FYW4 S
A0A0S4WFM4 I
A0A101HKN9 S
Q9REX3 S
F0S3Z6 S
A8NAG3 I
C6LBD3 S
A0A149U2G9 S
V4REY8 S
A0A0H3H4I7 V
A8N2H6 M
S0APH6 L
A0A017SYR8 A
A0A1B9MZ78 L
E4T3F3 -
D7E934 S
A0A0M3AB44 S
A9WHW6 A
A0A5M4AUM9 T
A0A1X4GBG2 S
I4D1H5 S
A0A0E3QYF3 S
B0CQX4 M
A0A378YR15 V
A0A495D4X4 S
A0A076PL76 V
Q1YDY7 V
A0A3E2UCG9 S
A0A2K3DPU7 -
A0A3R9Q7C4 T
V5U2Z4 V
K9P718 S
M1V7W3 A
Q6LKC8 S
E5Y789 S
J9Z839 A
A0A1G7VM92 V
K9Z0D3 S
A0A482TED1 S
R1EGK6 S
J1ASR8 T
A0A7U4E420 T
K9YR86 S
A8PXT8 C
A0A0U1NJW3 S
B8FL88 S
A2CCK1 S
D6TFE1 -
A0A2H4U5R1 S
I2GD40 T
A0A060HFT5 V
B1Y842 S
A0A0X8NXA9 V
A0A0A2A5X1 S
A0A318FY98 V
Q7V4T8 S
A0A1A0DHK0 L
C1A872 S
A0A395VB65 S
A7MFK3 V
J4KM12 V
A1SY01 S
A0A1H4DJ49 S
A0A9R0NTP8 S
A3PAY4 S
B4CV94 V
A2C095 S
Q2HD43 I
A0A836M2B6 S
H6RWK9 S
A0A087EQK8 V
A0A1I0AQM4 M
L7CG11 C
A0A248LNK5 T
B7FTM9 A
L0K9M1 S
I4D6Z7 T
A0A2K1RA81 A
Q2WBF7 T
A0A1B9BUU6 A
A0A2S0JW39 S
A0A2S5YID7 S
B3PIH2 V
U3P8G1 S
C9R9J0 S
A8AC17 A
F0YLV7 S
A0A1D3GAE9 T
C1MHX0 T
A0A1H4KAQ7 S
A0A2T4XZC1 V
A1B3N0 V
C7LW87 T
A1SZ12 S
A0A2T2Y0D5 V
A0A1H8D0R8 M
A0A2S5V2F6 A
G3IYW2 V
F5L8M7 F
C7BJG7 I
E4U5Z1 S
A0A1B9K8L2 P
A0A2S5WMT7 S
A0A0D2UPA8 S
A0A161SKF4 S
B4D7W2 T
A0A1H3WA00 I
C1D6X6 T
A0A4D6KHD1 S
Q488X2 S
A9V5W4 Y
A0A5M4ATH9 T
E4TRS4 S
A0A011U1K7 V
C7R314 S
A0A077EFU9 T
A0A0A2A0Y9 S
A0A0D8BQX6 W
A0A0L0S493 V
A0A328Q6M1 S
A0A016XCG9 V
B7FSA7 A
G0AFH4 I
A0A177W826 Y
A0A2S8GF54 S
Q1YDY8 S
Q5QVH2 S
A3ZT81 S
A0AA35XZV0 I
F4H924 T
K0NJH2 S
A0A1V3SSW1 W
F2AUF4 S
A6DN47 S
W8KM07 S
A0A1X3RP39 I
A0A7S0KKL8 S
A0A318QZ80 S
K8VZC6 V
A0A1B9JZS5 P
A0A2S6GKN5 V
A0A4R2Z2K6 V
H1YCC3 T
E1QIU3 S
A0A8H6MPB9 A
A0A369N7Y3 T
T2IEJ2 S
H5UND3 S
Q1PX09 A
A0A149TSA9 S
F2NGJ8 I
A0A0E3SHQ9 S
Q5FLR6 V
S0EUS1 V
A0A369M386 T
W0DZS7 V
A8MCL4 V
V3ZVE4 S
O26757 S
A0A317FZW2 S
A0A085GI50 V
A1ZGK6 S
G0IYI2 S
A7S731 S
A0A1U9YY82 S
A0A328EMN2 T
A0A8E2UDJ3 S
A0A2S5WUP6 A
A0A8H7P8U1 I
A0A257T7G4 A
B3MX93 S
A0A1G5W0P2 S
D4H2Y7 S
A0A4P8HC89 S
Q7T070 F
F7NPQ3 T
B9SA70 G
Q9M6N7 A
I7ZHW3 A
F4XTK4 S
A4G1J2 V
G7WFX4 T
B8JBH5 S
D9QPC8 T
A0A4R7GKA0 V
R9PMC6 S
A0A0E3LMT4 -
A0A511NGC7 T
E4NS62 S
E4T3F7 I
M0D580 S
J7J5E7 S
B1XZU2 S
A0A366IE34 V
A0A6U2BIY7 S
Q9QXP0 F
A0A424WAH3 V
A0A410K1J5 S
L1IHZ8 T
I8TC71 V
A0A7U8C744 S
A8M670 S
A0A0S4VNK2 I
Q2SIR0 S
A0A5C4RNH5 I
A0A3E0X011 S
A0A0E3SP24 S
E1IF27 S
Q2YBP7 M
A0A2S5WZU0 S
A0A172YBR4 S
A0A0K2STK6 S
A0A2N6JV02 S
F0S0G1 S
A0A1C7EL50 S
Q18PF5 Y
A0A1I0C958 S
A0AA35XVN2 V
L8GGA0 S
Q3AP28 A
D0MFE9 S
J9VXX9 I
A0A166IS52 S
F0J7D3 A
W7QG13 S
A4BMY5 V
A6LV49 T
Q1H483 V
A6M3G0 T
E4T0A4 T
A0A3E2UHE6 S
A0A174SD65 T
A0A855EH99 V
C3YB74 S
A0A074KZD8 S
J0S2I0 S
K9WSX4 T
E8RLT5 A
Q2FS34 T
Q3Z7F9 T
Q2S8H9 S
A0A060HN92 T
E6ME92 T
A0A172RYW3 T
L0FU80 S
C8WZE0 S
A0A2S8F4W0 S
A0A2C6C0X3 V
F3ZVV4 T
A0A7R6PER3 S
A0A495WJM6 T
A0A0B4DUR9 S
A0A251YU48 S
A5D4I5 S
A0A2X2C038 V
A0A2A2M8K7 V
D3FBG3 S
A0A2V4EA49 L
D0MFE8 S
Q3B6Q2 A
A0A1B9KID3 P
A0A9J9ES23 S
A0A3N2SFS2 V
Q0VLH1 S
A0A1U9Z147 T
Q0G2T1 S
A6GJF5 S
A0A059XXR1 A
A0A5J6WPP9 S
P41948 L
L1IUV5 T
A0A2W0GQV0 V
Q1K433 S
A0A4Y7XC43 S
D5AU98 L
E1QFA8 T
A0A075WBP9 T
Q0BWD0 S
A0A1Y0HX98 S
A0A098S5Y7 S
Q0I445 T
A0A1E5BXA4 S
A0A2C9CK98 T
G4H971 C
A0A1I0BYN1 T
A0A330GB00 V
A0A2S8FR08 C
Q84KJ6 A
A0A2S5WGI8 A
M2ALH9 S
A0A2K3DQF8 S
A0A8G2IZM3 V
F5Y3C1 V
A0A370FPU0 V
F5RGM7 I
A0A4R4K1P9 I
R8VWI7 S
A0A0A2AMW2 S
Q7Z1M1 S
A0A414NWT8 T
A0A0P6VSR8 I
A0A0L0TDW1 V
U3PCH5 G
W7QGE0 V
C5BWX7 A
A0A1B9M1A9 P
B8GGC3 T
D6SPD1 S
A0A0H3DR67 T
A0A4R7VEK0 V
G4R7P1 S
A0A1M5ZVP9 S
A0A2S5Y0D3 S
I0ICG0 S
D0L8H3 A
A0A1B9LFW3 L
Q6ND34 V
A0A6H9GWG4 S
Q5UZ98 S
A0A2S0P9T4 T
H2CDR5 S
T2KGT3 S
A0A088E6Q7 V
A0A258HS77 T
E1V4T3 S
B7GKP4 W
Q9QUT0 F
I3Z3H7 S
G7WCB6 S
A0A1Y6GLJ1 V
A0A0S2DQB6 V
Q6CRN1 V
A0A401X433 S
A7HT14 A
A0A009TDB1 S
D4XSW0 S
B0SRS8 S
A0A149QSR6 T
B1Y0E5 V
Q7UGU7 S
A0A2S0Q8P1 S
F0ZPL3 T
A0A2T0GTU1 S
I4CCD1 T
A0A9Q6P4A5 T
A0A418VIJ8 V
C1MX19 V
A0A1B9BUZ8 V
K9W6F3 S
Q1K8A3 I
L8GFX3 S
A0A1G6ABL9 C
A0A087L0B9 V
A0A073CP02 S
A0A0A1ZJU5 S
A0A258HPP1 A
A0A149QAW7 S
D2V6Q5 S
A0A1X4G8K1 S
A0A067Z3S3 T
A0A8F5ZDT8 T
A0A854QN45 L
A0A2N7LCD7 S
G7WFX2 S
A0A7S4GNJ2 S
A4G0C5 S
A6VE60 V
A0A1S1HM83 T
A0A037ZJY5 V
N1WR17 S
Q2W5V2 S
A1VIM5 V
A0A1Y5E3E3 I
A0A1T4SFK4 A
A7RNC3 S
M7XJ51 S
A0A399T909 S
A0A2N6P374 I
H8L2Q4 I
D5EP68 S
E6SF19 S
A0A1T4SFY6 S
D3LBI0 V
E6W5C1 S
Q0VPH4 S
K9WT03 S
L0KW14 T
A0A4R8H081 S
A0A1B9N3H7 L
B0RC35 S
A0A420KGW4 V
A0A4R3NLV5 V
Q47K18 V
Q21P82 S
M1WRK6 S
A0A290XBB5 V
A0A6T9XUR2 S
A0A1J1JH03 S
I3R0S7 S
A9UR54 S
A0A1G7H8X3 L
A0A8G2F718 S
Q1H0G2 S
D0LAL7 S
C7LQR9 S
A0A1G5PWV0 I
K1K628 V
B9SXC7 A
G7WA28 S
Q1IWN6 S
H6LKH9 V
A0A1H7CU41 T
G8JUJ2 V
A0A081N2G5 S
A0A074ME37 L
Q0VQH6 V
C8XB51 A
A1VIG8 V
Q8GQS1 T
A0A1I7FBM5 M
A0A1M6ZMI3 S
A0A482PLH3 V
A0RXK8 V
D0KXQ0 S
Q8JI14 Y
A0A7T4WEP4 A
A0A4R3ZNW3 A
A0A074KY88 S
A0A6M3ZKU5 S
M1SJL5 T
A0A1W9KSU5 V
E3GI40 C
A0A369NYJ2 T
A0AA92K392 I
O04161 S
A9BQZ4 V
A0A6N2Z556 S
A0A8H6NAG3 A
A0A2T9X1V4 A
Q2J376 V
A0A0F5EZP7 T
A0A7G5DK18 V
M9YAI9 T
D2ZRW2 S
G7UUY6 L
A0A8H4GS02 V
A0A2T5IHP0 M
A0A165MAC2 A
A0A7S4LPS8 S
A0A075JIN0 S
C8X554 S
B8FZP7 S
Q5KAF6 I
A0A427KNL6 V
A0A7G5DPV0 V
Q22947 M
A0A1S1HRJ0 V
A0A3N1VXY4 V
A0A2S7YPJ9 V
I0JI83 F
A0A7U3YMN6 I
Q9BLG3 S
A0A1H9RTW8 V
A0A1I4W3A0 S
A0A0B4M163 F
U2EN72 S
A0A2W5VAZ2 V
E4YA63 S
D5ELM4 S
M9RJS5 V
A0A2G3E8V2 S
Q5FSX6 T
I0HKQ8 V
A0A833H2R7 S
B8ENL9 I
B3DUX7 M
A0A1D8UWJ6 A
D5E995 S
A0A7U8C2Y6 S
L0KGR8 A
B0VMH1 S
P40260 A
L0JT30 S
C1GR74 V
A0A423Y4I6 V
A0A4P7UHQ5 S
A0A8E2R1Y5 S
I5BYV5 S
A0A6B8N021 V
A0A7G5DPV1 S
A0A2G5RQK9 W
A0A5M4B0G1 T
A0A6S5K4J1 V
C1D4X0 A
A1SVA8 S
H1YF74 -
A0A8B4RWH8 V
A0A0A0D6K5 V
A0A0A2BBY0 S
A0A089ZBW5 S
A0A068TC78 V
Q46G49 S
A1CQ21 V
A0A1G6ABX1 S
E1SLM7 S
K5CFE5 C
Q2YLQ6 T
Q0G2V0 S
A4ABK3 S
A0A9Q5QVI9 S
A0A4Q7Y9I7 S
A9HMD6 T
K9YN27 S
Q9UBD6 F
D9SI59 V
Q8I0L6 Y
A0A142VAD6 T
G3IYW0 V
A0A062IU58 S
R1D1H4 S
A0A366XFS8 V
A0A7S4GNF3 S
F0J6E8 T
A0A7U4DN04 A
V4RHR4 S
F7ZJM0 S
A0A2S5XAB8 S
U5C4L4 S
Q21J04 V
A0A142NNN1 A
H1Y7T6 T
F5R974 S
B0DU91 V
A2BP62 S
A7HSN9 S
A0A377I7W9 T
D2RU19 S
G7WJN0 S
E2SD33 S
A0A0D7F2Y9 V
A0AA92EGF5 I
A0A9E9LXV9 V
A4BEP1 S
A0A0E3WZH5 -
F7ZEU9 S
A5E3X2 V
A0A0A3XTJ3 V
A0A830ZZN8 V
A0A1S8D478 S
J7IVQ1 S
A0A2U1SS17 I
S3K1S2 V
C6XKC2 S
A0A2S7YIM5 I
K2IMJ7 S
Q5P1S8 S
A0A7T5BFQ2 S
A0A556SRH6 L
A8P923 V
A0A7G5DKA9 S
L8JUH3 S
A0A0D2LEF5 M
A0A258FTB0 A
A0A5P9P1L2 S
M8E0R3 W
A0A6J5IRX5 C
W5WIX6 S
Q82X47 M
I4DBY0 S
A0A6F8TLE9 S
A0A1G7UZX2 S
A0A6P4JM51 S
G0J614 S
U2WTW8 W
A0A642KQG8 S
Q1AUG3 W
A0A6G9Y3Q0 S
B8J5X4 S
M7NFH3 F
A0A0E3R6S1 T
Q2IHY5 S
A7I8Z2 T
L1IYP4 S
B4HDZ9 S
A0A366WYI9 S
E4TJ50 S
A0A7S0ILH2 T
A4BAE1 S
B3QRJ4 A
A0A5C5BWI6 T
Q7NQY2 T
A0A091AXI3 V
Q1QSQ2 S
R4FZE3 W
A0A2N0MZ27 V
A9BTK1 V
A0A242NIL1 L
G0LFE3 S
A0A1B9NQ91 P
A0A5M5PZE2 S
A0A0D2NYP3 V
D9QPE5 A
I5B3H0 S
L1IYW7 C
C6WEW7 S
B7FW68 A
F4GED5 V
A0A4R8GSH7 S
A0A1W2H3F0 S
A0A3E2T713 S
A0A0H3KTD3 V
A0A1Y4LM49 S
G2PRJ6 S
A0A0X8X7Y7 S
K8EJ02 Y
A0A1L3F1X5 V
G8TK77 V
A0A855F5Y8 V
A0A975BTN0 L
A0A562RGZ4 S
G5EB09 M
A0A833LX85 S
U1H1F7 T
K8W1E2 V
E3HJW8 V
Q7SEH0 V
Q47X17 I
B0DXT9 V
A0A3G9G2C9 A
Q95P70 F
A0A837C6X5 V
Q89WR5 V
A6DUG4 S
D7UQE2 M
A0A2I1M481 S
A0A0T7GZ59 I
O66395 F
J3EXK0 S
A0A1B9MYL7 L
K9U8C7 S
E2SD44 S
H6LKH6 V
Q605Y6 V
A0A9Q9D9I3 V
A0A6N2TIA4 S
A0A1E3PQH0 V
A4CMI3 S
Q1K0H9 S
A0A0S6UEK9 T
A0A0H3LUA3 V
B9LU00 S
A9BIZ7 S
A0A7H8UK07 V
E3H8C9 S
M2A398 C
Q1QS12 C
G0VI62 L
A0A1Z3MS36 V
A0A0B5FNH4 S
D9SI36 S
A0A410JZR4 S
F7ZJZ1 S
F0ZCX7 Y
W0DZX1 S
A0A4R3ZZ35 S
A0A317G0I6 S
Q0ARJ4 A
A7I8Z4 T
T2KJ59 S
I3C0V3 S
E3H8A6 S
B2IJT1 I
A0A2G6JLT9 S
A3ZZL7 C
A0A2T0XPP2 S
Q31CR9 S
A0A1R1IDV3 V
K2JVF8 S
V5BYZ7 I
D8J4C6 S
D4H5F9 S
K9ZG59 S
A0AA86YS65 V
Q608B6 S
A0A562BXM4 V
A0A401WXG0 L
A0A857DMN9 T
A0A1X6N3Q5 I
A0A173R3X4 S
Q63EK5 S
K9ZLY2 T
A0A533I6R2 V
I0WJ97 S
K0N2R5 L
M0J579 S
B8GGC1 T
A0A6H9GFU4 S
C6CBB1 I
A0A510HHK8 W
A0A1B9MBX6 L
A0A9Y2AG30 S
E8RSE4 T
F2B2B8 C
Q7UYZ3 C
I1YJH7 S
A0A853MG28 S
A0A0L0STS6 V
A0A251XU71 S
Q60BI2 L
A0A829X098 T
F3KUN4 V
Q60C43 V
A0A0T7FAP8 I
A0A3E2TW06 S
W0E077 A
A0KPE9 V
R7PZ71 S
A0A0A1ZMZ9 S
A0AA40J491 V
D3S2L0 T
A0A373FQ71 V
A0A0A2C6L1 S
Q7W7D3 V
A0A165K0X5 S
A0A2S5X482 S
R9GM11 V
Q0G0A3 S
D4GLQ6 V
E7RJZ0 S
F8IJE0 V
A0A1V2XMU9 C
Q7TNN9 F
A0A1G5RZU9 S
A0A2N6K4Y5 S
B0SLB7 S
A0A251YFS0 S
B9WDK0 A
Q7N0M6 I
A0A0M2LU39 V
F4B548 A
D6Z5V9 S
A0A4R2M206 V
A0A1E2SKM1 G
A0A127JTU2 V
A0A212AV03 V
G4QHD2 S
A0A021VMC6 S
A0A2J7TJ33 I
G7WDB5 S
Q6BK68 F
Q1K3N8 S
A0AA91Q161 A
A0NJ07 V
A0A316BQ38 I
A0A377PLP5 V
W7QGM4 S
A0A015YIP3 S
A0A060UWC8 A
A0A1I4ZIZ6 C
A0A264VQM8 I
A9AUR8 S
A0A1W5PRD1 F
A0A0E3BR91 V
A0A1B0ZRL8 S
B9ACS5 S
Q92BJ7 S
F2JTN3 S
A1AVV2 I
D2Q0J8 S
A0A3S9N9F3 C
A8ZQD5 S
C3X831 V
A0A1M6BPM0 T
A0A8F5VN39 T
A0A1E5C7W4 S
A0A2S5WV24 S
A0A833GZR2 S
C7M2A9 L
A6W7U2 S
W0JIB3 S
Q07UM3 V
A0A066ZRQ5 S
S0G181 S
D3PAH1 S
Q4WHC6 M
A0AA94HTL8 S
D5ASL9 V
A0A4U1JNL6 L
M0MDP9 S
A0A653N397 V
A0A2S8GSU9 C
A0A097R891 V
A0A8H7U3I1 M
A0A1H1MB73 S
A0A016XDZ5 S
A0A1B9JHS5 L
D3PE53 S
A0A9J9BAE8 S
Q2RM12 T
A0A3N0AQL8 T
C5KTM6 S
M1P5F0 S
I1YG38 S
A0A660CH85 A
A0A2N7L7C8 S
Q5KZZ9 W
M1NZT5 S
A0A225CMT8 S
A0A068NV61 -
H2CJI0 S
B0DU93 V
Q221S8 V
F4Y3C5 S
Q94CJ2 F
M0D3Q9 S
A0A3P2A7W8 S
C0GKN4 S
Q7T3R4 Y
A0A562USB9 S
A2SS52 V
A0A211ZGL5 V
A0A4V3ALP8 V
A0A147GP06 V
H2IZ00 V
Q45HK8 I
A0A6C8LST1 V
A0A257T8W6 A
Q5P470 V
I5AZQ4 L
Q07UM1 A
E5B358 V
A0A1Y4L5P0 S
Q3AFY9 S
B0BZN3 S
A0A1Q2C7H7 T
A0A4R5U5V1 V
H6LKX6 S
A0A1Y0UZX2 S
F6BEI0 S
M9RKT6 S
A7SGD4 S
A0A257TE48 S
R1FI09 S
E4N1T5 S
U1PIR6 S
F2JYR9 S
Q84KJ7 A
A0A2S8FTB5 S
D2R647 S
G9Y5B0 V
A0A144NLT9 V
A0A5J6WQU1 S
D2R355 C
F3ZYD6 S
B0SL05 S
A0A5A7MAJ9 V
A0A977NL43 V
A0A433ZQ80 T
A0A1Y0V4A5 L
A0A1M7UEG2 S
G8R7U9 T
K1LDP0 S
B7G0Y4 A
A0A2W4ZXC0 T
B3PF77 S
Q2KZK9 V
Q18ES8 S
D3F545 W
B4S394 A
Q1Q357 T
Q9H310 F
D3PKL4 S
M5SY07 C
Q8RUT6 S
A7NKH2 S
Q1Q879 S
A0A1B9M5B8 P
A6LRS5 S
J2ZGN6 S
V5E0F3 V
A0A149RQX0 S
A0A165BP25 V
C0QSY0 S
B0XVV6 M
E0SD83 I
A8HSA2 A
A0A1E3PSK5 M
A5DYQ2 A
A0A4U1K1W1 V
Q0AT01 S
A4FMG0 S
C3YB73 S
A0A9P3CXY2 S
A0A0L8BVU4 I
A0A401WUW1 S
I4C9L2 S
Q8RUE9 F
F0JGZ1 T
A0A2I0UUY1 S
A0A542XGT4 S
G0JRH4 V
A2SPS8 T
A0A5M4AWD2 S
Q6QH01 A
D3F0Z1 W
A6XBM2 F
D6E7B3 T
Q13E03 V
A0A060URB8 V
A0A2T1N7R1 S
D6TCH6 I
B0CXH8 V
A3TVQ9 S
Q4WT12 V
C7QGX3 S
F0Y9X3 S
A0A7S0D560 V
A0A160KTE9 S
A0A2H1HV86 A
A0A251Y3N4 S
A0A419AVL2 V
A0A4Q2QWS1 V
C7Q1E4 S
A0A5C5TYS5 V
F2NNQ0 S
A0A2R4TRE0 V
K9YJQ3 S
D9QS43 S
A7SQ16 S
A1DG05 M
U1SIR9 S
C4Y298 A
A0A9W3LFI9 V
D3RMV7 V
F3QNA7 C
E4RTK5 T
C8XBX8 S
C0QTA4 A
E6VIW4 V
A0A2S6H643 V
Q46HB1 S
A0A2S5CTX8 S
A0A1T4SF40 A
K0K7J4 S
A0A1J5JH24 T
Q6LMI6 S
A0A9W5JBA9 V
A0A291PMC6 S
A0A4Y4DZN4 S
A0A2R4MBA2 V
R9PI53 S
A0A6H9GLV4 S
A0A7S4GND2 S
A0A6H9FPY5 S
A0A1G7DX68 V
A0A075WEB4 V
A0A140NHJ5 V
A0A1C6Z081 V
Q5FA36 T
Q0ACK1 S
A0A975GIX9 L
A0A323UE08 V
U7VB41 T
A0A063Y780 S
C5CIT6 T
A0A0A2VPU3 I
F0RHS0 S
A0A2S5WX34 S
C1G973 V
A0A2S6GKF6 V
A0A0A2B651 S
A0A4R3A5P7 I
A0A2A7U6W1 V
Q2GX26 I
F5XN43 S
A0A0K2STH0 S
A0A1H1U2Q6 S
A7SED8 Y
A0LV78 T
K5DBA0 S
B8IZX4 S
A8LKQ0 S
A0A5C6LWQ1 V

In [93]:
seqf1 = []

for i in f1:
    print(i.id, i.seq)
    seqf1.append(i.seq)

A0A858ZNJ3 F
A0A1H9M798 F
B0DY50 F
P69680 F
A0A3G9G4Q4 F
A0A149UP06 F
F2G6G4 F
A0A2M9D7S8 F
A0A034WGQ2 F
I0KDC6 F
F8D7H6 F
K9W4V5 F
Q466Y3 F
D2SE15 F
A0A377PBY1 F
B1JZ69 F
A0A2W5HTC3 F
A8G2S3 F
D5T4N9 F
Q2RWY7 F
A0A0E3R4G0 F
I4C9L0 F
D5VJ32 F
C0Z5S5 F
C1N6X9 F
J7ITF6 F
A0A068SVR1 F
A0A0D7F328 F
Q0G0A4 F
F0J3F9 F
Q0BQ69 F
F2YIC4 F
D4XLN6 F
A0A420WC79 F
A0A5C5TUT2 F
A0RUZ2 F
A0A0A2ZRL7 F
J4UGB7 F
E5Y678 F
A0A0D2KGN8 F
S5ABR8 F
A9DQM8 F
G5EB13 F
A0A2N6NEK4 F
C6DB68 F
Q81GN5 F
Q0F2M5 F
A0A0C6P439 F
B9SWW9 F
L8H5K0 F
Q9NIV0 F
C1N5A7 F
Q1JXS5 F
A0A1M6JKY3 F
F4D1J0 F
A0A257SYX3 F
V4RK08 F
G0V8D6 F
A0A7S4GMD8 F
B3QVV5 F
F2JZ83 F
A0A857DDJ7 F
A0A0S6UHP2 F
D5EP71 F
F4KY49 F
M5S9B4 F
A0A009PYN3 F
A0A3T0SZ22 F
A0A248LMH8 F
A0A6H9GEE4 F
A7HSP2 F
A0A7V8IKS6 F
T2JFS5 F
F6FRU9 F
A0A9E9L9J1 F
A0AIW5 F
A0A0E9NHV4 F
Q2N625 F
C8WSI9 F
A0A1H1BPD6 F
A0A176XNC5 F
A0A4V0XUI3 F
A7S3L2 F
M5U2P1 F
K9P5D1 F
Q0F2M7 F
A0A2R3IMJ8 F
Q2RVB5 F
A0A556RTU3 F
E0TGP9 F
B7G0Y1 F
A0A1G9P6Q0 F
D0LTW3 F
Q6BT62 F
Q2IK04 F
Q6BJI7 F
B7X047 F
A0A068NPW2 F
A0A399NT81 F
K0F9X7 F
A0A037ZMW1 F
A0A075JZ35 F
A0A369MHK2 F
A0A1B9JPL5 F
D8PD01 F
A0A2G5BI87 F
A0A2G5BGA9 F
A0A657K391 F
P69681 F
A0A4P6UIJ8 F
A0A0V8M0W6 F
A0A0H2XSU4 F
Q1Z695 F
A0A7Z0V0A4 F
K0ER80 F
A0A149UWF2 F
G0H0Z6 F
G0EFF3 F
C8WLL8 F
X5CNT2 F
A0A4Y1MSE7 F
H2CLF7 F
M4VEJ9 F
A0A4V2X6C2 F
A0A2K1RA77 F
A0A375YPN6 F
A0A7M6UUM4 V
A0A172YCA7 F
A0A918MJ52 F
A0A2S8QA29 F
A0A251XJT0 F
A0A0B4E6X7 F
A0A0K2STQ7 F
A1C5Z7 F
C9KKP2 F
A0A2Z4MD56 F
Q9VFA9 F
A0A502GPV4 F
I5C044 F
D2V6P8 F
D3RN22 F
Q97L80 F
A0A0D5YN10 F
A0A1I5GN22 F
A0A1Y5E8I7 F
B1Y8C9 F
M5SYZ1 F
Q6HM26 F
A0A379A0S9 F
A0A101DCS3 F
A0A1Y3U5V2 F
A0A202B535 F
F8E6R1 F
Q6ND36 F
A0A8H6K7L7 F
Q7NCB8 F
A0A369MRW6 F
C9RS76 F
A3U857 F
A0A127PIQ9 F
B8FGW0 F
A0A060JMP6 F
D5V7B3 F
A0A494JB70 F
A0A5M8QF12 F
A0A8G2F3G4 F
J7L3W8 F
G0JRG9 F
D3DJN2 F
A0A1Y2JH43 F
Q1L727 Y
A0A7T2S0Z6 F
A0A315S845 F
A0A2S6H6B7 F
A0A1J5NTP7 F
A0A0E3QY86 F
A0A096EEV9 F
A0A380S5X4 F
B8ZYW3 F
A0A2S8GEJ5 F
A0A248TDF2 F
B2GFN1 F
U1PPI7 F
C7LW88 F
G3A431 F
A0A066ZTE4 F
L7CG99 F
S0ET45 F
A0A178TA08 F
H1XV27 F
A0A6M3ZJI1 F
U5DEY6 F
H6LFQ2 F
Q6CRN0 F
A0A4Q2EAG7 F
A0A1J5NNB8 F
E3I393 F
A0A243SC06 F
D4F313 F
W0F0I7 F
A9B874 F
A1D2Y5 F
T2J0N1 F
Q2FQT3 F
A0A075WG29 F
A0A979GQ79 F
A0A381CAY8 F
A0A2G3DSU6 F
A0A168EVK8 F
A0A094W9G3 F
A0A4R3NVT3 F
W0DYY3 F
G8JTW0 F
A0A4P6UIK6 F
I9P003 F
G2T1Y3 F
B8EMQ8 F
I6Z905 F
E0TCV4 F
A3XNG6 F
A0A087MGU4 F
A2BUP4 F
A0A562S8V2 F
A0A495DND0 F
A0A0S2FHD7 F
F3QPR6 F
A0A063Y394 F
F6G5I9 F
A0A323UDG5 F
A0A0G9HEC5 F
B8FDY8 F
Q5KPM5 F
A0A147EQL9 F
A0A854Q6X9 F
C3X1J1 F
A0A5B2V3B9 F
A0A258FS85 F
A0A7T2W1B3 F
A0A060UN76 F
G0JRQ3 F
D5UD26 F
G2ZN72 F
A0AA46Q839 F
A5UJR1 F
L1INN6 F
C1F584 F
C5LAG4 F
A0A2A2MCP3 F
B1Y6V4 F
A0A1G6ABK5 F
A0A6A1TYJ4 F
A0A2T4UWF1 F
V4AP67 F
A0A173R3W6 F
C7NND3 F
B0DFJ4 F
A0A3E2VY88 F
R1EDV9 F
J1L5M8 F
D7G265 F
Q8ERT9 F
I4D6Z9 F
A0A4R6DFU8 F
A0A060URC3 F
D2BIB2 F
F5ISF6 F
A5CRL2 F
A0A6G9XJV9 F
Q59UP8 F
A0A6N4SPH9 F
I0HGY4 F
X5DX97 F
L1J6I4 F
I1DSU5 F
B9L7N1 F
Q1Z4I4 F
Q21CP1 F
A0A165MFD1 F
V4CRP5 F
Q7S5K0 F
A0A071MMV1 F
A0A149RYW7 F
A0A7G5EC77 F
A0A1W2GZ82 F
A0A7U3XVQ4 F
A0A071M4L5 F
U5C2K4 F
A0A248LNW8 F
L8H844 F
A0A149V596 F
S9QZ09 F
B1ZSW9 F
D2BUJ8 F
A0A9Q8L398 F
M5S735 F
Q6ARH0 F
K6W5X0 F
G0JRG6 F
A0A6H9FYW4 F
A0A0S4WFM4 F
A0A101HKN9 F
Q9REX3 F
F0S3Z6 F
A8NAG3 F
C6LBD3 F
A0A149U2G9 F
V4REY8 F
A0A0H3H4I7 F
A8N2H6 F
S0APH6 F
A0A017SYR8 F
A0A1B9MZ78 F
E4T3F3 F
D7E934 F
A0A0M3AB44 F
A9WHW6 F
A0A5M4AUM9 F
A0A1X4GBG2 F
I4D1H5 F
A0A0E3QYF3 F
B0CQX4 F
A0A378YR15 F
A0A495D4X4 F
A0A076PL76 F
Q1YDY7 F
A0A3E2UCG9 F
A0A2K3DPU7 F
A0A3R9Q7C4 F
V5U2Z4 F
K9P718 F
M1V7W3 F
Q6LKC8 F
E5Y789 F
J9Z839 F
A0A1G7VM92 F
K9Z0D3 F
A0A482TED1 F
R1EGK6 F
J1ASR8 F
A0A7U4E420 F
K9YR86 F
A8PXT8 F
A0A0U1NJW3 F
B8FL88 F
A2CCK1 F
D6TFE1 F
A0A2H4U5R1 F
I2GD40 F
A0A060HFT5 F
B1Y842 F
A0A0X8NXA9 F
A0A0A2A5X1 F
A0A318FY98 F
Q7V4T8 F
A0A1A0DHK0 F
C1A872 F
A0A395VB65 F
A7MFK3 F
J4KM12 F
A1SY01 F
A0A1H4DJ49 F
A0A9R0NTP8 F
A3PAY4 F
B4CV94 F
A2C095 F
Q2HD43 F
A0A836M2B6 F
H6RWK9 F
A0A087EQK8 F
A0A1I0AQM4 F
L7CG11 F
A0A248LNK5 F
B7FTM9 F
L0K9M1 F
I4D6Z7 F
A0A2K1RA81 F
Q2WBF7 F
A0A1B9BUU6 F
A0A2S0JW39 F
A0A2S5YID7 F
B3PIH2 F
U3P8G1 F
C9R9J0 F
A8AC17 F
F0YLV7 F
A0A1D3GAE9 F
C1MHX0 F
A0A1H4KAQ7 F
A0A2T4XZC1 F
A1B3N0 F
C7LW87 F
A1SZ12 F
A0A2T2Y0D5 F
A0A1H8D0R8 F
A0A2S5V2F6 F
G3IYW2 F
F5L8M7 F
C7BJG7 F
E4U5Z1 F
A0A1B9K8L2 F
A0A2S5WMT7 F
A0A0D2UPA8 F
A0A161SKF4 F
B4D7W2 F
A0A1H3WA00 F
C1D6X6 F
A0A4D6KHD1 F
Q488X2 F
A9V5W4 F
A0A5M4ATH9 F
E4TRS4 F
A0A011U1K7 F
C7R314 F
A0A077EFU9 F
A0A0A2A0Y9 F
A0A0D8BQX6 F
A0A0L0S493 F
A0A328Q6M1 F
A0A016XCG9 F
B7FSA7 F
G0AFH4 F
A0A177W826 F
A0A2S8GF54 F
Q1YDY8 F
Q5QVH2 F
A3ZT81 F
A0AA35XZV0 F
F4H924 F
K0NJH2 F
A0A1V3SSW1 F
F2AUF4 F
A6DN47 F
W8KM07 F
A0A1X3RP39 F
A0A7S0KKL8 F
A0A318QZ80 F
K8VZC6 F
A0A1B9JZS5 F
A0A2S6GKN5 F
A0A4R2Z2K6 F
H1YCC3 F
E1QIU3 F
A0A8H6MPB9 F
A0A369N7Y3 F
T2IEJ2 F
H5UND3 F
Q1PX09 F
A0A149TSA9 F
F2NGJ8 F
A0A0E3SHQ9 F
Q5FLR6 F
S0EUS1 F
A0A369M386 F
W0DZS7 F
A8MCL4 F
V3ZVE4 F
O26757 F
A0A317FZW2 F
A0A085GI50 F
A1ZGK6 F
G0IYI2 F
A7S731 F
A0A1U9YY82 F
A0A328EMN2 F
A0A8E2UDJ3 F
A0A2S5WUP6 F
A0A8H7P8U1 F
A0A257T7G4 F
B3MX93 F
A0A1G5W0P2 F
D4H2Y7 F
A0A4P8HC89 F
Q7T070 F
F7NPQ3 F
B9SA70 F
Q9M6N7 F
I7ZHW3 F
F4XTK4 F
A4G1J2 F
G7WFX4 F
B8JBH5 F
D9QPC8 F
A0A4R7GKA0 F
R9PMC6 F
A0A0E3LMT4 F
A0A511NGC7 F
E4NS62 F
E4T3F7 F
M0D580 F
J7J5E7 F
B1XZU2 F
A0A366IE34 F
A0A6U2BIY7 F
Q9QXP0 F
A0A424WAH3 F
A0A410K1J5 F
L1IHZ8 F
I8TC71 F
A0A7U8C744 F
A8M670 F
A0A0S4VNK2 F
Q2SIR0 F
A0A5C4RNH5 F
A0A3E0X011 F
A0A0E3SP24 F
E1IF27 F
Q2YBP7 F
A0A2S5WZU0 F
A0A172YBR4 F
A0A0K2STK6 F
A0A2N6JV02 F
F0S0G1 F
A0A1C7EL50 F
Q18PF5 F
A0A1I0C958 F
A0AA35XVN2 F
L8GGA0 F
Q3AP28 F
D0MFE9 F
J9VXX9 F
A0A166IS52 F
F0J7D3 F
W7QG13 F
A4BMY5 F
A6LV49 F
Q1H483 F
A6M3G0 F
E4T0A4 F
A0A3E2UHE6 F
A0A174SD65 F
A0A855EH99 F
C3YB74 F
A0A074KZD8 F
J0S2I0 F
K9WSX4 F
E8RLT5 F
Q2FS34 F
Q3Z7F9 F
Q2S8H9 F
A0A060HN92 F
E6ME92 F
A0A172RYW3 F
L0FU80 F
C8WZE0 F
A0A2S8F4W0 F
A0A2C6C0X3 F
F3ZVV4 F
A0A7R6PER3 F
A0A495WJM6 F
A0A0B4DUR9 F
A0A251YU48 F
A5D4I5 F
A0A2X2C038 F
A0A2A2M8K7 F
D3FBG3 F
A0A2V4EA49 F
D0MFE8 F
Q3B6Q2 F
A0A1B9KID3 F
A0A9J9ES23 F
A0A3N2SFS2 F
Q0VLH1 F
A0A1U9Z147 F
Q0G2T1 F
A6GJF5 F
A0A059XXR1 F
A0A5J6WPP9 F
P41948 F
L1IUV5 F
A0A2W0GQV0 F
Q1K433 F
A0A4Y7XC43 F
D5AU98 F
E1QFA8 F
A0A075WBP9 F
Q0BWD0 F
A0A1Y0HX98 F
A0A098S5Y7 F
Q0I445 F
A0A1E5BXA4 F
A0A2C9CK98 F
G4H971 F
A0A1I0BYN1 F
A0A330GB00 F
A0A2S8FR08 F
Q84KJ6 F
A0A2S5WGI8 F
M2ALH9 F
A0A2K3DQF8 F
A0A8G2IZM3 F
F5Y3C1 F
A0A370FPU0 F
F5RGM7 F
A0A4R4K1P9 F
R8VWI7 F
A0A0A2AMW2 F
Q7Z1M1 F
A0A414NWT8 F
A0A0P6VSR8 F
A0A0L0TDW1 F
U3PCH5 L
W7QGE0 F
C5BWX7 F
A0A1B9M1A9 F
B8GGC3 F
D6SPD1 F
A0A0H3DR67 F
A0A4R7VEK0 F
G4R7P1 F
A0A1M5ZVP9 F
A0A2S5Y0D3 F
I0ICG0 F
D0L8H3 F
A0A1B9LFW3 F
Q6ND34 F
A0A6H9GWG4 F
Q5UZ98 F
A0A2S0P9T4 F
H2CDR5 F
T2KGT3 F
A0A088E6Q7 F
A0A258HS77 F
E1V4T3 F
B7GKP4 F
Q9QUT0 F
I3Z3H7 F
G7WCB6 F
A0A1Y6GLJ1 F
A0A0S2DQB6 F
Q6CRN1 F
A0A401X433 F
A7HT14 F
A0A009TDB1 F
D4XSW0 F
B0SRS8 F
A0A149QSR6 F
B1Y0E5 F
Q7UGU7 F
A0A2S0Q8P1 F
F0ZPL3 Y
A0A2T0GTU1 F
I4CCD1 F
A0A9Q6P4A5 F
A0A418VIJ8 F
C1MX19 F
A0A1B9BUZ8 F
K9W6F3 F
Q1K8A3 F
L8GFX3 F
A0A1G6ABL9 F
A0A087L0B9 F
A0A073CP02 F
A0A0A1ZJU5 F
A0A258HPP1 F
A0A149QAW7 F
D2V6Q5 F
A0A1X4G8K1 F
A0A067Z3S3 F
A0A8F5ZDT8 F
A0A854QN45 F
A0A2N7LCD7 F
G7WFX2 F
A0A7S4GNJ2 F
A4G0C5 F
A6VE60 F
A0A1S1HM83 F
A0A037ZJY5 F
N1WR17 F
Q2W5V2 F
A1VIM5 F
A0A1Y5E3E3 F
A0A1T4SFK4 F
A7RNC3 F
M7XJ51 F
A0A399T909 F
A0A2N6P374 F
H8L2Q4 F
D5EP68 F
E6SF19 F
A0A1T4SFY6 F
D3LBI0 F
E6W5C1 F
Q0VPH4 F
K9WT03 F
L0KW14 F
A0A4R8H081 F
A0A1B9N3H7 F
B0RC35 F
A0A420KGW4 F
A0A4R3NLV5 F
Q47K18 F
Q21P82 F
M1WRK6 F
A0A290XBB5 F
A0A6T9XUR2 F
A0A1J1JH03 F
I3R0S7 F
A9UR54 F
A0A1G7H8X3 F
A0A8G2F718 F
Q1H0G2 F
D0LAL7 F
C7LQR9 F
A0A1G5PWV0 F
K1K628 F
B9SXC7 F
G7WA28 F
Q1IWN6 F
H6LKH9 F
A0A1H7CU41 F
G8JUJ2 F
A0A081N2G5 F
A0A074ME37 F
Q0VQH6 F
C8XB51 F
A1VIG8 F
Q8GQS1 F
A0A1I7FBM5 F
A0A1M6ZMI3 F
A0A482PLH3 F
A0RXK8 F
D0KXQ0 F
Q8JI14 F
A0A7T4WEP4 F
A0A4R3ZNW3 F
A0A074KY88 F
A0A6M3ZKU5 F
M1SJL5 F
A0A1W9KSU5 F
E3GI40 F
A0A369NYJ2 F
A0AA92K392 F
O04161 F
A9BQZ4 F
A0A6N2Z556 F
A0A8H6NAG3 F
A0A2T9X1V4 F
Q2J376 F
A0A0F5EZP7 F
A0A7G5DK18 F
M9YAI9 F
D2ZRW2 F
G7UUY6 F
A0A8H4GS02 F
A0A2T5IHP0 F
A0A165MAC2 F
A0A7S4LPS8 F
A0A075JIN0 F
C8X554 F
B8FZP7 F
Q5KAF6 F
A0A427KNL6 F
A0A7G5DPV0 F
Q22947 F
A0A1S1HRJ0 F
A0A3N1VXY4 F
A0A2S7YPJ9 F
I0JI83 F
A0A7U3YMN6 F
Q9BLG3 F
A0A1H9RTW8 F
A0A1I4W3A0 F
A0A0B4M163 F
U2EN72 F
A0A2W5VAZ2 F
E4YA63 F
D5ELM4 F
M9RJS5 F
A0A2G3E8V2 F
Q5FSX6 F
I0HKQ8 F
A0A833H2R7 F
B8ENL9 F
B3DUX7 F
A0A1D8UWJ6 F
D5E995 F
A0A7U8C2Y6 F
L0KGR8 F
B0VMH1 F
P40260 F
L0JT30 F
C1GR74 F
A0A423Y4I6 F
A0A4P7UHQ5 F
A0A8E2R1Y5 F
I5BYV5 F
A0A6B8N021 F
A0A7G5DPV1 F
A0A2G5RQK9 F
A0A5M4B0G1 F
A0A6S5K4J1 F
C1D4X0 F
A1SVA8 F
H1YF74 F
A0A8B4RWH8 F
A0A0A0D6K5 F
A0A0A2BBY0 F
A0A089ZBW5 F
A0A068TC78 F
Q46G49 F
A1CQ21 F
A0A1G6ABX1 F
E1SLM7 F
K5CFE5 F
Q2YLQ6 F
Q0G2V0 F
A4ABK3 F
A0A9Q5QVI9 F
A0A4Q7Y9I7 F
A9HMD6 F
K9YN27 F
Q9UBD6 F
D9SI59 F
Q8I0L6 F
A0A142VAD6 F
G3IYW0 F
A0A062IU58 F
R1D1H4 F
A0A366XFS8 F
A0A7S4GNF3 F
F0J6E8 F
A0A7U4DN04 F
V4RHR4 F
F7ZJM0 F
A0A2S5XAB8 F
U5C4L4 F
Q21J04 F
A0A142NNN1 F
H1Y7T6 F
F5R974 F
B0DU91 F
A2BP62 F
A7HSN9 F
A0A377I7W9 F
D2RU19 F
G7WJN0 F
E2SD33 F
A0A0D7F2Y9 F
A0AA92EGF5 F
A0A9E9LXV9 F
A4BEP1 F
A0A0E3WZH5 F
F7ZEU9 F
A5E3X2 F
A0A0A3XTJ3 F
A0A830ZZN8 F
A0A1S8D478 F
J7IVQ1 F
A0A2U1SS17 F
S3K1S2 F
C6XKC2 F
A0A2S7YIM5 F
K2IMJ7 F
Q5P1S8 F
A0A7T5BFQ2 F
A0A556SRH6 F
A8P923 F
A0A7G5DKA9 F
L8JUH3 F
A0A0D2LEF5 F
A0A258FTB0 F
A0A5P9P1L2 F
M8E0R3 F
A0A6J5IRX5 F
W5WIX6 F
Q82X47 F
I4DBY0 F
A0A6F8TLE9 F
A0A1G7UZX2 F
A0A6P4JM51 F
G0J614 F
U2WTW8 F
A0A642KQG8 F
Q1AUG3 F
A0A6G9Y3Q0 F
B8J5X4 F
M7NFH3 F
A0A0E3R6S1 F
Q2IHY5 F
A7I8Z2 F
L1IYP4 F
B4HDZ9 F
A0A366WYI9 F
E4TJ50 F
A0A7S0ILH2 F
A4BAE1 F
B3QRJ4 F
A0A5C5BWI6 F
Q7NQY2 F
A0A091AXI3 F
Q1QSQ2 F
R4FZE3 F
A0A2N0MZ27 F
A9BTK1 F
A0A242NIL1 F
G0LFE3 F
A0A1B9NQ91 F
A0A5M5PZE2 F
A0A0D2NYP3 F
D9QPE5 F
I5B3H0 F
L1IYW7 F
C6WEW7 F
B7FW68 F
F4GED5 F
A0A4R8GSH7 F
A0A1W2H3F0 F
A0A3E2T713 F
A0A0H3KTD3 F
A0A1Y4LM49 F
G2PRJ6 F
A0A0X8X7Y7 F
K8EJ02 F
A0A1L3F1X5 F
G8TK77 F
A0A855F5Y8 F
A0A975BTN0 F
A0A562RGZ4 F
G5EB09 F
A0A833LX85 F
U1H1F7 F
K8W1E2 F
E3HJW8 F
Q7SEH0 F
Q47X17 F
B0DXT9 F
A0A3G9G2C9 F
Q95P70 F
A0A837C6X5 F
Q89WR5 F
A6DUG4 F
D7UQE2 F
A0A2I1M481 F
A0A0T7GZ59 F
O66395 F
J3EXK0 F
A0A1B9MYL7 F
K9U8C7 F
E2SD44 F
H6LKH6 F
Q605Y6 F
A0A9Q9D9I3 F
A0A6N2TIA4 F
A0A1E3PQH0 F
A4CMI3 F
Q1K0H9 F
A0A0S6UEK9 F
A0A0H3LUA3 F
B9LU00 F
A9BIZ7 F
A0A7H8UK07 F
E3H8C9 F
M2A398 F
Q1QS12 F
G0VI62 F
A0A1Z3MS36 F
A0A0B5FNH4 F
D9SI36 F
A0A410JZR4 F
F7ZJZ1 F
F0ZCX7 F
W0DZX1 F
A0A4R3ZZ35 F
A0A317G0I6 F
Q0ARJ4 F
A7I8Z4 F
T2KJ59 F
I3C0V3 F
E3H8A6 F
B2IJT1 F
A0A2G6JLT9 F
A3ZZL7 F
A0A2T0XPP2 F
Q31CR9 F
A0A1R1IDV3 F
K2JVF8 F
V5BYZ7 F
D8J4C6 F
D4H5F9 F
K9ZG59 F
A0AA86YS65 F
Q608B6 F
A0A562BXM4 F
A0A401WXG0 F
A0A857DMN9 F
A0A1X6N3Q5 F
A0A173R3X4 F
Q63EK5 F
K9ZLY2 F
A0A533I6R2 F
I0WJ97 F
K0N2R5 F
M0J579 F
B8GGC1 F
A0A6H9GFU4 F
C6CBB1 F
A0A510HHK8 F
A0A1B9MBX6 F
A0A9Y2AG30 F
E8RSE4 F
F2B2B8 F
Q7UYZ3 F
I1YJH7 F
A0A853MG28 F
A0A0L0STS6 F
A0A251XU71 F
Q60BI2 F
A0A829X098 F
F3KUN4 F
Q60C43 F
A0A0T7FAP8 F
A0A3E2TW06 F
W0E077 F
A0KPE9 F
R7PZ71 F
A0A0A1ZMZ9 F
A0AA40J491 F
D3S2L0 F
A0A373FQ71 F
A0A0A2C6L1 F
Q7W7D3 F
A0A165K0X5 F
A0A2S5X482 F
R9GM11 F
Q0G0A3 F
D4GLQ6 F
E7RJZ0 F
F8IJE0 F
A0A1V2XMU9 F
Q7TNN9 F
A0A1G5RZU9 F
A0A2N6K4Y5 F
B0SLB7 F
A0A251YFS0 F
B9WDK0 F
Q7N0M6 F
A0A0M2LU39 F
F4B548 F
D6Z5V9 F
A0A4R2M206 F
A0A1E2SKM1 L
A0A127JTU2 F
A0A212AV03 F
G4QHD2 F
A0A021VMC6 F
A0A2J7TJ33 F
G7WDB5 F
Q6BK68 M
Q1K3N8 F
A0AA91Q161 F
A0NJ07 F
A0A316BQ38 F
A0A377PLP5 F
W7QGM4 F
A0A015YIP3 F
A0A060UWC8 F
A0A1I4ZIZ6 F
A0A264VQM8 F
A9AUR8 F
A0A1W5PRD1 F
A0A0E3BR91 F
A0A1B0ZRL8 F
B9ACS5 F
Q92BJ7 F
F2JTN3 F
A1AVV2 F
D2Q0J8 F
A0A3S9N9F3 F
A8ZQD5 F
C3X831 F
A0A1M6BPM0 F
A0A8F5VN39 F
A0A1E5C7W4 F
A0A2S5WV24 F
A0A833GZR2 F
C7M2A9 F
A6W7U2 F
W0JIB3 F
Q07UM3 F
A0A066ZRQ5 F
S0G181 F
D3PAH1 F
Q4WHC6 F
A0AA94HTL8 F
D5ASL9 F
A0A4U1JNL6 F
M0MDP9 F
A0A653N397 F
A0A2S8GSU9 F
A0A097R891 F
A0A8H7U3I1 F
A0A1H1MB73 F
A0A016XDZ5 F
A0A1B9JHS5 F
D3PE53 F
A0A9J9BAE8 F
Q2RM12 F
A0A3N0AQL8 F
C5KTM6 F
M1P5F0 F
I1YG38 F
A0A660CH85 F
A0A2N7L7C8 F
Q5KZZ9 F
M1NZT5 F
A0A225CMT8 F
A0A068NV61 F
H2CJI0 F
B0DU93 F
Q221S8 F
F4Y3C5 F
Q94CJ2 F
M0D3Q9 F
A0A3P2A7W8 F
C0GKN4 F
Q7T3R4 F
A0A562USB9 F
A2SS52 F
A0A211ZGL5 F
A0A4V3ALP8 F
A0A147GP06 F
H2IZ00 F
Q45HK8 F
A0A6C8LST1 F
A0A257T8W6 F
Q5P470 F
I5AZQ4 F
Q07UM1 F
E5B358 F
A0A1Y4L5P0 F
Q3AFY9 F
B0BZN3 F
A0A1Q2C7H7 F
A0A4R5U5V1 F
H6LKX6 F
A0A1Y0UZX2 F
F6BEI0 F
M9RKT6 F
A7SGD4 F
A0A257TE48 F
R1FI09 F
E4N1T5 F
U1PIR6 F
F2JYR9 F
Q84KJ7 F
A0A2S8FTB5 F
D2R647 F
G9Y5B0 F
A0A144NLT9 F
A0A5J6WQU1 F
D2R355 F
F3ZYD6 F
B0SL05 F
A0A5A7MAJ9 F
A0A977NL43 F
A0A433ZQ80 F
A0A1Y0V4A5 F
A0A1M7UEG2 F
G8R7U9 F
K1LDP0 F
B7G0Y4 F
A0A2W4ZXC0 F
B3PF77 F
Q2KZK9 F
Q18ES8 F
D3F545 F
B4S394 F
Q1Q357 F
Q9H310 F
D3PKL4 F
M5SY07 F
Q8RUT6 F
A7NKH2 F
Q1Q879 F
A0A1B9M5B8 F
A6LRS5 F
J2ZGN6 F
V5E0F3 F
A0A149RQX0 F
A0A165BP25 F
C0QSY0 F
B0XVV6 F
E0SD83 F
A8HSA2 F
A0A1E3PSK5 F
A5DYQ2 F
A0A4U1K1W1 F
Q0AT01 F
A4FMG0 F
C3YB73 F
A0A9P3CXY2 F
A0A0L8BVU4 F
A0A401WUW1 F
I4C9L2 F
Q8RUE9 F
F0JGZ1 F
A0A2I0UUY1 F
A0A542XGT4 F
G0JRH4 F
A2SPS8 F
A0A5M4AWD2 F
Q6QH01 F
D3F0Z1 F
A6XBM2 F
D6E7B3 F
Q13E03 F
A0A060URB8 F
A0A2T1N7R1 F
D6TCH6 F
B0CXH8 F
A3TVQ9 F
Q4WT12 F
C7QGX3 F
F0Y9X3 F
A0A7S0D560 F
A0A160KTE9 F
A0A2H1HV86 F
A0A251Y3N4 F
A0A419AVL2 F
A0A4Q2QWS1 F
C7Q1E4 F
A0A5C5TYS5 F
F2NNQ0 F
A0A2R4TRE0 F
K9YJQ3 F
D9QS43 F
A7SQ16 F
A1DG05 F
U1SIR9 F
C4Y298 F
A0A9W3LFI9 F
D3RMV7 F
F3QNA7 F
E4RTK5 F
C8XBX8 F
C0QTA4 F
E6VIW4 F
A0A2S6H643 F
Q46HB1 F
A0A2S5CTX8 F
A0A1T4SF40 F
K0K7J4 F
A0A1J5JH24 F
Q6LMI6 F
A0A9W5JBA9 F
A0A291PMC6 F
A0A4Y4DZN4 F
A0A2R4MBA2 F
R9PI53 F
A0A6H9GLV4 F
A0A7S4GND2 F
A0A6H9FPY5 F
A0A1G7DX68 F
A0A075WEB4 F
A0A140NHJ5 F
A0A1C6Z081 F
Q5FA36 F
Q0ACK1 F
A0A975GIX9 F
A0A323UE08 F
U7VB41 F
A0A063Y780 F
C5CIT6 F
A0A0A2VPU3 F
F0RHS0 F
A0A2S5WX34 F
C1G973 F
A0A2S6GKF6 F
A0A0A2B651 F
A0A4R3A5P7 F
A0A2A7U6W1 F
Q2GX26 F
F5XN43 F
A0A0K2STH0 F
A0A1H1U2Q6 F
A7SED8 F
A0LV78 F
K5DBA0 F
B8IZX4 F
A8LKQ0 F
A0A5C6LWQ1 F

In [94]:
seqf2 = []

for i in f2:
    print(i.id, i.seq)
    seqf2.append(i.seq)

A0A858ZNJ3 F
A0A1H9M798 F
B0DY50 F
P69680 F
A0A3G9G4Q4 F
A0A149UP06 F
F2G6G4 F
A0A2M9D7S8 F
A0A034WGQ2 F
I0KDC6 F
F8D7H6 F
K9W4V5 F
Q466Y3 F
D2SE15 F
A0A377PBY1 F
B1JZ69 F
A0A2W5HTC3 F
A8G2S3 F
D5T4N9 F
Q2RWY7 L
A0A0E3R4G0 F
I4C9L0 F
D5VJ32 F
C0Z5S5 F
C1N6X9 F
J7ITF6 F
A0A068SVR1 F
A0A0D7F328 F
Q0G0A4 F
F0J3F9 F
Q0BQ69 F
F2YIC4 F
D4XLN6 F
A0A420WC79 F
A0A5C5TUT2 F
A0RUZ2 F
A0A0A2ZRL7 F
J4UGB7 F
E5Y678 F
A0A0D2KGN8 F
S5ABR8 F
A9DQM8 F
G5EB13 F
A0A2N6NEK4 F
C6DB68 F
Q81GN5 F
Q0F2M5 F
A0A0C6P439 F
B9SWW9 F
L8H5K0 F
Q9NIV0 F
C1N5A7 F
Q1JXS5 F
A0A1M6JKY3 F
F4D1J0 F
A0A257SYX3 F
V4RK08 F
G0V8D6 F
A0A7S4GMD8 F
B3QVV5 F
F2JZ83 F
A0A857DDJ7 F
A0A0S6UHP2 F
D5EP71 F
F4KY49 F
M5S9B4 F
A0A009PYN3 F
A0A3T0SZ22 F
A0A248LMH8 F
A0A6H9GEE4 F
A7HSP2 F
A0A7V8IKS6 F
T2JFS5 F
F6FRU9 F
A0A9E9L9J1 F
A0AIW5 F
A0A0E9NHV4 F
Q2N625 F
C8WSI9 F
A0A1H1BPD6 F
A0A176XNC5 F
A0A4V0XUI3 F
A7S3L2 F
M5U2P1 F
K9P5D1 F
Q0F2M7 F
A0A2R3IMJ8 F
Q2RVB5 F
A0A556RTU3 F
E0TGP9 F
B7G0Y1 F
A0A1G9P6Q0 F
D0LTW3 F
Q6BT62 F
Q2IK04 F
Q6BJI7 F
B7X047 F
A0A068NPW2 F
A0A399NT81 F
K0F9X7 F
A0A037ZMW1 F
A0A075JZ35 F
A0A369MHK2 F
A0A1B9JPL5 F
D8PD01 F
A0A2G5BI87 F
A0A2G5BGA9 F
A0A657K391 F
P69681 F
A0A4P6UIJ8 F
A0A0V8M0W6 F
A0A0H2XSU4 F
Q1Z695 F
A0A7Z0V0A4 F
K0ER80 F
A0A149UWF2 F
G0H0Z6 F
G0EFF3 F
C8WLL8 F
X5CNT2 F
A0A4Y1MSE7 F
H2CLF7 F
M4VEJ9 F
A0A4V2X6C2 F
A0A2K1RA77 F
A0A375YPN6 F
A0A7M6UUM4 F
A0A172YCA7 F
A0A918MJ52 F
A0A2S8QA29 F
A0A251XJT0 F
A0A0B4E6X7 F
A0A0K2STQ7 F
A1C5Z7 F
C9KKP2 F
A0A2Z4MD56 F
Q9VFA9 F
A0A502GPV4 F
I5C044 F
D2V6P8 F
D3RN22 F
Q97L80 F
A0A0D5YN10 F
A0A1I5GN22 F
A0A1Y5E8I7 F
B1Y8C9 F
M5SYZ1 F
Q6HM26 F
A0A379A0S9 F
A0A101DCS3 F
A0A1Y3U5V2 F
A0A202B535 F
F8E6R1 F
Q6ND36 F
A0A8H6K7L7 F
Q7NCB8 F
A0A369MRW6 F
C9RS76 F
A3U857 F
A0A127PIQ9 F
B8FGW0 F
A0A060JMP6 F
D5V7B3 F
A0A494JB70 F
A0A5M8QF12 F
A0A8G2F3G4 F
J7L3W8 F
G0JRG9 F
D3DJN2 F
A0A1Y2JH43 F
Q1L727 F
A0A7T2S0Z6 F
A0A315S845 F
A0A2S6H6B7 F
A0A1J5NTP7 F
A0A0E3QY86 F
A0A096EEV9 F
A0A380S5X4 F
B8ZYW3 F
A0A2S8GEJ5 F
A0A248TDF2 F
B2GFN1 F
U1PPI7 F
C7LW88 F
G3A431 F
A0A066ZTE4 F
L7CG99 F
S0ET45 F
A0A178TA08 F
H1XV27 F
A0A6M3ZJI1 F
U5DEY6 F
H6LFQ2 F
Q6CRN0 F
A0A4Q2EAG7 F
A0A1J5NNB8 F
E3I393 F
A0A243SC06 F
D4F313 F
W0F0I7 F
A9B874 F
A1D2Y5 F
T2J0N1 F
Q2FQT3 F
A0A075WG29 F
A0A979GQ79 F
A0A381CAY8 F
A0A2G3DSU6 F
A0A168EVK8 F
A0A094W9G3 F
A0A4R3NVT3 F
W0DYY3 F
G8JTW0 F
A0A4P6UIK6 F
I9P003 F
G2T1Y3 F
B8EMQ8 F
I6Z905 F
E0TCV4 F
A3XNG6 F
A0A087MGU4 F
A2BUP4 F
A0A562S8V2 F
A0A495DND0 F
A0A0S2FHD7 F
F3QPR6 F
A0A063Y394 F
F6G5I9 F
A0A323UDG5 F
A0A0G9HEC5 F
B8FDY8 F
Q5KPM5 F
A0A147EQL9 F
A0A854Q6X9 F
C3X1J1 F
A0A5B2V3B9 F
A0A258FS85 F
A0A7T2W1B3 F
A0A060UN76 F
G0JRQ3 F
D5UD26 F
G2ZN72 F
A0AA46Q839 F
A5UJR1 F
L1INN6 F
C1F584 F
C5LAG4 F
A0A2A2MCP3 F
B1Y6V4 F
A0A1G6ABK5 F
A0A6A1TYJ4 F
A0A2T4UWF1 F
V4AP67 F
A0A173R3W6 F
C7NND3 F
B0DFJ4 F
A0A3E2VY88 F
R1EDV9 F
J1L5M8 F
D7G265 F
Q8ERT9 F
I4D6Z9 F
A0A4R6DFU8 F
A0A060URC3 F
D2BIB2 F
F5ISF6 F
A5CRL2 F
A0A6G9XJV9 F
Q59UP8 F
A0A6N4SPH9 F
I0HGY4 F
X5DX97 F
L1J6I4 F
I1DSU5 F
B9L7N1 F
Q1Z4I4 F
Q21CP1 F
A0A165MFD1 F
V4CRP5 F
Q7S5K0 F
A0A071MMV1 F
A0A149RYW7 F
A0A7G5EC77 F
A0A1W2GZ82 F
A0A7U3XVQ4 F
A0A071M4L5 F
U5C2K4 F
A0A248LNW8 F
L8H844 F
A0A149V596 F
S9QZ09 F
B1ZSW9 F
D2BUJ8 F
A0A9Q8L398 F
M5S735 F
Q6ARH0 F
K6W5X0 F
G0JRG6 F
A0A6H9FYW4 F
A0A0S4WFM4 F
A0A101HKN9 F
Q9REX3 F
F0S3Z6 F
A8NAG3 F
C6LBD3 F
A0A149U2G9 F
V4REY8 F
A0A0H3H4I7 F
A8N2H6 F
S0APH6 F
A0A017SYR8 F
A0A1B9MZ78 F
E4T3F3 F
D7E934 F
A0A0M3AB44 F
A9WHW6 F
A0A5M4AUM9 F
A0A1X4GBG2 F
I4D1H5 F
A0A0E3QYF3 F
B0CQX4 F
A0A378YR15 F
A0A495D4X4 F
A0A076PL76 F
Q1YDY7 F
A0A3E2UCG9 F
A0A2K3DPU7 F
A0A3R9Q7C4 F
V5U2Z4 F
K9P718 F
M1V7W3 F
Q6LKC8 F
E5Y789 F
J9Z839 F
A0A1G7VM92 F
K9Z0D3 F
A0A482TED1 F
R1EGK6 F
J1ASR8 F
A0A7U4E420 F
K9YR86 F
A8PXT8 F
A0A0U1NJW3 F
B8FL88 F
A2CCK1 F
D6TFE1 F
A0A2H4U5R1 F
I2GD40 F
A0A060HFT5 F
B1Y842 F
A0A0X8NXA9 F
A0A0A2A5X1 F
A0A318FY98 F
Q7V4T8 F
A0A1A0DHK0 F
C1A872 F
A0A395VB65 F
A7MFK3 F
J4KM12 F
A1SY01 F
A0A1H4DJ49 F
A0A9R0NTP8 F
A3PAY4 F
B4CV94 F
A2C095 F
Q2HD43 F
A0A836M2B6 F
H6RWK9 F
A0A087EQK8 F
A0A1I0AQM4 F
L7CG11 F
A0A248LNK5 F
B7FTM9 F
L0K9M1 F
I4D6Z7 F
A0A2K1RA81 F
Q2WBF7 F
A0A1B9BUU6 F
A0A2S0JW39 F
A0A2S5YID7 F
B3PIH2 F
U3P8G1 F
C9R9J0 F
A8AC17 F
F0YLV7 F
A0A1D3GAE9 F
C1MHX0 F
A0A1H4KAQ7 F
A0A2T4XZC1 F
A1B3N0 F
C7LW87 F
A1SZ12 F
A0A2T2Y0D5 F
A0A1H8D0R8 F
A0A2S5V2F6 F
G3IYW2 F
F5L8M7 F
C7BJG7 F
E4U5Z1 F
A0A1B9K8L2 F
A0A2S5WMT7 F
A0A0D2UPA8 F
A0A161SKF4 F
B4D7W2 F
A0A1H3WA00 F
C1D6X6 F
A0A4D6KHD1 F
Q488X2 F
A9V5W4 F
A0A5M4ATH9 F
E4TRS4 F
A0A011U1K7 F
C7R314 F
A0A077EFU9 F
A0A0A2A0Y9 F
A0A0D8BQX6 F
A0A0L0S493 F
A0A328Q6M1 F
A0A016XCG9 F
B7FSA7 F
G0AFH4 F
A0A177W826 F
A0A2S8GF54 F
Q1YDY8 F
Q5QVH2 F
A3ZT81 F
A0AA35XZV0 F
F4H924 F
K0NJH2 F
A0A1V3SSW1 F
F2AUF4 F
A6DN47 F
W8KM07 F
A0A1X3RP39 F
A0A7S0KKL8 F
A0A318QZ80 F
K8VZC6 F
A0A1B9JZS5 F
A0A2S6GKN5 F
A0A4R2Z2K6 F
H1YCC3 F
E1QIU3 F
A0A8H6MPB9 F
A0A369N7Y3 F
T2IEJ2 F
H5UND3 F
Q1PX09 F
A0A149TSA9 F
F2NGJ8 F
A0A0E3SHQ9 F
Q5FLR6 F
S0EUS1 F
A0A369M386 F
W0DZS7 F
A8MCL4 F
V3ZVE4 F
O26757 F
A0A317FZW2 F
A0A085GI50 F
A1ZGK6 F
G0IYI2 F
A7S731 F
A0A1U9YY82 F
A0A328EMN2 F
A0A8E2UDJ3 F
A0A2S5WUP6 F
A0A8H7P8U1 F
A0A257T7G4 F
B3MX93 F
A0A1G5W0P2 F
D4H2Y7 F
A0A4P8HC89 F
Q7T070 F
F7NPQ3 F
B9SA70 F
Q9M6N7 F
I7ZHW3 F
F4XTK4 F
A4G1J2 F
G7WFX4 F
B8JBH5 F
D9QPC8 F
A0A4R7GKA0 F
R9PMC6 F
A0A0E3LMT4 F
A0A511NGC7 F
E4NS62 F
E4T3F7 F
M0D580 F
J7J5E7 F
B1XZU2 F
A0A366IE34 F
A0A6U2BIY7 F
Q9QXP0 F
A0A424WAH3 F
A0A410K1J5 F
L1IHZ8 F
I8TC71 F
A0A7U8C744 F
A8M670 F
A0A0S4VNK2 F
Q2SIR0 F
A0A5C4RNH5 F
A0A3E0X011 F
A0A0E3SP24 F
E1IF27 F
Q2YBP7 F
A0A2S5WZU0 F
A0A172YBR4 F
A0A0K2STK6 F
A0A2N6JV02 F
F0S0G1 F
A0A1C7EL50 F
Q18PF5 F
A0A1I0C958 F
A0AA35XVN2 F
L8GGA0 F
Q3AP28 F
D0MFE9 F
J9VXX9 F
A0A166IS52 F
F0J7D3 F
W7QG13 F
A4BMY5 F
A6LV49 F
Q1H483 F
A6M3G0 F
E4T0A4 F
A0A3E2UHE6 F
A0A174SD65 F
A0A855EH99 F
C3YB74 F
A0A074KZD8 F
J0S2I0 F
K9WSX4 F
E8RLT5 F
Q2FS34 F
Q3Z7F9 F
Q2S8H9 F
A0A060HN92 F
E6ME92 F
A0A172RYW3 F
L0FU80 F
C8WZE0 F
A0A2S8F4W0 F
A0A2C6C0X3 F
F3ZVV4 F
A0A7R6PER3 F
A0A495WJM6 F
A0A0B4DUR9 F
A0A251YU48 F
A5D4I5 F
A0A2X2C038 F
A0A2A2M8K7 F
D3FBG3 F
A0A2V4EA49 F
D0MFE8 F
Q3B6Q2 F
A0A1B9KID3 F
A0A9J9ES23 F
A0A3N2SFS2 F
Q0VLH1 F
A0A1U9Z147 F
Q0G2T1 F
A6GJF5 F
A0A059XXR1 F
A0A5J6WPP9 F
P41948 F
L1IUV5 F
A0A2W0GQV0 F
Q1K433 F
A0A4Y7XC43 F
D5AU98 F
E1QFA8 F
A0A075WBP9 F
Q0BWD0 F
A0A1Y0HX98 F
A0A098S5Y7 F
Q0I445 F
A0A1E5BXA4 F
A0A2C9CK98 F
G4H971 F
A0A1I0BYN1 F
A0A330GB00 F
A0A2S8FR08 F
Q84KJ6 F
A0A2S5WGI8 F
M2ALH9 F
A0A2K3DQF8 F
A0A8G2IZM3 F
F5Y3C1 F
A0A370FPU0 F
F5RGM7 F
A0A4R4K1P9 F
R8VWI7 F
A0A0A2AMW2 F
Q7Z1M1 F
A0A414NWT8 F
A0A0P6VSR8 F
A0A0L0TDW1 F
U3PCH5 L
W7QGE0 F
C5BWX7 F
A0A1B9M1A9 F
B8GGC3 F
D6SPD1 F
A0A0H3DR67 F
A0A4R7VEK0 F
G4R7P1 F
A0A1M5ZVP9 F
A0A2S5Y0D3 F
I0ICG0 F
D0L8H3 F
A0A1B9LFW3 F
Q6ND34 F
A0A6H9GWG4 F
Q5UZ98 F
A0A2S0P9T4 F
H2CDR5 F
T2KGT3 F
A0A088E6Q7 F
A0A258HS77 F
E1V4T3 F
B7GKP4 F
Q9QUT0 F
I3Z3H7 F
G7WCB6 F
A0A1Y6GLJ1 F
A0A0S2DQB6 F
Q6CRN1 F
A0A401X433 F
A7HT14 F
A0A009TDB1 F
D4XSW0 F
B0SRS8 F
A0A149QSR6 F
B1Y0E5 F
Q7UGU7 F
A0A2S0Q8P1 F
F0ZPL3 Y
A0A2T0GTU1 F
I4CCD1 F
A0A9Q6P4A5 F
A0A418VIJ8 F
C1MX19 F
A0A1B9BUZ8 F
K9W6F3 F
Q1K8A3 F
L8GFX3 F
A0A1G6ABL9 F
A0A087L0B9 F
A0A073CP02 F
A0A0A1ZJU5 F
A0A258HPP1 F
A0A149QAW7 F
D2V6Q5 F
A0A1X4G8K1 F
A0A067Z3S3 F
A0A8F5ZDT8 F
A0A854QN45 F
A0A2N7LCD7 F
G7WFX2 F
A0A7S4GNJ2 F
A4G0C5 F
A6VE60 F
A0A1S1HM83 F
A0A037ZJY5 F
N1WR17 F
Q2W5V2 F
A1VIM5 F
A0A1Y5E3E3 F
A0A1T4SFK4 F
A7RNC3 F
M7XJ51 F
A0A399T909 F
A0A2N6P374 F
H8L2Q4 F
D5EP68 F
E6SF19 F
A0A1T4SFY6 F
D3LBI0 F
E6W5C1 F
Q0VPH4 F
K9WT03 F
L0KW14 F
A0A4R8H081 F
A0A1B9N3H7 F
B0RC35 F
A0A420KGW4 F
A0A4R3NLV5 F
Q47K18 F
Q21P82 F
M1WRK6 F
A0A290XBB5 F
A0A6T9XUR2 F
A0A1J1JH03 F
I3R0S7 F
A9UR54 F
A0A1G7H8X3 F
A0A8G2F718 F
Q1H0G2 F
D0LAL7 F
C7LQR9 F
A0A1G5PWV0 F
K1K628 F
B9SXC7 F
G7WA28 F
Q1IWN6 F
H6LKH9 F
A0A1H7CU41 F
G8JUJ2 F
A0A081N2G5 F
A0A074ME37 F
Q0VQH6 F
C8XB51 F
A1VIG8 F
Q8GQS1 F
A0A1I7FBM5 F
A0A1M6ZMI3 F
A0A482PLH3 F
A0RXK8 F
D0KXQ0 F
Q8JI14 F
A0A7T4WEP4 F
A0A4R3ZNW3 F
A0A074KY88 F
A0A6M3ZKU5 F
M1SJL5 F
A0A1W9KSU5 F
E3GI40 F
A0A369NYJ2 F
A0AA92K392 F
O04161 F
A9BQZ4 F
A0A6N2Z556 F
A0A8H6NAG3 F
A0A2T9X1V4 F
Q2J376 F
A0A0F5EZP7 F
A0A7G5DK18 F
M9YAI9 F
D2ZRW2 F
G7UUY6 F
A0A8H4GS02 F
A0A2T5IHP0 F
A0A165MAC2 F
A0A7S4LPS8 F
A0A075JIN0 F
C8X554 F
B8FZP7 F
Q5KAF6 F
A0A427KNL6 F
A0A7G5DPV0 F
Q22947 F
A0A1S1HRJ0 F
A0A3N1VXY4 F
A0A2S7YPJ9 F
I0JI83 F
A0A7U3YMN6 F
Q9BLG3 F
A0A1H9RTW8 F
A0A1I4W3A0 F
A0A0B4M163 F
U2EN72 F
A0A2W5VAZ2 F
E4YA63 M
D5ELM4 F
M9RJS5 F
A0A2G3E8V2 F
Q5FSX6 F
I0HKQ8 F
A0A833H2R7 F
B8ENL9 F
B3DUX7 F
A0A1D8UWJ6 F
D5E995 F
A0A7U8C2Y6 F
L0KGR8 F
B0VMH1 F
P40260 F
L0JT30 F
C1GR74 F
A0A423Y4I6 F
A0A4P7UHQ5 F
A0A8E2R1Y5 F
I5BYV5 F
A0A6B8N021 F
A0A7G5DPV1 F
A0A2G5RQK9 F
A0A5M4B0G1 F
A0A6S5K4J1 F
C1D4X0 F
A1SVA8 F
H1YF74 F
A0A8B4RWH8 F
A0A0A0D6K5 F
A0A0A2BBY0 F
A0A089ZBW5 F
A0A068TC78 F
Q46G49 F
A1CQ21 F
A0A1G6ABX1 F
E1SLM7 F
K5CFE5 F
Q2YLQ6 F
Q0G2V0 F
A4ABK3 F
A0A9Q5QVI9 F
A0A4Q7Y9I7 F
A9HMD6 F
K9YN27 F
Q9UBD6 F
D9SI59 F
Q8I0L6 F
A0A142VAD6 F
G3IYW0 F
A0A062IU58 F
R1D1H4 F
A0A366XFS8 F
A0A7S4GNF3 F
F0J6E8 F
A0A7U4DN04 F
V4RHR4 F
F7ZJM0 F
A0A2S5XAB8 F
U5C4L4 F
Q21J04 F
A0A142NNN1 F
H1Y7T6 F
F5R974 F
B0DU91 F
A2BP62 F
A7HSN9 F
A0A377I7W9 F
D2RU19 F
G7WJN0 F
E2SD33 F
A0A0D7F2Y9 F
A0AA92EGF5 F
A0A9E9LXV9 F
A4BEP1 F
A0A0E3WZH5 F
F7ZEU9 F
A5E3X2 F
A0A0A3XTJ3 F
A0A830ZZN8 F
A0A1S8D478 F
J7IVQ1 F
A0A2U1SS17 F
S3K1S2 F
C6XKC2 F
A0A2S7YIM5 F
K2IMJ7 F
Q5P1S8 F
A0A7T5BFQ2 F
A0A556SRH6 F
A8P923 F
A0A7G5DKA9 F
L8JUH3 F
A0A0D2LEF5 F
A0A258FTB0 F
A0A5P9P1L2 F
M8E0R3 F
A0A6J5IRX5 F
W5WIX6 F
Q82X47 F
I4DBY0 F
A0A6F8TLE9 F
A0A1G7UZX2 F
A0A6P4JM51 F
G0J614 F
U2WTW8 F
A0A642KQG8 F
Q1AUG3 F
A0A6G9Y3Q0 F
B8J5X4 F
M7NFH3 F
A0A0E3R6S1 F
Q2IHY5 F
A7I8Z2 F
L1IYP4 F
B4HDZ9 F
A0A366WYI9 F
E4TJ50 F
A0A7S0ILH2 F
A4BAE1 F
B3QRJ4 F
A0A5C5BWI6 F
Q7NQY2 F
A0A091AXI3 F
Q1QSQ2 F
R4FZE3 F
A0A2N0MZ27 F
A9BTK1 F
A0A242NIL1 F
G0LFE3 F
A0A1B9NQ91 F
A0A5M5PZE2 F
A0A0D2NYP3 F
D9QPE5 F
I5B3H0 F
L1IYW7 F
C6WEW7 F
B7FW68 F
F4GED5 F
A0A4R8GSH7 F
A0A1W2H3F0 F
A0A3E2T713 F
A0A0H3KTD3 F
A0A1Y4LM49 F
G2PRJ6 F
A0A0X8X7Y7 F
K8EJ02 F
A0A1L3F1X5 F
G8TK77 F
A0A855F5Y8 F
A0A975BTN0 F
A0A562RGZ4 F
G5EB09 F
A0A833LX85 F
U1H1F7 F
K8W1E2 F
E3HJW8 F
Q7SEH0 F
Q47X17 F
B0DXT9 F
A0A3G9G2C9 F
Q95P70 F
A0A837C6X5 F
Q89WR5 F
A6DUG4 F
D7UQE2 F
A0A2I1M481 F
A0A0T7GZ59 F
O66395 F
J3EXK0 F
A0A1B9MYL7 F
K9U8C7 F
E2SD44 F
H6LKH6 F
Q605Y6 F
A0A9Q9D9I3 F
A0A6N2TIA4 F
A0A1E3PQH0 F
A4CMI3 F
Q1K0H9 F
A0A0S6UEK9 F
A0A0H3LUA3 F
B9LU00 F
A9BIZ7 F
A0A7H8UK07 F
E3H8C9 F
M2A398 F
Q1QS12 F
G0VI62 F
A0A1Z3MS36 F
A0A0B5FNH4 F
D9SI36 F
A0A410JZR4 F
F7ZJZ1 F
F0ZCX7 F
W0DZX1 F
A0A4R3ZZ35 F
A0A317G0I6 F
Q0ARJ4 F
A7I8Z4 F
T2KJ59 F
I3C0V3 F
E3H8A6 F
B2IJT1 F
A0A2G6JLT9 F
A3ZZL7 F
A0A2T0XPP2 F
Q31CR9 F
A0A1R1IDV3 F
K2JVF8 F
V5BYZ7 F
D8J4C6 F
D4H5F9 F
K9ZG59 F
A0AA86YS65 F
Q608B6 F
A0A562BXM4 F
A0A401WXG0 F
A0A857DMN9 F
A0A1X6N3Q5 F
A0A173R3X4 F
Q63EK5 F
K9ZLY2 F
A0A533I6R2 F
I0WJ97 F
K0N2R5 F
M0J579 F
B8GGC1 F
A0A6H9GFU4 F
C6CBB1 F
A0A510HHK8 F
A0A1B9MBX6 F
A0A9Y2AG30 F
E8RSE4 F
F2B2B8 F
Q7UYZ3 F
I1YJH7 F
A0A853MG28 F
A0A0L0STS6 F
A0A251XU71 F
Q60BI2 F
A0A829X098 F
F3KUN4 F
Q60C43 F
A0A0T7FAP8 F
A0A3E2TW06 F
W0E077 F
A0KPE9 F
R7PZ71 F
A0A0A1ZMZ9 F
A0AA40J491 F
D3S2L0 F
A0A373FQ71 F
A0A0A2C6L1 F
Q7W7D3 F
A0A165K0X5 F
A0A2S5X482 F
R9GM11 F
Q0G0A3 F
D4GLQ6 F
E7RJZ0 F
F8IJE0 F
A0A1V2XMU9 F
Q7TNN9 F
A0A1G5RZU9 F
A0A2N6K4Y5 F
B0SLB7 F
A0A251YFS0 F
B9WDK0 F
Q7N0M6 F
A0A0M2LU39 F
F4B548 F
D6Z5V9 F
A0A4R2M206 F
A0A1E2SKM1 L
A0A127JTU2 F
A0A212AV03 F
G4QHD2 F
A0A021VMC6 F
A0A2J7TJ33 F
G7WDB5 F
Q6BK68 F
Q1K3N8 F
A0AA91Q161 F
A0NJ07 F
A0A316BQ38 F
A0A377PLP5 F
W7QGM4 F
A0A015YIP3 F
A0A060UWC8 F
A0A1I4ZIZ6 F
A0A264VQM8 F
A9AUR8 F
A0A1W5PRD1 F
A0A0E3BR91 F
A0A1B0ZRL8 F
B9ACS5 F
Q92BJ7 F
F2JTN3 F
A1AVV2 F
D2Q0J8 F
A0A3S9N9F3 F
A8ZQD5 F
C3X831 F
A0A1M6BPM0 F
A0A8F5VN39 F
A0A1E5C7W4 F
A0A2S5WV24 F
A0A833GZR2 F
C7M2A9 F
A6W7U2 F
W0JIB3 F
Q07UM3 F
A0A066ZRQ5 F
S0G181 F
D3PAH1 F
Q4WHC6 F
A0AA94HTL8 F
D5ASL9 F
A0A4U1JNL6 F
M0MDP9 F
A0A653N397 F
A0A2S8GSU9 F
A0A097R891 F
A0A8H7U3I1 F
A0A1H1MB73 F
A0A016XDZ5 F
A0A1B9JHS5 F
D3PE53 F
A0A9J9BAE8 F
Q2RM12 F
A0A3N0AQL8 F
C5KTM6 F
M1P5F0 F
I1YG38 F
A0A660CH85 F
A0A2N7L7C8 F
Q5KZZ9 F
M1NZT5 F
A0A225CMT8 F
A0A068NV61 F
H2CJI0 F
B0DU93 F
Q221S8 F
F4Y3C5 F
Q94CJ2 F
M0D3Q9 F
A0A3P2A7W8 F
C0GKN4 F
Q7T3R4 F
A0A562USB9 F
A2SS52 F
A0A211ZGL5 F
A0A4V3ALP8 F
A0A147GP06 F
H2IZ00 F
Q45HK8 F
A0A6C8LST1 F
A0A257T8W6 F
Q5P470 F
I5AZQ4 F
Q07UM1 F
E5B358 F
A0A1Y4L5P0 F
Q3AFY9 F
B0BZN3 F
A0A1Q2C7H7 F
A0A4R5U5V1 F
H6LKX6 F
A0A1Y0UZX2 F
F6BEI0 F
M9RKT6 F
A7SGD4 L
A0A257TE48 F
R1FI09 F
E4N1T5 F
U1PIR6 F
F2JYR9 F
Q84KJ7 F
A0A2S8FTB5 F
D2R647 F
G9Y5B0 F
A0A144NLT9 F
A0A5J6WQU1 F
D2R355 F
F3ZYD6 F
B0SL05 F
A0A5A7MAJ9 F
A0A977NL43 F
A0A433ZQ80 F
A0A1Y0V4A5 F
A0A1M7UEG2 F
G8R7U9 F
K1LDP0 F
B7G0Y4 F
A0A2W4ZXC0 F
B3PF77 F
Q2KZK9 F
Q18ES8 F
D3F545 F
B4S394 F
Q1Q357 F
Q9H310 F
D3PKL4 F
M5SY07 F
Q8RUT6 F
A7NKH2 F
Q1Q879 F
A0A1B9M5B8 F
A6LRS5 F
J2ZGN6 F
V5E0F3 F
A0A149RQX0 F
A0A165BP25 F
C0QSY0 F
B0XVV6 F
E0SD83 F
A8HSA2 F
A0A1E3PSK5 F
A5DYQ2 F
A0A4U1K1W1 F
Q0AT01 F
A4FMG0 F
C3YB73 F
A0A9P3CXY2 F
A0A0L8BVU4 F
A0A401WUW1 F
I4C9L2 F
Q8RUE9 F
F0JGZ1 F
A0A2I0UUY1 F
A0A542XGT4 F
G0JRH4 F
A2SPS8 F
A0A5M4AWD2 F
Q6QH01 F
D3F0Z1 F
A6XBM2 F
D6E7B3 F
Q13E03 F
A0A060URB8 F
A0A2T1N7R1 F
D6TCH6 F
B0CXH8 F
A3TVQ9 F
Q4WT12 F
C7QGX3 F
F0Y9X3 F
A0A7S0D560 F
A0A160KTE9 F
A0A2H1HV86 F
A0A251Y3N4 F
A0A419AVL2 F
A0A4Q2QWS1 F
C7Q1E4 F
A0A5C5TYS5 F
F2NNQ0 F
A0A2R4TRE0 F
K9YJQ3 F
D9QS43 F
A7SQ16 F
A1DG05 F
U1SIR9 F
C4Y298 F
A0A9W3LFI9 F
D3RMV7 F
F3QNA7 F
E4RTK5 F
C8XBX8 F
C0QTA4 F
E6VIW4 F
A0A2S6H643 F
Q46HB1 F
A0A2S5CTX8 F
A0A1T4SF40 F
K0K7J4 F
A0A1J5JH24 F
Q6LMI6 F
A0A9W5JBA9 F
A0A291PMC6 F
A0A4Y4DZN4 F
A0A2R4MBA2 F
R9PI53 F
A0A6H9GLV4 F
A0A7S4GND2 F
A0A6H9FPY5 F
A0A1G7DX68 F
A0A075WEB4 F
A0A140NHJ5 F
A0A1C6Z081 F
Q5FA36 F
Q0ACK1 F
A0A975GIX9 F
A0A323UE08 F
U7VB41 F
A0A063Y780 F
C5CIT6 F
A0A0A2VPU3 F
F0RHS0 F
A0A2S5WX34 F
C1G973 F
A0A2S6GKF6 F
A0A0A2B651 F
A0A4R3A5P7 F
A0A2A7U6W1 F
Q2GX26 F
F5XN43 F
A0A0K2STH0 F
A0A1H1U2Q6 F
A7SED8 F
A0LV78 F
K5DBA0 F
B8IZX4 F
A8LKQ0 F
A0A5C6LWQ1 F

In [95]:
seqh1 = []

for i in h1:
    print(i.id, i.seq)
    seqh1.append(i.seq)

A0A858ZNJ3 H
A0A1H9M798 H
B0DY50 H
P69680 H
A0A3G9G4Q4 H
A0A149UP06 H
F2G6G4 H
A0A2M9D7S8 H
A0A034WGQ2 H
I0KDC6 H
F8D7H6 H
K9W4V5 H
Q466Y3 H
D2SE15 H
A0A377PBY1 H
B1JZ69 H
A0A2W5HTC3 H
A8G2S3 H
D5T4N9 H
Q2RWY7 H
A0A0E3R4G0 H
I4C9L0 H
D5VJ32 H
C0Z5S5 H
C1N6X9 H
J7ITF6 E
A0A068SVR1 H
A0A0D7F328 H
Q0G0A4 H
F0J3F9 H
Q0BQ69 H
F2YIC4 H
D4XLN6 H
A0A420WC79 H
A0A5C5TUT2 H
A0RUZ2 H
A0A0A2ZRL7 H
J4UGB7 H
E5Y678 H
A0A0D2KGN8 H
S5ABR8 H
A9DQM8 H
G5EB13 H
A0A2N6NEK4 E
C6DB68 H
Q81GN5 H
Q0F2M5 H
A0A0C6P439 H
B9SWW9 H
L8H5K0 H
Q9NIV0 H
C1N5A7 H
Q1JXS5 H
A0A1M6JKY3 H
F4D1J0 H
A0A257SYX3 H
V4RK08 H
G0V8D6 E
A0A7S4GMD8 H
B3QVV5 H
F2JZ83 H
A0A857DDJ7 H
A0A0S6UHP2 H
D5EP71 H
F4KY49 H
M5S9B4 H
A0A009PYN3 H
A0A3T0SZ22 H
A0A248LMH8 H
A0A6H9GEE4 H
A7HSP2 H
A0A7V8IKS6 H
T2JFS5 H
F6FRU9 H
A0A9E9L9J1 H
A0AIW5 H
A0A0E9NHV4 H
Q2N625 H
C8WSI9 H
A0A1H1BPD6 H
A0A176XNC5 H
A0A4V0XUI3 H
A7S3L2 H
M5U2P1 H
K9P5D1 H
Q0F2M7 H
A0A2R3IMJ8 H
Q2RVB5 H
A0A556RTU3 H
E0TGP9 H
B7G0Y1 H
A0A1G9P6Q0 H
D0LTW3 H
Q6BT62 H
Q2IK04 H
Q6BJI7 E
B7X047 H
A0A068NPW2 H
A0A399NT81 H
K0F9X7 H
A0A037ZMW1 H
A0A075JZ35 H
A0A369MHK2 H
A0A1B9JPL5 H
D8PD01 H
A0A2G5BI87 E
A0A2G5BGA9 H
A0A657K391 H
P69681 H
A0A4P6UIJ8 H
A0A0V8M0W6 H
A0A0H2XSU4 H
Q1Z695 H
A0A7Z0V0A4 H
K0ER80 E
A0A149UWF2 H
G0H0Z6 H
G0EFF3 H
C8WLL8 H
X5CNT2 H
A0A4Y1MSE7 H
H2CLF7 H
M4VEJ9 H
A0A4V2X6C2 H
A0A2K1RA77 H
A0A375YPN6 H
A0A7M6UUM4 H
A0A172YCA7 H
A0A918MJ52 H
A0A2S8QA29 H
A0A251XJT0 H
A0A0B4E6X7 H
A0A0K2STQ7 H
A1C5Z7 E
C9KKP2 H
A0A2Z4MD56 H
Q9VFA9 H
A0A502GPV4 H
I5C044 H
D2V6P8 H
D3RN22 H
Q97L80 H
A0A0D5YN10 H
A0A1I5GN22 H
A0A1Y5E8I7 H
B1Y8C9 H
M5SYZ1 H
Q6HM26 H
A0A379A0S9 H
A0A101DCS3 H
A0A1Y3U5V2 H
A0A202B535 H
F8E6R1 H
Q6ND36 H
A0A8H6K7L7 E
Q7NCB8 H
A0A369MRW6 H
C9RS76 H
A3U857 H
A0A127PIQ9 H
B8FGW0 H
A0A060JMP6 H
D5V7B3 H
A0A494JB70 H
A0A5M8QF12 H
A0A8G2F3G4 H
J7L3W8 H
G0JRG9 H
D3DJN2 H
A0A1Y2JH43 H
Q1L727 H
A0A7T2S0Z6 H
A0A315S845 H
A0A2S6H6B7 H
A0A1J5NTP7 H
A0A0E3QY86 H
A0A096EEV9 H
A0A380S5X4 H
B8ZYW3 H
A0A2S8GEJ5 H
A0A248TDF2 H
B2GFN1 H
U1PPI7 H
C7LW88 H
G3A431 H
A0A066ZTE4 H
L7CG99 H
S0ET45 H
A0A178TA08 H
H1XV27 H
A0A6M3ZJI1 H
U5DEY6 H
H6LFQ2 H
Q6CRN0 H
A0A4Q2EAG7 H
A0A1J5NNB8 H
E3I393 H
A0A243SC06 H
D4F313 H
W0F0I7 H
A9B874 H
A1D2Y5 H
T2J0N1 H
Q2FQT3 H
A0A075WG29 H
A0A979GQ79 H
A0A381CAY8 H
A0A2G3DSU6 H
A0A168EVK8 H
A0A094W9G3 H
A0A4R3NVT3 H
W0DYY3 H
G8JTW0 E
A0A4P6UIK6 H
I9P003 H
G2T1Y3 H
B8EMQ8 H
I6Z905 H
E0TCV4 H
A3XNG6 H
A0A087MGU4 H
A2BUP4 H
A0A562S8V2 H
A0A495DND0 H
A0A0S2FHD7 H
F3QPR6 H
A0A063Y394 H
F6G5I9 H
A0A323UDG5 H
A0A0G9HEC5 H
B8FDY8 H
Q5KPM5 E
A0A147EQL9 H
A0A854Q6X9 H
C3X1J1 H
A0A5B2V3B9 H
A0A258FS85 H
A0A7T2W1B3 H
A0A060UN76 H
G0JRQ3 H
D5UD26 H
G2ZN72 H
A0AA46Q839 H
A5UJR1 H
L1INN6 H
C1F584 H
C5LAG4 H
A0A2A2MCP3 H
B1Y6V4 H
A0A1G6ABK5 H
A0A6A1TYJ4 H
A0A2T4UWF1 H
V4AP67 H
A0A173R3W6 H
C7NND3 H
B0DFJ4 H
A0A3E2VY88 H
R1EDV9 H
J1L5M8 E
D7G265 H
Q8ERT9 H
I4D6Z9 H
A0A4R6DFU8 H
A0A060URC3 H
D2BIB2 H
F5ISF6 H
A5CRL2 H
A0A6G9XJV9 E
Q59UP8 H
A0A6N4SPH9 H
I0HGY4 H
X5DX97 H
L1J6I4 H
I1DSU5 H
B9L7N1 H
Q1Z4I4 H
Q21CP1 H
A0A165MFD1 H
V4CRP5 H
Q7S5K0 H
A0A071MMV1 H
A0A149RYW7 H
A0A7G5EC77 H
A0A1W2GZ82 H
A0A7U3XVQ4 H
A0A071M4L5 H
U5C2K4 H
A0A248LNW8 H
L8H844 H
A0A149V596 H
S9QZ09 H
B1ZSW9 H
D2BUJ8 H
A0A9Q8L398 H
M5S735 H
Q6ARH0 H
K6W5X0 H
G0JRG6 H
A0A6H9FYW4 H
A0A0S4WFM4 H
A0A101HKN9 H
Q9REX3 H
F0S3Z6 H
A8NAG3 H
C6LBD3 H
A0A149U2G9 H
V4REY8 H
A0A0H3H4I7 H
A8N2H6 E
S0APH6 H
A0A017SYR8 H
A0A1B9MZ78 H
E4T3F3 H
D7E934 H
A0A0M3AB44 H
A9WHW6 H
A0A5M4AUM9 H
A0A1X4GBG2 H
I4D1H5 E
A0A0E3QYF3 H
B0CQX4 E
A0A378YR15 H
A0A495D4X4 H
A0A076PL76 H
Q1YDY7 H
A0A3E2UCG9 H
A0A2K3DPU7 H
A0A3R9Q7C4 H
V5U2Z4 H
K9P718 H
M1V7W3 H
Q6LKC8 H
E5Y789 H
J9Z839 H
A0A1G7VM92 H
K9Z0D3 H
A0A482TED1 H
R1EGK6 H
J1ASR8 H
A0A7U4E420 H
K9YR86 H
A8PXT8 H
A0A0U1NJW3 H
B8FL88 H
A2CCK1 H
D6TFE1 H
A0A2H4U5R1 H
I2GD40 H
A0A060HFT5 H
B1Y842 H
A0A0X8NXA9 H
A0A0A2A5X1 H
A0A318FY98 H
Q7V4T8 H
A0A1A0DHK0 H
C1A872 H
A0A395VB65 H
A7MFK3 H
J4KM12 E
A1SY01 H
A0A1H4DJ49 H
A0A9R0NTP8 H
A3PAY4 H
B4CV94 H
A2C095 H
Q2HD43 E
A0A836M2B6 H
H6RWK9 H
A0A087EQK8 H
A0A1I0AQM4 H
L7CG11 H
A0A248LNK5 H
B7FTM9 H
L0K9M1 H
I4D6Z7 H
A0A2K1RA81 H
Q2WBF7 H
A0A1B9BUU6 H
A0A2S0JW39 H
A0A2S5YID7 H
B3PIH2 H
U3P8G1 H
C9R9J0 H
A8AC17 H
F0YLV7 H
A0A1D3GAE9 H
C1MHX0 H
A0A1H4KAQ7 H
A0A2T4XZC1 H
A1B3N0 H
C7LW87 H
A1SZ12 H
A0A2T2Y0D5 H
A0A1H8D0R8 H
A0A2S5V2F6 H
G3IYW2 H
F5L8M7 H
C7BJG7 H
E4U5Z1 H
A0A1B9K8L2 H
A0A2S5WMT7 H
A0A0D2UPA8 H
A0A161SKF4 H
B4D7W2 H
A0A1H3WA00 H
C1D6X6 H
A0A4D6KHD1 H
Q488X2 H
A9V5W4 H
A0A5M4ATH9 H
E4TRS4 H
A0A011U1K7 H
C7R314 H
A0A077EFU9 H
A0A0A2A0Y9 H
A0A0D8BQX6 H
A0A0L0S493 E
A0A328Q6M1 H
A0A016XCG9 H
B7FSA7 H
G0AFH4 H
A0A177W826 H
A0A2S8GF54 H
Q1YDY8 H
Q5QVH2 H
A3ZT81 H
A0AA35XZV0 H
F4H924 H
K0NJH2 H
A0A1V3SSW1 H
F2AUF4 H
A6DN47 H
W8KM07 H
A0A1X3RP39 H
A0A7S0KKL8 H
A0A318QZ80 H
K8VZC6 H
A0A1B9JZS5 H
A0A2S6GKN5 H
A0A4R2Z2K6 H
H1YCC3 H
E1QIU3 H
A0A8H6MPB9 E
A0A369N7Y3 H
T2IEJ2 H
H5UND3 H
Q1PX09 H
A0A149TSA9 H
F2NGJ8 H
A0A0E3SHQ9 H
Q5FLR6 H
S0EUS1 H
A0A369M386 H
W0DZS7 H
A8MCL4 H
V3ZVE4 H
O26757 H
A0A317FZW2 H
A0A085GI50 H
A1ZGK6 H
G0IYI2 H
A7S731 H
A0A1U9YY82 H
A0A328EMN2 H
A0A8E2UDJ3 H
A0A2S5WUP6 H
A0A8H7P8U1 H
A0A257T7G4 H
B3MX93 H
A0A1G5W0P2 H
D4H2Y7 H
A0A4P8HC89 H
Q7T070 H
F7NPQ3 H
B9SA70 H
Q9M6N7 H
I7ZHW3 H
F4XTK4 H
A4G1J2 H
G7WFX4 H
B8JBH5 H
D9QPC8 H
A0A4R7GKA0 H
R9PMC6 H
A0A0E3LMT4 H
A0A511NGC7 H
E4NS62 H
E4T3F7 H
M0D580 H
J7J5E7 H
B1XZU2 H
A0A366IE34 H
A0A6U2BIY7 H
Q9QXP0 H
A0A424WAH3 H
A0A410K1J5 H
L1IHZ8 H
I8TC71 H
A0A7U8C744 H
A8M670 H
A0A0S4VNK2 H
Q2SIR0 H
A0A5C4RNH5 H
A0A3E0X011 H
A0A0E3SP24 H
E1IF27 H
Q2YBP7 H
A0A2S5WZU0 H
A0A172YBR4 H
A0A0K2STK6 H
A0A2N6JV02 H
F0S0G1 H
A0A1C7EL50 H
Q18PF5 H
A0A1I0C958 H
A0AA35XVN2 H
L8GGA0 H
Q3AP28 H
D0MFE9 H
J9VXX9 H
A0A166IS52 H
F0J7D3 H
W7QG13 H
A4BMY5 H
A6LV49 H
Q1H483 H
A6M3G0 H
E4T0A4 H
A0A3E2UHE6 H
A0A174SD65 H
A0A855EH99 H
C3YB74 H
A0A074KZD8 H
J0S2I0 H
K9WSX4 H
E8RLT5 H
Q2FS34 H
Q3Z7F9 H
Q2S8H9 H
A0A060HN92 H
E6ME92 H
A0A172RYW3 H
L0FU80 H
C8WZE0 H
A0A2S8F4W0 H
A0A2C6C0X3 H
F3ZVV4 H
A0A7R6PER3 H
A0A495WJM6 H
A0A0B4DUR9 H
A0A251YU48 H
A5D4I5 H
A0A2X2C038 H
A0A2A2M8K7 H
D3FBG3 E
A0A2V4EA49 H
D0MFE8 H
Q3B6Q2 H
A0A1B9KID3 H
A0A9J9ES23 H
A0A3N2SFS2 H
Q0VLH1 H
A0A1U9Z147 H
Q0G2T1 H
A6GJF5 H
A0A059XXR1 H
A0A5J6WPP9 H
P41948 H
L1IUV5 H
A0A2W0GQV0 H
Q1K433 H
A0A4Y7XC43 H
D5AU98 H
E1QFA8 H
A0A075WBP9 H
Q0BWD0 H
A0A1Y0HX98 H
A0A098S5Y7 H
Q0I445 H
A0A1E5BXA4 H
A0A2C9CK98 H
G4H971 H
A0A1I0BYN1 H
A0A330GB00 H
A0A2S8FR08 H
Q84KJ6 H
A0A2S5WGI8 H
M2ALH9 H
A0A2K3DQF8 H
A0A8G2IZM3 H
F5Y3C1 H
A0A370FPU0 H
F5RGM7 H
A0A4R4K1P9 H
R8VWI7 H
A0A0A2AMW2 H
Q7Z1M1 H
A0A414NWT8 H
A0A0P6VSR8 H
A0A0L0TDW1 H
U3PCH5 -
W7QGE0 H
C5BWX7 H
A0A1B9M1A9 H
B8GGC3 E
D6SPD1 H
A0A0H3DR67 H
A0A4R7VEK0 H
G4R7P1 H
A0A1M5ZVP9 H
A0A2S5Y0D3 H
I0ICG0 H
D0L8H3 H
A0A1B9LFW3 H
Q6ND34 H
A0A6H9GWG4 H
Q5UZ98 H
A0A2S0P9T4 H
H2CDR5 H
T2KGT3 H
A0A088E6Q7 H
A0A258HS77 H
E1V4T3 H
B7GKP4 H
Q9QUT0 H
I3Z3H7 H
G7WCB6 H
A0A1Y6GLJ1 H
A0A0S2DQB6 H
Q6CRN1 H
A0A401X433 H
A7HT14 H
A0A009TDB1 H
D4XSW0 H
B0SRS8 H
A0A149QSR6 H
B1Y0E5 H
Q7UGU7 H
A0A2S0Q8P1 H
F0ZPL3 H
A0A2T0GTU1 H
I4CCD1 H
A0A9Q6P4A5 H
A0A418VIJ8 H
C1MX19 H
A0A1B9BUZ8 H
K9W6F3 H
Q1K8A3 H
L8GFX3 H
A0A1G6ABL9 H
A0A087L0B9 H
A0A073CP02 H
A0A0A1ZJU5 H
A0A258HPP1 H
A0A149QAW7 H
D2V6Q5 H
A0A1X4G8K1 H
A0A067Z3S3 H
A0A8F5ZDT8 H
A0A854QN45 E
A0A2N7LCD7 H
G7WFX2 H
A0A7S4GNJ2 H
A4G0C5 H
A6VE60 H
A0A1S1HM83 H
A0A037ZJY5 H
N1WR17 H
Q2W5V2 H
A1VIM5 H
A0A1Y5E3E3 H
A0A1T4SFK4 H
A7RNC3 H
M7XJ51 H
A0A399T909 H
A0A2N6P374 H
H8L2Q4 H
D5EP68 H
E6SF19 H
A0A1T4SFY6 H
D3LBI0 H
E6W5C1 H
Q0VPH4 H
K9WT03 H
L0KW14 H
A0A4R8H081 H
A0A1B9N3H7 H
B0RC35 H
A0A420KGW4 H
A0A4R3NLV5 H
Q47K18 H
Q21P82 H
M1WRK6 H
A0A290XBB5 H
A0A6T9XUR2 H
A0A1J1JH03 H
I3R0S7 H
A9UR54 H
A0A1G7H8X3 H
A0A8G2F718 H
Q1H0G2 H
D0LAL7 H
C7LQR9 H
A0A1G5PWV0 H
K1K628 H
B9SXC7 H
G7WA28 E
Q1IWN6 H
H6LKH9 E
A0A1H7CU41 H
G8JUJ2 H
A0A081N2G5 H
A0A074ME37 H
Q0VQH6 H
C8XB51 H
A1VIG8 H
Q8GQS1 H
A0A1I7FBM5 H
A0A1M6ZMI3 H
A0A482PLH3 H
A0RXK8 H
D0KXQ0 H
Q8JI14 H
A0A7T4WEP4 H
A0A4R3ZNW3 H
A0A074KY88 H
A0A6M3ZKU5 H
M1SJL5 H
A0A1W9KSU5 H
E3GI40 H
A0A369NYJ2 H
A0AA92K392 H
O04161 H
A9BQZ4 H
A0A6N2Z556 H
A0A8H6NAG3 E
A0A2T9X1V4 H
Q2J376 H
A0A0F5EZP7 H
A0A7G5DK18 H
M9YAI9 H
D2ZRW2 H
G7UUY6 H
A0A8H4GS02 H
A0A2T5IHP0 H
A0A165MAC2 H
A0A7S4LPS8 H
A0A075JIN0 H
C8X554 H
B8FZP7 H
Q5KAF6 H
A0A427KNL6 H
A0A7G5DPV0 H
Q22947 H
A0A1S1HRJ0 H
A0A3N1VXY4 H
A0A2S7YPJ9 E
I0JI83 H
A0A7U3YMN6 H
Q9BLG3 H
A0A1H9RTW8 H
A0A1I4W3A0 H
A0A0B4M163 H
U2EN72 H
A0A2W5VAZ2 H
E4YA63 H
D5ELM4 H
M9RJS5 H
A0A2G3E8V2 H
Q5FSX6 H
I0HKQ8 H
A0A833H2R7 H
B8ENL9 H
B3DUX7 H
A0A1D8UWJ6 H
D5E995 H
A0A7U8C2Y6 H
L0KGR8 H
B0VMH1 H
P40260 E
L0JT30 H
C1GR74 E
A0A423Y4I6 H
A0A4P7UHQ5 H
A0A8E2R1Y5 H
I5BYV5 H
A0A6B8N021 H
A0A7G5DPV1 H
A0A2G5RQK9 H
A0A5M4B0G1 H
A0A6S5K4J1 H
C1D4X0 H
A1SVA8 H
H1YF74 H
A0A8B4RWH8 H
A0A0A0D6K5 H
A0A0A2BBY0 H
A0A089ZBW5 H
A0A068TC78 H
Q46G49 H
A1CQ21 H
A0A1G6ABX1 H
E1SLM7 H
K5CFE5 H
Q2YLQ6 H
Q0G2V0 H
A4ABK3 H
A0A9Q5QVI9 H
A0A4Q7Y9I7 H
A9HMD6 H
K9YN27 H
Q9UBD6 H
D9SI59 H
Q8I0L6 H
A0A142VAD6 H
G3IYW0 H
A0A062IU58 H
R1D1H4 H
A0A366XFS8 H
A0A7S4GNF3 H
F0J6E8 E
A0A7U4DN04 H
V4RHR4 H
F7ZJM0 H
A0A2S5XAB8 H
U5C4L4 H
Q21J04 H
A0A142NNN1 H
H1Y7T6 H
F5R974 H
B0DU91 E
A2BP62 H
A7HSN9 H
A0A377I7W9 H
D2RU19 H
G7WJN0 H
E2SD33 H
A0A0D7F2Y9 H
A0AA92EGF5 H
A0A9E9LXV9 H
A4BEP1 H
A0A0E3WZH5 H
F7ZEU9 H
A5E3X2 H
A0A0A3XTJ3 H
A0A830ZZN8 H
A0A1S8D478 H
J7IVQ1 H
A0A2U1SS17 H
S3K1S2 H
C6XKC2 H
A0A2S7YIM5 H
K2IMJ7 H
Q5P1S8 H
A0A7T5BFQ2 H
A0A556SRH6 H
A8P923 H
A0A7G5DKA9 H
L8JUH3 H
A0A0D2LEF5 E
A0A258FTB0 H
A0A5P9P1L2 H
M8E0R3 H
A0A6J5IRX5 H
W5WIX6 H
Q82X47 H
I4DBY0 H
A0A6F8TLE9 H
A0A1G7UZX2 H
A0A6P4JM51 H
G0J614 H
U2WTW8 H
A0A642KQG8 H
Q1AUG3 H
A0A6G9Y3Q0 H
B8J5X4 H
M7NFH3 H
A0A0E3R6S1 H
Q2IHY5 H
A7I8Z2 H
L1IYP4 H
B4HDZ9 H
A0A366WYI9 H
E4TJ50 H
A0A7S0ILH2 H
A4BAE1 H
B3QRJ4 H
A0A5C5BWI6 H
Q7NQY2 H
A0A091AXI3 H
Q1QSQ2 H
R4FZE3 H
A0A2N0MZ27 H
A9BTK1 H
A0A242NIL1 H
G0LFE3 H
A0A1B9NQ91 H
A0A5M5PZE2 H
A0A0D2NYP3 H
D9QPE5 H
I5B3H0 H
L1IYW7 H
C6WEW7 H
B7FW68 H
F4GED5 H
A0A4R8GSH7 H
A0A1W2H3F0 H
A0A3E2T713 H
A0A0H3KTD3 H
A0A1Y4LM49 H
G2PRJ6 H
A0A0X8X7Y7 H
K8EJ02 H
A0A1L3F1X5 H
G8TK77 H
A0A855F5Y8 H
A0A975BTN0 H
A0A562RGZ4 H
G5EB09 E
A0A833LX85 H
U1H1F7 H
K8W1E2 H
E3HJW8 H
Q7SEH0 E
Q47X17 H
B0DXT9 E
A0A3G9G2C9 H
Q95P70 H
A0A837C6X5 H
Q89WR5 H
A6DUG4 H
D7UQE2 H
A0A2I1M481 H
A0A0T7GZ59 H
O66395 H
J3EXK0 H
A0A1B9MYL7 H
K9U8C7 H
E2SD44 H
H6LKH6 H
Q605Y6 H
A0A9Q9D9I3 H
A0A6N2TIA4 H
A0A1E3PQH0 H
A4CMI3 H
Q1K0H9 H
A0A0S6UEK9 H
A0A0H3LUA3 H
B9LU00 H
A9BIZ7 H
A0A7H8UK07 H
E3H8C9 H
M2A398 H
Q1QS12 H
G0VI62 H
A0A1Z3MS36 H
A0A0B5FNH4 H
D9SI36 H
A0A410JZR4 H
F7ZJZ1 H
F0ZCX7 H
W0DZX1 H
A0A4R3ZZ35 H
A0A317G0I6 H
Q0ARJ4 H
A7I8Z4 E
T2KJ59 H
I3C0V3 H
E3H8A6 H
B2IJT1 H
A0A2G6JLT9 H
A3ZZL7 H
A0A2T0XPP2 H
Q31CR9 H
A0A1R1IDV3 H
K2JVF8 H
V5BYZ7 H
D8J4C6 H
D4H5F9 H
K9ZG59 H
A0AA86YS65 H
Q608B6 H
A0A562BXM4 H
A0A401WXG0 H
A0A857DMN9 H
A0A1X6N3Q5 H
A0A173R3X4 H
Q63EK5 H
K9ZLY2 H
A0A533I6R2 H
I0WJ97 H
K0N2R5 H
M0J579 H
B8GGC1 H
A0A6H9GFU4 H
C6CBB1 H
A0A510HHK8 H
A0A1B9MBX6 H
A0A9Y2AG30 H
E8RSE4 H
F2B2B8 H
Q7UYZ3 H
I1YJH7 H
A0A853MG28 H
A0A0L0STS6 E
A0A251XU71 H
Q60BI2 H
A0A829X098 H
F3KUN4 H
Q60C43 H
A0A0T7FAP8 H
A0A3E2TW06 H
W0E077 H
A0KPE9 H
R7PZ71 H
A0A0A1ZMZ9 H
A0AA40J491 H
D3S2L0 H
A0A373FQ71 H
A0A0A2C6L1 H
Q7W7D3 H
A0A165K0X5 H
A0A2S5X482 H
R9GM11 H
Q0G0A3 H
D4GLQ6 H
E7RJZ0 H
F8IJE0 H
A0A1V2XMU9 H
Q7TNN9 H
A0A1G5RZU9 H
A0A2N6K4Y5 H
B0SLB7 H
A0A251YFS0 H
B9WDK0 E
Q7N0M6 H
A0A0M2LU39 H
F4B548 H
D6Z5V9 H
A0A4R2M206 H
A0A1E2SKM1 -
A0A127JTU2 H
A0A212AV03 H
G4QHD2 H
A0A021VMC6 H
A0A2J7TJ33 H
G7WDB5 H
Q6BK68 H
Q1K3N8 H
A0AA91Q161 E
A0NJ07 H
A0A316BQ38 H
A0A377PLP5 H
W7QGM4 H
A0A015YIP3 H
A0A060UWC8 H
A0A1I4ZIZ6 H
A0A264VQM8 H
A9AUR8 H
A0A1W5PRD1 H
A0A0E3BR91 H
A0A1B0ZRL8 H
B9ACS5 H
Q92BJ7 H
F2JTN3 H
A1AVV2 H
D2Q0J8 H
A0A3S9N9F3 H
A8ZQD5 H
C3X831 H
A0A1M6BPM0 H
A0A8F5VN39 H
A0A1E5C7W4 H
A0A2S5WV24 H
A0A833GZR2 H
C7M2A9 H
A6W7U2 H
W0JIB3 H
Q07UM3 H
A0A066ZRQ5 H
S0G181 H
D3PAH1 H
Q4WHC6 E
A0AA94HTL8 H
D5ASL9 H
A0A4U1JNL6 H
M0MDP9 H
A0A653N397 H
A0A2S8GSU9 H
A0A097R891 H
A0A8H7U3I1 E
A0A1H1MB73 H
A0A016XDZ5 H
A0A1B9JHS5 H
D3PE53 H
A0A9J9BAE8 H
Q2RM12 H
A0A3N0AQL8 H
C5KTM6 H
M1P5F0 H
I1YG38 H
A0A660CH85 H
A0A2N7L7C8 H
Q5KZZ9 H
M1NZT5 H
A0A225CMT8 H
A0A068NV61 H
H2CJI0 H
B0DU93 E
Q221S8 H
F4Y3C5 H
Q94CJ2 H
M0D3Q9 H
A0A3P2A7W8 H
C0GKN4 H
Q7T3R4 H
A0A562USB9 H
A2SS52 H
A0A211ZGL5 H
A0A4V3ALP8 H
A0A147GP06 H
H2IZ00 H
Q45HK8 H
A0A6C8LST1 H
A0A257T8W6 H
Q5P470 H
I5AZQ4 H
Q07UM1 H
E5B358 H
A0A1Y4L5P0 H
Q3AFY9 H
B0BZN3 H
A0A1Q2C7H7 H
A0A4R5U5V1 H
H6LKX6 H
A0A1Y0UZX2 H
F6BEI0 H
M9RKT6 H
A7SGD4 H
A0A257TE48 H
R1FI09 H
E4N1T5 E
U1PIR6 H
F2JYR9 H
Q84KJ7 H
A0A2S8FTB5 H
D2R647 H
G9Y5B0 H
A0A144NLT9 H
A0A5J6WQU1 H
D2R355 H
F3ZYD6 H
B0SL05 H
A0A5A7MAJ9 H
A0A977NL43 H
A0A433ZQ80 H
A0A1Y0V4A5 H
A0A1M7UEG2 H
G8R7U9 H
K1LDP0 H
B7G0Y4 H
A0A2W4ZXC0 H
B3PF77 H
Q2KZK9 H
Q18ES8 H
D3F545 H
B4S394 H
Q1Q357 H
Q9H310 H
D3PKL4 H
M5SY07 H
Q8RUT6 H
A7NKH2 H
Q1Q879 H
A0A1B9M5B8 H
A6LRS5 E
J2ZGN6 H
V5E0F3 H
A0A149RQX0 H
A0A165BP25 H
C0QSY0 H
B0XVV6 E
E0SD83 H
A8HSA2 H
A0A1E3PSK5 E
A5DYQ2 E
A0A4U1K1W1 H
Q0AT01 H
A4FMG0 H
C3YB73 H
A0A9P3CXY2 H
A0A0L8BVU4 H
A0A401WUW1 H
I4C9L2 H
Q8RUE9 H
F0JGZ1 H
A0A2I0UUY1 H
A0A542XGT4 H
G0JRH4 H
A2SPS8 H
A0A5M4AWD2 H
Q6QH01 H
D3F0Z1 H
A6XBM2 H
D6E7B3 H
Q13E03 H
A0A060URB8 H
A0A2T1N7R1 H
D6TCH6 H
B0CXH8 H
A3TVQ9 H
Q4WT12 H
C7QGX3 H
F0Y9X3 H
A0A7S0D560 H
A0A160KTE9 H
A0A2H1HV86 H
A0A251Y3N4 H
A0A419AVL2 H
A0A4Q2QWS1 H
C7Q1E4 E
A0A5C5TYS5 H
F2NNQ0 H
A0A2R4TRE0 H
K9YJQ3 H
D9QS43 H
A7SQ16 H
A1DG05 E
U1SIR9 H
C4Y298 E
A0A9W3LFI9 H
D3RMV7 H
F3QNA7 H
E4RTK5 H
C8XBX8 H
C0QTA4 H
E6VIW4 H
A0A2S6H643 H
Q46HB1 H
A0A2S5CTX8 H
A0A1T4SF40 H
K0K7J4 H
A0A1J5JH24 H
Q6LMI6 H
A0A9W5JBA9 H
A0A291PMC6 H
A0A4Y4DZN4 H
A0A2R4MBA2 H
R9PI53 H
A0A6H9GLV4 H
A0A7S4GND2 H
A0A6H9FPY5 H
A0A1G7DX68 H
A0A075WEB4 H
A0A140NHJ5 H
A0A1C6Z081 H
Q5FA36 H
Q0ACK1 H
A0A975GIX9 H
A0A323UE08 H
U7VB41 H
A0A063Y780 H
C5CIT6 H
A0A0A2VPU3 H
F0RHS0 H
A0A2S5WX34 H
C1G973 E
A0A2S6GKF6 H
A0A0A2B651 H
A0A4R3A5P7 H
A0A2A7U6W1 H
Q2GX26 H
F5XN43 H
A0A0K2STH0 H
A0A1H1U2Q6 H
A7SED8 H
A0LV78 H
K5DBA0 H
B8IZX4 H
A8LKQ0 H
A0A5C6LWQ1 H

In [96]:
seqh2 = []

for i in h2:
    print(i.id, i.seq)
    seqh2.append(i.seq)

A0A858ZNJ3 H
A0A1H9M798 H
B0DY50 H
P69680 H
A0A3G9G4Q4 H
A0A149UP06 H
F2G6G4 H
A0A2M9D7S8 H
A0A034WGQ2 H
I0KDC6 H
F8D7H6 H
K9W4V5 H
Q466Y3 H
D2SE15 H
A0A377PBY1 H
B1JZ69 H
A0A2W5HTC3 H
A8G2S3 H
D5T4N9 H
Q2RWY7 H
A0A0E3R4G0 H
I4C9L0 H
D5VJ32 H
C0Z5S5 H
C1N6X9 H
J7ITF6 H
A0A068SVR1 H
A0A0D7F328 H
Q0G0A4 H
F0J3F9 H
Q0BQ69 H
F2YIC4 H
D4XLN6 H
A0A420WC79 H
A0A5C5TUT2 H
A0RUZ2 H
A0A0A2ZRL7 H
J4UGB7 H
E5Y678 H
A0A0D2KGN8 H
S5ABR8 H
A9DQM8 H
G5EB13 H
A0A2N6NEK4 H
C6DB68 H
Q81GN5 H
Q0F2M5 H
A0A0C6P439 H
B9SWW9 H
L8H5K0 H
Q9NIV0 H
C1N5A7 H
Q1JXS5 H
A0A1M6JKY3 H
F4D1J0 H
A0A257SYX3 H
V4RK08 H
G0V8D6 H
A0A7S4GMD8 H
B3QVV5 H
F2JZ83 H
A0A857DDJ7 H
A0A0S6UHP2 H
D5EP71 H
F4KY49 H
M5S9B4 H
A0A009PYN3 H
A0A3T0SZ22 H
A0A248LMH8 H
A0A6H9GEE4 H
A7HSP2 H
A0A7V8IKS6 H
T2JFS5 H
F6FRU9 H
A0A9E9L9J1 H
A0AIW5 H
A0A0E9NHV4 H
Q2N625 H
C8WSI9 H
A0A1H1BPD6 H
A0A176XNC5 H
A0A4V0XUI3 H
A7S3L2 H
M5U2P1 H
K9P5D1 H
Q0F2M7 H
A0A2R3IMJ8 H
Q2RVB5 H
A0A556RTU3 H
E0TGP9 H
B7G0Y1 H
A0A1G9P6Q0 H
D0LTW3 H
Q6BT62 H
Q2IK04 H
Q6BJI7 H
B7X047 H
A0A068NPW2 H
A0A399NT81 H
K0F9X7 H
A0A037ZMW1 H
A0A075JZ35 H
A0A369MHK2 H
A0A1B9JPL5 H
D8PD01 H
A0A2G5BI87 H
A0A2G5BGA9 H
A0A657K391 H
P69681 H
A0A4P6UIJ8 H
A0A0V8M0W6 H
A0A0H2XSU4 H
Q1Z695 H
A0A7Z0V0A4 H
K0ER80 H
A0A149UWF2 H
G0H0Z6 H
G0EFF3 H
C8WLL8 H
X5CNT2 H
A0A4Y1MSE7 H
H2CLF7 H
M4VEJ9 H
A0A4V2X6C2 H
A0A2K1RA77 H
A0A375YPN6 H
A0A7M6UUM4 H
A0A172YCA7 H
A0A918MJ52 H
A0A2S8QA29 H
A0A251XJT0 H
A0A0B4E6X7 H
A0A0K2STQ7 H
A1C5Z7 H
C9KKP2 H
A0A2Z4MD56 H
Q9VFA9 H
A0A502GPV4 H
I5C044 H
D2V6P8 H
D3RN22 H
Q97L80 H
A0A0D5YN10 H
A0A1I5GN22 H
A0A1Y5E8I7 H
B1Y8C9 H
M5SYZ1 H
Q6HM26 H
A0A379A0S9 H
A0A101DCS3 H
A0A1Y3U5V2 H
A0A202B535 H
F8E6R1 H
Q6ND36 H
A0A8H6K7L7 H
Q7NCB8 H
A0A369MRW6 H
C9RS76 H
A3U857 H
A0A127PIQ9 H
B8FGW0 H
A0A060JMP6 H
D5V7B3 H
A0A494JB70 H
A0A5M8QF12 H
A0A8G2F3G4 H
J7L3W8 H
G0JRG9 H
D3DJN2 H
A0A1Y2JH43 H
Q1L727 H
A0A7T2S0Z6 H
A0A315S845 H
A0A2S6H6B7 H
A0A1J5NTP7 H
A0A0E3QY86 H
A0A096EEV9 H
A0A380S5X4 H
B8ZYW3 H
A0A2S8GEJ5 H
A0A248TDF2 H
B2GFN1 H
U1PPI7 H
C7LW88 H
G3A431 H
A0A066ZTE4 H
L7CG99 H
S0ET45 H
A0A178TA08 H
H1XV27 H
A0A6M3ZJI1 H
U5DEY6 H
H6LFQ2 H
Q6CRN0 H
A0A4Q2EAG7 H
A0A1J5NNB8 H
E3I393 H
A0A243SC06 H
D4F313 H
W0F0I7 H
A9B874 H
A1D2Y5 H
T2J0N1 H
Q2FQT3 H
A0A075WG29 H
A0A979GQ79 H
A0A381CAY8 H
A0A2G3DSU6 H
A0A168EVK8 H
A0A094W9G3 H
A0A4R3NVT3 H
W0DYY3 H
G8JTW0 H
A0A4P6UIK6 H
I9P003 H
G2T1Y3 H
B8EMQ8 H
I6Z905 H
E0TCV4 H
A3XNG6 H
A0A087MGU4 H
A2BUP4 H
A0A562S8V2 H
A0A495DND0 H
A0A0S2FHD7 H
F3QPR6 H
A0A063Y394 H
F6G5I9 H
A0A323UDG5 H
A0A0G9HEC5 H
B8FDY8 H
Q5KPM5 H
A0A147EQL9 H
A0A854Q6X9 H
C3X1J1 H
A0A5B2V3B9 H
A0A258FS85 H
A0A7T2W1B3 H
A0A060UN76 H
G0JRQ3 H
D5UD26 H
G2ZN72 H
A0AA46Q839 H
A5UJR1 H
L1INN6 H
C1F584 H
C5LAG4 H
A0A2A2MCP3 H
B1Y6V4 H
A0A1G6ABK5 H
A0A6A1TYJ4 H
A0A2T4UWF1 H
V4AP67 H
A0A173R3W6 H
C7NND3 H
B0DFJ4 H
A0A3E2VY88 H
R1EDV9 H
J1L5M8 H
D7G265 H
Q8ERT9 H
I4D6Z9 H
A0A4R6DFU8 H
A0A060URC3 H
D2BIB2 H
F5ISF6 H
A5CRL2 H
A0A6G9XJV9 H
Q59UP8 H
A0A6N4SPH9 H
I0HGY4 H
X5DX97 H
L1J6I4 H
I1DSU5 H
B9L7N1 H
Q1Z4I4 H
Q21CP1 H
A0A165MFD1 H
V4CRP5 H
Q7S5K0 H
A0A071MMV1 H
A0A149RYW7 H
A0A7G5EC77 H
A0A1W2GZ82 H
A0A7U3XVQ4 H
A0A071M4L5 H
U5C2K4 H
A0A248LNW8 H
L8H844 H
A0A149V596 H
S9QZ09 H
B1ZSW9 H
D2BUJ8 H
A0A9Q8L398 H
M5S735 H
Q6ARH0 H
K6W5X0 H
G0JRG6 H
A0A6H9FYW4 H
A0A0S4WFM4 H
A0A101HKN9 H
Q9REX3 H
F0S3Z6 H
A8NAG3 H
C6LBD3 H
A0A149U2G9 H
V4REY8 H
A0A0H3H4I7 H
A8N2H6 H
S0APH6 H
A0A017SYR8 H
A0A1B9MZ78 H
E4T3F3 H
D7E934 H
A0A0M3AB44 H
A9WHW6 H
A0A5M4AUM9 H
A0A1X4GBG2 H
I4D1H5 H
A0A0E3QYF3 H
B0CQX4 H
A0A378YR15 H
A0A495D4X4 H
A0A076PL76 H
Q1YDY7 H
A0A3E2UCG9 H
A0A2K3DPU7 H
A0A3R9Q7C4 H
V5U2Z4 H
K9P718 H
M1V7W3 H
Q6LKC8 H
E5Y789 H
J9Z839 H
A0A1G7VM92 H
K9Z0D3 H
A0A482TED1 H
R1EGK6 H
J1ASR8 H
A0A7U4E420 H
K9YR86 H
A8PXT8 H
A0A0U1NJW3 H
B8FL88 H
A2CCK1 H
D6TFE1 H
A0A2H4U5R1 H
I2GD40 H
A0A060HFT5 H
B1Y842 H
A0A0X8NXA9 H
A0A0A2A5X1 H
A0A318FY98 H
Q7V4T8 H
A0A1A0DHK0 H
C1A872 H
A0A395VB65 H
A7MFK3 H
J4KM12 H
A1SY01 H
A0A1H4DJ49 H
A0A9R0NTP8 H
A3PAY4 H
B4CV94 H
A2C095 H
Q2HD43 H
A0A836M2B6 H
H6RWK9 H
A0A087EQK8 H
A0A1I0AQM4 H
L7CG11 H
A0A248LNK5 H
B7FTM9 -
L0K9M1 H
I4D6Z7 H
A0A2K1RA81 H
Q2WBF7 H
A0A1B9BUU6 H
A0A2S0JW39 H
A0A2S5YID7 H
B3PIH2 H
U3P8G1 H
C9R9J0 H
A8AC17 H
F0YLV7 H
A0A1D3GAE9 H
C1MHX0 H
A0A1H4KAQ7 H
A0A2T4XZC1 H
A1B3N0 H
C7LW87 H
A1SZ12 H
A0A2T2Y0D5 H
A0A1H8D0R8 H
A0A2S5V2F6 H
G3IYW2 H
F5L8M7 H
C7BJG7 H
E4U5Z1 H
A0A1B9K8L2 H
A0A2S5WMT7 H
A0A0D2UPA8 H
A0A161SKF4 H
B4D7W2 H
A0A1H3WA00 H
C1D6X6 H
A0A4D6KHD1 H
Q488X2 H
A9V5W4 H
A0A5M4ATH9 H
E4TRS4 H
A0A011U1K7 H
C7R314 H
A0A077EFU9 H
A0A0A2A0Y9 H
A0A0D8BQX6 H
A0A0L0S493 H
A0A328Q6M1 H
A0A016XCG9 H
B7FSA7 H
G0AFH4 H
A0A177W826 H
A0A2S8GF54 H
Q1YDY8 H
Q5QVH2 H
A3ZT81 H
A0AA35XZV0 H
F4H924 H
K0NJH2 H
A0A1V3SSW1 H
F2AUF4 H
A6DN47 H
W8KM07 H
A0A1X3RP39 H
A0A7S0KKL8 H
A0A318QZ80 H
K8VZC6 H
A0A1B9JZS5 H
A0A2S6GKN5 H
A0A4R2Z2K6 H
H1YCC3 H
E1QIU3 H
A0A8H6MPB9 H
A0A369N7Y3 H
T2IEJ2 H
H5UND3 H
Q1PX09 H
A0A149TSA9 H
F2NGJ8 H
A0A0E3SHQ9 H
Q5FLR6 H
S0EUS1 H
A0A369M386 H
W0DZS7 H
A8MCL4 H
V3ZVE4 H
O26757 H
A0A317FZW2 H
A0A085GI50 H
A1ZGK6 H
G0IYI2 H
A7S731 H
A0A1U9YY82 H
A0A328EMN2 H
A0A8E2UDJ3 H
A0A2S5WUP6 H
A0A8H7P8U1 H
A0A257T7G4 H
B3MX93 H
A0A1G5W0P2 H
D4H2Y7 H
A0A4P8HC89 H
Q7T070 H
F7NPQ3 H
B9SA70 H
Q9M6N7 H
I7ZHW3 H
F4XTK4 H
A4G1J2 H
G7WFX4 H
B8JBH5 H
D9QPC8 H
A0A4R7GKA0 H
R9PMC6 H
A0A0E3LMT4 H
A0A511NGC7 H
E4NS62 H
E4T3F7 H
M0D580 H
J7J5E7 H
B1XZU2 H
A0A366IE34 H
A0A6U2BIY7 H
Q9QXP0 H
A0A424WAH3 H
A0A410K1J5 H
L1IHZ8 H
I8TC71 H
A0A7U8C744 H
A8M670 H
A0A0S4VNK2 H
Q2SIR0 H
A0A5C4RNH5 H
A0A3E0X011 H
A0A0E3SP24 H
E1IF27 H
Q2YBP7 H
A0A2S5WZU0 H
A0A172YBR4 H
A0A0K2STK6 H
A0A2N6JV02 H
F0S0G1 H
A0A1C7EL50 H
Q18PF5 H
A0A1I0C958 H
A0AA35XVN2 H
L8GGA0 H
Q3AP28 H
D0MFE9 H
J9VXX9 H
A0A166IS52 H
F0J7D3 H
W7QG13 H
A4BMY5 H
A6LV49 H
Q1H483 H
A6M3G0 H
E4T0A4 H
A0A3E2UHE6 H
A0A174SD65 H
A0A855EH99 H
C3YB74 H
A0A074KZD8 H
J0S2I0 H
K9WSX4 H
E8RLT5 H
Q2FS34 H
Q3Z7F9 H
Q2S8H9 H
A0A060HN92 H
E6ME92 H
A0A172RYW3 H
L0FU80 H
C8WZE0 H
A0A2S8F4W0 H
A0A2C6C0X3 H
F3ZVV4 H
A0A7R6PER3 H
A0A495WJM6 H
A0A0B4DUR9 H
A0A251YU48 H
A5D4I5 H
A0A2X2C038 H
A0A2A2M8K7 H
D3FBG3 H
A0A2V4EA49 H
D0MFE8 H
Q3B6Q2 H
A0A1B9KID3 H
A0A9J9ES23 H
A0A3N2SFS2 H
Q0VLH1 H
A0A1U9Z147 H
Q0G2T1 H
A6GJF5 H
A0A059XXR1 H
A0A5J6WPP9 H
P41948 H
L1IUV5 H
A0A2W0GQV0 H
Q1K433 H
A0A4Y7XC43 H
D5AU98 H
E1QFA8 H
A0A075WBP9 H
Q0BWD0 H
A0A1Y0HX98 H
A0A098S5Y7 H
Q0I445 H
A0A1E5BXA4 H
A0A2C9CK98 H
G4H971 H
A0A1I0BYN1 H
A0A330GB00 H
A0A2S8FR08 H
Q84KJ6 H
A0A2S5WGI8 H
M2ALH9 H
A0A2K3DQF8 H
A0A8G2IZM3 H
F5Y3C1 H
A0A370FPU0 H
F5RGM7 H
A0A4R4K1P9 H
R8VWI7 H
A0A0A2AMW2 H
Q7Z1M1 H
A0A414NWT8 H
A0A0P6VSR8 H
A0A0L0TDW1 H
U3PCH5 A
W7QGE0 H
C5BWX7 H
A0A1B9M1A9 H
B8GGC3 H
D6SPD1 H
A0A0H3DR67 H
A0A4R7VEK0 H
G4R7P1 H
A0A1M5ZVP9 H
A0A2S5Y0D3 H
I0ICG0 H
D0L8H3 H
A0A1B9LFW3 H
Q6ND34 H
A0A6H9GWG4 H
Q5UZ98 H
A0A2S0P9T4 H
H2CDR5 H
T2KGT3 H
A0A088E6Q7 H
A0A258HS77 H
E1V4T3 H
B7GKP4 H
Q9QUT0 H
I3Z3H7 H
G7WCB6 H
A0A1Y6GLJ1 H
A0A0S2DQB6 H
Q6CRN1 H
A0A401X433 H
A7HT14 H
A0A009TDB1 H
D4XSW0 H
B0SRS8 H
A0A149QSR6 H
B1Y0E5 H
Q7UGU7 H
A0A2S0Q8P1 H
F0ZPL3 H
A0A2T0GTU1 H
I4CCD1 H
A0A9Q6P4A5 H
A0A418VIJ8 H
C1MX19 H
A0A1B9BUZ8 H
K9W6F3 H
Q1K8A3 H
L8GFX3 H
A0A1G6ABL9 H
A0A087L0B9 H
A0A073CP02 H
A0A0A1ZJU5 H
A0A258HPP1 H
A0A149QAW7 H
D2V6Q5 H
A0A1X4G8K1 H
A0A067Z3S3 H
A0A8F5ZDT8 H
A0A854QN45 H
A0A2N7LCD7 H
G7WFX2 H
A0A7S4GNJ2 H
A4G0C5 H
A6VE60 H
A0A1S1HM83 H
A0A037ZJY5 H
N1WR17 H
Q2W5V2 H
A1VIM5 H
A0A1Y5E3E3 H
A0A1T4SFK4 H
A7RNC3 H
M7XJ51 H
A0A399T909 H
A0A2N6P374 H
H8L2Q4 H
D5EP68 H
E6SF19 H
A0A1T4SFY6 H
D3LBI0 H
E6W5C1 H
Q0VPH4 H
K9WT03 H
L0KW14 H
A0A4R8H081 H
A0A1B9N3H7 H
B0RC35 H
A0A420KGW4 H
A0A4R3NLV5 H
Q47K18 H
Q21P82 H
M1WRK6 H
A0A290XBB5 H
A0A6T9XUR2 H
A0A1J1JH03 H
I3R0S7 H
A9UR54 H
A0A1G7H8X3 H
A0A8G2F718 H
Q1H0G2 H
D0LAL7 H
C7LQR9 H
A0A1G5PWV0 H
K1K628 H
B9SXC7 H
G7WA28 H
Q1IWN6 H
H6LKH9 H
A0A1H7CU41 H
G8JUJ2 H
A0A081N2G5 H
A0A074ME37 H
Q0VQH6 H
C8XB51 H
A1VIG8 H
Q8GQS1 H
A0A1I7FBM5 H
A0A1M6ZMI3 H
A0A482PLH3 H
A0RXK8 H
D0KXQ0 H
Q8JI14 H
A0A7T4WEP4 H
A0A4R3ZNW3 H
A0A074KY88 H
A0A6M3ZKU5 H
M1SJL5 H
A0A1W9KSU5 H
E3GI40 H
A0A369NYJ2 H
A0AA92K392 H
O04161 H
A9BQZ4 H
A0A6N2Z556 H
A0A8H6NAG3 H
A0A2T9X1V4 H
Q2J376 H
A0A0F5EZP7 H
A0A7G5DK18 H
M9YAI9 H
D2ZRW2 H
G7UUY6 H
A0A8H4GS02 H
A0A2T5IHP0 H
A0A165MAC2 H
A0A7S4LPS8 H
A0A075JIN0 H
C8X554 H
B8FZP7 H
Q5KAF6 H
A0A427KNL6 H
A0A7G5DPV0 H
Q22947 H
A0A1S1HRJ0 H
A0A3N1VXY4 H
A0A2S7YPJ9 H
I0JI83 H
A0A7U3YMN6 H
Q9BLG3 H
A0A1H9RTW8 H
A0A1I4W3A0 H
A0A0B4M163 H
U2EN72 H
A0A2W5VAZ2 H
E4YA63 H
D5ELM4 H
M9RJS5 H
A0A2G3E8V2 H
Q5FSX6 H
I0HKQ8 H
A0A833H2R7 H
B8ENL9 H
B3DUX7 H
A0A1D8UWJ6 H
D5E995 H
A0A7U8C2Y6 H
L0KGR8 H
B0VMH1 H
P40260 H
L0JT30 H
C1GR74 H
A0A423Y4I6 H
A0A4P7UHQ5 H
A0A8E2R1Y5 H
I5BYV5 H
A0A6B8N021 H
A0A7G5DPV1 H
A0A2G5RQK9 H
A0A5M4B0G1 H
A0A6S5K4J1 H
C1D4X0 H
A1SVA8 H
H1YF74 H
A0A8B4RWH8 H
A0A0A0D6K5 H
A0A0A2BBY0 H
A0A089ZBW5 H
A0A068TC78 H
Q46G49 H
A1CQ21 H
A0A1G6ABX1 H
E1SLM7 H
K5CFE5 H
Q2YLQ6 H
Q0G2V0 H
A4ABK3 H
A0A9Q5QVI9 H
A0A4Q7Y9I7 H
A9HMD6 H
K9YN27 H
Q9UBD6 H
D9SI59 H
Q8I0L6 H
A0A142VAD6 H
G3IYW0 H
A0A062IU58 H
R1D1H4 H
A0A366XFS8 H
A0A7S4GNF3 H
F0J6E8 H
A0A7U4DN04 H
V4RHR4 H
F7ZJM0 H
A0A2S5XAB8 H
U5C4L4 H
Q21J04 H
A0A142NNN1 H
H1Y7T6 H
F5R974 H
B0DU91 H
A2BP62 H
A7HSN9 H
A0A377I7W9 H
D2RU19 H
G7WJN0 H
E2SD33 H
A0A0D7F2Y9 H
A0AA92EGF5 H
A0A9E9LXV9 H
A4BEP1 H
A0A0E3WZH5 H
F7ZEU9 H
A5E3X2 H
A0A0A3XTJ3 H
A0A830ZZN8 H
A0A1S8D478 H
J7IVQ1 H
A0A2U1SS17 H
S3K1S2 H
C6XKC2 H
A0A2S7YIM5 H
K2IMJ7 H
Q5P1S8 H
A0A7T5BFQ2 H
A0A556SRH6 H
A8P923 H
A0A7G5DKA9 H
L8JUH3 H
A0A0D2LEF5 H
A0A258FTB0 H
A0A5P9P1L2 H
M8E0R3 H
A0A6J5IRX5 H
W5WIX6 H
Q82X47 H
I4DBY0 H
A0A6F8TLE9 H
A0A1G7UZX2 H
A0A6P4JM51 H
G0J614 H
U2WTW8 H
A0A642KQG8 H
Q1AUG3 H
A0A6G9Y3Q0 H
B8J5X4 H
M7NFH3 H
A0A0E3R6S1 H
Q2IHY5 H
A7I8Z2 H
L1IYP4 H
B4HDZ9 H
A0A366WYI9 H
E4TJ50 H
A0A7S0ILH2 H
A4BAE1 H
B3QRJ4 H
A0A5C5BWI6 H
Q7NQY2 H
A0A091AXI3 H
Q1QSQ2 H
R4FZE3 H
A0A2N0MZ27 H
A9BTK1 H
A0A242NIL1 H
G0LFE3 H
A0A1B9NQ91 H
A0A5M5PZE2 H
A0A0D2NYP3 H
D9QPE5 H
I5B3H0 H
L1IYW7 H
C6WEW7 H
B7FW68 H
F4GED5 H
A0A4R8GSH7 H
A0A1W2H3F0 H
A0A3E2T713 H
A0A0H3KTD3 H
A0A1Y4LM49 H
G2PRJ6 H
A0A0X8X7Y7 H
K8EJ02 H
A0A1L3F1X5 H
G8TK77 H
A0A855F5Y8 H
A0A975BTN0 H
A0A562RGZ4 H
G5EB09 H
A0A833LX85 H
U1H1F7 H
K8W1E2 H
E3HJW8 H
Q7SEH0 H
Q47X17 H
B0DXT9 H
A0A3G9G2C9 H
Q95P70 H
A0A837C6X5 H
Q89WR5 H
A6DUG4 H
D7UQE2 H
A0A2I1M481 H
A0A0T7GZ59 H
O66395 H
J3EXK0 H
A0A1B9MYL7 H
K9U8C7 H
E2SD44 H
H6LKH6 H
Q605Y6 H
A0A9Q9D9I3 H
A0A6N2TIA4 H
A0A1E3PQH0 H
A4CMI3 H
Q1K0H9 H
A0A0S6UEK9 H
A0A0H3LUA3 H
B9LU00 H
A9BIZ7 H
A0A7H8UK07 H
E3H8C9 H
M2A398 H
Q1QS12 H
G0VI62 H
A0A1Z3MS36 H
A0A0B5FNH4 H
D9SI36 H
A0A410JZR4 H
F7ZJZ1 H
F0ZCX7 H
W0DZX1 H
A0A4R3ZZ35 H
A0A317G0I6 H
Q0ARJ4 H
A7I8Z4 H
T2KJ59 H
I3C0V3 H
E3H8A6 H
B2IJT1 H
A0A2G6JLT9 H
A3ZZL7 H
A0A2T0XPP2 H
Q31CR9 H
A0A1R1IDV3 H
K2JVF8 H
V5BYZ7 H
D8J4C6 H
D4H5F9 H
K9ZG59 H
A0AA86YS65 H
Q608B6 H
A0A562BXM4 H
A0A401WXG0 H
A0A857DMN9 H
A0A1X6N3Q5 H
A0A173R3X4 H
Q63EK5 H
K9ZLY2 H
A0A533I6R2 H
I0WJ97 H
K0N2R5 H
M0J579 H
B8GGC1 H
A0A6H9GFU4 H
C6CBB1 H
A0A510HHK8 H
A0A1B9MBX6 H
A0A9Y2AG30 H
E8RSE4 H
F2B2B8 H
Q7UYZ3 H
I1YJH7 H
A0A853MG28 H
A0A0L0STS6 H
A0A251XU71 H
Q60BI2 H
A0A829X098 H
F3KUN4 H
Q60C43 H
A0A0T7FAP8 H
A0A3E2TW06 H
W0E077 H
A0KPE9 H
R7PZ71 H
A0A0A1ZMZ9 H
A0AA40J491 H
D3S2L0 H
A0A373FQ71 H
A0A0A2C6L1 H
Q7W7D3 H
A0A165K0X5 H
A0A2S5X482 H
R9GM11 H
Q0G0A3 H
D4GLQ6 H
E7RJZ0 H
F8IJE0 H
A0A1V2XMU9 H
Q7TNN9 H
A0A1G5RZU9 H
A0A2N6K4Y5 H
B0SLB7 H
A0A251YFS0 H
B9WDK0 H
Q7N0M6 H
A0A0M2LU39 H
F4B548 H
D6Z5V9 H
A0A4R2M206 H
A0A1E2SKM1 A
A0A127JTU2 H
A0A212AV03 H
G4QHD2 H
A0A021VMC6 H
A0A2J7TJ33 H
G7WDB5 H
Q6BK68 H
Q1K3N8 H
A0AA91Q161 H
A0NJ07 H
A0A316BQ38 H
A0A377PLP5 H
W7QGM4 H
A0A015YIP3 H
A0A060UWC8 H
A0A1I4ZIZ6 H
A0A264VQM8 H
A9AUR8 H
A0A1W5PRD1 H
A0A0E3BR91 H
A0A1B0ZRL8 H
B9ACS5 H
Q92BJ7 H
F2JTN3 H
A1AVV2 H
D2Q0J8 H
A0A3S9N9F3 H
A8ZQD5 H
C3X831 H
A0A1M6BPM0 H
A0A8F5VN39 H
A0A1E5C7W4 H
A0A2S5WV24 H
A0A833GZR2 H
C7M2A9 H
A6W7U2 H
W0JIB3 H
Q07UM3 H
A0A066ZRQ5 H
S0G181 H
D3PAH1 H
Q4WHC6 H
A0AA94HTL8 H
D5ASL9 H
A0A4U1JNL6 H
M0MDP9 H
A0A653N397 H
A0A2S8GSU9 H
A0A097R891 H
A0A8H7U3I1 H
A0A1H1MB73 H
A0A016XDZ5 H
A0A1B9JHS5 H
D3PE53 H
A0A9J9BAE8 H
Q2RM12 H
A0A3N0AQL8 H
C5KTM6 H
M1P5F0 H
I1YG38 H
A0A660CH85 H
A0A2N7L7C8 H
Q5KZZ9 H
M1NZT5 H
A0A225CMT8 H
A0A068NV61 H
H2CJI0 H
B0DU93 H
Q221S8 H
F4Y3C5 H
Q94CJ2 H
M0D3Q9 H
A0A3P2A7W8 H
C0GKN4 H
Q7T3R4 H
A0A562USB9 H
A2SS52 H
A0A211ZGL5 H
A0A4V3ALP8 H
A0A147GP06 H
H2IZ00 H
Q45HK8 H
A0A6C8LST1 H
A0A257T8W6 H
Q5P470 H
I5AZQ4 H
Q07UM1 H
E5B358 H
A0A1Y4L5P0 H
Q3AFY9 H
B0BZN3 H
A0A1Q2C7H7 H
A0A4R5U5V1 H
H6LKX6 H
A0A1Y0UZX2 H
F6BEI0 H
M9RKT6 H
A7SGD4 H
A0A257TE48 H
R1FI09 H
E4N1T5 H
U1PIR6 H
F2JYR9 H
Q84KJ7 H
A0A2S8FTB5 H
D2R647 H
G9Y5B0 H
A0A144NLT9 H
A0A5J6WQU1 H
D2R355 H
F3ZYD6 H
B0SL05 H
A0A5A7MAJ9 H
A0A977NL43 H
A0A433ZQ80 H
A0A1Y0V4A5 H
A0A1M7UEG2 H
G8R7U9 H
K1LDP0 H
B7G0Y4 H
A0A2W4ZXC0 H
B3PF77 H
Q2KZK9 H
Q18ES8 H
D3F545 H
B4S394 H
Q1Q357 H
Q9H310 H
D3PKL4 H
M5SY07 H
Q8RUT6 H
A7NKH2 H
Q1Q879 H
A0A1B9M5B8 H
A6LRS5 H
J2ZGN6 H
V5E0F3 H
A0A149RQX0 H
A0A165BP25 H
C0QSY0 H
B0XVV6 H
E0SD83 H
A8HSA2 H
A0A1E3PSK5 H
A5DYQ2 H
A0A4U1K1W1 H
Q0AT01 H
A4FMG0 H
C3YB73 H
A0A9P3CXY2 H
A0A0L8BVU4 H
A0A401WUW1 H
I4C9L2 H
Q8RUE9 H
F0JGZ1 H
A0A2I0UUY1 H
A0A542XGT4 H
G0JRH4 H
A2SPS8 H
A0A5M4AWD2 H
Q6QH01 H
D3F0Z1 H
A6XBM2 H
D6E7B3 H
Q13E03 H
A0A060URB8 H
A0A2T1N7R1 H
D6TCH6 H
B0CXH8 H
A3TVQ9 H
Q4WT12 H
C7QGX3 H
F0Y9X3 H
A0A7S0D560 H
A0A160KTE9 H
A0A2H1HV86 H
A0A251Y3N4 H
A0A419AVL2 H
A0A4Q2QWS1 H
C7Q1E4 H
A0A5C5TYS5 H
F2NNQ0 H
A0A2R4TRE0 H
K9YJQ3 H
D9QS43 H
A7SQ16 H
A1DG05 H
U1SIR9 H
C4Y298 H
A0A9W3LFI9 H
D3RMV7 H
F3QNA7 H
E4RTK5 H
C8XBX8 H
C0QTA4 H
E6VIW4 H
A0A2S6H643 H
Q46HB1 H
A0A2S5CTX8 H
A0A1T4SF40 H
K0K7J4 H
A0A1J5JH24 H
Q6LMI6 H
A0A9W5JBA9 H
A0A291PMC6 H
A0A4Y4DZN4 H
A0A2R4MBA2 H
R9PI53 H
A0A6H9GLV4 H
A0A7S4GND2 H
A0A6H9FPY5 H
A0A1G7DX68 H
A0A075WEB4 H
A0A140NHJ5 H
A0A1C6Z081 H
Q5FA36 H
Q0ACK1 H
A0A975GIX9 H
A0A323UE08 H
U7VB41 H
A0A063Y780 H
C5CIT6 H
A0A0A2VPU3 H
F0RHS0 H
A0A2S5WX34 H
C1G973 H
A0A2S6GKF6 H
A0A0A2B651 H
A0A4R3A5P7 H
A0A2A7U6W1 H
Q2GX26 H
F5XN43 H
A0A0K2STH0 H
A0A1H1U2Q6 H
A7SED8 H
A0LV78 H
K5DBA0 H
B8IZX4 H
A8LKQ0 H
A0A5C6LWQ1 H

In [97]:
seqsn = []

for i in sn:
    print(i.id, i.seq)
    seqsn.append(i.seq)

A0A858ZNJ3 S
A0A1H9M798 S
B0DY50 S
P69680 S
A0A3G9G4Q4 S
A0A149UP06 S
F2G6G4 N
A0A2M9D7S8 S
A0A034WGQ2 N
I0KDC6 I
F8D7H6 N
K9W4V5 N
Q466Y3 N
D2SE15 S
A0A377PBY1 S
B1JZ69 S
A0A2W5HTC3 S
A8G2S3 N
D5T4N9 S
Q2RWY7 Q
A0A0E3R4G0 N
I4C9L0 S
D5VJ32 S
C0Z5S5 N
C1N6X9 N
J7ITF6 S
A0A068SVR1 S
A0A0D7F328 S
Q0G0A4 S
F0J3F9 S
Q0BQ69 S
F2YIC4 N
D4XLN6 S
A0A420WC79 N
A0A5C5TUT2 S
A0RUZ2 T
A0A0A2ZRL7 S
J4UGB7 S
E5Y678 V
A0A0D2KGN8 S
S5ABR8 N
A9DQM8 N
G5EB13 S
A0A2N6NEK4 S
C6DB68 S
Q81GN5 C
Q0F2M5 N
A0A0C6P439 S
B9SWW9 Q
L8H5K0 N
Q9NIV0 N
C1N5A7 N
Q1JXS5 S
A0A1M6JKY3 S
F4D1J0 S
A0A257SYX3 Q
V4RK08 S
G0V8D6 S
A0A7S4GMD8 N
B3QVV5 V
F2JZ83 N
A0A857DDJ7 S
A0A0S6UHP2 N
D5EP71 T
F4KY49 I
M5S9B4 N
A0A009PYN3 S
A0A3T0SZ22 S
A0A248LMH8 S
A0A6H9GEE4 N
A7HSP2 T
A0A7V8IKS6 S
T2JFS5 N
F6FRU9 S
A0A9E9L9J1 S
A0AIW5 S
A0A0E9NHV4 S
Q2N625 S
C8WSI9 A
A0A1H1BPD6 S
A0A176XNC5 S
A0A4V0XUI3 N
A7S3L2 T
M5U2P1 N
K9P5D1 T
Q0F2M7 S
A0A2R3IMJ8 S
Q2RVB5 S
A0A556RTU3 S
E0TGP9 N
B7G0Y1 N
A0A1G9P6Q0 N
D0LTW3 N
Q6BT62 T
Q2IK04 N
Q6BJI7 S
B7X047 S
A0A068NPW2 S
A0A399NT81 S
K0F9X7 S
A0A037ZMW1 N
A0A075JZ35 S
A0A369MHK2 T
A0A1B9JPL5 S
D8PD01 S
A0A2G5BI87 S
A0A2G5BGA9 S
A0A657K391 S
P69681 S
A0A4P6UIJ8 S
A0A0V8M0W6 T
A0A0H2XSU4 S
Q1Z695 N
A0A7Z0V0A4 S
K0ER80 S
A0A149UWF2 S
G0H0Z6 N
G0EFF3 S
C8WLL8 T
X5CNT2 Q
A0A4Y1MSE7 S
H2CLF7 N
M4VEJ9 V
A0A4V2X6C2 S
A0A2K1RA77 Q
A0A375YPN6 S
A0A7M6UUM4 N
A0A172YCA7 T
A0A918MJ52 N
A0A2S8QA29 S
A0A251XJT0 S
A0A0B4E6X7 S
A0A0K2STQ7 N
A1C5Z7 S
C9KKP2 S
A0A2Z4MD56 N
Q9VFA9 N
A0A502GPV4 S
I5C044 N
D2V6P8 N
D3RN22 N
Q97L80 T
A0A0D5YN10 S
A0A1I5GN22 S
A0A1Y5E8I7 N
B1Y8C9 S
M5SYZ1 N
Q6HM26 C
A0A379A0S9 N
A0A101DCS3 S
A0A1Y3U5V2 T
A0A202B535 S
F8E6R1 N
Q6ND36 S
A0A8H6K7L7 S
Q7NCB8 T
A0A369MRW6 T
C9RS76 N
A3U857 I
A0A127PIQ9 S
B8FGW0 S
A0A060JMP6 S
D5V7B3 N
A0A494JB70 I
A0A5M8QF12 S
A0A8G2F3G4 S
J7L3W8 S
G0JRG9 Q
D3DJN2 S
A0A1Y2JH43 S
Q1L727 N
A0A7T2S0Z6 S
A0A315S845 S
A0A2S6H6B7 T
A0A1J5NTP7 S
A0A0E3QY86 T
A0A096EEV9 S
A0A380S5X4 N
B8ZYW3 N
A0A2S8GEJ5 N
A0A248TDF2 N
B2GFN1 S
U1PPI7 N
C7LW88 N
G3A431 S
A0A066ZTE4 N
L7CG99 N
S0ET45 T
A0A178TA08 N
H1XV27 N
A0A6M3ZJI1 S
U5DEY6 N
H6LFQ2 N
Q6CRN0 S
A0A4Q2EAG7 S
A0A1J5NNB8 N
E3I393 S
A0A243SC06 I
D4F313 S
W0F0I7 I
A9B874 N
A1D2Y5 S
T2J0N1 N
Q2FQT3 S
A0A075WG29 N
A0A979GQ79 I
A0A381CAY8 S
A0A2G3DSU6 N
A0A168EVK8 S
A0A094W9G3 N
A0A4R3NVT3 N
W0DYY3 N
G8JTW0 S
A0A4P6UIK6 S
I9P003 N
G2T1Y3 N
B8EMQ8 S
I6Z905 N
E0TCV4 N
A3XNG6 N
A0A087MGU4 S
A2BUP4 N
A0A562S8V2 S
A0A495DND0 S
A0A0S2FHD7 S
F3QPR6 T
A0A063Y394 S
F6G5I9 S
A0A323UDG5 S
A0A0G9HEC5 S
B8FDY8 S
Q5KPM5 T
A0A147EQL9 S
A0A854Q6X9 S
C3X1J1 S
A0A5B2V3B9 S
A0A258FS85 S
A0A7T2W1B3 S
A0A060UN76 N
G0JRQ3 N
D5UD26 S
G2ZN72 S
A0AA46Q839 I
A5UJR1 S
L1INN6 N
C1F584 N
C5LAG4 N
A0A2A2MCP3 T
B1Y6V4 S
A0A1G6ABK5 N
A0A6A1TYJ4 S
A0A2T4UWF1 S
V4AP67 N
A0A173R3W6 T
C7NND3 N
B0DFJ4 S
A0A3E2VY88 N
R1EDV9 N
J1L5M8 S
D7G265 N
Q8ERT9 N
I4D6Z9 S
A0A4R6DFU8 S
A0A060URC3 Q
D2BIB2 T
F5ISF6 T
A5CRL2 S
A0A6G9XJV9 S
Q59UP8 M
A0A6N4SPH9 N
I0HGY4 S
X5DX97 N
L1J6I4 S
I1DSU5 N
B9L7N1 S
Q1Z4I4 N
Q21CP1 S
A0A165MFD1 N
V4CRP5 N
Q7S5K0 S
A0A071MMV1 S
A0A149RYW7 S
A0A7G5EC77 S
A0A1W2GZ82 N
A0A7U3XVQ4 S
A0A071M4L5 S
U5C2K4 N
A0A248LNW8 N
L8H844 N
A0A149V596 S
S9QZ09 S
B1ZSW9 S
D2BUJ8 S
A0A9Q8L398 S
M5S735 S
Q6ARH0 N
K6W5X0 S
G0JRG6 N
A0A6H9FYW4 S
A0A0S4WFM4 S
A0A101HKN9 N
Q9REX3 N
F0S3Z6 N
A8NAG3 S
C6LBD3 N
A0A149U2G9 S
V4REY8 N
A0A0H3H4I7 S
A8N2H6 S
S0APH6 V
A0A017SYR8 S
A0A1B9MZ78 S
E4T3F3 N
D7E934 N
A0A0M3AB44 S
A9WHW6 N
A0A5M4AUM9 T
A0A1X4GBG2 N
I4D1H5 S
A0A0E3QYF3 N
B0CQX4 S
A0A378YR15 S
A0A495D4X4 N
A0A076PL76 S
Q1YDY7 S
A0A3E2UCG9 N
A0A2K3DPU7 N
A0A3R9Q7C4 S
V5U2Z4 S
K9P718 N
M1V7W3 N
Q6LKC8 N
E5Y789 S
J9Z839 Q
A0A1G7VM92 S
K9Z0D3 S
A0A482TED1 N
R1EGK6 N
J1ASR8 S
A0A7U4E420 I
K9YR86 N
A8PXT8 S
A0A0U1NJW3 N
B8FL88 N
A2CCK1 N
D6TFE1 N
A0A2H4U5R1 S
I2GD40 I
A0A060HFT5 S
B1Y842 N
A0A0X8NXA9 S
A0A0A2A5X1 N
A0A318FY98 S
Q7V4T8 N
A0A1A0DHK0 S
C1A872 T
A0A395VB65 N
A7MFK3 S
J4KM12 S
A1SY01 N
A0A1H4DJ49 N
A0A9R0NTP8 S
A3PAY4 N
B4CV94 S
A2C095 N
Q2HD43 S
A0A836M2B6 S
H6RWK9 S
A0A087EQK8 T
A0A1I0AQM4 N
L7CG11 S
A0A248LNK5 V
B7FTM9 N
L0K9M1 N
I4D6Z7 T
A0A2K1RA81 Q
Q2WBF7 S
A0A1B9BUU6 Q
A0A2S0JW39 N
A0A2S5YID7 S
B3PIH2 T
U3P8G1 S
C9R9J0 S
A8AC17 S
F0YLV7 S
A0A1D3GAE9 S
C1MHX0 V
A0A1H4KAQ7 N
A0A2T4XZC1 S
A1B3N0 S
C7LW87 S
A1SZ12 N
A0A2T2Y0D5 S
A0A1H8D0R8 N
A0A2S5V2F6 T
G3IYW2 S
F5L8M7 N
C7BJG7 S
E4U5Z1 T
A0A1B9K8L2 S
A0A2S5WMT7 S
A0A0D2UPA8 I
A0A161SKF4 S
B4D7W2 S
A0A1H3WA00 S
C1D6X6 V
A0A4D6KHD1 N
Q488X2 N
A9V5W4 N
A0A5M4ATH9 I
E4TRS4 N
A0A011U1K7 S
C7R314 S
A0A077EFU9 I
A0A0A2A0Y9 N
A0A0D8BQX6 N
A0A0L0S493 T
A0A328Q6M1 T
A0A016XCG9 S
B7FSA7 N
G0AFH4 S
A0A177W826 S
A0A2S8GF54 N
Q1YDY8 N
Q5QVH2 N
A3ZT81 N
A0AA35XZV0 T
F4H924 S
K0NJH2 N
A0A1V3SSW1 N
F2AUF4 N
A6DN47 N
W8KM07 N
A0A1X3RP39 S
A0A7S0KKL8 N
A0A318QZ80 N
K8VZC6 S
A0A1B9JZS5 S
A0A2S6GKN5 T
A0A4R2Z2K6 S
H1YCC3 I
E1QIU3 N
A0A8H6MPB9 S
A0A369N7Y3 T
T2IEJ2 N
H5UND3 S
Q1PX09 N
A0A149TSA9 S
F2NGJ8 S
A0A0E3SHQ9 N
Q5FLR6 T
S0EUS1 N
A0A369M386 T
W0DZS7 T
A8MCL4 S
V3ZVE4 N
O26757 S
A0A317FZW2 N
A0A085GI50 S
A1ZGK6 N
G0IYI2 N
A7S731 T
A0A1U9YY82 N
A0A328EMN2 T
A0A8E2UDJ3 S
A0A2S5WUP6 T
A0A8H7P8U1 S
A0A257T7G4 Q
B3MX93 N
A0A1G5W0P2 T
D4H2Y7 N
A0A4P8HC89 S
Q7T070 N
F7NPQ3 S
B9SA70 Q
Q9M6N7 Q
I7ZHW3 S
F4XTK4 N
A4G1J2 S
G7WFX4 T
B8JBH5 S
D9QPC8 S
A0A4R7GKA0 S
R9PMC6 N
A0A0E3LMT4 N
A0A511NGC7 I
E4NS62 N
E4T3F7 T
M0D580 N
J7J5E7 S
B1XZU2 N
A0A366IE34 S
A0A6U2BIY7 N
Q9QXP0 N
A0A424WAH3 S
A0A410K1J5 N
L1IHZ8 S
I8TC71 S
A0A7U8C744 N
A8M670 S
A0A0S4VNK2 S
Q2SIR0 N
A0A5C4RNH5 S
A0A3E0X011 N
A0A0E3SP24 T
E1IF27 A
Q2YBP7 N
A0A2S5WZU0 S
A0A172YBR4 N
A0A0K2STK6 N
A0A2N6JV02 N
F0S0G1 S
A0A1C7EL50 N
Q18PF5 N
A0A1I0C958 N
A0AA35XVN2 S
L8GGA0 S
Q3AP28 S
D0MFE9 T
J9VXX9 S
A0A166IS52 N
F0J7D3 Q
W7QG13 N
A4BMY5 S
A6LV49 T
Q1H483 S
A6M3G0 T
E4T0A4 T
A0A3E2UHE6 N
A0A174SD65 T
A0A855EH99 S
C3YB74 N
A0A074KZD8 N
J0S2I0 N
K9WSX4 N
E8RLT5 S
Q2FS34 S
Q3Z7F9 T
Q2S8H9 N
A0A060HN92 N
E6ME92 T
A0A172RYW3 T
L0FU80 N
C8WZE0 N
A0A2S8F4W0 N
A0A2C6C0X3 S
F3ZVV4 S
A0A7R6PER3 N
A0A495WJM6 I
A0A0B4DUR9 N
A0A251YU48 S
A5D4I5 S
A0A2X2C038 S
A0A2A2M8K7 S
D3FBG3 T
A0A2V4EA49 S
D0MFE8 N
Q3B6Q2 S
A0A1B9KID3 S
A0A9J9ES23 N
A0A3N2SFS2 S
Q0VLH1 N
A0A1U9Z147 V
Q0G2T1 S
A6GJF5 N
A0A059XXR1 Q
A0A5J6WPP9 N
P41948 S
L1IUV5 S
A0A2W0GQV0 S
Q1K433 F
A0A4Y7XC43 S
D5AU98 T
E1QFA8 T
A0A075WBP9 S
Q0BWD0 N
A0A1Y0HX98 S
A0A098S5Y7 N
Q0I445 S
A0A1E5BXA4 N
A0A2C9CK98 T
G4H971 N
A0A1I0BYN1 I
A0A330GB00 S
A0A2S8FR08 S
Q84KJ6 Q
A0A2S5WGI8 T
M2ALH9 N
A0A2K3DQF8 N
A0A8G2IZM3 S
F5Y3C1 S
A0A370FPU0 S
F5RGM7 S
A0A4R4K1P9 S
R8VWI7 N
A0A0A2AMW2 N
Q7Z1M1 N
A0A414NWT8 S
A0A0P6VSR8 S
A0A0L0TDW1 S
U3PCH5 C
W7QGE0 T
C5BWX7 S
A0A1B9M1A9 S
B8GGC3 T
D6SPD1 N
A0A0H3DR67 S
A0A4R7VEK0 S
G4R7P1 N
A0A1M5ZVP9 N
A0A2S5Y0D3 S
I0ICG0 N
D0L8H3 T
A0A1B9LFW3 S
Q6ND34 S
A0A6H9GWG4 N
Q5UZ98 N
A0A2S0P9T4 S
H2CDR5 N
T2KGT3 N
A0A088E6Q7 N
A0A258HS77 S
E1V4T3 N
B7GKP4 N
Q9QUT0 N
I3Z3H7 N
G7WCB6 S
A0A1Y6GLJ1 S
A0A0S2DQB6 S
Q6CRN1 S
A0A401X433 S
A7HT14 N
A0A009TDB1 S
D4XSW0 N
B0SRS8 N
A0A149QSR6 S
B1Y0E5 S
Q7UGU7 N
A0A2S0Q8P1 N
F0ZPL3 N
A0A2T0GTU1 S
I4CCD1 S
A0A9Q6P4A5 S
A0A418VIJ8 S
C1MX19 T
A0A1B9BUZ8 S
K9W6F3 S
Q1K8A3 S
L8GFX3 S
A0A1G6ABL9 S
A0A087L0B9 S
A0A073CP02 N
A0A0A1ZJU5 N
A0A258HPP1 S
A0A149QAW7 S
D2V6Q5 N
A0A1X4G8K1 T
A0A067Z3S3 S
A0A8F5ZDT8 S
A0A854QN45 T
A0A2N7LCD7 N
G7WFX2 M
A0A7S4GNJ2 N
A4G0C5 N
A6VE60 S
A0A1S1HM83 T
A0A037ZJY5 T
N1WR17 N
Q2W5V2 N
A1VIM5 S
A0A1Y5E3E3 T
A0A1T4SFK4 S
A7RNC3 V
M7XJ51 N
A0A399T909 S
A0A2N6P374 S
H8L2Q4 S
D5EP68 N
E6SF19 S
A0A1T4SFY6 S
D3LBI0 N
E6W5C1 N
Q0VPH4 N
K9WT03 T
L0KW14 S
A0A4R8H081 N
A0A1B9N3H7 S
B0RC35 S
A0A420KGW4 S
A0A4R3NLV5 S
Q47K18 S
Q21P82 N
M1WRK6 S
A0A290XBB5 S
A0A6T9XUR2 N
A0A1J1JH03 N
I3R0S7 N
A9UR54 N
A0A1G7H8X3 T
A0A8G2F718 N
Q1H0G2 N
D0LAL7 S
C7LQR9 N
A0A1G5PWV0 S
K1K628 S
B9SXC7 Q
G7WA28 S
Q1IWN6 T
H6LKH9 T
A0A1H7CU41 S
G8JUJ2 S
A0A081N2G5 N
A0A074ME37 S
Q0VQH6 T
C8XB51 S
A1VIG8 S
Q8GQS1 S
A0A1I7FBM5 N
A0A1M6ZMI3 N
A0A482PLH3 S
A0RXK8 T
D0KXQ0 N
Q8JI14 N
A0A7T4WEP4 Q
A0A4R3ZNW3 S
A0A074KY88 N
A0A6M3ZKU5 N
M1SJL5 S
A0A1W9KSU5 S
E3GI40 M
A0A369NYJ2 T
A0AA92K392 S
O04161 N
A9BQZ4 S
A0A6N2Z556 N
A0A8H6NAG3 S
A0A2T9X1V4 S
Q2J376 S
A0A0F5EZP7 S
A0A7G5DK18 S
M9YAI9 S
D2ZRW2 S
G7UUY6 S
A0A8H4GS02 S
A0A2T5IHP0 N
A0A165MAC2 S
A0A7S4LPS8 N
A0A075JIN0 S
C8X554 S
B8FZP7 S
Q5KAF6 S
A0A427KNL6 S
A0A7G5DPV0 S
Q22947 N
A0A1S1HRJ0 S
A0A3N1VXY4 S
A0A2S7YPJ9 S
I0JI83 N
A0A7U3YMN6 S
Q9BLG3 N
A0A1H9RTW8 S
A0A1I4W3A0 S
A0A0B4M163 N
U2EN72 N
A0A2W5VAZ2 S
E4YA63 D
D5ELM4 N
M9RJS5 T
A0A2G3E8V2 N
Q5FSX6 S
I0HKQ8 S
A0A833H2R7 N
B8ENL9 S
B3DUX7 T
A0A1D8UWJ6 S
D5E995 N
A0A7U8C2Y6 N
L0KGR8 S
B0VMH1 S
P40260 S
L0JT30 N
C1GR74 S
A0A423Y4I6 S
A0A4P7UHQ5 S
A0A8E2R1Y5 S
I5BYV5 N
A0A6B8N021 S
A0A7G5DPV1 N
A0A2G5RQK9 N
A0A5M4B0G1 T
A0A6S5K4J1 S
C1D4X0 S
A1SVA8 N
H1YF74 N
A0A8B4RWH8 S
A0A0A0D6K5 S
A0A0A2BBY0 N
A0A089ZBW5 S
A0A068TC78 S
Q46G49 T
A1CQ21 S
A0A1G6ABX1 N
E1SLM7 N
K5CFE5 S
Q2YLQ6 S
Q0G2V0 S
A4ABK3 N
A0A9Q5QVI9 T
A0A4Q7Y9I7 S
A9HMD6 S
K9YN27 N
Q9UBD6 N
D9SI59 S
Q8I0L6 N
A0A142VAD6 T
G3IYW0 T
A0A062IU58 S
R1D1H4 N
A0A366XFS8 T
A0A7S4GNF3 N
F0J6E8 S
A0A7U4DN04 S
V4RHR4 S
F7ZJM0 N
A0A2S5XAB8 S
U5C4L4 N
Q21J04 T
A0A142NNN1 S
H1Y7T6 I
F5R974 N
B0DU91 S
A2BP62 N
A7HSN9 N
A0A377I7W9 S
D2RU19 N
G7WJN0 N
E2SD33 S
A0A0D7F2Y9 S
A0AA92EGF5 S
A0A9E9LXV9 S
A4BEP1 N
A0A0E3WZH5 N
F7ZEU9 N
A5E3X2 T
A0A0A3XTJ3 S
A0A830ZZN8 S
A0A1S8D478 S
J7IVQ1 N
A0A2U1SS17 S
S3K1S2 S
C6XKC2 N
A0A2S7YIM5 S
K2IMJ7 N
Q5P1S8 N
A0A7T5BFQ2 N
A0A556SRH6 S
A8P923 S
A0A7G5DKA9 N
L8JUH3 N
A0A0D2LEF5 S
A0A258FTB0 S
A0A5P9P1L2 N
M8E0R3 N
A0A6J5IRX5 S
W5WIX6 S
Q82X47 N
I4DBY0 S
A0A6F8TLE9 S
A0A1G7UZX2 N
A0A6P4JM51 N
G0J614 N
U2WTW8 N
A0A642KQG8 N
Q1AUG3 N
A0A6G9Y3Q0 S
B8J5X4 N
M7NFH3 N
A0A0E3R6S1 T
Q2IHY5 S
A7I8Z2 S
L1IYP4 S
B4HDZ9 N
A0A366WYI9 N
E4TJ50 S
A0A7S0ILH2 V
A4BAE1 N
B3QRJ4 S
A0A5C5BWI6 T
Q7NQY2 S
A0A091AXI3 S
Q1QSQ2 N
R4FZE3 N
A0A2N0MZ27 S
A9BTK1 S
A0A242NIL1 S
G0LFE3 N
A0A1B9NQ91 S
A0A5M5PZE2 N
A0A0D2NYP3 S
D9QPE5 S
I5B3H0 N
L1IYW7 S
C6WEW7 S
B7FW68 N
F4GED5 S
A0A4R8GSH7 N
A0A1W2H3F0 N
A0A3E2T713 N
A0A0H3KTD3 S
A0A1Y4LM49 N
G2PRJ6 N
A0A0X8X7Y7 N
K8EJ02 T
A0A1L3F1X5 S
G8TK77 I
A0A855F5Y8 S
A0A975BTN0 S
A0A562RGZ4 N
G5EB09 S
A0A833LX85 N
U1H1F7 S
K8W1E2 S
E3HJW8 S
Q7SEH0 S
Q47X17 T
B0DXT9 S
A0A3G9G2C9 S
Q95P70 N
A0A837C6X5 S
Q89WR5 S
A6DUG4 N
D7UQE2 N
A0A2I1M481 S
A0A0T7GZ59 S
O66395 S
J3EXK0 N
A0A1B9MYL7 S
K9U8C7 N
E2SD44 S
H6LKH6 T
Q605Y6 S
A0A9Q9D9I3 S
A0A6N2TIA4 N
A0A1E3PQH0 S
A4CMI3 N
Q1K0H9 N
A0A0S6UEK9 S
A0A0H3LUA3 S
B9LU00 N
A9BIZ7 N
A0A7H8UK07 S
E3H8C9 N
M2A398 S
Q1QS12 S
G0VI62 S
A0A1Z3MS36 S
A0A0B5FNH4 N
D9SI36 N
A0A410JZR4 S
F7ZJZ1 S
F0ZCX7 N
W0DZX1 N
A0A4R3ZZ35 S
A0A317G0I6 N
Q0ARJ4 S
A7I8Z4 S
T2KJ59 N
I3C0V3 N
E3H8A6 N
B2IJT1 S
A0A2G6JLT9 N
A3ZZL7 S
A0A2T0XPP2 N
Q31CR9 N
A0A1R1IDV3 S
K2JVF8 N
V5BYZ7 S
D8J4C6 N
D4H5F9 N
K9ZG59 T
A0AA86YS65 S
Q608B6 N
A0A562BXM4 S
A0A401WXG0 S
A0A857DMN9 S
A0A1X6N3Q5 S
A0A173R3X4 N
Q63EK5 C
K9ZLY2 N
A0A533I6R2 S
I0WJ97 N
K0N2R5 S
M0J579 N
B8GGC1 S
A0A6H9GFU4 S
C6CBB1 S
A0A510HHK8 N
A0A1B9MBX6 S
A0A9Y2AG30 S
E8RSE4 S
F2B2B8 S
Q7UYZ3 S
I1YJH7 N
A0A853MG28 N
A0A0L0STS6 T
A0A251XU71 S
Q60BI2 T
A0A829X098 S
F3KUN4 S
Q60C43 T
A0A0T7FAP8 S
A0A3E2TW06 N
W0E077 N
A0KPE9 S
R7PZ71 S
A0A0A1ZMZ9 N
A0AA40J491 S
D3S2L0 T
A0A373FQ71 S
A0A0A2C6L1 N
Q7W7D3 S
A0A165K0X5 N
A0A2S5X482 S
R9GM11 I
Q0G0A3 N
D4GLQ6 S
E7RJZ0 N
F8IJE0 A
A0A1V2XMU9 S
Q7TNN9 N
A0A1G5RZU9 N
A0A2N6K4Y5 T
B0SLB7 S
A0A251YFS0 S
B9WDK0 S
Q7N0M6 S
A0A0M2LU39 S
F4B548 S
D6Z5V9 N
A0A4R2M206 S
A0A1E2SKM1 C
A0A127JTU2 S
A0A212AV03 S
G4QHD2 N
A0A021VMC6 S
A0A2J7TJ33 S
G7WDB5 N
Q6BK68 S
Q1K3N8 N
A0AA91Q161 S
A0NJ07 N
A0A316BQ38 S
A0A377PLP5 S
W7QGM4 N
A0A015YIP3 N
A0A060UWC8 N
A0A1I4ZIZ6 S
A0A264VQM8 S
A9AUR8 A
A0A1W5PRD1 N
A0A0E3BR91 S
A0A1B0ZRL8 N
B9ACS5 S
Q92BJ7 S
F2JTN3 N
A1AVV2 T
D2Q0J8 S
A0A3S9N9F3 S
A8ZQD5 N
C3X831 S
A0A1M6BPM0 S
A0A8F5VN39 S
A0A1E5C7W4 N
A0A2S5WV24 S
A0A833GZR2 N
C7M2A9 N
A6W7U2 S
W0JIB3 N
Q07UM3 S
A0A066ZRQ5 N
S0G181 N
D3PAH1 S
Q4WHC6 S
A0AA94HTL8 S
D5ASL9 S
A0A4U1JNL6 T
M0MDP9 N
A0A653N397 S
A0A2S8GSU9 S
A0A097R891 S
A0A8H7U3I1 S
A0A1H1MB73 S
A0A016XDZ5 S
A0A1B9JHS5 S
D3PE53 S
A0A9J9BAE8 N
Q2RM12 S
A0A3N0AQL8 T
C5KTM6 N
M1P5F0 N
I1YG38 N
A0A660CH85 S
A0A2N7L7C8 N
Q5KZZ9 N
M1NZT5 N
A0A225CMT8 S
A0A068NV61 N
H2CJI0 N
B0DU93 S
Q221S8 S
F4Y3C5 N
Q94CJ2 N
M0D3Q9 N
A0A3P2A7W8 S
C0GKN4 N
Q7T3R4 N
A0A562USB9 N
A2SS52 S
A0A211ZGL5 S
A0A4V3ALP8 S
A0A147GP06 S
H2IZ00 S
Q45HK8 S
A0A6C8LST1 S
A0A257T8W6 N
Q5P470 S
I5AZQ4 S
Q07UM1 S
E5B358 S
A0A1Y4L5P0 N
Q3AFY9 T
B0BZN3 N
A0A1Q2C7H7 T
A0A4R5U5V1 S
H6LKX6 N
A0A1Y0UZX2 S
F6BEI0 N
M9RKT6 N
A7SGD4 R
A0A257TE48 N
R1FI09 N
E4N1T5 S
U1PIR6 N
F2JYR9 S
Q84KJ7 Q
A0A2S8FTB5 N
D2R647 N
G9Y5B0 S
A0A144NLT9 S
A0A5J6WQU1 N
D2R355 S
F3ZYD6 N
B0SL05 N
A0A5A7MAJ9 S
A0A977NL43 S
A0A433ZQ80 S
A0A1Y0V4A5 S
A0A1M7UEG2 S
G8R7U9 I
K1LDP0 N
B7G0Y4 N
A0A2W4ZXC0 V
B3PF77 N
Q2KZK9 S
Q18ES8 N
D3F545 N
B4S394 S
Q1Q357 T
Q9H310 N
D3PKL4 T
M5SY07 S
Q8RUT6 N
A7NKH2 N
Q1Q879 N
A0A1B9M5B8 S
A6LRS5 S
J2ZGN6 N
V5E0F3 T
A0A149RQX0 S
A0A165BP25 S
C0QSY0 S
B0XVV6 S
E0SD83 S
A8HSA2 N
A0A1E3PSK5 S
A5DYQ2 S
A0A4U1K1W1 T
Q0AT01 N
A4FMG0 S
C3YB73 N
A0A9P3CXY2 S
A0A0L8BVU4 S
A0A401WUW1 S
I4C9L2 S
Q8RUE9 N
F0JGZ1 S
A0A2I0UUY1 N
A0A542XGT4 S
G0JRH4 S
A2SPS8 S
A0A5M4AWD2 N
Q6QH01 N
D3F0Z1 N
A6XBM2 N
D6E7B3 T
Q13E03 S
A0A060URB8 S
A0A2T1N7R1 N
D6TCH6 T
B0CXH8 S
A3TVQ9 N
Q4WT12 S
C7QGX3 S
F0Y9X3 N
A0A7S0D560 T
A0A160KTE9 S
A0A2H1HV86 S
A0A251Y3N4 S
A0A419AVL2 S
A0A4Q2QWS1 S
C7Q1E4 S
A0A5C5TYS5 S
F2NNQ0 T
A0A2R4TRE0 S
K9YJQ3 N
D9QS43 N
A7SQ16 T
A1DG05 S
U1SIR9 S
C4Y298 S
A0A9W3LFI9 S
D3RMV7 T
F3QNA7 S
E4RTK5 I
C8XBX8 S
C0QTA4 T
E6VIW4 S
A0A2S6H643 S
Q46HB1 N
A0A2S5CTX8 N
A0A1T4SF40 S
K0K7J4 S
A0A1J5JH24 S
Q6LMI6 N
A0A9W5JBA9 S
A0A291PMC6 S
A0A4Y4DZN4 S
A0A2R4MBA2 T
R9PI53 N
A0A6H9GLV4 N
A0A7S4GND2 N
A0A6H9FPY5 N
A0A1G7DX68 S
A0A075WEB4 S
A0A140NHJ5 S
A0A1C6Z081 S
Q5FA36 S
Q0ACK1 N
A0A975GIX9 S
A0A323UE08 S
U7VB41 V
A0A063Y780 N
C5CIT6 T
A0A0A2VPU3 S
F0RHS0 N
A0A2S5WX34 S
C1G973 S
A0A2S6GKF6 S
A0A0A2B651 N
A0A4R3A5P7 S
A0A2A7U6W1 S
Q2GX26 S
F5XN43 S
A0A0K2STH0 N
A0A1H1U2Q6 S
A7SED8 N
A0LV78 S
K5DBA0 N
B8IZX4 S
A8LKQ0 N
A0A5C6LWQ1 I

In [98]:
df = pd.DataFrame(idid)

In [99]:
df['E'] = seqe
df['N'] = seqn
df['D'] = seqd
df['T'] = seqt
df['F'] = seqf
df['S'] = seqs
df['f1'] = seqf1
df['f2'] = seqf2
df['h1'] = seqh1
df['h2'] = seqh2
df['sn'] = seqsn

In [136]:
df['edg'] = seqedg

In [100]:
df2 = pd.DataFrame(df[0])

In [101]:
df2['four'] = df['E'].astype(str) + df['N'].astype(str) + df['D'].astype(str)+ df['F'].astype(str)+ df['T'].astype(str)+ df['S'].astype(str)

In [102]:
df2['first'] = df['E'].astype(str)

In [103]:
df2['PheGate'] = df['f1'].astype(str) + df['f2'].astype(str)

In [104]:
df2['TwinHis'] = df['h1'].astype(str) + df['h2'].astype(str)

In [105]:
df2['SN'] = df['sn'].astype(str)

In [137]:
df2['EDG'] = df['edg'].astype(str)

In [82]:
u = UniProt(verbose=False)

In [83]:
linige = []
for item in tqdm(idid):
    lineage = u.search(item, columns='lineage')
    print(item)
    print(lineage.split(',')[1])
    finige = f"{item}:{lineage.split(',')[1]}" 
    linige.append(finige)

  0%|▏                                                                                                                                          | 2/1281 [00:00<04:13,  5.04it/s]

A0A858ZNJ3
 Bacteria (superkingdom)
A0A1H9M798
 Bacteria (superkingdom)

  0%|▍                                                                                                                                          | 4/1281 [00:00<04:27,  4.78it/s]

B0DY50
 Eukaryota (superkingdom)
P69680
 Bacteria (superkingdom)

  0%|▋                                                                                                                                          | 6/1281 [00:01<04:19,  4.92it/s]

A0A3G9G4Q4
 Bacteria (superkingdom)
A0A149UP06
 Bacteria (superkingdom)

  1%|▊                                                                                                                                          | 8/1281 [00:01<04:11,  5.07it/s]

F2G6G4
 Bacteria (superkingdom)
A0A2M9D7S8
 Bacteria (superkingdom)

  1%|█                                                                                                                                         | 10/1281 [00:02<04:13,  5.01it/s]

A0A034WGQ2
 Eukaryota (superkingdom)
I0KDC6
 Bacteria (superkingdom)

  1%|█▎                                                                                                                                        | 12/1281 [00:02<04:13,  5.00it/s]

F8D7H6
 Archaea (superkingdom)
K9W4V5
 Bacteria (superkingdom)

  1%|█▌                                                                                                                                        | 14/1281 [00:02<04:21,  4.85it/s]

Q466Y3
 Archaea (superkingdom)
D2SE15
 Bacteria (superkingdom)

  1%|█▌                                                                                                                                        | 15/1281 [00:03<04:31,  4.67it/s]

A0A377PBY1
 Bacteria (superkingdom)

  1%|█▊                                                                                                                                        | 17/1281 [00:03<04:19,  4.88it/s]

B1JZ69
 Bacteria (superkingdom)
A0A2W5HTC3
 Bacteria (superkingdom)

  1%|██                                                                                                                                        | 19/1281 [00:04<04:21,  4.83it/s]

A8G2S3
 Bacteria (superkingdom)
D5T4N9
 Bacteria (superkingdom)

  2%|██▎                                                                                                                                       | 21/1281 [00:04<04:12,  4.98it/s]

Q2RWY7
 Bacteria (superkingdom)
A0A0E3R4G0
 Archaea (superkingdom)

  2%|██▍                                                                                                                                       | 23/1281 [00:04<04:18,  4.86it/s]

I4C9L0
 Bacteria (superkingdom)
D5VJ32
 Bacteria (superkingdom)

  2%|██▋                                                                                                                                       | 25/1281 [00:05<04:20,  4.83it/s]

C0Z5S5
 Bacteria (superkingdom)
C1N6X9
 Eukaryota (superkingdom)

  2%|██▉                                                                                                                                       | 27/1281 [00:05<04:10,  5.01it/s]

J7ITF6
 Bacteria (superkingdom)
A0A068SVR1
 Bacteria (superkingdom)

  2%|███                                                                                                                                       | 29/1281 [00:06<04:15,  4.90it/s]

A0A0D7F328
 Bacteria (superkingdom)
Q0G0A4
 Bacteria (superkingdom)

  2%|███▎                                                                                                                                      | 31/1281 [00:06<04:12,  4.94it/s]

F0J3F9
 Bacteria (superkingdom)
Q0BQ69
 Bacteria (superkingdom)

  3%|███▌                                                                                                                                      | 33/1281 [00:06<04:07,  5.05it/s]

F2YIC4
 Eukaryota (superkingdom)
D4XLN6
 Bacteria (superkingdom)

  3%|███▊                                                                                                                                      | 35/1281 [00:07<04:03,  5.11it/s]

A0A420WC79
 Bacteria (superkingdom)
A0A5C5TUT2
 Bacteria (superkingdom)

  3%|███▉                                                                                                                                      | 36/1281 [00:07<04:45,  4.36it/s]

A0RUZ2
 Archaea (superkingdom)
A0A0A2ZRL7
 Bacteria (superkingdom)

  3%|████▏                                                                                                                                     | 39/1281 [00:08<04:07,  5.02it/s]

J4UGB7
 Eukaryota (superkingdom)
E5Y678
 Bacteria (superkingdom)

  3%|████▍                                                                                                                                     | 41/1281 [00:08<04:16,  4.83it/s]

A0A0D2KGN8
 Eukaryota (superkingdom)
S5ABR8
 Bacteria (superkingdom)

  3%|████▌                                                                                                                                     | 42/1281 [00:08<04:25,  4.67it/s]

A9DQM8
 Bacteria (superkingdom)

  3%|████▋                                                                                                                                     | 43/1281 [00:09<04:21,  4.73it/s]

G5EB13
 Eukaryota (superkingdom)

  3%|████▋                                                                                                                                     | 44/1281 [00:09<04:18,  4.78it/s]

A0A2N6NEK4
 Eukaryota (superkingdom)

  4%|████▉                                                                                                                                     | 46/1281 [00:09<04:12,  4.89it/s]

C6DB68
 Bacteria (superkingdom)
Q81GN5
 Bacteria (superkingdom)

  4%|█████▏                                                                                                                                    | 48/1281 [00:10<04:01,  5.10it/s]

Q0F2M5
 Bacteria (superkingdom)
A0A0C6P439
 Bacteria (superkingdom)

  4%|█████▍                                                                                                                                    | 50/1281 [00:10<04:08,  4.96it/s]

B9SWW9
 Eukaryota (superkingdom)
L8H5K0
 Eukaryota (superkingdom)

  4%|█████▌                                                                                                                                    | 52/1281 [00:10<04:16,  4.78it/s]

Q9NIV0
 Eukaryota (superkingdom)
C1N5A7
 Eukaryota (superkingdom)

  4%|█████▋                                                                                                                                    | 53/1281 [00:11<04:12,  4.85it/s]

Q1JXS5
 Bacteria (superkingdom)

  4%|█████▊                                                                                                                                    | 54/1281 [00:11<04:12,  4.87it/s]

A0A1M6JKY3
 Bacteria (superkingdom)

  4%|██████                                                                                                                                    | 56/1281 [00:11<04:04,  5.01it/s]

F4D1J0
 Bacteria (superkingdom)
A0A257SYX3
 Bacteria (superkingdom)

  5%|██████▏                                                                                                                                   | 58/1281 [00:12<04:07,  4.94it/s]

V4RK08
 Bacteria (superkingdom)
G0V8D6
 Eukaryota (superkingdom)

  5%|██████▍                                                                                                                                   | 60/1281 [00:12<03:57,  5.15it/s]

A0A7S4GMD8
 Eukaryota (superkingdom)
B3QVV5
 Bacteria (superkingdom)

  5%|██████▌                                                                                                                                   | 61/1281 [00:12<04:37,  4.40it/s]

F2JZ83
 Bacteria (superkingdom)
A0A857DDJ7
 Bacteria (superkingdom)

  5%|██████▉                                                                                                                                   | 64/1281 [00:13<03:56,  5.14it/s]

A0A0S6UHP2
 Bacteria (superkingdom)
D5EP71
 Bacteria (superkingdom)

  5%|███████                                                                                                                                   | 66/1281 [00:13<04:03,  4.99it/s]

F4KY49
 Bacteria (superkingdom)
M5S9B4
 Bacteria (superkingdom)

  5%|███████▎                                                                                                                                  | 68/1281 [00:14<04:00,  5.05it/s]

A0A009PYN3
 Bacteria (superkingdom)
A0A3T0SZ22
 Bacteria (superkingdom)

  5%|███████▌                                                                                                                                  | 70/1281 [00:14<03:56,  5.11it/s]

A0A248LMH8
 Bacteria (superkingdom)
A0A6H9GEE4
 Bacteria (superkingdom)

  6%|███████▋                                                                                                                                  | 71/1281 [00:14<04:35,  4.39it/s]

A7HSP2
 Bacteria (superkingdom)
A0A7V8IKS6
 Bacteria (superkingdom)

  6%|███████▊                                                                                                                                  | 73/1281 [00:15<04:30,  4.46it/s]

T2JFS5
 Bacteria (superkingdom)
F6FRU9
 Bacteria (superkingdom)

  6%|████████▏                                                                                                                                 | 76/1281 [00:15<03:52,  5.19it/s]

A0A9E9L9J1
 Bacteria (superkingdom)
A0AIW5
 Bacteria (superkingdom)

  6%|████████▍                                                                                                                                 | 78/1281 [00:16<03:57,  5.07it/s]

A0A0E9NHV4
 Eukaryota (superkingdom)
Q2N625
 Bacteria (superkingdom)

  6%|████████▌                                                                                                                                 | 80/1281 [00:16<03:51,  5.19it/s]

C8WSI9
 Bacteria (superkingdom)
A0A1H1BPD6
 Bacteria (superkingdom)

  6%|████████▊                                                                                                                                 | 82/1281 [00:17<03:46,  5.29it/s]

A0A176XNC5
 Bacteria (superkingdom)
A0A4V0XUI3
 Bacteria (superkingdom)

  7%|█████████                                                                                                                                 | 84/1281 [00:17<03:56,  5.06it/s]

A7S3L2
 Eukaryota (superkingdom)
M5U2P1
 Bacteria (superkingdom)

  7%|█████████▏                                                                                                                                | 85/1281 [00:17<04:43,  4.22it/s]

K9P5D1
 Bacteria (superkingdom)
Q0F2M7
 Bacteria (superkingdom)

  7%|█████████▍                                                                                                                                | 88/1281 [00:18<03:54,  5.09it/s]

A0A2R3IMJ8
 Bacteria (superkingdom)
Q2RVB5
 Bacteria (superkingdom)

  7%|█████████▋                                                                                                                                | 90/1281 [00:18<03:51,  5.15it/s]

A0A556RTU3
 Bacteria (superkingdom)
E0TGP9
 Bacteria (superkingdom)

  7%|█████████▊                                                                                                                                | 91/1281 [00:19<04:31,  4.38it/s]

B7G0Y1
 Eukaryota (superkingdom)
A0A1G9P6Q0
 Bacteria (superkingdom)

  7%|██████████                                                                                                                                | 93/1281 [00:19<04:26,  4.46it/s]

D0LTW3
 Bacteria (superkingdom)
Q6BT62
 Eukaryota (superkingdom)

  7%|██████████▏                                                                                                                               | 95/1281 [00:20<04:21,  4.54it/s]

Q2IK04
 Bacteria (superkingdom)
Q6BJI7
 Eukaryota (superkingdom)

  8%|██████████▍                                                                                                                               | 97/1281 [00:20<04:27,  4.43it/s]

B7X047
 Bacteria (superkingdom)
A0A068NPW2
 Bacteria (superkingdom)

  8%|██████████▋                                                                                                                              | 100/1281 [00:21<04:06,  4.79it/s]

A0A399NT81
 Bacteria (superkingdom)
K0F9X7
 Bacteria (superkingdom)

  8%|██████████▊                                                                                                                              | 101/1281 [00:21<04:30,  4.37it/s]

A0A037ZMW1
 Bacteria (superkingdom)
A0A075JZ35
 Bacteria (superkingdom)

  8%|███████████                                                                                                                              | 103/1281 [00:21<04:17,  4.57it/s]

A0A369MHK2
 Bacteria (superkingdom)
A0A1B9JPL5
 Bacteria (superkingdom)

  8%|███████████▏                                                                                                                             | 105/1281 [00:22<04:20,  4.51it/s]

D8PD01
 Bacteria (superkingdom)
A0A2G5BI87
 Eukaryota (superkingdom)

  8%|███████████▍                                                                                                                             | 107/1281 [00:22<04:14,  4.62it/s]

A0A2G5BGA9
 Eukaryota (superkingdom)
A0A657K391
 Bacteria (superkingdom)

  9%|███████████▋                                                                                                                             | 109/1281 [00:23<04:18,  4.53it/s]

P69681
 Bacteria (superkingdom)
A0A4P6UIJ8
 Bacteria (superkingdom)

  9%|███████████▊                                                                                                                             | 111/1281 [00:23<04:13,  4.61it/s]

A0A0V8M0W6
 Bacteria (superkingdom)
A0A0H2XSU4
 Bacteria (superkingdom)

  9%|████████████                                                                                                                             | 113/1281 [00:24<04:18,  4.52it/s]

Q1Z695
 Bacteria (superkingdom)
A0A7Z0V0A4
 Bacteria (superkingdom)

  9%|████████████▎                                                                                                                            | 115/1281 [00:24<04:17,  4.52it/s]

K0ER80
 Bacteria (superkingdom)
A0A149UWF2
 Bacteria (superkingdom)

  9%|████████████▌                                                                                                                            | 118/1281 [00:25<03:56,  4.91it/s]

G0H0Z6
 Archaea (superkingdom)
G0EFF3
 Archaea (superkingdom)

  9%|████████████▊                                                                                                                            | 120/1281 [00:25<03:56,  4.90it/s]

C8WLL8
 Bacteria (superkingdom)
X5CNT2
 Eukaryota (superkingdom)

 10%|█████████████                                                                                                                            | 122/1281 [00:25<04:02,  4.79it/s]

A0A4Y1MSE7
 Bacteria (superkingdom)
H2CLF7
 Bacteria (superkingdom)

 10%|█████████████▎                                                                                                                           | 124/1281 [00:26<03:52,  4.98it/s]

M4VEJ9
 Bacteria (superkingdom)
A0A4V2X6C2
 Bacteria (superkingdom)

 10%|█████████████▍                                                                                                                           | 126/1281 [00:26<03:48,  5.06it/s]

A0A2K1RA77
 Eukaryota (superkingdom)
A0A375YPN6
 Bacteria (superkingdom)

 10%|█████████████▋                                                                                                                           | 128/1281 [00:27<03:44,  5.14it/s]

A0A7M6UUM4
 Eukaryota (superkingdom)
A0A172YCA7
 Bacteria (superkingdom)

 10%|█████████████▉                                                                                                                           | 130/1281 [00:27<03:46,  5.08it/s]

A0A918MJ52
 Bacteria (superkingdom)
A0A2S8QA29
 Bacteria (superkingdom)

 10%|██████████████                                                                                                                           | 132/1281 [00:27<03:44,  5.12it/s]

A0A251XJT0
 Bacteria (superkingdom)
A0A0B4E6X7
 Bacteria (superkingdom)

 10%|██████████████▏                                                                                                                          | 133/1281 [00:28<03:58,  4.82it/s]

A0A0K2STQ7
 Eukaryota (superkingdom)

 10%|██████████████▎                                                                                                                          | 134/1281 [00:28<04:03,  4.72it/s]

A1C5Z7
 Eukaryota (superkingdom)

 11%|██████████████▌                                                                                                                          | 136/1281 [00:28<03:54,  4.89it/s]

C9KKP2
 Bacteria (superkingdom)
A0A2Z4MD56
 Bacteria (superkingdom)

 11%|██████████████▊                                                                                                                          | 138/1281 [00:29<03:46,  5.06it/s]

Q9VFA9
 Eukaryota (superkingdom)
A0A502GPV4
 Bacteria (superkingdom)

 11%|██████████████▉                                                                                                                          | 140/1281 [00:29<03:49,  4.98it/s]

I5C044
 Bacteria (superkingdom)
D2V6P8
 Eukaryota (superkingdom)

 11%|███████████████▏                                                                                                                         | 142/1281 [00:30<03:41,  5.13it/s]

D3RN22
 Bacteria (superkingdom)
Q97L80
 Bacteria (superkingdom)

 11%|███████████████▎                                                                                                                         | 143/1281 [00:30<04:17,  4.41it/s]

A0A0D5YN10
 Bacteria (superkingdom)
A0A1I5GN22
 Bacteria (superkingdom)

 11%|███████████████▌                                                                                                                         | 146/1281 [00:30<03:39,  5.16it/s]

A0A1Y5E8I7
 Bacteria (superkingdom)
B1Y8C9
 Bacteria (superkingdom)

 12%|███████████████▊                                                                                                                         | 148/1281 [00:31<03:44,  5.04it/s]

M5SYZ1
 Bacteria (superkingdom)
Q6HM26
 Bacteria (superkingdom)

 12%|████████████████                                                                                                                         | 150/1281 [00:31<03:37,  5.20it/s]

A0A379A0S9
 Bacteria (superkingdom)
A0A101DCS3
 Archaea (superkingdom)

 12%|████████████████▎                                                                                                                        | 152/1281 [00:32<03:33,  5.29it/s]

A0A1Y3U5V2
 Bacteria (superkingdom)
A0A202B535
 Bacteria (superkingdom)

 12%|████████████████▎                                                                                                                        | 153/1281 [00:32<04:27,  4.22it/s]

F8E6R1
 Bacteria (superkingdom)
Q6ND36
 Bacteria (superkingdom)

 12%|████████████████▋                                                                                                                        | 156/1281 [00:33<03:44,  5.01it/s]

A0A8H6K7L7
 Eukaryota (superkingdom)
Q7NCB8
 Bacteria (superkingdom)

 12%|████████████████▉                                                                                                                        | 158/1281 [00:33<03:51,  4.86it/s]

A0A369MRW6
 Bacteria (superkingdom)
C9RS76
 Bacteria (superkingdom)

 12%|█████████████████                                                                                                                        | 160/1281 [00:33<03:38,  5.14it/s]

A3U857
 Bacteria (superkingdom)
A0A127PIQ9
 Bacteria (superkingdom)

 13%|█████████████████▎                                                                                                                       | 162/1281 [00:34<03:32,  5.27it/s]

B8FGW0
 Bacteria (superkingdom)
A0A060JMP6
 Bacteria (superkingdom)

 13%|█████████████████▍                                                                                                                       | 163/1281 [00:34<04:16,  4.37it/s]

D5V7B3
 Bacteria (superkingdom)
A0A494JB70
 Bacteria (superkingdom)

 13%|█████████████████▋                                                                                                                       | 165/1281 [00:35<04:02,  4.60it/s]

A0A5M8QF12
 Bacteria (superkingdom)
A0A8G2F3G4
 Bacteria (superkingdom)

 13%|█████████████████▊                                                                                                                       | 167/1281 [00:35<04:06,  4.52it/s]

J7L3W8
 Bacteria (superkingdom)
G0JRG9
 Bacteria (superkingdom)

 13%|██████████████████                                                                                                                       | 169/1281 [00:35<04:04,  4.55it/s]

D3DJN2
 Bacteria (superkingdom)
A0A1Y2JH43
 Bacteria (superkingdom)

 13%|██████████████████▎                                                                                                                      | 171/1281 [00:36<04:04,  4.55it/s]

Q1L727
 Eukaryota (superkingdom)
A0A7T2S0Z6
 Bacteria (superkingdom)

 14%|██████████████████▌                                                                                                                      | 173/1281 [00:36<03:57,  4.67it/s]

A0A315S845
 Bacteria (superkingdom)
A0A2S6H6B7
 Bacteria (superkingdom)

 14%|██████████████████▋                                                                                                                      | 175/1281 [00:37<03:51,  4.78it/s]

A0A1J5NTP7
 Bacteria (superkingdom)
A0A0E3QY86
 Archaea (superkingdom)

 14%|██████████████████▉                                                                                                                      | 177/1281 [00:37<03:48,  4.84it/s]

A0A096EEV9
 Bacteria (superkingdom)
A0A380S5X4
 Bacteria (superkingdom)

 14%|███████████████████▏                                                                                                                     | 179/1281 [00:37<03:47,  4.85it/s]

B8ZYW3
 Archaea (superkingdom)
A0A2S8GEJ5
 Bacteria (superkingdom)

 14%|███████████████████▎                                                                                                                     | 181/1281 [00:38<03:45,  4.87it/s]

A0A248TDF2
 Bacteria (superkingdom)
B2GFN1
 Bacteria (superkingdom)

 14%|███████████████████▋                                                                                                                     | 184/1281 [00:38<03:28,  5.25it/s]

U1PPI7
 Archaea (superkingdom)
C7LW88
 Bacteria (superkingdom)

 14%|███████████████████▊                                                                                                                     | 185/1281 [00:39<04:00,  4.55it/s]

G3A431
 Bacteria (superkingdom)
A0A066ZTE4
 Bacteria (superkingdom)

 15%|████████████████████                                                                                                                     | 188/1281 [00:39<03:40,  4.96it/s]

L7CG99
 Bacteria (superkingdom)
S0ET45
 Bacteria (superkingdom)

 15%|████████████████████▎                                                                                                                    | 190/1281 [00:40<03:43,  4.88it/s]

A0A178TA08
 Bacteria (superkingdom)
H1XV27
 Bacteria (superkingdom)

 15%|████████████████████▌                                                                                                                    | 192/1281 [00:40<03:35,  5.05it/s]

A0A6M3ZJI1
 Bacteria (superkingdom)
U5DEY6
 Bacteria (superkingdom)

 15%|████████████████████▋                                                                                                                    | 193/1281 [00:41<04:15,  4.26it/s]

H6LFQ2
 Bacteria (superkingdom)
Q6CRN0
 Eukaryota (superkingdom)

 15%|████████████████████▊                                                                                                                    | 195/1281 [00:41<03:59,  4.53it/s]

A0A4Q2EAG7
 Bacteria (superkingdom)
A0A1J5NNB8
 Bacteria (superkingdom)

 15%|█████████████████████                                                                                                                    | 197/1281 [00:41<04:02,  4.48it/s]

E3I393
 Bacteria (superkingdom)
A0A243SC06
 Bacteria (superkingdom)

 16%|█████████████████████▍                                                                                                                   | 200/1281 [00:42<03:47,  4.75it/s]

D4F313
 Bacteria (superkingdom)
W0F0I7
 Bacteria (superkingdom)

 16%|█████████████████████▌                                                                                                                   | 202/1281 [00:42<03:53,  4.63it/s]

A9B874
 Bacteria (superkingdom)
A1D2Y5
 Eukaryota (superkingdom)

 16%|█████████████████████▊                                                                                                                   | 204/1281 [00:43<03:39,  4.91it/s]

T2J0N1
 Bacteria (superkingdom)
Q2FQT3
 Archaea (superkingdom)

 16%|██████████████████████                                                                                                                   | 206/1281 [00:43<03:35,  5.00it/s]

A0A075WG29
 Archaea (superkingdom)
A0A979GQ79
 Bacteria (superkingdom)

 16%|██████████████████████▏                                                                                                                  | 208/1281 [00:44<03:33,  5.03it/s]

A0A381CAY8
 Bacteria (superkingdom)
A0A2G3DSU6
 Bacteria (superkingdom)

 16%|██████████████████████▍                                                                                                                  | 210/1281 [00:44<03:30,  5.10it/s]

A0A168EVK8
 Bacteria (superkingdom)
A0A094W9G3
 Bacteria (superkingdom)

 17%|██████████████████████▋                                                                                                                  | 212/1281 [00:44<03:35,  4.96it/s]

A0A4R3NVT3
 Bacteria (superkingdom)
W0DYY3
 Bacteria (superkingdom)

 17%|██████████████████████▉                                                                                                                  | 214/1281 [00:45<03:29,  5.09it/s]

G8JTW0
 Eukaryota (superkingdom)
A0A4P6UIK6
 Bacteria (superkingdom)

 17%|███████████████████████                                                                                                                  | 216/1281 [00:45<03:37,  4.89it/s]

I9P003
 Bacteria (superkingdom)
G2T1Y3
 Bacteria (superkingdom)

 17%|███████████████████████▎                                                                                                                 | 218/1281 [00:46<03:44,  4.74it/s]

B8EMQ8
 Bacteria (superkingdom)
I6Z905
 Bacteria (superkingdom)

 17%|███████████████████████▍                                                                                                                 | 219/1281 [00:46<03:49,  4.64it/s]

E0TCV4
 Bacteria (superkingdom)
A3XNG6
 Bacteria (superkingdom)

 17%|███████████████████████▋                                                                                                                 | 221/1281 [00:46<03:39,  4.84it/s]

A0A087MGU4
 Bacteria (superkingdom)

 17%|███████████████████████▊                                                                                                                 | 223/1281 [00:47<03:31,  5.00it/s]

A2BUP4
 Bacteria (superkingdom)
A0A562S8V2
 Bacteria (superkingdom)

 18%|████████████████████████                                                                                                                 | 225/1281 [00:47<03:27,  5.10it/s]

A0A495DND0
 Bacteria (superkingdom)
A0A0S2FHD7
 Bacteria (superkingdom)

 18%|████████████████████████▎                                                                                                                | 227/1281 [00:48<03:26,  5.09it/s]

F3QPR6
 Bacteria (superkingdom)
A0A063Y394
 Bacteria (superkingdom)

 18%|████████████████████████▍                                                                                                                | 229/1281 [00:48<03:20,  5.24it/s]

F6G5I9
 Bacteria (superkingdom)
A0A323UDG5
 Bacteria (superkingdom)

 18%|████████████████████████▋                                                                                                                | 231/1281 [00:48<03:25,  5.10it/s]

A0A0G9HEC5
 Bacteria (superkingdom)
B8FDY8
 Bacteria (superkingdom)

 18%|████████████████████████▉                                                                                                                | 233/1281 [00:49<03:18,  5.28it/s]

Q5KPM5
 Eukaryota (superkingdom)
A0A147EQL9
 Bacteria (superkingdom)

 18%|█████████████████████████▏                                                                                                               | 235/1281 [00:49<03:28,  5.03it/s]

A0A854Q6X9
 Eukaryota (superkingdom)
C3X1J1
 Bacteria (superkingdom)

 19%|█████████████████████████▎                                                                                                               | 237/1281 [00:50<03:22,  5.17it/s]

A0A5B2V3B9
 Bacteria (superkingdom)
A0A258FS85
 Bacteria (superkingdom)

 19%|█████████████████████████▌                                                                                                               | 239/1281 [00:50<03:17,  5.26it/s]

A0A7T2W1B3
 Bacteria (superkingdom)
A0A060UN76
 Bacteria (superkingdom)

 19%|█████████████████████████▊                                                                                                               | 241/1281 [00:51<03:30,  4.94it/s]

G0JRQ3
 Bacteria (superkingdom)
D5UD26
 Bacteria (superkingdom)

 19%|█████████████████████████▉                                                                                                               | 243/1281 [00:51<03:21,  5.15it/s]

G2ZN72
 Bacteria (superkingdom)
A0AA46Q839
 Bacteria (superkingdom)

 19%|██████████████████████████▏                                                                                                              | 245/1281 [00:51<03:34,  4.82it/s]

A5UJR1
 Archaea (superkingdom)
L1INN6
 Eukaryota (superkingdom)

 19%|██████████████████████████▍                                                                                                              | 247/1281 [00:52<03:31,  4.89it/s]

C1F584
 Bacteria (superkingdom)
C5LAG4
 Eukaryota (superkingdom)

 19%|██████████████████████████▋                                                                                                              | 249/1281 [00:52<03:42,  4.65it/s]

A0A2A2MCP3
 Bacteria (superkingdom)
B1Y6V4
 Bacteria (superkingdom)

 20%|██████████████████████████▊                                                                                                              | 251/1281 [00:53<03:30,  4.90it/s]

A0A1G6ABK5
 Bacteria (superkingdom)
A0A6A1TYJ4
 Bacteria (superkingdom)

 20%|██████████████████████████▉                                                                                                              | 252/1281 [00:53<03:41,  4.65it/s]

A0A2T4UWF1
 Bacteria (superkingdom)

 20%|███████████████████████████▏                                                                                                             | 254/1281 [00:53<03:30,  4.88it/s]

V4AP67
 Eukaryota (superkingdom)
A0A173R3W6
 Bacteria (superkingdom)

 20%|███████████████████████████▍                                                                                                             | 256/1281 [00:54<03:35,  4.76it/s]

C7NND3
 Archaea (superkingdom)
B0DFJ4
 Eukaryota (superkingdom)

 20%|███████████████████████████▍                                                                                                             | 257/1281 [00:54<03:36,  4.73it/s]

A0A3E2VY88
 Bacteria (superkingdom)

 20%|███████████████████████████▋                                                                                                             | 259/1281 [00:54<03:37,  4.70it/s]

R1EDV9
 Eukaryota (superkingdom)
J1L5M8
 Archaea (superkingdom)

 20%|███████████████████████████▉                                                                                                             | 261/1281 [00:55<03:31,  4.82it/s]

D7G265
 Eukaryota (superkingdom)
Q8ERT9
 Bacteria (superkingdom)

 21%|████████████████████████████▏                                                                                                            | 263/1281 [00:55<03:20,  5.09it/s]

I4D6Z9
 Bacteria (superkingdom)
A0A4R6DFU8
 Bacteria (superkingdom)

 21%|████████████████████████████▎                                                                                                            | 265/1281 [00:56<03:27,  4.89it/s]

A0A060URC3
 Bacteria (superkingdom)
D2BIB2
 Bacteria (superkingdom)

 21%|████████████████████████████▌                                                                                                            | 267/1281 [00:56<03:31,  4.79it/s]

F5ISF6
 Bacteria (superkingdom)
A5CRL2
 Bacteria (superkingdom)

 21%|████████████████████████████▊                                                                                                            | 269/1281 [00:57<03:33,  4.74it/s]

A0A6G9XJV9
 Bacteria (superkingdom)
Q59UP8
 Eukaryota (superkingdom)

 21%|████████████████████████████▉                                                                                                            | 270/1281 [00:57<03:32,  4.77it/s]

A0A6N4SPH9
 Bacteria (superkingdom)

 21%|█████████████████████████████                                                                                                            | 272/1281 [00:57<03:25,  4.91it/s]

I0HGY4
 Bacteria (superkingdom)
X5DX97
 Bacteria (superkingdom)

 21%|█████████████████████████████▎                                                                                                           | 274/1281 [00:58<03:28,  4.83it/s]

L1J6I4
 Eukaryota (superkingdom)
I1DSU5
 Bacteria (superkingdom)

 22%|█████████████████████████████▌                                                                                                           | 276/1281 [00:58<03:31,  4.74it/s]

B9L7N1
 Bacteria (superkingdom)
Q1Z4I4
 Bacteria (superkingdom)

 22%|█████████████████████████████▋                                                                                                           | 278/1281 [00:58<03:19,  5.03it/s]

Q21CP1
 Bacteria (superkingdom)
A0A165MFD1
 Bacteria (superkingdom)

 22%|█████████████████████████████▉                                                                                                           | 280/1281 [00:59<03:12,  5.20it/s]

V4CRP5
 Eukaryota (superkingdom)
Q7S5K0
 Eukaryota (superkingdom)

 22%|██████████████████████████████▏                                                                                                          | 282/1281 [00:59<03:05,  5.38it/s]

A0A071MMV1
 Bacteria (superkingdom)
A0A149RYW7
 Bacteria (superkingdom)

 22%|██████████████████████████████▎                                                                                                          | 283/1281 [01:00<03:41,  4.51it/s]

A0A7G5EC77
 Bacteria (superkingdom)
A0A1W2GZ82
 Bacteria (superkingdom)

 22%|██████████████████████████████▍                                                                                                          | 285/1281 [01:00<03:32,  4.70it/s]

A0A7U3XVQ4
 Bacteria (superkingdom)
A0A071M4L5
 Bacteria (superkingdom)

 22%|██████████████████████████████▋                                                                                                          | 287/1281 [01:00<03:36,  4.58it/s]

U5C2K4
 Bacteria (superkingdom)
A0A248LNW8
 Bacteria (superkingdom)

 23%|██████████████████████████████▉                                                                                                          | 289/1281 [01:01<03:40,  4.51it/s]

L8H844
 Eukaryota (superkingdom)
A0A149V596
 Bacteria (superkingdom)

 23%|███████████████████████████████                                                                                                          | 291/1281 [01:01<03:39,  4.52it/s]

S9QZ09
 Bacteria (superkingdom)
B1ZSW9
 Bacteria (superkingdom)

 23%|███████████████████████████████▎                                                                                                         | 293/1281 [01:02<03:31,  4.68it/s]

D2BUJ8
 Bacteria (superkingdom)
A0A9Q8L398
 Bacteria (superkingdom)

 23%|███████████████████████████████▌                                                                                                         | 295/1281 [01:02<03:34,  4.59it/s]

M5S735
 Bacteria (superkingdom)
Q6ARH0
 Bacteria (superkingdom)

 23%|███████████████████████████████▊                                                                                                         | 297/1281 [01:03<03:36,  4.55it/s]

K6W5X0
 Bacteria (superkingdom)
G0JRG6
 Bacteria (superkingdom)

 23%|███████████████████████████████▉                                                                                                         | 299/1281 [01:03<03:30,  4.68it/s]

A0A6H9FYW4
 Bacteria (superkingdom)
A0A0S4WFM4
 Bacteria (superkingdom)

 24%|████████████████████████████████▎                                                                                                        | 302/1281 [01:04<03:11,  5.12it/s]

A0A101HKN9
 Bacteria (superkingdom)
Q9REX3
 Bacteria (superkingdom)

 24%|████████████████████████████████▌                                                                                                        | 304/1281 [01:04<03:15,  5.01it/s]

F0S3Z6
 Bacteria (superkingdom)
A8NAG3
 Eukaryota (superkingdom)

 24%|████████████████████████████████▌                                                                                                        | 305/1281 [01:04<03:43,  4.36it/s]

C6LBD3
 Bacteria (superkingdom)
A0A149U2G9
 Bacteria (superkingdom)

 24%|████████████████████████████████▊                                                                                                        | 307/1281 [01:05<03:37,  4.49it/s]

V4REY8
 Bacteria (superkingdom)
A0A0H3H4I7
 Bacteria (superkingdom)

 24%|█████████████████████████████████▏                                                                                                       | 310/1281 [01:05<03:14,  4.99it/s]

A8N2H6
 Eukaryota (superkingdom)
S0APH6
 Archaea (superkingdom)

 24%|█████████████████████████████████▎                                                                                                       | 312/1281 [01:06<03:06,  5.21it/s]

A0A017SYR8
 Bacteria (superkingdom)
A0A1B9MZ78
 Bacteria (superkingdom)

 25%|█████████████████████████████████▌                                                                                                       | 314/1281 [01:06<03:12,  5.02it/s]

E4T3F3
 Bacteria (superkingdom)
D7E934
 Archaea (superkingdom)

 25%|█████████████████████████████████▊                                                                                                       | 316/1281 [01:07<03:06,  5.17it/s]

A0A0M3AB44
 Bacteria (superkingdom)
A9WHW6
 Bacteria (superkingdom)

 25%|██████████████████████████████████                                                                                                       | 318/1281 [01:07<03:02,  5.26it/s]

A0A5M4AUM9
 Bacteria (superkingdom)
A0A1X4GBG2
 Bacteria (superkingdom)

 25%|██████████████████████████████████                                                                                                       | 319/1281 [01:07<03:44,  4.28it/s]

I4D1H5
 Bacteria (superkingdom)
A0A0E3QYF3
 Archaea (superkingdom)

 25%|██████████████████████████████████▎                                                                                                      | 321/1281 [01:08<03:32,  4.51it/s]

B0CQX4
 Eukaryota (superkingdom)
A0A378YR15
 Bacteria (superkingdom)

 25%|██████████████████████████████████▌                                                                                                      | 323/1281 [01:08<03:23,  4.71it/s]

A0A495D4X4
 Bacteria (superkingdom)
A0A076PL76
 Bacteria (superkingdom)

 25%|██████████████████████████████████▊                                                                                                      | 325/1281 [01:09<03:19,  4.78it/s]

Q1YDY7
 Bacteria (superkingdom)
A0A3E2UCG9
 Bacteria (superkingdom)

 26%|██████████████████████████████████▉                                                                                                      | 327/1281 [01:09<03:17,  4.83it/s]

A0A2K3DPU7
 Eukaryota (superkingdom)
A0A3R9Q7C4
 Bacteria (superkingdom)

 26%|███████████████████████████████████▎                                                                                                     | 330/1281 [01:09<03:01,  5.24it/s]

V5U2Z4
 Bacteria (superkingdom)
K9P718
 Bacteria (superkingdom)

 26%|███████████████████████████████████▍                                                                                                     | 331/1281 [01:10<03:28,  4.55it/s]

M1V7W3
 Eukaryota (superkingdom)
Q6LKC8
 Bacteria (superkingdom)

 26%|███████████████████████████████████▋                                                                                                     | 334/1281 [01:10<03:06,  5.09it/s]

E5Y789
 Bacteria (superkingdom)
J9Z839
 Bacteria (superkingdom)

 26%|███████████████████████████████████▉                                                                                                     | 336/1281 [01:11<03:08,  5.01it/s]

A0A1G7VM92
 Bacteria (superkingdom)
K9Z0D3
 Bacteria (superkingdom)

 26%|████████████████████████████████████▏                                                                                                    | 338/1281 [01:11<03:08,  5.01it/s]

A0A482TED1
 Archaea (superkingdom)
R1EGK6
 Eukaryota (superkingdom)

 27%|████████████████████████████████████▎                                                                                                    | 340/1281 [01:12<03:02,  5.16it/s]

J1ASR8
 Archaea (superkingdom)
A0A7U4E420
 Bacteria (superkingdom)

 27%|████████████████████████████████████▌                                                                                                    | 342/1281 [01:12<03:14,  4.82it/s]

K9YR86
 Bacteria (superkingdom)
A8PXT8
 Eukaryota (superkingdom)

 27%|████████████████████████████████████▋                                                                                                    | 343/1281 [01:12<03:25,  4.57it/s]

A0A0U1NJW3
 Bacteria (superkingdom)

 27%|████████████████████████████████████▊                                                                                                    | 344/1281 [01:13<03:21,  4.65it/s]

B8FL88
 Bacteria (superkingdom)

 27%|████████████████████████████████████▉                                                                                                    | 345/1281 [01:13<03:28,  4.48it/s]

A2CCK1
 Bacteria (superkingdom)
D6TFE1
 Bacteria (superkingdom)

 27%|█████████████████████████████████████                                                                                                    | 347/1281 [01:13<03:17,  4.74it/s]

A0A2H4U5R1
 Archaea (superkingdom)

 27%|█████████████████████████████████████▎                                                                                                   | 349/1281 [01:14<03:04,  5.06it/s]

I2GD40
 Bacteria (superkingdom)
A0A060HFT5
 Archaea (superkingdom)

 27%|█████████████████████████████████████▍                                                                                                   | 350/1281 [01:14<03:32,  4.39it/s]

B1Y842
 Bacteria (superkingdom)
A0A0X8NXA9
 Bacteria (superkingdom)

 27%|█████████████████████████████████████▋                                                                                                   | 352/1281 [01:14<03:21,  4.62it/s]

A0A0A2A5X1
 Bacteria (superkingdom)
A0A318FY98
 Bacteria (superkingdom)

 28%|█████████████████████████████████████▊                                                                                                   | 354/1281 [01:15<03:16,  4.71it/s]

Q7V4T8
 Bacteria (superkingdom)
A0A1A0DHK0
 Bacteria (superkingdom)

 28%|██████████████████████████████████████                                                                                                   | 356/1281 [01:15<03:22,  4.58it/s]

C1A872
 Bacteria (superkingdom)
A0A395VB65
 Bacteria (superkingdom)

 28%|██████████████████████████████████████▍                                                                                                  | 359/1281 [01:16<03:00,  5.10it/s]

A7MFK3
 Bacteria (superkingdom)
J4KM12
 Eukaryota (superkingdom)

 28%|██████████████████████████████████████▌                                                                                                  | 360/1281 [01:16<03:31,  4.35it/s]

A1SY01
 Bacteria (superkingdom)
A0A1H4DJ49
 Bacteria (superkingdom)

 28%|██████████████████████████████████████▊                                                                                                  | 363/1281 [01:17<02:59,  5.10it/s]

A0A9R0NTP8
 Bacteria (superkingdom)
A3PAY4
 Bacteria (superkingdom)

 28%|███████████████████████████████████████                                                                                                  | 365/1281 [01:17<03:02,  5.03it/s]

B4CV94
 Bacteria (superkingdom)
A2C095
 Bacteria (superkingdom)

 29%|███████████████████████████████████████▏                                                                                                 | 366/1281 [01:17<03:37,  4.20it/s]

Q2HD43
 Eukaryota (superkingdom)
A0A836M2B6
 Bacteria (superkingdom)

 29%|███████████████████████████████████████▎                                                                                                 | 368/1281 [01:18<03:22,  4.50it/s]

H6RWK9
 Bacteria (superkingdom)
A0A087EQK8
 Bacteria (superkingdom)

 29%|███████████████████████████████████████▋                                                                                                 | 371/1281 [01:18<02:56,  5.16it/s]

A0A1I0AQM4
 Bacteria (superkingdom)
L7CG11
 Bacteria (superkingdom)

 29%|███████████████████████████████████████▉                                                                                                 | 373/1281 [01:19<02:55,  5.18it/s]

A0A248LNK5
 Bacteria (superkingdom)
B7FTM9
 Eukaryota (superkingdom)

 29%|████████████████████████████████████████                                                                                                 | 375/1281 [01:19<02:57,  5.11it/s]

L0K9M1
 Bacteria (superkingdom)
I4D6Z7
 Bacteria (superkingdom)

 29%|████████████████████████████████████████▎                                                                                                | 377/1281 [01:20<02:58,  5.07it/s]

A0A2K1RA81
 Eukaryota (superkingdom)
Q2WBF7
 Bacteria (superkingdom)

 30%|████████████████████████████████████████▌                                                                                                | 379/1281 [01:20<02:52,  5.22it/s]

A0A1B9BUU6
 Bacteria (superkingdom)
A0A2S0JW39
 Bacteria (superkingdom)

 30%|████████████████████████████████████████▋                                                                                                | 381/1281 [01:20<03:01,  4.97it/s]

A0A2S5YID7
 Bacteria (superkingdom)
B3PIH2
 Bacteria (superkingdom)

 30%|████████████████████████████████████████▉                                                                                                | 383/1281 [01:21<03:06,  4.80it/s]

U3P8G1
 Bacteria (superkingdom)
C9R9J0
 Bacteria (superkingdom)

 30%|█████████████████████████████████████████▏                                                                                               | 385/1281 [01:21<03:02,  4.91it/s]

A8AC17
 Archaea (superkingdom)
F0YLV7
 Eukaryota (superkingdom)

 30%|█████████████████████████████████████████▍                                                                                               | 387/1281 [01:22<03:09,  4.72it/s]

A0A1D3GAE9
 Bacteria (superkingdom)
C1MHX0
 Eukaryota (superkingdom)

 30%|█████████████████████████████████████████▍                                                                                               | 388/1281 [01:22<03:05,  4.81it/s]

A0A1H4KAQ7
 Bacteria (superkingdom)

 30%|█████████████████████████████████████████▌                                                                                               | 389/1281 [01:22<03:05,  4.80it/s]

A0A2T4XZC1
 Bacteria (superkingdom)

 30%|█████████████████████████████████████████▋                                                                                               | 390/1281 [01:22<03:13,  4.62it/s]

A1B3N0
 Bacteria (superkingdom)

 31%|█████████████████████████████████████████▊                                                                                               | 391/1281 [01:23<03:10,  4.68it/s]

C7LW87
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████                                                                                               | 393/1281 [01:23<03:00,  4.92it/s]

A1SZ12
 Bacteria (superkingdom)
A0A2T2Y0D5
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████▏                                                                                              | 395/1281 [01:23<02:53,  5.10it/s]

A0A1H8D0R8
 Bacteria (superkingdom)
A0A2S5V2F6
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████▍                                                                                              | 397/1281 [01:24<02:59,  4.94it/s]

G3IYW2
 Bacteria (superkingdom)
F5L8M7
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████▋                                                                                              | 399/1281 [01:24<02:55,  5.02it/s]

C7BJG7
 Bacteria (superkingdom)
E4U5Z1
 Bacteria (superkingdom)

 31%|██████████████████████████████████████████▉                                                                                              | 401/1281 [01:25<02:50,  5.17it/s]

A0A1B9K8L2
 Bacteria (superkingdom)
A0A2S5WMT7
 Bacteria (superkingdom)

 31%|███████████████████████████████████████████                                                                                              | 403/1281 [01:25<02:49,  5.17it/s]

A0A0D2UPA8
 Eukaryota (superkingdom)
A0A161SKF4
 Bacteria (superkingdom)

 32%|███████████████████████████████████████████▎                                                                                             | 405/1281 [01:25<02:44,  5.34it/s]

B4D7W2
 Bacteria (superkingdom)
A0A1H3WA00
 Bacteria (superkingdom)

 32%|███████████████████████████████████████████▍                                                                                             | 406/1281 [01:26<03:24,  4.28it/s]

C1D6X6
 Bacteria (superkingdom)
A0A4D6KHD1
 Archaea (superkingdom)

 32%|███████████████████████████████████████████▋                                                                                             | 408/1281 [01:26<03:19,  4.38it/s]

Q488X2
 Bacteria (superkingdom)
A9V5W4
 Eukaryota (superkingdom)

 32%|███████████████████████████████████████████▉                                                                                             | 411/1281 [01:27<02:56,  4.94it/s]

A0A5M4ATH9
 Bacteria (superkingdom)
E4TRS4
 Bacteria (superkingdom)

 32%|████████████████████████████████████████████▏                                                                                            | 413/1281 [01:27<03:02,  4.76it/s]

A0A011U1K7
 Bacteria (superkingdom)
C7R314
 Bacteria (superkingdom)

 32%|████████████████████████████████████████████▍                                                                                            | 415/1281 [01:28<02:56,  4.91it/s]

A0A077EFU9
 Bacteria (superkingdom)
A0A0A2A0Y9
 Bacteria (superkingdom)

 33%|████████████████████████████████████████████▌                                                                                            | 417/1281 [01:28<02:53,  4.97it/s]

A0A0D8BQX6
 Bacteria (superkingdom)
A0A0L0S493
 Eukaryota (superkingdom)

 33%|████████████████████████████████████████████▊                                                                                            | 419/1281 [01:28<02:52,  4.99it/s]

A0A328Q6M1
 Archaea (superkingdom)
A0A016XCG9
 Bacteria (superkingdom)

 33%|████████████████████████████████████████████▉                                                                                            | 420/1281 [01:29<03:00,  4.78it/s]

B7FSA7
 Eukaryota (superkingdom)

 33%|█████████████████████████████████████████████▏                                                                                           | 422/1281 [01:29<02:57,  4.84it/s]

G0AFH4
 Bacteria (superkingdom)
A0A177W826
 Eukaryota (superkingdom)

 33%|█████████████████████████████████████████████▏                                                                                           | 423/1281 [01:29<02:54,  4.91it/s]

A0A2S8GF54
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████▎                                                                                           | 424/1281 [01:29<02:54,  4.92it/s]

Q1YDY8
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████▍                                                                                           | 425/1281 [01:30<02:54,  4.90it/s]

Q5QVH2
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████▋                                                                                           | 427/1281 [01:30<02:49,  5.04it/s]

A3ZT81
 Bacteria (superkingdom)
A0AA35XZV0
 Bacteria (superkingdom)

 33%|█████████████████████████████████████████████▉                                                                                           | 429/1281 [01:30<02:54,  4.88it/s]

F4H924
 Bacteria (superkingdom)
K0NJH2
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████                                                                                           | 431/1281 [01:31<02:58,  4.76it/s]

A0A1V3SSW1
 Bacteria (superkingdom)
F2AUF4
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████▎                                                                                          | 433/1281 [01:31<03:02,  4.66it/s]

A6DN47
 Bacteria (superkingdom)
W8KM07
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████▌                                                                                          | 435/1281 [01:32<02:53,  4.88it/s]

A0A1X3RP39
 Bacteria (superkingdom)
A0A7S0KKL8
 Eukaryota (superkingdom)

 34%|██████████████████████████████████████████████▋                                                                                          | 437/1281 [01:32<02:47,  5.03it/s]

A0A318QZ80
 Bacteria (superkingdom)
K8VZC6
 Bacteria (superkingdom)

 34%|██████████████████████████████████████████████▉                                                                                          | 439/1281 [01:33<02:46,  5.04it/s]

A0A1B9JZS5
 Bacteria (superkingdom)
A0A2S6GKN5
 Bacteria (superkingdom)

 34%|███████████████████████████████████████████████                                                                                          | 440/1281 [01:33<02:50,  4.94it/s]

A0A4R2Z2K6
 Bacteria (superkingdom)

 35%|███████████████████████████████████████████████▎                                                                                         | 442/1281 [01:33<02:49,  4.94it/s]

H1YCC3
 Bacteria (superkingdom)
E1QIU3
 Bacteria (superkingdom)

 35%|███████████████████████████████████████████████▍                                                                                         | 444/1281 [01:34<02:46,  5.03it/s]

A0A8H6MPB9
 Eukaryota (superkingdom)
A0A369N7Y3
 Bacteria (superkingdom)

 35%|███████████████████████████████████████████████▋                                                                                         | 446/1281 [01:34<02:53,  4.81it/s]

T2IEJ2
 Bacteria (superkingdom)
H5UND3
 Bacteria (superkingdom)

 35%|███████████████████████████████████████████████▉                                                                                         | 448/1281 [01:34<02:46,  4.99it/s]

Q1PX09
 Bacteria (superkingdom)
A0A149TSA9
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████▏                                                                                        | 450/1281 [01:35<02:42,  5.11it/s]

F2NGJ8
 Bacteria (superkingdom)
A0A0E3SHQ9
 Archaea (superkingdom)

 35%|████████████████████████████████████████████████▎                                                                                        | 452/1281 [01:35<02:52,  4.82it/s]

Q5FLR6
 Bacteria (superkingdom)
S0EUS1
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████▍                                                                                        | 453/1281 [01:35<02:51,  4.83it/s]

A0A369M386
 Bacteria (superkingdom)

 35%|████████████████████████████████████████████████▌                                                                                        | 454/1281 [01:36<02:52,  4.81it/s]

W0DZS7
 Bacteria (superkingdom)

 36%|████████████████████████████████████████████████▊                                                                                        | 456/1281 [01:36<02:44,  5.01it/s]

A8MCL4
 Archaea (superkingdom)
V3ZVE4
 Eukaryota (superkingdom)

 36%|████████████████████████████████████████████████▉                                                                                        | 457/1281 [01:36<03:12,  4.27it/s]

O26757
 Archaea (superkingdom)
A0A317FZW2
 Bacteria (superkingdom)

 36%|█████████████████████████████████████████████████                                                                                        | 459/1281 [01:37<02:59,  4.57it/s]

A0A085GI50
 Bacteria (superkingdom)
A1ZGK6
 Bacteria (superkingdom)

 36%|█████████████████████████████████████████████████▍                                                                                       | 462/1281 [01:37<02:42,  5.04it/s]

G0IYI2
 Bacteria (superkingdom)
A7S731
 Eukaryota (superkingdom)

 36%|█████████████████████████████████████████████████▌                                                                                       | 464/1281 [01:38<02:37,  5.19it/s]

A0A1U9YY82
 Bacteria (superkingdom)
A0A328EMN2
 Bacteria (superkingdom)

 36%|█████████████████████████████████████████████████▊                                                                                       | 466/1281 [01:38<02:35,  5.23it/s]

A0A8E2UDJ3
 Bacteria (superkingdom)
A0A2S5WUP6
 Bacteria (superkingdom)

 37%|██████████████████████████████████████████████████                                                                                       | 468/1281 [01:39<02:33,  5.29it/s]

A0A8H7P8U1
 Eukaryota (superkingdom)
A0A257T7G4
 Bacteria (superkingdom)

 37%|██████████████████████████████████████████████████▏                                                                                      | 469/1281 [01:39<03:07,  4.32it/s]

B3MX93
 Eukaryota (superkingdom)
A0A1G5W0P2
 Bacteria (superkingdom)

 37%|██████████████████████████████████████████████████▎                                                                                      | 471/1281 [01:39<03:03,  4.40it/s]

D4H2Y7
 Bacteria (superkingdom)
A0A4P8HC89
 Bacteria (superkingdom)

 37%|██████████████████████████████████████████████████▌                                                                                      | 473/1281 [01:40<03:02,  4.43it/s]

Q7T070
 Eukaryota (superkingdom)
F7NPQ3
 Bacteria (superkingdom)

 37%|██████████████████████████████████████████████████▊                                                                                      | 475/1281 [01:40<03:01,  4.45it/s]

B9SA70
 Eukaryota (superkingdom)
Q9M6N7
 Eukaryota (superkingdom)

 37%|███████████████████████████████████████████████████                                                                                      | 477/1281 [01:41<02:58,  4.51it/s]

I7ZHW3
 Bacteria (superkingdom)
F4XTK4
 Bacteria (superkingdom)

 37%|███████████████████████████████████████████████████▏                                                                                     | 479/1281 [01:41<02:58,  4.50it/s]

A4G1J2
 Bacteria (superkingdom)
G7WFX4
 Bacteria (superkingdom)

 38%|███████████████████████████████████████████████████▍                                                                                     | 481/1281 [01:42<02:54,  4.60it/s]

B8JBH5
 Bacteria (superkingdom)
D9QPC8
 Bacteria (superkingdom)

 38%|███████████████████████████████████████████████████▊                                                                                     | 484/1281 [01:42<02:35,  5.14it/s]

A0A4R7GKA0
 Bacteria (superkingdom)
R9PMC6
 Bacteria (superkingdom)

 38%|███████████████████████████████████████████████████▉                                                                                     | 486/1281 [01:42<02:31,  5.24it/s]

A0A0E3LMT4
 Archaea (superkingdom)
A0A511NGC7
 Bacteria (superkingdom)

 38%|████████████████████████████████████████████████████▏                                                                                    | 488/1281 [01:43<02:34,  5.12it/s]

E4NS62
 Archaea (superkingdom)
E4T3F7
 Bacteria (superkingdom)

 38%|████████████████████████████████████████████████████▍                                                                                    | 490/1281 [01:43<02:37,  5.03it/s]

M0D580
 Archaea (superkingdom)
J7J5E7
 Bacteria (superkingdom)

 38%|████████████████████████████████████████████████████▌                                                                                    | 491/1281 [01:44<03:01,  4.36it/s]

B1XZU2
 Bacteria (superkingdom)
A0A366IE34
 Bacteria (superkingdom)

 39%|████████████████████████████████████████████████████▊                                                                                    | 494/1281 [01:44<02:31,  5.21it/s]

A0A6U2BIY7
 Eukaryota (superkingdom)
Q9QXP0
 Eukaryota (superkingdom)

 39%|█████████████████████████████████████████████████████                                                                                    | 496/1281 [01:45<02:29,  5.24it/s]

A0A424WAH3
 Bacteria (superkingdom)
A0A410K1J5
 Bacteria (superkingdom)

 39%|█████████████████████████████████████████████████████▎                                                                                   | 498/1281 [01:45<02:36,  5.00it/s]

L1IHZ8
 Eukaryota (superkingdom)
I8TC71
 Bacteria (superkingdom)

 39%|█████████████████████████████████████████████████████▍                                                                                   | 500/1281 [01:45<02:43,  4.77it/s]

A0A7U8C744
 Bacteria (superkingdom)
A8M670
 Bacteria (superkingdom)

 39%|█████████████████████████████████████████████████████▋                                                                                   | 502/1281 [01:46<02:36,  4.97it/s]

A0A0S4VNK2
 Bacteria (superkingdom)
Q2SIR0
 Bacteria (superkingdom)

 39%|█████████████████████████████████████████████████████▉                                                                                   | 504/1281 [01:46<02:33,  5.06it/s]

A0A5C4RNH5
 Bacteria (superkingdom)
A0A3E0X011
 Bacteria (superkingdom)

 39%|██████████████████████████████████████████████████████                                                                                   | 505/1281 [01:46<02:38,  4.89it/s]

A0A0E3SP24
 Archaea (superkingdom)

 40%|██████████████████████████████████████████████████████▏                                                                                  | 507/1281 [01:47<02:34,  5.00it/s]

E1IF27
 Bacteria (superkingdom)
Q2YBP7
 Bacteria (superkingdom)

 40%|██████████████████████████████████████████████████████▍                                                                                  | 509/1281 [01:47<02:31,  5.10it/s]

A0A2S5WZU0
 Bacteria (superkingdom)
A0A172YBR4
 Bacteria (superkingdom)

 40%|██████████████████████████████████████████████████████▋                                                                                  | 511/1281 [01:48<02:29,  5.15it/s]

A0A0K2STK6
 Eukaryota (superkingdom)
A0A2N6JV02
 Bacteria (superkingdom)

 40%|██████████████████████████████████████████████████████▊                                                                                  | 513/1281 [01:48<02:26,  5.23it/s]

F0S0G1
 Bacteria (superkingdom)
A0A1C7EL50
 Bacteria (superkingdom)

 40%|███████████████████████████████████████████████████████                                                                                  | 515/1281 [01:48<02:23,  5.32it/s]

Q18PF5
 Eukaryota (superkingdom)
A0A1I0C958
 Bacteria (superkingdom)

 40%|███████████████████████████████████████████████████████▎                                                                                 | 517/1281 [01:49<02:20,  5.46it/s]

A0AA35XVN2
 Bacteria (superkingdom)
L8GGA0
 Eukaryota (superkingdom)

 40%|███████████████████████████████████████████████████████▍                                                                                 | 518/1281 [01:49<02:56,  4.32it/s]

Q3AP28
 Bacteria (superkingdom)
D0MFE9
 Bacteria (superkingdom)

 41%|███████████████████████████████████████████████████████▌                                                                                 | 520/1281 [01:50<02:48,  4.52it/s]

J9VXX9
 Eukaryota (superkingdom)
A0A166IS52
 Bacteria (superkingdom)

 41%|███████████████████████████████████████████████████████▉                                                                                 | 523/1281 [01:50<02:29,  5.06it/s]

F0J7D3
 Bacteria (superkingdom)
W7QG13
 Bacteria (superkingdom)

 41%|████████████████████████████████████████████████████████▏                                                                                | 525/1281 [01:51<02:32,  4.95it/s]

A4BMY5
 Bacteria (superkingdom)
A6LV49
 Bacteria (superkingdom)

 41%|████████████████████████████████████████████████████████▎                                                                                | 527/1281 [01:51<02:32,  4.94it/s]

Q1H483
 Bacteria (superkingdom)
A6M3G0
 Bacteria (superkingdom)

 41%|████████████████████████████████████████████████████████▍                                                                                | 528/1281 [01:51<02:57,  4.24it/s]

E4T0A4
 Bacteria (superkingdom)
A0A3E2UHE6
 Bacteria (superkingdom)

 41%|████████████████████████████████████████████████████████▋                                                                                | 530/1281 [01:52<02:45,  4.55it/s]

A0A174SD65
 Bacteria (superkingdom)
A0A855EH99
 Bacteria (superkingdom)

 42%|████████████████████████████████████████████████████████▉                                                                                | 532/1281 [01:52<02:46,  4.49it/s]

C3YB74
 Eukaryota (superkingdom)
A0A074KZD8
 Bacteria (superkingdom)

 42%|█████████████████████████████████████████████████████████                                                                                | 534/1281 [01:53<02:45,  4.51it/s]

J0S2I0
 Archaea (superkingdom)
K9WSX4
 Bacteria (superkingdom)

 42%|█████████████████████████████████████████████████████████▎                                                                               | 536/1281 [01:53<02:40,  4.63it/s]

E8RLT5
 Bacteria (superkingdom)
Q2FS34
 Archaea (superkingdom)

 42%|█████████████████████████████████████████████████████████▌                                                                               | 538/1281 [01:54<02:41,  4.61it/s]

Q3Z7F9
 Bacteria (superkingdom)
Q2S8H9
 Bacteria (superkingdom)

 42%|█████████████████████████████████████████████████████████▊                                                                               | 541/1281 [01:54<02:26,  5.05it/s]

A0A060HN92
 Archaea (superkingdom)
E6ME92
 Bacteria (superkingdom)

 42%|██████████████████████████████████████████████████████████                                                                               | 543/1281 [01:54<02:28,  4.96it/s]

A0A172RYW3
 Bacteria (superkingdom)
L0FU80
 Bacteria (superkingdom)

 43%|██████████████████████████████████████████████████████████▎                                                                              | 545/1281 [01:55<02:25,  5.05it/s]

C8WZE0
 Bacteria (superkingdom)
A0A2S8F4W0
 Bacteria (superkingdom)

 43%|██████████████████████████████████████████████████████████▌                                                                              | 547/1281 [01:55<02:24,  5.08it/s]

A0A2C6C0X3
 Bacteria (superkingdom)
F3ZVV4
 Bacteria (superkingdom)

 43%|██████████████████████████████████████████████████████████▋                                                                              | 549/1281 [01:56<02:21,  5.16it/s]

A0A7R6PER3
 Bacteria (superkingdom)
A0A495WJM6
 Bacteria (superkingdom)

 43%|██████████████████████████████████████████████████████████▉                                                                              | 551/1281 [01:56<02:20,  5.20it/s]

A0A0B4DUR9
 Bacteria (superkingdom)
A0A251YU48
 Bacteria (superkingdom)

 43%|███████████████████████████████████████████████████████████▏                                                                             | 553/1281 [01:56<02:18,  5.26it/s]

A5D4I5
 Bacteria (superkingdom)
A0A2X2C038
 Bacteria (superkingdom)

 43%|███████████████████████████████████████████████████████████▎                                                                             | 555/1281 [01:57<02:25,  4.99it/s]

A0A2A2M8K7
 Bacteria (superkingdom)
D3FBG3
 Bacteria (superkingdom)

 43%|███████████████████████████████████████████████████████████▌                                                                             | 557/1281 [01:57<02:25,  4.97it/s]

A0A2V4EA49
 Bacteria (superkingdom)
D0MFE8
 Bacteria (superkingdom)

 44%|███████████████████████████████████████████████████████████▊                                                                             | 559/1281 [01:58<02:21,  5.10it/s]

Q3B6Q2
 Bacteria (superkingdom)
A0A1B9KID3
 Bacteria (superkingdom)

 44%|███████████████████████████████████████████████████████████▉                                                                             | 561/1281 [01:58<02:19,  5.17it/s]

A0A9J9ES23
 Bacteria (superkingdom)
A0A3N2SFS2
 Bacteria (superkingdom)

 44%|████████████████████████████████████████████████████████████▏                                                                            | 563/1281 [01:59<02:15,  5.30it/s]

Q0VLH1
 Bacteria (superkingdom)
A0A1U9Z147
 Bacteria (superkingdom)

 44%|████████████████████████████████████████████████████████████▍                                                                            | 565/1281 [01:59<02:21,  5.07it/s]

Q0G2T1
 Bacteria (superkingdom)
A6GJF5
 Bacteria (superkingdom)

 44%|████████████████████████████████████████████████████████████▋                                                                            | 567/1281 [01:59<02:18,  5.16it/s]

A0A059XXR1
 Bacteria (superkingdom)
A0A5J6WPP9
 Bacteria (superkingdom)

 44%|████████████████████████████████████████████████████████████▊                                                                            | 569/1281 [02:00<02:22,  5.00it/s]

P41948
 Eukaryota (superkingdom)
L1IUV5
 Eukaryota (superkingdom)

 45%|█████████████████████████████████████████████████████████████                                                                            | 571/1281 [02:00<02:27,  4.81it/s]

A0A2W0GQV0
 Bacteria (superkingdom)
Q1K433
 Bacteria (superkingdom)

 45%|█████████████████████████████████████████████████████████████▏                                                                           | 572/1281 [02:00<02:26,  4.83it/s]

A0A4Y7XC43
 Bacteria (superkingdom)

 45%|█████████████████████████████████████████████████████████████▍                                                                           | 574/1281 [02:01<02:24,  4.91it/s]

D5AU98
 Bacteria (superkingdom)
E1QFA8
 Bacteria (superkingdom)

 45%|█████████████████████████████████████████████████████████████▌                                                                           | 576/1281 [02:01<02:21,  4.99it/s]

A0A075WBP9
 Archaea (superkingdom)
Q0BWD0
 Bacteria (superkingdom)

 45%|█████████████████████████████████████████████████████████████▊                                                                           | 578/1281 [02:02<02:18,  5.08it/s]

A0A1Y0HX98
 Bacteria (superkingdom)
A0A098S5Y7
 Bacteria (superkingdom)

 45%|██████████████████████████████████████████████████████████████                                                                           | 580/1281 [02:02<02:15,  5.19it/s]

Q0I445
 Bacteria (superkingdom)
A0A1E5BXA4
 Bacteria (superkingdom)

 45%|██████████████████████████████████████████████████████████████▏                                                                          | 582/1281 [02:02<02:22,  4.91it/s]

A0A2C9CK98
 Bacteria (superkingdom)
G4H971
 Bacteria (superkingdom)

 46%|██████████████████████████████████████████████████████████████▍                                                                          | 584/1281 [02:03<02:19,  4.99it/s]

A0A1I0BYN1
 Bacteria (superkingdom)
A0A330GB00
 Bacteria (superkingdom)

 46%|██████████████████████████████████████████████████████████████▌                                                                          | 585/1281 [02:03<02:22,  4.87it/s]

A0A2S8FR08
 Bacteria (superkingdom)

 46%|██████████████████████████████████████████████████████████████▊                                                                          | 587/1281 [02:04<02:17,  5.04it/s]

Q84KJ6
 Eukaryota (superkingdom)
A0A2S5WGI8
 Bacteria (superkingdom)

 46%|██████████████████████████████████████████████████████████████▉                                                                          | 589/1281 [02:04<02:11,  5.25it/s]

M2ALH9
 Bacteria (superkingdom)
A0A2K3DQF8
 Eukaryota (superkingdom)

 46%|███████████████████████████████████████████████████████████████▏                                                                         | 591/1281 [02:04<02:18,  4.98it/s]

A0A8G2IZM3
 Bacteria (superkingdom)
F5Y3C1
 Bacteria (superkingdom)

 46%|███████████████████████████████████████████████████████████████▍                                                                         | 593/1281 [02:05<02:21,  4.86it/s]

A0A370FPU0
 Bacteria (superkingdom)
F5RGM7
 Bacteria (superkingdom)

 46%|███████████████████████████████████████████████████████████████▋                                                                         | 595/1281 [02:05<02:16,  5.02it/s]

A0A4R4K1P9
 Bacteria (superkingdom)
R8VWI7
 Bacteria (superkingdom)

 47%|███████████████████████████████████████████████████████████████▋                                                                         | 596/1281 [02:05<02:19,  4.91it/s]

A0A0A2AMW2
 Bacteria (superkingdom)

 47%|███████████████████████████████████████████████████████████████▉                                                                         | 598/1281 [02:06<02:16,  4.99it/s]

Q7Z1M1
 Eukaryota (superkingdom)
A0A414NWT8
 Bacteria (superkingdom)

 47%|████████████████████████████████████████████████████████████████▏                                                                        | 600/1281 [02:06<02:17,  4.95it/s]

A0A0P6VSR8
 Bacteria (superkingdom)
A0A0L0TDW1
 Eukaryota (superkingdom)

 47%|████████████████████████████████████████████████████████████████▍                                                                        | 602/1281 [02:07<02:13,  5.09it/s]

U3PCH5
 Bacteria (superkingdom)
W7QGE0
 Bacteria (superkingdom)

 47%|████████████████████████████████████████████████████████████████▌                                                                        | 604/1281 [02:07<02:08,  5.28it/s]

C5BWX7
 Bacteria (superkingdom)
A0A1B9M1A9
 Bacteria (superkingdom)

 47%|████████████████████████████████████████████████████████████████▊                                                                        | 606/1281 [02:07<02:14,  5.04it/s]

B8GGC3
 Archaea (superkingdom)
D6SPD1
 Bacteria (superkingdom)

 47%|█████████████████████████████████████████████████████████████████                                                                        | 608/1281 [02:08<02:09,  5.21it/s]

A0A0H3DR67
 Bacteria (superkingdom)
A0A4R7VEK0
 Bacteria (superkingdom)

 48%|█████████████████████████████████████████████████████████████████▏                                                                       | 609/1281 [02:08<02:34,  4.34it/s]

G4R7P1
 Bacteria (superkingdom)
A0A1M5ZVP9
 Bacteria (superkingdom)

 48%|█████████████████████████████████████████████████████████████████▎                                                                       | 611/1281 [02:09<02:25,  4.61it/s]

A0A2S5Y0D3
 Bacteria (superkingdom)
I0ICG0
 Bacteria (superkingdom)

 48%|█████████████████████████████████████████████████████████████████▌                                                                       | 613/1281 [02:09<02:27,  4.54it/s]

D0L8H3
 Bacteria (superkingdom)
A0A1B9LFW3
 Bacteria (superkingdom)

 48%|█████████████████████████████████████████████████████████████████▊                                                                       | 615/1281 [02:09<02:23,  4.64it/s]

Q6ND34
 Bacteria (superkingdom)
A0A6H9GWG4
 Bacteria (superkingdom)

 48%|█████████████████████████████████████████████████████████████████▉                                                                       | 617/1281 [02:10<02:26,  4.52it/s]

Q5UZ98
 Archaea (superkingdom)
A0A2S0P9T4
 Bacteria (superkingdom)

 48%|██████████████████████████████████████████████████████████████████▎                                                                      | 620/1281 [02:10<02:12,  4.98it/s]

H2CDR5
 Bacteria (superkingdom)
T2KGT3
 Bacteria (superkingdom)

 49%|██████████████████████████████████████████████████████████████████▌                                                                      | 622/1281 [02:11<02:07,  5.15it/s]

A0A088E6Q7
 Archaea (superkingdom)
A0A258HS77
 Bacteria (superkingdom)

 49%|██████████████████████████████████████████████████████████████████▋                                                                      | 624/1281 [02:11<02:11,  5.01it/s]

E1V4T3
 Bacteria (superkingdom)
B7GKP4
 Bacteria (superkingdom)

 49%|██████████████████████████████████████████████████████████████████▊                                                                      | 625/1281 [02:12<02:36,  4.20it/s]

Q9QUT0
 Eukaryota (superkingdom)
I3Z3H7
 Bacteria (superkingdom)

 49%|███████████████████████████████████████████████████████████████████                                                                      | 627/1281 [02:12<02:24,  4.52it/s]

G7WCB6
 Bacteria (superkingdom)
A0A1Y6GLJ1
 Bacteria (superkingdom)

 49%|███████████████████████████████████████████████████████████████████▍                                                                     | 630/1281 [02:13<02:03,  5.27it/s]

A0A0S2DQB6
 Bacteria (superkingdom)
Q6CRN1
 Eukaryota (superkingdom)

 49%|███████████████████████████████████████████████████████████████████▌                                                                     | 632/1281 [02:13<02:08,  5.04it/s]

A0A401X433
 Bacteria (superkingdom)
A7HT14
 Bacteria (superkingdom)

 49%|███████████████████████████████████████████████████████████████████▊                                                                     | 634/1281 [02:13<02:06,  5.11it/s]

A0A009TDB1
 Bacteria (superkingdom)
D4XSW0
 Bacteria (superkingdom)

 50%|████████████████████████████████████████████████████████████████████                                                                     | 636/1281 [02:14<02:01,  5.32it/s]

B0SRS8
 Bacteria (superkingdom)
A0A149QSR6
 Bacteria (superkingdom)

 50%|████████████████████████████████████████████████████████████████████▏                                                                    | 637/1281 [02:14<02:30,  4.29it/s]

B1Y0E5
 Bacteria (superkingdom)
Q7UGU7
 Bacteria (superkingdom)

 50%|████████████████████████████████████████████████████████████████████▎                                                                    | 639/1281 [02:15<02:19,  4.61it/s]

A0A2S0Q8P1
 Bacteria (superkingdom)
F0ZPL3
 Eukaryota (superkingdom)

 50%|████████████████████████████████████████████████████████████████████▋                                                                    | 642/1281 [02:15<02:05,  5.07it/s]

A0A2T0GTU1
 Bacteria (superkingdom)
I4CCD1
 Bacteria (superkingdom)

 50%|████████████████████████████████████████████████████████████████████▊                                                                    | 644/1281 [02:15<02:05,  5.09it/s]

A0A9Q6P4A5
 Bacteria (superkingdom)
A0A418VIJ8
 Bacteria (superkingdom)

 50%|█████████████████████████████████████████████████████████████████████                                                                    | 646/1281 [02:16<01:59,  5.31it/s]

C1MX19
 Eukaryota (superkingdom)
A0A1B9BUZ8
 Bacteria (superkingdom)

 51%|█████████████████████████████████████████████████████████████████████▏                                                                   | 647/1281 [02:16<02:23,  4.41it/s]

K9W6F3
 Bacteria (superkingdom)
Q1K8A3
 Eukaryota (superkingdom)

 51%|█████████████████████████████████████████████████████████████████████▍                                                                   | 649/1281 [02:17<02:18,  4.58it/s]

L8GFX3
 Eukaryota (superkingdom)
A0A1G6ABL9
 Bacteria (superkingdom)

 51%|█████████████████████████████████████████████████████████████████████▌                                                                   | 651/1281 [02:17<02:13,  4.72it/s]

A0A087L0B9
 Bacteria (superkingdom)
A0A073CP02
 Bacteria (superkingdom)

 51%|█████████████████████████████████████████████████████████████████████▊                                                                   | 653/1281 [02:17<02:09,  4.83it/s]

A0A0A1ZJU5
 Bacteria (superkingdom)
A0A258HPP1
 Bacteria (superkingdom)

 51%|██████████████████████████████████████████████████████████████████████▏                                                                  | 656/1281 [02:18<01:55,  5.42it/s]

A0A149QAW7
 Bacteria (superkingdom)
D2V6Q5
 Eukaryota (superkingdom)

 51%|██████████████████████████████████████████████████████████████████████▎                                                                  | 658/1281 [02:18<01:55,  5.41it/s]

A0A1X4G8K1
 Bacteria (superkingdom)
A0A067Z3S3
 Bacteria (superkingdom)

 52%|██████████████████████████████████████████████████████████████████████▌                                                                  | 660/1281 [02:19<01:53,  5.47it/s]

A0A8F5ZDT8
 Archaea (superkingdom)
A0A854QN45
 Eukaryota (superkingdom)

 52%|██████████████████████████████████████████████████████████████████████▋                                                                  | 661/1281 [02:19<02:14,  4.61it/s]

A0A2N7LCD7
 Bacteria (superkingdom)
G7WFX2
 Bacteria (superkingdom)

 52%|███████████████████████████████████████████████████████████████████████                                                                  | 664/1281 [02:20<01:58,  5.20it/s]

A0A7S4GNJ2
 Eukaryota (superkingdom)
A4G0C5
 Archaea (superkingdom)

 52%|███████████████████████████████████████████████████████████████████████                                                                  | 665/1281 [02:20<02:16,  4.53it/s]

A6VE60
 Bacteria (superkingdom)
A0A1S1HM83
 Bacteria (superkingdom)

 52%|███████████████████████████████████████████████████████████████████████▍                                                                 | 668/1281 [02:20<01:58,  5.16it/s]

A0A037ZJY5
 Bacteria (superkingdom)
N1WR17
 Bacteria (superkingdom)

 52%|███████████████████████████████████████████████████████████████████████▋                                                                 | 670/1281 [02:21<02:01,  5.04it/s]

Q2W5V2
 Bacteria (superkingdom)
A1VIM5
 Bacteria (superkingdom)

 52%|███████████████████████████████████████████████████████████████████████▊                                                                 | 672/1281 [02:21<01:59,  5.10it/s]

A0A1Y5E3E3
 Bacteria (superkingdom)
A0A1T4SFK4
 Bacteria (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████                                                                 | 674/1281 [02:22<02:02,  4.97it/s]

A7RNC3
 Eukaryota (superkingdom)
M7XJ51
 Bacteria (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████▎                                                                | 676/1281 [02:22<01:57,  5.16it/s]

A0A399T909
 Bacteria (superkingdom)
A0A2N6P374
 Eukaryota (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████▌                                                                | 678/1281 [02:23<02:06,  4.77it/s]

H8L2Q4
 Bacteria (superkingdom)
D5EP68
 Bacteria (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████▋                                                                | 680/1281 [02:23<01:57,  5.13it/s]

E6SF19
 Bacteria (superkingdom)
A0A1T4SFY6
 Bacteria (superkingdom)

 53%|████████████████████████████████████████████████████████████████████████▉                                                                | 682/1281 [02:23<01:58,  5.05it/s]

D3LBI0
 Bacteria (superkingdom)
E6W5C1
 Bacteria (superkingdom)

 53%|█████████████████████████████████████████████████████████████████████████▏                                                               | 684/1281 [02:24<02:01,  4.92it/s]

Q0VPH4
 Bacteria (superkingdom)
K9WT03
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████▎                                                               | 686/1281 [02:24<01:55,  5.15it/s]

L0KW14
 Archaea (superkingdom)
A0A4R8H081
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████▌                                                               | 688/1281 [02:25<02:00,  4.94it/s]

A0A1B9N3H7
 Bacteria (superkingdom)
B0RC35
 Bacteria (superkingdom)

 54%|█████████████████████████████████████████████████████████████████████████▊                                                               | 690/1281 [02:25<01:58,  4.98it/s]

A0A420KGW4
 Bacteria (superkingdom)
A0A4R3NLV5
 Bacteria (superkingdom)

 54%|██████████████████████████████████████████████████████████████████████████                                                               | 692/1281 [02:25<02:01,  4.86it/s]

Q47K18
 Bacteria (superkingdom)
Q21P82
 Bacteria (superkingdom)

 54%|██████████████████████████████████████████████████████████████████████████▏                                                              | 694/1281 [02:26<01:57,  5.01it/s]

M1WRK6
 Bacteria (superkingdom)
A0A290XBB5
 Bacteria (superkingdom)

 54%|██████████████████████████████████████████████████████████████████████████▍                                                              | 696/1281 [02:26<01:55,  5.07it/s]

A0A6T9XUR2
 Bacteria (superkingdom)
A0A1J1JH03
 Bacteria (superkingdom)

 54%|██████████████████████████████████████████████████████████████████████████▋                                                              | 698/1281 [02:27<01:59,  4.86it/s]

I3R0S7
 Archaea (superkingdom)
A9UR54
 Eukaryota (superkingdom)

 55%|██████████████████████████████████████████████████████████████████████████▊                                                              | 700/1281 [02:27<01:57,  4.95it/s]

A0A1G7H8X3
 Bacteria (superkingdom)
A0A8G2F718
 Bacteria (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████                                                              | 702/1281 [02:28<01:57,  4.93it/s]

Q1H0G2
 Bacteria (superkingdom)
D0LAL7
 Bacteria (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████▎                                                             | 704/1281 [02:28<01:52,  5.14it/s]

C7LQR9
 Bacteria (superkingdom)
A0A1G5PWV0
 Bacteria (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████▌                                                             | 706/1281 [02:28<01:50,  5.21it/s]

K1K628
 Bacteria (superkingdom)
B9SXC7
 Eukaryota (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████▌                                                             | 707/1281 [02:29<02:16,  4.20it/s]

G7WA28
 Bacteria (superkingdom)
Q1IWN6
 Bacteria (superkingdom)

 55%|███████████████████████████████████████████████████████████████████████████▊                                                             | 709/1281 [02:29<02:07,  4.47it/s]

H6LKH9
 Bacteria (superkingdom)
A0A1H7CU41
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████                                                             | 711/1281 [02:30<02:03,  4.63it/s]

G8JUJ2
 Eukaryota (superkingdom)
A0A081N2G5
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████▎                                                            | 713/1281 [02:30<01:59,  4.75it/s]

A0A074ME37
 Bacteria (superkingdom)
Q0VQH6
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████▌                                                            | 716/1281 [02:30<01:50,  5.10it/s]

C8XB51
 Bacteria (superkingdom)
A1VIG8
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████▊                                                            | 718/1281 [02:31<01:47,  5.23it/s]

Q8GQS1
 Bacteria (superkingdom)
A0A1I7FBM5
 Bacteria (superkingdom)

 56%|████████████████████████████████████████████████████████████████████████████▉                                                            | 719/1281 [02:31<02:03,  4.56it/s]

A0A1M6ZMI3
 Bacteria (superkingdom)
A0A482PLH3
 Bacteria (superkingdom)

 56%|█████████████████████████████████████████████████████████████████████████████                                                            | 721/1281 [02:32<02:03,  4.55it/s]

A0RXK8
 Archaea (superkingdom)
D0KXQ0
 Bacteria (superkingdom)

 56%|█████████████████████████████████████████████████████████████████████████████▎                                                           | 723/1281 [02:32<02:03,  4.52it/s]

Q8JI14
 Eukaryota (superkingdom)
A0A7T4WEP4
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████▌                                                           | 725/1281 [02:32<01:58,  4.68it/s]

A0A4R3ZNW3
 Bacteria (superkingdom)
A0A074KY88
 Bacteria (superkingdom)

 57%|█████████████████████████████████████████████████████████████████████████████▊                                                           | 727/1281 [02:33<01:55,  4.78it/s]

A0A6M3ZKU5
 Bacteria (superkingdom)
M1SJL5
 Bacteria (superkingdom)

 57%|██████████████████████████████████████████████████████████████████████████████                                                           | 730/1281 [02:33<01:45,  5.21it/s]

A0A1W9KSU5
 Bacteria (superkingdom)
E3GI40
 Bacteria (superkingdom)

 57%|██████████████████████████████████████████████████████████████████████████████▎                                                          | 732/1281 [02:34<01:44,  5.26it/s]

A0A369NYJ2
 Bacteria (superkingdom)
A0AA92K392
 Bacteria (superkingdom)

 57%|██████████████████████████████████████████████████████████████████████████████▍                                                          | 733/1281 [02:34<02:01,  4.51it/s]

O04161
 Eukaryota (superkingdom)
A9BQZ4
 Bacteria (superkingdom)

 57%|██████████████████████████████████████████████████████████████████████████████▌                                                          | 735/1281 [02:35<01:56,  4.69it/s]

A0A6N2Z556
 Bacteria (superkingdom)
A0A8H6NAG3
 Eukaryota (superkingdom)

 58%|██████████████████████████████████████████████████████████████████████████████▉                                                          | 738/1281 [02:35<01:42,  5.31it/s]

A0A2T9X1V4
 Archaea (superkingdom)
Q2J376
 Bacteria (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████▏                                                         | 740/1281 [02:35<01:41,  5.32it/s]

A0A0F5EZP7
 Bacteria (superkingdom)
A0A7G5DK18
 Bacteria (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████▏                                                         | 741/1281 [02:36<02:01,  4.43it/s]

M9YAI9
 Bacteria (superkingdom)
D2ZRW2
 Archaea (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████▌                                                         | 744/1281 [02:36<01:41,  5.30it/s]

G7UUY6
 Bacteria (superkingdom)
A0A8H4GS02
 Eukaryota (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████▊                                                         | 746/1281 [02:37<01:39,  5.38it/s]

A0A2T5IHP0
 Bacteria (superkingdom)
A0A165MAC2
 Bacteria (superkingdom)

 58%|███████████████████████████████████████████████████████████████████████████████▉                                                         | 747/1281 [02:37<01:57,  4.54it/s]

A0A7S4LPS8
 Eukaryota (superkingdom)
A0A075JIN0
 Bacteria (superkingdom)

 58%|████████████████████████████████████████████████████████████████████████████████                                                         | 749/1281 [02:37<01:56,  4.57it/s]

C8X554
 Bacteria (superkingdom)
B8FZP7
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████▎                                                        | 751/1281 [02:38<01:55,  4.60it/s]

Q5KAF6
 Eukaryota (superkingdom)
A0A427KNL6
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████▌                                                        | 753/1281 [02:38<01:52,  4.70it/s]

A0A7G5DPV0
 Bacteria (superkingdom)
Q22947
 Eukaryota (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████▋                                                        | 755/1281 [02:39<01:50,  4.78it/s]

A0A1S1HRJ0
 Bacteria (superkingdom)
A0A3N1VXY4
 Bacteria (superkingdom)

 59%|████████████████████████████████████████████████████████████████████████████████▉                                                        | 757/1281 [02:39<01:48,  4.83it/s]

A0A2S7YPJ9
 Eukaryota (superkingdom)
I0JI83
 Bacteria (superkingdom)

 59%|█████████████████████████████████████████████████████████████████████████████████▎                                                       | 760/1281 [02:40<01:38,  5.28it/s]

A0A7U3YMN6
 Bacteria (superkingdom)
Q9BLG3
 Eukaryota (superkingdom)

 59%|█████████████████████████████████████████████████████████████████████████████████▍                                                       | 762/1281 [02:40<01:37,  5.33it/s]

A0A1H9RTW8
 Bacteria (superkingdom)
A0A1I4W3A0
 Bacteria (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████▋                                                       | 764/1281 [02:40<01:41,  5.11it/s]

A0A0B4M163
 Eukaryota (superkingdom)
U2EN72
 Bacteria (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████▊                                                       | 765/1281 [02:41<01:47,  4.78it/s]

A0A2W5VAZ2
 Bacteria (superkingdom)

 60%|█████████████████████████████████████████████████████████████████████████████████▉                                                       | 766/1281 [02:41<01:46,  4.82it/s]

E4YA63
 Eukaryota (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████                                                       | 767/1281 [02:41<01:50,  4.66it/s]

D5ELM4
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 769/1281 [02:42<01:45,  4.87it/s]

M9RJS5
 Bacteria (superkingdom)
A0A2G3E8V2
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████▍                                                      | 771/1281 [02:42<01:41,  5.02it/s]

Q5FSX6
 Bacteria (superkingdom)
I0HKQ8
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████▌                                                      | 772/1281 [02:42<01:44,  4.85it/s]

A0A833H2R7
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████▋                                                      | 773/1281 [02:42<01:46,  4.79it/s]

B8ENL9
 Bacteria (superkingdom)

 60%|██████████████████████████████████████████████████████████████████████████████████▉                                                      | 775/1281 [02:43<01:42,  4.96it/s]

B3DUX7
 Bacteria (superkingdom)
A0A1D8UWJ6
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████                                                      | 777/1281 [02:43<01:37,  5.19it/s]

D5E995
 Archaea (superkingdom)
A0A7U8C2Y6
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████▎                                                     | 779/1281 [02:44<01:40,  5.01it/s]

L0KGR8
 Bacteria (superkingdom)
B0VMH1
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████▌                                                     | 781/1281 [02:44<01:45,  4.73it/s]

P40260
 Eukaryota (superkingdom)
L0JT30
 Archaea (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████▋                                                     | 783/1281 [02:44<01:38,  5.07it/s]

C1GR74
 Eukaryota (superkingdom)
A0A423Y4I6
 Bacteria (superkingdom)

 61%|███████████████████████████████████████████████████████████████████████████████████▉                                                     | 785/1281 [02:45<01:35,  5.22it/s]

A0A4P7UHQ5
 Bacteria (superkingdom)
A0A8E2R1Y5
 Bacteria (superkingdom)

 61%|████████████████████████████████████████████████████████████████████████████████████▏                                                    | 787/1281 [02:45<01:34,  5.25it/s]

I5BYV5
 Bacteria (superkingdom)
A0A6B8N021
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████▍                                                    | 789/1281 [02:46<01:32,  5.34it/s]

A0A7G5DPV1
 Bacteria (superkingdom)
A0A2G5RQK9
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████▌                                                    | 791/1281 [02:46<01:31,  5.36it/s]

A0A5M4B0G1
 Bacteria (superkingdom)
A0A6S5K4J1
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████▊                                                    | 793/1281 [02:46<01:34,  5.17it/s]

C1D4X0
 Bacteria (superkingdom)
A1SVA8
 Bacteria (superkingdom)

 62%|████████████████████████████████████████████████████████████████████████████████████▉                                                    | 794/1281 [02:47<01:55,  4.23it/s]

H1YF74
 Bacteria (superkingdom)
A0A8B4RWH8
 Bacteria (superkingdom)

 62%|█████████████████████████████████████████████████████████████████████████████████████▏                                                   | 796/1281 [02:47<01:45,  4.58it/s]

A0A0A0D6K5
 Bacteria (superkingdom)
A0A0A2BBY0
 Bacteria (superkingdom)

 62%|█████████████████████████████████████████████████████████████████████████████████████▎                                                   | 798/1281 [02:48<01:41,  4.74it/s]

A0A089ZBW5
 Archaea (superkingdom)
A0A068TC78
 Bacteria (superkingdom)

 63%|█████████████████████████████████████████████████████████████████████████████████████▋                                                   | 801/1281 [02:48<01:32,  5.19it/s]

Q46G49
 Archaea (superkingdom)
A1CQ21
 Eukaryota (superkingdom)

 63%|█████████████████████████████████████████████████████████████████████████████████████▉                                                   | 803/1281 [02:49<01:35,  5.00it/s]

A0A1G6ABX1
 Bacteria (superkingdom)
E1SLM7
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████                                                   | 805/1281 [02:49<01:34,  5.05it/s]

K5CFE5
 Bacteria (superkingdom)
Q2YLQ6
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████▎                                                  | 807/1281 [02:49<01:37,  4.88it/s]

Q0G2V0
 Bacteria (superkingdom)
A4ABK3
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████▌                                                  | 809/1281 [02:50<01:33,  5.04it/s]

A0A9Q5QVI9
 Bacteria (superkingdom)
A0A4Q7Y9I7
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████▋                                                  | 811/1281 [02:50<01:35,  4.92it/s]

A9HMD6
 Bacteria (superkingdom)
K9YN27
 Bacteria (superkingdom)

 63%|██████████████████████████████████████████████████████████████████████████████████████▉                                                  | 813/1281 [02:51<01:35,  4.90it/s]

Q9UBD6
 Eukaryota (superkingdom)
D9SI59
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████▏                                                 | 815/1281 [02:51<01:30,  5.12it/s]

Q8I0L6
 Eukaryota (superkingdom)
A0A142VAD6
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████▍                                                 | 817/1281 [02:52<01:28,  5.24it/s]

G3IYW0
 Bacteria (superkingdom)
A0A062IU58
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████▍                                                 | 818/1281 [02:52<01:46,  4.36it/s]

R1D1H4
 Eukaryota (superkingdom)
A0A366XFS8
 Bacteria (superkingdom)

 64%|███████████████████████████████████████████████████████████████████████████████████████▊                                                 | 821/1281 [02:52<01:29,  5.16it/s]

A0A7S4GNF3
 Eukaryota (superkingdom)
F0J6E8
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████                                                 | 823/1281 [02:53<01:30,  5.05it/s]

A0A7U4DN04
 Bacteria (superkingdom)
V4RHR4
 Bacteria (superkingdom)

 64%|████████████████████████████████████████████████████████████████████████████████████████▏                                                | 825/1281 [02:53<01:29,  5.10it/s]

F7ZJM0
 Bacteria (superkingdom)
A0A2S5XAB8
 Bacteria (superkingdom)

 65%|████████████████████████████████████████████████████████████████████████████████████████▍                                                | 827/1281 [02:54<01:31,  4.94it/s]

U5C4L4
 Bacteria (superkingdom)
Q21J04
 Bacteria (superkingdom)

 65%|████████████████████████████████████████████████████████████████████████████████████████▌                                                | 828/1281 [02:54<01:36,  4.70it/s]

A0A142NNN1
 Bacteria (superkingdom)

 65%|████████████████████████████████████████████████████████████████████████████████████████▋                                                | 829/1281 [02:54<01:35,  4.75it/s]

H1Y7T6
 Bacteria (superkingdom)

 65%|████████████████████████████████████████████████████████████████████████████████████████▊                                                | 831/1281 [02:55<01:35,  4.71it/s]

F5R974
 Bacteria (superkingdom)
B0DU91
 Eukaryota (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████                                                | 833/1281 [02:55<01:33,  4.82it/s]

A2BP62
 Bacteria (superkingdom)
A7HSN9
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▏                                               | 834/1281 [02:55<01:33,  4.77it/s]

A0A377I7W9
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▍                                               | 836/1281 [02:56<01:28,  5.05it/s]

D2RU19
 Archaea (superkingdom)
G7WJN0
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▌                                               | 837/1281 [02:56<01:42,  4.34it/s]

E2SD33
 Bacteria (superkingdom)
A0A0D7F2Y9
 Bacteria (superkingdom)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▋                                               | 839/1281 [02:56<01:36,  4.57it/s]

A0AA92EGF5
 Bacteria (superkingdom)
A0A9E9LXV9
 Bacteria (superkingdom)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▉                                               | 841/1281 [02:57<01:37,  4.53it/s]

A4BEP1
 Bacteria (superkingdom)
A0A0E3WZH5
 Archaea (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▎                                              | 844/1281 [02:57<01:25,  5.10it/s]

F7ZEU9
 Bacteria (superkingdom)
A5E3X2
 Eukaryota (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▍                                              | 846/1281 [02:58<01:23,  5.22it/s]

A0A0A3XTJ3
 Bacteria (superkingdom)
A0A830ZZN8
 Bacteria (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▋                                              | 848/1281 [02:58<01:19,  5.42it/s]

A0A1S8D478
 Bacteria (superkingdom)
J7IVQ1
 Bacteria (superkingdom)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▉                                              | 850/1281 [02:58<01:24,  5.10it/s]

A0A2U1SS17
 Bacteria (superkingdom)
S3K1S2
 Bacteria (superkingdom)

 66%|███████████████████████████████████████████████████████████████████████████████████████████                                              | 851/1281 [02:59<01:38,  4.37it/s]

C6XKC2
 Bacteria (superkingdom)
A0A2S7YIM5
 Eukaryota (superkingdom)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▏                                             | 853/1281 [02:59<01:34,  4.53it/s]

K2IMJ7
 Bacteria (superkingdom)
Q5P1S8
 Bacteria (superkingdom)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▍                                             | 855/1281 [03:00<01:30,  4.71it/s]

A0A7T5BFQ2
 Bacteria (superkingdom)
A0A556SRH6
 Bacteria (superkingdom)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▋                                             | 857/1281 [03:00<01:33,  4.54it/s]

A8P923
 Eukaryota (superkingdom)
A0A7G5DKA9
 Bacteria (superkingdom)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▊                                             | 859/1281 [03:01<01:31,  4.60it/s]

L8JUH3
 Bacteria (superkingdom)
A0A0D2LEF5
 Eukaryota (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████                                             | 861/1281 [03:01<01:28,  4.72it/s]

A0A258FTB0
 Bacteria (superkingdom)
A0A5P9P1L2
 Archaea (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 863/1281 [03:01<01:30,  4.64it/s]

M8E0R3
 Bacteria (superkingdom)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 864/1281 [03:02<02:02,  3.40it/s]

A0A6J5IRX5
 Bacteria (superkingdom)
W5WIX6
 Bacteria (superkingdom)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 866/1281 [03:02<01:52,  3.70it/s]

Q82X47
 Bacteria (superkingdom)
I4DBY0
 Bacteria (superkingdom)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 868/1281 [03:03<01:43,  4.01it/s]

A0A6F8TLE9
 Bacteria (superkingdom)
A0A1G7UZX2
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 871/1281 [03:03<01:26,  4.75it/s]

A0A6P4JM51
 Eukaryota (superkingdom)
G0J614
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 873/1281 [03:04<01:22,  4.96it/s]

U2WTW8
 Bacteria (superkingdom)
A0A642KQG8
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 875/1281 [03:04<01:18,  5.20it/s]

Q1AUG3
 Bacteria (superkingdom)
A0A6G9Y3Q0
 Bacteria (superkingdom)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 876/1281 [03:05<01:35,  4.26it/s]

B8J5X4
 Bacteria (superkingdom)
M7NFH3
 Bacteria (superkingdom)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 878/1281 [03:05<01:28,  4.58it/s]

A0A0E3R6S1
 Archaea (superkingdom)
Q2IHY5
 Bacteria (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████                                           | 880/1281 [03:05<01:28,  4.54it/s]

A7I8Z2
 Archaea (superkingdom)
L1IYP4
 Eukaryota (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 882/1281 [03:06<01:27,  4.54it/s]

B4HDZ9
 Eukaryota (superkingdom)
A0A366WYI9
 Bacteria (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 884/1281 [03:06<01:27,  4.54it/s]

E4TJ50
 Bacteria (superkingdom)
A0A7S0ILH2
 Eukaryota (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 886/1281 [03:07<01:27,  4.54it/s]

A4BAE1
 Bacteria (superkingdom)
B3QRJ4
 Bacteria (superkingdom)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 888/1281 [03:07<01:24,  4.64it/s]

A0A5C5BWI6
 Bacteria (superkingdom)
Q7NQY2
 Bacteria (superkingdom)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 891/1281 [03:08<01:14,  5.23it/s]

A0A091AXI3
 Bacteria (superkingdom)
Q1QSQ2
 Bacteria (superkingdom)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 892/1281 [03:08<01:24,  4.62it/s]

R4FZE3
 Bacteria (superkingdom)
A0A2N0MZ27
 Bacteria (superkingdom)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 894/1281 [03:08<01:24,  4.56it/s]

A9BTK1
 Bacteria (superkingdom)
A0A242NIL1
 Bacteria (superkingdom)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 896/1281 [03:09<01:24,  4.55it/s]

G0LFE3
 Archaea (superkingdom)
A0A1B9NQ91
 Bacteria (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████                                         | 898/1281 [03:09<01:22,  4.67it/s]

A0A5M5PZE2
 Bacteria (superkingdom)
A0A0D2NYP3
 Eukaryota (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 900/1281 [03:10<01:21,  4.70it/s]

D9QPE5
 Bacteria (superkingdom)
I5B3H0
 Bacteria (superkingdom)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 903/1281 [03:10<01:12,  5.22it/s]

L1IYW7
 Eukaryota (superkingdom)
C6WEW7
 Bacteria (superkingdom)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 904/1281 [03:10<01:24,  4.46it/s]

B7FW68
 Eukaryota (superkingdom)
F4GED5
 Bacteria (superkingdom)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 906/1281 [03:11<01:21,  4.63it/s]

A0A4R8GSH7
 Bacteria (superkingdom)
A0A1W2H3F0
 Bacteria (superkingdom)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████                                        | 908/1281 [03:11<01:18,  4.76it/s]

A0A3E2T713
 Bacteria (superkingdom)
A0A0H3KTD3
 Bacteria (superkingdom)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 910/1281 [03:12<01:16,  4.83it/s]

A0A1Y4LM49
 Bacteria (superkingdom)
G2PRJ6
 Bacteria (superkingdom)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 913/1281 [03:12<01:11,  5.12it/s]

A0A0X8X7Y7
 Bacteria (superkingdom)
K8EJ02
 Bacteria (superkingdom)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 914/1281 [03:12<01:15,  4.83it/s]

A0A1L3F1X5
 Bacteria (superkingdom)

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 916/1281 [03:13<01:13,  4.95it/s]

G8TK77
 Bacteria (superkingdom)
A0A855F5Y8
 Bacteria (superkingdom)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 918/1281 [03:13<01:11,  5.04it/s]

A0A975BTN0
 Bacteria (superkingdom)
A0A562RGZ4
 Bacteria (superkingdom)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 920/1281 [03:14<01:10,  5.15it/s]

G5EB09
 Eukaryota (superkingdom)
A0A833LX85
 Bacteria (superkingdom)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 922/1281 [03:14<01:12,  4.95it/s]

U1H1F7
 Bacteria (superkingdom)
K8W1E2
 Bacteria (superkingdom)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 924/1281 [03:15<01:10,  5.05it/s]

E3HJW8
 Bacteria (superkingdom)
Q7SEH0
 Eukaryota (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████                                      | 926/1281 [03:15<01:10,  5.04it/s]

Q47X17
 Bacteria (superkingdom)
B0DXT9
 Eukaryota (superkingdom)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 928/1281 [03:15<01:10,  4.97it/s]

A0A3G9G2C9
 Bacteria (superkingdom)
Q95P70
 Eukaryota (superkingdom)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 930/1281 [03:16<01:12,  4.86it/s]

A0A837C6X5
 Bacteria (superkingdom)
Q89WR5
 Bacteria (superkingdom)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 932/1281 [03:16<01:11,  4.88it/s]

A6DUG4
 Bacteria (superkingdom)
D7UQE2
 Eukaryota (superkingdom)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 934/1281 [03:17<01:08,  5.05it/s]

A0A2I1M481
 Bacteria (superkingdom)
A0A0T7GZ59
 Bacteria (superkingdom)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 936/1281 [03:17<01:05,  5.27it/s]

O66395
 Bacteria (superkingdom)
J3EXK0
 Archaea (superkingdom)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 938/1281 [03:17<01:06,  5.13it/s]

A0A1B9MYL7
 Bacteria (superkingdom)
K9U8C7
 Bacteria (superkingdom)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 940/1281 [03:18<01:05,  5.24it/s]

E2SD44
 Bacteria (superkingdom)
H6LKH6
 Bacteria (superkingdom)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 941/1281 [03:18<01:19,  4.26it/s]

Q605Y6
 Bacteria (superkingdom)
A0A9Q9D9I3
 Bacteria (superkingdom)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 943/1281 [03:19<01:14,  4.55it/s]

A0A6N2TIA4
 Bacteria (superkingdom)
A0A1E3PQH0
 Eukaryota (superkingdom)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 946/1281 [03:19<01:05,  5.13it/s]

A4CMI3
 Bacteria (superkingdom)
Q1K0H9
 Bacteria (superkingdom)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 948/1281 [03:20<01:03,  5.24it/s]

A0A0S6UEK9
 Bacteria (superkingdom)
A0A0H3LUA3
 Bacteria (superkingdom)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 950/1281 [03:20<01:05,  5.08it/s]

B9LU00
 Archaea (superkingdom)
A9BIZ7
 Bacteria (superkingdom)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 952/1281 [03:20<01:07,  4.91it/s]

A0A7H8UK07
 Bacteria (superkingdom)
E3H8C9
 Bacteria (superkingdom)

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 954/1281 [03:21<01:06,  4.92it/s]

M2A398
 Bacteria (superkingdom)
Q1QS12
 Bacteria (superkingdom)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 955/1281 [03:21<01:19,  4.11it/s]

G0VI62
 Eukaryota (superkingdom)
A0A1Z3MS36
 Bacteria (superkingdom)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 958/1281 [03:22<01:02,  5.14it/s]

A0A0B5FNH4
 Bacteria (superkingdom)
D9SI36
 Bacteria (superkingdom)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 960/1281 [03:22<01:02,  5.11it/s]

A0A410JZR4
 Bacteria (superkingdom)
F7ZJZ1
 Bacteria (superkingdom)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 962/1281 [03:23<01:03,  5.01it/s]

F0ZCX7
 Eukaryota (superkingdom)
W0DZX1
 Bacteria (superkingdom)

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 964/1281 [03:23<01:01,  5.12it/s]

A0A4R3ZZ35
 Bacteria (superkingdom)
A0A317G0I6
 Bacteria (superkingdom)

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 966/1281 [03:23<01:02,  5.01it/s]

Q0ARJ4
 Bacteria (superkingdom)
A7I8Z4
 Archaea (superkingdom)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 968/1281 [03:24<01:04,  4.83it/s]

T2KJ59
 Bacteria (superkingdom)
I3C0V3
 Bacteria (superkingdom)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 970/1281 [03:24<01:04,  4.81it/s]

E3H8A6
 Bacteria (superkingdom)
B2IJT1
 Bacteria (superkingdom)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 972/1281 [03:25<01:02,  4.96it/s]

A0A2G6JLT9
 Bacteria (superkingdom)
A3ZZL7
 Bacteria (superkingdom)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 974/1281 [03:25<01:02,  4.91it/s]

A0A2T0XPP2
 Bacteria (superkingdom)
Q31CR9
 Bacteria (superkingdom)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 976/1281 [03:25<01:01,  4.97it/s]

A0A1R1IDV3
 Bacteria (superkingdom)
K2JVF8
 Bacteria (superkingdom)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 977/1281 [03:26<01:02,  4.90it/s]

V5BYZ7
 Bacteria (superkingdom)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 979/1281 [03:26<01:02,  4.82it/s]

D8J4C6
 Archaea (superkingdom)
D4H5F9
 Bacteria (superkingdom)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 981/1281 [03:27<00:59,  5.04it/s]

K9ZG59
 Bacteria (superkingdom)
A0AA86YS65
 Bacteria (superkingdom)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 983/1281 [03:27<00:56,  5.27it/s]

Q608B6
 Bacteria (superkingdom)
A0A562BXM4
 Bacteria (superkingdom)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 985/1281 [03:27<00:54,  5.39it/s]

A0A401WXG0
 Bacteria (superkingdom)
A0A857DMN9
 Bacteria (superkingdom)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 986/1281 [03:28<01:04,  4.60it/s]

A0A1X6N3Q5
 Eukaryota (superkingdom)
A0A173R3X4
 Bacteria (superkingdom)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 988/1281 [03:28<01:03,  4.64it/s]

Q63EK5
 Bacteria (superkingdom)
K9ZLY2
 Bacteria (superkingdom)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 990/1281 [03:28<01:01,  4.74it/s]

A0A533I6R2
 Bacteria (superkingdom)
I0WJ97
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 993/1281 [03:29<00:56,  5.12it/s]

K0N2R5
 Bacteria (superkingdom)
M0J579
 Archaea (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 994/1281 [03:29<01:04,  4.42it/s]

B8GGC1
 Archaea (superkingdom)
A0A6H9GFU4
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 996/1281 [03:30<01:04,  4.42it/s]

C6CBB1
 Bacteria (superkingdom)
A0A510HHK8
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 998/1281 [03:30<01:01,  4.63it/s]

A0A1B9MBX6
 Bacteria (superkingdom)
A0A9Y2AG30
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 1001/1281 [03:31<00:55,  5.07it/s]

E8RSE4
 Bacteria (superkingdom)
F2B2B8
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 1003/1281 [03:31<00:53,  5.21it/s]

Q7UYZ3
 Bacteria (superkingdom)
I1YJH7
 Bacteria (superkingdom)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 1005/1281 [03:32<00:54,  5.06it/s]

A0A853MG28
 Bacteria (superkingdom)
A0A0L0STS6
 Eukaryota (superkingdom)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 1007/1281 [03:32<00:55,  4.97it/s]

A0A251XU71
 Bacteria (superkingdom)
Q60BI2
 Bacteria (superkingdom)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 1009/1281 [03:32<00:55,  4.92it/s]

A0A829X098
 Bacteria (superkingdom)
F3KUN4
 Bacteria (superkingdom)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 1011/1281 [03:33<00:53,  5.08it/s]

Q60C43
 Bacteria (superkingdom)
A0A0T7FAP8
 Bacteria (superkingdom)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 1012/1281 [03:33<00:56,  4.77it/s]

A0A3E2TW06
 Bacteria (superkingdom)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 1014/1281 [03:33<00:54,  4.86it/s]

W0E077
 Bacteria (superkingdom)
A0KPE9
 Bacteria (superkingdom)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 1016/1281 [03:34<00:52,  5.05it/s]

R7PZ71
 Archaea (superkingdom)
A0A0A1ZMZ9
 Bacteria (superkingdom)

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 1018/1281 [03:34<00:54,  4.81it/s]

A0AA40J491
 Bacteria (superkingdom)
D3S2L0
 Archaea (superkingdom)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 1019/1281 [03:34<00:53,  4.86it/s]

A0A373FQ71
 Bacteria (superkingdom)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 1020/1281 [03:35<00:53,  4.88it/s]

A0A0A2C6L1
 Bacteria (superkingdom)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 1022/1281 [03:35<00:52,  4.89it/s]

Q7W7D3
 Bacteria (superkingdom)
A0A165K0X5
 Bacteria (superkingdom)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 1023/1281 [03:35<00:52,  4.88it/s]

A0A2S5X482
 Bacteria (superkingdom)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 1025/1281 [03:36<00:52,  4.90it/s]

R9GM11
 Bacteria (superkingdom)
Q0G0A3
 Bacteria (superkingdom)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 1027/1281 [03:36<00:51,  4.91it/s]

D4GLQ6
 Bacteria (superkingdom)
E7RJZ0
 Bacteria (superkingdom)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 1029/1281 [03:37<00:50,  5.02it/s]

F8IJE0
 Bacteria (superkingdom)
A0A1V2XMU9
 Bacteria (superkingdom)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 1031/1281 [03:37<00:48,  5.15it/s]

Q7TNN9
 Eukaryota (superkingdom)
A0A1G5RZU9
 Bacteria (superkingdom)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 1032/1281 [03:37<00:51,  4.84it/s]

A0A2N6K4Y5
 Bacteria (superkingdom)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1034/1281 [03:38<00:49,  4.99it/s]

B0SLB7
 Bacteria (superkingdom)
A0A251YFS0
 Bacteria (superkingdom)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 1035/1281 [03:38<00:50,  4.88it/s]

B9WDK0
 Eukaryota (superkingdom)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 1037/1281 [03:38<00:48,  5.00it/s]

Q7N0M6
 Bacteria (superkingdom)
A0A0M2LU39
 Bacteria (superkingdom)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 1039/1281 [03:39<00:47,  5.06it/s]

F4B548
 Archaea (superkingdom)
D6Z5V9
 Bacteria (superkingdom)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 1041/1281 [03:39<00:46,  5.14it/s]

A0A4R2M206
 Bacteria (superkingdom)
A0A1E2SKM1
 Bacteria (superkingdom)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 1043/1281 [03:39<00:45,  5.22it/s]

A0A127JTU2
 Bacteria (superkingdom)
A0A212AV03
 Bacteria (superkingdom)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 1045/1281 [03:40<00:44,  5.30it/s]

G4QHD2
 Bacteria (superkingdom)
A0A021VMC6
 Bacteria (superkingdom)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 1047/1281 [03:40<00:44,  5.31it/s]

A0A2J7TJ33
 Bacteria (superkingdom)
G7WDB5
 Bacteria (superkingdom)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 1049/1281 [03:41<00:45,  5.05it/s]

Q6BK68
 Eukaryota (superkingdom)
Q1K3N8
 Bacteria (superkingdom)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 1051/1281 [03:41<00:47,  4.81it/s]

A0AA91Q161
 Eukaryota (superkingdom)
A0NJ07
 Bacteria (superkingdom)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 1052/1281 [03:41<00:46,  4.88it/s]

A0A316BQ38
 Bacteria (superkingdom)
A0A377PLP5
 Bacteria (superkingdom)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 1055/1281 [03:42<00:45,  4.96it/s]

W7QGM4
 Bacteria (superkingdom)
A0A015YIP3
 Bacteria (superkingdom)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 1056/1281 [03:42<00:44,  5.04it/s]

A0A060UWC8
 Bacteria (superkingdom)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 1058/1281 [03:42<00:44,  5.06it/s]

A0A1I4ZIZ6
 Bacteria (superkingdom)
A0A264VQM8
 Bacteria (superkingdom)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 1060/1281 [03:43<00:42,  5.15it/s]

A9AUR8
 Bacteria (superkingdom)
A0A1W5PRD1
 Eukaryota (superkingdom)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 1062/1281 [03:43<00:41,  5.23it/s]

A0A0E3BR91
 Bacteria (superkingdom)
A0A1B0ZRL8
 Bacteria (superkingdom)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 1064/1281 [03:44<00:42,  5.07it/s]

B9ACS5
 Archaea (superkingdom)
Q92BJ7
 Bacteria (superkingdom)

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 1066/1281 [03:44<00:43,  4.93it/s]

F2JTN3
 Bacteria (superkingdom)
A1AVV2
 Bacteria (superkingdom)

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 1068/1281 [03:45<00:40,  5.20it/s]

D2Q0J8
 Bacteria (superkingdom)
A0A3S9N9F3
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 1070/1281 [03:45<00:42,  4.96it/s]

A8ZQD5
 Bacteria (superkingdom)
C3X831
 Bacteria (superkingdom)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1072/1281 [03:45<00:41,  5.08it/s]

A0A1M6BPM0
 Bacteria (superkingdom)
A0A8F5VN39
 Archaea (superkingdom)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 1074/1281 [03:46<00:39,  5.21it/s]

A0A1E5C7W4
 Bacteria (superkingdom)
A0A2S5WV24
 Bacteria (superkingdom)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 1076/1281 [03:46<00:41,  4.94it/s]

A0A833GZR2
 Bacteria (superkingdom)
C7M2A9
 Bacteria (superkingdom)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 1078/1281 [03:47<00:40,  4.99it/s]

A6W7U2
 Bacteria (superkingdom)
W0JIB3
 Archaea (superkingdom)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 1080/1281 [03:47<00:39,  5.11it/s]

Q07UM3
 Bacteria (superkingdom)
A0A066ZRQ5
 Bacteria (superkingdom)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 1082/1281 [03:47<00:41,  4.78it/s]

S0G181
 Bacteria (superkingdom)
D3PAH1
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 1084/1281 [03:48<00:38,  5.10it/s]

Q4WHC6
 Eukaryota (superkingdom)
A0AA94HTL8
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 1085/1281 [03:48<00:45,  4.29it/s]

D5ASL9
 Bacteria (superkingdom)
A0A4U1JNL6
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 1087/1281 [03:49<00:43,  4.46it/s]

M0MDP9
 Archaea (superkingdom)
A0A653N397
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 1089/1281 [03:49<00:40,  4.71it/s]

A0A2S8GSU9
 Bacteria (superkingdom)
A0A097R891
 Bacteria (superkingdom)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 1091/1281 [03:49<00:39,  4.79it/s]

A0A8H7U3I1
 Eukaryota (superkingdom)
A0A1H1MB73
 Bacteria (superkingdom)

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 1093/1281 [03:50<00:38,  4.85it/s]

A0A016XDZ5
 Bacteria (superkingdom)
A0A1B9JHS5
 Bacteria (superkingdom)

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 1095/1281 [03:50<00:39,  4.73it/s]

D3PE53
 Bacteria (superkingdom)
A0A9J9BAE8
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 1097/1281 [03:51<00:39,  4.67it/s]

Q2RM12
 Bacteria (superkingdom)
A0A3N0AQL8
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 1100/1281 [03:51<00:35,  5.16it/s]

C5KTM6
 Eukaryota (superkingdom)
M1P5F0
 Bacteria (superkingdom)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 1101/1281 [03:52<00:39,  4.59it/s]

I1YG38
 Bacteria (superkingdom)
A0A660CH85
 Bacteria (superkingdom)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 1104/1281 [03:52<00:34,  5.09it/s]

A0A2N7L7C8
 Bacteria (superkingdom)
Q5KZZ9
 Bacteria (superkingdom)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 1105/1281 [03:52<00:40,  4.36it/s]

M1NZT5
 Bacteria (superkingdom)
A0A225CMT8
 Bacteria (superkingdom)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 1107/1281 [03:53<00:37,  4.60it/s]

A0A068NV61
 Bacteria (superkingdom)
H2CJI0
 Bacteria (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 1110/1281 [03:53<00:33,  5.04it/s]

B0DU93
 Eukaryota (superkingdom)
Q221S8
 Bacteria (superkingdom)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 1111/1281 [03:54<00:38,  4.43it/s]

F4Y3C5
 Bacteria (superkingdom)
Q94CJ2
 Eukaryota (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 1113/1281 [03:54<00:37,  4.46it/s]

M0D3Q9
 Archaea (superkingdom)
A0A3P2A7W8
 Bacteria (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 1115/1281 [03:55<00:36,  4.56it/s]

C0GKN4
 Bacteria (superkingdom)
Q7T3R4
 Eukaryota (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 1118/1281 [03:55<00:32,  5.05it/s]

A0A562USB9
 Bacteria (superkingdom)
A2SS52
 Archaea (superkingdom)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 1120/1281 [03:55<00:31,  5.17it/s]

A0A211ZGL5
 Bacteria (superkingdom)
A0A4V3ALP8
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 1122/1281 [03:56<00:31,  5.02it/s]

A0A147GP06
 Bacteria (superkingdom)
H2IZ00
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 1124/1281 [03:56<00:30,  5.15it/s]

Q45HK8
 Bacteria (superkingdom)
A0A6C8LST1
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 1125/1281 [03:57<00:32,  4.79it/s]

A0A257T8W6
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 1127/1281 [03:57<00:31,  4.90it/s]

Q5P470
 Bacteria (superkingdom)
I5AZQ4
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 1128/1281 [03:57<00:32,  4.78it/s]

Q07UM1
 Bacteria (superkingdom)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 1130/1281 [03:58<00:30,  4.98it/s]

E5B358
 Bacteria (superkingdom)
A0A1Y4L5P0
 Bacteria (superkingdom)

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 1132/1281 [03:58<00:29,  5.03it/s]

Q3AFY9
 Bacteria (superkingdom)
B0BZN3
 Bacteria (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 1134/1281 [03:58<00:28,  5.10it/s]

A0A1Q2C7H7
 Bacteria (superkingdom)
A0A4R5U5V1
 Bacteria (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 1136/1281 [03:59<00:27,  5.22it/s]

H6LKX6
 Bacteria (superkingdom)
A0A1Y0UZX2
 Bacteria (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 1138/1281 [03:59<00:28,  4.97it/s]

F6BEI0
 Archaea (superkingdom)
M9RKT6
 Bacteria (superkingdom)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 1139/1281 [04:00<00:32,  4.37it/s]

A7SGD4
 Eukaryota (superkingdom)
A0A257TE48
 Bacteria (superkingdom)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 1142/1281 [04:00<00:27,  5.03it/s]

R1FI09
 Eukaryota (superkingdom)
E4N1T5
 Bacteria (superkingdom)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 1144/1281 [04:00<00:27,  5.06it/s]

U1PIR6
 Archaea (superkingdom)
F2JYR9
 Bacteria (superkingdom)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 1146/1281 [04:01<00:25,  5.24it/s]

Q84KJ7
 Eukaryota (superkingdom)
A0A2S8FTB5
 Bacteria (superkingdom)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 1148/1281 [04:01<00:26,  5.02it/s]

D2R647
 Bacteria (superkingdom)
G9Y5B0
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 1150/1281 [04:02<00:24,  5.27it/s]

A0A144NLT9
 Bacteria (superkingdom)
A0A5J6WQU1
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 1151/1281 [04:02<00:31,  4.12it/s]

D2R355
 Bacteria (superkingdom)
F3ZYD6
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 1153/1281 [04:03<00:30,  4.20it/s]

B0SL05
 Bacteria (superkingdom)
A0A5A7MAJ9
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 1155/1281 [04:03<00:28,  4.44it/s]

A0A977NL43
 Archaea (superkingdom)
A0A433ZQ80
 Bacteria (superkingdom)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 1157/1281 [04:03<00:26,  4.60it/s]

A0A1Y0V4A5
 Bacteria (superkingdom)
A0A1M7UEG2
 Bacteria (superkingdom)

 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 1159/1281 [04:04<00:26,  4.53it/s]

G8R7U9
 Bacteria (superkingdom)
K1LDP0
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 1161/1281 [04:04<00:26,  4.52it/s]

B7G0Y4
 Eukaryota (superkingdom)
A0A2W4ZXC0
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1163/1281 [04:05<00:26,  4.52it/s]

B3PF77
 Bacteria (superkingdom)
Q2KZK9
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 1166/1281 [04:05<00:22,  5.05it/s]

Q18ES8
 Archaea (superkingdom)
D3F545
 Bacteria (superkingdom)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 1167/1281 [04:06<00:26,  4.33it/s]

B4S394
 Bacteria (superkingdom)
Q1Q357
 Bacteria (superkingdom)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 1169/1281 [04:06<00:25,  4.40it/s]

Q9H310
 Eukaryota (superkingdom)
D3PKL4
 Bacteria (superkingdom)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 1171/1281 [04:06<00:24,  4.45it/s]

M5SY07
 Bacteria (superkingdom)
Q8RUT6
 Eukaryota (superkingdom)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 1174/1281 [04:07<00:21,  5.01it/s]

A7NKH2
 Bacteria (superkingdom)
Q1Q879
 Bacteria (superkingdom)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 1176/1281 [04:07<00:21,  4.91it/s]

A0A1B9M5B8
 Bacteria (superkingdom)
A6LRS5
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 1178/1281 [04:08<00:21,  4.79it/s]

J2ZGN6
 Archaea (superkingdom)
V5E0F3
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 1180/1281 [04:08<00:20,  4.91it/s]

A0A149RQX0
 Bacteria (superkingdom)
A0A165BP25
 Bacteria (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 1182/1281 [04:09<00:19,  5.00it/s]

C0QSY0
 Bacteria (superkingdom)
B0XVV6
 Eukaryota (superkingdom)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 1184/1281 [04:09<00:20,  4.80it/s]

E0SD83
 Bacteria (superkingdom)
A8HSA2
 Eukaryota (superkingdom)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 1185/1281 [04:09<00:19,  4.83it/s]

A0A1E3PSK5
 Eukaryota (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 1187/1281 [04:10<00:19,  4.94it/s]

A5DYQ2
 Eukaryota (superkingdom)
A0A4U1K1W1
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 1189/1281 [04:10<00:18,  5.02it/s]

Q0AT01
 Bacteria (superkingdom)
A4FMG0
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 1191/1281 [04:11<00:17,  5.16it/s]

C3YB73
 Eukaryota (superkingdom)
A0A9P3CXY2
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 1192/1281 [04:11<00:20,  4.44it/s]

A0A0L8BVU4
 Bacteria (superkingdom)
A0A401WUW1
 Bacteria (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 1195/1281 [04:11<00:16,  5.13it/s]

I4C9L2
 Bacteria (superkingdom)
Q8RUE9
 Eukaryota (superkingdom)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 1196/1281 [04:12<00:19,  4.32it/s]

F0JGZ1
 Bacteria (superkingdom)
A0A2I0UUY1
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 1198/1281 [04:12<00:18,  4.56it/s]

A0A542XGT4
 Bacteria (superkingdom)
G0JRH4
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 1200/1281 [04:13<00:17,  4.52it/s]

A2SPS8
 Archaea (superkingdom)
A0A5M4AWD2
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 1203/1281 [04:13<00:15,  5.08it/s]

Q6QH01
 Eukaryota (superkingdom)
D3F0Z1
 Bacteria (superkingdom)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 1205/1281 [04:14<00:15,  4.90it/s]

A6XBM2
 Eukaryota (superkingdom)
D6E7B3
 Bacteria (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 1206/1281 [04:14<00:17,  4.23it/s]

Q13E03
 Bacteria (superkingdom)
A0A060URB8
 Bacteria (superkingdom)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 1209/1281 [04:14<00:14,  4.98it/s]

A0A2T1N7R1
 Bacteria (superkingdom)
D6TCH6
 Bacteria (superkingdom)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1211/1281 [04:15<00:13,  5.05it/s]

B0CXH8
 Eukaryota (superkingdom)
A3TVQ9
 Bacteria (superkingdom)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 1212/1281 [04:15<00:16,  4.23it/s]

Q4WT12
 Eukaryota (superkingdom)
C7QGX3
 Bacteria (superkingdom)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 1214/1281 [04:16<00:15,  4.31it/s]

F0Y9X3
 Eukaryota (superkingdom)
A0A7S0D560
 Eukaryota (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1216/1281 [04:16<00:14,  4.56it/s]

A0A160KTE9
 Bacteria (superkingdom)
A0A2H1HV86
 Bacteria (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 1218/1281 [04:16<00:13,  4.72it/s]

A0A251Y3N4
 Bacteria (superkingdom)
A0A419AVL2
 Bacteria (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 1221/1281 [04:17<00:11,  5.32it/s]

A0A4Q2QWS1
 Bacteria (superkingdom)
C7Q1E4
 Bacteria (superkingdom)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 1222/1281 [04:17<00:12,  4.71it/s]

A0A5C5TYS5
 Bacteria (superkingdom)
F2NNQ0
 Bacteria (superkingdom)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 1224/1281 [04:18<00:11,  4.83it/s]

A0A2R4TRE0
 Bacteria (superkingdom)
K9YJQ3
 Bacteria (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 1227/1281 [04:18<00:10,  5.23it/s]

D9QS43
 Bacteria (superkingdom)
A7SQ16
 Eukaryota (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 1228/1281 [04:19<00:11,  4.45it/s]

A1DG05
 Eukaryota (superkingdom)
U1SIR9
 Bacteria (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 1230/1281 [04:19<00:11,  4.42it/s]

C4Y298
 Eukaryota (superkingdom)
A0A9W3LFI9
 Bacteria (superkingdom)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 1233/1281 [04:20<00:09,  5.02it/s]

D3RMV7
 Bacteria (superkingdom)
F3QNA7
 Bacteria (superkingdom)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 1234/1281 [04:20<00:10,  4.30it/s]

E4RTK5
 Bacteria (superkingdom)
C8XBX8
 Bacteria (superkingdom)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 1236/1281 [04:20<00:10,  4.37it/s]

C0QTA4
 Bacteria (superkingdom)
E6VIW4
 Bacteria (superkingdom)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 1238/1281 [04:21<00:09,  4.58it/s]

A0A2S6H643
 Bacteria (superkingdom)
Q46HB1
 Bacteria (superkingdom)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 1240/1281 [04:21<00:08,  4.71it/s]

A0A2S5CTX8
 Bacteria (superkingdom)
A0A1T4SF40
 Bacteria (superkingdom)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 1242/1281 [04:22<00:08,  4.62it/s]

K0K7J4
 Bacteria (superkingdom)
A0A1J5JH24
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 1244/1281 [04:22<00:07,  4.64it/s]

Q6LMI6
 Bacteria (superkingdom)
A0A9W5JBA9
 Bacteria (superkingdom)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 1246/1281 [04:22<00:07,  4.72it/s]

A0A291PMC6
 Bacteria (superkingdom)
A0A4Y4DZN4
 Bacteria (superkingdom)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 1249/1281 [04:23<00:06,  5.28it/s]

A0A2R4MBA2
 Bacteria (superkingdom)
R9PI53
 Bacteria (superkingdom)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 1251/1281 [04:23<00:05,  5.39it/s]

A0A6H9GLV4
 Bacteria (superkingdom)
A0A7S4GND2
 Eukaryota (superkingdom)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 1252/1281 [04:24<00:06,  4.66it/s]

A0A6H9FPY5
 Bacteria (superkingdom)
A0A1G7DX68
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 1254/1281 [04:24<00:05,  4.81it/s]

A0A075WEB4
 Archaea (superkingdom)
A0A140NHJ5
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 1256/1281 [04:24<00:05,  4.81it/s]

A0A1C6Z081
 Bacteria (superkingdom)
Q5FA36
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 1258/1281 [04:25<00:04,  4.70it/s]

Q0ACK1
 Bacteria (superkingdom)
A0A975GIX9
 Bacteria (superkingdom)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 1261/1281 [04:25<00:03,  5.31it/s]

A0A323UE08
 Bacteria (superkingdom)
U7VB41
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 1263/1281 [04:26<00:03,  5.12it/s]

A0A063Y780
 Bacteria (superkingdom)
C5CIT6
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 1265/1281 [04:26<00:03,  5.12it/s]

A0A0A2VPU3
 Eukaryota (superkingdom)
F0RHS0
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 1266/1281 [04:27<00:03,  4.84it/s]

A0A2S5WX34
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 1268/1281 [04:27<00:02,  5.04it/s]

C1G973
 Eukaryota (superkingdom)
A0A2S6GKF6
 Bacteria (superkingdom)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1270/1281 [04:27<00:02,  5.12it/s]

A0A0A2B651
 Bacteria (superkingdom)
A0A4R3A5P7
 Bacteria (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 1272/1281 [04:28<00:01,  5.03it/s]

A0A2A7U6W1
 Bacteria (superkingdom)
Q2GX26
 Eukaryota (superkingdom)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 1274/1281 [04:28<00:01,  5.19it/s]

F5XN43
 Bacteria (superkingdom)
A0A0K2STH0
 Eukaryota (superkingdom)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1276/1281 [04:29<00:01,  4.85it/s]

A0A1H1U2Q6
 Bacteria (superkingdom)
A7SED8
 Eukaryota (superkingdom)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 1278/1281 [04:29<00:00,  5.09it/s]

A0LV78
 Bacteria (superkingdom)
K5DBA0
 Bacteria (superkingdom)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1280/1281 [04:29<00:00,  5.19it/s]

B8IZX4
 Bacteria (superkingdom)
A8LKQ0
 Bacteria (superkingdom)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1281/1281 [04:30<00:00,  4.74it/s]

A0A5C6LWQ1
 Bacteria (superkingdom)

In [168]:
with open('kingdom.txt', 'w') as fp:
    for ite in linige:
        # write each item on a new line
        fp.write("%s\n" % ite)
    print('Done')

Done

In [73]:
# with open('kingdom.txt', 'r') as file:

#     linage = []
#     for line in file:
#         line = line.strip()
#         linage.append(line)

# print(linage)

['A1D2Y5: Eukaryota (superkingdom)', 'M8E0R3: Bacteria (superkingdom)', 'A0A2G3DSU6: Bacteria (superkingdom)', 'A0A328EMN2: Bacteria (superkingdom)', 'A0A6A1TYJ4: Bacteria (superkingdom)', 'D3RMV7: Bacteria (superkingdom)', 'F0J3F9: Bacteria (superkingdom)', 'G2ZN72: Bacteria (superkingdom)', 'I0KDC6: Bacteria (superkingdom)', 'A0A081N2G5: Bacteria (superkingdom)', 'A0A144NLT9: Bacteria (superkingdom)', 'B4D7W2: Bacteria (superkingdom)', 'F3QNA7: Bacteria (superkingdom)', 'Q4WHC6: Eukaryota (superkingdom)', 'Q8JI14: Eukaryota (superkingdom)', 'A0A395VB65: Bacteria (superkingdom)', 'A0A975GIX9: Bacteria (superkingdom)', 'Q5UZ98: Archaea (superkingdom)', 'A0A4R4K1P9: Bacteria (superkingdom)', 'A0A7T4WEP4: Bacteria (superkingdom)', 'C6LBD3: Bacteria (superkingdom)', 'D5V7B3: Bacteria (superkingdom)', 'A0A4R3ZNW3: Bacteria (superkingdom)', 'A9BQZ4: Bacteria (superkingdom)', 'A0A642KQG8: Bacteria (superkingdom)', 'A9BIZ7: Bacteria (superkingdom)', 'K0NJH2: Bacteria (superkingdom)', 'Q2IK04: Bacteria (superkingdom)', 'T2KJ59: Bacteria (superkingdom)', 'A0A1B9M5B8: Bacteria (superkingdom)', 'A0A323UE08: Bacteria (superkingdom)', 'E8RLT5: Bacteria (superkingdom)', 'F6G5I9: Bacteria (superkingdom)', 'G3A431: Bacteria (superkingdom)', 'G4H971: Bacteria (superkingdom)', 'L1J6I4: Eukaryota (superkingdom)', 'M0J579: Archaea (superkingdom)', 'A0A377PBY1: Bacteria (superkingdom)', 'A0A401WUW1: Bacteria (superkingdom)', 'L1IYW7: Eukaryota (superkingdom)', 'A0A315S845: Bacteria (superkingdom)', 'A0A6M3ZKU5: Bacteria (superkingdom)', 'A0A502GPV4: Bacteria (superkingdom)', 'A0A9J9BAE8: Bacteria (superkingdom)', 'A1AVV2: Bacteria (superkingdom)', 'B1XZU2: Bacteria (superkingdom)', 'Q5P1S8: Bacteria (superkingdom)', 'A0A0F5EZP7: Bacteria (superkingdom)', 'A0A4R7GKA0: Bacteria (superkingdom)', 'A0A2T4UWF1: Bacteria (superkingdom)', 'A0A3E0X011: Bacteria (superkingdom)', 'A0A4R8H081: Bacteria (superkingdom)', 'C7LQR9: Bacteria (superkingdom)', 'A0A0A2A0Y9: Bacteria (superkingdom)', 'A0A0A2A5X1: Bacteria (superkingdom)', 'A0A7T5BFQ2: Bacteria (superkingdom)', 'A3U857: Bacteria (superkingdom)', 'E1V4T3: Bacteria (superkingdom)', 'F0J7D3: Bacteria (superkingdom)', 'M7XJ51: Bacteria (superkingdom)', 'Q1K0H9: Bacteria (superkingdom)', 'A0A2S5XAB8: Bacteria (superkingdom)', 'A0A366IE34: Bacteria (superkingdom)', 'Q1Z695: Bacteria (superkingdom)', 'A0A8G2IZM3: Bacteria (superkingdom)', 'G3IYW2: Bacteria (superkingdom)', 'A0A2G5BGA9: Eukaryota (superkingdom)', 'A0A5M4AUM9: Bacteria (superkingdom)', 'E3HJW8: Bacteria (superkingdom)', 'U1PIR6: Archaea (superkingdom)', 'A0A1B9N3H7: Bacteria (superkingdom)', 'A0A2S5WV24: Bacteria (superkingdom)', 'A0A6U2BIY7: Eukaryota (superkingdom)', 'A0A833LX85: Bacteria (superkingdom)', 'I9P003: Bacteria (superkingdom)', 'K8VZC6: Bacteria (superkingdom)', 'L1IUV5: Eukaryota (superkingdom)', 'A0A0K2STQ7: Eukaryota (superkingdom)', 'A0A2H1HV86: Bacteria (superkingdom)', 'Q2GX26: Eukaryota (superkingdom)', 'A0A074KY88: Bacteria (superkingdom)', 'A0A858ZNJ3: Bacteria (superkingdom)', 'A0A3P2A7W8: Bacteria (superkingdom)', 'A0A7S4GND2: Eukaryota (superkingdom)', 'O26757: Archaea (superkingdom)', 'Q46G49: Archaea (superkingdom)', 'A0A140NHJ5: Bacteria (superkingdom)', 'A0A2S8GF54: Bacteria (superkingdom)', 'B1JZ69: Bacteria (superkingdom)', 'E5Y678: Bacteria (superkingdom)', 'A0A149U2G9: Bacteria (superkingdom)', 'A0A9Q5QVI9: Bacteria (superkingdom)', 'Q18PF5: Eukaryota (superkingdom)', 'A0A317FZW2: Bacteria (superkingdom)', 'G5EB13: Eukaryota (superkingdom)', 'Q1YDY8: Bacteria (superkingdom)', 'A0A1X4GBG2: Bacteria (superkingdom)', 'A0A4Q7Y9I7: Bacteria (superkingdom)', 'I0HKQ8: Bacteria (superkingdom)', 'A0A097R891: Bacteria (superkingdom)', 'A0A7S4GMD8: Eukaryota (superkingdom)', 'Q488X2: Bacteria (superkingdom)', 'U3PCH5: Bacteria (superkingdom)', 'A0A378YR15: Bacteria (superkingdom)', 'I1YG38: Bacteria (superkingdom)', 'F5XN43: Bacteria (superkingdom)', 'Q1IWN6: Bacteria (superkingdom)', 'A0A1E3PSK5: Eukaryota (superkingdom)', 'A0A833H2R7: Bacteria (superkingdom)', 'A0A2T0XPP2: Bacteria (superkingdom)', 'A0A399T909: Bacteria (superkingdom)', 'L8GGA0: Eukaryota (superkingdom)', 'A0A0D8BQX6: Bacteria (superkingdom)', 'A0A1M5ZVP9: Bacteria (superkingdom)', 'I5BYV5: Bacteria (superkingdom)', 'A0A0K2STH0: Eukaryota (superkingdom)', 'A0A2N6K4Y5: Bacteria (superkingdom)', 'A0A1B9JZS5: Bacteria (superkingdom)', 'A0A2W0GQV0: Bacteria (superkingdom)', 'A0A369MHK2: Bacteria (superkingdom)', 'A0A087L0B9: Bacteria (superkingdom)', 'A0A0A2AMW2: Bacteria (superkingdom)', 'A0A377PLP5: Bacteria (superkingdom)', 'Q6BJI7: Eukaryota (superkingdom)', 'Q7S5K0: Eukaryota (superkingdom)', 'Q7Z1M1: Eukaryota (superkingdom)', 'T2JFS5: Bacteria (superkingdom)', 'W0JIB3: Archaea (superkingdom)', 'A0A1V2XMU9: Bacteria (superkingdom)', 'A0A2S6GKN5: Bacteria (superkingdom)', 'A0A7G5DK18: Bacteria (superkingdom)', 'A0A830ZZN8: Bacteria (superkingdom)', 'A0A8B4RWH8: Bacteria (superkingdom)', 'A0A9Q6P4A5: Bacteria (superkingdom)', 'B8ENL9: Bacteria (superkingdom)', 'Q9QXP0: Eukaryota (superkingdom)', 'A0A060URC3: Bacteria (superkingdom)', 'A0A2W5HTC3: Bacteria (superkingdom)', 'A7S731: Eukaryota (superkingdom)', 'A0A1Y0UZX2: Bacteria (superkingdom)', 'A0A257TE48: Bacteria (superkingdom)', 'Q2RVB5: Bacteria (superkingdom)', 'Q605Y6: Bacteria (superkingdom)', 'A0A918MJ52: Bacteria (superkingdom)', 'K6W5X0: Bacteria (superkingdom)', 'V4AP67: Eukaryota (superkingdom)', 'A0A7Z0V0A4: Bacteria (superkingdom)', 'C0GKN4: Bacteria (superkingdom)', 'A9HMD6: Bacteria (superkingdom)', 'B1ZSW9: Bacteria (superkingdom)', 'K5DBA0: Bacteria (superkingdom)', 'V4REY8: Bacteria (superkingdom)', 'A0A0D2KGN8: Eukaryota (superkingdom)', 'A0A242NIL1: Bacteria (superkingdom)', 'A8PXT8: Eukaryota (superkingdom)', 'B7X047: Bacteria (superkingdom)', 'D2ZRW2: Archaea (superkingdom)', 'H1Y7T6: Bacteria (superkingdom)', 'Q97L80: Bacteria (superkingdom)', 'A0A0S6UHP2: Bacteria (superkingdom)', 'A0A323UDG5: Bacteria (superkingdom)', 'E3I393: Bacteria (superkingdom)', 'A0A4V2X6C2: Bacteria (superkingdom)', 'D7G265: Eukaryota (superkingdom)', 'A6LRS5: Bacteria (superkingdom)', 'D8J4C6: Archaea (superkingdom)', 'F2NGJ8: Bacteria (superkingdom)', 'A0A0E9NHV4: Eukaryota (superkingdom)', 'A1CQ21: Eukaryota (superkingdom)', 'A0A6N2Z556: Bacteria (superkingdom)', 'Q0BWD0: Bacteria (superkingdom)', 'A0A071MMV1: Bacteria (superkingdom)', 'A0A168EVK8: Bacteria (superkingdom)', 'B3DUX7: Bacteria (superkingdom)', 'F5L8M7: Bacteria (superkingdom)', 'G7WJN0: Bacteria (superkingdom)', 'Q0BQ69: Bacteria (superkingdom)', 'A0A3N2SFS2: Bacteria (superkingdom)', 'A0A9Y2AG30: Bacteria (superkingdom)', 'A0AA46Q839: Bacteria (superkingdom)', 'E8RSE4: Bacteria (superkingdom)', 'F6BEI0: Archaea (superkingdom)', 'I1DSU5: Bacteria (superkingdom)', 'I4C9L2: Bacteria (superkingdom)', 'Q5QVH2: Bacteria (superkingdom)', 'A0A068NPW2: Bacteria (superkingdom)', 'A0A6J5IRX5: Bacteria (superkingdom)', 'A0A3R9Q7C4: Bacteria (superkingdom)', 'A3ZT81: Bacteria (superkingdom)', 'K0ER80: Bacteria (superkingdom)', 'Q0VLH1: Bacteria (superkingdom)', 'Q2KZK9: Bacteria (superkingdom)', 'R9GM11: Bacteria (superkingdom)', 'A0A0T7GZ59: Bacteria (superkingdom)', 'A0A1G5PWV0: Bacteria (superkingdom)', 'S5ABR8: Bacteria (superkingdom)', 'W7QGM4: Bacteria (superkingdom)', 'F5Y3C1: Bacteria (superkingdom)', 'I8TC71: Bacteria (superkingdom)', 'M1P5F0: Bacteria (superkingdom)', 'A0A149RYW7: Bacteria (superkingdom)', 'A0A1J1JH03: Bacteria (superkingdom)', 'A0A1U9Z147: Bacteria (superkingdom)', 'A0A243SC06: Bacteria (superkingdom)', 'A0A3G9G2C9: Bacteria (superkingdom)', 'I4C9L0: Bacteria (superkingdom)', 'I4D1H5: Bacteria (superkingdom)', 'Q7W7D3: Bacteria (superkingdom)', 'A0A0B4M163: Eukaryota (superkingdom)', 'A0A1M7UEG2: Bacteria (superkingdom)', 'A7HT14: Bacteria (superkingdom)', 'C8X554: Bacteria (superkingdom)', 'A0A127PIQ9: Bacteria (superkingdom)', 'A0A1B9JPL5: Bacteria (superkingdom)', 'W5WIX6: Bacteria (superkingdom)', 'A0AA40J491: Bacteria (superkingdom)', 'D8PD01: Bacteria (superkingdom)', 'A0A251XU71: Bacteria (superkingdom)', 'A0A2N6P374: Eukaryota (superkingdom)', 'B3QVV5: Bacteria (superkingdom)', 'K1K628: Bacteria (superkingdom)', 'A0A1E2SKM1: Bacteria (superkingdom)', 'A0A1I0BYN1: Bacteria (superkingdom)', 'A0A556RTU3: Bacteria (superkingdom)', 'A0A829X098: Bacteria (superkingdom)', 'D5EP68: Bacteria (superkingdom)', 'F0J6E8: Bacteria (superkingdom)', 'A0A073CP02: Bacteria (superkingdom)', 'A0A127JTU2: Bacteria (superkingdom)', 'C7BJG7: Bacteria (superkingdom)', 'D2BUJ8: Bacteria (superkingdom)', 'B8IZX4: Bacteria (superkingdom)', 'I3R0S7: Archaea (superkingdom)', 'A0A3E2TW06: Bacteria (superkingdom)', 'B1Y0E5: Bacteria (superkingdom)', 'E6ME92: Bacteria (superkingdom)', 'A0A251Y3N4: Bacteria (superkingdom)', 'A0A380S5X4: Bacteria (superkingdom)', 'F0YLV7: Eukaryota (superkingdom)', 'F8D7H6: Archaea (superkingdom)', 'Q31CR9: Bacteria (superkingdom)', 'W0E077: Bacteria (superkingdom)', 'A5DYQ2: Eukaryota (superkingdom)', 'A8LKQ0: Bacteria (superkingdom)', 'A0A4Y1MSE7: Bacteria (superkingdom)', 'A3TVQ9: Bacteria (superkingdom)', 'F2B2B8: Bacteria (superkingdom)', 'L0K9M1: Bacteria (superkingdom)', 'Q4WT12: Eukaryota (superkingdom)', 'Q8ERT9: Bacteria (superkingdom)', 'A0A1H3WA00: Bacteria (superkingdom)', 'A0A1U9YY82: Bacteria (superkingdom)', 'A1DG05: Eukaryota (superkingdom)', 'B8GGC1: Archaea (superkingdom)', 'F3ZVV4: Bacteria (superkingdom)', 'P69680: Bacteria (superkingdom)', 'Q0G2T1: Bacteria (superkingdom)', 'A0A3T0SZ22: Bacteria (superkingdom)', 'A0A4R2Z2K6: Bacteria (superkingdom)', 'L1IYP4: Eukaryota (superkingdom)', 'Q46HB1: Bacteria (superkingdom)', 'A0A149QAW7: Bacteria (superkingdom)', 'A0A1Y4L5P0: Bacteria (superkingdom)', 'A0A6B8N021: Bacteria (superkingdom)', 'D5EP71: Bacteria (superkingdom)', 'V5U2Z4: Bacteria (superkingdom)', 'A0A0E3QYF3: Archaea (superkingdom)', 'A0A0K2STK6: Eukaryota (superkingdom)', 'A0A8H7U3I1: Eukaryota (superkingdom)', 'A0A062IU58: Bacteria (superkingdom)', 'A0A178TA08: Bacteria (superkingdom)', 'A0A3G9G4Q4: Bacteria (superkingdom)', 'A0A6H9FPY5: Bacteria (superkingdom)', 'A1C5Z7: Eukaryota (superkingdom)', 'A0A0A1ZJU5: Bacteria (superkingdom)', 'A0A258HPP1: Bacteria (superkingdom)', 'G0H0Z6: Archaea (superkingdom)', 'A0A2Z4MD56: Bacteria (superkingdom)', 'G0EFF3: Archaea (superkingdom)', 'E2SD33: Bacteria (superkingdom)', 'E4TJ50: Bacteria (superkingdom)', 'A0A016XCG9: Bacteria (superkingdom)', 'A0A2S5Y0D3: Bacteria (superkingdom)', 'K9YN27: Bacteria (superkingdom)', 'Q3AFY9: Bacteria (superkingdom)', 'Q7N0M6: Bacteria (superkingdom)', 'W8KM07: Bacteria (superkingdom)', 'A0A0G9HEC5: Bacteria (superkingdom)', 'A5UJR1: Archaea (superkingdom)', 'A0A9Q9D9I3: Bacteria (superkingdom)', 'B9SXC7: Eukaryota (superkingdom)', 'C0QTA4: Bacteria (superkingdom)', 'A0A176XNC5: Bacteria (superkingdom)', 'A0A317G0I6: Bacteria (superkingdom)', 'A0A2S5CTX8: Bacteria (superkingdom)', 'U2EN72: Bacteria (superkingdom)', 'A0A248LNW8: Bacteria (superkingdom)', 'A0A4P8HC89: Bacteria (superkingdom)', 'G7UUY6: Bacteria (superkingdom)', 'A0A0E3WZH5: Archaea (superkingdom)', 'A0A165K0X5: Bacteria (superkingdom)', 'D3FBG3: Bacteria (superkingdom)', 'Q608B6: Bacteria (superkingdom)', 'A0A854Q6X9: Eukaryota (superkingdom)', 'H2IZ00: Bacteria (superkingdom)', 'A0A4V0XUI3: Bacteria (superkingdom)', 'A0A7S4GNJ2: Eukaryota (superkingdom)', 'A0A2S5WX34: Bacteria (superkingdom)', 'C1D6X6: Bacteria (superkingdom)', 'A0A418VIJ8: Bacteria (superkingdom)', 'A0A857DMN9: Bacteria (superkingdom)', 'Q7T3R4: Eukaryota (superkingdom)', 'R1D1H4: Eukaryota (superkingdom)', 'T2J0N1: Bacteria (superkingdom)', 'A0A419AVL2: Bacteria (superkingdom)', 'K0K7J4: Bacteria (superkingdom)', 'A0A4U1K1W1: Bacteria (superkingdom)', 'A0A9R0NTP8: Bacteria (superkingdom)', 'B0RC35: Bacteria (superkingdom)', 'C8XB51: Bacteria (superkingdom)', 'E4NS62: Archaea (superkingdom)', 'R9PMC6: Bacteria (superkingdom)', 'A0A1R1IDV3: Bacteria (superkingdom)', 'A0A2N6JV02: Bacteria (superkingdom)', 'A7MFK3: Bacteria (superkingdom)', 'B0BZN3: Bacteria (superkingdom)', 'F7ZEU9: Bacteria (superkingdom)', 'K9P718: Bacteria (superkingdom)', 'Q82X47: Bacteria (superkingdom)', 'Q8RUE9: Eukaryota (superkingdom)', 'A0A0M2LU39: Bacteria (superkingdom)', 'A0A3N1VXY4: Bacteria (superkingdom)', 'A0A370FPU0: Bacteria (superkingdom)', 'A0A7G5DPV1: Bacteria (superkingdom)', 'A9UR54: Eukaryota (superkingdom)', 'F0S0G1: Bacteria (superkingdom)', 'K9W4V5: Bacteria (superkingdom)', 'A0A015YIP3: Bacteria (superkingdom)', 'A0A291PMC6: Bacteria (superkingdom)', 'G8R7U9: Bacteria (superkingdom)', 'U1H1F7: Bacteria (superkingdom)', 'A0A021VMC6: Bacteria (superkingdom)', 'A0A855F5Y8: Bacteria (superkingdom)', 'A0A2W5VAZ2: Bacteria (superkingdom)', 'M0MDP9: Archaea (superkingdom)', 'A0A1X3RP39: Bacteria (superkingdom)', 'A0A653N397: Bacteria (superkingdom)', 'A0A8G2F718: Bacteria (superkingdom)', 'F4B548: Archaea (superkingdom)', 'I0ICG0: Bacteria (superkingdom)', 'A0A009TDB1: Bacteria (superkingdom)', 'A0A1G7DX68: Bacteria (superkingdom)', 'E4YA63: Eukaryota (superkingdom)', 'Q2W5V2: Bacteria (superkingdom)', 'Q3AP28: Bacteria (superkingdom)', 'Q9BLG3: Eukaryota (superkingdom)', 'A0A0D5YN10: Bacteria (superkingdom)', 'A0A0L0S493: Eukaryota (superkingdom)', 'H1YCC3: Bacteria (superkingdom)', 'L8JUH3: Bacteria (superkingdom)', 'A0A0E3SHQ9: Archaea (superkingdom)', 'A0A366XFS8: Bacteria (superkingdom)', 'E6VIW4: Bacteria (superkingdom)', 'F6FRU9: Bacteria (superkingdom)', 'A1VIM5: Bacteria (superkingdom)', 'E0TGP9: Bacteria (superkingdom)', 'A0A0E3SP24: Archaea (superkingdom)', 'A0A8H6NAG3: Eukaryota (superkingdom)', 'B8FGW0: Bacteria (superkingdom)', 'C3X1J1: Bacteria (superkingdom)', 'D9SI36: Bacteria (superkingdom)', 'E0TCV4: Bacteria (superkingdom)', 'E4U5Z1: Bacteria (superkingdom)', 'A0A094W9G3: Bacteria (superkingdom)', 'A0A7G5EC77: Bacteria (superkingdom)', 'A0A482TED1: Archaea (superkingdom)', 'A0A4Q2QWS1: Bacteria (superkingdom)', 'A3PAY4: Bacteria (superkingdom)', 'A0A173R3W6: Bacteria (superkingdom)', 'A0A1B9BUU6: Bacteria (superkingdom)', 'A0A495D4X4: Bacteria (superkingdom)', 'A0A833GZR2: Bacteria (superkingdom)', 'D0L8H3: Bacteria (superkingdom)', 'F4XTK4: Bacteria (superkingdom)', 'I4D6Z7: Bacteria (superkingdom)', 'L8H844: Eukaryota (superkingdom)', 'A0A0S6UEK9: Bacteria (superkingdom)', 'A0A1M6ZMI3: Bacteria (superkingdom)', 'U1SIR9: Bacteria (superkingdom)', 'A0A066ZTE4: Bacteria (superkingdom)', 'A9DQM8: Bacteria (superkingdom)', 'A0A0A0D6K5: Bacteria (superkingdom)', 'D6E7B3: Bacteria (superkingdom)', 'A0A562USB9: Bacteria (superkingdom)', 'C7LW87: Bacteria (superkingdom)', 'G0JRG6: Bacteria (superkingdom)', 'A0A1X6N3Q5: Eukaryota (superkingdom)', 'A0A1Y4LM49: Bacteria (superkingdom)', 'B7FSA7: Eukaryota (superkingdom)', 'E1QIU3: Bacteria (superkingdom)', 'H2CDR5: Bacteria (superkingdom)', 'Q1K433: Bacteria (superkingdom)', 'Q1QS12: Bacteria (superkingdom)', 'Q7T070: Eukaryota (superkingdom)', 'A0A0H3DR67: Bacteria (superkingdom)', 'A5CRL2: Bacteria (superkingdom)', 'A0A836M2B6: Bacteria (superkingdom)', 'E6SF19: Bacteria (superkingdom)', 'I2GD40: Bacteria (superkingdom)', 'Q18ES8: Archaea (superkingdom)', 'A0A060UWC8: Bacteria (superkingdom)', 'A0A0U1NJW3: Bacteria (superkingdom)', 'A0A7R6PER3: Bacteria (superkingdom)', 'A4G1J2: Bacteria (superkingdom)', 'A9AUR8: Bacteria (superkingdom)', 'C1N5A7: Eukaryota (superkingdom)', 'D3S2L0: Archaea (superkingdom)', 'F8IJE0: Bacteria (superkingdom)', 'A0A0D2LEF5: Eukaryota (superkingdom)', 'A0A1H1MB73: Bacteria (superkingdom)', 'W7QGE0: Bacteria (superkingdom)', 'G2T1Y3: Bacteria (superkingdom)', 'L7CG99: Bacteria (superkingdom)', 'A0A1I0C958: Bacteria (superkingdom)', 'A0KPE9: Bacteria (superkingdom)', 'A9V5W4: Eukaryota (superkingdom)', 'F5RGM7: Bacteria (superkingdom)', 'A0A1C6Z081: Bacteria (superkingdom)', 'A0A1D3GAE9: Bacteria (superkingdom)', 'A0A410JZR4: Bacteria (superkingdom)', 'A8N2H6: Eukaryota (superkingdom)', 'I1YJH7: Bacteria (superkingdom)', 'A0A2G5BI87: Eukaryota (superkingdom)', 'A0A2N6NEK4: Eukaryota (superkingdom)', 'A0A1Y0HX98: Bacteria (superkingdom)', 'C3YB74: Eukaryota (superkingdom)', 'Q1H0G2: Bacteria (superkingdom)', 'Q2FQT3: Archaea (superkingdom)', 'S0APH6: Archaea (superkingdom)', 'A0A075WEB4: Archaea (superkingdom)', 'A0A172RYW3: Bacteria (superkingdom)', 'I3C0V3: Bacteria (superkingdom)', 'A0A556SRH6: Bacteria (superkingdom)', 'A0A7U4DN04: Bacteria (superkingdom)', 'A0A1V3SSW1: Bacteria (superkingdom)', 'Q466Y3: Archaea (superkingdom)', 'A0A0A2ZRL7: Bacteria (superkingdom)', 'A0A0H3LUA3: Bacteria (superkingdom)', 'A4G0C5: Archaea (superkingdom)', 'A5E3X2: Eukaryota (superkingdom)', 'A8P923: Eukaryota (superkingdom)', 'B8EMQ8: Bacteria (superkingdom)', 'D0MFE9: Bacteria (superkingdom)', 'A0A060HFT5: Archaea (superkingdom)', 'A0A060JMP6: Bacteria (superkingdom)', 'A0A8E2UDJ3: Bacteria (superkingdom)', 'I4D6Z9: Bacteria (superkingdom)', 'Q13E03: Bacteria (superkingdom)', 'Q1JXS5: Bacteria (superkingdom)', 'A0A076PL76: Bacteria (superkingdom)', 'A0A6N2TIA4: Bacteria (superkingdom)', 'Q1AUG3: Bacteria (superkingdom)', 'A0A098S5Y7: Bacteria (superkingdom)', 'A0A7S4GNF3: Eukaryota (superkingdom)', 'A0A5J6WQU1: Bacteria (superkingdom)', 'A2SS52: Archaea (superkingdom)', 'M9RKT6: Bacteria (superkingdom)', 'A0A2K1RA77: Eukaryota (superkingdom)', 'A0A2K1RA81: Eukaryota (superkingdom)', 'A0A2S0JW39: Bacteria (superkingdom)', 'A0A2T9X1V4: Archaea (superkingdom)', 'D3F545: Bacteria (superkingdom)', 'A0A1E3PQH0: Eukaryota (superkingdom)', 'A0A1J5JH24: Bacteria (superkingdom)', 'C4Y298: Eukaryota (superkingdom)', 'Q3B6Q2: Bacteria (superkingdom)', 'Q7TNN9: Eukaryota (superkingdom)', 'A0A4Y7XC43: Bacteria (superkingdom)', 'A0A5B2V3B9: Bacteria (superkingdom)', 'B9L7N1: Bacteria (superkingdom)', 'C7M2A9: Bacteria (superkingdom)', 'D2V6Q5: Eukaryota (superkingdom)', 'E4T3F7: Bacteria (superkingdom)', 'F2YIC4: Eukaryota (superkingdom)', 'Q0G0A3: Bacteria (superkingdom)', 'A0A424WAH3: Bacteria (superkingdom)', 'B8ZYW3: Archaea (superkingdom)', 'U7VB41: Bacteria (superkingdom)', 'A0A7S0KKL8: Eukaryota (superkingdom)', 'A0A1C7EL50: Bacteria (superkingdom)', 'A0A6G9Y3Q0: Bacteria (superkingdom)', 'A0A6S5K4J1: Bacteria (superkingdom)', 'G0LFE3: Archaea (superkingdom)', 'J9VXX9: Eukaryota (superkingdom)', 'V4RHR4: Bacteria (superkingdom)', 'A0A0D7F2Y9: Bacteria (superkingdom)', 'A0A1S8D478: Bacteria (superkingdom)', 'Q47K18: Bacteria (superkingdom)', 'B9SWW9: Eukaryota (superkingdom)', 'L8H5K0: Eukaryota (superkingdom)', 'A0A369N7Y3: Bacteria (superkingdom)', 'A0A399NT81: Bacteria (superkingdom)', 'B0SLB7: Bacteria (superkingdom)', 'B4CV94: Bacteria (superkingdom)', 'E1IF27: Bacteria (superkingdom)', 'G2PRJ6: Bacteria (superkingdom)', 'A0A202B535: Bacteria (superkingdom)', 'A0A2M9D7S8: Bacteria (superkingdom)', 'Q6LMI6: Bacteria (superkingdom)', 'K2JVF8: Bacteria (superkingdom)', 'Q1Q357: Bacteria (superkingdom)', 'B8FDY8: Bacteria (superkingdom)', 'B8FL88: Bacteria (superkingdom)', 'E3H8A6: Bacteria (superkingdom)', 'H8L2Q4: Bacteria (superkingdom)', 'A0A248LMH8: Bacteria (superkingdom)', 'A0A5C5BWI6: Bacteria (superkingdom)', 'L1INN6: Eukaryota (superkingdom)', 'M7NFH3: Bacteria (superkingdom)', 'A0A060URB8: Bacteria (superkingdom)', 'K9W6F3: Bacteria (superkingdom)', 'A0A7S0D560: Eukaryota (superkingdom)', 'D2Q0J8: Bacteria (superkingdom)', 'A0A251YU48: Bacteria (superkingdom)', 'A0A6H9GEE4: Bacteria (superkingdom)', 'A0A8F5ZDT8: Archaea (superkingdom)', 'C1G973: Eukaryota (superkingdom)', 'M0D580: Archaea (superkingdom)', 'A0A1Y5E3E3: Bacteria (superkingdom)', 'A0A328Q6M1: Archaea (superkingdom)', 'Q7UGU7: Bacteria (superkingdom)', 'A0A660CH85: Bacteria (superkingdom)', 'E4T3F3: Bacteria (superkingdom)', 'A0A6H9GFU4: Bacteria (superkingdom)', 'A3XNG6: Bacteria (superkingdom)', 'B9LU00: Archaea (superkingdom)', 'E4RTK5: Bacteria (superkingdom)', 'H6LKH9: Bacteria (superkingdom)', 'Q0AT01: Bacteria (superkingdom)', 'A0A330GB00: Bacteria (superkingdom)', 'A0A657K391: Bacteria (superkingdom)', 'Q2N625: Bacteria 

In [106]:
king = []
eyed = []

for y in linige:
    eyed.append(y.split(':')[0])
    king.append(y.split(' ')[1])

In [107]:
df2['eyed'] = eyed

In [108]:
df2['kingdom'] = king

In [109]:
df2 = df2.drop('eyed', axis=1)

In [138]:
df2

,0,four,first,PheGate,TwinHis,SN,kingdom,Phyla,Class,EDG
0,A0A858ZNJ3,YNSVAV,Y,FF,HH,S,Bacteria,Pseudomonadota,Betaproteobacteria,E
1,A0A1H9M798,YNNTAV,Y,FF,HH,S,Bacteria,Pseudomonadota,Betaproteobacteria,E
2,B0DY50,YNSMMV,Y,FF,HH,S,Eukaryota,Basidiomycota,Agaricomycetes,E
3,P69680,YNSMGV,Y,FF,HH,S,Bacteria,Pseudomonadota,Gammaproteobacteria,E
4,A0A3G9G4Q4,YNATAT,Y,FF,HH,S,Bacteria,Pseudomonadota,Alphaproteobacteria,E
...,...,...,...,...,...,...,...,...,...,...
1276,A0LV78,YNAMAT,Y,FF,HH,S,Bacteria,Actinomycetota,Actinomycetes,D
1277,K5DBA0,ENDLTS,E,FF,HH,N,Bacteria,Planctomycetota,Planctomycetia,G
1278,B8IZX4,YRSTAS,Y,FF,HH,S,Bacteria,Thermodesulfobacteriota,Desulfovibrionia,E
1279,A8LKQ0,ENLYSS,E,FF,HH,N,Bacteria,Pseudomonadota,Alphaproteobacteria,E
1280,A0A5C6LWQ1,YNSTAV,Y,FF,HH,I,Bacteria,Bacteroidota,Chitinophagia,E

In [113]:
linige = []
for item in tqdm(idid):
    lineage = u.search(item, columns='lineage')
    print(item)
    print(lineage)
    finige = f"{item}:{lineage}" 
    linige.append(finige)

  0%|                                                                                                                                           | 1/1281 [00:00<02:42,  7.87it/s]

A0A858ZNJ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Alicycliphilus (genus)

  0%|▎                                                                                                                                          | 3/1281 [00:00<03:28,  6.14it/s]

A0A1H9M798
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Giesbergeria (genus)

B0DY50
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

  0%|▌                                                                                                                                          | 5/1281 [00:00<03:34,  5.94it/s]

P69680
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Escherichia (genus), Escherichia coli (species)

A0A3G9G4Q4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Asticcacaulis (genus)

  1%|▊                                                                                                                                          | 7/1281 [00:01<03:37,  5.87it/s]

A0A149UP06
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

F2G6G4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Alteromonas/Salinimonas group (no rank), Alteromonas (genus), Alteromonas mediterranea (species)

  1%|▉                                                                                                                                          | 9/1281 [00:01<03:36,  5.89it/s]

A0A2M9D7S8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Salinibacterium (genus)

A0A034WGQ2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Brachycera (suborder), Muscomorpha (infraorder), Eremoneura (clade), Cyclorrhapha (clade), Schizophora (no rank), Acalyptratae (no rank), Tephritoidea (superfamily), Tephritidae (family), Dacinae (subfamily), Dacini (tribe), Bactrocera (genus), Bactrocera (subgenus), Bactrocera dorsalis complex (no rank)

  1%|█                                                                                                                                         | 10/1281 [00:01<04:15,  4.98it/s]

I0KDC6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Spirosomataceae (family), Fibrella (genus), Fibrella aestuarina (species)

F8D7H6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Natrialbaceae (family), Halopiger (genus), Halopiger xanaduensis (species)

  1%|█▎                                                                                                                                        | 12/1281 [00:02<04:07,  5.13it/s]

K9W4V5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Gomontiellales (order), Gomontiellaceae (family), Crinalium (genus), Crinalium epipsammum (species)

Q466Y3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

  1%|█▌                                                                                                                                        | 14/1281 [00:02<04:04,  5.18it/s]

D2SE15
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Geodermatophilales (order), Geodermatophilaceae (family), Geodermatophilus (genus), Geodermatophilus obscurus (species)

A0A377PBY1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus)

  1%|█▋                                                                                                                                        | 16/1281 [00:02<04:00,  5.26it/s]

B1JZ69
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank), Burkholderia orbicola (species)

A0A2W5HTC3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bdellovibrionota (phylum), Bdellovibrionia (class), Bdellovibrionales (order), Pseudobdellovibrionaceae (family), Micavibrio (genus)

  1%|█▉                                                                                                                                        | 18/1281 [00:03<03:58,  5.30it/s]

A8G2S3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

D5T4N9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Lactobacillaceae (family), Leuconostoc (genus), Leuconostoc kimchii (species)

  2%|██▏                                                                                                                                       | 20/1281 [00:03<03:56,  5.32it/s]

Q2RWY7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Rhodospirillaceae (family), Rhodospirillum (genus), Rhodospirillum rubrum (species)

A0A0E3R4G0
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

  2%|██▎                                                                                                                                       | 22/1281 [00:04<03:56,  5.33it/s]

I4C9L0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfomonilia (class), Desulfomonilales (order), Desulfomonilaceae (family), Desulfomonile (genus), Desulfomonile tiedjei (species)

D5VJ32
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Caulobacter (genus), Caulobacter segnis (species)

  2%|██▌                                                                                                                                       | 24/1281 [00:04<03:55,  5.33it/s]

C0Z5S5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Paenibacillaceae (family), Brevibacillus (genus), Brevibacillus brevis (species)

C1N6X9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus), Micromonas pusilla (species)

  2%|██▊                                                                                                                                       | 26/1281 [00:04<03:54,  5.34it/s]

J7ITF6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus meridiei (species)

A0A068SVR1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus), Neorhizobium galegae (species), Neorhizobium galegae bv. orientalis (no rank)

  2%|███                                                                                                                                       | 28/1281 [00:05<03:54,  5.33it/s]

A0A0D7F328
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus)

Q0G0A4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Fulvimarina (genus), Fulvimarina pelagi (species)

  2%|███▏                                                                                                                                      | 30/1281 [00:05<03:54,  5.34it/s]

F0J3F9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acidiphilium (genus), Acidiphilium multivorum (species)

Q0BQ69
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Granulibacter (genus), Granulibacter bethesdensis (species)

  2%|███▍                                                                                                                                      | 32/1281 [00:05<03:53,  5.34it/s]

F2YIC4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Crustacea (subphylum), Multicrustacea (superclass), Malacostraca (class), Eumalacostraca (subclass), Eucarida (superorder), Decapoda (order), Pleocyemata (suborder), Brachyura (infraorder), Eubrachyura (no rank), Heterotremata (no rank), Cancroidea (superfamily), Cancridae (family), Metacarcinus (genus)

D4XLN6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter haemolyticus (species)

  3%|███▋                                                                                                                                      | 34/1281 [00:06<03:53,  5.34it/s]

A0A420WC79
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Oceanibaculaceae (family), Oceanibaculum (genus)

A0A5C5TUT2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus)

  3%|███▉                                                                                                                                      | 36/1281 [00:06<03:53,  5.32it/s]

A0RUZ2
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Nitrososphaerota (phylum), Candidatus Cenarchaeales (order), Candidatus Cenarchaeaceae (family), Candidatus Cenarchaeum (genus), Cenarchaeum symbiosum (species)

A0A0A2ZRL7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Gallibacterium (genus), Gallibacterium anatis (species)

  3%|████                                                                                                                                      | 38/1281 [00:07<03:54,  5.31it/s]

J4UGB7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus), Beauveria bassiana (species)

E5Y678
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Bilophila (genus), Bilophila wadsworthia (species)

  3%|████▎                                                                                                                                     | 40/1281 [00:07<03:53,  5.31it/s]

A0A0D2KGN8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Strophariaceae (family), Hypholoma (genus), Hypholoma sublateritium (species)

S5ABR8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Alteromonas/Salinimonas group (no rank), Alteromonas (genus), Alteromonas mediterranea (species)

  3%|████▌                                                                                                                                     | 42/1281 [00:07<03:52,  5.33it/s]

A9DQM8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Kordia (genus), Kordia algicida (species)

G5EB13
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Nidulantes (subgenus), Emericella nidulans (species)

  3%|████▋                                                                                                                                     | 44/1281 [00:08<03:52,  5.32it/s]

A0A2N6NEK4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus)

C6DB68
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Pectobacterium (genus), Pectobacterium carotovorum (species), Pectobacterium carotovorum subsp. carotovorum (subspecies)

  4%|████▉                                                                                                                                     | 46/1281 [00:08<03:51,  5.33it/s]

Q81GN5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Bacillus (genus), Bacillus cereus group (no rank), Bacillus cereus (species)

Q0F2M5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Zetaproteobacteria (class), Mariprofundales (order), Mariprofundaceae (family), Mariprofundus (genus), Mariprofundus ferrooxydans (species)

  4%|█████▏                                                                                                                                    | 48/1281 [00:08<03:51,  5.34it/s]

A0A0C6P439
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Bordetella (genus), Bordetella bronchiseptica (species)

B9SWW9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Malpighiales (order), Euphorbiaceae (family), Acalyphoideae (subfamily), Acalypheae (tribe), Ricinus (genus)

  4%|█████▍                                                                                                                                    | 50/1281 [00:09<03:51,  5.33it/s]

L8H5K0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Discosea (phylum), Longamoebia (order), Centramoebida (clade), Acanthamoebidae (family), Acanthamoeba (genus), Acanthamoeba castellanii (species)

Q9NIV0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Evosea (phylum), Eumycetozoa (class), Dictyostelia (clade), Dictyosteliales (order), Dictyosteliaceae (family), Dictyostelium (genus)

  4%|█████▌                                                                                                                                    | 52/1281 [00:09<03:48,  5.38it/s]

C1N5A7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus), Micromonas pusilla (species)

Q1JXS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Desulfuromonadaceae (family), Desulfuromonas (genus), Desulfuromonas acetoxidans (species)

  4%|█████▊                                                                                                                                    | 54/1281 [00:10<03:48,  5.37it/s]

A0A1M6JKY3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus), Desulfatibacillum alkenivorans (species)

F4D1J0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Pseudonocardia (genus), Pseudonocardia dioxanivorans (species)

  4%|██████                                                                                                                                    | 56/1281 [00:10<03:48,  5.36it/s]

A0A257SYX3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

V4RK08
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Tepidamorphaceae (family), Lutibaculum (genus), Lutibaculum baratangense (species)

  5%|██████▏                                                                                                                                   | 58/1281 [00:10<03:48,  5.35it/s]

G0V8D6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Naumovozyma (genus)

A0A7S4GMD8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Oxyrrhinales (order), Oxyrrhinaceae (family), Oxyrrhis (genus)

  5%|██████▍                                                                                                                                   | 60/1281 [00:11<03:47,  5.36it/s]

B3QVV5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chloroherpetonaceae (family), Chloroherpeton (genus), Chloroherpeton thalassium (species)

F2JZ83
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Marinomonas (genus), Marinomonas mediterranea (species)

  5%|██████▋                                                                                                                                   | 62/1281 [00:11<03:47,  5.35it/s]

A0A857DDJ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Dehalobacter (genus)

A0A0S6UHP2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus), Moorella thermoacetica (species)

  5%|██████▉                                                                                                                                   | 64/1281 [00:11<03:47,  5.35it/s]

D5EP71
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Opitutia (class), Puniceicoccales (order), Coraliomargaritaceae (family), Coraliomargarita (genus), Coraliomargarita akajimensis (species)

F4KY49
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Saprospiria (class), Saprospirales (order), Haliscomenobacteraceae (family), Haliscomenobacter (genus), Haliscomenobacter hydrossis (species)

  5%|███████                                                                                                                                   | 66/1281 [00:12<03:46,  5.35it/s]

M5S9B4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula europaea (species)

A0A009PYN3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

  5%|███████▎                                                                                                                                  | 68/1281 [00:12<03:46,  5.34it/s]

A0A3T0SZ22
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Rathayibacter (genus), Rathayibacter festucae (species)

A0A248LMH8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Laribacter (genus)

  5%|███████▌                                                                                                                                  | 70/1281 [00:13<03:45,  5.36it/s]

A0A6H9GEE4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

A7HSP2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Parvibaculaceae (family), Parvibaculum (genus), Parvibaculum lavamentivorans (species)

  6%|███████▊                                                                                                                                  | 72/1281 [00:13<03:44,  5.39it/s]

A0A7V8IKS6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Pectobacterium (genus)

T2JFS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Aphanothecaceae (family), Crocosphaera (genus), Crocosphaera watsonii (species)

  6%|███████▉                                                                                                                                  | 74/1281 [00:13<03:44,  5.37it/s]

F6FRU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Promicromonosporaceae (family), Isoptericola (genus), Isoptericola variabilis (species)

A0A9E9L9J1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Oxalobacter (genus)

  6%|████████▏                                                                                                                                 | 76/1281 [00:14<03:45,  5.35it/s]

A0AIW5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Listeriaceae (family), Listeria (genus), Listeria welshimeri (species)

A0A0E9NHV4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), Taphrinomycotina (subphylum), Taphrinomycotina incertae sedis (no rank), Saitoella (genus), Saitoella complicata (species)

  6%|████████▍                                                                                                                                 | 78/1281 [00:14<03:44,  5.37it/s]

Q2N625
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Sphingomonadales (order), Erythrobacteraceae (family), Erythrobacter/Porphyrobacter group (no rank), Erythrobacter (genus), Erythrobacter litoralis (species)

C8WSI9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Alicyclobacillaceae (family), Alicyclobacillus (genus), Alicyclobacillus acidocaldarius (species), Alicyclobacillus acidocaldarius subsp. acidocaldarius (subspecies)

  6%|████████▌                                                                                                                                 | 80/1281 [00:14<03:42,  5.40it/s]

A0A1H1BPD6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Leucobacter (genus)

A0A176XNC5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Achromobacter (genus)

  6%|████████▊                                                                                                                                 | 82/1281 [00:15<03:42,  5.40it/s]

A0A4V0XUI3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Oscillatoriales (order), Microcoleaceae (family), Planktothrix (genus), Planktothrix agardhii (species)

A7S3L2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

  7%|█████████                                                                                                                                 | 84/1281 [00:15<03:42,  5.37it/s]

M5U2P1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula sallentina (species)

K9P5D1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Cyanobium (genus), Cyanobium gracile (species)

  7%|█████████▎                                                                                                                                | 86/1281 [00:16<03:43,  5.35it/s]

Q0F2M7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Zetaproteobacteria (class), Mariprofundales (order), Mariprofundaceae (family), Mariprofundus (genus), Mariprofundus ferrooxydans (species)

A0A2R3IMJ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus), Pseudomonas aeruginosa group (no rank)

  7%|█████████▍                                                                                                                                | 88/1281 [00:16<03:43,  5.34it/s]

Q2RVB5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Rhodospirillaceae (family), Rhodospirillum (genus), Rhodospirillum rubrum (species)

A0A556RTU3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

  7%|█████████▋                                                                                                                                | 90/1281 [00:16<03:41,  5.37it/s]

E0TGP9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Parvularculales (order), Parvularculaceae (family), Parvularcula (genus), Parvularcula bermudensis (species)

B7G0Y1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Bacillariophyta (phylum), Bacillariophyceae (class), Bacillariophycidae (clade), Naviculales (order), Phaeodactylaceae (family), Phaeodactylum (genus), Phaeodactylum tricornutum (species)

  7%|█████████▉                                                                                                                                | 92/1281 [00:17<03:41,  5.38it/s]

A0A1G9P6Q0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Geoalkalibacteraceae (family), Geoalkalibacter (genus)

D0LTW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Polyangia (subclass), Haliangiales (order), Kofleriaceae (family), Haliangium (genus), Haliangium ochraceum (species)

  7%|██████████▏                                                                                                                               | 94/1281 [00:17<03:41,  5.37it/s]

Q6BT62
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Debaryomyces (genus), Debaryomyces hansenii (species)

Q2IK04
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Myxococcia (class), Myxococcales (order), Cystobacterineae (suborder), Anaeromyxobacteraceae (family), Anaeromyxobacter (genus), Anaeromyxobacter dehalogenans (species)

  7%|██████████▎                                                                                                                               | 96/1281 [00:17<03:40,  5.37it/s]

Q6BJI7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Debaryomyces (genus), Debaryomyces hansenii (species)

B7X047
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus), Comamonas testosteroni (species)

  8%|██████████▌                                                                                                                               | 98/1281 [00:18<03:41,  5.35it/s]

A0A068NPW2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Armatimonadota (phylum), Fimbriimonadia (class), Fimbriimonadales (order), Fimbriimonadaceae (family), Fimbriimonas (genus), Fimbriimonas ginsengisoli (species)

A0A399NT81
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

  8%|██████████▋                                                                                                                              | 100/1281 [00:18<03:41,  5.34it/s]

K0F9X7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Nocardiaceae (family), Nocardia (genus), Nocardia brasiliensis (species)

A0A037ZMW1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Actibacterium (genus), Actibacterium mucosum (species)

  8%|██████████▉                                                                                                                              | 102/1281 [00:19<03:40,  5.35it/s]

A0A075JZ35
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Rhodanobacteraceae (family), Dyella (genus), Dyella japonica (species)

A0A369MHK2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Eggerthella (genus)

  8%|███████████                                                                                                                              | 104/1281 [00:19<03:40,  5.34it/s]

A0A1B9JPL5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

D8PD01
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Nitrospirota (phylum), Nitrospiria (class), Nitrospirales (order), Nitrospiraceae (family), Nitrospira (genus)

  8%|███████████▎                                                                                                                             | 106/1281 [00:19<03:38,  5.37it/s]

A0A2G5BI87
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Zoopagomycota (phylum), Kickxellomycotina (subphylum), Kickxellomycetes (class), Kickxellales (order), Kickxellaceae (family), Coemansia (genus), Coemansia reversa (species)

A0A2G5BGA9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Zoopagomycota (phylum), Kickxellomycotina (subphylum), Kickxellomycetes (class), Kickxellales (order), Kickxellaceae (family), Coemansia (genus), Coemansia reversa (species)

  8%|███████████▌                                                                                                                             | 108/1281 [00:20<03:38,  5.37it/s]

A0A657K391
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

P69681
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Escherichia (genus), Escherichia coli (species)

  9%|███████████▊                                                                                                                             | 110/1281 [00:20<03:38,  5.35it/s]

A0A4P6UIJ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Hylemonella (genus)

A0A0V8M0W6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Dehalococcoidia (class), Dehalococcoidales (order), Dehalococcoidaceae (family), Dehalococcoides (genus)

  9%|███████████▉                                                                                                                             | 112/1281 [00:20<03:38,  5.34it/s]

A0A0H2XSU4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank), Burkholderia orbicola (species)

Q1Z695
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Photobacterium (genus), Photobacterium profundum (species)

  9%|████████████▏                                                                                                                            | 114/1281 [00:21<03:38,  5.33it/s]

A0A7Z0V0A4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Moraxella (genus)

K0ER80
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Nocardiaceae (family), Nocardia (genus), Nocardia brasiliensis (species)

  9%|████████████▍                                                                                                                            | 116/1281 [00:21<03:38,  5.34it/s]

A0A149UWF2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

G0H0Z6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanococci (class), Methanococcales (order), Methanococcaceae (family), Methanococcus (genus), Methanococcus maripaludis (species)

  9%|████████████▌                                                                                                                            | 118/1281 [00:22<03:37,  5.36it/s]

G0EFF3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Desulfurococcales (order), Pyrodictiaceae (family), Pyrolobus (genus), Pyrolobus fumarii (species)

C8WLL8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Eggerthella (genus), Eggerthella lenta (species)

  9%|████████████▊                                                                                                                            | 120/1281 [00:22<03:37,  5.34it/s]

X5CNT2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Rosales (order), Rosaceae (family), Amygdaloideae (subfamily), Maleae (tribe), Pyrus (genus)

A0A4Y1MSE7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Roseomonas (genus)

 10%|█████████████                                                                                                                            | 122/1281 [00:22<03:35,  5.37it/s]

H2CLF7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus), Leptonema illini (species)

M4VEJ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bdellovibrionota (phylum), Bdellovibrionia (class), Bdellovibrionales (order), Pseudobdellovibrionaceae (family), Micavibrio (genus), Micavibrio aeruginosavorus (species)

 10%|█████████████▎                                                                                                                           | 124/1281 [00:23<03:35,  5.37it/s]

A0A4V2X6C2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus), Photorhabdus luminescens (species)

A0A2K1RA77
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Malpighiales (order), Salicaceae (family), Saliceae (tribe), Populus (genus)

 10%|█████████████▍                                                                                                                           | 126/1281 [00:23<03:34,  5.38it/s]

A0A375YPN6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Mycobacteriaceae (family), Mycolicibacterium (genus)

A0A7M6UUM4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Hymenoptera (order), Apocrita (suborder), Aculeata (infraorder), Apoidea (superfamily), Anthophila (clade), Apidae (family), Apinae (subfamily), Apini (tribe), Apis (genus)

 10%|█████████████▋                                                                                                                           | 128/1281 [00:23<03:34,  5.39it/s]

A0A172YCA7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Halomonadaceae (family), Halotalea (genus)

A0A918MJ52
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Arenibacter (genus)

 10%|█████████████▉                                                                                                                           | 130/1281 [00:24<03:35,  5.34it/s]

A0A2S8QA29
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus)

A0A251XJT0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus), Clavibacter michiganensis (species)

 10%|██████████████                                                                                                                           | 132/1281 [00:24<03:36,  5.32it/s]

A0A0B4E6X7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Leisingera (genus), unclassified Leisingera (no rank)

A0A0K2STQ7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Gonyaulacales (order), Pyrocystaceae (family), Alexandrium (genus)

 10%|██████████████▎                                                                                                                          | 134/1281 [00:25<03:34,  5.35it/s]

A1C5Z7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus clavatus (species)

C9KKP2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Negativicutes (class), Selenomonadales (order), Selenomonadaceae (family), Mitsuokella (genus), Mitsuokella multacida (species)

 11%|██████████████▌                                                                                                                          | 136/1281 [00:25<03:33,  5.36it/s]

A0A2Z4MD56
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Paenibacillaceae (family), Brevibacillus (genus)

Q9VFA9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Brachycera (suborder), Muscomorpha (infraorder), Eremoneura (clade), Cyclorrhapha (clade), Schizophora (no rank), Acalyptratae (no rank), Ephydroidea (superfamily), Drosophilidae (family), Drosophilinae (subfamily), Drosophilini (tribe), Drosophila (genus), Sophophora (subgenus), melanogaster group (no rank), melanogaster subgroup (no rank)

 11%|██████████████▊                                                                                                                          | 138/1281 [00:25<03:33,  5.36it/s]

A0A502GPV4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Ewingella (genus)

I5C044
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Phyllobacteriaceae (family), Nitratireductor (genus), Nitratireductor aquibiodomus (species)

 11%|██████████████▉                                                                                                                          | 140/1281 [00:26<03:32,  5.37it/s]

D2V6P8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Discoba (clade), Heterolobosea (phylum), Tetramitia (clade), Eutetramitia (clade), Vahlkampfiidae (family), Naegleria (genus)

D3RN22
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Allochromatium (genus), Allochromatium vinosum (species)

 11%|███████████████▏                                                                                                                         | 142/1281 [00:26<03:32,  5.37it/s]

Q97L80
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Clostridiaceae (family), Clostridium (genus), Clostridium acetobutylicum (species)

A0A0D5YN10
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank)

 11%|███████████████▍                                                                                                                         | 144/1281 [00:26<03:31,  5.39it/s]

A0A1I5GN22
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Geodermatophilales (order), Geodermatophilaceae (family), Geodermatophilus (genus)

A0A1Y5E8I7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Colwelliaceae (family), Colwellia (genus)

 11%|███████████████▌                                                                                                                         | 146/1281 [00:27<03:30,  5.38it/s]

B1Y8C9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Leptothrix (genus), Leptothrix cholodnii (species)

M5SYZ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), unclassified Rhodopirellula (no rank)

 12%|███████████████▊                                                                                                                         | 148/1281 [00:27<03:31,  5.36it/s]

Q6HM26
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Bacillus (genus), Bacillus cereus group (no rank), Bacillus thuringiensis (species), Bacillus thuringiensis subsp. konkukian (no rank)

A0A379A0S9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Stappiaceae (family), Pannonibacter (genus)

 12%|████████████████                                                                                                                         | 150/1281 [00:28<03:30,  5.36it/s]

A0A101DCS3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Archaeoglobi (class), Archaeoglobales (order), Archaeoglobaceae (family), Archaeoglobus (genus)

A0A1Y3U5V2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Coriobacteriales (order), Coriobacteriaceae (family), Enorma (genus)

 12%|████████████████▎                                                                                                                        | 152/1281 [00:28<03:30,  5.38it/s]

A0A202B535
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Chromobacteriaceae (family), Chromobacterium (genus)

F8E6R1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Flexistipitaceae (family), Flexistipes (genus), Flexistipes sinusarabici (species)

 12%|████████████████▍                                                                                                                        | 154/1281 [00:28<03:30,  5.37it/s]

Q6ND36
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

A0A8H6K7L7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Glomerellales (order), Glomerellaceae (family), Colletotrichum (genus), Colletotrichum orchidearum species complex (no rank)

 12%|████████████████▋                                                                                                                        | 156/1281 [00:29<03:28,  5.38it/s]

Q7NCB8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Gloeobacterales (order), Gloeobacteraceae (family), Gloeobacter (genus), Gloeobacter violaceus (species)

A0A369MRW6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Eggerthella (genus)

 12%|████████████████▉                                                                                                                        | 158/1281 [00:29<03:29,  5.37it/s]

C9RS76
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Fibrobacterota (phylum), Fibrobacteria (class), Fibrobacterales (order), Fibrobacteraceae (family), Fibrobacter (genus), Fibrobacter succinogenes (species), Fibrobacter succinogenes subsp. succinogenes (subspecies)

A3U857
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Croceibacter (genus), Croceibacter atlanticus (species)

 12%|█████████████████                                                                                                                        | 160/1281 [00:29<03:28,  5.38it/s]

A0A127PIQ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Collimonas (genus)

B8FGW0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus)

 13%|█████████████████▎                                                                                                                       | 162/1281 [00:30<03:28,  5.36it/s]

A0A060JMP6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Luna cluster (no rank), Luna-1 subcluster (clade), Rhodoluna (genus)

D5V7B3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Campylobacterota (phylum), Epsilonproteobacteria (class), Campylobacterales (order), Arcobacteraceae (family), Arcobacter (genus), Arcobacter nitrofigilis (species)

 13%|█████████████████▌                                                                                                                       | 164/1281 [00:30<03:29,  5.34it/s]

A0A494JB70
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Weeksellaceae (family), Elizabethkingia (genus)

A0A5M8QF12
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Agrococcus (genus)

 13%|█████████████████▊                                                                                                                       | 166/1281 [00:30<03:27,  5.37it/s]

A0A8G2F3G4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfomicrobiaceae (family), Desulfomicrobium (genus)

J7L3W8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Streptosporangiales (order), Nocardiopsidaceae (family), Nocardiopsis (genus), Nocardiopsis alba (species)

 13%|█████████████████▉                                                                                                                       | 168/1281 [00:31<03:27,  5.36it/s]

G0JRG9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus), Acidithiobacillus ferrivorans (species)

D3DJN2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Aquificota (phylum), Aquificia (class), Aquificales (order), Aquificaceae (family), Hydrogenobacter (genus), Hydrogenobacter thermophilus (species)

 13%|██████████████████▏                                                                                                                      | 170/1281 [00:31<03:27,  5.35it/s]

A0A1Y2JH43
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Bradyrhizobium (genus)

Q1L727
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Nematocera (suborder), Culicomorpha (infraorder), Culicoidea (superfamily), Culicidae (family), Culicinae (subfamily), Aedini (tribe), Aedes (genus), Stegomyia (subgenus)

 13%|██████████████████▍                                                                                                                      | 172/1281 [00:32<03:27,  5.35it/s]

A0A7T2S0Z6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Delftia (genus)

A0A315S845
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Bifidobacteriales (order), Bifidobacteriaceae (family), Bifidobacterium (genus), Bifidobacterium animalis (species)

 14%|██████████████████▌                                                                                                                      | 174/1281 [00:32<03:27,  5.34it/s]

A0A2S6H6B7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus)

A0A1J5NTP7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus)

 14%|██████████████████▊                                                                                                                      | 176/1281 [00:32<03:26,  5.34it/s]

A0A0E3QY86
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

A0A096EEV9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

 14%|███████████████████                                                                                                                      | 178/1281 [00:33<03:26,  5.33it/s]

A0A380S5X4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Fibrobacterota (phylum), Fibrobacteria (class), Fibrobacterales (order), Fibrobacteraceae (family), Fibrobacter (genus)

B8ZYW3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloferax (genus), Haloferax mediterranei (species)

 14%|███████████████████▎                                                                                                                     | 180/1281 [00:33<03:25,  5.37it/s]

A0A2S8GEJ5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

A0A248TDF2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Cytobacillus (genus)

 14%|███████████████████▍                                                                                                                     | 182/1281 [00:33<03:24,  5.36it/s]

B2GFN1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Micrococcaceae (family), Kocuria (genus), Kocuria rhizophila (species)

U1PPI7
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloquadratum (genus), Haloquadratum walsbyi (species)

 14%|███████████████████▋                                                                                                                     | 184/1281 [00:34<03:24,  5.36it/s]

C7LW88
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfomicrobiaceae (family), Desulfomicrobium (genus), Desulfomicrobium baculatum (species)

G3A431
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank), Ralstonia syzygii (species)

 15%|███████████████████▉                                                                                                                     | 186/1281 [00:34<03:23,  5.38it/s]

A0A066ZTE4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Thiotrichales (order), Piscirickettsiaceae (family), Hydrogenovibrio (genus)

L7CG99
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

 15%|████████████████████                                                                                                                     | 188/1281 [00:35<03:22,  5.40it/s]

S0ET45
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Armatimonadota (phylum), Chthonomonadia (class), Chthonomonadales (order), Chthonomonadaceae (family), Chthonomonas (genus), Chthonomonas calidirosea (species)

A0A178TA08
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Anoxybacillus (genus)

 15%|████████████████████▎                                                                                                                    | 190/1281 [00:35<03:22,  5.37it/s]

H1XV27
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Calditrichota (phylum), Calditrichia (class), Calditrichales (order), Calditrichaceae (family), Caldithrix (genus), Caldithrix abyssi (species)

A0A6M3ZJI1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Herbaspirillum (genus), Herbaspirillum rubrisubalbicans (species)

 15%|████████████████████▌                                                                                                                    | 192/1281 [00:35<03:23,  5.36it/s]

U5DEY6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Aphanothecaceae (family), Rubidibacter (genus), Rubidibacter lacunae (species)

H6LFQ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Acetobacterium (genus), Acetobacterium woodii (species)

 15%|████████████████████▋                                                                                                                    | 194/1281 [00:36<03:22,  5.37it/s]

Q6CRN0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Kluyveromyces (genus), Kluyveromyces lactis (species)

A0A4Q2EAG7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

 15%|████████████████████▉                                                                                                                    | 196/1281 [00:36<03:22,  5.35it/s]

A0A1J5NNB8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus)

E3I393
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Hyphomicrobiaceae (family), Rhodomicrobium (genus), Rhodomicrobium vannielii (species)

 15%|█████████████████████▏                                                                                                                   | 198/1281 [00:36<03:21,  5.39it/s]

A0A243SC06
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Flavobacterium (genus), unclassified Flavobacterium (no rank)

D4F313
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Edwardsiella (genus), Edwardsiella tarda (species)

 16%|█████████████████████▍                                                                                                                   | 200/1281 [00:37<03:20,  5.38it/s]

W0F0I7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Chitinophagia (class), Chitinophagales (order), Chitinophagaceae (family), Niabella (genus), Niabella soli (species)

A9B874
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Chloroflexia (class), Herpetosiphonales (order), Herpetosiphonaceae (family), Herpetosiphon (genus), Herpetosiphon aurantiacus (species)

 16%|█████████████████████▌                                                                                                                   | 202/1281 [00:37<03:20,  5.39it/s]

A1D2Y5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus fischeri (species)

T2J0N1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Aphanothecaceae (family), Crocosphaera (genus), Crocosphaera watsonii (species)

 16%|█████████████████████▊                                                                                                                   | 204/1281 [00:38<03:20,  5.38it/s]

Q2FQT3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanospirillaceae (family), Methanospirillum (genus), Methanospirillum hungatei (species)

A0A075WG29
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Archaeoglobi (class), Archaeoglobales (order), Archaeoglobaceae (family), Archaeoglobus (genus), Archaeoglobus fulgidus (species)

 16%|██████████████████████                                                                                                                   | 206/1281 [00:38<03:20,  5.37it/s]

A0A979GQ79
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Chitinophagia (class), Chitinophagales (order), Chitinophagaceae (family), Chitinophaga (genus), Chitinophaga pinensis (species)

A0A381CAY8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Buttiauxella (genus)

 16%|██████████████████████▏                                                                                                                  | 208/1281 [00:38<03:19,  5.37it/s]

A0A2G3DSU6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Pseudobutyrivibrio (genus)

A0A168EVK8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Klebsiella (genus)

 16%|██████████████████████▍                                                                                                                  | 210/1281 [00:39<03:20,  5.35it/s]

A0A094W9G3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Nitrospirota (phylum), Nitrospiria (class), Nitrospirales (order), Nitrospiraceae (family), Leptospirillum (genus), Leptospirillum sp. Group III (no rank)

A0A4R3NVT3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Martelella (genus)

 17%|██████████████████████▋                                                                                                                  | 212/1281 [00:39<03:19,  5.35it/s]

W0DYY3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Marichromatium (genus), Marichromatium purpuratum (species)

G8JTW0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Eremothecium (genus), Eremothecium cymbalariae (species)

 17%|██████████████████████▉                                                                                                                  | 214/1281 [00:39<03:18,  5.38it/s]

A0A4P6UIK6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Hylemonella (genus)

I9P003
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Alishewanella (genus), Alishewanella agri (species)

 17%|███████████████████████                                                                                                                  | 216/1281 [00:40<03:18,  5.36it/s]

G2T1Y3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Roseburia (genus), Roseburia hominis (species)

B8EMQ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Beijerinckiaceae (family), Methylocella (genus), Methylocella silvestris (species)

 17%|███████████████████████▎                                                                                                                 | 218/1281 [00:40<03:18,  5.35it/s]

I6Z905
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Ignavibacteriota (phylum), Ignavibacteria (class), Ignavibacteriales (order), Melioribacteraceae (family), Melioribacter (genus), Melioribacter roseus (species)

E0TCV4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Parvularculales (order), Parvularculaceae (family), Parvularcula (genus), Parvularcula bermudensis (species)

 17%|███████████████████████▌                                                                                                                 | 220/1281 [00:41<03:18,  5.36it/s]

A3XNG6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Leeuwenhoekiella (genus), Leeuwenhoekiella blandensis (species)

A0A087MGU4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Arenimonas (genus), Arenimonas donghaensis (species)

 17%|███████████████████████▋                                                                                                                 | 222/1281 [00:41<03:17,  5.36it/s]

A2BUP4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A0A562S8V2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobotulus (genus)

 17%|███████████████████████▉                                                                                                                 | 224/1281 [00:41<03:17,  5.34it/s]

A0A495DND0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Maricaulales (order), Maricaulaceae (family), Maricaulis (genus)

A0A0S2FHD7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Lysobacter (genus)

 18%|████████████████████████▏                                                                                                                | 226/1281 [00:42<03:16,  5.37it/s]

F3QPR6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Prevotellaceae (family), Paraprevotella (genus), Paraprevotella xylaniphila (species)

A0A063Y394
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Nitrincola (genus)

 18%|████████████████████████▍                                                                                                                | 228/1281 [00:42<03:15,  5.38it/s]

F6G5I9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank), Ralstonia solanacearum (species)

A0A323UDG5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus)

 18%|████████████████████████▌                                                                                                                | 230/1281 [00:42<03:15,  5.37it/s]

A0A0G9HEC5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Rhodanobacteraceae (family), Dyella (genus), Dyella japonica (species)

B8FDY8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus)

 18%|████████████████████████▊                                                                                                                | 232/1281 [00:43<03:16,  5.35it/s]

Q5KPM5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Tremellomycetes (class), Tremellales (order), Cryptococcaceae (family), Cryptococcus (genus), Cryptococcus neoformans species complex (no rank), Cryptococcus neoformans (species), Cryptococcus neoformans var. neoformans (varietas)

A0A147EQL9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Leucobacter (genus)

 18%|█████████████████████████                                                                                                                | 234/1281 [00:43<03:14,  5.37it/s]

A0A854Q6X9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Tremellomycetes (class), Tremellales (order), Cryptococcaceae (family), Cryptococcus (genus), Cryptococcus neoformans species complex (no rank), Cryptococcus neoformans (species), Cryptococcus neoformans var. grubii (varietas)

C3X1J1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Oxalobacter (genus)

 18%|█████████████████████████▏                                                                                                               | 236/1281 [00:44<03:14,  5.37it/s]

A0A5B2V3B9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Salinarimonadaceae (family), Salinarimonas (genus)

A0A258FS85
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus)

 19%|█████████████████████████▍                                                                                                               | 238/1281 [00:44<03:13,  5.38it/s]

A0A7T2W1B3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Delftia (genus)

A0A060UN76
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

 19%|█████████████████████████▋                                                                                                               | 240/1281 [00:44<03:13,  5.38it/s]

G0JRQ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus), Acidithiobacillus ferrivorans (species)

D5UD26
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Cellulomonadaceae (family), Cellulomonas (genus), Cellulomonas flavigena (species)

 19%|█████████████████████████▉                                                                                                               | 242/1281 [00:45<03:16,  5.30it/s]

G2ZN72
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank), Ralstonia syzygii (species), Ralstonia syzygii subsp. celebesensis (subspecies)

A0AA46Q839
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Myxococcia (class), Myxococcales (order), Cystobacterineae (suborder), Myxococcaceae (family), Myxococcus (genus)

 19%|██████████████████████████                                                                                                               | 244/1281 [00:45<03:14,  5.32it/s]

A5UJR1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobrevibacter (genus), Methanobrevibacter smithii (species)

L1INN6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

 19%|██████████████████████████▎                                                                                                              | 246/1281 [00:45<03:13,  5.35it/s]

C1F584
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Acidobacteriota (phylum), Terriglobia (class), Terriglobales (order), Acidobacteriaceae (family), Acidobacterium (genus), Acidobacterium capsulatum (species)

C5LAG4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Perkinsozoa (phylum), Perkinsea (clade), Perkinsida (order), Perkinsidae (family), Perkinsus (genus), Perkinsus marinus (species)

 19%|██████████████████████████▌                                                                                                              | 248/1281 [00:46<03:13,  5.35it/s]

A0A2A2MCP3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus)

B1Y6V4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Leptothrix (genus), Leptothrix cholodnii (species)

 20%|██████████████████████████▋                                                                                                              | 250/1281 [00:46<03:12,  5.35it/s]

A0A1G6ABK5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Kaistiaceae (family), Bauldia (genus)

A0A6A1TYJ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus)

 20%|██████████████████████████▉                                                                                                              | 252/1281 [00:47<03:12,  5.35it/s]

A0A2T4UWF1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Rathayibacter (genus), Rathayibacter caricis (species)

V4AP67
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Spiralia (clade), Lophotrochozoa (clade), Mollusca (phylum), Gastropoda (class), Patellogastropoda (subclass), Lottioidea (superfamily), Lottiidae (family), Lottia (genus)

 20%|███████████████████████████▏                                                                                                             | 254/1281 [00:47<03:12,  5.34it/s]

A0A173R3W6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Anaerostipes (genus)

C7NND3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloarculaceae (family), Halorhabdus (genus), Halorhabdus utahensis (species)

 20%|███████████████████████████▍                                                                                                             | 256/1281 [00:47<03:11,  5.35it/s]

B0DFJ4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

A0A3E2VY88
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Oscillospiraceae (family), Faecalibacterium (genus)

 20%|███████████████████████████▌                                                                                                             | 258/1281 [00:48<03:11,  5.35it/s]

R1EDV9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Haptista (clade), Haptophyta (phylum), Prymnesiophyceae (clade), Isochrysidales (order), Noelaerhabdaceae (family), Emiliania (genus)

J1L5M8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanomicrobiaceae (family), Methanofollis (genus), Methanofollis liminatans (species)

 20%|███████████████████████████▊                                                                                                             | 260/1281 [00:48<03:11,  5.34it/s]

D7G265
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), PX clade (clade), Phaeophyceae (class), Ectocarpales (order), Ectocarpaceae (family), Ectocarpus (genus)

Q8ERT9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Oceanobacillus (genus), Oceanobacillus iheyensis (species)

 20%|████████████████████████████                                                                                                             | 262/1281 [00:48<03:10,  5.34it/s]

I4D6Z9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus acidiphilus (species)

A0A4R6DFU8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Curtobacterium (genus)

 21%|████████████████████████████▏                                                                                                            | 264/1281 [00:49<03:10,  5.34it/s]

A0A060URC3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

D2BIB2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Dehalococcoidia (class), Dehalococcoidales (order), Dehalococcoidaceae (family), Dehalococcoides (genus), Dehalococcoides mccartyi (species)

 21%|████████████████████████████▍                                                                                                            | 266/1281 [00:49<03:10,  5.33it/s]

F5ISF6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Dysgonomonadaceae (family), Dysgonomonas (genus), Dysgonomonas gadei (species)

A5CRL2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus), Clavibacter michiganensis (species), Clavibacter michiganensis subsp. michiganensis (subspecies)

 21%|████████████████████████████▋                                                                                                            | 268/1281 [00:50<03:09,  5.35it/s]

A0A6G9XJV9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Nocardiaceae (family), Nocardia (genus)

Q59UP8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Candida/Lodderomyces clade (clade), Candida (genus), Candida albicans (species)

 21%|████████████████████████████▉                                                                                                            | 270/1281 [00:50<03:09,  5.35it/s]

A0A6N4SPH9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cytophagaceae (family), Cytophaga (genus), Cytophaga hutchinsonii (species)

I0HGY4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micromonosporales (order), Micromonosporaceae (family), Actinoplanes (genus), Actinoplanes missouriensis (species)

 21%|█████████████████████████████                                                                                                            | 272/1281 [00:50<03:09,  5.34it/s]

X5DX97
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Draconibacterium (genus)

L1J6I4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

 21%|█████████████████████████████▎                                                                                                           | 274/1281 [00:51<03:08,  5.33it/s]

I1DSU5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Rheinheimera (genus), Rheinheimera nanhaiensis (species)

B9L7N1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Campylobacterota (phylum), Epsilonproteobacteria (class), Nautiliales (order), Nautiliaceae (family), Nautilia (genus), Nautilia profundicola (species)

 22%|█████████████████████████████▌                                                                                                           | 276/1281 [00:51<03:08,  5.34it/s]

Q1Z4I4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Photobacterium (genus), Photobacterium profundum (species)

Q21CP1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

 22%|█████████████████████████████▋                                                                                                           | 278/1281 [00:51<03:08,  5.33it/s]

A0A165MFD1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Chlorobium/Pelodictyon group (no rank), Pelodictyon (genus)

V4CRP5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Spiralia (clade), Lophotrochozoa (clade), Mollusca (phylum), Gastropoda (class), Patellogastropoda (subclass), Lottioidea (superfamily), Lottiidae (family), Lottia (genus)

 22%|█████████████████████████████▉                                                                                                           | 280/1281 [00:52<03:07,  5.33it/s]

Q7S5K0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Sordariomycetidae (subclass), Sordariales (order), Sordariaceae (family), Neurospora (genus), Neurospora crassa (species)

A0A071MMV1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank)

 22%|██████████████████████████████▏                                                                                                          | 282/1281 [00:52<03:07,  5.33it/s]

A0A149RYW7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconobacter (genus)

A0A7G5EC77
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

 22%|██████████████████████████████▎                                                                                                          | 284/1281 [00:53<03:06,  5.35it/s]

A0A1W2GZ82
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Aquiflexum (genus), Aquiflexum balticum (species)

A0A7U3XVQ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 22%|██████████████████████████████▌                                                                                                          | 286/1281 [00:53<03:05,  5.37it/s]

A0A071M4L5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank)

U5C2K4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cytophagaceae (family), Rhodonellum (genus), Rhodonellum psychrophilum (species)

 22%|██████████████████████████████▊                                                                                                          | 288/1281 [00:53<03:04,  5.38it/s]

A0A248LNW8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Laribacter (genus)

L8H844
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Discosea (phylum), Longamoebia (order), Centramoebida (clade), Acanthamoebidae (family), Acanthamoeba (genus), Acanthamoeba castellanii (species)

 23%|███████████████████████████████                                                                                                          | 290/1281 [00:54<03:04,  5.37it/s]

A0A149V596
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

S9QZ09
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Rubellimicrobium (genus), Rubellimicrobium thermophilum (species)

 23%|███████████████████████████████▏                                                                                                         | 292/1281 [00:54<03:04,  5.36it/s]

B1ZSW9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Opitutia (class), Opitutales (order), Opitutaceae (family), Opitutus (genus), Opitutus terrae (species)

D2BUJ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Dickeya (genus), Dickeya parazeae (species)

 23%|███████████████████████████████▍                                                                                                         | 294/1281 [00:54<03:04,  5.36it/s]

A0A9Q8L398
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank)

M5S735
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula europaea (species)

 23%|███████████████████████████████▋                                                                                                         | 296/1281 [00:55<03:03,  5.37it/s]

Q6ARH0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfocapsaceae (family), Desulfotalea (genus), Desulfotalea psychrophila (species)

K6W5X0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Dermatophilaceae (family), Kineosphaera (genus), Kineosphaera limosa (species)

 23%|███████████████████████████████▊                                                                                                         | 298/1281 [00:55<03:03,  5.36it/s]

G0JRG6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus), Acidithiobacillus ferrivorans (species)

A0A6H9FYW4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

 23%|████████████████████████████████                                                                                                         | 300/1281 [00:56<03:03,  5.35it/s]

A0A0S4WFM4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank)

A0A101HKN9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Dysgonomonadaceae (family), Proteiniphilum (genus)

 24%|████████████████████████████████▎                                                                                                        | 302/1281 [00:56<03:02,  5.37it/s]

Q9REX3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus)

F0S3Z6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Aquificota (phylum), Aquificia (class), Desulfurobacteriales (order), Desulfurobacteriaceae (family), Desulfurobacterium (genus), Desulfurobacterium thermolithotrophum (species)

 24%|████████████████████████████████▌                                                                                                        | 304/1281 [00:56<03:01,  5.39it/s]

A8NAG3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Psathyrellaceae (family), Coprinopsis (genus), Coprinopsis cinerea (species)

C6LBD3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Marvinbryantia (genus), Marvinbryantia formatexigens (species)

 24%|████████████████████████████████▋                                                                                                        | 306/1281 [00:57<03:01,  5.39it/s]

A0A149U2G9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

V4REY8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Tepidamorphaceae (family), Lutibaculum (genus), Lutibaculum baratangense (species)

 24%|████████████████████████████████▉                                                                                                        | 308/1281 [00:57<03:01,  5.37it/s]

A0A0H3H4I7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Klebsiella (genus), Klebsiella michiganensis (species)

A8N2H6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Psathyrellaceae (family), Coprinopsis (genus), Coprinopsis cinerea (species)

 24%|█████████████████████████████████▏                                                                                                       | 310/1281 [00:57<03:00,  5.38it/s]

S0APH6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Thermoplasmatota (phylum), Thermoplasmata (class), Thermoplasmatales (order), Ferroplasmaceae (family), Ferroplasma (genus), Ferroplasma acidarmanus (species)

A0A017SYR8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Polyangia (subclass), Polyangiales (order), Polyangiaceae (family), Chondromyces (genus), Chondromyces apiculatus (species)

 24%|█████████████████████████████████▎                                                                                                       | 312/1281 [00:58<03:00,  5.35it/s]

A0A1B9MZ78
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

E4T3F3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Paludibacteraceae (family), Paludibacter (genus), Paludibacter propionicigenes (species)

 25%|█████████████████████████████████▌                                                                                                       | 314/1281 [00:58<03:00,  5.36it/s]

D7E934
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanohalobium (genus), Methanohalobium evestigatum (species)

A0A0M3AB44
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), unclassified Acinetobacter (no rank)

 25%|█████████████████████████████████▊                                                                                                       | 316/1281 [00:58<02:59,  5.37it/s]

A9WHW6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Chloroflexia (class), Chloroflexales (order), Chloroflexineae (suborder), Chloroflexaceae (family), Chloroflexus (genus), Chloroflexus aurantiacus (species)

A0A5M4AUM9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Prolixibacter (genus)

 25%|██████████████████████████████████                                                                                                       | 318/1281 [00:59<02:59,  5.36it/s]

A0A1X4GBG2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Cylindrospermopsis (genus), Cylindrospermopsis raciborskii (species)

I4D1H5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus acidiphilus (species)

 25%|██████████████████████████████████▏                                                                                                      | 320/1281 [00:59<02:59,  5.37it/s]

A0A0E3QYF3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

B0CQX4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

 25%|██████████████████████████████████▍                                                                                                      | 322/1281 [01:00<02:58,  5.38it/s]

A0A378YR15
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Pandoraea (genus)

A0A495D4X4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Maricaulales (order), Maricaulaceae (family), Maricaulis (genus)

 25%|██████████████████████████████████▋                                                                                                      | 324/1281 [01:00<02:58,  5.37it/s]

A0A076PL76
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus), Comamonas testosteroni (species)

Q1YDY7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Aurantimonas (genus), Aurantimonas manganoxydans (species)

 25%|██████████████████████████████████▊                                                                                                      | 326/1281 [01:00<02:58,  5.35it/s]

A0A3E2UCG9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Oscillospiraceae (family), Faecalibacterium (genus)

A0A2K3DPU7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

 26%|███████████████████████████████████                                                                                                      | 328/1281 [01:01<02:57,  5.35it/s]

A0A3R9Q7C4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Acidobacteriota (phylum), Terriglobia (class), Terriglobales (order), Acidobacteriaceae (family), Edaphobacter (genus)

V5U2Z4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Cronobacter (genus)

 26%|███████████████████████████████████▎                                                                                                     | 330/1281 [01:01<02:58,  5.34it/s]

K9P718
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Cyanobium (genus), Cyanobium gracile (species)

M1V7W3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Rhodophyta (phylum), Bangiophyceae (class), Cyanidiales (order), Cyanidiaceae (family), Cyanidioschyzon (genus), Cyanidioschyzon merolae (species)

 26%|███████████████████████████████████▌                                                                                                     | 332/1281 [01:01<02:56,  5.37it/s]

Q6LKC8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Photobacterium (genus), Photobacterium profundum (species)

E5Y789
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Bilophila (genus), Bilophila wadsworthia (species)

 26%|███████████████████████████████████▋                                                                                                     | 334/1281 [01:02<02:56,  5.38it/s]

J9Z839
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Nitrospirota (phylum), Nitrospiria (class), Nitrospirales (order), Nitrospiraceae (family), Leptospirillum (genus), Leptospirillum sp. Group III (no rank), Leptospirillum ferriphilum (species)

A0A1G7VM92
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Rhodocyclaceae (family), Propionivibrio (genus)

 26%|███████████████████████████████████▉                                                                                                     | 336/1281 [01:02<02:56,  5.37it/s]

K9Z0D3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Synechococcaceae (family), Dactylococcopsis (genus), Dactylococcopsis salina (species)

A0A482TED1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Halogeometricum (genus)

 26%|████████████████████████████████████▏                                                                                                    | 338/1281 [01:03<02:55,  5.39it/s]

R1EGK6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Haptista (clade), Haptophyta (phylum), Prymnesiophyceae (clade), Isochrysidales (order), Noelaerhabdaceae (family), Emiliania (genus)

J1ASR8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanomicrobiaceae (family), Methanofollis (genus), Methanofollis liminatans (species)

 27%|████████████████████████████████████▎                                                                                                    | 340/1281 [01:03<02:55,  5.38it/s]

A0A7U4E420
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Spirosomataceae (family), Runella (genus), Runella slithyformis (species)

K9YR86
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Synechococcaceae (family), Dactylococcopsis (genus), Dactylococcopsis salina (species)

 27%|████████████████████████████████████▌                                                                                                    | 342/1281 [01:03<02:54,  5.39it/s]

A8PXT8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Ustilaginomycotina (subphylum), Malasseziomycetes (class), Malasseziales (order), Malasseziaceae (family), Malassezia (genus), Malassezia globosa (species)

A0A0U1NJW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Nereida (genus)

 27%|████████████████████████████████████▊                                                                                                    | 344/1281 [01:04<02:53,  5.39it/s]

B8FL88
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus)

A2CCK1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 27%|█████████████████████████████████████                                                                                                    | 346/1281 [01:04<02:54,  5.37it/s]

D6TFE1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Ktedonobacteria (class), Ktedonobacterales (order), Ktedonobacteraceae (family), Ktedonobacter (genus), Ktedonobacter racemifer (species)

A0A2H4U5R1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobrevibacter (genus)

 27%|█████████████████████████████████████▏                                                                                                   | 348/1281 [01:04<02:53,  5.37it/s]

I2GD40
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Spirosomataceae (family), Fibrisoma (genus), Fibrisoma limi (species)

A0A060HFT5
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Nitrososphaerota (phylum), Nitrososphaeria (class), Nitrososphaerales (order), Nitrososphaeraceae (family), Nitrososphaera (genus), Nitrososphaera viennensis (species)

 27%|█████████████████████████████████████▍                                                                                                   | 350/1281 [01:05<02:54,  5.35it/s]

B1Y842
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Leptothrix (genus), Leptothrix cholodnii (species)

A0A0X8NXA9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Achromobacter (genus)

 27%|█████████████████████████████████████▋                                                                                                   | 352/1281 [01:05<02:53,  5.35it/s]

A0A0A2A5X1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A0A318FY98
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Klebsiella (genus)

 28%|█████████████████████████████████████▊                                                                                                   | 354/1281 [01:06<02:53,  5.34it/s]

Q7V4T8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A0A1A0DHK0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

 28%|██████████████████████████████████████                                                                                                   | 356/1281 [01:06<02:52,  5.37it/s]

C1A872
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Gemmatimonadota (phylum), Gemmatimonadia (class), Gemmatimonadales (order), Gemmatimonadaceae (family), Gemmatimonas (genus), Gemmatimonas aurantiaca (species)

A0A395VB65
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Roseburia (genus)

 28%|██████████████████████████████████████▎                                                                                                  | 358/1281 [01:06<02:51,  5.39it/s]

A7MFK3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Cronobacter (genus), Cronobacter sakazakii (species)

J4KM12
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus), Beauveria bassiana (species)

 28%|██████████████████████████████████████▌                                                                                                  | 360/1281 [01:07<02:51,  5.38it/s]

A1SY01
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Psychromonadaceae (family), Psychromonas (genus), Psychromonas ingrahamii (species)

A0A1H4DJ49
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Geopsychrobacteraceae (family), Desulfuromusa (genus)

 28%|██████████████████████████████████████▋                                                                                                  | 362/1281 [01:07<02:50,  5.38it/s]

A0A9R0NTP8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Amycolatopsis (genus), Amycolatopsis mediterranei (species)

A3PAY4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 28%|██████████████████████████████████████▉                                                                                                  | 364/1281 [01:07<02:50,  5.39it/s]

B4CV94
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Spartobacteria (class), Chthoniobacterales (order), Chthoniobacteraceae (family), Chthoniobacter (genus), Chthoniobacter flavus (species)

A2C095
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 29%|███████████████████████████████████████▏                                                                                                 | 366/1281 [01:08<02:50,  5.38it/s]

Q2HD43
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Sordariomycetidae (subclass), Sordariales (order), Chaetomiaceae (family), Chaetomium (genus), Chaetomium globosum (species)

A0A836M2B6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 29%|███████████████████████████████████████▎                                                                                                 | 368/1281 [01:08<02:50,  5.36it/s]

H6RWK9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Geodermatophilales (order), Geodermatophilaceae (family), Blastococcus (genus), Blastococcus saxobsidens (species)

A0A087EQK8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Lactobacillaceae (family), Apilactobacillus (genus)

 29%|███████████████████████████████████████▌                                                                                                 | 370/1281 [01:09<02:49,  5.36it/s]

A0A1I0AQM4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosospira (genus)

L7CG11
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

 29%|███████████████████████████████████████▊                                                                                                 | 372/1281 [01:09<02:49,  5.35it/s]

A0A248LNK5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Laribacter (genus)

B7FTM9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Bacillariophyta (phylum), Bacillariophyceae (class), Bacillariophycidae (clade), Naviculales (order), Phaeodactylaceae (family), Phaeodactylum (genus), Phaeodactylum tricornutum (species)

 29%|███████████████████████████████████████▉                                                                                                 | 374/1281 [01:09<02:49,  5.35it/s]

L0K9M1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Halanaerobiales (order), Halobacteroidaceae (family), Halobacteroides (genus), Halobacteroides halobius (species)

I4D6Z7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus acidiphilus (species)

 29%|████████████████████████████████████████▏                                                                                                | 376/1281 [01:10<02:47,  5.39it/s]

A0A2K1RA81
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Malpighiales (order), Salicaceae (family), Saliceae (tribe), Populus (genus)

Q2WBF7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Magnetospirillaceae (family), Paramagnetospirillum (genus), Paramagnetospirillum magneticum (species)

 30%|████████████████████████████████████████▍                                                                                                | 378/1281 [01:10<02:47,  5.38it/s]

A0A1B9BUU6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

A0A2S0JW39
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Lysinibacillus (genus)

 30%|████████████████████████████████████████▋                                                                                                | 380/1281 [01:10<02:47,  5.37it/s]

A0A2S5YID7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Rathayibacter (genus), unclassified Rathayibacter (no rank)

B3PIH2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Cellvibrionales (order), Cellvibrionaceae (family), Cellvibrio (genus), Cellvibrio japonicus (species)

 30%|████████████████████████████████████████▊                                                                                                | 382/1281 [01:11<02:47,  5.38it/s]

U3P8G1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Leifsonia (genus), Leifsonia xyli (species), Leifsonia xyli subsp. cynodontis (subspecies)

C9R9J0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Thermoanaerobacterales (order), Thermoanaerobacteraceae (family), Ammonifex (genus), Ammonifex degensii (species)

 30%|█████████████████████████████████████████                                                                                                | 384/1281 [01:11<02:47,  5.35it/s]

A8AC17
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Desulfurococcales (order), Desulfurococcaceae (family), Ignicoccus (genus), Ignicoccus hospitalis (species)

F0YLV7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Pelagophyceae (class), Pelagomonadales (order), Pelagomonadaceae (family), Aureococcus (genus)

 30%|█████████████████████████████████████████▎                                                                                               | 386/1281 [01:12<02:47,  5.34it/s]

A0A1D3GAE9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Neisseriaceae (family), Neisseria (genus)

C1MHX0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus), Micromonas pusilla (species)

 30%|█████████████████████████████████████████▍                                                                                               | 388/1281 [01:12<02:47,  5.34it/s]

A0A1H4KAQ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Phyllobacteriaceae (family), Nitratireductor (genus)

A0A2T4XZC1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

 30%|█████████████████████████████████████████▋                                                                                               | 390/1281 [01:12<02:46,  5.35it/s]

A1B3N0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Paracoccaceae (family), Paracoccus (genus), Paracoccus denitrificans (species)

C7LW87
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfomicrobiaceae (family), Desulfomicrobium (genus), Desulfomicrobium baculatum (species)

 31%|█████████████████████████████████████████▉                                                                                               | 392/1281 [01:13<02:45,  5.38it/s]

A1SZ12
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Psychromonadaceae (family), Psychromonas (genus), Psychromonas ingrahamii (species)

A0A2T2Y0D5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Kluyvera (genus)

 31%|██████████████████████████████████████████▏                                                                                              | 394/1281 [01:13<02:44,  5.40it/s]

A0A1H8D0R8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosospira (genus)

A0A2S5V2F6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 31%|██████████████████████████████████████████▎                                                                                              | 396/1281 [01:13<02:43,  5.40it/s]

G3IYW2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus), Methylobacter tundripaludum (species)

F5L8M7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Caldalkalibacillus (genus), Caldalkalibacillus thermarum (species)

 31%|██████████████████████████████████████████▌                                                                                              | 398/1281 [01:14<02:43,  5.41it/s]

C7BJG7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus), Photorhabdus asymbiotica (species), Photorhabdus asymbiotica subsp. asymbiotica (subspecies)

E4U5Z1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deinococcota (phylum), Deinococci (class), Thermales (order), Thermaceae (family), Oceanithermus (genus), Oceanithermus profundus (species)

 31%|██████████████████████████████████████████▊                                                                                              | 400/1281 [01:14<02:43,  5.39it/s]

A0A1B9K8L2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

A0A2S5WMT7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 31%|██████████████████████████████████████████▉                                                                                              | 402/1281 [01:15<02:43,  5.39it/s]

A0A0D2UPA8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Filasterea (class), Capsaspora (genus), Capsaspora owczarzaki (species)

A0A161SKF4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Microbacterium (genus), unclassified Microbacterium (no rank)

 32%|███████████████████████████████████████████▏                                                                                             | 404/1281 [01:15<02:43,  5.37it/s]

B4D7W2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Spartobacteria (class), Chthoniobacterales (order), Chthoniobacteraceae (family), Chthoniobacter (genus), Chthoniobacter flavus (species)

A0A1H3WA00
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Lonsdalea (genus)

 32%|███████████████████████████████████████████▍                                                                                             | 406/1281 [01:15<02:42,  5.37it/s]

C1D6X6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Laribacter (genus), Laribacter hongkongensis (species)

A0A4D6KHD1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloarculaceae (family), Halomicrobium (genus)

 32%|███████████████████████████████████████████▋                                                                                             | 408/1281 [01:16<02:42,  5.37it/s]

Q488X2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Colwelliaceae (family), Colwellia (genus), Colwellia psychrerythraea (species)

A9V5W4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Choanoflagellata (class), Craspedida (order), Salpingoecidae (family), Monosiga (genus)

 32%|███████████████████████████████████████████▊                                                                                             | 410/1281 [01:16<02:42,  5.35it/s]

A0A5M4ATH9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Prolixibacter (genus)

E4TRS4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Marivirgaceae (family), Marivirga (genus), Marivirga tractuosa (species)

 32%|████████████████████████████████████████████                                                                                             | 412/1281 [01:16<02:41,  5.39it/s]

A0A011U1K7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Phyllobacteriaceae (family), Aquamicrobium (genus)

C7R314
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Jonesiaceae (family), Jonesia (genus), Jonesia denitrificans (species)

 32%|████████████████████████████████████████████▎                                                                                            | 414/1281 [01:17<02:41,  5.37it/s]

A0A077EFU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Weeksellaceae (family), Elizabethkingia (genus), Elizabethkingia anophelis (species)

A0A0A2A0Y9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 32%|████████████████████████████████████████████▍                                                                                            | 416/1281 [01:17<02:41,  5.35it/s]

A0A0D8BQX6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Geobacillus (genus), Geobacillus thermoleovorans group (no rank)

A0A0L0S493
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Blastocladiomycota (phylum), Blastocladiomycetes (class), Blastocladiales (order), Blastocladiaceae (family), Allomyces (genus), Allomyces macrogynus (species)

 33%|████████████████████████████████████████████▋                                                                                            | 418/1281 [01:17<02:41,  5.36it/s]

A0A328Q6M1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanosphaera (genus)

A0A016XCG9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Hylemonella (genus), Hylemonella gracilis (species)

 33%|████████████████████████████████████████████▉                                                                                            | 420/1281 [01:18<02:41,  5.34it/s]

B7FSA7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Bacillariophyta (phylum), Bacillariophyceae (class), Bacillariophycidae (clade), Naviculales (order), Phaeodactylaceae (family), Phaeodactylum (genus), Phaeodactylum tricornutum (species)

G0AFH4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Collimonas (genus), Collimonas fungivorans (species)

 33%|█████████████████████████████████████████████▏                                                                                           | 422/1281 [01:18<02:40,  5.34it/s]

A0A177W826
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Chytridiomycota (phylum), Chytridiomycota incertae sedis (no rank), Chytridiomycetes (class), Rhizophydiales (order), Rhizophydiales incertae sedis (no rank), Batrachochytrium (genus), Batrachochytrium dendrobatidis (species)

A0A2S8GF54
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

 33%|█████████████████████████████████████████████▎                                                                                           | 424/1281 [01:19<02:40,  5.34it/s]

Q1YDY8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Aurantimonas (genus), Aurantimonas manganoxydans (species)

Q5QVH2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Idiomarinaceae (family), Idiomarina (genus), Idiomarina loihiensis (species)

 33%|█████████████████████████████████████████████▌                                                                                           | 426/1281 [01:19<02:40,  5.34it/s]

A3ZT81
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus), Blastopirellula marina (species)

A0AA35XZV0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus)

 33%|█████████████████████████████████████████████▊                                                                                           | 428/1281 [01:19<02:39,  5.34it/s]

F4H924
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Gallibacterium (genus), Gallibacterium anatis (species)

K0NJH2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobacula (genus), Desulfobacula toluolica (species)

 34%|█████████████████████████████████████████████▉                                                                                           | 430/1281 [01:20<02:38,  5.37it/s]

A0A1V3SSW1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Nitrospirota (phylum), Nitrospiria (class), Nitrospirales (order), Nitrospiraceae (family), Leptospirillum (genus), Leptospirillum sp. Group III (no rank)

F2AUF4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

 34%|██████████████████████████████████████████████▏                                                                                          | 432/1281 [01:20<02:37,  5.41it/s]

A6DN47
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Lentisphaerota (phylum), Lentisphaeria (class), Lentisphaerales (order), Lentisphaeraceae (family), Lentisphaera (genus), Lentisphaera araneosa (species)

W8KM07
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Ectothiorhodospiraceae (family), Ectothiorhodospira (genus)

 34%|██████████████████████████████████████████████▍                                                                                          | 434/1281 [01:21<02:47,  5.05it/s]

A0A1X3RP39
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Lonsdalea (genus)

A0A7S0KKL8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus)

 34%|██████████████████████████████████████████████▋                                                                                          | 436/1281 [01:21<02:45,  5.10it/s]

A0A318QZ80
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

K8VZC6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus), Providencia sneebia (species)

 34%|██████████████████████████████████████████████▊                                                                                          | 438/1281 [01:21<02:43,  5.17it/s]

A0A1B9JZS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

A0A2S6GKN5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus)

 34%|███████████████████████████████████████████████                                                                                          | 440/1281 [01:22<02:41,  5.21it/s]

A0A4R2Z2K6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Rahnella (genus), unclassified Rahnella (no rank)

H1YCC3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Sphingobacteriia (class), Sphingobacteriales (order), Sphingobacteriaceae (family), Mucilaginibacter (genus), Mucilaginibacter paludis (species)

 35%|███████████████████████████████████████████████▎                                                                                         | 442/1281 [01:22<02:39,  5.25it/s]

E1QIU3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfarculia (class), Desulfarculales (order), Desulfarculaceae (family), Desulfarculus (genus), Desulfarculus baarsii (species)

A0A8H6MPB9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Glomerellales (order), Glomerellaceae (family), Colletotrichum (genus), Colletotrichum orchidearum species complex (no rank)

 35%|███████████████████████████████████████████████▍                                                                                         | 444/1281 [01:22<02:37,  5.31it/s]

A0A369N7Y3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Eggerthella (genus)

T2IEJ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Aphanothecaceae (family), Crocosphaera (genus), Crocosphaera watsonii (species)

 35%|███████████████████████████████████████████████▋                                                                                         | 446/1281 [01:23<02:36,  5.35it/s]

H5UND3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Dermatophilaceae (family), Mobilicoccus (genus), Mobilicoccus pelagius (species)

Q1PX09
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Candidatus Brocadiia (class), Candidatus Brocadiales (order), Candidatus Brocadiaceae (family), Candidatus Kuenenia (genus)

 35%|███████████████████████████████████████████████▉                                                                                         | 448/1281 [01:23<02:35,  5.35it/s]

A0A149TSA9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

F2NGJ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobaccia (class), Desulfobaccales (order), Desulfobaccaceae (family), Desulfobacca (genus), Desulfobacca acetoxidans (species)

 35%|████████████████████████████████████████████████▏                                                                                        | 450/1281 [01:24<02:34,  5.37it/s]

A0A0E3SHQ9
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

Q5FLR6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Lactobacillaceae (family), Lactobacillus (genus), Lactobacillus acidophilus (species)

 35%|████████████████████████████████████████████████▎                                                                                        | 452/1281 [01:24<02:34,  5.36it/s]

S0EUS1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Armatimonadota (phylum), Chthonomonadia (class), Chthonomonadales (order), Chthonomonadaceae (family), Chthonomonas (genus), Chthonomonas calidirosea (species)

A0A369M386
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Gordonibacter (genus)

 35%|████████████████████████████████████████████████▌                                                                                        | 454/1281 [01:24<02:34,  5.35it/s]

W0DZS7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Marichromatium (genus), Marichromatium purpuratum (species)

A8MCL4
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Thermoproteales (order), Thermoproteaceae (family), Caldivirga (genus), Caldivirga maquilingensis (species)

 36%|████████████████████████████████████████████████▊                                                                                        | 456/1281 [01:25<02:38,  5.21it/s]

V3ZVE4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Spiralia (clade), Lophotrochozoa (clade), Mollusca (phylum), Gastropoda (class), Patellogastropoda (subclass), Lottioidea (superfamily), Lottiidae (family), Lottia (genus)

O26757
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanothermobacter (genus), Methanothermobacter thermautotrophicus (species)

 36%|████████████████████████████████████████████████▉                                                                                        | 458/1281 [01:25<02:38,  5.19it/s]

A0A317FZW2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Butyrivibrio (genus)

A0A085GI50
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Buttiauxella (genus), Buttiauxella agrestis (species)

 36%|█████████████████████████████████████████████████▏                                                                                       | 460/1281 [01:25<02:36,  5.24it/s]

A1ZGK6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Microscillaceae (family), Microscilla (genus), Microscilla marina (species)

G0IYI2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Cyclobacterium (genus), Cyclobacterium marinum (species)

 36%|█████████████████████████████████████████████████▍                                                                                       | 462/1281 [01:26<02:35,  5.26it/s]

A7S731
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

A0A1U9YY82
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Martelella (genus), Martelella mediterranea (species)

 36%|█████████████████████████████████████████████████▌                                                                                       | 464/1281 [01:26<02:34,  5.30it/s]

A0A328EMN2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Dehalococcoidia (class), Dehalococcoidales (order), Dehalococcoidaceae (family), Dehalococcoides (genus)

A0A8E2UDJ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 36%|█████████████████████████████████████████████████▊                                                                                       | 466/1281 [01:27<02:33,  5.32it/s]

A0A2S5WUP6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

A0A8H7P8U1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetes incertae sedis (no rank), Polyporales (order), Postiaceae (family), Postia (genus)

 37%|██████████████████████████████████████████████████                                                                                       | 468/1281 [01:27<02:32,  5.32it/s]

A0A257T7G4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

B3MX93
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Brachycera (suborder), Muscomorpha (infraorder), Eremoneura (clade), Cyclorrhapha (clade), Schizophora (no rank), Acalyptratae (no rank), Ephydroidea (superfamily), Drosophilidae (family), Drosophilinae (subfamily), Drosophilini (tribe), Drosophila (genus), Sophophora (subgenus), melanogaster group (no rank), ananassae subgroup (no rank), ananassae species complex (no rank)

 37%|██████████████████████████████████████████████████▎                                                                                      | 470/1281 [01:27<02:32,  5.33it/s]

A0A1G5W0P2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Negativicutes (class), Veillonellales (order), Veillonellaceae (family), Allisonella (genus)

D4H2Y7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Geovibrionaceae (family), Denitrovibrio (genus), Denitrovibrio acetiphilus (species)

 37%|██████████████████████████████████████████████████▍                                                                                      | 472/1281 [01:28<02:31,  5.34it/s]

A0A4P8HC89
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Brevibacteriaceae (family), Brevibacterium (genus), unclassified Brevibacterium (no rank)

Q7T070
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Actinopterygii (superclass), Actinopteri (class), Neopterygii (subclass), Teleostei (infraclass), Osteoglossocephalai (clade), Clupeocephala (no rank), Otomorpha (cohort), Ostariophysi (subcohort), Otophysi (clade), Cypriniphysae (superorder), Cypriniformes (order), Cyprinoidei (suborder), Danionidae (family), Danioninae (subfamily), Danio (genus)

 37%|██████████████████████████████████████████████████▋                                                                                      | 474/1281 [01:28<02:30,  5.35it/s]

F7NPQ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Negativicutes (class), Selenomonadales (order), Sporomusaceae (family), Acetonema (genus), Acetonema longum (species)

B9SA70
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Malpighiales (order), Euphorbiaceae (family), Acalyphoideae (subfamily), Acalypheae (tribe), Ricinus (genus)

 37%|██████████████████████████████████████████████████▉                                                                                      | 476/1281 [01:28<02:31,  5.33it/s]

Q9M6N7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), malvids (clade), Brassicales (order), Brassicaceae (family), Camelineae (tribe), Arabidopsis (genus)

I7ZHW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Nevskiales (order), Nevskiaceae (family), Hydrocarboniphaga (genus), Hydrocarboniphaga effusa (species)

 37%|███████████████████████████████████████████████████                                                                                      | 478/1281 [01:29<02:30,  5.34it/s]

F4XTK4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Oscillatoriales (order), Oscillatoriaceae (family), Moorena (genus), Moorena producens (species)

A4G1J2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Herminiimonas (genus)

 37%|███████████████████████████████████████████████████▎                                                                                     | 480/1281 [01:29<02:30,  5.33it/s]

G7WFX4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

B8JBH5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Myxococcia (class), Myxococcales (order), Cystobacterineae (suborder), Anaeromyxobacteraceae (family), Anaeromyxobacter (genus), Anaeromyxobacter dehalogenans (species)

 38%|███████████████████████████████████████████████████▌                                                                                     | 482/1281 [01:30<02:29,  5.35it/s]

D9QPC8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus), Brevundimonas subvibrioides (species)

A0A4R7GKA0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Rahnella (genus), unclassified Rahnella (no rank)

 38%|███████████████████████████████████████████████████▊                                                                                     | 484/1281 [01:30<02:28,  5.35it/s]

R9PMC6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Agarivorans (genus), Agarivorans albus (species)

A0A0E3LMT4
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

 38%|███████████████████████████████████████████████████▉                                                                                     | 486/1281 [01:30<02:28,  5.35it/s]

A0A511NGC7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Weeksellaceae (family), Empedobacter (genus), Empedobacter brevis (species)

E4NS62
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Halogeometricum (genus), Halogeometricum borinquense (species)

 38%|████████████████████████████████████████████████████▏                                                                                    | 488/1281 [01:31<02:27,  5.36it/s]

E4T3F7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Paludibacteraceae (family), Paludibacter (genus), Paludibacter propionicigenes (species)

M0D580
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloarculaceae (family), Halosimplex (genus), Halosimplex carlsbadense (species)

 38%|████████████████████████████████████████████████████▍                                                                                    | 490/1281 [01:31<02:27,  5.37it/s]

J7J5E7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus meridiei (species)

B1XZU2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Leptothrix (genus), Leptothrix cholodnii (species)

 38%|████████████████████████████████████████████████████▌                                                                                    | 492/1281 [01:31<02:27,  5.36it/s]

A0A366IE34
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Brenneria (genus), Brenneria salicis (species)

A0A6U2BIY7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus)

 39%|████████████████████████████████████████████████████▊                                                                                    | 494/1281 [01:32<02:26,  5.37it/s]

Q9QXP0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Sarcopterygii (superclass), Dipnotetrapodomorpha (clade), Tetrapoda (clade), Amniota (clade), Mammalia (class), Theria (clade), Eutheria (clade), Boreoeutheria (clade), Euarchontoglires (superorder), Glires (clade), Rodentia (order), Myomorpha (suborder), Muroidea (clade), Muridae (family), Murinae (subfamily), Mus (genus), Mus (subgenus)

A0A424WAH3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Achromobacter (genus)

 39%|█████████████████████████████████████████████████████                                                                                    | 496/1281 [01:32<02:26,  5.35it/s]

A0A410K1J5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Geovibrionaceae (family), Geovibrio (genus)

L1IHZ8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

 39%|█████████████████████████████████████████████████████▎                                                                                   | 498/1281 [01:33<02:26,  5.36it/s]

I8TC71
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Nevskiales (order), Nevskiaceae (family), Hydrocarboniphaga (genus), Hydrocarboniphaga effusa (species)

A0A7U8C744
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Neptuniibacter (genus)

 39%|█████████████████████████████████████████████████████▍                                                                                   | 500/1281 [01:33<02:25,  5.35it/s]

A8M670
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micromonosporales (order), Micromonosporaceae (family), Salinispora (genus), Salinispora arenicola (species)

A0A0S4VNK2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank)

 39%|█████████████████████████████████████████████████████▋                                                                                   | 502/1281 [01:33<02:25,  5.36it/s]

Q2SIR0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Hahellaceae (family), Hahella (genus), Hahella chejuensis (species)

A0A5C4RNH5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus), Photorhabdus luminescens (species)

 39%|█████████████████████████████████████████████████████▉                                                                                   | 504/1281 [01:34<02:24,  5.36it/s]

A0A3E0X011
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Ectothiorhodospiraceae (family), Alkalilimnicola (genus)

A0A0E3SP24
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

 40%|██████████████████████████████████████████████████████                                                                                   | 506/1281 [01:34<02:24,  5.35it/s]

E1IF27
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Chloroflexia (class), Chloroflexales (order), Chloroflexineae (suborder), Oscillochloridaceae (family), Oscillochloris (genus), Oscillochloris trichoides (species)

Q2YBP7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosospira (genus), Nitrosospira multiformis (species)

 40%|██████████████████████████████████████████████████████▎                                                                                  | 508/1281 [01:34<02:24,  5.33it/s]

A0A2S5WZU0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

A0A172YBR4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Halomonadaceae (family), Halotalea (genus)

 40%|██████████████████████████████████████████████████████▌                                                                                  | 510/1281 [01:35<02:23,  5.36it/s]

A0A0K2STK6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Gonyaulacales (order), Pyrocystaceae (family), Alexandrium (genus)

A0A2N6JV02
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Hapalosiphonaceae (family), Fischerella (genus), Fischerella muscicola (species)

 40%|██████████████████████████████████████████████████████▊                                                                                  | 512/1281 [01:35<02:24,  5.34it/s]

F0S0G1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Aquificota (phylum), Aquificia (class), Desulfurobacteriales (order), Desulfurobacteriaceae (family), Desulfurobacterium (genus), Desulfurobacterium thermolithotrophum (species)

A0A1C7EL50
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Planococcaceae (family), Planococcus (genus)

 40%|██████████████████████████████████████████████████████▉                                                                                  | 514/1281 [01:36<02:23,  5.33it/s]

Q18PF5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Actinopterygii (superclass), Actinopteri (class), Neopterygii (subclass), Teleostei (infraclass), Osteoglossocephalai (clade), Clupeocephala (no rank), Euteleosteomorpha (cohort), Neoteleostei (clade), Eurypterygia (clade), Ctenosquamata (clade), Acanthomorphata (clade), Euacanthomorphacea (clade), Percomorphaceae (clade), Eupercaria (clade), Tetraodontiformes (order), Tetraodontoidei (suborder), Tetradontoidea (superfamily), Tetraodontidae (family), Takifugu (genus)

A0A1I0C958
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Peptostreptococcales (order), Natronincolaceae (family), Natronincola (genus)

 40%|███████████████████████████████████████████████████████▏                                                                                 | 516/1281 [01:36<02:23,  5.32it/s]

A0AA35XVN2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus)

L8GGA0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Discosea (phylum), Longamoebia (order), Centramoebida (clade), Acanthamoebidae (family), Acanthamoeba (genus), Acanthamoeba castellanii (species)

 40%|███████████████████████████████████████████████████████▍                                                                                 | 518/1281 [01:36<02:22,  5.36it/s]

Q3AP28
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Chlorobium/Pelodictyon group (no rank), Chlorobium (genus), Chlorobium chlorochromatii (species)

D0MFE9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Rhodothermota (phylum), Rhodothermia (class), Rhodothermales (order), Rhodothermaceae (family), Rhodothermus (genus), Rhodothermus marinus (species)

 41%|███████████████████████████████████████████████████████▌                                                                                 | 520/1281 [01:37<02:22,  5.33it/s]

J9VXX9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Tremellomycetes (class), Tremellales (order), Cryptococcaceae (family), Cryptococcus (genus), Cryptococcus neoformans species complex (no rank), Cryptococcus neoformans (species), Cryptococcus neoformans var. grubii (varietas)

A0A166IS52
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Nodularia (genus), Nodularia spumigena (species)

 41%|███████████████████████████████████████████████████████▊                                                                                 | 522/1281 [01:37<02:22,  5.34it/s]

F0J7D3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acidiphilium (genus), Acidiphilium multivorum (species)

W7QG13
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Catenovulum (genus), Catenovulum agarivorans (species)

 41%|████████████████████████████████████████████████████████                                                                                 | 524/1281 [01:37<02:21,  5.35it/s]

A4BMY5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Ectothiorhodospiraceae (family), Nitrococcus (genus), Nitrococcus mobilis (species)

A6LV49
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Clostridiaceae (family), Clostridium (genus), Clostridium beijerinckii (species)

 41%|████████████████████████████████████████████████████████▎                                                                                | 526/1281 [01:38<02:21,  5.35it/s]

Q1H483
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Methylophilaceae (family), Methylobacillus (genus), Methylobacillus flagellatus (species)

A6M3G0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Clostridiaceae (family), Clostridium (genus), Clostridium beijerinckii (species)

 41%|████████████████████████████████████████████████████████▍                                                                                | 528/1281 [01:38<02:21,  5.33it/s]

E4T0A4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Paludibacteraceae (family), Paludibacter (genus), Paludibacter propionicigenes (species)

A0A3E2UHE6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Oscillospiraceae (family), Faecalibacterium (genus)

 41%|████████████████████████████████████████████████████████▋                                                                                | 530/1281 [01:39<02:20,  5.35it/s]

A0A174SD65
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Anaerostipes (genus)

A0A855EH99
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Leclercia (genus)

 42%|████████████████████████████████████████████████████████▉                                                                                | 532/1281 [01:39<02:19,  5.36it/s]

C3YB74
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Cephalochordata (subphylum), Leptocardii (class), Amphioxiformes (order), Branchiostomatidae (family), Branchiostoma (genus)

A0A074KZD8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cytophagaceae (family), Anditalea (genus)

 42%|█████████████████████████████████████████████████████████                                                                                | 534/1281 [01:39<02:20,  5.32it/s]

J0S2I0
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanomicrobiaceae (family), Methanofollis (genus), Methanofollis liminatans (species)

K9WSX4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Nostocaceae (family), Cylindrospermum (genus), Cylindrospermum stagnale (species)

 42%|█████████████████████████████████████████████████████████▎                                                                               | 536/1281 [01:40<02:19,  5.34it/s]

E8RLT5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Asticcacaulis (genus), Asticcacaulis excentricus (species)

Q2FS34
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanospirillaceae (family), Methanospirillum (genus), Methanospirillum hungatei (species)

 42%|█████████████████████████████████████████████████████████▌                                                                               | 538/1281 [01:40<02:19,  5.32it/s]

Q3Z7F9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Dehalococcoidia (class), Dehalococcoidales (order), Dehalococcoidaceae (family), Dehalococcoides (genus), Dehalococcoides mccartyi (species)

Q2S8H9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Hahellaceae (family), Hahella (genus), Hahella chejuensis (species)

 42%|█████████████████████████████████████████████████████████▊                                                                               | 540/1281 [01:40<02:18,  5.34it/s]

A0A060HN92
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Nitrososphaerota (phylum), Nitrososphaeria (class), Nitrososphaerales (order), Nitrososphaeraceae (family), Nitrososphaera (genus), Nitrososphaera viennensis (species)

E6ME92
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Pseudoramibacter (genus), Pseudoramibacter alactolyticus (species)

 42%|█████████████████████████████████████████████████████████▉                                                                               | 542/1281 [01:41<02:17,  5.36it/s]

A0A172RYW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Denitrobacterium (genus)

L0FU80
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Echinicola (genus), Echinicola vietnamensis (species)

 42%|██████████████████████████████████████████████████████████▏                                                                              | 544/1281 [01:41<02:17,  5.37it/s]

C8WZE0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfohalobiaceae (family), Desulfohalobium (genus), Desulfohalobium retbaense (species)

A0A2S8F4W0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

 43%|██████████████████████████████████████████████████████████▍                                                                              | 546/1281 [01:42<02:16,  5.38it/s]

A0A2C6C0X3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Budviciaceae (family), Budvicia (genus)

F3ZVV4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Thermoanaerobacterales (order), Thermoanaerobacterales Family IV. Incertae Sedis (family), Mahella (genus), Mahella australiensis (species)

 43%|██████████████████████████████████████████████████████████▌                                                                              | 548/1281 [01:42<02:16,  5.36it/s]

A0A7R6PER3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Neptunomonas (genus), Neptunomonas japonica (species)

A0A495WJM6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Barnesiellaceae (family), Coprobacter (genus), Coprobacter fastidiosus (species)

 43%|██████████████████████████████████████████████████████████▊                                                                              | 550/1281 [01:42<02:16,  5.34it/s]

A0A0B4DUR9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Leisingera (genus), unclassified Leisingera (no rank)

A0A251YU48
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

 43%|███████████████████████████████████████████████████████████                                                                              | 552/1281 [01:43<02:15,  5.37it/s]

A5D4I5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfotomaculaceae (family), Pelotomaculum (genus), Pelotomaculum thermopropionicum (species)

A0A2X2C038
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Proteus (genus)

 43%|███████████████████████████████████████████████████████████▏                                                                             | 554/1281 [01:43<02:14,  5.39it/s]

A0A2A2M8K7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus)

D3FBG3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Thermoleophilia (class), Solirubrobacterales (order), Conexibacteraceae (family), Conexibacter (genus), Conexibacter woesei (species)

 43%|███████████████████████████████████████████████████████████▍                                                                             | 556/1281 [01:43<02:14,  5.41it/s]

A0A2V4EA49
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

D0MFE8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Rhodothermota (phylum), Rhodothermia (class), Rhodothermales (order), Rhodothermaceae (family), Rhodothermus (genus), Rhodothermus marinus (species)

 44%|███████████████████████████████████████████████████████████▋                                                                             | 558/1281 [01:44<02:13,  5.41it/s]

Q3B6Q2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Chlorobium/Pelodictyon group (no rank), Pelodictyon (genus), Pelodictyon luteolum (species)

A0A1B9KID3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 44%|███████████████████████████████████████████████████████████▉                                                                             | 560/1281 [01:44<02:13,  5.38it/s]

A0A9J9ES23
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Paraglaciecola (genus), unclassified Paraglaciecola (no rank)

A0A3N2SFS2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Kluyvera (genus)

 44%|████████████████████████████████████████████████████████████                                                                             | 562/1281 [01:45<02:14,  5.37it/s]

Q0VLH1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Alcanivoracaceae (family), Alcanivorax (genus), Alcanivorax borkumensis (species)

A0A1U9Z147
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Martelella (genus), Martelella mediterranea (species)

 44%|████████████████████████████████████████████████████████████▎                                                                            | 564/1281 [01:45<02:13,  5.37it/s]

Q0G2T1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Fulvimarina (genus), Fulvimarina pelagi (species)

A6GJF5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Polyangia (subclass), Nannocystales (order), Nannocystaceae (family), Plesiocystis (genus), Plesiocystis pacifica (species)

 44%|████████████████████████████████████████████████████████████▌                                                                            | 566/1281 [01:45<02:13,  5.36it/s]

A0A059XXR1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Nitrospirota (phylum), Nitrospiria (class), Nitrospirales (order), Nitrospiraceae (family), Leptospirillum (genus), Leptospirillum sp. Group III (no rank), Leptospirillum ferriphilum (species)

A0A5J6WPP9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Moritellaceae (family), Moritella (genus), Moritella marina (species)

 44%|████████████████████████████████████████████████████████████▋                                                                            | 568/1281 [01:46<02:13,  5.35it/s]

P41948
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Saccharomyces (genus), Saccharomyces cerevisiae (species)

L1IUV5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

 44%|████████████████████████████████████████████████████████████▉                                                                            | 570/1281 [01:46<02:12,  5.36it/s]

A0A2W0GQV0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank), unclassified Enterobacter cloacae complex (no rank)

Q1K433
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Desulfuromonadaceae (family), Desulfuromonas (genus), Desulfuromonas acetoxidans (species)

 45%|█████████████████████████████████████████████████████████████▏                                                                           | 572/1281 [01:46<02:12,  5.37it/s]

A0A4Y7XC43
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Alkanindiges (genus)

D5AU98
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus), Rhodobacter capsulatus (species)

 45%|█████████████████████████████████████████████████████████████▍                                                                           | 574/1281 [01:47<02:11,  5.36it/s]

E1QFA8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfarculia (class), Desulfarculales (order), Desulfarculaceae (family), Desulfarculus (genus), Desulfarculus baarsii (species)

A0A075WBP9
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Archaeoglobi (class), Archaeoglobales (order), Archaeoglobaceae (family), Archaeoglobus (genus), Archaeoglobus fulgidus (species)

 45%|█████████████████████████████████████████████████████████████▌                                                                           | 576/1281 [01:47<02:12,  5.33it/s]

Q0BWD0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomonadales (order), Hyphomonadaceae (family), Hyphomonas (genus), Hyphomonas neptunium (species)

A0A1Y0HX98
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Promicromonosporaceae (family), Cellulosimicrobium (genus)

 45%|█████████████████████████████████████████████████████████████▊                                                                           | 578/1281 [01:47<02:11,  5.35it/s]

A0A098S5Y7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Saprospiria (class), Saprospirales (order), Haliscomenobacteraceae (family), Phaeodactylibacter (genus)

Q0I445
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Histophilus (genus), Histophilus somni (species)

 45%|██████████████████████████████████████████████████████████████                                                                           | 580/1281 [01:48<02:10,  5.37it/s]

A0A1E5BXA4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Enterovibrio (genus), Enterovibrio norvegicus (species)

A0A2C9CK98
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Candidatus Brocadiia (class), Candidatus Brocadiales (order), Candidatus Brocadiaceae (family), Candidatus Kuenenia (genus)

 45%|██████████████████████████████████████████████████████████████▏                                                                          | 582/1281 [01:48<02:10,  5.34it/s]

G4H971
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Paenibacillaceae (family), Paenibacillus (genus), Paenibacillus lactis (species)

A0A1I0BYN1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Draconibacterium (genus)

 46%|██████████████████████████████████████████████████████████████▍                                                                          | 584/1281 [01:49<02:10,  5.34it/s]

A0A330GB00
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

A0A2S8FR08
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

 46%|██████████████████████████████████████████████████████████████▋                                                                          | 586/1281 [01:49<02:10,  5.33it/s]

Q84KJ6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), Liliopsida (clade), Petrosaviidae (subclass), commelinids (clade), Poales (order), Poaceae (family), BOP clade (clade), Oryzoideae (subfamily), Oryzeae (tribe), Oryzinae (subtribe), Oryza (genus), Oryza sativa (species)

A0A2S5WGI8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 46%|██████████████████████████████████████████████████████████████▉                                                                          | 588/1281 [01:49<02:09,  5.34it/s]

M2ALH9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula europaea (species)

A0A2K3DQF8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

 46%|███████████████████████████████████████████████████████████████                                                                          | 590/1281 [01:50<02:10,  5.30it/s]

A0A8G2IZM3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Rhizobium (genus), Rhizobium leguminosarum (species)

F5Y3C1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Ramlibacter (genus), Ramlibacter tataouinensis (species)

 46%|███████████████████████████████████████████████████████████████▎                                                                         | 592/1281 [01:50<02:09,  5.31it/s]

A0A370FPU0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Pseudacidovorax (genus)

F5RGM7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Sterolibacteriaceae (family), Methyloversatilis (genus), Methyloversatilis universalis (species)

 46%|███████████████████████████████████████████████████████████████▌                                                                         | 594/1281 [01:50<02:08,  5.34it/s]

A0A4R4K1P9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus), Photorhabdus khanii (species)

R8VWI7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Butyricicoccaceae (family), Butyricicoccus (genus), Butyricicoccus pullicaecorum (species)

 47%|███████████████████████████████████████████████████████████████▋                                                                         | 596/1281 [01:51<02:08,  5.34it/s]

A0A0A2AMW2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

Q7Z1M1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Nematocera (suborder), Culicomorpha (infraorder), Culicoidea (superfamily), Culicidae (family), Anophelinae (subfamily), Anopheles (genus), Cellia (subgenus), Pyretophorus (clade), gambiae species complex (no rank)

 47%|███████████████████████████████████████████████████████████████▉                                                                         | 598/1281 [01:51<02:07,  5.35it/s]

A0A414NWT8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Negativicutes (class), Selenomonadales (order), Selenomonadaceae (family), Mitsuokella (genus)

A0A0P6VSR8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Kaistiaceae (family), Prosthecomicrobium (genus)

 47%|████████████████████████████████████████████████████████████████▏                                                                        | 600/1281 [01:52<02:07,  5.35it/s]

A0A0L0TDW1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Blastocladiomycota (phylum), Blastocladiomycetes (class), Blastocladiales (order), Blastocladiaceae (family), Allomyces (genus), Allomyces macrogynus (species)

U3PCH5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Leifsonia (genus), Leifsonia xyli (species), Leifsonia xyli subsp. cynodontis (subspecies)

 47%|████████████████████████████████████████████████████████████████▍                                                                        | 602/1281 [01:52<02:07,  5.34it/s]

W7QGE0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Catenovulum (genus), Catenovulum agarivorans (species)

C5BWX7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Beutenbergiaceae (family), Beutenbergia (genus), Beutenbergia cavernae (species)

 47%|████████████████████████████████████████████████████████████████▌                                                                        | 604/1281 [01:52<02:06,  5.35it/s]

A0A1B9M1A9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

B8GGC3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanoregulaceae (family), Methanosphaerula (genus), Methanosphaerula palustris (species)

 47%|████████████████████████████████████████████████████████████████▊                                                                        | 606/1281 [01:53<02:06,  5.35it/s]

D6SPD1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfonatronovibrionaceae (family), Desulfonatronospira (genus), Desulfonatronospira thiodismutans (species)

A0A0H3DR67
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Edwardsiella (genus), Edwardsiella tarda (species)

 47%|█████████████████████████████████████████████████████████████████                                                                        | 608/1281 [01:53<02:06,  5.34it/s]

A0A4R7VEK0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus)

G4R7P1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Devosiaceae (family), Pelagibacterium (genus), Pelagibacterium halotolerans (species)

 48%|█████████████████████████████████████████████████████████████████▏                                                                       | 610/1281 [01:53<02:05,  5.35it/s]

A0A1M5ZVP9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Butyrivibrio (genus), Butyrivibrio fibrisolvens (species)

A0A2S5Y0D3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Rathayibacter (genus)

 48%|█████████████████████████████████████████████████████████████████▍                                                                       | 612/1281 [01:54<02:05,  5.34it/s]

I0ICG0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Phycisphaerae (class), Phycisphaerales (order), Phycisphaeraceae (family), Phycisphaera (genus), Phycisphaera mikurensis (species)

D0L8H3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Gordoniaceae (family), Gordonia (genus), Gordonia bronchialis (species)

 48%|█████████████████████████████████████████████████████████████████▋                                                                       | 614/1281 [01:54<02:05,  5.32it/s]

A0A1B9LFW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

Q6ND34
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

 48%|█████████████████████████████████████████████████████████████████▉                                                                       | 616/1281 [01:55<02:04,  5.35it/s]

A0A6H9GWG4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

Q5UZ98
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloarculaceae (family), Haloarcula (genus), Haloarcula marismortui (species)

 48%|██████████████████████████████████████████████████████████████████                                                                       | 618/1281 [01:55<02:03,  5.36it/s]

A0A2S0P9T4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Microvirgula (genus)

H2CDR5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus), Leptonema illini (species)

 48%|██████████████████████████████████████████████████████████████████▎                                                                      | 620/1281 [01:55<02:03,  5.37it/s]

T2KGT3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Formosa (genus), Formosa agariphila (species)

A0A088E6Q7
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Sulfolobales (order), Sulfolobaceae (family), Metallosphaera (genus)

 49%|██████████████████████████████████████████████████████████████████▌                                                                      | 622/1281 [01:56<02:03,  5.36it/s]

A0A258HS77
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus)

E1V4T3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Halomonadaceae (family), Halomonas (genus), Halomonas elongata (species)

 49%|██████████████████████████████████████████████████████████████████▋                                                                      | 624/1281 [01:56<02:02,  5.34it/s]

B7GKP4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Anoxybacillus (genus), Anoxybacillus flavithermus (species)

Q9QUT0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Sarcopterygii (superclass), Dipnotetrapodomorpha (clade), Tetrapoda (clade), Amniota (clade), Mammalia (class), Theria (clade), Eutheria (clade), Boreoeutheria (clade), Euarchontoglires (superorder), Glires (clade), Rodentia (order), Myomorpha (suborder), Muroidea (clade), Muridae (family), Murinae (subfamily), Mus (genus), Mus (subgenus)

 49%|██████████████████████████████████████████████████████████████████▉                                                                      | 626/1281 [01:56<02:01,  5.37it/s]

I3Z3H7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Belliella (genus), Belliella baltica (species)

G7WCB6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

 49%|███████████████████████████████████████████████████████████████████▏                                                                     | 628/1281 [01:57<02:02,  5.34it/s]

A0A1Y6GLJ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Raoultella (genus)

A0A0S2DQB6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Lysobacter (genus)

 49%|███████████████████████████████████████████████████████████████████▍                                                                     | 630/1281 [01:57<02:01,  5.34it/s]

Q6CRN1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Kluyveromyces (genus), Kluyveromyces lactis (species)

A0A401X433
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus), Acetobacter pasteurianus (species)

 49%|███████████████████████████████████████████████████████████████████▌                                                                     | 632/1281 [01:58<02:01,  5.36it/s]

A7HT14
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Parvibaculaceae (family), Parvibaculum (genus), Parvibaculum lavamentivorans (species)

A0A009TDB1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 49%|███████████████████████████████████████████████████████████████████▊                                                                     | 634/1281 [01:58<02:01,  5.33it/s]

D4XSW0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter haemolyticus (species)

B0SRS8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptospira (genus), Leptospira biflexa (species), Leptospira biflexa serovar Patoc (no rank)

 50%|████████████████████████████████████████████████████████████████████                                                                     | 636/1281 [01:58<02:01,  5.32it/s]

A0A149QSR6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconobacter (genus)

B1Y0E5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Leptothrix (genus), Leptothrix cholodnii (species)

 50%|████████████████████████████████████████████████████████████████████▏                                                                    | 638/1281 [01:59<02:00,  5.32it/s]

Q7UGU7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

A0A2S0Q8P1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Nodularia (genus), Nodularia spumigena (species)

 50%|████████████████████████████████████████████████████████████████████▍                                                                    | 640/1281 [01:59<02:00,  5.31it/s]

F0ZPL3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Evosea (phylum), Eumycetozoa (class), Dictyostelia (clade), Dictyosteliales (order), Dictyosteliaceae (family), Dictyostelium (genus)

A0A2T0GTU1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Actinopolysporales (order), Actinopolysporaceae (family), Actinopolyspora (genus)

 50%|████████████████████████████████████████████████████████████████████▋                                                                    | 642/1281 [01:59<01:59,  5.33it/s]

I4CCD1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfomonilia (class), Desulfomonilales (order), Desulfomonilaceae (family), Desulfomonile (genus), Desulfomonile tiedjei (species)

A0A9Q6P4A5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Histophilus (genus)

 50%|████████████████████████████████████████████████████████████████████▊                                                                    | 644/1281 [02:00<01:58,  5.36it/s]

A0A418VIJ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus)

C1MX19
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus), Micromonas pusilla (species)

 50%|█████████████████████████████████████████████████████████████████████                                                                    | 646/1281 [02:00<01:58,  5.35it/s]

A0A1B9BUZ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

K9W6F3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Gomontiellales (order), Gomontiellaceae (family), Crinalium (genus), Crinalium epipsammum (species)

 51%|█████████████████████████████████████████████████████████████████████▎                                                                   | 648/1281 [02:01<01:58,  5.34it/s]

Q1K8A3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Sordariomycetidae (subclass), Sordariales (order), Sordariaceae (family), Neurospora (genus), Neurospora crassa (species)

L8GFX3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Discosea (phylum), Longamoebia (order), Centramoebida (clade), Acanthamoebidae (family), Acanthamoeba (genus), Acanthamoeba castellanii (species)

 51%|█████████████████████████████████████████████████████████████████████▌                                                                   | 650/1281 [02:01<01:57,  5.35it/s]

A0A1G6ABL9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Kaistiaceae (family), Bauldia (genus)

A0A087L0B9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Serratia (genus), unclassified Serratia (in: enterobacteria) (no rank)

 51%|█████████████████████████████████████████████████████████████████████▋                                                                   | 652/1281 [02:01<01:57,  5.34it/s]

A0A073CP02
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Oscillatoriales (order), Microcoleaceae (family), Planktothrix (genus), Planktothrix agardhii (species)

A0A0A1ZJU5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 51%|█████████████████████████████████████████████████████████████████████▉                                                                   | 654/1281 [02:02<01:57,  5.34it/s]

A0A258HPP1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus)

A0A149QAW7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

 51%|██████████████████████████████████████████████████████████████████████▏                                                                  | 656/1281 [02:02<01:57,  5.33it/s]

D2V6Q5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Discoba (clade), Heterolobosea (phylum), Tetramitia (clade), Eutetramitia (clade), Vahlkampfiidae (family), Naegleria (genus)

A0A1X4G8K1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Cylindrospermopsis (genus), Cylindrospermopsis raciborskii (species)

 51%|██████████████████████████████████████████████████████████████████████▎                                                                  | 658/1281 [02:02<01:56,  5.35it/s]

A0A067Z3S3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconobacter (genus), Gluconobacter oxydans (species)

A0A8F5ZDT8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanospirillaceae (family), Methanospirillum (genus)

 52%|██████████████████████████████████████████████████████████████████████▌                                                                  | 660/1281 [02:03<01:55,  5.36it/s]

A0A854QN45
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Tremellomycetes (class), Tremellales (order), Cryptococcaceae (family), Cryptococcus (genus), Cryptococcus neoformans species complex (no rank), Cryptococcus neoformans (species), Cryptococcus neoformans var. grubii (varietas)

A0A2N7LCD7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Enterovibrio (genus)

 52%|██████████████████████████████████████████████████████████████████████▊                                                                  | 662/1281 [02:03<01:55,  5.38it/s]

G7WFX2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

A0A7S4GNJ2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Oxyrrhinales (order), Oxyrrhinaceae (family), Oxyrrhis (genus)

 52%|███████████████████████████████████████████████████████████████████████                                                                  | 664/1281 [02:04<01:54,  5.40it/s]

A4G0C5
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanococci (class), Methanococcales (order), Methanococcaceae (family), Methanococcus (genus), Methanococcus maripaludis (species)

A6VE60
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus), Pseudomonas aeruginosa group (no rank), Pseudomonas aeruginosa (species)

 52%|███████████████████████████████████████████████████████████████████████▏                                                                 | 666/1281 [02:04<01:54,  5.38it/s]

A0A1S1HM83
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus)

A0A037ZJY5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Actibacterium (genus), Actibacterium mucosum (species)

 52%|███████████████████████████████████████████████████████████████████████▍                                                                 | 668/1281 [02:04<01:54,  5.38it/s]

N1WR17
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Psychroflexus (genus), Psychroflexus gondwanensis (species)

Q2W5V2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Magnetospirillaceae (family), Paramagnetospirillum (genus), Paramagnetospirillum magneticum (species)

 52%|███████████████████████████████████████████████████████████████████████▋                                                                 | 670/1281 [02:05<01:54,  5.36it/s]

A1VIM5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Polaromonas (genus), Polaromonas naphthalenivorans (species)

A0A1Y5E3E3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Colwelliaceae (family), Colwellia (genus)

 52%|███████████████████████████████████████████████████████████████████████▊                                                                 | 672/1281 [02:05<01:53,  5.38it/s]

A0A1T4SFK4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Hyphomicrobiales incertae sedis (no rank), Enhydrobacter (genus)

A7RNC3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

 53%|████████████████████████████████████████████████████████████████████████                                                                 | 674/1281 [02:05<01:53,  5.36it/s]

M7XJ51
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Mariniradius (genus), Mariniradius saccharolyticus (species)

A0A399T909
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

 53%|████████████████████████████████████████████████████████████████████████▎                                                                | 676/1281 [02:06<01:53,  5.35it/s]

A0A2N6P374
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus)

H8L2Q4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Rhodanobacteraceae (family), Frateuria (genus), Frateuria aurantia (species)

 53%|████████████████████████████████████████████████████████████████████████▌                                                                | 678/1281 [02:06<01:52,  5.35it/s]

D5EP68
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Opitutia (class), Puniceicoccales (order), Coraliomargaritaceae (family), Coraliomargarita (genus), Coraliomargarita akajimensis (species)

E6SF19
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Intrasporangiaceae (family), Intrasporangium (genus), Intrasporangium calvum (species)

 53%|████████████████████████████████████████████████████████████████████████▋                                                                | 680/1281 [02:07<01:52,  5.36it/s]

A0A1T4SFY6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Streptosporangiales (order), Nocardiopsidaceae (family), Marinactinospora (genus), Marinactinospora thermotolerans (species)

D3LBI0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Lactobacillaceae (family), Oenococcus (genus), Oenococcus oeni (species)

 53%|████████████████████████████████████████████████████████████████████████▉                                                                | 682/1281 [02:07<01:52,  5.32it/s]

E6W5C1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Chrysiogenota (phylum), Chrysiogenia (class), Chrysiogenales (order), Chrysiogenaceae (family), Desulfurispirillum (genus), Desulfurispirillum indicum (species)

Q0VPH4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Alcanivoracaceae (family), Alcanivorax (genus), Alcanivorax borkumensis (species)

 53%|█████████████████████████████████████████████████████████████████████████▏                                                               | 684/1281 [02:07<01:52,  5.33it/s]

K9WT03
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Nostocaceae (family), Cylindrospermum (genus), Cylindrospermum stagnale (species)

L0KW14
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanomethylovorans (genus), Methanomethylovorans hollandica (species)

 54%|█████████████████████████████████████████████████████████████████████████▎                                                               | 686/1281 [02:08<01:51,  5.32it/s]

A0A4R8H081
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Halanaerobiales (order), Halobacteroidaceae (family), Orenia (genus)

A0A1B9N3H7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 54%|█████████████████████████████████████████████████████████████████████████▌                                                               | 688/1281 [02:08<01:51,  5.30it/s]

B0RC35
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

A0A420KGW4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Alicycliphilus (genus)

 54%|█████████████████████████████████████████████████████████████████████████▊                                                               | 690/1281 [02:08<01:51,  5.30it/s]

A0A4R3NLV5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus)

Q47K18
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Azonexaceae (family), Dechloromonas (genus), Dechloromonas aromatica (species)

 54%|██████████████████████████████████████████████████████████████████████████                                                               | 692/1281 [02:09<01:51,  5.30it/s]

Q21P82
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Cellvibrionales (order), Cellvibrionaceae (family), Saccharophagus (genus), Saccharophagus degradans (species)

M1WRK6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Pseudodesulfovibrio (genus), Pseudodesulfovibrio piezophilus (species)

 54%|██████████████████████████████████████████████████████████████████████████▏                                                              | 694/1281 [02:09<01:49,  5.35it/s]

A0A290XBB5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus)

A0A6T9XUR2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Alteromonas/Salinimonas group (no rank), Alteromonas (genus)

 54%|██████████████████████████████████████████████████████████████████████████▍                                                              | 696/1281 [02:10<01:48,  5.40it/s]

A0A1J1JH03
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Oscillatoriales (order), Microcoleaceae (family), Planktothrix (genus)

I3R0S7
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloferax (genus), Haloferax mediterranei (species)

 54%|██████████████████████████████████████████████████████████████████████████▋                                                              | 698/1281 [02:10<01:47,  5.42it/s]

A9UR54
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Choanoflagellata (class), Craspedida (order), Salpingoecidae (family), Monosiga (genus)

A0A1G7H8X3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus)

 55%|██████████████████████████████████████████████████████████████████████████▊                                                              | 700/1281 [02:10<01:47,  5.40it/s]

A0A8G2F718
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfomicrobiaceae (family), Desulfomicrobium (genus)

Q1H0G2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Methylophilaceae (family), Methylobacillus (genus), Methylobacillus flagellatus (species)

 55%|███████████████████████████████████████████████████████████████████████████                                                              | 702/1281 [02:11<01:47,  5.37it/s]

D0LAL7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Gordoniaceae (family), Gordonia (genus), Gordonia bronchialis (species)

C7LQR9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfomicrobiaceae (family), Desulfomicrobium (genus), Desulfomicrobium baculatum (species)

 55%|███████████████████████████████████████████████████████████████████████████▎                                                             | 704/1281 [02:11<01:47,  5.35it/s]

A0A1G5PWV0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus)

K1K628
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Aeromonadales (order), Aeromonadaceae (family), Aeromonas (genus)

 55%|███████████████████████████████████████████████████████████████████████████▌                                                             | 706/1281 [02:11<01:47,  5.35it/s]

B9SXC7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), rosids (clade), fabids (clade), Malpighiales (order), Euphorbiaceae (family), Acalyphoideae (subfamily), Acalypheae (tribe), Ricinus (genus)

G7WA28
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

 55%|███████████████████████████████████████████████████████████████████████████▋                                                             | 708/1281 [02:12<01:47,  5.33it/s]

Q1IWN6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deinococcota (phylum), Deinococci (class), Deinococcales (order), Deinococcaceae (family), Deinococcus (genus), Deinococcus geothermalis (species)

H6LKH9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Acetobacterium (genus), Acetobacterium woodii (species)

 55%|███████████████████████████████████████████████████████████████████████████▉                                                             | 710/1281 [02:12<01:46,  5.35it/s]

A0A1H7CU41
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Negativicutes (class), Selenomonadales (order), Selenomonadaceae (family), Propionispira (genus)

G8JUJ2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Eremothecium (genus), Eremothecium cymbalariae (species)

 56%|████████████████████████████████████████████████████████████████████████████▏                                                            | 712/1281 [02:13<01:45,  5.39it/s]

A0A081N2G5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Endozoicomonadaceae (family), Endozoicomonas (genus)

A0A074ME37
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Sphingomonadales (order), Erythrobacteraceae (family), Erythrobacter/Porphyrobacter group (no rank), Erythrobacter (genus)

 56%|████████████████████████████████████████████████████████████████████████████▎                                                            | 714/1281 [02:13<01:44,  5.42it/s]

Q0VQH6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Alcanivoracaceae (family), Alcanivorax (genus), Alcanivorax borkumensis (species)

C8XB51
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Nakamurellales (order), Nakamurellaceae (family), Nakamurella (genus), Nakamurella multipartita (species)

 56%|████████████████████████████████████████████████████████████████████████████▌                                                            | 716/1281 [02:13<01:44,  5.39it/s]

A1VIG8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Polaromonas (genus), Polaromonas naphthalenivorans (species)

Q8GQS1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconacetobacter (genus)

 56%|████████████████████████████████████████████████████████████████████████████▊                                                            | 718/1281 [02:14<01:44,  5.39it/s]

A0A1I7FBM5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosospira (genus)

A0A1M6ZMI3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus), Desulfatibacillum alkenivorans (species)

 56%|█████████████████████████████████████████████████████████████████████████████                                                            | 720/1281 [02:14<01:44,  5.37it/s]

A0A482PLH3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Citrobacter (genus)

A0RXK8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Nitrososphaerota (phylum), Candidatus Cenarchaeales (order), Candidatus Cenarchaeaceae (family), Candidatus Cenarchaeum (genus), Cenarchaeum symbiosum (species)

 56%|█████████████████████████████████████████████████████████████████████████████▏                                                           | 722/1281 [02:14<01:43,  5.42it/s]

D0KXQ0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Halothiobacillaceae (family), Halothiobacillus (genus), Halothiobacillus neapolitanus (species)

Q8JI14
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Actinopterygii (superclass), Actinopteri (class), Neopterygii (subclass), Teleostei (infraclass), Osteoglossocephalai (clade), Clupeocephala (no rank), Otomorpha (cohort), Ostariophysi (subcohort), Otophysi (clade), Cypriniphysae (superorder), Cypriniformes (order), Cyprinoidei (suborder), Danionidae (family), Danioninae (subfamily), Danio (genus)

 57%|█████████████████████████████████████████████████████████████████████████████▍                                                           | 724/1281 [02:15<01:42,  5.45it/s]

A0A7T4WEP4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

A0A4R3ZNW3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Dietziaceae (family), Dietzia (genus)

 57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 726/1281 [02:15<01:42,  5.42it/s]

A0A074KY88
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cytophagaceae (family), Anditalea (genus)

A0A6M3ZKU5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Herbaspirillum (genus), Herbaspirillum rubrisubalbicans (species)

 57%|█████████████████████████████████████████████████████████████████████████████▊                                                           | 728/1281 [02:15<01:42,  5.42it/s]

M1SJL5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Morganella (genus), Morganella morganii (species), Morganella morganii subsp. morganii (subspecies)

A0A1W9KSU5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Rhodoferax (genus)

 57%|██████████████████████████████████████████████████████████████████████████████                                                           | 730/1281 [02:16<01:42,  5.38it/s]

E3GI40
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Eubacterium (genus)

A0A369NYJ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Adlercreutzia (genus), Adlercreutzia equolifaciens (species)

 57%|██████████████████████████████████████████████████████████████████████████████▎                                                          | 732/1281 [02:16<01:42,  5.36it/s]

A0AA92K392
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank)

O04161
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), eudicotyledons (clade), Gunneridae (clade), Pentapetalae (clade), asterids (clade), lamiids (clade), Solanales (order), Solanaceae (family), Solanoideae (subfamily), Solaneae (tribe), Solanum (genus), Solanum subgen. Lycopersicon (subgenus)

 57%|██████████████████████████████████████████████████████████████████████████████▍                                                          | 734/1281 [02:17<01:41,  5.37it/s]

A9BQZ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Delftia (genus), Delftia acidovorans (species)

A0A6N2Z556
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Eubacterium (genus)

 57%|██████████████████████████████████████████████████████████████████████████████▋                                                          | 736/1281 [02:17<01:41,  5.36it/s]

A0A8H6NAG3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Glomerellales (order), Glomerellaceae (family), Colletotrichum (genus), Colletotrichum orchidearum species complex (no rank)

A0A2T9X1V4
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Sulfolobales (order), Sulfolobaceae (family), Acidianus (genus)

 58%|██████████████████████████████████████████████████████████████████████████████▉                                                          | 738/1281 [02:17<01:41,  5.37it/s]

Q2J376
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

A0A0F5EZP7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Avibacterium (genus)

 58%|███████████████████████████████████████████████████████████████████████████████▏                                                         | 740/1281 [02:18<01:40,  5.37it/s]

A0A7G5DK18
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus)

M9YAI9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Azotobacter group (subfamily), Azotobacter (genus), Azotobacter vinelandii (species)

 58%|███████████████████████████████████████████████████████████████████████████████▎                                                         | 742/1281 [02:18<01:40,  5.36it/s]

D2ZRW2
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobrevibacter (genus), Methanobrevibacter smithii (species)

G7UUY6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Pseudoxanthomonas (genus), Pseudoxanthomonas spadix (species)

 58%|███████████████████████████████████████████████████████████████████████████████▌                                                         | 744/1281 [02:18<01:40,  5.36it/s]

A0A8H4GS02
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus)

A0A2T5IHP0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosospira (genus)

 58%|███████████████████████████████████████████████████████████████████████████████▊                                                         | 746/1281 [02:19<01:39,  5.37it/s]

A0A165MAC2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Chlorobium/Pelodictyon group (no rank), Pelodictyon (genus)

A0A7S4LPS8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Oxyrrhinales (order), Oxyrrhinaceae (family), Oxyrrhis (genus)

 58%|███████████████████████████████████████████████████████████████████████████████▉                                                         | 748/1281 [02:19<01:39,  5.35it/s]

A0A075JIN0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Dermacoccaceae (family), Dermacoccus (genus)

C8X554
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfohalobiaceae (family), Desulfohalobium (genus), Desulfohalobium retbaense (species)

 59%|████████████████████████████████████████████████████████████████████████████████▏                                                        | 750/1281 [02:20<01:38,  5.37it/s]

B8FZP7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfitobacterium (genus), Desulfitobacterium hafniense (species)

Q5KAF6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Tremellomycetes (class), Tremellales (order), Cryptococcaceae (family), Cryptococcus (genus), Cryptococcus neoformans species complex (no rank), Cryptococcus neoformans (species), Cryptococcus neoformans var. neoformans (varietas)

 59%|████████████████████████████████████████████████████████████████████████████████▍                                                        | 752/1281 [02:20<01:38,  5.39it/s]

A0A427KNL6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

A0A7G5DPV0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus)

 59%|████████████████████████████████████████████████████████████████████████████████▋                                                        | 754/1281 [02:20<01:38,  5.38it/s]

Q22947
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Nematoda (phylum), Chromadorea (class), Rhabditida (order), Rhabditina (suborder), Rhabditomorpha (infraorder), Rhabditoidea (superfamily), Rhabditidae (family), Peloderinae (subfamily), Caenorhabditis (genus)

A0A1S1HRJ0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus)

 59%|████████████████████████████████████████████████████████████████████████████████▊                                                        | 756/1281 [02:21<01:37,  5.38it/s]

A0A3N1VXY4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Erwiniaceae (family), Erwinia (genus), unclassified Erwinia (no rank)

A0A2S7YPJ9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus)

 59%|█████████████████████████████████████████████████████████████████████████████████                                                        | 758/1281 [02:21<01:37,  5.38it/s]

I0JI83
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Halobacillus (genus), Halobacillus halophilus (species)

A0A7U3YMN6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfobulbaceae (family), Desulfobulbus (genus), Desulfobulbus propionicus (species)

 59%|█████████████████████████████████████████████████████████████████████████████████▎                                                       | 760/1281 [02:21<01:37,  5.36it/s]

Q9BLG3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Evosea (phylum), Eumycetozoa (class), Dictyostelia (clade), Dictyosteliales (order), Dictyosteliaceae (family), Dictyostelium (genus)

A0A1H9RTW8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Giesbergeria (genus)

 59%|█████████████████████████████████████████████████████████████████████████████████▍                                                       | 762/1281 [02:22<01:36,  5.39it/s]

A0A1I4W3A0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Streptosporangiales (order), Thermomonosporaceae (family), Actinomadura (genus)

A0A0B4M163
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Crustacea (subphylum), Multicrustacea (superclass), Malacostraca (class), Eumalacostraca (subclass), Eucarida (superorder), Decapoda (order), Pleocyemata (suborder), Brachyura (infraorder), Eubrachyura (no rank), Heterotremata (no rank), Portunoidea (superfamily), Portunidae (family), Portuninae (subfamily), Portunus (genus)

 60%|█████████████████████████████████████████████████████████████████████████████████▋                                                       | 764/1281 [02:22<01:36,  5.39it/s]

U2EN72
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Salinisphaerales (order), Salinisphaeraceae (family), Salinisphaera (genus), Salinisphaera shabanensis (species)

A0A2W5VAZ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Caulobacter (genus)

 60%|█████████████████████████████████████████████████████████████████████████████████▉                                                       | 766/1281 [02:23<01:35,  5.37it/s]

E4YA63
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Tunicata (subphylum), Appendicularia (class), Copelata (order), Oikopleuridae (family), Oikopleura (genus)

D5ELM4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Opitutia (class), Puniceicoccales (order), Coraliomargaritaceae (family), Coraliomargarita (genus), Coraliomargarita akajimensis (species)

 60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 768/1281 [02:23<01:35,  5.35it/s]

M9RJS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Octadecabacter (genus), Octadecabacter arcticus (species)

A0A2G3E8V2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Pseudobutyrivibrio (genus)

 60%|██████████████████████████████████████████████████████████████████████████████████▎                                                      | 770/1281 [02:23<01:35,  5.35it/s]

Q5FSX6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconobacter (genus), Gluconobacter oxydans (species)

I0HKQ8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Rubrivivax (genus), Rubrivivax gelatinosus (species)

 60%|██████████████████████████████████████████████████████████████████████████████████▌                                                      | 772/1281 [02:24<01:35,  5.34it/s]

A0A833H2R7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus)

B8ENL9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Beijerinckiaceae (family), Methylocella (genus), Methylocella silvestris (species)

 60%|██████████████████████████████████████████████████████████████████████████████████▊                                                      | 774/1281 [02:24<01:35,  5.33it/s]

B3DUX7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Verrucomicrobiota (phylum), Methylacidiphilae (class), Methylacidiphilales (order), Methylacidiphilaceae (family), Methylacidiphilum (ex Ratnadevi et al. 2023) (genus), Candidatus Methylacidiphilum infernorum (species)

A0A1D8UWJ6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Kozakia (genus)

 61%|██████████████████████████████████████████████████████████████████████████████████▉                                                      | 776/1281 [02:24<01:34,  5.35it/s]

D5E995
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanohalophilus (genus), Methanohalophilus mahii (species)

A0A7U8C2Y6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Neptuniibacter (genus)

 61%|███████████████████████████████████████████████████████████████████████████████████▏                                                     | 778/1281 [02:25<01:34,  5.34it/s]

L0KGR8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Phyllobacteriaceae (family), Mesorhizobium (genus), Mesorhizobium australicum (species)

B0VMH1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 61%|███████████████████████████████████████████████████████████████████████████████████▍                                                     | 780/1281 [02:25<01:33,  5.37it/s]

P40260
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Saccharomyces (genus), Saccharomyces cerevisiae (species)

L0JT30
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Natrialbaceae (family), Natrinema (genus), Natrinema pellirubrum (species)

 61%|███████████████████████████████████████████████████████████████████████████████████▋                                                     | 782/1281 [02:26<01:32,  5.37it/s]

C1GR74
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Onygenales (order), Ajellomycetaceae (family), Paracoccidioides (genus), Paracoccidioides lutzii (species)

A0A423Y4I6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Cronobacter (genus)

 61%|███████████████████████████████████████████████████████████████████████████████████▊                                                     | 784/1281 [02:26<01:32,  5.38it/s]

A0A4P7UHQ5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Desulfovibrio (genus)

A0A8E2R1Y5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 61%|████████████████████████████████████████████████████████████████████████████████████                                                     | 786/1281 [02:26<01:32,  5.38it/s]

I5BYV5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Nitritalea (genus), Nitritalea halalkaliphila (species)

A0A6B8N021
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Klebsiella (genus)

 62%|████████████████████████████████████████████████████████████████████████████████████▎                                                    | 788/1281 [02:27<01:31,  5.38it/s]

A0A7G5DPV1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus)

A0A2G5RQK9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Anoxybacillus (genus)

 62%|████████████████████████████████████████████████████████████████████████████████████▍                                                    | 790/1281 [02:27<01:31,  5.38it/s]

A0A5M4B0G1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Prolixibacter (genus)

A0A6S5K4J1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

 62%|████████████████████████████████████████████████████████████████████████████████████▋                                                    | 792/1281 [02:27<01:30,  5.38it/s]

C1D4X0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Aquaspirillaceae (family), Laribacter (genus), Laribacter hongkongensis (species)

A1SVA8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Psychromonadaceae (family), Psychromonas (genus), Psychromonas ingrahamii (species)

 62%|████████████████████████████████████████████████████████████████████████████████████▉                                                    | 794/1281 [02:28<01:30,  5.37it/s]

H1YF74
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Sphingobacteriia (class), Sphingobacteriales (order), Sphingobacteriaceae (family), Mucilaginibacter (genus), Mucilaginibacter paludis (species)

A0A8B4RWH8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

 62%|█████████████████████████████████████████████████████████████████████████████████████▏                                                   | 796/1281 [02:28<01:30,  5.35it/s]

A0A0A0D6K5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Rhodospirillaceae (family), Inquilinus (genus), Inquilinus limosus (species)

A0A0A2BBY0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 62%|█████████████████████████████████████████████████████████████████████████████████████▎                                                   | 798/1281 [02:29<01:30,  5.34it/s]

A0A089ZBW5
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobacterium (genus)

A0A068TC78
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus), Neorhizobium galegae (species), Neorhizobium galegae bv. officinalis (no rank)

 62%|█████████████████████████████████████████████████████████████████████████████████████▌                                                   | 800/1281 [02:29<01:29,  5.35it/s]

Q46G49
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

A1CQ21
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus clavatus (species)

 63%|█████████████████████████████████████████████████████████████████████████████████████▊                                                   | 802/1281 [02:29<01:29,  5.34it/s]

A0A1G6ABX1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Kaistiaceae (family), Bauldia (genus)

E1SLM7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Ferrimonadaceae (family), Ferrimonas (genus), Ferrimonas balearica (species)

 63%|█████████████████████████████████████████████████████████████████████████████████████▉                                                   | 804/1281 [02:30<01:29,  5.34it/s]

K5CFE5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

Q2YLQ6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Brucellaceae (family), Brucella/Ochrobactrum group (no rank), Brucella (genus), Brucella abortus (species)

 63%|██████████████████████████████████████████████████████████████████████████████████████▏                                                  | 806/1281 [02:30<01:28,  5.37it/s]

Q0G2V0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Fulvimarina (genus), Fulvimarina pelagi (species)

A4ABK3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Cellvibrionales (order), Halieaceae (family), Congregibacter (genus), Congregibacter litoralis (species)

 63%|██████████████████████████████████████████████████████████████████████████████████████▍                                                  | 808/1281 [02:30<01:28,  5.37it/s]

A0A9Q5QVI9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Cylindrospermopsis (genus), Cylindrospermopsis raciborskii (species)

A0A4Q7Y9I7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Geodermatophilales (order), Geodermatophilaceae (family), Blastococcus (genus)

 63%|██████████████████████████████████████████████████████████████████████████████████████▋                                                  | 810/1281 [02:31<01:27,  5.36it/s]

A9HMD6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconacetobacter (genus), Gluconacetobacter diazotrophicus (species)

K9YN27
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Geminocystaceae (family), Cyanobacterium (genus), Cyanobacterium stanieri (species)

 63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 812/1281 [02:31<01:27,  5.38it/s]

Q9UBD6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Sarcopterygii (superclass), Dipnotetrapodomorpha (clade), Tetrapoda (clade), Amniota (clade), Mammalia (class), Theria (clade), Eutheria (clade), Boreoeutheria (clade), Euarchontoglires (superorder), Primates (order), Haplorrhini (suborder), Simiiformes (infraorder), Catarrhini (parvorder), Hominoidea (superfamily), Hominidae (family), Homininae (subfamily), Homo (genus)

D9SI59
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Gallionellaceae (family), Gallionella (genus), Gallionella capsiferriformans (species)

 64%|███████████████████████████████████████████████████████████████████████████████████████                                                  | 814/1281 [02:32<01:26,  5.37it/s]

Q8I0L6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Evosea (phylum), Eumycetozoa (class), Dictyostelia (clade), Dictyosteliales (order), Dictyosteliaceae (family), Dictyostelium (genus)

A0A142VAD6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Dehalococcoidia (class), Dehalococcoidales (order), Dehalococcoidaceae (family), Dehalococcoides (genus)

 64%|███████████████████████████████████████████████████████████████████████████████████████▎                                                 | 816/1281 [02:32<01:26,  5.37it/s]

G3IYW0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus), Methylobacter tundripaludum (species)

A0A062IU58
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 64%|███████████████████████████████████████████████████████████████████████████████████████▍                                                 | 818/1281 [02:32<01:26,  5.36it/s]

R1D1H4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Haptista (clade), Haptophyta (phylum), Prymnesiophyceae (clade), Isochrysidales (order), Noelaerhabdaceae (family), Emiliania (genus)

A0A366XFS8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Phaeobacter (genus)

 64%|███████████████████████████████████████████████████████████████████████████████████████▋                                                 | 820/1281 [02:33<01:26,  5.35it/s]

A0A7S4GNF3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Oxyrrhinales (order), Oxyrrhinaceae (family), Oxyrrhis (genus)

F0J6E8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acidiphilium (genus), Acidiphilium multivorum (species)

 64%|███████████████████████████████████████████████████████████████████████████████████████▉                                                 | 822/1281 [02:33<01:26,  5.33it/s]

A0A7U4DN04
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfobulbaceae (family), Desulfobulbus (genus), Desulfobulbus propionicus (species)

V4RHR4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Tepidamorphaceae (family), Lutibaculum (genus), Lutibaculum baratangense (species)

 64%|████████████████████████████████████████████████████████████████████████████████████████                                                 | 824/1281 [02:33<01:25,  5.35it/s]

F7ZJM0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Roseobacter (genus), Roseobacter litoralis (species)

A0A2S5XAB8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 64%|████████████████████████████████████████████████████████████████████████████████████████▎                                                | 826/1281 [02:34<01:24,  5.36it/s]

U5C4L4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cytophagaceae (family), Rhodonellum (genus), Rhodonellum psychrophilum (species)

Q21J04
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Cellvibrionales (order), Cellvibrionaceae (family), Saccharophagus (genus), Saccharophagus degradans (species)

 65%|████████████████████████████████████████████████████████████████████████████████████████▌                                                | 828/1281 [02:34<01:24,  5.35it/s]

A0A142NNN1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Brevibacteriaceae (family), Brevibacterium (genus)

H1Y7T6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Sphingobacteriia (class), Sphingobacteriales (order), Sphingobacteriaceae (family), Mucilaginibacter (genus), Mucilaginibacter paludis (species)

 65%|████████████████████████████████████████████████████████████████████████████████████████▊                                                | 830/1281 [02:35<01:23,  5.38it/s]

F5R974
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Sterolibacteriaceae (family), Methyloversatilis (genus), Methyloversatilis universalis (species)

B0DU91
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

 65%|████████████████████████████████████████████████████████████████████████████████████████▉                                                | 832/1281 [02:35<01:23,  5.36it/s]

A2BP62
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A7HSN9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Parvibaculaceae (family), Parvibaculum (genus), Parvibaculum lavamentivorans (species)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▏                                               | 834/1281 [02:35<01:23,  5.39it/s]

A0A377I7W9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Avibacterium (genus)

D2RU19
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Natrialbaceae (family), Haloterrigena (genus), Haloterrigena turkmenica (species)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▍                                               | 836/1281 [02:36<01:22,  5.39it/s]

G7WJN0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

E2SD33
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Propionibacteriales (order), Nocardioidaceae (family), Aeromicrobium (genus), Aeromicrobium marinum (species)

 65%|█████████████████████████████████████████████████████████████████████████████████████████▌                                               | 838/1281 [02:36<01:22,  5.39it/s]

A0A0D7F2Y9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus)

A0AA92EGF5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Ralstonia (genus), Ralstonia solanacearum species complex (no rank)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▊                                               | 840/1281 [02:36<01:21,  5.41it/s]

A0A9E9LXV9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Oxalobacter (genus)

A4BEP1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Saccharospirillaceae (family), Reinekea (genus), Reinekea blandensis (species)

 66%|██████████████████████████████████████████████████████████████████████████████████████████                                               | 842/1281 [02:37<01:21,  5.39it/s]

A0A0E3WZH5
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

F7ZEU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Roseobacter (genus), Roseobacter litoralis (species)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▎                                              | 844/1281 [02:37<01:21,  5.39it/s]

A5E3X2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Candida/Lodderomyces clade (clade), Lodderomyces (genus), Lodderomyces elongisporus (species)

A0A0A3XTJ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Bradyrhizobium (genus)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▍                                              | 846/1281 [02:37<01:20,  5.38it/s]

A0A830ZZN8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Erwiniaceae (family), Erwinia (genus), Erwinia amylovora (species)

A0A1S8D478
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Roseomonas (genus)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▋                                              | 848/1281 [02:38<01:20,  5.36it/s]

J7IVQ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus meridiei (species)

A0A2U1SS17
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Methylocystaceae (family), Methylosinus (genus)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▉                                              | 850/1281 [02:38<01:20,  5.35it/s]

S3K1S2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Cedecea (genus), Cedecea davisae (species)

C6XKC2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomonadales (order), Hyphomonadaceae (family), Hirschia (genus), Hirschia baltica (species)

 67%|███████████████████████████████████████████████████████████████████████████████████████████                                              | 852/1281 [02:39<01:20,  5.34it/s]

A0A2S7YIM5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus)

K2IMJ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Gallaecimonadaceae (family), Gallaecimonas (genus), Gallaecimonas xiamenensis (species)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 854/1281 [02:39<01:20,  5.32it/s]

Q5P1S8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Rhodocyclaceae (family), Aromatoleum (genus), Aromatoleum aromaticum (species)

A0A7T5BFQ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▌                                             | 856/1281 [02:39<01:19,  5.31it/s]

A0A556SRH6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

A8P923
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Psathyrellaceae (family), Coprinopsis (genus), Coprinopsis cinerea (species)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▊                                             | 858/1281 [02:40<01:19,  5.32it/s]

A0A7G5DKA9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pseudomonadales (order), Pseudomonadaceae (family), Pseudomonas (genus)

L8JUH3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Fulvivirgaceae (family), Fulvivirga (genus), Fulvivirga imtechensis (species)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▉                                             | 860/1281 [02:40<01:18,  5.34it/s]

A0A0D2LEF5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Strophariaceae (family), Hypholoma (genus), Hypholoma sublateritium (species)

A0A258FTB0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 862/1281 [02:40<01:18,  5.36it/s]

A0A5P9P1L2
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Natrialbaceae (family), Natronorubrum (genus)

M8E0R3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Anoxybacillus (genus), Anoxybacillus flavithermus (species)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 864/1281 [02:41<01:18,  5.34it/s]

A0A6J5IRX5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank)

W5WIX6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Kutzneria (genus), Kutzneria albida (species)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 866/1281 [02:41<01:17,  5.33it/s]

Q82X47
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Nitrosomonadaceae (family), Nitrosomonas (genus), Nitrosomonas europaea (species)

I4DBY0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus acidiphilus (species)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 868/1281 [02:42<01:17,  5.34it/s]

A0A6F8TLE9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank)

A0A1G7UZX2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Rhodocyclaceae (family), Propionivibrio (genus)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████                                            | 870/1281 [02:42<01:16,  5.35it/s]

A0A6P4JM51
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Brachycera (suborder), Muscomorpha (infraorder), Eremoneura (clade), Cyclorrhapha (clade), Schizophora (no rank), Acalyptratae (no rank), Ephydroidea (superfamily), Drosophilidae (family), Drosophilinae (subfamily), Drosophilini (tribe), Drosophila (genus), Sophophora (subgenus), melanogaster group (no rank), montium subgroup (no rank)

G0J614
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Cyclobacterium (genus), Cyclobacterium marinum (species)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 872/1281 [02:42<01:15,  5.39it/s]

U2WTW8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Geobacillus (genus), Geobacillus thermoleovorans group (no rank), Geobacillus kaustophilus (species)

A0A642KQG8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Bacteroidaceae (family), Bacteroides (genus)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 874/1281 [02:43<01:15,  5.37it/s]

Q1AUG3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Rubrobacteria (class), Rubrobacterales (order), Rubrobacteraceae (family), Rubrobacter (genus), Rubrobacter xylanophilus (species)

A0A6G9Y3Q0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Nocardiaceae (family), Nocardia (genus)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 876/1281 [02:43<01:15,  5.36it/s]

B8J5X4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Myxococcia (class), Myxococcales (order), Cystobacterineae (suborder), Anaeromyxobacteraceae (family), Anaeromyxobacter (genus), Anaeromyxobacter dehalogenans (species)

M7NFH3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Planococcaceae (family), Bhargavaea (genus), Bhargavaea cecembensis (species)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 878/1281 [02:43<01:15,  5.36it/s]

A0A0E3R6S1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanosarcinales (order), Methanosarcinaceae (family), Methanosarcina (genus), Methanosarcina barkeri (species)

Q2IHY5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Myxococcota (phylum), Myxococcia (class), Myxococcales (order), Cystobacterineae (suborder), Anaeromyxobacteraceae (family), Anaeromyxobacter (genus), Anaeromyxobacter dehalogenans (species)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████                                           | 880/1281 [02:44<01:15,  5.34it/s]

A7I8Z2
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanoregulaceae (family), Methanoregula (genus), Methanoregula boonei (species)

L1IYP4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 882/1281 [02:44<01:14,  5.34it/s]

B4HDZ9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Hexapoda (subphylum), Insecta (class), Dicondylia (clade), Pterygota (subclass), Neoptera (infraclass), Endopterygota (cohort), Diptera (order), Brachycera (suborder), Muscomorpha (infraorder), Eremoneura (clade), Cyclorrhapha (clade), Schizophora (no rank), Acalyptratae (no rank), Ephydroidea (superfamily), Drosophilidae (family), Drosophilinae (subfamily), Drosophilini (tribe), Drosophila (genus), Sophophora (subgenus), melanogaster group (no rank), melanogaster subgroup (no rank)

A0A366WYI9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Phaeobacter (genus)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 884/1281 [02:45<01:14,  5.33it/s]

E4TJ50
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Calditerrivibrionaceae (family), Calditerrivibrio (genus), Calditerrivibrio nitroreducens (species)

A0A7S0ILH2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 886/1281 [02:45<01:13,  5.35it/s]

A4BAE1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Saccharospirillaceae (family), Reinekea (genus), Reinekea blandensis (species)

B3QRJ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Chlorobaculum (genus), Chlorobaculum parvum (species)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 888/1281 [02:45<01:13,  5.37it/s]

A0A5C5BWI6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Eggerthella (genus)

Q7NQY2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Chromobacteriaceae (family), Chromobacterium (genus), Chromobacterium violaceum (species)

 69%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 890/1281 [02:46<01:12,  5.37it/s]

A0A091AXI3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Arenimonas (genus), Arenimonas oryziterrae (species)

Q1QSQ2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Halomonadaceae (family), Chromohalobacter (genus), Chromohalobacter salexigens (species)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 892/1281 [02:46<01:12,  5.40it/s]

R4FZE3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Anoxybacillus (genus), Anoxybacillus flavithermus (species)

A0A2N0MZ27
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Ewingella (genus)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 894/1281 [02:46<01:11,  5.40it/s]

A9BTK1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Delftia (genus), Delftia acidovorans (species)

A0A242NIL1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 896/1281 [02:47<01:11,  5.39it/s]

G0LFE3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloquadratum (genus), Haloquadratum walsbyi (species)

A0A1B9NQ91
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████                                         | 898/1281 [02:47<01:11,  5.38it/s]

A0A5M5PZE2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Bacteroidaceae (family), Bacteroides (genus)

A0A0D2NYP3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Strophariaceae (family), Hypholoma (genus), Hypholoma sublateritium (species)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 900/1281 [02:48<01:11,  5.36it/s]

D9QPE5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Brevundimonas (genus), Brevundimonas subvibrioides (species)

I5B3H0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobacter (genus), Desulfobacter postgatei (species)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 902/1281 [02:48<01:10,  5.35it/s]

L1IYW7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Cryptophyceae (class), Pyrenomonadales (order), Geminigeraceae (family), Guillardia (genus), Guillardia theta (species)

C6WEW7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Actinosynnema (genus), Actinosynnema mirum (species)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 904/1281 [02:48<01:10,  5.35it/s]

B7FW68
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Bacillariophyta (phylum), Bacillariophyceae (class), Bacillariophycidae (clade), Naviculales (order), Phaeodactylaceae (family), Phaeodactylum (genus), Phaeodactylum tricornutum (species)

F4GED5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Alicycliphilus (genus), Alicycliphilus denitrificans (species)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 906/1281 [02:49<01:10,  5.35it/s]

A0A4R8GSH7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Halanaerobiales (order), Halobacteroidaceae (family), Orenia (genus)

A0A1W2H3F0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Aquiflexum (genus), Aquiflexum balticum (species)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████                                        | 908/1281 [02:49<01:09,  5.35it/s]

A0A3E2T713
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Oscillospiraceae (family), Faecalibacterium (genus)

A0A0H3KTD3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Erwiniaceae (family), Pantoea (genus), Pantoea ananas (species)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 910/1281 [02:49<01:09,  5.37it/s]

A0A1Y4LM49
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Butyricicoccaceae (family), Butyricicoccus (genus)

G2PRJ6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Flagellimonas (genus), Flagellimonas ruestringensis (species)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 912/1281 [02:50<01:08,  5.37it/s]

A0A0X8X7Y7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Ectothiorhodospiraceae (family), Halorhodospira (genus)

K8EJ02
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Carnobacteriaceae (family), Carnobacterium (genus), Carnobacterium maltaromaticum (species)

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 914/1281 [02:50<01:08,  5.40it/s]

A0A1L3F1X5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Bradyrhizobium (genus)

G8TK77
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Chitinophagia (class), Chitinophagales (order), Chitinophagaceae (family), Niastella (genus), Niastella koreensis (species)

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 916/1281 [02:51<01:07,  5.37it/s]

A0A855F5Y8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Klebsiella/Raoultella group (no rank), Raoultella (genus)

A0A975BTN0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfococcaceae (family), Desulfonema (genus)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 918/1281 [02:51<01:07,  5.37it/s]

A0A562RGZ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobotulus (genus)

G5EB09
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Nidulantes (subgenus), Emericella nidulans (species)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 920/1281 [02:51<01:07,  5.37it/s]

A0A833LX85
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus)

U1H1F7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Pasteurellales (order), Pasteurellaceae (family), Gallibacterium (genus), Gallibacterium anatis (species)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 922/1281 [02:52<01:07,  5.35it/s]

K8W1E2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus), Providencia burhodogranariea (species)

E3HJW8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Achromobacter (genus), Alcaligenes xylosoxydans xylosoxydans (species)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 924/1281 [02:52<01:06,  5.35it/s]

Q7SEH0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Sordariomycetidae (subclass), Sordariales (order), Sordariaceae (family), Neurospora (genus), Neurospora crassa (species)

Q47X17
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Colwelliaceae (family), Colwellia (genus), Colwellia psychrerythraea (species)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████                                      | 926/1281 [02:52<01:06,  5.35it/s]

B0DXT9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

A0A3G9G2C9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Asticcacaulis (genus)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 928/1281 [02:53<01:05,  5.36it/s]

Q95P70
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Protostomia (clade), Ecdysozoa (clade), Panarthropoda (clade), Arthropoda (phylum), Mandibulata (clade), Pancrustacea (clade), Crustacea (subphylum), Multicrustacea (superclass), Malacostraca (class), Eumalacostraca (subclass), Eucarida (superorder), Decapoda (order), Pleocyemata (suborder), Brachyura (infraorder), Eubrachyura (no rank), Heterotremata (no rank), Portunoidea (superfamily), Carcinidae (family), Carcinus (genus)

A0A837C6X5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Bradyrhizobium (genus), Bradyrhizobium diazoefficiens (species)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 930/1281 [02:53<01:05,  5.34it/s]

Q89WR5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Bradyrhizobium (genus), Bradyrhizobium diazoefficiens (species)

A6DUG4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Lentisphaerota (phylum), Lentisphaeria (class), Lentisphaerales (order), Lentisphaeraceae (family), Lentisphaera (genus), Lentisphaera araneosa (species)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 932/1281 [02:54<01:05,  5.35it/s]

D7UQE2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Cephalochordata (subphylum), Leptocardii (class), Amphioxiformes (order), Branchiostomatidae (family), Branchiostoma (genus)

A0A2I1M481
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Bifidobacteriales (order), Bifidobacteriaceae (family), Alloscardovia (genus)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 934/1281 [02:54<01:04,  5.38it/s]

A0A0T7GZ59
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus), Neorhizobium galegae (species)

O66395
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Xanthobacteraceae (family), Azorhizobium (genus)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 936/1281 [02:54<01:04,  5.36it/s]

J3EXK0
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Halogranum (genus), Halogranum rubrum (species)

A0A1B9MYL7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 938/1281 [02:55<01:04,  5.34it/s]

K9U8C7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Chroococcidiopsidales (order), Chroococcidiopsidaceae (family), Chroococcidiopsis (genus), Chroococcidiopsis thermalis (species)

E2SD44
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Propionibacteriales (order), Nocardioidaceae (family), Aeromicrobium (genus), Aeromicrobium marinum (species)

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 940/1281 [02:55<01:03,  5.33it/s]

H6LKH6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Acetobacterium (genus), Acetobacterium woodii (species)

Q605Y6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus), Methylococcus capsulatus (species)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 942/1281 [02:55<01:03,  5.32it/s]

A0A9Q9D9I3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Sinorhizobium/Ensifer group (no rank), Ensifer (genus)

A0A6N2TIA4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Anaerostipes (genus)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 944/1281 [02:56<01:03,  5.30it/s]

A0A1E3PQH0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Dipodascomycetes (class), Dipodascales (order), Dipodascales incertae sedis (no rank), Nadsonia (genus), Nadsonia fulvescens (species), Nadsonia fulvescens var. elongata (varietas)

A4CMI3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Robiginitalea (genus), Robiginitalea biformata (species)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 946/1281 [02:56<01:02,  5.32it/s]

Q1K0H9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Desulfuromonadaceae (family), Desulfuromonas (genus), Desulfuromonas acetoxidans (species)

A0A0S6UEK9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus), Moorella thermoacetica (species)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 948/1281 [02:57<01:02,  5.32it/s]

A0A0H3LUA3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Bordetella (genus), Bordetella bronchiseptica (species)

B9LU00
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Halorubrum (genus), Halorubrum lacusprofundi (species)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 950/1281 [02:57<01:02,  5.32it/s]

A9BIZ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermotogota (phylum), Thermotogae (class), Petrotogales (order), Petrotogaceae (family), Petrotoga (genus), Petrotoga mobilis (species)

A0A7H8UK07
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 952/1281 [02:57<01:01,  5.33it/s]

E3H8C9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Fusobacteriota (phylum), Fusobacteriia (class), Fusobacteriales (order), Fusobacteriaceae (family), Ilyobacter (genus), Ilyobacter polytropus (species)

M2A398
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula europaea (species)

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 954/1281 [02:58<01:01,  5.34it/s]

Q1QS12
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Nitrobacter (genus), Nitrobacter hamburgensis (species)

G0VI62
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Saccharomycetes (class), Saccharomycetales (order), Saccharomycetaceae (family), Naumovozyma (genus)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 956/1281 [02:58<01:00,  5.34it/s]

A0A1Z3MS36
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank), unclassified Enterobacter cloacae complex (no rank)

A0A0B5FNH4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Geoalkalibacteraceae (family), Geoalkalibacter (genus)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 958/1281 [02:58<01:00,  5.33it/s]

D9SI36
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Nitrosomonadales (order), Gallionellaceae (family), Gallionella (genus), Gallionella capsiferriformans (species)

A0A410JZR4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Geovibrionaceae (family), Geovibrio (genus)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 960/1281 [02:59<01:00,  5.35it/s]

F7ZJZ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Roseobacter (genus), Roseobacter litoralis (species)

F0ZCX7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Amoebozoa (clade), Evosea (phylum), Eumycetozoa (class), Dictyostelia (clade), Dictyosteliales (order), Dictyosteliaceae (family), Dictyostelium (genus)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 962/1281 [02:59<00:59,  5.33it/s]

W0DZX1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Marichromatium (genus), Marichromatium purpuratum (species)

A0A4R3ZZ35
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Mycobacteriales (order), Dietziaceae (family), Dietzia (genus)

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 964/1281 [03:00<00:58,  5.37it/s]

A0A317G0I6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Butyrivibrio (genus)

Q0ARJ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Maricaulales (order), Maricaulaceae (family), Maricaulis (genus), Maricaulis maris (species)

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 966/1281 [03:00<00:58,  5.36it/s]

A7I8Z4
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanoregulaceae (family), Methanoregula (genus), Methanoregula boonei (species)

T2KJ59
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Formosa (genus), Formosa agariphila (species)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 968/1281 [03:00<00:58,  5.36it/s]

I3C0V3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Galbibacter (genus), Galbibacter orientalis (species)

E3H8A6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Fusobacteriota (phylum), Fusobacteriia (class), Fusobacteriales (order), Fusobacteriaceae (family), Ilyobacter (genus), Ilyobacter polytropus (species)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 970/1281 [03:01<00:57,  5.37it/s]

B2IJT1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Beijerinckiaceae (family), Beijerinckia (genus), Beijerinckia indica (species), Beijerinckia indica subsp. indica (subspecies)

A0A2G6JLT9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Neptuniibacter (genus)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 972/1281 [03:01<00:57,  5.35it/s]

A3ZZL7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus), Blastopirellula marina (species)

A0A2T0XPP2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Marinilabiliaceae (family), Marinilabilia (genus)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 974/1281 [03:01<00:57,  5.37it/s]

Q31CR9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A0A1R1IDV3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Azonexaceae (family), Azonexus (genus)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 976/1281 [03:02<00:56,  5.36it/s]

K2JVF8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Oceanibaculaceae (family), Oceanibaculum (genus), Oceanibaculum indicum (species)

V5BYZ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methyloglobulus (genus), Methyloglobulus morosus (species)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 978/1281 [03:02<00:56,  5.36it/s]

D8J4C6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Halococcaceae (family), Halalkalicoccus (genus), Halalkalicoccus jeotgali (species)

D4H5F9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Geovibrionaceae (family), Denitrovibrio (genus), Denitrovibrio acetiphilus (species)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 980/1281 [03:03<00:56,  5.35it/s]

K9ZG59
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Nostocaceae (family), Anabaena (genus), Anabaena cylindrica (species)

A0AA86YS65
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus), Providencia stuartii (species)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 982/1281 [03:03<00:56,  5.32it/s]

Q608B6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus), Methylococcus capsulatus (species)

A0A562BXM4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus), unclassified Luteimonas (no rank)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 984/1281 [03:03<00:55,  5.32it/s]

A0A401WXG0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus), Acetobacter pasteurianus (species)

A0A857DMN9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Dehalobacter (genus)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 986/1281 [03:04<00:55,  5.33it/s]

A0A1X6N3Q5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetes incertae sedis (no rank), Polyporales (order), Postiaceae (family), Postia (genus), Postia placenta (species)

A0A173R3X4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Anaerostipes (genus)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 988/1281 [03:04<00:54,  5.37it/s]

Q63EK5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Bacillus (genus), Bacillus cereus group (no rank), Bacillus cereus (species)

K9ZLY2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Nostocaceae (family), Anabaena (genus), Anabaena cylindrica (species)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 990/1281 [03:04<00:54,  5.36it/s]

A0A533I6R2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Paracoccaceae (family), Paracoccus (genus)

I0WJ97
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Imtechella (genus), Imtechella halotolerans (species)

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 992/1281 [03:05<00:54,  5.34it/s]

K0N2R5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobacula (genus), Desulfobacula toluolica (species)

M0J579
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloferax (genus), Haloferax mediterranei (species)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 994/1281 [03:05<00:53,  5.33it/s]

B8GGC1
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanoregulaceae (family), Methanosphaerula (genus), Methanosphaerula palustris (species)

A0A6H9GFU4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 996/1281 [03:06<00:53,  5.37it/s]

C6CBB1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Musicola (genus), Musicola paradisiaca (species)

A0A510HHK8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Rubrobacteria (class), Rubrobacterales (order), Rubrobacteraceae (family), Rubrobacter (genus)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 998/1281 [03:06<00:52,  5.36it/s]

A0A1B9MBX6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

A0A9Y2AG30
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Micrococcaceae (family), Kocuria (genus), unclassified Kocuria (no rank)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 1000/1281 [03:06<00:52,  5.35it/s]

E8RSE4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Caulobacterales (order), Caulobacteraceae (family), Asticcacaulis (genus), Asticcacaulis excentricus (species)

F2B2B8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 1002/1281 [03:07<00:52,  5.34it/s]

Q7UYZ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

I1YJH7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Thiotrichales (order), Piscirickettsiaceae (family), Methylophaga (genus)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 1004/1281 [03:07<00:51,  5.35it/s]

A0A853MG28
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Aphanizomenonaceae (family), Cylindrospermopsis (genus), Cylindrospermopsis raciborskii (species)

A0A0L0STS6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Fungi incertae sedis (no rank), Blastocladiomycota (phylum), Blastocladiomycetes (class), Blastocladiales (order), Blastocladiaceae (family), Allomyces (genus), Allomyces macrogynus (species)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 1006/1281 [03:07<00:51,  5.35it/s]

A0A251XU71
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

Q60BI2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus), Methylococcus capsulatus (species)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 1008/1281 [03:08<00:51,  5.34it/s]

A0A829X098
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Gluconobacter (genus), Gluconobacter oxydans (species)

F3KUN4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Hylemonella (genus), Hylemonella gracilis (species)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 1010/1281 [03:08<00:50,  5.33it/s]

Q60C43
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylococcus (genus), Methylococcus capsulatus (species)

A0A0T7FAP8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus), Neorhizobium galegae (species)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 1012/1281 [03:09<00:50,  5.31it/s]

A0A3E2TW06
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Oscillospiraceae (family), Faecalibacterium (genus)

W0E077
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Marichromatium (genus), Marichromatium purpuratum (species)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 1014/1281 [03:09<00:50,  5.33it/s]

A0KPE9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Aeromonadales (order), Aeromonadaceae (family), Aeromonas (genus), Aeromonas hydrophila (species), Aeromonas hydrophila subsp. hydrophila (subspecies)

R7PZ71
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobrevibacter (genus), Methanobrevibacter smithii (species)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 1016/1281 [03:09<00:49,  5.32it/s]

A0A0A1ZMZ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

A0AA40J491
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Pectobacterium (genus), Pectobacterium carotovorum (species)

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 1018/1281 [03:10<00:49,  5.32it/s]

D3S2L0
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Archaeoglobi (class), Archaeoglobales (order), Archaeoglobaceae (family), Ferroglobus (genus), Ferroglobus placidus (species)

A0A373FQ71
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 1020/1281 [03:10<00:49,  5.33it/s]

A0A0A2C6L1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

Q7W7D3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Bordetella (genus), Bordetella parapertussis (species)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 1022/1281 [03:10<00:48,  5.35it/s]

A0A165K0X5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Rossellomorea (genus)

A0A2S5X482
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 1024/1281 [03:11<00:47,  5.36it/s]

R9GM11
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Sphingobacteriia (class), Sphingobacteriales (order), Sphingobacteriaceae (family), Arcticibacter (genus), Arcticibacter svalbardensis (species)

Q0G0A3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Aurantimonadaceae (family), Fulvimarina (genus), Fulvimarina pelagi (species)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 1026/1281 [03:11<00:47,  5.35it/s]

D4GLQ6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Erwiniaceae (family), Pantoea (genus), Pantoea ananas (species)

E7RJZ0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Planococcaceae (family), Planococcus (genus), Planococcus donghaensis (species)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 1028/1281 [03:12<00:47,  5.34it/s]

F8IJE0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Alicyclobacillaceae (family), Alicyclobacillus (genus), Alicyclobacillus acidocaldarius (species), Alicyclobacillus acidocaldarius subsp. acidocaldarius (subspecies)

A0A1V2XMU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 1030/1281 [03:12<00:46,  5.34it/s]

Q7TNN9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Sarcopterygii (superclass), Dipnotetrapodomorpha (clade), Tetrapoda (clade), Amniota (clade), Mammalia (class), Theria (clade), Eutheria (clade), Boreoeutheria (clade), Euarchontoglires (superorder), Glires (clade), Rodentia (order), Myomorpha (suborder), Muroidea (clade), Muridae (family), Murinae (subfamily), Rattus (genus)

A0A1G5RZU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Peptostreptococcales (order), Acidaminobacteraceae (family), Acidaminobacter (genus), Acidaminobacter hydrogenoformans (species)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 1032/1281 [03:12<00:46,  5.34it/s]

A0A2N6K4Y5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Nostocales (order), Hapalosiphonaceae (family), Fischerella (genus), Fischerella muscicola (species)

B0SLB7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptospira (genus), Leptospira biflexa (species), Leptospira biflexa serovar Patoc (no rank)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1034/1281 [03:13<00:46,  5.37it/s]

A0A251YFS0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

B9WDK0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Candida/Lodderomyces clade (clade), Candida (genus), Candida dubliniensis (species)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 1036/1281 [03:13<00:45,  5.40it/s]

Q7N0M6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Photorhabdus (genus), Photorhabdus laumondii (species), Photorhabdus laumondii subsp. laumondii (subspecies)

A0A0M2LU39
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Sphingomonadales (order), Sphingomonadaceae (family), Sphingomonas (genus), unclassified Sphingomonas (no rank)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 1038/1281 [03:13<00:45,  5.39it/s]

F4B548
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Thermoproteota (phylum), Thermoprotei (class), Sulfolobales (order), Sulfolobaceae (family), Acidianus (genus), Acidianus hospitalis (species)

D6Z5V9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfobulbaceae (family), Desulfurivibrio (genus), Desulfurivibrio alkaliphilus (species)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 1040/1281 [03:14<00:44,  5.36it/s]

A0A4R2M206
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sphaerotilaceae (family), Rubrivivax (genus)

A0A1E2SKM1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Leifsonia (genus), Leifsonia xyli (species)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 1042/1281 [03:14<00:44,  5.36it/s]

A0A127JTU2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Ramlibacter (genus)

A0A212AV03
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Paracoccaceae (family), Haematobacter (genus)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 1044/1281 [03:15<00:44,  5.35it/s]

G4QHD2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Glaciecola (genus), Glaciecola nitratireducens (species)

A0A021VMC6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Cellulomonadaceae (family), Actinotalea (genus), Actinotalea ferrariae (species)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 1046/1281 [03:15<00:44,  5.32it/s]

A0A2J7TJ33
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Beijerinckiaceae (family), Methylocella (genus)

G7WDB5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Desulfitobacteriaceae (family), Desulfosporosinus (genus), Desulfosporosinus orientis (species)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 1048/1281 [03:15<00:43,  5.34it/s]

Q6BK68
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Debaryomyces (genus), Debaryomyces hansenii (species)

Q1K3N8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfuromonadia (class), Desulfuromonadales (order), Desulfuromonadaceae (family), Desulfuromonas (genus), Desulfuromonas acetoxidans (species)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 1050/1281 [03:16<00:43,  5.36it/s]

A0AA91Q161
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Metschnikowiaceae (family), Clavispora (genus)

A0NJ07
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Lactobacillales (order), Lactobacillaceae (family), Oenococcus (genus), Oenococcus oeni (species)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 1052/1281 [03:16<00:42,  5.35it/s]

A0A316BQ38
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Phyllobacteriaceae (family), Pseudaminobacter (genus)

A0A377PLP5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 1054/1281 [03:16<00:42,  5.38it/s]

W7QGM4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Catenovulum (genus), Catenovulum agarivorans (species)

A0A015YIP3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Bacteroidales (order), Bacteroidaceae (family), Bacteroides (genus), Bacteroides fragilis (species)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 1056/1281 [03:17<00:41,  5.38it/s]

A0A060UWC8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

A0A1I4ZIZ6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Chitinibacteraceae (family), Formivibrio (genus)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 1058/1281 [03:17<00:41,  5.38it/s]

A0A264VQM8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus)

A9AUR8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Chloroflexia (class), Herpetosiphonales (order), Herpetosiphonaceae (family), Herpetosiphon (genus), Herpetosiphon aurantiacus (species)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 1060/1281 [03:17<00:40,  5.41it/s]

A0A1W5PRD1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Cyclostomata (clade), Myxini (class), Myxiniformes (order), Myxinidae (family), Eptatretinae (subfamily), Eptatretus (genus)

A0A0E3BR91
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 1062/1281 [03:18<00:40,  5.40it/s]

A0A1B0ZRL8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Phaeobacter (genus)

B9ACS5
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanobacteria (class), Methanobacteriales (order), Methanobacteriaceae (family), Methanobrevibacter (genus), Methanobrevibacter smithii (species)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 1064/1281 [03:18<00:40,  5.36it/s]

Q92BJ7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Listeriaceae (family), Listeria (genus), Listeria innocua (species)

F2JTN3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Marinomonas (genus), Marinomonas mediterranea (species)

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 1066/1281 [03:19<00:40,  5.35it/s]

A1AVV2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Gammaproteobacteria incertae sedis (no rank), sulfur-oxidizing symbionts (clade), Candidatus Ruthturnera (genus), Candidatus Ruthturnera calyptogenae (species)

D2Q0J8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Propionibacteriales (order), Kribbellaceae (family), Kribbella (genus), Kribbella flavida (species)

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 1068/1281 [03:19<00:40,  5.31it/s]

A0A3S9N9F3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Burkholderiaceae (family), Burkholderia (genus), Burkholderia cepacia complex (no rank)

A8ZQD5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Acaryochloridales (order), Acaryochloridaceae (family), Acaryochloris (genus), Acaryochloris marina (species)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 1070/1281 [03:19<00:39,  5.31it/s]

C3X831
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Oxalobacter (genus), Oxalobacter formigenes (species)

A0A1M6BPM0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfatibacillaceae (family), Desulfatibacillum (genus), Desulfatibacillum alkenivorans (species)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1072/1281 [03:20<00:39,  5.31it/s]

A0A8F5VN39
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanospirillaceae (family), Methanospirillum (genus)

A0A1E5C7W4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Enterovibrio (genus), Enterovibrio norvegicus (species)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 1074/1281 [03:20<00:38,  5.33it/s]

A0A2S5WV24
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

A0A833GZR2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 1076/1281 [03:20<00:38,  5.36it/s]

C7M2A9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Acidimicrobiia (class), Acidimicrobiales (order), Acidimicrobiaceae (family), Acidimicrobium (genus), Acidimicrobium ferrooxidans (species)

A6W7U2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Kineosporiales (order), Kineosporiaceae (family), Kineococcus (genus), Kineococcus radiotolerans (species)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 1078/1281 [03:21<00:37,  5.34it/s]

W0JIB3
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Natrialbaceae (family), Halostagnicola (genus), Halostagnicola larsenii (species)

Q07UM3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 1080/1281 [03:21<00:37,  5.33it/s]

A0A066ZRQ5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Thiotrichales (order), Piscirickettsiaceae (family), Hydrogenovibrio (genus)

S0G181
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfotignum (genus), Desulfotignum phosphitoxidans (species)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 1082/1281 [03:22<00:37,  5.35it/s]

D3PAH1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Deferribacteraceae (family), Deferribacter (genus), Deferribacter desulfuricans (species)

Q4WHC6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus fumigatus (species)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 1084/1281 [03:22<00:36,  5.33it/s]

A0AA94HTL8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Desulfovibrio (genus)

D5ASL9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus), Rhodobacter capsulatus (species)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 1086/1281 [03:22<00:36,  5.33it/s]

A0A4U1JNL6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus)

M0MDP9
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Halococcaceae (family), Halococcus (genus), Halococcus saccharolyticus (species)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 1088/1281 [03:23<00:36,  5.33it/s]

A0A653N397
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus), unclassified Luteimonas (no rank)

A0A2S8GSU9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 1090/1281 [03:23<00:35,  5.32it/s]

A0A097R891
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus), Hafnia alvei (species)

A0A8H7U3I1
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetes incertae sedis (no rank), Polyporales (order), Postiaceae (family), Postia (genus)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 1092/1281 [03:23<00:35,  5.34it/s]

A0A1H1MB73
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Microbacterium (genus)

A0A016XDZ5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Hylemonella (genus), Hylemonella gracilis (species)

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 1094/1281 [03:24<00:35,  5.30it/s]

A0A1B9JHS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

D3PE53
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deferribacterota (phylum), Deferribacteres (class), Deferribacterales (order), Deferribacteraceae (family), Deferribacter (genus), Deferribacter desulfuricans (species)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 1096/1281 [03:24<00:34,  5.31it/s]

A0A9J9BAE8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Paraglaciecola (genus), unclassified Paraglaciecola (no rank)

Q2RM12
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus), Moorella thermoacetica (species)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 1098/1281 [03:25<00:34,  5.32it/s]

A0A3N0AQL8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Adlercreutzia (genus), Adlercreutzia equolifaciens (species), Adlercreutzia equolifaciens subsp. celatus (subspecies)

C5KTM6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Perkinsozoa (phylum), Perkinsea (clade), Perkinsida (order), Perkinsidae (family), Perkinsus (genus), Perkinsus marinus (species)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 1100/1281 [03:25<00:33,  5.32it/s]

M1P5F0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfocapsaceae (family), Desulfocapsa (genus), Desulfocapsa sulfexigens (species)

I1YG38
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Thiotrichales (order), Piscirickettsiaceae (family), Methylophaga (genus)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 1103/1281 [03:26<00:32,  5.54it/s]

A0A660CH85
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Prauserella (genus)

A0A2N7L7C8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Enterovibrio (genus)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 1104/1281 [03:26<00:35,  5.00it/s]

Q5KZZ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Geobacillus (genus), Geobacillus thermoleovorans group (no rank), Geobacillus kaustophilus (species)

M1NZT5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobulbia (class), Desulfobulbales (order), Desulfocapsaceae (family), Desulfocapsa (genus), Desulfocapsa sulfexigens (species)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 1106/1281 [03:26<00:34,  5.05it/s]

A0A225CMT8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus), Clavibacter michiganensis (species)

A0A068NV61
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Armatimonadota (phylum), Fimbriimonadia (class), Fimbriimonadales (order), Fimbriimonadaceae (family), Fimbriimonas (genus), Fimbriimonas ginsengisoli (species)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 1108/1281 [03:27<00:35,  4.90it/s]

H2CJI0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptonema (genus), Leptonema illini (species)

B0DU93
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 1110/1281 [03:27<00:34,  5.00it/s]

Q221S8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Rhodoferax (genus), Rhodoferax ferrireducens (species)

F4Y3C5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Oscillatoriales (order), Oscillatoriaceae (family), Moorena (genus), Moorena producens (species)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 1112/1281 [03:27<00:33,  5.08it/s]

Q94CJ2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

M0D3Q9
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloarculaceae (family), Halosimplex (genus), Halosimplex carlsbadense (species)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 1114/1281 [03:28<00:32,  5.09it/s]

A0A3P2A7W8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Neisseriaceae (family), Conchiformibius (genus)

C0GKN4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Dethiobacteria (class), Dethiobacterales (order), Dethiobacteraceae (family), Dethiobacter (genus), Dethiobacter alkaliphilus (species)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 1117/1281 [03:28<00:32,  5.00it/s]

Q7T3R4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Actinopterygii (superclass), Actinopteri (class), Neopterygii (subclass), Teleostei (infraclass), Osteoglossocephalai (clade), Clupeocephala (no rank), Euteleosteomorpha (cohort), Neoteleostei (clade), Eurypterygia (clade), Ctenosquamata (clade), Acanthomorphata (clade), Euacanthomorphacea (clade), Percomorphaceae (clade), Eupercaria (clade), Tetraodontiformes (order), Tetraodontoidei (suborder), Tetradontoidea (superfamily), Tetraodontidae (family), Takifugu (genus)

A0A562USB9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Sphingomonadales (order), Erythrobacteraceae (family), Altererythrobacter (genus)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 1119/1281 [03:29<00:30,  5.30it/s]

A2SS52
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanocorpusculaceae (family), Methanocorpusculum (genus), Methanocorpusculum labreanum (species)

A0A211ZGL5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Rhodospirillaceae (family), Inquilinus (genus)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 1120/1281 [03:29<00:33,  4.79it/s]

A0A4V3ALP8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus)

A0A147GP06
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Pseudacidovorax (genus)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 1122/1281 [03:29<00:31,  5.01it/s]

H2IZ00
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Yersiniaceae (family), Rahnella (genus), Rahnella aquatilis (species)

Q45HK8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Oxalobacteraceae (family), Herbaspirillum (genus)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 1124/1281 [03:30<00:30,  5.12it/s]

A0A6C8LST1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Salmonella (genus), Salmonella enterica (species), Salmonella enterica I (subspecies)

A0A257T8W6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 1126/1281 [03:30<00:29,  5.19it/s]

Q5P470
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Rhodocyclales (order), Rhodocyclaceae (family), Aromatoleum (genus), Aromatoleum aromaticum (species)

I5AZQ4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfobacteraceae (family), Desulfobacter (genus), Desulfobacter postgatei (species)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 1128/1281 [03:31<00:29,  5.23it/s]

Q07UM1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

E5B358
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Erwiniaceae (family), Erwinia (genus), Erwinia amylovora (species)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 1130/1281 [03:31<00:28,  5.30it/s]

A0A1Y4L5P0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Butyricicoccaceae (family), Butyricicoccus (genus)

Q3AFY9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Thermoanaerobacterales (order), Thermoanaerobacteraceae (family), Carboxydothermus (genus), Carboxydothermus hydrogenoformans (species)

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 1132/1281 [03:31<00:27,  5.33it/s]

B0BZN3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Acaryochloridales (order), Acaryochloridaceae (family), Acaryochloris (genus), Acaryochloris marina (species)

A0A1Q2C7H7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Lachnospirales (order), Lachnospiraceae (family), Anaerostipes (genus)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 1134/1281 [03:32<00:27,  5.36it/s]

A0A4R5U5V1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus)

H6LKX6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Eubacteriaceae (family), Acetobacterium (genus), Acetobacterium woodii (species)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 1136/1281 [03:32<00:27,  5.36it/s]

A0A1Y0UZX2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

F6BEI0
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Methanomada group (clade), Methanococci (class), Methanococcales (order), Methanocaldococcaceae (family), Methanotorris (genus), Methanotorris igneus (species)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 1138/1281 [03:32<00:26,  5.35it/s]

M9RKT6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Octadecabacter (genus), Octadecabacter arcticus (species)

A7SGD4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 1140/1281 [03:33<00:26,  5.34it/s]

A0A257TE48
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

R1FI09
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Haptista (clade), Haptophyta (phylum), Prymnesiophyceae (clade), Isochrysidales (order), Noelaerhabdaceae (family), Emiliania (genus)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 1142/1281 [03:33<00:25,  5.35it/s]

E4N1T5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Kitasatosporales (order), Streptomycetaceae (family), Kitasatospora (genus), Kitasatospora setae (species)

U1PIR6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloquadratum (genus), Haloquadratum walsbyi (species)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 1144/1281 [03:34<00:25,  5.35it/s]

F2JYR9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Marinomonas (genus), Marinomonas mediterranea (species)

Q84KJ7
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Streptophyta (phylum), Streptophytina (subphylum), Embryophyta (clade), Tracheophyta (clade), Euphyllophyta (clade), Spermatophyta (clade), Magnoliopsida (class), Mesangiospermae (clade), Liliopsida (clade), Petrosaviidae (subclass), commelinids (clade), Poales (order), Poaceae (family), BOP clade (clade), Oryzoideae (subfamily), Oryzeae (tribe), Oryzinae (subtribe), Oryza (genus), Oryza sativa (species)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 1146/1281 [03:34<00:25,  5.35it/s]

A0A2S8FTB5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Blastopirellula (genus)

D2R647
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Pirellula (genus), Pirellula staleyi (species)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 1148/1281 [03:34<00:24,  5.36it/s]

G9Y5B0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus), Hafnia alvei (species)

A0A144NLT9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 1150/1281 [03:35<00:24,  5.38it/s]

A0A5J6WQU1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Moritellaceae (family), Moritella (genus), Moritella marina (species)

D2R355
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Pirellula (genus), Pirellula staleyi (species)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 1152/1281 [03:35<00:24,  5.36it/s]

F3ZYD6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Thermoanaerobacterales (order), Thermoanaerobacterales Family IV. Incertae Sedis (family), Mahella (genus), Mahella australiensis (species)

B0SL05
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Spirochaetota (phylum), Spirochaetia (class), Leptospirales (order), Leptospiraceae (family), Leptospira (genus), Leptospira biflexa (species), Leptospira biflexa serovar Patoc (no rank)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 1154/1281 [03:35<00:23,  5.39it/s]

A0A5A7MAJ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Comamonadaceae (family), Comamonas (genus)

A0A977NL43
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Thermoproteati (kingdom), Nitrososphaerota (phylum), Nitrososphaeria (class), Nitrososphaerales (order), Nitrososphaeraceae (family), Nitrososphaera (genus)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 1156/1281 [03:36<00:23,  5.35it/s]

A0A433ZQ80
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Morganella (genus)

A0A1Y0V4A5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 1158/1281 [03:36<00:23,  5.35it/s]

A0A1M7UEG2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Geodermatophilales (order), Geodermatophilaceae (family), Geodermatophilus (genus)

G8R7U9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Owenweeksiaceae (family), Owenweeksia (genus), Owenweeksia hongkongensis (species)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 1160/1281 [03:37<00:22,  5.37it/s]

K1LDP0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Cyclobacteriaceae (family), Cecembia (genus), Cecembia lonarensis (species)

B7G0Y4
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Bacillariophyta (phylum), Bacillariophyceae (class), Bacillariophycidae (clade), Naviculales (order), Phaeodactylaceae (family), Phaeodactylum (genus), Phaeodactylum tricornutum (species)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 1162/1281 [03:37<00:22,  5.35it/s]

A0A2W4ZXC0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bdellovibrionota (phylum), Bdellovibrionia (class), Bdellovibrionales (order), Pseudobdellovibrionaceae (family), Micavibrio (genus)

B3PF77
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Cellvibrionales (order), Cellvibrionaceae (family), Cellvibrio (genus), Cellvibrio japonicus (species)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 1164/1281 [03:37<00:21,  5.37it/s]

Q2KZK9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Alcaligenaceae (family), Bordetella (genus), Bordetella avium (species)

Q18ES8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Haloquadratum (genus), Haloquadratum walsbyi (species)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 1166/1281 [03:38<00:21,  5.38it/s]

D3F545
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Thermoleophilia (class), Solirubrobacterales (order), Conexibacteraceae (family), Conexibacter (genus), Conexibacter woesei (species)

B4S394
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Chlorobiota (phylum), Chlorobiia (class), Chlorobiales (order), Chlorobiaceae (family), Prosthecochloris (genus), Prosthecochloris aestuarii (species)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 1168/1281 [03:38<00:21,  5.37it/s]

Q1Q357
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Candidatus Brocadiia (class), Candidatus Brocadiales (order), Candidatus Brocadiaceae (family), Candidatus Kuenenia (genus)

Q9H310
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Sarcopterygii (superclass), Dipnotetrapodomorpha (clade), Tetrapoda (clade), Amniota (clade), Mammalia (class), Theria (clade), Eutheria (clade), Boreoeutheria (clade), Euarchontoglires (superorder), Primates (order), Haplorrhini (suborder), Simiiformes (infraorder), Catarrhini (parvorder), Hominoidea (superfamily), Hominidae (family), Homininae (subfamily), Homo (genus)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 1170/1281 [03:38<00:20,  5.39it/s]

D3PKL4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deinococcota (phylum), Deinococci (class), Thermales (order), Thermaceae (family), Meiothermus (genus), Meiothermus ruber (species)

M5SY07
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), unclassified Rhodopirellula (no rank)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 1172/1281 [03:39<00:20,  5.40it/s]

Q8RUT6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

A7NKH2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Chloroflexia (class), Chloroflexales (order), Roseiflexineae (suborder), Roseiflexaceae (family), Roseiflexus (genus), Roseiflexus castenholzii (species)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 1174/1281 [03:39<00:19,  5.40it/s]

Q1Q879
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Psychrobacter (genus), Psychrobacter cryohalolentis (species)

A0A1B9M5B8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Orbales (order), Orbaceae (family), Gilliamella (genus)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 1176/1281 [03:39<00:19,  5.40it/s]

A6LRS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Eubacteriales (order), Clostridiaceae (family), Clostridium (genus), Clostridium beijerinckii (species)

J2ZGN6
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Halobacteria (class), Halobacteriales (order), Haloferacaceae (family), Halogranum (genus), Halogranum rubrum (species)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 1178/1281 [03:40<00:19,  5.41it/s]

V5E0F3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methyloglobulus (genus), Methyloglobulus morosus (species)

A0A149RQX0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 1180/1281 [03:40<00:18,  5.42it/s]

A0A165BP25
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Kosakonia (genus)

C0QSY0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Aquificota (phylum), Aquificia (class), Aquificales (order), Hydrogenothermaceae (family), Persephonella (genus), Persephonella marina (species)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 1182/1281 [03:41<00:18,  5.43it/s]

B0XVV6
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus fumigatus (species)

E0SD83
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Dickeya (genus), Dickeya dadantii (species)

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 1184/1281 [03:41<00:17,  5.42it/s]

A8HSA2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

A0A1E3PSK5
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Dipodascomycetes (class), Dipodascales (order), Dipodascales incertae sedis (no rank), Nadsonia (genus), Nadsonia fulvescens (species), Nadsonia fulvescens var. elongata (varietas)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 1186/1281 [03:41<00:17,  5.41it/s]

A5DYQ2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Debaryomycetaceae (family), Candida/Lodderomyces clade (clade), Lodderomyces (genus), Lodderomyces elongisporus (species)

A0A4U1K1W1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 1188/1281 [03:42<00:17,  5.43it/s]

Q0AT01
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Maricaulales (order), Maricaulaceae (family), Maricaulis (genus), Maricaulis maris (species)

A4FMG0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Saccharopolyspora (genus), Saccharopolyspora erythraea (species)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 1190/1281 [03:42<00:16,  5.44it/s]

C3YB73
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Cephalochordata (subphylum), Leptocardii (class), Amphioxiformes (order), Branchiostomatidae (family), Branchiostoma (genus)

A0A9P3CXY2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Moraxellales (order), Moraxellaceae (family), Acinetobacter (genus), Acinetobacter calcoaceticus/baumannii complex (no rank), Acinetobacter baumannii (species)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 1192/1281 [03:42<00:16,  5.42it/s]

A0A0L8BVU4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Sinorhizobium/Ensifer group (no rank), Ensifer (genus)

A0A401WUW1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus), Acetobacter pasteurianus (species)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 1194/1281 [03:43<00:16,  5.39it/s]

I4C9L2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfomonilia (class), Desulfomonilales (order), Desulfomonilaceae (family), Desulfomonile (genus), Desulfomonile tiedjei (species)

Q8RUE9
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 1196/1281 [03:43<00:15,  5.40it/s]

F0JGZ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Pseudodesulfovibrio (genus)

A0A2I0UUY1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Lysinibacillus (genus)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 1198/1281 [03:44<00:15,  5.39it/s]

A0A542XGT4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micromonosporales (order), Micromonosporaceae (family), Salinispora (genus)

G0JRH4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus), Acidithiobacillus ferrivorans (species)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 1200/1281 [03:44<00:15,  5.37it/s]

A2SPS8
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Stenosarchaea group (clade), Methanomicrobia (class), Methanomicrobiales (order), Methanocorpusculaceae (family), Methanocorpusculum (genus), Methanocorpusculum labreanum (species)

A0A5M4AWD2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Bacteroidia (class), Marinilabiliales (order), Prolixibacteraceae (family), Prolixibacter (genus)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 1202/1281 [03:44<00:14,  5.37it/s]

Q6QH01
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), core chlorophytes (clade), Chlorophyceae (class), CS clade (clade), Chlamydomonadales (order), Chlamydomonadaceae (family), Chlamydomonas (genus)

D3F0Z1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Thermoleophilia (class), Solirubrobacterales (order), Conexibacteraceae (family), Conexibacter (genus), Conexibacter woesei (species)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 1204/1281 [03:45<00:14,  5.33it/s]

A6XBM2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Bilateria (clade), Deuterostomia (clade), Chordata (phylum), Craniata (subphylum), Vertebrata (clade), Gnathostomata (clade), Teleostomi (clade), Euteleostomi (clade), Actinopterygii (superclass), Actinopteri (class), Neopterygii (subclass), Teleostei (infraclass), Osteoglossocephalai (clade), Clupeocephala (no rank), Euteleosteomorpha (cohort), Neoteleostei (clade), Eurypterygia (clade), Ctenosquamata (clade), Acanthomorphata (clade), Euacanthomorphacea (clade), Percomorphaceae (clade), Ovalentaria (clade), Atherinomorphae (superorder), Cyprinodontiformes (order), Aplocheiloidei (suborder), Rivulidae (family), Kryptolebias (genus)

D6E7B3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Coriobacteriia (class), Eggerthellales (order), Eggerthellaceae (family), Gordonibacter (genus), Gordonibacter pamelaeae (species)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 1206/1281 [03:45<00:14,  5.32it/s]

Q13E03
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

A0A060URB8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Acidithiobacillia (class), Acidithiobacillales (order), Acidithiobacillaceae (family), Acidithiobacillus (genus)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 1208/1281 [03:45<00:13,  5.36it/s]

A0A2T1N7R1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Mesoflavibacter (genus), Mesoflavibacter zeaxanthinifaciens (species)

D6TCH6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Chloroflexota (phylum), Ktedonobacteria (class), Ktedonobacterales (order), Ktedonobacteraceae (family), Ktedonobacter (genus), Ktedonobacter racemifer (species)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 1210/1281 [03:46<00:13,  5.38it/s]

B0CXH8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Basidiomycota (phylum), Agaricomycotina (subphylum), Agaricomycetes (class), Agaricomycetidae (subclass), Agaricales (order), Agaricineae (suborder), Hydnangiaceae (family), Laccaria (genus), Laccaria bicolor (species)

A3TVQ9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Paracoccaceae (family), Pseudooceanicola (genus), Pseudooceanicola batsensis (species)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 1212/1281 [03:46<00:12,  5.38it/s]

Q4WT12
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus fumigatus (species)

C7QGX3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Catenulisporales (order), Catenulisporaceae (family), Catenulispora (genus), Catenulispora acidiphila (species)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 1214/1281 [03:47<00:12,  5.38it/s]

F0Y9X3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Stramenopiles (clade), Ochrophyta (clade), Pelagophyceae (class), Pelagomonadales (order), Pelagomonadaceae (family), Aureococcus (genus)

A0A7S0D560
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Viridiplantae (kingdom), Chlorophyta (phylum), Mamiellophyceae (class), Mamiellales (order), Mamiellaceae (family), Micromonas (genus)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1216/1281 [03:47<00:12,  5.36it/s]

A0A160KTE9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Rathayibacter (genus)

A0A2H1HV86
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Brevibacteriaceae (family), Brevibacterium (genus), Brevibacterium linens (species)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 1218/1281 [03:47<00:11,  5.34it/s]

A0A251Y3N4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Clavibacter (genus)

A0A419AVL2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Pectobacteriaceae (family), Pectobacterium (genus)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 1220/1281 [03:48<00:11,  5.19it/s]

A0A4Q2QWS1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank), unclassified Enterobacter cloacae complex (no rank)

C7Q1E4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Catenulisporales (order), Catenulisporaceae (family), Catenulispora (genus), Catenulispora acidiphila (species)

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 1222/1281 [03:48<00:11,  5.23it/s]

A0A5C5TYS5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Lysobacterales (order), Lysobacteraceae (family), Luteimonas (genus)

F2NNQ0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Deinococcota (phylum), Deinococci (class), Thermales (order), Thermaceae (family), Marinithermus (genus), Marinithermus hydrothermalis (species)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 1224/1281 [03:48<00:10,  5.24it/s]

A0A2R4TRE0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Aeromonadales (order), Aeromonadaceae (family), Aeromonas (genus), Aeromonas hydrophila (species)

K9YJQ3
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Geminocystaceae (family), Cyanobacterium (genus), Cyanobacterium stanieri (species)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 1226/1281 [03:49<00:10,  5.27it/s]

D9QS43
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Halanaerobiales (order), Halobacteroidaceae (family), Acetohalobium (genus), Acetohalobium arabaticum (species)

A7SQ16
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 1228/1281 [03:49<00:10,  5.28it/s]

A1DG05
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Eurotiales (order), Aspergillaceae (family), Aspergillus (genus), Aspergillus subgen. Fumigati (subgenus), Aspergillus fischeri (species)

U1SIR9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Bifidobacteriales (order), Bifidobacteriaceae (family), Alloscardovia (genus), Alloscardovia omnicolens (species)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 1230/1281 [03:50<00:09,  5.30it/s]

C4Y298
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Saccharomycotina (subphylum), Pichiomycetes (class), Serinales (order), Metschnikowiaceae (family), Clavispora (genus), Clavispora lusitaniae (species)

A0A9W3LFI9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), Enterobacter cloacae complex (no rank), Enterobacter cloacae (species)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 1232/1281 [03:50<00:09,  5.30it/s]

D3RMV7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Chromatiaceae (family), Allochromatium (genus), Allochromatium vinosum (species)

F3QNA7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Burkholderiales (order), Sutterellaceae (family), Parasutterella (genus), Parasutterella excrementihominis (species)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 1234/1281 [03:50<00:08,  5.31it/s]

E4RTK5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Cytophagia (class), Cytophagales (order), Leadbetterellaceae (family), Leadbetterella (genus), Leadbetterella byssophila (species)

C8XBX8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Nakamurellales (order), Nakamurellaceae (family), Nakamurella (genus), Nakamurella multipartita (species)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 1236/1281 [03:51<00:08,  5.31it/s]

C0QTA4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Aquificota (phylum), Aquificia (class), Aquificales (order), Hydrogenothermaceae (family), Persephonella (genus), Persephonella marina (species)

E6VIW4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus), Rhodopseudomonas palustris (species)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 1238/1281 [03:51<00:08,  5.32it/s]

A0A2S6H643
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus)

Q46HB1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 1240/1281 [03:51<00:07,  5.36it/s]

A0A2S5CTX8
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Bacilli (class), Bacillales (order), Bacillaceae (family), Lysinibacillus (genus)

A0A1T4SF40
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Hyphomicrobiales incertae sedis (no rank), Enhydrobacter (genus)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 1242/1281 [03:52<00:07,  5.35it/s]

K0K7J4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Pseudonocardiales (order), Pseudonocardiaceae (family), Saccharothrix (genus), Saccharothrix espanaensis (species)

A0A1J5JH24
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Bacillota (phylum), Clostridia (class), Moorellales (order), Moorellaceae (family), Moorella (genus)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 1244/1281 [03:52<00:06,  5.34it/s]

Q6LMI6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Vibrionales (order), Vibrionaceae (family), Photobacterium (genus), Photobacterium profundum (species)

A0A9W5JBA9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Enterobacteriaceae (family), Enterobacter (genus), unclassified Enterobacter (no rank)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 1246/1281 [03:53<00:06,  5.36it/s]

A0A291PMC6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodospirillales (order), Acetobacteraceae (family), Acetobacter (genus)

A0A4Y4DZN4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Promicromonosporaceae (family), Cellulosimicrobium (genus)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 1248/1281 [03:53<00:06,  5.35it/s]

A0A2R4MBA2
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Devosiaceae (family), Maritalea (genus)

R9PI53
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Alteromonadales (order), Alteromonadaceae (family), Agarivorans (genus), Agarivorans albus (species)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 1250/1281 [03:53<00:05,  5.35it/s]

A0A6H9GLV4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

A0A7S4GND2
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Oxyrrhinales (order), Oxyrrhinaceae (family), Oxyrrhis (genus)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 1252/1281 [03:54<00:05,  5.36it/s]

A0A6H9FPY5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Oscillatoriophycideae (subclass), Chroococcales (order), Microcystaceae (family), Microcystis (genus), Microcystis aeruginosa (species)

A0A1G7DX68
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Rhodobacter group (no rank), Rhodobacter (genus)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 1254/1281 [03:54<00:05,  5.34it/s]

A0A075WEB4
Taxonomic lineage
cellular organisms (no rank), Archaea (superkingdom), Methanobacteriati (kingdom), Methanobacteriota (phylum), Archaeoglobi (class), Archaeoglobales (order), Archaeoglobaceae (family), Archaeoglobus (genus), Archaeoglobus fulgidus (species)

A0A140NHJ5
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Morganellaceae (family), Providencia (genus), Providencia stuartii (species)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 1256/1281 [03:54<00:04,  5.34it/s]

A0A1C6Z081
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Hafnia (genus)

Q5FA36
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Betaproteobacteria (class), Neisseriales (order), Neisseriaceae (family), Neisseria (genus), Neisseria gonorrhoeae (species)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 1258/1281 [03:55<00:04,  5.28it/s]

Q0ACK1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Chromatiales (order), Ectothiorhodospiraceae (family), Alkalilimnicola (genus), Alkalilimnicola ehrlichii (species)

A0A975GIX9
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfobacteria (class), Desulfobacterales (order), Desulfococcaceae (family), Desulfonema (genus)

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 1260/1281 [03:55<00:04,  5.23it/s]

A0A323UE08
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Nitrobacteraceae (family), Rhodopseudomonas (genus)

U7VB41
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Fusobacteriota (phylum), Fusobacteriia (class), Fusobacteriales (order), Fusobacteriaceae (family), Cetobacterium (genus), Cetobacterium somerae (species)

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 1262/1281 [03:56<00:03,  5.26it/s]

A0A063Y780
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Oceanospirillales (order), Oceanospirillaceae (family), Nitrincola (genus)

C5CIT6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermotogota (phylum), Thermotogae (class), Kosmotogales (order), Kosmotogaceae (family), Kosmotoga (genus), Kosmotoga olearia (species)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 1264/1281 [03:56<00:03,  5.22it/s]

A0A0A2VPU3
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Hypocreomycetidae (subclass), Hypocreales (order), Cordycipitaceae (family), Beauveria (genus), Beauveria bassiana (species)

F0RHS0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Flavobacteriia (class), Flavobacteriales (order), Flavobacteriaceae (family), Cellulophaga (genus), Cellulophaga lytica (species)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 1266/1281 [03:56<00:02,  5.15it/s]

A0A2S5WX34
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Microbacteriaceae (family), Pseudoclavibacter (genus), unclassified Pseudoclavibacter (no rank)

C1G973
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), Eurotiomycetes (class), Eurotiomycetidae (subclass), Onygenales (order), Ajellomycetaceae (family), Paracoccidioides (genus), Paracoccidioides brasiliensis (species)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 1268/1281 [03:57<00:02,  5.18it/s]

A0A2S6GKF6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Methylococcales (order), Methylococcaceae (family), Methylobacter (genus)

A0A0A2B651
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Cyanobacteriota/Melainabacteria group (clade), Cyanobacteriota (phylum), Cyanophyceae (class), Synechococcales (order), Prochlorococcaceae (family), Prochlorococcus (genus), Prochlorococcus marinus (species)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1270/1281 [03:57<00:02,  5.21it/s]

A0A4R3A5P7
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Hyphomicrobiales (order), Rhizobiaceae (family), Rhizobium/Agrobacterium group (no rank), Neorhizobium (genus), unclassified Neorhizobium (no rank)

A0A2A7U6W1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Gammaproteobacteria (class), Enterobacterales (order), Hafniaceae (family), Edwardsiella (genus)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 1272/1281 [03:58<00:01,  5.26it/s]

Q2GX26
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Fungi (kingdom), Dikarya (subkingdom), Ascomycota (phylum), saccharomyceta (clade), Pezizomycotina (subphylum), leotiomyceta (clade), sordariomyceta (clade), Sordariomycetes (class), Sordariomycetidae (subclass), Sordariales (order), Chaetomiaceae (family), Chaetomium (genus), Chaetomium globosum (species)

F5XN43
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Propionibacteriales (order), Propionibacteriaceae (family), Microlunatus (genus), Microlunatus phosphovorus (species)

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 1274/1281 [03:58<00:01,  5.29it/s]

A0A0K2STH0
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Sar (clade), Alveolata (clade), Dinophyceae (class), Gonyaulacales (order), Pyrocystaceae (family), Alexandrium (genus)

A0A1H1U2Q6
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Micrococcales (order), Cellulomonadaceae (family), Paraoerskovia (genus)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1276/1281 [03:58<00:00,  5.30it/s]

A7SED8
Taxonomic lineage
cellular organisms (no rank), Eukaryota (superkingdom), Opisthokonta (clade), Metazoa (kingdom), Eumetazoa (clade), Cnidaria (phylum), Anthozoa (class), Hexacorallia (subclass), Actiniaria (order), Edwardsiidae (family), Nematostella (genus)

A0LV78
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Bacillati (kingdom), Actinomycetota (phylum), Actinomycetes (class), Acidothermales (order), Acidothermaceae (family), Acidothermus (genus), Acidothermus cellulolyticus (species)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 1278/1281 [03:59<00:00,  5.29it/s]

K5DBA0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), PVC group (clade), Planctomycetota (phylum), Planctomycetia (class), Pirellulales (order), Pirellulaceae (family), Rhodopirellula (genus), Rhodopirellula baltica (species)

B8IZX4
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Thermodesulfobacteriota (phylum), Desulfovibrionia (class), Desulfovibrionales (order), Desulfovibrionaceae (family), Desulfovibrio (genus), Desulfovibrio desulfuricans (species)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1281/1281 [03:59<00:00,  5.35it/s]

A8LKQ0
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), Pseudomonadota (phylum), Alphaproteobacteria (class), Rhodobacterales (order), Roseobacteraceae (family), Dinoroseobacter (genus), Dinoroseobacter shibae (species)

A0A5C6LWQ1
Taxonomic lineage
cellular organisms (no rank), Bacteria (superkingdom), FCB group (clade), Bacteroidota/Chlorobiota group (clade), Bacteroidota (phylum), Chitinophagia (class), Chitinophagales (order), Chitinophagaceae (family), Chitinophaga (genus)

In [114]:
phylum1 = []
phylum2 = []
together = []
kingdo = []

for items in linige:
    if "(phylum)" in items:
        first = items.split(' (phylum)')[0]
        second = first.split(' ')[-1]
        third = first.split(':')[0]
        # fir = items.split(' (superkingdom)')[0]
        # sec = fir.split(' ')[-1]
        
                    
        phylum1.append(third)
        phylum2.append(second)
        together.append(f"{third}: {second}")
        # kingdo.append(f"{sec} {second}")
dicphyl = dict(zip(phylum1, phylum2))

In [115]:
phylum_set = set(phylum2)
phylum_set

{'Acidobacteriota',
 'Actinomycetota',
 'Aquificota',
 'Armatimonadota',
 'Arthropoda',
 'Ascomycota',
 'Bacillariophyta',
 'Bacillota',
 'Bacteroidota',
 'Basidiomycota',
 'Bdellovibrionota',
 'Blastocladiomycota',
 'Calditrichota',
 'Campylobacterota',
 'Chlorobiota',
 'Chloroflexota',
 'Chlorophyta',
 'Chordata',
 'Chrysiogenota',
 'Chytridiomycota',
 'Cnidaria',
 'Cyanobacteriota',
 'Deferribacterota',
 'Deinococcota',
 'Discosea',
 'Evosea',
 'Fibrobacterota',
 'Fusobacteriota',
 'Gemmatimonadota',
 'Haptophyta',
 'Heterolobosea',
 'Ignavibacteriota',
 'Lentisphaerota',
 'Methanobacteriota',
 'Mollusca',
 'Myxococcota',
 'Nematoda',
 'Nitrososphaerota',
 'Nitrospirota',
 'Perkinsozoa',
 'Planctomycetota',
 'Pseudomonadota',
 'Rhodophyta',
 'Rhodothermota',
 'Spirochaetota',
 'Streptophyta',
 'Thermodesulfobacteriota',
 'Thermoplasmatota',
 'Thermoproteota',
 'Thermotogota',
 'Verrucomicrobiota',
 'Zoopagomycota'}

In [121]:
df2['Phyla'] = df2[0].map(dicphyl)

In [122]:
df2

,0,four,first,PheGate,TwinHis,SN,kingdom,Phyla
0,A0A858ZNJ3,YNSVAV,Y,FF,HH,S,Bacteria,Pseudomonadota
1,A0A1H9M798,YNNTAV,Y,FF,HH,S,Bacteria,Pseudomonadota
2,B0DY50,YNSMMV,Y,FF,HH,S,Eukaryota,Basidiomycota
3,P69680,YNSMGV,Y,FF,HH,S,Bacteria,Pseudomonadota
4,A0A3G9G4Q4,YNATAT,Y,FF,HH,S,Bacteria,Pseudomonadota
...,...,...,...,...,...,...,...,...
1276,A0LV78,YNAMAT,Y,FF,HH,S,Bacteria,Actinomycetota
1277,K5DBA0,ENDLTS,E,FF,HH,N,Bacteria,Planctomycetota
1278,B8IZX4,YRSTAS,Y,FF,HH,S,Bacteria,Thermodesulfobacteriota
1279,A8LKQ0,ENLYSS,E,FF,HH,N,Bacteria,Pseudomonadota
1280,A0A5C6LWQ1,YNSTAV,Y,FF,HH,I,Bacteria,Bacteroidota

In [123]:
class1 = []
class2 = []
classtog = []


for items in linige:
    if "(class)" in items:
        first = items.split(' (class)')[0]
        second = first.split(' ')[-1]
        third = first.split(':')[0]
        # fir = items.split(' (superkingdom)')[0]
        # sec = fir.split(' ')[-1]
        
                    
        class1.append(third)
        class2.append(second)
        classtog.append(f"{third}: {second}")
        # kingdo.append(f"{sec} {second}")
dicclass = dict(zip(class1, class2))

In [35]:
df['Phyla'] = df['0'].map(dicphyl)

In [124]:
df2['Class'] = df2[0].map(dicclass)

In [144]:
df2

,0,four,first,PheGate,TwinHis,SN,kingdom,Phyla,Class,EDG
0,A0A858ZNJ3,YNSVAV,Y,FF,HH,S,Bacteria,Pseudomonadota,Betaproteobacteria,E
1,A0A1H9M798,YNNTAV,Y,FF,HH,S,Bacteria,Pseudomonadota,Betaproteobacteria,E
2,B0DY50,YNSMMV,Y,FF,HH,S,Eukaryota,Basidiomycota,Agaricomycetes,E
3,P69680,YNSMGV,Y,FF,HH,S,Bacteria,Pseudomonadota,Gammaproteobacteria,E
4,A0A3G9G4Q4,YNATAT,Y,FF,HH,S,Bacteria,Pseudomonadota,Alphaproteobacteria,E
...,...,...,...,...,...,...,...,...,...,...
1276,A0LV78,YNAMAT,Y,FF,HH,S,Bacteria,Actinomycetota,Actinomycetes,D
1277,K5DBA0,ENDLTS,E,FF,HH,N,Bacteria,Planctomycetota,Planctomycetia,G
1278,B8IZX4,YRSTAS,Y,FF,HH,S,Bacteria,Thermodesulfobacteriota,Desulfovibrionia,E
1279,A8LKQ0,ENLYSS,E,FF,HH,N,Bacteria,Pseudomonadota,Alphaproteobacteria,E
1280,A0A5C6LWQ1,YNSTAV,Y,FF,HH,I,Bacteria,Bacteroidota,Chitinophagia,E

In [139]:
df2.to_csv('all_annotations.csv')

In [127]:
pocket = set(df2['four'].to_list())

In [132]:
len(pocket)

275

In [131]:
from collections import Counter

starts_with = [item[0] for item in pocket if item[0] in {'E', 'Y', 'C', 'M'}]
counts = Counter(starts_with)
print(counts)

Counter({'Y': 181, 'E': 70, 'M': 7, 'C': 4})

In [39]:
hishis  = set(df['TwinHis'].to_list())

In [40]:
hishis

{'#NAME?', 'EH', 'H-', 'HH'}

In [41]:
phephe  = set(df['PheGate'].to_list())

In [140]:
edg = set(df2['EDG'].to_list())

In [141]:
edg

{'-', 'A', 'D', 'E', 'G', 'N', 'S', 'T'}

In [142]:
ssnn = set(df2['SN'].to_list())

In [143]:
ssnn

{'A', 'C', 'D', 'F', 'I', 'M', 'N', 'Q', 'R', 'S', 'T', 'V'}